### ISSUE TITLE
CLEAFI (RFP Application)

### ISSUE THREAD

**Issue by 1Busayo** [filecoin-project/devgrants#1004]
CLEAFI # RFP Proposal: `CLEAFI`

**CLEAFI:**

**Link to RFP:** https://filecoin.io/blog/posts/filecoin-green-s-1-million-green-grants-program-will-support-climate-positive-regenerative-finance-refi-initiatives/

**RFP Category:** `app-dev` , `Filecoin Green`  

**Proposer:**  [Samuel Fanimokun](https://github.com/1Busayo)

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Please respond with either "Yes" or "No"

Yes I agree to make my work an open source

# Project Description

Please describe what problem or need your project addresses, why it's important, and your technical approach. Since this is a response to an RFP, make sure to address the request directly.

>   The Recycle rate around the world is dropping daily which enables more carbon emissions across the globe.
>    We can use web3  to create a  legal and traceable work of recycling  which will enable us to support more recyclers around the world to do more
>    Images uploaded by recyclers would be converted to NFTs which can help in generating money to recycle more and also link recyclers to businesses interested in buying recycled materials

## How we are  planning to measure and verify the amount of recycling

 We would use the existing measuring tools used in the recycling centers and also take down records for verification purposes

## When the project gets too big for you to verify the recycling

we would have verified field agents who go to the recycling site for inspection

## Plan to reach out to recycling centers 
 With the help of the recyclers association in Nigeria, I would be able to visit serval recycling centers

## Recycle Type

We would start with  Plastic  recycle  then later  support other types of recycling as we expand

## Target Customers
 People who are intrested in donating or buying from the recyclers

## Plan to get people to be interested in donating to recycling
Create webinars and seminars to explain or educate how recycling can help to reduce carbon emissions and make the environment more green

## How we help recyclers
Sell the recycler materials to companies in need of them and also use their NFT to raise funds for individuals interested in supporting recycling

## Milestone Summary

The purpose of the research is to see how the current method can be adapted with web3 and  also how to onboard recyclers to adopt new ways on how they can get supported in recycling more

| Milestone No. | Milestone Summary & Staffing    | Funding          | Estimated Timeframe                  |
| -------------  | ———————————————-----| ------------- | -------------------------------- |
| 1                     | Research                                        | $10,000         |     4 weeks  01/10/22 -31/10/22    |

## Total Budget Requested

$10,000

## Development Roadmap

Launch on Testnet - Completed
Developed an MVP on Ethereum testnet

Promote CLEAFI Community - Pending
Grow CLEAFI Community to collect feedback and improve the current system developed on testnet

Launch on Mainnet - Pending
Migrate the MVP solution from Ethereum testnet to mainnet

## Maintenance and Upgrade Plans

After the launch, we would be able to maintain the project from commissions of NFT sales and recycled materials sold which would help us pay for hosting and managing staff. We would also build mobile dapps or apps once we have up to 1000 recyclers on the CLEAFI web3 platform

# Team
[Samuel Fanimokun](https://github.com/1Busayo)
## Contact Info
info@cleafi.com
fanimokunbusayo@gmail.com

Provide us with a way to contact you (email is probably the easiest). You can also email grants@filecoin.org with your GH username and link to your public proposal.

## Team Members

- Team Member 1 - https://github.com/1Busayo

## Team Website

https://cleafi.com

## Relevant Experience

Samuel Fanimokun (Founder): has experience in developing Dapps and smart contracts using
Solidity, Reactjs, and Web3js participated in hackathons like EthGlobal (https://showcase.ethglobal.com/nfthack2022/linke) and also have experience in developing the web3 community
.

## Team code repositories

https://github.com/1Busayo/CLEAFI

# Additional Information
Currently deployed on the Ethereum rinkeby testnet network

Demo link : https://cleafi-8kssqb4y6-1busayo.vercel.app/

Demo Video link: https://youtu.be/kcsQq4v7oOs

**Comment by redransil** [comment]
Hey @1Busayo - thanks for the application! Can you explain to me:
- How do you verify that the person who mints the NFT actually did recycling (say they have pictures of material to recycle but they didn't actually recycle it)
- How do you measure how much material was recycled?

It's really important for the work that we support to be able to measure the impact, and I'm not sure how the project is planning to do that

**Comment by 1Busayo** [comment]
- How do you verify that the person who mints the NFT actually did recycling (say they have pictures of material to recycle but they didn't actually recycle it)

   **Answer**: Every recycler would be verified on our platform, giving us access to visit their recycling site. we would go to the recycling site for inspection before they can upload pictures of recycled material and mint into an NFT.
 
- How do you measure how much material was recycled?
 
    **Answer**: it would be measured in tons, and it would be calculated during the inspection at the recycling site.

**Comment by orinayodele** [comment]
Hi @1Busayo thanks for your answers! We want to give you a $5,000 microgrant for your idea. Could you please fill out [this ](https://github.com/filecoin-project/devgrants/issues/new?assignees=ErinOCon&labels=Micro+Grant&template=microgrant.md&title=%3CYour+Title+Here%3E)template to proceed.

**Comment by 1Busayo** [comment]
Hello @orinayodele  please check  out the [template](https://github.com/filecoin-project/devgrants/issues/1092#issue-1414097084)  you told me to fill. 
Thanks

**Comment by orinayodele** [comment]
Hi @1Busayo we are happy to award you a $5,000 microgrant for this project! We do want to iterate that you must meet with recyclers and document your visits to complete the grants process. The next steps will be communicated to you by next week.

**Comment by 1Busayo** [comment]
ok thanks, @orinayodele I would be expecting  the next steps

**Comment by 1Busayo** [comment]
@orinayodele  This is the link to the microgrant you asked me to create https://github.com/filecoin-project/devgrants/issues/1092

**Comment by realChainLife** [comment]
Thanks @1Busayo closing this proposal so we can process as microgrant!

**Comment by 1Busayo** [comment]
@realChainLife  thanks this is the link to the micro grant
