### ISSUE TITLE
Web3 Domain

### ISSUE THREAD

**Issue by gupta977** [filecoin-project/devgrants#1006]
# Open Grant Proposal: Web3Domain

**Name of Project:**

**Proposal Category:**  integration-adoption

**Proposer:** https://github.com/gupta977

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** YES

# Project Description

We are building Web3 Domain Name which will be used as decentralized identity and to host website over Filecoin.

This domain name are used to create profile including wallet address, social handles, avatar, bank details and many more. 
We are **proud to say that Filecoin helped us** since microgrant and these features are ready to use.

Currently domains are minted only on our website.
We wanted build WordPress plugin so that **anyone able to mint domain on their own website**. 

_For example:_ 
Filecoin registered .fil domain on our website.
Filecoin company will install or use plugins on [filecoin](https://filecoin.io/) and let user to register/mint someone.fil or anything.fil.
This will create trust between users. 
Filecoin will have full controls over .fil domain to set minting price and to prevent public from minting subdomain of .fil domain. 
Minting activities are performed directly with smart contract.

Since, only domain minting is nothing unless data is associated with it.
The data are profile image, webpage, JSON file which are auto generated are _uploaded to Filecoin using IPFS_.
The curl _API of nft.storage_ is used to achieve it. 

Each and every time user updates records, new set of files are created and assigned to the NFT domain. 
In short without Filecoin this project is nothing. 
Thank you for creating such platform for complete web3 solution. 

To visit web3 website and to fetch web3 records we have already created telegram bots & browser extension. Again with the help of Filecoin we did it. 

## Deliverables

Users able to SELL / MINT domain on their web site. 
No need to depend on us for this. 
Open source wordpress plugin code which will be continuously updated as required. 

## Development Roadmap

This project required 4 weeks of time.
As we are working for Wordpress Plugins since last 8 years, we know what to provide for the best service possible. 

## Total Budget Requested

- Milestone 1- We will do everything in single milestone because in middle it is hard to demonstrate or explain the completed part. 
- It will cost us US$12,000. ( We invested $5000 already from our side, so insufficient amount of  $12000 is required)
- We won't add additional cost on it and promise to complete it within the promised amount.
- This software will be free to use and open source. 
- Users no need to purchase any licenses or services from our end. 
- We will keep on updating it with more added features in future.
- We will handover with LIVE working example of .fil domain on dedicated website which will full documentation. Reviewer do not have to give special time for milestone checking. 

## Maintenance and Upgrade Plans

We keep on updating the plugins. 
The updated changes with time can be monitored through Github. 

# Team

## Team Members

Navneet Gupta is leader of the team and rest everyone are freelancers. 

## Team Website

https://web3domain.org/
http://w3d.name/

## Relevant Experience

We are working in web industry since more then a decade. We know the quality need to offer and business practices to promote products in minimum cost but in efficient way. 

## Team code repositories

https://github.com/gupta977

# Additional Information
I learn it since microgrant and after conversation with different team of Filecoin, I feel my self to contribute each possible way for Filecoin ecosystem. 
navneet@odude.com

Thank you.
Navneet Gupta

**Comment by ErinOCon** [comment]
Hi @gupta977, thank you for your proposal! This grant has been approved. We will be in touch by email to discuss next steps.
