### ISSUE TITLE
Next Step Microgrant: <WEB2 SOCIAL MEDIA INTEGRATION T0 WEB3>

### ISSUE THREAD

**Issue by bolajiscott** [filecoin-project/devgrants#1007]
### 1. What is your project? (max 100 words)
The project brings transactions data from standard databases - such as PostgreSQL - to the on-chain space, by leveraging the use of Chainlink API features. Initially, this data will be stored on IPFS and FileCoin's OrbidDB. This way, we can guarantee the security and privacy of the data, giving more control to the web2 users transacting in the web3 space, as he can see at any time which accounts has the end user transactions.
The connection using Chainlink simply enables a more cryptographic-proven management of sensitive data. It can also serve as a platform to improve web3 based transction fees

### 2. Project links
  
[hackathon-neon.vercel.app](http://hackathon-neon.vercel.app/)
https://github.com/mum33n/tronpay

License:

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

   IPFS based OrbitDB is used to store transactions logs  care data which is pulled from relational database like postgres.

  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

 A full fletched smart contract to handle the following scenerios:

1. create a basic userflow of the web app for testing (beta-test)
2. Give users accounts to test with
3. smaller units of tokens are provided for beta testers
4.Build a mobile app for the project.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

YES
  
### 6. Does your proposal comply with our Community Code of Conduct?

YES

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* YES

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Name : bolaji ogidan
* E-mail: bolajiscott@yahoo.com
* Github account: github.com/bolajiscott

   Name : Azeez Mumeen
   E-mail : azeezmumeen6@gmail.com
   Github account : https://github.com/mum33n

* How did you learn about our microgrant program?
   Filecoin & IPFS Hackathons team mail
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @bolajiscott, thank you for your proposal. Is this project related to [this proposal](https://github.com/filecoin-project/devgrants/issues/680)?

**Comment by bolajiscott** [comment]
Yes
    On Wednesday, October 19, 2022 at 09:19:24 PM GMT+1, ErinOCon ***@***.***> wrote:  
 
 


Hi @bolajiscott, thank you for your proposal. Is this project related to this proposal?

**Comment by bolajiscott** [comment]
Hello , just checked up on link referenced to the mail sent earlier , it’s not attached to the proposal .
    On Wednesday, October 19, 2022 at 09:19:24 PM GMT+1, ErinOCon ***@***.***> wrote:  
 
 


Hi @bolajiscott, thank you for your proposal. Is this project related to this proposal?

**Comment by ErinOCon** [comment]
Hi @bolajiscott, thank you for your response. Since much of the language in this application and in your code are similar, can you briefly describe the relationship between the proposals?

**Comment by bolajiscott** [comment]
Hi, My application is social media focused on data storage to allow crypto users perform a seamless transactions without a 3rd party. relationship is based on data storage usability assigned to each social media handlers on the crypto network.    On Friday, November 4, 2022 at 03:46:58 PM GMT+1, ErinOCon ***@***.***> wrote:  
 
 


Hi @bolajiscott, thank you for your response. Since much of the language in this application and in your code are similar, can you briefly describe the relationship between the proposals?

**Comment by ErinOCon** [comment]
Hi @bolajiscott, we will not proceed with a grant for this project at this time. Thank you for your interest in our grants program.
