### ISSUE TITLE
Next Step Microgrant: CooperDB

### ISSUE THREAD

**Issue by IKalonji** [filecoin-project/devgrants#1008]
### 1. What is your project? (max 100 words)

CooperDB is a Relational Database Management as a Service built on top of IPFS/Filecoin.

To onboard more developers into the web3 space we need to provide tools that most developers are familiar with. Relational databases are the most widely used database option in development of systems and are a very powerful tool for handling data.

CooperDB is a Relational Database built on IPFS that developers can access using simple http api calls or future SDK's that will be developed. Making it easier to store relational data on IPFS.

### 2. Project links
  
Link to Github repo: https://github.com/IKalonji/CooperDB
Link to demo or website, if applicable: 
* Initial MVP (https://youtu.be/pLqrLngBJcg) 
* Updated MVP (https://youtu.be/mmEXSMz2a9o) 
License: MIT
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

IPFS is used as the main storage layer to store the database state as is updated each time content is added to the tables. Filswan MCS is used as the layer to facilitate storage deal management and payment.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We close to achieving a publicly deployable MVP however a few items need to be addressed: 
- Look into data encryption because anyone with the CID can simply read the data.
- Improve the developer console UI as suggested by the hackathon judges.
- Finalize the final API endpoints for the deployed MVP
- Add stored procedures to the database for developers to create queries that are usually called
- Lastly add some data visualization to the developer console. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

I agree to share reports upon request and a grant report.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes, the project complies.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Web3Infinity (MVP - Pool prize)
* https://pl.coinemissary.com/transfer-requests/628413841289
DataDAO (Improved iteration - 2nd place MCS Filecoin track)
* https://pl.coinemissary.com/transfer-requests/682319231828
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
- Issa Kalonji
- ikalonji@student.wethinkcode.co.za
- https://github.com/IKalonji
- Project creator

* How did you learn about our microgrant program?
Winners were encouraged to apply for the grant if the project is being worked on and going to be deployed.

* If your project was created as part of an event or hackathon:
- Web3 Infinity Hackathon (Devpost) submission: https://devpost.com/software/cooperdb (Runner up)
- Data DAO Hackathon 2022 (Dorahacks) submission: https://dorahacks.io/buidl/3438 (Second place MCS Filecoin track)

**Comment by ErinOCon** [comment]
Hi @IKalonji, thank you for your proposal! This grant is currently under review. In the meantime, I have provided a reporting template for your previous projects. Please let me know if you have any questions!

**Comment by IKalonji** [comment]
Hi @ErinOCon, thank you. I'll complete the forms.

**Comment by ErinOCon** [comment]
Hi @IKalonji, thank you for your proposal. We will not be proceeding with a grant at this time. Wishing you the best as you continue to build!
