### ISSUE TITLE
Next Step Microgrant: DIDStorage

### ISSUE THREAD

**Issue by yangdouios** [filecoin-project/devgrants#1009]
### 1. What is your project? (max 100 words)
Building a decentralized DropBox across DApps based on decentralized identity, using ceramic's DID technology, not only makes it an independent Dropbox, but also builds a cross-Dapp user data space by relying on DID. We use web3.storage to store user data and combine IPFS based ceramic & did to bring users a fully decentralized Dropbox

### 2. Project links
  
Link to Github repo:
https://github.com/yangdouios/DIDStorage
Link to demo or website, if applicable:
https://didstorage.vercel.app/
License:MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
 We mainly use related technologies in 2 places:
1: Use IPFS-based ceramic & did to bring decentralized authentication to users
2: Use web3.storage to store all the real data of the user

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

I divided the project mainly into 3 miles for development : 

1. Web2-based Dropbox improves all related functions, mainly including data upload, classification, time/modification time/upload time, new directory, deletion, download, etc.
2. Rich more functions based on storage : Integrate NFT function and introduce nft.storage to support user Mint nft  & Create a shared data space with others & More node selection based on IPFS/Filecoin (pinata，textile)
3.  Introduce Filecoin nodes, provide long-term storage of big data, and use Fil-based payment mechanism

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  yes

### 6. Does your proposal comply with our Community Code of Conduct?

  yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  MingYang, duyuios@gmail.com , https://github.com/yangdouios
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @yangdouios, thank you for your patience with our review. Before considering this proposal for a grant, we would like to review more building progress. For next steps, I would recommend taking your project to a [hackathon](https://hackathons.filecoin.io/). Please be in touch with any questions!
