### ISSUE TITLE
Next Step Microgrant: Learnify

### ISSUE THREAD

**Issue by lakshh07** [filecoin-project/devgrants#1010]
### 1. What is your project? (max 100 words)

An education platform allowing projects to outsource and incentives for the creation of high-quality learning materials.

Learnify aims to change the way we collate and share information with each other by contributing to or maintaining courses. A platform for educators to make money fulfilling bounties. A place to learn and earn governance rights in the process.

Applying the principles of open-source software development to education. Create courses and incentivise the creation of high-quality learning materials for these courses. Contributors may fulfil bounties for course creators - maintainers of the courses approve these requests, improving the overall quality of each course with time.

Students of these courses receive a high-quality course from many points of view and areas of expertise.

Learnify uses the same philosophy as Github, but we provide courses instead of repositories.

Decentralised Services (Ether.js and communication with Smart Contract).

All smart contracts are deployed on Polygon Mumbai ( LearnifyFactory.sol, LearnifyCourse.sol, LearnifyMembership.sol, LearnifyQuest.sol)

This project uses,

✨ Next.js to design the frontend
✨ IPFS for storing courses metadata through IPFS-HTTP-Client
✨ Storing user profiles using Ceramic Network 3ID Connect

### 2. Project links
  
Link to Github repo: https://github.com/lakshh07/learnify
Link to demo or website, if applicable: https://learnify.vercel.app/
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
All the course metadata, profile data and NFTs metadata are stored on IPFS using ipfs-http-client.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

First of all, I want to improve UI, little bugs and easy flow for consumers. Redesign the structure of the whole process of application and wanted to add some more features like

- Community section where all the DAOs members will interact with each other.
- Wanted to add a gasless feature for new members of web3 to freely interact with the website.
- Podcast section where user can also mint their podcasts NFT(ERC1155) and podcast metadata will also be stored on IPFS.
- Change the profile section to show badges, their NFTs, courses and podcasts they have enrolled in or completed.
- wanted to make smart contracts upgradable using proxy.

Deploy it to mainnet and more things.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.

  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Yes, I have submitted for IPFS prizes.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  Name: [Lakshay Maini](https://www.lakshaymaini.com/)
  Email: lakshk886@gmail.com
  Github: https://github.com/lakshh07
  Role: Full Stack Blockchain Developer
* How did you learn about our microgrant program?
   From email.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum): ETHGlobal HackFs 2022
  * Please link to your hackathon submission: https://ethglobal.com/showcase/learnify-221ng

**Comment by ErinOCon** [comment]
Hi @lakshh07, thank you for your proposal! This grant has been approved. Look out for an email to confirm payment details.

**Comment by ErinOCon** [comment]
Hi @lakshh07, as you may have guessed from my recent comments in your proposals :), the final grant report for this project is due within three months of the approval date above and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by lakshh07** [comment]
Hey, @Erin O'Connor ***@***.***> Did I have to launch the project on the
mainnet also?
