### ISSUE TITLE
Hut 8 - Sustainable Storage

### ISSUE THREAD

**Issue by joshrayner** [filecoin-project/devgrants#1011]
# Open Grant Proposal: `Hut 8 - Sustainable Storage`

**Name of Project:** Renewable Data Centers Support the Filecoin Network

**Proposal Category:** Green

**Proposer:** `joshrayner`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:**  Yes

# Project Description

Hut 8 owns and operates five data centers and two cloud regions across Canada, in addition to our three digital asset mining sites. While we're pushing for 100% renewable energy at all our data centers, our Kelowna data center and cloud environment is currently powered 100% by renewable energy. We're planning to deploy a Filecoin node at this facility and would like the community to follow. 

Hut 8 is serious about our ESG mandate, we have set a carbon neutrality goal of 100% by 2025 and have offset emissions, annually, since 2021 using meaningful carbon credits. Our Full ESG report can be viewed here: [https://hut8mining.com/wp-content/uploads/2022/05/HUT-8_2021-ESG-Report_5-10-2022.pdf](url)

The early stages of running a Filecoin node are expensive. In addition to hardware, there are monthly data center; space, power, network and remote hands costs. Revenue is limited as sectors are in the process of being sealed. Hut 8 is looking to solve this problem in partnership with Filecoin Green Grants. Leveraging a Green Grant, Hut 8 will offer data center; space, power, network and remote hands costs free (3-6 months) for Filecoin nodes that deploy in our data centers. This will enable new nodes to significantly reduce their costs during the early stages of their deployment when revenue is limited. 

## Value

Issuing a Green Grant to Hut 8 will enable more providers to participate in the Filecoin network. We'll work alongside the Filecoin team to structure a program for new nodes that will reduce capital costs and minimize contract risk compared to traditional data center providers. Working with the Filecoin team on a structured program will ensure Green Grant funds are distributed fairly across Filecoin participants.  

There is significant financial overhead and contractual commitments require for new Filecoin node operators. Typically, data center and network providers expect Filecoin operators to sign 12-36 months terms. Hut 8 will provide month to month terms to Filecoin nodes who are approved under the Green Grant program. Hut 8 is looking to increase Filecoin node operators and enable existing node operators to expand by lowering their capital and contractual commitments. 

## Deliverables

NA

## Development Roadmap

The Filecoin and Hut 8 team need to collaborate on the structure for this program. For example, how many parties the Green Grant should be divided between and what the application process looks like. A Grant should be around $20,000 - $30,000 per party to have a positive impact on capital requirements and reduce capital burn for a sustained period. 

If provided a Green Grant, The Hut 8 team can implement this program immediately. We have the team and data centers in place to accommodate a large amount of Filecoin nodes.  

## Total Budget Requested

$200,000 USD 

This amount will enable us to help 6-10 Filecoin node operators and add a sizeable amount of storage to the Filecoin network. The number of parties able to benefit from these funds will vary based on the program structure that Filecoin and Hut 8 establish. 

## Maintenance and Upgrade Plans

Providing data center and cloud hosting for Web3 is a core objective for Hut 8. 

# Team

## Team Members

 Jaime Leverton,
 James Beer,
 Alex Shiskin,
 and Josh Rayner

## Team Member LinkedIn Profiles

Jaime Leverton [https://www.linkedin.com/in/jaime-leverton-she-her-3033a911/](url)
James Beer [https://www.linkedin.com/in/james-beer-4a39a/](url)
Alex Shiskin [https://www.linkedin.com/in/alex-shiskin-48188113/](url)
Josh Rayner [https://www.linkedin.com/in/joshua-rayner-67ba4122/](url)

## Team Website

 
[https://hut8mining.com/corporate/](url)

## Relevant Experience

Our team has decades of data center, cloud and network experience. 

## Team code repositories

 NA

# Additional Information
 Protocol Labs
 josh.rayner@hut8mining.com

**Comment by ErinOCon** [comment]
Hi @joshrayner, thank you for your patience with our review. We will not be moving forward with a grant at this time, but would be very interested to consider your work for grant opportunities in the future. 

Thank you for your time with this application. Wishing you only the best as you continue to build!
