### ISSUE TITLE
Next Step Microgrant: Pasteis 🍮

### ISSUE THREAD

**Issue by SamT6** [filecoin-project/devgrants#1012]
### 1. What is your project? (max 100 words)

Pasteis a decentralized hackathon platform aims to make hackathon experience more transparent and inclusive by having better features such as prize distribution, team-building and community voting. We started with a focus on hackathons but plan to double-down on the team-building aspect and expand the platform to focus on finding teammates & collaborators in any environment. 

Our platform would be an attempt to solving the question *How might we collaborate better to solve pressing challenges?* and we think by building tools to help people find compatible collaborators is a great place to start.

### 2. Project links
  
Link to Github repo: https://github.com/Pasteis-de-Web3/Pasteis
Link to demo or website, if applicable: https://youtu.be/zmUg20iNtJU
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
We use Web3.Storage, NFT.Storage and Tableland to store user data in a decentralized way.  

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The grant will be used to take this project from a hackathon prototype to a production-level MVP, hopefully with real users. The grant will cover developer time, deployment fees & potential  marketing cost. 
Next steps:

1. Hackathon code is messy! Re-design the infrastructure & refactor the code
2. Design better UI/UX
3. Improve upon existing code, implement new features 
    - bug fixes to make things scalable
    -  potential features include: 
        - support email signup if user doesn’t have a wallet
        -  integrate huddle01 for quick meetings
        - allow no-sign up events to be created for quick and easy team-finding (idea similar to meeting-scheduling tool [https://lettucemeet.com/](https://lettucemeet.com/))
        - random generated default POAP designs (or make it context-aware with AI) 
        - and more!
4. User interview people on their experiences of finding teammates for hackathons or collaborators for personal projects, find inspiration for new features, and get feedback on this project
    - back to step 3
5. Deploy & user testing in production

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, happy to!  

### 6. Does your proposal comply with our Community Code of Conduct?

Yes, it does. 

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: - [https://ethglobal.com/events/hackfs2022/prizes](https://ethglobal.com/events/hackfs2022/prizes)
Yes, *Best use of web3.storage or nft.storage* & *Web3 it!* at HackFS 2022
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
   - Samuel Tang, samueltang06@gmail.com, SamT6, Full-stack Developer
* How did you learn about our microgrant program?
  - Invited to apply by Niki Gokani from PL
* If your project was created as part of an event or hackathon:
  * What was the name of the event? - HackFS 2022
  * Submission link: [https://ethglobal.com/showcase/pasteis-de-web3-bza80](https://ethglobal.com/showcase/pasteis-de-web3-bza80)

**Comment by ErinOCon** [comment]
Hi @SamT6, thank you for your proposal! Can you confirm how you are connected to the provided hackathon submission? I wasn't able to find you listed as a member or contributor on the source code. If the owner of the hackathon repo can comment on this proposal with this information, this would be very helpful!

**Comment by SamT6** [comment]
Hi @ErinOCon thanks for the response! I'd be happy to confirm my connection to the project:
* if you head over to https://github.com/Pasteis-de-Web3/Pasteis you can see me listed under the team section
* I'm a code contributor as shown here https://github.com/Pasteis-de-Web3/Pasteis/graphs/contributors and this screenshot
![image](https://user-images.githubusercontent.com/26547344/193963616-a8dd5abd-6a63-4f6a-878f-9c413540a012.png)
* I'm also an owner of the repo so feel free to let me know if you'd like any further proofs
Thanks!

**Comment by ErinOCon** [comment]
Thanks, @SamT6! It looks like this was an oversight on my part. This grant has been approved! Look out for an email to confirm next steps.

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @SamT6, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

**Comment by SamT6** [comment]
Hey @ErinOCon, hope you're doing well too! I'm currently on Chinese Lunar New Year break and will aim to wrap up the project and submit the report by the end of January, thanks!

**Comment by ErinOCon** [comment]
Thank you, @SamT6!

**Comment by SamT6** [comment]
@ErinOCon Thanks for your patience with me! I've submitted the final report and the code can be found [here](https://github.com/SamT6/Ordinary), thanks!
