### ISSUE TITLE
Open Grant Proposal: `Eystorage`

### ISSUE THREAD

**Issue by Jeffonemore** [filecoin-project/devgrants#1014]
**Name of Project:** `Eystorage`

**Proposal Category:** `app-dev`

**Proposer:** `Jeffonemore`

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** `No`

*The front-end module is open source only because of the security of services. We will consider open source at the right time.*

# Project Description

#### What's the Eystorage?

Eystorage means easy to store data which provides an easy-to-use storage and retrieval service platform for users and developers of distributed storage. The backend stores data based on distributed storage networks such as IPFS, GlusterFS, web3.storage, Filecoin and [IPOS](https://github.com/filecoin-project/devgrants/issues/430), and provides storage for developers through OpenAPI interface. The front end provides a visual interface for users to store and retrieve data.

#### Github：
https://github.com/StorerOS/Eystorage

#### Website：
https://www.ey-storage.com/

## Value

1. Eystorage helps users easily and quickly store and retrieve data in decentralized storage service provider through an easy-to-use UI interface.

2. If we do not do it right, there should be no risk. Even if it fails, Eystorage will be an important infrastructure in Filecoin network.

3. We don't have such risks because we already have 12 members working on it, and they are well experienced in executing the things. The only risk that we see is if we don't get enough support from the Filecoin Foundation in the long time.

## Deliverables

1. Develop and support distributed networks such as IPFS, GlusterFS, web3.storage, and Filecoin to achieve decentralized data storage.
 
2. Develop a user-oriented visual retrieval market service gateway based on the native Index and Payment Channels provided by Louts Currently using the command line.We will provide a UI interface.

3. Visual retrieval market service gateway also supports indexing of IPFS hot storage data

### Milestone 1:
**Funding:** $20,000

**Achievable Date:** 2022.10.31

1. Develop and support distributed networks such as IPFS, GlusterFS, web3.storage, and Filecoin to achieve decentralized data storage.
 

2. Develop a user-oriented visual retrieval market service gateway based on the native Index and Payment Channels provided by Louts Currently using the command line.We will provide a UI interface.

2.1. Retrieval Process Overview
![image](https://user-images.githubusercontent.com/90947287/191929201-b9797f5a-47d7-4bd9-a723-551911629c20.png)

2.2. The specific implementation of the retrieval process
![image](https://user-images.githubusercontent.com/90947287/191933288-e914c7a8-59ec-4a19-b348-9b7d1f4d8b24.png)

### Milestone 2:
**Funding:** $10,000

**Achievable Date:** 2022.11.30

3. Visual retrieval market service gateway also supports indexing of IPFS hot storage data

## Total Budget Requested

Total Budge Requested: $30,000

# Team

## Team Members

Leader:  Wu J.
Product Manager: Xu Z. /Zeng J.
Blockchain Engineers: Li B./ Qin R.
Senior Development Engineers: Deng X./ Lu Z./ Yao H./ Tan H.
Test Engineer: Gao Z.
UI Designer: Liu H.
Business Manager：Jessica

## Team Introduction
https://docs.google.com/document/d/1j-cvSi529JrCYMbaGkV6E2x9gnSyjL4Mr_Rxv2YPsog/edit?usp=sharing

## Relevant Experience

Our team is an early storage service provider on Filecoin. Now focus on the development of Filecoin's infrastructure and ecology.
Our team has vast experience in writing high-quality code and tests. The team has an average experience of 5 years developing scalable solutions around the infrastructure protocol.
Our team is young and enthusiastic about building deep tech in the blockchain ecosystem.
BTW, The [UniFile](https://github.com/StorerOS/UniFile) and [IPOS](https://github.com/StorerOS/IPOS) which be developing by our team have been accepted now.

## Team code repositories

https://github.com/StorerOS

# Additional Information

**Comment by Jeffonemore** [comment]
@realChainLife Hi, I would like to know when will I get the review result about the proposal?

**Comment by ErinOCon** [comment]
Hi @Jeffonemore, this grant has been approved! Do you have a preferred email address for confirming next steps?

**Comment by Jeffonemore** [comment]
> Hi @Jeffonemore, this grant has been approved! Do you have a preferred email address for confirming next steps?

Hi @ErinOCon , thanks for your reply. The Email: storeros@wenchu.io

**Comment by Jeffonemore** [comment]
> Hi @Jeffonemore, this grant has been approved! Do you have a preferred email address for confirming next steps?

 I have sent you a email to you about the Milestones evidence document of Eystorage, Check it if possible.

**Comment by Jeffonemore** [comment]
@ErinOCon @realChainLife @

**Comment by ErinOCon** [comment]
@Jeffonemore This issue has been closed. Please contact our team at grants@fil.org if you have any questions.
