### ISSUE TITLE
Devforia.com

### ISSUE THREAD

**Issue by cameronzsmith** [filecoin-project/devgrants#1015]
# Open Grant Proposal: `Devforia Inc`

**Name of Project:** I am building a tech team looking to get small businesses started on Web3. I also have an idea for a digital business manager that could use a team of developers and designers.

**Proposal Category:** metaverse

**Proposer:** @cameronzsmith

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

Devforia.com is a technology group that I run from my experiences doing development for over 20+ years. I have a subscription model to allow small businesses to get on board, and plan to use that as startup capital to expand my team and make a Digital Business Manager application that's catered to these customers. The Digital Business Manager would allow businesses to take cryptocurrency for their products & services.

I also have an idea for a website called politic.in that scans politician data and provides an easy overview of which policies they support.

## Value

A large amount of small businesses in North America put onto the Web3 ecosystem with plans to make a self-sustaining company from application inventions from developers.

If 10% of my leads convert, I can net $175,000 on the low end.
If 10% of my leads convert, I can net $700,000 on the high end.

If my team takes on too many contracts and disappointed customers, this could be an issue. This is why I'm seeking funding ahead of marketing so that we can scale as needed.

Too many lead conversions without adequate staffing.

## Deliverables

Devforia.com is already finished and ready to take customers immediately. I still have to roadmap Digital Business Manager (DBM) and Politic.in. 

## Development Roadmap

I only wish for a grant to scale Devforia.com and the roadmap has been completed already. I have already received over 20k for the work I've done freelancing, now I'm ready to start a company that scales.

## Total Budget Requested

$100,000. This lets me get a starting base in USD to begin cryptography conversions. This would be spent on things like designers, developers, sales & marketing representatives, lawyers, and the like.

## Maintenance and Upgrade Plans

I use Agile practices and continuously develop and maintain projects. To upgrade the site as it is, I need to perform a Shopify integration so that I can take payments automatically. All payments will ideally be in cryptocurrency.

# Team

## Team Members

Cameron Smith - Chief Executive Office
Logan Jensen - Quality Specialist
Michelle Smith - Social Media Manager
Tina Bell - Customer Acquisition Specialist
Keyra Randall - Customer Acquisition Specialist

## Team Member LinkedIn Profiles

[](https://www.linkedin.com/in/cameronzsmith/)
[](https://www.linkedin.com/in/keyra-smith-953a21176)
[](https://www.linkedin.com/in/tina-bell-238b9868/)

## Team Website

https://www.devforia.com

## Relevant Experience

I have invited, deployed, and maintained an application for a Fortune 500 company that made >$5m in revenue in 1 year. The application deployed to a global level. I've successfully completed and ran software projects with teammates ranging from budgets < $100k to > $1m.

## Team code repositories

[GitLab](https://gitlab.com/DevforiaInc)
[GitHub](https://github.com/cameronzsmith)

# Additional Information

Followed the rabbit.

cameron@devforia.com

I believe I can make a significant impact on converting businesses to the Digital Age. I've been doing this for a while and have never felt more ready in my life to take on this task.

**Comment by ErinOCon** [comment]
Hi @cameronzsmith, thank you for your proposal! We think this is better suited for an [accelerator program](https://ecosystem-wg.notion.site/Protocol-Labs-Accelerator-Program-d45d8792a7d544eca9beb7d3e3d3b05d). If this program is of interest, the waitlist form can be found [here](https://airtable.com/shrDQf4msK4WfR3ps)!

Wishing you the best with your project!
