### ISSUE TITLE
Dank Thrift: NFT powered Sustainable Fashion E-commerce store

### ISSUE THREAD

**Issue by charulthrift** [filecoin-project/devgrants#1016]
# Open Grant Proposal: `Dank Thrift: NFT powered Sustainable Fashion E-commerce store`

**Name of Project: Dank Thrift**

**Proposal Category:**  `app-dev` `green`   

**Proposer:** `charulthrift`

**(Optional) Technical Sponsor:** `No`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

​​Dank Thrift is an affordable, sustainable and fashionable thrift store aimed to build a solid community of conscious shoppers. Our vision is to create a more sustainable fashion economy by making second-hand fashion inventory transparent and circular, one wardrobe at a time.

Fast fashion is an inexpensive and quick way of producing clothes, but it can have devastating effects on the environment. The fast fashion industry produces globally 20% of wastewater. Textile dyeing is the second largest water polluter globally.7600 litters of water Is needed to produce a single pair of jeans.

Fashion trends change just as fast as the seasons. This fast pace causes many clothes only to be worn one or two times before being tossed. Most of these clothes are tossed out in the trash and end up in landfills. All these clothes then sit there for hundreds if not thousands of years. 

The fast fashion industry produces 10% of global carbon emissions. Every second, the equivalent of one garbage truck full of textiles is burned or landfilled. It takes 200 years for some materials to break down. During this process, toxic gases and chemicals are emitted into the atmosphere, or filtered into the soil and groundwater, harming the environment.

## Value

We will contribute the following through Dank Thrift :

KEEP CLOTHES OUT OF LANDFILLS
 
Many people don't realise that recycling incorporates more than the typical plastics and includes textile recycling. One of thrifting's biggest advantages for the planet is that it keeps clothes out of landfills. People now more than ever are recognising that the clothes they no longer want will make much more of an impact when donated and brought to thrift stores, rather than tossed in the garbage.  
 
LOWER OUR CARBON FOOTPRINT
 
A ton of energy goes into clothing manufacturing. The whole process—transportation of raw materials to the production processes and shipping to stores—takes up a plethora of energy and time. The fashion industry is moving faster than ever, creating millions of clothing items every day to fill up the stores every week. At Dank Thrift, we aim at preventing that massive waste of energy and resources on the production of new clothes.
 
 PRESERVE WATER
 
Like we've mentioned, clothing production is a process that takes up a lot of time and energy, it also uses a lot of water. Water consumption is extremely high in every single stage of clothing production. When made unsustainably, even simply growing one kilogram of cotton requires at least 10,000 litters of water. That’s just the beginning of the production process. There’s wet processing and printing, packaging and transportation processes—all these steps add to the overall water consumption. At Dank Thrift, we are creating awareness for secondhand clothing, which plays a part in preserving water.

 
REDUCE CHEMICAL POLLUTION
 
Another great way that thrifting helps the planet is that it reduces the chemical pollution induced by creating and buying new clothes. Let's think back to cotton-the production of cotton not only uses tons of water, but it's also highly pesticide-intensive. This means that when cotton is produced and manufactured, it causes soil acidification and water contamination. And this is from material that many people consider sustainable
 

## Deliverables

We will be creating an e-commerce store that will help in creating easy access to good quality, pre-loved clothing thus promoting a circular economy. We will be using IPFS as our storage layer.

## Development Roadmap

Initial Phase(2 months): $15,000
1. Images and assets for the e-commerce site to be uploaded on IPFS
2. An e-commerce site to take orders in crypto currencies
3. Customers can track their orders via Metamask logins
4. Cart and wish list features for users

Advanced Phase(2 months): $15,000
1. Admin dashboard with user access levels of admin, manager and employee
2. Product uploading from Admin dashboard and assets to be uploaded to IPFS
3. Analytics for the admin dashboard regarding purchases.

## Total Budget Requested

We are requesting for a total amount of $30,000 for the project development.

## Maintenance and Upgrade Plans

Based on the market trends and requirements we will regularly update the platform along the maintenance for a minimum period of 4 years.

# Team

## Team Members

Charul Sharma, Founder

Charul Sharma, 27, acknowledges her shopaholic tendencies left her with a mountain sized pile of clothes. She was aware of the ill effects of fast fashion and how they finally end up in landfills. She founded her purpose after her introduction to sustainable and pre-loved fashion. She had gone from shopping at malls and big retail stores to bargaining at thrift stores. She wanted to create more awareness especially among the youth who are more persuasive to the ‘slow fashion’ trends.

This led her to quit her 9 to 5 and build a thrift store- Dank Thrift that would help create a circular fashion community. 
She now manages and directs the vision and the voice of Dank Thrift.

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/charul-sharma-b77bbbb2/

## Team Website

https://dankthrift.com/

## Relevant Experience

The team is well versed with the technical and business expertise to build the project which is an amalgamation of blockchain tech with fashion.

## Team code repositories

https://github.com/dank-thrift/thrift-application

# Additional Information
How did you learn about the Open Grants Program?  Twitter
 Please provide the best email address for discussing the grant agreement and general next steps. charul@dankthrift.com

**Comment by ErinOCon** [comment]
Hi @charulthrift, thank you for your proposal! For this stage of your project, we recommend participating in a hackathon. These events include opportunities to learn more about Filecoin and can also provide support to your team as you build out the prototype for the ipfs uploader.

Please feel welcome to apply in the future as your project continues to make progress!

**Comment by charulthrift** [comment]
Thank you for the update @ErinOCon . Sorry for making an impression regarding the early stage of our project. We are already selling our products through our established web2-based platforms. Please have a look at the following operating metrics:

1. 1177 orders in this quarter
2. 73% repeat customer rate
3. 300 plus SKUs

We have already created web3 MVP and will be shifting our existing client base on this e-commerce platform as we will provide them royalty-based NFTs which will provide them an extra discount on the next purchase giving use cases to our NFTs. 

I request IPFS/Filecoin support in reducing the impact on the environment by fast fashion.
