### ISSUE TITLE
Next Step Microgrant: Chemotronix 

### ISSUE THREAD

**Issue by PeaceBello** [filecoin-project/devgrants#1017]
### 1. What is your project? (max 100 words)

We are building a platform that provides real-time tracking of greenhouse gas emissions to efficiently allocate carbon credits and invest in clean energy infrastructure.
Our solution is basically an interplay between AI x Blockchain x Clean Energy x IoT. We send the data from our IoT device to decentralized platform (web3.storage) to allocate carbon credits and invest in clean energy infrastructure.

### 2. Project links
  
Link to Github repo:  https://github.com/Chevtrox-Ventures-Chemotronix/Web3athon-Chemotronix

Link to demo or website, if applicable https://chemotronix.vercel.app/

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

 Web3.storage is used to store the various emissions data and later used to display visualizations on our Blockchain platform.
The data is important to track and monitor progress regarding protecting the environment from climate change.
The data obtained would be effectively used to allocate carbon credits.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We will use this grant to improve on our Blockchain platform, hire more experienced Blockchain developers  to build a more robust solution.

We will use the grants to ensure we make more impact by ensuring we get experienced individuals regarding Tokenomics and better visualizations.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, we agree to share our grant report

  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Yes, we made a submission to Web3athon. https://web3athon.hackerearth.com/challenges/hackathon/consensus-2022-2/dashboard/64f736f/submission/published/chemotronix-filecoin/ 

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Peace Bello (Team Lead, peacelekanbello@gmail.com, github.com/PeaceBello)
Victor Olufemi ( Hardware Engineer, femiosinkolu@gmail.com, https://github.com/osinkolu)
Oreoluwa Akinola ( Blockchain Developer, oreoluwaakinola22@gmail.com, https://github.com/dear-ore
* How did you learn about our microgrant program? Via polygon voucher grant through Piyush Maheshwari
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) Web3athon
  * Please link to your hackathon submission
https://web3athon.hackerearth.com/challenges/hackathon/consensus-2022-2/dashboard/64f736f/submission/published/chemotronix-filecoin/

**Comment by redransil** [comment]
Hi! Sorry about the long response time. I see you are looking at tracking carbon emissions and trading offsets. Can you let me know more about what projects and hardware you are working with? Whose emissions are you tracking, and what is the plan to launch a working system with them?

**Comment by PeaceBello** [comment]
Good day Alan,

Chemotronix is an early stage startup (part of Microsoft for startups
founders hub) tracking greenhouse gas emissions via a IoT device to enable
efficient allocation of carbon credits which will offset emissions to
ensure we attain net zero.

Currently we have our IoT prototypes deployed in some areas around  Osogbo
and Lagos, Nigeria.

We are currently in talks with some state government to produce more
devices. Also we are partnering with some reputable organizations to test
run our solutions, probably in Q1 of 2023.

We could set up a call next week to discuss further for more details.

Currently, we are using web3.storage provided by filecoin to store the data
from our IoT device, and polygon for allocation of carbon credits.

You can check out our demo platform here.
https://chemotronix.vercel.app/


Really glad to hear from you and expecting a feedback from you soon.

Best Regards,
Peace.

**Comment by PeaceBello** [comment]
Industrial IIoT devices coupled with various sensors for detecting
greenhouse gas emissions

**Comment by orinayodele** [comment]
Hi @PeaceBello we are happy to award you $1k to start iterating out your idea! You will receive next steps shortly.

**Comment by PeaceBello** [comment]
Thanks so much.

Looking forward to hearing from you soon.

Best Regards,
Peace

**Comment by ErinOCon** [comment]
Hi @PeaceBello, we have sent an email to confirm payment details. Please let me know of any questions!

**Comment by PeaceBello** [comment]
Good afternoon Filecoin-Project/Devgrants,

Thanks so much for getting back to me.

We will complete the form shortly.

Best  Regards,
Peace
