### ISSUE TITLE
Next Step Microgrant: Ecse

### ISSUE THREAD

**Issue by rageofaxe** [filecoin-project/devgrants#1018]
### 1. What is your project? (max 100 words)

ECSE helps to create e-commerce websites in the web3 world. It includes creating a catalog with static site generator (Hugo in our case) and providing web3 dynamics with billing using lazy minted NFT. It's similar to SSG e-commerce flow in web2 where you can use snipcart or another third-party service that resolves cart issues.

### 2. Project links

Link to Github repo: [https://github.com/rageofaxe/ecse](github)
Link to demo or website, if applicable: [https://ecse.herokuapp.com/](demo) (some features don't work in this environment)
License: MIT

### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

We use NFT.storage for resolving cart issues in decentralized ecosystem. We want to mint NFT of completed orders and store their metadata in IPFS.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Our work contains two parts: billing and catalog.

Billing:

1. Develop UI for the cart on frontend-side, theme-independent at first but customizable in the future. (less than two weeks)
2. Write API and smart-contract for lazy minting NFT with stored order's metadata on IPFS. (less than a month)

Catalog:

1. Develop 3 themes that will be integrated with our cart (less than a month). But in the future we'll develop more themes and/or include the community in development of the themes.
2. Create a service that provides access to static assets with self-hosted headless-CMS (we decided to choose Ghost, it has an MIT license) (less than two weeks)

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### Additional questions:

- For each team member(s), please list name, email, Github account, and role in the project.

Ivan Arlenka

Contacts: arlienka@gmail.com, [github](https://github.com/rageofaxe)

Role: fullstack, smart contracts

Fiodar Arlenka

Contacts: fvorlenko@gmail.com, [github](https://github.com/theodarl)

Role: frontend, theme developing

- How did you learn about our microgrant program?

When exploring IPFS ecosystem on github

**Comment by ErinOCon** [comment]
Hi @rageofaxe, thank you for your patience with our review! Did you complete user research for this project? Are you pursuing a solution for a specific scenario? Also, I noticed [geroes](https://github.com/geroes) has been involved in the building of this project. Will this person continue to be involved?

**Comment by ErinOCon** [comment]
HI @rageofaxe, I hope you are doing well! Is this a project you are still working on? Please let me know if you have questions for our team.

**Comment by rageofaxe** [comment]
Hi @ErinOCon, I'm sorry for the long answer, we have some problems due to our relocation. Anyway, we didn't do any user research, we just believe that some businesses want to work incognito or independently from the government. For example, in our country (Belarus) many businesses are exposed to repression just for political reasons.

geroes - it's me, I believe it's a strange bug in the GitHub

**Comment by ErinOCon** [comment]
HI @rageofaxe, thank you again for your proposal. We will not be moving forward with a grant at this time, but you may have an interest in taking this to [a hackathon](https://hackathons.filecoin.io/). Wishing you the best as you continue building!
