### ISSUE TITLE
SlackBot to identify trends in stock prices

### ISSUE THREAD

**Issue by rickityjo** [filecoin-project/devgrants#1019]
### 1. What is your project? (max 100 words)

I was tired of seeing all these other people making money from their stock trading bots so I wanted to see if this was actually possible I tried to make my own bot that would data to see if it was actually possible to identify trends in stock prices of certain companies and see if these people are actually able to make money with trading bots. The project is a Slack bot that collects the prices of a stock on each weekday and then on a Friday sends a report of the stock to the slack channel. The idea is that we can use this data stored in IPFS to train a trading bot to make money. This project uses IPFS to store all its data for easy access and security.

### 2. Project links
  
Link to Github repo: https://github.com/rickityjo/SlackBotIPFS
Link to demo or website, if applicable: https://www.youtube.com/watch?v=crXG7bKXGb0
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

There is currently no open source collection of stock data available on the internet so I want to make this and store it in IPFS and so IPFS is used as the storage backend.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

I plan to add more stocks, I also want to collect new insights about stocks I am already collecting.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?

Yes, I agree to share grant reports upon request, including a final grant report at the end of the three-month period.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

N/A

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @rickityjo, thank you for your proposal! Can you provide more details regarding your next steps? What specifically will you accomplish over the next three months? How will this action improve the impact of your project?

**Comment by rickityjo** [comment]
Hi, @ErinOCon I want to collect this data from the bot to try to recognize a pattern (what is the best day to buy certain cryptocurrencies) and send reports to the members of the Slack channels. I will the money to pay for servers to store huge datasets of time series data from the coins. I will use the past data from the yfinance api to get the data

**Comment by jenks-guo-filecoin** [comment]
Hey there @rickityjo, I know there is a "build" part of your slack bot application. However the main purpose of the grant application seems to be to store the data. 

What kind of services is suitable for your data storage? Does it need to be stored on IPFS for fast retrieval or can be archived on Filecoin? 

I would also recommend looking at Filecoin Plus program and see if you are eligible for Data Cap application: https://github.com/filecoin-project/filecoin-plus-large-datasets

**Comment by rickityjo** [comment]
There is a substantial amount of time involved in the "build" of this project that is why I am looking for this grant to cover development hours and the server costs. Storage won't be that bad of a cost.

**Comment by rickityjo** [comment]
Hi @jenks-guo-filecoin - has this grant proposal been ruled out? I still want to apply for this grant, am I still eligible?

**Comment by rickityjo** [comment]
Ok, that's no worries

**Comment by ErinOCon** [comment]
Hi @rickityjo, thank you for your patience with our review. We will not be moving forward with a grant at this time, but wish you the best as you continue building out the project. Thank you again for your interest in our grants program!
