### ISSUE TITLE
Open Grant Proposal: Video Chat App - Web3RTC

### ISSUE THREAD

**Issue by utkucy** [filecoin-project/devgrants#1021]
# Open Grant Proposal: Video Chat App - Web3RTC

**Name of Project:** Video Chat App - Web3RTC

**Proposal Category:** `app-dev`

**Proposer:** @utkucy

**(Optional) Technical Sponsor:** `No`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** `Yes` `GPLv3`

# Project Description

It has been observed that people with different needs (work, social, school, etc.) seek different solutions to meet the increasing need for online meetings. Web3RTC is a video chat application built on completely decentralized technologies. It aims to establish connections between users without the need for any central server to store data or transmit media resources.

Web3RTC uses peer connections for both storing and transmitting operations:

**Store Operations** <br />
Authentication processes (register - login), creating and retrieving room data (participant list, chat messages, etc.), storing and retrieving past meetings information, storing past meeting records, allowing to make changes for user preferences.

**Transmitting Media Source Operations** <br />
Establishing connections between peers in the rooms with both voice (source: microphone) and video (source: camera, screen share) sources.

Since Web3RTC will use OrbitDB for database operations, Web3Storage for storing meeting records, and finally WebRTC for the media transmitting operations,
it guarantees that every action that users can take on the apps would be established by peer-to-peer connections. Although there is just a web app that exists at the moment, my goal is to develop this app for 5 different platforms if the proposal would be approved. A web app, an IOS app, an android app, a macOS app, and finally a Windows app.

`App Dashboard 1`

<img width="1112" alt="Screen Shot 2022-09-25 at 18 48 45" src="https://user-images.githubusercontent.com/41550693/192152595-28219f6e-1680-48a1-b6b2-3ce285fdfb17.png">
<br />

`App Room with Connected Peers`

![photo_2022-09-25 18 39 06](https://user-images.githubusercontent.com/41550693/192166251-2da68510-5521-4cef-9223-4b41485b466b.jpeg)
<br />

<br />

**Demo app can be found on: https://jade-sunburst-1968ce.netlify.app/**

## Value

Web3RTC is a smooth way of the transaction from web2 to web3 ecosystems. The main purpose of these apps is to be cost-efficient and accessible from anywhere to anyone at any time. Since all the applications will use the same P2P logic for every action, it will lower the cost of the programs. With the applications planned for 5 different platforms, Web3RTC would have a wide usage case.

Last but not least, I believe that it would have a great impact on the Filecoin community for educational purposes about how to use these technologies since it will be published as open source projects.

However, there may be constraints on the app usage because of the used technologies. WebRTC constraints can affect the streaming quality, total peer connection number (since WebRTC uses local computer resources, restricting connections may be a must), or being able to connect with other peers (NAT traversal problem for WebRTC). Also please note that OrbitDB is alpha-stage software. It means OrbitDB hasn't been security audited and programming APIs and data formats can still change.

## Deliverables

There will be 5 apps as final products: **IOS app, android app, Desktop Apps (macOS, windows), Web App)**

- Creating and publishing a web app with a custom domain name
- Creating and publishing an ios app
- Creating and publishing an android app
- Creating and publishing the macOS app
- Creating and publishing windows app

Common features:

- IPFS will be used for all data management process
- Authentication process will be added as _Login_ and _Register_ cases with OrbitDB.
- **Ability to Create a room**
- **Ability to Join a room**
- **Ability to Chat with others in the room**
- **Ability to Share voice and camera source**
- **Ability to Change media sources**
- **Ability to Add other users to the contact list**
- **Ability to List Past Meetings**
- **Ability to List Contact List**
- **Ability to Manage App Settings**, are common dashboard usages for all apps.
- However, **Screen Sharing** and **Recording Screen** features will be available for only Desktop and Web app.
- **Recording Screen** will be downloaded to the local computer as a first step. After a milestone, Web3Storage will be another option for storing the recorded file.

- Sign-in with Metamask will be added to the web app as an authentication option.
- Web app will be published in its domain
- Mobile apps will be published in their stores

For more information please check the development roadmap.

## Milestone 1

Budget: $20,000
Estimated Time: 2 weeks

|     | Milestone Steps                                                                      |
| --- | ------------------------------------------------------------------------------------ |
| [x] | Creating and publishing the web app                                                  |
| [x] | Normal authentication flow (login-register) added                                   |
| [x] | Ability to Create a room                                                             |
| [x] | Ability to Share voice and camera source                                           |
| [x] | Ability to Change media sources                                                    |
| [x] | Ability to Add other users to the contact list                                           |
| [x] | Ability to List Past Meetings                                                        |
| [x] | Ability to List Contact List                                                         |
| [x] | Ability to Manage App Settings                                                       |
| [x] | Ability to Record a screen sharing and download it in WebP format to a local computer |
| [ ] | Custom domain for the web app                                                        |
| [ ] | Publishing the web app's code as open source with GNU GPLv3 license on GitHub.       |

 <br />
 
 If the proposal would be approved, I will focus on creating a product team to continue the development process at the end of this milestone.
- 1 UI/UX product designer,
- 2 Developers will be hired as teammates.

## Milestone 2

Budget: $20,000
Estimated Time: 3-4 weeks

|     | Milestone Steps                                                                                                                                                   |
| --- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| []  | Ability to Chat with others in the room                                                                                                                           |
| []  | Metamask authentication process will be added to web app                                                                                                          |
| []  | Web3Storage will be added as another option to store the recorded meeting file                                                                                    |
| []  | Creating and publishing the Desktop apps for both macOS and Windows Platforms. All milestone steps mentioned in Milestone 1 and 2 will be completed for the apps. |

Additionally, mobile app developments and new UI/UX design processes for all of the apps would be started at this milestone.

 <br />

## Milestone 3

Budget: $20,000
Estimated Time: 3-4 weeks

|     | Milestone Steps                                                                                                                                 |
| --- | ----------------------------------------------------------------------------------------------------------------------------------------------- |
| []  | Creating both the IOS and Android apps. All of the common features stated in the **Deliverables** section will be implemented for both apps. |
| []  | Both mobile apps will be published in their app stores.                                                                                         |
| []  | Redesign process for all 5 apps.                                                                                                                |
| []  | End-to-end testing process for all 5 apps                                                                                                       |
| []  | A detailed README file will be prepared for all 5 apps to explain the logic of the used techs and programs.                                      |

## Total Budget Requested

$60,000

## Maintenance and Upgrade Plans

I am committed to maintaining the development of the project. I will continue to maintain and upgrade all of the products.

- Design improvements according to user feedback
- Production tests for all 5 apps
- Detailed documentation will be prepared

# Team

## Team Members

Utkucan Yıldırım

## Relevant Experience

- I am a software developer mainly focused on front-end development areas. However, I am also interested in many various topics such as Web3 and P2P apps (specifically with the WebRTC apps) for in that matter. I have 3+ years of work experience in my professional career and approximately 2 years of knowledge of WebRTC technologies.

## Team code repositories

https://github.com/utkucy/ipfs-webrtc

# Additional Information

I learned the Open Grants Program while researching about the Filecoin ecosystem.

Email: yil.utkucan@gmail.com

**Comment by ErinOCon** [comment]
Hi @utkucy, thank you for your proposal! This grant has been approved. Look out for an email to discuss next steps.
