### ISSUE TITLE
Next Step Microgrant:  FundKyiv

### ISSUE THREAD

**Issue by paschal533** [filecoin-project/devgrants#1022]
### 1. What is your project? (max 100 words)

FundKyiv is a decentralized fundraising application built specifically for fundraising organizations in Ukraine, where users can create a fundraising campaign, Donate to a fundraiser with a CELO token and print the receipt of their donations. FundKyiv also has other additional features that allow users to send CELO tokens to anyone across the world, view the amount of CELO tokens they have in their wallet, and view their last five transaction counts.

### 2. Project links
  
Link to Github repo: https://github.com/paschal533/FundKyiv
Link to demo or website, if applicable: https://fundkyiv.netlify.app/
License: MIT
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

All the Fundraiser metadata, and profile data are stored on IPFS using ipfs-http-client.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

 - Move from Testnet to Mainnet

- For security reasons, we will disable users from creating a fundraiser directly into the blockchain. You will need to send a proposal to us first, then we will verify your identity before you will be authorized to set up a fundraising campaign.

- Fix Bugs and add more features to FundKyiv to make it more interactive.

- Develop API for Developers to easily interact with our data.

- Multi-chain.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
 
Yes.

### 6. Does your proposal comply with our Community Code of Conduct?
 
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: https://devpost.com/software/fundkyiv
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

   Name: Paschal Okwuosa
   Email: Okwuosahpaschal@gmail.com
   Github: https://github.com/paschal533
   Role: Team Lead

   Name: Kosisochukwu
   Email:  kosisochukwuokwuosah@gmail.com
   Role: UI/UX designer

   Name: Kunal Dawar
   Email: dawar.kunal703@gmail.com
   Github:  https://github.com/developerkunal
   Role: Blockchain developer

   Name:  Andrii Ponamarov
   Email: ponamarevandrej@gmail.com
   Github:  https://github.com/dresha-dev
   Role: Frontend developer

   Name: Vitaliy
   Email:  vitaliy.sobur@gmail.com
   Github: https://github.com/vitaliysobur
   Role:  Full Stack developer

* How did you learn about our microgrant program?

  Through Email after winning IPFS | Filecoin Sponsored Bounty

* If your project was created as part of an event or hackathon:
  
  Kyiv Tech Summit

  * Please link to your hackathon submission
    https://devpost.com/software/fundkyiv

**Comment by ErinOCon** [comment]
Hi @paschal533, thank you for your proposal! This microgrant has been approved. Look out for an email to confirm payment details.

**Comment by ErinOCon** [comment]
Hi @paschal533, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!
