### ISSUE TITLE
Next Step Microgrant: Wildfire detection and alerting using IPFS

### ISSUE THREAD

**Issue by mjsmith98** [filecoin-project/devgrants#1026]
### 1. What is your project? (max 100 words)
This project retrieves data from the NIFC wildfire API that covers the United States. I use this data to alert me on new wildfires across the country using Gmail. This project is built with Physical Asset Security/Emergency responder sectors in mind and I am looking to expand to tracking fires globally. 

### 2. Project links
  
Link to Github repo: https://github.com/mjsmith98/Wildfire-Detection-IPFS/tree/main
Link to demo or website, if applicable: https://youtu.be/5j7q4pGesuo
License: MIT
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
I use IPFS to store API data which I will use to keep track of fire progression/containment by referring to previous hashcodes.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
I want to add deduplication functionality so that I don't get alerted on old content. I want to create state with my data pipeline where I can monitor if a fire has grown or decreased in size, and will do this using IPFS as my storage/archive retrieval.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes I do
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes it does

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Mark Smith - https://github.com/mjsmith98
* How did you learn about our microgrant program?
* I heard about it from a friend
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @mjsmith98, thank you for your proposal. This microgrant has been approved! Can you provide a preferred email address to confirm payment information?

**Comment by mjsmith98** [comment]
Great thank you, Erin! My email is mjsmith9822@gmail.com

**Comment by ErinOCon** [comment]
Hi @mjsmith98, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @mjsmith98, following up on the request above.
