### ISSUE TITLE
Next Step Microgrant: Dappvault

### ISSUE THREAD

**Issue by ankitshubham97** [filecoin-project/devgrants#1028]
### 1. What is your project? (max 100 words)

Dappvault is a document-protection dapp which is truly decentralized yet secure. It protects your organization's sensitive files while enabling seemless-sharing with the authorized members; powered by blockchain, cryptography & IPFS.
### 2. Project links
  
Link to Github repo: https://github.com/ankitshubham97/dappvault/
Link to demo video: https://youtu.be/Eu0ivvFS7co
Link to website,: https://dappvault-frontend.vercel.app/
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
   The files are tightly-encrypted & then stored securely on IPFS. Access is granted only if the user has enough governance tokens or governance NFTs. They can only be accessed by the members of the organization which the organization has authorized to. The authorization is granted to a member only if any of the 2 conditions are met:

1. Have the correct NFT in their wallet which the organization provided.
2. Have a certain amount of governance tokens of the organization.

Think something similar to Developer DAO (You need to either have one of their genesis NFTs or 400 $CODE tokens to unlock access)

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

I see Dappvault as a decentralized SAAS product and the primary customers could be organizations and individuals who take special care when it comes to security of sensitive documents. With grant, I have following pending tasks to complete:

1. Purchase Chainsafe storage as the product depends on it.
2. Get a cloud provider, preferrably AWS, to host the SAAS platform.
3. Improve UI/UX.
4. Improve admin dashboard and include management & analytics modules.
5. Do thorough E2E and build automated testing.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  Yes.
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Submitted at ETHOnline 2022 for IPFS bounty: https://ethglobal.com/showcase/dappvault-dhkg4
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Ankit Shubham
Email: ankitshubham97@gmail.com
Github: https://github.com/ankitshubham97
Role: Designer/Developer
* How did you learn about our microgrant program?
SuperteamDAO
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  ETHGlobal (ETHOnline 2022)
  * Please link to your hackathon submission
https://ethglobal.com/showcase/dappvault-dhkg4

**Comment by ErinOCon** [comment]
Hi @ankitshubham97, thank you for your proposal! Can you provide access to the repo?

**Comment by ErinOCon** [comment]
Hi @ankitshubham97, this issue has been closed per our discussion in [this proposal](https://github.com/filecoin-project/devgrants/issues/1029). Thanks!
