### ISSUE TITLE
Next Step Microgrant: Fanstop (Data Dao hackathon bounty winner)

### ISSUE THREAD

**Issue by ankitshubham97** [filecoin-project/devgrants#1029]
### 1. What is your project? (max 100 words)

Fanstop is a decentralized-yet-private content sharing platform for creators where they can:

1. Store content on IPFS(so decentralized)
2. Remain worry-free because their content are first encrypted and then stored on IPFS
3. Token-gate their content; so only that fan who possesses a certain NFT can truly access the data (Of course, the NFT would be provided/auctioned by the creator and it would be a guarantee of access to their private content!)
### 2. Project links
  
Link to Github repo: https://github.com/ankitshubham97/fanstop/
Link to demo video: https://www.youtube.com/watch?v=aCtSajvr0LQ
Link to website : https://fanstop-frontend.vercel.app/
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  Fanstop is using IPFS to store encrypted content that creator uploads. IPFS solves the problem of storage being centralized (hence the creator losing control of their content and the centralized storage being the choke point) in web2 realm and very high storage cost/subscription cost.
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

I see Fanstop as a decentralized SAAS product and the primary customers would be digital creators who want to take control of their own content, remove dependency on centralized systems and improve data security (Fanstop always encrypts data before uploading to IPFS). With grant, I have following pending tasks to complete:

1. Purchase Chainsafe storage as the product depends on it.
2. Get a cloud provider, preferrably AWS, to host the SAAS platform.
3. Improve UI/UX.
4. Improve creator dashboard and include management, analytics & monetization modules.
5. Do thorough E2E and build automated testing.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  Yes.
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Fanstop won the 2nd place in the Data DAO Hackathon 2022 under the track 'Network Drive - Best use of IPFS/Filecoin for file storage - $12,500'. Link to the project: https://dorahacks.io/buidl/3439
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Ankit Shubham
Email: [ankitshubham97@gmail.com](mailto:ankitshubham97@gmail.com)
Github: https://github.com/ankitshubham97
Role: Designer/Developer
* How did you learn about our microgrant program?
Data DAO hackathon's post award ceremony communication.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  Data DAO hackathon 2022
  * Please link to your hackathon submission
  https://dorahacks.io/buidl/3439

**Comment by ayushgupt** [comment]
Woah, this would be super helpful!

**Comment by shivankgoel** [comment]
Sounds interesting, looking forward!

**Comment by skyfeature** [comment]
this is an excellent idea. Content creators are going to love this!

**Comment by ErinOCon** [comment]
Hi @ankitshubham97, thank you for your proposal! It looks like the next steps provided match exactly with your [other proposal](https://github.com/filecoin-project/devgrants/issues/1028). Can you provide details that are specific for this project? For example, how will you improve UI/UX? What metrics will be included in the updated dashboard? What testing automations will you build out?

**Comment by ankitshubham97** [comment]
Sure @ErinOCon! Let me dive a bit deeper here:

## What is your company mission and vision?

Mission: To bring control of content and monetization back to creators.

Vision: Every creator gets the last penny that they deserve. Every penny that a fan pays goes to their creator. A creator is not bound to push brand sponsorships just for financing. We aim to eliminate large commissions being paid out to content platforms and replace brand sponsorships with direct monetization from fans

## What are your metrics to measure project's performance?

We measure success in a way that we have a proper vision and scope to expand on the company's vision and build a product that deals with optimistic growth in the following metrics:

1. Number of creators on-boarded.
2. Number of fans subscribed to at least one creator.
3. Cumulative/Per-head frequency of content upload.
4. Engagement from Fans wrt views, tips, NFT-minting.
5. Cumulative/Per-head earnings of creators.

## What is/will be included in the updated dashboard?

We have started to give the dashboard a major upgrade. These are a few tasks that are already done as of now:

1. To Creators:
  - A dashboard to manage their content. It includes adding new content, viewing & deleting existing content.
  - A monetization dashboard where they can track their monetization. This includes all the donations that they get and the minting fees.
  - A dashboard to view the NFTs that got minted. These are the NFTs of that creator.
2. To Fans:
  - A dashboard to view all the NFTs that they minted.
 
We are brain-storming on different gamifications that could be applied to make the platform more engaging & interesting.

## Improvements in UI/UX

We have already started working on UI. We are now using tailwindcss and are strictly following Google's material design concepts. The UI looks far better than before. We are also looking into different gamification strategies to improve overall UX and make the platform more engaging.

## Testing & Automations:
1. UI testing: We are setting up selenium-based UI testing suite and infra.
2. API testing: We are doing it via POSTMAN as of now, if the load increases, we would move to Apigee.
3. UT: Suites are being written as of now,

## Progress till date:
Here are some snapshots of the project (pseudonamed to stardapp for dev purpose):
![g4](https://user-images.githubusercontent.com/16755676/196977131-7fbbc23a-966c-4991-9a3c-67025aca5555.PNG)
![g3](https://user-images.githubusercontent.com/16755676/196977144-671dc88d-e60f-4c25-b8b0-d55561cd4e65.PNG)
![g2](https://user-images.githubusercontent.com/16755676/196977146-3911abbf-de51-4b88-8db4-c479b11f6670.PNG)
![g1](https://user-images.githubusercontent.com/16755676/196977149-b5de37d8-684b-4c31-ae0c-e409634e6a50.PNG)
![g6](https://user-images.githubusercontent.com/16755676/196977156-d816f2f7-2e08-486f-84ff-9b0a8560a7cd.PNG)
![g5](https://user-images.githubusercontent.com/16755676/196977165-85a3a3cc-a392-4870-b107-0ecbecd52086.PNG)

**Comment by ankitshubham97** [comment]
@ErinOCon Please find the current work at the phase-2 branch: https://github.com/ankitshubham97/fanstop/blob/phase-2

**Comment by ErinOCon** [comment]
Hi @ankitshubham97, thank you for your proposal and for your patience with our review! While this project and [Dappvault](https://github.com/filecoin-project/devgrants/issues/1028) are both eligible for a grant, it is highly preferred that microgrant projects be completed one at a time. Can you select the preferred project?

**Comment by ErinOCon** [comment]
Hi @ankitshubham97, thank you for the update! We will send you an email to confirm payment details for this project. Thank you again for your interest in our grants program!

**Comment by ErinOCon** [comment]
Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
