### ISSUE TITLE
Next Step Microgrant: ChromeExt+ChatOnWeb3WithTokenGatingContent on HackFS 2022 

### ISSUE THREAD

**Issue by NftTopBest** [filecoin-project/devgrants#1032]
### 1. What is your project? (max 100 words)
XMTP web3 chat improvement that with chrome notification, token gating and NFT unlocking widget in chat box ;)

We build a chrome extension that can notify users that they have new messages coming from XMTP. And we inject into the XMTP Chat Opensource code with LIT and IPFS(via NFT.Storage) that provide users a token gating chat UX. Users can send images with title/description and NFT gating contract addresses that only users with the NFT in their wallet can unlock the image. This can be used as chat 2 earn or selling while chatting

### 2. Project links
  
GitHub: https://github.com/NftTopBest/eth-global-XMTP-LIT-img-gating-chat
Demo: https://eth-global-xmtp-lit-img-gating-chat.web3hacker.ninja/

License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  
we build the useNFTStorage hook to provide a utils for our application to interact with IPFS: [code](https://github.com/NftTopBest/xmtp-chat-with-lit/pull/1/files#diff-2a09e7c28157db59a45459d3ec9ecaa190ce2477b0f9cc5cba44e42510ee4381)

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

* Rewrite our own Chat Application with XMTP and LIT by Vue3 framework
* Chrome Extension will inject ui into Twitter page that can chat direct on the twitter page also show some of the user's NFT on that injected components.
* Build the next generation of the Social platform that all follow the Web3 logic!
* make the XMTP listener work in the background service worker
  * I have spend over 10+ hours try to make it work in the background service worker, but it has some issues
    * xmtp package has some kind of `fs` call that can not work in browser
    * that I can not compile it to work in the background.js
* use [plasmo extension framework](https://www.plasmo.com/) to re-build the extension
  * I try before over 20 hours, but still, the same as the xmtp compile problem
  * Need more digging for this problem

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
 Prize on HackFS: https://ethglobal.com/showcase/chromeext-chatonweb3withtokengatingcontent-mq751

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Bruce, nfttop.best@gmail.com, NFTTopBest, Web3 Full Stack Hacker

* How did you learn about our microgrant program?
The winner email's content tell me

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
   Yes, the HackFS 2022
  * Please link to your hackathon submission
    https://ethglobal.com/showcase/chromeext-chatonweb3withtokengatingcontent-mq751

**Comment by ErinOCon** [comment]
Hi @NftTopBest, it looks like you have found a lot of building opportunity through our microgrants program! We will not be proceeding with a grant at this time for this project. Please feel welcome to consider our [other grant types ](https://github.com/filecoin-project/devgrants/issues/new/choose)should the scale and scope of your future work align with the outlined criteria.
