### ISSUE TITLE
Climate CRED Protocol (NFTs claimed by Email)

### ISSUE THREAD

**Issue by MehighCB** [filecoin-project/devgrants#1033]
# Open Grant Proposal: Climate CRED Protocol (NFTs claimed by Email)

**Climate CRED Protocol (NFTs claimed by Email)**

**Proposal Category:** `green`  

**Proposer:** `@MehighCB`

**(Optional) Technical Sponsor:** `@mjohnson518`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** "Yes" 

# Project Description

We are building a dynamic NFT minter, that will allow creators, artists and interested third parties to generate dynamic NFTs, using relevant climate change data sets and provide visual asset representation based on real-world change. The resulting NFTs will only be purchasable via the CRED token, which is generated by the retirement of carbon credits on a 1$ = 1 CRED basis. 

CRED protocol is a reward-based incentive platform that brings together world-class carbon credits partners for incentive retirement schemes. The goal of CRED is to provide verifiable, open and enticing rewards for both individuals and companies alike to become carbon neutral and not only. 

CRED protocol is part of Project-Ark, a venture and studio start-up that builds the tech and initiatives to help scale the voluntary carbon markets to 100 B USD for 2030.

## Problem to solve

The current voluntary carbon markets stand roughly above the 1 B $ mark, which is very little in comparison to where it needs to be (around 50x, 100x) to actually have a chance to reduce the temperatures below 2 degrees C. We need to reduce 30 billion tons of CO2 per year to avoid a climate disaster. As of today, the status quo doesn’t reward companies and especially individuals enough to retire carbon credits, making the voluntary carbon market just “voluntary”. 

At the same time, the is little trust in current carbon credit schemes, and dry climate change data and current narratives make it hard to accelerate the market and create a value loop.

## Solution

CRED protocol incentivises the retirement of carbon credits, by issuing a  token,  for each dollar spent on retiring carbon credits. CRED token can be then used to purchase NFTs, in the form of digital art, event tickets, metaverse land, experiences and much more. By providing the tools and the incentive for the retirement of carbon credits, we facilitate the scaling of the voluntary carbon markets towards the size required to avoid a climate disaster scenario.

The dynamic NFT minter will provide a powerful tool for artists, companies and interested parties to use data in creative ways. The tool will provide innovative paths of representation and endless possibilities to tie real-world changes to digital assets.

## Value

The proposal will be a strong value proposition for the Filecoin ecosystem by combining the strictness and dryness of data, with creativity, art and visual representations. We strongly believe that dynamic NFTs tied to climate change data will get us closer to providing a new class of assets that will provide a positive feedback loop for similar initiatives to rise.

## Getting things Right
Provide a great tool for carbon scaling, enabling creative solutions and displays of relevant data, as well as closing the gap between dry scientific data sets, art and the creative parts of it.

## Risks
Get stuck at the current level of carbon markets, with no real incentives to become carbon neutral as well as few use cases for climate change data outside of raising awareness and shouting facts into empty/echo chambers.

## Risks in execution
Getting a valuable market proposition that is enticing for both regens and degens alike will become a problem once scaling is involved. Outside of not finding product market fit, the risks of being too successful might bring a lot of bad actors in the ecosystem, bad reputation (supply side of credits) as well as damaging the reputation of the carbon credits altogether, in times where we need to create more credibility, legitimacy and world-wide adoption.

## Milestone 1: IPFS migration

Migrate the NFT storage from the current system to the Filecoin IPFS system as well as use the newly create storage solution for climate change storage [Co2 storage](https://co2.storage/) to represent retired carbon credits, store data sets and newly created dynamic NFTs.

**People involved:** Project Manager, Back-end Dev, Front-end Dev

Timeline: November-December 2022

Funding Needed:  25.000 USD

## Milestone 2: ERC 721/1155 minter 

Create an easy-to-use minter that uses the ERC 721 and 1155 standard for the creation of green impact NFTs now made possible even for people with little Web3 knowledge to use it. As an innovation piece, we will enable the NFT creators to send the NFTs to other people using only their email address (storage using filecoin IPFS, and Project-Ark custodial wallet).

**People involved:** Product Manager, Back-end Dev, Front-end Dev, Blockchain Dev, Ui/Ux Dev

**Timeline:** December-January 2022 

**Funding Needed:** 25.000 USD

## Development Roadmap

The roadmap for the product is compiled by different stages of the product and complexities, with a target to finish everything by February 2023 

1. Filecoin data storage migration
2. Simple to use NFT minter with the ability to send NFTs via mail.

## Total Budget Requested

**Wages** 

1.. Senior Dev Back-end 15K (3 months)
2. Senior Dev Front-end 15 K (3 months)
3. Product Manager 10 K (3 months)
4. Smart Contract Development 10K (2 months)

**Total Budget Requested**

50 K USD

Most of the budget will be used for hiring more people into the team and developing the product.

## Maintenance and Upgrade Plans

The dynamic NFT minter represents one of the most important functionalities of the Climate CRED protocol, which will provide a functional and basic data sets aggregator, with desired features and improvements based on community feedback. 
The ability to create and send NFTs via email will become one of it's crucial features, that will allow people to use NFTs without the hassle of creating a wallet.

# Team

## Team Members

**Max Song:** Forbes 30u30, HuRun U30, and Tatler Gen T Honoree, Schwarzman Scholar. Data scientist, venture partner at PCG
**Nick Edgar:** Director of Software Platform 22 years at IBM. ex Shopify, build the first Shopify carbon application. Experienced software developer, passionate about creating well-crafted software.
**Stella Zhou:** Product Lead Platform Global head of operations. 5 years at a gaming company that grew from 10M users to 50M users
**Khashayar (Cyrus) Nouroozi:** Engineer and REFI Community Lead Founding team of Wombo (scaled to 100M users), web3 architect at Syndicate.io, founder of EdenDAO.
**Joe Pan:** Communications and Investor Relations Executive Director of ImpactNFT Alliance which has 70+members. Founding member of Forkast.news, 20+ years of communications and IR executive.
**Mihai Hrimiuc:** Project Manager European Lead. Social Innovation Kenya Alumni, Aspire Leadership Program Graduate and experienced project manager.
**Nir Asaf**: CTO for numerous projects, working at the intersection of tech and impact, leading teams, initiatives and tech development.

## Team Member LinkedIn Profiles

Max Song https://www.linkedin.com/in/songmax/ 
Nick Edgar https://www.linkedin.com/in/nedgar/ 
Stella Chen Zhou https://www.linkedin.com/in/stellaxingchenzhou/ 
Khashayar (Cyrus) Nouroozi https://www.linkedin.com/in/knouroozi/ 
Joe Pan https://www.linkedin.com/in/joepannftnews/ 
Mihai Hrimiuc  https://www.linkedin.com/in/mihai-hrimiuc/ 
Nir Asaf  https://www.linkedin.com/in/nirasaf/ 

## Team Website

https://credprotocol.io/ 
https://www.project-ark.co/ 

## Relevant Experience

We come from a decade + of combined experience in the carbon space, as well as building tech products with hundreds of millions of users. Credibility in the corporate and clean tech world through Carbonbase.co start-up working the Porsche, Three Gorges ( Biggest Damn in China) and Veolia. We have collaborated with WWF Panda Labs, as well as working with Lay’s Chips, Peace Park, and Viviene Tam for NY Fashion Show 2022 through Project-Ark.

Our key blockchain developer comes from building apps that scaled to 50 million downloads as well as product people that have built similar size products before scaling them to 100 million users. 

## Team code repositories

[AsafNir](https://github.com/asafnir)
 [Cyrus](https://github.com/DaoDeCyrus)
[Nick Edgar](https://github.com/nedgar)

## Similar Projects

[github.com/edendao/omniprotocol](http://github.com/edendao/omniprotocol)
[github.com/edendao/contracts](http://github.com/edendao/contracts)
[Hydat-datasette](https://github.com/nedgar/hydat-datasette)

# Additional Information

Learn about the Open Grants Program? 
From David DAO ( Gainforest) and Marc Johnson

Email address for contact: mihai.hrimiuc@carbonbase.co 

 [CRED concept 3.0 (Greenpaper)](https://docs.google.com/presentation/u/1/d/1uLCg69b4sfkx7Of_D3P8r5iLLIVLrMb3H51QqVvKTuY/edit?usp=sharing)

**Comment by mjohnson518** [comment]
Hey @MehighCB, interesting proposal! A few questions/comments:

1. How will tools that incentive the retirement of carbon credits help facilitate the scaling of the vcm if you do not focus on enhancing the quality of the credits themselves? 
> One of the primary problems with offsets is that, in general, people see an offset saying it equates to -1 ton of CO2, and think it's doing some good. However, more times than not, the offsets do not actually mitigate the amount of emissions they state they will, and some don't mitigate any emissions at all! I would encourage you to think of ways to enhance the transparency & verifiability of the data underlying offsets, to encourage the creation of higher-quality credits.

2. Could you provide more details on M1: IPFS migration? It's not clear to me how this will require $25K and take 2 months. 
> We've developed [CO2.Storage](https://co2.storage/) in a way that makes it very simple to create a data schema and natively store it on Filecoin/IPFS instantaneously. The product (both UI & API) will be ready for users to start testing next week. 

3. Could you provide more details on M2: NFT Minter? It's not clear to me how this will require $50K and take 2 months.
> Both ERC721 & 1155 are standard contracts used regularly and there are plenty of tools that help facilitate the creation of the contracts in a very limited amount of time/effort.

4. Could you provide more details on M3 & M4? It's not clear to me how both of these milestones will require $50K and take 2 months.
> For M3, are you familiar with [Hyphen](https://www.hyphen.earth/)? You may want to check out what they're doing so you minimize duplication of efforts.
> For M4, are you familiar with [IPNS](https://docs.ipfs.tech/concepts/ipns/#interplanetary-name-system-ipns) and [Ceramic](https://ceramic.network/)? You may want to check out what these two options give you for [Mutable NFTs](https://nftschool.dev/guides/mutable-nfts/#background-ipfs-naming-services) so you minimize duplication of efforts.

5. I recommend removing M5, as well as the expenses related to traveling to events and marketing expenses, as they are not relevant to the development of the proposed technical solution.

Looking forward to hearing back!

**Comment by MehighCB** [comment]
Hey Marc,

Thanks for reviewing this, let me come back with answers over the weekend.

Have a good one

**Comment by MehighCB** [comment]
Hello Marc,
Thank you very much for your remarks and feedback, here are a couple of thoughts
about each of the points.
Once confirmed, I will update the repo.
 1. of the vcm if you do not focus on enhancing the quality of the credits
    themselves?
    
    

One of the primary problems with offsets is that, in general, people see an
offset saying it equates to -1 ton of CO2, and think it's doing some good.
However, more times than not, the offsets do not actually mitigate the amount of
emissions they state they will, and some don't mitigate any emissions at all! I
would encourage you to think of ways to enhance the transparency & verifiability
of the data underlying offsets, to encourage the creation of higher-quality
credits.

  The enhancement of the carbon credits themselves is an effort that will go in
parallel with the technological development through the carbon standardization
bodies. We are working with IEEE (the entity that has created the Wi-fi &
Bluetooth standards) to create a universally accepted carbon standard. We
believe that these efforts will bear fruit in the years to come creating a
common understanding of the quality of carbon credits, and dismissing the
credits that don’t actually mitigate emissions. The scope of our product is to
help accelerate a tedious and expensive process, while the quality of the carbon
credits will be ensured by the vetting of the partners and projects that we sell
carbon credits from.




For the rest of the points, I had a look through what you have provided. I will
eliminate the marketing and travel expenses (although I have seen grants that
these kinds of expenditures have been covered) and put together the dynamic NFT
minter combining Hyphen, IPFN and the Ceramic API into one. I will also reduce
the grant requirements from 200k To 50k with a 2-month creation of the minter
and transfer of the IPFS provider. Do you think that is still feasible or should
I broaden the scope for the entire platform and try to find new elements of
innovation?




Thank you




MIHAI HRIMIUC
***@***.***
https://www.carbonbase.co/Hong Kong
Sent with Mixmax  





On Fri, Oct 7, 2022 at 4:33 PM Mihai Hrimiuc ***@***.***> 
wrote:
Hey Marc,
Thanks for reviewing this, let me come back with answers over the weekend.
Have a good one
On Thu, 6 Oct 2022, 23:15 Marc Johnson, ***@***.***> wrote:


Hey @MehighCB, interesting proposal! A few questions/comments:

 1. How will tools that incentive the retirement of carbon credits help
    facilitate the scaling of the vcm if you do not focus on enhancing the
    quality of the credits themselves?

One of the primary problems with offsets is that, in general, people see an
offset saying it equates to -1 ton of CO2, and think it's doing some good.
However, more times than not, the offsets do not actually mitigate the amount of
emissions they state they will, and some don't mitigate any emissions at all! I
would encourage you to think of ways to enhance the transparency & verifiability
of the data underlying offsets, to encourage the creation of higher-quality
credits.

 1. Could you provide more details on M1: IPFS migration? It's not clear to me
    how this will require $25K and take 2 months.

We've developed CO2.Storage  in a way that makes it very simple to create a data
schema and natively store it on Filecoin/IPFS instantaneously. The product (both
UI & API) will be ready for users to start testing next week.

 1. Could you provide more details on M2: NFT Minter? It's not clear to me how
    this will require $50K and take 2 months.

Both ERC721 & 1155 are standard contracts used regularly and there are plenty of
tools that help facilitate the creation of the contracts in a very limited
amount of time/effort.

 1. Could you provide more details on M3 & M4? It's not clear to me how both of
    these milestones will require $50K and take 2 months.

For M3, are you familiar with Hyphen? You may want to check out what they're
doing so you minimize duplication of efforts.
For M4, are you familiar with IPNS  and Ceramic? You may want to check out what
these two options give you for Mutable NFTs  so you minimize duplication of
efforts.

 1. I recommend removing M5, as well as the expenses related to traveling to
    events and marketing expenses, as they are not relevant to the development
    of the proposed technical solution.

Looking forward to hearing back!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: 
***@***.***>

**Comment by mjohnson518** [comment]
Hi @MehighCB, thanks for your thoughtful responses. 

It's still not clear to me how this scope of work will complement your efforts with the IEEE to create a universally accepted carbon standard, and how this grant funding will help enhance the quality of tokenized credits. Can you please further explain your thinking here? 

As for the rest of my feedback, I do think it would be helpful if you limited the scope of your work, and revised the proposal to reflect what core components you anticipate developing. This project is still too vague and broad as currently defined. 

Please let me know if you have any questions!

**Comment by MehighCB** [comment]
Hey Marc,
Thanks for the remarks again, we will come back with a reduction in scope for
the project.In the meantime, CRED Protocol addresses the problem of carbon
market scalability and incentivization at its core.
In regards to the quality of the carbon credits, we have a couple of ways to
ensure the quality of the carbon credits:1. We do the curation of projects
ourselves, either through the partners that we will be working with on the
supply side, or when putting at the disposal the credits from our side (we are
in touch with the project developers on the ground, we verify meticulously each
project that we put)2. The IEEE Efforts are done in parallel, and they are not
subject to the scope of this grant at the moment. By involving a reputable
organization that has worked with standards for decades, IEEE is the perfect
partner to help facilitate the creation of a universal carbon standard. I think
the confusion here comes from the word "standard", which the work with IEEE will
be done, in  creating a universally accepted and recognized way for these carbon
credits to be accepted and used beyond the current misconceptions. The IEEE
standard will not become a methodology for registering carbon credits, but for
recognizing carbon credits, differentiating qualitative ones from
non-qualitative ones, as well as create  trust in them by the larger
population.
I hope these answer your questions.
Have a good one

MIHAI HRIMIUC
***@***.***
https://www.carbonbase.co/Hong Kong
Sent with Mixmax  





On Wed, Oct 19, 2022 at 12:14 AM Marc Johnson ***@***.***>  wrote:


Hi @MehighCB, thanks for your thoughtful responses.

It's still not clear to me how this scope of work will complement your efforts
with the IEEE to create a universally accepted carbon standard, and how this
grant funding will help enhance the quality of tokenized credits. Can you please
further explain your thinking here?

As for the rest of my feedback, I do think it would be helpful if you limited
the scope of your work, and revised the proposal to reflect what core components
you anticipate developing. This project is still too vague and broad as
currently defined.

Please let me know if you have any questions!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: 
***@***.***>

**Comment by mjohnson518** [comment]
Hey @MehighCB checking in to see if you're still interested in revising this proposal? We're interested in this work and would like for you to focus on M1 & M2. The deliverables & ask for M1 look good. For M2, we think the ask should be reduced to 25k. 

Let me know your thoughts!

**Comment by ErinOCon** [comment]
Hi @MehighCB, we have sent you an email to discuss next steps!

**Comment by MehighCB** [comment]
Hello Erin,
Thank you very much, this is great news indeed.
Will follow-up on the separate thread.
All the best

MIHAI HRIMIUC
***@***.***
https://www.carbonbase.co/Hong Kong
Sent with Mixmax  





On Wed, Dec 7, 2022 at 3:01 AM ErinOCon ***@***.***>  wrote:


Hi @MehighCB, we have sent you an email to discuss next steps!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: 
***@***.***>
