### ISSUE TITLE
RFP Application "Forest Maker"

### ISSUE THREAD

**Issue by paulaaguirrefeliu** [filecoin-project/devgrants#1034]
# RFP Proposal: `Forest Maker`

**Name of Project:** **Forest Maker**

**Link to RFP:** Please link to the RFP that you are submitting a proposal for. **Green grant**

**RFP Category:**  `app-dev`

**Proposer:** `https://github.com/GrupoSabra/`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Please respond with either "Yes" or "No" **yes**

# Project Description

Please describe what problem or need your project addresses, why it's important, and your technical approach. Since this is a response to an RFP, make sure to address the request directly. 

This section should be 2-3 paragraphs long.

Lack of adequate funding and the complexity of inclusiveness have been the causes that have prevented the full potential of forests to contribute to the achievement of the Sustainable Development Goals (SDGs) from being unleashed. Investments in forest protection and restoration have historically been limited. In 2019, approximately USD 124-143 billion was committed to biodiversity-focused projects, including forest conservation and restoration, compared to annual needs of between USD 722 and 967 billion. Moreover, only a tiny part of the forest funding comes from the private sector, perhaps less than 5%.

For those reasons, we are putting investors in direct contact with Green developers to democratize forestry investment and provide a triple development impact. Unlock large-scale forest financing through transparent technology, such as blockchain, that provides monitoring and accountability and supports social actions for vulnerable populations. Our solution proposes democratizing nature based solutions (NbS) investments to increase access to private investors. This openness to these financial products will generate inclusive liquidity for project creators of all scales. Furthermore, this innovation would contribute to protecting and regenerating biodiversity and climate action by providing open and transparent tools to increase conservation, deforestation, and regenerative agricultural production.

In order to accomplish that objective, Forest Maker is a WEB3 forest marketplace that connects forestry companies in need of financing for their forestry projects with institutional and retail investors. A FOREST MYNT PROTOCOL will provide forest makers with a simple tool for tokenization of their forestry projects. Also, we intend to implement a SEEDLAUNCH PROTOCOL where forest makers pitch their projects to the investment community by offering competitive liquidity and profitability options. Furthermore, there will be a FORESTKEEPERS PROTOCOL that will generate the incentives to create a global community of forest keepers who will act as validators of forestry projects.

## Development Roadmap

Please break up your research or development work into a clear set of 2-3 milestones.

For each milestone, please describe the software functionality that we can expect after the completion of each milestone. This should be detailed enough that it can be used to ensure that the software meets the RFP scope.

This section should be approximately 1 page long.

**1. Data architecture / IT development suited to the market need** 
( MVP: Tokenization Platform for Green Projects - UX/UI Wallet - Mobile App Framework - Back Office Web - Smart Contracts Implementation)

1.1: In the first MVP which is in progress we have 9 persons + various cross-sectors advisors. 4 people (Grupo Sabra) in the technical area of infrastructure development, 2 people in operations strategy, a legal member and CF0.
We require  15K for this implementation and we estimate 3 months of work.
 
**2. Mobile/ Web App Launch / Market:** 
Tokenization of 1 Forest Maker pilot projects - Approval FINMA Letter (Adapt the structure of the most suitable financial instruments and the appropriate risk allocation and mitigation)
2.1: In the second Milestone we are working in parallel to the first with our PPP Partnership with the ACDI organization. In addition to the 9 people described in Milestone 1, resources will be deployed in the creation and research of a more robust business development team and legal discussions with the various jurisdictions to implement the pilot in Gran Chaco Argentino.
We require  10K for this implementation and we estimate it will be done by february 2023.

**3. Creation of investment platform for Institutional-Grade Safekeeping**
3.1: Once the testing is done with the first project we will tackle the development and upgrade of the platform allowing the ability of financial institutions to be able to invest in Nature based solutions (NbS) in infrastructure suited to their needs and create a marketplace for the secondary financial market.
We require  25K for this implementation and we estimate it will be done by June 2023

## Documentation, Education, and Community

Specify your plans for any documentation, education, and/or community-building that will be essential to your project's success.

Market risks exist; clear evidence is in crises experienced in the past. We will evaluate the chaos that could encompass the entire project on the stochastic impact of financial assets. Besides, we will focus on the systematic risk of natural NbS assets. In addition, a watchful eye for natural and artificial disasters could impact these very fragile assets. Forest Maker provides strict requirements and guidelines on managing the environmental impact.
On the other hand, it's essential for our project success to understand the volume of transactions in the primary and secondary market, and finally, considering that tokens are listed on secondary markets to enhance their liquidity, it's important to evaluate the variation of price offers of carbon tokens on this market.  

## Other Deliverables

Specify any other deliverables proposed as part of this project.

1. Integration with Private Chains (RSK-CARDANO- CELO)
2. Develop proper SDKs and APIs
3. A decentralized exchange where TREE tokens shall become tradable in the future
4. Biodiversity and Conservation bank model

## Milestone Summary

This table should summarize all of the efforts above. For each milestone, please describe:
- Summary of milestone
- How many people will be working on each milestone and their roles
- The amount of funding required for each milestone
- How much time this milestone will take to achieve (using real dates)

| Milestone No. | Milestone Summary & Staffing | Funding | Estimated Timeframe |
| ------------- | --------------------- | ------- | ------------------- |
| 1             | Data architecture & IT development  ( 9 persons + various cross-sectors advisors.)      | $15.000      | 12 weeks             |
| 2             |Mobile & Web App launch (same staff estimation as in milestone 1)     | $10.000    | 20 weeks             |
| 3             | Investment platform for institutional-grade safekeeping    | $25.000      | 36 weeks             |

## Total Budget Requested

Sum up the total requested budget across all milestones.

USD $50.000

## Maintenance and Upgrade Plans

Specify your team's long-term plans to maintain and improve this project over time.

***1. Create a market (short term) (Gran Chaco - Switzerland)***
Forest Maker proposes a bottom-up approach to the economic dynamics related to NbS activities and assets. Inclusive B2BG are targeted as the main actors and models of approach. In addition, we seek solid partnerships and networking activities in line with NbS and ESG models.

Our network currently comprises a diverse range of grassroots and civil organizations, universities, R&D institutes, financial institutions, public policy entities, and businesses, all working together to secure the coexistence of Forest and community in the interests of generating development and inclusion for the Gran Chaco region. 
The initiative that partners with Forest Maker now embraces over 4600 entrepreneurs, 90 organizations, and 57 communities in six provinces of Argentina and has forged alliances with Bolivia and Paraguay. 
A new cooperation agreement with Inter-American Development Bank (BID Lab) recently came into force to support the scalability of [THE FUTURE IS IN THE FOREST](https://elfuturoestaenelmonte.org/#/) by funding a model of collective impact investment to leverage the integral and sustainable development of native forests. Furthermore, we have forged an alliance with IOVLAbs and Celo since the execution of [DeFi 4 Green recovery](https://cl.socialab.com/challenges/defi4greenrecovery) challenge.

***2. PPP partnership with other key organizations in the market to include them in the use of this technology (medium term)***

As soon as we acquire new customers and penetrate new markets, we will make new local and international PPP (Public Private Partnership) partnerships. PPP can provide us with the expansion capabilities for Forest Maker. At this time, we should develop proper SDKs and APIs to turn a closed financial market into an Open source for Replication. The best way is to build in our protocol with suitability to their market and target.
 
We strongly believe that the skills of ACDI and The Future is in the Forest can assure the replication of economic models will be more effective.

***3. Scale up and monitor investissement (Long Term)***

In relation to the possibility to scale up, Forest Maker should guarantee that the integration of ecosystems and inter-mobility is based on common standards. Furthermore, it should allow the integration with Market Wallets so users can operate from any Market Wallet to buy and sell the digital assets generated by Forest Maker. 
In relation to the security, it should guarantee that it is at Smart Contract level: checks on the SC involved in project governance and those representing the assets represented.
Also, it should have Environmental impact project certifiers to integrate the information model that certifies that what we propose in the virtual world exists in the physical world. (Integrate satellite imagery services of tokenized plots to establish the level of progress of the forestry project).  It may require sufficient availability of reliable and efficient certifiers that can support the project at a reasonable cost.
Finally, Forest Maker could offer the distribution of rewards in stablecoin to Token Tree holders from the positive flows that their project has; the generation of a third-social token if the payment for results is assured (bonus social impact), for example by generating jobs in vulnerable communities.

On the other hand, for the MRV of the investissement of the project is important to consider:

- Drivers: Populations/ Regional Stability/Scenarios
- Socio Economics Data
- Policies & Climate action
- Biogeographical & climate impact
- Use of capital and resources to mitigate climate change (internal and external environment)
- Break-even point
- Net income ratio
- Leads, conversion and bounce rate
- ROI and ROAS
- Turnover & employment 
- Conversion rate: Net promoter score (NPS) Customer lifetime value (CLV)
- CO2 Offset
- Transactions Volume in Primary and Secondary Market 
- Interoperability with other infrastructure
- Known risks

# Team

## Contact Info

Provide us with a way to contact you (email is probably easiest). You can also email grants@filecoin.org with your GH username and link to your public proposal.

paulaaguirrefeliu@gmail.com

## Team Members

- Team Member 1 - [Mauricio Moresco](https://www.linkedin.com/in/mauriciomoresco/) from ACDI NGO
- Team Member 2 - [Harpalium Initiative](https://ch.linkedin.com/company/harpalium)
- Team Member 3 - [Grupo Sabra](https://www.linkedin.com/company/grupo-sabra/)
- Team Member 4 -  [Paula Aguirre](http://www.linkedin.com/in/aguirrepaula) from ACDI NGO

## Team Website

Please link to your team's website here.

[ACDI](https://acdi.org.ar/)
[Grupo Sabra](https://www.gruposabra.com/)

## Relevant Experience

Please describe (in words) your team's relevant experience, and why you think would do a great job with this RFP. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

Three organizations with specific skills and knowledge critical for this NbS industry have come together to create Forest Maker that will radically change the concept to align individual incentives for a global response to climate change. A tool to restore harmony between nature and humans.

[Grupo Sabra](https://www.linkedin.com/company/grupo-sabra/): Grupo Sabra is a Blockchain Solution company focused on integrating traditional technology with Distributed Ledger Technologies. We are followed by the founder, Pedro Perrota and Alejandro Wyss, whose strong knowledge and dedication guided us through this ambitious goal.

[Harpalium Initiative](https://ch.linkedin.com/company/harpalium): Collaborative design-thinking methodologies and human- and nature-centered approaches are the essences of the Alliance. We collaborate with various actors and organizations in the 2030 Agenda ecosystem. We believe that co-innovation provides the capacity to increase knowledge and to share essential information to advance the Agenda's goals. We firmly believe in the SDGs' ambitions to "Envisage a world free of fear and violence. A world with universal literacy. A world with equitable and universal access to quality education at all levels, to health care and social protection, where physical, mental, and social well-being are assured," is to be taken with a cooperative mindset.

[ACDI](https://acdi.org.ar/) (_Asociación Cultural para el desarrollo integral_): an argentine NGO that promotes social development centered in the human person and innovation and partnership as its method. ACDI has a technical cooperation with the IDB Lab and an alliance with RSK-IOV Labs to build the technological base of decentralized digital applications that support the governance processes of common goods, align incentives and channel global resources towards local initiatives that allow to drive more investment and credit towards business models and ventures that promote a low-carbon economy. In that context, ACDI has been accompanying a development process for the most vulnerable communities in the Gran Chaco Americano region introducing technological innovations and generating sustainable opportunities for these population to overcome their situation of poverty while conserving the natural resources of this great region of global importance for the fight against climate change.

We have all the capabilities to fulfill our mission on the technical and strategic front.

## Team code repositories

Please provide links to your team's prior code repos for similar or related projects.

_[Self sovereign digital identity project](https://github.com/ACDI-Argentina/identidad-digital/wiki)_
_[Avaldao](https://github.com/ACDI-Argentina/avaldao/wiki)_

# Additional Information

Please include any additional information that you think would be useful in helping us to evaluate your grant application.
![Forest Maker Mappa](https://user-images.githubusercontent.com/106391451/193053629-19700c5f-5a2a-4819-bbad-519f1e6e69a4.png)

**Comment by ErinOCon** [comment]
Hi @paulaaguirrefeliu, thank you for your patience with our review. We will not be moving forward with a grant this round, but would encourage you to consider applying for RFP opportunities in the future. Wishing your team the best as you continue building!

**Comment by paulaaguirrefeliu** [comment]
Thank you Erin for your reply. Hope we can apply in the future for other opportunities!
Regards
