### ISSUE TITLE
FUTR: Data-to-Earn Ecosystem

### ISSUE THREAD

**Issue by futrnetwork** [filecoin-project/devgrants#1036]
# Open Grant Proposal: `FUTR NETWORK`

**FUTR NETWORK:**

**Proposal Category:** app-dev

**Proposer:** `futrnetwork`

**(Optional) Technical Sponsor:** @jenks-guo-filecoin

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes
We will open source all of our smart contracts, Filecoin integration libraries, and all other non-proprietary software that does not pose a threat to our users' security or compliance/regulatory requirements. 

# Project Description

In 2021 Google generated $209 billion from digital advertising, Facebook generated $115 billion, and users made ZERO. FUTR’s mission is to allow people to **Monetize Their Personal Information** – and break away from the monopoly big-tech currently has on the sale of their personal information, data, and documents.

FUTR’s bank-grade (SOC 2 Type 2) Personal Life Management Vault™ allows users to seamlessly store and manage their personal information (banking, financial, legal, tax, etc) saving users time and effort every time they use their vault, while also letting users earn $FUTR tokens for every document they store.

In addition to earning $FUTR for each document they store, users can opt-in to consent tracking, allowing third parties to pay them with $FUTR tokens for each datapoint they want to access. FUTR will be the first zero-party data marketplace that allows users to transact directly with third parties. 

FUTR’s Digital Vault technology is powered by FutureVault. FUTR Network was born out of FutureVault Inc. FutureVault pioneered the Personal Life Management Vault™ space and has developed the most advanced and secure Digital Vault on the market. Operating as a SaaS company focused on designing, developing, and commercializing Personal Life Management Vault solutions, FutureVault the company works with some of North America’s most senior and trusted financial service firms as customers including (CI Financial, BlueShore Financial, Coinsquare, and Coinsmart). FutureVault has invested over $24 million into R&D to build its’ SOC 2 Type 2 secure vault technology. FutureVault is a modern platform that integrates with several software solutions including DocuSign, Zapier, and Salesforce.

FutureVault has four total patents, two of which have been granted and two are pending:

	1. GRANTED – Systems and Methods for Sharing Documents (No. 62/383,301 - Application US20180068010A1)
	https://patents.google.com/patent/US20180068010A1/en?assignee=futurevault&oq=futurevault
	2. GRANTED – Automated Document Filing and Processing Methods and Systems 
	(No. 62/383,284 - Application US20180067957A1)
	https://patents.google.com/patent/US20180067957A1/en?assignee=Futurevault+Inc
	3. PENDING – Real-Time Document Filtering Systems and Methods (No. 62/383,293 - Application US20180067932A1)
	4. https://patents.google.com/patent/US20180067932A1/en?assignee=Futurevault+Inc
	PENDING – No. 63/225,659: Systems and Methods for Document Hierarchy Permissioning

FUTR is leveraging FutureVault's vault technology as the base layer of its Data-to-Earn ecosystem to allow people to monetize their personal information while keeping it secure within Bank-Grade Digital Vaults.  

FUTR intends to build the first Web2-Web3 bridge to allow users to seamlessly move their **data & documents of permanence** from a FUTR vault onto Filecoin's document storage protocol. Such data & documents will be encrypted and stored on FileCoin’s decentralized storage, represented on the blockchain by the data hash, which ensures complete document authenticity. The data hash uniquely identifies the data itself and also incorporates authorization mechanisms to ensure the privacy of the data. 

Shown below is the architecture flow diagram for FUTR. Our whitepaper referenced in additional resources explains the complete functionality of how blockchain is integrated, and here we focus on the filecoin integration. FUTR establishes proof of data ownership, the trail of data transfer, and data value over the blockchain and to achieve this, user data is hosted over decentralized storage to provide trust, transparency and stronger user security. 

![Filecoin Integration (1)](https://user-images.githubusercontent.com/114413511/194073838-b524cdc4-4baa-4fdf-b8c8-05aca9201158.png)

FUTR is a tool built for the masses, meaning a large percentage of non-blockchain users will be introduced to blockchain and filecoin for the first time through the FUTR app. This makes FUTR an ideal onramp into decentralized document storage solutions like Filecoin. Our goal is to build an integrated connection between FUTR and Filecoin so our users have a seamless option for bringing their documents into Filecoin and benefiting from the system’s advantages of transparent accounting which is encrypted and as well as greater security. This bridge will be additionally useful to users to understand more about the decentralized storage ecosystem and its benefits including files that are transparently encrypted with proof. 

The FUTR system protects data represented on the blockchain from several core issues which will be possible as a result of how filecoin is currently built: 

1. Ownership 
Users should own and have full access over the data they have shared providing access rights to systems which are necessary as per the agreed terms. 

2. Transparency 
Users should be able to transparently observe data access and sharing happening over the ecosystem. 

3. Traceability
Users should be able to audit the data transfer that has happened historically for the data they own. 

4. Authorisation
Users should have access control over the data they own to grant or revoke permissions. 

Every file uploaded on Filecoin is first encrypted by a user-generated key ( ukg) for each file which is further encrypted with the user's private key and persisted over the blockchain. Such personal documents are unusable to any system participant without the decryption key. Any further sharing outside the ecosystem can be done only by the user or users can opt to delegate the transfer rights to a system wallet. 

To make such a transaction happen, the data owner simply shares an encrypted user-generated key ( ukg ) which can be decrypted only by the wallet's owner receiving the file utilizing the public key cryptography technique. 

FUTR maintains its own cache of such data as well as a filecoin pin server to ensure speed, consistency, and availability with user data.

## Value

A) FUTR’s Data-to-Earn ecosystem represents a new customer pipeline for Filecoin with the potential to drive millions of new users and documents into the Filecoin ecosystem.  
FUTR’s target audience is a key demographic of 21-35, this audience creates the opportunity to bring thousands of new document types into Filecoin’s ecosystem **including, but not limited to:**   

1. **Documents of Permanence:**  
   * Documents of Achievements 
   * Birth Certificate. 
   * Adoption Papers
   * High School Diploma
   * University Degree
   * Undergraduate Degree 
   * Masters Degree
   * PHD  
2. **PII Information (Personal Identifiable Information)**
   * Passports/ID Cards
   * Drivers licenses
   * Health Cards
   * Social Security Cards
   * Proof of Address
   * Etc.    
3. **Mortgages & Homeowner Information**
4. **Banking Information**
   * Personal Line of Credit
   * Credit Card Statement
   * Credit Score
   * Etc. 
5. **Insurance**
   * Health Insurance
   * Life Insurance 
   * Home-Owners insurance
   * Long-term Disability insurance
   * Pet insurance
   * Travel Insurance
   * Flood Insurance
   * Etc. 
6. **Medical bills and health reports**
7.  **Tax Information**   
     * W2
     * 1040
     * T4
     * 1099
     * Etc. 

B) The Web2-Web3 bridge will allow Filecoin to integrate with a technology that is already connected to legacy software solutions including Docusign, Zapier, and Salesforce, making Filecoin more ubiquitous and accessible across traditional Web2 tools and services.   
 
C) FUTR plans to integrate with other business API’s including WhatsApp, Gmail, DropBox, and Imessage/Airdrop. **Upon completion, Filecoin will be connected to millions of new potential users through FUTR.**  
  
D) FutureVault exposes a number of RESTful APIs for third parties like Filecoin to access key functionality within the platform. Single Sign on capabilities are supported via SAML 2.0 or OpenID Connect.

## Deliverables

1. Features:  
   * Personal Life Management Vault  
     * Document storage
     * Document Scanning and Filing
     * Data Monetization/Consent Tracking Opt-In

<img width="360" alt="Screen Shot 2022-09-30 at 12 13 06 AM" src="https://user-images.githubusercontent.com/114413511/193116978-7eebf3ef-ccda-454f-9ada-a3b20a469509.png">

   * Data Independence Tool
     * FUTR’s technology empowers users to control and monetize their data  

<img width="248" alt="Screen Shot 2022-09-30 at 12 19 03 AM" src="https://user-images.githubusercontent.com/114413511/193117334-feafd364-e3ef-438f-9e8c-07ab8fc3a21e.png">

   * Token Wallet
     * Send/Withdrawal
     * Connection to RFP Portal
     * Connection to Personal Life Management Vault

<img width="278" alt="Screen Shot 2022-09-30 at 12 19 50 AM" src="https://user-images.githubusercontent.com/114413511/193117470-561b1735-5e40-48a4-a748-10fd6455329c.png">

   * Two-Sided Marketplace
     * Consumers sending opt-in data to the marketplace
     * Business inputting specific requirements/traits for data purchase
     * Sales dashboard where businesses can place a bid on data sets
     * Tracking and reporting dashboard for businesses to track conversion and success
     * Wallet integration so customers can earn $FUTR in real time
<img width="472" alt="Screen Shot 2022-09-30 at 12 20 29 AM" src="https://user-images.githubusercontent.com/114413511/193117685-ea6f8182-1fed-4ca5-9c8d-093cc035c2d8.png">

  * RFP Portal
      * Dashboard where users can shop for highly personalized deals based of the data they have monetized
      * Dashboard where businesses can launch highly personalized deals directly to end users that are based on the data they have opted-in to sharing.

<img width="229" alt="Screen Shot 2022-09-30 at 12 21 23 AM" src="https://user-images.githubusercontent.com/114413511/193117847-d5a3cdf5-6618-4505-abb6-9d374850bca6.png">

 
### Personal Life Management Vault™

The personal vault consists of a cloud-based storage solution that enables users to securely store and manage all their personal and professional documents. The vault can include pre-populated “suggested” folders or users can create their own taxonomy. Once documents are placed in the vault, they are scanned with FutureVault’s patent protected **(‘Document Filing and Processing Methods and Systems US20180067957A1’)** machine learning algorithm to sort and extract relevant data points to:

1. Assign a value to the document
2. Recommend what folder the document should be stored in. 

For example when a user uploads their car insurance policy that document will be automatically scanned and a recommendation for where to store the document will be made. $FUTR tokens will then be automatically deposited to the users FUTR wallet based on the market-value of a car insurance policy. 

<img width="480" alt="Screen Shot 2022-09-30 at 12 22 23 AM" src="https://user-images.githubusercontent.com/114413511/193118100-577b0ac2-6352-48c1-89b6-d8dc099c6e3c.png">

FutureVault Inc. prides itself on having robust technology. Ten key pillars of that techstack are described below 

#### 1. Multi-Tier Platform
<img width="885" alt="Screen Shot 2022-09-30 at 12 23 36 AM" src="https://user-images.githubusercontent.com/114413511/193118247-04e79eac-d055-4aac-aa87-bd642a248353.png">

#### 2. Automated Vault Creation & Document Filing

Using any e-signature protocol FutureVault automatically creates a new Vault (or folder in an existing Vault) and automatically deposits documents within specified filing locations upon completion of signing. 

<img width="747" alt="Screen Shot 2022-09-30 at 12 24 11 AM" src="https://user-images.githubusercontent.com/114413511/193118392-42784570-5d6d-4c58-8788-629705a97441.png">

#### 3. Customized Check Listing

Advisors customize a check list of documents for clients to provide to prepare a Financial or Estate Plan and when uploaded are automatically deposited into the client Vault.

<img width="484" alt="Screen Shot 2022-09-30 at 12 25 03 AM" src="https://user-images.githubusercontent.com/114413511/193118562-22bc97cb-0769-46fc-aa0d-563150f93911.png">

#### 4. Integrations Connecting the Disconnected

FutureVault is a modern platform with restful APIs permitting integrations with any and all platforms to assimilate documents and data in the Vaults.

<img width="412" alt="Screen Shot 2022-09-30 at 12 25 56 AM" src="https://user-images.githubusercontent.com/114413511/193118671-24b71cba-2052-452c-8fdc-5dfe063f10e7.png">

#### 5. Custom Inbound-Only Ingestion Email Address

All Vaults have an inbound-only email address. Vault holders receive a notification when documents have been emailed into their Vault. Ex: After donating $500 to the cancer society, a Vault holder would provide this email address for the tax receipt to be automatically deposited into their Vault. 

<img width="744" alt="Screen Shot 2022-09-30 at 12 26 53 AM" src="https://user-images.githubusercontent.com/114413511/193118873-352169f3-64d3-4c84-b8a6-819da486f00d.png">

#### 6. AI-Driven AutoFile Suggestion Engine

FutureVault’s patented AI AutoFile provides Filing Suggestions after reading documents (including hand writing) to determine what they are. 

<img width="569" alt="Screen Shot 2022-09-30 at 12 27 37 AM" src="https://user-images.githubusercontent.com/114413511/193119196-10bfc69d-17b9-47ea-84a7-c5ec26531f87.png">

#### 7. Dynamic Visualization of Household Documents via Multiple Entities

Vault holders can have multiple sub Vaults (Entities) for family members, holding companies, Trusts, etc and the platform’s patent pending technology provides dynamic visualization of some or all of the Entities. 

<img width="726" alt="Screen Shot 2022-09-30 at 12 30 00 AM" src="https://user-images.githubusercontent.com/114413511/193119423-8be604b7-a819-41d2-b174-b7378bbe5461.png">

#### 8. Automated Intelligent Reminders
FutureVault makes it easy to automate reminders for simple things like renewing a health card, passport, outdoor card, Nexus, and drivers license, with reminders going to emails and/or texts to multiple recipients.
<img width="500" alt="Screen Shot 2022-09-30 at 12 30 37 AM" src="https://user-images.githubusercontent.com/114413511/193119543-3dd773f7-9ef2-431d-91b4-80637eb17b32.png">

#### 9. Third Party Permissioning of Trusted Advisors
FutureVault’s patented technology permits constituents of each tier to permission-in Trusted Advisors and stakeholders to discrete elements of the Vault with a complete fiduciary trail of all activity logged in perpetuity.
<img width="616" alt="Screen Shot 2022-09-30 at 12 31 21 AM" src="https://user-images.githubusercontent.com/114413511/193119665-44f44bd0-e761-4191-8317-d274d56837d5.png">

#### 10. Integrated Marketplace Optionality
Advisors/Agents can select, customize and deliver a suite of products and services offerings directly to their clients through an integrated marketplace through the platform. By virtue of key documents being stored in a client Vault, permissions to obtain products and services can take place automatically as the Vault automatically accesses the requisite documentation and approvals happen in real-time. 
<img width="450" alt="Screen Shot 2022-09-30 at 12 31 50 AM" src="https://user-images.githubusercontent.com/114413511/193119753-eec846e9-81da-48b8-8a03-25b6c23f0fa8.png">

 

### Data Independence Tool  
FUTR’s Personal Life Management Vault allows users to control and monetize their personal information. For the first time ever, users will have the option to opt into consent tracking and have third-parties pay them directly for their personal information and data. FUTR’s data independence tooling enhances FUTR’s personal life management vault beyond just securely storing personal information and data, making these vaults the gateway into the data-to-earn economy.  

### Token Wallet
FUTR’s native wallet will hold $FUTR to allow users to seamlessly earn tokens from the vault, and spend it on the RFP portal.
 
1. The Token  
Users will earn $FUTR, the native digital asset within FUTR for the following actions
 * Opening a vault (signing up to the platform). 
 * Uploading a document (once it’s scanned and validated)
 * Sharing data points with third parties
 * Referring a friend
 * Amplifying on social 
 
2. Consumer Marketplace
 
The consumer marketplace is where consumers consent to share their personal information with third parties. Businesses can search, identify and purchase leads from the data that vault holders have made available. Enterprise Partners can pay for leads with fiat or $FUTR tokens. They will receive a 20% data bonus when they make their purchase with tokens. Even though they are purchasing zero-party data (data directly from the source), this data is grouped together and packaged into various behavioral, demographic, geographic, economic, and psychographic traits. Allowing businesses to acquire highly targeted personal information, while allowing users to stay pseudonymous. 
  
3. RFP Portal

The RFP Portal is where users can go to receive offers and opportunities from enterprise partners based on the data they’ve shared with the platform. For example, if their insurance policy is up for renewal, they will receive targeted offers for new car policies that they are eligible for based on the info in their vault. Businesses are also able to list generic/evergreen offers in the RFP portal for all platform users to browse and engage with. 

## Development Roadmap

FUTR will launch a commercially viable consumer mobile application and enterprise desktop platform within 6 months. The milestones below can be achieved in parallel and on expedited timelines with appropriate capital and resources. 

###### Description:
Following *Filecoin related integrations* will be done in this milestone: 
 * User will be able to persist their documents over Filecoin  
 * User will be able to fetch their documents from Filecoin  
 * User ownership proof of file will be established over blockchain as well  
 * User filecoin document hash will be encrypted and persisted via user private key over blockchain  
 * Users can share files with other users in the ecosystem. A copy of the encrypted hash via other user's key pair will be persisted over the blockchain so that document privacy and accessibility are achieved    
  
  
App backend infrastructure that securely integrates with the current vault and uses Filecoin as an additional vault for the user-opted onchain data storage. The FUTR app will help users understand the cost and security advantages of using Filecoin, while introducing them to the advantages of using FUTR which include AI automated file storage, earning $FUTR, and receiving custom offers through the RFP Portal. FUTR will enable users to interact with Filecoin via their encrypted keys and users will be able to share such data over the blockchain. To achieve this objective, FUTR will build an integration layer with Filecoin. This layer will connect users directly via their social login, providing them a seamless experience through the browser that allows them to upload files just as they would on their local FUTR folders. 
User-side application that enables users to store their documents in a FUTR Personal Life Management Vault. Users will get pre-populated or “suggested” folders that users can drop their personal documents into, they can also create their own folders. Application will also utilize FutureVault’s existing infrastructure to extract relevant metadata from the storage to assign a market value for every document shared. 
###### People: 
UX Designer, Product Manager, CTO, Product Manager, Blockchain Engineers, Backend Engineer, FutureVault team
###### Grant Required: 
50000 USD
###### Time: 
12 Weeks

###### Description:  
Following *Filecoin related integrations* will be done in this milestone: 
 * User will be able to get $FUTR tokens for files persisted over Filecoin   
 * User will be able to trace the trail of file sharing    
 * User will be able to transparently track the $FUTR tokens transferred to them for sharing their data as per tiers mentioned in white paper    
 * File copies will not be replicated but the same document hash id will be encrypted with the key pairs to whom the file needs to be shared   
 * Enterprises will be able to establish proof of ownership as well as the trail of transactions over blockchain for all filecoin documents.       

  
Once docs are placed in the vault, they are scanned by the platform, and individual data points are extracted. For example, a user’s car insurance policy will be scraped to identify the expiry date, vehicle, monthly premiums and other valuable data points to determine how valuable the document is. Users can then consent to have this data accessed by third parties. When this data is accessed, they will earn additional $FUTR tokens based on the value of the data shared.
Blockchain-based campaigns engine allows users to earn $FUTR tokens when they exchange data with third parties.The campaign engine will allow third parties to create rules for using these data points and launch targeted offers through the RFP Portal with enterprise dashboard .
Blockchain-based campaigns engine allows users to earn $FUTR tokens when they exchange data with third parties.The campaign engine will allow third parties to create rules for using these data points and launch targeted offers through the RFP Portal.
Blockchain wallet for users that enables inflow and outflow of $FUTR tokens from uploading documents, plus tokens that come from third-party data transactions. All token inflows and outflows will be verified over the blockchain with the ability to also withdraw and spend $FUTR from their wallet.

###### People: 
Product Manager, Blockchain Engineers, Backend Engineer, FutureVault team, Apps Team, CTO, Data Team
###### Grant Required: 
50000 USD
###### Time: 
18 Weeks

## Total Budget Requested

We will require a total of 532k USD to build the app. We request a grant of 100k USD from Filecoin

## Maintenance and Upgrade Plans

We will hire the team full-time. We are building a consumer application which means we will be constantly incorporating user feedback to ensure we are adequately addressing pain points and successfully building the world’s first zero-party data storage and exchange ecosystem.

# Team

### G. Scott Paterson - Executive Chairman, Co-Founder 
* 20+ Years as Director of Lionsgate Entertainment
* 3x nine-figure exits
* Canada’s Top 40 Under 40
* Recognized as ‘One of Canada’s 21st Century Leaders’ by TIME Magazine
* EY Entrepreneur of the Year

### Hunter Scharfe - Director, President and Co-Founder
* Capital Markets Professional and Entrepreneur with over $100 million capital raised
* Two TSX IPO exits
* 8+ capital market transactions completed
* Sector experience across blockchain, technology, and media

### Parag Arora - Chief Technology Officer
* 35 under 35 Member on Entrepreneur.com
* Founding team member of the decentralized entertainment platform
Xfinite.io
* Founding member of the YCombinator backed tech startup ‘Glowing.io’

### Eric Shedlevsky - Head of Product
* Head of Operations, Eye Turn Marketing
* VP Client, EQ WorksSuccess
* Co-Founder & Head of Operations, Tapped Mobile
* Co-Founder & COO, Blue Haze
* Former advertising manager for Shazam Canada

### Daniel Kenny - Director, CEO of FutureVault 
* CEO & COO of FutureVault
* 20+ years as COO & Managing Director for the Global Banking and Markets business of HSBC Canada

### Justin Hartzman
* CEO & Co-Founder of CoinSmart (SMRT.NE) a publicly traded cryptocurrency exchange
* Successfully exited four multimillion dollar businesses
* Respected crypto, Web3, and all things internet thought leader

### Doug Barker - EVP, Enterprise Sales
* Analyst at Paterson Partners
* Digital Consulting Background
* Focus on Sustainable Development and ESG practices 

### Gene McBurney - Council Member at FUTR Foundation
* 25+ Years in Investment Banking catering to the Caribbean and Latin American Markets with a focus on mining and natural resources

### Swaneet Singh - Director at FUTR Ltd. 
* CEO, Xfinite.io
* 10 Years within Investment Banking at Goldman Sachs
* Former head of Strategy at Eros International PLC

### Jim ​​Allan - Director at FUTR Ltd. and Council Member at FUTR Foundation
* Partner at Trinity Atlantic Capital, Ltd.
* Director of Dark Horse Capital, Ltd.
* President of Roundtable Asset Management, Ltd.Z

## Advisory
* **Agilno:** Agilno helps companies build custom software solutions for web & mobile. The team has expertise across Node.js, Typescript, Python, Django and React.js and Solidity development. The team is based out of Canada and Croatia.  
* **GDA Capital:** GDA Capital is a blockchain venture incubator, successfully working with 20+ projects and raising over 100M for their clients in specialized private placements. 
* **Zuber Lawler:** Zuber Lawler is one of the most selective law firms in the United States, representing clients throughout the world from offices in Austin, Chicago, Denver, Los Angeles, Phoenix, New York, and Silicon Valley. Zuber Lawler focuses on M&A, finance, and other deals; IPOs; intellectual property; antitrust, data/privacy, FDA, anti-corruption, and other regulatory work; and litigation.
* **Graham Thompson:** Graham Thompson (GT) prides itself on its unique combination of expert legal skills and real-world experience in working out effective solutions to complex problems. With more than 70 years of continuous history and a first-rate balance between seasoned practitioners and dynamic young lawyers, GT is excellence-driven in every way.
* **Revelin7:** Center of Excellence for blockchain products led by YCombinator alumni and engineering leaders. With more than 7 years of experience in blockchain, Revelin7 has worked on remarkable products like Xfinite, Poynt ( acquired by Godaddy ), Trivver, TrakInvest, etc.
 

## Team Member LinkedIn Profiles

1. [https://www.linkedin.com/in/gscottpaterson/](https://www.linkedin.com/in/gscottpaterson/)
2. [https://www.linkedin.com/in/hunterscharfe/](https://www.linkedin.com/in/hunterscharfe/)
3. [https://www.linkedin.com/in/paragarora/](https://www.linkedin.com/in/paragarora/)
4. [https://www.linkedin.com/in/ericshedletsky/](https://www.linkedin.com/in/ericshedletsky/)
5. [https://www.linkedin.com/in/daniel-s-kenny/](https://www.linkedin.com/in/daniel-s-kenny/)
6. [https://www.linkedin.com/in/justinhartzman/](https://www.linkedin.com/in/justinhartzman/)
7. [https://www.linkedin.com/in/douglas-barker/](https://www.linkedin.com/in/douglas-barker/)
8. [https://www.linkedin.com/in/gene-mcburney-17381a159/](https://www.linkedin.com/in/gene-mcburney-17381a159/)
9. [https://www.linkedin.com/in/swaneet/](https://www.linkedin.com/in/swaneet/)
10. [https://www.linkedin.com/in/jim-allan/](https://www.linkedin.com/in/jim-allan/)

## Team Website

[https://futrnetwork.com/](https://futrnetwork.com/)  
[https://www.futurevault.com/](https://www.futurevault.com/)  
[https://gscottpaterson.com/](https://gscottpaterson.com/)   

## Relevant Experience

1. The technology team that built FutureVault are advisors to the FUTR team. As we integrate their vault technology into FUTR, we will have direct access to the team that built this technology from the ground up.
2. FUTR CTO Parag Arora was previously CTO for XFinite/Mzaalo; a tokenized content streaming platform in India. XFinite pays users Mzaalo tokens each time they watch content from their catalog. The project uses very similar token mechanics and game theory. Parag’s experience building XFinite and using the ‘to-earn’ token model will be a key asset as we build FUTR’s Data-to-Earn marketplace.
3. FUTR has partnered with GDA Capital as their blockchain advisor. GDA Capital is a blockchain venture incubator, successfully working with 20+ projects and raising over 100M for their clients in specialized private placements. 

## Team code repositories

1. XFinite (Watch-to-Earn tokenized entertainment app) - https://github.com/xfinite-io 
2. CoinVoting - DAO tool to take decisions https://github.com/adopterscc/coinvoting-caas 
3. Adopters Infrastructure - User onboarding utilities built on Solidity https://github.com/adopterscc/infrastructure 
4. Verime Token Project - KYC over blockchain solution https://github.com/parag-arora/VRM 

# Additional Information
Jenks referred us.  
parora@futrnetwork.com  
Link to FUTR Data Room -> [https://gdacapital.docsend.com/view/s/me4p28tfnmnzcvh5](https://gdacapital.docsend.com/view/s/me4p28tfnmnzcvh5)

**Comment by jenks-guo-filecoin** [comment]
Hi @futrnetwork thanks for your proposal. I don't see specific of how Filecoin storage is integrated into the system, it's important in this project. Providing some architecture diagram or explain the technical details will help a lot. 

What stage is the project currently at? Has a prototype been built already? Or the product is close to launching?

**Comment by futrnetwork** [comment]
Hi @jenks-guo-filecoin 
I have updated architecture diagram and how filecoin will act as foundation user vault for the FUTR application. 

Currently we are at the prototype building stage. We will be launching a go-to-market product in next 4-6 months.

**Comment by parag** [comment]
Hello @jenks-guo-filecoin 

Following up on the above. 

Thanks Jenks

**Comment by jenks-guo-filecoin** [comment]
Hi @parag, thanks for updating the information. We will review and get back to you next week. 

Please note I will also need to sync with grants team and it might take some time before we can achieve a grant decision. :-) Thanks for being patient with us.

**Comment by xfiniteio** [comment]
Hello @jenks-guo-filecoin, following up on this. Thanks Jenks.

**Comment by futrnetwork** [comment]
Hello @jenks-guo-filecoin , let us know if you need anything else from our side or what are the next steps?

**Comment by ErinOCon** [comment]
Hi @futrnetwork, I hope all is well! I am closing this issue as the review was conducted last year. Our records reflect our final update was submitted by email in January, but please let me know if you had any trouble receiving the email or have any questions.
