### ISSUE TITLE
Next Step Microgrant: CreatorLabs

### ISSUE THREAD

**Issue by itsanishjain** [filecoin-project/devgrants#1039]
### 1. What is your project? (max 100 words)
Support your favorite content creators and earn rewards that's the motto of creator labs, a tool that allows anyone to send their Mattic in a very simple and intuitive way to their favorite content creators and earn rewards.

### 2. Project links
  
Link to GitHub repo: https://github.com/itsanishjain/CreatorLabs
Link to demo or website: https://stake-labs.vercel.app/
License: MIT license
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

Users upload their content to IPFS, and subscribers get the dynamic NFT whenever they support the creators so for all the user data we are using IPFS. 
We are creating encryption for data as well as for storing private data on IPFS so only real supporters opt for the content

  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

-  As of now, there is nothing for content creators to keep track of there their audience so building an admin panel for them is my number 1 priority.
- for the audience, there is no easy way to find their favorite content creators.
- integrations seem really powerful features for this app it works like anyone with just 1 click added this to their social media as we do with Patreon. hence encourages mass adoption.
- using funds to build better UI/UX
- Strong integration with IPFS and adding a encryption layer for storing private data. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, we agree to provide the grant reports.

  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes, it does comply with the code of conduct

### 7. Links and submissions

Winner for: [Polygon BUIDL IT : Summer 2022](https://buidlit.devpost.com/)
CreatorLabs: https://devpost.com/software/creatorlabs
  
### Additional questions:
* For each team member(s), please list name, email, GitHub account, and role in the project.

	Name: Anish Jain
	Email: [helloanishjain@gmail.com](mailto:kushagrasarathe@gmail.com)
	GitHub: https://github.com/itsanishjain
	Role: Full stack blockchain developer

* How did you learn about our microgrant program?
	My friends told me about the grant program 
	
* If your project was created as part of an event or hackathon:
	[Polygon BUIDL IT : Summer 2022](https://buidlit.devpost.com/)

  * Please link to your hackathon submission
	https://devpost.com/software/creatorlabs

**Comment by ErinOCon** [comment]
Thank you for your proposal! This grant has been approved. Look out for an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by itsanishjain** [comment]
Hey Thanks for the grants

**Comment by ErinOCon** [comment]
Hi @itsanishjain, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

**Comment by itsanishjain** [comment]
Hey sure I will update you guys by the end of the week thanks
