### ISSUE TITLE
Twinquasar-Celeste - European Green Hosting Offer

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/devgrants#1042]
# Filecoin Green Grant proposal

To submit a proposal, please create a PR against this template in this repo. Please title your file `open-proposal-title.md`, replacing `title` with the name of your project.

# Open Grant Proposal: `Filecoin Green - Green Hosting Offer`

**Name of Project:** `Filecoin Green - Green Hosting Offer`
**Proposal Category:** `Green`
**Proposer:** `Twinquasar & Celeste`
**Technical Sponsor:** `Marc Johnson`
**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** `Yes`

# Project Description

**Twinquasar in collaboration with Celeste to propose an European green hosting offer, tailored for and dedicated to Filecoin Storage Providers.**

Our main objective is to provide to Filecoin Storage providers and investors a green and cost effective hosting offer, leveraging Paris strategic position in EU and France low price access to renewal energy.

### 1. End user proximity

Paris is a major IP transit Hub with super low latency connectivity to all the major cities in EU (447M people) which represent 30% of the Global datasphere; it's the largest market of data consumers and data producers in the world (twice bigger than US)

![image](https://user-images.githubusercontent.com/30711794/193344087-d0fe15f3-0d72-4b46-858d-2c83e82b7d7f.png)

#### a. France is a worldwide leader in renewal energy; ~90% of the french production is renewal.

![image](https://user-images.githubusercontent.com/30711794/193344106-61554ffa-fb24-427e-827f-8157966b16e2.png)

#### b. France is the bigger exporter of electricity in EU

![image](https://user-images.githubusercontent.com/30711794/193344128-d7ce9561-52bf-414c-8a48-01e58dedf3db.png)

### 3. Local regulation and GDPR

France has a strong local regulatory environment with regards to RGPD and data protection.
Hosting in France is a key position to address european market where regulation is less restrictive.

## Target customers

- Storage Providers of any size from a few racks to multiple cabinets.
- Investors looking to invest in longterm Filecoin Storage Providers. 
- For any geographies :
	- European SPs will get a turnkey environmental impact free offer tailored to Filecoin
	- Foreign SPs without local presence will be able to easily extend to EU and find the best place to settle in EU with a strong and reputable local Filecoin expertise.

## Our "Filecoin Green hosting" offer highlights

Celeste launched the first ecological high density DC in the world back in 2011 introducing the FreeCooling patented technology allowing -35% power consumption for cooling.

#### 100% Green energy certified (solar panel)

- Transparent energy production and consumption for Filecoin racks.
- Burst consumption above solar production, will be covered by green energy from the grid (with certificate).

#### Disaster recovery across 2 Datacenters (600km distance)
- Both datacenters are Celeste Core network POPs

#### Filecoin expertise :

- Hardware provisioning
- Filecoin Miner setup
- On site expertise (Paris)
- Support L1 / L2 / L3
- Node deployment
- Filecoin monitoring dashboard and alerting
- Professional Services

#### Certifications :

- Tier 3
- ISO 27001
- HDS (security and protection of personal health data)

### Promoting the offer 
- Celeste will promote the offer on its website, but also reference to Filecoin / Filecoin green based on the content provided by PL / FF
- Celeste will promote this offer through it's client network
- Celeste and PL will do joint marketing. 
- A launch ceremony will be organised physically in France with PL/FF
- Celeste will invite PL to participate to at least 3 events on their booth to promote the offer and Filecoin
- Celeste sales team and Twinquasar propose to participate and promote the offer during Filecoin events. 

# Offer Pricing Commitment
- The pricing will be fixed (including the energy component) for 3 years contract. 
- Pricing will be cheaper than Celeste equivalent offer running on no green energy. 
- Celeste solar panel farm will be extended to ensure that energy consumed by Filecoin clients will meet Filecoin green program Gold criterias.    
 
## Metrology and Reporting

Our solution will collects and stores metrics as time series data on a [prometheus](https://prometheus.io/) server; providing realtime and historical access to any data at any point of time.

We target **a "per Filecoin sector" granularity.**

**We could study a "per deal granularity" by extrapolating chain data and/or adding additional metrics, this is out of scope of this proposal**

The metrics will be publicly accessible through API.

### Data provided

For each component we target a one measure per minute. We already achieve that frequency on servers. (other equipment might have a lower frequency).

- Solar Panel Production
- Cabinet total Consumption
- Per server Consumption
- Server type (Miner / Node / PC1 Workers / PC2 workers / jbods / etc...)
- MinerID
- Software version : Lotus version
- Filecoin current sealing pipeline
- Process resources consumption for miner and workers :
    - CPU
    - GPU
    - RAM
    - VMEM

**We won't expose client name without their consent**
**We can provide more information like Hardware Specification, Lotus data, etc ... on demand (out of scope for this proposal)**

### Data relationship

On each measure, the relationship between the different objects will be provided :

- Workers &lt;-&gt; miner (relationship automatically adjusted in realtime)
- Worker &lt;-&gt; ongoing sealing sectors (relationship automatically adjusted in realtime)
- Servers &lt;-&gt; Cabinet (manually set when provisioning the server / moving the equipment)

### Data retention

1 year

**This can be adjusted if needed**

### APIs

Data will be exposed through a standard and open API format.

### Support to Filecoin Green
If needed we will provide support on our technology and prometheus to the Filecoin Green team to integrate these data within their portal [Filecoin Green Space](https://green.filecoin.space/metered-energy-consumption/)

### Community templates
We will provide grafana dashboard samples consuming these API to kickstart the community and help anyone to create it's own dashboard. [Grafana](https://grafana.com) is a multi-platform open source analytics and interactive visualisation web application, that can run in the cloud or on-premises

### Integration to Client Portal

historical graphs will be available and integrated with Celeste Client Portal, to provide clients a one stop shop for any components of their offer.

## Solar Panels and Renewal energy

- Solar panels will be deployed within Celeste premises to produce up to 100.000 kWh per year
- Celeste will contract with a Green certified provider to cover burst demand and ensure 100% of this client offer is covered by green energy.

## Documentation and Source Code

The project will be Open Source and available under the Twinquasar Github Account

### Documentation

- Solar Units
- Bill of materials
- Specifications
- Audit report

### Source code

The Source code will be released Open Source under the Twinquasar Github Account including but not limited to :
- Api
- Dashboard
- Data exporter tooling
- Prometheus configuration
- Documentation

## Audit

At the end of the project we accept to be audited by a 3rd party company selected by Filecoin Green.

## Budget and Project

The estimation for launching the first version of the offer is estimated to 550k$ and a 6 months go to market.
This estimation is conservative, but Celeste and Twinquasar will cover the extra charges as part of their long term investment strategy to Filecoin.

### Ask

We ask for a 300kUSD grant from the Filecoin Foundation.

### Budget

![image](https://user-images.githubusercontent.com/30711794/193344185-a2e4780a-3a20-4900-9058-490065be0cf7.png)

## Maintenance and Upgrade Plans

Twinquasar and Celeste have both in their respective domains a strong commitment towards their clients.
This offer will be supported, and the components upgraded as long as our clients last.

## Others

**Maintenance and Upgrade Plans** : We will provide a minimum of 2 years support on all opensource deliverables.
**Team Members** : Julien Noël, Nicolas Aubé, Marc Johnson
**Team Website** : https://twinquasar.io
**Team code repositories** : https://github.com/twinquasar (empty for now)
**Julien Noel repository** : https://github.com/s0nik42

**Team Member LinkedIn Profiles**

- https://www.linkedin.com/in/julien42/
- https://www.linkedin.com/in/nicolasaube/
- https://www.linkedin.com/in/marc--johnson/

**Relevant Experience**

- Celeste is a international Telecommunication carrier and Data Center company with a French Head Quarter :

[https://fr.wikipedia.org/wiki/Celeste_(opérateur_télécom)](https://fr.wikipedia.org/wiki/Celeste_%28op%C3%A9rateur_t%C3%A9l%C3%A9com%29 "https://fr.wikipedia.org/wiki/Celeste_(op%C3%A9rateur_t%C3%A9l%C3%A9com)")

- Twinquasar is an active member of the Filecoin :
    - Filecoin +Notary
    - Miner association representative for EU
    - Developing [Farcaster](https://github.com/s0nik42/lotus-farcaster) since 2020 the filecoin realtime and analytics monitoring used by 400+ miners today. (Opensource)
    - Founder of [CIDgravity](https://cidgravity.com) a Storage Provider Deal enabler :
        - Backed by PL / Consensys and large miners
        - 11M+ deals analysed over the last 12 months
        - 330+ Community members
        - 700+ users on the platform

**Additional Information**
If anyone has any questions about our proposal please reach out to me through this issue or by sending an email to [julien.noel@twinquasar.io](mailto:julien.noel@twinquasar.io)

**Comment by orinayodele** [comment]
Hi @s0nik42! We would love to have our kickoff call for your project. Could you please schedule a time in Alan's [calendly](https://calendly.com/ransil) for the grant kickoff in the next upcoming week. Once you have done that, please just shoot me a message here that you have done it.

**Comment by ErinOCon** [comment]
Hi @s0nik42, I am closing this item as the grant is approved and in progress. If you have any questions or new updates, please contact our team at grants@fil.org.
