### ISSUE TITLE
Next Step Microgrant: d-Stor - Decentralized Encrypted Cloud Storage.

### ISSUE THREAD

**Issue by KeatonKirk** [filecoin-project/devgrants#1043]
### 1. What is your project? (max 100 words)

d-Stor is a decentralized, encrypted storage platform using Filecoin/IPFS for data storage, Lit protocol for decentralized encryption, Ceramic Protocol  for decentralized database management, self.id for decentralized identity and NFTs for access control. Other decentralized cloud storage platforms still rely on centralized access control and database management, introducing the familiar singular points of failure. d-Stor will leverage emerging web3 tech such as decentralized encryption, NFTs, and decentralized ID for a fully decentralized experience.

The goal of d-Stor is to focus on web3 principles such as user-centric data, decentralization, and data privacy. Data storage should be treated as a utility and should not be monetized by a single entity, while also allowing for composability and scalability.

### 2. Project links
  
Link to Github repo: https://github.com/KeatonKirk/d-stor
License: APACHE2
Link to Project Demo: https://www.youtube.com/watch?v=oEOU98cQ2IA
Link to Project Alpha: https://d-stor.herokuapp.com

NOTE: project demo is currently hosted on a cold start server, please allow ~30 seconds for server to start when first loading. Also, the state of the test networks I'm using (ceramic, chainsafe) can occasionally result in timeout errors. With funding I will update to more stable networks and apis.

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Filecoin and IPFS are the backbone of the platform, providing the primary file storage infrastructure via the Chainsafe API. I will look to create custom APIs in future deliverables to interact directly with Filecoin network and reduce reliance on third party libraries.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The Filecoin grant will allow me to fund full time developer work on the project and work towards a public launch, user support, feature additions, scaling optimization and additional dev support. 

Additionally I will be able to upgrade to paid hosting services and improve platform performance.

Short term deliverables:
- polygon or mainnet launch for smart contract (currently on goerli testnet)
- UX improvements: reduce number of clicks needed for first time user registration
- Front end styling 
- upgraded server and database for lower latency and greater reliability 
- improve support for multiple device usage

Medium term deliverables:
- gasless network implementation
- add compression library for improved scalability
- custom DID solution 
- custom Filecoin APIs

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  Absolutely! As a former core team member of Algovera.ai I have been active in the Filecoin grant process in the past.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes!

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  N/A

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  Keaton Kirkpatrick - Full Stack Web3 Developer, founder
  keatondkirkpatrick@gmail.com
  https://github.com/KeatonKirk
 
* How did you learn about our microgrant program?
   I have worked with Filecoin grants in the past, and became aware of the microgrant program through my involvement in the Algovera.ai grant.
* If your project was created as part of an event or hackathon: N/A
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by KeatonKirk** [comment]
@ErinOCon Thanks so much for all your work on the grant submissions! Not sure if you've reviewed my application yet, but just wanted to let you know I added a video walkthrough of the demo for your convenience :) Might make reviews a bit quicker.

Please let me know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @KeatonKirk, thank you for your proposal! This grant has been approved. Look out for an email to confirm payment information. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @KeatonKirk, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!
