### ISSUE TITLE
RFP Application

### ISSUE THREAD

**Issue by kenGIS** [filecoin-project/devgrants#1044]
# RFP Proposal: `Shamba DMRV Network`

**Name of Project:** `Shamba DMRV Network`

**Link to RFP:** [https://github.com/filecoin-project/devgrants/blob/master/rfps/green-grants.md](url)

**RFP Category:**  `app-dev`

**Proposer:** `kenGIS`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:**"Yes"

# Project Description

Shamba is building a digital monitoring reporting and verification (DMRV) network along with software tools specifically designed to support small-scale ReFi projects in the global south. 

Using remote sensing, geospatial modeling, and machine learning as the backbone, our DMRV solution will enable the verification of ecological impact claims affordably and at scale. The tools we develop alongside the DMRV network will enable the easy onboarding of communities onto ReFi. This will allow a big part of the global south to participate in regeneration and channel new resources to rural communities to support ReFi initiatives. This work is important as the current MRV paradigm for ReFi is highly manual, too expensive, and not suited for small-scale projects. 

Our solution uses the power of web3, combining satellite data with advanced analytics along with crowdsourcing to automate and digitize MRV for ReFi. We are building an oracle that integrates with Filecoin to immutably store all the MRV data used in verifying ecological claims by the Shamba Network. In our stack, Filecoin plays a key role in providing a trustless storage solution for DMRV data that can be used to audit ecological credits.  

## Development Roadmap

Milestone 1: Integrate the Shamba ecological data oracle with the Regen Network ledger.
Under this milestone, we are working to integrate our Chainlink-based data oracle (currently serving 60 regularly-updated satellite datasets) with the Regen Ledger and the Regen Data Module. This will allow data from our oracle to be used to create ecological credits on the Regen Ledger. This milestone will enable our existing ecological data oracle to serve a wide range of ReFi projects that are using the Regen Ledger.

Milestone 2: Developing tools to enable the easy creation of on-chain ecological credits by farming communities.
Under this milestone, we are working to build user-facing tools that will make it easy for farmers to create eco-credits and work with advanced web3 technologies without having to learn too many new concepts. We are following a participatory design methodology to co-develop these tools with farming communities to ensure they meet the needs of the intended users.  The outcome of this milestone will be web-based tools that allow anyone to be able to navigate the process of creating and monitoring eco-credits using the Shamba DMRV network.

Milestone 3: Integrating the DMRV network with the Filecoin stack for enhanced data verifiability.
Under this milestone, we shall be integrating the Shamba DMRV network components with the Filecoin stack to create a system for the storage of DMRV data in a decentralized manner. The goal with this is to use the Filecoin/IPFS stack to both store DMRV data long-term, as well as make it available for auditing purposes. We are looking at using the Filecoin Virtual Machine as a part of the stack in building this component of our solution. Some of the data that will be stored in Filecoin under this system include the raw satellite data used in analysis, model inputs, parameters and outputs, as well as the data collected on the ground by different sensors and submitted to the DMRV network. 

## Documentation, Education, and Community

We are going to develop both written documentation as well as video tutorials instructing on the use of the DMRV data as well as the ReFi tools we are developing to accompany the network. We are also planning to roll out a series of workshops and seminars to capacity-build rural communities in Africa on the use of these tools and how they can get started in ReFi. We are also building a community of people who can contribute to the DMRV network as well as farmers who will use the tools in ReFi project. We strongly believe an awareness and community-building campaign needs to accompany the launching of new tech in order for ReFi to take off in the global south.

## Other Deliverables

We aim to build and deploy our solution during this project so another deliverable will be the launching of the ReFi tools we are building and their piloting in rural farming communities.

## Milestone Summary

| Milestone No. | Milestone Summary & Staffing | Funding | Estimated Timeframe |
| ------------- | --------------------- | ------- | ------------------- |
| 1             | Integrate the Shamba ecological data oracle with the Regen Network ledger. 4 backend developers.     | $20,000     | 8 weeks             |
| 2             | Developing tools to enable the easy creation of on-chain ecological credits by farming communities. 6 front and back-end developers.     | $40,000      | 16 weeks             |
| 3             | Integrating the DMRV network with the Filecoin stack for enhanced data verifiability.    | $20,000 4 full-stack developers     | 6 weeks             |
| 4             | Solution Launch and Piloting     | $20,000  2 product managers, 4 support agents    | 14 weeks             |

## Total Budget Requested

$100,000 across all milestones.

## Maintenance and Upgrade Plans

This project is being built as a web 3 project led by a core team that will maintain the project in the initial period. As the project becomes more decentralized and external developers chip in, a bounty system to reward technical contributions and improvements will be instituted. Improvement proposals and voting by governance token holders will be used to drive the evolution of the solution.

# Team

## Contact Info

kennedy@shambadynamic.com

## Team Members

- Kennedy Nganga - https://github.com/kenGIS and https://www.linkedin.com/in/kennedynganga/
- Mohammed Mwijaa - https://github.com/MwinyiMoha and https://www.linkedin.com/in/mohammed-mwijaa/
- Steve Omondi - https://github.com/SteveFirsake and https://www.linkedin.com/in/steve-firsake/
- Wanjohi Kibui - https://github.com/wanjohikibui and https://www.linkedin.com/in/wanjohi-kibui/
- Syed Asad Kazmi - https://github.com/SyedAsadKazmi and https://www.linkedin.com/in/syed-asad-kazmi-a65b67179/
- Atak Ngor - https://www.linkedin.com/in/atakngor/

## Team Website

[https://shamba.network](https://shamba.network)

## Relevant Experience

The Shamba team was the first to deploy an ecological data oracle on web3 [https://t.co/6WwaYgY9NL](url) and is a winner both of Hackatom VI and Faber Filecoin hackathons. Shamba Network is an alumni of the Outlier Ventures Filecoin Basecamp 2 program and has close to 20 partnerships with projects in the ReFi space including giants such as Regen Network [https://medium.com/regen-network/regen-network-launches-strategic-eco-credits-partnership-with-shamba-network-89322192233f](url). 

The Shamba team has vast experience working at the junction of web3 and geospatial technology and are currently on-chaining 60 satellites data through their data oracle which is bridged to 7 different chains [https://docs.shamba.app](url). The team is building on its success with the data oracle to build out an entire DMRV network and accompanying tools for smallholder farmers to get into ReFi. 

Not only is the team technically talented, they also have a strong contextual understanding of the project. Team members are majorly drawn from Kenya, India and Australia hence bringing different perspectives and strong understanding of dynamics in the global south. This allows them to work closely with the target users of such solutions (smallholder farmers) and develop solutions that correlate with realities on the ground. The team has many techies with strong backgrounds working with geospatial technology and applying it to solve farmer's challenges.

## Team code repositories

https://github.com/shambadynamic

# Additional Information

Shamba has worked with Filecoin-based solutions before such as web3.storage to store analytics metadata on Filecoin. We are looking to build a solution capable of storing drastically higher volumes of data on Filecoin (potentially terabytes per week) as the satellite data we use in our analytics coupled with the heavy models we run are big data. We have both proven experience building on Filecoin as well as a technical roadmap that we believe we can complete within a year of kicking off work.

**Comment by realChainLife** [comment]
Hi @kenGIS thank you for your proposal. We would like to fund the work outlined here. Look out for an email with detailed next steps.
