### ISSUE TITLE
Next Step Microgrant: QSTN - DATA DAO Hackathon 2022 

### ISSUE THREAD

**Issue by qstnus** [filecoin-project/devgrants#1046]
### 1. What is your project? (max 100 words)
QSTN is a blockchain enabled market research portal where users earn digital rewards for completing surveys, questionnaires and short answers on the NEAR Protocol. 

### 2. Project links
  
Link to Github repo: https://github.com/qstnus 
Link to demo or website, if applicable: https://qstn-frontend.vercel.app [demo]
Link to demo or website, if applicable: https://qstn.us [website]
License: MIT (applicable to all smart contract components) 
  
### 3. How is IPFS, Filecoin, or related technology used in this project? 
When users complete a questionnaire, they earn digital credits which can be used to purchase to digital collectibles. These collectibles (e.g. NFTs, digital art) are pinned and hosted on IPFS using the NFT. Storage tool. 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? This grant will allow us to redesign the MVP and assist with development costs as we build out the business portal.

Right now, only admins are able to create questions and conduct market research. We would like to build out a white label solution so that everyone is able to create their own questionnaire and reward users in their native currency. 

In terms of value add, any and all businesses who use our business portal and mint digital rewards will be using hosting the image on IPFS since we are making them our sole storage provider. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes

### 6. Does your proposal comply with our Community Code of Conduct? 
Yes

### 7. Links and submissions 
https://twitter.com/qstnus/status/1572926592677978113 - submission to the DATA DAO Hackathon 2022 (community track) 
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Orrin Campbell
qstnus@gmail.com
https://github.com/qstnus
CEO & Founder

* How did you learn about our microgrant program? 
DATA DAO Hackathon 2022

* If your project was created as part of an event or hackathon: 
DATA DAO Hackathon 2022

 * Please link to your hackathon submission
Submission = https://twitter.com/qstnus/status/1572926592677978113
Demo = https://qstn-frontend.vercel.app/

**Comment by ErinOCon** [comment]
Hi @qstnus, thank you for your proposal! We will not be moving forward with a grant at this time. Please feel welcome to re-apply if/when your project further incorporates IPFS, Filecoin, or related tech.
