### ISSUE TITLE
Filecoin Green - Solar

### ISSUE THREAD

**Issue by corenseglem** [filecoin-project/devgrants#1047]
# Open Grant Proposal: `Filecoin Green - Lucky Solar`

**Name of Project:** Lucky Solar

**Proposal Category:** `green`  

**Proposer:** `corenseglem` `hotuan87`

**(Optional) Technical Sponsor:** `Marc Johnson'

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

The Lucky Strike Facility (LSF) in Reidsville, NC is a 1MM square foot former tobacco factory that we are in the process of converting to a modern datacenter. Our primary focus is to provide a green, environmentally sustainable facility space for Web3 infrastructure, in particular, space for Filecoin service providers.

![git](https://user-images.githubusercontent.com/109981188/193364432-183b3529-8caa-49b9-a0fd-a64398cf5883.jpg)

We formed Lucky Storage as an anchor tenant at LSF to pioneer using this new facility for Filecoin. We are in the process of retrofitting the facility and installing up to 25 PiBs of JBOD storage racks for Filecoin, with future plans to install a Filecoin sealing cluster. Additionally, we are an early testing node for Filecoin’s Saturn CDN project. Our plans include expanding our fiber capacity at the facility to support multiple high capacity fiber connections as an L1 Saturn CDN node.

Ultimately, our plans are to build this into a community site for multiple Web3 service providers to operate. We are already in active discussions with some of the largest Filecoin SP’s in the ecosystem to provide accommodations for their equipment.

All of this requires power, ideally clean power. At the moment, LSF has immediate access to 16MW of power from Duke Energy supplied to us through our own dedicated power transmission line and two redundant substations. Duke’s power mix is 40% nuclear, 40% natural gas and 18% coal and 2% renewable. For carbon emissions and for datacenter operation, it’s nice that we have an above average mix of nuclear from Duke, but we still need to do everything we can to offset the natural gas and coal mix.

We are blessed with a tremendous amount of roof space and land (~25 acres in total). Theoretically, we could support megawatts of solar capacity, but for right now, we want to focus on completely offsetting the expected near term Filecoin operations at the facility.

Additionally, the facility is already outfitted with an existing solar farm with the necessary equipment to sell power back to the grid. The current solar farm has a max output of 125 kW (150,000 kWh a year). For this grant, we are seeking support for a $250K expansion to build an additional 45 kW (55,000 kWh a year) rooftop solar farm to augment the existing solar farm. For a combined 205,000 kWh per year, we are confident this will help to offset more than 100% of our local Filecoin SP power needs, while helping to further offset the power usage of other Filecoin SPs.

## Value

But there’s more, because this expansion is just the starting point to bring more attention to Filecoin, to the facility and to motivate future projects to further expand solar.
We are also applying for additional grants from both state and federal renewable energy programs to retrofit as much of the facility for solar as possible. We estimate the facility could support several megawatts of power across the roof of all 26 buildings as well as the spacious parking lots (which we plan to convert to public EV charging stations with additional infrastructure grants).
By showing progress here, we can prime ourselves to succeed in further expansions supported by the government, nonprofits and private investors. The value to the Filecoin ecosystem is that we will be able to:

(a) provide more green power capacity to offset Filecoin SPs globally and
(b) provide more public visibility to the Filecoin Green initiative, and the broader efforts of the blockchain community, as the initial “angel investor” and backer of this ambitious energy and economic development project.

When all is said and done, you can expect to see a shiny Filecoin logo emblazoned one of the buildings here (we were thinking of the iconic water tower). Given that we are working with well established solar contractors and the facility is already fitted with some solar capacity, we expect the risk of execution here to be very low. It’s low hanging fruit a sure bet on a very publicly visible project that will garner lots of attention in the local community here.

## Deliverables

Below are visualizations of the solar farm we will be building with this grant.

![git1](https://user-images.githubusercontent.com/109981188/193363147-2ea4899c-30cd-4c17-8d08-46f6b537e7c9.JPG)

![git2](https://user-images.githubusercontent.com/109981188/193363153-cb0d2ef5-b4db-4bca-af05-fb0b9da83a01.JPG)

This solar farm will be on Building 1 of the Lucky Strike Facility. The exterior map below should put it in larger perspective where this solar farm will be located relative to the entire facility and future potential.

![git3](https://user-images.githubusercontent.com/109981188/193363186-29d8383c-5925-4e19-b6b5-f5351fc807f0.JPG)

![git4](https://user-images.githubusercontent.com/109981188/193363197-83dec4a2-1485-44ab-91e0-e98b0b57906b.JPG)

![git5](https://user-images.githubusercontent.com/109981188/193363209-ee648f2a-8702-4a19-a043-29964f6771a1.JPG)

## Development Roadmap

![NC Rooftop Solar Development roadmap - Project Timeline 2](https://user-images.githubusercontent.com/109981188/193360124-54ec028f-a362-455f-bdfa-f3ba20e575da.jpg)

## Total Budget Requested

![budget](https://user-images.githubusercontent.com/109981188/193361571-ed41afc2-9468-45f9-b160-6dfdda08af32.JPG)

## Maintenance and Upgrade Plans

Long term, we plan to further expand the solar generation across multiple roofs and parking lots.  In total, we have access to ~25 acres of space that we plan to explore for further renewable energy production and sustainable blockchain operations. 

# Team

## Team Members

**Coren Seglem** is a Lucky Storage and Ascendency co-founder with a background in the U.S. Marine Corps. Coren’s interest in data storage stems from extensive working experience with commercial and industrial hardware, and a recognition of the importance of infrastructure in building Web3 internet. His military experience spans more than 12 years, with a focus on aviation and logistics. Coren is a graduate of the Ross School of Business at the University of Michigan, where he graduated with honors.

Coren oversees the redevelopment of the Lucky Strike factory, which includes developing and expanding Lucky Storage’s Filecoin storage operations. Coren’s mandate includes recruiting and managing a variety of tenants to occupy the former tobacco factory. 

**Tuan Ho** is a founding partner of Lucky Storage and Ascendency, and a serial tech entrepreneur. Prior to Lucky Storage’s formation, Tuan founded and grew Raydiant, a digital experience platform for brick & mortar companies. Tuan’s first successful tech company was a streaming TV business called Philo, and his career experience includes venture investing with Atomic Labs. Tuan is a Harvard University graduate who participated in the 2017 Filecoin initial coin offering, after debating the future of data storage with a group of Thiel Fellows.

Tuan focuses on deal execution and client relationship management for Lucky Storage. He also oversees the company’s marketing and sales operations, and assists with capital raising efforts.

**Evans Richards** is the founding partner of Ascendency and part-owner of the Lucky Strike tobacco factory. Evans is the founder and CEO of West End Toys, one of the factory’s first tenants. As an Ascendency partner, Evans’ primary focus is on fundraising activities for the entire facility.

Lucky Storage is a small team with a scrappy work ethos and bootstrap culture. Aside from each team member having core responsibilities, the members of Lucky Storage each wear many professional hats.

**Reid Garton** is the President and CEO of NY State Solar, a solar developer that specializes in the sale, design, and installation of customized residential and commercial photovoltaic systems. NY State Solar has nearly 200 employees and six locations across New York City and Long Island.

Through his work with NYSEIA, Reid's extensive experience within the solar industry works to advance further adoption of green technology on both local and regional scales.

Reid's knowledge of the renewable energy sector regularly helps educate those outside the industry on the long-term financial and environmental benefits of choosing eco-friendly energy options for New York State.
Before joining NY State Solar, Reid served as the founder of a series of successful telecom and internet service companies.

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/coren-seglem-16b45111/
https://www.linkedin.com/in/hotuan/
https://www.linkedin.com/in/evans-r-46ab0522/
https://www.linkedin.com/in/reidgarton/

## Team Website

You can learn more about New York State Solar, our partner in the Lucky Strike Facility solar deployment by visiting https://nystatesolar.com/

## Relevant Experience

Our partner in the LSF solar farm project is NY State Solar (NYSS, LLC, f/k/a NY State Solar, LLC, d/b/a NY State Solar) a solar developer that specializes in the sale, design, and installation of customized commercial and residential photovoltaic systems.  NY State Solar has nearly 250 employees and six locations. Custom solar solutions are engineered from the ground-up, and every system that we install is tailored to each property's unique characteristics.

The company has example projects of previous rooftop solar developments that are available on request.  NY State Solar is growing its footprint in the region by applying its successful approach to driving solar adoption in both new and established markets.

# Additional Information
We originally learned about the Open Grants Program through Filecoin Green, Youtube, FIL Austin, and as ESPA 1 graduates.
For more information or questions about our proposal, please contact us by email at [coren@luckystrikefacility.com](mailto:coren@luckystrikefacility.com) and [tuan@luckystrikefacility.com](mailto:tuan@luckystrikefacility.com).

**Comment by ErinOCon** [comment]
Hi @corenseglem, I am closing this item as the the grant has been approved and the project is in progress. If you have any updates or questions, please contact grants@fil.org.
