### ISSUE TITLE
Next Step Microgrant: CryptoPay

### ISSUE THREAD

**Issue by Shubham0850** [filecoin-project/devgrants#1048]
### 1. What is your project? (max 100 words)
CryptoPay ( Not just a CryptoPay ): All in one crypto wallet for all your needs. We make it safe and easy for you to store, buy, send, receive, swap tokens, and collect NFTs on the Solana blockchain. Also integrated the Solana Pay SDK and added a Scan and Pay feature like the UPI payment apps.

### 2. Project links
[Cpay](https://cpay.vercel.app/wallet ) : Optimised for mobile
  
Link to Github repo:
[Github repo](https://github.com/Shubham0850/crypto-pay/tree/main)

Link to demo or website, if applicable:
[Demo link and public reactions](https://www.linkedin.com/feed/update/urn:li:activity:6911591366472921088/)

License: 
Yes, all of the work is Open Source under MIT license.
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Our idea is to onboard Merchants and customers to the application. And at the same time we are planning of partnering with Coupon companies to offer free coupons on every transaction ( GooglePay, PhonePay, Paytm ). We are going to store all this information on IPFS, so that in future we can integrate smart-contract to provide additional features to the user.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Currently our project has basic functionalities but it is not fully built and we are also planning to do some experiment's that and try to add other features. But for now I'm the only one in the team working as a Full-Stack Developer so, I'm looking for a Backend Dev, UI/UX designer and a Blockchain Dev who can contribute in this project. This mini grant will act as an starting fuel to boost up our development process.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, I do
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  [https://github.com/orgs/Web3Auth/discussions/587](https://github.com/orgs/Web3Auth/discussions/587)

  WON best UI/UX price: [https://twitter.com/Web3Auth/status/1570660084895862784](https://twitter.com/Web3Auth/status/1570660084895862784)

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Shubham Raj
Email - [rajshubham0850@gmail.com](mailto:rajshubham0850@gmail.com)
Github - Shubham0850
Role - Full Stack Developer

* How did you learn about our microgrant program?
Friend
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  Solana Riptide 2022
  * Please link to your hackathon submission
  [https://solana.com/riptide/voting/crypto-pay](https://solana.com/riptide/voting/crypto-pay)

**Comment by ErinOCon** [comment]
Hi @Shubham0850, thank you for your proposal! Are you currently building with IPFS, Filecoin, or closely related tech? If so, can you point to this usage in your code?

**Comment by Shubham0850** [comment]
Hi ErinOCon,

Actually I'm still in college so I've been busy with my college
examination. That's why I didn't get much time to work on it.

But I've been designing a system for integrating FileCoin into CryptoPay,
and it is almost done. Now I'm going to start writing code. As I discussed
in the PR that I'm the only one who is working on this project for now
that's why It is taking little time to implement it. But will soon update
you regarding the implementation of FileCoin into it.

Hope you understand it.

Thanks,
Shubham Raj

**Comment by Shubham0850** [comment]
Hi ErinOCon,

I've added the basis ipfs functionality to the CryptoPay. Actually my future plan is to create a dynamic NFT for the merchant where all of their transaction is stored and they will earn interest on that token. All the NFT metadata will be going to stored on ipfs and also the merchant details is also stored on the ipfs to create more trust to the merchant.

Also end user of the application will be able to use the dynamic NFT to claim some rewards for the payment they made so far. ( User will be rewarded with dynamic NFTs when they do transactions ).

Looking forward to hear from you.

Thanks,
Shubham Raj

**Comment by ErinOCon** [comment]
Thanks, @Shubham0850! I will circle back with an update!

**Comment by Shubham0850** [comment]
Thanks for making it clear.

Looking forward to hear from you.

**Comment by Shubham0850** [comment]
Hi @ErinOCon , any update on this ?

**Comment by ErinOCon** [comment]
Hi @Shubham0850, thanks for checking in! Can you provide more detail on what you hope to accomplish over the next three months? For example, what functionalities or features will you work on? I also recently sent you a question regarding your final report for [m-tribe](https://github.com/filecoin-project/devgrants/issues/616). Please let me know if you have any questions.

**Comment by Shubham0850** [comment]
Hi ErinOCon,

*CryptoPay*


Next 3 month plan after getting grant


*Features 1: Merchant Registration page*

Registration page for merchants where any merchant who wants to receive
crypto as a mode of payment can register their store to the application.


*Feature 2: Integrate WEB3Auth*

To make the wallet creation part more smooth and sure. We will implement
WEB3Auth into the application.


*Feature 3: Responsive UI*

In the current design UI is not meant for the bigger screen, it is only
designed to look good in mobile phones. So, we will design a new UI which
looks good for both small devices as well as big screen size.


- Finally do alpha testing of the application ( in Solana Mainnet ). And do
improvement if needed.


- And also will try to involve some other interested developer to
contribute to this project. Few of them are already ready to contribute to
the project.


- Thinking of implementing FEVM and Data DAO into this ( It's just a
research thing )


This is the rough plan that I thought I would implement after getting the
grant.


will update about m-tribe on that mail only.


Best,

Shubham Raj

**Comment by Shubham0850** [comment]
Any update for me @ErinOCon  ?

**Comment by Shubham0850** [comment]
Any update for me @ErinOCon ?

**Comment by ErinOCon** [comment]
Hi @Shubham0850, thank you for checking in and for your patience. We will not be proceeding with a microgrant at this time. If you are still planning to build with FVM, you may have an interest in these [Space Warp opportunities](https://spacewarp.fvm.dev/). 

Wishing you the best as you continue to build!
