### ISSUE TITLE
Next Step Microgrant: Neat storing and sharing files

### ISSUE THREAD

**Issue by ghost** [filecoin-project/devgrants#1049]
### 1. What is your project? (max 100 words)
Building neat super lightweight hosting and sharing services with using HTTP endpoints.

### 2. Project links
  
Link to Github repo: https://github.com/ipfsloafer/neat
Link to demo: https://ipfsloafer.dev/
License: MIT https://github.com/ipfsloafer/neat/blob/main/LICENSE 
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
The project uses Web.Storage API to store files on IPFS/Filecoin and retrieves data using an HTTP endpoint (at https://ipfs.io/ipfs)
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Taking steps with adding variations with optional next to https://ipfs.io/ipfs additional HTTP endpoints and next to Web3StorageApi, adding optional Api.estuary.tech or other storage services with crossovers in the application. 
ipfsloafer.dev is about ideal neat super-lightweight hosting and sharing service solutions under 1 roof.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, final grant report will be provided.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
No.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Mark Evers, info@ipfsloafer,dev ,https://github.com/ipfsloafer, Developer.
* How did you learn about our microgrant program?
Did read about it in slack.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
 No.
 * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Closed item as applicant repo as closed.
