### ISSUE TITLE
Next Step Microgrant: Web3QR

### ISSUE THREAD

**Issue by akhileshthite** [filecoin-project/devgrants#1051]
### 1. What is your project? (max 100 words)

<p align="center">
  <img align="center" src="https://w3s.link/ipfs/bafybeie2ues4wwotiljpgshefpa7hqsivhxx53c5k354qvd3viaddegdzu/logo.png/" width="200" height="200"></img>
</p>

Web3QR allows you to deploy static websites to [IPFS](https://ipfs.io/) by using [web3.storage](https://web3.storage/about/). After publishing the website, you'll get a decentralized QR code, IPFS CID, and hosted gateway link.

"It's like a web app version of [DScan](https://chrome.google.com/webstore/detail/dscan-decentralized-qr-co/idpfgkgogjjgklefnkjdpghkifbjenap) chrome extension". 
Why?
So that mobile users can use it by accessing Web3QR in their browser.

### 2. Project links
  
Link to Github repo: https://github.com/akhileshthite/web3qr
Link to demo or website, if applicable: https://web3qr.netlify.app/
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Web3QR uses web3.storage for uploading the content to IPFS.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Create all in one web app that uploads any type of content to IPFS and generate customizable D-QR codes. 
* Fix the directory tree issue using vanilla javascript.
![Screenshot 2022-10-01 at 8 31 00 PM](https://user-images.githubusercontent.com/68826419/193416840-6473a450-b419-441d-9816-7b451f09f415.png)
* Add a feature that can publish normal text (blogs or links) to IPFS and generate QR Codes.
* Add QR code customization feature so that users can change colors or even put their brand logo in the middle of the QR Code.
* Support file, folder, and text (all in one) uploads.
* Improve UI.
* Refactor and improve code style.
* Improve documentation.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  Yes.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes.
Won Filecoin runner-up track.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Name: Akhilesh Thite

Email: [akhileshthite@hotmail.com](mailto:akhileshthite@hotmail.com)

GitHub: [@AkhileshThite](https://github.com/AkhileshThite)

Role: Main developer

* How did you learn about our microgrant program?
 -> E-mail
![Screenshot 2022-10-01 at 8 33 06 PM](https://user-images.githubusercontent.com/68826419/193416399-11cf8676-1d4f-4326-b894-54ef542b28cd.png)
      
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  -> [Chainlink Spring 2022 Hackathon](https://chainlinkspring2022.devpost.com)
  * Please link to your hackathon submission
  -> https://devpost.com/software/web3qr

**Comment by ErinOCon** [comment]
Hi @akhileshthite, thank you for your proposal. It looks like you have found a lot of building opportunity through our microgrants program!

We will not be proceeding with a grant at this time for this project. Please feel welcome to consider our [other grant types ](https://github.com/filecoin-project/devgrants/issues/new/choose) should the scale and scope of your future work align with the outlined criteria.

**Comment by akhileshthite** [comment]
> Hi @akhileshthite, thank you for your proposal. It looks like you have found a lot of building opportunity through our microgrants program!
> 
> We will not be proceeding with a grant at this time for this project. Please feel welcome to consider our [other grant types ](https://github.com/filecoin-project/devgrants/issues/new/choose) should the scale and scope of your future work align with the outlined criteria.

No problem @ErinOCon, thanks for the update.
I love building on IPFS/Filecoin.

The grant programs helped me to put extra hours apart from the university work and ship the software!
Thanks a ton :)

Happy decentralizing 🏴‍☠️

Users are growing rapidly:
https://buidltools.com/
