### ISSUE TITLE
Next Step Microgrant: IPFS Upload Web Component

### ISSUE THREAD

**Issue by FazioNico** [filecoin-project/devgrants#1055]
## 1. What is your project? (max 100 words)

This project is an Javascript library that provide a Web Component that allow user/developper hosting media files on IFPS network.

This Web Component is fast, easy to use, customizable and can be used in any web page or web application by just adding script and tag to the HTML page.

## 2. Project links

Link to Github repo: [https://github.com/FazioNico/ipfs-upload-button](https://github.com/FazioNico/ipfs-upload-button)

Link to demo or website, if applicable: [https:/fazionico.github.io/ipfs-upload-button](https://fazionico.github.io/ipfs-upload-button/)

License: MIT

## 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

Media files are stored on the [IPFS/Filecoin network](https://ipfs.io/). The application uses [Web.Storage](https://web3.storage) API to upload files.

## 4. How will you improve your project with this grant? What steps will you take to meet this objective?

We will improve the project by adding the following features:

  - Improve the UI/UX of the customable component parts to make it more customable and user friendly.
  - Improve the documentation of the project and add more examples of usage (react,vue, angular, etc...).
  - Allow user to use multiple IPFS providers and pinning services (Pinata, Infura, etc...)
  - Add more features to the component (e.g. upload a file from a URL, upload a folder, etc...)
  - Promote the project by create video tutorials and blog posts.

## 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes

## 6. Does your proposal comply with our Community Code of Conduct?

Yes

## 7. Links and submissions

  - If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

N/A

## 8. Is this project open source?

This project is open source under MIT Licence

## Additional questions:

  - For each team member(s), please list name, email, Github account, and role in the project:

    - [**@fazionico**](https://github.com/FazioNico) - **Nicolas Fazio** 
    
      Software Architect & Blockchain Developer

      Mr. Fazio is a software architect and blockchain developer with over 15 years of industry experience. He has worked on a variety of projects ranging from cloud enterprise software to blockchain applications focusing last 3 years exclusively in the Web 3 industry. He is passionate about building decentralized solutions and is currently working on the Web3 project.

      LinkedIn: [https://www.linkedin.com/in/fazio-nicolas/](https://www.linkedin.com/in/fazio-nicolas/)
      Email: [contact@nicolasfazio.ch](contact@nicolasfazio.ch)

  - How did you learn about our microgrant program? 
    
    Google

  - If your project was created as part of an event or hackathon: 
    
    N/A

  - What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) :
    
    N/A

  - Please link to your hackathon submission: 
    
    N/A

**Comment by FazioNico** [comment]
Update demo link

**Comment by ipfsloafer** [comment]
Chapeau to you @FazioNico ! Absolutely Brilliant!  🎉

**Comment by jenks-guo-filecoin** [comment]
Love your work @FazioNico

**Comment by ErinOCon** [comment]
Hi @FazioNico, thank you for your proposal! This grant has been approved. Look out for an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by FazioNico** [comment]
Hi, @ErinOCon, Thanks for the approval!

**Comment by ErinOCon** [comment]
Hi @FazioNico, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!
