### ISSUE TITLE
Next Step Microgrant: DAO Atheneum

### ISSUE THREAD

**Issue by cryptotwilight** [filecoin-project/devgrants#1060]
### 1. What is your project? (max 100 words)
**DAO Atheneum**
DAO Atheneum is new way for DAOs to share and commercialise their knowledge seamlessly. The purpose of the project is to enable a given DAO upload media quickly easily and publicly for either Commons or Commercial use using IPFS and EVM. The idea is to enable DAOs to do this transparently and on chain helping them to get their message and their wares to the world. 

### 2. Project links
  
Link to Github repo: https://github.com/cryptotwilight/dao-atheneum
Link to demo or website, if applicable: https://nameless-sky-5381.on.fleek.co/
License: Apache 2.0

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
The project uses IPFS to manage media storage and content addressing. Thus when DAO users upload their data it is stored on IPFS and the content hash is used as an operational primitive for EVM functions. This enables us to provide features on chain search and billing using EVM without assembling any sort of database queries. 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The next steps we would like to take are to introduce selective encryption of media to the platform as well as more granular access control. We would also like to improve the UI and create a third party smart contract level integration API that confers oracle like functions enabling DAOs to build their own smart contract & UI level integrations into their Atheneum easily, thus moving us closer to commercial full viability. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes
https://gitcoin.co/hackathon/Rollathon/projects/15283/dao-atheneum/summary?
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Name: Tony Ushe, 
* Email: tonyusheuk@gmail.com 
* Github: cryptotwilight 
* Role: Founder & Core Dev

* How did you learn about our microgrant program?
 Gitcoin 

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  Gitcoin L2 Rollathon 

  * Please link to your hackathon submission
  https://gitcoin.co/hackathon/Rollathon/projects/15283/dao-atheneum

**Comment by ErinOCon** [comment]
Hi @cryptotwilight, thank you for your proposal. It looks like you have found a lot of building opportunity through our microgrants program! For next steps, you may be interested in considering our [other grant types ](https://github.com/filecoin-project/devgrants/issues/new/choose) should the scale and scope of your future work align with the outlined criteria.

We will not be moving forward with a grant at this time. Wishing you the best as you continue building!

**Comment by cryptotwilight** [comment]
oh yes and all of the projects have won note-able prizes in major hacks in
the blockchain ecosystem and also funded by Filecoin so I'm not sure what
to make of the shift in decision making. Any insights I would deeply
appreciate.

Thank you so much 😊

Tony
