### ISSUE TITLE
Filecoin sponsorship during HackOnChain

### ISSUE THREAD

**Issue by majacholewka** [filecoin-project/devgrants#1061]
### 1. What is your project? 

HackOnChain is an official hackathon for the Next Block Expo, which is aiming to become the biggest blockchain festival in Europe (5k+ attendees).

It is an initiative organized by the biggest community of web3 developers in CEE - Web 3 Devs Poland which itself consists of more than 700 members.

Throughout the hackathon, it is expected to see more than 200 web3 developers from all around the world working on their projects’ ideas during two days of hard work on the 23rd and 24th of November.

### 2. Project links
  
Linktree: https://linktr.ee/hackonchain
Deck: https://bit.ly/hackonchain
  
### 3. How is IPFS, Filecoin, or related technology used in this project? 

Berlin is the city where many important things in crypto happened - Görli testnet, Dune Analytics and much more have been brought to life during hackathons. Great amount of the best minds in the space will be coding to find the best solutions on articulated by us problems. We align with Filecoin mission and love the idea to grow its ecosystem so we'd like to invite you to participate in our hackathon by sponsoring the event or/and providing bounties.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

We believe that with one of the leading storage protocols in the crypto space, we'll be able to level up our event and provide the best experience for the hackers. With the grant we'll fund tea & coffee bar and merch for the attendees as well as provide bounty for hackers.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
YES
  
### 6. Does your proposal comply with our Community Code of Conduct?
YES
  
### Additional info:
* Mail for contact: contact@hackonchain.xyz

The lead of the project:

@upperm#8053; Founder @ Web3 Devs Poland - the biggest community for web3 developers in CEE region, organized 3 IRL meetups, CryptoMondays Warsaw, Crypto Coffee House & Hacker Hub with over 1k+ attendees in total

* How did you learn about our microgrant program?
* We learned about the programme during ETHNY.

**Comment by realChainLife** [comment]
Hi @majacholewka Could you submit the event details via [this form](https://airtable.com/shrXjIWKOrr8o5Cyh), and someone from our hackathons team will reach out. cc @jenks-guo-filecoin

**Comment by ErinOCon** [comment]
Hi @majacholewka, this item has been closed. Please be in touch with any questions regarding the form!
