### ISSUE TITLE
RFP Application: Tools for DMRV of Natural Capital

### ISSUE THREAD

**Issue by de-plan** [filecoin-project/devgrants#1062]
# RFP Proposal: `Developing methodology and tools for DMRV of Natural Capital`

**Name of Project:** Ostrom

**Link to RFP:** https://github.com/filecoin-project/devgrants/blob/master/rfps/green-grants.md

**RFP Category:** `green`

**Proposer:** `de-plan`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** "Yes" 

# Project Description

**Background**
Ostrom is a protocol for community based development and environmental regeneration. Communities and individuals can deposit their land or purchase Ostrom independently to be invested in a land asset. Ostrom enables a network of Community Land Trust’s to be formed and a dynamic management of land. 50% of all land in the vault is dedicated toward nature-based carbon removal programs and all development is carbon neutral. Ostrom’s goal is to allow communities to control their development trajectory and make environmental regeneration financially viable in the global south. The centrepiece of Ostrom’s method is to measure the baseline and recurring value of natural capital locked in its vault. 

**Introduction**

**_What we are planning to build: _**
This project will develop a new method for valuing ecosystems based on the services they provide and the value of their natural capital stock. Using GIS mapping and environmental sensor data, this project will establish a method to determine the baseline value of environmental assets and calculate recurring values as the ecosystem asset improves over time. The project will build on existing market and non-market valuation techniques, adapt them for recurring valuation and DMRV, and test both the IoT and the methods. 
The project will cover the methods for calculation, the software and hardware required for it and the on-chain infrastructure for NCV DMRV. The project does not cover building out Ostrom itself or any other part of it apart from developing the valuation methods and the necessary tools. All the research conducted under the project will be open-source and available publicly. Filecoin will be utilised for storage of all relevant data; geospatial and environmental data is heavy, difficult to manage and storing it securely is often challenging. Moving the NCV-DMRV data to the permaweb will make it verifiable, easy to access and permanent. Stored data will include GIS maps, data collected by sensors and baseline data in any other format. 

**Problem Statement**

**_The need or problem we are trying to solve: _**
Natural capital asset valuation is a complex process, often highly dependent on manual surveys, field work and large scale data collection exercises. Attempts at developing digital methods for calculating the value of Natural Capital are now widely in discussion in the ReFi realm. Developing DMRV methods integrated with environmental sensors for valuing Natural capital will increase the efficiency of this process and help ReFi projects tokenize natural capital assets and develop coordination methods to regenerate and preserve the environment. It will also help communities in the global south by providing them with payments for ecosystem services and a true value for their assets.
We can break this problem down into three technical questions:

1. How do we calculate the baseline value of Natural Capital using methods conducive to recurring digital valuation?
2. How do we calculate the recurring value of Natural Capital digitally using IoT, geospatial data and oracle data?
3. How do we design the software and hardware tools to collect data, analyse it and process it?

**_Why our solution will solve this problem adequately:_**
To date, most valuation methods employed use a stock flow approach. I.e, they consider the Natural Capital Asset a part of the larger economy and value it based on the flows of capital to and from it. This method is reliable and commonly used, however it uses a static approach to an ecosystem. By considering an ecosystem a single unit, it fails to recognise the multifaceted nature of environmental assets. Our approach is built on disaggregating an ecosystem into Measurable units of stock and services. By doing this, we are able to not only value the environment more accurately, we are also able to assign each discrete unit a unique data collection method that can be remotely tracked, thereby removing the need for long and tedious manual exercises in data collection. We believe this approach will also help us understand the value of environmental assets at per unit level; a much needed step as we move towards environmental regeneration. 

## Development Roadmap

Since this projects development is hardware focussed, and our research will be on both the tools and the methodology; this development roadmap is structured to provide insight into the methods involved in our solution and the areas where we will focus. Further information is also available in our attached milestone document. 

**Terminology**
Before proceeding further, it would be appropriate to establish a foundation and define some terms that will be used in the methodology. 
1. Natural Capital : Can be defined as the worlds (or a regions) stock of natural assets which include geology, soil, water, air, biodiversity and minerals.
2. Natural Capital Valuation (NCV) : Calculating the economic (or other) value of Natural Capital. 
3. Natural Capital Accounting : The process of calculating the total stocks and flows of natural capital resources and services in a given region. 
4. Measurement, Reporting and Verification (MRV) : MRV is a carbon accounting term referring to the multi-step process involved in measuring the amount of Greenhouse Gas emissions reduced by a specific activity. In the context of this project, MRV refers to the measurement of variables indicating natural capital services; their reporting on-chain and verification of the data.
5. DMRV : Following from the above definition, Digital Measurement, Reporting and Verification (DMRV) can be defined as software and hardware solutions capable of automated data collection, processing and analysis. DMRV is an emerging field, and tools in this field are being developed by several organisations currently. 
6. Market-based Valuation: The monetization of goods and services with a market price.
7. Non-Market Valuation: The monetization of goods and services without a market price.
8. Use Value: The features of a commodity which can satisfy a human requirement, want, need or have a useful purpose. Since this project is focussed on the value of natural capital; use-value will be categorised further as follows
1. Direct-Use: Uses of the asset which involve a direct interaction between those using the asset and the asset itself. 
2. Indirect-Use: Uses of the asset which do not involve a direct interaction between those using the asset and the asset itself. 
3. Consumptive-Use: Uses of the asset that lead to a depletion of its constituent resources. 
4. Non-Consumptive Use: Uses of the asset that do not lead to a depletion of its constituent resources. 
5. Intangible Use: These types of uses arise from factors apart from the actual use of the asset, they often involve social and cultural factors and are harder to accurately place within any of the above-listed categories.

**Proposed Methodology**
If we imagine ecosystem value as a function of two variables;

Total Land Value (TLV) = 𝒇 {(Market value of land), (Natural Capital Value)}

Since this project is application based, we can safely say that any valuation process will begin with an identified parcel of land and therefore the market value of the land in question would be known. We can therefore exclude this variable from our calculations. This leaves us with the Natural capital value variable to calculate. As earlier, we can disaggregate this into constituent parts;

Total Land Value (TLV)  =  Market Value of Land  +  𝒇 {(Current Value of services provided by the ecosystem), (Current value of natural capital stock in the ecosystem)}

Additionally, there is a possibility depending on the context that the market value of the land already includes the value of natural capital or has an overlap with some parts of it. We’d therefore need to calculate and subtract the overlap; 

Total Land Value (TLV)  =  Market Value of Land  -  Overlap  +  𝒇 {(Current Value of services provided by the ecosystem), (Current value of natural capital stock in the ecosystem)}

This gives us three unknown variables to calculate, the overlap, the current value of services provided by the ecosystem (henceforth called the Ecosystem Service Value or ESV) and the current value of natural capital stock in the ecosystem (henceforth called the Natural Capital Stock Value or NCSV). Additionally, the disaggregated types of use value mentioned earlier, can be correlated as services provided by an ecosystem; i.e, A specific use of an ecosystem is possible only because it provides the conditions for that use or that ‘service’. Using this method, we can classify these ecosystem services into one of the five types of use value. Each type of use value can then be assigned an ideal calculation method, giving us an idea of the data we need to collect, the best method of collecting it and processing it. The table here provides an example of common uses of an ecosystem, categorises the use type, defines the impact scope and presents the ideal valuation method.

Use | Usage type | Impact Scope | Valuation Type
-- | -- | -- | --
Playing/Recreation | Direct Non-Consumptive | Community | Travel Cost + Spatial Suitability
Foraging/Gathering/Forest product use | Direct Consumptive | Community | Market Price + Spatial Suitability
Grazing/Fodder/Pasture | Direct Consumptive | Livelihoods | Market Price + Spatial Suitability
Unorganised labour/farming activities | Direct Consumptive | Livelihoods | Market Price + Spatial Suitability
Events/Festivals/Gathering | Direct Non-Consumptive | Community | Market Price
Water/Groundwater Recharge | Indirect Consumptive | Environmental / Community | Market Price + Impact Radius
Non-Timber Produce/Minerals/Other extractive resources | Direct Consumptive | Livelihoods | Market Price
Spiritual/Religious/Cultural | Intangible | - | Willingness to Pay
Clean Air/Scenic beauty/Vegetation | Indirect Non-Consumptive | Environmental | Willingness to Pay + Market Price + Impact Radius
Biodiversity | Intangible | Environmental | TBD

Impact scope is a term used here to define the range of people using the ecosystem for that specific purpose. Defining this helps in scoping out the problem and identifying the scale of data collection and the extent of the impact that the asset has. With this, we can now map out our methodology as follows: 

![Ostrom - Working Document](https://user-images.githubusercontent.com/104695768/194434348-97c87497-7e71-45f7-8010-62550a3a7468.jpg)

This methodology is a broad outline. The project will begin by examining this outline and each of its steps, working through their details and reorienting them wherever necessary. Using this as a guide, this project will develop methods and tools specific to ReFi, with the intent of them being utilised in the future for Ostrom or by any other project that wishes to. 

## Documentation, Education, and Community

1. Tooling documentation - For hardware developers interested in using the IoT Kits
2. Oracle documentation - Explaining data collection, processing and analysis
3. Methodology documentation - Documentation explaining how to establish a baseline, set-up for recurring valuation and develop an appropriate asset value. 

## Milestone Summary

| Milestone No. | Milestone Summary & Staffing | Funding | Estimated Timeframe |
| ------------- | --------------------- | ------- | ------------------- |
| 1             | Phase 1: Background Research, Data Requirements and Collection methods     | $13,500      | 11 weeks             |
| 2             | Phase 2: IoT Hardware Design, Development and Testing     | $7,875      | 8 weeks             |
| 3             | Phase 3 : Integration and Final Production     | $24,625      | 10 weeks             |

![Ostrom-Milestones and Roadmap - Ostrom Tasks - Research V2](https://user-images.githubusercontent.com/104695768/194447958-abb1bcf0-780a-4644-9967-e994b9a6ee80.jpg)

## Total Budget Requested
$50,600

## Maintenance and Upgrade Plans
Our team will continue building more tooling and improving this methodology even after the project is completed. All methodology related information will be continually updated on the Project Repo. 
A field test of our methodology and the hardware will be done after project completion and we will be updating the changes made after this test and the results of the test on the Repo as well. 

# Team
## Contact Info
akshay93aditya@gmail.com

## Team Members
Akshay Yeleswarapu
Akshay is an Urban Planner turned Web3 Founder. He has experience in project development, economic and environmental planning and geospatial solutions. He has worked in the urban planning industry, in academic research and on IoT - VR solutions for cities. Currently, he's focussed on building de_plan and Ostrom.
[LINKED IN](https://www.linkedin.com/in/akshay-aditya-75957388/)

Shreyash Addepalli
Shreyash is a talented engineer with an expertise in frontend development. He has experience in enterprise SaaS development and IoT development. Currently, Shreyash is involved in building Web3-IoT solutions with de_plan. He's on his way to transitioning into web3 full-time and hopes to incorporate IoT into ReFi with us. 
[LINKED IN](www.linkedin.com/in/shreyash-a-4248661b1)

Elzaphan Gitonga
Elzaphan is a Financial Analyst and Architect with experience in sustainable finance instruments and climate regulation. He has prior experience working on sustainable development with financial institutions and has transitioned to Web3 with the intent of bringing climate positive development to Kenya, where he is from.
[LINKED IN](https://www.linkedin.com/in/elzaphan-murage-24550aa0/)

## Team Website
We are a new team, and our website is currently under construction. 

## Relevant Experience
Included in Team member section.

**Comment by realChainLife** [comment]
Hi @de-plan thank you for this proposal. We would like to fund the work outlined in this scope. Look out for an email with detailed next steps.
