### ISSUE TITLE
Green RFP:Carbon Credit Market

### ISSUE THREAD

**Issue by lk2684753** [filecoin-project/devgrants#1065]
**Name of Project**: **Carbon Credit Market**

**Link to RFP:** https://github.com/filecoin-project/devgrants/blob/master/rfps/green-grants.md

**RFP Category:**  app-dev

**Proposer:** `lk2684753`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** "Yes"

## Project Description

**Where anyone can offset carbon and invest in planet-saving projects**

Based on `NEAR` public chain, combined with distributed storage technology `IPFS` and `Filecoin`;Building a carbon credit market. 

About Carbon Credit Independent Proof [CCIP];It allows organization, which have audited projects that generates carbon credit to issue their voluntary carbon credit on the `NEAR`blockchain. 

`CCIP` aims to build transparency for the voluntary carbon credit [VCC] market. 

`Co2. storae`, which maps carbon emission inputs to off-chain data (such as metadata, images, supporting documents and other assets);It provides a way to issue verified carbon credit as an NFT. 

The contract records the deployment date, address (owner of the relevant carbon credits), and year (the time the carbon credits were generated), all of which are publicly accessible.
Next, the owner of the CCIP can conduct an OTC transaction and transfer the CCIP to a new buyer without any intermediaries. This increases efficiency as the current approach requires carbon registries to manually assist with ownership changes when the OTC transaction is completed

The owner of CCIP can retire the carbon credit whenever they want. This greatly improve transparency as the contract records the date of retirement and there is no need to check with a trusted intermediary, such as the carbon registry.

## Value to the ecosystems

Our goal is to accelerate decarbonization through the preservation and protection of earth’s natural ecosystems, which are among the most immediate and cost-effective carbon sinks, while investing in longer term carbon removal and reduction projects.

Realizing that a key impediment to scaling carbon solutions is the opaque over-the-counter market for carbon credits, we set out to bring carbon credits onto blockchain to create democratized access, price transparency, immutable tracking of credits as they change hands, and incentivize high impact climate change mitigation projects.

The valuable benefits for Filecoin ecosystem is potentially to be one of the leading players in the decentralised carbon trading industry by supporting a full solution platform.

Near is an open source decentralized PoS public chain platform, which adopts sharding technology and is very friendly to developers. Technically, Near has the advantages of high expansion suite and low development cost.

## Deliverables

The results we will deliver are:

- Carbon Credit Market website；
- Filecoin & IPFS integration as our storage solution to provide file persistence and authenticity of the proofs and certificates. We will require paid plans on Web3.storage&Co2.storage to host our data；
- NFT platform for casting carbon credits；
- User carbon credit trading platform；
- Enterprise-level carbon credit support；
- An interactive interface for querying storage information;
- Multiple NEAR contracts；
- Multiple code test cases；

## Development Roadmap

Milestones:

- M1 (Week 1 to 3) 4 developers
  - Requirements finalization
  - Web UI interface design
  - Near Carbon Credit NFT mint	
  - Related functional tests
  - Budget requested: $20,000
- M2 (Week 4-6)3 developers 
  - Co2.storoge access to realize the upload of relevant carbon data
  - The development of carbon credit market supports carbon credit trading
  - Easy to find personal carbon credits
  - Related functional tests
  - Budget requested: $25,000
- M3 (Week 5 to 6) 3 developers
  - NEP-141 carbon token launched
  - Enterprise-level carbon credit support
  - Bug fixes and Improvements
  - Deploying Demo Application
  - Operation and promotion&project incubation
  - Budget requested: $25,000

## Total Budget Requested

$70,000(currently in USD, eventually can be a distribution between USD/FIL)

## Maintenance and Upgrade Plans

A CCIP trading place where users can easily buy and sell their carbon credits. A dashboard for viewing the status of CCIP in the marketplace. Work with universities to explore whether CCIP is useful in the marketplace. Project incubation to find more carbon neutral and carbon reduction projects

### Contact Info

`lk2684753@163.com`

### Team Members

-  Liangkai 
   developer
Responsible for jingdong cloud hosting and cloud architecture of database, and research and development work, previously in sohu product technology center is responsible for sohu webim, real-time gaming platform technology products such as research and development work with architecture, after joining sina weibo underlying platform research and development work of sina weibo, dominated the redis in sina weibo's development and application of mass customization. Later, I joined Tencent and was responsible for the r&d and architecture of Tencent's large-scale distributed storage project, providing highly reliable storage services for Tencent's various business product lines. In terms of technology, I mainly focus on distributed storage/cache/database, Linux kernel and other basic technical fields, and have a deep understanding of blockchain basic technology;

- Nick Chen

  Carbon Finance

  https://www.linkedin.com/in/nicklqchen/

-  Ben 

    Operations

     https://www.linkedin.com/in/ben-noel-b1229b105/

### Team code repositories

https://github.com/lk2684753/sd-cloud

https://github.com/lk2684753/go-palletone

https://github.com/lk2684753/chubaofs

https://github.com/lk2684753/near_contract_rust-did

## Additional Information

The team developers are all certified by the NEAR community as developers, and we are certified 

lk2684753.near https://learnnear.club/near-certified-developers-level1/

**Comment by realChainLife** [comment]
Hi @lk2684753 thank you for this proposal, however we will not fund the work outlined here at this time. We'd be happy to consider future proposals from your team.
