### ISSUE TITLE
Next Step Microgrant: MetaPods

### ISSUE THREAD

**Issue by Suvraneel** [filecoin-project/devgrants#1066]
### 1. What is your project? (max 100 words)
MetaPods is a React Native-based mobile application to share images, videos and other heavy BLOB files with friends over a decentralized network. It uses a Polygon Smart contract to make sure of the logic and IPFS as the storage protocol.  
*  **Features**  
   - It allows creation of Pods where an individual can add their friends as `podmates`, add wallet addresses or ENS domains. Then they can add the images to the Pod by choosing from local storage and those images are hosted over IPFS. All the podmates can view the images shared in the Pod.
   - It also has an the Instant NFT Minter that lets you click pictures/ or choose an existing one from gallery and to mint them as NFTs instantly on the go.  
---  
### 2. Project links
  
Link to Github repo: https://github.com/Open-Sorcerer/MetaPods
Link to demo or website, if applicable:  [App APK release](https://github.com/Open-Sorcerer/MetaPods/releases/tag/v1.0.0)
License:  MIT License  

 ---  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)  
IPFS is being used for storage of all the data/ metadata, all the NFTs/ image assets, and the BLOBs/files which get stored in Pods   

---    
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- Better UX 
- Adding Lit Protocol for data encryption 
- Making it multichain 
- Adding Lighthouse for getting the Filecoin integration done as well  
---   
### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, we agree to provide any & every minute detail about the project & its SDLC if asked.   

---   
### 6. Does your proposal comply with our Community Code of Conduct?

  - Yes, it complies with the Community Code of Conduct.  

---  
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:  
  - Yes. The project was a winner at the [1, 2, Web3 : Moralis X Filecoin 2022](https://moralis.io/filecoin-hackathon/) Hackathon.
   
---  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  - Name: [Suvraneel Bhuin](https://suvraneel.github.io)
Email: [bsuvraneel@gmail.com](mailto:bsuvraneel@gmail.com)
GitHub: @Suvraneel
Role: Full Stack Developer  
  
  - Name: Harsh Ghodkar
Email: [harshghodkar@gmail.com](mailto:harshghodkar@gmail.com)
GitHub: @Saviour1001
Role: Smart Contract Dev  

* How did you learn about our microgrant program?  
   -  We got a mail from Protocol Labs.  
  
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)  
    - **1, 2, Web3 Hackathon - Moralis X Filecoin 2022 Hackathon**
  * Please link to your hackathon submission  
    - **The submission was done via Google Forms**

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
