### ISSUE TITLE
Next Step Microgrant: dappshare

### ISSUE THREAD

**Issue by ZoefdeHaasCode** [filecoin-project/devgrants#1068]
### 1. What is your project? (max 100 words)
![logo192](https://user-images.githubusercontent.com/115461926/194863055-3380a5f3-8d78-4bb7-8668-b23b942e4574.png)
DappShare to IPFS, upload file to IPFS

### 2. Project links
  
Link to Github repo: https://github.com/ZoefdeHaasCode/dappshare.xyz

Link to demo or website: https://dappshare.xyz/

License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
User files are stored via the IPFS network. The application uses Infura API to upload files.
IPFS API ENDPOINT is https://ipfs.infura.io:5001 and DEDICATED GATEWAY SUBDOMAIN is https://dappshare.infura-ipfs.io
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Adding more dev time to add additional and optional (NFT.Storage & Web3.storage) API endpoints, allowing user to use multiple IPFS providers and pinning services. Adding more features as customable component parts to make it user friendly.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
N/A

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Name: Oscar Schapink 
email: info@dappshare.xyz
Role: Dev

* How did you learn about our microgrant program?
Surfing Filecoin

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
N/A

  * Please link to your hackathon submission
N/A

**Comment by ErinOCon** [comment]
Hi @ZoefdeHaasCode, thank you for your patience with our review! We will not be proceeding with a grant at this time, but would strongly encourage you to take this project to a hackathon. Please feel welcome to reapply as you continue to make building progress.
