### ISSUE TITLE
Next Step Microgrant: Mint Tea

### ISSUE THREAD

**Issue by Webmoss** [filecoin-project/devgrants#1071]
### 1. What is your project? (max 100 words)
Mint dynamic NFTs and brew them cross-chain using our custom NFT bridge. Send your favourite NFTs to all the best blockchains. Search, filter and verify NFTs for rarity by contract address, token Id, name, description and image url from multiple blockchains.

Brew up some fresh cross-chain NFTs with the Mint Tea dApp. Port your best NFTs to all the top chains to maximise your exposure using our NFT bridge. Mint Tableland NFTs with mutable metadata all stored in relational data tables on chain.

NFT holders can bridge their NFTs cross-chain to trade, stake or use on different blockchains and their local dApps. We've included a standard bridge using the IOU approach so users can bridge standard ERC-721 token or our dynamic Tableland NFTs to the different blockchains.

Search and verify your NFTs for rarity by name, description and image across all chains using NFT Ports api. Search by image url to verify your NFT artworks and images are true before purchasing your favourite works.

Browse through our marketplace to list and trade NFT collections for art, music, game items and so much more.

Mint Tea aims to become a truly cross-chain platform that opens up new markets in the blockchain space. We aim to bridge as many chains as possible starting with Ethereum, Polygon, Optimism, Arbitrum and Avalanche. As our core technologies expand then we will grow with them incorporating more chains in the future.

Please visit https://mint-tea.netlify.app/ to view the 🍵 Mint Tea web3 application, feel free to connect your metamask wallet and enjoy!

### 2. Project links
Showcase: https://ethglobal.com/showcase/mint-tea-2nn7k  
Github: https://github.com/Mint-Tea-ETHOnline
Demo: https://mint-tea.netlify.app/
License: Open Source
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Mint Tea uses IPFS and NFT.Storage for all our uploaded digital assets for our dynamic NFTS
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. We plan to continue development on the project, currently we need to update our NFT Bridge and complete the marketplace.
2. We would like to create an official website, ENS and any other social related profiles.
3. We would like to expand on our core idea of building out dynamic NFTS using Tableland.
4. We would like to do more integrations with web3 technologies.
5. We want to buidl ;)

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, we happy to share.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes, we won the IPFS/Filecoin pool prize of $440 for the team, see Transfer Request #687919791884
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Anne Krauwer - Visual Designer
Projects: https://shokumotsu.superhi.com/ 
Email: akoek@protonmail.com

Craig Moss - Front-End / Co-ordinator
Twitter: @webmoss
LinkedIn: https://www.linkedin.com/in/craig-moss-21822628/
GitHub: https://github.com/webmoss
Email: craigmoss36@gmail.com

Nobuhito Kurose - Solidity & Smart Contracts
GitHub: https://github.com/enu-kuro
Email: inner_vision2004@yahoo.co.jp / pudding.heart.hd@gmail.com

Mourad Bouabdallah - Solidity & Smart Contracts
LinkedIn: https://www.linkedin.com/in/mourad-bouabdallah/
GitHub: https://github.com/mourad96
Email: mourad.bouabdallah96@gmail.com

* How did you learn about our microgrant program?
ETH Online Prizes email

* If your project was created as part of an event or hackathon:
* What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
* Please link to your hackathon submission

ETH Global - ETH Online 2022
https://ethglobal.com/showcase/mint-tea-2nn7k

**Comment by ErinOCon** [comment]
Hi @Webmoss, thank you for your proposal! Generally, we approve one microgrant at a time. Do you expect the work for your previous project to be complete soon?

**Comment by Webmoss** [comment]
Hi @ErinOCon Thanks for the feedback, I understand completely and yes the work for my other project is completed, the next phase can get started as I have completed my objectives. I would prefer to then keep my focus and attentions on Mojo as the project has more interest from sponsors like Filecoin and Tableland. I will share more details in my final report. I will close this request and thank you for your time reviewing.

Regards Craig
