### ISSUE TITLE
Next Step Microgrant: Clubsss

### ISSUE THREAD

**Issue by Jds-23** [filecoin-project/devgrants#1072]
### 1. What is your project? (max 100 words)
Create web3-powered communities with clubsss. Reddit communities inspired me to make clubsss. Managing a Reddit community is a hassle due 🤖 Spammers, 🦹🏻‍♂️ Scammers, 📢 Noise, distracting from the purpose of the community was created for. In clubsss, every community is backed by A Smart Contract which controls the eligibility of a member who posts and the weight of their vote in a post. We use IPFS to store all content of clubsss to maintain decentralization.

### 2. Project links
  
Link to Github repo: https://github.com/Jds-23/clubsss-interface
Link to demo or website, if applicable: https://clubsss-interface.vercel.app/
License: Open Source

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

IPFS is used to store the metadata of a community and posts inside the community. Later when we support off-chain voting, we will IPFS again to store signed messages.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Next, the step of your project will be building community module smart contracts: A Treasury Module, A erc1155 module and more. Before launching to polygon mainnet we need to get some of your smart contracts audited wherever there are transfers of funds. Shortly After the polygon mainnet we will be making our dapp completely gasless to improve the UX. Next, we will expand to chain more L2 chains.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, we do 

### 6. Does your proposal comply with our Community Code of Conduct?
Yes, they do

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Yes, we build out the project in https://moralis.io/filecoin-hackathon/ . We don't have a submission link for the submission.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Name: Joydeep Singha
Email: [joydeepsingha68@gmail.com](mailto:joydeepsingha68@gmail.com)
Github Account: Jds-23
Role: Blockchain Developer And FullStack developer
* How did you learn about our microgrant program?
* Through email
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission: https://moralis.io/filecoin-hackathon/ no submission link present as we had submit through google forms

**Comment by Jds-23** [comment]
@ErinOCon just received an email saying I am eligible for Microgrant. 
<img width="1440" alt="Screenshot 2022-10-13 at 10 45 49 PM" src="https://user-images.githubusercontent.com/67229156/195663133-9df18a8a-c9b5-4050-8326-13874e2ef82c.png">

**Comment by ErinOCon** [comment]
Hi @Jds-23, thank you for your proposal! I have recently provided final report information in the proposal of a [previous project](https://github.com/filecoin-project/devgrants/issues/577). Do you expect these details can be submitted this week?

**Comment by Jds-23** [comment]
Hey @ErinOCon , I got stuck on some other task. Can I submit the submit update later this week.

**Comment by ErinOCon** [comment]
Hi @Jds-23, I haven't seen the report come through yet. Please let me know if there is an oversight on my end!

**Comment by ErinOCon** [comment]
Hi @Jds-23, this item has been closed. Please be in touch with any questions.
