### ISSUE TITLE
Next Step Microgrant: <Hexlibrium>

### ISSUE THREAD

**Issue by aeonicc** [filecoin-project/devgrants#1073]
### 1. What is your project? (max 100 words)

Game studio focused on connecting education and blockchain.
We envision game design solutions to provide a data-sovereign as digital twin service.
The game it self is a Play to learn approach oriented towards to teach financial literacy thought smart contracts code with an blockly language interface. 

### 2. Project links
  
Link to Github repo: https://github.com/aeonicc/HexlibriumIPFS
Link to demo or website, if applicable: www.hexlibrium.com
License: Original
Video pitch: https://vimeo.com/715407852

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

IPFS NFT`s game assets;
Steganografy technology to encrypt the wallet owner address to off-chain data features;
The game is building using an Data Oriented Design in which we envision to make synergy with FVM.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Make a beta version with:
>4096 NFT IPFS arts with attributes meta data;
>Design 10 levels related to the 10 planets;
>64 Procedural robots with their respective smart contracts features;

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, We agree.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes, it does.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
https://devpost.com/software/hexlibrium-9gi4sm

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Vinicius De Moraes Nascimento: 
https://www.linkedin.com/in/vinicius-de-moraes-nascimento-ba195850/
https://github.com/aeonicc
vinicci.exe@gmail.com

https://github.com/mard145
surrealdevelopers@gmail.com

* How did you learn about our microgrant program?
I received and e-mail from niki.gokani@protocol.ai 

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)

Chainlink Spring Hackthon

  * Please link to your hackathon submission

https://devpost.com/software/hexlibrium-9gi4sm

**Comment by ErinOCon** [comment]
Hi @aeonicc, thank you for your proposal! Can you confirm which license you are using and add this to the repo?

**Comment by aeonicc** [comment]
Hello Erin,

Can you help me choose the License?

I had chosen the original type license,

Not sure what the requirements are,

Thank you,

Em seg., 21 de nov. de 2022 às 14:08, ErinOCon ***@***.***>
escreveu:

**Comment by aeonicc** [comment]
> Hi @aeonicc, thank you for your proposal! Can you confirm which license you are using and add this to the repo?

Hello @ErinOCon it is open source Licence

**Comment by ErinOCon** [comment]
HI @aeonicc, thank you for your reply. Can you review our [open source policy](https://github.com/filecoin-project/devgrants/blob/master/open-source-policy.md) and confirm which license will apply?

**Comment by aeonicc** [comment]
Hello @ErinOCon it is under the MIT license!

**Comment by ErinOCon** [comment]
Hi @aeonicc, thank you for your patience with our review. We will not be moving forward with a grant at this time, but wish you all the best as you continue to build!
