### ISSUE TITLE
Filecoin Storage Farm Germany 

### ISSUE THREAD

**Issue by BHK-Industry** [filecoin-project/devgrants#1076]
Filecoin Storage Farm Germany

technical-design, core-dev

BHK-Industry 

Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?: Yes

# Project Description

Building and enabling the first Filecoin Storage Farm in Germany. Our plan is to simplify the access to Filecoin storage capacities in Germany. Our aim is to develop a user-friendly interface. Customers can buy storage as simple as ordering online. 

The collaboration between Protocol Labs, Filecoin Association and BHK Industry will help German customers to understand the Filecoin ecosystem.

We are currently at ESPA Las Vegas 10/11 - 10/13 to discuss our project. 

## Maintenance and Upgrade Plans

# Team

## Team code repositories

# Additional Information

**Comment by jenks-guo-filecoin** [comment]
Hi @BHK-Industry, great to hear about your project, and ESPA is great! 

This issues is meant to be a grant application, it doesn't seem like you intent to file one hence we might close this. 

You are welcome to post this in [Community Discussion](https://github.com/filecoin-project/community/discussions) for sparking some conversation. :-)

**Comment by BHK-Industry** [comment]
Hi everyone,

I want to ensure if we are eligible to file coin grants!


Regards,


BHK Industry

On 12. Oct 2022, at 04:08, jenks-guo-filecoin ***@***.***> wrote:

﻿

Hi @BHK-Industry<https://github.com/BHK-Industry>, great to hear about your project, and ESPA is great!

This issues is meant to be a grant application, it doesn't seem like you intent to file one hence we might close this.

You are welcome to post this in Community Discussion<https://github.com/filecoin-project/community/discussions> for sparking some conversation. :-)

**Comment by realChainLife** [comment]
Hi @BHK-Industry thanks for the project description. Unfortunately, this project type is not eligible for grant funding, and will not be considered here. We welcome you to explore other opportunities available within the ecosystem, the [Community Discussion](https://github.com/filecoin-project/community/discussions) @jenks-guo-filecoin recommended above is a good starting off point.
