### ISSUE TITLE
Next Step Microgrant: 🐍Snake Mania Game🐍

### ISSUE THREAD

**Issue by alexaport** [filecoin-project/devgrants#1077]
### 1. What is your project? (max 100 words)
Snake Mania is classic web3 game with DeFi, NFT-1155, ERC-20 token based fun and enteraining game

### 2. Project links
  
Link to Github repo: https://github.com/MoonBeamHack/Snake-Mania
Link to demo or website, if applicable: https://bafybeifs3xlomsfuufht63zr6xxievx6faglpxvngh4bm4qch2y53ju44y.ipfs.gateway.valist.io/
License:

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
- The game it self hosted on IPFS and NFT data like metadata, and images are stored on Filecoin/IPFS on NFT. Storage
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
* Implementing more NFT themes which basically stored on Filecoin/IPFS
* Improving gameplay and fixing some minor bugs
* Update game coins, purchase mechanism and cost of NFT like real game
* Adding polygon mumbai chain support to gain more uses through multichain

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Mandy (Solidity developer) [mlp@thundergamestudio.com] Github : alexaport
Jigar (Full Stack Developer) [jigar@thundergamestudio.com] Github : TGS2016

* How did you learn about our microgrant program?
 -- From protocol labs email
* If your project was created as part of an event or hackathon:
 -- Yes
 
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  -- Moonbeam's Connected Contracts
  
  * Please link to your hackathon submission
  -- https://devpost.com/software/snake-mania-6czx0i

**Comment by TGS2016** [comment]
License is MIT : https://github.com/MoonBeamHack/Snake-Mania/blob/main/License

**Comment by ErinOCon** [comment]
Hi @alexaport, thank you for your proposal! Can you briefly describe the long term goals for this project? Do you have any specific plans to build user participation?

**Comment by TGS2016** [comment]
Hi @ErinOCon ,
Sure. Further I would like to launch same project on android/ios so that market will be covered, Open multiplayer mechanism after that where multiple users can challenge against each other and winner can get ERC-20 tokens. Multiple themes are also in pipeline. We can also add few more themes if we get this grant so user will have more options in the game.
Thank you

**Comment by ErinOCon** [comment]
Hi @TGS2016, thank you for the additional information. We will not be moving forward with a grant at this time. Please feel welcome to reapply as your project continues to progress.
