### ISSUE TITLE
Next Step Microgrant: sharefilecoin.link 

### ISSUE THREAD

**Issue by sharefilecoin** [filecoin-project/devgrants#1078]
### 1. What is your project? (max 100 words)

A web app for decentralized file-sharing using IPFS and Filecoin. 
https://sharefilecoin.link/ - allows you to share files which are then packed into a format called a Content Archive (CAR) before being sent to the web3.storage API service to store files on IPFS/Filecoin and retrieves data with w3link using an HTTP endpoint (at w3s.link)

### 2. Project links
  
Link to Github repo: https://github.com/sharefilecoin/sharefilecoin.link 
Link to demo or website, if applicable: https://sharefilecoin.link/
License: MIT
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
This project is based on using the web3.storage API service via IPFS.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Next steps are spending more dev time to build the best Filecoin user experience with improving UI and adding optional Api.estuary.tech and other storage services.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
No
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Tim Zuiderbroek, info@sharefilecoin.link my role is Dev.
* How did you learn about our microgrant program?
Surfing Github and Filecoin
* If your project was created as part of an event or hackathon:
No
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Thank you for your proposal! Before considering this project for a microgrant, we would like to see how your building progresses. For next steps, we recommend participating in a [hackathon](https://hackathons.filecoin.io/)!  Thank you for your interest in our grants program.
