### ISSUE TITLE
EtherSign - QuickTemplate 

### ISSUE THREAD

**Issue by bsoldre** [filecoin-project/devgrants#1079]
# Open Grant Proposal: EtherSign - QuickTemplate

EtherSign - QuickTemplate

**Proposal Category:** `app-dev`

**Proposer:** bsoldre

**(Optional) Technical Sponsor:** Aaron Stanley, Piyush Maheshwari

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

QuickTemplate is a mobile based document template marketplace combined with e-signature. Together these provide a simple document workflow solution to help small business take their first steps in to a digital future. The project is aimed at helping small businesses in emerging economies. Users can buy, sell, send, sign, store and verify documents with the people they do business with. We use IPFS through web3 storage to store all of the document data while using the Polygon blockchain as a data index and e-sign system of record. 

We believe the next steps in the web3 distributed future must include tools regular everyday people can use on a day to day basis. To this end we have partnered with the USAID contractor Paladium to work on their project of "Digital Transformation of Small Business" in Latin America. Our tool will be used by businesses in the hospitality industry in El Salvador. They will use the tool to create simple e-document workflows. For example a fish monger can use the app to accept electronic orders for future banquets. A small hotel manager can use the app to collect employees weekly timesheets.

## Value

QuickTemplate is a chance for Filecoin (and the rest of us) to use their cutting edge tech to solve an important problem and lift up regular people in the emerging world. We believe that small businesses are force multipliers in economic growth. When you help a small business owner you also help, her family, her employees, their families, and the whole community they provides services to. By taking the wonderful tech you folks create we can empower the business owner with game changing tools. 

The distributed tech that we are all working on present dramatically different economics from what exists in web2. These economic advantages allow us to build tools that can reach and be profitable in geographies the web2 players have never served. This gives us a once in a lifetime opportunity to make a major impact on the lives of ordinary people. Presently, we are at the leading edge of this sea change. We have the tools and now is the time. Let's Go!

## Deliverables

We will use the grant funds to fully engage with the USAID org in El Salvador. We will take the existing product we have and work with the small business community in El Salvador to massage the product in to something they love and really fits their needs tightly. Once we have this we can spread the application in the 125 other countries USAID is working in.

## Development Roadmap
QuickTemplate -
We are searching for a strong product market fit with QuickTemplate. We will be working with the USAID org in El Salvador and their business clients to uncover the most impactful use cases and any barriers that may exist. For the next 6 months we will keep 2 development resources dedicated to quickly making changes to the apps as we churn on the value proposition with our business users.
**SDKs**
Mobile SDK to record e-signature events including storage of file in IPFS
Mobile SDK to search, find, buy, store, sell document templates.
**APIs**
Api to record e-signature events including storage of file in IPFS
API to search, find, buy, store, sell document templates.

CryptoEscrow - 
Our second product is a mobile app that presents a peer to peer escrow solution to business users. The escrow will be handled completely by smart contract. We will utilize our existing codebase and build on top of that. We currently have wireframes and brand guides for the CryptoEscrow application and with 2 developers could have a version 1 app built by April of 2023. From there we take the same approach with the same audience as the QuickTemplate app.
**SDKs**
Mobile SDK to create manage and execute escrow contracts
**APIs**
Api  to create manage and execute escrow contracts

4 development resources from now until April will require $140,000 ($35/hr per dev x 4 devs x 40hrs / wk x 25 weeks)

## Total Budget Requested

$140,000 ($35/hr per dev x 4 devs x 40hrs / wk x 25 weeks)

## Maintenance and Upgrade Plans

QuickTemplate and CryptoEscrow accept micro-payments in crypto in the form of transaction fees. Whenever a write transaction is requested the users will make a small payment to EtherSign's crypto wallet. We will be revenue positive at the end of this effort and will support the software with this revenue.

# Team

## Team Members

Brook Oldre - 15 yrs software development and leadership experience - Lifelong entrepreneur 
Drew Pearson - 20 years in marketing and leadership
Sunil Bafna - 25 years in operations and leadership

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/brook-oldre-7542495/
https://www.linkedin.com/in/thedrewpearson/
https://www.linkedin.com/in/sunil-bafna/

## Team Website

https://www.quicktemplate.app

## Relevant Experience

Brook Oldre has been involved in launching a number of very successful mobile applications as a contractor for Honeywell, Target, Medtronic and more.

Sunil Bafna has run a successful software services company for the last 25 years.

Drew Pearson is a go-to professional for digital marketing in Minnesota and beyond for the last 20 years for clients in the banking, education and consumer product industries.

## Team code repositories

https://bitbucket.org/boldre/etherchatmobile/src/develop/
Many others not currently public

# Additional Information
I attended a blockchain event in Minneapolis and also had contact with members of the Filecoin team.
brook@ethersign.app
See the QuickTemplate apps at the following links
Android: https://play.google.com/store/apps/details?id=com.ethersign
Apple: https://apps.apple.com/us/app/ethersign/id1620481733

**Comment by realChainLife** [comment]
Hi @bsoldre thank you for the proposal however we will not be funding work as its outlined. A few notes: 

- On QuickTemplate: who will be the major uses of the SDKs and APIs at this stage? Assuming that you'd be focusing on user-onboarding post-launch. What would this cost as a stand-alone deliverable?

- On P2P Escrow: The current project details are not enough to help us reach a funding decision. If you'd like to submit a separate proposal for this project development specifically, we would be happy to review that.
