### ISSUE TITLE
Next Step Microgrant: Filecoin Network Analytics Day by Starboard

### ISSUE THREAD

**Issue by sylvanzhang** [filecoin-project/devgrants#1082]
### 1. What is your project? (max 100 words)

Filecoin Network Analytics Day is a community event that aims to raise the awareness and inspire participation of analyzing the most important metrics of the Filecoin Network and generating new ideas based on network intelligence. In this event, we will dive into the network analytics that continually define and shape Filecoin.

We aim to host this event at FIL-Lisbon and we believe this event will be beneficial to the entire Filecoin community.

### 2. Project links

Previous talks and co-hosted events by Starboard
Talks and interviews
https://www.youtube.com/watch?v=72UadM5u0qs
https://www.youtube.com/watch?v=soCNjduv5Aw
https://www.youtube.com/watch?v=9Ol9PoYHsqs
https://www.youtube.com/watch?v=b1iX24s9CW4

Crypto-econ day @FIL-SG
https://www.youtube.com/watch?v=LYS3CrquJL8

### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

On the Filecoin Network Analytics Day, we will have insightful talks and discussions covering important topics on Filecoin network analytics, including:
- The importance of network analytics to Web3 governance and improvement
- Conducting effective network analytics for Filecoin - what's needed?
- Demystifying Filecoin circulating supply
- Analyzing key health metrics of Filecoin
- Storage provider reputation analytics
 
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We will use this grant to cover some logistics and expenses of the event, making it a high quality event with positive impact for the community to inspire more participation.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions

https://www.filecoinanalytics.xyz/home
  
### Additional questions:

Main point of contact: Sylvan @Starboard
Email: sylvan@starboardventures.io
Role: main organizer
We learned about this program through referrals from the LabWeek22 event team.
Name of event: Filecoin Network Analytics Day
https://www.filecoinanalytics.xyz/home

**Comment by ErinOCon** [comment]
Hi @sylvanzhang, this request falls outside the scope of the microgrant program. A member of the Orbit team will be in touch by email to discuss possible reimbursement options.
