### ISSUE TITLE
Next Step Microgrant: <Web3Cloud>

### ISSUE THREAD

**Issue by stevetn611** [filecoin-project/devgrants#1083]
### 1. What is your project? (max 100 words)
Project Name: Web3Cloud- DISTRIBUTED STORAGE And COMPUTING FOR WEB3
Built with IPFS, Filecoin, OrbitDB, FilSwan-MCS

### 2. Project links
  
Link to Github repo: https://github.com/stevetn611/Fdrive
Link to demo or website: https://web3cloud.tech
License: Apache2
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  IPFS for stored data , hosting Dapp on Filecoin Network, OrbitDB for mapping folder and CID to manage data structures on IPFS. MCS use for multichain payment, get price feed from chainlink,..

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

**Implement for Fdrive product (Decentralized data storage drive)**

| No.        | Milestone Description | Estimated Timeframe |
| :---        |    :----:   |          ---: |
| 1.   | Implement feature DID Authentication (DIDs is the W3C standard for decentralized identifiers. The DID specification outlines a standard URI scheme for creating a persistent decentralized identifier (DID) for a given subject as well as resolving metadata about that identifier)        | 2 weeks      |
| 2.   | AmazonS3 Data Migration integration      | 2 weeks      |
| 3.   | Mint and Store NFT Data, allow upload folder        | 1 week      |
| 4.   | DApp integration API (for enabling IPFS publishing/linking to DApp)     | 2 weeks      |
| 5.   | Implement feature Allow editing and updating file content in stateful data structures on IPFS     | 2 weeks      |

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://dorahacks.io/buidl/3281  (Runner-up Prize)

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
    Tri Nguyen - CEO  Linkedin: https://www.linkedin.com/in/tringuyen611/
    Hoa Le - CTO  Linkedin: https://www.linkedin.com/in/hoaflee/
    Toi Hoang - Developer  Linkedin: https://www.linkedin.com/in/toihoang/
* How did you learn about our microgrant program?
    Microgrant program have incubated a lot of projects to more quickly grow up and contribute to the development ecosystem of for Filecoin network
* If your project was created as part of an event or hackathon:
    DataDao Hackathon - Dorahacks
    https://dorahacks.io/buidl/3281

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @stevetn611, can you provide a preferred email address for confirming payment information?

**Comment by stevetn611** [comment]
> Hi @stevetn611, can you provide a preferred email address for confirming payment information?

Thanks @ErinOCon , My email: tringuyen.brse@gmail.com

**Comment by jenks-guo-filecoin** [comment]
Hi @stevetn611, we have asked FilSwan team to look into your repo. However they have not found the use of their product. Could you let us know your plans of incorporating their product in your project?

**Comment by stevetn611** [comment]
Hi, Filecoin DevGrant,

At the current stage, We splitting up the "Web3cloud IChill Ecosystem"
project (for Hackathon) into 2 separate projects (Web3cloud project:
web3cloud, the current stage does not use FilSwan services, and IChill
project: decentralized video sharing platform that uses FilSwan's MCS
storage ).
For this Microgrant, We apply for the Web3cloud  project so whether it
would be eligible to get funds from Filecoin's microgrant?

Many Thanks!

**Comment by ErinOCon** [comment]
Hi @stevetn611, thank you for providing the additional context. Can you briefly describe how you will accomplish usage growth for both Web3Cloud and Web3Cloud IChill?

**Comment by stevetn611** [comment]
Hi @ErinOCon,
Sure, The following is our  go to market strategy plan:
Web3Cloud:
     -Partnerships with top projects of the ecosystem.
     -Provide free trial services plan
     -Create hackathons/dev grant to evangelize the protocol amongst
developers
     -Build Reward/ incentive mechanism to incentivize network services use
     -Speed up launch mainnet for Storage and Hosting services soon and
blockchain payment menthod soon

Ichill Ecosystem:
     -Partnerships with KOLs, Creators to produce more content videos (
create-to-earn)
     -Launch Reward mechanism to incentivize create-to-earn, watch-to-earn
     -Reduce services fee by using decentralize storage service (based on
Filecoin network)
     -Organize idol contests/online courses to encourage/expand service use


Thanks.

**Comment by stevetn611** [comment]
Hi @ErinOCon , anything update?

**Comment by stevetn611** [comment]
Hi @ErinOCon ,
we are partner with FilSwan and will release the next version on the polygon mainnet soon.
If you have any updates about Microgrant for Ichill-Web3Cloud  Ecosytem. Let inform me!
Thank you!

**Comment by ErinOCon** [comment]
Hi @stevetn611, thank you for checking in! Before we provide a final update, can you provide the current repo for this project? It looks like the previous repo provided is not working.

**Comment by stevetn611** [comment]
@ErinOCon Sure, here it is.
https://gitlab.com/ichill-web3cloud-ecosystem

**Comment by stevetn611** [comment]
Hi @ErinOCon ,
I just updated repo permission. For commercial reasons, we just share some repo relative to IPFS, Filswan-MCS
For account verification purposes, here is the link reference to your Github handle: https://gitlab.com/tringuyen611

**Comment by stevetn611** [comment]
Hi @ErinOCon , Ichill Ecosystem Team still keep in touch with FilSwan Team (Mr. Charley Chen) and just release Ichill Dapp v1.1 which integrates to Filswan MCS SDK new version, and continues building Ichill Funding Platform. 
So Hope you see that we keep building more features.
Thanks.

**Comment by ErinOCon** [comment]
Hi @stevetn611, thank you very much for your patience and for the provided updates! I will be in touch by email to discuss the remaining payment steps.
