### ISSUE TITLE
Next Step Microgrant:PixelMetaverse

### ISSUE THREAD

**Issue by gaorany** [filecoin-project/devgrants#1085]
### 1. What is your project? (max 100 words)
PixelMetaverse is a self-identity pixel metaverse. Everyone can choose their favorite picture to pixelize, we provide a variety of algorithms and various attributes, users can upload pictures to IPFS/Filecoin and mint into nft in polygon, which represents your presence in the Metaverse identity. This self-produced identity pixel is like your avatar on Facebook, Twitter. It's your external show pic.

### 2. Project links
  
Link to Github repo:
https://github.com/gaorany/pixelmetaverse
Link to demo or website, if applicable:
Not yet.  But you can look the video in our hackathon submission
License: MIT 

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
 We use various image processing algorithms to pixelize the image, and use IPFS/Filecoin's nft.storage to store the user's metadata in a decentralized storage network and perform Mint into nft in the polygon network

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
 We will use this grant to accomplish the following:
1. Modify the contract to create an IPFS/Filcoin based content storage space with a pixel identity
2. optimize website
3. Add user login function, build my nfts & my data & my activitys

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes

### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
   https://devpost.com/software/pixelmetaverse

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  LiZiYang , Product Design & Team Leader , gaoranycos@163.com , https://github.com/gaorany
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  [Polygon BUIDL IT : Summer 2022](https://buidlit.devpost.com/)
  * Please link to your hackathon submission
  https://devpost.com/software/pixelmetaverse

**Comment by ErinOCon** [comment]
Hi @gaorany, we will not proceed with a grant for this project. Thank you for your proposal.
