### ISSUE TITLE
Next Step Microgrant: Building data access layer for Mina Protocol.

### ISSUE THREAD

**Issue by gundeep** [filecoin-project/devgrants#1086]
### 1. What is your project? (max 100 words)
The project initially coined DALi (Data Access Layer) wants to build a library for MINA protocol using IPFS since like some other blockchains, Mina's on-chain storage is very limited (255*8 (Field) bits). This unlocks a whole new set of ZK-apps which could initially not be possible due to the constraints.

### 2. Project links
  
Link to Github repo:  
Link to demo or website, if applicable: https://showcase.ethglobal.com/ethamsterdam/dali-p0q8r
License: MIT
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
IPFS / WEB3.stroage will be the backbone of this library, which enables reliable and quick retrieval of the data. 

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. Currently as part of the demo, one needs to manually extend the OffChainStorageSmartContract class to be able to use the IPFS. We would like to convert this into a library so that its easy to import into Mina's ZK-apps.
2. Also, in the initial prototype was only built from an NFT storage perspective hence it only store images. Whereas we would like to generalize this library further to be able to store data of other types too.
To implement step 1 and 2 requires significant time and effort and grant will allow us to do so.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?
Yes indeed. That seems like a great milestone to work towrards. Would be happy to know if there is some report template!
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
https://github.com/octaborg/mina-data-layer
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Gundeep Singh Bhamra(Backend Dev) https://github.com/gundeep

* How did you learn about our microgrant program?
Recieved an email to apply from niki.gokani@protocol.ai

* If your project was created as part of an event or hackathon:
ETH Amsterdam 2022.
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
  https://showcase.ethglobal.com/ethamsterdam/dali-p0q8r

**Comment by gundeep** [comment]
Hello Team Filecoin, 

How often are the Microgrant proposals reviewed?

Best,
Gundeep S

**Comment by jenks-guo-filecoin** [comment]
Hi @gundeep, Microgrant applications are reviewed weekly. However we might not have capacity to be able to complete the queue every week. Rest assured, your application will looked at and responded in time.

**Comment by gundeep** [comment]
Thanks, @jenks-guo-filecoin will keep an eye on it.

**Comment by gundeep** [comment]
Thank you for the update @ErinOCon.
Is there an email I can reach out to for more information about the report? Or is here the best place to ask questions?

**Comment by ErinOCon** [comment]
Hi @gundeep, I hope you are doing well! Do you still have outstanding questions regarding the report?

**Comment by gundeep** [comment]
Hi @ErinOCon I am fine for now. Thanks
