### ISSUE TITLE
FileCoin Sentiment Analysis

### ISSUE THREAD

**Issue by conorforde** [filecoin-project/devgrants#1090]
### 1. What is your project? (max 100 words)

This project is an app that gets the price of filecoin cryptocurrency and also gets news articles on that day and then we use this dataset to identify if there is a correlation between the sentiment of news articles and the change in price of the cryptocurrencies.

### 2. Project links
  
Link to Github repo: https://github.com/conorforde/filecoin-sentiment-analysis
Link to demo or website, if applicable: https://www.youtube.com/watch?v=2IFKGb0-K2E
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

I use IPFS to store the data from the APIs so I can access and use the data quickly and easily.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

I want to add the Gmail API to alert me when the news is specifically active (i.e. the change is above 5% from the previous day). But I also want to build up the dataset by collecting some historical data to make the insights from the data more useful. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes I agree 

### 6. Does your proposal comply with our Community Code of Conduct?

Yes it does

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

No

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Conor Forde, forde.conor@yahoo.com, conorforde, owner, developer
* How did you learn about our microgrant program?
* Google
* If your project was created as part of an event or hackathon: No
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @conorforde, thank you for your proposal! Before considering this project for a grant, we would like to see more building progress. For next steps, we recommend participating in a [hackathon](https://hackathons.filecoin.io/)! Thank you for your interest in our grants program.
