### ISSUE TITLE
Next Step Microgrant: <FindTruman>

### ISSUE THREAD

**Issue by Tasse00** [filecoin-project/devgrants#1091]
### 1. What is your project? (max 100 words)

FindTruman is the STEAM-like co-creation story-gameplay platform in Web3. Our team has accumulated more than 30 million registered users on our APP, 1,500 authors in Web2. To solve the current issues in Web2 story-gameplay industry (i.e. the profit distribution problem, the piracy problem, …), FindTruman further clarifies the proof-of-stake and incentive mechanism to make the creators and players more profitable with Web3 thinking and blockchain technology. In FindTruman platform, you could experience the joy of story-gameplay, the rewards of participation in content co-creation and the potential airdrops of story NFTs.

### 2. Project links
Link to Github repo: https://github.com/findtruman-official
Link to demo or website: https://findtruman.io
License: GPL license

### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
This project will use IPFS technology to effectively protect the story content and encourage content co-creation. We will make IPFS as our general data solution in our UGC Editor Platform. Moreover, with Filecoin network, we will periodically back up the story contents for persistence store, which will ensure that the users' data assets will not be lost accidentally.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

With this grants, we will be helped to use IPFS technology to effectively protect the story content and encourage content co-creation. It will make IPFS as our general data solution in our UGC Editor Platform.

We will further build our UGC Editor platform, and all the descriptive contents (i.e. the story title, content, cover) will be stored in IPFS system, while the user's ownership of the corresponding content(i.e. the author name, the Hash ID of the story content, the status of story NFT, etc.) will be recorded on blockchain. 

For building the co-creation functions of our UGC Editor, we will further use the IPFS to store all the task descriptions published by the creator, and the works submitted by the applicants.

Moreover, by using the FileCoin network, we will periodically back up the story contents in the UGC Editor platform for persistence store, which will ensure that the platform data assets will not be accidentally lost.

	
### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.

  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions
We won the Protocol Labs Special Awards of 2022 Wanxiang Blockchain Fall Hackathon
Details: https://wxblockchain.medium.com/announcing-the-winners-of-2022-wanxiang-blockchain-fall-hackathon-46138d443769?source=social.tw

### Additional questions:
Here are the co-founders of FindTruman:

- Will (Co-Founder, CEO, miura7728@gmail.com): founder of a Web2 online story-gameplay application with 30 million users and thousands of professional content creators. 
- Lyon (Co-Founder, CTO, longfenghou@gmail.com): got his PhD in France in data science, and enter the blockchain industry in 2017 to do some technical research and development.
- Bing (Co-founder, CMO, findtruman.io@gmail.com): got her PhD in France in CS, and is invited as academic scholar by National University of Singapore during 2022-2023 in Blockchain Innovation Lab.

•How did you learn about our microgrant program?
Through conversations we had with Isabella and Longfei at Protocol Labs.

**Comment by ErinOCon** [comment]
Hi @Tasse00, this microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
