### ISSUE TITLE
CLEAFI

### ISSUE THREAD

**Issue by 1Busayo** [filecoin-project/devgrants#1092]
### 1. What is your project? (max 100 words)
Using web3  to create a green environment and reduce carbon emissions.it helps recyclers to convert their images into NFTs with the help of smart contracts and are stored on a decentralized storage IPFS
### 2. Project links
  
Link to Github repo: https://github.com/1Busayo/CLEAFI
Link to demo or website, if applicable: https://cleafi.com
License:

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
IPFS is used for NFT storage
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

 Meeting with recyclers on how the current method can be adapted with web3 and also how to onboard recyclers to adopt new ways on how they can get supported in recycling more

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes

  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes it complies
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
name: Samuel Fanimokun
email: fanimokunbusayo@gmail.com
Github account: https://github.com/1Busayo
role: developer/founder
* How did you learn about our microgrant program?
filecoin green grant idea
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  EthCC Hack 2022
  * Please link to your hackathon submission
  * https://devpost.com/software/cleafi?ref_content=my-projects-tab&ref_feature=my_projects

**Comment by ErinOCon** [comment]
Hi @1Busayo, thank you for your patience with our review. - This microgrant has been approved! We will send an email to confirm payment details. Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). 

Please let us know if you have any questions!

**Comment by 1Busayo** [comment]
Thanks @ErinOCon  i would make sure i submit the report as soon as possible
