### ISSUE TITLE
RFP Proposal: Filfox with FVM / FEVM support

### ISSUE THREAD

**Issue by chadwick2143** [filecoin-project/devgrants#1094]
# RFP Proposal: `Filfox with FVM / FEVM support`

**Name of Project:** Filfox with FVM / FEVM support

**Link to RFP:** [Block Explorer with FVM / FEVM support](https://github.com/filecoin-project/devgrants/blob/master/rfps/fvm-block-explorer.md)

**RFP Category:** `devtools-libraries`

**Proposer:** `chadwick2143`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** No

# Project Description

[Filfox](https://filfox.info/en) is currently one of the best explorers for Filecoin. With user programmability arriving to the Filecoin Virtual Machine early next year, we are going to update Filfox to showcase activity and interactions involving user-defined actors (native and EVM smart contracts). 

### Milestone 1: Basic FVM features on Wallaby Testnet

- Actor Introspection Tooling for both EVM and native FVM
  - Actor ABI view (Solidity and native ABIs)
  - Actor code view: Wasm bytecode, EVM bytecode, and high-level code
  - Internal transactions

- Transaction data
  - Interpreting token transfers, internal transactions

- Transaction metadata (function name, message type, value, etc.)
  - Parsing of passed parameters and return values
  - Support for both EVM and Filecoin addresses (f0, f1, f2, f3, f4)
  - Gas information

- Support for all address classes
  - Displaying all addresses associated with an actor

### Milestone 2: Advanced FVM features on Wallaby Testnet

- Actor Introspection Tooling for both EVM and native FVM
  - 4byte integration for function signatures (EVM)
  - Internal transactions and decoding those

- Transaction data
  - decoding token transfers, internal transactions

- Transaction metadata (function name, message type, value, etc.)
  - Logs emitted
  - State difference

- Support for all address classes
  - Including F4 address class (decomposing the address)
  - Displaying Ethereum address equivalents

- Support for abstract accounts and delegated transactions

### Milestone 3: Additional features on Wallaby Testnet

- Contract source code verification

- Contract interactions for developer testing
  - Read-only methods based on ABI
  - Write methods based on ABI

- Public API other developers can use

- Token tracker

### Milestone 4: All features on mainnet and ongoing maintenance updates

- All features on mainnet
- Ongoing maintenance updates with long term support

## Milestone Summary

| Milestone No. | Milestone Summary & Staffing | Funding | Estimated Timeframe |
| ------------- | ---------------------------- | ------- | ------------------- |
| 1             | Basic FVM features           | $A      | 4 weeks             |
| 2             | Advanced FVM features         | $B      | 5 weeks             |
| 3             | Additional features          | $C      | 6 weeks             |
| 4             | Ongoing maintenance updates  | $D      | 5 years             |

## Total Budget Requested

We will DM this to @eshon via [Filecoin Slack](https://filecoin.io/slack).

## Maintenance and Upgrade Plans

**Long Term Support**

# Team

## Contact Info

Provide us with a way to contact you (email is probably easiest). You can also email grants@filecoin.org with your GH username and link to your public proposal.

## Team Members

- Team Member 1 - Github and/or LinkedIn profiles
- Team Member 2 - Github and/or LinkedIn profiles
- Team Member 3 - Github and/or LinkedIn profiles
- ...

## Team Website

https://filfox.info/en

## Relevant Experience

Please describe (in words) your team's relevant experience, and why you think would do a great job with this RFP. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

## Team code repositories

Please provide links to your team's prior code repos for similar or related projects.

# Additional Information

Please include any additional information that you think would be useful in helping us to evaluate your grant application.

**Comment by ErinOCon** [comment]
Hi @chadwick2143, since this approved project kicked off last year, I have closed this issue. Please contact grants@fil.org with any new updates or questions regarding the grant.
