### ISSUE TITLE
Uncl🖤ak

### ISSUE THREAD

**Issue by thor314** [filecoin-project/devgrants#1096]
# Open Grant Proposal: `Uncl🖤ak`

**Name of Project:** Uncl🖤ak

**Proposal Category:** `community` 
Secondarily `docs` 

**Proposer:** Github: https://github.com/thor314; twitter: https://twitter.com/cryptograthor

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`: None

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Hell yeah

# Project Description
For a full description, see https://uncloak.org,
But to give a short summary:

Uncloak is an attempt to synthesize an approachable, structured knowledge base on topics in cryptography for cryptography practitioners and a broader developer community. We claim that developers are increasingly exposed to cryptography concepts and tools on a regular basis, but are likely to misunderstand and misuse cryptography tools. The problem also extends to cryptography implementers: many engineers in the cryptocurrency space work cryptography systems, including threshold computation, zero knowledge, and fully homomorphic encryption schemes. Because these systems are novel to the last 10 years while cryptography engineering curriculum has largely stagnated, engineers are ill-prepared to implement modern cryptography systems.

Uncloak is currently working on two projects: the [cryptography wiki at uncloak.org](https://uncloak.org/) and weekly study groups. Our first study group on [Cryptography Engineering with Rust](https://uncloak.org/courses/rust+cryptography+engineering/course-Rust+Cryptography+Engineering+Study+Group+Syllabus) launched November 18, 2022, and there are plans for further study groups in the works.

The site will initially focus on generating content directed at cryptography learners and developers in cryptography engineering and zero knowledge, as we see these fields as most lacking in resources. Where there are already decent existing resources (Wikipedia pages, blog posts, etc.), the site will aim to link to them, while we expand content in target areas where the need is greater. These stubs are great candidates for first-time-contributions.

## Value
The Uncloak project represents a common resource for cryptography engineers in particular, and systems developers in general. We claim that one of the major obstacles for Filecoin's development is the inaccessibility of pedagogical material on the novel systems engineering concepts developed by Filecoin and others. Uncloak is attempting a way forward for guiding engineers through novel cryptography in particular, and systems development in general.

## Deliverables and Development Roadmap
We're focused on creating content for our wiki and initial course on cryptography engineering. 

We would like to suggest roadmap goals could be tied to material produced for our course and wiki. We might propose a scheme like 30 new pages per month, over the course of three months.

## Total Budget Requested
I'm asking for $25,000 over a 3 month time horizon. The funding can be tied to site and course development, as described above.

## Maintenance and Upgrade Plans
For the site, maintenance is site-hosting, which is relatively cheap. We are also investigating migrating the site to be mirrored on IPFS. 

# Team 

## Relevant Experience
[I’m](https://twitter.com/cryptograthor) a cryptography engineer. For the last year, I’ve been running the [Proofs, Arguments, and Zero Knowledge Study Group](https://gitcoin.co/grants/6020/the-proofs-arguments-and-zero-knowledge-study-gro), with Dr. Justin Thaler, centered around his [pre-print book](https://people.cs.georgetown.edu/jthaler/ProofsArgsAndZK.pdf) on Zero Knowledge Cryptography. Under a grant from the Ethereum Foundation, I wrote [learning-grade implementations](https://github.com/thor314/pazk) of early protocols in the book, in Python and Rust.

I’ve watched the zero-knowledge community space grow. I’ve mentored newcomers grokking to the space, and exchanged complaints about the discontinuity in the available learning resources. Our information is siloed across disconnected papers and blog posts. The top result on a [search for Pedersen Commitments](https://duckduckgo.com/?t=ffab&q=pedersen+commitment&atb=v344-4vb&ia=web) is a stack-exchange complaint from 2018 that information on Pedersen commitments is either unavailable, or not delivered at the right level.

As an educator, I’ve had a front-row seat to zkFOMO, zkFrustration, and zkDisinformation. As an engineer, I’ve been working for the last year to build [Entropy](https://entropy.xyz/), a decentralized asset custodian network, building on recent work in ECDSA threshold signature schemes (TSS). After integrating our network with the [Axelar GG20 implementation](https://github.com/axelarnetwork/tofn), I grew into an engineering management role, hired engineers, and set direction for the company, which I am leaving in competent hands while I pursue this new project. And as a student, I contributed mathematical security research towards a [consensus mechanism that secures billions of dollars](https://arxiv.org/abs/2003.03052).

## Team code repositories
- https://github.com/thor314/uncloak
- https://github.com/thor314/uncloak-hw

# Additional Information
- email: thorck@pm.me.

**Comment by realChainLife** [comment]
Hi @thor314 thank you for the proposal. While I appreciate mapping a development roadmap for the project might be tough at this stage we absolutely need one to support the estimated completion timeframe and budget requested. 

Are you able to consider a phased-development approach based on two areas: 

- Phase one: Content creation
- Phase two: Platform development

With this split, we'd be happy to consider a phased-funding option starting with phase-one. If this works for you, please rework the proposal to reflect the phase-one milestones and total budget request.

**Comment by ErinOCon** [comment]
Hi @thor314, I hope you are doing well! Do you expect to have an update available by next week?

**Comment by thor314** [comment]
Hi, thanks for the bump. There are several updates to the project. Since the original proposal, focus has shifted more in the direction of content creation and education. Platform development isn't on the near-term roadmap. 

Two weeks ago we launched the site (https://uncloak.org/, https://github.com/thor314/uncloak.org), and last week we launched our first study group on Rust-based Cryptography engineering (https://hackmd.io/@thor314/ryEWRY6Qs), with over 150 in attendance (unclear how many stick around though!) Both projects aim to create resources for cryptography learning. 

Depending on which of these projects sounds more appropriate for the Filecoin foundation to support, we could structure a phased milestone plan based on either cryptography resources on the site (eg N new resource new pages per grant milestone), or resources around Rust-based cryptography education, centered around the course. We intend to build exercises in the spirit of [cryptopals](https://cryptopals.com/), for example, here are solutions for the first week's exercises https://hackmd.io/LfgJiWdTRQKoIDOe1na-eQ.

There are plans to follow up the initial study group with further courses on more advanced cryptography engineering topics, zero knowledge protocols, and multiparty computation techniques, mirrored by efforts to contextualize course material on the site, these are about 4 months down the road.

Also, I think I probably over-asked in my initial submission. I'm proposing an update to a 3-month timescale, over a 25k sized grant.

**Comment by realChainLife** [comment]
@thor314 great to hear you'll be prioritiing content creation at this stage, happy to work with your preferred subject here, both if applicable as well. Please rework the proposal to reflect this development plan change and we'll re-evaluate.

**Comment by thor314** [comment]
@realChainLife Updated. Thanks for the flexibility.

**Comment by ErinOCon** [comment]
Thank you, @thor314! We will circle back once the next round of our review is complete.

**Comment by ErinOCon** [comment]
Hi @thor314, I know it has been a considerable amount of time since we have provided an update for this proposal. In light of the macroeconomic climate, the review of our budget and priorities for the fiscal year has resulted in a longer evaluation period.

Unfortunately, we will not be moving forward with a grant at this time. We are wishing you all the best as you continue to build!
