### ISSUE TITLE
Hiring Blocks: Decentralizing Talent and Opportunities 

### ISSUE THREAD

**Issue by hiringblock** [filecoin-project/devgrants#1099]
### 1. What is your project? (max 100 words)
Hiring Blocks is aimed at becoming a one stop solution where talent meets opportunities in a truly decentralized manner. Hiring Blocks is a decentralized job listings and talent marketplace. All the companies or projects can list their jobs here and the candidates can apply from the platform. 

We are also providing the chat feature and will build the video interview feature going forward. This will help bring all the people hiring related options at a single place.

### 2. Project links
  
Link to Github repo: https://github.com/hiring-blocks/hiring-blocks-app
Link to demo or website, if applicable: https://hiringblocks.xyz/

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
We are using IPFS to store the static content of the website which will include resume, images, logos of organizations, organization info etc. We will be facilitating the video interviews between candidates and companies using IPFS tech stack like Huddle. Going forward user can mint their skills and achievements as NFTs which will also be stored using IPFS tech like nft storage. 

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. Enhancing UI and UX of the application to create a better experience for our platform users
2. Exploring options of mobile application
3. Admin dashboard to check the health of the application as well as smooth the operations of company and user onboarding.
4. Create a better chat features for the interviewer and interviewee
5. Try to explore and integrate a video calling in the application for scheduled interviews using Huddle, 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes we will share the monthly progress report with Foundation. 
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program? Website
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by hiringblock** [comment]
Hi @ErinOCon please let me know if you need any specific detail or information about the project for the review.

**Comment by hiringblock** [comment]
Hi @ErinOCon is there any update on the application?

**Comment by hiringblock** [comment]
Hi @ErinOCon please let me know if there's any update regarding the application.

**Comment by ErinOCon** [comment]
Hi @hiringblock, thank you for your patience. Can you point to how IPFS, Filecoin, or closely related tech is included in your code? Also, I noticed the linked repo belongs to "[hiring-blocks](https://github.com/hiring-blocks)". Can you briefly describe how this handle is related to yours?

**Comment by hiringblock** [comment]
Thank you @ErinOCon   , We are using IPFS to store the static content of the website which will include resume of candidates, images, logos of organizations, organization info etc. We have updated the repository and added the backend code where we are using IPFS as our storage layer. We will be facilitating the video interviews between candidates and companies using IPFS tech stack like Huddle. We will also issue NFTs using IPFS as storage layer for the achievements of the candidates. Going forward we will integrate chat option facilitated by IPFS tech stack between companies and candidates. 

We have two different githubs made for the purpose of segregation of notifications of development and applying grants. We own the other one as well.

**Comment by ErinOCon** [comment]
Hi @hiringblock, thank you for the additional information. I will circle back with an update shortly!

**Comment by hiringblock** [comment]
Thank you @ErinOCon looking forward to hearing from you. Really excited to build using IPFS/Filecoin and FVM going forward.

**Comment by hiringblock** [comment]
Hi @ErinOCon , is there any update regarding our application?

**Comment by ErinOCon** [comment]
Hi @hiringblock, thank you for your patience with our review. Before considering for a microgrant, we would like to see how the building for this project continues to progress. For next steps, we recommend taking this to a [hackathon](https://hackathons.filecoin.io/).

Thank you for your interest in our grants program!
