### ISSUE TITLE
Next Step Microgrant: Tooling for Alexa Voice Developer

### ISSUE THREAD

**Issue by goldzulu** [filecoin-project/devgrants#1101]
### 1. What is your project? (max 100 words)

Tooling for Alexa Voice Developer

Opens up Web3 to the over 1 million Alexa developers out there by reducing cost of storage and bandwidth.

### 2. Project links
  
Link to Github repo: https://github.com/goldzulu/helloblockchain
Link to demo or website, if applicable: https://youtu.be/ijlIpv0TwfQ
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

In the initial implementation, an SDK functionality that use Web3.Storage to store persistent data over multiple Alexa conversation sessions has been developed.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The improvement would next build on top of the initial implementation by the introduction of another functionality to the SDK to the allow the easy use of NFT.Storage to encapsulate audio sound files that can played back on Alexa enabled devices.

- A command line interface (CLI) will be developed to generate NFT meta data from Audio files automatically
- An API will be built to translate from NFT.storage NFT format so that it can be consumed by Alexa for sound playing 
- A video tutorial on the voicetechguy's YouTube channel will be done to show how to use it
- A corresponding blog will be written and submitted to Medium 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project. 
GoldZulu, goldzulu222@gmail.com, https://github.com/goldzulu, Lead Developer

* How did you learn about our microgrant program? 
Suggested as next step after winning the hackathon

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  Moralis Filecoin 1,2 Web3 Hackathon

  * Please link to your hackathon submission
  https://github.com/goldzulu/helloblockchain
  https://youtu.be/ijlIpv0TwfQ
  https://www.youtube.com/watch?v=a_2n0sEPuxc&t=352s

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
