### ISSUE TITLE
Next Step Microgrant: Krypto Koffee

### ISSUE THREAD

**Issue by elcharitas** [filecoin-project/devgrants#1107]
### 1. What is your project? (max 100 words)

**Krypto Koffee** is a decentralized crowd funding/payment bridge application for web3 content creators. It is a web3fied version of buymeacoffee.com which allows content creators receive support from their audience in cypto.

Krypto Koffee allows **creators**(artistes, designers, developers etc) to grow and get rewarded for their effort in building a loyal community of connected users who share and engage with them on their platform.

### 2. Project links
  
Link to Github repo: https://github.com/elcharitas/krypto-koffee
Link to demo or website: https://krypto-koffee.vercel.app/
License: MIT License
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

Internally, Krypto Koffee uses w3name and web3.storage in handling user data. User information is stored securely off-chain on web3.storage. While, w3name is used to keep track of user data updates. 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
The next steps would be to:
   * Get one extra developer on board to make work faster
   * Fix some existing known bugs on Krypto Koffee
   * Introduce new features such as locked posts/content, in-app chat etc.
   * Actively build, test and ship Krypto Koffee.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes I do. Grant reports would be prepared a-forehand and shared when requested.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes it does. I looked through the code of conduct and found this proposal complying with it

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* https://www.encode.club/eth-safari-hackathon
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  * Jonathan Irhodia - jonathanirhodia@gmail.com - https://github.com/elcharitas (Full Stack Developer)
* How did you learn about our microgrant program?
  * I learnt via mail after winning prizes on the ETHSafari Hackathon
<img width="746" alt="Screen Shot 2022-10-26 at 3 08 19 PM" src="https://user-images.githubusercontent.com/30146982/198048577-676af6a7-5052-496a-99a3-e9c6ef6d0237.png">

* If your project was created as part of an event or hackathon:
  * What was the name of the event? ETHSafari
  * Please link to your hackathon submission: https://krypto-koffee.vercel.app/

**Comment by elcharitas** [comment]
Hello @ErinOCon What's the update on this grant?
What comes next after creating the issue?

**Comment by elcharitas** [comment]
Hello @ErinOCon What's the update?

**Comment by elcharitas** [comment]
Hello @ErinOCon Whats the update on this application

**Comment by ErinOCon** [comment]
Hi @elcharitas, this microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by elcharitas** [comment]
> Hi @elcharitas, this microgrant has been approved! We will send an email to confirm payment details.
> 
> Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

Thanks for this update @ErinOCon
I await the email.
