### ISSUE TITLE
Open Grant Proposal: MINDFLY ‘Art + Sport’ Platform 

### ISSUE THREAD

**Issue by mindflyart** [filecoin-project/devgrants#1108]
**MINDFLY ‘Art + Sport’ Platform**

**Proposal Category:**  `integration-adoption`

**Proposer:** `mindflyart`

**Technical Sponsor:** `Jenks Guo  from Filecoin Australia`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:**  `No`

# Project Description

 MINDFLY.art is the first collaborative platform among art and sport  in the world, it strives for a decentralized community, and boosts the both industries through cross collaboration on-chain, especially in NFT and related media. MINDFLY is creating a unique cultural ecosystem in Art+Sport mechanism, inspiring more people into art and sport .

We aim to build up an ever-growing solution to scale the integration,  between two most fascinating industries ( Art and Sport ) in the world, in the past ten months, regarding the art industry, MINDFLY has attracted lots of artists onboard from different countries, through art exhibition and competition,  when it is becoming a four dimensional platform for art creation, storage and display across artist communities. MINDFLY would allow and educate artists to start using IPFS and Filecoin infrastructure directly in MINDFLY eco-system, from integrated functions, where a portal would be applied under the infrastructure of NFT.storage, allowing artists can create, display and store their creations ( including video and music ) ,  simultaneously all NFT from onboard artists ( not only from MINDFLY ) would be motivated with utilities to apply filecoin IPFS service .

MINDFLY is also running Dao community ( mindfly.dao) for sport lover, ( especially for soccer ), who is passionate to reform unfair regulation in different election and hosting for sport competition, like in the World cup, there would be chance to let all documentary and event related information stored in decentralized system, like mint NFT via IPFS,and storage etc, applicable in the NFT Sport+Art collection, MINDFLY would invite different nation team players and fans to collaborate during the World Cup in Nov, the best solution for our upcoming activities would be through Filecoin IPFS storage mechanism.

MINDFLY is creating an eco-system to help artists promote their arts through sport event and NFT collaboration, simultaneously, sport events can collaborate with artists through customized business model in MINDFLY platform, where the artists and athletes would team up to demonstrate their dream and ambition genuinely, through unique on chain mechanism, by picture, video or audio files, the uniqueness of MINDFLY will customize NFT algorithm in mutual interest.
MINDFLY will roll out comic story, animation and video for a world tour, in collaboration with artists and athletes from different countries, which need huge storage for the journey.  

In the MINDFLY eco-system, the onchain voting and rewarding system would be developed in chainlink, to make all election and competition more accessible for the public, and let all people have voice and rights in the important sport events, like FIFA World Cup.  

**Value**

- Brings Filecoin to the hands of artists and athletes
- Reach 10 billion Art and Sport enthusiasts  
- Convenience in applying a huge volume of data through the MINDFLY platform and community 
- Solid Collaboration with significant NFT communities in Australia - OZNFTCLUB and NFTSYD, and frequent reach out with artists and athletes in the world .
- Challenges:
- Demonstrate and educate potential use cases for artists and athletes.
- MINDFLY is bridging the real world and decentralized world, so the open source should be accessible for all users in public.
- A considerable education period would be spent in this innovative mechanism. 

 
**Development Roadmap for Mindfly**

`Milestone 1`   	
Filecoin IPFS gateway integration to Mindfly

- Mindfly Storage infrastructure upgrade to Filecoin IPFS storage solution
1. Priority H: High Level Design ($3,000 USDT)
2. Priority M: CI/CD pipeline upgrade

- Build Mindfly storage solution with filecoin SDK
1. Priority M: Unit Testing for storage solution
2. Priority H: Build assets gateway via Filecoin system  ($6,500 USDT)

- Setup Mindfly Storage gateway pull all image/video assets from filecoin system and push all assets to IPFS storage
1. Priority H: Setup Mindlfy storage with Filecoin ipfs gateway  ($3,500 USDT)
2. Priority M: Integrate filecoin gateway to Mindfly assets function 
3. Priority L: Deployment on dev/uat environment
4. Priority L: Unit Testing pull and push storage gateway

Members:

- Chen Yu - Backend Developer (nodejs, express API)
- Chen Jie - Frontend Developer (JavaScript, React)
- Lin - product manager
- Johnson -  CEO 
- Simo - Designer 

Start date: Dec, 2022
Completed By: Jan, 2023

Budgetary Needs: This milestone will last 3 weeks = $15,000

`Milestone 2`

Mindfly Ticketing system partnership with OZNftClub Australia 

- Build ticketing gateway system
1. Priority H: High Level Design with Mindfly Filecoin IPFS gateway solution   ($5,000 USDT)
2. Priority H: UI/UX for event/travel ticket system  ($10,000 USDT)
3. Priority M: System infrastructure build
4. Priority M: Build frontend base on desgin
5. Priority M: Build API
6. Priority M: Devops build docker container for frontend and backend (scaleable solution)
7. Priority M: CI/CD pipeline setup
8. Priority L: UNIT Testing setup with CI/CD

- Each of ticket sale will mint ticket NFT to client
1.    Priority H: build fiat and crypto payment solution  ($13,000 USDT)
2.    Priority H: when user buy a ticket(event/travel/or something), we will mint this ticket to blockchain via Mindfly Filecoin IPFS gateway solution ($12,000 USDT)
3.    Priority M: Add sponsor to NFT ticket
4.    Priority L: Metamask compatible with NFT ticket

- Storage each of nft ticket via Mindfly Filecoin IPFS gateway
1. 	Priority H: build cross-chain technology, mint those NFT in support blockchain via  Mindfly Filecoin IPFS gateway solution  ($10,000 USDT)
2. 	Priority H: make dashboard portal to control those storage solution. ($8,000 USDT)
3. 	Priority L: monitor those assets usage

- client nft ticket meta data read from Filecoin IPFS gateway
1. 	Priority M: User have memorable meta data can mint to those event ticekt via Mindfly Filecoin IPFS gateway solution
2. 	Priority L: Make those nft ticket can upgrade by join with another event
3. 	Priority L: Add coupon discount/voucher to those meta data for nft ticekt via Filecoin IPFS

- Vendor can validate nft ticket system
1. 	Priority H: Vendor got device/mobile to scan those NFT ticeket ($8,000 USDT)
2. 	Priority H: All scan will encryption during operation	 ($10,000 USDT)

Members:

- Chen Yu - Backend Developer (nodejs, express API)
- Chen Jie - Frontend Developer (JavaScript, React)
- Lin - product manager
- Johnson - CEO 
- Simo - Designer 

Start date: DEC, 2022
Completed By: AUG, 2023

Budgetary Needs: This milestone will last 20 weeks = $100,000

`Milestone 3`

‘ART + Sport’  NFT collection launch

- Mindmap
- Nft mint system for mpassport collection 
- AI protocol to generate derivative art for nft collection
- Use new Mindfly Filecoin IPFS gateway to store nft media
- Allowlist system
- Voting system for election 

Members:

- Chen Yu - Backend Developer (nodejs, express API)
- Chen Jie - Frontend Developer (JavaScript, React)
- Lin - product manager
- Johnson - CEO 
- Simo - Designer 

Start date: AUG, 2023
Completed By: MAR, 2024

Budgetary Needs: This milestone will last 20 weeks = $100,000

`Milestone 4`

MINDFLY mobile application and voting & rewarding system

- Infrastructure in voting and reward model design and implementation
- IOS web2 and web3 trading platform build up
- Androids application for mindfly
- Integrate with nft.storage to upload NFT collection and mint CID address in smart contract
- Implement Filecoin nft.storage superhot gateway build up for reading  nft collection

Members:

- Chen Yu - Backend Developer (nodejs, express API)
- Chen Jie - Frontend Developer (JavaScript, React)
- Lin - product manager
- Johnson - CEO 
- Simo - Designer 

Start date: MAR, 2024
Completed By: OCT, 2024

Budgetary Needs: This milestone will last 20 weeks = $100,000

**Conclusion:** 

Considering the influence in the Art and Sport, both exciting industries in the world, MINDFLY are passionate to collaborate with Filecoin foundation and community, who can provide more value, innovation and technology to artists and athletes. 

MINDfly believe the Filecoin technology can inspire and unleash more creativities on art and sport, simultaneously MINDFLY team is happy to apply more plug-in and one-button start solution on top of Filecoin IPFS, either in upcoming NFT collection or onchain storage solution to artist or athletes.

**Comment by realChainLife** [comment]
Hi @mindflyart thank you for the proposal. Do you have a prototype link you can share with us, or this a new project proposal?

**Comment by mindflyart** [comment]
Dear Sonia John:

How are you? I'm really sorry for my late reply, coz we can't find the
email in spam folder.

Our website is link is www.mindfly.art , and the linktree link is
https://linktr.ee/mindfly.art.

We aim to build up biggest Art+Sport Dao with our community members, and
will apply filecoin in our upcoming IPFS, whatever in our NFT onchain
storage, metaverse or for our artists and athletes in our DAO.

We will roll out MINDFLY World Cup NFT very soon, look forward to your
support.

Pls contact me at ***@***.***, if you have more queries then.

Thanks for your time and support.

Best Regards,

Johnson Young
Co-Founder
MINDFLY.art
MINDFLY.DAO

**Comment by mindflyart** [comment]
HI Sonia John:

Thanks for your inquiry !

We will put it online very soon, would you please contact us at your
convenience?

Thanks a lot,

Johnson Young
Co-founder
MINDFLY.art
MINDFLY.Dao
61-0403648068

**Comment by realChainLife** [comment]
Hi @mindflyart thank you for your patience with our feedback here. We would be interested in funding part of the work outlined here, could you kindly rework the proposal for a phased development approach prioritizing features to include in phase one, for instance M1 and part of M2.

**Comment by mindflyart** [comment]
Dear Sonia John:

Lots of thanks for your reply with support.

We are proceeding with implementation in the project now, so we will get
back to you soonest ( within this week), about the updated proposal.

Wish you have a good day ahead !

Cheers,


Johnson

**Comment by mindflyart** [comment]
Dear Sonia John:

How are you doing? be glad to articulate our plan with the ambition in IPFS
at filecoin.

We have updated the proposal, especially in the milestone 1 and milestone
2, which is addressed with your suggestion. view it on GitHub
<https://github.com/filecoin-project/devgrants/issues/1108#issuecomment-1323772109>
,

Thanks for your patience and technical sponsoring support from Jenks Guo in
Filecoin Australia.

Look forward to your kind attention.

Best Regards,


*Johnson Young *
CEO of
MINDFLY.art
Artsportdao.xyz
Website: https://www.mindfly.art/
Art+Sport DAO Medium: ***@***.***
Mindfly.art  Medium: ***@***.***
Discord: https://discord.com/invite/mRv8bKdcHW
Twitter: https://twitter.com/Mindfly_art

**Comment by mindflyart** [comment]
Dear Sonia John:

How are you? I'm Johnson from MINDFLy.art, I'm wondering that if you have
received my mail ? I just want to make sure that I put right email address
here. Thanks.

All revision is done and awaiting your kind review.

Your attention and reply is highly appreciated.

Cheers,

*Johnson Young *
CEO
MINDFLY.art
Artsportdao.xyz

Tel: 0061-0403648068
Email: ***@***.***
Website: https://www.mindfly.art/
Art+Sport DAO Medium: ***@***.***
Mindfly.art  Medium: ***@***.***
Discord: https://discord.com/invite/mRv8bKdcHW
Twitter: https://twitter.com/Mindfly_art

**Comment by realChainLife** [comment]
Hi @mindflyart thanks for the rework, can you also update the budget request for the scope of work marked as high priority?

**Comment by mindflyart** [comment]
Dear Sonia John:

Be glad to to reach out with you again.

I updated the budget requested for the scope of work marked as high
priority in the Github link below, at milestone 1 and 2.
https://github.com/filecoin-project/devgrants/issues/1108#issuecomment-1330529472
(
original link).

Regarding milestone 1,there are $12000 in High Priority, regarding
Milestone 2, there are $74000 in high priority.

The funding is very important for our upcoming development, and all team
and artists are finger crossed for your support. we will put your logo in
our website to announce it uon your approval.

Please let me know if you have queries on that.

Thanks a lot!

Johnson
Mindfly.art
ArtsportDao.xyz

**Comment by mindflyart** [comment]
Good Morning Sonia :

Have you received our update in Github?  which I sent by mail 3 days ago.

Wish you have an enjoyable Sunday.

Best Regards,

Johnson

**Comment by ErinOCon** [comment]
Hi @mindflyart, thank you for checking in! We will be in touch once the next round of our review is complete.

**Comment by mindflyart** [comment]
Hi Sonia:

Thanks for your kind reply.  Can we have a rough idea when the next round
of review would be completed, coz the Christmas and new year holiday is
approaching, and we need have all onboard before long holiday.

Your understanding is much appreciated.

Best Regards,


Johnson

**Comment by ErinOCon** [comment]
Hi @mindflyart, thank you for your time with our questions. We have decided to not proceed with a grant at this time, but would be interested to hear from you as your project builds community traction and an active user base.

**Comment by mindflyart** [comment]
Hi ErinOCon

Thank you for your reply, ErinOcon !  We are building two communities:
MINDFLY and OZNFTCLUB simultaneously.
 If you like to consider a lower level grant to us?  we are happy to send
you our prototype in Figma, which describes our mission in building a
gateway to Filecoin IPFS, for our artists and athletes community, where all
NFT creators and collectors can easily enjoy the service in Filecoin
eco-system .

Thanks for your consideration.

Cheers,

Johnson
