### ISSUE TITLE
Next Step Microgrant: Teztile

### ISSUE THREAD

**Issue by Udit-Kapoor** [filecoin-project/devgrants#1111]
### 1. What is your project? (max 100 words)
TezTile is a decentralized web app where users can play Teztile with others by putting some TEZ / USDT / CTEZ coins at stake and getting rewards for winning. TezTile also allows users to engrave their teztile game memories on blockchain by minting position-based NFTs.

It solves the big problem of trusting a middleman in every betting scenario by creating a trustless betting system in which you don't need to trust any party. Here, our smart contract plays the role of middle man by collecting staked tokens and distributing them to the winner of the match (code is the law here).

### 2. Project links
  
Link to Github repo: https://github.com/TarunWebdev/teztris
Link to demo, if applicable: https://www.youtube.com/watch?v=QKdMILSf3mo
Link to Website : https://teztris.xyz/
License: MIT License
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
We are using IPFS nodes in our codebase to pin metadata of each TezTile game between 2 players to store the memories and as a Trophy and then mint it as a NFT for the Winner!
We have received a lot of love and support and already have 100 unique games played on our system by the community members and are planning to scale it even further!
Currently we use Piñata as our service due to ease of access but we have reached the free account limit and will be shifting soon!
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Improvements Planned :
● Implement a Available Room System where people can play with Strangers

● Add support for Custom Tokens on UI

● Constantly develop better User Experience

● Get Contracts Audited

● Add a NFT Gallery which shows your Teztile NFTs of all time (exists in wallets already)

● Pin GIFs of the entire game and mint as NFTs 

● Implement No bet Solo Player system to onboard more web2 users

Apart from this we are planning to launch on mainnet in under a month and thus will be using the grant amount to support infrastructure , marketing and salary costs of developers
We are two members working on this project full time even after hackathon completion and will add more improvements from community feedback

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes , happily we love open-sourcing and documentations!
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
https://twitter.com/teztris
https://devfolio.co/projects/teztris-cd4a
  
### Additional questions:
Team Member 1 : 
Name : Udit Kapoor
Email : udit.dude01@gmail.com
Github : Udit-Kapoor
Role : Co-Founder and Smart Contract and Backend Developer

Team Member 2: 
Name : Tarun Sharma
Email : tarun19csu322@ncuindia.edu
Github : TarunWebdev
Role : Co-Founder and Frontend Developer

Learnt about MicroGrant from a Friend who got 2 micro-grants and said our project is also eligible

Teztris was created at Unfold 2022 , Bangalore Hackathon but has been renamed now to TezTile
Link : https://devfolio.co/projects/teztris-cd4a

**Comment by Udit-Kapoor** [comment]
Hey @ErinOCon , are the micro grant reviews paused? Or is there an eta regarding the review work
Warm Regards
Udit Kapoor

**Comment by jenks-guo-filecoin** [comment]
Hey @Udit-Kapoor, micro grant reviews are not paused. Please understand that we have a large backlog and grants team will get back to you as soon as possible. 😃

**Comment by Udit-Kapoor** [comment]
Hey @jenks-guo-filecoin , Gotcha
Looking forward for the review whenever the backlog catches up✌️

**Comment by ErinOCon** [comment]
Hi @Udit-Kapoor, thank you for your patience! We would be interested in exploring this proposal further. Upon the conclusion of this project, will you be building a protocol that can support similar use cases?

**Comment by Udit-Kapoor** [comment]
Hey @ErinOCon , Thanks for taking the time out and reviewing the proposal. The initial aim is to launch the project on mainnet with awesome NFT features like gallery , GIFs of matches as NFTs and explore a marketplace!

Can you explain a bit more by what you mean with a protocol with similar use cases?
Are you asking about an arcade system which has multiple 1V1 games and then the user can select whichever they wish to play and earn? because we have thought about this idea and will require market research and community response of Teztile on mainnet

**Comment by Udit-Kapoor** [comment]
Hey @ErinOCon , development of a protocol for arcades will take a significant time which might be out of scope for the micro-grant

Alternatively we will be treating each individual game as a separate project as we develop them during Hackathons

Do let me know your thoughts

Warm Regards
Udit Kapoor

**Comment by ErinOCon** [comment]
Hi @Udit-Kapoor, thank you for the provided update This microgrant has been approved at the scope provided in your proposal! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by Udit-Kapoor** [comment]
Hey @ErinOCon and team. I know this update is a bit late but we finally launched on 15th June 2023 onainnet with all the enhancements and have a consistent user base and leaderboard.

I thank you for the support you provided with the grant without which it would have been impossible to build.

Check us out at https://teztile.xyz

Warm Regards
Udit Kapoor
