### ISSUE TITLE
Open Grant Proposal: Archival Layer Integration for ntent.art with Filecoin

### ISSUE THREAD

**Issue by drbentonbanner** [filecoin-project/devgrants#1112]
# Open Grant Proposal: `Archival Layer Integration for ntent.art with Filecoin`

**Name of Project: ntent.art Archival Layer Integration**

**Proposal Category:** `app-dev`

**Proposer:** `@drbentonbanner`

**(Optional) Technical Sponsor:** `@tkkonstantin`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** "Yes"

# Project Description
ntent is a collective of artists, technologists, and activists powered by ntent.art [technology] founded to support the culture of art by empowering artists and institutions with advanced smart contract applications and cross-protocol integration use cases for art production. To execute the latter, we craft live art experiences with curated art drops built on top of and powered by decentralized technologies. An example of this would be the live feeding of audience interaction data into a generative art algorithm, in real-time, recorded to the blockchain. [1]

ntent.art is a fine art technology platform that uses blockchain and decentralized technologies to lift up artists, galleries, and institutions through a collection of blockchain solutions. Our current technology stack consists of a cross-chain, multi-artist, multi-project smart contract platform and partnership solution, built on Ethereum, Polygon, and soon-to-be on Tezos, and includes deployment of all assets to the permaweb. [2]

Our goal is to be able to fully store our data openly for everyone to access, research, and build upon in an inclusive and sustainable way. The current version of app.ntent.art supports generated at mint generative art, dynamic art, and mixed media infrastructures. This platform currently holds over 1,400 digital artworks from over 50 artists and currently operates a storage system using Arweave.

Arweave was initially chosen as the archival storage layer because it touted to be a “pay once, store forever” permaweb solution available at the time of creation (Q3 2021), as compared to IPFS pinning services such as Pinata. It was important to choose a solution that seemed the most durable and did not require ongoing payment to ensure data persists over the long term. We want to implement Filecoin now as it has been researched to be the superior solution to fulfill these same needs while being economically sustainable long-term and verifiably accessible over time. 

We believe love > hate. inclusion > exclusion. diversity > boring sameness. We're about sustainability and equal rights, & we’re cool with everyone. Based in Berlin. Creating art worldwide. [3]

## Value
Integrating IPFS and Filecoin with our collective’s technology will provide the primary archival layer for our application’s network. We view this as the first step in a multipart initiative to build on and within the Filecoin ecosystem. Institutional level partners and artists using ntent.art [technology] will have a built-in storage and archival solution as they continue to contribute to the history and validation of decentralized technologies in art. Similarly, the technology developed openly for ntent [collective] live art experiences and the opportunities for artists and institutions to build upon them generates new use cases for the further development of unique cross-protocol partnerships with Filecoin as the foundation and Web3 ecosystem as a whole.  

Built to support the arts community, these partners and experiences provide an opportunity to create an incredible and open web used to record, track, and access the development of the generative and dynamic art movements. We want to enable such collaboration and validation with the Protocol Labs stack.

![ntent FILECOIN project outline_PHASE 1](https://user-images.githubusercontent.com/64104985/198581946-f87f4172-fdc3-432d-a9a3-dacd8160b99b.jpg)

While our application network continues to grow beyond our three platform partnerships NOTAGALLERY [4], MISS EXCEL [5], TREV EL VIZ ARTISTS GROUP [6] and two major live art experience partnerships NOTAGALLERY, FRIENDS OF THE ARTIST W. BRIGHT MOMENTS [7], we will continue to push the boundaries of what blockchain technology and art can do together. With Filecoin as a storage and archival layer, we can expand to implement more cross-protocol partnerships and integrations as we continue to develop new tech implementations.

## Deliverables

We aim to implement an archival layer for our smart contract application network and technology stack. 
 
Integration of IPFS into ntent.art [technology]
Migration of existing ntent [collective] data and systems to IPFS

### Deliverable 1: Integration of IPFS and Filecoin to existing tech stack
Integrate IPFS and Filecoin within our entire ntent.art [technology] ecosystem and tech stack. 

A brief description of the technology stack can be found here: NTENT.ART [TECHNOLOGY] [8]

The integration effort will occur in the following three existing ntent.art applications. 

    **1. POWERED BY NTENT.ART**
    Integration into “powered by ntent.art” will enable our artist, gallery, and institution partners to store the assets and metadata for their NFTs on IPFS.
    
    This area of the codebase will be updated in three areas: 
    1) deploying digital multimedia assets before project launch
    2) deploying previews from algorithmic generative art generated at mint on-demand 
    3) migrating token metadata for all minted NFTs to IPFS post-mint.  
    
    **2. NTENT.MINT**
    Integration into ntent.mint will enable our partners to have assets for the NFTs minted through their project websites and stored on IPFS.
    
    The codebase for ntent.mint will be updated, so generated token metadata files will be migrated to IPFS post-mint. The “powered by ntent.art” section above covers the updates needed to deploy assets before the project launch.
    
    **3. NTENT.IO**
    Integration into ntent.io will allow scaled video projects, i.e., 1,000 - 10,000+ video assets per project, to be stored on IPFS.

This area of the codebase will be updated in a minimum of 2 areas, 1) deploying finalized video assets and 2) deploying auto-captured video preview images. If the project is categorized as an NFT project, related token metadata will be generated and deployed to IPFS.

### Deliverable 2: Migration of existing data to IPFS
Migrate existing ntent [collective] data and systems to IPFS. This includes all data for each existing NFT, publishing the content assets and token metadata to IPFS / Filecoin for all Ethereum and Polygon NFTs. 

## Development Roadmap

We plan to execute across 3 months from Deliverable 1 to Deliverable 3. We expect the following outline in billable hours and human resources:

### Milestone 1: Integration of IPFS and Filecoin
30 days (4 weeks) | one part-time project manager, one part-time node.js developer, one part-time Quality Assurance engineer | complete by January 2023

RESULT: Integrate IPFS and Filecoin within our entire ntent.art [technology] ecosystem and tech stack, so the deployment of all new ntent.art assets are published to IPFS.

    - Team onboarding (4 Proj. mgr hours, 4 dev hours, 4 QA hours) (1.5 days)
    - Dev onboarding deep dive (16 dev hours) (2 days)
    - Create a project plan with the developer/QA engineer (4 Proj. mgr hours / 4 dev hours / 4 QA hours) (1.5 days) 
    - Update codebase (60 dev hours) (1 week 0.5 days) 
        - powered by ntent.art
        - ntent.mint
        - ntent.io
    - Create unit tests alongside development ( 20 dev hours ) (2.5 days)
    - Deploy to staging environments ( 4 dev hours ) (1 day)
    - Quality Assurance (24 QA hours ) (3 days)
    - Upon passed QA, deploy to production ( 16 dev hours ) (2 day)
    - Confirm successful production deployment ( 8 QA hours ) (1 day)
    - Project Manager will hold stand up meetings and communicate with ntent team ( 12 Proj. mgr hours ) (1.5 days)
    - Buffer on bug fixing and QA (16 dev hours / 8 QA hours / 4 PM hours) (3.5 days)

140 Developer Hours x $120 / hr = $16,800
24 Project Manager Hours x $70 / hr = $1,680
48 Quality Assurance Hours x $90 / hr = $4,320
Total = $22,080

### Milestone 2: Migration of existing data to IPFS
16 days | one part-time project manager, one part-time node.js developer, one part-time Quality Assurance engineer, one part-time content writer | complete by February 2023

RESULT:  Migration of all existing ntent [collective] data and systems to IPFS. For each existing NFT, the content assets and token metadata will be published to IPFS / Filecoin, including assets for all Ethereum and Polygon NFTs. 

    - Create a project plan with the developer / QA  (4 Proj. mgr hours / 4 dev hours / 4 QA hours) (1.5 days)
    - Develop code to migrate assets (24 dev hours) (3 days)
    - Download assets from Arweave / cloud-hosting systems agnostically, and publish to IPFS 
    - Upon publishing to IPFS, the token-metadata will be updated with new asset locations on IPFS. (8 dev hours)  (1 day)
    - Upon completion of the migration of all content assets we will deploy the content assets to IPFS, update the token-metadata with new IPFS content urls, publish metadata to IPFS, and then update the url to the metadata folder in the smart contract (16 dev hours) (2 days)
    - Create unit tests alongside development (12 dev hours) (1.5 days)
    - Deploy to staging environments and begin QA (8 dev hours) (1 day)
    - Quality Assurance( 12 QA hours ) (1.5 days)
    - Upon passed QA, production assets will be migrated. (8 dev hours) (1 day)
    - Final Quality Assurance( 4 QA hours ) (0.5 day)
    - Buffer on bug fixing and QA (16 dev hours / 8 QA hours / 4 PM hours) (3.5 days)
    - Project Manager will hold stand-up meetings and communicate with ntent team ( 6 proj. mgr hours ) (0.75 day)
    - Integration Article ( 4 Planning hours, 8 Development hours, 4 QA hours) (2 days)
    - Press Release ( 2 Planning hours, 4 Development hours, 2 QA hours) (1 days)

108 Developer Hours x $120 / hr = $11,520
8 Project Manager Hours x $70 / hr = $560
28 Quality Assurance Hours x $90 / hr = $2,520
24 Content Writing Hours x $30 / hr = $720
Total = $15,320

### Milestone 3: Partnership & Integration Generative Art Exhibition
60 days part-time | one part-time creative director, one part-time content producer, one public relation agency, one part-time operation manager | complete from Q4 2022 - Q1 2023

RESULT: Lead our technology integration directly into a marketing and publicity plan featuring the implementation, partnership, and execution of the storage and archival layer, culminating in an exhibition featuring a collection of generative art immutably stored on IPFS in partnership with Tezos Berlin. This exhibition will highlight Filecoin, IPFS, and ntent’s partnership, the technology, its value, and Filecoin’s commitment to preserving art history and supporting the culture of art. 

Operations Manager (ops), Creative Director (cd), Content Producer (cp), Billable Expenses (be) 

    - Venue + Event Management ( $1,000 ) (be)
    - Production Equipment ( $1,500 ) (be)
    - Production Installation ( $500) (be)
    - Planning (PL) + Development (D) will be needed for each of the following executions. 
    - Exhibition Curation (14 PL +  D Hours) (cd)
    - Graphic Content Design (6 cd hours  + 16 cp hours) (cd + cp)
    - Social Media Planning  (14 PL +  D Hours) (ops)
    - Public Relations 8 week campaign ($7,500) (external contractor from previous projects, like [ARTPRESS](https://www.artpress-uteweingarten.de/en/home), [Artist Network](https://www.artistnetwork.de/), [favourized](https://www.favourized.com/), [Send/Recieve](https://www.sendreceive.eu/), or [Bold Berlin](https://www.boldberlin.com/)): 
        - Agenda setting, Public relations
        - Press events
        - Influencer & Press Trips
        - Media cooperations 
        - Media planning
        - Event Poster Campaign ($1,800)

Operations Manager (ops) Hours x $35 / hr = $490
Creative Director (cd) Hours x $70 / hr = $1400
Content Producer (cp) Hours x $25 / hr = $400
Billable Expenses (be) Hours x $35 / hr = $12,300
Total = $14,590

## Total Budget Requested

We request a total budget of $52,710 for this project based on the following costs:

  - Software Development and Integration by NTENT Team
      - $38,120
  - Exhibition and publications/promo campaign by NTENT Team
      - $14,590

## Maintenance and Upgrade Plans

For maintenance and upgrade of the codebase explicitly described in this grant proposal. We want to request an additional $5000 to ensure proper support through 2024.

The integration laid out in this proposal is the first step of a larger roadmap in continuing to create fine art technology tools, including an open and multi-use digital fine art archival system for artists, galleries, and institutions, which paves the way for more applications requiring the durable storage of fine art assets/content to create social value for the community at large. We would love to continue collaborating with Protocol Labs and continue verifying the value of decentralized technologies for artists and Web3 space.

# Team

## Team Members

River Davis known as Dr. Benton Banner 
Sean Ryan O’Connor known as jiwa
Coco Shin known as bluem0xn
Tkachuk Konstantin

## Team Member LinkedIn Profiles

River Davis - https://www.linkedin.com/in/riverdavis/
Sean Ryan O’Connor - NA
Coco Shin - https://www.linkedin.com/in/cocoshin/
Konstantin Tkachuk - https://www.linkedin.com/in/tkachukk/

## Team Website

Official Website: https://www.ntent.art/ 
Web3 Platform: https://app.ntent.art/
Video Scaling Solution: https://ntent.io/ 

## Relevant Experience

**Sean Ryan O’Connor**
Senior-level Full-stack, smart contract/dapp developer
Over 15 years of experience building technology for startups and Fortune 500 companies, including Sony Pictures and Interpublic Group. 

        https://jiwa.art/ 
        [@dotjiwa](https://twitter.com/dotjiwa)
        jiwa.eth / jiwa.tez
        jiwa@ntent.art

jiwa is a generative artist, dev, activist, and founder of ntent.art. From writing code for Hollywood to building his own generative art platform where ntent.art releases crypto art at the edge; jiwa is
creating new ways to display, interact, and think about generative art. 

        Jiwa recently spoke at NFTBerlin:
        https://ntent.art/talks/jiwa/nftberlin 

**River Davis**
Senior-level International Creative Director and Operations Specialist/Mgr
Over nine years of experience in international creative production for, NGOs, brands and personalities, including Center for Dignity, Donate Attention, Blesswell, and Dj Kahlid.

        [@drbentonbanner](https://twitter.com/drbentonbanner)
        [drbentonbanner.eth](https://www.ntent.art/drbentonbanner)
        drbanner@ntent.art

Dr. Benton Banner is a pseudo-anonymous digital fine artist rapidly rising to the spotlight within contemporary art culture. He is the founder of ntent and works as a public voice for sustainability, inclusion, decentralization, and the expansion of smart contract-based art technologies. Banner’s work features meditative 2d expressionist and 3d surrealist visualizations that use smart contracts to create reactive and participatory art experiences.

**Coco Shin**
Operations Manager + Marketing and Content Specialist 
5+ years of experience managing projects and content development.
Over 3 million views across social platforms. 

        [@bluem0xn](https://twitter.com/bluem0xn)
        Bluem0xn.eth
        [ntent.art/redpaper](https://www.ntent.art/articles/onedropnfts)

Blue Moon is a founding partner of ntent.art and creator of #OneDropNFTs, a movement to destigmatize menstruation through discussion and art. She champions inclusion and sustainability in both Web3 and existing social platforms. Her multimedia art centers on themes of self-care, sustainability, personal awareness, and discipline. She is also an environmental activist passionate about bridging the gap between blockchain and the environment.

**Tkachuk Konstantin**
4+ years of entrepreneurial experience in European tech startups
ex. Protocol Labs - Startup Operator, Ecosystem Collabs Team

        @tkachuk_science

Schwarzman Scholar '23, Web3 enthusiast and artist. A young leader and entrepreneur advising multiple cutting-edge tech projects in the blockchain space. He is a civil engineer by training and has gone through various entrepreneurial experiences in the European landscape. Won the SpaceX Hyperloop competition and was awarded the Schwarzman Scholarship.

## Team code repositories

We will set one up once we start this project so that our code snippets can be viewed openly. 

# Additional Information
We learned of the Open Grants Program during NFTBerlin Conference through Protocol Labs. 
The best email address for discussing the grant agreement and general next steps = drbanner@ntent.art

### References
[1] https://www.ntent.art/articles/momentafter
[2] https://www.ntent.art/
[3] [https://www.ntent.art/collective](https://www.ntent.art/articles/momentafter)
[4] https://notagallery.de/   
[5] https://www.miss-excel.com/ 
[6] https://www.trevelviz.com/  
[7] https://www.ntent.art/fota 
[8] https://www.ntent.art/tech

### Future Road Map 
We aim to form a strong, mutually beneficial long-term partnership between Filecoin and ntent. Below we have included a simple outline of the additional application layers we are looking to build with Filecion after phase 1 is completed. The outline includes a visual reference. No additional context has been included as we first aim to complete Phase 1 before we submit our additional future documentation.

![ntent FILECOIN project outline_PHASES 1-5](https://user-images.githubusercontent.com/64104985/198584829-dd226b6c-5b91-4525-9156-ca357628c6ac.jpg)

**Comment by drbentonbanner** [comment]
Hey, @realChainLife, we submitted this during IPFS Lab in Lisbon (which was awesome btw), so we are awaiting feedback but also aware of everything going on on your side. Thank you!

**Comment by realChainLife** [comment]
Hi @drbentonbanner thanks for your proposal, and your patience with our review. We'd like to fund the work outlined in this scope. Look out for an email with detailed next steps.

**Comment by drbentonbanner** [comment]
@realChainLife great to hear! We are ready to go. I will keep an eye out for the email and the next steps.
