### ISSUE TITLE
Next Step Microgrant: <IncollabSpace>

### ISSUE THREAD

**Issue by july321** [filecoin-project/devgrants#1113]
### 1. What is your project? (max 100 words)

Incollabspace is a decentralized project management platform powered by IPFS. It allows teams of creators, developers and managers to manage their projects, communicate in a simple and minimalistic way. 

Incollabspace is a unique idea in the collaboration tooling sphere, because it provides users not just a way to communicate and work with their teammates, but also the opportunity to exchange  ideas with other users and take part on building other ideas and projects while receiving rewards along the way.

### 2. Project links
  
Website Link : https://incollabspace.com/
Demo video : https://www.youtube.com/watch?v=M5noXF3cM-M
Github repo: https://github.com/july321/Incollabspace

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

At the moment the IPFS technology is used for storing and exchanging photos and files with different formats. In the future IPFS will be used for storing the records of the video meetings so users can easily review the past meetings or watch the ones they didn’t attend.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Using this grant, we will: 
1.	Improve the UI/UX of the platform. 
2.	Finish all the core functionalities such as videocalls, task manager, statistics and online events.
3.	Improve our backend.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

  
### Additional questions:

* For each team member(s), please list name, email, Github account, and role in the project.
 **Yuliya Ustimenko**
    - Full stack web developer and UX/UI Designer
    - Github : https://github.com/july321
    - email : yuliya.ustimenko02@gmail.com
* How did you learn about our microgrant program?
    - From Filecoin discord channel
* If your project was created as part of an event or hackathon: What was the name of the event? 
  - **Moralis x Filecoin Hackathon 2022**

**Comment by ErinOCon** [comment]
Hi @july321, thank you for your proposal and patience with our review. We will not be proceeding with a grant at this time. Thank you again for your interest!

**Comment by july321** [comment]
Hi! Thank you for your review. Can I, please, get a feedback about my project, like what was not really good in it and what can be improved? And thank you.
