### ISSUE TITLE
Next Step Microgrant: Navigational Warnings IPFS

### ISSUE THREAD

**Issue by buhbeck** [filecoin-project/devgrants#1115]
### 1. What is your project? (max 100 words)
This project retrieves and combines data across mulitple api's that cover radio navigational warnings in the Baltic Sea region. It then plots all current warnings on a map.  I think this information could be very valuable to organizations such as government agencies where they have this information in one place.

### 2. Project links
  
Link to Github repo: https://github.com/buhbeck/RadioNavWarnings-IPFS
Link to demo or website, if applicable: https://youtu.be/MKyDGmn_1vc
License: MIT
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
IPFS and w3storage are used to write daily navigational warnings to a file which are retrieved from multiple API sources and then stored on the network.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
I want to incorporate more regions around the world, such as The Mediterranean, Persian Gulf and Oman Gulf. I also want to create a system where these warnings can be sent to a person interested in the data via email or slack. Adding to that as well I want to use IPFS and w3storage as my backend for a database where people can view all past and current navigational warnings.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes I do.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes it does.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Rebecca Dineen - rebeccadineen1@gmail.com, github username - buhbeck, developer
* How did you learn about our microgrant program?
* I heard from a friend
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @buhbeck, thank you for your proposal! For next steps, we recommend taking this project to a [hackathon](hackathons.filecoin.io). Please feel welcome to reapply for a microgrant as your work progresses. Happy building!

**Comment by buhbeck** [comment]
No problem @ErinOCon thanks for the update! I will take some time to work on it further
