### ISSUE TITLE
Next Step Microgrant: Vigilance DAO

### ISSUE THREAD

**Issue by VenkatTeja** [filecoin-project/devgrants#1117]
### 1. What is your project? (max 100 words)

A lot of non-tech savvy people get scammed through phishing websites, wallet scams, etc. To begin with, idea is to create a protocol that crowdsources and maintains active scammers information on the chain so that other apps/dapps like browsers, DEXs, CEXs, wallets, etc. can use this information to warn their users if they try interaction with scammers. As a start, a simple chrome extension that warns people when they land at unknown websites is built. The protocol uses IPFS to maintain historical snapshot of websites to keep track of historical legitimacy of any website on chain.  

More details on how the protocol works is here: [link](https://www.notion.so/56c27e27bebd4f1999ae90412934c93e)

### 2. Project links

Link to Github repo: https://github.com/VenkatTeja/VigilanceDAO

Link to demo or website, if applicable: [link](https://drive.google.com/file/d/14Fdj_5lF1XtehwsvFgQ6NHrWTum-zHg0/view?usp=sharing)

License: GPL

### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

The protocol relies on certain evidence submitted by the report to help the validator verify if a particular domain is being used for legitimate purposes.  These evidence act as a historical proof which anyone can use in future to verify and ensure the protocol has been working as intended. Further, anyone can report the authenticity of validators based on the evidence submitted. We use IPFS to store the evidence.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Since an MVP is ready now, we have to work further to implement certain edge case scenarios into the protocol to ensure its safety. This will involve understanding and planning how the protocol can be attacked and how we can design to prevent the same. 

**Possible attack types:**

1. **Phishing domains (e.g. uniswap attack in July 2022) - MVP ready ✅**
2. scam wallets (e.g. Tron multi sig wallet scam)
3. Attacker script injection in legitimate websites (e.g. Badger DAO, curve fi attack)

The grant will help us build solutions for rest of these attack types. We will hire a team of devs and a content manager to ensure we keep building the community as well while we build and fine tune the product, taking active feedback from the community along the process.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes 

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions

[https://ethglobal.com/showcase/vigilance-dao-043jh](https://ethglobal.com/showcase/vigilance-dao-043jh)  

### Additional questions:

- For each team member(s), please list name, email, Github account, and role in the project.
    
    1) Venkat Kunisetty - [email](mailto:teja.kunisetty@gmail.com) - [github](https://github.com/VenkatTeja/) - **Product/Developer**
    
    2) Dinesh Aitham - [email](mailto:dineshaitham2@gmail.com) - [github](https://github.com/dinesh11515) - **Developer**
    
    3) Ishan, Raj Karia & Nitanshu from [truts.xyz](http://truts.xyz/) - **Advisory & Community building**
    

- How did you learn about our microgrant program?
    
    From Raj Karia, Truts
    
- If your project was created as part of an event or hackathon:
    - What was the name of the event? **ETHGlobal HackFS**
    - Please link to your hackathon submission: [here](https://ethglobal.com/showcase/vigilance-dao-043jh)

**Comment by VenkatTeja** [comment]
Hey @ErinOCon ser, 
Hope you will get a chance to look at this project sometime. If needed, we can setup a demo call as well.

**Comment by ErinOCon** [comment]
Hi @VenkatTeja, thank you for your proposal. Is your repo open to the public? The provided link currently isn't working.

**Comment by VenkatTeja** [comment]
Hey, @ErinOCon, its public now.

**Comment by ErinOCon** [comment]
HI @VenkatTeja, this microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
