### ISSUE TITLE
KwikTrust

### ISSUE THREAD

**Issue by KwikTrust** [filecoin-project/devgrants#1118]
Q.1 What is your project’s name? 
KwikTrust

 Q.2 What is your email address?
yasir@kwiktrust.com

Q.3 Your Name?
Yasir Qayam

Q.4 Your Company’s Name?
Kwikt Limited

Q.5 Your website?
www.kwiktrust.com

Q.6 Were you referred to our Grant Program?
 - Online
 - 
Q.7 Project Description (One Sentence)?
Ans: KwikTrust is a digital signature and e-validation solution that  combines digital signatures with KYC ensuring the signatures are tied to verified identity. Users can convert digital assets to transferable assets through SNFT.

Q.8  What Category are you applying Under?
Startup Grant - For the development of decentralized applications which will create a network effect, drive user adoption, and promote scalability.

Q.9 Project Focus Area?
Ans:  Corporate Metaverse, NFT, Identity, Other (Digital Signatures and E-validation)

Q.10 Grant Proposal (250 words)?
KiwikTrust utilises blockchain technology (Enterprise - Hyperledger Fabric 2.0 and Public -  NEAR protocol)  to make your digital signing, e-validation, and NFTs easier to execute and more secure.
Currently, KwikTrust offers its users the following services:
Digital Signature
E-validation
KYC
Contact Management
NFT and SuperNFT
KwikTrust Arena
KwikTrust is a web3.0 SaaS offering, which aims to bridge the gap between Web2.0 and Web3.0 and in order to do so we are constantly building and evolving.
With the next iteration of KwikTrust, we would like to offer our users a decentralised, secure and cheaper storage.
As the awareness of IPFS and benefits of decentralisation grows, the adoption rate of the offering will grow. There needs to be a clear educational piece that needs to be undertaken to grow the ecosystem and adoption of the technology.
KwikTrust are also working on decentralised Identity.
KwikTrust is also building a corporate metaverse which will allow brands to hold events in the metaverse, allow its participants to communicate and socialise with each other, stage to hold events, round table and product launch, and at the same time sell digital assets as SuperNFT within the metaverse.
KwikTrust would like to implement decentralised storage within KwikTrust Arena also to bring true decentralisation.

Q.11 Team?(upto 6 core members)  Their titles, roles and linkedIn profile links.  
Simon Read, CEO - https://www.linkedin.com/in/simonread/
Yasir Qayam, COO - https://www.linkedin.com/in/yasirqayam/
Muhammad Sabir, CTO - linkedin.com/in/muhammad-sabir-707b5760
Hassam Khawaja, CFO - https://www.linkedin.com/in/hassam-aziz-khawaja-831167b7/
Christina Ashley, CMO - [linkedin.com/in/mchristina-ashley](https://www.linkedin.com/in/mchristina-ashley)
Nick Spiller, CPO - [linkedin.com/in/nick-spiller-6610a844](https://www.linkedin.com/in/nick-spiller-6610a844)

Q.12 What stage is your project in?
Working Product

Q.13  What is the value proposition that your project is bringing 
Re-inventing web2 tech like Dropbox and Docusign using Web3 tech - making it cheaper and giving users full control. 
KwikTrust is digital signature and data validation platform which, with the help of decentralised storage will offer users an alternative to dropbox and docusign. The users will have full control of their data using KwikTrust interface. The vision is to onboard users and allow them to use blockchain by lowering the barrier to entry. 
KwikTrust acknowledges that the bulk of the users sit outside of the crypto communities, KwikTrust main aim is to convert these users, onboard them as blockchain users by providing them with tools to convert IP, content, copyright, data in general to SuperNFT by reducing the learning curve. 
The aim is to bring 1000 users to the ecosystem this year followed by 100k users by the end of 2023. 

Q.14 What is your project looking to solve? This question is required.*
Making e-validation and digital signature cheaper and more accessible to wider public using IBMs enterprise solution. We have also incorporated KYC within digital signatures to improve compliance. 

Q.15  Describe the strategy your team will execute in order to address this problem and the deliverables required for success.
Ans: The KwikTrust solution is faster, simpler, more secure and less expensive than competitors. It features triple lock security- each file is locked onto the blockchain with three separate hashes. Users have to undertake KYC checks before validating any documents and files. Intellectual property and other assets can be represented digitally - including property deeds, company shares, asset ownership, and validated identities - which can be minted into a NFT (non-fungible token) as a permanent and transferable record of ownership through digital signatures with complete audit trail and stored in decentralised storage. We are looking to integrate IPFS with the help of filecoin that will enhance the dynamics of NFTs and SuperNFTs and will increase the overall efficiency of the process.

Q.16  What is the market demand or need for your project / initiative? 
Paid Media: Includes Paid social campaigns across Twitter, LinkedIn Sponsored/ Boosted Content, Facebook + Instagram, Google AdWords, and Retargeting
Organic Content Marketing Campaigns
PR announcing integration / link with filecoin
Twitter Spaces + LinkedIn Lives to discuss the problems solved and addressed
Employee and Customer advocacy program
Earned Media

Q.17 What impact do you expect your project will have on sustainability, democratization, or the planet/society in another way?
The project provides a positive impact on societies as it enables a number low-cost, secure and fast delivery initiatives to the target groups including extending financial services to underserved businesses in Asia and Africa (an initiative supported by the UK Financial Conduct Authority Innovation Pathways Program) and  the provision of lower-cost  protection for content creators and originators of intellectual property so they can protect and monetise their assets.

Q.18 What makes you different from other similar projects?
Ans: KwikTrust incorporates an e-validation platform that provides provenance and legal protection. The platform enables self- certified and third-party validation of files, with the results stored securely on a blockchain, creating an irrefutable record of activity. The KwikTrust solution is faster, simpler, more secure and less expensive than competitors. It features triple lock security- each file is locked onto the blockchain. Users can record and validate intellectual property origination, contracts, accounts, invoices, references, qualifications, identities, video and audio files, and undertake know-your-client checks. Intellectual property and other assets can be represented digitally - including property deeds, company shares, asset ownership, and validated identities - which can be minted into a NFT (non-fungible token) as a permanent and transferable record of ownership with complete audit trail .Our competition such as Docusign and HelloSign in digital signatures and Google docs in storage have security risks as they operate on cloud and have centralized storage, hence, a centralized point of failure while not immune to hacking and does not offer audit trail.

Q.19 What is your fit in the current blockchain space.
 KwikTrust is a digital signature platform that allows users to e-validate and authenticate data. The data can range from contracts to intellectual property to music and art. KwikTrust allows users to digitally sign and authenticate data on-chain. 
The users will have the option to store their data on decentralised platforms such as filecoin. Currently, we provide data storage with AWS which is centralised and secure, however, as we move towards more decentralisation, the FileCoin platform will allow users to own and manage their own data. 
KwikTrust will build tools on FileCoin that will be compatible with IBM’s permissioned blockchain, Hyperledger Fabric for enterprise solution and with Near Protocol on public blockchain. 
The grants will allow KwikTrust to build tools for both public and private ledgers. 

Q.20 What is your requested grant amount? (in $USD please)
Ans: Grant size - $200,000. 

Q.21 How much time would you need to complete the deliverables tied to your requested grant?This question is required. *
Ans: 6-8 months

Q.22 If any, what other funding have you received for this project/initiative over the past 12-18 months and from who?
Ans: We have raised funding through token sale (Utility Token) and we have also secured funding from NEAR. This funding has been employed mainly in product development and operational expenses i.e (Marketing, Legal, Labor)

Q.23 Please list all deliverables which your project will provide in bullet points. Please be as precise as possible. 
Scope and Ideation - 3 weeks
R&D - 6 weeks
Front End Design - 4 weeks
Assessment of current smart contracts and Smart Contract Development - 8 weeks
Incorporation of the above - 3 weeks
Testing and bugs - 3 weeks
APIs - 3 weeks
Marketing - 3 weeks
Roll out - 2 weeks

Q.24 Please describe your approach towards delivery, from ideation to implementation and testing, including how that ties with your team size and distribution.
Scope and Ideation - 3 weeks
R&D - 6 weeks
Front End Design - 4 weeks
Smart Contract Development - 8 weeks
Incorporation of the above - 3 weeks
Testing and bugs - 3 weeks
APIs - 3 weeks
Marketing - 3 weeks
Roll out - 2 weeks
The team allocation would be 3 SC devs, one front end designer, 2 front end developers, 2 QAs, internal team for testing and bugs, mainnet launch and go-to-market. 

Q.25 How dependent do you feel you would be on the FileCoin team for support and collaboration when measured from a time/month perspective?
Ans : We will need 4 hours per month for troubleshooting and guidance on implementation of the FileCoin within the KwikTrust product. 

Q.26 Please upload documentation related to:
1. Technical detail (as applicable)

KwikTrust is looking to bring decentralised storage to WEB” space, building a bridge for consumers who are comfortable with WEB2. This will allow more users to make the jump into WEB3 space. With FileCoin, we will be able to further enhance SuperNFT, data validation and authentication with decentralised storage offering, giving the users full control of their data and manage the state. 

Q.27 Roadmap and milestones related to the grant request

Scope and Ideation - 3 weeks - 15K
R&D - 6 weeks - 30k
Front End Design - 4 weeks - 20k
Smart Contract Development - 8 weeks - 50k
Incorporation of the above within the existing platform  - 3 weeks - 20k
Testing and bugs - 3 weeks - 15k
APIs - 3 weeks - 20k
Marketing - 3 weeks - 20k
Roll out - 2 weeks - 10k
Total cost - 200k

Q.28  Please describe your initial go-to-market strategy, assuming a successful grant completion. 
A large part of our strategy focuses on creating brand awareness, recognition, and user adoption. This is achieved by building and continuing to use a data-backed marketing system that can adapt to the ever-changing trends of the marketplace.
Key elements of this strategy include:
Messaging - Placing not only what we do, but why we do it at the forefront of our messaging will ultimately help users to buy into the brand and platform as an ecosystem rather than simply a tool. Focusing on the ability to reduce unnecessary costs, save time, and build security is key to this message.
Targeting - The use case applications for KwikTrust stretch across most industries and market segments. In order to narrow our focus and hone targeted campaigns, our initial target markets have been niched down with a variety of use cases mapped out. A targeted approach will allow us to craft truly impactful messaging and
campaigns that can easily adapt and shift to additional key industries. We will expand targeting using our initial sectors as a campaign model.
Demand Generation - Through a series of activities and campaigns, we aim to build a sustainable marketing funnel that will consistently pull in qualified leads.
Essential areas of development will include- Content marketing, specifically the creation of educational and thought leadership elements. Establishing an engaged and active community across multiple platforms. Trust establishment through case studies, events, and authentic messaging.
Implementation of paid and earned media campaigns.
User Advocacy - Building out a user advocacy program. KwikTrust benefits from a natural referral and customer advocacy environment that is enabled by users' third party validation of documents. An advocacy program will help to expand this natural expansion of users.
Strategic Partnerships and Direct Distribution - Tapping into existing network contacts to distribute messaging, materials and establish meaningful partnerships and distribution ecosystems.
Industry body collaborations and third-party integrations: Tapping into external marketing systems to build trust, recognition, and reach.
These activities will be implemented in a phased approach that is guided by the attainment of key performance indicators and selective data points.
A portion of our strategy will also be reserved for marketing activities that allow for an additional level of creativity and outside-the-box thinking, (for example live broadcasts, roundtable discussions, community engagement events, podcasts), in order to build a brand that is recognizable as an industry leader in every sense of the word.
Our Strategy is set to be adaptable, data-driven, and innovative - leading KwikTrust to greater brand recognition and user demand

**Comment by ErinOCon** [comment]
Hi @KwikTrust, this proposal falls outside the scope of the [microgrant program](https://github.com/filecoin-project/devgrants/blob/master/microgrants/microgrants.md). Check out our grant opportunities [here](https://github.com/filecoin-project/devgrants) and proceed with our [provided templates](https://github.com/filecoin-project/devgrants/issues/new/choose), as applicable.

**Comment by KwikTrust** [comment]
Thanks for the note. What's best grant option for KwikTrust?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ErinOCon** [comment]
Hi @KwikTrust, my apologies for the delay! It looks like I missed this message before. Updates on granting focus areas will be posted throughout the year and can be found [here](https://github.com/filecoin-project/devgrants). Stay tuned!
