### ISSUE TITLE
Next Step Microgrant: SolSnipp

### ISSUE THREAD

**Issue by lakshh07** [filecoin-project/devgrants#1119]
### 1. What is your project? (max 100 words)

Web3-Native solidity snippets for the world's best communities.

SolSnipp is a decentralized vscode extension, a new way of community-driven snippets for solidity. Anyone can request the smart contract snippet to be added to the extension.

There are many categories like Proxy, Interface, Boilerplate, NFTs, Token and many more.
All the data are stored on Polygon through IPFS and fetched using The Graph, a decentralized way
SolSnipp also helps the new members interact with web3, learning how to build smart contracts

[Smart Contract Address](https://mumbai.polygonscan.com/address/0x39C66C06C58bfD0FD4AECC1cD58943e33F5224D6)
[The Graph Protocol](https://thegraph.com/hosted-service/subgraph/lakshh07/solsnipp)
[Vscode Marketplace](https://marketplace.visualstudio.com/items?itemName=lakshay-maini.web3-solsnipp)

#### How it's Made
Decentralised Services (Ether.js and communication with Smart Contract).

All smart contracts are deployed on Polygon Mumbai ( Solsnipp.sol)

This project uses,

✨ Next.js to design the frontend
✨ IPFS for storing snippets metadata through IPFS-HTTP-Client
✨ The Graph for fetching smart contract
✨ Vscode API for vscode-extension

### 2. Project links
  
Link to Github repo: https://github.com/lakshh07/solsnipp
Link to demo or website, if applicable: https://solsnipp.vercel.app/
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
All the snippets metadata are stored on IPFS using ipfs-http-client.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

First, I want to improve UI, and little bugs, and easy flow for consumers. Redesign the structure of the whole process of application and wanted to add some more features like

- Wanted to add more smart contracts.
- Wanted to hire a smart contract developer for smart contract development.
- Discussion section where all the members can interact with each other.
- Comments section on snippet request.
- Gasless transactions
- wanted to make smart contracts upgradable using proxy.

Deploy it to mainnet and more things.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes, I have submitted for IPFS prizes.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  Name: [Lakshay Maini](https://www.lakshaymaini.com/)
  Email: [lakshk886@gmail.com](mailto:lakshk886@gmail.com)
  Github: https://github.com/lakshh07
  Role: Full Stack Blockchain Developer
* How did you learn about our microgrant program? From Email
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) ETHOnline 2022
  * Please link to your hackathon submission: https://ethglobal.com/showcase/solsnipp-ijii3

**Comment by ErinOCon** [comment]
Hi @lakshh07, thank you for your proposal! Does this work build on any of your previous projects supported through the microgrant program? If so, please provide a brief explanation.

**Comment by ErinOCon** [comment]
Hi @lakshh07, this issue has been closed. Please be in touch with any questions.
