### ISSUE TITLE
Web3Box Open Grant Application

### ISSUE THREAD

**Issue by web3andrew** [filecoin-project/devgrants#1123]
# Open Grant Proposal: `Web3Box`

**Name of Project:** Web3Box

**Proposal Category:** `app-dev`

**Proposer:** `web3andrew`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:**  "Yes" 

# Project Description

Web3Box is committed to creating a Web3 UGA platform with a secure environment worldwide, which is supported by the IPFS  storage system.

- In order to prevent inevitable frauds, we propose a privacy-safe sandbox concept, Web3Box, so that all the information of Filecoin ecosystem users is controlled in their local trusted environment and backed up in  IPFS storage system

- Web3Box will become the Web3 portal for Filecoin ecosystem users, giving them one-stop access to all Web3 applications. Filecoin ecosystem users can manage their multi-chain assets and track asset changes, ensuring asset security, including Filecoin Network, Ethereum, etc.

- In response to the frequent Web3 asset security incidents, Filecoin ecosystem users can track the risks of Web3 projects through the Web3Box, so as to choose Web3 portfolio safely.

## Web3Box Architecture
<img width="691" alt="image" src="https://user-images.githubusercontent.com/117150831/200275332-1644e126-2e97-4903-9d11-58a91f9f0c0e.png">

## Web3Box Preview
<img width="781" alt="image" src="https://user-images.githubusercontent.com/117150831/200275211-cad5ee13-c89c-469b-aa42-a5dc79415bf1.png">

## Value

1. Web3Box allows Filecoin ecosystem users to access Filecoin eco wallet, Defi, Swap, and browse Web3 websites in the privacy-safe sandbox. The data generated in transactions and browsing is securely stored on the Filecoin ecosystem users’ personal computers and fully backed up in the IPFS storage system, which could effectively isolate hackers & viruses and avoid system horse calls & program supervision.

2.  Web3Box provides Filecoin users with risk assessment of web3 projects, so that Filecoin users can timely and accurately understand the risks of different web3 projects; select the web3 projects with low risks for users to avoid those with high risks when making investment decisions.

3. Web3Box presents the visual Web3 news for Filecoin users, including value-added content services and interactive narrative subjects, bringing better reading experience and more accurate content timeliness. 
Meanwhile, the unique aggregation function of Web3Box will be improved by Filecoin users in a decentralized manner, including Web3 industry sites, resources and tools. Finally, it will let Filecoin users liberate the conventional webpage favorites in Web2, achieving the one-stop access to all Web3 applications.

## Deliverables

Web3Box Client in Mac and Win version

Supported Network: Filecoin Network

## Development Roadmap

**Milestone 1 - Dashboard / Filecoin Eco Wallet**

- Estimated duration: 6 weeks
- FTE: 2
- Costs: 10,000 USD

| Number | Deliverable | Specification |
| -----: | ----------- | ------------- |
| **0a.** | License |  MIT  |
| **0b.** | Documentation | We will provide both **inline documentation** of the code and a basic **tutorial** that explains how a user can install and operate Web3Box client. |
| **0c.** | Testing and Testing Guide | Core functions will be fully covered by comprehensive unit tests to ensure functionality and robustness. In the guide, we will describe how to run these tests. |
| **0d.** | Article | We will publish an **article** in our official [Medium](https://medium.com/@web3box.official) that explains what was done/achieved as part of the grant.  |
| 1. | **Dashboard**:Statistics and display of Filecoin users' assets | Statistics and display of the value of Filecoin users’ onchain assets, statistics and display of the value of input assets & output assets |
| 2. | **Dashboard**:Latest transaction display | View the lastest asset transactions of Filecoin users |
| 3. | **Dashboard**:Real-time assets price | Real-time display of Filecoin assets' price |
| 4. | **Filecoin eco wallet**: Filecoin assets management  | asset management, including asset sending, receiving and transaction record query

**Milestone 2 — Risk Assessment**
Estimated Duration: TBD
FTE: TBD
Costs: TBD 

| Number | Deliverable | Specification |
| -----: | ----------- | ------------- |
| **0a.** | License |  MIT  |
| **0b.** | Documentation | We will provide both **inline documentation** of the code and a basic **tutorial** that explains how a user can install and operate Web3Box client. |
| **0c.** | Testing and Testing Guide | Core functions will be fully covered by comprehensive unit tests to ensure functionality and robustness. In the guide, we will describe how to run these tests. |
| **0d.** | Article | We will publish an **article** in our official [Medium](https://medium.com/@web3box.official) that explains what was done/achieved as part of the grant.  |
| 1. | **Risk Socre**| Web3 projects risk score query for Filecoin users |
| 2. | **Risk Report**| Web3 projects risk report inquiry and download for Filecoin users |

## Total Budget Requested

10,000 USD

## Maintenance and Upgrade Plans

Web3Box team would keep updating about the following milestones and community feedback.

# Team

Team Founder: Eric
Team member: Andrew, more devs would be announced when promoting Web3Box officially.

## Team Website

https://web3box.cc/

## Relevant Experience
Web3Box team has been working on blockchain development and blockchain projects operations for many years, and recently, we have operated the gamefi project [Metauce](https://metauce.org/) successfully

## Team code repositories

https://github.com/web3box-labs

## Additional Information
Learn about the Open Grants Program From https://grants.filecoin.io/
Contact Email: andrew@web3box.cc

**Comment by realChainLife** [comment]
Hi @web3andrew thank you for your proposal. We'd like to fund the work outlined in milestone one above. Look out for an email with detailed next steps!

**Comment by web3andrew** [comment]
> 
@realChainLife  Thanks Filecoin & Sonia, we will pay attention to the next detailed steps. Thank you for your recognition and trust in Web3Box.

**Comment by web3andrew** [comment]
Thanks Filecoin & Sonia, we will pay attention to the next detailed steps. Thank you for your recognition and trust in Web3Box.







---- On Fri, 11 Nov 2022 19:59:56 +0800 Sonia John ***@***.***> wrote ---





Hi https://github.com/web3andrew thank you for your proposal. We'd like to fund the work outlined in milestone one above. Look out for an email with detailed next steps!

**Comment by jenks-guo-filecoin** [comment]
Hi @web3andrew , congrats on your successful grant appeal. Is it possible to get a list of all data sources of your dashboards? I am curious of the data sources, where they are from, and how often do you obtain the information. :-)

**Comment by web3andrew** [comment]
> Hi @web3andrew , congrats on your successful grant appeal. Is it possible to get a list of all data sources of your dashboards? I am curious of the data sources, where they are from, and how often do you obtain the information. :-)

These parts' details are still under talking, our dev will update these info asap. Once ready, I will sync to you.

**Comment by web3andrew** [comment]
@jenks-guo-filecoin  For FIL on-chain data, we will get this info from the Filecoin mainnet in real time. And for the token price data source, we will get the data from [chainlink](https://chain.link/) every 5 mins or 10mins. All data sources are requested in a decentralized way.

**Comment by web3andrew** [comment]
@realChainLife Hi, Sonia, I have sent the OSA confirming email to you, maybe it's in your spam or trash folder, you could check it again. And I also have submitted the info that you guys request. More, I forwarded this email to Erin, you could let Erin know that, perhaps, my email is in his spam or trash folder too.
![image](https://user-images.githubusercontent.com/117150831/202336078-b6a225a7-8eca-4bbc-beb1-0f73c90b9e06.png)
![image](https://user-images.githubusercontent.com/117150831/202336145-faf11d48-82a2-42fa-9ba0-2e26eec53620.png)
