### ISSUE TITLE
Next Step Microgrant: IPFS-MEDICAL-CERTIFICATES

### ISSUE THREAD

**Issue by nattakz** [filecoin-project/devgrants#1124]
### 1. What is your project? 
In some countries, it is common practice for doctors to issue a certificate to validate a worker's absence from work or to certify that a patient can perform physical activities. There, the falsification of these documents is a serious problem. This Dapp allows doctors to securely issue medical certificates. As the documents are stored in the IPFS and the corresponding CID is stored in a smart contract, there is no chance for the patient to falsify the medical certificate. Since only registered doctors can upload medical certificates to the Dapp, it is impossible for the patient to falsify those documents.

### 2. Project links
  
Link to Github repo: https://github.com/grego02/IPFS-Medical-Certificates
Link to demo or website, if applicable: Does not apply
License: 

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
 IPFS is used to share medical certificates between doctors and patients in safe mode. 
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
 Improvements will be made in the UX. 
 Once the CID has been generated, a QR will be generated so that the patient and the final recipient can scan it, so that the app 
 automatically opens and the corresponding certificate is displayed. In addition, aesthetic improvements will be made to the 
 interface.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
  Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
  Yes

### 7. Links and submissions
Does not apply.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  Gregorio Kominiarz - gregorio.kominiarz@gmail.com - https://github.com/grego02/ Full stack developer
* How did you learn about our microgrant program?
  It was recommended to me by a friend.
* If your project was created as part of an event or hackathon:
  Does not apply

**Comment by ErinOCon** [comment]
Hi @nattakz, thank you for the updated submission. We would like to see this project in a [hackathon](https://hackathons.filecoin.io/) before considering for a grant. This can help showcase the trajectory of your future building progress and can also help you get closer to your working prototype/demo. 

Thank you again for your interest in our grant program
