### ISSUE TITLE
Next Step Microgrant: IPFS-SUPPLY-CHAIN-ASSURANCE

### ISSUE THREAD

**Issue by nattakz** [filecoin-project/devgrants#1125]
### 1. What is your project? (max 100 words)
 The project consists of a system to ensure that the goods sent by the supplier to a client, through a 
 carrier, arrives in the same conditions in which they were packed. At the moment of introducing the 
 goods into the transport, a photo of it is taken. This picture  is digitally signed by the carrier. The 
 obtained hash is stored in a smart contract (ethereum), and the photo is uploaded to IPFS.
 This system avoids frauds, since the CID of the original photo and the digital signature of the carrier
 are stored into the smart  contract.

### 2. Project links
  
Link to Github repo:  https://github.com/nattakz/IPFS-SUPPLY-CHAIN-ASSURANCE 
Link to demo or website, if applicable: Does not apply
License:
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
 IPFS is used to share photos of goods sent to the customers by the supplier. As they are digitally signed, 
 and the hash is stored in one smart contract,in the event that the customer doesn’t receive what he ordered, 
 they will be able to verify the goods with the photo of the original CID, since its hash is stored in the smart contract
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Improvements will be made in the aesthetic part and UX. In order to improve the user experience, the CID will be     
facilitated as QR code. So, the carrier will be able to sign the CID by scanning the mentioned QR. Also, the supplier
will be able to take a photo directly from the smartphone or tablet, and upload it directly to IPFS. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
Does not apply.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Nataniel Kominiarz - nattakz@hotmail.com - https://github.com/nattakz/
 Solidity developer
* How did you learn about our microgrant program?
It was recommended to me by a friend.
* If your project was created as part of an event or hackathon:
Does not apply

**Comment by ErinOCon** [comment]
Hi @nattakz, thank you for your proposal. We would also highly recommend a [hackathon](https://hackathons.filecoin.io/) for the next steps of this project. Please feel welcome to submit this project or IPFS-MEDICAL-CERTIFICATES(https://github.com/filecoin-project/devgrants/issues/1124)](https://github.com/filecoin-project/devgrants/issues/1124#top) after completing a hackathon.
