### ISSUE TITLE
MetaID for Azomland

### ISSUE THREAD

**Issue by azomland** [filecoin-project/devgrants#1126]
### What is your project (100 words maximum)?

MetaID is a product of Azomland that will allow people to have a distributed and hierarchical system of information on FPS, with association to a wallet on the Polygon network.
The product will allow users to generate a quick registration on Azomland and other compatible platforms.
 ### 2. Project links

Link to the Github repository:
Link to demo or website, if applicable: www.azomland.com, demo Q3 https://youtu.be/RujOPNwluf8
 
 
  
### 4. How will you enhance your project with this grant? What steps will you take to accomplish this goal (max. 200 words)?
The first development goal is to move the concept to a functional model with technology based on Three.js with which we will have a solution on the web, with generalized compatibility. The grant will allow us to accelerate the process by increasing our developers. 

### Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?
We agree
  
### 6. Does your proposal comply with our Community Code of Conduct?
Compliant

### 7. Links and submissions.
Has not been submitted to Filecoin Labs.
  
### Additional questions:
*Niccolas Munoz, CEODEV, niccolas@azomland.com
* How did you hear about our microgrant program?
I was advised by telegram with part of the Labs and Filecoin team.

**Comment by ErinOCon** [comment]
Hi @azomland, thank you for your proposal! In order to be an eligible candidate for the microgrant program, a project repo with applicable code is necessary. It is also required that the supported work be open source. 

Please feel welcome to reapply if your project meets this criteria in the future.
