### ISSUE TITLE
Next Step Microgrant: Podmatic

### ISSUE THREAD

**Issue by ayushgupta0110** [filecoin-project/devgrants#1127]
### 1. What is your project? (max 100 words)
Podmatic is an NFT marketplace for podcasters and fans. We aim to uplift podcasters by enabling them to create NFTs of their podcasts and provide them with the royalties and recognition that they deserve.

The royalty distribution in its present form makes it difficult to keep the fair share of revenue podcasters generate on existing platforms. Moreover, there’s no transparent and decentralized platform for the same.

Podmatic is more than just an NFT marketplace for podcasters and fans. It will bring them together like never before and unlock novel models of communications and commerce.

### 2. Project links
Link to GitHub repo: https://github.com/ayushgupta0110/Podmatic
Link to website: https://podmatic.vercel.app/ 
License: MIT (https://github.com/ayushgupta0110/Podmatic/blob/main/LICENSE)
Pitchdeck: https://drive.google.com/file/d/1ShzpkDGDwPqJHufM2R66hHMaJ5U0EDMz/view?usp=share_link
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Podmatic makes use of IPFS to store all kinds of files ranging from images used in Podcast covers to profile pictures. We also store the audio files of the podcasts on IPFS. NFT metadata and profile data are also stored on IPFS and Filecoin. 
IPFS & Filecoin will be used to exclusively share secret files and contents between the parties involved as unlockable content. We will encrypt the files and store the ipfs hash of the unlockable content in our smart contract which will only be accessible by the current owner of NFTs. So, this content will basically be token-gated.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We look forward to continuing to build this product after the hackathon as we believe this product has potential and our team can make it big. We will expand our development, designing, and marketing team.

We’re planning to add multiple features to improve this project:
- Improve the UI/UX of the platform
- Multichain support
- Migrating to Moralis
- Royalty distribution (Split ownership)
- Unlockable Content
- Add to cart feature
- Follower/Following
- Favourite NFTs
We will start building the community and get their initial feedback to further improve and expand the vision.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, we will share regular updates about the project. We are planning to build this project in public. 
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
- Our project was developed at 1, 2, Web3 Hackathon - Moralis x Filecoin 2022 Hackathon.
Podmatic won the Polygon pool prize in this hackathon: https://moralis.io/filecoin-hackathon/winners/ 
![podmatic](https://user-images.githubusercontent.com/76724104/200792939-edc142c3-7f5e-4938-8e87-107111ed9309.png)  
- We have applied to Filecoin’s Hall of Fame projects. It’s yet to be accepted.

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
### Team Members:
* Name: Ayush Gupta
    Email: [ayushgupta747492@gmail.com](mailto:ayushgupta747492@gmail.com)
    GitHub Account: [https://github.com/ayushgupta0110](https://github.com/ayushgupta0110)
    Role in the project: Front-End Development

* Name: Shivam Singh
    Email: [shivamsinghc502@gmail.com](mailto:shivamsinghc502@gmail.com)
    Linktree: [https://linktr.ee/shivamsinghcco](https://linktr.ee/shivamsinghcco) 
    Role in the project: Designing

* Name: Pushpit Bhardwaj
     Email: [pushpit07@gmail.com](mailto:pushpit07@gmail.com)
     GitHub Account: [https://github.com/Pushpit07](https://github.com/Pushpit07)
     Role in the Project: Smart Contracts Development, Front-End Development, and Back-End Development.

* Name: Yuvraj Chandra
    Email: [singhyuvraj179@gmail.com](mailto:singhyuvraj179@gmail.com)
    GitHub Account: [https://github.com/Yuvrajchandra](https://github.com/Yuvrajchandra)
    Role in the project: Product Management and Content Writing

* Name: Sparsh Sharma
    Email: [sparsh.sharma2510@gmail.com](mailto:sparsh.sharma2510@gmail.com)
    GitHub Account: [https://github.com/sparshsharma2510](https://github.com/sparshsharma2510)
    Role in the project: Front-End Development

* How did you learn about our microgrant program?
Through Github

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
* Podmatic was developed at **1, 2, Web3 Hackathon - Moralis x Filecoin 2022 Hackathon**.
* [https://moralis.io/filecoin-hackathon/winners/](https://moralis.io/filecoin-hackathon/winners/) (Polygon Pool Prize Winner)
* Link to the live website: [https://podmatic.vercel.app/](https://podmatic.vercel.app/)

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
