### ISSUE TITLE
Getaverse

### ISSUE THREAD

**Issue by yubygetaverse** [filecoin-project/devgrants#1128]
# Open Grant Proposal: Getaverse

**Name of Project: Getaverse**

**Proposal Category:**  `metaverse` 

**Proposer:** `yubygetaverse`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** 

Yes

# Project Description

### What is Getaverse

Getaverse is a web3 DID platform deployed on several public chains. We are aiming to create an ecological metaverse service platform based on the Web3 protocol for digital authentication systems. Innovative Web3 projects and applications are able to publish and access data through Getaverse open API interface. Getaverse's vision is to be the largest trusted data curation DID platform in the Web 3.0 world, empowering the full ecological application of Web 3.0 innovative products.

### **Problems Statement**

Data Security & Ownership: Web2 users do not have the ownership and right to control of their own personal information.

Credit Issues: There is no unified credit platform, the user’s credit data is often limited to a single ecosystem.

Trusted Marketing Traffic: There are numberless fake data and robots in the markets.

### Getaverse’s Solution

Getaverse creates a multi-layer independent on-chain ecosystem providing DID, SBT based system. Providing API for Data Collection, Analysis and Authentication. Covering a very wide range of areas including Metaverse, GameFi, DeFi, NFT, DEX, Social Fi and others.

- Unified Identity platform based on Soul Bound Tokens (SBT)
- On-chain credit system based on data analysis and scoring, chaging the system of web3 personal data value
- Trusted traffics, enabling the full ecological applications of web3 innovation product
- Open DID and API for linking all web3 application ecosystems.

## Deliverables

Major functional components includes:

- Credit System
- DAO Governance
- Trusted Verifier Node

Data sources will be built for Reputation & Credit

- Identity information
- Assets evaluation
- Behavior tracking
- Social influence

## Development Roadmap

- Markets Development (2022)
    - Already created strategic partnership with web3 projects including LINK3, Bit, Element NAwareat, Chill, Dtools, ReadON, Chamcha and more
    - Already created strong strategic partnership with major IP cooperation covers world-famous football players, modern artists, humanities artists, illustrators, etc. Such as Christian Vieri, Wesley Sneijder, Kendra Dandy, FAFI, Aunty Acid, Mister Phil, Karan Singh, Heather Dutton, Owen Davey and Rongrong DeVoe, etc.
- Product Development
    - 2022 Q3
        - Launch Getaverse platform
        - Launching on BSC Chain Wallet
        - Launching DID system
        - Deploying the genesis node
    - 2022 Q4
        - Launch nodes operation
        - Start the systematic token production and distribution
        - Launch DAO governance
        - Launch the SBT-based credit system
    - 2023 Q1
        - Launch the decentralized social system
        - Develop and deploy on multi-chains(ETH/SOL…)
        - Open the multi-functional API interface on the platform
        - Launch more web3 applications based on community voting
        - Upgrade the SBT-based credit system
    - 2023 Q2
        - Provide customized platform services
        - External authorization of DID identity
        - DID identity recovery
        - More expansionary work…

## Total Budget Requested

Product Development

- Dev: USD $30000
    - Build getaverse Core System
        - Computing Nodes
    - Build Getaverse Core Reputation System
        - Multichain Smart Contracts
    - Getaverse SBT Credit System Foundation
        - Build Getaverse Protocol
        - Getaverse Web Client SDK
        - Getaverse Protocol Web API
    - Build Getaverse Ecosystem
        - Decentralized Social System
- Audit: USD $20000

## Maintenance and Upgrade Plans

N/A

# Team

## Team Members

Ryan Chris

Yuby Brown

Eden

## Team Member LinkedIn Profiles

[https://www.linkedin.com/in/ryanchris3](https://www.linkedin.com/in/ryanchris3)
[https://www.linkedin.com/in/yuby-che-06316a231/](https://www.linkedin.com/in/yuby-che-06316a231/)
[www.linkedin.com/in/eden-calvin](http://www.linkedin.com/in/eden-calvin)

## Team Website

**Email**: info@getaverses.com

**Website**: [https://getaverses.com/](https://getaverses.com/)

**Twitter**: [https://twitter.com/GetaverseGlobal](https://twitter.com/GetaverseGlobal)

**Telegram**: [https://t.me/Getaverse_Official](https://t.me/Getaverse_Official)

**Medium**: [https://medium.com/@GetaverseGlobal](https://medium.com/@GetaverseGlobal)

**Discord**: [https://discord.gg/MKe3YJyQ65](https://discord.gg/MKe3YJyQ65)

**Whitepaper: [https**://docs.getaverses.com/](https://docs.getaverses.com/)

## Relevant Experience

**Ryan Chris**: with 5 years of investment research experience in cryptocurrency and expert in digital marketing and cryptocurrency startups. Ryan invested in more than 10 projects and provided marketing and financial consulting services for more than 5 projects.

**Yuby Brown**: has over 5 years of project management experience and has worked for blue chip companies and a number of startups. Yuby is responsible for the governance and planning of the Getaverse ecosystem, the review of proposals, the voting, and the supervision and operation of funding allocations.

**Eden**: has over 7 years of executive experience in IT strategy and cybersecurity. Previously the CTO of a multinational enterprise software company focused on technology monitoring, cybersecurity and compliance.

## Team code repositories

Under development

# Additional Information

N/A

**Comment by realChainLife** [comment]
Hi @yubygetaverse thank you for your proposal. Several questions came up during the initial review and I'd appreciate your thoughts on the same: 
- What parameters / attributes will you use, especially as signed credentials, to link to DID objects? 
- How will you store the hashes of the verifiable statements?

**Comment by ErinOCon** [comment]
This issue has been closed. Please feel welcome to reapply at your convenience.
