### ISSUE TITLE
Open Grant Application - DAOhub

### ISSUE THREAD

**Issue by ardaerturk** [filecoin-project/devgrants#1131]
**Open Grant Proposal:** DAOhub

**Proposal Category:** `app-dev`

**Proposer:** `@ardaerturk`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Please respond with either "Yes"

# Project Description
DAOhub is a DAO marketplace to make DAO discovery, voting, and portfolio management easier in one central platform.

https://daohub.xyz

## Value

**Problem:**
Pain points in the DAO ecosystem:

- Despite the growing popularity of DAOs, finding and joining them is still difficult. It can take an investor up to 8 to 9 steps to invest in a DAO. Almost impossible for newcomers to web3.
- Voter turnout is often low as there is no easy way to get notified about ongoing votes. You need to keep track of different platforms such as Snapshot, and Telegram. It is almost impossible if you have more than 10-15 different DAO holdings.
- Not all governance matters are equally sensitive. A need for voting process for every business decision is inefficient.

**Solution:**
We are building a full suite of products to provide the full user experience in 3 layers, Discover, Invest, and Involve.

- The marketplace product will bring DAO information together while allowing investors to review their financials and buy their tokens.
- DAOhub dashboard will enable investors to connect their wallets and manage their portfolios easily while getting notified about new proposals and allowing them to vote on one platform.
- Our AI-based portfolio manager will help investors to automate voting based on their risk profile to increase voter turnout while removing human-bias. We will also use this data to offer customized investment products. We are not seeing a lot of applications of AI in web3 so far. We are aiming to become one of the first movers.

## Deliverables

1. Integrating Filecoin DAOs into our marketplace.
2. Launchpad Product Launch - Promoting Filecoin to encourage DAO builders to build on Filecoin
3. Creating index funds

## Development Roadmap

**Milestone 1: Integrating Filecoin DAOs into our marketplace.**
Our users will be able to see information about DAOs including the background, team, technology, financials, token economics, community, investors, etc.
In addition, our users will be able to purchase or sell their governance tokens in 2 simple steps.

2 full time developers ($7,000/employee)

Dates:
12/01/2022 - 15/01/2023

**Milestone 2: Launchpad Product Launch**
We will support DAO builders with fundraising and 3rd-party tools.

- Prepare marketing materials
- Promote Filecoin as the preferred network for new DAO builders
- Build a smart contract to allow individual investors to invest in DAOs on our Launchpad
- Build a smart contract that acts like a SAFE note for institutional investors

***Metrics***

- Number of new DAO listings
- Average fund size for launchpad DAOs
- Number of launchpad DAO investors

       
3 full time developers ($9,000/employee)
2 business development ($5,000/employee)

Dates:
12/01/2022 - 10/02/2023

**Milestone 3: Creating index funds**
We will build DAO index funds. The tokens will be backed by DAO token holdings in the same category. (E.g. Top 10 DAOs in DeFi). Some of the important criteria include; a $15M minimum market cap, a minimum of 120 days of historical financial data, daily volume to market cap ratio is at least 15%.

2 full time developers ($4,000/employee)
Financial Analyst ($5,000)

Dates:
01/01/2023 - 01/03/2023

## Total Budget Requested

$64,000

# Team

## Team Members

Arda Erturk - CEO & Founder https://www.linkedin.com/in/ardaerturk/
I studied machine learning & data science at University of Toronto between 2016-2021. During my academic career, I worked at Canada's largest bank, Scotia Bank, as a solutions architect under Global Wealth Management department. During my 3rd year, I co-founded Roll Scooters which is backed by Techstars and now being acquired by a competitor. I'm a strong believer in the future of DAOs and that's why I'm pivoting myself into this industry. I'm part of various DAOs including Lime DAO, Constellation DAO, and building my own DAO called AceDAO.

Daniel Robinson - Founding Engineer https://www.linkedin.com/in/danielrobinson94/
Daniel is a self-taught web3 engineer. He has prior DAO and DApp experience as lead developer including Fragmints. He also worked at Goldman Sachs as an analyst prior to his engineering career.

Nikhil Nampalli - Advisor https://www.linkedin.com/in/nikhilnampalli/
Nikhil is our advisor at DAOHub. He is the Head of Product at American Express and has served in an executive product leadership role for the largest financial institutions including American Express and Citi Group.

## Team Website

https://daohub.xyz

**Email:** arda@mefi.ca

**Comment by ardaerturk** [comment]
**Traction Update:**

It's been almost a month since we released our beta version and received over 30K+ calls on our Infura node with zero marketing dollars!

![Screen Shot 2022-11-08 at 4 18 48 PM](https://user-images.githubusercontent.com/21202887/202219065-a649391f-9271-4365-b13d-832e032c9c62.png)

**Comment by ErinOCon** [comment]
Hi @ardaerturk, thank you for the update! Can you briefly explain what "Filecoin DAOs" refers to in your development roadmap? For example, are these DAOs formed by FVM smart contracts? Or DAOs governing data stored on Filecoin? Also, can you provide example DAOs planned for on-boarding?

**Comment by ErinOCon** [comment]
Hi @ardaerturk, are you still interested in applying for this grant?

**Comment by ardaerturk** [comment]
Hi @ErinOCon, I'm really sorry for the delay. I didn't get a notification.

By Filecoin DAOs, we meant DAOs that are utilizing Filecoin - and DAOs formed by FVM smart contracts. We already listed some DAOs like ENS and are in the process of adding more such as Ocean Protocol.

Since our last update in December, we built a governance product where investors can easily review all the active proposals of portfolio DAOs and vote directly on DAOhub. One of our goals is to enable our users to create a proposal and we would love to work with Filecoin to store the contract and this data. https://daohub.xyz/dashboard

Another product we are launching this week is a data analytics dashboard for DAOs where you can review sentiment analysis and subjectivity analysis of off-chain data, analytics of on-chain data, and community-powered by AI. We'd also love to explore the ways we can collaborate with Filecoin for this product as well.

![Screen Shot 1](https://user-images.githubusercontent.com/21202887/214719735-536e71c7-c0cb-45d3-9f11-e7001ab1f1b3.png)
![Screen Shot 2](https://user-images.githubusercontent.com/21202887/214719737-57b39776-4db8-418c-9c02-693b6160ed23.png)
![Screen Shot 3](https://user-images.githubusercontent.com/21202887/214719738-cf459bf4-b2ca-41cc-b457-1dc1384fb376.png)
![Screen Shot 4](https://user-images.githubusercontent.com/21202887/214719739-15d993d5-a4dd-4535-a6aa-2afc6672d940.png)

**Comment by ErinOCon** [comment]
HI @ardaerturk, thank you for the provided updates and for your time with this proposal! Unfortunately, we will not be moving forward with a grant at this time, but we would be interested to learn more as you continue to progress. 

Wishing you the best as you continue to build!
