### ISSUE TITLE
Next Step Microgrant: StableBridge $SBRB

### ISSUE THREAD

**Issue by dizzyexis** [filecoin-project/devgrants#1132]
### 1. What is your project? (max 100 words)
StableBridge uses LayerZero solution that embraces multiple routings to safely transfer user assets without the need to lock for a huge time or rely on liquidity in both sides. It's native stablecoin $SBRB is pegged to the Brazilian Reais, and can be purchased using the country payment system PIX, later being transfered in the desired wallet and network. 

### 2. Project links
Link to Github repo:
https://github.com/dizzyexis/stablebridge-front-main
https://github.com/dizzyexis/stablebridge-backend-main

License:
MIT License  
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
All user historical data and activities will be encrypted and pinned to IPFS using the directory method. In parallel, all user data, protocol data etc, will be listed in another CID directory, using the power of IPFS recursion and cryptography to hold records in public server but keeping the secrecy of data.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Our product is currently what we've built in the hackathon, and we want to improve and test it with real users, so this becomes a product. 

We gonna use this grant to kickoff this development, mainly to keep a cloud server that can constantly read, write and pin all of our protocol activities, with an expected runtime of over a year, with several months of constant CID generation, transactions and other activities.

1- Create a data model for the transactions being made in the protocol
2- Fill the data with the protocol operations, both on and off-chain
3- Encrypt data with the suggested IPFS encryption partners (more study must be made)
4- Generate the CID, push the new CID to the main CID directory (containing all operations)
5- Run metrics on the process and benchmark cloud services that will fit our needs
6- Prepare the cloud service
7- Raise security measures
8- Upload algorithm 
9- Runtime
10- Optimizations and next moves 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
https://blockful.io/
https://medium.com/blockful
https://twitter.com/Blockful_io
https://www.instagram.com/blockful.io/
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

name: Alexandro de Campos Teixeira Netto
email: alex@blockful.io
github: alextnetto
role: Smart Contract Developer

name: Franco Camelo Aguzzi
email: franco@blockful.io
github: FrancoAguzzi
role: Frontend Developer

name: Guilherme Heilmann Costa Neves
email: guilherme@blockful.io
github: dizzyexis
role: Smart Contract Developer

name: Maicon Moreira
email: maicon@blockful.io
github: Maicon-Moreira
role: Backend Developer

* How did you learn about our microgrant program?
We've been instructed by Filecoin representatives in the EthereumSP Brasil Event

* If your project was created as part of an event or hackathon:
EthereumSP Brasil

  * Please link to your hackathon submission
  https://taikai.network/ethbrasil/hackathons/ethereumsp22/projects/cl7w6dtqh94309101wu3u9q0xua/idea

**Comment by jenks-guo-filecoin** [comment]
@ErinOCon this is one of the winners of ETH Lisbon hackathon. Not on Filecoin track but recommend approving them.

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
