### ISSUE TITLE
Localnet.Farm

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/devgrants#1133]
### 1. What is your project? (max 100 words)

Hosted Filecoin Lotus "[localnets](https://lotus.filecoin.io/lotus/developers/local-network/)" in the cloud for developers and researchers.

### 2. Project links
  
Link to Github repo: https://github.com/jimpick/localnet-farm
Link to demo or website, if applicable: https://localnet.farm/ (coming soon)

License:

MIT+Apache. Data is CC-BY-SA 3.0.
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

This project enables hosting a personalized localnet in the cloud that runs Filecoin Lotus. The initial
target users will be FVM security researchers.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Deliverables:

* Docker images: https://github.com/jimpick/lotus-fvm-localnet
* Hosted cluster setup on AWS
* Github repo using terraform to setup AWS EKS (Kubernets) + EFS + load balancing (can be self-hosted)
* Command-line utility + simple API for developers to provision and control their localnets
* Small website for signups, documentation

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

N/A
  
### Additional questions:

* For each team member(s), please list name, email, Github account, and role in the project.

Jim Pick, [jim@jimpick.com](mailto:jim@jimpick.com), @jimpick - sole contributor

* How did you learn about our microgrant program?

I have applied and received microgrants previously.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

N/A

**Comment by BlocksOnAChain** [comment]
@realChainLife @ErinOCon  - I think this is needed by the FVM team + external devs that will use the local net. I approve this micro-grant for Jim and his work.
Let me know about next steps.

**Comment by ErinOCon** [comment]
Hi @jimpick, thank you for your proposal! We have sent an email to confirm payment details. Please let me know if you have any questions.
