### ISSUE TITLE
Next Step Microgrant: Greenlit Protocol 

### ISSUE THREAD

**Issue by TheDecentralizedProducer** [filecoin-project/devgrants#1134]
### 1. What is your project? (max 100 words)

Greenlit Protocol  streamlines licesning & distrubution in the media & entertainment industry for creators & independent studios. We leverage IPFS to store backend data  for platform and as well interested in offering a Media Asset Management feature that allows decentralized storage of a projects IP that owners can authenticate access to end users. 

### 2. Project links
  
Link to Github repo:  https://github.com/Granting-Wishes-Studios
Link to demo or website, if applicable: https://www.figma.com/proto/wmaBYpVYsMihxZd7mRZ1MI/POSL-MVP?node-id=105%3A3219&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=105%3A3219&show-proto-sidebar=1
License: TBD either MIT or GPL

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
<img width="826" alt="image" src="https://user-images.githubusercontent.com/84410115/201001025-7cbd521a-cdc1-42f2-8ac4-a5e52404890e.png">  

We are looking to expand on this to incorpate " Media containers' Per projects/spaces where users can Store, Media/assets/screeners etc related to the IP they are looking to license.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Currently as it is, our app stores & retrives data that is shown on the front end. We want to build a way where users can  essientally create " Media containers" using a DID structure based on who/what is licensed, grants access to the users  orginal media, wether its images,video,clips etc so the licesee can use/manipulate the orginal files. This will allow us to be a strong compeitor within the space and Web2 counter parts, as well as providing access to media storage & delivery, for pennies on the dollar. Futher more we will be tokenizing our licesning agreements on chain resulting in a need to store the actual contract in a decentralized way that can always be referenced. This will be a flexible use  case as we will eventually work in Zk proofs to extract senstive information from being publicly seen so it provides the benefits of a decentralized without sacrificing security. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Absolutely!
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes it does.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
  It did not start at a hackathon. 

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program? @doctorrobinson 
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
  
  ### Team
  
 **Ian Grant** - CEO/President 
 Ian@getgreenlit.xyz 
 Github: https://github.com/TheDecentralizedProducer

-  Marketing
- Sales 
- Project Managment 

**Zach Lona** - Co-Founder/Product Lead 
Zach@getgreenlit.xyz 
Github: N/A 

- Product 
- Design 
- User Testing  

**Rejoice Edokpayi** - Front End Developer 
Rejoiceoedokpayi@gmail.com 
Github: https://github.com/rejoicedo 

- UI/UX 
- Front End Development  (React)  

**Jeremiah Chike** - Lead Full Stack Dev 
mcjerry73@gmail.com 
Github: https://github.com/Slymcode 

- Back end development 
-  Front end development 
- Solidity development 
- Architect design

**Comment by jenks-guo-filecoin** [comment]
Hi @TheDecentralizedProducer, could you please help me understand what is exactly stored in IPFS and via what services/method/nodes do you plan to store this for persistency of the media files? 

I would like to also understand in more details the access control part. How is it provided and how does it exactly protect the media files that is stored publicly on IPFS? 

Could you also explain the flow of NFT staking and agreement part? Explain via a typical media right purchase flow please.

**Comment by TheDecentralizedProducer** [comment]
Hey @jenks-guo-filecoin  Sorry for the delay here.

**_could you please help me understand what is exactly stored in IPFS and via what services/methods/nodes do you plan to store this for persistence of the media files?_**

Currently were storing our Media/ (PDFs(contracts) that will be used as well site images and when the time comes Video.) This is being done through PINTA currently. We are also exploring running our own IPFS node to ensure data is persistent. 


**_I would like to also understand in more detail the access control part. How is it provided and how does it exactly protect the media files that is stored publicly on IPFS?_**

As creators/ studio owners etc, have original media assets related to the IP in question for licensing. Distributors/licensees will need access to these files, as well as a way to share the access to these files. Greenlit is acting at the “ front end “ to facilitate that, where users can upload media to be stored on IPFS, then allowing granted access to only those who have the proper access via a licensing (Licensing IP)  to be able to grant access/ update the state ( show mockups of designs etc). This can be achieved by [Ceramics](https://blog.ceramic.network/what-is-ceramic/) Stream state. This would allow the IP owner to have a dynamic, mutable, version control & access control with programmable logic. Furthermore, the License IP authenticates by granting access via the decentralized identifier access ( see diagram below). Therefore Because the JSON stores, the DID access on IPFS only the user licensing would be able to access the Media because it points to the proper hash (CID)

![Group 1](https://user-images.githubusercontent.com/84410115/203215580-5777dcbb-f7e5-40a3-bae6-a1deb1cb8105.png)

_**Could you also explain the flow of NFT staking and agreement part? Explain via a typical media right purchase flow please.**_

Yes, traditionally in the media & entertainment space, when someone has a media(film/ etc) there are rights associated with the underlying copyright of the film/media. So they can do what is called “ Carving” out of rights ( Game rights, Toy rights, merchandise rights, etc.). These can be multiple parties or a single party that acquire these monetization rights. Normally they would Pay a fee, sign the agreement & then be granted access to the original IP/ deliver the IP, then have a revenue share all stipulated within the contract. With Greenlit through our Proof of Staking licensing, we developed a way to “ Stake an NFT, based on a Tier set by the IP owner ( I.e for a movie you would need 5 NFTS of said collection, Merchandise 2 NFTs of collection) and stake the NFTs. Through the platform, users will sign an agreement, using components of (OpenLaw E signature smart contract markdown &  A16z’s can’t be evil license).  The agreement would then become tokenized and able to be referenced for any revenue recoupment & payments responsible to be paid to the Original  IP owner. 

happy to provide more context if it helps.  We'll be modeling something similar to what a Big pharma DAO is doing but tweaking & tailoring it toward Film/Media & entertainment.

**Comment by ErinOCon** [comment]
Hi @TheDecentralizedProducer, the project repo currently isn't open to the public. Can this be updated?

**Comment by TheDecentralizedProducer** [comment]
Hi @ErinOCon  Yes I can open it,  We're just double-checking to make sure no APIs or anything is exposed in any of the repos, we'll have it open shortly.

**Comment by TheDecentralizedProducer** [comment]
Hey @ErinOCon  Happy New Year, we just opened the repo.

**Comment by ErinOCon** [comment]
Hi @TheDecentralizedProducer, thank you for the update. This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
