### ISSUE TITLE
Chanson Studio – FileCoin Powered Music NFT DApp - Further Milestone Development

### ISSUE THREAD

**Issue by ChansonStudio** [filecoin-project/devgrants#1137]
# Open Grant Proposal: `Chanson Studio – FileCoin Powered Music NFT DApp - Further Milestone Development`

**Name of Project: Chanson Studio

**Proposal Category:** `app-dev`

**Proposer:** `ChansonStudio`

**(Optional) Technical Sponsor:** `jenks@fil.org`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** `Yes`

# Project Description

Chanson Studio has successfully completed 2 milestone delivery via Filecoin RFP application "Chanson Studio – FileCoin Powered Music NFT DApp #762", our team is seeking future feature delivery on enhancing product security & popular leasing features to be delivered in Milestone 3 & Milestone 4.

Chanson Studio is a Decentralised NFT online platform to promote, capture and propagate music inspirations. Chanson is powered by FileCoin to store and retrieve music created by both established or aspiring artists. 

Chanson has an innovative feature whereby music creators can mint NFTs for any musical works they created whether it is a full solo piece or just an unfinished melody. Other creators can then build on these musical components to create more music while the original creators get paid through their NFT copyright.

Chanson aims to reward music creators fairly and encourage more creation and innovations in the music industry through our platform.

Chanson is not just an NFT marketplace, it is a project in the creator economy. We want to create together with the artists an ecosystem that redefines the rules of the game and that brings value to artists and fans. Our goal is to help musicians spreading their creations all over the world.

We have a vision for decentralised content streaming (both music and video) achieved through the power of Web3 technologies and enhanced by the fully decentralised storage networks from FileCoin. Chanson Studio has also planned a decentralized peer-to-peer streaming that allows users to earn cryptocurrency while watching the streaming video (Watch & Earn).

## Development Roadmap
#Milestone 3 – Music NFT Content Encryption Security Enhancement
-	Security enhancement on music NFT content to ensure content protection for owners. Leverage Python encryption solution, after encryption place encrypted content onto Filecoin NFT.storage solution. Retrieving of content by owner will involve content decryption then content is available for access.
-	Complete encryption key generation.
-	Complete file encryption / decryption.
-      Deploy the NFT smart contracts written in Solidity directly to FVM.
-	Integrate the security encryption process before loading into Filecoin NFT.storage solution.
-	Integrate the security decryption process after retrieving encrypted content from Filecoin NFT.storage and get ready for user access.

#Milestone 4 – Music NFT Short Term Leasing Capability & Product Soft Launch
-	Short term leasing capability is essential for events that broadcasts the music content.
-	Complete peer to peer leasing capability build.
-	Develop call back smart contract which sets the leasing term and criteria for call back.
-      Deploy the NFT smart contracts written in Solidity directly to FVM
-	Chanson Studio soft launch on TestNet.

#Milestone 5 – Soft launch user adoption target
-	0 - 3 months from TestNet launch we aim at targeting 200 users on TestNet
-	3 – 6 months from TestNet launch we aim at targeting 500 users on TestNet
-	Upon successful TestNet launch and product improvement we aim at MainNet launch a quarter after.

## Total Budget Requested
USD$50,000

| Budget Table        | Milestone 1 | Milestone 2 |
|---------------------|-------------|-------------|
| Graphic Designer    | USD$9,000   | USD$9,000   |
| Front End Dev       | USD$15,000  | USD$15,000  |
| Cloud Platform Cost | USD$1,000   | USD$1,000   |
|                     |             |             |
| Total               |             | USD$50,000  |

# Team

## Team Members
Jack Hui – Founder and Tech Lead
Linda Chew – Blockchain Developer

## Team Member LinkedIn Profiles
https://www.linkedin.com/in/jackhui88/
https://www.linkedin.com/in/linda-chew-b8b578243/
https://www.linkedin.com/in/benjamin-russell-856392245/

## Team Website

[https://chansonstudio.xyz/](https://chansonstudio.xyz/)
[https://chaining.com.au/](https://chaining.com.au/)

## Relevant Experience

Jack Hui
A very passionate and experienced technologist who enjoys designing and implementing elegant designs that help achieve strategic business and human objectives. Practical knowledge in software development best practices and excellent communication skills. Hands on experiences in developing web-based applications and experiences with solidity, NFT's and other cryptocurrency technologies. Experiences in building micro services-oriented blockchain infrastructure and nodes.

Linda Chew
Linda has a strong passion for learning and is fascinated with disruptive technologies, particularly blockchain and genetic technologies. Linda has experience in both blockchain development and entertainment and media, music industry. Her unique combination of skills allows her to bring strong technical competencies, engaging communication and the accuracy required to produce secure code in the entertainment and media space.
Her initial interest in blockchain technology and cryptocurrency quickly compounded into a passion resulting her to pursue further study of blockchain technologies and programming, eventually becoming a digital nomad and full-time solidity developer.

## Team code repositories
https://github.com/ChansonStudio/ChansonStudio.git

**Comment by ChansonStudio** [comment]
Our team has communicated to Technical Sponsor jenks@fil.org and he has recommended of adding these great features into the products.

**Comment by ChansonStudio** [comment]
Hi Team @realChainLife , any updates on the new feature dev application?

**Comment by ChansonStudio** [comment]
@realChainLife  Hi team any updates?? =)

**Comment by jenks-guo-filecoin** [comment]
Hi @ChansonStudio, do you think we can alter the milestones to include launching NFT standards on the upcoming [FVM (EVM compatible)](https://fvm.filecoin.io/)?

**Comment by ChansonStudio** [comment]
@jenks-guo-filecoin Sure thing, we are extremely excited about the soon to launch FVM capability, and our purpose is to deploy the NFT smart contracts written in Solidity directly to FVM. NFT assets & metadata will be saved to NFT.Storage.
I have also updated the above Development Roadmap.

**Comment by ErinOCon** [comment]
Hi @ChansonStudio, thank you for your proposal and congrats on your progress! Can you describe how you are interacting with your target audience? Do you have information that speaks to your current and projected user base?

**Comment by ChansonStudio** [comment]
Hi Team, We are currently forming a partnership with VMDO https://www.vmdo.com.au/ in Australia, and we have a projected user base starts with 200-500 user (members from VMDO).

**Comment by ErinOCon** [comment]
Hi @ChansonStudio, thank you for the additional details! We will not be moving forward with a grant at this time, but would recommend you check out [accelerator opportunities](https://ecosystem-wg.notion.site/Protocol-Labs-Accelerator-Program-d45d8792a7d544eca9beb7d3e3d3b05d). 

Wishing you the best as you continue to build!
