### ISSUE TITLE
Open Grant Application - Lagrange DAO

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/devgrants#1138]
# Open Grant Proposal: `Lagrange DAO`

**Name of Project:** Lagrange DAO

**Proposal Category:** `app-dev`

**Proposer:** `flywork`

**(Optional) Technical Sponsor:** `bacalhau`，`filswan`,`fevm`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL
licenses?:**

Yes

# Project Description

![img_2](https://user-images.githubusercontent.com/8363795/201774826-45ac645a-0736-4802-aeb8-37f5637c58c7.png)

Lagrange DAO is a DAO for data value realization. It provides data sharing & analytic spaces for Decentralized science (
DeSci). With Lagrange Spaces, researchers are able to use public infrastructure for storing, sharing, creating,
rewarding,
and disseminating scientific knowledge fairly and equitably using the Web3 stack.

Lagrange DAO consists of 4 parts: dataset, model, space and revenue sharing. Researchers can upload the dataset and
models to their workspace and sharing with the community. Users can share the benefit with the data and model
contributors.

The Lagrange DAO's treasure fund comes from data consumption, model usage and community donation. Funds will be used
for:

* Reward the dataset upload
* Model creation
* Storage and computing
* Public relations and external cooperation.

With Lagrange DAO we are aiming to provide a self-sustainable data ecosystem driven by the community.

### Data

Data is owned by the user. it is not limit to the dataset but also include the data schema, model and anything
related.

* Data uploader owns the data, he has the right to mint the data as an NFT
* With the Ownership of the data, he can authorize, sharing and gain the revenue from the data created
* Arbitration need the community token as a cost
* Data is stored on IPFS/Filecoin

### Space

Space is the major place where user shares and calculates the data. User can integrate the data and
model inside their workspace.

* Anyone can create a space
* Owner can share the space with other users, more shares will bring more credits
* The space is stored on IPFS and Filecoin
![img_3](https://user-images.githubusercontent.com/8363795/201774601-1f150c65-69c3-4aac-90cc-9c98eb42a5f3.png)

### Revenue sharing

In the ecosystem, there are different roles:

- Data Providers
- Storage Providers
- Other Resource Providers

Based on different scenarios, the revenue sharing is backed by smart contract based on the task types. The initial
contract revenue sharing is:

* 10% for storage provider
* 10% for bandwidth
* 50% for Other Resource Providers
* 30% for DAO treasure

### Token

The lagrange token (LAG)  is a token created for community sharing incentive. It is designed for the following purpose:

* Incentive for uploading dataset
* co-work inside the working space
* community governance
* For other service payment e.g. computing and CDN resource

## Value

Filecoin currently has over 18EB storage space and Scientific dataset is growing rapidly. Scientific data is high
valuable assets and requires storage over 10 years, which is a perfect use case for filecoin network. At the end of 2025
the scientific data will grow to 250 PB, which is equivalent to 2.5EB quality adjusted storage power, according to Fil+
requirement, 4 node is needed for redundancy, so the total quality adjusted storage power will be over 10 EB. This will
fulfil the over 75% of filecoin existing storage capability.

The value with the dataset will provide significant social value and scientific impact.

* Enable the scientist access data anywhere from the world
* Lower the cost of computing networks provide by the community
* Contribution and social impact as NFT badge
* Open Data on Chain proof of existence
* Blockchain native data version tracking
* CID based content referring for less duplication of storage

![Scientific-Experiment-Dataset-Growth-2](https://user-images.githubusercontent.com/8363795/201775665-5a51cf99-072b-400e-b946-429ba9bf5f6b.png)

[Scientific Experiment Dataset Growth ](https://www.researchgate.net/publication/360559502_Query_Complexity_Based_Optimal_Processing_of_Raw_Data)

Since 2020, Filecoin Slingshot project has submitted over 100 PB data stored, however there are issues in the project:

- Project is leading by the Filecoin Foundation, we need a community driven data dao ecosystem as well
- Not enough incentive for data providers
- Data Schema is not stored decentralized
- Not a self sustainable system

In order to let the system become long-term sustainable, the project need a way to self running, it will use the fil+ as
the ramp up to kick off the project.

The challenge is coming from different aspects:

* Implementation of FEvm
* Tokenism and payment
    * Validation of the computing might be hard
    * Fake downloads for contribution points
    * Data transfer monitoring

### Data Provider

The data provider's dataset is public dataset, and it is hosted on Filecoin, but from the user survey lots of project
are
using IPFS, those parts is not provide by the filecoin protocol. The data schema should be persistent in filecoin as
well with a more robust design.

![img_1](https://user-images.githubusercontent.com/8363795/201775118-940a0328-7994-4f69-8a07-d96a2558ffb4.png)

<figcaption align = "center"><b>Fig.1 - Data schema/Model Storage</b></figcaption>

Use case:

[Fogmeta Chainsnap](https://github.com/FogMeta/chainsnap)

``` 
Chainsnap is a project for maintaining blockchain snapshots.This project enables the storing and retrieval of snapshots for blockchain projects including Filecoin, Polygon, Ethereum, Binance Smart Chain, and Near.
```

### Data consumer

Data Consumer is the core part of the Data Dao ecosystem. Data consumer is the user who fetch and use the data.They can
be DAPP developers, scientist and other users. Storage providers can also be a data consumer if they incentive by fil
plus.

Data consumer may need other resource than storage.

**Case 1 - Data computing**

Users do not have a powerful machine locally, so they want to get a resource from the DAO netowrk.

**Case2 - Low latency Data Accessibility Globally**

CDN is needed for some dataset when doing international research.

### Storage Provider

Storage providers are the heart of the network. They earn FIL by storing data for clients and computing cryptographic
proofs to verify storage across time, and they earn rewards for adding new blocks of data.

If a storage provider relies on Fil+ to get rewards, it essentially also a data consumer, as a data consumer, he
should pay for the data downloading fee. Currently, the storage provider benefits all the revenue from the dataset. The
incentive layer is not directly pass to the data provider.
![img_5](https://user-images.githubusercontent.com/8363795/201775194-0c0a06de-9158-4979-b1a6-0645c5e925f2.png)

### Other Resource Provider

Bandwidth and computing provider is considered as other resource provider. It is based on an order book format design
and
order matching on-chain.

Typical Resource Vendor:

* Bandwidth
    * Saturn
    * Helium
    * Pocket Network
* Computing
    * Akash
    * Bacalhau
    * etc.

A governance and arbitrage system is needed. Reputation system decides the changes of bid wining rate.

Storage provider can also be other resource provider if they qualified for the Service Level Agreement.

### Milestone 1 Project setup with scope and architecture |1 week

* define the goals and scope of the project
* define the acceptance criteria
* define the user scenario
* define the components and specs
* document the design and workflow

### Milestone 2 Login,Dataset, model and space | 10 week
* User can connect to his metamask wallet from UI
* User can create a workspace
* Dataset upload and model management
* User can manage his workspace and integrate the dataset and model

### Milestone 3 Computing and Network Sharing | 10 week

* User can compute their data and model with metamastk
* The computing resource are from Filecoin network

### Milestone 4 SDKs for project integration | 8 week

* Devs can use golang sdk for making payment
* JS will be in Phase 2, since we believe this will be a multi phases project

### Milestone 5  DAO Governance for the token fund maintenance | 8 week

* Revenue sharing
* Init members sign keys
* define the policy of adding and remove member from the board

### Milestone 6. Release document and marketing | 2 week

* Testing in alpha group
* Document creation
* Workshop and marketing

## Total Budget Requested

| Milestone | Description                                | Time(Weeks) | Developer &Managers | Budget           |
| --------- | ------------------------------------------ | ----------- | ------------------- | ---------------- |
| 1         | Project setup with scope and architecture  | 1           | 2                   |  $      4,000.00 |
| 2         | Login,Dataset, model and space             | 10          | 4                   |  $    80,000.00  |
| 3         | Computing and Network Sharing              | 10          | 4                   |  $    80,000.00  |
| 4         | SDKs for project integration               | 8           | 4                   |  $    64,000.00  |
| 5         | Payment DAO for the token fund maintenance | 8           | 4                   |  $    64,000.00  |
| 6         | Release document and marketing             | 2           | 1                   |  $      4,000.00 |
|           | Total                                      | 39          |                     |  $  296,000.00   |
## Maintenance and Upgrade Plans

All FilSwan developed product has more than 24 months supporting plan and the maintenance is global support in both English and Chinese. 
We followed 2 weeks agile development cycle and releases every 4 weeks.
As a self-sustained DAO project, it will be live for a long time without extra development funding.

# Team

## Team Members

**  Core Team **
Charles Cao | Architect
Founder of FilSwan,the ambassador of Filecoin, mentor of Techstars accelerator, OG player of Web3. He is working closely with numerous leading hardware providers, government, web3 blockchain communities, analysts, and investors in the space.

Daniel Wang | Development Manager
More than 6 years of experience in software development and management, and 3 years of successful entrepreneurial experience. Bachelor of Software Engineering, Nanchang University, Master of International Business Administration of the University of Poitier. Founder of beelant.com; Operated BTC, ETH, Filecoin and other mining business, with a scale of over $50 million.  Non-front-end full stack engineer, multi-computer language, including back-end, big data, algorithm and maintenance, etc. 

Rishabh Thaney | Blockchain Developer
He is an MS CS student at McGill University and an adept software developer with demonstrated experience of more than 4 years in the blockchain field. During this time he won prizes at some of the biggest hackathons organised by ETHGlobal, InOut and SIH, has worked for the following companies: XMargin Inc. (now Credora), DeFiner Inc., Blockchain Foundry, MIT Digital Currency Initiative, Google Summer of Code, Globallogic and has also made projects for Consensys and PwC as well as other personal projects which can be found on his GitHub profile.
He strongly adheres to the idea of a 'trustless borderless economy' and also loves to share his profound thoughts on the same by taking sessions and keynoting at blockchain events.

Aayush Simkhada
He is a software engineer working at Filswan as a Developer Advocate. He is very passionate about Web3, Crypto, Blockchain, and everything in between.
 
Ricky Yuen | Blockchain Developer
Graduated from the University of Toronto. As a web3 enthusiast, Ricky has participated in ethglobal hackathon, hackmoon, and chainlink. Working on several defi and cross-chain projects and also token generation events. His major skill set it solidity and js.

**Advisor from Protocol Labs**: Xilin, Wes Floyd 

## Team Member LinkedIn Profiles

- [Charles Cao](https://www.linkedin.com/in/charles-cao-09a79526/)
- [Aayush Simkhada](https://www.linkedin.com/in/aayush-s-88b698202/)
- [Rishabh Thaney](https://www.linkedin.com/in/rishabhthaney/)
- [Ricky Yuen](https://www.linkedin.com/in/yuenricky/)

## Team Website

http://lagrangedao.org

## Relevant Experience

We - FilSwan Canada participated in SR1, SR2, and cooperation with starling and pinata project. In slingshot 2 we
processed over 10,000 deals and over 500 offline deals, talked to 100 miners and actively working data transfer service
between Asia and North American users. Prior to working on Filecoin project, we were working on a decentralized AI
computing platform which using smart contract for data/task transmission to different AI workers, we have in hand
experience of handling encryption and data pipeline.

We are building the following product

-  FilSwan
-- 7K deals/day
-- 10 PB Storage

- multichain.storage
-- 8K wallets
-- 10K CIDs

- Swan Provider
-- 200 SPs

- Filecoin Devgrant 7: S3/Filecoin integration
- [filswan-chainlink-filecoin-joint-grant](https://blog.chain.link/filswan-chainlink-filecoin-joint-grant)

The team get the following reward and honor.

- The Natural Science and Engineering Research Council of Canada (NSERC) special fund supports research on the direction of video coding.
- Canadian government high-tech research and development grant
- Natural Science Foundation of Canada (NSERC) Blockchain to AI Cloud Computing Research Grant
- Canadian Information Technology and Integrated Systems Mathematical Organization (Mitacs) AI medical identification
  project grants
- Canadian tax support for scientific research and experimental development
- Quebec e-commerce innovation enterprise support
- CENGN (Canadian Center of Excellence for Next Generation Networks) Research Support Project
- Canadian D3 incubator Hosted Startup support
- Microsoft Entrepreneurship Support Program (BizSpark) Support
- HP Enterprise Supplier Partner, Dell Enterprise Supplier Partner, ASUS Enterprise Service Partner, Amazon Enterprise
  Partner, NVIDIA Canadian Cloud Computing Supplier

## Team code repositories

https://github.com/lagrangedao

# Additional Information

ccao@nbai.io

**Comment by max1015070108** [comment]
as an SP,we would like to support this project.

**Comment by spark8899** [comment]
As a developer, we would like to use the dataset for development

**Comment by woshidama323** [comment]
As a developer and an SP, we would also like to support this project

**Comment by jamesyu1999** [comment]
As an SP, we definitely support this project.

**Comment by nickboot** [comment]
as an SP,we would like to support this project

**Comment by Icarus9913** [comment]
As a developer, we would like to use the dataset for development

**Comment by GuiPulp** [comment]
As a developer and an SP, we would also like to support this project

**Comment by jnthnvctr** [comment]
How does access management happen here? Or I guess framed another way - how does one manage: 
a) the flow of funds (to ensure payment is actually flowing back to the DAO) 
b) if the CID is embedded in the NFT, how does one prevent the first user (who might pay) from reselling at a cheaper price by just storing and serving the data themselves? 

Is the data getting encrypted / re-encrypted on reads?

**Comment by flyworker** [comment]
> How does access management happen here? Or I guess framed another way - how does one manage: a) the flow of funds (to ensure payment is actually flowing back to the DAO) b) if the CID is embedded in the NFT, how does one prevent the first user (who might pay) from reselling at a cheaper price by just storing and serving the data themselves?
> 
> Is the data getting decrypted / re-encrypted on reads?

a) The fund is a smart contract based on FEVM, when the result is validated the fund will be sent to the different parties after unlocked.
b) This is not just a problem of dataset but also the problem of the entire NFTs industry, the IP of the data property is a grey space on the legal side, however, the first one who mints the dataset CID as an NFT will have advantages on the legal side. The user might be able to resell and serve data, but they cannot benefit from the cooperation and benefit from the Lagrange community.

We did not provide Data encryption for v1

**Comment by flyworker** [comment]
Project Update:
Milestone 2:
Creating dataset with IPFS is done. You can test create a dataset here
http://lagrangedao.org

**Comment by ErinOCon** [comment]
Hi @flyworker, thank you for the update! We are hoping to have more information available soon regarding this review. In the meantime, can you provide an MVP under $50k for this work? Also, can you briefly describe how you plan to onboard your first 5 users?

**Comment by flyworker** [comment]
Hi  @ErinOCon,
Thanks for your advice. We update the work within an MVP with the following milestones and budget.

### Milestone 1 Project setup with scope and architecture |1 week

* define the goals and scope of the project
* define the acceptance criteria
* define the user scenario
* define the components and specs
* document the design and workflow

### Milestone 2 Login, Dataset and space | 10 week
* User can connect to his metamask wallet from UI
* User can create a workspace
* Dataset upload and management

### Milestone 3 Computing and Network Sharing | 10 week

* User can compute their data and model with metamastk
* The computing resource is from Filecoin network

### Milestone4. Release document and marketing | 2 week

* Testing in the alpha group
* Document creation
* Workshop and marketing


## Total Budget Requested

| Milestone | Description                                | Time(Weeks) | Developer &Managers | Budget           |
| --------- | ------------------------------------------ | ----------- | ------------------- | ---------------- |
| 1         | Project setup with scope and architecture  | 1           | 2                   |  $      4,000.00 |
| 2         | Login,Dataset and space             | 10          | 4                   |  $    20,000.00  |
| 3         | Computing and Network Sharing              | 10          | 4                   |  $    20,000.00  |
| 4         | Release document and marketing             | 2           | 1                   |  $      4,000.00 |
|           | Total                                      | 23          |                     |  $  48,000.00   |

We have talked to about 20 users on the user case side and got very positive feedback. We hereby list 5 users answer below:

### Storage Providers
We have talked with **Dcent** and **Origin Storage**, as an SP they are very interested to get data stored to provide storage power and computing resource in Asia, the EU and NA.

### Data Provider
**Ocean protocol**, *Slingshot V3 moonlight*  confirmed the interest in listing their data as a dataset provider

### Space User
 **ITOKA** is confirmed interest in using Space as their working space for their music NFT downloading
**bacalhau**  confirmed interest in using Space for computing cases e,g, stable diffusion,

**Comment by ErinOCon** [comment]
Hi @flyworker, thank you so much for your time with this proposal and for your patience with our review. I know it has been a considerable amount of time since your original submission. 

Unfortunately, we will not be proceeding with a grant at this time. We look forward to learning of your project progress and are wishing you all the best as you continue to build!
