### ISSUE TITLE
Next Step Microgrant: Web3 Filecoin/IPFS CMS Package

### ISSUE THREAD

**Issue by okhaimie-dev** [filecoin-project/devgrants#1140]
### 1. What is your project? (max 100 words)

This is a web3 content management system which stores its media files such as posts, thumbnails using Web3.storage and banks on polygon as the blockchain layer. We then expect CMS users to leverage the Graph protocol to query the content.

### 2. Project links
  
Link to Github repo:[ https://github.com/Jarvis-Nu/web3-cms](https://github.com/Jarvis-Nu/web3-cms)
Link to demo or website, if applicable:[ https://web3cms.vercel.app](https://web3cms.vercel.app/)
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Our project uses Filecoin/IPFS as the data storage and retrieval layer with the aid of Web3.storage javascript library.
This project stores its thumbnails and post media on Filecoin.

  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

This grant will give us the wiggle room to experiment further on a more robust application with filecoin/IPFS in our CMS application. Our plan is to further improve the CMS dashboard to allow further integration, a better UI/UX, and also publish an npm package.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
**Victor Omorogbe,**
Email: [victoromorogbe69@gmail.com](mailto:victoromorogbe69@gmail.com)
Github: https://github.com/supreme2580
Role: Fullstack Dev
**Okhai Omotuebe,** 
Email: [oktonystark8@gmail.com](mailto:oktonystark8@gmail.com), 
Github: https://github.com/okhaimie-dev
Role: Fullstack Dev
**Eniola Ajiboye,**
Email: [ajiboyeniola@gmail.com](mailto:ajiboyeniola@gmail.com)
Github: https://github.com/Ajiboyeniola
Role: UI/UX
* How did you learn about our microgrant program?
Learned about the grant after my team won a Web3.storage prize at an ETHGlobal hackathon 2 months, unfortunately we didn’t want to continue with that particular project.
* If your project was created as part of an event or hackathon: 
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
  N/A

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
