### ISSUE TITLE
Next Step Microgrant: ProtoDapp

### ISSUE THREAD

**Issue by IntergalacticDotDev** [filecoin-project/devgrants#1141]
### 1. What is your project? (max 100 words)
Installable Protodapp with NextGen Storage via IPFS & w3ui with web3.storage service for storing content addressed IPLD data on IPFS and Filecoin.

### 2. Project links
  
Link to Github repo: https://github.com/IntergalacticDotDev/protodapp 
Link to demo or website, if applicable: https://protodapp.dev/ 
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
It's built with w3ui components and Preact.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
This grant will extend development time to experiment further on more applications that use the web3.storage service for storing content addressed IPLD data on IPFS and Filecoin.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Klaas de Vries 
info@protodapp.dev
https://github.com/IntergalacticDotDev
Dev
* How did you learn about our microgrant program?
Social media
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @IntergalacticDotDev, we will not proceed with a grant for this project. Thank you for your interest in the grants program.
