### ISSUE TITLE
Digital Persona

### ISSUE THREAD

**Issue by petragor** [filecoin-project/devgrants#1143]
### 1. What is your project? (max 100 words)
An avatar creator that will include accounts and storage for each personal avatar. Based on their inputs, the users will be able to create 3D avatars and gain access to their personalities. Finally, they will be able to mint their avatars or export-import them, connecting them to different clients. 

### 2. Project links
Not yet.
  
Link to Github repo: https://github.com/Artificial-Leap/Digital-Persona

Link to demo or website, if applicable: I don't have yet.
License: MIT
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
We will use IPFS to store 3D models.
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Raising funds to be able to work full-time on this project.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
No
  
### Additional questions:
Lead Engineer: https://github.com/alextitonis
We've learnt it through Discord

**Comment by ErinOCon** [comment]
Hi @petragor, it looks like this project is in the very early stages of building. For next steps, I would recommend participating in a [hackathon](https://hackathons.filecoin.io/). This is a great way to showcase building progress and a working prototype!

Thank you for your interest in the grants program!
