### ISSUE TITLE
SolarFi – An Innovative Sustainable Blockchain Solution for Solar Energy

### ISSUE THREAD

**Issue by SolarFi2022** [filecoin-project/devgrants#1144]
# Open Grant Proposal: `SolarFi – An Innovative Sustainable Blockchain Solution for Solar Energy`

**Name of Project: SolarFi

**Proposal Category:** `app-dev`

**Proposer:** `SolarFi`

**(Optional) Technical Sponsor:** ` `

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** `Yes`

# Project Description

SolarFi is a new, innovative web3 solution that advance sustainable energy and mobility to the world through blockchain technology and Filecoin decentralised storage.

SolarFi identifies sun-soaked areas in Australia(and potentially the world) where solar panels could be at their most efficient, then sells the modules to private investors who can then lease them to local schools and businesses. This business model ensures that local communities are able to benefit from cheap, clean energy whilst investors help fund and develop several projects that will generate income for the twenty years that solar panels are viable. All transactions can be processed in crypto simplifying international monetary transactions, and SolarFi uses blockchain-based smart contracts as well as Filecoin decentralised storage to reduce the needs and cost of physical administration and paperworks.

SolarFi acts as a crowdfunding platform for small to medium-scale solar projects allowing investors worldwide to help fund plants with national currency or crypto payments. 

SolarFi is accessible from a web portal and backend infrastructure platform will be hosted on both public cloud integration with blockchain and decentralised secured Filecoin storage for storing customer documents, transaction details, which allows data analysis on payment history performance and project rating scores, etc.

SolarFi requires each user to establish trustworthy personal digital identity, with uploaded documents stored in Filecoin.

## Value

The consultancy Deloitte estimates that unchecked climate change could cost the global economy US$178 trillion over the next 50 years. One of the major contributors to the climate change is the generation of electricity from fossil fuel power plants.

Generating electricity from solar panels produce no greenhouse gases whatsoever, and so can help to reduce the effect of climate change if used widely.  With solar energy powering a home or business, there is no burning of fuel and no emissions from energy production.

Solar dramatically reduces carbon emissions and air pollution, and it’s also quickly becoming the most affordable source of electricity. However, financial obstacles continue to hinder solar adoption, especially in emerging markets. 

SolarFi aims to provide a peer-to-peer solar leasing platform through which, anyone, anywhere in the world, can own solar energy-producing cells and build wealth by leasing those cells to power businesses and organisations in emerging markets.

This is achieved by leveraging technology innovations such as blockchain smart contract and decentralised storage Filecoin (i.e. Co2.storage).

The benefit of SolarFi using Filecoin decentralised solution is the security and transparency of a reliable trusted storage for transaction histories. The benefit to Filecoin as part of the solution is the potential of large market user adoption and transaction volume the product can bring to Filecoin ecosystem.

SolarFi solution would require secure storage when uploading and storing approved solar credit documents as well as other data related to the specific solar projects. The documents should be available for reading, unable to be tempered and stored for a long time (30+ years). We are looking for a fully decentralised storage solution and Filecoin Co2.storage appears to be the perfect fit for our solution.

# The risks if we don't get it right:

The risk if we don’t get it right is we might not attract the forecasted user adoption rate initially has expected.

# Risks likely to make project execution difficult:

User adoption difficulties from less technology savvy communities.

## Deliverables

SolarFi will deliver a web portal allows users to perform transaction related tasks:

-	Connect and fund wallet
-	Create user profile & upload ID documents
-	Browse potential solar projects
-	Buy solar cells from chosen projects
-	Receive regular payments from installed projects based on the solar output 

We will leverage the free and secured NFT.storage from Filecoin to store transactions and ID documents

### Milestone 1 - INFRASTRUCTURE SETUP, WEB FRONT-END UI DEVELOPMENT:
-	Design and complete cloud web server & application server hosting infrastructure setup. A web hosting solution is required for our webapp which then will be fully integrated with blockchain and FileCoin platform.
-	The web server infrastructure will be hosting our web application
-	The application server infrastructure will be hosting smart contract and storage operation application.
-	Set up front-end web portal home page and user interface.

Duration: 1 month

### Milestone 2 - Filecoin integration for ID document storage and transaction storage.
-	Filecoin storage integration (CO2.Storage) to allow uploading user ID documents and storing transactions data such as solar generation data and other associated data.
-	Blockchain backend setup and integration with Filecoin.
-	Smart contract development.

Duration: 1 month

## Total Budget Requested
USD$45,000

## Maintenance and Upgrade Plans

We will provide industry standard SLA support for all maintenance & upgrade plans.

# Team

## Team Members
Jack Hui – Founder and Front End Developer
Benjamin Russell – Full Stack Blockchain Developer

## Team Member LinkedIn Profiles
https://www.linkedin.com/in/jackhui88/
https://www.linkedin.com/in/benjamin-russell-856392245/

## Relevant Experience

Jack Hui
A very passionate and experienced technologist who enjoys designing and implementing elegant designs that help achieve strategic business and human objectives. Practical knowledge in software development best practices and excellent communication skills. Hands on experiences in developing web-based applications and experiences with solidity, NFT's and other cryptocurrency technologies. Experiences in building micro services-oriented blockchain infrastructure and nodes.

Benjamin Russell
Benjamin was part of a dynamic team building applications on Ethereum and Bitcoin Blockchains writing Smart Contracts. End to end Cryptocurrency development and launch. Initial Coin Offering (ICO) strategy, development, consulting and advising.
Vast experience of setting up cryptocurrency full-node servers as well as easily work with any third party integration like Blockchain API, Coinbase API, Mycelium API, Bitgo API, Bitcoin Daemon, Ethereum, PM, alt coin and financial API's. Special knowledge to maximize the security of cryptocurrency based platforms. Strong implementation in enterprise level security with public and private keys, hash and signature encrypted service.

## Team code repositories
[https://github.com/SolarFi](https://github.com/RentFi)

**Comment by ErinOCon** [comment]
@SolarFi2022., thank you for your proposal. We will not be moving forward with a grant this round. Please feel welcome to apply for RFP opportunities in the future. Wishing your team the best as you continue building!
