### ISSUE TITLE
Next Step Microgrant: Phishing URL detection with IPFS

### ISSUE THREAD

**Issue by lewisg8** [filecoin-project/devgrants#1149]
### 1. What is your project? (max 100 words)
My project retrieves raw data from the Phishstats API endpoint. The data is cleaned and transformed into human readable notifications for phishing urls found on a given day. These notifications include phishing URL, originating IP address, and location of origination. 
The Gmail API is used to send a generated HTML file that outlines the various phishing URLs found for a given day. This cleaned information is then stored in IPFS.

### 2. Project links
  
Link to Github repo: https://github.com/lewisg8/Phishing-URL-detection-IPFS
Link to demo or website, if applicable: https://youtu.be/E6dxd_oRtKI
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
IPFS and web3 storage are used to store the cleaned data which I have generated. 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1.  Expand the coverage globally and not just in the US
2. Create RSS feed that updates daily with new phishing URLs through integration with my script
3.  Integrate the Twitter API to post daily updates of new phishing URLs
4.  Use the cleaned data I am storing in IPFSanalyzelyse phishing URLs and IP addresses and identify what companies are being targeted the most.
5. Incorporate more data fields from the API such as CVE and port vulnerabilities to add richer content

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Email: lewisgresham8@gmail.com , Github: lewisg8 , Role: Developer
* How did you learn about our microgrant program?
* I was using IPFS to store data in other projects and saw you had a microgrant program
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @lewisg8, thank you for your proposal! Before considering this proposal, we would like to review additional building progress. For next steps, I would recommend participating in a [hackathon](https://hackathons.filecoin.io/). Please let me know if you have any questions.

**Comment by lewisg8** [comment]
No problem thanks for the update Erin, will work on it more. Best
