### ISSUE TITLE
Hype Squad - Educational DAO

### ISSUE THREAD

**Issue by WojtasDAO** [filecoin-project/devgrants#1150]
# Open Grant Proposal: `Hype Squad`

**Name of Project:** Hype Squad

**Proposal Category:** Community

**Proposer:** WojtasDAO

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

We are building the first polish DAO community around blockchain and Web3 technology on various social media channels - Twitch, Discord, Twitter, etc. The main idea is to bring blockchain closer to the people, and at the beginning, members will not know that they are using blockchain to form, vote, and decide about the community's future. So the first part is to make the community use blockchain technology without knowing it's some new technology.

I agreed with Warsaw government entities to host around 1h presentation in 100 high schools in Warsaw about Web3 - it will be the leading way to reach out to new DAO members and future blockchain users at the beginning. It gives me around 500 students and 50 teachers reach per school - 55000 in total.
Lectures will start in January 2023.

The first acquisition of the members will be grapevine in the web3 community, the next presentation at schools, and giveaways. After we reach a certain point of members, we will start influencers marketing (lives, interviews, etc)

We are providing education and social investing opportunities with no obstacles to enter. In Poland, still, the language barrier is the strongest one to enter crypto and understand blockchain.

## Value

In Poland, there are a lot of people who want to enter the web3 world but the knowledge is really hard to find and we need more educational materials right now.
The main goal is education around: knowledge, career, business development, and investment. The project is set up for the long term, and we are presenting a plan for first 12 months.
Benefits:
- educated people ready to start work in web3 (developers, business managers, marketing, HR, PR, UX/UI etc.)
- Businessmen will have interesting opportunities and enter their existing business from web2 to web3
- New projects and initiatives in web3 because people will understand the idea and possibilities
- People start investing in web3 startups, tokens, NFT, Gamefi, DeFi, metaverse, new technology

## Deliverables

💎Deliverable #1 (monthly tasks)
Community building, education content creation, promotion.
 
📚 Distribution Channel and Frequency
* (60-90x) Twitter 
* (60-90x) TikTok
* (60-90x) Instagram 
 
🔗 Channel URL(s)
https://twitter.com/HypeSquadDAO
https://www.instagram.com/hypesquaddao/
https://discord.gg/jQngcvrUfu 

 
🎥 Content Format:
* (60-90x) Video
* (60-90x) Visual / Image
* (60-90x) Text Only
 
🍡 Type of Content:
* Promotional - News around web3
* Fact / Statistics - Near Statistics and Other Projects
* Editorial - Founder quotes 
* More
 
and
- Lectures in the 100 high schools in Warsaw
- Full DAO organization set up
- first community investment in the web3 project
- web3 talent acquisition server
- community launchpad (supporting community ideas)

## Development Roadmap

(https://docs.google.com/spreadsheets/d/1Y9c_UJsZOiqb6svSbYN5spvf-Kl1c1rRQamBmAifDaw/edit?usp=sharing)

The core team will take part in each of the milestones cuz everything we will do is for the community. The most difficult things connected with coding will be outsourced.

**Core Team:**
Michał Wojtas - Leader
https://www.linkedin.com/in/micha%C5%82-wojtas-i-nft-london-8b3b45193/
EXP: Fanadise/MAMNFT/Fancy Bears Metaverse/Star Heroes

Mikołaj Smereczyński - Marketing
https://www.linkedin.com/in/miko%C5%82aj-smereczy%C5%84ski-33bb9023b/
EXP: Fanadise/MAMNFT/Fancy Bears Metaverse/Star Heroes

Filip Mokrodulski - Video And Production
https://www.linkedin.com/in/filipmokrogulski/
EXP: Pareidolia / Fanadise / Fancy Bears Metaverse

Łukasz Olender - Acquisition
https://www.linkedin.com/in/lukaszolender/
EXP: Web3 Devs Poland/Wennect

Aleksander Wasielewski - Event / Project Manager
https://www.linkedin.com/in/aleksander-wasielewski-b3472256/
EXP: Fanadise/MAMNFT/Fancy Bears Metaverse/BIG idea

Magdalena Żuchowska - Community Lead
https://www.linkedin.com/in/emgiea/
EXP: Fancy Bears Metaverse

Zuzanna Jelska - Social Media
https://www.linkedin.com/in/zuzanna-jelska-693430156/
EXP: Fanadise/Fancy Bears Metaverse

## Total Budget Requested

(https://docs.google.com/spreadsheets/d/1Y9c_UJsZOiqb6svSbYN5spvf-Kl1c1rRQamBmAifDaw/edit?usp=sharing)

We need $15k for the first year, and after this time, we will develop a business model to sustain the project.

## Maintenance and Upgrade Plans

In the long term, we want to create a DAO 2-layers system for the community. Social investing and social launchpad are also 2 things that we want to develop more in the future of the project, as well as community services.

# Team

## Team Members

Michał Wojtas - Leader - 
Mikołaj Smereczyński - Marketing
Filip Mokrodulski - Video And Production
Łukasz Olender - Acquisition
Aleksander Wasielewski - Event / Project Manager
Magdalena Żuchowska - Community Lead
Zuzanna Jelska - Social Media

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/micha%C5%82-wojtas-i-nft-london-8b3b45193/
https://www.linkedin.com/in/miko%C5%82aj-smereczy%C5%84ski-33bb9023b/
https://www.linkedin.com/in/filipmokrogulski/
https://www.linkedin.com/in/lukaszolender/
https://www.linkedin.com/in/aleksander-wasielewski-b3472256/
https://www.linkedin.com/in/emgiea/
https://www.linkedin.com/in/zuzanna-jelska-693430156/ 

## Team Website

https://fanadise.com/
https://www.goslinggaming.com/
https://www.fancybearsmetaverse.com/
https://starheroes.io/
https://web3devs.pl/
https://www.big-idea.eu/ 

## Relevant Experience

Michał Wojtas - Leader
EXP: Fanadise/MAMNFT/Fancy Bears Metaverse/Star Heroes

Mikołaj Smereczyński - Marketing
EXP: Fanadise/MAMNFT/Fancy Bears Metaverse/Star Heroes

Filip Mokrodulski - Video And Production
EXP: Pareidolia / Fanadise / Fancy Bears Metaverse

Łukasz Olender - Acquisition
EXP: Web3 Devs Poland/Wennect

Aleksander Wasielewski - Event / Project Manager
EXP: Fanadise/MAMNFT/Fancy Bears Metaverse/BIG idea

Magdalena Żuchowska - Community Lead
EXP: Fancy Bears Metaverse

Zuzanna Jelska - Social Media
EXP: Fanadise/Fancy Bears Metaverse

Each person in the core team used to work with me. Each person has different types of skills and is dedicated to tasks that they do the best. Each of them we have experience in the web3 industry. The team is here to deliver.

## Team code repositories

All the things connected with the dev we will source cuz we will 
[The First DAO Polish Community.pdf](https://github.com/filecoin-project/devgrants/files/10055567/The.First.DAO.Polish.Community.pdf)
not need full-time support from the dev cuz we are community focused on education. But if dev services, website creation, dao, etc., these dev things can also include the grant, it will be awesome.

# Additional Information
gitcoin media 
e-mail: michal@mamnft.io

**Comment by ErinOCon** [comment]
HI @WojtasDAO, thank you for your proposal. We will not be moving forward with a grant at this time, but would highly recommend checking out [Orbit](https://orbitcommunity.filecoin.io/) for additional opportunities!
