### ISSUE TITLE
RFP Application: FaucetFil, Generic FVM Faucet

### ISSUE THREAD

**Issue by brymut** [filecoin-project/devgrants#1153]
# RFP Proposal: `FaucetFil - FVM Faucet`

**Name of Project:** FaucetFIl

**Link to RFP:** [/rfps/fvm-open-tools-infra.md](https://github.com/filecoin-project/devgrants/blob/9daa0c8295f06ba6551b18b06c2e0e8261c2725b/rfps/fvm-open-tools-infra.md?plain=1#L39)

**RFP Category:** `app-dev`

**Proposer:** `brymut`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes

# Project Description

With FVM development currently underway and builders from the community working towards building for FVM, a key need will arise for users and developers to have test tokens in their wallets for testing and new user-onboarding. This project provides a way for project maintainers/developers to easily configure and deploy their own faucets for contracts deployed on public testnets.

The FaucetFil project is a free and opensource, generic, white-label solution for FVM projects to deploy and provide a way for their community members to obtain test tokens. Built using Nextjs, Tailwind and Redis, projects can easily configure/modify and deploy a frontend faucet, either on their own infrastructure that supports node or on affordable/free platforms like Vercel. This template will come with an unopinionated style for interested projects to add on top of to apply their own brand. There will also be an element of Sybil resistance, the project will also come with login options such as Github OAuth and other centralized identity providers, to uniquely identify users and limit token provision to help prevent system abuse.

I anticipate that the value add here will be towards the general Filecoin developer/testing community and will alleviate a lot of the time consumption that comes with Test coin distribution. 

### Architecture

<img width="706" alt="Screen Shot 2022-11-21 at 3 08 35 PM" src="https://user-images.githubusercontent.com/14836056/203053156-250b77a1-fad2-4e77-89d9-f3ba70bd4a0c.png">

### Configuration

To ensure its generic nature & simplicity in configuration, we shall use 3 main modification methods:

- **.ENV configuration file** - To configure various settings that are required for reaching various endpoints and other uses around the template. A few config variables to include would be: `TOKEN_LIMIT`, `TOKEN_LIMIT`, `WAIT_PERIOD`, `REDIS_ENDPOINT`, `TESTNET_NODE_RPC_ENDPOINT`, `GITHUB_CLIENT_ID`,  `GITHUB_CLIENT_SECRET`, `HOMEPAGE_LINK`, `BLOG_LINK`, `DISCORD_INVITE_LINK`,  etc
- **Markdown Files** - To have the project bio and instructions configurable
- **Tailwind.config.js** - To configure key branding attributes. e.g Colours, Font, etc

These as well as further configuration steps shall be outlined the accompanying documentation and tutorial article.

### Interface Wireframes

 - **Before Signing In**

<img width="441" alt="Screen Shot 2022-11-21 at 3 16 43 PM" src="https://user-images.githubusercontent.com/14836056/203053239-8b15be3b-109b-4089-b06f-16c195b90d26.png">

 - **Requesting Tokens**

<img width="426" alt="Screen Shot 2022-11-21 at 3 16 51 PM" src="https://user-images.githubusercontent.com/14836056/203053259-d3e462d8-f8d9-4d7b-a1ff-2239a57a75ad.png">

- **Limit Reached**

<img width="417" alt="Screen Shot 2022-11-21 at 3 16 59 PM" src="https://user-images.githubusercontent.com/14836056/203053286-0fcfa264-448c-486a-8a63-79451201146b.png">

## Development Roadmap
This project will be handled by 1 full time project member, in approximately 4 weeks, split across 2 Milestones

### Milestone 1 - Design and Implementation

 - Design & Development of the generic user interface using Nextjs and Tailwind with key areas around UI being being configurable using ENV variables, tailwind.config.js and Markdown files as outlined above in the configuration section.
 - Implementation of Authentication using OAuth to support Sybil resistance 
 - Implementation of a user status checking function using Redis as storage
 - Based on the step above, another function to determine if the user logged in is eligible for a predefined provision of test tokens and sending the test tokens from the Faucet's wallet to the user's wallet.
 - Unit testing coverage for the core functionality outlined above.

### Milestone 2 - Documentation, Test Instance release and Article Tutorial

- Inline documentation as well as deployment & testing instructions will be provided 
- A test instance of the Faucet project in action for users to get a feel for how the faucet should run and look
- Article/Tutorial combo describing the project, its intent and how it can be used by developers using a small tutorial  walking through the reader on how I deployed the test instance.

## Documentation, Education, and Community

Accompanying documentation, article and tutorial is described in Milestone 2 above.

## Milestone Summary

| Milestone No. | Milestone Summary & Staffing | Funding | Estimated Timeframe |
| ------------- | --------------------- | ------- | ------------------- |
| 1             | Design and Implementation, 1 FTE     | $4700      | 3 weeks             |
| 2             | Documentation, Test Instance release and Article Tutorial, 1 FTE    | $1600      | 1 week             |

## Total Budget Requested
$6300

## Maintenance and Upgrade Plans

- **Maintenance**: such as critical bugs and security updates
- **Project Upgrades**: Implementing FVM community suggestions/feedback on features that could help improve the experience of both deploying and using the project.

# Team

- **Bryan Mutai** : Full-Stack developer and web designer

## Contact Info

- **Name:** Bryan Mutai
- **Email:** mutaiwork@gmail.com

## Team Members

- Bryan Mutai - [Github](https://github.com/brymut) and [LinkedIn](https://www.linkedin.com/in/bryanmutai)

## Relevant Experience

I studied software engineering at the University of Glasgow, I currently have 5 years experience in web design & development and have been working as a freelance web developer, working in various programming languages (Typescript/Python) and in various frameworks and libraries (React/Angularjs/Django). Over the past 2 years I have also been contributing towards various blockchain related opensource projects. Recently in particular:

- Designed & built a Voting Delegation Dashboard for the APWine DAO using React/Typescript/Tailwind - https://vote-delegation-dashboard.vercel.app/
- Contributions to the Shapeshift Web App & related KeepKey hardware wallet features. - https://github.com/shapeshift/web/commits?author=brymut
- Integrating price data for Superfluid tokens into the Gnosis Safe web app backend - https://github.com/safe-global/safe-eth-py/pull/381
- Added support for Zora NFTs viewing & the Celo blockchain onto the Mask.io browser plugin - https://github.com/DimensionDev/Maskbook/commit/810999f38a09df8d5cefb490b4ca475b837458bc & https://github.com/DimensionDev/Maskbook/commit/c5cfdf393baf6cf7997f66cbabc5e5952dc8cb4d

**Comment by eshon** [comment]
Hi @brymut! Our testnet infrastructure already includes a faucet. But your skillset looks great for building an FVM dapp! Checkout the FVM Request for Startups here: https://rfs.fvm.dev/ for ideas on what to build. We encourage you to apply for an FVM Microgrant: https://spacewarp.fvm.dev/ to build something.

**Comment by brymut** [comment]
Thank you for your feedback and consideration @eshon. I'll consider your suggestion and get back with a new application in the new year. Happy holidays! 🎉
