### ISSUE TITLE
Next Step Microgrant: Afriverse

### ISSUE THREAD

**Issue by jbrit** [filecoin-project/devgrants#1155]
### 1. What is your project? (max 100 words)
Afriverse is a community driven web3 education platform for africans by africans. We incentivise learning and the upload of quality content by rewarding our learners with tokens for each course completed, and rewarding the content creators with tokens. This ensures creators always aim to create more quality content, and that learners aim to learn more. Our token AFCT also serves as a governance token, and as the platform grows it would be used in making more key decisions by the community.

### 2. Project links
  
Link to Github repo: https://github.com/jbrit/afriverse
Link to demo or website, if applicable: https://youtu.be/wIPaCWy_T44
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
NFT.storage is used to power all the NFTs generated & used on our platform. Right from the Soul Bound Token generated from worldcoin to the NFT certifications given to users.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Currently, the Afriverse team needs more to improve the user experience on the platform consequently the fund would go into:
Paying for a redesign of the platform, including newer features. Paying for the implementation and shipping it to a new domain.
For our custom platform NFTs, we would need to work with Artists to improve the currently look & feel of these NFts.
We would also need the fund to support storage costs of the platform.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, I agree to do this.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Ajibola Ojo
Email: pro.ajibolaojo@gmail.com
Github: https://github.com/jbrit
Role: Founder/Blockchain Engineer

* How did you learn about our microgrant program?
I learnt about it via email

* If your project was created as part of an event or hackathon:
  * What was the name of the event?
     1, 2, Web3 Hackathon - Moralis x Filecoin 2022 Hackathon.
  * Please link to your hackathon submission
     https://afrivese.ajibolaojo.com/

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
