### ISSUE TITLE
Research and implementation of an IPFS based open data Platform and API for short term lease price movements

### ISSUE THREAD

**Issue by sideris** [filecoin-project/devgrants#1156]
# Open Grant Proposal: `Fund the research and implementation of an IPFS open data Platform and API for short-term lease pricing`

**Name of Project:**
Open data Platform and APIs on short-term lease prices that can be used by everyone

**Proposal Category:**
`app-dev`

**Proposer:** `sideris`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Please respond with either "Yes" or "No"

`YES`

# Project Description

There is no open-source data about short-term rental prices and resales.  This creates opaqueness on what should be an open market and many pricing disparities. 

**We want to open source the unique data that is the pricing of resales of leases on any region, date, and property type. This set of data does not exist and the creation of this asset class was pioneered by TripsTrade.** 

We have already built an open system on-chain where renters and investors can buy and resell their STR Leases.

We will provide an open data market and dashboards for everyone to check how lease prices move over time and over regions.

Some examples where this data will be useful:

**As a traveler**
Imagine going to Airbnb or Booking.com and seeing the prices for your trips. Imagine that you know there is a Dashboard where you can see that if you book these places in 5 days you will get a better price based on historical data.

**As an investor**
You want to speculate on property leases in a certain area. By scouring through the data you can identify the opportunity where the historical prices are higher than current prices in that certain area.

**As a property owner**
A common mistake many property owners that lease their property is that they misprice their places. You want to have really accurate data on how to price your property at a specific period compared with similar properties.

## Value

This data will provide visibility to retail and sophisticated investors as well as property funds as to how price move closer to the check-in date. We will use FileCoin and IPFS more specifically in two ways:

* Store the metadata for the leases
* Store the time series for each region, type of property, length of lease

Thousands of people will be able to access this public data via Filecoin's solid network.

Should we deliver this:

* We create a new data market, that doesn't exist right now and can be leveraged by property owners, renters, and speculators
* We can create business opportunities for anyone that wants to use this data to provide specific or in-depth analytics.
* Travelers, property owners, funds, and speculators can benefit by accessing this data.

If we don't get it right then the decisions that investors or retail lease traders can make will be misinformed and if it scales it will create short-term pricing imbalances in our user's markets.

The only major risk we see going forward is not having JIT (just in time) data as we are just getting started with our marketing efforts. However, we have good data on our test network and we will use this to build the platform to be ready once we do our marketing push.

## Deliverables

* Software Services to collect on-chain data from resales and upload to IPFS
* APIs to read this data filterable by region, time period, property type, price range
* Dashboards to explore data if one does not want to use the APIs
* Readable data on IPFS for everyone to use

(stretch goal financed by us): Integrate the API for pricing on our second product; LeaseLabs to provide relevant and useful pricing information for property owners and investors.

#### Hire a mid-level Software Engineer(s) or re-purpose one of our developers
This is a necessary step that will require allocating resources to ensure success and delivery. The person responsible will work very closely with the CTO.

The cost will vary but we intend to allocate around $70000 on this. By targeting the right markets we can hire more than one. 

Expected dates: January 2023 -> Feb 2023

#### 1. Build Software Services that read and analyze our on-chain data
In the first month, we will focus on reading and analyzing the right format of data that is needed to make the right decisions for any user of the platform. 

Since we already have the data on-chain we will need to understand how to load, manipulate and enrich those datasets. 

The cost will be around $1000 for services and software costs.  (1 backend dev, CTO as PM and Dev Manager)

Expected dates: Mid February 2023 -> Mid March 2023

#### 2. Build Software Services that upload this data on IPFs
This is expected to take two weeks to a month. We will need to deploy scalable services that can continuously load and transform data as per 2). Given we have done the research we will just need to build these functionally simple services. 

The cost will be around $2000 mainly for DevOps consulting. (1 backend dev, 1 DevOps contractor, CTO as PM and Dev Manager)

Expected dates: Mid-March 2023 -> End of March 2023

#### 3. Build a front end that consumes this data and provides useful dashboards
This is intended for our less tech-savvy users (e.g travelers and some property owners) that just want to explore the data. This is expected to take anything between 4 and 8 months. 

The cost will be around $20000 (1 front-end contractor, 1 DevOps contractor, CTO as PM and Dev Manager, 1 backend dev)

Expected dates: April 2023 -> November 2023

#### 4. Build a scalable API for external users to consume the data
This is the platform that institutional users will use. For example, our second product (LeaseLabs) will use this data to inform property owners how much to price their leases for presale and investors what is the fair price value and expected returns of the leases being sold based on historical data.

The cost will be around $30000 (2 backend devs, 1 DevOps contractor, CTO as PM and Dev Manager)

Expected dates: April 2023 -> November 2023  (same dates as we want to build it on parallel)

## Total Budget Requested

`$123000`

`$70000`: 1 - 3 mid-level engineers for 1 year. The goal is to get them permanently onboard
`$30000`: DevOps, Backend and front end contractors (most cost on DevOps). Plus software services costs (Kubernetes, Load Balancers, Services, Databases, API keys)
`$3000` for minor research and services cost

## Maintenance and Upgrade Plans

We will keep maintaining this platform as part of our core services as a way to complete our mission; which is to provide transparency in the lease markets for everyone. This will be one of our core offerings.

For example, we intend to make it an integral part of the trifecta of our services to provide visibility of lease pricing. 

# Team

## Team Members

Petros G. Sideris: CTO & Engineer
Stefanos Kostalas: Backend and Web3 Integration Dev
New hire(s)?

## Team Member LinkedIn Profiles

[Petros' LinkedIn](https://www.linkedin.com/in/pgsideris/)
[Stefanos' LinkedIn](https://www.linkedin.com/in/stefanos-kostalas-17384215b/)

## Team Website
https://tripstrade.com

## Relevant Experience

At TripsTrade we have already built on-chain a system where people can trade and resell their leases. We use the **Polygon** blockchain and **IPFS** to store relevant Property and NFT data (each lease is being generated as an NFT).

We have delivered the first phase and product; TripsTrade which is an OTA using our blockchain-based system to enable the booking and resale of leases.
We are building the second phase and product; LeaseLabs which will enable property owners to finance their properties via the presale of leases to investors, other OTAs, funds, and speculators.

We have a great track record of delivering, as well as relevant business and tech experience.

## Team code repositories

https://github.com/TripsTradeDAO
https://github.com/TripsTradeDAO/leases-price-decay

# Additional Information
We met a lot of Filecoin people during WebSummit and they all suggested we do a grant for what we are doing!

You can use petros@tripstrade.com to reach out to discuss the grant agreement and other general steps.

**Comment by ErinOCon** [comment]
Hi @sideris, thank you for your proposal. We will not be moving forward with a grant at this time, but would encourage you to check out accelerator program opportunities [here](https://ecosystem-wg.notion.site/Protocol-Labs-Accelerator-Program-d45d8792a7d544eca9beb7d3e3d3b05d). Happy building!"
