### ISSUE TITLE
Pandos

### ISSUE THREAD

**Issue by adidabakare** [filecoin-project/devgrants#1158]
### 1. What is your project? (max 100 words)
Music platforms such as Spotify and Apple Music take a large percentage of royalties from their own artists. Which we believe should not be the case. Musicians are expected to enjoy the majority of their work. Aside from that, these platforms have the censor your content anytime they want. Music, podcasts, and similar content should be owned and controlled by the user. It should not be taken over by a third party.

Pandos is a decentralized music, podcast and online radio platform built on IPFS that offers the ability to upload, stream and play music. The goal is to create a free decentralized version music platform which artists get paid directly through listener support.

Our application does four(4) things really well

Create: It allows podcast creators to record their podcasts directly from our website. And then upload them for their users to listen.

Meta Space provides an intuitive user experience when it comes to creating a space for a conversation about anything. Send live reactions, tip users, and many other things.

NFT: Artists can mint their album covers as NFTS and reap the benefits of both their fans purchasing the music and their NFTS.

Chat: Send live messages during online space sessions on pandos.

### 2. Project links
  
Link to Github repo: https://github.com/adidabakare/pandos
Link to demo or website, if applicable:  https://pandos.netlify.app/
License: MIT

### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Every single song, Album , podcast and NFTs were stored on IPFS. Literally all storage on the platform were stored on IPFS

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
In order for this project to serve its original purpose and be made public in early next year, we are now working on an improved version of it. New features are being added to the platform to increase usability. With the help of this grant, we will be able to host the project, launch it on the mainnet, and do some marketing to make use of it and connect with a few target customers.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes , I agree to share grant reports 
  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
[* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
](https://devpost.com/software/pandos-l0b6qs)
  
### Additional questions:
* Adida Baka : Full stack blockchain engineer 
* How did you learn about our microgrant program? Through hackertons
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) (Chainlink)
  * Please link to your hackathon submission https://devpost.com/software/pandos-l0b6qs

**Comment by ErinOCon** [comment]
Hi @adidabakare, thank you for your proposal. We will not be moving forward with a grant at this time. Please feel welcome to reapply as you continue to make building progress.

**Comment by adidabakare** [comment]
Thank you for considering our grant application. We were disappointed to learn that our grant was not accepted. Could you please provide some feedback or insight as to why our application was not successful?
