### ISSUE TITLE
Movers

### ISSUE THREAD

**Issue by mendsalbert** [filecoin-project/devgrants#1160]
### 1. What is your project? (max 100 words)
Making use of blockchain technology, we present to you Movers, an property management platform that seeks simplify property management processes with blockchain. By doing so, we offer you an easy way to trade properties amongst users. And what we seek to achieve is to make the property management processes more transparent to end users.

There are about four (4) user types (that is buyer, seller, lender and approver) that is captured on the platform. Among the four (4) user types, a user can perform an activity on the platform by choosing the user type they represent and then proceed to provide to make the exchange of a property a smooth sail. The user is also to ensure that metamask is installed in their browser. Below are steps a user can undertake to perform an activity on the platform:

The buyer can view a property and once interested can proceed to buy the property.
The seller can approve the sale of the property to enable the process, if not, the bid amount will be returned to the buyer. The seller after all other process will finally approve the sale to release the property to the buyer and then receive the bid amount.
The inspector will approve inspection once everything is in order for the next process.
The lender finally approve and lend the property for the seller to finally approve the property.

### 2. Project links
  
Link to Github repo:  https://github.com/mendsalbert/movers
Link to demo or website, if applicable:  https://moversv2.vercel.app
License:MIT

### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  
All properties on the platform were store on IPFS. including images and NFTS

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We are now working on an upgraded version of this project since we plan to make it available to the public. To improve the platform's usability, we are introducing new features. With the support of this award, we will be able to host the project, put it on the mainnet, and do some marketing to use it and reach a few target markets.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://devpost.com/software/movers

### Additional questions:
* Mends Albert - Fullstack developers
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) 
  * Chainlink
  * Please link to your hackathon submission
  https://devpost.com/software/movers

**Comment by ErinOCon** [comment]
Hi @mendsalbert, thank you for your proposal. We will not be moving forward with a grant at this time. Wishing you the best as you continue building!
