### ISSUE TITLE
Next Step Microgrant :FlowShield builds on FVM

### ISSUE THREAD

**Issue by gitsrc** [filecoin-project/devgrants#1161]
### 1. What is your project, and what problem does it solve? (max 100 words)

FlowShield aims to build a decentralized web3 privacy data retrieval security network system around the world, and help users recapture privacy security information eroded by giants under web2, so that the current global hot zero-trust security network technology combined with web3 can better help users master their own security privacy data and give users a good experience of privacy data retrieval security network products.

**As one of the early build teams of fvm-foundry-f1, we built the FlowShield project on FVM**.

**According to community suggestions, we upgraded cloudslit to FlowShield project name.**

### 2. Project links
  
Link to Github repo: https://github.com/FlowShield/flowshield/tree/fevm-testnet
Link to demo or website, if applicable: https://fvm-testnet.flowshield.xyz/
License: MIT Open Source License

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

1. **FlowShield-Fullnode** - build with libp2p | web3.storage
   
   Establish a global node metadata center based on P2P, and build a point-to-point decentralized network,for all user and Dao data, we use Filecoin's web3.storage for decentralized storage of user data.

2. **FlowShield-Provider** - build with libp2p | web3.storage
   
   Nodes realize automatic networking through peer discovery and routing through libp2p's kademlia DHT and IPFS network, and realize data synchronization between multiple nodes through libp2p's PubSub function. For all user and Dao data, we use Filecoin's web3.storage for decentralized storage of user data.

3. **DeCA** - build with libp2p | ipfs-crdt | web3.storage
   
   Constructing decentralized public key infrastructure (PKI)DeCA supports key PKI functions (registration, verification, revocation and OCSP authentication).The certificate information is stored in web3.storage by using the characteristics of IPFS.using IPFS-CRDT synchronization strategy, enhance hidden sharing and synchronize quickly.

4. **Smart contracts** - build with **FVM**

   FlowShield mainly uses smart contracts to build a decentralized storage engine policy center. Our goal is to establish a private data retrieval platform that can run by itself and be managed by the public. At present, the operation carrier of smart contract mainly considers the virtual machine environment compatible with EVM. First, we choose FVM as our decentralized management platform. As the computing layer of the FileCoin storage ecosystem, FVM allows us to conduct trusted computing, provide services closer to data storage, and provide users with more reliable data computing credibility.
   The main functions of smart contracts include:
   1. Pledge and redemption of fullnode node and provider node
   2. Matching and payment of users’ online orders
   3. Withdrawal of benefits by network providers

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)

yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

  We will use this funding to improve the following areas:
  1. Adapting FlowShield fullnode, network provider, smart contracts on fevm test network.
  
  2. Deploy FlowShield-FVM's exclusive website, and let FlowShield platform run on **FVM's** test network.
  
  3. Upgrade FlowShield provider and fullnode pledge process to adapt to **FVM** test network.
     
  4. Report the problems in the FVM adaptation process to the fvm team.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
#### **Hackathons that have ended**
1. 2022 Wanxiang Blockchain Autumn Hackathon 

    Winners of the Blue Future Track

    https://wxblockchain.medium.com/announcing-the-winners-of-2022-wanxiang-blockchain-fall-hackathon-46138d443769

2. 2022 Filecoin China Hackathon

    We won a total of three awards, namely the most potential award in the filecoin track, the first prize in the nervos track, and the most ambitious project award.

    [https://twitter.com/Filecoin/status/1554491609668100098](https://twitter.com/Filecoin/status/1554491609668100098)

    [https://mp.weixin.qq.com/s/VjbtGJMMnfFOO1VottQ7sw](https://mp.weixin.qq.com/s/VjbtGJMMnfFOO1VottQ7sw)

    More than 600 geeks participated and 11 teams were finalists.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
    Biao Li, IPFS/Filecoin ecological contributor ,web3 ecological researcher and builder, corerman@gmail.com, https://github.com/gitsrc
* How did you learn about our microgrant program?
  
  1. We are currently one of the project build teams of fvm-foundry-f1, we learned in the meeting that we can apply for grant.
  2. https://spacewarp.fvm.dev/
   
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
HI @gitsrc, thank you for your patience with our review. This microgrant has been approved! We will send an email to confirm payment details.

**Comment by gitsrc** [comment]
@ErinOCon Thanks to filecoin for their generous support.

**Comment by gitsrc** [comment]
Hi @eshon  latest testnet contract deployment address: [https://hyperspace.filfox.info/en/address/0x074b9f1523C471b30677c196aE1678a01556bD4c](https://hyperspace.filfox.info/en/address/0x074b9f1523C471b30677c196aE1678a01556bD4c)


ps: FlowShield platform address for the latest testnet smart contract: https://fvm-testnet.flowshield.xyz/


thanks @ErinOCon

**Comment by eshon** [comment]
Hi @gitsrc,

1. Hyperspace will be discontinued soon and replaced by the [Calibration testnet](https://docs.filecoin.io/networks/calibration/details/). Can you please redeploy your contracts to Calibration?
2. The demo [here](https://fvm-testnet.flowshield.xyz/) does not work for me - do you have a working demo or can you share a demo video?
3. Can you please provide Github links to the smart contracts that you have written for this microgrant?

Let us know if you can provide more of this info about microgrant completion so we can consider initiating the 2nd microgrant payment.

FYI - here are some general things we like to see to consider an FVM microgrant completed:

- A fully working user-facing demo with nice UX that anyone can easily use.
- A dapp deployed to a Filecoin testnet, so that we can see all the functionality working on a testnet, and will be deployed to Filecoin mainnet in a production-ready state on project completion.
- Interesting use of Filecoin’s EVM, especially with respect to what’s unique to Filecoin (for example, via exploration of the [Filecoin Solidity API](https://docs.filecoin.io/developers/smart-contracts/hardhat/), [FVM use cases](https://docs.filecoin.io/smart-contracts/fundamentals/the-filecoin-virtual-machine/), or [Bacalhau x FVM](https://github.com/bacalhau-project/lilypad), etc.)

**Comment by eshon** [comment]
Let us know if you have any updates on the above questions @gitsrc

**Comment by gitsrc** [comment]
Hi @eshon ,We have completed the content of the micro grant and deployed the contract on the fvm main network and test network. We participated in the fvm SPACE WARP activity and ranked 28th  (a total of 130 projects). We use fvm to build the flowshield network tunnel market.

1. calibration testnet：0x074b9f1523C471b30677c196aE1678a01556bD4c
https://calibration.filfox.info/zh/address/0x074b9f1523C471b30677c196aE1678a01556bD4c

2. fvm main net ：0x2592a5cee5fd0928c79e9c9ede896d1ec9e7fe47


3. Smart contract source code：https://github.com/FlowShield/flowshield/tree/fevm-testnet/contract

4. The speech material we used on the fvm pitch day contains some videos of flowshield strengthening the network security of other software systems.  https://docs.google.com/presentation/d/1C4IeQZo5ipAjhAme57XlfWHpFAaUO9m-1zQok_8B3MY/edit

**Comment by eshon** [comment]
Hi @gitsrc - Apologies for the very late response. We'd like to close out this grant but noticed that your demo site at https://fvm-testnet.flowshield.xyz/ is no longer live. I was never able to get the demo working back in May.

I see one smart contract at https://github.com/FlowShield/flowshield/blob/fevm-testnet/contract/contracts/FlowShieldDao.sol. Can you please point out where and how the following are implemented?

The main functions of smart contracts include:

1. Pledge and redemption of fullnode node and provider node
2. Matching and payment of users’ online orders
3. Withdrawal of benefits by network providers

Please explain via what functions the above are implemented. I just want to make sure that everything that was described in the proposal has been implemented.

Let me know so we can process this for final payment.

**Comment by gitsrc** [comment]
@eshon Thanks for contacting，Currently https://fvm-testnet.flowshield.xyz/ can be accessed. We have completed the task and here is the relevant contract explanation.

<img width="1200" alt="image" src="https://github.com/filecoin-project/devgrants/assets/34047788/b7b63db4-0bab-4b8d-bd72-92cdb69dd82c">


1. Pledge and redemption of fullnode node and provider node
Full nodes perform on-chain staking through the stake function by integrating evm sdk, and can redeem their own pledges through the withdraw function.
* https://github.com/FlowShield/flowshield/blob/fevm-testnet/contract/contracts/FlowShieldDao.sol#L121
* https://github.com/FlowShield/flowshield/blob/fevm-testnet/contract/contracts/FlowShieldDao.sol#L137

2. Matching and payment of users’ online orders
Users can initiate their own orders with the clientOrder function and pay for their orders. After the order is paid, it will be received by the network miner and the service will be started.
* https://github.com/FlowShield/flowshield/blob/fevm-testnet/contract/contracts/FlowShieldDao.sol#L157
* https://github.com/FlowShield/flowshield/blob/fevm-testnet/contract/contracts/FlowShieldDao.sol#L153
* https://github.com/FlowShield/flowshield/blob/fevm-testnet/contract/contracts/FlowShieldDao.sol#L149
* https://github.com/FlowShield/flowshield/blob/fevm-testnet/contract/contracts/FlowShieldDao.sol#L165

3. Withdrawal of benefits by network providers
The network provider can query the token income obtained by all orders through the getAllOrderTokens method and the withdrawAllOrderTokens method in the contract.
* https://github.com/FlowShield/flowshield/blob/fevm-testnet/contract/contracts/FlowShieldDao.sol#L169
* https://github.com/FlowShield/flowshield/blob/fevm-testnet/contract/contracts/FlowShieldDao.sol#L189
* https://github.com/FlowShield/flowshield/blob/fevm-testnet/contract/contracts/FlowShieldDao.sol#L209
