### ISSUE TITLE
Next Step Microgrant: <Dialstone_NFT's>

### ISSUE THREAD

**Issue by Dialstone-airdrop** [filecoin-project/devgrants#1162]
### 1. What is your project? (max 100 words)
 the development and sales of NFT's on platforms like Opensea, Rarible, etc.

### 2. Project links https://opensea.io/0xF2c9B9d549d741AE68dAd0f0D33be4248f8DCf79

https://lnkd.in/gVMM5CKN

Link to Github repo:https://github.com/Dialstone-airdrop
Link to demo or website, if applicable:
License:https://dialstone.myshopify.com

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  Could potentially be used as form of payment, records, and tax information. 
### 6. Does your proposal comply with our Community Code of Conduct?

Yes, it is in compliance. 
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project. N/A
* How did you learn about our microgrant program? Filecoin Github repository. 
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) N/A
  * Please link to your hackathon submission N/A

**Comment by dawnkelly09** [comment]
Hello, Dialstone! Before we can further consider your grant application, we will need you to fill in some missing information:

- [ ] Your repo link leads to an empty repo. Please update with link to a repo where your code can be reviewed.
- [ ] You seem to mention how our technologies could be used but not how they are currently used in your project. Please elaborate on how your project uses Filecoin or IPFS. 
- [ ] Items 4 and 5 in the application were let blank. Please take a look at these items and complete them.

Once we receive this missing information, we will review your application. Thank you

**Comment by ErinOCon** [comment]
This item has been closed. Please feel welcome to reapply once all information is available.
