### ISSUE TITLE
Next Step Microgrant: Trasnpar3ncy

### ISSUE THREAD

**Issue by ffatique** [filecoin-project/devgrants#1163]
### 1. What is your project? (max 100 words)
Transpar3ncy is an open source token infographic for web3 projects. We are currently running a demo on top of the https://mafagafo.com/ project, which brings information about holders, number of unique portfolios, indicators, data aggregators and ranking of holders. Our goal is to create this infographic for the FIL Token https://bscscan.com/token/0x0d8ce2a99bb6e3b7db580ed848240e4a0f9ae153.

Our product for contributing to Filecoin by bringing transparency and clear information to users who seek to buy, negotiate or believe in Filecoin project when they buy its token, so we can bring more solidity and positive points to the FIL Token.

### 2. Project links
  
Link to Github repo: https://github.com/ffatique/Transpar3ncy
Link to demo or website, if applicable: https://transpar3ncy-m3.vercel.app/
License: MIT
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Transpar3ncy will use the FIL Token to ensure clear views of the token on the BSC network. It will be our first step to increase our scale of projects that we want to bring to our Infographic.

In addition, we intend to use IPFS to bring this product to NFT projects in an upcoming roadmap where we also intend to show the use of the IPFS network in NFTS collections such as the amount of data, accesses, file sizes, usage, among other information
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
This grant will help our developer team implement the Infographic for TOKEN FIL and add the new reporting, tracking and notification features to the project.

Goal: Deliver the infographic for TOKEN FIL with all the platform improvements within 8 weeks.

Deliverables: TOKEN FIL Transpar3ncy website

Timeline:
Week 1 and 2: Prototype design of new Filecoin infographic with new tools and features
Week 3 and 4: Development of the new Transpar2ncy
Week 5 and 6: Deploying the new Transpar2ncy with Filecoin and tweaks
Week 7 and 8: Final adjustments and delivery of the TOKEN FIL Transpar3ncy website

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes
  
### Additional questions:
Felipe Fatique, felipe.fatique@sozei.com.br, https://github.com/ffatique, FullStack Developer
Rivan Belo, rivan.belo@sozei.com.br, https://github.com/rivanbello  , CTO
Alexandre Osorio, ale.osorio@sozei.com.br, CEO
Guilherme, gui.bassoli@sozei.com.br, CMO

### How did you learn about our microgrant program?
Alexandre Nicastro

**Comment by ErinOCon** [comment]
Hi @ffatique, thank you for your proposal. We will not be moving forward with a grant at this time. Wishing you all the best with your project!
