### ISSUE TITLE
Blockdrive

### ISSUE THREAD

**Issue by stugufaka** [filecoin-project/devgrants#1165]
### 1. What is your project? (max 100 words)
Blockdrive is a decentralized cloud storage platform that leverages the use of IPFS and web3 storage to store files, thereby improving security. It also comes with chatting capabilities and the ability to convert a file into an NFT.

We believe that data should be stored in a decentralized manner so that no single entity has control over it. This is why we have built our platform on top of IPFS and web3 storage. These technologies enable us to provide a secure and reliable storage solution for our users.

In addition to our storage capabilities, Blockdrive also offers chatting capabilities. This allows our users to communicate with each other directly through our platform. We believe that this feature will be particularly useful for those who need to collaborate on projects or files.

Finally, we also offer the ability to convert a file into an NFT.

### 2. Project links
  
Link to Github repo:  https://github.com/stugufaka/blockdrive
Link to demo or website, if applicable: https://blockdrive.netlify.app/app/dashboard
License:MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
All Files and folders are stored on IFPS and web3 storage.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. Due to the fast growth in the number of files being kept on BlockDrive, we must downgrade our membership plan from Free-tier on Web3.storage to Expert. Our subscription will be upgraded thanks to this funding.
2. It is intended to develop a mobile version of this software, and a portion of the funding will be utilized to host it on the Apple Store and Google Play Store.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://devpost.com/software/block-drive

### Additional questions:
* For each team member: Stugu faka (full stack blockchain developer)
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) Chainlink
  * Please link to your hackathon submission.: https://devpost.com/software/block-drive

**Comment by ErinOCon** [comment]
HI @stugufaka, we will not be moving forward with a grant at this time. Thank you for your proposal.
