### ISSUE TITLE
Built Different - Open Grant Application

### ISSUE THREAD

**Issue by TheGodOfAwesome** [filecoin-project/devgrants#1166]
# Open Grant Proposal: `Built Different`

**Name of Project:** `Built Different` - Introducing, Teaching and Supporting Decentralized Storage and Peer-to-Peer File Sharing in Africa

**Proposal Category:** `community`

**Proposer:** `@thegodofawesome`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** `Yes`

# Project Description

Built Different is an African Web3 startup community and DAO started in Harare, Zimbabwe. We connect founders, developers and enthusiasts, build a shared and inclusive community around a more open, honest and decentralized internet in Zimbabwe and Africa.

During our time building in Web3 and dAPPs, we realized there was very little to no local/African support for individuals and  companies building Web3/Decentralized apps or a place where Africans could learn more about Web3 and participate in building the decentralized web. 

We see decentralized storage as a vital part of the Web3 ecosystem and we would like as many Web3 curious individuals, enthusiasts, developers and founders to learn about, build on top off and adopt decentralized storage and peer-to-peer file sharing using Filecoin and IPFS. We are big believers in community and we think the right ecosystem is necessary to stimulate the growth of startups and Web3 in Africa.

## Value

We see decentralized storage as a vital part of the Web3 ecosystem and we would like as many Web3 curious individuals, enthusiasts, developers and founders to learn about, build on top off and adopt decentralized storage and peer-to-peer file sharing using Filecoin and IPFS.

- We are working to support local developers to build tools that can bridge the divide and help more Africans participate in Web3 and use tools like IPFS in new and novel ways built around the African context.

- We would also like to create a path for unemployed Africans to access career opportunities based on this new found knowledge and and ability

- We are creating localized open source Filecoin and IPFS tutorials and content.

- Encourage the use of best practices and standards when using and building on top of Filecoin and IPFS
 
- We want to inspire, support and incubate products built using and on top off IPFS and Filecoin.

If the campaign does not take off we fear that the adoption of these vital technologies continues to wane in the markets we are in, in Africa.   

## Deliverables

1. Open Source Filecoin and IPFS tutorials and content.
2. Monthly developer workshops for local developers.
  - Goals:
    - Ramping up the community
    - Build knowledge base for developers
    - Duration: 12 months
3. Run Hackathons and Build events to help these developers team up build real world solutions with their newly acquired skills around the themes of 
 - Accessibility
 - Actionable Insights
 and
 - Adoption
(We are working to support local developers to build tools that can bridge the divide and help more Africans participate in Web3 and use tools like Filecoin and IPFS in new and novel ways built around the African context.)
4. We would like to help shine a light on these products in their local markets and help them get local adoption.

## Development Roadmap

November 2022 - We've already started creating some Filecoin and IPFS tutorials. In the form of Open Source Projects and Free Video tutorials.  
Duration: 2 Months  
Team: 2 * Developers  
Budget: 2 * Developers = $4000

December 2022 - We will start hosting Developer workshops starting on December 10, 2022 in Harare, Zimbabwe and continue hosting events all through December 2022 to December 2023 (50-100 attendees, IRL)  
Duration: 12 months  
Team: 4 * Community Leads  
Budget: (venue, catering, audio/video, print materials, incidentals = $1000) * 12 months = $12000

February 2023 - We will proceed to hosting quarterly build days and hackathons starting at the end of  January with the goal of supporting the developers who are already building on Filecoin and IPFS and to help developers build teams and products for the African markets they are in. (50-100 attendees, IRL)  
Duration: 12 months  
Team: 4 * Community Leads  
Budget: (venue, catering, audio/video, print materials, incidentals & prizes = $2500) * 4 months = $10000

March 2023 - By March 2023 we would have started supporting all of the best dAPPs created as a result of this Campaign and give these dAPPs support in their early stage adoption and growth phases.  
Duration: 12 months  
Team: 4 * Community Leads  
Budget: (Marketing, Promotions & Spotlight Events = $4000)  = $4000

## Total Budget Requested
Total (USD): $30000

## Maintenance and Upgrade Plans
We plan to improve from just being a campaign to turning it into a full scale web3 skills program with content partners, a cohort and certification for participants. 

# Team

## Team Members

Kuzivakwashe Muvezwa  
George Chakama  
Eddy Kayiganwa

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/kuzivakwashemuvezwa/  
https://www.linkedin.com/in/george-chakama-76739816b/  
https://www.linkedin.com/in/eddy-kayiganwa-601340207

## Team Website

https://www.builtdifferent.foundation/

## Relevant Experience

Kuzivakwashe Muvezwa

Developer Circles from Facebook Developer (Meta) Circles  
Harare, Zimbabwe  
Jul 2017-Jan 2022  
(4 years, 7 months)  
I helped build and run Facebook Developer Circle Harare as part of Facebook's Developer Circle Program. I helped found and build what is to this day the biggest most engaged developer community in Zimbabwe and Harare. I volunteered my time to help organize and run events, teach other developers, engage and run an offline/online community.

Muzinda Hub (An Econet Company) — Startup and Projects Coordinator  
June 2015 - August 2016  
Start-Up and Project Coordinator  
● I was a project lead helping with the planning, creating, testing and deployment software solutions for both web and mobile
applications. As Start-Up coordinator I was involved in helping Muzinda Hub start-ups with Ideation, Conception (i.e. Product
Development, Business Model etc.), Validation (Product Market Fit) and early stage Scaling. Also creating opportunities and
synergies with local businesses and media.

Develop/Developer Mentor  
● But I had started out as a volunteer Android Developer Mentor assisting in the training of 1000 new developers under the
teamtreehouse program. Also helping Muzinda Hub technology startups as an advisor and technical support.

## Team code repositories

https://github.com/TheGodOfAwesome
https://github.com/gtchakama
https://github.com/kayiganwa04

# Additional Information
We learnt about open grants through EthGlobal and the Next Steps Microgrants which we have been a recipient of.
kuzi@builtdifferent.foundation
https://www.builtdifferent.foundation/

**Comment by ErinOCon** [comment]
Hi @TheGodOfAwesome, thank you for your proposal. We will not be moving forward with a grant at this time, but would highly recommend checking out [Orbit](https://orbitcommunity.filecoin.io/) for additional opportunities!

**Comment by ErinOCon** [comment]
Hi @TheGodOfAwesome, in case you have interest in the Orbit program, you can find an application form [here](https://docs.google.com/forms/d/e/1FAIpQLSfIjth-qWpuYqSYtGwlZ9HxllcZ_5zCT80tCd7XF2P5mYfh2Q/viewform)!

**Comment by TheGodOfAwesome** [comment]
Thanks @ErinOCon will do!
