### ISSUE TITLE
World3

### ISSUE THREAD

**Issue by pakariisbum** [filecoin-project/devgrants#1168]
### 1. What is your project? (max 100 words)
World 3 is a web 3.0 platform that will bring together explorers to solve social and environmental problems of the SDG goals. Our mission is to use blockchain to achieve real world impact, especially in areas where there is no other solution. We believe that the technology exists today, and more importantly, we have built World3 to be easily adopted by anyone that needs a tool for managing social issues.

### 2. Project links
  
Link to GitHub repo: https://github.com/pakariisbum/world3
Link to demo or website, if applicable: https://world3s.netlify.app/
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  IPFS is used to store all the media on this project most especially the images

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. One of our top goals is mainnet launch.
2. By including new features, we'll enhance the user experience.
3. The grant will utilize services like Quicknode and Chainlink (price feed).

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?
Definitely 
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://devpost.com/software/world3-2p1dbt

### Additional questions:
* For each team member(s), please list name, email, GitHub account, and role in the project.
Name: Pakari Isbum
email: pakariisbum@gmail.com
github: github.com/pakariisbum.com

* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) Chainlink 
  * Please link to your hackathon submission
https://devpost.com/software/world3-2p1dbt

**Comment by ErinOCon** [comment]
Hi @pakariisbum, thank you for your proposal! This grant has been approved. We will send an email to confirm next steps.
