### ISSUE TITLE
Blogistics

### ISSUE THREAD

**Issue by gonormonor** [filecoin-project/devgrants#1171]
### 1. What is your project? (max 100 words)

Blogistics is a blockchain-based logistics platform that enables secure and transparent supply chain management. By decentralizing the supply chain management process on the blockchain, Blogistics provides a higher level of security and transparency, as well as immutability.

By using Blogistics, businesses will be able to enjoy a higher level of security and transparency in their supply chain management process. In addition, the platform is also immutable, which means that once data is entered into the blockchain, it cannot be changed or tampered with. This provides businesses with a higher level of confidence in the accuracy of the data. by a third party.

### 2. Project links
  
Link to Github repo:  https://github.com/gonormonor/Blogistics
Link to demo or website, if applicable: https://blogistics.netlify.app/
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
 1. IPFS is used to store the orders and the products on the applications
 2. User profile information are being stored on IPFS as well
 
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. The team is planning to scale this platform and this grant will help us purchase some toolkits and services for better User experience
2. We are also going to move the platform from testnet to mainnet
3. Marketing and reaching out for more users is one of thing we will also be using this grant for

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

 Yes
### 6. Does your proposal comply with our Community Code of Conduct?

Yes absolutely 
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://devpost.com/software/blogistics
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Gonor Monor - Blockchain Developer
email: [gonormonor@gmail.com](mailto:gonormonor@gmail.com)
GitHub: github.com/gonormonor
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) Chainlink
  * Please link to your hackathon submission
https://devpost.com/software/blogistics

**Comment by ErinOCon** [comment]
Hi @gonormonor, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
