### ISSUE TITLE
Brainic

### ISSUE THREAD

**Issue by sensurusirupus** [filecoin-project/devgrants#1172]
### 1. What is your project? (max 100 words)

Brainic is a web3 memory game application that helps improve the memory of individuals while wining tokes as a result. The application is designed to be played by anyone, regardless of their age or experience with memory games. The goal of the game is to help the player improve their memory, while also providing them with the opportunity to win tokens as a result.

The game is played by matching pairs of cards, with each card representing a different nft image challenge. The more pairs of cards the player can match, the more tokens they will win. In addition to the opportunity to win tokens, the game also provides the player with a chance to improve their memory skills. The application is available for free, and can be played on any web-enabled device.

### 2. Project links
  
Link to Github repo: https://github.com/sensurusirupus/brainic
Link to demo or website, if applicable: https://brainic.netlify.app/
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
 All the card of the NFTs were stored on IPFS and web3storage

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. A mobile app version of this app has the potential to reach a larger audience. this grant will be used to build the mobile app version of this app for both iOS and Android.
2. A portion of this grant will be used for marketing as well

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  Certainly 
### 6. Does your proposal comply with our Community Code of Conduct?

 yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 https://devpost.com/software/brainic

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Sensurus Irupus
email: sensurusirupus@gmail.com
GitHub: github.com/sensurusirupus
role: Full stack developers
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) Chainlink
  * Please link to your hackathon submission
https://devpost.com/software/brainic

**Comment by sensurusirupus** [comment]
Hello @ErinOCon Please any update on this grant?

**Comment by ErinOCon** [comment]
@sensurusirupus, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
