### ISSUE TITLE
WebBadminton

### ISSUE THREAD

**Issue by Pfed-prog** [filecoin-project/devgrants#1173]
### 1. What is your project? (max 100 words)

WebBadminton Dapp introduces users to the sport of Badminton as well as contains item store to track and ledger the delivery of badminton equipment.
Each real equipment item is ledgered via a digital one with a smart contract logic system in place to determine the demand and track iteam. When delivery is completed the DApp ERC1155 NFTs should be exchanged for the physical items. WebBadminton DApp succeeds where off-chain software ledgering system products fail because they may go out of service, need updates, crash with data losses. Web Badminton DApp is a very low cost business systems management product/tool.

### 2. Project links
  
Link to Github repo: https://github.com/dspytdao/WebBadminton
Link to demo or website, if applicable: https://webbadminton.com/
License: MIT License

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
All the card of the NFTs were stored on IPFS and web3storage. 
The newsletter list data is stored on ipfs with web3.storage.
The contract is built with solidity, hardhat. 
The polygon blockchain mumbai testnet and lukso l14 host the smart conract.
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We aim to co-operate with equipment sellers to enter the market. We outline the following milestones to make it a reality:

1. Making User Experience better with lower size assets and caching. 
2. Integration of the stable wallet library to the application.
3. Creation of additional posts on the site which can attract more audience and interest it.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  Yes
### 6. Does your proposal comply with our Community Code of Conduct?

Yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

[2022 THUBA DAO’s Summer Hack Bounty Winner: Scale your decentralized applications by deploying on the Polygon PoS blockchain network](https://dorahacks.io/hackathon/34)
  
[Web3 Infinity Hackathon: WINNER Next Top 30](https://web3infinityhackathon.devpost.com/)

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Name: Pavel Fedotov
email: pfedprog@gmail.com
GitHub: https://github.com/pfed-prog
Role: Back End Developer and Smart Contract Engineer

Name: Dmitry Kulin
email: dmitryinstagram1@gmail.com
GitHub: https://github.com/BadmWe
Role: Front End Developer and Badminton Expert

* How did you learn about our microgrant program? Filecoin and IPFS Newsletter
* If your project was created as part of an event or hackathon: Yes
  * What was the name of the event? Web3 Infinity Hackathon and 2022 THUBA DAO’s Summer Hack
  * Please link to your hackathon submission

[Devpost](https://devpost.com/software/web-badminton) 

[DoraHacks Buidl](https://dorahacks.io/buidl/3416)

**Comment by ErinOCon** [comment]
Hi @Pfed-prog, thank you for your patience with our review. This microgrant has been approved! We will send an email to confirm payment details. Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). 

Please let us know if you have any questions!
