### ISSUE TITLE
Next Step Microgrant: ♟️ ETH-Chess

### ISSUE THREAD

**Issue by StarKeyJON** [filecoin-project/devgrants#1174]
### 1. What is your project? (max 100 words)

ETH-Chess allows for decentralized Ethereum wagered chess matches and death-match tournaments(where the winner of 3 consecutive games in a row wins the rewards pot!).
Matches are initiated and settled on the Ethereum blockchain.
IPFS is used for match details, move preservation during gameplay, and for the review of disputed winning claims.
Truth-fullness of winning claims is presumed through security deposits >= the wagered amount.
Platform NFT holders can vote on disputed claims and receive a portion of the false claim's security deposit.

### 2. Project links
Link to Github repo: 
  https://github.com/StarKeyJON/EthChess
Link to demo or website, if applicable: 
  https://ethchess.com
License: 
  Apache License 2.0

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
IPFS is used for match details, move preservation during gameplay, and for the review of disputed winning claims.
NFT.storage is to be implemented for creating memorable ETH-Chess Match winning trophy NFTs.
Match details: Each player's Ethereum address, off-chain cryptographic public key-pair, wager amount, initial move and transaction hash of the contract call to start the match is saved to IPFs for the Match Details.

Move Preservation: Each player's Ethereum address, off-chain cryptographic public key-pair, current FEN, last FEN, last move, gameplay nonce, and total board move history is preserved to IPFS with each valid move taken.

Review of Disputed Winning Claims: Platform NFT holders can review the match details, each player's gameplay history and the fully preserved gameplay history to vote on an outcome.

Trophy NFTs: NFT.storage will be implemented to create memorable NFTs as trophies to showcase winning matches, death-matches and tournaments.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

I am currently building this project in my spare time as I work 3 jobs trying to get by. Two of those jobs can be placed on hold as I work on improving this project to a final state of public usage. The grant would go towards supplementing server costs, contract deployments, development time, deployment on the Ethereum main-net and TheGraph main-net, an official white paper, treasury implementation, revenue model and grant repayment plan.
1.) Developmental funding.(Domain name purchases, copyrights, server/subscription costs, dev time compensation, etc.)
2.) Develop ETH-Chess white paper, treasury and revenue model.
3.) Implement platform Treasury contracts and grant repayment plan from platform generated revenue.
  3a.) Implement expansion contracts for ETH-Chess Leagues and ETH-Chess League Tournaments.
  3b.) Implement NFT.storage for memorable ETH-Chess Match/Death-Match and League Tournament trophy NFTs.
4.) Deploy backend express server to allow for 3rd party move validation and gameplay preservation.
5.) Deploy smart contracts on the Ethereum main-net. Deploy subgraphs on TheGraph main-net.
6.) Front-end finalizations and production build deployment.
7.) (To be considered) Fund initial platform Rewards Pot/micro-advertising campaigns.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  Yes, it would be my pleasure.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Hackathon link:  https://gitcoin.co/issue/29523

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
JON, starkeyjon@protonmail.com, https://github.com/StarKeyJON, founder/dev

* How did you learn about our microgrant program?
From the email alerting me about winning a place in the Gitcoin Social Hour hackathon.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
 Social Hour

  * Please link to your hackathon submission
https://gitcoin.co/hackathon/socialhour/projects/17206/ethchess

**Comment by ErinOCon** [comment]
Hi @StarKeyJON, this microgrant has been approved! We will send an email to confirm payment details. Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
