### ISSUE TITLE
Next Step Microgrant: NFT-Certs

### ISSUE THREAD

**Issue by allanokothdev** [filecoin-project/devgrants#1175]
### 1. What is your project? (max 100 words)
NFT-Certs - Fake certificates is a prevalent issue in Kenya, It is reported that one on every 3 Kenyans holds a fake academic document, and it is unfortunate that these holders manage to climb their respective career ladder to assume professional roles like surgeons, and later cause irreparable damage because they don't have the relevant skill set needed for that role. NFT-Certs, a Decentralized platform uses IPFS technology to store authenticated certificates, which HR's can view when evaluating their an interviewee's candidacy. 

### 2. Project links
Link to Github repo: https://github.com/allanokothdev/NFT-Certs
Link to demo or website, if applicable: https://youtu.be/SkRT-Hs1K_0
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
I've integrated IPFS to store authenticated certificates.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. Create User Profiles: where each user can view all the certificates attached to their address
2. Add payment module (sustainability), so that institutions, program managers, teachers can pay a fee when publishing certificates.
3. Add program/opportunities pages: A page where we list hackathons, competitions (basically opportunities/programs where certifications are issued to the participants).  

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
No
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  Allan Okoth - allanokothdev@gmail.com - Frontend & Smart Contract Developer - https://github.com/allanokothdev
  Kelly Kigan - User Research - kellykigan.kk@gmail.com

* How did you learn about our microgrant program - Filecoin Website
* If your project was created as part of an event or hackathon:
  * What was the name of the event? EthSafari
  * Please link to your hackathon submission: https://github.com/allanokothdev/NFT-Certs

**Comment by ErinOCon** [comment]
Hi @allanokothdev, This microgrant has been approved! We will send an email to confirm payment details. Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
