### ISSUE TITLE
FIL-Peggy: Tools to manage miner with smart contract

### ISSUE THREAD

**Issue by kikakkz** [filecoin-project/devgrants#1176]
### 1. What is your project? (max 100 words)

FIL-Peggy is a series of tools to help user manage their miner with smart contract. It's developed with FVM.

### 2. Project links
  
Link to Github repo: https://github.com/NpoolFilecoin/fil-peggy, https://github.com/NpoolFilecoin/fil-owner-actor
Link to demo or website, if applicable:
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

We use FVM sdk to build helper tools at host side, including create account, create miner, compile actor, install actor, etc. And we implement all miner management functionality in smart contract. Then we deploy actor to Filecoin blockchain. User can manage their miner through deployed smart contract.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1  We'll finish the base functionality with a cli version
2  We'll finish the full functionality with desktop / website / dApp version later
3  We'll make a miner reputation system to let user know about the investment detail

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

Yes. https://ethglobal.com/showcase/fil-peggy-f77i2  

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Zhao KK: Software Engineer
Tang Song: Software Engineer
Tang Hong: QA Engineer

* How did you learn about our microgrant program?
Community.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  Hack FEVM
  * Please link to your hackathon submission
https://ethglobal.com/showcase/fil-peggy-f77i2

**Comment by ErinOCon** [comment]
Hi @kikakkz, thank you for your proposal! This grant has been approved. We will send an email to confirm payment details.

**Comment by ErinOCon** [comment]
Hi @kikakkz, I hope your project is progressing well! If you have any questions regarding the reporting process for this work, please be in touch. In the meantime, here are some things we are looking for when reviewing FVM Microgrant results: 

- A fully working user-facing demo with nice UX that anyone case easily use.
- Deployment to FVM mainnet - now that it has officially launched!
- Interesting use of the EVM on Filecoin, especially with respect to what's unique to Filecoin

Happy building!

**Comment by ErinOCon** [comment]
Hi @kikakkz, can you provide an update on your project progress? Below is a current list of what we look for when determining if a FVM microgrant project is complete:

- A fully working user-facing demo with nice UX that anyone can easily use.
- A dapp deployed to a Filecoin testnet like [Calibration testnet](https://docs.filecoin.io/networks/calibration/details/) so that we can see all the functionality working in a demo, and will be deployed to Filecoin mainnet in a production-ready state on project completion.
- Interesting use of Filecoin’s EVM, especially with respect to what’s unique to Filecoin (for example, via exploration of FVM use cases or the Filecoin Solidity API (see https://github.com/filecoin-project/community/discussions/585#resources, or [Bacalhau x FVM](https://github.com/bacalhau-project/lilypad), etc.)

Please be in touch with any questions!

**Comment by kikakkz** [comment]
> Hi @kikakkz, can you provide an update on your project progress? Below is a current list of what we look for when determining if a FVM microgrant project is complete:
> 
> * A fully working user-facing demo with nice UX that anyone can easily use.
> * A dapp deployed to a Filecoin testnet like [Calibration testnet](https://docs.filecoin.io/networks/calibration/details/) so that we can see all the functionality working in a demo, and will be deployed to Filecoin mainnet in a production-ready state on project completion.
> * Interesting use of Filecoin’s EVM, especially with respect to what’s unique to Filecoin (for example, via exploration of FVM use cases or the Filecoin Solidity API (see [FVM Hackathon Cheat Sheet community#585 (comment)](https://github.com/filecoin-project/community/discussions/585#resources), or [Bacalhau x FVM](https://github.com/bacalhau-project/lilypad), etc.)
> 
> Please be in touch with any questions!

Hi @ErinOCon , development work of peggy is still in progress (and seems have to be delayed). We met some issues when we want to custody a miner to smart contract. We managed to solve some of them, but still some security issue need to be checked. And it'll be integrated to our staking and storage provider management product.

**Comment by ErinOCon** [comment]
Thank you for the update, @kikakkz! Do you have an estimated completion date? Please let us know if support from our team would be helpful!

**Comment by kikakkz** [comment]
Hi @ErinOCon , we have scheduled to finished the product about at end of July (hope it'll be not too late). It'll be live on mainnet with a small miner custodied to the smart contract.

**Comment by ErinOCon** [comment]
Thanks, @kikakkz!

**Comment by ErinOCon** [comment]
Hi @kikakkz, I hope you are doing well! Can you provide an update on grant progress?

**Comment by kikakkz** [comment]
Hi @ErinOCon , i'm so sorry we have to delay the schedule of the production version to Nov. 2023 due to we redesign some features of peggy. we still need to tune some user experience of its scenario for mainnet.

**Comment by ErinOCon** [comment]
HI @kikakkz, thank you for the update. Can you confirm when the work will be ready for review?

**Comment by kikakkz** [comment]
Hi @ErinOCon , we're still in developing. if everything is OK, i think we can finish the first version at end of Nov.. it'll be deployed to mainnet along with our power/device lease and hosting platform which is scheduled to be online at end of Nov.
