### ISSUE TITLE
Next Step Microgrant: voteproposal.xyz

### ISSUE THREAD

**Issue by JSchimanski** [filecoin-project/devgrants#1177]
### 1. What is your project? (max 100 words)
https://voteproposal.xyz/ is a decentralized super lightweight snapshot.org API based voting and proposal app. 
All ERC20, BEP20 new and existing tokens and other EVM blockchains are supported. 
Token holders can create proposals and vote. 
With a preset value of tokens, any token holder can create proposals. 
With a preset value of tokens, any holder can vote for proposals.

To test/participate: Request Free testnet LINK on Mumbai Polygon Chain.
https://faucets.chain.link/mumbai

Required “LINK” tokens to Publish 1
Required “LINK” tokens to Vote 1

https://mumbai.polygonscan.com/token/0x326C977E6efc84E512bB9C30f76E30c160eD06FB

To change the project to any other erc20 or bep20, simply "change" the variables to correspondent with the token you want to vote on or make proposals on.

data-network = "80001"
data-token-address = "0x326C977E6efc84E512bB9C30f76E30c160eD06FB"
data-token-symbol = "LINK"
data-required-amount-to-publish = "5"
data-required-amount-to-vote = "1"

data-network = is chainID from this list https://chainlist.org (Ethereum - "1", BSC - "56")
data-token-address = ...address and variables of your erc20 or bep20 contract
data-token-symbol = ...address and variables of your erc20 or bep20 contract
data-required-amount-to-publish = your required tokens amount to publish proposal
data-required-amount-to-vote = your required tokens amount to vote for proposal

### 2. Project links
Link to Github repo: https://github.com/JSchimanski/voteproposal 
Link to demo or website, if applicable: https://voteproposal.xyz/ 
License: MIT

### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
IPFS is used to store proposals and user votes using a technique known as ‘off-chain’ voting, where the cryptographic signatures proving user votes are persisted to IPFS instead of being stored on the blockchain. We already prepared the Filecoin Wallaby FEVM as supported chain within it.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Improve the UI with fronted accessible variables and chain options with overall improvements. We think we have some awesome opportunities for many users here!

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes  

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Johan Schimanski - vote@voteproposal.xyz  - https://github.com/JSchimanski - Dev
* How did you learn about our microgrant program?
Surfing https://filecoin.io/blog/posts/what-the-fvm-unlocks/

**Comment by ErinOCon** [comment]
Hi @JSchimanski, thank you for your patience with our review. We will not be moving forward with a grant at this time, but
 recommend checking out [our hackathons](https://hackathons.filecoin.io/). Wishing you the best as you continue building!
