### ISSUE TITLE
Next Step Microgrant: IPFS/Filecoin integration to SAP with proUBC

### ISSUE THREAD

**Issue by fleischr** [filecoin-project/devgrants#1179]
### 1. What is your project? (max 100 words)
Add further IPFS/Filecoin support for SAP's ABAP programming language with proUBC, the open source Web3 connector for SAP

### 2. Project links
  
Link to Github repo:
https://github.com/provideplatform/proUBC
Link to demo or website, if applicable:
IPFS example first implemented in Chainlink Fall Hackathon 
Youtube video https://youtu.be/fxqMscQVItE
https://github.com/provideplatform/proubc-chainlink-fall-hackathon-2022
proUBC enablement Docs https://docs.provide.services/proubc
License: Apache 2.0
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Currently - the proUBC supports SAP adding a file to IPFS from SAP's server directory.

SAP itself manages a large number of files across other integration channels and external business partners . This project will help to grow the IPFS/Filecoin integration capabilities to those scenarios in SAP and introduce IPFS/Filecoin to a broader, B2B-based audience.

proUBC includes several other Web3 integration capabilities to supplement use of IPFS/Filecoin in SAP (Baseline/Privacy for ZK, Ident for decentralized identity/account abstraction, Vault/Nchain for secrets management, HD wallet integration and smart contracts integration capability)

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Implement additional API methods to read, write, pin and otherwise manage files between SAP and IPFS/Filecoin using the ABAP programming language and proUBC.  This will be achieved by analyzing how the same has been done across other language-specific API clients (Java, .NET, Python, etc) and other open source examples that have achieved similar results. 

In the proUBC enablement docs, document steps to connect SAP to IPFS and run an example

Engage further SAP developer community engagement with a standalone example (ex: sharing an Excel file to/from IPFS and SAP) and blog post on SAP community blogs

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 Filecoin *Bonus* DeFi Magician
Filecoin - Runners up 
Filecoin - *Bonus* Computer Over Data 
Filecoin - *Bonus* On the Tools
Filecoin - *General* StorageWizard
 Filecoin - *Bonus* Web3Fy 
Filecoin - *Bonus* Social Good Warrior
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Ryan Fleischmann, ryan@provide.services, @fleischr, SAP Architect and Developer Evangelist @provideplatform
* How did you learn about our microgrant program?
Via Twitter - after checking out the Filecoin foundation page
* If your project was created as part of an event or hackathon:
Chainlink Fall 2022 Hackathon
  * Please link to your hackathon submission
  https://devpost.com/software/chainlink-price-feed-integration-to-sap

**Comment by ErinOCon** [comment]
Hi @fleischr, thank you for your proposal! This grant has been approved. We will send an email to confirm next steps.
