### ISSUE TITLE
open-proposal-on-chain-compliance-certifications.md

### ISSUE THREAD

**Issue by okgardner** [filecoin-project/devgrants#1181]
# Open Grant Proposal: `On-chain compliance certifications (and more!)`

**Name of Project:** `On-chain compliance certifications (and more!)`

**Proposal Category:** `devtools-libraries`

**Proposer:** `banyancomputer`

**(Optional) Technical Sponsor:** ` David Aronchick` 

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

Data Custodians (DCs) have legal obligations to store data under various compliance specifications across a variety of userflows, implementations, and environments. Currently, the Filecoin network is specifically in the position to offer archival-cloud storage at scale at a fraction of the price of AWS S3 Glacier and related services. However, data custodians cannot use the Filecoin network to meet their storage needs because there are few-to-no Filecoin Service Providers (SPs) that meet compliance requirements (HIPAA, SOC2, GDPR, etc), and there’s no way to look up which miners are compliant without contacting the miners directly and asking for their paperwork. The Filecoin ecosystem is growing rapidly to address the enterprise storage use case, building out robust CDN, CoD, and hot-storage/retrievability solutions, but is not currently implementing a compliance signaling mechanism. Compliance is not optional for enterprise customers - The Filecoin network will not be able to onboard the large majority of data (80% of which is enterprise data) without a compliance layer. 

We propose to design a specification for an SP compliance information format that produces verifiable SP compliance certification and metadata on the Filecoin network. Our solution has two milestones:

1. A specification for publishing resulting certifications in a way that is standardized, upgradeable (think Multiformats), accessible via either an API or Filecoin state, and compatible with existing enterprise data pipelines. 

2. Analysis and recommendations for future development and integration of this standard with other pieces of the Filecoin network, like Bacalhau, Boost, Storage Market Actor, Fil+, and Saturn. Special attention will be paid to the interaction of services with each other in a compliant environment, and avoiding dispatching jobs from compliant services to non-compliant ones. 

The proposed solution is essential to integrating compliant SPs into the Filecoin network. A well-designed compliance-certification-publishing specification would give enterprise clients the ability to discover SPs offering their desired compliant service and use that information to onboard data onto the Filecoin network. It would also allow potential clients to use various services seamlessly, mimicking an AWS Cloudformation and integrating compliant archival, hot storage, CoD, and retrieval all within the Filecoin network.

## Value

Today, approximately 30% of the world’s data volume is being generated by the healthcare industry. By 2025, the compound annual growth rate of data for healthcare will reach 36%. The global healthcare data storage market reached $3.08 billion in 2020 and is projected to grow by 10.7% annually to surpass $6.12 billion by 2027. Covered healthcare entities are required by HIPAA and state-by-state law to maintain health records for 6-10 years, and often retain multiple backups for security and disaster recovery purposes. There is a massive and growing amount of data in the US to be stored that meets the current technological capacities of the Filecoin network, but cannot be onboarded because there is no network of HIPAA compliant SPs. A similar story can be told about US highly regulated financial institutions, which are required by [Section 17(a)(1) of the Securities Exchange Act ](https://www.govinfo.gov/content/pkg/USCODE-2019-title15/pdf/USCODE-2019-title15-chap2B-sec78q.pdf)to store all communications and business records for approximately 6 years, and do so archivally. This data could be onboarded if SOC 2 compliant SPs had a way to demonstrate their compliance to enterprise customers. The benefits of this proposed solution extend beyond US-specific applications. For example, any personal data in the EU must be stored in compliance with GDPR. 
On-chain compliance certifications is a necessary precondition for bringing enterprise to the Filecoin ecosystem. Getting this project right means that if SPs get compliant, there is a framework for them to signal their certification to enterprise clients and a lot more data can be onboarded to the Filecoin network. If we do not get this right and design a bad specification, then providers won’t use it and someone will design a better specification because this is essential for ecosystem growth and data onboarding. The main risk our team will have to deal with is how trust is handled in a distributed system, particularly between compliant and non-compliant entities (i.e. data centers, CDNs, etc). 
Since most enterprise data requires compliant storage, the current scale of this opportunity is the roughly [5.75 billion dollar](https://www.statista.com/statistics/498032/information-archiving-market/#:~:text=In%202022%2C%20the%20information%20archiving,7.20%20billion%20U.S.%20dollars%20annually.) enterprise archival data storage market, which represents around 80% of all archival storage. The long term scale, conditional on Filecoin developing CoD and hot/storage, is facilitating the onboarding of the [83 billion dollar](https://www.statista.com/statistics/1322710/global-cloud-storage-market-size/#:~:text=Size%20of%20the%20cloud%20storage%20market%20worldwide%202021%2D2029&text=The%20market%20is%20estimated%20to,growth%20rate%20of%2024%20percent.) enterprise data storage market growing at a 24% CAGR.

## Deliverables

The final deliverables for this project will be: 
1. A spec and interface of how an entity with information about the compliance status of a certain entity with a certain piece of regulation might post that information on the Filecoin blockchain using FVM, for consumption by other entities in the Filecoin ecosystem.
2. A research and recommendations brief on the design of specs and interfaces so that this compliance system might interact with other Filecoin ecosystem services (Saturn, Boost, Storage Market Actor, block explorers, Bacalhau, retrieval markets).

## Development Roadmap

**Milestone 1:** 

At the end of this milestone, we will deliver a spec and interface (compatible with both WASM actors and FEVM/solidity) of how one entity with information about the compliance status of a different entity might post that information on the Filecoin blockchain using FVM, for use by other entities in the Filecoin ecosystem. **The spec will:**  

1. Enable an entity like a compliance auditor to post an attestation of compliance on chain, post links/CIDs to relevant documentation, post relevant information in a standardized format for programmable consumption, revoke this compliance attestation, specify an expiration or renewal date, and delegate scoped permissions to grant/revoke attestations to other entities.
2. Be a standardized and sufficiently general interface, such that various entities can be treated idempotently in consuming code. I.e., if Bob is no longer trustworthy to certify whether miners are KYC/AML-checked to avoid transacting with sanctioned entities, instead using Alice’s certification should only involve changing one variable in consuming services.
3. Work for a variety of attestations – physical location, KYC/AML, HIPAA, SOC2, presence or absence of specific hardware, having a certain kind of insurance, participation in an ESG/climate standard, or arbitrary other specifications we find might be useful in the future from our research.

**This spec will also require answering the following unanswered questions:** 

What is the optimal architecture decision for runtime efficiency? Do we want to be able to rapidly get a list of every available compliant server to run this job, or do we just want to be able to efficiently check whether a given statement is true or false?
Should the specification consist of a format of information on-chain, or an on-chain interface that client contracts can call? 

- **Team:** Claudia, Xiangan, Ita
- **Funding:** $30k
- **Timeline:** December 1, 2022 - December 23, 2022

**Milestone 2:** 

At the end of this milestone, we will deliver a research and recommendations brief on the design of specs and interfaces so that this compliance system might interact with other Filecoin ecosystem services (Storage Market Actors, Bacalhau, and Retrieval markets). **This will require:** 

1. Technical deep-dives into each Filecoin ecosystem product. For example, something like a block explorer might have a mode where you can input a given contract address to check compliance with, and then it’ll filter the service providers it displays by that address, or add a specific logo next to SPs that hold that certification.
2. Specific attention on integrating some of the more complicated projects like Bacalhau or Saturn, where data may cross multiple nodes and will need to be checked for compliance on each one. 

**This research will also answer the following unanswered questions:** 

1. Given the previous specification in Milestone 1, what is the optimal way for other services to interact with compliance information formatted on-chain?
2. How does this affect things like job schedulers and threat modeling in a system in which there are compliant and non-compliant actors? We probably can’t act under the assumption that KYC’d nodes are a closed set in terms of relaying communications, but maybe we can act under the assumption that HIPAA-certified nodes are guaranteed to only ever pass computations and data to other HIPAA-certified nodes. Figuring out the details of this will be specific to the compliance certification and subset of Filecoin infrastructure and are essential for ecosystem expansion. 

- **Team**: Claudia, Xiangan, Alex, Jonah, Ita
- **Funding**: $30k
- **Timeline**: December 26, 2022 - January 16, 2023

**NOTE**: For this milestone, we plan on targeting Bacalhau, storage markets, and retrieval markets. Please let us know if there are additional services you’d like us to target for this milestone, such as Block explorers, Saturn, and Boost. We are open to negotiating a third milestone that will cover more services. 

## Total Budget Requested

The total budget request is $60k. We will use the budget to pay for the researchers needed to complete and maintain this grant. 

## Maintenance and Upgrade Plans

The scope and value of enabling enterprise data to be brought onto the Filecoin ecosystem is immense, so we’re planning to update this spec as needed to accommodate new needs of the ecosystem. Banyan is pivoting into being an end-to-end compliance solution for cloud services on web3, and we will be the ones with needs related to continuing the work covered by completing this grant. Given the many possible applications for this grant, however, it is likely that we will not be the only entity using the research conducted through this grant. We will design our specs to be as general as possible to cover as many future needs as we can imagine the ecosystem will have, and we plan to collaborate with other interested parties (including the permissioning working group run by the Fission folks). 

# Team

## Team Members

- [Claudia Richoux](https://www.linkedin.com/in/laudiacay/)
- [Maya Krasovsky](http://linkedin.com/in/maya-krasovsky-297881185)
- [Olive Gardner](https://www.linkedin.com/in/olive-gardner-27751715a)
- [Ita Caroline](https://www.linkedin.com/in/ita-c-491b54171)
- [Vitaly Gachkovsky](https://www.linkedin.com/in/vitasiempre)
- [Al Miller](http://linkedin.com/in/al-miller-110953171)
- [Jonah Kaye](https://www.linkedin.com/in/jonah-kaye-875a051b2)
- [Xiangan He](https://www.linkedin.com/in/xianganhe)
- [Thea Chhim](https://www.linkedin.com/in/sokkunthea)

## Team Website

[https://banyan.computer/](https://banyan.computer/)

## Relevant Experience

**The backgrounds of individual team members who will be actively involved in this project include:** 

- Claudia, CEO, worked at Protocol Labs as a software developer on various Filecoin initiatives. She left PL to start Banyan with the goal of improving the decentralized storage ecosystem. Claudia also worked in cybersecurity for 4 years. 
- Xiangan, Software Developer, worked as a smart contractor auditor and on Nomad before joining Banyan. He has been developing developer tools for the FEVM as well as deploying basic DeFi infrastructure onto the Wallaby testnet. Xiangan is currently participating in Launchpad. 
- Alex, Software Developer, is a full-stack developer with DevOps and architecture experience. He has experience in the Filecoin ecosystem and is currently participating in Launchpad.
- Ita, Lead Product Manager, worked as a PM in Biotech for 3 years on various Algo team projects and an FDA submission before leaving to work for Banyan.
- Jonah, Software Developer, worked in human rights compliance for a year, focusing on designing US government import restrictions and regulations and standards for enforcement.  
We are the best team for this project because of our mixture of compliance, regulatory, auditing, and cybersecurity experience along with our strong team of developers deeply familiar with the Filecoin Ecosystem, FVM, and FEVM. 

## Team code repositories

[github.com/banyancomputer](https://github.com/banyancomputer)

# Additional Information
 Claudia previously worked at PL and has been in the ecosystem for over a year now. She discussed this grant with David Aronchick and a few others at Lab Week.
 The best contacts for discussing the grant agreement and general next steps are Jonah Kaye at jonah@banyan.computer and Olive Gardner at olive@banyan.computer.
 We would also like to note that we are long term also looking to build additional compliance architecture.

**Comment by okgardner** [comment]
@laudiacay @aronchick @jonahkaye @ita_c @amiller68

**Comment by laudiacay** [comment]
Also: see this: "KYC and claims attestation" on here: https://rfs.fvm.dev/#46ba2bcb4a0d4968b97c5e72b8534608

**Comment by aronchick** [comment]
This is a great project - I'm a big supporter.

**Comment by laudiacay** [comment]
We started work this week on the first milestone, regardless: https://github.com/banyancomputer/on-chain-compliance-attestations

**Comment by laudiacay** [comment]
Not sure whether this is going to get approved, so I'm just going to share this here- it's been done since like November. Fulfills part 1. No point in me withholding work...

https://github.com/banyancomputer/on-chain-compliance-attestations

**Comment by ErinOCon** [comment]
Hi @laudiacay, thank you for the provided update. Can you confirm which portion of this project is pending funding?

**Comment by ErinOCon** [comment]
Thanks, @ita-c! I wanted to make sure I understood the amount of work completed thus far before proceeding with our consideration of this grant. In light of the macroeconomic climate, we are currently in the process of re-evaluating our budget and priorities for this fiscal year. This process is requiring additional review time. 

We appreciate your patience and will follow up when we have more information!

**Comment by ErinOCon** [comment]
Hi @okgardner, Thank you for all of your patience during our review process. I know it has been a considerable amount of time since our last update. 

Unfortunately, we will not be moving forward with a grant at this time. We look forward to learning how your work progresses and are wishing you all the best as you continue to build!
