### ISSUE TITLE
VideOracle Open Grant Application

### ISSUE THREAD

**Issue by codethazine** [filecoin-project/devgrants#1184]
# Open Grant Proposal: `VideOracle`

**Name of Project:** VideOracle

**Proposal Category:** `app-dev`

**Proposer:** `codethazine`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** "Yes"

# Project Description

VideOracle is a protocol to verify real-world events on-chain through video.

Currently, real-world events cannot be easily verified in a reliable manner. We have thus designed a protocol to verify events in a decentralized manner through video proofs.

We now want to develop a DApp on top of the protocol.

## Value

Today businesses and organizations are suffering from a lack of transparency over the verification of real-world events:
- Brands may want to verify that the shops execute in-store marketing as per requirements.
- Town councils and other public offices may wish to verify that road works are being correctly executed.
- Journalists may want to verify events through videos directly from the local community.
- Insurance companies may want to verify the state of insured properties and cars.
- Investment funds may want to verify the state of multiple properties in a fund.

  
VideOracle sets out to solve these issues through a decentralized and trustless verification protocol. The protocol's architecture is detailed below. Read our [Whitepaper](https://github.com/videoracle/wiki/blob/main/WHITEPAPER.md) or [Smart Contract](https://polygonscan.com/address/0xaf9835bb230bf70b966dfdba4fefe42839ec844c#codehere) to get a more detailed overview.

![1669480292676](https://user-images.githubusercontent.com/41583025/204505995-33309b04-6a7c-4889-8526-970aa91f2f6d.png)

## Deliverables

A React DApp built on top of IPFS for Video Proof storage, Fleek for hosting, and Polygon as a chain.

## Development Roadmap

**Milestone 1 - Wireframes / Market Research**
* Estimated duration: 2 weeks
* FTE: 3
* Costs: 8,000 USD

| Number | Deliverable          | Specification                                                                                                                                          |
|--------:|----------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1.     | Wireframes           | • Home	  <br />• Log-in section  <br />• Logged in home 	 <br />• Ask video proof	  <br />• View video proofs	  <br />• Submit video proof	  <br />• Vote video proof	  <br />• Dashboard              |
| 2.     | DApp development     | • Infrastructure set-up	  <br />• Home	  <br />• Log-in section                                                                                                      |
| 3.     | Business Development | • Verify the best business opportunity to start with between insurance’s due diligence, public sector, journalism, real estate, advertising and retail |	

**Milestone 2 - DApp development / User Discovery**
* Estimated duration: 2 weeks
* FTE: 2.5
* Costs: 6,000 USD

| Number | Deliverable          | Specification                                                                                                                    |
|-------:|----------------------|----------------------------------------------------------------------------------------------------------------------------------|
|    1.  | DApp development     | • Solution to prevent Video Tampering 	<br>• Ask video proof	<br>• View video proofs	<br>• Submit video proof	<br>• Vote video proof |
|    2.  | Business Development | • Conduct user interviews with Businesses	<br>• Write TOS and Privacy Policy                                                      |
	
**Milestone 3 - Testing DApp / UX**
* Estimated duration: 2 weeks
* FTE: 3
* Costs: 8,000 USD

| Number | Deliverable          | Specification                                                                            |
|-------:|----------------------|------------------------------------------------------------------------------------------|
|    1.  | DApp development     | • Testing<br>• Deployment                                                                |
|    2.  | Business Development | • Get at least 2 LOIs with businesses<br>• Business user onboarding	<br>• UX user testing |

**Milestone 4 - Bugfixing / Consumer Onboarding**
* Estimated duration: 2 weeks
* FTE: 3
* Costs: 8,000 USD

| Number | Deliverable          | Specification                                                                                                                      |
|-------:|----------------------|------------------------------------------------------------------------------------------------------------------------------------|
|    1.  | DApp development     | • Implement the feedback got from the UX tests and user on-boarding                                                                |
|    2.  | Business Development | • Define growth strategy for onboarding consumers	<br>• Get at least 10 completed video proof verifications                         |
|    3.  | Marketing            | • Spend the $5000 marketing budget on ads to get consumer Video Proofs	<br>• Reach at least 500 perspective users on a mailing list |

## Total Budget Requested

30.000 USD

2x Full-time Dev 4k a month
1x Full-time BD 3k a month
1x Part-time Designer 1k a month 
5k in marketing
1k in infrastructure cost (cloud, hosting, domain, etc.)

So in total time effort, we would have:
Development: 640 hrs
Design: 160 hrs
BD: 160 hrs

## Maintenance and Upgrade Plans

We want to use this grant to develop an MVP, get some traction, and subsequently raise a Seed round.

# Team

## Team Members

- Dario Finocchiaro @codethazine
- Anon @mastrogepp.eth
- Mattia Pomelli @mattiapomelli
- Jack Glacken @jackgdesignexplorer

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/dario-finocchiaro-a89419168/
https://www.linkedin.com/in/mastrogepp-eth-%E3%85%A4-65364b24a/
https://www.linkedin.com/in/mattia-pomelli-b857511b1/
https://www.linkedin.com/in/jackglacken/

## Team Website

https://videoracle.io/

## Relevant Experience

@codethazine - Sr. Full-stack Developer with 3+ years in consulting and 2+ years as co-founding member in Startups (Web3 and non). One of the core team members at the NFT Berlin Hackathon, where VideOracle started.
@mastrogepp.eth - BD with 3+ years in consulting and 2+ years as an Independent Consultant for Web3 Companies.
@mattiapomelli - Full-stack Blockchain Developer with 2+ years working as an Independent Consultant and for one of the leading protocols for borrowing and lending on top of the Algorand blockchain.
@jackgdesignexplorer - Sr. UX & Product Designer. One of the core team members at the NFT Berlin Hackathon.

## Team code repositories

https://github.com/codethazine
https://github.com/mattiapomelli

# Additional Information
VideOracle started at the NFT Berlin '22 Hackathon, where we were selected among the winning projects.
Contact Email: dario.finocchiaro@opensquare.art

**Comment by ErinOCon** [comment]
Hi @codethazine, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. We are wishing you all the best as you continue to build!
