### ISSUE TITLE
Next Step Microgrant: IPFS Computing Router

### ISSUE THREAD

**Issue by bq1024** [filecoin-project/devgrants#1185]
### 1. What is your project? (max 100 words)

IPFS Computing Router enables users to fetch datasets from the nearest IPFS nodes, and upload the training result to the IPFS gateway, or multichain.storage, whichever is faster.

### 2. Project links
  
Link to Github repo: https://github.com/Nebula-Block-Data/ipfs-computing-router
Link to demo or website, if applicable: https://www.youtube.com/watch?v=S8GYYJ09au0
License: Apache2.0 License 

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
This tool enables users to upload computing results to IPFS nodes directly, or upload to multichain.storage(https://www.multichain.storage), which will also upload to IPFS nodes and backup to the Filecoin network

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will use this grant to continue the development of the project, and also for tokens used to upload files to multichain.storage.
The project will be improved in the following ways:
- Searching and uploading files to the nearest available IPFS gateways automatically
- Adding file retrieval from IPFS and Filecoin networker feature
- Adding SDK support
- Providing better user experience

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
Winner of Data DAO Hackathon, Computing Over Data track.  https://dorahacks.io/buidl/3442
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
   Boqian Wang, boqian.wang@nbfsdata.com, https://github.com/bq1024, Project Mananger
   Mike Li, mike.li@nbfsdata.com, https://github.com/mikeli2022, Developer

* How did you learn about our microgrant program?
   From Filecoin community
* If your project was created as part of an event or hackathon:
   Data DAO Hackathon, https://dorahacks.io/buidl/3442#intro

**Comment by dawnkelly09** [comment]
Hello! I am reviewing your grant application and am seeking some additional information. Can you please have the GitHub user [claydrone](https://github.com/claydrone) post here to confirm they are aware of this grant application and are part of this team requesting funding? All repo contributions seem to have come from this user; however, I don't see their name or contact information on this application. Thanks!

**Comment by bq1024** [comment]
> Hello! I am reviewing your grant application and am seeking some additional information. Can you please have the GitHub user [claydrone](https://github.com/claydrone) post here to confirm they are aware of this grant application and are part of this team requesting funding? All repo contributions seem to have come from this user; however, I don't see their name or contact information on this application. Thanks!

Sure!

**Comment by claydrone** [comment]
> Hello! I am reviewing your grant application and am seeking some additional information. Can you please have the GitHub user [claydrone](https://github.com/claydrone) post here to confirm they are aware of this grant application and are part of this team requesting funding? All repo contributions seem to have come from this user; however, I don't see their name or contact information on this application. Thanks!

Hi, I am aware of this grant application and am part of this team requesting funding. Thank you.

**Comment by ErinOCon** [comment]
Hi @bq1024, this microgrant has been approved! We will send an email to confirm payment details. Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

Thank you for the confirmation, @claydrone!
