### ISSUE TITLE
The descrowhub project

### ISSUE THREAD

**Issue by AdjacentHub** [filecoin-project/devgrants#1191]
### 1. What is your project? (max 100 words)
The Self-service Escrow Platform demo/prototype runs on Goerli Testnet with GoerliETH. 
In the Search by escrow ID just type 1 or 2 or 3, etc. Disputes can be resolved by the admin to refund the buyer according to the contract escrow mechanics.

The descrowhub project can be installed into any type of EVM-compatible network.
– The project is comparable to Upwork Escrow. It enables anyone to start a decentralized escrow business and the owner can benefit from the fee with the escrow clearance.

The escrow transaction is published on the blockchain once it has been created. Unless the set-terms are met by seller/buyer, neither party can withdraw any tokens. 

With the creation of “new escrow” multiply documents can be uploaded, images, NDA, Agreement documentation, Videos, PDF, etc.

If more clarifications are needed after visiting https://descrowhub.vercel.app/ and checking the repo, please email: [escrow@descrowhub.com](mailto:escrow@descrowhub.com)

Contract: https://goerli.etherscan.io/address/0x217Cd81d61B32a6de0CA401C35B4847010ccA087 

### 2. Project links

Link to Github repo: https://github.com/AdjacentHub/descrowhub 
Link to demo or website, if applicable: https://descrowhub.vercel.app/ 
License: MIT  

### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

It uses IPFS/Filecoin decentralized object storage through Web3Storage to store metadata and other files and retrieves uploaded files via w3s.link http endpoint in the escrow contract.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

It will be used to expand the project. Currently it supports all EVM chain native currency. We want to upgrade the project to all of the EVM-compatible chains to implement storage for new, current, custom and existing erc20, bep20, trc20 and other chain tokens, hence, significantly expanding the IPFS/Filecoin storage facilities to stakeholders.  The grant will also be used for producing user documentation, build and deployment guide. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, progress report will be presented and can be followed in the github.
  

### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: 
N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Name: Mike Hoekstra, Email: [escrow@descrowhub.com](mailto:escrow@descrowhub.com), Github account: https://github.com/AdjacentHub, Role: 0xBrain Exercise Hobby Developer 

* How did you learn about our microgrant program?
I was looking into Filecoin roadmap and came across the grants program.

* If your project was created as part of an event or hackathon:
N/A
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
N/A
  * Please link to your hackathon submission
N/A

**Comment by ErinOCon** [comment]
Hi @AdjacentHub, thank you for your proposal. We will not be moving forward with a microgrant at this time, but recommend checking out [our hackathons](https://hackathons.filecoin.io/)! Wishing you the best as you continue building!

**Comment by AdjacentHub** [comment]
@ErinOCon Can you please enlighten more specific the reason for not moving forward with the microgrant? More insight would be highly appreciated. Thanks
