### ISSUE TITLE
Open Grant Proposal: Testground 

### ISSUE THREAD

**Issue by brdji** [filecoin-project/devgrants#1192]
# Open Grant Proposal: `Testground`
 
**Name of Project:**
Testground
 
**Proposal Category:**
 `devtools-libraries`
 
**Proposer:**
Darko Brdareski - `brdji`
 
**(Optional) Technical Sponsor:**
N/A
 
**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes
 
# Project Description
Testground is a platform for testing, benchmarking, and simulating distributed and p2p systems at scale.
The Bloxico team, along with PL collaborators, has implemented new features and infrastructure improvements to the project in the past 7 months. We have brought Testground to AWS EKS, allowing for easier maintainability and customizability of the action cluster.

After close examination of the roadmap, this proposal aligns with the vision and direction of the IPDX team. Bloxico is committed to work on features that are our expertise, rather than features targeted by the IPDX team. This way, we can leverage our extended experience in infrastructure development, along with our knowledge of Testground, to further develop and make Testground as useful and attractive as possible for Web2 and Web3 teams, while still supporting the efforts of the IPDX team.
 
## Value
1. Testground as a service (TaaS) is very useful for testing any distributed project. Being able to integrate it as a part of a CI pipeline is of great benefit to many development teams.
 
## Deliverables
- Testground cluster improvements, including (but not limited to): Improving cluster performance (both during image building, and run execution), migrating cluster deployment to Terraform, and investigating IPv6 support
- Upgrade Kubernetes cluster Kubernetes version, along with any accompanying resources and tools. We are currently using v1.22, and should strive to upgrade to the latest one available (currently sitting at v1.24).
- Additional features, agreed upon in the future with key stakeholders

The Bloxico team plans to create a public fork of the Testground Github repository, so we can develop, test, and iterate on features with greater speed. By creating a public fork, development can proceed without interfering with the work of the IPDX team. Once one or more features have been completed, a feature PR will be compiled and submitted by the Bloxico team, so that it can be reviewed and merged into the main repository.

We will also maintain a demo branch in the main Testground repository, from which features will be demoed once they are deemed complete by the Bloxico team. We propose that a milestone be approved once the demo has been approved by the IPDX team, so the Bloxico  team can proceed onto the next milestone, while the PR is being reviewed and discussed.

Should the IPDX team request an expansion of a feature PR’s scope, both teams will discuss the desired changes, so as to come to a mutual agreement, while minimizing the risk to the roadmap.
 
## Development Roadmap
 
**Milestone(s)**
 
**Milestone 1**
- Identify outdated parts of the infrastructure: Certain parts of the cluster are deprecated, and others are reaching their end of support date (e.g. CNI plugins, helm charts, etc.).  To continue running the cluster on EKS, we must replace the outdated libraries with newer versions, and the first step is to perform a deep dive into used cluster resources.
- Integrate AWS Cloudwatch: The cluster can be easily connected to many other AWS services; integrating Cloudwatch would allow users to access logs and metrics more easily, and it can be integrated further with any existing AWS pipeline.
- Investigate and implement autoscaling. This will be implemented both node-side and pod-side.
- Authentication
 
 
Est Milestone Date:
Q1 2023
 
**Milestone 2**
- Implement Multus v4 at the moment of its release.This should bring support for (un)plugging Network Interfaces on running containers, allowing us to use other CNIs than Weave. 
- Migrate Testground images to ECR: Moving all Testground images from DockerHub to ECR would allow easier management of releases.
- Benchmark secondary CNIs: Provided we can utilize Multus’ v4 on our running cluster, we should benchmark additional secondary CNI plugins to find the most performant one for our cause.
- Terraform scripts: The deployment of the action cluster is currently handled through a tool named `eksctl`. We believe that writing the new infrastructure scripts in Terraform would increase stability and maintainability. Terraform is a more robust solution.
 
Est Milestone Date:
Q2 2023
 
**Milestone 3**
- Continue upgrading outdated resources: Provided we have identified more deprecated resources in phase 1, we will upgrade them to the latest possible stable version.
- Investigate IPv6 support: IPv6 support would greatly expand the supported features and address space of the cluster; however, its support depends on the CNI plugins, and their performance. Therefore, we will first investigate if the available CNI plugins support IPv6, and proceed with integration if they do.
- Update and expand the infrastructure documentation
- Continue fixing issues and maintain service integrity
- Add new features, starting with those most-requested by the community and key stakeholders
 
The goal for this milestone will be to implement features that have been selected by the community and stakeholders.
Since it is currently unclear what new features will be most impactful, the Bloxico team working on the Testground will keep an ongoing
list of desired (and possible) features, from which key features will be selected.
 
Est Milestone Date:
Q3 2023
 
 
## Total Budget Requested
 
The project is time and material based, and the average hourly rate of the team is estimated at $85.
Our overall estimate is that each milestone will take between 2-3 months, based on IPDX team feedback and the selected issues.
 
## Maintenance and Upgrade Plans
 
Once the outlined milestones have been completed, a new plan for long-term maintenance will be drafted by the Bloxico team and stakeholders. The Bloxico team sees the maintenance of this project as something of great importance, both in accrued technical knowledge, and the value the Testground brings to other dev teams and the community.
 
# Team
Bloxico
 
## Key contributors
@brdji
@dektech
@djoroslav
 
## Team Member LinkedIn Profiles
 
https://www.linkedin.com/in/darko-brdareski-b7463b63/
 
## Relevant Experience
Our team is composed of experienced devops engineers and developers who have worked on scalable systems in the past. As we have familiarized ourselves with Testground in the past several months, we are eager to continue developing the project further.
The team will be composed of 1 developer and 3 devops engineers. This composition of roles reflects the needs of the proposed improvements, where most of the tasks focus on improving the infrastructure of the service.

**Comment by ErinOCon** [comment]
Hi @brdji, thank you for your proposal. We will not be moving forward with a grant at this time, but can be sure to keep this proposal in mind as we continue to explore grant opportunities. Wishing you all the best as you continue building!
