### ISSUE TITLE
Next Step Microgrant: Bounty-based Filecoin Ecosystem Growth

### ISSUE THREAD

**Issue by Randomacy** [filecoin-project/devgrants#1193]
### 1. What is your project, and what problem does it solve? (max 100 words)

Onboard is a bounty aggregator and a bounty hunter community. We help bounty sponsors get higher-quality content in their ecosystem through engaging highly curated bounty hunters.  

On Onboard, senior hunters conduct brainstorming sessions to guide hunters or formulate a strategy to tackle bounties, e.g., create product, write articles, etc.

While Onboard currently aggregates bounties from various platforms, we would like to receive Filecoin grant funding to hold our own campaigns for Onboard’s hunters. We would like to apply for a small grant to directly incentivize Onboard hunters to create educational content - technical and non-technical - for the Filecoin community.

### 2. Project links
  
Link to demo or website, if applicable: https://onboard.super.site
Deck: https://bit.ly/onboardintrodeck

  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Currently, the platform aggregates and curates a collection of interesting bounties that further the development of an ecosystem. For example, a request for a tutorial or an ecosystem analysis summarised as a blog post. We also help hunters tackle bounties create better and higher quality content through guided hunting as a community as hunting can be a lonely and daunting activity.

Instead of aggregating bounties reactively, we would like to use this grant as a way to proactively and directly incentivize bounty hunters to create more content, products, and tutorials for the Filecoin ecosystem. 

We are requesting USD$5,000 for the following content:

1. Ecosystem content bounty: US$100 x 10 = US$1,000
Ecosystem content refers to any content that describes, explains, or expands upon the Filecoin ecosystem.

2. Technical content bounty: US$250 x 6 = US$1,500
Technical content refers to content that helps developers build things, e.g., tutorials, 101s, best practices, how to use documentation effectively, etc.

3. Product bounty: US$500 x 4 = US$2,000
This is bounty for more technical products, e.g., product requests for dApps in the Filecoin ecosystem.

4. Management and guidance fees/mentorship: US$500 x 1 = US$500
This is used to incentivise bounty leaders to lead bounties, especially if the hunters are experienced.

### 4. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes  

### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Jackie Tan, jackie@tribex.co, @Randomacy, Product Lead

* How did you learn about our microgrant program?
Dropped Filecoin grants team an email, and was redirected here by Sonia.

**Comment by dawnkelly09** [comment]
Hello! In reviewing your grant application, I am unable to locate a link to your code repo. Please provide a link to the open source repo for this project before we can consider it further. Thank you!

**Comment by Randomacy** [comment]
Hello @dawnkelly09! Thank you for reviewing my application. I don't have a code repo for this idea, because
1. Hunters who are tacking written technical/non-technical content will submit their pieces to popular developer platforms, i.e. Dev.to and Medium (after our vetting of course)
2. Hunters who are tackling the product bounties will be working off the product's repo

Happy to set up a repository just to consolidate the content first - would that work?

**Comment by Randomacy** [comment]
Hello @dawnkelly09! Wanted to follow up with this, and see if there were any more comments / questions that I needed to adddress

**Comment by ErinOCon** [comment]
Hi @Randomacy, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time. 

Wishing you the best with your building progress!
