### ISSUE TITLE
Bazooka - Gaming Infra (ChainLink Fall 2022)

### ISSUE THREAD

**Issue by piyush-master739** [filecoin-project/devgrants#1197]
### 1. What is your project, and what problem does it solve? (max 100 words)
‘First Person Shooter’ is one of the most sought after genre in gaming. Every first person shooter game requires one thing — good aim. At bazooka, the goal for us is to store user’s “aim” progression on chain and make their skill provable. 

Using the Bazooka dApp, the user can practice their aim as well as log their results to the polygon blockchain, which helps the user prove their skill using NFTs as well as just their wallet address. 

Bazooka can then be integrated to other gaming applications like P2E games, who can then use this data to asses various parameters for their usecase.

Example - A P2E games requires the user’s aim-skill-level to make sure their opponents are rightly matched (good match-making UX for games). Using Bazooka, this data is made available, thus providing a good user experience. We believe that we are building a core skill tracking piece of gaming infrastructure for web3.

### 2. Project links
  
GitHub Main Project - https://github.com/piyush-master739/bazooka
OrbitDB - https://github.com/piyush-master739/bazooka/blob/master/src/orbitdb/storage.js
Link to demo or website, if applicable: https://vimeo.com/772623640
License: MIT
Devpost: https://devpost.com/software/bazooka-shooting-game
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
We use IPFS to store user’s data publicly using [web3.storage](http://web3.storage/) and use [NFT.storage](http://nft.storage/) for handing out skill-based NFTs as well!
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. We want to go beyond the first-person shooter genre, and tackle other genres like MOBA, Open World, RPGs, Battle Royale.. We want bazooka to be web3 game devs, to help track user’s skills (Think of Experian and Equifax for web3 gaming skills)
2. Convert js to ts for better type safety
3. Promote our product with various gamers and developers to onboard for different use cases
4. Work with games like [krunker.io](http://krunker.io/) to work on various use cases

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes I agree.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes it does.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 https://devpost.com/software/bazooka-shooting-game
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Name - Piyush Nair
Email - chopsticksmaster1999@gmail.com
GitHub Account - Piyush-Master739
Role - Founder & Developer

* How did you learn about our microgrant program?
Through the hackathon 
* If your project was created as part of an event or hackathon - Yes part of Chainlink Fall 2022
* What was the name of the event?
  
Chainlink Fall 2022 - https://devpost.com/software/bazooka-shooting-game

**Comment by ErinOCon** [comment]
Hi @piyush-master739, we will not be moving forward with a grant at this time. Thank you for your proposal.
