### ISSUE TITLE
Next Step Microgrant: Remember Me

### ISSUE THREAD

**Issue by shivansh-link** [filecoin-project/devgrants#1199]
### 1. What is your project, and what problem does it solve? (max 100 words)
Remember me is a P2E game, where users can test their memory against other users and earn RM Tokens. These tokens can be used to unlock more game time, and enables a micro-economy for the player base. Think of *remember me* as the first iteration of a set of games (Zynga esque), where all of them will have a shared economic model for users to collaborate and have fun.

Making the project open source will help devs create their own game using existing game engines like Unity to create a more open and decentralised gaming platform.

### 2. Project links
  
Link to Github repo: https://github.com/shivansh-link/remember-me
Tableland Usage: https://github.com/shivansh-link/remember-me/blob/master/src/pages/index.ts
Demo link YouTube - https://www.youtube.com/watch?v=I-OcNKDLhN8
License: MIT License

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
We use Filecoin to store user data using [Tablelands](https://tableland.xyz/), and [NFT.storage](http://nft.storage/) for storing user’s NFT Meta Data.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
- We want to work on developer tooling to help devs launch other games on the RM (Remember Me) Platform while helping them have easily selectable tokenomic models which can use RM tokens as well.

Some tokenomics we want to support:

1. Single token reward model (Custom Token)
2. Dual token reward model (Like StepN)
3. Skill Curve reward model

- Implementing a DataDao structure allowing early participants in the community to vote on game development and upgrades making Remember Me composable and democratic.

- We want to provide a whole new array of in-game tokenomics to our users.

- Hiring a design team, UI/UX & Graphic designers.

- Also, we want to work on the SDK in various other languages, like c# and java, to help more legacy game devs get on board web3. For this, we will be using JSON RPC calls, and will require a log of work

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
https://devpost.com/software/remember-me-vqb2tz
Chainlink Fall 2022 (Filecoin - *Bonus* Gaming, Metaverse, Daos & NFTs (Oh My!)
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Shivansh Yadav (Name)
xtremedev786@gmail.com (Email)
https://github.com/shivansh-link (GitHub)
Sole Developer & Designer (Role) - Shivansh Yadav 

* How did you learn about our microgrant program?
During the hackathon presentation by Dawn Kelly and going through the sponsor prizes list.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? Chainlink Fall 2022 Hackathon
  * Please link to your hackathon submission
  https://chainlinkfall2022.devpost.com/

**Comment by ErinOCon** [comment]
Hi @shivansh-link, we will not be moving forward with a grant at this time. Thank you for your proposal.
