### ISSUE TITLE
RFP: Block explorer

### ISSUE THREAD

**Issue by pooja** [filecoin-project/devgrants#12]
We just put out our first RFP for a Filecoin block explorer! You can read the details of the RFP at [this link](https://github.com/filecoin-project/devgrants/blob/master/rfps/rfp-block-explorer.md), and add any questions/comments you may have in this issue!

**Comment by lrgeoemtry** [comment]
Should this be specific to filecoin ? Or can an explorer that includes IPFS hashes be submitted?

**Comment by lrgeoemtry** [comment]
@julianapeace

**Comment by Anish-Agnihotri** [comment]
Just added my proposal to #29. Looking forward to seeing the submissions from contributors.

**Comment by pooja** [comment]
@lrgeoemtry It should be specific to Filecoin, please!

@Anish-Agnihotri Sounds great! We are looking forward to reviewing the proposal :)

**Comment by lrgeoemtry** [comment]
Thanks @pooja i just sent our proposal to our team and then we'll make a PR :)

**Comment by lrgeoemtry** [comment]
planning on submitting by EoW @pooja  :)

**Comment by Anish-Agnihotri** [comment]
Hey folks, just wanted to bump the thread and see if there was any timeline for when we should be expecting a proposal review.

**Comment by pooja** [comment]
Hey! Thanks for the ping. This week! We’ve already started reviewing and will reach out to teams this week.
