### ISSUE TITLE
[Chainlink Fall22 IPFS Runner Up] Chameleon - Topographic Data Library for Earth and Plant Science Research 

### ISSUE THREAD

**Issue by Zhixuan0318** [filecoin-project/devgrants#1201]
### 1. What is your project, and what problem does it solve? (max 100 words)

Chameleon is an IPFS-powered topographic data library that provides high-quality and high-resolution topographic data for earth and plant science-oriented research. As a data collector and provider, you can now contribute various types of topographic data (as well as topography-derived raster data) to Chameleon. Chameleon will act as the hub to aggregate all of the contributed data from the IPFS clusters. As a user (institutes, researchers, etc), you may now easily perform an instant download of topographic data from Chameleon with only a few simple clicks, as Chameleon will handle all IPFS fetching jobs (sometimes Chameleon will split big data into chunks before storing on IPFS, then will only process the combine of data during fetching).

### 2. Project links
  
Link to GitHub repo: https://github.com/Zhixuan0318/Chameleon
Link to demo or website, if applicable: https://ipfs-chameleon.xyz/
License: MIT
  
### 3. How is IPFS, Filecoin, or related technology used in this project?

![bts](https://user-images.githubusercontent.com/69501009/201462004-0d756665-b78f-4126-bfcb-659cf9ae909a.png)

Chameleon is the heart of the whole interaction process, which communicate with the IPFS clusters via Pinata, Chameleon Database, Users (researcher, institute, or any party), and the Polygon Blockchain.

- **IPFS**: Forming a network to handle all the processes of high-quality, high-resolution topography data and their respective metadata version.

- **Researcher**: Capable of downloading topography data from the Chameleon Open Data Library instantly. Chameleon will handle the IPFS file fetching job as well as the IPFS-fetched data pre-processing, after which the files will be downloaded to the user's local machine.

- **Chameleon Database**: Managing the metadata for all contributed topography data. It also manages metadata version updates when the data owner modifies the data info and details and then writes back to the IPFS.

- **Polygon Blockchain**: The foundation of Chameleon Sponsor, which allows users to make financial contributions to the data collector or provider.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective?

![multihub](https://user-images.githubusercontent.com/69501009/201409519-e897a6bb-c176-4c05-aa50-168dce86a16c.png)

Chameleon is now simply a single hub network, which means that all users must rely on the platform and complete all tasks in this main hub. The Chameleon project's next major step is to bring Mini Chameleon to the network. In other words, we'll use Mini Chameleons to create a multi-hub Chameleon network. But how exactly?

### <u>What is Mini Chameleon?</u>

Mini Chameleons are nodes (or mini hubs) that branch off the main hub (Chameleon) and contribute to expanding the network as a whole. Anyone, including research institutes, businesses, universities, and individuals, can run a mini-chameleon and act as a mini-hub in the Chameleon network. All mini hubs can also serve as the main hub, forming their own mini Chameleon network. Consider how powerful and efficient it would be to expand the entire topography data network! Here are some of the features of the Mini Chameleon:

- Direct data calling from the main hub via IPFS and cloud computing using topographical data

- Create a private Chameleon network with advanced customization for personal usage or topography research with public access restrictions.

- Pre-processing of topography data by hashing before storing on IPFS, as well as decoding of IPFS-fetched topography data

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?

Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions

Submission: https://devpost.com/software/chameleon-iukahc
Demo Vid: https://youtu.be/H5bJX-bwPU0
  
### Additional questions:

Tan Zhi Xuan (t.zhixuan318@gmail.com)
GitHub: https://github.com/Zhixuan0318
Linkedin: https://www.linkedin.com/in/tan-zhi-xuan-805836196/

* How did you learn about our microgrant program?

I'm a developer in the IPFS community and bringing several projects to the IPFS space.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? Chainlink Fall22
  * Please link to your hackathon submission: https://devpost.com/software/chameleon-iukahc

**Comment by ErinOCon** [comment]
Hi @Zhixuan0318, it looks like you have found a lot of building opportunity through our microgrants program! For next steps, I would highly recommend checking out this [accelerator program](https://www.notion.so/ecosystem-wg/Protocol-Labs-Accelerator-Program-d45d8792a7d544eca9beb7d3e3d3b05d). 

We will not be moving forward with a microgrant, but wish you the best as you continue building!
