### ISSUE TITLE
VideoStreamingIPFS

### ISSUE THREAD

**Issue by frankpn** [filecoin-project/devgrants#1205]
### 1. What is your project, and what problem does it solve? (max 100 words)

My project is a video streaming web app that uses IPFS as the backend storage. It allows people to store their videos on the internet without having to give them to private companies that may want to suppress or gather data from them. Instead you can store them on the IPFS network and be able to access them anywhere.

### 2. Project links
  
Link to Github repo: https://github.com/frankpn/VideoStreamingIPFS
Link to demo or website, if applicable: https://www.youtube.com/watch?v=z6tvo5cQXHs
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

  
IPFS is used to store all the video files

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

To improve this web app I would like to make a search feature to allow you to search for your videos based on the names/titles of the video you have stored on the app. To add this search feature I would create a hash map (dictionary) for every video when it is uploaded to the app. So then we can search this hash map for the key which would be the name of the video and the value from this key search would be the video we would like to get back. 

I would also like to build a login page for the app so that people can have accounts. To add this login feature I would use the flask library flask-login.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes I will share the grant reports upon request and the final grant report at the end of the 3 months

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  N/A
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @frankpn, thank you for your proposal. We will not be moving forward with a grant at this time. Wishing you the best as you continue building!
