### ISSUE TITLE
Filecoin Green:  SeaTrees Ocean Positive NFT

### ISSUE THREAD

**Issue by kwhilden1** [filecoin-project/devgrants#1206]
# Open Grant Proposal: `SeaTrees Ocean Positive NFT`

**Name of Project:**. SeaTrees Ocean Positive NFT

**Proposal Category:** green

**Proposer:** kwhilden1

**(Optional) Technical Sponsor:** Alan Ransil and Marc Johnson

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:**  "Yes" 

This proposal was originally submitted on September 30, 2022, under a different username (kevin-SSURF). Due to issues with that account being flagged, the proposal is now submitted by the same person using their personal Github account.  

# Project Description

Need:  Solutions to climate change need to accelerate rapidly, and blockchain should be a core part of that effort. However, blockchain is being under-utilized and even demonized by the environmental movement. We need positive solutions that re-frame the role of blockchain as a positive solution for climate change.  

Solution:  [SeaTrees](https://www.sea-trees.org/) will use the power of NFTs and blockchain to create stronger individual engagement with reversing climate change. Using our unique surfing NGO perspective to radically change how people see the value of blockchain in the climate world. We believe NFTs can be used in a new way that creates a significant “system change” opportunity. This would include both research data, as well as an application for users to use filecoin green's platform to demonstrate supply side eco-sustainability. (via SealStorage.io)
 
SeaTrees NFTs will be soul-bound (non-transferable) and used as digital receipts to prove an individual has taken a positive action on climate change through our SeaTrees platform. Then we will use all tools available to create “utility” and increase tangibility of impact and engagement. Such as, multi-media updates, impact dashboards, GPS coordinates of SeaTrees planted, project info through SeaTrees impact viewer, and 3D models of restoration projects (see coral [model example](https://www.youtube.com/watch?v=zabcrcIz16E) and [final video](https://www.youtube.com/watch?v=zaQvbv2-AsI)).

We expect SeaTrees Ocean Positive NFTs to serve as the core experience framework for other NGOs to build their NFT programs.

A sample of the expected model for a single SeaTrees Ocean Positive NFT includes: 

- Cover Art (jpeg)
- NFT table of contents (jpeg)
- Use of Funds Declaration (pdf)
- Tax Receipt (pdf)
- Certificate of Retirement (PDF)
- Impact Report (file format TBD) - file type tbd:will be updatable
- Video Stream Access - (wave)
- Audio (mp3)

Note: [SeaTrees](https://www.sea-trees.org/) is a program of California-based 501c3 non-profit, [Sustainable Surf](http://www.sustainablesurf.org/). SeaTrees protects and restores blue carbon ecosystems around the world, and inspires both individuals and corporations to take action. SeaTrees is our primary program that has the most recognition around the world, including in the tech sector. Learn more about our [vision here](https://www.youtube.com/watch?v=egfsj9j3gOU).

## Value

Benefits:  We can change the narrative about blockchain and climate change, by enabling an innovative NGO to rapidly scale up their ocean-focused blue carbon climate change solutions with the highest credibility. SeaTrees sees this as a major opportunity to increase donor engagement and our ability to raise significantly more funding for blue carbon ecosystem restoration.

Risks:  The majority of the risk falls on SeaTrees, however we feel the risk to our reputation and donor base is very low. We are confident that we can tell an outstanding story around this project, or else we wouldn’t do it.   Other risks include a loss of time and money if the project is not successful.  We  have limited risk in harming the reputation of blockchain and our other partners, because the non-transferable NFTs will avoid ponzi-nomic skepticism, and the whole system is based on Filecoin Green with net-zero CO2 emissions.

Execution risks:  it’s all about funding. As a non-profit, we have limited financial resources, and will not be able to launch this project with grants. The initial cash outlay is the barrier. Once built, we have the funds for operations, including software maintenance and program operations, sales, and marketing.  

Other points to consider including:  
- FC is looking for use-cases for their real-time dashboard
- End-to-end sustainable storage
- Partnership with credible NGO to help promote FC to the external world
- Access to corporate and science partnerships (Salesforce, Boardriders, Scripps, etc…)
- Storytelling collaboration

## Deliverables

First of its kind NGO website with integrated data stored on FilecoinGreen storage infra

- Ability to produce multi-asset and file NFT framework for other NGOs to replicate
- Ability to see information related to the geo-location of your donation
- Ability to use NFT to gain access to live/file streams to show how funds are spent
- Ability to publish and provide transparent access to research data.

## Development Roadmap

**Business Vision & Key Objectives** 

- Blue Carbon Ecosystem Project Development
    - SeaTrees develops blue carbon projects (see [current projects](https://sea-trees.org/pages/projects))
    - SeaTrees quantifies impact on projects (MRV - monitoring, reporting, verification)
- SeaTrees Impact Database (on-chain)
    - Records results from project verification. Whenever we plant a SeaTree, it’s recorded on the blockchain database, along with all associated impact metrics and multi-media content. Also, whenever a SeaTree is “retired” on behalf of a donor, this is recorded too on the database.
    - Data storage on FC-Green blockchain, via SEAL node operator (guaranteed sustainable facility vis SealStorage.io) 
- Front-end website visualizer
    - Immersive custom viewer of database, for anyone to explore the impact of SeaTrees projects on the SeaTrees website and see the record of retirement
    - Viewer includes ways to access multimedia content developed by SeaTrees
- NFT minting, distribution and management
    - Aspen for NFT merchandising and minting, with front-end experience and apps developed by Mint Werx. (e.g. Immersive website, NFT viewing gallery, reporting dashboards, user interfaces)
- Payment rails
    - Shopify powers SeaTrees website currently
    - Salesforce is being considered for a new gift management platform (CRM), which may include custom payment solutions and integration.  
- End-user utility tooling
    - Multi-media news and updates from SeaTrees through NFT ownership
    - “Donorship Globe”, displaying plots (lat/long) of seatrees that were publicly sponsored by brand sponsors and patrons
    - Token-gated discounts with SeaTrees brands and affiliates
    - Token-gated access to exclusive events and discussions (via Discord)
- Salesforce enterprise application offerings
    - CRM Gift Manager Suite
        - Automatic Reporting
        - Non-profit specific accounting features (e.g. restricted vs. general donations)

## Total Budget Requested

$200,000

[Website concept example](https://fusion92.sharepoint.com/:p:/s/mintwerx/EZU_90AP2t1DiJL-Q3_BaFEBQ33NIH0HB2XAzUUuM6ntmA?e=huibPD)

*Note each phase is approx 2-4 weeks.

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-220c1b6f-7fff-c3e4-d291-9b07d594a462"><div dir="ltr" style="margin-left:2.25pt;" align="left">

Est* Timeline: 2 - 4 Mo. | Phase
-- | --
Hire Project Manager | I
Discord Build & Community Development | I
Program Strategy | I
Public Research Database Kickoff | II
Interactive Web3 Website Design (UX/UI) | II
NFT Artwork + Illustrations | II
Interactive Web3 Website Development | III
Dynamic CMS Donor Portal & NFT Content Media Player | III
Payment Setup | III
Full Website Launch | IV
Public Research Database Launch | IV
Matching Gift Manager (Post - Launch) | IV

</div></b>

  

| SeaTrees x Filecoin Green | Budget | Comments
| ----- | ------ | ------ |
Interactive Web3 Website + Launchpad | $59,850 | Interactive multimedia website platform to purchase /view NFTs,  acknowledge donors, verify sustainability, and access SeaTrees climate research data.
Sustainable NFT Dashboard (via Filecoin Green API) | (Includes) | Public NFT dashboard (via Filecoin Green) to provide transparency/proof of end-to-end sustainability for NFTs minted.
Dynamic Global Donorship Map | (Includes) | Dynamic and interactive global map of SeaTrees planted, and carbon credits retired by donorship sponsors.
Dynamic CMS Donor Portal & NFT Content Media Player | $29,625 | Authenticated donor portal to view/interact with updatable, multi-media NFT content and access to other community utilities.
Program Strategy & Management | $11,500 | Mint Werx strategy and program management.
NFT Artwork + Illustrations | $12,500 | NFT artwork (1NFT) and related creative media content for marketing/communications. (+3% Aspen variable fee on donations for minting and on-site promotion)
SeaTrees Public Research Database + Public App | $22,525 | Blockchain platform to store and provide public access to SeaTrees research data. (Includes migration, data ingestion, and reporting application layers)
Payment Setup | $5,500 | $2k annually recurring fee.
Credit Card, Venmo, PayPal, Google Pay, Bank ACH |  (Includes)   | Est* 4% fee. Accept, report (donor + non-profit) *CRM API integration available in separate scope.
Crypto donations |  (Includes)   | 6% processing fee. Accept, convert, settle, report (donor + non-profit)
*Donors have option to cover processing fees |   | ~80% of donors may choose to cover fees
Matching Gift Manager | $5,000 | One-time setup; 25% of matching gifts received.
Constituent Data Enrichment | $3,000 | Per refresh, recommend updating annually.
Email, Cell, Employer, Verification & Append |  (Includes)  | Highly recommended data enrichment procedures to maximize benefits of matching gift manager.
Discord Build | $4,500 | Set up and organize discord channels, security, and automation.
Project Manager | $46,000 | Dedicated project manager to oversee business, marketing/communications, and community development.
Total Budget | $200,000 |  

## Maintenance and Upgrade Plans

Software maintenance: Software Vendors (Aspen, Mint Werx, Salesforce, Filecoin via SealStorage.io) will maintain the health of their software based on their ongoing R&D and SLA processes.

Community maintenance:  SeaTrees will operate community managers and develop media and marketing content 

# Team

## Team Members

- Kevin Whilden - SeaTrees
- Brian Spitz - Big Sky
- Jeremy Drane - Monax Labs, makers of Aspen NFT platform 
- Megan Cornelius - Monax Labs, makers of Aspen NFT platform 
- Ryan Sands - SVP, Mintwerx 
- Mark Horowitz - SealStorage.io 

## Team Member LinkedIn Profiles

[Kevin Whilden](https://www.linkedin.com/in/kevin-whilden-67b6585/) 
[Brian Spitz](https://www.linkedin.com/in/spitzbrian/) 
[Jeremy Drane](https://www.linkedin.com/in/nftjd/) 
[Ryan Sands](https://www.linkedin.com/in/ryan-sands-5216765/) 

## Team Website

[Sea-trees.org](https://sea-trees.org/)
[bigskyvc.com](https://bigskyvc.com/)
[aspenft.io](https://aspenft.io/)
[mintwerx.com](https://www.mintwerx.com/)
[sealstorage.io](https://www.sealstorage.io/)

## Relevant Experience

**>SeaTrees**** - SeaTrees is a non-profit directly supporting communities and scientists who protect and regenerate blue-carbon coastal ecosystems. This includes planting mangrove trees, restoring kelp forests, coral reefs, seagrass meadows, and conserving coastal watersheds.  The Sea Trees[ impact report](https://sea-trees.org/pages/sdg-master) documents over 2 million Sea Trees planted to date.  Brand Partners range from Salesforce to BoardRiders to Bank of the West.  Sea Trees believes the ocean has the superpower to reverse climate change and want to be the first to bring this story on chain. 

**>Big Sky Partners** - Big Sky is a founder-focused, early-stage fund based in Venice, California focused on clean energy, adventures sports & wellness, and web3. 

**>MintWerx** - Mint Werx is a premium Web3 creative and production studio that develops strategies and turnkey solutions for brands and creators. Harnessing the power of sustainable blockchain technologies, Mint Werx delivers cutting-edge, scalable and one-of-a-kind dynamic NFTs and platforms, producing, minting and activating authentic digital expressions that last a lifetime. Through these solutions, Mint Werx simplifies and brings together a complex array of technologies to empower ownership and build prosperous connections between collectors, consumers, communities and culture. Mint Werx is a division of Fusion92 ([Fusion92.com](https://c212.net/c/link/?t=0&l=en&o=3543540-1&h=3900587070&u=http%3A%2F%2Fwww.fusion92.com%2F&a=Fusion92.com)), a leading Chicago-based independent marketing innovation company founded in 1999. Learn more at [MintWerx.com](https://c212.net/c/link/?t=0&l=en&o=3543540-1&h=1975319774&u=http%3A%2F%2Fwww.mintwerx.com%2F&a=MintWerx.com). 

**>Monax Labs**, makers of the Aspen Platform -  Core team has been in crypto since 2013-14. Built first ever private permissioned chains, large digital asset data businesses in both risk and tax, a complete contract management system, akin to DocuSign, with a blockchain backend, one of the largest existing NFT marketplaces, and now a comprehensive NFT platform with both launchpad and marketplace capabilities including integrated legal contracting - ‘Aspen’ (platform is live and can be accessed via [APP](https://aspenft.io/) or [API](https://aspenft.readme.io/docs)).

**>Seal Storage** - https://www.sealstorage.io/home/#whyseal

## Team code repositories

Monax Labs, Aspen NFT documentation: https://aspenft.readme.io/docs

# Additional Information
_How did you learn about the Open Grants Program?_
[jeremy.drane@monaxlabs.io](mailto:jeremy.drane@monaxlabs.io) worked with [James Slazas](mailto:js@vault.link) on a different Filecoin project related to Vivid Labs.

_Please provide the best email address for discussing the grant agreement and general next steps._
[kevin@sustainablesurf.org](mailto:kevin@sustainablesurf.org)

_Please include any additional information that you think would be useful in helping us to evaluate your proposal._

### Ocean Positive NFT project – Data Description

Two key elements:

- SeaTrees Impact Database Blockchain
- Ocean Positive NFT 

**SeaTrees Impact Database Blockchain**

Records the data from every SeaTrees project, including “retirement transactions” that record when a donation is made from external donors.  Data is available for transparent inspection and visualization.  

SeaTrees develops projects around the world ([current list](https://sea-trees.org/pages/projects))

When a new project is approved, there are five types of data that will be collected over time:

- General project data (project name, location, partner, etc)
- SeaTree Units (number of SeaTrees “planted” by date)
- SDG impacts (qualitative or quantitative UN SDG metrics - [examples](https://sea-trees.org/pages/sdg-master))
- Media data  (photos, videos, articles about the project)
- Evaluation reports (episodic reports to confirm success of projects)

_SeaTree Units_

The key data is the number of SeaTree Units “produced” by a SeaTrees Project, which we define as follows:

- One mangrove tree planted
- One sq-ft of kelp forest restored
- One coral fragment placed into a restoration project
- One sq-ft of seagrass meadow restored
- One sq-ft of coastal watershed restored
- One ton of CO2 from a Verra certified project (called a “VCU”)

Some SeaTrees Units are physically planted, such as mangrove tree seedlings or coral reef fragments. Whereas kelp SeaTree Units are produced by clearing a sea urchin barren, and letting kelp spores re-seed the reef with a kelp forest.  So we use the terminology, “SeaTree Units produced”.  

Carbon is a special case. In that SeaTrees buys VCUs on the open market and holds them in our Verra registry account.  When a donor “buys” a VCU from SeaTrees, we retire the VCU on behalf of the donor on Verra’s registry ([example](https://registry.verra.org/myModule/rpt/myrpt.asp?r=206&h=175959)). This is a manual process for now, until Verra eventually figures out how to automate this on-chain.

_SeaTree Units Data Accounting Principles_

Each project operates on a unique timescale.  Some projects produce SeaTree Units in a single year, while others produce SeaTree Units over multiple years.  

Our current accounting practice is to record SeaTree Units produced in our google sheet on the date in which we send payment to a Project Partner.  Typically, we make 2-3 payments per-year to projects, and record inventory on the same date.

Subsequently, donors make donations to “retire” SeaTree Units that are available in our ledger. When a SeaTree Unit is retired, it is removed from our available inventory and we can no longer accept donations for that specific Unit.   

The retirement process is key for transparency and accountability.  Our donors want to know that their donation is connected to specific SeaTree Units, and those units cannot be sold again.

_General Donations_

Not every SeaTrees project can produce a quantified SeaTrees Unit, because some of the projects are research-focused vs. restoration-focused. Thus, some projects will accept donations without retiring an associated SeaTree Unit. So our system needs to have the flexibility to simply record general donations to a project.

**Ocean Positive NFT**

NFT acts as a record of donation that includes data and multimedia that makes tangible the impact of that donation.  

- Key SeaTrees data in the Ocean Positive NFT
- Retired SeaTrees Units associated with the donation
- Link to Verra retirement URL for transactions with carbon
- Donation amount and date
- Links to media from associated SeaTrees Projects

**Social Certificate of Sustainability** 

Once live, we intend to create a blockchain sustainability certification badge to include on the company website(s) and verify PFPs that meet our standards of sustainability.  For example on Twitter, if the metadata for the connected PFP meets our sustainable standards, a green halo could appear around the PFP. (vs. existing blue halos).

**Comment by ErinOCon** [comment]
Hi @kwhilden1, thank you for your proposal. We will not be moving forward with a grant this round, but would encourage you to consider applying for RFP opportunities in the future. Wishing your team the best as you continue building!
