### ISSUE TITLE
Next Step Microgrant: Radio Vaults

### ISSUE THREAD

**Issue by yourmercury** [filecoin-project/devgrants#1207]
### 1. What is your project, and what problem does it solve? (max 100 words)
Radio Vaults is a Technology  that would be used for uploading NFT assets and deploying NFT contracts, especially Music NFT Assets to IPFS. The perk of using this app is that you can permission (whitelisting access to assets) and track access to these assets and also count streams from NFT Marketplaces and wallets using the metadata. With the Meta-verse in view, music NFTs will be here too and so we are presenting a way to secure musicians assets from plagiarism (stripping metadata to make other NFT contracts) and serve as a decentralized streaming platform.

### 2. Project links
  
Link to Github repo: https://github.com/Songs-To-Radio/raadio-vaults/tree/master/backend
Link to demo or website, if applicable:  https://darling-truffle-5ce8ae.netlify.app/
License: MIT
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
Presently, Users create a Vault by uploading a music video (either lyric video, or a video with music cover), the web 3 metadata info and the music metadata. The application deploys these to IPFS using NFT.storage javascript API and then our server stores the metadata url and assets urls on our database and maps it to an access url from our endpoints. This is what the User would use in their contract thereby obscuring the real CIDs from those who want to access the assets. Now the user can control ( fo r the prototype, whitelisting domains is the major control option. Domains like Marketplaces and online wallets) access to their server using out server as middleware to IPFS.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
The next step we are taking is improving the whitelisting feature, Adding a blacklisting Feature, then research better ways to account for music streams ( as this would help in the valuation of the music NFT ).

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: https://devpost.com/software/radio-vaults
  
### Additional questions:
Polycarp Momoh, momohpolycarp@gmail.com, https://github.com/yourmercury, Lead Developer
Osarodion Osayande, josiahosarodion@gmail.com, https://github.com/sahrodion, frontend developer
Emmanuel Okotete, okotetedv@gmail.com, UI UX designer
Jacob Ryan, jacobryan258@gmail.com, Project Manager 

* How did you learn about our microgrant program?
Ans: A friend of mine saw what we were building and told me about the grant opportunity
 
* If your project was created as part of an event or hackathon:
 * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
 Ans: Chainlink Fall Hackathon

  * Please link to your hackathon submission
 Ans: https://devpost.com/software/radio-vaults

**Comment by ErinOCon** [comment]
Hi @yourmercury, this microgrant has been approved! We will send an email to confirm next steps.

**Comment by ErinOCon** [comment]
Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
