### ISSUE TITLE
Encryption supported by IPFS

### ISSUE THREAD

**Issue by encryptshare** [filecoin-project/devgrants#1208]
### 1. What is your project, and what problem does it solve? (max 100 words)
Upload anything, encrypt (aes encryption) with the given or your "own password" and share with your friends. All the benefits of web3.storage technologies over the public IPFS network with optional encryption. https://cryptshare.xyz/ solves enhancing your privacy, to improve and provide storage privacy to users.

### 2. Project links
  
Link to Github repo: https://github.com/encryptshare/CryptShare
Link to demo or website, if applicable: https://cryptshare.xyz/
License: MIT
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
Project is build on web3.storage. It provides all the benefits of web3.storage technologies over the public IPFS network with optional encryption. 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Expanding with dedicated dev time adding more storage options with Filecoin and to improve the overall UI for further explorations and better user experiences.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
N/A  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Ron Neele, storage@cryptshare.xyz, https://github.com/encryptshare, Dev.
* How did you learn about our microgrant program?
Via surfing on filecoin.io 
* If your project was created as part of an event or hackathon:
N/A
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @encryptshare, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time, but would encourage you to check out [a hackathon](https://hackathons.filecoin.io/)! Wishing you the best of luck as you continue building!
