### ISSUE TITLE
NFT E-shop

### ISSUE THREAD

**Issue by alextitonis** [filecoin-project/devgrants#1210]
# Open Grant Proposal: `NFT E-shop`

**Name of Project:**

**Proposal Category:** app-dev

**Proposer:** `alextitonis` 

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Please respond with either "Yes" 

# Project Description

The project is aimed for a clothing e-shop where users will be able to generate the clothes using Stable Diffusion and get the Clothe NFT as a receipt, but also the option for users to pay with NEAR tokens or Ethereum.

## Value

The project will make an easy implementation of Filecoin to Reactjs and automatic Minting.

## Deliverables
The base e-shop using react js and nft minting system upon checkout

## Development Roadmap

Milestone 1:
* Finish the translation system
* Fix the UI (css/ux)
* Implement the minting system
* Finish the checkout

## Maintenance and Upgrade Plans

We are going to upgrade the e-shop with an AI assistant chat.

# Team

## Team Members

Alex Titonis

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/alexandros-titonis-0ba061176/

## Team Website

https://artificial-leap.com/

## Relevant Experience

I've worked on different projects, but i've focused mostly on Games and Networking, also there are many open-source projects in my github profile.

## Team code repositories
https://github.com/Artificial-Leap/e-shop

**Comment by alextitonis** [comment]
Hey, please let me know if there is any additional information I can provide here to help out with this process!

**Comment by ErinOCon** [comment]
HI @alextitonis, thank you for your proposal. We will not be moving forward with a grant at this time. Wishing you the best as you continue to build!
