### ISSUE TITLE
DeCommerce - an ecommerce app for IPFS

### ISSUE THREAD

**Issue by jozefpinter** [filecoin-project/devgrants#1211]
# Open Grant Proposal: `DeCommerce`

**Name of Project: DeCommerce - Decentralized ecommerce for Web3**

**Proposal Category:** `app-dev`

**Proposer:** `jozefpinter`

**(Optional) Technical Sponsor:** `No`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** `Yes`

# Project Description
It is a decentralized ecommerce for Web3. You can run a shop on IPFS and accept BTC, ETH, XMR payments for goods and services.

https://github.com/ivyca-com/decommerce
ipfs://bafybeihum4fojabe7cmvwr4ozn42fw6xhew3qwhv6iy27buqybdtjrgjea/
https://www.ivyca.com/decommerce/

I want to build a desktop app in electron. DeCommerce is going to be more users-friendly. Because, for example, currently to add products you have to edit a JSON file, or to configure the eshop, you have to edit a JS file. This approach is not suitable for non-tech savvy users. With a desktop app you will be able to deploy a shop and its content on the IPFS network from a desktop app. I have been working on the current version (v1; currently v1.2) since January. It is a fully working product, but it is more difficult to set up and operate than, for example, Shopify. So v2 (an electron app) is going to be a second phase.

## Value

Decentralized ecommerce - without middlemen. No Middleman, no Bank, no Big Tech, no Government.

## Deliverables

With an electron app you will be able to deploy decentralized eshop on IPFS with a single click. Currently you have to edit files (JSON, HTML, JS).

## Development Roadmap

Working desktop app which is able to deploy eshop (files) on the IPFS network. Currently, I'm working on it alone, but I have 1 year of experiences with DeCommerce (ecommerce 10+ years, IPFS 1 year)

$5000 for first working desktop app - prototype
2 - 3 months

$5000 to polish the prototype so it is ready for public adoption 
- find/repair bugs
- graphic work
- marketing materials

1 month

## Total Budget Requested

$10'000

## Maintenance and Upgrade Plans

I want to make DeCommerce the main ecommerce app for IPFS. WooCommerce/Wordpress for IPFS.

# Team

## Team Members

Jozef Pintér

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/jozefpinter/

## Team Website

https://www.ivyca.com/

## Relevant Experience

I'm a software engineer with 10+ years of working experiences in field: Magento, PrestaShop, WooCommerce + Software development for Web3

## Team code repositories

https://github.com/ivyca-com

# Additional Information

Google
jozefpinter@gmail.com

**Comment by realChainLife** [comment]
Hi @jozefpinter thank you for the proposal, could kindly shed some light on the following questions from our initial review: 

- How many premium users are currently subscribed relative to the wider subscriber pool? 
- How many eshops have been deployed to date relative to completed transactions by end-users (buyers)
- How much data is currently being generated and stored on IPFS?
