### ISSUE TITLE
LEGACY - Perpetual Identity

### ISSUE THREAD

**Issue by motherdomains** [filecoin-project/devgrants#1212]
# Open Grant Proposal: `LEGACY: Perpetual Identity'

**LEGACY: Perpetual Identity**

**Proposal Category:** `app-dev`

**Proposer:** `TheLegacyNetwork`

**Technical Sponsor:** `Sarah Thiam / FVM Foundry F/1`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** `Yes`

# Project Description

[LEGACY](https://legacy.page/) is a Web 3 community and platform for capturing and preserving personal and institutional memoirs. Anyone can record their memoirs in whatever format with which they are most comfortable. LEGACY will certify ownership of the memoirs and store them, “forever”.

But how is ownership proven? It begins with Identity. Who created or submitted the piece? Who is granted rights to interact with it? Who is related to this Identity, and/or has permission to administer the content or data, even after the departure of the original creator? Are they a real person?

Presently, each of us hold dozens if not hundreds of individual Identities online, from email and social media accounts, to applications, forums, messaging, medical records, banks, government, travel sites, miscellaneous services, and more. Very rarely do they interact with each other, and in almost all cases we have to continually register the same core details. This heightens security and privacy risks, can often lead to errors or misinformation, and certainly is a misuse of valuable time.

Web3 moves towards collating our digital identities, where one core ID is relevant to almost every dApp and service provider that we may ever need to encounter. This empowers us, the individual user, to enable temporary access on a per-application level, for as long as we deem necessary. We can revoke our access to any dApp at any time; unless explicitly specifying, they shouldn’t store or scrape our data.

Through our forthcoming development process, we’ll enable cross-chain integration that ties Identity to Data Ownership. We’ll explore the concepts of Social Identity, Reputation, Self-Sovereign Identities, and how they interact with Data DAOs. We’ll develop FVM actors that integrate Identities and their respective levels of Access Control, into the FVM concept of Perpetual Storage, and what that means in the context of LEGACY: preserving valuable memoirs, stories and content, “forever”.

## Value

Our timeline seeks to enable FVM actors on the LEGACY dApp in time for the FVM’s mainnet launch scheduled for February 2023, as one of the very first dApplications on FVM.

While we've been building LEGACY, we realized that a [number of features](https://medium.com/@andreas.vogel/identity-access-control-licensing-life-cycle-management-in-a-web-3-context-explored-in-the-7832435dd8d5) are needed beyond our specific dApplication. We decided to separate our efforts into the development of a platform, called the LEGACY Network, that offers the common features and functionality, and LEGACY Page, our flagship dApp that sits atop it. We have developed a 6-9 months roadmap that reflects this. This will enable our open source SDKs and API to be made available to the wider Filecoin and compatible chain communities.

## What are the benefits to getting this right?
SSI, Iden3 and Polygon ID, as well as perpetual and perma-storage, are critical features for the continued success of Filecoin. Making these easily accessible and usable through FVM actors is a substantial benefit to the Filecoin community, as well as the common, useful mechanisms we anticipate discovering along the way.

## What are the risks if you don't get it right?
Technology risk: all of these technologies are bleeding edge, and unexpected problems can occur
Misspent time and resources

## What are the risks that will make executing on this project difficult?
Initial accessibility, viability and resiliency of FVM - i.e. will it reliably work well enough over its initial rollout?
Not finding the ideal developer candidates. (Mitigation: We've started building a candidate pipeline, and collectively we have considerable experience in hiring talent)
Environmental or social-political catastrophes

# Deliverables

This development grant application specifically focuses on the deliverables for the FVM go-live event. We are focussing on FVM actors around two major topics: Web3 Identity and Perpetual Storage. First, here are the key components forming the basis of our consideration.

## Web3 Identity
As described in [our recently published paper](https://medium.com/@andreas.vogel/identity-access-control-licensing-life-cycle-management-in-a-web-3-context-explored-in-the-7832435dd8d5), there are many types of identities, including “official”, as in KYC, social identity, communication identity, and wallets.

#### **Ownership**
We have defined the authentic ownership of memoirs (i.e. documents) via digital certificates in the form of NFTs. The owner is defined by the wallet address used for minting these NFTs. As of today we support ERC20 wallets.

But anonymous wallet addresses are not sufficient for applications like LEGACY.

#### **Social Identity**
The wallet address serves as an anchor for an identity.

The social identity of a person or institution in the LEGACY context is a social identity that comprises the entirety of the published memoirs of a person or institution, and their relationship with other people, events and locations.

While this social identity is implicit, we will integrate Soulbound Tokens as they become available.

#### **Reputation**
Social interaction may have social value, that leads to a reputation. Examples include publishing high-quality and relevant content or by making meaningful contributions to the community.

The value can be expressed numerically and a reputation score can be calculated. While the concept is broadly applicable, the specifics of the scoring algorithm depend on the values established in the communities.

#### Self-Sovereign Identities
Based on our research, Polygon ID and Iden3 (the open source project Polygon Id is based on) are the most promising SSI projects to date. We will include Polygon Id into our Identity system.

#### DataDAO
Identities play a critical role in Data DAOs. Often, DAOs require proof of personhood for voting, and the enforcement of, in our prototype instance, the one-vote-per-person rule. In our forthcoming cross-generational Guardians of Legacy DAO, these Identities are depended upon to preserve and maintain the LEGACY network.

### Deliverable: Integrated Identity
Users will have a LEGACY ID, that is a Decentralized ID (DID). The DID has additional context including Wallet address(es), a human-consumable handle and Self-Sovereign Identity (SSI).

Users’ wallets are used to mint their NFT, implying that the wallet holder is the owner of the document that is digitally certified by the NFT. The handle is a human-consumable identifier which also points to their LEGACY page.

The SSI, in the form of Polygon, provides “officially” certified claims, such as name, date of birth, country of residence, etc. This can be relevant for KYC and other use cases.
 
We will integrate these different types of identities under the umbrella of the LEGACY ID. We will also ensure compatibility with the forthcoming AT Protocol, as shown in Figure 1.

_Figure 1_
<img width="624" alt="LEGACY-FILECOIN-2-FIGURE1" src="https://user-images.githubusercontent.com/41924928/206141811-cda44330-91e8-4530-b4b3-d8e3dcb8ed11.png">

We will also provide test cases and documentation, including a research paper on Web 3 identities, and how to use them for document ownership, access control, Data DAOs and other use cases.

### Deliverable: Data DAO and FVM actors for identity-based rules enforcement

Our FVM actor will implement ID-based voting constraints. Identity is based on Polygon ID. Polygon ID currently supports the following claims:

1. **proof of personhood**,
2. **country of residence**, and
3. **age**

Other claims would be possible by other implementations of Iden3. We will explore the limits of the Polygon ID, and the need for creating a richer identity that supports additional claims.

A Filecoin / FVM use case would be content moderation, such as granting rights to the moderator based on their identity.

_Figure 2_
<img width="629" alt="LEGACY-FILECOIN-2-FIGURE2" src="https://user-images.githubusercontent.com/41924928/206142242-dec2a39d-8a17-4f67-b73a-6046631d21eb.png">

The deliverables will include testing and documentation.

## Perpetual Storage
Perma-storage has two critical components:

1. **Perpetual storage**, i.e. automatic renewal of storage contract
2. **Pay-once-store-forever pricing** model and the underlying tokenomics

Each of these aspects are managed via the LEGACY Data DAO.

### Deliverable: Contract renewal as FEVM actor
The steps for contract renewal are the following:

1. **Discover expiring contracts**. There could be different approaches for doing so. We are also in discussion with PikNik. They will provide such features in 2023.
2. **Solicit bids for contract renewals**
3. **Select bid based on price, storage provide reputation, and other parameters**
4. **Sign and pay new contracts from the Data DAO treasury**

These steps should be executed automatically.

### Deliverable: Pay-once-store-forever pricing model
We made assumptions for storage costs and growth rates of the amount of stored data. In reality, values will differ from the assumption. The model will need to be adjusted to the actual values. This will be the responsibility of the DataDAO. The DataDAO governing the perpetual storage will adjust policy / pricing parameters.

# Development Roadmap

## Timeline
We propose to deliver these two development packages via 2 milestones, each entailing 6-8 week efforts.

## Milestone 2-1 - Identity
Set-up and test Polygon ID, create a number of identities for testing
Build and run the sample verifier smart contract (EVM)
Port sample verifier smart contract to FEVM on testnet, built, run and test
Modify verifier smart contract to for data DAO use case, built, run and test

People/Roles: 2 developers (~400 dev hours), research & documentation, testing
Duration: 6-8 weeks
Funding required: USD 20,000

## Milestone 2-2 - Perpetual Storage
Implement FEVM actor for perpetual storage as described above
Build, run and test FEVM actor/s on test net 

People/Roles: 2-3 developers (~600 dev hours), research & documentation, testing
Duration: 6-8 weeks
Funding required: USD 30,000

## Total Budget Requested

USD 50,000

## Maintenance and Upgrade Plans

An integral component of LEGACY is our concept of Guardians - the human individuals who will be entrusted with the long-term development, maintenance and preservation of the LEGACY network and its valuable content. Through these proposed milestones, we'll step closer to realizing this Guardians system, through our first foray into Data DAOs, and the core concept of Identity (who are the Guardians now, and how do we reliably pass down administrative authorization in the future?)

In the shorter term, we'll continue to manually administer the network. Treasury tokenomic allocations are intended to ensure technical support/maintenance, ongoing development, moderation, and (bug) bounties.

# Team

## Team Members

Andreas Vogel - Head of Product
Kyle Matheson - Head of Technology
Jono Birkett - Head of Business Development
Sea Ansley - Head of Community / Content

## Team Member LinkedIn Profiles

Andreas -[ https://www.linkedin.com/in/andreasvogel/](https://www.linkedin.com/in/andreasvogel/)
Kyle -[ https://www.linkedin.com/in/kyle-matheson/](https://www.linkedin.com/in/kyle-matheson/)
Jono -[ https://www.linkedin.com/in/jonothanbirkett/](https://www.linkedin.com/in/jonothanbirkett/)
Sea -[ https://www.linkedin.com/in/gashe/](https://www.linkedin.com/in/gashe/)

## Team Website

https://legacy.page

## Relevant Experience

Our experienced core team has enjoyed long-term success across all spectrums of Internet-based businesses, from architecture, research, strategy, domain & hosting infrastructure, development, production, onboarding strategic partners, live events, XR, marketing and bringing applications to market.

Andreas – Headed Deutsche Telekom’s Portfolio of Business Applications, serial entrepreneur, published author
Kyle – CTO of Memtell, 10+ years experience leading tech companies / projects, coded across Arweave, Immutable, some IPFS and more, former Digital Media Manager at Bitcoin Group (2014)
Jono – CEO, co-founder of Memtell, developed Memtell’s web2 app, crafted partnerships for European-wide retail distribution across thousands of physical outlets, headed marketing for Wao.io through Sevenval GmbH
Sea – CEO of Mother.Domains, 20+ years senior web developer & strategist, Certified Holochain Developer (from 2017), “pioneer in Internet radio” (from 2001), producer of hybrid events & music festivals, published author

## Team code repositories

https://github.com/TheLegacyNetwork
https://github.com/kylematheson (Lead developer)
https://github.com/motherdomains

# Additional Information

We were originally invited to apply for Filecoin grants through Blake @ Outlier Ventures. We've since been welcomed into the prestigious FVM Foundry F/1 Early Builders Cohort.

Primary contact email: andreas@legacy.page

We've started reviewing applications for FVM/FEVM-specific developers to join our global team

**Comment by motherdomains** [comment]
We appreciate there is a backlog for submissions. We wondered if there might be any feedback or questions on the submission, before the holidays for us to consider?

**Comment by motherdomains** [comment]
An update from LEGACY... We successfully completed a test exercise related to our first proposed milestone - Perpetual Identity. A new developer on our team ported over Polygon ID code to run a smart contract on the FEVM; you can find the relevant repository here: https://github.com/TheLegacyNetwork/experiments-fvm-polygonid-fevm

**Comment by ErinOCon** [comment]
Hi @motherdomains, thank you for the provided update and for your patience with our review. We will not be moving forward with a grant for this proposal at this time, but are wishing you the best as you continue to build!

If there is a smaller scope of work you would like to be considered, please feel welcome to submit a proposal to our [micorgrants program](https://github.com/filecoin-project/devgrants/blob/master/microgrants/microgrants.md).
