### ISSUE TITLE
Next Step Microgrant: Resume3

### ISSUE THREAD

**Issue by dinesh11515** [filecoin-project/devgrants#1214]
### 1. What is your project, and what problem does it solve? (max 100 words)
Resume3 is a decentralized platform for Resume building powered by IPFS / Filecoin, Polygon.We can see world moving towards decentralization and more companies / orgs are being created to achieve this. Also more than 80% companies are hiring devs by their resumes which are built by using centralized apps and high prices even for creating a resume this can be changed by resume3.
 

### 2. Project links
  
Link to Github repo: https://github.com/dinesh11515/resume3
Link to demo or website, if applicable: https://resume3-631701.spheron.app/
License: APACHE2

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

Resume3 Dapp uploads all the data like work experience,projects and their links etc of a user to IPFS / Filecoin. This data further used for resume creation.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

As of now it was developed by me alone and mostly MVP was ready but the  UI/UX was too bad right now I have to  work further to give better user experience and make sure that resume3 have more resume templates and need to add encryption before uploading data to IPFS to make sure user privacy.This grant helps me to hire a team of frontend devs, designers and marketers to ensure we keep building the community as well while we build and fine tune the product, taking active feedback from the community along the process.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes

  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
https://devpost.com/software/resume3

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
	* Dinesh Aitham
		
        Email : dineshaitham2@gmail.com 
        
        github : https://github.com/dinesh11515)
        
        Role : Full Stack Developer

* How did you learn about our microgrant program?
   * From Superteam bounties
* If your project was created as part of an event or hackathon:
  * What was the name of the event? Chainlink Fall 2022 Hackathon
  * Please link to your hackathon submission [link](https://devpost.com/software/resume3)

**Comment by ErinOCon** [comment]
Hi @dinesh11515, thank you for your proposal. We will not be moving forward with a grant at this time, but wish you the best as you continue building!
