### ISSUE TITLE
Reach + FileCoin Foundation Proposal

### ISSUE THREAD

**Issue by TheChronicMonster** [filecoin-project/devgrants#1217]
# Open Grant Proposal: `FileCoin Developer Program: Education, Onboarding, & Deployment`

**OutReach Developer Programs**

**Proposal Category:** `community` and ‘app-dev’

**Proposer:** `reach-sh`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** 

Yes

# Project Description

In the next 6 months Reach will launch 2 [developer programs](https://docs.google.com/document/d/1G1eB0bc7Q6fIekIQkqY9ipmKn2NXiecNIRdSaRiUrqc/edit#heading=h.aj3aq9itznxd), work to teach developers about FileCoin while building its community in regions like APAC, Latin America, and Africa. Predominantly focused around university students.

Reach makes it possible for web2 CS students, full-stack developers to become web3 developers at a fraction of the time and development cost (over 50% reduction in cost, over 40% reduction in time to build, and over 50% reduction in number of lines of code when compared to traditional blockchain development). This allows for new companies with little to no funding to bootstrap their way to market. 

Together, FileCoin and Reach have the ability to grow the builder community, and bring curriculum to universities. We do so by providing and creating educational resources for developers, through mentorship, curriculum, and opportunities for protocols and builders. Reach Platform is an AVM, EVM compatible programming language, specialized compiler and deployment tool that lowers the barrier of entry into blockchain development. 

Blockchain development is difficult. Launching a company requires costly developers, and time to execute using the current tools that are widely adopted. Our objective is to make it possible for web2 full-stack developers to become web3 developers at a fraction of the time and development cost (over 50% reduction in cost when compared to traditional blockchain development). Reach is the easiest and safest way to build decentralized applications without sacrificing sophistication in what is built. We have a robust tiered curriculum and training offering that takes web2 developers from novice web3 developers to expert Reach accredited blockchain developers in a matter of weeks (please refer to appendix to see Exhibit A where we describe the learning objectives and curriculum plan for the proposed courses. This is not "stick them in a room with CryptoZombies'; it is a fully developed course that we've offered many times with proven success and outcomes). 

## Value

FileCoins release of its virtual machine requires adoption, and incentives to have new builders come to add new DApps and users. Considering we have aligned goals to make blockchain accessible, and multi-chain we can support in providing the frameworks for builders to take part in educational programs, and hacks to deploy functional applications, to bring to mainnet for the ecosystem to use. 

Reach is a 3 in 1 tool that will allow developers to only have to use one platform to do it all, and deploy to any EVM chain. Reach's built in language, formal verification, compiler, and deployment tool makes building more efficient. The whole ecosystem can benefit because we are lowering the barriers to entry, and welcoming new developers to start innovating for the future growth of Ethereum. FileCoin benefits because we are able to teach every developer about the best way to use filecoin in the development of their applications, as well as integration of FileCoin in university curriculum.

The greatest hurdles to success are not having the proper funding to involve our marketing partners. We are dependent on the foundation to support us by providing the necessary resources for Reach to create the prizes and incentives, but also content, promotional materials, and staff to coordinate the efforts. Considering we have followed this framework many times, our executional risks are low. We tend to average in retention for programs at 53% completion rate, but if we do not have enough resources to incentivize builders then the risk of falling below that retention rate can occur. 

## Deliverables

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-4aff7ed3-7fff-3591-c2b5-70af4af00e8d"><h2 dir="ltr" style="line-height:1.38;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Projected Participation&nbsp;</span></h2><div dir="ltr" style="margin-left:0pt;" align="left">

Event | Projected | Completed | Projects (2-5 member teams) | Completion Rate
-- | -- | -- | -- | --
APAC University | 150 | 79 | 26 | current average = 53%
Decentralized Umoja | 300 | 159 | 53 | current average = 53%
outReach Incubator | 10 | 8 | 8 | This is expected to be higher because it will undergo a more rigorous acceptance process
Total Developers Acquired |   | 246 |   |  
Total projects completed |   | 87 |   |  

</div></b>

## Development Roadmap

We have outlined the entire plan of the program [here](https://docs.google.com/document/d/1G1eB0bc7Q6fIekIQkqY9ipmKn2NXiecNIRdSaRiUrqc/edit?usp=sharing)

**Overview:**
### Detailed Overview of Event - APAC UNIVERSITY EVENT:
**March 2023 Onboarding students**
+ **Community Partner:** Women In Blockchain Asia (WIBA), is focused on onboarding under represented communities and is responsible for university, professor and student participation during our developer program.
+ Universities considering participation:
  + 6 universities (subject to change)
    + University Sains Malaysia
    + Asia Pacific University
    + Raffles College
    + University Technology Malaysia
    + University Tunku Abdul Rahman
    + University Malaysia Kelantan
+ Promotion of Filecoin developer bootcamp is launched across all channels of communication

**April 2023**
+ Kick Off for 4-week Education Reach Lang Bootcamp
+ Weekly Office Hours, and Mentor check-ins with teams
+ Demo Day to take place at the end of the program

**May 2023**
+ Kick Off 4-week Incentive program for completed real-world use case DApps
  + By the end of the bootcamp students will understand the foundation of Blockchain, building Reach DApps and the major features allowing them to deploy basic DApps to the FileCoin TestNet
  + By the end of the Incentive Program students will have developed a DApp inspired by regenerative solutions in their communities
**Theme:** Regenerative Communities
**Key Dates:**
+ Kick Off: March 13, 2023
+ Bootcamp begins:
+ First small incentive payout for creating an FileCoin wallet
+ Second incentive for completing the bootcamp
**Final Pay out:** April 10, 2023 for completed custom independent projects

### Detailed Overview of Event - Decentralized Umoja:
**June 2023**
**Community Partner:** Africa Blockchain Alliance (ABA
+ Anyone in any African country is encouraged to kick start blockchain education, and create an MVP to then become incubated by our OutReach team.
+ Developer focused
**July 2023**
**Primary Objective:**  4-week refresher bootcamp.
+ MVP built and top 5 selected to join the incubator program.

**August 2023**
+ 4-week Incentive program for completed real-world use case DApps
  + By the end of the bootcamp students will understand the foundation of Blockchain, building Reach DApps and the major features allowing them to deploy basic DApps to the FileCoin TestNet
  + 4+ Weeks of mentorship focused growth, and business development supported by professionals in our network, and internal team experts.

## Total Budget Requested

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-0f456a05-7fff-e186-4331-79e3fcaed3c8"><p dir="ltr" style="line-height:1.38;text-align: center;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Cost of Operations</span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Included in this proposal is the cost to operate the programs, vision in virtual hackathon events, retention challenges, and strategy for acquiring community partners to bring new developers. Below is a breakdown of those costs based on past programs we have completed:</span></p><br /><div dir="ltr" style="margin-left:0pt;" align="left">

Name |   | Approx. Cost
-- | -- | --
Incubator Incentives | Awarded to the top 5 projects that join the incubator. | $10,000
Completion Incentive | Awarded for project completion, this is to support the continued development of their projects(assuming 50 completed projects). | $25,000
Mentor’s Commission | Awarded to mentors for each team they help cross the finish line. | $10,000
Curriculum Prep | Developing curriculum for University, and LMS | $17,600
Code Review | Reviewing code for quality and completeness to be eligible for Prizes
Increased Discord Support | Troubleshooting with new users
Admin Time | Managing communications, organizing program
Prep Payouts | Payout fairly, completely and efficiently
Technical Support | Index Management, to provide ecosystem partners with the top talent to hire for their companies. | $2,400
Marketing Events, Content Development & Admin Fees | Video editing, graphic design, and the facilitation of payouts; overall event coordination. Supported by WIBA, and ABA. | $10,000
Total | Cost per Bootcamp event + Incubator | $75,000
Grand Total | Cost for 2 programs(APAC unis & Decentralized Umoja incubator) | $150,000

</div><br /></b>

# Team

## Team Members

**JP Miller**
+ Director of Developer Experience
+ Coordination of DevX team
+ Live lecture/office hours support
+ Curriculum development/QA

**Nick Stanford**
+ Developer Experience Lead
+ Live lecture sessions, workshops and office hours
+ Troubleshooting
+ Guiding Developers through the technicals of Reach

**Michelle Hetlage**
+ Monitoring and encouraging engagement among students.
+ Managing retention and the success of students' completion of programs.
+ Coordinating community workshops to help support our students with Reach language and career services. 
+ Managing our Career Services and job placement program.

## Team Member LinkedIn Profiles

JP Miller - https://www.linkedin.com/in/jpmillerii

Nick Stanford - https://www.linkedin.com/in/reachnick/

Michelle Hetlage - https://www.linkedin.com/in/michellehetlage/

## Team Website

https://reach.sh

## Relevant Experience

As described above, our team has extensive experience creating, operating, and maintaining bootcamps that teach blockchain development that result in unparalleled graduation rates and result in secured employment opportunities. 

## Team code repositories

JP Miller - https://github.com/thechronicmonster
Nick Stanford - https://github.com/nstanford5

# Additional Information

Please contact estefania@reach.sh to discuss the grant agreement and the next steps for our collaboration.

**Comment by TheChronicMonster** [comment]
Hi @realChainLife, 
Following up regarding our Reach proposal on Filecoin, post holiday season. 
Is it possible to secure a review and/or schedule a call? 
Thank you!

**Comment by realChainLife** [comment]
Hi @TheChronicMonster thanks for your patience with our feedback. We will update you here when we have a status update.

**Comment by ErinOCon** [comment]
Hi @TheChronicMonster, thank you for your proposal and for all of your patience during our review process. Unfortunately, we will not be moving forward with a grant at this time. We are wishing you all the best as you continue to build!
