### ISSUE TITLE
CrewS FVM

### ISSUE THREAD

**Issue by AAYUSH-GUPTA-coder** [filecoin-project/devgrants#1218]
### 1. What is your project, and what problem does it solve? (max 100 words)
FVM enables a new kind of data-centric DAO that has heretofore been impossible. DataDAOs are DAOs whose mission revolves around preserving, curating, augmentation, and promoting datasets considered valuable by their stakeholders.

Creating DataDaos should be easily available for everyone, and thus no code tools are required to make the process easier. Currently, we have a few features which are kinda basic for Data Daos, like finding the best deals on the network and then executing the proposals on top of the chain.

The entire voting takes place on the chain and the execution is handled by the actor. This way having governance on the chain whilst able to have governance on storage is something that has never been done before and having an easy-to-use interface to create and manage them makes it easier for the users to have an awesome experience.

We also publish a tutorial around it : [How to build your first DataDAO Factory on FVM](https://aayushguptaji.hashnode.dev/how-to-build-your-first-datadao-factory-on-fvm)

### 2. Project links
  
Link to GitHub repo: https://github.com/Open-Sorcerer/CrewS
Link to demo or website, if applicable: https://bafybeidaa7n4ujlkd6mialpyc4arhortlcg6f2x5o34hom5m5wa7nplnda.ipfs.gateway.valist.io/
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
We have developed smart contracts and deployed them on **FEVM**. We have created a MockMarket() on Filecoin which gets us client deals for storage providers. The voting happens on the chain in the contract and the data DAO gets created on Filecoin. 
The result of the voting gets executed and the best storage provider, according to the Market at the current time, gets selected and the deal gets published on the chain.

We deployed our web app using **IPFS**  (Valist). 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We will require indexers on the FEVM which are not there yet. We have looked into how to setup Graph Protocol for a new chain, here are the [steps](https://github.com/graphprotocol/graph-node). We would look to setup servers that can help in hosting these indexers and later make it community-driven so that its not dependant on us. We would require funds to setup early-stage servers for hosting different tools. 
Next, we want to have Superfluid tokens on the FEVM which would help to streamline funds in regular intervals. This feature will help in asset management as a DAO. These contracts also require always going on readers which require servers to keep them up. So the majority of funds will be used to putting the infrastructure for the project.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  **YES**

### 6. Does your proposal comply with our Community Code of Conduct?

**YES**

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

  **Yes**, We submitted the project in **ETHIndia** (Worlds Biggest ETH Hackathon)

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  * Name: [Suvraneel Bhuin](https://suvraneel.github.io/)
Email: [bsuvraneel@gmail.com](mailto:bsuvraneel@gmail.com)
GitHub: @Suvraneel
Role: Full Stack Developer

  * Name: Harsh Ghodkar
Email: [harshghodkar@gmail.com](mailto:harshghodkar@gmail.com)
GitHub: @Saviour1001
Role: Smart Contract Dev

  * Name: Aayush Gupta
Email: [guptaaayush432@gmail.com](mailto:guptaaayush432@gmail.com)
GitHub: @AAYUSH-GUPTA-coder
Role: Smart Contract Dev

* How did you learn about our microgrant program?
  * Through **FVM** team in ETHIndia Hackathon

* If your project was created as part of an event or hackathon:
* What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * **Yes** in ETHIndia 2022
  * Please link to your hackathon submission
[https://devfolio.co/projects/crews-2c1c](https://devfolio.co/projects/crews-2c1c)

**Comment by Saviour1001** [comment]
@ErinOCon any updates on this ?

**Comment by AAYUSH-GUPTA-coder** [comment]
@ErinOCon @eshon 

GM 👋 Any update on our grant application? It will be super helpful if we get any status update.

**Comment by eshon** [comment]
Hi, this proposal was not accepted in our 1st tranche of FVM microgrants. A 2nd tranche of microgrants will likely be opened up later in February though. 

Note that Zondax has an API for indexed chain data here: https://beryx.zondax.ch.
Your team is also welcome to add _new features_ to this project during the FVM Space Warp hackathon (please be clear about what's new vs what's already been submitted before in your submission).
More info is here:  https://spacewarp.fvm.dev/
