### ISSUE TITLE
Next Step Microgrant: dLink

### ISSUE THREAD

**Issue by surendravarmadendukuri** [filecoin-project/devgrants#1219]
### 1. What is your project, and what problem does it solve? (max 100 words)
A platform for users to create dynamic NFTs on Polygon in a simple manner within a few clicks, similar to MintNft by Polygon which offers the same services for traditional NFTs.

### 2. Project links
<b>Github</b>: https://github.com/surendravarmadendukuri/DLink
<b>Demo</b>: https://youtu.be/fizWFQYvU8w
<b>Link</b>: https://d-link-sooty.vercel.app
<b>License</b>: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
The Images uploaded by the user that he wants to feature in his dNFT one by one, are uploaded to IPFS simultaneously.
 
###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
No

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
- <b>Better UI/UX</b>: We will hire a designer and work closely with him to improve the user experience.
- <b>Optimise the application</b>: Redesign the architecture in a scalable way and write tests for smart contract audits.
- <b>Create an API for third-party use of the dynamic NFT</b>: Reach out to the upcoming NFT collections interested in dynamic NFTs, who will be the potential customers.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
<b>Hackathon [ Filecoin - Runners up ]</b>: https://devpost.com/software/dlink

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  Surendra Varma Dendukuri
  Email - [surendravarmadendukuri@gmail.com](mailto:surendravarmadendukuri@gmail.com)
  Github - surendravarmadendukuri
  Role - Frontend Developer

  Pradeep
  Email - [pradeepvarma2292@gmail.com](mailto:pradeepvarma2292@gmail.com)
  Github - pradeepvarma22
  Role - Smart Contract Developer
  
  Shashank
  Email - [17211a05a5@bvrit.ac.in](mailto:17211a05a5@bvrit.ac.in)
  Github - shashanka2a
  Role - Full Stack Developer

* How did you learn about our microgrant program?
Friend
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  Chainlink Fall 2022 Hackathon
  * Please link to your hackathon submission
  https://devpost.com/software/dlink

**Comment by ErinOCon** [comment]
Hi @surendravarmadendukuri, this microgrant has been approved! We will send an email to confirm payment details. Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). 

Please let us know if you have any questions!
