### ISSUE TITLE
Next Step Microgrant: Kangaroo - Winner of ETHIndia FVM Track Grand Prize

### ISSUE THREAD

**Issue by kangaroo-data-dao** [filecoin-project/devgrants#1221]
### 1. What is your project, and what problem does it solve? (max 100 words)

Kangaroo (a play on wallaby i.e. baby kangaroo) is a Data DAO Starter kit, which lets anyone create a DAO, distribute ERC20 tokens to the DAO members and allow them to vote on the preservation of data / file sets. 

The starter kit allows the DAO members to do the following:

1. Stake tokens to vote for a particular data set to be preserved
2. Submit a data set for members to vote for
3. Pay storage providers using governance tokens
4. Vote on storage providers’s deal upkeep and reward them accordingly

### 2. Project links

Link to Github repo: [https://github.com/kangaroo-data-dao/kangaroo-data-dao](https://github.com/kangaroo-data-dao/kangaroo-data-dao)
Link to demo or website, if applicable: [https://youtu.be/dn7neEnpQsM](https://youtu.be/dn7neEnpQsM)
License: MIT

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

We are built on top of FVM to enable easy data-dao creation

### b) Is this project contributing to the upcoming FVM launch? (Yes or No)

Yes

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The goal of Kangaroo is to be the defacto factory to create DataDAOs on the Filecoin Blockchain. We are keen to build this project further, such that different DAOs can leverage our the smart-contracts to support the governance of persistent decentralized file storage. 

Furthermore, we want to add different builtin DAO Tools to our codebase, such as voting mechanisms, token distribution, member onboarding and deboarding, such that it’s easy for Teams to create a DataDAO.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes I will

### 6. Does your proposal comply with our Community Code of Conduct?

Yes it does

### 7. Links and submissions

- If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
    
    We were the winners of the #BulitOnFVM Grand Prize - [https://twitter.com/Filecoin/status/1599385715401527299](https://twitter.com/Filecoin/status/1599385715401527299) at ETH India 2022
    [https://devfolio.co/projects/fevm-data-dao-starter-kit-kangaroo-2f3d](https://devfolio.co/projects/fevm-data-dao-starter-kit-kangaroo-2f3d)
    

### Additional questions:

- For each team member(s), please list name, email, Github account, and role in the project.
    
    Name - Prasad
    
    Email - [prasadax.g@gmail.com](mailto:prasadax.g@gmail.com)
    
    Github - [https://github.com/kangaroo-data-dao/kangaroo-data-dao](https://github.com/kangaroo-data-dao/kangaroo-data-dao)
    
- If your project was created as part of an event or hackathon:
    - What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
    - Please link to your hackathon submission
    
    [https://devfolio.co/projects/fevm-data-dao-starter-kit-kangaroo-2f3d](https://devfolio.co/projects/fevm-data-dao-starter-kit-kangaroo-2f3d)

**Comment by ErinOCon** [comment]
Hi @kangaroo-data-dao, this microgrant has been approved! We will send an email to confirm payment details.

**Comment by kangaroo-data-dao** [comment]
@eshon Please find the deployed addresses on Wallaby
1. Deployed Instance of Kangaroo Data DAO - 0x7f121129c2F10fF01616a275a3cbd0d343B1E201
2. Deployed Instance of KDCoin - 0xDA19cAF1B4650CaDC36D2802D0b1C88ACd9E4322
3. Deployed Instance of KangarooFactory - 0x3d57C109a697030e49Dab65762d01751d27dfeB0

Here is a demo of all of them in action - https://youtu.be/dn7neEnpQsM

This is done as of 5th Jan 2022, as I understand that Wallaby testnet will be restarted in the near future. I shall redeploy these contracts if you need me to in the future. Thanks

**Comment by kangaroo-data-dao** [comment]
Just to update. Me and the team are prototyping a new UI on a different repository. 
Will leave the link for the same here - https://github.com/kangaroo-data-dao/kangaroo-ui-v2
We are calling it the UI-v2. Thanks and cheers.

**Comment by ErinOCon** [comment]
Hi @kangaroo-data-dao, thank you for the update! We will be in touch with any questions.

**Comment by eshon** [comment]
Hi @kangaroo-data-dao

**Comment by eshon** [comment]
Hi @kangaroo-data-dao! Other than deploying your existing contracts to an FVM testnet, what other improvements have you made to this project for this microgrant? 

Here are some things we'd like to see in FVM Microgrant projects:

- A fully working user-facing demo with nice UX that anyone case easily use.
- Is currently deployed on the Hyperspace testnet, so that we can see all the functionality working on Hyperspace, and will be deployed to Filecoin mainnet after FVM mainnet launch on March 14th, 2023.
- Interesting use of the EVM on Filecoin, especially with respect to what's unique to Filecoin.

**Comment by kangaroo-data-dao** [comment]
Hi @eshon 
We have been updating the project from January. We started working on v2 of the UI and the smart contracts as we found a lot of optimizations for this project, which demanded a rewrite. 
We will make them open source today and upload a demo video as requested. We are very happy to launch this app on the FVM Mainnet as well. 
Will be updating the thread shortly.

Thank you for the support!

**Comment by kangaroo-data-dao** [comment]
Hi @eshon 

We are continually working on the project. We are happy to share some updates with you:

1. A fully working user-interface easy for any user to create a new DataDAO available here (V2) - https://kangroo-data-dao.vercel.app
2. We are live on the Hyperspace Testnet and we are happy to be a part of the main-net launch
3. We extensively use the MarketAPI from Zondax to make sure the deal is valid so that the DataDAO can automatically pay out to the designated Storage Provider 

I will shortly post a demo video for the same as well which will help you navigate the application - we are constantly trying to improve the UX as well, so any feedback is greatly appreciated.

We have planned out the next phase of improvements to make this a more marketable product for all the Daos which can benefit from a DataDAO counter-part.

**Comment by trruckerfling** [comment]
@kangaroo-data-dao hey hey we have an early builder program to support teams going to mainnet deployment, from march 14th until april 14th. Would kangaroo like to join? can we connect on slack if so? the channel is #fvm-mainnet-cohort

**Comment by kangaroo-data-dao** [comment]
@trruckerfling Thank you so much. We are excited to be a part of the this. I'm messaging you right away.

@eshon We just ported our code form Bitbucket to Github -> https://github.com/kangaroo-data-dao/contracts

Thanks

**Comment by eshon** [comment]
Let us know if you have any updates @kangaroo-data-dao

**Comment by kangaroo-data-dao** [comment]
Hey @eshon 

I apologise for the delay. The team is working on a relayer system which can help FEVM projects provide a gasless experience for users by sponsoring gas. But beyond that, we have fixed the issue which you were facing, and also have updated all our contracts to the Calibration testnet. You can check the application here - [https://kangroo-data-dao.vercel.app](https://kangroo-data-dao.vercel.app/)

Coming to all the changes we have made to the project, 
1. We have update the User Interface - 
How it used to look like
![UI v1](https://github.com/filecoin-project/devgrants/assets/119771802/b69de522-caeb-43b4-99bc-49ecf7c30abb)

How it looks like now
<img width="1440" alt="image" src="https://github.com/filecoin-project/devgrants/assets/119771802/ff6e87f5-08a4-4ca0-8c7e-675c104975ae">

<img width="720" alt="" src="https://github.com/filecoin-project/devgrants/assets/119771802/7c29f6e3-298b-4c17-9afc-e8d73643ced2">

2. We have integrated RainbowKit to work with both Hyperspace and Calibration testnet. The one in production right now, only uses Calibration Testnet however. Once we have received good feedback from the people we have sent this application to, we will enable both hyperspace and calibration testnet.

3. As a part of the microgrant, we have better implemented Zondax's APIs which integrates a lot of the core functionality of Filecion into our project. We have made submitting miner proof mandatory for the rewards to be disbursed using our contract logic. This checks for the deal commitment and validates it using Zondax's APIs. 
Beyond this, we also implemented the EIP-1167 proxy contract standard, as the defacto way to launch self-verifying Kangaroo Contracts using a singleton KangarooFactory contract. 

Finally, we plan to work on a few more features such as Quadratic Voting, DB Connectivity for better UX, an intricate DAO Profile Page which advertises the DAO to the public and Public Deal Discoverability Features (Enabling a better participation of miners & daos) before we get audits done for the mainnet. We also are pitching Kangaroo to various daos to get feedback to make sure we are thinking in the right direction.

This final payment of the grant would achieve the same and would fastrack the progress. 
Thank you

**Comment by kangaroo-data-dao** [comment]
Also while testing, please make sure you have some extra tFIL in the testing wallet. 
We are still working on a relayer, which will help make all this gasless - This is also a part of the roadmap

**Comment by kangaroo-data-dao** [comment]
HI @eshon
We are continually working on this project and we are happy to receive any updates from you.

**Comment by kangaroo-data-dao** [comment]
HI @eshon - Happy to receive any updates on this project - Happy to provide more updates shortly

**Comment by kangaroo-data-dao** [comment]
Hi @eshon - I hope you are doing good. I can please receive an update?

**Comment by kangaroo-data-dao** [comment]
Hi @eshon We are looking forward to supporting this project and promoting it, but the promised grant support would be essential. Please get back to us. Thanks

**Comment by kangaroo-data-dao** [comment]
Hi @ErinOCon @eshon checking in for any updates you might have.

**Comment by eshon** [comment]
@kangaroo-data-dao - I was able to successfully create a DAO but when trying to create a File Proposal I received the following error:

<img width="1413" alt="Screen Shot 2023-09-26 at 4 24 17 PM" src="https://github.com/filecoin-project/devgrants/assets/1017762/7b5896a1-1fc3-4318-8620-43e05af407a1">

What is a valid CID?

Can you please create a quick demo video of the new functionality that has been implemented for this FVM Microgrant and add it to the README of your Github repo at https://github.com/kangaroo-data-dao/kangaroo-data-dao? Then let me know here when it's been posted and I'll review it.

**Comment by kangaroo-data-dao** [comment]
Hi @eshon and @ErinOCon,

Here is the link to the demo video, which we have also added to our README: https://www.youtube.com/watch?v=DKi2L540QRQ.

You may also want to consider creating a proposal file now. Everything is working flawlessly.

**Comment by kangaroo-data-dao** [comment]
> @kangaroo-data-dao - I was able to successfully create a DAO but when trying to create a File Proposal I received the following error:
> 
> <img alt="Screen Shot 2023-09-26 at 4 24 17 PM" width="1413" src="https://user-images.githubusercontent.com/1017762/270689800-7b5896a1-1fc3-4318-8620-43e05af407a1.png">
> What is a valid CID?
> 
> Can you please create a quick demo video of the new functionality that has been implemented for this FVM Microgrant and add it to the README of your Github repo at https://github.com/kangaroo-data-dao/kangaroo-data-dao? Then let me know here when it's been posted and I'll review it.

Hi @eshon and @ErinOCon,

Here is the link to the demo video, which we have also added to our README: https://www.youtube.com/watch?v=DKi2L540QRQ.

You may also try creating a file proposal now. Everything is working flawlessly.

Regards,
Prasad
