### ISSUE TITLE
Certy Network 

### ISSUE THREAD

**Issue by AaronCerty** [filecoin-project/devgrants#1227]
### 1. What is your project, and what problem does it solve? (max 100 words)
Certy Network is a Learn-to-Earn & Professional Networking Services Platform. We provide an online platform to host Learn-to-Earn campaigns to educate and attract users. After completing the courses, users can earn NFTs representing their completion, and they can use these NFTs to apply for jobs or show it on their social profile using Certy Platform. Previously, we received over $100k in Grants from NEAR Foundation, Filecoin Foundation, and The Graph Foundation to develop the infrastructure for Learn-to-Earn. Now, we reapply to ask for funding to create a Learn-to-Earn course about Filecoin and IPFS to educate and spread Filecoin's vision and use case to smart Web3 users. 
  
Link to Github repo: https://github.com/CertyNetwork
Link to demo or website, if applicable: https://certy.network/
License: GPL
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
The metadata and some content of Learn-to-Earn course as well as the NFTs that users received after learning will be stored on Filecoin, which will make sure it is fully decentralized and always accessible.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
No
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
We will use this grants to develop and create the content for the Learn-to-Earn course, a small amount of the grants (10-20%) will be deposit into the reward pool of the Learn-to-Earn infrastructure to incentivize Web3 users to deep dive about Filecoin and IPFS. Currently, we're running our testnet (over 6000 unique users). We will launch mainnet in next 1-2 months, and Filecoin course will be one of the first course on mainnet. 

The tentative curriculum (videos, animation, graphics, text): 
1. Introduction to Filecoin and IPFS 
2. How Filecoin and IPFS works?
3. Impact of Filecoin and IPFS 
4. How to use Filecoin and IPFS?
5. Final Exam (Quizzes and Short Answer questions)

We already have a very big community and reputation in NEAR Ecosystem. Therefore, our purpose is to spread knowledge about Filecoin and IPFS to NEAR users. You can check our social traction here: 

- Twitter Followers (over 8000): https://twitter.com/CertyHQ
- Testnet users (over 6000): https://thegraph.com/hosted-service/subgraph/edricngo/certy-network-testnet
- Telegram members (~5000): https://t.me/certynetwork

Our goal for this course is to attract at least 2000 users to learn about Filecoin & IPFS. This is a basic pilot Learn-to-Earn course, if we get strong traction after the course, we will reapply to open grant from Filecoin to create more advanced courses in the future. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
No
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

- **Contact email**: ceo@certy.network 

- Aaron - CEO: Former Developer Augmentation at Covalent (https://www.covalenthq.com/)
- Edric - CTO: Former Blockchain Engineer at FTX JP. Github: https://github.com/EdricNgo
- Minh - CMO: Former Manager at Foxconn
- Daniel - PM: Former Developer at Tokenize Xchange 
- Above are the founder, we have more members who are designers, developers, content creators, and instructors. 

* If your project was created as part of an event or hackathon:
 Grants from NEAR Foundation, Filecoin Foundation, The Graph Foundation 
  * Please link to your hackathon submission
 You can check the previous open grant submission here: https://github.com/filecoin-project/devgrants/issues/608 
 The Graph Foundation Grants Announcement: https://thegraph.com/blog/wave-six-grants/
 NEAR Foundation Grants: It is a contract with sensitive information (can only show in DMs) 
 
 Sample images of the Learn-to-Earn Platform and NFTs. 
![Learn](https://user-images.githubusercontent.com/69748760/206638349-ba6d3474-8dd4-4659-8508-dc47d4674011.png)
![Learn 2](https://user-images.githubusercontent.com/69748760/206638331-f19e8301-37fe-45cf-90db-0d91e9c55592.png)
![Learn-1](https://user-images.githubusercontent.com/69748760/206638347-dbf7514f-1df6-4073-9210-93f46ce61f51.png)
![Pool Details](https://user-images.githubusercontent.com/69748760/206638353-bc2774e6-6ede-44d5-a30e-8f33e87ad796.png)
![photo_2022-12-09_13-27-11](https://user-images.githubusercontent.com/69748760/206638875-273acc7f-e4db-49f0-9c90-2c5cc03c25c0.jpg)

**Comment by ErinOCon** [comment]
Hi @AaronCerty, thank you for your proposal! We will not be moving forward with a microgrant at this time, but you may have an interest in checking out the [accelerator program](https://ecosystem-wg.notion.site/Protocol-Labs-Accelerator-Program-d45d8792a7d544eca9beb7d3e3d3b05d) for additional support opportunities. 

Wishing you the best as you continue to build!
