### ISSUE TITLE
Next Step Microgrant: Sadaiv CI - Winner of ETH India

### ISSUE THREAD

**Issue by sheetalojha** [filecoin-project/devgrants#1229]
### 1. What is your project, and what problem does it solve? (max 100 words)
Sadaiv CI is a continuous integration pipeline that backs up GitHub contributions on the Filecoin Network without one worrying about it. Today, most developer communities and organizations (including DAOs) use GitHub to host their projects. GitHub is a centralised organization providing limited support for web3 native values; hence, the data could be lost. 

And the other solutions that tend to create decentralised GitHub are not user friendly and need a lot of efforts from users. So we are creating an easy to integrate CI/CD pipeline that automatically backups GitHub commits on the Filecoin network.

### 2. Project links
  
Link to Github repo: https://github.com/sadaiv-ci/sadaiv-ci
Link to demo or website, if applicable:
Demo Video (4min) : https://www.youtube.com/watch?v=cx3ZCdmf5Xs
Website: https://sadaiv-web-app.vercel.app

License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
Sadaiv CI is powered by Web3.storage to provide its core functionality i.e. to backup GitHub repositories and have a decentralised source of truth rather than giving custody to GitHub. The project at its core working on the mission to onboard humanity's data on to Filecoin network that will give them easily accessible yet verifiable source of truth. 

The below diagram explains the full flow:

![Diagram](https://user-images.githubusercontent.com/36601970/206647376-13283f4f-51ec-4f51-bb62-e41577e08049.jpg)

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)

No plans for now, but we can create solutions to optimise storing data on Filecoin and can create Data DAO in future. 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The project was built at ETH India. We got great initial validation and we want to build the first minimum version and launch it in market to test the product. This will require us to do improvements and build a set of tools, the following list represents the milestones: 

- Hiring DevOps developer to improve CI/CD pipeline and make process more seamless 
- 1 Web Dev and 1 Designer to write beautiful frontend 
- Working on adding the following features:
  - Backing up commits and branches in structured format on Filecoin to optimise storage usage
  - Adding web3 social auth to allow developers login using GitHub to integrate Sadaiv CI automatically rather than manual process
  - Implementing smart contract wallet abstraction to hold the user's identity for contributions 
  - Allowing users to claim their on-chain contributions identity by social auth and verification
  - Building Dashboard for developers to see their ranking and contribution graph
  - Deriving formulas for on-chain reputation for developers 
- Launching the project from testnet to mainnet
 - The project is on testnet right now, we will lift off the project to mainnet that includes paying for the gas, spreading awareness to get some traction and doing a couple of airdrops
 - We will be paying for the on-chain transactions for now to on-board maximum number of users without web3 complexities

Additional costs that will be covered from grant money:
- Buying domain for the project
- Vercel premium to host the website
- Booking ENS domains and other brand handles

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, we will provide detailed report upon completion of 3 months.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
We begin our project at ETH India this year. We were lucky to be selected as one of the winner out of 437 projects.

ETH India website: https://ethindia.co
Here's the link to hackathon submission: https://devfolio.co/projects/sadaiv-ci-4cf9
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
   * Sheetal Ojha (Frontend & Data Science) 
       * GitHub @sheetalojha
       * Email: sheetalojhabkn@gmail.com
   * Tushar Ojha (Core, Smart Contract Dev)
       * GitHub @tusharojha 
       * Email: tusharojha2001@gmail.com
* How did you learn about our microgrant program?
   * From a Juan Benet at his ETH India talk.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
      * ETH India
  * Please link to your hackathon submission
      * https://devfolio.co/projects/sadaiv-ci-4cf9

**Comment by tusharojha** [comment]
@ErinOCon please review.

**Comment by ErinOCon** [comment]
Hi @sheetalojha, thank you for your patience with our review! This microgrant has been approved. We will send an email to confirm payment details.
