### ISSUE TITLE
Next Step Microgrant: dStor - Decentralized Cloud Storage

### ISSUE THREAD

**Issue by KeatonKirk** [filecoin-project/devgrants#1233]
### 1. What is your project, and what problem does it solve? (max 100 words)
dStor is a decentralized cloud storage platform platform leveraging decentralized, client side encryption and decentralized identity for access control. Decentralized cloud storage is a popular topic, though many storage solutions store PII or access credentials on a centralized server. dStor leverages Ceramic network for user centric data storage and Lit Protocol + Ethereum NFTs for decentralized access control. dStor does not require any identifiable information to sign up and stores encrypted files on the Filecoin network using Chainsafe APIs.

### 2. Project links
  
Link to Github repo: https://github.com/KeatonKirk/d-stor
Link to demo or website, if applicable: https://d-stor.herokuapp.com/
License: Apache 2.0

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
 Filecoin provides the base storage layer for dStor and is a critical component of the architecture. The full dStor stack is :
- decentralized, user-centric data with Ceramic Network
- decentralized encryption and access control with Lit Protocol
- IPFS/filecoin storage through Chainsafe APIs.
###    b) Is this project contributing to the upcoming FVM launch? (Yes or No) 
Not at the moment, though this proposal includes a report on the possibility of building on the FVM! (See deliverables below)
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

This microgrant will fund the following technical, community, and research work: 

Technical/ UX Upgrades:
- Support for multiple folders
- Renaming Files
- Deleting Files
- File search
- Professionally designed custom graphics and color pallet

Community:
- Medium blog post introducing dStor and explaining the importance of treating data storage as a public good
- Public Discord server for user support and full time support staffing

Research:
- Report on feasibility of hosting dStor front end on decentralized platform such as Fleek, as well as report on FVM and the state of decentralized compute platforms capable of hosting a Node.js server.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
 Yes!
  
### 6. Does your proposal comply with our Community Code of Conduct?
 Yes!

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
- Keaton Kirkpatrick:
Lead Full Stack Developer
keatondkirkpatrick@gmail.com
https://github.com/KeatonKirk/

* How did you learn about our microgrant program?
Prior grant recipient!
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
  N/A

**Comment by KeatonKirk** [comment]
Hi @ErinOCon , I hope your holiday season is going well! Just wanted to touch base and see if there's any additional info I can provide regarding this proposal. I'd be happy to record a video walkthrough if that would make things easier for you! In the meantime, the application is live here if you'd like to try it out: https://d-stor.herokuapp.com/

Thanks for all your work on the grants program!

**Comment by KeatonKirk** [comment]
Hi @ErinOCon, I hope you're doin well! Just wanted to follow up on this request and see if there's any questions I can answer or additional material you need for this proposal.

I'm sure things are super busy coming back from the holidays, please don't hesitate to reach out if there's anything else you need from my end!

**Comment by ErinOCon** [comment]
Hi @KeatonKirk, thank you for your patience with our review. Glad to see this project making progress! The grant has been approved. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Look out for an email to confirm payment information.

**Comment by KeatonKirk** [comment]
Hi @ErinOCon !

I submitted the form for this in November, I believe on 11/26. That being said I think my other email address was used, keatondkirkpatrick@gmail.com. I hope this helps, let me know if you need anything else from me!
