### ISSUE TITLE
NFTs as clickable elements within a digital comic book

### ISSUE THREAD

**Issue by alecmaslov** [filecoin-project/devgrants#1234]
# Open Grant Proposal: `Stellar Dream Embedded NFT`

**Name of Project:** Stellar Dream

**Proposal Category:** Choose one of `core-dev`, `app-dev`, `devtools-libraries`, `integration-adoption` , `technical-design`, `docs` , `community` , `metaverse` , `research` , `green`  Learn what these categories are here: https://github.com/filecoin-project/devgrants/tree/master/open-grants#readme

app-dev

**Proposer:** `alecmaslov`

**(Optional) Technical Sponsor:** `Piyush Maheshwari`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Please respond with either "Yes" or "No" Yes

# Project Description

We have launched a prototype on Stellar-Dream.com showcasing how NFTs can be "embedded" as characters within a digital comic book. The purpose of this prototype is to provide additional utility for NFT holders. With our technology, NFTs get drawn into stories and linked to the underlying smart contract as well as a marketplace where that NFT can be bid on and traded. Currently, we have our project files stored on Amazon AWS as publicly accessible files. We would like for all of our files to be stored on the most optimal Filecoin system and to continue building all future work on top of Filecoin.

The bigger picture behind this prototype is to be able to offer a B2B service or platform for other IP holders to be able to create digital comics with embedded content (it's not just limited to NFTs!). As part of this, we want to use FIlecoin as the underlying technology. In the future, we aim to build a platform where our B2B clients can upload their artwork and our tech can automatically create SVG paths and clickable elements. We believe this technology will go beyond comic books and can become the new standard for digital entertainment.

## Value

We believe that fans will be able to own and trade characters from their favorite stories. We believe that this user experience will be as seamless as the current market for physical collectibles. Imagine a world where you can customize your own character in a comic book or cartoon, personalize that character's appearance, and then see your own personalized character appear on the pages or screen of your favorite story - knowing that YOU own that character and that YOU made that character appear that way. That's what we aim to build and we aim to build it on Filecoin. 

If we get it right, fans will have the option to engage much deeper in their favorite stories, and Filecoin will be under the hood. If we don't get it right, it will take longer to bring this idea to market. Since our prototype is already live, there aren't many risks in switching to Filecoin. Once our technology is live, any developer will be able to use our code to embed NFTs directly into their own digital comic book using Filecoin.

## Development Roadmap

Milestone 1: Switch from AWS to Filecoin for the prototype.
- currently, the images for our prototype are hosted on AWS. Switching the hosting to Filecoin should not be difficult or time intensive. 
- We estimate up to 1 week before going live with an updated prototype built on Filecoin.
- Total contributors: Alec Maslov and Igor Kuznetsov (GitHub username: iforaa)
- Budget: $2,000

Milestone 2: Launch our 1st volume
- 4 additional NFTs embedded in a scrollable manga reader
- build and test scrolling functionality with SVG paths
- test and debug
- estimated deadline: February 2023
- Contributors: Alec Maslov, Igor Kuznetsov, and Manabu Okamato (Art Director)
- Total funding: $8,000

Milestone 3: Launch a pilot project for a B2B customer
- create an interactive comic book for a third party using our existing prototype technology and built on Filecoin
- use this experience to create a framework for building a platform
- estimated deadline: May 2023
- Contributors: Alec Maslov and Igor Kuznetsov
- Budget: $0 (we are aiming to get a paid pilot)

Milestone 4: launch a beta of the interactive comic platform
- build technology that can automatically create SVG paths for interactive elements on a page
- build a backend and admin section for B2B users to login, upload art, add links, and manage elements
- build a way to easily share/distribute interactive comics once they have been created
- integrate with Filecoin
- test and debug
- estimated deadline: August 2023
- Contributors: Alec Maslov and Igor Kuznetsov
- Budget: $25,000

## Total Budget Requested

Budget for Milestones 1 & 2: $10,000

Use of funds:
- Filecoin system costs
- developer salary
- hiring artists

Budget for Milestone 4: $25,000
- Filecoin costs
- Developer salaries
- Testing/QA

## Maintenance and Upgrade Plans

Our team has a content roadmap for Stellar Dream that includes releasing at least 3-4 new comic book volumes per year. We will continue to use this technology to release new NFTs and embed them into our comics. During that time, we will be actively developing the platform and code for improved performance and functionality. 

# Team

## Team Members

 Alec Maslov
 Igor Kuznetsov
 Manabu Okamoto
 https://linkedin.com/in/alec-maslov/
 https://www.linkedin.com/in/igor-kuznetsov-b8028618/
 No LinkedIn
 https://stellar-dream.com

## Team code repositories

https://github.com/alecmaslov/stellardream
https://github.com/iforaa

# Additional Information
 Piyush Maheshwari
 alec@thig.io

**Comment by ErinOCon** [comment]
Hi @alecmaslov, thank you for your proposal and for your patience during our review. Unfortunately, we will not be moving forward with a grant at this time. We are wishing you all the best as you continue to build!
