### ISSUE TITLE
Next Step Microgrant: <Your Title Here>

### ISSUE THREAD

**Issue by alecmaslov** [filecoin-project/devgrants#1235]
### 1. What is your project, and what problem does it solve? (max 100 words)

We have launched a prototype on Stellar-Dream.com showcasing how NFTs can be "embedded" as clickable characters within a digital comic book. The purpose of this prototype is to provide additional utility for NFT holders. With our technology, NFTs get drawn into stories and linked to the underlying smart contract as well as a marketplace where that NFT can be bid on and traded. Currently, we have our project files stored on Amazon AWS as publicly accessible files. We would like for all of our files to be stored on the most optimal Filecoin system and to continue building all future work on top of Filecoin.

The images for our NFT collection are currently on IPFS. https://opensea.io/collection/god-levels
https://etherscan.io/address/0xCb01F00562c7a70026374F29e75510E3066D2932#writeContract

### 2. Project links
  
Link to Github repo: https://github.com/alecmaslov/stellardream
Link to demo or website, if applicable: stellar-dream.com
License: 

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

Currently, we are using AWS to store the images for our prototype, but we would like to use Filecoin. The images for our NFTs are on IPFS.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We will move all of the prototype images off of AWS and onto Filecoin. Currently, our prototype consists of 1 page, 3 embedded NFTs, and 6 total clickable elements. Our next release will be a 15-page scrollable comic book with 7 total embedded NFTs and dozens of clickable elements. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Alec Maslov, CEO, alec@thig.io, https://github.com/alecmaslov
Igor Kuznetsov, Lead Dev, igor.n.kuz@gmail.com, https://github.com/iforaa

* How did you learn about our microgrant program?

Piyush Maheshwari

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @alecmaslov, thank you for your proposal. We will not be moving forward with a grant at this time, but recommend checking out [our hackathons](https://hackathons.filecoin.io/) as a potential next step. 

Wishing you the best as you continue to build!
