### ISSUE TITLE
Next Step Microgrant: GlacierDAO

### ISSUE THREAD

**Issue by inezpereira** [filecoin-project/devgrants#1236]
### 1. What is your project, and what problem does it solve?
We believe that code, like data, should be preserved in a censorship-resistant way. GlacierDAO is a Data DAO that specifically preserves code as a public good. This is done by storing repositories on the Filecoin network.

### 2. Project links
- Frontend Demo: https://github.com/joaosantos15/glacierdao-frontend
- Smart contract Prototype: https://github.com/joaosantos15/glacierdao 
  
### 3. How is IPFS, Filecoin, or related technology used in this project?
GlacierDAO aims to solve the problem of source code preservation. Our vision is to build a DAO that:
* Makes possible the replication of Git repositories which contain code deemed to be of public interest.
* Allows individuals to pool funds together in order to fund the replication of these repositories, on the Filecoin network.
* Rewards individuals who show alignment with the community values by giving them higher voting power on the curation of repos.
* Is completely run by smart contracts deployed on the Filecoin network and does not require accounts with admin privileges. This means that the curation of repos, storage deal making and rewards distribution is handled entirely by the smart contract.

**Technical limitations**
As of December 10th 2022, there are technical constraints which prevent this vision from being fully implemented. These limitations are:
* The FEVM currently only exists on testnets (Wallaby)
* There are no Solidity libraries available for interactions with the FVM (for instance, for storage deal making)

For that reason, the GlacierDAO team proposes a phased approach to development:
* [Stage 1] MVP: Storage done using web3.storage (uses IPFS + Filecoin)
* [Stage 2] Moving to Filecoin: possible once the Filecoin mainnet supports EVM smart contracts. GlacierDAO makes on-chain deals with storage providers
* [Stage 3] Full on Data DAO: At this stage we hope to have an active community who participates in funding the replication of Git repositories and the whole system will be running on the Filecoin network.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective?
See above for detailed roadmap. The current grant would allow us to deploy a fully functioning MVP.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.  

### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions

**Current progress:**
* [Genesis] ETH Lisbon: Prototype built. The GlacierDAO team won the hackathon, as well as 3rd place for the IPFS/Filecoin bounty (see [here](https://eth-lisbon.notion.site/Winners-0b5e1564d84044718ec6d5be50f6d108) and [here for submission](https://taikai.network/ethlisbon/hackathons/ethlisbon-2022/projects/cl9uk7sb335995101tp0k0duqhn/idea))
* [Demo of user interface] HackFEVM: GlacierDAO team members were speakers at the FEVM Summit and mentors at the Hack FEVM Hackathon (see [here](https://web3weekend.ethglobal.com/))
* [Ongoing] Part of [Foundry Program F/1](https://fvm.filecoin.io/foundry)
  
### Additional questions:
* João Santos 
    * Email: [jrmsantos15@gmail.com](mailto:jrmsantos15@gmail.com)
    * Github: https://github.com/joaosantos15
    * Role: Dev
    * Previous experience: Fullstack developer at Consensys Diligence
* Inês Pereira 
    * Email: [pereira.inez@gmail.com](mailto:pereira.inez@gmail.com)
    * Github: https://github.com/inezpereira
    * Role: Everything else
    * Previous experience: Medical doctor & Computational Neuroscientist at ETH Zürich, Organizer of the Annual Computational Psychiatry Course, co-initiator of NeuraDAO, former VitaDAO governance

* How did you learn about our microgrant program?
Via the [Foundry program](https://fvm.filecoin.io/foundry).

**Comment by eshon** [comment]
This is a nice proposal @inezpereira! Note that starting in late January FVM team intends to support a workflow from Web3.storage (i.e., Verifiable Off-chain Data Aggregation) on the coming Hyperspace testnet and it'd be great if your team can help us test that when it's ready as part of this Microgrant.

**Comment by ErinOCon** [comment]
Hi @inezpereira, this microgrant has been approved! We will send you an email to confirm payment details.

**Comment by ErinOCon** [comment]
Hi @inezpereira, I hope your project is progressing well! If you have any questions regarding the reporting process for this work, please be in touch. In the meantime, here are some things we are looking for when reviewing FVM Microgrant results: 

- A fully working user-facing demo with nice UX that anyone case easily use.
- Deployment to FVM mainnet - now that it has officially launched!
- Interesting use of the EVM on Filecoin, especially with respect to what's unique to Filecoin

Happy building!

**Comment by ErinOCon** [comment]
Hi @inezpereira, can you provide an update on your project progress? Below is a current list of what we look for when determining if a FVM microgrant project is complete:

- A fully working user-facing demo with nice UX that anyone can easily use.
- A dapp deployed to a Filecoin testnet like [Calibration testnet](https://docs.filecoin.io/networks/calibration/details/) so that we can see all the functionality working in a demo, and will be deployed to Filecoin mainnet in a production-ready state on project completion.
- Interesting use of Filecoin’s EVM, especially with respect to what’s unique to Filecoin (for example, via exploration of FVM use cases or the Filecoin Solidity API (see https://github.com/filecoin-project/community/discussions/585#resources, or [Bacalhau x FVM](https://github.com/bacalhau-project/lilypad), etc.)

Please be in touch with any questions!

**Comment by ErinOCon** [comment]
HI @inezpereira, can you provide an update on your project in this thread?

**Comment by inezpereira** [comment]
Hi there @ErinOCon ! Thanks for the ping!
We have an open thread with you on the Filecoin Slack workspace 😊

Here are our open questions once more:
 ⁃ Given the time that has passed since the original implementation, is this a project you are still interested in? Or would you say it has become outdated?
 ⁃ What are you expectations for this project and do you have any specific expectations when it comes to its contribution to the ecosystem?
 ⁃ Do you have any recommendations in terms of deployment? How stable are the APIs, currently?

Happy to discuss here or on Slack. Any news from the FVM team?

**Comment by eshon** [comment]
Hi @inezpereira! 

You have a few options, but overall we're NOT so interested in dapps that try to implement basic DAO functionality, like creating a fund, admin for users to vote and control that fund, etc. This is all well-developed territory by many open source DAO projects.

We're more interested in teams that can explore interesting use cases for FEVM / Filecoin and have a high chance of becoming nice, user-friendly dapps that people will want to use.

While the overall idea of backing up Github repos using a DAO is a good, your demo focuses a lot on trying to raise funding for this which may not be that compelling for users to contribute to.

We do have another project your team could work on for the remaining $4k tranche however that would be very useful to the Filecoin developer community...

We'd like to update https://datasets.filecoin.io/ to focus on much smaller datasets that can be stored on Calibration testnet (where there's 1 SP currently accepting smaller deals) for Filecoin developers to use during hackathons.
- Ideally these datasets could be used across FEVM, Bacalhau, etc.
- The goal of this site is to help Filecoin hackathon participants improve the data narratives and user stories in their dapps by suggesting and providing nice sample data sets 
- Many of the mainnet deals on this site have expired but these should all be open source datasets that can be found online
- It'd be great if your team could also research and find additional interesting datasets and get them stored on Calibration testnet
- Please use Lighthouse, PoDSI (a type of proofs of storage), Replication as a Service, etc. to get these stored on Calibration (more info about these services this [Hackathon cheatsheet](https://github.com/filecoin-project/community/discussions/585) or talk to us)
- It'd be great if a form could be added to this website for users to suggest new sample public datasets

Let me know if this project would interest your team.

**Comment by eshon** [comment]
@inezpereira - Any update? Otherwise we can give this project to another team. Please let us know.

**Comment by inezpereira** [comment]
Hi @eshon!

Thank you very much for your response and apologies for the time it took us to respond! 
We're genuinely excited about the vision you've laid out for enhancing https://datasets.filecoin.io/. It's a crucial initiative, and we can see how it would benefit the Filecoin developer community.

That being said, after some internal discussions, we believe that handing this project off to another team would be the best course of action. Due to our ongoing commitments, we won't be able to give this the time and focus it deserves, at least for the next six months.

We're really excited about seeing what another dedicated team will accomplish with this. We're still committed to contributing to the Filecoin ecosystem and will be eagerly following the project's progress. 
Of course, if it helps, we'll be available for any meetings or sharing insights if the new team needs a springboard for their work. 

Thanks again for your work! 
We're looking forward to seeing this project evolve!

All the best,

Inês, João and Vicente

**Comment by ErinOCon** [comment]
Hi @inezpereira, thank you for your response. Since this project is now closed, we will cease future grant payments.

Wishing you the best with future project work!

**Comment by inezpereira** [comment]
Thank you!!
