### ISSUE TITLE
Next Step Microgrant: dePay Decentralise Payment Gateway

### ISSUE THREAD

**Issue by adityakaklij** [filecoin-project/devgrants#1237]
## dePay 
# Scale Secure Decentralise

# What is dePay?

dePay is a Decentralised Payment Gateway for the B2C segment. Just like PayPal, stripe provides a gateway for accepting fiat currency in a centralised manner. dePay provides the same service for accepting all types of crypto as payment over a plethora of blockchains and tokens including FVM! 

1. No KYCs are required.
2. No one is controlling APIs for the transaction. 
3. No payment settlement period.
4. Immediate approval for business.

# Why is dePay Required?

For accepting payments, businesses are required to sign a variety of contracts with the centralised entity, a minimum of 10 days period for verifying the KYC. The entity charges anywhere between 1-7% for each transaction. Payment settlement period of a minimum of 3 days. Even with all hassle, all the authority for payment and all the user's data is completely held by ‘that entity. Businesses don’t have any control. The Gateway providers are utilising the customer's data in multiple ways without taking any permissions.

With dePay, businesses own all the contract rights. Within minutes, businesses are able to accept all types of crypto from the user. With the smart contract, 100% reliable payment acceptance and no central authority is required to verify the transactions. 
dePay is designated to handle end-to-end crypto payments. With a powerful business dashboard, it is easy to analyse sales. 

# dePay for Business

1. Instant one-click contract deployment.
2. Real-time data analytics.
3. Complete no-code customisable smart contract.
4. No third-party intervention.
5. Accepts all blockchains and tokens.
6. Real-time payment notifications.
7. 100% secure.
8. 100% uptime.

# dePay for User

1. No billing details are required.
2. Complete anonymous transactions.
3. One-click payments.
4. QR scan for payment.
5. Trustless.

# How dePay helps to scale the business

1. Accepting all types of ERC-20 tokens.
2. Trustless deployments.
3. No middle-man

### 2. Project links
  
GitHub repo:- https://github.com/adityakaklij/dePay
Details:- ​​https://adityakaklij11.gitbook.io/depay/
Demo site:- https://bafybeiafh7aqvx26ca4it7qm227uxw7zkhqo37asoa2q2526j2quost3fe.ipfs.gateway.valist.io/#/
License:- MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? 

dePay supports multiple blockchain payments. dePay also supports the FVM blockchain to deploy the contracts and accepts all ERC-20 tokens on FVM.
Also for business data analysis, we are planning to use IPFS to store the transaction-related data to later analyse the overall treasure and multi-chain transactions.

###    b) Is this project contributing to the upcoming FVM launch?

Yes
  

### 4. How will you improve your project with this grant? What steps will you take to meet this objective?

1. APIs creation for business deployment.
2. Website improvement and deployment on IPFS.
3. Working on data analysis.
4. Improving smart contract deployment.
5. Onboarding business.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?

Yes. Will agree to share all the details as per request.

### 6. Does your proposal comply with our Community Code of Conduct?

	Yes, Our proposal complies with the Community Code of Conduct.

### 7. Links and submissions

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

    Yes, Project began at the Hackathon, Submitted for the FVM track.
Submission link:- https://devfolio.co/projects/depay-decentralise-payment-gateway-d5d1

### Additional questions:
* For each team member(s), please list name, email, GitHub account, and role in the project.

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-b291d1c4-7fff-e758-7cd0-ba7b774bdb27"><div dir="ltr" style="margin-left:0pt;" align="left">

Aditya Kaklij | adityakaklij11@gmail.com | https://github.com/adityakaklij | Lead
-- | -- | -- | --
Ashutosh Shimpi | ashushimpi0211@gmail.com | https://github.com/Ashuu02 | Front-end dev
Jaydatta Bade | jaydattabade11@gmail.com | https://github.com/Jaydatta-Bade | Management
Nikhil Shinde | shindenikhil659@gmail.com | https://github.com/shindenikhil659 | Deployment
Sarthak Shilwant | shilwantsarthak6@gmail.com | https://github.com/Sarthak-006 | Data Analytics

</div></b>

* How did you learn about our microgrant program?
Filecoin e-mail

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
    ETHIndia2022

  * Please link to your hackathon submission
	https://devfolio.co/projects/depay-decentralise-payment-gateway-d5d1

**Comment by ErinOCon** [comment]
Hi @adityakaklij, thank you for your proposal. We will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
