### ISSUE TITLE
Next Step Microgrant: Banana Smart Wallet

### ISSUE THREAD

**Issue by hfarazul** [filecoin-project/devgrants#1238]
### **Problem with current wallets:**

- Withdrawals from **custodial wallets** can be frozen, users don’t have control over their assets.
- **Non-custodial wallets** are prone to hacks, and the recovery mechanism is usually difficult.
    - **Hardware wallets** are safe, but the UX is bad, and they are expensive.

### Banana wallet by In**finito Labs:**

We are building a **wallet infrastructure** that any application can integrate and provide:

- Self-custodial solution
- Safety at par with a hardware wallet
- The user experience would be as good as a centralised solution

### **How it works:**

We are achieving this by using smart contract wallets based on an account abstraction solution. This enables us to **provide custom features**, one of which we have successfully implemented is a zero-knowledge proof-based **two-factor authentication system**. This 2FA prevents a single point of failure, and even if your private key is compromised, the hacker **cannot access users’ funds.**

<img width="980" alt="image" src="https://user-images.githubusercontent.com/26204081/206875428-c17b7f40-0c95-42a6-a6da-85c8922e4c00.png">

### 2. Project links
  
Link to Github repo: https://github.com/nlok5923/hacking-at-ethindia
Link to demo: https://youtu.be/pwRpqJxBWdg
Link to app: https://banana-smart-wallet.netlify.app/
License: APACHE2

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
The project leverages IPFS to store the merkle tree.
<img width="778" alt="image" src="https://user-images.githubusercontent.com/26204081/206875479-080faae9-52d3-4bc3-8e48-1668e425141d.png">

In future, it can also be used to store encrypted recovery key of accounts

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
  No plans for now, but we can create solutions to optimise storing data on Filecoin and can create Data DAO in future.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will use the grant to create an SDK of the functionality and create a robust authentication mechanism using TouchID. 

Milestone 1: 

- Build the functionality of zk two-factor authentication (fraud management) on the application **(done)**
- Validate the prototype with ~50 users. **(In-progress)**
- Talk to customers to define and refine the needs **(In-progress)**

Milestone 2: 

- Build SDK of two FA(fraud management) **(To-start)**
- Build the functionality of authentication using touch ID **(To-start)**

**Here is the grant budget breakup:**
- $1750 - 2 Smart Contract dev interns to integrate safe(gnosis safe) and launch on polygon, and optimism
- $750 - Full stack intern to build SDK
- $1250 - Generalist for user research, designing user experience and BD.
- $750 - Infra costs
- $500 - Marketing/ Business Development/ Misc

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, we will provide a detailed report upon completion of 3 months.

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
We participated in ETHIndia
ETH India website: [https://ethindia.co/](https://ethindia.co/)
Here's the link to hackathon submission: [https://devfolio.co/projects/banana-smart-wallet-efca](https://devfolio.co/projects/banana-smart-wallet-efca)

Some recognition that we got in ETHIndia
- First prize 🥇 from Ethereum Foundation
- First prize 🥇 from Safe(prev. Gnosis safe)
- First prize 🥇 from Gnosis chain
- Third prize 🥉 from Coindcx
- And pool prizes from filecoin and push protocol

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
We are a team with **skillsets in product and software development**. We have professional **experience in web2 and web3** and have worked on multiple side projects together.

Haque Farazul (Product and Research)
- Email: [[h.farazul@gmail.com](mailto:h.farazul@gmail.com)](mailto:h.farazul@gmail.com)
- Github: @hfarazul

Rishabh Gupta (Smart Contract Dev, Full stack Dev)
- Email: [[rishotics@gmail.com](mailto:rishotics@gmail.com)](mailto:rishotics@gmail.com)
- Github: [[@rishotics](https://github.com/rishotics)](https://github.com/rishotics)

* How did you learn about our microgrant program?
From a Juan Benet at his ETH India talk.

* If your project was created as part of an event or hackathon:
  * What was the name of the event?
  ETH India
  * Please link to your hackathon submission
https://devfolio.co/projects/banana-smart-wallet-efca

**Comment by dawnkelly09** [comment]
Greetings! I am processing your grant application. When I tried to review the project repo, I got a 404 error. Would you please provide a working link to the project repo so I can review your code? Thank you!

**Comment by rishotics** [comment]
Hey Dawn, here is the link for the repo: https://github.com/nlok5923/hacking-at-ethindia . So sorry for the inconvenience caused.

**Comment by ErinOCon** [comment]
Hi @hfarazul, this microgrant has been approved! We will send an email to confirm payment details. Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
