### ISSUE TITLE
WootzApp: Mobile web browsers with deep wallet integration  

### ISSUE THREAD

**Issue by sandys** [filecoin-project/devgrants#1241]
# Open Grant Proposal: WootzApp: Mobile web browsers with deep wallet integration  
 
 **Name of Project:** WootzApp
 
 **Proposal Category:** `app-dev`
 
 **Proposer:** sandys
 
 **(Optional) Technical Sponsor:** NA
 
 **Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes
 # Project Description
 
Onboarding the next billion users to Blockchain. Are you going to ask them to use a desktop browser extension ? Most people dont have a desktop - especially in Asia. Their only device of accessing the internet is their mobile phone. That's why you need a web browser build ground up for crypto (and which implements all of the browser specific EIP). The user does not need a wallet app and a browser app separately.

Wootzapp is the way that a hundred million NEW users will use the FileCoin chain for the *First Time*. In fact, by making their first account on filecoin, we will lead the default chain experience to be FileCoin first. We want people to mint their first FileCoin asset/NFT within 30 seconds of signing up for Wootzapp. It stands to reason, since FileCoin manages assets like images and media and the number reason people do anything on the web is media.

we are a fully opensource (https://github.com/wootzapp/wootz-browser) mobile browser that is built for crypto. The wallet and everything else is integrated in. We have also implemented several EIP that were specific to browser integration and were waiting for Chrome to implement in.
for a new user to crypto - especially the billions of users in Asia who do NOT have a desktop computer or browser extensions - the way to use crypto is simply "use this browser, it has everything built in". 
If you visit a dapp website, our custom javascript-native bridge will popup and all the web3 functions will work automatically.
 
The goal of this proposal is to create a new web browser for the next billion users to interact with Web3 services such as IPFS, Filecoin, etc. You can think of this like Google Chrome built purposely to the needs of first time crypto users (and with better integration for Web3 services).
Our goal is to give the easiest possible onramp experience for the mainstream user (who is not crypto savvy) and then progressively draw him deeper over time into ZK rollups, Account Abstraction, etc.
 
We are razor focused on dropping cost of acquisition for blockchain at large. By solving for on-ramp. Our whole goal is to bring the next 100 million users to crypto. Our GTM is to act as the heldesk for crypto/NFT projects who encounter "how should I use a wallet" or "how do I mint this NFT". WootzApp will act as the helpdesk for these users on social media. 
Our revenue model is well understand - similar to Firefox. we will have partnerships with default search engines, swap platforms and exchanges.

 ## Value
 
 **What are the benefits of getting this right?**
 
 We believe that a web3 browser built ground up can open up the addressable market for crypto. In a time for market volatility, it is a matter of great urgency to expand the market outside the few million crypto early adopters and influencers.
 For example, even in the US, crypto adoption is restricted to the major cities like NY,LA, SF. However if you go to the midwest, where there is abysmally low credit card penetration..it is surprising that there is no crypto adoption. This is trillions of dollars left on the table for the overall crypto world.
 The best case scenario is that our browser kickstarts a next generation of dapps built purposefully for the mainstream user. 
 
 **What are the risks if you don't get it right?**
 
Hindi is spoken by 300 million users across India, Pakistan, Nepal and Bangladesh. There is no word for "virtual" in Hindi. BIP-39 mnemonic also has no equivalent in Hindi.
In our experience, crypto onramp is in its infancy and the design+language of crypto needs to evolve to serve the needs of all.
Failing to get this right could put off the mainstream user for a long long time. And it is the mainstream user that has the voting power to change regulations.

 **What are the risks that will make executing this project difficult?**
 
 Distribution and retention.

 Distribution: Distributing a new browser is known to be a tough problem. We hope to mitigate this by acting as the heldesk for crypto/NFT projects who encounter "how should I use a wallet" or "how do I mint this NFT". WootzApp will act as the helpdesk for these users on social media. 
 
Retention: Design and Langage is key to keep the user from getting frustrated with the developer experience. We have found great value in design workshops with this demographic. For example these are our design studies for what a new tab looks like in https://twitter.com/WootzApp/status/1599108929711378432 and https://twitter.com/WootzApp/status/1598380478029266944
We propose to have 4 designers do indepth interviews in 4 different countries - India, Brazil (esp the favela neighborhood), Nigeria and Greece. We will choose non-major cities and these designers will spend 1 month iterating on design in their communities. we are estimating a rough cost of 2000$ per month for each designer and some incidentals.
This is the highest value deliverable that comes out of this project. We commit to release this study publicly to have them in the public domain for the ecosystem to utilise.

 ## Deliverables
 
     * Design study for new markets - on how to give a killer onramp experience to the mainstream user in crypto
 
     * Fiat ramps to Filecoin
 
     * Security Audit of Flutter Codebase
 
 ## Development Roadmap
1. Security Audit of Flutter Codebase::30 days::10K USD
Done by external agency. most auditors are familiar with Solidity. Flutter and mobile codebases need a special audit.

2. Initial filecoin integration::30 days::5k USD
This involves filecoin integration into the mobile app, testing on both platforms (ios + android) and release to live. We want to have users an experience where they can entirely replace the imgur/dropbox experience with filecoin.

3. Fiat ramps to filecoin::90 days::5k USD
Being able to buy filecoin in a single click of the button with credit card, etc. I have worked for a long time in payments space. this will take the longest because of the need for specific compliances/approvals, etc. This is critical for Filecoin, since the protocol hinges on being able to incentivize file processing. Anything that makes this super easy from the end user side is super critical and is missing from Filecoin right now

4. Design study for new markets::120 days::12k USD
Our primary goal is to be the wallet for the next billion users. We figured out that it can only happen if you kill the concept of a wallet. And become a browser.
We have found great value in design workshops with this demographic. For example these are our design studies for what a new tab looks like in https://twitter.com/WootzApp/status/1599108929711378432 and https://twitter.com/WootzApp/status/1598380478029266944
We propose to have 4 designers do indepth interviews in 4 different countries - India, Brazil (esp the favela neighborhood), Nigeria and Greece. We will choose non-major cities and these designers will spend 1 month iterating on design in their communities. we are estimating a rough cost of 2000$ per month for each designer and some incidentals.
This is the highest value deliverable that comes out of this project. We commit to release this study publicly to have them in the public domain for the ecosystem to utilise.
The value to filecoin is this - we want filecoin to be the first/default blockchain for these users. And most of them know only about "Bitcoin" if anything. How do you explain the value of investing in filecoin to this demographic? This is a low cost cost-of-acquisition line item for filecoin. I would imagine the result of this study to be utilised in your own marketing materials, for example.
 

 ## Total Budget Requested
 
 $25,000

 # Team

 ## Website and Code Repositories
 
* [https://www.wootzapp.com/](https://www.wootzapp.com/)
* [https://github.com/wootzapp/wootz-browser](https://github.com/wootzapp/wootz-browser)
* [https://play.google.com/store/apps/details?id=com.wootzapp.browser](https://play.google.com/store/apps/details?id=com.wootzapp.browser)
 

 ## Founder
 
Sandeep Srinivasa is a senior payments CXO with about 20 years experience in payments and startups. His last company was YCombinator and Lightspeed funded. His last company had about 3 million payment users. He is on the board of several national banking and federal regulatory boards in India. He is also named on semi-banking licenses by the banking regulator of India. He has spent a decade on payment APIs, regulations and compliance. With particular focus on onramp millions of users to payments.  
[https://www.linkedin.com/in/sandeepss](https://www.linkedin.com/in/sandeepss)   
[https://github.com/sandys/](https://github.com/sandys/)
[https://twitter.com/sandeepssrin](https://twitter.com/sandeepssrin)

**Comment by ErinOCon** [comment]
Hi @sandys, thank you for your proposal and for your patience during our review process. Unfortunately, we will not be proceeding with a grant at this time. We are wishing you all the best as you continue to build.
