### ISSUE TITLE
Next Step Microgrant: GETSecured

### ISSUE THREAD

**Issue by detasecure** [filecoin-project/devgrants#1242]
### 1. What is your project, and what problem does it solve? (max 100 words)
Can we build an analytics and early warning/alerting system that could possibly save web3 investors from losing money in an FTX kind of incident?

Questions the web3 investors & project owners are always worried about after the investment are : 
- Is the fund getting utilized properly? 
- Is there a way to get regular notifications about the cash flow? 
- Are there any data breaches or vulnerabilities in the project that could possibly impact the company?

There is very limited transparency today in understanding the cash flow of a project and identifying any technical vulnerabilities or data breaches.

No mechanisms are available to do regular automated recurring reporting for financial MIS to investors and data breaches & vulnerability alerting to founders. 

### 2. Project links
  
Link to GitHub repo: https://github.com/detasecure/ethIndia2022

Link to demo or website, if applicable:
Here are three different components of the project that I built in three different hackathons and now consolidating them together to make it a full-fledged product.
- https://devfolio.co/projects/niche-3b93 (ETH India winner)
- https://devpost.com/software/gsos-getsecured-on-chain-security (Polygon BUIDL winner)
- https://docs.google.com/presentation/d/1yNL-_E9ND6p5dS0ly9vf7dKgtxY09msGMf9fJFxrOcg/edit#slide=id.g137a3e96b3c_0_302 (ETHNYC winner)

License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

We will be dealing with a lot of sensitive data which we would like to store in IPFS and maintain a ledger of who is accessing those data and when. This will help us to protect the data and track the activities in a more transparent and secured manner.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
Well, spoke to Sarah, and we would love to be part of the FEVM early builder program so that the other projects can make use of this p[rogram.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We would be focussing on the UI/UX to make it very intuitive with meaningful data and actionable. We would also build a decentralized storage architecture.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?

Sure.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  I have shared the link above.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
Got a mail from Corey and Sarah
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  ETHNYC, PolygonBUIDL, ETHIndia

  * Please link to your hackathon submission
  Submitted above

**Comment by ErinOCon** [comment]
Hi @detasecure, thank you for your proposal! We will not be proceeding with a microgrant at this time, but would encourage you to check out upcoming [Space Warp](https://spacewarp.fvm.dev/) opportunities as you continue to build with FVM. 

Wishing you the best with your project!
