### ISSUE TITLE
Open Grant Proposal: NFT content conversion SDK 

### ISSUE THREAD

**Issue by vartprotocol** [filecoin-project/devgrants#1243]
# Open Grant Proposal: `NFT content conversion SDK`

**V-Art Protocol Converter**

**Proposal Category:** `app-dev`

**Proposer:** `vartprotocol`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:**  Yes

# Project Description

Today there is a demand for the use of various creative digital assets not only from nft collectors, but also from games, art, fashion and e-commerce industries. Problems, stopping the market from mass adoption of digital assets (and making something like Ready Player One not our reality yet) are the questionable value liquidity, IP rights mismanagement, and the limited options for actually using the digital assets and almost no cross-platform integrations (also both a legal and a tech problem). This is especially true for 3D content, but currently this conversion option is not provided by any NFT platform or Protocol, as the file within the NFT is usually stored on IPFS in only one possible format. From the legal standpoint, further using the digital assets commercially/non-commercially, integrating it to other platforms, means that the rights for this change should have also been provided at the moment of the sale. Which is not covered by the status-quo of the NFT market. Thus, the brands and creators cannot really track how their content is being further modified, integrated and used. It's time for a change.
<br>
V-Art Protocol is a white-label solution for licensing creative digital assets with IP rights verified and managed on the blockchain. It is a simple, safe, and flexible way to monetize creative digital assets 3-5x more as NFTs with IP rights, plus integrate them to different digital platforms (metaverses, AR/VR, games, etc). https://vartprotocol.com/ 
We already use IPFS to store the files, connect them to the main tokens and to the licensing tokens (sub NFTs), created specifically through our solutions. In this grant project we want to  integrate with Filecoin via NFT.Storage, by introducing a unique feature of automated conversion and adaptation of the files through IPFS and tokens to the formats needed for the particular usage cross-platform – in games, Metaverses, AR/VR, social media, etc. Next goal is to connect our current and future partners both from web2 and web3 creative, tech and luxury businesses to it, and streamline the licensing and direct integrations of the content. 
<br>
Our conversion solution (to be available open-source) shows how to bind an already converted file to NFT legally and technically with the additional possibility of subsequent validation of the converted file. Thus, the minified NFT will have links not only to the original media, but also to the converted copies, some of which may already have links to the viewer or other integrations. Also, the approach to storing information about validated file storage is additional evidence of the authenticity of the NFT that is used and resold.

![Mintbase-Licensing Conversion V-Art](https://user-images.githubusercontent.com/116814057/207070096-431c0da9-fc75-4f6b-95d2-28e7f14aa7db.png)
![Mintbase-Filecoin Conversion V-Art](https://user-images.githubusercontent.com/116814057/207070110-c9d86e37-8bef-46eb-8b60-d36a40073e02.png)

## Value

**Benefits:** we will bring our unique expertise in IP law and immersive tech to the Filecoin community, in addition to our extensive base of Ukrainian and global partners with art and cultural assets. Providing the white-label and easy-to-integrate V-Art Protocol solution together with a new unique converter feature (converter is to be open source, V-Art Protocol – free to connect after the KYC, closed code), we will help any project to streamline the licensing and integration of their creative digital assets to games, Metaverses, AR/VR, avatar platforms, social media and virtual spaces. We support cross-contract licensing already together with moderation of brands, creators, and much more.
**Challenges of the project:** 
setting up the right WebGL use cases (Examples) for most of the developers and businesses 
not supporting certain types of files to be converted

## Deliverables

The result of the proposed project will be an open SDK that allows you to convert content from NFT to another format necessary for the user. Also, during the project, examples and ready-made templates will be developed for the further use of such content: virtual 3d galleries developed on WebGL, e-commerce web modules for selling and displaying NFTs. A module will also be developed to verify the correctness and authenticity of the conversion/compression done.
## Development Roadmap

**Milestone 1**

*Converter solution for NFT marketplaces:* 
-	Implementation of Draco compressing library. Implementation of Facebook FBX to gLTF converter. 
-	Development of the library that enables converting of the 3d assets via, stores compression data on IPFS via NFT.Storage and provides links to compressed results.
-	Development of the JS SDK that contains all needed functionality such as: minting, conversion obtaining and verifying conversion results and additional features of assets transferring, selling, etc.

**Budget: 35k**

**Estimated time: 3 months**
<br>
**Milestone 2**

*File convertion with templates and use cases for 3d:* 
-	Development of minting SDK for AR and Virtual Gallery Experiences. Part one. Implementation of multiple 3d (.fbx, .obj, .stl, .dae) and image formats conversion libraries with ready use cases for web site usage (both conversion and compression of the model). 
-	Development of the example of an e-commerce website as a template. Open-source libraries will be used as base.

**Budget: 30k**

**Estimated time: 2 months**
<br>
**Milestone 3**

*File convertion with templates and use cases for audio and video:* 
-	Implementation of video and audio formats (mp3, mp4, mov, wav) conversion libraries with ready use cases for web site usage (both conversion and compression of the model). 
-	Development of npm package that supports viewing of the converted content. 
**Budget: 25k**

**Estimated time: 1.5 month**
<br>
**Milestone 4**

- Community building and public announcements. Organise an online event for creative, tech and luxury businesses and the benefits of Web3, where the experts will discuss and give some tips + how to protect your IP in a Web3 World, as well as highlight the specifics of the Filecoin infrastructure for it. PR and sales support in promotion of the announcement of the V-Art Protocol and licensing being available. Onboarding of web2 (fashion, art, luxury) brands to the created solution.

**Budget: 10k**

**Estimated time: 2 months**

## Total Budget Requested

100.000 USD

## Maintenance and Upgrade Plans

V-Art will provide this library to be implemented in several marketplaces including those which are developed or to be developed. After the grant is completed, we will also onboard projects and web2 businesses, connecting the V-Art Protocol (admin panel, API, automated certification and many more features), to use the NFT Converter solution. Education and ongoing legal support to the community, integrating the NFT Converter and/or V-Art Protocol, are as always our priority.

**Our objectives:**

**Long-term goal:** become the global unifying bridge for creative content. Can compare the final point of the V-Art Protocol network, connecting creative, tech and luxury companies, as an “AppStore, where you can exchange and monetize the content between the apps”. But we as a business are realistic about the pros of accelerating the growth in case of being offered a highly beneficial acquisition, and if this happens, we as founders plan to stay on the board.

**Middle term:** reach a total of 1M people using the V-Art Protocol (through the communities of the creative, tech and luxury companies connecting it), develop cross-platform bridges (to games, AR/VR, Metaverse, social media, etc) and cross-blockchain (currently support NEAR and Ethereum, want to be on other EVM-compatible blockchains and consider partnerships with other too), launch our V-Art token and raise series A.

**Short term:** connect 192 companies and projects from our pipeline  to the V-Art Protocol, develop an NFT converter and expand our team to provide more integrations of the V-Art Protocol, raise community awareness of the IP rights on the Blockchain.

# Team

## Team Members

- Project Coordinator: Anastasiia Gliebova
- Technical Lead: Anton Dembytskyi
- 3d Assets guidance: Ruslan Kapustin
-	Full Stack/SDK Dev: Valerii Beloenko
-	Front-end Dev: Bogdan Malina
- Back-end Dev: Kostia Lopykh
- UI/UX design: Victor Grytsenko

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/anastasiia-gliebova-96a4681a3 

https://www.linkedin.com/in/ruslan-kapustin 

https://www.linkedin.com/in/anton-dembitsky-ba71471b9/

https://www.linkedin.com/in/olga-simson-416a9883/ 

https://www.linkedin.com/in/olegglovatskiy/ 

https://www.linkedin.com/in/alexandr-velychko-50698a172/ 

https://www.linkedin.com/in/anastasiiakiondratiuk/ 

## Team Website

Company’s website: https://v-art.digital/

V-Art Protocol: https://vartprotocol.com/ 

## Relevant Experience

V-Art team combines expertise in IP law, Blockchain, and immersive tech (3D/AR/VR), and is highly strengthened by a board of advisors and mentors. Founders are all serial Ukrainian entrepreneurs, located in Portugal, UK and Ukraine, who have previously built legal and tech businesses together. Now we have 14 full-time colleagues all over the world, our own tech department and an extensive IP portfolio of our own virtual exhibition tech, AR and VR applications, as well as a unique tech model for blockchain-powered licensing.

Our mission: to launch and help to monetize a new wave of digital creativity across Web3. 
Our vision: to enable multi-platform licensing of creative assets for a new era, the Internet of Value.

V-Art’s executives, directly working on the project:

**Anastasiia Gliebova, CEO and Co-founder**
Ukrainian tech entrepreneur with a deep passion for blockchain and creative digital assets. Prior to V-Art, she used her background in international law and business at 5+ years of experience as a manager and legal advisor of over 30 creative projects. She is also Partner and Head of Research at the Institute of Law, Technology and Innovation, guest lecturer at multiple universities, including Sotheby’s Institute of Art.

**Anton Dembytskyi, CTO**
Results-oriented IT professional with over 8 years experience in development and technical leadership for gaming, AR/VR, AI and blockchain projects. Anton leads the R&D team at V-Art, including product development, technical analysis and market research from initial idea to the final product launch. He’s led over 30 development projects for various startups and corporations in the USA, Ukraine, UK, EU and Israel. In 2017 Mr. Dembytskyi founded the software development company, Soft U Up, which provides services for AR/VR and complex R&D solutions. He also invented an artificial intelligence app for a new board game similar to backgammon.

**Olga Simson, Chief Strategy Officer and Co-founder**
Doctor of Law with over 20 years of experience providing legal counsel for creative brands and more than 50 successful cases of building IP portfolios for IT, art, fashion, media and other companies. Olga’s expertise combines academic research and teaching with providing legal counsel for tech businesses. In 2016, she founded the Institute of Law, Technology and Innovation (ILTI), the first company in Ukraine to provide educational and legal services for creative industries. Simson has also been a key expert for EU, USAID and UCF projects. She is author of the Art Market Guide and a series of handbooks on legal issues for creative industries. Simson has published over 110 scientific papers, and specializes in legal counsel for digitization processes and intellectual property protection and innovation.

**Ruslan Kapustin, CCO**
Seasoned professional with over 14 years of emerging technology and application development experience. With a high business acumen and natural aptitude for leading international teams, Ruslan oversees the entire creative project lifecycle from initial scoping to deployment. His well-honed communication, negotiation, resource management and systems analysis skills enable his teams to maximize efficiency and ROI. Ruslan is the author of the first VR courses in Ukraine.

## Team code repositories

Solutions were closed-sourced so far, for that reason we cannot provide source code of the V-Art Protocol project. 
Lite paper: https://docsend.com/view/5i69i3bh2mjr8wc7 
How it works: https://vartprotocol.com/licensing-protocol/ 
Demo: https://docsend.com/view/afmutbm85ddw4xaf 
As seen by The Block: https://www.theblock.co/post/181859/new-protocol-aims-to-improve-on-chain-nft-intellectual-property-rights 
GitHub links:
https://github.com/KostiaLopukh 
https://github.com/MalinaBogdan 
https://github.com/valexandrovich 
https://www.behance.net/victordetroy 

# Additional Information

Email: anastasiia.gliebova@v-art.digital (CEO), anton.dembytskyi@v-art.digital (CTO).

Met the Filecoin team at Web Summit (had an exhibition booth right in front of the Filecoin pavilion), talked to team members about the ecosystem and applied to introduce and enhance our solution in it. 

We are striving to provide a “one-click-to-integrate” mode, our current focus is on establishing partnerships with leading digital platforms (Meta, Ready Player Me, Epic Games, Steam, etc). And the conversion solution would not only streamline the technical side of enabling the content integrations, but also provide the community with “one-click-to buy - one-click-to-use” for any creative digital assets. Which will enhance the adoption of IPFS, Filecoin and V-Art Protocol respectively.

**Comment by ErinOCon** [comment]
Hi @vartprotocol, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time, but you may have an interest in checking out [an accelerator program](https://ecosystem-wg.notion.site/Protocol-Labs-Accelerator-Program-d45d8792a7d544eca9beb7d3e3d3b05d) for this project!

Wishing you all the best as you continue to build!
