### ISSUE TITLE
Next Step Microgrant: <Educ>

### ISSUE THREAD

**Issue by joaoolucas** [filecoin-project/devgrants#1244]
### 1. What is your project, and what problem does it solve? (max 100 words)

Educ is a learn-to-earn blockchain protocol that allows the creation of courses with an open and personalized curriculum by the teacher or institution that wants to bring gamification to their teaching. Each course created on the platform has a curriculum with challenges based on the content studied, students enroll in courses of interest and receive participatory study content with real interaction. By bringing an individualized curation of students, allowing the teachers to define who their students will be and evaluate their exercises, we believe that this maximizes the effectiveness of teaching, bringing a real effect of feedback to the student and proximity to the teacher.

### 2. Project links
  
Link to Github repo: https://github.com/marciob/education-dapp
Link to demo or website, if applicable: https://education-dapp.vercel.app/
License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

Filecoin via web3storage will be used to store the metadata of the courses, such as classes and tasks. Also, the metadata of a course completion NFT.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)

No.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- Improve the UI/UX 
- Create course rating system
- Completed course NFT certification
- Create a mobile prototype

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

The demo was made at Ethereum São Paulo, where it was submitted for an Filecoin prize.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
João Lucas Liberato Alves - Blockchain Developer
GitHub: https://github.com/joaoolucas
Email: joaolucasliberato4@gmail.com

* How did you learn about our microgrant program?
Through a friend.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
 Ethereum Brasil - Ethereum São Paulo Hackathon

  * Please link to your hackathon submission
  https://taikai.network/en/ethbrasil/hackathons/ethereumsp22/projects/cl7wa1d6m141134001wuwoxazrdv/idea

**Comment by ErinOCon** [comment]
Hi @joaoolucas, thank you for your proposal! It looks like there are a number of builders on your team that are not referenced in this proposal. Can one of your team members comment on this Issue confirming that they are aware of this grant and will be contributing to the next steps outlined in item 4?

**Comment by joaoolucas** [comment]
Hi @ErinOCon, I'm developing this project alone.

**Comment by ErinOCon** [comment]
HI @joaoolucas, thank you for your reply. Since we do not have a clear view of your building contributions, we will not be proceeding with a grant for this project.
