### ISSUE TITLE
Next Step Microgrant: <DEAL-LOCK>

### ISSUE THREAD

**Issue by holyaustin** [filecoin-project/devgrants#1245]
### 1. What is your project, and what problem does it solve? (max 100 words)
DEAL-LOCK is a new and efficient way to Time Lock Storage deals on Storage Providers in the Filecoin network. This project intends to use a time lock actor on  Filecoin storage deals (deals 67 - 82). The project will also allow users to store data in and retrieve data from the Filecoin network via deals. Participants in the network, miners (supply-side) and clients (demand-side), interact with each other via storage deals and retrieval deals. This DApp pulls out various variables of any deal once the time lock expires. 

### 2. Project links
  
 [Link to public Github repo](https://github.com/holyaustin/deal-lock) 
 [Link to demo or website, if applicable](https://ethglobal.com/showcase/deal-lock-ob00d) 

License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
IPFS FVM is a new way to bring compute to data and storage providers. This project will help to time lock IPFS storage deals.  Filecoin storage providers can now leverage the power of FEVM to create deals that will help store data with various storage compute on data. This provider will use both the MarketAPI and  MinerAPI to create storage deals on the Filecoin Storage Network. Zondax API will be used.

###    b) Is this project contributing to the upcoming FVM launch? 

(Yes )
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
During the hackathon, the work was not completed on both the smart contract, frontend and the interaction between the smart contract and the front end.
* Developing the time lock smart contract to interact with the Filecoin Actor.
* Using Zondax API to optimize the smart contract for better performance and to seamlessly call methods on Filecoin built-in actors, as well as to access Filecoin-specific syscalls idiomatically.
* Integrate frontend visuals for users
* Create deal lock options
* Improve the front-end to a better user interface 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes. A report on the completion of the project will be made available. 
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes 

### 7. Links and submissions
* ETHGlobal HackFEVM2022 Hackathon
*  https://ethglobal.com/showcase/deal-lock-ob00d
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Augustine Onuora, holyaustin@yahoo.com, @holyaustin – Sole developer.
* How did you learn about our microgrant program?
I was emailed about it after the hackathon
* If your project was created as part of an event or hackathon:
ETHGlobal HackFEVM2022 Hackathon

**Comment by ErinOCon** [comment]
Hi @holyaustin, thank you for your proposal! We are sorry to let you know your project was not selected for a FVM microgrant at this time. Please note we are planning to release another round of grant funding in a few weeks. You are welcome to re-apply with the above or a future FVM project once the new grant funding round has been announced. Until the new founding round opens, no applications will be reviewed or accepted. 

If you have already started building your project, we would like to encourage you to join the community of builders on Filecoin Slack and to consider submitting your project to the FVM Community Leaderboard, where the community votes bi-weekly on the top projects to win prizes from a $75k prize pool. Learn more [here](https://network-goods.notion.site/Impact-Evaluators-Builders-Leaderboard-602ea6755b5642e1ad6f9da59a47fa62).
