### ISSUE TITLE
Australia - Melbourne Filecoin Conference

### ISSUE THREAD

**Issue by ChansonStudio** [filecoin-project/devgrants#1247]
### 1. What is your project, and what problem does it solve? (max 100 words)
Over the course of 3 months (Jan 2023 - March 2023), we propose to undertake the following community-building services for the Filecoin ecosystem: 
**1. Build Filecoin brand and ecosystem presence in Australia**
- Run 1-2 conferences in Melbourne for Filecoin, targeting developers, conducted by local developers who understand the technicalities
- Encourage developer communities to join our established channels for updates and regular engagement (Filecoin Slack and Telegram once they are set up)

**2. Collaboration on other existing hackathons where appropriate**
- We have an existing engagement with Monash University blockchain centres(https://www.monash.edu/blockchain) as well as RMIT university blockchain innovation hub (https://rmitblockchain.io/)
- As part of the proposal, we will collaborate with these two institutions to loop Filecoin in (where appropriate) into relevant Blockchain or Crypto Summits or Conferences in collaboration with them for speaking engagements, etc.

**3. Introduction to Strategic Partners and Enterprises in Australia** 

Advise Filecoin on potential high leverage collaborations in Australia (and/or New Zealand), and make the introduction - such as Blockchain Australia, CSIRO, Monash university, RMIT university, Melbourne University etc; other blockchain projects

### 2. Project links
  
Link to Github repo: https://github.com/ChansonStudio/
Link to demo or website, if applicable: https://chansonstudio.xyz/
License:
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
Our proposal will aid in the following goals:
- Grow Filecoin presence in Australia, focusing on the overall brand and visibility
- Engage and onboard more Developers and Filecoin enthusiasts in Australia
- Build 1-2 strategic partnerships with large enterprises in Australia
- Monitor Australian community feedback to advise any next steps required

Potential risks of not getting it right:
- Filecoin lost the opportunity to grow Australian community, brand and adoption in Australia-New Zealand.

Potential risks that will make executing on this project difficult: 
- Sudden tightening of crypto landscape by government (such as restricting activities)

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
No

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
No
  
## Development Roadmap
Here is a tentative timeline for some of the activities, where best effort is placed to conduct the activity or similar activities either within the month or in another month.
Tentative date for the Melbourne Filecoin conferences
-	25th Jan 2023
-	20th March 2023

## Total Budget Requested
- $4,000

# Team
## Team Members
- Jack Hui

## Team Member LinkedIn Profiles
- https://www.linkedin.com/in/jackhui88/

## Relevant Experience
- Co-founder of Chanson Studio, Filecoin grant recipient project in 2022
- Co-founder of Project Galapago, a web3 NFT liquidity protocol
- Hosted over 10 meetups in Melbourne, Hong Kong, Shanghai, Chengdu.

**Comment by ErinOCon** [comment]
Hi @ChansonStudio, thank you for your proposal. This request falls outside of the scope of our microgrant program, but please feel welcome to [apply](https://forms.gle/T9XF3HZKEcurYLpV8) with [Orbit](https://orbitcommunity.filecoin.io/)!
