### ISSUE TITLE
Next Step Microgrant: asserts_ipfs_smartcontracts

### ISSUE THREAD

**Issue by xinminsu** [filecoin-project/devgrants#1248]
### 1. What is your project, and what problem does it solve? (max 100 words)
a.deploy smart contract for much type of  3d or game asserts
b.load from IPFS: from transaction id or something simular to load files from IPFS
c.update to IPFS: pay gas fee to call smart contract, after aproved, save to IPFS

### 2. Project links
  
https://github.com/xinminsu/asserts_ipfs_smartcontracts

License:

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
3d or game asserts editors new save and open features in ipfs smart contract :deploy smart contract,  save to ipfs, load from ipfs

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
a.FVM smart contract support for blender asserts:
- smart contract deploy, save and open through smart contract in https://github.com/blender/blender (will fork soon later)

![blender-save-startup-file](https://user-images.githubusercontent.com/16698808/207489160-dfbd98df-433b-4209-bfcc-42ca73cfd422.png)

b. FVM smart contract support  for unreal asserts
- smart contract deploy, save and open through smart contract in https://github.com/EpicGames/UnrealEngine  (will fork soon later)

![unreal](https://user-images.githubusercontent.com/16698808/207489277-74a474b4-2348-4ce8-9e1a-5c868915e4d5.jpg)

c.FVM smart contract support  for unity component
- smart contract deploy, save and open through smart contract in  https://github.com/BayatGames/SaveGameFree 
![ComponentSaveSystem](https://user-images.githubusercontent.com/16698808/207489385-63682782-5dbf-4e23-9b1b-49f58a79e27c.png)

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
We will report content include progress or results of microgrant-funded work, filecoin technical or usage guidance we used, and a description of our team experience building on Filecoin, also including any challenges or shortcomings encountered.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Our project will be in compliance with Filecoin Code of Conduct

**Comment by xinminsu** [comment]
Thanks for your timely information.

Yes, in my old project (#655<https://github.com/filecoin-project/devgrants/issues/655>), I used web3.storage to save files to IPFS,  before that i register an account in web3.storag website,  and create a API Token for upload files.

then in jspaint
https://github.com/xinminsu/jspaint/commit/ebc5ac6a631d3b3af6833e4f9d245435ada8614f#diff-cccf2a6eadcc0c1cf6816c2f375ecdd20683df6688ac4690fc0d7b8c560daf27

line 162:
     ipcMain.on("upload-to-ipfs", async (event, fileName) => {
            const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDU4ZDc1ZjYzN2Y5NDc2YzVkQmU1OGIxNzEyN0Q1MGU0NDgxMzUzQjQiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NjE0MDU2Mzc2MDQsIm5hbWUiOiJ4aW5taW5zdSJ9.sb1ATMTwOtsquSn6kTWQylCRUZjVDWrGUq5o6sLHlis";
            const storage = new Web3Storage({ token });

            const files = await getFilesFromPath(fileName);
            const cid = await storage.put(files);
            console.log('Content added with CID:', cid);
      });

this way is not good, because other users use this function should update the "const token = user's own token", then they can check where the files uploaded, otherwise i will check for them.

after replan I want to reimplement the project in FVM smart contract , smart contract is open to public, so every one can pay some gas fee, then call the smart contract to upload files, also easy to check where their files is uploaded.

So I recreate a new project https://github.com/filecoin-project/devgrants/issues/1248.  plan to go deep into FVM smart contract to do much type of rich multimedia files save, load,  assemble, search...

thank you.

Best Regards.

________________________________

**Comment by ErinOCon** [comment]
Hi @xinminsu, thank you for your proposal. We will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
