### ISSUE TITLE
RPC Service for Filecoin

### ISSUE THREAD

**Issue by Alvis1998** [filecoin-project/devgrants#1249]
# Open Grant Proposal: `RPC Service for Filecoin`

**Name of Project: **Hamster

**Proposal Category:** `integration-adoption` 

**Proposer:** `lt-liam`

**(Optional) Technical Sponsor:** `Jenks Guo`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description
More and more developers are participating in the web3 world. Building a blockchain Dapp requires setting up node services or using public hosted endpoints , which sometimes requires pricey servers and blockchain node resources. Self-hosted servers could be expensive and take up to 6-12 months to build and scale to the production level that Dapp requires. The instability of self-built blockchain nodes will also be one of the team's costs. The operations & maintenance (O&M) issues such as data inconsistency, memory leaks, disk operations, etc. also haunt developers.

Based on a powerful technical architecture, Hamster can support developers to quickly create applications without the need for a large number of node operation and maintenance work. We are planning to build super nodes that support multiple chains and multiple networks. Super nodes ensure timely, consistent and stable data with high availability and scalability. We can make it easy for developers to access on-chain data and conduct on-chain transactions through our APIs. Developers enjoy an integrated Dapp dev and deployment experience by spinning up hosted nodes, deploying their services/site on Hamster infrastructure and using Hamster dev SDKs. 

This grant application is for Hamster to implement Filecoin Verifier Nodes and Filecoin Client Nodes and integrate with the Filecoin ecosystem.

## Value
Filecoin is the world's largest distributed data storage project, and we aim to provide developers with a better data storage bridge, so Filecoin is an important node we need to integrate. We allow developers to use it directly in our platform services without deploying their own Filecoin retrieval nodes.

It is a low-risk thing for us to build Filecoin retrieval nodes, but there are also some risks that make our implementation tortuous, such as how to quickly deploy Filecoin retrieval nodes, how to ensure the stability and security of Filecoin nodes, disk operations for Filecoin, it is however a valuable thing that worth doing.

## Deliverables
**A login page for developers, here we provide:**
Hamster node service platform
Hamster Operations Documentation
Hamster front-end source code
Hamster Filecoin one-click deployment toolkit source code

**The functions of the Hamster node service platform include:**
List of Blockchain nodes
Dapp management function
Dapp Dashboard
Filecoin node call statistics page
Filecoin API call GUI
Filecoin API documentation
Filecoin node monitoring

## Adoption & Expansion Plan
Currently, Hamster has about 1000 developers using our indexing node service that we developed for theGraph (testnet). The team members have a quite successful record of promoting Web3.0 service/product within Web3.0 communities. 

With the service we would like to develop for Filecoin, firstly we will iterate our product with our engineering know-how to be the “top” user experienced service/product, by keeping collecting feedback from the community.  Secondly, we're gonna promote it within and outside the Filecoin community in multiple ways, aiming to achieve a fast growing group, using our service.

## Development Roadmap

**Milestone 1   Time: 19.Dec.2022-12.Jan.2023**
Complete the functions of the Hamster node service platform, which is an important platform for developers to carry our Filecoin litenodes. It allows users to use Filecion's node services through the Filecoin node API interface.
1, Blockchain node list: You can view Filecoin nodes through the page, including node query, node current statistics and other functions
2, Dapp management function: provide users with the ability to create Dapps, delete Dapps, modify Dapp names, link Blockchain nodes to generate Filecoin node API links
3. Dapp Dashboard: The node information interface provided to the user, the request statistics page, and the request log statistics.
4, Hamster node service operation document: how to allow users to use the node service platform
We use vue.js + ts for the front end, rust language for the back end, OpenTelemetry for the monitoring service, and Mysql for the database.

Development Team:
1, 1 product manager
2, 1 front-end R&D engineer
3, 1 back-end R&D engineer
4, 1 UI designer
Cost required: $20,000

**Milestone 2  Time: 16,Jan.2023- 24.Feb.2023**
Complete Filecoin's litenodes deployment and fast node building tools
1. Filecoin one-click deployment script: scripts can be used to quickly build multi-node deployment.
2. Filecoin calls the proxy gateway: it allows users to access multiple File nodes through the gateway to maintain high availability and high scalability.
3. Filecoin API: Investigate FilecoinAPI and generate a Filecoin API that can be used by developers
4. Filecoin API Documentation: we will provide callable documents
We plan to use ansible language to build multi-node deployment scripts, or use rust language to write rapid deployment, which can make node deployment faster and more convenient, and the proxy gateway can achieve efficient scheduling under high load conditions. And generate the enhancement of Filecoin API, which can allow developers to operate and use more conveniently through Filecoin API.

Development team:
1, 1 product manager
2. One front-end R&D engineer
3. One back-end R&D engineer
4. One UI designer
5. One operation and maintenance development engineer
Cost required: $20,000

**Milestone 3 Time: 27.Feb.2023-31.March.2023**
High-availability maintenance and expansion functions for Filecoin nodes.
1. Filecoin API call GUI: Allow users to call Filecoin API from the interface for testing
2. Filecion node call statistics: It can provide user call statistics interface, so that users can know the call statistics of their own applications for business planning
3. Filecoin node monitoring: Build a Filecoin node monitoring program to ensure the health of filecoin nodes, and develop functions such as alarms to make nodes operate safely and effectively. We will develop the operation and maintenance monitoring function to ensure the stable operation of Filecoin nodes.

Development team:
1, 1 product manager
2. One front-end R&D engineer
3. One back-end R&D engineer
4. One UI designer
5. One operation and maintenance development engineer
Cost required: $20,000

## Total Budget Requested

The budget we need:
Part 1: 50,000 on manpower
Part 2: 10,000 for the cost of computing resources required by our nodes to deploy Filecoin 

## Maintenance and Upgrade Plans

It will be maintained by our Hamster team in the future

# Team

## Team Members

Nova CMO
Alvis  COO
Porsche CTO
Liam VP&Head of Tech
and + 20 Devs & 3 Marketing

## Team Member LinkedIn Profiles

Nova: https://www.linkedin.com/in/nova-wong-92b48359/ 
Alvis: https://www.linkedin.com/in/alvis-tsui-69952341/ 
Porsche: https://www.linkedin.com/in/porsche-shi-41832446/
Liam: https://www.linkedin.com/in/liam-liang-092950245/ 

## Team Website

https://hamsternet.io/

## Relevant Experience

Our team has been deeply involved in traditional Web2.0 fields for over 20 years, and has accumulated precipitation in the field of cloud native and cloud computing. We have profound experience in the operation, maintenance and deployment of large-scale projects. The core members of our R&D team have experience in deploying and hosting blockchain nodes, and have also conducted research and development of blockchain projects in Web3.0. We believe that the provision of nodes can better empower developers and lower the threshold for entering the filecoin world

## Team code repositories

https://github.com/hamster-shared 

# Additional Information
We heard several times from the community of Filecoin that a better RPC service solution is urgently needed, which is in the scope of our goal as well.

Filecoin is a super big ecosystem, and is one of the top projects in the space. We learnt about the open grants program from Jenks Guo.  And based on the information from the filecoin community, we feel quite excited to BUIDL such a service for Filecoin and in Filecoin.

**Comment by ErinOCon** [comment]
Hi @Alvis1998, thank you for your proposal and for your patience with our review. This grant is still under consideration. We expect to have a new update available soon.

**Comment by Alvis1998** [comment]
> Hi @Alvis1998, thank you for your proposal and for your patience with our review. This grant is still under consideration. We expect to have a new update available soon.

Hi dear @ErinOCon , is there any update regarding this proposal? Thank you！

**Comment by ErinOCon** [comment]
Hi @Alvis1998, thank you again for your patience during our review. Unfortunately, we will not be proceeding with a grant at this time. 

We are wishing you all the best as you continue to build!
