### ISSUE TITLE
Grant Application for Enlighten

### ISSUE THREAD

**Issue by bhirkoff** [filecoin-project/devgrants#1250]
### 1. What is your project, and what problem does it solve? (max 100 words)
People are often faced with inaccessibility to books, especially digital books. The need to register, login, access books based on geographical location, and lot more. 
Enlighten is basically the Amazon of the web3 space. Enlighten is a decentralized open library on IPFS where anyone can upload, read, and download books for free in the public domain, still maintaining the rules of copyright. 
These books are stored on IPFS. 

### 2. Project links
Link to Github repo: https://github.com/HeritageLabs/Enlighten 
Link to website: https://enlighten-gamma.vercel.app 
License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
Enlighten uses the NFT.Storage technology which is an open-source, decentralized data storage platform that enables users to securely store and manage books uploaded via Enlighten as non-fungible tokens (NFTs) on the InterPlanetary File System (IPFS).

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
No, It is not contributing to the upcoming FVM launch.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. We will begin by conducting a comprehensive market analysis to gain insights into user needs and preferences to create an effective product roadmap.  
2. We will use the resources provided by this grant to develop new features for our platform that are tailored towards meeting user demands, such as enhanced security measures, books categorization, and more intuitive navigation tools.  
3. We will also utilize funds from this grant to optimize existing functionalities of our platform so that they are easier for users to access and understand.  
4. Additionally, we plan on utilizing the resources provided by this grant to increase visibility of Enlighten, including through marketing campaigns and collaborations.        

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, I do agree t share reports as regards the progress of Enlighten once being funded, including every other relevant information.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes, my proposal does comply with the Community Code of Conduct.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
No, I have not submitted my project to relevant Protocol Labs prizes.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Name - Chukwuka Okorie 
Email – [chuksdav4@gmail.com](mailto:chuksdav4@gmail.com) 
Github – github.com/bhirkoff 
Role – Product Manager

Name - Aroyewon Tope
Email – [aroyewontope@gmail.com](mailto:aroyewontope@gmail.com) 
Github – github.com/temitope3665
Role – Frontend Developer

Name - Lukman Saheed
Email – [lukmansaheed79@gmail.com](mailto:lukmansaheed79@gmail.com) 
Github – github.com/hexdee
Role – Backend Developer

* How did you learn about our microgrant program?
I did receive an email about the microgrant requesting I join in. 
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
   Web3 Infinity Hackathon
  * Please link to your hackathon submission
  https://devpost.com/software/enlighten-t9exd0

**Comment by ErinOCon** [comment]
HI @bhirkoff, thank you for your proposal. We will not be proceeding with a grant at this time. Wishing you the best of luck as you continue to build!
