### ISSUE TITLE
Next Step Microgrant: <Coin Rise>

### ISSUE THREAD

**Issue by mourad96** [filecoin-project/devgrants#1254]
### 1. What is your project, and what problem does it solve? (max 100 words)
Coin Rise is a decentralized Crowdfunding platform where users can raise funds for projects without the presence of a third party. It's transparent for both the contributors and the project submitters.

### 2. Project links
  
Link to Github repo: https://github.com/coin-rise/coin-rise
Link to demo or website, if applicable: https://youtu.be/9w6S-J6DpH0
License:  MIT license

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
-ChainLink Keeper automates the funding process and the voting system
-Data storage of campaign details and request details via Web3 Storage ( IPFS + Filecoin )
-All smart contracts are deployed on Polygon Mumbai
###    b) Is this project contributing to the upcoming FVM launch? 
  yes
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
-We plan to implement on ramp feature on the platform. Where contributors can buy USDC directly from the platform using their credit card
-Users can vote to get their funds back if the project does not go according to their wishes.
-Make a community to approve submitted projects and filter spams where they can earn money from that

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://devpost.com/software/coin-rise
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
-Mourad Bouabdallah - Fullstack Web3 Developer - [www.linkedin.com/in/mourad-bouabdallah/](http://www.linkedin.com/in/mourad-bouabdallah/)
-Florian Meiswinkel - Smart Contracts Developer - [www.linkedin.com/in/florian-meiswinkel-33a727257/](http://www.linkedin.com/in/florian-meiswinkel-33a727257/)
-Wajih Jabeur - Front-end Developer - [www.linkedin.com/in/wajih-jabeur-506965144/](http://www.linkedin.com/in/wajih-jabeur-506965144/)
-Stephen Ayeomotor - UI/UX Designer - [www.linkedin.com/in/stephen-ayeomotor-19b474100/](http://www.linkedin.com/in/stephen-ayeomotor-19b474100/)
-Anupriya Lathey - Front-end Developer - [www.linkedin.com/in/anupriya-lathey-585071222/](http://www.linkedin.com/in/anupriya-lathey-585071222/)
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon: Hackathon
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) Chainlink Hackathon
  * Please link to your hackathon submission   https://devpost.com/software/coin-rise

**Comment by ErinOCon** [comment]
Hi @mourad96, thank you for your proposal. We will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
