### ISSUE TITLE
ARC Data wallet

### ISSUE THREAD

**Issue by dsrdrk11a** [filecoin-project/devgrants#1255]
# Open Grant Proposal: `FVM Tooling & Infrastructure`

**Name of Project: ARC Data Wallet**

**Proposal Category:** `app-dev`

**Proposer:** @dsrdrk11a

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?** Yes

# Project Description
Bela Supernova propose to develop a crypto wallet for the FEVM network, that will combine classic wallet functions for managing, sending and receiving assets as well as easy to use functionality for managing files stored in the Filecoin network. A new data wallet will become a client-end solution enabling independent users to use the Filecoin storage network as well as enabling developers to run their dApps in the FEVM network on a B2C basis, when users independently pay for their transactions in a dApp.
Currently there is no user transparent way to use FileCoin as a personal storage. There are third-party services that declare storage in FileCoin, but users do not handle FIL transactions and data privacy and manageability are at risk. Current methods of working with FIL limit the number of users to professionals and corporate solutions who can provide the necessary infrastructure and competencies.
The ARC data wallet will significantly decrease the competencies threshold for using the storage service and open an opportunity for non-experienced users to independently use the decentralized data storage system.

## Value
Key benefits the ARC data wallet will bring:
1.	High Filecoin storage availability for independent users;
2.	Stored data ownership guarantee;
3.	A client-end solution for all FEVM dApps that use FileCoin storage;
4.	Significant increase in user coverage by lowering the threshold of competencies for accessing the service.

## Deliverables

As a result of this project BSN will deliver:
1.	A working data wallet extension MVP that supports data storage management. The MVP will be tested under Chrome and Firefox browsers.
2.	An FVM smart contract for management of data stored in the FileCoin: methods for working with encryption keys, making and managing catalogues, storing files’ indexes.

![flDataWallet](https://user-images.githubusercontent.com/98888366/207639567-bd9fa90b-c76d-4b16-b93a-9bb96248aea0.png)

## Development Roadmap
Each milestone will be supported by a group of 1 PM, 4 developers and 1 QA with additional 1 PO and a UX designer on the 2nd milestone.

| Milestone | Time | Budget |
| ----- | ----------- | ------------- |
| 1. Development of a FEVM smart contract for managing stored data with the ARC data wallet extension. | 1,5 months | € 81 000 |
| 2. Design and development of the ARC data wallet extension. | 3 months | € 104 000 |

**Milestone 1. Development of a FEVM smart contract for managing stored data with the ARC data wallet extension**
1.	Development of methods for storing and managing encryption keys for stored data;
2.	Development of methods for making and managing catalogues structure;
3.	Development of methods for storing data indexes;
4.	Design and development of a CLI tool for testing the smart contract methods.

**Milestone 2. Design and development of the ARC data wallet extension**
1.	Developing functionality for adding and encrypting files;
2.	Developing functionality for saving files to IPFS (operational storage) and FileCoin (archive storage);
3.	Developing functionality to show catalogues structure and navigation;
4.	Developing functionality to delete files (from the extension);
5.	Developing functionality to show balance and transactions history;
6.	Developing functionality for sending transactions;
7.	UI/UX design;
8.	MVP release.

## Total Budget Requested

The total budget for MVP development - € 185 000

## Maintenance and Upgrade Plans

We have no plans on maintaining the ARC data wallet in this proposal.
The ARC data wallet functionality will be extended by the team in accordance with the functional development of FVM and FileCoin storage, but should be arranged at a later time under another application.

# Team

Bela Supernova is a member of the FVM Foundry Early Builders program with the [ipEHR project](https://github.com/bsn-si/IPEHR-gateway)

## Team Members

•	Sergey Cymbal, MBA, CEO at Bela Supernova d.o.o
•	Dmitrii Putilov, CTO at Bela Supernova d.o.o
•	Alexey Vexin, Blockchain Department Director at Bela Supernova d.o.o
•	Dmitrii Shevchenko, Techlead & full stack software developer at Bela Supernova d.o.o
•	Ilia Shavrin, Full stack software developer at Bela Supernova d.o.o
•	Anton Shramko, Full stack software developer at Bela Supernova d.o.o
•	Alexander Plekhanov, Middle Golang developer at Bela Supernova d.o.o
•	Valeriy Tetevin, Senior Golang developer at Bela Supernova d.o.o
•	Ksenia Baranova, QA Lead at Bela Supernova d.o.o
•	Anton Borisov, DevOps Engineer at Bela Supernova d.o.o

## Team Member LinkedIn Profiles

[Sergey Cymbal](https://www.linkedin.com/in/sergecymbal/)
[Dmitrii Putilov](https://www.linkedin.com/in/dmitri-p-96b0a140/)
[Alexey Vexin](https://www.linkedin.com/in/alexey-vexin-800a4068/)
[Ilia Shavrin](https://www.linkedin.com/in/ilia-shavrin-716552228/)
[Anton Shramko](https://www.linkedin.com/in/anton-shramko-25971b162/)
[Valeriy Tetevin](https://www.linkedin.com/in/sealtv/)
[Ksenia Baranova](https://www.linkedin.com/in/mayawotson/)
[Anton Borisov](https://www.linkedin.com/in/anton-borisov-17b80211b/)

## Team Website

https://www.bsn.si/

## Relevant Experience

Our team has extensive expertise on multiple levels starting from progressive vision all the way down to software and solution development. This blend of knowledge and skills ensure we tackle the most ambitious challenges and come up with commercially successful solutions in Healthcare and FinTech industries. Natural ability of some of the team member to navigate and predict future technological trends combined with technical experience and project management skills of other members translates into the clear roadmap.

Sergey Cymbal is an experienced executive, leader and visioner responsible for the most disruptive innovations initiatives across Oil/Gas, Utilities, and Telcos. Ex-member of national winter Olympics HQ, responsible for digitalisation, Smart grid evangelist. Blockchain early follower, participates in several crypto initiatives .

Dmitrii Putilov has over 17 years of experience leading the teams creating and maintaining high availability sites. His portfolio contains creation of the robee.io investment platform included in top500 in coinmarketcap.

Alexey Vexin is a product owner and project manager with 10+ years experience in managing complicated telecoms and IT projects in Telco, Utilities and Govermental sectors with deep focus on business process management. Led a dozen of federal scaled projects for IT systems implementation and industry scaled technology development, standardisation and implementation.

Dmitrii Shevchenko is is a TechLead engineer with 10+ years of experience in developing and integrating IT, networking, security and blockchain solutions. Involved in implementation of highly reliable industrial solutions and development of FinTech and DeFi applications.

Ilia Shavrin is a solution architect and full stack software developer with over 12 years of experience in high load enterprise applications. His most recent focus is on blockchain and creation of decentralised applications.

Anton Shramko is an experienced developer with ver 7 years of experience on various positions, including solution architect in Krypton. Anton active contributor to open source and blockchain communities, he is also a frequent speaker in DevCon conferences.

Alexander Plekhanov is fullstack software developer with over 5 years of experience including blockchain-based projects, enterprise solutions for fintech, call-centers, goverment services. Recent time mostly focuced on smart-contracts development.

Valeriy Tetevin is a programming engineer with over 8 years of experience in cloud-native applications. He also has strong knowledge of microservices arhechecture and back-end development for high-loaded applications.

Ksenia Baranova is an QA test engineer with over 5 years of experience. Ksenia has exceptional knowledge and skills in the field. She is highly refered within this team, as well as by her former teams.

Anton Borisov îs a DevOps Engineer with broad experience. For for over 15 years Anton was supporting, administering, and maintaining secure networks, servers and clusters. He also has verstile experience with CI/CD, IT Infrastructure Monitoring, and Kubernetes on-premise and in Cloud. One of the most recent projects Anton particapted in was building a first onchain casino.

## Team code repositories

- https://github.com/orgs/bsn-si/repositories
- https://github.com/ManageIQ/manageiq-providers-amazon/commits?author=aiperon
- https://github.com/ManageIQ/manageiq/commits/?author=aiperon
- https://github.com/friktor?tab=repositories
- https://github.com/dsputilov
- https://github.com/friktor
- https://github.com/aiperon
- https://github.com/1db1
- https://github.com/SealTV
- https://github.com/Fivehundredth

# Additional Information
If you have any questions please contact Alexey Vexin via [av@bsn.si](mailto:av@bsn.si)

**Comment by dsrdrk11a** [comment]
Dear, Sonia @realChainLife 
I want to inquire about the status of this application. We feel very enthusiastic about the ARC wallet and are looking forward to make a positive contribution with FVM and FIL. Is it possible for you to provide an update and a timeline for a decision?

**Comment by ErinOCon** [comment]
Hi @dsrdrk11a, I know it has been a considerable amount of time since we have provided an update for this proposal - thank you for all of your patience! In light of the macroeconomic climate, the review of our budget and priorities for the fiscal year has resulted in a longer evaluation period. 

Unfortunately, we will not be moving forward with a grant at this time. We are wishing you all the best as you continue to build!
