### ISSUE TITLE
Next Step Microgrant: An open-metaverse platform to build, host, explore

### ISSUE THREAD

**Issue by Developer-piyush** [filecoin-project/devgrants#1256]
### 1. What is your project, and what problem does it solve? (max 100 words)
At De3Verse, our vision is to build an open-metaverse platform where anyone can build, explore, meet friends, and enjoy/host events at the same time.
At De3Verse, we have lands which are owned by the users as NFT, owners can customize their land as per their own will, just like metaverse. Then we have central city which hosts clubs, DJ’s, movie theatre, streets, music, business headquarters.
We have functionality to host business headquarters in the central city which increased the brand awareness through tutorials etc.. inside the metaverse.
As per current situation, digital life have no 3d avatars and experience similar to real life while interacting with others. We are building social experience in the metaverse for the community and users that makes digital life feel more real.

De3Verse consists of (Refer to teaser video for more visual details):
•	Residential spaces
•	Commercial spaces
•	Resource Gathering or hunt games
>For residential spaces: we are building a map-based economy where users will be able to own a land through NFT access. Land will have functionality to build/customize house, private/public meet & display/showcase NFTs that users hold in their wallets.
>Commercial ecosystem is the central hub of de3verse ecosystem which is designed for events, clubs, users’ hangout, offices, DJs, and commercial exclusive headquarters for ecosystem brands/company.
>Resource gathering/hunting game ecosystem is designed to host regular giveaway events in a gaming fashion to keep users engaged. We have some more plans to build some cool games in integration with blockchain.

### 2. Project links
  
Live Testing Links with social profiles: 
•	Twitter: https://twitter.com/de3verse
•	Teaser: https://youtu.be/MqPyW2LrvFc 
•	Land Some live testing videos: https://www.loom.com/share/31af9a4a4a7c4010aaf738c16de687d6
•	To experience city, visit on our website
•	Discord: https://discord.gg/D3H8ySvxwe 
•	Website: https://de3verse.com/
•	Dummy Website:  https://de3meta.com/
•	Our minting website: https://mint.de3verse.com/ 
•	Our NFT collection: https://new.paras.id/collection/de3verse_deploy.near 

Check what users are saying:
•	https://twitter.com/De3Verse/status/1601452734993268737?s=20&t=hXx3MXW3pPKh_aqf9wmKPw
•	https://twitter.com/NFTus_ART/status/1601066358749679618?s=20&t=hXx3MXW3pPKh_aqf9wmKPw
•	https://twitter.com/De3Verse/status/1600818719223033856?s=20&t=hXx3MXW3pPKh_aqf9wmKPw
•	https://twitter.com/trevinvsnft/status/1600616555322437632?s=20&t=hXx3MXW3pPKh_aqf9wmKPw
•	https://twitter.com/DodgeHello/status/1600562301069053952?s=20&t=hXx3MXW3pPKh_aqf9wmKPw
•	More on our profile: https://twitter.com/de3verse

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
We are using https://nft.storage/ to host all the land co-ordinates NFTs which are being used to define co-ordinates of land and ownership of land in metaverse . We are also using nft.storage api to fetch the details of land NFTs in real time.
IPFS Link: https://bafybeihh7ejsmmuljzy6vnxqfzh2t7kjtmlefuuzkwpdn2a4tiezv3whdm.ipfs.nftstorage.link/
Few NFTs  link:  https://bafybeihh7ejsmmuljzy6vnxqfzh2t7kjtmlefuuzkwpdn2a4tiezv3whdm.ipfs.nftstorage.link/1.json , https://bafybeihh7ejsmmuljzy6vnxqfzh2t7kjtmlefuuzkwpdn2a4tiezv3whdm.ipfs.nftstorage.link/1.png

We minted land NFTs few days back through whitelist and free model which rewarded the active members, these land NFTs define co-ordinates of the land in their json file, which is being used to identify owners of land through end-to-end react blockchain api model:
Minting website: https://mint.de3verse.com/

**High Level Diagram**
![](https://bafybeihvrvwduvgc5xlhhwrxbmmv2t3cn6kkjdps6qmldedfxsmbw3ayou.ipfs.nftstorage.link/1.png)

**Some Live visuals**
![](https://bafybeihvrvwduvgc5xlhhwrxbmmv2t3cn6kkjdps6qmldedfxsmbw3ayou.ipfs.nftstorage.link/2.jpg)
![](https://bafybeihvrvwduvgc5xlhhwrxbmmv2t3cn6kkjdps6qmldedfxsmbw3ayou.ipfs.nftstorage.link/1.jpg)
![](https://bafybeihvrvwduvgc5xlhhwrxbmmv2t3cn6kkjdps6qmldedfxsmbw3ayou.ipfs.nftstorage.link/3.jpg)
![](https://bafybeihvrvwduvgc5xlhhwrxbmmv2t3cn6kkjdps6qmldedfxsmbw3ayou.ipfs.nftstorage.link/4.jpg)

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will use the grant amount to improve user experience and highlight use of decentralized and immutable tech stack that is being integrated in our metaverse ecosystem.
We are looking forward to expand towards our vision to build open metaverse, de3verse is just a first step towards this vision: the grant amount will be used to brainstorm more ideas and implement the same.
We are looking forward to build exclusive filecoin 3D headquarter in our central city beside other brands which are already there: this headquarter will showcase power and use cases of decentralized storage and its advantage over centralized storage.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
Nope, we started this project on our own with a mission to build open-metaverse.
  
### Additional questions:
* https://github.com/Developer-piyush
* Twitter, our twitter: https://twitter.com/de3verse
* If your project was created as part of an event or hackathon: NO

**Comment by ErinOCon** [comment]
Hi @Developer-piyush, thank you for your proposal! Can you confirm the applicable repo for this project? Also, can you confirm if this work is open source (see our policy [here](https://github.com/filecoin-project/devgrants/blob/master/open-source-policy.md))?

**Comment by Developer-piyush** [comment]
> Hi @Developer-piyush, thank you for your proposal! Can you confirm the applicable repo for this project? Also, can you confirm if this work is open source (see our policy [here](https://github.com/filecoin-project/devgrants/blob/master/open-source-policy.md))?

Thank you @ErinOCon for taking a time to review our proposal.
We have already released the first version of our metaverse and is getting used by 200+ real active users so far.
Yes the architecture level of the code will be open sourced, sharing links below:
https://github.com/Developer-piyush/de3_virtual_main
https://github.com/Developer-piyush/de3_mint_main

Looking forward to your reply/any more concern about our proposal.

Thank you

**Comment by Developer-piyush** [comment]
@ErinOCon is there any further update on this??

**Comment by ErinOCon** [comment]
Hi @Developer-piyush, thank you for your patience with our review. We will not be moving forward with a grant at this time, but would be interested to learn more as building progresses! We recommend checking out a [hackathon](https://hackathons.filecoin.io/) or, if you plan to incorporate FVM in the near future, opportunities with [Space Warp](https://spacewarp.fvm.dev/).

Wishing you all the best as you continue to build!
