### ISSUE TITLE
Unity Filecoin Integration Plugin

### ISSUE THREAD

**Issue by ericvanderwal** [filecoin-project/devgrants#1259]
# Open Grant Proposal: `Unity Game Engine Support Plugin`

**Name of Project:**

**Proposal Category:**  `integration-adoption`

**Proposer:** `ericvanderwal`

**(Optional) Technical Sponsor:** `DeveloperAlly`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:**  Yes

# Project Description

Unity Game Engine is the world's most popular game engine and has a market share of over 50% as of 2020. Unity Game Engine publishes games to Steam, iOS, PCs, Macs, Android, WebGL, and consoles.

We will bring a simple-to-use plugin (asset) to the Unity Asset Store for free (as well as release the entire code base under a dual MIT and APACHE2 License) that brings access to IPFS technology on any gaming platform.

In fact, the first phase of the project has already been completed and showcased in both talks (and applications) at Blockjam Hackathon 2022, Moralis x Filecoin Hackathon, and India's first Blockchain Gaming Conference. More educational pieces are planned for 2023 and beyond.

https://globalblockjam.com/talks.html
https://moralis.io/filecoin-hackathon/
https://events.godwoken.com/

Integrations will include support via code in C#, custom Unity Engine Editors, and Unity Game Engine's most popular visual scripting solution (Playmaker).

## Value

-   Access to filecoin/IPFS through the world's most popular game engine and the largest cohort of game developers ever.
-   Support for PC, iOS, Android, WebGL, and all major consoles through a single code base
-   Code released entirely open source, free to use, mix and modify
-   Ease of use from both native coding in C# but also visual scripting solutions for artists and creatives

**Challenges:**

-   Maintaining backward compatibility for older versions of the Unity Game Engine
-   Support for both multi-threaded and non-multithreaded devices in a single SDK

## Deliverables

-   Both editor and runtime integration, where appropriate
-   Support for PC, iOS, Android, WebGL, and all major consoles
-   Helper and sample functions to ease the development process, such as taking screenshots and uploading IPFS pinning services
- Built-in easy low/ no code editor windows
-   Support for NFT.Storage and Web3.Storage data pinning and retrieval
-   Gateway support for private and public gateways such as Cloudflare, Pinata, Infura, Web3.Storage, NFT.Storage. This includes read and write, authentication, various resolution styles, and real-time switching to create a more secure solution.
-   Learning materials, clear documentation for ease of use and sample projects will be prioritized.

## Development Roadmap

  

Development for the project will take an agile approach which always leave it in a working state. Phase 1 (MVP) stage has been launched and is being used in production projects. Phases 2 - 4 will continue similarly. 16 weeks total is allocated to development. With additional time for post-launch support and bug and Unity Engine Asset Store Maintence

  

**Phase 1 - MVP**

-   Project available on GitHub
-   MVP Project release
-   nft.storage integration
-   threaded and multi-threaded support platform support
	- PC, iOS, Android, WebGL, major consoles (Playstation, Nintendo, Xbox)
-   Simple sample projects for screen captures and data uploading
-   Helper functions to deal with image capture and management within Unity

Time: 4 weeks
Cost: 20,000 USD
  

**Phase 2 - Gateway Phase**

-   Improvement of gateways support
	-   Support for authenticated (private) gateways
	-   Gateway support for public gateways
	-   Editor management of gateways with no code solutions
-   Helper function to support JSON and bitarray data
-   Helper functions to upload both raw data and NFT metadata conforming to commonly used standards
-   The first version of the documentation to ease the onboarding process

Time: 4 weeks
Cost: 20,000 USD

  

**Phase 3 - Pinning Phase**

-   Support for alternative pinning services
	-   Web.Storage
	-   Pinata
	-	 NFT.Storage
-   Visual scripting integrations
	-   Playmaker (Unity's most popular visual scripting solution)

Time: 4 weeks
Cost: 20,000 USD

  

**Phase 4 - Final Release**

-   Submit to Unity Asset Store (always available for free)
-   Direct editor support through custom unity editors
-   Completion of documentation
-   Video demonstrations to support other learning styles

Time: 4 weeks
Cost: 20,000 USD

  

**Phase 5 - Post Launch Support**

-   Bug removal and community support as necessary via the Unity Forums and discord as required

Time: Ongoing
Cost: 10,000 USD
## Total Budget Requested

$90,000 USD over 16 weeks for development costs, documentation, and recorded video series.

## Maintenance and Upgrade Plans

Based on the market trends and requirements, we will regularly update the platform along the maintenance for a minimum period of 4 years. This includes each major LTS release of the Unity Game Engine

# Team

## Team Members

Lead Developer - Eric Vander Wal

Eric has over 20 years of combined web & game development, management, and software engineering experience with a focus on easy-to-use technology and content management systems. This led to his focus on the C# Microsoft .Net ecosystem, Rust, Javascript, and Blockchain! 

He is the former Director of Developer Relations of the Nervos Blockchain and current co-founder of Godwoken Game+ Blockchain.

## Team Member LinkedIn Profiles

Eric Vander Wal: https://www.linkedin.com/in/eric-vander-wal/

## Team Website

No website currently. Documentation specific for this project will be launched on Gitbook.

## Relevant Experience

Eric Vander Wal is a former professional game developer who worked on integrations and advocacy for Unity Game Engines' most popular third-party plugin, Playmaker. He has over 20 years of development experience, including a lead technical position in the blockchain space. He has produced more than a dozen integrations for the Unity Game Engine to date.

## Team code repositories

Current code repository but will be moved to a more IPFS agnostic one in phase 2: https://github.com/ericvanderwal/NFTStorageUnitySDK

# Additional Information

I heard about the open grants program while teaching online classes on how to use IPFS within the Unity Game Engine at several events. I can be reached at tcmeric@gmail.com or on discord tcmeric#7727

**Comment by ErinOCon** [comment]
Hi @ericvanderwal, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
