### ISSUE TITLE
Next Step Microgrant: vStorage - decentralised versioning Storage

### ISSUE THREAD

**Issue by VlodkoMr** [filecoin-project/devgrants#1263]
### 1. What is your project, and what problem does it solve? (max 100 words)
Store and manage your files and folders, structure IPFS content and share important information using Filecoin with great and simple user interface. We develop smart-contract that allow create any files/directories structure and provide the best user experience for Filecoin. User can create directories, sub-directories, upload/download files (we use NFT.storage service), mark files and directories as favorite. Also we provide files versioning - when you upload the same filename to any directory, we will store next file version with access to previous versions.

### 2. Project links
  
Link to Github repo: https://github.com/VlodkoMr/v-storage
Link to demo or website: https://v-storage.atomic-lab.io/
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
We create solidity smart-contract and upload to Filecoin Wallaby network. This smart-contract manage files and directories structure, favorite lists and versioning. For frontend we use react with wagmi and wallet connector that allow to support multiple wallets. When user upload new files we use NFT.storage service to upload all files into IPFS and then update data in our smart-contract. Also user can edit and remove files, directories, download files and view favorites. For future updates each user will be able to set own NFT.storage API Key (in browser local storage) and upload content to own account.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
Yes.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Current project version is working prototype with main logic in smart-contract and frontend. With this grant we will be able to complete development: implement favorite list, edit files and directories, allow users to set NFT.storage API key to use their own account, move files between folders and complete rest of frontend pages. 

For now we completed main parts for working prototype: connect wallet, create directories and sub-directories, open all created directories, upload files, see version history (if uploaded few file versions), download files from IPFS, remove files and directories.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, I agree.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
No
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
>> Volodymyr, vlodkow@gmail.com, https://github.com/VlodkoMr, CEO and developer.

* How did you learn about our microgrant program?
>> From email newsletter

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
>> No, developed from scratch for Microgrant.

**Comment by ErinOCon** [comment]
Hi @VlodkoMr, thank you for your proposal and for all of your patience with our unexpectedly long review process. We will not be moving forward with a grant at this time, but are wishing you all the best as you continue to build. 

Thank you again for your interest in our grants program!
