### ISSUE TITLE
Next Step Microgrant: Cyclimate

### ISSUE THREAD

**Issue by salviega** [filecoin-project/devgrants#1264]
### 1. What is your project, and what problem does it solve? (max 100 words)

Cyclimate is a tool that allows you to calculate carbon footprint in cities while promoting and rewarding healthy practices such as cycling; with IoT technology we'll be able to measure the pulse of carbon on the planet. We used; IPFS, WEb3.storage, Estuary

### 2. Project links
  
Link to Github repo: https://github.com/salviega/cyclimate-frontend-react
Link to demo or website, if applicable: https://calm-surf-6459.on.fleek.co/
License: GPL
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
Filecoin (Stuary): 
  * IPFS storage of sensor CO2 readings, IPFS storage of native token redemption.
  * https://github.com/Oriojas/skywood_urban.git
 Filecoin (Fleek):
 * Deployment on IPFS of the app.
 * https://calm-surf-6459.on.fleek.co/
Filecoin (web3Storage):
* SDK for storage of the image and metadata of the NFT of the benefits.
* https://github.com/salviega/cyclimate-frontend-react/blob/main/src/middleware/web3Storage.js
Filecoin (pinata.cloud):
* Storage of the image and metadata of the NFTs of the markertplace.
* https://gateway.pinata.cloud/ipfs/QmQzV6R7PnfJFXtg2szTwfpT7NpSAoDH6PjUpTr75HPZNP/

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)

No

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

 * Hardware design (upgrade CO2 sensors).
 * GPS hardware.
 * Deploy MVP on FVM.
 * Developer payment.
 * Refactor coding.
 * Pay Chainlink services: ANY APIs.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, we are agree.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes, we readed the code of conduct.

### 7. Links and submissions
If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* https://devpost.com/software/cyclimate
  
### Additional questions:
John Tejanda:
 * rol: Product management 
 * email: jhontejada95@gmail.com
 * github: https://github.com/jhontejada95
 
Oscar Riojas:
 * rol: Data Science
 * email: oscarriojas@gmail.com
 * github:  https://github.com/Oriojas

Santiago VIana;
* rol:  Frontend Developer
* email: salviega6@gmail.com
* github: https://github.com/salviega

Felipe Marin:
* rol: Backend Developer
* email: luisf.maring0910@gmail.com
* github: https://github.com/LuisFelipe09

How did you learn about our microgrant program?

* Yes, after of Chainlink Hackathon Fall 2022

If your project was created as part of an event or hackathon:
 
* ETHGlobal: https://ethglobal.com/showcase/skywood-mo3fy
 Chainlink Hackathon Fall 2022: https://devpost.com/software/cyclimate

**Comment by ErinOCon** [comment]
Hi @salviega, thank you for your proposal. This microgrant has been approved! We will send an email to confirm payment details. Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). 

Please let us know if you have any questions!
