### ISSUE TITLE
Next Step Microgrant: RugHalt

### ISSUE THREAD

**Issue by AyyMaaz** [filecoin-project/devgrants#1265]
### 1. What is your project, and what problem does it solve? (max 100 words)

Rughalt is a DAO that minimizes the amount of rugs in the NFT space where the nft founders can dox themselves and the community can vote as to whether a project is a slow rug / straight up rug incase it is rugged the founders identity would get reveal by automation. If everything is fine its just sored in the blockchain. We would like to increase the security of the space, because right now everyone sees it as a scam.
Built with Ipfs,Filecoin.

### 2. Project links
  
Link to Github repo: https://github.com/AyyMaaz/RugHalt
Link to demo : https://rughalt.netlify.app/

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

All the users and projects data is being stored in the ipfs..

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

RugHalt is functional, but it is far from being production ready that's true you can say it's the first phase of the project. There are numerous things to be done like upgradation optimizing contract, test coverage, bug fixes, audits etc. before it would go live. I also have a list of some professional level missing features that I would implement in future: 1.Real world Data feeds of Nft project 3.Rather giving the specific code to the project we will using erc1115 token in the future so it could go better. 2.There is no functionality that stops someone from fake doxing themselves .Anyone could submit the fake identity like should also think about this situation. 3.We do have to figure out the security behind this .We could add verification of both the face + the ID .Maybe some discord control as well. 4.Currently the dapp is deployed to mumbai and goerli testnet only. We will make it on different chains. 5.We will also make it a perfect Nft MakretPlace like opensea . So you dont have to go on other marketplace. RugHalt is gonna be all in one. 6.Launching the Rughalt token in the future. 7.More..

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

yes sure

  
### 6. Does your proposal comply with our Community Code of Conduct?

yeh it does

### 7. Links and submissions

* WINNER Filecoin - Runners up - $11,000
  
### Additional questions:

* Name : Maaz Imran , email : maazweb3@gmail.com , Github : https://github.com/AyyMaaz/  , Role : Solo Developer and designer
* I received an email from filcoin..Then i do a research about it.
* Yes
* ChainLink Hackathon 2022
* https://devpost.com/software/rughalt-ekp42b

**Comment by ErinOCon** [comment]
Hi @AyyMaaz, thank you for your proposal. We will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
