### ISSUE TITLE
Next Step Microgrant: Project Shale

### ISSUE THREAD

**Issue by renning22** [filecoin-project/devgrants#1266]
### 1. What is your project, and what problem does it solve? (max 100 words)

**Shale** is distributed compute on Filecoin.

Public user will be able to rent computing instances from Storage Providers and access their sealed data (Filecoin+ storage deals) via local network.

The first goal of Shale is attracting AI companies/researchers to utilize the cheap GPUs resources in storage provider network and consume the big data in storage deals (300+ PiB).

Early use cases include fine-tuning public deep learning models (NLP, AIGC) from [huggingface.co](https://huggingface.co/) against various public datasets on Filecoin network.

Shale consists of a layer-2 marketplace on FEVM and offline protocols & SDKs.

- The marketplace prototype has been demonstrated at FVM Foundry F1.
- The SDK prototype has been demonstrated at HACK FEVM.

### 2. Project links
  
Link to Github repo: https://github.com/renning22/shale
Link to demo or website, if applicable: https://shale.finae.io/
License: APACHE2
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

Shale consists of a layer-2 marketplace on FEVM and offline protocols & SDKs.

[Design doc](https://github.com/renning22/shale#readme)

![image](https://user-images.githubusercontent.com/4597657/208069811-3a581f20-05f7-4b03-a800-b944b9f190df.png)

Screenshots:

<img width="1315" alt="shale_1" src="https://user-images.githubusercontent.com/4597657/208286688-6ca43d6f-40e9-4484-bdf2-748f5e4636d5.PNG">
<img width="1340" alt="shale_3" src="https://user-images.githubusercontent.com/4597657/208286767-24af6e5e-8bdc-48c1-bacc-3613bb3147e5.png">
<img width="1295" alt="shale_2" src="https://user-images.githubusercontent.com/4597657/208286692-6a73d68d-4897-4fc7-8142-275e9ced9df9.PNG">

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
Yes.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. Hire a full-time developer continuing marketplace and SDKs (we are part-time now) 
2. Deliver an end-to-end (beta) product in Feb 2023 when FEVM is launched in Filecoin mainnet.
3. Demos & funds raising from public VCs.
4. Business development for users of AI companies, academies and open-source communities.
5. TBD: Use case expansion and alpha version around Mid 2023.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.

### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
Started at HACK FEVM (NOVEMBER 18 — 20, 2022).
https://ethglobal.com/showcase/shale-anbpo
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  * Ning Ren, renning22@gmail.com, renning22, Tech Lead & ML Engineer
  * Lhd Boy, hongde.li@chainpion.com, lhdboy, Blockchain Engineer
  * Titian Xie, titantse@gmail.com, xtt129, Business Development Manager
* How did you learn about our microgrant program?
  * FVM Foundry F1 
* If your project was created as part of an event or hackathon:
  * ETHGlobal HACK FEVM (NOVEMBER 18 — 20, 2022)
  * https://ethglobal.com/showcase/shale-anbpo

**Comment by ErinOCon** [comment]
Hi @renning22, this microgrant has been approved! We will send an email to confirm payment details.

**Comment by renning22** [comment]
Thank you so much, Erin!! 
Your support is significant to Project Shale!

**Comment by ErinOCon** [comment]
HI @renning22, can you provide an update on your project progress? Below is a current list of what we look for when determining if a FVM microgrant project is complete:

- A fully working user-facing demo with nice UX that anyone can easily use.
- A dapp deployed to a Filecoin testnet like [Calibration testnet](https://docs.filecoin.io/networks/calibration/details/) so that we can see all the functionality working in a demo, and will be deployed to Filecoin mainnet in a production-ready state on project completion.
- Interesting use of Filecoin’s EVM, especially with respect to what’s unique to Filecoin (for example, via exploration of FVM use cases or the Filecoin Solidity API (see https://github.com/filecoin-project/community/discussions/585#resources, or [Bacalhau x FVM](https://github.com/bacalhau-project/lilypad), etc.)

Please be in touch with any questions!

**Comment by renning22** [comment]
Hi @ErinOCon, sorry for the late reply.
We took a step back and launched https://shaleprotocol.com/ as a milestone. FVM mainnet is still on our roadmap, but we pushed it to a later stage where we have some user basis.

**Comment by ErinOCon** [comment]
Hi @renning22, thank you for the update! Do you have an anticipated timeline for the remainder of the grant? 

@eshon

**Comment by renning22** [comment]
Let's see if the current stage goes well, we may revisit it in ~6 months.
Thanks you so much for your help, @ErinOCon!


> Hi @renning22, thank you for the update! Do you have an anticipated timeline for the remainder of the grant?
> 
> @eshon

**Comment by trruckerfling** [comment]
hey @renning22 i saw shaleprotocol being used at hackfs, i worked with karen to add it in as a tool that hackers could use! what steps are you left with to complete this grant? I think its just demos now.

**Comment by ErinOCon** [comment]
Hi @renning22, can you confirm the remaining steps for this project? It's important that an end date is established for this project.

**Comment by ErinOCon** [comment]
@renning22, following up on the request above request.

**Comment by ErinOCon** [comment]
Hi @renning22, we have not heard from your team and have resolved this issue. 

Please contact grants@fil.org with any questions.

**Comment by renning22** [comment]
Hi @ErinOCon, sorry for very slow response. we are still work on it and will give you an update soon.
