### ISSUE TITLE
Open Grant Proposal: IPFSum

### ISSUE THREAD

**Issue by BaranBayden** [filecoin-project/devgrants#1269]
# Open Grant Proposal: IPFSum

**Name of Project:** IPFSum

**Proposal Category:**  `app-dev`

**Proposer:** @BaranBayden

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes, GNU General Public License v3.0

# Project Description

IPFSum is accounting software integrated with decentralized storage. We aim to develop a software that can be used by Freelancers and SMEs.

We aim to develop Cash Entry-Exit tracking, Stock Tracking, Sales and Purchasing tracking, an invoice module and a small CRM in it.

We plan to offer two different usage models, On-Prem and SaaS. In On-Prem, the user will be able to install the open source project published on Github on their own system and use it unlimitedly. Users who do not want to deal with this will also be able to use IPFSum with our SaaS service for a small fee.

IPFSum works integrated with IPFS. Generated invoices are stored in IPFS and the invoiced person can verify documents with CID from the IPFSum login screen:

<img width="1276" alt="Ekran Resmi 2022-12-16 22 07 00" src="https://user-images.githubusercontent.com/35538702/208170865-115b900a-1881-4317-9be6-88bfd377f43f.png">

<img width="1297" alt="Ekran Resmi 2022-12-16 22 07 34" src="https://user-images.githubusercontent.com/35538702/208170930-05ba10cc-f322-4e1c-9233-13e2c5c1c6f3.png">

Also, screenshot of in-platform invoice control section:

<img width="1743" alt="Ekran Resmi 2022-12-16 23 36 13" src="https://user-images.githubusercontent.com/35538702/208184787-b49387f1-5c28-4938-839d-4994c0cfc459.png">

In addition, we will offer the customer the opportunity to use OrbitDB alongside PostgreSQL and MySQL. The reason why we do not require OrbitDB is because the audit report has not been created yet.

The user will provide full integration by selecting the IPFS pinning service on the setup screen.

There is also a demo to experience the accounting portal:

https://ipfsum.com
E-mail: demo@demo.com
Password: Demo1234*

## Value

IPFSum is a project that integrates IPFS technology into real life and people at all levels of society. So, it is a great opportunity to introduce IPFS technology even to small businesses.

However, creating false documents can be avoided with the CID control module. A customer of a company using IPFSum will have the opportunity to verify their invoice and other valuable documents. As a result, we position IPFS as a notary-like verification tool.

## Deliverables

At the end of the project, we will have a Web Application, an IOS Application, an Android Application, and a Desktop Application.

Respectively:
Web Application and Backend development and release
Developed and published SaaS model on ipfsum.com
Development and publishing of Android and IOS applications
Release on Google Play and App Store
Desktop application development and release

**Basic App Features**
Database and created files will be stored in IPFS in selected pinning service.

Customers can be added to the CRM module and customer relations can be controlled from there.

With the inventory module, warehouses can be controlled and entry and exit records can be made. In addition, barcodes can be created per product.

With the purchasing module, the inputs and costs of the products purchased to the company will be recorded. A product entered in the purchasing module can also be automatically added to the stock module.

With the sales module, sales transactions can be controlled, entries can be recorded in the company cash register and invoices can be created. This invoice can be saved in IPFS. In addition, the added sales and the products sold from the stock module will be reduced automatically.

With the Bank/Cash module, entries and exits to bank accounts will be displayed, and additional entries or exits can be added if necessary.
  
Users will be able to control IPFSum from their mobile phones, if they wish, thanks to the mobile application. For this, we plan to publish two different applications for On-Prem and Cloud in mobile application markets. On-Prem users can access the mobile application by entering the Endpoint URLs on their first login.

## Development Roadmap

***Milestone 1**

Budget: $30000
Estimated Time: 3 weeks

|   | Milestone Steps |
| ------------- | ------------- |
| [x]  | Creating and publishing the web app  |
| [x]  | Authentication with E-Mail and Password  |
| [x]  | DB Table Customer Module  |
| [x]  | Product table in DB  |
| [x]  | CRUD of Invoice  |
| [x]  | Invoice data to PDF  |
| [x]  | List, create and edit ability of Products  |
| [x]  | List, create and edit ability of Customers  |
| [x]  | List, create and edit ability of Invoices  |
| [x]  | Custom domain for the web app |
| [ ] | Tax Regulation Consulting Service for US, EU and Turkey |
| [x] | Generating relationship tree for tables |
| [ ] | CRM Module included customer table |
| [ ] | Leads Table for CRM |
| [ ] | Kanban page for Leads |
| [x] | Inventory table in DB |
| [x] | Inventory control page |
| [ ] | Inventory relationship with other tables |

The biggest expense here is the fee to be paid to the tax and regulation consultant. I can provide more information on this in a DM. 

If the proposal is approved, 1 UX Designer and 2 Developers will participate in the project in this phase.

***Milestone 2**

Budget: $15000
Estimated Time: 3-4 weeks

|   | Milestone Steps |
| ------------- | ------------- |
| []  | Integration infrastructure with Web3Storage  |
| []  | OrbitDB integration  |
| []  | Uploading module for generated invoices to IPFS via Web3Storage  |
| []  | Development of desktop applications. It will be connected to the backend developed in Milestone 1 via API. We plan to develop with Electron + React Native.  |

***Milestone 3**

Budget: $15000
Estimated Time: 3-4 weeks

|   | Milestone Steps |
| ------------- | ------------- |
| []  | Creating both the IOS and Android apps  |
| []  | Both mobile apps will be published in app stores.  |
| []  | Ultimate UI design process for all platforms  |
| []  | Creation of a detailed Readme and also knowledgebase creation.  |

## Total Budget Requested

We are asking for a total budget of $60,000.

We will give the majority of the budget to our new teammates.
In addition, there is the fee for the tools we will use while developing, and the publishing fee for the mobile application markets.
Finally, we have to work with a tax consultant while developing this application because we want to develop a project that complies with the regulations.

## Maintenance and Upgrade Plans

I said we will also release a SaaS platform, we may have to deal with that at first.

But after that, we can also add No-Code builder module. In this way, we address both enterprise-level companies and enable users to easily implement custom implementations.

Platforms such as Quickbooks have accountant training and certification programs. We would like to create such a certification program for our own product.

# Team

## Team Members

Baran Bayden - https://github.com/BaranBayden - baran@baydenteknoloji.com and bayden_b1@denison.edu 

Negotiations continue with a few people from my company to be added to the team.

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/baran-bayden-aa791373/

##Team code repositories

https://github.com/BaranBayden/IPFSum

## Relevant Experience

My company is the solution and implementation partner of Microsoft Dynamics in Turkey. Therefore, I am familiar with the structures of ERP and company applications such as this. Dynamics mostly appeals to enterprise level companies, but I would love to open source this solution to SMEs or freelancers who come to me and ask for an accounting solution.

**Comment by BaranBayden** [comment]
Update: The amount requested has been updated due to the reduction in Tax Advisor Fee and employee cost (the subsidiary company is entitled to tax exemption under R&D by the government). You can contact us for detailed information on the subject.

The milestone has been updated as the development of the inventory module has ended.

Also, it was forgotten to include the contact e-mail in the application document. This information has also been added.

**Comment by ErinOCon** [comment]
Hi @BaranBayden, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time, but are wishing you all the best as you continue to build!

Thank you again for your interest in our grants program.
