### ISSUE TITLE
DAO Enabled Research Paper Submission

### ISSUE THREAD

**Issue by ARUNMANNURU** [filecoin-project/devgrants#1271]
### 1. What is your project, and what problem does it solve? (max 100 words)

DAO enabled research paper submission helps community to review and provide their feedback. Based on number of votes they can either request further enhancements or approve submission.  

### 2. Project links
  
<img width="1323" alt="Screen Shot 2022-12-16 at 9 43 30 PM" src="https://user-images.githubusercontent.com/19398870/208222186-c5386d14-837e-45f2-8dde-1e8ca0328ee0.png">

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

- I will be using IPFS to store the research paper. 
- Ethereum to deploy and run the smart contracts for DAO. 
- React JS to build UI and access smart contracts. 

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)

No
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- Will build the prototype, based on inputs I can start enhancing the prototype. 
- Once, this prototype is built. I will do some research on how to issue NFT upon paper submission. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions

Not yet.
  
### Additional questions:

- Arun Mannuru -  Full Stack Developer - mannuruarun@outlook.com , https://github.com/ARUNMANNURU
- Recently attended dWEB conference at California. 
- Nope

**Comment by ErinOCon** [comment]
HI @ARUNMANNURU, thank you for your proposal. We will not be proceeding with a grant at this time, but would recommend checking out [our hackathons](https://hackathons.filecoin.io/) to continue building progress!
