### ISSUE TITLE
Publishing Books as NFT's

### ISSUE THREAD

**Issue by ARUNMANNURU** [filecoin-project/devgrants#1272]
# Open Grant Proposal: `NFT Enabled Book Publishing`

**Name of Project:  Publishing Books as NFT's**

**Proposal Category:** `app-dev`, `research`

**Proposer:** `ARUNMANNURU`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Please respond with either "Yes" 

# Project Description

- I would like to build a marketplace for authors to publish their books as NFT's
- This helps authors to monetize their work.   

## Value

- Book publishers can monetize their work.
- Will be utilizing IPFS as underlying file system to store the books.

## Deliverables

<img width="1085" alt="Screen Shot 2022-12-16 at 10 13 05 PM" src="https://user-images.githubusercontent.com/19398870/208224308-2c23d8c7-bdbe-40ac-aa90-6a68f092c61e.png">

## Development Roadmap

** MileStone 1 **

# Author Functional Flow:

1. Author can mint NFT collection.
2. Publish book collections.
3. Generate the IPFS token for the file/book.

# Buyer Functional Flow:

1. Search for specific author collections.
2. See books catalog.  

## Development Roadmap

# Milestone 1 ( MVP )

1. Connecting to Wallet, and Showing all book collections in marketplace. 15 days Part Time $5000.
2. Author functionality: Author can able to upload the book with meta data details. 30 days Part time. $10000.
3. Buyer functionality: Buyer can able to buy book after transferring funds. 30 days. Part time. $10000.

## Total Budget Requested

$25000.

## Maintenance and Upgrade Plans

Address issues and enhance features based on the feedback.

## Team Members

Arun Mannuru

## Team Website

N/A

## Relevant Experience

Full Stack Developer with 7+ years of hands on experience. 

## Team code repositories

N/A

# Additional Information

- Attended dWEB 2022 conference at California.
- Arun Mannuru, mannuruarun@outlook.com.
-

**Comment by ErinOCon** [comment]
Hi @ARUNMANNURU, thank you for your proposal. We will not be moving forward with a grant for the outlined project, but please feel welcome to check out our [microgrants program](https://github.com/filecoin-project/devgrants/blob/master/microgrants/microgrants.md). 

Wishing you the best as you continue to build!
