### ISSUE TITLE
Next Step Microgrant: Migrate Wiki-IPFS to FEVM

### ISSUE THREAD

**Issue by 70nyIT** [filecoin-project/devgrants#1274]
### 1. What is your project, and what problem does it solve? (max 100 words)
Index files on IPFS connecting their sha-256 hash to their public CIDs 

### 2. Project links
  
Link to Github repo: https://github.com/odfdata/wiki-ipfs
License: MIT

Project is fully working (the demo video shows how it works). Due to cost management currently the oracle is paused, but if you launch the oracle instance on your machine (as explained in the repo README), you can have it working.
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
Once the CID of a file is generated, and file available on IPFS, we allow the registration of the hash of the file (sha-256) in the project Smart Contract, along with the wallet address requesting the registration (the certifier). Since the same file can have different CIDs on IPFS (due to how it has been generated, etc etc), users can avoid the upload of duplicate files if a CID is already available.
In addition, given a CID, you can see if it's a CID registered by a trusted certifier.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
+ currently the smart contracts are on Polygon chain, and we'll migrate them to FEVM
+ currently only single files can be indexed, we want to open up the index to CIDs containing multiple-files

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Project created during the [Chainlink Fall 22 Hackathon](https://chainlinkfall2022.devpost.com/). We won the 2nd Prize of the Filecoin - Computer over Data grant.
Submission link: https://devpost.com/software/chainlink-hash
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
👉 Antonio, as@odfdata.com, @70nyIT, Solidity Dev + Frontend Dev
👉 Federico, fc@odfdata.com, @fedecastelli, Backend dev + Cloud architecture

* How did you learn about our microgrant program?
Talking with Iryna, Head of Developers Relations at Bacalhau

* If your project was created as part of an event or hackathon:
  * It was created during the last Chainlink Fall 22 Hackathon
  * Please link to your hackathon submission: https://devpost.com/software/chainlink-hash

**Comment by ErinOCon** [comment]
Hi @70nyIT, thank you for your proposal! This microgrant has been approved. We will send an email to confirm payment details.

**Comment by 70nyIT** [comment]
@eshon 

The grant is completed!

Things we've implemented:

* improved the logic by breaking up **smart contract into 3**: one to manage oracle operations, one to manage CID-Hash matching, one to manage endorsement of a file
* **simplified** the deployment of solution, including chainlink, also for FEVM
* change the logic of endorsement: now more users can **endorse a CID**, and not only who adds it to the registry
* **migrated to FEVM**, adapting our smart contracts deployed
* added the option to index not only CIDs representing single files, but also **CIDs linking to more than one file**
* chainlink oracle can now **verify files of any size**, with an event-based cloud architecture that allows better replaying of failed events
* created a detailed **guide on how to set up an IPFS node with private access**. This is the node used by Chainlink Oracle
* **adapted frontend UI** to reflects the features included in our smart contract
* included README on each folder, with a master README to tell exactly how to deploy our solution, also on a local testnet

Why using Wiki-IPFS now?

* to **publicly endorse a file**. In this way, if I see a CID, I can check who is endorsing it, and if I trust one of more addressing endorsing it
* to **help better index the IPFS space**. Matching a hash - CID combination avoids duplication of uploaded files, as the same file can have different CIDs
* before computing a file in a solution like Bacalhau, it's convienent to **check who is endorsing the file**, and if the file I get can be trusted

You can track all the work we've done looking at the branch `master-FIL-grant-q1-23` of our repository ( https://github.com/odfdata/wiki-ipfs/tree/master-FIL-grant-q1-23 ). It has already been merged in the `master` branch, but all the work included in this microgrant has been first merged in that branch, also for tracking.

There's currently a deployment on FEVM (hyperspace), and we've recorded the smart contract addresses of that deployment in our main readme. Though, since FEVM is often reset in this phase, there's the option you'll need to redeploy the contracts if they're no more availables (link to FEVM explorers are provided).

**Comment by ErinOCon** [comment]
Hi @70nyIT, thank you for your update! We will be in touch with any questions.

**Comment by 70nyIT** [comment]
Excellent @ErinOCon !

**Comment by eshon** [comment]
Hi @70nyIT - Can you please provide a working demo link? In addition, please link to a demo video if you can. Also we'd like to see the following:

- A fully working user-facing demo with nice UX
- Currently deployed on the Hyperspace testnet, so that we can see all the functionality working on Hyperspace
- Deployed to Filecoin mainnet when FVM launches on mainnet after March 14

If you need oracle infrastructure support, you can use https://midpointapi.com. They are currently setting up their infra on Hyperspace and will be supporting FVM mainnet launch. We'll update https://github.com/filecoin-project/testnet-hyperspace with more Midpoint API details when it's ready.

**Comment by 70nyIT** [comment]
Hey @eshon , sorry for the delayed response. We have been pretty busy.

You can find the deployed version at https://master.d1yjc3iv5vpzcb.amplifyapp.com/.

To get started, connect to Hyperspace and ensure that you have some tFIL in your wallet. Then, choose a file, upload it, and request verification. You can also endorse the file by clicking on the "Endorse" button once it has been uploaded.

For the Oracle, we are using external adaptors and have implemented a fully functional Chainlink Oracle. We have also deployed a testing version of the LINK token on FEVM.

Let me know if you are able to test it!

**Comment by eshon** [comment]
Hi @70nyIT, I just tried the demo and it's working well. Thanks! Your submission has been approved and we'll process this soon.

**Comment by 70nyIT** [comment]
Wonderful, thank you so much @eshon !!!

**Comment by 70nyIT** [comment]
@eshon , we are yet to receive the second installment of our grant. I've contacted @ErinOCon via email, who has been very kind and forwarded the request to @pap1ll0n , but after two months we haven't received an answer yet. Could you please check from your end to ensure everything is in order? We appreciate your assistance. Thank you!

**Comment by pap1ll0n** [comment]
@70nyIT Payments are processed via the [Coin Emissary](https://pl.coinemissary.com) - the same tool used to facilitate the first tranche. Please submit a new FVM Microgrant request for $4000.
