### ISSUE TITLE
Next Step Microgrant: FELT Labs (federated learning on Filecoin)

### ISSUE THREAD

**Issue by FilipMasar** [filecoin-project/devgrants#1275]
### 1. What is your project, and what problem does it solve? (max 100 words)

We are creating set of tools for running federated learning / federated analytics on distributed data. Originally our tools work with Ocean Protocol. We would like to extend it and use it with Filecoin Virtual Machine. This would allow users to easily perform data analytics or train machine learning models on data stored on Filecoin

### 2. Project links
  
Link to Github repo: <https://github.com/FELT-Labs>
Link to demo or website, if applicable: [website](https://feltlabs.ai), [demo video](https://youtu.be/xLcIxxA_9Rs)
License: GPL-3.0

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

We would like to create web application, that will allow users to easily run data analytics on datasets stored on Filecoin. Users will be able to pick datasets and choose which analytics  they would like to compute. We will run that analytics using FVM on individual datasets and then aggregate them into final result. Final result will be available to download. The flow is similar as what we have currently for Ocean Protocol. We would like to extend it to Filecoin. Once we have this basic workflow for analytics, we can extend it to support different machine learning models. So users will be able to easily train machine learning models across multiple datasets stored on Filecoin.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Our project currently works with Ocean Protocol. With support from this grant: we will research how to extend what we have to support data from Filecoin, we will create a data analytics workflow and we will update our web application for anyone to easily start similar worklow
Steps:
1. Understand how to run our algorithm for data analytics on FVM
2. Run simple data analytics on FVM on 1 dataset stored on Filecoin
3. Run simple data analytics on FVM on 2 datasets and aggregate results together using FVM
4. Integrate with our web application

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, we are willing to submit grant reports.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
No, we haven't submitted it for the Protocol Labs prizes

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  * Bretislav Hajek: breta.hajek@gmail.com, <https://github.com/Breta01>, Co-founder, developer
  * Filip Masar: filip.masar99@gmail.com, <https://github.com/FilipMasar>, Co-founder, developer
* How did you learn about our microgrant program?
  * from email
* If your project was created as part of an event or hackathon:
  * Started with Chainlink hackaton 2021 - <https://devpost.com/software/federated-learning-token>
  * We were supported by OceanDAO, Ocean Shipyard - [blog post](https://medium.com/@TeamOcean/felt-labs-joins-shipyard-222d2d885108)

**Comment by ErinOCon** [comment]
HI @FilipMasar, thank you for your proposal and for all of your patience with our unexpectedly long review process. We will not be moving forward with a grant at this time, but are wishing you all the best as you continue to build. 

Thank you again for your interest in our grants program!
