### ISSUE TITLE
Next Step Microgrant: FEVM - Proof of Help [Update]

### ISSUE THREAD

**Issue by irwingtello** [filecoin-project/devgrants#1276]
### 1. What is your project? (max 100 words)
Platform to keep track of the volunteering/assistance/mentoring impact a person has had on FEVM.

The impact this platform will have is that it will be able to validate the real impact a person is having, to have a real metric outside of centralized services (Twitter Reactions,Youtube Reactions, etc).

Currently, if you delete your social network, you lose track of the support you have given or if you are censored.

### 2. Project links
Link to Github repo:
https://github.com/irwingtello/poh

FEVM Integration:
https://github.com/irwingtello/poh/commit/4be4b4a9b81a4a41475e09b39c8b0f61a3a76e4c

Link to demo or website, if applicable:
Demo:
https://poh-irwingtello.vercel.app/

![FkPcOz2WIAAF31k](https://user-images.githubusercontent.com/28800239/208331236-93be0d29-2b73-46e2-a919-cd8ca6160fb7.png)

License: MIT , Open Source
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
The site will be stored in IPFS, along with the badges and transactions will be processed in FEVM, with this MVP we want to experiment with FEVM and use the potential of the FEVM.
  ![X](https://user-images.githubusercontent.com/28800239/202844978-08c93372-fd32-4394-93da-a8cba13da9a1.png)

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
It would help us to cover part of the transactions that users generate and to develop a project that can be used by someone else as a example to build on the FEVM .

In the demo i have built, includes this features:
1.- User can generate an image and upload this to NFT.Storage
2.- Smart contract to mint a POH badge to specific address [WIP]

These two features are in progress, and we would love to integrate AI image generator and good mechanism.

This development will be publicly updated on Twitter, Linkedin and Discord.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes,i have experience with the creation of the dfhcommunity.com,transparency,open source,collaboration source it's part of  our core values.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions:
https://poh-irwingtello.vercel.app/
https://twitter.com/irwingtello/status/1604375213902336001
https://github.com/irwingtello/poh

### Additional questions:
Founder:
Irwing Tello
Experience:+5 yoe, JS, React, Solidity.
Experience in different communities teaching about web3.
Recently i participated as mentor on ETH San Francisco 2022
https://sf.ethglobal.com/
Role: Main Developer
https://github.com/irwingtello
https://www.linkedin.com/in/irwingtello/
https://twitter.com/irwingtello

Contribuitor:
Carlos Huerta
Role: Main Developer
Experience in voluntaring and teaching people with IT problems. 
https://github.com/CarlosHuerta06

**Comment by ErinOCon** [comment]
Hi @irwingtello, this microgrant has been approved! Can you provide the preferred email address to confirm payment details?

**Comment by irwingtello** [comment]
Hello @ErinOCon ,

This is my preferred email:
irwing@dfhcommunity.com

Furthermore, thanks for the review, this project will be amazing :D

**Comment by ErinOCon** [comment]
Thanks, @irwingtello!

**Comment by irwingtello** [comment]
First weekly update #1
We integrated wagmi.sh and we have part of our feature on the FVM, we are pending to add the message to write on the badge

https://youtu.be/J24ZGAcZZAE

Happy new year!

**Comment by irwingtello** [comment]
Weekly update 2
We analized the ways to integrate AI to generate beautiful images for our users to different badges.

https://buildspace.so/p/build-ai-avatars

We found this tutorial, and we build this feature on the weekly update 3

**Comment by irwingtello** [comment]
Weekly update 3

I learned how to generate images for the project with artificial intelligence, but the main objective of integration, I see it still in a state of development the generation of artificial intelligence images.

You have to be very specific and sometimes it gives strange results.

These are the images I will be implementing:

It is better to provide the user with images by POH and give the ability to upload images by  the user.

![poh (1)](https://user-images.githubusercontent.com/28800239/213822332-3deffc85-67fb-4684-b546-0f0323fdc0b2.jpg)
![poh (2)](https://user-images.githubusercontent.com/28800239/213822335-7c592d00-2f80-4bac-8e07-3c6254cea343.jpg)
![poh (3)](https://user-images.githubusercontent.com/28800239/213822336-124ec3d8-26fb-43e5-93f3-5663b55aff1d.jpg)
![poh (4)](https://user-images.githubusercontent.com/28800239/213822337-76cce742-c536-4485-9559-c11f41a67f72.jpg)
![poh (5)](https://user-images.githubusercontent.com/28800239/213822338-2fb1eee4-12e1-4b4c-9501-67dd018dc631.jpg)
![poh (6)](https://user-images.githubusercontent.com/28800239/213822339-a1509757-e9cb-426d-984b-36fb2bbcf66b.jpg)
![poh (7)](https://user-images.githubusercontent.com/28800239/213822340-c7132c50-13b2-4371-87f4-51a4a996d285.jpg)

**Comment by ErinOCon** [comment]
Hi @irwingtello, thank you for the regular updates! Once your project is complete, you can find the template for the final report [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

**Comment by irwingtello** [comment]
Weekly update 4:

I have made the following changes:
1.- Migrated from Wallaby Testnet to HyperspaceTestnet.
2.- Added the page where the badges will be minted [the minting process is not yet complete].
The mechanism for minting is in progress. To prevent abuse of the self-generated badge system, 
I'm considering implementing a validation process where the user must submit a photo along with a random number.

Could you please check the FVM integration, @eshon? 😁

This is the demo for this update:
https://youtu.be/h9_R3-M80UU

And the new changes are available on the site:
https://poh-irwingtello.vercel.app/

Yes, I will complete the form when I finish, Thanks @ErinOCon :D
I have these doubts:
1.- About the second tranche ,i know i will mention @eshon 😄 .
2.- Are now tools in the Hyperspace Testnet to detect onChain events,like https://www.whal3s.xyz/?

**Comment by irwingtello** [comment]
Weekly update 5:
I'm continuing to analyze and implement an anti-abuse system for the auto-generation of badges

For the second tranch, was the implementation I did correct?
@eshon , @ErinOCon

**Comment by irwingtello** [comment]
Weekly update 6:
The anti-abuse system will require the user to upload a photo that will be uploaded to IPFS, so that this platform will be used for international volunteer use cases and the same community will validate the badge or someone from DFH.

We will use firebase to store the IPFS URI

**Comment by eshon** [comment]
Hi @irwingtello,

Thanks for your work on this project!

- You can use eth_getLogs or eth_subscribe for events with the Filecoin RPC endpoints described here: https://github.com/filecoin-project/testnet-hyperspace#resources

- I just tried out the demo and have some questions:
  - The image didn't load - does it load for you?
  - What is the domain *.poh about? Is this intended to be a way to retrieve the NFT later on?

- Other than deploying your existing contract to an FVM testnet, I don't see enough FVM-related development or UX/UI improvements for the full microgrant yet. Here are some things we'd like to see in FVM Microgrant projects:
  - A fully working user-facing demo with nice UX that anyone case easily use.
  - Will be deployed at FVM mainnet launch and is currently deployed on the Hyperspace testnet, so that we can see all the functionality working on Hyperspace.
  - Interesting use of the EVM on Filecoin, especially with respect to what's unique to Filecoin.

Is it possible for you to figure out ways to improve your project with respect to the above? Some possibilities: 
  - Completing the domain name feature
  - Creating a registry of these NFT badges on FVM and displaying them on a new "POH Community page", along with their NFT.storage links
  - Making the website nicer with more helpful instructions for users
  - etc.

**Comment by irwingtello** [comment]
Thanks  @eshon  and the filecoin team,we will  work on these recommendations, and we have some delays,because we created the first beta tester community about this project ,we will launch on one hackhaton we planned

**Comment by irwingtello** [comment]
Hello @eshon , @ErinOCon ,

We have been working hard to improve the project and have made significant progress. Based on the feedback we received, we made the following changes:

•	We created a registry of NFT badges for individuals.

•	Users can now see their badges on the "My Badges" page.
https://github.com/irwingtello/poh/blob/main/src/Personal.js

•	We have implemented the domain name feature on the smart contract, though we encountered some issues with on-chain enumeration. However, we found a way to overcome this obstacle.
https://github.com/irwingtello/poh/tree/main/src/Solidity

•	We have also improved the UX/UI and have implemented an anti-abuse system on the platform. 

•	With the anti-abuse system, users must upload a selfie with a hash to avoid self-minting of badges.
Note: We are still pending the creation of organization badges page.

•	Regarding the image loading issue, it worked fine for us and other testers.
 Please refer to the demo video:
 https://youtu.be/GLlwDVNLkA8

•	Before deploying it on the FVM Mainnet, we are stressing the project and we will launch mainnet until we have stressed the different parts

•	The POH Badges functionality is similar to POAP tokens, but with a key differentiation: users need to input a random hash to mint the badge. 

•	The POH Badges have various use cases, including detecting the value of volunteering and team player spirit in business and tracking employee behavior across different companies.

•	Our project provides unique data about how people interact with each other in the world. In the future step, local governments can search our page to detect if citizens have good behavior or values.

Could you review the new improvements? , @eshon , @ErinOCon 
Platform:
https://pohdfh.vercel.app/

Thanks in advance

**Comment by ErinOCon** [comment]
Thank you, @irwingtello! We will review and circle back.

**Comment by irwingtello** [comment]
Hi Eshon, thanks for the feedback, yes, we will move to the Calibration network and we are happy to be a reference for other builders :D

**Comment by irwingtello** [comment]
Hi @eshon , thanks for the feedback, yes, we will move to the Calibration network and we are happy to be a reference for other builders :D
