### ISSUE TITLE
FID: A Decentralized Self-Incentivized User Identity Community on Filecoin

### ISSUE THREAD

**Issue by TerenceClark** [filecoin-project/devgrants#1277]
### 1. What is your project, and what problem does it solve? (max 100 words)
Providing a unified decentralized user identity system for the Filecoin ecosystem. 

### 2. Project links
  
Link to Github repo: https://github.com/TerenceClark/fid
Link to demo or website, if applicable: https://fid.domains/
License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
The project is done primarily with the solidity contract and requires the use of FVM. The user profile picture is stored in Filecoin.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
Yes

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
* Currently our contracts is only deployed on the goerli testnet, we need to deploy the contracts on FVM.
* Currently our dApp page is just a Demo, we still need to redesign and deploy it.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
The detailed description of our project is as follows:
[FID: A Decentralized Self-Incentivized User Identity Community on Filecoin](https://docs.google.com/document/d/1QeRzHAtxRLCIrqVKa4YZDE9fiGf9s0ri5JCtTYdpn1I/edit?usp=sharing)
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Terence, lwow2020@gmail.com, @TerenceClark, Solidity Dev + Frontend Dev.
bowen, 511838976@qq.com, @yanbowen1994, Solidity Dev + Backend Dev.
Ben_ZXS, 757724280@qq.com, @ElecRoastChicken, Backend Dev.
* How did you learn about our microgrant program?
We saw this microgrant program in Filecoin's Slack.

**Comment by eshon** [comment]
Hi @TerenceClark, your app seems to be a fork of ENS. What specifically will you build for this grant project that is new and original?

**Comment by TerenceClark** [comment]
> Hi @TerenceClark, your app seems to be a fork of ENS. What specifically will you build for this grant project that is new and original?

Our first step focused on completing the decentralized community Self-Incentive Mechanism and getting our community started. Of course, the redesign of dApp should be completed at the same time (currently the appearance of ENS is used, but it does not meet the needs of our dApp). These works are expected to be completed by 2023-06.
In the second step we will look to partner with appropriate projects in the Filecoin community to use FID.

**Comment by ErinOCon** [comment]
Hi @TerenceClark, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
