### ISSUE TITLE
Next Step Microgrant: Easy txs with Fil

### ISSUE THREAD

**Issue by knrdrbn** [filecoin-project/devgrants#1278]
### 1. What is your project, and what problem does it solve? (max 100 words)
It solves transacting with Fil easily. Currently, you have to ask for a wallet address and make a test transaction. This solution enables single payment links.

### 2. Project links
  
Link to Github repo: 
Link to demo or website, if applicable: 
https://docs.google.com/presentation/d/1n0dsJch5uv4eWXy_q4vbDBp0PEy4AX87E8-CiHfjJY0/edit?usp=sharing
Demo with Wallet Connect and aEth, oEth, goerliEth to demonstrate flow with Glif/Lotus and Fil. http://peanut.to/
License: UNLICENSE

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

Fil, Glif and Lotus will be to make transactions safer and easier.
###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will include Fil and Glif/Lotus. http://peanut.to/

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 We won #1 at EthCC for best use of Filecoin

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Konrad Urban, konrad@peanut.to, knrdrbn
Hugo Montenegro hugo@peanut.to, hugo0

* How did you learn about our microgrant program?
At Fillisbon

**Comment by ErinOCon** [comment]
Hi @knrdrbn, thank you for your proposal and for your patience during our unexpectedly long review process. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
