### ISSUE TITLE
Next Step Microgrant: Upragde-Doge

### ISSUE THREAD

**Issue by metanomad21** [filecoin-project/devgrants#1281]
### 1. What is your project, and what problem does it solve? (max 100 words)
Web3 project owners are not aware that upgradeable contracts have admin rights independent of business logic. As a result, when project handover, the remaining permissions are in the hands of the departing coders, resulting in security vulnerabilities.So upgrade-doge provides a series of visual upgrade management tools for Openzeppelin-based upgradeable contract projects.In particular, the friendly interactive interface is used to enable non-technical members to view and manage the contract upgrade authority conveniently and timely.

### 2. Project links
  
Link to Github repo:https://github.com/doge-verse
Link to demo or website, if applicable:https://www.upgrade-doge.xyz/
License:Apache 2.0
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
First of all, our front-end web page is deployed on IPFS, and when users import the Network file of the project, they can choose to save the Network file in IPFS to prevent loss.
###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
Yes.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
This microgrant will fund the following technical, community, and research work:
Technical/ UX Upgrades:
Create official website, optimize dapp user experience, and invite professional designers to design logo and UI.
Community:
Create Medium blog post about the Upgrade-doge project and create Twitter accounts and interact with users.
Research:
Continue to investigate contract security related issues and solutions, explore more possibilities of cooperation with FVM.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  Frontend-Dev: @Caploef-Xie @metanomad21
  Backend-Dev: @FWangZil @JangoCCC @AMARAjustone
* How did you learn about our microgrant program?
Learned from Antalpha Hackerhouse
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  Antalpha Hackerhouse
  * Please link to your hackathon submission
  https://www.notion.so/Upgrade-Doge-upgradeable-smart-contract-toolkit-5c7f4bed24dc45d69ac64436cf463006

**Comment by ErinOCon** [comment]
Hi @metanomad21, thank you for your proposal. We will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
