### ISSUE TITLE
Next Step Microgrant: Web3VitePress

### ISSUE THREAD

**Issue by Web3HackerDAO** [filecoin-project/devgrants#1282]
### 1. What is your project, and what problem does it solve? (max 100 words)
Make your vitepress blog to be a NFT that content store on IPFS.

### 2. Project links
  
Link to Github repo: https://github.com/Web3VitePress/Web3VitePress
Link to demo DApp: https://web3-vite-press.vercel.app/
Link to demo on ETHGlobal FEVM:  https://ethglobal.com/showcase/web3vitepress-43gs7
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
1. it pack blog article content onto IPFS
2. It pack metadata onto IPFS
3. Use NFT.Storage
4. Use FEVM to deploy our ERC1155 NFT contract(support create new token for new article and mintNFT to get the article's NFT)

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
Yes

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. [Fix the bug while mint NFT action](https://github.com/Web3VitePress/Web3VitePress/issues/1), this maybe need to further dig into the FEVM to find the solution then.
2. [A Blog/Article for the Web3VitePress explanation both in English && Chinese](https://github.com/Web3VitePress/Web3VitePress/issues/2)
- [ ] How this idea comes out?
- [ ] How the tech combine and works?
- [ ] Invite more developers to join to use this theme and make PR!
- [ ] Publish the article on Medium/Twitter/reddit/Wechat Office Account of Web3HackerDAO

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, will be in 1 months to finish the work list above.

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
Yes, it win a Pool Prize(should be in top 10 slot, but I fall asleep while call me to make another final demo) on the ETHGlobal FEVM hackathon.
https://ethglobal.com/showcase/web3vitepress-43gs7

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Web3Hacker, web3hackerdao@gmail.com, https://github.com/Web3HackerDAO, Web3 Full Stack developer.

* How did you learn about our microgrant program?
From the  the Pool Prize notification email.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
 ETHGlobal FEVM

  * Please link to your hackathon submission
  https://ethglobal.com/showcase/web3vitepress-43gs7

**Comment by ErinOCon** [comment]
Hi @Web3HackerDAO, thank you for proposal. This microgrant has been approved! We will send an email to confirm payment details.

**Comment by Web3HackerDAO** [comment]
> 

Great! I will reply update here later after I done with these tasks

**Comment by Web3HackerDAO** [comment]
Hi @eshon I just deploy to the latest testnet， and make some func call here:
https://wallaby.filfox.info/zh/address/0xc6eD496eaFAaCD3254adD3e62Cd3f1D87b8d89Ac

also fix the issue 1: https://github.com/Web3VitePress/Web3VitePress/issues/1

**Comment by Web3HackerDAO** [comment]
Hi @eshon , I just finish the second task of the grant: https://github.com/Web3VitePress/Web3VitePress/issues/2

So the grant's all tasks done! Pls check!

**Comment by ErinOCon** [comment]
Hi @Web3HackerDAO, congrats on your progress! We will be in touch once we've completed our review.

**Comment by eshon** [comment]
@Web3HackerDAO - I get the following error when trying to run this:

<img width="692" alt="Screen Shot 2023-02-23 at 2 38 43 PM" src="https://user-images.githubusercontent.com/1017762/220922978-b9ff833c-e23a-4281-9504-34a4bc31794f.png">

Also we'd like to see the following:

- A fully working user-facing demo with nice UX
- Will be deployed at FVM mainnet launch and is currently deployed on the Hyperspace testnet, so that we can see all the functionality working on Hyperspace

Can you please create the following to make this demo easier for users just wanting to try something out quickly:
- an example blog
- an example of NFT-based access to some blog post on that blog
- a way for users to mint the NFT for access?

**Comment by Web3HackerDAO** [comment]
Hi @eshon I just make the update these days: 
PR here: https://github.com/Web3VitePress/Web3VitePress/pull/4


- [x] A fully working user-facing demo with nice UX
https://github.com/Web3VitePress/Web3VitePress

- [x] Will be deployed at FVM main net launch and is currently deployed on the Hyperspace testnet, so that we can see all the functionality working on Hyperspace
Deploy on here: https://hyperspace.filfox.info/en/address/0x859b5D835cb718c0ab892Eef7F5419f1aEc3fc78
- [x] an example blog
Example blog here: https://web3-vite-press.vercel.app/demo-blog/clonex.html
User can connect wallet and mint the current article NFT as donation
- [x] an example of NFT-based access to some blog post on that blog
we just make that every article can generate a NFT that the readers can donate $FIL to mint the NFT to support the writer
- [x] a way for users to mint the NFT for access?
Yes! on every article's right side if it marked as have NFT relative to it!
![Screenshot 2023-02-26 at 19 35 33](https://user-images.githubusercontent.com/109504677/221408088-26f7e56e-cef5-434a-8de2-635f0ba52ec0.png)

**Comment by eshon** [comment]
Hi @Web3HackerDAO - I have a Metamask wallet connected to Hyperspace but when I visit  https://web3-vite-press.vercel.app/demo-blog/clonex.html I cannot see the Mint NFT button link above. How can I see this link?

Can you please also record a demo video of this workflow working and link to it here?

https://github.com/Web3VitePress/Web3VitePress is not a user-facing demo but developer-facing. How does a regular end-user interact with this project? Do you have a sample blog that requires NFT-based access?

**Comment by Web3HackerDAO** [comment]
@eshon 
1. I have write the guide in text here: https://web3-vite-press.vercel.app/guide/
2. Just make a video demo on loom here: https://www.loom.com/share/287d393b3b2341be9a1f800c99572bc7
3. The user-facing demo is this page, that it shows to the user how to mint the article NFT to support the author of the article  https://web3-vite-press.vercel.app/demo-blog/clonex.html

**Comment by Web3HackerWorld** [comment]
@eshon Hi , how is this going? Is this response ok?

**Comment by Web3HackerWorld** [comment]
> 

The mint of the NFT is more like the feature on Mirror.xyz, which only means the user pays to mint the NFT to support the article's author.

The goal of this project is just to create a donate solution and publish the content to IPFS to make the copyright on Chain.

You can see the improvement on the grant content  # 4, it do not include NFT access feature actually.

===>>>
4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. fix the error here: https://github.com/Web3VitePress/Web3VitePress/issues/1, this maybe need to further dig into the FEVM to find the solution then.
2. write blog for this idea: https://github.com/Web3VitePress/Web3VitePress/issues/2

**Comment by Web3HackerWorld** [comment]
Hi @eshon 
I just successed deploy it to the calibration testnet: https://calibration.filfox.info/en/address/0x558d97E41E5415620a68CF237E9469a78811F015

**Comment by eshon** [comment]
Hi @Web3HackerWorld -

1) I cannot see the Mint NFT button again at https://web3-vite-press.vercel.app/demo-blog/clonex.html - Why has it disappeared?

2) The idea for NFT-based access was included in your blog post about this project and was one of the reasons this project was accepted for an FVM Microgrant. 

3) Otherwise if you're going to focus on the donation aspect, can you please improve the UX of donations and make it more clear that by minting an NFT the user is going to donate it to the author? Can you give the author a clear address on the blog and show their current donation balance?

**Comment by Web3HackerWorld** [comment]
Hi @eshon 

1. Ok, I will fix this
2. Ok, I will refactor the code to implement this feature that can provide the nft-gating func for vitepress users, give me more time that I will rewrite some more code for this, also planning to make a general solution for this that can avoid new vitepress user to deploy new contract and only need user to click some button to have new NFT for them.
3. Ok! I will do that!

This requires more time as I build the platform-level solution for this nft-gating stuff. 

After that comes back to this project and make the web3 vitepress easier to use.

**Comment by eshon** [comment]
Hi @Web3HackerWorld - You submitted a request for the 2nd milestone payment but we would like to see the updates above in order to release that. Do you have any updates?

**Comment by Web3HackerWorld** [comment]
> Hi @Web3HackerWorld - You submitted a request for the 2nd milestone payment but we would like to see the updates above in order to release that. Do you have any updates?

not yet, as I build a separate js SDK to support this project now for nft-gating logic, after I finish build the nft-gating ts SDK, then I will come back to update this project to use that sdk to implement the nft-gating feature. 
Hope this is all right as I build the SDK need more time to work on it.

Thx
