### ISSUE TITLE
Next Step Microgrant: searchable encryption

### ISSUE THREAD

**Issue by ice0wyb** [filecoin-project/devgrants#1283]
### 1. What is your project, and what problem does it solve? (max 100 words)
A decentalized storage and retrieval protocol for encrypted data that can be applied to the Meta and Web3.0 scenarios, and can be used on mainstream blockchain ecosystems such as Ethereum, Polka, Solana, Filecoin, etc
Enables encrypted data to be retrieved and calculated
Offers decentralized storage of encrypted data and reliable, highly-efficient and complete search on cipher text

### 2. Project links
  
Link to Github repo: https://github.com/ice0wyb/SE
Link to demo or website, if applicable:
License:

MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
Use ipfs to store ciphertext data, and can directly retrieve and calculate ciphertext data, so that ipfs can use ciphertext data more efficiently, and can directly train artificial intelligence networks on ciphertext data. Better improve the efficiency of ipfs storage usage, and store more valuable data on ipfs.
###    b) Is this project contributing to the upcoming FVM launch? (Yes or No) 
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Q1. Optimize the precise search algorithm of the non-interactive searchable encryption algorithm to improve search performance; improve the accuracy of fuzzy search and synonym search
Q2. Add a conditional search function to the non-interactive searchable encryption algorithm, and be able to search encrypted pictures
Q3. Through non-interactive searchable encryption, the authorization of encrypted data can be realized, and the user who leaked encrypted data can be traced back
Q4. Implement a non-interactive searchable encryption algorithm that can perform ciphertext calculations on encrypted data

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by eshon** [comment]
@ice0wyb - can you be more specific about how you will use Filecoin Virtual Machine smart contracts in your project going forward, if at all?

**Comment by ice0wyb** [comment]
收到邮件

**Comment by ice0wyb** [comment]
> @ice0wyb - can you be more specific about how you will use Filecoin Virtual Machine smart contracts in your project going forward, if at all?

We will use FVM to issue search tasks, and use FVM to verify the integrity of search results and search results to prevent participating nodes from doing evil. The redirection authorization of the ciphertext content will also be performed through FVM.

**Comment by ErinOCon** [comment]
Hi @ice0wyb, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
