### ISSUE TITLE
Web3Domain FEVM

### ISSUE THREAD

**Issue by gupta977** [filecoin-project/devgrants#1284]
# Open Grant Proposal: Web3Domain

**Name of Project:**

**Proposal Category:**  integration-adoption

**Proposer:** https://github.com/gupta977

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** YES

# Project Description

We are building a Web3 Domain Name that will be used as a decentralized identity and to host a website over Filecoin using IPFS & NFT.Storage.

This domain name is used to create a profile including wallet address, social handles, avatar, bank details, and many more. 
We are **proud to say that Filecoin helped us** since microgrant and these features are ready to use.

We already completed the FIL domain over the polygon chain. 
Now we will migrate the FIL domain completely on FEVM so that every FIL domain minted occurs in FVM only.
Users need to connect to Metamask and choose Filecoin main net (Currently using wallaby test net because FVM is still not ready).
We have joined the Filecoin foundry program and daily interact with different teams.

Every domain minted has a use case and all use polygon at the backend.
_We need to migrate every application to use FVM too for fil & other user-specified domains._

**It includes**

- update of the Telegram Bot
- update of Chrome Extension at Web Store.
- update of Web Tools at our resolver websites.
- update on the developer's PHP & JavasScript API
- updates to the WordPress Application at wordpress.org
- updates of Developer Libraries at w3d.name
- updates and deployment of new smart contract interface public function call.
- and all upcoming application

Our WordPress application is currently used by 200+ sites and it will open the door to FEVM. They will have the choice to mint their own desired TLD domains on FVM. 
All records are uploaded to Filecoin using IPFS
Every domain will generate a website uploaded using NFT.Storage API. Decentralized hosted website in short with every domain. 

Thank you for creating a such platform for a complete web3 solution. 

## Deliverables

Users can SELL / MINT domain on their website using FEVM
fil domain uses only FEVM
Open source WordPress plugin code which will be continuously updated as required. 
Updating all the applications required to interact with the domain to use FVM-based smart contract. 

## Development Roadmap

This project required 4 weeks.
As we are working on WordPress Plugins for the last 8 years, we know what to provide for the best service possible. 

## Total Budget Requested

- Milestone 1- We will do everything in a single milestone because in middle it is hard to demonstrate or explain the completed part. 
- It will cost us US$10,000. (We invested $3000 already from our side, so an insufficient amount of $10,000 is required)
- We won't add additional cost to it and promise to complete it within the promised amount.
- This software will be free to use and open source. 
- Users do not need to purchase any licenses or services from our end. 
- We will keep on updating it with more added features in the future.
- We will hand over with LIVE working example on a dedicated website that will documentation. 

## Maintenance and Upgrade Plans

We keep on updating the plugins. 
The updated changes with time can be monitored through Github. 

# Team

## Team Members

Navneet Gupta is the leader of the team and the rest everyone is freelancers. 

## Team Website

https://web3domain.org/
http://w3d.name/

## Relevant Experience

We are working in the web industry for more than a decade. We know the quality need to offer and business practices to promote products at a minimum cost but in an efficient way. 

## Team code repositories

https://github.com/gupta977

# Additional Information
I feel myself contributing in each possible way to the Filecoin ecosystem. 
Filecoin team continues to support and kept believed in our project. We promise to deliver the world's best-class product with multiple applications. 

Thank you.
Navneet Gupta

**Comment by ErinOCon** [comment]
Hi @gupta977, thank you for your proposal. It's great to see the continued use of the Filecoin stack for improving product functionality! We will not be awarding a grant at this time as we would like to see more traction and usage of the product prior to considering a third grant.

Wishing you the best as you continue to build!

**Comment by gupta977** [comment]
We have improved a lot product functionality and it's live.
you can check these updates at
web3yak.com
web3domain.org
w3d.name

Above are the different website separated for user continence and understanding.
Please review again.

**Comment by ErinOCon** [comment]
Hi @gupta977, thank you for the update! The review for this specific item is closed, but you are welcome to submit a new proposal [here](https://github.com/filecoin-project/devgrants/issues/new/choose) at any time.
