### ISSUE TITLE
Next Step Microgrant: <seedstore>

### ISSUE THREAD

**Issue by globotree** [filecoin-project/devgrants#1285]
### 2. Project links
  
Link to Github repo:
Link to demo or website, if applicable:
License:

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
<linked here at the critical point, require dev to email me please, I am trying to talk to some kind of mentor, I tend to do things to better understand systems of complexity many people do not and cannot understand due to the lack of guidance, my experience with A.I. is not one I am very proud of to date so it seems my messages are all sent into hyperspace anyways, why not ramble on here? I am a semi retired arborist/artist/ father and Law man, when I do go to work on my computer and attempt to develop my own data bank I run into all kinds of processes I honestly have a hard timemaking any headway, a friend of mine, a good friend at one point, he was an ethical hack, figured i would just try and live a little and build some content, somehow always lured back to github and I am afraid to mess any of the good work going on out here, so help me...send money, could use it, if i can help people someday its a pleasure, people can learn if we know what we are doing we can tell others, i don't know, i am learning but as you can see i have nothing to my credit here in the development forums, I am simply trying to develop an idea, which i can back up with physical assets, micro data, proof of work, but what about those who cannot, say someone just has no idea what content has anything to do with digital assets, code, encryption, developed and undeveloped webspace, web3, 5g or no key at all. trash2gold.crypto, globotree.crypto-->
### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
please.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @globotree, this issue has been closed as this program is intended for grant applications. To explore project and networking opportunities, check out our hackathons!
