### ISSUE TITLE
Next Step Microgrant: <Encrypted FileToken by Mark3d>

### ISSUE THREAD

**Issue by underkong-eth** [filecoin-project/devgrants#1288]
### What is your project, and what problem does it solve? (max 100 words)
<img width="1727" alt="Screenshot 2022-12-23 at 14 40 41" src="https://user-images.githubusercontent.com/112761407/209330452-0d9c18cb-c14d-438a-b991-7fbe4ff507e6.png">

We have created a new token standard on FVM, which we call EFT - Encrypted FileToken. Our project aims to solve the issue of unauthorized access to digital content by encrypting it and storing it on a blockchain using Filecoin in a way that protects data from unauthorized copying. We have developed a protocol that allows users to mint NFTs with attached encrypted files of any size stored on Filecoin, which can only be accessed exclusively by the owner of the NFT. This solution allows creators to monetize their content while protecting and securing their intellectual property.

### Project links
Link to Github repo: https://github.com/mark3d-xyz 
Link to demo or website, if applicable: [mark3d.xyz](http://mark3d.xyz/)  
License: MIT

### a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
<img width="1727" alt="Screenshot 2022-12-23 at 14 40 58" src="https://user-images.githubusercontent.com/112761407/209330744-a9fcb615-3262-4dbf-9d09-565cc83b706b.png">

Our project utilizes IPFS and Filecoin to store and manage files on it when minting NFT on Polygon blockchain. Specifically, we use the Lighthouse.storage protocol to work with IPFS and Filecoin to store and retrieve files on the decentralized network. This allows us to leverage the decentralized nature of IPFS and Filecoin to ensure the security and integrity of the files that we are managing.

In the future, we plan to further utilize the capabilities of Filecoin to manage and verify the transfer of encrypted files directly on the blockchain. This will allow us to create a fully on-chain solution for verifying the transfer of these files, providing an additional layer of security and accountability.

b) Is this project contributing to the upcoming FVM launch?
<img width="1728" alt="Screenshot 2022-12-23 at 14 41 17" src="https://user-images.githubusercontent.com/112761407/209330801-8a7503ab-2ce3-4675-9cfe-26d7597fe9b4.png">
Regarding the upcoming FVM launch, our project plans to launch on FVM and will contribute to the ecosystem by writing a technical article about EFT and creating a fip (Filecoin Improvement Proposal). These efforts will help to increase awareness and understanding of our project within the Filecoin community, as well as provide valuable information and resources for others who may be interested in using EFT or similar technologies.

### How will you improve your project with this grant? What steps will you take to meet this objective? 7 (max 200 words)

<img width="1726" alt="Screenshot 2022-12-23 at 14 41 58" src="https://user-images.githubusercontent.com/112761407/209331241-aab73138-08e4-423a-a4f4-f3e5eb647047.png">

1. With the Micro Grant, we plan to take several steps to improve our project and meet our objective. First, we will put altogether everything, we've built, and describe transfers in our protocol with all technical details. It will be in form of a technical article. This article will be distributed to the Filecoin and broader Web3 community through various channels such as Telegram groups and Twitter accounts. By providing this information to the community, we hope to increase awareness and understanding of the EFT standard and its potential uses.
This will increase the accessibility and usability of the EFT standard, helping to drive adoption within the community.

2. Finally, we will start the second stage of protocol development: starting to store the encrypted file in Filecoin storage, putting our web2 backend for transfer verification in FVM native actor, deploying our Solidity smart contracts to FEVM and connecting all these pieces (reading files in FVM actors from Filecoin storage and calling FVM actors from FEVM contracts). All our experience will be explained in detail for developers to use our project as a reference for developing their own ecosystems/applications with the Filecoin stack

### Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?
Yes, we agree to share grant reports upon request, including a final grant report at the end of the three-month period.

### Does your proposal comply with our Community Code of Conduct?
Yes, our proposal complies with the Community Code of Conduct.

### Links and submissions

Mark3d Twitter: https://twitter.com/mark3d_xyz 
Telegram Group for Metaverse builders: https://t.me/mark3d_xyz
Telegram Channel Metverse Radio: https://t.me/Metaverse_Radio
Metaverse Review by Mark3d: https://medium.com/@mark3d
Podcast The Metaversed: https://anchor.fm/the-metaversed
Metaverse TV by Mark3d: https://youtube.com/@mark3d
Linkedin: https://linkedin.com/company/mark3dxyz/

### Additional questions:

*How did you learn about our microgrant program?
FVM Early builder F1 cohort Weekly Check-in Zoom call 

*If your project was created as part of an event or hackathon:
Part of our project was developed on ETHGlobal FEVM Hack https://github.com/mark3d-xyz/hack-fevm 

*Team members:
Oleg Shatniuk - SysArch, Backend and Smartcontracts @shleshg https://github.com/shleshg
Stan Santalov - Frontend Dev @Santalov github https://github.com/santalov
Ilya Orlov - Founder and CEO of Mark3d (https://www.linkedin.com/in/orlov-ilya/)
Michael Korolev - Project Manager @kor2m ( https://linkedin.com/in/michael-korolev-a01a68150/ )
Eugene Ustinovich - Product Owner ( https://linkedin.com/in/ustinovichevgeny/ ) 
Oleg Kashuk - UX/UI Engineer

**Comment by ErinOCon** [comment]
Hi @underkong-eth, thank you for your proposal. It looks like your team members are significant contributors to the progress of your project. Can a member of your team comment here to verify this handle's affiliation with the project?

**Comment by shleshg** [comment]
> Hi @underkong-eth, thank you for your proposal. It looks like your team members are significant contributors to the progress of your project. Can a member of your team comment here to verify this handle's affiliation with the project?

Hello, @ErinOCon, I (Oleg Shatniuk) am confirming that I'm a part of the Mark3d project team.  As the mark3d github repository is public, this fact can be checked in the commit history and in "contributors" insights. Should we provide more proof of affiliation or comments from other team members like this one are enough?

**Comment by Santalov** [comment]
> Hi @underkong-eth, thank you for your proposal. It looks like your team members are significant contributors to the progress of your project. Can a member of your team comment here to verify this handle's affiliation with the project?

Hey, @ErinOCon. I am Stanislav Santalov, and I confirm this handle is affiliated with the project. I am a frontend developer in the Mark3d team, and I am involved in the development of Encrypted FileToken infrastructure.

**Comment by underkong-eth** [comment]
♥

**Comment by ErinOCon** [comment]
@underkong-eth Can you provide the preferred email address for this communication?

**Comment by underkong-eth** [comment]
orlov88io@gmail.com  🤗🙏🏼❤️

**Comment by ErinOCon** [comment]
Hi @underkong-eth, I hope your project is progressing well! If you have any questions regarding the reporting process for this work, please be in touch. In the meantime, here are some things we are looking for when reviewing FVM Microgrant results: 

- A fully working user-facing demo with nice UX that anyone case easily use.
- Deployment to FVM mainnet - now that it has officially launched!
- Interesting use of the EVM on Filecoin, especially with respect to what's unique to Filecoin

Happy building!

**Comment by Santalov** [comment]
> @underkong-eth Was trying out Filemarket.xyz today and ran into this. What image file types are supported?
> 
> <img alt="Screen Shot 2023-05-04 at 1 59 25 PM" width="1369" src="https://user-images.githubusercontent.com/1017762/236217662-70f2eeca-a1c6-42cd-9312-1313f5d0fa94.png">

Hello! We have recently added support for all image formats in the preview. Btw, filemarket.xyz is now on FileCoin mainnet. We have changed the core of our protocol and introduced FileWallet. FileWallet is a necessary solution for encryption key management

**Comment by underkong-eth** [comment]
> @underkong-eth Was trying out Filemarket.xyz today and ran into this. What image file types are supported?
> 
> <img alt="Screen Shot 2023-05-04 at 1 59 25 PM" width="1369" src="https://user-images.githubusercontent.com/1017762/236217662-70f2eeca-a1c6-42cd-9312-1313f5d0fa94.png">

You can still download the file, but not all formats are supported for the preview on the frontend yet. We are working on that and will soon update it=)

**Comment by underkong-eth** [comment]
Hello @ErinOCon nad @Eshon, the frontend Preview bug was fixed, you are able to preview pictures and 3D Models now.
<img width="1725" alt="Screenshot 2023-05-18 at 16 08 02" src="https://github.com/filecoin-project/devgrants/assets/112761407/c2a7ce1c-18fb-42cf-abc9-550f36d269bc">
