### ISSUE TITLE
<Your Title Here>

### ISSUE THREAD

**Issue by babeldao-admin** [filecoin-project/devgrants#1289]
### 1. What is your project, and what problem does it solve? (max 100 words)

We are a collaborative fiction DAO developing a publishing platform to display our works and invite more Web2 audiences to join us. Every work in our project is derived from a short story which is the DAO's collective property. Every work also expands the same universe and makes it richer by day. We compensate our creators with our native ECR-20 token and connect our pieces with a uniquely designed creator economy. In this way, we solve the problem that "fan works" cannot be monetized. On one hand, the distinction between fan-created and official works doesn't exist in our project. On the other hand, the creators profit from their individual works by making the entire universe IP more valuable. 
We are using NFT.storage to store our writings, visual arts, music, and creator economy metadata (a ledger that defines how revenue is distributed). 

### 2. Project links
  
Link to Github repo: https://github.com/Babel-Universe/Publishing-Platform
Link to demo or website, if applicable: Figma Wireframe: https://www.figma.com/proto/1XizFdyqt1btvfNFGmSgnL/Babel-Gallery-Website-Design?node-id=343%3A1065&scaling=scale-down&page-id=343%3A1064&starting-point-node-id=343%3A1065
DAO website: https://www.babeldao.co/
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

We use NFT.storage to store all the content we created and present them on our publishing platform. 

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No) 
No
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We plan to alpha(including basic publishing functions) launch our platform by the end of January 2023, Beta launch(including a prototype of the creator economy - automatic revenue distribution system) by the end of April 2023, and Public launch it within Q3 2023. Having the $5000 grant will let us involve more DAO contributors and accelerate this process. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

 Yes.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program? Google search, we've been knowing Filecoin for a long time.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @babeldao-admin, thank you for your proposal. We will not be proceeding with a grant for this project.
