### ISSUE TITLE
Next Step Microgrant: Cryptea

### ISSUE THREAD

**Issue by Temiloluwa-ade** [filecoin-project/devgrants#1290]
### 1. What is your project, and what problem does it solve? (max 100 words)

Cryptea is a payment infrastructure for businesses built on the blockchain. It’s a software that uses the blockchain to enable peer-to-peer transactions. Our APIs make it easy for companies to accept crypto payments without needing to compromise your customer data, while bridging the Web3 payment gap.

What does it solve?
The primary benefits are simplicity, speed, and improved security. Web3 has the potential to provide the simplest way for businesses to receive payments from their customers, clients, and individuals alike. Cryptea enables this.

Cryptea also addresses vulnerability to fraud with increased security, powered by the blockchain. We are improving transaction times, and providing scalability for large businesses or startups as well as small businesses. 

In recent times, blockchain is now widely accepted for business and people do that manually. We believe that this technology has the potential to revolutionize the way we make and receive payments, offering a fast, simple, secure, and transparent alternative to traditional payment methods. 

### 2. Project links
  
Link to Github repo: https://github.com/Cryptea-eth/cryptea
Link to demo or website, if applicable: https://cryptea.me, https://app.cryptea.me
License:  MIT license

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

We currently are integrated with the Filecoin EVM, and all our storage is done on IPFS, through the web3.storage SDKs.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

PHASE 1, Timeline: January - February 2023 (Funding Ask: $3000):
- Support for non-native tokens on-chain [USDC, USDT, etc]
- Integration of non-EVM chains (Solana, Cardano, etc)
- Early-stage marketing cost
- Infrastructural costs 

PHASE 2, Timeline: February - March 2023 (Funding Ask: $2000):
- On-ramp, for users
- Off-ramp, for businesses
- Integration of more chains (Tron, Bitcoin, Binance, Avalanche, Fantom, etc)
- Follow-up marketing cost
- Multi-currency support [Pound, Euro, etc]
- Mobile app for businesses and individuals
- Proposal to companies, to integrate the product.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, we agree to share grant reports upon request and share a final grant report at the end of the 3 months period.
In addition to this, we would be willing to create blog posts or short-form content for the Filecoin team. This would be in order to aid other Buidlers on Filecoin.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes, it complies with the code of conduct.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* https://cryptea.me
* https://app.cryptea.me
* https://github.com/Cryptea-eth/cryptea
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Temiloluwa Adelowo: 
   * temiadev@gmail.com, 
   * https://github.com/Temiloluwa-ade, 
   * Product Designer/Frontend Developer
* Joel Idiaghe:
  * idiaghegeorge9@gmail.com
  * https://github.com/george-hub331
  * Fullstack Developer/Blockchain Engineer

* How did you learn about our microgrant program? 
   - We learnt about it through the follow-up emails sent by the Protocol labs team, and the early builders' newsletter from FilecoinEVM.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) Chainlink Spring 2022 Hackathon, ETHGlobal ETHOnline, HackFEVM, Chainlink Fall 2022 Hackathon.
  * Please link to your hackathon submission
  * https://devpost.com/software/cryptea (initial idea)
  * https://devpost.com/software/cryptea-btu9xd
  * https://ethglobal.com/showcase/cryptea-rtmmj
  * https://ethglobal.com/showcase/cryptea-ty022
  * https://devpost.com/software/cryptea-48l76p (current build)

**Comment by ErinOCon** [comment]
Hi @Temiloluwa-ade, thank you for your proposal and for your patience during our unexpectedly long review process. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue to build!
