### ISSUE TITLE
Next Step Microgrant: <Thirdfund>

### ISSUE THREAD

**Issue by nuelvations** [filecoin-project/devgrants#1292]
### 1. What is your project, and what problem does it solve? (max 100 words)

Thirdfund is a decentralised fund raiser platform built using IPFS and Moralis the on polygon network. Effortlessly raise funds with crypto zero gas transactions (thirdfund is deployed on matic) Say a bye to card integration issues and funding transaction limits,let’s go all crypto! No sneaky policies our platform is 100% decentralised and easy to use . 

Thirdfund is decentralised (you don’t need to link your bank details or debit card) Effortlessly connect your crypto wallet,create fund raiser,provide your wallet address (polygon matic)and automatically get a funding contract in less than 1 minute, use your funding contract as a deposit slip to receive funding and donations round the world with zero gas transactions and no third party, end the fundraiser at your quest and get your funds deposited to your wallet address automatically no time lapse . Our platform has swift ux, and all transactions are recorded on our public ledger which users can acess via search,thirdfund is safe,fast,free and transparent that is why we chose the blockchain technology.

### 2. Project links

https://fundmeweb3.on.fleek.co/

  
Link to Github repo:
Link to demo or website, if applicable:
License:

https://github.com/Godhanded/Fund_Me-web3

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

We used IPFS in Third FUND for a number of things,

Firstly the Frontend for This project is hosted on IPFS through Fleek https://fundmeweb3.on.fleek.co/ . you can verify through IPFS here https://ipfs.fleek.co/ipfs/QmYzCYWA1uM8dLcZwdcyJotaWQ8dmLw2hdwUXzPuX7L3Wy/

Secondly IPFS came into play again after a user creates a fund raising contract through our platform, The Meta data such as; see [Upload Metadata Function](https://github.com/Godhanded/Fund_Me-web3/blob/main/public/main.js#L212), [Upload image Function](https://github.com/Godhanded/Fund_Me-web3/blob/main/public/main.js#L204)

                            {
                                "project Name": "Name",
                                "Project Image":"Avatar IPFS url",
                                "Owner Name":"Owner name",
                                "Funding Amount":"Amount needed",
                                "Project details":".....",
                                "Contract Address":"0xb1...",
                                "Owners Address":"0x12...",
                            }
The projects image/avatar is uploaded to IPFS through Moralis' gateway, the url is retrived and added to the Metadata which is also uploaded to IPFS. This to make it easy for fund raisers to share details about their funding, project, Cause ect.

Lastly IPFS is also used to retrive and View the Metadata of any fund raiser generated on our Platform, this is done by searching for the projects name in the search bar, it looks for the IPFS url mapped to the name and retrieves the Metadata from IPFS through Moralis' gateway on our IFrame src. Donations are made by sending Matic to the Contract address generated for the user for their project. see [Retrieve Ipfs Metadata to Iframe](https://github.com/Godhanded/Fund_Me-web3/blob/main/public/main.js#L238)
###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
  Yes
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
 AWe would hire more blockchain developers to our team to increase our work productivity as we are pushing our project to mainnet to enable donations in over 5 crypto currency’s, we would also do push marketing to announce our product in blockchain events,meet-ups and social media 

We plan to push this project further,and integrate some stacks we weren’t able to complete due to financial constraints for dev tools and more developers 

Firstly we propose to make withdrawals cross-chain after your fund raiser has ended so to enable users withdrawal their funds to any blockchain of their choice,this is to improve compatibility of thirdfund to all networks. -Support; we are working towards integrating a live chat support for users who wish to make inquiries or give feedback, we plan using Xmtp for this .

Improved algorithm and analytics that provides you with details like wallet addresses of your funders,time and location .

Backup wallet; incase you happen to loose your device or so,your backup wallet helps you get acess to your fundraiser page without you loosing a coin .

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period? 
 Yes 
  
### 6. Does your proposal comply with our Community Code of Conduct?
 Yes 

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 Only submitted for Moralis hackathon 
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Blockchain dev - Godhand, aezeigwe2003@gmail.com,@Godhanded
* Frontend Dev - Miracle EMENIKE, https://github.com/miraclemenikelechi
* Product manager - Eze JE, https://github.com/nuelvations
* How did you learn about our microgrant program? Mail
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) Moralis Filecoin hackathon 
  * Please link to your hackathon submission
https://docs.google.com/forms/d/e/1FAIpQLSfdhy1fYNUGWHSm4r20lubS-9M2GcWGEjhIV81llaEgSip2Pg/viewform

**Comment by ErinOCon** [comment]
Hi @nuelvations, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
