### ISSUE TITLE
Next Step Microgrant: pRoots-FVM-computegenomics

### ISSUE THREAD

**Issue by weitinglin** [filecoin-project/devgrants#1293]
![logo](https://camo.githubusercontent.com/d82c3cdc3426b373e9fd8e28a0e4453dc28aa196e191fc4a43d4453f11bccf92/68747470733a2f2f736864772d64726976652e67656e65737973676f2e6e65742f36575357344e3835507850554656726a4234317669636e355a715a525741345344757174637a416e6a744c412f6c6974746c652532304c4f474f2e706e67)
### 1. What is your project, and what problem does it solve? (max 100 words)
[pRoots](https://github.com/Proots-Foundation/proots-doc) **IPFS command line tool** is what we want to apply for the IPFS microgrant. pRoots is a desci project found from GR15. and we want to build web3 infrastructure on genomic data, currently focusing on plasmid data use case first.

In this microgrant application for FVM use cause, we want to develop **pRoots-FVM-computegenomics** module, which is still in a design phase.  Here is our current overall design in pRoots project:
![20221220 v1](https://camo.githubusercontent.com/ebd6c662658fc1ff7f6f9ca1ae4a2e038d57a46a5ecf3a1397e12804134a8864/68747470733a2f2f736864772d64726976652e67656e65737973676f2e6e65742f36575357344e3835507850554656726a4234317669636e355a715a525741345344757174637a416e6a744c412f7070745f626c75657072696e745f76312e706e67)
In our pRoots project, our main purpose is to enable people to upload, annotate, edit and share genomic data with web3 tools. One of the problems will be encountered is how to provide a data-driven way to valuation and index genomic data people share. Besides using on-chain social credit, we want to build a layer on FVM to compute on genomic data uploaded in IPFS network under DAG-PLASMID schema.

### 2. Project links
Overall pRoots github doc: [pRoots doc](https://github.com/Proots-Foundation/proots-doc) 
pRoots **FVM Genomics Compute** [repo](https://github.com/Proots-Foundation/proots-fvm-genomicscompute) 
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words) b) Is this project contributing to the upcoming FVM launch? 
pRoots is one of the first DeSci projects focused on proposing a IPLD schema for certain genomic data application. And we will also build the tools for people outside web3 can use to deal with their need for sharing, annotating genomic data(plasmid). Although FVM is still in development phase, but we want to use it for computing the data uploading under our DAG-PLASMID schema for advance data layout scenario.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
This microgrant will be used specifically on development and assessment of using FVM in pRoots project. We want to investigate the application of FVM in developing genomic data computing layer, which enable  a advanced data layout on genomic data.
- test the possibiligy of FVM computing capability and decide the intensity of computing work pRoots put on FVM. We will test the k-mer computation and phylogenicc calculation with FVM 
- figure out the possible FVM mechanism (seems to be just like EVM?) to implement our advance data layout design on DAG-PLASMID
- design the possible genomic data contract on FVM for data uploading in IPFS/Filecoin
- complete the v1 of repo on **FVM Genomics Compute** [repo](https://github.com/Proots-Foundation/proots-fvm-genomicscompute) 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, in our final report for this microgrant on using FVM for a computing data layer of pRoots infrastructure, we will provide the design thinking process of v1 **FVM Genomics Compute** [repo](https://github.com/Proots-Foundation/proots-fvm-genomicscompute). Make a possible advanced data layout through the implementation on our test dataset uploading through our proots-ipfs-cli.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Our project is also under the same scope with Community Codes of Conduct to Filecoin Code of Conduct.[Filecoin Code of Conduct](https://github.com/filecoin-project/community/blob/master/CODE_OF_CONDUCT.md) 

### 7. Links and submissions
We are referred to apply microgrant after winning [2022 gitcoin social hour hackathon](https://github.com/ipfs-and-filecoin/hackathons-bounties/issues/15).1st Runners up. We have proposed a microgran for pRoots IPFS cli tools recently in order to push our project further. [ipfs/devgrants #276](https://github.com/ipfs/devgrants/issues/276)

 pRoots found from [GR15](https://gitcoin.co/grants/7445/proots-empower-people-to-store-share-annotate-and). Below are our current team members and as our project grows more complex, we are also looking for people aligned for the desci direction in web3.
 - * [Weiting Lin](https://t.co/elU5wwOvpc)| email: [weitinglin66@gmail.com](mailto:weitinglin66@gmail.com) | github: https://github.com/weitinglin | bioinformatician
- * [Chitaolang](https://twitter.com/chitaolang) | email: [tingyilin91@gmail.com](mailto:tingyilin91@gmail.com) |github: https://github.com/chitaolang | blockchain engineering
-  * Social Hour Hackathon submission: [repo](https://github.com/Proots-Foundation/proots-client-v1), [gitcoin link](https://github.com/ipfs-and-filecoin/hackathons-bounties/issues/15)

**Comment by weitinglin** [comment]
Here is some additional information on what we need to use FVM for computing genomic data under DAG-PLASMID schema in IPFS/Filecoin.

![Advanced Data Layouts](https://shdw-drive.genesysgo.net/6WSW4N85PxPUFVrjB41vicn5ZqZRWA4SDuqtczAnjtLA/design_4v1.png)

we are thinking about whether there can be a FVM layer to do k-mer computation on the sequence data uploading. And by aggregating the k-mer meta data of the upload genomic data, we can further categorize the plasmid data into the grouped genomic knowledge graphs.

**Comment by ErinOCon** [comment]
Hi @weitinglin, thank you for your proposal and for your patience with our unexpectedly long review. While we will not be moving forward with a grant at this time, we are wishing you the best as you continue to build!

Thank you again for your interest in our grants program.
