### ISSUE TITLE
HashCase Grant Application

### ISSUE THREAD

**Issue by incepthink** [filecoin-project/devgrants#1296]
# Open Grant Proposal: `HashCase`

**Name of Project:** HashCase

**Proposal Category:** `app-dev`, `devtools-libraries`, `integration-adoption` 

**Proposer:** `@taahanizam`

**(Optional) Technical Sponsor:** `Piyush Maheshwari`, `@itsPiyushMaheshwari`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** Yes

# Project Description

Almost every major brand and organisation runs a ‘loyalty programme’. These are aimed at promoting customer loyalty and aiding in consumer retention. Over the last 4 years, there has been a significant trend in brands spending up to 75% of their marketing budget on customer retention, which is especially relevant to the luxury sector, which earns over 70% of its total revenue through repeat customers. 
Although intended, most loyalty programmes are ineffective and have been reduced to data collection strategies with discounts included. Over the last year, several global brands have found success by using NFTs to reward the community with loyalty programmes that they actually ‘own’. This presented a couple of unique challenges that impaired smaller brands from following suit: 1. Brands needed to have web3/NFT strategy and know-how and develop campaigns in-house. Larger brands solved this by hiring expensive agencies or acquiring smaller companies. 
2. Users needed to be web3 onboarded. Global brands have so many users that their web3 numbers were strong as well, so for the most part they were unaffected. 
 
HashCase aims to solve these problems by creating a no-code platform that allows brand managers to create, launch, and manage NFT collections, accompanied by a custodial wallet solution that enables users to log in via mobile or email authentication, thereby allowing users to engage with web3 assets without necessarily being web3 onboarded. 

## Value

Our current value is bringing true NFT utility and distribution capabilities to the Protocol Labs Ecosystem and, ultimately, the greater web3 ecosystem as well. Filecoin / IPFS is the best option to store NFT data in an immutable and decentralised method. While most brands have been using AWS solutions, Fliecoin IPFS offers speed and reliability and protects against future information loss. 
With a Blockchain agnostic and gasless platform like HashCase, brands, enterprises, and content creators can increase their reach across all existing web3 platforms. Our custodial wallet solution

## Deliverables

A no-code platform that allows you to launch an NFT collection, manage analytics, and create a customisable landing page. 

- Custodial wallet integration, accessible through email addresses
  - Logging in with your email should create a delegated wallet address for you, which is accessible through this email. You should have access to your wallet address and may proceed to store tokens and NFTs in it. 
- ‘My wallet’ section to view NFTs
  - A page that shows all your NFTs from all your wallets, ie. The one created by your email and any others that you would like to integrate
- Ability to add a decentralised wallet to your account
  - Allowing for the user to connect their decentralised account as well as the one created for their email, our platform will support: 
    - Metamask
    - Rainbow
    - Trust Wallet
    - Wallet Connect
    - Fantom and many more
- Gasless feature for free mint/claim
  - When we create a wallet for the user, it is empty. Having the gasless feature enables them to mint/claim NFTs without needing crypto for gas fees. 
- Gasless Transferability to external addresses
  - Ability to transfer/withdraw your NFTs to other wallet addresses
- Setting up individual profiles that are shareable 
  - Creating usernames in the backend, that allow people to create a profile with the following features: 
    - Username
    - Email address
    - Twitter/Instagram handle
    - Logo and Banner Image

This ensures that users can share their HashCase profiles which will display all their assets

- Building an e-commerce checkout for NFTs purchased that unlock physical merchandise
  - Creating a workflow that migrates an NFT from an initial ‘unclaimed’ state, to a final ‘claimed’ state. Doing so allows enterprises to sell limited edition products via NFTs that can be claimed for physical products. In doing so, the unclaimed NFT will be burned, and a claimed NFT will be minted in its place. 
- Integrating a FIAT on-ramp for payments
  - Enabling FIAT on-ramp so non-web3 users can pay with ease
- Creating a shareable API for brands to integrate on their platforms
  - Having an API key allows brands to customize their frontend while still being able to use our backend wallet functionality
- Building a suite of utility that can be integrated with the NFTs
  - Airdrops, raffles, NFT-based liquidity pools, voting, future mints and unlockables are among some of the utility that can be later integrated into the existing NFT campaigns.

## Development Roadmap
Each milestone implements the corresponding deliverables

|No. |Milestone Description|Est. Time|Funding Allocation (USD)|
| :- | :- | :- | :- |
||Custodial wallet with gasless minting/transfers, |1 month|10,000|
||Ability to add your own Metamask/Trust wallet/Wallet Connect etc. |1 week|N/A|
||My wallet, where you can view your NFTs|1 week|N/A|
||Setup of shareable profiles |2 weeks|10,000|
||Building e-commerce functionality|2 months|10,000|
||Integrating FIAT on-ramp|2 weeks|N/A|
||Creating a shareable API key for consumers|1 month|5,000|
||Enabling Multi-chain functionality|1 month|10,000|
||Building a suite of utility that can integrate with our NFTs|2 months|10,000|

## Total Budget Requested

$55,000 which includes a fully-decentralised custodial wallet solution with e-commerce capability, multi-chain integration, shareable profiles, and a suite of NFT utility that can be integrated with existing campaigns. 

## Maintenance and Upgrade Plans

We will continue to maintain and upgrade our existing solution, taking into account feedback and comments from the community. We also intend to create future functionality for erc 20 tokens, as well as metaverse use cases for our NFTs. 

# Team

## Team Members

- Taaha Nizam
- Alan Tom Jose
- Manan Shah Vyara
- Swayam Ranjan

## Team Member LinkedIn Profiles

<https://www.linkedin.com/in/taaha-nizam/>
<https://www.linkedin.com/in/alan-tom-jose-7665b3197/>
<https://www.linkedin.com/in/swayam-ranjan-8103b71b6/>
<https://www.linkedin.com/in/manan-m-shah/>

## Team Website

<https://hashcase.co/>

## Relevant Experience

HashCase is run by a team of driven engineers all based out of India. Over the past 2 years, we have worked directly with Blockchain foundations such as Polygon to develop their NFT ecosystem launching over 14 NFT-based projects and generating over 8 Million in revenue. 

## Team code repositories

<https://github.com/manan-m-shah/cricket-dao>
<https://github.com/manan-m-shah/leap-wallet-clone>
<https://github.com/manan-m-shah/code-share>
<https://github.com/manan-m-shah/warranty-nfts>
<https://github.com/incepthink/nftranking-engine-django>
<https://github.com/incepthink/Python-CLI-ranking>
<https://github.com/incepthink/hashCase-mobile-app>

# Additional Information
We learned about the grants programme by interacting with Juan Benet. Piyush Maheshwari and Niki Gokani at FIL Bangalore. 
Please feel free to reach out to us at taaha@hashcase.co

HashCase has received a grant from Polygon Studios as well. 

We would love to help build the multi-chain FileCoin ecosystem and add value to other projects building on it as well. We are keen on integrating our solution with FVM when ready. 

We would also love some introductions from the Filecoin team to relevant brands/enterprises who can use our solution and help get it market-validated.

**Comment by ErinOCon** [comment]
Hi @incepthink, thank you for your patience with our review! Unfortunately, we will not be moving forward with a grant at this time. For next steps, you may have an interest in checking out [accelerator opportunties](https://ecosystem-wg.notion.site/Protocol-Labs-Accelerator-Program-d45d8792a7d544eca9beb7d3e3d3b05d).
