### ISSUE TITLE
Next Step Microgrant: Make Existing IPFS Data Searchable with Subgraph on TalentLayer

### ISSUE THREAD

**Issue by KirstenPomales** [filecoin-project/devgrants#1297]
### 1. What is your project, and what problem does it solve? 
Today’s labor markets are siloed. These silos lead to low liquidity, segregated user reputation, and centralization of power in platforms. Users are forced to use many platforms because they can’t find enough work or people to hire on just one; think Upwork, Rappi, Thumbtack, Freelancer.com, Indeed.

Talentlayer is composable infrastructure for open labor markets.
- Interoperable backend and financial components for labor marketplace platforms
- Pooled liquidity for jobs and user
- A new economic model for marketplaces based on fee splitting

TalentLayer uses IPFS for all of our off-chain data storage. We're a 100% open-source protocol.

### 2. Project links
Core Github repo: https://github.com/TalentLayer
Demo DAPP Github repo: https://github.com/TalentLayer-Labs/indie-frontend
Demo: https://youtu.be/EAEbYyRAlsY
Website: https://talentlayer.org/
Twitter: https://twitter.com/talentlayer/
License: APACHE3

All of our code is currently licensed as APACHE3. For development done under this Microgrant, we are happy to license it as MIT or APACHE2.
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
TalentLayer uses IPFS for all of our off-chain data. Thanks to IPFS, we can store long text and large file data in a form that is highly available, decentralized, and cost-effective. We store a LOT of data on IPFS. 

Since TalentLayer is infrastructure for work marketplaces, we have a few different data structures relating to work; Platform ID, TalentLayer ID, Service, Proposal, Review. Each of these structures includes some on-chain metadata and some IPFS metadata. 

These metadata elements on IPFS are able to be displayed in any integrated platform’s frontends to create a clean user experience. The data we store on IPFS is essential to allowing interoperability between labor marketplaces; this is because any number of marketplaces can reference the data stored on IPFS via TalentLayer. 

For example, within a TalentLayer ID, the structure representing a user’s profile, the following info is pinned on IPFS. 

```title // a user's professional title (e.g. "developer", "creative marketing expert")
about // user's about me information
skills // user's skill keywords
timeZone //  user's time zone
headline // an introduction headline (e.g. "passionate developer looking for solidity opportunities")
country // country of residence of a user
picture // picture of a user
```
For a full list of metadata pieces stored on IPFS view our docs here: https://docs.talentlayer.org/technical-guides/page-5

### 3. b) Is this project contributing to the upcoming FVM launch? (Yes or No)
No.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective?
At TalentLayer we have a very pressing need to make our IPFS data searchable. We have an implementation plan for this and have already started with preparations.

#### Milestone A. $2,500 - Make IPFS Data Searchable with Subgraph
Timeline: January 2023

Issue: Right now our data stored on IPFS is not searchable. This is a big issue because we need to allow marketplace frontends to be able to filter, for example, by geo-location of a user, by keywords in a user's profile, or by time zone, (which would all require IPFS data to be searched).

Objective: Deploy a subgraph to index our IPFS data and allow marketplaces to search it. 

Steps:
- Scoping config for subgraph (Already in progress, have an open issue with The Graph team trying to resolve some errors)
- Deploy subgraph 
- Testing

#### Milestone B. $2,500 - Create Fork-Able Code Snips and How-To Guides for Searching TalentLayer IPFS Data
Timeline: February - March 2023

Issue: We don’t much have documentation or fork-able code to help marketplaces configure searches for on-chain and IPFS data. This is essential to building core functionality for marketplaces and must be well documented!

Objective: Create step-by-step guides for configuring searches on frontends for on-chain and IPFS data. 

Steps:
- Define the most common searches that marketplaces would want to do (profile filtering, job search, proposal search - sub-searches of each). 
- Make fork-able code snippets representing the structures of different queries and how to configure them - integrate these into our existing fork-able demo DAPP (https://docs.talentlayer.org/technical-guides/dapp-setup) 
- Write docs for these searches with the example code embedded (We’d try to follow the format of this example we made, only provide code snips on different configurations you can do: https://docs.talentlayer.org/technical-guides/how-to-guides/how-to-implement-minting-talentlayer-ids) 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?
Absolutely! We build in public and will be sharing reports not only with you but also with the world at large. 
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
_If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available._

IPFS Prize Submitted For - ETH CC - https://devpost.com/software/talentlayer-2bns5l

IPFS Prize Submitted For - ETH Berlin - https://devfolio.co/projects/talentlayer-universal-work-system-f410

We had two projects at ETH Lisbon, building generalized tools that we will use to improve our escrow and fees system, but are also generally applicable to other projects.

IPFS Prize Submitted For - ETH Lisbon team 1 - https://taikai.network/ethlisbon/hackathons/ethlisbon-2022/projects/cl9uh7tas22416501ttfhrydamq/idea

IPFS Prize Submitted For - ETH Lisbon team 2 - https://taikai.network/ethlisbon/hackathons/ethlisbon-2022/projects/cl9v709a3115498601tpgycvy82g/idea
  
### For each team member(s), please list name, email, Github account, and role in the project.
We have 15 active opensource contributors (mostly devs) that contribute each week. Out of that, we have 6 full-time core team members (listed below). 

Kirsten Pomales Langenbrunner, Executive Lead - [kirsten@talentlayer.org](mailto:kirsten@talentlayer.org)
https://github.com/KirstenPomales

Romain Martin, Technical Lead - [romain@talentlayer.org](mailto:romain@talentlayer.org)
https://github.com/0xromain

Martin Leclercq, Smart Contract Contributor - [martin@talentlayer.org](mailto:martin@talentlayer.org)
https://github.com/akugone

Quentin de Châteaubriant, Smart Contract and DAPP Contributor - [quentin@talentlayer.org](mailto:quentin@talentlayer.org)
https://github.com/quent043

Dercio H, DAPP Contributor -  vanish[@talentlayer.org](mailto:dercio@talentlayer.org)
https://github.com/CreedsCode

Emil Madrell, Smart Contract Contributor - [emil@talentlayer.org](mailto:emil@talentlayer.org) 
https://github.com/empaemanuel

### How did you learn about our microgrant program?
We’ve known about the program for a while and are excited to apply now that our Alpha is launched. 

### If your project was created as part of an event or hackathon, what was the name of the event? Please link to your hackathon submission.
We’re a full-time team, but we’ve also built out different components over many hackathons (opportunities to bring the team together to build!). We’ve worked on parts of TalentLayer at ETH Prague, ETH CC, ETH Berlin, ETH Lisbon.

ETH CC - https://devpost.com/software/talentlayer-2bns5l

ETH Berlin - https://devfolio.co/projects/talentlayer-universal-work-system-f410

ETH Prague - https://devpost.com/software/talentlayer?ref_content=my-projects-tab&ref_feature=my_projects

ETH Lisbon (we had two projects, building generalized tools that we will use to improve our escrow and fees system, but are also generally applicable to other projects). 

https://taikai.network/ethlisbon/hackathons/ethlisbon-2022/projects/cl9uh7tas22416501ttfhrydamq/idea

https://taikai.network/ethlisbon/hackathons/ethlisbon-2022/projects/cl9v709a3115498601tpgycvy82g/idea

**Comment by KirstenPomales** [comment]
Hey @ErinOCon :) Can you provide us more info on the review process for Microgrants and anything else would need from us? Cheers!

**Comment by ErinOCon** [comment]
Hi @KirstenPomales, thank you for your patience with our review. This microgrant has been approved! We will send an email to confirm payment details. Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). 

I would also like to make sure you are aware of the [PL Accelerator Program](https://ecosystem-wg.notion.site/Protocol-Labs-Accelerator-Program-d45d8792a7d544eca9beb7d3e3d3b05d). This could be a cool opportunity to explore as you continue to build!

**Comment by KirstenPomales** [comment]
**### TalentLayer Filecoin Micro Grant Progress Report**

**Documentation of IPFS Indexing via The Graph**
https://docs.talentlayer.org/technical-guides/graph-schema

**Subgraph Playground**
https://thegraph.com/hosted-service/subgraph/talentlayer/talent-layer-protocol

**IPFS Search-ability Update on Github - January 24th 2023**
https://github.com/TalentLayer/talentlayer-id-subgraph/pull/32
_*One small bug still present on indexing keyword data. All else working! It's aliveee!_
