### ISSUE TITLE
Next Step Microgrant: FILL Liquidity Pool for Storage Providers

### ISSUE THREAD

**Issue by robertl0705** [filecoin-project/devgrants#1302]
### 1. What is your project, and what problem does it solve? (max 100 words)

FILL is designed as a liquidity pool that will be implemented on FVM (Filecoin Virtual Machine) as a fully open-sourced, decentralized, algorithm-based lending platform. FILL facilitates a market for FIL token holders to deposit for passive income, and for SPs to borrow FIL cost-effectively for storage providing. 

Since Filecoin data is secured by pledge collaterals, it is necessary for SPs to pledge Filecoin tokens to the network. SPs are eager to borrow from service providers who own Filecoin tokens, however, the existing lending services usually require collaterals of other cryptocurrencies and charge high interest. 

### 2. Project links
  
Link to Github repo: https://github.com/orgs/FILL-Lab/repositories
Link to demo or website, if applicable: under construction, to be released
License: MIT, APACHE2
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

FILL does not require storage providers to collateralize Fiat currencies or other digital assets, instead, the storage providers’ existing account balance and future income would be organically acting as the collateral. Specifically, by taking over the storage provider’s Beneficiary Address, the potential income from storage mining is pledged by the protocol before the payback. 

The borrowing interest rate is not pre-defined or fixed, but dynamically adjusted naturally by the market condition, i.e., supply and demand. Entry barrier is significantly lowered not only for the SPs to borrow FIL for power growth, but also for FIL token holders to make deposit, regardless the amount of FIL committed.

FILL is expected be providing unprecedented liquidity in Filecoin market. It would also contribute the Filecoin ecosystem’s overarching goal of incentivizing a global network of computer operators to provide file sharing and storage services by enhancing the liquidity of FIL and further reducing the cost of storage power growth.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
 
Yes

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

This grant is mainly for the development of smart contract and user interface, trial on HyperSpace testnet, and later implementation on Filecoin mainnet when FVM M2.2 is launched. 

1.	Develop a smart contract to process the request for deposit, withdraw, borrowing and repayment. 
2.	Embed the model that determines the borrowing interest rate and the deposit benefit based on the market conditions into the smart contract. 
3.	Develop the collateralization and liquidation functionalities to ensure the security of the system.
4.	UI and UX design. 
5.	A prototype and a user interface website.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
Not for the moment, but will be willing to join a hackathon in next few months with the development of the project.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Yuebo Li - Yuebol0705@gmail.com, https://github.com/robertl0705, Co-Founder and Token-economics Scientist
John Yang - johnyxh21@gmail.com ,https://github.com/y-ang2010, Co-Founder and Full Stack Developer
Jinming Liu - jinming0603.lucky@gmail.com, https://github.com/ljinming, Co-Founder and Fount-end Developer

* How did you learn about our microgrant program?

From Space Wrap.

* If your project was created as part of an event or hackathon:

Yes.

  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  FVM SPACE WARP HACKATHON
  * Please link to your hackathon submission

**Comment by eshon** [comment]
@robertl0705 - This is a great use case but your organization and team have no prior Github history or work linked. Let us know if you can provide some work samples or please apply again in the future with more work samples!

**Comment by robertl0705** [comment]
> @robertl0705 - This is a great use case but your organization and team have no prior Github history or work linked. Let us know if you can provide some work samples or please apply again in the future with more work samples!

Hi Eva, Happy New Year and thanks for your response! I'm sorry that I forgot to link the GitHub repos for my team members, which is now added. However, the work history on the Github only represents part of our experience since many of our work history is not fully open sourced. Please let us know if you need more details and other supplemental materials regarding our development experience. Thanks a lot!

**Comment by ErinOCon** [comment]
Thanks, @robertl0705! It looks like the provided [project repo](https://github.com/orgs/FILL-Lab/repositories) does not have repositories that are open to the public. Since the open source component is an important criteria point, can this be updated? Please let me know if there is additional context to consider.

**Comment by robertl0705** [comment]
> Thanks, @robertl0705! It looks like the provided [project repo](https://github.com/orgs/FILL-Lab/repositories) does not have repositories that are open to the public. Since the open source component is an important criteria point, can this be updated? Please let me know if there is additional context to consider.

Hi Erin, yes we definitely will! Our project is also participating the Hackathon, which required us to start working on Jan 19. However, this week is the Chinese traditional holiday, Spring Festival. Team is spending time with family and working individually. We will coordinate and update the repositories in the next few days. Please let me know if there is a deadline that we need to make it public. Thanks for your understanding, wish you and Filecoin network a prosperous year of Rabbit!

**Comment by robertl0705** [comment]
> > Thanks, @robertl0705! It looks like the provided [project repo](https://github.com/orgs/FILL-Lab/repositories) does not have repositories that are open to the public. Since the open source component is an important criteria point, can this be updated? Please let me know if there is additional context to consider.
> 
> Hi Erin, yes we definitely will! Our project is also participating the Hackathon, which required us to start working on Jan 19. However, this week is the Chinese traditional holiday, Spring Festival. Team is spending time with family and working individually. We will coordinate and update the repositories in the next few days. Please let me know if there is a deadline that we need to make it public. Thanks for your understanding, wish you and Filecoin network a prosperous year of Rabbit!

Hi Erin, our repo has set to public.

**Comment by robertl0705** [comment]
@ErinOCon Hi Erin, is there still anything missing from the Microgrant being approved?

**Comment by robertl0705** [comment]
> Hi @robertl0705 - It looks like FILL won a $6k prize at the Space Warp Hackathon. Can you please provide a detailed update on what your team would add to the FILL project using this microgrant?
> 
> Note that unless your workplan is really compelling, we are less likely to give prize winners additional microgrants. We seek your understanding to allow other teams to receive funding support as well!

Hi @ErinOCon thanks for your prompt response! I agree, being more inclusive and supportive is the best way to build the ecosystem.
