### ISSUE TITLE
Next Step Microgrant: <Gideon>

### ISSUE THREAD

**Issue by GideonAssociation** [filecoin-project/devgrants#1303]
### 1. What is your project, and what problem does it solve? (max 100 words)

Our project is Gideon, a decentralized voting and streaming platform for the battery rap industry. The problem we solved for the battle rap industry was introducing an encrypted voting mechanism that would ensure fair voting outcomes. This gives the sport credibility as a mainstream form of competitive entertainment as well as enabling new sectors such as fantasy gaming and betting to emerge from these trusted statistics. 

### 2. Project links
  
Link to Github repo:

https://github.com/GideonAssociation

Link to demo or website, if applicable:

https://www.figma.com/proto/ke1gjWSQR4M446ixf3mT2g/Gideon?node-id=7788%3A66498&scaling=min-zoom

License:

  
###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)

We use IPFS in our project to store our videos, images of our merchandise sold via our in-app shopping portal, as well as NFTs that will be used for We use IPFS in our project to store our videos, images of our merchandise sold via our in-app shopping portal, as well as NFTs that will be used for the fantasy gaming aspect fantasy gaming aspect. All of these items can be retrieved upon request via API access from within our application. Yes, we do plan to contribute to the upcoming FVM launch. 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We intend to use this microgrant to complete all of the necessary back end development for the first version of our application. This microgrant will enable us to go from the prototype stage and our back end code, to launching our first public version of our application. 

1. Find a work-for-hire back end developer to program the necessary functions for the web3 side of the platform. 
2. Find a work-for-hire front end developer to program a functioning version of our Figma MVP.
3. Coordinate the front end and back end devs to sync the code.
4. Gather a focus group to test the application.
5. Make any necessary updates to the code and prepare for a public launch by Q2 2023.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
<!-- Report content may include progress or results of your microgrant-funded work, any Filecoin technical or usage guidance requests, and a description of your experience building on Filecoin, including any challenges or shortcomings encountered. →

Yes. 
  
### 6. Does your proposal comply with our Community Code of Conduct?
<!-- Please read the [Filecoin Code of Conduct](https://github.com/filecoin-project/community/blob/master/CODE_OF_CONDUCT.md) and make sure your project is in compliance →

Yes. 

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Jahmeke Rodriquez: Founder/CEO
rodriquezjah@gmail.com

* How did you learn about our microgrant program?

We learned about it through a previous hackathon where we won $500 from Filecoin. 

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @GideonAssociation, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
