### ISSUE TITLE
Next Step Microgrant - <FEVM Development Tools>

### ISSUE THREAD

**Issue by awesome-fvm** [filecoin-project/devgrants#1304]
### 1. What is your project, and what problem does it solve? (max 100 words)

This microgrant proposal contains 3 tools (and corresponding repositories) which can immensely help developer adoption for FEVM and improve Developer Experience.

1. **NextJS-Hardhat-FVM-Starter** - This is a tool that helps developers quickly set up a full-stack project on the FVM. It combines the NextJS framework for the front-end with various tools like web3modal, rainbowkit, and wagmi that are configured to work seamlessly with FEVM, and uses the Hardhat starter kit from FEVM as the backend. This mono-repo architecture allows developers to save time setting up their codebase and get started with development quickly. The tool also includes relevant tests for the starter kit.
The link for the same - [https://github.com/awesome-fvm/fevm-nextjs-hardhat-kit](https://github.com/awesome-fvm/fevm-nextjs-hardhat-kit)
2. **FEVM-Foundry-Starter** - Foundry is a blazing fast, portable and modular toolkit for Ethereum application development written in Rust. We have configured Foundry to work with FEVM by including all the relevant mocks and scripts, as well as relevant test cases in Solidity. 
Foundry is one of the most popular tools in the EVM ecosystem and this starter kit helps bring that experience to developers of FEVM as well. 
The link for the same - [https://github.com/awesome-fvm/fevm-foundry-kit](https://github.com/awesome-fvm/fevm-foundry-kit)
3. **Awesome FVM** - An open source / collaborative collection of resources required for building on FVM and FEVM, which can help new developers and builders get access to all the existing tools in the FEVM ecosystem. 
By being open sourced, anyone can update the repository with their own tools/softwares and find discoverability in the ecosystem. This is a ubiquitous standard across all major developer ecosystems.
(We have taken inspiration from `awesome-react`, `awesome-ethereum` and `awesome-ipfs`for the creation of this repository.)
The link can be found here - [https://github.com/awesome-fvm/awesome-fvm](https://github.com/awesome-fvm/awesome-fvm)

### 2. Project links

Link to Github repo: [https://github.com/awesome-fvm](https://github.com/awesome-fvm)
Link to demo or website, if applicable: [https://youtu.be/-X-xF6pKfok](https://youtu.be/-X-xF6pKfok) (Video walkthrough)
License: Everything is open source and MIT

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

- FEVM-Foundry-Starter - Custom solidity configs included in this helps developers to deploy on the Filecoin Wallaby Testnet using tools like Forge and Anvil.
- NextJS-Hardhat-FVM-Starter - Custom Configs using well known packages like Rainbow Kit helps developers build full stack applications on FEVM.
- We are building these tools for Filecoin and FVM to help drive adoption to the ecosystem. We believe that tools like this will make development much easier for developers who are exploring FEVM for the first time. We will continue to maintain these repositories, as well as add any recommended / relevant developers are maintainers to get progress quicker.

### b) Is this project contributing to the upcoming FVM launch? (Yes or No) - 
Yes

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We would like to build the following:

1. Curate a list of example projects on which implements various FVM actor API’s in the smart contracts to help new devs get up to speed quickly. 
2. Add more maintainers to the awesome-fvm repository and automate evaluation of PR’s such that merging new pull requests is easier and quicker by using Jenkins.
3. Create a NPM package which can create a new FVM Foundry / FVM-Hardhat Starter with various configs like:
    1. Example repos
    2. JS vs TS selection
    3. Foundry vs Hardhat Selection
    4. Different FVM actor api example selection
4. Continue to create more tools to help building on FEVM better.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes we do

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions

- If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

### Additional questions:

- For each team member(s), please list name, email, Github account, and role in the project.
Nikhil Thakur
awesomefvm@gmail.com
https://github.com/awesome-fvm

- How did you learn about our microgrant program? Filecoin Spacewarp Program
- If your project was created as part of an event or hackathon:
    - What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
    - Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @awesome-fvm, thank you for your proposal and for your patience with our unexpectedly long review process. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
