### ISSUE TITLE
Next Step Microgrant: integration of Filecoin into Anita, a Decentralized Data Management Solution

### ISSUE THREAD

**Issue by ilDon** [filecoin-project/devgrants#1306]
### 1. What is your project, and what problem does it solve? (max 100 words)

Anita is a private, no-server data management solution to track and organize any data in a customizable and user-friendly way. 
Built as a PWA with open technologies, Anita stores all data on the user's machine using IndexedDB, JSON files, or SQLite databases (wasm), accessed through the FileSystemAccess APIs.
Anita has a modular design which allows for integration with other technologies to extend storage options and enable syncing between devices. Currently, there is a beta version of a Dropbox integration, and the next logical step would be integrating with Filecoin to provide a decentralized and secure storage solution.

### 2. Project links
  
Link to Github repo: https://github.com/anita-app/anita
Link to demo or website, if applicable: https://anita-app.com/
License: current license CC-BY-NC-4.0, as specified in package.json (https://github.com/anita-app/anita/blob/main/package.json). If this is incompatible with the grant, I'm willing to adopt the CC-BY-SA 3.0 license or the MIT should you fund the project.

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

The integration of Filecoin into Anita would provide users with a decentralized storage option for their data. With this new module, users would have the ability to save their data on the Filecoin network, taking advantage of its decentralized nature and increasing the security and privacy of their data.
Using the Filecoin module, users would simply have to select the option to save their data on Filecoin when creating or updating a record in Anita. Behind the scenes, the module would handle the process of adding the data to Filecoin and returning the unique Filecoin hash for the data. This hash could then be stored within Anita along with the rest of the data, allowing for easy retrieval and access to the data on the Filecoin network.
In addition to providing users with a decentralized storage option, the integration of Filecoin into Anita would also allow for seamless synchronization across multiple devices. As the data is stored on the Filecoin network, it can easily be accessed from any device with an internet connection. This would make it convenient for users to access and update their data from anywhere, at any time.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)

While Anita itself would not directly contribute to the FVM, the integration of IPFS into Anita could potentially be further developed to extend its capabilities. For example, the IPFS module could be enhanced to allow users to store and retrieve data using smart contracts on the FVM. This could potentially provide even more flexibility and functionality for users, allowing them to automate certain processes or create custom rules for data storage and access.
 
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The integration of Filecoin into Anita would greatly improve the application by providing users with a decentralized storage option for their data. This new module would fit seamlessly into the current architecture, allowing users to easily switch between storing their data on Filecoin or on their local machine.
The next steps for creating a new module to store data on Filecoin would involve utilizing the Filecoin JavaScript library to handle the process of adding and retrieving data from the Filecoin network. This would involve the use of functions to create a deal and then send the data, and store locally the deal info to later retrieve the data.
One of the key benefits of this new module is that data synchronization and conflict resolution is already solved within the current architecture of Anita. This means that users will not have to worry about managing their data across multiple devices or resolving any conflicts that may arise.
The new Filecoin module will provide users with a storage decentralized option for storing their data, therefore increasing the security and privacy of their data. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, I agree to share grant reports upon request, including a final grant report at the end of the three month period. In addition, I plan to release tech and non-tech blog posts on the implementation of the Filecoin module on the Anita blog (https://anita-app.com/blog/). These blog posts will provide detailed information on the process of integrating Filecoin into Anita, including any challenges and solutions encountered along the way. They will also provide insight into the benefits of using Filecoin for data storage and how it fits into the overall architecture of Anita.
 
### 6. Does your proposal comply with our Community Code of Conduct?

Yes, my proposal and the Anita project fully comply with your Community Code of Conduct

### 7. Links and submissions

No, Anita did not begin at a hackathon.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  * Don gerrard, don.gerrard at outlook dot com, Github @ilDon, founder and unique contributor (for now)
* How did you learn about our microgrant program?
  * I was looking for developer resources to build the integration of IPFS into Anita and came across the microgrant program
* If your project was created as part of an event or hackathon:
  * n/a

**Comment by ErinOCon** [comment]
Hi @ilDon, thank you for your proposal! We will not be moving forward with a grant at this time, but I would like to make sure you're aware of the upcoming [FVM Space Warp Hackathon](https://ethglobal.com/events/spacewarp). Wishing you the best as you continue building!
