### ISSUE TITLE
Next Step Microgrant: Web3 email Eppie

### ISSUE THREAD

**Issue by ValeraFinebits** [filecoin-project/devgrants#1307]
### 1. What is your project, and what problem does it solve? (max 100 words)
We think than Internet users have effectively lost their privacy. Every bit of private data is being stolen and listed for sale by criminals, as well as legally analyzed and used for profit by anyone willing to spend money for targeted ads.

Eppie is a decentralized encrypted email. It allows users of classic centralized email (such as Google, Hotmail, etc.) with their existing Web2 addresses easily migrate to decentralized protected Web3 email.  

Eppie encrypts all the mail, attachments, contacts, and personal information, then breaks the encrypted data into fragments and, finally, distributes them within a decentralized network in such a way that it cannot be accessed by anyone except for the owner. With no additional effort required from the user.

### 2. Project links
  
Link to Github repo: 
https://github.com/Eppie-io
Link to demo or website, if applicable: 
https://eppie.io/
https://youtu.be/j2hUnNSEOEI
License: 
APACHE2
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
We want to use IPFS to store Eppie's users backup. Decentralized storage is free from intermediaries. 

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
No

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Storing user data in a distributed network IPFS combined with encryption, will allow us to create an email service that protects sensitive users data that stores in email.

Steps:
1. Setting up and running IPFS nodes.
2. Creation of a service for storing user backups in IPFS.
3. Integration of this service into Eppie.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
No
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Valera – developer
valera@finebits.com
https://github.com/ValeraFinebits

* How did you learn about our microgrant program? 
https://twitter.com/Filecoin

**Comment by ErinOCon** [comment]
Hi @ValeraFinebits, thank you for your proposal! We will not be proceeding with a grant at this time. For next steps, I would recommend reviewing our upcoming [hackathon opportunities](https://hackathons.filecoin.io/).

Wishing you the best as you continue to build!
