### ISSUE TITLE
Open Grant Proposal: Spear

### ISSUE THREAD

**Issue by 41hulk** [filecoin-project/devgrants#1309]
# Open Grant Proposal: Spear

**Name of Project:** Spear

**Proposal Category:** `app-dev'

**Proposer:** 41hulk

**(Optional) Technical Sponsor:** n/a

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** "Yes"

# Project Description

Sometimes accessing financial services like Loans and mortgages all around the world becomes more and more difficult sometimes due to unfair, origin, location, and predatory lending practices. When you are eligible for those services(Loan and mortgage) it takes months to get access to funds with high-interest rates due to system lags and old-fashioned lending systems.

According to [Bloomberg](https://www.bloomberg.com/news/articles/2013-08-16/the-dramatic-racial-bias-of-subprime-lending-during-the-housing-boom)
In 2006, at the height of the boom, black and Hispanic families making more than $200,000 a year were more likely on average to be given a subprime loan than white families making less than $30,000 a year.

Post-Covid, 3.4% of white homeowners in New York said they were very likely to leave their homes due to foreclosure in the next two months compared to, 9.4% of Black homeowners, according to a recent [U.S. Census](https://www.census.gov/programs-surveys/household-pulse-survey/data.html).

SPEAR is a mobile app that provides decentralized private loans and mortgage services to low-income earners and underrepresented groups/communities without borders.

Where a loan seeker applies to different low-interest loan plans and we fund those loan plans with our fractionalized NFTs collectibles where a holder of an NFT is an investor and that NFT gives you a Return On Investment(monthly or yearly)

## Value

IPFS can play a key role by storing important financial data and NFTs metadata making SPEAR more trustworthy and accessible for Loan seekers and Investors.

Risks if we don't get this right:
- Inability to handle a high amount in loan origination
- Possible losses due to market fluctuations, especially during bear market

Execution risk:
- Data collected from loan seekers may be insufficient to grant a loan

## Deliverables

There will be a native mobile app as a final deliverable

A User is able to signup/sign in and connects with a wallet as an investor or loan seeker. 

As an Investor, you are able to navigate through different NFT collectibles and bid your share as an investor, view NFTs you are holding with statistics on your returns and monthly income.

As a Loan seeker, you are able to navigate through loan plans available, view loan and mortgage application status when approved you are able to view payment plans in your portfolio section

<img width="1023" alt="portfolio" src="https://user-images.githubusercontent.com/40362530/210117351-ff976a87-0685-479d-a2f5-6fcd7dc65e5f.png">
<img width="887" alt="market" src="https://user-images.githubusercontent.com/40362530/210120766-d95588b3-d272-4ebe-9151-58320d9327fb.png">

## Development Roadmap

|     | Milestone 0 (Pilot) |
| ----------- | ----------- |
| -  | Spear app wireframe(Design document)|
| -  |  Spear use case diagrams(Design document) |
| -  | Spear functional requirements Document(document) |
| - | Test guide: In the guide, we will describe how to run tests to ensure functionality and robustness |

**Milestone 0 estimated Time**: 8 weeks (Jan 2023 - Feb 2023)
-  1 Tech Lead($5000/month)*2 = $10000 
-  1 UX designer($4000/month)*2= $8000
-  1 Project Manager( $6000/month )*2 = $12000
-  1 Business development associate($4000/month)*2 = $8000

**Milestone 0 Total Fund:** $38000

|     | Milestone 1 (Investor NFT marketplace) |
| ----------- | ----------- |
| -  | Setup a Development Environment(Kanban board, Apple Store and Playstore Store, Etc|
| -  |   Re-visit UX designs and user flow |
| - | Implement Normal authentication flow(connect wallet, login, register, etc)|
| - | Ability to view NFT collectibles available |
| - | Ability to view NFT details (interest, monthly income, etc) | 
| - | Ability to purchase fractionalized NFT using a wallet |
| - | Ability to view Spear NFT a user holds on their wallets |
| - | Ability to withdraw funds to your favorite wallet |
| - | Unit testing |

 
**Milestone 1 estimated Time**: 12 weeks (March 2023 - May 2023)
- 1 Tech Lead($5000/month)*3 = $15000 
-  1 Project Manager( $6000/month )*3 = $18000
-  1 UX designer($4000/month)*3= $12000
-  1 Front-end Engineer ($3500/month)*3= $10500
- 1 Back-end Engineer($3500/month)*3= $10500
- 1 Business development associate($4000/month)*3 = $12000

**Milestone 1 Total Fund:** $78000

|     | Milestone 2 (Loan Seeker) |
| ----------- | ----------- |
| -  | Ability to view available loans plans and categorize |
| -  | Ability to view loan plans details(interest rate, repayment terms,etc)|
| -  | Ability to submit documents and data for loan requests |
| -  | Ability to see loan application statuses  |
| -  | Ability to view credit scores| 
| -  | Ability to select payment methods|
| -  | Ability to view details of granted loans (Current payoffs, next payment, etc) |
| - |  Ability to withdraw funds to your favorite wallet |
| -  | Unit testing |

**Milestone 2 estimated Time**: 12 weeks (June 2023 - August 2023)
-  1 Tech Lead($5000/month)*3 = $15000 
-  1 Project Manager( $6000/month )*3 = $18000
-  1 UX designer($4000/month)*3= $12000
-  1 Front-end Engineer ($3500/month)*3= $10500
-  1 Back-end Engineer($3500/month)*3= $10500
-  1 Business development associate($4000/month)*3 = $12000

**Milestone 2 Total Fund:** $78000

## Total Budget Requested
Milestone 0: $38000<br>
Milestone 1: $78000 <br> 
Milestone 2: $78000

**Other**

Deployment cost: $2000(e.g.transaction fee) <br> 
Legal&compliance consultant: $6000 <br>
Security Audit: $12000<br>
Travel, Conference: $15000 (e.g. DEVCON2023, ETHConferences)

**Total Fund**: $229,000

## Maintenance and Upgrade Plans

I am committed to maintaining the development of the project.
- Design improvements according to user feedback
- Spear Multi-chain 

# Team
Founder
Guy E. Ntare<br>
https://www.linkedin.com/in/ntare-guy/<br>
https://github.com/41hulk

## Relevant Experience

I've been involved in web3 From hackathons to working on real-world dApps, I worked with ETHGlobal as a support staff for their hackathons, as well as providing general support to their team and also participated in their hackathons like HackFs2022, ETHOnline which gave me a holistic view 

I worked in web2 as a Mobile developer(Flutter) contractor until I migrated to web3 full-time.
I was a Blockchain Engineer at Minority Programmers Association building Genedrop a no-code solution for artists to create, mint, and sell their generative art as NFTs across multiple blockchains. 

## Team code repositories
https://github.com/SpearFi

# Additional Information
How did you learn about the Open Grants Program?: **Past Grantee**

 Please provide the best email address for discussing the grant agreement and general next steps: gntare2@gmail.com

**Comment by realChainLife** [comment]
Hi @41hulk thank you for the proposal however we will not be funding the work outlined here. We'd be happy to eval a smaller scope proposal, for instance a [microgrant](https://github.com/filecoin-project/devgrants/blob/master/microgrants/microgrants.md) proposal that focuses on the development of these smart contracts / NFT functionalities on FEVM. You can read more our SpaceWarp opportunities [here](https://spacewarp.fvm.dev/).

**Comment by 41hulk** [comment]
Thanks @realChainLife I just submitted a Microgrant at #1403 to develop the NFT functionalities and smart contract on FEVM. I also applied for the Impact Evaluator Round 2.

Thanks again for the support
