### ISSUE TITLE
Next Step Microgrant: web3turkiye.com community

### ISSUE THREAD

**Issue by umutcanli** [filecoin-project/devgrants#1310]
### 1. What is your project, and what problem does it solve? (max 100 words)
I am the owner of the web3turkiye.com domain name and I am a software startup owner. I aim to establish a forum for the development of this field in my country.

### 2. Project links
  
Link to Github repo: https://github.com/umutcanli/web3tr
Link to demo or website, if applicable:
License: MIT 

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
I made a very simple prototype for now, but if I get a grant, I will host especially the media data inside ipfs. Apart from that, I am sure that I will reach at least 8000 developers in my country about Filecoin.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
  yes
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
First of all, I will provide front end developments and web3.storage link for the project, then I want to organize at least 2 panels in the web3 storage (ipfs) field in universities in my country. I think we will exceed 500 members in the first month after broadcast

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project. now just i am. 
* How did you learn about our microgrant program? - my friends told.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @umutcanli, thank you for your proposal! We will not be moving forward with a microgrant at this time, but encourage you to check out [hackathon opportunities](https://hackathons.filecoin.io/)!

Wishing you the best as you continue to build!
