### ISSUE TITLE
WEB3DEV: Grow Filecoin in Latin America

### ISSUE THREAD

**Issue by danicuki** [filecoin-project/devgrants#1311]
# Open Grant Proposal: `WEB3DEV: Grow Filecoin in Latin America`

**Name of Project:** WEB3DEV

**Proposal Category:**  `community`

**Proposer:** `danicuki`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** YES

# Project Description

WEB3DEV is the largest and most engaged web3 developers community in LATAM. We already had an [approved grant from Filecoin](https://github.com/filecoin-project/devgrants/issues/629). It was a success for both Filecoin and our community. WEB3DEV community members were very engaged and delivered all the promised milestones for this grant and would like to double click on this partnership.

Since then, our Discord grew from 1800 to 4600 developers: https://bit.ly/w3b3d3v, our technical content YouTube channel has more than 1,000 subscribers, our website grew to 5,000 MAU. It is a big audience, but not even close to what it can reach in 2023. We estimate there are more than 4 million developers in Latin America, most of them working with web2 technologies. We want to help this huge audience to learn and start building on web3.

## Value

As we stated in the first grant proposal, there are thousands of great developers in Latina America eager to get into Filecoin, but English-only content is still a limitation. We engage people to translate English content and also produce original content for specific blockchains.

With the previous approved grant, we were able to create 15 articles and 15 videos. With this creation, we reached 3,060 plays,  178.7 hours of watched content, and 4,200 page views. Our estimate is that we reached 2,000 developers with this content. 

Here is a table with previous grant results:
![Screen Shot 2023-01-02 at 12 09 52](https://user-images.githubusercontent.com/77552/210249499-4b6aaea6-fab7-431a-8da3-96acdefb3394.png)

Now we want to go even further and reach much more people with new content, not only in Portuguese, but now also in Spanish, reaching even more developers.

## Deliverables

We expect to have 30,000 developers in our community by the end of 2023. We expect to reach at least 4,000 with specific filecoin and libp2p ecosystem content, some of them being able to work and deliver value on real projects in the Filecoin ecosystem.

6 months of ongoing technical content creation in Portuguese and Spanish:
- 30 videos - 5 per month, 6 months to produce, publish and advertise
- 30 text articles - 5 per month, 6 months to produce, publish and advertise

### Milestone 1

- coordinator allocation and setup: $3,000 
- 10 videos: $3,500
- 10 articles: $2000

### Milestone 2

- 10 videos: $3,500
- 10 articles: $2000

### Milestone 3

- 10 videos: $3,500
- 10 articles: $2000

## Total Budget Requested

- $10,500 for 30 videos (cost per video: $350)
- $6,000 for 30 articles (cost per article: $200)
- $3,000 for editorial and publishing coordination

Total **$19,500**

## Maintenance and Upgrade Plans

We can continue to generate high quality content for filecoin on a monthly basis. Our next step could be to help Filecoin to run Launchpad in our region. Our course platform is 100% open source and we already have 3,550 developers subscribed to Solidity and Solana bootcamps. 

# Team

## Team Members

- Daniel Cukier: PhD in CS, developer since 1995, In Crypto since 2020, Founder of Playax, CTO of Elo7, CTO of Pravaler
Twitter: https://www.twitter.com/danicuki
- Yan Luiz: Developer since 2014, in Crypto since 2016, Youtuber, Solidity Teacher, Blockchain Developer - https://www.linkedin.com/in/yanluiz/
- Melk, In crypto since 2015
Founder of web3dev, developer and entrepreneur
http://github.com/web3melk

## Team Member LinkedIn Profiles
- https://www.linkedin.com/in/danielcukier/
- https://www.linkedin.com/in/yanluiz/

## Team Website

https://www.web3dev.com.br
https://bootcamp.web3dev.com.br

## Relevant Experience

I am a technology innovator, working with web3 projects in the last 2 years. Former CTO in Brazilian startups such as Pravaler - a fintech that offers accessible student loans - also founder and CTO at Playax - an audience development platform for music professionals based on BigData - also worked for two years as CTO at Elo7 – the biggest crafts marketplace in Brazil.

Experienced working in different programming languages such as Elixir, Ruby, JavaScript and Java, I helped many startups as venture advisor at Monashees Capital and other accelerator programs in Brazil. I am also PhD in Computer Science at University of São Paulo – IME-USP. My PhD research is about Software Startups Ecosystems and Entrepreneurship.

I mastered in Computer Science in University of São Paulo in 2009, with the Thesis Patterns for Introducing New Ideas in the Software Industry. Daniel is a Cloud Computing GDE (Google Developer Expert). I started developing software in Brazil when he was 10, on his TK-3000 Basic 2MB RAM computer.

## Team code repositories

- https://github.com/w3b3d3v
- https://github.com/w3b3d3v/web3-bootcamp-platform

# Additional Information
- 4,500 developers in our Discord Server
- 5,400 [bootcamp](https://bootcamp.web3dev.com.br) subscriptions - more than 100 graduated
- [Bootcamp LMS platform open sourced](https://github.com/w3b3d3v/web3-bootcamp-platform) 
- 637 published articles [our website](https://www.web3dev.com.br)
- ~1,400 page views / day in our website.

**Comment by ErinOCon** [comment]
Hi @danicuki, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!

**Comment by danicuki** [comment]
Thanks @ErinOCon for the update. It would be nice to have a feedback about the reasons you don't consider our proposal a good one. It will help us to get better.
