### ISSUE TITLE
IPFS (Filebase, Pinata, Fleek, Web3, Lighthouse) storage adapter for Ghost

### ISSUE THREAD

**Issue by alexbakers** [filecoin-project/devgrants#1313]
<img alt="ghost-ipfs" src="https://raw.githubusercontent.com/alexbakers/ghost-ipfs/main/public/banner.png" />

### 1. What is your project, and what problem does it solve? (max 100 words)
:point_right: [Ghost-IPFS](https://github.com/alexbakers/ghost-ipfs) is an open source and widely tested storage adapter for IPFS (Filebase, Pinata, Fleek, Web3, Lighthouse) with a comprehensive setup guide.

*[Ghost](https://github.com/TryGhost/Ghost) [**42.1k** ⭐️] is one of the most popular headless CMS.

### 2. Project links
  
Link to Github repo: https://github.com/alexbakers/ghost-ipfs
License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
A custom storage adapter allows Ghost to upload and serve images directly to/from external services like Filebase, Pinata, Fleek, Web3, Lighthouse. Once you have deployed your storage adapter, you can use the Filebase, Pinata, Fleek, Web3, Lighthouse media library interface to manage the images and assets on your Ghost site.
###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- [ ] Submit a request to add the adapter to the [Ghost Marketplace](https://ghost.org/integrations/?tag=storage).
- [ ] Adapting the project to the new version of Fleek.xyz
- [ ] Adding new IPFS storages, primarily Infura.
- [x] [Adding new IPFS storages, Lighthouse](https://github.com/alexbakers/ghost-ipfs/commit/8aeba5b541cfedd36c2e39e6a344fe6231be0a44).
- [ ] Support for Pinata, Web3, Filebase storage.
- [ ] Writing neat code in a single style according to certain rules (eslint).

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
All the work done can be seen in future project commits.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
No
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
[Alex Baker](https://github.com/alexbakers), alex.baker.fon[at]gmail.com
* How did you learn about our microgrant program?
I was advised to apply for a grant by one of your employees.
* If your project was created as part of an event or hackathon:
No.

**Comment by eshon** [comment]
Hi @alexbakers - What would be the FVM component of this project? (Question 3b)

**Comment by alexbakers** [comment]
> Hi @alexbakers - What would be the FVM component of this project? (Question 3b)

Hello, @eshon.

I'm sorry if I misunderstood the question.
I wasn't thinking about "using" but about "contributing". The more Ghost developers will use IPFS/Filecoin, the more of them will be interested in FVM technology.
The project uses IPFS/Filecoin.

PS: However, when it comes to using FVM, I'm looking forward to a full launch, when I can use my own WASM actors. There are some ideas for use.

**Comment by eshon** [comment]
Hi @alexbakers - This is a nice project but it's not in the scope of our current FVM Microgrants round for projects that leverage FVM.

What would be nice is if you were to explore a new adapter that integrated something like [Lighthouse.storage's access control](https://docs.lighthouse.storage/lighthouse-1/lighthouse-sdk/code-examples/access-conditions) and then worked with us to build a nice website using this to provide gated access to a subset of FVM users (we could airdrop NFTs to everyone who attended some event, for example).

But essentially for this round we're looking for project ideas that experiment with the new EVM-compatible FVM.
