### ISSUE TITLE
Next Step Microgrant: zkFil: A decentralized system for data exchange based on Filecoin

### ISSUE THREAD

**Issue by xuxinlai2002** [filecoin-project/devgrants#1314]
### 1. What is your project, and what problem does it solve? (max 100 words)
zkFil is a decentralized platform for data exchange between *untrusted parties* realizing "Payment on Delivery" without any *trusted third party* based on filecoin storage network. 

The protocol is based on zero-knowledge(zk-SNARK) to ensure safety.

The project consists of 3 parts:
1. zkFil-node
2. zkFil-lib
3. zkFil-contract
<p align="center"> <img src="https://raw.githubusercontent.com/xuxinlai2002/zkFil/main/img/overview.png"> </p>

### 2. Project links
  
Link to Github repo:https://github.com/xuxinlai2002/zkFil
Link to demo or website, if applicable:
License:MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
+ zkFil uses smart contracts on FEVM/FVM as the trustless third party.
+ This project uses FVM/FEVM token to exchange data
+ Encrypted data is stored on IPFS
+ This protocol can be used as layer2 of the Filecoin network to process various transactions

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No) 
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
+ Improve the logic of the contract layer (including FVM/FEVM), support on-demand download of verifiers and verify authenticators using Merkle proofs
+  Supports delivering large data file within one transaction.
+ Support Claims or Refunds mode, increasing the versatility of the system
+ Optimize zkSNARK work so as to increase the throughput of data by 2-3 orders of magnitude.
+ Build a general layer2 based on filecoin

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
YES
  
### 6. Does your proposal comply with our Community Code of Conduct?
YES

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
navid  xuxinlai2002               contract developer
smile   Wangxiaolei123456   algorithm engineer
jimmy  jimmy668                    test Engineer

* How did you learn about our microgrant program?
from friends

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by eshon** [comment]
@xuxinlai2002 - Is it possible for this project to use Lurk on FVM in the future? More info about Lurk: https://github.com/filecoin-project/devgrants/issues/808

**Comment by xuxinlai2002** [comment]
Yes, we will use Lurk on FVM in this project. Because Lurk can support zk-SNARKs very well and is Turing complete, it should be of great help to our project.

**Comment by ErinOCon** [comment]
Hi @xuxinlai2002, thank you for your proposal. We will not be proceeding with a grant at this time. Wishing you the best as you continue building!
