### ISSUE TITLE
Next Step Microgrant: Decentralized QR Codes Hosting Service

### ISSUE THREAD

**Issue by legut2** [filecoin-project/devgrants#1315]
### 1. What is your project, and what problem does it solve? (max 100 words)
I would like to make a decentralized QR code solution that is hosted on filecoin that anyone can use. The files stored would be images of the QR codes themselves. The funding would go towards developer time. I would include a way to make people's faces into QR codes but that portion will not be open source.

### 2. Project links
  
Link to Github repo: N/A
Link to demo or website, if applicable: [Upload a 400x400px profile picture here and watch it turn into a QR code 30 seconds later.](https://jsbin.com/dalukamobi/edit?html,output)
License: Apache 2.0
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
I will be making filecoin be the hosting for the image files themselves.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
It's unlikely to contribute to that launch because of timing, but it can be used for marketing future events. I consider QR codes to be a marketing technology. That's where they bring the most value to an organization.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
I am exploring decentralized QR codes and different competing technologies. There are quite a number of them and this would allow me to justify spending more time on understanding filecoin and the specific implementation details. I'd like to improve the runtime of my existing algorithm for generating QR codes with designs in them. At present, the runtime is in the order of 20-30 seconds. I would like to get that down to below 250ms. I believe this grant can help me get there.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.

### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
qrtoad.com,
humanqr.com (under development)
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Daniel Legut, daniel@devmandan.com, legut2, Project Owner
* How did you learn about our microgrant program?
Google
* If your project was created as part of an event or hackathon:
N/A

**Comment by legut2** [comment]
If you have any questions for me please don't be afraid to ask @ErinOCon , @eshon

**Comment by ErinOCon** [comment]
Hi @legut2, thank you for your proposal. We will not be moving forward with a grant at this time, but would recommend checking out [hackathon opportunities](https://hackathons.filecoin.io/)! 

Wishing you the best as you continue to build!

**Comment by legut2** [comment]
I appreciate you for taking the time @ErinOCon to review my application. I am not interested in hackathons for this specific project but will consider it if something else makes sense.
