### ISSUE TITLE
Next Step Microgrant  The Eden: a decentralized live streaming platform for Web3.0 

### ISSUE THREAD

**Issue by dennishuang85** [filecoin-project/devgrants#1316]
### 1. What is your project, and what problem does it solve? (max 100 words)
The Eden is a decentralized live streaming platform for Web3.0 users. For the frontend, the project will provide 3D NFT avatar generating technology from 2D PFP NFT by using [our AI algorithm](https://github.com/VOKA-AI/3DAvatarGenerator), and be able to live stream with the 3D avatars. On the backend, the media data is delivered by IPFS network and RTMP server. 
![UML 图](https://user-images.githubusercontent.com/20713531/210529901-ef6decd5-d602-4123-ac5a-0e2ebd99e371.jpg)

![UML 图 (1)](https://user-images.githubusercontent.com/20713531/210529958-63d2296b-02bb-43b4-a940-95b377831543.jpg)

### 2. Project links
Link to Github repo：https://github.com/VOKA-AI/TheEdenLiveStreaming
Link to demo or website, if applicable: https://youtu.be/1Mr1tiPBc-o
License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
	The Live Client pushes media data to RTMP server. The IPFS network pulls that RTMP steam, encodes ts chunks in a live m3u8 file using ffmpeg. then IPFS adds and pins those files and uses IPNS to publish the m3u8 to its node ID. The built-in ipfs-http gateway allow those content to be accessed via HTTP, which is what the embedded player on the website will use. However, viewers running an IPFS client (with pubsub enabled) can directly view the streams over IPFS.
	3D NFT avatar is stored on IPFS. 
	The project uses smart contract on FEVM/FVM as the trustless third party. 

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
This grant is mainly for the development of smart contract and live server (RTMP+IPFS server) testing. 
	Develop a smart contract of FEVM/FVM to process the request for NFT buy, sell, swap, and staking, 
	Purchase aws server for Live-Server testing. 
	A prototype and a user interface website.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
2022 ETH Shanghai Hackathon – Bronze Prize
2022 Filecoin China Hackathon – Winner Prize: https://github.com/VOKA-AI/VokaAIProtocol
Polygon Buidl it：Summer 2022 – Pool Prize

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Dennis Huang: [dennishuang85@icloud.com](mailto:dennishuang85@icloud.com)
Github: https://github.com/dennishuang85
Role: Product Manager

Vincent Zhang: [576781512@qq.com](mailto:576781512@qq.com)
Github: https://github.com/Zhang-Tianxu
Role: Full Stack Developer

* How did you learn about our microgrant program?
Filecoin Hackathon

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
2022 Filecoin China Hackathon
  * Please link to your hackathon submission
https://github.com/VOKA-AI/VokaAIProtocol

**Comment by ErinOCon** [comment]
Hi @dennishuang85, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
