### ISSUE TITLE
Self custody cold wallet

### ISSUE THREAD

**Issue by WEb3markus** [filecoin-project/devgrants#1317]
# Open Grant Proposal: `Airgap`

Airgap.it

**Proposal Category:`integration-adoption` 

**Proposer:** Web3markus`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** Please respond with either "Yes" 

# Project Description

AirGap[1]is a self-custody wallet supporting multiple cryptocurrencies with the focus on security and usability. With AirGap’s unique approach a dedicated smartphone with the AirGap Vault mobile application becomes your offline hardware wallet where secrets are securely generated and stored. The companion application AirGap Wallet is installed on an everyday smartphone and responsible for connection to the internet and the protocols. We want to give the highest possibel security for the users in the Filecoin Ecosystems.

AirGap Wallet is available on Android, iOS, Web, macOS, Linux and Windows
AirGap Vault is available on Android and iOS
[1] https://airgap.it/

## Value

Every user in the Filecoin ecosystem get s a high secure self custody cold wallet. In this times it is very important that every user has full control over their funds. The old statement "not your keys not your coins" is constantly gaining in importance. With our unique architecture we garante a fully airgapped solution.

•	[AirGap Vault] (https://github.com/airgap-it/airgap-vault) – application responsible for the secure handling of the secret, account creation and transaction signing
•	[AirGap Wallet] (https://github.com/airgap-it/airgap-wallet) – application responsible for the communication with the protocoll

Your Ecoysystems as well profits from our 300K User base all over the world.

We dont see much risk here, as we are a very trained team of highly skilled developpers and have a lot of experience with the integration of our wallet.

## Deliverables

●	Airgap-coin-lib with Substrate support
●	AirGap-coin-lib with Filecoin
●	AirGap Vault application support for Filecoin
●	AirGap Wallet application support for Filecoin

## Development Roadmap

•	Phase 1: Week 1 | 4 days | 4000 USD
Requirements engineering
•	Phase 2: Week 2 – 4 | 8 days | 7000 USD
airgap-coin-lib integration of Filecoin
•	Phase 3: Week 5 | 8 days  |  7000 USD
AirGap Vault Filecoin account creation and transaction signing and testing on Filecoin test network
•	Phase 4: Week 6 – 9 | 10 days |  8000 USD
AirGap Wallet Desktop Filecoin build
AirGap Wallet Desktop UI
Filecoin account and transaction UI
•	Phase 5: Week 10 | 3 days | 3000 USD
Testing and internal security audit

## Total Budget Requested

Total Amount requested: 29`000 USD

## Maintenance and Upgrade Plans

Airgap is constantly maintained and there are aroundt 4 updates a year.

# Team

In total the paper team are around 25 blockchain enthusiast which try to change the status quo. We expect that on the Filecoin Integration into Airgap around 5-10 people will be involved in different phases. Our team is highly motivated and very skilled. Most of the Team members have 5 to 10 years experience in high end engineering. Papers is in the blockchain field since the early days. The Team is located in Zug Switzerland.

## Team Members

Alessandro de Carli, Founder and lead Software Engineer
Andreas Gassman, Lead Airgap Software Engineer
Julia Samol, Senior Airgap Software Engineer
Tim Schluchter, Senior Software Engineer
Raymond Abiola, Community Manager
Markus Städler , Head of Sales and Marketing
<!-- - ...

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/alessandro-de-carli-99011428/
https://www.linkedin.com/in/andreas-gassmann-36040341/
https://www.linkedin.com/in/julia-samol/
https://www.linkedin.com/in/raymondabiola/
https://www.linkedin.com/in/markus-staedler-782ab529/

## Team Website

www.papers.ch

## Relevant Experience

Actual Projects running by the Papers AG Team:
· Airgap is a self-custody wallet supporting multiple cryptocurrencies with the focus on security and usability. With AirGap’s unique approach a dedicated smartphone with the AirGap Vault mobile application becomes your offline hardware wallet where secrets are securely generated and stored .www.airgap.it. We already integrated quite a few relevant currencies.

· Youves is youves is a decentralised, non-custodial and self-governed platform for the creation and management of synthetic assets. Minters of synthetic assets earn a passive income in YOU, the governance token on youves.www.youves.com

· Acurast is the newest oracle chain. Acurast has reimagined the concept of bringing off-chain data on-chain, creating a platform where developers can access real world data

· Ecoo marketingplattform to generate your dedicated own coin in a closed ecosystem.

·E-seal.ch is the Multichain plattform to seal any kind of data.

## Team code repositories

The airgap project is fully open source and always available on Github:
https://github.com/airgap-it/airgap-coin-lib
https://github.com/airgap-it/airgap-vault
https://github.com/airgap-it/airgap-wallet

# Additional Information
We like the Filecoin project, and a few users out of our commnity already asked for integration.
You can reach me best : m.staedler@papers.ch, telegram:Web3 _markus

**Comment by ErinOCon** [comment]
Hi @WEb3markus, thank you for your proposal and for your patience with our review. Unfortunately, we will not be proceeding with a grant at this time. Wishing you all the best as you continue building!
