### ISSUE TITLE
Next Step Microgrant: Swann APP

### ISSUE THREAD

**Issue by canererdem21** [filecoin-project/devgrants#1321]
### 1. What is your project, and what problem does it solve? (max 100 words)
  Web3.storage

Swann is a meditation & music listening application that works using WEB3.0 technology. With the spread of WEB3.0, a need for a decentralized music listening platform has emerged today. Swann has emerged as a solution to this problem. Swann's aim is to become the most important application in this industry by using the power of artificial intelligence and web3.0 over time, rather than just an application that plays music inside. Thanks to Swann, people's listening habits of all sensitive data and other information will be more secure as they are in a decentralized system.

### 2. Project links

Link to Github repo:
https://github.com/canererdem21/SwannServer
https://github.com/canererdem21/SwannFront/

Link to demo or website, if applicable:
In App Screenshot;
https://ipfs.io/ipfs/bafybeihmwmmoij3rkwlbinsdhbc7yyaxcwcbepcmw4wiagh75acui6t734/swann1.jpg 
https://ipfs.io/ipfs/bafybeihhiwnijomsatv5v5qkzgrj4whgvmwgceobmmxrlhdhpaocmpuzey/swann2.jpg 
https://ipfs.io/ipfs/bafybeigi3octqexws45npcvozw6v33bxd34n4ybsbzexg6nemb3c52dnea/swann3.jpg 
https://ipfs.io/ipfs/bafybeicspsknqnngraz5fu42k5o2frl3llvypd6esnmc54m7tev4uokusi/swann4.jpg 
https://ipfs.io/ipfs/bafybeiawlkxkkqnfboiafbqdwmfx5iaea2yejs2gzceczyank5lncbjyme/swann5.jpg 
https://ipfs.io/ipfs/bafybeihfs6dnaz2i6vm2ivmsvoi4wsc7bnm6f7k4r3st54w5zgmgtrpyme/swann6.jpg 

License:MIT

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
All songs and cover images used in the project are stored from web3.storage. When users enter a page, the server sends the CID and full name of the relevant music and brings the images and the cover of the music over ipfs.io. In the next development, the admin panel will be created.  From this panel, music and covers will be sent to web3.storage using the web3.storage npm package.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
No

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

After the grant support, the auth system will be redesigned with the metamask login method. 
Then, with artificial intelligence, the user's profile pictures will be converted from real photos to avatars. Premium content will be brought and paid with smart contracts in an easy way.  And it will contain a detailed admin panel.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
We agree

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  No

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Caner Erdem | canererdem21@hotmail.com | https://github.com/canererdem21 | Full Stack App Developer
Tuba Kazoğlu | tugbakazoglu7@gmail.com | UI/UX Designer
Muhammed Ümit Bayraktar | bayraktar103@gmail.com | Researcher 

* How did you learn about our microgrant program?
Friend Recommendation

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

.env file ;
`PORT=8080
DB_URL= "mongodb+srv://swann:test123123@testdatabase.vsdji.mongodb.net/?retryWrites=true&w=majority"
JWT_TOKEN = "n077o#2PANv*`

**Comment by ErinOCon** [comment]
Hi @canererdem21, thank you for your proposal. We will not be moving forward with a grant at this time. For next steps, you may have an interest in checking out [hackathon opportunities](https://hackathons.filecoin.io/)!
