### ISSUE TITLE
ZKSwap - A Decentralized Exchange

### ISSUE THREAD

**Issue by ZKSwap-fe** [filecoin-project/devgrants#1322]
# Open Grant Proposal: `ZKSwap`

**Name of Project: ZKSwap** 

**Proposal Category:**  `app-dev`

**Proposer:** `ZKSwap-fe`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** Yes

# Project Description

Our technical team comes from the Ethereum Layer 2 project ZKSpace. We have deployed smart contracts on the ETH mainnet and built a comprehensive Layer 2 ecosystem using ZK-Rollups technology. Our products include ZKSwap, ZKSquare (a payment protocal), ZKSea (an NFT marketplace) and ZNS (ZKSpace domain name service).

The ZKSwap project, to be deployed on FVM, is a decentralized trading platform that uses the AMM trading model of Uniswap V2.

On the one hand, it allows users to make a market. Users can continuously earn transaction fees by simply forming a constant-product fund pool with two tokens.

On the other hand, users can trade freely by swapping one token for another in the pool. In that case, they need to pay a certain amount of transaction fee.

Our team has extensive experience in developing economic models for liquidity mining and transaction mining, and can reasonably adjust the mining parameters to incentivize the market. We have the passion and ability to become the most widely used DEX on FVM with the largest trading volume. With years of experience in Defi and Layer 2 projects, we can also contribute to the Layer 2 future of FVM.

See below for some screenshots of our products:

![image](https://user-images.githubusercontent.com/76548012/210941767-d80e48d4-122b-47b8-8037-ab8b0e29f6fe.png)
![image](https://user-images.githubusercontent.com/76548012/210941826-a013ba71-bb4f-469b-bf11-5b6959e8d6f7.png)
![image](https://user-images.githubusercontent.com/76548012/210941837-ded98ce8-de24-4863-b681-5b8c69941006.png)

## Value

- Benefits

For any new public chain, token is a core requirement, and for any Dapps, token is the core of its economic system. With tokens comes the demand for trading, and a DEX can meet the demand for trading any token. On the ZKSwap platform we plan to build, users can independently list tokens, add liquidity and trade tokens. We will also offer various liquidity mining and trading mining opportunities to meet user needs.

- Risks and Difficulties

Building a DEX requires continuous and intense work by the technical team, as well as auditors to repeatedly review to ensure the security of user assets, which is the biggest challenge for any team.

Besides, user adoption of the Filecoin network and the richness of other applications and assets on the chain will affect user demand and usage of DEX.

## Deliverables

We will deliver a complete decentralized exchange with market-making and trading functions.

It will provide Pool, Swap (trading), Mining, trading data analysis, NFT trading functions and more.

See [https://zks.app](https://zks.app) for proven products our team has been working on.

## Development Roadmap

-  Q1-Q2 2023

Develop and launch the official website and the basic functions of DEX  (released with the FVM mainnet launch), including user-initiated market making and trading functions.

-  Q3-Q4 2023

Develop and launch liquidity mining (PoL), trading mining (PoT) and staking mining (PoS) functions, and incentivize users to provide liquidity and trade.

- 2024

Develop corresponding functions for the FVM ecosystem, including but not limited to: NFT marketplace, NFT mining, IDO platform, Layer 2 scaling solution based on ZK-Rollups, order book trading, derivatives trading, etc.

![image](https://user-images.githubusercontent.com/76548012/210942427-6f06513e-1f67-4b23-b48a-153d00002606.png)

## Total Budget Requested

![screenshot-20230106-143038](https://user-images.githubusercontent.com/76548012/210944470-b4de77c3-3cd0-4c7f-ad56-a858606f1ab7.png)

## Maintenance and Upgrade Plans

We will complete the full functionality in accordance with the roadmap, and creatively improve the functions and upgrade the products over time.

# Team
The entire ZKSpace team

## Team Website

[https://zks.org](https://zks.org)

## Relevant Experience

Our technical team comes from the Ethereum Layer 2 project ZKSpace. We have deployed smart contracts on the ETH mainnet and built a comprehensive Layer 2 ecosystem using ZK-Rollups technology. Our products include ZKSwap, ZKSquare (a payment protocal), ZKSea (an NFT marketplace) and ZNS (ZKSpace domain name service).

Our team has extensive experience in developing economic models for liquidity mining and transaction mining, and can reasonably adjust the mining parameters to incentivize the market. We have the passion and ability to become the most widely used DEX on FVM with the largest trading volume. With years of experience in Defi and Layer 2 projects, we can also contribute to the Layer 2 future of FVM.

## Team code repositories

[https://github.com/l2labs](https://github.com/l2labs)

# Additional Information

For any questions, please comment or email us at [comms@zks.org](mailto:comms@zks.org). Thank you!

**Comment by ErinOCon** [comment]
Hi @ZKSwap-fe, thank you for your proposal. We will not be moving forward with a grant at this time, but you may have an interest in checking out [an accelerator program](https://ecosystem-wg.notion.site/Protocol-Labs-Accelerator-Program-d45d8792a7d544eca9beb7d3e3d3b05d) for this project!

Wishing you all the best as you continue to build!
