### ISSUE TITLE
# Open Grant Proposal: `Web3.com`

### ISSUE THREAD

**Issue by Roymamoku** [filecoin-project/devgrants#1324]
# Open Grant Proposal: `Project Title`

**Name of Project:** Web3.com

**Proposal Category:**  `app-dev`

**Proposer:** `roymamoku`

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** Please respond with either "Yes" or "No"

# Project Description

Web3.com is an information aggregation service platform dedicated to serve the web3 user community. The platform will give entities and individual studios as well as new users an opportunity to generate a web3 'business card' and avatar and the primary stage of the platform will serves like a "yellow page" for people to better navigate in the web3 world. No matter the information is off-chain or on-chain, users will find them on display. 

Through Web3.com, people, organizations, projects and other information in the Web3 world can be linked to explore a network form more in line with the Web3 paradigm and spirit. web3.com currently has two **main products:** Web3ite Pass and Web3 Space.

**I. Web3ite Pass**
Web3ite is a combination of Web3 Website Page,  Each Web3ite Pass corresponds to a third-level domain name of web3.com, such as Web3ite Pass named "bitcoin", which corresponds to the third-level domain name "bitcoin.web3.com". . Users who choose a name and cast a Web3ite Pass will enjoy the following benefits.

(1) Web3.com third-level domain name as the address of the display home page
Web3ite Pass holders can create and edit a web3.com third-level domain display page with the same name, e.g. NFT holders named "abc" can manage the "abc.web3.com" page, and users can use this The display page serves as a digital business card with integrated links and more information. After accessing Filecoin, the data of the Filcoin chain will be integrated in the display homepage and users can display relevant information.

(2) On-chain domain name as an identity symbol
Web3.com is a traditional DNS domain name, not registered on the blockchain, but with some existing on-chain infrastructure (such as the Ethernet Name System, abbreviated as ENS), the Web3.com domain name can be brought to on-chain use and perform similar functions as on-chain domain names. After accessing Filecoin, we will explore ways to bring Web3.com domain names for use on the Filcoin chain.

**Web3 Space**
Web3 Space is a space for information aggregation in the Web3 world. In the Web3.com, projects and organizations are important components, but currently there is no systematic platform to discover projects and organizations. Web3 Space relies on the content of Web3ite Pass showcase page and the collected project and organization information to build an easy-to-use and reliable project and organization discovery page through the navigation and search modules, so that users can get real and reliable project information, and based on It allows users to get real and reliable project information, and to discover and understand projects and organizations in the Web3 world based on different needs. At the same time, this information navigation and distribution can provide exposure and traffic support for the showcase pages created by Web3ite Pass.
After accessing Filecoin, we will establish more cooperation with Filecoin eco-projects and organizations to provide guided tours and traffic exposure for Filecoin eco-projects in Web3 Space.

## Value

Benefits.
1. brings a cross-chain domain name and identity system to the Filecoin ecosystem
2. Provide Filecoin ecosystem users with an application product that showcases on-chain behavior
3. Provide project guides and exposure services for project parties and organizations in the Filecoin ecosystem

Risks.
The cross-chain use of domain names is technically difficult, and the on-chain use of Web3.com domain names requires the use of some existing infrastructure, so it may be necessary to seek the cooperation of related projects to achieve

## Deliverables

1. Web3ite Pass' showcase page: supports adding Filecoin blockchain addresses to support the display of Filecoin on-chain assets and behaviors
2. Web3ite Pass' on-chain domain name and identity service can be used on the Filecoin blockchain
3. Web3 Space provides a guided tour for projects and apps under Filecoin unbrella.

## Development Roadmap

2023.Q1: Access to the Filecoin blockchain in the Web3ite Pass showcase page, and improve in stages that more contents modules can be displayed
2023.Q2: Web3 Space goes live and provides a guided tour for Filecoin eco-projects
2023.Q3: Web3ite Pass's on-chain domain name service connected to the Filecoin blockchain

## Total Budget Requested

Item 1: Show page access to Filecoin eco-related content
R&D Manpower: 30/Day
Maintenance: 1/Day/Month
Budget: $15000

Item 2: Web3 Space Guide Tour
R&D Manpower: 20/Day
Maintenance: 10/Day/Month
Budget:$15000

Item 3: Web3ite Pass's on-chain domain name service connected to the Filecoin blockchain
R&D Manpower: 30/Day
Maintenance:1/day/month
Budget: $15000

## Maintenance and Upgrade Plans

1. continue to explore the contents and attractions that can be displayed on the showcase page
2. Maintain Web3 Space's guided tour service and explore new forms of tours following the ecological and Web3 development

# Team
Team would like to keep anonymous. 

## Relevant Experience

The team members have rich experience in on-chain ecosystem app development, and have had experience in the development of several Ether based products, so they are efficient in terms of time and quality in app development on new public chains.

## Team code repositories

# Additional Information

**Comment by realChainLife** [comment]
Hi @Roymamoku thank you for this proposal. We will not be funding the work outlined here. Without additional details on how information will be collected and verified we can't ascertain the growth potential for the product. It would be great to also consider computation operations that can provide additional utility beyond listing.
