### ISSUE TITLE
Flustora Flutter Package

### ISSUE THREAD

**Issue by flustora** [filecoin-project/devgrants#1325]
### 1. What is your project, and what problem does it solve? (max 100 words)
FLustora is a dedicated Flutter package to help mobile app developers communicate with the Filecoin environment. The package makes it easy to communicate with the filecoin virtual machine using a Lotus node.
### 2. Project links
  
Link to Github repo: 
Github : https://github.com/flustora/dart_flustora/tree/main/packages/flustora
Link to demo or website, if applicable: 
Demo video :  https://github.com/flustora/dart_flustora/tree/main/packages/flustora/demo/videos
License: This project is under MIT License
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
Filecoin is at the very heart of the project because the plugin facilitates the communication of external applications with the Filecoin virtual machine.
###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
To be able to improve our project, we will use the grant in the following way:
- Recruit an additional developer to accelerate the development
- Deploy a public Lotus server for development.

The following improvements will be made to the package:
- Addition of missing Lotus modules to the project
- Add a Flutter-Rust bridge module to enable direct communication between a contract created on FVM and the mobile application coded on FVM.
- Add an encryption layer in the communication between the Flutter package and the Lotus node
- Add the functions of communications in Websocket with the lotus server
- Create graphical widgets to facilitate work with developers.
- Improve the project documentation

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
I Agree to share grants reports periodically and the final grant report after the Three months period.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Afer reading, i can confirm that my proposal comply with the Filecoin Community code of conduct standard

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
- Frontend dev : James Brel
Github :  https://github.com/JamesBrel
Email : [breljamesb@gmail.com](mailto:bbreljamesb@gmail.com)

- Backend DEV : Nicolas Madur
Github : https://github.com/nicolaemaduro
Email : Nicos1776Ju@hotmail.fr

* How did you learn about our microgrant program?
Filecoin slack community group
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by flustora** [comment]
Update: After carefully studying the technology around the filecoin virtual machine and its many possible applications. We decided to integrate a Flutter-Rust bridge module to enable direct communication between a contract created on FVM and the mobile application coded on FVM.

**Comment by ErinOCon** [comment]
Hi @flustora, thank you for your proposal! Unfortunately, the first wave of the FVM microgrant program closed prior to these application updates. We are planning to release another round of grant funding in a few weeks. Please feel welcome to re-apply at this time!

If you have already started building your project, we would like to encourage you to join the community of builders on Filecoin Slack and to consider submitting your project to the FVM Community Leaderboard, where the community votes bi-weekly on the top projects to win prizes from a $75k prize pool. Learn more [here](https://network-goods.notion.site/Impact-Evaluators-Builders-Leaderboard-602ea6755b5642e1ad6f9da59a47fa62).

**Comment by flustora** [comment]
Thanks for your reply and your consideration for this project. We will reapply.
