### ISSUE TITLE
Next Step Microgrant: <ensō collective>

### ISSUE THREAD

**Issue by julessw** [filecoin-project/devgrants#1327]
### 1. What is your project, and what problem does it solve? (max 100 words)

**Ensō Collective is a digital closet to explore your social graph. It allows users to store, organize, and share their personal wardrobes online. Using decentralized storage systems like Filecoin would be important for Ensō Collective because it would ensure that the data is stored in a secure and reliable manner, allow the service to scale more easily, and align with Ensō Collective's values of sustainability and transparency. Decentralized storage systems are more resilient and reliable than traditional centralized systems, and they can be more cost-effective and sustainable as well.**

### 2. Project links
  
Link to Github repo:

We currently have a private Repo but we are happy to add you.
Link to demo or website, if applicable:

**https://ensocollective.xyz/

Link to product:
https://vimeo.com/786990508**

License:

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

We’ll be using IPFS to store off-chain data about our users and the collections that they have minted. We’re currently building on top of Lens Protocol, and will be using ComposeDB to create graphs of any additional information we need.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
  Yes

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We are working on building our MVP for a digital closet that will be accessible on web3 social platforms. This grant will allow us to accelerate our progress and showcase our MVP at ETHDenver. We currently have around 400 signed up for Beta and have secured several partnerships. We plan to use the grant funds to hire an additional developer to help us create a usable product within the next two months

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, we are happy to share weekly/monthly reports and a finalized report on progress in three months.

  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes!

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Jules (jules@ensocollective.xyz) (CEO)
* Michi (michi@ensocollective.xyz) (COO)
* Xian (xian@ensocollective.xyz/seeinplays@gmail.com) (Lead Developer) 
* 
* How did you learn about our microgrant program?
On Twitter

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * N/A
  * 
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @julessw, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
