### ISSUE TITLE
Next Step Microgrant : Minofil Filecoin storage provider platform

### ISSUE THREAD

**Issue by Minofil** [filecoin-project/devgrants#1331]
### 1. What is your project, and what problem does it solve? (max 100 words)
Minofil is a free platform dedicated to supporting miners on the FIlecoin Blockchain. The platform offers a set of tutorial tools and courses to enable anyone wishing to become a storage provider. The Minofil platform offers, among other things, a simulator allowing you to make projections on the assembly of a storage provider server, an analytics dashboard to allow you to have a view of the network and be able to determine its evolutionary curve and above all scripts to accelerate the setting up node.
### 2. Project links
Link to Github repo: 
Frontend : https://github.com/Minofil/Minofil-front
Backend : https://github.com/Minofil/Minofil-back

Link to demo or website, if applicable: http://minofil.space
License: This project is under MIT License
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
Minofil uses Lotus servers to retrieve and process data from the Filecoin network in order to make projections on its evolution and profitability for storage providers. Minofil also improves the Filecoin user experience by creating scripts to facilitate the onboarding of new users.

###    b) Is this project contributing to the upcoming FVM launch? 
No
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
This grant will be used to mainly add to the team 2 young developers as well as a community manager. A small part will be used to create a development infrastructure with servers on Digitalocean.
The following improvements will be made to Minofil's free service:
- Creation of an advanced simulator of mining profits
- Creation of a dashboard containing data from the Filecoin network and temporal evolution curves.
- Creation of tutorials on Lotus server deployment
- Creation of courses on the Filecoin Virtual Machine
### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
I agree  
### 6. Does your proposal comply with our Community Code of Conduct?
Our proposal fully comply with the community code of conduct

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Frontend Dev : Adiyi Xavier
[adiyixavier@gmail.com](mailto:adiyixavier@gmail.com)
https://github.com/xavierlamar

Backend Dev : Mark Lavel[marklav@outlook.fr](mailto:marklav@outlook.fr)
https://github.com/poclus

* How did you learn about our microgrant program?
Kontour.io
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
HI @Minofil, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
