### ISSUE TITLE
Next Step Microgrant: Cookbook

### ISSUE THREAD

**Issue by pnkfluffy** [filecoin-project/devgrants#1332]
### 1. What is your project, and what problem does it solve? (max 100 words)
OpenZeppelin for FVM.

### 2. Project links
https://cookbook.dev/

Link to Github repo: https://github.com/Breakthrough-Labs
Link to demo or website, if applicable: https://cookbook.dev/
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

It it's current state, we are working to list and host FVM compatible contracts to make it easier for developers to build in the FVM ecosystem. As we cement the foundation of the platform, we are looking towards IPFS as a way to permanently host and version all smart contracts.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We are working to enable users to source FVM smart contracts and all of their relevant information. We are working to enable users to deploy FVM smart contracts directly from browser.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, we plan on reporting and documenting all progress, and staying in close communication with the FVM team.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
N/A

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Tyler Sehr
tyler@cookbook.dev
https://github.com/TylerSehr
CEO, head of operations

James Ewens
james@cookbook.dev
https://github.com/JamJomJim
CTO, head of development

Jackson Felty
jackson@cookbook.dev
https://github.com/pnkfluffy
head of busdev, partnerships

Sam Kamani
sam@cookbook.dev
https://open.spotify.com/show/6PrBYY9y55wManYu5IpXxZ?si=3faf74ec9f3a4a60
head of growth

* How did you learn about our microgrant program?
Referred by Sarah Thiam

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by pnkfluffy** [comment]
Hi guys, let me know if there is any additional information I can provide here to help out with this process!

**Comment by eshon** [comment]
Hi @pnkfluffy! We like your platform and it's currently being considered for an FVM microgrant but we'd like to figure out how this can be more useful for the Filecoin community (and also help improve your product).

We did a quick brainstorm of features / content that would be helpful and here's an initial list:

- A way to discover all Filecoin ecosystem stuff from the main landing page
   - How do new users know to navigate to https://www.cookbook.dev/filecoin?
- All the Zondax contracts are actually part of the [Filecoin Solidity Library](https://github.com/Zondax/filecoin-solidity) - can they be grouped under "Filecoin Solidity Library"?
- Can links to Github repos for these contracts be added to the UI?
- Better content curation - How can we improve Filecoin content on here? Possible ideas:
   - Quantity - can Cookbook commit to adding contracts from at least 20 more Filecoin teams?
   - Quality: 
          - We'd like to see more Filecoin-specific contracts on here related to the use cases listed in our [docs](https://docs.filecoin.io/smart-contracts/fundamentals/the-filecoin-virtual-machine/) including more Data DAO, Perpetual Storage and Collateral Leasing examples
          - @trruckerfling from the FVM DX team also said she can work with you to add some new FEVM tutorial contracts 
- We learned that you have 6k followers on Twitter which is fantastic. Are any Filecoin-related marketing commitments you can make for when more quality Filecoin content has been added?

Anyways, this is an initial list. If you can commit to these things and perhaps a few more features that may come up after the FVM DX team tries to use your platform more then we can consider your microgrant proposal.

Let us know what you think!

**Comment by trruckerfling** [comment]
on co-marketing:
- include cookbook into devrel demos
- include cookbook into builder cohorts moving forward, at least those focused on FVM

**Comment by trruckerfling** [comment]
for maintenance of contracts, cookbook is looking into upgradeable contracts. no action for now on teams. ETA 1-2 months.

**Comment by pnkfluffy** [comment]
Just got off call with @trruckerfling and we went over these points. Many of them were in the pipeline and the rest are great ideas! To respond to them in descending order:

- we will list different ecosystems including Filecoin on the home page shortly below the search bar. This will allow cookbook users to organically discover FEVM
- projects will be grouped into project cards (Zondax, Trustify, etc.)
- links to github repos will be added to the UI where appropriate
- Cookbook will add contracts from 20 more Filecoin teams (Sarah will help with sourcing)
- documentation on the contracts will be updated and made more thorough
- FEVM tutorial contracts will be added (supplied by Sarah)
- Cross-promotion will occur from the Cookbook Twitter, covering FEVM as well as ecosystem specific projects and contracts

**Comment by trruckerfling** [comment]
@pnkfluffy can we start with integrating these few demo contracts so we can use them in the dataverse hackathon demo on 3rd May? We can use it in our demo and you can use it in your workshop
- https://github.com/filecoin-project/fevm-hardhat-kit/blob/main/contracts/basic-deal-client/DealClient.sol
- https://github.com/filecoin-project/fevm-hardhat-kit/blob/main/contracts/filecoin-api-examples/DealRewarder.sol
- https://github.com/filecoin-project/fevm-hardhat-kit/blob/main/contracts/filecoin-api-examples/FilecoinMarketConsumer.sol

**Comment by pnkfluffy** [comment]
@eshon @trruckerfling we've gone ahead and updated the page to address all points there!

Let me know if there are any new things that have come to mind. Looking to get in touch with inbound devs in the space as well. Thinking the best way is helping out with Hackathons and being present in the upcoming cohorts. Let me know if there are any other ideas or the best ways I can be of assistance there!

**Comment by JamJomJim** [comment]
Thanks @trruckerfling! I just made all of these changes - let me know if there's anything else!

**Comment by ErinOCon** [comment]
Hi @pnkfluffy, this microgrant has been approved! We will send an email to confirm payment details. In regards to the final report for this project, here are some things we are looking for:
* A fully working user-facing demo with nice UX that anyone case easily use.
* Deployment to FVM mainnet - now that it has officially launched!
* Interesting use of the EVM on Filecoin, especially with respect to what's unique to Filecoin.

**Comment by pnkfluffy** [comment]
Hi Erin,

I've left the team, but Tyler ***@***.***) took lead on these
things.

**Comment by ErinOCon** [comment]
@TylerSehr can you provide an update on your project?

**Comment by ErinOCon** [comment]
@TylerSehr can you provide an update on your project?

**Comment by TylerSehr** [comment]
Hey Erin, we're currently updating the Filecoin page with some new updates. These are extended to the ecosystem page as well, and incorporate your previous feedback

**Comment by ErinOCon** [comment]
Hi @TylerSehr, can you confirm the end date for this project?

**Comment by ErinOCon** [comment]
Hi @TylerSehr, do you have an update available?
