### ISSUE TITLE
Open Grant Proposal: `SellX3.com`

### ISSUE THREAD

**Issue by Web3HackerDAO** [filecoin-project/devgrants#1333]
# Open Grant Proposal: `SellX3.com`

**Name of Project:** SellX3.com

**Proposal Category:** app-dev

**Proposer:** [Web3HackerDAO](https://github.com/Web3HackerDAO)

**(Optional) Technical Sponsor:** None

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** Yes

# Project Description

NFT is still in the PFP stage and has not played a very important role in the creator economic system. IPFS provides a decentralized storage infrastructure. However, the application of specific and practical scenarios in various industries has not yet been popularized and popularized.

Web3VitePress is a Web3 NFT as a Service Open-Source solution that builds on top of the [VitePress](https://vitepress.vuejs.org/).

It can help buidlers(blogger, photo maker, musician, book writer) to create a flexible member card platform that leverage the [NFT.Storage](https://nft.storage/) / [LitProtocol](https://litprotocol.com/) / NFT / Web3 / [VitePress](https://vitepress.vuejs.org/) technology and compose them to build a Web3 native member card platform that provides a developer themes && plugins marketplace to build unlimited industries web3 native landing page and membership selling system.

So, the buidlers can use the platform to create new content they want and have the freedom to customize the UX whatever they want as it is open-source.

It builds on top of the open-source project [VitePress](https://vitepress.vuejs.org/) that can get potential tech users to use and even join in to develop more themes and plugins for the platform.

Also, we will build a PaaS platform for non-tech users to use without any coding skills(more like GitBook). So the target users will be huge.

## Value

By introducing NFT-Gating for stored data, it can bring real data value landing applications to Web3, prosperity to the number of users, and opportunities for more use of IPFS. The development of an open-source Web3 Native creator economic ecological platform based on VitePress will significantly stimulate the extensive use of IPFS, because all valuable creative content is inseparable from a large amount of storage, and the introduction of NFT-Gating will also It will bring the logic of the final clear goal for the last paid storage of IPFS.

## Deliverables

1. Web3VitePress open-source components:
    * Refactor the web3 vitepress theme code that provides more elegant and robust UX / DX code for readers and developers
    * Build the Web3 / IPFS way of content comment module/widget that provide a comment function for each blog content
    * Build a theme/plugin pattern that provides developers can join the open-source project to create more theme widgets/plugins
    * Add unlimited web3/IPFS relative vitepress components as needed while the whole project is developing
    * Develop a full-function theme that provides a good UX for target users(Buidlers) to use the code to build their Web3VitePress site

2. SellX3.com
    * Makes the platform more reasonable and attractive to target users
    * Provide buidlers create blogs(create their owned NFT token) function so later they can use it for their WebVitePress site
    * A Web3 Buidlers and content feed: it aggregated all the decentralized data and content on the PaaS so helping readers/consumers to discover the creative content easier.

### Milestone 1

For this milestone, we focus on making the MVP of the Web3VitePress works and introduce some seed developers to use it in their tech-blogging stuff.

* Member:
  * [Web3HackerDAO](https://github.com/Web3HackerDAO) Full Stack Developer(Web3, JavaScript, Vue3, VitePress, Solidity)
  * Maybe hire some other developers to build more modules for the system
* Time Span: 2023/01/07 - 2023/04/01 (80+ days)
* Funding required: $30k
* Deleived features:
  1. SellX3.com site application functions to guide new users to use the Web3VitePress
  2. Refactor the web3 vitepress theme code that provides more elegant and robust UX / DX code for readers and developers
  3. Build the Web3 / IPFS way of content comment module/widget that provide a comment function for each blog content
  4. Integrated [LitProtocol](https://litprotocol.com/) to have a token gating feature for each content (but integrated to FEVM maybe need to wait for LitProtocol to launch their node for FEVM)
  5. Re-design and deploy the Web3VitePress contract to FEVM mainnet

### Milestone 2

For this milestone, we focus on marketing the Web3VitePress, turning it into a PaaS platform, and building-related modules to support the marketing work.

* Member:
  * [Web3HackerDAO](https://github.com/Web3HackerDAO) Full Stack Developer(Web3, JavaScript, Vue3, VitePress, Solidity)
  * Maybe hire some other developers/marketing guys
* Time Span: 2023/04/01 - 2023/10/01 (180 days)
* Funding required: $50k
* Deleived features:
  1. Write a blog to invite developers to use the open-source platform(will launch some NFT rewards for the event)
  2. Build a theme/plugin pattern that provides developers can join the open-source project to create more theme widgets/plugins
  3. Add unlimited web3/IPFS relative vitepress components as needed while the whole project is developing (The detail plugins/modules name not sure for now, as they will come out during heavy development of the code)
  4. Develop a full-function theme that provides a good UX for target users(Buidlers) to use the code to build their Web3VitePress site
  5. Build 3+ themes to make users more choice in the UI/UX
  6. Build the Web3 Buidlers and content feed: it aggregated all the decentralized data and content on the PaaS so helping readers/consumers to discover the creative content easier
  7. Maintain / Feedback while more and more users use the open-source code

## Total Budget Requested

We're requesting total funding of $80,000 to complete all the above milestones, and the fund will be split in to:

| Milestone      | Duration | Cost |
| ----------- | ----------- |----- |
| #1          | 80+ days    | $30k |
| #2          | 180 days    | $50k |
| Total       | 260+days    | $80k |

## Maintenance and Upgrade Plans

This is an open-source project and we are committed to maintaining it by doing bug fixes based on the community feedback.

# Team

## Team Members

[Web3HackerDAO](https://github.com/Web3HackerDAO), web3hackerdao@gmail.com

## Team Member LinkedIn Profiles

I do not have LinkedIn profiles, as I do not use them before, also do not have any plans to find any job later. As I am all in web3 and build the cool projects I like to build.

## Team Website

<https://SellX3.com>

## Relevant Experience

I am a full stack developer(Web3, Solidity, JavaScript, Vue3, DevOps, NodeJS, React...) with experience in blockchain technologies.

The project starts from the ETH-Global/FEVM hackathon and gets the top 10 slots then.
And just finish the Micro-grant from Filecoin/dev grants: <https://github.com/filecoin-project/devgrants/issues/1282>.
And now comes out the idea that turns this idea more seriously, as I think this can have a big impact on the Web3 ecosystem.

## Team code repositories

<https://github.com/orgs/Web3VitePress/repositories>

<https://SellX3.com>

**Comment by ErinOCon** [comment]
Hi @Web3HackerDAO, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant for this proposal at this time. 

Wishing you the best as you continue to build!
