### ISSUE TITLE
Next Step Microgrant: D-DriveStorage

### ISSUE THREAD

**Issue by mohitthakkar30** [filecoin-project/devgrants#1334]
### 1. What is your project, and what problem does it solve? (max 100 words)

- My project is about decentralized drive storage, similar to google drive. It solves the problem of centralization, not depending on a single entity. This can be more secure and efficient than traditional centralized storage systems, because it eliminates the risk of a single point of failure and allows data to be stored closer to users, reducing latency.

### 2. Project links
  
Link to Github repo: https://github.com/mohitthakkar30/D-drive-storage
Link to demo or website, if applicable: https://d-drive-storage.vercel.app/
License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

- Data storage via Web3 Storage ( IPFS + Filecoin )
- One way that IPFS can be used for decentralized drive storage is by using it to store and share large amounts of data, such as documents, images, and videos. For example, a user could use IPFS to store their personal files and share them with friends or colleagues, or a company could use IPFS to store and share large amounts of data among its employees. By using IPFS, users can store and share their data in a decentralized manner, without the need for a central server or other points of control.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
- No

  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
- Grant will help me to get paid API which will help me to reduce fetching time, and will also help me to improve UX. Adding Lit Protocol for data encryption

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
- Yes, I agree to provide grant reports.
  
### 6. Does your proposal comply with our Community Code of Conduct?
- Yes, it complies with the Community Code of Conduct.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: NA
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
    
-  Name: Mohit Thakkar
    Email: [thakkarmohit90@gmail.com](mailto:thakkarmohit90@gmail.com)
    GitHub: @mohitthakkar30
    Role: Full-Stack Dev

* How did you learn about our microgrant program?
- Got details from a Friend

* If your project was created as part of an event or hackathon: NA
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum):-  NA
  * Please link to your hackathon submission :- NA

**Comment by ErinOCon** [comment]
Hi @mohitthakkar30, this microgrant has been approved! We will send an email to confirm payment details. Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
