### ISSUE TITLE
Next Step Microgrant: ChargeSwap

### ISSUE THREAD

**Issue by mittal-parth** [filecoin-project/devgrants#1335]
### 1. What is your project, and what problem does it solve? (max 100 words)
ChargeSwap is a decentralized platform that aims to address the challenges of the electric vehicle (EV) battery swapping ecosystem through the use of blockchain and IoT technology. By facilitating the creation of a network of EV battery swapping stations and providing a transparent and immutable record of battery information, ChargeSwap hopes to create incentives for the manufacture, sale, and usage of electric vehicles and contribute to the goal of having 30% of all vehicles in India be electrically driven by 2030.

### 2. Project links
  
Link to GitHub repo: https://github.com/CommanderAstern/ChargeSwap
Link to demo or website, if applicable: [ETHIndia Finalist Demo](https://youtu.be/9rieTya8Yds?t=3908)
License: Apache License 2.0

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

1. The user signs up for our platform. We made the onboarding simple for conventional Web2 users, by allowing them to sign up with social login in addition to the usual MetaMask login using the Biconomy SDK.
2. [Assumption for now]: The user is sent a battery by us with the ownership transferred to them in the smart contract. This smart contract is deployed on Polygon (the Mumbai testnet as of now).
3. Upon arriving at the station, the user scans his discharged battery using RFID at the IoT-enabled device. The metadata of each battery is immutably stored using IPFS. This information, such as the age, previous treatment of the batteries, and attribution of the energy source are stored in a decentralized manner and can be accessed and verified by users of the ChargeSwap platform.  
4. The user is asked to pay the price for the charge required. The price is just a multiple of (100 - discharged battery %) written in the smart contract. 
5. Upon successful purchase, the IoT-enabled device interacts with the smart contract to swap the ownership of a new charged battery and the user's discharged battery. 

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
No
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- Purchasing equipment or hardware needed for the project, such as IoT devices for battery swapping stations.
- Hiring additional team members or contractors to help with development and other tasks.
- Funding research and development efforts to improve and expand the platform's capabilities.
- Covering operational costs such as hosting fees.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

 Yes
### 6. Does your proposal comply with our Community Code of Conduct?

Yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
[Submission](https://devfolio.co/projects/chargeswap-3527)
  - Top 12 winning projects,
  - Best Public Good by Polygon and  
  - Best New Module using Biconomy 
  - Push Protocol Prize Pool at ETHIndia'22 - the world's largest Ethereum Hackathon

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

| Member| Role | GitHub | Email |
| --- | --- | --- | --- |
| Parth Mittal | Frontend Developer | [mittal-parth](https://github.com/mittal-parth) | mittalparth22@gmail.com |
| Abhiraj Mengade | Frontend Developer | [abhiraj-mengade](https://github.com/abhiraj-mengade) | abhiraj.mengade@outlook.com |
| Ashish Bharath | Solidity Developer | [MistaAsh](https://github.com/MistaAsh) | ashishbharath2002@gmail.com |
| Asim Jawahir | IoT/Solidity Developer | [CommanderAstern](https://github.com/CommanderAstern) | asimjawahir123@gmail.com |
| Rahul Pujari | UI/UX Devoloper/ Product Manager | [EmperorRP](https://github.com/EmperorRP) | leelarahul@gmail.com |

* How did you learn about our microgrant program?
I learned about the microgrant program through a member of the Protocol Labs team who contacted us after the final demo at ETHIndia. They encouraged us to apply for the grant and provided information about the program and how to apply.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  ETHIndia
  * Please link to your hackathon submission
  [Submission](https://devfolio.co/projects/chargeswap-3527)

**Comment by dawnkelly09** [comment]
Greeting, team ChargeSwap! I am reviewing your grant application and you have quite an interesting project with a pretty big repo. Would you please be so kind as to show me where I can find the IPFS/Filecoin tech in use in the code? Thank you so much!

**Comment by ErinOCon** [comment]
Hi @mittal-parth. thank you for your patience with our review. This microgrant has been approved! We will send an email to confirm payment details. Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
