### ISSUE TITLE
Next Step Microgrant: Collabs-On-Chain

### ISSUE THREAD

**Issue by TheDARKFURY** [filecoin-project/devgrants#1336]
### 1. What is your project, and what problem does it solve? (max 100 words)

Collabs-On-Chain is a project focused on creating a new contribution power gating mechanism. This mechanism is designed to allow users to earn and accumulate contribution power, which can then be used to participate in gated communities, DAOs and governance decisions within the ecosystem. The goal of this system is to create a more fair and transparent way for users to be a part of the community and project and have a say in the direction of the project.

### 2. Project links
  
Link to Github repo: https://github.com/TheDARKFURY/Collabs-On-Chain
Link to demo or website, if applicable: https://collabs-on-chain.vercel.app/
License: MIT License
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

As users start making contributions and collaborations, we started creating on-chain history of this. So, we are using IPFS for storing the data and thus getting a decentralized storage protocol. We would also like to add Filecoin as an optional storage using Lighthouse so the users can have more options.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
No
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

I would improvise the UX with premium APIs for making it scalable. One of the goals is to make it multichain and make it chain abstracted, this can be achieved by using better aggregators and services.
Right now this project is on Solana and then adding other chains would require nodes and services to handle and make it scalable. We would be working a lot on creating the UX better, a mobile version for simple handling of the app also acknowledges that we are on the path to making it user-friendly.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, I agree to provide any & every minute detail about the project & its SDLC if asked.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes, it complies with the Community Code of Conduct.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Yes. The project was a winner at the [Devfolio-Amritathon](https://amritathon.devfolio.co/) Hackathon.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project

   *   Name: Soham Shah
        Email: [sohamshah419@gmail.com](mailto:sohamshah419@gmail.com)
        GitHub: [@TheDARKFURY](https://github.com/TheDARKFURY)
        Role: Full Stack Developer

* How did you learn about our microgrant program?

I learned about the microgrant program from a Protocol Labs team member at ETHIndia. They provided information about the program and encouraged me to apply.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  
      [Devfolio - Amritathon](https://amritathon.devfolio.co/)

  * Please link to your hackathon submission
 
       https://devfolio.co/projects/collabsonchain-72e9

**Comment by TheDARKFURY** [comment]
Hey @ErinOCon can you please let me know the status on this? Thank you! ✌️

**Comment by ErinOCon** [comment]
Hi @TheDARKFURY, thank you for your proposal. We will not be proceeding with a grant at this time. Wishing you the best as you continue to build!
