### ISSUE TITLE
Next Step Microgrant: PEERIO

### ISSUE THREAD

**Issue by Akoek** [filecoin-project/devgrants#1337]
### 1. What is your project, and what problem does it solve? (max 100 words)
Some of the main problems with the current peer review process are plagiarism, limited and small review groups, lack of input from other researchers who may be working on research that is relevant and meaningful to reference, unnecessary duplication of efforts, and a need to get others to validate and replicate research findings.

Peerio aims to provide a solution for these problems. It's an app that allows users to earn by uploading and reviewing research papers.

How does it work?

Reputation adds trust to the review process
Peer reviewers are rewarded FIL tokens for participation
To ensure honest activity - reputation (value between 0 & 1) is multiplied by Maximum payout. ( rep = pay)
Peer Reviewers will win or lose reputation based on the accuracy of their review

### 2. Project links
  
**Link to Github repo: https://github.com/brandonsurh/HackFEVM-proj
Link to demo or website, if applicable: https://peerio.netlify.app/**
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

Peerio is made from React, IPFS, web3.storage, Tableland, and runs on the FEVM. Our smart contract is coded in Solidity which handles all of the backend for our peer review process of voting and peer review proposals. When a file is uploaded it is stored through IPFS's interface in a decentralized manner. This was done using Protocol Lab's service web3.storage. We also used Tableland to save information about the article while the actual file is stored on web3.storage.

Front-end: Js/React, MUI
Backend: smart contract on FEVM (Wallaby), Ethers, Hardhat, Web3.Storage, & Tableland DB
Hosting: Netlify

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)

No

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Issues to resolve
- Tweak and implement UX/UI
- Tableland integration with Wallaby
- Fix file upload
- Fix rating algorithm
- Decentralized database integration

Features to add
- Search

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions

Yes https://ethglobal.com/showcase/peerio-0bv55
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Brandon - brandonsurh@gmail.com - brandonsurh - developer
Thomas - tombutler4@hotmail.com - trbutler4 - software engineer
Albert - marcial.arturo@yahoo.com - electrone901 - frontend developer
Anne - akoek@protonmail.com - akoek - designer

* How did you learn about our microgrant program? Through Filecoin Slack
* If your project was created as part of an event or hackathon:
  * What was the name of the event? ETHGlobal HACK FEVM
  * Please link to your hackathon submission https://ethglobal.com/showcase/peerio-0bv55

**Comment by ErinOCon** [comment]
Hi @Akoek, thank you for your proposal! It looks like the building progress for this project is linked with your team members' Github handles. Can a member of your team comment on this proposal verifying that they will be contributing to the next steps of this project?

**Comment by brandonsurh** [comment]
I will be contributing to the next steps of the project

**Comment by trbutler4** [comment]
Also will be contributing

**Comment by Akoek** [comment]
> Hi @Akoek, thank you for your proposal! It looks like the building progress for this project is linked with your team members' Github handles. Can a member of your team comment on this proposal verifying that they will be contributing to the next steps of this project?

Hi @ErinOCon I probably should've added the team as contributors but am not super Github savvy.. Sorry!

**Comment by ErinOCon** [comment]
Hi @Akoek, thank you for the updates! This microgrant has been approved! We will send an email to confirm payment details.

**Comment by ErinOCon** [comment]
Hi @Akoek, I hope your project is progressing well! If you have any questions regarding the reporting process for this work, please be in touch. In the meantime, here are some things we are looking for when reviewing FVM Microgrant results: 

- A fully working user-facing demo with nice UX that anyone case easily use.
- Deployment to FVM mainnet - now that it has officially launched!
- Interesting use of the EVM on Filecoin, especially with respect to what's unique to Filecoin

Happy building!

**Comment by Akoek** [comment]
Hi @ErinOCon, 
Thanks for your message, @trbutler4 @brandonsurh would like to get in touch with you about the project!

**Comment by ErinOCon** [comment]
Hi @Akoek, thank you for your reply! Please feel welcome to reach out at grants@filecoin.org.

**Comment by ErinOCon** [comment]
Hi @Akoek, do you have a new update available for this project?

**Comment by ErinOCon** [comment]
@trbutler4 @brandonsurh Have you reached out to our team by email? Please let us know if you are having trouble contacting our team.

**Comment by trbutler4** [comment]
I want to tweak the issues to resolve a bit as well. 

Issues to resolve

Tableland integration with Wallaby -> abandon tableland in favor of supabase
Decentralized database integration -> use supabase instead for simplicity

this is just to speed up build time and get to a working solution.

**Comment by trbutler4** [comment]
i know this is now well past the 3 month period. Please let me know if I can still complete this to receive the rest of the grant.

**Comment by trbutler4** [comment]
As far as hosting and API keys for a production project goes, I am unable to pay for a domain and api key for continued use. The best I can do is get it to a production ready state, that would only need to be deployed with its own api key and domain

**Comment by eshon** [comment]
Any updates @trbutler4?  We'd like to close out this grant program
