### ISSUE TITLE
Delta Data DAO

### ISSUE THREAD

**Issue by escapizt** [filecoin-project/devgrants#1338]
### 1. What is your project, and what problem does it solve? (max 100 words)

Delta Data DAO is a extensible Command Line Interface Toolkit to create and manage Data DAOs on FEVM.

The CLI Tool can be used to perform the following tasks:

1. Create a DataDAO from a particular template
2. Join the DataDAO by staking tFIL
3. Check the details of deals managed by the DataDAO using the MarketAPI
4. Vote on new deals being created by the DataDAO

This command line tool can be installed easily across all operating systems and can be extended to support any future type of DataDAO as well.

### 2. Project links

Link to Github repo: [https://github.com/escapizt/DeltaDataDAO](https://github.com/escapizt/DeltaDataDAO)
Link to demo or website, if applicable:
License: MIT

Command Line Interface Demo:

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/121949430/211914454-59a379eb-b3fe-4c03-aeed-5b379b67aa2b.png">

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/121949430/211914059-b43cc566-811c-4545-bb6c-88a5b1663976.png">

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/121949430/211914494-6c6243d5-3436-4c15-bb03-8f5df63583f2.png">

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

Smart Contracts on the Filecoin Virtual Machine are used to manage the DataDAO using the Command Line Interface.

All the Deals, Storage Provider and Client related information comes from the MarketAPI which is exclusive to Filecion

### b) Is this project contributing to the upcoming FVM launch? (Yes or No)

Yes

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Creating a config file for the CLI, which can help manage keys and other required configs for the tool installed on the local system

Given the github repository URL (Filecion CID) of a DataDAO in the parameter, the tool can be used to easily deploy that DataDAO on to a preferred FEVM network and then can be used to communicate with the said DataDAO

The command line tool can be extended to become an API service, which can act as the communication layer for making DataDAO native to Mobile

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions

- If your project began at a hackathon, have you submitted it for the
relevant Protocol Labs prizes? Include links here if available:

### Additional questions:

- For each team member(s), please list name, email, Github account, and role in the project.
    Name - Vinay Reddy
    Email - **[reddymuzzle444@gmail.com](mailto:reddymuzzle444@gmail.com)**
    Github - escpaizt
    Role - Solidity Developer + CLI Tooling Expert
    
- How did you learn about our microgrant program? Piyush Maheshwari on LinkedIn
- If your project was created as part of an event or hackathon:
    - What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks
    hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
    - Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @escapizt, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be proceeding with a grant at this time. Wishing you all the best as you continue to build!
