### ISSUE TITLE
Next Step Microgrant: Third Storage <> FVM

### ISSUE THREAD

**Issue by hackyguru** [filecoin-project/devgrants#1339]
### 1. What is your project, and what problem does it solve? (max 100 words)
Third Storage is a decentralized blockend (backend + blockchain) as a service built with IPFS, Filecoin and FVM. With Third Storage, developers can build web3 dapps by using content addressed and verifiable database, file storage and other utilities. With self sovereign identity and storage, users are democratized to own their own data. 

### 2. Project links
  
Link to Github repo: https://github.com/thirdstorage
Link to demo or website, if applicable: https://thirdstorage.com
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
The project uses Filecoin for perpetual pinning (via Web3.storage and estuary.tech). All the data is content addressed and served via IPFS. We use FVM to deploy all our necessary smart contracts that can help us bring programmability to storage. For detailed information on the usage of IPFS and our roadmap - please refer to https://thirdstorage.com/localhost

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
With this grant, we will be able to fast pace our R&D with FVM and deploy our smart contracts pertaining to decentralized database backups, perpetual pinning and project usage/cost estimation. These funds will also enable us to amplify a unique use case of FVM.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
https://docs.thirdstorage.com
https://twitter.com/thirdstorage
https://discord.thirdstorage.com
https://thirdstorage.com/products
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project. Guru - https://github.com/hackyguru (please refer our [github organization](https://github.com/thirdstorage) for detailed information about our repositories)
* How did you learn about our microgrant program? - Through FVM Foundry

**Comment by eshon** [comment]
@hackyguru - Can you please be more specific about how you will use FVM and what smart contracts will be built?

**Comment by hackyguru** [comment]
sure @eshon 

we're planning to use FVM for multiple use cases in the coming months which can help us with storage deals. To be more specific,

1. Perpetual pinning contract - a timebound file pinning smart contract that ensures a file's availability for a specific time. This will help us ensuring the persistence of all the assets and data stored on Third Storage.

2. Contracts to create projects and manage billing in Third Storage Cloud - a set of smart contract functions that can help us in allowing users to create new Third Storage projects on Third Storage Cloud and then manage the billing with $FIL staking. This will be the very first of it's kind use case of FVM where we operate a cloud instance based on the events emitted from the smart contract deployed on FVM.

![StakingModel](https://cdn.discordapp.com/attachments/1030935403177459732/1064602978578866276/image.png)

**Comment by ErinOCon** [comment]
Hi @hackyguru, thank you for your proposal and for your interest in our grants program. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
