### ISSUE TITLE
Next Step Microgrant: <Your Title Here>

### ISSUE THREAD

**Issue by wangzheqingze** [filecoin-project/devgrants#1340]
### 1. What is your project, and what problem does it solve? (max 100 words)

A model in which everyone shares the income of decentralized co-governance, throwing away the original income and distribution obtained by centralization, and distributing the income by themselves, everyone can see the income of the platform and the income promised by the platform to themselves in real time. A resource integration of platform content. Solve the current mistrust and deception of centralization and build a good trust model.
### 2. Project links
  https://golduuu.com
Link to Github repo:
Link to demo or website, if applicable:
License:

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
Files are added to the IPFS network, and CDN acceleration is carried out around the world, aiming to achieve global network balance. The income of the platform can be converted into the token FIL, and the platform income dividend can be obtained by holding FIL, and the FIL can be locked. This project can be combined with offline, which can promote a customer acquisition channel for offline merchants and better promote FIL. Currently, there are only Chinese nodes. Since China does not support the development of cryptocurrencies, we can only use Tokens get dividends and cannot generate themselves. Deploy the website on IFPS, realize the decentralization of global intercommunication, and let the website exist on the Internet forever. This is the revolution of the Internet!
###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
  yse
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

First of all, a notice will be issued that we have received a grant from FIL to support the projects we have developed, and will publish this deposit in a lock pool. The user's lock will be carried out in a wallet, and that wallet will never leave the network. Yes, we will award this grant to users and merchants who actively promote the project development. Our ultimate vision is to link offline, virtual and reality, which requires many merchants to settle in. Only with the support of entities, FIL will develop more prosperously!
### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  yes
### 6. Does your proposal comply with our Community Code of Conduct?

yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  no
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
We did not carry out an online development, but deployed them together offline

**Comment by ErinOCon** [comment]
Hi @wangzheqingze, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
