### ISSUE TITLE
Push Chat (Push Protocol)

### ISSUE THREAD

**Issue by richajoshi123** [filecoin-project/devgrants#1342]
# Open Grant Proposal: `Push Chat`

**Name of Project:** `Push Chat`

**Proposal Category:** `app-dev`

**Proposer:** `https://github.com/ethereum-push-notification-service`

**Technical Sponsor:** `Piyush Maheshwari`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** `Yes`

# Project Description

Push chat is a secure messaging protocol that encrypts, signs, and stores messages on IPFS and sends those messages via Push Nodes. Push chat allows users to communicate with each other directly from their wallet to wallet. This means that there is no need for any personal information to be shared in order to use the chat feature. Instead, the chat messages are stored on IPFS (InterPlanetary File System), and sent through Push Nodes.

Push chat is designed to be simple and easy to use, with a focus on privacy and security. It uses advanced encryption techniques to ensure that all chat messages are kept secure, even if they are being transmitted over the internet. This makes it ideal for users who value their privacy and want to avoid the risks associated with sharing personal information online.

One of the key benefits of Push chat is its decentralized nature. Because it is built on top of IPFS, it is not dependent on any central server or authority. This makes it resistant to censorship and ensures that users have complete control over their own data.

Overall, Push chat is a powerful and secure chat application that allows users to communicate with each other without the need to share any personal information. It is a great choice for anyone who values their privacy and wants to stay safe online.

## Value

Push chat can bring several values to the Filecoin ecosystem. First and foremost, it can help to increase the adoption and usage of Filecoin by providing a practical and useful application that leverages the decentralized network. As more people use Push chat and become familiar with Filecoin, they may be more likely to use other Filecoin-based applications and services, which can help further to promote the growth and development of the IPFS ecosystem.

Push chat can also help to demonstrate the power and potential of Filecoin as a decentralized platform. By providing a high-quality chat application that is fast, reliable, and secure, Push chat can showcase the capabilities of Filecoin and inspire other developers to build new and innovative applications on top of the network.

In addition, Push chat can contribute to the overall security and stability of the Filecoin ecosystem. By storing chat messages on the decentralized network, Push chat can help to distribute data across multiple nodes, making it more resilient to attacks and outages. This can help to ensure that the Filecoin ecosystem remains strong and reliable for all users.

Overall, Push chat has the potential to bring significant value to the Filecoin ecosystem by promoting the adoption and usage of Filecoin, demonstrating its potential as a decentralized platform, and contributing to the security and stability of the network.

## Deliverables

As of now, Push Chat is in Alpha version and it’s under heavy development. Here below are the deliverables:

- A functional chat application that allows users to communicate with each other directly from their wallet to wallet, without the need to share any personal information.
- A functional Push Chat SDK, that can be integrated into platforms to leverage the functionality of Push chat.
- A user-friendly interface that makes it easy for users to send and receive messages, as well as manage their chats and contacts.
- Advanced encryption techniques to ensure that all chat messages are kept secure, even if they are being transmitted over the internet. Also, can be sent via Push Nodes.
- Integration with IPFS to store chat messages on the decentralized network, providing a secure and decentralized solution for data storage and transmission.
- Documentation and technical support resources to help users get started with Push chat and troubleshoot any issues they may encounter.
- Regular updates and maintenance to keep the chat application running smoothly and to address any bugs or issues that may arise.
- Marketing and outreach efforts to promote the chat application and encourage adoption among potential users.

## Development Roadmap

The milestones below are separated for better understanding and they will be developed in parallel by the development team from Push Protocol.

Milestone 1

On this milestone we will be focusing on researching and improving the Push Chat sdk with Filecoin tech stack and the documentation for the same.
Integrate native support for IPFS tech stack on Push Nodes for enabling chat infrastructure support via IPFS 
Improve javascript sdk for chat with capabilities of rest apis and websocket
Improve existing sdk functions
Capabilities to store at IPFS and persist
Add support for new chat functionalities
Improve the react sdk for chat
Create new react components
Improve UI for the existing components
Improve the technical documentation for the sdks above and create more examples on how to integrate the protocol
This milestone will be done by a team of 3 developers.
Timeline: 6 weeks.

Milestone 2

We will continue to research and develop our solution for integrating Push Protocol with IPFS, and will also work on integrating IPFS into the mobile app. This will allow users to store and share data on IPFS directly from the mobile app.

Work on supporting the entire tech stack on mobile
Improve the mobile sdk to enable developers to integrate chat on their apps and have native notifications deliveries
Improve the chat functionality to make it mobile friendly
Make the mobile app sdk more responsive and intuitive for the end user
This milestone will be done by 2 developers and 1 designer.
Timeline: 4 weeks.

Milestone 3

We will focus on extending chat functionalities to incorporate popular features present in any web2 chat but in a way that they are IPFS / IPNS compatible and forms the web3 way of chatting. This will include researching the best methods for using those features and porting the equivalent form that will be used to extend basic chat functionalities. Owing to the secretive nature of the feature plans, the entire list cannot be shared but it encompasses all features that web2 users love.

The milestone will also focus on enabling chat support for non-evms as well making the Push Chat powered by IPFS a true web3 chat, fully compatible with any chain and supporting any web3 users.

This milestone will be done by a team of 2 developers and 1 designer.
Timeline: 3 weeks.

Milestone 4

We will update the technical documentation to include information on how to use Push Protocol with IPFS and any changes that were made to the SDK, mobile app and Dapp as result of IPFS integration. This will include creating guides for users on how to use IPFS with Push Protocol and updating the documentation with any new features added to the SDK, mobile app and Dapp as a result of the integration.

This milestone is for improving the overall technical documentation about Push Chat, how it works, how to integrate and its applications.

This will be done by 1 technical writer.
Timeline: 1 week.

## Total Budget Requested

- Development: $50,000 - $60,000
- Testing and quality assurance: $10,000 - $20,000
- Launch and marketing: $10,000 - $20,000
- Maintenance and support: $10,000 - $20,000 per year

## Maintenance and Upgrade Plans

Push chat plan includes: 

- Regular updates: Release regular updates to the chat application to fix bugs, improve performance, and add new features. These updates could be released on a monthly or quarterly basis, depending on the needs of the chat application and the feedback received from users.
- Maintenance: Provide ongoing maintenance and support for the chat application to ensure that it remains stable and reliable. This could include fixing any issues that arise and providing technical support to users who need assistance.
- User feedback: Gather feedback from users on a regular basis to understand their needs and preferences and incorporate this feedback into the chat application through updates and new features.
- Security: Regularly review and update the chat application's security measures to ensure that it remains secure and resistant to attacks. This could include implementing new encryption techniques and addressing any vulnerabilities that are discovered.
- Compatibility: Ensure that the chat application is compatible with the latest versions of relevant software and devices, and make updates as necessary to maintain compatibility.
- Scalability: Monitor the performance and usage of the chat application, and make updates as necessary to ensure that it can scale to meet the needs of an increasing number of users.

# Team

## Team Members

- Harsh Rajat, Founder and Project Lead
- Richa Joshi, Co-founder and Marketing Lead
- Fabio Costa, Backend Lead
- Zaryab Afser, Smart Contract Lead
- Pranshu Rastogi, Ecosystem
- Everett Muzzy, Strategy Lead

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/harshrajat/
https://www.linkedin.com/in/richa-joshi-90b04126/
https://www.linkedin.com/in/zaryab-afser-97085b157/
https://www.linkedin.com/in/rastogipranshu/
https://www.linkedin.com/in/everett-muzzy/

## Team Website

`https://push.org/`

## Team code repositories

`https://github.com/ethereum-push-notification-service`

https://github.com/HarshRajat
https://github.com/strykerin
https://github.com/zaryab2000

# Additional Information
How did you learn about the Open Grants Program? --> Through Filecoin team
Please provide the best email address for discussing the grant agreement and general next steps. --> richa@epns.io

**Comment by realChainLife** [comment]
@richajoshi123 thank you for the proposal. 

- Can you share additional details about the architecture overview that will support the SDK x IPFS integration? 
- What are the core chat functionalities built into the mobile app that will benefit from the IPNS integrations? 
- Instead of the range shared here, do you have a specific budget request for the development of this work?

**Comment by pranshurastogi** [comment]
Hey @realChainLife !!

Here is the explanation of given queries:
A1: 
Push Chat is a secure and private messaging platform that prioritizes user privacy. The platform is developed by Push Protocol, and it allows users to send and receive messages without the need to share any personal information. This is achieved by using IPFS (InterPlanetary File System) as the underlying storage layer, where messages are stored encrypted and signed.
When a user sends a message, the Push Network validates the message payload and if it is accepted, the message is stored on IPFS. The recipient then receives a push notification alerting them of the new message. With more users utilizing Push Chat, the number of messages stored on IPFS increases, thereby contributing to the growth of IPFS usage.
Users can interact with the protocol via the Push dApp (https://app.push.org/), the Push SDK (https://github.com/ethereum-push-notification-service/push-sdk), or any other dApp or wallet that has integrated Push Protocol. Since Push Chat is platform agnostic, messages can be read and sent through any dApp or protocol that has integrated the platform.
The Push SDK is designed with ease of use in mind, making it simple for developers to integrate Push Chat into their own dApps and services. The SDK currently offers a REST API and a frontend SDK, with work underway on the mobile SDK.


A2:
IPFS is the underlying storage layer for all Push Chat messages and plays a crucial role in the platform's functioning. Its use ensures secure and reliable messaging for all users, contributing to the growth of both Push Chat and IPFS. Since all the chat messages are stored on IPFS, the chat app will need to resolve the CID for each message to get its content. To fetch the messages, the sdk calls our local ipfs node resolve the CID.


A3:
Development: $55,000
Testing and quality assurance: $10,000
Launch and marketing: $15,000
Maintenance and support: $15,000
TOTAL - $95,000

Do let us know, if you need anything else.

**Comment by ErinOCon** [comment]
Hi @richajoshi123, thank you for the additional details and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue to build!
