### ISSUE TITLE
Next Step Microgrant - TulaFIL <decentralized storage marketplace using FEVM>

### ISSUE THREAD

**Issue by heisenberg-of-web3** [filecoin-project/devgrants#1343]
### 1. What is your project, and what problem does it solve? (max 100 words)

TulaFIL is a decentralized marketplace for renting storage space on the Filecoin network. TulaFIL aims to solve the problem of a centralized storage marketplaces, where users have to rely on a single company or organization to store their data and have limited options for providers and pricing. With TulaFIL, users can easily search for and rent storage space from multiple providers on the Filecoin network, and can make payments using the native cryptocurrency FIL, giving users more control and flexibility over their storage needs.

### 2. Project links

Link to Github repo - [https://github.com/heisenberg-of-web3/tulaFIL](https://github.com/heisenberg-of-web3/tulaFIL)
FEVM Smart Contracts - [https://github.com/heisenberg-of-web3/tulaFIL/tree/master/src/contracts](https://github.com/heisenberg-of-web3/tulaFIL/tree/master/src/contracts)

Unit Tests - [https://github.com/heisenberg-of-web3/tulaFIL/tree/master/tests](https://github.com/heisenberg-of-web3/tulaFIL/tree/master/tests)

User Interface Components - [https://github.com/heisenberg-of-web3/tulaFIL/tree/master/src/components](https://github.com/heisenberg-of-web3/tulaFIL/tree/master/src/components)

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

In TulaFIL, IPFS is used for storing the data on the Filecoin network and generating a unique CID (Content Identifier) as a pointer to the data. Users can then use the CID to retrieve their data through the TulaFIL smart contract or other IPFS-enabled clients. The project also utilizes the Filecoin network for payments, allowing users to rent storage from providers using FIL, the native cryptocurrency of the network. The TulaFIL smart contract interacts with the Filecoin network (Via FEVM) for managing providers and rents.

### b) Is this project building with FVM?

Yes, TulaFIL uses FEVM for it’s smart-contracts, as it’s the only way to achieve this project on the Filecoin network.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

With the Microgrant, TulaFIL project will improve the scalability and security of the marketplace.

- By implementing a Factory contract, we will increase the ability of the contract to handle more providers, customers and transaction at the same time.
- It will also improve the security by implementing access controls, which will allow only authorized providers to add new storage or update prices, and by implementing off-chain encryption, which will keep the data private and secure.

In order to meet these objectives, the following steps will be taken:

- Research and evaluate different scalability implementations for the smart contract
- Implement access controls for providers in the TulaFIL contract using LightHouse and LitProtocol
- Research and evaluate off-chain encryption solutions
- Implement off-chain encryption for storing the data
- Test and deploy the updated TulaFIL contract on the Filecoin network

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

We will

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions

- If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: No

### Additional questions:

- For each team member(s), please list name, email, Github account, and role in the project.
Areeb Abbasi (Co-Founder + Core Developer) - abbasiareeb769@gmail.com - https://github.com/heisenberg-of-web3
Mahesh Dholakia (Frontend Developer) 
- How did you learn about our microgrant program? On Twitter

**Comment by ErinOCon** [comment]
Hi @heisenberg-of-web3, thank you for your proposal! We are sorry to let you know your project was not selected for a FVM microgrant at this time. Please note we are planning to release another round of grant funding in a few weeks. You are welcome to re-apply with the above or a future FVM project once the new grant funding round has been announced. Until the new founding round opens, no applications will be reviewed or accepted.

If you have already started building your project, we would like to encourage you to join the community of builders on Filecoin Slack and to consider submitting your project to the FVM Community Leaderboard, where the community votes bi-weekly on the top projects to win prizes from a $75k prize pool. Learn more [here](https://network-goods.notion.site/Impact-Evaluators-Builders-Leaderboard-602ea6755b5642e1ad6f9da59a47fa62).
