### ISSUE TITLE
Next Step Microgrant: 7Zen - KYC Service For Storage Providers

### ISSUE THREAD

**Issue by kritikriti** [filecoin-project/devgrants#1344]
### 1. What is your project, and what problem does it solve? (max 100 words)

7Zen is an open-source protocol that utilises zero-knowledge proof to provide an identity solution that allows users to verify their identities without disclosing sensitive personal information. The protocol addresses three key problems:

1. The Copy Problem: When users share personal information with regulated entities, they have no control over how that information is subsequently used, potentially leading to negative consequences such as data breaches or misuse.
2. The Bundling Problem: AML/CTF regulations only require specific data attributes to be verified, but often more personal data is collected and stored.
3. The Recursive Oversight Problem: Users have limited governance over their personal information once shared with a regulated entity, raising questions about how data protection regulations are enforced and who holds entities accountable for violations.

### 2. Project links

Link to Github repo & Tech Demo: [https://github.com/kritikriti/7zen-hackathon-project](https://github.com/kritikriti/7zen-hackathon-project)
License: GPL
Demo app: https://7zen.netlify.app/

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

7Zen is a protocol that uses decentralised technology, such as ZKP and MPC, to provide an identity solution that preserves users' privacy. In the 7Zen protocol, all participants have equal status and there are no third parties with privileged access.

In the secure multi-party calculation process, each party's input is kept independent and no raw data is exposed during the calculation process. All data is securely stored on IPFS for better protection and accessibility.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
Yes, this can be used to provide proofs against the claims of Storage Providers to prevent Sybil Attacks

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. Scalability optimisation: To handle a large number of users, we could work on ways to improve the scalability of the 7Zen protocol, such as optimising the use of sharding or off-chain computation.
2. User Interface : Developing a simple and intuitive user interface that makes it easy for users to interact with the protocol.
3. Security audit: Thoroughly reviewing the protocol to identify any potential vulnerabilities and develop solutions to address them
4. Research & Development of new features: Investing in research and development of new features that can improve the overall user experience, such as integration of ZKPs and MPC for new use cases or industries.
5. Community building and education : Developing educational resources, like tutorials, documentation and videos, to help people understand the benefits of the protocol and how to use it and facilitating community events and incentives to drive user engagement.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, I agree.

### 6. Does your proposal comply with our Community Code of Conduct?
Yes the project is compliant and completely open source.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Team Member - Kriti Sinha
Email - kritisinhaz51@gmail.com
GitHub - https://github.com/kritikriti
Role - Project Lead & Lead Developer

Team Member - Muskan Choudhary
Email - mchoudhary_creates@proton.me
Role - Designer

* How did you learn about our microgrant program?
Through twitter - [Link to the post](https://twitter.com/Filecoin/status/1607828416174202880?s=20&t=vfO4TFCIUSX1jNb4bU5EQg)

**Comment by ErinOCon** [comment]
Hi @kritikriti, thank you for your proposal! We are sorry to let you know your project was not selected for a FVM microgrant at this time. Please note we are planning to release another round of grant funding in a few weeks. You are welcome to re-apply with the above or a future FVM project once the new grant funding round has been announced. Until the new founding round opens, no applications will be reviewed or accepted.

If you have already started building your project, we would like to encourage you to join the community of builders on Filecoin Slack and to consider submitting your project to the FVM Community Leaderboard, where the community votes bi-weekly on the top projects to win prizes from a $75k prize pool. Learn more [here](https://network-goods.notion.site/Impact-Evaluators-Builders-Leaderboard-602ea6755b5642e1ad6f9da59a47fa62).
