### ISSUE TITLE
Next Step Microgrant: Employment Reference

### ISSUE THREAD

**Issue by metaversemoon** [filecoin-project/devgrants#1345]
### 1. What is your project, and what problem does it solve? (max 100 words)

Employment Reference is a safeguard for employers and employees to track their professional references, ratings, and job history all in one place. It is a dApp that brings transparency and accountability to all partners. Ultimately, decreasing wasted time and resources. If you are an employee you should be able to find your company and rate its management, installations, equipment, building, etcetera. If you are an employer you can register your company, provide employment references, and more.

Employment Reference is composed of 5 main features:
- A marketplace where companies and institutions can be listed by themselves or by users.
- Employment Reference Requester where employees or ex-employees can request professional reference letters from employers during the application process for a new position.
- Employment Reference is where users can share information.
- A job community page with all the company's information.
- Employment Reference Reviewer where employees or ex-employees can review companies in the following: employee satisfaction, employee healthy, prevent burnout, quality of life, increase company loyalty, employee engagement, paid leave, affordable health insurance, gym reimbursement, and tuition reimbursement.

Employment Reference is where workers come together and help each other by sharing helpful information to take the best decision about their job and career.

### 2. Project links

Link to Github repo: https://github.com/marcialarturo/decentralized-employee-referral
Link to demo: https://employment-reference.netlify.app/
License: MIT

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

Employment Reference is using IPFS and web3.storage to store every company listed within the platform. This includes the company’s name, description, website, location, address, images, and social handles. IPFS also is helping store the reference letters itself in different formats. Currently, we accept pdfs and images but we are expanding this feature. When a new company registers within Employment Reference App all its data is uploaded and stored through IPFS's interface in a decentralized manner. This process returns a CID that is saved in the smart contract and we use it to populate our front end.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No)
Yes

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

 Improvements
- UX/UI: come up with a clean design, for this, I am planning to hire a designer. Once the design is ready, it will take me about a week to update it.
- CI/CD: I would like to add continuous integration using circleci and Skynet. This probably will take me a few days.
- Fix the file upload functionality and make it as seamless as possible for a better user experience.
- Leverage the number of requests made by the front end by adding a way to cache the previous requests.

**New features:**
-  Chat functionality: it’s one of the most important features of my application. It will allow users to send and receive personal messages from other users and companies.

- Adding a dynamic search for companies

- Another feature is the `send a recognition NFT` feature. This will allow companies to provide awards to their employees for their hard work.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes it does

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes, I have submitted it. Here is the link https://ethglobal.com/showcase/employement-reference-dq4da
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
   - Albert - metaversemoon@gmail.com - 4metaverse - software engineer
   - David - bycoolcodes@gmail.com - coolcodes23 - developer
   - Arturo - realcheapny@gmail.com - realcheapny - frontend developer

* How did you learn about our microgrant program?
They emailed me and suggested to apply

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
  https://ethglobal.com/showcase/employement-reference-dq4da

**Comment by ErinOCon** [comment]
Hi @metaversemoon, thank you for your proposal! We are sorry to let you know your project was not selected for a FVM microgrant at this time. Please note we are planning to release another round of grant funding in a few weeks. You are welcome to re-apply with the above or a future FVM project once the new grant funding round has been announced. Until the new founding round opens, no applications will be reviewed or accepted.

If you have already started building your project, we would like to encourage you to join the community of builders on Filecoin Slack and to consider submitting your project to the FVM Community Leaderboard, where the community votes bi-weekly on the top projects to win prizes from a $75k prize pool. Learn more [here](https://network-goods.notion.site/Impact-Evaluators-Builders-Leaderboard-602ea6755b5642e1ad6f9da59a47fa62).
