### ISSUE TITLE
RFP Application: Edge + ZEC Upgrades + Filecoin

### ISSUE THREAD

**Issue by rjrs2k** [filecoin-project/devgrants#1346]
# RFP Proposal: `Edge + ZEC Upgrades + Filecoin`

**Name of Project:** Edge + ZEC Upgrades + Filecoin

**Link to RFP:** https://github.com/filecoin-project/devgrants/blob/master/rfps/zcash-and-filecoin.md

**RFP Category:** `app-dev`

**Proposer:** `rjrs2k`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes

# Project Description

Edge is an open-source, non-custodial, and privacy focused wallet that is available on iOS/Android that has multi-asset support, swap, and staking functionality. 

Edge currently already supports ZEC and would like to add ZEC upgrades as well as the integration of Filecoin.

By implementing the upgrades with ZEC on Edge this will provide a better user experience for existing ZEC users on Edge as well as another wallet option for ZEC users looking for a wallet with our proven track record and core values. 

By supporting Filecoin on Edge this would help grow the user base of Filecoin with Edge's already existing millions of users.

Edge would like to integrate the following:

1. Auto Shielding
2. Unified Addresses
3. Upgrade to Latest Shielded Pool
4. Memo Fixes
5. Halo2/Fast Sync
6. Filecoin and Delegated Staking to Validators

Completing this project will help grow the ecosystems for ZEC and Filecoin by providing a wallet that has a proven track record which is open-source, private, and non-custodial that has NEVER been hacked and has been around since 2014. In addition, Edge has been providing phone support since 2014 where a user that needs help can speak with an actual human being and we hope to continue that and be able to provide the best user experience and support with both ZEC and Filecoin.

## Development Roadmap

**Milestone 1**
- **Auto Shielding:** Automatically move funds from a transparent address to the latest shielded ZEC pool
- **Unified Addresses:** A single unified address that is compatible to all Zcash pools shielded and transparent

**Milestone 2**
- **Upgrade to Latest Shield Pool:** Ensure that Zcash is automatically stored in the latest shielded pool regardless of the sender's address type
- **Memo Fixes:** Allow for a memo field in Zcash shielded transactions. This would allow a sender to include information to the receiver which would be completely encrypted.

**Milestone 3**
- **Halo 2 Upgrade/Fast Sync:** Reduce the time it takes for a Zcash wallet to sync
- **Filecoin Delegated Staking to Validators:** Add support in Edge for users to be able to create a Filecoin wallet where they can send, receive, or store Filecoin on Edge while also still being able to swap out of or into Filecoin using Edge's swap functionality. In addition the ability to do delegated staking to validators.

## Documentation, Education, and Community

1. Update documentation in training to make sure that Edge QA and Support staff are adequately trained in being able to identify issues and resolve customer issues related to ZEC/Filecoin
2. Update FAQ and related articles for ZEC/Filecoin for common troubleshooting steps and for education in learning more
3. Continued ZEC meetups at Edge Headquarters to promote and educate users 
4. The possibility of hosting Filecoin meetups and educational events at Edge Headquarters
5. Edge has been doing meetups since 2014. For example here is one with Zcash - https://www.meetup.com/bitcoin-san-diego/events/283205603/ - Josh Swihart SVP of Growth at Electric Coin Co. (ECC)
6. Livestreams for example https://www.youtube.com/watch?v=mbhHDm6entw - Paul Puey, Zooko Wilcox, and Naomi Brockwell

## Other Deliverables

Other deliverables related to this project are:

1. Marketing efforts via Newsletters, Blog posts, Social Media such as Twitter/Facebook/Instagram and Website announcements of the upgrades and integrations of ZEC and Filecoin
7. Possible joint marketing efforts with the ZEC and Filecoin teams
8. Articles and YouTube/Twitter Livestreams of ZEC and Filecoin

## Milestone Summary

**Summary of milestones**

Milestone 1 - Approximately 104 hours or 13 business work days or a little over 2 weeks to implement Auto Shielding and Unified Addresses.
Milestone 2 - Approximately 80 hours or 10 business work days or 2 weeks to implement Upgrade to Latest Shield Pool and Memo Fixes.
Milestone 3 - Approximately 120 hours or 15 business work days or 3 weeks to implement Halo 2/Fast Sync and Filecoin and Delegated Staking to Validators

The man hours covered is for Engineering and QA in making sure each feature is properly developed and thoroughly tested.

**How many people will be working on each milestone and their roles**

A total of 8 people involving 5 Engineers and 3 QA

**The amount of funding required for each milestone**

Milestone 1 - $28,000
Milestone 2 - $28,000
Milestone 3 - $42,000

**How much time this milestone will take to achieve (using real dates)**

Milestone 1 - Approximately 2 weeks from 3/1/23 - 3/15/23
Milestone 2 - Approximately 2 week from 3/16/23 - 3/30/23
Milestone 3 - Approximately 3 weeks from 4/1/23 - 4/22/23

**Note, our team is able to start even sooner. We can begin as soon as February 1st, 2023 if this proposal is approved.**

| Milestone No. | Milestone Summary & Staffing | Funding | Estimated Timeframe |
| ------------- | --------------------- | ------- | ------------------- |
| 1             | Auto Shielding and Unified Addresses     | $28,000      | 2 weeks             |
| 2             | Upgrade to Latest Shielded Pool and Memo Fixes     | $28,000      | 2 weeks             |
| 3             | Halo 2/Fast Sync and Filecoin    | $42,000      | 3 weeks             |

## Total Budget Requested

$98,000

## Maintenance and Upgrade Plans

Edge plans to continue to maintain and support functionality for ZEC and Filecoin with continued resource allocation from our engineers. In addition, both QA and Support will continue to make sure that any new bugs that are introduced are identified and fixed as well as any user support issues are properly helped by the Support team.

Edge also plans to make sure that swap functionality continues to be supported with our partner integrations.

# Team

## Contact Info

RJ Raljoseph Ricasata - rj@edge.app

## Team Members

- **CEO Paul Puey** is a proud Electrical Engineering and Computer Science graduate of UC Berkeley with a wide range of technical skills from low-level 3D graphics engineering to development of custom web CMS systems, even before people knew what a CMS was. He held lead engineering positions with Nvidia and Chromatic Research.

https://www.linkedin.com/in/paulpuey/
https://twitter.com/paullinator
https://github.com/paullinator

- **Chief Architect William Swanson** has been writing software since he was 11 years old. Although he has a degree in Electrical Engineering from Cal Poly San Luis Obispo, he is just as comfortable working with software as he is with electronics. He has built systems at every level of the technology stack, from custom circuit boards with embedded firmware up through websites and 3D graphics applications.

https://www.linkedin.com/in/william-swanson-834089a6
https://github.com/swansontec

- **Head of QA RJ Raljoseph Ricasata** has had the honor and privilege of working with Edge since 2014 to this day with Edge and has had an incredible journey with a front row seat in crypto since 2012 to witness the space evolve to where it is today. RJ is a Certified Project Management Professional (PMP), MBA, and has an accounting background.

https://www.linkedin.com/in/rjricasata/
https://twitter.com/rjrs2k
https://github.com/rjrs2k

## Team Website

https://edge.app/

## Relevant Experience

Edge formerly known as Airbitz has been around since 2014 and is one of the few open source and non-custodial wallets that still exist today. Edge consists of a team that has been in the cryptocurrency space as early as 2012 and with core values of privacy and in being open source.

Edge has finished through many projects successfully and some of those implementations are:

1. XRP & Monero - https://edge.app/blog/company-news/edge-wallet-monero-ripple-xrp/
9. TOMB Swap & Staking - https://edge.app/blog/company-news/edge-adds-support-for-tomb-staking/
10. ZEC - https://edge.app/blog/company-news/edge-adds-support-for-zcash/
11. Built in AAVE Loans - https://edge.app/blog/company-news/defi-crypto-loans-via-aave/
12. Thorchain Swaps - https://edge.app/blog/company-news/edge-adds-support-for-thorchain-swaps/
13. Thorchain Savers - https://www.youtube.com/watch?v=pv_MS9DZz1s
14. FIO Protocol & FIO Staking - https://edge.app/blog/company-news/edge-adds-support-for-fio-staking/
15. Many more! We are happy to provide additional references of other projects we have completed.

## Team code repositories

https://github.com/EdgeApp

# Additional Information

Airbitz Inc was founded in 2014, and rebranded to Edge, a self-custody exchange platform, in 2017. Since then, we have been focused on increasing functionality, expanding our global accessibility, and growing our presence in the crypto space by sponsoring conferences and hosting our own monthly meetups, with notable speakers and influencers. We support over 177 different fiat payment methods around the world and support over 130 assets. We have created a “best price option” which automatically searches through our swap exchange partners that provides the best price for a given pair. We have reached over 3+ million accounts created and our exchange volume has grown 3-4x year over year.

Edge is known as being the first open-source, non-custodial, and multi-asset wallet with swaps built into it to support XRP and Monero. We want to continue to build on ZEC and integrate Filecoin on Edge and provide users of these ecosystems with an open-source and privacy focused wallet yet still familiar and easy to use.

We’re building for the next billion users in mind where the wallet must be familiar and secure yet still allows users complete privacy and full custody and ownership of their keys without even Edge ever having access or knowledge.

**Comment by ErinOCon** [comment]
Hi @rjrs2k, since this project has cleared the final milestone review, I have closed out the. Issue. Please contact our team at grants@fil.org if you have any outstanding questions.
