### ISSUE TITLE
Polysnap - Wrappers

### ISSUE THREAD

**Issue by PolyWrapper** [filecoin-project/devgrants#1347]
### 1. What is your project, and what problem does it solve? (max 100 words)
With the current state, You need to build new snaps for every capability you want to add to your Metamask extension. Polysnap allows you to execute any WASM wrappers deployed on IPFS on the fly without needing to build a new snap. You can also write these wrappers in any language that supports WASM as a compilation target (Ex: Assemblyscript, Rust, TinyGo, etc) instead of just writing it in JS.

### 2. Project links
  
Link to Github repo: https://github.com/PolyWrapper/Polysnap
Link to demo or website, if applicable: https://www.loom.com/share/1091982f55bf4d3394c036e10787098d?t=61
<img width="361" alt="Screenshot 2023-01-13 202521" src="https://user-images.githubusercontent.com/122609889/212350012-798a480c-be98-4340-b2c0-16406509110a.png">

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

We deploy wrappers directly to IPFS Storage.

b) Is this project building with FVM? (Yes or No)
Not Currently. But we intend to build different solutions catering to FVM.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective?

Scale up the platform to handle the computation of all wrappers. We will be Onboarding a Rust Developer. 

Designing and developing the UI to take care of execution that helps with multiple wrappers. 

Build the foundation to handle the ENS Wrapper Functionality and append it to the existing flow. 

Finally, contributing to the [[wrapper.io](http://wrapper.io/)](http://wrapper.io) to add more Wrappers built for the IPFS indexes.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

   Winners for the IPFS/Filecoin - General Storage track - Top 3 at Eth India: 

   The project Submission on Devfolio : https://devfolio.co/projects/polysnap-8c87

  
### Additional questions:

* For each team member(s), please list name, email, Github account, and role in the project.
    Name: Niraj 

    Email: kamdarniraj3@gmail.com

    GitHub: https://github.com/PolyWrapper/Polysnap

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
   Eth India
  * Please link to your hackathon submission
  https://devfolio.co/projects/polysnap-8c87

**Comment by ErinOCon** [comment]
Hi @PolyWrapper, thank you for your proposal. It looks like this project repo is using code from [here](https://github.com/Niraj-Kamdar/Polysnap). Can you confirm how these accounts are related?

**Comment by ErinOCon** [comment]
Hi @PolyWrapper, we will not be moving forward with a grant at this time. Wishing you the best as you continue to build.
