### ISSUE TITLE
Next Step Microgrant: GitVerse

### ISSUE THREAD

**Issue by GitVerse-Web3** [filecoin-project/devgrants#1349]
### 1. What is your project, and what problem does it solve? (max 100 words)
Project name: Gitverse
Vision: To become a value network for global open-source projects and their developers
Mission: Realize the value network of open-source projects and incentives for developers through programmable code NFTs and decentralized code storage.

We use the nft.storage SDK to upload user's code to IPFS.

### 2. Project links
  
Link to Github repo: https://github.com/GitVerse-HQ/gitverse
Link to demo or website, if applicable: 
        It include a cli tool and UI, 
           * Cli tool: pls check video demo: https://www.youtube.com/watch?v=0eBAB9rtWJI 
           * UI: https://dev-app.gitverse.co
License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
We add the nft.storage SDK to make our project support file upload to IPFS https://github.com/GitVerse-HQ/gitverse/blob/main/src/storage/nft_storage.js.

###    b) Is this project building with FVM? (Yes or No)
  No, We are working on it now!

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
* Make it work on FVM: Deploy our contract on to the FVM
* Refactor our CLI code to be more flexible

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  No

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
|  name   | email  | github | 
|  ------  | -----  | -----  |
| Yiko | jam_1992@163.com | TecSong |
| Protobia | keencode.eth@gmail.com | GitVerse-Web3 |

* How did you learn about our microgrant program?
https://spacewarp.fvm.dev/

* If your project was created as part of an event or hackathon:
No

**Comment by ErinOCon** [comment]
Hi @GitVerse-Web3, thank you for your proposal! We are sorry to let you know your project was not selected for a FVM microgrant at this time. Please note we are planning to release another round of grant funding in a few weeks. You are welcome to re-apply with the above or a future FVM project once the new grant funding round has been announced. Until the new founding round opens, no applications will be reviewed or accepted.

If you have already started building your project, we would like to encourage you to join the community of builders on Filecoin Slack and to consider submitting your project to the FVM Community Leaderboard, where the community votes bi-weekly on the top projects to win prizes from a $75k prize pool. Learn more [here](https://network-goods.notion.site/Impact-Evaluators-Builders-Leaderboard-602ea6755b5642e1ad6f9da59a47fa62).
