### ISSUE TITLE
Next Step Microgrant - Greenplicity

### ISSUE THREAD

**Issue by shivansh-link** [filecoin-project/devgrants#1350]
### 1. What is your project, and what problem does it solve? (max 100 words)

Greenplicity is a decentralized application that aims to promote the use of renewable energy by creating a transparent and efficient market for energy certificates. The project utilizes the Filecoin network for decentralized storage and smart contracts for creating and managing energy certificates. It solves the problem of lack of transparency and trust in the current energy certificate market by providing a secure, tamper-proof and transparent platform for recording and trading energy certificates. Greenplicity allows energy producers to easily create and sell certificates of their renewable energy production, and it allows consumers to easily purchase and verify the certificates. The project is intended to make it easier to buy and sell energy certificates, which in turn will help to increase the use of renewable energy.

### 2. Project links

Link to Github repo:
Energy Certificate Manager - [https://github.com/shivansh-devgen/greenplicity](https://github.com/shivansh-devgen/greenplicity)

Javascript SDK - [https://github.com/shivansh-devgen/greenplicity-sdk](https://github.com/shivansh-devgen/greenplicity-sdk)

License: [MIT](https://opensource.org/licenses/MIT)

Demo (Alpha Build): https://greenplicity.netlify.app/

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

In Greenplicity, we use the Filecoin network to build a decentralized and trustless marketplace for energy certificates. The Filecoin network provides a decentralized storage layer for energy certificates and related data, ensuring that the data is tamper-proof and always available.

We leverage the decentralized storage layer of Filecoin to provide immutability and transparency for the energy certificates, which is crucial for the integrity of the certificates, and for the trust of the consumers in the system. By using Filecoin, we can guarantee that the certificates are stored in a decentralized manner and that the data is accessible to anyone with the proper permissions, allowing for easy verification of the certificates by consumers.

We also leverage the built-in economic incentives of the Filecoin network to attract storage providers to the platform and ensure that the data is always available. This allows for a dynamic storage market that adapts to the demand and supply of the energy certificates, making it more efficient.

Usage of Filecoin can be found in these files - 
[Here](https://github.com/shivansh-link/greenplicity/blob/master/pkg/greenplicity.go#L57)
[Here](https://github.com/shivansh-link/greenplicity/blob/master/pkg/greenplicity.go#L22)

### b) Is this project building with FVM? (Yes or No)

No

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- Establish partnerships with companies in the renewable energy industry to showcase the benefits of using Greenplicity and the Filecoin network for managing energy certificates.
- Attend relevant industry conferences and events to network and establish relationships with potential partners.
- Develop and improve the decentralized storage functionality of the application using Filecoin network by optimizing storage, retrieval and data integrity of energy certificates.
- Conduct marketing campaigns and organize events to raise awareness of the benefits of using renewable energy and the Greenplicity project.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes

### 6. Does your proposal comply with our Community Code of Conduct?

yes

### 7. Links and submissions

- If your project began at a hackathon, have you submitted it for the
relevant Protocol Labs prizes? Include links here if available:

### Additional questions:

- For each team member(s), please list name, email, Github account, and role in the project.

****Shivansh Yadav****

Full Stack Developer (Go + JS) 

[shhhivank80@gmail.com](mailto:shhhivank80@gmail.com)

[https://github.com/shivansh-link/](https://github.com/shivansh-link/)

**Rakesh Verma**

Backend / GoLang developer

- How did you learn about our microgrant program? On linkedin
- If your project was created as part of an event or hackathon:
    - What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks
    hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
    - Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @shivansh-link, thank you for your proposal. We will not be moving forward with a grant at this time. For next steps, you may have an interest in checking out a [hackathon](https://hackathons.filecoin.io/)!

Wishing you the best as you continue to build!
