### ISSUE TITLE
Next Step Microgrant: Bacalhau-Powered GIS System (Oil Palm Tree Segmentation)

### ISSUE THREAD

**Issue by jimcoco** [filecoin-project/devgrants#1351]
### 1. What is your project, and what problem does it solve? (max 100 words)

This project is mainly powered by Bacalhau and IPFS, which focuses on tree segmentation tasks in the GIS domain (especially for plantation) and helps users to process massive LIDAR-based terrain datasets, easing the research or analyzing related tasks (obtaining vegetation metrics, disease detection, etc.) for each individual vegetation on that terrain. The program provides an all-in-one pipeline to process the raw LAS or LAZ (LIDAR point cloud files) into individual vegetation point cloud files. This process includes the pre-processing and classification of point cloud raw data, height normalization process, canopy height model (CHM) generation and smoothing, tree tops filter, segmentation Dalponte algorithm, as well as convex hull building.

![image](https://user-images.githubusercontent.com/118844558/206871283-03ab3bdd-86ce-4a03-bd57-f8aca90c0ce3.png)

### 2. Project links
  
GitHub Repo: https://github.com/jimcoco/Bacalhau-GIS

License: MIT
  
#### Implementation of IPFS

As raw LIDAR datasets of terrain are usually massive in file size due to the high resolution (number of points in the point cloud) needed for post-processing, hence came out with a storage solution that uses IPFS and only fetched the required datasets for processing and calculations from the clusters via API. We will also be building a comprehensive index library to store all our oil palm terrain datasets (for research purposes) which are powered by IPFS and create an ecosystem connection between plant science research institutes in Singapore.

#### Implementation of Bacalhau

All the tree segmentation calculation processes (pipeline) will be running on the Bacalhau network, which includes pre-processing and classification of raw LiDar data, ground point normalization, CHM generation and smoothing process, ITD process, and convex hull generation. By taking advantage of the open compute resources and our catalog form calculation technique, we are able to process our large datasets much faster and more cost-friendly.

###    b) Is this project contributing to the upcoming FVM launch? (Yes or No) 

No, it is not for the FVM launch.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We currently have two student teams working on this project. Below is the milestone that we plan to achieve in these three months of the grant period. 

*Note: If there is a delay in the grant approval time, I will update the milestone plan accordingly. 

#### Milestones
- Algorithm and calculation advancement which implement machine learning to help user to find their optimum settings for dataset training, enhancing the user experience of parameter tuning. [February-Mid of March: Team A]
- IPFS-powered oil palm index library setup [February-March: Team B] 
- Bacalhau integrations [March-April: Team A and Team B]
- Frontend design and development [April-Mid of April: Team B. Design will be outsourced to a professional UI/UX design team]
- Hosting and final testing [End of April]

#### Deliverables
- Stronger algorithm and calculation in tree segmentation and analysis task
- IPFS-powered oil palm dataset library
- Bacalhau-powered calculation process which will connect to our frontend application
- Oil palm tree shape files (for analysis) and reports which can be stored on IPFS easily

More improvement and development will be made by our team and the product will be released to the public at end of May or early June. Currently, we will be focusing on the Beta version for oil palm research institutes in Singapore.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?

Yes, I'm happy to share the progress and final result of the major update funded by this microgrant! Our youth organization will also write blogs during the development period and give credit to the help of this microgrant (Filecoin).
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions

I am focusing on the development of this project and it is not submitted to any hackathon currently.
  
### Additional questions:

Person of contact:
Name: Jim Whittington
GitHub: https://github.com/jimcoco
Email: cocomelon.web3@gmail.com
Role: Leader of a non-profit GIS student organization, CM GIS Singapore

* How did you learn about our microgrant program?

I had participated in previous IPFS and Filecoin hackathons and had learned about this microgrant program from the hackathon manager (email received post-hackathon)

* If your project was created as part of an event or hackathon: No

**Comment by ErinOCon** [comment]
Hi @jimcoco, this microgrant has been approved! We will send an email to confirm payment details. Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
