### ISSUE TITLE
Digital factory intelligent logistics project

### ISSUE THREAD

**Issue by SiGe-Technology** [filecoin-project/devgrants#1353]
### 1. What is your project, and what problem does it solve? (max 100 words)

Digital factory intelligent logistics project, the project will use intelligent equipment such as AGV intelligent vehicle (Automated Guided Vehicle), through special landmark navigation automatically transport items to the designated location, in the factory, logistics, warehousing can assist and replace human.
AGV (Automated Guided Vehicle), which automatically transports items to designated locations by navigating through special landmarks.
In this digital factory project, we will monitor and control the on-site logistics automation, logistics scheduling and cost settlement.

### 2. Project links
  
Link to Github repo: https://github.com/datahome73/AGV-Scene-DEMO
Link to demo or website, if applicable:
License:

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

The project plan：
It will digitize and store the publicly available drawings of the industrial design of smart devices into the IPFS/Filecoin network, so that the relevant stakeholders of the project, such as manufacturers and owners, can realize sharing and continuous optimization.
The actual working locations are converted into semantic maps and stored in the IPFS network for the intelligent devices to plan their routes.
It will monitor the actual operation of the smart devices, the lines, and store the monitoring videos and pictures to IPFS/Filecoin network. To provide a basis for subsequent optimization of lines and optimization steps.
Create a smart contract for FVM to calculate the actual storage space used in the IPFS network, as a basis for settlement with storage providers.

###    b) Is this project building with FVM? (Yes or No)  
Yes, this project building with FVM. The core is to make a fair and equitable billing system.
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

With this grant, we will be able to accelerate our development with FVM and deploy our smart contracts related to decentralized database backup and project usage/cost estimation. And we will be able to further improve our UI/UX design for the project, as well as the subsequent addition and implementation of features.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  Yes, I agree.
### 6. Does your proposal comply with our Community Code of Conduct?

Yes the project is compliant and completely open source.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Dahong Chen, datahome@21cn.com, Product Manager 
Liangfang Lin,, Project Manager
Sidon Liu,, Architect
Fei-Ling Cai,, Lead Programmer
Liu Handong, Programmer
Zhu Maofeng, Programmer 

* How did you learn about our microgrant program?

We learned about it through some small technical forums.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by datahome73** [comment]
Please join in the project construction。

**Comment by ErinOCon** [comment]
Hi @SiGe-Technology, thank you for your proposal! We are sorry to let you know your project was not selected for a FVM microgrant at this time. Please note we are planning to release another round of grant funding in a few weeks. You are welcome to re-apply with the above or a future FVM project once the new grant funding round has been announced. Until the new founding round opens, no applications will be reviewed or accepted.

If you have already started building your project, we would like to encourage you to join the community of builders on Filecoin Slack and to consider submitting your project to the FVM Community Leaderboard, where the community votes bi-weekly on the top projects to win prizes from a $75k prize pool. Learn more [here](https://network-goods.notion.site/Impact-Evaluators-Builders-Leaderboard-602ea6755b5642e1ad6f9da59a47fa62).
