### ISSUE TITLE
Next Step Microgrant: <Dao Risk Control System Apply Microgrant>

### ISSUE THREAD

**Issue by qingfengzxr** [filecoin-project/devgrants#1355]
### 1. What is your project, and what problem does it solve? (max 100 words)

The decentralized Dao Risk Control System, based on the idea of DAO, is completely autonomous by the community. The project is a risk control system for all web3 users. It is designed to help users predict risks in advance, reduce the probability of users being cheated, and protect users from property loss or danger。IPFS will be used to support multiple types of evidence.
More information can be found at this url: https://ghuuti.gitbook.io/drcs/

### 2. Project links
Link to Github repo: https://github.com/qingfengzxr/DRCS/tree/develop
Link to demo or website, if applicable: There is no demo that can be viewed on the public network
License:GPL

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
I hope to use ipfs to provide users with more evidence styles, such as pictures, videos. This cannot be accomplished by ETH alone. The cost is too high. At the same time, the project is expected to migrate to FVM, possibly refactoring with Rust to support more features, such as roloidity search, that require the capabilities of the programming language itself and are difficult for Solidity to accomplish.

###    b) Is this project building with FVM? (Yes or No)
No yet. But  will build with FVM soon.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
The money will be used to advance the development of the project.
1) Find professional UI design teams and front-end developers to design better UI interactions.
2) Improve the current Sol code logic as the initial version
3) Access IPFS to provide picture and video evidence support
4) Use Rust to build FVM available programs to provide more powerful functional support

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Agree
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
name: cooper
email: xiaoyao1441546669@163.com
github account: qingfengzxr
role: project leader & developer

* How did you learn about our microgrant program?
From the filecoin website, I have been following filecoin.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @qingfengzxr, thank you for your proposal. We will not be moving forward with a microgrant at this time, but you may have an interest in [hackathon](https://hackathons.filecoin.io/) and [Space Warp](https://spacewarp.fvm.dev/) opportunities as you continue to build. 

Wishing you the best with your building progress!
