### ISSUE TITLE
Next Step Microgrant: PodShip

### ISSUE THREAD

**Issue by DevABDee** [filecoin-project/devgrants#1356]
### 1. What is your project, and what problem does it solve? (max 100 words)
PodShip is a Decentralized Podcast Sharing & Streaming Platform. PodShip empowers Podcasters to upload their podcasts over a decentralized Internet and mint it as an NFT. 

### 2. Project links
  
Link to GitHub repo: [PodShip Github Organization](https://github.com/PodShip)
Link to demo or website: [PodShip Live Demo](https://main.d1xz58n1iiqqx5.amplifyapp.com/)
New UI/UX Designs: [PodShip Figma](https://www.figma.com/file/Fu5KXe6gGL2qO3HaLQVfdx/Web3Quest---Podship-Website?node-id=0%3A1&t=TRYgc01k1DYvNfd8-0)
License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
* It uses NFT.storage (SDK) for Podcast NFTs metadata storage
* Uploads podcasts over a decentralized internet i.e IPFS & FIlecoin

###    b) Is this project building with FVM? (Yes or No)
Yes, we deployed to the Filecoin Wallaby: `xcc4E8Ce3fAc29a6d816AF7CFE396781A91CdD3c5`
We want a multi-chain application and FVM deployment is in our plans.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
* Front-End Development (According to the new UI Designs)
* New Features addition e.g Upvote & Gasless TRXs features
* Smart Contracts Audit
* Mainnet Deployment
* Developer & Designer Payments

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, we agree to share grant reports upon request.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes, we have read the code of conduct.

### 7. Links and submissions
Yes, [PodShip](https://devpost.com/software/podship) won the Filecoin - Web3Fy Prize in the [Chainlink Hackathon](https://devpost.com/software/podship). 
  
### Additional questions:
* For each team member(s), please list name, email, GitHub account, and role in the project.
* Team member 1:
 Name: ABDul Rehman (DevABDee)
 Role: Smart Contract Developer & Product Manager
 Email: devabdee@gmail.com
 Github: https://github.com/DevABDee
* Team member 2:
 Name:  Norbert Frank (Virae)
 Role: Backend & TheGraph Developer
 Email: norbertmbafrank@gmail.com
 Github: https://github.com/NorVirae
* Team member 3:
 Name: Albert (Electrone)
 Role: Front-end developer
 Email: metaversemoon@gmail.com
 Github: https://github.com/electrone901
* Team member 4:
 Name: Habib Kaghas
 Role: Front-End & IPFS Developer
 Email: habibkaghas@gmail.com
 Github: https://github.com/HABIBKAGHAS
* Team member 5:
 Name: Ihtisham Ullah
 Role: Smart Contract Developer
 Email: ihtishamullah174@gmail.com
 Github: https://github.com/ihtisham-sudo
* Team member 5:
 Name: Argjent Ramiqi
 Role: UI/UX Designer
 Email: argjent.ramiqi.19@gmail.com
 Behance: https://www.behance.net/argjent_ramiqi

* How did you learn about our microgrant program? 
From the Chainlink Hackathon's Prize notification email.

* If your project was created as part of an event or hackathon:
  * What was the name of the event?
  Chainlink Fall Hackathon 2022

  * Please link to your hackathon submission
   https://devpost.com/software/podship

#### Extras:
PodShip Twitter: [PodShipNFT](https://twitter.com/PodShipNFT)

**Comment by ErinOCon** [comment]
Hi @DevABDee, thank you for your proposal! We are sorry to let you know your project was not selected for a FVM microgrant at this time. Please note we are planning to release another round of grant funding in a few weeks. You are welcome to re-apply with the above or a future FVM project once the new grant funding round has been announced. Until the new founding round opens, no applications will be reviewed or accepted.

If you have already started building your project, we would like to encourage you to join the community of builders on Filecoin Slack and to consider submitting your project to the FVM Community Leaderboard, where the community votes bi-weekly on the top projects to win prizes from a $75k prize pool. Learn more [here](https://network-goods.notion.site/Impact-Evaluators-Builders-Leaderboard-602ea6755b5642e1ad6f9da59a47fa62).
