### ISSUE TITLE
Next Step Microgrant: <DeStore Network Digital Twin (NFT) IPFS Storage>

### ISSUE THREAD

**Issue by Doinglifewell** [filecoin-project/devgrants#1358]
![Group 1134](https://user-images.githubusercontent.com/72717548/211964308-2aa199e0-6d1b-4da4-9632-a50e8119880e.png)

### 1. What is your project, and what problem does it solve? (max 100 words)
The DeStore platform aims to facilitate the adoption and management of Phygital Assets, which are physical assets connected to a Digital Twin. By utilising blockchain technology, DeStore enables the creation, management, and trading of these assets, with the goal of providing pathways for small to medium enterprises (SMEs), Creators, and decentralised autonomous organisations (DAOs) to expand their brand and sell real-world products on web 3.0 infrastructure.

### 2. Project links
  
Link to GitHub repo: - [Link](https://github.com/DeStore-Network)

MVP Demo: - [Link](https://drive.google.com/file/d/1A-BQGZOCe2leUgtjYblk_JUXMYdB15pB/view?usp=share_link)

Pitch Deck: - [Link](https://docs.google.com/presentation/d/1CHO5uBlfinzwrqDb31qAylNZDZ4pb26iAWWs36LnXwY/edit#slide=id.g1b8def4b5a1_0_49)

Kusama delegated merchandise distributor motion approval: - [Link](https://kusama.polkassembly.io/motion/562)

Development website: - [Link](https://development.destore.network/)
 _"Please note we are currently updating our Decentlised ID login, only google login is currently available"_ 
  
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

Our mission at DeStore is to revolutionise e-commerce by creating a secure and decentralised marketplace that empowers users. By integrating Filecoin's decentralised storage and compute solutions, we aim to provide a tamper-proof, highly available, and cost-effective platform for data storage and transactions. By leveraging the power of Web 3.0 computing technology, we aim to eliminate the need for centralization and third-party trust, driving innovation and trust in e-commerce. Our goal is to create a platform that is not only secure, but also accessible, open, and fair for all, ultimately leading to a more equitable economy. In order to achieve full decentralisation, DeStore is seeking a long-term collaboration with Filecoin, with the expectation of integrating the Filecoin Virtual Machine (FVM) to perform computations on a globally distributed backend, providing a secure and tamper-proof environment, which will bring transparency and immutability to the backend of DeStore Network.

###    b) Is this project building with FVM? 
(no) We intend to build on FEVM on wallaby & buildernet as a part of FVM Spacewarp program. Currently deployed to a few chains via Polkadot.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
On receipt of this micro-grant, DeStore plans to integrate Filecoin's IPFS storage solution into our protocol and offer a GitHub repository under the Apache 2.0 license to the Filecoin community.

Currently, DeStore is minting Digital Twins (NFTs) on Pinata.cloud based on the RMRK standard, which is a substrate-based standard for the Polkadot ecosystem and considered as an NFT 2.0 equivalent for the Polkadot ecosystem. By integrating Filecoin's IPFS into our platform, we aim to offer our users the ability to mint and store Digital Twins data on the Filecoin network via NFT.Storage, providing them with a decentralised IPFS solution.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?
On receipt of this micro-grant, DeStore will allocate a developer and manager to create a GitHub repository under the Apache 2.0 license, so that users can mint using the RMRK 1.0 standard and store NFT data on the Filecoin network.

### 6. Does your proposal comply with our Community Code of Conduct?
(Yes)

### Additional questions:
* For each team member(s), please list name, email, GitHub account, and role in the project.

**Josiah Kotzur**
CEO/Founder
- [GitHub](https://github.com/Doinglifewell)
- [Email](josiahkotzur3@gmail.com)

**James F**
Lead Developer
- [GitHub](https://github.com/TopCodeBeast)
- [Email](maxb47163@gmail.com)

**Levi Kotzur** 
Casual Developer
- [GitHub](https://github.com/Hammy227)
- [Email](Levi.Kotzur@gmail.com)

### How did you learn about our microgrant program?
Referred by our technical sponsor Jenks Guo ([jenks@fil.org](mailto:jenks@fil.org)) 

### If your project was created as part of an event or hackathon: 

(N/A)
### What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)

(N/A)

### Please link to your hackathon submission
  (N/A)

**Comment by jenks-guo-filecoin** [comment]
Hi @Doinglifewell we are assessing this grant application. There are some questions we need to ask before making a decision: 

1. How does FVM fit in to your application's architecture. The FVM is compute over Filecoin's machine state it is not ideal for running a backend such as an application server. Could you refer to https://rfs.fvm.dev/ to see if any of the use cases could fits Destore? 

2. For running compute heavy programs, we recommend using Bacalhau project. https://www.bacalhau.org/. But for now it will require you to run your own node for compute. Could this fit into your plan for decentralising the backend for Destore? 


3. Unrelated to the grant, do you have an adoption plan such as how many retail stores you plan to onboard in 2023? Any projection will help but you are not obliged to answer as it is only an microgrant. 
4.

**Comment by Doinglifewell** [comment]
### Answer to question 1.

DeStore Network is in the early stages of research and we can not provide a detailed plan on the utility of the FVM use and our Product market fit has stabilized. 

That being said as we are blockchain agnostic and will be onboarding businesses and equipping them with the ability to mint multi-resource products Digital Twins as NFTs.



![Group 20](https://user-images.githubusercontent.com/72717548/234732663-d4e99bb9-4281-4317-a75f-5d238e88b8b4.png)





### We believe that our utility for FVM could fit into the following categories: 



**Perpetual Storage**


https://rfs.fvm.dev/#48bcf3798b694da1a2baf0db85335936

DeStore multi-resource NFTs will store a lot of files for a lot of Small Businesses it makes perfect sense for us to continuously renew deals 


**Games**


https://rfs.fvm.dev/#48c58e5d861f4fe6b03e63beaf2cdbb3

DeStore is providing Brands tooling to produce web3 wearable a new breed of an asset class that in web3 native gives multi-dimensional product utility

**XR wearables** 

DeStore is building paths for businesses to expand their brand into web3. DeStore is providing brands with the tool to create and distribute XR wearables; XR wearables are multi-dimensional products that allow the user to use a product in real life, in Augmented Reality, and virtual reality.   

These XR wearables can also be used as in-game assets. 


https://user-images.githubusercontent.com/72717548/234733813-42b548be-230b-425e-858d-d438bcd15fa8.mp4


https://user-images.githubusercontent.com/72717548/234740887-b6facb48-afcb-47a7-b311-7eca5d479c83.mp4

**Comment by Doinglifewell** [comment]
### Answer to question 2.

DeStore will commit to running a node throughout its Filecoin RnD phase. Providing that the Bacalhau is able to meet the requirements of DeStore Networks decentralized backend Destore will continue to run nodes. 

![Group 1](https://user-images.githubusercontent.com/72717548/234741894-36897498-2ceb-4517-910b-fa299d2ba633.png)

**Comment by Doinglifewell** [comment]
### Answer to question 3.

Currently, we plan to deploy on 4 Parachains in 6 months and onboard 15 Brands to test our platform for each of the Parachains brands through the release of Phygital Products. DeStores' primary focus will be on the Parchains of Polkadot then the existing NFT DAOs within those chains following that we will start onboarding SMEs in geographical regions that we can offer local support to. For the initial platform refinement we will slowly onboard 1000 businesses until we get to a critical mass and are happy with our product review system and 


[Kusama.network](https://kusama.network/)
[Astar.network](https://astar.network/)
[Bit.country ](https://bit.country/)
[phala.network](https://www.phala.network/)


DeStore is currently a participant in the[ Astar / Sony Incubator](https://astar.network/incubation/) and will be showcasing a real live demo to [Sony ](https://www.sonynetwork.co.jp/corporation/sustainability/)during [Japan Blockchain week](https://japanblockchainweek.jp/). We expect to partner with Japanese businesses and partner with a local warehouse in Japan,

**Comment by ErinOCon** [comment]
Hi @Doinglifewell, thank you for your proposal and for your time with our questions. We will not be proceeding with a grant at this time, but are wishing you all the best as you continue to build. 

Thank you again for your interest in our grants program!
