### ISSUE TITLE
Next Step Microgrant: <SXX Future - Filfi>

### ISSUE THREAD

**Issue by SXXFuture-Xindy** [filecoin-project/devgrants#1359]
### 1. What is your project, and what problem does it solve? (max 100 words)
 Building Filecoin nodes requires a lot of pledged coins, which has become one of the bottlenecks in the growth of Filecoin network. The built node itself has great value, including pledged currency and future income, which is an ideal collateral. FilFi protocol expects to release the liquidity of the node by mortgaging the digital assets of the node, which lowers the capital threshold for (small and medium-sized) storage providers to enter the market and increases the driving force for the development of Filecoin network. 
The goal of the Filfi project is to create an unlicensed liquidity market for the Filecoin community. All investors holding FIL can contribute liquidity, and all builders with nodes can gain the motivation to continue development by mortgaging node assets, helping small and medium-sized storage to enter the network, and promoting the expansion of Filecoin network and decentralization of power. 

### 2. Project links
  
Link to Github repo: https://github.com/filfi
Link to demo or website, if applicable: ( FVM Hackathon requires that the github code can not be submitted before January 20th, and the prototype of Figma product can be provided temporarily. ) https://www.figma.com/file/rNZyMvwJlAiEX00s14ggdd/FilFi-V1.0?node-id=0%3A1 
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
< Filfi is an open source liquidity agreement. With the help of FEVM, OpenZeppelin related contracts and upgrade components,a callable solution library of built-in miners and market API supported by Zondax, this protocol mainly implements lending services, and the design of fund pool is inspired by Compound liquidity protocol.
- The agreement mainly includes the following smart contracts: 
  - FilfiPool.sol: Implement core lending functionality, keep contract addresses fixed and independent of future market upgrades, using OpenZeppelin TransspaentUpgradeableProxy contract 
  - Confugurator: This is the proxy contract, which is used to set and update FilfiPool contract parameters and save gas.
  - MinerAPI: Miner-related, calling built-in contracts 
  - MakketAPI: Market-related, calling built-in contracts 
  - Proxy Admin: Administrator of the proxy contract, recommended by OpenZeppelin for upgradeability 
  - Rewards: Reward contract, allowing users to receive Rewards >
###    b) Is this project building with FVM? (Yes or No) 
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- In February 2023, the v1.0 version will be implemented, and the beta version will be released for small-scale testing. Grants will be used to expand team members and test.

- In March 2023, the smart contract needs to be audited, and the grant will pay for the audit cost.
- In April 2023, version v1.0 will be officially launched, open to the public, and the source code was 100% open source. Grants will be used for operating costs such as servers and bandwidth.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
- Agree
  
### 6. Does your proposal comply with our Community Code of Conduct?
- Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* - We are about to take part in [FVM SPACE WARP HACKATHON Jan 20 - Feb 10, 2023](https://ethglobal.com/events/spacewarp).
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
- Chenyang  
Emal janckerchen@gmail.com  
Github  janckerchen@gmail.com  
Role Product Manager
- Chaojie Xie
      Email gladysvelzeboertow90@gmail.com
      Github https://github.com/glady90
      Role Designer
- Lingtong Li
  Email sxx.leo@gmail.com
  Github https://github.com/leotons
  Role Developer
- Chenjian Chan
  Email geektheripper@gmail.com
  Github https://github.com/geektheripper
  Role Developer
* How did you learn about our microgrant program?
- It was introduced by FVM team.
* If your project was created as part of an event or hackathon: 
- Yes
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) 
- ETHGlobal
  * Please link to your hackathon submission
  [FVM SPACE WARP HACKATHON Jan 20 - Feb 10, 2023](https://ethglobal.com/events/spacewarp)

**Comment by ErinOCon** [comment]
Hi @SXXFuture-Xindy, thank you for your proposal! We are sorry to let you know your project was not selected for a FVM microgrant at this time. Please note we are planning to release another round of grant funding in a few weeks. You are welcome to re-apply with the above or a future FVM project once the new grant funding round has been announced. Until the new founding round opens, no applications will be reviewed or accepted.

If you have already started building your project, we would like to encourage you to join the community of builders on Filecoin Slack and to consider submitting your project to the FVM Community Leaderboard, where the community votes bi-weekly on the top projects to win prizes from a $75k prize pool. Learn more [here](https://network-goods.notion.site/Impact-Evaluators-Builders-Leaderboard-602ea6755b5642e1ad6f9da59a47fa62).
