### ISSUE TITLE
Next Step Microgrant: <Fil-Minerverse: a platform of storage mining power tokenization based on FEVM>

### ISSUE THREAD

**Issue by kelly0x** [filecoin-project/devgrants#1360]
### 1. What is your project, and what problem does it solve? (max 100 words)

Fil-Minerverse is an easy-to-use filecoin storage mining platform where mining activists could join Filecoin storage mining to earn $FIL. With a strong technical know-how in the development and operations of Filecoin storage mining, the core team of Hedra Labs is to develop a product that allows users to participate in the mining business to earn $FIL by obtaining and staking a certain amount of storage power shares. We call it "stake-to-earn".

The liquidity problem of Filecoin can be largely resolved via Fil-Minerverse.

### 2. Project links
  
Link to Github repo: https://github.com/HedraTech
Link to demo or website, if applicable: N/A
License:

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

Fil-Minerverse is a dApp based on FEVM. It will deploy these FEVM actors to improve platform security and reliability assurances:
- deploying FEVM actors to interact with FVM built-in actors and settle miner rewards to stakeholder and hardware provider. 
- tokenizing storage power so that end users can buy storage power tokens and get rewards.
- creating a DAO to manage the platform.

###    b) Is this project building with FVM? (Yes or No)
  Yes
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Phase 1
Implementing a smart contract based on FVM that allows miners to share out their storage power with end users and make deals with clients to store files onto Filecoin via the Fil-Minerverse platform. The mining rewards of the storage power will be distributed to the stakeholders accordingly via smart contracts.
Implementing storage-power-bearing tokens, a type of ERC-20 tokens that will be distributed mining yields simply by holding and staking them in Fil-Minerverse mining pools for end users. It’s a kind of liquid and marketable asset.
Providing liquidity for the storage-power-bearing ERC-20 tokens and FIL via liquidity pools.
Upgrading the website and mobile app

Phase 2
Upgrading the platform to a Miner DAO and getting multiple roles engaged in the DAO, which includes Project Team, FIL Providers, Storage Providers, DataCap Providers, Storage Clients. All the DAO members could participate in DAO governance through a type of DAO tokens, such as Miners reputation supervision and management, DAO Treasury management, Punishment mechanism for miners, Metrics devising like staking or mining rewards distribution proportions, DAO yield management, etc.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

 Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 N/A
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Matt, Full-Stack developer, [matt@hedralabs.org](mailto:matt@hedralabs.org), https://github.com/mattkb  
Mark, Full-Stack developer, [mark@hedralabs.org](mailto:mark@hedralabs.org), https://github.com/vricale

* How did you learn about our microgrant program?
Got to know about the program from Filecoin slack channel.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
N/A

**Comment by ErinOCon** [comment]
HI @kelly0x, thank you for your proposal! We are sorry to let you know your project was not selected for a FVM microgrant at this time. Please note we are planning to release another round of grant funding in a few weeks. You are welcome to re-apply with the above or a future FVM project once the new grant funding round has been announced. Until the new founding round opens, no applications will be reviewed or accepted.

If you have already started building your project, we would like to encourage you to join the community of builders on Filecoin Slack and to consider submitting your project to the FVM Community Leaderboard, where the community votes bi-weekly on the top projects to win prizes from a $75k prize pool. Learn more [here](https://network-goods.notion.site/Impact-Evaluators-Builders-Leaderboard-602ea6755b5642e1ad6f9da59a47fa62).
