### ISSUE TITLE
Next Step Microgrant: DAYOU Cloud Drive

### ISSUE THREAD

**Issue by dayou-dev** [filecoin-project/devgrants#1361]
![github申请](https://user-images.githubusercontent.com/119026685/213187845-501401e1-f659-430f-b2f4-51e37545d50e.png)

### 1. What is your project, and what problem does it solve? (max 100 words)
DAYOU Cloud Drive is a private cloud drive based on distributed storage technology as the underlying storage, designed to allow more Web2 users to quickly experience Web3 technology.

### 2. Project links
Link to Github repo: [DAYOU Cloud Drive Github](https://github.com/dayou-dev/netdisk)
Link to demo or website, if applicable: [DAYOU Cloud Drive](http://www.dayoudrive.com)
License: **MIT & Apache**

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

- It calls the IPFS interface to store user file data.
- Uploads file over a decentralized network just like Infura.

###    b) Is this project building with FVM? (Yes or No)
  No

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- Add online preview function;
- Add NFT wallet function;
- Optimize UX design;
- Publish the mobile terminal.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

 Yes, We agree to share grant reports upon request.

### 6. Does your proposal comply with our Community Code of Conduct?

Of course, we have read the code of conduct.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
We will participate in [「FVM SPACE WARP HACKATHON 2023」](https://ethglobal.com/events/spacewarp).
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

| Name | Mail | Github | Role |
| -------- | -------- | -------- | -------- |
| Liang | liangzhiyou45@gmail.com | @dayou-dev | Dev |

* How did you learn about our microgrant program?
Referred by Developer Advocate @ Filecoin - Jenks Guo (jenks@fil.org)

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
[FVM SPACE WARP](https://spacewarp.fvm.dev/).

  * Please link to your hackathon submission
[「FVM SPACE WARP HACKATHON 2023」](https://ethglobal.com/events/spacewarp)

**Comment by ErinOCon** [comment]
Hi @dayou-dev, thank you for your proposal. We will not be moving forward with a grant at this time. Wishing you the best as you continue to build!
