### ISSUE TITLE
Next Step Microgrant: Defi Ecosytem on Filecoin EVM

### ISSUE THREAD

**Issue by inventionsbyhamid** [filecoin-project/devgrants#1362]
### 1. What is your project, and what problem does it solve? (max 100 words)

We are building an entire suite of Defi products on the upcoming Filecoin EVM. We are currently working on the following products: 
1. DEX - A decentralized exchange to enable users to add liquidity among different token pairs and swap. We are testing initial version on wallaby network - https://floppy.trade
2. Bridge connecting ETH and FIL network - will facilitate interoperatibility with ETH and will help in onboarding new users into the Filecoin network.
3.  Storage derivatives market using OpynV2 - Users can lock in storage prices by pre-buying from providers, while providers can secure demand by bidding on future storage delivery.
4. Lending and borrowing - storage providers can borrow FIL to use as collateral to seal more sectors and lenders can profit from the storage deals.

### 2. Project links
  
Link to Github repo: private/under development
Link to demo or website, if applicable: https://floppy.network (currently redirects to dex - https://floppy.trade)
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

With the Filecoin FVM in launching in Feb, we are building products keeping in consideration all the participants in the Filecoin ecosystem as we are a strong believer in the Filecoin community.
With storage derivatives market storage providers on Filecoin can offer options for pre-buying storage space at a fixed price, allowing data producers to predict costs. On the other hand, providers can bid on future storage delivery to secure demand and manage inventory efficiently.

###    b) Is this project building with FVM? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

With this micro-grant we are targeting to take our first product (DEX) live. We'll able to add on the compute and hosting resources required. We have the required engineering bandwidth to make the project live and this grant will help us in other non engineering tasks that we have identified. 
1. Security audit 
2. Beta testing the product
with these tasks closed we'll be able to smoothly make the project live for end users.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes we'll be transparent on where the grant resources are being used for the project and can share reports as well.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Team:
1. Hamid Siddiqui, hamid@floppy.network, @inventionsbyhamid, Full Stack Engineer
2. Manish Bisht, manish@floppy.network, @manish05, Full Stack Engineer
4. Gokul Saravanan, gokul@floppy.network, @xogz3, Business and Product Design
5. Raunak Seth, raunak@floppy.network, @botraunak, Full Stack Engineer
* How did you learn about our microgrant program?
We learned from a friend

**Comment by ErinOCon** [comment]
Hi @inventionsbyhamid, thank you for your proposal! We are sorry to let you know your project was not selected for a FVM microgrant at this time. Please note we are planning to release another round of grant funding in a few weeks. You are welcome to re-apply with the above or a future FVM project once the new grant funding round has been announced. Until the new founding round opens, no applications will be reviewed or accepted.

If you have already started building your project, we would like to encourage you to join the community of builders on Filecoin Slack and to consider submitting your project to the FVM Community Leaderboard, where the community votes bi-weekly on the top projects to win prizes from a $75k prize pool. Learn more [here](https://network-goods.notion.site/Impact-Evaluators-Builders-Leaderboard-602ea6755b5642e1ad6f9da59a47fa62).
