### ISSUE TITLE
Next Step Microgrant: CollectifDAO (ex. Filstake)

### ISSUE THREAD

**Issue by kmadorin** [filecoin-project/devgrants#1363]
### 1. What is your project, and what problem does it solve? (max 100 words)
Collective DAO is a non-custodial liquid staking protocol that lets users stake their FIL and receive clFIL in exchange, enabling them to participate in the Filecoin network. Staked FIL is distributed among storage providers who use the capital to expand their mining operations.

### 2. Project links
  
Link to Github repo: https://github.com/collective-dao/
Link to demo or website, if applicable:
   Website: [https://collectif.finance/](https://collectif.finance/)
   Demo app: [http://app.collectif.finance/](http://app.collectif.finance/)
License: GPL
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
We use FEVM to build a liquid staking pool and provide its FIL liquidity to Storage Providers

###    b) Is this project building with FVM? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1) Finish liquid staking pool for direct FIL transfer into Storage Provider's initial pledge

2) Finish an SDK for Storage Providers to allow them to borrow from the staking pool

3) Add Staking Router to allow integrations with other staking pools and sources of liquidity for miners. (Glif pools, for example)

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes, here is the link to our submission: [https://ethglobal.com/showcase/collectifdao-zdk29](https://ethglobal.com/showcase/collectifdao-zdk29)

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* 
Bah Adylbekov, bach@collectif.finance, [https://github.com/bahadylbekov](https://github.com/bahadylbekov) -  Developer

Kirill Madorin, kirill@collectif.finance, [https://github.com/kmadorin/](https://github.com/kmadorin/) - Developer

Artem Bryzgalov, [artem@collectif.finance](mailto:abrizgalov@gmail.com), [https://github.com/artbreez](https://github.com/artbreez) - Designer

* How did you learn about our microgrant program?
Referred by Filecoin Developer Advocate - Sarah Thiam

* If your project was created as part of an event or hackathon:
  * What was the name of the event?
    Ethglobal Space Warp 
  
  * Please link to your hackathon submission
  [https://ethglobal.com/showcase/collectifdao-zdk29](https://ethglobal.com/showcase/collectifdao-zdk29)

**Comment by ErinOCon** [comment]
Hi @kmadorin, thank you for all of your patience with our grant review process. Unfortunately, we will not be proceeding with a grant a this time. Wishing you all the best as you continue to build!
