### ISSUE TITLE
Next Step Microgrant: SoulSystem Protocol

### ISSUE THREAD

**Issue by toledoroy** [filecoin-project/devgrants#1364]
### 1. What is your project, and what problem does it solve? (max 100 words)

The SoulSystem protocol is a set of interconnected composable primitives based around a soulbound contract. 
With the power of generalized semantic architecture, the SoulSystem is ready to serve as a fully decentralized framework for all kinds of socio-economic dApps. Allowing web3 to become more accessible to non-developers and serve as a foundation for network states.

### 2. Project links
  
[Link to Github repo](https://github.com/SoulSystemProtocol/SoulSystem-Protocol)
[Link to demo or website](https://solidify.space/)
License: MIT

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

We use IPFS for all off-chain data. From token images and metadata to custom content such as posts, submissions, file uploads, and any additional custom data. 

###    b) Is this project building with FVM? (Yes or No)
  
At this stage, we’re running on the Mumbai testnet. We’re making extensive use of The Graph so hopefully in the future when FVM is supported and we’re ready to go live. 

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- Engage with more customers for additional feedback to better serve the market
- Implement reputation and token transfers on frontend 
- Integrate our ERC1155 with DAO governance 
- Humanly readable permission management – use semantic triples to manage function execution.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
An earlier version was submitted to Moralis + Avalanche 2022 and won, but we were too late to claim the prize. I don't have a link, but the project was called NFT Bonfire.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

 Name: Roy Toledo 
 Email: toledoroy@gmail.com
 GitHub: https://github.com/toledoroy/
 Role: Founder & CTO

* How did you learn about our microgrant program?

I’m familiar with Protocol Labs mostly from hackathons.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

A precursor of this project have won some prizes on [ETHGlobal](https://ethglobal.com/showcase/mentordao-u1cj7)

**Comment by ErinOCon** [comment]
Hi @toledoroy, thank you for your proposal and for your patience with our unexpectedly long review. Unfortunately, we will not be moving forward with a grant a this time. Wishing you all the best as you continue to build!
