### ISSUE TITLE
Next Step Microgrant: MediChain - Decentralized Telemedicine and Medical Records

### ISSUE THREAD

**Issue by sadityakumar9211** [filecoin-project/devgrants#1365]
### 1. What is your project, and what problem does it solve? (max 100 words)

MediChain: Decentralized Telemedicine and Record System is built with using IPFS for storing medical data of the patients so that they can securely access their data anywhere and anytime. It aims to solve the problems of security, privacy, and efficiency that exist in traditional centralized systems. By using a decentralized, immutable ledger, the platform is able to mitigate risks such as ransomware attacks and counterparty risks. Additionally, the platform is going to include a secure and private communication channel for patients and doctors, and in the future, we plan to incorporate a DAO to further decentralize the system and enable patients to participate in medical administration.

### 2. Project links

Link to Github repo: -  
[Primary Repository](https://github.com/sadityakumar9211/medichain-hardhat)

> This is one (hardhat repository) of the repository of MediChain Project. The links to other repository are below:

- [NextJS](https://github.com/sadityakumar9211/medichain-nextjs)
- [The Graph](https://github.com/sadityakumar9211/medichain-thegraph)

Link to demo or website: https://medichain.vercel.app

> This prototype is deployed on Goerli Testnet. If you're seeing an error: `Application error: a client-side exception has occurred (see the browser console for more information)`, ensure that you switch to `Goerli` testnet and retry whatever you were trying to do. I am working on providing a better error message.

License: [GPL v3](https://github.com/sadityakumar9211/medichain-hardhat/blob/main/COPYING)

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

<img src="https://gateway.pinata.cloud/ipfs/QmRQRJk4TJNAA3448Eqfov24z7rw5j5WLeDsuwto3Ub8Pi?_gl=1*1l8x8pp*_ga*MTM2MzA3MTc2Ni4xNjc0MDczMjM4*_ga_5RMPXG14TE*MTY3NDA3NzMwMi4yLjEuMTY3NDA3NzMzMS4zMS4wLjA."  alt="medichain_design" width="700"/>

The project proposes a hierarical medical administration, with a committee governed by a director overseeing all hospitals in the area. The hospitals are the next in the administration and then the doctors. In future, among other features this project plans to incorporate a DAO to involve patients in the selection of the director.

MediChain is supported by a EVM compatible smart contract developed in `hardhat` runtime environment. Currently, for data storage(medical files of patients), this platform uses the IPFS, and plans to use `Filecoin` (FVM) in future. In future, we also selectively plan to store the video meet transcripts between patients and doctors in decentralized storage.

Currently, the doctor can upload the patient's file. The doctor selects the file to be uploaded. This file gets uploaded to `IPFS` using `ipfs-core` package and the fetched `hash` is used to construct a metadata object. This metadata is again uploaded to `IPFS` and the fetched hash is encrypted (2048 bit RSA encryption)with the public key of the patient and this `encrypted hash` is stored in the blockchain along with patient details.

To increase the scalability of this system, I have also used a decentralized indexer - `The Graph`. This indexes the blockchain and stores the data on a subgraph. We query this subgraph for fetching any details for the application instead of the blockchain directly and hence increasing the scalability.

When the patient wants to view the file, he has to enter the `private key` to `decrypt` the metadata hash hence ensuring that only he is able to view his sensitive medical files.

> For more details about the detailed architecture of the system, contact me at `sadityakumar9211@gmail.com`

### b) Is this project building with FVM? (Yes or No)

No.
However, future versions will be built on top of FVM.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

With this grant, I plan to take several steps to improve the project. Firstly, I will have the financial security to fully commit to the project and hire other developers as needed. This will allow me to add new features such as decentralized communication channels between patients and doctors, including text messaging using XMTP and video conferencing using Huddle01. This will greatly improve the patient-doctor experience, and provide more efficient and convenient means of communication. Additionally, I plan to integrate a DAO into the platform to democratize the selection of the director of the governing committee. This will give patients a greater level of control and participation in the administration of the platform. Furthermore, I will implement user experience improvements such as adding ENS search for patients, doctors, and hospitals. This will make it easier for users to find and connect with the relevant parties, and improve the overall usability of the platform. Overall, the grant will allow me to make significant improvements to the project and bring it closer to achieving its goals of a decentralized state-of-the-art Telemedicine and Record System.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, I agree.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes, it does.

### 7. Links and submissions

If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

- This is an independent personal project.

### Additional questions:

- For each team member(s), please list name, email, Github account, and role in the project.
  1. Aditya Kumar Singh
  - sadityakumar9211@gmail.com
  - https://github.com/sadityakumar9211
  - Creator and sole developer. Responsible for conception, design, development, and deployment of the project. 
- How did you learn about our microgrant program?
  > I received a mail from hackathons@protocol.ai about various hackathons. This microgrants program was one of them.

**Comment by ErinOCon** [comment]
Hi @sadityakumar9211, thank you for your proposal. We will not be moving forward with a grant at this time. Wishing you the best as you continue to build!
