### ISSUE TITLE
Next Step Microgrant: Loarr - Decentralized Learning Platform

### ISSUE THREAD

**Issue by bharath5262** [filecoin-project/devgrants#1368]
### 1. What is your project, and what problem does it solve? (max 100 words)
Loarr is the world’s first decentralized learning platform on the blockchain. Enabling to self-learn and upskill, with the proof of learning and work stored on the blockchain powered with learn to earn mechanism.

Making Internet Learning Valued & Valid by the proof of learning on the blockchain powered by AI-based decentralized computation.

Moving from a paper based to skill based economy by proof of work stored on the blockchain.

Loarr is making it easy to self learn & upskill yourself, enabling skill based jobs with the first of its kind open skill set profile on the Internet 

### 2. Project links
  
Link to Github repo: https://github.com/project-loarr/FIL 
Link to demo or website, if applicable: website & Apps in stealth mode (will update shortly) 
Loarr Deck - http://bit.ly/3ZNRCGX

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
We make sure content is owned by the users.
Text based data (json) is stored on Filecoin
NFTs stored on IPFS

###    b) Is this project building with FVM? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We would want to achieve an important milestone in our project!

Launch of the product “threads”
Post a question 
Ans a question
Google Index
Users are rewarded with tokens for the contribution 
Text based data (json) is stored on Filecoin
NFTs stored on IPFS
Royalties & Rewards for the contributors 
Platform fee
Recommended threads
 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, definitely!

  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* We haven't started at the hackathon 
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
* Eth India

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @bharath5262, thank you for your proposal! We are sorry to let you know your project was not selected for a FVM microgrant at this time. Please note we are planning to release another round of grant funding in a few weeks. You are welcome to re-apply with the above or a future FVM project once the new grant funding round has been announced. Until the new founding round opens, no applications will be reviewed or accepted.

If you have already started building your project, we would like to encourage you to join the community of builders on Filecoin Slack and to consider submitting your project to the FVM Community Leaderboard, where the community votes bi-weekly on the top projects to win prizes from a $75k prize pool. Learn more [here](https://network-goods.notion.site/Impact-Evaluators-Builders-Leaderboard-602ea6755b5642e1ad6f9da59a47fa62).
