### ISSUE TITLE
Next Step Microgrant: Odyssey 

### ISSUE THREAD

**Issue by Ayushjain2205** [filecoin-project/devgrants#1371]
### 1. What is your project, and what problem does it solve? (max 100 words)

Odyssey is an **NFT hunt/game**- An exciting and surprising game to capture the rarest NFTs of their favorite brands dropped at different locations around them. Go out in the physical world to find NFTs in the virtual world.

**Augmented Experience** - A stimulating AR experience that introduces new environments, and visuals on a daily basis. You see a new world through your camera. Capture the best of the best to utilize.

**Real value to users** - Humans get hooked onto things they like. If they provide them with value. Odyssey creates a continuous stream of value that is verifiable.
For eg, I have an NFT of my favorite clothing brand Zara and if I keep staying loyal to them (by going on a search to find their NFTs) I can get access to Zara shows in the Metaverse or exclusive collections that can be redeemed right on our app through a link attached as the utility of the NFT.

Exclusivity - Humans like things others don't have, that's human behavior. By having access to a Tesla Car launch event because you own the NFT through the hunt, we create excitement.

For businesses,

**Entry into the Metaverse Odyssey** - Web2 brands can get an opportunity to enter into the Metaverse. This ecosystem can allow them to experiment with the Metaverse. Create exclusive gated hunts for their loyal customers with customized worlds and assets that match their brand language.

**Create dynamic NFTs** - By dynamic we mean, NFTs that have various layers and move in various directions in terms of the utility attached to them. NFTs can have an omnichannel presence, and be integrated into socials. Brands can create collections that are recurring, that add value to the user at different stages. For eg, If I have found a certain NFT of a brand, only then I am eligible for the exclusive NFTS drops of that brand. Through token gating, the perceived value of the brand will increase which in turn increases user sentiment.

**Focused marketing through geotagging** - Brands can drop their NFTs at locations where they would be relatively unpopular to increase their user base. The better the utility, the more engagement from users too.

**An interactive distribution channel** - Marketing campaigns don’t need to be 2d, the degree of interaction could be much more if brands start creating fun, exclusive 3-dimensional hunts all around the world. ( A secret - Brands can literally post interactive campaigns in AR)

### 2. Project links
  
Link to GitHub repo: https://github.com/entropyylabs/odyssey
Link to demo or website, if applicable:

1. Ecosystem website -  https://sites.google.com/view/entropylabs-pitch/home
2. Link to product demo video - https://youtu.be/Tq0jaRTc2NU
3. Pilot hunt link (Roar is our pilot hunt) - https://roar-nft.netlify.app/

License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
We store NFT metadata on NFT.storage. We have a lot of 3d assets for our AR hunts which we store on IPFS. 
###    b) Is this project building with FVM? (Yes or No).
Currently we use the Mumbai testnet but want to migrate our contracts to the FEVM in our next iteration.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We want to improve our geolocation experience.
We want to add a social aspect to the hunts -  Multiplayer modes etc.
We want to improve the user experience and make onboarding very seamless.
We are running a couple of pilots and that's what we need the grant for.

We need to get the following:
- Unity Pro license
- Apple dev program
- Figma plugins
- Give away for pilot hunt
- Hire a couple of interns

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
[Web3 Infinity Hackathon](https://web3infinityhackathon.devpost.com/) - Winners 
We got a chance to conduct a side event at FIL-Singapore as winners of this hackathon. 
[Link to our event ](https://filsingapore22.sched.com/event/1Aow2/entropy-labs-discover-an-ecosystem-of-utility-nfts-with-entropy-labs)

Our previous iteration (GeoNFT) was the winner at ETHGlobal buildquest and chainlink 
[Buildquest](https://showcase.ethglobal.com/buildquest/geonft-qtsnj) - Finalist and 5 other category winners
[Chainlink Spring Hackathon](https://devpost.com/software/geonft) - Filecoin storage wizard winners

  
### Additional questions:

* For each team member(s), please list name, email, Github account, and role in the project.

Ayush Jain
ayushjain2205@gmail.com
https://github.com/Ayushjain2205/
Developer

Ishika Pareek
ishikapareek@gmail.com
https://github.com/ishikapareek
Product designer

* How did you learn about our microgrant program?

Referred by Filecoin teams at FIL-Singapore and FIL-Bangalore during ETHIndia

* If your project was created as part of an event or hackathon:

[Web3 Infinity Hackathon](https://web3infinityhackathon.devpost.com/) - Winners 
We got a chance to conduct a side event at FIL-Singapore as winners of this hackathon. 
[Link to our event ](https://filsingapore22.sched.com/event/1Aow2/entropy-labs-discover-an-ecosystem-of-utility-nfts-with-entropy-labs)

Our previous iteration (GeoNFT) was the winner at ETHGlobal buildquest and chainlink 
[Buildquest](https://showcase.ethglobal.com/buildquest/geonft-qtsnj) - Finalist and 5 other category winners
[Chainlink Spring Hackathon](https://devpost.com/software/geonft) - Filecoin storage wizard winners

**Comment by ErinOCon** [comment]
HI @Ayushjain2205, thank you for your proposal. The [provided repo link](https://github.com/entropyylabs/odyssey) is not working. Is it open to the public?

**Comment by Ayushjain2205** [comment]
Hey @ErinOCon , This was a private repository but I have made it public now for you to see.

**Comment by ErinOCon** [comment]
Hi @Ayushjain2205, thank you again for your proposal! We will not be moving forward with a grant at this time, but please feel welcome to check-in for upcoming support opportunities as you continue to build!

You can review our latest focus areas [here](https://github.com/filecoin-project/devgrants/blob/master/microgrants/microgrants.md#focus-areas)!
