### ISSUE TITLE
Next Step Microgrant: CredLancer: Secure, verifiable credentials platform

### ISSUE THREAD

**Issue by captainahab0x** [filecoin-project/devgrants#1372]
### 1. What is your project, and what problem does it solve? (max 100 words)
CredLancer aims to deliver tamper-proof credentials, showcase professional development and achievement, while maintaining data privacy and sovereignty. We aim to address three major problems:
1. The lack of trust and verifiability in professional credentials
2. Difficulty in demonstrating professional development and achievements 
3. Lack of interoperability and portability of professional data

CredLancer enables organizations to issue tamper-proof credentials to employees and other members, and allows professionals to showcase these on-chain credentials along with their professional development certifications. With the integration of Zero-Knowledge Proofs, CredLancer ensures that personal data remains private while still allowing for verifiable validation of professional qualifications.

### 2. Project links
  
Link to Github repo:
https://github.com/captainahab0x/CredLancer_Nov22/edit/main/README.md

Link to demo or website, if applicable:
Pitch Video: https://www.loom.com/share/45c880278d0041c7889c6f3d65a3eabd
Demo: https://www.loom.com/share/47564c02330340038544ebb5f75b73b4

License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
Tech Used: FEVM, Solidity, next.js, react.js hardhat-kit, Web3.Storage
Also considering Lighthouse

Examples of data that could be stored on IPFS and interact with FVM include:
1. User Profile Data: Information such as name, contact information, professional qualifications, and other details about users' professional background could be stored on IPFS. This data would be hashed and encrypted before being stored on IPFS to ensure privacy and security. Here we plan to dive into Lighthouse incorporate their solutions.

2. Credentials: Self-attested digital credentials such as degrees, certificates, and badges issued to users could be stored on IPFS. Organization issued Soul Bound Token Credentials (ERC1155) can also be stored.

3. Professional Development Data: Information about professional development activities, such as training courses, workshops, and conferences that users have participated in could be stored on IPFS.

4. Reputation and skills scoring: We can create a system that incorporated smart contracts deployed on FVM to read data stored on IPFS and create a tamper-proof record of users’ professional achievements, allowing them to demonstrate their skills and reputation on-chain. As these are connected to a specific CID, they are portable for other uses.  

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Our objectives are to complete a product demo with the following features:

Organization Flow:
-Creating a multiple wallet connection and issue credentials to Lancers
-Resolve issues related to Web3.Storage minter connection and explore Lighthouse for added encryption features
-Create APIs to connect org profile to Discord, Twitter, Linkedin for greater verification

Lancer Flow:
-Create Lancer sign-in option with same tools as org login but without credential issuing access
-Create API to connect Discord and Twitter for greater verification
-Create API to other SoulBoundNFT Badges like MintKudos, POAP and create path to showcase and store on IPFS with similar flow as Org

 
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

ETHGlobal FVM Hackathon Finalist Winner: https://ethglobal.com/showcase/credlancer-credentialed-freelancer-protocol-znzpf
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

ChristyAna Viva, Scrum Master, Design Architect
christyana@protonmail.com
https://github.com/captainahab0x

Julio M. Cruz, Full Stack Developer
https://github.com/JulioMCruz
julio.cruz@eb-ms.net 

Adedamola, Full Stack Developer, Blockchain Developer
https://github.com/AdedamolaXL
adedamolaxl@outlook.com

* How did you learn about our microgrant program? 
We received an email after EthGlobal FVM Hackathon.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
ETHGlobal FVM Hackathon Finalist Winner: https://ethglobal.com/showcase/credlancer-credentialed-freelancer-protocol-znzpf

**Comment by ErinOCon** [comment]
HI @captainahab0x, thank you for your proposal! We are sorry to let you know your project was not selected for a FVM microgrant at this time. Please note we are planning to release another round of grant funding in a few weeks. You are welcome to re-apply with the above or a future FVM project once the new grant funding round has been announced. Until the new founding round opens, no applications will be reviewed or accepted.

If you have already started building your project, we would like to encourage you to join the community of builders on Filecoin Slack and to consider submitting your project to the FVM Community Leaderboard, where the community votes bi-weekly on the top projects to win prizes from a $75k prize pool. Learn more [here](https://network-goods.notion.site/Impact-Evaluators-Builders-Leaderboard-602ea6755b5642e1ad6f9da59a47fa62).

**Comment by captainahab0x** [comment]
@ErinOCon 
Hello! We are checking back in. Is there another path to grants available?
