### ISSUE TITLE
Next Step Microgrant: Kontract

### ISSUE THREAD

**Issue by NatoSilue** [filecoin-project/devgrants#1373]
### 1. What is your project, and what problem does it solve? (max 100 words)

Kontract is a decentralized marketplace for storage deals, where clients can go and see storage providers, their capacity, reputation and storing price and pick who they want to store with. Kontract will also allow filecoin storage users to sign data deals contracts on the blockchain. These contracts can be sign for current and future deals. 

### 2. Project links
  
Link to Github repo: https://github.com/CanzaApps/Experimental
Link to demo or website, if applicable: N/A
License: MIT 

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

All contracts and data from the websites will be stored on IPFS and Filecoin
The smart contracts will be deployed on FEVM

###    b) Is this project building with FVM? (Yes or No)
Yes, we are planning to deploy our smart contracts on FEVM.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Our plan is to start building this project on FVM. 
-We will first deploy our smart contract on FEVM.
-We will build the frontend
-Have an intern or two interns with Filecoin integration skills

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes 

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
   
No, 

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Nato Silue, Front End Developer
n.silue@canza.io
https://github.com/NatoSilue

Victor Teixeira, Senior Crypto Economist
v.teixeira@canza.io 
https://github.com/0xVonBismarck

Deon Achuo, Full Stack & Blockchain Developer
d.achuo@canza.io
https://github.com/Sir-Deon

* How did you learn about our microgrant program?
 Twitter

* If your project was created as part of an event or hackathon:  
No
 
  * Please link to your hackathon submission 
  N/A

**Comment by ErinOCon** [comment]
HI @NatoSilue, thank you for your proposal! We are sorry to let you know your project was not selected for a FVM microgrant at this time. Please note we are planning to release another round of grant funding in a few weeks. You are welcome to re-apply with the above or a future FVM project once the new grant funding round has been announced. Until the new founding round opens, no applications will be reviewed or accepted.

If you have already started building your project, we would like to encourage you to join the community of builders on Filecoin Slack and to consider submitting your project to the FVM Community Leaderboard, where the community votes bi-weekly on the top projects to win prizes from a $75k prize pool. Learn more [here](https://network-goods.notion.site/Impact-Evaluators-Builders-Leaderboard-602ea6755b5642e1ad6f9da59a47fa62).
