### ISSUE TITLE
Arivu's EasyWriter - 

### ISSUE THREAD

**Issue by rmattnelson** [filecoin-project/devgrants#1375]
**Proposal Category:** `app-dev` 

**Proposer:** `rmattnelson` 

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here` 

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:**  "Yes"  

# Project Description 
Companies, Financial Institutions, and public bodies around the world face unprecedented demand from customers, investors, and regulators to disclose increasingly granular data on their net zero transition and broader sustainability commitments.  Proving there is no greenwashing is a major obstacle to trust in this reported information. 

The immutability of public blockchains and large file storage blockchains can play a vital role in fossilising data to build trust in these reported facts.  But key hurdles keep corporates from utilising public blockchains even for publicly disclosed reporting: 

Layer1 blockchains have small data payloads restricting corporate use cases 

Lack of technical support restricts the ability of traditional enterprise IT functions to access and best utilise public blockchains.

Arivu has developed a solution to help companies use public blockchains without the need to own wallets and interact with tokens. 

EasyWriter as a SaaS tool that allows corporates to write large data sets to any public blockchain or large file storage solution without deep technical knowledge of web 3.0.  

When integrated with a Layer1 public blockchain, Arivu's EasyWriter offers corporate users the ability to immutably store complex data sets and files on Filecoin and to access content and attributes for reporting and for rapid audit and attestation. 

This project proposal is to integrate EasyWriter with Filecoin. 

Arivu is also creating powerful encryption/decryption capabilities to allow secure transfer and storage of sensitive information via public blockchains.  

With this key inhibitor removed, we anticipate a significant surge in data volumes written to Filecoin. 

## Value 
The benefits of getting this right include: 

1) reducing greenwashing risk in corporate sustainability reporting 
2) improving trust in the provenance of any data exchanged between companies for compliance and reporting 
3) hundreds of new off-chain to on-chain 'large data-set' use cases for public blockchains for Filecoin corporate customers globally 
4) significant growth in corporate usage of Filecoin 

Risks of not getting this right are limited: 
1) project code is not used for (our) intended purpose...but can be used for novel data processing applications by other community members 
2) reputational risk sits with Arivu as developers and not with the host Layer1 blockchain provider 

Project execution risks include: 
1) inadequate support from the Filecoin user community could impact the speed of delivery 

Project execution risk is mitigated by Arivu's access to multiple blockchain dev teams for Filecoin expertise.  Also, our release strategy is based on comprehensive product user acceptance testing before Mainnet release.  Arivu will be testing this using our own corporate customer data to ensure the release of this EasyWriter integration is effective and fit for purpose. 

## Deliverables 
EasyWriter integration to Filecoin will have three milestones: 
1) When EasyWriter can write to Filecoin 
2) When an external user calls and API to write to Filecoin 
3) When an external user utilises an asynchronous API with error handling to write to Filecoin and can also log into an account and switch between any of multiple Layer1 blockchains (e.g. switch from writing to Algorand to Filecoin, etc.) 

Deliverables are the demonstrable integration of EasyWriter to Filecoin to demo the above milestones.   

Given Arivu's current customer data sets, we anticipate between 120GB and 420GB of data per month written to Filecoin within 12 months of integration. 

## Development Roadmap 
Phase 1:  EasyWriter writing transactions to Filecoin 
 - Evaluation of restful API 
 - Get access to a Lotus full-node 
 - Send text and binary payloads 
 - Ensure EasyWriter is working on Filecoin Testnet 

Milestone 1:  When there is proof that EasyWriter can write to Filecoin 
Effort estimate = 2FTE * 20 days = 40 FTE days 
Milestone deadline proposed for end of March 2023 
Phase 1 funding requirement = $12,000 

Phase 2: Expose public API for people to write to Filecoin 
 - Secure using API key in request header 
 - Send text to EasyWriter API endpoint 
 - Format payload into Arivu JSON standard 
 - Return JSON object detailing the address of the transaction, and performance statistics 
 - End users don't have their own wallet and they pay in Fiat currency (EasyWriter is a fiat-based, SaaS subscription) 
 - EasyWriter does not store a user's API key, we store a hash of the API key 

Milestone 2:  When user calls an API to write to Filecoin 
Effort estimate = 2FTE developers + 1FTE tester * 20 days = 60 FTE days 
Milestone deadline proposed for end of April 2023 
Phase 2 funding requirement = $18,000 

Phase 3: User interface and call-back 
 - update chain policy allowing customer to select Filecoin 
 - Asynchronous writing to chain.  Some transactions could take minutes and cause time-outs.  Thus the need for asynchronous requests. 
 - all previous user transactions are viewable online with all EasyWriter transactions indexed in Arivu GDI (graph database indexer) 
 - read API so users can retrieve data 
 - issue and re-generate API keys in EasyWriter user interface 

Milestone 3:  When users utilise an asynchronous API with error handling to write to Filecoin and user can also log into an account and change Layer1 blockchains (e.g. switch from Algorand to Filecoin, etc.). 
Effort estimate = 3FTE for combined 50 FTE days 
Milestone deadline proposed for end May 2023 
Phase 3 funding requirement = $15,000 

## Total Budget Requested 
Total budget requested is $45,000 

This budget is to cover developer and tester time and effort.  It is based on $300 per day as a blended FTE day rate for our development team. 

## Maintenance and Upgrade Plans 
Upgrades: 
Arivu are targeting 3 new blockchains per year, to be added to the product. 
2024 will see the launch of Smart Contract execution added to all blockchain providers. 

Maintenance:
Arivu operate a serverless architecture in Azure, this means continuous operating system upgrades and patches are applied with zero downtime. 

# Team 
Mark Cliffe – CTO 
Matthew Nelson – CEO 
Noel Kilby – Co-Founder 
Gerald Acheampong – Co-Founder 
Stuart Lacey – Developer 
Mike Deane – Commercial Director 
Richard Clouter – Chief Risk Officer 

## Team Member LinkedIn Profiles 
Matthew Nelson https://www.linkedin.com/in/rmatthewnelson/ 
Mark Cliffe https://www.linkedin.com/in/cliffey/ 
Noel Kilby  https://www.linkedin.com/in/noelkilby/ 
Gerald Acheampong  https://www.linkedin.com/in/gerald-acheampong-9704746/ 
Mike Deane  https://www.linkedin.com/in/michael-deane-1b8747/ 
Richard Clouter  https://www.linkedin.com/in/richard-clouter-a907741/ 

## Team Website 
https://arivu.io/ 

## Relevant Experience 
Mark Cliffe CTO - Mark has over 20 years experience in FinTech and Legal Process Outsourcing and has built market-leading applications to visualise workflows and life-cycles of people and automated tasks.  His focus is on how to bridge the gap between off- and on-chain data platforms to radically enhance business decision making.  Mark wants Arivu's technology to equip user communities with a secure and trustworthy ability to conduct business. 

Noel Kilby Co-Founder - Noel founded his first business in 1997 building and rapidly scaling it into a global operation spanning Europe, North America, Asia and Australia and serving numerous regulators, tier 1 banks, magic circle law firms and big 4 accountancies along the way.  Noel is an active Angel investor, mentor and crypto investor and has served four years on the selection committee for TechStars in the UK.  Noel wants Arivu's technology to be instrumental in the proliferation of green energy. 

Gerald Acheampong Co-Founder - Gerald brings over 15 years of systems engineering and technology infrastructure experience in large corporates and a global technology consultancy.  Gerald is also an active crypto investor and advisor in the De-Fi space.  Gerald wants Arivu's technology to become a protocol-agnostic, cross-chain service to dramatically improve investor protection. 

Matthew Nelson CEO - Matthew brings over 24 years of banking, capital markets, investment management and start-up experience to Arivu.  His experience includes architecting and building shared service banking back-office platforms and developing the world's first cloud-based data repository for global real estate investors.  Matthew wants Arivu's technology to provide a bridge to translate off-chain contracts into on-chain, collaborative solutions. 

Stuart Lacey Developer - Stuart comes from a graphic design background with skills in illustration, iconography and photorealism.  Focussing primarily on UX, Stuart uses jQuery and CSS technologies to build responsive web applications which are desktop and mobile-friendly.  Stuart would like Arivu's technology to democratise identity and asset ownership for communities globally. 

 

## Team code repositories 
https://ArivuDigitalLtd@dev.azure.com/ArivuDigitalLtd/Arivu%20Dev/_git/Arivu%20Dev 

 

# Additional Information 
  GitHub 

  matthew.nelson@arivu.io   and 
mark.cliffe@arivu.io

 

Arivu’s first blockchain integration for EasyWriter is Concordium (https://concordium.com), the world’s first identity-led blockchain for business.  https://concordium.com/ 

Arivu has been grant funded for that integration and is targeting a range of business-friendly public blockchains for future integrations.

**Comment by ErinOCon** [comment]
Hi @rmattnelson, thank you for your proposal. While we will not be proceeding with a grant at this time, you may have an interest in exploring [Estuary software](https://estuary.tech/) for this project! 

Wishing you all the best as you continue to build!
