### ISSUE TITLE
Next Next Step Microgrant: The Bacalhau Grimoire

### ISSUE THREAD

**Issue by tippi-fifestarr** [filecoin-project/devgrants#1377]
### 1. What is your project, and what problem does it solve? (max 100 words)

> 🧙 In D&D, the gameplay is driven by imagination.  It’s about storytelling in worlds of sorcery and swords and sometimes, Dragonborn people with Red Dragon Ancestry. We must create an environment that your character lives in, and that character needs to look and feel right.  **You have to be able to show, with words or images, who you are.** This isn’t easy for first-timers or people with lack of time or weak imagination muscles. 💪 Our tools will help players with generating their character avatar, driven by NFT.Storage, Stable Diffusion and Bacalhau.

"The Bacalhau Grimoire" is the next Next Step after our [Operation Dragonborn Next Step Grant](https://github.com/filecoin-project/devgrants/issues/1232).  Originating with our "Top Quality" Chainlink Hackathon project [D&D Diffusion](https://devpost.com/software/dndiffusion). Our focus for this sprint will be **the narrow objective of integrating Bacalhau into our end-to-end user experience MVP.** Bacalhau gives us free and decentralized cloud compute so we can enable Optical Recognition of Character-sheets (ORCs), allowing our users to upload a screenshot or photograph of their character sheet instead of just a PDF.

This year, we want to create usable, unique, AI generated visual assets for a game that’s been played for generations. Using cutting edge technology, we are going to bring people together for collaborative storytelling, inspire creativity and save time! Tabletop roleplaying is a multibillion dollar industry and not enough of it is decentralized. Our future platform will connect AI generated art to an NFT marketplace for human artists to participate in the conversation between players and their imaginations.

### 2. Project links
  
Link to Github repo:

https://github.com/DnDnDiffusion

Link to demo or website, if applicable:

https://operation-dragonborn-git-nftstorage-operationdragonborn.vercel.app/

Link to "The Bacalhau Grimoire" progress:

https://danj-o.notion.site/The-Bacalhau-Grimoire-5548482ade27446ebc811b229b6acdb9

License: MIT

### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
We use IPFS and [NFT.Storage](http://nft.storage/) to get a CID and pin the user’s chosen avatar image.  

We then create a ERC-721 metadata blob with that CID, and pin it through NFT.Storage again.  

This becomes the tokenURI for the users NFT. 

Example NFT on Goerli testnet here: [https://testnets.opensea.io/assets/goerli/0x4379044facb5f0879de15e70b45afd495a197674/16](https://testnets.opensea.io/assets/goerli/0x4379044facb5f0879de15e70b45afd495a197674/16)

In the scope of this grant, we will be integrating Bacalhau GPU Easy OCR processing of the character sheets (ORCs). This has IPFS all over it.  As a bonus deliverable, we can mint a special edition Dragonborn in Interplanetary Space (but only if someone mentions it in the comments).

###    b) Is this project building with FVM? (Yes or No)

NO.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We will integrate Bacalhau GPU OCR processing of the character sheets into our front-end, to provide users with a more ideal upload method. They can easily take a picture or screenshot of their sheet and then upload the .png to our app and see some key information rendered onscreen.  This data is used to generate the prompt, which is used to generate the images.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.  We have a team of Technical Sponsors which include [Discordian](https://github.com/TheDiscordian/), [Dawn Kelly](https://github.com/dawnkelly09), [Developer Ally](https://github.com/DeveloperAlly), [Alexandre Nicastro](https://github.com/AlexxNica) and [Jenks Guo](https://github.com/jenksguo).  We regularly attend the Protocol Labs Office Hour and communicate with them on Slack.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:

For each team member(s), please list name, email, Github account, and role in the project.
- Tippi Fifestarr: Founder, HR, Product & DevRel
    - [fifestarr21@gmail.com](mailto:fifestarr21@gmail.com)
    - [https://github.com/tippi-fifestarr](https://github.com/tippi-fifestarr)
- Somya Tomar: Developer (R&D, back-end, ML)
    - [somyatomar15@gmail.com](mailto:somyatomar15@gmail.com)
    - [https://github.com/somya-15](https://github.com/somya-15)
- Danjo the 0x: Chief Technology Officer
    - [danjo@danj0x.com](mailto:danjo@danj0x.com)
    - [https://github.com/danj-O](https://github.com/danj-O)
- Jason Demma: Creative & Humanity Officer
    - [creatjve@gmail.com](mailto:creatjve@gmail.com)
    - [jasondemma.com](https://www.jasondemma.com/)
- Aire: Developer
    - [aire.forwork@gmail.com](mailto:aire.forwork@gmail.com)
    - [https://github.com/airecr](https://github.com/airecr)
- Alex: Front-end Development Intern
    - [carteblanchecarriage@protonmail.com](mailto:carteblanchecarriage@protonmail.com)
    - [https://github.com/carteblanchecarriage](https://github.com/carteblanchecarriage)
- Ali: Front-end Development Intern
    - [alizahreddine89@gmail.com](mailto:alizahreddine89@gmail.com)
    - [https://github.com/0xAli0x](https://github.com/0xAli0x)

* How did you learn about our microgrant program?
    - Tippi introduced our team to this grant, Dawn recommended we apply again.

* If your project was created as part of an event or hackathon:
    - Chainlink Fall 2022: https://devpost.com/software/dndiffusion

**Comment by wesfloyd** [comment]
Big fan of the goals for this grant. Sharing existing related documentation in case it is helpful to get you started: https://docs.bacalhau.org/examples/model-inference/EasyOCR/

Love to get your feedback along the way in case you find better algorithms/approaches than the example above 👍

**Comment by somya-15** [comment]
Hi @wesfloyd,
Thanks a lot for sharing the Bacalhau EasyOCR documentation, we were super excited about it and headed directly to use it as a focused feature of our project. We were able to implement it really smooth on Colab. I have been stuck on getting the endpoints for a couple of weeks. We want to connect our frontend to Bacalhau EasyOCR (and maybe even Stable Diffusion with our custom models in it). 

How can we make this connect?

We would love to meet you to overcome these obstacles and have ideas about better algorithms/approaches for our use case. By the way, have you played DnD?

**Comment by wesfloyd** [comment]
Yes, you can test with our generic endpoint documented here: https://bacalhau.substack.com/p/bacalhau-project-report-feb-3-2023#%C2%A7a-generic-endpoint

For any technical questions, please post to the public [#bacalhau channel in Filecoin slack here](https://bit.ly/bacalhau-slack)

**Comment by ErinOCon** [comment]
Hi @tippi-fifestarr, congrats on your project progress! We will not be moving forward with an additional grant at this time, but welcome you to keep an eye out for future grant opportunities that may align with our [focus areas](https://github.com/filecoin-project/devgrants) in the future. 

Wishing you all the best as you continue to build!

**Comment by tippi-fifestarr** [comment]
@ErinOCon Thank you for your best wishes! We've entered the Chainlink Spring Hackathon (it's been 6 months already!), here is our site if you'd like to make yourself a Dragonborn or two: https://ceptor.club/
