### ISSUE TITLE
Zerocap Research Lab

### ISSUE THREAD

**Issue by SgtPeppers1** [filecoin-project/devgrants#1378]
Filecoin Foundation Open Grant Application

# Open Grant Proposal: Filecoin Research Grant
**Name of Project:** `Zerocap Research Lab`

**Proposal Category:** `research`

**Proposer:** `SgtPeppers1`

**(Optional) Technical Sponsor:** `Jenks Guo`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** Yes
# Project Description

**Problem**

The main problem that we will be solving with this project is education. Zerocap is in a unique position with our institutional & crypto-native client base and reach to sufficiently educate the wider community about important projects in the space. Unfortunately, inside and outside of our industry, many individuals and teams are insufficiently educated relating to Filecoin and IPFS. There are two fundamental problems I have observed here:
- **Purely technology based information**: These individuals understand all of the specific details relevant to Filecoin, yet their knowledge is relatively siloed - they are unaware of how IPFS and Filecoin interact with the rest of the world. Nonetheless, these individuals see the future of Filecoin external to simply making money in the nascent industry. The Research Lab can explore the current use cases for Filecoin and expand on the future potential for the protocol. In doing so we will attempt to educate them on how to use their knowledge to drive adoption to the industry through a greater cognisance for a more holistic view of the market.
- **Surface level knowledge**: These are the individuals who are selling, promoting, beginning to learn about and new to the crypto space. Without specific details relating to Filecoin, they are failing to accurately educate and inspire new individuals to enter the industry. Moreover, in my experience, these people frequently make up information to obfuscate their lack of understanding; it is easy to see how these actions are detrimental to the space.

On top of those two issues, many other individuals fall in between the ends of the spectrum. These people LOVE the decentralised storage industry and want to learn more about the specific details of the space. These are the people who do not understand the significance of IPFS, or the impact of the Filecoin Virtual Machine, for example. Education here is crucial. Many individuals in this category have the potential to become the next wave of innovators - only if educational pieces are catered to them. In a similar sense, there is another class of individuals, primarily new developers, who cannot find coverage on esoteric concepts. This is drastically poor when juxtaposed with the TradFi industry which sufficiently covers more concepts through academic papers, podcasts, blog posts and general article posts.

**The Solution**

The solution is a new Research Lab, targeting enterprises, crypto-natives, degens, institutions, banks and developers focused on educating the entire community on a range of relevant issues, such as Filecoin! This may sound highly ambitious but the driving principle behind the lab is to become an **ecosystem of knowledge**. This is achieved through a three tier structure:
- **Tier 1 - Foundational**: Spanning beyond core basics, foundational research pieces provide an educational resource for entry-level blockchain researchers. The aim is to provide a healthy foundation of knowledge which can be used as a fundamental reference point for more advanced topics.
- **Tier 2 - Innovation**: In-depth analysis of advanced blockchain related topics in an easily digestible yet technical format. We focus on applications of blockchains in specific domains while providing a forward thinking framework that gives readers the foundation to solve practical problems and predict future trends. As well as diving into particular technical details and thoroughly explaining them, this tier takes a general look at the importance of this infrastructure piece in the context of the wider market.
- **Tier 3 - Full-Length Report** (temporary name): Full-length reports expanding on sophisticated topics, applying critical thinking to predict market trends from a first principles perspective. Our applied research assists in identifying specific problems that blockchain technology can solve as well as the technical resources to execute in rectifying those issues.

We are better suited to solve the problem outlined above as, unlike other similar research labs/teams, there will be no assumed knowledge. This is frequently an impediment for readers to follow the carrot down the rabbit hole and even finish the article. The Zerocap Research Lab will not require any prior knowledge given that the articles will span every relevant area of the space - for example,  if we reference IPFS in an article on the FVM, we will backlink to an article we wrote specifically on IPFS!

## Value

IPFS is revolutionary technology with benefits existing outside of the crypto space. The grant going to the Zerocap Research Lab such that we write regular pieces on the technology is valuable to the current ecosystem and future ecosystem, that is, the members of the community that are presently utilising Filecoin will be able to learn more about the technology and the papers will assist educating those who are thus far unaware of the true potential of Filecoin. As mentioned already, Zerocap has a huge reach across many institutions and countries. Along with distributors like Bloomberg, institutions like the ASX, Commbank and Morgan Stanley as well as family offices, impact investing funds and sovereign wealth funds, our readers include the crypto-native community as our articles will be going out through platforms like DeFiLlama and more. With reference to the traffic on our platform, our reach is global. As you’d anticipate, our strongest location for the origination of our traffic is Australia, closely followed by the USA, UK, France, the UAE, China. Accordingly, though less significant, the visitors of the website are also dominated by Colombia, New Zealand, Canada and Turkey. Furthermore, here are some more details I have pulled from our website:

- Greater than 50% organic growth YoY across primary marketing channels (website traffic, social media, email, referrals).
- Steady month on month growth of subscriber database
- Global tier 1 media coverage with a market reach of more than 20 million
- Strong brand awareness as evidenced by media mentions, award recognition, key industry event participation, website backlinks

Notably, although there are many other research labs attempting to educate the community, the Zerocap Research Lab can differentiate itself in a plethora of ways, each adding additional value to the Filecoin and IPFS ecosystems:

- **Article Structure** - Unique 3 tier structure caters to all
- **Accessibility** - All pieces in the Zerocap Research Lab, including those written under the grant funding, will be free and available to all readers desiring to learn about Filecoin, making in-depth research accessible to all readers in a digestible format. 
- **Ecosystem Collaboration and Ecosystem Wide Engagement** - We frequently collaborate within the community to shed light on new projects and ideas in the space. Additionally, we can leverage our existing client base and strong reach to ensure that the ecosystem grows through disseminating research papers to a broader audience

**Benefits**

The benefits of getting this right is clear; more individuals and companies will learn more about Filecoin, IPFS and the role of the chain/technology in bringing web3 closer to mainstream adoption without relying on web2 alternatives. Research Lab articles will not only excite our readers but illustrate specific use cases and technical aspects of Filecoin which can drive adoption. The ecosystem will burgeon with more institutional involvement (banks, exchanges, etc), family office interest / high net wealth individuals as well as more individuals realising the utility of Filecoin and the FVM. If we get this right by writing and disseminating numerous articles on Filecoin and IPFS each month, additional discussions, ideas and applications will gradually move into the ecosystem as knowledge/information spark inevitably result in future innovation.

**Risks**

If the Zerocap Research Lab does not manage to effectively educate the wider community (within and without the crypto space), the growth of Filecoin and influence of IPFS is at risk of stagnating. Growing in the context of an insular community is dangerous. Through Zerocap's networks and readers, we will be able to ensure that Filecoin is never trapped in a vacuum of a community but instead circulating throughout the space. If we fail here, the benefits of decentralised storage, namely Filecoin, may not be leveraged by other individuals and entities. Furthermore, there exists risks that make executing on this project difficult. There is a lot of information to get across, distill, make understandable, digestible and interesting to read. If the research pieces do not remain interesting, we will fail at educating to the fullest extent given that the number of readers will likely decrease. Likewise, making technical information, for example, how IPFS works, easily comprehensible is no easy task. Fortunately, we are up to the task of overcoming these risks through the experience and knowledge of our team, the writing background of the team, and our collaborative nature!

## Deliverables

The final deliverable will be a series of articles on Filecoin, IPFS and their relevance in the wider crypto and storage industries being researched, written and published through the Zerocap Research Lab. These articles will be free and available to the community to read and invigorate their knowledge and passion for Filecoin. All Filecoin-related articles will go through our list of distributors (which includes Bloomberg, True Altitude and more - list available upon request) such that they are seen by the most amount of people. The lab will deliver on comprehensive writeups, clear definitions and unique research investigations relating to Filecoin.

All articles written as part of the research allowed for by the grant will remain on our soon to be released Zerocap Research Lab website. Upon being launched and throughout the passage of time, these articles will not be behind a paywall, ensuring the information is available to all readers. 

### Stage 1: ###

**Stage Description:**

This stage will primarily be focused on writing the base articles that will be referred back to throughout the remaining stages. In this way, stage 1 will see the completion of articles along the lines of:

- What is Filecoin?
- What is the Filecoin Virtual Machine and What Possibilities Does it Unlock?
- The Inner Workings of IPFS
- And more

Stage 1 will see the launch of the Zerocap Research Lab, with Filecoin related pieces being written and launched frequently. At this point of the roadmap, the output schedule will be:

- 4 tier 1 pieces per month
- 2 tier 2 pieces per month
- 2 collaborative / project specific pieces per month
- 1-2 tier 3 reports per quarter

**People Involved:**

At stage 1, there will be 2 team members working on the Filecoin articles. We are both knowledgeable on the subjects of the philosophies of Filecoin, the architecture of the blockchain, IPFS and more. Importantly, the funding in this stage will be used to increase the salary of one of the team members as he takes on more responsibility in going further down the Filecoin and IPFS rabbit holes. This writer will take ownership of most of the pieces written in this stage whilst I begin researching for tier 2 pieces we cover in stage 2.

Additionally, in stage 1, we will make another hire for the research lab - a young, yet experienced, part time researcher that too has experience with Filecoin and similar technologies. Hiring this analyst in stage 1 will be crucial to have sufficient time to onboard him such that he can contribute most effectively in future stages.

**Timeline:**

Stage 1 will last for 1.5 months. 

I expect (and hope) to start the project on the 15th of February, hence:

15th of February, 2023 - 1st of April, 2023

**Funding Breakdown:**

For this stage, US$ 6k will be split between setting aside and utilising funds for increasing the salary of our current analyst, while the remaining value will go to hiring and paying for the new analyst.

### Stage 2: ###

**Stage Description:**

The second stage will concentrate on distribution of the articles, partnering with community members building on Filecoin and the FVM and increasing the depth of research pieces. Stage 2 will build on stage 1; our thesis for the 3 tier output structure sees that all content is covered through other articles or glossaries - tier 2 pieces will refer back to existing tier 1 pieces completed in stage 1. At this point, the research will explore more advanced topics without losing the digestible, comprehensive and easily understandable qualities of our content.

With a larger team, as detailed below, at this point of the roadmap we will be increasing our output of general articles, including Filecoin/IPFS related pieces. The intended output schedule for stage 2 is:

- 6 tier 1 pieces per month
- 3 tier 2 pieces per month
- 3 collaborative pieces per month
- 1-2 tier 3 reports per quarter

**People Involved:**

Stage 2 will be where the team begins utilising our newly hired analyst from stage 1. Accordingly, at this point, there will be a total of 3 people working on the project, hence investigating new concepts relating to Filecoin. Any relevant insights will be incorporated into tier 2 research articles. 

As mentioned above, this stage will strive for community engagement. Therefore, one of the analysts involved in the grant side of the research lab will spend time selecting innovative teams in the ecosystem and building a relationship with their team. Throughout stage 2, the research team will collaborate with these projects to accentuate what they are building, why it is important and the benefit to the wider community.

**Timeline:**

Stage 2 will last for 2 months. 

1st of April, 2023 - 1st of June, 2023

**Funding Breakdown:**

For this stage, US$ 8k will be utilised.

This can be divided up as such:
The majority of the funds will be allocated to paying the newly hired research analyst and covering the increased rate for the initial analyst in the team
In this stage, significantly more time will be spent on researching different features of Filecoin in depth - the current focal points include:

- The potential of the FVM
- The game theory and mechanism design behind being a Filecoin validator
- The role of financial incentives in Filecoin
- Finding an equilibrium for demand and supply for Filecoin storage

### Stage 3: ###

**Stage Description:**

As the final stage within the grant, this shorter stage will focus on a smaller amount of research pieces that weave together all previously completed articles. In stage 3, although additional tier 1 and tier 2 pieces will be written, the notable difference of this stage is the inclusion of a tier 3 piece. This piece will likely be written in collaboration with an Australian-based institution or dominant player in the ecosystem; the report will act as a ‘hitchhikers guide for Filecoin and IPFS’ whilst concurrently proposing new areas for research and improvement with respect to the blockchain. 

Stage 3 will maintain the output schedule outlined in stage 2. However, another difference in the way in which the grant funds and coverage of Filecoin/IPFS will factor stage 3 is their integration with other articles. Stage 3 will investigate Filecoin's long term importance in the web3 stack, hence will begin to reference IPFS and the blockchain in relation to other forthcoming narratives and concepts in the industry.

**People Involved:**

The people involved in stage 3 will be the same as stage 2; the 3 Filecoin-informed analysts. However, with more detail going into the pieces, research concepts will be obtained from the wider Zerocap trading teams at no cost to the project. In addition, as mentioned, it is likely that financial institutions based in Australia will get involved with writing articles at this stage to contribute to the lab.

**Timeline:**

Stage 3 will last for 1 month. 

1st of June, 2023 - 1st of July, 2023

**Funding Breakdown:**

For this stage, US$ 4.5k will be utilised.

All funds will go to paying analysts for the research and obtaining on-chain data. This is the same as the funding breakdown in stage 2. The only difference here is the shortened length of this stage as the time that will go into writing tier 3 reports.

## Total Budget Requested

The grant funds will be used to increase the people power within the Research Lab and provide our existing team with pay commensurate to the additional work and effort they are putting in. Gradually, we will use the funds to invest more into our team and the quality of the reports by contracting developers to work with me to obtain on-chain data.

Breakdown:

- Funds will be used to cover the increased rate of an analyst as he takes on additional responsibilities relating to researching further into it Filecoin and IPFS through more working hours
- 5 months of the increased wage = US$ 5k
- Hiring another analyst (part time) to write articles that range from a simple difficulty to deeply technical concepts relating to the technology
- 5 months = US$ 13k
- Obtaining quantifiable, on-chain research data for advanced pieces
- US$ 2k throughout all pieces across 5 months

The total estimated budget is US$ 20k over a 5 month period.

## Maintenance and Upgrade Plans

We have an extremely colourful, saturated vision for the future of the Zerocap Research Lab. With the ambitious goal of offering an ecosystem of knowledge, all points of content must be covered in some capacity. Filecoin and IPFS make up a significant portion of the content that we want to cover.

In this way, the maintenance and upgrade plans will see us gradually integrate more of the Filecoin content into other articles we write that are relevant to the technology. Similarly, we will continue to return to tier 1 and tier 2 articles that have information that will cease to be accurate through time; the team will make the necessary changes to guarantee these quantitative details are invariably correct. More specific to our upgrade plans, the lab intends to constantly improve the appeal and reach with funding, partnerships and more content. Given that the Filecoin content comprises the lab, the aesthetics, graphics and look of the pieces will continuously be improved with branding upgrades and novel ideas, including glossaries, future collaborations and more.

# Team

We are a small team working within a larger company. There are plans to expand the team gradually with more funding and an effective launch.

## Team Members

Trent Barnes
Nathan Lenga
Finn Judell

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/trentbarnes/
https://www.linkedin.com/in/nathan-lenga/
https://www.linkedin.com/in/finn-judell-295477149/ 

## Team Website

https://zerocap.com/

## Relevant Experience

Trent is a force to be reckoned with in the business world, as the co-founder of a successful venture capital fund, Primal Capital, co-founder and Chief Innovation Officer at Zerocap, and a seasoned serial entrepreneur. Trent’s experience in sales, business development, and recruiting, combined with his skills as a writer and analyst, make him perfect to work on this research and education project. As an early investor in IPFS-related blockchains and platforms, Trent has an in-depth knowledge and understanding of Filecoin and the many moving pieces within the ecosystem. But Trent does not stop there, he is also an avid surfer, used to be a rapper, a contrarian, free thinker, making him a unique and well-rounded individual. 

Nathan is an experienced coder with a background in decentralised systems. He is well-versed in a variety of programming languages such as WASM, JavaScript, Rust, C++, and Go; knowledge relating to these languages are especially helpful for understanding the architecture of Filecoin. He has a computer science and commerce degree, giving him a strong foundation in both technical and business aspects of the field. In addition to his coding skills, Nathan is an avid writer and researcher, with a focus on decentralised systems, game theory, mechanism design, and game theory. His knowledge in these areas combined with his coding skills make him a valuable asset in the Filecoin and IPFS focused project. 

Finn is a unique individual in the blockchain space, with a diverse set of skills and experiences. He too is an experienced writer, with a talent for articulating complex ideas in a clear and engaging way. Finn has also been an innovator at several startups, focused on public goods and freedom of information. He is an early participant and contributor to Protocol Labs projects, including validating the Filecoin chain and mining FIL. With a deep cognancy of Filecoin and IPFS, as well as a capable writer with strong ties to the community having previously worked as a crypto-focused recruiter, Finn is perfectly suited to educate the institutional and wider community on the technology and its potentials.

Our team, with their diverse backgrounds in many fields and industries, brings a unique set of skills and perspectives to the research and education project for Filecoin and IPFS. From early contributors to Protocol Labs projects, to innovators in startups, to consultants in the blockchain space, we have a deep understanding of the intricacies of decentralised systems and the potential of this technology. We are confident in our ability to deliver valuable insights and educate others on the potential of Filecoin, and we look forward to the opportunity to contribute to the growth and success of this promising blockchain company.

## Team code repositories

Given the nature of the project, there are no code repos relevant to the Zerocap Research Lab. However, in lieu of code repositories, I’ve included some examples of our past research projects and work!

NB: Existing articles for the research lab are unavailable as they are PDFs - not published yet. However, upon request, I can send a bunch through. Most of these do not relate to Filecoin.

Main website: https://zerocap.com/category/zerocap-articles/
Other research articles:
-  ReFi part 1: https://zerocap.com/regenerative-finance-part-1-how-it-works-and-why-it-matters/
- ReFi part 2: https://zerocap.com/regenerative-finance-part-2-a-new-financial-paradigm/
- ReFi part 3: https://zerocap.com/regenerative-finance-part-3-social-incentives-and-the-endgame/
- "Has Ethereum Become More Centralised After the Merge?": https://zerocap.com/has-ethereum-become-more-centralised/ -- lots of love to the team, but loving critics are always going to exist ;)
- "Bitcoin History: What Led to the First Cryptocurrency": https://zerocap.com/bitcoin-history-first-cryptocurrency/
- "How do DeFi Protocols Make Money?": https://zerocap.com/how-do-defi-protocols-make-money/
- "Crypto Trends in South Korea: Metaverse, NFTs and the Digital New Deal": https://zerocap.com/crypto-trends-in-south-korea-metaverse-nfts-and-the-digital-new-deal/

The unpublished research lab pieces include:
- "Decentralised Blockchain Governance: Challenges of Current DeFi, Mental Models and a Proposed, Frictionless Framework" - governance failures, consideration of edge cases through game theory and mental models before the proposal of a new model
- "Finding an Equilibrium Between the Demand for Ethereum Mainnet and Rollups". Quantitatively discussing the impacts of future EIPs and rollup upgrades, how that will impact perception, and the end state. This is a 40 page research report into the dynamic interrelation between Ethereum and its layer 2s
- "The Future of Ethereum" - all of the EIPs and large upgrades / roadmap stages  explained at a very simple level
- "The MEV Environment" - 0 to 1 on MEV
- "The Move Ecosystem" - Move as a language, Sui and Aptos
- “What is Decentralised File Storage and How Does it Work?” - simple coverage of IPFS, Filecoin and Arweave 
- "The Possibilities of Zero Knowledge Proofs" - Highly simplified explanations on what ZKPs are and some potential applications for the future
- "The Evolution of Monolithic to Modular Blockchains" - I think the title is pretty clear :)
- "Applications of a Virtual Machine on Filecoin" - This one is still going and getting a bit too long but similar to above, the contents of the article is clear

And there are a lot more completed research articles available upon request

# Additional Information

I learnt about the Open Grants Program through Jenks after a conversation with him about how Zerocap can work with the Filecoin Foundation

The best email address is `nathan.lenga@zerocap.com`

As I assume is clear throughout my submission, I am a huge fan of the Filecoin ecosystem and have always been drawn to its potential to shape the future of technology and society. The technology and underlying cryptography is what encouraged me to cease pursuing a career in computational computer science and jump into the cryptocurrency arena. I am passionate about exploring and understanding the full range of applications and implications of Filecoin, and I firmly believe that a section of a reputable research lab dedicated to this purpose is vital to the ongoing development and advancement of the Filecoin and IPFS communities.

I am beyond excited to apply for this grant from the Filecoin Foundation to establish a research lab that will focus on the latest developments and trends in the decentralised storage networks, as well as the potential for Filecoin to address real-world challenges and opportunities. With this grant, we will be able to conduct cutting-edge research, educate and engage with the wider Filecoin community to share our findings and insights. Similarly, I’d love to take this opportunity to propose collaborations with the Filecoin Foundation. Working with inspirations is invariably an awesome experience that I will never not push for!

**Comment by ErinOCon** [comment]
Hi @SgtPeppers1, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
