### ISSUE TITLE
Historical Collection Decentralized Storage

### ISSUE THREAD

**Issue by tokenville** [filecoin-project/devgrants#1379]
# Open Grant Proposal: Historical Collection Decentralized Storage

**Name of Project:** Historical Collection Decentralized Storage

**Proposal Category:** app-dev

**Proposer:** Tokenville / Mintmade

**(Optional) Technical Sponsor:** Piyush Maheshwari

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** Yes

# Project Description

The Historical Collection is a decentralized user-generated catalog of articles from verified news outlets (now Cointelegraph). It utilizes blockchain technology and NFT standards to store and transact value, and also combines principles and engagement patterns common to the web3 community. In simple terms, it aims to bring back the value to news outlets by providing an easy way to sell articles as digital collectibles.

The next step in the development of the Historical Collection Protocol is to store these articles in decentralized storage provided by FileCoin. This will ensure that the articles are stored in a secure and decentralized manner, making them easily accessible to anyone who wants to view them. This feature will also make it possible for users to own a physical copy of the article, as the NFT will be linked to the article's content stored in FileCoin.

The project was already implemented on Cointelegraph: http://cointelegraph.com/historical/

## Value

This proposal is valuable for the FileCoin ecosystem as it will increase the usage of FileCoin's decentralized storage. Storing articles in decentralized storage will ensure that the articles are easily accessible to anyone who wants to view them even if the media will be down.

It will also create a new use case for FileCoin and bring more attention to the idea of the decentralised storage as we will add FileCoin logo to ensure that all users coming from media outlets know that the data is stored securely.

![filecoin_preview](https://user-images.githubusercontent.com/34478472/214031570-99a61c67-d6c4-4c75-bc48-0bb99842295c.png)

## Deliverables

1. All Cointelegraph articles minted into NFTs and article previews are stored on FileCoin.
2. The FileCoin logo is presented on the minting page.
3. If a new media outlet is connected to the protocol they are getting the same feature.

## Development Roadmap

**Milestone 1: Research and Development**

- Software functionality: Research and development of the technical aspects of the Historical Collection Protocol and its integration with FileCoin decentralized storage.
- Team members: 2 developers, 1 designer
- Funding required: $20,000
- Timeframe: 2 months (January-February 2023)

**Milestone 2: Implementation of FileCoin storage**

- Software functionality: Implementation of the FileCoin decentralized storage system for the NFT articles in the Historical Collection Protocol.
- Team members: 2 developers, 
- Funding required: $15,000
- Timeframe: 2 months (March-April 2023)

**Milestone 3: Testing and Quality Assurance**

- Software functionality: Testing and quality assurance of the integrated Historical Collection Protocol and FileCoin storage system.
- Team members: 2 developers, 1 tester
- Funding required: $5,000
- Timeframe: 1 month (May 2023)

**Milestone 4: Launch and PR**

- Software functionality: Deployment of the integrated Historical Collection Protocol and FileCoin storage system to the mainnet; additional PR and marketing support on Cointelegraph.
- Team members: 1 developer, 1 maintenance engineer
- Funding required: $15,000
- Timeframe: 1 month (June 2023)

## Total Budget Requested

The total budget requested for the development and deployment of the Historical Collection Protocol and its integration with FileCoin decentralized storage is $55,000. The breakdown of the budget is as follows:

1. Research and Development: $20,000
2. Implementation of FileCoin storage: $15,000
3. Testing and Quality Assurance: $5,000
4. Launch and PR: $15,000

## Maintenance and Upgrade Plans

The development team plans to provide ongoing maintenance and support for the integrated Historical Collection Protocol and FileCoin storage system. This includes regular updates and upgrades to ensure the system remains secure and stable. The team also plans to work closely with the FileCoin community to ensure the system is fully integrated and compatible with future developments in the FileCoin ecosystem.

# Team

## Team Members

- Ivan Sokolov (founder, product manager) [LinkedIn](https://www.linkedin.com/in/ivansokolov2017/)
- Anna Shakola (CBDO) [LinkedIn](https://www.linkedin.com/in/anna-shakola-a8731992/)
- Damir Iskhakov (CTO)
- Ruslan Zakirov  (front-end developer)
- Anton Spizman (full-stack developer)
- Andrei Maslichenka (DevOps engineer)
- Vlad Alyakin (UI designer)
- Bridget Imarhia (community manager)

## Team Website

https://tokenville.tv
https://mintmade.io

## Relevant Experience

Tokenville was exploring the topic of blockchain and media since 2018 when we launched the first show powered by smart contracts – [Deus ETH](https://deuseth.com). After partnering with Cointelegraph we launched our own tokenization platform called [Mintmade](https://mintmade.io) and now we are 100% dedicated to its development and adoption.

## Team code repositories

https://gitlab.com/damlab/mintmade-frontend

# Additional Information
**How did you learn about the Open Grants Program?:** Cointelegraph Acceleration Program.
**Contact email:** i.sokolov@tokenville.tv

**Comment by ErinOCon** [comment]
Hi @tokenville, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time. Wishing you the best as you continue to build!
