### ISSUE TITLE
Next Step Microgrant: CashFlow

### ISSUE THREAD

**Issue by ffatique** [filecoin-project/devgrants#1382]
### 1. What is your project, and what problem does it solve? (max 100 words)
Cashflow is a graphical protocol that is able to combine information from token transactions into a knowledge graph, enabling a new generation of data queries that allow analysis and visualization of transaction relationships on the blockchain. It is also possible to mitigate the risk of investing in new projects when you manage to have a service to help you explore the transaction data of a token on the blockchain.

It is also possible to obtain clear information and data about large holders of the FIL token in addition to large institutions that also hold it.

### 2. Project links
  
Link to Github repo: https://github.com/sozei-ti/sozei-cashflow-filecoin
Link to demo or website, if applicable: https://sozei-cashflow-filecoin.vercel.app/
License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)
Filecoin is used in our project to bring clarity to the exploration of wallets that use this token on the BSC network

b) Is this project building with FVM? No
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
With this grant, our team will be able to dedicate more time to the development of this tool, adding new visual resources to it.

Objective: Deliver the complete CashFlow tool in 8 weeks.

steps:
Week 1 and 2: Expand transactions over time history at each node to past and future
Week 3 and 4: Integrate new information filters
Week 5 and 6: Integrate Transaction Grouping by Wallets
Week 7 and 8: Create Tags to track large filecoin holders and trading entities in real time

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### Additional questions:
Felipe Fatique, [felipe.fatique@sozei.com.br](mailto:felipe.fatique@sozei.com.br), https://github.com/ffatique, FullStack Developer
Rivan Belo, [rivan.belo@sozei.com.br](mailto:rivan.belo@sozei.com.br), https://github.com/rivanbello , CTO
Alexandre Osorio, [ale.osorio@sozei.com.br](mailto:ale.osorio@sozei.com.br), CEO
Guilherme, [gui.bassoli@sozei.com.br](mailto:gui.bassoli@sozei.com.br), CMO

**Comment by ErinOCon** [comment]
Hi @ffatique, thank you for your proposal. We will not be moving forward with a proposal at this time. Wishing you the best as you continue to build!
