### ISSUE TITLE
Next Step Microgrant: Web3 Goals + FVM

### ISSUE THREAD

**Issue by kiv1n** [filecoin-project/devgrants#1386]
### 1. What is your project, and what problem does it solve? (max 100 words)

Web3 Goals is an app in which a person can set a personal goal and stake funds on it. If the goal is achieved, he will return the stake, otherwise the funds will be shared between people who have subscribed to this goal.

This solution will give person an external motivation not to lose money. He will be concerned about failed goals as non-transferable NFTs will be linked to his blockchain account.

There will also be group goals and competitions between people who want to achieve the same goal to give people even more motivation and fun.

### 2. Project links
  
Link to Github repo: https://github.com/web3goals
Link to demo or website, if applicable: http://web3goals.space/
License: MIT  
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project? (max 200 words)

Right now the prototype is running on Polygon Network, but I want to switch to FVM because this environment gives cool new features.

I want to use data access control for making private group goals, perpetual storage for storing account biographies with a history of their achieved and failed goals, which can be used as a reputation indicator.

I hope that with FVM it will be easy to make a super friendly application that not only web3 users but also old fashioned web2 users can use.

###    b) Is this project building with FVM? (Yes or No)

Yes.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. Move from Polygon Network to FVM.
2. Add the possibility of reaching goals that can be verified on-chain with or without oracles (finance, sport).
3. Add the opportunity to participate in contests where people want to achieve the same goal.
4. Add the ability to set goals that can only be seen by certain users (friends, family).
5. Improve UI for mobile users.
6. Add a dashboard for analytics.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions

This is a fresh application that has not been launched at hackathons or any acceleration programms.
  
### Additional questions:

* For each team member(s), please list name, email, Github account, and role in the project.
    * Arthur Sabirzyanov, aloha@kiv1n.ru, @kiv1n, developer.

* How did you learn about our microgrant program?
    * Twitter.

* If your project was created as part of an event or hackathon:
    * No.

**Comment by ErinOCon** [comment]
HI @kiv1n, thank you for your proposal! We are sorry to let you know your project was not selected for a FVM microgrant at this time. Please note we are planning to release another round of grant funding in a few weeks. You are welcome to re-apply with the above or a future FVM project once the new grant funding round has been announced. Until the new founding round opens, no applications will be reviewed or accepted.

If you have already started building your project, we would like to encourage you to join the community of builders on Filecoin Slack and to consider submitting your project to the FVM Community Leaderboard, where the community votes bi-weekly on the top projects to win prizes from a $75k prize pool. Learn more [here](https://network-goods.notion.site/Impact-Evaluators-Builders-Leaderboard-602ea6755b5642e1ad6f9da59a47fa62).
