### ISSUE TITLE
Quidli | 

### ISSUE THREAD

**Issue by Lukerio** [filecoin-project/devgrants#1388]
# Open Grant Proposal: `Quidli`

**Name of Project:** Quidli

**Proposal Category:** `community`

**Proposer:** `Lukerio`

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** Yes

# Project Description
Web3 orgs faced challenges regarding their community growth and retention such as:
- Lack of community engagement
- Lack of community loyalty
- Low community growth and acquisition

Quidli is a micro on-ramp connecting Web 2.0 apps and web3 assets for you to embed crypto rewards and incentives into your collaboration workflows to boost participation and motivation. The app enables you to recognize your top contributors natively in your Slack and or Discord, and is mainly used today by community managers who want to leverage community engagement on social media. Quidli users include the community teams at ConsenSys, the NEAR Foundation, ETHDenver, OrangeDAO, iExec, Flare Network, Concordium, and CUDOS.
Quidli demo on discord: https://j.gifs.com/GRrk23.gif 

## Value
We propose to you to build a light integration of FileCoin to Quidli by adding FIL to our API and hosted app environment. This will enable you to seamlessly distribute FIL as rewards to the top active participants in your community directly in your Slack or Discord.
In addition to helping you internally share FIL within FileCoin, this integration lets us offer FIL to our user base of 1000+ organizations as an option via Quidli’s open token platform.

Through this initial partnership, we can help FileCoin build an awesome community and ecosystem by enabling you to effectively boost community engagement using token incentives. Sharing more tokens with community members can help you to establish a positive alignment flywheel leading to more contributions and ultimately growth towards your main mission and objectives.

## Deliverables
The initial work will be to integrate the FIL  into Quidli’s micro on-ramp environment.

Once completed, FileCoin will be available as an option on:
1. Quidli web app
2. Quidli Slack app
3. Quidli Discord app
4. Any subsequent integrations built by Quidli

Our immediate aims for adding FIL token to quidli ecosystem are:
1. To enable FileCoin to use Quidli internally via Slack and external via Discord.
2. To offer our existing user base FIL token as a micro-incentive option.

## Development Roadmap
1st Milestone: first week
We review the necessary technical documentation (blockchain, smart contracts, token, etc.). If additional docs and or consultation is needed, we’ll contact you to get connected with the appropriate person/team for guidance.

2nd Milestone: second week
Integration should be in place, and we start testing to ensure the new token is functional and usable within our environment. FYI, we will ask you to send some FIL in order to perform these initial tests.

3rd Milestone: third week
Review the integration with FileCoin.
Create & publish PR announcing FIL on Quidli as well as this initial partner with FileCoin.

## Total Budget Requested
We’re asking for $5,000 in FIL to kick off the integration work.

## Maintenance and Upgrade Plans
In the future:
•	We can participate in AMA session to promote Quidli to your Community.
•	We can provide you datas/personalized dashboard and engagement metrics.
•	Telegram integration coming in 2023.

# Team

## Team Members

Justin Ahn, CEO
- Professional: Rocket Internet, KPMG Advisory
- Education: HEC Paris (MBA), University of Maryland, College Park (undergraduate)
- email: justin@quid.li
- Telegram: @justinahn
- Twitter: @ahn_going
- Discord: justinahn.eth#3201
- LinkedIn: [https://www.linkedin.com/in/ahnjustin/](https://www.linkedin.com/in/ahnjustin/)

Guillaume Figielski, CTO
- Professional: Fullstack software developer @ Orange, Peugeot, Airbus
- email: guillaume@quid.li
- Discord: guillaume#1708
- LinkedIn: https://www.linkedin.com/in/guillaume-figielski/

Luke Vignal, Business development
- Professional: ZenDesk, Forrester
- email: luke@quid.li
- Telegram: @Lukeri0
- Twitter: @LukeViignal
- Discord: Lukerio#3260
- LinkedIn: https://www.linkedin.com/in/luke-vignal

## Team code repositories
github.com/quidli

# Additional Information
Contact: Email: luke@quid.li or Telegram: @Lukeri0

Quidli Social media:
•	Website: https://quid.li/ 
•	Youtube: https://www.youtube.com/channel/UCsek4oSa_GipcBfaQQDeSrQ 
•	Linkedin: https://www.linkedin.com/company/quidli/ 
•	Twitter: https://twitter.com/quidliprotocol 
•	Medium: https://medium.com/quidli

**Comment by ErinOCon** [comment]
Hi @Lukerio, unfortunately, we will not be moving forward with a grant at this time. Thank you again for your interest in our grants program!

**Comment by Lukerio** [comment]
Hi,

Thanks for your response, any particular reasons leads to this refusal? Always appreciate feedback, especially when we put efforts and time to created this proposal :-)
