### ISSUE TITLE
Reelspot Media

### ISSUE THREAD

**Issue by jmggaray** [filecoin-project/devgrants#1389]
# Open Grant Proposal: Reelspot Media

**Name of Project:** Reelspot Media

**Proposal Category:** App-dev`

**Proposer:** @jmggaray

**(Optional) Technical Sponsor:** [Piknik](https://www.piknik.com/)

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:**  Yes 

# Project Description

Reelspot is building the first smart workspace solution created for the **Film and TV industry in Latin America** We are building a decentralized audiovisual **content storage and retrieval/Transfer solution** using the the Filecoin network and IPFS. The market niche that we will impact is the audiovisual entertainment industry. 

Our users (audiovisual producers), deal daily with the problem of storage and transfer of audiovisual files during the production and postproduction stages of an audiovisual project. The solutions currently used by the industry to solve this problems of storage (Dropbox, AWS S3, Azure, Harddrives) and transfer (IBM Aspera, WeTransfer) of audiovisual files **(Mp4)**,  **are very expensive, unsafe, and unprofitable for audiovisual projects in Latin America.** 
 
Reelspot partners have worked for more than 30 years in the audiovisual entertainment industry in Latin America. We know which are the biggest needs in the industry and we have the access to the whole networking ecosystem. **Our mission is that audiovisual producers adopt and take the advantages of using decentralized technologies within their daily operation (Cost, Security)** . This will allows our users to have a workflow that simplifies content storage and transfer tasks using decentralized technologies (Filecoin and IPFS), and also  reducing significantly their operational costs.

## Value

We want to position Reelspot as **Latin America’s leading decentralized storage and computing company** using the filecoin network. Our main goal is to grow and expand Filecoin’s network and technology throughout Latin America with our specific use of case. We want to **boost the development and adoption of retreival markets in the filecoin ecosystem**. With the launch of Filecoin Saturn in October of 2022 we want to contribute to the development of apps that allow transferring files within the same ecosystem of decentralized solutions. IPFS usage would increase as would Filecoin. Latin America would turn into a fertile scenario for new businesses; archiving, NFTs marketplaces, transcoding and transferring video, etc..

During our first year of operation we expect to migrate more than 2 Petabytes of audiovisual content to the Filecoin network with potential customers such as: Television Channels, independent audiovisual producers, among others. At the moment we have the backing and migration of potential customers such as [MGE Entertainment](https://mgenetwork.tv/), [Proimagenes Colombia](https://www.proimagenescolombia.com/), [Labzuca](https://labzuca.org/), among other companies dedicated to the production and distribution of audiovisual content in Latin America.

On the other hand Reelspot team is working with **The Starling Lab of the University of Standford,** led by Jonathan Dotan, for the **migration of all data, testimonies of victims and archive images of everything that has happened during the more than 60 years of the internal conflict between the Colombian Government and the armed group (guerrilla) FARC**. Currently, we have the backing of the National Historical Memory Center of Colombia to be able to start bringing data from **one of the longest-running armed conflicts in Latin America into the Filecoin network.**

## Deliverables

A decentralized storage and retrieval B2B solution for media and audiovisual entertainment industry where the user can

1. **Storage Solution**
- Upload, store, manage and download their files.

2. **Transfer and retrieval Solution**
- Transfer their files with other users.

3. **Content Marketplace (B2B)** (FVM)
- Get into a Global Marketplace for Film and Television Content where the user can connect with audiovisual distributors and exhibitors channels (OTT Platforms, TV Channels, Film Festivals etc..) 
- Monetize their content. 

## Development Roadmap

**Milestone 1** (15 days)
Goal: build fundamental data structure and the overall architecture of this project
Description:

**1. Development of two layers of Storage (Sealed and Unseald files)**
- Build two layers of storage (Sealed/Filecoin and Unsealed/ IPFS node)
- Providers basic storage service for _ReelspotOnboardings_

2. **Reelspot Onboardings**
- Multi-user access
- Boost integration

3. **Object store**
- Implements basic data structure, such as user, region, bucket, and object
- Implements API of user authentication
- Connect [boost](https://boost.filecoin.io/) to manage the data onboarding and retrieval on the Filecoin network.
- Sealing as a service

Resource:

**Back-end Engineer**-  (15 days- 360 hours)-$30.000 USD 
**Project Manager** - One day- $1.000 USD 
**Sealing as a Service** - 2 PiBs- $70.000 USD

**Funding: $101.000**

**Milestone 2** (15 days)
**Goal: implement management and transfer of data**

Description:
1. Reelspot transfer
- Implementation of [Konvergence Solution CloudForest (IPFS nodes using Kubernettes)](https://hub.filecoin.io/case-study-konvergence)
- Reference records of data blocks
- Strategy of data pinning services with IPFS

**2. Object store:**
- API of bucket related operations
- API of object manipulation
- API of permission operation

**Resource:**
**Back-end Engineer**-  (15 days- 360 hours)-$30.000 USD 
**Project Manager** - One day- $1000 USD 
**Funding: $31.000 USD*

**Milestone 3 (60 days)
Goal: FVM implementation**

Description: 
**1. Retreival assurance contracts
2. Multi-protocol Storage**
- implements Satellite Nodes connected to the IPFS network in the outer layer of the Reelspot transfer feature
- provides lightweight IPFS gateway services according to user customization

Role | Rate/Hr | HC | Man-Hour | Workday | Price
-- | -- | -- | -- | -- | --
Full-stack Engineer | $50 | 3 | 720 hours | 60 days | $72,000
Project Manager | $100 | 1 | 8 hours | 30 days | $5000

**Milestone 4** (30 days)
**Goal: Frontend and UX/UI** 

Description:

**- Dashboard of storage pool statistics overview
- User interface
- Object Store interface**
> users
> user access operations
> bucket operations
> Permission setting

**Resource:**
**Full Stack Engineer**-  (30 days- 360 hours)-$30.000 USD 
**UI/UX Designer**-(30 days- 360 hours)-$5.000 USD 
**Product Manager** - 10 days- $5.000 USD 
**Project manager** 10 days $4.000 USD
**Funding: $45.000 USD**

**Milestone 5** (6 months)
**Goal: Go to market** 

Description:
**- Assitance in principal audiovisual markets around Latam
- PR Marketing and Awareness Building
- Inbound Marketing
- Paid media**

**Resource:**
**Growth Manager**-  (180 days- 6 months)-$10.000 USD per month
**Marketing Director**-(180 days- 6 months)-$5.000 USD per month
**Sales Director** - (180 days- 6 months) $5.000 USD per month
**UI Designer** (180 days- 6 months) $5.000 USD per month
**Road Costs** $20.000 USD per trip (3)
**Marketing and analytics tools (Hubspot- Intercom- Metabase- Metamap- Amplitude)- $30.000 USD
**Funding: $240.000 USD**

## Total Budget Requested
- **Milestone 1** - $ 101.000 USD
- **Milestone 2** - $ 31.000 USD
- **Milestone 3** - $ 77.000 USD
- **Milestone 4** - $ 45.000 USD
-  **Milestone 5** - $240.000 USD

**Total budget requested- $500.000 USD**

## Maintenance and Upgrade Plans

Maintenance and upgrade plans provided by Reelspot media will include:

- maintenance and bug fixing of this project to ensure that all bugs could be addressed
- upgrade relevant documents as this project progresses
- identify ongoing ways to improve this project and build those features with our sponsors Piknik and Konvergence

# Team

## Team Members
![DSC09047](https://user-images.githubusercontent.com/115324836/217363858-a2113065-6f6a-4970-a17d-0d4361a7786f.JPG)

 [Juan Manuel Gacha Garay CEO- Co-Founder](https://www.linkedin.com/in/juan-manuel-gacha-garay-578911166/)
 [Jorge Andrés Solano Ávila CTO- Co-Founder](https://www.linkedin.com/in/jorge-solano-avila/)

 
[Reelspot website](https://reelspots-landing-site.webflow.io/)
[Reelspot Figma](https://www.figma.com/file/Huh2HIL39QJAtLn93dIEru/UI-Reelspot)

## Relevant Experience: 

We are participantas of the fifth cohort of the Enterprise  Storage Provider Accelerator (ESPA). 

**Juan Manuel**
Juan Manuel has worked in the marketing and startup ecosystem in LatAm for the last 7 years leading areas of Growth, Sales and Marketing. His expertise is mainly based on Fintech, crypto, B2C and B2B software.

Awards and Recognitions

- [Cannes Lions Creative Ecommerce Grand Prix](https://www.adweek.com/creativity/the-big-issue-and-bavaria-ab-inbev-win-cannes-lions-creative-ecommerce-grand-prix/)
- [Littio YC Batch (W23)](https://www.ycombinator.com/companies/littio)

**Jorge Andrés**
Jorge has spent his last 10 years working in Product and Software Engineering. His path led him to Y Combinator in 2022 as Head of Engenieering of Littio leading the product and tech team.

Awards and recognitions

- [Littio YC Batch (W23)](https://www.ycombinator.com/companies/littio)
- [Mi Aguila tech lead](https://apps.apple.com/co/app/mi-%C3%A1guila/id902706774)

## Team code repositories

[Jorge Solano Repositories](https://github.com/jorge-solano-avila?tab=repositories)

# Additional Information
 We learn about the Grants program because we meet the head of community of Filecoin Foundation in the Enterprise Storage Provider Accelerator,

 Mail: jmggaray94@gmail.com

**Comment by ErinOCon** [comment]
Hi @jmggaray, thank you for your proposal and for your patience with our review process. While we will not be moving forward with a grant at this time, I would like to connect you with the Estuary team to determine if there are other support opportunities available. I will be following up with an email shortly. 

Wishing you all the best as you continue to build!
