### ISSUE TITLE
Open Grant Proposal: STFIL - Filecoin Liquid Staking

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/devgrants#1390]
# Open Grant Proposal: `STFIL - Filecoin Liquid Staking`

**Name of Project:** STFIL - Filecoin Liquid Staking

**Proposal Category:** app-dev

**Proposer:** FrogHubMan

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** Yes.

# Project Description

STFIL will build a decentralized liquidity staking platform for Filecoin, and we will deploy this protocol on FVM. It is decentralized, trust-free, and compatible with pledges in Filecoin. STFIL allows users to earn block rewards without locking up assets or maintaining infrastructure.

In the Filecoin network, the Filecoin pledge is an effort to improve the quality of service across the network. It is the cornerstone of a robust, stable, and experiencable distributed storage network that can challenge the centralized storage market. Filecoin's PoSt consensus mechanism is the key to providing stable Storage, which requires storage providers to have more professional hardware equipment, more professional room space, more professional operation and maintenance engineers, more stable power equipment, and high initial investment. This creates a high barrier to entry for Filecoin Storage providers, and typically only companies or teams with resources can participate. Since the pledge needs to buy a large amount of FIL, it means that SP has to accept the fluctuation of Fil price. This is certainly high risk, and it is easy to discourage SP even when Fil prices are low. On the other hand, it is very difficult for the average user to participate in the storage pledge of the Filecoin network. At the moment their only way to participate is to seek partnerships with SP (retail investors may be squeezed out), but such partnerships are centralized, risky and fraught with uncertainty.

STFIL aims to address these pain points. Users (Assets) can deposit their FIL into  STFIL smart contract and receive stFIL, a token pledging FIL, which is used to earn a pledge reward. Storage providers (SP) can pledge their nodes to qualify for a loan to STFIL Smart contracts (the pledge is to prevent SP's evil behavior, and the loan interest is essentially giving away future FIL pledge incentives). Of course, the entry of SP needs to be approved by STFIL DAO, and only qualified SP will be allowed to join. Clearly, users provide idle FIL, SP provides infrastructure and operational capabilities, and this is a win-win opportunity. At the same time, funds deposited by users are controlled by STFIL smart contracts and SP never has direct access to users' assets.

Unlike the pledged FIL, the stFIL token is not subject to a lack of liquidity and it can be transferred at any time. The stFIL token balance will be calculated based on the total amount of FIL pledged, plus incentives and minus any penalties.

STFIL is a more flexible solution than existing ones, allowing users to provide unlimited amounts of FIL and be rewarded with as small a deposit as they want. STFIL only charges a portion of the Filecoin node reward (which is regulated by STFIL DAO), the amount of FIL and STFIL issues pledged by stFIL is fully transparent, auditable, and managed by DAO's multi-signature wallet private key, which is not controlled by any single party. Is a decentralized mobile pledge protocol.
 

## Deliverables

Users can pledge FIL using STFIL
The user looks at the SP list of the settled contract to see the revenue of STFIL
SP can borrow FIL using STFIL

### Aquarius (January 2023)   7,000 USD
1. Launch the STFIL Dao official website (https://www.stfil.io). Improve the introduction of the official website theme, STFIL DAO, working mechanism, token economics, system architecture, etc.
2. Launch STFIL Dao social accounts, Forum,Twitter, Github.
3. The STFIL DAO white paper is released.
Open the STFIL DAO Documentation Center website (https://docs.stfil.io). It covers stFIL economics, contract interpretation, and rule interpretation.
### Bootes (From January to February 2023)  25,000 USD
1. Open the STFIL DAO website (https://voting.stfil.io). It includes an introduction to FDO economics, governance, and proposals.
2. Open the storage provider website (https://sp.stfil.io). It includes introduction of the on-boarding process, loan process, mining income, platform rules and so on.
3. Open the Assets website (https://stake.stfil.io). It contains the annual interest rate of mortgage income, mortgage rules, projects and other introduction.
4. Improve the STFIL DAO website (https://www.stfil.io). Including bounty program, ILS entrance, etc.
### Capricorn (February 2023)    20,000 USD
1. Contract development of STFIL DAO.
2. Test of STFIL DAO contract, STFIL submitted audit, sp audit.
### Draco (March 2023)   10,000 USD
1. Open the STFIL DAO Content audit website (https://audits.stfil.io). It includes STFIL DAO contract audit, SP audit.
2. Deploy the STFIL DAO FVM contract. Officially open all functions.
Open the node information viewing portal of storage provider (SP) website, and obtain mining income portal and other specific operation functions.
3. Open the wallet of the Assets website to log in, stake(FIL exchange stFIL), select SP, pledge stFIL, receive pledge rewards and other specific operations.
4. Improve STFIL DAO Documentation Center website, operation tutorials, API/SDK, etc

## Total Budget Requested

Other development work + contract development work: 62,000 USD
Operation and publicity work：50,000 USD

Set a discount with a final total budget of $100,000

## Maintenance and Upgrade Plans

We will continue to maintain STFIL and all changes and updates will be posted.

# Team

## Team Members

FrogHub, a team focused on blockchain and web3, is committed to the development of fully decentralized web3 application services, with the goal of helping developers quickly switch from web2 to web3. At present, it has provided users with mature decentralized storage solutions, decentralized CDNS, decentralized cloud computing, gateway and other easy-to-use products.

## Team Website

https://www.froghub.io/

## Relevant Experience

At present, the team has more than 20 technical and operational personnel who are deeply engaged in web3.0. They have their own exploration in multiple blockchain ecosystems and have accumulated rich resources and experience.
1. [**Buckets**](https://froghub.io/files.html) is developed by FrogHub based on IPFS to store users' and enterprises' data securely and reliably on the Filecoin network using a simple and concise interface or the industry-standard AWS S3 API.
2. [**Key Management Service (KMS)**](https://github.com/froghub-io/kms) allows you to easily create and control keys for encryption operations, providing encryption and re-storage services for data stored on IPFS.
3. [**IPFS Gateway service**](https://dash.froghub.io/#/) , focused on providing technical and non-technical creators with a fast, easy and reliable way to share content without limit. It does all the heavy lifting for the developer, who can easily bundle the content stored in FrogHub Buckets to IPFS without having to manage his own IPFS node. For NFT creators, it makes it easy to deliver content at scale without any technical experience.
4. [**NFT Art**](https://nft-art.froghub.io/) , a codeless NFT tool trusted by NFT creators. Creators can use this tool to create their own NFT from materials without contract development experience. And publish it to the decentralized network of ETH and Filecoin.
5. [**ICSQLite**](https://github.com/froghub-io/ic-sqlite) is a cloud database on the IC chain developed by us in Dfinity Ecology. It simplifies the storage and retrieval of structured data on the IC, allowing developers to embed it in the Dapp container or even call it remotely. When an application changes the implementation language, the program does not become unusable because it cannot recognize the original data, and ICSQLite solves the problem of multiple applications using the same data.
6. [**Filecoin Cloud C2**](https://github.com/froghub-io/cloudc2-daemon) is designed to provide remote service for zero-knowledge proof algorithms in Filecoin's computing package, serving some regions and providing 3PiB/ day computing power.

## Team code repositories

FrogHub: https://github.com/froghub-io/
STFIL: https://github.com/stfil-io/

# Additional Information
We are active participants in filecoin Ecology, and we have participated in the Open Grants Program. You can find out more about our work at https://www.stfil.io/. If you have any questions, please contact us at contacts@stfil.io.

**Comment by ErinOCon** [comment]
Hi @FroghubMan, thank you for your proposal and for your patience with our review. We know it was an unexpectedly long process! While we will not be proceeding with a grant at this time, please feel welcome to submit a new proposal in the future as staking protocols continue to develop. 

Thank you again for your interest in our grants program. Wishing you the best as you continue to build!
