### ISSUE TITLE
Grant proposal for Project Calico

### ISSUE THREAD

**Issue by 0xIlyas** [filecoin-project/devgrants#1394]
# Open Grant Proposal: `Project Calico`

**Name of Project: Project Calico**

**Proposal Category:** app-dev

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

## Value

Calico is a website and web service that maps crypto wallets to Oauth-able identities in web2 services, and provides services to enable use-cases for those mappings, at both the domain and account level.

Unlock crypto/web3 use-cases for web2 services which do not support web3 technologies yet, primarily for direct rewards in crowdsourced ecosystems. It will use FEVM as the smart contract platform.

## Example 1: StackOverflow

* Donate directly to the wallet of a StackOverflow user who answered a question.
* Smart contract which periodically disburses to all wallets of registered StackOverflow accounts which answered questions for a given tag.

## Example 2: Wikipedia

* A donation wallet + smart contract which disburses contents each month to all registered Wikipedia authors, requiring zero changes to Wikipedia, and is opt-in for authors.
* Donate directly to a Wikipedia author.
* Support all authors in a Wikipedia category.
* Disburse to all authors in a given list who contributed during a specific period of time, such as registrants for a local Wikipedia meetup.

## Deliverables

Web front-end & back-end and smart contracts

## Development Roadmap

- Project & database & api design ($1k)
- Email & Wallet & Stackoverflow Oauth Login/Register ($2k)
- Frontend development, and integrating with backend ($3k)
- Stackoverflow integration in the backend (2k)
- Smart contract development ($3k)
- Smart contract integration with the project ($3k)
- Testing & Feedback ($1k)

## Total Budget Requested

$15k

## Maintenance and Upgrade Plans

We can maintain and upgrade this software over time.

# Team

## Relevant Experience
HTML5, CSS3, JavaScript, React.js, Node.js, Web3.js, and Solidity

## Team code repositories

# Additional Information

**Comment by ErinOCon** [comment]
Hi @0xIlyas, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time, but are wishing you all the best as you continue to build!
