### ISSUE TITLE
Grant proposal for Dojo Guru

### ISSUE THREAD

**Issue by xhitz** [filecoin-project/devgrants#1395]
# Open Grant Proposal: `Dojo Guru`

**Name of Project: Dojo Guru**

**Proposal Category:** `devtools-libraries`

**Proposer:** `https://github.com/xhitz`

**Technical Sponsor: `Brad Holden - brad@protocol.ai` | `Lacey Wisdom - lacey@protocol.ai`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** Please respond with either "Yes"

# Project Description

Unleash the full potential of decentralized technology with Dojo, the ultimate platform for building Dynamic Interactive Assets. With its easy-to-use no-code editor, seamless testing environment, and one-click deployment to any evm-compatible chain, Dojo streamlines the development process and empowers developers to bring their visions to life. Join the revolution and experience the future of NFTs and beyond with Dojo.

## Value

Creating Dynamic Interactive Assets can be a daunting task due to the intricate nature of the process and the limited tools and resources available. This results in decreased efficiency, prolonged timelines, and increased expenses for both developers and organizations. A streamlined and efficient solution is necessary to address these challenges. 

Dojo seeks to set a standard for Dynamic Interactive Assets in the web3 space called DIAS that will be able to work with all Dynamic Interactive Asset projects and if we don't onboard more dynamic projects that use our standards there will be many implementations of different standards for dynamic interactive assets that won't be interoperability.

## Deliverables

We are solving the problem of creating Dynamic interactive assets by introducing "The Dojo Guru" - A developer toolkit. This toolkit offers an easy-to-use, time-saving, environment to launch any type of Dynamic Interactive Assets project that streamlines the process and enables developers to bring their visions to life efficiently and effectively. We have created a standard to render Dynamic Interactive Assets with our no-code solution editor that will bootstrap any project.

In the end, our developer toolkit will provide projects the tools, infrastructure, and our no-code editor for making dynamic interactive assets interoperable with any evm-chain. 

## Development Roadmap

- UIX Frontend development ($3K)
- FEVM DataDao development ($3K)
- DIAS feature integration ($2K)
- Hardhat and Foundry Integrations ($2K)
- Lotus Web3 Storage deal integration ($3K)
- NPM extension development ($5K)
- Custom oracle widget development ($3K)
- Tutorial & Edutainment content creation ($5K)
- Interactive Documentation development (2K$)

## Total Budget Requested

$28k

## Maintenance and Upgrade Plans

We can maintain this software and upgrade it over time.

# Team

## Team Members

Nathan Misner 
https://linkedin.com/in/nathan-misner

Aron Ayuk 
https://www.linkedin.com/in/stereoiii6/

## Relevant Experience

Aron and I created the first no-code editor for creating Dynamic NFTs - `Fractio`
- `Fractio` won Chainlinks hackathon for Spring 2021 
- `Fractio` was a part of the Tachyon Accelerator program
- `Fractio` has created a standard for Dynamic Interactive Assets - DIAS 
- `Fractio` is apart of `Dojo Guru` Development Toolkit to create dynamic interactive asset projects. 
- `Dojo Guru` also won Chainlinks hackathon for fall 2022 

Aron is a full stack engineer and solidity developer
Nathan is a cybersecurity expert and jr solidity developer

## Team code repositories

https://github.com/iii6code/III6Dojo
https://github.com/iii6code/codeBENDER

# Additional Information

We were contacted by niki.gokani@protocol.ai to apply to the program to help our project's development.

**Contact:** `nmisner@codebender.xyz`

https://www.youtube.com/watch?v=8O8aoz_kNII
https://devpost.com/software/dojo-guru-xhr5fl
https://devpost.com/software/deconomy
https://devpost.com/software/dias

**Comment by ErinOCon** [comment]
Hi @xhitz, thank you for your proposal! Can you provide a timeline for each milestone within the development road map? Also, please let us know if you have any specific goals for future user engagement/onboarding.

**Comment by ErinOCon** [comment]
Hi @xhitz, thank you again for your proposal. Unfortunately, we will not be moving forward with a grant. Wishing you all the best as you continue to build!
