### ISSUE TITLE
ShastraOS

### ISSUE THREAD

**Issue by vivekpal1** [filecoin-project/devgrants#1398]
# Open Grant Proposal: ShastraOS

**ShastraOS**

**Proposal Category:** `integration-adoption` 

**Proposer:** `vivekpal1`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?: "Yes"**

# Project Description
### We're creating [ShastraOS](https://shastraos.org/) - a secure, decentralized Linux desktop workstation with strong performance, user experience, and daily decentralized backups.

There are millions of professionals who are still using outdated, centralized desktop operating systems that are insecure and prone to vulnerabilities. In response to this problem, we are developing ShastraOS, a secure, decentralized, and privacy-focused Linux desktop workstation that not only offers powerful performance, but also a smooth user experience and daily decentralized backups on Filecoin for added protection.
<p align="center">
  <img width="80%" height="80%" src="https://raw.githubusercontent.com/ShastraOS/.github/main/profile/assets/banner.png" alt="Banner">
</p>

For users' personalized and decentralized backups, we are building **Astra Protocol**.
Astra Protocol is a decentralized solution for personal backups. It is built on top of Filecoin, providing a secure and decentralized way to store important data. Astra integrates with the popular backup tool Deja-dup on Gnome desktops, making it easy for users to store and retrieve their backups.

We are designing Astra Protocol to be flexible and scalable, making it easy to integrate with other tools and platforms in the future. Additionally, it establishes a standardized approach for creating and storing backups on the Filecoin network, allowing for a seamless user experience.
<p align="center">
  <img width="80%" height="80%" src="https://raw.githubusercontent.com/ShastraOS/.github/main/profile/assets/backups.png" alt="Banner">
</p>

## Value

ShastraOS enhances security and privacy through its decentralized approach to personal backups, which is achieved through the development of the Astra Protocol. The integration with Deja-dup, a popular backup tool for Gnome desktops, makes it simple for users to store and access their data. Astra Protocol is a community-led solution that encourages collaboration and innovation among users and developers. As an open-source solution, Astra offers transparency, versatility, and scalability, granting users complete control over their data and privacy.

Problems with today's Desktops -
- Centralized and paid backup options
- Centralized Packages repositories and mirrors
- Windows OS is not as easy to install
- Unsecured, closed source and lacking in transparency
- Promises about user privacy that are false or exaggerated for marketing purposes

Problems we are solving -
- With Astra Protocol, users can enjoy decentralized backups and seamlessly switch between desktops. While it's still in its early stages, users may experience some ups and downs.
- Verified packages are available from decentralized mirrors, providing a secure source of packages and applications.
- Astra Protocol offers an easy installation process and is portable across different devices.
- Fully open-source and transparent, with enhanced security measures in place.
- Astra Protocol empowers users to fully control their privacy settings and holds themselves accountable for any unethical tracking within their workstations.

## Deliverables

The final deliverable for the Astra Protocol project will be a fully functional decentralized backup solution integrated with Deja-dup on Gnome desktops. The software will provide users with secure and decentralized storage options for their personal data, allowing them to easily store and retrieve their files.

The project specifications include:

- Decentralized backups using the Astra Protocol
- Integration with Deja-dup on Gnome desktops
- User-friendly interface for storing and retrieving data
- Advanced security measures to protect user data
- Community-driven development and collaboration
- Open-source and transparent development process

The software will deliver the following functionality when it is finished:

- Easy and secure storage of personal data
- Flexible and scalable solution for future growth
- Accessible to users on Gnome desktops
- Transparent and auditable codebase for increased security and trust.

The Alpha launch is planned for October or November of this year, and the team is working hard to make sure the product is delivered on time and meets all expectations. While [ShastraOS Preview Release](https://shastraos.org/preview/) is ready with decentralized packages mirrors on IPFS and Filecoin.

#### Milestone 2: ShastraOS Pre Launch
- We have decided to launch ShastraOS Preview Release, with minimal functionalities for testing and R&D purposes.
- [Vivek](https://github.com/vivekpal1) and [Akshat](https://github.com/akshatcoder-hash) are building this since last year.
- For final touches and public launch we will require funding of $3,500
- It will be completed by March

#### Milestone 2:  Astra Protocol MVP Development
- A basic prototype of the Astra Protocol will be developed, including the core functionality for decentralized backups and integration with Deja-dup.
- Two developers will work on this milestone, with one leading the development and the other assisting with coding and testing.
- Funding requirement: $4,000
- Timeframe: The prototype is expected to be completed by April 2023

#### Milestone 3: Astra Protocol -  Core Functionality, UI Testing, and Development
- To make it more secure and usable, testing and final touches for Astra Protocol.
- Will increase the number of developers up to 3
- Funding requirement: $6,000
- Timeframe: The prototype is expected to be completed by July 2023

#### Milestone 4: ShastraOS Alpha Launch and Community Feedback
- The Alpha version of the ShastraOS with Astra Protocol will be launched and feedback will be gathered from the community to further improve the product.
- 2-3 developers will work on this milestone
- Funding requirement: $5,000
- Timeframe: The prototype is expected to be completed by August 2023

## Total Budget Requested

Here is a budget breakdown for the requested **$18,500** funding:

**Development costs** - $9,500

**Testing and Quality Assurance** - $4,500

**Marketing and Outreach** - $2,700

**Miscellaneous Expenses** - $1,800

This budget breakdown is estimated based on the current scope and timeline of the project. The actual costs may vary slightly depending on the final requirements and the pace of development. However, we believe that this budget will cover all the necessary expenses for the successful completion of the project.

## Maintenance and Upgrade Plans

As an Open Source project, ShastraOS is maintained by a dedicated community of developers who regularly contribute to its development and improvement. Our team is committed to continuously updating and upgrading the software to meet the changing needs of our users. To achieve this, we have implemented a robust development process that includes regular code reviews, bug fixing, and feature updates.

In the long term, our plan is to establish a sustainable development model that provides ongoing support and resources to our community of developers. This may include funding initiatives, community engagement programs, and regular workshops and training sessions to help contributors enhance their skills and knowledge. We believe that a vibrant and active community is critical to the success and longevity of ShastraOS, and we are committed to fostering its growth and development for many years to come.

# Team

## Team Members

- **Akshat Sharma**
- **Vivek Pal**

## Team Member LinkedIn Profiles

- Akshat - https://www.linkedin.com/in/akshatcoder/
- Vivek - https://www.linkedin.com/in/vivekpal1/

## Team Website

https://shastraos.org/team/

## Relevant Experience
We both have a passion for Open Source and Linux technology, contributing to various Open Source projects. We have been active participants in Web3 Hackathons and communities organized by ETHGlobal, Devpost, and Devfolio. Akshat also established the [FOSSCU]()https://fosscu.org Open Source community, which has a growing number of active members who support open-source projects, empower women in tech, and guide early-stage students. In 2022, we decided to build our own Linux Distro, ShastraOS, a decentralized desktop workstation. Now, we are seeking Filecoin grants to further enhance its capabilities by offering decentralized backups.

**Our Portfolio**
- https://vivekpal.in/
- https://akshat.shastraos.co/

## Team code repositories
- https://gitlab.com/shastraos
- https://github.com/ShastraOS
- https://github.com/vivekpal1?tab=repositories
- https://github.com/akshatcoder-hash?tab=repositories

# Additional Information
We came here from the Filecoin website.

**Our Mails**
- ShastraOS Team  - info@shastraos.org
- Vivek Pal - vivek@shastraos.com
- Akshat Sharma - akshat@shastraos.com

**Our Telegram**
- Akshat - https://t.me/vivekpal0x
- Vivek - https://t.me/akshatsharma23

**Our Twitter**
- ShastraOS  - https://twitter.com/ShastraOS
- Vivek Pal - https://twitter.com/vivekpal0x
- Akshat Sharma - https://twitter.com/akshatwts

**Comment by ErinOCon** [comment]
Hi @vivekpal1, thank you for your proposal! Can you describe how this project uses Filecoin?

**Comment by vivekpal1** [comment]
> Hi @vivekpal1, thank you for your proposal! Can you describe how this project uses Filecoin?

## How ShastraOS uses filecoin
ShastraOS uses Filecoin for two main purposes, ShastraRepo and Astra Backups.

### ShastraRepo
ShastraOS uses Filecoin to power ShastraRepo, a decentralized software package repository, and mirror for ShastraOS.
ShastraRepo uses Filecoin as its decentralized storage backend. When a user requests a package, ShastraRepo first determines which node in the network is closest to the user in terms of latency and bandwidth. This is typically done using a CDN.
ShastraRepo queries the Filecoin network to locate the package. This involves searching for the package's CID on Filecoin or IPFS. The blockchain provides a decentralized and immutable record of all storage deals and retrieval deals that have been made, so ShastraRepo can be confident that the package is available for retrieval.
If the package is found on the Filecoin network, ShastraRepo initiates a retrieval deal with the closest node. This involves negotiating a price for the retrieval of the package and transferring the appropriate amount of Filecoin from the user's account to the node's account. Once the transfer is complete, the node retrieves the package from its storage on the Filecoin network and sends it to the user.

Gitlab - https://gitlab.com/shastraos/shastrarepo

> Currently, this is in the development phase, but we have already shipped the IPFS mirrors of ShastraRepo.

### Astra Backups
How Astra Backups on ShastraOS works:

- The user data that needs to be backed up is encrypted using a strong encryption algorithm. Currently, Astra uses GNU Privacy Guard (GPG). GPG is an open-source implementation of the OpenPGP encryption standard, which provides end-to-end encryption for email messages and other types of data. Deja-Dup Backups uses GPG encryption to encrypt backup files before storing them on IPFS, which helps ensure the privacy and security of user data.

- Astra Backups can be set up to create regular backups of user data. This ensures that the latest version of the data is always backed up to the Filecoin network.

- In case of data loss or corruption, the user can retrieve their backed-up data from the Filecoin network. The data is retrieved and decrypted and can be restored to its original location.

#### Integration of Deja-Dup Backups
A user-friendly backup tool for Linux-based operating systems, to manage and schedule backups of user data. When a backup is initiated, Deja-Dup creates an encrypted archive of the user's data and stores it locally on the user's device. Astra Backups then utilizes IPFS to add the encrypted archive to the network, which splits the archive into small chunks and distributes them across the network. Additionally, Astra Backups uses Filecoin to store the encrypted archive on the decentralized Filecoin network, ensuring long-term and reliable storage for the user's data. To retrieve their data, users can simply request it through Astra Backups.

> Astra Backups is in Research and Development stage, the prototype can be delivered by July 2023.

Gitlab - https://gitlab.com/shastraos/astra

## Astra Drop
Astra Drop is a decentralized file-sharing solution that allows users to quickly and easily share files with others over a local network. The system is based on the libp2p networking protocol, which ensures that files are transferred quickly and securely between devices.

<img src="https://user-images.githubusercontent.com/88021457/231962707-b5f84b61-1719-48de-8544-6ef33c887269.png" alt="image" width="50%" height="50%">


Astra Drop is a frontend built on top of PeerPy, written in Python for file sharing on local networks, which also uses libp2p. This enables Astra Drop to offer fast and efficient file-sharing capabilities while ensuring that data remains private and secure.

Astra Drop provides a seamless and reliable way for users to share files with each other on public networks without the need for centralized servers or third-party platforms. This makes Astra Drop an ideal solution for users who want to keep their data private and secure while still enjoying the convenience of easy file sharing.
> It is also in Research and Development stage
