### ISSUE TITLE
Open Grant Proposal: Quest Chains

### ISSUE THREAD

**Issue by vidvidvid** [filecoin-project/devgrants#1399]
# Open Grant Proposal: `Quest Chains`

**Name of Project:** `Quest Chains`

**Proposal Category:** `app-dev`

**Proposer:** `vidvidvid`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

As we work towards being the leading gamified Web3 onboarding platform, Quest Chains is dedicated to providing the ultimate structure and gamification experience for task management. We are constantly improving and expanding our platform to ensure it remains the top choice for DAO onboarding.

We are enhancing the gamification features and flexibility of Quest Chains by adding auto-accepted submissions and optional quests, laying the foundation for an XP system. Our platform's explorer page is also undergoing a major upgrade with the addition of filters, sorting mechanisms, a category field, and a refined UI. The most popular quest chains will be showcased in a "featured" or "trending" section. We also want to make modifications of our smart contracts to allow better accessibility of the app's features. This will be explained in detail in the `Deliverables` section.

Our goal is to establish Quest Chains as the go-to tool for DAO onboarding in the Ethereum ecosystem. We have already completed two integrations with our SDK (three if you count ourselves) and are in talks with Urbanika for another integration. We will continue to increase our presence and make Quest Chains the best option.

## Value

Benefits of getting it right:

- it would provide a comprehensive and intuitive onboarding tool for DAOs with a better UI, UX and the essential XP system, which will make joining a DAO more accessible and engaging
- this will enhance user experience and potentially increase user retention

The risks of not getting this right:

- users may have difficulty understanding how to join a DAO, leading them to abandon the process altogether
- users may become frustrated with the process if it feels too cumbersome or complex

The risks that will make executing this project difficult:

- we may not be able to correctly anticipate user needs, leading to a platform that does not meet their needs
- if the platform is not intuitive and well-designed, users may have difficulty understanding how to use it
- we may not have the necessary resources to build the platform quickly.

### 1. Gamification

Our focus is make the best DAO onboarding tool, but keep it flexible enough to successfully use it for anything that can be abstracted into a chain of quests. We currently support only 1 type of quests - quests that need their submissions by questers to be reviewed by another human and approved before the users can mint the NFT. We want to expand this functionality to additional 2 types of quests:

- quests with submissions that get auto-accepted and therefore serve as something similar as POAP
- optional quests. meaning that one can submit a proof, but it will not be necessarily reviewed and it will not count towards completion of the quest chain

This will increase the flexibility of quest chain creators in curating their onboarding story and expand the potential use cases. On top of that it will prepare a foundation for the implementation of the XP system, which is the last missing piece of the whole `gamified onboarding platform` puzzle, since the gamification will not be complete without it. We will define the XP awarding system, propose the implied UX and UI changes and implement all of it.

### 2. Quest Chains Explorer

The past month has been a phenomenal success for our community and app.  Our statistics show a significant increase in usage, with `26` new quest chains created, a surge in our discord community from `50` to `1450` users, and a whopping `300` new Twitter followers.
<img width="1107" alt="Screenshot 2023-02-03 at 11 24 56" src="https://user-images.githubusercontent.com/35112939/217291614-4d7a4dd0-8399-4338-8b91-2be05ec776da.png">

This surge in usage, combined with the positive feedback from our users, has strengthened our aim to improve the Quest Chains' explorer page. We are firmly committed to providing users with the most comprehensive and efficient search experience possible. Currently, this is possible just by searching for the title/description keyword or scrolling through all of the created quest chains: [https://questchains.xyz/explore](https://questchains.xyz/explore).

We will implement various filters and sorting mechanisms, elevate quest chains with a categorization system, and enhance the overall UI of the page. The goal is to showcase the most popular quest chains in a prominently featured or trending section, making it easier than ever for users to find what they're looking for.

### 3. Market research and integrations

We want Quest Chains to become the go-to tool for DAO onboarding. Since our [first grant proposal](https://github.com/filecoin-project/devgrants/issues/645), we have done [another integration](https://metagame.wtf/learn/thegreathouses) with our SDK and are currently talking with [Urbanika](https://urbanika.my.canva.site/), to create an integration with them as well on top of another integration with MetaGame. PageDAO [created about 6 quest chains](https://medium.com/pagedao-magazine/earn-nfts-with-pagedao-questchains-dfe9229d7d38) for their needs and purposes.
Although we are experiencing nice organic growth, we would like to further spread the awareness of the existence of Quest Chains throughout the Ethereum ecosystem to both, make life easier for our potential users and help us with clearing out the user needs. To do that we'll need to conduct thorough market research, improve our documentation, engage our community, increase our twitter presence and talk at podcasts.

### 4. Accessibility

With gain of traction, we want to simplify the UX of questers and quest givers while simultaneously layout the groundwork for future fun upgrades. With that in mind, we want to introduce 2 major changes to our contracts. 

1. Change our NFT contracts from ERC-1155 to EIP-4973 or EIP-721 in order to support upgradability of minted NFTs.
2. Support funding of quest chains, so that questers won’t have to pay fees for interacting with quests.

The proposed changes will attract more users, since the quest chains will become completely free to use & amplify the gamification aspect, which is proven to increase user engagement and retention.

### 1. Quest Chains Explorer: March 1st, 5000$

```
Deliverables:
- Filters and sorting mechanism
- Category field for quest chains
- UI/UX improvements
- Featured/Trending section
```

**Dan** - Full-Stack

**Vid** - FE

**Dave** - UX & UI

### 2. Gamification: May 1st, 10.000$

```
Deliverables:
- Expansion of quest types
- Implementation of XP system
- UX and UI changes
- Leaderboard
```

**Dan** - Full-Stack

**Parv** - Full-Stack

**Vid** - FE

**Dave** - UX & UI

### 3. Market research and integrations: May, 1st 5.000$

```
- Thorough market research
- SDK documentation
- 5 additional integrations
- Talk at 3 podcasts
```

**Vid** - FE

**Tony** - Writer

**Evgeniy** - Community manager

**Dan** - Full-Stack

### 4. Accessibility: June, 1st 6.000$

```
- Change our NFT contracts from ERC-1155 to EIP-4973 or EIP-721
	-> Implement an example of an upgradable NFT
- Support funding of quest chains
	-> Implement necessary UI changes
```

**Vid** - FE

**Dan** - Full-Stack

**Parv** - Full-Stack

**Dave** - UX & UI

## Total Budget Requested

26.000$

We plan to spend all of it to fund the development of the application & conduct market research and consequent marketing.

## Maintenance and Upgrade Plans

After we are done with the batch of proposed changes, we will 

- find ways to optimise the performance of the application
- continue doing user experience research by collecting their feedback and communicating with them
- continue marketing
- further develop the gamification aspect
- look for more opportunities for integrations & use cases of DAOs

# Team

## Team Members

**Dan**: Full-Stack, [GitHub](https://github.com/dan13ram), [Website](https://dan13ram.com/)

**Dave**: Designer, [LinkedIn](https://www.linkedin.com/in/davortomic)

**Beti**: Artist & Designer, [Portfolio](https://www.behance.net/betifrim)

**Vid**: Front-End, [GitHub](https://github.com/vidvidvid), [Linkedin](https://www.linkedin.com/in/vid-topolovec/)

**Parv**: Full-Stack, [GitHub](https://github.com/parv3213), [Linkedin](https://www.linkedin.com/in/parv3213/)

**Tony**: Writer, [Twitter](https://twitter.com/anthonyihediwa1)

**Evgeniy**: Community Manager, [Twitter](https://twitter.com/LizardResearch)

## Team Website

[Quest Chains](https://questchains.xyz/)

## Relevant Experience

- **Dave** is a seasoned UX/UI designer who is extremely passionate about his work (in fact we are all very passionate about what we do 🙂), he is very patient and knowledgeable.
- **Dan** has dedicated his life to working as a full stack web3 developer in DAOs, which he believes are the future of work. He's also an active member of Raid Guild.
- **Beti** is a graphic design student who's in love with 3D and digital art in general.
- **Vid** has continuously contributed to various blockchain projects for the past year while working professionally as a FE developer for the past 5 years.

We all have met in MG and make a great team.

In the past couple of months 3 more people joined to strengthen our development:

- **Parv** is a Solidity dev who has vast experience in writing and auditing smart contracts. Recently he started implementing also FE features.
- **Tony** is a passionate writer, who has experience in producing high quality documentations and articles.
- **Evgeniy** is a 22 years old crypto enthusiast, who had been searching for best investment opportunities since 2017, has graduated with a degree of management in web business and is a member of several DAOs.

## Team code repositories

https://github.com/quest-chains/

# Additional Information

We were aware of your granting system since the first [grant](https://github.com/filecoin-project/devgrants/issues/645) we wrote in June, 2022.

Email: weetopol@gmail.com

We are grateful that the Techstars Filecoin accelerator team has expressed interest in our project, but as I'm sure you're aware, their program has been moved to 2024. As our team has grown, and our ambitions have become more ambitious, we are in need of additional funding to dedicate more of our time to further develop our project. We would be immensely appreciative if you could continue to support our outlined work by approving this grant and/or connecting us with a skilled business development professional to help us monetize our product. Thank you for your consideration.

**Comment by ErinOCon** [comment]
Hi @vidvidvid, thank you for your proposal. We will not be moving forward with a grant at this time, but you may have an interest in checking out other [accelerator options](https://ecosystem-wg.notion.site/Protocol-Labs-Accelerator-Program-d45d8792a7d544eca9beb7d3e3d3b05d). I know you mentioned the Techstars timeline wasn't a good fit for your project, but there may be other accelerator opportunities that line up well!
