### ISSUE TITLE
RFP: go-filecoin maintainership

### ISSUE THREAD

**Issue by momack2** [filecoin-project/devgrants#140]
We are looking for teams interested in stewarding and improving [go-filecoin](http://github.com/filecoin-project/go-filecoin), one of the [4 current Filecoin implementations](https://filecoin.io/blog/announcing-filecoin-implementations-in-rust-and-c++/). go-filecoin is nearly feature-complete, so you will be starting from a very strong foundation. lotus and go-filecoin achieved interoperability in April 2020, but go-filecoin will need to be updated to bring it back to an interoperable state and to feature-completeness for mainnet launch. 

As the implementation graduates to community maintainership, we are looking for community members able to actively maintain compatibility with the other Filecoin implementations, run and optimize this implementation in live deployments, and ensure go-filecoin continues to be a fully-functional implementation. This is a great opportunity for teams to become strong stakeholders and stewards in the Filecoin ecosystem by building their expertise and engagement. This grant builds on the [previous RFP for protocol implementation teams](https://github.com/filecoin-project/devgrants/issues/43) (see the [full grant specification](https://docs.google.com/document/d/1L7ZZOC4cms3SZNyx7u1Hr0H_XFDUI8FYA2W8dXWBGsY/edit) for details).

In particular, we’re looking for teams that are interested in differentiating the go-filecoin implementation from other Filecoin implementations to drive adoption. Some examples include:
- Making the implementation highly optimized for mining operations
- Building services around the core go-filecoin implementation, e.g. hosting go-filecoin nodes as a service
- Involving the greater Filecoin community in completing the implementation
- We’d love to hear any other direction you think is compelling as well

Note that while this RFP description does not follow the same template as our others, submitted proposals should follow the application format described [here](https://github.com/filecoin-project/devgrants#submit-a-proposal-for-an-rfp).

Please drop any questions below!

**Comment by taoshengshi** [comment]
I, on behalf of IPFSForce Community with some key contributors in Filecoin mining pool development, would like to apply for & take the ownership of go-filecoin maintainership. 
 
Our team members have relevant experience and background on go-filecoin implementation. We have learned the go-filecoin project for building mining pool,fixing bug,customizing the modules before lotus project lanched. Based on the knowledge we got from lotus and mining pool till now, we have more ideas which could put into another alternative implementation.

More over, we also want to motivated community members & talents from IPFSForce community where we have been holding tech meetups for 2+ years. and we also have many trainees in Shanghai protoschool and Chengdu protoschool.

We are very glad to contibute more to go-filecoin and deliver another software & product to community and help to verify the protocol security.

please let me know if any other process need to follow.

thanks!

Contact: 
taoshengshi01@gmail.com @IPFSFORCE researcher
steven004@gmail.com @IPFSFORCE CTO

**Comment by momack2** [comment]
That’s great! Thanks so much for applying, @taoshengshi! It’d be great to get a formal application following the guidelines here: https://github.com/filecoin-project/devgrants#submit-a-proposal-for-an-rfp

I’ll also start an email thread for us to discuss more. Great to have you in this community!

**Comment by eshon** [comment]
@taoshengshi - What is meant by mining pool?

I thought mining pool refers to like SparkPool, AntPool, etc. with individual miners sharing their compute with the pool for a share of block rewards. For Filecoin, what would it mean?

**Comment by taoshengshi** [comment]
@eshon here 'mining pool' is somehow ambiguity, I mean big miner or cluster.  But we are very interested in the mining pool refers to like SparkPool, AntPool, etc. and I remember that go-filecoin had initial discussion on that.

@momack2 will apply it following the guidelines.

**Comment by banishee** [comment]
Is there more detailed plan?

**Comment by momack2** [comment]
Applied [here](https://github.com/filecoin-project/devgrants/pull/171) and accepted.
