### ISSUE TITLE
Collector — Mobile Wallet Client

### ISSUE THREAD

**Issue by depatchedmode** [filecoin-project/devgrants#1402]
# Open Grant Proposal: `Collector — Mobile Wallet Client`

**Name of Project:** Collector — Mobile Wallet Client

**Proposal Category:** `devtools-libraries`

**Proposer:** Ryan Betts

**Technical Sponsor:** Dietrich Ayala

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

Very few wallet clients natively support Filecoin right now. 

Those that do, don't take full advantage of Filecoin's capabilities. In turn, this serves to constrain growth of Filecoin's app ecosystem, and active FIL accounts. It's a chicken-egg problem: who moves first? Filecoin apps need wallet client support, but wallet clients only put that work in to meet customer demand.

We intend to demonstrate how Filecoin integration can add capabilities to a wallet client that strengthen its consumer appeal, independent of external demand: paid backup of NFTs, and other on & off-chain data. We'll also outfit developers of wallet clients with open source libraries to make Filecoin integration simpler.

Collector will be a production-ready reference wallet client implementation with unique file storage capabilities that battle tests these open-source libraries, documents associated UX best practices, and enables swifter adoption of the Filecoin network by wallet client teams.

![image](https://user-images.githubusercontent.com/84613835/218206091-4076698e-5da0-47f5-be9a-3c9901673e85.png)

## Value

Collector will bring value to the Filecoin network by:

1. **Simplifying Adoption of Filecoin by Wallet Clients:** Our open source libraries will open a simpler path for wallet clients to provision their users with Filecoin account, take advantage of Filecoin's unique storage capabilities, and support Filecoin app connectivity & signing flows.
2. **Improving wallet client UX:** Demonstrate how account abstraction & UCAN support can improve wallet client UX by providing individuals with greater control (eg. spending limits, fewer round trips to the wallet client for signing) and 
3. **Demonstrating Filecoin support as a competitive advantage**: Showcase unique capabilities that Filecoin can bring to wallet clients to expand their functionality, making them more desirable than wallet clients and improve UX
4. **Growing active FIL wallets**: We intend for Collector to be valuable enough to a general audience that it will grow the number of active wallets on the Filecoin network. The final launch 

The primary risks facing us are external dependencies on the following:
1. **Apple App store approval:** we're aware that wallet clients can face difficulties during the App Store approval process. This can be mitigated by falling back to a longer beta period of provisioning to devices via Testflight.
2. **FEVM Account Abstraction support:** timelines for Account Abstraction support aren't currently set in stone. We should be able to fall back to a standard contract account with Passkey signing support that can be migrated at a future date (is this actually possible? not sure)
3. **Wallet Connect support:** our ideal flow for app connectivity and signing would be to leverage Wallet Connect to support signing from our mobile wallet to the user's preferred mobile browser, and also any desktop browsers they use on other devices. Wallet Connect does not yet support the Filecoin network. We are confident it can and will be put in place within our launch timeline. As a fallback we can emulate the Metamask API through an in-app browser.

The worst case scenario is the development of the app will produce a tech demo that pushes best practices and the state of the art on Filecoin forward, but Collector may fail as a product.

## Deliverables

1. **UX flows and principles:** During the process of designing and iterating on the UX of our mobile client, we will be producing a variety of design specs, clickable prototypes, research finding and guiding principles. The source Figma files and any other documentation will be shared publicly for the benefit of other teams.
2. **Libraries** implemented in React Native for FIL FEVM with UCAN and WNFS support, open-sourced
3. **End to end app store deployed experience of v0.1 of Collector:** we will ship a working, production-ready version of the app to both iOS's App Store and Android's Google Play.
4. **Contract deployed on FEVM** to provision Passkey backed contract accounts, leveraging the Account Abstraction built-in actor.

### Milestone 1: Functional Prototype 

R&D phase to produce a basic functional wallet client, and better understand the current limits of the Filecoin ecosystem.

**Dates:** Mar 1 – Apr 30
**Team:** 1 Designer, 1 Dev
**Cost:** $80,000
**Outputs:** 

* Wallet client functional prototype capable of:
    * launching on iOS & Android
    * connecting to Filecoin Wallaby testnet
    * create a single contract account from a Passkey
    * sign out from an account in the app, and sign back in again using your Passkey
    * signing messages on behalf of that contract account
    * connecting to any Filecoin app deployed on Wallaby testnet
    * sending & receiving tFil
    * reviewing tFIL balance 
    * listing ERC-20, ERC-721 & ERC-1155 assets on the Filecoin network
    * backing up an image to the Filecoin network, and displaying the list of backed up files in the app
    * viewing any backed up file through an IPFS gateway
* Prototype of accounts contract deployed to Wallaby testnet
* UX Principles, to guide the design process through Milestones 2 & 3.

### Milestone 2: UX Iteration 1 

**Dates:** May 1 – Jun 30
**Team:** 1 Designer, 1 Dev
**Cost:** $80,000
**Outputs:** 

* SiWE & ReCap signing modals
* Account recovery on a fresh device
* Ability to group collected items into boards
* Ability to attest control of an Ethereum account
* Backup all ERC-721 and ERC-1155 metadata and assets from that Ethereum account
* User testing results, to inform next design iteration and validity of initial UX Principles

### Milestone 3: UX Iteration 2 

**Dates:** Jul 1 – Aug 31
**Team:** 1 Designer, 1 Dev
**Cost:** $80,000
**Outputs:** 

* Revisions to the UX of the app, based on learnings from user testing
* Additional rounds of user testing
* Continued development and refinement to supporting libraries
* Deploy accounts contract to mainnet
* Network switching between Filecoin's testnets and mainnet

### Milestone 4: Launch Prep & Documentation

Get everything ready for the production launch of Collector.

**Dates:** Sep 1 – Sep 30
**Team:** 1 Designer, 1 Dev
**Cost:** $40,000
**Outputs:** 

* Documentation for libraries
* Prepare launch assets for app stores
* Landing page for Collector marketing site
* Customer focused blog post about the capabilities of Collector
* Dev focused blog post about the experience of developing Collector
* Setup of support channel (dedicated area w/in Fission Discord)
* Setup of social handles (Mastodon, Twitter, etc)

### Milestone n: Community Maintenance Phase

**Dates:** Sep 2022 – Sep 2023
**Team:** Fission Organization
**Outputs:** 

* Deploy Community Funding Reserves (10% of overall grant) to community dev teams in pursuit of maintaining, upgrading and extending Collector & the supporting libraries and contracts.
* A blog post summarizing the learnings from the deployment of the Community Funding Reserves

## Total Budget Requested

Milestone 1: $80,000
Milestone 2: $80,000
Milestone 3: $80,000
Milestone 4: $40,000
Total: $280,000

Dedicated to development: $252,000
Dedicated to Milestone n: $28,000 (10% reserved from the total)

### Support of Collector:

If Collector succeeds in attracting active use, we intend to continue to maintain and evolve it as an open-source wallet client. We would hope to cultivate an active community of contributors beyond just Fission employees.

### Support of the core libraries: 

As mentioned above, our team will retain 10% of the overall grant in a maintenance fund to be allocated over the 12 months following the final launch milestone. These funds will be targeted at supporting development efforts from the community that seek to maintain or extend Collector, the account contract and the supporting libraries. 

Management and deployment of the funds will be done as a part of Fission's standard operations. As such, no additional budget has been requested for Fission's efforts during this deployment phase.

# Team

## Team Members

+ Ryan Betts: Project lead & UX designer
+ Jeff Griffiths: Product management
+ Andy Vivash: Mobile app & smart contract development

## Team code repositories

* https://github.com/fission-codes/
* https://github.com/webnative-examples/

# Additional Information

The team can be contacted through ryan@fission.codes

**Comment by depatchedmode** [comment]
Hello! Looks like there are quite a few grants, so I'm sure y'all are busy, but was just wondering what the typical timeline / next steps are for hearing about these proposals?

**Comment by ErinOCon** [comment]
Hi @depatchedmode, yes, there certainly are quite a few grant submissions! In light of the macroeconomic climate, we are currently in the process of re-evaluating our budget and priorities for this fiscal year. Please feel welcome to check back in if you do not receive an update in the next few weeks. 

We appreciate your patience and will follow up as soon as we have more information!

**Comment by depatchedmode** [comment]
Hey @ErinOCon — just checking in to see if there's any progress on your front, or anything we could focus on clarifying on our end. Thanks!

**Comment by ErinOCon** [comment]
Hi @depatchedmode, thank you for all of your patience with our review.  I know it has been a considerable amount of time since we have provided an update for this proposal.  

Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!

**Comment by depatchedmode** [comment]
@ErinOCon Thanks for the update. Are you able to provide any reasons for why the proposal was rejected?
