### ISSUE TITLE
PeerStreams(Decentralized video streaming and storage application)

### ISSUE THREAD

**Issue by aeyshubh** [filecoin-project/devgrants#1407]
# Open Grant Proposal: `PeerStreams(Decentralized video streaming and storage application)`

**Name of Project:**`PeerStreams`

**Proposal Category:** `Webapp-dev`

**Proposer:** `shxb7`

**Deployed Site : https://www.peerstreams.tv/**

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** `Yes`

**We have started building this project after we met the FVM team at Ethindia'22 .**
# Project Description
**3 sentence description for your proposal.**
- Twitch+Discord+Youtube+Buy Me a Coffee = PeerStreams 
- We Strawhats are building the new way of streaming video content without Ads and better monetization opportunities for the creator.We follow a Pay as you go model in which user can watch content with a money stream according to the flowrate set by the streamer if he/she/they decides to make it payable and many more exciting features which will create a ultimate OG Video streaming platform .
- Our platform promotes true ownership of data using Ipfs ,Filecoin Virtual Machine and Nfts.
- User can Video Chat,send donations ,receive notifications from the app itself.

**The problem we are solving.** 

- Recently on youtube the biggest crypto channel called “Bankless” was banned and disappeared with which the hard work and hundreds of hours of content was gone like huff which is not fair and this is not a single case there are channels which are getting strikes and getting banned without any major reasons .
- For seeing a video content of 5 mins ,i have to watch two adds of 30 seconds which is becoming frustrating day by day in youtube .
- Generally streamers have their discord channels for engaging with their users for which they have to go back and forth for sending notifications about their streams and interact with the audience.
- the ownership of the content is not in the creator's hand and is at the risk of being de-platformed anytime.

## Value
**The solution we are proposing and how it will have a positive impact on the Filecoin ecosystem.** 

- As the number of streamer increases on our platform more content will be uploaded on IPFS and more people will be adding their data on IPFS network.
- After a livestream a streamer can mint his videos as Nft on IPFS network which will remain on the network forever.
- Streamers can upload their Thumbnails for the video on IPFS for easy and fast retrieval.
- We are using a solidity smart contract to store data about minted videos by a streamer and thumbnails uploaded by him/her.
- The smart contract will be deployed on Filecoin Hyperspace testnet for data retrivals and data addition.
- Futher we could also motivate the streamer to select a storage provider by himself on the Filecoin ecosystem of which the computation will be done through Filecoin virtual machine (FVM)
- This will also promote the true owner of content by minting his videos as Nfts on our platform on IPFS network.
- This project will also give rise to new users in Filecoin ecosystem and storage network.

**There is a very less risk of getting things wrong as we are confident on our skills and are determined for our project's success.** 

 # Project flow

**Streamer**
![](https://res.cloudinary.com/dm6aa7jlg/image/upload/v1674567483/Streamer_Flow_Horizontal_MConverter.eu_ojggix.jpg)

**User**
![](https://res.cloudinary.com/dm6aa7jlg/image/upload/v1674567671/User_Flow_Horizontal.drawio_get4gw.png)

## 🔗 Links
Project video demo : https://youtu.be/H3WPV93_5uo

## Deliverables
**Milestone 1 :** 
- Streamer can add thumbnails for their video which will be uploaded on IPFS and the Cids will be stored in the smart contract on Filecoin Virtual Machine.
- Viewer can donate to streamer using FIL tokens through a smart contract deployed on Filecoin Hyperspace testnet.

**Milestone 2:**
- Streamer can do Livestream and after stream ends he/she can mint that livestream on IPFS and the Cids will be stored on Smart contract which is deployed on Filecoin Hyperspace.

**Milestone 3:**
- Streamer can select various storage deals and storage providers for storing his livestreams and thumbnails ,we can also automate this thing in solidity by selecting the best storage deal or auto upgrading the storage deal after a certain time periods.

## Development Roadmap

**Milestone 1(25 Feb to 10 March)($2500)**
- I will be working on the solidity smart contract for storing cid and keeping a account of tokens donated by the users. 
- @gunner26735 will be working on the IPFS Storage
- @phovious-14 will be working on the UI of the website.

**Milestone 2(11 March to 30 March)($2750)**
- I will be working on the a smartcontract to mint those livestreams as Nfts and will be researching about the storage deals.
- Further user can watch past livestreams in form of minted Nft videos by the streamers.
- @gunner26735 will be working on the process of storing the livestreams on IPFS.
- @phovious-14 will be working on the UI of the website.

**Milestone 3(1 April to 25 April)($2750)**
- I will be working on the storage deal smart contract for the streamer to get best deal for storing it's data.
- @gunner26735 will be integrating the webapp and will be running the tests on the beta version.
- @phovious-14 will be working on the UI of the website and will be making the final changes to the website.

## Total Budget Requested
- Total Budget = $8,000
- 1 Smart contract developer($2,000),1 backend Engineer($2,200),1 Frontend Engineer($2,300) will be working on this project for the duration of 2.5 months and in bracket is the amount they will be receiving as base salaries for their work.
- $500 for publicity stunts to gain attention of more users on twitter for other platform.

## Maintenance and Upgrade Plans
- We won't be using the whole budget in salaries , we have kept a buffer of $1,000 in case of emergency fund.

## Shubham Patel (Project manager and protocol integration lead 🧑‍💼) 
- I like experimenting with different protocols and integrating it with our project for betterment of the User Experience.

## Siddharth Shukla (Backend development of API's 🦾)[@gunner26735]
- As having a logically strong background in Backend development which help me to have the stable & sustainable backend-management of this application

## Krishn Panchal( Frontend Wiz 🧑‍💻)[@phovious-14]
- Expert in UI/UX and developed interactive front-end, handles integration of various protocols and backend . 

## Team Member LinkedIn Profiles

- Team Member 1 : https://www.linkedin.com/in/devshub21/   
- Team Member 1 Twitter : https://twitter.com/shxb7_
- Team Member 2 : https://www.linkedin.com/in/krishn-panchal-665388201/
- Team Member 3 : https://www.linkedin.com/in/siddharth-shukla-9b4448205/

## Portfolio

- My Portfolio : https://shxb7.github.io/portfolio/

## Relevant Experience

- We 3 are studying together since past 5 years and have been hacking together since past 2 years.
- We have been to 15 + hackathons together and have won in 11 🥇  of them ,our biggest win was at Superfluid Wavepool#5 and EthIndia.
- You can find more about our wins in my portfolio mentioned above.
- 3rd Year Computer Science Engineering students .

## Team code repositories
- Repo: https://github.com/phovious-14/peer-streams

# Additional Information
- I got to know about the grants proposal from the recent EthGlobal hackathon ~Hack FVEM spacewrap.
- Mail : shubhamashishpatel@gmail.com
- I am also doing a fellowship at EthIndia in Wei track.

**Comment by shxb7** [comment]
Hello @realChainLife ,any updates on the grants application

**Comment by ErinOCon** [comment]
Hi @aeyshubh, thank you for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
