### ISSUE TITLE
Pluser

### ISSUE THREAD

**Issue by elshan-eth** [filecoin-project/devgrants#1408]
# Open Grant Proposal: `Pluser | Web3 Account`

**Name of Project:**

**Proposal Category:** app-dev

**Proposer:** `elshan-eth`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** Yes
# Project Description

About $2 billion were stolen from wallets in 2022 due to hacker attacks and the loss of access. Current wallets as accounts are complex and insecure. 

# Problems
![Problems](https://drive.google.com/uc?id=12R565w8MQxOs2iclh-QrcMcks05kZF79)

### Authorization via Seed

To manage your wallet, you need to store your seed phrase securely. The seed phrase is a complex way of authorization. If a user loses their seed, they lose their account and assets.

### One seed for all devices
Users can't control access between devices. If a user has lost their device, they can not block it from the account. Whoever gains access to the device can access the user's account. Therefore, the only option is to create a new wallet and withdraw all assets there as soon as possible.

### Weak Security
Currently, security is the responsibility of the user. If the user encounters an insecure application, he may lose all his assets.

### No 2FA
If a user encounters a hacker attack, there is no two-factor authentication for defending the user's account.

# Solution
![Solution](https://drive.google.com/uc?id=1d0TOiu99e9Hxt46_G7dJ1Ut-kEZFdoq5)

Pluser is a single account for all web3 apps with authorization via email, decentralized 2FA, device manager, and hack protection.

The user can use any web3 application and not worry about security. We thought of everything for them. Now they never lose their crypto, NFT, etc. Our solution is entirely decentralized, convenient, and secure. It consists of several parts.

### Authorization via email
Users create an account and recover access to an account using email and password. It's simple, and users will never lose access to their accounts.

### Device manager
Users can manage access for each device. If a user loses their device, they can revoke access.

### Hack Protection
If a user uses an unsafe web3 app, Pluser will notify the user about it and block this app.

### Decentralized 2FA
If hackers attack a user's account, 2FA will protect it.

# Web2/Web3
Pluser is a simple and secure way to use web3 applications. It's like **Google Account/Apple ID** but in web3.

![Web2/Web3](https://drive.google.com/uc?id=12uGMkzhZ8HmXdXMfyI5sOU0UcQkjbGjt)

# Easy to use
![1. Create an account via email](https://drive.google.com/uc?id=1y0UEaTZqv6c9lGfe-WtWY2CWc0mk9QQa)

![2. Choose an application in dAppStore](https://drive.google.com/uc?id=1ZzFPrP6nTY9ZXrpNJ8q6iMCZd_ufaLpA)

![3. Don't worry about security. Pluser will protect you. ](https://drive.google.com/uc?id=1l2u3LKlxX-zMn955vGIU7JukCZLYD7bD)

# Market Validation
![Market Validation](https://drive.google.com/uc?id=14DNBjykXq-KpS46UnjEm1zIsJPJOqj-4)

# Comparison
### Terminology:
- **Easy/Complicated** - Degree of difficulty for a user to create an account and gain access.
- **Safe/Unsafe** - How much a user needs to think about security and keeping access to the wallet.

![Comparison](https://drive.google.com/uc?id=1plZfgbqjl8Fv3T3yhTOxYZ7CBaGIZ3Ep)

# Value
Pluser can be a simple and secure way to use the Filecoin ecosystem. Also, pluser can help in onboarding web2 users.

# Deliverables
The MVP will include creating and managing an account via the Web, a Browser Extension for authorization in applications, Mobile Apps, and a dAppStore with a list of applications that can be used in the Filecoin ecosystem.

# Development Roadmap
![Comparison](https://drive.google.com/uc?id=1pfHOLzNMH9nkCn_id2ivMVqz-UGKP3Nm)

# Total Budget Requested
$50,000 for a full-time team of 4 people.

# Maintenance and Upgrade Plans
We are going to raise a full-fledged venture round

# Team
![Comparison](https://drive.google.com/uc?id=1WKDxa7MGYj8s52-GYtTDbGlib9SJLalx)

**Comment by ErinOCon** [comment]
Hi @elshan-eth, thank you for your proposal! Can you briefly explain how/if you are engaging with your target user base? Do you have projections or a general timeline for your onboarding goals?

**Comment by elshan-eth** [comment]
@ErinOCon, Hi! 

We plan to launch on Product Hunt with each new stage described in Roadmap. In August, we plan to have a 1k MAU. And In December, we plan to have a 5k MAU.

We are also talking with other projects about partnerships. We are discussing adding Pluser as one of the authorization methods in their dapp.

**Comment by elshan-eth** [comment]
@ErinOCon @realChainLife @juliangruber @iand 
Hello, do you have updates?

**Comment by juliangruber** [comment]
I think I was mentioned by accident

**Comment by ErinOCon** [comment]
Hi @elshan-eth, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time. For next steps, you may have an interest in considering an [accelerator program](https://ecosystem-wg.notion.site/Protocol-Labs-Accelerator-Program-d45d8792a7d544eca9beb7d3e3d3b05d).
