### ISSUE TITLE
Bacalhau Documentation in Simplified (zh-CN) & Traditional (zh-CHT) Chinese + Docusaurus Site Merge

### ISSUE THREAD

**Issue by lucas-chong** [filecoin-project/devgrants#1413]
### 1. What is your project, and what problem does it solve? (max 100 words)

This project is to perform manual translation and reword the complete Bacalhau documentation into both simplified Chinese (zh-CN) and traditional Chinese (zh-CHT) for the benefit of the Chinese community, providing them an entry point with a lower barrier to the new Bacalhau ecosystem. The Chinese documentation will be accessible on the official GitHub repo and further presented as an attractive web version (using Docusaurus. If possible, cooperate with the person in charge of the official doc repo and merge it with the official Bacalhau doc site).

As English is not the primary language for many individuals in the Chinese community, comprehending the Bacalhau English documentation can be challenging for Chinese developers and beginners. Utilizing automatic page translation (for example Google Translation) is not recommended as it often modifies the meaning of the content due to differences in professional tech-related terms, sentence structure, and grammar. Therefore, it is crucial to have Chinese documentation available for the Bacalhau project. Simplified Chinese will be preferred by the Chinese Bacalhau community in **Malaysia, Singapore, China**, etc. While the traditional Chinese version will be preferred by the Chinese community in **Taiwan and Hong Kong**.

#### Some info about me and my reason for doing this translation project 👇

As a postgraduate student working on a brainwave analysis project related to Bacalhau, I have been actively involved in the JYDC (an international youth developer club). During my time in this organization, I have noticed that many Chinese developers face a significant barrier when attempting to utilize English documentation. These developers often rely heavily on machine translation tools such as Google Translate to decipher technical materials, which can result in inaccuracies and misunderstandings.

Given that my own project is centered around Bacalhau and involves the use of machine learning techniques, I have taken it upon myself to lead a documentation translation project for the Chinese Bacalhau community. My hope is that by offering a more accurate and user-friendly version of the documentation, I can help to alleviate some of the difficulties that Chinese developers face in working with this technology.

My approach to this translation project will be highly organized and collaborative, involving the participation of community members with diverse skill sets and areas of expertise. By working together, we can ensure that the translated documentation is not only accurate but also accessible and engaging for members of the Chinese Bacalhau community.

Overall, I believe that this translation project has the potential to make a significant impact on the development and understanding of Bacalhau within the Chinese market. It is my hope that by improving the accessibility and quality of the documentation, we can help to facilitate more widespread adoption and use of this innovative technology.

### 2. Project links
  
Link to Github repo: https://github.com/lucas-chong/cn-docs.bacalhau.org

License: **Apache License 2.0**
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

This translation project is related to Bacalhau, a project under Protocol Lab
 
###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)

No, it is not related to FVM. But this is a microgrant project with clear milestones.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
  
| Number 	| Grant Deliverable                                                	| Briefly describe how you will meet deliverable objectives                                                                                                          	| Timeframe (within 3 months)      	|
|--------	|------------------------------------------------------------------	|--------------------------------------------------------------------------------------------------------------------------------------------------------------------	|----------------------------------	|
| 1.     	| Documentation Translation to Simplified Chinese                  	| Translate the documentation into Simplified Chinese and review the submitted work.                                                                                    	| Beginning of April - Mid of May  	|
| 2.     	| Documentation Translation to Traditional Chinese                 	| Translate the documentation into Traditional Chinese and review the submitted work.                                                                                   	| Beginning of April - Mid of May  	|
| 3.     	| Final Translation Review + Content Fixing + Diagram Reproduction 	| Perform final translation review and error fixing. Recreate diagrams in documentation in Chinese ver.                                                              	| Mid of May - End of May          	|
| 4.     	| Documentation Site Building                                      	| Integrate Docusaurus and introduce an aesthetic web version Chinese doc site. Build up an automated pipeline for future contribution (update content or fixing errors) 	| Beginning of June - Mid of June                            	|
| 5.     	| Introduce Multi-Language on Official Doc Site                                     	| Contact the person in charge of the official doc repo and cooperate to merge the translated sites into the official doc site for easy access	| End of June                             	|

***Note**: The timeline depends on when the grant is approved, which is predicted to be in early April. Therefore, it may be adjusted if the approval date changes. Once the grant application is approved, the most recent timeline will be provided in this issue.

#### How the grant will be used to improve the translation project? 👇

The grant allocated for the translation of documentation within the Chinese Bacalhau community will be distributed equally among all translation tasks as a bounty payout. In order to ensure fair compensation for the efforts of the translators and reviewers involved in the process, the bounty payout will be divided based on a 7:3 ratio.

By offering this form of compensation, we aim to incentivize more community developers to participate in the translation work and the subsequent post-review tasks. This will ultimately lead to a higher quality final product, as there will be more eyes on the work and a greater pool of individuals contributing their expertise.

We believe that this approach not only promotes inclusivity and collaboration within the Chinese Bacalhau community but also ensures that the documentation is accurately and effectively translated for its intended audience. Additionally, by valuing the time and effort of the translators and reviewers involved, we hope to establish a positive precedent for future community-driven translation projects.

### 5. If accepted, do you agree to share monthly project updates in this GitHub issue for 3 months or until the project described here is complete?

Yes! Our translation project will always be keeping track by a checklist (in the GitHub repo) and can update the progress in this issue every month (from April to June). In addition, when the translation project is complete (the doc site is up and running), I will share a final report of the project.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes, it is.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: - 
  
### Additional questions:

Name: Lucas Chong Eugene (Malaysia)
Email: kl.gogodragon@gmail.com
GitHub: https://github.com/lucas-chong
Role: Leader of the Bacalhau Chinese Community Project

* How did you learn about our microgrant program? I'm an experienced developer in the Filecoin community
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) - 
  * Please link to your hackathon submission -

**Comment by ErinOCon** [comment]
Hi @lucas-chong, thank you for your proposal. Unfortunately, this project does not align with the [current scope](https://github.com/filecoin-project/devgrants/blob/master/microgrants/microgrants.md#focus-areas) of our microgrants program. 

Keep an eye out for additional "focus areas" to open up in the future!
