### ISSUE TITLE
Next Step Microgrant: Bear Store

### ISSUE THREAD

**Issue by SalihToruner** [filecoin-project/devgrants#1414]
### 1. What is your project, and what problem does it solve? (max 100 words)

Bear Store is a decentralized note-taking application with several useful features that make it a great choice for users who need to manage their notes effectively. The features of Bear Store include:

* Add Note: Users can easily add new notes to the application. This feature allows users to quickly create new notes and start jotting down their ideas or important information.

* Edit Note: Users can edit existing notes to update or modify the content. This feature allows users to make changes to their notes without having to create a new one from scratch.

* Delete Note: Users can delete any note they no longer need. This feature helps keep the application organized and clutter-free by allowing users to remove any unwanted notes.

* Web3 Authentication (Soon): This upcoming feature will allow users to authenticate themselves on the application using their Web3 wallet, which offers an added layer of security.

* IPFS Upload via web3.storage (Soon): This feature allows users to store their notes securely using IPFS (InterPlanetary File System) and web3.storage, which ensures that their notes are always accessible and protected.

* Cross-platform compatible (Soon): The application is compatible with multiple platforms, including Windows, macOS, Linux, iOS, and Android, making it easy for users to access their notes from any device.

Overall, Bear Store offers a comprehensive set of features that make it a reliable note-taking application. Its upcoming Web3 authentication and IPFS storage options make it an excellent choice for users who prioritize security and privacy.

### 2. Project links
  
Link to Github repo: https://github.com/SalihToruner/Bear-Store
Link to demo or website: https://bear-store.vercel.app/
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

Bear Store uses IPFS and web3.storage to securely store notes uploaded by users, ensuring that the notes are always accessible and protected. The application plans to implement Web3 authentication in the future to enhance its security and make it more resilient to attacks.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
No  

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |         Web3 Storage Implementation |                                    I will implement web3.storage as storage solution                        |                1 weeks            | 
| 2.     |           Magic Auth Implementation              |                                Bear Store will use Magic Web3 authentication for user onboarding and authentication                          |                     1 weeks       | 
| 3.     |        UI Developments                 |              UI improvements will be completed as the final stage                                              |       1 weeks                     | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes, I accept.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes, it complies.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: **No**

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by SalihToruner** [comment]
Any progress?

**Comment by ErinOCon** [comment]
Hi @SalihToruner, thank you for your proposal. Unfortunately, we will not be moving forward with a microgrant at this time. Wishing you the best as you continue building!
