### ISSUE TITLE
Eclipse - Data DAO's Simplified - 🏆 Space Warp Winners

### ISSUE THREAD

**Issue by eclipse-ddao** [filecoin-project/devgrants#1417]
### 1. What is your project, and what problem does it solve? (max 100 words)
Eclipse is a decentralized platform that provides a digital workspace for startups and businesses to store and manage their files securely using Data DAOs. 
With Eclipse, businesses can:
1. Store and share files securely and privately with the members of their DAO (on Filecoin).
2. Leverage a decentralized Storage Provider Marketplace and request for storage of Big Files (100+ GB).

### 2. Project links

- [Eclipse Smart Contracts](https://github.com/eclipse-ddao/smart-contracts)  

- [Our Web Application Source Code](https://github.com/eclipse-ddao/web-application)

- [Our UX Backend Source Code](https://github.com/eclipse-ddao/ux-backend)

- [Video Demo](https://ethglobal.com/showcase/eclipse-data-daos-simplified-2o8fc)

- [Live Demo](https://eclipse-web3.netlify.app/)

License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

The architecture of Eclipse is two fold:

1. Every DataDAO on eclipse gets an unique instance of 'Eclipse' deployed for them, such that all the information is contained and easy to sift through. Using the power of Sharded Keys by [LightHouse](https://www.lighthouse.storage/), we are able to provide Dao Members with a Google Drive like experience for sharing files within their DAO - "PRIVATELY". Even if the CID is out there in public, the content of the CID will be encrypted from the get-go!

2. Secondly, we absolutely believe that Storing Big Files in a secure and decentralized way is an absolute requirement for many companies and startups, especially with the amount of data one is able to collect. With eclipse we have built an integrated-automated storage marketplace for Companies to put out "Requests" and for Storage Providers to bid on top of these requests with their "Proposals" . Once a storage proposal is accepted, an escrow will get deployed using the DAO's treasury and the deal management is automated using [Zondax's MarketAPIs](https://github.com/Zondax/filecoin-solidity).

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |Video calling amongst Data DAO members.                         | Integrating Huddle & Creating a UI Interface to support the same                                                        |~1 Month                            | 
| 2.     |More control over how your files exist within a Data DAO                       |Building on top of our current Access control infrastructure using lighthouse                                                             |~1 Month                            | 
| 3.     |Analytics for SPs                      | Add additional features of storage providers giving them a detailed view of their active deals, total data cap etc.                                                            |~15 days                      | 
| 4.     |Integrating social auth                         |To provide a more seamless user experience to web2 users we would be implementing web3auth                                                            |~15 days                          | 

We are committed to making Eclipse a practical + usable application which can showcase the capabilities of FVM and Filecoin. 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

#### Eclipse was made as a submission for the FVM Space Warp Hackathon

- Our Submission Link - [ETHGlobal](https://ethglobal.com/showcase/eclipse-data-daos-simplified-2o8fc)
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Ankit N.
Github - ankitn1311
Front End Developer & Lead

Ankit S.
Github - zigzagsz
Project Lead

Ashwin P.
Github - hwnprsd
Smart Contract Developer

Our team mail for communication - eclipseddao@outlook.com

* How did you learn about our microgrant program?
Mail from prizes@protocol.ai
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) 

#### Eclipse was made as a submission for the FVM Space Warp Hackathon

- Our Submission Link - [ETHGlobal](https://ethglobal.com/showcase/eclipse-data-daos-simplified-2o8fc)

🔥 Filecoin & IPFS — 🏊 FVM Jetpacks trophy
🏆 FVM Space Warp Finalist

Recognition from Filecoin - [Twitter post](https://twitter.com/Filecoin/status/1624108885987426314?s=20)
ETHGlobal Finalists - [Twitter post](https://twitter.com/ETHGlobal/status/1624106026696835078?s=2)

**Comment by ErinOCon** [comment]
Hi @eclipse-ddao, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue to build!

**Comment by eclipse-ddao** [comment]
Dear @eshon @ErinOCon

Thank you for taking the time to review our grant application. We understand and respect the decision but would like to provide additional context that may warrant reconsideration.

During the hackathon, our team utilized the Lighthouse Encryption SDK (Kavach), which was supported by Filecoin. However, post-hackathon, Kavach has not been supported or further developed. This has led us, the Eclipse team, to work on developing our own Encryption SDK.

Our project aims to help developers integrate access-control based encryption that is designed with Filecoin storage in mind. We plan to support all contracts on the FVM, initially on the calibration testnet. Our SDK will include capabilities that allow files to be decrypted only when storage-deals are complete or ongoing.

This effort is primarily to enable more secure access to files, particularly for DAOs and Treasuries, while keeping absolute decentralization in mind. We believe this open-source effort is crucial for the broader Filecoin ecosystem, hence our application for grant funding.

We are more than willing to provide additional information or clarify any aspects of our proposal. Given the potential impact of this project on the broader ecosystem, we kindly request that you reconsider our grant application. We appreciate your time and consideration and look forward to your feedback.

Best Regards,
The Eclipse Team

**Comment by eclipse-ddao** [comment]
@ErinOCon @eshon Looking forward to hearing from you soon. We see a vision with Eclipse and this microgrant will really allow us to fulfil the vision and as mentioned before We are more than willing to provide additional information or clarify any aspects of our proposal. Given the potential impact of this project on the broader ecosystem, we kindly request that you reconsider our grant application.
