### ISSUE TITLE
Next Step Microgrant: DataHaus

### ISSUE THREAD

**Issue by Webmoss** [filecoin-project/devgrants#1418]
### 1. What is your project, and what problem does it solve? (max 100 words)
DataHaus is a decentralised data economy, built on Filecoin, which provides a reliable web3 data foundation to efficiently handle all data types and uses cases needed today.

Filecoin is a powerful and dynamic distributed cloud storage network for your data. Create and tune strategies to suit your big and small data needs in redundancy, retrieval speed, data processing and cost.

Project Overview

1. Upload your valuable files and data to IPFS, NFT.Storage, Web3.Storage, Estuary for 6x data replication or LightHouse for data encyption / decryption and permissioned file sharing. DataHaus offers truly decentralised storage options.
2. Create collections of big or small datasets, useful for batch processing, analytics and AI use cases. Bacalhau offers Compute Over Data or COD services.
3. Create storage deals / bounties for your valuable data, the Filecoin storage providers compete to win storage bounties and bring the costs down for the client.
4. Receive discounts and bid for entire sectors and volume discounts, where the price is further reduced for purchasing multiple sectors at once.
5. Receive dynamic NFTs for completed storage deals that serve as Proof-of-Deal or POD's'.
6. A defi element will be incorporated for staking the dNFT's, this offers further incentives to data holders and storage providers or miners. Our ERC-20 datacoin, will be incorporated for additional miner rewards, etc.
7. Our dashboard allows user to browse Filecoin data including latest block heights and time, get block info by tipset, transaction id and more.
8. View your account transactions and search global Filecoin transaction in a sleek user-interface.
Incorporate various API's like Beryx API and Filrep to utilise the FEVM to it's fullest potential as a everyday user, big or small business and storage providers or miners.

### 2. Project links
  
Link to Github repo: https://github.com/DataHaus/datahaus
Link to demo or website: https://datahaus.vercel.app/
Link to showcase: https://ethglobal.com/showcase/datahaus-jvhhb

License:

License updated as above
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

DataHaus allows users to upload files and data to IPFS, NFT.Storage, Web3.Storage, Estuary for 6x data replication or LightHouse for data encyption / decryption and permissioned file sharing. DataHaus will utilise Bacalhau which offers Compute Over Data or COD services. Users will be able to create storage deals / bounties for your valuable data, the Filecoin storage providers compete to win storage bounties and bring the costs down for the client. Receive discounts and bid for entire sectors and volume discounts, where the price is further reduced for purchasing multiple sectors at once.

###    b) Is this project building with the current microgrants focus area (FVM)? 
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |   Integrate Filecoin Contracts for Storage Deals | Work through code examples and other to achieve this goal                                |   1 month            | 
| 2.     |          Integrate Bacalhau services               |     Integrate the Bacalhau sdk and smart contract services                                                       |.   1 month.   | 
| 3.     |    Establish a website, twitter and other social channels       |  Create a business profile for DataHaus and improve the front-end look and feel       |   2 weeks      | 
| 4.     |   Launch datacoin ERC-20 token and ERC-721 NFT on Filecoin     |  Launch an ERC-20 token and build on the Tableland protocol for the ERC-721 NFT that the app will mint     |   2 weeks      | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes, happy to report on progress
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes it does

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
EthGlobal Space Warp Hackathon 2023
Filecoin & IPFS — 🏊 FVM Jetpacks
https://ethglobal.com/showcase/datahaus-jvhhb
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Craig Moss
craigmoss36@gmail.com
https://github.com/Webmoss
web3 hacker / front-end developer

* How did you learn about our microgrant program? Received email for winners of prizes.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
DataHaus
EthGlobal Space Warp Hackathon 2023
Filecoin & IPFS — 🏊 FVM Jetpacks
https://ethglobal.com/showcase/datahaus-jvhhb

**Comment by eshon** [comment]
Hi @Webmoss - This is a nice project and we're leaning towards approving this for an FVM microgrant but was wondering if you could connect with the Bacalhau team (@AlisonWonderland on Filecoin Slack) and incorporate some upcoming FEVM storage deal workflows from a smart contract that will be published around FEVM launch time next week on Pi Day, March 14? We'll let you know when these are ready for your reference!

**Comment by Webmoss** [comment]
Thanks @eshon 

A grant will be fantastic 👏. 

I definitely plan on incorporating FEVM storage deal workflows and will be attending the Scaling Ethereum hackathon to work on this and some other pieces I want to bring into DataHaus.

I'm already on the Filecoin slack channel and chatted with Ally on the channel about her work with the Bacalhau stable diffusion cod service. Been following the Bacalhau project closely and will be utilizing Bacalhau for my data processing.

There's still alot to do but I've got plans to include more features like Polybase and Tableland for the POD Nfts.

Let me know if you need more info, I've also applied for the mainnet cohort, hope its still open.

Regards Craig Moss

**Comment by Webmoss** [comment]
Gonna close this now

**Comment by Webmoss** [comment]
Hi Eva

Thanks for getting back to me.

Thats sounds good, apologies, I thought my application was unsuccessful so
closed it.

It would be great if we can get a grant, will be a big help for me

Regards
Craig
