### ISSUE TITLE
Next Step Microgrant: FVM-Explore - Developer Tooling

### ISSUE THREAD

**Issue by Abbas-Khann** [filecoin-project/devgrants#1419]
### 1. What is your project, and what problem does it solve?

FVM-Explore allows developers to **Compile, Deploy, Verify, and Interact with Smart contracts** on the FVM-Chain with an easy-to-use interface and interactive experience. It also provides developers with APIs to build on top of the platform.

It is a native developer tooling and Infrastructure application for the FVM Ecosystem focusing on providing the best developer experience. Developers no longer need to write scripts or export private keys or do any previous setup to deploy or interact with their smart contracts.

### 2. Project links

[FVM-Explore Source Code](https://github.com/Abbas-Khann/FVM-Explore)

[Link to Web Application](https://fvm-explore.vercel.app/)

[Link to our APIs](https://github.com/Abbas-Khann/FVM-Explore/blob/main/frontend/API.md)

License: MIT

### 3. a) How is IPFS, Filecoin, or related technology used in this project?

FVM-Explore was built with one thing in mind, To improve the developer experience on the Filecoin Virtual Machine and to make this chain more adaptable and easier to work with for developers. The sole aim is to just to add value the FVM Ecosystem with the best developer tooling and experience to build upon. The platform will be enabled for the **FVM MAINNET** as soon as it is launched on March 23, along with further testing.

All the Contract data and records are also stored on IPFS for the smooth functioning of the platform.

### b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)

Yes

### 4. How will you improve your project with this grant? What steps will you take to meet this objective?

| Number | Grant Deliverable                          | Briefly describe how you will meet deliverable objectives                                                 | Timeframe (within 3 months) |
| :----- | :----------------------------------------- | :-------------------------------------------------------------------------------------------------------- | :-------------------------- |
| 1.     | Onchain Bytecode verification              | Partial Verification of on Chain Contract Bytecode with the Contract Code to verify the deployed contract | ~2 weeks                    |
| 2.     | Improved compilation and compiler settings | Adding an improved version of compiler and adding a complete online IDE to work with                      | ~2 weeks                    |
| 3.     | Dashboard for ease in development          | A Full developer dashboard to manage and interact with pre-deployed Smart contracts                       | ~ 1 week                    |
| 4.     | Mainnet deployment                         | Adding FVM-Mainnet deployment support after release                                                       | ~1 week                     |

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions

- FVM-Explore was built as a submission for the FVM-Space-Warp hackathon.

* Our submission link: [EthGlobal](https://ethglobal.com/showcase/fvm-explore-zk0dg)

  Winner of trophy:
  🛠 Filecoin & IPFS — 🥇 Discovery Tools

  🏆 FVM Space Warp Finalist

### Additional questions:

- For each team member(s), please list name, email, Github account, and role in the project.

  Abbas Khan

  [Github](https://github.com/Abbas-Khann)

  Frontend Developer and Product Designer

  Dhruv Agarwal

  [Github](https://github.com/Dhruv-2003)

  Backend Developer

  Our Email for communication - [abbaskhan61999@gmail.com](mailto:abbaskhan61999@gmail.com)

- How did you learn about our microgrant program?

* Mail from [prizes@protocol.ai](mailto:prizes@protocol.ai)

- If your project was created as part of an event or hackathon:

  - What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)

    FVM-Explore was built as a submission for the FVM Space Warp Hackathon

  - Our Submission link: [EthGlobal](https://ethglobal.com/showcase/fvm-explore-zk0dg)

  - Recognition from Filecoin: [Twitter Post](https://twitter.com/ETHGlobal/status/1624106022326632448?s=20)

  - EthGlobal Finalist: [Twitter Post](https://twitter.com/ETHGlobal/status/1624106022326632448?s=20)

### Notes

We are also interested in applying for a Request for Proposals under the FVM Tooling and infrastructure category. We have a lot of other features planned, to make the platform even better for developers. Some of them are :

- Command Line tool ( CLI ) access to the full platforms and its feature right from scratch on the command line
- Customisation with support of different compiler versions and fully interactive coding IDE environment

These could be discussed further, as these features will take much more time and effort.

**Comment by ErinOCon** [comment]
Hi @Abbas-Khann, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
