### ISSUE TITLE
Next Step Microgrant: Tellor

### ISSUE THREAD

**Issue by brendaloya** [filecoin-project/devgrants#1422]
### 1. What is your project, and what problem does it solve? (max 100 words)

The Tellor oracle system is a fully decentralized community focused on securely placing data on-chain. The oracle mechanism works by using simple crypto-economic incentives to secure data through staking and dispute mechanisms, while the community is bound by a token for governance and monetary policy to reward adoption and development of the network. Oracles are key infrastructure for any blockchain ecosystem.  Whether it’s the ability to query price data for defi applications, connect to other chains, or make governance decisions based on real world input, oracles make the future of a chain not only exciting, but relevant to the real world.

### 2. Project links
  
Link to Github repo: https://github.com/tellor-io/
Link to demo or website: https://tellor.io/
License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

Our oracle would be deployed and supported on Filecoin’s Virtual Machine. The Tellor system is composed of three main contracts: TellorFlex, Governance and Autopay. TellorFlex contains all the functionality for reporters to deposit their bond, report the data, receive economic incentives to provide the data, for users to read the data, and begin a dispute if data seems suspect. The Governance module allows for the dispute resolution, including voting, and calling functions on TellorFlex for settling the dispute either by slashing the reporter if found guilty or paying them the dispute fee otherwise. The autopay module allows users to incentivize reporters to provide their data. Together they provide a crypto-economically secure oracle system that can continue to function with minimal team intervention. Tellor will continue to provide integration support to the Filecoin community. 

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)

  Yes

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

We will expand the reporter software to support the filecoin virtual machine as well as work with filecoin developers and team to add novel data types which can be utilized and bridged to all chains connected by the tellor oracle. 
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |   Testnet deployment of the oracle, dispute mechanism, fees contract to incentivize data reporters, and test TRB token contract for testing  (will use bridged TRB once the bridge is up and running)    |     March 3, 2023                                                           |                            | 
| 2.     |    Provide support for data reporting on FVM                      |    March 10, 2023     |                            | 
| 3.     |     User and reporter documentation                       |    March 10, 2023      |                            | 
| 4.     |     Mainnet deployment  with bridged TRB  (dependent on when the ETH - FVM bridge is up and running)     |    April 10, 2023      |                            | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: 

N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
    * https://github.com/themandalore - Nick Fett CTO
    * https://github.com/brendaloya - Brenda Loya CEO 
    * https://github.com/tkernell  -   Integrations Engineer
    * https://github.com/orgs/tellor-io/people/akremstudy - Developer
    * https://github.com/tallywiesenberg - Developer
    * https://github.com/oraclown - Developer

* How did you learn about our microgrant program?

A mutual community member (X-Factor).

* If your project was created as part of an event or hackathon: 

N/A

  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
  
N/A

**Comment by brendaloya** [comment]
Hi @ErinOCon !  That is awesome. Please email me at Brenda@tellor.io

**Comment by brendaloya** [comment]
Hi @ErinOCon , can you provide what email I should expect communication from? I want to make sure it doesn't got to spam.

**Comment by ErinOCon** [comment]
Hi @brendaloya, you should receive an email from grants@filecoin.org. Thanks!

**Comment by ErinOCon** [comment]
Hi @brendaloya, I hope your project is progressing well! If you have any questions regarding the reporting process for this work, please be in touch. In the meantime, here are some things we are looking for when reviewing FVM Microgrant results: 

- A fully working user-facing demo with nice UX that anyone case easily use.
- Deployment to FVM mainnet - now that it has officially launched!
- Interesting use of the EVM on Filecoin, especially with respect to what's unique to Filecoin

Happy building!

**Comment by brendaloya** [comment]
Hi @ErinOCon, I still have not received a follow up email from grants@filecoin.com. Any update on that?

We are currently launched on testnet and we are waiting for the bridge to be ready so we can deploy on mainnet. 

An oracle is implemented at the code base and is custom to each project (B2B). The integration is not something that can be done  on a front end. With that said, we will show reported data on file coin on our data feeds page once indexing for it is added to the graph or other similar service. 

Happy to jump on a zoom call if you guys need any additional clarification. 

Milestone 1: Testnet deployment of the oracle, dispute mechanism, fees contract to incentivize data reporters, and test TRB token contract for testing (will use bridged TRB once the bridge is up and running):

Autopay - 0x9BE9B0CFA89Ea800556C6efbA67b455D336db1D0
https://beryx.zondax.ch/v1/search/fil/mainnet/address/f410ftpu3bt5it2uaavlmn352m62fluzw3moqdk6qyfq
QueryDataStorage - 0xf44166ca8bdB612268a4D401e4c5147968E5a190
https://beryx.zondax.ch/v1/search/fil/mainnet/address/f410f6rawnsul3nqse2fe2qa6jriupfuolimqf6f6xei
Governance - 0xb55bB55f7D8b4F26Bd18198088C96488D95cab39
https://beryx.zondax.ch/v1/search/fil/mainnet/address/f410fwvn3kx35rnhsnpiydgairslerdmvzkzzfhinr2q
TellorFlex - 0xb2CB696fE5244fB9004877e58dcB680cB86Ba444
https://beryx.zondax.ch/v1/search/fil/mainnet/address/f410fwlfws37ferh3sacio7sy3s3ibs4gxjceyjtyofa
TellorPlayground - 0xe7147C5Ed14F545B4B17251992D1DB2bdfa26B6d
https://beryx.zondax.ch/v1/search/fil/mainnet/address/f410f44khyxwrj5kfwsyxeumzfuo3fpp2e23noyw65vq

**Comment by brendaloya** [comment]
ping @ErinOCon

**Comment by brendaloya** [comment]
Hi @ErinOCon ,

Autopay contract deployed to:  0x60cBf3991F05a0671250e673Aa166e9D1A0C662E
https://filfox.info/en/address/0x60cBf3991F05a0671250e673Aa166e9D1A0C662E

QueryDataStorage contract deployed to:  0xf44166ca8bdB612268a4D401e4c5147968E5a190
https://filfox.info/en/address/0xf44166ca8bdB612268a4D401e4c5147968E5a190

Governance contract deployed to:  0xb55bB55f7D8b4F26Bd18198088C96488D95cab39
https://filfox.info/en/address/0xb55bB55f7D8b4F26Bd18198088C96488D95cab39

TellorFlex contract deployed to:  0xb2CB696fE5244fB9004877e58dcB680cB86Ba444
https://filfox.info/en/address/0xb2CB696fE5244fB9004877e58dcB680cB86Ba444

Bridged TRB 0x045CE60839d108B43dF9e703d4b25402a6a28a0d

**Comment by ErinOCon** [comment]
Hi @brendaloya, thank you for the provided updates! The email regarding the first installment should have arrived on March 1, 2023. I have sent you a new email regarding the second installment today. Can you confirm receipt?

**Comment by ErinOCon** [comment]
Hi @brendaloya, I have closed this issue as our records reflect all payments are complete. Please be in touch at grants@fil.org with any additional updates or questions.
