### ISSUE TITLE
Next Step Microgrant: 🐱‍👤Ninja Dash 🐱‍🚀

### ISSUE THREAD

**Issue by alexaport** [filecoin-project/devgrants#1423]
### 1. What is your project, and what problem does it solve? (max 100 words)
Ninja Dash is an amazing platformer game loaded with FVM web3 features built-on FVM, in-game purchase store to buy with FVM, NFT minting of characters, in-game tokens like ERC20 and use of in-game token ERC20. NFT mining, store and retrieving on filecoin IPFS. 15 levels and 3 NFT playable characters in the game.

### 2. Project links
  
Link to Github repo: https://github.com/NinjaDash/NinjaDash
Link to demo or website: https://www.thundergamestudio.com/web3/ninjadash/
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
 = FVM is used to create multiple smart contracts for in-game purchase store, NFT minting, ERC20 token, token exchange mechanism, Filecoins IPFS to store and load NFT data like metadata, FVM for native balance, and transaction stuff. 

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
 = Yes 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |  More game levels                        |      35 level design, implementations and testing                                                      |   6 weeks                         | 
| 2.     |     More NFT Game Character                    |    2 More NFT characters with animations and in game implementations with controllers                                                 |    3 weeks                        | 
| 3.     |    Game Optimization                     |     Improving overall game size, performance, fixing bugs and browser-friendly upgrades                                                       |      1 week | 
| 4.     |  Game UI/UX Upgrade                       |  Improving overall game UI/UX flow for better user engagement                                                            |     1 week                       | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
 = Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
 = Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 = https://ethglobal.com/showcase/ninja-dash-2yka2
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
 - Harsha - harsha@thundergamestudio.com
    GitHub - alexaport
    [Game And Graphics Designer]

 - Mahesh- mlp@thundergamestudio.com
    GitHub - vivektgs
    [Blockchain Developer]

 - Jigar - jigar@thundergamestudio.com
    GitHub - TGS2016
    [Full Stack Game Developer]

* How did you learn about our microgrant program?
 = Email information through Niki (Ecosystem Growth - Protocol Labs)

* If your project was created as part of an event or hackathon:
 = Yes
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  = [FVM SPACE WARP](https://ethglobal.com/events/spacewarp)
  * Please link to your hackathon submission
  =  https://ethglobal.com/showcase/ninja-dash-2yka2
       Note : 🏆 FVM Space Warp Finalist

**Comment by ErinOCon** [comment]
Hi @alexaport, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
