### ISSUE TITLE
Next Step Microgrant: Data Depot for FVM Dealmaking

### ISSUE THREAD

**Issue by nandit123** [filecoin-project/devgrants#1425]
### 1. What is your project, and what problem does it solve? (max 100 words)
This solution entails building out a data depot for devs to upload files to; this data depot can then be used by Boost SPs to download data. 

In particular, this is a web server and web portal where any builder (with github login) can upload an item <5GB. 
- The goal is for this project to provide a good educational example for other FVM developers so that they can easily run this themselves and extend it if they choose.

That item will then be converted to a .car file, and the dev will get a hyperlink to the file. The link can be referenced in any smart contract the dev writes to make a storage deal. The file is automatically deleted in 30 days. They can upload at most 20 items at one time.

### 2. Project links
  
Link to Github repo: https://github.com/lighthouse-web3/data-depot

License:

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
Upload File to the backend service and generate CAR File for filecoin deal making by Boost SPs to download data via url

###    b) Is this project building with the current microgrants focus area (FVM)? 
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |       End user can upload a file, the file will be converted into carfile, user will get a URL of its equivalent car file                  |   Create single page UI for uploading File and backend service for CAR generation                                                         |        27th Feb-8th March                   | 
| 2.     |       End user can only upload a file <5GB, and only upload 20 files at once                  |                Handle the required number of files and file size on upload returning the appropriate response to the user                                            |        27th Feb-8th March                    |
| 3.     |       End user needs to have a github account to login                  |             Integrate github auth or similar service                                               |            9th March-13th March                | 
| 4.     |        End user will be notified of file deletion in 30 days                 |           Notified on UI                                                 |          9th March-13th March                   | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Nandit Mehra - nandit@lighthouse.storage - @nandit123 - project lead

* How did you learn about our microgrant program?
Github

* If your project was created as part of an event or hackathon:
N/A

**Comment by raulk** [comment]
Some feedback:

- Needs to be open source: https://protocol.ai/blog/announcing-the-permissive-license-stack/
- Needs to be self-hostable (users should be able to set up their own depots locally, or there may be future hosted services besides Lighthouse).
- The terms of the Lighthouse costing are not clear in this proposal (how long this devgrant will cover, SLA, etc.)

**Comment by raulk** [comment]
@eshon the questions above are blocking for approval

**Comment by eshon** [comment]
@nandit123 - Can you please update the proposal with Raúl's requests above? cc: @honghaoq

**Comment by ErinOCon** [comment]
HI @nandit123, this microgrant has been approved! We will send an email to confirm payment details.
