### ISSUE TITLE
WFIL-wrapped FIL

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/devgrants#1426]
### 1. What is your project, and what problem does it solve? (max 100 words)

Wrapped Filecoin (WFIL) is a token pegged to Filecoin (FIL).  WFIL is used in several platforms and DApps that support ERC-20 tokens.  While FIL is used to pay for network transaction fees, WFIL has the same functionality as ERC-20 tokens.
Filecoin's DeFi ecosystem is large, and using WFIL provides more opportunities for staking and investing.  There are many versions of WFIL, but some are more popular than others.  You can even find wrapped FIL on other blockchains to use in their ecosystems.  Popular uses for WFIL include NFTs trading, providing liquidity to liquidity pools, and crypto lending.
### 2. Project links
  
Link to Github repo: https://github.com/froghub-io/WFIL
Link to demo or website:https://wfil.io
License:

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

WFIL is a FEVM smart contract.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

First of all, it's not a profitable project. It will be completely open source. We hope to get this grant to better carry out the preliminary work: contract development and improvement, testing, official website, white paper, publicity and other works.
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |        WFIL Smart contract code                 |                  Accelerate smart contract development and commit all code on git.                                          |               Before 2023.03.13             | 
| 2.     |              White paper           |                       Complete the WFIL document, WFIL introduction, basic operations, and access methods.                                     |            Before 2023.03.13                 | 
| 3.     |           Multiple network deployment              |                                        Deploy the WFIL smart contract to Mainnet and Hyperspace networks                    |              Before 2023.03.13               | 
| 4.     |              Audit          |                          Complete the smart contract test and invite the blockchain ecological security team to audit.                                  |               Before 2023.03.13              | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
N/A

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Mercy Lin - team@froghub.io - @FroghubMan - project lead
* How did you learn about our microgrant program?
GitHub
* If your project was created as part of an event or hackathon:
N/A

**Comment by eshon** [comment]
@FroghubMan - Have you contacted any potential security auditors to get a quote for an audit?

**Comment by FroghubMan** [comment]
Quotation from SlowMist smart contract audit group:
Project: WFIL
Quoted Price: 10000 USD
Type: Token
Module: ERC20 Token + flashLoan
Code Lines: 288
Complexity: Simple
Audit Workload: 3 working days
Description: This is ERC20 token contract that contains the flashLoan part

Project address:
https://github.com/froghub-io/wfil
commit: 4fe1ebae420db8aff9eb9d63484044281bba60f5

Please confirm whether the project address and commit listed above is correct.
Smart contract security audit items reference:
https://www.slowmist.com/en/service-smart-contract-security-audit.html

**Comment by FroghubMan** [comment]
We just found out that the microgrant is not enough to support wFIL to complete the audit fee. what do I do? Are there any recommended blockchain security audit companies?

**Comment by FroghubMan** [comment]
Hi @eshon , our project wfil won second prize at OPEN HACK DAYS, which has helped to increase its visibility within the community and gain support from many community members. Therefore, we hope to further improve it and we would appreciate it if you could take this factor into consideration. We sincerely hope to receive further funding.

**Comment by FroghubMan** [comment]
Hi @eshon , our project wfil won second prize at OPEN HARK DAYS. It has gained some recognition within the community and received support from many community members. Therefore, we hope to further improve it and we would appreciate it if you could take this factor into consideration. We sincerely hope to receive further funding.

**Comment by ErinOCon** [comment]
Hi @FroghubMan, this issue has been closed as the review for this microgrant is complete. Please feel welcome to contact our team at grants@fil.org with any questions.
