### ISSUE TITLE
Next Step Microgrant: Tau

### ISSUE THREAD

**Issue by ozeliger** [filecoin-project/devgrants#1427]
### 1. What is your project, and what problem does it solve? (max 100 words)

Tau introduces a next-gen decentralized exchange providing liquidity, an auto-farming stablecoin, and enabling peer-to-peer transactions on Filecoin. 
Tau allows users on Filecoin to trade directly from their wallets rather than through a 3rd-party -- your tokens never leave your custody, and are 100% owned by you. Further, low trading fees and high liquidity makes Tau an attractive platform to trade with, and also helps provide a broad range of support to various facets of the Filecoin community -- to continuously adapt to the changing markets by continuing to provide value to both token holders and the community. Tau provides the following features:

1. High-efficiency swapping (fork of Uniswap; made more gas-efficient)
2. Yield Farming
3. Secure Cross-chain Bridge

[[More details here](https://github.com/ozeliger/tau)]

### 2. Project links
  
Link to Github repo: https://github.com/ozeliger/tau
Link to demo or website: https://tau-fvm.vercel.app/
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

Our contracts would be deployed and supported on the Filecoin Virtual Machine. This includes our capital-efficient swapping & yield farming features as well as our cross-chain bridge. We're looking at potentially launching an oracle service for said bridge, which would also be deployed on FVM.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |  Testing contracts already deployed on Hyperspace, and iron out bugs                       |          1 month                                                 |                            | 
| 2.     |  Deploy swap & yield farming to Mainnet                       |                end-March 2023                                            |                            | 
| 3.     |    Deploy oracle service for bridge                     |           April 7, 2023                                                 |                            | 
| 4.     |     Deploy cross-chain bridge on Mainnet                    |      mid-April 2023                                                      |                            | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes ([FVM Space Warp 2023](https://ethglobal.com/showcase/tau-gowot))  

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Jason D (jasozeliger@gmail.com) CEO/CTO
* How did you learn about our microgrant program? Email
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
  [Tau - FVM Space Warp 2023](https://ethglobal.com/showcase/tau-gowot)

**Comment by ozeliger** [comment]
Hi there. Any update? @ErinOCon @eshon ?

**Comment by ozeliger** [comment]
Could I kindly request an update on this @ErinOCon @eshon

**Comment by trruckerfling** [comment]
Hey @ozeliger can I check if Tau has been pivoted into Calabi Exchange? Marc mentioned this on Slack. If so, could you provide details on the new project direction please? Thanks

**Comment by ozeliger** [comment]
That's right @trruckerfling. Our direction largely remains the same. Though as indicated to Lukas & Anshuman, our grant needs might spill over past the microgrant size of $5k. Should I convert this to an open grant proposal instead?

**Comment by trruckerfling** [comment]
@ozeliger can you pls share the new scope that would require an open grant? we are inclined to have you switch it over to open grant and be reviewed there for a larger amount. also please submit as calabi exchange
