### ISSUE TITLE
Greenade - ReFi Data Dao [ETHforAll Winner - FVM Track] 🍃🍃

### ISSUE THREAD

**Issue by Greenade-refi** [filecoin-project/devgrants#1429]
### 1. What is your project, and what problem does it solve? (max 100 words)
Greenade is a decentralized carbon credit platform that allows customers to buy carbon credits from producers using tokens. The platform consists of four smart contracts written in Solidity:

1. CarbonRegistry - This is the smart contract where various companies can come and provide proof that they generated mWH of electricity and put it on the blockchain.
2. Verifier - This is a smart contract where authorized verifiers can verify that the projects uploaded in the registry are legit and can approve the same using a multi-sig mechanism.
3. Token - This is a normal ERC20 token, which is minted every time a project is verified, proportional to the mwh generated and is burnt when a customer wants to avail the carbon credit NFT.
4. AMM - This is a smart contract used for market making the Token with stable coins or in this case (TFIL ).
### 2. Project links
  
Link to Github repo: 
Smart contracts -> https://github.com/Greenade-refi
Front end -> https://github.com/Greenade-refi/Greenade-frontend-v2 (Updated)
Devfolio -> [Link](https://devfolio.co/projects/greenade-refi-data-dao-73e7)

Link to demo or website -> https://greenade-web3.vercel.app/

License: MIT

### 3. a) How is IPFS, Filecoin, or related technology used in this project?
AMM - This is a smart contract deployed on FVM used for market making the token with stable coins or in this case (TFIL) we intend to take it to Mainnet when the time comes.

CarbonRegistry - This is the smart contract deployed on FVM where various companies can come and provide proof that they generated mWH of electricity and store it on the blockchain.

We use FVM to conduct all operations on Greenade. The storage of SoulBound Tokens, the GRN Token itself as well as DataDAO & Carbon Registry, all exists in FVM. 
We also use FVM's native actor APIs to make calls to Storage Provider Markets to make sure any data being stored by the DataDAO is stored with integrity and longevity in mind.

We are live on Hyperspace Testnet -

Token - 0xB4652c0BD9Df997a93b1CAa476e94336089F1b99 (https://hyperspace.filfox.info/en/address/0xB4652c0BD9Df997a93b1CAa476e94336089F1b99)

Carbon Registry - 0xe061B68D9022D7776B9fBE24EE3d6e23e2008474 (https://hyperspace.filfox.info/en/address/0xe061B68D9022D7776B9fBE24EE3d6e23e2008474)

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes!
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | Smart contract rewrite                         |We can make the AMM and the registry smart-contracts more optimized and reduce the number of smart-contract calls needed. Making it ready for mainnet launch                                                          |15 Days                        | 
| 2.     |Dashboard for clients                         |The user interface requires more work as it was made during the hackathon and differs from what we would expect the final flow to be. We would ideally want to onboard +1 UX Researcher for the same.                                                          |15 Days                            | 
| 3.     |UI Rework                         |This work requires major work from the UI end in terms of better visual explanation when it comes to deploying capital costs for renewables. We want our platform to be the most transparent and seamless way of helping individuals and corporates go green                                                     |1 Month                           | 
| 4.     |Developer Hire                       |Looking forward to use the prize and hire a developer / intern to help me with the above mentioned deliverables |1 Month                           | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes indeed!
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes!

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes we participated in the Filecoin FVM track of the ETHForAll Hackathon: https://devfolio.co/projects/greenade-refi-data-dao-73e7

We won the Filecoin FVM Track - https://ethforall.devfolio.co/projects?prizes=Filecoin%3A+Top+3+hacks&show_winners=false

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Name: Pulkit
GMail: teamgreenade@gmail.com
GitHub: https://github.com/Greenade-refi
Role: Lead dev & designer

* How did you learn about our microgrant program?
Through Spacewarp we learnt about Acceleration / Continuation Grants - https://spacewarp.fvm.dev/ 
* If your project was created as part of an event or hackathon: Project was made during [ETHforAll](https://devfolio.co/projects/greenade-refi-data-dao-73e7) https://devfolio.co/projects/greenade-refi-data-dao-73e7

**Comment by eshon** [comment]
Hi @Greenade-refi! This is very cool project. I checked with the Filecoin Green team, and they made the following suggestion: 
> They could build out support for some of the carbon offset interoperability solutions we've been working on and enter it in our hackathon: https://sbsboston.devpost.com/

If you have any questions regarding this, reach out to me on Filecoin Slack ([Slack invite](https://filecoin.io/slack), then DM @eshon) and I can put you in touch with the Filecoin Green team!

**Comment by Greenade-refi** [comment]
That's great news! We will definitely be participating in sbsboston and are looking forward to connecting with the team at Filecoin Green :) Pinging you on Slack.

**Comment by ErinOCon** [comment]
Hi @Greenade-refi, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time, but are wishing you all the best as you continue to build!
