### ISSUE TITLE
Next Step Microgrant: npx create-fvm-dapp

### ISSUE THREAD

**Issue by akhileshthite** [filecoin-project/devgrants#1430]
### The project:
create-fvm-dapp is a full-stack starter template with React & Hardhat to develop, deploy, and test Solidity smart contracts on the FEVM network. The starter kit also includes pre-installed `web3.storage`, `tailwindcss`, `web3.js`, etc. packages.

![Fo8I61GWAAEJggy](https://user-images.githubusercontent.com/68826419/221245034-1b2c023d-6407-4718-9355-18a0034177fd.png)

### The problem:
Currently, there's no full-stack developer tooling starter kit built for FEVM, and that makes it harder for developers to build dapps. Mostly FEVM developers are using remix to deploy their smart contracts, which is a time-consuming process and a bad practice to build a production-level dapp. create-fvm-dapp is the all-in-one solution for this problem.

### Achievement:
Only two days after its publication, this package has already received 547 downloads and has received overwhelming response on social media.
Tweet: https://twitter.com/akhileshthite_/status/1625528959101284354?s=20

### 2. Project links
  
Link to Github repo: https://github.com/akhileshthite/create-fvm-dapp
Link to demo or website: https://www.npmjs.com/package/create-fvm-dapp
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

The starter tool kit currently includes a simple smart contract template that can be easily replaced by developers for deployment of their own smart contracts on the Hyperspace testnet (and Filecoin Mainnet in March). Future plans include the addition of more templates such as ERC20, ERC721, ERC1155, DAOs, and data DAOs.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |       Full-stack templates               |                Add more full-stack templates  such as ERC20, ERC721, DataDAOs, etc. to improve DX                                         |            ~ 3 weeks                | 
| 2.     |          Education & awareness              |                       Publish articles,  create content (videos), and conduct workshops.                                   |             ~ 2 weeks             | 
| 3.     |       Mainnet deployment                  |         Add  FVM mainnet deployment support              |          ~ 1 week                 | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
-> Not intentionally. I submitted the project at ETHforAll Hackathon (it was around that same time period) to get feedback and raise awareness.
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

| Name | Email | GitHub | Role |
| :---   | :------                 | :---    | :--- | 
| Akhilesh Thite | akhileshthite@hotmail.com | https://github.com/akhileshthite | Main developer |

* How did you learn about our microgrant program?
 https://spacewarp.fvm.dev/
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
 N/A
  * Please link to your hackathon submission
 N/A

**Comment by ErinOCon** [comment]
Hi @akhileshthite, thank you for your proposal and for your patience. I know our review has required a considerable amount of time! Unfortunately, we will not be moving forward with a grant. Wishing you all the best as you continue building!
