### ISSUE TITLE
Grant Application: SubQuery Data Indexing Support for Filecoin 🚀

### ISSUE THREAD

**Issue by brittanyseales** [filecoin-project/devgrants#1432]
# Open Grant Proposal: `Project Title`

**Name of Project:** `SubQuery`

**Proposal Category:** `devtools-libraries`

**Proposer:** `brittanyseales`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** 

Yes.

SubQuery’s SDK is open source under the Apache 2.0 Licence. This SDK provides everything that you need to build and run an indexer for your dApp. You can see detailed instructions on how you can run [SubQuery locally in our documentation](https://academy.subquery.network/run_publish/run.html). The SubQuery Network will be open source under the same licence.

The SubQuery managed service is a hosted environment that is closed source and run privately by SubQuery. It does not have any features that customers can’t do themselves and runs the same open source versions of SubQuery SDK.

# Project Description

Almost every blockchain has a need to process and query data, however everyone knows that a core weakness of blockchain data is that the processing and query performance is extremely inefficient. SubQuery is an open source platform that solves that and provides a more performant and feature-rich alternative to The Graph.

SubQuery is your own custom open-source API between blockchain data and your dApps and tools. Our indexer works on Polkadot, Substrate, Avalanche, Cosmos, and Algorand chains, and then provides that data for developers to use for a wide array of projects (wallets, explorers, custom chains, or any other decentralised app). We provide a similar project to The Graph, but focus on non-eth chains. SubQuery’s mission is to make decentralised data more accessible.

We have three products:

- An open source SDK, which includes the instructions on how any Indexer should traverse the blockchain, what data to collect, and how it should be shown to users. 
- A Managed Service, which provides enterprise level hosting (99.9% uptime) for SubQuery projects by our team (with a generous free tier)
- A decentralised SubQuery Network. With the testnet just finished, we are about to launch a first version of the SubQuery Network. The SubQuery Network is our effort to move towards a decentralised and tokenised network in order to ensure no single point of failure and superior performance for SubQuery. It will support Filecoin from genesis and will encourage as many participants in the process as possible.

In our view, the Filecoin ecosystem is poised for an extreme growth period and it requires tools such as SubQuery in order to thrive.

## Value

SubQuery is a flexible, cross-chain indexing service similar to the Graph. There are endless possibilities for the variety of data sources that can be analysed and served using SubQuery. 

We build SubQuery with the following key competitive advantages in mind:

- Faster than others. We’re focusing on making SubQuery faster than other solutions with advanced indexing caches and precomputed indices saving developers time, our solution is fast to set-up, fast to manage, and fast to index. 
- More Flexible and Feature rich. SubQuery is a scaffold for building custom APIs and we provide additional features like GraphQL subscriptions, automated historical tracking, and more.
- Open. Customers have already extended our open source SDK to suit their own custom implementation.
- Universal. A universal infrastructure stack bringing communities together, developers now have a tool to search, sort, filter and query any data for their app across multiple blockchains.

We build an advanced developer tool that makes a technically challenging process easy. As a result, the sole measure of our success is the number of developers and projects in BNB using our tool to index data for their dApp/service. We are confident we can build the best indexer tool, with unmatched features, faster performance, and higher reliability. However, if we aren’t able to make the BNB ecosystem aware of SubQuery and guide them through the learning curve on how to use it, then we will fail at onboarding developers to use our tool. That’s why we focus on more than just product development, we put a lot of effort into business development, developer education, and ecosystem outreach to achieve this, and you can see this represented in the above milestones. 

## Deliverables

This funding grant aims to help us to build the next stage of our vision for SubQuery to become a multi-chain tool - SubQuery support encompassing Filecoin through full testing and implementation.

- The SubQuery SDK will be open-sourced / free for the Filecoin community and (test) network agnostic
- The SubQuery Hosted Service will be available for free for all customers on Filecoin  (up to a basic level with paid enterprise level support for larger ones to cover infrastructure costs)
- The decentralised SubQuery Network will be fully compatible with Filecoin
- We will deliver a considerable amount of developer documentation, tutorials, and example projects that will help developers in your ecosystem build
- Our BD teams will reach out to multiple developers in your ecosystem make themselves available for any demos or workshops

Milestones = 1
Time to complete milestone = 9 days
Total cost (USD) = $8,100

**See milestones and cost projection table for full breakdown:** https://docs.google.com/document/d/198Hwy7BxIbhO4tIb8x2Q7_aoSxS35yubz86TY3PE_s4/edit#

## Development Roadmap

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-834b8fb4-7fff-d75a-d085-bc4e9ef3ea97"><div dir="ltr" style="margin-left:0pt;" align="left">

Create a new data source processor for Filecoin | 3
Define new manifest structure and update SubQuery CLI | 1
Import and manage Filecoin ABIs | 1
Create basic documentation for Filecoin support | 1
Create end to end developer tutorial (written and video) | 1
Project Management | 2
Milestone 1 Time | 9

</div></b>

**Milestone 1: Resources**
Resource | Quantity (Days) | Day Rate (USD) | Cost (USD)
Engineers | 7 | $900 | $6,300
Project Managers | 2 | $900 | $1,800
Milestone 1 Cost (USD) | $8,100

**See milestones and cost projection table for full breakdown:** https://docs.google.com/document/d/198Hwy7BxIbhO4tIb8x2Q7_aoSxS35yubz86TY3PE_s4/edit#

</div></b>

## Total Budget Requested

Milestone 1 Cost (USD) | $8,100

**See milestones and cost projection table for full breakdown:** https://docs.google.com/document/d/198Hwy7BxIbhO4tIb8x2Q7_aoSxS35yubz86TY3PE_s4/edit#

## Maintenance and Upgrade Plans

The best part about SubQuery is that we have an entire team focused on building and maintaining the best indexing tool so that you don’t have to build your own custom solution. We’re constantly working on performance improvements and adding new features as well as building our own decentralised network which will support filecoin projects from the outset.

# Team

We’re a high performing team that has rapidly grown to more than 20 members spread across New Zealand, Singapore and Portugal. Mostly software developers, devOps engineers, and business development staff with a track record of experience in extending our tooling to different layer 1 chains.

Sam Zou - CEO (https://www.linkedin.com/in/sam-zou-5b8169a/)
Entrepreneur, Investors and more than 20 years  of IT experience specialising in infrastructure and cloud service design

Ian He - CTO (https://www.linkedin.com/in/yin-he-7a266345/)
Blockchain Architect, Contributor of polkadot-js, Early adopter of substrate technology and won second place in the first polkadot hackathon.

James Bayly - COO (https://www.linkedin.com/in/james-bayly/)
Software engineer with experience creating and growing 3 startups over the past 5 years

# Additional Information

**Email Address:** brittany.seales@subquery.network

**Full Proposal here:** https://docs.google.com/document/d/198Hwy7BxIbhO4tIb8x2Q7_aoSxS35yubz86TY3PE_s4/edit#

Read through https://blog.subquery.network/ for all partnership announcements.

Chains we support:
All Substrate and Polkadot/Kusama chains
Avalanche
Cosmos (both CosmWasm and Ethermint)
Algorand
Near
Flare

**Comment by ErinOCon** [comment]
Hi @brittanyseales, thank you for your proposal! @jamesbayly, can you confirm this proposal is being submitted on behalf of your team? Once confirmed, we will circle back to discuss next steps!

**Comment by jamesbayly** [comment]
I can confirm that @brittanyseales  is submitting on behalf of our team!

**Comment by ErinOCon** [comment]
Thanks, @jamesbayly! @brittanyseales, I have sent you an email to discuss next steps.

**Comment by ErinOCon** [comment]
@brittanyseales This issue has been closed. Updates on this proposal will be sent from grants@fil.org.
