### ISSUE TITLE
Next Step Microgrant: Dora, the TipsetExplorer

### ISSUE THREAD

**Issue by zediogoviana** [filecoin-project/devgrants#1433]
### 1. What is your project, and what problem does it solve? (max 100 words)
This project, "Dora, The TipsetExplorer" is a The Graph-like event indexer, for the FEVM, where you specify Handlers (files written/generated in Elixir that instructs Dora on how to deal with events) by Smart Contract or default Handlers for a specific Event. 

At the moment there is nothing similar to this Project working on FEVM (Hyperspace, at least), so we decided to build our own. It relies on the current RPC Node API to obtain logs (events) information.

### 2. Project links
  
Link to Github repo: https://github.com/finiam/dora-the-tipset-explorer
Link to demo or website: https://dora-the-tipset-explorer.fly.dev/ (Example indexer deployed)
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
This project relies on an RPC Node to retrieve logs (Events) emitted by Smart Contracts deployed on FVM. These Events can then be used within dApps being developed for this chain!

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
There are, a couple of ideas in the pipeline, that we believe would be a great addition to this Project (after the Hakcathon) and the FEVM as a whole.
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | Fixes and improvents | Fixes and improvements to some parts of the code that were specifically made during the Hackathon | 2 weeks |
| 2.     | API Auth Mechanism  | Implement an authentication mechanism like API Keys to avoid the service being spammed by unwanted requests.                                                            | 1 month | 
| 3.     | Make an App generator | Check [this part of the Project's README](https://github.com/finiam/dora-the-tipset-explorer#generating-a-new-indexer-app) for more info. |  2 months                          | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  * https://ethglobal.com/showcase/dora-the-tipsetexplorer-uwg3o
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  * José Diogo:
    [diogo@finiam.com](mailto:diogo@finiam.com)
    https://github.com/zediogoviana
    role: Developer
* How did you learn about our microgrant program?
  * I got an email from Niki Gokani, after the "FVM Space Warp" Hackathon that mentioned this.
* If your project was created as part of an event or hackathon:
  * What was the name of the event?
    * FVM Space Warp
  * Please link to your hackathon submission
    * https://ethglobal.com/showcase/dora-the-tipsetexplorer-uwg3o

**Comment by ErinOCon** [comment]
Hi @zediogoviana, thank you for your proposal and for your patience. I know our review has required a considerable amount of time! Unfortunately, we will not be moving forward with a grant. Wishing you all the best as you continue building!
