### ISSUE TITLE
WIP Next Step Microgrant: <Your Title Here>

### ISSUE THREAD

**Issue by Man-Jain** [filecoin-project/devgrants#1435]
### 2. Project links
  
Link to Github repo:
Link to demo or website:
License:

  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |                         |                                                            |                            | 
| 2.     |                         |                                                            |                            | 
| 3.     |                         |                                                            |                            | 
| 4.     |                         |                                                            |                            | 

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by eshon** [comment]
Closing because this is an empty proposal
