### ISSUE TITLE
Next Step Microgrant:Alithis: Ai Decentralized Traceability

### ISSUE THREAD

**Issue by elivasquezhdz** [filecoin-project/devgrants#1437]
### 1. What is your project, and what problem does it solve? (max 100 words)
Alithis, we  promote AI safety by ensuring machine learning models and data traceability using blockchain. We're proposing means to map datasets and models resulting in a comprehensive relation of the data, its model process, and storing the data persistently on Filecoin.

### 2. Project links
  
[Link to Github repo:](https://github.com/elivasquezhdz/alithis) 
[Link to website:](https://alithispage-dcf298.spheron.app/)
[Link to demo:](https://alithis-mnist.elfx.repl.co/)
[License:  MIT license](https://github.com/elivasquezhdz/alithis/blob/main/LICENSE.MD)

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
* Datasets and models are uploaded to persistent storage providers (Lighthouse) and IPFS
* Smart contracts will be deployed to FEVM mainet

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
 **Yes**
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |  Whitepaper                       |    Research among current machine learning models and datasets practices will be documented and decentralized solutions will be presented in such document                                                        |     2 ~ 3 weeks                       | 
| 2.     |    Mnist demo deployed in FEVM                     |  There is a current demo for Alithis deployed on Goerli (see links) it is crucial fo deploy such demo on FEVM mainet and deliver it along with the whitepaper                                                          |           3 weeks                 | 
| 3.     |     Demo APIs                    | Public APIs will de delivered to ensure datasets and ML model traceability                                                            |           6 ~ 7 weeks                 | 
| 4.     |  Public presentations and meetups                       | Alithis founder will seek to promote the project in meetups to promote user adoption and integration with data stakeholders                                                           |     6~8 weeks                       | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
 **Yes**

  
### 6. Does your proposal comply with our Community Code of Conduct?
 **Yes**

### 7. Links and submissions
**Yes** Alithis was born at ETHGlobal FVM Space Warp
[project page](https://ethglobal.com/showcase/alithis-6s995)

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
    * Eli Vasquez, eli.vasquezhdz@gmail, elivasquezhdz, Main dev
* How did you learn about our microgrant program?
    * At the Spacewarp page 
* If your project was created as part of an event or hackathon:
    * Alithis was born at ETHGlobal FVM Space Warp
    * [ hackathon submission](https://ethglobal.com/showcase/alithis-6s995)

**Comment by trruckerfling** [comment]
hey eli! super interested in this project and to dedicate a grant to it. We have some questions/asks on the roadmap for alithis before we proceed:
- is it possible to integrate FVM for storage after minting the NFT? we have a [storage contract template](https://github.com/filecoin-project/fevm-hardhat-kit/tree/main/contracts/basic-deal-client) that can be easily integrated to your stack 
- do you have plans for an easy GUI/frontend to view the minted datasets? the current demo link shows only description

**Comment by elivasquezhdz** [comment]
Thanks for the follow up!

1. Yes it is posible to use FVM storage after the minting. Although I've been considering on not using NFTs only persistent storage.
2. Yes, I will provide a GUI to view the datasets, this demo works with the mnist dataset [Alithis Mnist Demo](https://alithis-mnist.elfx.repl.co/) (but this demo only verifies the dataset it does not visualize it.
3. Yes, Alithis will benefit from filecoin storage feature, it will provide the tooling to view and verify any dataset.
4. I did deploy the [Alithis Mnist Contract](https://filfox.info/en/address/0xcaeabb8ad81096a5cf5ee6951bf4a05aeb5fcfba) on FEVM, and the tooling mentioned above will be deployed on mainnet.

Please let me know your thoughts or how to follow up for next steps.

**Comment by ErinOCon** [comment]
HI @elivasquezhdz, thank you for all of your patience with our review process. Unfortunately, we will not be moving forward with a grant at this time. While this is a really interesting project, we are currently prioritizing grants that are more specific / unique to Filecoin. 

Wishing you the best of luck as you continue building!
