### ISSUE TITLE
Next Step Microgrant: <Your Title Here>

### ISSUE THREAD

**Issue by FlameLaunch** [filecoin-project/devgrants#1438]
### 1. What is your project, and what problem does it solve? (max 100 words)
FLAME LAUNCH is a decentralized launch platform based on the Filecoin ecosystem, which integrates internet social graphs and chain asset data to provide multiple functions such as identification, rating, and adaptation. In this way, investors can obtain comprehensive project information, so as to make more prudent investment decisions.
### 2. Project links
  
FLAME LAUNCH links:
Twitter: https://twitter.com/FlameLaunch
Telegram: https://t.me/FlameLaunch
Discord: https://discord.gg/7VsNUcavBw
Youtube:https://www.youtube.com/@FlameLaunch
Medium: https://medium.com/@FlameLaunch
Official website：https://www.flamelaunch.com

### 3. a) How is IPFS, Filecoin, or related technology used in this project?

FLAME Launch is a platform for creating and organizing token-driven communities, supported by Filecoin.
FLAME Launch and Filecoin form a perfect symbiotic relationship. The Filecoin platform is centered around data storage and retrieval, and these two features form the protocol's Layer0, while the introduction of smart contracts brings programmability and compatibility to Filecoin's Layer1, ushering in a new stage of development for the ecosystem. The Filecoin ecosystem provides the infrastructure required for FLAME Launch, while FLAME Launch brings more vitality and vitality to the Filecoin ecosystem, attracting more quality developers and investors.
FLAME Launch and Filecoin form a powerful blockchain ecosystem. FLAME Launch provides more opportunities and avenues for developers and investors, driving the development of blockchain technology and DeFi ecosystem. This relationship will continue to help Filecoin and FLAME Launch in their future development and expansion, bringing more value and returns to their users and communities.
###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
  yes
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
The funds obtained will be used for the later construction and setup of Flame Launch, including recruitment of personnel, improvement of functions, and technological research and development.
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
2023 Q1
Launch of Flame Launch website and MVP
Development and private sale of FLT token
Launch of Flame Launch Launchpad
Public sale of FLT token on Launchpad
Acceptance of applications for Launchpad projects
2023 Q3
Exchange Program of Flame Launch
DAO Governance Model
2023 Q2
FLT Hot Launch Platform
New Projects
NFT Launcher
Token Ownership Platform
Launch of WEB3.0/Metaverse/DEFI three major boards
2023 Q4
Token Burn to take effect in Q1 of 2024
Launch of Combat Platform
Enhancement of DAO Governance
2024 Q1
Opening of One-stop Crowdfunding Platform Entrance with KYC No-sign Verification
2024 Q2
Launch of IDO Token Encryption List Automated Airdrop, Candy, Red Packet Plate IDO Plate Self-application Listing DEX Release Protection Agreement
### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
 yes,We agree.
  
### 6. Does your proposal comply with our Community Code of Conduct?
We agree to fully comply with your requirements.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
No, I'm sorry.
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
George S Krebs(Flame Launch CEO):optve9zs70b@claimab.com
Dennis L Brodsky(Flame Launch CTO):61oxwhczfkp@thrubay.com
Heather G Montgomery(Flame Launch COO):t9bxncumn6g@thrubay.com
* How did you learn about our microgrant program?

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @FlameLaunch, thank you for your proposal and for your patience. I know our review has required a considerable amount of time! Unfortunately, we will not be moving forward with a grant. Wishing you all the best as you continue building!
