### ISSUE TITLE
Open Grant Proposal: Gandalf Protocol Implementation on FVM

### ISSUE THREAD

**Issue by Rishikeshk9** [filecoin-project/devgrants#1440]
# Open Grant Proposal: Gandalf Protocol Implementation on FVM

**Name of Project: Gandalf Protocol Implementation on FVM**

**Proposal Category:** core-dev,devtools-libraries

**Proposer**: @Rishikeshk9

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** Yes

# Project Description

Gandalf Protocol is a highly secure and encrypted way of storing data on the Flow blockchain. However, the project is currently implemented on the Flow Blockchain, and the grant proposal is for the Filecoin Virtual Machine (FVM) Blockchain.

The primary goal of this grant is to create native FVM actors for Gandalf Protocol to enable the encryption of files and IPFS links, improving data privacy for specific organizations. Currently, storing encrypted data on the Filecoin network is challenging, as encrypting data requires a specific encryption key that must be securely stored. If the key is leaked, the data can be decrypted without the user's consent, compromising its privacy.

The proposed solution will save a specific encryption key on the user's storage, which will be decrypted with a secret key stored inside Gandalf Protocol, managed by a Distributed Key Generation (DKG) algorithm. Multiple nodes will generate this secret key when required, enhancing the security of the encryption and decryption process.

The Gandalf Protocol can be used in various scenarios where data needs to be private, such as a recording or a locked NFT that can only be shared once access to that data is granted.

## Value

The project provides a highly secure method of storing data on the FVM blockchain, ensuring data privacy for specific organizations. The native FVM actors for Gandalf Protocol will enable encryption of files and IPFS links, making it an ideal solution for Dapps that require secure and efficient data storage on the Filecoin network.

The benefits of this project include improved data privacy, enhanced security, and reliable encryption and decryption processes. Failure to implement this solution could result in data breaches, loss of trust from clients, and a decrease in the adoption of the Filecoin network.

## Architecture

![Gandalf Protocol](https://raw.githubusercontent.com/Rishikeshk9/Gandalf/main/Gandalf.png)

## Deliverables

The final deliverable for this project will be native FVM actors for Gandalf Protocol, which will enable the encryption of files and IPFS links. The software will provide an interface for users to encrypt and decrypt their files and IPFS links using the secret key stored in Gandalf Protocol. The software will also provide an API that can be used by Dapps to encrypt and decrypt data.

## Development Roadmap

The development work for this project will be broken up into the following milestones:

### **Milestone 1: Research and Planning**

Perform research on the best practices for implementing the Gandalf Protocol on the FVM blockchain
Plan the development roadmap and milestones for the project

**Team Members: 2 Developers**

**Budget: $15,000**

**Timeline: 1 month**

### **Milestone 2: Native FVM actors for Gandalf Protocol**

Develop and test the native FVM actors for Gandalf Protocol that will enable encryption of files and IPFS links
Integrate the secret key storage mechanism using the DKG algorithm
Implement the software interface for users to encrypt and decrypt their files and IPFS links

**Team Members: 3 Developers**

**Budget: $25,000**

**Timeline: 2 months**

### **Milestone 3: API Development and Testing**

Develop and test the API that can be used by Dapps to encrypt and decrypt data
Conduct extensive testing to ensure the software is secure and reliable

**Team Members: 2 Developers**

**Budget: $15,000**

**Timeline: 1 month**

### Total Budget Requested

The total budget requested for this project is **$55,000**

## Team Member

- Rushikesh Kardile - [Github](https://github.com/Rishikeshk9), [LinkedIn](https://www.linkedin.com/in/rushikeshkardile)

## Team code repositories

- [Gandalf Frontend](https://github.com/Rishikeshk9/Gandalf)
- [Gandalf Backend](https://github.com/Rishikeshk9/gandalf-backend)

## Protocol Website 
- https://gandalf-protocol.vercel.app (Currently on Flow)
## Additional Information

- [Email](mailto:rushikeshkardile9@gmail.com)

**Comment by ErinOCon** [comment]
Hi @Rishikeshk9, thank you for your proposal. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
