### ISSUE TITLE
Next Step Microgrant: Cruzo Cards

### ISSUE THREAD

**Issue by modus77** [filecoin-project/devgrants#1441]
### 1. What is your project, and what problem does it solve? (max 100 words)
Multi-chain NFT marketplace & Web3 AI-powered platform for digital emotions. Sell, Buy, Gift or Store your NFT greetings in Blockchain.

### 2. Project links
  
Link to Github repo: https://github.com/cruzocards/
Link to demo or website: https://cruzo.cards/
License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
Frontend: Next.js, SCSS, ethers.js, IPSF 
Backend: Nest.js (REST API), ethers.js, Postgres, Redis, Bull, S3, IPSF 
Blockchain (smart contracts): Solidity 
Indexer: Go Ethereum

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
We will give us an opportunity for our users to use FVM together with IPSF. We will extend the variety of fast and reliable networks for minting NFTs with low gas commissions. This gives us a competitive advantage among NFT marketplaces as well as a good reputation because Filecoin is one of the trusted leaders in the industry.

1 Testnet integration
We will deploy or smart contracts into Filecoin Huperspace testnet. We will Test all functionality: Minting. Put on sale. Remove from sale. Transfer. Purchase. Burn. Transactions speed. 
Time frame: 1,5 weeks

2 Mainnet integration
We will deploy or smart contracts into Filecoin Mainnet. We will test on mainnet all functionality: Minting. Put on sale. Remove from sale. Transfer. Purchase. Burn. Transactions speed. 
Time frame: 1,5 weeks

3 Users tests, CusDev, Reports
We will announce to our community the new integration with FVM and will ask our users to test all functionality. We will collect reports and see the result
Time frame: 2 months

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes, we agree to share updates in this Github issue
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
No
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Denis Stepanov, Founder - dsa@cruzo.io - modus77
Nikita Korshunov - Full-stack developer - nka@cruzo.io - kewka
Timur Makarov - Full-stak developer - tmi@cruzo.io - PowderDev
Artem Kovalenko - Blockchain developer -akv@cruzo.io - suNrisEinMyeYes

* How did you learn about our microgrant program?
From Filecoin team, Erin O'Connor

* If your project was created as part of an event or hackathon:
No

* Please link to your hackathon submission
 No

**Comment by ErinOCon** [comment]
Hi @modus77, thank you for your proposal and for your patience. I know our review has required a considerable amount of time! Unfortunately, we will not be moving forward with a grant. Wishing you all the best as you continue building!
