### ISSUE TITLE
Next Step Microgrant: OpenBiSea NFT marketplace

### ISSUE THREAD

**Issue by oleksiivinogradov** [filecoin-project/devgrants#1442]
### 1. What is your project, and what problem does it solve? (max 100 words)
[OpenBiSea.io](http://openbisea.io/) - Game Studio and Multi-chain NFT auctions in all-in-one place to cut any NFT deal in a few clicks with a $200M fund in $OBS. 

### 2. Project links
  
Link to Github repo: https://github.com/oleksiivinogradov/
Link to demo or website: https://app.openbisea.com/
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

https://app.openbisea.com/ - before NFT mint, we upload image and then JSON

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)

Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
  
Integration all smart contracts to:
https://app.openbisea.com/
https://t.me/openbisea_bot 

Announces and marketing in social channels:
https://twitter.com/openbisea
https://t.me/openbisea_en
https://discord.gg/bwbpgp9jhS

Post integration campaign, add liquidity to MultiSwap, farm OBS, sell/buy NFT

1 week Smart contracts deploy - $2k 
1 week UI (web, android app, bot) update - $1k
1 month farm OBS campaign $2k

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

https://openbisea.io/#team

* How did you learn about our microgrant program?

Filecoin team

**Comment by oleksiivinogradov** [comment]
any updates?

**Comment by ErinOCon** [comment]
Hi @oleksiivinogradov, thank you for your proposal and for your patience. I know our review has required a considerable amount of time! Unfortunately, we will not be moving forward with a grant. Wishing you all the best as you continue building!
