### ISSUE TITLE
Next Step Microgrant: Spheron Decentralized Bundlr

### ISSUE THREAD

**Issue by rekpero** [filecoin-project/devgrants#1443]
### 1. What is your project, and what problem does it solve? (max 100 words)

Our project aims to solve the problem of unattractive small-sized deals on Filecoin, which makes it economically unfeasible for Storage Providers to store them.

We propose a decentralized deal bundler that aggregates these small deals into larger ones in a transparent and trustless manner, making it more appealing for Storage Providers to pick them up.

With the implementation of PoDSI, clients can also verify the inclusion of their sub-piece data in the bigger deal.

### 2. Project links
  
Link to Github repo: https://github.com/orgs/spheronFdn (Yet to start, will update once the repos are created)
Link to demo or website: https://spheron.network
License: Apache-2
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

Using IPFS as a file storage service, we aim to make deals more economical for Filecoin SPs while still keeping the feasibility and accessibility of uploading smaller files for users.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

The proposed solution involves creating an
- Upload Service
- Deal Bundling System
- Bundler Node
- Proof of Upload,
- Spheron SDK integration for simple upload to IPFS and start the filecoin deal creation.

The system will be tested and debugged to ensure functionality.

![grant-image](https://user-images.githubusercontent.com/34746546/233560754-2e4c7e92-b0db-4a98-8580-00f10b9c09ae.jpeg)

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | Upload Service | Allow users to upload their CAR files or upload any file then convert into CAR file, save in DB | 4 Days | 
| 2.     | Deal Bundling | Create bundle or add file/files to existing bundle by sending API request to the bundlr | 4 Days | 
| 3.     |  Bundler Node | Off-Chain service that monitors deals and bundles in DB, Creates an aggregated CAR file and data segment index for SP | 1 week | 
| 4.     |  Proof of Upload | Generate and Expose proofs for file inclusion in Bundle | 4 Days | 
| 5.     |  Deal Creation with SP | Connect with SP to create deals for bundles and update DB with the deal information | 4 Days | 
| 6.     |  AggrFil SDK | Create functions in SDK to interact with bundling system | 4 Days | 
| 7.     |  Testing and Debugging | Testing and Debugging System | 5 Days | 

_The expected timeline for the first MVP is 3 weeks which will contain a deal creation bot and an endpoint to create the deal. We expect to finish the project after testing and SDK creation in 6 weeks._

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

#### For each team member(s), please list name, email, Github account, and role in the project.
- Mitrasish Mukherjee - Project owner and manager - [rekpero](https://github.com/rekpero)
- Prashant Maurya - Project owner - [izrake](https://github.com/izrake)
- Manank Patni - Blockchain Developer - [Man-jain](https://github.com/Man-Jain)

#### How did you learn about our microgrant program?
Filecoin Slack - fvm-foundry-f1

**Comment by ErinOCon** [comment]
Hi @rekpero, I have sent an email to your team members to discuss next steps. If you would like to be included, please feel welcome to include your preferred email address here.

**Comment by rekpero** [comment]
> Hi @rekpero, I have sent an email to your team members to discuss next steps. If you would like to be included, please feel welcome to include your preferred email address here.

Please include me `mitrasish@spheron.network` and cc Prashant as well `prashant@spheron.network`

**Comment by ErinOCon** [comment]
You got it!

**Comment by ErinOCon** [comment]
Hi @rekpero, do you have an update available for this project? Please note that we are looking for the following for completed projects:

- A fully working user-facing demo with nice UX that anyone can easily use
- Deployment to Filecoin mainnet + a testnet
- Interesting use of FVM, especially what's unique to Filecoin (for example, via the Filecoin Solidity API, FVM use cases, or Bacalhau x FVM, etc.)

Let me know of any questions!

**Comment by ErinOCon** [comment]
Hi @rekpero , do you have an update regarding your project progress?
