### ISSUE TITLE
Open Grant Proposal: Web3 Games School Stage 1

### ISSUE THREAD

**Issue by 8bitpal** [filecoin-project/devgrants#1445]
# Open Grant Proposal: `Web3 Games School Stage 1`

**Name of Project:** Web3 Games School Stage 1
**Proposal Category:** Docs
**Proposer:** 8bitpal
**Technical Sponsor:** Dietrich Ayala
**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** Yes

# Project Description
One of the key markets for any web3 project is Gaming. Game developers tend to be exposed to content and targeting differently from web2 developers. The Web3 Games School is designed to lay the foundation for a funnel of game developers building with p2p technology from the ground up, driving adoption of FVM, libp2p, and IPFS.

We want to provide practical learning materials to improve the on-boarding of new developers to Filecoin and FVM. The content aims to showcase a simple game which incorporates several web3 features. Students will initially consider the design requirements for extending a specific game concept and the implications of realizing them in a web3 context. They will then conduct the basic game implementation and be challenged to practically extend it by developing level creation and marketplace features using Filecoin and the FVM.

The project is designed to stand and add value on its own, but with the potential to later be extended into a more complete academy experience.

## Value
The project's content is designed to attract game developers and introduce them to development with FVM. The overarching goal is to help FVM compete better in the L1 landscape and unlock a new developer demographic.

Students will benefit from following a predefined, practical learning pathway, gaining hands-on experience of valuable techniques and being rewarded by achieving concrete objectives. The knowledge gained from the learning materials will have clear transferable value to their own future projects. The materials will also serve to raise the profile of Filecoin, FVM, and the utility of DataDAOs, establishing strong engagement with these tools in the students.

As a step up from merely theoretical learning, there is the possibility that some students will be overwhelmed by the need to perform in a relatively "high pressure" context. The project involves the creation of various tools which need to work well together. Establishing a clear path for the students to follow is essential.

Demonstrating the viability of the proposed tools in advance of guiding students through their own implementation process is key, so any issues when creating pre-program versions could impact the project's execution. However, the identification of real-world challenges and their solutions can also deepen the learning opportunities offered by the final project.

## Deliverables
The project will deliver a program of educational content hosted on a dedicated landing page, designed to familiarize developers with Filecoin and FVM. The game development process provided by the guided tutorial offers a concrete use case example to teach devs how to implement a variety of system features. The learning journey consists of two modules:
In Module 1, the learners create a simple game including a level editor. This part of the content does not focus on web3, so we will keep the game simple and the implementation short: the labyrinth level will be stored as a grid-based map and the game will run in a browser environment. A labyrinth works only if visibility conditions are met; therefore, the easiest solution is to implement a first-person view. This can be achieved relatively quickly with a ray casting algorithm, given the level is a grid-based one-floor map without need for textures.
In Module 2, the learners create a simple trading gallery where a community user base can upload or download levels created with the level editor. This part will focus on web3 and therefore extend the base game. A DataDAO will manage the upload and download of the levels, and the trading gallery will serve as the user interface. Note that such a trading gallery concept can be used with almost any other game or game asset, but in order to streamline the experience and keep things simple we will not attempt a general trading gallery. Instead it will be integrated within the game created in module 1.

The deliverables are as follows:
Educational content (Module 1 and 2) deployed on a free accessible portal website
A github repository with functioning code for the portal
A github repository with functioning code for the content (2 modules)
A github repository with forkable and functioning game example for FVM

## Development Roadmap

Milestone 1: Didactical concept and curriculum
B9Lab will initiate the project with an analysis of your desired target group by our team's didactics expert, identifying the prospective learners and evaluating their needs and requirements. Based on this analysis, we will design a learning journey which follows a logical and accessible structure to ensure a positive experience which focuses on practical orientation.

Our three-person content production team will begin work on the respective training elements through conceptualisation and research into basic game development with web3 implications. They will screen any existing material and documentation, and explore the use of appropriate tools and code. 

Combining these research results with the didactic analysis, the team will then develop a final curriculum covering all aspects recognised as important for the user’s learning process.

Estimated costs and duration: $22.5k over a 2-week period.

Milestone 2: Use case development
With the concept and curriculum in place, our three-person content production team will develop a guided tutorial providing a development use case that includes curated and original code and text content. Text-based materials will undergo language revision and review from our technical editor for effectiveness and clarity, and visual elements will be produced by our graphic design specialist.

The program will consist of 2 modules:

Module 1 – Create a simple single-player labyrinth game
Students will begin by implementing a simple game from a curated example. They will go on to create a level editor for it. Module 1 will cover:

1. Introduction to grid-based game worlds.
2. Guided development of a level editor.
3. Undertaking a sample game implementation with graphics (eg voxel graphics).
4. Conclusions and further resources.

Module 2 – Extend the game to use web3 for multiplayer features
Students will now further extend the game from the previous section. They will create a simple "trading gallery" marketplace where a hypothetical community of game users can upload or download new levels generated with the level editor. Module 2 will cover:

1. Introduction to FVM.
2. Guided development of a trading gallery marketplace for user-created levels.
3. Guided implementation of a DataDAO to manage the tradable content.
4. Conclusions and further resources.

Estimated costs and duration: $58.8k over a 6-week period.

Milestone 3 – Portal 
The learning program will be released on a portal where users can independently navigate through the content. B9Lab will design and deliver this platform, with one team member responsible for portal design and two team members for the technical setup and implementation.

This will include:

Selection of portal framework: B9Lab will recommend a technical framework for the portal.
Feature specification: B9Lab will work out a set of basic features to be implemented on the platform.
Portal design: B9Lab will design a portal structure, defining the theme and layout.
Implementation: A staging environment will be set up and content will be implemented continuously before being pushed to production.

Estimated costs and duration: $18.7k over a 4-week period.

Indicative roadmap

Below is an indicative roadmap based on a 3 April 2023 start date. This is subject to change depending on the actual start date. 

![image](https://user-images.githubusercontent.com/473137/223089600-296436a5-e623-4c63-9077-4ff0dee6f7a5.png)

## Total Budget Requested

The total estimated budget to complete this project is $100k. 

| Phase | Costs (k$) |
| --------- | -------------- |
|1. Concept & Curriculum | 22.5 |
| 2. Use case development | 58.8 |
| 3. Portal | 18.7 |
| **Grand Total** | **100.0** |

## Maintenance and Upgrade Plans
This is Stage 1 in a project designed to evolve into the foundation for an instructor-supported academy, if the initial feedback and metrics are positive. The content and infrastructure is designed to be extended in the future to cover IPFS and libp2p.

# Team

## Team Member LinkedIn Profiles
Anil Öner: linkedin.com/in/murat-anil-oener
Xavier Leprete: linkedin.com/in/xavierlepretre
Rob Hitchens: linkedin.com/in/rob-hitchens
Andrew Critchley: linkedin.com/in/andrew-critchley-28010650
Citlali Mora Catlett: linkedin.com/in/citlali-mora-catlett
Maria Montes: N/A
Ibo Sy: linkedin.com/in/ibo-sy-43195176
Gioele Bonifetto: linkedin.com/in/gioele-b-8826a0a8
Ursula Neulinger: linkedin.com/in/ursula-neulinger

## Team Website
https://b9lab.com/

## Relevant Experience
B9Lab is the most experienced Adoption and Technical Marketing agency in web3. We have been working with various communities, protocols, and technologies since 2015.

Examples of our most recent work include the following:

2022 – We designed, built, and launched the Interchain Developer Academy for the Interchain Foundation.
B9Lab developed the content and structure, managed the support and execution, and led a marketing campaign which produced a 5-to-1 ratio of applicants to seats for the first cohort alone. The Academy is on course to onboard over 700 learners during its first year of operation. When polled, graduate responses have been very positive.
61% report that the Academy improved their professional situation, and 60% who applied for a role in the Cosmos Ecosystem were successful.
65% are currently working on Cosmos-related projects, 85% of whom in a coding or engineering capacity.
Post-program engagement remains very high: 96% continue to study Cosmos technology, and report they would enjoy access to further training materials.
2021 – We established the Developer Adoption strategy and Developer Portal for the Interchain Foundation and Polymesh.
2020 – We launched the Corda online training with a supported track.

Feel free to ask for more references.

## Team member profiles
Anil Murat Öner
Anil has worked with several programming languages and higher mathematics, and conducted research projects in ultra-high vacuum, electrotechnics, and computer-based simulations. Anil has taken a stake in embedded and scientific programming, as well as cryptography. At B9Lab, Anil is part of the core content creation team and has worked on projects for Tezos, Cosmos, EOS.IO, and Hyperledger.

Xavier Lepretre
From an early age, Xavier has been fascinated by software artistry. He's a senior blockchain engineer with expertise in Cosmos, Ethereum, and Corda. Within B9Lab he has trained thousands of software engineers in these technologies. Xavier likes to think adversarially when designing, is an advocate of clean coding and expressiveness and pays close attention to detail.

Rob Hitchens
Rob has worn many hats in his extensive IT career, including experience designing, constructing, implementing, and operating innovative software solutions, developing training programs, and supporting online education platforms. Rob has been dabbling in blockchain technology since the early days and quickly recognised the disruptive potential of smart contracts and decentralized apps. Since 2016 Rob has been absorbing all things related to smart contracts, solidity and supporting developers on their quest to master this technology.

Andrew Critchley
Andrew is a writer and editor in both technical and creative contexts. His journey into web3 includes experience with education, journalism, social media management and promotion, screenwriting and film production, industrial and 3D printing, and magazine and book publishing. If you don't find him writing something, he'll be reading something.

Citlali Mora Catlett
Citlali is a political scientist with a focus on international relations, international organizations, security policy, and economy. She has a MA in Political Science from the LMU Munich and has worked at international scholastic conferences providing educational experiences for students from around the world and assisted with university undergrad courses. At B9Lab, Citlali works across the content and delivery teams as a project manager and client liaison.

Maria Montes
Maria is a multidisciplinary designer with over 16 years of experience creating content for digital and print assets as well as visual design. Her experience includes creating motion graphics and 3D renderings for managing stage design projects. At B9Lab, she works collaboratively with the content production team in creating both intelligible and visually appealing representations of complex blockchain concepts, designing landing pages, components, and illustrations.

Ibo Sy
Ibo is a software engineer and entrepreneur with extensive experience in native desktop, web, and mobile application development. He has worked on 3D Virtual and Augmented Reality projects and has a knack for embedded systems. He has been delivering software projects for 14 years. As a founder, Ibo covers all aspects of B9Lab but has a particular interest in innovative infrastructure projects, for B9Lab and our clients.

Gioele Bonifetto
Gioele is a software engineer at B9Lab. He studied IT in high school and started working with startups as soon as he graduated, learning several programming languages and approaches to mobile and web development.

Ursula Neulinger
Uschi has been working for the last 19 years in learning and communication and has extensive experience in instructional design. She has run research projects with universities in Europe and Latin America and consulted for major companies regarding knowledge management and e-learning.

## Team code repositories
The following repositories showcase projects and materials from previous B9Lab collaborations:

https://tzmint.b9lab.com/
https://github.com/cosmos/sdk-tutorials
https://github.com/cosmos/sdk-tutorials/tree/master/academy
Polymesh: https://github.com/PolymeshAssociation/technical-content
Tezos:
Platform: https://github.com/b9lab/tezos-developer-platform
CSO
App: https://github.com/b9lab/tezos-cso-project
Smart Contract & wrapper: https://github.com/b9lab/tezos-app-project
Corda: https://github.com/corda/training.corda.net
B9Lab projects:
ETH faucet: https://github.com/b9lab/b9_faucet
Sample game project checkers: https://github.com/b9lab/react-checkers
EIP 1102 example: https://github.com/b9lab/eip-1102-example

# Additional Information
How did you learn about the Open Grants Program?
From Dietrich Ayala

Please provide the best email address for discussing the grant agreement and general next steps.
elias at b9lab.com | Elias Haase, Head of Strategy @B9Lab

**Comment by autonome** [comment]
I worked w/ B9 on this proposal. Game dev is large market and traditional learning journeys with certifications are 1) a key adoption vector expected by developers and 2) a sustainable industry in that space. Having this pathway for FVM as a cheat code for making it first choice for game devs would be a boost for FVM to onboard more developers. If B9 can bridge from this initial content into a paid course+certification it becomes an independently sustaining resource for the Filecoin ecosystem, and can grow course+certification offerings beyond games into other areas like data onboarding and management, and more.

**Comment by ErinOCon** [comment]
Hi @8bitpal, thank you for your patience with our review. Unfortunately, due to certain budget constraints, we will not be moving forward with a grant at this time. Should a collaboration opportunity arise in the future, we will be sure to keep your project work in mind!
