### ISSUE TITLE
Algovera FVM AI-Art Attribution Project Stable Diffusion Model

### ISSUE THREAD

**Issue by DeveloperAlly** [filecoin-project/devgrants#1451]
### 1. What is your project, and what problem does it solve? (max 100 words)
The FVM AI-Art Attribution Project is being run by the Bacalhau team and will be highlighted as one of the main use case on FEVM at the 14 March launch FVM mainnet launch. This project will provide new revenue streams for artists and an ethical new paradigm for AI-Art.

A core requirement of this project is to train a machine learning stable diffusion model based on an Artists work portfolio. 

This grant will cover [Algovera's](https://app.algovera.ai/) critical work of creating several ML models based on Artists work. These models will belong to the artist and be secured privately on the Bacalhau network and not be available publicly to ensure the security of an Artists work, however all other parts of this project will be open source, including how to create a similar model.

Technical sponsors: @DeveloperAlly @aronchick and @mishmosh 

### 2. Project links
  
Link to Github repo: https://github.com/bacalhau-project/AI-Art-Attribution
Link to demo or website: https://www.figma.com/file/SzYjdapUdn9fU4YoF76XGg/AI-art-Attribution-App?node-id=28%3A401&t=4i5DgYTIaBZDU5hm-0
License: MIT

As mentioned, these models will belong to the artist and be secured privately on the Bacalhau network and not be available publicly to ensure the security of an Artists work, however all other parts of this project will be open source, including documentation on how to create a similar model.
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

This project will be deployed to FVM mainnet on the 14th March. Bacalhau itself runs off IPFS and returns results as IPFS CIDs and stored on Estuary (IPFS  &  Filecoin)

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
- Build Model with 1 Artist to run on Bacalhau Cluster (2 days)
- Build multiple models from other artists input (up to 10) to run on Bacalhau Cluster (2 days)
- Document process (1 day)
- Provide ongoing support for models in the following 2 weeks as needed

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes - though the timeframe for this work is 1 week, with an additional week for maintenance and support.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
N/A https://app.algovera.ai/
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Team:

- Dr. Richard Blythman ([LinkedIn](https://www.linkedin.com/in/richard-blythman-64b2b948/), [Twitter](https://twitter.com/richardblythman))
- Hithesh Shaji ([LinkedIn](https://www.linkedin.com/in/hithesh-shaji-141274159))
- Mohamed Arshath ([LinkedIn](https://www.linkedin.com/in/mohamed-arshath-72152562))
- Casey Clifton ([LinkedIn](https://www.linkedin.com/in/casey-clifton-22b9b9147/))
- Jakub Smekal ([LinkedIn](https://www.linkedin.com/in/jakub-smekal/))

* How did you learn about our microgrant program?
 Bacalhau team
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  N/A
  * Please link to your hackathon submission
  N/A

### Relevant Experience
Dr. Richard Blythman is an AI developer with 5 years of experience in industry, university, and startups with companies. He did his PhD with Bell Labs, before working as a machine learning engineer with Huawei Technologies and Xperi Corporation across a number of different products (publishing 5 ML patents including generative AI products and transformers, as well as a number of research publications). He has worked on several AI startups and as a research fellow at Trinity College Dublin. 
Mohamed Arshath is a machine learning engineer. He has experience building numerous machine-learning models. Apart from building models, he has experience building backend APIs and managing the backend on the cloud using docker and Kubernetes.
Casey Clifton is a fullstack software developer and AI researcher. He has experience building a scaling numerous applications from AI medical imaging tools to a blockchain-powered rendering engine. He has also published research papers and completed industry and government R&D grants in these areas.

### Past Successful Project Delivery
Algovera has previously worked on several IPFS integrations:

Python libraries for IPFS ([ipfspy](https://github.com/AlgoveraAI/ipfspy))
Integrated IPFS with HuggingFace ([ipfsspec](https://github.com/AlgoveraAI/ipfsspec)) and ActiveLoop [Hub](https://github.com/AlgoveraAI/Hub)
Integrated IPFS with Ocean Protocol
Developed a decentralized hub for data scientists built on top of IPFS and Ocean Protocol
Integrated IPFS with JupyterLab ([jupyterlab_extensions](https://github.com/AlgoveraAI/jupyterlab_extensions))
Integrate Metamask, Ocean C2D and Lit Protocol with Streamlit ([streamlit-metamask](https://github.com/AlgoveraAI/streamlit-metamask), [streamlit-lit-nft](https://github.com/AlgoveraAI/streamlit-lit-nft))

We’ve also worked with a variety of compute protocols and workflow orchestrators:
Integrate [SAME project](https://github.com/SAME-Project/same-project/) with Ocean Protocol Compute-to-Data (C2D)
Integrated Kubeflow with Ocean Protocol Compute-to-Data (C2D)

**Comment by ErinOCon** [comment]
Hi @DeveloperAlly, this microgrant has been approved! We will send an email to confirm payment details.

**Comment by DeveloperAlly** [comment]
Thanks @ErinOCon FYI Richards github is @richardblythman

**Comment by richardblythman** [comment]
Hi @eshon @ErinOCon, We've successfully completed this grant (@DeveloperAlly can confirm). 
You can find the live app at https://www.waterlily.ai/
Would be great if you can start the process for approval and payment :)

**Comment by DeveloperAlly** [comment]
Hello folks! cc @ErinOCon 

Who would I reach out to about payment timelines? 

Richard hasn't received the remaining 4k on this one? 

Thanks!

**Comment by ErinOCon** [comment]
Thanks, @DeveloperAlly! 

@richardblythman, the work for the second payment has been reviewed and approved! Our team will be in touch by email with any questions.
