### ISSUE TITLE
Next Step Microgrant: Foliohouse - A decentralized dataset repository

### ISSUE THREAD

**Issue by bashybaranaba** [filecoin-project/devgrants#1452]
### 1. What is your project, and what problem does it solve? (max 100 words)

Foliohouse is a decentralized dataset repository that leverages the Filecoin Virtual Machine (VM) and Web3 Storage to provide secure, efficient and incentivized storage of high-quality datasets. With access control and a lightweight dataset loader, Foliohouse is an effective way for data scientists and machine learning practitioners to share, access, and use datasets.

### 2. Project links
  
Link to Github repo:  https://github.com/bashybaranaba/foliohouse
Link to demo or website: https://foliohouse-prototype.vercel.app/
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

- The general flow of the project's  design is as follows:
 A dataset creator uploads their dataset  -> The dataset file is encrypted and stored -> The smart contract defines the incentives and who can access the dataset -> The [foliohouse dataset loader](https://github.com/bashybaranaba/foliohouse-datasetloader) (a lightweight python library ) is used to access and interact with the dataset -> Each time a dataset is loaded for analysis, the creator of the dataset earns tokens which can be used to pay for storage on the platform

- **The Filecoin VM** brings user programmability to the Filecoin network, allowing the creation of the smart contract that governs the built-in token economy used in Foliohouse.
- **Web 3 storage**, on the other hand, stores data redundantly across multiple Filecoin miners and the public IPFS network and provides information about where the data is stored, and retrieves data by CID, ensuring that datasets are available and accessible to users.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
  Yes

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | Reworked smart contract  | Optimizing the smart contract governing the built-in token economy and access control functions and incorporating more features (eg. collaboration and community features )  | 3 weeks | 
| 2.     | Reworked  Node API |  Fixing existing issues with the API, and update the API to work with the newly added smart contract functions after the smart contract rework| 2 weeks | 
| 3.     | Reworked  dataset loader  library |  - Adding an access key param to the existing dataset_loader function for access control purposes. - Adding more functions to the library (eg a function to list all publicly available datasets on the platform) | 2 weeks | 
| 4.     |  Improved UI | Creating an intuitive UI for the web that allows users to fully realize the capabilities of the project | 3 weeks | 
| 5.     | Testnet relaunch and Mainnet Launch readiness evaluation|  Testing and fixing any arising issues ahead of testnet relaunch and evaluating if the project is ready for a mainnet launch| 2 weeks | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

  Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

	Name: Baranaba Mugabane
	Github: https://github.com/bashybaranaba
	Email: [bashybaranaba@gmail.com](mailto:bashybaranaba@gmail.com)
	Role: Fullstack dev
* How did you learn about our microgrant program?
     Filecoin's grants page
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by bashybaranaba** [comment]
Hey @ErinOCon, just checking on the status of my request

**Comment by bashybaranaba** [comment]
Any update?

**Comment by bashybaranaba** [comment]
Hey, just checking in on the status of the grant request once again

**Comment by ErinOCon** [comment]
Hi @bashybaranaba, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
