### ISSUE TITLE
YAR

### ISSUE THREAD

**Issue by YARlabs** [filecoin-project/devgrants#1453]
# Open Grant Proposal: `YAR`

**YAR:**

**Proposal Category:** `integration-adoption`

**Proposer:** `YARlabs`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** "Yes"

# Project Description

YAR - blockchains interconnector that brings together all of blockchains in one place, in any place.
With Filecoin grant we plan to build Filecoin interoperability connector for YARprotocol.

## Value

YAR makes any blockchain interoperable with FILECOIN, and FILECOIN is interoperable with any blockchain. It means more assets, more transactions, more users, and more cash flow. It means that assets from another blockchain can be tradable and transferable into FILECOIN, into FILECOIN-based projects. It means more TVL, more community, and more power.

## Deliverables

Certified Filecoin interoperability connector for YARprotocol.

## Development Roadmap

Filecoin connector development - up to 3mo - 8 people - 50000
Filecoin connector security audit - up to 2mo - 4 people - 30000
Filecoin connector test and deploy for market - up to 2mo - 5 people - 20000

## Total Budget Requested

Total budget 100'000USDT

## Maintenance and Upgrade Plans

Filecoin connector should be always updated. So, we never stop to working on.

# Team

## Team Members

Sergey Glukhota

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/glukhota/

## Team Website

https://yarchain.org

## Team code repositories

https://github.com/YARlabs

# Additional Information
https://docs.yarchain.org

**Comment by ErinOCon** [comment]
Hi @YARlabs, thank you for your proposal. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!
