### ISSUE TITLE
Next Step Microgrant: <FEVM Starter Kits>

### ISSUE THREAD

**Issue by xBalbinus** [filecoin-project/devgrants#1454]
### 1. What is your project, and what problem does it solve? (max 100 words)
A starter kit project for rapidly bootstrapping, developing, deploying, and testing Solidity smart contracts on the FEVM (Ethereum Virtual Machine on Filecoin) to improve dev experience.

### 2. Project links
  
Link to Github repo: https://github.com/filecoin-project/fevm-hardhat-kit, https://github.com/xBalbinus/FEVM-Hardhat-Kit
Link to demo or website: ^
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

Heavily uses FVM (RPCs to connect / broadcast transactions onto the FVM, contract deployment scripts and testing tasks on the FVM, etc.)

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |    Feature parity between Hardhat & Foundry kits                    |          met (for reference, this microgrants application was filed late: the project had already been scoped out and work had already been done.             |          1 week                  | 
| 2.     |   Client contract support                      |              met            |           1 week                 | 
| 3.     |   Starter kit frontend                      |                   met / in review                     |              1 week              | 
| 4.     |                         |                                                            |                            | 

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @xBalbinus, thank you for your proposal! Do you agree to provide a final report for this project? Also, can you provide an email address to discuss next steps?

**Comment by xBalbinus** [comment]
Yes, and xiangan9@gmail.com

Please note that this microgrant request should be considered for both my contributions to the client contracts frontend and the starter kits.

**Comment by xBalbinus** [comment]
Hey @ErinOCon, any updates? I haven't received any communication via. email regarding this.

**Comment by ErinOCon** [comment]
Hi @xBalbinus, thanks for checking in! You should now see payment instructions provided by email.
