### ISSUE TITLE
Next Step Microgrant: <FogMeta Data Rebuilder>

### ISSUE THREAD

**Issue by Normalnoise** [filecoin-project/devgrants#1459]
### 1. What is your project, and what problem does it solve? (max 100 words)
FogMeta Data Rebuilder (Replication and Repair) is a guaranteed storage service based on FEVM contract.
It guarantees N replicas stored on filecoin network, 50% of the storage fund locked in FEVM contract will be used for the initial storage copies and the remaining 50% will be used for future replication when the data replicas loss occurs within the term. The reserved fee percentile is based on the current average storage provider failure rate. 
Assuming the current failure rate per SP is 30% in the term, with 99.99% SLA, we need to maintain 8 replicas all the time. When a replicas loss occurs, a 5% fee will be used for the fee of the replica deal, and unused funds in the contract will be refunded to the user after the term expired.

### 2. Project links
  
 - [Link to Github repo](https://github.com/FogMeta/Rebuilder)

 - [Link to demo](http://rebuilder.fogmeta.com/#/dashboard/index)

 - [License: Apache](https://github.com/FogMeta/Rebuilder#license)

### 3. a) How is IPFS, Filecoin, or related technology used in this project?

FogMeta Data Rebuilder, as a guaranteed storage service, has integrated the technology of IPFS, IPNI, Filecoin network, and FEVM  smart contract.

FogMeta Data Rebuilder V1 Functions are as follows.
-   **Build** (IPFS To Filecoin): Use the [MCS SDK](https://docs.filswan.com/multi-chain-storage/developer-quickstart/sdk) to upload the data to the IPFS node.
-   **Rebuild** (Filecoin To IPFS):
    -   Find the storage providers' peerIds by the [Indexer node](https://github.com/filecoin-project/index-provider)
    -   Get the storage providers IDs from the [Filecoin Network](https://github.com/filecoin-project/lotus/blob/master/api/v0api/full.go)
    -   Retrieve the data from the storage providers using [Lotus](https://github.com/filecoin-project/lotus)
    -   Upload the data to the IPFS gateway

-   **CID-Discover (IPFS)**: Rebuilder will check if the data content is available on the IPFS gateway
-   **Auto-Rebuild**: once the lost data cid is found, the auto-rebuild process will trigger and reload data from the storage provider to the target IPFS gateway.

### b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |      Auto-replica                  |      if the current count of replicas is below a threshold of 3/5, the auto-replica process will be triggered, and the cost will be deducted from the perpetual smart contract for the deal cost to store on replica storage providers.                                                      |     4 weeks                       | 
| 2.     |           Funding contract              |       auto payment for a replica, funds lock, refund                                                      |                       4 weeks    | 
| 3.     |             Integrate Metamask wallet            |     support different users manage their own accounts, and rebuild their data according to the SLA                      |              4 weeks          | 
|
### 5. If accepted, do you agree to share monthly project updates in this GitHub issue for 3 months or until the project described here is complete?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

 	- https://dorahacks.io/hackathon/27/results
 	- https://ethglobal.com/showcase/fogmeta-data-rebuilder-8em0i
	- https://spacewarp.fvm.dev/#ie

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
 	- [Normalnoise](https://github.com/Normalnoise)
 	- [sonic-chain](https://github.com/sonic-chain)
	- [rykci](https://github.com/rykci)
    - [qinghua8080](https://github.com/qinghua8080)

* How did you learn about our microgrant program?

	We were early members of the Filecoin community and participated in the SPACE WARP Pilot, Round 1, Round 2, Round 3, and Round 4; The Filecoin and FVM team highly encourage us to apply for the FVM Microgrants.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 

	Data Dao Hackathon in 2022

  * Please link to your hackathon submission

	(1) Data Dao Hackathon in 2022: https://dorahacks.io/buidl/3394

	(2) Results: https://dorahacks.io/hackathon/27/results

**Comment by satoshi-kevin** [comment]
@ErinOCon  Sir, any update?

**Comment by Normalnoise** [comment]
@ErinOCon could you please help review the grant?

**Comment by ErinOCon** [comment]
Hi @Normalnoise, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant for this project. This proposal is very interesting and was strongly considered for a significant period of time.

Please feel welcome to contact our team at [grants@fil.org](mailto:grants@fil.org) with any questions. Wishing you the best as you continue to build!
