### ISSUE TITLE
Next Step Microgrant: Kinba

### ISSUE THREAD

**Issue by sa8** [filecoin-project/devgrants#1460]
### 1. What is your project, and what problem does it solve? (max 100 words)

Kinba is a decentralized subscription platform for content creators and their fans that provides censorship resistance. 
Kinba fights the issues of deplatforming, censorship and financial exclusion that are routinely faced by content creators on centralized platforms such as OnlyFans or Patreon. At Kinba, we cannot delete content, ban profiles or withheld funds arbitrarily.
Futhermore, Kinba implements a novel decentralized content moderation protocol that ensures that legal content cannot be removed arbitrarily while illegal content is appropriately banned.

### 2. Project links
  
Link to Github repo: https://github.com/kinbaApp/medusa-kinba
Link to demo or website: [kinba.app](https://www.kinba.app/)
License: MIT 

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

With Kinba, the content is stored on IPFS (later on Filecoin when retrievals will become available), the subscriptions are handled by the Filecoin Virtual Machine (FVM) and payments are processed on the Filecoin blockchain.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
  Yes.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |    Better looking MVP                    |          I will hire a UI developer to help me improve the UI of my prototype, as I do not have myself a UI background.                                                  |                    1 month        | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

  Yes.
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  * Sarah Azouvi, s.azouvi@gmail.com, @sa8, Principal instigator.
* How did you learn about our microgrant program?
  * I used to work for Protocol Labs.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @sa8, thank you for your proposal and for your patience with our review process. This is an interesting project and was considered for a number of our microgrant cycles. 

Unfortunately, we will not be moving forward with a grant at this time. Please feel welcome to contact our team at [grants@fil.org](mailto:grants@fil.org) with any questions. 

Wishing you the best as you continue to build!
