### ISSUE TITLE
FIL+ Scan

### ISSUE THREAD

**Issue by MingHok** [filecoin-project/devgrants#1462]
### 1. What is your project, and what problem does it solve? (max 100 words)

FIL+ Scan (tentative) is a dashboard targeting [Filecoin Plus Large Datasets](https://github.com/filecoin-project/filecoin-plus-large-datasets). It will provide daily updates of triggered, approved, used, and requested DataCap, including aggregated network-wide statistics from client, notary and SP views. It also supports searching by date, SP ID, and address. 
This dashboard will help community members keep a more timely track of DataCap status and enables the community to visualize the growth of the network and to locate specific quadrants. To meet the user needs, the project will be available in English and Chinese.

### 2. Project links
  
Link to Github repo: https://github.com/benhaixu/FILSCAN
Link to demo or website: Please see in the repo
License: APACHE2

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
 By building lotus full nodes, we will pull all the messages on the Filecoin chain and aggregate into the database. then sort the data sources according to the categories in the repo and create each subpage.

FIL+ project carries the most important value of Filecoin targeting the most important information to humanity. The development of the entire network QAP depends to a great extent on the process of LDN applications. Our project will accurately mark the progress and milestone of the network from updates of each LDN dimension.
###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No) 
No
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1   |      Date Source           |           Refine full node, re-integrate database.                                         |      5 work days                | 
| 2-1.     | LDN Overview Page  |  Improve requested and approved volume sections; Add triggered volume and used volume sections. |    5 work days    | 
| 2-2.    |   Notary, Client, and SP Pages |   Add notary & client address and sp ID; Notary & Client Page: FIL+ to Client, Notary to Client, Unallocated DataCap, and DataCap Sealed/ Used actions; SP Page: Aggerate client address, QAP, sealed DataCap, and detailed actions.   |  5 work days  | 
| 3.     | Search Bars   | Added LDN overview page date search box, notary, customer address and sp ID search bars.                                                   |    2 work days                         | 
| 4.     |   Overall Revision         |                                                            |    3  work days                  | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
 Yes, absolutely.
  
### 6. Does your proposal comply with our Community Code of Conduct?
 Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  * Frontend developer: Benhai Xu https://github.com/benhaixu
  * Backend developer: Ming Hok mhok95406@gmail.com
  * UI designer: Macy Qian Macyqian@skiff.com

* How did you learn about our microgrant program?
Through #fil-builders. 
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) N/A
  * Please link to your hackathon submission

**Comment by MingHok** [comment]
Hi @ErinOCon, this is my first time applying for a grant. Please let me know if anything else is needed. Thank you!

**Comment by ErinOCon** [comment]
Hi @MingHok, thank you for your proposal. We will not be proceeding with a grant at this time. Wishing you all the best as you continue to build!
