### ISSUE TITLE
Next Step Microgrant: Soji.app

### ISSUE THREAD

**Issue by lantos1618** [filecoin-project/devgrants#1468]
### 1. What is your project, and what problem does it solve? (max 100 words)
Soji is a decentralised emoji and mp4 library like Tenor or Giffy. The reason to have a decentralised emoji library is emojis and webms shared on Tennor and Giffy are being censored.  Soji also allows for sojis to be minted so that there is a reward mechanism to prevent over crowding of the same emoji.

The word Soji is play on the words sound + emoji.
Technologies
- ipfs
- Chainlink vrf
- Ethereum 
- ReactJS (typescript) 
- Web3.js

### 2. Project links
  
Link to Github repo: https://github.com/lantos1618/soji.app
Link to demo or website: http://www.soji.app/
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

IPFS is integral to Soji as it provides the backbone to store the decentralised Soji's. 
###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | Refresh the website front end| Develop a requirements document get a new frontend designed | estimate effort 7 Days within 2 months| 
| 2.     |Add/Test the Link VFR function| The vrf function and minting of the |estimate effort 3 Days within 1 month | 
| 3.     |Discord and/or mobile Keyboard integrations|Create a specification for the requirements and develope the functionality                     | estimate effort 5 days within 1 month
| 4.     |Add a NSFW filter| Define a specification for requirements to add NSFW filters| estimate effort 7 days within 2 months| 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

  Agreed
### 6. Does your proposal comply with our Community Code of Conduct?

Yes this does comply with code of conduct
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://devpost.com/software/soji-xjrc8h

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Lantos - l.leong1618@gmail.com, https://github.com/lantos1618, creator 
* Skippy - marlon.leong@hotmail.com, https://github.com/SkippyHub, creator
* How did you learn about our microgrant program?
* I was emailed by Niki (niki.gokani@protocol.ai) to submit to the grant as a suggestion
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Chainlink
  * Please link to your hackathon submission
  *   https://devpost.com/software/soji-xjrc8h

**Comment by ErinOCon** [comment]
HI @lantos1618, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!
