### ISSUE TITLE
Next Step Microgrant: Latis

### ISSUE THREAD

**Issue by Sgandhi10** [filecoin-project/devgrants#1469]
### 1. What is your project, and what problem does it solve? (max 100 words)

Our project streamlines firmware updates for machinery in manufacturing plants shifting to Industry 4.0. One primary concern with the shift to industry 4.0 is an increase in cyberattacks due to the increase in connectivity in manufacturing plants specifically for large-scale actuators that aren’t replaced often. With the number of independent parties involved in updating firmware, there are numerous points where data can be manipulated or attacked. Accountability and party trust are crucial to secure update operations. We use a decentralized framework with Filecoin/IPFS and DAGs (like Hedera) for a trusted IoT firmware update pipeline.

### 2. Project links
  
Link to Github repo: https://github.com/LATISNetwork
Link to demo or website: N/A
License: Apache 2.0

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

To upload files from the OEM side to the IPFS “mirror list” for pushing firmware updates to devices, we’re planning on using Estuary as a client to upload encrypted large files to IPFS and the Filecoin network. Filecoin helps with providing secure and distributed storage of files in the network, which is more cost-efficient and less reliant compared to current cloud solutions. With this upload, we also call a smart contract, written in Hedera, to update the manufacturer side that there is a new firmware push, with all of the specifications such as the checksum, CID, and permissioned access requirements. This could also be written in FVM. The manufacturer side then uses the Hedera network to send the update command to specific edge IoT devices. These devices run a Hedera smart contract from their trusted execution environment (TEE) with the proper information (CID, miner, checksum, etc) to pull the update from Filecoin down to the device.

IPFS and Filecoin overall help with facilitating the file upload and storage for these firmware updates, which are very prone to corruption and attacks, and decentralization can combat these attacks and keep these systems, which include third-party actors, trusted by the OEM and manufacturers. Hedera, and similar DAG-based frameworks, allow for fast and cheap computing, which is why we believe it is useful for IoT applications. 

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

We plan to utilize this grant to help us fund the deployment of the smart contracts on the network and purchase appropriate hardware to help further the development. Our next steps involve creating the pipeline and increasing its overall security of the pipeline. At this moment we have each of the individual components, but they aren’t tied together as a single cohesive system.
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
1. 3/31/23 Estuary-based file upload portal 
    * Using Estuary’s node client & end-to-end encryption algorithm on the backend, we will create an Electron portal for OEMs to upload encrypted files to the Filecoin network.
2. 4/15/23 Permissioned access with Hedera
    * Using a Hedera contract for permissioned query to the Filecoin network to grab and download the file. Additionally, we are having a Hedera contract to collaborate with the OEM’s contract to update the manufacturer’s list of updates.
3. 4/30/23 Fetching updates with TEEs
    * Using the TEE to host a wallet and call the Hedera contract to download the file from Filecoin and decrypt it
4. 5/15/23 Implementing updates to large-scale systems
    * Execute the update after running the Filecoin request and download process
5. 5/31/23 Integrate all components through a UI/UX
    * Deploy electron apps for OEM and manufacturers to use for streamlined, synced views on firmware updates.
6. 6/15/23 Pitching ideas to companies and showing off prototypes
    * Running initial tests with local companies and manufacturers for basic firmware updates.

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Soham Gandhi: [sgandhi25@vt.edu](mailto:sgandhi25@vt.edu), sgandhi10, project manager & developer on manufacturer side
Forrest Meng: [forrestm@vt.edu](mailto:forrestm@vt.edu), pyInvenio, FVM and embedded systems developer
Rakesh Pillai: [rakeshpillai@vt.edu](mailto:rakeshpillai@vt.edu), rxkesh, application developer
* How did you learn about our microgrant program?
While looking for information on API’s for filecoin we stumbled upon this link and found out about this microgrant program that was applicable to us.
* If your project was created as part of an event or hackathon: N/A
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) N/A
  * Please link to your hackathon submission N/A

**Comment by Sgandhi10** [comment]
Here is the link to the updated repo: https://github.com/LATISNetwork

**Comment by ErinOCon** [comment]
HI @Sgandhi10, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
