### ISSUE TITLE
CARBONIC : Carbon footprint Calculator built on FVM

### ISSUE THREAD

**Issue by ValarieOyieke** [filecoin-project/devgrants#1470]
# Open Grant Proposal: `CARBONIC`

**Name of Project:** `CARBONIC`

**Proposal Category:**
 `green` 

**Proposer:** `ValarieOyieke`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** Yes

# Project Description

People and organizations are looking for ways to lessen their carbon footprint and lessen the environmental impact of their daily activities as climate change becomes an urgent worldwide concern. Unfortunately, many people and even organizations lack the skills and resources necessary to determine their carbon footprint with accuracy and take meaningful efforts to minimize it. This inhibits accountability and hinders the achievement of sustainability objectives.

Our Application assesses carbon footprint and offers tailored ways to assist people and businesses in being more conscious of their environmental impact and taking proactive efforts to lessen it. The program can calculate a person's carbon footprint using the information on their energy use, dietary preferences, and transit patterns. It can then advise users on reducing their carbon emissions, by using less electricity, choosing eco-friendly transportation, or buying carbon offsets. The app can contribute to the development of a more environmentally conscious society and the reduction of our collective carbon footprint by offering a simple-to-use tool that promotes sustainable practices.

## Value

**1.    Benefits of getting this right** 

- The integration of CARBONIC will help to enhance the sustainability of the Filecoin ecosystem. By enabling users to track their carbon emissions associated with storing files on the Filecoin network, the app can encourage more sustainable behavior among users, leading to a reduction in the overall carbon footprint of the network.

- The integration of CARBONIC will also increase user engagement with the Filecoin ecosystem. It will provide users with more information on the environmental impact of their storage choices, leading to more informed decisions and a greater sense of personal responsibility for their carbon emissions

**2.  The risks if we don't get it right** 

- Getting this wrong will turn off people on the concepts of how Filecoin works when building real-world solutions.

**3.  Risks that will make executing on this project difficult** 

- User privacy: Collecting data from users to calculate their carbon footprint can raise concerns about privacy. Users may feel uncomfortable sharing their personal data or the details of their activities with a third party, especially if they are unsure about how the data will be used or stored. Therefore, it is important to ensure that appropriate privacy and security measures are in place to protect user data.

- Data accuracy: The accuracy of carbon footprint calculations relies heavily on the accuracy and completeness of the data used. If the data is incomplete or inaccurate, the calculations will not be reliable. Therefore, it is crucial to ensure that the data sources used are trustworthy and that the calculations are based on a robust methodology.

- User adoption: A carbon footprint calculator requires user adoption to be successful. However, there is a risk that users may not be willing to use the calculator due to concerns about data privacy, lack of awareness or interest, or the perception that the calculator is difficult to use or understand.

## Deliverables

Our dApp will allow individuals and businesses to calculate their carbon footprint using the information they feed it with. It will then advise the users on the best ways to offset their carbon footprint to maintain a carbon-free environment. 

Functionality the dApp will deliver when it is finished:

- Detailed design documents that outline the functionality and user interface of CARBONIC, including wireframes and mockups.

-  A working codebase including all necessary libraries and dependencies and  Specifications on the Data sources, algorithms, and methodologies used to calculate carbon footprint .

-  An API that will integrate the CARBONIC app with the Filecoin Ecosystem, including endpoints, parameters, and authentication requirements while providing solutions to users every time their carbon emission is calculated.

- Detailed documentation  with Instructions on how users can work around the app and interpret the results.

## Development Roadmap

**Milestone 1: Planning and Design**

- Defining the key features and functionalities that the app should have, such as data input fields, calculation methods, and output formats.

- Determining the user interface design and user experience requirements while identifying the target audience and their needs.

- Evaluation of existing sources of data, such as carbon emission factors for different activities and transportation modes.

- Determination of the most accurate and reliable calculation methods for each activity type and creation of a  database to store the necessary data and calculation methods.

- Creation of sketches and wireframes of the app's interface and functionality and developing  a clickable prototype of the app to test user interactions and validation of the design.

**Team Members**: 2
Valarie Oyieke: Software Tester, Frontend and Smart Contract Developer 
Sylvia Ndunge: Web Design, Software tester, and research.

**Budget**: $10,000
**Duration**: 1 month ( April 1, 2023 - April 2, 2023)

**Milestone 2: Development and Testing**

- Implementation of the user interface design and development of the data input fields and data validation logic.

- Development of the logic and algorithms to calculate carbon emissions for each activity type and Integration of the data sources and calculation methods into the app.

- Thorough testing to ensure the app is functioning properly and accurately calculating carbon emissions while identifying and fixing any bugs or issues that arise during testing.

**Team Members**: 2
Valarie Oyieke: Software Tester, Frontend and Smart Contract Developer 
Sylvia Ndunge: Web Design, Software tester, and research.

**Budget**: $20,000
**Duration**: 3 months (May 1, 2023 - July 31, 2023)

**Milestone 3: Launch** 

- Deploy the app to a web server or app store, making it accessible to the public, and develop a marketing strategy to promote the app and attract users.

- Identify potential partnerships and collaborations with organizations or influencers that align with the app's mission.

**Team Members** : 2

Valarie Oyieke: Software Tester, Frontend and Smart Contract Developer 
Sylvia Ndunge: Web Design, Software tester, and research.

**Budget**: $10,000
**Duration**: 1 month (August 1, 2023 - October 31, 2023)

## Total Budget Requested
**$40,000**

## Maintenance and Upgrade Plans

- Monitoring the app usage and frequent collection of feedback from users.

- Identifying and fixing any bugs or issues that arise post-launch.

- Continuous update of the app with new data sources, calculation methods, and features to improve accuracy and usability.

# Team

## Team Members

**Sylvia Ndunge**
**Valarie Oyieke**

## Team Member LinkedIn Profiles

[Valarie Oyieke](https://www.linkedin.com/in/valarie-oyieke-92b8a3185/ )
[Sylvia Ndunge](https://www.linkedin.com/in/sylviandunge/ )

## Relevant Experience

**Sylvia Ndunge** is a Web3 marketer, software tester, and web designer with a deep understanding of the web3 ecosystem and its unique challenges and opportunities. Her work experience has allowed her to work on projects that push the boundaries of traditional web development and grow skills that contribute to the web3 community.

**Valarie  Oyieke** is a Smart Contract developer and software tester with experience in developing large-scale systems as well as working on public key blockchains and performing manual, and automated tests, writing and execution of scripts, and overseeing  testing activities in different environments, including web and mobile.

Our team has an extensive understanding of environmental issues, especially those related to carbon emissions and climate change, developing accurate calculations and providing users with helpful tips for reducing their carbon footprint.In addition to that, we both have a solid understanding of modern software development methodologies including web development, database design, and user interface design. 

# Additional Information

How did you learn about the Open Grants Program?   **Filecoin Website** 
Please provide the best email address for discussing the grant agreement and general next steps. 

[oyiekeav@gmail.com](mailto:oyiekeav@gmail.com)
[socialswithsysh@gmail.com](mailto:socialswithsysh@gmail.com)

Please include any additional information that you think would be useful in helping us to evaluate your proposal. 
[Sylvia Ndunge Github](https://github.com/Sysshh )
[Valarie Oyieke Github](https://github.com/ValarieOyieke )

**Comment by ErinOCon** [comment]
Hi @ValarieOyieke, thank you for your proposal. Unfortunately, we will not be moving forward with a grant at this time. For next steps, you may want to consider participating in a [hackathon](https://hackathons.filecoin.io/) or applying for a [microgrant](https://github.com/filecoin-project/devgrants/blob/master/microgrants/microgrants.md)!

Wishing you the best as you continue to build!
