### ISSUE TITLE
Collaboration tool using IPFS

### ISSUE THREAD

**Issue by Cuttlas90** [filecoin-project/devgrants#1471]
# Open Grant Proposal: `Collaboration tool using IPFS`

**Name of Project:** DecenCol

**Proposal Category:** `core-dev`

**Proposer:** `Cuttlas90`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes, this project will be released under GPL license for code.

# Project Description

Remote working is trending nowdays. different persons working on a project or article remotly and some times dont see eachothers at all. this trend needs new tools to make them connected and help them collaborate with eachother regardless of distance. messaing, video conference and online storage space are growthing tools to fill groups needs.

DecenCol is good solution for this problem. it allows teams, to create, store, share, modify and review  documents on decentrlized network effortlessly. they can use it for free to immedatly share documents between team members. also they have this chance to pin important file for as long as they want.

## Value

DecenCol can bring this value for teams

- Decentralization: Using one of the key advantages of IPFS, DecenCol allows for decentralized collaboration, which means that data can be shared and stored on multiple nodes in the network. This helps to ensure that data is always available, even if a single node goes offline.
- Improved security: IPFS uses cryptographic hashes to verify the integrity of data, which helps to prevent tampering, corruption, or loss. This makes it an attractive option for organizations and individuals who are concerned about the security of their data.
- Reduced dependence on centralized services: decenCol can help reduce the dependence on centralized services like onedrice and dropbox. This can be particularly beneficial for organizations and individuals who are concerned about privacy and control over their data.

## Deliverables

- Allow user to upload and share new type of documet type;
	- Word
	- Excel
	- CSV
- Previw section, support shows of styled file;
	- Markdown
	- CSV
	- HTML
- Support Pinning files on available services, owner can pin its file using filecoin for remaining on network for longer time.
- Version History, allow owner to see document previous versions.
- Access Control, owner can give read, suggest and edit control to other users
- LibreOffice integration, allowing user study, modify

## Milestones & Funding

**Total Funding Amount:**  $35,100 

Milestone |functionality |Hours | Cost
--- | --- | --- | ---
Upload files | users can upload different document type on the space |45 |4,050 $
Preview Section | users can preview their styled file and see how its look |30 |2,700 $
Version History | owner can see history of document change and return to desire state |75 |6,750 $
Libre Integration | users can modify their using LibreOffice  |100  |9,000 $
Access control | can give read, suggest and edit control to other users  |40  |3,600 $
Pin file | owner can pin the desire file through availabe services |100 |9,000 $
**Total** | |390 |35,100 $

## Maintenance and Upgrade Plans

We plan the add more feature and make it an enterprise product, the current features wil remain as Free tier for all users.

# Team

## Team Members

- mohsen, Product Manager, mohsenbarekati@gmail.com, https://github.com/Cuttlas90
- Ali, Backend Developer, ali.mhossaini@gmail.com, https://github.com/amhossaini
- Shahed, FrontEnd Developer, shahedmoez@gmail.com,https://github.com/shahedmoez

## Team Member LinkedIn Profiles

- https://www.linkedin.com/in/mohsenbarekati/
- https://www.linkedin.com/in/ali-mohammad-hosseini/

## Team Website

- https://cuttlas.app (team website)
- https://comolus.com

## Relevant Experience

I think the best our relevent experince is developing DecenCol V.1. it gives basic functionality to owner to share its file with multi users, get their opinins and decide to reject or apply changes.

## Team code repositories

- https://github.com/Cuttlas90
- https://github.com/amhossaini
- https://github.com/shahedmoez

# Additional Information
How did you learn about the Open Grants Program? --> google website
Please provide the best email address for discussing the grant agreement and general next steps. --> mohsenbarekati@gmail.com

**Comment by ErinOCon** [comment]
Hi @Cuttlas90, thank you for your proposal. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!
