### ISSUE TITLE
File Bridge - Swap & Bridge

### ISSUE THREAD

**Issue by gianlucadibella** [filecoin-project/devgrants#1473]
### 1. What is your project, and what problem does it solve? (max 100 words)
File Bridge is a decentralized exchange that enables user to trade enables users to trade cryptocurrencies without any involvement with a centralized third party on FVM. Also, it enables users to bridge their tokens to other EVM supported blockchains.

With File Bridge, users can:
1. Swap tokens on FVM without a centralized third party.
2. Bridge their tokens to other EVM supported blockchain.

It solves the interoperability of digital assets between the Filecoin project blockchain and other blockchain networks.

### 2. Project links
  
[Github repo](https://github.com/FileBridge):
[Demo](https://ipfs.io/ipfs/QmPddWJCpmJAkCSBPpeLn17HaZ6qDZKK6cYByxL93w8LTL) hosted on IPFS
[ETHGlobal Demo video](https://ethglobal.com/showcase/file-bridge-9mk1g)
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

The project was developed using the following tech stack: 

- 💻 Using advanced technologies like [React](https://www.linkedin.com/company/reactofficial/), [Rainbow](https://www.linkedin.com/company/rainbowdotme/) + [wagmi](https://www.linkedin.com/company/wagmi-sh/) kit, and Ethers, while the Chainstack node library managed our formidable backend.

- 💪 Our smart contracts are designed to be future-proof with proxy compatibility, which means they can quickly change to adapt to new developments in the blockchain world, enabling users to swap tokens on FVM blockchain + bridge them to any other EVM-supported blockchain.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
  Yes.
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | Swap mainnet launch |     Improve the UI/UX of the swap and add an incentive for users to add liquidity                                                  |           ~15 days | 
| 2.     |        Improve Bridge Smart Contracts + backend executor                 |        Make kind of merkle tree proof with nullifier to stop relying on guardians                                                |               ~1.5 month |                  | 
| 3.     |               Bridge NFTs | Add support on the smart contracts to bridge NFTs from any EVM-supported blockchain                                                          |                    ~15 days          | 
| 4.     |      Launch to mainnet                   |                Test and audit smart contracts + web app to launch a fully working and secure version                                           |                ~15 days              | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

  Yes.
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.
### 7. Links and submissions
**File Bridge was made as a submission for the FVM Space Warp ETH Global Hackathon**
* Our Submission Link - [ETHGlobal](https://ethglobal.com/showcase/file-bridge-9mk1g)
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Amirreza Ghodrati Dola
Github - Amir0reza
Smart Contract Developer & Smart Contract Integration

Abdul Gilani
Github - abdulqgg
Smart Contract Developer 

Gianluca Di Bella.
Github - gianlucadibella
Front End Developer & Smart Contract Integration

Raquel Carrasco
Github - raigal-r
Backend Developer

* How did you learn about our microgrant program?
A Discord message from a FVM Space Wrap ETH Global hackathon finalist.

**File Bridge was made as a submission for the FVM Space Warp ETH Global Hackathon 🌉**
* Our Submission Link - [ETHGlobal](https://ethglobal.com/showcase/file-bridge-9mk1g)

**Comment by ErinOCon** [comment]
Hi @gianlucadibella, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!
