### ISSUE TITLE
Rate My Courses 

### ISSUE THREAD

**Issue by metaversemoon** [filecoin-project/devgrants#1475]
### 1. What is your project, and what problem does it solve? (max 100 words)

Rate My Courses is an educational platform where students evaluate, rate, and review teachers and courses.

It also allows students to review classes before committing to them or registering. This will help you save thousands of dollars and time. Students can add a new class that doesn’t exist on the app or can rate one that already exists for a chance of winning NFTs.

So far users can do the following: 
- Browse Class Materials 
- Post New Material 
- Get All Class Materials   
- Post New Class 
- Get All Classes
- Post Reviews  
- Get All Reviews

Users can also search for teachers by name or choose a department and rate its teachers or read reviews left by other students. The rating system allows you to assign one to five stars to your teachers within the following categories:

- Effective
- Integrity
- Empathy
- Respect
- Determination
- Homework

Rate My Courses is a safeguard for students and professors to track their professional references, ratings, and courses all in one place. It is a dApp that brings transparency and accountability to all partners. Ultimately, decreasing wasted time and resources.

### 2. Project links
Link to Github repo: https://github.com/metaversemoon/Class-Reviewer-App-hackerearth
Link to demo: https://student-reviews.netlify.app/#/
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

Rate My Courses is using IPFS and web3.storage to store every course listed within the platform. This includes the course’s name, description, website, location, address, images, and professors information. IPFS also is helping storage the class’ material itself in different formats. Currently, we accept pdfs and images but we are expanding this feature. When a new class register within the app all its data is uploaded and stored through IPFS's interface in a decentralized manner. This process returns a CID that is save in the smart contract and the we use it to populate our front-end.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No) 
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |            UX/UI             |    Come up with a clean design, for this, I am planning to hire a designer.                                                    |               1 to 2 weeks              | 
| 2.     |        Frontend                 |   Once the design is ready,  we will start working on the Frontend.                                         |       2 to 3 weeks                       | 
| 3.     |           Fix Smart Contract Bugs & File Upload             |             Fix the Smart Contract & file upload functionality to make it as seamless as possible for a better user experience.                                               |           2 to 3 weeks                      | 
| 4.     |          Cache & CI/CD               |             Add continuous integration & leverage the number of requests made by the frontend by adding a way to cache the previous requests.      |             1 to 2 weeks                    | 
| 5.     |          Add Chat & dynamic search           |             Add Chat & dynamic search for courses      |             3 to 4 weeks                    | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

  Yes
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes, I have submitted it. Here is the link https://ethglobal.com/events/hackfs2022/home
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Albert - metaversemoon@gmail.com - 4metaverse - software engineer
David - bycoolcodes@gmail.com - coolcodes23 - developer
Arturo - realcheapny@gmail.com - realcheapny - frontend developer

* How did you learn about our microgrant program?
It was mentioned by the IPFS team at EthDenver

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
  NA

**Comment by ErinOCon** [comment]
Hi @metaversemoon, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!
