### ISSUE TITLE
Next Step Microgrant: Reward-Hub

### ISSUE THREAD

**Issue by Mohammed-16** [filecoin-project/devgrants#1476]
### 1. What is your project, and what problem does it solve? (max 100 words)

- Reward-Hub is a platform designed to incentivize and recognize contributions made by open-source contributors to various projects. 
- The platform aims to solve the problem of a lack of recognition and reputation-building mechanisms for open-source contributors, who often make valuable contributions to projects but are not adequately acknowledged for their efforts.
- By providing a real connection between project owners and contributors and offering complete flexibility, Reward-Hub seeks to encourage open-source contributions and build a stronger open-source community.

### 2. Project links
  
Link to Github repo: https://github.com/Mohammed-16/Reward-Hub
Link to demo or website: https://reward-hub.vercel.app/
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

- We are using IPFS-Infura as its storage solution for secure and decentralized data storage.
- All assests, metadata, and NFTs are stored on this decentralized network, ensuring that data is secure, reliable and redundant.
- The platform's smart contracts are deployed on multiple chains, including Filecoin Testnet Hyperspace, Polygon, and Mantle.
- This approach makes Reward-Hub a multichain platform, which enables more users to onboard and provides greater flexibility and choice to users, allowing them to onboard easily from different chains.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
- Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.    | Integrating Perpetual Storage | Adding Lighthouse and Perpetual Storage functions on FVM mainnet | One week for Integrating and Few days for testing |      
| 2.     | Making onboarding easier | we will be adding social login wallets via web3Auth, need to get premium  version for more users                                         | Couple of days | 
| 3.     | Assessment of Testnet relaunch and readiness for the launch on Mainnet | Conducting testing and resolving any potential issues prior to the testnet relaunch, and assessing the project's readiness for a mainnet launch | Two weeks |    
| 4.     | Improving UI/UX |   Adding more features, buttons and feasible UX |  Few weeks| 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
- Yes, we will attempt to publish Open-Source articles documenting our development journey on FVM.
  
### 6. Does your proposal comply with our Community Code of Conduct?
- Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  
   * Name: [Mohammed Lokhandwala](https://mohammedlokhandwala.netlify.app/)
     Email: [mohammedlokhand4429@gmail.com](mailto:mohammedlokhand4429@gmail.com)
     GitHub: @Mohammed-16
     Role: Full Stack Developer
   
    * Name: [Soham Shah](https://twitter.com/sohamshah__/)
     Email: [sohamshah419@gmail.com](mailto:sohamshah419@gmail.com)
     GitHub: @TheDARKFURY
     Role: Backend + Smart Contract Developer

* How did you learn about our microgrant program?
  * We got a mail from Protocol Labs.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) - N/A
  * Please link to your hackathon submission - N/A

**Comment by ErinOCon** [comment]
Hi @Mohammed-16, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!
