### ISSUE TITLE
Next Step Microgrant: FileMart

### ISSUE THREAD

**Issue by rahulvivaramneni** [filecoin-project/devgrants#1479]
### 1. What is your project, and what problem does it solve? (max 100 words)
FileMart is an open blockchain platform designed to enable anyone to create data purchase or checkout (Buy/Sell) pages managed on the FEVM network.

### 2. Project links
  
Link to Github repo: https://github.com/rahulvivaramneni/FileMart
Link to demo or website: [filemart.vercel.app/](https://filemart.vercel.app/)
Link to demo Video: https://clipchamp.com/watch/XqigbA3iARy
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
Users create data pages which are purchase pages for secured IPFS datasets.

FileMart is self-governing. If a bad or inaccurate dataset is uploaded and sold, a purchaser or potential purchaser can flag the dataset as being fraudulent. The dataset page is locked after three flags.

To ensure that the data provides user satisfaction, the owner of the listing is only paid out from the contract after three non-flagged successful sales, and each sale after that. This is done automatically via logic tied to the purchaseData contract method which releases the funds on the contract after the third purchase.

Each dataset cannot be modified after it is posted, but the price can be updated by the owner and the listing can be marked as inactive. A new page should be created if a dataset needs to be changed - this protects the mutability and trust of data collections that have already been deployed.

**Using FEVM smart contracts, FileMart can:**

- Enable an immutable, append-only, history of interactions against FileMart smartcontracts.
- Store the data in a scalable/low-cost way for data owners, where no single source has to be the custodian of the data log.
- Perform low-cost, high-volume, and fast transactions on the FEVM network.
- Be self-governing by the user base and flag or shut down any fraudulent pages by logic included in the FEVM smart contract.

**Technologies used:**

- **FEVM**: Serves as the primary smart contract network for the FileMart application. FEVM enables fast and low-cost smart contract transactions that make it to deploy and interact with contracts in the field without heavy additional costs or time delays. Deployed contracts also enforce that the datasets be valid by enabling public users to flag suspicious listings.

- **IPFS**: Record keeping and storage. IPFS is used as the main backend for all uploaded datasets attached to DataContracts. The url of the asset is provided to the user post-purchase.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |     Smart contract rewrite                    |      We can make PageFlag smart-contract more optimized so that users can't flag it multiple times.                                                   |              15 days              | 
| 2.     |          Increase Revenue               |       Add a usage fee that takes a small percentage of each purchase. This could be easily added to the checkout flow - for now the purchases are completely free.                                                     |                      15 days      | 
| 3.     |             New Features            |       Add a searchable interface to discover datasets deployed.                                                |      20 days                      | 
| 4.     |           Easy onboarding              |      Add support for user logins in addition to metamask (or wallet-based) logins.                                                      |                     30 days       | 
| 5.     |     Smart contract                 |     Permanent data removal support from the filecoin network (uploaded sets remain live post-flagging currently).                                                    |              30 days              | 
| 6.     |    Developer Hire              |     Looking forward to use the prize and hire a developer / intern to help me with the above mentioned deliverables.                                                   |              30 days              | 
| 7.     |    Get Users              |  Identify influential people in this niche and reach out to them to see if they are interested in promoting FileMart to their followers. This can be an effective way to reach a wider audience and increase awareness of the platform.                            |              30 days              | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

- Name: [Rahul Vivaramneni](https://rahulvivaramneni.com/)
- Email: [rahulvivaramneni@gmail.com](mailto:rahulvivaramneni@gmail.com)
- GitHub: [@rahulvivaramneni](https://github.com/rahulvivaramneni)
- Role: Full Stack Developer

- Name: [Pradeep Varma](https://pradeepvarma22.is-a.dev/)
- GitHub: [@pradeepvarma22](https://github.com/pradeepvarma22)
- Role: Backend + Smart Contract Developer

* How did you learn about our microgrant program?
  We got a mail from Protocol Labs.
* If your project was created as part of an event or hackathon:
  * We began working on our project during the EthForAll hackathon, but unfortunately, we were unable to submit it due to our inability to create a minimum viable product (MVP) for our project.

**Comment by ErinOCon** [comment]
Hi @rahulvivaramneni, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!
