### ISSUE TITLE
Next Step Microgrant: Filestorage 

### ISSUE THREAD

**Issue by priyaraval12** [filecoin-project/devgrants#1480]
### 1. What is your project, and what problem does it solve? (max 100 words)

- Filestorage is a platform for uploading and sharing encrypted files.
- It is a decentralized platform that uses two technologies: IPFS and Filecoin virtual machine.
- It provides an encryption layer on top of IPFS using smart contract to overcome its transparent nature.
- It is designed to function as a Google Drive for Web3.
- Filestorage is built with composability in mind, so that other dApps can easily use it as a service and build on top of it.

### 2. Project links
  
Link to Github repo: https://github.com/priyaraval12/Filestorage-Filecoin
Link to demo or website: https://filestorage-filecoin.vercel.app/
License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

- Web3 Storage is used for storing data on IPFS and Filecoin.
- IPFS enables secure decentralized storage and sharing of data, including documents, images, and videos, without relying on central servers or points of control. 
- This benefits individuals and companies, who can securely store and share their files in a distributed manner, reducing their reliance on traditional centralized storage solutions.
-  This approach enhances security, accessibility, and privacy, making IPFS a promising solution for decentralized file storage.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)

- Yes

  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |  Incorporating Eternal Storage                 |  Plan to integrate Lighthouse and Perpetual Storage functions on the FVM mainnet.  | One week for Integrating and Few days for testing                           | 
| 2.     |  simplifying onboarding                | I intend integrate to incorporate social login wallets through web3Auth premium version to accommodate more users.   |  Couple of days                          | 
| 3.     | Evaluation of the Testnet restart and preparation for the Mainnet launch                       | Testing and addressing any possible difficulties prior to the restart of the testnet, as well as analysing the project's preparedness for a mainnet launch                                                     |  Two weeks                          | 
| 4.     |  Integrate Lit Protocol    |  Will be adding lit protocol for data encryption to bolster the application's security and privacy features                                                  |  Two weeks                          | 
| 5.     |  Enhancing UI/UX         |  Adding more buttons and feasible UX and attractive UI     |  Two weeks                          | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

- Yes, I will attempt to publish Open-Source articles documenting our development journey on FVM.

  
### 6. Does your proposal comply with our Community Code of Conduct?

- Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

- Name: [Priyanshi Raval](https://priyanshiraval.vercel.app/)
 Email: [priyanshiraval26@gmail.com](mailto:priyanshiraval26@gmail.com)
 GitHub: @priyaraval12
 Role: Full Stack Developer

* How did you learn about our microgrant program?

-  Got details from a Friend

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)-N/A
  * Please link to your hackathon submission-N/A

**Comment by ErinOCon** [comment]
Hi @priyaraval12, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!
