### ISSUE TITLE
Next Step Microgrant: FILaunch

### ISSUE THREAD

**Issue by hembreeb** [filecoin-project/devgrants#1481]
**1. What is your project, and what problem does it solve? (max 100 words)**
FILaunch is a decentralized FEVM launchpad that supports public sale. It is a relatively new type of platform that allow developers to deploy smart contracts on the Filecoin network in a decentralized and permissionless manner. The platform provides a user-friendly interface that supports new protocols launching on Filecoin, providing the tools that enable them to launch, bootstrap liquidity, and sustain their growth.

**2. Project links**
Link to Github repo: https://github.com/hembreeb/contract
Link to demo or website: https://filaunch.io/
License: MIT

**3. a) How is IPFS, Filecoin, or related technology used in this project?**
With FEVM, FILaunch enables developers to conduct public sales in a secure and transparent way, using smart contracts to automate the process of token distribution and ensure that funds are allocated fairly and securely. We also provides integrations with other products such as cross-chain bridges and decentralized exchanges with a seamless experience for users. By integrating with decentralized exchanges, tokens launched on the FEVM launchpad can be easily traded with other cryptocurrencies, increasing liquidity and potentially reducing price volatility. Integrations with cross-chain bridges allow tokens on other blockchain networks to be transferred to the Filecoin network, expanding the reach of the platform and potentially attracting new users and investors.

b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes.

**4. How will you improve your project with this grant? What steps will you take to meet this objective?**
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/hawkj/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/hawkj/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Number | Grant Deliverable | Briefly describe how you will   meet deliverable objectives | Timeframe (within 3 months)
-- | -- | -- | --
1 | Launch mainnet alpha version | Adding more features, buttons and   feasible UX | One week for UI/UX improvement and few   days for testing
2 | Support decentralized and permissionless   public sale contract deployment | Making user-friendly UI for project teams   to deploy their public sale contracts without permission | Two weeks
3 | Integrations with other products such as   DEXs & cross-chain bridges | Cooperating with other FEVM ecosystem   products, intergrating their UI/UX or links in our website | One month
4 | Support more public sale mechanism such   as Dutch Auction and Batch Auction | Conducting public sale mechanism research   and making users voting on the next mechanism by governance system | One month

</body>

</html>

**5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?**
Yes, we plan to publish the updates of FILaunch monthly.

**6. Does your proposal comply with our Community Code of Conduct?**
Yes

**7. Links and submissions**
Name: Hembree Bengo
Email: hembreebengocbenghiavw9135@gmail.com
GitHub: @hembreeb
Role: Full Stack Developer

How did you learn about our microgrant program?
We googled 'FEVM grant'.

**Comment by ErinOCon** [comment]
Hi @hembreeb, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!
