### ISSUE TITLE
Integration FIL in Trustee Global ecosystem 

### ISSUE THREAD

**Issue by taki-183** [filecoin-project/devgrants#1483]
# Open Grant Proposal: `Integration FIL in Trustee Global ecosystem `

**Name of Project:** Trustee Global

**Proposal Category:** `integration-adoption`

**Proposer:** `taki-183` & `trustee-wallet`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** Yes

# Project Description

Providing safe and durable storage of information is one of the most important tasks humanity faces today. IPFS can be one such solution that we are committed to promoting.

The integration of Filecoin into the Trustee Global ecosystem will grow the FIL users base and at the same time introduce the Trustee community to new methods of secure data storage.

## Value

We believe that the community and its expansion is the heart of any technology and its engine. An additional important factor is simple familiarity with the technology and its application.

Today, the Trustee Global ecosystem includes two fundamental solutions:

1. Trustee Plus is the first crypto neobank that allows you to manage cryptocurrencies profitably and with minimal time without any special knowledge. The app allows you to simultaneously store both crypto and fiat currencies, as well as replenish them from the card or vice versa transfer to the card (in some cases with 0% fee).
This is a completely new product focused on the simple use of cryptocurrencies in everyday life. In the near future we will implement a crypto card. It will allow you to pay with crypto at any outlets and pay for purchases on the Internet. Despite the relatively new service, it is already used by more than 30k users, mainly in Europe.

2. Trustee Wallet is a non-custodial multicurrency crypto wallet with the ability to exchange, buy and sell crypto with Visa/MasterCard bank cards. Today, the app has over 1 million installs and over 100k active users worldwide, and is available for Android and iOS users.
The app allows you to connect to DeFi services, supports many coins, staking, NFT and thousands of custom tokens on various blockchains. Unlike other multicurrency wallets, Trustee Wallet is open source.

The integration of FIL into the Trustee Global ecosystem will significantly expand the Filecoin community and introduce new users to decentralized data storage technology.

## Deliverables

By integrating FIL into the Trustee Global ecosystem, users will have a range of basic features across the two apps, as well as additional features depending on the app being used.

**Basic Functions**

- Deposit/Top Up - the user will receive a FIL wallet address for the deposit. The address can be obtained in text format and as a QR code.
- Withdraw/Transfer - allows the user to send FIL to a crypto address of their choice. The sending process includes entering the recipient's address, the amount and confirming the operation. To confirm the operation, the user can use a PIN code or Touch ID.
- Balance - shows the balance of the FIL wallet both in its own asset and in the local currency selected by the user by default, for example, fiat (multiple currencies), as well as in BTC equivalent.
- History - shows the history of transactions performed on the address in this wallet. Thus, all deposits, withdrawals, etc., all transactions that affect the balance will be listed.
- Security - to access the wallet, the user will be able to set a PIN code, Touch ID or Face ID.

**In Trustee Plus**

- Trading - the ability to make FIL trading operations with fiat currencies - EUR, UAH, KZT, as well as with other cryptocurrencies in the app (the number is gradually increasing).
- Transfers without fees - our technology allows you to transfer cryptocurrencies by phone number or Trustee Plus ID, instantly and without fees.
- Market - the FIL page in the Market section, where the user can get information about the Filecoin technology, see the FIL price chart and other important information.
- Notifications - the ability to set up specialized notifications for a given range of FIL price deviation depending on time.
- Crypto card - users will be able to pay with crypto at merchants using a crypto card from Trustee Plus (2nd 2023)

**In Trustee Wallet**

- CEX Swap - exchange FIL for other crypto in the wallet at the most favorable rate on the market. The Trustee Swap system automatically selects the most profitable swap provider for a transaction based on the user's conditions.
- DEX Swap - exchange FIL BEP20 to other tokens using Pancake Swap, Uniswap and other DEXs.
- Security - the user will have full control over the Recovery Phrase (seed-phrase), while the user will be responsible for backup and be able to restore to other wallets.

### Milestone 1 — Basic functions in Trustee Plus

**Deliverables**

- Top Up FIL
- Transfer FIL by crypto address
- Balance and history FIL display

Estimated duration: 3 weeks
Costs: $7000

### Milestone 2 — Additional functions in Trustee Plus

**Deliverables**

- Filecoin page in Market section
- Transfer FIL via phone number and Trustee Plus ID
- Adding trading pairs with FIL
- Testing all functionality and releasing an updated version of the app

Estimated duration: 2 weeks
Costs: $2000

### Milestone 3 — Basic functions in Trustee Wallet

**Deliverables**

- Base code: add FIL. Solutions used to generate transactions, securely store Recovery (mnemonic) phrases, sign and broadcast transactions
- Balances of FIL accounts
- Send & Receive FIL
- History of transactions
- App design adaptation

Estimated duration: 6 weeks
Costs: $20000

### Milestone 4 — Additional functions in Trustee Wallet

**Deliverables**

- Adding trading pairs with FIL in Swap section
- Testing all functionality and releasing an updated version of the app

Estimated duration: 2 weeks
Costs: $2000

## Total Budget Requested

Costs: $31000
Total estimated duration: 8 weeks
Some Milestones can run in parallel

## Maintenance and Upgrade Plans

We will ensure that FIL runs smoothly within the Trustee Global ecosystem and will expand it whenever possible or as new functionality becomes available.

# Team

## Team Members

Vadym Hrusha - CEO
Kseniia Zhytomyrska - CTO
Roman Hrusha - DevOps
Mike Kutsenko - BizDev

The Trustee team is more than 16 experienced professionals in programming, application development and design

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/vadymhrusha/
https://www.linkedin.com/in/turtus/
https://www.linkedin.com/in/mikekutsenko/

## Team Website

Trustee Global: https://trusteeglobal.com/

## Relevant Experience

[Vadym Hrusha](https://www.facebook.com/vadym.grusha) is an entrepreneur and IT specialist with sixteen years of professional experience. As an active participant in the crypto community since 2013, he is an active speaker at conferences around the world.

Vadym is the head of the Blockchain section at the most prominent Ukrainian offline conference dedicated to the Internet - IForum. Hrusha is also the organizer of the international conference - Money of the Future - showcasing innovations in financial technology. 

[Kseniia Zhytomyrska](https://www.facebook.com/ksu.zhytomirsky) has 17 years of professional experience in fintech software development, 6 years of blockchain development and over 3 years in business. She took second place at Consensus hackathon 2017, first place at Connect Ukraine festival hackathon. 

Kseniia developed smart contracts for large Ethereum blockchain projects, worked as external consultant in fintech. She cooperated both with well-known fintech projects and implemented her own.
 
Kseniia Zhytomyrska is one of the key representatives of the Ukrainian crypto community, often speaks at blockchain conferences, gives lectures and mentors other projects.

## Team code repositories

https://github.com/trustee-wallet/
https://github.com/Vadymhr
https://github.com/Turtus
https://github.com/rhrusha

# Additional Information

Our team has vast experience in the field of cryptocurrencies and we are confident that we can transfer our experience to Filecoin technology.

Please feel free to contact us by mail: [contact@trusteeglobal.com](mailto:contact@trusteeglobal.com)

**Comment by doc4comp** [comment]
Filecoin is a promising decentralized storage network that has gained traction in recent years due to its innovative approach to data storage and retrieval. As more and more users and applications begin to adopt Filecoin, its recognition and usage are likely to grow even further. One potential avenue for this growth is through trustee applications, which could provide a serious boost to Filecoin's visibility and appeal.

Trustee applications have become increasingly popular in recent years, especially in the realm of digital assets and cryptocurrency. If Filecoin were to appear in trustee applications, it would open up new avenues for users to engage with the platform and could help to increase its adoption and recognition.

Overall, the potential for Filecoin to appear in trustee applications is an exciting development that could provide a significant boost to the platform. As more users and applications become aware of the benefits of Filecoin's decentralized storage network, its usage and recognition are likely to continue to grow in the years to come.

**Comment by ErinOCon** [comment]
Hi @taki-183, thank you for your proposal. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue building!
