### ISSUE TITLE
Next Step Microgrant: FileStock

### ISSUE THREAD

**Issue by RobertoBarb** [filecoin-project/devgrants#1485]
### 1. What is your project, and what problem does it solve? (max 100 words)
Filestock is a platform uses blockchain technology to protect and sell digital images. It ensures that photographers are fairly compensated for their work and that the rights to the images are clearly represented. It's a Web3 take on stock photography

### 2. Project links
  
Link to Github repo: https://github.com/file-stock
Link to demo or website: https://frontend-filestock.vercel.app/
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
We developed used two different repositories, one for the smart contract and the second one for the front end. The three contracts, developed using solidity, are respectively

FileStock.sol: storage and purchase of the images,
RightsNFT: mints the ERC1155 token to decrypt the images stored on lighthouse
CreatorNFT: mints the NFT token, the one which gives the rights to receive the proceedings from the image sales.
The frontend was built with NextJS, dividing the organization in pages that represent the steps the user does to upload the files and to buy them.

All the files are stored in lighthouse, which let us deploy them both encrypted and not, in order to protect the original ones and show to the user the images with the watermark applied.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |                        |      Tag system insertion and search functionalities      |       3 weeks                     |  3 weeks
| 2.     |                         |      Complete seller profile                     |     2 weeks                       |  2 weeks
| 3.     |                         |      Complete buyer profile                   |      2 weeks                      |  2 weeks
| 4.     |                         |     Improve UX and user experience      |     2 weeks                       |  2 weeks

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
https://ethglobal.com/showcase/filestock-fdo7k
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project. 
- Simone Ruggeri: Project Manager simone.ruggeri81@gmail.com
- Roberto Barbone: fullstack developer barboroberto98@gmail.com
- Simone Russomanno: frontend developer simonerussomanno4@gmail.com
* How did you learn about our microgrant program? From the ETHGlobal SpaceWarp Hackathon 
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) ETHGlobal Spacewarp
  * Please link to your hackathon submission https://ethglobal.com/showcase/filestock-fdo7k

**Comment by eshon** [comment]
HI @RobertoBarb, 

This is a really nice project and we are interested in seeing it further developed. Can you please confirm that your team can implement the following if this microgrant proposal is approved?

- A fully working user-facing production deployment with nice UX that anyone can easily use.
- Deployed to Filecoin Mainnet (we can help cover the gas costs of smart contract deployment).
- A nicely curated collection of initial stock images for sale on your site from at least 25 unique photographers.

**Comment by RobertoBarb** [comment]
Hi Eva,
Thank you very much for your email and interest, we are definitely
committed to keep working on Filestock!
We confirm we are able to deliver the product with the features and
requirements you pointed out.

Waiting for further steps.
Thanks again
Roberto

Il giorno mar 18 apr 2023 alle ore 17:41 Eva ***@***.***> ha
scritto:

**Comment by RobertoBarb** [comment]
Hi @eshon , 

we are reaching the end of our MVP according to what you asked.

Considering we are ahead of schedule, before the official review for the second tranche could you be available for a quick meeting in order to have a look and discuss about eventual fixes or changes? That would be really appreciated. 
Thanks in advance, 

Roberto

**Comment by eshon** [comment]
Sure @RobertoBarb 

Next Wednesday the 28th does 15:30 CET work? If so I can send an invite.  Otherwise let me know what timezone you're in.

**Comment by RobertoBarb** [comment]
Yes, it works for us, thanks a lot

Il ven 23 giu 2023, 12:09 Eva ***@***.***> ha scritto:

**Comment by RobertoBarb** [comment]
Hi @eshon ,

Any news about the meeting? If you can send the meeting link or invite it would be really appreciated.

Thanks a lot

**Comment by RobertoBarb** [comment]
Hi @eshon can we reschedule the meeting? if possible at the same time, no matter which day, thank you

**Comment by RobertoBarb** [comment]
Hello @eshon any news?? Thank you

**Comment by eshon** [comment]
Hi @RobertoBarb - Sorry for the late response. I'm in CET / EU time, are you available tomorrow for a chat? Please grab a time here: https://calendar.app.google/D3V3yKrGMbaREzhn8

**Comment by RobertoBarb** [comment]
Hello I booked the meeting at 2:00 pm europe time. See you tomorrow.

Roberto

Il mer 26 lug 2023, 16:47 Eva ***@***.***> ha scritto:

**Comment by eshon** [comment]
Hi @RobertoBarb - I'm really sorry but I had to schedule another meeting for this time tomorrow. Is it possible to move your meeting to half an hour earlier / earlier in the day / after 15:00 CET?

**Comment by RobertoBarb** [comment]
Yes 15:00 is ok thank you

Il mer 26 lug 2023, 18:36 Eva ***@***.***> ha scritto:

**Comment by RobertoBarb** [comment]
Hi @eshon we finished the tasks for the second tranche of the grants as agreed

**Comment by RobertoBarb** [comment]
Hello @eshon any news? Thank you

**Comment by ErinOCon** [comment]
Hi @RobertoBarb, thank you for your project update! I have sent you an email regarding the second payment.
