### ISSUE TITLE
Automated Training Pipeline and 50 artist models for Algovera FVM AI-Art Attribution Project Stable Diffusion Model 

### ISSUE THREAD

**Issue by richardblythman** [filecoin-project/devgrants#1486]
### 1. What is your project, and what problem does it solve? (max 100 words)

The FVM Waterlily.ai project is an AI-Art Attribution Project being spearheaded by the Bacalhau team and highlighted as one of the main use case on FEVM at the 14 March FVM mainnet launch. This project aims to provide new revenue streams for artists and an ethical new paradigm for AI-Art by leveraging the utility of FVM for distributing artist royalties.

In a previous [grant](https://github.com/filecoin-project/devgrants/issues/1451), Algovera fine-tuned machine learning stable diffusion models on the work with the portfolios of 10 different artists. 

This grant will cover [Algovera's](https://app.algovera.ai/) work to automate this training pipeline so that it can be applied to a larger batch of initial artist models (50 total), and used to add new artist models at will over time. This is essential work to ensure the longevity and scalability of waterlily.ai on the FVM network.
 
Technical sponsors: [@DeveloperAlly](https://github.com/DeveloperAlly) [@aronchick](https://github.com/aronchick) and [@mishmosh](https://github.com/mishmosh)

### 2. Project links
  
Link to Github repo: https://github.com/bacalhau-project/Waterlily
Link to demo or website: https://www.waterlily.ai/
License: MIT

As mentioned, these models will belong to the artist and be secured privately on the Bacalhau network and not be available publicly to ensure the security of an Artists work, however all other parts of this project are open source, including documentation on how to create a similar model.

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

This project has been deployed to FVM mainnet. Bacalhau itself runs off IPFS and returns results as IPFS CIDs and stored on Estuary (IPFS & Filecoin)

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)

Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
- Build automated pipeline for training artist models (3 days)
- Run on work portfolios of 40 artists (3-4 days)
- Document process (1 day)
- Provide ongoing support for models in the following 2 weeks as needed

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes  

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
N/A https://app.algovera.ai/  

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Dr. Richard Blythman ([LinkedIn](https://www.linkedin.com/in/richard-blythman-64b2b948/), [Twitter](https://twitter.com/richardblythman))
Hithesh Shaji ([LinkedIn](https://www.linkedin.com/in/hithesh-shaji-141274159))
Mohamed Arshath ([LinkedIn](https://www.linkedin.com/in/mohamed-arshath-72152562))
Casey Clifton ([LinkedIn](https://www.linkedin.com/in/casey-clifton-22b9b9147/))
Jakub Smekal ([LinkedIn](https://www.linkedin.com/in/jakub-smekal/))

* How did you learn about our microgrant program?
Bacalhau team
* If your project was created as part of an event or hackathon:
N/A
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
N/A
  * Please link to your hackathon submission
N/A

### Relevant Experience

- Dr. Richard Blythman is an AI developer with 5 years of experience in industry, university, and startups with companies. He did his PhD with Bell Labs, before working as a machine learning engineer with Huawei Technologies and Xperi Corporation across a number of different products (publishing 5 ML patents including generative AI products and transformers, as well as a number of research publications). He has worked on several AI startups and as a research fellow at Trinity College Dublin.
- Mohamed Arshath is a machine learning engineer. He has experience building numerous machine-learning models. Apart from building models, he has experience building backend APIs and managing the backend on the cloud using docker and Kubernetes.
- Casey Clifton is a fullstack software developer and AI researcher. He has experience building a scaling numerous applications from AI medical imaging tools to a blockchain-powered rendering engine. He has also published research papers and completed industry and government R&D grants in these areas.

### Past Successful Project Delivery
Algovera has previously worked on several IPFS integrations:

- Python libraries for IPFS ([ipfspy](https://github.com/AlgoveraAI/ipfspy))
- Integrated IPFS with HuggingFace ([ipfsspec](https://github.com/AlgoveraAI/ipfsspec)) and ActiveLoop [Hub](https://github.com/AlgoveraAI/Hub)
- Integrated IPFS with Ocean Protocol
- Developed a decentralized hub for data scientists built on top of IPFS and Ocean Protocol
- Integrated IPFS with JupyterLab ([jupyterlab_extensions](https://github.com/AlgoveraAI/jupyterlab_extensions))
- Integrate Metamask, Ocean C2D and Lit Protocol with Streamlit ([streamlit-metamask](https://github.com/AlgoveraAI/streamlit-metamask), [streamlit-lit-nft](https://github.com/AlgoveraAI/streamlit-lit-nft))
- We’ve also worked with a variety of compute protocols and workflow orchestrators:
- Integrate [SAME project](https://github.com/SAME-Project/same-project/) with Ocean Protocol Compute-to-Data (C2D)
- Integrated Kubeflow with Ocean Protocol Compute-to-Data (C2D)

**Comment by ErinOCon** [comment]
Hi @richardblythman, we would like to move your proposal forward to the next steps in our process as an [Open Grant](https://github.com/filecoin-project/devgrants/tree/master/open-grants). We will send an email with further details.
