### ISSUE TITLE
Open Grant Proposal: Rubic Finance

### ISSUE THREAD

**Issue by IlyaStor** [filecoin-project/devgrants#1488]
# Open Grant Proposal: `Rubic Finance`

**Name of Project:** Rubic Finance

**Proposal Category:**  `app-dev`, `devtools-libraries`, `integration-adoption` 

**Proposer:** `IlyaStor`

**(Optional) Technical Sponsor:** `None`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** Yes

# Project Description

DeFi is a complex and rapidly-evolving space, and it can be challenging for both experienced users and newcomers to navigate the different features and platforms available. Cross-chain technology is a critical component of the DeFi ecosystem, as it enables users to access liquidity that is distributed across multiple chains. However, there are significant infrastructure limitations in the blockchain space that make it time-consuming and expensive for developers to create interoperable dApps that function seamlessly across different chains.
Rubic's solution addresses these challenges by providing users with a platform that offers the best rates, low fees, and fast transaction speeds for cross-chain trading. Our user-friendly interface and intuitive design make it easy for anyone to use, regardless of their level of experience with DeFi. Moreover, our platform is designed to be scalable, ensuring that we can support additional chains and provide users with access to liquidity across different ecosystems.
Our focus on providing tools and resources to help developers easily gain cross-chain operability for their dApps is a critical component of our platform. We believe that by reducing the time and resources required for developers to create interoperable dApps, we can help drive innovation and growth in the DeFi space.

## Value

_Benefits_: 

- Rubic is developed to bring significant value to other blockchains by enabling users to access liquidity and trade assets across different ecosystems. 
- By connecting to Rubic's ecosystem, blockchain projects can expand their user base, increase their liquidity pool, and provide their users with access to a wider range of assets. 
- Our technology allows fast and secure cross-chain or on-chain trading that enables Rubic to connect to different blockchain networks and facilitate transactions between them, regardless of their underlying technology. This means that blockchain projects can leverage Rubic's infrastructure to gain access to liquidity across multiple chains, without having to worry about the technical complexities of cross-chain interoperability. 
- Provided free for integration tools reduce a time and resources required to create interoperable applications letting users to make swaps at one place even without leaving dApp itself.

_Risks_: No risks, if there is any eligible bridge, DEX we connect Filecoin into our aggregator. 

_Executing risks_: Bridges are under hacker's attacks usually, but we have no risk in this regard, we have ability to shut off any of different bridges, any of different liquidity pools that were sourcing from at any given time. We do 24/7 monitoring, we have 24/7 support stuff as well. Someone is always present to be able to make sure the system is automatically doing what is needs to do.

## Deliverables

Rubic's cross-chain interoperability solution offers several deliverables that can bring value to other blockchains, including:

- Access to liquidity: By connecting to Rubic's network, other blockchains can gain access to a wider range of liquidity sources. This increases trading volumes, improves price discovery for assets, attracts new users and boosts adoption.
- Asset interoperability: Rubic's solution enables users to trade assets across different blockchain networks, which gives a growth to the utility and value of assets. This creates new use cases for blockchain projects and drives innovation across the ecosystem.
- New user acquisition: Rubic's platform is designed to be user-friendly and accessible attracting new users from other blockchain networks. By providing easy access to liquidity and assets, Rubic expands blockchain's user base.
- Reduced development time and costs: Integrating with Rubic's platform reduces the time and resources required to create interoperable applications. Our tools and resources make it easy for developers to integrate their dApps with our platform, which can accelerate their interoperability.
- Improved user experience: Rubic's platform is designed to provide a seamless and intuitive user experience for smooth user engagement and retention. By providing a fast and secure cross-chain trading experience enhances the overall user journey.

## Development Roadmap

We divide integration into three milestones:

- **Milestone 1**: 
_Planning the integration/Analysis_
Approximately 1,5-2 weeks
Deeper dive into the technical requirements of the Network; Analysis of existing bridge solutions; Analysis of existing DEX platforms on Conflux ; Analysis of community/developer engagement and potential marketing starting points
**Budget**: $10000
**Team members involved**: 7

- **Milestone 2**: 
_Finishing all analytics/ Start of the technical integration_
Approximately 1,5-2 weeks
Finishing all analytics; Starting with the implementation of the Conflux API into Rubic’s smart contract structure; Integration of Conflux into the Multi-chain protocol; Integration of Conflux into Rubic’s Routing AI; Further research and completion of marketing plan by marketing department
**Budget**: $10000
**Team members involved**: 7

- **Milestone 3**:
_Completion of Integration_
Approximately 1,5-2 weeks
Complete the integration by deploying Conflux into the Rubic platform UI; Deploy Conflux into Developer tools; Launch of marketing campaign
**Budget**: $10000
**Team members involved**: 7

## Total Budget Requested

**$30000**

## Maintenance and Upgrade Plans

Rubic makes Strategic Partnerships, Marketing and Promotion, User Incentives, Community Development, Continuous Platform's Development, Integrations of Rubic's tools as SDK and widget to projects from DeFi, GameFi, NFT, Lending protocols for valuable contribution to blockchain.
Another way for business is a focus on integrating with new and emerging blockchains that are gaining traction in the industry. By getting in on the ground floor with blockchains, Rubic establishes itself as an early adopter and building relationships with their communities, which lead to increased usage and adoption in the long run.

Our plans for future development where Rubic and Filecoin could find options for collaboration:

- NFT/GameFi widget (Widget for NFT swaps)
- NFT bridges aggregation
- Rubic’s new umbrella SDK that enables developers to aggregate the best Web3 cross-chain tech, from oracles and signals to tokens and NFT bridges, in ready-made templates for DEXs, lending/farming, and more.

# Team

## Team Members

Founders: 
- Vladimir Tikhomirov - https://www.linkedin.com/in/vtikhomirov/ 
Highly experienced and visionary founder, with a PhD in Computer Science and a successful track record as a software industry executive with over 10 years of experience, Vladimir brings a wealth of knowledge and expertise to the team. He is a seasoned entrepreneur, having founded the popular smart contract platform MyWish.io and the Polygon-based DEX Algebra
- Alexandra Korneva - https://www.linkedin.com/in/alexandrakorneva/ 
Alexandra Korneva brings a wealth of business acumen to the team, with a Master's degree in Business Administration and Management and extensive experience leading marketing and communication companies, including Hapax and AIESEC in Ireland.

The rest of the Rubic team is comprised of talented entrepreneurs and smart contract developers, with a wealth of experience in the industry and previous stints at renowned companies such as Microsoft, Motorola, Visa, and Unilever.

## Team Member LinkedIn Profiles

- Vladimir Tikhomirov - Founder - https://www.linkedin.com/in/vtikhomirov/ 
- Alexandra Korneva - Co-Founder - https://www.linkedin.com/in/alexandrakorneva/ 
- Evgenii Korol - CTO - https://www.linkedin.com/in/evgeny-korol
- Sven Michael - CBDO - https://www.linkedin.com/in/sven-michael
- Collin O'Brien - Head of PR - https://www.linkedin.com/in/collin-o-brien
- Ilya Storchilov - BD - https://www.linkedin.com/in/ilya-storchilov

## Team Website 

https://rubic.exchange/

## Relevant Experience

Rubic Finance boasts a talented and dedicated team of over 20 individuals from diverse regions including Eastern Europe, Germany, and the United States, with our headquarters and founder's residences located in Dubai, UAE. Our team is fully transparent, with all members publicly disclosed, and we have earned recognition from industry leaders such as Polygon, Harmony, Tezos, Bitgert, Symbiosis, Internet Computer, Hedera, Kava, NEAR for our outstanding contributions to the DeFi space. Team is experienced in the industry and previous stints at renowned companies such as Microsoft, Motorola, Visa, and Unilever.

## Team code repositories

https://github.com/Cryptorubic

# Additional Information

**Source of learning about the Open Grants Program** - Intropia
**Email of applicant** - `illya.storchilov@rubic.finance`
**Additional information** - At the moment of submission this proposal Rubic includes On-Chain & Cross-Chain swaps for Ethereum, BNB Chain, Polygon, Avalanche, Fantom, Arbitrum, Moonriver, Bitcoin, Solana, NEAR, Telos, Optimism, Celo, Fuse, OKExChain, Gnosis (xDAI), Moonbeam, Cronos, Aurora, Boba Network, Boba BNB, Boba Avalanche, Bitcoin, TRON, Kava, Oasis, Metis, Syscoin, Velas, Klaytn, Ripple, ICP, Cardano, Dogecoin, Polkadot, Litecoin, Monero, Algorand, Tezos, Dash, Zilliqa; with seamless fiat on-ramps and more. 
Rubic Finance is a platform designed to simplify the complexities of decentralized finance and provide users with efficient, low-cost, and fast cross-chain trading. We are similar to Google Maps in that we help users navigate the decentralized finance ecosystem by finding the best routes for completing trades across different blockchains.
Our platform is built on advanced technology and infrastructure that allows us to provide multiple routes for each trade, with the ability to quickly switch to alternative paths in case of congestion or system failures. This ensures maximum efficiency and minimal risk for our users.
We also recognize that cross-chain interoperability is a crucial challenge facing the blockchain industry, so we provide a range of tools and resources to help developers build cross-chain functionalities into their dApps, making it easier for them to achieve interoperability and increase liquidity.
In addition, we prioritize accessibility and user-friendliness. Our platform features an intuitive interface and user-friendly resources, making it easy for users of all levels of experience to navigate the complexities of decentralized finance.

**Total accumulated volume** - $320m+
**Total accumulated transactions** - 240k+

**Official links:**

Twitter  https://twitter.com/CryptoRubic
Telegram https://t.me/cryptorubic_chat
GitHub https://github.com/Cryptorubic
Medium https://cryptorubic.medium.com/
Discord https://discord.gg/zmf9QF2Vuh
Reddit https://www.reddit.com/r/Rubic/
YouTube https://www.youtube.com/channel/UCuFejvCuMtepW-4nx1DNFfg

In case you need to get in touch with Rubic directly use socials to reach me out via Telegram (@IlyaRubic) or Discord (Ilia#3116).

**Comment by ErinOCon** [comment]
Hi @IlyaStor, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. In case you have interest, here are a couple exchange integration guides that may be helpful: 

- [Exchange integration](https://docs.filecoin.io/reference/exchanges/exchange-integration/)
- [Exchange Integration Guide - FEVM Edition](https://www.notion.so/Exchange-Integration-Guide-FEVM-Edition-9fe9158360cf423da256b1bb1f47ff26#90ca58e1a2fb4236b73f676497118b76)

Wishing you the best as you continue to build!
