### ISSUE TITLE
Microgrant: Ecoland - EcoMarket

### ISSUE THREAD

**Issue by fac3m4n** [filecoin-project/devgrants#1492]
### 1. What is your project, and what problem does it solve? (max 100 words)
EcoMarket is a marketplace that offers it's users the ability to trade assets (buy, sell and bid) while yielding ecological benefits. 
It collects a small percentage of each transaction and uses it to purchase carbon credits from verified projects and plant trees through NGO partnerships.
The usage of the Tableland SQL tables will enable EcoMarket to directly index sales, bids, and receipts upon smart contract function calls. This will also enable server-side rendering for filtered/sorted queries without developing another solution to provide this (such as event listeners and indexers) at our Next.js dApp

### 2. Project links
  
Link to Github repo: https://github.com/ecoland-world/eco_marketplace
Link to demo or website: -
License:  APACHE2

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
It currently utilizes IPFS to host the asset's metadata and images of the items being sold.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Not atm, but we are planning to add it in the future...
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | Easy minting            | Smart contract factory to allow users to easily create a collection                                                           | 3 weeks                         | 
| 2.     | Built-in IPFS uploader  | Develop a good UI and experience using web3 storage UI components                                                          | 3 weeks                           | 
| 3.     | Metadata builder        | Develop an API endpoint that parses image data, description, and name into JSON and uploads to ipfs                                                            | 3 weeks                           | 
| 4.     |                         |                                                            |                            | 

### 5. If accepted, do you agree to share monthly project updates in this GitHub issue for 3 months or until the project described here is complete?
Yes

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: Tablelande Pilot Program
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Kevo - akerimberdi@gmail.com - https://github.com/fac3m4n - front end dev
Jovi - jvwfreire@gmail.com - https://github.com/joaovwfreire - fullstack and blockchain dev

* How did you learn about our microgrant program? - Tablelande Pilot Program
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) - Tablelande Pilot Program
  * Please link to your hackathon submission

**Comment by eshon** [comment]
Sorry for the late response @fac3m4n!

We'd need to see more use of FEVM for this project to be eligible for the current FVM Microgrant round.

Current possibilities for using FEVM are available in the hackathon tutorials for the OpenDataHack (see https://hackathons.filecoin.io/) and the [FVM cheatsheet here => see FVM starter kits](https://github.com/filecoin-project/awesome-filecoin/blob/main/fvm.md#fvm-starter-kits).

**Comment by ErinOCon** [comment]
Hi @fac3m4n, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant for this project. This proposal is very interesting and was strongly considered for a significant period of time.

Please feel welcome to contact our team at [grants@fil.org](mailto:grants@fil.org) with any questions. Wishing you the best as you continue to build!
