### ISSUE TITLE
Web Brain

### ISSUE THREAD

**Issue by alextitonis** [filecoin-project/devgrants#1493]
### 1. What is your project, and what problem does it solve? (max 100 words)
Web Brain is a NodeJS application that connects OpenAI GPT model with an easy to use behavior editor (morals, ethics, interests etc) and different clients to use the chat bot for communication (Discord, Telegram, Shopify and Unity).
Each user can connect using an account or a wallet, create a new Brain and select the personality and then Mint the brain, in order to trade it with other users.
After editing a brain, then the user will be able to set up the Client Settings (discord api key, twitter keys etc) and select the right Brain for the Chat Bot to run through.
The system will include chat history, emotions towards the user, able to talk in group and private chat and voice.

### 2. Project links
Client: https://github.com/Artificial-Leap/WebBrain-Client
Server: https://github.com/Artificial-Leap/WebBrain-Server
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
WebBrain is going to use IPFs to upload the Brain Files there.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
I will be able to hire a team, to help me with the development.
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
Milestone 1:
Simple Login, Register, Brain database system, using Express backend
Front-end editor and ui for login/register
Chat Discord Implementation
Telegram Chat Implementation
Unity Implementation
Milestone 2:
Add Voice Support for Discord, Telegram (voice messages) and Unity
Add Wallet Connection for Eth
Upload Brains into IPFs
Add Minting function for the brains

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

**Comment by alextitonis** [comment]
hey, are there any updates?

**Comment by ErinOCon** [comment]
HI @alextitonis, thank you for your proposal. We will not be proceeding with a grant at this time, but are wishing you all the best as you continue to build!
