### ISSUE TITLE
Next Step Microgrant: <Oasis Labs>

### ISSUE THREAD

**Issue by mmaheanhasan** [filecoin-project/devgrants#1494]
### 1. What is your project, and what problem does it solve? (max 100 words)
 

Oasis Labs is a revolutionary DAO-based platform that enables users to access funds and talent and collaborate to build real-time rendered 3D virtual worlds like personalized dreams with the help of generative AI and other AI algorithms. We harness the power of decentralized networks to foster creativity and teamwork while addressing the barriers to entry and collaboration in traditional 3D world-building. Imagine you are playing DnD, and you speak, and the world, monsters, and adventure are all generated in front of you, fully rendered, in real time. That's our collective dream that traditional means won't be able to do.

### 2. Project links
  
Link to Github repo: https://github.com/mmaheanhasan/OASIS-Labs
Link to demo or website: https://devpost.com/software/oasis-labs
License:  MIT license

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

As Oasis Labs was created solo in just 5 days, as my first hackathon experience, I was only able to use NFT.storage for securely storing NFT metadata. However, if I were to build it today or tomorrow, I would leverage IPFS for content-addressable, distributed storage of 3D assets, with Filecoin's decentralized storage to ensure data redundancy, and its smart contracts service to facilitate the governance and funding mechanisms within the DAOs.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
  YES
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | Integrate Filecoin Virtual Machine (FVM) for smart contracts and Layer 1 services                        | Research FVM capabilities, design appropriate contract structures, and integrate FVM into the Oasis Labs platform for seamless execution of smart contracts                                                           | Month 1                           | 
| 2.     | Develop user-friendly interfaces for creating and managing DAOs                        | Research UX/UI of existing successful DAOs to design and create intuitive interfaces, ensuring ease of use in DAO creation, management, and collaboration                                                           | Month 1-2                           | 
| 3.     | Create a strong talent-matching system to connect users with the right skills to build things such as AI-powered NPCs and develop intelligent AI agents through research.                        | Develop an algorithm to analyze user profiles, skill sets, and interests to match them with suitable projects, enabling collaboration on things like AI-powered NPCs and intelligent AI agent research                                                           | Month 1-2                           | 
| 4.     | Create a marketplace for 3D assets, monetized through NFTs and powered by Filecoin                        | Design and implement a decentralized marketplace for buying, selling, and trading 3D assets, utilizing NFTs for asset ownership and powered by Filecoin for secure, decentralized storage. TO END WITH, I will most likely be attending Buildspaces N&W-3, so I will take six weeks to complete most of the things I described, certainly an edge.                                                           | Month 2-3                           | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete? 

  
Definitely!

### 6. Does your proposal comply with our Community Code of Conduct?
 

Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
Yes, in fact, I won the first prize of $5000 in Filecoin's Metaverse, DAO, Gaming, NFT category. Here's the Devpost link: https://devpost.com/software/oasis-labs

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
 
Mohammad Mahean Hasan; mmaheanhasan@gmail.com; https://github.com/mmaheanhasan; Creator

* How did you learn about our microgrant program?

Niki Gokani from Protocol Labs sent me an invitation to apply for the accelerator program, and later told me that if I am not ready, I can start with microgrants.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)

Chainlink Fall Hackathon 2022

  * Please link to your hackathon submission

https://devpost.com/software/oasis-labs

**Comment by ErinOCon** [comment]
Hi @mmaheanhasan, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!

**Comment by mmaheanhasan** [comment]
@ErinOCon Thank you for taking the time to review this proposal. I would greatly appreciate your feedback on the project. I have gone through several iterations and currently on a pretty exciting track. Can you leave some reviews on this idea I originally put?

**Comment by ErinOCon** [comment]
Hi @mmaheanhasan, thanks for following up! Adding @eshon to provide additional insight.

**Comment by eshon** [comment]
Hi @mmaheanhasan,

- It looks like this project has already won $5k in a Chainlink hackathon.
- The current planned scope is too broad and not attainable near-term. It does not have appropriate scope for a $5k FVM microgrant.
- Also I could not find any smart contracts in your Github repo and you have very limited Github history.
- Note that this particular microgrants round is focused on the Filecoin Virtual Machine (FVM) and what is unique to the FVM which you can read more about in the Filecoin Docs.

Therefore we did not approve this proposal.

**Comment by mmaheanhasan** [comment]
Thank you. I understand all of those points, and as I mentioned earlier, I have iterated a lot. May I please reapply soon with more specific points while addressing all the necessary components? I have specific concepts in mind for the iterated idea that need to be implemented in the Filecoin ecosystem as a whole and would need help.
