### ISSUE TITLE
Next Step Microgrant : IPFSpace on FVM

### ISSUE THREAD

**Issue by ZhangPeibin** [filecoin-project/devgrants#1496]
### 1. What is your project, and what problem does it solve? (max 100 words)
IPFSpace aims to build Decentralized DataSharing Infrastructure. 

IPFSpace‘s mission: “To store the world's data and share it to the world.

IPFSpace's deck link: https://hub.textile.io/ipfs/bafybeicgdjsy77vg3ilg5c5he2kxjeogqx6t3oceockm5zdb4hinvbthyy

We have received wave 9 funding before, but the wave 9 funding is to support us to complete this project in the polygon network. We completed this project as planned, but we ultimately hope to build this project on FVM. The purpose of our application for this grant is to launch our project on FVM and unite with the community to complete a content sharing platform based on FVM

You can check our project here : https://github.com/filecoin-project/devgrants/pull/283

 Problems:
 - Identity information is controlled by the service platform
 - Centralized storage of data, controlled by centralized service providers, very insecure
 - The data storage platform is too differentiated, and the life cycle may be short (burning money to death)
 - The data storage platform charges fees by controlling download speed and other unreasonable behaviors
 - The resource link of the data is easy to expire and lose, resulting in the data cannot be retrieved
 - Data cannot be shared effectively (data is controlled centrally and cannot be shared)
 - Duplicate data and excessive junk data make data acquisition difficult
 - Content creators cannot transfer data to other platforms (data will be lost if the platform account is cancelled)
 - Data sharing and reward economy are difficult to combine

Solution:

- All data are built on the next protocols that power the web3 (IPFS,Filecoin,Textile,NFT.storage,Web3.storage)
- Decentralized registration brought by blockchain
- Decentralized Sharing based on Token Economy System
- Decentralized Searching based on data's metadata （also rewards on Token Economy System）
- Data generates NFT and on-chain transaction

### 2. Project links
  
Link to Github repo:
https://github.com/ZhangPeibin/IPFSpace
Link to demo or website:
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
We are building a decentralized content sharing platform, all data can be traded in our NFT market .
 Our storage core is IPFS/Filecoin, and all data is stored in IPFS/Filecoin
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
We used polygon to build the trading market in wave9. With the launch of FVM, we plan to use this fund to migrate our project to FVM and finally complete the content sharing platform based on FVM

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
yes

  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
All is here : https://github.com/filecoin-project/devgrants/pull/283
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  ZhangPeibin  , wiki4zhang@gmail.com

* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by eshon** [comment]
@ZhangPeibin - https://www.anipfs.space/ does not load. https://hub.textile.io/ipfs/bafybeicgdjsy77vg3ilg5c5he2kxjeogqx6t3oceockm5zdb4hinvbthyy also does not load. Please provide a link to a live working demo for microgrant consideration.

**Comment by ZhangPeibin** [comment]
@eshon anyupdate?
