### ISSUE TITLE
Matanglawin- Data Analytics for All Scale

### ISSUE THREAD

**Issue by MrDrolyaj** [filecoin-project/devgrants#1499]
# Open Grant Proposal: `Matanglawin- Data Analytics for All Scale`

**Name of Project:Matanglawin**

**Proposal Category:**  `app-dev`

**Proposer:** `MrDrolyaj`

**(Optional) Technical Sponsor:** 

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** Please respond with either "Yes" or "No"
Yes

# Project Description
The Philippines is a developing country, with major industries in agribusiness and fisheries. Filipinos working in these sectors are among the individuals with the lowest-paying jobs. They provide our basic needs and necessities. Despite having access to mobile phones and the internet, innovations are lagging because information and awareness aren't properly spread. We are rich with data that is waiting to be explored and benefited from. Our goal is to empower all—individuals or employers, and owners of small or large businesses, primarily working in the agriculture and fisheries sectors. 
This project seeks to mitigate the effect of poverty with data-driven decisions using AI and statistical analysis in a mobile app. People in these sectors will be able to manage their resources and assets wisely, apply risk assessment, and predict consumption trends within their sector. This means that the app will be simple enough for the users to input basic known data, and the rest of the complex data will be concatenated, which will be researched beforehand by the team. The data includes databases, images from computer vision, and data input by the users, all of which will be stored and extracted using Filecoin.
This process will be done in real-time; visualizations and statistical analysis will be updated from time to time, and will alert the user depending on the predictions by the AI/ML models used; thus, data transfer will be communicated with an API. One of the goals of the app is to give users a maximum multiplicity of output while minimizing the loss of capital or assets. 

## Value
This project will in turn funnel data into a transparent and secure blockchain, that is the Filecoin ecosystem. The entire process will be dependent on the scalability and data transaction rate that Filecoin can handle, especially for dealing with big data. If we get this right, the user, i.e., farmers or fishermen will get to receive real-time predictions and act intelligently, and in return provide input data to databases. If the process is jeopardized, the results will say otherwise.  

## Deliverables
- Flutter mobile app that has visualization and analytics interface.
- Python API for AI and statistical tools
- Python library for Filecoin integration

## Development Roadmap
**Milestone 1 – Conceptualization and Framework Building Phase**
We will research common problems and needs encountered in these sectors, as well as the behavior of the users. This is to ensure only relevant and simple input from users will be needed without compromising the output. Next is the outlining of the technical details of data flows from the user to the Filecoin ecosystem, vice versa, including the algorithm as implemented in the Flutter app. Then, we do data collection of relevant cases. Consequently, we will be able to map out the UI/UX flow of the architecture, from authentication to data transference and output; thus, basic framework of the app is expected here.
People: Project Manager/ UI/UX designer, Full-stack mobile developer, Data Scientist, Blockchain Engineer
Estimated time: 1 month (5/01/2023 - 6/01/2023)
Budget: 4 persons x 1 month x $2500 = $10000 

**Milestone 2: Data Flow Implementation**
In this phase, we will work with data transference. We will create:
- a python API for communicating AI/ML models and statistical tools (sci-kit and tensorflow) and data to the user, vice versa through the Flutter app. 
- connection of Filecoin API to the Flutter app using Estuary, and pin researched data and from that of from the user. A part of this is to ensure proper communication of Filecoin to concatenate relevant data and store SQL databases for querying in real time.
People: Full-stack mobile developer, Data Scientist, Blockchain Engineer
Estimated time: 3 months (6/01/2023 - 9/01/2023)
Budget: 3 persons x 3 months x USD2500 = USD22500 

**Milestone 3: Security Layer and App Finalization**
We will integrate tokenomics using Filecoin to incentivize the users while allowing a more secure authentication mechanism. This will give the users ability to add more values to the existing databases stored in the Filecoin ecosystem. If there occurs any loopholes during alpha tests, we will redesign the algorithm, probably adding another security layer as researched by our blockchain engineer and improve on existing one to make sure security is not compromised. The UI/UX flow will also be improved owing to the implementation of the previous milestone. 
People: Full-stack mobile developer, Data Scientist, Blockchain Engineer, UI/UX designer
Estimated time: 2 months (9/01/2023 - 11/01/2023)
Budget: 4 person x 2 months x USD2500 = USD20000 

**Milestone 4 : Beta Testing and Collaboration**
This phase includes creating community of farmers, fishermen, or any interested researchers in this field. We will collaborate with universities and local government units such as the Department of Agriculture and the Department of Fisheries to implement the tool and improve on the feedback received. This will also allow more data-driven participants into the Filecoin community. This also includes the improvement and deployment of the current website.
People: Project Manager, Blockchain Engineer, Data Scientist
Estimated time: 1 month (11/01/2023 - 12/01/2023)
Budget: 3 person x 1 month x USD2000 = USD6000

## Total Budget Requested
Total: USD58500

## Maintenance and Upgrade Plans
We will update our models and databases to ensure accurate results for the users. We will make data policy and plan on making the databases open source. Through further collaboration and funding, we will scale up the application to other businesses and individuals in other industrial sectors and make an enterprise account.

# Team

## Team Members
- Jaylord Veloso- Project manager/ UI/UX designer  
- Noli Maaghop- Statistican  
- Jhay Castillo- Full-stack developer  
- Isnaina U. Abdulazis- Web developer/ Marketing Specialist
- Anne Hayathi S. Albiso- Full-stack developer
 
## Team Member LinkedIn Profiles

- [linkedin.com/in/jaylord-veloso-1a8148245/](https://www.linkedin.com/in/jaylord-veloso-1a8148245/)
- [linkedin.com/in/noli-maaghop-8848b6262/](https://www.linkedin.com/in/noli-maaghop-8848b6262/)
- [linkedin.com/in/jhay-castillo-597706171/](https://www.linkedin.com/in/jhay-castillo-597706171/)
- [linkedin.com/in/isnaina-abdulazis-8b8170259/](https://www.linkedin.com/in/isnaina-abdulazis-8b8170259/)
- [linkedin.com/in/anne-hayathi-albiso-86a36b238/](https://www.linkedin.com/in/anne-hayathi-albiso-86a36b238/)

## Relevant Experience
Matanglawin was founded recently with the goal of furthering blockchain awareness and implementation in the country. We also plan on hiring several specific roles for this project as follows:
- Back-end developer with experience in building blockchain 
- Senior Data Scientist

To mention the relevant experience of the team: Jaylord Veloso has a Master’s in physics with experience in computational methods for solving complex systems using object-oriented programs such as C++ and Python, and currently applying machine learning techniques in these fields; Jhay Castillo has 6 years of experience as a full-stack developer mainly working with MERN stack plus Laravel. He is also a graphic designer and currently building business digital solutions.; Anne Hayathi Albiso is professionally a quality assurance engineer, and spent building apps in various stacks such as Flutter; Noli Maaghop is a statistician with interests in Bayesian statistics applied for real-life cases such as COVID-19 evolution, and; Isnaina Abdulazis is a seasoned WordPress developer primarily applying her skill as a UX designer and at the same time a marketing specialist applying SEO for contents. 

## Team code repositories
https://github.com/Matanglawin-Data
https://github.com/jhayforshort15

# Additional Information
Through research prior to conceptualizing this project, we have learned about this grant and we plan to further contribute to the constant transference of data to the Filecoin ecosystem through incentivization of the users and collaboration with local government units for the outreach program. 
Prior to the creation of the team, which was only 2 weeks ago, the Project manager conceived and kickstart the idea, including the bare website and UI/UX of the app. He could only do a part, but not the entire project as his skills is limited to the aforementioned outputs. The rest of the team works full-time feeding their family so as of now they couldn't dedicate a time to move the project forward; however, with the help of the grant they assure they would commit to give their best to the success of the project. This entails starting to work with the code and the app to be uploaded in the github repo. Collectively with the future hire, we believe this project will be feasible and would successfully follow the milestone.

**Comment by ErinOCon** [comment]
Hi @MrDrolyaj, thank you for your proposal. Unfortunately, we will not be proceeding with a grant at this time. Wishing you all the best as you continue to build!
