### ISSUE TITLE
 Open Grant Proposal: Acrontech Cloud Platform

### ISSUE THREAD

**Issue by TinySwitcher** [filecoin-project/devgrants#1500]
# Open Grant Proposal: `Acrontech Cloud Platform`

**Name of Project:** Acrontech Cloud Platform

**Proposal Category:**  `integration-adoption` 
**Proposer:** `TinySwitcher`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** `No`

# Project Description

Acrontech is a technology services company based in Delaware, USA, specializing in distributed storage technology based on the IPFS protocol. We are trying to establish a cloud platform for Filecoin SP community.

Extensive expertise required in many technical domains:
-  Data Center Colocation
-  how to select cost effective hosting data center from marketplace?
-  Architecture Design
-  What to buy, where to buy them, how to get most cost-effective hardware?
-   How to design an effective configuration that will be reliable and resilient?
-   Implementation
-   Standing up – Racking/stacking/installation
-   Go live - Configuration/testing/
-   Operation – Keep the lights on, always on
-   System upgrade and maintenance
-   Break and fix, Tech refresh
Skills needed: hardware, software, OS, network, storage, Lotus, Mining operation, etc, etc.
A full-scale IT team is needed to pull it off

Established storage providers may have overcome many challenges, but still facing new ones:
-   Ever evolving technical requirement
-   Identity shift : from Filecoin miner to a client facing storage provider
-   Customer Relationship Management
-   Real data cap process
-   Sealing and storage real data
-   Bear market dilemma : To Mine or Not To Mine?
-   How to keep existing seal datasets safe and secure for 18 months duration?
-   How to embrace FIL+ and continue expand capacity?
-   How to maintain positive cash flow during bear market?

Filecoin implementation, in many ways, resembles enterprise-level data center computing; 
They come up with Cloud Service to address those questions in the last 3-4 decades. 
- Virtualization – virtualize everything
- Software Defined Infrastructure
- Infrastructure as Code
- Container Technology
- Automation

We trailblaze Filecoin implementation through enterprise-level architectural design, deployment, and operation. Based on the cloud operational model, Acrontech Cloud Platform can provide different kinds of services to SPs with flexibility and cost efficiency. We aim to help SPs solve challenges and attract more of them to the ecosystem.

## Value
**Why Storage Providers Choose Us**
<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">

</head>

<body>

  | Self-Owned   Bare Metal | Acrontech   Cloud Solution
-- | -- | --
Hardware Procurement | Unpredictable shipment;    uneven hardware price;   high-cost labor;   time wasted on mounting and   testing | Flexibility Availability,    enough storage stock;    on-demand renting;    significantly time-saving
Sealing | Unnecessary budget waste;    Capacity spared | On-demand renting;   large-scale sealing capacity;   Up to 50% CapEx   saving
Operation | 7x24-hours monitoring and   operating,    needs lots of maintenance   engineers,    high labor costs | Full-automatic monitoring and   alerting;   Tier 3 IDC guarantee;   Standard workflow;    high fault tolerance
Network | Bandwidth limited;    network connection failure;    unstable upload/download speed | Backbone network supported;   Large bandwidth;   high-efficiency network usage;   stable network connection

</body>

</html>

## Deliverables

**Sealing as a Service, rent sealing capacity by TiB per day.**
- Pre-commit sealing capacity if the user chooses our storage service in the same IDC. 
- Remote Sector Upgrade service (This could be a top-rated service in the future, but internet bandwidth will be a challenge )  

**Storage as a Service, rent storage with full life-cycle management.**
- ZFS storage for cold storage(sealed, cache, real-data)
- Object storage with high performance (unsealed, retrieval)
 
**Utilization as need**
- Rent VMs for node, miner, market, retrieval, and all other purpose related to SP’s operation.
- We can also operate everything for Investors/Data clients. 

## Development Roadmap
By 2023, Acrontech is establishing the Acrontech cloud platform for global storage providers. We will complete the construction of nodes in Europe, North America, and Australia.

## Total Budget Requested

100K Dollars， for expand our technical team and prepare for rapid expansion. 

## Maintenance and Upgrade Plans

We will update our models and databases to ensure accurate results for the users. We will make data policy and plan on making the databases open source. Through further collaboration and funding, we will scale up the application to other businesses and individuals in other industrial sectors and make an enterprise account.

# Team

## Team Members

**Tao Tao**
Acrontech Inc. CEO
Senior Information Systems Infrastructure Expert

Professional Experience:
- Chief Technology Officer, Place Properties, the largest student housing developer in the US.
- Director of Information Systems Technology, McCalla Raymer, et al, the largest real estate bankruptcy law firm in the US.
- Senior Solution Architect, Data Center Business, Accenture, Ernst & Young US.
- Chief Architect, Enterprise Data Center Business, Hewlett Packard Enterprise, HP US.
- Enterprise Architect, Dell Strategic Services Center, Dell Technologies, Dell US.
- Senior Partner, Data Center Business, DXC Technology, DXC.
- Senior Partner, Strategic Services Division, ICF, (focus on CDC data business).

**Mark Ma**
Acrontech Inc. CTO
Senior Systems Architect
Ma has over 20 years of industry experience, specializing in helping enterprise-level clients effectively utilize emerging technologies to achieve their strategic goals. As a senior consultant, he has served Fortune 50 companies and is skilled at balancing strategic direction with technical depth based on the needs of information technology executives and business leaders. In cloud computing, he leads various technical teams and implements solutions.

Professional  experience:
- Chief Enterprise Cloud Architect, VMware, with clients including top international enterprises such as Citibank, Mercedes-Benz, and Toyota
- Chief Solution Architect, CentriNet, led consulting team to double revenue
- Chief Hybrid Cloud Builder, DynaSis/Novatech, led cloud computing department and pioneered global cloud deployment for clients in the industry.

**Devin Chen**
Acrontech Inc. Network Engineer
Computer network management expert

Professional  experience:
- President, Canopus Enterprise Inc., Canada, the PEI region's number one computer system maintenance provider.
- Chief Technology Officer, Beijing Xinlian Yutong Technology Service Co., Ltd.
- Chief Technology Officer, PUSP Information Technology Service Center.

## Team Member LinkedIn Profiles

[**Tao Tao**](https://www.linkedin.com/in/tao-tao-1560a04/)
[**Mark Ma**](https://www.linkedin.com/in/markpower60/)
[**Devin Chen**](https://www.linkedin.com/in/devin-c-26b625bb/)

## Team Website

http://acrontech.us

## Relevant Experience
Acrontech has a technical team of more than 25 people,especially in the fields of virtual machine and information system 
architecture construction, with an international first-class standard.  Core members have previously worked for internationally renowned technology companies such as HP, Dell, Accenture, and VMware. Acrontech's clients include Toyota, Daimler-Benz, and Wealthfront Bank.
Acrontech Inc. offers state-of-the-art VCF cloud architecture technology that allows for dynamic reallocation of resources in near real-time, achieving optimal efficiency. Combined with scalable and cutting-edge automation, we provide the most cost-effective one-stop Filecoin mining technology services, ensuring the best return on investment.

## Team code repositories

# Additional Information
**How did you learn about the Open Grants Program?**
Mara McMahon,one of your colleages, introduce us

**Please provide the best email address for discussing the grant agreement and general next steps.**
info@acrontech.us

**Please include any additional information that you think would be useful in helping us to evaluate your proposal.** 
some investment institutions have shown great interest in our cloud platform. We are currently conducting A-round financing to expand our technical team and prepare for rapid expansion. we hope Protocol Labs and Filecoin Foundation can symbolically act as a lead investor to bring greater confidence to any other investment institutions who will invest us.

**Comment by ErinOCon** [comment]
Hi @TinySwitcher, thank you for your proposal. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!
