### ISSUE TITLE
Next Step Microgrant: IPFS Supply Chain Assurance

### ISSUE THREAD

**Issue by flororsi** [filecoin-project/devgrants#1501]
### 1. What is your project, and what problem does it solve? (max 100 words)

The objective of the project is to create a secure and transparent supply management solution that can safely deliver high-value goods from suppliers to clients through carriers, without any tampering. Digital signatures are used to authenticate and validate the transactions and goods at every stage of the supply chain.

As a result, the system provides a reliable way to prevent fraud, enhance the security of the transportation process, ensure transparency and security for all parties involved, and ultimately improve customer satisfaction.

### 2. Project links
 
Link to Github repo: https://github.com/turtle-chain/IPFS-Supply-Chain-Assurance
Link to website: https://turtle-chain.github.io/IPFS-Supply-Chain-Assurance1/
Link to video demo: 
https://www.canva.com/design/DAFeldyHxQE/2XNm66_baNC-bxZG6o8JiQ/watch?utm_content=DAFeldyHxQE&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink
License: open
 
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
IPFS is used to share photos of goods sent to the customers by the supplier. As they are digitally signed,
and the hash is stored in one smart contract,in the event that the customer doesn’t receive what he ordered,
they will be able to verify the goods with the photo of the original CID, since its hash is stored in the smart contract
### 4. How will you improve your project with this grant? What steps will you take to meet this objective?

 
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       |
| 1 |New branding  | We want to improve the aesthetics of the company along with its functionality.| 1month |
| 2.     | Better notifications | We want to improve our customer notification channels.|1 month |
| 3.| Automatic validation | Use of AI algorithms to assess the accuracy, reliability, and authenticity of images. |    1 month                        |

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes
 
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

Not aplicable.
 
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Gregorio Kominiarz, grego02@gmail.com, https://github.com/grego02 , Solidity developer
Florencia Capmourteres, flororsi@gmail.com , https://github.com/flororsi, Front-end developer.
Damian Doña, damianedona@gmail.com, https://github.com/damian-bit , Full-Stack developer

* How did you learn about our microgrant program?
Recommendation from a friend.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

Not aplicable.

**Comment by ErinOCon** [comment]
Hi @flororsi, thank you for your proposal and for your interest in our grants program. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
