### ISSUE TITLE
Block Crawler Grant Application

### ISSUE THREAD

**Issue by Zettafi** [filecoin-project/devgrants#1502]
# Open Grant Proposal: `Block Crawler Grant Application`

**Block Crawler:**

**Proposal Category:** `devtools-libraries`

**Proposer:** `jchysk`

**(Optional) Technical Sponsor:** `NA`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** "Yes"

# Project Description

We built an open source high-performance ETL framework for blockchain data designed to process blockchain data and transform it into useful datasets in the easiest way possible. We will configure it for free to collect any dataset for you. 

Block Crawler creates datasets from blockchains and provides it to those who are building applications. Its high-performance, open-source ETL framework is designed to process massive amounts of blockchain data and transform it into useful datasets in the easiest and most expedient way possible. With Block Crawler, anyone can extract any blockchain data from EVM RPC APIs like Ethereum, Polygon, and more, transform it into desired datasets, and persist it into databases to support data access requests on historical and real-time data. Furthermore, the Block Crawler's modular components can be combined with dataset specific components to cater to the unique requirements of every user.

Whether a blockchain looking to improve data availability or a blockchain application needing a specific dataset, we are creating a product where data consumers tell us what data they need, and we configure the Block Crawler for them and work with them to extract, transform, and load the data.

While open-source data extraction tools for overly generic or specific niches are emerging, there is currently no high-performance framework for creating and maintaining robust datasets from Blockchain data. We are hoping to accomplish the goal of improving accessibility to valuable datasets. We would define success for this grant to be extracting, transforming and loading valuable datasets from any blockchain into a database of your choice. The scope of the grant would depend on the volume and complexity of the datasets requested. We would consider this project successful if we improve data accessibility in the blockchain industry.

## Value

If done right, It will allow you to extract any dataset from any blockchain you might find valuable now and into the future. This will ensure you have access to the data you need to display the complex analytics dashboards, make important internal business decisions and analyze on chain behavior. We can load any historical dataset you want into a database to perform data science as well as loading real-time data into a database you can query with an API.

Besides funding, one of the challenges faced is that we're finding that contracts created by contracts that do not adhere to standard identification of contract creation with a null "to" address in the transaction. We have not fully solved the issue yet, as there is no standard way to identify contract creation. We have implemented a workaround for forcing the load of a contract, but this is a one-at-a-time procedure as we identify missing contracts.

## Deliverables

The core deliverable of the Block Crawler is a high-performance parallel processing data bus that allows data to be passed between the various components implemented. First, data is fed to the data bus which provides the data to the various components that transform the data and feeds it back into the data bus. This transformation process continues until the data has reached its final form and is then persisted. 

## Development Roadmap

The initial consultation and configuration of Block Crawler is free. We will work with your team to identify important datasets, configure the Block Crawler for you to extract those datasets and assist you with loading those datasets into the database of your choice. After this initial milestone, the long-term engagement would depend highly on the project's scope. The volume and complexity of the data extraction would impact the cost and future milestones.

As mentioned, the initial configuration and consultation would be free and the software is open source. We have a team of 6 engineers working to increase data availability in the blockchain industry. The funds would be used to shift the focus of those team members from their usual day-to-day activities to fulfilling the requirements of our engagement. This cost is variable depending on the scope and level of skill necessary for your needs. 

## Total Budget Requested

We are offering the initial configuration and consultation for free and the software is open source. After the free initial engagement, we would be looking for anywhere from $10k to $50k depending on the scope of the ongoing work.

## Maintenance and Upgrade Plans

# Team

## Team Members

Yo Sub Kwon is the CEO of ZettaFi team and has co-founded Coinsetter, which was acquired by Kraken and LaunchKey and is now owned by TransUnion. He started mining Bitcoins in 2010 and also co-founded Hosho Group, a smart contract security analysis firm in 2017. 

Cylus Watson, CSO, is a serial entrepreneur in the blockchain space, having launched a consulting firm and two hedge funds with consistent success in identifying and capitalizing on trends, as well as being a leading yield-farming expert. 

Adam Englander, Director of Engineering, is the founder of two successful developer groups and maintainer of Pallets (including Flask). He is also a voting member of the Python Software Foundation and a global speaker on cybersecurity.

## Team Member LinkedIn Profiles

Yo's LinkedIn: https://www.linkedin.com/in/jchysk/
Yo’s GitHub: https://github.com/jchysk

Adam's LinkedIn: https://www.linkedin.com/in/adamenglander/
Adam’s GitHub: https://github.com/aenglander

Cylus's LinkedIn: https://www.linkedin.com/in/cylus-watson-064190157/
## Team Website

https://drive.google.com/file/d/1Wcfz3Yr9ybrWAvblFhpyq__L8uYxeK7K/view?usp=share_link
https://zetta.fi/

## Relevant Experience

Our team consists of nine full-time staff members who work remotely globally. This includes six engineers with multiple proficiencies in cybersecurity, blockchain technology, distributed systems, and large-scale systems. The engineering team has reputable distinctions as maintainers of highly popular open-source projects, founders of developer groups, and regular speakers at events worldwide.

## Team code repositories

https://github.com/block-crawler 

# Additional Information

The best email address for discussing the grant agreement and general next steps is grants@zetta.fi

We are currently doing market research into what datasets are difficult to extract from blockchains and are considered valuable. Our open source software is capable of being configured to extract, transform and load any dataset but we are still unsure about which datasets the industry considers most important to extract. In addition to financial support, or even instead of financial support, we would appreciate the ability to ask some questions about your data needs and any pain points you have experienced when dealing with blockchain data.

**Comment by ErinOCon** [comment]
Hi @zettafi, thank you for your proposal. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
