### ISSUE TITLE
Next Step Microgrant: Store Don

### ISSUE THREAD

**Issue by armanthepythonguy** [filecoin-project/devgrants#1504]
### Brief idea about the project
Using our product you can store large files in Filecoin in a very decentralized and simple manner. Currently, you can either use products like web3. storage, NFT.storage, LightHouse, or store directly using Lotus. The applications mentioned earlier are not useful when it comes to commercial storage of data although the process is very easy. Using Lotus is not that simple as you need to manually install a Lite node, find miners and interact with them to fix a rate and store data. Now, coming to our application, you can use it for all your storage needs, and it's very easy to use. We are using an orderbook-based mechanism where clients and SPs can fill up their bids and asks. Our order matching engine will generate orders in a decentralized manner using FEVM to verify the orders. Once the orders are verified, oracles will act as lotus lite nodes and send the data to the particular SP to store. The SP can later come to the smart contract and collect the submitted bounty by the client. As implementing Orderbook in solidity is not efficient, we are using oracles to match the orders. Once the orders are matched, the oracles submit it to the FEVM smart contract and if we have more than 51% vote for a particular order from all the oracles, the oracle will pass on the data to the SP, who will create a deal. Later we have plans to launch an L2 on top of FEVM, with all these oracles features in-built.

### Deliverables
An end to end platform for both normal web3 clients as well as business clients to store bulk data in Filecoin with the best possible rates available. A simple UI/UX for normal user to store data and a stable API for business clients to store bulk data seamlessly in Filecoin.

### Useful Links
Link to Pitch: https://www.canva.com/design/DAFd_-aVmAM/TQDhqOx_0ES9y0T07--LDA/view?utm_content=DAFd_-aVmAM&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink
Link to Github repo: https://github.com/armanthepythonguy/StoreDon-FEVM-ETHFORALL
Link to Devfolio project: https://devfolio.co/projects/store-don-455f
Link to Youtube video: https://youtu.be/Sag1wFHP4wU  
License:

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

We use FVM to store data in a decentralized manner using the oracles. The oracles need to interact with the smart contract in order to find matching deals for them. Moreover, we will be using Lotus clients over in oracles for creating deals.
###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes, FVM is the core of our project.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |  Launching alpha version in mainnet                |         Creating oracle networks, proper UI/UX for normal clients and API for business clients                                                   |            1 month                | 
| 2.     |              Launching testnet of the L2 based on FEVM           |                           Creating an optimistic rollup using OpStack provided by Optimism to increase the transaction speed                               |            2 weeks                | 
| 3.     |               Integrating L2 and oracle        |                           We will be integrating both oracle and the L2 solution, so as to end the dependence on a different network of oracles as we will be having oracles in-built in our L2                                 |              1 month 2 weeks              | 

### 5. If accepted, do you agree to share monthly project updates in this GitHub issue for 3 months or until the project described here is complete?

Yes, I agree to share monthly project updates.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* We created this project during the ETHForAll hackathon, organized by ETHIndia and Devfolio. Our project was one of the top 3 hacks in the Filecoin track. Below is the link to the project:
* Link to Devfolio project: https://devfolio.co/projects/store-don-455f
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Arman Aurobindo, armanityours@gmail.com, @armanthepythonguy, Solidity and backend dev
* How did you learn about our microgrant program?
* Filecoin website
* If your project was created as part of an event or hackathon:
  *  We created this project during the ETHForAll hackathon, organized by ETHIndia and Devfolio. Our project was one of the top 3 hacks in the Filecoin track. Below is the link to the project:
  * Link to Devfolio project: https://devfolio.co/projects/store-don-455f

**Comment by ErinOCon** [comment]
Hi @armanthepythonguy, thank you for your proposal and for your patience with our unexpectedly long review process. Unfortunately, we will not be moving forward with a grant. Wishing you all the best as you continue to build!
