### ISSUE TITLE
Next Step Microgrant: Clover; G-Suite for DAOs.

### ISSUE THREAD

**Issue by Temiloluwa-ade** [filecoin-project/devgrants#1505]
### 1. What is your project, and what problem does it solve? (max 100 words)

Clover is a professional product dedicated to simplifying intra-DAO communications and processes. Say, Google Suites, but for DAOs. Our mission is to provide a complete Workspace suite tailored to the unique needs of DAOs. Our current offering is the Clover Workspace which sports a number of features, including Intra-DAO chats, multiple channels for communication, token-gated NFT authentication, meetings, and collective file storage.

### 2. Project links
  
Link to Github repo: https://github.com/Temiloluwa-ade/clover-warp
Link to demo or website: https://ethglobal.com/showcase/clover-zcfug
License: APACHE2

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

We make use of IPFS, and Filecoin, for complete File storage. 
Files are uploaded on Filecoin via FVM, and pinned on IPFS.
This includes a DAO's collective file storage, and individual sharing of files among members of a DAO. 
We are also building on the Filecoin Virtual Machine, and have deployed on the testnet, while testing and continuous iteration would go on, pending the time we deploy on the mainnet.
We aim to deploy on the mainnet by the end of the FVM mainnet cohort.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |DAO chats   |  Improve the current chat system and the user experience for the Chat system  | Month 1  | 
| 2.     | Voting campaigns  | Implement DAO Voting campaigns, aided by individual DAO tokens. Use Smart contracts on the Filecoin Virtual Machine to facilitate the voting campaigns | Month 1 | 
| 3.     | DAO Meeting Rooms | Build out meeting rooms, integrating relevant service providers, like Huddle, using their SDK. Meeting recordings are then stored on Filecoin, through the virtual machine, and pinned on IPFS. | Month 1 | 
| 4.     | Mainnet Deployment | Deploy our Smart contracts on the FVM Mainnet. | Month 2 | 
| 5.    | User research, and creation of user profiles| Carry out user research meetings, and create ideal user profiles for Clover's target market. | Month 1|
| 6.   |User testing | Initial user test, with select DAOs. Make changes, and reiterate based on feedback received. | Months 1-2 |
| 7.      |Verification of Smart contract | Verify our smart contracts, on the FVM mainnet. | Month 2 |
| 8.     | Integration with Google Calendar | Work on Google Calendar integrations, to enable DAO members set reminders and returning meetings. | Month 3 |
| 9.     | Search Functionality | Integrate a DAO-wide search functionality | Month 3|

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes, we agree to share monthly project updates, and other updates, when needed.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://ethglobal.com/showcase/clover-zcfug

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

  * Temiloluwa Adelowo
  * temiadev@gmail.com
  * https://github.com/Temiloluwa-ade
  * Product designer/Frontend developer

  * Joel George
  * idiaghegeorge9@gmail.com
  * https://github.com/george-hub331
  * Fullstack developer/Blockchain developer

* How did you learn about our microgrant program?
We were advised to apply, by a mentor in the FVM mainnet cohort.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
    * FVM Space Warp Hackathon
  * Please link to your hackathon submission
    * https://ethglobal.com/showcase/clover-zcfug

**Comment by Temiloluwa-ade** [comment]
Sure, we would go over it according to these.

- We'd move step 2 & 3 down the scope.
- Step 4: We use Smart contracts on the Filecoin Virtual Machine to facilitate the voting campaigns, and voting-to-store also uses Filecoin for the storage, based on the results from the vote campaigns.
- Step 5: We are currently integrated with Huddle's SDKs for the meeting rooms. Meeting recordings are then stored on Filecoin, through the virtual machine, and pinned on IPFS.

**Comment by ErinOCon** [comment]
Hi @Temiloluwa-ade, this microgrant has been approved! We will send an email to confirm payment details. In regards to the final report for this project, here are some things we are looking for:
* A fully working user-facing demo with nice UX that anyone case easily use.
* Deployment to FVM mainnet - now that it has officially launched!
* Interesting use of the EVM on Filecoin, especially with respect to what's unique to Filecoin.

**Comment by Temiloluwa-ade** [comment]
Hi @ErinOCon @trruckerfling 
We're done with Month 2 of the grant period and would love to update you on our progress.

We've been able to meet up with the proposed milestones for both months, having done these:
- Redesigned the landing page
- Deployed our smart contract to the FVM
- Verified our smart contract 
- Completed End-to-End encryption of all the chat systems
- Completed basic user research, and have user testing ongoing
- Completed the Meeting room integration (currently undergoing tests)
- Added in the DAO creation feature, making us the first DAO creation app on the FVM
- Worked on the Voting campaigns smart contract, to enable it to work with various DAO contracts
- Began discussions with other DAO creation tools, to make way for seamless integration of both our platforms.

So far, the product is in the alpha stage, at https://useclover.xyz/ for the FVM mainnet, and the testnet version on https://test.useclover.xyz/

Over the next month, we intend to 
- Advance discussions with other DAO tools
- Complete our initial testing phase
- Go public, and announce for beta testers on Twitter
- Begin work on our blog, to enable user sensitization on DAOs and their features.

**Comment by Temiloluwa-ade** [comment]
Hi @
At the end of the 3-month window, we've met our proposed targets and also worked on a few additional things. We have listed our feats over the past 3 months in the table below:

| Number | Deliverable       | Brief outline of the deliverable  | Month completed |
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |Landing page  |  Redesigned the landing page | Month 1  | 
| 2.     | Smart Contract  | Deployed and verified our smart contract on the FVM | Month 1 | 
| 3.    | Encryption | Implemented End-to-End encryption of all the chat systems, using the Diffie Hellman key exchange method for cryptographic encryption | Month 1 |
| 4.   | User research | Completed basic user research, and began initial user testing with a few DAOs | Month 2 |
| 5.   | Meeting rooms | Completed the Meeting room integration, with Huddle01's dRTC as our primary integration | Months 1-2 |
| 6.   | DAO Creation | Implemented the DAO creation feature, making us the first DAO creation app on the FVM | Month 2 |
| 7.   | Voting Campaigns | Worked on the Governance Voting campaigns smart contract, to enable it to work with various DAO contracts | Month 2 |
| 7.   | Voice rooms | Worked on Voice-only calls within DAO Discussion channels, accessible only to members of the specific Discussion channel at a certain time | Month 3 |
| 8.   | Collaboration | Began discussions with other DAO creation tools, to make way for seamless integration of both our platforms. | Months 2 - 3 |
| 9.   | Blog | Began development processes for our blog, and also began curating articles to help the Web3 ecosystem get onboarded to the FVM | Month 3 |
| 10.  | Multi-DAO support | Began working on Multi-DAO support on a single sign-in | from Month 3 |
| 11.   | Notifications | Began working on notifications, to enable users to receive notifications on-chain | from Month 3 |
| 12.  | Gasless transactions | Began working on gasless transactions (an optional feature to be decided by DAO leaders) | from Month 3 |

Currently, the product is still in the alpha stage, at https://useclover.xyz/ for the FVM mainnet, and the testnet version on https://test.useclover.xyz/

Going forward, we intend to do these, in addition to the development and continuous testing of the platform: 
- Advance discussions with other DAO tools
- Complete our initial testing phase
- Go public, and announce for beta testers on Twitter

Temi.

**Comment by Temiloluwa-ade** [comment]
Hi @ErinOCon @trruckerfling 
At the end of the 3-month window, we've met our proposed targets and also worked on a few additional things. We have listed our feats over the past 3 months in the table below:

| Number | Deliverable       | Brief outline of the deliverable  | Month completed |
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |Landing page  |  Redesigned the landing page | Month 1  | 
| 2.     | Smart Contract  | Deployed and verified our smart contract on the FVM | Month 1 | 
| 3.    | Encryption | Implemented End-to-End encryption of all the chat systems, using the Diffie Hellman key exchange method for cryptographic encryption | Month 1 |
| 4.   | User research | Completed basic user research, and began initial user testing with a few DAOs | Month 2 |
| 5.   | Meeting rooms | Completed the Meeting room integration, with Huddle01's dRTC as our primary integration | Months 1-2 |
| 6.   | DAO Creation | Implemented the DAO creation feature, making us the first DAO creation app on the FVM | Month 2 |
| 7.   | Voting Campaigns | Worked on the Governance Voting campaigns smart contract, to enable it to work with various DAO contracts | Month 2 |
| 7.   | Voice rooms | Worked on Voice-only calls within DAO Discussion channels, accessible only to members of the specific Discussion channel at a certain time | Month 3 |
| 8.   | Collaboration | Began discussions with other DAO creation tools, to make way for seamless integration of both our platforms. | Months 2 - 3 |
| 9.   | Blog | Began development processes for our blog, and also began curating articles to help the Web3 ecosystem get onboarded to the FVM | Month 3 |
| 10.  | Multi-DAO support | Began working on Multi-DAO support on a single sign-in | from Month 3 |
| 11.   | Notifications | Began working on notifications, to enable users to receive notifications on-chain | from Month 3 |
| 12.  | Gasless transactions | Began working on gasless transactions (an optional feature to be decided by DAO leaders) | from Month 3 |

Currently, the product is still in the alpha stage, at https://useclover.xyz/ for the FVM mainnet, and the testnet version on https://test.useclover.xyz/

Going forward, we intend to do these, in addition to the development and continuous testing of the platform: 
- Advance discussions with other DAO tools
- Complete our initial testing phase
- Go public, and announce for beta testers on Twitter

Temi.

**Comment by eshon** [comment]
Hi @Temiloluwa-ade - Can you please create a demo video demonstrating what features have been implemented for this microgrant?

**Comment by Temiloluwa-ade** [comment]
Alright @eshon 
I'd link it as a reply to this issue, once I'm done with it

**Comment by Temiloluwa-ade** [comment]
Hey @eshon 
Here's a link to the demo: https://youtu.be/bEocnupxdzk

**Comment by Temiloluwa-ade** [comment]
Hey @eshon 

We've fixed that up, and added the demo video in.
