### ISSUE TITLE
Next Step Microgrant: IPFS-Backup

### ISSUE THREAD

**Issue by ottpeter** [filecoin-project/devgrants#1506]
### 1. What is your project, and what problem does it solve? (max 100 words)
IPFS-Backup - Backup pinned items from an IPFS node to Filecoin 

### 2. Project links
  
Link to Github repo: https://github.com/ottpeter/IPFS-Backup
License: [MIT](https://github.com/ottpeter/IPFS-Backup/blob/master/LICENSE)
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
This is intended for entities that are operating a server which runs an IPFS node, the application is running on that node, and periodically backups the repository to Filecoin.
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| 1.     | Keep redundancy  | Smart contract keeps target redundancy (renews deals) (only API)                                 | ~ 1 month            | 
| 2.     | Simple UI              |  A simple web UI for the application, where the user can set target redundancy               | ~ 2 month           | 
| 3.     | Map                       | A map which is showing the StorageProviders that are storing the data                           | ~ 2  month          | 
| 4.     | Access control      |  Decentralize the access control, so no single entity can set target redundancy to 1        | ~ 3 month           | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

  
### Additional questions:

__Team__:
Peter Ott
ottpeter [at] tuta [dot] io
https://github.com/ottpeter
Project Owner / Developer

* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program? Discordian told me about it.

**Comment by ottpeter** [comment]
We have a live demo now that works for the most part: http://5.180.183.88/#/dashboard
And we have a website that explains the basic idea: https://ipfs-backup.com/

**Comment by eshon** [comment]
@ottpeter - Sorry for the delayed response! Your project wasn't labeled correctly in our system. 

This project is great and we are interested in funding it with a microgrant but are wondering if you'd be willing to update it with some new FVM-related tools for managing smaller amounts of data.

However it'd understandable if it's been too long and you've decided to move on. Let us know.

**Comment by ottpeter** [comment]
Hi Eva,
Probably I would be interested in continuing this project.
However, I don't understand what you mean, what do you mean by "some new FVM-related tools for managing smaller amounts of data"? You mean specific tools to be able to handle small data as well? Or you think that this project is not FVM related?
Waiting for your reply!
Regards,
Peter

**Comment by eshon** [comment]
@ottpeter - Almost all SPs in Filecoin do not want to accept small deals from clients, the overhead of managing that isn't usually worth the cost. Plus the default minimum sector size in Filecoin is 32 GiB. SPs prefer large data clients, ideally even beyond a single sector.

A few teams are working on centralized and decentralized storage deal aggregators that bundle smaller deals into larger ones as an intermediate layer that uses FVM for small deal management and payment. There is also a new way to prove that a small piece is included in a larger deal called Proof of Data Segment Inclusion ([beta Lighthouse Docs example](https://docs.lighthouse.storage/lighthouse-1/filecoin-virtual-machine/podsi)). 

More of this tooling will be coming online and presented during the [Open Data Hack](https://www.encode.club/open-data-hack) starting at the end of August.

So the ask would be to try to incorporate IPFS-Backup with these aggregator tools. And if they're not supporting backing up pinned items from IPFS yet, what would it take for them to support it? What would need to be modified? This project could be a great way to explore this and provide a useful demand for this from the community.

Anyways, that's a suggestion for how this could move forward as a microgrant in a way that would make it a really useful and practical backup tool in the future that can have legs.

I think the only other concern was that your website is not currently live and we want to fund projects and demos that have longevity, even as just demos.

**Comment by ottpeter** [comment]
Thanks the info,

Yes, I would be interested in experimenting with these tools, I care about the IPFS/Filecoin ecosystem so I find these deal aggregators interesting.

Last time the website worked with Hyperspace testnet, I would need some time to redeploy it to new testnet.
On mainnet, the conditions are slightly different, because providers will not auto-accept deals with 0 FIL/epoch, so I would need to implement mechanism that is setting the price, but if this gets funded I will start working on that.

**Comment by eshon** [comment]
Yeah Hyperspace was deprecated at the end of May and Calibration testnet is the primary testnet.

On Calibration, there is 1 SP auto-accepting deals (deals at https://github.com/benjaminh83/fmv-calib-deal-miners although I just asked him to fix the name of his repo from fmv to fvm). Definitely different from what's on mainnet.

There will be more workshops and camera-ready docs for all this at the [ODH hackathon](https://www.encode.club/open-data-hack) at the end of the month, so might be better to wait til then to start.

In the meantime, I'll recommend that this project is a good candidate for a microgrant and we can get that processed.

**Comment by ErinOCon** [comment]
Hello @ottpeter, I hope you are doing well! Do you have an update regarding project progress at this time?

**Comment by ottpeter** [comment]
Hello @ErinOCon 
Currently I have to focus on my day job a lot. After that will be resolved, hopefully i will have time working on this.
Sorry for the delay!

**Comment by ErinOCon** [comment]
Hi @ottpeter, it's good to hear from you! Do you have an anticipated end date for the project?

**Comment by ottpeter** [comment]
Hi @ErinOCon,
I started working at Solar Punk and there are _non-compete obligations_ in the contract, in regard of decentralized storage technologies, so unfortunately i won't be able to work on IPFS-Backup this time.
Sorry about this situation!
