### ISSUE TITLE
Next Step Microgrant: Radio-vaults streaming Service Prototype

### ISSUE THREAD

**Issue by yourmercury** [filecoin-project/devgrants#1507]
### 1. What is your project, and what problem does it solve? (max 100 words)
Radio Vaults is a Technology that would be used for uploading NFT assets and deploying NFT contracts, especially Music NFT Assets to IPFS. The perk of using this app is that you can permission (whitelisting access to assets) and track access to these assets and also count streams from NFT Marketplaces and wallets using the metadata. With the Meta-verse in view, music NFTs will be here too and so we are presenting a way to secure musicians assets from plagiarism (stripping metadata to make other NFT contracts) and serve as a decentralized streaming platform.

### 2. Project links
  
Link to Github repo: https://github.com/yourmercury/Radio-vault-next.git
Link to demo or website: https://radio-vault.vercel.app
License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
With the FVM live on mainnet, we would be revamping our plans of creating a streaming service on Binance to creating on Filecoin. A particular small problem we had going with the former was that there would be a web2 layer which basically reduces the decentralization to an extent. Now with the power of smart contract on filecoin itself we can recreate our backend and host 'trustlessly' on a filecoin and automatically have a complete decentralized system. A big thanks to your team for solving an underrated web problem. This achievement has really brought a whole lot of implementation possibilities for my team and for sure several other teams in the Web3 space.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
YES
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
Firstly, A huge thank you for the last funding. The grant really took us through concurrent research and development to the point that we are in.
The Next step we are in is building the Prototype Streaming service. We need the funding to take us through the period when we would be designing the User Interface and Building the frontend and concurrently add the Music NFT deployment feature to the Application
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---:       | :---                           |     :----                                                                                    |  :---:
|1 | Prototype UI and UX design and Smart contracts for Streaming Platform. | Emmanuel will be designing the streaming service and DAO interface using the laid down features decided upon by the team. I would be concurrently planning and developing the needed Prototype smart contracts while The UI is being designed by Emmanuel so as not to leave any feature undesigned on the UI. | 2 months |
|2 | Prototype Frontend development. | Osarodion would be Tasked with developing the Frontend of the application off the UI UX design. | 1 month |

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: https://devpost.com/software/radio-vaults
  
### Additional questions:
Polycarp Momoh, [momohpolycarp@gmail.com](mailto:momohpolycarp@gmail.com), https://github.com/yourmercury, Lead Developer
Osarodion Osayande, [josiahosarodion@gmail.com](mailto:josiahosarodion@gmail.com), https://github.com/sahrodion, frontend developer
Emmanuel Okotete, [okotetedv@gmail.com](mailto:okotetedv@gmail.com), UI UX designer

* How did you learn about our microgrant program? 
* Ans: A friend of mine saw what we were building and told me about the grant opportunity

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Ans: Chainlink Fall Hackathon
  

  * Please link to your hackathon submission
  * Ans: https://devpost.com/software/radio-vaults

**Comment by eshon** [comment]
Hi @yourmercury, thanks for your FVM microgrant submission!

While your project could be an nice demo on any EVM, we don't see anything Filecoin-specific in your current prototype or roadmap.

Here are some general things we’d like to see in FVM Microgrant projects:

- A fully working user-facing demo with nice UX that anyone can easily use.
- Is deployed to a Filecoin testnet, so that we can see all the functionality working on a testnet, and will be deployed to Filecoin mainnet in a production-ready state on project completion.
- Interesting use of Filecoin’s EVM, especially with respect to what’s unique to Filecoin (for example, via exploration of the [Filecoin Solidity API](https://docs.filecoin.io/developers/smart-contracts/hardhat/), [FVM use cases](https://docs.filecoin.io/smart-contracts/fundamentals/the-filecoin-virtual-machine/), or [Bacalhau x FVM](https://github.com/bacalhau-project/lilypad), etc.)

**Comment by yourmercury** [comment]
Thanks for the feedback @eshon  . The project started before the FVM and was originally designed for Binance and the stacks blockchain but with the FVM mainnet launch, we have decided to solely use filecoin from store to contract. note that the state of the current prototype was funded by the dev grants. 

please view this https://drive.google.com/file/d/1DleP0f2RUS6GWMtWzro6Kg9Dd2RYppq3/view?usp=share_link

**Comment by eshon** [comment]
Thanks @yourmercury it's a nice demo! 

But for this round of FVM microgrants, we're looking for use cases that explore what's unique to Filecoin compared to other EVMs. That is specifically more about exploring smart contracts that can leverage the [Filecoin Solidity API](https://docs.filecoin.io/developers/smart-contracts/hardhat/), [FVM use cases](https://docs.filecoin.io/smart-contracts/fundamentals/the-filecoin-virtual-machine/), or [Bacalhau x FVM](https://github.com/bacalhau-project/lilypad).

**Comment by eshon** [comment]
We currently don't offer microgrants for IPFS-only projects @yourmercury unfortunately. There are thousands and thousands of projects that use IPFS organically without a microgrant.
