### ISSUE TITLE
BCDEx Network: Support FIL and LN BTC atomic swap on FEVM

### ISSUE THREAD

**Issue by devbcdex** [filecoin-project/devgrants#1510]
### 1. What is your project, and what problem does it solve? (max 100 words)

We noticed that FEVM is live, which is great information. Our project BCDEx can realize the exchange of assets between BTC of Lightning Network and any EVM compatible chain. In other words, we can exchange FIL and BTC directly, just on the main network. Completely decentralized and non-custodial approach.

### 2. Project links
  
Link to Github repo: https://github.com/bcdexnet
Link to demo or website: https://dev.bcdex.net
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

Mainly relying on the Solidity smart contract supported by FEVM, we need to use the smart contract to lock FIL and calculate the password, so as to complete the atomic exchange of BTC and FIL.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
  YES

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |   1000 USD     |  Deployment contract and corresponding tests   |       1 Month      | 
| 2.     |  4000 USD     | to upgrade the website function and support FIL exchange |         1 Month       | 
| 3.     |                         |                                                            |                            | 
| 4.     |                         |                                                            |                            | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes, I would do that.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

Not yet, but plans to attend. 

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Bluza dev@bcdex.net Full Stack Developer

* How did you learn about our microgrant program?

News and Google

* If your project was created as part of an event or hackathon:

Not yet

**Comment by ErinOCon** [comment]
Hi @devbcdex, thank you for your proposal and for your your patience with our review. Unfortunately, we will not be proceeding with a grant. 

Wishing you the best with your future work in the ecosystem!
