### ISSUE TITLE
Next Step Microgrant: SFILDao

### ISSUE THREAD

**Issue by wendao1919** [filecoin-project/devgrants#1513]
### 1. What is your project, and what problem does it solve? (max 100 words)
Calculate power autonomous platform, mint   tokens for pledging mining, pledging loans, token transactions, and also storing tokens to obtain interest.This also includes blockchain notarization and multi signature vault wallet referendum

### 2. Project links
  
Link to Github repo: https://github.com/wendao1919/fildao.git
Link to demo or website:  http://ast.w3dao.finance/fil/index.html#/
License:

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
It is an extension based on FIL calculate  power(FCP)
FCP has created a broader Filecoin hashrate marketwhich enables free and efficient circulation of thecompliant money worldwide. Every FCP is pegged to0.01T Filecoin full hashrate. Once you hold Token in yourwallet, you can get free FIL each day.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
YES
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |    Obtaining 1000+ users                     |  Obtaining 1000+ users                                                          |                            | 
| 2.     |   100T Filecoin full hashrate per  month                      |   100T Filecoin full hashrate per  month                                                         |                            | 
| 3.     |                         |                                                            |                            | 
| 4.     |                         |                                                            |                            | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
YES
  
### 6. Does your proposal comply with our Community Code of Conduct?
YES

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project. 
* maxwell  hashcow60@gmail.com wendao1919  manager
* sand     fuyu315@gmail.com  fuyu315         developer
* fish fish12345679123@163.com  fish12345679 developer
* jason 597081195@qq.com  jason  developer
* How did you learn about our microgrant program?  
* bilibili,twitter
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by wendao1919** [comment]
hope add our project

**Comment by wendao1919** [comment]
filDao

**Comment by ErinOCon** [comment]
Hi @wendao1919, thank you for your proposal and for your patience with our review. Unfortunately, we will not be proceeding with a grant at this time. 

Thank you again for your interest in our grants program.
