### ISSUE TITLE
Open Grant Proposal: Metch dApp

### ISSUE THREAD

**Issue by franc0rk** [filecoin-project/devgrants#1517]
# Open Grant Proposal: `Metch dApp`

**Project Name: Metch**

**Proposal Category:** `Applications`

**Individual or Entity Name:** Individual

**Proposer:** `franc0rk`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

Metch is a dApp for connecting hackers and form teams to start building new web3 ideas not only in events such as hackathons but also anytime they want to build something. It works with a matching system similar to one from a dating app but for forming groups/teams. Also, users would be able to see information about upcoming hacking events so that they can participate on them and these events will be posted and validated by the Metch community DAO. Besides, it recognizes users with a reputation system called Proof of Hacking(POH) which allows hackers to find experienced people for their teams.

The main functionality is, hackers post ideas they want to work on or look for ideas already published by other hackers, if a user likes an idea and the idea creator likes their profile it would be a match and they would be in a group chat to start discussing about how to build the idea. It works the other way around as well if an idea creator likes a user profile and the user likes the idea, they will be part of the same team. Idea creators could match as many members they want for their team and they will be in the same group chat. Also hackers could be part of different teams.

## Impact 

The main idea is to have a tool where hackers can connect with others rather than use tools such as Discord or Telegram where could lose track of our team easily on these ones among many messages.

This also keeps the web3 hacker community active so that they could be building new ideas on different events and meeting new people that they could learn from and gain more experience.

- What pain points does this project seek to address? Difficulty for finding teams on other chat tools.

- What are the benefits to getting this right? What are the risks of not getting this right? Grow the builders community would be faster since it would be easier to make teams. Otherwise we would have the current limitations using the stated tools.

- What impact will this project have in a specific vertical, market, or ecosystem? What does success look like? I could say how success looks like with an example. Imagine someone is new to web3 or is participating in a hackathon, they ask where could I find a team. The answer would be "you can search on Metch".

## Outcomes

- Main deliverable would be a dApp with a responsive web design with the following features: profile and idea creation (using Lens Protocol and storing data on IPFS), matching system, chat, reputation system and calendar.
- Landing page for attracting users to use the dApp.
- Metch Avatar NFT Collection for the DAO community.

In order to measure the success we will be working on 2 week sprints completing a goal of story points(TBD) estimated based on Fibonacci scale.

## Adoption, Reach, and Growth Strategies

The target audience is the web3 hackers community which is increasing everyday. To onboard new users we pretend Metch to be the hackathons official tool that they use when participating in this kind of events and need to look for a team.

## Development Roadmap

**Milestone 1. Landing Page and dApp Design:**
Functionality: We plan to start making attractive UI wireframes for our landing page and dApp based on the [previous MVP](https://ethglobal.com/showcase/metch-amr83).
Roles: UI/UX Designer would be in charge of the wireframes while I will be developing the landing page as a Frontend Developer.
Funding: The funding required is $5k to cover design and development hours.
Time: This will take a month starting from May 1 to May 31.

**Milestone 2. MVP Development:**
Functionality: The MVP would have the main features stated (profiles and ideas CRUD, matching system, chat, reputation system, and calendar with the new design and adding unit and e2e testing to ensure small quantity of bugs.
Roles: Frontend Developer (I) will be working on this development.
Funding: The funding required is $5k to cover development hours.
Time: This will take two months starting from June 1 to July 31.

**Milestone 3. dApp Beta Testing:**
Functionality: Once dApp development is almost finished, in order to test it with real data we will be looking for actual events and people who want to be part of the Metch community to test on a staging environment.
Roles: Frontend Developer (I) will be in charge of finishing the development.
Funding: The funding required is $5k to cover development hours.
Time: This will take one month starting from August 1 to August 31.

**Milestone 3. dApp Launch:**
Functionality: After beta testing feedback development will be finished and dApp ready for production will be launched.
Roles: Frontend Developer (I) will be in charge of finishing the development and deploy.
Funding: The funding required is $5k to cover deployment costs such as storage, web hosting and smart contract deployments.
Time: This will take two months starting from September 1 to October 31.

## Total Budget Requested

| Milestone # | Description | Deliverables | Completion Date | Funding |
| ------------| ------------ | ------------- | ---------------- | ------- |
| 1 |  Landing Page and dApp Design | Wireframes and Website  | May 31 | $5k |
| 2 | MVP Development |  The MVP with its new design | July 31 | $5k
| 3 | dApp Beta Testing |  The dApp with main features to be tested for small groups or small event | August 31 | $5k
| 4 | dApp Launch | dApp deployment on production | October 31 | $5k

## Maintenance and Upgrade Plans

- We plan to release new features on demand according to users experience and feedback as well as fixing bugs they report as soon as possible.
- Upgrading the services used for storage will be done on demand as well.

# Team

## Team Members

Franco De Leon (Frontend Developer)
*Looking for a UI/UX Designer

## Team Member LinkedIn Profiles

[Franco De Leon](https://www.linkedin.com/in/franc0rk/)

## Team Website

https://francork.netlify.app/resume

## Relevant Experience

Franco De Leon: Frontend Developer with +7 yoe working on web projects also as a Fullstack Developer, currently exploring blockchain and web3 technologies participating and building in different hackathons.

## Team code repositories

https://github.com/franc0rk/metch-ethglobal-scale-eth

# Additional Information
How did you learn about the Open Grants Program? Friend
Email: francodeleon97@hotmail.com
I have an MVP built during Scaling Ethereum 2023 Hackathon by EthGlobal
Demo: https://ethglobal.com/showcase/metch-amr83
Link: https://metchdapp.netlify.app/

**Comment by ErinOCon** [comment]
Hi @franc0rk, thank you for your proposal. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!
