### ISSUE TITLE
DataEx - Decentralised Data Exchange

### ISSUE THREAD

**Issue by Abhay-2811** [filecoin-project/devgrants#1518]
1. Problem : 

The global data marketplace market has been growing rapidly, and its market size was valued at USD 968 million in 2022. Moreover, it is expected to expand at a CAGR of 25.0% from 2023 to 2030, which presents a significant opportunity for innovative solutions to address the centralization problem that currently dominates the market.

Data-Ex is one such solution that can revolutionize the data marketplace industry. By leveraging FVM-based technology, it enables any user to monetize any kind of data, breaking down the barriers to entry that often hinder smaller players from participating in the market. This technology empowers individuals and businesses to control their data and use it to generate revenue, which is a critical step toward democratizing the industry.

Given the potential of Data-Ex to disrupt the data marketplace industry, we believe that it would be a strong candidate for a grant application. Its innovative technology and focus on decentralization align with the objectives of many grant programs, making it a compelling option for funding support.

----------------------------------------------------------------------------------------------------------------------------------

2. Project links :
  
Link to Github repo: https://github.com/Abhay-2811/Data_Ex
Link to demo or website: https://data-ex-0.vercel.app/
License: MIT

----------------------------------------------------------------------------------------------------------------------------------

3.

a) How is IPFS, Filecoin, or related technology used in this project?

- FVM: FVM is the major tool that wraps up our entire project as it was needed for data storage/deals and data retrieval back from miners. 

b) Is this project building with the current microgrants focus area (FVM)? 

- Yes

----------------------------------------------------------------------------------------------------------------------------------

4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |  Enabling Data DAO feature   |  Current feature includes only a singular buyer and seller, so creating Data DAO to facilitate institutional buyers is our top priority.                                                    |  within  2 months  | 
| 2.     | Adding features to secure buyers and sellers from fake data scams      |  This will be implemented through seller staking tokens higher than the sell value, so in case of possible scams by the seller, this stake would be adjusted with the buyer and additional penalty and ban would be implemented.       |   within 3 months                   | 
| 3.     |   Improving frontend                   | Hiring someone to improve the frontend of the website to make it more aesthetic and dynamically optimized.                                                   |          within 1 month                  | 

----------------------------------------------------------------------------------------------------------------------------------

5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

- Yes

----------------------------------------------------------------------------------------------------------------------------------

6. Does your proposal comply with our Community Code of Conduct?

- Yes

----------------------------------------------------------------------------------------------------------------------------------

7. Links and submissions: 

- Winners of Scaling Ethereum | FVM Track: Best Programmable Storage Market

Link of submission: https://ethglobal.com/showcase/data-ex-x43o6

----------------------------------------------------------------------------------------------------------------------------------
  
Additional questions:

Team Members : 

-  Abhay Upadhyay, abhay_upadhyay@icloud.com, https://github.com/Abhay-2811, Full stack blockchain developer
-  Aditya Chaplot, aditya311001rj@gmail.com, https://github.com/adielliot37, Smart Contract and backend developer

How did you learn about our microgrant program? : 

After the submission of our project on Scaling Ethereum, we enjoyed working with FVM and were interested to work further on DataEX with a vision to deploy it on mainnet someday.

If your project was created as part of an event or hackathon:
 
Yes, our project was created during the Scaling Ethereum hackathon.
Link: https://ethglobal.com/showcase/data-ex-x43o6

----------------------------------------------------------------------------------------------------------------------------------

**Comment by eshon** [comment]
Hi @Abhay-2811, Congratulations on winning an FVM prize at the Scaling Ethereum hackathon!

To be considered for a $5k FVM microgrant, can your team please provide a more detaie technical roadmap?

- What specific Data DAO features/workflows do you plan to implement?
- What anti-data scam features do you plan to implement?
- Do you have a content management plan to onboard users and seed your platform with quality data for sale?

Note that we hope to see great mainnet-ready demos delivered for an FVM microgrant. This generally should include:

- A fully working user-facing demo with nice UX that anyone can easily use.
- A dapp deployed to a Filecoin testnet, so that we can see all the functionality working on a testnet, and will be deployed to Filecoin mainnet in a production-ready state on project completion.
- Interesting use of Filecoin’s EVM, especially with respect to what’s unique to Filecoin (for example, via exploration of the [Filecoin Solidity API](https://docs.filecoin.io/developers/smart-contracts/hardhat/), [FVM use cases](https://docs.filecoin.io/smart-contracts/fundamentals/the-filecoin-virtual-machine/), or [Bacalhau x FVM](https://github.com/bacalhau-project/lilypad), etc.)

**Comment by Abhay-2811** [comment]
@eshon thanks for the reply. I understand that I should've been more descriptive about the project's future roadmap, and I apologize for that.
 
 Detailed roadmap as requested:

-  Data DAO features:  I'll take an example to explain this further, let's say a research company needs data about people's workout habits, in this case, the flow would be:
    -  admin creates a DAO where they can choose DAO's capacity like 5k participants and rewards. 
    - After this Admin chooses the format of data input and frequency of the input. 
    -  Later participants of DAO would be notified every day for as long as dao exists to input data using the frontend as 
        chosen by DAO admin, failure to do so would result in a penalty i.e. reward reduction.
    - The uploaded data would get stored on FVM and at the end of the duration of DAO, the rewards would be distributed 
       according to contributions made.
 
- Anti-data Scam feature: In the case of solo data sellers, the sellers would be requested to stake a small amount of money before listing data for sale, while sale a escrow like feature would be installed where in case of any discrepancy the buyer would be given back money, data would be unlisted and stake amount would be taken as a penalty.

- As a permissionless system managing content won't be ideal. To seed our platform we will be reaching out to institutional research firms and list their DAOs.

**Comment by Abhay-2811** [comment]
@eshon  Any updates on this?

**Comment by adielliot37** [comment]
@eshon ?

**Comment by eshon** [comment]
Hi @Abhay-2811 and @adielliot37 - We are impressed with your team's work but want to support a dapp project that has a high likelihood of becoming a long-lasting and useful dapp demo on FEVM.

If you're participating in any subsequent [Filecoin hackathons](https://hackathons.filecoin.io) like ODH with updated FEVM storage workflows then please do apply for an FVM Microgrant again in the future with a new project and we'll keep a lookout for it.
