### ISSUE TITLE
CREATIVE'S DAO PROPOSAL

### ISSUE THREAD

**Issue by lyndananu** [filecoin-project/devgrants#1519]
### 1. What is your project, and what problem does it solve? (max 100 words)

The project is the establishment of a NFT creatives DAO for African creatives in Art, music and fashion. The NFT creatives DAO aims to provide a platform for African creatives to showcase their work on the block chain, and enable buyers to purchase unique pieces of creatives as NFTs. This proposal outlines the goals of the project, the activities that will be undertaken to achieve these goals, the expected outcomes, and the budget required to complete the project.
 

We plan to use filecoin virtual machine to create an NFT creatives DAO platform. This platform will also serve as a marketplace for creatives to monetize on their content ranging from music, videos, images etc. We will also have a creatives data DAO that will be used to help preserve large data sets of artifacts, antique collections and bulk designs from creatives and several archeological companies.

### 2. Project links

 https://green-base-4541.on.fleek.co/

  
Link to Github repo:

Link to demo or website:  https://green-base-4541.on.fleek.co/

License:

MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

We plan to use filecoin virtual machine to create an NFT creatives DAO platform. This platform will also serve as a marketplace for creatives to monetize on their content ranging from music, videos, images etc. We will also have a creatives data DAO that will be used to help preserve large data sets of artifacts, antique collections and bulk designs from creatives and several archeological companies.

Front-end built using ReactJS and web3.js.
Includes a custom-built smart contract for NFT ownership verification and transfer on the Filecoin network.
Collectors can browse and search for NFTs on the platform, and purchase them using cryptocurrency.
Implements authentication and authorization using a third-party provider such as Auth0.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)

YES
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 

| 1.     | Establishing the NFT creatives DAO:|   This will involve setting up the DAO structure, developing a smart contract, and recruiting members for the DAO. | 3 weeks  | 

| 2.     |  Developing the platform:|   The platform will be developed on top of Filecoin virtual machine. This platform will be used by creatives to store NFT collections, and we p-lan to integrate with AI to create custom digital collectibles based on the Art uploaded by the artists to be used in metaverse projects.|    4 weeks     | 

| 3.     | Creating a community:| The project will create a community of buyers and sellers of NFT creatives items, with a focus on supporting African creatives. The community will be established through social media and marketing efforts, and will include outreach to creative influencers and media outlet | 3weeks  | 

| 4.     |Providing training and support:| | The project will provide training and support to African creatives in creating NFTs of their creative designs. This will involve workshops, mentorship, and access to resources such as design software and block chain tools. |  4 weeks | 
|5.     | Marketing and outreach:| The project will undertake marketing and outreach efforts to increase the visibility of African creatives on the global market. This will involve creating content for social media, outreach to media outlets, and participating in creative events and exhibitions.|  6 weeks |
        	                                                          
	
### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

YES

  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Allan mang’eni
 Role: technical lead
 GitHub: [github.com/allanmangeni](http://github.com/allanmangeni)
 LinkedIn: [linkedin.com/in/allanmangeni](http://linkedin.com/in/allanmangeni)
 
Lynda Nanu
Role: Project Manager
GitHub:[ https://github.com/lyndananu](https://github.com/lyndananu)

* How did you learn about our microgrant program?

Friend

* If your project was created as part of an event or hackathon:

N/A

  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)

N/A
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
HI @lyndananu, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant for this project. 

Thank you again for your interest in our program.

**Comment by lyndananu** [comment]
Thank you for letting me know.


Regards.

Lynda
