### ISSUE TITLE
Open Grant Proposal: magipop DAO

### ISSUE THREAD

**Issue by Kincc-9999** [filecoin-project/devgrants#1520]
# Open Grant Proposal: `magipop DAO`

**Name of Project: magipop DAO*

**Proposal Category: community** 

**Proposer:** `RocRace`

**(Optional) Technical Sponsor:** `wjy@bitrisevc.com`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT or APACHE2 licenses?:** "Nope"

# Project Description
magipop is a DAO-driven creators funfair, for co-creating IP through Tokenomics mechanisms. 

With the potential to disrupt the trillion-dollar IP market, magipop fosters efficiency, diversity, and trust in the creative process by harnessing the power of Web 3.0, DAO, and tokenomics. The magippop's first successful IP, a sci-fi novel co-created by 100 people, became a bestseller and earned an income of $200,000 in NFT Launch within three days.

This is a new way of organizing creators and creativity:

- This is a structure that everyone can co-create. Efficiency & Diversity in co-creation.
- Through the DAO mechanism and Tokenomics, creators can better build trust with and have open and transparent Incentives
- Far efficient way of going to market, a new structure for consumers and creators to take share together

## Value
value:
	magipop aims to forge creations directly from the community, disrupting the traditional process of creating IPs and bringing Filecoin to the hands of content creator.
	by leveraging the power of Web 3.0, DAO, and tokenomics to foster a decentralized, collaborative, and efficient environment for the co-creation of IPs. magipop enables creators and fans to work together seamlessly, ensuring a fair distribution of rewards and accelerated growth. creators and consumers can break away from traditional IP creation processes and forge IPs directly from the community.
Challenges:
	Quality and trust: magipop must establish a strong reputation for quality content to attract top creators and consumers. Ensuring that co-created IPs maintain high standards while fostering a trustworthy environment for collaboration will be essential.
	adoption: As a DAO built on blockchain and tokenomics, magipop needs to bridge the gap between traditional creators and the crypto community. Convincing non-crypto creators of the advantages of magipop's decentralized approach might be challenging.
	Scalability: As the creator community grows, magipop must ensure that the tokenomics can handle increased collaboration without compromising user experience, and security.
	Legal and regulatory challenges: As with any project in the crypto space, magipop may face legal and regulatory challenges that could impact its operations or the way it conducts business.

## Deliverables
1. A diverse and engaged community of creators, IPs, and fans collaborating on innovative projects.
2. A DAO mechanism that facilitates seamless co-creation of create using AI and Web 3.0 technology.

## Development Roadmap

**First Six Months**

Milestone: launch the co-creation of Bubble Observers S2, which will involve community co-creation using AI tools and launch the AI-powered DAO infrastructure

- Description: magipop will focus on building and launching a robust DAO platform with integrated AI capabilities to streamline content co-creation. The Bubble Observers Season 2 will demonstrate the potential of the community and help attract new members.
- Software Functionality: A user-friendly DAO platform with AI-powered tools for co-creation, collaboration, and content management.
- Team: 7 people – Project Manager, AI Engineer, Blockchain Developer, UX/UI Designer, Community Manager, Content Strategist, and Marketing Specialist.
- Funding Required: $250,000
- Timeline: Completion by Dec 2023.
- KPI: Expand creator base to 500, DAO members to 30,000, partners to 100, and media followers to 100,000.

**Second Six Months**

Milestone: magipop will launch the community-driven content creation event while enabling spontaneous community-driven content creation based on the tokenomic, test tokenomic system and operate the DAO in the test environment, 

- Description: Magipop will implement a test tokenomic system to ensure fair and transparent incentives for community members. The milestone will also focus on fostering active participation in content creation.
- Software Functionality: Integration of test tokenomic system, smart contract support, and enhanced collaboration features.
- Team: 7 people – Project Manager, AI Engineer, Blockchain Developer, Tokenomics Expert, Community Manager, UX/UI Designer, and Marketing Specialist.
- Funding Required: $350,000
- Timeline: Completion by March 31, 2024.
- KPI: Increase creators to 900, DAO members to 45,000, partners to 220, and media followers to 220,000.

**Third Six Months**

Milestone: organize Creator Festival, officially launch tokenomic system, and develop consumer brand.

- Description: Magipop will transition to the official token system and organize the Creator Festival to promote the community, attract creators, and inspire users. Developing a consumer brand will also help establish a playbook for future collaborations.
- Software Functionality: Full tokenomic system, event management features, and e-commerce integration for branded products.
- Team: 8 people – Project Manager, AI Engineer, Blockchain Developer, Tokenomics Expert, Community Manager, Content Strategist, UX/UI Designer, Marketing Specialist
- Funding Required: $400,000
- Timeline: Completion by September 30, 2024.
- KPI: Grow creators to 1,400, DAO members to 70,000, partners to 300, and media followers to 300,000.

**Fourth to Sixth Months**

Milestone: During the Fourth period, magipop will gamify and produce films based on native IPs, further expanding its reach in the creator economy.

- Description: Magipop will expand its scope by gamifying native IPs and producing films, further increasing the platform's appeal and reach. The community will play a crucial role in shaping these endeavors.
- Software Functionality: Game development and filmmaking tools, licensing management, and additional collaboration features.
- Team: 10 people – Project Manager, AI Engineer, Blockchain Developer, Tokenomics Expert, Game Developer, Film Producer Content Strategist, UX/UI Designer, Community Manager, Marketing Specialist
- Funding Required: $600,000
- Timeline: Completion by March 31, 2025.
- KPI:  Expand creator base to 4,000, DAO members to 200,000, partners to 1,000, and media followers to 1,000,000.

## Total Budget Requested
The total requested budget across all milestones is $1,600,000.

Budget Breakdown:

Personnel: $900,000
Salaries for project managers, developers, designers, marketing specialists, content strategists, and other team members.

Marketing and Community Building: $300,000
Advertising, public relations, social media campaigns, and community events like the Creator Festival.

Software Development and Tools: $250,000
Licensing fees for software, development tools, and AI technologies, as well as costs associated with platform maintenance and upgrades.

IP Development and Licensing: $100,000
Expenses related to the creation of new IPs, including game development and film production, as well as IP licensing costs.

Administrative and Overhead Costs: $50,000
Office space, utilities, equipment, and other general administrative expenses.

## Maintenance and Upgrade Plans

magipop's team will continuously research and develop new features and functionalities to keep magipop at the forefront of the creator economy. We will explore cutting-edge technologies in AI, blockchain, and content creation to deliver innovative tools that empower creators and facilitate community engagement.

# Team

## Team Members and Profiles

Race li
---
Hurun U30 Winner, Founder of 1million+ download social app, invited to Apple WWDC 2018, Apple WWDC Scholarship winner, e**lectronic musician**
email: callmerace@hotmail.com
phone: +86 133 6239 8785
Linkedin URL [https://www.linkedin.com/mwlite/in/race-li-841591111](https://www.linkedin.com/mwlite/in/race-li-841591111)

Annie
---
Freshman at UC Berkeley CS major, started cryptocurrency research in high school, NCWIT Award Winner, Canada National Book Award Winner, connected with several North American NFT and creator communities
email: annie.v.karen@gmail.com
phone: +1(217)8983115
Linkedin URL [http://linkedin.com/in/tianyu-annie-huang](http://linkedin.com/in/tianyu-annie-huang)

Setsukousa
---
senior Web3 researcher, research published in Chaos, Solitons & Fractals, cryptocurrency investors, master in financial physics at ZJU, metaverse consultant at a fine arts institute
Email: ma767759110@gmail.com
Phone: +86 15158508151
Linkedin URL [https://www.linkedin.com/in/kousa-setsu-55764a216/](https://www.linkedin.com/in/kousa-setsu-55764a216/)

Sloan GW
---
senior Web3 researcher, early cryptocurrency investor, and expert in building distributed systems of autonomy, trust, and collaboration
Email kincc9999@gmail.com
Phone: +86 159 0961 9928

Elekine
---
Expert in creator economy, published article with 100k+ views, operated 1 million+ creators,10 million+ DAU Content App, former Alibaba responsible for creator live streaming e-commerce with an annual $3 billion+ GMV
Brand advertisement
Email [elekine007@gmail.com](elekine007@gmail.com)
Phone: +86 185 1920 7437
Linkedin URL  [https://www.linkedin.com/in/serein-ai/](https://www.linkedin.com/in/serein-ai/)

Bl1nk^
---
Co-founder and CTO of a music technology company, the app recommended by Apple Today home page, Apple WWDC18 scholarship winner, Apple official certified Swift developer
Email ck.king.cyk@gmail.com
Linkedin URL [https://www.linkedin.com/in/yukai-chen-8a9821166/](https://www.linkedin.com/in/yukai-chen-8a9821166/) 

Tz
---
Graduated from the University of Edinburgh artificial intelligence major, more than ten years of experience in Internet, artificial intelligence / human-computer interaction design experts, senior science fiction writer, founder of popular Clubhouse science fantasy community

## Team Website

https://magipop.xyz/

## Relevant Experience

When Race wanted to write a book about the metaverse, he reached out to Setsu and Sloan, and they decided to bring together a group of like-minded individuals to collaborate on the book. As more and more creators came together to contribute to the project, we saw this as a DAO-like model. With our experience and collaborative approach to creation, we aim to promote our creative model to the community with the support of DAO and blockchain economic models.

Annie is a former winner of the Canadian National Book Award, while Race previously developed an AI music social networking app with millions of downloads. Setsu and Sloan entered the blockchain field in 2017 and have a deep understanding of economic mechanisms. Tz is a passionate sci-fi enthusiast who has hosted sci-fi-related events on ClubHouse and has a wealth of knowledge on the subject. Elekine has extensive experience in the e-commerce live-streaming industry and has a unique understanding of the creator economy.
## Team code repositories

Our code base is not yet publicly available

# Additional Information
Recommended by kobe(0wjy@bitrisevc.com)
the email address for discussing the grant agreement and general next steps: sloan_gw@magipop.xyz

**Comment by ErinOCon** [comment]
Hi @Kincc-9999, thank you for your proposal. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!
