### ISSUE TITLE
3Pad

### ISSUE THREAD

**Issue by 3Pad** [filecoin-project/devgrants#1522]
### 1. What is your project, and what problem does it solve? (max 100 words)

3Pad is an open-source Web3-based platform that provides landing pages for content creators. The platform is designed to give users an easy-to-use framework for building and managing a single webpage or landing page, with ownership and control over their content. The platform is secure, censorship-resistant, and transparent, providing a decentralized alternative to traditional web hosting services. 3Pad's mission is to empower content creators to own and control their online presence in a decentralized and censorship-resistant manner.

![Logo](https://api.fileverse.io/content/58e4224d-95ca-45da-884c-3f725c93cad0?sessionId=64357f39374004d2b23caff1)

### 2. Project links
  
Link to Github repo: [Github](https://github.com/3Pad/3pad)
Link to demo or website: [Website](https://hello.3pad.xyz)
License: [![License: MIT](https://img.shields.io/badge/License-MIT%2FAPACHE%202-yellow)](https://opensource.org/licenses/MIT)

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

3Pad uses IPFS (InterPlanetary File System) as the underlying technology for storing and delivering user-created landing pages. When a user deploys a landing page on 3Pad, the site is automatically deployed to IPFS, providing censorship-resistant and decentralized storage. This means that the content is distributed across a network of nodes, making it difficult to take down or censor.
###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | Platform development    | Continue developing the platform and adding new features to improve user experience and security. This will include enhancing the page editor, improving user onboarding, and implementing additional security measures. | 3 months |
| 2.     | Marketing               | Launch targeted ad campaigns on social media platforms, collaborate with NFT artists to promote their content on the platform, and develop marketing materials such as blog posts and email newsletters to increase awareness and engagement with the platform. | 3 months |
| 3.     | Community engagement    | Implement a bug bounty program to incentivize community members to identify and report vulnerabilities or bugs on the platform, and engage with the community through social media and other channels to gather feedback and improve the platform. | 3 months |
| 4.     | Technical documentation | Develop technical documentation and tutorials to help users navigate and utilize the platform's features, and provide resources for developers looking to build on top of the platform. | 3 months |

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Osiris Fields - Co Founder - osiris@3pad.xyz
* Jada Dantzler - Co Founder - jada@3pad.xyz

---

* How did you learn about our microgrant program?
Filecoin Website
---

* If your project was created as part of an event or hackathon:
* No
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @3Pad, the theme of each microgrant round is listed [here](https://github.com/filecoin-project/devgrants/blob/master/microgrants/microgrants.md). Please let us know of any questions. In the meantime, I have closed this issue.
