### ISSUE TITLE
Next Step Microgrant: FVM AI NFT GENERATOR

### ISSUE THREAD

**Issue by 1Busayo** [filecoin-project/devgrants#1526]
### 1. What is your project, and what problem does it solve? (max 100 words)

Using AI to convert text into images and mint it as an NFT on FVM. It can be used to create dynamic NFTs or digital arts. The current method (Bacalhau) for creating a text to AI NFT is complex so I created a more straightforward implementation, so other developers can find it easier to develop dynamic NFT on FVM.

TECH STACK: IPFS (NFT.storage), Solidity, Reactjs, Etherjs, Hardhat.

### 2. Project links
  
Link to Github repo: https://github.com/1Busayo/AI-NFT-GENERATOR
Link to demo or website: https://ai-nft-generator-pearl.vercel.app/
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
The smart contract is deployed on FVM and the NFTs are stored on IPFS

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
 Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|

I would create Technical content for this project to educate developers on how they can easily create Dynamic NFT projects on FVM (2 weeks).

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes

  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  name: Samuel Fanimokun
email: [fanimokunbusayo@gmail.com](mailto:fanimokunbusayo@gmail.com)
Github account: https://github.com/1Busayo

* How did you learn about our microgrant program?
  Filecoin Community
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @1Busayo, thank you for your proposal and for your interest in our grants program. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
