### ISSUE TITLE
Pitch Deck Fuel Art 

### ISSUE THREAD

**Issue by kunal171** [filecoin-project/devgrants#1527]
Hello Team FileCoin,
 
I hope this email finds you well. My name is Kunal, and I am the Co-founder of Fuel Art.
Fuel Art is a next-generation NFT marketplace built on Fuel Network, a high-performance, Ethereum-compatible Layer 2 scaling solution. Our platform offers a seamless user experience, low transaction fees, and lightning-fast transaction speeds. 
 
 
 
We are excited to share our pitch deck with you, which outlines our vision, market opportunity, product, and business model. We believe our company has the potential to revolutionize Web3 and Digital Asset Market, and we are seeking investment to help us achieve our goals.
 
 
 
Market Overview: The NFT market is rapidly growing, with a total sales volume of $2.5 billion in the first half of 2021 alone. However, the current market faces scalability issues and high transaction fees, which limit growth potential. Fuel Network solves these issues by offering near-instant transaction confirmation times, low fees, and scalability that can handle millions of transactions per second.
 

Business Model: Fuel Art operates on a commission-based revenue model. We charge a commission on all transactions conducted on our platform, and we plan to expand our revenue streams by offering additional services such as NFT creation and curation tools.
 
 
 
Competitive Advantage: Our platform offers several competitive advantages that set us apart from other NFT marketplaces. These include:
 
Built on Fuel Network, providing low fees, high transaction speeds, and scalability
Advanced search and filtering tools that make it easy to find and discover NFTs
A secure and reliable transaction process that protects both buyers and sellers
Integration with popular wallets and exchanges, making it easy to buy and sell NFTs
Marketing Strategy: We plan to market our platform through targeted advertising campaigns, social media, and influencer marketing. We will also focus on building a community of creators and collectors by hosting events, webinars, and meetups.
 
 
 
Team: Fuel Art is led by a team of experienced entrepreneurs and blockchain experts who have a deep understanding of the NFT market and the potential for growth. Our team includes:
 
Ankit Saini who has [4 years of experience] in the blockchain industry and Backend Development services
Kunal, who has [3 years of experience] in software development and blockchain technology
Investment: Fuel Art seeks funding to scale our operations and expand our team. We are confident that our platform has the potential to revolutionize the NFT market and become a leading player in the industry.
 
 
 
Conclusion: Investing in Fuel Art is a smart decision for investors looking to capitalize on the growing demand for NFTs. With our competitive advantage, experienced team, and innovative platform built on Fuel Network, we are poised to become a leading player in the NFT market. Thank you for considering our investment opportunity.
 

Competitors: We have a significant advantage over our competitors as we have successfully launched a fully scaled decentralized application (Dapp) on the test net of the fuel network, making us the pioneers in this field. Our accomplishment demonstrates our commitment to innovation and our ability to stay ahead of the curve. By being the first to launch a Dapp on this network, we have set a new standard for the industry, and we are excited about the potential for our technology to transform the way people interact with decentralized applications.
 
Launching an MVP on Fuel Testnet is a significant achievement as it indicates that the project has progressed from the development phase to the testing phase. This means that the team has successfully built a working product that can be tested and iterated upon. It also suggests that the team has a clear vision and roadmap for the project, which is critical for gaining traction in the market. 
 

We already have 16k+ active wallets registered on our Dapp. It suggests that the project has generated a lot of interest and engagement from users who are willing to try out the product. This is a key metric for our Dapp, as it indicates that there is a demand for our product and that it is gaining traction in the market. 
 

Additionally, the fact that approximately more than 25% of Fuel beta 3 testnet transactions are coming through Fuel Art is also noteworthy. This suggests that the project has identified a specific use case that is resonating with users and that there is potential for the project to gain traction in this particular market. This can be used as a foundation to build upon and expand the project's user base and overall value proposition. 
 

Overall, these milestones are positive indicators of the project's potential for success. However, it's important to remember that there is still a long road ahead, and the team will need to continue iterating, testing, and refining the product to achieve wider adoption and success in the market.
 
 Use of FileCoin in Fuel Art: - We plan to use FileCoin as our primary storage system for our marketplace for every launchpad and every NFT image and Metadata will be hosted on Filecoin and all in future development that might use decentralized storage we'll be using Filecoin.

 
 
These Are Our Official Website and Twitter Links: 
 
 
 
Website https://fuelart.io/ 
 
Twitter https://twitter.com/fuel_art 
 
Discord https://discord.gg/BGk5UghWWk

Pitch Deck PPT - https://drive.google.com/file/d/1R4fdyfhuaRKmmJAKZpEMdh9dBhwG-TLl/view?usp=share_link
 
 
We would love to schedule a meeting to discuss our vision and answer any questions you may have. We are available for a meeting at your convenience.
 
We look forward to hearing from you soon

**Comment by ErinOCon** [comment]
Hi @kunal171, thank you for your interest in our grants program! Before we proceed with our review, can you complete our standard application template? 

Please open a new issue when you are ready to proceed with this request.
