### ISSUE TITLE
Next Step Microgrant: Dripps

### ISSUE THREAD

**Issue by exstalis** [filecoin-project/devgrants#1528]
### 1. What is your project, and what problem does it solve? (max 100 words)

Dripps is a groundbreaking platform that leverages blockchain technology, including Filecoin, to revolutionize community engagement in the web3 space. Our platform allows communities to interact, share feedback, and participate in events and activities seamlessly, while ensuring privacy through anonymous feedback. We solve the problem of lack of transparency and inclusivity in community engagement by providing a user-friendly and secure platform that fosters genuine connections and enables community members to express their opinions freely without compromising their privacy.
### 2. Project links
  
Link to Github repo: https://github.com/Dripps-Universe/
Link to demo or website: https://dripps.app

License:

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

Dripps is built on Filecoin, one of the most prominent decentralized storage networks, and we utilize its robust and secure storage capabilities to store community data, including feedback, event details, and other community-generated content. This ensures that the community data is securely stored in a distributed manner, providing resilience and data redundancy. Additionally, we leverage other related technologies such as libp2p, IPFS, and OrbitDB to create a distributed and peer-to-peer network for community engagement. Our platform utilizes the power of blockchain technology to create a transparent and trustless system where community members can interact, share feedback, and participate in activities in a decentralized and privacy-preserving manner, empowering them to have more control over their data and fostering a more inclusive and authentic community engagement experience in the web3 ecosystem.
###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)

  Yes, this project is building with the current microgrants focus area, which is the Filecoin Visionary-Missionary (FVM) program.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
Number	Grant Deliverable	Briefly describe how you will meet deliverable objectives	Timeframe (within 3 months)
1.	MVP Launch: NFT and POAP Functionality to Support All Events	We will develop and launch the minimum viable product (MVP) version of the Dripps platform with NFT (Non-Fungible Token) and POAP (Proof of Attendance Protocol) functionality to support all events. This will involve integrating smart contract functionality for NFT and POAP creation and management, as well as ensuring smooth user experience for event organizers and attendees.	1-2 months
2.	Continuous Iteration and Improvement	Once the MVP is launched, we will gather user feedback, iterate on the platform, and continuously improve its features, user interface, and overall performance based on user needs and feedback. This may involve updates, bug fixes, and enhancements to ensure a seamless experience for users.	Ongoing
3.	Community Engagement Campaigns	We will launch targeted community engagement campaigns to encourage users to provide feedback, actively participate in events, and share their experiences. This may include social media campaigns, community events, and other initiatives to foster community involvement and gather valuable insights from users.	2-3 months
4.	Enhance Community Accounts and Feedback Structure	As the platform gains traction and the community grows, we will work on developing a system that allows for community accounts with anonymous feedback structure. This will involve implementing a feedback form within the platform, ensuring user anonymity, and establishing a process for collecting, analyzing, and distributing feedback in numerical form to the community.	3-4 months
5.	Documentation and Knowledge Sharing	We will create comprehensive documentation and knowledge sharing resources to provide transparency to the community and share our progress, challenges, and learnings. This may include blog posts, tutorials, and documentation on the platform's development, features, and community engagement initiatives.	2-3 months

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

  Yes, if our project is accepted, we agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete. The updates will include progress or results of our microgrant-funded work, any Filecoin technical or usage guidance requests, and a description of our experience building on Filecoin, including any challenges or shortcomings encountered. We are committed to providing regular updates to keep the community informed about our progress and to seek support or guidance as needed during the development process.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes, our proposal complies with the Filecoin Community Code of Conduct. We have reviewed and understand the Code of Conduct, and our project and team will adhere to the principles and guidelines outlined in it. We are committed to maintaining a respectful and inclusive environment throughout the development of our project and will ensure that all interactions and communications align with the values and expectations set forth in the Filecoin community.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 
Yes, Last year I myself attended with the project ideation phase and we submitted for FEVM Hackaton. Poaps are available upon request

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
https://github.com/exstalis - Founder
https://github.com/coolguycam - Technical Support/Advisor

* How did you learn about our microgrant program?
Online Search and debates on grant applications. 

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
N/A - > https://github.com/0x606a/Dripps

**Comment by exstalis** [comment]
@ErinOCon Good Morning, If there is any additional information I can provide, please feel free to contact me
Thank you!

**Comment by ErinOCon** [comment]
Hi @exstalis, thank you for your proposal and for your interest in our grants program. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
