### ISSUE TITLE
Decentralized, Globally-distributed Climate Sensor Data for Public Goods

### ISSUE THREAD

**Issue by weavechain-web3** [filecoin-project/devgrants#1529]
# Open Grant Proposal: `Decentralized, Globally-distributed Climate Sensor Data for Public Goods`

**Decentralized, Globally-distributed Climate Sensor Data for Public Goods:**

**Proposal Category:** `Integrations`

**Individual or Entity Name:** Weavechain

**Proposer:** `weavechain-web3`

**(Optional) Filecoin ecosystem affiliations:** `David Aronchick & Wes Floyd, Protocol Labs` 

**(Optional) Technical Sponsor:** David Aronchick & Wes Floyd, Protocol Labs`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary
This project aims to provide an integration between IPFS, Weavechain, and Bacalhau to bridge the gap between legacy data storage. We’ll showcase this for our customer ClimeCheck, to support the global initiative for Climate Research for public goods. By utilizing Weavechain's integration with over 26 databases and ability to put snapshots on IPFS, we will build an integration for ClimeCheck to securely store incrementally updating snapshots of real-time sensor readings from around the world in a global climate commons of open-source data.

Weavechain would also store an index of all the parts that were saved from a time series in a regular DB and put proofs on a blockchain, so researchers would be able to reconstruct it from immutable pieces, guaranteeing data integrity. The snapshot data and blockchain proofs would be available for researchers to use Bacalhau's Compute Over Data technology to further the global effort to understand and mitigate the negative effects of climate change.

The background for this project is that ClimeCheck currently sells consumers an inexpensive Air Quality Sensor that can be plugged in at home. They're establishing partnerships with local refineries who would go and buy the data to use for their ESG (Environmental, Social and Governance) reporting, allowing them to compensate the consumers with a source of passive income. These consumers usually reside in low-income regions in Nigeria and Ethiopia, and there is work being done to establish a partnership with the African Union to expand their reach. 

ClimeCheck would like to additionally make this data available to a “global climate commons" of open-source climate data for research to contribute to the global effort to combat climate change. While storing this global climate commons of open-source data would further ClimeCheck's mission, the problem with putting this data directly on IPFS is that storing every new sensor reading presents two obstacles:
1. Millions of readings in short timeframes could overload and slow down the network
2. IPFS is not the ideal system for storing time series: once you put something there, it is addressed by a hash of its content, meaning you can't "update" something you've added to IPFS

That's why we propose to integrate IPFS with Weavechain, using Weavechain as a secure data layer interface to be putting snapshots of data rather than every individual update on IPFS to be available for research using Bacalhau's Compute over Data technology for researchers to utilize in their work for public goods.

## Impact 
This project has the potential to significantly impact the global climate research effort. By providing a secure data layer interface to store snapshots of aggregated real-time sensor readings from around the world on IPFS, we will create a global climate commons of open-source data that can be used by researchers and businesses alike. This data will be available for anyone to use to understand climate change, develop innovative solutions, and help mitigate its effects.

As an open-source integration that can be reconfigured to work with all sorts of large time-series datasets, this project seeks to address the pain point of storing and providing open-source access to any kind of large time-series dataset using IPFS.

Getting this project right has the potential to make a huge impact on the fight against climate change. By providing an open source data commons of real-time sensor readings from around the world, researchers will have access to more accurate and up-to-date data than ever before. This could lead to more accurate models and predictions of the effects of climate change, allowing us to take more effective action to mitigate them. 

Additionally, the growth and success of this project will provide a source of passive income to consumers in low-income regions who have installed ClimeCheck's Air Quality Sensors. 
The success of this project can be measured by its ability to provide reliable data that is accessible to researchers and businesses, and its ability to create an economic incentive for people in low-income regions.

## Outcomes
To measure the success of this project, we will track several metrics:

1. Number of sensor readings being stored in the global climate commons on a daily basis
2. Number of researchers and businesses accessing this data and using it to develop solutions or gain insights into climate change
3. Amount of passive income generated for consumers in low-income regions who have installed ClimeCheck's Air Quality Sensors
4. Reliability and uptime of the integration between Climecheck, Weavechain, IPFS, and Bacalhau. We aim to achieve at least three 9s of uptime for this integration to ensure that researchers and businesses can rely on this data being available when they need it
5. Feedback from users of this integration to understand how it is impacting their work and what improvements could be made. This feedback will help us continue to improve and iterate on this project over time
6. Number of additional businesses with time-series DBs they'd like to open-source who express interest in using Weavechain to achieve a similar storage of data snapshots on IPFS

## Adoption, Reach, and Growth Strategies
The primary target audience for this project is researchers and businesses looking to access open-source climate data. This is a significant and broad audience including but not limited to scientists, researchers, policymakers, NGOs, government agencies, students, and other stakeholders who need to access and analyze climate data to make informed decisions.

ClimeCheck is currently engaging with this audience through its partnerships with local refineries, their proposed partnership with the African Union, and through ongoing research and discovery efforts.

## Development Roadmap
The development of this project will be divided into three milestones. Each milestone will tackle a specific aspect of the integration between Climecheck, Weavechain, IPFS, and Bacalhau.

### Milestone 1: Integration Between ClimeCheck and Weavechain
Functionality: Develop an integration between ClimeCheck and Weavechain that enables the secure storage of snapshots of real-time sensor readings from around the world in a global climate commons of open-source data on IPFS.
Team Members: One full-stack developer with experience in integrating blockchain technologies, ClimeCheck CEO and engineer to support with data and answers to questions.
Funding Required: $4,000
Timeline: 2 weeks (September 4 - September 15)

### Milestone 2: Integration Between Weavechain and IPFS
Functionality: Develop an integration between Weavechain and IPFS that allows for the secure storage of snapshots of real-time sensor readings.
Team Members: One full-stack developer with experience in integrating blockchain technologies, Weavechain CEO to support with product requirements.
Funding Required: $4,000
Timeline: 2 weeks (September 18 - September 29)

### Milestone 3: Final Testing and Deployment
Functionality: Conduct final testing on all integrations to ensure reliability and uptime, including the ability to use Bacalhau's Compute Over Data technology to make further use of stored snapshots. Deploy the integrated solution for public use.
Team Members: One full-stack developer with experience in deploying blockchain technologies, Weavechain CEO to interview two researchers for testing integration's usability.
Funding Required: $7,000
Timeline: 3 weeks (October 2 - October 20)

The total funding required for this project is $15,000. The team will consist of one full-stack developer with experience in integrating and deploying blockchain technologies, one representative from ClimeCheck to provide data and answer questions, and two researchers to interview for usability testing. The timeline for completing all milestones is approximately 7 to 8 weeks, with a launch date of September 4.

## Total Budget Requested
| Milestone # | Description | Deliverables | Completion Date | Funding |

| 1 | Integration Between ClimeCheck and Weavechain | An integration between ClimeCheck and Weavechain that enables the secure storage of snapshots of real-time sensor readings. | September 15th, 2023 | $4,000 | 
| 2 | Integration Between Weavechain and IPFS | An integration between Weavechain and IPFS that allows for the secure storage of snapshots of real-time sensor readings. | September 29th, 2023 | $4,000 | 
| 3 | Final Testing and Deployment | Final testing and debugging of all integrations to ensure reliability and uptime, including the ability to use Bacalhau's Compute Over Data technology to make further use of stored snapshots. Interview reports from two researchers for testing integration's usability and usability improvements. Deployed integration solution for public use and open source code for modification for other use cases. | October 20th, 2023 | $7,000 |

## Maintenance and Upgrade Plans

The success of this project doesn't end with the completion of the development roadmap. To maintain its impact, Weavechain plans to continue supporting and improving the integration through ongoing maintenance and upgrades.

One key aspect of this long-term plan is to ensure that the integration remains secure and reliable. This will require regular updates to address any vulnerabilities or bugs that may arise over time. We will also monitor the network for any potential threats and take proactive measures to prevent them from causing disruption or data loss.

Another important element of our long-term plan is to improve the functionality of the integration based on user feedback. We will actively seek out feedback from researchers, businesses, and other stakeholders who use this data. This feedback will help us identify areas where we can make improvements or add new features that better meet their needs.

Finally, we plan to continue expanding the reach and impact of this project by partnering with other organizations and initiatives producing and in possession of similar datasets that could be snapshotted and hosted on IPFS to support research for public goods. By collaborating with like-minded groups, we can leverage our collective expertise and resources to achieve even greater impact in the mission to create and maintain a decentralized, efficient, and robust foundation for humanity’s information.

# Team
## Team Members
Ioan Moldovan
Omar ElNaggar
Bruno Chikeka

## Team Member LinkedIn Profiles
[Ioan Moldovan](https://www.linkedin.com/in/ioan-moldovan/)
[Omar ElNaggar](https://www.linkedin.com/in/oelnaggar/)
[Bruno Chikeka](https://www.linkedin.com/in/brunochikeka/)

## Team Website
[Weavechain](https://www.weavechain.com/)
[ClimeCheck](https://climecheck.network/)

## Relevant Experience
Our team has extensive experience in the fields of blockchain technology and data science. Ioan Moldovan is a full-stack developer with extensive experience in developing and deploying blockchain applications. Omar ElNaggar is a data scientist with experience in working with large datasets and leveraging machine learning algorithms to uncover insights who is passionate about . Bruno Chikeka is an engineer with experience in developing hardware solutions for environmental monitoring, including ClimeCheck's Air Quality Sensors. His partnerships with local communities, governmental organizations, and NGOs are also essential to this project’s success. Together, we have the technical expertise, domain knowledge, and audience reach necessary to successfully develop and launch this project.

## Team code repositories
None

# Additional Information
We heard about the Open Grants Program from our advisors Wes Floyd and David Aronchick at Protocol Labs. The best email address for outreach is: [omar@weavechain.com](mailto:omar@weavechain.com)

#### Competitive Landscape
It's worth noting the competitive landscape of this project, which includes existing climate data repositories and platforms such as the Climate Data Store by the European Centre for Medium-Range Weather Forecasts, NASA's Earth Observing System Data and Information System (EOSDIS), and the National Oceanic and Atmospheric Administration's (NOAA) National Centers for Environmental Information.

However, what sets our project apart is our focus on decentralization and open-source data. By leveraging blockchain technology and IPFS, we aim to create a public good that is accessible to all stakeholders with an internet connection. Additionally, our accessibility to Bacalhau's Compute Over Data technology allows for more efficient analysis of large timeseries datasets.
#### Impact on Climate Research
The potential impact of this project on climate research cannot be overstated. By creating a global climate commons of open-source data, researchers will have access to real-time sensor readings from around the world. This will enable them to make more informed decisions about climate change mitigation strategies, track progress towards emissions reduction targets, and better understand the impacts of climate change on vulnerable populations.

Furthermore, by making this data available in a decentralized manner through IPFS, we are reducing reliance on centralized authorities that may be subject to political pressure or other forms of interference. This ensures that the integrity of the data remains intact and that it can be accessed by anyone who needs it regardless of their location or political affiliation.

#### Conclusion
In conclusion, this project has significant potential to make a positive impact on climate research and global efforts towards mitigating climate change. Our team has the technical expertise and domain knowledge necessary to successfully develop and launch this project. We are excited about the opportunity to integrate ClimeCheck, Weavechain, IPFS, and Bacalhau to create a public good that benefits society as a whole.

**Comment by ErinOCon** [comment]
Hi @weavechain-web3, thank you for your proposal! We are behind schedule for our April submissions, but expect to have an update available in the next couple weeks. Thank you for your patience!

**Comment by ErinOCon** [comment]
Hi @weavechain-web3, thank you for your ongoing patience during this unexpectedly long review period. This proposal is in the final stages of review. We expect to have an update available soon.

**Comment by weavechain-web3** [comment]
Thanks for the update, Erin! Looking forward to hearing from you. Please
let us know if you have any questions.

All the best,
Leticia

--

<http://www.weavechain.com>

Leticia Shaaban

Director of Community & Design

<https://www.linkedin.com/in/leticia-shaaban/>

**Comment by realChainLife** [comment]
Hi @weavechain-web3 we appreciate your patience with our feedback here. Could you provide additional details on the following: 

- Can you also clarify the proposal is a database backend tool for storing MongoDB data onto IPFS, and eventually Filecoin. The current development roadmap reads differently. 
- Unfortunately your (account submitting application) Github history leaves us unable to verify your connection with Weavechain, do you have other links you can share to provide this verification.

**Comment by weavechain-web3** [comment]
Hi Sonia, thanks for your message, happy to clarify:

1. Correct, the heart of this proposal is storing ClimeCheck's sensor data
into IPFS and eventually Filecoin. We had not mentioned MongoDB
specifically in our original proposal because this implementation will
enable the storing of data from any database that Weavechain supports into
IPFS/Filecoin, including heavy timeseries databases like InfluxDB, and
traditional ones like PostgreSQL. This is encapsulated in Milestone 2 with
the Integration Between Weavechain and IPFS.
2. Apologies for the disconnect in accounts here, we had submitted the
proposal from our business development GitHub account while we were still
preparing our core open source repo (https://github.com/weavechain). I've
gone and forked the 'Inheritable' repo from the account submitting the
application (weavechain-web3) over to our main repo (weavechain) as a
simple proof. What else can I do to give you confidence that we own both
accounts? I'm happy to have our CEO send you an Email from his corporate
account ***@***.*** confirming that we own both GitHub
accounts.

**Comment by ErinOCon** [comment]
Thank you for the update, @weavechain-web3! We have just sent you an email regarding the proposal status and will be in touch as soon as more information is available.

**Comment by ErinOCon** [comment]
Hi @weavechain-web3, thank you again for your patience with our review. Unfortunately, due to budget constraints in this current climate, we are not able to move forward with a grant at this time. We appreciate the work you are completing and are wishing you all the best as you continue forward!

If you have any questions for our team, please feel welcome to contact us at [grants@fil.org](mailto:grants@fil.org).
