### ISSUE TITLE
Next Step Microgrant: Megaxis tokenizing AI prompts

### ISSUE THREAD

**Issue by dvzhang** [filecoin-project/devgrants#1530]
### 1. What is your project, and what problem does it solve? (max 100 words)

Megaxis is a decentralized platform that enables tokenizing AI prompts, providing a new revenue stream for prompt engineers. Our platform allows you to mint your prompt as an ERC-721 NFT, share it as a template with others without revealing the actual text, and earn revenue from sharing and selling your prompt NFT. Through incentivizing high-quality prompt creation via tokenomics and fostering a strong community of prompt engineers and users, Megaxis seeks to build an AI resource sharing pool that encourages efficient machine learning. We plan to expand our use case by collaborating with more AI generative tools and enabling the community to rent and share GPU resources. 
Our smart contract is deployed on Filecoin Hyperspace testnet, and our NFT is stored on IPFS. We want to deploy on Filecoin network using FVM to automate minting, revenue and governance function. We also want to tap into the decentralized compute power. 

### 2. Project links
  
Link to Github repo: https://github.com/megaxis-for-ethtokyo/megaxis_for_ethtokyo
Link to demo or website:  http://megaxis.ai:8528/welcome
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

MEGAxis uses smart contracts written in Solidity. Every prompt mints a unique NFT ( PromptNft.sol) which stored by ipfs and can be bought, sold or rented on our marketplace powered by (PromptNftMarketplace.sol). We deploy on the industry-leading Hardhat infrastructure to ensure high-performance and seamless execution.
In addition, We integrate with The Graph indexing protocol to create subgraphs that allow users to easily query prompt data and optimize their AI models. We also store our data on Filecoin to ensure maximum security and decentralization. We deploy the smart contract on Filecoin Hyperspace testnet
###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.  |   Backend Dev and technology Research     |  Conduct product competitive and market research to clarify problem statement and product solution. Conduct technical research, conduct trials and tests to select suitable protocols to leverage. Hiring. |      1st month                      | 
| 2.     |   User Experience Research   |    Conduct user research to understand pain point, Determine product value preposition                                                         create userflow. Hiring. |              1st month              | 
| 3.     |    V1 infrastructure, basic UI wireframe , White-paper draft  |    Finalize product user-flow, upgrade protocol deployments, begin with basic visual kit to develop V0.1, produce white paper draft 1       |               2nd month             | 
| 4.     |           Beta Test V1, Publish white paper        |         V1  launch for beta testing, collect internal and WL user feedback to begin with V2                                                          |           3rd month                 | 
### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes.
https://ethglobal.com/showcase/megaxis-wvxrq
Prizes won during EthGlobal Tokyo:
FVM: Compute over Data
The Graph: Pool Prize
Polygon: Pool Prize 
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Frank, dvzhangtz@gmail.com, dvzhang, Co-founder, CTO, full-stack developer
Shina, shizudio.eth@gmail.com, shizudio.eth@gmail.com, Co-founder, Product manager and Lead designer
Huang Run Ze, 878822589@qq.com, hrzisme, front-end developer 
Chen Boyu, neilneilchen5555@gmail.com, neilneilchen5555@gmail.com, Operation, front-end developer
Xu Zhida, 1459601448@qq.com, xzd1621, full-stack developer
* How did you learn about our microgrant program?
Conversed with Filecoin members (Sarah Thiam and Robert) during EthGlobal Tokyo
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
Yes, EthGlobal Tokyo
  * Please link to your hackathon submission
https://ethglobal.com/showcase/megaxis-wvxrq

**Comment by eshon** [comment]
@dvzhang Can you please respond to @trruckerfling's asks above to be considered for an FVM microgrant?

**Comment by dvzhang** [comment]
Really sorry for the delay, missed this message. @eshon @trruckerfling Thanks for reminding!!!

1. ensure that minting an NFT is done using an FVM contract on our testnet (or can you confirm that is being done already)
Yes: the contract is deployed to testnet (prompt-nft：https://hyperspace.filscan.io/address/general?address=0x86929a4634CbB0f9c4c77cE0Ae9987D70144Ce0B)

2. using FVM's client contract to store the NFT once minted, onto Filecoin, while continuing to back up on IPFS for easy retrieval
Now, we store our NFT on IPFS, for example: ipfs://QmT7paUH7aZRdR36oEJiNrxzUaxMxN3GbzFrK68M3zLuWC/?filename=0-Prompt.json

3. deploying the project onto a testnet and aspirationally on mainnet (we can provide some gas funds to help with mainnet deployment)
Of course, we already deplyed our contrant on testnet! 
prompt-nft：https://hyperspace.filscan.io/address/general?address=0x86929a4634CbB0f9c4c77cE0Ae9987D70144Ce0B
prompt-nft-market：https://hyperspace.filscan.io/address/general?address=0xba6fbbAB59C04aacde97831Df2C8f903E5c8849E

Really appreciate for your gas funds help! (wallet address: f12ezq4unutxg4riukyiigclloeh33enmbpqho7ni)

4. general UI/UX improvements for a smooth user flow (we can chat more)
We are still trying to make our front-end better. http://megaxis.ai/

**Comment by dvzhang** [comment]
Thanks for your feedback! @eshon 

	1. Unfortunately the Hyperspace testnet will be discontinued at the end of this month. So please move all of your contracts to Filecoin's Calibration testnet.
	OK~

	2. Filecoin isn't a current option in your UI so please make sure it's added for this microgrant.
	Yes. This day we changed our front-end a lot. We will add filecoin within one week.

	3. Also for this microgrant, we'd like to see your project use FVM's client contract to automatically store the NFT once minted, onto Filecoin, while continuing to back up on IPFS for easy retrieval.
	OK, we will make it within two weeks.
	
Thanks for your help!

**Comment by eshon** [comment]
@dvzhang - One of our microgrant reviewers just noticed that none of your team members are listed as committers to the Megaxis Github repo here: https://github.com/megaxis-for-ethtokyo/megaxis_for_ethtokyo 

Can you please explain this or confirm your relationship to the original Megaxis Github project?

**Comment by dvzhang** [comment]
Sorry for the confusion. One of my teammates (Huang Run Ze) had two github accounts, and when he submitted microgrant at the time it didn't match the account he was using at eth tokyo.

**Comment by ErinOCon** [comment]
Hi @dvzhang, thank you for the provided explanation. Can a project contributor that is represented in the repo comment here clarifying their involvement?

**Comment by eshon** [comment]
@dvzhang - Any update? Can you provide proof that you worked on https://github.com/megaxis-for-ethtokyo/megaxis_for_ethtokyo?

**Comment by ErinOCon** [comment]
This issue has been closed. Please feel welcome to open a new issue to share additional context.
