### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by chaalpritam** [filecoin-project/devgrants#1531]
# Open Grant Proposal: `Filter`

**Project Name:** Filter

**Proposal Category:** `Applications`

**Individual or Entity Name:** Individual

**Proposer:** `chaalpritam`

**(Optional) Filecoin ecosystem affiliations:** `No` 

**(Optional) Technical Sponsor:** `No`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** `Yes` 

# Project Summary

Filter is a social app for Web3. Unlike others, here you can mint photos directly with a limited number of mints per day. The Filter encourages users to focus on capturing their best shots rather than snapping hundreds of photos and filtering them. Moreover, our dynamic pricing and NFT marketplace enable users to trade their unique photos as valuable assets.

https://twitter.com/filterappfun
https://twitter.com/filterappfun/status/1641534711989428224

We have made a prototype for the Solana hackathon, but we have decided to shift our focus towards Filecoin FVM due to its storage advantages.

https://twitter.com/filterappfun/status/1639383802169659393?s=20

## Impact 

The proposal of integrating with Filecoin and Filter, is highly valuable for several reasons. 

Firstly, it addresses the pain point of centralized control of user-generated content, where the data is stored on centralized servers, and the content can be censored, modified, or lost due to a variety of reasons. 

Filecoin and IPFS provide a secure, tamper-proof, and fault-tolerant environment to store data, ensuring that users' content remains private and accessible.

Secondly, this will allow users to have greater control over their data and monetize their content through non-fungible tokens (NFTs). The Filter's dynamic pricing and NFT marketplace enable users to trade their unique photos as valuable assets, thereby creating new revenue streams for creators and incentivizing them to produce high-quality content.

Getting this integration right would lead to several benefits, such as increased user adoption of filecoin storage, increased demand for NFTs, and increased revenue for creators, where creators have greater control over their content, and users have a seamless and secure experience.

## Outcomes

**Specification document:** will outline the project's scope, requirements, and objectives, and provide a detailed description of the integration process, including the necessary tools and technologies required.

**Integration of Filecoin FVM and IPFS:** will involve integrating Filecoin and IPFS with the App, ensuring that users' data is securely and transparently stored.

**Smart contract development:** will involve developing smart contracts that enable users to mint photos directly with a limited number of mints per day and enable the dynamic pricing and NFT marketplace functionality.

**User interface design:** will involve designing a user-friendly interface that allows users to seamlessly interact with the platform and utilize its various functionalities.

**Testing and deployment:** will involve extensive testing of the integrated platform to ensure its functionality, security, and scalability, followed by the deployment of the platform on a testnet and eventually on the mainnet.

## Measuring Success 

**User adoption:** The number of active users and the rate of user acquisition can be used to measure the platform's adoption rate.

**User engagement:** The level of user engagement with the platform, such as the frequency of use, the time spent on the platform, and the number of interactions, can indicate the platform's popularity and effectiveness.

**Revenue generated:** The amount of revenue generated by content creators through the NFT marketplace can indicate the platform's ability to incentivize high-quality content creation and monetization opportunities.

**Data storage:** The amount of data stored on the filecoin network and the rate of growth can indicate the platform's scalability and effectiveness.

**Community feedback:** Feedback from the platform's community, such as user surveys, reviews, and forums, can provide valuable insights into user satisfaction and identify areas for improvement.

## Adoption, Reach, and Growth Strategies

The target audience for such a project could be content creators and users who value privacy, security, and transparency as we expand this into a full fledge social media platforms. This could include photographers, artists, influencers, and social media enthusiasts who are looking for new opportunities to monetize their content and engage with a community of like-minded individuals.

To identify the size and characteristics of the target audience, we could conduct market research and analyze user data to identify trends, preferences, and pain points. This could involve surveying potential users, analyzing competitor platforms, and leveraging data analytics tools to gather insights into user behavior and preferences. By understanding the target audience's needs and preferences, we can tailor their marketing and engagement strategies to effectively reach and engage with this audience.

## Onboard Users

To onboard new users, we could leverage various strategies, such as offering incentives, simplifying the registration process, and providing user-friendly interfaces. For example, we could offer a limited number of free NFTs to new users who sign up for the platform or refer their friends. we also simplify the registration process by allowing users to sign up with their existing social media accounts and providing step-by-step instructions for creating a digital wallet and purchasing cryptocurrency. Additionally, we could provide user-friendly interfaces that guide users through the process of minting and trading NFTs, as well as interacting with the decentralized storage network.

To onboard the first 100 users, we could leverage their personal networks and engage with early adopters in relevant online communities, such as forums, social media groups, and Discord channels. We can also offer beta access to a limited number of users and gather feedback to improve the platform's functionality and user experience.

To onboard the first 1000 users, we could also offer incentives, such as exclusive NFT drops, rewards for referrals, and discounts on platform fees, to incentivize users to join and engage with the platform. Additionally, we could leverage data analytics tools to optimize their marketing and engagement strategies and identify areas for improvement.

By leveraging these strategies, we can onboard new users and build a loyal community.

## Development Roadmap

Milestone 1: User Interface Design and Smart Contract Development

Functionality: Develop a user-friendly interface that allows users to create, edit, and trade NFTs. Develop smart contracts for minting, bidding, and trading NFTs.
Funding: $5,000
Timeframe: 3 weeks

**Milestone 2:** Platform Infrastructure and Filecoin/IPFS Integration with Mobile App (IOS & Android)

Functionality: Create the core infrastructure of the platform and integrate it with Filecoin and IPFS to enable users to mint, store, and trade NFTs on a decentralized storage network.
Team: 2 developers.
Funding: $15,000
Timeframe: 6 weeks

Milestone 3: Launch and Community Building

Functionality: Launch the platform and build a community of users and content creators who value privacy, security, and transparency in social media platforms.
Funding: $5,000
Timeframe: 3 weeks

## Total Budget Requested

$25k

## Maintenance and Upgrade Plans (based on further funding)

Regular updates and bug fixes
Community building
New feature development
Partnerships and collaborations

# Team

## Team Members

[Chaal Pritam](https://github.com/chaalpritam) - UI Design (3 Years) & FullStack JS & Blockchain Engineer (8 Years)
[Sathish Kumar](https://github.com/sathishkumarmsk) - React Native & Backend Engineer (3 Years)
[Yoga Lakshmi](https://github.com/IamYogalakshmi) - UI/UX & Frontend Engineer (3 Years)
[Akshaya](https://github.com/akshayacode) - Blockchain & Solidity Engineer (3 Years)

## Team code repositories

https://github.com/chaalpritam/FilterFun
https://github.com/chaalpritam/filterfunfvm

# Additional Information

https://twitter.com/filterappfun

**Comment by ErinOCon** [comment]
Hi @chaalpritam, thank you for your proposal. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!
