### ISSUE TITLE
PowerVoting

### ISSUE THREAD

**Issue by macro-ss** [filecoin-project/devgrants#1533]
### 1. What is your project, and what problem does it solve? (max 100 words)
Power Voting is going to enable people voting in trustless based on FEVM, and it uses the timelock feature based on drand which can make sure the data security during the voting process. Timelock feature gives you time based encryption and decryption capabilities by relying on a drand threshold network. please refer to https://drand.love/ for drand network details, which is verifiable, unpredictable and unbiased random numbers as a service. Per encryption/decryption time based, the secret info can’t be leaked before end time, thus it doesn’t need a centralized public notary to monitor the process and justify the result.

### 2. Project links
  
Link to Github repo: https://github.com/black-domain/power-voting
Link to demo or website: https://sparkling-rain-4933.on.fleek.co/
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

This project will use IPFS to deploy the PowerVoting website, and all of the NFT metadata will be stored in IPFS.
The contracts used in the project are deployed on the Filecoin network.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable      | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                                | :---                                                                      | :---                       | 
| 1.     |   UX Improvement           |   Refactor beta version based on new design    |     10 Days           | 
| 2.     |   Feature Complete         |   Full feature implemented                                  |      55 Days          | 
| 3.     |   Smoke Testing              |   Functionality check                                           |      5 Days            | 
| 4.     |   Smart Contract Audit    |   Audit smart contract with 3rd-parties                |      5 Days            | 
| 5.     |   Testnet Deployment      |  Deploy dapp into testnet and test                      |      5 Days            | 
| 6.     |   Mainnet Deployment     |  Deploy dapp into mainnet and test                    |      5 Days            | 
| 7.     |   Marketing Engagement |  Engage FIP polling via PowerVoting                 |      5 Days            | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project. 
  ***[Team Members](https://github.com/black-domain/power-voting)***
* How did you learn about our microgrant program?
  ***From Community***
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
    ***Randomness Summit 2023***
  * Please link to your hackathon submission

**Comment by jennijuju** [comment]
I am very interested in this application, I think with concrete requirements, it could be useful for FIL+ governance and much more later on!

**Comment by ErinOCon** [comment]
+ @eshon

**Comment by ErinOCon** [comment]
Hi @macro-ss, thank you for your grant proposal! Is this still an outstanding project you have an interest in building?

**Comment by Flyssit** [comment]
Sure, It is still working in progress.

**Comment by macro-ss** [comment]
Sure, it is still working in progress.

> Hi @macro-ss, thank you for your grant proposal! Is this still an outstanding project you have an interest in building?

**Comment by ErinOCon** [comment]
Hi @macro-ss, can you confirm the team members for this project? The link currently only takes me to the repo. Also, I do not seek you listed in the commits/project activity. Can you clarify your involvement with the project?

**Comment by eshon** [comment]
@macro-ss - You're not listed as a contributor https://github.com/black-domain/power-voting/graphs/contributors can you provide proof that you're on the team?

**Comment by macro-ss** [comment]
@ErinOCon @eshon Sorry for making you guys confuse on this, knig**1 is me, I am the admin of this repo. Yes, we are still building on this project, new features are under developing now, any suggestions are welcome!

**Comment by eshon** [comment]
Hi @macro-ss - Can you please post a comment in this thread using your other Github handle or have one of your other contributors do it? We just want to be sure you're an original contributor to the project.

**Comment by xianglinhe** [comment]
> Hi @macro-ss - Can you please post a comment in this thread using your other Github handle or have one of your other contributors do it? We just want to be sure you're an original contributor to the project.

Hi @eshon , yes, we are a team work on it. @macro-ss is the admin of this repo: https://github.com/black-domain/power-voting/commits/main

**Comment by ErinOCon** [comment]
Thank you for the clarification! We will be in touch after the holidays.

**Comment by ErinOCon** [comment]
Hi @macro-ss, thank you for your proposal and for your patience with our review process. It's great to see this project continue to progress. Unfortunately, after much consideration, it has been determined that we will not be be moving forward with a new grant at this time.

I will be sending you an email shortly to discuss other ways to partner with our community (in case you have an interest). Wishing you the best as you continue to build!
