### ISSUE TITLE
Next Step Microgrant: EASTORE

### ISSUE THREAD

**Issue by lordshashank** [filecoin-project/devgrants#1535]
### 1. What is your project, and what problem does it solve? (max 100 words)
Eastore is a decentralized storage marketplace built using FEVM on the backend and user-friendly UI for people to store and retrieve their files on-chain directly. We aim to provide services that remove hurdles for people making on-chain deals.

### 2. Project links
  
Link to Github repo: https://github.com/lordshashank/Eastore-Filecoin
Link to demo or website: https://drive.google.com/file/d/14QGmS-Wf-YZc36R5b9gkpKKF1B8QaNhM/view?usp=share_link
Link to pitch: https://www.canva.com/design/DAFg5brV9bQ/9qhAShKPiTVHoXC6MyqVCw/view?utm_content=DAFg5brV9bQ&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink
Link to devfolio: https://devfolio.co/projects/eastore-e336 
Dapp link= https://eastore-filecoin.vercel.app/
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
We use FEVM smart contracts to make and retrieve deals directly from the Filecoin blockchain. We aim to develop a product where users can just come, store their files by running the meta mask transaction and be able to download it whenever they want by using our UI. We currently use deal client contracts and lotus to make all this possible. We aim to shift all this to smart contracts using FEVM so that everything becomes transparent with on-chain visibility. We also aim to provide cross-chain functionality in our Dapp that will allow users to have any token to make an on-chain deal. We look forward to make a product comparable to google-drive and one-drive but uses web3 wallet to login and Filecoin's blockchain to store the data in a decentralized way. We look forward to build SDKs for the features stated so that other people can also utilise the features we use like cross-chain functionalities, etc.
###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
  YES
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |  Use FEVM smart contracts to make and retrieve deals on-chain                       |     We will use deal client contract to enable these functionalities on our Dapp                                                       |     1 month                       | 
| 2.     |   Integrate cross-chain functionality to make people having any token to use the Eastore to make on-chain storage deals                      |  we are working with axelar, router protocols to integrate this feature by writing smart contracts on different chain                                                          |     1.5  months                      | 
| 3.     |  work to make the free-flowing UI                      |  We know the importance of UI, and we would be developing and iterating throughout to make it user-friendly as per reviews by community and testers                   |     2  months                      | 
| 4.     | Build an MVP  and SDK(if possible)                   |      after integrating all important features we look forward to deploy our dapp for further feedbacks and then go for mainnet deployment. Moreover if time permits, we look forward to build SDK for others to implement this cross-chain functionality                                             |       2-3 month                    | 

Throughout the period we would be improving the UI to make it as par if not better than the centralized solutions like drive, etc. so as give users smooth transition to decentralized databases rather than trusting some centralized authority for it.

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
YES, I agree to share monthly updates of the project.

### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* We created this project during the ETHForAll hackathon, organized by ETHIndia and Devfolio. Our project was one of the top 3 hacks in the Filecoin track. Below is the link to the project:
 * Devfolio link: https://devfolio.co/projects/eastore-e336 
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
    * Shashank Trivedi - shashanktrivedi1917@gmail.com - @lordshashank - smart contract and backend developer
    * Puspendra Mahariya - @me-loser - frontend developer 
* How did you learn about our microgrant program?
     * Came to know about it by participating in FEVM mainnet cohort
* If your project was created as part of an event or hackathon:
     *  We created this project during the ETHForAll hackathon, organized by ETHIndia and Devfolio. Our project was one of the top 3 hacks in the Filecoin track. Below is the link to the project:
     *  Devfolio link: https://devfolio.co/projects/eastore-e336

**Comment by eshon** [comment]
@lordshashank - I see good activity around the backend but your dapp's UX and frontend needs improvement. I don't see any improvements proposed for this in your roadmap. Can you comment on this?

Note that our requirements for completion of an FVM Microgrant are as follows:

- A fully working user-facing demo with nice UX that anyone can easily use
- Deployment to Filecoin mainnet + a testnet
- Interesting use of FVM, especially what's unique to Filecoin (for example, via the Filecoin Solidity API, FVM use cases, or Bacalhau x FVM, etc.)

**Comment by lordshashank** [comment]
Ya @eshon , as you could see our aim is to go for user friendly AI as I know good UI could be the difference maker in the field. I didn't added it as we would be improving it throughout the time to achieve a good product by end. Adding it now.
Let me know of any other aspects if any.

**Comment by ErinOCon** [comment]
Hi @lordshashank, this microgrant has been approved! We will send an email to confirm payment details. As mentioned above, the following are required for this microgrant: 

- A fully working user-facing demo with nice UX that anyone can easily use
- Deployment to Filecoin mainnet + a testnet
- Interesting use of FVM, especially what's unique to Filecoin (for example, via the Filecoin Solidity API, FVM use cases, or Bacalhau x FVM, etc.)

Please be in touch with any questions!

**Comment by ErinOCon** [comment]
HI @lordshashank, I hope you are doing well! Do you have any project updates or questions for our team at this time?

**Comment by lordshashank** [comment]
Hey, we have been working on Eastore all this time, we will try to finalize the deliverables within a month. I have been in contact with @eshon and @truckerfling in slack and getting feedback on designs, etc as well. Thank You. From: ErinOConSent: 13 September 2023 20:19To: filecoin-project/devgrantsCc: Shashank Trivedi; MentionSubject: Re: [filecoin-project/devgrants] Next Step Microgrant: EASTORE (Issue #1535) HI @lordshashank, I hope you are doing well! Do you have any project updates or questions for our team at this time?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
