### ISSUE TITLE
Zeeve, No code Infrastructure as a Service for Filecoin

### ISSUE THREAD

**Issue by gnv-zeeve** [filecoin-project/devgrants#1537]
# Open Grant Proposal: No code Filecoin Infrastructure as a Service

**Project Name:** Zeeve, no code Filecoin Dedicated Node and Elastic RPC APIs

**Proposal Category:** `Developer and data tooling`

**Individual or Entity Name:** Organization: Zeeve Inc.

**Proposer:** `ghan@zeeve.io`

**(Optional) Filecoin ecosystem affiliations:** N.A

**(Optional) Technical Sponsor:** N.A

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** No

# Project Summary

The deployment and management of web3 infrastructure is very complex, manually intensive and error-prone putting the Blockchain network and user experience at risk. The lack of expertise, high learning curve and lack of standardization for web3 DevOps is one of the major hindrances to the widespread adoption of a Blockchain protocol.

The project aims to provide a no code approach to setup, deploy and manage filecoin nodes, which will support Lotus as a full featured client for Filecoin network. The platform will further extend the capability to provide elastic RPC endpoints to the filecoin network for developers around the world to build on filecoin without having a need to manually setup nodes.

## Impact

Deploying and managing Filecoin nodes can be a challenging task that requires technical expertise and continuous monitoring. Some of the key pain points include lack of expertise, security and performance optimization, compliance complexities, node management and health monitoring, and API setup delays.

Zeeve's one-click deployment, no-code platform, proactive monitoring, and automated updates, upgrades and patching can help address these concerns. Additionally, Zeeve is compliant with industry standards such as SOC2 Type2, ISO 27001, and GDPR. Overall, Zeeve can reduce setup time, improve security and compliance, and simplify node management and monitoring for Filecoin participants.

## Outcomes

1. Filecoin Validators would be able to deploy Filecoin validator nodes in seconds with military-grade security & high availability.

2. Filecoin Developers can deploy Filecoin full and archive nodes in seconds.

3. Filecoin DApp developers can consume secure RPC endpoints to connect with the Filecoin protocol.

4. Get new developers to join the Filecoin developer community.

## Adoption, Reach, and Growth Strategies

Our audience is Developers building on protocols and web3 applications, potential validators and stackers in a protocol, Computer science students with an interest in web3 based language models and every day ecosystem players for education purpose. We are already running initiatives to onboard and educate, here is how we plan to onboard the first 100 users for Filecoin:

1. We will promote the launch of Filecoin support on the Zeeve platform to all of Zeeve’s user base of 24,000+ users.

2. We are going to launch a marketing campaign that will include a Press Release, How to articles and blogs on Zeeve’s blog and 3rd party sites like Hackernoon, Webinars and Twitter Spaces through Zeeve’s Web3Voice and offline developer meetups through Zeeve’s Web3 Titans initiative and Hackathons through Zeeve’s network on 30+ community DAOs, colleges and developer forums.

### Total Budget Requested $100,000

|Milestone|Description|Deliverables|Completion Date|Funding|
|--|--|--|--|--|
|1|Filecoin Developer RPC APIs| <li><ul>Shared endpoints for https and wss with auth and JWT to choose from</ul></li><li><ul>Frontend integration on Zeeve Platform</ul></li><li><ul>Method wise RPC call metics and monitoring</ul></li><li><ul>Filecoin webpage on Zeeve.io</ul></li> <li><ul>Update Filecoin webpage on Zeeve.io</ul></li> <li><ul>PR, social media outreach, community promotion</ul></li>|31st July 2023| $40,000|
|2|Filecoin Client Nodes| <li><ul>Staking nodes automation</ul></li><li><ul>Zeeve managed cloud deployments</ul></li><li><ul>Frontend integration on Zeeve Platform</ul></li><li><ul>System and node health monitoring, alerts and notifications</ul></li><li><ul>Update Filecoin webpage on Zeeve.io PR, social media outreach, community promotion</ul></li>|31st May 2023| $30,000|  
|3|Filecoin Storage Miner and Retrieval Miner Nodes| <li><ul>Nodes Deployment scripts</ul></li><li><ul>Zeeve managed cloud deployments</ul></li><li><ul>Frontend integration on Zeeve Platform</ul></li><li><ul>System and node health monitoring, alerts and notifications</ul></li><li><ul>Blockchain event webhooks</ul></li><li><ul>Filecoin webpage on Zeeve.io</ul></li><li><ul>PR, social media outreach, community promotion</ul></li>|30th June 2023| $30,000|  

  
## Maintenance and Upgrade Plans

We will maintain and continuously integrate support features, upgrades and patches on Zeeve Platform for Filecoin Nodes & APIs on our own without any additional grant or cost for a long term under the Zeeve Platform LTS for 5 years. Specifically it is not being open-source, that is completely covered by us.

# Team

## Team Members

1. Ghan Vashishtha: CTO

2. Sankalp Sharma: VP Engineering

3. Dr Ravi Chamria: CEO

4. Poonam Kumari: L1 Lead

5. Lakshay Gaur: DevOps Lead

6. Hitesh Sharma: EVMs Lead

7. Nitesh Sharma: Data Engineer

## Team Member LinkedIn Profiles

1. Ghan Vashishtha: https://www.linkedin.com/in/ghan-vashishtha/

2. Sankalp Sharma: https://www.linkedin.com/in/sankalp-sharma-502008139/

3. Dr Ravi Chamria: https://www.linkedin.com/in/rchamria/

4. Poonam Kumari: https://www.linkedin.com/in/poonam-kumari-21043b98/

6. Lakshay Gaur: https://www.linkedin.com/in/lakshay-gaur-2241b4146/

7. Hitesh Sharma: https://www.linkedin.com/in/hiteshsharma6/

8. Nitesh Sharma: https://www.linkedin.com/in/nitesh-sharma-93517a80/

## Team Website

https://www.zeeve.io  

## Relevant Experience

Our team holds a substantial collective experience in major projects in web2 as well as web3, with our founders leading with 15+ years of tech and business experience, proving our competence in building bespoke solutions as per the need for Filecoin:

1. Ghan Vashishtha, CTO - 15+ years with Gov Projects, Defence & Aerospace, Media and Telecom, 5+ years in web3 and Enterprise Blockchain space.

2. Sankalp Sharma, VP Engineering - Blockchain Architect and Engineer with experience of more than 5 years in web3, Smart Contracts and Blockchain DevOps.

3. Dr Ravi Chamria, CEO - Tech Entrepreneur with 6+ years of web3 experience.

4. Poonam Kumari, L1 Lead - C++ and Rust engineer with 12+ years of experience

5. Lakshay Gaur, DevOps Lead - 5+ years of experience with Blockchain DevOps.

6. Hitesh Sharma, EVMs Lead - 4+ years of experience with Solidity smart contracts, full stack engineer and EVMs DevOps.

7. Nitesh Sharma, Data Engineer - 8+ years of experience in Data Analytics, GraphQL and enterprise database systems.

## Team code repositories

https://github.com/Zeeve-App
 
# Additional Information

We have been closely watching Filecoin’s developments for the past few years. We learnt about the grant essentially through Filecoin's website.

Email to connect:
ghan@zeeve.io

**Comment by ErinOCon** [comment]
Hi @gnv-zeeve, thank you for your proposal! We are behind schedule for our April submissions, but expect to have an update available in the next couple weeks. Thank you for your patience!

**Comment by ErinOCon** [comment]
Hi @gnv-zeeve, thank you for your proposal and for your patience with our review. Unfortunately, we will not be proceeding with a grant at this time. Wishing you all the best as you continue to build!
