### ISSUE TITLE
Open Grant Proposal: Infinity Wallet

### ISSUE THREAD

**Issue by InfinityWallet** [filecoin-project/devgrants#1538]
# Open Grant Proposal: `Infinity Wallet`

**Project Name:**
Infinity Wallet

**Proposal Category:** 
Integrations

**Individual or Entity Name:** 
Infinity Wallet

**Proposer:** 
https://github.com/InfinityWallet

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:**
Infinity wallet, while free to use for users and developers, is not open source due to the pitfalls of being open-source for such software.

1. Open sourcing software brings increased security risks to users, by enabling scammers to target users more easily with fake, malicious, phishing versions of Infinity Wallet. This is already a major problem our team deals with daily, from users contacting about fake versions of the Infinity Wallet that don’t even look or operate like the official version. An open source version would simply enable scammers to clone the wallet and make malicious changes, impacting our resources and reputation as well as affected users even more greatly.

2. Open-sourcing all aspects of a product (including the design and user interface elements) makes it very easy for anyone to copy and reap the benefits from our hard work, innovation and time/money freely. It would enable mass cloning as seen with DEXs, browser extension wallets, and other open-source front-end interfaces or software, which plagues the industry with many cloned projects launching with low skilled developers, stifling innovation.

We do however provide open-source access for developers to our libraries and repositories that we develop.

# Project Summary
Infinity Wallet is the first all-in-one non-custodial wallet ecosystem and Web3 browser of its kind on desktop (“a Wallet Super App”). Not a browser extension, but a complete standalone desktop application providing a one-stop solution for seamless access and usability of DeFi, NFTs and cross-border payments, with a gateway to the world of Web3/DApps via the first desktop Web3 browser and Dapp store. Fulfilling all a user's decentralized needs in a single platform, while removing the complexities of decentralized finance and Web3, enabling economic freedom for everyone globally!

Infinity Wallet was created to finally enable mass adoption, as a single access point to the entire decentralized world. We have focused on providing the best possible user experience, to lower the barrier to entry and allow for streamlined and secure adoption of DeFi and Web3. Providing a world-class user experience with a seamless user interface, and a full spectrum of constantly growing in-wallet features and services as a one-stop hub. Making Infinity Wallet the complete solution for all crypto users’ needs, while making adoption and usage of cross-border payments, DeFi, NFTs and Web3 easier than ever before for mainstream adoption.

Infinity Wallet is not just a unique one-stop wallet built for the masses, but it is also the first desktop platform to provide users with access to the entire Web3 and DApp space without needing to leave their wallet, with the first Web3 browser and DApp store on desktop as a standalone App. Finally removing the need to use unintuitive, unfriendly and feature-lacking browser extension wallets ever again! Providing a far superior, safer and more natural user experience, with a range of unique advantages for users, DApps, and chains alike, while enabling easier usage and adoption.

## Impact 
Wallets are one of the most fundamental components required for usage and adoption of DeFi, Web3, crypto payments, a chain and its ecosystem, however they are one of the least well developed applications in the crypto ecosystem.

Today, wallets act mainly as an interface, serving primarily as a transaction signing layer, with very limited functionality or in-wallet features, requiring use of multiple platforms, and are generally lacking in basic UX, while providing very unprofessional, hard to use and aesthetically poor user interfaces, with most platforms built for developers rather than end users. This has been sufficient for the early adopters in crypto, however, for the next billion users to onboard, a more curated, frictionless and high quality user experience is required!

Desktop Web3 wallet options are limited in particular, delivering very little in terms of new innovation, or solving today’s issues, while requiring the user to install a browser extension, which is not the natural flow. Overall delivering an unintuitive and feature-lacking user experience, with limited support for a chain and its ecosystem/DApps, greatly restricting the possibility for discoverability and adoption.

For FileCoin to compete and attract users and developers, it needs a one-stop wallet super app providing a seamless user experience, to enable users to onboard and adopt FileCoin, and discover the FileCoin ecosystem as their home.

As of today the FileCoin ecosystem has very few wallet solutions! The wallet solutions that do exist today are not built for mass adoption or use by less tech savvy users, they are more built with a focus on usage by developers and generally provide low quality user interfaces, lack a curated in-wallet experience, lack many features/services that users require and overall provide a terrible UX.

Infinity Wallet steps in to fill this need, as a one-stop hub for all payment, DeFi, NFT and Web3 activity. Providing a unique all-in-one wallet and Web3 browser solution with a full spectrum of in-platform services, features and protocols, focusing on delivering a premium platform and enhancing the user experience, while providing a user centric interface for a seamless decentralized user experience. Streamlining accessibility and lowering the barrier to entry, to allow for easy onboarding and true adoption of DeFi, crypto payments & Web 3.0 globally.

## Project Metrics
- 46,000 MAU on Desktop;
- $600,000,000+ TVH;
- 100,000+ users subscribed to be notified of mobile release;

Some metrics/evidence of Infinity Wallet’s success:
- Infinity Wallet desktop download activity [Github Release Stats](https://somsubhra.github.io/github-release-stats/?username=infinitywallet&repository=Releases&page=1&per_page=1000)

- Around 110,000 monthly website visits (https://www.similarweb.com/website/infinitywallet.io/)

## Outcomes
The goal of the proposal would be to enhance FileCoin FVM with a much needed one-stop user focused wallet and web3 browser ecosystem, providing FileCoin access to the many advancements we have, bringing much needed valuable infrastructure, services and ecosystem support, which FileCoin currently lacks (for DeFi, Web3, and cross-border payments). While enhancing the user experience and bringing new utility, and allowing for easier usage, access and adoption of FileCoin and its ecosystem by less tech-savvy users, while also empowering developers with easier discoverability and usability of their DApps & Tokens, driving easier adoption.

Infinity Wallet, as a unique first of its kind one-stop wallet and Web3 browser ecosystem on desktop (with unique ux focused mobile release to come), built for the masses and supporting hundreds of thousands of users, can help excel FileCoin by improving the user experience and lowering the barrier to entry. Delivering an all-in-one ecosystem platform that will provide access to multiple unique in-wallet features/services with constant new developments, along with a focus on delivering a high quality and user-centric interface, redefining the DeFi & Web3 user experience and providing users direct access to all their needs in a single platform. Allowing for streamlined adoption and onboarding of FileCoin and its ecosystem, for DeFi, Web3, and cross-border payments.

Additionally, FileCoin currently lacks streamlined Web3 support for connecting and transacting with DApps. As the FIRST desktop Web3 browser and DApp store, we bring a unique more natural user experience and value to any chain integrated when accessing DApps and Web3 (compared with browser-extensions), finally freeing desktop users from having to use unintuitive, unfriendly and feature-lacking browser extension wallets to access Web3 and DApps, while enabling easier DApp/developer discoverability!

Below are some of the key infrastructure and features/services that could benefit and bring value to FileCoin FVM and its ecosystem:

* Portfolio and Analytics Monitoring/Dashboard - **![portfolio management|690x360](https://i.gyazo.com/8668526d0473f9fd30e6ac1bdf28a4e8.png)**

* One-stop DeFi Wallet Solution with a strong focus on user experience - **![wallet management|690x360](https://i.gyazo.com/da6349af8e2e16ab2d5e6ad152bd5ef7.png)**

**![wallet send|690x360](https://i.gyazo.com/7ded287eb401ee9d6933a83a4b1b7ecc.jpg)**

* First desktop Web3 Browser (One-click connect and transact with Web3 DApps, with utmost discoverability and use of a chains’ ecosystem) This removes the need for unfriendly and feature-lacking browser extensions to access Web3 and decentralized applications on desktop - **![web3 browser|690x360](https://i.gyazo.com/531ffe2563c4ea7b37d80e33dcfb2ee5.png)**

* Web3 DApp Store (Enables easier DApp & ecosystem discoverability, adoption and usage) - 
**![web3 dapp store|690x360](https://i.gyazo.com/f7c7bb506bafa0c770ebae251408c9fa.png)**

* Cross-chain swap & bridge (Swap/Bridge between multiple supported chains) - **![swap & bridge|690x360](https://i.gyazo.com/d14dd13a96adabebb5466a5e8ed80d9f.png)**

* In-wallet decentralized exchange aggregator - **![dex aggregator|690x360](https://i.gyazo.com/7594a5313e85339b3779debe77b81545.png)**

* NFT support and Gallery to manage (view, send and receive) and easily trade NFTs - **![nft wallet|690x360](https://i.gyazo.com/2aeba586199fe74c2e82544383a56331.png)**

**![nft individual|690x360](https://i.gyazo.com/e675a10ce96331c01d256cf347764c1f.jpg)**

* Fiat on/off-ramp (enabling easy and direct onboarding into crypto and supported chains) - **![buy and sell crypto|690x360](https://i.gyazo.com/ab1f2770fc8dc4182c0a6ee76798ab2b.png)**

* Complete Transaction History for all transaction types with DApp linking and balance/performance tracking - **![advanced transaction history|690x360](https://i.gyazo.com/a30215224b45a5a8eea6aee5a7bef6b1.png)**

* Custom Token Importing (Allowing any token to be imported on any supported chain) - **![custom token importing|690x360](https://i.gyazo.com/7233b8795e1786b00f537f6fca95a116.png)**

* Live user and chain support, with a focus on delivering the best possible user experience to make onboarding for users as easy and seamless as possible

## Adoption, Reach, and Growth Strategies
Our target audience are primarily retail users (for wallet, payments, accessing DeFi, NFTs and Web3/DApps), along with a secondary focus on developers and driving further awareness, adoption and easier usage of their project (DApps, Tokens and NFTs).

**If applicable, how do you intend to onboard new users? If you are just starting to interact with your target audience, how will you onboard your first 10 users? Your first 100?**

Infinity Wallet is an already live platform supporting hundreds of thousands of users and has over 46k MAU during the current market. All adoption and growth of the Infinity Wallet up to now has been mainly from organic growth (partnerships and word of mouth) due to the inherent issues we solve, as well as the value and unique premium experience we provide users, projects and chains within the space, as we continue to redefine the wallet, DeFi and Web3 experience.

## Development Roadmap

We would operate via a single milestone, which would be the completion of all deliverables and live launch of FileCoin developments and integration. This expedites the process and allows us to focus on fully completing, before receiving any payment.

While we operate via a single milestone, you can find our internal milestones/deliverables below to give a deeper insight:

| Deliverable | Description | Deliverables |
| -----: | ----------- | ------------- |
| 1. | Develop out FileCoin chain core functionalities | - FileCoin FVM chain integration/support in wallet;<br/>- FileCoin core functionalities (balance tracking, send, receive, create/restore wallet and etc);<br/>-  Smart contract resolving for protocols & transactions;<br/>- Complete FileCoin  transaction history with advanced information;<br/>- Integrate/develop portfolio & analytics management for FileCoin; |
| 2. | Custom token Importing and support of top tokens | - Ability to import and custom manage any non-default integrated token;<br/>- Develop out support for FileCoin tokens across Infinity Wallet (send, receive, balance, transaction history, DApps and etc) and available Infinity Wallet features;<br/>- Support top tokens with default integrations for instant use; |
| 3. | Web3 browser | - Desktop Web3 Browser to allow for seamless transacting (signing and approving) and one-click connecting/management (manage DApp connecting), removing the need for browser extensions;<br/>- Web3/DApp Store to allow for easy discoverability and adoption of FileCoin ecosystem projects; |
| 4. | Implement FileCoin into remaining features/services and secondary features. | - Cross-chain swap/bridge support for Filecoin (Allowing users to directly onboard to Filecoin from different chains “BTC, ETH, BSC and etc” within a single click);<br/>- Contact/Address book;<br/>- Payment requests;<br/>- Desktop drag and drop QR scan;<br/>- Live Market stats;<br/>- Price Alerts;<br/>- WalletConnect;<br/>- Etc.. |
| 5. | Internal testing | Internal testing and auditing of the developments, infrastructure and integrations |
| 6. | Release of the FileCoin FVM integration & developments | - Release on Windows, MacOS and Linux with the FileCoin integrations & developments;<br/>- Support FileCoin as a native chain;<br/>- We will announce across all social channels and in-wallet;<br/>- We will create a custom FileCoin web page on the website;<br/>- Provide on-going support to the FileCoin ecosystem of DApps/Projects with direct integration into the Infinity Wallet for free (waiving our usual fee) to drive increased FileCoin ecosystem adoption and discoverability;|

## Total Budget Requested

Budget = $30,000

## Maintenance and Upgrade Plans

**Specify your team's long-term plans to maintain this project and improve it over time.**
On completion of the proposed deliverables and integration of FileCoin we will provide ongoing maintenance support for FileCoin chain as well as development support with integration into future available features/services on a case by case basis, along with integration into our unique user focused mobile launch.

As a project we have a lot of goals we look to accomplish and developments planned over the next couple of years, some of these can be found on our roadmap on page 27, here: https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf 

# Team

## Team Members
Information on the core team members can be found at the following link: https://docs.google.com/document/d/1c4fpyzI64569uNr8l9Ygo_G3x2NTs_Dq8wRGSnOXH14/edit?usp=sharing 

## Team Website
[infinitywallet.io](https://infinitywallet.io/)

## Relevant Experience
Our team is made up from individuals that have extensive experience in the space, with a complete crypto experience from Smart Contracts, DeFi/Web3 projects, DApp development, Wallet and more. Our team has a general background in software development and UI/UX.

Additionally, our team members have between 5-10 years of experience within the space (as investors, miners and developers), so we have a vast amount of experience and understanding of major shortcomings in the market, along with what is needed to enable mass adoption.

# Additional Information
**How did you learn about the Open Grants Program?**
Our support team has received requests from users reaching out regarding integrating support for Filecoin, so we looked to see if there was a grant program to be able to accomplish the integration.

**Please provide the best email address for discussing the grant agreement and general next steps**
aron@infinitywallet.io

**Comment by InfinityWallet** [comment]
Hello @realChainLife, I am following up as we have not heard back and were wondering if there was any update on the proposal?

**Comment by ErinOCon** [comment]
Hi @InfinityWallet, thank you for your proposal! We are behind schedule for our April submissions, but expect to have an update available in the next couple weeks. Thank you for your patience!

**Comment by InfinityWallet** [comment]
> Hi @InfinityWallet, thank you for your proposal! We are behind schedule for our April submissions, but expect to have an update available in the next couple weeks. Thank you for your patience!

Hi @ErinOCon, no worries. If there are any questions just let us know and we look forward to hearing back soon. Thanks

**Comment by ErinOCon** [comment]
Hi @InfinityWallet, thank you again for all of your patience. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!

**Comment by InfinityWallet** [comment]
> Hi @InfinityWallet, thank you again for all of your patience. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!

Hello @ErinOCon, appreciate getting back. It would be great to know if there is any specific reason? That way we can see if we can make any changes or answer any possible misunderstandings.

We have seen a fair demand for FileCoin in the Infinity Wallet, Web3 browser and our ecosystem of services, as a unique platform in the space that is actively solving many of today's issues for users. This is something that Filecoin greatly lacks and is needed if it is to grow and enable users to seamlessly onboard, use and discover Filecoin and its ecosystem as their home.

**Comment by InfinityWallet** [comment]
> > Hi @InfinityWallet, thank you again for all of your patience. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
> 
> Hello @ErinOCon, appreciate getting back. It would be great to know if there is any specific reason? That way we can see if we can make any changes or answer any possible misunderstandings.
> 
> We have seen a fair demand for FileCoin in the Infinity Wallet, Web3 browser and our ecosystem of services, as a unique platform in the space that is actively solving many of today's issues for users. This is something that Filecoin greatly lacks and is needed if it is to grow and enable users to seamlessly onboard, use and discover Filecoin and its ecosystem as their home.

Hello @ErinOCon and @realChainLife, we are following up in-regards to the previous comment. Thanks

**Comment by ErinOCon** [comment]
Hi @InfinityWallet, our team will follow up with more information shortly.

**Comment by ErinOCon** [comment]
Hi @InfinityWallet, thank you for your patience. Below are a couple points from our review that you may find helpful: 
- Our devgrants program is generally intended to support open source projects (see policy [here](https://github.com/filecoin-project/devgrants/blob/master/open-source-policy.md)). More details as to why it cannot be open source would have been helpful.
- Details regarding security concerns and security features on the wallet not provided. These are key review points when reviewing wallet projects.

**Comment by InfinityWallet** [comment]
> Hi @InfinityWallet, thank you for your patience. Below are a couple points from our review that you may find helpful:
> 
> * Our devgrants program is generally intended to support open source projects (see policy [here](https://github.com/filecoin-project/devgrants/blob/master/open-source-policy.md)). More details as to why it cannot be open source would have been helpful.
> * Details regarding security concerns and security features on the wallet not provided. These are key review points when reviewing wallet projects.

Hello @ErinOCon,

In-regards to the reasons for not fully open-sourcing the platform this was answered in the proposal here (https://github.com/filecoin-project/devgrants/issues/1538), which explains the serious issues open-sourcing brings to users, cloning, devaluing of the project, and the additional costs that doing so would bring to us as a free to use project. However, we do open-source certain things such as smart contracts, dependencies and libraries we create, for use by other developers.

In your grant policy it mentions "we award funding in the Integration and adoption category to applications seeking to add IPFS, Filecoin, or libp2p support to an existing, closed-source software project", which as an already existing project with years in the space and significant traction in the industry, with over 48,000 MAU, I would think we would fall under this category.

Regarding security concerns and security features, as a fully decentralized and non-custodial wallet the user is in full control of their wallet, funds and data. This removes the vast majority of security risks, in comparison with centralized platforms. As for wallet security, the user's private keys are only held locally on the user's own device, while being encrypted, with the option to add D2FA to each individual wallet to add an extra layer of encryption and security. In addition we are looking into enabling users the option to encrypt their wallet with a U2F key, which would then require a U2F hardware device to unlock their wallet for maximum security, providing nearly the same degree of security as a hardware wallet.

In addition to providing the highest level of security for users' private keys, we also provide users that access the Web3 browser with phishing and scam protection, by blacklisting known scam and malicious apps/smart contracts to warn users of potential scams and increase user protection.

Overall our team takes security very seriously at all levels. We internally audit each release and maintain strict internal policies to ensure user and app security at all time.

Do we need to re-apply with a new proposal containing this information? Or is it fine in the comments here?

Thanks

**Comment by InfinityWallet** [comment]
Hello @ErinOCon, following up as its been awhile since we heard back in-regards to the previous message. Thanks
