### ISSUE TITLE
Next Step Microgrant：Sunshine NFT market

### ISSUE THREAD

**Issue by yuorowi** [filecoin-project/devgrants#1539]
1. What is your project, and what problem does it solve? (max 100 words)

Sunshine NFT Market is a decentralized platform that allows anyone to upload images to create NFTs. Our platform enables you to mint your own ERC-721 NFTs and earn revenue by selling them on our platform. We seek to partner with other platforms to integrate and share resources, and to establish an NFT market and AI resource sharing pool. We plan to expand our user base by collaborating with more NFT markets and AI generation tools. Our smart contract is deployed on the Filecoin Calibration Testnet, and our NFTs are stored on IPFS. We aim to use FVM for deployment on the Filecoin network for automation of minting, revenue and governance functions.

2. Project links
  
Link to Github repo:  https://github.com/yuorowi/SUNSHINE
Link to demo or website:  https://sunshine-nft-market.vercel.app/
smart contract: https://github.com/yuorowi/SUNSHINE/blob/main/src/contracts/Auction.sol
License:  MIT

  
 3. a) How is IPFS, Filecoin, or related technology used in this project?

Sunshine NFT Market uses smart contracts written in Solidity. Each uploaded image generates a unique NFT (Auction.sol) that is stored on IPFS and can be purchased, minted, or sold on our marketplace supported by Auction.sol. We deploy on the industry-leading Hardhat infrastructure to ensure high performance and seamless execution.
We store our data on Filecoin for maximum security and decentralization. Our smart contracts are deployed on the Filecoin Calibration Testnet.

    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)

  Yes, the project is building with the current microgrants focus area, the Filecoin Virtual Machine (FVM) initiative.

 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

1.MVP Release: We will develop and release the Minimum Viable Product (MVP) version of the Sunshine NFT market, which will include basic NFT creation, storage, and trading functions. This will involve integrating Solidity smart contracts, IPFS, and Filecoin to ensure efficient, secure, and decentralized NFT creation and trading. ( It is expected to take 1-2 months to complete.)

2.Continuous Iterative Improvement of MVP: After launch, we will collect user feedback, iterate the platform, and continuously improve its functionality, user interface, and overall performance based on user needs and feedback. This may involve updates, bug fixes, and feature enhancements to ensure a seamless experience for users. (3 months, and this will be an ongoing process.)

3.Community Engagement Activities: We will conduct targeted community engagement activities to encourage users to provide feedback, actively participate in activities, and share their experiences. This may include social media activities, community events, and other initiatives aimed at promoting community involvement and gathering valuable insights from users. (It is expected to take 2-3 months to complete.)

4.Establish a Community Engagement Plan: We will launch community engagement activities, including social media activities, online activities, and offline activities, to attract more users and developers to participate in the construction and development of the Sunshine NFT market. We will also actively respond to user feedback and incorporate their ideas and suggestions into our development plans to better meet their needs and expectations. (It is expected to take 2-3 months to complete.)

5.Publish White Papers, Documents, and Shared Resources: Including user manuals, development logs, etc., to provide transparency to the community and share our progress, challenges, and lessons learned. These resources will help users better understand and use the Sunshine NFT market and also attract more developers and contributors to join our community.( It is expected to take 2-3 months to complete.)

6.Establish an AI resource sharing pool that allows people to share their AI models and resources with those who need them to increase the speed and efficiency of AI development. Such a resource sharing platform allows people to quickly find the AI models and resources they need, avoiding the problem of duplicated development and wasted resources.

In addition, it is also necessary to establish an NFT market sharing pool. The NFT market is becoming more and more popular, but many people may not know how to get started due to the complexity of NFT trading and management. Establishing an NFT market sharing pool can make it easier for people to enter the NFT market, purchase and trade NFTs of interest to them. (3 months, and this will be an ongoing process.)

5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes, if our project is accepted, we agree to share monthly updates on this Github issue for a period of 3 months or until the project described here is completed. The updates will include progress or outcomes of our microgrant-funded work, any Filecoin technical or usage guidance requests, and descriptions of our experiences on Filecoin, including any challenges or shortcomings encountered. We are committed to providing regular updates to keep the community informed of our progress and seek support or guidance as needed during the development process.

6. Does your proposal comply with our Community Code of Conduct?

Yes, our proposal complies with the Filecoin Community Code of Conduct. We have reviewed and understood the Code of Conduct and our project and team will adhere to the principles and guidelines outlined in it. We are committed to maintaining a respectful and inclusive environment throughout the entire project development process and will ensure that all interactions and communications align with the values and expectations set forth by the Filecoin community.

 7. Links and submissions

If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Additional questions:

For each team member(s), please list name, email, Github account, and role in the project.

Gerald , yuorowi@gmail.com , Co-founder, CTO
	
Hector , hoqthy@gmail.com , Co-founder,Project Manager,Blockchain Developer

Lennon , everfow62@gmail.com , Front-end Developer

Zonghan Chen , julyhuhu0001@gmail.com , Back-end Developer

Yuchen Chou , powgem030@gmail.com , AI Developer：AI resource sharing pool and NFT market sharing pool

How did you learn about our microgrant program?

I saw the "Next Step Microgrant" plan on Github from the community and hope to have the opportunity to implement it!

If your project was created as part of an event or hackathon:
What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
No

Please link to your hackathon submission
No

**Comment by yuorowi** [comment]
> 1. What is your project, and what problem does it solve? (max 100 words)
> 
> Sunshine NFT Market is a decentralized platform that allows anyone to upload images to create NFTs. Our platform enables you to mint your own ERC-721 NFTs and earn revenue by selling them on our platform. We seek to partner with other platforms to integrate and share resources, and to establish an NFT market and AI resource sharing pool. We plan to expand our user base by collaborating with more NFT markets and AI generation tools. Our smart contract is deployed on the Filecoin Hyperspace testnet, and our NFTs are stored on IPFS. We aim to use FVM for deployment on the Filecoin network for automation of minting, revenue and governance functions.
> 
> 2. Project links
> 
> Link to Github repo: https://github.com/yuorowi/SUNSHINE Link to demo or website: https://sunshine-nft-market.vercel.app/ License: MIT
> 
> 3. a) How is IPFS, Filecoin, or related technology used in this project?
> 
> Sunshine NFT Market uses smart contracts written in Solidity. Each uploaded image generates a unique NFT (Auction.sol) that is stored on IPFS and can be purchased, minted, or sold on our marketplace supported by Auction.sol. We deploy on the industry-leading Hardhat infrastructure to ensure high performance and seamless execution. We store our data on Filecoin for maximum security and decentralization. Our smart contracts are deployed on the Filecoin Hyperspace testnet.
> 
> ```
> b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
> ```
> 
> Yes, the project is building with the current microgrants focus area, the Filecoin Virtual Machine (FVM) initiative.
> 
> 4. How will you improve your project with this grant? What steps will you take to meet this objective?
> 
> 1.MVP Release: We will develop and release the Minimum Viable Product (MVP) version of the Sunshine NFT market, which will include basic NFT creation, storage, and trading functions. This will involve integrating Solidity smart contracts, IPFS, and Filecoin to ensure efficient, secure, and decentralized NFT creation and trading. ( It is expected to take 1-2 months to complete.)
> 
> 2.Continuous Iterative Improvement of MVP: After launch, we will collect user feedback, iterate the platform, and continuously improve its functionality, user interface, and overall performance based on user needs and feedback. This may involve updates, bug fixes, and feature enhancements to ensure a seamless experience for users. (3 months, and this will be an ongoing process.)
> 
> 3.Community Engagement Activities: We will conduct targeted community engagement activities to encourage users to provide feedback, actively participate in activities, and share their experiences. This may include social media activities, community events, and other initiatives aimed at promoting community involvement and gathering valuable insights from users. (It is expected to take 2-3 months to complete.)
> 
> 4.Establish a Community Engagement Plan: We will launch community engagement activities, including social media activities, online activities, and offline activities, to attract more users and developers to participate in the construction and development of the Sunshine NFT market. We will also actively respond to user feedback and incorporate their ideas and suggestions into our development plans to better meet their needs and expectations. (It is expected to take 2-3 months to complete.)
> 
> 5.Publish White Papers, Documents, and Shared Resources: Including user manuals, development logs, etc., to provide transparency to the community and share our progress, challenges, and lessons learned. These resources will help users better understand and use the Sunshine NFT market and also attract more developers and contributors to join our community.( It is expected to take 2-3 months to complete.)
> 
> 6.Establish an AI resource sharing pool that allows people to share their AI models and resources with those who need them to increase the speed and efficiency of AI development. Such a resource sharing platform allows people to quickly find the AI models and resources they need, avoiding the problem of duplicated development and wasted resources.
> 
> In addition, it is also necessary to establish an NFT market sharing pool. The NFT market is becoming more and more popular, but many people may not know how to get started due to the complexity of NFT trading and management. Establishing an NFT market sharing pool can make it easier for people to enter the NFT market, purchase and trade NFTs of interest to them. (3 months, and this will be an ongoing process.)
> 
> 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
> 
> Yes, if our project is accepted, we agree to share monthly updates on this Github issue for a period of 3 months or until the project described here is completed. The updates will include progress or outcomes of our microgrant-funded work, any Filecoin technical or usage guidance requests, and descriptions of our experiences on Filecoin, including any challenges or shortcomings encountered. We are committed to providing regular updates to keep the community informed of our progress and seek support or guidance as needed during the development process.
> 
> 6. Does your proposal comply with our Community Code of Conduct?
> 
> Yes, our proposal complies with the Filecoin Community Code of Conduct. We have reviewed and understood the Code of Conduct and our project and team will adhere to the principles and guidelines outlined in it. We are committed to maintaining a respectful and inclusive environment throughout the entire project development process and will ensure that all interactions and communications align with the values and expectations set forth by the Filecoin community.
> 
> 7. Links and submissions
> 
> If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: Additional questions:
> 
> For each team member(s), please list name, email, Github account, and role in the project.
> 
> Gerald , [yuorowi@gmail.com](mailto:yuorowi@gmail.com) , Co-founder, CTO
> 
> Hector , [hoqthy@gmail.com](mailto:hoqthy@gmail.com) , Co-founder,Project Manager,Blockchain Developer
> 
> Lennon , [everfow62@gmail.com](mailto:everfow62@gmail.com) , Front-end Developer
> 
> Zonghan Chen , [julyhuhu0001@gmail.com](mailto:julyhuhu0001@gmail.com) , Back-end Developer
> 
> Yuchen Chou , [powgem030@gmail.com](mailto:powgem030@gmail.com) , AI Developer：AI resource sharing pool and NFT market sharing pool
> 
> How did you learn about our microgrant program?
> 
> I saw the "Next Step Microgrant" plan on Github from the community and hope to have the opportunity to implement it!
> 
> If your project was created as part of an event or hackathon: What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
> 
> Please link to your hackathon submission

Good Morning, If there is any additional information I can provide, please feel free to contact me
Thank you!

**Comment by ErinOCon** [comment]
Hi @yuorowi,  thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
