### ISSUE TITLE
Next Step Microgrant: STC-GlobalAPIMarket

### ISSUE THREAD

**Issue by Jchicode** [filecoin-project/devgrants#1540]
### 1. What is your project, and what problem does it solve? (max 100 words)

STC-GlobalAPIMarket is an open API market based on blockchain technology, aiming to provide developers with a safe, transparent and efficient platform for buying and selling Web2/Web3 API services, providing decentralized global cloud operation environment, service operation governance environment, and trusted function computing scheduling environment.

### 2. Project links
  
Link to Github repo: https://github.com/stc-community/GlobalAPIMarket
Link to demo or website: https://stc.netlinks.world/
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

In the Github repo is our front-end project, and the smart contract is in the contract directory. We build our two contracts based on FVM.

STCMarket.sol: API market creation and storage, storage of user information
STCMarketToken.sol: token token generation, service provider's pledge, orders in the API Market.

We use web3.storage and IPFS services for file storage. The contract will be deployed on the Filecoin main network.
###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |                         |  Api call and billing function                           |      3 weeks      | 
| 2.     |                         | Improve Api service provider experience and user experience        |       3 weeks      | 
| 3.     |                         |  Contract optimization and deployment to the Filecoin mainnet   |   3 weeks          | 
| 4.     |                         | Onboard unique providers and users on our platform  |      3 weeks        | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

  Yes
### 6. Does your proposal comply with our Community Code of Conduct?

Yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://ethglobal.com/showcase/stc-globaldevdao-utow4
  We joined the Impact Evaluator and also joined the fvm-mainnet-cohort.
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  * Qiang Cheng, qianggeek@gmail.com, https://github.com/Jchicode, Founder and fullstack developer.
* How did you learn about our microgrant program?
  * From the fvm-mainnet-cohort and the Impact Evaluator.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)Scaling Ethereum 2023
  * Please link to your hackathon submission
      https://ethglobal.com/showcase/stc-globaldevdao-utow4

**Comment by ErinOCon** [comment]
HI @Jchicode, thank you for your proposal and for your patience with our review process. This is an interesting project and was considered for a number of our microgrant cycles. Unfortunately, we will not be moving forward with a grant at this time.

Please feel welcome to contact our team at [grants@fil.org](mailto:grants@fil.org) with any questions. Wishing you the best as you continue to build!
