### ISSUE TITLE
Moonshot Web3 Hackathon Proposal

### ISSUE THREAD

**Issue by Bingqi-Wang** [filecoin-project/devgrants#1542]
# Open Grant Proposal: `Project Title`

**Project Name:**
Moonshot Commons

**Proposal Category:** Choose one of `Developer and data tooling`, `Applications`, `Integrations`, `Research & protocols`, `Other`. Learn what these categories are here: https://github.com/filecoin-project/devgrants/tree/master/open-grants#readme
Developer and data tooling

**Individual or Entity Name:** Is the proposal on behalf of an individual, or an entity/organization? Please note that the agreement and any payments must be completed by the same entity, either individual or organization.
Moonshot Commons

**Proposer:** `replace with your GitHub username`
Bingqi-Wang

**(Optional) Filecoin ecosystem affiliations:** `Please disclose any existing work relationships with organizations in the Protocol Labs Network, including Protocol Labs, Filecoin Foundation, Filecoin Foundation for the Decentralized Web, and any others.` 
N/A

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`
N/A

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Please respond with "Yes" or "No".
Yes

# Project Summary

Moonshot Commons is a vibrant, Gen-Z Web3 builder community dedicated to fostering innovation in the blockchain and Web3 domain. We host biannual month-long Web3 hackathons, in December and June, to support and encourage creators in developing new Web3 ideas. Our community has over 1,000 members globally, and we have successfully assisted more than 40 founders in transforming their ideas into venture-backed projects. By partnering with top-tier VCs and industry-leading founders, we aim to provide a robust platform for the development and launch of groundbreaking Web3 projects.

By hosting hackathons, possibly with specific tracks dedicated to Filecoin, we can create opportunities for these builders to develop and showcase their ideas, thus increasing the number of quality projects being built on your ecosystem. This, in turn, will drive growth and adoption of your blockchain, while fostering a thriving developer community that actively contributes to the ecosystem's success.

## Impact 

Moonshot has a proven track record of attracting top tier engineers to start meaningful projects. We have a founders community of over 1000 builders and a wide connection among Asia Web3 buidlers. We also has extensive partnerships with China’s top tier investors and media, which can help raise awareness of Filecoin’s capabilities to Chinese developer communities. For instance, we closely partner with Sunny Gao, the Founder and CEO of China’s #1 venture-backed Developer Community, SegmentFault. Through Moonshot’s network of talented and innovative young builders and various resources to empower their ideas, we believe our hackathons will bring quality projects to the Filecoin Ecosystem.

## Outcomes

1. Venture Partner Recruiting Stage (April 20th - May 15th, No Expense)
2. Promoting Stage (May 1st - May 30th, $5,000 USD)
3. Candidate Selection Stage (June 1st - June 30th , No Expense):
4. Fellowship Stage (July 1st - August 5th, $3,000 USD) :
5. Apollo Day Stage (August 5th and Beyond, $2,000 USD):

1. Venture Partner Recruiting Stage (April 20th - May 15th, No Expense)
2. Promoting Stage (May 1st - May 30th, $5,000 USD)
3. Candidate Selection Stage (June 1st - June 30th , No Expense):
4. Fellowship Stage (July 1st - August 5th, $3,000 USD) :
5. Apollo Day Stage (August 5th and Beyond, $2,000 USD):

## Adoption, Reach, and Growth Strategies

We have already over 1000 founders in our community and over 8000 members. We plan to continue hosting hackathons and fireside chat events in the future to grow the community and keep it active. 

## Development Roadmap

1) Venture Partner Recruiting Stage (April 20th - May 15th, No Expense)

- Finalize the hosting partners and investments from funds and the collaboration approach
- Finalize the mentors and judges and the collaboration approach
- Finalize the Moonshot organizing team and match our resources

2) Promoting Stage (May 1st - May 30th, $5,000 USD)
- working with Crypto medias to post PR articles

- Host 4 to 6 "Moonshot Mafia" (panel discussion with accomplished entrepreneurs)
- Post 8 interviews with founders from previous Moonshot demo days on Moonshot WeChat official account
- Reach 20,000 traffic on the WeChat official account
- Cooperate with 20+ promoting partners

3) Candidate Selection Stage (June 1st - June 30th , No Expense):

- Interview with the candidates
- Send invites to all Venture Capitals and investment teams

4) Fellowship Stage (July 1st - August 5th, $3,000 USD) :

- Explain the judging rubrics and detailed procedures to all participants
- Expand the Apollo Day exploration group to to 200 investors and media reporters

5) Apollo Day Stage (August 5th and Beyond, $2,000 USD):

- Expand the Apollo Day exploration group to 1500
- Confirm the participation of 150 VC partners

## Total Budget Requested

| Milestone # | Description | Deliverables | Completion Date | Funding |
1) Venture Partner Recruiting Stage (April 20th - May 15th, No Expense)

- Finalize the hosting partners and investments from funds and the collaboration approach
- Finalize the mentors and judges and the collaboration approach
- Finalize the Moonshot organizing team and match our resources

2) Promoting Stage (May 1st - May 30th, $5,000 USD)
- working with Crypto medias to post PR articles

- Host 4 to 6 "Moonshot Mafia" (panel discussion with accomplished entrepreneurs)
- Post 8 interviews with founders from previous Moonshot demo days on Moonshot WeChat official account
- Reach 20,000 traffic on the WeChat official account
- Cooperate with 20+ promoting partners

3) Candidate Selection Stage (June 1st - June 30th , No Expense):

- Interview with the candidates
- Send invites to all Venture Capitals and investment teams

4) Fellowship Stage (July 1st - August 5th, $3,000 USD) :

- Explain the judging rubrics and detailed procedures to all participants
- Expand the Apollo Day exploration group to to 200 investors and media reporters

5) Apollo Day Stage (August 5th and Beyond, $2,000 USD):

- Expand the Apollo Day exploration group to 1500
- Confirm the participation of 150 VC partners

## Maintenance and Upgrade Plans

We plan to host hackathons two times a year in the future, and keep growing our buidlers community. 

# Team

## Team Members

Kevin - CEO

Vassar College CS & Education Major

Founder of Moonshot Commons & HackQuest

Ex-Education Researcher@ Beijing Normal University，developed the first teaching competency framework in China

Junxi - CTO

Cornell University CS Major

Carnegie Mellon University CS PhD Candidate

Co-Founder@ Moonshot Commons & HackQuest

Research area focus on game theory, mechanism design, and blockchain MEV

Ex-Meta Software Engineer

Harry - CMO

Emory University

Business & Data Science Majors

Consultant at GEP，

Consulted for 10+ Fortune 500 companies and venture-backed startups on GTM, product launch and distribution, marketing strategy, etc.

Haomiao - CTO

Cornell University CS Major

Cornell University CS Master

Ex-Software Engineer at Meta

Optimized FB ads delivery flow

Contributed 13.5% revenue gain to FB Reels

Contributed 3% revenue gain to FB Story.

Cameron - COO

University of Chicago CS & Game Design Majors

Co-Founder of Moonshot Commons & HackQuest

Organized seven Web3 hackathons, with more than 2000 hackers registered

Ex-CEO @ PeerInsight Education

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/kevin-l-2a7128193/

https://www.linkedin.com/in/junxi-song-218721153/

https://www.linkedin.com/in/harryzhangprofile/

https://www.linkedin.com/in/haomiao-liu-14127417a/

https://www.linkedin.com/in/bingqiwang/

## Team Website

Our winter hackathon website:
(https://moonshothacker.com/)

Our official website:
(http://moonshotcommons.com/)

Our Medium:
(https://medium.com/@moonshotcommons)

Our Twitter:
(https://twitter.com/buildmoonshot)

Our previous media coverage:
(https://cointelegraph.com/press-releases/gen-z-web3-builder-community-moonshot-commons-launches-winter-hackathon)

## Relevant Experience

Our team possesses the ideal combination of experience, trust, and a proven track record, making us the right people to build and nurture the Moonshot Commons ecosystem. Before embarking on the Moonshot journey, we co-founded an online education platform called Peer Insight Education, which focused on teaching standardized tests. From 2017 to 2021, we successfully ran the company together and eventually sold it to Vision Education.

This prior experience of working together as a team has enabled us to develop a strong foundation of trust and collaboration. We understand each other's strengths and weaknesses, and know how to leverage our collective skills to achieve success. This established synergy gives us an edge over the competition, as our team is well-equipped to handle the challenges and opportunities that come with nurturing and supporting the Gen-Z Web3 founders community through Moonshot Commons and our hackathons.

## Team code repositories

# Additional Information

Through Filecoin Website

cameron@moonshotcommons.com

We have successfully organized 8 hackathons so far. In last year solely, we organized two Moonshot Web3 Hackathons, one in summer and the other in winter. During the Summer Hackathon, we interviewed 523 teams, invited 45 to participate, and saw 25 of them demo their products. Of these, 70% received seed funding from top venture capital firms. In the Winter Hackathon, we received 221 applications, invited 52 teams, and 22 of them participated in the final Demo Day, pitching their products to more than 100 VCs.

**Comment by ErinOCon** [comment]
Hi @Bingqi-Wang, thank you for your proposal! We are behind schedule for our April submissions, but expect to have an update available in the next couple weeks. Thank you for your patience!

**Comment by ErinOCon** [comment]
Hi @Bingqi-Wang, thank you again for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
