### ISSUE TITLE
Developer Toolkit and Middleware for Filecoin

### ISSUE THREAD

**Issue by Alvis1998** [filecoin-project/devgrants#1543]
# Open Grant Proposal: `Developer Toolkit and Middleware for Filecoin`

**Project Name: **`Hamster`

**Proposal Category:** `Developer and data tooling` 

**Individual or Entity Name:**`Hamster LTD.`

**Proposer:** `lt-liam`

**(Optional) Technical Sponsor:** `Jenks Guo`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Summary
There are many programming languages being used in the current blockchain world , such as Solidity, Move, Func, JavaScript, Rust, and Cario. Each developer has to choose different public chains and languages for their development and master deeper knowledge which raises the technical threshold.

Other than this, we still lack automated tools, and the degree of systematization and automation in the product development process is inadequate. In addition, project dependencies on manual configuration lead to high error rates and costs.
Based on the above situation, we have developed the Hamster product.

Hamster (hamsternet.io) is the one - stop toolkit and middleware platform for Web3 developers. It enables developers/teams to achieve cost-effective and automatic development as well as O&M processes, including contract template, code/contract check, deployment, node service, CI/CD and more. With Hamster, projects in Web3.0 are empowered to improve their coding and delivery speed, quality and efficiency, as well as product reliability & safety.

Our goal is to make the development, delivery, and operation of Filecoin ecosystem Web3.0 projects more efficient and automated by providing the following deliverables:
1, Hamster provides a fully-featured developer platform where developers can log in using their GitHub account and use Hamster services.
2, The main features of Hamster include:
Template market: providing smart contract templates for filecoin mainstream business scenarios.
Project creation: allowing users to select a template and create it directly in their GitHub repository.
Pipeline setup: automatically creating contract checking pipelines, contract build pipelines, and contract deployment pipelines after creating a dApp project.
Contract operation: providing an interface for operating contracts deployed via the Hamster platform.
Contract monitoring: monitoring and alerting for data on already deployed contracts.

## Impact

The value of Hamster to Filecoin, IPFS, or related ecosystems lies in its provision of a more efficient and reliable way to build, deploy, and run smart contracts. By providing a one-stop infrastructure, development toolkit, and framework, Hamster can greatly simplify developers' workflows, enabling them to create, test, deploy, and maintain smart contracts more easily. This can not only improve development efficiency but also reduce the possibility of errors, thereby lowering costs and increasing reliability.
In addressing these pain points, Hamster offers many features, including integration with popular contract templates on the market, code building and deployment tools, contract quality and security checks, and more. These features can help developers avoid some common errors when writing smart contracts, such as security vulnerabilities, inefficient code, and contract quality issues. At the same time, Hamster also offers the functionality of customizing work pipelines, enabling developers to adjust and optimize according to their own needs, better meeting the needs of different application scenarios.

The benefits of achieving this are obvious. By using Hamster, developers can build and deploy smart contracts more quickly while maintaining high quality and security, thus improving development efficiency and reliability. At the same time, Hamster can attract more developers to join the Filecoin and IPFS ecosystems, thereby promoting the development of the entire ecosystem.

This project enhances the usability and attractiveness of the entire Filecoin and IPFS ecosystem. By simplifying developers' workflows and improving development efficiency, Hamster can attract more developers and application scenarios to join the Filecoin and IPFS ecosystems, further promoting the development of the entire ecosystem. It becomes a more prosperous and innovative ecosystem, with more application scenarios and partners joining it, bringing more value to users and developers.

With the Hamster platform, when users choose Hamster for Dapp development, their operational path is reduced by 30%. Using Filecoin's FVM contract development, they can directly create, build, and deploy projects in just a few minutes. For Dapp developers, they no longer need to perform initialization operations and configure Filecoin settings locally before deployment, greatly reducing the entry barrier for users.

##  Outcomes

The ultimate deliverable of the Hamster project is an infrastructure and developer platform designed to help developers of Filecoin and IPFS to develop and operate smart contracts and DApps more efficiently.

It includes the following components:
1, A flexible infrastructure and developer platform that supports multiple contract writing, compilation, testing, deployment, and interaction.
2, Integration of popular contract templates, supporting Solidity contracts, to help developers get started quickly.
3, A complete automated work chain to help developers improve development efficiency and code quality. Features include code building, code/contract quality/security checks, deployment, CI/CD integration tools, etc.
4, Allowing developers to define their own work pipelines for easier project maintenance and management.
5, Documentation and examples to support developers in quickly mastering the platform's usage.

We are building a developer platform with several modules: hamster-frontend, hamster-develop, and aline-engine.

Hamster-frontend: is the frontend of Hamster, written in Vue.js, used for developer interaction.
Hamster-develop: is the backend of Hamster for developers, written in Go. It includes tools for template management, project management, pipeline management, deployment management, contract monitoring, and other management functions.
Aline-engine: is the core CICD engine written in Go. It is used to execute pipeline files and allows developers to write pipeline files to perform tasks.

Our team will measure the success of the project through the following indicators:
1, The number of developers using Hamster and the number of smart contracts and DApps supported by Hamster.
2, Activity and contribution on GitHub, including the number of stars, forks, PRs, and commits.
3, User satisfaction and feedback, including feedback on user experience, improved development efficiency, and improved code quality.
4, Participation and community development, including the number of community members, community activities, and developer conferences.

By continuously improving these indicators, we can judge the success of the project and constantly optimize and improve the functionality and performance of Hamster based on feedback, providing better support for developers in the Filecoin and IPFS ecosystems.

##  Adoption, Reach, and Growth Strategies

The target audience of Hamster is developers and teams who want to build Web3.0 applications, especially those who want to build applications in the Filecoin, IPFS, and other related ecosystems. Our target audience is large, including tens of thousands of developers and teams worldwide.

We interact with our target audience through social media, industry events, and developer communities. We also maintain close contact with members of the Filecoin and IPFS communities and collaborate with them to ensure that our tools and frameworks best meet their needs.

To attract new users, we will promote on social media platforms and actively participate in discussions and sharing of our tools and frameworks in developer communities. We also plan to collaborate with developer communities to provide training and support for developers.

For the acquisition of the first 10 and first 100 users, we will actively participate in the developer community, showcase our tools and frameworks to them and continuously improve and expand our products through collaboration and feedback. We will also organize online and offline activities to promote our tools and frameworks and attract more developers to join our community. We will go to the official Filecoin developer community to host events and promote our tool. Also, we will check with each project in the Filecoin ecosystem for cooperation and offering our tool for use. Besides, Hackathons and developers events will be hosted for promotion as well.

## Development Roadmap

First Milestone: Integration of Contract Templates
Integrate contract templates, including support for Solidity contracts and other contract languages. Mainly adapt templates contracts strongly related to FVM and FIL.
Participants: 3 developers, 1 test engineer
Expected funding: $10,000
Expected time: 1 month

Second Milestone: Development of CI/CD Processes and Code/Contract Quality/Security Check Tools
Develop CI/CD processes and code/contract quality/security check tools to improve the quality and security of the code. Contract deployment tools.
Contracts can be deployed to different networks chosen by the user. Currently, we support the production and test networks of Ethereum, Polygon, BNB Smart Chain, Arbitrum, IRIShub, StarkNet, Sui, and Aptos. In the future, we will add support for the mainnet and hyperspace network of Filecoin, and we will also host public PRC endpoints for users to use.
Participants: 6 developers, 1 test engineer
Expected funding: $20,000
Expected time: 1 month

Third Milestone: Define Your Own Work Pipeline
Developers can define their own work pipeline to adapt to their project needs.
Participants: 4 developers, 1 test engineer, 1 product manager
Expected funding: $20,000
Expected time: 1 month

## Total Budget Requested

The budget we need:
50,000Usd on manpower

## Maintenance and Upgrade Plans

It will be maintained by our Hamster team in the future

As a developer tool platform, Hamster's long-term plan is to continuously optimize and improve our tools, frameworks, and infrastructure to meet the evolving needs and technological developments of developers. Specifically, our long-term plan includes the following aspects:
Ongoing updates and maintenance: We will continuously keep up with the latest blockchain technology and market trends and update and maintain the tools, frameworks, and infrastructure of the Hamster platform in a timely manner to keep it up to date.
Based on existing functionality, we will optimize automated contract deployment, AI-based template recommendation generation, wallet component framework, contract operation and maintenance monitoring, and other features.
Strengthening security measures: We will continuously strengthen the security performance of the Hamster platform, provide more rigorous security mechanisms and practical tools to ensure the security of the contracts developed by users at runtime.
Support for more functions: We will continuously expand the functionality of the Hamster platform, so that more developers can use Hamster to develop and deploy smart contracts.
Providing more development tools and templates: We will continuously develop and provide more development tools and smart contract templates to help developers develop and deploy more efficiently and reduce development costs.
Strengthening community building: We will strengthen the community building of the Hamster platform, attract more developers and users to join, and provide better technical support and communication platforms to promote the development of blockchain technology together.

# Team

## Team Members

Porsche CTO
Nova CMO
Alvis  COO
Liam VP&Head of Tech
+ 20 Devs & 3 Marketing

## Team Member LinkedIn Profiles

Porsche: https://www.linkedin.com/in/porsche-shi-41832446/
Nova: https://www.linkedin.com/in/nova-wong-92b48359/ 
Alvis: https://www.linkedin.com/in/alvis-tsui-69952341/ 
Liam: https://www.linkedin.com/in/liam-liang-092950245/ 

## Team Website

https://hamsternet.io/

## Relevant Experience

Our team has been deeply involved in traditional Web2.0 fields for over 20 years, and has accumulated precipitation in the field of cloud native and cloud computing. We have profound experience in the operation, maintenance and deployment of large-scale projects. 

The core members of our R&D team have conducted research and development of blockchain projects in Web3.0. We believe that the provision of nodes can better empower developers and lower the threshold for entering the filecoin world.

## Team code repositories

https://github.com/hamster-shared 

# Additional Information
We heard several times from the community of Filecoin that a developer tooling service solution is urgently needed, which is in the scope of our goal as well.

Filecoin is a super big ecosystem, and is one of the top projects in the space. We learnt about the open grants program from Jenks Guo.  And based on the information from the filecoin community, we feel quite excited to BUIDL such a service for Filecoin and in Filecoin.

**Comment by ErinOCon** [comment]
Hi @Alvis1998, thank you for your proposal and for your patience with our review. Are you currently contributing to [this project](https://github.com/filecoin-project/devgrants/issues/794), as well?

**Comment by Alvis1998** [comment]
Dear @ErinOCon , thank you for your feedback! The decentralized computing power narrative was what Hamster was doing till Sept. 2022. Afterwards, we focused on development toolkit and middleware enginee which help to onboard more and more deverlopers into web3.0. Computing power, btw, is part of the Middleware. That proposal was submitted by the previous colleague. Now we focus more on this proposal, but depends on what filecoin needs the most.

**Comment by ErinOCon** [comment]
Hi @Alvis1998, thank you for the additional background. Unfortunately, we will not be proceeding with a grant for this proposal at this time. We would, however, like to make sure the previously approved project is fully resolved. I have sent you an email to set up a call time for this week.

Wishing you the best as you and your team continue to build!
