### ISSUE TITLE
Moonstax Grant Application

### ISSUE THREAD

**Issue by josephmoonstax** [filecoin-project/devgrants#1545]
# Open Grant Proposal: `Moonstax`

**Project Name: Moonstax**

**Proposal Category:** `Developer and data tooling`

**Individual or Entity Name:** `gDEX Metaverse Pte Ltd (DBA Moonstax)`

**Proposer:** `joseph moonstax`

**(Optional) Filecoin ecosystem affiliations:** `N/A` 

**(Optional) Technical Sponsor:** `N/A`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** "Yes"

# Project Summary

## Outcomes

140+ partners 
320k+ registered users 
1M+ SEA NFT crypto community backers
50K+ newsletter list 
100K+ socials & community

## Adoption, Reach, and Growth Strategies

Products/Users Strategy:

We have deep domain expertise and execution skills across Web3 and traditional entertainment, celebrity creators and gaming. Our network is extensive both Web3 and Web2 and already have existing partner/customer advantages. We are backed by top global gaming celebrities with 30M followers and 5Bn views. We are onboarding more gaming and lifestyle celebrities for promotion. Advertising across google, Twitter, Facebook, crypto networks, and youtube. Leveraging our current partners of over 140 and their communities of over 2M users for cross-collaboration marketing. We are currently expanding and integrating even more large crypto and NFT communities and identifying, evaluating, and partnering with more projects and communities around the world. We will continue doing sponsorships and key territory billboard advertising like Times Square and key cities in SEA

To date, we have utilized a lean startup model and leveraged our relationships, viral growth hacking and grass roots strategies to go to market. To optimize budgets we created a "marketing-specific" token round (private sale) exclusively for top gaming celebrities with 30+ million of followers/subscribers and billions of streams to promote, top SEA crypto NFT communities with millions of users to distribute Moonstax products and promote. We have executed AMAs, contests and events with all our NFT and gaming partners to keep an engaged ecosystem to facilitate cross-pollination to acquire new users. We have been featured on top news and media like NASDAQ and other notable media all from buzz, word of mouth and relationships and have acquired advisors who are top industry leaders both Web3 & Web2 who are opening doors for us for key accounts and customers. 

Once we complete this funding round we will start more traditional Performance Marketing for accelerated acquisitions, scale our sales & biz dev teams to acquire more high ticket partnerships/customers and onboard outside marketing experts to support our growth stage.  

MSTAX Token/Token Holders Strategy:

We will use effective planning and implementation to make sure our token holder marketing campaigns are a success. We currently are already educating and promoting our valuable token utilities to our community and all the benefits of being a holder. We already have reward and bug bounty programs going on. We will start full marketing campaigns 3 months before the date of the token sale. Currently we already use Google Analytics for all our current campaigns so we can efficiently optimize our digital brand, users and traffic online. This includes using link builders like Bit.ly for UTMs (Urchin Tracking Modules) so we can monitor and optimize our efforts.

We will implement a content strategy that educates, connects, and informs investors about our token offering across Twitter, Facebook, Telegram, Discord, YouTube, Reddit, Quora, BitcoinTalk. Our project uses a “community first,” approach where we focus on the opinions of our community members and allow our community to be a part of our development, growth and launch. We prioritize the feedback of our community to make sure they feel a part of the project and are incentivized to be a long term holder. Some of the activations for token marketing include:

Community marketing
Influencer Marketing Campaigns
Ambassador program
Bounty programs
User generated content contests
AMAs
PR & Media
Partnership media and events for cross-community promotion
Podcasts
Performance marketing and banner ads on CMC, Coingecko, Eth Scan, etc
SEO
Email marketing to our growing 50,000 member lists

## Total Budget Requested

| Milestone # | Description | Deliverables | Completion Date | Funding |
|$75,000|Filecoin Integration|4Months|===|

## Maintenance and Upgrade Plans

As for the payout structure, you could consider dividing the funds into two payments, with 50% upfront for each milestone.

#1: Build, marketing & partnership development - $37.5k Payment

~ Research & Filecoin education 
~ Build contracts 
~ Testnet integration
~ Finalize UI
~ Complete testing
~ Audit
~ Create & Prepare marketing materials
~ Create & Prepare sales/partnership materials
~ Start Filecoin marketing and promotion
~ Start Filecoin partnership development

#2: Mainnet & Full Ecosystem Growth - $37.5k Payment

~ Full-scale Filecoin ecosystem go to market 

~ Launch Filecoin focused AMA with Moonstax, Filecoin team, and Filecoin ecosystem partner

~ Influencer marketing and social media outreach: 
Identify and reach out to relevant influencers in the Filecoin ecosystem, collaborate with influencers on social media campaigns and content creation and create social media content for Moonstax and Filecoin accounts

~ Community growth and engagement: 
Host community events and meetups to engage with Filecoin users and community members, develop and execute a community management strategy to foster engagement and loyalty, create and distribute educational content to help users understand Moonstax and its benefits and provide ongoing customer support to ensure user satisfaction and retention

~ Content marketing: 
Develop and execute a content marketing strategy to drive traffic and generate leads and develop and execute a thought leadership strategy to position Moonstax as a leader in the Filecoin ecosystem -->

# Team

## Relevant Experience

# Additional Information

CEOs email and twitter
<!-- jd@moonstax.com →
https://twitter.com/JDSalbego

Moonstax Pitch Deck
https://moonstax.docsend.com/view/fbkise7yf4i84r4r
Moonstax Tokenomics
https://moonstax.docsend.com/view/cs9q6h8d46hy9eh7

**Comment by ErinOCon** [comment]
Hi @josephmoonstax, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
