### ISSUE TITLE
Filecoin Storage Bridge

### ISSUE THREAD

**Issue by mwittie** [filecoin-project/devgrants#1548]
# Open Grant Proposal: `Filecoin Storage Bridge`

**Project Name:** Filecoin Storage Bridge

**Proposal Category:** `Developer and data tooling`

**Individual or Entity Name:** BLOCKY, Inc.

**Proposer:** `mwittie`

**(Optional) Filecoin ecosystem affiliations:** `N/A`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

The [Ethereum blockchain is transitioning](https://www.youtube.com/watch?v=N5p0TB77flM&t=0m0s) from a global computation platform to a global data platform, or an L1 settlement chain for computation performed on L2 rollups, and validiums. The roadmap of that transition starts with [Proto-Danksharding](https://www.eip4844.com/), which will provide blob storage for L2 chains. The intention for this blob storage is to record L2 data structures (blocks, Merkle trees, transactions) that reflect the consensus over the state of the L2 chain. The key simplification of Proto-Danksharding with respect to Danksharding is that blobs stored in Proto-Danksharding expire after [30-60 days](https://eips.ethereum.org/EIPS/eip-4844#security-considerations). The assumption underlying Proto-Danksharding is that in that time interested parties will have ample opportunity to migrate the expiring blob data onto permanent storage. The mechanism of data migration, has not been specified, which creates an opportunity for Filecoin to position itself as the default storage platform for blob data evicted from Proto-Danksharding.

However, the problem of migrating data from Proto-Danksharding is more complex than it may seem at first glance. L2 chains often rely on weaker consensus mechanisms than L1 chains, which means that their ledger histories are more vulnerable to rewriting by a determined attacker. It is precisely to prevent such attacks that L2 chains use L1 chains as a settlement layer, or a record of truth. Consequently, it is not sufficient to simply migrate blob data to permanent storage - it must also be possible to verify that the migrated data came from Proto-Danksharding, as opposed to another source that may contain a rewritten version of the data.

To facilitate verifiable migration of blob storage data, we propose to create Filecoin Storage Bridge (FSB). The key innovation behind the FSB is to use the [Nitro Enclave](https://aws.amazon.com/ec2/nitro/nitro-enclaves/) Trusted Execution Environment (TEE) to create attestations of where data came from and where it is stored. At its core, a Nitro Enclave executes a containerized application in an isolated environment and provides a mechanism for the application to generate cryptographic attestations over its state, signed by Amazon. As long as users trust Amazon to retain the control over the Nitro Enclave private key and to maintain isolation between EC2 instances, they can trust that the attestations are valid.

The FSB will use Nitro Enclaves to fetch data from Proto-Danksharding blob storage, create attestations over the source of the data, and store the blob data along with the attestations on Filecoin. Effectively, FSB attestations will preserve the veracity and verifiability of Proto-Danksharding blob storage migrated onto Filecoin. More broadly, the FSB could be extended to serve as a general *data oracle*, for example to allow Ethereum smart contracts to verify the source of off-chain data written to Filecoin.

## Impact

- L2 projects that settle onto Ethereum will be able to offload Proto-Danksharding data onto Filecoin
- A general service to create attestations over the source and content of REST API responses

## Outcomes

1. An enclave application that supports fetching data from an HTTPS endpoint and creates a Nitro enclave attestations over the source and contents of the data
2. Scripts to build and deploy a Nitro-enabled EC2 instance running the enclave application allowing anyone to deploy their own API data bridge to Filecoin
3. A CLI client to request and validate Nitro enclave attestations over the source and contents of the data

## Adoption, Reach, and Growth Strategies

We propose a mechanism to attest the source and content of data primarily to move Ethereum Proto-Danksharding blob data to Filecoin. The intended users of Proto-Danksharding are L2 rollups and validiums developers. Currently, there are [22 Ethereum L2 projects with $9.25B of locked value](https://l2beat.com/scaling/tvl) issuing over [112 million transactions in the last 30 days](https://l2beat.com/scaling/activity) that will make their way into Proto-Danksharding when it becomes available. We have talked with rollup developers, who perceive the lack of Proto-Danksharding blob data migration mechanism as a challenge. Beyond L2 projects, FSB has the potential to serve as the basis for general data oracle to attest the source and content of REST API responses.

## Development Roadmap

Our objective is to make it possible for data clients to attest the source of the data they store on Filecoin. Such attestations are critical to storing Proto-Danksharding data on Filecoin, since anyone reading that data needs to trust that the data originated from Proto-Danksharding blob storage.

We propose to extend the existing Nitro Enclave tooling to create an application to read and attest data from arbitrary internet sources. As a starting point, we will use BLOCKY's fork of the [Brave](https://brave.com/) [nitriding](https://github.com/blocky/nitriding) framework, which allows users to build and verify Nitro Enclave containers. Nitriding already permits TLS connections to the enclave container, which we will extend to allow enclave applications to reach out to URLs and attest the source as well as the content of the data.

To allow Filecoin clients to attest the source of the data they store on Filecoin, we propose to implement the following protocol:

```mermaid
sequenceDiagram
	autoNumber
	participant client as Data Client
	participant enclave as Enclave
	participant url as Web Server
	participant ipfs as IPFS
	participant network as Filecoin
	
	opt Get enclave attestation
		client ->> enclave: GET /attestEnclave
		activate client
		activate enclave
		enclave --) client: enclaveAttestation
		deactivate client
		deactivate enclave
		
		client ->> ipfs: store enclaveAttestation
	end
	
	client ->> enclave: GET /attestSource?URL
	activate client
	activate enclave
	enclave ->> url: GET URL
	url --) enclave: OK (content)
	note right of enclave: Create sourceAttestation
	enclave --) client: OK (sourceAttestation)
	deactivate enclave
	
	client ->> network: store sourceAttestation
	activate network
	deactivate network
	deactivate client
```

1. A new nitriding-based enclave application creates a unique key pair `K_pub/K_pri` on startup. The key `K_pri` is only available inside the enclave, and so any information signed by `K_pri` is known to come from the enclave. For a client to know that `K_pub` is an enclave key generated by a specific enclave application, the client requests a Nitro Enclave `enclaveAttestation` from the `/attestEnclave` endpoint.

2. The enclave generates an `enclaveAttestation` containing:
	- the application's public key `K_pub`
	- `PCR0`, or [the measurement of application container running on the enclave](https://docs.aws.amazon.com/enclaves/latest/user/set-up-attestation.html)
	
	both signed by the well-known [Nitro Enclave private key](https://aws-nitro-enclaves.amazonaws.com/AWS_NitroEnclaves_Root-G1.zip). Any client can thereafter [verify the attestation using the well-known Nitro Enclave public key](https://docs.aws.amazon.com/enclaves/latest/user/verify-root.html), check that the `PCR0` matches an expected value, and use `K_pub` to authenticate messages from the enclave.

3. The client stores the `enclaveAttestation` on IPFS, so that it becomes available to other users.

Note that steps 1 through 3 need to be performed only once. With the `enclaveAttestation` available under its `CID`, the client may start requesting attestation over URL data.

4. A Filecoin data client requests a `URL` attestation from the enclave by calling the `/attestSource` endpoint with a `URL` as a parameter. In the context of Proto-Danksharding, the `URL` points to a blob available through a well-known blockchain explorer.

5. The enclave makes a `GET` request to the Web server hosting the `URL`.

6. The enclave downloads the `content` of the `URL` and creates a `sourceAttestation` containing:
	- the `URL`
	- the `content` of the `URL`[^1]
	- the TLS `certificate` of the Web Server
	- a `timestamp`
	- and the `CID` of the `enclaveAttestation` (computed on the enclave from the
	  previously issued `enclaveAttestation`)
	
	all signed with the enclave application's private key `K_pri`.

[^1]: The `HTTP` response to a `GET` request could contain content requiring no further action. Alternatively, the response could require further processing of redirects, links, or scripts. In the first version of FSB we propose to simply attest the content of `HTTP` response as-is, if the response status code is `200`, which will suffice for Proto-Danksharding blob storage. In the context of a more general data oracle, it might be practical for data clients to specify the download method, such as `curl`, and for the enclave to attest to the method, its release version, invocation parameters, etc., as well as its output.

7. The enclave replies to the client with the `sourceAttestation`.

8. The client stores the `sourceAttestation` on Filecoin.

At the end of this process anyone reading the `sourceAttestation` from Filecoin will be able to:

- find the corresponding `enclaveAttestation` from its `CID` embedded in the `sourceAttestation`
- verify the `enclaveAttestation` and its `K_pub`
- use `K_pub` to verify the `sourceAttestation`
- know that the `content` in `sourceAttestation` came from the `URL` hosted at a web server with a specific `certificate` at a specific `timestamp`

In the context of Proto-DankSharding, anyone reading an attested blob from Filecoin will know that the data came from Proto-Danksharding blob storage.

### Milestones

1. An enclave application written in Go that supports fetching data from an HTTPS endpoint and creates a `sourceAttestation` over the data
2. Scripts to build and deploy a Nitro-enabled EC2 instance running FSB
3. A CLI client to request and validate `sourceAttestations`

## Total Budget Requested

```mermaid
gantt
	dateFormat  YYYY-MM-DD
	excludes    weekends
	Milestone 1 - Enclave application: m1, 2023-07-01, 30d
	Milestone 2 - Deployment scripts: m2, after m1, 20d
	Milestone 3 - CLI client: m3, after m1, 20d    
```

We request $60K to complete these milestones:

- $30K to begin development
- $15K on completion of Milestone 1
- $15K on completing the Milestone 2 and Milestone 3

## Maintenance and Upgrade Plans

We plan to release the project as open source to allow developers to update the FSB enclave application and CLI to meet their needs. On our end we will maintain the `nitriding` framework for enclave application development and the Nitro-enabled EC2 deployment scripts.

# Team

## Team Members

- Taylor Heinecke, BLOCKY, CEO
- Mike Wittie, BLOCKY, Chief Scientist
- David Millman, BLOCKY, CTO
- Taylor Hardin, Software Engineer

## Team Member LinkedIn Profiles

- Taylor Heinecke - https://www.linkedin.com/in/taylor-heinecke/
- Mike Wittie - https://www.linkedin.com/in/mike-wittie/
- David Millman - https://www.linkedin.com/in/dlmillman/
- Taylor Hardin - https://www.linkedin.com/in/taylor-hardin-4984ba275/

## Team Website

https://blocky.rocks

## Relevant Experience

Mike Wittie, David Millman, and Taylor Hardin hold PhDs in Computer Science with joint expertise in distributed systems, software engineering, and secure computing.

Particularly relevant to this proposal is our collaboration with the [Brave](https://brave.com/) team on [nitriding](https://github.com/blocky/nitriding) - a framework for deployment and verification of containerized applications running on Nitro Enclaves. We have dog fooded `nitriding` to develop several internal applications.

## Team code repositories

https://github.com/blocky/nitriding

# Additional Information

To discuss grant agreement and general next steps please contact [Taylor Heinecke](mailto:taylor@blocky.rocks).

**Comment by ErinOCon** [comment]
HI @mwittie, thank you for your patience with our review. Unfortunately, we will not be proceeding with a grant at this time. Wishing you all the best as you continue to build!
