### ISSUE TITLE
Themis Protocol

### ISSUE THREAD

**Issue by Annokay1** [filecoin-project/devgrants#1549]
# Open Grant Proposal: `Themis Protocol`

**Project Name:**`Themis Protocol`

**Proposal Category:**  `Applications`

**Individual or Entity Name:** Is the proposal on behalf of an individual, or an entity/organization? Please note that the agreement and any payments must be completed by the same entity, either individual or organization.

**Proposer:** `Themis Labs. Organisation- Themis Matrix Foundation`

**(Optional) Filecoin ecosystem affiliations:** `The Themis Protocol has no work relationship with Protocol Labs Network. The Themis community consists of numerous FIL holders as well as small and medium-sized service providers.` 

**(Optional) Technical Sponsor:** `Bool network、Guazi Dongli、Ntminerpoor`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** `Yes`

# Project Summary

1. The scope of Themis Protocol includes building the underlying infrastructure of the FVM public chain, including: Themis Swap, an AMM exchange; Themis Pro, a decentralised asset exchange for spot and derivatives trading with 0 slippage; Themis Pool, an LSD protocol based on Themis Pro for FIL holders and SPs; Themis Stablecoin, a USD stablecoin protocol based on FVM.

2. The development roadmap for Themis Protocol is as follows: The Themis Swap public beta version has already been launched on FVM, and the Themis Pro public beta was launched on May 7th. Derivatives trading will require the official launch of Filecon's IPC. Themis Pool will launch in late May, and Themis Stablecoin will launch in June to July.

3. The operational roadmap for Themis Protocol includes an IDO that started in April and has raised $1.5 million,and more than 2,000 participants. On May 7th, more than 100 Themis community leaders will participate in the Themis Protocol's FVM launch event. Going forward, Themis Protocol will continue to attract users through online and offline conferences worldwide to expand its influence and become the most influential DeFi protocol on the FVM, helping to establish a solid financial foundation for FVM and Filecoin.

## Impact 

**What pain points does this project seek to address?**

1. The Themis Protocol will help lock a large amount of FIL tokens, drive up the FIL price, stimulate miner enthusiasm, bring in FIL packaging mining machines and consume GAS, and bring the Filecoin ecosystem into a positive development trajectory.

2. FVM is a new public chain, and looking at the early development of Ethereum, Solana, and Avalanche, they often rely on increasingly rich and mature product structures to gain huge transaction volume and liquidity, and quickly become the absolute protagonist on the public chain stage. However, FVM lacks basic infrastructure protocols such as cross-chain, DEX, stablecoins, and lending, which will seriously hinder its development. Themis Protocol is here to help FVM build the underlying infrastructure of the public chain, and Themis Swap, Themis Pro, and Themis stablecoin are all essential components of FVM.

**What are the benefits to getting this right? What are the risks of not getting this right? What impact will this project have in a specific vertical, market, or ecosystem? What does success look like?**

1. Currently, the LSD business that FF, PL, and Filecoin Marketing are focusing on cannot fundamentally solve the difficulties that Filecoin is facing. It will only make FIL tokens more concentrated in the hands of top SPs, without increasing the number of retail holders and middle-to-lower tier SPs. As a result, it will be difficult for FIL prices to rise and Filecoin's development will become more challenging. Therefore, Filecoin should pay more attention to the development of FVM financial infrastructure.

2. The development of Themis Protocol is of great significance for the locking of FIL tokens and is more valuable in the long run than LSD dominated by SPs:

-  1) First of all, Themis Swap will immediately become the largest DEX on FVM in terms of TVL (initially expected to be $1.5 million) once it is officially launched. It will gradually attract more projects to issue tokens on FVM, some of which will form trading pools with FIL. With the development and expansion of Themis, Themis Swap will lock in a large amount of FIL into the AMM trading pool.

-  2) Themis Pro's treasury will include FIL as one of the main assets for minting the platform token THS. With the development of Themis, the amount of locked FIL tokens will continue to increase. Themis Pro is expected to be launched around May 10th, and after three months, i.e., August 2023, the Themis treasury will include FIL worth $3 million (10% of the total assets in the Themis treasury). At FIL's current price of $5.2, the Themis treasury will lock in about 600,000 FIL in August, 1.2 million FIL in November, 2 million FIL in February 2024, and 4 million FIL in May 2024.

-  3) Themis Pool- Themis LSD business, based on the underlying technology of Themis Pro, offers higher annualised returns to retail FIL holders compared to most LSD businesses developed by SPs. Annualised returns can reach more than 30%. Themis Pool receives FIL deposits from retail holders and then lends them to top SPs to collect interest, which is used to mint THS. Then, THS can be staked to obtain annualised returns of more than 2000%, which is enough to support an annualised return of more than 30% for FIL depositors (more advantageous than SP's LSD business). Themis Pool is expected to launch in late May, and is expected to lock in 1 million FIL in August 2023, 2 million FIL in November 2023, 4 million FIL in February 2024, and 10 million FIL in May 2024.

-  4) Themis Stablecoin, which will be launched in July 2023, will allow FIL holders to mint a USD stablecoin using FIL. At the same time, Themis treasury will accept this stablecoin to mint THS. It is expected that 3 million FIL will be used to mint stablecoins in February 2024, and 6 million FIL will be used to mint stablecoins in May 2024.

In summary, with the four products of Themis Swap, Themis Pro, Themis Pool, and Themis Stablecoin, under the normal development of the protocol, Themis Protocol will help lock in no less than 20 million FIL tokens for Filecoin within a year.

## Outcomes

1. Themis Swap is a decentralised exchange built on the FVM using the AMM mechanism, similar to Uniswap and PancakeSwap.
2. Themis Pro is the core product of the Themis protocol and the underlying framework of the protocol. It implements the Liquidity as a Service (Laas) incentive model for the new generation of DeFi liquidity. It is an innovative DeFi protocol that combines the advantages of Curve, Olympus, and GMX. Due to the complexity of the model, it is not elaborated here, and you can refer to the "Themis Pro-DeckV2.1-EN" link for more information: https://themis-pro.gitbook.io/themis-pro-docs/themis-deck/themis-pro-deck-v2.1-en.
3. Themis Pool - for more information, please refer to the "Themis Protocol-Deck V1-EN" link: https://themis-pro.gitbook.io/themis-pro-docs/themis-deck/themis-protocol-deck-v1-en.
4. Themis Stablecoin, temporarily named fUSD, similar to DAI, is minted by over-collateralizing FIL. Users can redeem FIL with a small amount of interest using fUSD. fUSD is also an asset stored in the Themis Treasury for minting THS. fUSD can be exchanged for USDT, USDC at a 1:1 ratio with 0 slippage in Themis Pro, and can also be exchanged for ETH, BTC, etc. at 0 slippage based on the oracle price. It is an important part of the Themis ecosystem, and even the Filecoin ecosystem.

`Phase 1`
In May 2023, Themis Pro will be officially launched. After 5 months, Themis Pro's TVL (Treasury assets) will reach $50 million, achieving the first phase goal. At the same time, the four main products will lock in 4 million FIL tokens.

`Phase 2`
On the one-year anniversary of the protocol's launch, the TVL of Themis Pro and Themis Swap will reach $400 million, with the four products locking in 20 million FIL tokens.

`Phase 3`
Themis Pro's derivative trading becomes the main source of profit for the protocol. In the second year of the protocol's launch, the goal of achieving $100 million in annual profit from derivative trading will be realised

## Adoption, Reach, and Growth Strategies

The Themis Marketing team has a mature online and offline operation system. I won't go into details here, but just the IDO of Themis has already attracted nearly 2,000 users to participate.

## Development Roadmap

**Our Recent Timeline **
1. In late April 2023, Themis Swap of the AMM exchange will undergo public testing, with a formal launch in May. As the underlying infrastructure of the FVM chain, the Themis Pro protocol will establish trading pools for THS-USDT and SC-USDT on Themis Swap. The initial liquidity of the THS-USDT trading pool is expected to be $800,000, while that of SC-USDT is expected to be $100,000. Additionally, a FIL-USDT trading pool will be established. Due to the limited circulation of USDT on the FVM chain, major centralised exchanges will not enable USDT deposits and withdrawals on the FVM chain in the short term. While users can transfer USDT to other public chains through cross-chain bridges, it is still not convenient enough for many users. The most convenient way is to exchange USDT for FIL through the FIL-USDT pool and then cash out through FIL. The initial liquidity of FIL-USDT is expected to be $100,000. We hope that all Filecoin ecosystem builders, including the Filecoin Foundation, will work together to promote liquidity on the FIL-USDT pool, as it is crucial for the development of the FVM and Filecoin's early ecosystem.

2. In May 2023, the core functions of Themis Pro, including the treasury contract, minting contract, bonding contract, staking contract, and DAO contract, will undergo public testing and formal launch. THS-USDT LP bond, FIL bond, and USDT bond sales will be available in the early stage, allowing users to use LP, USDT, and FIL to mint THS on Themis treasury. This will increase the size of the THS-USDT pool and bring a large amount of FIL and USDT into the Themis treasury.

3. In late May, perpetual trading on Themis Pro will undergo public testing. After Themis treasury has accumulated a certain amount of FIL and USDT, a zero-slippage FIL token trading will be enabled on the chain through the oracle. As the amount of BTC and ETH deposited into the Themis treasury increases, perpetual zero-slippage spot trading for BTC and ETH will also be available. When FVM-IPC is officially launched, contract trading for FIL, BTC, and ETH will also be enabled, becoming the core profit point of the Themis protocol.

4. In late May, Themis Pool's LSD service will undergo public testing, based on high-yield THS staking on the Themis Pro's underlying layer, Themis Pool can support an annual interest rate of over 30% for FIL deposits.

5. In June, Themis Stablecoin will undergo public testing, allowing excess FIL to be used as collateral to mint USD stablecoins. Through Themis Pro, users can exchange these stablecoins for USDT, USDC, and other cryptocurrencies with zero-slippage, creating liquidity value for idle FIL in users' hands.

6. In July, the LAAS service for NFT will undergo public testing.

| Milestone # | Description | Deliverables | Completion Date | Funding |

| No.1 #|Themis Swap|The largest TVL AMM-type DEX on the FVM chain.|April 30th, 2023 |$10,000|
| No.2 # | Themis Pro | The first LAAS-type DeFi protocol on the FVM chain. | Early May 2023 | $30,000 |
| No.3 # | Themis Perpetual and Themis Pool | The first decentralised 0-slippage asset exchange-type DEX on FVM with LSD protocol on FVM with the highest FIL deposit yield. | Late May 2023| $70,000 |
| No.4 # | Themis Stablecoin | The first stablecoin protocol on FVM to mint USD by staking FIL as collateral |$40,000 |

## Total Budget Requested

Our fund needed is a total of $150,000. 

**However** , we are only requesting to apply a **$50,000**  OPEN GRANT from Filecoin Foundation. The other remaining fund $100,000 are supported by our strong community. 

**Special Request**
Themis Swap FIL-USDT liquidity needs FF to lead and build together.

## Maintenance and Upgrade Plans

After reading the previous content, you may have some understanding of the long-term plan of Themis protocol. Here are some additional explanations:

The LAAS of Themis is a long-term process that continuously increases the protocol's liquidity and the types of liquid assets. Themis Treasury initially absorbed three types of assets: THS-USDT LP, USDT, and FIL. In the mid-term, the focus was on increasing the absorption of BTC, ETH, USDC, and DAI. In the mid-to-late term, assets in the top 20 of the crypto market capitalization could become an important part of Themis liquidity. This will make Themis Pro the blue-chip asset trading platform with the highest TVL on the FVM chain, and this platform has unique advantages such as zero slippage, low fees, high capital utilisation, and strong profitability. When the TVL reaches a certain amount, such as 30-50 million US dollars, the decentralised derivatives trading market will open. The huge blue ocean market for decentralised contract trading of BTC and ETH will become the driving force for Themis's rapid development, further supporting the value of the platform token THS. In particular, the opening of the FIL derivatives futures trading market is a huge benefit for Filecoin SP. SP has invested a lot of manpower, financial resources, and physical resources to build mining farms, but the uncertainty of future FIL prices may bring uncertainty to SP's income. SP can fully utilise the decentralised derivatives futures trading market of Themis Pro to hedge the risks of possible price drops in FIL, thus attracting more people to join SP's ranks.

Themis Pool, which focuses on LSD, is a crucial area that Themis protocol has paid close attention to since the beginning, and it is something that Themis protocol will soon vigorously promote. Through LSD, Themis has more opportunities to connect with Filecoin community users and SP and establish partnerships. Through recent contacts with the Filecoin community, SP, and FVM marketing, the team has further validated its previous speculation that the Filecoin community is almost a DeFi desert with low awareness of DeFi. Filecoin needs a DeFi team like Themis, which has been deeply involved in the DeFi field for many years and has a wealth of experience in development and operations, to educate the community and drive it forward.

Themis Swap and Themis Stablecoin are important pieces of the Themis protocol ecosystem, and as two of the three basic infrastructure of the public chain, their value and significance to FVM are self-evident. Themis protocol has the responsibility, obligation, and ability to help FVM do a good job in these two areas. We hope that the Filecoin Foundation can work with Themis protocol to build liquidity for FIL-USDT in Themis Swap. This is crucial, and even though it has been mentioned  before in this document, as an applying organisation, we still need to emphasise it for the third time. This is important and beneficial to everyone and every organisation, including FF, PL, SP, FVM, FIL holders, and of course, Themis.

In summary, it is highly likely that Themis protocol will become the most solid foundation for the FVM and even the Filecoin DeFi financial layer. Themis protocol will not only help FVM build a sound underlying infrastructure but also bring a steady flow of external traffic through Themis operations, driving the rapid expansion of FVM's influence. The Themis team believes that Themis and FVM will become partners who achieve mutual success and close cooperation, just like GMX and Arbitrum.-->

# Team

## Team Members

Sam Kroos - CEO        
Slack ID Name: Sam
Alan Meta - CTO         
Slack ID Name: Alan Meta
Tabor - CMO              
Slack ID Name: Tabor Themis Protocol
Joe Andy - COO         
Slack ID Name: Joe Andy
Ann - BDM                  
Slack ID Name: Ann

https://twitter.com/themis_pro?s=11

## Relevant Experience

From 2017 to 2018, the development team participated in the development of two public blockchain projects. From 2021 to 2022, both the development and operations teams continued to develop and operate DeFi protocols on the ETH and BSC chains. After in-depth research on the advantages and disadvantages of the Olympus protocol, the team developed and operated Themis V1 in the LAAS category on the BSC chain in 2022, which was unanimously recognized by the community and achieved good results. The development team can quickly adapt to the development of DeFi protocols on various public chains, while the operations team excels at DeFi education and community engagement.

## Team code repositories

https://github.com/BIUT-Block/biutblock-client

# Additional Information

During the Hong Kong Web3 Festival, our team met with the Filecoin team in person. Following a call, a staff member from the Filecoin Foundation shared many useful links with us and mentioned that the Themis Team has the potential to apply for an Open Grant.

To discuss grant agreement and general next steps please contact themis.pro33@gmail.com

Themis V1 official website: https://themis.capital

**Comment by ErinOCon** [comment]
Hi @Annokay1, thank you for your patience with our review process. Unfortunately, we will not be proceeding with a grant at this time. Wishing you all the best as you continue building!
