### ISSUE TITLE
Cirrus IPFS - Decentralized Cloud Storage Alternative to Google Drive

### ISSUE THREAD

**Issue by Pr0fe5s0r** [filecoin-project/devgrants#1552]
# Open Grant Proposal: `CIRRUS IPFS`

**Name of Project:** CIRRUS IPFS - Decentralized File Storage Solution.

**Proposal Category:** `App-dev`, `Devtools-libraries`

**Proposer:** `@Pr0fe5s0r`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes

# Project Description
The Cirrus IPFS is a decentralized storage solution alternative to centralized storage solutions like Google Drive, One Drive, etc. Cirrus IPFS uses Filecoin and IPFS. The vision of Cirrus IPFS is to provide a simplified UX experience that abstracts the complexity behind storing data in IPFS and Filecoin protocol. Under the hood, Cirrus IPFS encrypts files using a simple password-based system encapsulated around the local web3 wallet. Cirrus IPFS also provides an S3 standard API system for migration and backup from traditional cloud storage to enable censorship-resistant decentralized storage for Developers and Enterprise Users.

Current Product Website: https://usecirrus.cloud/

## Impact

- What are the benefits of getting this right?

    1) Enhanced privacy and security through encryption and decentralized storage.
    2) Simplified user experience, making IPFS accessible to a broader audience.
    3) Censorship-resistant storage for developers and enterprise users.
    4) Integration with existing applications through the S3 standard API.

- What are the risks if you don't get it right?

    1) Data vulnerabilities due to weak encryption or compromised password-based system.
    2) Poor user experience, leading to limited adoption and user dissatisfaction.
    3) Potential regulatory challenges due to decentralized and censorship-resistant features.

- What are the risks that will make executing on this project difficult?

    1) Technical complexities in integrating Filecoin and IPFS effectively.
    2) Competition from existing centralized storage solutions.
    3) Regulatory scrutiny around decentralized storage and data privacy.
    4) User resistance to adopting a new storage paradigm.

## Outcomes

   1) Decentralized and censorship-resistant storage: Cirrus IPFS provides a robust solution that promotes data sovereignty and protects against censorship, ensuring users have control over their data.

   2) Enhanced data privacy and security: By encrypting files and utilizing decentralized storage, Cirrus IPFS offers improved data privacy and security compared to centralized storage solutions.

   3) Simplified user experience: The project's focus on providing a simplified user interface abstracts the complexities of IPFS, making it accessible to a wider range of users.

   4) Integration with existing workflows: The S3 standard API system enables developers and enterprise users to seamlessly integrate Cirrus IPFS into their existing applications and workflows, enhancing their storage capabilities.

   5) Incentivized storage marketplace: Leveraging Filecoin, Cirrus IPFS creates an incentivized marketplace where users can earn rewards for providing storage resources, fostering a dynamic and self-sustaining ecosystem.

   6) Empowering developers: The availability of a developer-friendly API and censorship-resistant storage opens up new possibilities for innovative applications and services built on the IPFS protocol.

## Development Roadmap

**Milestone 1:**

- Redefining the API system and Product.

- Making much more friendly UI/UX.

- Simplified and Secure File Sharing System.

- Integrating Wallet Encryption for Private File Upload.

Estimated Time - 3-4 weeks, Funding - $8,000

**Milestone 2:**

- Establishing more IPFS nodes and Filecoin nodes.

- Creating more gateways based on geolocation.

Estimated Time - 3 weeks, Funding - $6,000

**Milestone 3:**

- Simplified NPM package for interacting with API system.

- To create Proper Documentation.

- To Create Demo videos.

- Properly documented GitHub README

Estimated Time - 3 weeks, Funding - $8,000

**Milestone 4:**

- Conduct Hackathons.

Estimated Time - 2 weeks, Funding - $5,000

## Total Budget Requested

Total Budget Requested - $27,000

Total Time - 12 weeks, starting as early as 06/3/2023

Funding will be used to pay the team and other expenses that occur to complete the project.

## Maintenance and Upgrade Plans

The plan is to involve the community to take in feedback during and after the project is built and resolve bug fixes or other issues that anyone faces while using the project and maintain it for the long term.

# Team

## Team Members

- Sri Santh M

## Team Member LinkedIn Profiles
- https://www.linkedin.com/in/sri-santh-089749212/

## Team Website

- https://usecirrus.cloud 

## Team Codes:

https://github.com/Cirrus-IPFS

## Relevant Experience

I have been working on Web3 space for around 3+ years. And also worked in the P2E gaming company **Zomfi** and many other small projects. Started Cirrus IPFS on 21st Jan 2023.

Won some web3 hackathons conducted by XDC and CoinEX blockchain. And 2+ years of experience in Bug Bounty.

**Comment by ErinOCon** [comment]
Hi @Pr0fe5s0r, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. 

Wishing you all the best as you continue building!
