### ISSUE TITLE
Next Step Microgrant: <resolutio>

### ISSUE THREAD

**Issue by snevii** [filecoin-project/devgrants#1553]
### 1. What is your project, and what problem does it solve? (max 100 words)

_resolutio_ is a Decentralised Justice and Social Platform, built as a service with IPFS, NFT.storage and FVM.

We provide creators & artists pre-emptive and post-conflict protection through affordable and accessible tools.

Both legal aid and legal tools to protect art or literary work and resolve disputes in cases of infringement are expensive and inaccessible. We solve this problem using our (1) decentralised dispute resolution platform (DDRP) and (1) AI chatbot.

DDRP is a community run mechanism where creator community resolves disputes. They are also incentivised for the same. AI chatbot will make legal information more accessible. 

### 2. Project links
  
Link to Github repo: https://github.com/resolutio-ai
Link to demo or website: https://resolutio.ai/ ( dispute resolution & AI chatbot tools not publicly launched on website ) | dispute resolution demo:
https://youtu.be/gywK4oqiMlE | AI Chatbot demo: https://youtu.be/QpsK3uDAC8A
License: APACHE 2.0

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

The project uses Filecoin for three primary things. To (i) deploy 3 smart contracts for dispute resolution on FVM, for (ii)evidence management using IPFS and for (iii) decision NFTs which uses IPFS-http-client and NFT.storage. The dispute resolution part of the project is divided into 4 phases, image verification, dispute initiation,  arbiter selection and voting. 

**Dispute Resolution**

1. Dispute Initiation
 If a party wants to initiate a dispute, details pertaining to it is collected and stored on IPFS ( to prevent evidence tampering). It’s CID is then recorded on the ‘DisputeInitation’ smart contract. Each dispute, with their ID, creator wallet address and the CID of the evidence is recorded on the ‘DisputeInitation’ smart contract. 
    
Details about the contract may be accessed here:
https://github.com/resolutio-ai/backend-smartcontract/blob/master/contracts/DisputeInitiation.sol
    
2. Arbiter Selection
When a dispute is notified, eligible persons may elect to participate in the adjudication process. Eligibility of persons and selection of arbiters for disputes are governed by the ArbiterSelection smart contract. 
Arbiter DAO reviews applications by users to become eligible to adjudicate. The Arbiter DAO was built on FVM. It was created using Openzepplin smart contracts for voting and ERC20 tokens for DAO voting.
Ref: https://github.com/resolutio-ai/resolutio-ai/commit/6ce9865d28e3d047a7039ff849b8c298f7679b00
    
ArbiterSelection smart contract may be accessed here: 
https://github.com/resolutio-ai/backend-smartcontract/blob/master/contracts/ArbiterSelection.sol
    
3. Voting
 The selected arbiters are given access to the details stored on IPFS.  Based on this they can  vote. The final decision is recorded and minted as NFTs. Copies of the Decision NFTs, which are ERC 1155 tokens are sent to honest arbiters and parties. This is governed by the DecisionNFT smart contract. The smart contract may be accessed here: https://github.com/resolutio-ai/backend-smartcontract/blob/master/contracts/DecisionNFT.sol
    
 To assist adjudication, we reply on web3 tools. Currently, we use solutions from Covalent and Huddle01. 
    
Documentation may be accessed here  https://resolutio.notion.site/lite-paper-96bb6e96db1842cd866a81bc480c8988
 
### 3  b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes! We have been part of the FVM mainnet cohort, and deployed our contracts on the mainnet
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---           | :---                       | 
| 1. |  Resolve Edge Cases - Improve the smart contracts to resolve the edge cases |  Work on our FVM Deployed smart contracts to include new functions, to handle identified edge cases |  10 June 2023    | 
| 2. |  Adopt encrypted data storage solutions  |  Research on solutions which facilitated data to be encrypted and stored such as ETF by FileMarket ( and other solutions) and implement them |  24 June 2023            | 
| 3. |   resolutio API - Build an API for _resolutio_ so that users on other platforms can directly resolve disputes within such platforms ( eg. marketplaces, metaverses, etc. | Make available a smart contract function of dispute resolution, through APIs.   |   20 July 2023     | 
| 4. |  resolutio whitepaper    |  Publish _resolutio_ whitepaper   |  20 July 2023   | 
| 5. |  Create NFT repository    |  Create a Web3 database to record all the decisionNFT data. ( First, we will research existing solutions on which we can build the database. Thereafter, we will implement it). This is a comprehensive art NFT database where users may access information pertaining to any NFTs, such as their dispute history, authenticity, IP License, creator wallet reliability, etc. This will be partly based on the history of disputes resolved on resolutio. |    12 August 2023 | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
yes!
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
Yes. We started with the Encode X Filecoin NFT Hackathon where we won 3rd prize

**Other relevant Links**
Twitter: https://twitter.com/resolutio_nft?lang=en
Medium ( creator’s rights awareness blog): https://medium.com/resolutio-nft
Discord: https://discord.gg/y6U7KVvptu
LinkedIn: https://www.linkedin.com/company/dec-resolutio/
Documentation: https://www.notion.so/lite-paper-96bb6e96db1842cd866a81bc480c8988

  
### Additional questions:
Sneha Vijayan
_resolutio_ lead ( co-founder )
snehavij20@gmail.com
https://github.com/snevii

_Zarreen Naowal Reza_
AI lead ( co-founder)
zarreen.naowal.reza@gmail.com
https://github.com/znreza

Rashmi V Abbigeri
Chief Technical Officer
rashmi.webdev@gmail.com
https://github.com/Rashmi-278

Ogubuike Alexandra Ozioma
Smart Contract Developer
ogubuikealex@gmail.com
https://github.com/king-Alex-d-great

Bestin John
Front End Developer
mailto:mail.bestinjohn@gmail.com
https://github.com/bestii

Anish Praveen
Front End Developer
-mailto:anishprvn@gmail.com
https://github.com/anishprvn

* How did you learn about our microgrant program?
via FVM Mainnet Cohort

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
  Encode X Filecoin NFT Hackathon
  
  * Please link to your hackathon submission
  https://www.youtube.com/watch?v=AOn97e8c2JQ
  ( Only presentation link is available)

**Comment by trruckerfling** [comment]
> Create NFT repository

@snevii  Could consider using tableland on FEVM to create this repo! https://www.twitch.tv/videos/1810562731

**Comment by snevii** [comment]
@trruckerfling Already on it. Seems like a great integration for us !

**Comment by eshon** [comment]
@snevii Can you please provide a link to your latest demo?

**Comment by snevii** [comment]
hi @eshon 
https://fvm.resolutio.ai/

Sorry it took as a few days. Our latest demo website was on hyperspace, and we had to move to calibration net.

Note: To access the arbiter page, you're wallet needs to be whitelisted. If you'd like to check the other side of the resolution aspect, just let me know. I'll whitelist your wallet. 

If you'd like a video demo, we can record that and send a link as well.

**Comment by ErinOCon** [comment]
Hi @snevii, this microgrant has been approved! We will send an email to confirm payment details. As mentioned above, the following are required for this microgrant:

- A fully working user-facing demo with nice UX that anyone can easily use
- Deployment to Filecoin mainnet + a testnet
- Interesting use of FVM, especially what's unique to Filecoin (for example, via the Filecoin Solidity API, FVM use cases, or Bacalhau x FVM, etc.)

Please be in touch with any questions!

**Comment by snevii** [comment]
Thank you !!!!  Excited to start building again !!! :D

**Comment by ErinOCon** [comment]
Hello @snevii, I hope you are doing well! Do you have an update on project progress?

**Comment by snevii** [comment]
Hey @ErinOCon & @eshon  
We have made significant progress. You'll find more details here
https://github.com/resolutio-ai/resolutio-chatbot-api
We've deployed a new website as well:https://resolutio.ai/
But the FVM functionalities we've built and deployed are currently only on the dev environment.  I will email the details.

**Comment by eshon** [comment]
Hi @snevii - Thanks for your update!

I'm having problems running your code:

<img width="642" alt="Screen Shot 2023-12-13 at 3 24 11 PM" src="https://github.com/filecoin-project/devgrants/assets/1017762/745422f3-27b6-4c87-a8c5-cff0de2e5abf">

For the final deliverable, we need to see a live demo that works on Filecoin's Calibration testnet or mainnet. Can you please get your dapp hosted (somewhere like Netlify or Fleek should have a free tier) and let us know?

**Comment by eshon** [comment]
Hi @snevii - any update on the final demo?

**Comment by snevii** [comment]
hi @eshon ! 
Sorry for the delayed reply. We've been working on the final demo for sometime now, but we're facing some difficulties on front end integration. The primary one being, difficulty integrating magic auth to FVM

We're working this out and hope to get back to you with the final demo asap. 

You'll find that while our Dispute Resolution Demo is running well on https://fvm.resolutio.ai/, we're having some difficulties with the evidence protection tool and the feed. I will update you as soon as we're able to tackle it and deploy it.

**Comment by ErinOCon** [comment]
Hello @snevii, I hope you are doing well! Do you have any new updates available?

**Comment by snevii** [comment]
Hi @ErinOCon 

We're still having some trouble with the evidence part. 
We have deployed it here: https://demo.resolutio.ai . It is partially working now. 
We will get back to you in a few days, with the resolved issue.

**Comment by snevii** [comment]
hi @ErinOCon 
Because we're continuously  hitting roadblocks with evidence Protection part of things, we thought it would be best to re-focus on the Dispute Resolution model. 
You'll be able to find our progress on the Evidence part ,(although not complete), in our Dev environment ( emailed to you). 

As regards Dispute Resolution, we've started internal testing, and solving existing issues. It was originally deployed on FVM ( Can be accessed here https://fvm.resolutio.ai/ ). We're also in the process of shifting to Lighthouse for our evidence storage needs. This is something we'd experimented with for Evidence Protection part of things, and thought it would work well for Dispute Resolution as well. 

As a user, there are 2 roles in which you can participate. As a disputant, and a juror. If you'd like to test out a dispute as a juror, please let me know. I will allow-list your wallet address. As a disputant though, you shouldn't have any trouble. 

Our plan currently is to polish dispute resolution model ( currently deployed on FVM testnet), publish it to the mainnet and make it publicly available. Once we've successfully done that, we'll return to the Evidence Protection aspect. If we continue to hit roadblocks again, I hope it will be ok to reach out to you for guidance. 

We hope https://fvm.resolutio.ai/ meets the requirement of the demo, as the dapp deployed on the laterst FVM testnet, while we continue to refine our product. If there are additional requirements, please let us know.
