### ISSUE TITLE
Open Grant Proposal: Bagel DB

### ISSUE THREAD

**Issue by BidhanRoy** [filecoin-project/devgrants#1556]
# Open Grant Proposal: `Bagel DB`

**Project Name:** Bagel DB

**Proposal Category:** Developer and data tooling

**Individual or Entity Name:** Bidhan Roy

**Proposer:** @BidhanRoy

**(Optional) Filecoin ecosystem affiliations:** N/A

**(Optional) Technical Sponsor:** Jonathan Victor

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

In the burgeoning world of AI, managing high-dimensional vector embeddings poses a significant challenge. Despite advancements in centralized vector databases like Pinecone, limitations persist—barriers to open-source indexed data sharing, collaboration, and permissionless access control being paramount among them. Such impediments hinder the self-improvement capabilities of autonomous AI systems. The revolutionary BagelDB, a decentralized vector database, emerges as a promising solution to these challenges, creating an ecosystem that nurtures open-source collaboration and indexed data sharing.

This project aims to leverage Filecoin/IPFS as a base storage layer for BagelDB, with a focus on utilizing the Filecoin virtual machine for robust storage management. We aim to dissect the mechanics of BagelDB, emphasizing its potential as an antidote to centralized system drawbacks, thereby heralding a new era in vector databases.

More details at https://paper.bageldb.ai/

## Impact 

The advent of this project marks a significant inflection point for the Filecoin, IPFS, and related ecosystems. The current pain points—limited open-source data sharing and collaboration, resource intensity, censorship vulnerability, and data sovereignty issues, all rooted in the centralization of vector databases—are precisely what this proposal targets. We're steering towards a future where these ecosystems are bolstered by decentralization, thereby enabling efficient resource sharing, collaborative indexing, and open-source data sharing.

The benefits of actualizing this vision are substantial. We can drive down computational and storage costs, foster a culture of open-source collaboration, uphold data sovereignty, and resist censorship. Conversely, failing to navigate these challenges could constrain innovation, limit growth potential, and stifle the development of AI applications in unrestricted environments.

The proposed project has the potential to transform the AI landscape, particularly in the realm of data management. Success looks like BagelDB becoming a powerhouse for open-source collaboration, global accessibility, fault tolerance, and resilience in AI data management. With Filecoin/IPFS as the base layer, we can position it as the premier hub for AI data storage, enriching the Filecoin ecosystem and drawing further innovative projects into its orbit.

In essence, our proposal isn't merely a leap in technological innovation—it's a stride towards a more collaborative, accessible, and resilient future in AI. It's not just about building a database—it's about creating a fertile ground for AI innovation, where everyone, irrespective of their scale, can contribute, learn, and grow. By supporting this project, you're not just investing in technology; you're investing in a vision for a more inclusive and decentralized AI future.

## Outcomes

The principal outcomes of this project will be thorough technical research and an in-depth technical design of BagelDB using Filecoin/IPFS as the base storage layer. The design will articulate how to leverage the Filecoin Virtual Machine (FVM) for effective data management and privacy control through smart contracts. Project success will be measured by the completion of this comprehensive design, one that effectively integrates Filecoin/IPFS and the FVM.

## Adoption, Reach, and Growth Strategies

Our target audience encompasses AI researchers, developers, and organizations keen on leveraging decentralized vector databases. To engage this extensive audience, we will disseminate our research findings and technical design through academic and industry conferences, workshops, and online platforms. We'll onboard our initial users through hands-on tutorials, demonstrations, and round-the-clock technical support.

## Development Roadmap

Milestone 1: Technical Research
Expected Outcome: Detailed technical research on Filecoin/IPFS as a base storage layer and the utilization of FVM for data management.
Team: 2 researchers and developers.
Funding: $5,000
Timeline: 1 month, ending July 2023

Milestone 2: Design Development
Expected Outcome: Completion of the technical design of BagelDB leveraging the outcomes of Milestone 1.
Team: 2 researchers and developers.
Funding: $7,000
Timeline: 1 month, ending August 2023

Milestone 3: Review and Refinement
Expected Outcome: Review and refinement of the design, ensuring its alignment with technical and user requirements.
Team: 2 researchers and developers.
Funding: $3,000
Timeline: 2 weeks, ending mid-September 2023

## Total Budget Requested

| Milestone # | Description | Deliverables | Completion Date | Funding |
|---|---|---|---|---|
| 1 | Technical Research on Filecoin/IPFS and FVM for BagelDB | Detailed Technical Research Report | July 2023 | $5000 |
| 2 | Design Development for BagelDB using Filecoin/IPFS and FVM | Comprehensive Technical Design | August 2023 | $7,000 |
| 3 | Review and Refinement of Design | Refined Technical Design | Mid-September 2023 | $3,000 |
| **Total** | | | | **$15,000** |

## Maintenance and Upgrade Plans

Our team is dedicated to the long-term maintenance and improvement of this project. Post the design phase, we aim to transition into the development and implementation stage, for which we will seek additional funding and resources. We plan to regularly evaluate the system performance and user feedback, making necessary upgrades to keep abreast with the advancements in AI, machine learning, and blockchain technology. In addition, we will continue to collaborate with the open-source community to harness collective intelligence, ensuring that our system remains cutting-edge, resilient, and efficient.

# Team

## Team Members
Bidhan Roy - Founder & Lead Engineer
Mesbah Tanvir - Engineer

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/bidhanr/
https://www.linkedin.com/in/mesbahtanvir/

## Team Website
https://paper.bageldb.ai/

## Relevant Experience

With nearly a decade of hands-on engineering experience, I am bringing a unique blend of AI infrastructure and blockchain knowledge to BagelDB. My tenure as the technical lead for the Alexa AI infrastructure at Amazon, where I successfully delivered machine learning models to Alexa devices worldwide, has equipped me with a deep understanding of the intricate demands of AI. At the same time, my work in web3, leading the ecosystem for one of the prominent L1s, has honed my proficiency in the realm of blockchain. This unique amalgamation of expertise is fundamental for a decentralized AI data infrastructure project like BagelDB. Furthermore, my experience as a technical lead for Instacart's data pipeline, one of the world's largest retail databases, aligns perfectly with BagelDB's goal to transform how vector databases are managed. Together, we will pioneer a new era of AI data storage, making Filecoin the epicenter of this revolution.

## Team code repositories

Several repositories are available at my github profile @BidhanRoy

# Additional Information
How did you learn about the Open Grants Program?
I learned about the Open Grants Program through my interactions with the Protocol Labs team. I had the privilege of conversing with Erin O'Connor at the Filecoin event at Consensus 2023. Additionally, I had an insightful online conversation with Brad Holden. Both of them recommended the Grants Program as an excellent opportunity for BagelDB.

Please provide the best email address for discussing the grant agreement and general next steps.
For further discussions about the grant agreement and general next steps, I can be reached at bidhan@bageldb.ai

Please include any additional information that you think would be useful in helping us to evaluate your proposal.
More technical details about the project BagelDB can be found here https://paper.bageldb.ai/

**Comment by ErinOCon** [comment]
Hi @BidhanRoy, thank you for your proposal and for your patience with our review. We will not be proceeding with an open grant at this time, but you may have an interest in applying for [a microgrant ](https://github.com/filecoin-project/devgrants/blob/master/microgrants/microgrants.md) to support this project at a smaller scale. 

Wishing you the best as you continue to build!
