### ISSUE TITLE
Open Grant Proposal: FNS

### ISSUE THREAD

**Issue by amncjf** [filecoin-project/devgrants#1557]
# Open Grant Proposal: FNS

**Project Name:** Filecoin Name Service

**Proposal Category:** Applications

**Individual or Entity Name:** Fildomains 

**Proposer:** amncjf

**(Optional) Filecoin ecosystem affiliations:** N/A

**(Optional) Technical Sponsor:** N/A

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

Our goal is to establish a fully open-source, complete, sustainable operation,
everyone can participate in and use and gain benefits,
and a name system on Filecoin that is fully compatible with ENS. 

More details at https://fildomains.com/

## Impact 

We can't remember the address on Filecoin, CID on IPFS, but we can remember names like alice.fil, and FNS can parse names like alice.fil into addresses on Filecoin, Ethereum, Bitcoin..., Of course, you can also use easy to remember the name to resolve the cid path of IPFS, set the name of the avatar, import DNSSEC and other functions...

FNS is an essential part of the Filecoin ecosystem and will lay a solid foundation for the development of the Filecoin ecosystem

The name of FNS can be used as an NFT transaction, the wallet can use the name of FNS to transfer money, enter the name of NFS in the browser to browse the website on IPFS

## Outcomes

1. You can apply for the name. Several users have applied for the name
2. The economic system runs successfully, and the user who applies for the name gets the FNS reward.
3. DNSSEC The system can import the DNSSEC domain name

## Adoption, Reach, and Growth Strategies

We will continue to promote and encourage more users to use FNS

## Development Roadmap

1. In late April, our product was released
2. matemata Data System in June
3. The document system was released in July

## Total Budget Requested

$100,000

## Maintenance and Upgrade Plans

Our team is committed to the long-term maintenance and improvement of this project. Beyond the release phase, our goal is user growth and continuous improvement, for which we will seek additional funding and resources. We plan to regularly evaluate system performance and user feedback and make the necessary upgrades to keep up with Filecoin's progress. In addition, we will continue to work with the open source community to harness the collective wisdom to ensure that our systems remain cutting-edge, resilient and efficient.

# Team

2 Founder Team Members

## Relevant Experience

Since 2016, We have developed ethereum public chain. During this period, We have developed the past centralized exchange, public chain, blockchain browser, etc

## Team code repositories

https://github.com/fildomains

# Additional Information
To discuss grant agreement and general next steps please contact [amncjf@gmail.com](mailto:amncjf@gmail.com)

FNS official website: https://fildomains.com/

**Comment by ErinOCon** [comment]
Hi @amncjf, thank you for your proposal and for your patience with our review. We will not be moving forward with a grant at this time, but we are wishing you all the best as you continue to build!
