### ISSUE TITLE
Next Step Microgrant: Quidli - Discord Reward Bot

### ISSUE THREAD

**Issue by Lukerio** [filecoin-project/devgrants#1558]
### 1. What is your project, and what problem does it solve? (max 100 words)
We help digital organizations (companies, teams, projects, DAOs, etc.) to better collaborate by building a platform to share crypto as incentives and rewards with contributors directly in the apps you're already using for coordination (Slack, Discord, etc.).
Our mission is to offer a composable and user-friendly tool for organizations to use, share and access crypto/web3 as micro-rewards with little-to-no friction.

### 2. Project links
  
• Website: https://quid.li/ 
• Youtube: https://www.youtube.com/channel/UCsek4oSa_GipcBfaQQDeSrQ 
• Linkedin: https://www.linkedin.com/company/quidli/ 
• Twitter: https://twitter.com/quidliprotocol 
• Medium: https://medium.com/quidli
• GitHub: https://github.com/quidli 

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
We propose to you to build a light integration of FileCoin to Quidli by adding FIL token to our API and hosted app environment. This will enable you to seamlessly distribute FIL as rewards to the top active participants in your community directly in your Slack or Discord.
In addition to helping you internally share FIL within FileCoin, this integration lets us offer FIL to our user base of 1000+ organizations as an option via Quidli’s open token platform.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
Once completed, FIL will be available as an option on:
1. Quidli web app
2. Quidli Slack app
3. Quidli Discord app
4. Any subsequent integrations built by Quidli

Through this initial partnership, we’d like to help Filecoin build an awesome community and ecosystem by enabling you to effectively boost community engagement using token incentives. Sharing more tokens with community members can help you to establish a positive alignment flywheel leading to more contributions and ultimately growth towards your main mission and objectives.
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|

| 1. |  Review of the technical documentation (blockchain, smart contracts, tokens, etc.).	 | Green light from our team to move to the token integration step.  |  1 week | 
| 2. | Testing to ensure the tokens are functional and usable within our environment | Successfully integrated FileCoin into Quidli’s micro on-ramp environment |   1 week     | 
| 3. |  Review the integration with the grant team | Validation of the deliverable by the FileCoin grant team |  1 week | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes, we agreed to share our progress directly on Discord
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Justin Ahn - CEO 
Previous experience: Helped launch high-growth e-commerce ventures in Southeast Asia, notably ZALORA & LAZADA Vietnam as EiR @ Rocket Internet 
LinkedIn profile link: https://www.linkedin.com/in/ahnjustin/ 
Role: Justin is the project coordinator 

Guillaume Figielski - CTO 
Previous experience: As blockchain engineer (incl. Solidity), launched ChainImpact, one of the first blockchain dev studios in France. Senior full-stack developer @ French multinationals including Airbus, Orange, and Peugeot.
LinkedIn profile link: https://www.linkedin.com/in/guillaume-figielski/ 
Role: Guillaume oversees token integration and product management 

Luke Vignal - Head of Business Dev 
Previous experience: Account Manager @Zendesk, Ex-Forrester 
LinkedIn profile link: https://www.linkedin.com/in/luke-vignal/ 
Role: Will be in charge of the partnership coordination and marketing efforts

* How did you learn about our microgrant program?
Website

* If your project was created as part of an event or hackathon: 
* No hackaton relation

**Comment by ErinOCon** [comment]
Hi @Lukerio, thank you for your proposal and for your patience with our review process. This is an interesting project and was considered for a number of our microgrant cycles. Unfortunately, we will not be moving forward with a grant at this time. 

Please feel welcome to contact our team at [grants@fil.org](mailto:grants@fil.org) with any questions. Wishing you the best as you continue to build!
