### ISSUE TITLE
Friendzone Grant Submission

### ISSUE THREAD

**Issue by LuisNeves05** [filecoin-project/devgrants#1559]
# Open Grant Proposal: Friendzone

**Project Name:**

**Proposal Category:** `Applications`, `Integrations`

**Individual or Entity Name:** Friendzone

**Proposer:** LuisNeves05

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** "Yes"

# Project Summary

Looking for a fun and engaging way to connect with friends, family, and even strangers? Look no further than Friendzone – the app that lets you challenge other users and get rewarded for it!

### Mission
Since its inception, Friendzone has been a huge hit with the local partygoers. The vibe is always high and immaculate. Everyone is welcomed with open arms. The founders of Friendzone believe that no one should ever feel left out or alone, which is why they created this party in the first place, by friends for friends and it's not just limited to Lisbon either – Friendzone has traveled from north to south of the country, and even ventured into Madrid, Spain!

Now, Friendzone is taking its concept to the next level by becoming an app. This app will allow users to challenge each other and get rewarded for it! It's not just about partying anymore, but about creating a community where people can come together and have fun in a unique way.

### Vision

We´ve started this company because we want to make the first social network that really aggregate value to the community!

## Outcomes

Milestone 1
Product development: 
- NFT as an Audio and Video  
- Abuse content analysis 
- Share NFTs as a deep link into the dApp  
- Share Profiles as a deep link into the dApp  
- Revamp Smart Contracts | Introduce new staking model 

Milestone 2
Product development and Business/Marketing development 
Product development:
- Mainnet integration 
- Invite code system 
- Reward System for inviting new users
Business and Marketing: 
- Create premium social media content 
- Boost community on social media to a total of 5000 followers in total 
- 1000 users in the waitlist for the launching of Beta Public Launch

Milestone 3
Launch and product development 
- Direct Messaging | Allow decentralized and encrypted direct messaging inside the App 
- Develop or Integrate an Internal Wallet 
- On Ramp (Buy NEFT Tokens in an easy and seamless way) 
- Publish App on Apple Store and Android Play Store
- Challenges v1 and Beta launch

## Adoption, Reach, and Growth Strategies

**FRIENDZONE Pitch Deck** [https://docs.google.com/presentation/d/1y1syktEv01upvfL_e8W1iPs_KCTCbym0/edit?usp=share_link&ouid=114731208641139401259&rtpof=true&sd=true](https://docs.google.com/presentation/d/1y1syktEv01upvfL_e8W1iPs_KCTCbym0/edit?usp=share_link&ouid=114731208641139401259&rtpof=true&sd=true)

**FRIENDZONE Business Plan**

[https://docs.google.com/presentation/d/1zxkeACkK57sR6nsFxyk9BsY8e2oGgrUz/edit?usp=share_link&ouid=114731208641139401259&rtpof=true&sd=true](https://docs.google.com/presentation/d/1zxkeACkK57sR6nsFxyk9BsY8e2oGgrUz/edit?usp=share_link&ouid=114731208641139401259&rtpof=true&sd=true)

# **WHO WE ARE?**

Founded as a party in October 2021 by a group of friends in Lisbon, Portugal. Friendzone’s concept is all about inclusivity, and the DJs who play there showcase a variety of music styles, from Hip Hop to R&B, Reggaeton, and funk.

# **BY FRIENDS, FOR FRIENDS!**

Since then, Friendzone has been a huge hit with the local partygoers. The vibe is always high and immaculate. Everyone is welcomed with open arms. We believe that no one should ever feel left out or alone, which is why we created this party in the first place, by friends for friends!

# **IT’S A MOVEMENT!**

We are not limited to Lisbon either – Friendzone has traveled from north to south of the country, and even ventured into Panthera in Madrid, Spain. We want to go around the world in a way for people to connect, have fun, and have a feeling of belonging. We are set to become even bigger and better than ever before.

Now, Friendzone is taking its concept to the next level by becoming an app. This app will allow users to challenge each other and get rewarded for it! It's not just about partying anymore, but about creating a community where people can come together and have fun in a unique way.

In a world where it's easy to feel isolated and disconnected, Friendzone is a breath of fresh air. It's a concept that celebrates friendship, inclusivity, and fun. Even thought the name 'friendzone' means otherwise, whether you're in Lisbon, Madrid, or anywhere else in the world, Friendzone is a reminder that we're all in this together.

Overall, Friendzone is more than just a party – it's a movement. It's a way for people to connect, have fun, and have a feeling of belonging. And with the app and more surprises launching in the near future, Friendzone is set to become even bigger and better than ever before.

**THE PROBLEM**

Social networks are centralized, and most of the value created is controlled and belongs to an entity, paid by advertisers for our attention, while we fight for followers and likes as a measurement of perceived success, fame, and ego reinforcement. In the end of the day, only users with a lot of traction regarding views, followers and likes can somehow monetize their content. 

In a world where it's easy to feel isolated and disconnected, Friendzone is a breath of fresh air. It's a concept that celebrates friendship, inclusivity, and fun. Even thought the name 'friendzone' means otherwise, whether you're in Lisbon, Madrid, or anywhere else in the world, Friendzone is a reminder that we're all in this together.

**THE SOLUTION**

Looking for a fun and engaging way to connect with friends, family, and even strangers? Look no further than Friendzone – the app that lets you challenge other users and get rewarded for it. 

You can challenge anyone on the app, including your crazy ex or your favorite celebrity. Who knows if Ronaldo will score that goal or Justin Bieber will sing for you? You might just get a response and start a new connection with someone you admire.

With Friendzone, challenges are more than just words on a screen. Users can react to challenges by capturing their facial expressions, making the app more real and engaging than ever before. Whether you're laughing, crying, or just feeling a little too crazy, Friendzone let’s you show your true self.

**COMPETITIVE ADVANTAGE**

CRYPTO-BASED REWARDS

Built on blockchain technology and crypto-based rewards, Friendzone is the ultimate social app for anyone who loves to have fun in a unique way and connect with others. Whether you're looking to challenge your best friend to do something crazy in the club or want to challenge your favorite singer or band to a dance-off or even sing your favorite song, Friendzone makes it easy to connect and compete.

Once the challenge is completed, the user earns a certain amount of FZs (cryptocurrency), which can be exchanged for traditional currency.

All published Challenges are NFTs!

GEO-LOCATION

With geo-location functionality you can find users near your location and even if you're not in the same place as your friends or family, you can still connect with them and challenge them.

Remember that cute looking person you saw that afternoon waiting for the bus? Maybe that was your soulmate, and you can find that person later in the app by checking the time you passed by

Get Connected and Have Fun with 'Friendzone' - The App That Challenges People!

## Development Roadmap

Already mentioned above

## Total Budget Requested

15k + 15k + 20k = 50k USD

Milestone 1
Product development: 
- NFT as an Audio and Video  
- Abuse content analysis 
- Share NFTs as a deep link into the dApp  
- Share Profiles as a deep link into the dApp  
- Revamp Smart Contracts | Introduce new staking model 

Milestone 2
Product development and Business/Marketing development 
Product development:
- Mainnet integration 
- Invite code system 
- Reward System for inviting new users 

Business and Marketing: 
- Create premium social media content 
- Boost community on social media to a total of 5000 followers in total 
- 1000 users in the waitlist for the launching of Beta Public Launch

Milestone 3
Launch and product development 
- Direct Messaging | Allow decentralized and encrypted direct messaging inside the App 
- Develop or Integrate an Internal Wallet 
- On Ramp (Buy NEFT Tokens in an easy and seamless way) 
- Publish App on Apple Store and Android Play Store
- Challenges v1 and Beta launch

## Maintenance and Upgrade Plans

We're focused on long term success, we plan on bootstraping Friendzone and creating buzz around it. After that, we want to scale the app to have worldwide use, always coming up with new features.

# Team

## Team Members

João Domingos
Valter Silva
Andreas Vilela
Luis Neves
Gonçalo Marques
João Rodrigues
João RIbeiro

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/joaofriendzone/
https://www.linkedin.com/in/valtersilva93/
https://www.linkedin.com/in/andreasvilela/
https://www.linkedin.com/in/luisneves05/
https://www.linkedin.com/in/gmarquesetr/
https://www.linkedin.com/in/jo%C3%A3o-rodrigues-a22150153/
https://www.linkedin.com/in/joaoribeiropt/

## Team Website

https://friendzone.global

## Relevant Experience

https://www.notion.so/friendzoneapp/ONE-PAGER-a9e9eb5e18d044de82f2f3f5f874ad87?pvs=4#a09542d9b1174b24b30a3b13b35e1820

# Additional Information

info@friendzone.global

**Comment by ErinOCon** [comment]
HI @LuisNeves05, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant at this time. 

Wishing you all the best as you continue to build!
