### ISSUE TITLE
Filecoin Automation System-graphical interface

### ISSUE THREAD

**Issue by zcfil** [filecoin-project/devgrants#1581]
# Open Grant Proposal: Graphical operation and maintenance of filecoin

**Project Name:** Filecoin Automation System
**Proposal Category:** Applications

**Individual or Entity Name:** Shenzhen Zhongchuang System Technology Co., Ltd.

**Proposer:** zcfil

**(Optional) Filecoin ecosystem affiliations:** Notary 

**(Optional) Technical Sponsor:** n/a

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary
This project is developed and constructed based on the filecoin business ecology. It is a one-stop service platform for filecoin storage providers to realize automatic deployment, automatic management, reduce operation and maintenance costs, and improve operation conversion efficiency, so as to contribute to the development of filecoin ecology. Provide some services within our ability.

## Impact 
1. The main pain points to be solved by the project:
(1)Solve the problem of high barriers to entry for storage providers: fil ops system integrates filecoin-related technologies to easily and effectively complete project deployment and business operations for ordinary operation and maintenance personnel.
 (2)Reduce storage costs: Storage providers can reduce costs through fine-grained management of storage resources, automated operation and maintenance, and improved storage service quality through the fil ops system.
 (3)Enhance business stability: The fil ops system integrates real-time monitoring and alarm functions. Through daily inspection modules and high-availability monitoring modules, custom monitoring strategies can be used to comprehensively monitor business processes and results or hardware operation and utilization. Real-time monitoring ensures that faults are discovered and dealt with immediately to ensure business stability.

4. If the project is successful, it will be able to help the ecology of filecoin, allowing more people who pay attention to filecoin to join in at a lower cost and lower threshold through the platform's functions, and provide services for the community.
5. If we do not do it right, we will lose part of the research and development costs. At the same time, we will continue to find problems, continue to improve research and development, and continuously improve the competitiveness of the project to meet the needs of the market and provide services for the community.
6. The fil ops system aims to provide business-related services and solutions for storage providers in the filecoin ecosystem, deepen and expand the role of storage providers, lower the entry threshold and operational success of storage providers, thereby promoting the filecoin ecosystem storage service.
7. The criterion for the success of the fil ops system is to allow individuals or small groups who want to become storage providers to realize and join the filecoin ecosystem at any time through this platform.

## Outcomes

1. The final result of the project: through the integrated functions of this platform, the deployment and operation of the equipment functions required by the role of storage service provider will be realized.
The main functions are: device environment initialization (oplian and oplian-gateway), device initialization (computer room and host), device testing, automatic deployment (lotus, miner, worker, storage), scheduling management (task control, sector management, sector Life cycle management, sector recovery), C2 cluster;
Auxiliary service functions include: monitoring center (custom policy), alarm center (hardware monitoring and business monitoring), regular inspection, job platform (script execution, file distribution, file management);

2. Our team will pass the self-test verification, and after 2-3 months after passing the self-operation verification, and there will be no major bugs during the self-operation process, the total number of small and medium BUGs should not exceed 130, and invite friends and business customers after synchronous BUG repairs Verify together for 1-2 months. During the verification period, there are no major BUGs, and the total number of small and medium BUGs does not exceed 30, which defines the successful launch of this project.

## Adoption, Reach, and Growth Strategies

1. Our target audience is storage providers in filecoin, and people or organizations who intend to join the filecoin community. Currently keeping in touch with all parties through community channels.

2.We will open source and use it for free to all members through the community platform, keep an eye on the development of filecoin, update and optimize our system at any time to meet the needs of the market.

3.We also had contact with some sps offline before, and learned about some needs from them. We all looked forward to the early launch of this project, and expressed that we would become our first users.

4.Our twitter account has been promoting the filecoin ecology and has accumulated some fans. We will also use twitter to promote it.
https://twitter.com/zc_labs

## Development Roadmap
![image](https://github.com/filecoin-project/devgrants/assets/45065975/dbf47505-b5b6-4198-8ffc-ca6ce08aef85)

## Total Budget Requested

| Milestone # | Description | Deliverables | Completion Date | Funding |
|===|===|===|===|===|
![image](https://github.com/filecoin-project/devgrants/assets/45065975/b8ff43f0-58d7-48cd-abbd-4a1470ca8ceb)
![image](https://github.com/filecoin-project/devgrants/assets/45065975/d8f77415-ea33-4af0-95f1-422a34463f05)

## Maintenance and Upgrade Plans

1. We will build an operation team to handle the daily maintenance and upgrade of the system.
2. Regularly carry out safety assessments, discover potential safety hazards in time and fix them.
3. Establish a comprehensive communication and supervision mechanism to maintain communication with more users, developers and partners, while absorbing various excellent innovations and suggestions. Regularly provide information about system security and functionality, which helps to protect the rights of users and the normal operation of the system.

# Team

## Team Members

Nathan、Mike、Eagar、Sugar、Lex、Peter、Mandy

## Team Member LinkedIn Profiles

1.Nathan：https://www.linkedin.com/in/%E6%8C%AF%E5%86%9B-%E7%BD%97-4b7259279
2.Mike：https://www.linkedin.com/in/%E6%99%BA%E9%B9%8F-%E9%BB%84-b3b253279
3.Eagar：https://www.linkedin.com/in/%E6%AF%85-%E5%BC%A0-30bab9278
4.Sugar：https://www.linkedin.com/in/%E5%B7%BE%E8%8E%B2-%E7%94%B0-412254279
5.Lex：https://www.linkedin.com/in/%E6%96%87%E9%BE%99-%E6%96%B9-366255279
6.Peter：https://www.linkedin.com/in/%E6%99%B6%E8%89%BA-%E6%A2%81-87b3a3279/
7.Mandy：https://www.linkedin.com/in/%E6%99%93%E7%83%A8-%E7%BD%97-375255279

## Team Website
https://www.szfil.com/

## Relevant Experience

As an active community member, we have participated in filecoin testing since before the space race. Our team has rich experience in Filecoin storage and transactions, and understands the application scenarios and user needs of the Filecoin ecosystem. These experiences can help you better assess the strengths and weaknesses of the current Filecoin ecosystem, as well as formulate a good strategy for the overall planning of the project. Our team has built Filtrace browser, Hechuang cloud computing platform and other projects, for which we have accumulated a lot of valuable experience, which can help the team better understand how to better integrate Filecoin storage into projects , and bring the greatest value and benefits to users. We have experience in working in related fields, collect relevant data and implant blockchain technology expertise, then we will be able to better identify and follow up the latest technology and market trends and ensure that the project meets the overall planning of the standard.
To sum up, I think our team does have the experience and skills to build Filecoin-related projects, and can make good contributions to the success of the project, so it is a good choice.
In addition, we have also developed DC and CC sector recovery tools, remote C2 tools, and filecoin wallet offline signature tools. If necessary, we can provide the code
## Team code repositories

https://github.com/zcfil/hechuangfil.git
https://github.com/zcfil/hechuangfil-admin.git
https://github.com/zcfil/hechuang.git
https://github.com/zcfil/hechuang-h5.git
https://github.com/zcfil/filtarce.git
https://github.com/zcfil/filtarce-ui.git

# Additional Information
1.Through the filecoin community, I learned that openness is a subsidy program.
2.service@szfil.com
3.We come from the Zc laboratory team in Shenzhen, China and have been joining the Filecoin family since 2019. We have witnessed the development of the entire Filecoin network together, with the official release of Test Network 1- "Test Network 2-" Space Race.
Our team members have been conducting research around the filecoin ecosystem:
Current achievements: SP maintenance, filecoin blockchain data browser https://filtrace.ccFilecoin Automated operation and maintenance platform testing phase.
Future plan: Based on FVM product development, use ipfs/filecoin to achieve private cloud product development.
The operational costs of the team are relatively high, and the value generated by these projects is limited. We hope to receive community support and make more contributions to the development of the filecoin ecosystem

**Comment by smagdali** [comment]
total cost is $47,967

**Comment by ErinOCon** [comment]
Hi @zcfil, thank you for your proposal and for your patience! This application is still under review, but we expect to have more information available in the coming weeks. If we have any questions during the final stage of this review period, we will let you know!

**Comment by zcfil** [comment]
Okay, if there are any questions, we will actively cooperate and answer them. Thank you for your attention

**Comment by zcfil** [comment]
@smagdali @ErinOCon Okay, if there are any questions, we will actively cooperate and answer them. Thank you for your attention

**Comment by ErinOCon** [comment]
Hi @zcfil, thank you again for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
