### ISSUE TITLE
OpenFilWallet v2

### ISSUE THREAD

**Issue by llifezou** [filecoin-project/devgrants#1582]
# Open Grant Proposal: `OpenFilWallet v2`

**Project Name:** OpenFilWallet v2

**Proposal Category:** `app-dev`

**Individual or Entity Name:** `individual`

**Proposer:** `llifezou`

**(Optional) Filecoin ecosystem affiliations:** `no` 

**(Optional) Technical Sponsor:** `no`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:**  Yes

# Project Summary

The goal of OpenFilWallet is to become an easy-to-use miner HD wallet, which is convenient for users to initiate ordinary transactions and multi-signature transactions simply and safely. OpenFilWallet allows users to easily initiate transactions without importing private keys to guardian nodes. OpenFilWallet provides offline functionality, allowing it to act as an offline signature machine, providing maximum security.

OpenFilWallet provides a safe and simple way to send Filecoin transactions, and introduces the mnemonic function to facilitate account management, and ensures wallet security through encryption. The focus is to provide a simple multi-signature transaction experience, lower the threshold for using the multi-signature function, and promote network stability.

## Impact 

Provide an open source, safe and convenient multi-signature wallet to manage nodes and improve security.

- What pain points does this project seek to address? 
  - The lotus private key is not encrypted, a full node is required to initiate a transaction, and the multi-signature function is not easy to use.

- What are the benefits to getting this right? What are the risks of not getting this right?
  - It is safer and more convenient to initiate multi-signature transactions. and increasing the diversity of community tools
  - it can be achieved

- What impact will this project have in a specific vertical, market, or ecosystem? What does success look like? 
  - Promote the use of multi-signature functions to promote network security

## Outcomes

Please describe in detail what your final outcomes & deliverable(s) for this project will be. Include a specification of the project and what functionality the software will deliver when it is finished.

- Completed so far:
  - Support mnemonic words and private keys exported by lotus
  - The mnemonic and private key are encrypted and saved
  - The transaction is split into generate/sign/send, the transaction is not encoded and human readable
  - Support adding, modifying and deleting daemon node
  - Support query wallet balance, wallet list, multi-sig wallet details, multi-sig wallet list, etc.
  - Support f1/f3 wallets, multi-signature wallets, provide transfer, miner withdraw, change owner/worker/control and other functions
  - Support command line, support web ui
- Deliverables: Adaptation of command-line client and web UI
  - Support miner management, which will be more convenient to use.
  - Support hardware wallet, greatly improving security
  - Support the fevm account system, allow the creation of f4 address, and allow mutual transfers between f1/f3 and f4 (check whether the f4 address is a contract address when transferring money, and issue a warning)

Please describe how your team is measuring the success of your project and define the metrics being used

- A user-friendly documentation and strict code quality, as well as good testing

## Adoption, Reach, and Growth Strategies

Who is the target audience for your project? How large is this audience and how are you currently engaging with them?

- SPs and FIL holders

If applicable, how do you intend to onboard new users? If you are just starting to interact with your target audience, how will you onboard your first 10 users? Your first 100? 

- Continuously optimize the project. Solve any problems raised by users in a timely manner.

## Development Roadmap

Milestone 1 ( 10 weeks) ($4,000)

- Miner management
  - Allow users to increase miner (multiple are supported). Display miner information, including owner, worker, withdrawable amount, miner computing power, miner status and other information
  - It is more convenient to change the mine owner, change the miner, and withdraw the available balance
  - Adaptation of command-line client and web UI

Milestone 2 ( 12 weeks) ($5,000)

- Support hardware wallet
  - For security, supporting hardware wallet (Nano X / Nano S) is perfect. Supports creating hardware wallet addresses, displaying hardware wallets, and signing transactions with hardware wallets.
  - Adaptation of command-line client and web UI

Milestone 3 ( 10 weeks) ($4,000)

- Support the fevm account system
  -  allow the creation of f4 address, and allow mutual transfers between f1/f3 and f4 (check whether the f4 address is a contract address when transferring money, and issue a warning).
  - Adaptation of command-line client and web UI

Milestone 4 ( 7 days)($4,000)

- Wallet audit
  - Key security: random numbers, key generation, key encryption algorithms, key storage, signing transaction.
  - Front-end security: Whether there is an HTML injection vulnerability; whether there is a vulnerability that can obtain the server token and change the transaction receiving address.
  - Supply chain security: front-end and server-side dependency security.
  - Safety of use: Under the black box test, user funds are safe.
- Success indicator
  - no critical vulnerabilities
- Deliverables
  - Cooperate with the auditor's audit work, deal with the auditor's feedback in a timely manner, and ensure the audit progress.
    - For simple and moderately complex questions, I will deal with them in one day.
    - For very complex issues, I will also complete the fix in a few days.
  - Complete any security recommendations from auditors
  - Audit results protection
    - When the audit is completed, I will design the rules for adding functions, and distinguish between the new function branch and the audit branch to ensure that the audit results will not be destroyed.

## Total Budget Requested

| Milestone                       | Description                     | Deliverables                                                 | Completion Date | Funding |
| ------------------------------- | ------------------------------- | ------------------------------------------------------------ | --------------- | ------- |
| 1                               | Miner management                | miner management &command-line client & web UI               | 10/11/2023      | $4,000  |
| 2                               | Support hardware wallet         | support hardware wallet &command-line client & web UI        | 31/01/2024      | $5,000  |
| 3                               | Support the fevm account system | allow the creation of f4 address, and allow mutual transfers between f1/f3 and f4 | 10/03/2024      | $4,000  |
| 4                               | Wallet audit                    | Cooperate with the wallet to complete the audit and release the version. | 19/03/2024      | $4,000  |
| Total Budget Requested: $17,000 |                                 |                                                              |                 |         |

## Maintenance and Upgrade Plans

Provide maintenance for at least five years

# Team

## Team Members

https://github.com/llifezou

## Team Website

https://docs.openfilwallet.com/

## Relevant Experience

[fil-wallet](https://github.com/llifezou/fil-wallet)

[OpenFilWallet](https://github.com/OpenFilWallet/OpenFilWallet)

## Team code repositories

https://github.com/OpenFilWallet/OpenFilWallet

# Additional Information
How did you learn about the Open Grants Program?

- https://github.com/filecoin-project/devgrants

Please provide the best email address for discussing the grant agreement and general next steps

- llifezou@gmail.com

Please include any additional information that you think would be useful in helping us to evaluate your proposal

- [lotus contributor](https://github.com/filecoin-project/lotus/pulls/llifezou)

**Comment by ErinOCon** [comment]
Hi @llifezou, thank you for your proposal and for your patience! This application is still under review, but we expect to have more information available in the coming weeks. If we have any questions during the final stage of this review period, we will let you know!

**Comment by llifezou** [comment]
> Hi @llifezou, thank you for your proposal and for your patience! This application is still under review, but we expect to have more information available in the coming weeks. If we have any questions during the final stage of this review period, we will let you know!

@ErinOCon  Hi Erin, thanks. 
This is the last grant application for OpenFilWallet. After this application, if OpenFilWallet continues to add functions, I will bear all the costs. If you have any questions, please feel free to contact!

**Comment by realChainLife** [comment]
Hi @llifezou could you add Wallet Audit as a deliverable in the development roadmap. Please Include parameters for audit performance actions, and how issues will be resolved during the process.

**Comment by llifezou** [comment]
> Hi @llifezou could you add Wallet Audit as a deliverable in the development roadmap. Please Include parameters for audit performance actions, and how issues will be resolved during the process.

Hi @realChainLife I added Milestone 4. Let me know if there are any questions. Thanks

**Comment by ErinOCon** [comment]
Hi @llifezou, thank you again for your patience with our review. Unfortunately, due to budget constraints in our current climate, we are not able to move forward with a grant at this time. We appreciate the work you are completing and are wishing you all the best as you continue forward!

If you have any questions for our team, please feel welcome to contact us at grants@fil.org.

**Comment by llifezou** [comment]
@ErinOCon @realChainLife  Thanks for the explanation. Thanks to the grants team for everything, I will continue it, thanks again.
