### ISSUE TITLE
MetaLinkFilecoin(plugin) to enable MetaMask users interaction with filecoin dapps.

### ISSUE THREAD

**Issue by STFILMan** [filecoin-project/devgrants#1585]
### 1. What is your project, and what problem does it solve? (max 100 words)
MetaLinkFilecoin(plugin) to enable MetaMask users interaction with filecoin dapps.

Develop plug-ins based on MetaMask Snaps, expand MetaMask to support f1 addresses,
support balance query, transfer, message signature, message uploading, contract interaction and other operations.
It makes it easier for users to enter the Fvm ecosystem without having to consider the support of 0x addresses and exchanges.

### 2. Project links

Link to Github repo: https://github.com/stfil-io/metalink-filecoin
Link to demo or website: https://stfil.io/
License: MIT

### 3. a) How is IPFS, Filecoin, or related technology used in this project?
This project is developed based on MetaMask Snaps and expands the capabilities of Filecoin dapps,
which uses Filecoin's f1 address generation and message signature.
Public gateway API services: balance query, message GAS estimation, message on-chain, transaction query etc.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes

### 4. How will you improve your project with this grant? What steps will you take to meet this objective?

| Number | Grant Deliverable                      | Briefly describe how you will meet deliverable objectives               | Timeframe (within 3 months) |
| :---   |:---------------------------------------|:------------------------------------------------------------------------|:----------------------------|
| 1.     | MetaLinkFilecoin Snap plug-in tool     | Publish MetaLinkFilecoin npm package & Provide website                  | 1 month                     |

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
If I selected for the Grant our team will report every week with your teams and will update you weekly with every changes and further planning.

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

| Name    | Email                   | Github                        | Role       |
|:--------|:------------------------|:------------------------------|:-----------|
| Amiable | grw1215884602@gmail.com | https://github.com/amiable169 | Developer  |

* How did you learn about our microgrant program? Participated in
* If your project was created as part of an event or hackathon: No
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by eshon** [comment]
Hi @STFILMan - As we discussed on a call before, the FilSnap is currently going through a security audit and will be launched in the Snaps Directory very soon. It will support all of the features you mentioned above. Because of this, the MetaLink Filecoin Plugin is not necessary.

**Comment by ErinOCon** [comment]
Hi @STFILMan, I have closed this issue, but please do not hesitate to be in touch with any questions.
