### ISSUE TITLE
Next Step Microgrant: Daggle

### ISSUE THREAD

**Issue by leostelon** [filecoin-project/devgrants#1588]
### 1. What is your project, and what problem does it solve? (max 100 words)
Provide a solution to centralised, slow and expensive computation platforms like Google Colab, AWS Lambda and other similar things via FVM and Bacalhau.

A Compute Over Data platform lets users offload their extensive CPU workloads to Bacalhau, an off-chain compute network closely packed to IPFS storage, making file retrieval faster. Users can use our platform's features, like training Tensorflow models, uploading data from web2 to web3 storage using Spheron, running Python or Node.js scripts and many more in just a few clicks.

Easy-to-use marketplace allows users to upload their Actions in the future and even monetise them if needed using DAOs. Actions are CLI commands that can be fed into Bacalhau. They can also manage bacalhau jobs, check the status or results, redeploy jobs, and many more.

### 2. Project links
  
Link to demo or website: https://daggle.xyz/
Link to Github repo: 
 - https://github.com/leostelon/daggle-server
 - https://github.com/leostelon/daggle-client

License: 
 - https://github.com/leostelon/daggle-server/blob/main/LICENSE
 - https://github.com/leostelon/daggle-client/blob/main/LICENSE
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

We have many features impacting IPFS, Filecoin and related technologies directly and indirectly.
 - Use of Bacalhau, an off-chain compute network closely packed with IPFS for faster data retrieval and processing.
 - Any files, codes and Actions created are uploaded to IPFS using Spheron. 
 - Credits and Payments system are smart contracts which are deployed to FVM.
 - We have used IPFS to store massive datasets using Estuary via Bacalhau.
 - Any AI/ML models generated are automatically stored in IPFS as outputs as a part of Bacalhau jobs.
 
 **Simple Work Flow**
The client retrieves all the parameters for the given action and passes them to the contract or server, depending on the action selected. While contracts handle some jobs, servers handle some by using the CLI. Lilypad handles the smart contract-based actions, while the server handles the rest. The server uploads all the relevant files and codes to IPFS and creates a Docker image if needed, and the inputs and files are passed as parameters to Bacalhau.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
YES
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |Improve UX|Hire a designer, and design a product that anyone should understand what Compute over data is.                                                       |1st Month      | 
| 2.     |Product Development|Developing and adding more actions.                                               |1 - 2 Months  | 
| 3.     |Onboard Businesses|Start to work on obarding businesses and end users to use our platform.                                                         |3rd Month     | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
YES

  
### 6. Does your proposal comply with our Community Code of Conduct?
YES

### 7. Links and submissions
Yes, our project was created during the EthGlobal HackFS 2023 hackathon.
Link: https://ethglobal.com/showcase/daggle-6xot9
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

> 	Leo Stelon 	
> leostelon17@gmail.com 	
> https://github.com/leostelon
> 	Hacker/Developer

* How did you learn about our microgrant program?
	

> HackFS 2023 Closing Ceremonies and Demos Video, mentioned by Juan Benet

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

> Daggle 
> EthGlobal HackFS 2023 hackathon.
> https://ethglobal.com/showcase/daggle-6xot9

**Comment by leostelon** [comment]
We are moving our repos from my personal account to an organisation account.
Organisation account 👉 https://github.com/dagglexyz

**Comment by DeveloperAlly** [comment]
Hey @ErinOCon Happy to be Technical consult / approver on this

**Comment by ErinOCon** [comment]
Hi @leostelon,  this microgrant has been approved! We will send an email to confirm payment details. Please note the following are required for this microgrant:

- A fully working user-facing demo with nice UX that anyone can easily use
- Deployment to Filecoin mainnet + a testnet
- Interesting use of FVM, especially what's unique to Filecoin (for example, via the Filecoin Solidity API, FVM use cases, or Bacalhau x FVM, etc.)

Please be in touch with any questions!

**Comment by leostelon** [comment]
**Update 2**

1. Release Bacalhau SDK for Node.js.
2. Integrated the same in our platform, removing Python SDK.

**TODO**
1. Lilypad re-integration.
2. Bacalhau SDK for the browser.

**Comment by leostelon** [comment]
Hi @eshon
I hope everything is going well! We want to let you know that we have launched on Filecoin Mainnet, and we are requesting the second tranche of funds. Find all the details regarding the dApp and contracts below. 

**Contract**
⌨️Find all contract codes [here](https://github.com/dagglexyz/client/tree/main/src/contracts).
📜Contract address is [f410fcshubysge5kmu4mjylxtht7nfelmug6dxnwbotq](https://filfox.info/en/address/0x148F40E2462754CA7189c2eF33cFeD2916Ca1BC3)
🔗Deployment [link](https://filfox.info/en/message/bafy2bzacectzpef2u45fkzuf4acp7sbnwid7dbmw5ji76f5yuijcte7jhh36c).

**You can try out our dApp at**
👨‍💻[https://daggle.xyz](https://daggle.xyz) (or)
👩‍💻[https://daggle.xyz/lilypad](https://daggle.xyz/lilypad)

Please do let me know if you need any further details from my end. Thank You :)

**Comment by leostelon** [comment]
Hi @eshon, apologies for the delay. Please find the demo video [here📺](https://drive.google.com/file/d/1LUQ-79K10pqFZt4ASNF9Dg15KfPjUUPw/view?usp=sharing).

Also tagging @DeveloperAlly for validation.

**Comment by leostelon** [comment]
**Update 3**

1. Lilypad SDK initialized.
2. Integrated the same in our platform, removing Python SDK.

**TODO**
1. Lilypad re-integration.
2. Bacalhau SDK for the browser.

**Comment by leostelon** [comment]
**Update 3**

1. Added Saturn support. [[know more](https://saturn.tech/)]
2. Created a module to download and archive files to the client using [@daggle/car](https://www.npmjs.com/package/@daggle/car).

**TODO**
1. Move to Lilypad V1.
2. Create a hub for modules.

**Comment by eshon** [comment]
Great @leostelon thanks for the demo video. Can you please post the video in the README of one of the Github repos associated with this project?

Once that's complete I'll approve the 2nd tranche.

**Comment by eshon** [comment]
@leostelon Exactly where is the README located?

**Comment by leostelon** [comment]
Hi @eshon, I apologize for not mentioning this earlier, but here is our GitHub project organization link: [https://github.com/dagglexyz/](https://github.com/dagglexyz/), which displays the README as the landing page.

**Comment by leostelon** [comment]
Hi @eshon 
wanted to check in with you on the next steps. Should we anticipate an email notification about this, or would it be better if I go ahead and submit a request in Coin Emissary? If you have any questions or need additional information, please don't hesitate to reach out. Your ongoing support is incredibly important to us.

**Comment by eshon** [comment]
@leostelon Our team will reach out to you soon about final steps.

**Comment by leostelon** [comment]
@eshon @ErinOCon 
Is there a procedure for submitting a final report? I'd like to discuss our plans for the product and the direction we'll be taking in the future.

**Comment by eshon** [comment]
@leostelon You can paste a link to the final report here when you're ready, ideally also add it to your Github repo
