### ISSUE TITLE
Open Grant Proposal: Navis, a WebAssembly based decentralised compute platform on Filecoin

### ISSUE THREAD

**Issue by grzxz** [filecoin-project/devgrants#1594]
# Open Grant Proposal: Navis, a WebAssembly based decentralised compute platform on Filecoin

**Project Name:** Navis

**Proposal Category:** `Research & protocols`

**Individual or Entity Name:** Individual

**Proposer:** grzxz https://github.com/grzxz

** Technical Sponsor:** https://github.com/DeveloperAlly

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

Navis is a decentralised compute platform based on WebAssembly that provides Functions as a Service like compute for blockchain developers so they access compute from smart contracts using Filecoin/IPFS for storage.

Navis is based on Proof of Compute, a replication by consensus algorithm where Navis miners provide compute and get token rewards for providing accurate compute results.

Building on Lilypad FVM bridge to enable smart contracts to run requests to Navis Functions from any supported EVM chain Axelar General Message Passing.

## Outcomes

 Facilitate adoption and providing access to users and blockchain developers to decentralized compute platforms such as Navis and Bacalhau through their wallets or smart contracts.
  

## Milestone 1 - Navis Interchain Gateway

Navis Interchain Gateway builds upon Axelar General Message Passing providing an interface for smart contracts to run Navis Functions requests and Bacalhau jobs connecting to Filecoin Virtual Machine providing results to the smart contracts asynchronously. 

Enable users to run Navis Functions requests and Bacalhau jobs from smart contracts in Axelar supported blockchains:

Ethereum
Avalanche
Polygon
Arbitrum

Development time: 3 weeks

## Milestone 2 - Navis Filecoin Virtual Machine deployment

Deploy Navis Functions beta to FVM via FEVM Solidity smart contracts.

Deploy set of Navis miners on cloud virtual machines.

Step by step Instructions on how to run Navis Functions through a Metamask transaction or through a Solidity smart contract in the supported chains of Navis Interchain Gateway.

Development time: 5 weeks

### Milestone Summary

Provided by email.

### Total Budget Requested

Provided by email.

### Team
Provided by email.

**Comment by ErinOCon** [comment]
Hi @grzxz, thank you for your patience with our review. Unfortunately, due to budget constraints in our current climate, we are not able to move forward with a grant at this time. We appreciate the work you are completing and are wishing you all the best as you continue forward!

If you have any questions for our team, please feel welcome to contact us at [grants@fil.org](mailto:grants@fil.org).
