### ISSUE TITLE
College Network

### ISSUE THREAD

**Issue by Udit-Kapoor** [filecoin-project/devgrants#1595]
### 1. What is your project, and what problem does it solve? (max 100 words)
The current educational system is centred on theory and cramming knowledge, but actual knowledge does not come in this way. Even in practical laboratories, students can learn a lot, but after the two hours of lab, they won't remember it.
Therefore, the best option is to include a network that is tightly connected with a school's or college's daily operations so that students can use common ideas of token transfers, minting nfts, staking, voting, and governance.

Who Cares - Colleges that specialise in Blockchain, as well as every organisation that offers a technological course

### 2. Project links
  
Link to Github repo:  https://github.com/Udit-Kapoor/CollegeNetwork
Link to demo or website: https://ncucoin.netlify.app/
License: MIT License
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
We use IPFS to store all the achievements for the students that the college issues them. Including the college degree and certificates. Further we have migrated the canteen system on-chain where we use NFTs to determine who owns the FOOD NFTs and burning them yields actual food via approved cafe.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Sadly No , but would be happy to migrate it.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |  Launch on Mainnet  | Develop the final parts and deploy the contract on mainnet    |                            | 
| 2.     | Migrate to FVM if required |                            | 
| 3.     |  Get students to learn about blockchain and develop more by creating basic steps using this dapp|                                                            |                            

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
https://devfolio.co/projects/college-network-aka-ncu-coin-3ceb
https://www.youtube.com/watch?v=DVAZ2D47UkM
  
### Additional questions:
Name : Udit Kapoor
Email : [udit.dude01@gmail.com](mailto:udit.dude01@gmail.com)
Github : Udit-Kapoor
Role : Co-Founder and Smart Contract and Backend Developer

**Comment by ErinOCon** [comment]
Hi @Udit-Kapoor, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant for this project. Please feel welcome to contact our team at [grants@fil.org](mailto:grants@fil.org) with any questions.

Wishing you the best as you continue to build!
