### ISSUE TITLE
Integration Filecoin FIL x Charity Impact

### ISSUE THREAD

**Issue by vetkoek-en-fietse** [filecoin-project/devgrants#1598]
# Open Grant Proposal: Integration Filecoin FIL x Charity Impact

**Project Name:** `Integration Filecoin FIL x Charity Impact`

**Proposal Category:** `Applications` 

**Individual or Entity Name:** `Charity Impact LLC`

**Proposer:** `https://github.com/malcacorp`

**(Optional) Filecoin ecosystem affiliations:** `None.`

**(Optional) Technical Sponsor:** `None.`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes.

# Project Summary

This project seeks to integrate FIL into our multichain crowdfunding platform, thus empowering the charity network within the Filecoin ecosystem. Once integrated, every NPO we onboard onto our platform will have a Filecoin wallet automatically generated and managed by our back-end system. This allows investors to donate directly to the NPOs in FIL.

Currently, there are numerous crowdfunding platforms available for fiat currencies or single cryptocurrencies, and very few multichain solutions. This fragmentation forces charities and nonprofit organizations to create campaigns on multiple platforms, leading to inefficiency and impracticality, and hampers investors’ abilities to source charitable projects to which they wish to contribute. 

Charity Impact’s multichain site seeks to mitigate this problem by streamlining the fundraising landscape. Using our site, complex fundraising campaigns and donations administration are managed with our integrated project-announcement feature, custom landing pages, widgets and CRM donation tracking, allowing our NPOs to redirect their resources to focus on their core mission. Donors benefit from the platform’s database of verified and legal charities, its offering of various currencies, automatically generated tax receipts, and its updates and reports features, which allows charities to share their accomplishments directly with their investors. Furthermore, our platform aims to empower the worldwide charity network through DeFi. By enabling charities to receive contributions in different currencies, we expand their opportunities for financial support. To date, we have successfully integrated strategies to donate in NEAR and fiat into our platform. In order to further enhance our multichain site, we have identified Filecoin as a vital role player in the DeFi space. 

Once this project is complete, a Filecoin wallet and an automatic generation of the wallet for each NPO will be integrated within the site. Filecoin will be integrated into the site’s payment forms, donation tracking system and CRM, and real-time currency evaluation system. Registered NPOs will be able to manage their wallets, transfer finances into fiat through Stripe integration, email their donors, and release updates and reports on their custom landing pages. Investors and potential investors will be able to read about the different charities, their reports and projects, they will be able to donate finances directly to the NPOs in FIL, and they will be generated automatic tax documentation upon completed transactions.

## Impact 

Our CEOs are active participants in the charity network, with a decade’s worth of combined experience in connecting charitable projects with funds. In recent years, Steven and Claudia identified DeFi as a valuable innovative tool that can empower the charity network by mitigating international transfer barriers established by the traditional financial system, protecting charities’ capital from fluctuating currencies in their countries of origin, providing donors with a variety of currencies in which to contribute, and potentially allowing charities to earn on their wealth as activity on the Filecoin blockchain grows.

Charity Impact has the potential to have a significant impact by reaching a large number of people and providing substantial value to the Filecoin ecosystem. Filecoin will benefit from this integration because:
1. Our integration code will be open sourced, to be freely used by other developers.
2. Once we launch the platform with multiple blockchains integrated, we will migrate our existing charity network from SAI and BeeTogether to the new platform. With every wallet and transaction generated through our site, we empower the ecosystem of each integrated crypto-currency and add to the value of the coin itself. By running ads we aim to boost the platform and increase its reach, bringing more people into its ecosystem. 
3. An integration with our platform provides Filecoin with exposure to our social media audience, amplifying visibility and increasing brand recognition.
4. Cross-linking with Charity Impact enhances credibility and trust, attracting potential investors and users.
5. A blockchain's involvement in social good is beneficial on multiple fronts. Firstly, it enhances their reputation as responsible actors in the digital landscape. By actively contributing to social causes, blockchains demonstrate their commitment to making a positive impact. Secondly, aligning with social good meets the expectations of an increasingly conscious public. People appreciate and support entities that prioritize social welfare. Finally, the collaboration between corporates and blockchains amplifies their collective ability to drive meaningful change in the world. Together, they possess the potential to tackle global challenges and foster a better future for all.

## Outcomes

The project will be developed using PHP integrated with Python. We have already tested our concept through the successful integration of NEAR Protocol on our live site. Our team will now use our existing architecture that is currently running our platform to integrate with Filecoin.

Once this project is complete, a Filecoin wallet and an automatic generation of the wallet for each NPO will be integrated within the site. Payment forms, a donation tracking system, and a real-time currency evaluation system will be integrated. Registered NPOs will be able to manage their wallets, transfer finances into fiat through Stripe integration, email their donors, and release updates and reports on their custom landing pages. Investors and potential investors will be able to read about the different charities, their reports and projects, and they will be able to donate finances directly to the NPOs in FIL.

We aim to onboard a minimum of 20 charities onto our platform by the end of 2023, creating 20 new active Filecoin wallets. These charities will be identified through our existing charity networks, including the South American Initiative (SAI) (https://www.sai.ngo/) and BeeTogether (https://bee-together.org/),  and leveraging traditional marketing tactics, such as social media campaigns and Google ads. Furthermore, we aim to onboard a minimum of six cryptocurrencies onto our platform before the end of 2023, and to raise a minimum of $50 000 USD through our platform before the end of 2024.

## Adoption, Reach, and Growth Strategies

Once launched, we will onboard the charities that are currently working with BeeTogether and SAI, thus beginning a planned initiative to approach approximately 500 charities from our network. Furthermore, we will leverage traditional marketing tactics, such as social media campaigns and Google ads, etc. to attract further NPOs and donors.

Please find our recently launched socials here: https://linktr.ee/charityimpact

## Development Roadmap

The integration of the Filecoin currency into the platform will take a maximum of three months and will be split over three milestones:

Milestone 1
Duration: 4 weeks; complete 4 September 2023 (if approved 31 July 2023)
Budget: $5 000 USD
Number of FTE: two developers
Deliverables: 

a. integrating the Filecoin wallet
- Functionality: once complete, charities who already have a Filecoin wallet can create a profile
- Measurement: once complete, we will provide you with a code and demonstration

b. integrating the automatic generation of the wallet for each organization
- Functionality: once complete, charities who do not own a Filecoin wallet will receive an automated wallet
- Measurement: once complete, we will provide you with a demonstration

Milestone 2
Duration: 6 weeks; complete 16 October 2023
Budget: $10 000 USD
Number of FTE: two developers
Deliverables:

c. Integrating FIL into the payment form 
- Functionality: once complete, the payment form will be fully functioning
- Measurement: once complete, we will provide you with a code and demonstration

d. integrating FIL into the donation tracking system and the CRM
- Functionality: once complete, the numbers and the system are updated automatically
- Measurement: once complete, we will provide you with a code and demonstration

e. integrating FIL into the email system
- Functionality: once complete, tax documents will be automatically emailed to donors upon completed transactions
- Measurement: once complete, we will provide you with a code and demonstration

f. integrating FIL into the real-time currency evaluation
- Functionality: once complete, Filecoin will be added to the real-time currency evaluation and will be automatically updated
- Measurement: once complete, we will provide you with a code and demonstration

Milestone 3
Duration: 2 weeks; complete 30 October 2023
Budget: $2 000 USD
Number of FTE: two developers
Deliverables: 

g. final testing and changes.
- Functionality: once complete, all functions will have been integrated and the project will be complete.
- Measurement: once complete, we will provide you with a code and demonstration

Please find our development documentation here: https://github.com/malcacorp/Charityimpact-Open-source.git. 

## Total Budget Requested

The total budget of $17 000 USD will be used to support our two software engineers through the integration process.

| Milestone 1 | Integrating the wallet | Integrating the wallet and automation of wallet generation | 4 September 2023 | $5 000 USD |
| Milestone 2 | Integrating the payment method | Integrating FIL into payment forms, donation tracking and CRM, email system and real-time currency evaluation | 16 October 2023 | $10 000 USD |
| Milestone 3 | Final testing and changes | Once these tests and final changes have been complete, Filecoin will have been successfully integrated into the platform and the project complete | 16 October 2023 | $2 000 USD |

## Maintenance and Upgrade Plans

Each transaction through our site will be subject to a 3.8% transaction fee which will maintain, manage and improve our platform.

# Team

Our diverse international team is dedicated to social and environmental justice. With a combined track record of a decade’s work in the charity sector, our CEOs carry with them a vast network of charitable organizations who will benefit from this Filecoin integration. Our development team, led by our founder and CEO Steven Malca, has extensive experience working on large-scale projects, including Instant Vital Records (https://instantvitalrecords.com/), Global Tal (https://globaltel.com/), and South American Initiative (https://sai.ngo/). These projects have required significant expertise in various domains, such as data management, security, and scalability. Leveraging their knowledge and skills, our team has delivered innovative solutions that have made a positive impact on people's lives.

## Team Members

Steven Malca (founder, CEO and chief software engineer)
Claudia Peter (co-CEO)
Lea Chisholm (business management)
Joshua Hernandez (lead software engineer)
Yudith Serrano (software engineer)

## Team Member LinkedIn Profiles

Steven Malca:  https://www.linkedin.com/in/steven-malca-66135099/
Claudia Peter: https://www.linkedin.com/in/claudiapeter/
Lea Chisholm: https://www.linkedin.com/in/lea-chisholm/

## Team Website

https://charityimpact.io/

## Relevant Experience

Steven Malca (founder and CEO) is a software developer with a decade of experience in the field. He specializes in the development of world-class CRM and ERP systems for businesses of all sizes (https://malcacorp.com/). In 2016 Steven entered the charity sector, establishing the South American Initiative (SAI) (https://www.sai.ngo/).

Claudia Peter (co-CEO) has amassed 15 years of experience in marketing and communications over various sectors. In 2020, Claudia founded BeeTogether (https://bee-together.org/), an association that explores innovative fundraising methods, including the utilization of NFTs. 

Joshua Hernandez (lead software engineer) is a skilled engineer with 7 years of experience in the field. Joshua is proficient in PHP, C++, and Python development. With expertise in blockchain technology, he has contributed to the creation of innovative cryptocurrency networks, showcasing his talent for cutting-edge software development.

Yudith Serrano (software engineer) is a talented PHP engineer specializing in CRM and ERP development. With a strong expertise in designing and implementing efficient software solutions, Yudith excels in creating custom systems that streamline business processes and enhance productivity. Yudith has 5 years of experience in the field.

## Team code repositories

Steven Malca: https://github.com/malcacorp
Joshua Hernandez: https://github.com/malcacomputerengineering 
Yudith Serrano: https://github.com/ycsa91-malcacorp 
Other projects: https://malcacorp.com/ http://www.sai.ngo/ http://www.bee-together.org/

# Additional Information

We learnt about this grant program through researching on the Filecoin website.

Please contact me at lea@charityimpact.net 

Please find a link to our proposal deck and a reference letter from NEAR's CFO Yessin Schiegg here: https://drive.google.com/drive/folders/1upfEFGFOxAr8iqIZxIQTb7qpEuDi1hh2?usp=drive_link

**Comment by ErinOCon** [comment]
Hi @vetkoek-en-fietse, thank you for your proposal and for your interest in our grants program. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
