### ISSUE TITLE
Open Grant Proposal: Spheron Decentralised Bundlr

### ISSUE THREAD

**Issue by rekpero** [filecoin-project/devgrants#1601]
# Open Grant Proposal: Spheron Decentralised Bundlr

**Spheron Decentralised Bundlr**

**Proposal Category:**`Developer and data tooling`

**Entity Name:** Spheron

**Proposer:** [rekpero](https://github.com/rekpero)

**(Optional) Filecoin ecosystem affiliations:** Protocol Labs

**(Optional) Technical Sponsor:** Honghao Qiu

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

Our project aims to solve the problem of unattractive small-sized deals on Filecoin, which makes it economically unfeasible for Storage Providers to store them.

## Impact 

Our project addresses the issue of unattractive small-sized deals on Filecoin. Currently, the economic feasibility of storing these small deals is limited for Storage Providers. This means that valuable data and storage opportunities are being missed out on.

To overcome this challenge, we propose a decentralized deal bundler. This system acts as a mediator, aggregating multiple small-sized deals into larger ones. By combining these smaller deals, we create a more appealing and economically viable opportunity for Storage Providers to participate in.

The deal bundler operates in a transparent and trustless manner. It ensures that all parties involved have visibility into the aggregation process, eliminating any concerns regarding biased or unfair bundling. The transparency helps build trust among the participants and ensures a level playing field for all.

Overall, our project aims to revolutionize the Filecoin ecosystem by making small-sized deals more economically viable and attractive for Storage Providers through decentralized bundling. The integration of PoDSI further enhances transparency, trust, and data integrity within the system.

## Outcomes

Our project entails the development of a fully decentralized aggregator network for Filecoin, aimed at consolidating small deals and providing Storage Providers with a more attractive and economically feasible opportunity to participate in a trustless and decentralized manner.

In addition to the network, we will be building dev tooling that integrates with the Filecoin Virtual Machine (FVM). This tooling will enhance transparency and simplify the process for developers to create deals with Filecoin. By removing the need for reliance on centralized entities to handle deal creation, developers will have greater flexibility and control over their data.

To facilitate the adoption of our network, we will provide a user-friendly SDK (Software Development Kit). This SDK will enable developers to build applications on top of our decentralized network. By leveraging this SDK, developers can seamlessly interact with the network, allowing anyone to participate as a dealer. This approach empowers a distributed community to run nodes and aggregate all the deals they receive, subsequently facilitating the creation of deals with Filecoin storage providers.

In summary, our project encompasses the development of a decentralized aggregator network for Filecoin, along with accompanying dev tooling and an SDK. This ecosystem will enhance transparency, decentralization, and accessibility, enabling a broader range of developers and participants to engage in Filecoin's deal creation and storage processes.

## Adoption, Reach, and Growth Strategies

Our project provides a decentralized aggregator service that offers numerous benefits for all participants within the Filecoin ecosystem. It offers a compelling alternative to the existing centralized counterparts when it comes to creating deals with Filecoin.

Clients can have greater confidence in the inclusion of their data within deals, thanks to our trustless and transparent system. Developers, on the other hand, can benefit from our user-friendly SDK, which empowers them to build applications on top of our decentralized network and engage with Filecoin's deal creation process more efficiently.

As active members of the Filecoin community, we are highly committed to contributing and making a positive impact within the ecosystem. We enthusiastically embrace the opportunity to support and enhance the Filecoin community's growth and development.

## Total Budget Requested

| Milestone | Completion Date | Funding |
| --- | --- | --- |
| SDK and Developer Tools | 30 Days | $10000 |
| On-Chain Payments | 30 Days | $15000 |
| Decentralization of the Off-Chain Bundlr | 60 Days | $25000 |

**Total Funding:** $50,000

### SDK and Developer Tools
- File Upload directly to Spheron and deal creation through SDK
- Creation of CAR file and uploading to Spheron IPFS, additional CAR conversion methods in the SDK
- SDK methods to manage the payment of deals, refunds, and data
- Methods to download data from SP and Spheron both (depending on the use case)

**No of People Working** - Team of 2 
**Funding Required** - $10000 
**Deadline** - 30 Days

### On-Chain Payments
- Enable payments on-chain using FIL Token
- Bounty Contract for Clients to deposit funds, and add ability for SP to claim funds from the pool 
- Allow aggregators to aggregate the files and creation of CommPa on-chain.
- Smart Contract to track user funds (stored in the contract state).

**No of People Working** - Team of 2 
**Funding Required** - $15000
**Deadline** - 30 Days

### Decentralisation of the Off-Chain Bundlr
- Allow multiple aggregators to participate in the process of bundling, implement consensus among the network of aggregators.
- On-Chain Aggregator registration and staking for rewards and punishment mechanisms. 
- Validators Nodes to Check for the deal integrity. Allow for potential payment refunds and re-initiation of the deal.

**No of People Working** - Team of 2 
**Funding Required** - $25000 
**Deadline** - 60 Days

## Maintenance and Upgrade Plans

We are dedicated to maintaining the SDK and ensuring that any issues that arise after its release are promptly resolved. Additionally, we are committed to enhancing both on-chain and off-chain proof creation processes (PoDSI Creation) to provide more efficient and reliable methods of verifying data integrity. Furthermore, we will focus on improving the filecoin deal creation process, streamlining the steps involved in initiating and managing deals on the Filecoin network. These efforts aim to enhance the overall functionality and user experience of the SDK, empowering developers to leverage its capabilities with ease and confidence.

# Team

## Team Members

- Mitrasish Mukherjee - [Github](https://github.com/rekpero) - [LinkedIn](https://www.linkedin.com/in/mmitrasish/)
- Prashant Maurya - [Github](https://github.com/izrake) - [LinkedIn](https://www.linkedin.com/in/techprashantmaurya/)
- Manank Patni - [Github](https://github.com/Man-jain) - [LinkedIn](https://www.linkedin.com/in/manankpatni/)

## Team Website

https://spheron.network
https://docs.spheron.network

## Relevant Experience

With a proven track record in network development, our team has established a strong presence within the Filecoin ecosystem. We have played a significant role in building crucial infrastructure for the web3 ecosystem and are dedicated to fostering greater adoption of these noble decentralized systems.

## Team code repositories

https://github.com/spheronFdn

# Additional Information

We have already received a [Micro Grant](https://github.com/filecoin-project/devgrants/issues/1443) for starting this project. It is important to note that the deliverables outlined in the grant go beyond the initial scope mentioned, demonstrating our commitment to expanding and enhancing the project's impact.

For any further inquiries or discussions regarding this open grant, please feel free to contact me via email - mitrasish@spheron.network. I look forward to addressing any questions you may have and engaging in further conversation.

**Comment by ErinOCon** [comment]
Hi @rekpero, thank you for your proposal! Is your team affiliated with [this project](https://github.com/filecoin-project/devgrants/issues/420)?

**Comment by ErinOCon** [comment]
Hi @rekpero, I hope you are doing well! We expect to have an update available soon regarding the status of your proposal. Thank you for your patience with our review.
