### ISSUE TITLE
HashBox Mail - The Smart Contract Mail

### ISSUE THREAD

**Issue by HashBoxBlockchain** [filecoin-project/devgrants#1604]
# Open Grant Proposal: `HashBox Mail - The Smart Contract Mail`

**Project Name:** HashBox Mail

**Proposal Category:** `Applications`

**Individual or Entity Name:** `HashBox Blockchain LTDA`

**Proposer:** `HashBoxBlockchain`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** `Yes`.

# Project Summary

It's a mail built on the blockchain using smart contracts to send and receive messages and files, eliminating the need for middlemen controlling the data. Without intermediaries, data cannot be changed or censored by a company.

## Impact 

Due to the nature of the blockchain that all data on it is public, anyone who knows a user's wallet address can know how much money the user has. If it is an exorbitant amount, this information could put that person's safety at risk if a criminal knows where the user lives or goes to. 

For this reason, no user should link his personal information (SSN, home address, telephone number or workplace address) to his wallet address. A criminal knowing someone's email address, can easily discover his home address or sensitive information from a resume posted online.

The solution removes this need for the user to expose personal information, using only his wallet address to communicate, to receive information or files from a company or another user. An online platform only needs to know the user's wallet address - if he has the necessary amount or if he has already paid for the product/service offered.

To know more, please read the White Paper:[ https://hashbox.app/white-paper](https://hashbox.app/white-paper)

- Why is this application so important?

It's important because this is one of the few applications on the blockchain that is not:

- A coin project (Bitcoin for example);
- A token project (to exchange business, intellectual property or private property rights);
- An NFT project (to exchange image, video, audio, text or game character);
- A DeFi project (to exchange tokens);
- A DNS project (to translate hexadecimal address into a human-readable name).

This is a project for communication: Communication on the blockchain.

Many apps work like this:

a) User A sends a message to the App;
b) The App resends the message to User B.

The core of HashBox Mail is to remove the "App".

The "App" is not needed with the blockchain and the smart contracts, everything is peer-to-peer (P2P).

Note: IPFS is used to storage the messages on the blockchain.

## Outcomes

The project is already working: [https://mail.hashbox.app](https://mail.hashbox.app)

The main objective is to create a utility project not linked to the cryptocurrency market: you don't need to know how much 1 Bitcoin costs if you have to communicate with someone. If you need to communicate, you'll do it without worrying about the price of Bitcoin.

If the project is successful, I support the project by selling the credits (HBMs).

## Adoption, Reach, and Growth Strategies

The target audience is the blockchain user.

Blockchain mass adoption involves creating daily applications.

The adoption, reach and growth will be driven by applications using the HashBox Mail, the “daily apps”, like: a carpool app, a delivery app, a house rental app, etc. 

In order to have these applications using the protocol, it is necessary to reach out to blockchain companies, blockchain builders and blockchain users to make them aware that blockchain has more functions than just functioning as a financial infrastructure. 

For the project be succeeded, I must to create networks first.

With the core of this project, you can build:

- A decentralized Uber - user asks driver for ride on the blockchain without the Uber;
- A decentralized DoorDash - user requests a delivery on the blockchain without the DoorDash;
- A decentralized AirBnb - user rents a house on the blockchain without the AirBnb.

With all the rules written using smart contracts. Immutable, forever.

"Blockchain Day By Day" - This is HashBox's motto.

Note: This project can be used by people even in the bear market, because this is a utility project not tied to the crypto market.

## Development Roadmap

The project is already working: [https://mail.hashbox.app](https://mail.hashbox.app)

- Why do I need grants?

1) Porting the solution to FVM network (the solution is currently working on the Polygon Network);
2) To rent and install the dApp on a better VPS server (current has only 2GB of RAM);
3) To rent and install the dApp on a better RPC server (I'm using a free tier);
4) To fix few issues about paging results;
5) To improve UI/UX for Feeds Settings;
6) To create responsive pages;
7) To create a UI for sending multiple emails and so on.

Note: The project is developed only by Silvio Guedes.

## Total Budget Requested

| Milestone # | Description | Completion Date | Funding |
| --- | --- | --- | --- |
|1|Porting the solution to FVM network|7 days|$26000|
|2|To rent and install the dApp on a better VPS server|7 days|$1000|
|3|To rent a better RPC server|1 day|$1000|
|4|To fix few issues about paging results|1 month|$4000|
|5|To improve UI/UX for Feeds and Settings|1 month|$4000|
|6|To create responsive pages|1 month|$4000|
|7|To create a UI for sending multiple emails|1 month|$4000|
|8|Other issues (what takes place)|1 month and a half|$6000|

Total: $50,000.

## Maintenance and Upgrade Plans

The project will have upgrades for deprecated libraries (HTML and Javascript).
The smart contracts code will never be upgraded, because they are immutable and don't use proxies. 
The project is open source, so anyone can improve it too.

# Team

## Team Members

Silvio Guedes: [https://github.com/SilvioGuedes](https://github.com/SilvioGuedes)

## Team Member LinkedIn Profiles

Silvio Guedes: [https://www.linkedin.com/in/silvio-guedes-santana-4b506442/](https://www.linkedin.com/in/silvio-guedes-santana-4b506442)

## Team Website

[https://hashbox.app](https://hashbox.app)

## Relevant Experience

I have more than ten years of professional experience in development, with deep knowledge of the languages Java, C/C++ for the platforms of mobile devices as Android, Bada and Windows Mobile. I also know to develop cross-platform applications with Unity 3D and Xamarin (C# language). This is my first blockchain project.

Note: the project is already built: [https://mail.hashbox.app](https://mail.hashbox.app)

## Team code repositories

[https://github.com/HashBoxBlockchain/HashBoxMailMatic](https://github.com/HashBoxBlockchain/HashBoxMailMatic)

# Additional Information

I learned about Open Grants Program on BlockchainGrants: [https://www.blockchaingrants.org/](https://www.blockchaingrants.org).

Thanks for your attention.

If you have any questions, please contact me: contact@hashbox.app.
If you want to thank me, please send an email on the blockchain (Fee 1 MATIC):[ https://mail.hashbox.app/address/0x55555E09bc39767C48Eb02863029Cb0838a80f2B](https://mail.hashbox.app/address/0x55555E09bc39767C48Eb02863029Cb0838a80f2B).

**Comment by ErinOCon** [comment]
Hi @HashBoxBlockchain, thank you for your proposal and for your interest in our grants program. Unfortunately, we will not be proceeding with a grant at this time. Wishing you all the best as you continue to build!
