### ISSUE TITLE
Filecoin Community Dashboard on Alphaday

### ISSUE THREAD

**Issue by Mikael337** [filecoin-project/devgrants#1605]
### 1. What is your project, and what problem does it solve? (max 100 words)

Alphaday is a React-Typescript dashboard on the frontend using a Python-Django backend built on distributed infrastructure with Postgres and Redis Databases.

### 2. Project links
  
Link to Github repo: https://github.com/AlphadayHQ
Link to demo or website: https://app.alphaday.com/
License: N/A

### 3. a) How is IPFS, Filecoin, or related technology used in this project?

  
Yes, we will not only share monthly updates but also work together with a representative from your team to build the dashboard as optimally as possible before publishing it to your community. Further to the initial development & deployment of the dashboard, we do not want to lose contact with Filecoin for future marketing opportunities.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

Our project began on the initiative and resources of the founders.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

Name: Deniz Omer
Position: Founder
Short Bio: Has been involved in the Ethereum space since early 2016 and joined Kyber Network in 2017 as Head of Ecosystem Growth before quitting to start Alphaday full-time in 2021. Previously he worked at Thomson Reuters for a decade building financial products that rivaled the Bloomberg Terminal. He is currently also a Venture Partner at IOSG.VC.
https://twitter.com/DenizOmer, https://www.linkedin.com/in/denizomer/ 

Name: Felipe Faraggi
Position: Co-founder
Short Bio: Has also been involved in Ethereum since 2016 and was a Developer Advocate at Pegasys and Consensys before quitting to work full time on Alphaday.
https://github.com/faraggi, https://twitter.com/felipefaraggi, https://www.linkedin.com/in/faraggi/ 

Name: Pablo Palomo
Position: Technical Lead
https://github.com/ppalomo, https://twitter.com/ppalomo, https://www.linkedin.com/in/pablo-palomo-07127711/ 

Name: Vicente Almonacid
Position: Software Engineer
https://github.com/v-almonacid, https://twitter.com/v_almonacid, https://www.linkedin.com/in/vicente-almonacid/ 

Name: Charles Nwankwo
Position: Developer
https://github.com/Xavier-Charles, https://twitter.com/Chadnium, https://www.linkedin.com/in/charles-nwankwo-01/ 

Name: Jonathan Irhodia
Position: Developer
https://github.com/elcharitas, https://twitter.com/iamelcharitas, https://linkedin.com/in/elcharitas 

Name: Gideon Anyalewechi
Position: Developer
https://github.com/getgiddy, https://twitter.com/get_giddy, https://www.linkedin.com/in/getgiddy/ 

Name: Michael Hagopian
Position: QA & Analyst
https://twitter.com/MikeJa33, https://www.linkedin.com/in/mikael-h-87bb4ba4/ 

We learned about the grant program via a representative of Filecoin, Jenks Guo - Developer Advocate, at EthLisbon. We then researched further into it and found ‘microgrants’ to be the most suitable program to apply to.

**Comment by ErinOCon** [comment]
Hi @Mikael337, thank you for your proposal and for your patience with our review. Unfortunately, we will not be proceeding with a grant at this time. Wishing you the best as you continue to build!
