### ISSUE TITLE
Next Step Microgrant: Mouseion

### ISSUE THREAD

**Issue by carrabre** [filecoin-project/devgrants#1610]
### 1. What is your project, and what problem does it solve? (max 100 words)
I'm building Mouseion - it's the modern day Library of Alexandria hosted on IPFS. We're building a decentralized, open source index that pairs with an LLM for data and citations, and starting with the Wikipedia dataset.

### 2. Project links
  
[embeddings pipeline github](https://github.com/themouseion/Wikipedia-Embeddings)
[github for website](https://github.com/themouseion/mouseionwebsite)
[website:](https://themouseion.eth.limo/)
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

The [website](https://themouseion.eth.limo) is hosted on IPFS, I plan to host the data itself on IPFS as well which will be used for the search and API interface. The first dataset i'm using is the english wikipedia dataset, and so once it's completed, users will be able to search all wikipedia embeddings from an index that's hosted on IPFS. The idea is to do this with the entire common crawl data set (almost 100 TiB), but this will take a long time and a large amount of resources (more than the scope of this grant). I believe that a project like this is why IPFS was created, and is the only place today where you could build a modern day Mouseion of Alexandria (Library of Alexandria). So i'm going to build it!

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                        | :---                                                       | :---                       | 
| 1.     | Search Interface complete      |    Finish the UI so that once data is returned it's a useable UI |   + 1 week                         | 
| 2.     | Embeddings hosted on IPFS with data   |   Host both the  embeddings and data on IPFS     |   + 4 weeks                         | 
| 3.     |  Embeddings + data on IPFS connected to Search interface |  Make sure that the UI can access the information stored on IPFS  |   + 2 weeks                        | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes!

  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes!

### 7. Links and submissions

n/a 
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Alex Carrabre - alexcarrabre@gmail.com - @carrabre - wearing every hat!
* How did you learn about our microgrant program?
I was accepted for a previous application for both micro grant and open grant, https://imbue.eth.limo. It's an open source decentralized live streaming site, used by people even today - hosted on IPFS.
* If your project was created as part of an event or hackathon: 
n/a
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @carrabre, thank you for your proposal and for your patience with our review. Unfortunately, we will not be proceeding with a grant at this time. Wishing you the best with your building progress!
