### ISSUE TITLE
# Open Grant Proposal: End-to-End Encrypted Web Disk Service 

### ISSUE THREAD

**Issue by zhoubing99** [filecoin-project/devgrants#1611]
# Open Grant Proposal: End-to-End Encrypted Web Disk Service 

**Project Name:** FireDrive

**Proposal Category:** Applications

**Individual or Entity Name:**  Firechat Global Limited

**Proposer:** @zhoubing99

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary
FireDrive combines the advantages of decentralized storage and end-to-end encryption to provide users with decentralized storage service. By utilizing IPFS and Filecoin technologies, FireDrive can ensure secure, shared storage; by utilizing end-to-end encryption, users can have complete control over their data to ensure data privacy.

## Impact 
- What pain points does this project seek to address? 
1. Data Privacy: Traditional centralized data storage services do not support client-side encryption, resulting in user-stored data that might be shared, abused, and regulated without the user's awareness; FireDrive allows users to have full control of their data.
2. Storage Reliability: Traditional centralized data storage services have the problem of high risk of single point of failure; FireDrive greatly reduces this risk through sharding and redundant storage based on IPFS and Filecoin networks.

- What are the benefits to getting this right? What are the risks of not getting this right?
Many organizations and developers are trapped in the high cost and risk of centralized storage, but they know very little about web3 storage, and the cost of migrating from traditional storage to decentralized storage is extremely high. FireDrive will provide easy-to-access SDKs and flexible APIs to help these developers access decentralized storage capabilities at a lower cost.

- What impact will this project have in a specific vertical, market, or ecosystem? What does success look like? -->
1. The FireDrive project will first be launched on the FireChat App (the biggest web3 social media app with 5,000,000 registered users), to make the IPFS and FIlecoin networks available to more end users
2. The FIleDrice project will also provide a full API and SDKs to allow more organizations and developers to connect their applications to the IPFS and FIlecoin networks.

## Outcomes
The FireDrive project is a decentralized storage service platform, and the following final results and deliverables can be expected:

- Distributed Storage : Build a distributed storage based on IPFS to decentralize data and improve data availability and durability.
- End-to-End Encryption Layer: Users manage their encryption secret keys to ensure that only that user's client can decrypt their uploaded data to ensure the privacy of the data during transmission and storage.
- Hash Check Layer: Ensures the integrity and consistency of files downloaded by users by comparing file hashes.
- App:  FireDrive will be first applied to FireChat (Social media app with 5,000,000 registered users), providing web, Android and iOS versions. The application allows users to store data, access data, and share data easily and securely;
- API: FireDrive will provide a full-featured API for organizations and developers to flexibly combine FrieDrive's capabilities to customize their decentralized storage applications.
- SDK: FireDrive will provide end-to-end encryption and decryption functions, data storage-related functions of the client SDK, so that organizations and developers can quickly access FireDrive to provide their applications with decentralized storage of the basic functions, the SDK will provide a number of features, including but not limited to JavaScript, iOS, Android versions.

Project Assessment Indicators:
- App
  - Application downloads and installations
  - UV, PV of FireDrive related functions
  - Data storage volume per unit time, data access volume per unit time
- API&SDK
  - Number of access parties
  - performance indicators

## Adoption, Reach, and Growth Strategies
End users: Users focused on data security, data privacy, flexible access
Corporate Users: organizations seeking a cost-effective, scalable and reliable data storage and sharing platform

User Development Program:
- First of all, we are targeting the existing users of FireChat. As a large volume Web3 community, the users fully understand the importance of data security and privacy, and also have the ability to manage local secret keys. We will invite FIreChat to participate in the Beta testing and utilize FireChat's community influence to attract more users to use FireDrive.
- FireChat has been used as a case study to attract more organizations and developers to use FireDrive's API and SDK to provide more users with secure decentralized storage services.

### Milestone 1: Interfacing to Filecoin network and completing basic data access control

Expected to complete functionality:
- Non-functional parts: system design, product design, UI design.
- File storage and access control: interfacing with Filecoin network and providing data upload and data download.
- Integrity verification of files: Ensure the integrity and consistency of files downloaded by users by comparing file hash values.
- Client end-to-end encryption: local data encryption/decryption, local secret key storage, local secret key export/import.

Team members: product manager, UI designer, front-end R&D engineers, client-side R&D engineers, back-end R&D engineers, blockchain R&D engineers

Funding: $25,000

Completion Time: 30 days

### Milestone 2: File Access Authentication and Functionality Integration

Expected Completion Functionality:

- File Access File access authentication to enable multi-party authorized file sharing or deletion.
- Client Integration: Full FireDrive functionality in FireChat web client and app.

Team members: front-end engineers, client-side  engineers, back-end engineers, blockchain engineers, test engineers

Funding: $15,000

Completion Time: 30 days

### Milestone 3: External SDK and APIs

Expected to complete the functionality:

- API: Implement a fully functional external API for organizations and developers to flexibly combine FrieDrice's capabilities to customize their decentralized storage applications.
- SDK: implement a client SDK that includes end-to-end encryption and decryption functions and data storage functions, so that organizations and developers can quickly access FireDrive to provide the basic functions of decentralized storage for their applications.
- Documentation: Provide friendly docking API and SDK documents.

Team Members: Front-end engineers, client-side  engineers, back-end engineers, test engineers

Funding: $10,000

Completion time: 20 days

## Total Budget Requested
Milestone 1:
Description: Interface to Filecoin network and complete basic data access control
Deliverables: Client Segment End-to-End Encryption Module, Data Access Control Module, Hash Check Module
Completion: August 30, 2023
Funding: $25,000

Milestone 2:
Description: File Access Authentication and Functionality Integration
Deliverables: Data Sharing Control Module, C-suite Complete Functionality Experience 
Completion: September 20, 2023 
Funding: $15,000

Milestone 3:
Description: External SDK & API
Deliverables: API, SDK | 
Completion: October 10, 2023 
Funding: $10,000 

**Total:** $50,000

## Maintenance and Upgrade Plans
Iteration of system features: Based on user feedback and market research, we will continue to iterate and expand FireDrive's features to improve user experience and optimize performance. We will update our security measures according to the latest technical standards to ensure the security and privacy of user data.

System maintenance and bug fixing: After FireDrive is launched, the technical and operation and maintenance teams will ensure the stable operation of the system and ensure that any bugs in the system will be resolved quickly to the best of the team's ability.

Sustainability: In order to ensure the sustainable development and profitability of the project, we will continue to explore and improve the business model of FireDrive, and launch more value-added services that can realize revenue while providing users with basic services for free.

Cooperative eco-expansion: We will continue to look for partners who use FireDrive's API and SDK, let them participate in the construction of FireDrive's eco-economy, and continuously optimize the functionality and performance indexes of API and SDK based on partners' opinions and feedback.

Feedback Mechanism and Community Governance: We will hold regular community events in FireChat and other communities to incorporate community feedback and add to the development roadmap. Community activities include, but are not limited to, voting on expected features, gray-scale testing, and satisfaction surveys.

# Team

## Team Members
Zhou Bing - Project Manager
Zeyong Xia - Architect
Duan Zhilin - Front-end Lead developer
Wu Jianping - Back-end Lead developer
more developers will be assigned in this project

## Team Member LinkedIn Profiles
https://www.linkedin.com/in/bing-zhou-40380264/
https://www.linkedin.com/in/acoaaeurhc8bqhebwjmj9f0tyks55v3zlpvonq4/
https://www.linkedin.com/in/%E5%9D%9A%E5%B9%B3-%E5%90%B4-b70777284/
https://www.linkedin.com/in/duanzhilin/

## Team Website
https://www.firechat.io

## Relevant Experience
Zeyong Xia, CTO, has worked for Sina, Gome, Ant Financial Services, Firecoin.com, etc. He has served as the main developer and architect in many projects, specializing in the architecture design, technology selection and core code writing of social systems.

Duan Zhilin, technical expert, has many years of experience in iOS and Android development, familiar with their respective development ecosystems, and able to make wise choices according to the needs of the project, has many years of experience in IM business development, and able to quickly solve the related business needs, has an in-depth understanding of the front-end development of the mobile terminal, good at analyzing and solving all kinds of problems in the application, and able to optimize the performance, to ensure that the application can run smoothly on all kinds of devices. All kinds of devices can run smoothly.

Wu Jianping, JAVA technology expert, computer science, has a solid background in computer science, more than 10 years of experience in JAVA development, skilled in the use of a variety of frameworks and middleware, etc., and in-depth source code, the principle of OOP has a deep understanding of object-oriented software analysis, design methodology, has a strong ability to abstract the design of many years of community, social networking, trading, blockchain business system design and construction experience, with complex business systems. Experience in community, social, trading, blockchain business system design and construction, experience in analyzing, designing and landing of complex business systems, excellent business analysis, program integration and problem solving ability, able to transform complex business problems into clear system requirements.

## Team code repositories
N/A

# Additional Information
We got to know Open Grants Program from our biz partner, they are the top tier Filecoin miner, they appreciate our FireDrive idea and highly recommend us to apply.
 [zhoubing99@hotmail.com](mailto:zhoubing99@hotmail.com) could bu used for grant agreement and general next steps.
FireChat has 5M+ web3 users and they need decentralized storage to store their data for anti-censorship，when FireDrive is developed and integrated into FireChat, FireDrive will prompt Filecoin/IPFS to more users and with real data stored in Filecoin/IPFS, and finally empowered Filecoin/IPFS ecosystem.

**Comment by ErinOCon** [comment]
Hi @zhoubing99, thank you for your proposal and for your patience with our review. Unfortunately, we will not be proceeding with a grant at this time. Wishing you all the best as you continue to build!
