### ISSUE TITLE
The House of Sounds - Web 3.0 Audio Format

### ISSUE THREAD

**Issue by ThoseApp** [filecoin-project/devgrants#1613]
Issue: Open Grant Application

TITLE: The House of Sounds

# Open Grant Proposal: `Web 3.0 Audio Format`

**Project Name:** .tkn Audio Format

**Proposal Category:** `Applications`

**Individual or Entity Name:** The House of Sounds Enterprises Limited

**Proposer:** `@boombomi`

**(Optional) Filecoin ecosystem affiliations:** `N/A.`

**(Optional) Technical Sponsor:** `www.theaudioprogrammer.com`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** "Yes".

# Project Summary
Rights Management: One of the significant issues in the music industry is ensuring fair compensation for artists, songwriters, producers, and other stakeholders. This involves identifying rights ownership for a given piece of music and allocating the revenue from its use appropriately. Music rights management is complex, involving different types of rights such as copyright, mechanical, performance, and synchronization rights.
Piracy: Piracy, referring to the unauthorized use, sharing, or distribution of copyrighted material, remains a substantial challenge in the music industry. It not only results in revenue loss for the industry but also impacts artists and songwriters, whose livelihoods depend on royalties and other forms of compensation from their work.
Royalty Distribution: While music streaming has grown in popularity, it has brought along issues related to royalties. Streaming services pay artists and record labels based on the number of streams, leading to contention and legal disputes as many artists and songwriters believe they are not receiving fair compensation for their work.

Our proposed solution involves an audio format specifically designed for Web 3.0. Through this, ownership rights allocation becomes transparent via smart contracts, music and other types of audio are secured due to the immutable nature of the blockchain, and earnings can potentially increase and become more accessible. This innovative approach seeks to resolve the industry's key pain points while empowering artists and stakeholders alike.

## Impact

The .tkn format primarily addresses three key pain points in the music industry: improper allocation of ownership rights, unauthorized use of music intellectual property, and inequitable compensation for songwriters and creators.

Addressing these issues has the potential to rectify almost three decades of losses experienced by artists and labels alike. The .tkn format is poised to open new avenues for enhancing the music economy, a concept partly demonstrated by the recent growth in NFT sales and song rights acquisitions. However, failing to address these issues adequately risks missing the chance to disrupt the entertainment industry and allowing the persistence of costly challenges for labels and creators. The format also faces potential risks, including the loss or damage of audio files, slow transition to Web 3.0, slow format adoption rate, and limitations caused by poor internet penetration.

The introduction of the .tkn format could significantly increase revenue for all industry stakeholders, creators and distributors alike. By facilitating transparency, it is poised to mitigate longstanding legal disputes between songwriters and labels. As the exclusive version of each song will be hosted on Filecoin/IPFS, your organization would become the primary custodian of global music, taking responsibility for storage, security, and revenue generation from music. This opportunity allows for various strategic partnerships. Given that around 30% of consumed music is accessed illegally, if we manage to reduce this figure by 80% within the first year of the format's adoption by major labels and streaming platforms, we would consider the project a success. Our efforts aim to build a more equitable, transparent, and profitable music industry for all parties involved.

## Outcomes

Upon the completion of this project, we expect to have developed the .tkn audio format designed for Web 3.0, alongside supporting tools and comprehensive documentation. The main deliverables include:
.tkn Audio Format: The .tkn format will encapsulate all necessary information related to an audio file, including ownership rights, earnings, and payment information. It will also act as a payment distributor, allowing direct payments to the rights owners' wallets as streams are generated.
Rights Exchange Platform: This innovative platform will revolutionize the music economy by enabling creators to trade their music rights, extending the lifespan of music and allowing fans to invest in music they love.
Conversion Tools: Standalone or web-based conversion tools will allow users to convert their existing audio files to the .tkn format. These tools could be integrated into existing digital audio workstations (DAWs) or media players.
Integration APIs: The creation of integration APIs will enable third-party software and platforms, such as streaming services and DAWs, to incorporate our audio format. This will empower these services to sell and distribute music in our format.
Metadata Generation & Extraction Tools: We will create tools to extract metadata from existing audio files and generate metadata for new files. This metadata includes a wide range of information, from technical details such as frequency range and bit depth, to copyright information, royalties, and more.
Quality Control Tools: These tools will test the .tkn format's quality and compatibility with various software and hardware, ensuring consistent high-quality audio.
Audio Processing Tool: This tool will process audio data to optimize the format's unique features such as spatial audio and low bit-rate encoding.
Audio Player: A specialized tool for playing .tkn audio files on various devices and platforms, providing users with a seamless listening experience.
Compression Tool: This tool will optimize audio file size while maintaining quality, essential for efficient storage and streaming.
Support and Documentation: Comprehensive support resources and documentation will ensure that users and developers can effectively use and integrate with our format. This includes user manuals, API documentation, and a knowledge base or FAQ.
With these deliverables, we aim to streamline the music industry, making it more transparent, fair, and efficient for all stakeholders.

Our team follows the principles of Agile, implementing a blend of Kanban and Scrum methodologies. To measure our team's success, we employ several metrics and practices as outlined below:

**Agile Principles:**

Our team success is determined by adherence to the twelve principles of Agile, which include continuous delivery, welcoming change, delivering value frequently, effective communication, continuous improvement, simplicity, and regular reflection on work methods.

**Key Performance Indicators (KPIs):**

1. *Kanban Metrics:* To organize and prioritize work, we use key metrics such as cycle time, throughput, and work in progress.

2. *Scrum Metrics:* These metrics focus on the delivery of working software. Key indicators include velocity and planned capacity.

**Management and Communication:**

As a manager, my responsibilities include maintaining motivation, encouraging personal development, and ensuring basic needs are met. I observe team dynamics and communicate regularly with team members to understand their individual and collective needs.

**Daily Meetings and Retrospectives:**

We organize daily meetings and retrospectives to foster communication, identify obstacles, and facilitate discussions about project improvement.

**Continuous Integration and Delivery (CI/CD):**

We follow the CI/CD model which supports an automated pipeline of tasks, including tests and checks for functionality assumptions. This helps track the frequency of changes implemented by team members and ensures efficient delivery of the application.

In summary, our team's success is a multifaceted measure encompassing Agile adherence, KPIs, effective management, clear communication, and efficient delivery practices.

## Adoption, Reach, and Growth Strategies

Our primary user base comprises major streaming services, record labels, and their associated partners. The size of this user base is significantly extensive, given the pervasive adoption of music streaming worldwide.
As of 2022, there were approximately 616.2 million paid subscribers on various music streaming platforms, as per Statista (source:[ https://www.statista.com/topics/6408/music-streaming/#topicOverview](https://www.statista.com/topics/6408/music-streaming/#topicOverview)). This estimate does not even account for the large number of users on freemium subscriptions, further increasing our potential user base.
Moreover, an estimated 5.3 trillion streams were generated in 2022 alone, according to a report by Music Business Worldwide (source:[ https://www.musicbusinessworldwide.com/on-demand-song-streams-grew-12-2-in-the-us-last-year-and-25-6-globally1/](https://www.musicbusinessworldwide.com/on-demand-song-streams-grew-12-2-in-the-us-last-year-and-25-6-globally1/)). This substantial figure underlines the vast opportunity that lies within our target audience and supports our aim to revolutionize the audio format industry.

Our primary strategy for user acquisition revolves around building strategic partnerships within the music industry. Our aim is to partner with the major record labels, which we believe will lead to widespread adoption of our format by streaming services and rights agencies.

Our initial approach will focus on the "big three" record labels: Universal Music Group, Warner Music Group, and Sony Music Entertainment. Their substantial influence and reach within the industry can act as a catalyst for the adoption of our format.

Once these major entities integrate our audio format, listeners, as the end consumers, will naturally adopt the new standard when accessing their favorite music. This strategy leverages the established networks of these influential industry leaders, enabling a more seamless user acquisition process.

## Development Roadmap

Requirements: Two (2) audio programmers

## Total Budget Requested

- Milestone 1: 4000 USD
- Milestone 2: 3500 USD
- Milestone 3: 4000 USD
- Milestone 4: 3500 USD

Total: 15000 USD

| Milestone # | Description | Deliverables | Completion Date | Funding |
| 1 | **Goal:** Finalize scope, Implementation of File Writing Mechanism <br> **Number of members:** 2 | 4000 USD | 1 week | 40 hours |
| 2 | **Goal:** Testing and Optimization of Writing Mechanism <br> **Number of members:** 2 | 3500 USD | 1.5 weeks | 60 hours |
| 3 | **Goal:** Implementation of File Reading Mechanism <br> **Number of members:** 2 | 4000 USD | 1 week | 40 hours |
| 4 | **Goal:** Testing and Optimization of Reading Mechanism <br> **Number of members:** 2 | 3500 USD | 1 week | 40 hours |

## Maintenance and Upgrade Plans

1. **Version Control**: We will employ a robust version control system such as Git to effectively track changes, manage different versions of the codebase, and allow for seamless collaboration between our development teams. This ensures a comprehensive record of the code evolution and aids in the quick resolution of conflicts during collaborative development.

2. **Bug Tracking and Issue Management**: A systematic bug tracking and issue management process will be put in place. This will provide visibility to known issues, allow for proper prioritization, and support an efficient process for addressing and closing them.

3. **Regular Updates and Maintenance**: Our plan includes scheduling regular updates and maintenance routines. This helps keep the software up-to-date with recent advances in related technologies, libraries, and crucial security patches, ensuring optimal performance and safety.

4. **Security Audits**: Regular security audits will be conducted to proactively identify and remediate potential vulnerabilities. This process helps ensure a secure experience for our users and maintain the integrity of our system.

5. **Feature Enhancements**: We will actively gather customer feedback and monitor evolving market requirements to plan and implement new features or improvements, enhancing the functionality and usability of the audio container over time.

6. **Testing and Quality Assurance**: Rigorous testing methods, including unit testing, integration testing, and stress testing, will be implemented throughout the development process. This ensures high-quality software and minimizes the risk of unexpected issues in production.

7. **Documentation Updates**: As the project evolves, our team will update and maintain comprehensive documentation. This includes detailed explanations of the codebase, implementation strategies, and user manuals, aiding both future development and user understanding.

8. **Code Reviews**: Our team will conduct regular code reviews to maintain high-quality code. This encourages knowledge sharing, identifies potential bugs early, and ensures coding standards are maintained.

9. **Continuous Integration and Deployment**: A Continuous Integration and Deployment (CI/CD) pipeline will be set up to automate testing, building, and deploying new updates. This process increases our development efficiency and helps maintain high-quality, reliable software.

10. **Feedback Loop**: We'll establish an efficient feedback loop involving users, developers, and stakeholders. This keeps future development aligned with real-world needs and expectations and improves user satisfaction.

11. **Collaboration and Knowledge Sharing**: We will cultivate a culture of collaboration and knowledge sharing within our team, which encourages innovation and benefits the project by harnessing each member's expertise and creativity.

# Team

## Team Members

- Bomi Mosuro - @boombomi 
- Gabriel Domanowski - @GGG1998

## Team Member LinkedIn Profiles

- https://www.linkedin.com/in/bomi-mosuro-717261111/ 
- https://www.linkedin.com/in/gabriel-domanowski-0b48a8144/

## Team Website

https://www.those.app/

## Relevant Experience

Bomi, the founder and CEO of The House of Sounds, brings over 20 years of invaluable experience as a musician, producer, and songwriter to the table. The conception and development of the .tkn audio format are testament to his innovative vision for the future of the music industry.
Gabriel, our Principal Software Engineer, possesses eight years of experience in the field of software engineering. His significant contribution to the Tenset project in the cryptocurrency sector, which reached the top 100 in 2021, showcases his technological prowess. As a co-founder, he's proven his leadership abilities by managing team recruitment, conducting project risk analysis, budget planning, team training, and overall project management during periods of growth and time pressure.
Currently, as our IT Manager, Gabriel utilizes his past experiences and skills to guide our team towards the successful completion of projects. His technical knowledge, combined with Bomi's deep understanding of the music industry, ensures our team is well-equipped to revolutionize the music landscape with the introduction of the .tkn audio format.

## Team code repositories

https://github.com/HouseOfSounds/house-of-sound
https://github.com/HouseOfSounds/hos-backend-updated

# Additional Information
FileCoin Website
bomi@those.app

House of Sounds is a UK-registered audio technology company with a significant background in blockchain technology. Last year, we had the opportunity to participate in Block Dojo, a blockchain-focused incubator. This experience has culminated in the successful completion of our first application - BEATLAB, a tool that promotes creative collaboration in the audio space.

Our proposed audio format will be seamlessly integrated into BEATLAB upon its completion. This will grant users the capability to convert their creative projects into our proprietary format directly within the BEATLAB environment. In addition to this, users will be provided with the option to distribute their audio files or songs directly to their preferred streaming platforms. This process encapsulates our commitment to providing an all-encompassing solution that simplifies and enhances the music creation and distribution experience.

**Comment by realChainLife** [comment]
Hi @ThoseApp this proposal is incomplete. Please update this in case it was an error, otherwise we will close this issue.

**Comment by ThoseApp** [comment]
Hi @realChainLife thanks for letting me know. I left all the answers between the comment syntax () which is why they weren't visible. I have rectified this and appreciate your patience and consideration.

**Comment by ErinOCon** [comment]
Hi @ThoseApp, thank you for your proposal and for your interest in our grants program. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
