### ISSUE TITLE
Glacier Network - Decentralized Database on Top of Filecoin

### ISSUE THREAD

**Issue by GlacierNetwork** [filecoin-project/devgrants#1614]
# Open Grant Proposal: `Glacier Network` 

**Project Name:**Glacier Network

**Proposal Category:**  `Developer and data tooling`

**Individual or Entity Name:** Glacier Labs

**Proposer:** https://github.com/glacier-labs

**(Optional) Filecoin ecosystem affiliations:** N

**(Optional) Technical Sponsor:** N

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

**Problem Statement:**
The decentralized database is a missing piece in Web3. Currently, most Dapps still rely on centralized cloud services, like AWS, which pose risks such as single points of failure and privacy leakage and also go against the core principles of Web3. In the current trend, we observed there are many protocols starting to build on permanent storage layers like Filecoin, but there is a big gap in processing large amounts of on-chain data between the applications and storage layers, so a decentralized database middleware is needed. 

**Glacier Network - Programmable Data Composability**
Glacier is building a composable, modular and scalable L2 data network for large-scale Dapps. Glacier empowers decentralized apps (DApp) to build on decentralized databases (DDB). It provides programmable data composability powered by L2 rollup solutions to seamlessly and effortlessly handle datasets with NoSQL GlacierDB on top of Filecoin and more.

**Project Highlights**
- Over 250k on-chain CRUD, 80k collections, 50k datasets and 30k addresses created on GlacierDB
- Modularization & Decentralization Secured by L2 rollup solutions
- Fully support MongoDB-like NoSQL and CRUD
- Programmable large KV store and dynamic datasets
- Apply ZK proofs to verify queries in the cache
- Integrate encryption protocols for access control of columns
- Develop web3 Dapps like web2 seamlessly with ultra-low cost
- Each row in a collection is a dynamic NFT
- Data curation & incentives in Stablecoin & Tokens

## Impact 

Glacier Network is building a composable, modular and scalable decentralized database on top of Filecoin storage, empowering decentralized apps (DApp) to build on Filecoin ecosystem.

The pain points Glacier seeks to address is that we know the decentralized storage layer is designed primarily for maintaining data immutability but not ideal for requiring data with frequent updates on-chain. GlacierDB provides an efficient way to manage large amounts of dynamic data and control access to it on top of filecoin, utilizing FVM.

Web3 is returning to the core tenet of decentralization to guard against data insecurity and all the challenges associated with centralized solutions. In the first phase, web3 developers are realizing the importance of decentralized databases in full-stack decentralization. They are starting to transfer from the centralized services to decentralized databases on Filecoin. In the second phase, Glacier will be the programmable data composability layer powered by L2 rollup solutions to allow developers to seamlessly and effortlessly handle datasets with NoSQL GlacierDB on top of Filecoin.

![GlacierDB User Growth](https://github.com/filecoin-project/devgrants/assets/119845846/8be11ce5-abdb-4482-b559-302e79cfbf56)

## Outcomes

Final Outcome of Glacier Features:

**- Composable, Modular & Scalable NoSQL Structure** 
The core of Glacier Network is a composable, modular and scalable NoSQL database—GlacierDB. It is built for resilience, immutability, interoperability, and the highest levels of data privacy and security in Web3.

**- Large-scale On-chain Adoption with ZK-Rollup**
Glacier powers massive amounts of data in production and fully mines the on-chain data to provide better data services to users. Modularization and decentralization is secured by zk-rollup.

**- Built On the Top of Permanent Storage**
Glacier applies Filecoin to store, share, and host datasets at scale to make the storage and query fully secure.

**- Mint & Build Your Own Datasets in One Minute**
With Glacier, developers can securely mint and build their own database in a permissionless way that enables Web3 devs to utilize data easily and effortlessly with ultra low cost.

## Adoption, Reach, and Growth Strategies

Some of the target audience include but not limited to the following: 

**- SocialFi:** Glacier helps the SocialFi developers to store the Web3 natives’ social connection data in a structural way. SocialFi developers could use the GlacierDB engine to build a social graph for their users.

**- GameFi:** Glacier could help GameFi developers store, update, manage, and query the metadata of the NFTs in the Games easily.

**- NFT**: Glacier will be one of the most professional and user-friendly database protocols that store NFT metadata in the NoSQL data structure.

**- Defi:** Glacier leverages full-stack decentralization to empower the permanence of on-chain transactions, providing an immutable and tamper-proof record. 

The theme of web3 decentralization is gaining more attention and the tools are growing to match it. Our GTM strategy is tailored at getting Pseudo-decentralized Dapps up to speed in becoming fully decentralized. Currently, over 250k on-chain CRUD, 80k collections, 50k datasets and 30k addresses have been created on GlacierDB.

![Market Opportunity](https://github.com/filecoin-project/devgrants/assets/119845846/dd16c9b5-cfcf-42e2-9d1b-9ff3e5be2db5)
 
## Development Roadmap

**Milestone 1: Permissionless Database On Filecoin ** 

- Functionality: Mainnet Alpha on Filecoin
- How many people: 5 ppl
- How much time this milestone will take to achieve: 2 months, have completed in June, 2023.

**Milestone 2: Strategic Marketing Approach on Filecoin FVM ** 
- Functionality: Fostering Dapp Development on Filecoin by utilizing GlacierDB
- How many people: 8 ppl
- How much time this milestone will take to achieve: Q3 2023

**Milestone 3: Decentralized Database Powered By ZK-Rollup ** 
- Functionality: Leveraging L2 rollup technology to anchor the security and decentralization of GlacierDB.
- How many people: 11 ppl
- How much time this milestone will take to achieve: Q4 2023

**Milestone 4: Infrastructure of Programmable Data Composability **

- Functionality: A programmable data composability layer powered by L2 rollup solutions, supporting multi-chains solutions. 
- How many people: 14 ppl 
- How much time this milestone will take to achieve: Q2 2024

**Technical Stack:**
The core of Glacier protocol is a fully decentralized NoSQL database service. We call it GlacierDB, built for resilience, scale, and the highest levels of data privacy and security in Web3. With GlacierDB, Web3 developers can easily build their own database in a decentralized and secure foundation that enables Web3 devs to store and deal with the data easily and effortlessly.

GlacierDB technical stack mainly consists of the following layers:
1. Web3 DApps, which are accessing the Glacier decentralized protocol through Glacier Dev SDK.
2. Glacier decentralized protocol, which is the main part of GlacierDB and consists of the following segments:
- Glacier Dev SDK
- Glacier NoSQL Access Protocol
- Database Engine Shards
- Database Transaction Rollup (Data Transactions Rollup)
- Data Permanent Availability Network
- L1 (Layer 1) Settlement
- Indexer Network
3. The permanent storage layer of the Glacier database, which is currently compatible with Filecoin storage.

## Total Budget Requested

| Milestone # | Description | Deliverables | Completion Date | Funding |
| ---- | ---- | ---- | ---- | ---- |
|Milestone 1 | Permissionless Database On Filecoin | Building a composable, modular and scalable L2 data network on top of Filecoin | June, 2023 |Self-supported|
|Milestone 2 | Strategic Marketing Approach on Filecoin FVM | Enabling and onboarding Dapps to GlacierDB on top of Filecoin FVM | Q3 2023| $1000 |
|Milestone 3 | Decentralized Database Powered By ZK-Rollup| Leveraging L2 Zk-Rollup technology to anchor the security and decentralization of the Layer 1 chain | Q4 2023| $500 |
|Milestone 4 | Infrastructure of Programmable Data Composability |A middleware infrastructure layer to support multi-chain solutions | Q2 2024| $500 |

## Maintenance and Upgrade Plans

**Future Work & Upgrade Plans:**

**1. Decentralized Identity**
In Web3, the data is owned by an on-chain address that has the owner key of the related data. However, the on-chain address alone is insufficient for identifying the profile or recording the identity and social graph. Worse, anyone could easily create hundreds of on-chain addresses in seconds. This means that someone is required to integrate all the on-chain data to form a one-chain Identity, which could be used in the logins, social connections, reputation system and credit finance of the Web3 space.

**2. Data Cross Rollup**
Today, crypto assets are easily transferred between Ethereum mainnet and Rollups, while the data on different Rollups are still unable to realize the Cross-rollup transfer or interoperability, which greatly limits the integration and potential of Web3 data. Therefore, Glacier will research how to achieve the cross-rollup transfer between different Rollups to make the data flow easily in the tens of Rollup chains in the future.

**3. Graph Database for Web3 Social Graph**
Web3’s openness creates a great foundation for building a user social graph which has not been achieved in Web 2.0 due to the data barriers. When creating the social graph in Web3, developers have to deal with a great load of on-chain data which is not structurally stored on the blockchain nodes. In Web2.0, the graph database, one of the important NoSQL database types, stores the user's social connection data to create a social graph. Therefore, Glacier will consider releasing a dedicated Graph Database SDK to help Web3 developers create the social graph more easily.

# Team

## Team Members

Kevin Hsu: Co-founder & Lead Initiator
Jacky Lee: Co-founder & Lead Engineer
Agbona Igwemoh: Lead Manager
Bart Yang：Senior Blockchain Engineer

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/yingkaixu/
https://www.linkedin.com/in/agbona/
http://www.linkedin.com/in/jacky3-meta
https://www.linkedin.com/in/bartyang/

## Relevant Experience

The Glacier team has a strong background in Web3 development and cloud storage. The CTO was leading the engineering team both in Micloud and Kingsoft cloud, developing an object storage system(like AWS S3) with EB-level scalability, adeptly tackling challenges such as system scalability, access latency, data consistency, and high availability among thousands of data nodes under immense data pressure, all while catering to hundreds of millions of global users.

Additionally, the team participated in the design of a high-performance distributed KV metadata storage built on RocksDB and possesses a profound understanding and practical experience with distributed NoSQL database technologies such as MongoDB, Cassandra, and Redis.

The team has a wealth of experience in blockchain technology development and has successfully applied Ethereum, Polkadot, ZK-SNARK Circuit, and Cosmos technology platforms in numerous prominent projects, contributing to the construction of future blockchain infrastructure and applications for the community.

## Team code repositories

# Additional Information
 

1. We have been closely following Filecoin ecosystem and integrating with Filecoin.
2. Email address: info@glacier.io
3. **Resources & Links**
- Website: https://glacier.io/
- Intro Video: https://youtu.be/LpFBz86QizA
- Whitepaper: https://docsend.com/view/83c74bw4dvb6mwzj
- FAQ: https://docs.glacier.io/faq

**Products & Solutions**
- Demo in Browser: https://youtu.be/b6GOxHS6El8
- Demo in Terminal: https://youtu.be/zfxURf0O8os
- Testnet: https://playground.fil.glacier.io/
- Explorer: https://scan.fil.glacier.io/
- SDK: https://docs.glacier.io/developers

**Comment by ErinOCon** [comment]
Hi @GlacierNetwork, thank you for your proposal! To the total amount requested for this project is $2,000, correct?

**Comment by GlacierNetwork** [comment]
> Hi @GlacierNetwork, thank you for your proposal! To the total amount requested for this project is $2,000, correct?

Correct. Thank you for your feedback, if you have any questions to us, please feel free to let us know.

**Comment by ErinOCon** [comment]
Hi @GlacierNetwork, thank you for your proposal and for your patience during our review process. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue building!
