### ISSUE TITLE
Cloak - On-chain Cryptocurrency Dark Pool

### ISSUE THREAD

**Issue by sreeduggirala** [filecoin-project/devgrants#1615]
# Open Grant Proposal: `Cloak`

**Project Name:** Cloak

**Proposal Category:** `Applications`

**Individual or Entity Name:** Noir Labs

**Proposer:** `sreeduggirala`

**(Optional) Filecoin ecosystem affiliations:** Noir Labs' founders are from Texas Blockchain, the Web3 student organization at the University of Texas at Austin. We hosted Filecoin at [Texas Blockchain's 2nd Annual Consensus Welcome Event](https://www.eventbrite.com/e/texas-blockchain-second-annual-welcome-reception-consensus-2023-tickets-579283581787). Texas Blockchain also attended the Consensus 2023 Filecoin Student Meetup. 

**(Optional) Technical Sponsor:** N

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

High-capital cryptocurrency traders today face complex challenges across on- and off-chain trading platforms. 

**On-chain: Maximal Extractable Value (MEV):**
On-chain, concerns like Maximal Extractable Value (MEV) enable front-running, back-running, and sandwich attacks through selective pre-trade visibility. Since validators and block builders can view transactions prior to their commitment on-chain, this enables them with alpha, incentivizing predatory trading strategies. 

**On-chain: Post-trade Transparency**
Blockchain's transparency allows effortless querying of past states from the genesis block. This allows for wallet activity tracking, potentially undermining their competitive edge by dissecting past trades. 

**Off-chain: Insider Trading and Front-running**
Off-chain scenarios are equally problematic, as centralized order books and alternative trading systems (i.e. OTC) are inherently trust-based: operators can leverage their privileged order book visibility to insider trade and front-run. This is especially prevalent in alternative trading systems (ATS), where countless operators were fined tens (if not hundreds) of millions in improper data management cases.

**Slippage and Market Impact**
In public markets, substantial orders (even AMM trades) are subject to significant slippage and market impact when paired with insufficient liquidity. Furthermore, large non-marketable orders may entail quote fading. TWAP and equivalent slippage mitigation strategies aren't entirely efficient, as they too suffer from price fluctuations. 

# Solution

Cloak is a non-custodial cryptocurrency dark pool, offering trustless, MEV-resistant, and slippage-resistant trades for _any_ ERC-20 trading pairs.

Cloak leverages zero-knowledge proofs (zkp) to ensure end-to-end privacy throughout a trade's lifecycle with off-chain matching and on-chain settlement (with zkp). By executing trades at the National Best Bid and Offer (NBBO) midpoint, Cloak guarantees optimal execution prices for its users.

## Impact 

**Addressing Pain Points:**
- **Privacy:** Cloak's use of zero-knowledge proofs ensures end-to-end privacy, a critical need in the cryptocurrency space where transaction details are often public, exposing users to potential risks.
- **MEV Resistance:** By offering MEV-resistant trades, Cloak protects users from sandwich attacks, front-running, back-running, and similar predatory trading strategies.
- **Slippage Resistance:** Cloak's slippage-resistant trades tackle the problem of significant price discrepancies that traders face during execution, enhancing the overall trading experience.

**Benefits of Getting It Right:**
- **Institutional Crypto Adoption:** Cloak's privacy and security features will attract users seeking a safer and discreet trading environment, increasing overall user confidence in Filecoin and crypto as a whole.
- **Increased Liquidity:** As Cloak ensures optimal execution prices by trading at the NBBO midpoint, it encourages more users to participate, resulting in increased liquidity for ERC-20 trading pairs.
- **Ecosystem Growth:** As liquidity aggregates on Filecoin through Cloak, building atop FVM could soon become a standard for DeFi due to abundant capital, applications, and builders. 

**Risks of Not Getting It Right:**

Other than smart contract risk, Cloak's main risk is lack of adoption. 

If financial institutions seek an off-chain alternative (i.e. OTC desks) without regard for centralization, front-running, and insider trading, on-chain activity could be inhibited. If Cloak garners less traction than expected, traders will continue to be victimized by MEV and trade tracking.

**Project Impacts and Success**

- **Trading Volume:** One of the primary indicators of success would be the total trading volume facilitated by Cloak's dark pool. Higher trading volume indicates increased adoption and usage of the platform, which, in turn, would contribute to higher liquidity for the supported ERC-20 trading pairs.

- **Number of Users and Active Traders:** The growth in the number of users and active traders on the Cloak platform would signify its appeal to the cryptocurrency community. A higher user base suggests that the project has successfully addressed pain points and provided solutions that resonate with traders.

## Outcomes

Our project plan for Cloak aims to achieve the goals of creating a trustless, MEV-resistant, and slippage-resistant cryptocurrency dark pool that guarantees optimal execution prices while ensuring end-to-end privacy throughout the trade lifecycle. To accomplish this, we will adopt the following methodologies, technologies, and resources:

**Secure Off-Chain Matching:** We will implement hardware-assisted isolation technology to ensure obscured, secure, and efficient off-chain matching. This will minimize latency while maintaining trustlessness through on-chain settlement via zero-knowledge proofs of valid matches. 

**Non-custodial Trading:** Unlike CEXs, where fund storage is trust-driven, Cloak champions non-custodial trading through smart contract-based deposits/withdrawals. Furthermore, balances are only accessible by the wallet of the depositor. 

**Permissionless:** Contrary to CEXs, token listing is not team-driven. Rather, users can establish markets to facilitate discreet trades for any ERC-20 pair. 

## Adoption, Reach, and Growth Strategies

Our target audience can be classified into two sections: on-chain whales and institutions. We seek to engage the latter via MEV- and CeFi/TradFi-related risks. Furthermore, we will highlight the **$150 million** generated by MEV in 2022 through predatory trading strategies (i.e. sandwich attacks). 

Furthermore, our platform will offer 0% trading fees for a limited time to facilitate user growth and interest. 

## Development Roadmap

The project is expected to take 9 months to complete, with a July 1st start date (including security audits, beta testing, and multi-chain support).

**Q3 2023** (2,500 USD)
- Whitepaper v1
- Smart contracts, matching engine, hardware procurement/financing, front-end (MVP)
- API

**Q4 2023** (10,000 USD)
- WBTC/USDC, WBTC/USDT, WBTC/DAI, WETH/USDC, WETH/USDT, WETH/DAI trading pair support
- Testnet deployment
- Security audit

**Q1 2024** (2,500 USD)
- Additional ERC-20 trading pairs
- Beta testing
- In-app analytics/data visualization (i.e. TradingView charts)

**Q2 2024** (5,000 USD)
- Mainnet deployment
- Crypto on- and off-ramp integration (fiat)
- KYC/AML through DID integration
- In-app wallet integration (i.e. Coinbase WaaS)

## Total Budget Requested

**Grant Request:** 20,000 USD

**Grant Allocation:** 
- **MVP (100%):** The grant will be dedicated to building Cloak (front-end, smart contracts, matching engine, hosting services) and procuring necessary tooling. This grant would prove instrumental in designing a sophisticated UI/UX and robust end-to-end solution.

## Maintenance and Upgrade Plans

Upon the launch of our MVP (Q4 2023), we will sequentially add these features: 

**Bridge Aggregator SDK Integration:** For aggregating liquidity across blockchain ecosystems and creating a unified UX, Cloak will leverage a bridge aggregator SDK (i.e. LI.FI). 

**On- and Off-Ramp Integration:** A pressing concern with DEXs is crypto to and from fiat. To alleviate this friction, we will integrate on- and off-ramp solutions (i.e. MoonPay) to seamlessly deposit/withdraw from Cloak. 

**API:** Cloak will offer APIs to facilitate trade automation for advanced users and trading algorithms. This will cater to a plethora of institutional _and_ retail traders. 

**In-App Analytics and Price Charts:** The platform will include in-app analytics and price charts, integrating the likes of TradingView's SDK for technical analysis.

**KYC/AML via DID Integration:** To ensure regulatory compliance, Cloak will integrate Decentralized Identifiers (DID) for Know Your Customer (KYC) and Anti-Money Laundering (AML) procedures. 

**In-App Wallets for Non-Web3 Native Users:** For users unfamiliar with Web3, we will offer in-app wallets through Coinbase's Wallet as a Service (WaaS).

**CEX-like UI/UX:** We will prioritize a user-friendly and intuitive UI/UX, similar to centralized exchanges (CEX), effectively streamlining the trading and sign-up processes. 

# Team

## Team Members

Sreevanth (Sree) Duggirala - CEO
Shantikiran Chanal - CTO
Dr. Cesare Fracassi (Advisor)
Dr. Sriram Vishwanath (Advisor)

## Team Member LinkedIn Profiles

[Sree Duggirala](https://www.linkedin.com/in/sreevanthduggirala/)
[Shantikiran Chanal](https://www.linkedin.com/in/shantikiran-chanal-a880641b6/)
[Dr. Cesare Fracassi](https://www.linkedin.com/in/cesare-fracassi-545ab/)
[Dr. Sriram Vishwanath](https://www.linkedin.com/in/sriramvishwanath/)

## Team Website

https://noirlabs.io

## Relevant Experience

**Sreevanth Duggirala (CEO):**

[LinkedIn](https://www.linkedin.com/in/sreevanthduggirala/), [Twitter](https://twitter.com/sreethereum)

Sreevanth (Sree) Duggirala is an undergraduate Electrical and Computer Engineering (ECE) Honors student at the University of Texas at Austin. As Director of Labs at Texas Blockchain (UT Austin's Web3 student organization), Sree founded and spearheads the competitive hackathon team. Furthermore, Sree is a seasoned Solidity developer, zk and MEV researcher, and Quantitative Analyst Intern at Bison Fund. 

**Shantikiran Chanal (CTO):**

[LinkedIn](https://www.linkedin.com/in/shantikiran-chanal-a880641b6/), [Twitter](https://twitter.com/shantikiranc)

Shantikiran Chanal is an undergraduate Computer Science student at the University of Texas at Austin. As the Directory of Treasury at Texas Blockchain, Shantikiran oversees the club's (and its DAO's) finances. Additionally, Shantikiran possesses extensive experience in zk and MEV research, full-stack development, and data science.

**Dr. Cesare Fracassi (Advisor):**

[LinkedIn](https://www.linkedin.com/in/cesare-fracassi-545ab/), [McCombs School of Business](https://www.mccombs.utexas.edu/faculty-and-research/faculty-directory/cesare-fracassi/), [Google Scholar](https://scholar.google.com/citations?hl=en&user=fdn3oJoAAAAJ)

Dr. Cesare Fracassi is the Chief Economist of the Coinbase Institute and Assistant Professor at the McCombs School of Business (University of Texas at Austin). Dr. Fracassi also directs UT Austin's Fintech Research Lab, supervising research on zero-knowledge proofs, AI-driven decentralization analysis, DeFi protocol hacks, and MEV. 

**Dr. Sriram Vishwanath (Advisor):**

[LinkedIn](https://www.linkedin.com/in/sriramvishwanath/), [Cockrell School of Engineering](https://www.ece.utexas.edu/people/faculty/sriram-vishwanath), [Google Scholar](https://scholar.google.com/citations?user=SOB-2hQAAAAJ&hl=en&oi=ao)

Dr. Sriram Vishwanath is a serial entrepreneur and Electrical and Computer Engineering (ECE) Professor at The University of Texas at Austin. Dr. Vishwanath also spearheads [ChainHub Foundation](https://csl.chainhub.foundation/), a Web3 incubation foundation supporting non-profit and academic blockchain organizations. 

## Team code repositories

Although we haven't worked on a DEX prior to this project, here are a few of our past hackathon/personal projects: 

[**ZK Magic Square**, a mathematical puzzle primitive built in ZoKrates](https://github.com/sreeduggirala/vrf-raffle)
[**Alias**, an AI-based 3D NFT avatar creation tool](https://github.com/sreeduggirala/Alias)
[**VRF NFT Raffle**](https://github.com/sreeduggirala/vrf-raffle)
[**Solace**, a trustless incident reporting platform](https://github.com/shondle/Solace)

# Additional Information

We learned about Filecoin's grants via the website and DevRel. 

### Email
sree@noirlabs.io

## Previous Work

**ChainHub Crypto Summer Lab (CSL):** Our team, Noir Labs, recently partook in ChainHub's CSL, a 6-week accelerator program with Lightspeed Venture Partners and Polychain Capital. In addition to participating in rigorous seminars regarding zero-knowledge proofs, market making, and AI, our team pitched for 30+ VCs/angel investors.

**Fintech Research Lab:** Both founders are research assistants at UT Austin's Fintech Research Lab, a selective undergraduate research cohort. Sree's research is rooted in applied cryptography, entailing hardware-assisted security solutions (PUFs, RoTs, HSMs, SEs, etc.) and smart contract development with zero-knowledge proofs (with ZoKrates). Shantikiran's research involves analytics-driven decentralization analysis on Ethereum governance and EIPs, factoring in proposer reputation, network status, and broader community sentiment.

**Texas Blockchain:** Both founders are executives at Texas Blockchain, UT Austin's Web3 student organization. We spearhead this club, championing blockchain/crypto on campus and in the greater Austin area. Our club has organized hackathons, speaking panels, incubator programs, research and writing cohorts, and internship pipelines with forerunners in Web3. 

**Web3 Hackathons:** Our team comprises competitive hackers, participating in the likes of Scaling Ethereum 2023, HackFS 2023, Chainlink Fall 2022, Chainlink Spring 2023, Consensus Web3athon 2023, and more!

**Comment by ErinOCon** [comment]
Hi @sreeduggirala, thank you for your proposal. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best of luck as you continue building!
