### ISSUE TITLE
Next Step Microgrant: Decentraclasses

### ISSUE THREAD

**Issue by HiberNuts** [filecoin-project/devgrants#1616]
### 1. What is your project, and what problem does it solve? (max 100 words)

Decentraclasses is a decentralised ed-tech platform in India that aims to decentralize education and empower learners to monetize their knowledge through staking in their own courses. By bridging the gap between web2 and web3 awareness, providing mentorships, and offering tradable courses with lifelong incentives, Decentraclasses enables individuals to leam, earn, and test their skills in a decentralized manner, fostering a more inclusive and rewarding learning experience.

### 2. Project links
  
Link to Github repo: https://github.com/DecentraSchool/decentraclasses
Link to demo or website: https://decentraclasses.vercel.app/
Socials: https://bento.me/decentraclasses

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
Decentraclasses uses Polybase for decentralized web3 based database storage provider. Polybase uses filecoin under the hood to store the user data on chain. Along with polybase we also use Lighthouse (Filecoin based web storage provider) to seamlessly host our video content onto filecoin and stream video to users. The user experience is highly enhanced by using web3 based storage providers. Also we are in constant communication with teams/Founder at both technologies to help us for any bottlenecks.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
  No, we ourselves are not developing on FVM but use lightouse as our storage provider.
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |KickStart and first product  |  The alpha version of the Product is in progress with user authentication and buying of courses and Video-based Assessment and a Strict Assessment Policy, PR and Community Building   |  ~1 Month  | 
| 2.     | Feature improvement 1                       |  Course Selling feature with rewards based on performance. Marketing and Promotions, EARN Features will be-Community Monetization. Partner up with companies to list Bounties/Surveys and Micro Tasks, Partner up with companies to list jobs/internships.   |   ~1.5 months                        | 
| 3.     | Feature improvement 2                        |      NFT-based Course Completion - Proof of Learning. Mentorship and 1:1 session connect with Industry experts. Customized ROADMAP based on user behaviors.   Project Based Learning (Practical Hands-on experience), Cohorts and short content courses                                                 | ~2months                           | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

  YES!
### 6. Does your proposal comply with our Community Code of Conduct?

YES!
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Aryan Ghosh, Founder (Decentraclasses)
Ex Co-founder of EVNTORG.COM
Expertise - Fintech, Ed-etch, e-commerce etc.
https://twitter.com/aryanghosh001

Raghav Jindal, Co-Founder & Tech Lead
Intern at TNEA (Tamil nadu engineering association) and Cookr.in
https://github.com/HiberNuts ( CTO )

Srikar MKS, Co-Founder & Community
Ex-Founder of Devpolis
https://github.com/Srikarmk ( Frontend Dev)

* How did you learn about our microgrant program?
Throught lighthouse founders and other socials.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @HiberNuts, thank you for your proposal and for your patience with our review. Unfortunately, we will not be proceeding with a grant at this time. Wishing you the best as you continue building!
