### ISSUE TITLE
Open Grant Proposal: SaaS token gating platform with SDK

### ISSUE THREAD

**Issue by jonasesr** [filecoin-project/devgrants#1617]
# IPFS / Filecoin

# Open Grant Proposal: SaaS token gating platform with SDK

**Project Name: Whal3s**

**Proposal Category:** `Developer and data tooling`, `Applications`

**Individual or Entity Name:** Whal3s GmbH

**Proposer:** jonasesr

**(Optional) Filecoin ecosystem affiliations:** Outlier Ventures x Protocol Labs accelerator program

**(Optional) Technical Sponsor:** 

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

The Whal3s SDK allows any web2 developer to integrate NFT technology into websites, apps, and games - to build connected / "interoperable" brand experiences within e-commerce, content platforms and in real life.

To reduce the development time from a few months to a few minutes Whal3s offers

1.  Whal3s SDK: Similar to the Stripe SDK, it enables developers to incorporate token-based experiences into any app or website i.e. access control
2.  Whal3s UI components: Similar to the Stripe checkout page, it facilitates the process of users claiming utility from their tokens. ([https://www.youtube.com/watch?v=w7SIqmxJZiw](https://www.youtube.com/watch?v=w7SIqmxJZiw)) test out here: [https://whal3s.xyz/demo](https://whal3s.xyz/demo)
3.  Whal3s App - Analytics and utility dashboard: Provides insights into user engagement, on chain activity and utility consumption.

We are currently live with Ethereum and Polygon and are now looking to become, the leading provider of token gated experiences on the Filecoin network.

## Impact

The Filecoin Network especially the FVM part is still very confusing for developers. Especially for Web2 developers. Developers have to understand the concept of FVM, what role EVM plays, how to access NFT attributes, how to interact with Smart Contracts, where to get IPFS hosted data from, etc. . That is way too much knowledge that is assumed. An adaptation into the mainstream will not be able to take place in this way.

Whal3s eliminates this complexity and takes the user by the hand. He can implement token gated experiences for FVM NFTs using tools he already knows (Web App, API Endpoints and JavaScript SDK).

With Whal3s, users now have a compelling reason to embrace the Filecoin Network and leverage its advantages. By enabling more users to create NFTs on Filecoin, the project aims for every NFT and application working on this network to be considered a success. This approach not only streamlines the development process but also facilitates wider adoption of Filecoin for NFT-related ventures.

## Outcomes

The Whal3s App serves as the primary platform for creating token gates (utilities) effortlessly. In addition to Ethereum and Polygon, both their test networks are available options for users. Excitingly, the Filecoin Network, encompassing calibration and spacenet, will also be integrated, providing users with more choices and opportunities.

To ensure seamless functionality, all API endpoints are being adapted to fully support the Filecoin Network. Furthermore, the SDK is undergoing a meticulous rework, ensuring that developers can effortlessly incorporate the Filecoin network into their projects, just as effortlessly as they currently do with the existing two networks. This enhancement promises a smoother and more versatile implementation process, enabling developers to harness the potential of Filecoin alongside Ethereum and Polygon with ease.

## Adoption, Reach, and Growth Strategies

Whal3s has got some strong traction with 350 developers on the platform that have been helping and testing our infrastructure since its launch. These individual developers will not make revenue for now, instead make up the core of our community and help find bugs, test the infra etc. Instead, Whal3s concentrates on winning lighthouse customers across key industries that are converting into customers throughout late 2023.

Whal3s has already secured 12 launch customers that are going to build with our solution in late 2023, including agencies, white-label platforms, a German liquor brand, a first league football club, and a creator community with more than 100 million followers. The company has also signed letters of intent with 15 other businesses and has a sales funnel of 50 companies that it is currently in contact with.

Adding to that we are particularly targeting agencies and NFT consultancies as multipliers as we call it. Multipliers are companies and or organisations that sell our product indirectly to the brands they are working with.

### Implement Filecoin Network to Whal3s Validation Engine

-   The validation engine is an open source, stateless and serverless runtime, that validates a wallet based on the holding NFTs with respect to the requested token gate.
-   Once finished you will be able to run your own validation engine as a node script (e.g. as AWS Lambda) or use the hosted one by Whal3s. This validation engine will be able to check if a users(wallet) matches the conditions of a token gate and has the right signature. E.g. Wallet 0x123…abc owns 1 NFT with a golden background of Collection XYZ on the Filecoin Network that is not used yet.
-   Persons involved:
    -   Developers:
        -   Jonas Esser (CTO of Whal3s)
        -   External freelancer
-   Required funding: 14.000€
-   ETA: 01.09.2023-01.10.2023 → 1 Month

### Implement Filecoin Network to Whal3s App + API

-   The Whal3s app is the primary interface used (besides the API) to create token gates (utilities). The creator is guided through the process and receives help at many points, e.g. auto-completion to select smart contracts.
-   Once finished you will be able to create token gates with no-code through the Whal3s App or via simple API request
-   Persons involved:
    -   Developers:
        -   Jonas Esser (CTO of Whal3s)
    -   UX/UI
        -   External agency
-   Required funding: 8.000€
-   ETA: 15.09.2023-08.10.2023 → 3 weeks

### Implement Filecoin Network to Whal3s SDK

-   The Whal3s SDK includes all the tools needed to implement created token gates into an existing environment (web app, website, mobile app, ...), including React UI components (Modal, Connect Wallet Button, ...).
-   Once finished the Whal3s SDK will fully support Filecoin Network. You will be able to use token gates for the Filecoin Network. Including functionalities like adding network to wallet, switching network, communication with network, …
-   Persons involved:
    -   Developers:
        -   Jonas Esser (CTO of Whal3s)
        -   External agency
-   Required funding: 7.000€
-   ETA: 15.09.2023-08.10.2023 → 3 weeks

### Documentation and promotion

-   To publicize and promote the new feature, we will…
    -   write guides on how to use and host the validation engine
    -   update the documentation on how to utilise Filecoin Network NFTs with Whal3s (App, API and SDK)
    -   create a YouTube tutorial that developers follow along to build their own token gated application in under an hour
    -   write two marketing articles on medium and start a twitter series on how to write token gated applications with Filecoin Network and Whal3s
-   Persons involved:
    -   Developers:
        -   Jonas Esser (CTO of Whal3s)
    -   Marketing and Promotion
        -   Luca Post (CEO of Whal3s)
        -   Florian Zeise (COO of Whal3s)
-   Required funding: 5.000€
-   ETA: 08.10.2023-31.10.2023 → 3 weeks

## Total Budget Requested

| Milestone # | Description                                            | Completion Time | Funding  |
|:-----------:|--------------------------------------------------------|-----------------|----------|
| 1           | Implement Filecoin Network to Whal3s Validation Engine | 30 days         | 14.000 € |
| 2           | Implement Filecoin Network to Whal3s App + API         | 21 days         | 8.000 €  |
| 3           | Implement Filecoin Network to Whal3s SDK               | 21 days         | 7.000 €  |
| 4           | Documentation and promotion                            | 21 days         | 5.000 €  |

**Total budget request: 34.000€**

## Maintenance and Upgrade Plans

With Whal3s, we have laid the foundation for token gated infrastructure. In the future we will focus on developing it into an open source protocol to establish a standard for token gated utility. But also the area of usability must not be neglected. Together with our customers we want to extend the value chain by minting and analytics. Also the lowering of hurdles for Web3 foreign users is an important inventory. We will make onboarding as easy as possible to make NFTs and token gates tangible for the mainstream.

# Team

## Team Members

Luca Post (CEO)

Florian Zeise (COO)

Jonas Esser (CTO)

## Team Member LinkedIn Profiles

[https://www.linkedin.com/in/luca-post-546508127/](https://www.linkedin.com/in/luca-post-546508127/)

[https://www.linkedin.com/in/florian-zeise-27786715b/](https://www.linkedin.com/in/florian-zeise-27786715b/)

[https://www.linkedin.com/in/jonas-esser/](https://www.linkedin.com/in/jonas-esser/)

## Team Website

[https://www.whal3s.xyz/](https://www.whal3s.xyz/)

## Relevant Experience

Co-founders profiles:

1.  Luca Post (CEO): Luca's background in economics, coupled with his three years of experience at Hertha Berlin, a German first league soccer club, has given him valuable insights into the world of web3 offerings and NFTs. His leadership in the new business department, reporting directly to the CFO, involved overseeing web3 initiatives, building an internal metaverse, and developing NFT offerings, licensing deals, and 3D fan experiences. His experience and expertise in this domain provide us with a strong foundation in understanding the potential and practical applications of NFT technology.
2.  Jonas Esser (CTO): Jonas's journey as a full-stack developer and tech lead in an agency for the past seven years equips him with extensive technical knowledge and problem-solving skills. His exposure to diverse client projects across various industries allows him to approach challenges with a broad perspective. Moreover, his passion for crypto, starting with IOTA (as a contributor to some community projects) and later embracing Ethereum since 2016, ensures that he is at the forefront of the latest developments in the blockchain and crypto space. This invaluable experience positions him as a key asset in architecting and implementing cutting-edge solutions within our NFT-focused venture.
3.  Florian Zeise (COO): As the third co-founder, he brings a background in venture capital at Earlybird and Richmond View Ventures with a particular focus on web3 and B2B SaaS companies. His experience over the last three years has provided him with an understanding of emerging technologies and trends in the web3 space. Prior to this venture, Jonas and Florian co-founded Dayone, a social media fitness platform empowering fitness creators to monetize their audience. This prior entrepreneurial experience enables him to contribute insights into building and scaling platforms while keeping the end-users' needs at the forefront.

## Team code repositories

[https://github.com/Whal3s-xyz](https://github.com/Whal3s-xyz)

# Additional Information

-   We were part of the Outlier Ventures IPFS Base Camp and we have been recommended the Filecoin Grant
-   Please contact jonas@whal3s.xyz (Jonas Esser) to discuss the grant agreement and next steps
-   Check out our demos or check our current state of the project:
    -   E-Commerce Demo: [https://www.whal3s.xyz/demos/commerce](https://www.whal3s.xyz/demos/commerce)
    -   Documentation: [https://docs.whal3s.xyz/](https://docs.whal3s.xyz/)
    -   Whal3s App: [https://app.whal3s.xyz/](https://app.whal3s.xyz/)

**Comment by ErinOCon** [comment]
Hi @jonasesr, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!
