### ISSUE TITLE
Next Step Microgrant: Domain Studio

### ISSUE THREAD

**Issue by gupta977** [filecoin-project/devgrants#1619]
### 1. What is your project, and what problem does it solve? (max 100 words)
Introducing Domain Studio, the revolutionary solution for companies seeking complete control and security over their domain names. Say goodbye to the hassle of creating individual use cases for domain names. Our platform empowers companies to sell or mint domain names with customized pricing and images using our seamless React DApp. 

With this application, companies can stay within their own website ecosystem while enjoying the benefits of a Web3 domain. Our system ensures that wherever a domain is minted, it seamlessly integrates with the ecosystem. This eliminates the need for additional domain execution work, saving time and effort.

What's more, companies can leverage our platform to create unique logic and applications that automatically work for other domains within the Web3Yak network. Unleash your brand's potential and stay ahead in the web3 revolution.

### 2. Project links
  
Link to Github repo: https://github.com/web3yak/web3domain-studio

 
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

Every domains contains records, images which is all based on IPFS using NFT.Storage API. 

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
This is open source free DApp which companies can fork it and make their adjustment. With this all domain minting part is done at companies with white labeled website.
We will be creating a multiple use case to support the domain minted.
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |              3 weeks completed -  DApp interface done.  
| 2.     |              4th Week   -  Mint service with IFPS record                      
| 3.     |               5th Week  - Own public record with social handles and wallet addresses    
| 4.     |               6th Week  - Full documentation, Demo site, Download link 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
It's for the first time we are doing and as to our knowledge non of the companies has made this yet. 
Free open source DApp which works instantly without any coding which can create next ENS like domain provider. 
  
### Additional questions:
Navneet Gupta
https://github.com/gupta977
Not submitted or participated in Hackathon. This project takes long time to build & testing. It cannot be completed in short time of hackathon. 
Not Exactly but similar functionality based on Wordpress Application was submitted.
The link is : https://ethglobal.com/showcase/web3yak-domain-studio-pqcpe

After this we deep conversation with some of the company and web3 individuals, suggested to create react based application with long term continues development. 
The main part is, company will host their app so that they will have full control.

As a small company we are unable to continue development thus applying for it. 
Thank you

**Comment by gupta977** [comment]
We are almost done,
Please have a look at
https://w3d-fvm.vercel.app/
https://w3d-fvm.vercel.app/domain/info/admin.filecoin

**Comment by gupta977** [comment]
![Hosting-Account-Management-Panel (1)](https://github.com/filecoin-project/devgrants/assets/49977216/38d0486b-1024-499f-a3fb-e390e0e2f2f0)

We have attached a invoice which is already paid for the hosting.

**Comment by ErinOCon** [comment]
Hi @gupta977, thank you for your proposal and for your patience with our review process. It's great to see this project continue to progress. Unfortunately, after much consideration, it has been determined that we will not be be moving forward with a new grant at this time.

If you have any questions for our team, please feel welcome to contact us at grants@fil.org. Wishing you the best as you continue to build.
