### ISSUE TITLE
Next Step Microgrant: JamiiLab - incentivizing citizen science & data crowdsourcing 

### ISSUE THREAD

**Issue by bashybaranaba** [filecoin-project/devgrants#1620]
### 1. What is your project, and what problem does it solve? (max 100 words)
JamiiLab is a decentralized citizen science and data crowdsourcing platform that aims to incentivize long-term engagement and commitment through gamification and rewards to participants for their contributions to scientific projects. 

### 2. Project links
  
Link to Github repo: https://github.com/bashybaranaba/jamiilab
Link to demo or website: https://jamiilab.vercel.app
License: MIT License

### 3. a) How is IPFS, Filecoin, or related technology used in this project?
Filecoin VM: for the deployment of the smart contract governing the rewarding mechanism for participants engaged in crowdsourcing and citizen science initiatives.
Web3 Storage for File Storage: for secure and reliable storage of project-related files, such as images associated with each project.
Polybase: for efficient and secure data management.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
The main objective for this grant is to enhance JamiiLab by focusing on three key areas: reworking smart the contract, implementing gamification elements, and improving the user interface
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | Reworked smart contract |Optimizing the smart contract governing the rewarding mechanism for participants engaged in data crowdsourcing and citizen science initiatives. |  4 weeks | 
| 2.     | Gamification Elements  | Design and implement a points, badges, and achievements system for enhanced engagement.  |  4 weeks  | 
| 3.     | Improved UI  |Revamp the user interface for improved usability and visual appeal. This will include a new landing page and a responsive web user interface. |  4 weeks  | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Link to HackFS 2023 Hackathon Submission: https://ethglobal.com/showcase/jamiilab-9z60q

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Baranaba Mugabane
Github: https://github.com/bashybaranaba
Email: [bashybaranaba@gmail.com](mailto:bashybaranaba@gmail.com)
Role: Fullstack dev

* How did you learn about our microgrant program? Filecoin's grants page. Also got an email from protocol.ai encouraging to apply
* If your project was created as part of an event or hackathon: 
  * What was the name of the event? HackFS 2023
  * Please link to your hackathon submission
  https://ethglobal.com/showcase/jamiilab-9z60q

**Comment by ErinOCon** [comment]
Hi @bashybaranaba, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant for this project. Please feel welcome to contact our team at [grants@fil.org](mailto:grants@fil.org) with any questions.

Wishing you the best as you continue to build!
