### ISSUE TITLE
Next Step Microgrant: Patch for Graph Nodes to handle Filecoin's null tipset rounds

### ISSUE THREAD

**Issue by levlite** [filecoin-project/devgrants#1622]
### 1. What is your project, and what problem does it solve? (max 100 words)
Subgraphs are used by many web3 dapp developer teams to index and watch their smart contracts. Currently Graph Nodes are not able to recognize the Filecoin chain's null tipset sounds as described in this Github issue: https://github.com/graphprotocol/graph-node/issues/4729. 

Vulcanize proposes to write a patch for this issue to existing Graph Node software and create a PR for their team to review.

This would help unblock many teams in the Filecoin / FVM ecosystem who currently need subgraph support.

### 2. Project links
  
Link to Github repo: https://github.com/graphprotocol/graph-node/issues/4729
Link to demo or website: https://github.com/vulcanize
License: Will use the license of https://github.com/graphprotocol/graph-node

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

This will patch the Graph Node's ability to index subgraphs from the Filecoin chain for FEVM projects.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)

Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe |

1. Review the existing recommendation provided by The Graph's core dev at https://github.com/graphprotocol/graph-node/issues/4729#issuecomment-1650257347
2. Create a patch that allows Graph Nodes to gracefully handle null tipset rounds in Filecoin
3. Make a PR using this patch to https://github.com/graphprotocol/graph-node
4. Work with the Graph's core devs who will review this patch to get this merged to their main branch.
5. Deploy and verify the solution 
6. Expose an API endpoint to relevant parties as determined by Filecoin

Total time: 2 dev weeks 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

https://github.com/vulcanize
https://github.com/AFDudley
https://github.com/i-norden

* How did you learn about our microgrant program?

Eva Shon

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @levlite, thank you for your proposal! This microgrant has been approved. Look out for an email to confirm payment details.

**Comment by xianglinhe** [comment]
Hi @levlite, any update of your solution now?

**Comment by dboreham** [comment]
Hi, I posted a link to a set of fixes that handle null tipset rounds [here](https://github.com/graphprotocol/graph-node/issues/4729#issuecomment-1928663928).
