### ISSUE TITLE
Next Step Microgrant: DefiKicks

### ISSUE THREAD

**Issue by md0x** [filecoin-project/devgrants#1623]
### 1. What is your project, and what problem does it solve? (max 100 words)

DefiKicks offers a decentralized approach to DeFi data, addressing centralization issues in TVL (Total Value Locked) aggregators. By transitioning TVL computation on-chain, DefiKicks enhances data authenticity, leverages community input, and brings about greater transparency. With its innovative version control system for TVL adapters and a blend of on-chain proposals with off-chain voting, the platform stands poised to revolutionize DeFi data analytics. - [Article](https://medium.com/@pmaldotci/tvl-dashboards-the-quintessential-dilemma-in-defi-4e72019069a2)

### 2. Project links

Link to Github repo: [DefiKicks Github Repository](https://github.com/md0x/defikicks)
Link to demo or website: [https://www.defikicks.xyz/](https://www.defikicks.xyz/)
License: MIT

### 3. a) How is IPFS, Filecoin, or related technology used in this project?

DefiKicks relies on the Filecoin network for hosting and proposing TVL adapters on-chain through an IPFS hash. The code for these adapters is hosted on IPFS, ensuring an immutable and transparent record. Additionally, Bacalhau Lilypad, a trusted oracle, brings the off-chain voting results back on-chain and calculates the DeFi Data of the approved adapters, further integrating with the Filecoin ecosystem.

### b) Is this project building with the current microgrants focus area (FVM)?

Yes

### 4. How will you improve your project with this grant? What steps will you take to meet this objective?

| Number | Grant Deliverable                                            | Briefly describe how you will meet deliverable objectives                                                                                                | Timeframe (within 3 months) |
| :----- | :----------------------------------------------------------- | :------------------------------------------------------------------------------------------------------------------------------------------------------- | :-------------------------- |
| 1.     | Migrate vote resolution and reward calculation to Lilypad V1 | Upgrade the voting and reward systems to align with Lilypad V1 functionalities                                                                           | Weeks 1-2                   |
| 2.     | Migrate data calculation to Lilypad v1                       | Transition data calculation processes to be compatible with Lilypad v1 and store results in IPFS                                                         | Weeks 3-4                   |
| 3.     | Refinement of the smart contracts                            | Enhance modular system for upgradability, gas optimizations, more efficient/versatile KICK (remove ERC20 Snapshot), introduce vote delegation, and integrate rules proposals                 | Weeks 5-7                   |
| 4.     | Improve frontend: better UX/UI                               | Enhance user interface and experience for increased usability and accessibility and upgrade stack to use: Rainbow kit, Next JS, Tailwind CSS, Web3 React |     Weeks 8-10                        |
| 5.     | Implement migration functionality: migrate adapters from DefiLlama to DefiKicks   | Develop a robust migration tool to transition adapters from DefiLlama to DefiKicks |     Weeks 11-12                        |

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions

- If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Yes, DefiKicks was a finalist in Eth Global Hack Fs 2023 and secured 4 best use case prizes (Filecoin, Bacalhau, Drand, Lit Protocol).

### Additional questions:

- For each team member(s), please list name, email, Github account, and role in the project.

    - Pablo Maldonado: [Github](https://github.com/md0x), [Twitter](https://twitter.com/md0x), [Email](mailto:pablomaldonadoturci@gmail.com)
Role: Smart Contract Engineer / Full Stack Developer
    - Mauro Donadio: [Github](https://github.com/donadiomauro)
Role: Full Stack Developer

- How did you learn about our microgrant program? From the Filecoin Discord server
- If your project was created as part of an event or hackathon:
  - What was the name of the event? Eth Global Hack Fs 2023
  - Please link to your hackathon submission: [DefiKicks Hackathon Submission](https://ethglobal.com/showcase/defikicks-b1wo0)

**Comment by ErinOCon** [comment]
Hi @md0x, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant for this project. Please feel welcome to contact our team at [grants@fil.org](mailto:grants@fil.org) with any questions.

Wishing you the best as you continue to build!
