### ISSUE TITLE
Lighthouse FVM Tooling

### ISSUE THREAD

**Issue by nandit123** [filecoin-project/devgrants#1624]
# Open Grant Proposal: `Lighthouse FVM Tooling`

**Project Name:** Lighthouse 

**Proposal Category:** `Developer and data tooling`

**Entity Name:** WEB3 TECH LABS PTE. LTD.

**Proposer:** `@nandit123`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:**  Yes
# Project Summary

This project aims to make tools for developers to use FVM easily and build on Filecoin with the best developer experience. Many developers are already building on FVM, and many more are interested in building new dapps leveraging the power of programmable storage that FVM has to offer. 

This proposal consists of new developments made by the Lighthouse team that provide the ability to verify storage via PoDSI (proof of data segment inclusion), implement the RaaS full interface, and the upload interface with interaction via contracts deployed on Filecoin Virtual Machine. This proposal takes into consideration the feedback from the FVM community in past events and makes sure that developers in upcoming events can leverage the full power of verifiable and programmable storage ability provided by FVM. 

## Impact 

1. Solves pain points of developers building on FVM and prepares the right developer experience for upcoming events like Open Data Hack
2. It benefits the whole Filecoin economy by providing the best set of tools and interfaces to build on FVM (Filecoin Virtual Machine). 

## Outcomes

1. PoDSI (Proof of Data Segment Inclusion) endpoint for Open data hack event as documented [here](https://docs.lighthouse.storage/lighthouse-1/filecoin-virtual-machine/podsi). Proof of data segment inclusion is used to prove that your file is in the deal created by the aggregator node. The aggregator provides aggregated files, piece CID, inclusion proof, and proof of sub-tree
2. Integrate the RaaS interface as defined by the FVM Team specs

- Make formatting edits to align with the aggregator interface defined [here](https://github.com/lighthouse-web3/FVM-Lighthouse-Code-Example/tree/main/contracts) 

- Test deal replication and add documentation for Open data hack

3. The upload interface will be added according to the below spec

- data_url: an https or ipfs link to fetch a copy of the data if the data is not provided as a binary in the API call 
- (optional) miner: id address of the miner that the user prefers to use (optional in upload) num_copies: the number of copies that the user wants to replicate (default: 3) 
- (optional in upload) repair_threshold: the number of epochs that the sector has to be in “inactive” status before the worker repairs the deal 
- (optional in upload) renew_threshold: the number of epochs that the deal is about to expire

4. Provide clear documentation for developers to interact with the FVM for PoDSI and RaaS interface

## Adoption, Reach, and Growth Strategies

Target audience: Developers and teams building on FVM in upcoming events. We are engaging with the audience via our socials - Discord, Slack, Telegram, and Twitter and participating in events. 

## Development Roadmap

_Milestone 1:_
**Functionality expected**:

- PoDSI endpoint Live
- Integrate the RaaS Interface as defined by the FVM team
- Upload Interface as per spec
- Clear documentation

**People**: 2

- Nandit Mehra - Technical
- Ravish Sharma - Technical

**Funding**: $15,000

**Time**: 1st August 2023 - 31st August 2023

## Total Budget Requested

| Milestone # | Description | Deliverables | Completion Date | Funding |
|---|---|---|---|---|
|1| Build Tooling for FVM|PoDSI Endpoint Live|31/08/23|$15,000|
|||Integrate the RaaS Interface as defined |||
|||Upload Interface as per spec as defined|||
|||Clear documentation with code examples|||

## Maintenance and Upgrade Plans

We plan to maintain and upgrade service in the future as per demand in the FVM community

# Team

## Team Members

Nandit Mehra - @nandit123
Ravish Sharma - @ravish1729

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/nanditmehra/ 
https://www.linkedin.com/in/ravish1729/ 

## Team Website

https://lighthouse.storage/ 

## Relevant Experience

Building on the Filecoin stack from the last three years. Active team building on FVM with top projects like Ocean Protocol, Syscoin, etc. using Lighthouse

## Team code repositories
https://github.com/lighthouse-web3 

# Additional Information
Email: nandit@lighthouse.storage

**Comment by ErinOCon** [comment]
Hi @nandit123, thank you for your patience! We would like to move your proposal forward to the next steps in our process. We will send an email with further details.
