### ISSUE TITLE
Newzchain: A Blockchain and AI powered Media Platform for Startups!

### ISSUE THREAD

**Issue by Suptotthita** [filecoin-project/devgrants#1627]
### 1. What is your project, and what problem does it solve? (max 100 words)

We are on a mission to revolutionize media for startups. We are developing a decentralized content publishing platform that empowers innovators, entrepreneurs, and enthusiasts in the tech industry.

With our blockchain-powered and AI-supported platform, we aim to provide a trusted, ad-free, and community-driven space for discovering and sharing verified news and stories from the world of technology.

Our platform is designed to cater specifically to the needs of tech startups, offering them a dedicated space to showcase their achievements, share their stories, and connect with a global audience.

We believe that by focusing on early-stage startups, we can contribute to their growth, foster collaboration, and inspire others with their success stories.

In addition to the media platform, we are also building several other innovative products:

- **Newzchain Learn:** Empower Startups with Expert Video Content.
- **Newzchain Tribe:** Connecting Investors and Mentors for Success.
- **Newzchain Partners:** Unlock Exclusive Deals for Your Startup.
- **Newzchain Insights:** Fueling Startup Growth with Expertise.

**Why Decentralization and Blockchain Matter:**

  Decentralization lies at the core of our platform because we recognize the immense value it brings to both users and companies. Unlike traditional media platforms that are often controlled by centralized entities, our decentralized approach ensures that power is distributed among the community.  

This means that no single authority can manipulate or control the content published on Newzchain. Instead, it is the collective wisdom and contributions of our users that shape the platform, making it truly community-driven. 

By leveraging blockchain technology, we enhance the transparency and trustworthiness of our platform. Every piece of content published on Newzchain is stored on the blockchain, providing an immutable record of its origin and ensuring that it cannot be tampered with or altered.  

This not only eliminates the risk of fake news but also enables users to verify the authenticity of the information they consume.
Furthermore, our use of AI technology enables us to deliver personalized and relevant content to our users.  Through advanced algorithms, we curate and recommend news and stories tailored to individual interests and preferences, ensuring a highly engaging and tailored experience for every user.

  **User Data Security and Safety:**
  
  At [Newzchain](https://newzchain.com/), we prioritize the security and safety of our users' data. We understand the importance of protecting personal information in today's digital landscape. As a decentralized platform, Newzchain reduces the risk of centralized data breaches.  
  
  Unlike traditional media platforms where a single database stores vast amounts of user data, our decentralized architecture distributes user data across the network, making it significantly more resilient to hacking attempts.  We are committed to transparency in how we handle user data. 
  
  We adhere to strict privacy policies and ensure that user data is only used for the intended purposes, such as personalization and improving the user experience.  We never share or sell user data to third parties without explicit consent. We believe that empowering users means giving them control over their own data.

### 2. Project links
  
Link to Github repo: https://github.com/newzchain
Link to demo or website: https://newzchain.com/
LinkedIn: https://www.linkedin.com/company/newzchain-hq/
Twitter: https://twitter.com/NewzchainHQ

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

We are using web3.storage/IPFS as the default storage in our platform to store all metadata, images, and many more. We are also integrating web3.storage/IPFS into upcoming products. We will be storing a few TB of data every month. 

We have completed the first phase of the development and are already [live](https://newzchain.com/). We already published 60+ startup stories on our platform and 100+ drafts in the pipeline. 

We are also onboarding 100s of content creators and brands into our platforms in the coming months. 

b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)

Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |  Store 100% of data on IPFS |   Reducing dependencies on centralized storage |  One month | 
| 2.     |  Integrate IPFS with Newzchain Learn and rest of the products |  Start storing large video files on IPFS |  One month | 
| 3.     |   FVM Integration  |   Integrate FVM with the backend  |  One month | 
| 4.     |   Increase Userbase  |  onboard 100+ content creator and brands on the platform |  One month | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Suptotthita Neogi, Founder & CEO, supto@newzchain.com, https://www.linkedin.com/in/suptotthitaneogi/
Pushpit, Full Stack Developer, pushpit@newzchain.com, https://github.com/Pushpit07
kundan, Blockchain developer, kundan@newzchain.com, https://github.com/mishra811
Content and other team: https://newzchain.com/authors/

* How did you learn about our microgrant program? 

Referred by the Filecoin team. 
Ruben Amen

**Comment by Suptotthita** [comment]
@ErinOCon Please let me know if you need any additional information.

**Comment by Suptotthita** [comment]
I'm thrilled to share that Newzchain was prominently highlighted across various media platforms yesterday. 

https://zexprwire.com/newzchain-redefining-startup-narratives-through-the-power-of-blockchain/
https://africanverdict.com/newzchain-redefining-startup-narratives-through-the-power-of-blockchain/
https://australiantribune.com/newzchain-redefining-startup-narratives-through-the-power-of-blockchain/
https://www.miamitimesnow.com/2023/08/24/newzchain-redefining-startup-narratives-through-the-power-of-blockchain/

**Comment by Suptotthita** [comment]
After months of relentless effort today, we proudly mark the milestone of featuring [85+ startup stories](https://newzchain.com/authors/) on our platform.

**Comment by Suptotthita** [comment]
@ErinOCon, When can I expect an update regarding our application?

**Comment by Suptotthita** [comment]
@ErinOCon Hope you are doing. 

I submitted this proposal 6 months ago. Can you provide an estimated timeline for an update?

**Comment by eshon** [comment]
@Suptotthita - Your news platform is nice but how specifically is your project planning to use FVM?

**Comment by Suptotthita** [comment]
@eshon, Thanks for your response. 

We aim to leverage FVM to revolutionize the landscape of decentralized media platforms. By integrating FVM into our infrastructure, we will address the key challenges that traditional media platforms face, including data integrity, content distribution, and monetization.

One primary use case for FVM within the Newzchain's ecosystem is decentralized content hosting and distribution. We strive to ensure censorship-resistant and tamper-proof storage, by storing articles, videos, and other media on the Filecoin network. This will enhance the trust and reliability of our users. 

We plan to utilize smart contracts on FVM to automate the content monetization processes and facilitate fair compensation for content creators. 

The smart contracts will manage subscription payments, micropayments for individual pieces of content, and revenue-sharing agreements, empowering creators and fostering a vibrant content ecosystem. 

Newzchain's integration of Filecoin Virtual Machine represents a significant step towards building a decentralized media platform that prioritizes security, transparency, and community engagement. 

We want to explore other use cases like deploying a decentralized Content Delivery Network in the future.

**Comment by Suptotthita** [comment]
@ErinOCon @eshon It's been 9 months since I submitted this proposal. When can I expect an update on my application? 


I'd like to highlight some of our recent accomplishments:

- Our platform recently surpassed 100K visits.
- We've reached a milestone of 10K users.
- Last week, we achieved a record of [700 published](https://newzchain.com/archive/) articles/stories.
- Our podcast, "[The Newzchain Podcast](https://newzchain.com/tag/podcast/)," has been successfully launched with over 20 episodes recorded.
- We're currently in the process of onboarding over 200 new content creators.
- Phase 2 development is now underway.

**Comment by ErinOCon** [comment]
Hi @Suptotthita, thank you for your patience with our review process. This is a very interesting application that was considered as a candidate for multiple waves of our FVM Microgrant Program. Unfortunately, after much consideration, it has been determined that we will not be be moving forward with a new grant at this time.

In case you have an interest, I will be sending you an email shortly to discuss other ways to partner with our community. Wishing you the best as you continue to build.

**Comment by Suptotthita** [comment]
Hi ErinOcon,

Thanks for the update.

Please send the email. We are very much interested in partnering with the
Filecoin community in any way we can.
