### ISSUE TITLE
Onchain File Aggregator

### ISSUE THREAD

**Issue by cezarparaschiv** [filecoin-project/devgrants#1630]
# Open Grant Proposal: `Onchain File Aggregator`

**Project Name: Onchain File Aggregator**

**Proposal Category:**`Other`

**Individual or Entity Name: Digital MOB** 

**Proposer: ** `cezarparaschiv’

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** "Yes"

# Project Summary

Build an Onchain file aggregator, leveraging the lunch of FVM. 

## Impact 

Currently smart contract deals on FVM are not aggregated, and mostly small size (under 32G), which is not very attractive for Storage Providers (note: we refer to these small deals as subpiece deals below, as compared to the aggregated full piece). Aggregating these small smart contract deals would make it much more appealing for Storage Providers to pick up the deal. 

## Outcomes 

The system will be developed in phases.
Phase 1 encompasses the fundamental functionalities and architecture required for the system to operate. This involves the following components: user → aggregator contract → bundler node → BOOST API → deal-making. In Phase 1, there is a single Bundler node, managed by Digital MOB.
Phase 2 encompasses functionalities aimed at achieving complete decentralization of the system. In Phase 2, multiple bundle nodes can consume data from the contract.

## Development Roadmap

Milestone 1
The system consists of three core components:

Smart Contract: 
The contract stores a collection of files that will be consumed by a bundler node for further aggregation. Users need to keep the files in a publicly accessible environment (IPFS, S3 bucket) and provide the contract with the file link, size, and subpieceCID. 
Once a deal is successfully established, the contract receives and retains the deal ID for each included file. 
The contract is designed to be upgradable to accommodate future feature enhancements.

Bundler Node: 
This node takes subfiles from the contract and, based on an algorithm, compiles the files into a file of approximately 32 GB in size. The bundling algorithm might follow a "first come, first served" approach until reaching the 20 GB limit. For the remaining 12 GB, the bundler selects from the list to reach or nearly reach the 32 GB size. 
The bundler node creates an index with subpiece CIDs and combines these into a 32 GB CommPa. These operations rely on libraries provided by PL. All proofs are stored in a database, and the bundler exposes an API for querying this database. 
The bundler downloads subfiles and constructs the CAR file, which becomes the subject of the deal. The bundler employs the BOOST API to finalize deals, and once a deal succeeds, the bundler sends the corresponding deal ID to the smart contract.

Verifier: 
The Verifier is a command-line tool used to verify if subfiles are part of a deal. Users input the sub piece CID, and the tool retrieves the Deal ID from the contract. Using this information, it fetches the deal data from the blockchain and acquires inclusion proofs from the Bundler API. The tool then verifies the computed CommPa against the deal price CID.

Milestone 2 
Additional features for the smart contract include:
Allowing multiple nodes to consume data with a reservation mechanism to prevent simultaneous selection of the same files.
Implementing a whitelisting function to authorize specific bundler nodes to interact with the contract.
Enabling users to send funds to the contract to incentivize nodes to prioritize their files for aggregation.
Milestone 2 will be subject to another grant proposal. 

To build Milestone 1, the timeline is 6 weeks. 

## Total Budget Requested

| Milestone # | Description | Completion Date | Funding |
|Milestone 1|Smart contract, Bundler Node, Verifier| 6 weeks|$51840|

## Maintenance and Upgrade Plans

- The provided fixed fee below covers one year of maintenance for the bundler node
- The improvements are listed above, under Milestone 2. 
- The interaction with the Smart Contract will be elaborated upon and exemplified in a README document, which can be located in the GitHub repository of the contract.

# Team

## Team Members

1 PM 
1 SC Developer
1.5 Backend Developers 
1 DevOps

## Team Website

https://digitalmob.ro

## Relevant Experience

We possess extensive expertise within the Filecoin ecosystem. Throughout our two-year collaboration with Protocol Labs, we have successfully developed a range of projects, including Spacerace (the incentive miner program), Filrep, Filplus, Filgreen, Filecoin Lending, Filecoin JS, Filstats, and FilPoll.

In addition, we boast robust capabilities in Solidity. Feel free to explore our website to view the comprehensive list of projects we have constructed on the Ethereum blockchain.

cezar@digitalmob.ro.

**Comment by ErinOCon** [comment]
Hi @cezarparaschiv, thank you for your proposal and for your patience with our review. Unfortunately, due to budget constraints in this climate, we will not be moving forward with a grant at this time. 

This is a very interesting project and look forward to learning of your building progress and future work!
