### ISSUE TITLE
FVM POWERED ART ARCHIVE & STORAGE ONRAMP SOLUTION & TOOLING

### ISSUE THREAD

**Issue by drbannerx** [filecoin-project/devgrants#1632]
# Open Grant Proposal: FVM POWERED ART ARCHIVE & STORAGE ONRAMP SOLUTION & TOOLING

**Project Name: NTENT.ARCHIVE**

**Proposal Category:Developer and Data Tooling** 

**Individual or Entity Name:  NTENT** 

**Proposer: @drbannerx** 

**(Optional) Filecoin ecosystem affiliations: @TkKonstantin**

**(Optional) Technical Sponsor: @TkKonstantin** 

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?: No.** 

We will opensource the framework of the archive for others to create their unique instances of a data onramp to storage solution but ntent.archive and its build-out will be propriety to ntent with a focus on the art industry and media.

# Project Summary

NTENT is an international art collective and Berlin-based Kulturhaus designing new realities through artistic and social experiences. We are merging technology and culture, revolutionizing how art is created, preserved, accessed, and presented through our decentralized solution, ntent.studio.

Our platform, ntent.studio provides artists and institutions with the tools and applications necessary to integrate with web3. We’ve combined multiple feature sets into a comprehensive solution that enables art to be created, accessed, studied, and appreciated by as many people, artists, and institutions as possible in a decentralized way. The goal of our technology and creative direction is to allow artists and institutions to create, archive, access, research, sort, curate, and present art in ways that expand human understanding like never before.

With this grant, We are continuing our work from the first grant (https://github.com/filecoin-project/devgrants/issues/1112), where we focused on the implementation of an archival layer for our existing smart contract application network and technology stack. Now we are focusing on the second act in our road map by developing an Art Archive & Storage Onramp Solution, [ntent.archive], specifically designed for the needs of the art community and developed directly on the FVM. We aim to support the preservation, presentation, and access of culturally valuable art-based datasets through a decentralized application that functions as a storage structure for the art and the data collected in the process of creating art. The solution is built for artists, art professionals, and patrons to access through TAR app, a mobile-first web3 experience application built on top of the ntent.archive.

We achieve this by offering the ability for artists to store art and art history assets on IPFS automatically within our technology solutions (ntent.studio), in unison with (ntent.archive), a decentralized app that uses FVM with IPFS for the storage and access of their contextual and historical documentation. 

Our current technology stack, ntent.studio is a fine art technology suite that uses blockchain and decentralized technologies to lift artists, galleries, and institutions through a collection of blockchain solutions. [1][2][3]

### **WHY**
**The power of art's creative energy has changed our lives; as children, our grandmothers took us to the world's most accessible art institutions. At ntent, we understand the power creativity has to impact each of us individually. Without access to those museums, we wouldn't have been exposed to the cultural commentary and experiences that shaped our consideration for social progress and made us into who we are today. By decentralizing and removing industry silos, we are making art accessible to the world through thoughtful action, intentional design, and visual experience powered by decentralized technology.**

Art reflects our collective human experience, a mirror of culture that every human should be able to engage with, interpret, and emotionally respond to, regardless of preference and background. A selfish and self-serving industry has gatekept art and its supporting context for generations, and no technology exists yet to democratize access to these experiences. Art is built by culture in real-time and through the ntent.archive functionality and TAR app easy access in real-time will be possible too. 

Ntent exists to unlock the universal accessibility of art, enabling the preservation of culture and human experience, shattering the tradition of an unsustainable industry. With the power of FVM, combining storage solutions with smart logic and accessible end-point, ntent creates a perfect combination of technology and resources to execute the vision of a fully accessible art future.

### **HOW**
We serve as a conduit for contemporary culture, to use our decentralized technology as a bridge to facilitate the creation, documentation, and delivery of art and culture in real-time, enabling truly inclusive opportunities for individuals to participate in, contribute to, and benefit from the world of art through decentralized systems.**

Our platform is producing social experiences that grant new access to art beyond that of the current centralized system. Through our decentralized technology stack ntent.studio, we have the opportunity to support artists, institutions, and patrons in creating, storing, and presenting art while integrating web2 infrastructures with web3 functionality. Using ntent.studio and ntent.archive artists are empowered to explore the creative potential of decentralized technology to create, preserve, access, and present art and its supporting data. With the use of FVM, IPFS, and Filecoin, we are giving a platform to this nouveau art movement and sparking emotional responses and inspiring dialogues that encourage society to explore the concept of how art can shape our collective future. 

<img width="4848" alt="NTENT" src="https://github.com/filecoin-project/devgrants/assets/64104985/f4b119c9-9e1d-4ea6-8ba4-8b31433854db">

[4] [Link to view the "ntent internal/development structure" in Figma](https://www.figma.com/file/Imevd78u6feTsPKaD0XnJC/NTENT?type=whiteboard&node-id=0-1&t=V2I9Jk8WhDX2nRCC-0)

## Outcomes

**DELIVERABLES**

We aim to implement an Art Archive & Storage Onramp Solution for uploading, indexing, and storing artistic data sets generated by artists and institutions to act as the foundation for additional tooling and applications to be built upon. **We also allow for index queries for art discovery via a search that is based on CID metadata.**

1. Develop FVM Onramp Actor
2. Develop Art Industry native/purpose Indexing system
3. Implement an indexing system in the contract and ntent layer
4. Integrate with our current ntent.studio systems 
5. Deploy ntent.archive
6. Create documentation of open-source components
7. Develop a case study and promote the developed component for the ecosystem
8. (To be discussed) Work with the artist(s) or institution to upload and launch a collection with all associated artistic data (World renowned modern era artist with a global presence and historical foundation,  (contact already established, happy to discuss the details under NDA), as well as verbal commits from two major decentralized generative art platforms. 

## Adoption, Reach, and Growth Strategies

Our target audience to start is artists and institutions set on intentionally building with decentralized technologies and their communities. We have engaged our audience through partnerships and relationships made within Web3 and traditional art spaces. 

We are already working with a World-renowned modern-era artist with a global presence and historical foundation, as well as verbal commits from two major decentralized art platforms. (contact already established, happy to discuss the details under NDA) And after this development round, we will immediately look to move into onboarding our first artists and institutions.  

## Development Roadmap

We plan to execute across 6 months and expect the following milestone outline in billable hours and human resources.

    Milestone 0 (PREPARATION): Develop Technical Specifications
    Milestone 1 (REQUIRED): Develop ntent.archive data onramp & FVM Actor
    Milestone 2 (REQUIRED): Develop Indexing system
    Milestone 3 (REQUIRED): Integrate with our current ntent-archive system
    Milestone 4 (IMPORTANT): Document ntent.archive open source components. 
    Milestone 5 (BENEFICIAL): Case study development, blog post publication, and promotion for the ecosystem

## **Milestone 0: (Preparation) Develop Technical Specifications**
14 days (2 weeks) | one part-time project manager, one part-time web3/node.js engineer, one part-time solidity engineer | complete by December 2024

**RESULT:** Given the scope of work, this milestone includes the completion of all detailed technical specifications for all subsequent milestones, including schedules of work. These will be developed with the human resources performing the work to ensure all persons are on the same page.

![MILESTONE 00 (Preparation)](https://github.com/filecoin-project/devgrants/assets/64104985/453f1d2e-c154-4a6d-8f62-3f6c52558171)

## **Milestone 2 (REQUIRED): Develop Indexing system**
30 days (4 weeks) | one part-time project manager, one full-time web3 engineer, one part-time Quality Assurance engineer | complete by February 2024

**RESULT:** Indexing system completed and API ready, built using IPFS + Ceramic network or similar functionality. 

![MILESTONE 02 (Required)](https://github.com/filecoin-project/devgrants/assets/64104985/0c742ac2-93aa-4738-9e85-047dd97ecedc)

## **Milestone 3 (REQUIRED): Integrate with our current ntent-archive system**
30 days (4 weeks) | one part-time project manager, one full-time node.js engineer, one part-time Quality Assurance engineer | complete from Q4 2022 - Q1 2023

**RESULT:** The ntent-archive library is updated/published to GitHub, with new functionality to upload to IPFS while creating storage deal in the ntent FVM actor and updating the index.

![MILESTONE 03 (Required)](https://github.com/filecoin-project/devgrants/assets/64104985/24d83be9-3af1-4feb-9a21-8608981782b1)

## **Milestone 4 (IMPORTANT): Document ntent.archive open source components** 
14 days (2 weeks) | One part-time project manager, One full-time node.js engineer, One part-time Quality Assurance engineer | Complete from Q4 2022 - Q1 2023

**RESULT:** Comprehensive and detailed documentation of the ntent.archive system, ensuring that external developers or teams can easily understand, deploy, and extend the tooling. The documentation will be stored on a GitHub repo and will cover setup, development, deployment, and maintenance.

![MILESTONE 04 (Important)](https://github.com/filecoin-project/devgrants/assets/64104985/945f5f34-94ca-4215-b0d4-d2e755e663c8)

## **Milestone 5 (BENEFICIAL): Case study development, blog post publication, and promotion for the ecosystem**
15 days part-time | one part-time creative director, one part-time content producer, one part-time Web3 developer | complete from Q4 2022 - Q1 2023

**RESULT:** Develop and publish a use-case to spotlight developed tooling for the ecosystem, plus engage with the community about the developed tooling via AMA, project highlight or other means in coordination with Filecoin Foundation

![MILESTONE 05 (Beneficial)](https://github.com/filecoin-project/devgrants/assets/64104985/42adb211-6142-483d-ab4a-83d728578259)

 **Reference points:**
      - Creating a write-up 
        - https://blog.uniswap.org/uniswap-interface-ipfs 
        - https://docs.ipfs.tech/case-studies/audius/#overview
      - Blog Post Joint Publishing 
        - Ntent.art blog https://www.ntent.art/articles +
        - Filecoin blog, plus Twitter resharing
      - Optional Promo Campaign 
        - Coverage & [Twitter AMA](https://twitter.com/rtclick_save) with [Right Click Save](https://www.rightclicksave.com/about)
        - Ecosystem call spotlight
        - online tutorial for the contract

With these added components, the promotional strategy becomes multi-faceted, ensuring that the content reaches a wider audience with engaging visuals. Each component is crafted to resonate with the target audience, fostering community engagement and discussion.

## Total Budget Requested

We request a total budget for this project based on the costs outlined for each milestone in the previous section, “Development Roadmap.” We have provided options based on what we feel is required for the project, Important for the ecosystem, and additionally beneficial to its success that is open for discussion.

### Complete (Prep + Required + Important + Beneficial)

     $111,420

### Meaningful (Prep + Required + Important)
     $102,150

### Minimal (Prep + Required)
     $90,990

## NEXT STEPS & LONG-TERM PARTNERSHIP

Having benefited from your support through the previous grant, we are optimistic about the progress and insights that a second grant will yield. Looking ahead, we aim to raise a seed round following this grant in ~Q4, and there's an invaluable opportunity for our paths to align even more deeply. We invite PL to consider playing a pivotal role as a lead or co-investor. Given our shared vision and your firsthand understanding of our mission from the initial grant, such a partnership would solidify our long-term commitment. We are eager to discuss flexible investment options, priority rights, and strategic collaborations that not only ensure mutual growth but also further solidify our joint endeavors in the ecosystem. To provide detailed information, we would be happy to share our pitch deck and existing partnership details by the end of Q3. Happy to plan additional calls with the PL accelerator and investment teams to align on the possible next steps after the grant whenever suitable.

### FUTURE ROAD MAP

- Finalize Company Foundation (Beginning Q4 2023)
    - Entity is already created, but further legal work is needed before round fundraising
- Push 1-2 key partnership engagements (one already in pipeline) (Q4 2023 - Q2 2024)
- Fundraising (Q4 2023 - Q1 2024)
- Scale up with received funding (Q1-2 2024)
    - HR is top priority
    - Core Developers
    - Community Developers
    - Extend resources for upcoming art projects and key partnerships
    - Extend outreach
    - Legal and advisory teams
    - Other
- Finalize archive development (Q2 2024)
- Prioritize building art community on a platform (Q2 2024)
- Stabilize positive cashflow from engagement projects and curatorship (Q2 2024)
- Deepen art & tech networks (Q2 2024 onwards)

# Team

## Team Members

  River Davis known as Dr.Banner
  Sean Ryan O’Connor known as jiwa
  Coco Shin known as bluem0xn
  Tkachuk Konstantin as reaktornano

## Team Member LinkedIn Profiles

  River Davis - https://www.linkedin.com/in/riverdavis/
  Sean Ryan O’Connor - NA
  Coco Shin - https://www.linkedin.com/in/cocoshin/
  Konstantin Tkachuk - https://www.linkedin.com/in/tkachukk/

## Team Website

Official Website: https://www.ntent.art/ 

### Sean Ryan O’Connor
Senior-level Full-stack, smart contract/dapp developer
Over 15 years of experience building technology for startups and Fortune 500 companies, including Sony Pictures and Interpublic Group. 

From writing code for Hollywood to building ntent; jiwa is bringing ideas and techniques with a distinctive thoughtfulness to generative art. jiwa is an early participant and believer in crypto and blockchain technologies since 2013.

[Read his full bio](https://ntent.art/jiwa)

### River Davis
Senior-level International Creative Director and Operations Specialist/Mgr
Over nine years of experience in international creative production for NGOs, brands, and personalities, including Center for Dignity, Donate Attention, Blesswell, and Dj Kahlid.

From creative directing across twelve countries to co-founding ntent Dr.Banner, an American multimedia artist and creative director based in Berlin, presents work that explores the evolution of consciousness and its impact on culture.

[Read his full bio](https://ntent.art/drbanner)

### Coco Shin
Operations Manager + Marketing and Content Specialist 
5+ years of experience managing projects and content development.
Over 3 million views across social platforms. 

Blue Moon is a founding partner of ntent.art and creator of #OneDropNFTs, a movement to destigmatize menstruation through discussion and art. She champions inclusion and sustainability in both Web3 and existing social platforms. Her multimedia art centers on themes of self-care, sustainability, personal awareness, and discipline. She is also an environmental activist passionate about bridging the gap between blockchain and the environment.

[Read her full bio](https://www.ntent.art/bluem0xn)

### Tkachuk Konstantin
4+ years of entrepreneurial experience in European tech startups
ex. Protocol Labs - Startup Operator, Ecosystem Collabs Team

Schwarzman Scholar '23, Web3 enthusiast and artist. A young leader and entrepreneur advising multiple cutting-edge tech projects in the blockchain space. He is a civil engineer by training and has gone through various entrepreneurial experiences in the European landscape. Won the SpaceX Hyperloop competition and was awarded with Schwarzman Scholarship.

## Track of record

    1. Ntent - Filecoin approved grant proposal No 1 - https://github.com/filecoin-project/devgrants/issues/1112
    2. Blogpost - https://fil.org/blog/remixing-the-art-world-with-blockchain-technology-a-q-a-with-ntent/ 
    3. Public event - https://twitter.com/ntentart/status/1674438886683029509 
    4. Twitter thread - https://twitter.com/ntentart/status/1674133049989054464 
    5. All existing and publicly committed projects - https://www.ntent.art/articles 

## Team code repositories

(https://github.com/ntentart)

# Additional Information

We learned about the Open Grants program through a previous grant and through the FVm request for start-ups page https://protocollabs.notion.site/Request-for-Startups-FVM-edition-8cd3e76982d14e29b33335ca458fb087#01c77142f95145fbb6ddefb351f1bccc 

The best email address for discussing the grant agreement and general next steps is drbanner@ntent.art

### References
[1] ntent https://www.ntent.art/
[2] ntent.studio https://www.ntent.art/studio
[3] Previous Grant https://github.com/filecoin-project/devgrants/issues/1112#issue-1427194573 
[4] ntent infrastructure and development roadmap https://www.figma.com/file/Imevd78u6feTsPKaD0XnJC/NTENT?type=whiteboard&node-id=0-1&t=V2I9Jk8WhDX2nRCC-0 
[5] Milestones Financial Breakdown https://docs.google.com/spreadsheets/d/1s46R-EaHScpGEkmvkwFHZseW2eitl2xd63Z_ANB6MOc/edit?usp=sharing

**Comment by ErinOCon** [comment]
Hi @drbannerx, thank you for your time with this proposal. Your application is still under review, but we expect to have more information available in the coming weeks. 

Thank you for your patience!

**Comment by ErinOCon** [comment]
Hi @drbannerx, thank you for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. We are wishing you all the best as you continue to build!
