### ISSUE TITLE
NIIIFTY2

### ISSUE THREAD

**Issue by edsilv** [filecoin-project/devgrants#1635]
# Open Grant Proposal: NIIIFTY2

**Project Name:** NIIIFTY2

**Proposal Category:** Applications

**Individual or Entity Name:** [Mnemoscene Ltd](https://mnemoscene.io/)

**Proposer:** edsilv

**Filecoin ecosystem affiliations:** [Web3.storage](https://web3.storage/)

**Technical Sponsor:** [Dietrich Ayala](https://github.com/autonome)

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

This project proposal builds upon the success of [Mnemoscene's](https://mnemoscene.io/) previous Filecoin devgrant project, [NIIIFTY](https://github.com/filecoin-project/devgrants/issues/504).

We are delighted to have received positive feedback from our client [Royal Holloway](https://www.royalholloway.ac.uk/), demonstrating their interest in improving upon and testing the software for the benefit of their faculty and students.

## Impact 

In 2021, Mnemoscene successfully delivered the [ARStoryDecks](https://arstorydecks.com/) project for Royal Holloway as part of the StoryFutures Train the Trainer programme. This project introduced an augmented reality storytelling platform, enabling the display of 3D models on mobile devices using markers on cards. The project's success led to Will Shüler, Vice-Dean at Royal Holloway, being shortlisted for the prestigious Times Higher Education "Most Innovative Teacher of the Year" [award](https://www.timeshighereducation.com/news/awards-2022-shortlist-announced).

However, a setback occurred several months after the project's launch when Google [discontinued](https://techcrunch.com/2020/12/02/google-shutting-down-poly-3d-content-platform/?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAANtok_rcDFB8F4C-GSaFhlRQFRaAkAmU4HUzpfgFb9uFI8zN_36qhyNUBvxuMiv07K_IFTUFaOOxxhfP_9ca3wlBiqLxQsU2VBXufFokrXJUgJLZ9TpOwcreSgRCa8sOD3amMSvfYmj5U4xB5tJ98K5JKjuNUGtQkUBEdAxoB2pR) their 3D model hosting platform, known as "Poly." This platform played a crucial role in the ARStoryDecks project, and its closure meant that existing stories would no longer function, and new stories could not be created.

Furthermore, Royal Holloway has recently implemented an "Acting 360" course for their students, incorporating the use of 360-degree video hosted on YouTube. However, during a recent visit to Shanghai to build partnerships with other universities, they encountered a challenge. YouTube was inaccessible in China, preventing them from sharing these videos with their counterparts.

## Outcomes

Royal Holloway is interested in leveraging the 3D model upload, compression, and retrieval capabilities of NIIIFTY. These features could serve as a viable alternative to the now defunct Google Poly platform, allowing them to revive the ARStoryDecks project. Additionally, they see value in NIIIFTY's utilisation of IPFS as a storage medium. This would ensure that their uploaded data is backed up in multiple locations, safeguarding against potential platform failures.

The implementation of IPFS also presents an attractive solution for storing their 360 video content, granting access to their Chinese partners via censor-proof URLs.

To proceed, we propose setting up a trial instance of NIIIFTY specifically for Royal Holloway. This will allow us to assess the ongoing running costs and determine the platform’s cost effectiveness.

Furthermore, we will make necessary modifications to the ARStoryDecks website, enabling it to load 3D models from Royal Holloway's NIIIFTY instance rather than relying on Google Poly. NIIIFTY will also require a new Google Poly style search function in order for ARStoryDecks users to be able to locate assets to use in their stories.

We aim to expand the capabilities of NIIIFTY to support the upload and preview of 360 video content.

We would also like to make uploaded content more discoverable via search by implementing auto-tagging of 3D model thumbnails and 360 videos using the [Label Images with Cloud Vision AI](https://extensions.dev/extensions/googlecloud/storage-label-images) and [Label Videos with Cloud Video AI](https://extensions.dev/extensions/googlecloud/storage-label-videos) Firebase extensions.

**Value**
- ARStoryDecks becomes usable again by Royal Holloway academics and students.
- Uploaded content is backed up permanently on the decentralised web and is accessible in countries where censorship is an issue.
- Running costs and cost effectiveness can be determined so that future clients have all the information they need when choosing whether to adopt the platform.

**Deliverables**
- A modified version of ARStoryDecks that can search for and load 3D models (glb) from NIIIFTY/IPFS.
- A NIIIFTY extension to allow the upload of GoPro Max 360 video content with in-browser preview.
- A written report detailing running costs over a 7 month period (two academic terms - September 2024 - March 2025).
- Extended documentation at niiifty.com/docs to include the newly developed features.

## Adoption, Reach, and Growth Strategies

The target audience is higher education institutions running creative arts and design courses. There are [338 Universities in the UK](https://www.hotcoursesabroad.com/study/training-degrees/uk/creative-arts-and-design-courses/loc/210/cgory/f-2/sin/ct/programs.html#:~:text=338%20Universities%20in%20the%20UK%20offering%20Creative%20Arts%20and%20Design%20degrees%20and%20courses) alone who offer creative arts and design degrees. Currently we engage with Universities like Royal Holloway through programs like [StoryFutures](https://www.storyfutures.com/).

Royal Holloway will supply a cohort of students to test the application and prove its applicability in a higher education context.

## Development Roadmap

**Milestone 1: 3D model search and loading into ARStoryDecks**

- Implement a Search Files by Title feature in the NIIIFTY web UI with ability to limit results by file type and uploader user id.
- Implement the [Label Images with Cloud Vision AI](https://extensions.dev/extensions/googlecloud/storage-label-images) Firebase extension to generate labels for 3D model thumbnails in order to provide extra searchable terms and greater discoverability.
- Implement a Google Cloud function to enable ARStoryDecks to search the files stored in NIIIFTY via an API call directly within the Add Card web UI.

January 8th - March 15th 2024 
10 weeks by one full stack developer

**Milestone 2: 360 video**

- Implement a 360 video viewer for mp4 files uploaded to NIIIFTY.

April 1st - April 19th 2024
4 weeks by one full stack developer

**Milestone 3: Analytics**

- Implement Google analytics tracking within NIIIFTY to collect usage data for the report. Data to include:
    - Number of users
    - Number of user visits over a given time period
    - Number of searches and search terms used
    - Number of files uploaded, including their type and size

April 29th - May 10th 2024
2 weeks by one full stack developer

**Milestone 4: Documentation**

- Write final usage report
- Update niiifty.com docs to reflect changes from v1

March 17th - March 28th 2025
2 weeks by one full stack developer

## Total Budget Requested

**Mnemoscene**

- 16 weeks of development @ $600 p/d
- 2 weeks of documentation @ $600 p/d

Subtotal: $54,000.00

**Royal Holloway**

Staff time
- Will Shuler – 11.5 days
- Technician (7-34, existing member of staff) – 8 days
- Materials - $2,536
- Conference travel - $1,268

Subtotal $28,900.00 (inc VAT)

**Grand total: $82,900.00**

## Maintenance and Upgrade Plans

Potential paths forward for maintenance/upgrades will largely depend on uptake from the community and any further funded projects that emerge. It is our intention to promote NIIIFTY to this end. 

# Team

## Team Members

[Edward Silverton](https://github.com/edsilv)

[Will Shüler](https://pure.royalholloway.ac.uk/en/persons/will-shuler)

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/edsilv/

https://www.linkedin.com/in/will-sh%C3%BCler-a531085a/

## Team Website

https://niiifty.com

https://www.royalholloway.ac.uk/

## Relevant Experience

[Edward Silverton](https://twitter.com/edsilv) is a full stack web developer with more than 20 years of experience, 10+ years of which working with galleries, libraries, archives, and museums. He is experienced in IPFS, nodejs, next.js, tailwindcss, and firebase, is the lead developer of [NIIIFTY](https://www.niiifty.com/), the [Universal Viewer](https://github.com/universalviewer), and [Exhibit](https://exhibit.so/), and is co-chair of the [IIIF 3D Technical Specification Group](https://iiif.io/community/groups/3d/tsg/). He presented at the 2018 [Internet Archive Decentralised Web Summit](https://decentralizedwebsummit2018.sched.com/speaker/e.silverton) on the subject of [P2P IIIF](https://docs.google.com/presentation/d/1vJtfzrIMvgiV9kYA8MwWk5KKVxTKfTeQMrs6SHVAI1s/edit?usp=sharing).

[Will Shüler](https://pure.royalholloway.ac.uk/en/persons/will-shuler) is the Vice Dean of Education and Student Experience for the School of Performing and Digital Arts at Royal Holloway, University of London, where he has worked as a Senior Lecturer in Drama and Theatre Studies since 2014. He has experience developing funded pedagogic projects integrating new technologies in performance training, including storytelling for Cinematic Virtual Reality and actor training for Volume LED Virtual Production. His published work ranges from articles in Times Higher Education such as “[Augmented Reality in Teaching: Key Challenges and How to Overcome Them](https://www.timeshighereducation.com/campus/augmented-reality-teaching-key-challenges-and-how-overcome-them)” and book chapters such as “The Emancipated Educator: Chance, Will and Intellectual Equality in Higher Education Role-Immersion Pedagogies” in [Rancière and Performance](https://rowman.com/ISBN/9781538148419/Ranci%C3%A8re-and-Performance) (paperback re-release 2023).

## Team code repositories

https://github.com/NIIIFTY

# Additional Information

I learned about the Open Grants Program from contacts at Protocol Labs.

Please contact ed@mnemoscene.io to discuss the grant agreement and general next steps.

**Comment by ErinOCon** [comment]
Hi @edsilv, thank you for your proposal and for your patience with our review. Unfortunately, we will not be proceeding with a grant at this time. Wishing you all the best as you continue to build!
