### ISSUE TITLE
ArtCoin

### ISSUE THREAD

**Issue by DorianLesnic** [filecoin-project/devgrants#1638]
# Open Grant Proposal: `ArtCoin`

**Project Name: ArtCoin**

**Proposal Category:**  `Other`

**Individual or Entity Name:** COR Creative Industries Association in Moldova

**Proposer:** `likedevs`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** "Yes" 

![ArtCoin-Youtube-cover](https://github.com/filecoin-project/devgrants/assets/99186740/9ad3f45f-62dc-47d4-bb47-186606a7c331)
# Project Summary

ArtCoin - a decentralized p2p marketplace of the underutilized assets and a sharing economy tool.

## Impact 

- Please describe in more detail why this proposal is valuable for the Filecoin, IPFS, or related ecosystems.

> We have 3000+ companies and 20k+ individuals in our community (Moldova’s Creative Industry), that perform monthly up to 1k transactions through our Organization of the total approximate amount of $100k. We want to move our Creative Community members to web3.

- What pain points does this project seek to address? 

> Countless organizations across industries possess valuable assets - from equipment and facilities to human capital and intellectual property - that are not being effectively utilized to their full potential. This lack of utilization not only hinders efficiency but also stifles growth and innovation.

- What are the benefits to getting this right? 

 > a currency, that serves as an exchange coin for the underutilized assets
 a technology that allows individuals and entities to exchange their underutilized assets 
 a marketplace displaying underutilized assets (the services and goods) that can be exchanged through ArtCoin.

- What are the risks of not getting this right?

>Technical issues that might arise in process of transition to web3

- What impact will this project have in a specific vertical, market, or ecosystem? What does success look like? 

>The COR contributes to the development and growth of the tech industry in Moldova and abroad

 > Launch the marketplace of the underutilized assets
Attract into our ecosystem the holders of underutilized assets, from different industries (cinemas, theaters, supermarkets, stores, etc.)
Expand into new markets, where global COR organization functions (Estonia/Latvia/Letonia, Romania, UK, Ukraine, Czech Republic, Azerbaijan, Croatia, Georgia, Poland, Serbia, Monte Negro, etc.).

![Logo-Cor](https://github.com/filecoin-project/devgrants/assets/99186740/748fc29a-7831-48ee-8774-4183201cf0e9)

## Outcomes

- Please describe in detail what your final outcomes & deliverable(s) for this project will be. Include a specification of the project and what functionality the software will deliver when it is finished.
>Milestone 1 - Software Technical Task Documentation development
Product Scope and Description
Product Architecture and Core Components
Elaboration of estimates, team, tasks (agile), etc.
Concept design, wireframes, UIX/UI, main components, etc.
Timeline: 2 weeks
Requested Budget: $5000 

Milestone 2 - ArtCoin Smart Contract (FT minter) and wallet authorization system
ArtCoin token smart contract
Fungible token initial amount generation
Test transfers of ArtCoin tokens between wallets
User registration/authorization with web3 wallet
ArtCoin token balance display functionality
User Management module development (account/profile)
Timeline: 3 weeks
Requested Budget: $15000 

Milestone 3 - ArtCoin Marketplace Development
Description: The Marketplace od underutilized assets will allow users to upload services/goods in respective categories, to add details (params, description, titles, price, etc.) on one hand. On the other hand it will allow users to purchase goods/service through ArtCoin and enter into possession of underutilized assets.
Categories, Params, Filters, Search, etc.
Service/good one page
Upload service/good functionality
Dashboard to track goods/services/payments/etc.
Timeline: 4 weeks
Requested Budget: $20000

Milestone 4 - Full dApp launch / mainnet version
All components manual tests
Predeployment (beta)
Beta testing (real users)
Bug fixing, golden master version (pre-release)
Golden master real-users testing
Final version launch
Timeline: 4 weeks
Requested Budget: $5000

Milestone 5 - First 5k users adoption
Onboarding (wallets creation, KYC, profile, etc.)
User Training: help users understand how the system works, how to navigate it, and how to get the most out of its features.
Timeline: 3 weeks
Requested Budget: $5000

Funds Usage:
Position: CTO, Manhours: 122, Price per H: 50, Total($): 6100
Position: Blockchain Developers, Manhours: 360, Price per H: 60, Total($): 21600
Position: Backend Developer, Manhours: 198, Price per H: 50, Total($): 9900
Position: Frontent/Multistack Developer, Manhours: 124, Price per H: 40, Total($): 4960
Position: Testers, Manhours: 198, Price per H: 25, Total($): 4950
Position: UIX/UI designer, Manhours: 83, Price per H: 30, Total($): 2490
Total($): 50000
Duration: 3 months

- Please describe how your team is measuring the success of your project and define the metrics being used.
> Our main metrics:
Amount of users 
Number of transactions between our users

## Adoption, Reach, and Growth Strategies

- Who is the target audience for your project? How large is this audience and how are you currently engaging with them?

> We have 3000+ companies and 20k+ individuals in our community (Moldova’s Creative Industry), that perform monthly up to 1k transactions through our Organization of the total approximate amount of $100k. 

>We are building the project initially for our community from Creative Community Moldova (over 20k individuals and 3k companies) , as the pilot project. And we are already discussing the expansion of the project, by attracting the holders of underutilized assets, from different industries (cinemas, theaters, supermarkets, stores, etc.)

- If applicable, how do you intend to onboard new users? 

>The strategy:

We are going to add to blockchain our existing users

Then we are going to expand our subnet gradually to other countries where global COR organization functions (Estonia/Latvia/Letonia, Romania, UK, Ukraine, Czech Republic, Azerbaijan, Croatia, Georgia, Poland, Serbia, Monte Negro, etc.).

## Development Roadmap

Milestone 1 - Software Technical Task Documentation development
Product Scope and Description
Product Architecture and Core Components
Elaboration of estimates, team, tasks (agile), etc.
Concept design, wireframes, UIX/UI, main components, etc.
Timeline: 2 weeks
Requested Budget: $5000 

Milestone 2 - ArtCoin Smart Contract (FT minter) and wallet authorization system
ArtCoin token smart contract
Fungible token initial amount generation
Test transfers of ArtCoin tokens between wallets
User registration/authorization with web3 wallet
ArtCoin token balance display functionality
User Management module development (account/profile)
Timeline: 3 weeks
Requested Budget: $15000 

Milestone 3 - ArtCoin Marketplace Development
Description: The Marketplace od underutilized assets will allow users to upload services/goods in respective categories, to add details (params, description, titles, price, etc.) on one hand. On the other hand it will allow users to purchase goods/service through ArtCoin and enter into possession of underutilized assets.
Categories, Params, Filters, Search, etc.
Service/good one page
Upload service/good functionality
Dashboard to track goods/services/payments/etc.
Timeline: 4 weeks
Requested Budget: $20000

Milestone 4 - Full dApp launch / mainnet version
All components manual tests
Predeployment (beta)
Beta testing (real users)
Bug fixing, golden master version (pre-release)
Golden master real-users testing
Final version launch
Timeline: 4 weeks
Requested Budget: $5000

Milestone 5 - First 5k users adoption
Onboarding (wallets creation, KYC, profile, etc.)
User Training: help users understand how the system works, how to navigate it, and how to get the most out of its features.
Timeline: 3 weeks
Requested Budget: $5000

Funds Usage:
Position: CTO, Manhours: 122, Price per H: 50, Total($): 6100
Position: Blockchain Developers, Manhours: 360, Price per H: 60, Total($): 21600
Position: Backend Developer, Manhours: 198, Price per H: 50, Total($): 9900
Position: Frontent/Multistack Developer, Manhours: 124, Price per H: 40, Total($): 4960
Position: Testers, Manhours: 198, Price per H: 25, Total($): 4950
Position: UIX/UI designer, Manhours: 83, Price per H: 30, Total($): 2490
Total($): 50000
Duration: 3 months

## Total Budget Requested

Total($): 50000

## Maintenance and Upgrade Plans

- Specify your team's long-term plans to maintain this project and improve it over time. 
> We have an insourced team of developers, that will maintain the project

# Team

## Team Members

Our management team:
Vasili Braga - Executive Director Creative Industries Association in Moldova. 

Viorica Cerbuska -  CEO Artcor Creative Industries Center & Yep!Moldova Founder, Startup Evangelist, PhD. 

Andrei Tintari - ArtCoin co-Founder, Web3 Moldova Community Founder, CTO. 

## Team Member LinkedIn Profiles

Vasili Braga’s  LinkedIn: https://www.linkedin.com/in/vasili-braga-4589b45a/
Viorica Cerbuska’s LinkedIn: https://www.linkedin.com/in/viorica-cerbusca-132547a/
Andrei Tintari’s LinkedIn: https://www.linkedin.com/in/andrei-tintari-839580218/

## Team Website

https://artcoin.media/

## Relevant Experience

Below are some examples from our web3 portfolio:

Near blockchain:
https://github.com/irinasoledy/soledynft
https://github.com/blockwebdevs/chainlib
https://github.com/iovitatudor/near-vue-proto
https://github.com/blockwebdevs/artcoin-landing/tree/master/contract

Polygon:
https://github.com/iovitatudor/blockaids
https://github.com/iovitatudor/blockaids-ssr
https://github.com/iovitatudor/avatar-generator
https://github.com/iovitatudor/blockaids-smart-contract
https://polygonscan.com/address/0xd3d65b24f2813ec152e4faa3dc714fc53ea5a47a

Casper Network:
https://github.com/likedevs/Artcoin-Casper/tree/master
https://github.com/likedevs/Artcoin-Casper/blob/master/README.md
https://github.com/likedevs/artcoin-cdn/blob/main/README.md
https://testnet.cspr.live/contract-package/4b69422d7ad9f07c8d4590aed690241d4d849c9385aa587f89260459e787237f

Solana:
https://github.com/blockwebdevs/BlockAids-solana-token
https://github.com/blockwebdevs/BlockAids-solana-token/blob/main/README.md
https://explorer.solana.com/address/DV78wP1FLFJp7Jr6YozurshB5fT7NeTK1KKoU6KbW6SF?cluster=testnet

A shortlist of our team members’ GitHub accounts:
https://github.com/iovitatudor
https://github.com/archiveiovita
https://github.com/blockwebdevs

## Team code repositories

Below are some examples from our web3 portfolio:

Near blockchain:
https://github.com/irinasoledy/soledynft
https://github.com/blockwebdevs/chainlib
https://github.com/iovitatudor/near-vue-proto
https://github.com/blockwebdevs/artcoin-landing/tree/master/contract

Polygon:
https://github.com/iovitatudor/blockaids
https://github.com/iovitatudor/blockaids-ssr
https://github.com/iovitatudor/avatar-generator
https://github.com/iovitatudor/blockaids-smart-contract
https://polygonscan.com/address/0xd3d65b24f2813ec152e4faa3dc714fc53ea5a47a

Casper Network:
https://github.com/likedevs/Artcoin-Casper/tree/master
https://github.com/likedevs/Artcoin-Casper/blob/master/README.md
https://github.com/likedevs/artcoin-cdn/blob/main/README.md
https://testnet.cspr.live/contract-package/4b69422d7ad9f07c8d4590aed690241d4d849c9385aa587f89260459e787237f

Solana:
https://github.com/blockwebdevs/BlockAids-solana-token
https://github.com/blockwebdevs/BlockAids-solana-token/blob/main/README.md
https://explorer.solana.com/address/DV78wP1FLFJp7Jr6YozurshB5fT7NeTK1KKoU6KbW6SF?cluster=testnet

A shortlist of our team members’ GitHub accounts:
https://github.com/iovitatudor
https://github.com/archiveiovita
https://github.com/blockwebdevs

# Additional Information
 How did you learn about the Open Grants Program? 
- website
 Please provide the best email address for discussing the grant agreement and general next steps. 
- team@artcoin.top
Please include any additional information that you think would be useful in helping us to evaluate your proposal. 
- Useful Links:
Demo version of ArtCoin technology:
https://artcoin.media/
Tutorial on how to use ArtCoin Currency and Technology:
https://github.com/likedevs/artcoin-cdn/blob/main/README.md
About COR community & organization
https://github.com/likedevs/artcoin-cdn/blob/main/README.md
Pitch deck: 
https://www.canva.com/design/DAFRRd71wJA/E13oraVPYTgzRDtr1ytfMQ/view?utm_content=DAFRRd71wJA&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink
Pitch deck (video):
https://youtu.be/u6V_SflNOSw
Milestones & Budgets & Team description:
https://docs.google.com/document/d/1ycKDW_X4xVxo1Sz7_2_y48KtkyTrfDBWZoYKl08JguI/edit?usp=sharing
ToR (ArtCoin technology):
https://drive.google.com/file/d/1VfSOBpgT2_if0QQBC71xBW5CmxO8hz-a/view?usp=sharing
Software Architecture:
https://miro.com/app/board/uXjVPsjRAlc=/?moveToWidget=3458764560616670929&cot=14
User Stories:
https://miro.com/app/board/uXjVPsjRAlc=/?moveToWidget=3458764561439908775&cot=14
Business Plan:
https://docs.google.com/spreadsheets/d/1K51khSXV5scab_ESvKc7oS70ETZdoJiKjeIxQ9XTfN8/edit?usp=sharing
Tokenomics:
https://docs.google.com/document/d/1mi5Ele8a-U1XtB8OKdaKGqXM7-LjI2h9ZQnlqns6T5E/edit?usp=sharing
Social Networks:
ArtCor Facebook
https://www.facebook.com/artcorcenter
ArtCor Instagram
https://www.instagram.com/artcor_center/
MediaCor Facebook
https://www.facebook.com/mediacormoldova
MediaCor Instagram
https://www.instagram.com/mediacor_hub/
ArtCoin Facebook
https://www.facebook.com/ArtCoinMarketSpace
ArtCoin Instagram
https://www.instagram.com/artcoin_marketplace/
ArtCoin LinkedIn
https://www.linkedin.com/company/artcoin-marketplace/?viewAsMember=true
ArtCoin Telegram
https://t.me/ArtCoinMD
GitHub repositories:
https://github.com/likedevs/Artcoin-Casper/tree/master
Smart-Contracts:
https://testnet.cspr.live/contract-package/4b69422d7ad9f07c8d4590aed690241d4d849c9385aa587f89260459e787237f

**Comment by ErinOCon** [comment]
Hi @DorianLesnic, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
