### ISSUE TITLE
Open Grant Application for WalletD, owned by Slaz Holdings Ltd

### ISSUE THREAD

**Issue by LivBoss** [filecoin-project/devgrants#1639]
# Open Grant Proposal: WalletD, owned by Slaz Holdings Ltd

**Project Name:** WalletD

**Proposal Category:** Developer and data tooling

**Individual or Entity Name:** The proposal is on behalf of our holding company, Slaz Holdings Ltd

**Proposer:** https://github.com/walletd/walletd

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

Describe the nature and scope of the problem you are addressing, and how this project will address that need. This section should be 2-3 paragraphs long:

Almost all blockchain projects, at their core, require wallet infrastructure. Even the most ambitious and innovative projects will need to interact with the blockchains they choose to operate on and, before they even come close to building their game-changing piece of technology, they will waste considerable time and resources on building their wallet infrastructure. Further to this, core infrastructure maintenance (hard, soft forks, and upgrades) require considerable resources.

We are building an open source multi-currency cryptocurrency wallet SDK which will allow any new or existing blockchain entrepreneurs to instantly build a fully operational, secure, and interoperable wallet infrastructure. In addition, the SDK will include pre-built integrations with existing blockchain and cryptocurrency service providers (such as swap providers, on/off-ramps, reporting tools etc) which can be added just as easily. In time, WalletD will become the backbone of almost all blockchain and cryptocurrency projects.

The main industry vertical of the WalletD project is the blockchain technology and cryptocurrency industry as a whole. WalletD focuses specifically on providing infrastructure solutions for the development of noncustodial cryptocurrency wallets and related services which are core pieces of infrastructure to these entire industries. This project aims to address challenges within the blockchain industry by streamlining wallet development, enabling seamless integration with various blockchains, and fostering cooperative growth and innovation within the broader cryptocurrency ecosystem.

## Impact 

With our experience drawn from building and operating the most popular non-custodial Monero wallet, MyMonero, we know that building a wallet is difficult and that even one mistake can cause an entire project to fall apart. So the entire industry is wasting time and money on building something that should be easy and we’re all missing out on the true innovation that most developers and entrepreneurs intend to bring to their projects and the world. 

Firstly, what this wallet module will do is allow developers looking to build in the Filecoin ecosystem a foundation to build upon. Almost every blockchain project needs a wallet and WalletD will provide a fully-functional wallet module which can become the base upon which any future FIL tool could be built. However, this is just the tip of the iceberg.

The second and most important consequence of this module is that developers building any blockchain project or tools can incorporate Filecoin into their project without the need for any additional resource spend. FIL tokens can quickly be incorporated into any multi-chain environment and become a part of the interconnected multi-ecosystem blockchain industry. This means that there will be increased exposure to Filecoin, increased use and trading of the FIL token, and the potential for a wider range of tools becoming available to the Filecoin ecosystem.

WalletD will scale quickly to become a significant infrastructure and developer tooling player in the web3 ecosystem with the aim of becoming the multi-chain wallet backbone of every commercial blockchain project. In doing so, WalletD will generate significant value for the wider web3 and crypto ecosystem players, developers and community.
And as the WalletD SDK user base grows, so does the user base of any interconnected network, in this case being the Filecoin network.

## Outcomes

Our final outcomes and deliverables for the WalletD project as a whole can be found at this link:
https://docsend.com/view/igqej3gfa5txk2mp

We have also release our alpha, view a sneak peek here:
https://www.loom.com/share/44c469525d434152b250d292078c350a?sid=62df1ba3-4b21-44c8-bdf4-9141f1a10be4

We will also be creating an ecosystem based in the WalletD Token which can be earned by participating in the contribution to the open source SDK (which we call the Build2Earn program) as well as by utilizing the SDK in your own project infrastructure and sharing certain metrics about that product’s use (which we call the Grow2Earn program). The tokens themselves will also entitle the holders to a share of the entire project’s profit as well as allowing holders participation in the governance of the project.

Please see the Tokenomics Litepaper here:
https://docsend.com/view/q6srtveubs6tuez3

## Adoption, Reach, and Growth Strategies

We have released the first modules in the WalletD SDK, including support for Bitcoin and Ethereum.

You can view a wallet CLI demo here, hosted by our Head of Engineering:
https://www.loom.com/share/44c469525d434152b250d292078c350a?sid=62df1ba3-4b21-44c8-bdf4-9141f1a10be4

We are currently working on the XMR and SOL modules which should be released within this quarter.

We will also be creating our own multicurrency wallet application (the Slaz Wallet) which will be the first commercialization of the WalletD library, and a demonstration of the library's capabilities to other developers and projects. Through leveraging existing projects, we will be starting Slaz with over 500, 000 monthly active users.

We don’t have a way to track WalletD users, since our software is open source and is being made available to any and all developers.

## Development Roadmap

Milestone 1: 
Integration module for Filecoin in WalletD.
Estimated Timeline: Two months
To achieve this milestone, we would require our full time development team, which consists of a Head of Engineering, three Senior Engineers and one Project Manager.
The grant funds would cover a portion of the following monthly cost breakdown:

Head of Engineering - Cost: $25,000
Senior Engineer 1 - Cost: $17,500
Senior Engineer 2 - Cost: $17,500
Senior Engineer 3 - Cost: $17,500
Operations Manager - Cost: $12,500

[Breakdown of Milestone 1]:

Integration Setup:
Establish communication channels between WalletD and Filecoin, ensuring compatibility and data exchange.
Define the integration protocol and message formats to facilitate seamless interaction between the two systems.
Set up authentication and security measures to ensure secure communication between WalletD and Filecoin.

Error Handling and Reporting:
Implement robust error handling mechanisms to handle exceptions, errors, and edge cases effectively.
Develop detailed error reporting capabilities to provide informative and actionable feedback in case of any issues during the integration process.

Testing and Documentation:
Conduct thorough testing of the integration to ensure the functionality, reliability, and security of the integration.
Document the integration process, including setup instructions, API documentation, and troubleshooting guides for future reference and support.

Milestone 2:
Smart Contract Support. This would include, but is not limited to the development of the functionality within WalletD to enable the deployment of smart contracts which interact directly with Filecoin.
Estimated Timeline: One month
To achieve this milestone, we would require our full time development team, which consists of a Head of Engineering, three Senior Engineers and one Project Manager.
The grant funds would cover a portion of the following monthly cost breakdown:

Head of Engineering - Cost: $25,000
Senior Engineer 1 - Cost: $17,500
Senior Engineer 2 - Cost: $17,500
Senior Engineer 3 - Cost: $17,500
Operations Manager - Cost: $12,500

[Breakdown of Milestone 2]:

Smart Contract Integration:
Define the integration approach for supporting smart contracts within WalletD and Filecoin.
Research and select appropriate smart contract platforms or frameworks that align with the requirements of both WalletD and Filecoin.
Establish the necessary connections and communication channels between WalletD and the selected smart contract platform.

Smart Contract Deployment:
Develop functionality using WalletD to enable the deployment of smart contracts onto the selected platform.
Using WalletD, we will implement a user-friendly interface for users to interact with the deployed smart contracts.
Enable the configuration of contract parameters, such as gas limits and contract initializations, using WalletD

Contract Interaction:
Implement methods for reading and retrieving data from smart contracts, providing real-time information for users within the Filecoin ecosystem.
Enable transaction signing and submission for executing contract transactions, ensuring proper validation and security measures.

Event Handling:
Implement event handling capabilities using WalletD, to capture and process events emitted by smart contracts.
Integrate event listeners to track and notify users of relevant contract events, such as transfers, state changes, or custom events.
Develop mechanisms to store and retrieve event data for future reference and analysis within WalletD and Filecoin.

## Total Budget Requested

| Milestone # | Description | Deliverables | Completion Date | Funding |
|===|===|===|===|===|

## Maintenance and Upgrade Plans

We aim to support as many blockchains as possible and will leverage a comprehensive and efficient token-based incentive scheme to ensure committed and experienced community contributors to build and maintain these libraries. At this stage, we have built out a brilliant- albeit small- team to develop and maintain our first few modules which are already live and available to the public. The aim is to build up our internal and community teams as quickly as possible to ensure that the project can keep growing and that developers have the ability to build out the tools of their dreams. A big part of this is the WalletD Token so the finalization of its development and its issuance are key to building up this team. 

# Team

## Team Members

Riccardo Spagni - Founder & CEO of WalletD
Zaheer Seedat - CFO
Jonathan Purnell - General Counsel
Devin Pearson - Head of Engineering
Karl Buys - Senior Engineer
Elaine Botha - UX/UI Engineer
Patrizio Spitalieri - COO

## Team Member LinkedIn Profiles

Zaheer Seedat - https://www.linkedin.com/in/zaheer-seedat-ca-sa-7aa8b558/
Jonathan Purnell - https://www.linkedin.com/in/jonathan-purnell-874069105/
Devin Pearson - https://www.linkedin.com/in/pearsondevin/
Karl Buys - https://www.linkedin.com/in/karl-buys/
Elaine Botha - https://www.linkedin.com/in/elaine-botha-31345542/
Patrizio Spitalieri - https://www.linkedin.com/in/patrizio-spitalieri/

## Team Website

https://developer.walletd.org/

## Relevant Experience

Riccardo Spagni - 
Our key team member, Riccardo Spagni has been involved in the cryptocurrency world since the early stages as he has been a member of the Monero Core Team since Monero’s inception. He acted as its first Lead Maintainer and was one of its core contributors for many years. Since then, he was the founder of cryptocurrency invoicing platform, GloBee; the founder and CEO of MyMonero; the Co-Founder of Tari (an upcoming smart contract protocol operating as a sidechain of Monero); Co-Founder of Yat; as well as a founder and CEO of a number of more traditional businesses.

Zaheer Seedat - 
Zaheer has previously worked in the financial sector with some reputable institutions, such as Deloitte South Africa, ABSA Bank, and Nedbank. 
He is currently the CFO for The Spagnis, which is an investment office focused mainly on the cryptocurrency and NFT industries. This has allowed him to gain extensive experience within the crypto space.
As a financial leader of 9-figure valuation crypto companies, he has become an asset as the CFO of Slaz.

Jonathan Purnell - 
Jonathan completed his Bachelor of Laws at the University of Cape Town and his Masters of Laws at New York University. He has 5 years experience working at the world renowned Norton Rose Fulbright as a tax attorney and being influential in the establishment of their cryptocurrency and blockchain practices. Since becoming the General Counsel for The Spagnis, as well as for Tari Labs, he has developed a deep understanding of the practical and regulatory laws within the crypto industry. He is currently the acting General Counsel for Slaz.

Devin Pearson - 
Devin operates at a senior level, with 15 years of software development under his belt.
He started out as a PHP Developer, and worked as a Software Architect for GloBee, where he started to grow his knowledge in crypto technology and development. With a massive amount of experience in the space, he has been a force to be reckoned with as the Lead Maintainer of MyMonero. He is putting his extensive knowledge of crypto tech to work as the Head of Engineering for Slaz.

Karl Buys - 
Karl has a strong 18 years of software development experience, which has given him extensive experience and a deep understanding of the dev environment. He operates at a senior level within the crypto dev space, and he put this extensive knowledge to work when he joined The Spagnis team as Development Lead. He then became a Core Developer at MyMonero, and has since become a strong asset to the Slaz team as a Senior Software Development Engineer.

Elaine Botha - 
Elaine has gained massive web and design experience over the past 14 years. She has worked on many international projects while leading the UI/UX team at the BMW Group South Africa. This experience has given her a deep understanding of technology and web design, which made her a brilliant addition to the Slaz team full-time as a UX/UI Developer.

Patrizio Spitalieri - 
Patrizio completed his Bachelors Degree in Business Administration and Management at Regent Business School. He built a high skill-set while working for GloBee as the head of Business Development and Operations. This gave him the edge when it came to understanding the inner workings of crypto in the business space. He then moved on to become the Head of Operations, Crypto Payments and Digital Asset Interoperability at MyMonero. The leadership and business development skills that he possesses are an asset to the Slaz team, where he now holds the role of Head of Operations and Growth.

## Team code repositories

Riccardo Spagni: https://github.com/fluffypony
Devin Pearson: https://github.com/devinpearson
Karl Buys: https://github.com/karlbuys

# Additional Information

We learnt about the Open Grants Program through research in the industry.

Our contact email address is: [patrizio.spitalieri@slaz.com](mailto:patrizio.spitalieri@slaz.com)

Our competitive advantage sits in the experience of our team which consists of the Core Monero Team & Ex-Lead Maintainer of Monero; the development team behind the largest non-custodial Monero wallet, MyMonero; and legal and finance teams with over 5 years of experience in the cryptocurrency field. In addition, we will leverage a state-of-the-art token-based incentivisation and governance structure which will ensure the committed participation of a growing community.

View our video pitch here: https://youtu.be/IQjXump9m84
Origin Story: https://docsend.com/view/4apqfpvnf3cdfdij
Pitch Deck, Developer Documents, Tokenomics Litepaper and Whitepaper: https://docsend.com/view/5x456mkbzzxc4w2z

**Comment by ErinOCon** [comment]
@LivBoss, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
