### ISSUE TITLE
open grant application to integrate Atriv AI with Filecoin Network

### ISSUE THREAD

**Issue by Sebhatu** [filecoin-project/devgrants#1641]
# Open Grant Proposal: `Atriv AI `

**Project Name:** Atriv AI  

**Proposal Category:**  Applications and  Integrations

**Individual or Entity Name:** PrimeSynapse B.V.  

**Proposer:** https://github.com/Sebhatu

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes
# Project Summary

Atriv AI is a revolutionary platform that enables users to transform their words into unique, one-of-a-kind NFTs using machine learning and natural language processing. Users can input their imaginative text into our generator, which then converts it into exquisite digital art. Once satisfied, they can tokenize their creation and share it with the world. This platform bridges the gap between creativity and blockchain technology, providing an intuitive, user-friendly interface that allows everyone to bring their imagination to life using the power of generative AI.

## Impact 

The integration of Filecoin into Atriv AI will address several pain points in the digital art and NFT ecosystem:

1. **Storage**: Artists and creators often struggle with finding secure and efficient storage solutions for their digital assets. With the integration of Filecoin, Atriv AI will offer decentralized storage, improving data integrity and resistance to censorship or data loss.
2. **Monetization**: Artists will be able to monetize their art by creating unique digital tokens for their artwork, proving provenance, ownership, and authenticity on the blockchain.
3. **Creation**: The process of creating NFTs and digital art will be simplified, opening up opportunities for artists who are not familiar with coding or blockchain technology.

The success of this project will be measured by the number of artists and creators using the platform, the amount of digital art created and stored, and the overall user satisfaction with the platform's features and functionalities.

## Outcomes

The final deliverables for this project will include:

1. **Filecoin Integration**: Integration of Filecoin into Atriv's storage system and the ability for users to create NFTs directly on Filecoin's Virtual Machine (FVM).
2. **White-label Collections**: Development of white-label collections for different use cases such as art collections, in-game assets, and business membership contracts.

## Adoption, Reach, and Growth Strategies

With our acceptance into the Google Web3 startup program, we have already garnered interest from 120 generative artists who are enthusiastic about accessing the early beta launch of our dashboard. The target audience for Atriv AI includes digital artists, NFT collectors, and businesses looking to create digital assets or membership contracts.

We plan to engage with our target audience through social media marketing, partnerships with art institutions and online art communities, and by participating in relevant events and webinars. To onboard new users, we will offer tutorials and educational content on our platform, explaining how to create, tokenize, and monetize digital art using Atriv AI. Additionally, we will provide customer support through our website and social media channels to assist users with any questions or issues they may encounter.

### Milestone 1: Filecoin Integration
- **Functionality**: Integration of Filecoin into Atriv's storage system and enable users to create NFTs directly on FVM.
- **People**: 2 developers
- **Funding**: $20,000
- **Time**: 2 months

### Milestone 2: White-label Collections
- **Functionality**: Development of white-label collections for different use cases.
- **People**: 2 developers
- **Funding**: $20,000
- **Time**: 2 months

## Total Budget Requested

$40,000 

## Maintenance and Upgrade Plans

We plan to continuously update and improve the Atriv AI platform based on user feedback and technological advancements. We will also monitor the performance of the Filecoin integration and make any necessary adjustments or optimizations. Our team will provide ongoing customer support and create additional educational content as needed. Being part of the Google Web3 startup program, we have access to $200k cloud credit, including GPU for 2 years, which will allow us to maintain our platform and add new features without worrying about infrastructure cost.

# Team

## Team Members

Abel Sebahtu , CEO & Co-founder 
Makda Sebhatu, CTO & Co-founder 

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/abel-sebhatu/
https://www.linkedin.com/in/makda-sebhatu-9544331b4/

## Relevant Experience

Our team has extensive experience in developing and deploying blockchain-based applications, machine learning, and natural language processing. We have successfully developed and launched several applications in the past, and our team members have worked for reputable technology companies and research institutions. Both co-founders previously worked on decentralized storage and infrastructure projects like Moralis. We have successfully deployed a stable diffusion model that can handle 1000 image generations in one click, and are currently working on sketch-image generation and a fine-tuning feature, where artists can retrain the model on their own artwork.

## Team code repositories
https://github.com/Sebhatu
https://github.com/Maki44

# Additional Information
I learned about the Grants Program through my participation in the Filecoin Launchpad Accelerator, Cohort 5, last year. 

 Our contact email address is: [abel@atriv.ai ](mailto:abel@atriv.ai )

We can provide access to our platform upon request.

**Comment by ErinOCon** [comment]
HI @Sebhatu, thank you for your proposal and for your patience with our review. Unfortunately, we will not be proceeding with a grant at this time. Wishing you all the best as you continue to build!
