### ISSUE TITLE
🏛 Open Grant Proposal: BaseX

### ISSUE THREAD

**Issue by marsrobertson** [filecoin-project/devgrants#1642]
# 🏛 Open Grant Proposal: BaseX

**Project Name:** `BaseX`

**Proposal Category:** `Applications`

**Individual or Entity Name:** `BaseX OÜ` _([E-Estonia legal entity](https://www.inforegister.ee/en/14986163-BASEX-OU))_

**Proposer:** `@marsrobertson`

**(Optional) Filecoin ecosystem affiliations:** `N/A`

I had a chance to meet with some fantastic humans at EthCC in Paris. High energy team. Passionate people. Great conversations. No affiliation though. 

**(Optional) Technical Sponsor:** `N/A`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** `Yes`

# Project Summary

Problem: misaligned incentives of the economic system, not accounting for externalities. Some actions are profitable because they externalise harm into nature, future, vulnerable communities, without accounting for collateral damage.

BaseX addresses this problem by accounting for externalities. We use reports and evaluations and we rely on independent jurors who fact-check accuracy of the claims.

What is **UNIQUE** - using self-assessment (bottom up) and verification layer as opposed to centralised (top down) approach.

Diagram illustrating the difference in evaluation between BaseX and legacy approach:

![BaseX bottom up](https://github.com/filecoin-project/devgrants/assets/44369284/66637abc-cfe1-4452-a1bb-cb91e98074fe)

## Impact 

We use IPFS to keep the reports and evaluations in the original form.

Without BaseX - externalities of economic activities being "outsourced" to nature, future generation, vulnerable communities.

With BaseX - proper accounting for impact in a scalable way.

## Outcomes

We have just released https://beta.basex.com/ and we are ready to onboard real-world users.

We are yet to hear from our users and build traction. 

Our primary metrics of success: number of reports, number of evaluations, returning users.

## Adoption, Reach, and Growth Strategies

Gitcoin 💯 💯 💯

Pretty much everyone in the Web3 knows about Gitcoin and vast majority of climate-aware projects are using Gitcoin funding rounds.

This is an obvious place to reach out for partnerships and invite projects participating in Gitcoin to evaluate their impact on BaseX.

## Development Roadmap

Roadmap: https://wiki.basex.com/Roadmap-00d4fb7d392d4d83a8a486afb5899665

IPFS copy (28th August 2023): https://pin.ski/45GPQJK _(so that we remain accountable)_

Summary of the roadmap above: tokenomics. The key for healthy and sustainable economy is the tokenomics that will ensure correct game theory and incentives.

### Milestone 0 ✅

We have just launched [beta.basex.com](http://beta.basex.com/) and we are ready for the outreach.

### Milestone 1

Onboarding users / organisation into BaseX.

### Milestone 2

Implementing advanced tokenomics features that allow to mint new tokens while ensuring economic sustainability. 

**TODO:** We really tried hard to put detailed, specific, measurable, actionable milestones. We are very proud to launch beta and our priority now is to onboard new users (described in milestone 1) and for the next release we definitely want to improve the tokenomics (described in milestone 2)

## Total Budget Requested

| Milestone # | Description | Deliverables | Completion Date | Funding |
|---|---|---|---|---|
| 1 | Onboarding | Inviting users, partners, organisations to use the plaform and getting at least 50 organisations onboard | 31.03.2024 | $20000 |
| 2 | Tokenomics | Implementing advanced features related to token economy that will ensure sustainability of the project | 31.03.2024 | $30000 |

## Maintenance and Upgrade Plans

Currently we are in beta - phase of rapid experimentation. Currently we retain admin controls to upgrade the contracts when necessary. Longer term we prefer to run the BaseX in the trestles and decentralised manner - that will involve governance module and token voting.

If practical, we will also decentralise the front-end so it hosted on IPFS. For the time being, for the benefit of speed we host it on Vercel.

# Team

## Team Members

* Mars Robertson
* Greg Trifan

## Team Member LinkedIn Profiles

* https://www.linkedin.com/in/marsrobertson/
* https://www.linkedin.com/in/grigore-trifan-666biyz/

## Team Website

* https://basex.com/ - main page
* https://wiki.basex.com/Team-e07a00ea4f4a481c976b853f3b10d4d2 - dedicated team page

## Relevant Experience

* Mars: deep understanding of climate and exponential technologies. 10+ years of software / web dev experience. Recently on the entrepreneurial side.

* Mars: I have experience using Kleros (blockchain justice, community of jurors) which is an integral building block - independent fact-checking of reports and evaluations.
* Greg: excellent full-stack developer.

## Team code repositories

Existing code repos:
* https://github.com/basexhq/front-end
* https://github.com/basexhq/esgtbl-smart-contract _(currently private, will make it public, need to do some housekeeping, in case accidentally comitted secrets or API keys)_

Prior code repos:
* Mars: TOP 3% on StackOverflow: https://stackoverflow.com/users/775359/mars-robertson
* Greg: https://github.com/dspytdao/PinSave-EVM

# Additional Information

We learnt about the Open Grants Program because Protocol Labs is an integral part of the community.

Best email address: [info@basex.com](mailto:info@basex.com)

From the [instructions](https://github.com/filecoin-project/devgrants/tree/master/open-grants):

> We will review your application. During review, we will add comments, questions, change requests, etcetera on your team's submission.

We are fully determined to answer any questions you may have. 

Sometimes the headers are different than supplementary questions in the `<-- comments -->`, we tried to figure out the intention.

Best way moving forward: https://calendly.com/marsxr/basex ☎️ 

_(any questions will be able to explain quickly and efficiently)_

**Comment by marsrobertson** [comment]
**FYI
RELATED** 

We recently released https://beta.basex.com and there are still various (relatively minor) front-end bugs to fix: https://github.com/basexhq/front-end/issues

<img width="909" alt="image" src="https://github.com/filecoin-project/devgrants/assets/44369284/b6275e3d-6892-4c37-8d0c-ecf63a11fd73">

On the other hand - this is slowing down onboarding new projects - first impression that counts.

![image](https://github.com/filecoin-project/devgrants/assets/44369284/39804c4d-39b0-45e0-8ab0-529d4314ad04)

I'm embarassed a little bit, but I have 100% confidence this can be fixed 💪

**Comment by ErinOCon** [comment]
HI @marsrobertson, thank you for your proposal and for the provided update regarding your initial release! Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
