### ISSUE TITLE
Next Step Microgrant: Web 3 Edi

### ISSUE THREAD

**Issue by cryptotwilight** [filecoin-project/devgrants#1643]
### 1. What is your project, and what problem does it solve? (max 100 words)

Web 3 Edi 

### 2. Project links

https://www.web3edi.com
https://web3edi.on.fleek.co
https://github.com/Web3Edi/2022-alpha

License: [GPL-3.0 license](https://github.com/Web3Edi/2022-alpha/blob/main/LICENSE)

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

Web 3 Edi currently uses Livepeer to facilitate community broadcasting and recording. NFTs are made of recordings which are stored on IPFS. Course ware, accreditations, and modules are stored on IPFS with creator tools leveraging IPFS for all data storage including analytics. IPFS is provisioned on a multi-tenant model that supports individual users, communities and events. Smart contracts are written in Solidity, with frontend in JS

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |   Multi-tenant Provisioning System |  We will build this using solidity for core FVM on chain functions. Where necessary we will use FVM native contracts to ease IPFS integration. We will use JS/React for front-end and API integration          |     1 month                       |  
| 2.     |   Basic Course creation tool                      | This will be built using JS/React and IPFS via the Multi-tenant Provisioning System.                                                           |   1 month                        | 
| 3.     |   Candidate Course Preview Experience                      |   This will be built using JS/React  with course/feature payments supported via FVM                               |    1 month                        | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

**Yes**
  
### 6. Does your proposal comply with our Community Code of Conduct?

**Yes**

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Yes, - Links no longer availabel

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Tony Ushe, tonyusheuk@gmail.com https://github.com/cryptotwilight - founder, fullstack developer

* How did you learn about our microgrant program?
Web3Con
* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
  Web 3 Con 
  * Please link to your hackathon submission
  https://github.com/cryptotwilight/web3edi

**Comment by ErinOCon** [comment]
HI @cryptotwilight, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant for this project. Please feel welcome to contact our team at [grants@fil.org](mailto:grants@fil.org) with any questions.

Wishing you the best as you continue to build!
