### ISSUE TITLE
Next Step Microgrant: Radio Vault - music NFT marketplace and streaming service

### ISSUE THREAD

**Issue by yourmercury** [filecoin-project/devgrants#1645]
### 1. What is your project, and what problem does it solve? (max 100 words)
Radio Vaults is a Technology that would be used for uploading NFT assets and deploying NFT contracts, especially Music NFT Assets to IPFS. The perk of using this app is that you can permission (whitelisting access to assets) and track access to these assets and also count and analyze streams from NFT Marketplaces and wallets using the metadata. With the Meta-verse in view, music NFTs will be here too and so we are presenting a way to secure musicians assets from plagiarism (stripping metadata to make other NFT contracts) and serve as a decentralized streaming platform.

### 2. Project links
  
Link to Github repo: https://github.com/yourmercury/radio-vault-prod
Link to demo or website:  
     webapp:    https://app.radiovaults.com
     landing page:    https://www.radiovaults.com
License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
IPFS using NFT.storage is used to store music metadata as well as NFT metadata. Users can then use the Deployment section of the website to deploy their music NFT to Filecoin network

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
YES
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
A big thank you for the first funding. The grant took us through concurrent research and development to the point that we are in.
The Next step we are in is building the Prototype Streaming service / Music NFT Marketplace. We need the funding to take us through the period when we would be designing the User Interface and Building the frontend.
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---:       | :---                           |     :----                                                                                    |  :---:
|1 | Prototype UI and UX design and Smart contracts for Streaming Platform. | Emmanuel will be designing the streaming service / marketplace and DAO interface using the laid down features decided upon by the team. I would be concurrently planning and developing the needed Prototype smart contracts while The UI is being designed by Emmanuel so as not to leave any feature undesigned on the UI. | 2 months |
|2 | Prototype Frontend development. | Osarodion would be Tasked with developing the Frontend of the application off the UI UX design. | 1 month |

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: https://devpost.com/software/radio-vaults
  
### Additional questions:
Polycarp Momoh, [momohpolycarp@gmail.com](mailto:momohpolycarp@gmail.com), https://github.com/yourmercury, Lead Developer
Osarodion Osayande, [josiahosarodion@gmail.com](mailto:josiahosarodion@gmail.com), https://github.com/sahrodion, frontend developer
Emmanuel Okpiapano, [kingemmy04@gmail.com](mailto:kingemmy04@gmail.com), UI UX designer

* How did you learn about our microgrant program? 
* Ans: A friend of mine saw what we were building and told me about the grant opportunity

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Ans: Chainlink Fall Hackathon
  

  * Please link to your hackathon submission
  * Ans: https://devpost.com/software/radio-vaults

**Comment by ErinOCon** [comment]
Hi @yourmercury, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant for this project. Please feel welcome to contact our team at [grants@fil.org](mailto:grants@fil.org) with any questions.

Wishing you the best as you continue to build!
