### ISSUE TITLE
Next Step Microgrant: Amarum - A Paywall Video Dataset Marketplace with a DataDAO

### ISSUE THREAD

**Issue by holyaustin** [filecoin-project/devgrants#1649]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>

</head>
<body lang="en-US" link="#000080" vlink="#800000" dir="ltr"><p style="margin-bottom: 0cm; line-height: 100%">
### 1. What is your project, and what problem does it solve? (max 100
words) </p>
<p style="margin-bottom: 0cm; line-height: 100%">Amarum: Most
Datasets especially video datasets are available on centralized
storage. This means that this storage can disappear one day and
cannot be available for users in the nearest future. Amarum is a Data
DAO video project with the aim of helping creators publish exciting
video datasets while getting rewarded for that. The datasets upon
submission is curated and stored on filecoin SPs through data deals
that are established by the DAO. The DAO has the responsibility of
storing these datasets and making money from the marketplace paywall.
The accrued income is distributed both to DAO members and some kept
in the DAO treasury. 
</p>
<p style="margin-bottom: 0cm; line-height: 100%">The project is built
Filecoin DataDAO template and deployed to FVM. 
</p>
<p style="margin-bottom: 0cm; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0cm; line-height: 100%">### 2. Project links
</p>
<p style="margin-bottom: 0cm; line-height: 100%">Link to Github repo:
https://github.com/holyaustin/Amarum</p>
<p style="margin-bottom: 0cm; line-height: 100%">Link to demo or
website: https://amarum.vercel.app/</p>
<p style="margin-bottom: 0cm; line-height: 100%">License: MIT</p>
<p style="margin-bottom: 0cm; line-height: 100%">  
</p>
<p style="margin-bottom: 0cm; line-height: 100%">### 3. a) How is
IPFS, Filecoin, or related technology used in this project?</p>
<p style="margin-bottom: 0cm; line-height: 100%">IPFS, Filecoin is
used as the Blockchain of choice to deploy the DataDAO smart 
contract and the deal making smart contract to service providers. FVM
plays a vital role in this trustless contracts between the DAO and
the Service providers.</p>
<p style="margin-bottom: 0cm; line-height: 100%">The technical design
implores using the FVM data storage helpers to first receive the data
for consideration by the DAO.</p>
<p style="margin-bottom: 0cm; line-height: 100%">When video dataset
is received, a proposal for the Dataset is opened for voting by the
DAO admin. If the proposal is accepted, the, the DAO admin brokers a
deal with storage providers to store the Datasets for the DAO. The
DAO have a paywall where such datasets are listed for users to pay /
buy and use for their experiments.</p>
<p style="margin-bottom: 0cm; line-height: 100%">IPFS Services and
tools used includes but no limited to</p>
<p style="margin-bottom: 0cm; line-height: 100%">1.  DataDao Kit for
the DataDAO</p>
<p style="margin-bottom: 0cm; line-height: 100%">2.  FEVM HardHat Kit
– Template for deploying to FVM</p>
<p style="margin-bottom: 0cm; line-height: 100%">3.  Filecoin
Solidity API Library Used to interact with Solidity API</p>
<p style="margin-bottom: 0cm; line-height: 100%">4. 
filecoin-address: JavaScript libraries</p>
<p style="margin-bottom: 0cm; line-height: 100%">5.  Cross-Chain
bridges for payment from other Blockchain tokens</p>
<p style="margin-bottom: 0cm; line-height: 100%">6. IPFS CID Checker</p>
<p style="margin-bottom: 0cm; line-height: 100%">7. Deal Making kit
for DAO admin to make deals for Datasets</p>
<p style="margin-bottom: 0cm; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0cm; line-height: 100%">###    b) Is this
project building with the current microgrants focus area (FVM)? (Yes
or No)</p>
<p style="margin-bottom: 0cm; line-height: 100%">  Yes. This project
is focused on FVM and is currently deployed on Filecoin (calibration)
Testnet.</p>
<p style="margin-bottom: 0cm; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0cm; line-height: 100%">### 4. How will you
improve your project with this grant? What steps will you take to
meet this objective? 
</p>

Milestone No. | Milestone Description and staffing | Funding | Estimated Time frame
-- | -- | -- | --
1 | Blockchain Back-end (Smart contract development / Testing) 				Work on the DataDAo 				Smart Contract 				Add the Deal Making 				Smart Contract 				Deploying to FVM 				Testnet 				Write Tests and check 				contract for effectiveness and efficiency 				  				 				1 developer work 25hrs per week @ $30 * 25*4 = 				$3,000 | $3,000 | 4 weeks. 				  				 				(1/10/23  				 				–  				 				28/10/23)
2 | Front-end (UI/UX) + Mobile 				responsiveness 				work 				for 5 hours / day for 5 days a week =  25 hours per week 				25 				hours per week x 4 weeks = 100 hours 				$20 				per hour x 100 = $2000 | $2,000 | 4 weeks. 				  				 				(29/10/223 				 -  				 				25/11/23)
3 | Documentation 				+ Community Building + 				Testing 				1 				technical writer for 4 				weeks @ $500 				= $500 				  				 				  				 				Social media community 				building / strategist.  				 				1 social media strategist  				for 4 weeks 				@ 500 				= $500 | $1,000 | 4 weeks. 				  				 				(26/11/23  				 				-  				 				20/12/23)
  | Project Launch | $6,000 | 12 weeks

<p style="margin-bottom: 0cm; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0cm; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0cm; line-height: 100%">### 5. If accepted,
do you agree to share monthly project updates in this Github issue
for 3 months or until the project described here is complete?</p>
<p style="margin-bottom: 0cm; line-height: 100%">Yes. Report should
be delivered.</p>
<p style="margin-bottom: 0cm; line-height: 100%">  
</p>
<p style="margin-bottom: 0cm; line-height: 100%">### 6. Does your
proposal comply with our Community Code of Conduct?</p>
<p style="margin-bottom: 0cm; line-height: 100%">Yes it comply with
the community code of conduct</p>
<p style="margin-bottom: 0cm; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0cm; line-height: 100%">### 7. Links and
submissions</p>
<p style="margin-bottom: 0cm; line-height: 100%">* If your project
began at a hackathon, have you submitted it for the relevant Protocol
Labs prizes? Include links here if available:</p>
<p style="margin-bottom: 0cm; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0cm; line-height: 100%">The project began as
an ETHGlobal HackFS hackathon and submitted foe the DataDAO category</p>
<p style="margin-bottom: 0cm; line-height: 100%"><a href="https://ethglobal.com/showcase/amarum-h7khc">https://ethglobal.com/showcase/amarum-h7khc</a>
</p>
<p style="margin-bottom: 0cm; line-height: 100%"><a href="https://amarum.vercel.app/">https://amarum.vercel.app/</a></p>
<p style="margin-bottom: 0cm; line-height: 100%"><a href="https://github.com/holyaustin/Amarum">https://github.com/holyaustin/Amarum</a></p>
<p style="margin-bottom: 0cm; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0cm; line-height: 100%">  
</p>
<p style="margin-bottom: 0cm; line-height: 100%">### Additional
questions:</p>
<p style="margin-bottom: 0cm; line-height: 100%">* For each team
member(s), please list name, email, Github account, and role in the
project.</p>
<p style="margin-bottom: 0cm; line-height: 100%">- Team Member 1 –
holyaustin / <a href="https://www.linkedin.com/in/holyaustin/">https://www.linkedin.com/in/holyaustin/</a></p>
<p align="left" style="margin-bottom: 0cm; line-height: 100%">Email:
<a href="mailto:holyaustin@yahoo.com">holyaustin@yahoo.com</a></p>
<p align="left" style="margin-bottom: 0cm; line-height: 100%">Github:
<a href="https://github.com/holyaustin/Amarum">https://github.com/holyaustin/Amarum</a></p>
<p align="left" style="margin-bottom: 0cm; line-height: 100%">Twitter:
https://twitter.com/holyaustin</p>
<p align="left" style="margin-bottom: 0cm; line-height: 100%"><br/>

</p>
<p align="left" style="margin-bottom: 0cm; line-height: 100%">- Team
Member 2,3,4 – will recruit more hands to join the team once for
frontend, community manager and technical writer once this proposal
is approved</p>
<p align="left" style="margin-bottom: 0cm; line-height: 100%"><br/>

</p>
<p style="margin-bottom: 0cm; line-height: 100%">* How did you learn
about our microgrant program?</p>
<p style="margin-bottom: 0cm; line-height: 100%">	From IPFS Community
Forum</p>
<p style="margin-bottom: 0cm; line-height: 100%">* If your project
was created as part of an event or hackathon:</p>
<p style="margin-bottom: 0cm; line-height: 100%">	ETHGlobal HackFS
hackathon</p>
<p style="margin-bottom: 0cm; line-height: 100%">* Please link to
your hackathon submission</p>
<p style="margin-bottom: 0cm; line-height: 100%">	https://ethglobal.com/showcase/amarum-h7khc</p>
</body>
</html>

**Comment by ErinOCon** [comment]
Hi @holyaustin, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant for this project. Please feel welcome to contact our team at [grants@fil.org](mailto:grants@fil.org) with any questions.

Wishing you the best as you continue to build!
