### ISSUE TITLE
NFT.Storage: LACMA’s first NFT Archive Collection

### ISSUE THREAD

**Issue by elizabeth-griffiths** [filecoin-project/devgrants#1651]
# Open Grant Proposal: NFT.Storage: LACMA’s first NFT Archive Collection

**Project Name:**
NFT.Storage: LACMA’s first NFT Archive Collection

**Proposal Category:** 
 `Applications`

**Individual or Entity Name:** Is the proposal on behalf of an individual, or an entity/organization? Please note that the agreement and any payments must be completed by the same entity, either individual or organization.
NFT.Storage

**Proposer:** 
@elizabeth-griffiths

**(Optional) Filecoin ecosystem affiliations:** 
NFT.Storage is a part of Protocol Labs

**(Optional) Technical Sponsor:** `

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes, for all relevant work

# Project Summary

Los Angeles County Museum of Art, LACMA, is one of most notable art institutions in the world. They are interested in converting a curated collection from their physical archive to a public digital archive in the form of NFTs. 

We will secure the partnership and work closely with them to create their NFT Collection by using NFT.Storage, IPFS and Filecoin for the off-chain NFT data. 

In the future, this project could extend to more of their archive being minted.

## Impact 

We also expect the impact of the NFT Collection launch to have a very positive impact: 

- The NFT Collection will be a fundraiser for the institute, so they are incentivized to heavily market and advertise it.
- As the institute has millions of visitors a year, we expect to reach millions of mainstream members of the art community and press globally. 
- Positive feedback from the Press and art community, including how the Institute is using web3 and increased awareness of Filecoin and IPFS.
- This will be a strong signal to other institutions to do the same. 

## Outcomes

- 1 LACMA NFT collection made of artworks/objects/associated data (i.e., certificates of authenticity) that are minted as NFT collections with off-chain NFT data made available across IPFS and stored decentrally in NFT.Storage Filecoin deals.
- Joint press release between NFT.Storage, the institutions and our development partner, ThirdWeb

## Adoption, Reach, and Growth Strategies

We believe that other art institutions will follow LACMA’s lead to mint their first NFT archive collections. 

We will try to get picked up on well-known web3 podcasts such as Bankless.

## Development Roadmap

- The goal is to launch the NFT collection in December.
- Now: LACMA is curating the collection
- Next: Design and develop NFT collection
- After that: Mint NFT Collection 
- And in parallel: Press about the Collection

## Total Budget Requested
$50,000

| Milestone # | Description | Deliverables | Completion Date | Funding |
|1. Secure LACMA partnerships|Get 100% confirmation from LACMA on moving forward with the project|Written agreement to partner on all of the above|TBD. Our goal is Oct 2023|20%|
|2.Timeline for each partnership|Create and get commitment from both institutions on timeline|Timeline|Timeline|20%|
|3.Collection design|Collections have been designed and are ready to mint|Collection name, collection description, NFT names, NFT files, NFT metadata, blockchain selection, hot storage selection, NFT type, mint price, collection size|4 weeks after milestone 1|20%|
|4.Collection mint launch|Begin minting the NFTs|NFTs available to mint|8 weeks after milestone 3|20%|
|5.Press release|Press release describing the initiative|Press release|Within 1 week of milestone 4|20%|

## Maintenance and Upgrade Plans

NA

# Team

## Team Members

Elizabeth Griffiths - Product Manager, NFT.Storage
Jesse Damiani  - Arts & Culture Advisor, Protocol Labs
ThirdWeb - Project management, NFT Collection + Minting best practice and development of the collection
Jenks Gou - Developer Advocate, Filecoin

## Team Member LinkedIn Profiles

Elizabeth Griffiths - https://www.linkedin.com/in/elizabethagriffiths/
Jesse Damiani - https://www.linkedin.com/in/jessedamiani/
https://www.linkedin.com/company/third-web/
Jenks Gou - https://www.linkedin.com/in/jenks-guo-58257438/

## Team Website
https://thirdweb.com/

## Relevant Experience

Elizabeth Griffiths - Deep experience in NFTs and storage for off-chain NFT data
Jesse Damiani - Deep experience working with art institutions and Filecoin produts
ThirdWeb - Deep experience guiding enterprise companies and non-profit organizations to mint successful NFT collections
Jenks Gou - Deep experience guiding NFT builders to store off-chain data across IPFS and in Filecoin

## Team code repositories

https://portal.thirdweb.com/

# Additional Information
elizabeth.griffiths@protocol.ai

**Comment by ErinOCon** [comment]
Hi @elizabeth-griffiths, thank you for your proposal! Unfortunately, we will not be proceeding with a grant at this time. Wishing you the best as you continue to build!

**Comment by elizabeth-griffiths** [comment]
@ErinOCon  what's the best way to understand the rationale for the decision?

**Comment by ErinOCon** [comment]
Hello @elizabeth-griffiths! Thank you for your question. I have provided a response [here](https://github.com/filecoin-project/devgrants/issues/1652).
