### ISSUE TITLE
NFT.Storage: Art & Cultural Institution Archives Use IPFS and Filecoin 

### ISSUE THREAD

**Issue by elizabeth-griffiths** [filecoin-project/devgrants#1652]
# Open Grant Proposal: NFT.Storage: Art & Cultural Institution Archives Use IPFS and Filecoin 

**Project Name:**
NFT.Storage: Art & Cultural Institution Archives Use IPFS and Filecoin 

**Proposal Category:**  `Applications`

**Individual or Entity Name:** Is the proposal on behalf of an individual, or an entity/organization? Please note that the agreement and any payments must be completed by the same entity, either individual or organization.
NFT.Storage

**Proposer:** `replace with your GitHub username`

(Optional) Filecoin ecosystem affiliations:
NFT.Storage is a part of Protocol Labs

(Optional) Technical Sponsor: `

Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?: Yes, for all relevant work

# Project Summary
This project focuses on getting art and cultural institutions to use IPFS and Filecoin for digitizing their archives.
We’ll do this through our personal connections with top-tier institutions, and using their influence and our educational pieces to bring awareness and convert the long tail.

The educational materials we’ll create are a blog post and a playbook.

## Impact 

We are going to increase consideration and adoption amongst art and cultural institutions to use IPFS and Filecoin for digitizing their archives. We’ll influence them to do this by educating them on the why and how using our learnings from LACMA’s first NFT Archive Collection (pending that grant application being approved).

We already have one very well-known art institute interested in converting their physical archive to a public NFT archive—name to be disclosed at a later date. We will secure additional partnerships throughout the project.

We believe that our 1-1 outreach and educational resources and the momentum of LACMA minting their first NFT Archive Collection will be a strong signal to other institutions to do the same. Art Institutes will be more willing to try using our playbook for their archives.

## Outcomes

Educational blog about on why institutions should store archives digitally and decentrally as NFTs in decentralized storage
NFT.Storage will develop a decentralized playbook that coaches Art Institutes and Cultural Organizations on how to convert their physical archive to a public NFT archive, with their off-chain NFT data made available across IPFS and stored on Filecoin. 
Pipeline of at least 3 art institutes who commit to mint their first NFT Archive Collection

## Adoption, Reach, and Growth Strategies

- We already have a small pipeline of Art Institutes who are interested in minting their first NFT Archive Collection. We will continue to meet with them 1-1 to influence them to fully commit and begin the process.
- We will be able to reach additional Institutes to use the completed playbook through our existing relationships with many of the top institutes. Other smaller Institutes will learn about the initiative through press and word of mouth.
- We believe that LACMA’s first NFT archive collection will influence others to do the same, but they will not know how without a resource that teaches them how to. The resource will be our playbook and our 1-1 relationships
- The blog post will be a great educational resource to share with the institutions early.

## Development Roadmap

Now: 
- Nurture existing relationships and influence them to commit.
- Write blog post on why institutions should store archives digitally and decentrally as NFTs in decentralized storage

 Next: 
- Begin writing playbook
- Continue to nurture existing relationships and influence them to commit. Establish new relationships as needed.

After that: 
- Complete playbook
- At least 3 more institutions have committed to minting their first NFT Archive Collection and using IPFS and Filecoin

## Total Budget Requested
$50,000

We are requesting $50,000 to fund the following:
| Milestone # | Description | Deliverables | Completion Date | Funding |
|1. Publish blog post	|Blog post on why institutions should store archives digitally and decentrally as NFTs in decentralized storage|1 blog post|30 Oct|20%|
|2. 3 institutions in consideration phase|Get 3 institutions (not including LACMA) to consider minting their first NFT Archive Collection|Strategy to convert each to committed|TBD. Our goal is Nov 2023|20%|
|3.Playbook |Playbook targeted to art institutions describing how to mint collections from their archive|Playbook|TBD - 2 weeks after LACMA launch|60%|

## Maintenance and Upgrade Plans
NA

# Team

## Team Members

Elizabeth Griffiths - Product Manager, NFT.Storage
Jesse Damiani - Arts & Culture Advisor, Protocol Labs
Jenks Gou - Developer Advocate, Filecoin

## Team Member LinkedIn Profiles

Elizabeth Griffiths - https://www.linkedin.com/in/elizabethagriffiths/
Jesse Damiani - https://www.linkedin.com/in/jessedamiani/
Jenks Gou - https://www.linkedin.com/in/jenks-guo-58257438/

## Relevant Experience

Elizabeth Griffiths - Deep experience in NFTs and storage for off-chain NFT data
Jesse Damiani - Deep experience working with art institutions and Filecoin products
Jenks Gou - Deep experience guiding NFT builders to store off-chain data across IPFS and in Filecoin

## Team code repositories

# Additional Information

**Comment by ErinOCon** [comment]
Hi @elizabeth-griffiths, thank you for your proposal and for your patience with our review. Unfortunately, we will not be proceeding with a grant at this time. Wishing you all the best as you continue to build!

**Comment by elizabeth-griffiths** [comment]
@ErinOCon what's the best way to understand the rationale for the decision?

**Comment by ErinOCon** [comment]
Hi @elizabeth-griffiths, this was an interesting project proposal and was considered as a grant candidate. Unfortunately, due to a shift in funding priorities in the current climate, this project did not advance to the final approval round. 

We will be sharing updates to our program focus and criteria in the coming weeks. In the meantime, please feel welcome to contact us at grants@fil.org with any questions.

**Comment by elizabeth-griffiths** [comment]
Thanks @ErinOCon ! Are you able to provide any feedback on what we could do to strengthen both proposals and re-submit?

**Comment by ErinOCon** [comment]
Hello @elizabeth-griffiths, I have provided a response in Slack.
