### ISSUE TITLE
Decentralized ABI Indexer (DABI)

### ISSUE THREAD

**Issue by AjiteshBD** [filecoin-project/devgrants#1653]
# Open Grant Proposal: Decentralized ABI Indexer (DABI)

**Project Name:** Decentralized ABI Indexer (DABI)

**Proposal Category:** Developer and Data Tooling

**Individual or Entity Name:** Cryptoineer

**Proposer:** AjiteshBD

**(Optional) Filecoin ecosystem affiliations:** Skillset

**(Optional) Technical Sponsor:** [If applicable, include the name and/or GitHub handle of a technical sponsor]

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

The Decentralized ABI Indexer (DABI) project aims to provide a user-friendly, decentralized solution for managing contract ABIs, versions, and chain-specific information within the Ethereum and EVM-compatible blockchain ecosystem. DABI will leverage Ceramic and IPFS for secure and tamper-proof data storage, simplifying contract interaction, enhancing security, and promoting cross-chain compatibility.

## Impact

DABI seeks to address several pain points within the blockchain development community, including the lack of standardized, decentralized ABI indexing tools and the risks associated with interacting with malicious contracts. By providing a decentralized, user-friendly, and cross-chain compatible solution, DABI aims to enhance the development experience and foster trust in the blockchain ecosystem.

The success of DABI will result in a more efficient and secure development process for Ethereum and EVM-compatible blockchain developers. It will also contribute to the broader blockchain ecosystem's growth by providing a valuable tool for contract management and interaction.

## Outcomes

The key outcomes and deliverables of the DABI project include:
- Integration of Ceramic and IPFS for decentralized contract ABI storage.
- Development of a user-friendly SDK for contract interaction.
- Implementation of a contract verification mechanism within the SDK.
- Support for multiple EVM-compatible blockchains for cross-chain compatibility.
- Educational initiatives and workshops to engage and onboard users.

Success metrics will include user adoption rates, the number of contracts indexed, community engagement, and the level of trust and security provided by DABI.

## Adoption, Reach, and Growth Strategies

The target audience for DABI includes Ethereum and EVM-compatible blockchain developers. We aim to engage with this audience through community-driven initiatives, educational programs, and by offering a user-friendly SDK. Our goal is to onboard an initial user base and expand our reach through partnerships, workshops, and collaboration with blockchain organizations.

# Development Roadmap

## Milestone 1: Ceramic and IPFS Integration (3 months)
- Integration of Ceramic and IPFS.
- Basic smart contract for registration.
- Budget: $10,000

## Milestone 2: SDK Development and Documentation (3 months)
- Initial SDK development.
- Preliminary documentation.
- Budget: $10,000

## Milestone 3: Verification Mechanism and Testing (3 months)
- Implementation of contract verification within the SDK.
- Initial testing and bug fixing.
- Budget: $10,000

## Milestone 4: SDK Development and Community Engagement (4 months)
- Feature-rich SDK development.
- Early UI prototype.
- Educational initiatives and user feedback gathering.
- Budget: $25,000

## Milestone 5: Cross-Chain Compatibility and Finalization (3 months)
- Cross-chain compatibility features.
- Enhanced security measures.
- Official DABI launch.
- Budget: $15,000

# Total Budget Requested

| Milestone # | Description | Deliverables | Completion Date | Funding |
|-------------|-------------|--------------|-----------------|---------|
| 1           | Ceramic and IPFS Integration | Functional Ceramic and IPFS integration, basic registration smart contract | [Completion Date] | $5,000 |
| 2           | SDK Development and Documentation | Early SDK prototype, initial documentation | [Completion Date] | $10,000 |
| 3           | Verification Mechanism and Testing | Functional verification mechanism, initial testing | [Completion Date] | $10,000 |
| 4           | SDK Development and Community Engagement | Feature-rich SDK, early UI prototype, educational initiatives | [Completion Date] | $25,000 |
| 5           | Cross-Chain Compatibility and Finalization | Cross-chain support, enhanced security, official DABI launch | [Completion Date] | $15,000 |

# Maintenance and Upgrade Plans

We plan to maintain DABI by actively engaging with the community, addressing user feedback, and continuously improving the platform. Our long-term sustainability will be supported by community contributions, optional premium features, and potential partnerships within the blockchain ecosystem.

# Team

## Team Members

- [Ajitesh Mishra]

## Team Member LinkedIn Profiles

- https://www.linkedin.com/in/cryptoineer/

## Team Website

https://ajiteshmishra.com

## Relevant Experience

Our team has extensive experience in blockchain development, decentralized systems, and open-source projects. We believe our collective expertise positions us well to deliver the DABI project successfully and make a valuable contribution to the blockchain community.

## Team code repositories

Github Link: https://github.com/AjiteshBD

Contracts Address

ERC20 Token Contracts 
https://etherscan.io/address/0xd1420af453fd7bf940573431d416cace7ff8280c
https://etherscan.io/address/0x6731827Cb6879a2091ce3ab3423f7bf20539b579
ERC721
https://etherscan.io/address/0x11EBce0e3a9C30abAEaa8dD4aBabC1A9d93dE688
https://etherscan.io/address/0x198D2b8EA1c60DB49Eaed720D890e7c7c0651f02

Marketplace Contract
https://etherscan.io/address/0xd5a46B999E5731f683D41883F237af5269DB545b

CollectionFactory to Create new ERC721 
https://etherscan.io/address/0x76a95edc242Ea1b239666E2395335df94cE65FBF

Staking Contract
https://etherscan.io/address/0x9f5360fC99746626D5D14E8CB4D2Dd19EF4Bb4c5

Uniswap LP Staking
https://etherscan.io/address/0xFB076e034198511505574DEf0b399bE5309Ace55

Airdrop
https://etherscan.io/address/0x2bF7673873F663903e5d576C5781fB2413a83b68#code

# Additional Information

We discovered the Open Grants Programme thanks to a recommendation from Ethereum.org. Our Decentralised ABI Indexer (DABI) project was recognized by Ethereum.org, and it was suggested that it could be a better fit for Filecoin's grant program: grants.filecoin.io. We appreciate Ethereum.org's suggestion and are pleased to explore the potential available within the Filecoin ecosystem to help us build and support our project.

For grant agreement discussions and general next steps, you can reach us at ajiteshm@outlook.com.

**Comment by ErinOCon** [comment]
Hi @AjiteshBD, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue to build!
