### ISSUE TITLE
PLEARN(PLAY.LEARN.EARN)

### ISSUE THREAD

**Issue by CryptoStein** [filecoin-project/devgrants#1654]
# Open Grant Proposal: `PLEARN (PLAY.LEARN.EARN)`

**Project Name:** PLEARN

**Proposal Category:** Applications

**Individual or Entity Name:** CryptoStein

**Proposer:** CryptoStein

<img width="1440" alt="Screenshot 2023-04-25 at 18 22 18" src="https://github.com/filecoin-project/devgrants/assets/107268440/1a10504c-49c4-4066-807f-e8a5b56ec25c">

_________________________________________________________________

**(Optional) Filecoin ecosystem affiliations:** N/A

**(Optional) Technical Sponsor:** N/A

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

PLEARN (PLAY.LEARN.EARN) is a groundbreaking project aiming to combine blockchain technology with gamification to revolutionize online learning. We address the pressing need for engaging, interactive educational platforms in the Filecoin and IPFS ecosystems. Our project will enhance user adoption, knowledge sharing, and growth within these communities.

## Impact

PLEARN tackles the challenge of creating a seamless, educational gaming experience, eliminating pain points in traditional learning methods. The benefits include increased user engagement, improved knowledge retention, and a more vibrant ecosystem. Failure to innovate in this space risks stagnation and decreased community engagement.

## Outcomes

Our project will deliver a fully functional educational game platform with blockchain integration, offering users a dynamic learning environment. Success metrics include user engagement rates, the number of active participants, and positive feedback from the community.

## Adoption, Reach, and Growth Strategies

Our target audience includes Filecoin and IPFS enthusiasts, developers, and learners. We plan to engage this audience through community partnerships, social media marketing, and educational content creation.

## Total Budget Requested

We have multiple milestones and  the below " Game Design and Development" is one of them and we are listing the sub milestones.

| Milestone # | Description | Deliverables | Completion Date | Funding |
| --- | --- | --- | --- | --- |
| 1 | Game design and concept development | Playable prototype | November 2023 | $4,000 |
| 2 | User interface and user experience design | Beta version with enhanced features | December 2024 | $5,000 |
| 3 | Gameplay mechanics and rules implementation | Alpha version with blockchain integration | January 2023 | $5,000 |
| 4 | Full version with advanced blockchain functionality I - Property trading system and virtual land development | Full version with advanced blockchain functionality, Smart contract development and blockchain integration, In-game currency management and transactions (token engineering), Securing ownership and digital asset management  | February - May 2024 | $20,000 |

## Maintenance and Upgrade Plans

We plan to allocate a portion of the funding for long-term maintenance, bug fixes, and future feature development. We are committed to ensuring the sustainability and growth of PLEARN.

# Team

## Team Members

- Nada Jabr, CEO
- Beshoy Shehata, CBO
- Rawan Mohsen, Product Owner
- Paolino Pagliuso, Marketing Manager
- Ujjwal Sachdeva, Game developer
- Sanskar Tyagi, Front-end developer

## Team Member LinkedIn Profiles

- https://www.linkedin.com/in/nada-jabr-15838b39/
- https://www.linkedin.com/in/beshoy/
- https://www.linkedin.com/in/rawan-mohsen-74563718b/
- https://www.linkedin.com/in/paolino-pagliuso/
- https://www.linkedin.com/in/ujjwal-sachdeva-5064651b4/
- https://www.linkedin.com/in/sanskar-tyagi-953a921b1/

## Team Website

https://plearngame.netlify.app/

## Relevant Experience

Our team brings a wealth of experience in game development, blockchain technology, and user experience design. We are confident in our ability to deliver a successful project.

## Team Code Repositories and game presentation

- https://github.com/CryptoStein-PLEARN/PLEARN
- https://youtu.be/sJTotf4UCNw

## Achievements:
- Have been selected by Lazio Region/Italy acceleration program
- Participated in Nights & Weekends- BuildSpace
  

## Future Plans

Please include the team's long-term project plans, operation plans and intentions:
- Expanding our virtual board game to multiple blockchains for broader accessibility.
- Launching regular content updates and new missions to keep players engaged.
- Exploring NFT integrations and unique tokenomics for in-game assets.
- Partnering with other projects and dApps to create a vibrant metaverse.
- Building a strong player community and hosting events.
- Exploring opportunities for virtual reality (VR) and augmented reality (AR) adaptations.
- Establishing sustainable revenue streams to support ongoing development.
- Collaborating with blockchain communities and platforms to drive adoption.
- Conducting research and development to enhance gameplay and user experience.
- Continuing to explore fundraising options to fuel our growth and development.

**Comment by ErinOCon** [comment]
Hi @CryptoStein, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you all the best as you continue building!
