### ISSUE TITLE
Open Grant Proposal: NuLink Network

### ISSUE THREAD

**Issue by Evan2375** [filecoin-project/devgrants#1655]
# Open Grant Proposal: NuLink Network

**Project Name:** NuLink

**Proposal Category:** Developer and data tooling

**Individual or Entity Name:** NULINK NETWORK FOUNDATION LTD.

**Proposer:** Evan2375

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

## Project Summary

NuLink - The Next Generation Privacy-Preserving Infrastructure
uLink is a privacy-preserving technology for decentralized applications that combines best practices with best-of-breed security solutions to provide enterprise-level security. We propose to construct a secure file storage and sharing decentralized application (Dapp) that empowers users with complete control over their files. Within this framework, files are encrypted locally using the user's private key and subsequently stored on the Filecoin Web3 storage network. Access to these files is strictly controlled by the owner, requiring users to submit requests to the file owner for approval. Once permission is granted, files can be decrypted using the requestor's private key. To ensure this secure data sharing, NuLink leverages a technology known as Proxy Re-encryption (PRE).

- Website: [NuLink Official Website](https://www.nulink.org)

## Impact

NuLink aims to protect data security by encrypting user data before it is stored in the IPFS ecosystem. By employing end-to-end encryption, NuLink enhances the security of data stored in distributed storage systems. 

By leveraging NuLink's privacy protection technology, businesses and individuals can ensure the security of their sensitive data. It provides a convenient and secure way to share important data or files without the risk of potential breaches. 

The maturity of data encryption and privacy protection technologies contributes to the overall security of the ecosystem. It reduces the likelihood of data leaks and represents a significant advancement. This progress silently supports the development of the data-driven era.

## Outcomes

| **Outcome**                           | **Specification**                                                                                                                                                                              |
| ------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 1. Secure File Store and Sharing Dapp | - User Authentication: Users can create accounts and log in securely.                                                                                                                          |
|                                       | - File Encryption: Users can encrypt their files before uploading them to the platform.                                                                                                        |
|                                       | - File Decryption: Users can decrypt files they have access to.                                                                                                                                |
|                                       | - File Upload: Users can upload files to their secure storage area.                                                                                                                            |
|                                       | - File Download: Users can download their own files and files shared with them.                                                                                                                |
|                                       | - Request Encrypted Files: Users can request access to encrypted files from other users.                                                                                                       |
|                                       | - Access Control: Users can grant or revoke access to their encrypted files for other users.                                                                                                   |
| 2. NuLink Agent                       | - File Encryption: The agent can be used to encrypt files on a user's device.                                                                                                                  |
|                                       | - Access Control Management: Users can define and manage access controls for their files using the agent.                                                                                      |
|                                       | - Integration with Dapp: The agent will seamlessly integrate with the Secure File Store and Sharing Dapp.                                                                                      |
| 3. NuLink Agent SDK                   | - A software development kit for developers to build applications that leverage the NuLink Agent's functionality.                                                                              |
| 4. Documentation and Tutorials        | - Comprehensive documentation and tutorials for the Secure File Store and Sharing Dapp and the NuLink Agent. Including user guides, developer documentation, and tutorials on effective usage. |

| **Metrics for Success**         | **Description**                                                         |
| ------------------------------- | ----------------------------------------------------------------------- |
| User Adoption                   | Measure the number of registered and active Dapp users.                 |
| File Uploads and Downloads      | Track the number of files uploaded and downloaded.                      |
| Integration Success             | Ensure smooth Dapp integration with the NuLink Agent and monitor usage. |
| SDK Usage                       | Monitor developer adoption and project usage of the SDK.                |
| Documentation Access            | Track documentation access frequency.                                   |
| Tutorial Completion             | Measure the completion rate of tutorials.                               |
| User and Developer Satisfaction | Gather feedback on documentation and tutorial quality and usefulness.   |

## Adoption, Reach, and Growth Strategies

Our target audience includes all users who have data storage and usage needs. Our data encryption protection services are not limited to businesses and individuals. We have engaged with users through various channels such as social media, industry recommendations, and offline events. We have already established partnerships with several enterprises. 

Moving forward, we will continue to actively promote our services. We will proactively collaborate with major public chains to deploy and support their ecosystems. Currently, we have completed testing network deployments for BNB Chain and Conflux and plan to support more in the future.

## Development Roadmap

| **Milestone**                                      | **Functionality**                                                                                                                                                                                       | **Team**                                                                                                                              | **Time Period** |
| -------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------- | --------------- |
| 1. NuLink Agent Integration                        | - Integrate the NuLink Agent with the Dapp, enabling file encryption on users' devices and access control management.                                                                                   | - Developers: 1 front-end, 1 back-end                                                                                                 | 4 weeks         |
| 2. SDK and Documentation                           | - Develop the NuLink Agent SDK, including documentation and code examples.                                                                                                                              | - SDK Development: 2 developers                                                                                                       | 3 weeks         |
| 3. Secure File Store and Sharing Dapp Prototype    | - Develop a functional prototype of the Secure File Store and Sharing Dapp with basic user authentication, file upload/download, and encryption/decryption features.                                    | - Developers: 1 front-end, 1 back-end                                                                                                 | 4 weeks         |
| 4. User Testing and Feedback + Final Documentation | - Conduct user testing for the Dapp and SDK, gather feedback from both users and developers. - Make necessary improvements and refinements based on feedback. - Finalize and publish the documentation. | - User Testing: 1 UX researcher - Development Team: Developers for implementing improvements - Documentation Team: 1 technical writer | 1 week          |

## Total Budget Requested

| Milestone # | Description                                     | Deliverables                                                                                      | Completion Date | Funding |
| ----------- | ----------------------------------------------- | ------------------------------------------------------------------------------------------------- | --------------- | ------- |
| 1           | NuLink Agent Integration                        | - NuLink Agent integrated with the Dapp for file encryption and access control management         | 4 weeks         | $10,000 |
| 2           | SDK and Documentation                           | - NuLink Agent SDK with documentation and code examples                                           | 3 weeks         | $7,500  |
| 3           | Secure File Store and Sharing Dapp Prototype    | - Functional Dapp prototype with user authentication, file upload/download, encryption/decryption | 4 weeks         | $10,000 |
| 4           | User Testing and Feedback + Final Documentation | - User testing and feedback gathered, improvements made - Final documentation published           | 1 week          | $2,500  |

## Maintenance and Upgrade Plans

We have long-term maintenance and upgrade plans in place to ensure the continuous operation and improvement of the project over time. Here are the steps we will take to achieve this:

- Regular Maintenance: We will perform regular system maintenance and updates to address any potential vulnerabilities or issues, ensuring the stability and security of the project.

- User Feedback and Requirements: We highly value user feedback and requirements. We will actively gather user opinions and suggestions, making improvements and optimizations based on user needs.

- Technological Upgrades: As technology continues to evolve, we will closely monitor the latest trends and advancements in the industry. We will continuously evaluate and adopt new technologies and tools to enhance the performance and functionality of the project.

- Security and Privacy Protection: Data security and privacy protection are our top priorities. We will continuously strengthen security measures for the project and comply with relevant privacy regulations and best practices.

Through these long-term plans, we are committed to providing users with a stable, secure, and continuously improving project experience.

# Team

## Team Members

- David Jiao
- Daniel Nilsson
- Pawn

## Team Member LinkedIn Profiles

- [LinkedIn - Yin Jiao](https://www.linkedin.com/in/yinjiao/)
- [LinkedIn - Daniel Nilsson](https://www.linkedin.com/in/danielnilssonsweden/)

## Team Website

- [NuLink Team Website](https://www.nulink.org/about-us#investors)

## Relevant Experience

Our team members have a wealth of experience in leading teams, scaling startups, and, most importantly, building great products. We're proud to have such a dedicated and talented group of individuals working together towards our mission of making data security accessible to all. But we're not just supported by a great team - we're also excited to share that NuLink is part of Season 4 of Binance's Incubation Program, which means we get guidance from some of the greatest minds in the industry.

## Team code repositories

[GitHub - NuLink Network](https://github.com/NuLink-network)

**Comment by ErinOCon** [comment]
HI @Evan2375, thank you for your proposal and for your patience with our review. Unfortunately, we will not be proceeding with a grant at this time. Wishing you the best as you continue to build!
