### ISSUE TITLE
Next Step Microgrant: SellPal - p2p platform for selling digital goods and services

### ISSUE THREAD

**Issue by sellmon** [filecoin-project/devgrants#1656]
# SellPal - sell digital goods via crypto

## 1. What is your project, and what problem does it solve?
SellPal is a peer-to-peer platform for selling and delivering digital goods and services. 

We address issues related to the diversity of financial services and banking restrictions in different regions. 
We are creating an independent global platform where people can transact and sell their digital goods without geographical limitations, financial barriers, and banks. We offer minimal fees and the reliability of smart contracts. 

SellPal is the path to free and secure financial transactions, transcending borders and limitations.

## 2. Project Links

- [GitHub Repository](https://github.com/sellmon)
  - *Note: My repository with the project is currently private. If you are interested in this idea, I will grant you access and make everything public as needed.*
- [Website](https://sellpal.xyz)
- License: MIT

### Additional Project Links

- [Example of real Product on Platform](https://sellpal.xyz/s/476)
  - *This product was sold to a real buyer who transferred the funds, froze them (as some questions arose), then unfroze them, and as the seller, I withdrew them to my wallet, with the platform receiving a commission.*
- [Beta Version of Smart Contract Factory and Smart Contract](https://explorer.zksync.io/address/0xDc4E0c4759a775cD2bc47dc25fF98b94FdeA71d0#contract)

### a) Technical Stack
My current tech stack includes React, Typescript, and I use Supabase for data storage. For smart contracts, I utilize ZkSync. I plan to integrate Polygon, Optimism, and other blockchains in the future to allow users to choose and pay with various cryptocurrencies.

Currently, I use Supabase as a database for storing files and content, but I would like to move away from it and create a fully decentralized solution. This is where the grant could help.

**At this stage, the application is fully functional as MVP.**

As a future development concept, I envision the ability to create various interaction scenarios between sellers and buyers. This includes adding functionality for recurring payments and subscriptions to specific content, selling specialized content (for example, data that is sold not in its entirety but in the volume specified by the buyer), and more.

I also see potential in semi-automated dispute resolution using AI.

### b) Focus Area
This project aligns with the current microgrants focus area (FVM).

### Grant Deliverables
We have identified several key deliverables for the project, aimed at enhancing its functionality and user experience:

| Number | Grant Deliverable                      | Description                                               | Timeframe (within 3 months) |
| :---   | :-----------------------------------   | :-------------------------------------------------------- | :-------------------------- |
| 1.     | Integration of Filecoin and Smart Contract Upgrades | Transition the website from a centralized database to a decentralized one. | 1 month |
| 2.     | Testing and Code Optimization            | Perform comprehensive testing of transactions, file uploads, and system components, followed by code optimization. | 2 weeks |

## 5. Monthly Updates

If our grant application is accepted, we commit to providing monthly project updates in this GitHub issue for 3 months or until the described project objectives are met.

## 6. Does your proposal comply with our Community Code of Conduct?

Yes, my proposal complies with the Filecoin Code of Conduct.

## 7. Links and Submissions

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: No

### Additional Questions

* For each team member(s), please list name, email, GitHub account, and role in the project.
  * - Vlad, [sgdk4an@sellpal.xyz](mailto:sgdk4an@sellpal.xyz), [github.com/sellmon](https://github.com/sellmon), Founder
* How did you learn about our microgrant program?
  * - I found it through a search.

**Comment by sellmon** [comment]
Fell free to ask me any question.
If someone want to participate in the project, you're welcome, let's talk.

**Comment by psyarcushub** [comment]
Hello, sellmon! I'm glad to see developers joining the ecosystem who share a similar mindset to us at FileMarket. You might find it interesting to explore our experience, as we've implemented a similar concept.

Check this out:
[Link1](https://github.com/filecoin-project/devgrants/issues/1288)

Then:
[Link2](https://medium.com/filemarket-xyz/how-to-attach-an-encrypted-file-to-your-nft-7d6232fd6d34)

**Comment by sellmon** [comment]
Hello @psyarcushub ! I didn't see your message.

It looks good. I was searching for similar solutions in the crypto space, but I didn't come across yours.

Yes, I figured it out without any issues and created a product page: https://filemarket.xyz/collection/ZkSync/0xEc8b32B53Af5075b6c05eB270637a84F1E94E066/220

Everything went well.

I also sell digital products, so I have some questions/recommendations moving forward. I'm curious to hear your opinion:

How do you ensure that what's purchased is exactly as described? In my smart contract, I've included provisions to address fraud because I've had experience with it. Buyers can purchase the item, and the funds will be held in escrow. They have a specified time to verify the item and freeze the funds. If the buyer is a scammer, we can then refund the funds.

**Comment by psyarcushub** [comment]
Thanks for the answer, @sellmon !

Thank you for showing interest in our product and for conducting the tests. I'm very grateful for that! It would be interesting to discuss a variety of issues related to the products we create.

One of the topics, among others, is resolving disputes when the customer is dissatisfied with the product. We considered the option where calling a moderator is a paid service. Implementing this in the contract would not be difficult. 

How about exchanging contacts to connect on some messenger?

**Comment by sellmon** [comment]
No problem @psyarcushub, my tg: @sgdk4an

**Comment by psyarcushub** [comment]
> @sgdk4an

And what is your Telegram handle now?

**Comment by sellmon** [comment]
@psyarcushub 😊 I changed to @flexyfleix

**Comment by ErinOCon** [comment]
HI @sellmon, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant at this time. Please feel welcome to contact our team at [grants@fil.org](mailto:grants@fil.org) with any questions. 

Wishing you the best as you continue to build!
