### ISSUE TITLE
Next Step Microgrant: PIC3

### ISSUE THREAD

**Issue by qq919006380** [filecoin-project/devgrants#1660]
### 1. What is your project, and what problem does it solve? (max 100 words)
A Web3 image hosting platform is a tool built on Web3 technologies that addresses the following issues compared to traditional image hosting solutions:

- Decentralized Storage: Web3 image hosting utilizes decentralized storage, eliminating reliance on a single central server and enhancing data reliability.
- Data Security: Through encryption and distributed storage techniques, Web3 image hosting enhances the security of image data and reduces the risk of unauthorized usage.
- Preventing Link Breakage: Web3 image hosting employs content addressing to ensure the persistence of image links, even if service providers become unavailable.
- Data Ownership: By utilizing blockchain technology to record image metadata, it ensures data authenticity and ownership, allowing users to have better control over their data.
- No Need to Trust Third Parties: Web3 image hosting is not dependent on a single centralized service provider, reducing the need to place complete trust in any entity to safeguard data.

Web3 image hosting provides a more secure, reliable, and decentralized image hosting solution suitable for distributed applications and users, particularly emphasizing data privacy and ownership protection.

### 2. Project links

[github](https://github.com/qq919006380/Pic3)
[website](https://pic3.vercel.app/)
[MIT](https://github.com/qq919006380/Pic3/blob/main/LICENSE)

### 3. a) How is IPFS, Filecoin, or related technology used in this project?

1. upload content via IPFS connector tools like nft.storage to obtain a CID.
2. The CID is then transformed into encrypted code using a compression encryption algorithm.
3. This encrypted code is uploaded to the blockchain via a contract.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective?

| Number | Grant Deliverable                                                                 | Briefly describe how you will meet deliverable objectives                                               | Timeframe (within 3 months) |
| :----- | :-------------------------------------------------------------------------------- | :------------------------------------------------------------------------------------------------------ | :-------------------------- |
| 1.     | Enhance UI with seamless user experience, including smooth transition animations. | Improve the user interface for a perfect human-computer interaction and seamless transition animations. | One month                   |
| 2.     | Optimize smart contract and encryption algorithms.                                | Refine the smart contract and encryption algorithms.                                                    | One month                   |
| 3.     | Launch and promote the platform, create IPFS and Filecoin documentation.          | Start operations and promotional efforts, and create documentation for IPFS and Filecoin integration.   | One month                   |
| 4.     |                                                                                   |                                                                                                         |                             |

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

yes

### 6. Does your proposal comply with our Community Code of Conduct?

yes

Name:bitSum
Email:919006380@qq.com
GitHub:[github](https://github.com/qq919006380)
Role: Full Stack Developer

**Comment by ErinOCon** [comment]
Hi @qq919006380, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant for this project. Please feel welcome to contact our team at [grants@fil.org](mailto:grants@fil.org) with any questions.

Wishing you the best as you continue to build!
