### ISSUE TITLE
Next Step Microgrant: Obsidian-Desci

### ISSUE THREAD

**Issue by polus-arcticus** [filecoin-project/devgrants#1661]
### 1. What is your project, and what problem does it solve? (max 100 words)
The Decentralized Science ecosystem has a great deal of impactful projects that could use a simpler UI/UX for use and composition by non prgramming native scientists.  Obsidian.md is a popular note taking software for intellectuals,  Obsidian-Desci offers a series of integrations into  obsidian to hide web3 inside of it to use the decentralized science legos together.  Users can pull from IPFS, run edge compute jobs, mint hypercerts, interact with desci.nodes, and much more

### 2. Project links
  
Link to Github repo: https://github.com/Obsidian-Desci
was https://github.com/polus-arcticus/obsidian-lilypad 
Link to demo or website: https://obsidian-desci.github.io/Docs/
License: GNU

### 3. a) How is IPFS, Filecoin, or related technology used in this project?
Libp2p for multiplayer, IPFS crud, push content into filecoin through lighthouse, execute storage deals on fevm, hit lilypad to perform edge compute.  This is an integrations and compositions project for the decentralized science techstack, by definition the process is hitting all the most economically relevant integrations and make a sum is greater than parts through composition.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes but it is not exclusive to FVM, though its a major part
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
Retreive content from filecoin with saturn, build in the labdao protein folding workflow which touches bacalhau, creating a lilypad worker for kamu.dev for stream processing, add support for POAPS, ip nfts, and a higher degree support for desci nodes dpid structure
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |   Lilypad-Kamu                     |       Work with desci labs and lilypad to deliver kamu functionality in lilypad by operating on research objects                                                     |  prototype won ethonline hackathon file coin prize!                      | 
| 2.     |      Filecoin fetch support through saturn                 |        retreive filecoin content through fastest retreivability workers                                                    |         hopefully only a week                   | 
| 3.     |      Lighthouse storage                   |   push the content of an obsidian vault through lighthouse onto filecoin                                                    |                hopefully only a week            | 
| 4.     |         hypercerts                |          add integration of hypercerts by committing to desci nodes coordinating through fil                                                |                            | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* encode club helia and lilypad bounty winner
* eth new york helia -pubsub-webrtc pool prize
* (hopefully future wins in ethonline, devconnect and ethinstanbul)
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Taylor Hulsmans, thulsmans.1133@gmail.com, https://github.com/polus-arcticus/, conductor
* How did you learn about our microgrant program?
* https://ecosystem-wg.notion.site/Protocol-Labs-Accelerator-Program-d45d8792a7d544eca9beb7d3e3d3b05d
* If your project was created as part of an event or hackathon:

  * Please link to your hackathon submission
  * https://github.com/polus-arcticus/helia-pubsub-webrtc (EthNewyork)
  * https://github.com/polus-arcticus/obsidian-lilypad (encode club filecoin hack)
  * https://github.com/polus-arcticus/lilypad-kamu-filecoin (eth online [currently trying to win])

**Comment by ErinOCon** [comment]
HI @polus-arcticus, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant for this project. Please feel welcome to contact our team at [grants@fil.org](mailto:grants@fil.org) with any questions.

Wishing you the best as you continue to build!
