### ISSUE TITLE
Next Step Microgrant: dStor - Decentralized Cloud Storage moving to the FVM!

### ISSUE THREAD

**Issue by KeatonKirk** [filecoin-project/devgrants#1665]
### 1. What is your project, and what problem does it solve? (max 100 words)

dStor is a fully built and deployed could storage solution using IPFS and Ethereum NFTs to allow for a truly decentralized and trustless cloud storage platform. The tech stack includes: Lit Protocol for decentralized authentication and encryption, IPFS through the chainsafe api for file storage, and Ethereum NFTs for access control. With the maturation of the FVM, it's time to migrate essential services to the FVM and leverage new FVM features! This funding request will fund the initial work to transition dStor the FVM, starting with the implementation of the current access control platform from the EVM to FVM agents.

### 2. Project links
  
Link to Github repo: https://github.com/KeatonKirk/d-stor
Link to demo or website: [d-stor-8b666744cf2c.herokuapp.com/](https://d-stor-8b666744cf2c.herokuapp.com/)
License: Apache 2.0

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

IPFS and the filecoin network form the backbone of dStor, and form the primary method by which users engage with decentralized storage! FVM features will allow dStor to further it's mission of providing trustless cloud storage, and will become a core part of the stack with more funding.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes! This current funding request will be specifically used to integrate FVM functionality with the existing platform, starting with decentralized access control via FVM agents.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

Funding will be used to fund developer time and resources to integrate the FVM in to the existing platform, starting with executing access control on the FVM instead of polygon.  This funding request and deliverables will lay the groundwork for a complete transition to FVM tools, meant to leverage the full suite of FVM capabilities.

| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |  scaffold and test FVM smart contracts  | Using FVM documentation, I will scaffold smart contracts currently executed on Polygon to FVM agents. This phase will include robust testing to retain current levels of security and reliability.  | December 31st  2023                         | 
| 2.     |  Migration and Deployment | After testing and scaffolding of core access control contracts, I will migrate and deploy the FVM agents.   | January 15th 2024                           | 
| 3.     |  Groundwork for additional FVM features | after successful deployment of core access control functionality to FVM, I will begin building on feature branches for FVM features, starting with verifiable proof of storage. Current funding request will allow for the core work of moving access control to be completed | January 18th 2024  | 
| 4.     |  Begin Research on maximizing storage for AI/ML applications                       |  As an ML engineer and AI enthusiast, I am constantly thinking of ways to improve dStor with an eye towards ML applications. Having built neural networks from scratch, I know firsthand the challenges of data storage and pipeline creations. I plan to use the end portion of this work package to form concrete ideas of how to leverage dStore and FVM features for ML builders.                                                          |  January 20th 2024                          | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes! I have received multiple filecion grants in the past and pride myself on timely communication and robust deliverables.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes!

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  - N/A
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
 -> Keaton Kirkpatrick - Lead Developer
 -> keatondkirkpatrick@gmail.com
 -> https://github.com/KeatonKirk
* How did you learn about our microgrant program?
-> I am a previous grant recipient!
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @KeatonKirk, thank you for your proposal and for your patience with our review process. It's great to see this project continue to progress from the proposal submitted originally in 2022. Unfortunately, after much consideration, it has been determined that we will not be be moving forward with a new grant at this time. 

I will be sending you an email shortly to discuss other ways to partner with our community. Wishing you the best as you continue to build!
