### ISSUE TITLE
Copernic Space

### ISSUE THREAD

**Issue by manuelolariu** [filecoin-project/devgrants#1666]
# Open Grant Proposal: `Copernic Space`

**Project Name:**
Copernic Space

**Proposal Category:** Choose one of `Developer and data tooling`, `Applications`, `Integrations`, `Research & protocols`, `Other`. Learn what these categories are here: https://github.com/filecoin-project/devgrants/tree/master/open-grants#readme
We choose the category of Applications, as Copernic Space focuses on developing applications for the space industry.

**Individual or Entity Name:** Is the proposal on behalf of an individual, or an entity/organization? Please note that the agreement and any payments must be completed by the same entity, either individual or organization.
The proposal is on behalf of Copernic Space, an entity/organization.

**Proposer:** `manuelolariu`

**(Optional) Filecoin ecosystem affiliations:** `Please disclose any existing work relationships with organizations in the Protocol Labs Network, including Protocol Labs, Filecoin Foundation, Filecoin Foundation for the Decentralized Web, and any others.` 
/

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`
/

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Please respond with "Yes" or "No".
Yes

# Project Summary

Copernic Space is a blockchain-based platform that aims to democratize access to space assets, data and more. The Copernic Space Platform features a marketplace where space assets, such as satellite imagery or IP, can be minted, listed, and transacted securely and transparently. We utilize advanced blockchain technology to ensure the authenticity and ownership of these digital assets. Our goal is to make space more accessible and beneficial for everyone, from space companies to the wider commercial market, researchers, educators, and even the general public.
We are addressing the need of democratizing real-world space assets and decentralized and secure solutions for the growing volume of space assets and related data in the new space economy. The current centralized storage systems are vulnerable to data breaches, censorship, and single points of failure. Our project aims to leverage the power of IPFS and Filecoin to build on top of our decentralized and resilient marketplace infrastructure.
By integrating with IPFS and Filecoin, we will enable users to store their data and space assets in a distributed network of nodes, ensuring redundancy and fault tolerance on our platform. This will significantly reduce the risk of data loss and increase data availability. Additionally, our project will utilize Filecoin to ensure data integrity and privacy.
We empower individuals and organizations to have full control over their data and space assets, eliminating the need to rely on centralized control. This will foster a more secure and censorship-resistant digital environment, where data ownership and privacy are protected:

## Impact 

The Copernic Space project holds significant value for the Filecoin, IPFS, and related ecosystems. By integrating Filecoin into our platform, we aim to address several pain points in the space industry. One of the key challenges is the secure and efficient storage of space-related data and assets, such as satellite imagery and other valuable information. The decentralized storage capabilities of Filecoin provide a robust solution to this problem, ensuring the integrity and accessibility of data within our ecosystem.
Getting this integration right has several benefits. Firstly, it enhances the commercialization of space assets by providing a secure and reliable storage solution. This encourages more space ventures to participate in the market, leading to increased transactions on the Filecoin network. Additionally, successful integration of Filecoin into our platform opens up new opportunities for financing space ventures, as investors can have confidence in the secure storage of asset-related data.
The risks of not getting this integration right are significant. Without a reliable and secure storage solution, the integrity of space-related data could be compromised, leading to mistrust and potential financial losses for space ventures. Furthermore, the lack of efficient storage options could hinder the growth and adoption of the space economy, limiting its potential impact on various verticals and markets.
The impact of this project extends to the space industry as a whole. Success in integrating Filecoin into our platform would enable asset creators to mint and transact space assets securely, driving increased usage of the Filecoin network. It would also foster the growth of the space economy by attracting more participants and facilitating the financing of space research, ventures and beyond. Ultimately, success would mean a thriving ecosystem where space assets are easily accessible, traded, and utilized, benefiting both the space industry and the broader Filecoin and IPFS ecosystems.

## Outcomes

Our final outcome for this project is to seamlessly integrate Filecoin for the storage and management of space-related data on our Copernic Space marketplace.
Minting and Trading of Space Assets: Users will be able to create and list space assets on our platform, leveraging the decentralized storage capabilities of Filecoin. This functionality will enable asset creators to securely store and manage their space-related data, ensuring its integrity and accessibility.
Compatibility with EVM Networks: Assets on our platform will be created on both EVM compatible networks and Filecoin. This compatibility will allow for seamless interoperability between different blockchain networks, expanding the reach and usability of space assets.
To measure the success of our project, we have defined the following metrics:
Number of Space Assets Minted: We are tracking the number of space assets minted on our platform, indicating the level of adoption and usage by asset creators.
Transaction Volume: We will monitor the transaction volume on our platform, measuring the number and value of transactions conducted using Filecoin. This metric will reflect the level of engagement and financial activity within our ecosystem.

## Adoption, Reach, and Growth Strategies

Our target audience for the Copernic Space platform includes space companies, investors, researchers, and enthusiasts who are interested in participating in the space economy. This audience represents a significant market size, as the space industry continues to grow and attract attention from various sectors.
To engage with our target audience, we have implemented several strategies:
Partnerships with Space Companies: We have established partnerships with premier space companies to execute space asset sales on our marketplace. These partnerships not only provide us with access to a wide range of space assets but also help us reach their existing customer base and engage with potential users.
Marketing and Outreach: We have implemented marketing and outreach campaigns to raise awareness about Copernic Space and its benefits. This includes mission driven initiatives such as Satellite Rhino, targeted advertising, content creation, and participation in industry events and conferences. By actively promoting our platform, we aim to attract the attention of our target audience and encourage them to explore and utilize our services.
User-Friendly Platform: We have designed our platform to be user-friendly and accessible to users with varying levels of technical expertise. This approach ensures that new users can easily onboard themselves onto our platform without facing significant barriers. We provide educational resources and support to guide users through the process of creating and utilizing space assets.
In terms of onboarding new users, we have a phased approach:
We leverage our partnerships with space companies to onboard our users on to the platform and community channels. By showcasing the benefits of our platform and demonstrating successful asset sales, we aim to attract more users who can serve as ambassadors for our platform.
Building on our success, we are expanding our marketing efforts to reach a wider audience. This will include targeted advertising, content creation, and engagement with relevant communities and forums. We will also offer incentives and rewards to early users who refer others to join our platform.
Our goal is to create a network effect, where the initial users attract more users through positive experiences and word-of-mouth recommendations. By continuously improving our platform and delivering value to our users, we aim to achieve widespread adoption and growth within the space industry.

## Development Roadmap

Milestone 1: Filecoin Integration
Functionality: After the completion of this milestone, we expect to have a direct Filecoin integration for the storage and management of space-related assets. Users will be able to mint and sell space assets, with compatibility across EVM networks and seamless integration of Filecoin.
Team and Roles: For this milestone, we will have a team of 3 developers working on the frontend and backend development, a project manager overseeing the progress, and a UX/UI designer ensuring a user-friendly experience.
Funding Required: We estimate that this milestone will require a funding amount of $20000. This will cover the salaries of the development team, project management costs, and any necessary infrastructure expenses.
Timeline: We anticipate that this milestone will take approximately 4 months to complete, starting from 01/2024 and ending on 05/2024.
Milestone 2: Testing and Optimization
Functionality: In this milestone, we will focus on testing the functionality of the integration, identifying and resolving any bugs or issues, and optimizing the performance for a seamless user experience. We will also conduct security audits to ensure the integrity and safety of the platform.
Team and Roles: The same team of developers, project manager, and UX/UI designer from Milestone 1 will continue their roles in this milestone.
Funding Required: We estimate that this milestone will require a funding amount of $15000. This will cover the costs of testing, security audits, and optimization efforts.
Timeline: We anticipate that this milestone will take approximately 2 months to complete from 06/2024 to 07/2024.
Milestone 3: User Onboarding and Education
Functionality: In this milestone, we will focus on user onboarding and marketing efforts to attract and engage with our target audience. We will create educational resources, conduct outreach campaigns, and establish partnerships to promote the platform and drive user adoption.
Team and Roles: The same team of developers, project manager, and UX/UI designer from Milestone 1 will continue their roles in this milestone. Additionally, we will allocate resources for marketing and community management.
Funding Required: We estimate that this milestone will require a funding amount of $10000. This will cover the costs of marketing campaigns, community management, and additional resources for user onboarding.
Timeline: We anticipate that this milestone will take approximately 3 months to complete from 08/2024 to 10/2024.
By completing these milestones, we will have Filecoin integrated on our platform, thoroughly tested and optimized for performance, and actively engaging with our target audience. We believe that this roadmap will enable us to achieve our goals and drive the adoption and growth of Copernic Space.

## Total Budget Requested

| Milestone # | Description | Deliverables | Completion Date | Funding |
|1|Integration|- Fully functional platform integrating Filecoin for storage and management of space-related data and assets. - Compatibility across EVM networks. - Seamless integration of Filecoin as a payment option.|01/2024 and ending on 05/2024|$20000|
|2|Testing and Optimization|- Thorough testing of platform functionality. - Identification and resolution of bugs and issues. - Performance optimization for a seamless user experience. - Security audits to ensure platform integrity and safety.|06/2024 to 07/2024|$15000|
|3|User Onboarding and Education|- Creation of educational resources. - Outreach campaigns to attract and engage with the target audience. - Establishment of partnerships to promote the platform. - User onboarding resources and support.|08/2024 to 10/2024|$10000|

## Maintenance and Upgrade Plans

Specify your team's long-term plans to maintain this project and improve it over time. 
ur plans to ensure the sustainability and growth of the project are critical for the success of Copernic Space:
Regular Updates and Bug Fixes: We have a dedicated team of developers who continuously monitor the platform for any bugs or issues. Regular updates are released to address these concerns and improve the overall user experience.
User Feedback and Feature Requests: We value the input of our users and actively seek their feedback and feature requests. This helps us identify areas for improvement and prioritize the development of new features based on user needs.
Collaboration with Partners: We actively seek partnerships with other Space organizations and institutions in the scientific community. This enables us to leverage their expertise and resources to further improve our platform’s offering and expand its reach to the commercial mass market.
Community Engagement: We foster an active and engaged community around Copernic Space. This includes organizing events, webinars, and workshops to educate users and promote collaboration. We also have a dedicated community management team to facilitate discussions and address user queries.

# Team

## Team Members

Grant Blaisdell - CEO & Co-Founder
Grant Blaisdell is a seasoned entrepreneur with a strong background in the blockchain industry. He started his first startup at the age of 19 in Los Angeles and entered the blockchain industry in 2013. As the Co-Founder and CMO of Coinfirm, a globally leading blockchain analytics company, he has worked with some of the largest names in Web3 and built the brand into a global name. Grant also has three generations of space experience, combining his entrepreneurship and blockchain expertise to democratize access to space by creating the economic infrastructure for it.
You can learn more about Grant Blaisdell on his Twitter profile: twitter.com/GBSavant and his LinkedIn profile: linkedin.com/in/grantblaisdell 
Eva Blaisdell - CVO & Co-Founder
Eva Blaisdell is a tech, space, and media entrepreneur based in the United States. She has a wealth of experience as an executive in Fortune 100 companies and startups across California and Europe. Eva has successfully built tech brands such as Compaq/HP in new markets and created innovative initiatives around the world. Her expertise in technology and space industries makes her a valuable asset to Copernic Space.
You can learn more about Eva Blaisdell on her LinkedIn profile: linkedin.com/in/eva-blaisdell-lady-rocket-998a89bb and her Twitter profile: twitter.com/LadyRocketSpace 
Pylyp Radionov - CTO
Pylyp Radionov is our Chief Technology Officer (CTO) and Co-Founder. He is a skilled developer with expertise in both frontend and backend development. Pylyp has a strong background in technology and has contributed to various open-source projects. His technical knowledge and leadership skills are instrumental in driving the development and innovation of our platform.
You can learn more about Pylyp Radionov on his GitHub profile: github.com/mr13tech and his LinkedIn profile: linkedin.com/in/mr13tech 
Ferrell Belesko - Business Development
Ferrell Belesko is a seasoned business development professional with over 23 years of experience in the software sector. He has worked across various industries, including energy, government, fintech, engineering, and general business. Ferrell's expertise lies in complex software development, automation projects, and business consulting. He brings a wealth of knowledge in identifying economic opportunities and driving impact within evolving technology ecosystems.
You can learn more about Ferrell Belesko on his LinkedIn profile: linkedin.com/in/ferrellbeleshko
Manuel Olariu - Innovation & Patents
Manuel Olariu is heavily involved in different web3 ecosystems, including Decentralized Science, Regenerative Finance, and Decentralized Space. As the founder of DeepVenture.io, a web3 marketplace for space patents, Manuel brings a deep understanding of innovation and patents in the space industry. With Copernic Space, he is responsible for driving innovation and patent-related activities.
You can learn more about Manuel Olariu on his LinkedIn profile: linkedin.com/in/manuelolariu

## Team Member LinkedIn Profiles

https://linkedin.com/in/grantblaisdell 
https://linkedin.com/in/eva-blaisdell-lady-rocket-998a89bb 
https://linkedin.com/in/mr13tech 
https://linkedin.com/in/ferrellbeleshko 
 https://linkedin.com/in/manuelolariu

## Team Website

 https://copernicspace.com/about#rec414047757

## Relevant Experience

Our team at Copernic Space consists of founders who have a deep-rooted connection with the space industry. Our CEO, Grant Blaisdell, comes from a lineage of space pioneers, with his grandfather being instrumental in building a national space program. This connection gives Grant a unique perspective and understanding of the challenges and opportunities in the space industry. Grant has also successfully spent over a decade in the blockchain market and has a decorated track record of creation successful blockchain based products and companies such as Coinfirm, one of the global leading analytics and AML platforms.
In addition to Grant, our Co-CEO, Lady Rocket, brings decades in leadership positions in silicon valley tech companies and startups aloong with a wealth of experience in space initiatives and strong network within the space industry. This experience and network allow us to tap into valuable resources and collaborations that will benefit our project.
With our team's combined expertise, vision for democratizing access to space, and entrepreneurial acumen, we believe we are the right team to build this project. We are passionate about making space more accessible and are committed to leveraging our experience and connections to achieve our goals.

## Team code repositories

https://github.com/copernicspace 

# Additional Information
Emails:
gb@copernicspace.com
manu@copernicspace.com
Litepaper: https://drive.google.com/file/d/10V7HveWZMnjVxsKdE0h-VQNtXKLDRmUK/
Pitchdeck: https://docs.google.com/presentation/d/1N9y_Zq4QJ5MpE4Gre_eYxb8QzexC7BZsEV9siD1y2-M/

**Comment by ErinOCon** [comment]
Thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!

Note: To contact our team with grant program related inquiries, please send an email to grants@fil.org.
