### ISSUE TITLE
Next Step Microgrant: Collect3 - Bookmark Now. Own Forever.

### ISSUE THREAD

**Issue by diegotorreslopez81** [filecoin-project/devgrants#1667]
### 1. What is your project, and what problem does it solve? (max 100 words)

Collect3 is a browser plugin that empowers users to eternalize digital content like articles or posts using web3 and IPFS technologies. Unlike traditional bookmarks or saved PDFs, Collect3 allows users to mint and store reader-friendly versions of the content on the IPFS, ensuring permanence and true ownership and doc sharing using FVM. This solves the problem of content loss due to website changes, discontinuations, or censorship, offering a robust, decentralized solution for preserving valuable information.

### 2. Project links

Link to Github repo: https://github.com/8infinitelabs/collect3/
Link to demo or website: (landing page) https://collect3.me/
License: MIT

Here the steps we follow to collect articles:

![collect3-demo](https://github.com/filecoin-project/devgrants/assets/22802165/0e5270e1-8152-445c-b28b-0f578f0cb7a1)

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
Collect3 will let users keep their content forever as NFTs, to solve this problem we need to store the articles in the IPFS using FVM Perpetual Storage. In addition, we would love to let users share their content with other users using the Data Access Control feature.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes, we need to use FVM for Data Access Control and Perpetual Storage features.

  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  

Now, the project is working on storing the content into local storage, our next milestone is to use decentralized storage in order to let users keep their content forever.
 
| Number | Grant Deliverable   	| Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------             	| :---                                                   	| :---                   	|
|1.	|GD1	| Encode and decode HTML read mode file into .car	|2 weeks	|
|2.	|GD2 | Mint the content as NFT|2 weeks	|
|3.	|GD3 | Store the content on IPFS using FVM (Perpetual Storage)|3 weeks	|
|4.	|GD4 | Share articles with other users FVM (Data Access Control)|3 weeks	|
|5.	|GD5 | Users can read the article in reading mode through a pleasant user-experience	|2 weeks	|

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Absolutely, we have experience with the other open-source projects and we would love to share with the community the Collect3 updates.

  
### 6. Does your proposal comply with our Community Code of Conduct?

Totally 🙂

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

https://github.com/diegotorreslopez81/collect3/
https://collect3.me/
https://twitter.com/Collect3me

 
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Sure thing:
+ Diego Torres
[diego@infinitelabs.co](mailto:diego@infinitelabs.co)
https://github.com/diegotorreslopez81
Developer and Marketing

+ Johnny Varela
[johnny@infinitelabs.co](mailto:johnny@infinitelabs.co)
https://github.com/jhonnyV-V
Developer
 

* How did you learn about our microgrant program?
I usually follow IPFS/Filecoin for the last 7 years and I knew about them a long time ago.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
It didn’t.

**Comment by diegotorreslopez81** [comment]
Hi there! Any news here? Thanks in advance!

**Comment by ErinOCon** [comment]
Hi @diegotorreslopez81, this microgrant has been approved! We will send an email to confirm payment details. As mentioned above, the following are required for this microgrant:
- A fully working user-facing demo with nice UX that anyone can easily use
- Deployment to Filecoin mainnet + a testnet
- Interesting use of FVM, especially what's unique to Filecoin (for example, via the Filecoin Solidity API, FVM use cases, or Bacalhau x FVM, etc.)

Please be in touch with any questions!

**Comment by diegotorreslopez81** [comment]
Hello @eshon and friends!

We have already finished the development, here the repo: 

https://github.com/8infinitelabs/collect3/tree/filecoin-final


Please, let us know next steps for the payment and if we are able to continue with the grants program. Thanks!!

**Comment by eshon** [comment]
Hi @diegotorreslopez81, thanks for this FVM integration!

I never see the Share link, despite waiting a few minutes + refreshing:

![Screenshot 2024-06-11 at 10 13 58 AM](https://github.com/filecoin-project/devgrants/assets/1017762/8b1d7d67-95bc-4441-8a97-3e769eceadbf)

This is my Storage Configuration:

![Screenshot 2024-06-11 at 10 19 59 AM](https://github.com/filecoin-project/devgrants/assets/1017762/b76054e7-d8d7-4d85-b070-fd782afe99de)

I've also tried Storage Option "fvm" and "filecoin" but never see the Share link appear.

Questions:
- Can you link to the smart contract on FVM? I don't see any txn requests via MetaMask. Is that happening on the server?
- Where are the files being stored? NFT.storage?

**Comment by jhonnyV-V** [comment]
Hi @eshon, sorry for the late reply, I tried to check our logs, but we migrated servers and looks like we don't have any logs previous to the 14 of June, could you try again?, just to generate the logs and check what is going wrong, also, I updated the extension to display the storage type to avoid ambiguities when two or more options points to the same server.

About your questions

> Where are the files being stored? NFT.storage?

we will update the README to add this information, currently depending on the option

sia -> we use our renterd node to rent the file storage
filecoin -> we indeed do use nft.storage
fvm -> we use [lighthouse api](https://www.lighthouse.storage/), they handle most of the parts to make the [deals](https://docs.lighthouse.storage/lighthouse-1/filecoin-virtual-machine/section-a)
fvmEncrypted -> we also use [lighthouse](https://docs.lighthouse.storage/lighthouse-1/how-to/encryption-features)

> Can you link to the smart contract on FVM? I don't see any txn requests via MetaMask, only 1 signature request for the encryption. Is NFT minting happening via the server?

I currently do not have the link to the contract on fvm that handles the perpetual storage part, but I think I could get it, and for the nft contract, they do not get minted automatically, currently we do not support minting nfts on the fvmEncrypted, to try to mint you should use the sia, fvm or filecoin options, after saving the article, below the read link, a new link that says mint should appear, that will take you to the minting page, after the minting there will be a button that takes you to the block explorer to see the tx

**Comment by jhonnyV-V** [comment]
@eshon I did try a bit to find the cause of your issue, but I can find yet what failed at that moment, the reason that you don't see the share link is because something failed when uploading the encrypted file to lighthouse, but if you try again it should currently work


https://github.com/filecoin-project/devgrants/assets/46012817/f941add7-cdf6-419d-99c3-58d12e57a685

**Comment by eshon** [comment]
@jhonnyV-V @diegotorreslopez81 

FYI - I just tried setting up an fvmEncrypted storage option and never see the Share option. Tried setting up another fvmEncrypted instance and trying different blog websites but still never see it. (Also In your video, the Share link always appears along with Mint.) Can you guys just fix this Share link issue?

![Screenshot 2024-07-05 at 1 04 52 PM](https://github.com/filecoin-project/devgrants/assets/1017762/cdd252c9-32bb-44c4-8302-b8628717e2dd)
![Screenshot 2024-07-05 at 1 04 09 PM](https://github.com/filecoin-project/devgrants/assets/1017762/8984f2e1-8d46-4662-a750-519f75732c53)

But I was able to mint an NFT. I am wondering who the NFT was sent to here. I am the **_from_** address in the txn below. Who is the **_to_** address? I never got a dialogue to add an **_to_** address when minting.

https://calibration.filfox.info/en/message/0x116f2ab0b19f77eee5b47433d17f63ee901b876b64355f68886b77ef26f04b13?t=1

But please just fix the Share option, overall the minting seems to work.

**Comment by jhonnyV-V** [comment]
Hi @eshon, I noticed a few things, the reason of why that feature is not working for you, it appears to be that for some reason that I will look at, when you try to use the fvmEncrypt option is internally setting it to filecoin, it turns out that due to changes in the nft.storage api it is not working currently (as we now have lighthouse maybe we could drop support for it at the moment), I will try to fix this issue, another thing that I noticed, is that you have some options with the same defaults (url + type), this could cause some issues, also, an important point is that you are not using the latest version of the extension, there is some new internal changes and some handy fixes like updating the storage status when you click make main, and displaying the storage type

**Comment by jhonnyV-V** [comment]
as we reworked the extension internals, it may be possible that the issue is fixed, but I'm not sure yet, when you try to compile the extension again remember first to install all dependencies, also you will need to make a small change to the .env of the extension, you can copy the .env.example

**Comment by jhonnyV-V** [comment]
I forgot to say, **_to_** address in the tx is the contract, the from address is the one marked as an owner of the nft

**Comment by jhonnyV-V** [comment]
and currently nft.storage (appears as filecoin) option will be marked as not supported by the https://node.collect3.me, but everything else should be working fine with the latest extension version

**Comment by eshon** [comment]
@ErinOCon - This microgrant project has been successfully completed and is ready to proceed to final payout.
