### ISSUE TITLE
Next Step Microgrant: Spade - Social Media Application Utilizing Filecoin Technology

### ISSUE THREAD

**Issue by Spade-Social** [filecoin-project/devgrants#1668]
### 1. What is your project, and what problem does it solve? (max 100 words)

Spade, an elegantly designed social media platform developed with precision in Flutter, seamlessly harmonizes with a robust NodeJS backend integrated with Web3.storage. This pioneering synergy enables users to securely store diverse content such as posts and stories, delivering a seamless and efficient social media experience. Moreover, Spade contributes to addressing the challenge of bridging real-world value with the dynamic crypto industry, gradually enhancing its significance in the digital landscape.

### 2. Project links
  
Link to Flutter Frontend Github repo: https://github.com/Spade-Social-Org/spade_v3_wk
Link to NodeJS backend: https://github.com/Spade-Social-Org/spade-backend-v3
Figma design: https://www.figma.com/file/1NnqFrb6AfpEiujL7xndhw/Spade?type=design&node-id=0-1&mode=design&t=ZTsQH6fzczqSPwVr-0
Quick 16 minutes preview: https://bafybeigt2ucurt3xlhesjjhz4ps77az34mpk7jnt6bnatpqfns4juwgvnq.ipfs.w3s.link/Screen-2023-10-26-183912.mp4
License: MIT

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

Our project leverages the robust Filecoin/IPFS infrastructure for data storage and retrieval, seamlessly harnessed through the Web3.storage JavaScript library. This sophisticated implementation serves as the foundation for storing a diverse range of content, including thumbnails, user posts, and stories, thereby establishing a comprehensive and secure repository for media assets on the Filecoin network.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | Build a user profile page | By employing a new frontend dev to work on this | This should be done in the first month | 
| 2.     | Add a questionaire for a more personalized experience | By assigning someone from the current team to add these screens | Get someone from the current team to work on this | On the first month
| 3.     | Add extra hands to handle our backend | By employing a new backend developer to join us | This should be done in the first month | 
| 4.     | Start building our discovery algorithm | By assigning this to our backend developers | In three months | 
| 5.     | Marketing | By running ads and campaigns | Between month two and three | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Did not begin at a hackathon  

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
- **Josh Adi**
* Email: joshadi222@gmail.com 
* Role: Administrator & UI/UX Lead
- **Victor Omorogbe**
* Email: victoromorogbe69@gmail.com
* Github: https://github.com/okhaimie-dev
* Role: Project Manager & Developer Lead
- **Tochukwu Ebenezer Okeke**
* Email: ebenezerokeke99@gmail.com
* Github: https://github.com/Tochukwu88
* Role: Backend developer
- **Uzonna Anthony Mmegwa**
* Email: anthonyuzonna341@gmail.com 
* Github: https://github.com/anthonycodes1
* Role: Flutter developer
- **Victor Augustine**
* Email: augustinevickky@gmail.com
* Github: https://github.com/austinevick
* Role: Flutter developer
- **Stef Bio**
* Email: biostef3@gmail.com
* Role: UI/UX designer
- ** Victory Okotete**
* Email: iamsmart5000@gmail.com
* Role: UI/UX designer
* How did you learn about our microgrant program?
Victor Omorogbe learnt about this when participating in an ETHGLobal Hackathon
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by supreme2580** [comment]
Hey @ErinOCon we decided to build a lite version of our idea as we do not have funds to fully build it out yet, here is the link to the new repo [https://github.com/Spade-Social-Org/spade-lite](https://github.com/Spade-Social-Org/spade-lite) still leveraging Filecoin's web3 storage in the same way as mentioned before, we hope to hear from you soon, thanks.

**Comment by Spade-Social** [comment]
Hey @ErinOCon we decided to build a lite version of our idea as we do not have funds to fully build it out yet, here is the link to the new repo https://github.com/Spade-Social-Org/spade-lite still leveraging Filecoin's web3 storage in the same way as mentioned before, we hope to hear from you soon, thanks.

**Comment by ErinOCon** [comment]
Hi @Spade-Social, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant for this project. Please feel welcome to contact our team at [grants@fil.org](mailto:grants@fil.org) with any questions.

Wishing you the best as you continue to build!
