### ISSUE TITLE
Open Grant Proposal: `ZKAmoeba`--The first ever zkRollup layer2 solution based on Filecoin.

### ISSUE THREAD

**Issue by ZkaWatcher** [filecoin-project/devgrants#1670]
# Open Grant Proposal: `ZKAmoeba`

**Project Name:** `ZKAmoeba`

**Proposal Category:** `Research & protocols`

**Individual or Entity Name:** `ZKAmoeba Team`

**Proposer:** `ZkaWatcher`

**(Optional) Technical Sponsor:** `Jenks Guo`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** `Yes`

# Project Summary

Filecoin's mainnet block confirmation speed is relatively slow, with an average of 30 seconds per block. This is not sufficient to meet the demand for high-frequency trusted computing on the chain. Currently, most applications in the Filecoin ecosystem are based on wrapped mining, which is lacking in diversity and cannot attract enough community and ordinary users. As a result, Filecoin tokens have limited use cases, and their prices are difficult to increase. This has led to slow ecosystem development.

The root cause of this problem is that the Filecoin mainnet cannot support high-frequency trusted computing. ZKAmoeba, which uses zk-rollup technology, can effectively solve this problem. This will allow the Filecoin ecosystem to support high-frequency trusted computing like ETH and BSC, making it easier for developers to build applications and for users to participate. The gas fees in Layer2 are still paid in Filecoin tokens, which will drive the demand for Filecoin tokens and create more use cases. This will lead to higher Filecoin prices and a more vibrant ecosystem.

While Filecoin has made great progress in decentralized data storage, the retrieval and indexing of data are still not perfect. The Layer2 solution based on ZKAmoeba will use zero-knowledge proof technology to build an efficient and secure index and retrieval network, which will significantly improve the speed of data retrieval to meet the needs of storage users for data retrieval.`

## Impact 

ZKAmoeba is a Layer2 solution based on zero-knowledge proof, which aims to address the following pain points of Filecoin:

1. **Slow block confirmation speed:** Filecoin mainnet's block confirmation speed is 30 seconds, which is insufficient to meet the demand for high-frequency trusted computing on chain. ZKAmoeba uses zkrollup technology to process transaction data and calculation results offline, which can significantly improve the block confirmation speed.
2. **Lack of application scenarios:** Most applications in the Filecoin ecosystem are based on wrapped mining, which is lacking in diversity and cannot attract enough community and ordinary users. ZKAmoeba can provide Filecoin with more abundant application scenarios, such as data retrieval and smart contracts, which can attract more developers and users to participate.
3. **Slow data retrieval speed:** The current data retrieval speed of Filecoin is relatively slow, which cannot meet the needs of storage users for data retrieval. ZKAmoeba uses zero-knowledge proof technology to build an efficient and secure index and retrieval network, which can significantly improve the data retrieval speed.
4. **Improve the income of existing Filecoin miners.**

ZKAmoeba can benefit Filecoin miners in a number of ways, including:

1. **Increased layer-1 transaction volumes:** ZKAmoeba transactions are validated on layer1, so if ZKAmoeba drives the rapid growth of the ecosystem, it will generate more layer-1 transactions, which will increase layer1 transaction fees.

2. **Dual mining:** ZKAmoeba server nodes have a low entry barrier, so existing miners can safely deploy them to participate in block mining. This means that the same mining machines can be used to provide services on layer 1 and layer 2, achieving dual mining.

3. **Prioritizing Prover nodes:** In the future, ZKAmoeba Prover nodes will be prioritized for Filecoin miners. Participating in block verification can earn more rewards.

As an L2 scaling solution for Filecoin, ZKAmoeba improves scalability and efficiency, significantly lowers the barrier to entry for developers, and is beneficial to ecosystem development.

1. **Data storage&index:** ZKAmoeba can improve Filecoin's data retrieval speed, which can meet the needs of storage users for data retrieval. This will benefit the development of the data storage industry, such as the media, healthcare, and finance industries.
2. **Smart contracts:** ZKAmoeba can provide Filecoin with more abundant application scenarios, such as data retrieval and smart contracts. This will benefit the development of the smart contract market, such as the financial, gaming, and supply chain industries.
3. **Decentralized applications:** ZKAmoeba can reduce Filecoin's gas fees, which can reduce the development and use costs of decentralized applications. This will benefit the development of the decentralized application ecosystem, such as social networking, gaming, and finance.

### **Final target outcomes**

1. Significantly improve block confirmation speed and transaction bursts: Using the zero-knowledge proof mechanism, the block confirmation speed is increased to the fastest 1 second per block, and supports large-scale transaction bursts, which is 20 times the current TPS of FILECOIN.
2. Make ZKAmoeba nodes completely decentralized: Through community participation and incentive mechanisms, promote the decentralization of ZKAmoeba nodes.
3. Become the largest infrastructure project on Filecoin: Through technological innovation and ecological expansion, become an indispensable infrastructure in the Filecoin ecosystem.
4. Improve the application categories in the Filecoin ecosystem: Cooperate with projects in the fields of DeFi and DAO to expand the application scenarios of Filecoin.

### **Deliverables**

1. Block confirmation speed is increased to 1 second per block at the fastest using zero-knowledge proof mechanism
2. The construction of decentralized nodes has started, with at least 13 servers and an unlimited number of prover nodes initially. Currently, 4 servers are running.
3. DeFi projects and DAO organizations have been expanded in the ecological application, a cooperation with a large community project with 400,000 members is confirmed, which will be deployed to ZKAmoeba after the mainnet launch.

ZKAmoeba aims to become the most impactful Layer 2 project on Filecoin within one year, with over 150 dApps, more than 10,000 transactions per day, and at least 500 daily active addresses.

Below are the part of projects that have been added to the ecology, and more are on the way.
1. (@FileBOX_FBOX) FileBox will help power the ZKAmoeba Network storage experience. It brings quality infrastructure to web3, allowing for seamless and secure file storage through advanced technolog.
2. (@DBSWAP) DBSWAP is the pioneering DeFi Protocol based on the ZKAmoeba Network & FEVM,that allows users to trade tokens at the lowest rate.
3. (@FoneFil) F-ONE is an innovative project. Discover the future of Layer2 Filecoin solutions with F-ONE, brought to you by ZKAmoeba. 
4. (@AiPocketFund) AiPocket is the first wallet addition to #ZKAmoeba. It's central hub of innovative Products & Services catered to the Web 3.0 Ecosystem.

## Adoption, Reach, and Growth Strategies

Our target audience: Filecoin users and blockchain developers.

ZKAmoeba has gained support from many Filecoin ecosystem projects and communities, including Orign Community, ND labs, Interstellar Storage, and Western World. Users from these communities will be the initial users of ZKAmoeba.

ZKAmoeba will organize a series of events to deepen users' understanding of ZKAmoeba, and attract developers to the ZKAmoeba ecosystem. These events include user education, community building, and developer engagement.

1. ZKAmoeba hosts tutorials, lectures, and workshops to help users learn about the basics of ZKAmoeba.
2. ZKAmoeba community activities will include, but are not limited to, online and offline AMAs, volunteer recruitment, and ZKAmoeba conferences.
3. ZKAmoeba hosts hackathons, technical meetups, and other events to attract developers to build on the ZKAmoeba ecosystem. It will also provide bug bounty to all whitehat hackers to help improve ZKAmoeba. 

## Development Roadmap

L2 Protocol Design   
Web v1(2023/01)   
Docs (2023/03)  
Revamped Design v2(2023/03)  
Internal Testnet(2023/05)  
Two Strategic Advisors added(2023/08)  
External Testnet v2(2023/08) 
Testnet v3(2023/08)  
-----We are here-----  
Mainnet v1  
Rapid Team Expansion  
Node mining  
Airdrop  
Community Development  
Develop Dapps   
Partnerships and Integrations  
The journey continues...  

## Total Budget Requested

| Milestone # | Description | Deliverables | Completion Date | Funding |
|===|===|===|===|===|

Milestone 1
- Time: March 2023 - July 30, 2023
- Key deliverables: Complete the development of the ZKAmoeba testnet, achieving 200 TPS.
- Status: Completed & demoable
- Funding used: 20,000 USDC (or FIL equivalent)

Milestone 2
- Time: August 2023 - October 2023
- Key deliverables: Complete the Prover verification of ZKAmoeba, achieving the gradual separation of server and Prover nodes.
- Status: Completed & Demoable
- Estimated funding required: 20,000 USDC (or FIL equivalent)

Milestone 3-Growth
- Time: due at 2024 Q4
- Key deliverables: Grow influence of ZKAmoeba Layer 2 project on Filecoin in 2024, onboard over 150 dApps, achieve more than 10,000 transactions per day, and at least 500 daily active addresses.
- Status: In progress
- Estimated funding required: 10,000 USDC (or FIL equivalent)

## Maintenance and Upgrade Plans

# Team

## Team Members

Henri/CTO
Serial entrepreneur; 
12 years of experience in internet product development; 
Founded three internet companies with valuations exceeding one billion dollars.

Morning/Co-Founder
Double Degree Graduate from Singapore Management University;
Former Head of Growth and SEA Market for Huobi Ecosystem (HECO). 
Founded a web3 accelerator.

Baiciao Ren/Head of Ecosystem
Wharton School and Haveford College;
Over 7 years of consultancy experience;
Former-VP of Business Development in Origin Storage.

## Team Member LinkedIn Profiles

[https://www.linkedin.com/in/henri-yao-8a0596298/](url)

[https://www.linkedin.com/in/qingchen-gao-476420b0](url)

[http://linkedin.com/in/baiciao-ren-77110a25](url)

## Team Website

[https://www.zkamoeba.com/](url)

## Relevant Experience

ZKAmoeba is a global team of over 20 people, spanning 4 continents and 7 countries. The team has extensive experience in zkRollup development, web3 community operations, and management. The founding team is made up of female entrepreneurs who graduated from Ivy League schools, and they will play a key role in ZKAmoeba's ecosystem development.

## Team code repositories

[https://github.com/ZKAmoeba-Micro/micro](url)

# Additional Information

We learn about the Open Grants Program from github.

**Comment by ErinOCon** [comment]
Hi @ZkaWatcher, thank you for your proposal and for your interest in our grant program. This proposal is still under consideration and has progressed to our final review round. We will be in touch if there are any questions before providing a final decision in this thread. 

Thank you for your patience!

**Comment by ErinOCon** [comment]
Hi @ZkaWatcher, thank you for your patience with our review. Would you have an interest in rescoping the project to focus on testnet completion for $50k? If so,  please break down the deliverables necessary to complete this objective in an updated proposal.

**Comment by ErinOCon** [comment]
HI @ZkaWatcher, this issue has been closed. Please feel welcome to contact our team at grants@fil.org if you would like to continue discussing this proposal.

**Comment by jenks-guo-filecoin** [comment]
Hi @realChainLife the team has contacted me about this issue. I will remind them to edit their proposal and get back to us here.

**Comment by ZkaWatcher** [comment]
We have recieved some feedback from @jenks-guo-filecoin, and reduced the total size of grant. We have also changed our ask from USDT to USDC or FIL equivalent. Please kindly review our application again. @ErinOCon @realChainLife

**Comment by ErinOCon** [comment]
Hi @ZkaWatcher, thank you for the revised submission! We would like to move your proposal forward to the next steps in our process. Can you confirm the preferred email address for your team?

**Comment by jenks-guo-filecoin** [comment]
@ZkaWatcher please provide your team's or responsible person's email address as soon as possible so we can process this grant contract.

**Comment by ZkaWatcher** [comment]
@jenks-guo-filecoin email: team@zkamoeba.com

**Comment by ErinOCon** [comment]
Hi @ZkaWatcher, please let us know if you have any questions regarding the next steps provided by email.
