### ISSUE TITLE
Next Step Microgrant: Navis, a WebAssembly based decentralized compute platform on Filecoin Virtual Machine

### ISSUE THREAD

**Issue by grzxz** [filecoin-project/devgrants#1672]
### 1. What is your project, and what problem does it solve? (max 100 words)

Navis is a decentralized compute platform based on WebAssembly that provides Functions as a Service like compute for blockchain developers so they access compute from smart contracts using Filecoin/IPFS for storage.

Navis is based on Proof of Compute, a replication by consensus algorithm where Navis miners provide compute and get token rewards for providing accurate compute results.

### 2. Project links
  
Link to Github repo: Prototype stage
Link to demo or website: Prototype stage
License: MIT

### 3. a) How is IPFS, Filecoin, or related technology used in this project?

Navis is deployed into FVM via FEVM Solidity smart contracts using Filecoin/IPFS for storage of compute executables, datasets and compute input/outputs.

###   b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
 
Yes, it use Filecoin Virtual Machine for Solidity smart contract deployment.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

Now project is at the prototype stage in a Hardhat local environment. The plan is to deploy it on Filecoin VIrtual Machine to record demo of product usage and share Github repository.
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|

| 1.     |   Navis Github repository + demo video     |  Update with GIthub demo and demo video | 4 weeks                       | 
         

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes, via the Github issue and Slack!
  
### 6. Does your proposal comply with our Community Code of Conduct?
Sure.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Guillermo Ritorni
https://www.linkedin.com/in/guillermorr/
guillermo.ritorni.salvo@gmail.com
https://github.com/grzxz

**Comment by grzxz** [comment]
@ErinOCon @eshon just checking on this, any updates?

**Comment by ErinOCon** [comment]
Hi @grzxz, this microgrant has been approved! We will send an email to confirm payment details. As mentioned above, the following are required for this microgrant:

- A fully working user-facing demo with nice UX that anyone can easily use
- Deployment to Filecoin mainnet + a testnet
- nteresting use of FVM, especially what's unique to Filecoin (for example, via the Filecoin Solidity API, FVM use cases, or Bacalhau x FVM, etc.)

Please be in touch with any questions!

**Comment by ErinOCon** [comment]
Hi @grzxz, since this project has kicked off, the issue has been closed. Please be in touch at grants@fil.org with any questions.
