### ISSUE TITLE
Next Step Microgrant : Xertificate to combat credential frauds

### ISSUE THREAD

**Issue by fatjase** [filecoin-project/devgrants#1674]
### 1. What is your project, and what problem does it solve? (max 100 words)

Imagine a world where our credentials are instantly verified, your real qualifications are recognized, and credential fraud is a thing of the past. A world where we can trust each other's expertise and build relationships based on merit, not deception.

Xertificate is a startup that issues digital certificates as verified proof of authenticity and permanent ownership with the mission to combat credential fraud and empower digital adoption.

We use IPFS tech and Lighthouse.storage, a layer-2 solution of Filecoin, to store and ensure longevity of digital media file existence.

### 2. Project links
  
[linktr.ee/xertificate](https://linktr.ee/xertificate)

[Website | xertificate.io](https://www.xertificate.io/)
[LinkedIn | xertificate](https://www.linkedin.com/company/xertificate)
[Twitter | @xertificate](https://twitter.com/xertificate)
[Email | team.xertificate@gmail.com](team.xertificate@gmail.com)

  

### 3. a) How is IPFS, Filecoin, or related technology used in this project?

For each digital certificate issued to prove credentials and serve academic institutions, NGO, students, brands and artists, it is stored and backed by decentralized storage to ensure permanent and longevity and IPFS protocol.

Both direct and virtual hosting are opted to ensure the longevity of media data.

-- Virtual IPFS hosting & pinning partner ( current ) : [Lighthouse.storage](https://www.lighthouse.storage/)
-- Direct hosting partner ( in conversation ) : SmallWorld Venture, Cambodia
-- Direct self-hosting  ( in planning ) : Self-hosting through IPFS cluster, own node

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)

No
   
 
 
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

Roll-out period : 3 months
Area of focus : 
(a). Decentralized data storage & longevity
(b). On-boarding academic institutions & NGOs
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | Lighthouse.storage secure virtual IPFS hosting ( x5 - x10 years )                        | Partnership & service subscription                                                           | Month +1                           |
| 2.     | SmallWorldVenture direct node IPFS hosting ( x2 - x5 years )                        | Partnership sign-off                                                          | Month +2                         | 
| 3.     | Pro bono issuance                        | Issue free of charge up to 100 digital certificates to eligible NGO or academic institutions, under Filecoin microgrant                                                            | Month +1 +2 +3                           | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes

 
 
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions

N/A

  
### Additional questions:

Team : 
-- Jason | team.xertificate@gmail.com | Github : @fatjase | Founder, Project Lead
-- Livin | livin.huotkeo@gmail.com | Github : - | Social Media & Secretary
-- Nou | mealika11@gmail.com | Github : @Mealika911 | Project Treasurer

We know of Filecoin protocol back in 2021.
We know of Filecoin microgrant from a friend and further research.

**Comment by ErinOCon** [comment]
Hi @fatjase, thank you for your proposal. Unfortunately, we will not be moving forward with a grant for this project. The microgrant program is currently focusing on FVM related work (see more details [here](https://github.com/filecoin-project/devgrants/blob/master/microgrants/microgrants.md)).

**Comment by fatjase** [comment]
Thank you for your prompted response.
