### ISSUE TITLE
Next Step Microgrant: Arttribute - Enabling Artists to Create and Share Fine-tuned AI Art Models Leveraging Bacalhau (Tokenizing Fine-tuned Models)

### ISSUE THREAD

**Issue by bashybaranaba** [filecoin-project/devgrants#1680]
### 1. What is your project, and what problem does it solve? (max 100 words)
Arttribute as a protocol aims to enable equitable and transparent usage of Artwork in generative AI. It allows artists to upload their artwork and define terms for AI usage, ensuring proper attribution through unique, verifiable certificates.

On top of this, we are building a product that allows visual artists to create and share fine-tuned models that mimic their artistic style, enabling them to earn from their model's usage.

### 2. Project links
  
Link to Github repo: https://github.com/orgs/Arttribute/repositories

Link to demo: https://studio.arttribute.io/

Link to website: https://www.arttribute.io/

License: MIT
  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?
We currently have an MVP that provides artists with a simple UI to upload art and create fine-tuned models.
In this implementation, artwork uploaded by artists is stored on IPFS using  Web3.Storage.
For model fine-tuning and text-to-image generation, we are currently using  [Astria's API](https://www.astria.ai/)  
We intend to build a model  fine-tuning and text-to-image generation API leveraging Bacalhau.
Fine-tuned models and generated images files will be stored on IPFS.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | A simple API for Model fine-tuning and image generation | Designing and implementing a model fine-tuning and image generation  API using Nest Js| 6 weeks | 
| 2.     | API Documentation |Creating a well-structured and detailed API documentation that covers essential aspects of using the API. This will be done using Docusaurus  and also an interactive Postman documentation |4weeks | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Baranaba Mugabane - bashybaranaba@gmail.com , https://github.com/bashybaranaba , dev & team lead

Eddie Gikundi - eddiemwiti10@gmail.com, https://github.com/eddiemg10  , dev

Fadhili Gakwa - ggakwa.me@gmail.com,  https://github.com/gitaugakwa , dev

Khalifa Fumo  - khalifafumo5@gmail.com, https://github.com/khalifa47 , dev

* How did you learn about our microgrant program?
    Filecoin's grants page
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by bashybaranaba** [comment]
Hello, and Happy New Year!
Just checking in on the status of the grant request

**Comment by ErinOCon** [comment]
HI @bashybaranaba, thank you for your proposal and for your patience with our review process. Unfortunately, we will not be moving forward with a grant for this project. Please feel welcome to contact our team at [grants@fil.org](mailto:grants@fil.org) with any questions.

Wishing you the best as you continue to build!
