### ISSUE TITLE
HuggingLily

### ISSUE THREAD

**Issue by justmert** [filecoin-project/devgrants#1681]
# Open Grant Proposal: `HuggingLily`

**Project Name:** HuggingLily

**Proposal Category:** `Applications`

**Individual or Entity Name:** YK Labs

**Proposer:** `justmert`

**(Optional) Technical Sponsor:** [Ally Haire](https://www.linkedin.com/in/ally-haire/), Lilypad CEO & Co-Founder

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

The rise of AI has unlocked advanced technological capabilities, yet the barriers to entry remain high due to complexities in model training, deployment, and the necessity for centralized infrastructures. Lilypad answers this call by offering an accessible gateway to AI in the form of trustless distributed compute network for web3, yet it still presents a steep learning curve for those looking to use AI models easily, thus needs an additional layer to become truly accessible to everyday users.

HuggingLily is designed to function as an AI studio, addresses this by using the power of Lilypad to provide a user-friendly platform for interacting AI models to perform tasks, wide range of AI tasks, without any technical expertise. By integrating directly with the Lilypad network and leveraging Hugging Face's transformers pretrained models, HuggingLily offers the decentralize compute just a click away. Users can not only submit jobs and retrieve results but also list, sell, or purchase these inferences, growing a community-driven AI ecosystem.

## Impact

* Hugging Face offers AI tasks and models in a priced, centralized manner through its Hosted Inference API. HuggingLily, on the other hand, provides decentralized solution by leveraging Lilypad. This approach offers decentralized access to compute layer, reducing costs and enabling a wider range of users to utilize advanced AI capabilities easily.

* Smart contracts of HuggingLily are accessible from any FEVM contract, serving a wide range of AI tasks to the Filecoin FVM network. This flexibility and accessibility expand the potential use cases for the FEVM network, giving access to the AI inference in smart contracts.

* HuggingLily makes advanced AI accessible to a wider audience, breaking down technical barriers. This aligns with the ethos of Filecoin and Lilypad to democratize access to data and computing power, furthering the adoption of decentralized AI in Filecoin.

* By providing a UX layer for Lilypad’s decentralized computing infrastructure, HuggingLily strengthens the entire Filecoin Lilypad ecosystem, showcasing the potential of decentralized compute, serving as a model for future projects and growing the field of decentralized computing.

* HuggingLily's AI marketplace brings a unique economic incentive to decentralized computing. By allowing users to buy, sell, and exchange AI inferences, it not only enriches the Lilypad ecosystem with a vibrant market but also motivates further participation and innovation in decentralized AI.

## Outcomes

In the end of the project, we will have a fully functional AI studio that can be used by anyone to perform AI tasks. The AI studio will be accessible from any FEVM contract, or from the frontend. Users will be able to select from a wide range of AI tasks (such as summarization, question answering, object detection etc.), select the model and model parameters, and submit the job to the Lilypad network. The results will be stored on IPFS (thanks to Lilypad) and the user will be able to retrieve them from the frontend or from smart contracts. The frontend displays the results dynamically based on the output format of the AI task.

The AI studio will also have a marketplace that allows users optionally list their inference results for sale, or buy inference results from other users by paying small amount of ETH or LP for the owner of the inference result. Owner of the inference result has paid compute fees to Lilypad (currently free besides network fee) to perform the inference, and the marketplace allows them to earn by selling the results to other users as an incentive. This creates a vibrant marketplace for AI inferences, furthering the adoption of decentralized AI.

Users will be able to register and login to the AI studio through WalletConnect, and their data will be stored on a database. The database will also store the CIDs of the inference results, allowing users to retrieve them later. The notifications will be sent to the users when the status of their jobs change, such as when the job is completed, or when the inference results are buyed by another user.

The full list of deliverables are listed below,

**Deliverables**

1. HuggingLily Contracts
    * Bacalhau job invocation and inference results retrieval that interacts with LilyPadEvents Contract
    * Functionality that allows users to list, buy and withdraw inference results from the marketplace
    * Callable functions for each AI task that can be invoked from any FEVM contract
2. Frontend Infrastructure
    * User registration and login through WalletConnect
    * More than 20 AI tasks with selectable models and model parameters
    * Task execution on Inference submission page
    * Displaying inference results dynamically based on output formats
    * Option to download inference results, or listing them on the marketplace
    * Marketplace page selling, or buying inference results
    * User profile page that displays user information and inference results CIDs
    * Receving notifications for job status changes
    * Marketplace economic incentive system that rewards users if listed inference results are purchased
3. Database setup for storing user data and job result CIDs
4. Dockerfiles for all HuggingFace transformers models for each task as well as each model
5. Implementation of Lilypad module job definition for Lilypad.
6. Inference scripts for HuggingFace model execution.
7. Documentation of the HuggingLily usage and architecture.
8. Testing framework for backend and frontend components.

**Technical Architecture**

![techincal_structure](https://github.com/filecoin-project/devgrants/assets/37740842/5038ba36-5061-44b8-a171-0c77c4add89d)

**MVP Mockups**

|  |  |
|----|----|
| <img width="1776" alt="mockup1" src="https://github.com/filecoin-project/devgrants/assets/37740842/d5a43591-9b83-43f5-b433-6c646a16f5ac"> | <img width="1776" alt="mockup2" src="https://github.com/filecoin-project/devgrants/assets/37740842/72ba8727-72a8-47a9-b562-efda3b3e898a"> |
|<img width="1784" alt="mockup3" src="https://github.com/filecoin-project/devgrants/assets/37740842/43987d27-bfbf-4e2c-8227-017216da8813"> | <img width="1784" alt="mockup4" src="https://github.com/filecoin-project/devgrants/assets/37740842/8d50889a-66b0-491a-bc57-6cdd45a8fde4"> |

## Adoption, Reach, and Growth Strategies

The target audience for HuggingLily includes users that needs to perform AI tasks, but do not have the technical expertise to do so, smart-contract developers who needs AI tasks in their FEVM contract, and potential users of decentralized AI services. We aim to engage with the Lilypad and Filecoin communities from Discord, Twitter etc. to promote adoption. Onboarding will involve creating user-friendly documentation with simple usage examples.

## Development Roadmap

| Milestone # | Description                               | Deliverables                                        | Completion Date | Funding  |
|-------------|-------------------------------------------|-----------------------------------------------------|-----------------|----------|
| 1           | Implementation of Core Inference Functionality | <ul><li>User registration and login through WalletConnect</li><li>Bacalhau job invocation and inference results retrieval that interacts with LilyPadEvents Contract</li><li>Task execution on Inference submission page implementation with more than 20 AI tasks with selectable models and model parameters, as well as displaying inference results dynamically based on output formats. Ability to download inference results.</li><li>Implementation of Lilypad module job definition for Lilypad.</li><li>Inference scripts for HuggingFace model execution.</li></ul>| January 26, 2024 | 19.200$   |
| 2           | Development of the Marketplace and User Profile System | <ul><li>Marketplace implementation that allows users to list, buy and withdraw inference results</li><li>User profile page that displays user information and inference results CIDs</li><li>Database setup for storing user data and job result CIDs</li><li>Dockerfiles for all HuggingFace transformers models for each task as well as each model</li></ul>| February 24, 2024 | 13.920$   |
| 3           | Integration of AI Tasks with Smart Contracts and Testing Framework          | <ul><li>Callable functions for each AI task in smart-contract that can be invoked from any FEVM contract</li><li>Marketplace economic incentive system that rewards users if listed inference results are purchased</li><li>Documentation of the HuggingLily usage and architecture.</li><li>Testing framework for backend and frontend components.</li></ul>| March 17, 2024   | 10.560$   |

## Total Budget Requested

**Total Budget Requested:** 43.680 USD

## Maintenance and Upgrade Plans

Our long-term plans for HuggingLily involve continuous maintenance and improvement. Lilypad is still in its early stages, and we will continue to improve the platform as it grows. We will also continue to add new AI tasks and models to HuggingLily, expanding the capabilities of the platform.

The future plans for HuggingLily are listed below,

* Supporting user trained models that can be uploaded to the platform, allowing users to earn by providing their models
* Adding new AI tasks and models to the platform
* Adding new features to the marketplace, such as the ability to rate and review inference results
* Currently incentivizing users to list their inference results on the marketplace, we will also incentivize list their data and custom models on the marketplace

# Team

## Team Members

* Mert Köklü - Backend Developer
* Tolga Yaycı - Frontend Developer

## Team Member LinkedIn Profiles

* Mert Köklü - <https://www.linkedin.com/in/mertkoklu/>
* Tolga Yaycı - <https://www.linkedin.com/in/tolgayayci/>

## Team Website

<https://yk-labs.com>

### Mert Köklü - Backend Developer

Have worked as Intelligent Video Analytics Team Leader in a NVIDIA distributer company that develops video analytics solutions for 2 years. Have experience in developing video analytics solutions using NVIDIA DeepStream, GStreamer, and Python. Created a AI computer vision engine that powers a video analytics platform that is used by many companies in Turkey.

As an experienced Web3 developer, became a grantee for Web3 Foundation, AAVE, Lens and Filecoin and other ecosystems by developing innovative projects. As a certified NVIDIA instructor, AAVE Turkey Community Co-Manager and ambassador for organizations such as Microsoft and The Graph protocol. Currently, focused on developing open-source and user-friendly applications that bring value in blockchain area.

* Github: <https://github.com/justmert>
* Discord: MertK#2634
* EMail: <kklumert@gmail.com>

### Tolga Yaycı - Frontend Developer

As a full-stack developer with 2 years of experience, have refined his skills in software development, with a focus on dApp development in the past year. Have a deep interest in the Web3 space and have applied his skills by creating a number of relevant applications. In addition to his experience, have developed detailed React and Next.js projects, further enhancing his ability to build robust and scalable web applications.

In addition to his technical skills, have also been actively involved in the wider tech community. Have served as a Chainlink Community Advocate, Aave Turkey Community Manager, and Founding Chair of Gazi University ACM Student Chapter. These roles have broadened his skills in both software development and community engagement.

* GitHub: <https://github.com/tolgayayci>
* Discord: @tolgayayci
* Email: <tolgayayci@protonmail.com>

## Team code repositories

We have founded YK Labs, a company specialized in developing applications and solutions within the blockchain ecosystem. Our collaborative efforts have led to the creation of numerous projects across various platforms, earning recognition and grants for our innovative contributions. These are some of our projects:

* Flowana: A protocol aggregator platform - flowana.app
* Peer-CLI: Swiss army knife for IPFS - github.com/justmert/peer-cli
* Slack and IPFS integration: github.com/tolgayayci/slack-ipfs-app
* IPIVA: Provides decentralized AI video analytics with syncing AI model metadata across OrbitDB peer networks. - github.com/justmert/IPIVA
* Awesome Platform: A social platform for discovering and exploring the projects in protocols - awesomecompound.org (for Compound)
* AaveQL: Aave Grapql documentation with built-in support editor and examples - aaveql.org
* Dotly: Polkadot Account statistics - dotly.net
* Aave Telegram Bot - github.com/justmert/Aave-API-Telegram-Bot

and many more. We have experience working with well-known protocols such as Aave, Compound, Filecoin, Flow, Lens Protocol, Dfinity Foundation, Web3 Foundation, Solana, and Sia, showcasing our ability to handle multiple ecosystems and expertises.

# Additional Information

HuggingLily was borned in the ETHGlobal Istanbul Hackathon! It has received 🏆 `Filecoin — Grand Prize` as <b>best project in Filecoin</b>!

* Hackathon Submission: <https://ethglobal.com/showcase/hugginglily-wvusa>
* Lilypad Tweet 1: <https://twitter.com/Lilypad_Tech/status/1729969278957543581>
* Lilypad Tweet 2: <https://twitter.com/Lilypad_Tech/status/1726250543767859243>

HuggingLily has been supported by [Ally Haire](https://www.linkedin.com/in/ally-haire/), Lilypad CEO & Co-Founder. She has been a great mentor for us and helped us to improve our project. We are very grateful for her support.

We can further discuss the details of the project with a [meeting](https://calendly.com/yklabs-mert/30min). Thank you.

**Comment by ErinOCon** [comment]
Hi @justmert, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Please feel welcome to submit a proposal in the future as your project continues to develop. 

To contact our team with any questions, please send an email to grants@fil.org. Wishing you the best as you continue building!
