### ISSUE TITLE
Next Step Microgrant: Harveeco, monetizing granular farm data through a DataDAO governance structure

### ISSUE THREAD

**Issue by Shubham-Rasal** [filecoin-project/devgrants#1684]
### 1. What is your project, and what problem does it solve? (max 100 words)

In developing countries, farmers don't have a way to make an educated guess for what the price of the crop they are growing today will be in the future. This leads to over or under-utilisation of farm resources. Also, most farmers don't have an idea about what crop is best for them in their kind of land. 

### 2. Project links
  
Link to Github repo: https://github.com/marcdhi/harveeco
Link to demo or website: https://harveeco.vercel.app/
License: [MIT](https://github.com/marcdhi/harveeco?tab=MIT-1-ov-file#)
  
#### Harveeco Architecture

![image](https://github.com/filecoin-project/devgrants/assets/95695273/d6e585cf-5451-4668-a347-626a9e2d8ceb)

Based on the above-mentioned design, our approach to solving this problem is  - 

- **Data Gathering with NodeMCU**: Our project utilizes NodeMCU microcontrollers equipped with various sensors to collect real-time data from the environment. These sensors capture temperature, pressure, altitude, and moisture levels, providing crucial insights into agricultural conditions.

- **Data Storage on Lighthouse:** The processed data is securely stored on the Lighthouse network, a decentralized storage platform built on Filecoin and FVM. This ensures data integrity and immutability, preventing any tampering or manipulation.

- **ML-powered Predictions**: The stored data is then analyzed by powerful machine learning algorithms. These algorithms identify patterns and predict future trends, enabling farmers to make informed decisions about their crops and optimize resource utilization. This predictive analysis helps farmers maximize yields, minimize losses, and improve overall efficiency.

- **Enhanced Transparency with ZKML**: Our project utilizes Zero-Knowledge Machine Learning (ZKML) to further enhance transparency and trust in our predictions. ZKML enables us to verify the correctness of model predictions without revealing the underlying model itself.

###    b) Is this project building with the current microgrant focus area (FVM)? (Yes or No)

**Yes**. 

The original idea we had was to build our own DataDAO from scratch with custom contracts. Although this approach is not bad, due to the time constraint in the hackathon, we decided to use Lighthouse which gave us a lot of features we wanted right out of the box. The most important feature we wanted was the ability to combine a set of time series data chucks into a single deal on the FVM. This drastically reduces the cost of storage and we observed that it was cheaper than the RDS costs of AWS.

  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

The main focus in future would be to make Harveeco production ready. Based on this vision, the following deliverables can be expected   

| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | Rework DataDao System Design| Brainstorming with the  Filecoin and Lighthouse teams to come up with a pragmatic solution design                                                            |    2 weeks                        | 
| 2.     | Implement DataDao|  Backend (Smart contracts for governance and monetisation) Implementation                                                         |    1 month                        | 
| 3.     | Setup IoT + ML                       | Implement infrastructure for IoT time series data streaming and zkML-based training pipeline                                                            | 2 weeks                           | 
| 4.     | Integration and Deployment                         |  Integrating all the parts and deployment on calibration testnet with a Nextjs UI                                                          |  1 month                           | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

If accepted, we would prefer a biweekly review with a monthly report for better transparency. Updates will be shared in this issue with a public roadmap of Harveeco in the repo project section.

  
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: https://ethglobal.com/showcase/harveeco-j7jci
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

#### Team Members

- [Shubham Rasal](https://github.com/Shubham-Rasal) - bluequbits@gmail.com (Blockchain + UI)
- [Hriday Mehta](https://github.com/HridayM25) - hridaym.211me129@nitk.edu.in (zkML)
- [Vedant Tarale](https://github.com/VedantTarale) - vedanttarale10@gmail.com (IoT)
- [Ayush Kumar Singh](https://github.com/ayush4345) - ayushk4549@gmail.com (Blockchain + Frontend UI integration)
- [Mardav Gandhi](https://github.com/marcdhi) - gandhimardav.211mn028@nitk.edu.in (Backend Integration)

* How did you learn about our microgrant program?

 - Got to know about the grant through a congratulatory email sent to our team for winning a track prize in ETHIndia'23

* If your project was created as part of an event or hackathon:
  * What was the name of the event? -  ETHIndia'23
  * Please link to your hackathon submission
  ### Submission links 
- [Devfolio Submission](https://devfolio.co/projects/harveeco-c20c)
- [EthGlobal Showcase](https://ethglobal.com/showcase/harveeco-j7jci)

**Comment by Shubham-Rasal** [comment]
Any update on this proposal?

**Comment by ErinOCon** [comment]
Hi @Shubham-Rasal, thank you for your proposal and for your patience with our review process. Unfortunately, after much consideration, it has been determined that we will not be be moving forward with a new grant at this time.

I will be sending you an email shortly to discuss other ways to partner with our community. Wishing you the best as you continue to build!
