### ISSUE TITLE
FileBuild - Adapptable

### ISSUE THREAD

**Issue by AdapptableDev** [filecoin-project/devgrants#1686]
# Open Grant Proposal: `FileBuild - Adapptable`

**Project Name:** FileBuild - Adapptable

**Proposal Category:** `Developer and data tooling`

**Individual or Entity Name:** Entity 

**Proposer:** `@AdapptableDev`

**Project Repo(s)** https://github.com/AdapptableDev

**(Optional) Filecoin ecosystem affiliations:** `/` 

**(Optional) Technical Sponsor:** `/`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** `Yes` 

# Project Summary

**What the Product Is**

FileBuild is an innovative plugin for Bubble.io, designed to facilitate the development of decentralized applications (Dapps) on Filecoin. It serves as a bridge for both novices and experienced developers, streamlining the integration of blockchain technology into web applications. 

**What Problems It Solves, How It Solves Them, and Who It Serves**

**The Problem:** The development of Dapps is often hindered by the complexity of blockchain technology, creating barriers for both novice and experienced developers. On the one hand, novices struggle with the technicalities of blockchain connections. On the other hand, advanced developers are looking for ways to create sophisticated, customized solutions while saving time and money.

**Solutions by Audience:**
- For Novice Developers, FileBuild revolutionizes backend interaction by converting complex blockchain operations into user-friendly API calls, paired with an intuitive interface. This approach demystifies blockchain technology, allowing beginners to focus on creative aspects without delving into the technicalities, thus making Dapp development accessible and less intimidating.
- For Advanced Developers, FileBuild offers an array of advanced features and customization options. It provides the necessary tools to build bespoke, sophisticated Dapp functionalities efficiently. This flexibility caters to the nuanced needs of experienced developers, enabling them to create complex Dapps with enhanced efficiency and precision.
- For All Users, FileBuild streamlines the entire Dapp development process, offering straightforward frontend development tools, including pre-built templates and intuitive design elements. It ensures a seamless integration of frontend ease with powerful backend capabilities, delivering a comprehensive development experience that caters to users of all skill levels. 

**Benefits of FileBuild:**

FileBuild offers a comprehensive suite of benefits, transcending the traditional limitations of no-code platforms : 
- Ease of Use: By turning complex blockchain interactions into user-friendly workflows, it opens up Dapp development to a wider audience.
- Customizability: The plugin provides a range of API calls and interfaces to Filecoin functions, catering to the nuanced needs of experienced developers.
- Efficiency in Development: Reducing the time and effort required for both backend and frontend development, FileBuild accelerates the Dapp creation process.
- Enhanced User Experience: With a focus on intuitive design elements and templates, the plugin ensures that the end-users have a seamless experience when engaging with the Dapps. 

**How It Works and Its Use of Filecoin:**

FileBuild leverages the capabilities of Filecoin through a combination of Curl JSON-API calls and pre-configured workflow templates. It transforms complex blockchain actions, like smart contract operations and token transactions, into simpler, manageable API calls. These are smoothly integrated into Bubble.io’s no-code environment, making it possible for both technical and non-technical users to efficiently create and manage Dapps on FileBuild . 
For a deeper insight into the architecture and technical workings of FileBuild, please refer to the accompanying architecture document present on the next page : 
[Link here](https://www.canva.com/design/DAF5kZQgNp0/U4CjksrOwXkbmihcK2XgEw/view?utm_content=DAF5kZQgNp0&utm_campaign=designshare&utm_medium=link&utm_source=editor
)

## Impact 

The FileBuild project addresses crucial pain points in blockchain development: the high technical complexity and specialized knowledge required to create decentralized applications (Dapps). This steep learning curve significantly restricts the diversity and innovation within the Filecoin and IPFS ecosystems. By offering a simplified, no-code approach, the project aims to make Dapp development more accessible, enabling a wider range of people to participate and contribute to these ecosystems. This democratization of technology is essential for fostering a richer, more varied development landscape. The project also addresses pain points for advanced developers, such as inefficiencies in existing development processes and the high costs associated with current Dapp-building solutions. This project aims to streamline the development workflow, saving time and resources for experienced developers. Additionally, it seeks to reduce the financial burden for many project builders who currently face significant expenses with the available tools and platforms. This approach not only benefits newcomers but also enhances the efficiency and cost-effectiveness for seasoned professionals in the blockchain development community.

Implementing this project would democratize blockchain development, fostering a surge in creative and diverse Dapp development. It would make development more efficient for seasoned developers and reduce costs for numerous projects in the Filecoin ecosystem. This would accelerate the growth and utilization of the Filecoin and IPFS networks. On the other side, risks of not developing this project is that the existing complexity will continue to deter potential innovators, leading to a slowdown in the ecosystem's evolution and diversity. While there are inherent risks in any project, the potential benefits far outweigh the risks, as even partial success would provide valuable insights and tools for the community. 

What success would look like: The project aims to help launch 10 new Dapps in the first year, given the actual number of [80](https://filscan.io/en/fvm/) in the ecosystem, attract over 20 developers (on the basis where each project would attract two new devs), and create 5,000 new unique wallets. This goal represents a substantial expansion in the user base and innovation within the Filecoin ecosystem. These achievements would significantly enhance the ecosystem's robustness and diversity, aligning with the capabilities of the Filecoin Virtual Machine (FVM).

## Outcomes

Concretely, the final outcomes and deliverables for the FileBuild project will include:
- **Filecoin API Calls to Bubble.io Actions:** Developing 10 key Filecoin API calls into Bubble.io workflow actions.
- **Workflow Templates for Operations:** Creating 15 workflow templates focused on general operations like transactions, account management, and smart contract interactions.
- **Comprehensive Documentation:** Providing in-depth documentation on blockchain fundamentals, integration with Bubble.io, and step-by-step user guides for these integrations.

The technical success of the project will be measured primarily by previously stated development metrics. 
Additionally, feedback and adoption rates among users will serve as key indicators of success, providing insight into the practical impact and acceptance of the tools within the community.

## Adoption, Reach, and Growth Strategies

Concerning target users, I have detailed who the plugin serves in a precedent part of our application file. More precisely, here are our different target users:
- **No-code Developers:** Individuals or teams looking to build blockchain applications without extensive coding knowledge.
- **Advanced Developers:** Enables experienced programmers to efficiently build sophisticated blockchain applications, leveraging advanced features for enhanced functionality.
- **Small and Medium Enterprises (SMEs):** Businesses seeking to integrate blockchain technology into their operations without significant investment in specialized blockchain development teams.
- **Educational Institutions:** Educators and students who use the plugin as a learning tool for blockchain technology and application development.
- **Blockchain Enthusiasts:** Individuals interested in creating DApps for personal use or to understand blockchain technology better.
- **Innovation Labs:** Research and development groups exploring blockchain's potential for new use cases.

Concerning how large our audience is, we can look at Bubbl.io’s number of users. Since 2021, the user base of Bubble.io has been growing exponentially from 950 000 users this same year to 3 000 000 in 2023. This surge is a testament to the rising demand for accessible, no-code development platforms. FileBuild taps into this growing community, offering a seamless bridge to the world of blockchain. 

To onboard new users, here is our strategy: 

**Ecosystem Growth Strategy:**
- Target Audience Engagement: Initiatives include engaging no-code development communities, utilizing social media channels, and participating in tech and entrepreneurship forums.
- Educational Collaborations and Content: Collaborations with educational platforms for workshops and tutorials to demonstrate the utility of FileBuild in no-code blockchain development.
- Hackathons and Developer Forums: Active participation in these events to demonstrate FileBuild's capabilities and to foster a community of users and developers.

**Partnerships:**
- Bubble.io: Currently in talks with Bubble.io to become an official partner for blockchain development. This partnership aims to integrate FileBuild directly into Bubble's platform, offering a seamless experience for no-code blockchain application development.
- Filecoin Blockchain: Actively seeking to become official partners with Filecoin Blockchain, which would enable deeper integration and utilization of their unique features like multiparty computation, enhancing FileBuild's capabilities.

## Development Roadmap

**M1: API Integration and Basic Workflow Templates**

**Brief Description:** Implement fundamental Filecoin blockchain operations through API calls and create standard workflow templates.
**Completion Measure:** Successful implementation of five essential Filecoin blockchain operations as modular workflow actions in Bubble.io. These actions will allow users to easily perform basic operations such as wallet connections and simple transactions. These will be published with our documentation on our Github repo. 
**Number of people:** 4 
**Estimated Date of Completion:** February 25, 2024.
**Budget:** $9,900.

<br> 

**M2: Advanced Smart Contract Features**

**Brief Description:** Develop advanced smart contract capabilities, including custom contract templates.
**Completion Measure:** Develop a suite of 10 advanced smart contract workflow templates for complex blockchain applications. These templates will enable developers to deploy and interact with sophisticated smart contracts within their Dapps. Documentation on our Github repo. 
**Number of people:** 4
**Estimated Date of Completion:** March 8, 2024.
**Budget:** $14,200.

<br> 

**M3: Comprehensive DevX Design**

**Brief Description:** Design a comprehensive and user-friendly plugin interface for both novice and advanced developers.
**Completion Measure:** A fully developed UI/UX plugin prototype, having undergone testing by ecosystem developers, with adaptations made based on their feedback. This process will ensure the interface's ease of use and functionality for both novice and advanced developers. 
**Number of people:** 3 
**Estimated Date of Completion:** March 22, 2024.
**Budget:** $8,700.

<br> 

**M4: Security Enhancements and Wallet Integration**

**Brief Description:** Enhance security features and integrate wallet connectivity options.
**Completion Measure:** Successful integration of two major wallet services and passing of a security audit that checks for vulnerabilities and secure transaction handling. Documentation on our Github repo. The plugin will then be published in the Bubbl.io library. 
**Number of people:** 3
**Estimated Date of Completion:** April 8, 2024.
**Budget:** $7,100.

## Total Budget Requested

`$39.900` 

## Maintenance and Upgrade Plans

Concerning our business model post-launch, the plan includes:
- **Subscription Model:** Implementing a subscription-based service for access to advanced features and templates.
- **Freemium Offerings:** Offering basic functionalities for free to attract users and upsell premium features.
- **Community Support and Services:** Providing support and additional services to the developer community for enhanced engagement and revenue generation.
- **Partnerships and Collaborations:** Forming strategic partnerships to expand reach and capabilities.
- **Continuous Product Development:** Reinvesting profits into product development for sustained growth and innovation.

For long-term maintenance and improvement of the project, the following strategies are planned:
- **Feature Enhancements:** Regularly adding new features to enhance user experience and functionality.
- **Integrating New API Calls:** Continuously updating the platform to include new API calls from Filecoin.
- **Adapting to Filecoin Updates:** Ensuring the plugin remains compatible with the latest Filecoin updates.
- **Expanding Workflow Templates:** Creating new templates for a wider range of operations and applications.
- **Community and Ecosystem Engagement:** Actively engaging with the developer community for feedback and contribution.

Our long-term plans are strategically designed to ensure that we remain at the forefront of no-code blockchain development. Our goal is to continuously innovate and adapt, solidifying our position as the reference point in this rapidly evolving field. This commitment to excellence and innovation underpins all aspects of our project's development and growth strategy.

# Team

## Team Members

**1) Barth Houot - CEO of FileBuild**

Barth Houot is a product of Icam engineering school where he acquired a robust foundation in general engineering and development. Complementing this is his advanced business acumen from CentraleSupélec and ESSEC Business School, creating a blend of engineering prowess and strategic insight.

With practical experience in product development and continuous improvement from his time at Wipak and PowerOfMoss, Barth is now channeling his lifelong fervor for technology into the dynamic realm of web3 and blockchain as the driving force behind FileBuild. 

His three-year living in the United States expanded his horizons, blending international expertise with his innate enthusiasm for innovation.

**2) Enzo Soyer - COO of FileBuild**

Enzo is an alumnus of ESSEC Business School, one of Europe's most prestigious business schools, and Centrale Supélec, one of France's top engineering schools. He has a well-rounded international background, with studies in Denmark, Singapore and France.

Professionally, he was the CEO of Tenk, a pioneering Web 3 development studio. Under his leadership, Tenk has launched innovative solutions such as the open source standard for launching generative NFT collections on Near protocol, and Smart Deploy, a comprehensive SDK/CLI and Dapp designed to streamline the management of smart contracts on Soroban/Stellar.

His expertise in the blockchain sector is augmented by a significant tenure at Brave Software, where he delved into the intricacies of search engine technology. Enzo's diverse experience is further complemented by his tenure at Thales Alenia Space, a leader in Europe's satellite manufacturing industry. His journey reflects a blend of technological innovation and international business acumen.

**3) Gabriel Benillouche - CTO of FileBuild**

With a rich foundation in IT and blockchain development from EPITA, Gabriel Benillouche has solidified his role as a technological visionary at BearingPoint. 

His journey through the digital terrain is marked by a transformative internship in Tel-Aviv, where he expanded his blockchain development expertise. 

Gabriel's arsenal includes proficiency in Rust, Java, Solidity, Python, and C, which are critical to architecting the robust backend of FileBuild's decentralized applications.

**4) Arthur Kieffer - Bubble.io plugin Developer at FileBuild**

Arthur Kieffer's journey through the no-code revolution is anchored in his educational experiences at École Cube and ESSEC Business School, coupled with a hands-on role as an Electronics Engineer at Etix Labs. 

As a co-founder of Cube, he has been pivotal in crafting bespoke web applications using Bubble technology, establishing him as a leading figure in the no-code community. His unique blend of technical and pedagogical expertise is central to developing FileBuild's intuitive user interface, empowering users to deploy Dapps with ease. 

## Team Member LinkedIn Profiles

Barth: [LinkedIn](https://www.linkedin.com/in/barth%C3%A9lemy-houot-64baa019b/) 
Enzo: [Linkedin](https://www.linkedin.com/in/enzo-soyer/)
Gabriel: [LinkedIn](https://www.linkedin.com/in/gbenillouche/)
Arthur: [LinkedIn](https://www.linkedin.com/in/arthur-kieffer/)
## Team Website

`https://adapptable.dev/` 

## Relevant Experience

**The FileBuild team: A Convergence of Vision, Expertise, and Innovation**

Our team at FileBuild is strategically assembled to tackle the intricacies of blockchain application development. Barth's strategic foresight, Gabriel's technical prowess, and Arthur's innovative approach to no-code development create a triumvirate poised to revolutionize the blockchain space. Their combined experiences across different sectors of technology and business ensure that FileBuild is not just a tool, but a comprehensive ecosystem that simplifies, secures, and accelerates the deployment of decentralized applications on the Filecoin blockchain.

**Team’s relevant experiences / track records**

The FileBuild team embodies a fusion of distinct yet complementary expertise, essential for the groundbreaking nature of our project. Gabriel Benillouche's experience in blockchain development underpins the technical foundation of FileBuild. His hands-on approach to crafting blockchain solutions ensures the technical robustness necessary for simplifying complex blockchain processes.

Complementing this, Enzo Soyer brings a track record of remarkable achievements in open-source projects. Under his stewardship at Tenk, the open-source standard for launching NFT collections on the Near protocol now commands usage by over 90% of NFT projects in the ecosystem, showcasing the real-world impact and acceptance of his work. Furthermore, Smart Deploy, a standout project from his tenure, emerges as one of the first functioning Dapps on the Soroban testnet. Its ongoing integration by various projects testifies to its utility and innovation in the blockchain space.

Arthur Kieffer’s expertise in converting SDKs into user-friendly Bubble.io plugins is pivotal. His ability to translate complex technology into accessible tools is directly aligned with FileBuild's mission. Arthur's knack for creating intuitive interfaces is not just about simplification; it's about empowering users to harness the full potential of decentralized applications with ease and efficiency.

This blend of Gabriel’s technical prowess in blockchain, Enzo's success in influential open-source projects, and Arthur’s skill in making technology accessible, forms a synergistic core for FileBuild. It's not just their individual experiences that set our team apart; it's how these experiences interlink to create a holistic approach to making blockchain technology accessible and adaptable for a wide range of users.

## Team code repositories

Links to precedent projects 

Smart Deploy, a Tenk studio product: [https://www.smartdeploy.dev/](https://www.smartdeploy.dev/)
Tenk open source NFT standard: [https://tenk.app/](https://tenk.app/)
AstroDao, a Tenk studio product: [https://astrodao.com/](https://astrodao.com/)
Cube, one of our collaborator's company in no-code plugin development: [https://en.cube.fr/](https://en.cube.fr/)

# Additional Information

E-mail: barthelemy.houot@gmail.com 

**Other Links:** 
- Pitch deck: [https://www.canva.com/design/DAF5kZGJPRY/YB9w8s1CGKnWAiR8PJQWsw/view?utm_content=DAF5kZGJPRY&utm_campaign=designshare&utm_medium=link&utm_source=editor](https://www.canva.com/design/DAF5kZGJPRY/YB9w8s1CGKnWAiR8PJQWsw/view?utm_content=DAF5kZGJPRY&utm_campaign=designshare&utm_medium=link&utm_source=editor) 
- Twitter: [https://twitter.com/AdapptableDev](https://twitter.com/AdapptableDev) 
- LinkedIn: [https://www.linkedin.com/company/adapptabledev](https://www.linkedin.com/company/adapptabledev)

**Comment by ErinOCon** [comment]
Hi @AdapptableDev, thank you for your proposal! We are wrapping up the preliminary review for this wave and will have an update available shortly. 

Thank you for your patience!

**Comment by ErinOCon** [comment]
Hi @AdapptableDev, thank you again for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!

Please contact our team at [grants@fil.org](mailto:grants@fil.org) with any questions regarding our grants program.
