### ISSUE TITLE
Open Grant Proposal: ZAG NETWORK

### ISSUE THREAD

**Issue by vandoornjoost** [filecoin-project/devgrants#1688]
Open Grant Proposal: ZAG NETWORK

Project Name: ZAG Network.

Proposal Category: Applications & Integrations.

Individual or Entity Name: This proposal is on behalf of ZAG Network.

Proposer: zag-net

Technical Sponsor: N/A

Do you agree to open source all work you do on behalf of this RFP and dual license under MIT, APACHE2, or GPL licenses: Yes

Project Summary:
ZAG Network is a Web3 decentralized social network platform built on the Polygon (Matic) blockchain, providing a fast and secure layer 2 Ethereum virtual machine and smart contracts. It aims to revolutionize social networks for professionals by driving user interactions with ZAG tokens, Soul-Bound NFT and peer-to-peer services and data sovereignty.

First, data sovereignty creates a more secure internet whereby the content creators own their own data. Centralized storage platforms benefit advertisement companies and attackers, not content creators. I.e., YouTube channel takedowns, Tik Tok & WeChat bans, User data hacks are all examples of issues that decrease drastically in decentralized platforms. We need a decentralized storage platform through File coin services and standardize the format of social media data to show all posts in one feed. We standardize access control to this data, to give back full control to the content creator.

Second, the field of Social Media requires large amounts of storage. Social Media databases will over time reach hundreds of petabytes and only a fraction of that would require large numbers of GB’s/TB’s. As a result, centralised cloud services such as AWS, GCP and Azure are expensive and can be difficult to use. Decentralised storage solutions have the potential to vastly reduce the costs incurred by platforms such as ZAG Network which over time.

Impact:
What pain points does this project seek to address:
•	A migration away from centralized storage providers significantly reducing monthly OPEX.
•	Over reliance on “too big to fail” companies such as Microsoft, Amazon or Google. This issue becomes bigger over time. With the increase of storage requirements, the harder it becomes to migrate out of their platforms. 

What are the benefits to getting this right:
•	By migrating away from centralized platforms in to File coin we remove another centralized component in a web3 platform increasing our decentralization level.
•	Early migration allows us to migrate out of centralized storage platform at relative low costs.
•	Adoption of File coin provides greater protection to malicious attackers due to its decentralized nature.

What are the risks of not getting this right:
•	Inappropriately designed architecture, implementation and migration could lead to large scale disruptions down the road when we start to scale up.

What impact will this project have in a specific vertical market, or ecosystem:
•	We aim to disrupt the social media landscape by showing that a platform does not have to be centralized. Including File coin in the overall architecture increases the business case of decentralization, data sovereignty, ownership and control.

What does success look like:
•	A successful implementation and migration of the current ZAG platform will have its complete database architecture migrated to File coin.
•	The user experience is not negatively impacted.
•	OPEX is reduced significantly.

Outcomes:

The primary objective of this project is to seamlessly integrate Filecoin, a decentralized file storage platform, into the Zag Network data storage system. The integration aims to enhance data security, decentralize storage, and provide a more robust and efficient experience for Zag Network users.

Final Outcomes and Deliverables:
1.	Secure Filecoin Integration Architecture Documentation:
•	Outcome: Comprehensive documentation outlining the secure architecture designed for integrating Filecoin into Zag Network.
•	Purpose: This document will serve as a blueprint for the entire integration process, providing insights into the architecture, encryption mechanisms, and data protection measures.

2.	Encrypted and Integrated Filecoin File IDs in the Database:
•	Outcome: Successful implementation and integration of encryption mechanisms for Filecoin file IDs within Zag Network's database.
•	Purpose: Ensure that user data, including images and videos, is securely stored and retrieved using encrypted Filecoin file IDs, enhancing overall data security.

3.	User Data Successfully Migrated and Stored on Filecoin:
•	Outcome: Completion of the migration process, transferring existing user data, images, and videos to the Filecoin storage network.
•	Purpose: Users' data will now benefit from the decentralized and incentivized storage provided by Filecoin, contributing to improved reliability and availability.

4.	Completed Security Audits, Educational Materials, and User Notifications:
•	Outcome: A comprehensive security audit report, user-friendly educational materials, and user notifications about enhanced data security measures.
•	Purpose: Provide users with a transparent view of the security measures in place, empowering them with the knowledge to manage their data security effectively.

5.	Enhanced User Interface with Filecoin Integration Features:
•	Outcome: An updated user interface within Zag Network, showcasing features related to Filecoin integration, such as storage status, security settings, and data access notifications.
•	Purpose: Enhance user experience by providing clear visibility into the benefits and security features associated with Filecoin integration.

6.	Documentation and Training Materials:
•	Outcome: User-friendly documentation and training materials for Zag Network administrators and users.
•	Purpose: Enable administrators to manage and maintain the integrated system effectively and empower users to understand and utilize the new features seamlessly.

Functionality of the Integrated Software: 

Upon completion, the integrated software will deliver the following functionalities:

•	Decentralized Storage: Users' data, including images and videos, will be securely stored on the Filecoin network, promoting decentralization and resilience.
•	Encrypted File IDs: Enhanced security using encrypted Filecoin file IDs, ensuring the privacy and integrity of user data.
•	User Education: Users will have access to educational materials and notifications, fostering awareness about the benefits of Filecoin integration and the security measures in place.
•	User Interface Enhancements: The user interface will be updated to include Filecoin-related features, providing a seamless and intuitive experience for users.
•	Transparent Security Measures: Security audits and notifications will provide transparency, assuring users of the rigorous security measures implemented to protect their data.

Success Metrics

The success metrics encompass various aspects of the integration, focusing on functionality, security, user engagement, and overall system health.

1.	Data Security Metrics:
•	Encryption Effectiveness: Measure the success of the encryption mechanisms by assessing the strength and resilience against potential threats.
•	Incident Reports: Monitor and record any security incidents or breaches, aiming for zero incidents during and after the integration.
2.	System Performance Metrics:
•	Data Retrieval Speed: Evaluate the speed at which user data can be retrieved from Filecoin storage, aiming for optimal performance.
•	System Downtime: Minimize system downtime during the integration and subsequent operation, ensuring high availability.
3.	User Engagement Metrics:
•	User Adoption Rate: Track the number of users actively utilizing the new features and Filecoin-integrated functionalities.
•	Educational Material Engagement: Measure user engagement with educational materials to gauge the effectiveness of user awareness campaigns.
4.	Decentralization Metrics:
•	Filecoin Storage Utilization: Monitor the percentage of user data migrated and stored on the Filecoin network, aiming for a substantial shift toward decentralized storage.
•	Incentivized Participation: Assess the participation of users in contributing storage resources to Filecoin, encouraging decentralization.

Adoption, Reach & Growth Strategies:
•	Initial Focus: Crypto Blockchain and AI Communities. To accelerate adoption, ZAG Network focuses its onboarding activities on the crypto blockchain and artificial intelligence communities. These technology-savvy communities are more likely to be comfortable with digital tokens and digital wallets, facilitating the platform's early adoption. 
•	Geographical Focus: Asia, Europe, and America. ZAG Network's initial market activities are concentrated in Asia, particularly Singapore, Hong Kong, India, Vietnam, Philippines and Indonesia. Once significant market share is captured in Asia, the focus will expand to other populous Asian countries, followed by Europe and America. 
•	Capturing Market Share in Key Asian Countries. After establishing a significant presence in the initial target countries, ZAG Network will target other large population Asian countries, such as Malaysia, Japan, and South Korea. This phased approach allows for gradual expansion and growth. 
•	Targeting Europe and America. Once ZAG Network achieves significant market share in Asia, the company plans to expand its focus to Europe and America. These regions offer vast user bases and diverse business ecosystems, providing opportunities for further growth and global reach. 

Development Roadmap:

Milestone 1: Foundation
Objective: Design a secure architecture for integrating Filecoin into Zag Network's data storage system.
The primary goal for this milestone is to ensure the privacy and security of user data while harnessing the benefits of Filecoin's decentralized storage.

Tasks:
•	Research and Best Practices:
Dive into comprehensive research to understand the best practices for Filecoin integration within similar platforms.
Explore successful case studies to glean insights and lessons learned from past implementations.
•	System Architecture Design:
Collaborate with our architecture team to craft a scalable and secure system design tailored to Zag Network's unique requirements.
Ensure that the architecture facilitates the seamless interaction between Zag Network's database and the decentralized storage capabilities of Filecoin.
•	Encryption and Protection Measures:
Develop a detailed plan outlining encryption methodologies to safeguard Filecoin file IDs.
Propose robust protection measures to shield user data from potential vulnerabilities or unauthorized access.

Deliverable: Documented Secure Integration Architecture

Upon completion of this milestone, we anticipate having a comprehensive document that serves as our guide – a blueprint for the secure integration of Filecoin into Zag Network. This document will not only showcase the architectural design but will also provide a clear roadmap for subsequent tasks. It is a crucial step towards realizing our vision of a secure, decentralized, and efficient data storage system.

Timelines: 2 weeks

Milestone 2: Fortifying Data Security and Database Harmony
Objective: Implement encryption mechanisms for Filecoin file IDs and integrate them into Zag Network's database.
The next milestone is fortifying data security and ensuring seamless integration with our database. This step is crucial to guaranteeing the confidentiality and integrity of user data throughout the process.
Tasks:
•	Encryption Mechanisms Development:
•	Robust encryption mechanisms for persisting filecoin file IDs.
•	Ensure that the encryption methods align with industry standards and provide a formidable defense against potential threats.
•	Integration with Zag Network's Database:
•	Establish a streamlined integration process for Filecoin file IDs with Zag centralised and decentralised infrastructures.
•	Develop microservice that facilitate the secure storage and retrieval of encrypted file IDs within our existing database structure.
•	Thorough Testing and Quality Assurance:
•	Conduct extensive testing to validate the effectiveness of the encryption mechanisms and the smooth integration with Zag Network's database.
•	Address any potential issues promptly to guarantee a seamless and secure user experience.

Deliverable: Encrypted and Integrated Filecoin File IDs in the Database
At the completion of this milestone, our expectation is to have successfully implemented and tested the encryption mechanisms for Filecoin file IDs, seamlessly integrated them into our database, and ensured the cohesiveness of the entire system. This achievement not only contributes to the security of user data but also sets the stage for subsequent milestones in our Filecoin integration journey.
Timelines: 4 weeks

Milestone 3: Elevating User Data Migration and Filecoin Storage Experience
Objective: Migrate existing user data, images, and videos to Filecoin storage while maintaining security.
Next milestone is migrating existing user data, images, and videos to Filecoin storage. This critical step aims to offer our users a more secure and resilient data storage experience while leveraging the decentralized capabilities of Filecoin.
Tasks:
•	Strategic Data Migration Plan:
•	Formulate a meticulous data migration plan that outlines the step-by-step process for transitioning existing user data to the Filecoin storage network.
•	Prioritize a user-centric approach to minimize disruptions and ensure a seamless experience during the migration.
•	Implementation of Filecoin Storage:
•	Implement the necessary procedures to persist user data securely on the Filecoin storage network.
•	Verify the functionality of the integration to guarantee that user data is efficiently stored and retrievable from Filecoin.
•	Thorough Testing and Quality Assurance:
•	Conduct extensive testing of the migration process to identify and rectify any potential challenges or anomalies.
•	Ensure that data retrieval from Filecoin storage is both efficient and secure.

Deliverable: User Data Successfully Migrated and Stored on Filecoin
The successful completion of this milestone will mark a pivotal moment in Zag Network's commitment to data security and decentralization. Users will benefit from a storage solution that not only ensures the integrity of their data but also harnesses the power of Filecoin's decentralized storage network.
Timelines: 2 weeks

Milestone 4: Safeguarding Security and Enhancing User Awareness
Objective: Conduct security audits to ensure the integrity of user data on Filecoin and educate users about enhanced data security.
The next milestone focused on safeguarding the security of user data on Filecoin and raising awareness among our users about the enhanced data security measures implemented.
Tasks:
•	Comprehensive Security Audits:
•	Engage security experts to conduct thorough audits of the Filecoin integration, identifying and mitigating potential vulnerabilities.
•	Implement any necessary security patches or improvements based on audit findings to fortify the overall security of user data.
•	Educational Materials Creation:
•	Develop user-friendly educational materials outlining the benefits of enhanced data security on Filecoin.
•	Craft notifications and guides to inform users about the security measures in place, reassuring them of the protection of their data.
•	User-Facing Security Features:
•	Implement user-facing security features such as notifications for data access, alerts for suspicious activities, and an accessible overview of data security settings.
•	Ensure that users have clear visibility into how their data is protected and how they can actively manage their security preferences.

Deliverable: Completed Security Audits, Educational Materials, and User Notifications

At the successful completion of this milestone, Zag Network will stand as a beacon of trust, offering users not only the advantages of decentralized storage through Filecoin but also a heightened awareness and control over the security of their data. The delivery of security audits, educational materials, and user notifications will contribute to a secure and informed user community.

Timelines: 3 weeks

 
Total Budget Requested:

![image](https://github.com/filecoin-project/devgrants/assets/107173327/e1e9f65d-7d59-4fe2-b8d2-81e5d036b829)

Total amount approx. 97K USD. The picture above provides a breakdown, but it is unclear to me whether that is accessible for you.

Maintenance and Upgrade Plans:
As we continue to grow the platform we will always be enhancing and developing new features. At the same time when critical mass is achieved a to be formed new IT team will be put in to place for maintenance & support. The size and location of this team highly depends on several factors such as the rate of growth, the location of expertise, political climate and the locality of most of our user base. This has yet to be determined.

Team:
Founders:
Steve Pang CEO (https://www.linkedin.com/in/stevexzag/)
Business Leader with over 20 years of executive search/recruitment experience across Asia Pacific. Advisor on various Human Resource technology (HR data analytics and payroll management), and blockchain projects. Been in crypto/blockchain since mid-2017.

Sasha Joshri CMO (https://www.linkedin.com/in/sashaxzag/)
Millennial female tech entrepreneur, experienced regional FinTech talent management consultant and a four-time startup founder. Published author, sales and marketing expert with a flair in C-suite level and investor relations management.

Joost van Doorn CTO (https://www.linkedin.com/in/joostvandoorn/)
Senior Technology Leader with over 20 years of experience in Banking across Asia Pacific and the EU. Web3/Crypto enthusiast and Investor/Advisor in various blockchain and clean energy projects since 2017.

Advisors
Parag (https://www.linkedin.com/in/paragarora/)
15 years of technology entrepreneurship experience. He was awarded as 25 under 25 Member by Entrepreneur.com, a founding member of the decentralized entertainment platform Xfinite.io, and cofounder of YCombinator-backed tech startup Glowing.io. Parag also started a consumer texting platform Plustxt back in 2011 which, later he sold to the largest fintech wallet platform in India - Paytm.

David (https://www.linkedin.com/in/david-maneval/)
With opportunities come risks, and David has dedicated over 20 years to risk management. His expertise lies in assisting insurance companies and corporations in understanding and mitigating the risks they face. ZAG can leverage this expertise to safeguard its upside potential. David prefers to maintain anonymity, and we fully respect his preference.

Tham (https://www.linkedin.com/in/tze-kin-tham-b316108a/)
Accomplished leader with over 20 years of experience in Financial Institutions Worldwide and 6 years of Audit. Prior role engaged as Managing Director of SWIFT Business and Technology, Malaysia. Astute in financial analysis, liquidity and capital management and most banking disciplines. Fellow Certified Practicing Accountant in Australia and Malaysia.

Evans (https://www.linkedin.com/in/evans-oyama-b-eng-zag-advisor-7049991b7/)
An accomplished electrical/electronic engineer, community manager, project builder, and trusted advisor. With a strong drive, adaptability, and a sense of responsibility, I bring a wealth of experience to the table. My journey in the Crypto/NFT space since 2020 has allowed me to delve into the world of blockchain projects, making me well-equipped to tackle challenges and drive innovation.

Liam (https://www.linkedin.com/in/liam-reynolds-b6412a93/)
Experienced engineer with over 10 years in design consultancy specializing in critical systems. A recent crypto and web3 enthusiast having been obsessed with the space since 2021.

## Team Website

https://www.zag.network/

Relevant Experience:

Meet Steve, CEO & Co-Founder 
A visionary in the world of Web3 and a co-founder of ZAG NETWORK (www.zag.network), a revolutionary Social-Fi Network Project. With a multifaceted background that spans leadership, career advising, coaching, vlogging, and authorship
Having spent over two decades as a seasoned business leader in executive search and recruitment across the dynamic Asia Pacific region. With 8 years of working experience and living in Australia, 5 years in Japan, and 15 plus years in Singapore, Steve's understanding of diverse markets and cultures across Asia Pacific makes him stand out from the pack. As a
As a co-founder and advisor on Web3 ventures, Steve has been actively engaged in the Web3 space since June 2017. His passion for the transformative potential of Web3 technology and the decentralized movement is evident.
Beyond his entrepreneurial endeavors, Steve is a natural and direct communicator. Through his regular vlogs on socials, he shares insights and knowledge gained from his diverse experiences, touching on topics ranging from leadership to career development and everything in between. As an author, Steve has penned two highly regarded books: "Everything You Wish to Ask A Headhunter" and "ZAG's Expert Guide to Personal Branding & Job Seeking." These literary accomplishments further showcase his dedication to empowering individuals to navigate their professional paths with confidence and success.
With a dynamic mix of high energy passion, innovation, and an unyielding commitment to personal and professional growth, Steve continues to shape the future while inspiring others to do the same.

Meet Sasha, CMO & Co-Founder 
Sasha Josri, an influential millennial techpreneur and Senior Consultant specializing in Maritime and Commercial Shipping (Dry Bulk) throughout the dynamic APAC region. Fueled by an unwavering commitment to delivering transformative outcomes, Sasha thrives on cultivating meaningful connections, fostering team growth, and turning ambitious visions into reality.

At the helm of ZAG Network, Sasha stands as the Co-Founder steering a revolutionary Web3 decentralized social network platform on the Arbitrum (ARB) blockchain. Simultaneously, as the Co-Founder of Rise wolves, Sasha embodies a serial entrepreneurial spirit, leading an algorithmic FX and Crypto trading platform.

Venturing boldly into the crypto space, Sasha orchestrated the successful launch of barkclub.io, an avant-garde Multi-utility NFT x Metaverse project based in Singapore. Beyond her groundbreaking initiatives, Sasha is also a published author, captivating readers with her recent eBook, "ZAG's Expert Guide on Personal Branding & Job Seeking." This follows her debut in 2019 with "Midnight Sun," a captivating collection of poetry and prose.

A distinguished global alumna of the European Innovation Academy (EIA), Sasha remains an active force in the tech startup realm as a participant in BGI (Portugal), a world-class deep tech startup accelerator. Committed to fostering diversity and inclusion, Sasha contributes significantly to the Women’s International Shipping and Trading Association (WISTA), showcasing her dedication to driving positive change in both tech and maritime industries. Sasha Josri embodies the essence of a visionary leader, leaving an indelible mark on the intersection of technology, entrepreneurship, and global impact.

Meet Joost, CTO & Co-Founder
A highly skilled senior IT executive, Joost has a wealth of experience in the financial industry, specializing in successfully delivering complex IT solutions both in BAU as well as in project mode. His expertise lies in seamlessly integrating technology solutions into the financial landscape, considering both the operational and regulatory requirements. He possesses exceptional leadership abilities and a strategic mindset, aligning technology initiatives with overarching business goals.
Key Skills:
Team Leadership: With extensive experience leading cross-functional teams, he excels in motivating individuals and fostering a collaborative work environment. He has a proven ability to manage diverse teams, facilitate communication, and drive high-performance outcomes.
Project Management: Proficient in managing end-to-end IT projects, ensuring adherence to project objectives, scope, budget, and timeline. Joost’s skills encompass project planning, risk management, resource allocation, and effective stakeholder communication.
Technology Integration: Proficiency in integrating IT systems and solutions into the financial industry ensures compliance with security standards and regulatory guidelines. Joost is skilled at evaluating and selecting appropriate technologies and vendors to optimize operations and enhance business processes.
Risk Management: Possesses strong expertise in identifying and mitigating operational and project risks, including technology-related risks, security vulnerabilities, and compliance issues. His proactive approach to risk assessment, contingency planning, and problem-solving ensures smooth project execution.
Communication and Stakeholder Management: Possesses excellent interpersonal and communication skills, enabling Joost to effectively convey complex technical concepts to non-technical stakeholders. He is adept at building and maintaining relationships with key stakeholders, including executives, clients, vendors, and regulatory bodies.
Advisor to Web3 Start-ups:
As an Advisor to Web3 start-ups Joost brings a wealth of experience and knowledge in the Web3 ecosystem. He has a proven track record of guiding and supporting start-ups in leveraging blockchain technology and building decentralized applications. His expertise lies in understanding Web3 protocols, smart contracts, decentralized finance (DeFi), non-fungible tokens (NFTs), and other emerging trends within the decentralized space.
With a unique blend of technical expertise and business acumen, he helps start-ups navigate the complexities of the Web3 landscape. He possesses a comprehensive understanding of blockchain fundamentals, consensus mechanisms, and decentralized governance models, allowing him to provide strategic guidance on project architecture, tokenomics, and community engagement.
Joost's expertise extends beyond technical aspects, as he possesses a solid understanding of market dynamics and user adoption challenges within the Web3 space. By analyzing market trends, user behavior, and competitive landscapes, He provides start-ups with actionable recommendations to refine their product-market fit, enhance user experience, and drive adoption.

Meet Parag, Technology & Engineering Advisor
Parag Arora has been working in the blockchain space for the last 7 years and has been recognized in Entrepreneur.com 35 under 35 listing. He has been part of the founding team at Xfinite.io - a decentralized entertainment ecosystem having millions of users and Turing Labs - a blockchain-based consulting agency that developed their in-house white labelled crypto exchange and token offering platform. Parag Arora cofounded Glowing.io - a Y-Combinator-backed cloud-based messaging solution. Before starting Glowing.io, Parag had started a consumer messaging app "Plustxt", which he sold to Paytm in 2013 which later did its largest IPO in India, of about USD 4 billion. Paytm is the largest consumer fintech app in India. Parag has done his graduation from IIT Delhi before starting his entrepreneurial journey.

Team Code Repositories:
1.	CoinVoting DAO tool to take decisions 
https://github.com/adopterscc/coinvoting-caas

2.	Adopters Infrastructure - User onboarding utilities built on Solidity https://github.com/adopterscc/infrastructure

3.	Verime Token Project - KYC over blockchain solution 
https://github.com/parag-arora/VRM

Additional Information:
We’ve learned about the grant program in the web3 community and through our own research.

The following email address can be used to discuss the grant agreement:

[joost@zag.network](mailto:joost@zag.network)

**Comment by ErinOCon** [comment]
Hi @vandoornjoost, thank you for your proposal! We are wrapping up the preliminary review for this wave and will have an update available shortly.

Thank you for your patience!
