### ISSUE TITLE
Education Ecosystem Open Grant Application  

### ISSUE THREAD

**Issue by ProjectManagaerEE** [filecoin-project/devgrants#1689]
# Open Grant Proposal: `Education Ecosystem Open Grant Application`

**Education Ecosystem**

**Proposal Category:** `Developer and data tooling`
**Education Ecosystem** Is the proposal on behalf of an individual, or an entity/organization? Please note that the agreement and any payments must be completed by the same entity, either individual or organization.

**Proposer:** `EducationEcosystem`

**Project Repo(s)** Please list Github repos used for this project work. 

**(Optional) Filecoin ecosystem affiliations:** `Please disclose any existing work relationships with organizations in the Protocol Labs Network, including Protocol Labs, Filecoin Foundation, Filecoin Foundation for the Decentralized Web, and any others.` 

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Please respond with "Yes" or "No".

# Project Summary

## Total Budget Requested
$100,000

Budget distribution:
40% on content creation
40% on content training and distribution
20% on Marketing

## Maintenance and Upgrade Plans

# Team

## Team code repositories

# Additional Information

**Comment by realChainLife** [comment]
@ProjectManagaerEE closing this issue since the proposal is incomplete. If this was an error, please let us know and we'll re-open this.
