### ISSUE TITLE
Next Step Microgrant: Saturn Observatory

### ISSUE THREAD

**Issue by 31z4** [filecoin-project/devgrants#1693]
### 1. What is your project, and what problem does it solve? (max 100 words)

The goal of this project is to increase the transparency of 🪐 Filecoin Saturn network.

We use historical data about the network gathered by 🌖 [Saturn Moonlet](https://github.com/cronian-tech/saturn-moonlet) to prepare and publish analytical reports on Saturn Observatory website every month.

Saturn Observatory compliments official tools like [Saturn Node Dashboard](https://dashboard.saturn.tech) and [Saturn Explorer](https://explorer.saturn.tech), aiming to provide better insights into the network state and performance.
### 2. Project links
  
Link to Github repo: https://github.com/cronian-tech/saturn-observatory
Link to demo or website: https://observatory.cronian.tech
License: MIT

### 3. a) How is IPFS, Filecoin, or related technology used in this project?

* Raw data that is used to generate the reports for Saturn Observatory [gets stored](https://gateway.ipfs.io/ipfs/bafybeibrmxyaolu226uqj3bv7qqjtjmmzugigsq6n3qzx74xpz2yt73yha) on IPFS and Filecoin using web3.storage.
* To perform the actual analysis we run a Bacalhau job that uses [DuckDB](http://duckdb.org) to execute a bunch of [SQL queries](https://github.com/cronian-tech/saturn-observatory/blob/main/analytics.sql) on the input CSV data that we previously pinned to IPFS.
* Moving forward, we're going to use Lilypad to run the analysis. We already made a couple of PRs ([one](https://github.com/bacalhau-project/lilypad-modicum/pull/80), [two](https://github.com/bacalhau-project/lilypad-docs/pull/9), [three](https://github.com/31z4/lilypad-duckdb)) with a custom DuckDB module. But, by the time of writing the module is not yet available on Lilypad testnet.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)

No, not directly. But it's going to use Lilypad which uses FVM.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | Improve website UX | Split to subpages, add navigation menu, handle CSV loading errors, etc. | 2 weeks | 
| 2.     | Accelerate CSV data using Saturn | We used to use Saturn browser client on the website, but replaced it with self hosting CSV when Saturn private beta launched. We're going to participate in private beta and use Saturn again on the website. | 2 days | 
| 3.     | Use Lilypad to generate reports | Implement custom DuckDB module for Lilypad. Replace Bacalhau with Lilypad for analytical computations. | 2 weeks | 
| 4.     | Auto generate reports every week | Setup GitHub actions to auto generate reports and publish them on the website every week. Right now the process is mostly manual and done every month. | 2 weeks | 
| 5.     | Implement new reports | Add new reports based on community feedback. E.g., top performing nodes, top growing regions, node churn, node health issues, etc. | 2 weeks | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes I do.  

### 6. Does your proposal comply with our Community Code of Conduct?

Yes it does.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: https://www.blog.encode.club/open-data-hack-powered-by-filecoin-prizewinners-and-summary-dcdf52059867 (Saturn and Lilypad bounties)
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  * Elisey Zanko, elisey.zanko@gmail.com, http://github.com/31z4, tech founder
* How did you learn about our microgrant program?
  * During a hackathon
* If your project was created as part of an event or hackathon:
  * What was the name of the event?
    * Open Data Hack
  * Please link to your hackathon submission
    * https://youtu.be/ErgUU7kwUro

**Comment by eshon** [comment]
Hi @31z4 - Are you still interested in working on this?

We'd like to accept it but would ask that you use [CoopHive](https://coophive.network/) which is a fork of Lilypad. They are currently finalizing deployment but recommend anyone planning to use CoopHive to start off by building Bacalhau jobs and making sure they run there: https://docs.bacalhau.org/getting-started/docker-workload-onboarding

**Comment by 31z4** [comment]
Hi @eshon yes I'm still interested in working on Saturn Observatory. Just a few comments from my side:
1. Yes I think it's definitely possible to adapt CoopHive instead of Lilypad. I'm already pretty familiar with building and running Bacalhau jobs.
2. I'm currently busy with another project that I'll finish by April. I'll be ready to start working on Saturn Observatory on April 10. Does that work for you?

**Comment by eshon** [comment]
That works!

**Comment by 31z4** [comment]
Awesome! What's our next steps?

**Comment by 31z4** [comment]
Sure, I'll be in touch.

**Comment by 31z4** [comment]
Hi @eshon as we agreed earlier I'm letting you know that I'm happy to start working on the project around April 10 ☺️

**Comment by ErinOCon** [comment]
Hi @31z4, thank you for the update! I have sent you an email with instructions regarding next steps. This issue has been closed, but please feel welcome to include project updates to this thread. 

If you have any follow up questions, please contact our team at grants@fil.org.
