### ISSUE TITLE
Filecoin Safe deployment

### ISSUE THREAD

**Issue by protofivan** [filecoin-project/devgrants#1694]
# Open Grant Proposal: `Safe (ex-Gnosis Safe Multisig) deployment to Filecoin network`
**Project Name: Safe (ex-Gnosis Safe)**
**Proposal Category:** `Integrations`
**Individual or Entity Name:** Protofire DAO
**Proposer:** `protofivan`
**(Optional) Filecoin ecosystem affiliations:**
1. Protofire is a part of FEVM journey as a member of GLIF infra team - the most popular Filecoin RPC -[ [hosting.glif.io](http://hosting.glif.io/)](http://hosting.glif.io/)  (also we provide the infrastructure for glif wallet and glif stacking)
2. CID checker: https://github.com/protofire/filecoin-CID-checker

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** "Yes"
# Project Summary
We propose a turnkey deployment of Safe (formerly Gnosis Safe) to Filecoin. As a result, we will publish and manage a web version of Filecoin Safe at a designated domain/sub-domain associated with Filecoin, supporting both mainnet and testnet networks.
In addition to the deployment, we offer a one-year support and maintenance service, extendable upon request. This service includes regular updates, incident resolution, and the introduction of new features such as Safe Apps, Modules, Toolings, and Connectors.
The entire codebase will be published in the Filecoin repository, making it accessible to the public.

What is Safe.
Safe (https://safe.global/) stands out as the most secure multisig wallet currently available for EVM-compatible blockchains, even earning the trust of notable figures like Vitalik Buterin, who uses it for personal funds across several networks. It is a smart contract wallet that requires a minimum number of signatures to approve a transaction before it can occur. This added layer of security helps to protect against the loss or theft of funds, attract institutional investors and subsequently increase network’s TVL.
Due to modular system, Safe functionality can be significantly extended, in accordance with business needs, what makes this solution not just a wallet, but complete financial platform for DAOs, blockchain companies, institutional investors and cautious individuals, managing $Millions of funds.
## Impact
We believe that deploying Safe will bring the following benefits to the Filecoin ecosystem: 
1) It will make it possible for some significant protocols (such as Chainlink and AAVE) and dApps to join the Filecoin ecosystem, as they rely on Safe contracts as a part of their infrastructure.
2) Filecoin Safe will enable institutional investors, organizations, and DAOs to manage their funds in a more secure and intelligent manner, ensuring a definite growth in the total number of valuable ecosystem participants. With an increased number of accounts securely holding $1M and more, the entire Filecoin ecosystem will progress towards maturity and enterprise readiness.
3) Safe offers fantastic flexibility in terms of functionality for users across all ranges, from individual developers to network governance. It includes Account Abstraction features (social recovery, fee payment relaying, etc.), DAO Tooling (Zodiac), tx building and batching. The mere presence of Safe will enhance the quality of UX, with an indisputable improvement in safety for all participants, especially for Web2 newcomers. That will significantly propel Filecoin ecosystem growth.

## Outcomes
Safe utilization by the Filecoin community, DAOs, and protocols is our main success criteria. Such indicators as total TVL, number of active accounts (safes), and average amounts per safe are our main metrics. 
## Adoption, Reach, and Growth Strategies
Safe is a well-known, intuitive, and standard de-facto multisig solution across EVM networks. To achieve mass adoption and high utilization, we are focusing on raising awareness of the possibility of using Safe on the Filecoin network. Our plan is to help organizations (DAOs, Protocols, dApps) unlock the full potential of Filecoin Safe and support its integration into their daily business operations. For individuals, our focus is enhancing their security by recommending the use of various wallets/devices for transaction signing.

To accomplish these objectives, we intend to initiate a marketing campaign in collaboration with the Filecoin team and deliver ongoing community support.

## Development Roadmap
Since the whole deployment is quite straightforward and relatively short process, we don’t have milestones, but stages and steps:
1) Official Testnet & Mainnet Smart Contracts Deployment
- Dev wallets funding.
- Deterministic Safe contracts deployment on both Filecoin Testnet and Mainnet.
- PR to Safe team in order to be added to “registry” of Safes deployed across all networks (required step). It could be also considered as informal verification of deployment process by Safe team.
ETA: 1-2 day for actual actions, ~2 weeks for PR review.

_Amount of funding: 5% from the total grant amount_

2) Spin Up Staging Infrastructure & Networks Configuration:		
- Spin Up Staging & Production AWS Infrastructure
- DNS configuration (in agreement with Filecoin governance/community).
- Setup Monitoring Tools and Alerts
ETA: 3-5 days.

_Amount of funding: 20% from the total grant amount_

3) [Safe components](https://github.com/safe-global) deployment on the infrastructure and its configuration:
- Backend components deployment and configuration with network and smart contracts (gtw, cfg, tx-service, event-service).
- Frontend (UI) component deployment and configuration (safe-wallet-web).
- Frontend Customization
- QA and testing
- Handover (if required)
ETA: 1-2 weeks.

_Amount of funding: 75% from the total grant amount._

## Total Budget Requested
**$85k** 

Cost breakdown:
1. $30k for Safe deployment (takes 1 month from the moment of Grant Approval & Payment Received)
2. $55k for 1 year support (starting from the 2nd month, $5k/mo, infrastructure costs are included)

## Maintenance and Upgrade Plans
Our maintenance consists of several parts:
1) Regular Safe updates (released by Safe team) will be performed and released to the Filecoin Safe. Updates consider Frontend (mainly user experience improvements), Backend services and Smart Contract.
2) Team scope of work includes research and implementation of features such as Safe Apps, Modules, Guards, External Wallets Connectors, etc. Improvements can be proactively suggested by Protofire or requested by Filecoin governance/community.
3) DevOps support and monitoring, covering all aspects of infrastructure security, architecture optimization, monitoring and CI/CD pipeline enhancement in order to improve cost-effectiveness and scalability. This team supports troubleshooting incidents and issues in the infrastructure context.
4) General support is provided to Filecoin governance/community. It includes incidents analysis and troubleshootings, research and general inquiries. Customer support cover all the issues related to Safe usage faced by end-users.
# Team
## Team Members
**Ivan Bandaryk - Field CTO**
12 years of commercial experience and 8 years of working with web3 projects. With his supervision team deployed Safes on 20+ networks. Experienced CTO with a technical background and strong blockchain business understanding.

**Nick Zhiltsov - Tech Lead**
Software engineer with vast experience in software development for 15+ years, 6 of them with blockchain projects. Took part in Safes deployment for 20+ networks.

**Eduardo Santos - Delivery Manager**
Started as a developer in 2008, then became Delivery Manager with main expertise in proposal management, team coaching, product backlog management, people leadership.

**Marta Savastijonok - Software Developer**
Blockchain researcher and full stack developer with 5 years of experience. Contributed in Uniswap ecosystem.

**Nikita Zasimuk - Software Developer**
Blockchain developer with 5+ years of experience with expertise on frontend (React, web3.js, ether.js).

**Anton Friedel - QA**
Quality Assurance Engineer with expertise in Web, Mobile and DeFi applications (wallets, networks, protocols).

**Leonid Belyatskiy - DevOps Engineer**
Systems Engineer with 7+ years of experience, 2 years in Blockchain ecosystem. Main expertise: CI/CD, Gnosis Beacon Chain, Ansible, AWS, Scripting

**Ilya Velinsky - DevOps Engineer**
Systems and DevOps Engineer with 8+ years of experience in cloud architecture, system administration, IaC, CI/CD.
Core skills: Linux, AWS, Docker, Kubernetes, Ansible, Terraform, Jenkins, Prometheus/Grafana.

## Team Member LinkedIn Profiles
https://www.linkedin.com/in/ivan-bandaryk/
https://www.linkedin.com/in/nickolai-zhiltsov/
https://www.linkedin.com/in/esantos089/
https://www.linkedin.com/in/marta-savastijonok/
https://www.linkedin.com/in/nikita-zasimuk/
https://www.linkedin.com/in/anton-friedel/
https://www.linkedin.com/in/leonid-belyatskiy/
https://www.linkedin.com/in/ilya-v-b226861a7/
## Team Website
https://protofire.io/services/safe-deployment
## Relevant Experience
Protofire DAO has deployed and currently supporting Safes on more than 25 networks, what proves that we are trusted and a reliable partner. The whole team is dedicated to Safe project and we are able to scale up quite quickly, so we will have enough resources to provide perfect service at any time. Since we are partner of Safe team and we have a long-term strategy for this type of service, community can be absolutely sure that Filecoin Safe will be available years from now.
## Team code repositories
We are publishing code in the project repository; in this case, it will be hosted in the Filecoin repository. Here is an example of the code we manage: https://github.com/AstarNetwork?q=safe&type=all
# Additional Information
Email address to discuss the application: [ivan@protofire.io](mailto:ivan@protofire.io)

**Comment by ErinOCon** [comment]
Hi @protofivan, thank you for your proposal! We are wrapping up the preliminary review for this wave and will have an update available shortly.

Thank you for your patience!

**Comment by ErinOCon** [comment]
Hi @protofivan, thank you again for your proposal and for your patience with our review. We will not be moving forward with a grant at this time, but anticipate this area of work will become a priority later in the year. Would you have an interest in checking back in with our team in the future? Perhaps sometime in September? We would be happy to reconsider a proposal at this time.

Our team can be reached at [grants@fil.org](mailto:grants@fil.org) with any questions. Wishing you the best with your project progress!

**Comment by protofivan** [comment]
Hey @ErinOCon. Thanks for the update. We are definitely interested in working with you, so feel free to contact me directly via email (ivan@protofire.io) whenever you prioritize Safe deployment. I'd be happy to delve into the technical and business aspects, along with discussing the commercial agreement. We're open to considering support for a shorter duration if needed.
