### ISSUE TITLE
Decentralized service for brokerage trading - Grants Program

### ISSUE THREAD

**Issue by Mercury-crew** [filecoin-project/devgrants#1696]
# Open Grant Proposal: `Project Title`

De_ trade

`Applications`

**Individual - Ostanin Pavel

**Proposer:** `(https://github.com/Mercury-crew)`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** - Yes
# Project Summary

## Impact 

If we aggregate this into one place in De_trade (decentralized without a backend), it is important to note that everything remains in the same pools as originally - we are not going to hold funds in our own wallets or smart contracts, we are only providing a middle-layer solution.

In this way using your product will be more profitable for users, which will increase total income for the protocol and increasing the opportunity for strategic lancing.

Our product:
De_Trade is a decentralized service for brokerage trading.
- Asset ownership - is decentralized,
- Asset management - is non-trust centralised by users

Service with decentralized ownership of assets to ensure the safety of users from scams and bankrupt exchanges.

Our goal is to provide a clear and safe brokerage service, that is, build a system that can't be attacked like regular brokerage services based on centralized exchanges.

Deck: https://docsend.com/view/qi8ipjt87ug7295y

## Development Roadmap

This is the complete development roadmap.
[(https://docs.google.com/spreadsheets/d/1WVPQzO_3e9iy4ACobunOc0rCKmNNuuPBsmcvqPxY6JY/edit?usp=sharing)]

## Total Budget Requested
$94920
[(https://docs.google.com/spreadsheets/d/1WVPQzO_3e9iy4ACobunOc0rCKmNNuuPBsmcvqPxY6JY/edit?usp=sharing)]

# Team

 Ostanin Pavel CEO 
 Konstantin Shestak CTO

## Team Member LinkedIn Profiles

 https://www.linkedin.com/in/osspaul/
https://www.linkedin.com/in/konstantin-shestak/

## Team Website

https://mercuryteam.world/

## Relevant Experience
https://xb3.finance/
https://www.degenape.academy/
https://representvote.com/
https://representid.com/

# Additional Information
 Google
 detrade.dao@gmail.com
 Deck: https://docsend.com/view/qi8ipjt87ug7295y

**Comment by ErinOCon** [comment]
Hi @Mercury-crew, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!

Note: To contact our team with grant program related inquiries, please send an email to [grants@fil.org](mailto:grants@fil.org).
