### ISSUE TITLE
Next Step Microgrant: FilSnap maintenance for multiple web3 providers issue

### ISSUE THREAD

**Issue by eshon** [filecoin-project/devgrants#1697]
### 1. What is your project, and what problem does it solve? (max 100 words)

Maintenance for the open source [MetaMask Filecoin Wallet](https://snaps.metamask.io/snap/npm/filsnap/) ([Github repo](https://github.com/filecoin-project/filsnap)) to address an issue when multiple wallet browser extensions are installed, described in https://github.com/filecoin-project/filsnap/issues/160. Glif.io is currently requesting this be fixed so that they can add the MetaMask Filecoin Wallet to the list of wallets they offer.

Any additional remaining hours may also be used to update the [iso-filecoin](https://www.npmjs.com/package/iso-filecoin) library, the cryptographic signing library which is also used by the FilSnap and Ledger.

### 2. Project links
  
Link to Github repo: https://github.com/filecoin-project/filsnap
Link to demo or website: https://snaps.metamask.io/snap/npm/filsnap/
License: Dual-licensed: [MIT](https://github.com/filecoin-project/filsnap/blob/master/LICENSE-MIT), [Apache Software License v2](https://github.com/filecoin-project/filsnap/blob/master/LICENSE-APACHE), by way of the [Permissive License Stack](https://protocol.ai/blog/announcing-the-permissive-license-stack/).

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

Filecoin dapps require a web3 wallet for users to interact with the dapp's smart contracts. The MetaMask Filecoin Wallet (Snap) supports Filecoin users with the ability to sign Filecoin transactions (including FEVM) using MetaMask. It can store native Filecoin key material in the MetaMask vault. This wallet is an open source project at https://github.com/filecoin-project/filsnap and has been a project in the Filecoin ecosystem for several years, as MetaMask develops and evolves its 3rd party Snaps platform which launched for users in Fall 2023.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)

Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |   Fix multiple providers bug described in [filsnap #160](https://github.com/filecoin-project/filsnap/issues/160)   |    Use https://github.com/Montoya/snap-connect-example as an example, test, and add docs     |            est.  20 hours               | 
| 2.     |    Update iso-filecoin       |       Provide any interim updates as needed       |                est. 5 hours            | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

David Justice - [work@justice.engineering](mailto:work@justice.engineering) - https://github.com/meandavejustice (@meandavejustice) - developer

David has worked as a software engineer on the Browsers and Platforms (and IPFS) group at Protocol Labs for several years. He has previously received an overview of the FilSnap architecture from the main developer of https://github.com/filecoin-project/filsnap, i.e. hugomrdias. 

* How did you learn about our microgrant program?
From @eshon

**Comment by ErinOCon** [comment]
Hi @meandavejustice, this microgrant has been approved! We will send an email to confirm payment details.
