### ISSUE TITLE
Filezilla - Creating a decentralized bridge that would connect FileCoin with Solana 

### ISSUE THREAD

**Issue by FiIeZilla** [filecoin-project/devgrants#1699]
# Open Grant Proposal: `FileZilla Bridge`

**Project Name:** FileZilla

**Proposal Category:** Applications : decentralized bridge to connect File with Solana

**Individual or Entity Name:** Is the proposal on behalf of an individual, or an entity/organization? On behalf of an individual.

**Proposer:** `FiIeZilla`

**Project Repo(s)** [Bridge-to-Sol](https://github.com/FiIeZilla/Bridge-to-Sol)

**(Optional) Filecoin ecosystem affiliations:** `No affiliation

**(Optional) Technical Sponsor:** `Have not discussed this with anyone yet. 

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Please respond with "Yes" or "No". YES

# Project Summary

 
The process of transferring $fil coins to and from the File blockchain can be complex, deterring potential investors. They prefer a straightforward process. Establishing a bridge between Solana and File would simplify this process, making it more appealing for investors to join the FileCoin chain.

## Impact 

The end goal is widespread adoption of the FileCoin chain, attracting numerous new developers and investors to the platform.

Success will be measured by tracking bridging activity and assessing the number of new projects launched on FileCoin.

## Adoption, Reach, and Growth Strategies

 
To onboard new investors, we will highlight the advantages of FileCoin's storage capabilities and promote the simpler bridging option as opposed to using the f address.

## Development Roadmap

Milestone 1: Launch FileZilla token on Filecoin chain.
Milestone 2: Deploy Bridge dapp that connects File to Solana
Milestone 3: Launch FileZilla token on Solana Chain.

## Total Budget Requested $25,000

| Milestone # | Description | Deliverables | Completion Date | Funding |
We expect for our cross chain bridge to be finished before 30 days are over.

## Maintenance and Upgrade Plans

Our Long term goal is to have a multiple tokens availble for bridging into the FIleCoin chain mainnet. Fees collected from bridge transactions will also be used to buy back and burn our own token and to improve the infrastructure and maintenance of the bridge. In the end, we want to be the go to bridge for onboarding and offboarding assets off of the Filecoin mainnet

# Team

## Team Members

 Hector Hernandez
 Marvin Aviles
 Lalith Kumar
https://www.linkedin.com/in/h-h-1144712a6/
 https://www.linkedin.com/in/marvin-aviles-7124314a
  https://www.linkedin.com/in/lalith-kumar-selvaraj?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app
 https://filezilla.rocks/

## Relevant Experience

I, Hector, have experience leading marketing and community manager for a project on BSC, the name was Doken Token (https://coinmarketcap.com/currencies/doken/) It was live for over a year with our all time high close to 3m market cap. I am a Registered Nurse from Texas.
We also have Lalith, who is our graphics designer, I have included his linkedin so you can see his previous projects. Our Developr is from Canada. He is a Senior blockchain developer with experience in Javascript, typescript, solidity, Rust, React, Vue, and Python. I  will include his repos.

## Team code repositories

 https://github.com/doflado

# Additional Information
 We learned about it because of the filecoin website. I am an investor of File and I happened to stumble upon the program. 
 yoda.h79@gmail.com
 I've been in the crypto space since 2010 as an early bitcoin enthusiast. I believe FileCoin is extremely undervalued. We want to bring mass adoption to the mainnet. This in turn will increase TVL, transactions and most of all, Marketcap. The partnership you made from Solana will only help bring light to the bridge we want to create from that blockchain to File. We are committed to a long term relationship to Filecoin mainnet. We are prepared to dox or sign any kind of contract to solidify the seriousness of our commitment.

**Comment by ErinOCon** [comment]
Hi @FiIeZilla, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!

Note: To contact our team with grant program related inquiries, please send an email to [grants@fil.org](mailto:grants@fil.org).
