### ISSUE TITLE
WP Smart Contracts Grant Request

### ISSUE THREAD

**Issue by WPSmartContracts** [filecoin-project/devgrants#1700]
### WP Smart Contracts

[WP Smart Contracts](https://wpsmartcontracts.com/) introduces a pioneering approach to integrating blockchain technology within WordPress websites. Since its inception in 2019, WP Smart Contracts has provided a robust plugin designed to facilitate the seamless implementation of smart contracts tailored specifically for the WordPress platform.

The plugin simplifies the process of incorporating blockchain functionalities into WordPress environments, offering developers and entrepreneurs a comprehensive suite of tools to deploy and manage various smart contracts with ease. From standard ERC-20/BEP-20 tokens to advanced NFT collections and staking solutions, WP Smart Contracts provides versatile options to address diverse blockchain use cases efficiently.

### WP Smart Contracts WordPress Plugin
During five years, the [WP Smart Contracts WordPress Plugin](https://wordpress.org/plugins/wp-smart-contracts/) has achieved significant milestones:

- Processed over $35M in Smart Contracts Value.
- Exceeding [50,000 WordPress Downloads](https://wordpress.org/plugins/wp-smart-contracts/advanced/).
- Facilitated over 2,000 Mainnet Deployments.
- Boasts [13 Smart Contracts / Flavors](https://wpsmartcontracts.com/flavors/), including:
-- ERC20/BEP20 tokens (Vanilla, Pistachio, Chocolate, Macadamia)
-- Staking contracts (Ube, Almond)
-- Crowdfunding contract (Mango)
-- ICO contract (Bubblegum)
-- Various NFT contracts (Mochi, Matcha, Suika, Yuzu, Azuki, Ikasumi).
- Supports [6 Different EVM Blockchains](https://wpsmartcontracts.com/networks/).
-- Ethereum
-- Arbitrum
-- Binance Smart Chain
-- Polygon
-- Avalanche
-- Fantom
- Underwent multiple [Smart Contract Audits](https://wpsmartcontracts.com/audits/).
- WordPress [Web3 User Registration and Login](https://wpsmartcontracts.com/wordpress-web3-login/): a simple and secure solution for user registration and login processes on WordPress websites.
-- Secure and easy user registration and login
-- Eliminates the need for passwords
-- Makes it more difficult for hackers to gain access to accounts
-- Collect users' email addresses during registration
-- Login using WordPress Forms, the Launcher, or a shortcode
- Offers localization in 10 languages: 
-- 🇸🇦 Arabic
-- 🇬🇧 English 
-- 🇫🇷 French
-- 🇩🇪 German
-- 🇮🇹 Italian
-- 🇯🇵 Japanese
-- 🇵🇹 Portuguese
-- 🇷🇺 Russian
-- 🇨🇳 Simplified Chinese
-- 🇪🇸 Spanish

For more information and access to the plugin, visit:

https://wpsmartcontracts.com/
https://wordpress.org/plugins/wp-smart-contracts/

### The Problem
In this section, we address the existing challenges and limitations encountered within the WP Smart Contracts plugin ecosystem.

**Paid Deployment**
The current model of the project operates under a freemium structure within the WordPress plugin ecosystem. While the plugin itself is free to install, users are obligated to pay a fee for smart contract deployment, alongside covering the network gas fee. This fee-based model may pose a hindrance for users seeking cost-free solutions, potentially limiting accessibility.

**Not Fully Open Sourced**
Moreover, although the PHP code underpinning the plugin is open-source, the smart contracts factories responsible for generating the smart contracts remain closed-source. This lack of full transparency may impede the community's ability to thoroughly review and contribute to the development process, curtailing collaborative efforts.

**Limited Networks**
Additionally, the plugin's support for smart contract deployment is presently confined to a limited number of networks. This limitation restricts users who may seek to deploy smart contracts on networks not currently supported by the plugin, thus constraining its overall utility and versatility within the blockchain ecosystem.

### The Future
**Open WP Smart Contracts**
We want to move the plugin to a next level and give to the community the code, the power and the ability to simply deploy the smart contracts on as many networks as possible without the need to pay an extra fee. They will pay only for gas fees.

### Proposal

**Milestone 1 - Free Software for WordPress Community**
Free and Open Source Smart Contracts Deployment for WordPress Users

For the future of WP Smart Contracts, we propose a step towards advancing accessibility and transparency in blockchain integration within the WordPress ecosystem.

**Expansion to New Networks**
We will expand support to include additional networks through a grant-based approach, ensuring strategic and sustainable growth.

**Availability of Filecoin for Current WP Smart Contracts User Base**
Current WordPress installations with the active plugin will automatically receive updates, including the addition of new networks for free. This includes free deployment for life, thereby exposing the network to a broader user base of freelancers, entrepreneurs, and developers.

**Free Smart Contract Deployment:**
As part of this milestone, the new networks will be available for free deployment within the plugin backend. Site administrators will only pay for the gas fee, benefiting the WordPress freelancers and developers community.

**Full Opening of the WP Smart Contracts Code**
The addition of new networks will require new smart contracts factory code, which will be fully open-sourced. Coupled with the existing open-source PHP code within the plugin itself and the open-source nature of the generated smart contracts, this ensures that the plugin comprises entirely open-sourced code for new networks.

**Smart Contracts Audits**
New smart contracts factories will undergo comprehensive audits by our internal team and a third-party team, [mirroring the audit processes employed in previous rounds](https://wpsmartcontracts.com/audits/).

**Website, Documentation, and WordPress Plugin Setup**
Documentation of the new Free plugin features will be provided.

By pursuing these Milestone 1 objectives, WP Smart Contracts aims to position itself as a leader in promoting accessibility, transparency, and innovation in blockchain integration for WordPress users.

**Milestone 2 - Beyond WordPress**
Free Smart Contracts Launcher For Everyone

This milestone expands our reach beyond the WordPress ecosystem, catering to users who may not have expertise in WordPress but seek to deploy smart contracts.

**Smart Contracts Free Launcher**
As part of Milestone 2, the new networks will be available in the [Smart Contracts Free Launcher](https://wpsmartcontracts.com/docs/doc-launcher.php). This launcher serves as a public platform where users, regardless of their familiarity with WordPress, can effortlessly deploy any available smart contract.

**Public and Replicable Launcher**
The Smart Contracts launcher will be publicly accessible and replicable, enabling installation by any user utilizing the WordPress plugin. Consequently, website users will have the freedom to deploy smart contracts at their discretion.

**Exclusive Launchers for Your Network**
The Launcher can be set to work exclusively with chosen networks, allowing site owners to create an exclusive launcher for their preferred network.

**Open Smart Contracts Launcher**
The public launcher will operate similarly to the current launcher, but it will be free to use for Filecoin users, with users only required to cover gas fees. Additionally, the networks integrated into the plugin will be openly accessible for deployment.

**Multiple Language Support**
All new features will be available in 10 languages: Arabic, English, French, German, Italian, Japanese, Portuguese, Russian, Simplified Chinese, and Spanish.

**Website, Documentation, and WordPress Plugin Setup**

Through Milestone 2, we aim to bridge the gap between blockchain technology and users from diverse backgrounds.

### Benefits for Filecoin

The Open WP Smart Contracts plugin serves as a tool, facilitating the deployment and management of smart contracts within Filecoin ecosystem. Below, we delve into the core benefits of incorporating this plugin into your projects:

1. Leverage the user base of the WP Smart Contracts plugin to ensure broader exposure of your network to WordPress users currently utilizing the plugin.

2. Accessible Smart Contract Deployment: Any users, regardless of their WordPress or programming proficiency, can utilize any publicly available Smart Contracts Launcher for seamless smart contract creation, deployment, and management. This process requires minimal technical expertise and is free of charge, with users only responsible for covering gas fees during deployment.

3. The community can create an exclusive Launcher dedicated exclusively for Filecoin network to promote a wider use of the Network across multiple use cases like:

- NFT Marketplaces
-- ERC-721
-- ERC-1155
- Standard ERC-20 like tokens
-- Advanced and Reflection Token creations
- Token Staking Solutions
- ICOs
- Crowdfundings

4. Community Engagement and Innovation: By incentivizing existing WordPress and freelancers communities to provide blockchain and smart contracts solutions using Filecoin platform, you stimulate community engagement and foster innovation. This collaborative effort enriches your platform with diverse solutions tailored to the specific needs of your community.

In essence, the Open WP Smart Contracts plugin offers a user-friendly and an accessible way for smart contract deployment, empowering both users and developers to harness the full potential of blockchain technology.

### Estimation
**Milestone 1**
Development: 5 weeks
Requested amount: $6,500
**Milestone 2**
Development: 4 weeks
Requested amount: $5,200

Full detailed ### proposal

For full details please check this proposal document:
https://wpsmartcontracts.com/grants/WPSC-Filecoin.pdf

**Comment by ErinOCon** [comment]
Hi @WPSmartContracts, I am very sorry that you have not heard from our team! It looks like this application was not tagged automatically under one of our [issue types](https://github.com/filecoin-project/devgrants/issues/new/choose). 

Are you still interested in this grant? If so, are there any new updates you wish to make before we proceed with our review?

**Comment by WPSmartContracts** [comment]
Hi,

No worries,

Yes, we are still interested in the grant and no, we don't have any updates
at this time

Thanks in advance

**Comment by ErinOCon** [comment]
Thanks, @WPSmartContracts! We will be in touch with any questions.

**Comment by ErinOCon** [comment]
Hi @WPSmartContracts, thank you for your time with this proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. If you have questions regarding our review process or have an interest in exploring other ways to get involved with the Filecoin community, please do not hesitate to contact our team at grants@fil.org. 

Wishing you the best as you continue building!
