### ISSUE TITLE
Blockhouse – The world’s first global home super dApp on the blockchain

### ISSUE THREAD

**Issue by Macdtd** [filecoin-project/devgrants#1702]
# Open Grant Proposal: `Project Title`
Blockhouse – The world’s first global home super dApp on the blockchain

**Proposal Category:** 
Applications

**Individual or Entity Name:** 
Tony Dicarlo

**Proposer:**
Macdtd

**Project Repo(s)** 
N/A

**(Optional) Filecoin ecosystem affiliations:** 
N/A 

**(Optional) Technical Sponsor:** 
N/A

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Please respond with "Yes" or "No". 
Yes

# Project Summary

Take control of your home’s digital life with a house logbook. Keep track and manage your home's records, content and data, access government services, and find products and services all in one place.
Blockhouse is the world’s first global super dApp for your home to improve how people own, manage and live in a house. 
We’re bringing real world asset provenance to the blockchain, storing data in a decentralised manner and using token incentives to reward participation.
Blockhouse is flipping the fat protocol thesis. This is a hugely exciting project that finally brings an application layer to the blockchain that captures web 2 customers at scale.

## Impact 

 

A super dApp for housing can have two extremely large impacts at scale. 1) Digitising a house creates the golden thread. Data and in particular decentralised data and its storage facilitate greater trust and more informed decision making amongst market participants such as owners, investors, trades people, financial institutions and insurance underwriters. Not only this but data availability will foster market democratisation and new innovative services and business models that bring new kinds of value to assets and their owners. 2) The blockhouse ecosystem and use of blockchain and token rewards means users can monetise and earn from a once stagnant asset. They can monetise their asset by recording updates on the logbook, control and monetise their data and enjoy discounts that the ecosystem and scale purchasing can bring.
We are a web 3 ecosystem which means our north start is how we can sustainably create and distribute the most value for our users. The question of web 2’s “How much can I extract from my users” for us evolves into “how much value can I give to my community?”
As Web 3 social structures distribute value outwards, our relationships with the platforms we use are going to evolve from extraction to enablement. The capacity to compete for our attention using outward value, fundamentally changes how platforms like ours will behave for decades to come.

## Outcomes

 

The projects long term goal is to become a global standard and government accepted record of a homes provenance. We want peoples biggest asset - their homes - to have a clear and transparent recorded history. Using an immutable store of record and storing data and records in a decentralised manner ensures we can offer trustful data and records that can lead to a government friendly business that can expand globally

 

The main metrics we use to assess dApp adoption are 1) # of house’s registered with a logbook and 2) the number of updates to a home’s logbook are made per year.

The number one metric we use to ensure value is being distributed outwardly is how much in £/$’s can the User and Providers earn each year by engaging with their logbook and our ecosystem.

## Adoption, Reach, and Growth Strategies

 

We intend to give equity in our onshore TopCo away to the 40 biggest housebuilders in the UK (who build 80% of new homes) in return for supply based vesting equity i.e. We give them a % equity for a X number of homes onboarded every year. This enables us to onboard 10's of thousands of homes each year in the UK alone (think Microsoft licencing for each computer deal akin to Housebuilders giving their customers handover packs (mandatory) which is the blockhouse logbook) We are aiming for every new home of the 250,000 built every year to be issued with a blockhouse logbook as standard. In year two as we expand to other global location we will have onshore TopCo's in utilising the same hyper growth structure and strategy to onboarding supply.

## Development Roadmap

Milestone 1: Defining data types and their storage requirements.
Each homes logbook will store possibly three sets of data for the house and customer. 

A homes data is stored in a decentralised manner to ensure immutable and trustful data for the lifespan of a house. We anticipate that by year 5 we will have onboarded over well over 5 million homes globally in our ecosystem all of which will need to store data as part of their logbook provenance. This data will be uploaded to each new build home on the first sales handover and then it’s anticipated that each home will update their logbook 4 -5 times per year. 
Logbook data – provenance data
Typical stored data will consist of scanned invoices, manuals and other digitised documents alongside photos - all of which needs to be stored long term (a homes has a typical lifespan of 75 - 100 years). We know for certain this must be stored in a decentralised manner
Customer data
Customer data includes admin credentials alongside transferable housing data such as mortgage records etc. This is required to be stored either in a centralised or decentralised manner.
Logbook data – Misc data
Misc data such as manuals for products and appliances etc. 
On completion of this milestone there should be a clear understanding on which of the three storage requirements Filecoin is the best suited and the opportunities and constraints filecoin brings for each.
Resources: We anticipate 4 x 1 hour workshops which would be accompanied by 10 hours of investigation and scoping works.
There will be two people from blockhouse (CEO/Founder and CTO) and we would expect three from filecoin. (1x frontend engineer, 1x backend engineer, 1x devops engineer)
Timeline: We anticipate 2 weeks 
Funding requirement: 14 hrs @$70per hour x 3 people = $2,940

Milestone 2: Design a solution for a Go to Market strategy
Brainstorming with the Filecoin and Blockhouse team to design a pragmatic solution design. Once the scope of services Filecoin can provide from Milestone 1 have been defined, an initial solution can then be designed. 
The solution will need to work with the Solana blockchain on the back end and a web 2 front end user interface where all things Web 3 have been abstracted away. The end result should be a solution for long term storage of data at scale that will work seamlessly within our ecosystem. This data will be predominantly long term non-editable data storage with a small elements of data that will be called and edited more frequently.
Resources: We anticipate 4 x 1 hour workshops which would be accompanied by 20 hours of investigation and scoping works.
There will be two people from blockhouse (CEO/Founder and CTO) and we would expect three from filecoin. (1x frontend engineer, 1x backend engineer, 1x devops engineer)
Timeline: We anticipate 2 weeks 
Funding requirement: 24 hrs @$70per hour x 3 people= $5,040

Milestone 3: Design solution integration
Building out and connecting the front end interfaces and backend structures between the Blockhouse ecosystem and Filecoin.
Resources: We anticipate 2 x 1 hour workshops which would be accompanied by 40 hours of build/implementation hours.
There will be two people from blockhouse (CEO/Founder and CTO) and we would expect three from filecoin. (1x frontend engineer, 1x backend engineer, 1x devops engineer)
Timeline: We anticipate 4 weeks 
Funding requirement: 42 hrs @$70per hour x 3 people= $8,8820

Milestone 4: Smoke testing design solution. Raising and resolving tickets
Testing is to occur in the Beta environment and will involve both teams to test for UI/UX bugs
Resources: We anticipate 12 hours of testing from Filecoin team and a further 10 hours to resolve any tickets raised by both teams.
There will be two people from blockhouse (CEO/Founder and CTO) and we would expect 1 from filecoin. (1x devops engineer)
Timeline: We anticipate 2 weeks 
Funding requirement: 22 hrs @$70per hour x 1 person = $1,540

Milestone 5: Handover and Post deployment plan
Discussing and setting out a maintenance and enhancement action plan for the project going forward.
Resources: We anticipate 1 x 1 hour workshop which would be accompanied by 4 hours of post deployment plan development
There will be two people from blockhouse (CEO/Founder and CTO) and we would expect 1 from filecoin. (1x devops engineer)
Timeline: We anticipate 1 week 
Funding requirement: 5 hrs @$70per hour x 1 person = $350

## Total Budget Requested
| Milestone # | Description | Deliverables | Completion Date | Funding |

|5|as above| as above|11 week from start date |$18,690|

## Maintenance and Upgrade Plans

We expect to have a post deployment plan developed between Blockhouse and Filecoin as part of the Fifth Milestone. This post deployment plan will include 1) Maintenance plan and 2) Enhancements plan.  
1)	Maintenance plan
A maintenance plan will define work required and completed to proactively maintain dApp functionality. The contents of the document help facilitate the continued use of an asset at optimum performance and help avoid downtime or malfunctioning of data storage.
2)	Enhancement plan
An enhancement plan will be defined to give is a structured process for continued review and assessment to identify areas for improvement and develop strategies to enhance product performance.

# Team

## Team Members

Tony Dicarlo

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/antonio-dicarlo/

## Team Website
 
N/A

## Relevant Experience
 

Please review LinkedIn for full experience on conceptualising and building out complex and award winning products.
This project is a blockchain residential real estate dApp. It was born out of the Founders 12+ years’ experience as an award-winning residential housing developer and coupled with his in-depth Crypto asset investment experience since 2017. In fact, the project was conceptualised in 2021 but decidedly parked due to the lack of appropriate real world asset infrastructure in the crypto sector at that time. However, the infrastructure in the sector has now matured as has 3 years of founder ideation on how to fuse housing with blockchain and token incentives. It's the founders extremely unique blend of in depth property/Proptech and blockchain experience that gave rise to the ability to conceptualise and develop the project further.

## Team code repositories

N/A

# Additional Information
 
Common knowledge about Filecoin grants then Google to find appropriate Grant program

 
[info@theblockhouse.xyz](mailto:info@theblockhouse.xyz)

info@theblockhouse.xyz

(https://1drv.ms/b/s!AtD0GsDt2lIUhLxT3ucmlL4tXgva8g?e=lqcUgL)

**Comment by ErinOCon** [comment]
Hi @Macdtd, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!

Note: To contact our team with grant program related inquiries, please send an email to [grants@fil.org](mailto:grants@fil.org).
