### ISSUE TITLE
FEVM-ApeWorX Python Development Kit

### ISSUE THREAD

**Issue by Aviksaikat** [filecoin-project/devgrants#1705]
### 1. What is your project, and what problem does it solve? (max 100 words)
Our project aims to develop a Python SDK for FEVM-[ApeWorX](https://github.com/ApeWorX/ape), which is a starter project for developing, deploying, and testing Solidity smart contracts on the FEVM (Ethereum Virtual Machine on Filecoin). The problem it solves is the lack of convenient developer tools for Python developers who want to interact with FEVM-Apeworkx contracts and access Filecoin APIs seamlessly. Currently, there is a gap in the tooling ecosystem for Python developers looking to build applications and smart contracts on the FEVM platform. Our SDK will bridge this gap by providing Python developers with intuitive tools to interact with FEVM-Apeworkx contracts, deploy contracts, and manage storage deals directly from Python environments. By simplifying the development and deployment process, our SDK aims to lower the barrier to entry for Python developers interested in leveraging the capabilities of the FEVM platform and Filecoin blockchain.

### 2. Project links
  
Link to Github repo:
Link to demo or website:
License: MIT

  
###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | SDK Implementation      | Implement Python SDK functionalities for interacting with FEVM-Apeworkx contracts and accessing Filecoin APIs. | Within 4 weeks |
| 2.     | Testing and Debugging   | Conduct thorough testing of the Python SDK to ensure functionality and reliability, addressing any identified bugs or issues. | Within 1 week after SDK implementation |
| 3.     | Documentation           | Create comprehensive documentation for the Python SDK, including usage examples and setup instructions. | Within 1 week after testing and debugging |
| 4.     | Milestone Review        | Review project progress, assess milestones achieved, and plan for any necessary adjustments or future steps. | Within 3 months, ongoing as needed |

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
 @Aviksaikat [Smart Contract Auditor, Systems Security Engineer, Lead Python Developer]

Previous projects
https://github.com/alienrobotninja/bee-py ( Ethereum Swarm Foundation)
https://github.com/Aviksaikat/swarm-cid-py ( Ethereum Swarm Foundation)

**Comment by eshon** [comment]
Hi @Aviksaikat - currently FEVM should work out of the box with tools like Hardhat, Foundry, etc., as well as Ethers.js and other SDKs. So there shouldn't need to be any FEVM-specific updates with the ApeWorX Python toolkit as long as it's EVM compatible.

**Comment by Aviksaikat** [comment]
Hardhat, etheres.js is for javascript/typescript. Foundry(it's different). But for Python developers who use `web3.py` or `ape`, there is no starter kit.  So I proposed to make a development kit specifically for Python developers to encourage them to build on FVM without learning JavaScript or Foundry if that makes sense.

**Comment by ErinOCon** [comment]
Hi @Aviksaikat, thank you for your patience with our review process. Unfortunately, after much consideration, it has been determined that we will not be be moving forward with a new grant at this time.

In case you have an interest, I will be sending you an email shortly to discuss other ways to partner with our community. Wishing you the best as you continue to build.
