### ISSUE TITLE
Next Step Microgrant: Reboot datasets.filecoin.io for hackathon developers

### ISSUE THREAD

**Issue by eshon** [filecoin-project/devgrants#1708]
### 1. What is your project, and what problem does it solve? (max 100 words)

This project is to reboot datasets.filecoin.io as a useful website for hackathon developers as a directory of smaller scale datasets stored on Filecoin's Calibration testnet.

The goal is to help Filecoin hackathon participants improve the data narratives and user stories in their dapps by suggesting and providing more interesting sample data sets.
- Ideally these datasets could be used across FEVM, Bacalhau, etc.
- New datasets can be proposed by community members (via a form in the FAQ)
- Lighthouse and PoDSI, etc. will be used to get these datasets stored on Filecoin's Calibration testnet
- The old site that was a directory of larger datasets stored via Slingshot will be moved to http://legacy.datasets.filecoin.io/
- Candidate datasets can be found at [AWS Open Data](https://registry.opendata.aws/) or [TensorFlow Datasets](https://github.com/tensorflow/datasets) and in this [Filecoin Test and Candidate Datasets](https://docs.google.com/spreadsheets/d/1p2Dvvcv6UUMurtvaORhMMx9uDDmybMC-AjKjq5H07Iw/edit#gid=622786920) spreadsheet that has been compiled.

### Background

The original Filecoin Dataset Explorer website (now at http://legacy.datasets.filecoin.io/) no longer has SPs hosting these datasets. It took datasets stored on Filecoin mainnet from initiatives like [Space Race 2: Slingshot](https://slingshot.filecoin.io/) and other sources and presented them in a unified interface. The project was primarily interested in creating a unified interface for users to find where on the Filecoin network public and open-access datasets were stored.

### 2. Project links
  
Link to Github repo: https://github.com/silent-cipher/dataset-explorer
Link to demo or website: https://datasets.filecoin.io
License: MIT

### 3. a) How is IPFS, Filecoin, or related technology used in this project?

* Lighthouse is used on Calibration + Boost, RaaS, PODSCI proofs if possible, Aggregator
* Multiple retrieval pathways possible: Boost, Lassie, Lotus, Lighthouse, Saturn

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)

Potentially via RaaS and PSD contract / Aggregator
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | Find new datasets | Compile smaller datasets [[spreadsheet](https://docs.google.com/spreadsheets/d/1p2Dvvcv6UUMurtvaORhMMx9uDDmybMC-AjKjq5H07Iw/edit#gid=622786920)] | 1 week | 
| 2.     | Store new datasets | Via Lighthouse on Calibration testnet / use Aggregator | 1 week | 
| 3.     | Update UI | Link new datasets to UI, update FAQ, retrieval options, etc.| 1 week | 
| 4.     | Additional features | Experiment with additional retrieval pathways, search for and add additional useful datasets. | 2 weeks | 
| 5.     | Testing and feedback | Have it used t an upcoming hackathon, get feedback, make improvements. | 2 weeks | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
YES, I agree to share monthly updates of the project.

### 6. Does your proposal comply with our Community Code of Conduct?
yes

 
### 7. Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
    * Shashank Trivedi - shashanktrivedi1917@gmail.com - @lordshashank - smart contract and backend developer
        - Previously worked on [EASTORE](https://github.com/filecoin-project/devgrants/issues/1535) microgrant
        - Currently works at [Lighthouse.storage](https://Lighthouse.storage)
   * Puspendra Mahariya - @silent-cipher - frontend developer
        - Previously worked on [EASTORE](https://github.com/filecoin-project/devgrants/issues/1535) microgrant
    
* How did you learn about our microgrant program?
     * This project was recommended for an FVM Microgrant by @eshon

**Comment by ErinOCon** [comment]
Hi @lordshashank and @silent-cipher, this microgrant has been approved! We will send an email to confirm payment details.

**Comment by eshon** [comment]
@ErinOCon - FYI - datasets.filecoin.io has been updated and the microgrant work is considered complete!
