### ISSUE TITLE
DeCAT- Decentralized identity and reputation system for revolutionizing the job market

### ISSUE THREAD

**Issue by dhananjaypai08** [filecoin-project/devgrants#1709]
### 1. What is your project, and what problem does it solve? (max 100 words)
 DeCAT aims to revolutionize credential management by leveraging Soulbound(Non transferrable NFT's) NFTs on Layer-2 Network(Polygon). This will address issues like forgery, duplication, and lack of trust in traditional certificates. 
The platform offers:
 - Unparalleled security: Soulbound NFTs ensure authenticity and uniqueness of achievements.
 - Decentralized efficiency: L2 network promotes scalability and bulk minting via Multi batch transaction.
 - Immutable records: Blockchain guarantees tamper-proof evidence of accomplishments.
 - Enhanced trust and transparency: Verifiable credentials using QR codes improves the hiring and recruitment processes.
 
We are a B2B SaaS Platform which caters to educational institutions, professional bodies, HR departments, and individuals, offering a secure and reliable system for managing and showcasing achievements, ultimately impacting millions of learners and professionals.

#### The problem:
- Traditional certificate issuance and verification suffer from issues like duplication, forgery, and lack of trust.
- This undermines the value of achievements and creates difficulty in verifying individual skills during recruitment.
- Even in web2 and web3 systems certificates and important documents can be easily duplicated and forged. 
- The verification system of credentials is Fragmented and no Unified method of verification and issuance is possible with high security.
- Organizations waste a lot of time, drive space for generating and distributing certificates for their attendees.

### 2. Project links
Link to Github Repo: [https://github.com/dhananjaypai08/DeCAT](https://github.com/dhananjaypai08/DeCAT)
Link to ETHGlobal showcase: [https://ethglobal.com/showcase/decat-y5jya](https://ethglobal.com/showcase/decat-y5jya)
Link to demo: [https://www.loom.com/share/dc68cfe4c1d540b89e5b85df7a263322](https://www.loom.com/share/dc68cfe4c1d540b89e5b85df7a263322)

### 3. a) How is IPFS, Filecoin, or related technology used in this project?
 DeCAT theme is for Soul Bound Tokens which on a granular level is nothing but an NFT. To store the metadata which includes the JSON format of image-uri, name, description and other details we use IPFS http storage via the **Lighthouse.storage sdk** to store the data and also to retrieve the data using its own http gateway. Moving forward the use case for storing metadata and other onchain data would require heavy use case of Filecoin( For generating and verifying onchain ZKproofs). Lighthouse.storage has the simplest docs and the development process after generating api-keys for the lighthouse.storage SDK was smoother

### b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes

### 4. How will you improve your project with this grant? What steps will you take to meet this objective?
- Grant Amount and Breakdown

The MVP would approximately take 3 months to be built including research, testing, auditing, new features, etc.
- Fixed Cost
    - Server Cost: Deployment of Reactjs frontend and FastAPI server on 2 different ec2 instances - 600$ for at least 3 months = 
    1800$
    - API proprietary: Using LLM API's and summarizing models by fine tuning it based on the already prevailing LLM models which are 
    trained on billions of parameters - 150$Rs for 3 months = 450$
    - One time direct cost of Registering DeCAT as a private Limited Company - 200$
    - One time direct cost of Domain registration and DNS - 200$
    - Salaries of 1 developer for developing Account abstraction and UI - 400 for 3 months = 1200$
    - Marketing, PR and overhead cost - 500$ for 1 month = 500$
    - Total Fixed Cost = 4350$
- Variable Cost
    - Deploying Smart contract continuously in the development and testing phase for 3 months ~ Approx 50$
    - Auditing of smart contracts ~ Approx 300$
    - Total variable cost ~= 350$
- Total Cost = 4700$

| Timeline |  work |
|:-----|:--------:|
| A month | Find existing bugs, extensive edge case handling, find vulnerabilities in the existing system and resolve those    |
| Next month   |  Domain registration, SSL certificate generation, EC2 instance deployment for the improved prototype, testing and deployment of smart contract on polygon mainnet  |
| Month after that   | Integration of web3 social auth for smoother user onboarding, integrating account abstraction SDK for making it web2 friendly |
| Remaining days   | continuation of account abstraction integration, moving from simple proofs to ZKproofs on-chain/off-chain(generating zk-proof based on the JSON metadata for qr-code and verifying this verifiable credential on our website), improving the off-chain capabilities via more exposed endpoints in FastAPI, improving UI based on organization feedback, catering to different organization requests and developing key business metrics to track the growth of beta version. And then finally releasing the MVP and looking to sustain via revenue and funds(if necessary)|

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
- If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
DeCAT was built at ETHIndia23 where we were among the Top 12 unique projects built on Filecoin at ETHIndia23 Hackathon + Scroll pool prize: [https://devfolio.co/projects/decat-4b74](https://devfolio.co/projects/decat-4b74)

### Additional questions:
For each team member(s), please list name, email, Github account, and role in the project.
Dhananjay Pai - [dhananjay2002pai@gmail.com](mailto:dhananjay2002pai@gmail.com) - https://github.com/dhananjaypai08 

Dhananjay is working as a Full stack developer intern at a Bangalore based startup named DataPOEM. He is proficient in python, FastAPI, redis, solidity, ReactJS, Mongo. BE CMPN Student at VESIT, Mumbai. Dhananjay contributed in building ERC5192 with some other tweaks in the smart contracts, integrating smart contract with frontend via ethers and setting up Lighthouse SDK

Hrishikesh Patil - [2020.hrishikesh.patil@ves.ac.in](mailto:2020.hrishikesh.patil@ves.ac.in) - https://github.com/hrishi0102
Hrishikesh is 4th Year CMPN student at VESIT, Mumbai. He majorly contributed in the Ideation, frontend design and implementation and Ethers Integration

How did you learn about our microgrant program?
From Ruben Amenyogbo <ruben.amen@protocol.ai>
We received a mail after we won the Filecoin track prize which introduced  us to this microgrants program

**Comment by ErinOCon** [comment]
Hi @dhananjaypai08, Thank you for submitting your proposal earlier this year. While your project was evaluated during multiple rounds of our microgrant program, we have ultimately decided not to move forward with awarding a grant.

The guidelines for the upcoming grant cycle can be found [here](https://github.com/filecoin-project/devgrants). If you have any questions about our program or wish to explore other opportunities to collaborate, please reach out to us at grants@fil.org.
