### ISSUE TITLE
Soulmates: Soulbound Token Issuance Engine Grant (HACK FEVM)

### ISSUE THREAD

**Issue by rohanagarwai** [filecoin-project/devgrants#1712]
### 1. What is your project, and what problem does it solve? (max 100 words)
**Project Name:** Soulmates

**Problem Statement:** Soulmates is a soulbound token (SBT) issuance engine built on the Filecoin Virtual Machine (FVM). It addresses the need for on-chain primitives for decentralized identity and reputation, catering to use cases such as lending protocols, DeFi solutions, storage provider reputation systems, and education credentials.

Soulmates contributes to the Filecoin ecosystem in several ways:

1. **Decentralized Identity and Reputation:** Soulmates introduces on-chain primitives for decentralized identity and reputation. This is crucial for various use cases within the Filecoin network, such as storage provider reputation systems. By establishing a system of soulbound tokens, Soulmates enhances trust and reliability in the Filecoin ecosystem.

2. **Use Cases in DeFi and Storage:** The issuance of soulbound tokens by Soulmates supports a range of use cases, including lending protocols, DeFi solutions, and storage provider reputation systems. These applications bring added functionality to the Filecoin network, expanding its utility beyond simple storage.

3. **Filecoin Virtual Machine (FVM) Integration:** Being built on the FVM, Soulmates aligns with Filecoin's vision of a decentralized and secure storage network. FVM enables the execution of smart contracts on the Filecoin blockchain, and projects like Soulmates demonstrate the flexibility and innovation possible within this ecosystem.

4. **Diverse Ecosystem Applications:** Soulmates' ability to issue soulbound tokens for education credentials and other use cases showcases the versatility of Filecoin's ecosystem. It contributes to the broader narrative of using blockchain technology for diverse applications beyond traditional storage.

5. **Technical Insights and Collaboration:** Through the development of Soulmates, the project team faced and overcame technical challenges, providing valuable insights that can be shared with the Filecoin Virtual Machine (FVM) team. This collaborative effort contributes to the improvement and refinement of the overall Filecoin ecosystem.

### 2. Project Links
- **Live Demo:** [https://hackfevm-frontend.vercel.app/](https://hackfevm-frontend.vercel.app/)
- **Source Code:** [Soulmates GitHub Repo](https://github.com/rohanagarwal/hack-fevm-submission)

### 3. Project Details
- **Smart Contracts:** 17 files, 11 test files, ~500 lines of Solidity code.
- **Frontend Dapp:** Fully-featured and fully-functioning React app.
- **Use Cases:** Lending protocols, DeFi solutions, storage provider reputation systems, education credentials, and more.

### 4. How it's Made
- **Smart Contract Architecture:**
  - Soulbound token engine with core, SBT, SBTFactory, and sample factories.
  - Oracles for bringing external data into the system.
  - Shared storage between all contracts.
- **Frontend Application Leverages:**
  - NFT.storage, Soulmates smart contracts, wagmi.sh, FVM mock API, and other technologies.

### 5. Technical Challenges and Achievements
- Successfully developed a comprehensive smart contract architecture and a fully-featured app within the hackathon timeframe.
- Faced and resolved numerous technical challenges, providing valuable insights for the FVM team.
- Efficiently worked as a team, showcasing effective collaboration.

### 6. Grant Objectives

| Number | Grant Deliverable    | Brief Description                                            | Timeframe         |
|--------|-----------------------|--------------------------------------------------------------|-------------------|
| 1.     | Develop UI Enhancements | Implement improvements to the user interface.                | 2 weeks           |
| 2.     | Optimize Smart Contracts | Conduct code optimization and enhance contract efficiency.   | 3 weeks           |
| 3.     | Explore Additional Use Cases | Identify and experiment with new use cases for SBTs.      | 2 weeks           |
| 4.     | Security Audit          | Perform a thorough security audit of smart contracts.         | 4 weeks           |
| 5.     | Testing and Feedback    | Deploy the updated version, gather user feedback, and make necessary improvements. | 2 weeks |

### 7. Monthly Project Updates
- *YES,* I agree to share monthly updates of the project.

### 8. Compliance with Community Code of Conduct
- *Yes,* the proposal complies with the Community Code of Conduct.

### 9. Team Information
- **Carson:**
  - *Role:* Smart contracts, front-end, integration
  
- **Chrisabdo**
  - *Role:* Front-end, integration

- **Hfccr**
  - *Role:* Front-end, integration

- **Pooja**
  - *Role:* product design, use cases
 
- **Rohanagarwal**
  - *Role:* Smart contracts, front-end, integration
  
### Project Grant Proposal Acknowledgment
*This proposal is prepared based on the information provided by the project team.*

**Comment by rohanagarwai** [comment]
Hi @ErinOCon,
I hope this message finds you well,
I would like to know if there is any update regarding this grant?

Best regards.

**Comment by ErinOCon** [comment]
Hi @rohanagarwai, thank you for your proposal and for your patience with our review process. Unfortunately, after much consideration, it has been determined that we will not be be moving forward with a new grant at this time.

I will be sending you an email shortly to discuss other ways to partner with our community. Wishing you the best as you continue to build!
