### ISSUE TITLE
Next Step Microgrant: poLateral  Filecoin Liquidity Protocol

### ISSUE THREAD

**Issue by zhxlnyu** [filecoin-project/devgrants#1713]
### 1. What is your project, and what problem does it solve? (max 100 words)
poLateral is an open-source liquidity protocol designed to offer Filecoin (FIL) collaterals as loans to storage providers (SPs). It addresses the challenges faced by SPs in meeting Filecoin's eligibility criteria for providing on-chain storage space, reducing barriers and fostering sustainable participation in the Filecoin network.

### 2. Project links
- **Link to Github repo:** [poLateral GitHub Repo](https://github.com/zhxinyu/poLateral)
- **License:** MIT

### 3. a) How is IPFS, Filecoin, or related technology used in this project?
poLateral utilizes Filecoin for collateral pledging, creating a lending pool where LPs can supply FIL assets. The protocol involves on-chain loan negotiation, with smart contracts governing collateral requirements. WFIL and sFIL tokens are implemented for seamless exchange and staking functionalities.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)
Yes.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective?
  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     | Smart Contract Deployment | Deploy and verify the Pool and LoanAgent contracts on the Filecoin network. | 2 weeks           | 
| 2.     | Token Integration      | Implement the WFIL and sFIL tokens, enabling seamless exchange and staking functionalities. | 3 weeks           | 
| 3.     | Underwrite Functionality | Develop and test the underwriting mechanism for SPs to borrow FIL tokens as collateral. | 4 weeks         | 
| 4.     | LP Interaction Features | Enhance LP interactions, including depositing, withdrawing, and atomic swap capabilities. | 3 weeks           | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?
Yes.

### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
[Link:](https://ethglobal.com/showcase/polateral-88ipp)
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
    - *GitHub:* https://github.com/zhxinyu
    - *Role:* Project Lead, Smart Contract Developer

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission [Link](https://ethglobal.com/showcase/polateral-88ipp)

**Comment by ErinOCon** [comment]
Hi @zhxlnyu, thank you for your proposal and for your patience with our review process. Unfortunately, after much consideration, it has been determined that we will not be be moving forward with a new grant at this time.

I will be sending you an email shortly to discuss other ways to partner with our community. Wishing you the best as you continue to build!
