### ISSUE TITLE
SignSplit

### ISSUE THREAD

**Issue by SignSplit** [filecoin-project/devgrants#1715]
**Project Name: SignSplit

**Proposal Category: `Integrations`,

**Individual or Entity Name:**
Company Name: NET CONTENT OÜ
Company Reg. No.: 12747425
Postal Address: Liivalaia 2, Tallinn city, Estonia, 10118

**Proposer:** SignSplit

**Project Repo(s)** Unfortunately, at the moment, we are not ready to disclose all the details of our GitHub repositories. However, we are actively working on the project and considering the possibility of opening up some of the code as part of future collaboration. We aim for transparency and are willing to share information about our work to the extent possible, taking into account our current commitments to our partners and development team.

**(Optional) Filecoin ecosystem affiliations:** We do not currently have any existing work relationships with organizations within the Protocol Labs Network.

**(Optional) Technical Sponsor:**  - 

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:**
 No

**# Project Summary**

Ultimate Creative Assets Management Solution 
Revolutionize how you manage your creative assets with SignSplit - the cutting-edge web platform and mobile application available for both iOS and Android. 
With SignSplit, safeguarding your creations is effortless. 
Utilizing blockchain ownership certificates, our platform ensures ironclad protection against unauthorized usage.
 We empower you to monitor usage statistics, effortlessly share your works, and seamlessly monetize your content. Moreover, SignSplit streamlines revenue distribution among co-owners, ensuring that everyone receives their fair share effortlessly.
At our core, we prioritize not only protecting your assets from users but also safeguarding against AI systems that may learn from openly accessible artworks.

**Our main features:** 
1) Store and manage your content
2) Record ownership details for each piece of content
3) Monetize content and let users pay easily
4) Promote your content and personal page to track statistics

**Enterprise and business solutions:**
Control use of your content with delegated rights, access to all files, ownership certificates and agreements, licenses and statistics from one dashboard. Professional business suite for bulk actions taken frequently by companies for their digital content. Our platform offers dedicated support and custom developments for business customers according to their needs.

## Impact 

SignSplit's _Creative Assets Management Solution_ 
directly addresses the critical need for content protection and monetization within the creative community, aligning seamlessly with the Filecoin ecosystem's mission to advance a more decentralized web. By utilizing blockchain ownership certificates, SignSplit ensures robust protection against unauthorized usage of digital assets, safeguarding creators' intellectual property. In a landscape where AI often profits from uncredited usage of creative works, SignSplit offers a vital solution to ensure fair compensation for creators while preserving the integrity of their content. With the potential to revolutionize content management and monetization, SignSplit's success signifies a significant step towards a more equitable and sustainable creative economy within the Filecoin network.

## Outcomes

The final outcomes and deliverables for the SignSplit project include completing the beta version of the platform, with 90% already accomplished. This beta version will provide users with essential functionality for managing and protecting their creative assets online. Key features include the ability to upload and manage various types of content, create blockchain certificates to confirm ownership details, set permissions and share files, and monetize content through paid licenses.
Success for the project will be measured by several metrics. Firstly, the launch and adoption of the platform will indicate initial success, with a focus on acquiring and retaining users.
User Acquisition:
User Sign-ups (UA)
Monthly Active Users (MAU)
Daily Active Users (DAU)

Engagement:
Session Duration
Frequency of Use
Retention Rate

Content Metrics:
Number of Uploaded Assets
Content Sharing Frequency
Monetization Rate

Transaction Metrics:
Total Transaction Volume (TTV)
Conversion Rate (CR)
Average Revenue per User (ARPU)

Security and Protection:
Effectiveness of Blockchain Certificates in Preventing Unauthorized Usage
User Satisfaction with Security Features

Collaborative Ownership:

Number of Co-owned Works
Fair Revenue Distribution Rate

These metrics will provide insights into the performance and effectiveness of the SignSplit platform in attracting and retaining users, facilitating content creation and sharing, monetization capabilities, and ensuring security and collaborative ownership.

## Adoption, Reach, and Growth Strategies

**Market Size**
Total Addressable Market - $ 3,15B
The global AI training dataset market was valued at USD 1.62 billion in 2022, which is anticipated to grow at a CAGR of 23.85% from 2023 to 2032. 
Serviceable Available Market  - $ 630M
Serviceable & Obtainable Market - $ 63M

_**Target audience**_
Music artists and songwriters 
Photographers, visual artists, and digital art creators
Book, screen/stage play,  blog, and other textual content writers
Video,UGC, social media influencer and digital content creators
AI artists
Record labels & music publishing companies 
Researchers, scientists and inventors
Software architects and developers
Artist managers and producers
Artists and designers

We are beginning the process to establish partnerships with creative industry associations which will bring initial customers to our platform (content creators, music artists and songwriters, visual and digital artists, photographers etc.).
We will intend to establish partnerships with web platforms and mobile applications which provides different instruments for content creators and digital artists (AI content editors, digital educating apps for musicians and photographers etc.) to exchange with customers base between our platform and their services.
We will launch digital as campaigns through TikTok and Facebook to reach the digital artists and content creators and promote our platform among them. 

## Development Roadmap

Project Roadmap & Milestones*
March 1- 31, 2024
Finalizing initial product features – content usage statistics and paid licenses management module launch; connection to the blockchain provider; submitting mobile application to the key app stores; translating platform to 12 languages; general platform improvements for the public launch.

April 1 – 7, 2024
Improvements to the Paid Licenses Management module – adding licenses viewing and buying analytics, conversion metrics, other analytical features that will help users analyze and improve their selling results; general platform improvements based on the user’s requests.

April 8 – 15, 2024
Improvements to the Content Ownership Management module – adding feature to unattach files from ownership certificates based on majority voting among content co-owners; adding feature of unattaching files from the parent files for which ownership certificate is issued; adding feature of automatic translation of the ownership certificates to different languages; general platform improvements based on user’ requests.

For each milestone, we require $16,000, and a team of 7 individuals works on each milestone.

## Total Budget Requested

50 000$

## Maintenance and Upgrade Plans
Our goals for the next 12 months
50,000+ active users
10,000+ active premium customers
100,000+ ownership blockchain certificates created and stored
200,000+ digital agreements and voting action blockchain certificates created and stored
10,000+ paid licenses created and are selling on our platform

## Relevant Experience

Our team possesses significant experience in creating successful products, as evidenced by our previous projects, including large-scale national and international initiatives in the education sector, such as projects with oshkola.company. We have invested our own resources into the development of this platform, recognizing that such large-scale projects require years of effort and the involvement of thousands of individuals. Our team has diverse skills and expertise necessary for the successful implementation of this project, including software development, user experience design, project management, and marketing. We are confident that our experience and dedication to this project make us the right team for its realization.

# Additional Information

 signsplit@gmail.com

Our PitchDeck https://drive.google.com/file/d/1dAnPaYf1qkF-7KFOWH4oZD1BhGEMffty/view?usp=drive_link

**Comment by ErinOCon** [comment]
Hi @SignSplit, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant for this project. Wishing you the best as you continue building!

Note: To contact our team with grant inquiries, please send an email to grants@fil.org.
