### ISSUE TITLE
Decentralized Antimicrobial Resistance Data Ecosystem on Filecoin

### ISSUE THREAD

**Issue by numpde** [filecoin-project/devgrants#1719]
# Open Grant Proposal: Decentralized Antimicrobial Resistance Data Ecosystem on Filecoin

**Project Name:** Decentralized AMR Data Ecosystem on Filecoin

**Proposal Category:** Applications

**Individual or Entity Name:** Counter-Resistance.org

**Proposer:** `numpde`

**Project Repo(s):** https://github.com/numpde/counter-resistance/tree/main/code

**(Optional) Filecoin ecosystem affiliations:** None at this time.

**(Optional) Technical Sponsor:** N/A

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

This project directly addresses the critical global health crisis of antimicrobial resistance (AMR), which currently contributes to approximately 700,000 deaths each year, with projections suggesting a rise to 10 million deaths annually by 2050 without effective intervention. We aim to develop a decentralized AMR data collection and analysis ecosystem on the Filecoin network, initially requiring some 2 petabytes of storage annually, with expectations to grow exponentially. This growth is anticipated as genomic analysis capabilities expand and as the volume of AMR-related data scales up accordingly. By leveraging Filecoin's decentralized storage solutions, we plan to establish a secure, transparent, and resilient infrastructure for AMR data. This infrastructure, coupled with advanced AMR data tools integrated into Filecoin, is designed to enhance global data contributions, improve data accessibility and reliability significantly, and support robust data analysis and forecasting initiatives to address and mitigate the AMR threat effectively.

## Impact

The project addresses the critical pain point of fragmented and unreliable AMR data storage and access, which hampers effective response strategies to AMR spread. By utilizing Filecoin, we ensure data integrity, availability, and global participation in AMR data sharing. Success in this endeavor means creating a scalable, cost-effective, and secure system for AMR data, directly contributing to better healthcare outcomes and preparedness against AMR threats. The risks of not addressing this issue include continued spread of AMR, ineffective treatment protocols, and increased healthcare costs. The impact of this project extends beyond the healthcare sector, affecting agricultural practices, pharmaceutical development, and global health security.

## Outcomes

Final outcomes include:
1. A decentralized platform for secure AMR data submission, storage, and access on Filecoin.
2. Tools for data ingestion, preparation, and analysis optimized for AMR datasets.
3. A blockchain-based incentive model to encourage global participation in AMR data collection.

Success metrics:
- Number of datasets stored and accessed via the platform.
- Active contributors and users of the AMR data ecosystem.
- Improvement in AMR data availability and reliability for research and public health decisions.

## Adoption, Reach, and Growth Strategies

The target audience includes researchers, healthcare professionals, and public health authorities worldwide. The platform aims to engage these groups through partnerships with research institutions, healthcare networks, and public health organizations. Initial user onboarding will focus on demonstrating the value of decentralized AMR data sharing and collaboration. Strategies include workshops, webinars, and pilot projects with key stakeholders to onboard the first 10 to 100 users.

## Development Roadmap

Milestone 1: Platform Design and Initial Development
- Functionalities: Basic data submission and storage on Filecoin, initial user interface.
- Team: 1-2 developers
- Funding: $10,000
- Timeframe: 3 months

Milestone 2: Data Tools Development and Integration
- Functionalities: Data preparation, ingestion tools, and initial analysis features.
- Team: 1-2 developers
- Funding: $15,000
- Timeframe: 4 months

Milestone 3: Incentive Model and Community Building
- Functionalities: Blockchain-based incentives, community engagement tools.
- Team: 1-2 developers, 1 community manager
- Funding: $15,000
- Timeframe: 3 months

Milestone 4: Platform Launch and Initial Data Collection
- Functionalities: Full platform launch, first data collection and analysis cycle.
- Team: Entire project team
- Funding: $10,000
- Timeframe: 2 months

## Total Budget Requested

| Milestone # | Description                          | Deliverables                                         | Completion Date | Funding  |
|-------------|--------------------------------------|------------------------------------------------------|-----------------|----------|
| 1           | Platform Design and Initial Development | Basic data submission and storage functionality | 3 months        | $10,000  |
| 2           | Data Tools Development and Integration  | Advanced data tools and initial analysis features    | 4 months        | $15,000  |
| 3           | Incentive Model and Community Building  | Blockchain-based incentives and community engagement | 3 months        | $15,000  |
| 4           | Platform Launch and Initial Data Collection | Full platform functionality and initial user adoption | 2 months        | $10,000  |
| **Total**   |                                      |                                                      |                 | **$50,000** |

## Maintenance and Upgrade Plans

Long-term, we plan to continuously update and improve the platform based on user feedback and advancements in AMR research and data analysis technologies. This includes expanding data tools, enhancing security measures, and fostering a growing community of contributors and users. Sustainability will be supported through ongoing grants, partnerships, and a self-sustaining incentive model that rewards valuable contributions to the AMR data ecosystem.

# Team

## Team Members

`numpde`

## Team Member LinkedIn Profiles

N/A

## Team Website

N/A

## Relevant Experience

25y+ background in coding, science/research such as computational math and bioinformatics.

## Team code repositories

https://github.com/numpde/

# Additional Information

☞ hello@counter-resistance.org

The Decentralized AMR Data Ecosystem on Filecoin aims to create a secure, globally accessible platform for AMR data collection, storage, and analysis, utilizing blockchain and decentralized storage technologies. By fostering collaborative partnerships and integrating advanced analytical tools, this initiative seeks to enhance global AMR response efforts, supported by a commitment to open-source development and community engagement. Our approach emphasizes innovation, sustainability, and inclusivity, aiming to make significant contributions to combating antimicrobial resistance.

**Comment by ErinOCon** [comment]
Hi @numpde, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!

Note: To contact our team with grant inquiries, please send an email to grants@fil.org.
