### ISSUE TITLE
Open Grant Proposal: 0xCastle

### ISSUE THREAD

**Issue by Tsatsch** [filecoin-project/devgrants#1720]
# Open Grant Proposal: 0xCastle

**Project Name:** 0xCastle

**Proposal Category:** Research & protocols

**Individual or Entity Name:** 0xCollective

**Proposer:** tsatsch

**Project Repo(s)** [0xCastle.xyz](https://github.com/0xCastle/0xcastle.xyz)

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

0xCastle is a five-day blockchain-focused educational and research retreat within the beautiful setting of a historic castle near Leipzig, Germany. It is scheduled immediately after ETHBerlin, from May 26-31. Our mission is to bring together bright minds from various ecosystems, fostering deep, collaborative research and education in blockchain technology. 

See our vision and more information about the event on the website: https://0xcastle.xyz/

## Impact 

0xCastle research retreat is not a typical conference or a meetup. It thrives on creating a salon-style atmosphere, fostering an environment where conversation flows freely and innovative ideas are exchanged naturally. This atmosphere is cultivated through a combination of structured sessions and informal interactions within the castle's surroundings. This distinctive approach makes 0xCastle an unparalleled event for both professional development in blockchain technology and enriching personal experiences. 

We believe in the idea of collective intelligence. To achieve this, we want to bring together bright minds from different ecosystems to conduct interdisciplinary research. The retreat is built on a blend of lectures, workshops, and collaborative research sessions. The main goal of 0xCastle is to facilitate understanding and developing concepts to solve Blockchain tech's most pressing problems.

Our education and research retreat covering pressing topics in Blockchain technology would be significantly enhanced by exploring Filecoin’s tech stack and IPFS technology. Filecoin’s ecosystem would benefit by facilitating knowledge exchange, accelerating the development of decentralized storage solutions, and fostering a community of engaged developers and researchers. Filecoin can provide research questions to allow participants to understand the current work in the space. Furthermore, Filecoin will receive brand recognition through mentions and branding during the event.

## Outcomes

The main goal of 0xCastle is to facilitate understanding and developing concepts to solve Blockchain tech's most pressing problems. With this initiative we will catalyze new ideas, innovations, and solutions that would drive the further development, research and adoption.

## Adoption, Reach, and Growth Strategies

0xCastle is targeting high-profile researchers, developers and blockchain enthusiasts. It is application-focused and the attendance is limited to 50-60 selected participants. Our experience in organizing events and strong outreach to previous partners and collaborators provides a solid base. Additionally, our close connections and the presence of blockchain clubs such as [Cambridge Blockchain Society](https://cambridgeblockchain.org/), [Cornell Blockchain](https://www.cornellblockchain.org/), [Blockchain at Berkeley](https://blockchain.studentorg.berkeley.edu/), [TUM Blockchain Club](https://www.tum-blockchain.com/), [KRYPTOSPHERE](https://kryptosphere.org/en/) and many more give us access to a highly engaged pool of potential attendees.

It is planned to host more events of this kind in the future allowing future events to facilitate diverse connections where individuals from various specializations can exchange insights and generate new ideas.

## Development Roadmap

**Phase 0 - Resources (January - February):**

- Milestone 1: Completion of Pitch Deck, Website, Team Structure, and Application Form.
- Deliverable: Fully developed Pitch Deck, Website launched, Team Structure finalized, Application Form ready for use.
- Milestone 2: Finalization of venue selection.
- Deliverable: Confirmed venue for the event.

**Phase 1 - Outreach (Feburary - March):**

- Milestone 3: Engagement with potential sponsors, partners, and speakers.
- Deliverable: Agreements or commitments from sponsors, partners, and speakers to participate in the event.
- Milestone 4: Launch of the application campaign.
- Deliverable: Application campaign initiated, with applications starting to come in.

**Phase 2 - Attendees (March - April):**

- Milestone 5: Finalization of sponsor contracts.
- Deliverable: Signed contracts with sponsors.
- Milestone 6: Processing of applications.
- Deliverable: Applications reviewed and accepted/rejected accordingly.
- Milestone 7: Ticket sales commence.
- Deliverable: Tickets available for purchase.

**Phase 3 - Logistics (April - May):**

- Milestone 8: Development of event content.
- Deliverable: Event agenda and content finalized based on applications and sponsor requirements.
- Milestone 9: Finalization of event logistics.
- Deliverable: Event logistics such as venue setup, equipment rental, and catering

Our roadmap adopts a dynamic task allocation model. We do not have pre-assigned roles, but we assess the project's needs at each milestone and determine the best skill sets to address them. This allows us to be responsive to shifting priorities and ensures optimal resource utilization.

## Total Budget Requested

Milestone # | Description | Deliverables | Completion Date | Funding in $
-- | -- | -- | -- | --
1 | Completion of Pitch Deck, Website, Team Structure, and Application Form | Fully developed Pitch Deck, Website launched, Team Structure finalized, Application Form ready for use. |   | 0
2 | Finalization of venue selection. | Confirmed venue for the event. |   | 0
3 | Engagement with potential sponsors, partners, and speakers. | Agreements or commitments from sponsors, partners, and speakers to participate in the event. |   | 0
4 | Launch of the application campaign. | Application campaign initiated, with applications starting to come in. |   | 0
5 | Finalization of sponsor contracts. | Deliverable: Signed contracts with sponsors. |   | 0
6 | Processing of applications. | Applications reviewed and accepted/rejected accordingly. |   | 0
7 | Ticket sales commence. | Tickets available for purchase. |   | 0
8 | Development of event content. | Event agenda and content finalized based on applications and sponsor requirements. |   | 0
9 | Finalization of event logistics. | Event logistics such as venue setup, equipment rental, and catering |   | 5,000

## Maintenance and Upgrade Plans

0xCollective is an organization that was founded with the purpose of organizing research and education-oriented events. Thereby, it is laid down to hold events of this kind in the future and continuously develop. External funding sources are considered to enhance educational opportunities and accessibility, particularly enabling student participation without financial barriers.

# Team

## Team Members

Adrian Kögl
Nour Assili
Shouvik Gosh
Jaqueline Schriefl
Johannnes Schaaf
Alexandra Häringer
Lucas Aschenbach
Alina Popp
Mila Brajkovska
Alexander Semenov

## Team Member LinkedIn Profiles

[Adrian Kögl](https://www.linkedin.com/in/adrian-koegl/)
[Nour Assili](https://www.linkedin.com/in/nour-assili-058916149/)
[Shouvik Gosh](https://www.linkedin.com/in/shouvik-ghosh/)
[Jaqueline Schriefl](https://www.linkedin.com/in/jaqueline-schriefl-76aa26182/)
[Johannnes Schaaf](https://www.linkedin.com/in/johannesschaaf/)
[Alexandra Häringer](https://www.linkedin.com/in/alexandra-h%C3%A4ringer/)
[Lucas Aschenbach](https://www.linkedin.com/in/lucas-aschenbach-021501173/)
[Alina Popp](https://www.linkedin.com/in/alina-popp-855bbb225/)
[Mila Brajkovska](https://www.linkedin.com/in/mila-brajkovska-ab132b201/)
[Alexander Semenov](https://www.linkedin.com/in/semenov-alex/)

## Team Website

https://0xcastle.xyz/

## Relevant Experience

Our team has extensive experience in web3, with both academic and professional backgrounds. We've graduated from top universities with computer science degrees, specializing in blockchain-related fields. Professionally, we've worked at leading blockchain companies like Quantstamp and Staking Facilities, contributing as developers, researchers, and thought leaders. Outside of formal education and careers, we're actively involved in the web3 community through non-profit organizations, bettering our understanding of both technical and societal aspects of blockchain. Every team member has a solid grasp of web3 technologies, with most excelling in technical development and others knowledgeable in blockchain theory. Have attended countless of hackathons and won many prizes there, web3 conferences and been part of various hands on workshops during those. Many of the team members have also been part of research teams in academia in web3 and blockchain.

Some of the previous events of members:

- [0xVillage](https://0xvillage.org/)](https://0xvillage.org/)
- [TUM Blockchain Conference](https://www.tum-blockchain.com/conference)
- [Digital Euro and CBDCs](https://www.notion.so/TUM-Co-Host-Agreement-c2988ab250674322a116a1d53607bcd4?pvs=21)
- [Consensus Student Program](https://www.youtube.com/watch?v=ng_ZCNgzFGc)
- [Blockchain@Columbia's LedgerFest](https://www.youtube.com/watch?v=_qopGYx12K4)
and many more…

## Team code repositories

[0xCastle](https://github.com/0xCastle)

[TUM Blockchain Club](https://github.com/TUM-Blockchain-Club)

# Additional Information
The https://www.useweb3.xyz/grants website helped us to find out about the Filecoin Dev Grants. In the devgrant git repository (https://github.com/filecoin-project/devgrants/tree/master), we found the Open Grants Program.

Feel free to contact info@0xcastle.xyz with any questions or for further discussion about 0xCastle.

**Comment by ErinOCon** [comment]
Hi @Tsatsch, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant for this project. Wishing you the best as you continue building!

Note: To contact our team with grant inquiries, please send an email to grants@fil.org.
