### ISSUE TITLE
Next Step Microgrant: <Mental Wealth Academy>

### ISSUE THREAD

**Issue by jhinnbay** [filecoin-project/devgrants#1721]
Hello, I have a large Figma file with many designs and prototypes, pitch deck.

I have a remote node for IPFS storing our library's material.

Also landing page https://mentalwealthacademy.framer.website/

Built hardware node to further decentralize the process and a friend told me to check out these grants, because I'm close to building my own blockchain but I don't think I need to do that.

**Comment by ErinOCon** [comment]
Hi @jhinnbay, thank you for contacting our team. Grant proposals should be submitted using our [application template](https://github.com/filecoin-project/devgrants/issues/new/choose). Please note active dev grant programs can be reviewed [here](https://github.com/filecoin-project/devgrants/blob/master/README.md). 

If you have any questions for our team, our team can be contacted at grants@fil.org
