### ISSUE TITLE
Open Grant Proposal: Utonoma: A social network based on blockchain to push people to do good things 

### ISSUE THREAD

**Issue by AstroSamus** [filecoin-project/devgrants#1722]
**Project Name:** Utonoma

**Proposal Category:** Applications.

**Individual or Entity Name:** Adrian Armenta Sequeira

**Proposer:** AstroSamus

**Project Repo(s)**

https://github.com/AstroSamus/utonoma (Smart contracts part)

https://github.com/AstroSamus/utonomaPWA (Client web application to interact with the smart contract)

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes.

# Project Summary

For communities to progress, improve, and solve their problems more quickly without directly depending on a profitable business model, it is necessary to implement an efficient incentive system that promotes productive collaboration. This is because, to date, such systems depend on the good faith, altruism of participants, and centralized committees that choose which actions are rewarded and which are not. However, there are few success stories, as most run out of resources or allow corruption to creep in.
	Utonoma is a system based on blockchain and self-managed by the community itself, which is decentralized and resistant to malpractices, such as collusion or corruption. A model where, in addition to good faith and altruism, social recognition and the  motivation to grow economically are added as incentives.
	Consists in a social network that works on the blockchain aimed at users posting content and documentary evidence of their actions with the aim of being rewarded allowing content creators to earn cryptocurrencies for each like. Only one condition: if a content has too many dislikes it will be removed from the platform with no reward for the creator. This small change in the rules allows content moderation in a democratic and decentralized way, contributing to the creation of the freer internet we all dream of.
	These cryptocurrencies are native to the system and are generated at the time of awarding the reward. Initially, they have no intrinsic value. Therefore, the system will only work if the rest of the network users appreciate and recognize the value generated within it by buying the network’s cryptocurrencies. This appreciates the reward obtained by the content creator, as it becomes scarce and valuable. It also benefits them as they can keep them to foster their own wealth, which would generate a self-perpetuating and reinforcing economic incentive system.

## Impact 

Utonoma is a social network that requires users to upload content to the IPFS network and then put the CIDs in the smartcontract. That way, the frontend app (Utonoma PWA) can display it to the user. Different content types can be uploaded and we require a big amount of storage space that Filecoin may provide. Also, as it's necessary for users to spend Utonoma tokens to vote for content (to avoid bots), we think that we may incentivise users to vote by offering premium on demand content to the users that vote a certain amount of times. This requires that we give conditional access to IPFS files depending on the number of votes that a user emits on a certain period time, something that we can archive with Filecoin.
	If Utonoma archives their objectives we'll have a more decentralized social network that is censorship resistant as moderation of content is based on the morality of the community, meanwhile it spreads the usage of the blockchain for a wider audience. 
	We hope to be the reference social network for users looking for privacy and freedom of speech.

## Outcomes

A full and versatile social network app that can be installed on the mobile devices and desktop (PWA) that allows the users to interact with the Utonoma contract in a simple and fun way (please check the roadmap to see the details, there you’ll find the committed functionalities written as user stories)
The application is written in React and JavaScript and allows users to interact with the smart contract on the Filecoin network via Ethers.js library and connect their wallets using the WalletConnect modal. The smart contracts part it’s already done, and now we are completely focused on created a PWA to interact with it.

Measuring Success.
We believe that most of the web3 applications fail because of the big inflation in their economies. For that, Utonoma has a coin emission system that gives more coins when there are few users in the network. This is necessary because it seeks to motivate new users with more coins to join and contribute to the network early. Later, when there are more users, the coin emission will be fewer.
	To have success, our main objective it’s to keep a low inflation at the time that new coins are emitted to keep rewarding users. For that, our goal is to increase the number of users and the market capitalization of Utonoma's tokens. 
Our KPIs are:
Circulating Supply 
Market cap
Monthly active users
Cost per Lead by Channel
Customer Acquisition cost

Note: The smart contract has a native way for calculating the MAU (monthly active users) and considers as “active users” the addresses that upload and vote for content.

## Adoption, Reach, and Growth Strategies

Once the application it's finished we want to engage users in the following way:
- Users can start to enjoy content with no barriers, no login, no paywalls to have the minimum possible friction. 
- Once they start to like content they may want to save it for later. For that, they can login using a crypto wallet, this will create a local profile on the user's device that they can backup in the IPFS network in an encrypted way without any personal information.   
- Later they will want to reward users that they think deserve it or punish users that behave bad, and they will buy the Utonoma token to like or dislike content.
- After, they will realize that if they vote a certain amount of times every month they can access premium content. This will fully engage them into the Utonoma experience.

During the development of the project we expect to catch audiences like this, each step corresponds to one product increment:
1. Catch the crypto world's attention by doing demonstrations on crypto conventions and activation dynamics with our simple MVP.
2. Reach the small content creators (content creators that cannot monetize as the have not enough audience) and convince them that with Utonoma they can monetize starting from a really low number of likes (only 6 likes are needed to cash the reward).
3. Attack the market of social network users that want more privacy
4. Reach a more mainstream audience, by offering on demand content to users that vote a certain amount of times. For instance, a user may find more convenient to vote a high number of times during the month and access the "on demand" music streaming service that Utonoma offers, instead of paying a Spotify membership. That way they can reward their favorite content creators at the time they access the music they love.

We expect early adopters to be crypto enthusiasts and people that does altruistic work
In the mid term we expect the target audience to be similar to the audience of the Mastodon social network.

## Development Roadmap

[Utonoma development roadmap 2024.pdf](https://github.com/filecoin-project/devgrants/files/14686612/Utonoma.development.roadmap.2024.pdf)

Please check the attached PDF file that contains our roadmap, note that the deliverables are written as user stories with the approximate start and finish dates

## Maintenance and Upgrade Plans

Utonoma it’s a social network focused on respect the privacy of the user, this means that we aim for a client web application that interacts as directly as possible with the Filecoin network. This poses a great technical challenge as the user information (favorite, subscribes, preferences, etcetera) needs to be stored on the device and be synced in all places where the user is logged, all with no central server. Also, the filters of explicit content and the recommendation system should work completely on the client.
The long term upgrade plans are really related to the performance optimization of the web application, with an optional Android and iOS port of the web app.

# Team

## Team Members

Adrian Armenta Sequeira
Gerardo Pedrizco Vela

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/adri%C3%A1n-armenta-sequeira-85a53617a/
https://www.linkedin.com/in/gerardo-pedrizco-vela-a2a786232

## Relevant Experience
We met at university, in Mexico City, our hometown, during a Blockchain course in 2018. Became great friends immediately and discovered the great combination that we could create by merging the economic and financial knowledge of one, with the technical and technological knowledge of the other.
Half a year later we created Kobold FX with the intention of producing computer robots that could perform automated trading in different markets, mainly in Forex, the software produced (written in  C/C++) is still in use today. It’s not open sourced but some products can be found in sale in this store:  
https://www.mql5.com/en/market/mt4?filter=koboldFX&Filter=kobold
Our earnings come from private use of the trading software but also selling some of it.

The idea of Utonoma came in 2019 when we were resting at the school and thinking about what we could do to improve our school and push people to do things for the university community.

Individual backgrounds:
Adrian Armenta Sequeira: I’m a full stack developer with more than 5 years of experience, with expertise in Android OS and web development. Working with languages like C#, Javascript, Java, and C/C++. Prior to this project, I used to work as an Advanced Software Engineer in Honeywell, my day to day work required good communication and leadership skills.

Gerardo Pedrizco Vela: I’m an Economist, independent trader with passion for technology. Winning the 1st place in the John Hull Derivatives Trading Competition from the Mexican Stock Exchange in 2023. Also, founder and community manager of CriptoUNAM, a robust and active university community focused on creating events like conferences and hackathons for students. I have a company called Vending Stelar that sells vending machines in the local Mexican market.

# Additional Information
We learned about the grants program while looking in the online Filecoin documentation
Reach us in: adrian.sequeira@utonoma.com
Check our white paper to find all the details of the project, like the coin emission system, and other technical and social problems that we solve with the system: https://utonoma.com/paper/utonoma_en.pdf

**Comment by ErinOCon** [comment]
Hi @AstroSamus, thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. Wishing you the best as you continue building!

To contact our team with grant inquiries, please send an email to grants@fil.org.
