### ISSUE TITLE
Next Step Microgrant: Founder, 0xFreePlay

### ISSUE THREAD

**Issue by 0xFreePlay** [filecoin-project/devgrants#1723]
0xFreeplay: Empowering Creators with Decentralized Video Storage on Filecoin (GitHub Proposal)

Project Title: 0xFreeplay - Leveraging Filecoin for Secure and Permanent Creator Content Storage

Project Lead: [Oluwafemi Olokode]

Project Summary:

0xFreeplay is a revolutionary video streaming platform built on the blockchain, empowering creators with direct monetization and community engagement. We propose integrating Filecoin, a decentralized storage network, to offer creators a secure, permanent, and cost-effective solution for storing their video content.

**Problem:**

* Centralized video storage platforms often have high costs, limited control for creators, and potential censorship risks.

**Solution:**

By integrating Filecoin, 0xFreeplay offers creators:

* **Decentralized Storage:**  Videos are stored across a global network of independent storage providers, eliminating reliance on centralized servers and censorship concerns.
* **Cost-Effectiveness:**  Filecoin leverages a robust economic model, potentially offering lower storage costs compared to traditional platforms.
* **Permanence:**  Filecoin incentivizes storage providers to ensure data availability for extended periods, guaranteeing long-term accessibility for creators' content.

**Integration Plan:**

* Develop a secure and efficient Filecoin integration within the 0xFreeplay platform.
* Allow creators to seamlessly choose Filecoin for video storage during the upload process.
* Implement functionalities for managing stored content on Filecoin from the 0xFreeplay platform.

**Benefits for Filecoin:**

* **Increased Network Usage:** 0xFreeplay can significantly contribute to Filecoin's storage capacity utilization and overall network growth.
* **New User Base:**  Attracts creators and viewers within the video streaming space to the Filecoin ecosystem.
* **Enhanced Use Case:**  Demonstrates Filecoin's value proposition for real-world applications within the creative economy.

**Call to Action:**

We propose collaborating with the Filecoin community to explore the technical and economic feasibility of this integration. We are open to exploring various collaboration models, including:

* **Grant Funding:**  Requesting a grant from Filecoin to support the development and implementation of the Filecoin integration within 0xFreeplay.
* **Technical Support:**  Seeking guidance and collaboration from Filecoin developers to ensure a smooth and secure integration process.
* **Ecosystem Partnership:**  Exploring broader partnership opportunities to promote Filecoin storage solutions within the 0xFreeplay platform and the creator community we serve.

**Next Steps:**

* We are committed to open-source development and will share the codebase for the Filecoin integration on GitHub upon completion.
* We will actively engage with the Filecoin community, seeking feedback and collaborating on the project's ongoing development.

**Conclusion:**

By integrating Filecoin, 0xFreeplay empowers creators with a secure and permanent storage solution for their valuable content. This collaboration fosters innovation within both ecosystems, promoting decentralized video streaming and the future of content ownership within the Web3 space.

**We look forward to collaborating with the Filecoin community to bring this vision to life!**

**Comment by ErinOCon** [comment]
Hi @0xFreePlay, thank you for your proposal. The microgrant program is not open to new applications at the moment, but please feel welcome to review our [Open Grant program](https://github.com/filecoin-project/devgrants/blob/master/Program%20Resources/Open%20Grants%20README.md) criteria. 

If you have any questions, you can reach our team at grants@fil.org.
