### ISSUE TITLE
SitYEA - AI Helth app 

### ISSUE THREAD

**Issue by sityea** [filecoin-project/devgrants#1724]
SitYEA.io - AI which helps computer users avoid back pain.
We’re on a mission to become a leading health AI app for daily computer users (crypto traders are the perfect fit ;) 

There are numerous apps for walking, jogging, or even sleeping, and we're here to take over the sitting area, which is yet undertaken! 

- 70% of office workers[ spend >5 hrs/day sitting](https://www.sciencedaily.com/releases/2012/01/120113210203.htm) on computers;
- Sitting causes back problems and 14+ other diseases;
- In China 70M people experience[ back pain](https://journals.lww.com/pain/fulltext/2019/01000/the_prevalence_and_years_lived_with_disability.24.aspx);
- Americans spent[ $134 billion](https://jamanetwork.com/journals/jama/article-abstract/2762309) on healing back-related problems. 

Product: We developed AI which analyzes a posture through a webcam, notifies to sit correctly and do proper breaks. Product alpha is live for Windows and Mac users, Crypto wallet integration, token, and NFTs on testnet are also done. Freelancers, traders, or any office workers are perfect users.

Our product is based on AI scientific research by our co-founder:
* 3D object recognition https://www.mdpi.com/1424-8220/20/7/2025 
* Human recognition trough a webcam: https://ieeexplore.ieee.org/document/9594811 
* Posture detection https://peerj.com/articles/cs-442/ 
* Tiredness monitoring trough a webcam https://www.mdpi.com/2079-9292/12/5/1130 

Business model: We merge WEB 2.0 revenues from monthly subscriptions + WEB 3.0 token and NFT sales, which would maximize revenue for our investors/shareholders same time incentivizing user's healthy behavior

Team: We have a small but super team. 
- I (CEO) am building IT products for 10 years.  Rytis (CTO) holds a Ph.D. in computer science, is a professor at two universities, and author of 268 scientific publications. 
- Vilma (COO) - Harward graduate and recently made an exit. 
- Plus a few developers and a couple of marketing people.

Traction: We raised $120k, exceeded 1.000 downloads, and attracted >5k community on Twitter, Telegram, Discord, and Linkedin. For NFT collection and community growth strategic partnership with Dappradar was agreed.

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-2eab281d-7fff-a802-1114-1f4b8eb7b791"><div dir="ltr" style="margin-left:0pt;" align="left">
Milestone | Goals | Duration | Grant amount
-- | -- | -- | --
Milestone 1:Dapp launch on FileCoin | - Launch $YEA (ERC-20) token on FileCoin- Develop Web dashboard (frontend+backend) - Connect desktop app (Win+Mac) with Web dashboard- Connect Web app with FileCoin blockchain- New SitYEA version with 15% increased accuracy- Reach 4,000 monthly active users | 4 months | $35,000
Milestone 2:Reach 40k users | - Staking program development- KOLs, PR, and partnership campaigns- Reach 40,000 monthly active users | 6 months | $25,000

</div></b>

SitYEA website: [www.sityea.io](https://www.sityea.io/)
Pitchdeck: https://drive.google.com/file/d/1sjduT-e05mg8SaqFFFsGaLxoCJm1Rwos/view?usp=sharing
Whitepaper: https://sityea.gitbook.io/whitepaper/ 
AI scientific research (by our co-founder):
3D object recognition[ www.mdpi.com/1424-8220/20/7/2025](https://www.mdpi.com/1424-8220/20/7/2025)
Human recognition trough a webcam:[ https://ieeexplore.ieee.org/document/9594811](https://ieeexplore.ieee.org/document/9594811)
Posture detection[ https://peerj.com/articles/cs-442/](https://peerj.com/articles/cs-442/)
Tiredness monitoring trough a webcam[ www.mdpi.com/2079-9292/12/5/1130](https://www.mdpi.com/2079-9292/12/5/1130)
SitYEA desktop application:
Mac OS: https://drive.google.com/file/d/1QRrlzeJu34EfG1M2GBK25ojxjjuTLzoD/view?usp=sharing
Windows: https://drive.google.com/file/d/1T-_1MHUTO_RztjRPJ7i3ZciVD2SWtV1T/view?usp=sharing
Video presentations:
Intro: https://youtu.be/WharBhHDBEM
Demo: https://youtu.be/x4G61313ZxE
Team: https://youtu.be/1LdfZ0kDAvo 
Wireframes / designs / technical description: https://docs.google.com/document/d/1RFqZEduiU74rNtA3zJUyVWgf4LnNZUKegcSYQi07R4Y/edit?usp=sharing 
Project (marketing) timeline: https://docs.google.com/spreadsheets/d/1Z81oCh1b2NPO0nQGy9haZC0cxgHWkRmOVuXsxKznsbo/edit?usp=sharing
Partnerships agreed with following partners: Dappradar, Bitdegree, Jumptask.io, Galxe

**Comment by ErinOCon** [comment]
Hi @sityea, thank you for your proposal! Can you resubmit this proposal using our Open Grant program [template](https://github.com/filecoin-project/devgrants/issues/new/choose)? You may also find our program criteria helpful ([here](https://github.com/filecoin-project/devgrants/blob/master/Program%20Resources/Open%20Grants%20README.md)).

If you have any questions, our team can be reached at grants@fil.org.

**Comment by sityea** [comment]
Good day,
haven't we use the template? Did we used the form wrong?

Maybe you have the form to fill?
