### ISSUE TITLE
BONOVAC Ecosystem

### ISSUE THREAD

**Issue by bobby4programming** [filecoin-project/devgrants#1725]
I plan to build an ecosystem  utilizing blockchain that utilizes a singular coin to conduct transactions for each brand of service hence increasing its use case. can i secure funds to help with preliminary costs and costs of operation for my project

**Comment by ErinOCon** [comment]
@bobby4programming To submit a grant request, please review our [program criteria](https://github.com/filecoin-project/devgrants/blob/master/Program%20Resources/Open%20Grants%20README.md) and application [template](https://github.com/filecoin-project/devgrants/issues/new/choose). This issue has been closed.
