### ISSUE TITLE
BFlo and the SDGs, A Sustainability Commons

### ISSUE THREAD

**Issue by AmySeidman** [filecoin-project/devgrants#1728]
**Project Name:** 'BFlo and the SDGs, A Sustainability Commons''

**Proposal Category:** `Developer and data tooling`

**Individual or Entity Name:** Two options: 
- Noble Profit PBC, the core developer of BFlo.
- BFlo, a project of WinWinGive, 501c3. 

_Note: a fiscal sponsor fee is charged as an additional administrative cost. 

The project is being built as a public good and Noble Profit, as the core developers, are committed to this and we can discuss together the best entity to have this fall under._

**Proposer:** `https://github.com/AmySeidman`

**Project Repo(s)** https://github.com/BFLOio 

**Filecoin ecosystem affiliations:** ` `Filecoin/IPFS: Highly Commended prize at TheGraph Hackathon 2022, affiliated to former and present employees via community, Gitcoin Kernel/Apollo Fellow, Top 20 Projects in 2020: Apparel Hot Spots for Forced Labor’

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

Never before have we needed a source of unhackable truth to insure the voice of people and the planet where Web3 and decentralized data provides a solution. "BFlo and The SDGs" is the seed of the BFlo Sustainability Data Commons, a public good for humanity to access open data claims related to climate and impact. 

We are racing toward the 6th mass global extinction with rapid decline in biodiversity amid the throes of climate change while tens of millions are slaves subject to forced labor suffering in the shadows of our lives and our social fabrics are challenged. Our world is rife with change and instability. With the rapid advance of AI, we have great opportunities to exponentially evolve with technology. We also have an increase in misinformation. 

BFlo technology helps track, verify and manage sustainability claims for proof of reputation. By leveraging BFlo technology and Filecoin’s decentralized storage, we are bringing data permanence and the structure for data within the Web3 ecosystem to establish a basis for transparency and the ability to align Web3 projects with these global goals. 

We are leveraging the Sustainable Development Goals (SDGs) to categorize data attestations around the world by nonprofits, governments, finance and business - and people. By starting with reported SDGs by country to seed the Sustainability Data Commons, we are designing and implementing the architecture necessary to achieve a standard way of representing these kinds of attestations over the decentralized web.

## Impact 

_The Big Picture Impact:_This grant also meets Filecoin’s mission for The Public Data Commons “to support open data initiatives in partnership with governments and official organizations…to make public data more resilient, accessible, and cost-effective while also increasing accessibility.”

We see continuing to build out the data tooling for BFlo Sustainability Commons across value chains and ecosystems, to provide access to open data, to support global initiatives that are bridging Web3 with Web2, and to facilitate decentralized access to the world’s information. 

_Addressing pain points_: Lack of transparency and accountability around sustainability claims affects everything. As a result of these clamoring concerns, over 14,000 governments, finance and business entities agree to meet the SDGs. Yet we can’t see their results when they are, and many aren’t.

_Benefits_: Transparent data for sustainability enables informed decision-making and promotes ethical practices. BFlo can potentially help billions of people have a voice and representation, governments, businesses and investors to make informed choices, and nonprofits to advocate by providing a forum for transparent and verifiable sources of SDG data.

_Risks of not getting this right:_ While Nature will survive and reset, not solving climate change and human suffering, is the blight of generations and the countless species we rely on in our delicate web of life. On the climate side, disconnected data and missing trust leads to inaction. Inaction shall lead to not only loss of life, but our livelihoods with a 10% GDP loss in 2040 totaling $16T. On the finance side of climate, private investors lost $200B in 2022 due to lack of climate data. Private money for climate finance requires public results. And we need action and funding to solve the climate and humanity crisis.

Meanwhile, Impact must be triangulated to climate as if we do not have ubiquitous adoption, all sectors will fail. SDGs are essential to humanity and nature flourishing in future. The UN estimates that achieving the SDGs requires an additional $2.5 trillion annually. Inaccurate sustainability claims diverts resources and action away from impactful solutions. 

BFlo is a valuable connective tissue within global data commons initiatives. Value to Filecoin is in meeting the organization's mission for open data, and providing meaningful intelligence to  help guide us collectively toward the world we want to exist.

By providing transparency in SDGs, BFlo technology can play a critical role in ensuring accountability for sustainability commitments, ultimately accelerating progress towards a more sustainable future. 

## Outcomes

BFlo’s Sustainability Data Commons roadmap includes designing a standard way of representing information accessible in the Filecoin ecosystem for SDG claims. 

The project will provide the tooling structure for reported Sustainable Development Goals (SDG) available by country and a dashboard interface.

The BFlo Sustainability Data Commons includes SDG claims by country as a public good for everyone seeking to solve climate and sustainability challenges. Connecting BFlo’s SDG system to Filecoin, we can seed the BFlo Sustainability Data Commons as part of the greater ecosystem.

Deliverables include:

- Defined data references and structures 
- Cleaned, processed and organized data 
- Integrated Filecoin with BFlo’s technology stack 
- Ingested and processed data
- Commited available SDG country reports to demonstrate
- Commited additional reports as permissioned by data owners
- BFlo Commons Explorer: browser interface 
- Develop a browser based interface using REACT that connects the front end to the BFlo Data Commons on Filecoin to view SDG country commitments
- FAQ explaining the interface, data and how to use it

Success includes:
Ability for folks to access the BFlo Data Commons via the Explorer
Continued growth of data uploaded to the BFlo Sustainability Data Commons
We report out metrics using BFlo and align with the SDGs.

## Adoption, Reach, and Growth Strategies

Our target audience encompasses a broad spectrum of stakeholders, including:

- Businesses seeking to measure, report and verify their impact
- Investors to evaluate ESG performance, verify due diligence
- Governments policymakers and funders seeking transparent climate finance allocation to track progress on national
- Serving NGOs, civil society organizations, impacted underserved communities to leverage for data-driven advocacy
- Citizens and workers who need to be represented, have governance, safeguards  and a voice.
- Partners and alliances include agencies, NGOs, business communities and tribal entities.

We have modeled over 5000 use cases in our system to test including banking, finance, investments, DAFs, grants, carbon credits, impact and corporate statements among a few. We have also done pilots from finance to circularity, corporate social responsibility (CSR) to apparel.

We are part of multiple communities, international organization and agency working groups, and have established strategic relationships to actively scale through partnerships.

## Development Roadmap

Key milestones for the "BFlo AND THE SDGs" project during the initial development phase (Months 1-3). Estimated timeline is 3-4 months. Each milestone details the functionalities achieved, resources required, and estimated timeframe.

Dates will be set based on timing of grant receipt. Milestones developed are as follows:

Project Manager / Producer: $12,000 (allocated throughout Months 1-3)

This covers producing the project, ongoing project management tasks, and overall project oversight, announcements and communications.

Administration & Operations: 3.5% of total budget covers the admin costs for  administration, bookkeeping and reporting. 

_Milestone 1: Architecture & Data Prep (Month 1 & Month 2 - $17,000)_
Team:

- 1 Full-Stack Developer (data structures, cleaning & processing)
- 1 Data Engineer (work with full-stack developer and analyst)
- 1 Data Analyst (data analytics, reference & structure definition)
- Front end designer (reviews joint discussions to ensure final outcome and address any questions and suggestions)
- DevOps

Functionality:

- Define data schema and reference points for storing SDG claims
- Clean, process, and organize data for efficient storage and retrieval.
- Establish development operations (DevOps) procedures for smooth workflow.

Deliverables:

- BFlo Sustainability Data Commons - Decentralized SDG Architecture definitions
- Cleaned and processed SDG data country level data
- Cleaned and processed data from Noble Profit pilots as permissioned by users
- Established DevOps procedures
- Plan for interface
- Project management - plan and workflow tools

_Milestone 2: Integration (Month 2 & Month 3 - $23,000)_

Team:

- 1 Full-Stack Developer (smart contract integration, data ingestion)
- 1 Data Engineer (work with full-stack developer, blockchain developer and analyst)
- 1 Blockchain Developer (Filecoin integration)
- 1 Data Analyst (review cycle, question/answer session)

Functionality:

- Integrate Filecoin with BFlo's technology stack
- Test smart contracts to facilitate hash documentation for data storage and access on Filecoin
- Ingest and process prepared SDG data into the BFlo data commons on Filecoin
- Commit publicly available SDG country reports into the BFlo data commons on Filecoin.
- Commit BFlo's open SDG reports (with permission from data owners) into the BFlo data commons on Filecoin.

Deliverables:

- Functional integration of Filecoin and BFlo technology stack
- Establishment of BFlo Sustainability Open Data Commons associate with contract for establishing knowledge graphs of on-chain attestations
- SDG data uploaded and committed to the BFlo data commons on Filecoin
- On-chain records of IPFS hash

_Milestone 3: Front-End & API Integration (Month 3 - $18,000)
Team:_

- 1 Front-End Developer (React development)
- 1 Full-Stack Developer (API development and integration)
- DevOps

Functionality:

- Develop a browser-based BFlo Commons Explorer v1 using React
- Integrate the BFlo Commons Explorer with the BFlo Data Commons API for data retrieval and visualization
- Enable users to view SDG country commitments through the BFlo Commons Explorer (interface)

Deliverables:

- Test version of BFlo Sustainability Data Commons with populated data
- Explorer v1 with API integration with Filecoin
- Users can access and view SDG country commitments
- User can access and explore test net records

_Milestone 4: QA/FAQ/Data/Refining/Commit (Month 3 - $9,000)
Team:_

- 1 QA Tester
- 1 Technical Writer
- 1 Data Analyst
- 1 Full Stack Developer
- 1 Blockchain Developer

Functionality:

- Conduct thorough Quality Assurance (QA) testing to identify and fix bugs
- Develop a comprehensive FAQ and Read.me guide 
- Continuously refine data modeling based on QA feedback and identified needs
- Refine functionalities based on QA findings.

Deliverables:

- Bug-free BFlo Commons Explorer v1
- User guides (FAQ & Read.me)
- Refined data modeling based on initial testing
- Test on-chain transactions and decentralized storage
- Test as part of QA on test net
- Run several initial transactions before committing all reports 

Final Commitment

- Commit all reports once successfully addressing QA and any bugs

## Total Budget Requested

The roadmap timeline runs over a 3 month period from the date of the grant receipt. Milestones will be developed in parallel as follows:

<table>
 <thead>
   <tr>
     <th>Milestone</th>
     <th>Description</th>
     <th>Deliverable</th>
     <th>Schedule</th>
     <th>Funding Cost</th>
   </tr>
 </thead>
 <tbody>
   <tr>
     <td>1</td>
     <td>Architecture & Data Prep</td>
     <td>
       BFlo Sustainability Commons SDG Architecture<br>
       <p>- Define data references and structures<br>
         <p> Data Prep<br>
   - Clean, process, and organize data </br>
<p> Dev Ops</p></td>
     <td>Weeks 1 - 5</td>
     <td>$17,000</td>
   </tr>
   <tr>
     <td>2</td>
     <td>Integration</td>
     <td>
       FileCoin, BFlo Tech Smart Contract Integration<br>
       <p>- Integrate Filecoin with BFlo’s technology stack<br>
       - Ingest and process data<br>
       - Commit available SDG country reports<br>
       - Commit BFlo's open SDG reports as permissioned by data owners</p>
</p>
     </td>
     <td>Weeks 5 - 11</td>
     <td>$23,000</td>
   </tr>
   <tr>
     <td>3</td>
     <td>Front End & API Integration</td>
     <td>
       BFlo Commons Explorer V1 Front and BFlo API Integration<br>
       <p>- Develop a browser-based interface using REACT that connects the front end to the BFlo Data Commons on Filecoin to view SDG country commitments</p>
     </td>
     <td>Weeks 12 - 14</td>
     <td>$18,000</td>
   </tr>
   <tr>
     <td>4</td>
     <td>QA/FAQ/Data/Refining</td>
     <td>
       QA to find and squash bugs</br>
FAQ Read.me guide</br> 
Continued Modeling of Data</br>
Refining based on QA responses</p>
     </td>
     <td>Weeks 14 - 16</td>
     <td>$5,000</td>
   </tr>
   <tr>
     <td></td>
     <td>Project Management</td>
     <td>
       Project management over three months, admin and other supportive tasks</p>
     </td>
     <td>Project duration</td>
     <td>$12,000</td>
   </tr>
   <tr>
     <td colspan="4">Total Budget</td>
     <td>$75,000</td>
   </tr>
 </tbody>
</table>

Team scope of work includes research and implementation of features such as preparing data and defining optimized format and methods to ingest and view on-chain hashes and decentralized data

## Maintenance and Upgrade Plans

_For maintenance_
Updates will be performed and released to the BFlo Sustainability Data Commons. These may include data sets we prepare, frontend user experience improvements, backend services and smart contract upgrades as we optimize our processes.
We anticipate with use there will be nuances, we look forward to battle testing and shall continue to refine as time and resources allow.

_Our Plans In Future To Improve Over Time_
We can leverage this seed as a basis to establish knowledge graphs and benchmarks for transparent data, to enable connecting claims, credentials, contributions and transactions in relation to transparent real world assets that answer the needs of people and planet. By doing so, we can begin to map the global ecosystems to make intelligent decisions around the flow of resources, while leveraging Web3 tools for digital ecosystem governance.

We are designing toward plans to:

- Add additional frameworks and bridges to the BFlo Commons
- Create and index knowledge graphs  
- Digital Identity and verifiable credentials
- Educate web3 implementation and technologies: deepen understanding of the benefits of decentralization, broaden awareness of the technologies we use and are creating, promote adoption by relevant ecosystem players 

# Team

## Team Members

- Amy Seidman, producer, designer, technology systems thinker, blockchain innovator
- Gary Fitts, technologist and mathematician, documentarian, Web3 explorer, legacy systems expert
- Davit Akobia, REACT, full stack developer and W3 developer
- Gurpreet Singh, financial analyst

Other developers and team mates who work with us shall be credited according to participation, availability, timing and budget allowances

## Team Member LinkedIn Profiles

- Amy Seidman, https://www.linkedin.com/in/amyseidman/
- Davit Akobia, https://ge.linkedin.com/in/davit-akobia-b944341b4 
- Gary Fitts, https://www.linkedin.com/in/garyfitts/
- Gurpreet Singh, https://www.linkedin.com/in/gurpreet-singh2504

## Team Website

https://BFlo.io
https://twitter.com/bflotech

## Relevant Experience

Amy is an innovator and early adopter of new technologies whose main skills are systems thinking and design, with deep experience in both media and technology development, as well as a sustainability background as founder of Noble Profit to inform the work. As an early adoptor of Web1 through Web3, Amy began building websites and interactive media and tech for entertainment studios, global companies and NGOs since the beginning of the web. A systems thinker, environmental activist and educator, Amy's work is led by deep conviction and a creative mind.

Gary brings experience of projects with large user networks and the first peer to peer networks, plus his work with academic data modeling offers unique perspectives on implementation and building across different systems. He has been a participant in modeling climate change with Lawrence Berkely Labs and most recently Rand Corporation, was a part of the team that created TOPs and built the first microprocessing website. Gary spends time with horses and is committed to the community and his family.
Davit has been working as a fullstack and blockchain developer. His background includes networks and bringing hardware and software together. He has also been a University professor and has a deep passion file 
GP has been providing robust financial modeling providing and operational support to the company. Bringing with him his MBA and experience working on structured finance and loan administration at BNY Mellon, and Motilal Oswal Securities Ltd.
_A little Bit of History_
Amy and Davit won a Filecoin notable project award at The Graph Hack 2022. They also both contributed as commenters to the recent smart cities sustainability framework with IEEE.
Gurpreet supports product development with an eye of the financial analyst, supports the admin and operations, as well as helps on financial data modeling with the project.
Amy has been a Gitcoin Kernel Fellow and an Apollo Fellow (the Filecoin fellowship track), advised UNEP on blockchain in 2018, a speaker at COP, UNGA, Davos, YLP, Earthx and other venues as a subject matter expert for sustainability, SDGs and Web3; as well as member of the UN RISD SDPI Working Group, IEEE Planet Positive Sustainable Smart Cities Framework Working Group, Climate Coalition member among a few.

## Team code repositories
We have been developing this tech under stealth mode due to the nature of the project’s integration to ensure veracity of truth and reputation, as well as the NDAs we have signed for associated project and pilots.

This project will be open source for the the open data accessible via an API

As we strengthen the network and our trust lines, we will open source access to the registry for verifiable credentials. And we shall roll out other tools and features to enable builders and developers to collaborate with the ecosystem.
Team member Github addresses:

Davit Akobia:  https://github.com/DM41131
Amy Seidman: https://github.com/AmySeidman
BFlo: https://github.com/BFLOio

# Additional Information

We have had an open grant application for some time. Our grant was approved. 

Please see https://github.com/AmySeidman/devgrants/blob/patch-1/open-grant-proposals/open-proposal-BFLO_AND_THE_SDGs.md
And 

While it was approved, it has not yet been provided. We were asked to reformat the proposal for the new format.

We learned about the Filecoin grant program years ago. Amy Seidman was an Apollo fellow as part of Filecoin’s Gitcoin Kernel cohort.  We were invited to apply and submitted a proposal. And again invited to Filecoin Green. 

We are already emailing with the Filecoin team Stef and Erin.
A big thank you for considering our proposal.

:)

**Comment by ErinOCon** [comment]
Hi @AmySeidman, thank you for contacting our team regarding this proposal and for your time with the resubmission. Unfortunately, after careful consideration, we have determined the scope of this project does not align with the current priorities of our program. With this in mind, I have reached out to you by email at [grants@fil.org](mailto:grants@fil.org).

Thank you again for your time with this proposal.
