### ISSUE TITLE
Open Grant Proposal: ByteAI

### ISSUE THREAD

**Issue by ByteAI-DevTeam** [filecoin-project/devgrants#1730]
**Project Name:** ByteAI

**Proposal Category:** `Applications`

**Individual or Entity Name:** ByteAI

**Proposer:** ByteAI-DevTeam

**Project Repo(s)** 

https://github.com/ByteAI-DevTeam/ByteAI-Miner (Open-source miner)

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

In a world filled with misinformation and bias, ByteAI is a decentralized platform democratizing impartial news access through AI agents and leveraging the crypto ecosystem to enhance sustainability and build incentives. Our products include news channels on Telegram that publish news and summarise it for our readership. Each channel's system agent ingests hundreds of articles daily via a vast decentralised network of proprietary RSS feeds. 

We currently use rudimentary LLM base transformer models to ordinally rank the articles before permanently storing them in large private databases before further processing via statistical methods and euclidean distances to derive precisely orthogonally relevant news. Rule based systems only care about mathematical accuracy and hence are always objective. This technique blackbox strengthens objectivity in a world of smokes and mirrors and increases resistance to emergent manipulation risks.

## Impact 

There is an essential need for unfiltered and up-to-the-minute information to navigate the rapidly evolving crypto markets. In an ecosystem where every second counts, staying informed is not just an advantage; it's a necessity. As crypto enthusiasts and investors strive to make informed decisions, the platform recognizes the urgency of providing timely news and diverse perspectives. Cryptocurrency markets operate 24/7, making real-time insights indispensable for understanding market trends, regulatory shifts, and emerging opportunities. The absence of censorship ensures that users receive unaltered information, empowering them to form accurate judgments and execute well-timed actions. Integrating Filecoin then furthers the cause of decentralization of media.

## Outcomes

Making unbiased summarized insights accessible to everyday citizens, not just those who can afford expensive analytics tools or Wall Street level Bloomberg terminals. 

Levelling the information playing field, mitigating editorial bias and fake news by leveraging decentralized networks, objective statistical methods, and crowd-sourced vetting to distil the signal from the noise - to produce summaries and insights users can trust as neutral. 

Ingesting, filtering, and connecting information across a wide array of global news sources, statements, regulatory filings, journal archives, and multimedia feeds to solve information asymmetry. No single source has the whole picture - ByteAI aims to fuse all the fragments through AI and web3 infrastructure to empower more informed decisions. 

Offering free channels utilizing sponsorships to provide freedom of unbiased and objective information for those unable to afford quality tools like ours. Access should not be gated only for the wealthy. In summary, making impartial and holistic intelligence that helps navigating complexity more achievable - that is the essence of the societal problem ByteAI intends to tackle.

## Measuring Success

Our current functional news channels with over 2,000 subscribers can be found on Telegram and added to any channel to forward up to date market insights. Our agents can be divided into three categories: crypto market insights, geopolitical insights and general financial insights, each respectively having its own news channel. 

Our KPIs are:
Market cap
Subscribers on our news channels

## Development Roadmap

https://byteai.gitbook.io/byteai-whitepaper/roadmap

# Team

## Team Members

James Joyce (Consultant)
Tensor Flow Surfer (Developer)

## Team Telegram

https://t.me/tensorflowsurfer

## Team Website

https://byteaitoken.com/

## Relevant Experience

I have been in the blockchain space for over 4 years and have acquired a holistic experience of many Web3 niches including NFTs, DeFi and blockchain logistics; having consulted for governments in the Middle East and picked the brains of some of the spaces’ biggest players. - James

I have a combined 3 years experience in AI/ML with backgrounds in econometrics and financial services data analytics. - Tensor Flow Surfer

# Additional Information

We learned about the grants program while looking in the online Filecoin documentation.

**Comment by ErinOCon** [comment]
Hi @ByteAI-DevTeam, yhank you for your time with this proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.

Wishing you the best as you continue building!
