### ISSUE TITLE
Burrito Wallet 

### ISSUE THREAD

**Issue by maengsudi** [filecoin-project/devgrants#1733]
# Open Grant Proposal: `Burrito Wallet`

**Project Name:** Burrito Wallet

**Proposal Category:**   `Integrations` 

**Individual or Entity Name:** Entity called Burrito Wallet 

**Proposer:** `maengsudi`

**Project Repo(s)** we don't have an open source 

**(Optional) Filecoin ecosystem affiliations:** `Filiquid Team.` 

**(Optional) Technical Sponsor:** `Filiquid Team has `

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** No

# Project Summary

Burrito wallet is a newly launched multi-chain wallet made in Korea, mainly targeting South Korean users, who have high ARPU and are active crypto traders. Burrito Wallet positions itself to be a user-friendly and fun for both users and the ecosystem. 

Being a whitelisted wallet on Korea's top central exchange called Bithumb, Burrito Wallet users can easily transfer crypto assets to Burrito Wallet while bieng fully compliant to Korean regulations like Travel Rule. Also the friendly interfaces and customer support service the of app makes the user easily engage in different projects and makes sure they explore more opprotunities in web 3.

Growing upto 150k users, Burrito Wallet has been actively hosting multitude campaigns with 100 different web 3 projects, helping them grow their community and enhance branding in Korea. More than 50% of the team had either been listed on majort exchanges, or grown their ecosystem exponentially especially through branding in Korea, and have genuinely active wallet users from Korea. 

## Impact 

The decentralized finance (DeFi) space suffers from fragmentation across various blockchain networks. Users face cumbersome asset bridging and limitations in accessing diverse financial opportunities. Integrating the innovative Filecoin Network into Burrito Wallet, a user-friendly multi-chain wallet, provides a compelling solution to bridge this gap and unlock immense value for both platforms. 

Burrito Wallet team believes that the impact of the integration will enable our users to 1) Transfer assets seamlessly across multiple blockchains: Users will be able to swap and move tokens between supported chains directly within Burrito Wallet, eliminating the need for third-party exchanges or complex bridge protocols and 2) Access liquidity pools on various chains: Integration with Filecoin liquidity pools will allow Burrito users to participate in DeFi activities from within the wallet, regardless of the chain where their assets reside.  

## Outcomes

The expected ROI is the following: 

- Increased user adoption: Burrito users gain access to a wider range of DeFi opportunities and streamlined cross-chain interactions, attracting new users and retaining existing ones.  
- Enhanced liquidity: Integrating Filecoin Networks liquidity pools expands market reach for both platforms, leading to deeper pools and better exchange rates for users.  
- Growth of the DeFi ecosystem: Seamless cross-chain interactions foster greater interconnectedness and innovation within the DeFi space, benefiting the Filecoin Network leads to further development of both platforms, potentially paving the way for new DeFi applications and protocols.
 

## Adoption, Reach, and Growth Strategies
The main target audience is Korean Web 3 Users. Burrito Wallet consists of 160k users, a half of them are Korean users. 
Also as a subsidiary of Bithumb, more exposure is out there to 8million Bithumb users. 
To onboard new users, we will activate Filecoin community in-app, and have the community outside Filecoin in Upbit, Bithumb to gather up in our wallet, by utilizing different social channels of Burrito Wallet, and support from KOLs through running a major marketing campaign, where we normally gather 5-10k users. 

## Development Roadmap

This is the rough timeline for the development: 

Milestone 1: Finish the development of fEvm on Burrito Wallet (Completed by April 1st, 2024 ) 
Milestone 2: Build Filecoin projects' space to introduce the ecosystem, dApps onboarded on Filecoin network like Filiquid, and promote the newly launched mainnnet and ecosystem to enhance more adoption by Korean users  (To be completed by Q2, 2024) 
Milestone 3: Integrate more defi protocols like staking in Burrito Wallet, increase TVL by Korean community. This way, Filecoin Network would be able to increase adoption, liquidity and grow its ecosystem through Burrito Wallet integration. (To be completed by Q3-4, 2024) 

This integration will enable users to: 
- Transfer assets seamlessly across multiple blockchains: Users will be able to swap and move tokens between supported chains directly within Burrito Wallet, eliminating the need for third-party exchanges or complex bridge protocols. 
- Access liquidity pools on various chains: Integration with FEVM's liquidity pools will allow Burrito users to participate in DeFi activities from within the wallet, regardless of the chain where their assets reside.

</div><br /></b>
</body>
</html>

## Total Budget Requested

| Milestone # | Description | Deliverables | Completion Date | Funding |
|3 milestones, 1 completed | Mainnet and Defi Protocol Integration | TBA | 2024, Q3-4 |$150,000|

This proposal seeks $100,000 to achieve the seamless integration of FEVM's network into Burrito Wallet, considering the following budget: 

- R&D of fEVM (including testing, security audits): $50,000  
- R&D of staking protocol: $50,000
- Marketing and community outreach: $50,000
- Node Operation, maintenance cost to be provided by the filecoin foundation 

## Maintenance and Upgrade Plans

# Team

## Team Members

<Business> 

Max Minchul Shin (CEO)  

Alex Sangho Lee (EVP, CSO)
 
Jinwoo An (CMO) 

<Development>

Daeyoung Kim (VP, CTO)

Hyunchul Kim (Head of R&D)  

Seungho Chung (Senior Engineer Lead)

Linkedin: 
CEO: https://www.linkedin.com/in/maxminchul/](https://www.linkedin.com/in/maxminchul/?originalSubdomain=kr
CSO: https://www.linkedin.com/in/voliamolee/
CMO:  https://www.linkedin.com/in/jinwoo-an-19325924b/ 
Senior Engineer Lead: https://www.linkedin.com/in/seungho-chung-544985b3/

https://www.burritowallet.com/en

## Relevant Experience

Our team is from diverse fields: consulting, gaming, investment, etc.. Above all, the core members are from Bithumb, top CEX in South Korea. In fact, Burrito Wallet was a spin-off project at Bithumb, led by CEO, CTO and CSO. 

## Team code repositories

we don't provide open source code 

# Additional Information

We learned about this grant system through our partners in Filiquid Team.

**Comment by ErinOCon** [comment]
Hi @maengsudi, Thank you for your proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.

Wishing you the best as you continue building!
