### ISSUE TITLE
Next Step Microgrant: FilSnap maintenance and new MetaMask UI feature planning

### ISSUE THREAD

**Issue by eshon** [filecoin-project/devgrants#1735]
### 1. What is your project, and what problem does it solve? (max 100 words)

Maintenance for the open source [MetaMask Filecoin Wallet](https://snaps.metamask.io/snap/npm/filsnap/) ([Github repo](https://github.com/filecoin-project/filsnap)) to address various outstanding maintenance issues, described at https://github.com/filecoin-project/filsnap/issues/ as well as longer-term planning for adding MetaMask's new built-in UI features for Snaps (as opposed to the external-dapp-UI only currently in place).

Any additional remaining hours may also be used to update the [iso-filecoin](https://www.npmjs.com/package/iso-filecoin) library, the cryptographic signing library which is also used by the FilSnap and Ledger.

### 2. Project links
  
Link to Github repo: https://github.com/filecoin-project/filsnap
Link to demo or website: https://snaps.metamask.io/snap/npm/filsnap/
License: Dual-licensed: [MIT](https://github.com/filecoin-project/filsnap/blob/master/LICENSE-MIT), [Apache Software License v2](https://github.com/filecoin-project/filsnap/blob/master/LICENSE-APACHE), by way of the [Permissive License Stack](https://protocol.ai/blog/announcing-the-permissive-license-stack/).

  
### 3. a) How is IPFS, Filecoin, or related technology used in this project?

Filecoin dapps require a web3 wallet for users to interact with the dapp's smart contracts. The MetaMask Filecoin Wallet (Snap) supports Filecoin users with the ability to sign Filecoin transactions (including FEVM) using MetaMask. It can store native Filecoin key material in the MetaMask vault. This wallet is an open source project at https://github.com/filecoin-project/filsnap and has been a project in the Filecoin ecosystem for several years, as MetaMask develops and evolves its 3rd party Snaps platform which launched for users in Fall 2023.

###    b) Is this project building with the current microgrants focus area (FVM)? (Yes or No)

Yes
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |   Fix multiple issues in [filsnap repo](https://github.com/filecoin-project/filsnap/issues/)   |    Provide any interim updates to @eshon as needed    |            est.  15 hours               | 
| 2.     |    Update iso-filecoin       |       Provide any interim updates to @eshon as needed       |                est. 5 hours            | 
| 3.     |    Plan for bulit-in UI updates      |       Provide any interim updates to @eshon as needed       |                est. 5 hours            | 

### 5. If accepted, do you agree to share monthly project updates in this Github issue for 3 months or until the project described here is complete?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Hugo - [hugomrdias@gmail.com](mailto:hugomrdias@gmail.com) - https://github.com/hugomrdias (@hugomrdias) - Lead developer

Hugo has worked as a JS / software engineer at Protocol Labs for several years and also more recently at Fission. He was the lead developer of the FilSnap architecture in 2023 and also of the [iso-filecoin](https://www.npmjs.com/package/iso-filecoin) cryptographic library for Filecoin.

* How did you learn about our microgrant program?
From @eshon

**Comment by ErinOCon** [comment]
Hi @hugomrdias, this microgrant has been approved! We will send an email to confirm next steps and payment details.

**Comment by hugomrdias** [comment]
All deliverables have been shipped.

Summary:
- Released all the packages
    - **filsnap: v1.0.3**
    - **filsnap-adapter: v1.0.2**
    - **filsnap-adapter-react: v1.0.1**
- All dependencies updated to the latest version
- Improved Wallet provider types
- Updated and fixed issues introduced by Metamask UI changes in the end to end testing tooling
- Improved all the UI elements in the extension using new APIs from Metamask
- Add cache to user snap confirmations to avoid unnecessary popups (reported by Glif)
- Improved the connection logic on `filsnap-adapter` to avoid forcing snap installation and extra user popups
- Updated companion dapp to wagmi 2.0
- New CI deploy system for the Companion Dapp
    - https://github.com/filecoin-project/filsnap/actions/runs/9781211572
    - Supports IPFS gateway and DNSLink
        - https://w3s.link/ipns/filsnap.dev
        - https://w3s.link/ipfs/bafybeihpyzrtmqmjwzhzkoqovyuohg4qc6mrfyfmands4go2nkzvty4dhi
    - Moved off Fission system to [web3.storage](http://web3.storage/) and Cloudflare
    - Created a new Github Action to handle [web3.storage](http://web3.storage/) upload and dnslink updates. https://github.com/hugomrdias/action-ipfs-publish
    - Dapp is now deploy to the [filsnap.dev](http://filsnap.dev/) domain
- Most pending issues and PRs were closed, the remaining are out of scope or already scoped for future work
- **iso-filecoin 4.1.0** published with all dependencies updated and fixes for eth<>fil address translation and improved eth address handling
- Research and planning for next phase of Snap UI and API improvements was finished
    - lifecycle-hooks: onInstall, onUpdate. Needs permissions `endowment:lifecycle-hooks`
        - `onInstall` can show a dialog similar to wallet ui
        - `onUpdate` we can should changelog and npm/github links and provenance
    - Homepage overrides the previous snaps info page
        - `OnHomePageHandler` another hook to build the homepage UI and needs permissions `endowment:page-home` can we use this to be the “wallet ui” for account balance and address.
    - Transaction Insights
    - Signatures Insights 
        - `OnSignatureHandler` can return UI with info and severity level that changes the UI accordingly
    - Dynamic UI - Show be useful to do transactions in the extension avoiding companion dapp 
    - Misc Improvements to filsnap
        - Add transaction receipt notifications
        - Improve injected provider types
        - Add support for disconnect
        - Add semver check to the `getSnap` function in the adapter
        - Add multiple account support, connect with mm account or enable changing in the UI
        - Update snap to use the new JSX UI components
        - Add support for `initialConnections` for companion dapp and glif (maybe add other trusted partners ?), improves UX with less popups and confirmations.

ping @eshon

**Comment by eshon** [comment]
Thanks @hugomrdias! cc: @ErinOCon this is ready for final tranche.
