### ISSUE TITLE
Unstoppable NFT

### ISSUE THREAD

**Issue by ash2cash** [filecoin-project/devgrants#1738]
# Open Grant Proposal: `Unstoppable NFT by Envelop DAO`

**Project Name:** Envelop DAO

**Proposal Category:** `FVM`

**Individual or Entity Name:** Envelop DAO 

**Proposer:** `ash2cash`

**Project Repo(s)** https://github.com/dao-envelop 

**(Optional) Filecoin ecosystem affiliations:** `we already use IPFS in our minting dApp to store metadata https://app.envelop.is/mintnew` 

**(Optional) Technical Sponsor:** `Haven't discussed about technical sponsorship`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:**  "Yes"

# Project Summary

In the realm of decentralized storage solutions, one significant challenge involves the absence of a standardized public pinning service. Currently, pinning—the process of ensuring data remains readily available on the network—tends to be localized, limited to individual nodes. This localized approach leads to inefficiencies and limited accessibility, as there isn't a unified system in place that ensures data remains consistently accessible across the decentralized network.

Another issue is the opacity surrounding the mechanisms for token exchange used in these pinning transactions. While some platforms may have a degree of transparency, the specifics of how tokens are valued and exchanged during the pinning process often remain complex and unclear to both users and node operators. This lack of clarity can hinder participation and investment in the ecosystem, as stakeholders may be reluctant to engage with a system that does not provide straightforward, understandable financial interactions.

Addressing these concerns, the proposed project on Filecoin’s technological stack aims to develop a clear and accessible methodology for a semi-public pinning service. This service will allow any user to request pinning services from node operators for a fee, enhancing the accessibility and reliability of data storage across the network. Additionally, the project will establish a transparent and user-friendly mechanism for the sale and exchange of tokens. This will ensure that all parties involved have a clear understanding of the financial transactions, thereby fostering trust and encouraging broader participation in the Filecoin ecosystem. This approach not only enhances the functionality of the decentralized web but also aligns with the principles of transparency and user empowerment at the core of blockchain technologies.

## Impact 

This proposal is designed to tackle critical challenges within the Filecoin and IPFS ecosystems, primarily focusing on improving data availability and the transparency of token transactions. The current lack of a semi-public pinning service means that data storage is often isolated to individual nodes. This fragmentation can lead to data being unavailable when needed unless specifically maintained by node operators. By establishing a structured, paid pinning service, this project aims to ensure that data remains accessible and secure across the network, which is essential for the long-term reliability and usability of the Filecoin system.

The benefits of successfully implementing this project include enhanced data permanence and a more user-friendly experience in handling token transactions, thereby fostering greater trust and participation from both existing stakeholders and potential new users. The clarity in token transactions will also demystify the financial aspects of data storage within the ecosystem, likely leading to increased investments. Conversely, failing to address these issues might risk the ecosystem’s reputation for reliability and security, potentially slowing down adoption and expansion.

If successful, this project could significantly impact various markets and verticals, such as decentralized finance (DeFi), content delivery, and data archiving, where assured data availability and transaction clarity are paramount. In the DeFi space, for instance, enhanced data reliability can lead to more robust financial products that can operate autonomously without concerns about data loss or inaccessibility. The success of this project would be marked by its widespread acceptance across the Filecoin network, leading to measurable improvements in system efficiency, user satisfaction, and an increase in the volume of data stored and retrieved across the ecosystem. This would not only validate Filecoin and IPFS as leading storage providers in the decentralized space but also as pivotal players in the broader blockchain infrastructure.

## Outcomes

To address the outlined challenges within the Filecoin ecosystem, our proposed solution involves developing a robust framework for NFT minting and management, integrating seamlessly with the decentralized environment provided by Filecoin. The final deliverables for this project include:

1. **Enhanced NFT Minting Service**: A user-friendly interface will be developed where users can select specific features for their NFTs, including the "Unstoppable NFT" option. This feature ensures that NFTs remain permanently accessible, leveraging Filecoin's decentralized storage capabilities.

2. **Automated Token Management System**: Upon NFT creation, our system will automatically handle the backend processes necessary for securing the NFT's permanence. This includes purchasing a batch of Filecoin tokens to ensure the NFT is pinned and remains accessible across the network.

3. **Integration with Envelop Protocol**: Each NFT minted will be wrapped using a specialized version of the Envelop protocol tailored for Filecoin. This wrapping process involves adding metadata and securing the necessary collateral in stablecoins or other permitted tokens to maintain the NFT's operational integrity.

4. **Batch Guardian Microservice**: This microservice will monitor and manage the financial transactions associated with each NFT, ensuring that collateral is converted and allocated correctly to support the NFT's permanence on the network.

5. **Cross-Network Asset Exchange**: Should there be a need to interact with other blockchain networks, our solution will facilitate the exchange of assets across different blockchains to support the financial operations associated with maintaining the NFTs.

**Success Metrics**:
Our team will measure the success of this project using several key metrics:
- **User Adoption Rate**: Tracking how many users utilize the new NFT minting service.
- **Operational Efficiency**: Monitoring the speed and reliability of the token management and microservice operations.
- **Cross-chain Functionality**: Evaluating the effectiveness of asset exchanges across different networks.
- **Financial Transactions Accuracy**: Ensuring that all financial transactions related to NFT 
maintenance are executed correctly and efficiently.

Success will be defined by high user engagement with the NFT minting service, efficient operational processes without significant downtime or errors, and positive user feedback regarding the ease of use and reliability of the system.

## Adoption, Reach, and Growth Strategies

The target audience for our project encompasses artists, collectors, and enthusiasts within the NFT (Non-Fungible Token) space, particularly those interested in the enhanced security and permanence offered by Filecoin's decentralized storage. This audience is sizeable and growing, as the demand for more reliable and permanent digital assets continues to increase in the blockchain and digital art markets.

**Engagement Strategies:**

1. **Community Building**: We are actively engaging with this community through social media platforms, blockchain forums, and NFT conferences. By participating in discussions, providing insights into the benefits of decentralized storage, and showcasing success stories, we build credibility and interest.

2. **Partnerships**: Collaborating with established NFT marketplaces and blockchain influencers to showcase our technology and demonstrate its benefits. These partnerships will help us tap into their existing user bases and gain early adopters.

3. **Educational Content**: Producing content that educates potential users on the advantages of using Filecoin for NFTs, including tutorials, webinars, and live Q&A sessions to reduce entry barriers and demonstrate the user-friendly nature of our platform.

**Onboarding Strategies:**

- **For the first 10 users**: Reach out directly through personal networks and blockchain meetups, offering personalized support and incentives such as reduced fees or special recognition within the platform.
  
- **For the first 100 users**: Leverage referral programs where early users can invite others to join with benefits for both the referrer and the referred. Additionally, running targeted ad campaigns on platforms frequented by crypto enthusiasts and digital artists will help widen our reach.

- **Long-term Growth**: Implement a scalable onboarding process, including automated tutorials and integration guides, to support a growing user base without compromising the quality of user experience. Offering seasonal promotions and participating in major blockchain events will continually refresh engagement and attract new users.

These strategies are designed to build a robust initial user base and foster a community that values the security and permanence of digital assets managed on the Filecoin network.

## Development Roadmap

To streamline the development process within the allocated budget of $50,000, the project is divided into three main milestones. Each milestone is designed to progressively build towards a fully functional NFT minting and management platform that leverages Filecoin’s decentralized storage capabilities. Here’s the detailed breakdown:

### Milestone 1: Platform Design and Initial Setup
**Duration:** 1 month (Start Date: May 1, 2024 - End Date: May 31, 2024)
**Team and Roles:**
- **Product Owner**: Overseeing project scope and features (40 hours)
- **CTO**: Architecture planning (40 hours)
- **Backend Developer**: Initial system setup (80 hours)

**Expected Functionality:**
- Completion of platform design documents.
- Setup of basic infrastructure and databases.
- Initial API endpoints for platform core functions.

**Funding Required:**
- Product Owner: $2,400
- CTO: $4,000
- Backend Developer: $5,600
- **Total for Milestone 1: $12,000**

### Milestone 2: Development and Integration
**Duration:** 2 months (Start Date: June 1, 2024 - End Date: July 31, 2024)
**Team and Roles:**
- **Product Owner**: Requirements management and sprint planning (80 hours)
- **CTO**: Supervision of development and integration (80 hours)
- **Blockchain Developer**: Smart contracts for NFT functionality (160 hours)
- **Backend Developer**: Integration with Filecoin and user interface development (160 hours)
- **QA**: Initial testing phases (80 hours)

**Expected Functionality:**
- Development of smart contracts for NFT minting and management.
- Integration with the Filecoin network for data pinning.
- Functional user interface for NFT creation and management.

**Funding Required:**
- Product Owner: $4,800
- CTO: $8,000
- Blockchain Developer: $12,800
- Backend Developer: $11,200
- QA: $4,000
- **Total for Milestone 2: $40,800**

### Milestone 3: Testing, Refinement, and Launch
**Duration:** 1 month (Start Date: August 1, 2024 - End Date: August 31, 2024)
**Team and Roles:**
- **Product Owner**: Final product review and adjustments (20 hours)
- **CTO**: Deployment oversight (20 hours)
- **Blockchain Developer**: Final adjustments to smart contracts (40 hours)
- **Backend Developer**: Final system refinements and setup (40 hours)
- **QA**: Extensive testing and bug fixing (40 hours)

**Expected Functionality:**
- Fully functional platform ready for public use.
- Robust testing and refinement to ensure reliability and performance.
- Launch of the platform to the target audience.

**Funding Required:**
- Product Owner: $1,200
- CTO: $1,000
- Blockchain Developer: $3,200
- Backend Developer: $2,800
- QA: $2,000
- **Total for Milestone 3: $10,200**

**Total Project Funding: $63,000**

The revised budget allocation increases resource hours and adjusts compensation to better reflect the scope and demands of each development phase, ensuring the project can be delivered effectively within the capabilities of the team and technological requirements. Despite Total Project Funding exceeds grant amount of $50 000 - our team will fit into as we are passionate about the product to be delivered. 

## Total Budget Requested

| Milestone # | Description                          | Deliverables                                         | Completion Date | Funding   |
|-------------|--------------------------------------|------------------------------------------------------|-----------------|-----------|
| 1           | Platform Design and Initial Setup    | Design documents, infrastructure setup, initial API  | May 31, 2024    | $12,000   |
| 2           | Development and Integration          | Smart contracts, UI development, Filecoin integration| July 31, 2024   | $40,800   |
| 3           | Testing, Refinement, and Launch      | Fully functional platform, user testing, final adjustments| August 31, 2024| $10,200   |
| **Total**   |                                      |                                                      |                 | **$63,000** |

### Maintenance and Upgrade Plans

**Long-term Maintenance:**
Our team is committed to ensuring the longevity and relevance of this project. Post-launch, we plan to establish a dedicated maintenance team responsible for regular updates and bug fixes. This team will monitor system performance, user feedback, and technological advancements to implement necessary updates. Regular maintenance intervals will be scheduled quarterly to ensure the platform remains efficient and secure.

**Future Upgrades:**
To keep our platform at the forefront of the Filecoin ecosystem, we will continuously explore new features and improvements. This includes expanding the platform’s capabilities to integrate additional blockchain functionalities and enhancing user experience based on community feedback. Future upgrades will be planned annually, with smaller incremental updates rolled out as needed based on the emerging needs of our users and changes in the blockchain landscape.

**Community Involvement:**
Engaging with the community will be critical for the iterative improvement of the platform. We plan to utilize community feedback tools and hold regular open forums where users can suggest features, report issues, and provide general feedback. This community-driven approach will help prioritize upgrades and ensure the platform evolves in alignment with user needs.

**Sustainability Measures:**
To fund ongoing maintenance and future upgrades, a portion of the transaction fees generated by the platform will be reinvested into the project. This self-sustaining financial model aims to ensure the project remains viable and progressive long-term without additional external funding.

These plans are designed to ensure that the project not only stays functional but also improves and adapts over time, maintaining high standards of reliability and user satisfaction in the dynamic environment of blockchain technology.

# Team

## Team code repositories

# Team Overview

## Team Members

- **Alexander Shedogubov**, CEO
- **Maksim Sesykh**, CTO (Smart Contracts)
- **Menaskop**, Architect/Analyst
- **Dmitriy Golubev**, Backend Developer
- **Konstantin Shuplenkov**, Frontend Developer
- **Alexander Agadjanov**, QA

## Team Member LinkedIn Profiles

- [Alexander Shedogubov LinkedIn](https://www.linkedin.com/in/aleksandr-shedogubov/)
- [Maksim Sesykh LinkedIn](https://www.linkedin.com/in/max-sizz-2688ba7a/)
- [Menaskop LinkedIn](https://www.linkedin.com/in/menaskop)
- [Dmitriy Golubev LinkedIn](https://www.linkedin.com/in/shotonoff/)
- [Konstantin Shuplenkov LinkedIn](https://www.linkedin.com/in/konstantin-shuplenkov)
- [Alexander Agadjanov LinkedIn](https://www.linkedin.com/in/alex-agadzhanov-05803599/)

## Team Website

Please visit our team's official website for more detailed information and updates: [Envelop Team Website](https://envelop.is)

## Relevant Experience

Our team brings a deep and varied set of expertise to the project, crucial for its success. Alexander Shedogubov, our CEO, has over 15 years in IT and operations, particularly in blockchain since 2017, and has been pivotal in steering product development and operations at DAO Envelop. Maksim Sesykh, our CTO, offers a rich background in blockchain and FinTech development, contributing significantly to our technical strategy.

Menaskop, the Architect and Analyst, provides crucial insights into system architecture and tokenomics, drawing from a robust history in Web3.0 analytics and IT-legal frameworks. Dmitriy Golubev and Konstantin Shuplenkov, specializing in backend and frontend development respectively, bring critical development skills from their experiences in significant blockchain and tech projects. Finally, Alexander Agadjanov ensures our quality assurance is stringent and effective, backed by his experience in blockchain projects.

## Team Code Repositories

For a look at our team's past projects and coding contributions, visit our repositories:
- [Envelop DAO GitHub](https://github.com/EnvelopDAO)

This composition of diverse skills and backgrounds uniquely positions our team to handle the complex demands of developing and deploying blockchain solutions effectively. With a proven track record in similar domains, our team is well-equipped to bring this innovative project to fruition.

# Additional Information

Learnt about the program from https://fil.org/grants/#dev-grants 

The beat email address for discussing the grant agreement and general next steps is alex@envelop.is 

Envelop DAO thrives on a deep passion for Web3 innovation and has demonstrated robust financial acumen, skillfully navigating through the challenges of the bear market since our initial fundraising in 2021. This expertise in financial management has not only sustained us but also positioned us as leaders in the Web3 space, ready to leverage emerging opportunities and drive future growth.

**Comment by ErinOCon** [comment]
HI @ash2cash, thank you for your proposal and for your interest in our grants program! It looks like we are currently blocked from viewing your website. Is this something that can be addressed?

Also, I haven't seen activity from this handle on the project repo. Is a regular contributor to the repo currently a part of your team? If so, can they briefly describe their involvement in this thread?

Thanks again!

**Comment by maxsiz** [comment]
Hi @ErinOCon !  Thank you for  your attention. First of all sorry for some inconvenient due typo. I am one of genesis contributor in Envelop project.  You can find my commits here [dao-envelop]( https://github.com/dao-envelop). Please notice that the link in section above has misprints. Actually we use github repos as showcases of our smart contracts. For everyday working flow we use public **gitlab** and you can find huge quantity of code over there.  And more contributors as well. Here it is https://gitlab.com/envelop
So i am involved a lot :-)  in  orchestrate the dao tech layer.

**About blocking from viewing our website.**  
Could you please provide links that you tried  to open?
For the legal purpose one can't access some of our sites from US.

**Comment by ash2cash** [comment]
Hello @ErinOCon !

Do you have any additional questions or clarifications needed about Envelop Grant application?

**Comment by ErinOCon** [comment]
Hi @ash2cash, thank you for your time with the additional information and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.

Wishing you the best as you continue building!
