### ISSUE TITLE
"DNA Network applies for an open grant"

### ISSUE THREAD

**Issue by xunyuyou** [filecoin-project/devgrants#1741]
# Open Grant Proposal: `Project Title`

**Project Name:** **DNA Network**

**Proposal Category:** **Developer and data tooling**

**Individual or Entity Name:** **DNA Network Labs**

**Proposer:** **xunyuyou**

**Project Repo(s):** **Coming soon**

**(Optional) Filecoin ecosystem affiliations:** **Titan Network provides us with basic storage services.**

**(Optional) Technical Sponsor:** **Jenks Guo**

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Please respond with "Yes" or "No".  **Yes**

# Project Summary
 &nbsp;&nbsp;&nbsp;&nbsp; **In the past few years, blockchain has been expecting to redefine high-value product experience through its connection with the real world, help businesses and individuals build up their reputation, brand stickiness, and loyalty, while maintaining their core values. However, many projects have failed in attempts successively, mainly because:**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**1. Blockchain acquires information by relying upon the oracle, however, centralized or multi-centralized oracle is susceptible to attacks and malicious operations. If the accuracy of the original data before being deployed on the blockchain cannot be guaranteed, blockchain technology will lose its value in practical application.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Previously, there was a lack of effective technical solutions to ensure that the physical objects corresponding to the data on the blockchain were not replaced or forged.**
 &nbsp;&nbsp; &nbsp;&nbsp; **As a middleware that serves as a bridge between the next-generation blockchain and the real world, DNA can help the real world deploy tangible assets (luxury goods, ceramics, calligraphy and paintings, antiques, handicrafts, artworks, etc.). To address the above problems, we’ve launched two revolutionary technological solutions. Firstly, we capture a micro fingerprint image of the physical surface magnified by N (N≥180) times using an "Intelligent Authentication Device" and upload it to IPFS for storage. Then, we summarize the information through a public blockchain account verified through real name authentication and mint it into an NFT. During verification, we take microscopic images for the same location of the physical object in the same magnification, and compare them with NFT fingerprint images using artificial intelligence (AI) algorithms to solve the accuracy issues of the original data arising from the fact that the physical object corresponding to the data on the blockchain will not be forged or replaced and the blockchain oracle is susceptible to attacks or subjective wrongdoing, thereby achieving the goal of bringing trillions of real-world assets into the blockchain world.**

DNA1.0 Video Introduction
https://www.youtube.com/watch?v=1u-sA9_2N5U

## Impact 
 &nbsp;&nbsp;&nbsp;&nbsp; **DNA will create a large number of NFTs, massive needs for storage of videos, images, and real-world information. We are collaborating with China Mobile to create the “Ceramic Traceability” project, providing the ceramic industry with a complete set of fundamental services related to data generation, update, storage, verification, and transmission (with data access and storage services provided by Titan), realizing the binding of artworks, enterprise mass-produced porcelain, and digital culture (digital collectibles NFT). In addition, we will also carry out the acquisition, authentication traceability and physical supervision of physical information data for over 10 million artworks or antiques from 72 countries and regions worldwide at the 7th China International Import Expo. It is expected to generate the storage and access needs for at least 100 million pieces of high-quality commercial data, which will greatly increase the use of IPFS and the entire filecoin ecosystem, and therefore create more revenue for the entire ecosystem.**
  &nbsp;&nbsp;&nbsp;&nbsp;**DNA aims to become a bridge to Web3 from the real world. It involves many risks, and we or any project in Web3 may have a more than 90% chance of achieving the level of success we pursue, but we will keep our scheduled pace unchanged until our product (including price and usability) is recognized by the market. We will keep iterating regularly until we reach a turning point. Doing this correctly will create a huge benefit for the filecoin ecosystem and the entire Web3 ecosystem.**

## Outcomes

&nbsp;&nbsp;&nbsp;&nbsp;**A Dapp that integrates NFT minting function, physical verification function, and all DID functions**

&nbsp;&nbsp;&nbsp;&nbsp;**The final product will not only create an entry point for the real world to enter Web3, but also further integrate Titan and Filecoin. We will store all NFTs, videos, and images on IPFS for mapping physical assets in the real world in Web3.**

## Adoption, Reach, and Growth Strategies

&nbsp;&nbsp;&nbsp;&nbsp;**DNA Network has been successfully applied in the supervision of bonded exhibition and transaction of artworks at the 5th China International Import Expo and the 6th China International Import Expo, with a success rate of 100%. This year, more than 10 million exhibits of enterprises or individuals from 72 countries and regions will be exhibited at the 7th China International Import Expo. Physical fingerprint data will be collected by enterprises or individuals rather than customs before being declared to customs, which will be only responsible for verification. It means that a large number of high-quality enterprises or individuals will become users of DNA, and storage needs involving at least 100 million pieces of high-quality commercial data will be generated.**
## Development Roadmap

Milestone | Date | Deliverables | developer | Cost
-- | -- | -- | -- | --
1 | June 7, 2024 | Titan The data storage and access of the Intelligent   Authentication Device 1.0 are connected to Titan. | Hardware Engineer*1   Front-endDeveloper engineers *1   Backend Developer engineers *2   Blockchain development engineers*1 | 15000
2 | June 30, 2024 | DNA Passport （DID）launched | Blockchain development engineers*3   front end development engineers *2   backend development engineers *3 | 21000
3 | August 13, 2024 | Launch C-end user Dapp, with functions including   NFT minting, NFT verification, and acquiring fingerprint data and location   data from ordinary users and storing them in Titan Network | front end development engineers *2   backend development engineers *3   Blockchain development engineers*3   Computer vision specialists*1 | 14000

## Total Budget Requested
**Request a total budget of USD 50,000**
| Milestone # | Description | Deliverables | Completion Date | Funding |
|===|===|===|===|===|

<div align=center>

Milestone | Date | Deliverables | Cost
-- | -- | -- | --
1 | June   7, 2024 | Titan The data storage   and access of the Intelligent Authentication Device 1.0 are connected to   Titan. | 15000
2 | June   30, 2024 | DNA Passport （DID）launched | 21000
3 | August   13, 2024 | Launch C-end user Dapp, with functions including   NFT minting, NFT verification, and acquiring fingerprint data and location   data from ordinary users and storing them in Titan Network | 14000
</div>

## Maintenance and Upgrade Plans

&nbsp;&nbsp;&nbsp;&nbsp;**With this grant, we will have enough fund to support the project in the next 12 months. I am still working as a full-time employee and will invest my funds into this project.**
&nbsp;&nbsp;&nbsp;&nbsp;**DNA target - at least 100,000 companies or individuals are using DNA technology, and 1 million physical assets are deployed on the blockchain through DNA technology every month.**

# Team
## Team Members

**XienCheng**

**WenLiu**

**BinHuang**

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/shawnchengcn/

https://www.linkedin.com/in/lw27303/

https://www.linkedin.com/in/28a356301/

## Team Website

**https://www.rdna.cc/index-en.html**

## Relevant Experience

**XienCheng**
PhD, Associate Professor, Master Supervisor, engaged in the research and application of machine vision, big data and blockchain technology. He is committed to the applied research and practice of new generation of information technology in industry. In the past five years, Dr. Cheng has undertaken and participated in more than ten research projects, published more than ten SCI/EI research papers, and authorized with six national invention patents and more than ten utility model patents.
**WenLiu**
Internet industry experts, worked for Huawei since 2010, responsible for Huawei's global cellphone configurator project, making outstanding contributions to Huawei's cellphone business. In 2016, he focused on the blockchain industry, as the founder of Star CloudShang blockchain company, and developed public chains, digital wallets, smart contracts, blockchain exchanges and blockchain basic tools, and has extensive experience and leadership in the blockchain industry.
**BinHuang**
With 10 years of experience in hardware R&D and IT system architecture and management, he has been a team leader for technical system planning in several well-known enterprises. He has been committed to the research and development of artificial intelligence and blockchain technology, and has developed blockchain framework and commercial application projects for many well-known large enterprises and startups. He has rich experiences in computer system design, product developmen.
## Team code repositories

https://github.com/camchain
https://github.com/sceplus100/darkchain
# Additional Information

**Sourced from Jenks Guo Introduction**

[rdna996@gmail.com](mailto:rdna996@gmail.com)

&nbsp;&nbsp;&nbsp;&nbsp;**We started our technology development in 2017, and have been validated in the 5th China International Import Expo, the 6th China International Import Expo, China Jingdezhen International Ceramic Expo and other scenarios, with a success rate of 100%! At the same time, we have also won many honors, including the First Prize of Innovation China, Maker China Winning Prize, Excellent Talent Team Award of World Conference on VR Industry, and so on.**

**Comment by ErinOCon** [comment]
Hi @xunyuyou, Thank you for your time with this proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.

Wishing you the best as you continue building!
