### ISSUE TITLE
Layer-1 blockchain as the foundation for a public “Property Identity Data System

### ISSUE THREAD

**Issue by Chiadok** [filecoin-project/devgrants#1746]
# Open Grant Proposal: `Layer-1 blockchain as the foundation for a public “Property Identity Data System`

**Dataholm Filecoin:**

**Proposal Category:** Choose one of `Integrations`. 

**Individual or Entity Name: Dataholm** Is the proposal on behalf of an individual, or an entity/organization? Organization. Please note that the agreement and any payments must be completed by the same entity, either individual or organization.

**Proposer: ChiadoK ** `replace with your GitHub username`

**Project Repo(s)** Please list Github repos used for this project work. 

**(Optional) Filecoin ecosystem affiliations:** `Please disclose any existing work relationships with organizations in the Protocol Labs Network, including Protocol Labs, Filecoin Foundation, Filecoin Foundation for the Decentralized Web, and any others.` 

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Please respond with "Yes" or "No". Yes

# Project Summary

Legacy real estate ecosystem based on the antiquated monopolistic MLS. No single source of truth for Listing, Identity, Property, Historical Data, and Titling.

Dataholm, is the patent pending "all things real estate" Layer-1 public/private single source of truth data blockchain where a homeowner like mineral rights, owns their data by claiming their property on the blockchain to potentially earn in perpetuity future chain of title transactions and data on their home. 

The PIDS is at its core a just lookup table of links to documents which can be stored on partners such as Filecoin and this grant will help integrate Dataholm with the Filecoin blockchain. 

## Impact 

Dataholm is looking for a preferred storage partner that is secure for homeowners to store public and private data. One pain point is the cost of storage and data pulls, where a homeowner can earn on their data. Looking at building a scalable program with a fixed price where there's a one time fee for Dataholm to store data on Filecoin with a set date and number of pulls within that package. 

Value adds to the Filecoin chain with users looking for a bundled package or meter of sorts where they can pay a fee and access data at a fixed price. Benefits of getting this right is tiered pricing or bundled package which is scalable and attractive to companies like Dataholm which choose Filecoin as the storage partner. Not getting it right, makes it difficult for forecasting expenses and storage capacity for companies planning for future storage needs. 

Success is Filecoin becoming the standard storage of public data and documents for Dataholm, counties, title offices, and financial institutions. 

## Outcomes

The Open Source github repository for accessing public data with a packaged program defining a set date, fixed cost and predetermined number of data pulls. Looking for long term storage with forecasted cost for property data such as Filecoin. 

Measuring success with the number of users and what type of files can be stored or updated by the users. 

## Adoption, Reach, and Growth Strategies

A user earns 10 reward tokens for signing up and claiming their property on the blockchain. First ten users through family and friends network. Next 100 through social media starting with X and Linkedin. 

## Development Roadmap

Purpose - The purpose of interacting with Filecoin is for long term document storage.  Many will be infrequently accessed, but all may have times where files have someone’s attention.  If Dataholm has to manage and maintain all files on the platform, we may as well use a centralized platform.  Wider adoption of the Dataholm titling system will contain participants that we have no direct connection with, but are stakeholders in the real estate identified in Dataholm. A common tool or interface for interacting with the system would be advantageous.

## Total Budget Requested: $50,000

| Milestone # | Description | Deliverables | Completion Date | Funding |
|===|===|===|===|===|

Open Source Program with fixed payment terms, duration and data pulls

Over time, the dataholm token will need to be listed on exchanges to have a valid price discovery for the token conversions with services such as Filecoin.  This is in connection with Milestones 4  and 5  , but is a business task that is not covered by this grant application.

# Team

## Team Members

 Matt Whittington
 Chad Amon

 https://www.linkedin.com/in/matt-whittington-320a461a/
 https://www.linkedin.com/in/chadamon/

Chad, CEO, has 10 years of experience building and designing software as a graduate of the University of Texas McCombs Graduate School of Business with a Master of Science in Technology Commercialization. At IBM, he led teams in building and redesigning innovative data analytic products, such as master data management, data virtualization, and AIops, on the Watson AI platform. He also worked as a contracted Design Director for the Disney+ analytics platform. 

Matt Whittington, CTO, attended Texas State University and has been actively involved in Layer-1 blockchain design and implementation. He has also worked on innovative projects related to IoT, blockchain, digital identity, recycling incentives, and real estate tokenization. His expertise includes system design, implementation of smart contract Oracle data into public blockchains, and designing security systems for IoT devices and health records systems. In the early 2000s Matthew created the first MISMO implementation holding property and personal information for Myriad Development that was eventually used by 8 out of the top 10 property insurance companies in the United States. Also while at Myriad Development, Matthew created and deployed the initial residency verification system used by FEMA for the New Orleans Katrina support payments.

## Team code repositories

# Additional Information
 Matt
 chad@dataholm.com, matt@dataholm.com
 We have Beta data blockchain and looking to add a storage solution. Thank you for your consideration

**Comment by ErinOCon** [comment]
Hi @Chiadok, thank you for your time with this proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.

Wishing you the best as you continue building!

**Comment by Chiadok** [comment]
Thank you for the follow up. Best, Chad
