### ISSUE TITLE
Filecoin Developer Guide and Interactive Coding Tutorials

### ISSUE THREAD

**Issue by ZhangPeibin** [filecoin-project/devgrants#1749]
# Grant Proposal: `Filecoin Interactive platform`

**Project Name:** Filecoin Developer Guide and Interactive Coding Tutorials

**Individual or Entity Name:** peibin.

**Proposer:** `ZhangPeibin`

**Filecoin ecosystem affiliations:** `The platform aims to build a technical entry platform for the Filecoin ecosystem, helping users to understand and acquire Filecoin ecosystem technology step by step. In some ways, the platform will be a bridge for new users to reach Filecoin.` 

### 1. What is your project and what existing gap will your project address? 
This project aims to create a comprehensive set of developer guides and interactive coding tutorials to help developers integrate and use Filecoin. The content will include a basic overview of Filecoin, environment setup, API usage, troubleshooting, and more. All documentation will be open-sourced to ensure it is freely available and modifiable by the community.

### 2. How does your project align with our program focus areas? 
Filecoin's technology is being updated every day, which is very difficult for developers. We are always following up with interactive learning documents on related technologies to help developers quickly understand and master the relevant technical knowledge of Filecoin. Our platform and Filecoin are progressing and building together.

### 3. What are the expected outcomes of the project? What steps will you take to meet this objective? 

1. Create a complete developer guide covering the core functionalities and use cases of Filecoin.
2. Develop three detailed interactive tutorials demonstrating how to use Filecoin APIs, SDKs, and tools for data storage, retrieval, and storage deal management.
3. Provide interactive coding examples using online platforms (e.g., Repl.it, CodeSandbox) to help developers learn through hands-on practice.

| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |         Developer Guide Initial Draft：Create the basics of Filecoin, including an overview and key concepts & Write an environment setup guide covering installation and configuration steps for different operating systems.                |        Define the project scope and specific goals & Analyze existing documentation and resources to identify improvement areas & Create a project timeline and task assignments.                                                    |              A month              | 
| 2.     |      Expand the developer guide to cover API usage, troubleshooting, and advanced techniques & Add code examples and diagrams to enhance readability and usability &                    |                   We will distinguish related technologies according to the direction, such as the use of SDK, contract development, etc., and then gradually show the use of specific related technologies from easy to difficult. The core is to initially build interactive examples to let you                                         |          half a month                    | 
| 3.     |      Create interactive coding examples using online platforms (e.g., Repl.it, CodeSandbox) where developers can run and modify code directly. & Provide detailed code examples and operational instructions for each interactive tutorial, ensuring developers can understand and master Filecoin usage through practice.                   |                 We will be looking for 1 to 2 technical people with teaching experience to code the relevant interactive learning tutorials. We plan to simulate https://cryptozombies.io/ to build relevant interactive learning                                           |               A month               | 
| 4.     |        Complete and stable interactive learning platform              |                        Recruit three to five developers to test the documentation and interactive tutorials, collect feedback, and make improvements &  Refine and revise the documentation and tutorials based on the feedback.                                       |         half a month                        | -->

### 4. How will you determine if your documentation is successfully supporting your intended audience? 
1. Audience Research: Understand the needs, preferences, and challenges of your target audience. Gather information through surveys, questionnaires, user feedback, etc
2.  User Testing and Feedback: Provide drafts or partial content of the documentation to your target audience for testing, and collect their feedback and opinions. Observe their experience and reactions while using the documentation.
3. Quantitative Metrics: Set quantitative metrics to evaluate the success of the documentation, such as user visits, page views, downloads, etc. These metrics can help determine the documentation's impact and popularity.
4. User Engagement: Observe the level of engagement of your target audience in documentation-related communities or forums, including asking questions, providing answers, sharing experiences, etc. High engagement typically indicates that the documentation is appealing to the target audience.
5. Continuous Improvement and Optimization: Based on user feedback and quantitative data, continuously optimize and improve the content and structure of the documentation to ensure it aligns with the needs of the target audience.

### 5. Will this work be published under the dual MIT and APACHE2 licenses?
MIT 

### 6. Does your proposal comply with our Community Code of Conduct? 
yes
### Additional questions: 
For each team member(s), please list name, email, Github account, and role in the project.
peibin, wiki4zhang@gmail.com , ZhangPeibin,  leader. 

How did you learn about this program?

**Comment by ErinOCon** [comment]
Hi @ZhangPeibin, thank you for your proposal. Do you know where you would build this in the ecosystem? Will you be building a platform from scratch or contributing to resources already available? Also, do you have a portfolio available for our team to review?

**Comment by ZhangPeibin** [comment]
> Hi @ZhangPeibin, thank you for your proposal. Do you know where you would build this in the ecosystem? Will you be building a platform from scratch or contributing to resources already available? Also, do you have a portfolio available for our team to review?

Hi! We are pleased to receive your reply! We will build this project based on FVM because our main focus is on an interactive learning platform. The metadata of the learning process and results will be constructed on FVM smart contracts, such as users' learning levels (similar to middle school, high school, university). All actions will be recorded on FVM. For project documents and data, we will use partners from the Filecoin ecosystem for hot storage. Later, for large data like videos, we will use a combination of cold and hot storage methods!
We will reconstruct the learning process by building a new approach to guide users through their learning journey. Unlike traditional methods, we will use ChatGPT-4 as a teacher to create learning resources and more.
Additionally, we will use NFTs and points to attract users, encouraging them to engage in learning from basic to advanced levels. We hope that ultimately, users will gain knowledge about Filecoin and also earn some rewards.

I previously received Wave 9 funding, as can be seen in this link: [Wave 9 Grant](https://github.com/filecoin-project/devgrants/pull/283). Additionally, I have been actively involved in the blockchain space and am currently developing an AI+Learning product to guide users in familiarizing themselves with and using Filecoin.

**Comment by ErinOCon** [comment]
Hi @ZhangPeibin, thank you for your reply. To clarify, are you building your own learning platform or will the guide and tutorials be featured in a space that is already active?

Also, thank you for pointing to your previous grant work. Can you share a link that will direct us to content or copy you have previously worked on?

**Comment by ZhangPeibin** [comment]
> Hi @ZhangPeibin, thank you for your reply. To clarify, are you building your own learning platform or will the guide and tutorials be featured in a space that is already active?
> 
> Also, thank you for pointing to your previous grant work. Can you share a link that will direct us to content or copy you have previously worked on?

Hi @ErinOCon , We are going to build a unique learning platform where we will introduce AI to assist users in learning, just like a teacher. Each user can have their own unique AI teacher, allowing them to learn relevant knowledge according to their interests and paths. To attract users, we will launch learning modes such as 'learn to earn', 'answer to earn', and 'help to earn'. 
This platform will be built by me but will be refined through the contributions of the vast community of Filecoin learners.

here is our project link : https://istorage-web-zhangpeibin.vercel.app/.
but the project has stopped maintenance and https://app.istorage.one/ is also inaccessible, but you can see what we are going to do on the homepage.

Artificial intelligence + learning is disruptive!

Hope to get your reply quickly!

**Comment by ZhangPeibin** [comment]
@ErinOCon Thank you, looking forward to your reply！

**Comment by ZhangPeibin** [comment]
@ErinOCon any news?

**Comment by ErinOCon** [comment]
HI @ZhangPeibin, thank you for your patience with our review process! Unfortunately, we have decided to not proceed with a grant at this time. Thank you for your time with this proposal and for your interest in our grants program.
