### ISSUE TITLE
Tutorial Creation - Tutorial Creation - FVM interoperability Developer Guides

### ISSUE THREAD

**Issue by AllanMangeni** [filecoin-project/devgrants#1752]
# Grant Proposal: `Tutorial Creation - FVM interoperability Developer Guides`

**Tutorial Creation - FVM interoperability Developer Guides**

**Individual or Entity Name:** Allan Mang'eni

**Proposer:** `AllanMangeni`

**Filecoin ecosystem affiliations:** `Filecoin Orbit Kenya` 

**(Optional) Technical Sponsor:** 

### 1. What is your project and what existing gap will your project address? 
Currently, the Filecoin documentation lacks detailed guides on how to integrate FVM with various development frameworks and AI models. We plan to create developer guides on how they could integrate FVM to various development frameworks ranging from small-scale to enterprise-grade applications. 

### 2. How does your project align with our program focus areas? 
Our project will  serve as tutorials for developers looking to integrate FVM to various frameworks like NodeJS, Angular, React and AI. We plan to do in-depth guides that can serve as boilerplates for developers looking to deploy smart contracts via FVM. 

### 3. What are the expected outcomes of the project? What steps will you take to meet this objective? 

- We will employ an agile approach for each tutorial listed on the deliverables as this will help get appropriate feedback and also makes it easy to share updates with the Grants team. 
- We expect to have an easier process to onboard developers to the filecoin ecosystem by showcasing realworld use cases and also providing guides on interoperability with other development frameworks. 

| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |   Integrating FVM with React for dApp Development                 |     This guide will include step-by-step instructions, code snippets, reallife use-case and troubleshooting tips for integrating FVM smart contracts with React Front-end                                                      |      3 Weeks                      | 
| 2.     |     Building a Full-Stack dApp with FVM and Node.js       |   This guide will entail a tutorial on writing functions to interact with FVM, installing and integrating necessary dependencies and troubleshooting tips                                                   |         3 weeks                 | 
| 3.     |   Using FVM with Angular for Enterprise-Grade dApps    l                |      We will showcase how Angular and FVM can be used to create Large-scale applications by using Filecoin for decentralized storage, and deploying smart contracts via FVM                                                |        3 weeks                    | 3 weeks
| 4.     |  Integrating FVM with AI Models for Decentralized AI Applications                 |    Our guide will entail a step-by-step tutorial on a use case of smart contracts leveraging AI models for tasks like data analysis and data-based decision making.                                                        |      3 weeks                      | 

### 4. How will you determine if your documentation is successfully supporting your intended audience? 
We will get feedback by conducting surveys from our users once the resources are live. We will also have more user engagement via community channel, workshops supported by Filecoin Orbit and hackathons to further understand ways we could refine the learning materials to make it easier to onboard developers looking to build on FVM.

Analysing search metrics and content scores via Gitbook would help make any necessary iterations around the deliverables and also for future Developer Guides.

### Additional questions: 
Team member information

Allan Mang'eni
Role: Lead
Email: allanwanyonyi@protonmail.com
Github: AllanMangeni

How did you learn about this program? Through Filecoin Orbit

**Comment by ErinOCon** [comment]
Hi @AllanMangeni, thank you for your proposal! We have sent you a message in Slack to get a little more background. You are, of course, welcome to reply on this thread if preferred. 

Let us know of any questions!

**Comment by ErinOCon** [comment]
Hi @AllanMangeni, thank you for the additional links and context. This proposal has advanced to our final round of reviews scheduled to be completed by the end of August (if not sooner). 

If we have any final questions during this review round, I will be in touch. Thank you again for your patience and for your interest in Filecoin documentation!

**Comment by ErinOCon** [comment]
Hi @AllanMangeni, thank you for your patience with our review process. Unfortunately, we will not be moving forward with a grant for this proposal at this time. If you have any questions for our team, please contact grants@fil.org.

Wishing you the best with your current and future projects!
