### ISSUE TITLE
Hedgey Finance Developer Grant

### ISSUE THREAD

**Issue by icemanparachute** [filecoin-project/devgrants#1753]
# Open Grant Proposal: `Hedgey Finance Developer Grant`

**Hedgey Finance:**

**Proposal Category:**`FVM`

**Individual or Entity Name:** Hedgey Finance Inc.

**Proposer:** `@icemanparachute`

**Project Repo(s)** [Vesting & Lockups](https://github.com/hedgey-finance/Locked_VestingTokenPlans) 

**(Optional) Filecoin ecosystem affiliations:** `Hedgey Finance Inc. is a current portfolio company of Protocol Labs, being an alumni of the Tachyon & Filecoin Accelerator program from summer of 2021, with follow on capital from Protocol Labs. ` 

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** "No"

# Project Summary

Hedgey provides a suite of onchain tools for responsible and efficient distribution of tokens from projects to their beneficiaries; team & contributors, investors, and community. The suite of onchain tools that Hedgey builds, maintains and offers are built as Public Goods, with no costs to use them, however Hedgey does charge some projects for custom development of airdrop / token claim pages, and white glove service & reporting as part of the freemium business model. 

Hedgey has deployed its contracts to multiple EVMs, and currently serves as the home for token vesting & lockups to over 500 projects, collectively with ~ $600mm of TVL based on current market prices. 

### Public Goods Tools

1. **Employee Vesting** 
    
    Tool for projects to grant and manage RTUs (Restricted Token Units) for employees & contributors. The tool automates the vesting schedule, and allows an admin to revoke the vesting plan at anytime prior to fully vested date. Project Admins have a dashboard to visualize the RTUs and have reporting capabilities, plus ability to revoke & manage the plans. Revoking the plan will return only the unvested tokens, while vested remain redeemable by the beneficiary. Beneficiaries have a dashboard to visualize their vesting schedules as well as redeem tokens as they vest. 
    
2. **Investor Lockups**
    
    Tool for projects do distribute tokens to investors and automate the unlock schedules, ensuring the investors are always in compliance of the agreed unlock schedule. After distribution projects have a dashboard to visualize the distributions, but there are no continued administration requirements. Investors have a dashboard to track their unlock progress, and redeem tokens as they unlock. 
    
3. **Treasury Lockups**
    
    Tool for projects to lock up their treasury tokens over time, to the extent they have emission schedules they want to adhere to based on tokenomics. This tool essentially self locks tokens, but comes equipped with a public dashboard that the team can share with the community for additional transparency of the unlock schedule.
    
4. **Grants Distributions**
    
    Tool for projects & DAOs to distribute grants to grantees. The tool can be used for retroactive grants that have already been earned, but may have an unlock schedule, or used for incentive and forward looking (optimistic) grants, which can be revoked and pulled back at any time prior to completion of milestones, should the grantees not complete their milestones. This tool comes with a dashboard for grant administrators to visualize, track, and manage the grants distributed, and revoke any necessary. Additionally it comes with a dashboard for the grantees to redeem their tokens as they unlock over the agreed unlock or milestone (time based) schedules. This tool also comes with a public dashboard that can be shared broadly with the community for public transparency and community alignment. 
    
5. **Community Airdrop / Claims**
    
    Tool for projects to distribute their initial token airdrop to their community. This tool can be customized for additional costs beyond the strict free to use public goods version (API and contracts are open to use, but hosing of the custom claim page UI involves additional development costs borne by the project). This tool efficiently distributes tokens to up to 5mm users at a time, and can be used to distribute both unlocked as well as locked or vesting tokens. This tool is an elegant way for projects to make a great claim experience for their initial airdrop! The tool comes with a dashboard for the project to manage their claims in real time, have stats to understand active claims, and ability to cancel them at any time. It can come with custom claim pages built by Hedgey, or teams can simply leverage the open API to create their own claim experience.

## Impact 

Hedgey will research the requirements to deploy its smart contracts onto Filecoin EVM, and use RPCs and the necessary infrastructure to host and maintain a backend indexer, front end UI to deploy the entire application onto FEVM. 

We estimate it will take 1 week for smart contract deployments. 
1 - 2 weeks after for standing up the data indexer, back end event listener, and storage systems, and at the end of that link up the front end UI. 
In less than a month we think we can have the full production app tested and deployed to production, and start onboarding initial token projects and users. 
Our goal after that is to become the go to system for token distributions for teams, we would like to have onboarded at least 5 teams by the end of August. After this we plan to collaborate with existing teams for adding native Filecoin wallet connectivity and other features to the application to make it broadly usable by all projects. 

## Adoption, Reach, and Growth Strategies

We often work hand in hand with projects 6 - 9 months prior to their token launch, and help them navigate the process of launching a token, and then assist with onboarding them to Hedgey for their token distributions. We find customers through partnerships, word of mouth and advertising, but the strongest relationships are built through direct references from Filecoin itself. 

## Development Roadmap

Milestone 1: Deploy Smart Contracts to FEVM. We would run tests to ensure all smart contracts behave as expected. 2 developers work on this milestone, one smart contract developer, and the CTO. We expect this to be completed in under 1 week. 

Milestone 2: Develop & Deploy back end infrastructure, including the indexer, database, file & proof storage system, public API and GraphQL endpoints. This requires 2 developers to work on this milestone, the CTO and the senior back end engineer. We expect this to take a week for completion. 

Milestone 3: Deploy & Link the Hedgey App UI to the smart contracts, SDK, and back end APIs & indexer. This is the last step for production launch, and we would complete this with the full app production deployment after sufficient testing. This requires 4 developers, the CTO, smart contract developer, front end engineer and back end engineer, all working together and completing multiple days of testing. We expect this to take 2 weeks to complete sufficient testing for the application to be completely pushed to production and ready for end use and client onboarding. 

Milestone 4: Onboard 5 projects with their tokens to Hedgey. This requires 3 individuals on the sales side, and potentially developer hours for any custom work required for support of specialized tokens. We hope to achieve this goal within 2 months after production launch. 

## Total Budget Requested

| Milestone # | Description | Deliverables | Completion Date | Funding |
|===|===|===|===|===|

## Maintenance and Upgrade Plans

Long term we plan to deploy the entire project onto Filecoin, migrating from our existing infrastructure. This migration would include not just FEVM support, but also a much larger Hedgey App using Filecoin for all of the non-smart contract infrastructure (ie app hosting, indexing, and file & proof storage), that would be accessible and usable across the entire web3 ecosystem for all chains to enjoy. This is a much larger build and requires significant development time, but will allow for the team to offer a truly globally accessible set of token distribution tools as public goods that can live on indefinitely in a decentralized and open way. In the short term we do pay for database, file storage and website hosting services to 3rd party providers, as well as 3rd party RPC providers for our app maintenance and hosting. 

# Team

## Team Members

Alex Michelsen, Cofounder, CFO, Smart contract engineer

Lindsey Winder, Cofounder, CEO

Shawn Simas, Cofounder, CTO

Mark Howard, Senior Back End Engineer

Hugh Law, Senior Front End Engineer

Ella Sherifova, Head of Business Development

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/alex-michelsen-cfa-59357421/

https://www.linkedin.com/in/lindsey-winder-14897b46/

https://www.linkedin.com/in/shawnsimas/

https://www.linkedin.com/in/markhowardeu/

https://www.linkedin.com/in/hughlaw/

https://www.linkedin.com/in/ellasherifova/

## Team Website

[Hedgey Finance](https://hedgey.finance)

## Relevant Experience

Hedgey has been building in the defi space since 2021 as an alumni of the Tachyon Filecoin Accelerator. The 3 cofounders have been working together and building web3 projects since 2018. 

## Team code repositories

https://github.com/hedgey-finance

# Additional Information

We were introduced to Eva by Jon at the Glif team, who we are partnering with as our first launch client. 

alex@hedgey.finance

**Comment by Schwartz10** [comment]
Advocating for the FF to approve this proposal! GLIF would build on top of Hedgey, and has been in close contact with their team in case they need technical help on deployments / FEVM assistance

**Comment by ErinOCon** [comment]
Hi @icemanparachute, thank you for your patience with our review process! As mentioned in our recent email communication, this proposal has progressed to the final steps of our review process. You can expect to receive future updates from grants@fil.org.
