### ISSUE TITLE
Filecoin Interactive Learning Lab

### ISSUE THREAD

**Issue by codedey** [filecoin-project/devgrants#1754]
# Grant Proposal: `Filecoin Interactive Learning Lab`

**Filecoin Interactive Learning Lab:**

**Individual or Entity Name:** Code_dey.

**Proposer:** `@codedey`

**Filecoin ecosystem affiliations:** `Filecoin Foundation 

**(Optional) Technical Sponsor:** `NA`

### 1. What is your project and what existing gap will your project address? 
The Filecoin Interactive Learning Lab will be a comprehensive, interactive platform designed to enhance the learning experience for developers using Filecoin. The Learning Lab will include interactive tutorials, AI code playgrounds, and video walkthroughs to provide hands-on experience with Filecoin APIs, SDKs, and tools.

### 2. How does your project align with our program focus areas? 
By building a complete platform with interactive lessons, AI coding playgrounds, and video walkthroughs, the Filecoin Interactive Learning Lab complements all three programme core areas. These materials will walk through popular use cases such data storage and retrieval, storage deal management, and smart contract interaction using Filecoin APIs, SDKs, and tools. Furthermore, the Learning Lab will include comprehensive developer guides that cover setup procedures, how to use the API, and troubleshooting advice, improving the documentation's instructional value and accessibility for developers using Filecoin.

### 3. What are the expected outcomes of the project? What steps will you take to meet this objective? 

| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                 | :---                                                       | :---                       | 
| 1.     |  Research, Planning, and Initial Development |Identification of key topics and use cases for tutorials, code playgrounds, and video content; outlining the structure and flow of interactive tutorials and guides; and developing interactive tutorials, code playgrounds, and comprehensive developer guides. | 1 month | 
| 2.     | Development and Production | Continuous development of interactive tutorials and code playgrounds, completing the initial draft of the comprehensive developer guides, recording and editing video walkthroughs, and integrating initial feedback from early testers to refine tutorials and playgrounds. | 1 month | 
| 3.     | Testing, Refinement, and Launch | Testing all interactive elements and tutorials for usability and accuracy, gathering feedback from beta testers and refining content, finalizing and ensuring user-friendliness, then launch and promote the Filecoin Interactive Learning Lab through social media, developer forums, and the Filecoin community. | 1 month | 

### 4. How will you determine if your documentation is successfully supporting your intended audience? 
We will utilise a combination of user engagement measures, feedback gathering, and community interaction analysis to ascertain if the Filecoin Interactive Learning Lab effectively serves its target audience. In addition to good user ratings and feedback via integrated surveys, key metrics will include high page visits, session lengths, and completion rates for instructional and interactive activities. We will compile endorsements and success stories to showcase practical uses and advantages. Keeping an eye on conversations on social media and Filecoin forums, along with examining help requests, will give more information on how successful the learning lab is. Frequent analytics reports will direct iterative changes, guaranteeing that the documentation is still applicable and beneficial. The Learning Lab's effectiveness will be shown by its steady high level of activity, encouraging comments, verified user success stories, and Filecoin recognition.

### 5. Will this work be published under the dual MIT and APACHE2 licenses?
Yes

### 6. Does your proposal comply with our Community Code of Conduct? 
Yes

### Additional questions: 

Team Member Information:
- Name: Lambat Ibrahim Osman
- Email: [codedeyy@gmail.com](mailto: codedeyy@gmail.com)
- GitHub: [Code_dey](https://www.github.com/codedey)
- Role: Lead

How did you learn about this program?
Through Filecoin Foundation

**Comment by ErinOCon** [comment]
Hi @codedey, thank you for your time with this proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.

Wishing you the best with your future projects!
