### ISSUE TITLE
Filecoin MetaMask Wallet - Major updates and MetaMask UI integration

### ISSUE THREAD

**Issue by eshon** [filecoin-project/devgrants#1762]
# Open Grant Proposal: `Filecoin MetaMask Wallet - Major updates and UI integration`

**Project Name:** FilSnap - Major Updates and UI 

**Proposal Category:**  `Developer and data tooling`

**Individual or Entity Name:** @hugomrdias

**Project Repo(s)** https://github.com/filecoin-project/filsnap and https://snaps.metamask.io/snap/npm/filsnap/

**(Optional) Filecoin ecosystem affiliations:** Hugo is ex-Fission, ex-NFT.storage

**(Optional) Technical Sponsor:** @eshon 

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes

# Project Summary

Major updates and MetaMask UI integration for the open source [MetaMask Filecoin Wallet](https://snaps.metamask.io/snap/npm/filsnap/) ([Github repo](https://github.com/filecoin-project/filsnap)) which is a MetaMask plugin that supports native Filecoin addresses. 

Scoping and pre-maintenance work for this larger project was initially done as part of a [previous microgrant](https://github.com/filecoin-project/devgrants/issues/1735).

### Scope of Work:

MetaMask has released significant updates in 2024 to enhance the usability of Snaps and this grant would be used to integrate those updates into the Filecoin Metamask Wallet. Details:

 - lifecycle-hooks: onInstall, onUpdate. Needs permissions endowment:lifecycle-hooks 
     - onInstall can show a dialog similar to wallet ui
     - onUpdate we can should changelog and npm/github links and provenance
 - Homepage overrides the previous snaps info page
     - OnHomePageHandler another hooks to build the homepage UI and needs permissions endowment:page-home its static ?? can we use this to be the “wallet ui” for account balance and address ? Does it refresh after a transactions ?
  - Transaction Insights 
  - Signatures Insights - OnSignatureHandler can return UI with info and severity level that changes the UI accordingly
  - Dynamic UI - Show be useful to do transactions in the extension avoiding companion dapp 
  - Localization ?
  - Custom Name Lookup?
  - Keyring?
  - Misc Improvements to FilSnap

## Impact 

Filecoin dapps require a web3 wallet for users to interact with the dapp's smart contracts. The MetaMask Filecoin Wallet (Snap) supports Filecoin users with the ability to sign Filecoin transactions (including FEVM) using MetaMask. It can store native Filecoin key material in the MetaMask vault. This wallet is an open source project at https://github.com/filecoin-project/filsnap and has been a project in the Filecoin ecosystem for several years, as MetaMask develops and evolves its 3rd party Snaps platform which launched for users in Fall 2023.

## Outcomes

- MetaMask Filecoin Wallet (Snap) with dynamic UI integrated into the MetaMask browser extension itself.
- New transactions insights information, signature insights, lifecycle hooks for updates and installs and other necessary technical updates that improve the overall UX
- Updated documentation.

## Adoption, Reach, and Growth Strategies

- Future blog posts describing the coming Filecoin MetaMask Snap updates and other Filecoin wallet and devtool-related initiatives Hugo is planning to work on
- With these major UI updates the uX of the Filecoin MetaMask Wallet will be greatly improved and ready to be promoted more in the Filecoin community

## Development Roadmap

| Number | Grant Deliverable      | Timeframe (within 3 months)|
| :---   | :------                              | :---                       | 
| 1.     |  Lifecycle hooks               |            est.  5 days               | 
| 2.     |   Homepage overrides      |                est. 5 days          | 
| 3.     |   Transaction insights    |                est. 3 days           | 
| 4.     |   Signature insights    |                est. 3 days           | 
| 5.     |   Dynamic UI    |                est. 15 days           | 
| 6.     |   Misc improvements    |                est. 8 days           | 
|      |   **TOTAL**    |               **est. 39 days**        |

## Total Budget Requested

Will send to grants@fil.org

# Team

## Team Members

Hugo - [hugomrdias@gmail.com](mailto:hugomrdias@gmail.com) - https://github.com/hugomrdias (@hugomrdias) - Lead developer

## Team Member LinkedIn Profiles

https://pt.linkedin.com/in/hugomrdias

## Relevant Experience

Hugo has worked as a JS-savvy Sr. software engineer at Protocol Labs for several years and also more recently at Fission. He was the lead developer of the FilSnap architecture in 2023 and also of the [iso-filecoin](https://www.npmjs.com/package/iso-filecoin) cryptographic library for Filecoin. He also worked on NFT.storage and IPFS JS.

## Team code repositories

https://github.com/hugomrdias

# Additional Information
- How did you learn about the Open Grants Program?  @eshon
- Please provide the best email address for discussing the grant agreement and general next steps. hugomrdias [at] gmail.com

**Comment by ErinOCon** [comment]
Hello! This proposal has advanced to our final round of reviews scheduled to be completed by the end of August (if not sooner).

If we have questions during this review round, I will be in touch. Thank you again for your patience and for your interest in our grants program!

**Comment by ErinOCon** [comment]
This proposal has advanced to the next steps in our processing. Please respond to the email from grants@fil.org if you have any questions or updates. 

Thank you again for your proposal and for your interest in our grants program!
