### ISSUE TITLE
Footprint Analytics - Build Data Infrastructure for Filecoin

### ISSUE THREAD

**Issue by Connie-Footprint** [filecoin-project/devgrants#1764]
**Project Name:**
Footprint Analytics

**Proposal Category:** 
Developer and Data Tooling

**Individual or Entity Name:**
VANTASTONE TECHNOLOGY PTE. LTD.

**Proposer:** `replace with your GitHub username`
Connie-Footprint

**Project Repo(s)** Please list Github repos used for this project work. 
Github: https://github.com/footprintanalytics 

**(Optional) Filecoin ecosystem affiliations:** `Please disclose any existing work relationships with organizations in the Protocol Labs Network, including Protocol Labs, Filecoin Foundation, Filecoin Foundation for the Decentralized Web, and any others.` 

I would like to disclose that currently, I do not have any existing work relationships or affiliations with organizations in the Protocol Labs Network, including Protocol Labs, Filecoin Foundation, Filecoin Foundation for the Decentralized Web, or any others.

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

I haven't had the opportunity to discuss this project with any member of the IPFS or Filecoin project teams. Therefore, at this point, I don't have a technical sponsor.

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Please respond with "Yes" or "No".

No

# Project Summary

Blockchain is still a nascent technology, and we are just starting to understand and explore the value of the data it provides. At this early stage, effectively collecting, summarizing, and visualizing data is crucial.

However, blockchain data utilization faces challenges with large volumes of data, incompleteness, and difficulty in making sense of raw data, resulting in a high barrier to entry. Often, a certain technical background is required to leverage the data.

Footprint is designed to simplify blockchain data. With structured data tables, no-code analytics tools, ready-to-use APIs, and a combination of AI technology, we have lowered the barrier to using blockchain data. Our goal is to make blockchain data accessible to everyone.

Website: https://www.footprint.network/ 
Twitter: https://twitter.com/Footprint_Data 

## Impact 

By implementing this proposal, the Filecoin ecosystem will benefit in the following ways:

1. Expand the adoption of Filecoin: With AI and no-code analytics tools, making blockchain accessible to more users and a more effortless blockchain experience and opening up the power of decentralization to millions of people by making it even easier to use.
2. Empower developers to build their DApps more efficiently: We can provide structured data tables, data API and data solutions for all developers.
3. EnableFilecoin to understand ecosystem development effectively and make important decisions for the whole ecosystem.
4. Increase brand awareness for Filecoin: We can amplify Filecoin's progress with dashboards and research reports. We have over 50+ media channels with 500k+ exposure.

## Outcomes

**Our delivery includes the following:**
1. Structured Data Tables: We parse on-chain data into accessible, structured, and business-relevant tables, publicly available on the Footprint website.
2. Data Analysis Tools for Analysts: Free visualization tools support zero-code and SQL access to historical and real-time on-chain data, enabling the creation of charts and dashboards.
3. Data APIs for Developers: Both REST API and SQL are supported, allowing developers to build any application they desire.
4. Filecoin Ecosystem Analytics Dashboard for the Community: Pre-built dashboards showcasing community data trends.
5. Filecoin Research Report: We generate research reports based on on-chain data performance and expand exposure through our media channels to raise awareness about Filecoin.
6. Providing Data Education Content for Filecoin Community Users.
7. AI Assistant for Users and Developers: A custom GPT indexes documents, whitepapers, websites, and data to provide 24/7 support for the community.
8. Filecoin GPT Store: Create a custom GPT assistant for every project on the chain.
9. Community Growth Event: Using our AI quest tool based on Telegram, we help ecosystems and projects acquire users. Unlike other quest platforms, our AI quest leverages Telegram's vast potential user base and can verify both on-chain and off-chain tasks.
10. Co-Marketing Support: Includes AMA sessions, Twitter Spaces, and more.

**How our team measures program success:**
1. Structured tables and APIs after indexing the chain raw data
2. Long-term data maintenance and data support
3. AI assistant provides 7x24 hours support and query for community users.
4. Market resource support: Footprint has 50+ cooperative media channels, which can bring Filecoin a lot of exposure.
5. Bringing 10,000 new users to the Filecoin ecosystem by community growth event.

## Adoption, Reach, and Growth Strategies

We have almost 7,000 analysts and 700 developers using Footprint Analytics since we launched in August 2021. We have partnered with more than 400 clients to provide them with our data products or solutions, such as Animoca Brands, Sui, Ronin, Mocaverse, NHN and more.

We focus on a combination of Inbound and Outbound marketing strategy.
1. Inbound: 
- This is a relatively strong segment for the Footprint team, which has gained its current market influence with zero marketing spend. Footprint traffic is 70% organic, thanks to our content and research output. We have partnered with a number of research reports, such as Coinmarketcap coingecko.
- We have also established cooperation with many media channels, such as Cryptoslate, CryptoTimes, etc., and our content has been reproduced many times by other media outlets, such as Yahoo Finance.

2. Outbound: 
- Starting in Q3 2022, we formed a sales team to reach out to developers and customers from online and offline, in multiple countries to improve our sales performance.
BD cooperation: Work on BD cooperation with public chains, research institutions, communities, and other organizations, and participate in major industry conferences, Hackathons, etc., to increase exposure and influence.

## Development Roadmap

**Milestone 1 - Filecoin chain raw data on Footprint** 
By integrating raw data and generating structured data tables, users can use the data on Footprint to create charts and dashboards and explore the data freely, and developers can use the data API to build any application or build a data analytics system for their project.

1. Deliverabe:
- Structured data tables and APIs , such as chain blocks, protocol info, address etc..
- Filecoin ecosystem analytics dashboard
2. Fee: $30,000
- 60% of costs will be for data storage and long-term maintenance
- 40% for human resources involvement
3. Duration: 8 weeks
4. Human resource: 1 DevOps Engineer and 2 Big Data Engineers

**Milestone 2 - Filecoin telegram growth event and co-marketing** 
We will be hosting an ecosystem event to encourage users to join the ecosystem and engage with projects on the ecosystem, and all of our application fees will be used to incentivize the community.

1. Deliverabe:
- Jointly host a telegram lucky draw event, Link: http://t.me/PeaAIBot/Fission?startapp=666054783a6fd50018067143_1373560566
  1) Bring 10K new users to Filecoin
- Co-marketing
  1) Providing educational materials on the data sector to help ecosystem projects build data pipelines and establish data-driven operational systems to achieve long-term healthy operations
  2) Providing content support such as ecosystem research reports, project interviews, Twitter spaces, etc.
2. Fee: $20,000
- This fee will be used as a prize pool for the lucky draw
3. Duration: 1 month
4. Human resource: 1 Marketing, 1 Engineer and 1 UI

**Milestone 3 - Filecoin AI assistants for Filecoin ecosystem**
We can customize an AI gpt assistant for each project on the chain, and we can add project docs, whitepapers, on-chain data, etc. to the GPT to enable it to answer project questions and provide 24/7 community service. At the same time, the AI assistant can create on-chain and off-chain tasks, and users can get rewards for completing the tasks, which can not only incentivize on-chain behaviors, but also incentivize off-chain activities, which can promote the growth of the project.

1. Deliverabe:
- AI assistant for Filecoin community
- GPT store for projects on Filecoin [ecosystem](https://app.pea.ai/explore/all?channel=Sui%20Ecosystem)
2. Fee: free to use
3. Duration: 2 weeks
4. Number of developer: 1 Engineer

## Total Budget Requested
We request a $50,000 grant amount to support the delivery of 4 milestones.

## Maintenance and Upgrade Plans

Footprint has been launched for more than 3 years and we have indexed data from 30+ public chains and we will maintain this data for a long time.

- We have a data monitoring system to monitor the real-time update and accuracy of the on-chain data
- We will continue to automatically collect and decode the projects and contracts deployed on the ecosystem on a weekly basis.
- We work closely with coingecko and coinmarketcap, so we keep our data up to date to ensure our cooperation.

# Team

## Team Members

**Tony Zhang - Co-founder & CEO**  
- A serial entrepreneur with over 20 years of experience on Wall Street 
- Formerly Senior Vice President of Global Credit Trading at Bank of America in New York; Director of Credit Derivatives Trading at Merrill Lynch, also worked at Goldman Sachs Global, JPMorgan, and Lehman Brothers

**Wade Deng - Co-founder & CTO** 
- Over a decade of tech experience
- Director of a fintech company where he built anti-fraud systems and AI models for credit score
- Led a crypto trading team, which focused on algo trading strategy on CeFi

**Navy Tse - Co-founder & Head of Product** 
- Over 10 years of experience in fintech, big data, e-commerce, and mobile internet development
- Entered the blockchain technology space in 2017
- Led the team to develop several DeFi projects
- A pioneer in the open source community, contributed to the Open Source Project with over 37k stars.

## Team Member LinkedIn Profiles

Tony Zhang: https://www.linkedin.com/in/tzhang88/
Wade Deng: https://www.linkedin.com/in/wade-deng-84bb8b6b/
Navy Tse: https://www.linkedin.com/in/navyxie/

## Team Website

Not yet.

## Relevant Experience

In the data track of blockchain, Footprint has competitive advantages in the following areas
1. Competitive Landscape of the Public Chain Market: We have extensive experience indexing over 30 public chains, including significant expertise in non-EVM chains.
2. Professional Blockchain Data Solutions: We provide BI customization services to leading web3 gaming titles, including Animoca Brands, NHN, Square Enix, and more.
3. Marketing Operations: Our in-house research team collaborates with media and the community to produce market reports.
4. Our team is a fully integrated one that not only possesses the ability for technical development but also excels in project operations, particularly in the operation of products in the blockchain data and financial domains.
  - Refined technical capabilities. Our core team is made up of experienced developers.Prior to venturing into the blockchain space, our team members have worked in reputed companies such as Goldman Sachs, JP Morgan Chase and Oracle.
    1) Since 2017, we have been deeply rooted in the blockchain space, endowing us with a rich reservoir of knowledge and expertise:
       - Early movers in BTC/ETH mining.
       - Crypto market data mobile application
       - Algorithmic crypto trading 
       - Multiple innovative DeFi protocols
       - Blockchain data platform
       - Vertical blockchain AI platform

## Team code repositories

https://github.com/footprintanalytics

# Additional Information

Twitter

connie@footprint.network

Footprint technical [documentation](https://docs.footprint.network/docs)

**Comment by ErinOCon** [comment]
Hi @Connie-Footprint, thank you for your time with this proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.

Wishing you the best as you continue building!

**Comment by Connie-Footprint** [comment]
Hi Filecoin team

I am writing to you today to follow up on my recent grant application. I
was disappointed to learn that my application was not selected for funding,
but I would appreciate it if you could provide me with some feedback on the
reasons for the decision.

I am particularly interested in understanding how my project aligns with
the foundation's funding priorities. I am also eager to learn more about
the types of projects that the foundation typically supports.

Although we didn't go through with the grant application, I'd still like to
keep in touch with Filecoin, and I've set up a group chat on Telegram that
I'd like you to join: Filecoin <> Footprint Analytics
<https://t.me/+EHr0_KIXNecyMDc1>

Thanks.
Connie







ErinOCon ***@***.***> 于2024年7月24日周三 02:52写道：
