### ISSUE TITLE
Chains Beyond Borders

### ISSUE THREAD

**Issue by meko-cell** [filecoin-project/devgrants#1771]
**Open Grant Proposal:** Chains Beyond Borders

**Project Name:** Chains Beyond Borders

**Proposal Category:** `Other`. Learn what these categories are [here](https://github.com/filecoin-project/devgrants/blob/master/Program%20Resources/Open%20Grants%20README.md). 

**Individual or Entity Name:**  FD CAPITAL
**Proposer:** `meko-cell`

**Project Repo(s)** Please list Github repos used for this project work. 

**(Optional) Filecoin ecosystem affiliations:** `Please disclose any existing work relationships with organizations in the Protocol Labs Network, including Protocol Labs, Filecoin Foundation, Filecoin Foundation for the Decentralized Web, and any others.` 

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Please respond with "Yes" or "No". "Yes'

# Project Summary

## Total Budget Requested

Milestone 1: Event Planning and Preparation (Weeks 3-6) Milestone 2: Marketing and Promotion (Weeks 7-10)Milestone 3: Final Preparations and Event Execution (Weeks 11-14)Milestone 4: Post-Event Activities (Weeks 15-16)
--

## Maintenance and Upgrade Plans

# Team

## Team code repositories

# Additional Information

**Comment by realChainLife** [comment]
Hi @meko-cell closing this issue since application is incomplete.
