### ISSUE TITLE
IPFS Content Authenticity utilizing C2PA and Mentaport Watermarking

### ISSUE THREAD

**Issue by asghaiermp** [filecoin-project/devgrants#1779]
# Open Grant Proposal: `IPFS Content Authenticity utilizing C2PA and Mentaport Watermarking`

**Project Name:** IPFS Content Authenticity utilizing C2PA and Mentaport Watermarking

**Proposal Category:** Integrations

**Individual or Entity Name:** Entity - Mentaport Inc.

**Proposer:** asghaiermp

**Project Repo(s)** 
https://github.com/mentaport/c2pa-js
https://github.com/mentaport/ipfs-c2pa

**(Optional) Filecoin ecosystem affiliations:**  

**(Optional) Technical Sponsor:** 

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Partially ( We will be open-sourcing all the IPFS and C2PA integration, including APIs. Mentapors Watermark technology is not open source. )

# Project Summary

Through this project, Mentaport aims to enhance content authenticity verification by integrating the Content Authenticity Initiative C2PA standard and Mentaport Watermarking technology within IPFS. This project addresses the growing demand for reliable digital content verification to combat misinformation and digital content manipulation and misuse. Mentaport proposes leveraging C2PA and Watermarking to ensure the integrity and availability of digital content uploaded to IPFS.

The project will develop a seamless integration between Mentaport's C2PA solution and IPFS, allowing users to efficiently store and retrieve authentic content and their certificates on IPFS. The integration will involve creating a user-friendly interface for managing certificates, tools for embedding and verifying C2PA metadata in digital content, and a robust backend to handle content certification and verification with required IPFS interactions.

Among the particular integrations that Mentaport will work on is to devise the right integration between IPFS IPNS and CID and C2PA metadata. One of the exciting aspects of IPNS is the capability to resolve an IPNS to the most recent CID; however, editing and modifying content will make it challenging to discover and find the CIDs for previous versions. Mentaport, through this project, will build the tools that will tie the usage of IPNS and CIDs to the proper schema of C2PA metadata such that the trace of all editions can be easily retrieved and discovered from the most recent CID and also provide a content authenticity tracking and trace that can be verified across all CID instances.

## Impact 

Mentaport believes this proposal is valuable for the Filecoin and IPFS ecosystems as it addresses critical pain points related to content authenticity and trust on the internet. A solution to enhance users' trust in content stored in decentralized storage and protect the rights of creators and content creation platforms utilizing IPFS as their primary storage option. The proliferation of digital misinformation poses a significant risk to public trust and information integrity; thus, ensuring content authenticity can mitigate these risks by providing verifiable proof of content origin and integrity.

By integrating C2PA and Mentaport Watermarking with IPFS, we can provide a decentralized solution that enhances the transparency of digital content verification. This project is believed to benefit content creators, content publishing platforms, and consumers by offering a mechanism that can be trusted by all stakeholders for verifying content authenticity.

With C2PA metadata easily modified, IPFS usage and integration between the two schemes can benefit IPFS by providing content authenticity for its file storage and C2PA by offering a more robust way for sharing files with C2PA metadata that can't be modified and removed without detection.

## Outcomes

The final deliverables of the project include:
- APIs for interacting with IPFS to store and retrieve the content and content authenticity certificates.
- Defining a method to link C2PA metadata manifest schema with IPFS IPNS and CIDs
- Documentation for users and developers.
We propose to measure success by the number of users adopting the solution, the volume of content authenticity certificates stored on IPFS, and the feedback provided by stakeholders on the system's ease of use.

## Adoption, Reach, and Growth Strategies

Our target audience includes digital content creators, publishing platforms, and consumers interested in content authenticity. This audience spans different verticals, including media, entertainment, and gaming, which encompass millions of users globally. We currently engage with our audience through our existing platform and several community channels, and we have worked with several partners and customers to obtain early feedback.

Our outreach strategy includes webinars, tutorials, and collaboration with key industry stakeholders. The initial focus will be onboarding the first 5-10 content creators or publishers through direct outreach, scaling up as we gather feedback, and improve the system.

### Milestone 1: Project Initialization

- Set up project repositories and development environment
- Initial design and architecture planning
- Funding: $10,000
- Completion Date: 1 week

### Milestone 2: API Development

- Create APIs for embedding and verifying C2PA metadata
- Integrate with existing Mentaport SDK and tools
- Funding: $10,000
- Completion Date: 2 weeks

### Milestone 3: IPFS Integration

- Integrate IPFS storage and retrieval functionalities within the app and the schema linkage between IPNS/CIDs and C2PA metadata
- Funding: $15,000
- Completion Date: 3 weeks

### Milestone 4: Testing, Documentation, and Deployment

- Running required testing and debugging
- Develop documentation and tutorials
- Deploy the solution and conduct user onboarding
- Funding: $15,000
- Completion Date: 1 week

## Total Budget Requested

|  Milestone #  |  Description  |  Deliverables  |  Completion Date  |  Funding  |
| 	:-----:	 | 	:-----:	 | 	:-----:	 | 	:-----:	 |	:-----:	 |
| 1 | Project Initialization | Repositories, environment setup, initial design | 1 week | $10,000 |
| 2 | API Development | APIs for C2PA metadata | 2 weeks | $10,000 |
| 3 | IPFS Integration | IPFS storage and retrieval functionalitiesSchema definition for IPNS/CID linkage to C2PA metadata | 3 weeks | $15,000 |
| 4 | Testing, Documentation, Deployment | Testing, documentation, tutorials, deployment | 1 week | $15,000 |

## Maintenance and Upgrade Plans

We plan to maintain and improve the project continuously. This includes regular updates based on user feedback, ensuring compatibility with IPFS updates, and adding new features to enhance functionality. We will establish a team that will handle ongoing support and maintenance, address raised issues, and ensure the solution remains robust and reliable.

# Team

## Team Members

- Mariale Montenegro (Project Lead)
- Ahmad Sghaier Omar (Backend Lead Developer)
- Fronted Engineer ( To be hired once project is confirmed)

## Team Member LinkedIn Profiles

- [Mariale Montenegro LinkedIn profile](https://www.linkedin.com/in/thinkmariale)
- [Ahmad Sghaier Omar LinkedIn profile](https://www.linkedin.com/in/ahmad-sghaier-2619a645/)

## Team Website

[Mentaport Website](https://www.mentaport.com)

## Relevant Experience

Our team has extensive experience in digital content management, blockchain technologies, and decentralized storage solutions. We have successfully delivered similar projects, demonstrating our capability to handle this project efficiently. Our C2PA, IPFS, and web development expertise ensure we can successfully execute this project.

## Team code repositories

[Mentaport Github](https://github.com/Mentaport)

# Additional Information
We learned about the Open Grants Program through community channels and discussions with industry peers.

To learn more about Mentaport, visit us at[ www.mentaport.xyz](http://www.mentaport.xyz/). For further discussions regarding the grant agreement and the next steps, please contact us at hello@mentaport.com.
We are excited about the potential impact of this project and look forward to contributing to the IPFS and Filecoin ecosystems.

**Comment by ErinOCon** [comment]
HI @asghaiermp, thank you for your time with this proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.

Wishing you the best as you continue building!
