### ISSUE TITLE
eOracle data feeds on Filecoin

### ISSUE THREAD

**Issue by liranmarkin** [filecoin-project/devgrants#1782]
# Open Grant Proposal: eOracle data feeds on Filecoin

**Project Name:** eOracle

**Proposal Category:** `Developer and data tooling`.

**Individual or Entity Name:** [eOracle Foundation](https://eoracle.io/)

**Proposer:** @liranmarkin

**Project Repo(s):** https://github.com/Eoracle/target-contracts

**(Optional) Filecoin ecosystem affiliations:** This is our first work relationship.

**(Optional) Technical Sponsor:** Sarah Thiam from Protocol Labs and Eva from Filecoin.

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes.

# Project Summary

eOracle extends Ethereum's trust to connect decentralized applications with off-chain data as the largest restaking protocol backed by over $5B of stake ETH through 120,000 stakers and over 100 validators distributed around the globe. eOracle provides reliable and secure on-chain price feeds, as well as custom data feeds.

## Impact 

- eOracle provides 13 price feeds to Filecoin: [eOracle Price Feeds](https://eoracle.gitbook.io/eoracle/price-feeds/feed-addresses). This enables a wide variety of feeds needed for a robust DeFi ecosystem.
- eOracle's modular architecture allows custom data feeds to be built on top of it. This could allow Filecoin developers, who are pioneering decentralized data use cases, to use it on-chain as well.
- eOracle provides price feeds in a more cryptoeconomically secure way compared to other oracles.

## Outcomes

- eOracle has already deployed price feeds to the Filecoin Calibration Network.
- eOracle will deploy the following price feeds to Filecoin Mainnet and maintain them for a year:
  - AUD/USD
  - BTC/USD
  - ETH/USD
  - EUR/USD
  - FIL/USD
  - GBP/USD
  - LINK/USD
  - SOL/USD
  - USDT/USD
  - XAU/USD
  - sFRAX/FRAX
  - sfrxETH/frxETH
  - stETH/ETH

## Adoption, Reach, and Growth Strategies

Our target audience is dApp developers in the Filecoin ecosystem, and we cater to both DeFi and non-DeFi use cases. The integration with eOracle is simple, and our technical support is available for the Filecoin ecosystem.

## Development Roadmap

eOracle is already live on the mainnet. Check out our documentation at [eOracle Docs](https://eoracle.gitbook.io/eoracle).

## Total Budget Requested

| Milestone # | Description                                   | Deliverables                           | Completion Date           | Funding |
|-------------|-----------------------------------------------|----------------------------------------|---------------------------|---------|
| 1           | Gas funds for publishing 13 feeds for 1 year  | eOracle price feeds on Filecoin Mainnet | A few days after grant received | $10,000 |

## Maintenance and Upgrade Plans

eOracle will continue to grow outside of the Filecoin ecosystem and will be maintained by the eOracle Foundation.

# Team

## Team Website

https://eoracle.io/

## Contact information
Email: partnerships@eoracle.io

# Additional Information
Thank you for your willingness to support our project! This grant will allow us to serve dApps on the Filecoin ecosystem. To discuss the grant and next steps, please contact us at partnerships@eoracle.io.

Website: https://eoracle.io/
Docs: https://eoracle.gitbook.io/eoracle

**Comment by ErinOCon** [comment]
Hi @liranmarkin, Thank you for your time with this proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.

Wishing you the best as you continue building!

**Comment by eshon** [comment]
Hi @liranmarkin - Is it possible to deploy eOracle to Filecoin Mainnet now?
We are interested in revisiting this proposal now.
I have tried reaching out to the eOracle team on Telegram and via the eo.tech's contact form but haven't been able to get a hold of anyone.
There is a Pyth deprecation happening on July 31, 2026, so it's kind of urgent.
Please let me know if you can put us in touch with someone from the eOracle team.
