### ISSUE TITLE
fil.eco - Build a gathering place for filecoin ecological projects

### ISSUE THREAD

**Issue by ohash-eth** [filecoin-project/devgrants#1783]
# Open Grant Proposal: `fil.eco`

**Project Name:**  `fil.eco`

**Proposal Category:** `Integrations`

**Individual or Entity Name:** `individual`

**Proposer:** `ohash-eth`

**Project Repo(s)** `https://github.com/ohash-eth/fileco`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** `Yes`.

# Project Summary

fil.eco will build a centralized location for FILECOIN ecological projects.
fil.eco will collect relevant projects of the filecoin ecosystem through the co-construction of web3 users, and provide information improvement through different channels for the projects, and finally form a one-stop information service platform for the filecoin ecosystem projects

<img width="1433" alt="image" src="https://github.com/user-attachments/assets/0e1bbd7f-79c1-47b8-b986-f15e5cf451e2">

## Impact

- Currently, the Filecoin ecosystem has flourished, but as a developer or web3 user, there is no convenient channel to quickly learn about related ecological projects, and the project information collected through other means is not comprehensive.In addition, very early ecological projects have no place to communicate with users. Fil.eco can provide a channel for users to co-build new projects.
- Help web3 users who want to understand the filecoin ecosystem to quickly understand the overall picture, and can improve information and evaluation of various dimensions for ecological projects through co-construction
- The fil.eco domain name itself has the natural meaning of gathering filecoin ecological projects. When the platform has a certain number of users, it will be able to accumulate strength for the development of filecoin ecological projects.
## Outcomes

- fil.eco v1.0.0 includes two sections: Ecology and WEB3. It mainly includes web3 wallet login, project classification, details display, comments, likes, ecological project popularity ranking, ecological project application, and autonomy.
- fil.eco is positioned as a community-autonomous project. Through the power of the community, more than 90% of filecoin's ecological projects are integrated, and new ecological projects can be promoted to be exposed in the community.

## Adoption, Reach, and Growth Strategies

- fil.eco's target audience is developers and miners who are concerned about the development of the filecoin ecosystem, and web3 users who have expectations for fil tokens.
- filecoin is the infrastructure of web3 and is in a leading position in the web3 storage sector. With the increasing demand for web3 storage, I believe that the user base of fil will continue to expand, and at the same time, the number of fil ecological projects will increase. An integrated platform that can quickly obtain fil ecological projects in one stop will become particularly important. Therefore, fil.eco's audience will continue to expand with the development of fil.
- fil.eco will reach users of ecological projects by holding events with various ecological projects in the early stage

## Development Roadmap

Milestone 0
- fil.eco has completed the v1.0.0 product prototype and 30% of the Java development work
- Team: Product Manager/Java Developer (1)
- Funding: $0
- Completion Date: now

Milestone 1
- Functionality: v1.0.0 version, completed the front-end and back-end development of the prototype.
- Team: Product Manager/Java Developer (1) 、 Vue Developer (1)
- Funding: $10,000
- Completion Date: October 2024 

Milestone 2
- Functionality: Complete the cooperation and integration of 90% of filecoin ecological projects.
- Team: Product Manager/Java Developer (1) 、 Vue Developer (1) 、 Community Operator (2)
- Funding: $20,000 (Development Funds $15,000 、 Servers, etc $5000)
- Completion Date: December 2024

Milestone 3
- Functionality: Develop a community autonomous points system, the goal is to gradually separate fil.eco from the team and gradually become autonomous in the form of DAO
- Team: Product Manager/Java Developer (2) 、 Vue Developer (1) 、 Community Operator (2)
- Funding: $25,000
- Completion Date: Q1 2025

## Total Budget Requested

| Milestone # | Description              | Deliverables                   | Completion Date | Funding |
|:------------|:-------------------------|:-------------------------------|----------------|---------|
| 0           | product prototype        | completed                      | now | $0      |
| 1           | v1.0.0 version           | Complete development           | October 2024  | $10,000 |
| 2           | Website online operation | Ecological Project Cooperation | December 2024  | $20,000 |
| 3           | Upgrade Points System    | DAO                            | Q1 2025  | $25,000 |
## Maintenance and Upgrade Plans

- The basic team completes the development and maintenance of the above plan 
- After completing the prototype of community autonomy, the team will continue to upgrade according to community suggestions and product planning

# Team
ohash :  Product Manager  / Java Developer

## Team Website

 [https://ohash.io](https://ohash.io) 

## Team code repositories
Ohash is a blockchain enthusiast and developer. He participated in the early testing of the filecoin project and was officially thanked by the developer.
He has designed and developed web3 multi-chain wallets and multi-signature wallets.

# Additional Information
- Learn about the Open Grants Program from the official website
- email: pengkai0506@gmail.com
- The two domain names fil.eco and filecoin.eco have been purchased

# Product prototype
<img width="1424" alt="image" src="https://github.com/user-attachments/assets/5ebbc711-c7d4-4a09-8b13-da1fd89bf212">
<img width="1423" alt="image" src="https://github.com/user-attachments/assets/730edc64-4e34-4b6e-8243-c32d2bb0d5e5">
<img width="1426" alt="image" src="https://github.com/user-attachments/assets/747c218e-c428-42ce-b139-a762e963bcd8">
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/0c8d6e3f-124c-4b5d-8d64-3a9e61881428">

**Comment by ErinOCon** [comment]
@ohash-eth, thank you for your patience with our review. Unfortunately, we will not be moving forward with a grant for this proposal. If you have any questions for our team, please contact grants@fil.org. 

Thank you again for your interest in our grants program.
