### ISSUE TITLE
Digital business card for corporate employees and govt. individuals

### ISSUE THREAD

**Issue by jaymishra01** [filecoin-project/devgrants#1785]
# Open Grant Proposal: `Alliance- your network is your networth`

**Alliance**

**Integrations:** Choose one of `data tooling`, `Integrations`, `Research & protocols`, `Storage`, `Retrieval`, `FVM`, or `Other`. Learn what these categories are [here](https://github.com/filecoin-project/devgrants/blob/master/Program%20Resources/Open%20Grants%20README.md). 

**clever technologies:** Is the proposal for an individual, or an entity/organization? Please note that the agreement and any payments must be completed by the same entity, either individual or organization.

**jaymishra01:** `replace with your GitHub username`

**N/A** Please list Github repos used for this project work. 

**(Optional) Filecoin ecosystem affiliations:** `Please disclose any existing work relationships with organizations in the Protocol Labs Network, including Protocol Labs, Filecoin Foundation, Filecoin Foundation for the Decentralized Web, and any others.` 

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Please respond with "Yes" or "No".

# Project Summary

## Impact 

- This project will entwine with professional social media career and job websites and can revolutionize the job and career ecosystem by adding an automatic credulity to each individual who is sincerely trying their level best while minimizing fraud.
- the product will revolutionize the corporate sector by following culture and instead, it will only consider the contacts made by people who met each other. This will add the highest level of credulity and credibility to individual talent. 

## Outcomes

 A digital business card exchange app where cards can only be exchanged when users are physically in each other's vicinity. This will develop a chain of smart exchanges that will be stored along with GPS location and exchange time stamp. This digital card asset will use Filecoin to provide static data storage for the users. The user will only have to pay for data retrieval instead of storage. The users of this app can send each other docs and numbers in exchange for the amount they fix for their information. Therefore, no more education or information is taken for granted. This app will also allow the professional community to carry each other courier during their flights (max 15kg) for their loved ones at flight speed and therefore get a chance to earn real mile-high money.

by on boarding all corporate offices to issue digital business cards for their employees using our application.
## Adoption, Reach, and Growth Strategies
corporate offices
government offices
individual properties
aspiring students looking for internships.

By issuing the digital cards in my own company of 500 people.
## Development Roadmap
The app needs to carefully developed with all business card features by integrating it with the ESIM technology. then more digital feature will be added using blockchain to record each card transaction. This will be followed by adding professional features to make it card more powerful by curating professional services with each card. lastly, robust security will be applied so nobody can disturb the privilege and confidentiality of users on the platform.

KINDLY refer to the attached ppt slide.

## Total Budget Requested $50000

| Backend development of business card wallet, Frontend integration of mobile application sensor features, UI development, UX development, server deployment, customer onboarding.
 # | It will be a privileged and confidential professional community with the transparent lifestyle of employees. The members of this community will have a powerful business card that will record each business card exchange to show individuals' network and networth status. The digital business card of employees will be ranked according to their position. Plus each individual will get static cloud storage which keep growing with every recharge.   | Deliverables | Completion Date | Funding |
|===|===|===|===|===|

## Maintenance and Upgrade Plans

# Team

## Team code repositories

# Additional Information

**Comment by jaymishra01** [comment]
For growth strategy the main stakeholder will be the conference organisers.

**Comment by ErinOCon** [comment]
Hi @jaymishra01, thank you for your time with this proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant for this project. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.

Wishing you the best as you continue building!

**Comment by jaymishra01** [comment]
Hi,
Thanks for not funding my idea. In promise while building my application i
will also not use filecoin. It is unfortunate that I participated in such
idea gathering scam.

Regards

Sincerely,
Jay Mishra
https://www.linkedin.com/in/jayendra-mishra-27027261/
