### ISSUE TITLE
OpenMark: Filecoin-Powered Marketplace for Gaming

### ISSUE THREAD

**Issue by mutobui** [filecoin-project/devgrants#1789]
# Open Grant Proposal: `Filecoin-Powered Marketplace for Gaming`

**Project Name:** OpenMark (https://openmark.io)

**Proposal Category:** `Integrations`. 

**Entity Name:** Grindy Technologies.

**Proposer:** `github.com/mutobui`

**Project Repo(s)** https://github.com/grindytech. (Currently, most repositories are private.)

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** "Yes".

# Project Summary

OpenMark: The Open Marketplace for Traditional Game Adoption with a GameFi background and a $66M trading volume, we understand the challenges of integrating traditional games into the blockchain.

For Web2 Gamers:
Blockchain can be harsh for traditional users. That's why we've developed a new trading mechanism that is simple, fast, and secure—making it easy for Web2 users to understand and engage in trading.

For Web2 Creators:
Coding and IPFS can be daunting. We provide no-code, decentralized tools for NFT artists, enabling game creators to launch NFT collections with just a few clicks.

For Game Projects:
Many projects struggle with poor game economies. Our open drops allow creators to set up sales campaigns in minutes with a streamlined, click-through process.

## Impact 

Deploying and integrating OpenMark with Filecoin will address several issues with IPFS:

Data Availability: IPFS can face data availability problems when gateways are down or pinning services are not maintained. Filecoin provides a stable, accessible solution with improved data persistence and availability.

Cost Efficiency: For gaming projects that involve storing and maintaining large amounts of data, the cost can be significant. Filecoin addresses this issue with its supply and demand model, offering much lower costs.

Blockchain Integration: The IPFS model, which is based on web2 payment systems, doesn’t seamlessly integrate with blockchain-based payment methods. Integrating Filecoin allows users to access OpenMark services directly with their crypto wallets, simplifying the user experience without requiring additional setup.

## Outcomes

After deploying and integrating with Filecoin, users can utilize OpenMark services to generate NFT collections and store them on Filecoin within minutes through a simple, click-based process. The best part is that users can then use this NFT collection on any network where OpenMark operates.

With the generated NFT collection, users can list it for sale in a drop within seconds. All of these processes can be completed using just a web3 wallet.

## Adoption, Reach, and Growth Strategies

- Target Audience:
Our primary target audience consists of gamers and NFT enthusiasts, particularly those interested in the growing intersection of gaming and blockchain technology. Gaming is one of the largest and most dynamic sectors in the crypto space, with a rapidly expanding market for digital assets.

- Onboarding Strategy:
We are actively collaborating with gaming projects to provide them with tools that enable the creation of in-game items within minutes and Gamers can easily trade these in-game assets using our new trading mechanisms, which make trading much easier, faster, and cheaper.

### **Milestone 1: Deployment to Filecoin Testnet & Community Launch**
- **Duration:** 1.5 months  
- **Team:** 5 FTE  
- **Description:** This milestone focuses on deploying OpenMark, an EVM-compatible platform, to the Filecoin Testnet. The deployment process is straightforward due to OpenMark's compatibility with the EVM.  
- **Functionalities:**  
  - Create NFT Collections with Filecoin Storage
  - Mint NFTs utilizing Filecoin Storage
  - List NFTs for Sale
  - Make and Accept Offers
  - Place Bids
- **Campaigns:**  
  - Implement a points-based system where users earn rewards by trading NFTs.

### **Milestone 2: Filecoin Decentralized Storage & Testnet Launch**
- **Duration:** 1 month  
- **Team:** 5 FTE  
- **Description:** This milestone is centered around integrating Filecoin's decentralized storage with game projects. The focus is on enabling game developers to create and manage NFT collections efficiently.  
- **Functionalities:**  
  - Generate NFT Collections: Start with layered images or Photoshop files, storing collections on Filecoin.
  - NFT Drops: Enable game projects to list and distribute their NFT collections.
- **Campaigns:**  
  - Expand the points-based system to allow users to mint and trade NFTs, earning rewards in the process.

### **Milestone 3: Mainnet Launch & Fee-Based Storage Integration**
- **Duration:** 1.5 months  
- **Team:** 5 FTE  
- **Description:** This milestone focuses on the full integration and launch on Mainnet, including the implementation of a fee-based system to cover Filecoin storage costs through NFT trading fees. It also involves deploying in-house game projects and NFT collections to validate the platform's capabilities.  
- **Functionalities:**  
  - Implement a fee-based system to automatically handle Filecoin storage costs via NFT trading fees.
  - Deploy and test in-house game projects and NFT collections on Mainnet.
  - Launch on Mainnet.
- **Campaigns:**  
  - Continue the points-based rewards system, allowing users to mint and trade NFTs while earning points.

## **Total Budget Requested: $38,000**

| **Milestone #** | **Description**                                           | **Deliverables**                                                                                             | **Completion Date** | **Funding** |
|-----------------|-----------------------------------------------------------|---------------------------------------------------------------------------------------------------------------|---------------------|-------------|
| **Milestone 1** | Deployment to Filecoin Testnet & Community Launch          | - EVM-compatible deployment on Filecoin Testnet<br>- NFT Collection creation with Filecoin storage<br>- NFT marketplace functionalities (sale, offers, bids)<br>- Community engagement and points-based rewards system | November 1, 2024    | **$14,000** |
| **Milestone 2** | Filecoin Decentralized Storage & Testnet Launch            | - Integration of Filecoin decentralized storage for game projects<br>- NFT generation from layers or Photoshop files<br>- NFT Drops for game projects<br>- Enhanced points-based rewards system | December 1, 2024    | **$10,000** |
| **Milestone 3** | Mainnet Launch & Fee-Based Storage Integration | - Mainnet launch with fee-based system to cover Filecoin storage costs<br>- Deployment of in-house game projects and NFT collections<br>- Finalization of points-based rewards system | February 1, 2025    | **$14,000** |

This table includes the specific completion dates for each milestone based on the starting date of September 15, 2024.

## Maintenance and Upgrade Plans

1/ Integration of Oracles for Randomness:
We plan to incorporate oracles to ensure reliable randomness for in-game events and NFT attributes, enhancing fairness and player engagement.

2/ Expanding Collaborations:
We aim to partner with more game developers and NFT creators to diversify our offerings and integrate innovative features that cater to a wide range of interests.

3/ Ongoing Platform Upgrades:
We will continually update and optimize our platform based on user feedback and industry trends, ensuring that we remain competitive and deliver value to our users.

# Team

## Team Members

Core team: 4, total members: 8

1. Thanh Bui Minh - Project Lead, Core Dev
4 Years of Blockchain Experience
LinkedIn: https://www.linkedin.com/in/thanhbuiminh/
Github: https://github.com/mutobui

2. Phan Dang Quy - Core dev
5 Years of Blockchain Experience,
Core Developer for Heroes & Empires with 200,000 users
Author of the ERC-7254 token standard.
LinkedIn: https://www.linkedin.com/in/phan-dang-quy/
Github: https://github.com/quyphandang

3. Do Tan Trung - Core dev
3 Years of Blockchain Experience,
Core Developer for Heroes & Empires
LinkedIn: https://www.linkedin.com/in/trung-dt/
Github: https://github.com/trungdo2789

4. Jack Huynh - Marketing
Former CEO of Heroes & Empire
LinkedIn: https://www.linkedin.com/in/quyethuynh2002/

## Team Website

https://grindy.io

## Relevant Experience

We began with GameFi projects and have over 3 years of experience working with blockchain technology, from Layer 1 protocols to smart contract development.

## Team code repositories

https://github.com/grindytech

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
