### ISSUE TITLE
Enhancing documentation of spinning up Lotus and f1-f4 wallet transfer

### ISSUE THREAD

**Issue by 1Busayo** [filecoin-project/devgrants#1793]
# Grant Proposal: `Enhancing documentation of spinning up Lotus and f1-f4 wallet transfer`

**Project Name:**

**Individual or Entity Name:** Individual

**Proposer:** `1Busayo`

**Filecoin ecosystem affiliations:** `Please disclose any existing work relationships with organizations in the Protocol Labs Network, including Protocol Labs, Filecoin Foundation, Filecoin Foundation for the Decentralized Web, and any others.` 

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

### 1. What is your project and what existing gap will your project address? 
Answer:
My project is creating a step-by-step guide on how to spin up a Lotus Node in documentation and recorded video, and also for F1-F4 wallets, and do transfers. Providing  recorded videos would easily guide beginners, it  video dev guides for Filecoin

### 2. How does your project align with our program focus areas? 
Answer:
My project covers a documentation and video guide that can serve as  a comprehensive tutorial and guide for developers

### 3. Please link previous examples of your work.
a) Text to NFTs on the Filecoin EVM
https://www.linkedin.com/pulse/text-nfts-blockchain-samuel-fanimokun
Github: https://github.com/1Busayo/AI-NFT-GENERATOR
Video: https://www.youtube.com/watch?v=pxiCbZDvPw4

b)Web3 E-commerce Store on the Filecoin EVM
Github: https://github.com/1Busayo/Dexstore
Video: https://www.youtube.com/watch?v=JSE6hwITy-Y

c) Using web3 to reduce carbon emissions on the Filecoin EVM
Github: https://github.com/1Busayo/CLEAFI
Video: https://www.youtube.com/watch?v=sECKVG3jKO0

d) Telehealth-web3 built on Filecoin EVM and huddle01
Github: https://github.com/1Busayo/Telehealth-web3
Video: https://www.youtube.com/watch?v=3MvsK0WiBf0

e) LINKE
Hackthon: https://ethglobal.com/showcase/linke-fwz3w
Github: https://github.com/1Busayo/LINKE
Video: https://www.youtube.com/watch?v=_maQKDYZqkk

### 3. What are the expected outcomes of the project? What steps will you take to meet this objective? 

| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)|
| :---   | :------                              | :---                                                                                         | :---                        | 
| 1.      |  Documentation               |     Steps on how to spin up Lotus Node                                |        3 weeks                       | 
| 2.     |  Documentation                |    how to setup f1-f4 wallet  and make transfers                |         2 weeks                      | 
| 3.     |  Video Guide                      |      Video Guide on how to spin up Lotus Node                  |        1 week                       | 
| 4.     |    Video Guide                    |       Video Guide on how to setup f1-f4 wallet  and make transfers                 |       1 week                     | -->

### 4. How will you determine if your documentation is successfully supporting your intended audience? 
Answer : I would share the documentation in the Filecoin slack channels with Developers who are having challenges and from the feedback i get , I can use that to determine if the documentation was successful

### 5. Will this work be published under the dual MIT and APACHE2 licenses?
Answer: Yes

### 6. Does your proposal comply with our Community Code of Conduct? 
Answer: Yes

### Additional questions: 
For each team member(s), please list name, email, Github account, and role in the project.
How did you learn about this program?

**Comment by ErinOCon** [comment]
Hi @1Busayo Thank you for your time with this proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.

Wishing you the best as you continue building!
