### ISSUE TITLE
Blade Labs

### ISSUE THREAD

**Issue by Ruchi20th** [filecoin-project/devgrants#1794]
# Open Grant Proposal: `**Blade Labs**

**Project Name:** **Blade Labs**

**Proposal Category:** Choose one of `Developer and data tooling`, `**Integrations**`, `Research & protocols`, `Storage`, `Retrieval`, `FVM`, or `Other`. Learn what these categories are [here](https://github.com/filecoin-project/devgrants/blob/master/Program%20Resources/Open%20Grants%20README.md). 

**Integration**

**Individual or Entity Name:** Is the proposal on behalf of an individual, or an entity/organization? Please note that the agreement and any payments must be completed by the same entity, either individual or organization.

**Blade Labs Inc - Organization**

**Proposer:** `**Ruchi**`

**Project Repo(s)** **(https://github.com/Blade-Labs**). 

**(Optional) Filecoin ecosystem affiliations:** `Please disclose any existing work relationships with organizations in the Protocol Labs Network, including Protocol Labs, Filecoin Foundation, Filecoin Foundation for the Decentralized Web, and any others.` 

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Please respond with "Yes" or "No".

**Yes, for new work and tools created specifically for the project, or any addition to our already open-sourced Blade SDK, but we cannot open source anything we add to/integrate with Blade Wallet.**

# Project Summary

**Blade Labs is pioneering embedded fintech solutions to accelerate financial innovation and enhance global financial inclusion through tokenization. Our business operates in two main verticals:

Digital Wallet Services: Provides wallet infrastructure for enterprises that want to engage with digital assets for community engagement and building. Customers include retail brands such as LG, Karate Combat.
Digital Asset Services: Offers compliant, DLT-based, multi-jurisdictional platforms as embedded fintech products for institutional investors and issuers of regulated digital assets. Customers include globally recognised financial institutions.

A key feature of our Digital Asset Services is the development of Shariah-compliant versions of our products, including a private financing platform and a regulated digital assets platform. This addresses a growing need in Islamic finance markets for innovative, compliant digital asset solutions.
Our proposed integration with Filecoin will focus on enhancing our Digital Wallet Services. Specifically to integrate Filecoin as NFT storage within Blade Console for NFT drop campaigns, secondly to integrate Filecoin as NFT storage for NFT minting using Blade SDK and thirdly to expand our WhiteLabel wallet offering with option to use Filecoin as decentralized storage for the wallet.**

## Impact 

**The proposed integration of Filecoin as NFT storage for Hedera NFT drop campaigns in Blade Console, the Blade SDK, and the WhiteLabel wallet offering is an impactful project for the Filecoin and related ecosystems. The benefits of correctly implementing this proposal extend far beyond mere storage solutions. Users will experience improved trust and transparency, knowing their NFTs and/or data are securely stored in a decentralized manner, which aligns with the broader goals of the blockchain space. Additionally, by enhancing their service offerings with Filecoin, Blade Labs can attract more users seeking reliable and decentralized solutions, thus broadening the market reach and user base for Filecoin , potentially reaching millions of users through our enterprise clients.**

## Outcomes

**Our integration with Filecoin will result in an enhanced Blade Wallet Services offering with the following key features:

- Integrate Filecoin as NFT storage for NFT drop campaigns within Blade Console
- Integrate Filecoin as default option for NFT storage while NFT minting using Blade SDK
- Expand Blade WhiteLabel Wallet with option to use Filecoin as decentralized storage for the Enterprise-grade wallet offering

Key metrics for measuring success:

- Successful integration of Filecoin support within Blade Console, Blade SDK & Blade Whitelabel Wallet
- Number of user accounts utilizing Filecoin storage
- Increased enterprise client interest due to enhanced security features**

## Adoption, Reach, and Growth Strategies

**Our target audience for this integration includes:
- Enterprise clients seeking blockchain-based community engagement tools
- End-users of our enterprise clients' applications
- Developers building on our wallet infrastructure

Current engagement: We have established relationships with 30+ enterprise clients, including major players like LG Electronics, Karate Combat, and Slime World, and have created over 2.8 million user accounts.

Growth strategies:
- Enterprise Partnerships: Leverage existing relationships to showcase Filecoin integration benefits.
- Co-marketing: Collaborate with Filecoin team to reach potential enterprise clients.**

## Development Roadmap

**Milestone 1: Initial Integration (2 months)

Integration of Filecoin support and enhanced UI for Filecoin promotion within Blade Console & Blade SDKs
Implementation of data storage and retrieval functions using IPFS
Team: 1 developers, 1 QA
Funding: $20,000

Milestone 2: Wallet Integration (2 months)

Implementation of Filecoin’s decentralized storage option to Blade Whitelabel wallet offering
Implementation of advanced security features of storing wallet secret phrase leveraging Filecoin
Team: 1 developer, 1 QA
Funding: $20,000

Milestone 3: Enterprise Client Onboarding (1.5 months)

Collaboration with Filecoin team for business development
Onboarding of the first enterprise client using Filecoin-integrated Blade Wallet
Team: 1 Business Development specialist
Funding: $10,000

Total Project Duration: 4.5 months
Total Funding Required: $50,000
Milestone 1 and Milestone 2 will get worked on by 2 separate teams in parallel.**

## Total Budget Requested

| Milestone # | Description | Deliverables | Completion Date | Funding |
|===|===|===|===|===|

**We request a total budget of $50,000 for our integration with Filecoin, spread across three milestones over a 4.5-month period.**

## Maintenance and Upgrade Plans

**Our long-term plans include:

- Regular security audits and updates of the Filecoin integration
- Performance optimization based on usage data and client feedback
- Exploration of additional Filecoin features for potential integration
- Ongoing collaboration with Filecoin team for business development
- Active participation in the Filecoin and IPFS ecosystems**

# Team

## Team Members

**Sami Mian**
**Ints Haquani** 
**Valera Olexienko**
**https://www.linkedin.com/in/samimian/**
**https://www.linkedin.com/in/ints-haquani/**
**https://www.linkedin.com/in/valera-oleksiienko/**
**https://bladelabs.io/**

## Relevant Experience

**Blade Labs brings together a team of seasoned professionals with extensive experience in finance, technology, and blockchain, uniquely positioning us to build and scale our Digital Asset Platform integrated with Filecoin.
Sami Mian, our CEO, brings over 20 years of experience in financial services, having held leadership roles at global institutions like Citigroup and Deutsche Bank. As the former Head of APAC for Hedera, Sami successfully onboarded major enterprises like LG Electronics and Nomura to the web3 space, demonstrating his ability to bridge traditional finance with blockchain technology.

Our COO, Ints Haquani, contributes 20 years of expertise in brand development and go-to-market strategies. His experience in shaping brands across various industries and forging strategic alliances with luxury brands like Roberto Cavalli and LVMH is invaluable for our expansion and partnership strategies.

Valera Olexienko, our CTO, is a veteran IT executive with a proven track record of delivering enterprise-level products. His experience in forming tech partnerships with global enterprises, including Netflix, ensures our platform meets the highest standards of scalability and performance.

Our team's combined experience is evidenced by our track record:

- We've successfully developed and deployed wallet infrastructure serving over 2.4 million user accounts.
- We've established partnerships with over 30 enterprise clients, including major players like LG Electronics and Diamond Standard.
- We've achieved significant certifications (SOC2, ISO27001:2022) demonstrating our commitment to security and compliance.
- We've successfully implemented our solutions across multiple blockchain networks, showcasing our adaptability and cross-chain expertise.

Our team's diverse background spanning traditional finance, blockchain technology, and enterprise software development makes us uniquely qualified to build this Filecoin-integrated Digital Asset Platform. We understand the nuances of both the traditional financial sector and the emerging blockchain landscape, allowing us to create solutions that truly bridge these worlds.

Moreover, our experience in navigating regulatory complexities and our focus on compliance and security align perfectly with the needs of enterprise clients and the stringent requirements of the financial services industry.
By combining our deep industry knowledge, technical expertise, and proven track record of delivering enterprise-grade blockchain solutions, Blade Labs is ideally positioned to execute this project successfully, driving innovation and adoption in the digital asset space.**

## Team code repositories

**Here are the key code repositories for Blade Labs:

1. Main GitHub Repository:[ https://github.com/Blade-Labs](https://github.com/Blade-Labs)

This repository contains open-source components of our SDK and wallet infrastructure, demonstrating our commitment to transparency and community contribution. It showcases our team's ability to develop robust, scalable blockchain solutions.

2. Blade Wallet Repositories:

While specific repository links are not provided in the original documents, our wallet solutions are available on multiple platforms, indicating our capability to develop cross-platform blockchain applications:

- Android:[ https://play.google.com/store/apps/details?id=org.bladelabs.wallet](https://play.google.com/store/apps/details?id=org.bladelabs.wallet)
- iOS:[ https://apps.apple.com/app/apple-store/id1623849951](https://apps.apple.com/app/apple-store/id1623849951)
- Chrome Extension:[ https://chrome.google.com/webstore/detail/blade-new-hedera-wallet/abogmiocnneedmmepnohnhlijcjpcifd](https://chrome.google.com/webstore/detail/blade-new-hedera-wallet/abogmiocnneedmmepnohnhlijcjpcifd)

3. Technical Documentation:[ https://docs.bladelabs.io/](https://docs.bladelabs.io/)

While not a code repository per se, this documentation outlines our API structure, SDK usage, and integration guidelines. It reflects our team's ability to create comprehensive, developer-friendly solutions and maintain clear technical documentation.
It's important to note that as a company dealing with sensitive financial infrastructure, some of our core repositories are likely private for security reasons. The public repositories and documentation we've shared demonstrate our team's technical capabilities and our commitment to open-source contributions where appropriate.**

# Additional Information

**We learned about the Open Grants Program through research in the Web3 industry. The best email for discussing the grant agreement is ruchi@bladelabs.io.
Additional points:

1. Strategic investment from Hashgraph Association, demonstrating our credibility in the blockchain space
2. Proactive regulatory approach across multiple jurisdictions, ensuring compliance in our Digital Asset Services
3. Cross-chain experience with multiple blockchain ecosystems, facilitating potential future integrations
4. Significant market traction with 2.4 million user accounts through our enterprise clients
5. Focus on Shariah-compliant digital asset solutions in our Digital Asset Services vertical
6. Strong security certifications (SOC2, ISO27001:2022) applicable to all our products
7. Commitment to community engagement and open-source contributions where possible
8. Long-term vision for potential advanced features leveraging Filecoin's capabilities across both our verticals

We believe our focused approach to integrating Filecoin with our Digital Wallet Services, combined with our established enterprise relationships, can significantly benefit both Blade Labs and the Filecoin ecosystem. This integration serves as a starting point for potential future collaborations across our Digital Asset Services vertical as well.**

**Comment by ErinOCon** [comment]
Hi @Ruchi20th,  I hope you are doing well! Your project is currently shortlisted as a review candidate. If we have any questions, we will contact you on this thread. 

If you have any questions on your end, please feel welcome to be in touch at [grants@fil.org](mailto:grants@fil.org). We would be happy to connect.
