### ISSUE TITLE
LOCKB0X: Chain-Agnostic File Encryption-to-Permanent Storage via Filecoin

### ISSUE THREAD

**Issue by inkedinlove** [filecoin-project/devgrants#1800]
# Open Grant Proposal: `LOCKB0X: Chain-Agnostic File Encryption, Viewing, and Permanent Storage`

**Project Name:** LOCKB0X  
**Proposal Category:** Storage  
**Entity Name:** Individual

**Proposer:**  
- Josh Kassabian  
  [GitHub: inkedinlove](https://github.com/inkedinlove)

**Project Repo(s):**  
- [GitHub Repo](https://github.com/inkedinlove/filecoinintegration)

**(Optional) Filecoin ecosystem affiliations:** None  
**(Optional) Technical Sponsor:** N/A  
**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Yes (viewer Dapp component only)

## Project Summary

LOCKB0X provides a chain-agnostic solution for creating, encrypting, storing, managing, grouping, and viewing various file formats, prioritizing privacy, permanence, and user control. Users can securely encrypt files via private keys or wallet integration (Trust Wallet, MetaMask), ensuring a seamless user experience.

Our open-source viewer Dapp will be hosted on many decentralized storage platforms, enabling users to decrypt and view files independently, ensuring data permanence and accessibility without reliance on centralized services. We support encryption on 20+ file formats, including 3D assets such as GLB, GLTF, OBJ, and FBX, to meet the needs of creators and professionals.

Integration with Filecoin enhances the resilience and permanence of encrypted files, expanding decentralized storage options beyond IPFS.

## Impact

LOCKB0X addresses the growing demand for self-sovereign, decentralized storage solutions that emphasize privacy, accessibility, and user control. The project provides a comprehensive encryption-to-permanent-storage solution and a decentralized viewing tool, empowering users to manage encrypted data independently.

By integrating Filecoin, we enhance file redundancy and long-term storage capabilities, fostering data resilience. Our open-source viewer Dapp enables users to access their files securely without relying on our platform, ensuring system resilience against downtimes or breaches.

## Outcomes

- Application for encryption, storage, management, and viewing of files via Filecoin and IPFS.
- Open-source viewer Dapp for decrypting and viewing files independently.
- Support for a wide range of file formats, including text, images, and 3D assets.
- Wallet integrations (Trust Wallet, MetaMask) for seamless encryption and decryption.

### Success Metrics:
- Number of files encrypted, stored, and accessed through decentralized storage.
- Adoption and usage of the open-source viewer Dapp.
- User feedback on file rendering and encryption/decryption processes.

## Adoption, Reach, and Growth Strategies

Target users include privacy-conscious individuals, professionals, creators, and systems handling sensitive data, and seeking permanently accessible storage. By integrating popular wallets (Trust Wallet, MetaMask), we lower the barrier for users familiar with Web3. 

The open-source viewer Dapp will encourage adoption within the decentralized storage and privacy communities. API integrations are being developed for easy implementation into existing projects and systems, increasing LOCKB0X’s reach.

### Milestone 1: Filecoin Integration (Month 1 - Oct.1-31)
- **Deliverables:**
  - Full Filecoin integration for uploading and retrieving encrypted files.
  - Testing across 20 file formats to ensure data integrity and accessibility.
- **Team:** 2 developers (back-end, front-end).
- **Funding:** $15,000

### Milestone 2: Wallet Integrations (Month 2 - Nov.1-30)
- **Deliverables:**
  - Trust Wallet and MetaMask integration for encryption and decryption.
  - Secure user flow for encryption via wallet signature.
- **Team:** 2 developers.
- **Funding:** $15,000

### Milestone 3: Open-source Viewer Dapp & Update Documentation (Month 3 - Dec.1-31)
- **Deliverables:**
  - Launch open-source viewer Dapp hosted on decentralized storage.
  - 3D asset file rendering support.
  - Publish public repository, Dapp addresses, and documentation.
- **Team:** 2 developers, 3 project testers.
- **Funding:** $20,000

## Total Budget Requested

The total budget is $50,000 for development, integration, and documentation.

| Milestone | Description                          | Completion Date | Funding  |
|-----------|--------------------------------------|-----------------|----------|
| 1         | Filecoin Integration                 | Month 1 - Oct.1-31         | $15,000  |
| 2         | Wallet Integrations                  | Month 2 - Nov.1-30         | $15,000  |
| 3         | Viewer Dapp & Updated Docs           | Month 3 - Dec.1-31         | $20,000  |
| **Total** |                                      |                 | **$50,000** |

## Maintenance and Upgrade Plans

We will continue to maintain the platform, focusing on upgrading encryption methods, supporting additional file types, releasing API access, and optimizing for large-file rendering via decentralized rendering networks. LOCKB0X LLC will maintain the open-source viewer Dapp with community contributions, ensuring longevity.

### Josh Kassabian  
**Co-Founder of Pakana | Creative Technologist | Full-Stack Engineer & Blockchain Integration Architect**  
With a strong background in computer science and a passion for research and development in emerging technologies, I’ve transitioned from a general product, hardware, and network engineer to deep blockchain exploration. As the owner of an ASIC mining operation, I developed a fascination with blockchain's potential in real-world applications.

In the past five years, I have focused on blockchain product design and development, working on financial technology products, decentralized systems, and interactive design. I actively engage with the blockchain community through events, forums, and social media, discussing solutions related to blockchain protocols, wallet security, and more.

**LinkedIn:** [Josh Kassabian](https://linkedin.com/in/joshuakassabian)

### Steven Tomlinson  
**Founder of Pakana | Expert Full-Stack Engineer & Solution Architect**  
Steven has over 20 years of experience delivering enterprise software and integration solutions. He began coding in the 1970s and has been involved in blockchain since 2010. His work spans industries such as finance, government, hospitality, and more.

Steven’s latest project, Pakana, focuses on improving trust in work engagements through blockchain. He has also developed Web2 applications and is experienced in EVM smart contracts, DeFi protocols, and NFT metaverse integrations.

**LinkedIn:** [Steven Tomlinson](https://linkedin.com/in/pakana)

## Relevant Experience

Josh and Steven have been business partners for over two years, providing technology consulting services and developing decentralized solutions. They have successfully delivered projects funded by Stellar Blockchain and the Avalanche-based Lamina1 project.

Our team has expertise in encryption, decentralized networks, blockchain integration, and database development, positioning us to create secure, user-controlled storage solutions.  

## Team Code Repositories

Our current open-source libraries and documentation can be found at:  
[Pakana Components](http://Pakanacomponents.com)

- GitHub Repo: [Pakana-Stellar-Razor-Components](https://github.com/lockb0x-llc/Pakana-Stellar-Razor-Components)

## Additional Information

We just concluded our first 4 weeks of live beta testing on the core functionality of Lockb0x and are making noncritical adjustments according to testers' feedback. 

LOCKB0X aligns with Filecoin’s goal of ensuring decentralized, long-term data resilience and empowering users with self-sovereign data control.

- [LOCKB0X Website](https://www.lockb0x.io)

Best contact email: `josh@thefirm.codes`

---

**Comment by ErinOCon** [comment]
Hi @inkedinlove, thank you for your proposal! Can you provide more detail on your success metrics? For example, do you have projections for the number of files encrypted, users onboarded, etc. Do you have a marketing plan in place to meet these number goals?

Also, could you provide a brief description on how you will use Filecoin specifically (as opposed to IPFS)?

**Comment by inkedinlove** [comment]
Absolutely, @ErinOCon, and thank you for your time. I’ve addressed each of your questions below. Please feel free to reach out with any further queries.

Success Metrics:
LOCKB0X is gaining traction across various sectors. We project onboarding 500 users in the first quarter, scaling to 5,000 users by the end of 2025, with 10,000 encrypted files within the first three months, and growing to 100,000 files by the end of the first year. Our integration at the L1 level with a top 10 blockchain and involvement in a $5 billion construction project over the next 8 years provide a strong foundation for achieving these targets, though legal constraints prevent us from naming the entity at this time.

Additionally, LOCKB0X has gained interest from a decentralized GPU rendering network that collaborates with industry leaders such as Disney and Unity. This partnership will empower 3D animated scene and character model artists to securely encrypt their creations and protect intellectual property throughout the creative and rendering process, driving further adoption among artists and studios.

Marketing Plan:

	1.	Developer Outreach: We will engage developers through targeted events such as hackathons, conferences, and partnerships with blockchain ecosystems by offering a developer API.
	2.	Platform Partnerships: Our ongoing discussions with a top 10 blockchain, along with our established presence in decentralized communities (e.g., Stellar, Avalanche), will fuel visibility and user onboarding.
	3.	Industry-Specific Use Cases: LOCKB0X’s collaboration with the decentralized GPU rendering network will attract 3D artists working with partners like Disney and Unity, offering a competitive advantage in protecting artistic intellectual property.

Filecoin vs. IPFS:
LOCKB0X utilizes IPFS for decentralized file distribution, but IPFS alone does not guarantee long-term file persistence. If we were to shut down our node or stop pinning files, the data could be garbage collected and lost. This is where Filecoin comes in: it provides a decentralized, incentivized storage layer that ensures files remain intact and retrievable over time, regardless of whether our platform or nodes continue to operate. By relying on Filecoin, users are not dependent on LOCKB0X or any single entity to maintain their files, thus decentralizing control and ensuring long-term, immutable storage for critical assets, such as construction documents or 3D animations created for major projects.

**Comment by ErinOCon** [comment]
Thank you for the quick reply @inkedinlove! We will be in touch with any additional questions.

**Comment by ErinOCon** [comment]
Thanks, @inkedinlove! It looks like the free trial option is quite available yet. Is there way we can demo the product in the meantime?

**Comment by inkedinlove** [comment]
Thank you for your response, @ErinOCon!

You’re correct—the free trial option is in the process of being added, and during this time, the platform has been temporarily locked down. In the meantime, I’ve attached a video walkthrough to give you a detailed look at how the application works.

If you’d prefer, we can also set up a live demo. Feel free to email me your availability at josh@thefirm.codes, and I’d be happy to walk through the product with you.

Walkthrough Video: https://drive.google.com/file/d/11LLQxuFW7IN88OEatx6H6TtyjI6NA9uU/view?usp=drivesdk

**Comment by ErinOCon** [comment]
Hi @inkedinlove, thank you for the provided background. I've followed up with an email to schedule a time for the demo.

**Comment by ErinOCon** [comment]
Hi @inkedinlove, thank you again for your proposal and for your time connecting with our team. Unfortunately, we will not be moving forward with a grant at this time. To contact our team with questions or to discuss other ways to connect in our ecosystem, please send an email to grants@fil.org. 

Wishing you the best as you continue building!
