### ISSUE TITLE
Filecoin Pulse TG Bot

### ISSUE THREAD

**Issue by OpenGateLabs** [filecoin-project/devgrants#1806]
# Open Grant Proposal: Filecoin Pulse Telegram Bot

**Project Name:**
Filecoin Pulse

**Proposal Category:** 
Other

**Individual or Entity Name:
OpenGate Tech

**Proposer:** `
OpenGate Labs

**Project Repo(s)** Please list Github repos used for this project work. 
https://github.com/OpenGateLabs?tab=repositories

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Please respond with "Yes" 

# Project Summary
The community building for Filecoin is currently very weak. As a leading project in the Depin space, the current user base of Filecoin's community is far from meeting the standards of a leading project. We must strengthen community building. Specifically, driving traffic from Telegram is a practical and effective approach, as Telegram has 1 billion active users globally, and almost every Web3 project has a Telegram community.

Filecoin Pulse is dedicated to cultivating Filecoin activists, enhancing awareness of the Filecoin ecosystem, and decentralizing community assets. Participants can engage in a lottery within the BOT to earn generous token rewards. The project integrates ecological research, resource consolidation, information updates, and user education through a Telegram lottery bot. Users can complete tasks to earn coins, which they can then use to participate in spin-the-wheel lotteries for token rewards. Tasks primarily involve watching educational videos, sharing Filecoin-related information, and following relevant social media accounts.
![231](https://github.com/user-attachments/assets/1a44e3c9-f265-4541-a1b2-8547658e9b70)

## Impact 

**What pain points does this project seek to address?**

Lack of Awareness: Many potential users and stakeholders are unfamiliar with the Filecoin ecosystem and its benefits. FilPulse aims to bridge this knowledge gap by providing educational resources and engaging content.

Community Fragmentation: The Filecoin community can be disjointed, with various groups operating in silos. By fostering a centralized hub for information and interaction, FilPulse seeks to unite these communities around shared goals.

Low Engagement Levels: Current user engagement in the Filecoin ecosystem may be low due to a lack of incentives or understanding of how to participate meaningfully. The project addresses this by gamifying engagement through tasks and rewards.

**Benefits:**

Enhanced Adoption: Successfully raising awareness and engaging users can lead to increased adoption of Filecoin, expanding its user base and network effects.

Stronger Community: Building a cohesive community can foster collaboration, innovation, and support among users, leading to a more robust ecosystem.

Sustainable Growth: Educated users who understand the ecosystem can contribute to its long-term sustainability and evolution.
Risks of Not Getting It Right

Risks of Not Getting It Right:

Continued Low Engagement: Failure to effectively educate and incentivize users may result in ongoing low engagement and missed opportunities for growth.

## Outcomes

Final Outcomes & Deliverables

Educational Content Library:

A comprehensive collection of videos, articles, and tutorials focused on the Filecoin ecosystem, covering topics such as blockchain fundamentals, Filecoin's architecture, and its use cases.
Interactive quizzes and assessments to reinforce learning and track user progress.

**Telegram Lottery Bot:**

A fully functional Telegram bot that allows users to participate in lotteries after completing tasks.
The bot will feature:
Task Management: Users can view and complete tasks to earn coins.
Spin-the-Wheel Functionality: Users can spin the wheel using earned coins to win token rewards.
User Profiles: A system for tracking user progress, task completion, and earned rewards.
Real-Time Notifications: Updates on lottery results and new tasks via Telegram alerts.

Community Engagement Platform:

A platform (or integrated section within the bot) for users to discuss and share insights about Filecoin.
Features for user-generated content, such as forums or discussion boards, to promote interaction and knowledge sharing.

Analytics Dashboard:

A backend dashboard for monitoring user engagement, task completion rates, and overall participation metrics.
Tools for tracking the effectiveness of educational content and community interactions.

Partnerships and Collaborations:

Establish partnerships with other Filecoin projects, influencers, and educational platforms to enhance content delivery and reach.

**To measure the success of FilPulse, the team will implement several metrics across different areas:**

Active Users: Track the number of unique users engaging with the Telegram bot and completing tasks on a daily and weekly basis.
Task Completion Rate: Measure the percentage of tasks completed by users to assess engagement levels and content effectiveness.

Social Media Followers: Track the growth of followers on Filecoin-related social media accounts as a measure of outreach success.
Discussion Participation: Measure the volume of discussions and user-generated content in the community engagement platform.
Lottery Participation:

Lottery Participation Rates: Monitor how many users engage with the lottery feature, including spins and rewards claimed.
Token Distribution: Track the number of tokens distributed through the lottery and their subsequent use within the Filecoin ecosystem.

## Adoption, Reach, and Growth Strategies

Target Audience

Crypto Enthusiasts and Investors:
Individuals interested in blockchain technology and cryptocurrencies, particularly those who are exploring new projects like Filecoin.

Developers and Tech Innovators:
Software developers and tech entrepreneurs looking for decentralized storage solutions and blockchain-based applications.
Academics and Students:

Students and researchers in computer science and finance who are eager to learn about emerging technologies and their practical applications.

Filecoin Community Members:
Existing Filecoin users who are looking for ways to engage more deeply with the ecosystem and contribute to its growth.
Audience Size and Engagement

**Growth Strategies**:

We are establishing a reward mechanism to attract users to complete tasks related to the Filecoin ecosystem. Through this TON bot, users can easily participate in various interactive activities, completing specified tasks to earn rewards. We will regularly update information and video content related to the Filecoin ecosystem and technology, guiding users to watch the videos to earn coins. Users can use these coins to participate in lotteries for a chance to win Filecoin tokens and other rewards. This approach will help more users understand the Filecoin project and hold $FIL tokens, bringing new traffic to the Filecoin ecosystem.

Using Telegram's mature social ecosystem, we will execute viral activities through mini-programs. With 1 billion active users globally, Telegram hosts communities for nearly all Web3 projects, making it a significant traffic entry point. We will encourage users to invite more new members into the community, with both the inviter and the invitee receiving coin rewards for participation in lottery activities.

## Development Roadmap

Milestone 1: Development of the Telegram Bot
Expected Functionality:

A functional Telegram bot that allows users to:
Complete tasks and earn coins.
Spin the wheel to win rewards.
View their profiles, including task completion and rewards earned.
Team Composition:

Backend Developer (2): Building the bot's server-side functionalities and integrations.
Frontend Developer (1): Designing the user interface and ensuring a smooth user experience.
Quality Assurance Tester (1): Testing the bot for functionality and user experience.
Funding Required:

Total: $18,000
Backend Developers: $1,000
Frontend Developer: $8,000

Timeframe:

Start Date: October 1, 2024
End Date: October 31, 2024 (1 month)

Milestone 2: Content Creation and Community Engagement Platform
Expected Functionality:

A platform for sharing educational content, including videos and articles about Filecoin.
Integration of community engagement features, such as discussion forums and user-generated content.
Team Composition:

Content Manager (1): Curating and managing educational content.
Community Manager (1): Engaging with users and moderating discussions.
Full Stack Developer (2): Building the community engagement platform and ensuring seamless integration with the Telegram bot.
Funding Required:

Total: $14,000
Content Manager: $8,000
Community Manager: $6,000
Timeframe:

Start Date: October 15, 2024
End Date: November 31, 2024 (1.5 months)

Milestone 3: Marketing and User Acquisition
Expected Functionality:

Implementation of marketing campaigns to attract new users and engage existing ones.
Launch of referral programs and social media challenges to drive growth.
Team Composition:

Marketing Specialist (1): Planning and executing marketing strategies.
Social Media Manager (1): Managing social media accounts and engagement.
Data Analyst (1): Monitoring campaign performance and user metrics.
Funding Required:

Total: $20,000
Marketing Specialist: $8,000
Social Media Manager: $6,000
Data Analyst: $6,000
Timeframe:

Start Date: November 1, 2024
End Date: December 31, 2024 (2 month)

## Total Budget Requested
$62,000

![230](https://github.com/user-attachments/assets/bad8ab6d-4628-4a17-9d59-ca5b1e9174fe)

## Maintenance and Upgrade Plans

**Long-Term Maintenance Strategies**
Regular Updates and Bug Fixes:

Establish a dedicated support team to monitor the platform continuously, addressing bugs and user feedback promptly.
Implement a schedule for regular updates to the Telegram bot and community platform, ensuring that all features remain functional and user-friendly.
User Feedback Mechanism:

Create an integrated feedback system within the Telegram bot and community platform where users can easily report issues and suggest improvements.
Conduct quarterly surveys to gather insights on user satisfaction and desired features, allowing the team to prioritize enhancements.
Community Management:

Assign a Community Manager responsible for fostering engagement and addressing user concerns, ensuring that the community remains active and vibrant.
Organize regular community events, such as Q&A sessions and feedback forums, to maintain open lines of communication between users and the development team.

**Timeline for Future Enhancements**
Short-Term (0-6 Months):

Focus on initial bug fixes and gathering user feedback post-launch.
Implement minor feature enhancements based on early user suggestions.
Medium-Term (6-12 Months):

Introduce significant feature expansions and educational content updates.
Begin organizing community events and enhancing user engagement strategies.

# Team

## Team Members
(https://sites.google.com/view/opengatelab/opengatelab))

## Team Website

(https://sites.google.com/view/opengatelab/opengatelab))

## Relevant Experience

Diverse Expertise: Our team's collective experience spans multiple fields, including project management, development, design, content creation, and community engagement. This diversity enables us to effectively address the multifaceted challenges of the FilPulse project.

Experience in the Filecoin Ecosystem: Team members have successfully developed multiple projects within the Filecoin ecosystem and have been involved in it from an early stage. We possess a deep understanding of Filecoin and have engaged with the majority of projects and communities within the ecosystem. Our prior experience provides us with valuable insights and best practices that we will apply to FilPulse.

Experience in Telegram Ecosystem Development: We have previously developed and launched a Telegram mini-game, collaborating with various projects in the TG ecosystem. This experience can provide resource entry points to drive traffic for the FilPulse project.

## Team code repositories

https://github.com/Filscriptions1/Filscriptions
https://github.com/OpenGateLab/FNS

# Additional Information

Filecoin Twitter

contact@opengatenft.com

**Comment by ErinOCon** [comment]
Hi @OpenGateLabs, thank you for your proposal and for your interest in our grants program. Unfortunately, we will not be proceeding with a grant for this project. If you have any questions for our team, please contact grants@fil.org. We would be happy to connect.
