### ISSUE TITLE
FusionX: A Digital Reflection of the Global Economy

### ISSUE THREAD

**Issue by InvluencerMikeDoyle** [filecoin-project/devgrants#1814]
# Open Grant Proposal: FusionX Decentralized Storage Integration

**Project Name:**
FusionX by Invluencer Ltd

**Proposal Category:**
Integrations 

**Individual or Entity Name:** 
Invluencer Ltd

**Proposer:** 
InvluencerMikeDoyle

**Project Repo(s)** Please list Github repos used for this project work. 
Not Applicable

**(Optional) Filecoin ecosystem affiliations:** 
i3D Protocol, Keyko.io

**(Optional) Technical Sponsor:** 
Not Applicable

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** 
Yes

**Project Summary**
Based on the success of the i3D Protocol which analyses and ranks the potential for success of Startups, we are building FusionX, a blockchain-based ecosystem that tracks the value of multiple global economic sectors—such as stocks, commodities, cryptocurrencies, and unlisted companies—through a decentralized oracle system. Users can 'invest' in a Portfolio $FXT Token or 4 underlying tokens that track key sectors. Our project will leverage Chainlink's oracle technology to integrate real-time, high-quality data feeds that reflect sector values, enabling our platform to provide an accurate and transparent representation of the world's economic state.

The FusionX Decentralized Storage Integration project aims to leverage Filecoin's decentralized storage solutions to support data transparency, security, and scalability within the FusionX ecosystem. FusionX is a blockchain-based platform that reflects via Data API’s, the value of global economic sectors through tokenized representations of stocks, commodities, cryptocurrencies, and unlisted companies. By integrating Filecoin, FusionX will securely store historical data, sector reports, and governance-related documents, ensuring that the data is tamper-proof and easily accessible to the community.

This project will implement a solution that allows FusionX to utilize Filecoin's decentralized storage for backing up oracle data, storing archival records, and hosting DAO-related content. The integration will also enable FusionX to provide a reliable backup for price feeds and data tracking, increasing the ecosystem's resilience.

## Impact 
The integration with Filecoin addresses the critical need for decentralized, secure data storage within the FusionX ecosystem. Currently, data storage in traditional finance is heavily centralized, leaving it vulnerable to manipulation, tampering, and single points of failure. By adopting Filecoin's decentralized model, FusionX will enhance data transparency and reliability, providing an auditable, long-term data storage solution.

The successful implementation of this integration will also serve as a model for other DeFi and blockchain projects seeking to utilize decentralized storage for secure data management. The integration will ensure that FusionX's data infrastructure scales along with the growth of the platform, offering continuous access to historical records and sector-based data without relying on centralized servers.

## Outcomes
The project will deliver the following outcomes, each focused on integrating Filecoin's decentralized storage capabilities to enhance the FusionX platform's data management, security, and accessibility:

1. Filecoin-Based Decentralized Storage Integration
- Implement a decentralized storage solution using Filecoin for storing historical data, price feeds, and governance documents related to the FusionX ecosystem.
- This integration ensures that data stored within the platform is tamper-proof, decentralized, and accessible to all stakeholders.

2. Secure and Redundant Data Backups
- Establish secure, tamper-proof backups for oracle data, archival records, and other critical information to safeguard against data loss or manipulation.
- The solution will provide redundancy for important datasets, ensuring that historical records and sector performance data remain available for auditing and analysis.

3. User Interface Enhancements for Accessing Decentralized Storage
- Develop user interface components within the FusionX platform that enable users to directly access and interact with data stored on Filecoin.
- The interface will provide features for browsing historical data, downloading archived information, and viewing governance-related documents, allowing for greater data transparency and community engagement.

4. Automated Data Archiving and Backup Processes
- Implement automated data archiving processes that leverage Filecoin's storage capabilities to perform ongoing backups of critical datasets, such as sector performance reports, transaction records, and oracle data outputs.
- The automation will ensure that the most recent data is consistently and reliably stored on Filecoin, maintaining a real-time backup cycle for continuous data protection.

**Functional Specifications**

- Integration with Filecoin's decentralized storage network to allow data uploads, retrievals, and management directly from the FusionX platform.
- Development of API endpoints and smart contracts for automated data transfers between FusionX and Filecoin.
- User interface components within the FusionX DApp for accessing and managing stored data.
- Automated scripts and processes for regular data backups, ensuring that all essential records are stored on Filecoin in real-time or at predefined intervals.

Software Functionality Upon Completion

- The final software will deliver a seamlessly integrated decentralized storage solution, allowing for secure and transparent data management.
- Users will be able to access stored data directly from the FusionX platform, ensuring data availability and auditability.
- Automated data archiving will keep essential datasets up-to-date, providing long-term resilience for the FusionX ecosystem's data infrastructure.

These deliverables will significantly enhance the security, reliability, and transparency of data within the FusionX platform, setting a foundation for sustainable growth and community trust in the ecosystem.

**Metrics for Success**
•	Successful integration of Filecoin's storage network into the FusionX platform.
•	At least 10 key data sets (e.g., price feeds, historical market data, governance proposals) securely stored on Filecoin.
•	Improved data transparency, measured through community access and audits of decentralized storage records.

## Adoption, Reach, and Growth Strategies

- The target audience for this integration includes the FusionX community, DeFi developers, and blockchain enthusiasts who prioritize data transparency and security. FusionX will onboard users by conducting community outreach, including webinars, educational content, and social media campaigns to explain the benefits of decentralized storage.
- To engage the first 100 users, FusionX will host a data integrity challenge where users can audit data sets stored on Filecoin, with incentives offered for participation. As more data sets are stored, FusionX will increase user engagement by developing DApp features that allow users to directly interact with the stored data.
- FusionX will leverage its existing network within the i3D Protocol and Partner ecosystems to adopt the FusionX Tokens

## Development Roadmap
**Milestone 1A: Initial Integration**
•	Functionality: Complete the FusionX platform wireframes and DApp MVP test pilot for data compilation and connection to the Filecoin network.
•	Team Roles: 2 developer (1 backend, 1 frontend).
•	Funding: $4,000
•	Timeframe: 2 weeks
**Milestone 1B: Connect Chainlink Oracles to Economic Data API’s**
•	Functionality: Implement data oracles for data draw down and archiving.
•	Team Roles: 2 developers (1 backend, 1 automation engineer).
•	Funding: $4,000
•	Timeframe: 1 month
**Milestone 2: Automated Data Storage and Backups**
•	Functionality: Implement design and automation of scripts for data formulation, backups and archiving.
•	Team Roles: 2 developers (1 backend, 1 automation engineer).
•	Funding: $5,000
•	Timeframe: 2 months
**Milestone 3: User Interface Enhancements**
•	Functionality: Create a DApp interface for accessing Filecoin-stored data.
•	Team Roles: 1 Developer (1 frontend, UX/UI designer).
•	Funding: $2.500
•	Timeframe: 1 month
**Milestone 4: Community Outreach and Documentation**
•	Functionality: Conduct educational workshops, produce documentation, and promote the benefits of decentralized storage.
•	Team Roles: 1 community manager, 1 content creator.
•	Funding: $3,000
•	Timeframe: 1 month

## Total Budget Requested: $18,500

| Milestone # | Description | Deliverables | Completion Date | Funding |
|1A | Initial Integration |Connection to Filecoin and test data storage| 1 month | $4,000 |
|1B | Connect Chainlink Oracles to Economic Data API’s | Implemented data oracles  | 1 Month |$ 4,000 |
|2 | Implement design and automation of scripts for data formulation, backups and archiving | Automated scripts for data backups | 1 Month | $5,000 |
|3 | User Interface Enhancements | DApp interface for Filecoin data access | 1 Month | $2,500 |
|4 | Community Outreach and Documentation | Educational workshops and documentation | 1 Month | $3,000 |

## Maintenance and Upgrade Plans

Long-term, FusionX plans to expand the number of data sets stored on Filecoin and develop advanced features for interacting with decentralized data. The team will establish regular maintenance cycles for data storage and release updates based on user feedback. Additionally, there will be ongoing audits and reviews to ensure data integrity.

# Team

## Team Members
Michael Doyle: Co-Founder & CEO of Invluencer - i3D Protocol
Role: Michael brings a strong background in Blockchain and cross-sector entrepreneurship and high-end projects for organizations like the UNDP and EU. His experience in leading projects across multiple jurisdictions will be valuable for overseeing the FusionX project development and ensuring compliance with international standards.

Don Gossen: Blockchain & Crypto Strategy
Role: Don's extensive experience in incubating and scaling blockchain ventures makes him a key asset for developing FusionX's blockchain strategy. His work on projects like Ocean Protocol (decentralized data marketplace) and Nevermined (decentralized computing) provides him with unique insights into building data-centric blockchain applications.

Aitor Argomaniz: Technical Blockchain & Crypto Development

Role: Aitor’s expertise in Deep Tech, Big Data, and blockchain development positions him as the lead technical director for the grant. His background as CTO at Nevermined and Keyko gives him a strong understanding of the technical requirements for building decentralized applications.

Smart Contract Development by CryptoDo
Bogdan Borodin, CEO CryptoDo
Vladimir Zlalevski, CTO CryptoDo
Roles: Strong strategic and technical capabilities, leading a team of dedicated smart contract developers to build, audit, and deploy the smart contracts for minting, burning, rebalancing, and integrating with Chainlink services. Cross-chain integration specialists, which is crucial for ensuring that FusionX can function seamlessly across multiple blockchains.

Other Team included from the i3D Protocol Team

## Team Member LinkedIn Profiles
https://www.linkedin.com/in/michael-doyle-26882bb6/
https://www.linkedin.com/in/donald-gossen-40ab96/
https://www.linkedin.com/in/aitorargomaniz/
https://www.cryptodo.app/#team

## Team Website
https://invluencer.com/about/

## Relevant Experience
Please see data in Team section

## Team code repositories
Available on request

# Additional Information

Received Filecoin Grant for the successful completion and development of the i3D Rapid by Invluencer Ltd

mikedoyle@invluencer.com

Full detailed Whitepaper
https://invluencer.com/wp-content/uploads/2024/10/FusionX-Whitepaper-October-2024.pdf
Website (subset of Invluencer.com): https://invluencer.com/fusionx/

**Comment by InvluencerMikeDoyle** [comment]
@ErinOCon Hi - just checking to see you received this?

**Comment by ErinOCon** [comment]
Hello @InvluencerMikeDoyle, thanks for checking in! Yes, this proposal has been received and is under review. For more information regarding our review process and timeline, check our our [repo](https://github.com/filecoin-project/devgrants/blob/master/Program%20Resources/Open%20Grants%20README.md). 

We will be in touch with any questions :)

**Comment by InvluencerMikeDoyle** [comment]
Hi @ErinOCon 
Just checking in for an update to see if we were shortlisted!

**Comment by ErinOCon** [comment]
Hi @InvluencerMikeDoyle, thank you for your time with this proposal and for your patience with our review. Unfortunately, we will not be moving forward with a grant at this time. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.

Wishing you the best as you continue building!
