### ISSUE TITLE
Open Grant Proposal:  Navis AI Agents on Filecoin

### ISSUE THREAD

**Issue by grzxz** [filecoin-project/devgrants#1819]
Open Grant Proposal:  `Navis AI Agents on Filecoin`

**Project Name:**  Navis  
**Proposal Category:**  Research & protocols
**Entity Name:**  Individual

**Proposer:**
-   Guillermo Ritorni 
    [GitHub: grzxz](https://github.com/grzxz)

**Project Information:**
-   [GitHub Repo](https://github.com/grzxz/navis)
-   [Navis Blog](https://navisprotocol.medium.com/navis-ai-agents-on-filecoin-transforming-ai-with-distributed-storage-0c197bcdec74)

**(Optional) Filecoin ecosystem affiliations:**  Akave
**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:**  Yes

## Project Summary
Navis provides a framework for the creation and management AI Agents using Filecoin for agent model storage and agent memory storage to unlock use cases for leveraging the vast amounts of data stored in Filecoin.

Alongside Navis AI Agents having ready to use models like Llama 3.2 already uploaded to Filecoin and also developers can upload their own trained models to Filecoin via Akave. Navis provides compute for model inference using Google Cloud TPUs, allowing for efficient and high-performance model inference while ensuring data integrity through Filecoin. Models are cached on Navis AI compute runtime based on usage so they enable interactive inference of LLMs based Agents.

Navis Agent memory is stored in Filecoin using Akave, ensuring that memory and state information are distributed and stored with data provenance. This guarantees resilience and the ability to scale as Filecoin provides redundancy and cost-effective storage for continuous operation of this agents.

A key component of Navis AI Agents is reflection, achieved through an integration of OpenAI's o1 model chain of thought feature and Llama 3.2 assesing and adapting to its own responses. This enables agents to self-evaluate and adapt their decision-making processes, increasing efficiency and allowing handling more complex tasks through planning.

Finally, Navis AI Agents are equipped with tools enabling them to perform specialised functions like reading/writing data in Filecoin with more functions in the roadmap.

### Navis Agents Profile, Memory, Planning and Action
Navis Agent Profile is an agent configuration such as initial identity and objective. Agent profiles specify models used like Llama 3.2 and OpenAI o1 as well as custom models uploaded to Filecoin by developers using Akave.
Navis Agent Memory is the knowledge store and experience archive of the agent stored in Filecoin using Akave. This serves as the state of the agent enabling context for new requests.
Navis Agent Planning enables agents to break down complex tasks into simpler sub-tasks through a chain-of-thought process using OpenAI o1 model.
Navis Agent Actions enable task completion is facilitated through function calling such as a functions to retrieve files from Filecoin.

### Navis AI Agents for Search
The primary use case for Navis AI Agents is facilitating search over data stored in Filecoin.

Navis AI Agents focusing on Search read data as context to answer questions to the user using Navis AI Agent LLM model. Developers and users can either read existing data stored in Filecoin or upload their own data to Filecoin.

Navis AI Agent for Search web application enables users to interact with Filecoin data by using designed to search through data stored on in Filecoin. It provides a Software Developer Kit (SDK) and a Command Line Interface (CLI), empowering developers to manage and deploy agents easily.

Navis AI Agents CLI/SDK allows developers to configure agents by defining key parameters in a YAML agent profile file. For example, in the agent_profile.yaml, the model_uri specifies the storage location of the AI model on Filecoin and the system_prompt_init defines the initial behavior/objective assistant of the agent such as a knowledgde. Through this configuration, agents can leverage AI models Large Language Models stored in Filecoin to handle user requests.

Navis AI Agent CLI simplifies creation and management of agents:
- *navis agent_profile agent_profile.yaml* initializes a new agent based on the provided configuration of model and memory storage
- *navis upload_model /path/to/model* uploads Large Language Models to Filecoin.
- *navis invoke_agent agent_uri request.json ipfs_uri* allows invoking an agent to fetch and process data from IPFS.

## Impact
 Navis AI Agents unlock additional functionality of over 23 exabytes of Network Storage Power in Filecoin with a focus on search alongside question answering with further functionality in the roadmap.
 Users are provided with web application to easily interface with Navis AI Agents to run search queries on Filecoin data. Developers are provided with a Python Software Developer Kit and a Command Line Interface. 
## Outcomes
-   Web Application
-   CLI
-   SDK
-   User and developer documentation

### Success Metrics:
- Navis AI Agents adoption via search Web Application.
- Developer adoption of Navis AI Agents via Software Development Kit and Command Line Interface. Navis AI Agents creation via upload of custom models to Filecoin.
- User feedback on the user experience and developer directly influencing Navis AI Agents roadmap.

### Milestone 1: Navis AI Agents Filecoin Integration on Akave (2 months)
-   **Deliverables:**
    -   Navis AI Agents Python Software Development Kit.
    -   Navis AI Agents Command Line Interface.
    -   Navis AI Agents search web application.
    -   Navis AI Agents developer documentation.
-   **Funding:**  $12,000

The total budget is $12,000 for development of Navis AI Agents Software Development Kit, Command Line Interface web application alongside documentation of all this components. Development costs involve compute costs using Google Cloud Compute Engine and Google Cloud TPUs for hosting Artificial Intelligence models.

### Guillermo Ritorni
**Founder of Navis | Software Developer** 
**LinkedIn:**  [Guillermo Ritorni](https://linkedin.com/in/guillermorr)
Contact email:  `guillermo.ritorni.salvo@gmail.com`

**Comment by ianconsolata** [comment]
Hi @grzxz! I have some questions for you about how you imagine this approach working:

1. I see you are planning to store the context and state using Filecoin. What are your latency considerations for that data? I assume you need very hot storage (or are you also keeping an in memory cache somewhere the agent is running and just using Filecoin as a backup of the context)?


1. I see you wrote:
> Navis AI Agents focusing on Search read data as context to answer questions to the user using Navis AI Agent LLM model. Developers and users can either read existing data stored in Filecoin or upload their own data to Filecoin.
> Navis AI Agent for Search web application enables users to interact with Filecoin data by using designed to search through data stored on in Filecoin.
Can you say more about how search, retrieval, and storage of docs would work? Search can be hard when you have to maintain a large search index of content on the network. Would you support retrieval augmented generation on these documents, or do you mean something else by search?

**Comment by grzxz** [comment]
Hi @ianconsolata! Sure here is the approach I have in mind:

Navis Agent storage will be using Akave https://www.akave.ai/. Akave testnet performance has been very solid so far, where I think they have retrieval optimizations to files uploaded to Filecoin such as caching of files.

Akave provides an interface Filecoin uploads and downloads. They provide an S3 compatible interface, so it is possible to use Python Boto3 for AI Agents model storage, memory storage and so on.

Search is provided on specific files stored on Filecoin where user already has CIDs of file or files such as text files or PDF files and asks question about it and LLM answers it . Akave also helps in the creation of data lakes which is another interesting use case to allow retrieval augmented generation over larger structured data stored in Filecoin via Akave. 
Managing and updating a search index of all Filecoin data would demand substantial effort, which falls beyond the scope of this grant.

Let me know if you have any further questions or anything you I need to clarify or explain further!

**Comment by ErinOCon** [comment]
Hi @grzxz! The preliminary review of your proposal is complete. Your project has been shortlisted as a final review candidate. If we have any remaining questions, we will contact you on this thread. 

If you have questions for our team, please contact us at [grants@fil.org](mailto:grants@fil.org).

**Comment by eshon** [comment]
@grzxz - DM'd you on Filecoin Slack, let me know!

**Comment by ErinOCon** [comment]
Hi @grzxz, thank you for your patience with our review! We would like to move your proposal forward to the next steps in our process. We will send an email with further details.

If you have any questions for our team, please contact us at [grants@fil.org](mailto:grants@fil.org).
