### ISSUE TITLE
Routescan Explorer for Filecoin EVM

### ISSUE THREAD

**Issue by rebeca-vacaru** [filecoin-project/devgrants#1820]
# Open Grant Proposal: Routescan Explorer for Filecoin EVM

**Project Name:** Routescan

**Proposal Category:** `Developer and data tooling`, `FVM`

**Individual or Entity Name:** Shaubiz Srl

**Proposer:** rebeca-vacaru (Rebeca)

**Project Repo(s):** The project is not open source, you can visit routescan.io to see the product.

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** No

## Project Summary

Routescan.io is a comprehensive multichain blockchain explorer that delivers real-time insights and advanced tracking tools for transactions across multiple blockchains. This project will develop a dedicated blockchain explorer specifically for the Filecoin Ethereum Virtual Machine (FVM), allowing for targeted, network-specific data tracking and analysis within the Filecoin ecosystem. With this custom-built FVM explorer, Filecoin developers and users will gain direct access to Filecoin-specific blockchain data, presented through Routescan’s clear and familiar interface, designed to streamline transaction tracking, contract verification, and network performance monitoring.

This new Filecoin EVM explorer will be fully integrated into Routescan’s broader multichain platform, making Filecoin data easily accessible and searchable alongside other major blockchains.

## Impact 

This dedicated Filecoin EVM explorer addresses critical needs within the Filecoin ecosystem, providing enhanced data access, redundancy, and integration within a broader multichain environment. While an existing explorer already supports Filecoin, this project introduces a robust layer of redundancy that ensures data remains accessible, accurate, and independently verifiable. This redundancy is essential for maintaining network resilience, allowing developers and users to access reliable transaction data and analytics even in cases of potential disruptions. 

By integrating Filecoin EVM data within Routescan’s multichain explorer, this project not only offers a cohesive tool for tracking metrics and verifying contracts but also positions Filecoin within a broad ecosystem of blockchain networks, enhancing its visibility and accessibility in the multichain landscape.

The advantages of successfully implementing this explorer extend beyond data redundancy to a more interconnected and developer-friendly experience. With seamless access to detailed analytics, contract verification, and real-time metrics across the broader Routescan multichain environment, developers can optimize dApp performance, better assess cross-chain usage patterns, and manage integrations with greater efficiency. If executed effectively, this project will help Filecoin strengthen its position within the multichain ecosystem, attracting developers who benefit from consistent data access and the ease of building on a stable, accessible platform. Without this redundancy and multichain integration, the ecosystem risks reduced reliability and limited interoperability, which could impact adoption and scaling.

Success for this project means establishing a reliable, resilient, and interconnected explorer that becomes essential for both Filecoin EVM and its integration within a broader blockchain landscape. By ensuring Filecoin EVM data is accessible in a robust multichain environment, this project supports Filecoin’s growth, making it a more connected and dependable platform within the multichain space, which in turn accelerates innovation and strengthens the entire Filecoin ecosystem.

## Outcomes

The final deliverable for this project is a fully operational, dedicated Filecoin Ethereum Virtual Machine (FVM) explorer, integrated into Routescan’s multichain platform. Key features of this explorer include:
+ **Smart contract verification**: An interface for developers to upload and verify the source code of their smart contracts directly within the Filecoin explorer, supporting transparency and ease of review.
+ **Public APIs and comprehensive documentation**: Robust APIs with detailed documentation will provide real-time, cross-chain data access across the Filecoin EVM and other networks within Routescan, all accessible with a single API key.
+ **Customizable analytics and enhanced charts**: Tools to visualize and monitor key metrics, including transaction flows, network performance, and usage patterns specific to Filecoin EVM.
+ **Data export and blockchain dumps**: Full data exports, including transaction histories, contract data, and other critical blockchain information for offline analysis, research, and audits.
+ **Advanced contract exploration tools**: Advanced search and filtering options for in-depth exploration and analysis of smart contracts within the Filecoin EVM network, allowing developers to review implementations across the ecosystem.

These features collectively define the functionality and deliverables of the Filecoin EVM explorer, providing a comprehensive, user-friendly toolset tailored to the Filecoin ecosystem.

The success of the project will be measured by the following metrics:
+ **Developer adoption and engagement**: Tracked through the number of verified contracts, API usage rates, and frequency of chart customizations and data exports within the Filecoin EVM ecosystem.
+ **Reliability and redundancy**: Measured by uptime, data accuracy, and system resilience, ensuring that the Filecoin EVM explorer provides reliable data access even under high-usage or disruptive conditions.
+ **Ecosystem integration**: Success will also be assessed by the extent of interoperability usage, indicated by the integration of Filecoin data with other blockchain networks within Routescan’s multichain environment.

By delivering these features and tracking these success metrics, the project aims to establish a resilient, user-friendly, and highly functional Filecoin EVM explorer that strengthens the Filecoin ecosystem while enhancing its role within the broader multichain landscape.

## Adoption, Reach, and Growth Strategies

The target audience for this Filecoin EVM explorer includes developers and blockchain enthusiasts who seek to dive deeply into on-chain data for insights, contract analysis, and data-driven decision-making. With over 2 million views per month and an existing base of 180,000-200,000 unique users, Routescan already has a substantial reach within the blockchain community. These users regularly access the platform for multichain data insights, transaction tracking, and contract verification, forming a strong foundation for the adoption of the new Filecoin EVM explorer.

To further grow our user base, we employ a range of ongoing outreach strategies, including social media campaigns, participation in major conferences, event sponsorships, and delivering talks within industry gatherings. These efforts not only keep existing users engaged but also serve to onboard new developers and blockchain enthusiasts into the Routescan ecosystem. As the dedicated Filecoin EVM explorer launches, we will leverage these channels to introduce new users to its functionalities, ensuring that developers across the Filecoin and broader blockchain ecosystem become aware of and utilize this powerful tool.

## Development Roadmap

This project will be divided into three key milestones to effectively allocate resources for node setup, indexing, design, and implementation. The total funding required is $25,000, with each milestone addressing critical aspects of the Filecoin EVM explorer’s development. 

### Milestone 1: Node setup and management
**Objective**: Establish and configure the Filecoin node to enable real-time data retrieval and ensure smooth integration with the Routescan infrastructure. This phase includes securing reliable connections, setting up servers, and implementing necessary security protocols.
**Expected functionality**: By the end of this milestone, the Filecoin node will be fully operational, providing stable data feeds and supporting the basic infrastructure needed for data indexing.
**Team**: 3 team members – 1 blockchain developer (node setup and integration), 1 data engineer (data management and feed stability), and 1 devOps
**Timeline**: 2 weeks from project start.
**Funding**: $7,000
### Milestone 2: Data indexing and recovery mechanisms
**Objective**: Implement a robust indexing system for Filecoin data to ensure efficient and rapid data retrieval, enabling real-time access for developers. This milestone also includes building recovery mechanisms to safeguard against data loss or network disruptions.
**Expected functionality**: The completion of this milestone will ensure that Filecoin transactions, contracts, and other blockchain data are efficiently indexed and accessible. Recovery protocols will be in place to maintain data integrity and uptime.
**Team**: 3 team members – 1 blockchain developer (indexing integration), 1 data engineer (recovery systems and data validation), and 1 backend developer
**Timeline**: 1-2 weeks following Milestone 1.
**Funding**: $16,000
### Milestone 3: Design and implementation of user interface
**Objective**: Develop a user-friendly interface that aligns with Routescan’s familiar look and feel while being customized to highlight Filecoin-specific data. This milestone includes UI/UX design, integration of data visualization tools, and front-end implementation for seamless user interaction.
**Expected functionality**: A fully designed and implemented user interface, featuring enhanced charts, data export options, and contract verification tools tailored to Filecoin’s needs. The explorer will be user-ready and capable of delivering comprehensive on-chain insights.
**Team**: 3 team members – 2 frontend developers (front-end integration) and 1 UX/UI designer (design and implementation).
**Timeline**: 1-2 weeks following Milestone 2.
**Funding**: $2,000

## Total Budget Requested

| Milestone # | Description                         | Deliverables                                                                                           | Completion Date                  | Funding |
|-------------|-------------------------------------|-------------------------------------------------------------------------------------------------------|----------------------------------|---------|
| 1           | Node Setup and Management           | Operational Filecoin node integrated with Routescan infrastructure, stable data feeds, security setup | 2-3 weeks from project start     | $7,000  |
| 2           | Data Indexing and Recovery Mechanisms | Efficient indexing system, data retrieval, and recovery protocols for data integrity                  | 4-5 weeks after Milestone 1      | $16,000 |
| 3           | Design and Implementation of User Interface | User-friendly interface with data visualization, Filecoin-specific features, and seamless interaction | 3-4 weeks after Milestone 2      | $2,000  |

## Maintenance and Upgrade Plans

The Routescan team will provide comprehensive maintenance for the first year following the project’s launch, including node management, data indexing, and system updates to ensure smooth operation and consistent data reliability. This will cover regular monitoring, troubleshooting, and performance optimization for the dedicated Filecoin EVM explorer.

After the initial year, we will evaluate and discuss extended maintenance options to address ongoing operational needs.
This project also represents the first foundational step, with significant potential for future development. In the next phase, we plan to implement cross-chain viewing capabilities within the explorer, enabling users to track and analyze cross-chain transactions seamlessly between Filecoin’s legacy network and the Filecoin EVM. This addition would broaden the explorer’s functionality, supporting enhanced multichain interactions and further solidifying Filecoin’s interoperability within the Routescan ecosystem.

# Team

## Team Members

Giacomo Barbieri - Growth manager	
Riccardo Migliorelli - DevRel
Rebeca Vacaru - DevRel
David Loucks - BizDev
Developers are not listed for security reasons.

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/giacomobarbieri94/
https://www.linkedin.com/in/riccardomigliorelli/

## Team Website

[Routescan](https://routescan.io/explorer-as-a-service)

## Relevant Experience

Our team has a strong background in data indexing, beginning with the creation of Avascan as part of an Avalanche grant. Since then, we’ve expanded significantly and now index data across 49 mainnets and 59 testnets, establishing a reputation for reliability and depth in blockchain data indexing. 

We are proud to serve a diverse range of clients, including

[Avalanche](https://snowtrace.dev/) 
[Berachain](https://bartio.beratrail.io/) 
[Boba](https://bobascan.com/) 
[Chiliz](https://chiliscan.com/) 
[Flare](https://flarescan.com/)
[Metis](https://explorer.metis.io/) 
[Mode](https://modescan.io/)
[Optimism ](https://thesuperscan.io/)(The SuperScan) 
[Taiko](https://taikoexplorer.com/) 
[Omni](https://testnet.omniscan.network/) 

Routescan has grown to become a trusted resource, with over 2 million page views and 180,000-200,000 unique users each month. Our experience in building scalable and user-friendly blockchain explorers positions us well to undertake this project, delivering efficient, accurate, and user-focused solutions.

## Team code repositories

Repos are not public, we can share access if asked

# Additional Information
rebeca.vacaru@routescan.io

**Comment by Migl992** [comment]
We already support all of them.

**Comment by eshon** [comment]
To clarify, @Migl992 is Routescan planning to run an FEVM archival node internally? We recommend using a node provider as I've mentioned that these nodes have 16 TiB of archival data.

**Comment by eshon** [comment]
Yes it's 250M transactions since March 2023 when Filecoin's EVM launched.

**Comment by iJaack** [comment]
OK @eshon but it seems unlikely that 250M tx is 16 TiB of data. Are you sure about the disk size?

**Comment by rebeca-vacaru** [comment]
Hey @ErinOCon thank you for your response regarding the proposal. I noticed that you mentioned sending an email to discuss other potential partnership opportunities, but I haven't received it yet. Can you please check again, and resend it? thank you
