### ISSUE TITLE
Open Source Cash for Privacy and Simple Self-Custody on FIL

### ISSUE THREAD

**Issue by KevinMckE** [filecoin-project/devgrants#1824]
# Open Grant Proposal: Open Source Cash for Privacy and Simple Self-Custody on FIL

**Project Name:** Open Source Cash for Privacy and Simple Self-Custody on FIL

**Proposal Category:**  `Other`. 

**Individual or Entity Name:** Anywhere Blockchain Corp

**Proposer:** [KevinMckE](https://github.com/KevinMckE)

**Project Repo(s)** Private

**(Optional) Filecoin ecosystem affiliations:** N/A

**(Optional) Technical Sponsor:** N/A

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** We will be open sourcing the mobile SDK that developers can use to implement this tech into their applications, but we will not be open sourcing our entire mobile application.

# Project Summary

Privacy is threatened by the open and transparent design paradigm of blockchains, and physical cash is a simple and private method of conducting transactions.
Our technology brings the benefits of private in person transactions and simple self custody that traditional cash offers to the world of FIL and Web 3.

Our Open Source Cash solution transforms open source, off-the-shelf, consumer-grade NFC tags into physical FIL or other digital assets, effectively recreating the advantages of traditional cash for our digital future. This turns every mobile phone on the planet using our software into a digital asset ATM that can transform these simple pieces of hardware into physical representations of digital assets.

This will be a beneficial new privacy and custody solution for retail FIL users, and our open source code will be made available for FIL wallet devs to build into their exchanges, wallets, and dapps in the FIL ecosystem.

## Impact 

The core of this technology is a key management primitive that simplifies the custody of assets. This approach has three benefits: privacy, simple/affordable self-custody, and interoperability.

Privacy: By making it possible to make transactions with physical objects, these transactions can be done offline for a private transaction that is not recorded onchain.

Simple/Affordable Self-Custody: this technology turns these tags into simple-to-use self-custody hardware wallets for %1 of the cost of other hardware wallet options.

Interoperability: These tags can operate as ecosystem multi-factor authentication that make it incredibly easy to access a wallet on several different systems without needing to leave the application to go through the wallet connect process.

## Outcomes

We are building a mobile application that will be available on Android and iOS, and an open source SDK for developers to use this technology in their mobile applications. If we receive the grant, these two offerings will include FIL functionality and we will develop and publish documentation to provide support for projects integrating this code into FIL projects.

We measure success based on increased adoption of the FIL ecosystem tools, and by the number of developers who use our SDK.

## Adoption, Reach, and Growth Strategies

We intend to onboard new users and developers at Web 3 conferences by giving them these tags, demonstrating the technology, and giving talks about the benefits of this technology. 

## Development Roadmap

$15,000 Write code to add FIL functionality to our Android and iOS mobile application. Measured by launch of beta version of our application featuring a working testnet version of our technology working on FIL testnet. 
Two software devs working on this milestone.
Deadline: 3 months after grant issued

$7,500 - Write code to add FIL to our open source React Native SDK functionality. Measured by publishing of SDK. 
One software dev working on this milestone.
Deadline: 2 months after grant issued

$2,500 - Develop documentation for integrating our SDK with other React Native applications. Measured by publication of docs on our website. 
One software dev working on this milestone.
Deadline: 2 months after grant issued

$15,000 Write code to add FIL mainnet functionality to our Android and iOS mobile application. Measured by launch of final version of our application featuring a working mainnet version of our technology working on ICP testnet. 
Two software devs working on this milestone.
Deadline: 3-6 months after grant issued

## Total Budget Requested

$40,000

## Maintenance and Upgrade Plans

We plan to maintain and upgrade functionality, security, and interoperability to our SDK for at least 12 months after the issuance of this grant, and potentially longer depending on community adoption.

# Team

## Team Members

Kevin Ecke - Founder/Product/Dev
Mark Lisanti - Co-Founder/Lead Dev
Cory Cranford - Cybersecurity Consultant

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/kevinecke/
https://www.linkedin.com/in/marklisanti/
https://www.linkedin.com/in/corycranford/

## Team Website

https://physikey.xyz

## Relevant Experience

Kevin Ecke - Founder, Open Source Cash inventor, head of product. Two time founder, Master's degree in technology design with a focus on cybersecurity, embedded systems, and user experience, and a certificate from MIT Sloan School of Business in Blockchain Innovation.

Mark Lisanti - Co-founder, CTO, Former IBM engineer. Master's degree in technology design with a focus on mobile app development, user experience, and web development.

Cory Cranford - Cybersecurity Consultant. Master's in Cybersecurity, 5 years experience in penetration testing for mobile applications and embedded system medical devices.

What our team has done:

Kevin previously developed an open source embedded system hardware oracle that ensures proper functioning of physical sensors to maximize data integrity for hardware oracles collecting data for blockchains.
https://github.com/KevinMckE/Dual-Sensor-Oracle

Mark has developed several mobile applications and technological art projects, one of which is available to view here:
https://marklisanti.me/projects/triangle-trail-status

Both Kevin and Mark were involved in developing the mobile application payment card technology called "Regen Card" that used Base, smart accounts, NFC cards, Transak onboarding, and paymasters to simplify USDC payments for farmers market vendors.

A video demo is available here, and a testflight/Android demo is available upon request:
https://www.physikey.xyz/physikey-payment-card

## Team code repositories

https://github.com/marklasagne
https://github.com/KevinMckE

# Additional Information
 
Met with a few devs at ETH Denver who mentioned it.
 
kevin@physikey.xyz

https://drive.google.com/file/d/1-dZfc58UoitqoVBtHqcxIsYMMC_xMgW_/view?usp=sharing

**Comment by ErinOCon** [comment]
Hi @KevinMckE, thank you for your proposal and for your patience with our review.  Unfortunately, we will not be moving forward with supporting your project at this time. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.

Wishing you the best as you continue building!
