### ISSUE TITLE
Integrating FIL & building the WooCommerce/Shopify extensions

### ISSUE THREAD

**Issue by BenraouaneSoufiane** [filecoin-project/devgrants#1825]
# Grant Proposal: `CryptoCheckout`

**Project Name:** CryptoCheckout

**Proposal Category:** `Integrations`

**Individual or Entity Name:** Individual

**Proposer:**  `BenraouaneSoufiane`

**Project Repo(s)** https://github.com/BenraouaneSoufiane/cryptocheckout.co/tree/main/site

**Filecoin ecosystem affiliations:** `This project does not have any existing work relationships, including investors and beneficial owners, with organizations in the Protocol Labs Network, including Protocol Labs, Filecoin Foundation, Filecoin Foundation for the Decentralized Web, and any others.` 

**(Optional) Technical Sponsor:** `N/A`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** "Yes".

### 1. What is your project and what problem does it solve?
Secure simple decentralized crypto payments gateway, enable online merchants to accept crypto payments on their websites, integrating Filecoin as payment coin may lead to the growth of the number of transactions, also may affect the Filecoin price.

Project website (& live demo): https://cryptocheckout.co
Pitch deck: https://pitch.com/v/crypto-checkout-2ygg9m
  
### 2. a) How is Filecoin used in this project?
![](https://cryptocheckout.co/archi.jpg)
    - Prepare & upload Filecoin thumbnails to the main dir for both users mobile & desktop (file-m.png & file.png).
    -  Add new form input in back.php (where the merchant can insert his file address when generating the merchant ID on the main page).
    -  Add filecoin decimals case in back.php.
    -  Handle the payment validation by adding new select case using filefox.info API as primary explorer.

(proposed) b) How does this project grow on-chain activity on Filecoin?
Depends on the merchant activity, users wailing to buy using their FIL balance, it increases the transaction volume.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? 

  
| Number | Grant Deliverable       | Briefly describe how you will meet deliverable objectives  | Timeframe (within 3 months)| Budget |
| :---   | :------                 | :---                                                       | :---                       | :---- |
| 1.     |  Filecoin supported/available (within the payment button) |  Integration details is in the section 2.a)   |   1 week   | 500 USD |
| 2.    |  WordPress plugin as GitHub repo    | Starting with empty wp plugin template, inclusion of WooCommerce class, init admin dasboard fields , handle save changes, echoing our payment script via init_payment_fields & wp_enqueue_script, handle connections frontend/backend, merchant site/our server, validate payment using process_payment()   | 2 weeks | 1000 USD |
| 3.   | 10 private mail servers | creating instance, install mail utils, install postfix, configure it, setup spf, dkim signing records with the main domain, prepare the mail list, init/format the message as php script as matches with/following spam act 2003 & Spam Hauss recommendations, add cron job (rate:1k msg/day per mail server), execute the job | 1 week | 1000 USD |
| 4.   |     Shopify app as GitHub repo   |   Starting with Shopify nodejs app template, install dependencies, init db, create admin form inputs, handle save changes, print our payment script in the checkout page, handle connections & other logics, validate payment    |  2 weeks | 1000 USD |

### 4. Adoption, Reach, and Growth Strategies
Target audience is any online business, there are about 200k of most visited/large businesses, 6M a normal businesses.<br/>
I'm using currently the email marketing to engage with them (accurate, efficient, low cost), also by partnerships, I previously contact li.fi, airbnb & razorpay via the partner form.

I'm focusing on the email marketing to onboard new users, also to understand my clients, I'm preparing to launch a marketing campaigns on x also efficient for 100$/day reach 300M person.

### 5. If accepted, do you agree to share monthly project updates in this Github Issue until the project described here is complete? 
Sure.

  
### 6. Does your proposal comply with our Community Code of Conduct?
Sure 

### 7. Links and submissions
N/A
  
### Additional questions:
* Team members

Benraouane Soufiane (solo): I started my career as an Envato author (making WordPress plugins/themes, selling them within the marketplace), then I built the WP auto translator known as Hirak, an online tool like POEDIT, then by 2019, I developed mini web apps with their apis such as translator, ip to country, currency exchange rates, until 2021 I started with the AI where where I built the OCR using the tesseractjs package & the faceapi using the tensorflowjs package, by 2022 I started with the web3 & the development of the CryptoCheckout

Code Repos
https://github.com/BenraouaneSoufiane/hypersub-bot
https://github.com/BenraouaneSoufiane/glodollar-donation-frame/tree/main
The previous repos are my most recent attemps, both are on the farcaster protocol (decentralized social media), the second repo uses the nextjs open graph images

LinkedIn Profile
https://www.linkedin.com/in/benraouane-soufiane-5993bb275

My Youtube channel where I post tutorials about my past webapps:
https://m.youtube.com/@hirakonlineservices6907
My resume: https://www.canva.com/design/DAGXIKIQR5Y/_OR5QoH8vwTQH7VDC27vRw/edit?utm_content=DAGXIKIQR5Y&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
Contact: admin@cryptocheckout.co or benrawane2012@gmail.com, t.me/benraouane
* How did you learn about this grant type program?
In Google search results

**Comment by ErinOCon** [comment]
Hi @BenraouaneSoufiane, Thank you for your interest in our grants program! We will review your proposal and will contact you with any questions on this thread. 

To learn more about our review process and timing, please see [our repo](https://github.com/filecoin-project/devgrants/blob/master/Program%20Resources/Builder%20Next%20Step%20Grants.md). If you have specific updates or questions for our team in the meantime, please contact grants@fil.org.
