### ISSUE TITLE
Snickerdoodle Labs Ecosystem Expansion

### ISSUE THREAD

**Issue by Dlul72** [filecoin-project/devgrants#1830]
# Open Grant Proposal: Snickerdoodle Labs
## Project Name:
Snickerdoodle Labs Ecosystem Expansion
## Proposal Category:
Integrations
## Individual or Entity Name:
Snickerdoodle Labs (Entity)
## Proposer:
Jonathan Padilla- CEO- https://www.linkedin.com/in/jpadillaca/

## Project Repo(s):
https://github.com/SnickerdoodleLabs
## (Optional) Filecoin ecosystem affiliations:
N/A
## (Optional) Technical Sponsor:
N/A
## Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:
No
---
## Project Summary
Snickerdoodle Labs is revolutionizing digital advertising by leveraging blockchain technology to create a transparent, rewarding ecosystem. The Snickerdoodle Ad Network uses tokenized incentives to attract consumer attention, rewarding both publishers and viewers for their engagement. This model enhances brand visibility, fosters community growth, and increases token distribution, benefitting the overall token ecosystem.
Our platform supports multiple blockchain protocols, including Polygon, Avalanche, Base, Arbitrum, Ethereum, Optimism, Binance, Chiliz, Astar, and Solana (coming soon). Snickerdoodle Labs allows brands to connect with consumers via blockchain-based incentives, providing a more engaging, privacy-focused alternative to traditional digital marketing methods. By creating a seamless, cross-chain experience, Snickerdoodle Labs is positioned to address the growing demand for more efficient, decentralized marketing solutions.
---
## Impact
As the digital advertising landscape shifts toward more transparent and rewarding models, Snickerdoodle Labs aims to fill the gap by offering a blockchain-powered advertising solution that rewards user engagement with tokens. This platform addresses several pain points in the current advertising industry: data privacy, user engagement, and the high costs associated with traditional advertising platforms.
Our solution not only enhances user participation but also increases token utility and distribution, supporting the broader blockchain ecosystem. With token incentives, brands can drive higher adoption rates while increasing the visibility of their products and services. The success of this project will be measured by the growth in the number of users, brands participating in the network, and the amount of token distribution.
---
## Outcomes
Upon completion, Snickerdoodle Labs will deliver:
- A fully functional digital advertising platform that leverages blockchain technology to reward user engagement.
- Token incentives for both publishers and viewers, driving more interactive and rewarding experiences.
- Increased visibility for brands participating in the network, contributing to stronger community growth.
- Enhanced token distribution, benefiting the overall token ecosystem.
Success will be measured by the number of brands and users on the platform, the volume of tokens distributed, and the overall impact on brand engagement and token utility.
---
## Adoption, Reach, and Growth Strategies
**Target Audience:**  
The target audience for Snickerdoodle Labs includes businesses and brands seeking to leverage blockchain technology for more transparent and efficient advertising, as well as blockchain users interested in earning tokens through engagement.
**Adoption Plan:**  
We plan to onboard early adopters by offering token incentives for engaging with brands within the Snickerdoodle Ad Network. To drive adoption, Snickerdoodle Labs will collaborate with a variety of dApps and integrate with established blockchain ecosystems to ensure broad reach.
**Growth Strategy:**  
Our growth strategy includes scaling the platform through partnerships with major blockchain foundations, securing funding to support the development of core features, and running targeted marketing campaigns. As the platform matures, we aim to expand to new networks and increase brand and user engagement globally.
—

Milestone 1: Integration of Snickerdoodle Labs onto Filecoin Ecosystem
Objective:
Seamlessly integrate Snickerdoodle Labs’ ad network with Filecoin’s decentralized storage solutions to enhance data security and tokenized advertising workflows.
Details:
This milestone focuses on adapting the Snickerdoodle platform to utilize Filecoin for secure storage and management of advertising data. By leveraging Filecoin's infrastructure, Snickerdoodle ensures encrypted storage for tokenized ad data, aligning with decentralized principles.
Deliverables:
Full integration of the Snickerdoodle Ad Network with Filecoin for secure and efficient storage of tokenized advertising data.
Demonstration of the Filecoin-powered data storage and token handling functionality within the ad network.
Funding Required: $10,000
Completion Date: Q4 2024
Milestone 2: Cross-Chain Functionality and Smart Contract Integration
Objective:
Expand Snickerdoodle’s cross-chain capabilities and integrate advanced smart contracts for token management and user engagement tracking.
Details:
This milestone enables compatibility with additional blockchain networks, such as Solana, and introduces smart contract features to streamline token distribution and user engagement metrics. This will enhance the platform’s flexibility and broaden its market appeal.
Deliverables:
Support for new blockchains, starting with Solana, to extend the platform’s reach.
Development and integration of smart contracts to manage token distribution and capture user engagement metrics.
Enhanced compatibility with a broader blockchain ecosystem for increased adoption.
Funding Required: $10,000
Completion Date: Q1 2025
Milestone 3: Platform Launch and Marketing
Objective:
Launch the Snickerdoodle Ad Network, targeting blockchain advertisers and consumers with a strong marketing push to drive adoption.
Details:
This milestone involves the official platform launch, onboarding advertisers and users, and executing marketing campaigns to establish Snickerdoodle as a leading blockchain-based ad network. Feedback from early users will guide continuous platform improvements.
Deliverables:
Official launch of the Snickerdoodle Ad Network, including live marketing campaigns to attract early adopters.
Onboarding of 50 brands and at least 1,000 active users.
Platform enhancements based on user feedback to ensure a seamless experience.
Funding Required: $10,000
Completion Date: Q2 2025

Total Budget Requested
$30,000
## Total Budget Requested

| Milestone # | Description                                | Deliverables | Completion Date | Funding |
|-------------|--------------------------------------------|--------------|-----------------|---------|
| 1           | Integration of Snickerdoodle Labs onto Filecoin Ecosystem | Secure token storage and management integration with Filecoin | Q4 2024 | $10,000 |
| 2           | Cross-Chain Functionality and Smart Contract Integration | Multi-chain support and smart contract functionality | Q1 2025 | $10,000 |
| 3           | Platform Launch and Marketing             | Full platform launch with initial marketing efforts and user engagement | Q2 2025 | $10,000 |
**Total:** $30,000

---
## Maintenance and Upgrade Plans
After the platform's launch, Snickerdoodle Labs will focus on long-term scalability, maintenance, and continuous upgrades. The team will prioritize enhancing security, improving user experience, and adding support for additional blockchain networks. The platform will also offer ongoing developer support, ensuring its continued relevance and growth within the ecosystem.
---
## Team
**Team Members:**  
- Jonathan Padilla (CEO)  
- Todd Chapman (CTO)  
- Isaac Lazoff (Head of BD)  
- Charlie Sibbach (Head of Architecture)  
- Sara Melamed (Head of Marketing)  
- Corentin Cadieu (Web 3 Serial Entrepreneur - Advisor)

**Team LinkedIn Profiles:**  
- Jonathan Padilla: http://www.linkedin.com/in/jpadillaca/  
- Todd Chapman: http://www.linkedin.com/in/todd-chapman/  
- Isaac Lazoff: http://www.linkedin.com/in/isaaclazoff/  
- Charlie Sibbach: http://www.linkedin.com/in/charlie-sibbach/  
- Sara Melamed: http://www.linkedin.com/in/saramelamed/
- Corentin Cadieu: https://www.linkedin.com/in/corentincadieu/?originalSubdomain=fr
**Relevant Experience:**  
The Snickerdoodle Labs team has over 20 years of combined experience in blockchain development, marketing, and business development. The team has successfully launched several Web3-based projects and worked with top-tier companies in the tech and finance sectors. With backgrounds in engineering, product development, and business development, Snickerdoodle Labs is well-equipped to drive the success of the Snickerdoodle Ad Network.
---
## Additional Information
**How did you learn about the Open Grants Program?**  
Through blockchain development forums and Filecoin community events.
**Best email address for discussing the grant agreement and next steps:**  
snickerdoodle@0xlabs.tech
---

**Comment by ErinOCon** [comment]
Hi @Dlul72, Thank you for your proposal and for your patience with our review.  Unfortunately, we will not be moving forward with supporting your project at this time. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.

Wishing you the best as you continue building!
