### ISSUE TITLE
Universal mass storage solution for the @Deso blockchain

### ISSUE THREAD

**Issue by ArnoudvanderPlas** [filecoin-project/devgrants#1832]
# Open Grant Proposal: `Project Title`

**SafetyNet decentralizing off chain mass storage**

**Proposal Category:**  Storage (and possible integration)

**Individual or Entity Name:** 
SafetyNet

**Proposer:** ArnoudvanderPlas

**Project Repo(s)** Please list Github repos used for this project work. 
The deso blockchain (https://github.com/deso-protocol/ ) is a decentralized social network with great potential and a proven track record. SafetyNet is a community driven project to further improve and decentralize parts of the deso blockchain.
Read more about SafetyNet via https://safetynet.social/u/SafetyNet

We propose to make use of FileCoin decentralized storage solution for blob storage of images and videos in social posts, profile pictures and NFTs. Read more here: https://docs.deso.org/deso-blockchain/on-chain-data

**(Optional) Filecoin ecosystem affiliations:** `Please disclose any existing work relationships with organizations in the Protocol Labs Network, including Protocol Labs, Filecoin Foundation, Filecoin Foundation for the Decentralized Web, and any others.` 

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Please respond with "Yes" or "No". I agree to the open source nature of this document my anser is: "YES"

# Project Summary

## Impact 

The impact in the market will be twofold. The DeSo Blockchain will be able to provide a secure, scaleable and decentralized service to it's userbase. Users of the DeSo social media platform can pay for the service to have their large off chain assets be stored securely on chain or on any IPFS service in cooperation with Filecoin. For Filecoin, this collaboration can provide a significant business opportunity if and when on chain social media takes off.

## Outcomes

The final outcome has to be a solution whereby the user of the DeSo blockchain can seamlessly and securely store large amounts of data using on chain micropayments (in the DeSo token) that can be automatically be paid to Filecoin and its' IPFS services. On the other side, nodes with a surplus of storage can "rent" out their space to Filecoin.

We will difine the success of our project by the number of nodes on the DeSo blockchain joining in on our proposal and in the amount of users (profiles) effectively using the service. Lastly, we measure the success by the raw amount of storage space used/ procured at your service

## Adoption, Reach, and Growth Strategies

Onboarding will go at a parallel pass to the adoption of Deso and the Focus application in the near future. If it grows so will our reach.

## Development Roadmap

Deso roadmap can be seen on https://docs.deso.org/deso-roadmap
Note that soon the Focus app will be launched, a major milestone in making deso known to larger audience.

SafetyNet project and roadmap can be read in our white paper: https://1drv.ms/w/c/a946bc8fcce09f1a/EdnhOleOVUNIrQqIiylcm8EBdqf-HDLZ88YhaIVUSkNCkw

## Total Budget Requested

| Milestone # | Description | Deliverables | Completion Date | Funding |
|===|===|===|===|===|

## Maintenance and Upgrade Plans

# Team

## Team Members

 Carry Megens
Arnoud van der Plas

](ttps://www.linkedin.com/in/carrymegens/)
https://www.linkedin.com/in/arnoud-van-der-plas-3a995416/

https://safetynetvalidator.nl/u/SafetyNet

## Relevant Experience

 We have three developers @carry2web @degen_doge and @diamondthumb. We have communications official, @ArnoudvanderPlas 

## Team code repositories

# Additional Information
From the Filecoin foundation website.
support@safetynet.social
Proposal: Integrating IPFS and Filecoin Functionality into DeSo Blockchain Nodes

Introduction

This proposal outlines the integration of IPFS (InterPlanetary File System) and Filecoin functionality into the DeSo blockchain nodes. This integration aims to enhance the capabilities of the DeSo network by providing decentralized storage, improved data availability, and reduced storage costs.

Problem Statement

Currently, DeSo stores all data on-chain. While this ensures security and immutability, it leads to increased storage costs and potential scalability issues as the network grows. Storing large files like images and videos directly on the blockchain can become expensive and inefficient.

Proposed Solution

Integrate IPFS and Filecoin functionalities into DeSo blockchain nodes to address these challenges.

IPFS Integration

    Decentralized Storage: Leverage IPFS as a decentralized storage solution for large files (e.g., images, videos, and long-form content). Instead of storing the entire file on the DeSo blockchain, only the IPFS content identifier (CID) will be stored.
    Content Addressing: Utilize IPFS's content addressing to ensure data integrity and eliminate duplicate data storage.
    Improved Efficiency: Reduce on-chain storage requirements and improve transaction speeds by storing large files off-chain.

Filecoin Integration

    Incentivized Storage: Integrate Filecoin to provide a financial incentive for users to store and distribute DeSo data. This ensures data availability and redundancy.
    Reduced Storage Costs: By utilizing Filecoin's decentralized storage marketplace, DeSo can potentially reduce storage costs compared to on-chain storage.
    Enhanced Security: Filecoin's cryptographic proofs ensure data integrity and availability over time.

Implementation Details

    Node Modification: Update DeSo nodes to include IPFS and Filecoin functionalities. This includes installing IPFS and Filecoin clients and implementing communication protocols between DeSo nodes and the IPFS/Filecoin networks.
    Data Handling: Modify DeSo applications to upload large files to IPFS and store the corresponding CID on the DeSo blockchain.
    Filecoin Integration: Develop a mechanism for DeSo users to utilize Filecoin for storing and retrieving data. This may involve integrating Filecoin wallets and payment channels into DeSo applications.
    API Development: Create APIs to allow developers to interact with the IPFS/Filecoin functionalities from their DeSo applications.

Benefits

    Scalability: Reduce on-chain storage burden, enabling the DeSo network to scale more efficiently.
    Cost Efficiency: Lower storage costs by utilizing Filecoin's decentralized storage marketplace.
    Enhanced Data Availability: Ensure data availability and redundancy through IPFS and Filecoin's decentralized networks.
    Improved User Experience: Faster transaction speeds and improved application performance due to reduced on-chain storage.

Challenges

    Integration Complexity: Integrating IPFS and Filecoin into DeSo nodes requires significant development effort and careful consideration of interoperability.
    Network Dependency: DeSo will rely on the IPFS and Filecoin networks for data availability and storage.
    User Adoption: Encouraging users to adopt IPFS and Filecoin for storing and retrieving data may require educational initiatives and user-friendly tools.

Conclusion

Integrating IPFS and Filecoin functionalities into DeSo blockchain nodes presents a significant opportunity to enhance the platform's capabilities and address scalability and cost challenges. By leveraging these decentralized technologies, DeSo can create a more robust, efficient, and cost-effective platform for decentralized social media and content creation.

**Comment by ArnoudvanderPlas** [comment]
First draft, please assist

**Comment by carry2web** [comment]
I can comment on it with Quote reply and participate on writing the proposal

> # Open Grant Proposal: `Project Title`
> **Safetynet decentralizing off chain mass storage for Deso blockchain**
> 
> **Proposal Category:** Storage (and integration)
> 
> **Individual or Entity Name:** Safetynet
> 
> **Proposer:** ArnoudvanderPlas 
> 
> **Project Repo(s)** Please list Github repos used for this project work.
> ToDo: Currently private repos on GitLab, will open up one repo for filecoin/safetynet 

> **(Optional) Filecoin ecosystem affiliations:** `Please disclose any existing work relationships with organizations in the Protocol Labs Network, including Protocol Labs, Filecoin Foundation, Filecoin Foundation for the Decentralized Web, and any others.`
> 
> **(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`
> 
> **Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Please respond with "Yes" or "No".
> 
> # Project Summary
> ## Impact
> ## Outcomes
> ## Adoption, Reach, and Growth Strategies
> ## Development Roadmap
> ## Total Budget Requested
> | Milestone # | Description | Deliverables | Completion Date | Funding | |===|===|===|===|===|
> 
> ## Maintenance and Upgrade Plans
> # Team
> ## Team Members
> ## Relevant Experience
> ## Team code repositories
> # Additional Information

**Comment by ErinOCon** [comment]
Hi @ArnoudvanderPlas, is this proposal still being drafted? Please let us know if additional time is needed prior to our team completing our review.

**Comment by ArnoudvanderPlas** [comment]
My good madam or sir,

It is not completely ready but we would like to discuss it further because
we want to evaluate a posible (seedless)bridge between File coin and Deso.
Almost all info is in it. Could we arrange a video meeting?
Please let us know if a meeting at this point is an option for you.

Met vriendelijke groet,
*Arnoud van der Plas*

telefoon: +31625363229
email: ***@***.***




Op ma 9 dec 2024 om 22:35 schreef ErinOCon ***@***.***>

**Comment by ErinOCon** [comment]
Hi @ArnoudvanderPlas, thank you for your proposal and for your patience with our review.  Unfortunately, we will not be moving forward with supporting your project at this time. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.

Wishing you the best as you continue building!
