### ISSUE TITLE
WWWAI - Decentralised AI training

### ISSUE THREAD

**Issue by ProjectIGIRemakeTeam** [filecoin-project/devgrants#1837]
# Open Grant Proposal: `WWWAI - Decentralised AI training`

**Project Name:

We'd like to bring the AI training easy and available for everyone, you can save, store and train your ai models based on websites you visited and you could share these models with others, like hugging face for example, but it based on website research data.
https://wwwaichat.netlify.app/?ai=wwwai

I made a little front-end version: you can tell 'play music', 'i want to draw', 'play half-life', the basis for this project was that every answer is a html page.

I'd like to apply for $50k grant, to create a windows application for the training part using filecoin system.

igiteam.remake@gmail.com

Thanks,
Gabriel Majorsky

**Comment by ErinOCon** [comment]
Hi @ProjectIGIRemakeTeam, thank you for your proposal. Unfortunately, we will not be moving forward with a grant for your project. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.
