### ISSUE TITLE
Block Rewards (BR) 3.0

### ISSUE THREAD

**Issue by InsaneDaneBrain** [filecoin-project/devgrants#1843]
# Open Grant Proposal: `Block Rewards 3.0`

Block Rewards (BR) 3.0

Integrations

The Digital Campus Inc.

**Proposer:** 'InsaneDaneBrain'
**Project Repo(s)** Please list Github repos used for this project work. 

**(Optional) Filecoin ecosystem affiliations:** `Please disclose any existing work relationships with organizations in the Protocol Labs Network, including Protocol Labs, Filecoin Foundation, Filecoin Foundation for the Decentralized Web, and any others.` 

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP under the MIT/Apache-2 dual-license?:** Please respond with "Yes" or "No".

# Project Summary

Block Rewards (BR) 3.0 is a unified platform for NFT-based gift cards, gamified loyalty programs, and employee incentives, secured by blockchain technology. Our core mission is to reduce the complexity and cost of loyalty programs by combining decentralized storage, blockchain-secured transactions, and tokenized incentives into a single solution for both consumers and businesses.

Filecoin will serve as the primary storage layer for all transaction data, reward issuance logs, and NFT metadata. Avalanche or Polygon will be used for fast, cost-effective on-chain transactions, ensuring seamless reward redemptions and transfers. This hybrid approach delivers the speed of layer-2 chains with the security and permanence of decentralized storage on Filecoin.

## Impact 

The rewards industry, valued at over $24B annually, faces issues like fragmented systems, inefficient storage, and centralized data vulnerabilities. BR addresses these issues head-on with decentralized storage and blockchain-powered rewards.

Impact to the Filecoin Ecosystem:
Decentralized Data Storage: Using Filecoin to store NFT metadata, loyalty point issuance records, and customer/vendor transaction data.
Enterprise Use Case: By onboarding major enterprises (like Starbucks, H.E.B., and Kroger), BR introduces decentralized storage to thousands of SMBs and millions of end-users.
Demonstrates Hybrid Blockchain Integration: By combining Filecoin for storage with Avalanche/Polygon for transactions, BR showcases a real-world use case for multi-blockchain integration.
Without this solution, vendors will continue using fragmented, insecure storage, and loyalty program growth will remain inefficient and costly.

## Outcomes

Final Deliverables
MVP for the Block Rewards Platform:
A fully operational, ready-to-use MVP with secure NFT gift cards, vendor-specific rewards, and employee incentive systems.
Decentralized Storage Integration:
Filecoin will host customer and vendor data (transactions, reward issuance) and all NFT metadata.
Enterprise-Grade Wallet:
Wallet system allowing users to store, transfer, and redeem loyalty tokens.
Vendor Portal for Rewards Customization:
Vendors can issue, redeem, and manage loyalty campaigns in real time.
Success Metrics
10,000+ NFTs for gift cards created and stored via Filecoin.
Onboard 500+ SMBs during the pilot phase.
100,000+ reward transactions processed using Filecoin and Avalanche/Polygon.

## Adoption, Reach, and Growth Strategies

Target Audience:
Small and Mid-Sized Businesses (SMBs) for loyalty programs.
Enterprise Partners (e.g., Starbucks, H.E.B, Kroger) for NFT gift card adoption.
HR Platforms (like Gusto and Rippling) for tokenized employee incentive programs.
Onboarding Strategies:
SMB Pilots: Onboard 500 SMBs to test Filecoin-backed reward issuance and NFT gift cards.
Enterprise Partnerships: Work with larger organizations (e.g., Starbucks, H.E.B) to promote adoption.
HR Platforms: Integrate BR with employee recognition platforms like Gusto, LinkedIn Learning, and Rippling.

## Development Roadmap

The goal is to have a fully operational MVP within 3-4 months
Milestone | Description | Deliverables | Completion Date | Funding
-- | -- | -- | -- | --
1 | MVP Buildout | Fully functional MVP with gift cards, vendor tools, and NFT storage on Filecoin | Month 2 | $100,000
2 | Decentralized Storage Integration | Full Filecoin integration for transaction data, NFT metadata, and reward issuance logs | Month 2 | Included
3 | Blockchain Transaction Layer | Avalanche/Polygon integration for on-chain reward issuance and redemption | Month 2 | Included
4 | Vendor Portal Development | Complete web-based dashboard for vendors to issue, track, and customize rewards | Month 3 | $75,000
5 | User Wallet & Redemption System | Wallet system for users to store, send, and redeem NFT gift cards and loyalty points | Month 4 | $75,000

## Maintenance and Upgrade Plans

Post-MVP Upgrades: We plan to enhance wallet features, improve vendor UI/UX, and scale Filecoin data capacity.
Long-Term Scalability: We will maintain and optimize Filecoin storage capacity for larger partnerships with Starbucks, H.E.B, and other enterprises.
Continuous Updates: New features and security updates will be released on a quarterly basis.

# Team

Team Members
Dane Rose – CEO & Founder (Business Leadership, Product Strategy)
Shari Swenson – Co-Founder (Financial Management, Real Estate, Investor Relations)
Robert Rooney Jr. – Co-Founder (Business Strategy, Investor, Consultant)
Solidea Capital - Strategic Advisory

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/dane-rose-03189922b/
https://www.linkedin.com/in/shari-swenson-07302a1b5/
https://www.linkedin.com/in/robertrooneyjr/
https://www.linkedin.com/company/solidea-capital/

## Team Website

https://www.blockrewardsapp.com/

## Relevant Experience

Our team has extensive experience in business development, blockchain adoption, and financial innovation. We are partnering with Aetsoft, a blockchain development firm, to accelerate the MVP build. This collaboration allows us to combine real-world business experience with blockchain development expertise.

Our unique approach to using Filecoin for storage and Avalanche/Polygon for transactions demonstrates how multi-chain solutions can bring significant operational and cost benefits to businesses.

## Team code repositories

Repositories will be established upon grant approval and will be open-sourced as required under the MIT/Apache-2 license.

# Additional Information

How did you learn about the Open Grants Program? Filecoin developer forums and grant announcements.
Best Email Address: exco@blockrewardsapp.com
Additional Notes: This project bridges blockchain with real-world use cases, driving adoption of Filecoin across loyalty, HR, and enterprise ecosystems.

**Comment by ErinOCon** [comment]
Hi @InsaneDaneBrain, thank you for your proposal and for your patience with our review.  Unfortunately, we will not be moving forward with supporting your project at this time. To contact our team with inquiries regarding our review or grants program, please send an email to grants@fil.org.

Wishing you the best as you continue building!
