### ISSUE TITLE
open-proposal-BFLO_FREEFLO_AND_THE_SDGs.md

### ISSUE THREAD

**Issue by AmySeidman** [filecoin-project/devgrants#197]
https://github.com/filecoin-project/devgrants/pull/195

@eshon for some reason I am spinning around the labeling. It doesn't seem to be appearing for me in my view...perhaps I am doing something wrong...or not clicking...but I have been doing so for a while and watched a few videos. I hope I can still submit this proposal which should have the label:

Proposal type: category:app-dev
Grant type: proposal-type:open

Many thanks!

Ames

**Comment by eshon** [comment]
@AmySeidman don't worry about labeling!

**Comment by AmySeidman** [comment]
PHEW! I've been looking for past few hours... so glad to hear from you.

Goodnight.

PS budget may need a revisit with team.
