### ISSUE TITLE
RFP: Reputation system

### ISSUE THREAD

**Issue by pooja** [filecoin-project/devgrants#25]
We just launched our RFP for a reputation system on the Filecoin network. Read more about it here: https://github.com/filecoin-project/devgrants/blob/master/rfps/rfp-reputation-system.md

We'd love to talk to you about the RFP in this issue.

**Comment by ElecRoastChicken** [comment]
Fantastic! The same concern was put forward on 14th March: https://discuss.filecoin.io/t/how-to-ensure-data-durability/161/3, a robust storage network needs it!

**Comment by mishmosh** [comment]
Closing because lots of progress has been made on reputation systems in the past 2 years. See https://filrep.io/ for one example.

**Comment by BrandonKMLee** [comment]
This is something to be concerned of, at least in theory
