### ISSUE TITLE
RFP: Hosting community events

### ISSUE THREAD

**Issue by pooja** [filecoin-project/devgrants#26]
Want to host an awesome Filecoin community meetup in your region? Please take a look at our RFP for community events! https://github.com/filecoin-project/devgrants/blob/master/rfps/rfp-community-meetups.md

Feel free to ask/comment about this RFP in this issue.

**Comment by josselinchevalay** [comment]
i live in paris maybe i can help to organize that's in france.

**Comment by pooja** [comment]
@josselinchevalay Hi there! We'd love to read your proposal. Would you mind filling one out according to the description in the RFP? https://github.com/filecoin-project/devgrants/blob/master/rfps/rfp-community-meetups.md Let us know if you have any questions!

**Comment by josselinchevalay** [comment]
i use  https://github.com/filecoin-project/devgrants/blob/master/rfps/rfp-community-meetups.md to create issue or i need to add new file into https://github.com/filecoin-project/devgrants/tree/master/rfp-proposals and create a pull request ?

**Comment by pooja** [comment]
Hi @josselinchevalay, please file a PR. You can follow the instructions here: https://github.com/filecoin-project/devgrants#submit-a-proposal-for-an-rfp
