### ISSUE TITLE
Next Step Microgrant: filplus.info

### ISSUE THREAD

**Issue by laurarenpanda** [filecoin-project/devgrants#270]
### 1. What is your project?
Filplus.info is the first visual dashboard for Filecoin Plus, which can be regarded as an incentive program for useful storage on Filecoin. Through monitoring on-chain messages on Filecoin and off-chain information on GitHub, filplus.info records relevant real-time data of each DataCap allocation and verified deal transactions on Filecoin from public APIs and open-source platforms.

On filplus.info, there are visual data analysis charts, information of notaries and clients, and deal-flow of DataCap. It also supports multiple parameters search and a hyperlink jump to the Filecoin browser filscan.io.

Github repo: [filplus-info](https://github.com/filedrive-team/filplus-info)

Website: [filplus.info](https://filplus.info)

### 2. How are you planning to improve this project? 
- Dashboard
  - More statistics and metrics about the Filecoin Plus program
  - More visual data analysis charts
- Notaries
  - Information updating about new notaries from the second round of Notary elections
  - Search for a specific Notary by name/organization/Filecoin address
  - Hyperlink jump to Notaries’ GitHub profile pages
- Clients
  - Statistics of verified deals and DataCap distribution to cooperative miners by a client
  - Statistics of auto verified DataCap
- Miners
  - Hyperlink jump to miners’ info on Filecoin browser
- UI design

### 3. Will the work be Open Source?
Yes, filplus.info will be open source under the MIT license for code.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes, we agree to share weekly updates and a grant report upon conclusion, include progress or results of our microgrant-funded work, any Filecoin technical or usage guidance requests, and a description of our experience building on Filecoin, including any challenges or shortcomings encountered.

### 5. Does your proposal comply with our Community Code of Conduct?
Yes, this proposal complies with the [Filecoin Code of Conduct](https://github.com/filecoin-project/community/blob/master/CODE_OF_CONDUCT.md).

### 6. Links and submissions
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
  Yes.

  The Filecoin Community Showcase:  [[Application]Filplus.info](https://github.com/filecoin-project/community/discussions/119)
  
* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
  Yes, we have.
  
  The thread for filplus.info: [filplus.info v2.1.0](https://github.com/filecoin-project/community/discussions/119#discussioncomment-775369)
  
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

  Filplus.info is a dashboard for the FIL+ project, so it didn't begin at a hackathon. However, we have participated in the Filecoin Quadratic Funding Grant Round-1 at DoraHacks with this project.

  Filplus.info at DoraHacks: [filplus.info仪表盘](https://hackerlink.io/buidl/499?roundProj=499)
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

  |   Name    |          Email          |   Github    |       Role        |
  | :-------: | :---------------------: | :---------: | :---------------: |
  | Felix Li  |  felixlee886@gmail.com  | @beeleelee  |    Founder/CTO    |
  | Laura Ren | laurarenpanda@gamil.com | @laurapanda |   Co-founder/PM   |
  |   Hh Q    | huanhuan2689181@126.com |    @Eric    | Backend Engineer  |
  |    Abu    | liguangbin2013@126.com  |  @abu0306   | Frontend Engineer |

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
  
    Filecoin Quadratic Funding Grant Round-1 at DoraHacks
  
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
  
    Filplus.info at DoraHacks: [filplus.info仪表盘](https://hackerlink.io/buidl/499?roundProj=499)

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

**Comment by laurarenpanda** [comment]
## [filplus.info](https://hackerlink.io/buidl/499?roundProj=499) v3.0.0 launched on Sep. 28th.
It is a very different version with a new UI design, statistics of three application methods of DataCap (including Notary allocation, large Datasets, and monthly automatic verification), and new features along with other bug fixes.

Significant new features including:
- Dashboard
  - More statistics and metrics about the Filecoin Plus program, including Notary allocation, large Datasets, and monthly automatic verification
  - Hyperlink jump to verify application page: *Issue: Client Datacap Allocation Request* and *Issue: Large Dataset Notary application* on GitHub, and DataCap faucet verify.glif.io
- Notaries
  - Information updating about new notaries from the second round of Notary elections
  - Search for a specific Notary by name/Filecoin address
  - Hyperlink jump to Notaries’ GitHub profile pages
  - Export Notary allocation record (display in the list, maximum 20)  as a CSV file
- Clients
  - Statistics of verified deals and DataCap distribution to cooperative miners by a client
  - Export DataCap receiving and usage record (display in the list, maximum 20) as a CSV file
- Large Datasets Application
  - The highest proportion of DataCap stored with one storage provider in each allocation
