### ISSUE TITLE
Next Step Microgrant: <CryptoBank Africa>

### ISSUE THREAD

**Issue by cryptobanks-app** [filecoin-project/devgrants#275]
### 6. Links and submissions...Yes

  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
  

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
  
  

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: https://hackerlink.io/en/buidl/884?roundProj=759 
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Ferdinand U.I...email;Investorferdinand@gmail.com...  CryptoBank Founder.
* Nick Dominic...asedeyhotblog.com... https://github.com/padom2020... Developer
* Abdulazee... abdulazeezsalihu41@gmail.com... https://github.com/abdulazeezsalihu41
* Olamide O... https://github.com/olamideokunola...  Developer
* Obi Joshua...Tplex.brand@gmail.com... CryptoBank Graphic designer
* If your project was created as part of an event or hackathon: Yes
  * What was the name of the event? Binance Africa hackathon
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
    https://hackerlink.io/en/buidl/884?roundProj=729

**Comment by SeedingTrees** [comment]
Thanks for submitting this application.  Can you provide more details on the project, including:

1) What is the current state of the project?
2) What needs to be done to complete this project, and how will this microgrant help you do that?
3) How do you plan to use IPFS and/or Filecoin as integral components to the project?  

Thanks,

ST

**Comment by mishmosh** [comment]
Hello, we are closing this application due to lack of activity. If you're like to re-submit in the future feel free to open another issue. Thank you!

**Comment by cryptobanks-app** [comment]
No problem... I was here waiting for your direction and response but
nothing happened and now this is it... We keep on moving...Thanks for
everything
