### ISSUE TITLE
Next Step Microgrant: <DatSphere>

### ISSUE THREAD

**Issue by cgpiao** [filecoin-project/devgrants#278]
### 1. What is your project? (max 100 words)
Datsphere: A blockchain based drive.  
Datsphere enable files to be placed and retrieved through on-chain transactions by the power of IPFS and Filecoin Network.   
We already implemented basic features, such as login/register an account, navigate uploaded files, upload file/folder, import remote ipfs hash to drive, create text-file/folder, generate ipfs hash to uploaded files.   
[Link to Github repo](https://github.com/cgpiao/datsphere)  
[website](https://datsphere.com/)  
### 2. How are you planning to improve this project? (max 200 words)
First step is to integrate filecoin to the application, then implement features as below.  
- Redesign UI/UX
- Provide handful SDK toolkit, help developers integrate drive to their service
- Integrate Payment System
- Support file versioning system
### 3. Will the work be Open Source?
Yes, already in MIT license  
### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes, I agree to share weekly updates and a grant report upon conclusion  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes
Yes, this proposal complies with the [Filecoin Code of Conduct](https://github.com/filecoin-project/community/blob/master/CODE_OF_CONDUCT.md).
### 6. Links and submissions

  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
Yes, still in review  
[The Filecoin Community Showcase](https://github.com/filecoin-project/community/pull/229)   
* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?  
https://github.com/filecoin-project/community/discussions/228  

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

|  Name      |  email  |  Github  |  Role  |
|  -----------  |  -----------  |  -----------  |  -----------  |
|  ChengGuo Piao   |  piaocg@outlook.com    | [cgpiao](https://github.com/cgpiao) | Main Developer     |
|  GuiHu Shen   |    |    |  FrontEnd Developer     |
|  YaZhou Li   |    |    |  Product Manager    |
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
