### ISSUE TITLE
Next Step Microgrant: <Filecoin Java sdk>

### ISSUE THREAD

**Issue by jc0803kevin** [filecoin-project/devgrants#296]
### 1. What is your project? (max 100 words)
Supporting features:

FilecoinJ is a lightweight, highly modular, reactive, type safe Java library for working with integrating with clients (nodes) on the Filecoin network:

+ Complete implementation of Filecoin's JSON-RPC client API over HTTP
+ offline wallet creation(BLS, secp256k1 & multisig), 
+ Transfer Signature, offline multi-signature, etc.
+ Filecoin wallet support

It has five runtime dependencies:
+ OKHttp for HTTP connections
+ Jackson Core for fast JSON serialisation/deserialization
+ web3j 

Remote Repositorie link :  [FilecoinJ](https://github.com/jc0803kevin/FilecoinJ)

### 2. How are you planning to improve this project? (max 200 words)
Integrate the SDK into the project, and then use the SDK function to complete the support for filecoin.

This allows you to work with the Filecoin blockchain, without the additional overhead of having to write your own integration code for the platform.

Just like [bitcoinj](https://github.com/bitcoinj/bitcoinj) support for bitcoin and [web3j](https://github.com/web3j) support for Ethereum, filecoinj can be used to fully support filecoin, and java language can be used to support json rpc, construct transactions, and sign transactions.

* Maven
```xml
<dependency>
    <groupId>io.filecoin.sdk</groupId>
    <artifactId>filecoinJ</artifactId>
    <version>1.0-SNAPSHOT</version>
</dependency>
```
### 3. Will the work be Open Source?
Yes

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes, I agree to share weekly updates and a grant report upon conclusion

### 5. Does your proposal comply with our Community Code of Conduct?
Yes, this proposal complies with the [Filecoin Code of Conduct](https://github.com/filecoin-project/community/blob/master/CODE_OF_CONDUCT.md).

### 6. Links and submissions

* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?

  Yes, the Filecoin Community Showcase PR has been approved. Please check [Commuynity Showcase](https://github.com/filecoin-project/community/pull/257).

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?

  Yes, The link are as follows, [Application Filecoin Java sdk](https://github.com/filecoin-project/community/discussions/252).

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  No

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

|Name |Email|Github|Role|
|---|---|---|---|
|Jc0803kevin|jc0803kevin@163.com| ([Jc0803kevin](https://github.com/jc0803kevin)) | Main Developer |

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.

**Comment by SeedingTrees** [comment]
Thank you for this application.  Can you please provide us with additional details on the project, including how it builds on or supports the Filecoin ecosystem?

**Comment by jc0803kevin** [comment]
> Thank you for this application. Can you please provide us with additional details on the project, including how it builds on or supports the Filecoin ecosystem?

Can I continue to add a description in the current issue?

**Comment by SeedingTrees** [comment]
> Can I continue to add a description in the current issue?

Yes, please do.  That's ideal for us.

**Comment by jc0803kevin** [comment]
> > Can I continue to add a description in the current issue?
> 
> Yes, please do. That's ideal for us.

Has been updated.

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

**Comment by jc0803kevin** [comment]
Now that most of the functions have been implemented, we have entered the testing phase, but using the Java language to perform bls signatures, and now I have some problems, who can I contact for advice? Thanks!
