### ISSUE TITLE
RFP Proposal: A web-based ChainIDE for filecoin devs

### ISSUE THREAD

**Issue by BlairQu** [filecoin-project/devgrants#299]
[Grant Proposal for Filecoin&Near.docx](https://github.com/filecoin-project/devgrants/files/7028715/Grant.Proposal.for.Filecoin.Near.docx)

**Comment by SeedingTrees** [comment]
Thanks, BlairQu.  We appreciate you providing this proposal.  I believe this is in response to one of our open requests for proposals (RFPs).  We will review this according to our RFP review timeline and come back to you with thoughts.
