### ISSUE TITLE
filscan

### ISSUE THREAD

**Issue by cuimeng1027** [filecoin-project/devgrants#305]
### 6. Links and submissions

  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
  

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
  
  

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.

**Comment by SeedingTrees** [comment]
Thanks, @cuimeng1027.  We will follow up with you directly about whether it makes sense to move the Filscan projects out of the microgrants channel and into a different channel.  

Cheers,

ST
