### ISSUE TITLE
Chainlink x Filecoin RFP Proposal: Commercial Use Smart Contracts by HealthTrends.AI

### ISSUE THREAD

**Issue by calebcbrown** [filecoin-project/devgrants#330]
[Chainlink x Filecoin RFP Proposal - Commercial Use Smart Contracts by HealthTrends.AI.pdf](https://github.com/filecoin-project/devgrants/files/7189123/Chainlink.x.Filecoin.RFP.Proposal.-.Commercial.Use.Smart.Contracts.by.HealthTrends.AI.pdf)

Audio Submission: https://drive.google.com/file/d/1FI0F_ViC1h1j9NE4chi-gGdYht-qvNrW/view?usp=sharing

**Comment by realChainLife** [comment]
Hi @calebcbrown just checking on the request above. After further evaluation we're open to fund a lower scope of work at a later date, a roadmap with development phases is a recommended approach.

**Comment by calebcbrown** [comment]
Thank you @realChainLife! We are working on a proposal with a reduced scope -- is there a suggested budget we should target?

**Comment by realChainLife** [comment]
Thanks for the update @calebcbrown please propose a budget for MVP, or prototype development.

**Comment by calebcbrown** [comment]
Hello @realChainLife, we appreciate the continued review. Attached is a document describing two options for funding a reduced scope & budget that we believe will support prototype development effectively. 

[ChainlinkFilecoinUpdatedProposal.docx](https://github.com/filecoin-project/devgrants/files/7757989/ChainlinkFilecoinUpdatedProposal.docx)

**Comment by calebcbrown** [comment]
Hello @realChainLife, just checking in on the proposal - are there any updates to status or additional feedback in the works on this?

**Comment by ErinOCon** [comment]
Hi @calebcbrown, this issue has been closed. If you have outstanding questions for our team, please contact us at grants@fil.org.
