### ISSUE TITLE
Chainlink x Filecoin: RFP Proposal- KopperDAO

### ISSUE THREAD

**Issue by Islandersfan2016** [filecoin-project/devgrants#331]
Project Description- Kopper allows content creators to form a close community with their fans by putting exclusive content into IPFS files. The community of fans can vote, give tips, and watch live content from the content creators. Each content creator is their own DAO.
The content creator has the option of charging the entire community for specific content going into the IPFS file. For example: charging a community of 100 fans, $1,000 for a song put into the file. Each community member would be charged $10. Fans will also in return have voting rights within the profile to whatever questions the content creator posts. 
This project utilizes Textile’s bridge Filecoin/Polygon (low gas fees). The Unlock protocol of NFTs as tickets for profile/IPFS file access. Chainlink’s oracle (external adapter) linking the addresses of the fans to the IPFS file of the content creator. 

Brief description- Kopper allows content creators to form a close community with their fans by putting exclusive content into IPFS files. The community of fans can vote, give tips, and watch live content from the content creators. Each content creator is their own DAO.

Value to the Filecoin and Chainlink ecosystems- This project connects Chainlink’s oracle to a Filecoin file via an external adaptor. This will be a demonstration of how to monetize content within IPFS files. 

Deliverables- 1. Textile’s Bridge to Filecoin/Polygon
2.Front-End (profile creation) with link to Unlock NFT.
3.DAO Smart Contract with Chainlink External Adaptor 

An explanation of your technical solution and architecture - This project utilizes Textile’s Filecoin/Polygon bridge for lower gas fees. The Unlock protocol security NFTs are used to access the IPFS files by being purchased by users. 
A Chainlink external adapter will be used to inform the smart contract containing the addresses of the community members to charge a fee when data is entered into the IPFS file. 
Imagine that an experienced software developer will evaluate your proposal
Milestones & Funding requested (most projects have 2-4 milestones)- Milestone 1. Launch of platform with profiles of at least 100 content creators
2.Platform has atleast 1,000 content creators with over 10,000 fans. Plus, more than $2million in funding.

Budget and estimated timeframe for each milestone- The platform looks to launch by October 30, 2021 reaching milestone 1. 
We plan on paying content creators with large social media followings to join the platform for our launch. The budget of the team combined with content creators would be $70,000. 

Team- Lamont Veal, Marcel Myers

Roles and Experience- Lamont Veal is an experienced (2 years) Blockchain developer who has won a prize in the Ethglobal Hackathon with the project xLiquidity (October 2020).

Marcel Myers is a music artist and producer based in Atlanta, GA with more than 50,000 downloads of his music on Spotify. He has over 10 years of experience in social media marketing and the entertainment industry.

**Comment by realChainLife** [comment]
Hi @Islandersfan2016 could you submit your proposal using this [RFP template](https://github.com/filecoin-project/devgrants/blob/master/rfp-proposals/rfp-proposal-template.md)? This will capture more information about your project.

**Comment by Islandersfan2016** [comment]
Hello Sonia,

I will re-submit it with RFP template.

Thank you,
Lamont V.

**Comment by Islandersfan2016** [comment]
Hi Sonia,

We are still working on our Project. We have an MVP ready. Is it still
possible to submit an RFP proposal to Filecoin/Dev grants?

Thank you,
Lamont V.
