### ISSUE TITLE
Filecoin x Chainlink rfp-proposal-SAO network

### ISSUE THREAD

**Issue by Adele0x** [filecoin-project/devgrants#333]
# RFP Proposal: `SAO Network`

**Name of Project:** Storage Autonomous Organization (SAO)

**Link to RFP:** https://github.com/filecoin-project/devgrants/blob/master/rfps/chainlink-and-filecoin.md

**RFP Category:** `app-dev`, `technical-design`

**Proposer:** `Adele0x`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes

# Project Description

The project is to build a storage autonomous network of stakeholders with no central governing body, just a set of rules encoded on a blockchain. We will use the InterPlanetary File System (IPFS) to store useful data like nun-fungible tokens (NFT) on the Filecoin network. In our view, NFT protocol can be widely used in various fields especially like the right affirmation with a proper Oracle solution bridging Filecoin and other public chains or the real world. We think the internet can’t be saved appropriately as we expect personally. The way things are going, MEGACORP will always control the apps and the data service based on the internet which leads to concerns over copyrights and the abuse of the data because we can no longer own and benefit from the data solely by ourselves. The only way out of this mess is with a completely new platform that’s owned and controlled by its users. That's what we’d like to build starting from this project. It’s just like a data DAO.
 
In phase one, SAO network is designed to give NFT creators and NFT markets a single, effective, customizable, integrated productivity tool for storing useful data on their own for a certain period as expected or even permanently on a decentralized storage network like Filecoin, rather than on a central server; and it takes full advantage of the IPFS system, the oracle solutions and the latest AI recognition technologies to protect and track the copyright on any piece of painting, writing, music, etc. It will be a tool and community platform that users can trust, control, and extend to their liking. We want to do away with the terrible user experience of the current centralized apps and the data service. 

In the next step after fundraising, SAO will also run the Filecoin miner nodes to help to store the useful data and make earnings from the storage mining business. We will make the miner nodes run publicly, transparently and governed by a DAO. The proceeds of mining business will be distributed with a set of rules encoded on Ethereum, or Filecoin in the future (if Filecoin network supports smart contracts someday). The Web 3 era is coming. And also we believe the SAO network has an enormous collaborative potential that the future Metaverse world needs.

## Brief Description
The project is to build a storage autonomous network of stakeholders with no central governing body, just a set of rules encoded on a blockchain. It's a protocol tool that utilize the InterPlanetary File System (IPFS) to store the data of nun-fungible tokens (NFT) on the Filecoin network, to use the oracle solution like Chainlink to leverage extensive off-chain resources, and to make full use of the latest AI recognition technologies to protect, track and affirm the copyright on any piece of painting, writing, music, etc. 

## Value to the Filecoin and Chainlink ecosystems

The SAO network will become one of the most easy-to-use tools in the FIlecoin ecosystem. 

It will be also like a NFT search engine, including image search and voice search, and the navigation showing the NFT collection lists, and an aggregator of NFT markets for users that utilizes the blockchain technologies, AI recognition technologies and Chainlink oracle solutions to protect, track and affirm the rights on any piece of videos, paintings, writings, music, etc. 

The team also would like to try to work out a possibly better oracle solution for the Filecoin storage and rights affirmation if Chainlink Labs could provide more technology support and fund support.

Besides, the Filecoin mining DAO will also engage more people to take part in the Filecoin storage mining. At the beginning, we will provide the hardware and software solution for free and the only thing that users need to do is to stake Filecoins in the nodes. To make the mining DAO run publicly and transparently, we will use the Chainlink oracle solution to upload the mining order data on the blockchains like Ethereum. 

## Deliverables

- Launch a NFT search engine and navigation
- Store the celebrated NFTs on Filecoin and record its CID on our website
- Provide NFT data API for NFT markets
- Run at least one Filecoin miner node governed by an decentralized autonomous organization (DAO)
- Use an oracle solution to upload the mining order data on the blockchains like Ethereum.
- Upload and verify the copyright data by the DAO and track the transaction records on blockchain.

## An explanation of your technical solution and architecture

Firstly, the user interface is to provide a search engine and navigation product showing the NFT collection lists, the details of NFT and the storage sites by the MYSQL database adoption and data API requests. 

And then the platform provides a one-stop aggregator for users to mint/generate/create the NFTs on various marketplaces or different blockchains by the means of cooperation with NFT markets and public blockchains.

With regard to the Filecoin mining decentralized autonomous organization, we want to engage more users participating in the Filecoin ecosystem and support the continuous operation of the platform working as a DAO. We have not decided the final solution of the DApp while the smart contracts are not available on the Filecoin chain. So maybe we will deploy the DApp on Ethereum and use the oracle solution to upload the mining order data between Filecoin and Ethereum.

## Milestones

- Launch a NFT search engine/navigation
- Launch a publicly, transparently, and jointly FIL-mining DApp governed by a DAO.
- Launch an aggregator of NFT markets for user’s better experience on minting NFTs
- Initiate a Data DAO for Web 3 and Metaverse world using the blockchain technologies, oracle solutions, token economy model,  and AI recognition technologies, etc.

## Budget and estimated timeframe for each milestone
|Milestones| Cost Items|Budget Amount|Estimated Release Date|
|:----|:----|:----|:----|
|Launch a NFT search engine/navigation|Cloud Server; Cost of Development|$15,000|Early in October 2021| 
|Launch a publicly, transparently, and jointly FIL-mining DApp governed by a DAO.|Filecoin miner hardware, $70,000; Filecoin mining software development, $10,000; Incentive Mechanism Design of the DAO, $5,000|$85,000|Early in November 2021| 
|Launch an aggregator of NFT markets for user’s better experience on minting NFTs|Cost of Development; Cost of business development for requesting application program interface from the major NFT markets.|$20,000|Late in December 2021| 
|Initiate a Data DAO for Web 3 and Metaverse world using the blockchain technologies, oracle solutions, token economy model, and AI recognition technologies, etc.|TBD|TBD|Q1 2022| 

Sum up the total requested budget across all milestones, and include that figure here. Ensure that it does not exceed the total funding limit on the RFP.

# Team

## Contact Info

- Github: https://github.com/SaoNetwork
- Contact email: adele@sao.network
- Github username:`Adele0x`

## Team Members

- Nick, Chief Software Architect 
Prior to Blockinsight, Nick used to be the technical director of a celebrated mining Pool. Nick is extensively experienced in blockchain and cryptocurrency mining. Expert in architecture design, smart contract deployment, blockchain development and multiple programming languages.

- Leo, Filecoin Expert
4yrs blockchain experiences in public chain, crypto wallet and mining. Actively involved in filecoin ecosystem and  decentralised storage area for more than 1yr.

- Adele, Project Manager
Adele is a passionate project manager who has worked extensively in both financial sections and blockchain industry. Prior to Blockinsight, she worked for several organizations including a investing group with multi-natinal business, financial consulting firms and a crypto mining R&D company. And she will take in charge of the manager of this project  “Storage Autonomous Organization” (SAO). 

## Team Website

Github: https://github.com/SaoNetwork

The website is to be online soon in one week.

## Additional Information of Team

The team consists of 3 full-time people and several part-timers who all have rich experience in Blockchain and IPFS and are keenly interested in this project. All the team members would like to be a part as well as make contributions to this project at the very beginning. After fundraising, we are planning to form an official team, and to hire more developers from the Filecoin developer community and business managers to reach out for more storage clients.

**Comment by Adele0x** [comment]
Hello PL team and FF team, we just happen to have some exciting ideas on distributed storage and oracle solution, and we have already started some developments on the project (https://github.com/SaoNetwork).

Thanks in advance for reviewing the proposal and we are looking forward to your reply and some advice on the project. If any problem, you can also contact me via email: adele@sao.network

Best Regards,  
Adele

**Comment by Adele0x** [comment]
@realChainLife Hi hi Sonia, I just wanna confirm with you that if I submit the RFP proposal in the right way?

**Comment by realChainLife** [comment]
Hi @Adele0x we received this as a [PR](https://github.com/filecoin-project/devgrants/pull/332) as well, so I'll close this issue and we can continue discussion on the PR.

**Comment by Adele0x** [comment]
> Hi @Adele0x we received this as a [PR](https://github.com/filecoin-project/devgrants/pull/332) as well, so I'll close this issue and we can continue discussion on the PR.

OK thanks!
