### ISSUE TITLE
Next Step Microgrant: JobCrypt

### ISSUE THREAD

**Issue by cryptotwilight** [filecoin-project/devgrants#340]
### 1. What is your project? (max 100 words)

This project is to create a jobsite, that utilises Ipfs for data storage. The project enables users to post their jobs using cryptocurrency, with jobseekers paying for value add features using cryptocurrency only. The focus of the site is purely blockchain project related jobs. The project was a winner of the Filecoin Pool prize for Browsers 3000

https://github.com/cryptotwilight/jobcrypt

  

https://ancient-glade-5009.on.fleek.co/ui/

### 2. How are you planning to improve this project? (max 200 words)

The next steps will be to 
1. Complete the links to IPFS
2. Evaluate performance and possible use of OrbitDB 
3. Review monitoring tools and requirements for LIVE support on mainnet.
4. Prepare for external code audit

 
### 3. Will the work be Open Source?

Yes

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

Yes
  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
  
No

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
  
  
Yes

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://devpost.com/software/cryptopartage

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? Browsers3000
  * 
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.
  https://devpost.com/software/cryptopartage

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

**Comment by SeedingTrees** [comment]
Can you please reply with the email addresses of your team members so that we can send instructions for receiving your grant?

**Comment by cryptotwilight** [comment]
Hello

Thank you so much for this, the team is just myself email address
***@***.***

Please see below for our new discord
https://discord.gg/2pAWVtYj

Thank you

Tony

**Comment by SeedingTrees** [comment]
Thanks, Tony.  It looks like Github stripped your email address.  Would you mind adding an email address to your Github profile and alerting me once you've done so?  I'll email you directly using that email.

**Comment by cryptotwilight** [comment]
Hello

All done https://github.com/cryptotwilight/jobcrypt

Thank you

Tony

**Comment by SeedingTrees** [comment]
Thanks, Tony.  I'm not seeing your email address at that link or in your profile.  Can you try editing the original comment in this issue to add in your email address?

**Comment by cryptotwilight** [comment]
Hello this is the email it's in the About box on the page **jobcrypt at blockstarlogic.com**

**Comment by cryptotwilight** [comment]
New UI work is now underway, our goal is to get an MVP available for the end of November

**Comment by cryptotwilight** [comment]
https://www.jobcrypt.com
