### ISSUE TITLE
Next Step Microgrant:  Project MyWorld (myw.art)

### ISSUE THREAD

**Issue by NguyenIvan** [filecoin-project/devgrants#342]
### 1. What is your project? (max 100 words)

MyWorld is a common place for autism artists to express their world through arts, music and their weird experiments. They can sell and exchange their work via smart contracts. A small fee from those buying and selling is contributed to autism awareness activities; those activities in turn are proposed and voted by means of token distribution in the community. All those beautiful things happened thanks to the greatness of Flow blockchain network, NFT.storage API and IPFS storage space.

Github repo: https://github.com/NguyenIvan/MyWorld
  

Project website: [myw.art](https://myw.art)

### 2. How are you planning to improve this project? (max 200 words)

1. Further improve cadence smart contracts to handle: 
- Decentralize Transaction
- Transaction Fees 
- Multiple Galleries - Stored in MongoDB
- Autism Community Vault to receive a portion of transaction fees

2. Unit tests for cadence smart contracts
3. Unit tests for the front end.
4. MyW token implementing NonFungibleToken. MyW will be used in transactions instead of FUSD as of now.
5. Fresh new 100 installations of blocto wallet in the autism community and distribute an initial amount of MyW tokens to those wallets so that they can start trading on testnet. 
6. Autism Artists profile page to tell their stories.
 
### 3. Will the work be Open Source?

Like many other projects that welcome community contribution, our project is also Open Source under MIT license.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

We will keep you updated with a weekly report so that we can be in sync.
  
### 5. Does your proposal comply with our Community Code of Conduct?

I have read and found the code of conduct quite interesting and informative. Rest assured that the project will be developed in compliance with it.

### 6. Links and submissions

  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
  

Link: https://github.com/filecoin-project/community/pull/308

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
  
  

Link: https://github.com/filecoin-project/community/discussions/307

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Nwin Lee
Email: a.mac@qhoach.com
GitHub: https://github.com/NguyenIvan
Role: Coder

Lynda P. 
Email: na.le@qhoach.com
Role: Community Manager

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission, proving you're a team that submitted for a Protocol Labs prize.

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
