### ISSUE TITLE
IPFS Research Project: Socio-technical Resilience in IPFS

### ISSUE THREAD

**Issue by kelsien** [filecoin-project/devgrants#353]
# Open Grant Proposal: `Socio-technical Resilience in IPFS'

**Socio-technical Resilience in IPFS**

**Proposal Category:** 'Qualitative research'

**Proposer:** `kelsien'

**Sponsor:** `Dietrich Ayala (PL)'

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** 'Yes'

# Project Description

## Research Problem 
It is necessary to understand the social contexts and vulnerabilities of the users of IPFS  network to inform both users and the PL team and enhance the resilience of the network.  

By surfacing “real-world” circumstances in which the network is being used, we can better  understand the needs, vulnerabilities, and threats to users of the network, and improve the  functioning and communication of the network in relation to user needs.  

## Research Process to address the problem

This research will function as a feedback loop to Protocol Labs teams, to contribute to a holistic perspective of possible and likely vulnerabilities and attacks on the network, as an input to improve protocol resilience by investigating the contexts in which the network is used.

The research methodology is ethnographic. Ethnography is the study and communication of  people. Ethnographers search for patterns in the lived human experiences by carefully  observing and participating in the lives of those participating in the study. The data  collection methods used are ethnographic interviews and digital ethnography (observation of  online channels). The advantage of ethnography is that it can provide rich, cultural insights  that are otherwise invisible to offer a feedback loop on the use of digital infrastructure. The  ethics approval for this research project is under the PhD project “Resilience in Decentralised  Technologies”. 

The research question that will guide the sociological phase of the research project is: What  does resilience mean in the context of specific user communities of the IPFS network?  

The aim of this research is to ground PL ecosystem workstreams in the context of user safety,  to better understand the threats, needs, and expectations of IPFS users.  

Applications of the research may include informing the language used to communicate the  risks and benefits of IPFS to end users to set an informed and realistic understanding of the  uses and limitations of the network, inform use-cases and threat modelling when developing  standards at W3C and IETF, and provide a grounded evidence basis to inform decision  making by application developers and service providers building on top of IPFS protocol. A  secondary benefit is to inform the technical work of ResnetLabs and governance research. 

## Value
1. Inform the language used to communicate the risks and benefits of IPFS to end users to set an informed and realistic understanding of the uses and limitations of the network.
2. Inform the use-cases and threat model when developing standards at W3C and IETF.
3. Provide a grounded evidence basis to inform decision making by application developers and service providers building on top of IPFS protocol.

The benefits to Protocol Labs and IPFS user communities of conducting this research are significant in terms of product development, UX, communications, and product-user fit. This research generates an iterative feedback loop between product development and user communities, to better understand the contexts and needs of those looking for decentralised content addressing and storage solutions. 

Assumptions and limitations: 

* a. Access to mutually agreed user communities will be possible. 
* b. Conducting research interviews with stakeholders identified will not cause risk to  either the researcher or research participants. If this is deemed a risk under research  ethics, the researcher reserves the right to not pursue an interview. 
* c. Relevant stakeholders will be available in a timely manner for research interviews. d. Research will be conducted remotely, via online ethnographic interviews and digital  ethnography. 
* e. The designated Protocol Labs contacts will be available in a timely manner for  research interviews, feedback, and project logistics.  
* f. Project timelines are estimates only.  

## Deliverables

Output: A research report and summary of findings which explores at lease two “real world” case studies to surface user needs, vulnerabilities, and threats. Desktop research methods will be adopted, with ethnographic interviews where access is appropriate and possible. See a breakdown of deliverables below.

## Development Roadmap

1. Preparation stage:  

* Problem formation in conjunction with the appropriate Protocol Labs (PL) team  member/s. 
* Selecting the research setting in conjunction with PL to ascertain: 
  - 1 relevant user community IPFS network use case, based on significant initial  perceived threat and need for resilience. 
  - 1 relevant generalisable IPFS network use case. 
* Listing relevant stakeholders for interview with PL. 
* Listing relevant online channels for digital ethnographic observation with PL.
  * Resilience mapping exercise: listing all known vulnerabilities in IPFS at network &  UX level.  
* Introductions where possible from PL to gain access to the appropriate research  participants.  

2. Data Collection:

Gathering and recording information.

• Ethnographic interviews (approximately 10, as guided by access and needs during the  data collection process), and 
• Digital ethnography (observation of online channels), internal and external to PL,  such as Slack, Telegram, Discord, etc. 

Semi-regular (fortnightly) calls with PL are anticipated throughout this period.

3. Analysis: 

An ethnographer collects data in multiple ways for triangulation over an extended period to  provide deep insights into community behaviours. The process is inductive, holistic, and  reflexive. Finally, the ethnographer analyses the data to surface interpretations and  conclusions. This is often tested in conjunction with research participants in the form of blogs  or conversations which give the opportunity for research participants to provide comments or  feedback to refine research findings and comply with ethical requirements. 

4. Findings: 
Surface and write up findings in the format of the key deliverables (see below).

## Research Deliverables: 

Milestone based. Scope to be developed and refined in conjunction with the priorities of the  Protocol Labs team. 
* a. 1 x Mini literature review to define and explain key concepts that guide the  research 
* b. 1 x Blog on key themes surfaced. (20k)
* c. 1 x Full research report and findings, towards informing protocol standards  and academic publication. (20k)
* d. 1 x 2 hour workshop with relevant PL team members (ecosystem team with  ResnetLabs optional) to communicate research findings and identify any  further research needs. (20k)
* e. Review research and communications priorities for year 2 of the Fellowship, including possible technical collaborations. 

## Proposed timelines:  

September, 2021. 
Preparation phase 
Deliverable a.

October – March, 2021. 
Data collection phase. 

April, 2021. 
Analysis phase. 
Deliverable b. 

June, 2022. 
Findings phase. 
Deliverable c & d. Review. 

A 10-month project timeline for the deliverables outlines is anticipated, with considerations  for end-of-year breaks with accessing research participants for interviews and pending the  assumptions and limitations listed. The timeline and scope of the project may be  reviewed upon agreement of PL and the Researcher to include other activities, such as  involvement in standards body working groups, or other communication and presentation  efforts.

## Total Budget Requested

1 x PhD Fellowship equivalent of $60,000 in FIL. 

## Maintenance and Upgrade Plans

The proposed final step of the project plan is to review research and communications priorities for a year 2 of the Fellowship, including possible technical collaborations (such as ongoing research, advocacy to relevant standards organisations, continuing to develop out research findings and publish as papers, and data science based network resilience modelling). 

# Team

## Team Members:
Kelsie Nabben

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/kelsien/

## Team Website

Website: https://rmit.academia.edu/KelsieNabben/Papers 
Blog: https://kelsienabben.substack.com/

## Relevant Experience

Researcher Profile: Kelsie Nabben, Researcher/Project Manager, RMIT University 
Blockchain Innovation Hub / Digital Ethnography Research Centre / Centre of Excellence for  Automated Decision-Making & Society 

Kelsie’s research focuses on resilience in socio-technical systems. As an ethnographic  researcher, she is interested in understanding the contexts, uses, and social outcomes of  decentralised technologies and the governance of these systems to ensure resilience. 

Kelsie has worked in internationally renowned blockchain projects, including OmiseGO and  Ethereum Foundation, and consults to government and the private sector on the development  of socio-technical systems. She is a research collaborator with the Blockscience Computer Aided Governance research team and Govbase at Metagov.org. She is also a Board Member of Blockchain Australia.  

## Team code repositories

See links above to publications.

**Comment by realChainLife** [comment]
Hi @kelsien thank you for this proposal. We would like to fund this work, please email devgrants@fil.org so we can discuss next steps.
