### ISSUE TITLE
Next Step Microgrant: 3D puzzle game (LOSSST)

### ISSUE THREAD

**Issue by xem** [filecoin-project/devgrants#359]
### 1. What is your project? (max 100 words)

LOSSST is a puzzle game I developed for a game jam in september.
In this game, the players control a little snake and go through a series of puzzles where they need to reproduce a pattern with the snake's body. Many worlds and different mechanics are here to make the challenge harder when they progress into the game.

Repo: https://github.com/xem/js13k21
  
Demo: https://js13kgames.com/entries/lossst-a-snake-in-space

### 2. How are you planning to improve this project? (max 200 words)

I want to implement many decentralized features in the game, possibly entirely in Filecoin, such as:
- Custom puzzle creation / sharing
- Custom skins creation / sharing
- Leaderboards
- E-shop (to buy in-game credits, exclusive puzzles, exclusive skins, etc)
 
### 3. Will the work be Open Source?
MIT

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions
  
* Have you submitted to the Filecoin Community Showcase
Yes https://github.com/filecoin-project/community/pull/350

* Have you created a thread introducing your project in the community discussion board's ?
Yes https://github.com/filecoin-project/community/discussions/351

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
- Maxime, maxime.euziere[at]gmail.com, @xem on Github, developer
 
* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
  JS13kGames

  * Please link to your hackathon submission
  https://js13kgames.com/entries/lossst-a-snake-in-space

**Comment by SeedingTrees** [comment]
Thank you for this application.  Since the prototype isn’t built yet, can you add an additional paragraph with more details on your software architecture?  Please include in that paragraph details on your IPFS pinning service.  If you have not yet picked a pinning service, we are happy to discuss this with you.

**Comment by xem** [comment]
@SeedingTrees Hi, thank you for your message!
I'd like to implement many decentralized features around my game indeed,
but I'm a beginner in this domain and I'm not exactly sure how to: store files, save people's high scores and perform FIL transactions.
If I understood correctly, all these features require an IPFS pinning service.
During the game jam, last september, I hosted a IPFS node on my own PC to store files.
For the next steps, I'd like your help/advice to pick a "real" pinning service. is there a list of such services? :)

**Comment by SeedingTrees** [comment]
Thanks, xem.  Our dev support team hosts office hours every Thursday to answer questions just like this.  We host two different office hours to support folks working in different time zones.  You can find the links below to the Gather Town office hours events.  Please let me know if you have any issues using these links.  

[Every Thursday at 9am ET](https://gather.town/invite?token=V1fATx6H)
[Every Thursday at 1pm ET](https://gather.town/invite?token=V1fATx6H)

**Comment by xem** [comment]
Great, thank you! I'll be there at 1PM ET next Thursday

**Comment by SeedingTrees** [comment]
Sounds great, Xem.  FYI - I just received a cancelation for at least one of the calls this week.  I think it is because Thursday is a holiday in the U.S.  You may want to plan to dial in next week rather than this week.

**Comment by xem** [comment]
Sure, I'll be there thursday 18th then. Thanks!

**Comment by SeedingTrees** [comment]
Hi, Xem.  Hopefully, the office hours meeting was helpful.  Please update us here after you make progress on the pinning service.  We can revisit your microgrant application then.

**Comment by ErinOCon** [comment]
@xem, I hope you are doing well! Do you have new progress updates available?

**Comment by xem** [comment]
Hi @ErinOCon , I'm sorry, I haven't had the chance / time to learn how use a pinning service.
I kinda hoped that the microgrant, if I earned one, would give me the means to get started.

**Comment by ErinOCon** [comment]
Hi @xem, We have approved this grant! Look out for an email to submit payment details. In regards to a pinning service, we would recommend checking out [Piñata](https://docs.ipfs.io/concepts/persistence/#pinning-services).

**Comment by xem** [comment]
Hello @ErinOCon, thank you for your message, I'm checking out Piñata!
I received my grant today, thank you very much (you and the people who made it possible) ! 
What's the best way to keep you posted about my ongoing implementation of the FIL protocol inside my game? Is Twitter OK, or should I post it on Github, Discord or by mail?
Thanks,
Maxime
