### ISSUE TITLE
Open Grant Proposal: Exorde

### ISSUE THREAD

**Issue by MathiasExorde** [filecoin-project/devgrants#373]
# Open Grant Proposal: `Exorde - Understanding Information differently`

**Name of Project:** Exorde

**Proposal Category:** app-dev

**Proposer:** `Mathias Dail (CTO @ Exorde Labs)`

**(Optional) Technical Sponsor:** `Zixuan (ZX) Zhang`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes

# Project Description

Exorde is a platform designed to contribute to the fight against misinformation, by capturing how information circulates on the Web, across all news articles, social media, and websites. Exorde exists to be web-scale and fully international. It aims to be a next-generation platform, provably neutral and transparent, offering a novel way to explore the Web, its information flows, and trends.

Facebook, for example, has increased its efforts to combat fake news, by employing human fact-checkers in combination with artificial intelligence systems. Even though the vast majority of Facebook’s efforts against fake news are powered by artificial intelligence, those fact-checkers, providing the necessary human touch to reviewing fake news, are overwhelmed with the amount of data flooding the social-medial giant’s platform. The issue of leveraging information and doing online virality analysis is a global challenge. Therefore, we believe that it can only be tackled by a global approach that goes beyond the reach of individual social networks or media platforms. Fighting misinformation is the end goal, but Exorde is designed to reach a broader target audience. Exorde has use-cases for journalists, political campaigns, traders, investors, social media platforms, and organizations. Exorde will sell trust scores on information online, as well as data services for individuals and businesses. 

Exorde aims for a scalable and neutral coverage of the Web, enabled by the decentralized (and therefore distributed) use of NLP technology by its contributors (scraping, indexing, and connecting information across the Web) at a large scale. The neutrality behind Exorde’s services and trust scores is enabled by both its heterogeneous community of users (international user base with a diversity of incentives and interests), and the blockchain technology it relies on (the work, systems, and trust scores are transparent and auditable at all times). Exorde is built on recent components (smart contracts, token-based incentives, NLP, Web3 protocols, decentralized storage) explaining why such a platform could not be possible before (NLP became scalable with transfer-learning in 2018-2019, scalable blockchain platforms after 2018, and decentralized storage networks such as Filecoin. 

Exorde is will provide an easy way to find the source of a piece of information (video, text, statement, etc.), look for what is currently viral, how trending information is circulating and where (on which networks such as Facebook, Reddit, Twitter, etc.). By leveraging state-of-the-art AI, transparent ledger technology, and a cross-lingual community, we believe Exorde can empower the fight against misinformation online.

## Value

In the last years, the industry has seen the emergence of indexing platforms, serving as a decentralized API infrastructure for querying easily the information existing in blockchains to serve it to web applications. There are new kinds of information retrieval needs that are not matched by current major applications, due to the fundamental complexity and volatile nature of this information. There is an empty spot in the market for a Web-based Data curation and indexing platform. This is where Exorde aims to shine, as it aims to serve a clear purpose in the Web and blockchain ecosystem by leveraging the security and global availability of the Filecoin storage network. 

The knowledge composing the core of the Exorde platform is expected to grow, by capturing increasing parts of the data market. The more its content grows, the more value will be created by the platform, impacting the value and emergence of new data services around it.  Getting Exorde right will benefit the entire crypto ecosystem, by providing a new, impactful use case for Internet users that is not related to current trends in crypto (DeFi, NFT marketplaces, etc.). The best-case scenario is that Exorde manages to capture a part of the untapped information/fake news data market, creating a new information-related ecosystem.

Exorde being a success will be a benefit for the Filecoin ecosystem, as Exorde's philosophy is directly aligned with Filecoin's: to store humanity's most important information, on secure and censorship-resistant storage. In Exorde's case, this information is knowledge about Web2, about viral content, news articles, their sources, etc. In the future, Exorde Data being successfully adopted can only increase the importance and role of Filecoin, as a long-lasting digital institution of the Internet. 

If Exorde fails, then the risk is minimal. The best-case scenario is that our work and approach will serve as the foundation for future information-related projects. 
To this day, no other projects had tried this cross-disciplinary approach to efficiently monitor information flows online, to fight misinformation, by combining community-based distributed work, AI, and decentralized databases. The novelty behind Exorde's concept is high, and this is where comes the difficulty to execute the project: it attempts to tie multiple recent technologies. Indeed, Exorde attempts to leverage NLP for automated text analysis, decentralized storage networks & databases, scalable blockchain for multi-agent coordination, and flexible decentralized organization for efficient governance and economical incentives management.

## Deliverables

Exorde will deliver 3 apps in the medium term, in the following order:

**1.  Virality App for Traders**: customizable alerts, statistics on financial-related information. Users will be able to select specific themes, topics or keywords to be monitored by Exorde Virality systems, to have real-time alerts in case virality is detected (hyped event, mass communication, a sharp increase of a topic (stock, crypto, project, etc.) being mentioned on social media in a short time frame (minutes, hours, days, etc.). This will be a desktop & mobile progressive web app.

**2.  Information Explore App for Organizations**: analysis of information flows and propagation, to analyze and prepare a communication strategy, extract statistics about specific themes: topics, trends. E.g. vaccine rollouts, fake news propagation, etc. This app will be a scaled version of the Virality App, enabled by more long-term trends analysis and latent information propagation capture thanks to a more sophisticated data science pipeline and larger contributor's community. This will be a desktop & mobile progressive web app.

**3. Trust scores APIs**: request-response service, served by Exorde Lab's high-performance APIs or by Exorde's decentralized APIs. These APIs will output a set of metadata indicating the reliability, sources, and relevant information related to a given URL (website, article, news post, tweet, etc.). This will be an API-based service.

## Development Roadmap

Exorde will build its platform and complete set of services in 3 phases:

1. Q3 2021 – Q2 2022 - **Phase 1**:  - $15000 of requested funding 

**Virality prediction**. In this early phase, we are building the core components of Exorde: the distributed data processes and pipelines. The internal mechanisms to process data, store it on Exorde’s knowledge database and the first Application.

Exorde Explore: the first application of Exorde, an online (mobile & PC) platform to alert users on customized topics, subjects, or websites. This application will be able to give alerts as soon as new viral content is spotted online (across any source: social media, news articles, blog, RSS news feed). The application will start with the English language and move on to become multilingual over the following months.

2. Q2 2022 – Q1 2023 - **Phase 2**:  - $20000 of requested funding 

 **Global trend analysis**. In this phase, we grow the scalability of the approach of Phase 1, by adding new sources in the data, by growing our community and therefore our contributing userbase. We will offer new services in the Exorde Explore, for organizations or individuals, to track, analyze and get insights on any topic online, whether they are viral or not. In this phase, we grow the coverage of the Web done by Exorde, and improve on the management of its data archives to produce latent insights over time: long-term trends, information flows patterns across platforms, historization of mediatic events.

This phase is where Exorde matures and gets more aware of the behavior of information sources online: what gets posted (e.g., which newspaper), how it gets relayed, by which entities or groups of sources. Here, the reputation and history (list of information) of all websites get recorded to provide a record of information-related events, enabling Exorde to build advanced data analytics applications while providing detailed transparency about the Web to users.

3. Starting 2023 - **Phase 3: Trust scores**.  - $40000 of requested funding 

This is the **last stage for Exorde**, which will only keep improving on itself in the following years. In Phase 3, Exorde has a large and sufficient coverage of the Web, with the associated memory of events, information flows, and patterns recorded by its community on the Web (in multiple languages). With enough historization and accurate monitoring, Exorde can reach its end goal: trust scores for data sources (websites, newspapers, publishers, blogs) and information (tweets, articles, topics), giving Web users a novel knowledge and context on any piece of information they encounter online. Not only will they be able to have a clear score, simple to understand, to apprehend anything they encounter online, but they will have the possibility to assess the methodology producing these scores.

Research has shown that users are not likely to fact-check their information and do any additional efforts to look for the source or credibility of the information or fact that they are consuming. While Web users are aware of the problem of misinformation, an effortless and frictionless solution has to be proposed if the problem is to be solved. 

**Detailed work implementation plan:**

Activity name | Description | Planned duration | Expected output
-- | -- | -- | --
Core work system | Core data processing   pipeline | 4 months | A constant stream of   data feeding Exorde’s database
Database setup | Setting up Exorde’s public,   distributed, scalable, and resilient database | 2 months | A public, working database capable of handling the data from the output of Exorde’s systems.
First application | The first application to provide virality alerts & basic insights to users, on selected topics about information circulation online. | 4 months | An application on mobile and PC. (progressive app)
Contributing platform   v1 | A contributing platform for   contributors to monitor and participate in the collaborative work | 6 months | A modern web interface on  Exorde’s website
Governance interface | An interface for   contributors to govern the different parameters of the systems | 8 months | A web interface, and a   governing backend infrastructure
Detailed archiving   & historization | Store the full history of all events that were captured by Exorde in its database: sources, information flows, trending topics, viral clusters of information. | 1 year | A complex data storage process   and a querying tool
Reputation system | Build a relevant reputation system for both contributors and sources of information being indexed by Exorde. The reputation system will strengthen the security of the platform   and its relevance for the Web | 1.5 years | A reputation system   for all Exorde’s data sources & users

There are 3 engineers in the core development team, working full time on each of the milestones.  
There are no expected barriers or risks related to the milestones, the technology, the
team’s skills, and the objectives that have been described above.

## Total Budget Requested

Cost category	| Budget | Description, and justification
-- | -- | -- 
[A] Direct personnel costs  |  $65000	| 3 Engineers working full time to develop and deploy the project technological architecture and the different apps for its clients & users. 
Then the team will develop and publish base NLP modules, the web platform (both backend and frontend where clients will interact with Exorde), and the contributors’ APIs and interfaces.	
Direct costs	| $10000	| Website & servers’ costs. Web platform & contributors’ infrastructure hosting
Indirect costs 		
TOTAL 	|  $75000

## Maintenance and Upgrade Plans

There will be a continuous improvement of our Data Science and Web scraping modules, to improve Exorde's coverage of the Web, to make it more real-time and more relevant.
There will also be more Apps after the 3 main phases listed above, which will initially be directed towards Exorde Contributors. We will initially propose a dashboard to follow stats and other information on the work being performed collectively on Exorde decentralized systems, then other web explorers to visualize Exorde's Data on Filecoin, its internal trends, etc.
Exorde is designed to be a long-lasting project, with a long-term vision with regards to its data, its longevity, and its decentralized community.

In the future, when the Exorde project becomes mature and well-integrated in the crypto and Filecoin ecosystem, we will move on to develop more specific news-related apps on top of the entire Exorde/Filecoin architecture. This will be defined during discussions with the community during the next 5 years, in order to create the most valuable applications with regards to the Exorde Protocol.

# Team

## Team Members

Applicant’s team:

Name of Team Member| Role in the  project | LinkedIn/ personal   profile | Key areas of    expertise
-- | -- | -- | --
Terence Gras  | CEO: Vision, big   picture, pitching the project, handling contacts & business | https://www.linkedin.com/in/t%C3%A9rencegras/ | Software    & Computer vision   engineer,
Mathias Dail  | CTO: Technology architecture. NLP   engineering, data science & backend development. | https://www.linkedin.com/in/mathias-dail-1311ab13a/ | Data scientist, distributed   system engineer
Damien Pucheu  | COO: Product lead. Web platform developer. Web | https://www.linkedin.com/in/damien-pucheu/ | Web development,   software engineering Web design

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/t%C3%A9rencegras/
https://www.linkedin.com/in/mathias-dail-1311ab13a/
https://www.linkedin.com/in/damien-pucheu/

## Team Website

**Exorde's Website**: https://exorde.network/

## Relevant Experience

The current team is composed of 3 founding members: Terence, Mathias & Damien. All core founders come from an engineering background with very complementary specializations. Our team has skills in distributed & advanced systems, NLP and machine learning, and web platform development:

•	**Terence Gras**: has 5+ years of experience in multiple industries (large automotive industry, video game industry, computer vision) and has all the experience and knowledge to lead the project, secure our long-term goals, and make sure Exorde stays true to its original vision.

•	**Mathias Dail**: has a full software engineering background, specialized in complex & intelligent systems. 4+ years of experience with Data Science with a strong focus on NLP, with some experience in AI Research. He also has 2+ years of experience in distributed systems, data engineering pipelines, and distributed ledger technologies. 

•	**Damien Pucheu**: has a full software engineering background, with a solid experience of 4+ years in entrepreneurship. He has worked in different industries and has a broad knowledge of Web2 and Web3 technologies. He is fully capable of developing and leading any modern web-based platform.

The team has gotten together organically, as our skills complemented each other. We are covering all the technological pillars necessary to build Exorde including AI (NLP), Web technologies, Data pipelines, and distributed architectures. 

## Team code repositories

No code repositories are available yet.

# Additional Information

Exorde Labs is part of the Outlier Ventures Filecoin Basecamp program of 2021.

**Comment by realChainLife** [comment]
Hi @MathiasExorde Touching base here to hopefully learn if your development roadmap has changed since you submitted this application, and completed your participation at the Outlier Basecamp. We'd be happy to review an updated proposal that reflects the roasmpa you have for this exorde in 2022. You can email devgrants@fil.org to arrange a call if that works for you. I'll close this for now and reopen, if we want to make updates here.
