### ISSUE TITLE
RFP Proposal: A new Web3 application based on Filecoin and NEAR Ecology

### ISSUE THREAD

**Issue by lk2684753** [filecoin-project/devgrants#375]
**Name of Project**:NEAR storage Web3 application

**Link to RFP:** https://github.com/filecoin-project/devgrants/blob/master/rfps/near-and-filecoin.md

**RFP Category:**  app-dev

**Proposer:** `lk2684753`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** "Yes"

## Project Description

​      We plan to develop a new Web3 application based on Filecoin and NEAR Ecology;

Based on NEAR public chain, combined with distributed storage technology IPFS and Filecoin, data is stored hot and cold.

Develop smart contracts using Rust language on NEAR, where users can select miners for data trading;

Users can pay for their own storage by paying NEAR without having to pay Fil for data storage;

Users can pay a small single fee to store their hot data on the IPFS network; In terms of cold data storage, pay NEAR to store data on Filecoin network according to storage miner quote, file size, storage cycle, etc.

NEAR contract records the order information of hot data and cold data storage on the chain, such as viewing file storage time, file hash value, storage users, file storage life cycle, storage order amount, status, data encapsulation and other information.

Applications that allow users to store encrypted data on Filecoin can only be decrypted by the user using the NEAR private key, thus maintaining ownership of their data;

In addition, we plan to provide free storage at the early stage, and users only need to pledge a small amount of NEAR to do contract storage transaction costs. First, to verify the stability of the new Web3 application, second, to attract more people to join us, and third, we have our own storage miner node. We need a large amount of real data storage to replace the 0 data encapsulated in the sector to improve the node computing power.

## Value to the Filecoin and NEAR ecosystems

​        [NEAR](https://near.org/) is a decentralized application platform built to bridge the users of today’s Internet to the blockchain-based web of the future. NEAR is a PoS Layer 1 blockchain platform, built with UX and DevX in mind. NEAR’s novel sharding mechanism, Nightshade, parallelizes computation on chain and automatically increases capacity when needed, resulting in theoretically infinite scalability.

​       [Filecoin](https://filecoin.io/) is a decentralized peer-to-peer storage network, allowing anyone to store and validate large-scale data as part of a global, 8-exabyte (and growing) network. Under the hood, all Filecoin nodes use the InterPlanetary File System (IPFS), a content-addressed protocol for storing and sharing data.

​         We find that currently there are no high-impact storage projects in the NEAR ecosystem, and new Web3 applications can change that; Let more developers and enthusiasts pay attention to NEAR ecology and participate in it to jointly build the ecological prosperity of the community;

On the Filecoin ecosystem, we've been following community dynamics, participating in the XMINER program, and making suggestions on community Slack. We will try to build our new Web3 application using tools and services such as Web3. storage, Filcosin-Near Bridge, etc. We have our own storage miner node, and we need more real data to be stored in our node; It's not just us, of course. I'm sure there are a lot of storage miners out there who would like to have more real data to replace the zero data and fulfill Filecoin's vision.

At the same time, during the development process, we will actively communicate with the NEAR&Filecoin community members, feedback the NEAR&Filecoin community members provide development SDK problems encountered; We believe that community members will be happy to receive our feedback; We believe that in the future the NEAR&Filecoin community will become ecologically diverse due to the continuous efforts of developers like us;

## Deliverables

The results we will deliver are:

A new Web3 storage application website and project description;

A decentralized identity (DID) system generated through NEAR accounts;

A simple, convenient and beautiful NEAR storage interface website;

A custom selectable hot storage data interface;

A cold data storage interface;

An interactive interface for querying storage information;

Multiple NEAR contracts to record relevant important information stored in files;

Multiple code test cases;  

## Development Roadmap

Milestones:

- M1 (Week 1 to 2) 3 developers
  - Requirements finalization
  - Web UI interface design
  - Hot data storage related development(SDK - Integrating&Contract development )	
  - Related functional tests
  - Budget requested: $15,000

- M2 (Week 4)3 developers 
  - Web3 storage program front-end interface interactive function development
  - Integration of DID digital identity systems
  - Hot data storage related development(SDK - Integrating&Contract development )
  - File storage data query related function development
  - Related functional tests
  - Budget requested: $25,000
- M3 (Week 5 to 6) 3 developers
  - Hot data storage node selection function
  - Cold data storage node selection function (supports custom storage miner node storage)
  - Budget requested: $15,000
- M3 (Week 7 to 8) 3 developers
  - Regression testing
  - Bug fixes and Improvements
  - Deploying Demo Application
  - Budget requested: $15,000

## Total Budget Requested

$70,000

## Maintenance and Upgrade Plans

we will responsible to coordinate the continuous maintenance of the web3 storage application components developed within the project, preserving at the same time their stability in terms of interface and behavior, so that higher-level frameworks and applications can rely on them.;

We will add storage hardware and IPFS storage nodes to ensure high availability of services. In terms of storage for miners, we can provide at least 50P storage space in the later stage to meet various storage needs.

We guarantee continuous maintenance and development for at least two years;

### Contact Info

`lk2684753@163.com`

### Team Members

- Liangkai

​       Responsible for jingdong cloud hosting and cloud architecture of database, and research and development work, previously in sohu product technology center is responsible for sohu webim, real-time gaming platform technology products such as research and development work with architecture, after joining sina weibo underlying platform research and development work of sina weibo, dominated the redis in sina weibo's development and application of mass customization. Later, I joined Tencent and was responsible for the r&d and architecture of Tencent's large-scale distributed storage project, providing highly reliable storage services for Tencent's various business product lines. In terms of technology, I mainly focus on distributed storage/cache/database, Linux kernel and other basic technical fields, and have a deep understanding of blockchain basic technology；

- Dongjiahong

​      Familiar with Golang language development and related tool chain; More than 8 years of basic system development and architecture experience in Internet industry; Experience in large-scale distributed storage/cache/database system design, knowledge of open source architectures such as Ceph,Swift,Sheepdog, etc. Have a deep understanding of web server design, read some excellent open-source project source code, such as Nginx,Redis,Memcached, etc. Blockchain technology enthusiasts, have unique insights into the design of economic models;

- Zoe

​      Years of experience in data product development and architecture. I have led the development and community construction of various data products in JINGdong and several companies. I am active in the field of data products and have rich experience in various products in the field of database and big data. At present, I am leading the r&d and promotion of flexible database in Jingdong Mall. Blockchain technology enthusiast, has participated in the development of Lambda and NEO public chain, and is currently committed to the planning and development of NFT market projects;

### Team code repositories

https://github.com/neo-project/neo

https://github.com/lk2684753/go-palletone

https://github.com/lk2684753/chubaofs

https://github.com/lk2684753/near_contract_rust-did

## Additional Information

The team developers are all certified by the NEAR community as developers, and we are certified 

lk2684753.near 、jiahong.near、boxer.near

https://learnnear.club/near-certified-developers-level1/

On storage miners, we currently have 100P+ computing power;

The following are some node addresses for maintenance and operation:

F020330 f0855056 F0711266 F0133235

**Comment by realChainLife** [comment]
Hi @lk2684753 thank you for this proposal. We would like to fund the work outlined in this proposal. Please email devgrants@fil.org to discuss next steps.

**Comment by lk2684753** [comment]
> Hi @lk2684753 thank you for this proposal. We would like to fund the work outlined in this proposal. Please email [devgrants@fil.org](mailto:devgrants@fil.org) to discuss next steps.

Hello, I'm sorry to reply to you now. Now we can discuss the following steps in the email.

**Comment by lk2684753** [comment]
> Hi @lk2684753 thank you for this proposal. We would like to fund the work outlined in this proposal. Please email [devgrants@fil.org](mailto:devgrants@fil.org) to discuss next steps.

I'm sorry for replying to you so late. I have already sent the email. Please check it.

**Comment by lk2684753** [comment]
Hello, I'm sorry to reply to you now. Now we can discuss the next steps.


RFP:
https://github.com/filecoin-project/devgrants/issues/375


| |
Lk
|
|
***@***.***
|
签名由网易邮箱大师定制
On 1/6/2022 19:05，Sonia ***@***.***> wrote：

Reopened #375.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
