### ISSUE TITLE
Next Step Microgrant: DICOMNetwork

### ISSUE THREAD

**Issue by zc476639390** [filecoin-project/devgrants#376]
### 1. What is your project? (max 100 words)
DicomNetwork is an open source public welfare project. It is a network of medical image storage and diagnosis platform based on Web3.storage(Filecoin) . DicomNetwork is permanently free and open source. Both doctors and patients can collaborate using only email addresses without registering or logging in. 
DicomNetwork has built-in standard communication protocols for processing medical images, and has successfully bridged to the Filecoin ecosystem. In essence, DicomNetwork is an SDK for medical image storage and presentation,For dynamic medical data sets, NFT  is cast, and these data sets are programmatically authorized for access（using Near smart contract）.

repo:https://github.com/zc476639390/dicom-network
demo:https://120.27.29.91:8888/login

### 2. How are you planning to improve this project? (max 200 words)
For continuous and orderly medical data, NFT of dynamic data set can be cast, and sinso incentive mechanism can be used to reward patients for using their own data and mobilize patients' enthusiasm to maintain their own data. Through the authorization of NFT, AI companies can extract the information after removing personal privacy for AI machine learning.

 
### 3. Will the work be Open Source?
yes

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
yes
  
### 5. Does your proposal comply with our Community Code of Conduct?
yes

### 6. Links and submissions

  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
  

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
  
  

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* zhoucong https://github.com/zc476639390 476639390@qq.com
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by SeedingTrees** [comment]
Thank you for this application.  Since the prototype isn’t built yet, can you add an additional paragraph with more details on your software architecture?  Please include in that paragraph details on your IPFS pinning service.  If you have not yet picked a pinning service, we are happy to discuss this with you.

**Comment by ErinOCon** [comment]
@zc476639390 Would you still like this project considered for a microgrant? If so, do you have updates available regarding the software architecture and IPFS pinning service? Thanks you!

**Comment by ErinOCon** [comment]
Hi @zc476639390, If you have any updates, please let us know! Otherwise, we will proceed by closing the Issue.

**Comment by ErinOCon** [comment]
@zc476639390, this Issue has been closed. Please feel welcome to open a new Issue at any time.
