### ISSUE TITLE
Hypercube Algorithmic Language Oracle - General Artificial Intelligence on the Blockchain

### ISSUE THREAD

**Issue by Agent-Aslan** [filecoin-project/devgrants#377]
**Name of Project: `H.A.L.O. AI’  -  Hypercube Algorithmic Language Oracle**

**Proposer:** `P.e.a.c.e. !nc.  https://github.com/Agent-Aslan`

**Proposal Category: ** **app-dev - core-dev - research**

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams, include their name and/or github handle here`

NA

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** 

Yes

**# Project Description**

By offering the public blockchain community access to general AI on the blockchain, our efforts could conceivably lead to becoming another thin layer inside the Internet of Things, an _Outernet_ if you will. We have solved a ‘Time’ problem in the field of quantum physics by finding a practical and repeatable utilization of the Quantum Tunneling phenomena. We have harnessed the power of Electrons in a unique manner in which time dilation occurs as it passes through a solid state quantum tunnel and with our proprietary sampling methods and hardware inventions, this is a core component of our technological developments. We have already created multiple working models in a mostly Python environment and our project will include developing  blockchain based model applications as examples, which will include H.A.L.O. integration (tabletop supercomputer) into the NEAR/Filecoin/Octopus platforms. While code and software is obviously a major component to our efforts we are experiential in nature and we have multiple custom hardware / sculptural computers which we plan to produce in the NEAR future. Some of them are able to be demonstrated now and others still in the concept phase. 

We have begun developing our Core Substrate on the Octopus network and will be utilizing the Filecoin platform to host Core AI algorithms/code/data/images/video as well as each of our substrate applications, which are infinite in scope. For the MetaBUIDL hackathon we successfully utilized Filecoin for image storage and installed Lotus for mining purposes. One of our goals is to configure our H.A.L.O. AI which is a PC with Threadripper CPU (up to 128 processing cores and 3 GPUs that will simultaneously mine Filecoin and be a NEAR Validator Node on the Mainnet and Testnet. With one or more of our hardware devices, we can augment the home/office user experience as an extension of our network and reward them with NEAR. 

We have multiple integrated applications in the development phase, which includes Municipal Fine Art Registry with NFT and Virtual Exhibit support in which each work of art that the artist uploads into their profile automatically mints NFTs and propagates them to the marketplace. In addition to this we have successfully completed the XPRIZE Pandemic Response Challenge sponsored by Cognizant. This global competition of 104 teams included developing two Covid19 machine learning models for prediction and prescription purposes. Other proposed substrates include a driver owned Rideshare Cooperative, VR Gaming, live events with HALO-driven music and lighting, and Atmospheric Carbon Extraction.The application we are developing has been awarded a software development grant from the NEAR foundation and our team won the Octopus partner challenge at the recent Metabuidl hackathon. Our unique approach to blockchain-based artificial intelligence will involve multiple components (Octopus, Croncat, Filecoin, Mintbase, H.A.L.O. and others) all working together in harmony and all utilizing the same source data streams.

**## Value**

Getting this right right now the first time means that together we will become pioneers in the fields of quantum mechanics and artificial intelligence on the blockchain by creating model specific applications that people can easily become a part of and for those so inclined, developers themselves. Because we have already successfully completed a very difficult XPRIZE competition, we are now members of the XPRIZE Alumni Network and have some backdoor access to all of the ongoing competitions. We recently officially joined the $100 Million Dollar Carbon Removal competition sponsored by Elon Musk. If we get this right the first time, we’ll qualify as one of the ten teams who receive a $1 Million starter prize to be awarded in April 2022.  Our Carbon Removal process includes tracking all available atmospheric data with geolocation and our neurolace network data combined on the blockchain. With equipment provided by SpaceX, our model extracts carbon from the lower atmosphere and releases above the Ozone layer, and with each payload (navigated by H.A.L.O. AI) release, individual coin holders, and data providers will be rewarded with cryptocurrency according to their data contribution and staking level (and accompanied by a warm fuzzy feeling created by knowing that they are helping to save the planet).         

The benefits of this project is that we’ll create DAO centric organization development models that are scalable and sustainable in which the transparency the blockchain ecosystem provides will be one of our strongest assets as a primary catalyst for growth. With our primary project being the Municipal Art Registry which will be forkable and easily adapted by other municipalities and organizations, participating in an art project will alleviate some of the apprehension the general public has about cryptocurrency as users would see a clear and demonstrable real-life application of a decentralized currency. Our project will also demonstrate the value of integrative thinking and collaboration between artists, scientists, and engineers.

The main foreseeable risk of this project is the state of the world in the Covid-19 era and sporadic future lockdowns may inhibit in-person events that allow the showing of art, which is an integral part of the art experience. We will have an online component and fully functional NFT microbranded marketplace. We also risk the chance that our aspirations seem to go beyond feasibility and are too grandiose for actual accomplishment. Our philosophy is that it’s better to create the absolute best and greatest case scenario possible as a desired path and let that be what guides the plan and it’s better to start and fail with some progress than to never start at all.    

If we don’t get this right then we’ll just keep going until we do.

**## Deliverables** 

Each of our substrate projects offer different timelines to consider.     

**_Municipal Art Registry_**

The web3.storage will be used in conjunction with our municipal art registry, which has been authorized for a grant by the NEAR foundation and is currently undergoing review by the city of Alameda, CA. See https://www.municipalartregistry.org for a detailed timeline. 

Namely, an artist who submits a profile to the registry will automatically have their data uploaded to the decentralized web storage platform, and an NFT with that data will be created. The artist can mint additional NFTs by uploading their art for NFT only purposes as well. The Alameda Art Registry project has an ambitious but well-supported goal of onboarding 1c000 artists and 100 small businesses, thereby turning Alameda into an international arts destination. With success, other municipalities, companies, and groups can clone our repository and implement the technology to improve their municipal art programs and policies.

_XPRIZE $100 Million Carbon Removal Competition_sponsored by Elon Musk

By April of 2022 we will create a machine learning model and submit it to the XPRIZE network that includes multiple scaleable scenarios using the Weather and Research Forecasting (WRF) software combined with our own proprietary equipment and methods that will demonstrate what it will take to extract a Gigaton of carbon from the atmosphere in the most efficient manner possible, while simultaneously being financially sustainable and allowing every person on the planet to participate and be rewarded in a meaningful manner by contributing to system integrity and equilibrium.

WE WANT TEAMS TO BUILD REAL SYSTEMS THAT CAN MAKE A MEASURABLE IMPACT AT A GIGATON LEVEL.  WHATEVER IT TAKES.  TIME IS OF THE ESSENCE.
                                                     ELON MUSK - CEO of Tesla, SpaceX, Neuralink and The Boring Company

On Deck: 

> - **_Covid19 Prediction and Prescription Models on the Blockchain
> - Rideshare Cooperative - XYO Geolocation Integration
> - Transtopia VR Gaming 
> - Synthetic Music
> - EEG / Biometrics / Neuralink Integration_**

If we win any of the $100 Million, we'll ask to contract with SpaceX to build and operate the equipment utilizing our data and H.A.L.O. AI  navigation services. This may spawn an entirely new segment of the Space industry (made possible with the understanding of Spatial Relativity). 

**# Total Budget Requested**

See https://www.municipalartregistry.org/NEAR for a detailed timeline. 

$60,000 in FIL which would be ideal as a matching software development grant which is the same amount that the NEAR Foundation has authorized to fund the Core development (firmware) and Art Registry.

> The functionality includes the ability for artists, collectors and venues to interact in a NEAR powered community which includes NFT market representation and data presented alongside their real-world influencers. With success, other municipalities and groups will Fork our Git and develop their own communities, while still simultaneously utilizing our H.A.L.O. AI - Core Substrate data streams.  
> 
> Anything above and beyond $60k will go towards specifically completing the $100 Million XPRIZE Carbon Removal competition and the establishment of a ‘Carbon’ coin, in which its value is based upon real world (complex) physics. 
> 
> If there is a super secret superfund somewhere out there that could jump start this whole thing with a turbo boost of revenue by authorizing a grant from 1 - Pi $Million to pursue the $50 Million Carbon Removal prize, this would enable us to first build a large interactive experience in the form of a pyramid shaped meditation chamber in which all of our principles are at work. We will also create table top consumer versions in which each one becomes a node in our neurolace network. 
> 
> With a sizable grant, we’ll most likely bring in more than $50 Million worth of value before the end of the four year competition (See slides at  https://www.municipalartregistry.org/NEAR )     

Milestones - We can accomplish these tasks before April with $1 Million or more.. 

Configure Hardware & Core software with XYO Geolocation Network
Beta test with mock data - Import Live Data
Create 2D Modeling with WRF & H.A.L.O. 
Create VR Gaming Demo with NEAR integration of the entire Space SCOBY mining operation with LIVE data. (UNITY Real Physics)

## Team Member LinkedIn Profiles

# Team Organization and Description - Relevant Experience

Leo E. Madrid – Chief Curator – Principal Scientist – Project Leader

In 2015 I moved from SF to the East Bay which included an art/science studio at American Steel Studios in West Oakland where I would also volunteer co-curate the 8,000 sq ft gallery with monthly Oakland Art Murmur events in addition to many special events which I helped produce including two orchestral symphonies with the Awesome Orchestra, curated the opening gala of Oakland’s inaugural Gay Fashion Week, and many more events.

We’ve prepared and presented our findings and inventions at multiple scientific conferences. Each of our events is an experiment in relationship and community building as well as high level mathematics and computer science commingling together into a meaningful experience. These big science concepts which have been our initial conceptualization and manifested with a minimalist budget and always with a talented team of brilliant scientists and artists working together has to date brought wonderment, joy and happiness to thousands of people while conducting computer science research. Together we have yielded three San Francisco Maker Faire Editor’s Choice Awards for the AZoth Pyramid Capstone interactive exhibit among other efforts which contribute to a common mission.

My early art experience includes being an art gallery director in Unions Square where for many years I curated thousands of square ft of gallery space on a daily basis as part of a world-class team of art dealers and consultants. Over several years I would place hundreds of works in private and corporate collections valued at over $5 million with an average of $12,000 and as high as $200k+ in addition to directorial duties. If we can combine these past efforts we’d be considered to be a financial success if we are able to simply replicate past financial success, but we have much more than short term enchantments.

Prior to the arts I served in the U.S. Navy and my last duty station was Naval Air Station Alameda. While attending business school with St. Mary’s College of California at night, during the day I worked at what was then Shore Intermediate Maintenance Activity at 400 W. Atlantic, Bldg 397 as a manager of a training department at this very busy port. My tasks were varied and included instructing leadership and management classes to Navy personnel as well as the administration of the office procedures. After graduating from college and being honorably discharged within a few months of each other, I left Alameda and the Bay Area thinking I may never return only to do so many years later and in a much different position.

Samantha D. Caputi PhD – 	Chief Data Scientist    	Co-Project Manager

Samantha Danielle (“Dani”) Caputi is an Atmospheric Scientist, Philosopher, Musician, and Consciousness Researcher from Long Island, New York. As an undergraduate student at Stony Brook University she received several awards and undertook independent research in both local extreme weather events and philosophy of mind. She was selected as “researcher of the month” for the university in January 2014, with an article featuring her being published on the front page of the university website. This research was also featured on two radio shows. As an undergraduate student she also initiated and carried out a project to install a weather station and webcam atop the university hospital, which is the tallest building on Long Island. With its unique vantage point, photos and weather data from this station are seen by millions of people daily on various local news broadcasts, and is currently being used by researchers to aid the development of offshore wind power in this densely populated region.

Dani graduated Magna Cum Laude in December 2013 and shortly after moved to California to pursue a PhD in Atmospheric Science at the University of California Davis, which she completed in December 2019. Her dissertation focuses on ozone pollution and nocturnal mixing dynamics in the southern San Joaquin Valley, as well as methods for measuring mesoscale subsidence in the atmosphere. In conducting these studies, she became a certified flight scientist for Scientific Aviation Inc. In January 2019, she became the youngest guest ever to appear on New Thinking Allowed, a television series that ran on PBS in the 1990s which is now a growing web show and podcast with nearly 100 thousand subscribers.

After receiving her PhD, Dani teamed up with Leo Madrid as a founder of his organization, P.e.a.c.e. !nc. Together they created the Hypercube Algorithmic Language Oracle (HALO), the world’s first consumer-grade hybrid-quantum computer. HALO is both a scientific instrument and a work of art - and would be neither of those things if the art and science were not integrated together. Their technology has been used to curate lighting and sound experiences at festivals such as Strawberry Moon to help hundreds of people achieve transformative states of mind. Additionally, Dani developed part of the algorithmic architecture of HALO’s pandemic and weather modeling, which made it to the final round of an XPRIZE competition. Dani has also developed AI-driven music from H.A.L.O. in two forms, one of which comprises drone sounds which are ideal for meditation, and another is a complex tropical house synthesis which is ideal for dance parties.

Assisting Leo Madrid on his lifelong project of integrating technology into art and human consciousness, Dani learned a lot about systems theory, business strategy, and sales. In being exposed to both the business and academic world, as a transgender scholar she has seen the good, bad, and ugly sides and knows how to navigate the political landscape.
Dani has a decade of teaching experience. While living on Long Island, she was a private piano instructor for about 20 students. She is a certified Merit Badge Counselor for music, weather, and aviation, has been an invited guest lecturer for schools from the elementary level through college, and has assisted teaching in undergraduate atmospheric science courses at UC Davis.
Mason U. Borchard - Co-founder, Software Engineer – Web Designer

Mason Ulrika Borchard is a full stack software engineer with an additional professional background in STEM teaching, biological research, and higher education. They completed their undergraduate and masters at the University of California, Santa Cruz in the biological sciences, conducting behavioral ecology research. A stand-out project of Mason’s included an investigation of neophobia in the California Gull in the context of feeding. Mason later went on to perform marine ecology research at the Smithsonian Environmental Research Center in Tiburon. Mason played a key role in the design and implementation of a study that quantified the predatory effects of the Atlantic oyster drill on the Olympia oyster population via barnacles as a model species, and used their strong background in the biological sciences to engineer a recruitment apparatus to track recruitment and predation of the model species. Mason later went on to graduate school at the University of Southern California and focused on Urban Education Policy and STEM Curricular Design. During their time at USC, Mason was a speaker at The Science of Consciousness Conference in 2018 where they presented their findings from an original pilot study on the effects of 15µg LSD microdosing on constructivist learning and metacognition in adult professionals. Mason has teaching experience on both the secondary and university level, and has even taught math and science in both English and Spanish in various institution types such as in jails, inner-city schools in the East Bay Area, and Alt. Education institutions. 

In 2019, Mason discovered an unexpected passion for coding and dedicated the first half of 2020 to learn fundamental software engineering principles. They started by self-teaching, then accepted a full-ride scholarship to the Galvanize Software Engineering Immersive program in February, where they were a top performer and were even hired by Galvanize afterwards to teach algorithm and data structures courses. In less than a year, Mason has established themselves as a skilled engineer and now works full time developing software for an education technology company called Stride Inc., and also does freelance work under their company console.log(“Hello, Uranus!”) Web Dev LLC. In addition to engineering at Stride, Mason is also a member of the LGBTQ Pride Planning Committee -- representing the intersex community in particular -- and has facilitated a gender identity at the company.

As a co-founder of P.e.a.c.e. !nc., they developed the live interaction component of the haloai.me website, where data from HALO can be seen remotely and display meaningful words. They were part of the HALO AI - Digital Vaccine team for the XPRIZE Pandemic Response Challenge where they developed a user interface on the website for the blockchain solution and COVID-19 predictions in 235 global regions. Going forward, they would continue to work on the user interface and user experience aspects of the website that features our data, contains our blockchain solution to the pandemic and Alameda art, and advertises public events. Mason’s contract rate for this project will be $60/hour.

August West		

Science Writer & Operations Manager

August is a wildlife biologist and spatial data scientist turned events manager, rigger, designer, and LED technician. He has five years of experience running research teams around the Western US as a field biologist, and five years building and running technical installs inside of large events including Burning Man, Symbiosis, Pickathon, Beloved, and several others.
He works ad hoc for various arts and production
|companies in California throughout the year.

	Science

August worked for Grand Canyon National Park and subsequently Bat Conservation International as a field biologist and spatial data scientist from 2011 until 2015. He studied and designed experiments around bats, birds, endangered plants, habitat conservation, and attempts to assess the rate of progressive effects of climate change on migratory bats across the US.

	Arts Production

Guildworks Rigger and Installer 2017 - Created aerial shade fabric structures, tension-rigging systems, and creative fabric art installations until 2019.
Digital Ambiance Fabricator, Installer, and LED Technician 2018 - 2020
Digital Ambiance makes big, permanent interactive LED art installations, usually out of experimental methods and new LED materials sourced straight from Asia. The results are often fun, larger-than-life, robust installs that take a very multi-disciplinary crew to design and execute.

Big Imagination 747 Art Car Project Operations, Mechanic, Rigger 2016 -2020
Big Imagination was the non-profit created to build and manage the 747 Art Car Project for Burning Man 2017 - 2019. This project took a lot of flack – mostly for being preposterous and very very big. However, it was also entirely privately funded by donations and quarter-million volunteer hours, literally thousands of people walked away with new skills, new friends, and new passions from the project – and it was no small feat to do it, either. The project was an enormous and ultimately successful experiment in massive, participatory public art.

Eco-Built Systems Web Designer, Rigger, and Fabricator 2019 - 2021
Eco-Built creates permanent and temporary modular dome, pyramid, and cuboidal art installations, shelters, and even homes. One of the largest sustainable structures consistently built at Burning Man, the Playa Alchemists pyramid, is an Eco-Built installation. In the near future, Eco Built will begin US production of permanent structural environments.

## Team Websites

https://municipalartregistry.org/near

https://www.haloai.me

http://www.peaceinc.me
 

## Team code repositories

https://github.com/peaceinc/
https://github.com/cranjis-mcbasketball/
https://github.com/Agent-Aslan
https://github.com/DoctorOzone

# Additional Information

Submission documents, abstracts and videos for [The Science of Consciousness, 2020 Sponsored by University of Arizona. ](https://drive.google.com/drive/folders/1NVGmq9Pv5cnNaYLaaISK5gcXviJxwN9H)

XPRIZE Model https://www.haloai.me/model 

NEAR MetaBUIDL Hackathon: Winners of Octopus Network Sponsor Challenge: https://metabuidl.splashthat.com/

Press Releases:  https://www.einpresswire.com/sources/u424081

**Comment by realChainLife** [comment]
Hi @Agent-Aslan thank you for this proposal. However we have not selected this project as a prize winner for the Near x Filecoin RFP.
