### ISSUE TITLE
Next Step Microgrant: TutoMe

### ISSUE THREAD

**Issue by h2qutc** [filecoin-project/devgrants#381]
### 1. What is your project? (max 100 words)

TutoMe is a decentralized platform where the developers can share, sell, exchange their tutorial articles/videos about the technologies via smart contracts. TutoMe allows the developers to earn money by writing the article, making the tutorial video, sharing their programming experience, creating the online classes.

The articles/videos will be organized by tags, authors, ratings.

Users can (partially or fully) access the tutorial articles/videos by paying some fees. They can also vote, add the comments for each article/video.

The platform will be developped by using Flow blockchain network, NFT.storage API and IPFS storage space.

Github repo: https://github.com/h2qutc/tutome

### 2. How are you planning to improve this project? (max 200 words)

- Set up Angular project with IPFS, Filecoin Network, NFT.storage API, MongoDb
- Integrate Payment System.
- Design UI/UX (Home page, Login page, Article/Video page...)
- Promote the platform on social media by writing the articles/tutorials
 
### 3. Will the work be Open Source?
Like many other projects that welcome community contribution, our project is also Open Source under MIT license.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes. The weekly reports will be updated so that all can be in sync.

  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes. I have read the code of conduct. I assured that the project will be developed in compliance with it.

### 6. Links and submissions
  
* Have you submitted to the Filecoin Community Showcase 
Yes. Pull request has been created: https://github.com/filecoin-project/community/pull/362
* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
Yes. Here is the link: https://github.com/filecoin-project/community/discussions/361

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  HO Hong Quan
  Email: hohongquan.bk@gmail.com
  Github: https://github.com/h2qutc
  Role: Coder
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by SeedingTrees** [comment]
Thank you for this application.  Since the prototype isn’t built yet, can you add an additional paragraph with more details on your software architecture?  Please include in that paragraph details on your IPFS pinning service.  If you have not yet picked a pinning service, we are happy to discuss this with you.

**Comment by ErinOCon** [comment]
@h2qutc Would you still like this project considered for a microgrant? If so, do you have updates available regarding the software architecture and IPFS pinning service? Thanks you!

**Comment by ErinOCon** [comment]
@h2qutc Would you still like this project considered for a microgrant? If so, do you have updates available regarding the software architecture and IPFS pinning service? Thanks you!

**Comment by h2qutc** [comment]
hi @ErinOCon Yes of course, I am working on this project. I will provide the updates regarding the software architecture and IPFS pinning service within some days. Thank you for your interest on my project.

**Comment by ErinOCon** [comment]
Thanks, @h2qutc! Once these updates are available, please feel welcome to open a new issue. We can continue our review once this is completed.
