### ISSUE TITLE
Open proposal sql-like DB over filecoin 

### ISSUE THREAD

**Issue by fnbellomo** [filecoin-project/devgrants#382]
# Open Grant Proposal: `Chest: sql-like DB over Filecoin`

**Name of Project:** `Chest`

**Proposal Category:** `devtools-libraries`

**Proposer:** `fnbellomo`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes

# Project Description

Public and private entities such as governments, NGOs and hacktivists that analyze and process public data invest a lot of effort, time and resources in normalizing their data before they start analyzing it. These data can range from temperatures from all national weather stations, state/province polygons to politicians' affidavits, census results and government spending. Once this first task is completed, these quality normalized data (in some cases using international standards) are published for third parties to reuse, mainly by publishing a csv file which is periodically updated.
The problem is when external developers or data analysts want to reuse these data because:

- Not always having a schema with the structure of the data.
- Every time the csv is updated, you need to make a process of updating the data.
- Generating relationships between your own data and published data is not trivial.

`Chest` is a sql-like database that uses Filecoin as a store. When a user creates and stores data in its table, it also stores a [json-schema](https://json-schema.org/) with the current model of the data. Each `migration` and each `commit` on the DB generates a new version (a new CID) saving all the history and allowing users to access the latest or any particular version. The default tables are public allowing other users to consume the data. In the tables, you can specify indexes and create relationships to external tables allowing sql-like operations. When generating a relationship with another table, you can specify a version or always use the latest version, which will always bring the latest data.
In addition, by using the [web3.storage](https://web3.storage/) API to store in Filecoin, users can have their DB without their own infrastructure and for free.

## Value

This project has the potential to add more developers to the Filecoin ecosystem since the js API is inspired by other ORMs such as [TypeORM](https://typeorm.io/#/), so the creation and consumption of data is very similar to a traditional DB.
In addition, by using Filecoin as a store, both the web and the data will be decentralized.

## Deliverables

The final product consists of a js api and a web app.

### JS API

Chest will be a js library that has 3 main components:

**The Models**: We can create them from a valid [json-schema](https://json-schema.org/) file or through an es7 class extending a base class that generates an associated json-schema. In the models we are going to specify the data types of each column, primary keys, foreign key, or more complete functions of relations as the [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance). This model is the one that will be in charge of generating the necessary indexes and relations in the table as well as validating new data. The schema (created automatically or read) is the one that is saved in each new version of the table, which allows us to read the model directly from the table, so that an external user does not have to rewrite it.

```typescript
import { Column, BaseModel, modelFromSchema } from 'chest'

class State extends BaseModel<State> {
    __tablename__ = "state"

    @Column({ nullable: false, index: true })
    name: string

    @Column({ nullable: false, description: "some nice text" })
    poligon: MultiPolygon
}

// Or load from schema file
// `ElectionResults` has a relation with `State`
const ElectionResults = modelFromSchema("./election-result.schema.json")
```

**The Query planner**: Given a model, this component is in charge of solving the query, in which we will be able to filter by relations or attributes returning one or multiple elements.
Chest will be a js library that has 3 main components:

```typescript
const result: ElectionResults = chest
  .query(ElectionResults)
  .where(ElectionResults.stateName === "california")
  .one()
```

**Chest Name System (CNS)**: This service is the one to which we will be able to consult which are the versions of a table to obtain the corresponding CID. Every time we generate/update a table, the CNS is updated. CNS uses IPNS for the maintenance of the names.
Chest will be a js library that has 3 main components:

```typescript
const versions = CNS.get({ username: "@fnbellomo", table: "state" })
console.log(version)
// [
//  { version: 1, createAt: datetime, CID },
//  ...
//  { version: 5, createAt: datetime, CID }
// ]
```

### Web app

The web app will allow us to search and inspect public and proprietary tables. We will be able to see some metadata such as who is the user that maintains it, how often it is updated, etc. We will also be able to see the associated schema and generate a graph with the relationships of the table (and the relationships of its relationships) to understand if this data is useful for our project. We will also be able to see the history of all the models and select a particular version to use.
In addition, from the app we will be able to generate queries and download the data to analyze with external tools.

In a second version (out of this proposal) the web app will allow to generate smart contracts about who accesses your data, generating a data economy.

## Development Roadmap

| Milestone | Specification | People Involved | Time | Bugdet |
|---|---|---|---|---|
| 1. Model | <ul><li>Have a base object (`BaseModel`) that uses `reflect api to define table properties using decorators</li><li>A function to create a model from a schema file</li></ul>In both cases we will use [AJV](https://ajv.js.org/) to create/validate the schemas. In addition, the generated model will be able to resolve the relationships and accept custom functions for the relationships.| @fnbellomo, @lbellomo | weeks 1-2 | 2000 USD |
| 2. Chest | At the end of this milestone, we will be able to create our `chest` instance (already connected to Filecoin) and save bulk data from a CSV. The CID results will be saved in a local file until milestone 4 | @fnbellomo, @lbellomo | weeks 3-4 | 1500 USD |
| 3. Query | At this point, we are going to be able to make queries which are going to be results using the indexes that we defined and created in the Model | @fnbellomo, @lbellomo | weeks 5-6 | 2000 USD |
| 4. CNS | This is a key piece of the project. Once developed, the CIDs will no longer be stored locally, and we will be able to query by tables created by other users | @lbellomo | weeks 6-8 | 3000 USD | 3000 USD |
| 5. Web App | With the js API working, we will be able to develop the web interface to search and display schemas and table data. The app will have an English version and a Spanish version (the cores are from Argentina) | @fnbellomo | weeks 7-10 | 2500 USD | 2500 USD |
| 6. Docs and tutorial | As a final point, we are going to document end to end an example of how to create new tables with relationships, load data from a csv and add a relationship to an external table with a custom join function | @fnbellomo, @lbellomo | weeks 11-12 | 1000 USD |

The project is going to be developed in typescript, and for the ui we are going to use svelte. In each milestone we are going to develop the associated unit-tests.

## Total Budget Requested

$12,000

All expenses will go toward development costs. See each milestone for estimated development costs.

## Maintenance and Upgrade Plans

Chest is a project that was born as a need of several projects in the region (we are from Argentina) in which we participate or know. Our idea is that these projects will gradually adopt `Chest` to make data exchange and collaboration easier. Although the main users will not be developers (they will mainly use the web UI), they will generate constant feedback and will contribute new features. Initially, the team that developed this proposal is the one that will maintain it, but we hope you can add more collaborators.

The project is going to be developed in typescript, and for the ui we are going to use svelte. In each milestone we are going to develop the associated unit-tests.

# Team

## Team Members

[Lucas Bellomo](https://github.com/lbellomo) - Data Science and backend develop with 3 years of exp.
[Franco Bellomo](https://github.com/fnbellomo) - DevOps and full-stack developer with 4 years of exp.

## Relevant Experience

We have a lot of experience working and collaborating with ngos on issues of transparency and national budget spending. We know what your needs are on how to share and reuse data.

**Comment by realChainLife** [comment]
Hi @fnbellomo thank you for this proposal. We would like to fund the work outlined here. Please email devgrants@fil.org to discuss next steps.

**Comment by ErinOCon** [comment]
Hi @fnbellomo! Are you still interested in receiving this grant? If so, please be in touch at [devgrants@fil.org](mailto:devgrants@fil.org).

**Comment by ErinOCon** [comment]
Hi @fnbellomo, this issue has been closed. If you are still interested in the grant, please feel welcome to re-apply!

**Comment by ErinOCon** [comment]
Hi @fnbellomo, thank you for your email. Can you confirm that your proposal is up-to-date and that you will be prepared to kick off your work upon receiving the payment?

**Comment by ErinOCon** [comment]
Hi @fnbellomo, are you still interested in proceeding?
