### ISSUE TITLE
Open Grant Proposal Cosines For Everyone: Creating Employment in Sustainable Crypto Mining

### ISSUE THREAD

**Issue by MurageKibicho** [filecoin-project/devgrants#383]
# Open Grant Proposal: `Cosines For Everyone: Creating Employment in Sustainable Crypto Mining`

**Name of Project:** Cosines For Everyone

**Proposal Category:** `app-dev`

**Proposer:** `MurageKibicho`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** "yes"

# Project Description
Cosines For Everyone is an online work platform that pays people to help computers compress images. In a more technical sense, we pay people in crypto to create image-specific quantization tables for JPEGs. This is simple, paid, non-technical work for the 650 million Africans who access the internet from their mobile phones. I got the idea from my experience implementing Discrete Cosine Transform algorithms and having terrible internet in my home country, Kenya, during the pandemic.

Our goal is to fight internet inequity in emerging economies. We are letting people create better quantization tables for the media they consume. We are also encouraging people who earn less than a dollar a day to hold crypto. We believe that no one should be living in poverty at a time Bitcoin is valued at 60,000 dollars. [Research](https://qz.com/africa/594455/the-worlds-poorest-households-are-more-likely-to-have-a-mobile-phone-than-a-toilet/) shows that people living in poverty are more likely to have a mobile phone than a toilet. Based on this, we use the Discrete Cosine Transform(DCT), the algorithm behind JPEGs, as our cryptographic hash. As a hashing algorithm, the DCT makes crypto accessible to anyone with a phone that can open JPEGs.

JPEGs compress data using the [Discrete Cosine Transform](https://en.wikipedia.org/wiki/Discrete_cosine_transform) (DCT). This process is entirely subjective since the image only changes in ways the human eye can see. In other words, humans can tell when a picture starts looking bad even when a computer cannot. The goal is to let humans intervene in cases where better quantization tables can be used.

## Value
This project needs Filecoin as a source of image and video data and as a storage platform. Sourcing from Filecoin opens up the Filecoin ecosystem to a new demographic: people who only access the internet from their mobile phones. Take Africa for example, [7.7% of all households have a computer at home](https://www.statista.com/statistics/748549/africa-households-with-computer/) while [75% of the population has access to mobile phones](https://www.economist.com/graphic-detail/2017/11/08/in-much-of-sub-saharan-africa-mobile-phones-are-more-common-than-access-to-electricity). This means at least 75% of the population in Africa cannot participate in the traditional roles on the Filecoin network because they obviously cannot run a Mainnet. 

This is the right time to get people on the network because [Africa recorded a 1200% in cryptocurrency adoption between July 2020 and June 2021](https://www.theafricareport.com/131083/african-countries-are-adopting-crypto-faster-than-their-global-counterparts/)  

If we fail, we risk perpetuating internet inequity.  

## Deliverables
The main deliverable is an open-source mobile application that lets anyone decide what images look the best at different levels of quantization. The app user is simply required to run a slider from left to right to determine what quantization values work best.

Once the quantization matrix is created, the person sends only the matrix to a Filecoin server that will create the new JPEG and store it.

## Development Roadmap
Note: the prototype is complete and is available in this [repo](https://github.com/MurageKibicho/Filecoin-RFP)
Week 1 - 3: `Finalize UI designs and tech stack`
The goal is to have a minimalist design that allows anyone to just start working. Our emphasis is on making the design accessible to people who may not be literate. The cost of hiring a part time designer for 3 weeks is 360 dollars, at a rate of 15 dollars an hour for 8 hours of work in a 5 day week. 
At this time, we will also finalize our current product architecture. The prototype uses Flutter and Dart for the UI, C for image processing and connects to a Node JS and Express backend with a Mongo DB database for user authentication. We plan on hiring a consultant  to determine if this stack is good for production. The cost of hiring a consultant for 3 weeks is 720 dollars, at a rate of 30 dollars an hour for 8 hours of work in a 5 day week. 

Week 4 - 7: `User testing and Internet testing`
The goal is to perform physical user testing in Nairobi, Kenya. We will be assessing what phones our target consumers are running, and figuring out how to send uncompressed bitmaps to areas with 2g and 3g internet connections. We will also be testing how accessible our designs are.

I will be traveling from New Haven, Connecticut to Nairobi, Kenya. If the prices remain the same, a round trip will cost 1000 dollars and the cost of accommodation, transport and testing for 3 weeks will be 800 dollars. I will perform this on my own to keep costs down.

Week 8 - 12: `Server costs and Push MVP to production`
Our goal is to finalize any changes we may need to make. If everything works well, then this will cost 100 dollars to release a mobile app on the App Store and Google Play Store. We hope to use free AWS credits to run our backend.

## Total Budget Requested

Hiring Designer - 360 dollars
Hiring Product Consultant - 720 dollars
Flight to Kenya and accommodation - 1800 dollars
Deploy MVP - 100 dollars
Total cost - 2980 dollars

## Maintenance and Upgrade Plans

I will maintain this project as long as it remains viable.

# Team

## Team Members

Murage Kibicho

## Team Member LinkedIn Profiles

(Murage Kibicho)[https://www.linkedin.com/in/murage-kibicho/]

## Team Website

[My Github](https://github.com/MurageKibicho)
[Prototype](https://github.com/MurageKibicho/Prototype)

## Relevant Experience

Murage Kibicho - C and Flutter programmer with 4 years of experience making mobile apps for Iphone and Android. Math major at Yale in his junior year, has prior research experience in computer graphics.

## Team code repositories

(Combining FFMPEG and the DCT)[https://github.com/MurageKibicho/ffmpeg-learning]

(My Discrete Cosine Transform implementation getting 4 upvotes on codereview.stackexchange)[https://codereview.stackexchange.com/questions/265527/faster-aan-algorithm-for-calculating-discrete-cosine-transform]

**Comment by realChainLife** [comment]
Hi @MurageKibicho thank you for this proposal. We would like to fund the work outlined here. Please email devgrants@fil.org to discuss next steps.
