### ISSUE TITLE
RFP Application Deadline

### ISSUE THREAD

**Issue by tryhardest** [filecoin-project/devgrants#384]
We are working on a project in this space ancillary to our main work, but very interested to put more effort into it. We just learned of this grant which just closed yesterday. Would you be open to a 1 week or few day deadline extension here?

Thank you kindly.

**Comment by realChainLife** [comment]
Hi @tryhardest, glad to hear you have project to submit for this RFP. Happy to keep submissions open for you until until Friday, 5th November. Looking forward to your proposal.

**Comment by tryhardest** [comment]
Looking forward to submitting @realChainLife, thanks!
