### ISSUE TITLE
Next Step Microgrant: Pristorage

### ISSUE THREAD

**Issue by manhnvan** [filecoin-project/devgrants#385]
### 1. What is your project?
This application is similar to Google Drive but using IPFS/Filecoin as a cloud storage system and everything related to user management and data sharing based on NEAR smart contracts. Therefore, this application is fully decentralized, different from traditional centralized file storage applications

Github: https://github.com/manhnvan/decentralize_file_store_app.git
  
Demo: https://pristorage.surge.sh

### 2. How are you planning to improve this project?
Currently, Pristorage provides users to upload, manage their files and share them to the other users. Every feature is handle by a fully decentralized system.
If funded by Filecoin or Protocol Labs, Pristorage team will research and develop more features to bring more benefit to users and improve user experience, complete and release a desktop version which has some features like Dropbox. We expect to bring a completed file store solution in a full decentralize application.
 
### 3. Will the work be Open Source?
Yes, of course, the source code is available on Github with the [MIT License](https://github.com/manhnvan/Pristorage/blob/main/LICENSE): https://github.com/manhnvan/Pristorage
Please give any issues to us so we can make Pristorage better.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes, team will share a weekly report on the development progress of Pristorage, experience building on the technology we use such as NEAR, Filecoin, IPFS and Web3.Storage, and results of the microgrant-funded work.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
  Yes, my PR at [here](https://github.com/filecoin-project/community/pull/366)

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
  Yes, we are always waiting for comments [here](https://github.com/filecoin-project/community/discussions/358).

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

|      Name      |          Email          |              Github              |          Role          |
|:--------------:|:-----------------------:|:--------------------------------:|:----------------------:|
| Nguyen Van Manh|    manhnv@giong.network |     https://github.com/manhnvan  |  Primary Developer     |
| Tuan Pham Minh |    tuanpm@giong.network |     https://github.com/iamvon    | Mentor                 |

**Comment by SeedingTrees** [comment]
Thank you for this application.  Since you also applied for a NEAR grant for this project, we are waiting for the NEAR grant process to complete before we review this proposal for a microgrant.

**Comment by realChainLife** [comment]
@manhnvan closing this issue since we've approved proposal #380
