### ISSUE TITLE
Next Step Microgrant: eth.limo

### ISSUE THREAD

**Issue by eth-limo** [filecoin-project/devgrants#392]
### 1. What is your project?
eth.limo (LIMO) is an alternative to Cloudflare’s often unreliable eth.link service, LIMO functions as a drop-in replacement for eth.link; a Web 2.0 infrastructure stack for resolving Ethereum Name Service (ENS) records and associated IPFS content. LIMO allows users and dApp developers to effortlessly access and host static sites built with a combination of IPFS and ENS.

Repo: https://github.com/eth-limo/eth.limo
  
Example: https://esteroids.eth.limo

### 2. How are you planning to improve this project?
1. Migration of all infrastructure to AWS in order to improve scalability, reliability and
future feature development.
2. Development of a routing middleware layer for serving Skynet and Arweave content in addition to IPFS.
3. Addition of dynamic load-balancing tools to allow dweb developers to test new features and deployments via mechanisms such as canary and A/B traffic routing to alternative content hashes.
4. Dynamically route requests to Skynet and Arweave if the primary IPFS content is unavailable and said content exists on either Skynet or Arweave.
5. Privacy focused analytics and traffic stats for dweb sites.
 
### 3. Will the work be Open Source?
Yes, the project is currently available with an MIT license: https://github.com/eth-limo/eth.limo

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes.

### 6. Links and submissions
  
* Have you submitted to the Filecoin Community Showcase?

Not specifically, but we have been mentioned by the Protocol Labs Twitter account: https://twitter.com/IPFS/status/1440365461368016907

* Have you created a thread introducing your project in the community discussion board's?

No, however we have had several notable mentions in other venues:

1. Recently we were featured as the `#1` most clicked in "Week in Ethereum News" : https://twitter.com/WeekInEthNews/status/1440813161167216647
2. FleekHQ wrote an article featuring our project - https://twitter.com/FleekHQ/status/1437451952946810887

We also regularly work with the Esteroids team (@eyalron33) in order to better collaborate and understand the needs of the dweb community. 

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

N/A
  
### Additional questions:

Team:

https://eth.limo

https://github.com/eth-limo

ethdotlimo@protonmail.com

https://twitter.com/eth_limo

**Comment by SeedingTrees** [comment]
Thanks for your application.  Can you provide more details on how you plan to dynamically route requests to other protocols?

**Comment by eth-limo** [comment]
> Thanks for your application. Can you provide more details on how you plan to dynamically route requests to other protocols?

We would be creating a middleware router that checks the content hash value of a given ENS record (derived from the hostname of the request received by the reverse proxy) and then determines which backend to route the request to, for example if the content hash location is `/ipfs/` then route to our IPFS cluster, else if it contains `sia://` then route to Skynet, etc..

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
