### ISSUE TITLE
Next Step Microgrant: HEATDAO

### ISSUE THREAD

**Issue by HEATDAO** [filecoin-project/devgrants#393]
### 1. What is your project? (max 100 words)
HEATDAO aims to take the next step in bridging creators between IRL and URL. We will onboard dancers, performers, athletes and anyone who wants to move their body to web3 and enable them to capture their movements to be used across the metaverse. Our Movement Data Marketplace will open the door to collaboration, monetization, and provenance for dancers FOR THE FIRST TIME!

HEATDAO is empowering creators to bring motion capture data on chain and is making that data accessible and usable via IPFS.

Github repo:
https://github.com/HEATDAO/HEATDAO
  
Website: 
https://nft-marketplace-three-beta.vercel.app/)](https://nft-marketplace-three-beta.vercel.app/

### 2. How are you planning to improve this project? (max 200 words)
Developer bounties for:
  - Improving IPFS integration with our motion data pipeline
  - Improving our motion data storage framework
  - Improving motion data callability to blockchain-based virtual worlds
  - Improving speed to display file on marketplaces
  - Helping solve for cross-platform interoperability between virtual worlds

### 3. Will the work be Open Source?
MIT or GPL for code, CC for assets

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes, we will share weekly updates and a grant report.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions
https://heat.mirror.xyz/

* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
https://github.com/filecoin-project/community/discussions/392

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
https://github.com/filecoin-project/community/discussions/392

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  n/a

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Prof - community, operations - zeprof7695@gmail.com
Stav - community, operations - info@heat.ooo
Brady - lead creative, mocap god - pm.human.la@gmail.com
Milan - dev - https://github.com/milan-shrestha0017 - milanshrestha0017@gmail.com
Jin - Advisor - https://xrdevlog.com/

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
