### ISSUE TITLE
Open Grant Proposal: `Aletheia Data: Information accessible anytime, anywhere.`

### ISSUE THREAD

**Issue by aletheiadata** [filecoin-project/devgrants#394]
# Open Grant Proposal: `Aletheia Data: Information accessible anytime, anywhere.`

**Name of Project:**
Aletheia Data

**Proposal Category:** Choose one of `core-dev`, `app-dev`, `devtools-libraries`, `technical-design`, `docs`
`app-dev`

**Proposer:** 
`aletheiadata`

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Please respond with either "Yes" or "No"
YES

# Project Description

Aletheia is an Open Source project that seeks to encourage both public and private entities to facilitate access to public information so that it can have a more relevant social impact. We use IPFS as our secure File Storage. We'd like to integrate Filecoin to our system. This solution allows keep this public information (dominican republic gov) safe, secure, and always available. 

As developers we have seen the need to make use of public information (information in the public domain that should be available and accessible by law) but in the search we quickly realized that although the information is (in part) available, it is not organized in a way that is easy to use (uses that can be from the consultation of the data, to the elaboration of the same for statistical use or to create computer products oriented to citizens. Another problem that we frequently find is the lack of a standard in the format of these files. As well as the use of formats that DO NOT allow the extraction of information. We know that, like us, there are other Dominicans who need to access this data and that is why we decided to develop a REST API to facilitate access and distribution The objective is to create an ecosystem where these files are ALWAYS available, accessible 24 hours a day and accompanied by APIs to facilitate the consumption and exchange of this information, immutable and reliable "single source of truth".

## Value

This is a way to get into the governmental institution and promote the use of this tool in the public administration. If i don't do it right, the status quo will keep people uninformed with not reliable access to public information. This project has a level of complexity related to the big data component of it. 

## Deliverables

Our goal is build a system to store, index, and distribute public information (dominican republic) to the people by using the new technologies to garantee security, availability, and remove any redundant data.

### Milestone 1: Core, Security Layer

3 month: USD$15000

- Improve search and transform algorithms
- Pin all available IPFS files
- Integrate Web.storage
- Integrate Filecoin

### Milestone 2: Documentation and demos

1-2 month: USD$8000

- Improve Documentation and Demos

### Milestone 3: Community

1 month: USD$6000

- Create community
    - Weekly meetings
    - Discord / Slack channels
    - Email list
    - Governance rules
    - Promote to schools and institutions

### Milestone 3: Independence Day

4 month: USD$16000

- Create DAO
- Airdrop for contributors

## Total Budget Requested

Total: USD$45,000

## Maintenance and Upgrade Plans

In our plans for couple of years:
- Hotfixes at any layer
- Website, Admin, API and Storage layer support and maintenance
- Integrations with vendors, service updates
- Marketing and distribution of project

# Team

## Team Members

[Enzo Vezzaro](https://github.com/EnzoVezzaro) - Full Stack Engineer / Founder

## Team Member LinkedIn Profiles

[Enzo Vezzaro](https://www.linkedin.com/in/enzo-vezzaro/)

## Team Website

* GitHub Discussion: https://github.com/ipfs/community/discussions/697
* Email: aletheiadata@gmail.com
* Docs:  https://docs.aletheiadata.org
* Twitter:  https://twitter.com/DataAletheia

## Relevant Experience

For now I'm the only developer, but planning on hiring this way:
- Senior Backend developer with tech-lead and system architect role (NodeJS, IPFS, Filecoin)
- Senior Frontend developer (React, NodeJS)
- Junior Backend developer (Nodejs)
- Blockchain Developer

All other staff listed in roles we plan to attract as freelancers

## Team code repositories

https://github.com/Aletheia-Data

# Additional Information

We plan to facilitate the exchange of information in the dominican republic and build a DAO with enough economic incentive (trough tokenomics) to make the tool useful and economically viable.

**Comment by realChainLife** [comment]
Hi @aletheiadata thank you for the proposal. Can you outline within the proposal how you'll be working with Filecoin/IPFS, an overview of the technical development roadmap will also be great.

**Comment by aletheiadata** [comment]
Hi @realChainLife , thank you for your answer. 

Sure. So, our plants are as followed: 

Milestone 1: Core, Security Layer: 

- Development Backend - Improve Aletheia crawler
- Development Backend - Move from [NFT.storage](https://nft.storage/) to [WEB.storage](https://web3.storage/)
- Development Backend - Improve Security and Access
- Development Backend - Implement [and Test IPFS-store](https://github.com/ConsenSys/Mahuta) internally
- R&D - Integration with The Graph

We already work with IPFS, it's been used as our File System.

**Comment by realChainLife** [comment]
Hi @aletheiadata thank you for the clarification. We would like to fund the work outlined in your proposal. Please email devgrants@fil.org to discuss next steps.
