### ISSUE TITLE
21M: The Nakamoto Collection 

### ISSUE THREAD

**Issue by WhiteFlamingo** [filecoin-project/devgrants#395]
**Open Grant Proposal:** #1

**Name of Project: 21M:** The Nakamoto Collection

**Proposal Category:** app-dev

**Proposer:** James Tunningley - whiteflamingo

**Founder:** GermanEngineering

**(Optional) Technical Sponsor:** Ruben Amenyogbo, Dekanbro (Metacartel), Penguin (Evermore, Chievemint), Saimano (RaidGuild) 

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** 
Yes

**Project Description**

21M aims to address a critical friction in the web3 ecosystem.

Friction = Critical intellectual contributions to the web3 ecosystem are not recognised.

Problem(s) = This results in reduced velocity of overall development especially in the area of public goods. Instead it introduces a focus on short-term gains; ignoring high impact/long-term horizons contributions; and lacking rigour in publications.

Solution = An ultra-rare, universally recognised award expressing the community's appreciation (potentially NFT).

We are building the solution: 21M. 21M is a nonprofit, community-led DAO. Our vision is to become the universally recognised authority of excellence in web3. Our mission is to recognise outstanding achievements & contributions to the advancement of humankind. Our north star is to become the de-facto web3 community-based 'Nobel Prize'. Execution will entail a highly curated award ceremony hosted in the metaverse.

**Value**

21M has strong strategic alignment with Filecoin & IPFS. 

IPFS / Filecoin is committed to backing the world's most important data. Permanently. 21M will store a complete image of the lifetime work of all award winners on IPFS, providing it permanence via Filecoin. 21M therefore provides IPFS a platform to realise this ambition publicly while relying on the community to decide the contributions considered essential. 

Accordingly, 21M taps significant synergy pools with IPFS/ Filecoin across core strategic alignment, signalling, and lighthouse high-profile use-cases.

The benefits of getting it right:

- 21M will position “recognition” and ”value” at the core of the web3 movement. We will  provide a clear and transparent path to social capital for outstanding contributions that do not have immediate profit motives.
- A global purpose driven community connected and inspired by what makes the web3 ecosystem tick: community and shared WAGMI. 

The risks if we don't get it right:

- Missing incentives for blue field contributions and public goods. 
- Forgotten contributions - if not stored on FIL/IPFS - of those who came before us -> inability to “stand on the shoulders of giants”

Risks likely to make project execution difficult:

- Building the right mechanism design to incentivise participants - from voters on awards, to award nominees, to award nominators, to award sponsors to the wider non-voting audience.

**Deliverables**

Final deliverables for the Open Grant:

- Issue a refined RFP for the media production of the award ceremony
- NFT collection for price ceremony initiated (NFT.storage)
- "How might we series" content series launched with goal of 21M + fundraise
- Best-in-class DAO mechanism design for contributor payroll and recognition

**Development Roadmap**

Milestones:

1) Genesis Phase [concluded]

- Build MVP of highly productive DAO hyper- tuned to its purpose.
- Build resilient core team of star contributors native to web3
- Deep dive into existing award ceremonies to uncover frictions and disruption potential

2) Growth Stage [Focus of this grant]

- Milestone 1: Open community to public while maintaining integrity of purpose and gaining velocity (options to be explored including potentially gated referral programme) (2 people working on this: Whiteflamingo, Andischuster)
- Milestone 2: Issue RFP to production company (1 contributors working on this: German_engineering)
- Milestone 3: Launch content marketing ("How might we series") (3 contributors working on this: Sarah, Whiteflamingo, Germanengineering, Harisson)
- Milestone 4: Standup NFT roster for awards (Dekanbro, whiteflamingo, Penguin, Harrison) 

3) Scale Stage

- Execute award ceremony
- Execute full backup of lifetime achievements

**Full strategy and timelines (with dates) can be found here:** [Link](https://docs.google.com/presentation/d/1qXbd33jPi7JqR1Wtba-2nNY9TT2ySTSCN7rxSI9D9wU/edit)

**Total Budget Requested for the "Growth Stage"**

Total requested budget across all milestones: USD$50k.

Budget breakdown:
Milestone 1: USD $20k
Milestone 2: USD $10k
Milestone 3: USD $10k
Milestone 4: USD $10k

**Maintenance and Upgrade Plans**

Our long-term plan to maintain this software and upgrade it over time is: Indefinite. 
We are building a timeless brand as captured in our brand guide.

**Team: 8**

21M team members:

Key Contributors: 

- James Tunningley - Community Build
- Larry Florio - Legal Counsel
- Harisson Santos - Brand
- Sarah Hamburg - Award Process
- Andi Schuster - Productivity
- Staza Berlin - Admin
- Dekanbro - Engineering
- Founder: Ruben Amenyogbo

Advisors:

- Anthony Beaumont (Encode Club)
- Saimano (Raidguild)

**Team Member LinkedIn Profiles**

https://www.linkedin.com/in/james-tunningley/
https://www.linkedin.com/in/florio/
https://www.linkedin.com/in/harissonsantos/
https://www.linkedin.com/in/sarah-hamburg-phd-9510a910a/
https://www.linkedin.com/in/andreas-a-schuster/ 
https://www.linkedin.com/in/anastazja-berlin-9686981a2/ 
https://www.linkedin.com/in/dekan-brown-42b250182/ 
https://www.linkedin.com/in/rgjamenyogbo/ 

**Team Website**

https://21mxxi.com

**Relevant Experience**

Web3 Expertise: Kernel, Meta Cartel, LexDAO, Syndicate DAO, Ethermore, Metafactory and many others.

Functional expertise: We span expertise across: Venture Capital, Entrepreneurship, Engineering & Engineering Management, Crypto Law, Community Building, DAO Governance, and Filecoin/IPDS ecosystems.

**Team code repositories**

https://github.com/Achievmintry/achievmintry-web
https://github.com/MolochVentures/moloch

**21M Brand guide & Assets**
[Link](https://drive.google.com/drive/folders/1FD6x6oCyvjql1J5YRPcPROpqYIUaou07)

Pitch Deck (as included in development roadmap above)
[Link](https://docs.google.com/presentation/d/1qXbd33jPi7JqR1Wtba-2nNY9TT2ySTSCN7rxSI9D9wU/edit)

**Additional Information**

Diversity: we are proudly and vocally an inclusive team of diverse backgrounds - across culture, gender, sexual orientation and ethnicity. Our contributors are truly globally distributed.

M&A: 

- The "Achievemintry" brand is continued as “21M”

**Comment by realChainLife** [comment]
Hi @WhiteFlamingo thank you for this proposal. We would like to fund the work outlined here. Please email devgrants@fil.org to discuss next steps.
