### ISSUE TITLE
Next Step Microgrant: Provider.Quest - Add Historical Published Deal Data + Active/Slashed Deals

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/devgrants#397]
### 1. What is your project? (max 100 words)

Provider.Quest is a project to collect analytics data from the Filecoin blockchain. It is also a collection of notebooks on ObservableHQ with interactive visualizations that use the data.

https://provider.quest/

https://github.com/jimpick/provider-quest-spark

### 2. How are you planning to improve this project? (max 200 words)

The project currently slurps in all the published deals in real-time and publishes out a variety of datasets, reports, graphs and visualizations. However, this is an incomplete picture, as published deals might never go "active" (the provider failed to complete the sealing process), or the deal might have been slashed when the provider lost data or shut down prematurely. Also, our data is incomplete, as it only goes back to when we started scanning deals (June 2021). A complete set of deal data is available at https://lilium.sh/ which could be used to backfill our data. Also, we could collect "StateMarketDeals" data from the Lotus JSON-RPC API to figure out if deals are active or slashed. This data has been requested several times by members of the community and we'd love to do it for them. Additional UI/publishing work is needed to support selecting historical date ranges in the notebooks.

### 3. Will the work be Open Source?

Yes, MIT+Apache. Data is CC-BY-SA 3.0.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes.
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes.

### 6. Links and submissions
  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?

https://github.com/filecoin-project/community/blob/master/projects/application/miner-report-en.md

(I will do a PR to update the project name as it was rebranded as "Provider.Quest")

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?

https://github.com/filecoin-project/community/discussions/208

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

N/A
  
### Additional questions:

* For each team member(s), please list name, email, Github account, and role in the project.

Jim Pick, jim@jimpick.com, @jimpick - sole contributor

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

N/A

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
