### ISSUE TITLE
Next Step Microgrant: Pluskit

### ISSUE THREAD

**Issue by PluskitOfficial** [filecoin-project/devgrants#398]
### 1. What is your project? (max 100 words)
Pluskit is a Fil+ eco-tools platform dedicated to providing functional, operational and typole-rich tools and plug-ins for eco-participants. It now provides data board of General Verification to help eco-users easily and clearly know the status of DataCap application and allocation.

It uses Python3.0 language and the overall framework uses Django, which conforms to the restful style. The database uses mysql8 and sets indexes in key fields. Due to the huge amount of data, Redis is used as the cache, which will greatly increase the speed of interface return, improve the user experience, and contribute to the development of IPFS.

GitHub：https://github.com/PluskitOfficial/Pluskit
  
Website: https://pluskit.io/

### 2. How are you planning to improve this project? (max 200 words)
We have three plans in the next step:

-Develop Large Datasets Board and Automatic Verification Data Board, containing the status of DataCap applications, allocations and storage, to help ecological users understand the reality of verified data storage.

-Launch 1~2 tools of DataCap allocation and recording to help reduce DataCap acquisition-allocation time.

-Carry out a round of promotion to let more people know and use our products, so as to help more users in the ecosystem.
 
### 3. Will the work be Open Source?
 Yes, the work will be Open Source.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes, Of course.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions

  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
Yes

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
https://github.com/filecoin-project/community/discussions/390

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Product Manager：chic，https://github.com/chicChang
Front-end developer：jiaming，https://github.com/zhf0437
Backend developer：Mr. Zhou,https://github.com/EzrealoveQXY

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by KwrayFF** [comment]
Looking forward to seeing more of this!

**Comment by SeedingTrees** [comment]
Hi, folks.  I would like to approve this microgrant but I need at least one email address.  Can you please message back with one or more email addresses for a team member?

**Comment by PluskitOfficial** [comment]
@SeedingTrees

**Comment by PluskitOfficial** [comment]
@SeedingTrees 
Sure, PluskitOfficial@163.com  or  julywu999@gmail.com. Thanks!

**Comment by PluskitOfficial** [comment]
Dear Sir or Madam,
I have left our email addresses in the comment of the issue.
They are ***@***.*** or ***@***.***

If any further information is needed, please tell us.
Hope to hear from you.


| |
pluskitofficial
|
|
***@***.***
|
On 12/11/2021 ***@***.***> wrote：

Hi, folks. I would like to approve this microgrant but I need at least one email address. Can you please message back with one or more email addresses for a team member?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
