### ISSUE TITLE
Open Grant Proposal: GuildsDAO

### ISSUE THREAD

**Issue by WizardOfAus** [filecoin-project/devgrants#401]
### 1. What is your project? (max 100 words)
GuildsDAO is a DAO building and maintaining a decentralised 'Glassdoor for DAOs'. People can submit a DAO, find onchain information on the DAO and review them. The site and reviews are aimed at helping people learn more about a particular DAO and insights into a DAO a 'community vibe' check. To submit a review on GuildsDAO, a user must sign the review with their wallet. The public address is then checked to see whether the user meets the minimum membership requirements for the DAO they are reviewing, and then masked. This enables users to submit anonymous but 'verified member' review.

[GuildsDAO Website](https://guildsdao.com/)

### 2. How are you planning to improve this project? (max 200 words)
The next step for GuildsDAO is providing more on-chain information on DAOs and to also create further decentralisation through making the data public or onchain. This will be done with improved links to IPFS and possible use of OrbitDB. Other possible avenues in improving the current project is to develop a protocol on how one may submit a decentralised trusted 'verified' but masked pubic address content submission. This will enable people to create censorship-resistant and decentralised reviews. I am looking for grant support to help pay for DAO bounties.
 
### 3. Will the work be Open Source?
Yes. GPL and CC-BY-SA 3.0.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes.

### 6. Links and submissions
  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
Not yet.

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
Not yet. This is TBD alongside the Community Showcase.

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Did not begin at a hackathon.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Daniel, informationdyz@gmail.com, WizardOfAus, Maker

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
  Not done at a hackathon

**Comment by Bhakti087** [comment]
You can also add the community link of GuildsDao , if their are any !

**Comment by ErinOCon** [comment]
Hi @Bhakti087, I am very sorry for this delayed response. Are you still interested in microgrant funding for this work? If so, can you provide a working website and repo link?

**Comment by WizardOfAus** [comment]
Hey @ErinOCon I am the creator of  this project. I have actually made significant progress on this and would be interested in an Open Grant. The project has been renamed and there are much more features. Would it be better if I start a new application?

**Comment by ErinOCon** [comment]
Hi @WizardOfAus, that's great news! Yes, please open a new issue using the applicable [template](https://github.com/filecoin-project/devgrants/issues/new/choose). I will close this one.
