### ISSUE TITLE
Next Step Microgrant: Avatar Metaverse

### ISSUE THREAD

**Issue by ZhangPeibin** [filecoin-project/devgrants#402]
### 1. What is your project? (max 100 words)
Avatar Metaverse is an identity avatar metaverse that uses Filecoin to store the underlying identity. We use a combination of avatar NFT and wallet address and DID constructs Metaverse's identity system. With such a decentralized identity,
A permanent, time-stamped record of personal achievements, contributions, interests, and activities to date can be made.

  https://github.com/ZhangPeibin/AvatarMetaverse

https://www.avatarverse.me/

### 2. How are you planning to improve this project? (max 200 words)
There are a few plans next:

1. Complete the mint process of Avatar NFT
2. Increase nft market
3. Connect to Opensea
4. add user did system

 
### 3. Will the work be Open Source?
yes

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

Yes
  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
  
https://github.com/filecoin-project/community/pull/360

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
  
  
https://github.com/filecoin-project/community/discussions/370

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Yes，https://xathon.mettl.com/event/MarsAsiaHackathon2021.
  we won third prize in this Hackathon.
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  peibin , wiki4zhang@gmail.com,https://github.com/ZhangPeibin
* If your project was created as part of an event or hackathon:
  * What was the name of the event?
   MarsAsiaHackathon2021
  * Please link to your hackathon submission
https://xathon.mettl.com/event/MarsAsiaHackathon2021
（this hackathon2021 didn't show winner,but you can get it here : https://twitter.com/LabsLumos/status/1464498281896054784  ）

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
