### ISSUE TITLE
Open Grant Proposal: Filecoin Green - Solar Solutions

### ISSUE THREAD

**Issue by DcentHosting** [filecoin-project/devgrants#406]
**Name of Project:** Filecoin Green - Solar Solutions

**Proposal Category:** core-dev

**Proposer:** DcentHosting

**Technical Sponsor:** @redransil https://github.com/redransil

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes

_# Project Description_
Since the early days of Crypto, power usage has been a subject of discussion. How much energy does any particular blockchain deserve to actually consume? That is a difficult one to answer. At this moment, a lot of organisations around the world are facing pressure to reduce their power consumption and make the shift to renewables. 

**We would like to be at the forefront of this shift and show the world what is possible.**

Filecoin has already greatly reduced the consumption of electricity by not only changing the mining protocol, but also making the actual power needed for blockwins an valuable asset. 

Dcent Hosting B.V. in collaboration with Filecoin Green wants to build the tooling to make the environmental impact of being a storage provider more transparent. We will also offset our global power consumption with 100% solar energy, generated on top of our own facility. We will be able to publicly show when the rig is running on solar and when it is running using the grid, with the ability to separately meter the production, consumption, and grid connection. 

_## Value_
One of the reasons this project is so valuable to the Filecoin ecosystem is that we make it easy for all storage providers worldwide to follow in our footsteps. We will keep a full documentation from day one that successors can follow step by step to make their site as efficient and green as possible. In addition to the documentation, we are developing several software tools internally using the APIs of inverters and our energy suppliers. This tooling can be used by the Filecoin community to make their energy usage transparent on-chain.

The difficult part about this system is the variations between different countries, energy suppliers and possible collocation. In some areas more developments are needed per individual provider for this project to succeed. Providers might not be able to install solar, or use the data from the inverters because they are using the collocation of an already existing datacenter. Therefore we might be able to assist them with making power usage of their servers visible, but we are not able to support them with the solar installation and data extraction.

_## Deliverables_
The functionalities we will make available after the completion of this project are:

**Detailed ROI:**
Detailed return on investment sheet for providers to compare their numbers. This way they can easily see if a solar solution is something that will fit their case.

**API Tooling:**
We will develop the API's necessary for data extraction for the inverters, utility companies and all necessary data center components. With these software tools storage providers are able to easily upgrade their systems and make their consumption visible on chain.

**Documentation:**
Documenting the whole process from start to finish, creating a complete manual for this project to make it as easy as possible for other providers to apply the same. We will also write out a separate document explaining how the power usage is drawn from components affiliated with storing Filecoin data.

**Audits:**
After the solar installation and API tooling implementation we will be audited by a seperate company. The audit reports will be shared with the community to get an even clearer picture of the installation and execution. With this report they are also able to set a quality standard for their own solar project developers.

**## Development Roadmap ## Total Budget Requested**
<img width="2121" alt="Application Solar" src="https://user-images.githubusercontent.com/95493190/144868223-48c26e9e-e0a9-4aca-ba07-4112d8e9ad92.png">

_## Maintenance and Upgrade Plans_
We ourselves have an extremely strong interest in keeping these API links functioning. In the coming years, the data center will continue to grow, and insight into our energy consumption and generation is crucial.

The inverters are expected to last about ten years under warranty. The APIs of these systems will most likely remain unchanged. We expect to upgrade our tools when required due to Lotus updates, security patches or Filecoin Green requests. All updates will be visible through our Github account and announced publicly.

_# Team_
_## Team Members_
Hidde Hoogland
Wijnand Schouten
Alan Ransil (Filecoin Green)

_## Team Member LinkedIn Profiles_
https://www.linkedin.com/in/wijnand-schouten-764a6412/
https://www.linkedin.com/in/hidde-hoogland-a68b7b1a/
https://www.linkedin.com/in/alan-ransil-53573873/

_## Team Website_
https://dcent.nl

_## Relevant Experience_
The team behind Dcent Hosting B.V. has a lot of knowledge and experience in the two main areas of this application.

Hardware Efficiency & Solar.

Hidde has spent the last four years developing and maintaining one of the largest Dutch Ethereum farms. During this project his main goal is always to operate as efficiently as possible. Energy costs and heat were in fact the biggest enemies of the operation. Through these experiences he has a good view on maximising the efficiency of hardware and air conditioning. 

Wijnand has spent most of his early life as an network engineer, maintaining the largest USP in the Netherlands while constructing and maintaining his own Datacenter in the middle of Amsterdam. After that business was sold he founded his own Solar company, which is now maintained by his Family due to being occupied full-time as a Filecoin storage provider. 
There is no one around with more knowledge on renewables and solar installations than he has.

_## Team code repositories_
https://github.com/cryptowhizzard

_# Additional Information_
If anyone has any questions about our proposal please reach out to me through this issue or by sending an email to info@dcent.nl.

**Comment by mishmosh** [comment]
Thank you for your submission! We review applications regularly and you should hear an initial response from us within one week.

**Comment by realChainLife** [comment]
Hi @DcentHosting thank you for this proposal. We would like to fund the work outlined here. Please email devgrants@fil.org to discuss next steps.
