### ISSUE TITLE
Next Step Microgrant: NFT Uploader

### ISSUE THREAD

**Issue by resrugam** [filecoin-project/devgrants#407]
### 1. What is your project? (max 100 words)
NFT Uploader is a simple NFT upload tool aimed at digital art creators who do not understand the crypto digital currency market and who do not need to have any programming skills or relevant financial knowledge about the blockchain. The data uploaded by the user is saved on our platform to our IPFS cluster and backed up in NFT.Storage, and finally the user's work will be available on the OpenSea platform.

Github repo：under constcucation
Website：under constcucation

  

### 2. How are you planning to improve this project? (max 200 words)
We tried to tie it to IPFS retrieval, where a work can be left with multiple backups to keep the data safe.
Support for more forms of NFT types, not just images

 

### 3. Will the work be Open Source?
Yes, NFT Uploader will be open source under the MIT license for code.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes, we agree to share weekly updates and a grant report upon conclusion

  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes, this proposal complies with the Filecoin Code of Conduct.

### 6. Links and submissions

  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
Not yet.
  

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
 Not yet.
  
  

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 Not yet.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

| Name   | Email                   | Github   | Role    |
| ------ | ----------------------- | -------- | ------- |
| Johnny | lcapobiancobo@gmail.com |@resrugam | Creator |

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by SeedingTrees** [comment]
Thanks, Resrugam.  Our microgrants are intended for projects that have already begun and are showing progress.  If you need help getting this off the ground, please join one of the Slack channels for Filecoin or IPFS builders.  I'm going to mark this application as closed.  Please submit a new application after you have made progress and can share the repo or a demo.
