### ISSUE TITLE
Next Step Microgrant: <Decanet>

### ISSUE THREAD

**Issue by Njvdwes** [filecoin-project/devgrants#408]
### 1. What is your project? (max 100 words)
 Decanet will be dependant on the helium network but will be a platform where we get people in communities to host the helium hotspots in return for free inyernet and a small fee , these hotspots will remain open ,no security protocol , and with this in a country like south africa , where internet is something 80% of south africans have no access to. But a decentralized open source free to use network with 1000's of hotspots , will be successful, especially since its completely self sustainable .filecoin can then be linked directly to this growing network as the cloud host . Benefits a country and 2 decentralized economies.

none needed , because whats needed exists , i need help financially to get it started and also to with networking parts

### 2. How are you planning to improve this project? (max 200 words)
As mentioned above , Decanet will financially funding its own growth , this will mean expansion for filecoin, helium accross a the continent of Africa. Unfortunately in south africa , corporations have started deploying hotspots to benefit nobody but themselves , the rich get richer here , even incorporating things like the planetwatch blockchain and deeper networks DPN with its DPR coin can mean that exponential growth could be upon us rapidly . I have a network for deployment from cape town to Johannesburg , i just need the help and guidance to make it happen
 
### 3. Will the work be Open Source?
the work used will be from already existing frameworks which are open source now so i see no reason why not to leave it open , just relying on something like DPN to protect against attacks . We could then fund so many more ideas or reinvest into development partners . Decanet is a passion project for me . And maybe a future for my family and millions of others accross Africa.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
I will provide weekly reports , monthly reports and gather feedback from lives we change . Publicity is what drives passion projects , a change That could change the worth . 
  
### 5. Does your proposal comply with our Community Code of Conduct?
 I dont see any way that i do violate the code in any way , though if i do , with guidance we can rectify this and make it fall in line with all guidelines.

### 6. Links and submissions
 
  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?No
  

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?No
  
  

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:None
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
This is solely my idea , Nicholas van der Westhuizen , njvdwes@gmail.com github mail address
Credit to: Ruan Huisamen , IT specialist that does help me understand certain things . 
Credit also : Alwyn van Zyl , been pointing out projects like these to post ideas .
* If your project was created as part of an event or hackathon:None
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)None 
  * Please link to your hackathon submission

**Comment by SeedingTrees** [comment]
Hi, folks.  Our microgrants are intended to support projects that show demonstrated progress.  I am going to close this application.  Please submit a new application once you have made progress and can share a repo or demo.
