### ISSUE TITLE
Next Step Microgrant: CID gravity Basic deal rate protection for retrieval market

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/devgrants#409]
### 1. What is your project? (max 100 words)
CID gravity enable markets for storage-providers by providing tooling to manage storage-market and (retrieval market) through this Microgrant

CID gravity connector repo : https://github.com/CIDgravity/CIDgravity-X
 
CID gravity homepage : https://cidgravity.com

### 2. How are you planning to improve this project? (max 200 words)
Storage-providers have concern with recent retrieval deals requests. Some clients initiate to many deals request in parallel, crashing storage-providers miners. To protect their miners, storage-providers think of disabling retrieval deals which has a negative impact for their reputation and the network. We propose to quickly give them a solution to limit the number of inbound request per client. So they will keep the ability to serve multiple clients in parallel and throttle them.     

This request comes from the CID gravity community and the minerX fellows. 
 
### 3. Will the work be Open Source?
CID gravity is partially opensource. All the code deployed on the miner is opensource, the platform code is not. 
This work will be mainly on the platform side. 

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Definitely, all our releases are publicly communicated on the Filecoin slack : #fil-lobby  and all storage-providers related channels. 
  
### 5. Does your proposal comply with our Community Code of Conduct?
YES

### 6. Links and submissions

  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
  

* Have you created a thread introducing your project in the community discussion board's 
many, here is the last annoucement and video presenting the product
https://filecoinproject.slack.com/archives/CEHTVSEG6/p1637341386402300
https://youtu.be/FghO20DdEgg?t=1724
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Julien Noël - CEO / Slack : Julien Noel - CID gravity
Florian Ruen - Head of Dev / Slack : Florian Ruen - CID gravity

**Comment by SeedingTrees** [comment]
Hi, folks.  I would like to approve this application but I need an email address to which I can send the payment instructions.  Can at least one of you add an email address here?

**Comment by s0nik42** [comment]
julien.noel@cidgravity.com

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

**Comment by ErinOCon** [comment]
@s0nik42 Thank you for reaching out to our team! Please complete the final grant repot [here](https://github.com/filecoin-project/devgrants/issues/603).
