### ISSUE TITLE
verses

### ISSUE THREAD

**Issue by jazzminewang** [filecoin-project/devgrants#412]
# Open Grant Proposal: `Verses.xyz`

**Name of Project:** Verses.xyz

**Proposal Category:** `docs`

**Proposer:** `@verses-xyz`

**(Optional) Technical Sponsor:** `miyazono`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** "No"

verses will author 
  verses 
compact, meaning-laden artifacts 
      _poems!_
advocating for / demonstrating / gesturing towards
                        a pluriverse: a world where many worlds may fit 

we sit around the fire
soup brimming with
offerings of scented thyme,
stones, boundary objects

we see a world
and imagine another, 
where many worlds might fit

we write and read new old maps
build and bury new old ground
   to be a good ancestor is to grasp 
an intergenerational reciprocity
 embers passed from hand to hand

 
we move within hyperobjects
with the knowledge that
  we walk, as all have walked
in history, interdependent

we sing for a world where all may sing
for a chorus singing, full throat
without center and within many centers 

we hold existential risk
as the risk of losing possible worlds
cutting branches before bloom
the best way to foreclose the future
is to never let it grow

we dance towards 
a future that has a future

## Total Budget Requested
$100,000

## Team Members
Jasmine Wang
Daanish Shabbir
Jacky Zhao
Raymond Zhong
Divya Siddarth
and many others

## Team Website
https://verses.xyz

**Comment by realChainLife** [comment]
Hi @jazzminewang thank you for your proposal and for the poem, however its not sufficient to approve this grant. Can you share additional details based on the questions in the [application template](https://github.com/filecoin-project/devgrants/issues/new?assignees=realChainLife&labels=&template=open-grant-application.md&title=). Closing this issue so you can submit a new proposal. If you have additional questions about our grant program, please reach out on filecoin.io/slack at #grants-questions
