### ISSUE TITLE
Metaverse School

### ISSUE THREAD

**Issue by taoshengshi** [filecoin-project/devgrants#413]
# Open Grant Proposal: `Metaverse School`

**Name of Project:** Metaverse School

**Proposal Category:**  `Community`, `Metaverse`

**Proposer:** `KEN Labs`

**(Optional) Technical Sponsor:** `Colin`,`Lukas`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** "Yes"

# Project Description

The Metaverse is currently getting a lot of attention in China (not just in the blockchain space).Expect that IPFS-based Metaverse companies to get a runway, and perhaps, in the near term, it is an opportunity to incubate more IPFS-based Metaverse startups.

Protocolin suggested KEN Labs to organize a hackathon for Metaverse on IPFS, I am discussing the plan with the team to involve more people from outside the Filecoin mining industry (even outside the blockchain industry, aka. web2) into the IPFS ecosystem.

So we need more standard content to reach more geeks. For example, we can refer to ProtoSchool and NFTSchool to build a Metaverse school:

- Welcome to NFT School | NFT School: https://nftschool.dev/
- ProtoSchool | Interactive tutorials on decentralized web protocols: https://proto.school/

And we could invite the industry’s Metaverse pioneers, such as KEN Labs, Outlier Ventures, …etc to deliver a Metaverse knowledge website and a series of courses.

Prototype: https://school.kencloud.com/

## Value

The Metaverse will require the transferring of A LOT of data. Distributed, peer-to-peer file systems like IPFS&Filecoin could provide the backbone of the decentralized Metaverse.

All web2 developers are paying attention to the Metaverse now. But for Web2 developers , they don't know what the basic building blocks of the Metaverse. There is a huge cognitive gap.

This website and course, designed specifically for IPFS and Filecoin, will provide a comprehensive introduction to IPFS and Metaverse, which will be of great help to a large number of developers.

For example the Building blocks of Metaverse:
```
LIBP2P – a peer-to-peer modular network stack, it underlies IPFS, Filecoin, Ethereum, Polkadot and a lot of other protocols.
LIBP2P is a way in which many nodes in Web3 interact with each other to pass along messages, communicate, find and distribute contents and so on. This is a layer where it can be extremely useful and valuable for many groups to explore building new kinds of protocols and other things.

IPFS – a protocol makes the web peer-to-peer, it is the content and data platform of Web3.
IPFS enables content addressing with CIDs, which are content identifiers that allow hash linking from one piece of content to another, this can make the piece of content verifiable and the distribution of that content secure so that nobody can tamper with the content. IPFS builds a huge and growing ecosystem, there are thousands of applications, millions of websites, excellent dev tools, browsers, DeFi joining in this iPFS ecosystem.

Filecoin – the storage network of Web3, it is a crypto powered storage network structured as a two-sided market where on one side there are clients that want to hire the network to store data and on the other side there are miners that want to store the users’ data.
```

Since the Metaverse concept is so broad, I’m not sure there should be such a limit for the scope to encourage more web3-oriented (around Filecoin and IPFS) Metaverse builders.

## Deliverables

The final deliverable for this project will be a website of Metaverse school like ProtoSchool and NFTSchool :
- Welcome to NFT School | NFT School: https://nftschool.dev/
- ProtoSchool | Interactive tutorials on decentralized web protocols: https://proto.school/

The details and architecture of the website refer the prototype :https://school.kencloud.com/

## Development Roadmap

Project Milestones:
Milestone 1 -- 2 weeks
Build a prototype website and design the architecture of Metaverse knowledge.

Deliverable: Build the website in Vuepress, and uses Vue/JavaScript for functional code and Markdown for post content.Desgin the architecture of Metaverse knowledge repository contains code and content for the Metaverse School website, an open-source community education platform devoted to core concepts, best practices, tutorials, showcases and so on.
```
the draft Metaverse architecture as below:

* Prequel
* Definition
* Framework
  - framework for the Metaverse
  - hardware
  - networking
  - compute
  - Virtual platforms
  - Interchange tools and standards
  - Payments payment rails and blockchains
  - Content services and asset businesses
  - Evolving user and business behaviors
* Buidl
  - Open Metaverse OS
    - hardware infrastructure
    - software backend
    - IPFS
    - filecoin
    - connecting the Metaverse with IPFS
    - World primitives and rules
    - In-world assets
    - End user hardware
    - End user software
    - bridges
  - Web3 Toolbox
    - Peer-to-peer networks 
    - Transaction layer 
    - Programmability layer 
    - Decentralised finance 
    - Nfts - sovereign virtual goods 
    - Decentralised governance 
    - Decentralised cloud services 
    - Self sovereign identity 
    - Agents

Resource
```
Metrics:
Openverse community review

Milestone 2 -- 2 weeks
Metaverse Prequel

Metrics:
Cover the history of Metaverse.

Milestone 3 -- 2 weeks
Metaverse Definition

Metrics:
Cover the mainstream definition of Metaverse.

Milestone 4 -- 4 weeks
Metaverse Framework

Metrics:
Cover the mainstream Framework of Metaverse.

Milestone 5 -- 4 weeks
Cover the building blocks of Metaverse.

Metrics:
Successful Metaverse website deliver.

## Total Budget Requested

| Milestones | Description | Time | Project Owner | Budget | 
| :--- | :------ | :--- | :--- | :--------: | 
| Milestone 1 | define architecture and build website      |  2 Weeks    |  William Yang    |   5,000         |
| Milestone 2 | Prequel      |  2 Weeks    |  William Yang    |   5,000         |
| Milestone 3 | Definition      |  2 Weeks    |  William Yang   |   5,000         |
| Milestone 4 | Framework      |  4 Weeks    |  Taosheng Shi    |   10,000         |
| Milestone 5 | Buidl      |  4 Weeks    |  Taosheng Shi     |   10,000         |
| Maintenance | content updated as the ecosystem develops.     |  1 year    |  William Yang    |   20,000         |
| Bounty | get the community engaged in Metaverse shcool building.     |  1 year    |  William Yang    |   15,000         |

Total Budget: $70,000

## Maintenance and Upgrade Plans

We will maintain the website as a window to Metaverse information. The information will be updated as the ecosystem develops. 

We will also use the strength of the community to get more people involved in the construction of the Metaverse school.

# Team

## Team Members

Taosheng Shi
William Yang

## Team Member LinkedIn Profiles

Taosheng Shi , Researcher and founder of KEN Labs.
https://www.linkedin.com/in/taoshengshi/

Abel Cao, former RavenTech CTO of Baidu. He has more than 20 years of experience in Internet applications, embedded systems and other hardware and software development. He has served as research and development director and CTO of several startups. He is now focusing on building the Cloud 2.0 of Web3.
https://www.linkedin.com/in/wireless-com/

William Yang: 15+ years of experience in Internet development. He was an architect of Nokia's wireless and an senior engineer of AOL. He is currently the chief architect of KEN Labs.
https://www.linkedin.com/in/william-yang-40047910/

Yongxing Liang: 20+ years of software industry experience, 6-Sigma black belt, with extensive experience in human resource management, innovation management and business expansion.He is currently manage priority and delivery of the project, Project manager of KEN Labs.
https://www.linkedin.com/in/yongxing-liang/

Xu Qiang(Ben), senior engineer - Head First IPFS @ KEN Labs
https://www.linkedin.com/in/ben-xu-4552a5101/

Aaric Chen, fullstak engineer
https://www.linkedin.com/in/aaric-chen-a84545137/

## Team Website

[KEN Labs](https://kencloud.com/)

## Relevant Experience

KEN Labs is the software engineering leader of the blockchain space,The core members of KEN Labs have over 10 years of experience in distributed storage and blockchain. KEN Labs' vision is to build Cloud 2.0 for Web3, which is infrastructure layer of the Metaverse. KEN Labs's full-stack Computation & Storage products help developers build next-generation Clouds and enable enterprises to launch more powerful web3 infrastructure.

## Team code repositories

[KEN Labs GitHub](https://github.com/kenlabs)

# Additional Information

**Comment by lksbrssr** [comment]
Thanks - excited to see this here! A couple of thoughts from my end:

- Let’s make sure we enable community contributions to this metaverse school
- Kenlabs should drive this initiative and also concert/coordinate the various efforts to develop a metaverse school
- To help with that, PL should make sure Kenlabs is connected to the various other stakeholders (i.e., members of the #openverse channel on FIL Slack) and make sure the community is aware of this effort
- Additionally, our Developer Advocate team (e.g., Longfei) should be in touch with Kenlabs throughout this effort to help provide feedback and ideas

**Comment by realChainLife** [comment]
Hi @taoshengshi thank you for the proposal. We would like to fund the work outlined here, lets discuss next steps.
