### ISSUE TITLE
Next Step Microgrant: Miner-tools 2

### ISSUE THREAD

**Issue by luluup777** [filecoin-project/devgrants#414]
### 1. What is your project? (max 100 words)

Recently, it has been observed that multiple miners have completely lost power due to unexpected circumstances. This is a huge loss for both the miners and the filecoin network.

This is `filecion-box`to facilitate miners to better participate in filecoin. This `filecion-box` plans to add two project:

- Redo program with scheduling
- wdpost server

https://github.com/filecoin-box

### 2. How are you planning to improve this project? (max 200 words)
1.Redo program with scheduling

- Multi-machine redo sectors. supports the redo of sectors based on deadline and partition, and supports the redo of custom sectors

2.wdpost server

- Simple to quickly start the wdpost service that supports multiple miners.

### 3. Will the work be Open Source?
yes

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
yes

### 5. Does your proposal comply with our Community Code of Conduct?
yes

### 6. Links and submissions
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
  https://github.com/filecoin-project/community/pull/412

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
  https://github.com/filecoin-project/community/discussions/352
### Additional questions:

| Name      | Email             | Github                       | Role      |
| --------- | ----------------- | ---------------------------- | --------- |
| luluup777 | luluup777@163.com | https://github.com/luluup777 | Developer |

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

**Comment by luluup777** [comment]
> This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

Merry Christmas!
