### ISSUE TITLE
Next Step Microgrant: Haiphen AI

### ISSUE THREAD

**Issue by haiphenAI** [filecoin-project/devgrants#416]
### 1. What is your project? (max 100 words)
 A digital copyright to sign http requests with a traceable signature the owners can use to manage access to their APIs. 

 https://github.com/haiphenAI/digital-copyright
  
 https://haiphenai.com

### 2. How are you planning to improve this project? (max 200 words)
 Leveraging filecoin currently. Intending to build a decentralized network of API nodes similar to 'The graph' (for storage)
 
### 3. Will the work be Open Source? 
 To the community yes. Will charge for enterprise solution

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
 Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?
 Yes

### 6. Links and submissions
 Yes
  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
   Not sure what this is?

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
   https://github.com/filecoin-project/community/discussions/413
   https://github.com/filecoin-project/community/discussions/413

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: n/a
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project: Jude Safo, CEO, pi@haiphenai.com, https://github.com/judesafo/digital-copyright
* If your project was created as part of an event or hackathon: no
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
