### ISSUE TITLE
KEN Labs Education

### ISSUE THREAD

**Issue by taoshengshi** [filecoin-project/devgrants#417]
# Open Grant Proposal: `KEN Labs Education`

**KEN Labs Education:**

**Proposal Category:** `Community`, `Metaverse`

**Proposer:** `KEN Labs`

**(Optional) Technical Sponsor:** `Cloin`,`Lukas`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** "Yes"

# Project Description

The metaverse is currently getting a lot of attention in China (not just in the blockchain space). Almost everyone is talking about it. We can expect a wave of startups in the metaverse late this year or early next year which will be similar to the wave of mobile Internet startups in 2010.

In this context, We plan to launch KEN Labs Community, a nine-month programme in collaboration with Filecoin and IPFS, in China.

This Community will phase into three stages — a KEN Labs Education series, a Metaverse-dedicated hackathon and a follow-up accelerator.

Base on Lukas 's suggestion, this application is just for education series.

The purpose of the KEN Labs Education is to teach students about Metaverse through the lens of IPFS. Over 100+ university blockchain communities and students from all corners of China will be participating in this series.

Build a Metaverse school website, in conjunction with CDSN and InfoQ, to get more developers engaged in learning and building.

The educational series is expected to be released in December and run for three months through the Chinese Spring Festival. New Year's Eve speech and education training have become a mature mode in China, which is a very good timing for students to participate in IPFS learning during the holidays. The series will be of tutorials, developer guides or videos which will be hosted on the mainstream social media platforms in China.

A Metaverse school website will be deployed separately, with a dedicated task force. Similar to NFT School, we need to collaborate with members of the Protocol Labs and Metaverse ecosystem.

Considering the characteristics of Chinese programmers, there are two directions of work that are critical to a successful hackathon:
- Develop high quality education courses
- Let entrepreneurs share more creative ideas in IPFS

Refer the prototype of KEN Labs education :
https://kencloud.com/educate.html

## Value

Accelerate IPFS/Filecoin Metaverse adoption
- Build China’s biggest IPFS and Metaverse curriculums for students, researchers and hackers
- Involve the web2.0 technology community, such as CSDN and infoQ, the largest developer community in China
- Promote Metaverse worldwide
- Set up domain standards and specifications in Metaverse
- Teach necessary skills in various aspects of Metaverse
- Strengthen developer communities
- Connect companies and groups to boost Metaverse development
- Foster a world class Metaverse ecosystem of developers and entrepreneurs

## Deliverables
Due to too much content, I sorted out the course structure as follows, please refer to Google Doc for details(Curriculums of KEN Labs Education):
https://docs.google.com/document/d/1RVDBnalcttF65zkZGhyni0Uitmu7VuoGZ1gjMx-dIKM/edit?usp=sharing

| Sections | Description | Content Build Time | 
| :--- | :------ | :--- | 
| Section 1 | Libp2p      |  2 Weeks    | 
| Section 2 | IPFS      |  2 Weeks    |  
| Section 3 | IPFS Compute & FVM      |  2 Weeks    |  
| Section 4 | Filecoin      |  2 Weeks    |  
| Section 5 | Metaverse      |  2 Weeks    |  
| Section 5 | Web3      |  2 Weeks    |  

## Development Roadmap

Project Milestones:

Milestone 1 -- 2 weeks
Build KEN Labs Education website 
Deliverable: KEN Labs Education website with content updated regularly(step by step).
Metrics:
easy for use by community.

Milestone 2 -- 2 weeks
Libp2p curriculum
Metrics:
All the curriculums delivered by recording video.

Milestone 3 -- 2 weeks
IPFS curriculum
Metrics:
All the curriculums delivered by recording video.

Milestone 4 -- 2 weeks
IPFS Compute & FVM curriculum
Metrics:
All the curriculums delivered by recording video.

Milestone 5 -- 2 weeks
Filecoin curriculum
Metrics:
All the curriculums delivered by recording video.

Milestone 6 -- 2 weeks
Metaverse curriculum
Metrics:
All the curriculums delivered by recording video.

Milestone 7 -- 2 weeks
Web3 curriculum
Metrics:
All the curriculums delivered by recording video.

## Total Budget Requested

| Milestones | Description | Time | Project Owner | Budget | 
| :--- | :------ | :--- | :--- | :--------: | 
| Milestone 1 | Education Website      |  2 Weeks    |  William Yang    |    10,000           |
| Milestone 2 | Libp2p      |  2 Weeks    |  William Yang    |    10,000         |
| Milestone 3 | IPFS      |  2 Weeks    |  William Yang    |    10,000           |
| Milestone 4 | IPFS Compute & FVM      |  2 Weeks    |  William Yang   |    10,000          |
| Milestone 5 | Filecoin      |  2 Weeks    |  William Yang    |   10,000         |
| Milestone 6 | Metaverse      |  2 Weeks    |  William Yang    |   10,000         |
| Milestone 7 | Web3      |  2 Weeks    |  William Yang    |   10,000         |

Total Budget: $70,000

## Maintenance and Upgrade Plans

We will maintain the website for the community. We will also use the strength of the community to get more people involved in the construction of the KEN Labs Education.

# Team

## Team Members

Taosheng Shi
William Yang

## Team Member LinkedIn Profiles

Taosheng Shi , Researcher and founder of KEN Labs.
https://www.linkedin.com/in/taoshengshi/

Abel Cao, former RavenTech CTO of Baidu. He has more than 20 years of experience in Internet applications, embedded systems and other hardware and software development. He has served as research and development director and CTO of several startups. He is now focusing on building the Cloud 2.0 of Web3.
https://www.linkedin.com/in/wireless-com/

William Yang: 15+ years of experience in Internet development. He was an architect of Nokia's wireless and an senior engineer of AOL. He is currently the chief architect of KEN Labs.
https://www.linkedin.com/in/william-yang-40047910/

Yongxing Liang: 20+ years of software industry experience, 6-Sigma black belt, with extensive experience in human resource management, innovation management and business expansion.He is currently manage priority and delivery of the project, Project manager of KEN Labs.
https://www.linkedin.com/in/yongxing-liang/

Xu Qiang(Ben), senior engineer - Head First IPFS @ KEN Labs
https://www.linkedin.com/in/ben-xu-4552a5101/

Aaric Chen, fullstak engineer
https://www.linkedin.com/in/aaric-chen-a84545137/

## Team Website

[KEN Labs](https://kencloud.com/)

## Relevant Experience

KEN Labs is the software engineering leader of the blockchain space,The core members of KEN Labs have over 10 years of experience in distributed storage and blockchain. KEN Labs' vision is to build Cloud 2.0 for Web3, which is infrastructure layer of the Metaverse. KEN Labs's full-stack Computation & Storage products help developers build next-generation Clouds and enable enterprises to launch more powerful web3 infrastructure.

## Team code repositories

[KEN Labs GitHub](https://github.com/kenlabs)

# Additional Information

**Comment by lksbrssr** [comment]
Hi team, let's discuss this one in some more detail: I want to make sure we're not duplicating efforts across various initiatives. 

For example, I know that we're working on translating the entire Encode Curriculum into Chinese and I think that curriculum captures a lot of what is outlined above already. We should make sure that we're closely aligned with what the curriculum should look like in order to ensure it's "net new" material. 

However, building a website and delivering these workshops _is_ useful. Looking forward to chatting on this more!

cc Longfei + Isa

**Comment by taoshengshi** [comment]
Hi Team,

The curriculums we have to prepare are much broader and deeper than the Encode‘s . 
refer this : https://docs.google.com/document/d/1RVDBnalcttF65zkZGhyni0Uitmu7VuoGZ1gjMx-dIKM/edit?usp=sharing

And we already have finished some curriculums translating FYI to avoid duplication on your end:
https://kencloud.com/educate.html

**Comment by longfeiWan9** [comment]
I am on the same page with Lucas about avoiding duplication. I looked into Curriculums structure, they are very detailed and broader ranged from IPLD to VDF. But I still could not see the clear different amount this, protoschool and encode. 
Since we already have Protoschool and encode club curriculums, I suggest making the goals and purpose of this education website very clean and preparing the right content towards achieving the goals.

**Comment by realChainLife** [comment]
Hi @taoshengshi thank you for this proposal. We have approved funding for the work outlined here. Lets discuss next steps.
