### ISSUE TITLE
RFP Application: openEHR Integration

### ISSUE THREAD

**Issue by bsnaam** [filecoin-project/devgrants#418]
# RFP Proposal: `openEHR integration`

**Name of Project:* `openEHR integration`

**Link to RFP:** https://github.com/filecoin-project/devgrants/blob/master/rfps/chainlink-and-filecoin.md**

**RFP Category:** `app-dev`

**Proposer:** `@bsnaam`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** "Yes"

# Project Description

Bela Supernova and Medicohealth propose to apply benefits of the Filecoins’ decentralised storage and the Chainlinks’ oracles in Healthcare industry for handling sensitive medical data. Parties propose to build an application enabling Filecoin and Chainlink usage to securely store medical data of Better HMS (widely adopted hospital management system) users and manage its’ access rights. New application will act as a gateway enabling proper communication of services and data flow between Better HMS, Filecoin storage, Chainlink network, and a blockchain. 

In the current set up Better HMS application stores patients data registry in a data base which creates creates significant security risks. Centralised storage and access rights administration of sensitive medical data creates additional challenges: 

- Administrative overheard due to the rights provisioning on per patients/per record level. 
- Patients lack control and visibility over who has access to their data which goes against natural data subject rights announced in GDPR (General Data Protection Regulation, chapter 3).
- Super user access for DB and LDAP (access rights catalogue) admins create additional security breach risks.
- In case of a data breach full registry will be compromised.

New application will enable an alternative way of storing the data registry. Patients’ data will be stored in a blockchain and will be accessible directly by stakeholders in case they have proper rights. Access rights and stakeholders wallets will be stored in Filecoin. Every data subject will have full unalienable control over his data and a manage access rights on a personal level. Chainlink will publishing public data into the blockchain (e.g. data related to the total number of Covid-19 tests performed on a certain day). 

Key benefit new application will bring:
- Data ownership transfer.
- High data availability.
- Enhances security. In case of a data breach only group of accounts will be compromised.
- Facilitation of secondary data use. 

## Deliverables

As a result of this project partners will deliver:

1. A working MVP that supports secure encrypted decentralised data storage. Application will transfer data using openEHR protocol, hence appliance can be connected (and used) to the widely adopted client applications. 
2. Decentralized access rights and keys management system operation on a smart contract together with the client application (web/mobile) which enables users manage access to their personal and medical data. This type of access rights and keys management system can be re-used by community to in other projects related to personal data. 
3. Public medical data pushed into blockchain (e.g. various types of statistics: number of positive tests, variation rates, ICU availability, death rates, and etc.). Blockchain will guaranty data integrity and reliability. The data itself can be re-used by the community in other dApp applications. 
 

## Development Roadmap

Each milestone will be supported by a group of 1 PM, 6 developers, 1 QA, and 1 DevOps Engineer.

| **Milestone**                                                                                                          |  **Time**       | **Budget**     |
|---------------------------------------------------------------------------- |--------------|---------------|
| 1. Design and development of MH-ORM and medical data storage structure and medical data storage structure. |2 months | € 94 000 |
| 2. Development of the functionality to access to the data stored in Filecoin. | 2 months| € 69 300|
| 3. Development of the functionality to manage access rights on a blockchain level. | 1 month| € 49 500|
| 4. OpenEHR API development and integration with MH-ORM.  | 1 month| € 55 970|
| 5. Public data publishing.   | 1,5 months | € 48 500 |
| 6. Design an development of an application to manage personal medical data and its’ access rights. | 2 months | € 87 900   
| 7. Testing, Documentation, MVP deployment. | 2 months   | € 74 250 |

![gateway](https://user-images.githubusercontent.com/96248313/146411797-fa312e62-4a4f-4367-b747-aaf11afcf47e.jpg)

**Milestone 1. Design and development of MH-ORM and medical data storage structure**

1. Design of the medical data storage, according to the typing structures adopted in the openEHR.
2. Design of the index storage. Design of the indexing system that utilises homomorphic encryption and blind indexing algorithm to prevent data decryption during indexing process, hence rooting out related data breaches.
3. Design and implementation of the data encryption methods. 
4. Design and implementation of the filtering functionality.
5. Design and implementation of the record creation and update functionality.
6. Development of an API and interfaces to process data.
7. Gathering test data set, extensive testing of the architecture.

**Milestone 2. Development of the functionality to access to the data stored in Filecoin.**

At this stage we’ll establish close interaction between MH-ORM and Filecoin. We will be adding the encryption functionality and functionality of saving/reading personal data from Filecoin.
1. Integrate Filecoin as a storage for MH-ORM database.
2. Integrate Filecoin as a storage for MH-ORM indexes.
3. Develop an algorithm of data re-encryption at the event of revoking or changing access rights for a single user or a group.
4. Design of the chains of records within the storage to ensure the data integrity and authenticity.
5. Run Performance tests and optimisation.
6. Setting up payment logic (for transactions).

**Milestone 3. Development of the functionality to manage access rights on a blockchain level.** 

This stage is fully dedicated to the developement of smart contract that will be managing access rights, and it the way it interacts with an outside world.
1. Research of available blockchains supporting EVM-based smart contracts. EVM will be at the basis of our access management system. 
2. Development of the user account catalogue and the user identification mechanism. 
3. Embedding information about use access rights in smart contract. Formalising methods of acquiring, setting up and delegating the user rights.
4. Design and development of the encrypted storage to store data access keys. Methods to verify the access rights and acquire the access keys. 
5. Design and development of an interface to interact with smart contract. Development of the dedicated library.

**Milestone 4. OpenEHR API development and integration with MH-ORM**

MVP will support central user authorisation and matching the existing accounts to their personal keys.
In the future security keys can be managed on the application level and data access will be directly through the user application. 
1. EHR system core
2. Implementation AQL according to the openEHR protocol. Client applications use for data queries, this way platform can be used by the 3rd party applications supporting the standard. 
3. Integration with access rights management system.
4. Integration with MH-ORM

**Milestone 5. Public data publishing.**
Data feed of public data to blockchain through chainlink.
1. Develop public data gatherer. 
2. Data feed (data provider) node development
3. Develop smart contract to push public data.
4. Design methods to access data in a gateway. 

** Milestone 6. Design an development of an application to manage personal medical data and its’ access rights** 
Application helping users to manage their personal data and its’ access rights
1. Application design compatible with with web and mobile platforms
2. UI/UX design.
3. Frontend development.
4. Blockchain integration to manage rights.
5. Test case design and development.
6. Testing. 

**Milestone 7. Testing, Documentation and MVP deployment** 
Future solution will process and store sensitive data what automatically implies extended security and solution reliability.
1. Stress testing to find performance bottlenecks.
2. Security audit.
3. Troubleshooting.
4. Creation of the documentation.
5. Release of smart contracts into the main net 
6. MVP release.

## Total Budget Requested

The total budget for MVP development - €479 420

## Maintenance and Upgrade Plans

The team will be supporting the app and offer it as an alternative solution to all Better customers. In the future app functionality can be extended, hence it can verify trust records in patients data and act as a guarantee of authenticity. This is applicable for vaccination certifications. 

# Team

## Contact Info

Sergei Cymbal sc@bsn.si

## Team Members

- Milan Rajlic, Co-Founder and Managing Director of Medicohealth Ltd. 
- Andrej Muzevic, Co-Founder and Advisor at Medicohealth Ltd, Partner at Interbora d.o.o
- Sergey Cymbal, MBA, CEO at Bela Supernova d.o.o
- Sergey Zolotukhin, CTO at Bela Supernova d.o.o
- Dmitrii Putilov, Blockchain Department Director at Bela Supernova d.o.o
- Dmitrii Volodin, COO at Bela Supernova d.o.o
- Ilia Shavrin, Full stack software developer at Bela Supernova d.o.o
- Anton Shramko, Full stack software developer at Bela Supernova d.o.o
- Ksenia Baranova, QA Lead at Bela Supernova d.o.o
- Alexey Vexin, Project Manager at Bela Supernova d.o.o
- Anton Borisov, DevOps Engineer at Bela Supernova d.o.o

## Team Member LinkedIn Profiles

- [Milan Rajlic] (https://www.linkedin.com/in/milan-rajlic-a53abaa/)
- [Andrej Muzevic] (https://www.linkedin.com/in/andrej-muzevic-075b674a/)
- [Sergey Cymbal] (https://www.linkedin.com/in/sergecymbal/)
- [Sergey Zolotukhin]
- [Dmitrii Putilov] (https://www.linkedin.com/in/dmitri-p-96b0a140/)
- [Dmitrii Volodin] (https://www.linkedin.com/in/dm1tr11-volodin/)
- [Ilia Shavrin] (https://www.linkedin.com/in/ilia-shavrin-716552228/)
- [Anton Shramko] (https://www.linkedin.com/in/anton-shramko-25971b162/)
- [Ksenia Baranova] (https://www.linkedin.com/in/mayawotson/)
- [Alexey Vexin] (https://www.linkedin.com/in/alexey-vexin-800a4068/)
- [Anton Borisov] (https://www.linkedin.com/in/anton-borisov-17b80211b/)
## Team Website

https://www.bsn.si
https://medicohealth.io

## Relevant Experience

Our team has extensive expertise on multiple levels starting from progressive vision all the way down to software and solution development. This blend of knowledge and skills ensure we tackle the most ambitious challenges and come up with commercially successful solutions in Healthcare and FinTech industries. Natural ability of some of the team member to navigate and predict future technological trends combined with technical experience and project management skills of other members translates into the clear roadmap. 

Milans Rajlic is an entrepreneur and visioner with 25+ years of experience in building and  scaling high-tech companies operating across Healthcare, FinTech, Energy, Manufacturing and Real Estate industries.

Andrej Muzevic for the last 25 years acts as an Advisor and Investor for high tech businesses empowering and mentoring bright minds who build technologies of the future. He has the most experience in Healthcare, Blockchain, Data and other knowledge intensive areas. Andrej is also a very active member of Etherium Community.

Sergey Cymbal is an experienced executive, leader and visioner responsible for the most disruptive innovations initiatives across Oil/Gas, Utilities, and Telcos in Russia. Ex-member of Sochi Olympics HQ, responsible for digitalisation, Smart grid evangelist. Blockchain early follower, participates in several crypto initiatives .

Sergey Zolotukhin has over 20 years of experience in R&D and software development with a deep focus on Machine Learning, Neural Networks and Mobile solutions design in Telcos and Pension Funds. Led several enterprise machine learning project, has various experience in crypto and blockchain development.

Dmitrii Putilov has over 17 years of experience leading the teams creating and maintaining high availability sites. His portfolio contains creation of the robee.io investment platform included in top500 in coinmarketcap.

Dmitrii Volodin has a background in IT. For over 15 years he has been helping customers build, implement and maximize value of their critical IT infrastructure and solutions across Enterprise, Manufacturing and Healthcare industries.

Ilia Shavrin is a solution architect and full stack software developer with over 12 years of experience in high load enterprise applications. His most recent focus is on blockchain and creation of decentralised applications.

Anton Shramko is an experienced developer with ver 7 years of experience on various positions, including solution architect in Krypton. Anton active contributor to open source and blockchain communities, he is also a frequent speaker in DevCon conferences. 

Ksenia Baranova is an QA test engineer with over 5 years of experience. Ksenia has exceptional knowledge and skills in the field. She is highly refered within this team, as well as by her former teams.

Alexey Vexin is product owner and project manager with 10+ years experience in managing complicated telecoms and IT projects in Telco, Utilities and Govermental sectors with deep focus on business process management. Led a dozen of federal scaled projects for IT systems implementation and industry scaled technology development, standardisation and implementation.

Anton Borisov îs a DevOps Engineer with broad experience. For for over 15 years Anton was supporting, administering, and maintaining secure networks, servers and clusters. He also has verstile experience with CI/CD, IT Infrastructure Monitoring, and Kubernetes on-premise and in Cloud. One of the most recent projects Anton particapted in was building a first onchain casino.  
## Team code repositories

https://github.com/ManageIQ/manageiq-providers-amazon/commits?author=aiperon
https://github.com/ManageIQ/manageiq/commits/?author=aiperon
https://github.com/friktor?tab=repositories
https://github.com/better-care

# Additional Information
We envision this project as a kickstart of a long journey. The team has ambitious plans for future development. 
If you have any questions please contact Sergei Cymbal via sc@bsn.si

**Comment by rajlo** [comment]
Nice!

**Comment by BlocksOnAChain** [comment]
@realChainLife any updates we can provide for applicants on this proposal?

**Comment by realChainLife** [comment]
Hi @BlocksOnAChain thank you for your proposal. We would like to fund the work outlined here, please email devgrants@fil.org to discuss the next steps.
