### ISSUE TITLE
Open Grant Proposal: Spheron (Previously ArGoApp) - Heroku for decentralised cloud

### ISSUE THREAD

**Issue by izrake** [filecoin-project/devgrants#420]
# Open Grant Proposal: `Spheron Protocol`

**Name of Project:** `Spheron`

**Proposal Category:**  `app-dev`

**Proposer:** `izrake`

**(Optional) Technical Sponsor:** `hq han`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:**  `Yes`

# Project Description

Spheron Protocol is a chain agnostic infrastructure aggregator that removes the friction of using decentralized infrastructure protocols
by providing tools and services to help developers get onboard on dWeb faster than usual.
This also allows developers not to carry multiple tokens around the chains to use the deployment services; instead, they can use it on their favourite chain.

## Value

We are building layer 1 on top of layer 0 to bring more users utilizing the file coin ecosystem without any friction of understanding it.
Currently, we have more than 2300 developers using the product with 366 plus projects. 
In terms of benefits, we will add more developers building on top of the file coin network and bring more websites and storage deployed on it. We will also be opening ways to run gateways to serve the data with the new integration. Our long term road map includes providing a data storage platform as well.
If we don't get it right, the possibility will be less data and web app getting deployed. But fortunately, we have tested things out, and our approach doesn't allow us to fail.
We don't have such risks because we already have 18 members working on it, and they are well experienced in executing the things. The only risk that we see is if we don't get enough support from the protocol in the long run.

## Deliverables

- Webapp Deployment on IPFS with Filecoin pinning automatically enabled
- Decentralized Edge network for Filecoin deployed web app
- Dedicated Analytics dashboard for Filecoin deployed projects
- ENS & HNS domain support for projects

### Milestone 1:
**Title**: Webapp Deployment on IPFS with Filecoin pinning automatically enabled
**Goal**:  Give developers an intuitive & straightforward platform for deploying their web app to IPFS and automatically pinning it to the filecoin network.
**Details**: This milestone will include support for all the feature sets that are currently present on the platform like Automated CI/CD, Collaboration with team members, Git integrations like GitHub, GitLab & Bitbucket, Concurrent Builds, Important Notifications, etc.
Developer can deploy their web app from our supported frameworks like React, Next, Vue, etc., and can view concise logs when deploying their web app. The static website files will be uploaded to IPFS, and the CID will be pinned to the Filecoin network using Estuary API. Every deployment will be pinned automatically so that developer doesn't need to do extra work for pinning the IPFS CIDs.
2 dedicated developers are working on it right now, one is taking care of the frontend and another is for backend development of managing pinning services.
**Funding**: $15000
Achievable Date: 24 December 2021 
### Milestone 2:
**Title**: Decentralized Edge network for Filecoin deployed web app
**Goal**:  Providing Edge network to serve website much faster than the ipfs gateways
**Details**: This milestone builds an edge network that provides heavy caching on website content. The edge network will also have DDOS protection and other modules to optimize & increase the performance of a website. Our idea is to decentralize the edge network. The solution is still in WIP, but the main idea is for the community to run the edge nodes and incentivize them in terms of the bandwidth they are providing to the network. The deployment on ipfs won't need to rely on ipfs gateways rather, developers can take advantage of our edge network to increase the performance with a need for a single entity to control over their websites.
There is a need for at least 3 dedicated developers working on it. Currently, one developer is already working on POCs and the architecture of CDN. We need another to work on implementing infrastructure for CDN and another blockchain dev for building the node staking and incentive mechanism.
**Funding**: $25000
**Achievable Date**: 4 Feb 2022 
### Milestone 3:
**Title**: Dedicated Analytics dashboard for Filecoin deployed projects
**Goal**:  Providing an analytics dashboard to view the performance of their filecoin deployed projects
**Details**: This milestone is to build an analytics dashboard for developers to keep track of the performance of their website.
There are two dedicated developers and one designer working on it. We need a designer who can work on the design system for the analytics dashboard. One dev for the frontend and another for the backend.
**Funding**: $7500
**Achievable Date**: 24 Feb 2022 (Prashant Confirm this)
### Milestone 4:
**Title**: ENS & HNS domain support for projects
**Goal**:  Providing a simple UI for attaching ENS and HNS domain to their ipfs deployed app
**Details**: This milestone is to build an intuitive UI for attaching and verifying HNS and ENS domains on the ipfs deployed app. The integration is done with simplicity in mind as a developer doesn't need to traverse through multiple websites to configure their domains. The UI will have an option for the developer to update the records with just a click. In the case of HNS domains, the developer will be redirected to confirm the record update. In the case of ENS domains, developers have to confirm an onchain transaction to update their ENS domain's content hash. API is used to verify if the records are updated or not.
There are 2 dedicated developers working on it right now, one is taking care of the frontend and another is for backend development of managing pinning services.
**Funding**: $2500

## Total Budget Requested

Total Budge Requested: $50000

## Maintenance and Upgrade Plans

Spheron team is committed to supporting any upgrades done on the protocol provided to our users who are using filecoin via us.
We have a dedicated team that will monitor and bring any changes to our platform to do so.

## Team Member LinkedIn Profiles

- https://www.linkedin.com/in/techprashantmaurya/
- https://www.linkedin.com/in/mmitrasish/
- https://www.linkedin.com/in/andrija-novakovic-55995a152
- https://www.linkedin.com/in/dusan-stanisavljevic-a08a42191
- https://www.linkedin.com/in/nikoleta-vukajlovic-3b200a1bb/
- https://www.linkedin.com/in/joshuanwankwo
- https://www.linkedin.com/in/nitin-sharma-73b032146/
- https://www.linkedin.com/in/singingapple/)

## Team Website

[](https://argoapp.net)

## Relevant Experience

Our team has vast experience in writing high-quality code and tests. They have proved it by delivering many features within a few months of the product launch. The team has an average experience of 5 years developing scalable solutions around the infrastructure protocol.
One of our team members has vast experience in building on many chains and won hackathons across many ecosystems. Our team is young and enthusiastic about building deep tech in the blockchain ecosystem.

## Team code repositories

https://github.com/rekpero
https://github.com/izrake
https://github.com/argoapp-live

# Additional Information

**Comment by realChainLife** [comment]
Hi @izrake thank you for this proposal. We would like to fund the work outlined here. Please email devgrants@fil.org to discuss next steps.
