### ISSUE TITLE
JACKAL Grant Ask

### ISSUE THREAD

**Issue by JACKALDAO** [filecoin-project/devgrants#421]
# Open Grant Proposal: `JACKAL`

**JACKAL Storage:**

**Proposal Category:** `app-dev`, `devtools-libraries`

**Proposer:** `JACKALDAO`

**(Optional) Technical Sponsor:** `Stefaan Vervaet, Jonathan Victor`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** "Yes" 

# Project Description

JACKAL Storage will provide a user-friendly solution for completely decentralized hot storage on-chain that follows the Amazon S3 Standard. This results from the confluence of many factors, including privacy by default blockchain technology from the Secret Network and decentralized cold storage from Filecoin. 

JACKAL Storage isn't the first of its kind regarding acting as a top layer to organize user data between a decentralized storage network and the user.  That being said, JACKAL Storage is unique from existing models by being fully decentralized and having the highest digital privacy and cybersecurity posture possible. JACKAL can lower entry barriers while maintaining decentralization by creating an incentivized peer-to-peer caching layer between the Secret Network and Filecoin. Our users will not need an expensive node, a centralized server to pin the files, or have a node running at all times. 

With the rise in popularity of the Secret Network, the idea that your data can be verifiable on the blockchain, while also being fully encrypted with permissions, created a unique opportunity for JACKAL. To create a storage platform true to decentralization while increasing our users’ digital privacy and cyber security posture.

The JACKAL Team believes data privacy is a fundamental human right and will ensure storage on our platform is safe, secure, and private by default. The JACKAL Team will never have the ability to access the data of our users as it can only be accessed and shared by the end-user with their private key. 

Not your keys, not your data. 

## Value

The JACKAL team believes a hot-storage solution that bridges Filecoin and the Secret Network would provide both ecosystems usage growth and user acquisition. This is because JACKAL Storage would provide an Amazon S3 comparable that is entirely decentralized, private, and on-chain craved by both enterprise clients and individuals. JACKAL Storage also has competitive advantages when compared to S3 by having higher digital privacy and cyber security postures at an unbeatable price point, thanks to Filecoin's cold storage. Over 50% cheaper than Amazon S3, Google Cloud, and Microsoft Azure per TB. 

JACKAL Storage will also provide the ability for builders to build applications on top of our hot-storage platform with permissions and viewing variables. We believe this will spark innovation to build applications that will access markets that currently do not leverage the Filecoin platform.  Interested builders have already contacted us and have proposed building or integrating decentralized applications on JACKAL Storage. Some of our favourite proposals include the following.

- Password manager
- Decentralized email and IM service (AlterMail integration) 
- Digital evidence capture, management, and chain of custody system for court proceedings and e-discovery
- Website hosting
- Adobe Sign comparable
- Private storage solution for NFTs
- Bug bounty & ethical hacking applications 
- Google docs collaboration comparable

The JACKAL team believes the risks associated with building this project are heavily outweighed by the need for the hot-storage layer JACKAL aims to develop.  Currently identified risks include possible corrupted data, DDOS & other cyber attacks, and legal risks associated with providing this product.  We believe many of these risks will be mitigated during the Alpha and Beta releases of JACKAL Storage. 

## Deliverables

A private hot/cold cloud storage system that follows the Amazon S3 standard but with higher digital privacy and cyber security standards along with an over 50% cheaper price point. 

## Development Roadmap

This project will require a full 14 weeks to develop a full mainnet Beta. Cost basis is paid out in FIL token or stable coin. 

### Key Milestones

**Testnet MVP Release - Weeks 0-4**

- Private File Uploads 
- File Version Control
- Early UI Displaying File Structure
- File Retrieval & Display in Browser
- File Permission System

**Synthesis and UI - Weeks 4-8**

- UX & UI Overhaul
- UX Testing
- Brand Book 
- Treasury Synthesis
- Governance Synthesis
- Economic Review

**Testing and Governance - Weeks 8-14**

- Governance Testing 
- Tokenomics Finalized 
- Payment Model Testing
- Integration with Automated Market Makers

### Roadmap Overview
**Phase 1**

- Smart contract deployed on the Secret Network. The contract creates a file system structure and maintains the user’s access to files. 
- Filecoin connection made through Powergate or comparable. 
- Front end to support uploading/viewing files. 
- Version control system with viewable changes. 
- Folder/file permissions to allow other users to view/edit files when granted permission by the private key holder. 

**Phase 2**

- UI overhaul - file editor for supported file types. 
- Integrate early enterprise adopters (AlterMail, Stashhh, Keepsake, etc.) 
- Scale into an AWS S3 comparable providing the ability to integrate JACKAL into legacy systems. 
- Start accepting DAO proposals to extend the software. 

**Phase 3**

- Features/changes will be as a result of DAO proposals. 

### Total Grant Ask - $69,600

**Development Team - $50,400**

JACKAL aims to build a team of 4 developers at $45 an hour 20 hours per week. 

**Operations - $19,200**

Project manager, marketing manager, and operations manager. 3 team members at 40 an hour for 20 hours per week for 8 weeks. 

## Maintenance and Upgrade Plans

Feature changes and updates will be conducted based on DAO proposals & votes. 

# Team

## Team Members

**Patrick Dunlop**

**Marston Connell**

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/patrick-dunlop-129767113/

https://www.linkedin.com/in/marston-connell-847753184/

## Team Website

https://twitter.com/JACKAL_DAO

## Relevant Experience

**Patrick** is an emerging voice and specialist in both the open source intelligence (OSINT) community and the digital forensics community specializing in blockchain.  He is published with the OSINT Curious Project and has fulfilled requests to lecture at Ottawa, McGill and Harvard universities.  Patrick also has a BSc from Saint Francis Xavier University and three professional certifications in computer science. Patrick has a deep understanding and knowledge surrounding the implications of poor privacy and cyber security in both civil and criminal proceedings. With this, Patrick has become a privacy advocate and believes digital privacy should be a basic human right. 

**Marston** has a passion for programming and problem-solving and strives to write clean and modular code.  Marston is proficient in functional and object-orient programming, allowing him to develop software in a cross-chain environment efficiently. At this time, Marston is fluent in Javascript, Rust, Java, C/C++, Python, PHP, and SQL.  Before starting JACKAL, Marston has developed a Web3 digital evidence capture and chain of custody software in the polygon ecosystem. Previously he has also created a Minecraft modification with over 3 million downloads. 

## Team code repositories

https://github.com/JACKAL-DAO

# Additional Information

**Wiki** working document (subject to change): https://bit.ly/3n4ahMS

**Discord**: https://discord.gg/8tCmKZUUyA

**Twitter**: https://twitter.com/JACKAL_DAO

**Comment by mishmosh** [comment]
Hello @JACKALDAO and thanks for this proposal! We will review this week and get back to you soon.

**Comment by JACKALDAO** [comment]
> Hello @JACKALDAO and thanks for this proposal! We will review this week and get back to you soon.

Woohoo

**Comment by realChainLife** [comment]
Hi @JACKALDAO thank you for this proposal. We would like to fund the work outlined here. Please email devgrants@fil.org to discuss next steps.
