### ISSUE TITLE
Verses.xyz

### ISSUE THREAD

**Issue by jazzminewang** [filecoin-project/devgrants#423]
# Open Grant Proposal: `Verses.xyz`

**Name of Project:** Verses

**Proposal Category:** Choose one of `core-dev`, `app-dev`, `devtools-libraries`, `technical-design`, `docs`

**Proposer:** `@verses-xyz`

**(Optional) Technical Sponsor:** `Evan Miyazono`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** "No"

# Project Description

verses will author 
  verses /vərses/ (n.)
  compact, meaning-laden artifacts 
      [poems!]
advocating for / demonstrating / gesturing towards
a pluriverse: a world where many worlds may fit 

## Value

we sit around the fire
soup brimming with
offerings of scented thyme,
stones, boundary objects

we see a world
consolidated and consolidating
and imagine another

we write and read new old maps
build and bury new old ground
   to be a good ancestor is to grasp 
an intergenerational reciprocity
 embers passed from hand to hand
 
we move within hyperobjects
with the knowledge that
  we walk, as all have walked
in history

we sing for a world where all may sing
for a chorus singing, full throat
without center and within many centers 

we hold existential risk
as the risk of losing possible worlds
cutting branches before bloom
the surest way to foreclose the future
is to never let it grow

## Deliverables
Verses will produce compact, well-executed artifacts that are philosophically coherent and legible enough to be extensible. These artifacts will advocate for, and demonstrate, the way of building we believe to lead to a healthier future of the web, and thereby have a greater change at a flourishing future. This work will inherently be coalitional; we plan to involve a diverse set of organizations in the co-creation of these artifacts.

Our first drop was the Declaration, which resonated with people on many levels because every part of the artifact was laden with the same ethos. Some current workstreams:

(1) Working on an essay about extending the ethic of the pluriverse to the digital realm that details the history of term ‘pluriverse’, implemented on custom infrastructure that allows other organizations to propose various operationalizations of the ethic as first-class citizens (vs. as commentators). This work will be followed by media / PR work to help coalesce value-aligned organizations around this term.
(2) In Q1, we are providing our infrastructure to Metagov for a collaborative drop / space for DAOs to host, fork, and ratify their constitutions. Building infrastructure that helps people articulate, express, debate, and codify their values is extremely important + exciting to us. Right now DAOs are not democratic because voice is expensive + membership is evaporative; it's also unclear to people before joining a DAO what it's governance procedures look like. MetaGov has done an analysis of more than a dozen DAO constitution templates. We want to create a general constitution template that folks are able to engage with in various ways (e.g. sign / vote on / discuss / edit / fork).
This work will probably roll up into the effort to define a new EIP for DAO, and to confirm what is immutable about a DAO so that the concept can’t be co-opted by corporated fiefdoms. 
(3) A decentralized glossary, with glossary governance rights as a $MEANING token, and the ability to earn this  by contributing meanings that are accepted into the glossary. Initially we could focus on terms that bring Web3 coherence / Meta immune response, including terms like interoperability, autonomy, and decentralization.
(4) Speculative fiction / visceralization of potential worlds to work towards, and to avoid (we’ve already received a Gitcoin grant of 2000 USDC for this proposal to the public goods workstream).
(5) Various partnerships (collaborating with Fight for the Future for a coalitional artifact, folks working on forking the Declaration of the Anti-Slavery Society manifesto)

## Total Budget Requested
$100,000

# Team

## Team Members

Jasmine Wang
Daanish Shabbir
Jacky Zhao
Raymond Zhong
Divya Siddarth
and many others

## Team Website

https://verses.xyz

## Team code repositories
https://github.com/verses-xyz/interdependence-web
https://github.com/verses-xyz/interdependence-server

**Comment by miyazono** [comment]
I wanted to add that, as the technical sponsor, I'd be happy to advocate for or answer questions about this effort - feel free to catch me on the FIL (or PL) slack.
   - Evan (@miyazono)

**Comment by realChainLife** [comment]
Hi @jazzminewang @miyazono thank you for this proposal. Can you also include in the development roadmap, how you'll intergrate Filecoin, or IPFS.

**Comment by miyazono** [comment]
The Verses team is developing social and memetic leadership around the need for and benefits of an open metaverse.  The goals and values are strongly aligned with those of Filecoin & IPFS, but the project should be seen as distanced and is unlikely to use Filecoin or IPFS, except naming the projects as a natural example for critical, permissionless infrastructure that is needed in their shared vision of how an open, interoperable metaverse should be built.

This effort intends to have a very high leverage impact on the development of an open metaverse that empowers users, and thus has a slightly longer timescale than a typical devgrant, so the connection to FIL/IPFS is a little more indirect in the short term.

Might also help to have one of Clara, @autonome, or @mishmosh chime in, since they each have some context.  I believe this fits into [the new Metaverse category of the open grants call](https://github.com/filecoin-project/devgrants/blob/master/open-grants/README.md)

**Comment by autonome** [comment]
Some thoughts below. Is fine to just update the original comment in the issue to address any requests for change.

Also, I saw the patterns documents but that work isn't listed here as part of the workstreams. Is that separate? If not, can you add it and link to those docs?

One general thought: I love so much about what I'm seeing and reading in the proposal and the various docs you've shared, but I don't have a sense of the theory of change. I see some articulation of the end state, and some workstreams, but not a path to bridge one to the other.

Some questions that I find helpful in articulating that pathway:

* Who are the specific communities/peoples/groups/businesses/govts/etc that you are speaking to?
* how are you reaching them? how do you know they heard?
* what are the behaviors they have, which you want to change?
* what decisions do they make that you want to influence?

Perhaps worth asking these types of questions of the team and integrating into the proposal somehow.

> Verses will produce compact, well-executed artifacts that are philosophically coherent and legible enough to be extensible. These artifacts will advocate for, and demonstrate, the way of building we believe to lead to a healthier future of the web, and thereby have a greater change at a flourishing future.

Would be helpful to list some examples of the type of artifacts, and point to some historical examples of where these types of artifacts contributed to or resulted in the type of societal guiding/shaping this effort is aiming for.

> This work will inherently be coalitional; we plan to involve a diverse set of organizations in the co-creation of these artifacts.

Can you list the collaborators who've already committed to the effort, and others who you plan to engage. Maybe could link the related google docs here from the pattern list work, would also be good example of what this work looks like.

> Our first drop was the Declaration, which resonated with people on many levels because every part of the artifact was laden with the same ethos.

Can you link the declaration you're talking about, along w/ some examples of how/where it resonated? Who did it resonate with? Coalition collaborators? The broader intended audience whose behavior you want to influence?

> Some current workstreams:

Would really help to break this list out into a table, with at least a general timeframe, and maybe a classification of which type of artifact, who it's targeting, and what the expect outcome is. Ideally would also have some ways to understand or measure whether it did the thing you wanted it to, but that level of detail could come later.

> (2) In Q1, we are providing our infrastructure to Metagov

What is Metagov, and can you link to it in the proposal? and any other external references you mention?

> Team Members

Can you link to the social/blog/portfolio... some way of understanding who the team you've put together are? verses.xyz doesn't have any of this information, as far as i could tell.

>  social and memetic leadership around the need for and benefits of an open metaverse
>  how an open, interoperable metaverse should be built

This is a very helpful way of describing this work. I recommend incorporating into the proposal language so it's clear to the grants team.

> very high leverage impact on the development of an open metaverse that empowers users, and thus has a slightly longer timescale than a typical devgrant, so the connection to FIL/IPFS is a little more indirect in the short term.

Helpful context for decision making and expectations management. This is not a typical "devgrant", so this framing should be explicitly written in the proposal, along with high-level timeframes and guidance for grant evaluation for success. Eg, maybe a table of "at 1yr: 2 major projects are using the patterns, 3 major publications have started using the language we propagated. at 2yrs: etc etc". That might help justify higher funding levels and also provide the team itself with a framework for understanding their own progress in achieving what they are setting out to do.

**Comment by autonome** [comment]
Oh and I just saw https://pluriverse.world/ !! Should note all things like this in the proposal.

**Comment by miyazono** [comment]
> What is Metagov, and can you link to it in the proposal? and any other external references you mention?
I can at least answer this one
https://metagov.org/
Josh (executive director of Metagov) spoke about mathematical models for governance at the PL Research seminar [here](https://www.youtube.com/watch?v=981FhtbX8vU)
Michael Zargham, advisor to PL's Cryptoeconomics team is one of the MetaGov Researchers (PIs)

**Comment by miyazono** [comment]
Just wanted to apologize to @realChainLife for my misunderstanding of the various grants program here - there was a miscommunication that led me to a very incorrect understanding of some of the grantmaking structures over here (i.e. outside of PL) and I want to both thank you for your professionalism and apologize for all awkwardness and the completely unnecessary headache I'm sure I caused.

Also, thanks to @autonome for clarifying things for me.
