### ISSUE TITLE
Next Step Microgrant: Oppanda offline proposals.

### ISSUE THREAD

**Issue by vigneshc** [filecoin-project/devgrants#425]
### 1. What is your project? 
**Oppanda** is an experimental project to add support for creating off chain proposals with defined validators that can be funded. Proposals are defined off-chain and `proposal=> external validator url` is recorded onchain. Funds are transfered when external oracle validates that proposal is approved by validators. Currently proposals can be validated through tweets from validators and Off-chain signatures stored in IPFS.
Proposals and approval records are optionally stored in IPFS using Web3.Storage api.

[Oppanda Github link](https://github.com/vigneshc/Oppanda)
  
### 2. How are you planning to improve this project?
Develop UX, deploy in mainnet and host it. At that point it, while the concept is still experimental, it can be used for real use cases. Detailed next steps are in the [readme.md](https://github.com/vigneshc/Oppanda/blob/master/Readme.Md) file

 
### 3. Will the work be Open Source?
Yes, it will be MIT.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes.

### 6. Links and submissions
  
* Project added to Filecoin showcase. Waiting to be merged.
* [Discussion link](https://github.com/filecoin-project/community/discussions/426)

### 7. Additional questions:
* Team Members: https://github.com/vigneshc
* It was created as part of Chainlink fall hackathon 2021. Here is the [submission link](https://devpost.com/software/oppanda)

**Comment by SeedingTrees** [comment]
Hi, @vigneshc.  I would like to approve this application but I need an email address to which I can send the instructions for receiving your grant payment.  Please drop your email address here and I will approve this grant.  Thanks.

**Comment by vigneshc** [comment]
Shared email offline on 1/21.

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
