### ISSUE TITLE
Next Step Microgrant: Laravel2IPFS

### ISSUE THREAD

**Issue by BaranBayden** [filecoin-project/devgrants#428]
### 1. What is your project? (max 100 words)
Laravel2IPFS is a plug-in that enables applications developed with Laravel infrastructure to be backed up to IPFS. There is also a feature that will allow you to quickly restore from your backups in case of any disaster.

https://github.com/BaranBayden/Laravel2IPFS
  
I will buy domain for this project. 

### 2. How are you planning to improve this project? (max 200 words)

I will develop a plugin for the project that will initially back up the database, design files and media files for the Laravel framework. For this plugin, I will initially use the APIs of IPFS infrastructure providers such as Infura. After developing the backup module, I will develop the one-click install module from the backup to a fresh Laravel installation. After that, I'm thinking of developing a base module on PHP. Thanks to this module, me and other developers will be able to integrate the module into any framework they want.

### 3. Will the work be Open Source?

Yes, It will be under MIT license. 
### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions

  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
Not Sure
  

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
  
https://github.com/filecoin-project/community/discussions/423
  

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Baran Bayden
baran@baydenteknoloji.com
Project Owner
https://github.com/BaranBayden
https://www.linkedin.com/in/baran-bayden-aa791373/

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
