### ISSUE TITLE
Open Grant Proposal: `UniFile`

### ISSUE THREAD

**Issue by Jeffonemore** [filecoin-project/devgrants#429]
**Name of Project:** `UniFile`

**Proposal Category:** `app-dev`

**Proposer:** `Jeffonemore`

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** `Yes`

# Project Description

An open source storage system for your data that storage in Filecoin/IPFS use Web3.Storage which makes it easy to share them anywhere on the web. UniFile have accepted Next Step Microgrants in https://github.com/filecoin-project/devgrants/blob/master/microgrants/accepted-microgrant-applications.md#surfing_woman-second-half-2021

Github：https://github.com/StorerOS/UniFile

demo: https://unifile.storeros.com:8443/

UniFile is tightly scoped for the present and more broadly thought out for the future. Our primary objective is to create a best-in-class experience for uploading, collecting, and sharing media. 

One more thing, User can mint NFT on the resource data contributed by themself on blockchain. This NFT can manage IP authorization and IP monetization.

## Value

1. We will adopt a decentralized incentive mechanism to encourage users to upload and use UniFile, and obtain a certain amount of Token(base to FVM). And give Token more and more functions, such as decentralized governance, payment and other functions.
So the benefits to getting this right is: empower Filecoin's vision and improve Filecoin's network storage capabilities. Bring new users to the Filecoin ecological community. Bring higher liquidity to FIL and give FIL more functions.

2. If we do not do it right, there should be no risk. Because the user's business data is permanently stored on Filecoin/IPFS. After all, our success also depends on the FIlecoin ecosystem

3. We don't have such risks because we already have 5 members working on it, and they are well experienced in executing the things. The only risk that we see is if we don't get enough support from the Filecoin protocol in the long run.

## Deliverables

1. Users login and file management within the UniFile
2. Incentive mechanism design and develop
3. NFT related to the files storage by users and develop NFT marketplace

### Milestone 1:
**Title:** Users login and file management within the UniFile

**Goal:** Users can register and log in by email in UniFile and have their own file management directory, which is convenient for users to find their uploaded files

**Details:** Develop a user registration and login system based on Web3.Storage in UniFile to manage users. Develop a management directory for users to store files in Filecoin/IPFS

**Funding:** $10000

**Achievable Date:** 2022.2.28

### Milestone 2:
**Title:** Incentive mechanism design and develop

**Goal:** Design and develop an incentive mechanism to encourage users to upload and download their own resource data in UniFile

**Details:** Design and develop an incentive mechanism to encourage users to upload and download their own resource data in UniFile

**Funding:** $10000

**Achievable Date:** 2022.4.30

### Milestone 3:
**Title:** NFT related to the files storage by users and develop NFT marketplace

**Goal:** Assign the files stored by the user to the NFT, and transactions can be carried out

**Details:** Based on the files stored by UniFile, the NFT mint application is developed to empower the files and can be traded on the marketplace

**Funding:** $15000

**Achievable Date:** 2022.6.30

## Total Budget Requested

Total Budge Requested: $35000

## Maintenance and Upgrade Plans

StorerOS team is committed to supporting any upgrades done on the protocol provided to our users who are using filecoin via us.
We have a dedicated team that will monitor and bring any changes to our platform to do so.

# Team

## Team Members

wujinquan: Project leader ，https://github.com/Jeffonemore
baijinying: Blockchain development engineer ，https://github.com/baijinying-wc
sunjiebin: Operation and maintenance engineer
luzewei: front-end engineer ，https://github.com/AlexzZzNM

## Relevant Experience
Our team is an early storage service provider on Filecoin. Now focus on the development of Filecoin's infrastructure and ecology.
Our team has vast experience in writing high-quality code and tests. The team has an average experience of 5 years developing scalable solutions around the infrastructure protocol.
Our team is young and enthusiastic about building deep tech in the blockchain ecosystem.

## Team code repositories

https://github.com/StorerOS

https://github.com/StorerOS/UniFile

# Additional Information

**Comment by realChainLife** [comment]
Hi @Jeffonemore thank you for this proposal as well. We would like to fund the work outlined here. Please email devgrants@fil.org to discuss next steps.
