### ISSUE TITLE
RFP: Filecoin protocol implementations

### ISSUE THREAD

**Issue by pooja** [filecoin-project/devgrants#43]
We are looking for teams who are interested in building an implementation of the Filecoin protocol. The full grant specification is [here](https://docs.google.com/document/d/1L7ZZOC4cms3SZNyx7u1Hr0H_XFDUI8FYA2W8dXWBGsY/edit?usp=sharing).

Note that while this RFP description does not follow the same template as our others, submitted proposals should follow the application format described [here](https://github.com/filecoin-project/devgrants#submit-a-proposal-for-an-rfp).

Please drop any questions below!

**Comment by waynewyang** [comment]
@pooja Hi,pooja,I have some questions,
1,If we implement the filecoin protocol in Rust, as I konw,libp2p has alreay been implemented in Rust, but we’ll implement some  ipfs component as well,such as IPLD, multiformat,cid and so on, is right?
2,Wave Deadline is also September 30, 2019, 11:59PM PT?
3,What are the requirements for the implementation team?

**Comment by pooja** [comment]
Hi @waynewyang:
1. Yes, you can use an existing Rust implementation of libp2p. And yes, there are some IPFS components you will need to implement in Rust, including IPLD (and CIDs).
2. The Wave 1 deadline passed on September 30, but we are accepting proposals on an ongoing basis. Please apply before the next wave deadline, December 31, 2019.
3. While we do not have explicit requirements for implementation teams, we would prefer teams that have demonstrated experience at implementing complex, high-profile blockchains before. However, this is not a requirement. We encourage all teams with interest to apply!

**Comment by mishmosh** [comment]
Closing since additional grant-funded implementations are now live.
