### ISSUE TITLE
Open Grant Proposal: `IPOS`

### ISSUE THREAD

**Issue by Jeffonemore** [filecoin-project/devgrants#430]
**Name of Project:** IPOS

**Proposal Category:** `devtools-libraries`

**Proposer:** `Jeffonemore`

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** `Yes`

# Project Description

IPOS is an open source decentralized storage protocol that provides [AWS S3](https://aws.amazon.com/cn/s3/) native APIs for developers. IPOS will distribute data stored based on the AWS S3 standard in IPFS. It supports IPFS mainet and private networks by the deployment of IPFS nodes. So as to meet the distributed storage needs of developers.

github: https://github.com/StorerOS/IPOS

website: http://14.215.91.114:8082/ipos/

## Value

1. IPOS help the traditional object storage developer to distribute data stored based on the AWS S3 standard in IPFS

2. If we do not do it right, there should be no risk. Because It now supports IPFS private networks by the deployment of IPFS nodes.

3. We don't have such risks because we already have 5 members working on it, and they are well experienced in executing the things. The only risk that we see is if we don't get enough support from the Filecoin protocol in the long run.

## Deliverables

1. Store the data stored through IPOS on the IPFS mainnet, which is currently only a private network
2. Develop an official website of IPOS to show developers all the functions and examples of IPOS
3. Develop development documents for developers to enable developers to access IPFS through IPOS more efficiently

### Milestone 1:
**Title:** Store the data stored through IPOS on the IPFS mainnet, which is currently only a private network

**Goal:** Store the data stored through IPOS on the IPFS mainnet

**Details:** Store the data stored through IPOS on the IPFS mainnet

**Funding:** $10000

**Achievable Date:** 2022.2.28

### Milestone 2:
**Title:** Develop an official website of IPOS to show developers all the functions and examples of IPOS

**Goal:** Develop an official website of IPOS to show developers all the functions and examples of IPOS

**Details:** Develop an official website of IPOS to show developers all the functions and examples of IPOS

**Funding:** $10000

**Achievable Date:** 2022.3.31

### Milestone 3:
**Title:** Develop development documents for developers to enable developers to access IPFS through IPOS more efficiently

**Goal:** Develop development documents for developers to enable developers to access IPFS through IPOS more efficiently

**Details:** Develop development documents for developers to enable developers to access IPFS through IPOS more efficiently

**Funding:** $10000

**Achievable Date:** 2022.4.30

## Total Budget Requested

Total Budge Requested: $30000

## Maintenance and Upgrade Plans

# Team

## Team Members

wujinquan: Project leader ，https://github.com/Jeffonemore
baijinying: Blockchain development engineer ，https://github.com/baijinying-wc
sunjiebin: Operation and maintenance engineer
luzewei: front-end engineer ，https://github.com/AlexzZzNM

## Relevant Experience

Our team is an early storage service provider on Filecoin. Now focus on the development of Filecoin's infrastructure and ecology.
Our team has vast experience in writing high-quality code and tests. The team has an average experience of 5 years developing scalable solutions around the infrastructure protocol.
Our team is young and enthusiastic about building deep tech in the blockchain ecosystem.

## Team code repositories

https://github.com/StorerOS
https://github.com/StorerOS/IPOS

# Additional Information

**Comment by realChainLife** [comment]
Hi @Jeffonemore thank you for this proposal. We would like to fund the work outlined here. Please email devgrants@fil.org to discuss next steps.
