### ISSUE TITLE
Open Grant Application: Shared Blocklists

### ISSUE THREAD

**Issue by feerst** [filecoin-project/devgrants#431]
# Open Grant Proposal: `Shared Blocklists`

**Name of Project:** BitScreen

**Proposal Category:** `devtools-libraries`

**Proposer:** `feerst`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes

# Project Description

Files contain content and that content, depending on what it is, can have a range of implications. Specifically, the content of files hosted by Filecoin Network storage providers may present at least one of several types of risk. A key type is legal risk. For example, the contents of a given file may be illegal in the jurisdiction where the storage provider is located (or elsewhere) under a range of potential laws, with many related nuances. For example, for some types of content, merely hosting a copy could involve criminal liability for any host. In other instances, hosting a file may give rise to civil liability for some though not all hosts, or require disabling access to the file to avoid liability, under one of the existing "notice and takedown" legal regimes. File contents may present other types of risks too, such as brand risk due to extremist content.

Storage providers seeking to mitigate these risks would benefit from not only the ability to block specific CIDs (by declining to do further storage or retrieval deals for that CID), but from the ability to easily gain knowledge of high-risk files that other storage providers have seen fit to block, and easily adopt those blocklists for their own use.

We propose to build this feature of shareable blocklists into our BitScreen software, which allows storage providers create and implement blocklists.

## Value

Helping storage providers anticipate and mitigate legal and brand risk is crucial to their continued operation and to the health of the network.

The benefits to getting this right include reducing legal risk for storage providers, and helping increase the likelihood that conduct related to the Filecoin Network is legal.

If the Filecoin Network fails to provide mechanisms for detecting and mitigating illegal conduct related to use of the Filecoin Network, it will eventually lead to expensive and/or existential legal risk.

For example, legal action related to illegal content storage on Megaupload led to criminal indictment and extradition of the service's owner, and seizure of hundreds of millions of dollars of company assets.

Developing a tool that will allow storage providers to share information about accused and risky files will help them mitigate risk. However, we do not want this tool to exert an inappropriate centralizing force, under which storage providers reflexively adopt other storage providers' blocklists, which could lead to increasing uniformity of determinations around what constitutes illegal or abusive content, with potential effects including higher prices or decreased availability of certain potentially lawful files.

## Deliverables

The feature would exist as part of Murmuration Labs' BitScreen tool, which is freely available.

## Development Roadmap

As this feature represents a subset of features for the BitScreen tool, we propose simply the Milestone of an operational blocklist feature. Using this feature, a storage provider may browse blocklists made available by assessors (including other storage providers, and other organizations, such as Murmuration Labs), determine how many and which CIDs are included as part of a blocklist, and use the software UI to import a blocklist, and run the list so as to block further storage or retrieval deals for a particular CID.

Our team will be made up of five people -- two software developers, one product manager, one legal policy lead, and a designer.

We propose making the code and a demo available by the end of February 2022.

## Total Budget Requested

We propose a budget of $35,000 to cover engineering, product management, and design resources.

## Maintenance and Upgrade Plans

We plan to offer a hosted version of this software as well as making the code available under an open source license. We plan to have storage providers stress test the feature in early 2022 and push out upgrades after 4-6 months of learnings. We plan to maintain the hosted version indefinitely to ensure it is functional for anyone want to use ut.

# Team

## Team Members

- [Alex Feerst](https://www.linkedin.com/in/feerst/)
- T. Boucher
- Samer Sallam
- Fernando Villaverde

## Team Website

www.murmuration.ai

## Relevant Experience

Murmuration Labs is a leader in web3 trust & safety.  Our team members have been building content moderation tools since 2015 and have worked with a range of companies, from small startups to Fortune 100, on content moderation policy and operations. Our engineering resources are provided in collaboration with keyko, which has considerable experience in both web3 development, and the Filecoin Network.

## Team code repositories

https://github.com/Murmuration-Labs

# Additional Information

For the benefit of storage providers and the network, we plan to continue adding features to BitScreen in 2022 and 2023, and welcome feedback and suggestions on how to maximize their value.

**Comment by realChainLife** [comment]
Hi @feerst thank you for this proposal. We would like to fund the work outlined here. Please email devgrants@fil.org to discuss next steps.
