### ISSUE TITLE
Next Step Microgrant: <Image Sharing as NFT>

### ISSUE THREAD

**Issue by PatelMeet05** [filecoin-project/devgrants#432]
### 1. What is your project? (max 100 words)
This is simple project is for storing images as NFT on IPFS and you can share with anyone by giving CID which is provided by the NFT.Storage. You can also check the balance of any address in any network, in this checking balance I have to use the Covalent and Chainlink API but it is in the working process still not completed. By storing images it will use to share with someone or you can make small groups share images by using Image Sharing As NFT. (libp2p, ipfs, ipld, OrbitDB, Textile, NFT.storage, Web3.storage, Estuary)

Github:  https://github.com/PatelMeet05/Image-sharing
  

2. How are you planning to improve this project? 
I am planning to test it for around 2 months. And with the help of the team we will try to build the best out of it with maintain PRIVACY. Our main agenda is to target public privacy. And after complete testing of the WebApp we will go for the Marketing with the help of some investments

3. Will the work be Open Source?
[CC-BY-SA 3.0] https://ipfs.io/ipfs/QmVreNvKsQmQZ83T86cWSjPu2vR3yZHGPm5jnxFuunEB9u) license for content.

4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
If I selected for the Grant our team will report every week with your teams and will update you weekly with every changes and further planning. Our team has some experienced member and some are new to blockchain but despite they are hardworking and we believe as a TEAM.

5. Does your proposal comply with our Community Code of Conduct?
Yes

6. Links and submissions
GitHub Link: https://github.com/PatelMeet05/Image-sharing
  
* Have you submitted to the Filecoin Community Showcase ?

 https://github.com/filecoin-project/community/discussions/435
  

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://devpost.com/software/image-sharing

### Additional questions:

  * What was the name of the event? 
  ChainLink Hackathon
  https://devpost.com/software/image-sharing

**Comment by SeedingTrees** [comment]
Hi, @PatelMeet05.  I would like to approve this application but I need your email address to send the instructions for receiving your payment.  Please drop your email address here and I will approve this microgrant.

**Comment by PatelMeet05** [comment]
Hello,
Here is email
***@***.***

**Comment by PatelMeet05** [comment]
> Hi, @PatelMeet05.  I would like to approve this application but I need your email address to send the instructions for receiving your payment.  Please drop your email address here and I will approve this microgrant.  

Here is my email patelmeet9631@gmail.com

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
