### ISSUE TITLE
Next Step Microgrant: DScan

### ISSUE THREAD

**Issue by AkhileshThite** [filecoin-project/devgrants#433]
### 1. What is your project? (max 100 words)
DScan is a chrome extension that uploads the content to IPFS and generates decentralized QR codes.
DScan allows you to quickly upload images, audio, video, and any type of files (including NFTs and static websites) to IPFS and get a QR code with IPFS CID and hosted Infura link. Later you can share the QR code or Infura link with everyone.

https://github.com/AkhileshThite/dscan
  
https://chrome.google.com/webstore/detail/dscan-decentralized-qr-co/idpfgkgogjjgklefnkjdpghkifbjenap

### 2. How are you planning to improve this project? (max 200 words)

1. Work on version 2.0, which will contain text and multiple directory uploads.
2. Upgrade from IPFS to Web3 Storage in upcoming releases.
3. Improve UI.
3. Make commercial-style videos so that everyone can understand the software.
3. Build a parent company that will focus on building decentralized tools.
 
### 3. Will the work be Open Source?

Yes.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes.
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes.

### 6. Links and submissions

  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?

https://github.com/filecoin-project/community/pull/411

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?

https://github.com/filecoin-project/community/discussions/410

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

Yes. 
Received 2nd prize for the track Filecoin & IPFS at MARS Asia Hackathon 2021.
https://xathon.mettl.com/event/MarsAsiaHackathon2021
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Name: Akhilesh Thite

Email: akhithite@hotmail.com

GitHub: [@AkhileshThite](https://github.com/AkhileshThite)

Role: Main developer 

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  MARS Asia Hackathon 2021
  * Please link to your hackathon submission
   The Mars Asia Hackathon 2021 submission portal is not publicly visible, please check the following link to verify.
   https://twitter.com/LabsLumos/status/1464498281896054784

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

**Comment by AkhileshThite** [comment]
> This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

Hey! @SeedingTrees,
Sorry I misspelled my email address in the issue, It's akhileshthite@hotmail.com
Don't worry the false email I provided in the above issue doesn't exist.

**Comment by SeedingTrees** [comment]
Thanks for flagging.  I just sent an email to the new address you provided.  Please let me know if you don't receive it.

**Comment by AkhileshThite** [comment]
> Thanks for flagging. I just sent an email to the new address you provided. Please let me know if you don't receive it.

Received. Thank you :)

**Comment by AkhileshThite** [comment]
Hey @SeedingTrees,
I filled out the grant claim form immediately after receiving the email. I did not receive the grant amount in my wallet yet. It typically doesn't take that long right?
Let me know if you need anything from my side.

Thank you.

**Comment by AkhileshThite** [comment]
> Hey @SeedingTrees,
> 
> I filled out the grant claim form immediately after receiving the email. I did not receive the grant amount in my wallet yet. It typically doesn't take that long right?
> 
> Let me know if you need anything from my side.
> 
> 
> 
> Thank you.

Update: received

Thanks

**Comment by SeedingTrees** [comment]
Thanks, @AkhileshThite.  I am happy to learn that you received the funding.

**Comment by AkhileshThite** [comment]
Hey @SeedingTrees! 
I've completed all the milestones for this grant, let me know if there's anything you wanna add :)

Final product: https://chrome.google.com/webstore/detail/dscan-decentralized-qr-co/idpfgkgogjjgklefnkjdpghkifbjenap

Discussion thread updates: https://github.com/filecoin-project/community/discussions/410
