### ISSUE TITLE
Next Step Microgrant: Athena Explorer

### ISSUE THREAD

**Issue by AthenaExplorer** [filecoin-project/devgrants#434]
### 1. What is your project? (max 100 words)
Athena Explorer mainly uses python3 and adopts microservice architecture. It uses django and mysql to provide services of prediction, calculator and pro, and uses flask and mongo to provide on-chain data services. At the same time, it takes full advantage of the distributed database performance to solve the problem of billion-level queries, and also uses redir and kafka as cache and message middleware.

GitHub：https://github.com/AthenaExplorer/AthenaExplorer

Website: https://www.atpool.io/en/

### 2. How are you planning to improve this project? (max 200 words)
1. Optimize ecosystem statistics data, so that users can understand the statistics more quickly and conveniently.
2. Increase the application toolset of the whole IPFS ecosystem, so that users can quickly find the tools they want through the explorer.
3. Add the information section, which will be very convenient for users to know the latest IPFS related information in real time.
 
### 3. Will the work be Open Source?
Yes

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions

  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
https://github.com/filecoin-project/community/pull/419

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
https://github.com/filecoin-project/community/discussions/420

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
1. EXC, product director
2. Saiya, product manager, chenlu9283@gmail.com
3. July, product operation, https://github.com/Doris1943
4. Zhou, front-end developer, https://github.com/zhoupeng296
5. Gt Tao, back-end developer, woshiguotao@gmail.com

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
 Wanxiang Blockchain Hackathon: Digital World 2077

  * Please link to your hackathon submission
https://hackerlink.io/buidl/941?roundProj=834

**Comment by flyworker** [comment]
Will the database part of the devgrant?

**Comment by SeedingTrees** [comment]
Hi, developers.  I am reviewing this microgrant application for the Filecoin Foundation.  I noticed that the links for the project's Github repo and its website are both inactive. I am going to pause on reviewing this application until both of those links are active and at least the repo is populated with the project's details.  Please alert me via comment once you have taken those actions.

**Comment by AthenaExplorer** [comment]
@SeedingTrees Hi, Sir, very happy to hear from you.
I checked our Github repo and website but found no problem.
Could you please re-open again?
GitHub：https://github.com/AthenaExplorer/Profile-and-Update-Points
Website: https://www.atpool.com/en/

**Comment by SeedingTrees** [comment]
Thanks, @AthenaExplorer.  I tried both links and neither of them work for me.  My colleagues previously checked and neither link worked for my colleagues, either.  I cannot review this application without being able to access the repo and/or the website.  Please continue to troubleshoot and update me once the links work for outside parties.

**Comment by AthenaExplorer** [comment]
> Will the database part of the devgrant?

@flyworker  Yes

**Comment by SeedingTrees** [comment]
@AthenaExplorer Can you check the privacy settings on your repo?  It may be marked as private, which is why the link works for you but not for outside parties.

**Comment by AthenaExplorer** [comment]
@SeedingTrees Thanks, Sir, I just updated our Github repo and website.
Kindly check and review again.
GitHub：https://github.com/AthenaExplorer/AthenaExplorer
Website: https://www.atpool.io/en/

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

**Comment by AthenaExplorer** [comment]
@SeedingTrees Sir, our email address is athenaexplorerbc@gmail.com.
We haven't received information about payment.
Could you please help check?

**Comment by SeedingTrees** [comment]
Thank you for the note.  I sent the payment instructions to the personal email addresses listed in the initial application.  I will forward the instructions email to athenaexplorerbc@gmail.com now.

**Comment by flyworker** [comment]
Hi guys
I would like to do some follow up about this project.
I am checking the code and the website.

The website has performance issue when we check the link
https://www.atpool.io/en/blockChain/order
and has no opensource code yet.

I am curious about the timeline and release data for the community.

**Comment by AthenaExplorer** [comment]
Thank you for your attention.
We've already opened source on Github before.
In addition, if the number of visitors or visits too much, the site will be slow to load.

**Comment by flyworker** [comment]
I think the devgrant is asking the contribute opensource it forever for the community access, not less than one month opensource then close it.

@SeedingTrees  Is my understanding correct?

![image](https://user-images.githubusercontent.com/8363795/156433059-8e41393d-004d-475f-950a-5a5f85c3d6c0.png)

> Thank you for your attention. We've already opened source on Github before. In addition, if the number of visitors or visits too much, the site will be slow to load.

**Comment by AthenaExplorer** [comment]
Our Github is https://github.com/AthenaExplorer/AthenaExplorer , not the
one you mentioned.


Charles Cao ***@***.***> 于2022年3月3日周四 03:19写道：
