### ISSUE TITLE
Next Step Microgrant: NFTIZ

### ISSUE THREAD

**Issue by Meyanis95** [filecoin-project/devgrants#435]
### 1. What is your project? (max 100 words)

NFTIZ is a Figma plugin that enables you to transform your design into an NFT. With NFTIZ, it's super easy to turn your Figma creations into NFT, put them on sale on OpenSea, or send them as gifts to your friends.  

https://github.com/Meyanis95/NFTIZ
  

https://www.figma.com/community/plugin/1047579004421824566/NFTIZ

### 2. How are you planning to improve this project? (max 200 words)

The next step is to not only upload the image but all the metadata of a design file, which will allow to link it to an NFT. This will give a quite simple function to save a design file as an NFT, to be able to sell or buy it and to use it directly on the Figma design software.  

### 3. Will the work be Open Source?

Yes

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
  
https://github.com/ipfs/community/pull/719 (not merged yet)

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
  
  
https://github.com/filecoin-project/community/discussions/451

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
ETHGlobal Web3JAM
  * Please link to your hackathon submission
https://showcase.ethglobal.com/web3jam/nftiz

**Comment by SeedingTrees** [comment]
Thank you for this submission.  Can you provide additional details on how this project supports or builds on IPFS and/or Filecoin?  Thanks.

**Comment by Meyanis95** [comment]
This project is built with NFT.storage, it will enable designers to save their work on IPFS. I developing a solution to upload all the data about a Figma design and building a way to save it on IPFS and retrieve it in the form of an NFT.
You can see below the implementation of uploading an image from Figma to IPFS, it's the first version of the app.

https://github.com/Meyanis95/NFTIZ/blob/fd127593c38f9ea33959298d2d143a0efe8edad5/src/app/components/Loader.tsx#L28

**Comment by ErinOCon** [comment]
Hi @Meyanis95, This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

**Comment by ErinOCon** [comment]
@Meyanis95, Can you provide your email address to kick off the grant process?

**Comment by Meyanis95** [comment]
Hey @ErinOCon!
Thanks for your response and happy to be eligible for the grant. My email address is Yanis.meziane@essec.edu

**Comment by ErinOCon** [comment]
@Meyanis95, many thanks!
