### ISSUE TITLE
Next Step Microgrant: <Crypto Lady Gang>

### ISSUE THREAD

**Issue by cryptoladygang** [filecoin-project/devgrants#436]
### 1. What is your project? (max 100 words)
<There is a massive opportunity to support women in NFTs. Women make up 16% of the NFT market even though women make 51% of visual artists. Crypto Lady Gang creates a space and resources for women artists, collectors & developers in the NFT industry to come together and support one another, centering the art and the artist. Crypto Lady Gang is a curated women NFT gallery and shoppable marketplace while simultaneously creating a virtual destination for women to connect and collaborate through forums and profiles. Our business model involves women minting and selling their NFTs directly on the site, which we will utilize NFT.storage and IPFS to do so on-chain.>
  
<https://www.cryptoladygang.io/>

### 2. How are you planning to improve this project? (max 200 words)
<With this grant money, we will be creating an application process for artists, along with profile pages that artists can edit themselves. We will also build non-artist profile pages for community members, such as developers and collectors. This will set us up to fundraise and hire for our next phase, which  will include building an NFT Marketplace and creating a space for women to collaborate. >
 
### 3. Will the work be Open Source?
<We are open to building this as an open source project, and would enjoy collaborating with Protocol Labs to determine the best approach to take. >

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
<Yes!>
  
### 5. Does your proposal comply with our Community Code of Conduct?
<Yes!>

### 6. Links and submissions

  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
  

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
  < https://github.com/filecoin-project/community/discussions/452>

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 N/A 
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Samantha Hume, Founder, cryptoladygang@gmail.com
Rebekah Bastian, Business Advisor, https://github.com/rebekahbastian, rebekah@owntrail.com
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
N/A

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
