### ISSUE TITLE
Next Step Microgrant: DeStore

### ISSUE THREAD

**Issue by surajsingla333** [filecoin-project/devgrants#437]
### 1. What is your project? (max 100 words)

DeStore is a decentralized platform that will provide a one-stop solution for all the processes related to application deploying and listing. For developers and companies, there is a web platform where they can publish their application and for users, there is a mobile store application where they can explore the listed applications and install them on their devices.

Github Repo - https://github.com/De-store/De-Store

Live Website - https://sparkling-disk-9446.on.fleek.co/
Demo video - https://www.youtube.com/watch?v=n-gSDf5BRoM

### 2. How are you planning to improve this project? (max 200 words)

1. **Buy and set up ENS domain** - We first need to buy the Domain for DeStore. We have deployed the site using fleek and will assign the domain to the same. We plan to make the platform completely decentralized and thus will be getting an END domain to do so,
2. **Setup IPFS node for faster response and management** - We are using open IPFS nodes such as infura to publish and fetch data from IPFS. These nodes have certain daily limits which harm the user experience. We will set up out IPFS nodes to make the process much more efficient,
3. **Production level android app** - The current android app is an alpha version and we need to release a production build for the same. We have also worked on the UI improvements and will work on the same as well.,
4. **IOS app intent settings and check the app installation** - We used react-native to build a cross-platform mobile application and we will be utilizing the same to create the IOS build of the app. IOS applications have blockers related to app intent and thus we are researching the same to find a solution.,
6. **Desktop application development** - After the mobile applications are completed to the beta version, we will start the desktop application as well and work on supporting desktop applications on the platform.,
7. **UI/UX improvements** - The platform currently provide very basic functionality and UI. We already have UI designers who are working on better designs for mobile and web applications and we will implement the new designs alongside.

The grant amount will be used in all of these parts, for buying the ENS domain, setting up IPFS nodes and payment for the designer and researcher. The smart contracts are currently deployed on testnet and mainnet deployment will also happen with the grant amount.
 
### 3. Will the work be Open Source?

Yes, It will be under MIT license.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions
  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?

  https://github.com/filecoin-project/community/pull/415
  https://github.com/ipfs/community/pull/726

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?

  https://github.com/filecoin-project/community/discussions/414

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

  1. ETHOdyssey - https://devfolio.co/submissions/destore-f352
  2. Browser3000 - https://browsers3000.devpost.com/submissions/search?utf8=%E2%9C%93&terms=destore&sort=
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

  1. Suraj Singla | surajsingla333@gmail.com | https://github.com/surajsingla333 | Owner
  2. Nipish Saini | nipishsaini13@gmail.com | UI/UX Designer

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  1. ETHOdyssey - https://devfolio.co/submissions/destore-f352
  2. Browser3000 - https://browsers3000.devpost.com/submissions/search?utf8=%E2%9C%93&terms=destore&sort=

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
