### ISSUE TITLE
Next Step Microgrant: FileofExam

### ISSUE THREAD

**Issue by devlordofblock** [filecoin-project/devgrants#439]
### 1. What is your project? (max 100 words)
FileofExam is a project that will enable assessment and evaluation institutions to publish the exam results of their examiners in the IPFS system. The reason for choosing IPFS as the infrastructure of this project is because it is a transparent and decentralized infrastructure, it increases the reliability of the exam result. Exam center will upload results from its own panel or via API. The examiner will also be able to see the result of this exam with the password shared with him. The exam result file will only be hosted in IPFS.

  https://github.com/devlordofblock/FileofExam

### 2. How are you planning to improve this project? (max 200 words)

 I will primarily design a frontend for the project. I want to use Laravel Tailwind for this. For this project, I will primarily use the APIs of IPFS infrastructure providers such as Infura. After integrating this API into Tailwind, exam bodies will be able to upload and annotate their exam results on IPFS. After a while, I'm thinking of setting up a private IPFS pinning service in partnership with testing organizations.

In the first phase of the project, I will use the APIs of Pinning Services such as Pinata. You can see the usage diagram for it below.
[https://ibb.co/ThB3pCj](https://ibb.co/ThB3pCj)
In the second phase of the project, I am planning to set up an IPFS pinning service between testing institutions. Examiners using FileofExam will be eligible to use the private IPFS Pinning Service if they join a portion of their server to the private IPFS cluster. For this, FileofExam needs to reach a certain user base. Therefore, I would appreciate it if you would evaluate the grant according to the first phase of the project.

### 3. Will the work be Open Source?

Yes, MIT.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

  Yes, I agree.
### 5. Does your proposal comply with our Community Code of Conduct?

Yes
### 6. Links and submissions

  Yes
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
  
Not sure
* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
  
  
https://github.com/filecoin-project/community/discussions/455

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  Nazife Sumer
  devlordofcrypto@gmail.com
  Owner
  https://github.com/devlordofblock/

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by SeedingTrees** [comment]
Thanks, @devlordofblock.  Please alert us once you have updated the repo with more progress on this project.  We do not currently have enough information to evaluate this application.  As you make your updates, I would appreciate learning more about how you plan to set up the [private pinning service](https://github.com/ipfs/ipfs-cluster).

**Comment by devlordofblock** [comment]
Hi @SeedingTrees. I just update project information. 
Added Informations:
"
In the first phase of the project, I will use the APIs of Pinning Services such as Pinata. You can see the usage diagram for it below.
https://ibb.co/BgvKFth
In the second phase of the project, I am planning to set up an IPFS pinning service between testing institutions. Examiners using FileofExam will be eligible to use the private IPFS Pinning Service if they join a portion of their server to the private IPFS cluster. For this, FileofExam needs to reach a certain user base. Therefore, I would appreciate it if you would evaluate the grant according to the first phase of the project.
"

If you have any question, I am here for answer. 
Have a nice day...

**Comment by devlordofblock** [comment]
Hi @ErinOCon,
Sorry for this issue, I created the previous sharing link for a while. Here is the permanent link:
https://ibb.co/ThB3pCj
I also updated the link in the application.
Thanks in advance!

**Comment by ErinOCon** [comment]
Many thanks, @devlordofblock!
