### ISSUE TITLE
Open Grant Proposal: Online Store Portal

### ISSUE THREAD

**Issue by byte-me-stan** [filecoin-project/devgrants#441]
Open Grant Proposal: Online Store Portal

---
Name of Project: shopinext

Proposal Category: app-dev

Proposer: Stanley

Technical Sponsor: Pancy jochasinga (https://github.com/jochasinga)

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes, only to the scope of the deliverable of this proposed project.

Project Description
---
Looking forward to build an online store portal for product sellers that runs on IPFS. Integrated shopping cart with crypto payment gateway. To echo "faster and higher performance" for products images, videos previews and faster products search. This is to give better users experience by content routing without using cache servers for images and videos to reduce the operational costs.

This portal allows sellers to manage and list their products. Each product will have a unique and immutable IPFS address and integrated into state management tool will be very efficient.

Value
---
Business use cases for mass adoption and more business users acquisition for Filecoin/IPFS.  This project will spearhead in the market and a strategic project for Filecoin/IPFS. Thus, it will create larger business effects in ecosystem.

Deliverables
---
This portal will allow login for both sellers and buyers using social logins, and allow sellers to upload and manage their products and applications.

Product list portal with images and preview video.
Anonymous visitors can browse / search the products.
Crypto payment gatway.
Shopping cart.
Seller/Admin Dashboard.
Sellers and buyers can view transactions and orders

Development Roadmap
---
![](https://i.imgur.com/TKdoFr9.png)

Total Budget Requested
---
27,500 USDT

Maintence and Upgrade Plan
---
Will continously take comments from community and make improvements to the portal.

Team
---
Stanley - https://www.linkedin.com/in/my07/    

Revelant Experience
---
Worked at F5 networks and FireEye.

Contact Info
---
Stanley
email: we.byte.together@gmail.com

**Comment by byte-me-stan** [comment]
@jochasinga @

**Comment by realChainLife** [comment]
Hello @byte-me-stan thank you for this proposal. We would like to fund the work outlined here. Please email devgrants@fil.org to discuss next steps.

**Comment by jochasinga** [comment]
@realChainLife thanks!
