### ISSUE TITLE
Next Step Microgrant: Samila

### ISSUE THREAD

**Issue by sepandhaghighi** [filecoin-project/devgrants#442]
### 1. What is your project? (max 100 words)

**Samila** is a user-friendly and easy-to-use generative art generator library written in Python, **Samila** lets you create arts based on many thousand points. The position of every single point is calculated by a formula, which has random parameters. Because of the random numbers, every image looks different.
**Samila** is integrated with [**NFT.Storage**](https://nft.storage/) and has this option to upload/backup generated arts(possible NFTs) directly to **IPFS**.

https://github.com/sepandhaghighi/samila
  

### 2. How are you planning to improve this project? (max 200 words)

 1. Create bots(Telegram, Twitter, and ...) for Samila based on a decentralized storage layer
2. Improve generation methods (by using AI,...)
3. Fix current issues
4. Create a client/web app for Samila
### 3. Will the work be Open Source?

Yes. MIT license
### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

 Yes
### 5. Does your proposal comply with our Community Code of Conduct?

Yes
### 6. Links and submissions

  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
  
https://github.com/filecoin-project/community/pull/447

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
  
  
https://github.com/filecoin-project/community/discussions/446  

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
    - Sepand Haghighi - [GitHub](https://github.com/sepandhaghighi) - [Email](mailto:sepand.haghighi@yahoo.com) - Core Developer
    - Sadra Sabouri - [GitHub](https://github.com/sadrasabouri) - [Email](mailto:sabouri.sadra@gmail.com) - Core Developer
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by sepandhaghighi** [comment]
@SeedingTrees @ErinOCon @realChainLife
Hi folks
Just a friendly reminder 🕐 
Any update? Let us know if you need more information for review 💯 

Best Regards
SH

**Comment by ErinOCon** [comment]
Hi @sepandhaghighi, my sincere apologies for the delayed reply. I am pleased to inform you that the grant has been approved! Look out for an email to submit payment details. 

Let's use your existing Community Discussion thread for updates.

**Comment by sepandhaghighi** [comment]
@ErinOCon Hi
I updated the members section (also mentioned in the email).

Best Regards
SH

**Comment by ErinOCon** [comment]
@sepandhaghighi, thank you for the update!
