### ISSUE TITLE
Next Step Microgrant: Braid Science 

### ISSUE THREAD

**Issue by ufkhan97** [filecoin-project/devgrants#444]
### 1. What is your project? (max 100 words)
Braid is trying to fix science publishing by reducing gatekeeping and increasing open access. We want to be a place where scientists can upload their papers via Web3.Storage (utilizing Filecoin and IPFS), review the work of their peers, and be compensated for both. We plan to use OrbitDB as our database technology for storing paper CIDs, user information, comments, and other info. 

Github Repo: https://github.com/ufkhan97/braid
  

Where it started: https://showcase.ethglobal.com/ethonline2021/paperfax
Where it continued: https://showcase.ethglobal.com/web3jam/braid

### 2. How are you planning to improve this project? (max 200 words)
We want to improve our project in three ways:
- Build a Community: We are looking to operate as a DAO. To do this, we need to have a strong online presence through Twitter, Discord, and Mirror. We hope to add many people to our organization who are scientists, lifelong learners, and developers.
- Build a Product: We need to greatly enhance our website. The majority of grant funding would go toward supporting full-time contributors, especially developers, to take the time to improve the user experience. We need a more friendly way to make an account (using your wallet), upload files, retrieve files, and store/retrieve comments. This will mean better integration with Filecoin and OrbitDB 
- Build a Userbase: We hope many of our earliest users will be community members but we also realize we need to reach out to the broader science community and receive feedback from researchers who may really use Braid one day. 
 
### 3. Will the work be Open Source?
Yes, completely. 

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes we will! We already had one meeting with a Filecoin developer (Discordian) who helped point us in the right direction for debugging javascript. We can commit to writing blogposts or twitter threads every Friday on our progress. 

  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions

  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))? 
* 
* Showcase: https://github.com/filecoin-project/community/discussions/377
  
Merged PR: https://github.com/filecoin-project/community/pull/378

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category]
(https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
  
  
Thread: https://github.com/filecoin-project/community/discussions/377 

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  We did begin at a hackathon and received the Web3Storage 2nd place prize: https://showcase.ethglobal.com/ethonline2021/paperfax

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Team:
- Name Umar Khan:
-- ufkhan97@gmail.com
-- Github: ufkhan97 
-- Role: Founder, Community building & outreach
 - Name: Kyle Norkett
-- knorkett@protonmail.com
--Github: cryptoFowl
-- Role: Founder, Backend Engineer
- Name: Andrew Stebbene
-- acstb@hey.com
-- Github: arthropodSeven
-- Role: Frontend Engineer 

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
  * Where it started: https://showcase.ethglobal.com/ethonline2021/paperfax
Where it continued: https://showcase.ethglobal.com/web3jam/braid

You can find us at https://www.twitter.com/braidscience (link in bio to our discord!)

**Comment by SeedingTrees** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
