### ISSUE TITLE
Next Step Microgrant: sched-plugin

### ISSUE THREAD

**Issue by llifezou** [filecoin-project/devgrants#445]
### 1. What is your project? (max 100 words)

At present, the lotus sector [sched](https://github.com/filecoin-project/lotus/blob/master/extern/sector-storage/sched.go) module pays more attention to versatility. It is undoubtedly more general. However, in the actual sealing process, miners may have different needs, and it is likely that lotus `sched` needs to be customized, such as AP/P1 /P2 binding to prevent files transfer, limit the number of workers running, etc. all of which require miners to have technical reserves. 

An effective and flexible scheduling system that can greatly contribute to sealing efficiency. This project is implementing a goal: change the `sched` module of lotus to a `sched-plugin`.

It will bring the following benefits:

- Increase community activity, community members can develop `sched-plugin` according to the actual situation, and this `sched-plugin` is also likely to be used by others.
- For different scenarios, different`sched-plugin` can be used to increase sealing efficiency and cluster scale.

### 2. How are you planning to improve this project? (max 200 words)

- change the `sched` module of lotus to a `sched-plugin`. lotus `sched` can use multiple `sched-plugin`.
- develop a `default plugin` based on the `sched` module of lotus.
- develop a custom plugin to support custom functions such as task binding/running limit.
- maintain `sched-plugin` branch until mature, try to merge into lotus master.

### 3. Will the work be Open Source?
yes

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
yes

### 5. Does your proposal comply with our Community Code of Conduct?
yes

### 6. Links and submissions
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
  
  https://github.com/filecoin-project/community/pull/465
  
* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
  
  https://github.com/filecoin-project/community/discussions/463
### Additional questions:

| Name     | Email              | Github                      | Role      |
| -------- | ------------------ | --------------------------- | --------- |
| llifezou | llifezou@gmail.com | https://github.com/llifezou | Developer |

**Comment by realChainLife** [comment]
Hi @jennijuju does this change need to included in the next lotus-update? Will also appreciate your thoughts on the technical-feasibility of the change-proposal.

**Comment by jennijuju** [comment]
> Hi @jennijuju does this change need to included in the next lotus-update? Will also appreciate your thoughts on the technical-feasibility of the change-proposal.

Hi @realChainLife i missed this ping - sorry about that. There is an issue open in lotus now and I will review with the team and get back to you.

**Comment by jennijuju** [comment]
@llifezou sorry for the late reply! Could you please elaborate more on what’s going to be implemented in the default plug-in and provide a high level  system architecture diagram on how the plug in, we’ll be plugged in?

**Comment by llifezou** [comment]
> @llifezou sorry for the late reply! I’m def interested about the idea but could you a bit more info - Could you please elaborate more on what’s going to be implemented in the default plug-in and provide a high level system architecture diagram on how the plug in, we’ll be plugged in?

@jennijuju thank you!
The most important thing is the abstract scheduling module, which decouples scheduling from lotus. The advantage of this is that adding a plug-in only needs to satisfy the interface defined by the plug-in module, which is convenient for enriching and extending the scheduling function.

The existing scheduling module is general in some cases, but in some scenarios, it cannot meet the requirements, and if the community wants to contribute to the existing scheduling module, it is undoubtedly complicated, and it also has a great impact on lotus. so the scheduling plugin pattern was thought out.

The specific implementation plan is:

1. Decouple current `sched` from lotus, abstract `sched`, and allow `sched` modules to exist independently
2. Change the existing `sched` module to the default `sched plugin`, and the existing scheduling function will still be provided by default. At the same time, it provides a custom plugin implementation: such as ap/p1/p2 binding, the maximum number of runs and other flexible functions for community use and reference.
3. Each plugin will have a name, which can be set in the lotus-miner config.toml. At startup, the `plugin` is loaded according to the `plugin` name set in config.yaml. Each time a lotus-supported `plugin` is added, only a few lines of code need to be changed. 
4. In each plug-in sched, scheduling logic can be added flexibly as needed, without affecting other modules of lotus other than scheduling.

**Comment by llifezou** [comment]
This is a schematic diagram of the system, if more detailed information is required, I will provide

<img width="832" alt="WechatIMG370" src="https://user-images.githubusercontent.com/46102475/162481588-c8ffe182-5973-4ef0-a461-ad672b5403d8.png">
