### ISSUE TITLE
Renovi Marketplace Applications

### ISSUE THREAD

**Issue by mostmojo** [filecoin-project/devgrants#448]
# Open Grant Proposal: `Renovi Marketplace`

**Name of Project:** Renovi Marketplace 

**Proposal Category:** Choose one of `core-dev`, `app-dev`, `devtools-libraries`, `technical-design`, `docs`
core-dev

**Proposer:** `@mostmojo`

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams, include their name and/or github handle here` Sonia John

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Please respond with either "Yes" or "No" Yes

# Project Description

Marketplace, built with love on Solidity and NextJS, enabling architects and 3D designers to buy and sell their NFTs. 

## Value

Unlike other NFT marketplaces, who only offer JPEGs/PNGs, we offer a plethora of file types for Architects and 3D designers to upload and preview. We currently use Pinata to store large file types like GLTF & Obj files.

## Deliverables

CRUD functionality for - creating, reading, updating, deleting NFTs, and user profiles. In future we aim to: Port to Polygon, enable cross platform minting, royalties transfers and introduce filters for various marketplaces in terms of compatibility. E.g. Decentraland, Sandbox, and more. Please see more elaborate breakdown below.

1. File storage

We currently experience a file storage issue with large files. We plan to integrate the Filecoin solution to mitigate gas fees but also allow for larger files, especially for scenes from Unity/Unreal Engine from architects. We are optimistic that the Metaverse will develop far beyond the low polygon Metaverse we have today, and larger files will be in high demand. We want to continue in the decentralized ethos, but at the same time build for the future. 

We aim to store the ID of each NFT of multiple architect-friendly file types on the smart contract, but the actual 3D on Filecoin. This will drastically decrease the buyers' gas fees, but also allow them the ability to mint a diverse range of file formats as NFTs. To ensure we have a working prototype for MVP, at this stage, we'll use Filecoin's API to ensure all endpoints and data is stored there for each file types. We'll start with JPEGs and ZIP files first, and then move forward to the remaining architectural filetypes at a later stage.

Cost: $5K 
Time: 1 month

2. Filecoin's advantage is cross-compatibility with our marketplace and Decentraland, Sandbox and After Math Island where we plan to increase file size storage and make it downloadable for each metaverse 

Cost: $5K 
Time: 1 month

3. NextJS 

We know that Filecoin works best with NextJS, so we envision having a full migration to NextJS serverside rendering in order to help connect/migrate all our processes to Filecoin. To ensure that NextJS is fully rendered with serverside rendering on the current application, all pages and marketplace, alongside wallets are fully functional, since we can allocate more time and resource on this, it is vital we ensure that this is the backbone of all future builds. Here we will ensure all APIs, assets and structure is robust and working, inclusive of all relative QA needed. 

Cost: $15K 
Time: 1 month

4.  Hub 

We aim to create a personal space for every architect, so they can publish their portfolio. For example, every architect or artist will be able to showcase their work that is stored on Filecoin without necessarily having to mint on smart contract every creation. This will not only create a space where architects mint NFTs but also a space where architects communicate and show to one another their creations, pushing forward the idea of architecture in the Metaverse and NFT space. Individuals will then be able to check those portfolios/profiles prior to making a purchase, therefore making more informed decisions. This will entail a CRUD functionality in coding terms and give Renovi's artists more value-added 

Cost: $15K 
Time: 1-2 months

5. On-platform royalties  

By enabling us to give a % cut to each artist, on every sale, we can store all the information both on contract and on Filecoin, where another user can trace back buyers/sellers of each NFT and if there are more filetypes (larger ones), Filecoin would handle the throughput. Some R&D also necessary to unplug Pinata and build out Filecoin. Documentation to be provided on build.

Cost: $10K 
Time: 1-1.5 months

## Development Roadmap

Polygon migration, Filecoin migration for more robust storage, Ethereum bridge, on-platform royalties, cross platform royalties, upgradable smart contracts (reducing the need to have multiple versions of the platform), DAO

## Maintenance and Upgrade Plans

# Team

## Team Members

Andy Charalambous - Co-Founder

https://www.linkedin.com/in/andy-charalambous-5882a347/

Andy’s career covers investment banking, asset management and he has been an investor and an advocate in the crypto space since 2016. Andy brings with him over thirty years of investment banking and finance experience to the digital world.

Jacob Papageorgiou - CTO / Co-Founder

https://www.linkedin.com/in/jacob-papa/

In the last decade, Jacob has led teams to $5M+ investments in the U.S and U.K and has worked alongside developers of the likes of TransferWise & Revolut. He's been a Technical Advisor to Blockchain and Private Equity startups raising $200K-1M and has led tech teams with clients of the likes of Nike, Vodafone, Adidas, National Lottery, Gordon Ramsay and UCL. He has been a fellow educator for Brixton-based code camps and global leading tech boot camp Le Wagon, prior to founding Mojo Digital of which he has a client base of over 300 web applications/sites to date prior to co-founding Renovi.

Adonis Zachariades - Co-Founder 

https://www.linkedin.com/in/adoniszachariades/

Adonis has a Masters in Investment Analysis from Stirling University with majors in Economics and Finance. He has researched extensively through his thesis the eﬃciency of cryptocurrency markets. Adonis is a futurist and has given presentations to universities about how the Metaverse will change our current status quo. He currently leads Renovi’s idea creation and management. 

Svetoslav Gyuretsov - Community Manager  

https://www.linkedin.com/in/svetoslav-gyuretsov-a51560131/
​​
Svetoslav is a Computer Science with Games Development graduate from Northumbria University in Newcastle UK. As a crypto analyst in Ramek Asset Management, he has supported the senior management team with research and analysis regarding market strategies in the cryptocurrency, Defi and NFT industries. His communication skills make him a perfect candidate to manage Renovi’s social media. He enjoys spending his pastime researching new investment opportunities.

George Manousios - Business Development 

https://www.linkedin.com/in/george-manousios-95167a31/

Graduated from ICMA Business School in 2011 having completed his Master’s Degree in Financial Risk Management. He is the Chief Investment Officer at Ramek Asset Management based in the City of London. With over 6 years of financial markets investment and analysis experience in fixed income, new issues and equity IPOs George brings a range of experience to Renovi.  

Stavros Zachariades - Architectural Curator/Advisor   

https://www.linkedin.com/in/stavrosz/

Architect and designer specialising in super-prime residential developments with built works in central London. Architecturally trained at the University of Bath, UK and the USI, Switzerland. Some of his built works that he was involved in are the Clarges Mayfair including 1 Ashburton Place, 7 Clarges and London’s Kennel Club. Stavros is also an architecture design studio tutor at the University of Bath. 

## Team Website

https://renovi.io

## Relevant Experience

7+ years of full stack web development and Solidity development 
Stack: NodeJS, React, NextJS
Secondary Stack: Python Flask for Rest APIs, Laravel for easy web dev

Built centralised exchange “London Block Exchange” - 5M investment
Built Renovi Marketplace 
Partnered with FIFA/EA Sports
Partnered with Mojo Digital
Partnered with Linode, U.S.A (DevOps)
Portfolio of clients exceed 20M in combined value (100 Tech Radar Startups UK, Mixmob - Solana Ventures @ 3M)
Other clients - Gordon Ramsay, reputable Architects, Lesley Sharp (BBC/Guardian/iTV), EA Sports, National Lottery, Ford

## Team code repositories

@mostmojo @nickelefth @nobbisky

https://github.com/mojodigital/renovi-nft

# Additional Information

Pitch deck: https://bit.ly/pitch-rdmap-rnvi  

Next Top Metaverse Build Competition Hosted By Renovi  

Topmetaversebuild.com 

https://www.youtube.com/watch?v=dBgF2Wt9cmk&t=55s

**Comment by realChainLife** [comment]
Hi @mostmojo thank you for this proposal, please additional technical detailed to your development roadmap specifically: 
- Deliverables specifications
- share key milestones and corresponding budget allocation

**Comment by mostmojo** [comment]
Update of team and deliverables

**Comment by realChainLife** [comment]
Thanks for the recommendations @mishmosh 

Hi @mostmojo thanks for the updates, we would like to fund part of your proposal. Please email devgrants@fil.org to discuss next steps.

**Comment by realChainLife** [comment]
Re-opening for milestone update

**Comment by mostmojo** [comment]
thanks @realChainLife - now updated from last week

**Comment by realChainLife** [comment]
Thanks for the updates @mostmojo we'll be sharing the contracting next steps via email.
