### ISSUE TITLE
Open Grant Proposal: Basic Beasts

### ISSUE THREAD

**Issue by bz-hashtag-0780** [filecoin-project/devgrants#450]
# Open Grant Proposal: `Basic Beasts`

**Name of Project:** `Basic Beasts - Play-2-earn NFT Collectibles Game`

**Proposal Category:** `app-dev`

**Proposer:** `bz-hashtag-0780`

**Technical Sponsor:** `Pancy/jochasinga`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** `Yes`

# Project Description

Play-2-earn (P2E) games are designed to be profitable for players who participate. Unfortunately many projects present this as the main objective in the game which encourages players to mindlessly buy and sell NFTs that lack uniqueness and usefulness. Basic Beasts aims to fix this problem through game mechanics that directly impact scarcity, multiple reasons to interact with unique NFTs, and opportunities for players to have a voice in the community to direct and shape the future of the project. 

Built on the Flow Blockchain, using pinata.cloud for the NFTs’ images and videos, Basic Beasts is a P2E collectibles NFT game inspired by Pokémon. Players can collect, evolve, trade, and breed beasts. By owning a beast, players become community members that can participate in the direction of the project. The core mechanic that differentiates Basic Beasts is the evolution of beasts. In order to evolve to the next level, a player must combine beasts from the previous level, in turn burning them from the game. These player choices directly impact the scarcity of the beasts, in turn impacting the rest of the community. 

Additionally, player choices will impact the traits of the specific beasts they collect. Nicknames, gender, interaction with fungible tokens, and fusing all lead to creating and collecting beasts that have unique traits, such as skill names and skin types. These decisions contribute to a player’s collector score, which will be displayed on leaderboards and profile pages; a prime way to show off and flex beast collections. All of these interactions with the application work toward the goal of building out player Dexicons in hopes of collecting all 150 beasts and unlocking a legendary 151st beast! 

In addition to playing, by owning a beast, players become community members that can participate in the direction of the project. With this, Basic Beasts is working with the Emerald City DAO (The First DAO on Flow) to ensure that the necessary DAO tooling will be available for the community. By involving the community, as well as being sure not to compromise the economic quality and experience, a game is created that is profitable and, more importantly, enjoyable to play. 

Basic Beasts’ goal is to onboard the next generation into the blockchain. We want to provide a place where everybody is welcome to join our community and at the same time be rewarded. We would like to make sure that Basic Beasts has something for everyone - collecting, trading, art, culture, entertainment, and participation in the metaverse.

![bb ipfs](https://user-images.githubusercontent.com/88026162/153921292-18943888-aa3b-4379-b9a8-8965eec145ca.png)

## Value

Basic Beasts will use pinata.cloud for its NFTs, both for beasts and its avatar/profile picture project. Working closely with Emerald City allows Basic Beasts to contribute our open-source code to educate and onboard more developers into the Flow and Filecoin ecosystem, thus increasing the adoption of IPFS. Making the code open-source ensures that other projects can follow suit and copy the recipe.

Basic Beasts is a project that is inviting for players of all ages. By basing the project off of popular mainstream games that have been around for decades, including Pokemon and Tamagotchi, Basic Beasts has gameplay mechanics that are easy to understand and familiar to many. Paired with seamless onboarding via the Blocto app and an inviting Discord community, Basic Beasts is a project that can be played and enjoyed by all.

Basic Beasts wants to: 
- Onboard people from Web 2.0 into Web 3.0
- Set up standards for the metaverse
- Strengthen developer knowledge and community
- Educate developers, and even kids, about NFTs 

## Deliverables

Receiving the IPFS grant would mean Basic Beasts will be able to deliver an interactive NFT collectibles game experience built around the following core elements:
- NFT Management System
- Scoring System
- Marketplace
- Evolution
- Breeding

### NFT Management system
Basic Beasts will have a frontend that allows an admin to manage NFTs and fungible tokens in the Basic Beasts ecosystem. This frontend makes it easier for an admin to upload images and videos to IPFS and minimize the risks of typo errors when minting and distributing NFTs.

![An overview of a beast NFT and its different types of skins](https://user-images.githubusercontent.com/88026162/153922743-cbbd8976-bf82-44c2-a378-964d7456313d.png)
An overview of a beast NFT and its different types of skins

### Scoring System
To make an enjoyable game, players must receive a sense of accomplishment and a feeling of progress when collecting, evolving, trading, or breeding beasts.
_Collector score_ - Points are awarded to players as they interact with the application.  
_Dexicon_ - Similar to a Pokédex, this tool will show a player’s collection of beasts. If a player is able to collect all 150 different types of beasts, a legendary # 151 beast can be claimed.
_Leaderboards and profile pages_ - Spaces where players can compare themselves with others and have fun showing off and flexing their beast collection.

![Part of the Dexicon displaying beasts #001 - #003](https://user-images.githubusercontent.com/88026162/153923266-f4b2272c-b218-4ba8-a478-bf0b1efe0511.png)
Part of the dexicon displaying beasts # 001 - # 003

### Evolution
Players can evolve higher-level beasts by combining three of the same star-level beasts. When this happens, the combined beasts are burned from the project. This process is necessary to collect star-level two and three beasts. 
![Example of evolving a level two beast by combining three level one beasts](https://user-images.githubusercontent.com/88026162/153923891-7a7dc587-49c9-4735-97d5-8a75658298b0.png)
Example of evolving a level two beast by combining three level one beasts

### Marketplace
There is a limited amount of packs available as the blockchain enables the NFTs to be scarce. When minting the beast that a player gets from a pack is random. The secondary marketplace allows players to buy or sell specific beasts in order to complete their dexicon, evolve, breed or just hodl.

### Breeding
Breeding is a minting mechanism that allows players to make additional normal skin beasts. This increases the collector score and adds beasts to the Dexicon. Inspired by CryptoKitties and Axie Infinity, in order to breed a beast, one will need a sire, a matron, and a love potion.
![Example visual of breeding](https://user-images.githubusercontent.com/88026162/153923775-e9df88d6-bbcd-4af1-af93-f281d4755b03.png)
Example visual of breeding

By implementing the above features, Basic Beasts will be able to provide a P2E experience in the following ways:
1. Increase the collector score to **receive tokens.**
2. Breed beasts and **sell them** in the secondary marketplace.
3. Evolve beasts and **sell them** in secondary marketplace.
4. Make love potions and **sell those** in secondary marketplace.
5. Become the first owner of a beast through pack drops, evolution, or breeding and **earn 5% lifetime royalty** every time the beast gets traded in secondary.

### Phase 1: NFT and fungible token UI Management system (3/31/2022) - Amount required $16,000
Bz (Smart contract & frontend dev) and WilliBlue (UI/UX designer & frontend dev)
- Write smart contracts for NFT, packs, collector score, evolution, and breeding
- UI for smart contracts, testing of NFT, packs, collector score, evolution, and breeding.
- Frontend for an admin account (Admin frontend)
  - Interact with the NFT smart contract
  - Create beast templates
  - Upload images and videos to IPFS
  - Mint beast templates as NFTs
  - Overview of each template, minted NFTs, admin NFT collection, number of NFTs transferred to users.
  - Mint fungible tokens and infuse them into a non-transferable NFT pack along with a beast NFT and transfer the packs to users.

Bz (Decision maker) and Kyle (Community Lead)
- Launch community events, AMAs, and collab with ecosystem partners.

Bz (Decision maker), WilliBlue (Designer), and PollyMiau (Designer)
- Design at least five new beasts in 5 different skins including animations.

### Phase 2: NFT pack distribution inbox system (4/30/2022) - Amount required $16,000
Bz (Smart contract & frontend dev) and WilliBlue (UI/UX designer & frontend dev)
- Frontend for users at Basic Beasts’ website (End-user frontend)
  - Submit pack orders and setup NFT collection and fungible token vaults transaction
  - Inbox page where users can redeem their packs at any time
  - Updated collection page where users can unpack packs to receive beasts and fungible tokens
- Updated admin frontend to distribute packs to multiple users’ NFT inbox collections by uploading a .csv file

Bz (Decision maker) and Kyle (Community Lead)
- Launch community events, AMAs, and collab with ecosystem partners.

Bz (Decision maker), WilliBlue (Designer), and PollyMiau (Designer)
- Design at least five new beasts in 5 different skins including animations.
- Design higher-level beasts in 5 different skins including animations.

### Phase 3: Collector score, leaderboard, profile pages (5/31/2022) - Amount required $18,000
Bz (Smart contract & frontend dev) and WilliBlue (UI/UX designer & frontend dev)
- End-user frontend
  - Collector score smart contract that shows how many points a user has from getting beast NFTs from packs, trading, evolution, or breeding.
  - Leaderboard that reads from the collector score and all user beast collections to see who has the highest collector score, buying volume, sale volume, and most NFTs
  - Profile pages will allow users to view and follow other players’ beast collections; either through our own smart contract or through find.xyz
  - Personal Dexicon to show which NFTs a player has previously collected and currently holds.

Bz (Decision maker) and Kyle (Community Lead)
- Launch community events, AMAs, and collab with ecosystem partners.

Bz (Decision maker), WilliBlue (Designer), PollyMiau (Designer), and more designers
- Design at least five new beasts in 5 different skins including animations.
- Design higher-level beasts in 5 different skins including animations.
- Commence Avatar/Profile Picture (PFP) designs.

### Phase 4: Evolution (6/30/2022) - Amount required $18,000
Bz (Smart contract & frontend dev) and WilliBlue (UI/UX designer & frontend dev)
- Smart contract to burn three beast NFTs to mint a higher-level beast, with a chance of getting a rare mythic 1/1 skin of the higher-level beast.
- Admin of smart contract can adjust the chances of getting the rare mythic skin.
- End-user frontend to allow users to pick which three beasts they want to evolve into a higher-level beast.
- Implement animations for evolution

Bz (Decision maker) and Kyle (Community Lead)
- Launch community events, AMAs, and collab with ecosystem partners.

Bz (Decision maker), WilliBlue (Designer), PollyMiau (Designer), and more designers
- Design animation for evolutions
- Design at least five new beasts in 5 different skins including animations.
- Design higher-level beasts in 5 different skins including animations.
- Design more traits for PFP.

### Phase 5: Marketplace (7/31/2022) - Amount required $18,000
Bz (Smart contract & frontend dev) and WilliBlue (UI/UX designer & frontend dev)
- Smart contract for a secondary marketplace to support marketplace fees, auctions, bids, and lifetime royalty payouts to the first owner of a beast NFT.
- Frontend with special filter and sorting options that makes sense for beast NFTs exclusively, as those contain several attributes for different use cases

Bz (Decision maker) and Kyle (Community Lead)
- Launch community events, AMAs, and collab with ecosystem partners.

Bz (Decision maker), WilliBlue (Designer), PollyMiau (Designer), and more designers
- Design at least five new beasts in 5 different skins including animations.
- Design higher-level beasts in 5 different skins including animations.
- Design more traits for PFP.

### Phase 6: Breeding (8/31/2022) - Amount required $18,000
Bz (Smart contract & frontend dev) and WilliBlue (UI/UX designer & frontend dev)
- Smart contract that mints new beasts using a sire and a matron beast NFT and based on a set of requirements set by an admin. Breeding is to require not only beast NFT but also several fungible tokens
- Smart contract to mint love potions using other fungible tokens. Admin set the requirement of the number of fungible tokens needed.
- Frontend where users can use their matron and sire for breeding.

Bz (Decision maker) and Kyle (Community Lead)
- Launch community events, AMAs, and collab with ecosystem partners.

Bz (Decision maker), WilliBlue (Designer), PollyMiau (Designer), and more designers
- Design at least five new beasts in 5 different skins including animations.
- Design higher-level beasts in 5 different skins including animations.
- Design more traits for PFP.

Note: Some specification details might change as Basic Beasts has launched. We will continuously test our application with our community and iterate based on the feedback we receive.

## Total Budget Requested

We are seeking a total of $104,000 with the following budget breakdown 

| Phase | Milestone Deadline | Amount | Uses |
| ----- | ------------------ | ------ | -------------------------- |
| 1     | 3/31/2022          | $5,000 | Smart Contracts & Frontend |
| 1 	  | 3/31/2022          | $5,000 | UI/UX Design & Frontend    |
| 1     | 3/31/2022          | $4,000 | Marketing & Pixel designs  |
| 1     | 3/31/2022          | $2,000 | Community & Collabs        |
| 2     | 4/30/2022          | $5,000 | Smart Contracts & Frontend |
| 2 	  | 4/30/2022          | $5,000 | UI/UX Design & Frontend    |
| 2     | 4/30/2022          | $4,000 | Marketing & Pixel designs  |
| 2     | 4/30/2022          | $2,000 | Community & Collabs        |
| 3     | 5/31/2022          | $5,000 | Smart Contracts & Frontend |
| 3 	  | 5/31/2022          | $5,000 | UI/UX Design & Frontend    |
| 3     | 5/31/2022          | $6,000 | Marketing & Pixel designs  |
| 3     | 5/31/2022          | $2,000 | Community & Collabs        |
| 4     | 6/30/2022          | $5,000 | Smart Contracts & Frontend |
| 4 	  | 6/30/2022          | $5,000 | UI/UX Design & Frontend    |
| 4     | 6/30/2022          | $6,000 | Marketing & Pixel designs  |
| 4     | 6/30/2022          | $2,000 | Community & Collabs        |
| 5     | 7/31/2022          | $5,000 | Smart Contracts & Frontend |
| 5 	  | 7/31/2022          | $5,000 | UI/UX Design & Frontend    |
| 5     | 7/31/2022          | $6,000 | Marketing & Pixel designs  |
| 5     | 7/31/2022          | $2,000 | Community & Collabs        |
| 6     | 8/31/2022          | $5,000 | Smart Contracts & Frontend |
| 6 	  | 8/31/2022          | $5,000 | UI/UX Design & Frontend    |
| 6     | 8/31/2022          | $6,000 | Marketing & Pixel designs  |
| 6     | 8/31/2022          | $2,000 | Community & Collabs        |

## Maintenance and Upgrade Plans

The Basic Beasts team is remote and we intend to attract talent from all over the world to ensure that the application not only gets maintained, but will also get new features and project expansion. The co-creator, bz, has up until now been the single person to handle most things related to Basic Beasts. Despite being such a small team, we have grown into a community with thousands of members in a short period of time. We are confident that by expanding the team we can accomplish much more at a faster pace.

With the help of funds from IPFS to expand the team, we plan to have our core features implemented as fast as possible. Once the core features have been implemented and we see user adoption, we move into an interoperable metaverse and work with other projects that could allow our users to interact with their NFTs in a new way. At the same time, we will look into the opportunities of building a battle or social simulator game for the Basic Beasts universe.

# Team

## Team Members

BeastKid21 - Brainchild
BeastKid21 is the 11-year old who came up with the idea of making NFTs that were inspired by Pokémon. While currently occupied with school, he works alongside his brother bz on the creative development of beast names, stories, and skills. He also creates video content for the community.

bz - Project Lead
bz leads the development and product design of Basic Beasts. Before launching Basic Beasts with his little brother, he spent six years on his web agency, serving thousands of customers by providing software solutions to B-2-B clients and service subscriptions to online consumers. He is responsible for the full-stack and blockchain development as well as the design and marketing of Basic Beasts.

WilliBlue - Frontend and Blockchain developer. Design Lead
WilliBlue is a UI designer, frontend, and blockchain developer. Before Basic Beasts, she  worked with bz for six years at the web agency as a project manager and web developer. She has been designing many of the beasts and assists with frontend development and testing of smart contracts and UI.

Kyle Patrick - Community Lead
Kyle is an NFT enthusiast and is studying Political Science. He joined the Discord a week after Basic Beasts had launched and quickly became the most engaged community member. He now leads the effort of building and growing the community.

Pollymiau - Graphical Designer
Pollymiau is a talented 2D & 3D designer. She has recently finished her studies in Design and is now available to help build Basic Beasts into a great collectibles game. Before Basic Beasts, she worked with bz and WilliBlue for six months on a project that included 3D unity characters.

## Team Member LinkedIn Profiles

Working in Web3 offers the unique opportunity of keeping one’s privacy. Because of this, most of the team members wish to continue working under pseudonymous names. However, each member will gladly share resumés and verify identities with IPFS through private emails or DMs.

## Team Website

https://basicbeasts.io/

## Relevant Experience

**Awards and Recognitions**
Basic Beasts won Mercury Hackathon in November 2021 https://angelhack.com/blog/announcing-mercury-hackathon2021-winners-%F0%9F%8E%89.html/ 
Basic Beasts is also the grand winner of Hyperhack by Decentology in December 2021 with three members of the team being winners (bz, WilliBlue, and Kyle) https://www.decentology.com/hyperhack 

**Collaborations**
AMA with Flowverse https://youtu.be/kczKvmwvNyw  
Flow China - https://youtu.be/acqVKAZYBJ0 (Video that Flow China used and translated for the Chinese Flow community)
Project Demo with Flow during Office Hours - https://youtu.be/Co-DERhq1Fg 
And many other AMA’s, Twitter spaces, and community events.

**Launching Monthly Drops**
Since launching in late October 2021, Basic Beasts has released a drop each month to accumulate users and receive feedback. So far, we have done 4 drops and sold 1158 packs - $51k

**Building a community**
Since launch, we have gathered 4.5k+ Discord members, 2k+ Twitter followers, and 500+ NFT holders.

## Team code repositories

https://github.com/basicbeasts/ 

# Additional Information

Basic Beasts has gone from being a fun little family project to a full-fledged community, with the purpose of making NFTs fun and interactive and helping the adoption of P2E games. We want to help onboard many more people into the NFT space. The collectibles game will not be the end result of the project but an entry to a space of much bigger opportunities.

Whitepaper: https://whitepaper.basicbeasts.io/
Official Website: https://www.basicbeasts.io/
Twitter: https://twitter.com/basicbeastsnft
Discord: https://discord.gg/basicbeasts
Youtube Channel: https://www.youtube.com/channel/UCFpEOzGU8fn-e8QKIvMvVKw

**Comment by realChainLife** [comment]
Hi @bz-hashtag-0780 thank you for this proposal. We would like to fund the work outlined here. Please email devgrants@fil.org to discuss next steps.
