### ISSUE TITLE
Open Grant Proposal: NodeGateway

### ISSUE THREAD

**Issue by Jeffonemore** [filecoin-project/devgrants#454]
**Name of Project:** `NodeGateway`

**Proposal Category:** `devtools-libraries`

**Proposer:** `Jeffonemore`

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** `No`

*Considering the security of node services, only the front-end modules are open source, and other services are not open source for the time being. We understand that many blockchain explorers do this too*

# Project Description

#### Why is the NodeGateway?
We all know that FIL community developers are waiting for the release of the much-anticipated FVM. It is believed that FVM will bring more users and traffic to the FIL ecosystem. However, similar to EVM, developers need to deploy their own FIL nodes to develop DAPP in FVM or other applications in Filecoin, which is not friendly to developers and requires more labor and technical success. So we developed a node access service platform named NodeGateway.

#### What's the NodeGateway?
NodeGateway is blockchain node access service platform similar to infrua on Ethereum which is a public blockchain（will support FIL、ETH etc）node access service for developers. Developers who want to develop DAPP in FVM or other application can use NodeGateway API to interact with the chain without deploying their own blockchain nodes.We will technically guarantee its strong and stable performance.Assuming that the developer has already use FIL node which they deployed self before, they can access the NodeGateway only by modifying the URL without changing the interface.

#### Github：
https://github.com/StorerOS/NodeGateway

#### Website：
https://node-gateway.storeros.com/console

username:test

password:test

Note: Under development, the function is not perfect

## Value

1. NodeGateway help developers who are willing to develop dapps or applications in Filecoin to reduce the development threshold and cost. Contribute to the long-term development of the Filecoin ecosystem.

2. If we do not do it right, there should be no risk. Even if it fails, NodeGateway will be an important infrastructure in a filecoin.

3. We don't have such risks because we already have 7 members working on it, and they are well experienced in executing the things. The only risk that we see is if we don't get enough support from the Filecoin protocol in the long run.

## Deliverables

 
1.Construction and deployment of Filecoin node operating environment

2.Basic functions of the client, including the development of login, homepage, statistics, and personal center

3.Basic functions of the background management terminal, including the development of login, project management, membership management, statistics management, and system management

4.Stability and concurrency testing and optimized development (multi-node) to ensure developer user experience

5.Development of Chinese and English language versions of the client

6.Official website and developer documentation, tutorial development

### Milestone 1:
**Title:** 

1.Construction and deployment of Filecoin node operating environment

2.Basic functions of the client, including the development of login, homepage, statistics, and personal center

3.Basic functions of the background management terminal, including the development of login, project management, membership management, statistics management, and system management

**Goal:**
Developers who want to develop application can preliminary use the NodeGateway API which as same as Filecoin node RPC API to interact with the chain without deploying their own blockchain nodes.

**Details:** 

![image](https://user-images.githubusercontent.com/90947287/155093221-0d0799a9-ff20-46be-8374-e4d6917f6123.png)

![image](https://user-images.githubusercontent.com/90947287/155093285-063d1b4a-ed9e-4dde-ab70-d2d51afa6a38.png)

**Member:**
Wu J.: Blockchain researcher/Leader https://github.com/Jeffonemore
Xu Z.: Product Manager
Qin R.: Blockchain development engineer 
li B.: Go development engineer
Lu Z.: front-end engineer   https://github.com/AlexzZzNM
Sun J.: Operation and maintenance engineer
Yao H.: front-end engineer

**Funding:** $140000

**Achievable Date:** 2022.3.31

### Milestone 2:
**Title:** 

4.Stability and concurrency testing and optimized development (multi-node) to ensure developer user experience

5.Development of Chinese and English language versions of the client

6.Official website and developer documentation, tutorial development etc.

**Goal:** Since the feature implemented in milestone 1 is only a beta version, developers may need to rely on the guidance of NodeGateway team to use the feature. Milestone 2 implements complete developer tool functions. Developers can access NodeGateway through the official website and developer documentation and realize a series of operations similar to those of the FIL node, and provide quality services for developers who require higher service requests. Higher-priced API services.

**Details:**
4.Stability and concurrency testing and optimized development (multi-node) to ensure developer user experience

5.Development of Chinese and English language versions of the client

6.Official website and developer documentation, tutorial development etc.

Wu J.: Blockchain researcher/Leader https://github.com/Jeffonemore
Xu Z.: Product Manager
Qin R.: Blockchain development engineer
li B.: Go development engineer
Lu Z.: front-end engineer   https://github.com/AlexzZzNM
Sun J.: Operation and maintenance engineer
Yao H.: front-end engineer

**Funding:** $60000

**Achievable Date:** 2022.4.30

## Total Budget Requested

Total Budge Requested: $200000

## Maintenance and Upgrade Plans

# Team

## Team Members

Wu J.: Blockchain researcher/Leader https://github.com/Jeffonemore
Xu Z.: Product Manager
Qin R.: Blockchain development engineer 
li B.: Go development engineer
Lu Z.: front-end engineer   https://github.com/AlexzZzNM
Sun J.: Operation and maintenance engineer
Yao H.: front-end engineer

## Team Website

Coming soon

## Relevant Experience

Our team is an early storage service provider on Filecoin. Now focus on the development of Filecoin's infrastructure and ecology.
Our team has vast experience in writing high-quality code and tests. The team has an average experience of 5 years developing scalable solutions around the infrastructure protocol.
Our team is young and enthusiastic about building deep tech in the blockchain ecosystem.
BTW, The [UniFile](https://github.com/StorerOS/UniFile) and [IPOS](https://github.com/StorerOS/IPOS) which be developing by our team have been accepted now.

## Team code repositories

https://github.com/StorerOS

# Additional Information

**Comment by realChainLife** [comment]
Hi @Jeffonemore thank you for this proposal. I'd like to learn more about this proposal and how it ties into your project overall roadmap and the composable components with UniFile and IPOS. Lets schedule a call via email.

**Comment by Jeffonemore** [comment]
> Hi @Jeffonemore thank you for this proposal. I'd like to learn more about this proposal and how it ties into your project overall roadmap and the composable components with UniFile and IPOS. Lets schedule a call via email.

Hi @realChainLife , Is any news about the next step?
