### ISSUE TITLE
Next-Step-Microgrant-DO-OR-DAON'T

### ISSUE THREAD

**Issue by Mistrymm7** [filecoin-project/devgrants#455]
### 1. What is your project? (max 100 words)
Our team developed Do or DAON’t which supports new DAO joiners to evaluate the transparency and decentralization of a DAO. With the help of our trust scores, they will only join DAOs that align with their values!

[ Link to Github repo](https://github.com/Mistrymm7/eth-denver-do-or-daont)  
  
[Link to demo](https://vimeo.com/679698184)

### 2. How are you planning to improve this project? (max 200 words)
We are storing offchain governance and proposals data in decentralized storage using Web3.Storage and combining it with Chainlink Keepers to automate daily calls of external API in hybrid governance smart contract which queries latest CID and stores offchain data > onchain using ERC721 and IPFS. 

We would like to develop webapp where anyone can customize and integrate their own API token of Web.Storage in initial prompt which makes it scalable and useful globally.  Additionally, we would like to experiment with governance data structures format and storage in IPFS. We believe this tool can revoluntize the future of DAO governance and voting by integrating Hybrid governance smart contracts where IPFS plays a key role in the workflow.

Feedback from Ruben (IPFS Bounty Judge ) at ETH Denver 2022 was quite helpful.
 
### 3. Will the work be Open Source?
 Yes, MIT license for code

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
No,
https://www.ethdenver.com/bounties/ifpsfilecoin  

### Additional questions:
Team Info

Name: Valerie Grappendorf , Email : valerie.grappendorf@arcor.de,  Github : https://github.com/valeriegrappendorf, Role: UX/UI Background: UX Design

Name: Sianoi Kimari ,  Email : seiyanoikimari@gmail.com,  Github : https://github.com/Sianoi, Role: Organizational Development and Leadership Researcher (ODL) Background: ODL and Data Analytics

Name: Mayur Mistry, Email : mmistry2@illinois.edu,  Github : https://github.com/Mistrymm7, Role: Applications Developer and Design Technologist Background: Architect and Developer

* If your project was created as part of an event or hackathon: Yes, 

  * What was the name of the event? : ETH Denver 2022
  * Please link to your hackathon submission: https://hackerlink.io/buidl/2112

Additional Info:

Model Architecture

![image](https://user-images.githubusercontent.com/7644450/155120948-cf3be45e-17bc-4992-9668-d9ecc1b45d83.png)

![team](https://user-images.githubusercontent.com/7644450/155121108-135617b7-3290-4474-ade3-55dc92d8261b.png)

**Comment by ErinOCon** [comment]
This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
