### ISSUE TITLE
Grant for SnowX

### ISSUE THREAD

**Issue by TaigaTigerKobayashi** [filecoin-project/devgrants#456]
# Open Grant Proposal: `Project Title`

**Name of Project:**
SnowX
**Proposal Category:** Choose one of `core-dev`, `app-dev`, `devtools-libraries`, `technical-design`, `docs`
app-dev
**Proposer:** `replace with your GitHub username`
Thomas Kobayashi
**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams, include their name and/or github handle here`
Pooja Shah(ETHDenver)
**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Please respond with either "Yes" or "No"
No
# Project Description

Collectors cannot see VR art(NFT) in VR before they buy, which becomes an obstacle for the market of VR art(NFT).
We're developing an Oculus app of marketplace for VR arts(NFT). We've interviewed 80 VR artists and NFT collectors, and made a FB messenger group with them to build our product together.
demo video https://youtu.be/RyXoeRzKaDA

## Value
VR arts are exported as glb file, and the file size is huge. Moreover, we're focusing on Tilt Brush art whose file seize is between few MB to 1 GB. So we use File coin a lot. Also, since this is the first project to try to make VR marketplace in VR, File coin ecosystem will receive knowledge about VR art files. We have 2 challenges for this project.
First one is cash flow. We need to spend money to storage before VR arts will be bought.
Second one is how we can make Crypto wallet inside Oculus app. We're thinking to use wallet connect, but there is no Crypto wallet in VR yet. So it will be a challenge as well.

## Deliverables
An Oculus app that anyone can buy/sell/experience VR arts in VR.

## Development Roadmap
Please check these.
https://docs.google.com/document/d/10B7ufIUrLlWGCPRSRg88PMX0ZNNkGLOzv-1eJSgJSIU/edit
https://docs.google.com/spreadsheets/d/1rGnVQUb9CfwF81B-pQh8NAhyvYdl5F0F-SZ5eNFLi2U/edit

## Total Budget Requested

$1,000,000
## Maintenance and Upgrade Plans

As it's on the Doc and the roadmap, we'll add VR game assets, VR wearables, and avatars.
# Team
CEO: Thomas Taiga Kobayashi
M&A advisor at Nihon M&A Center. ($10 billion company) The best advisor in 2018(track record of the company), the youngest
manager. 
Moved to San Francisco in 2020. 
Researcher of Thirdverse.io
Founded a community of 1,100 founders and organizing pitch events with VCs every day.
(*Past VC panelists: Multicoin Capital(Kyle), Founders Fund(Leigh), Accel Partners(Pranay), YC(DG))
Co-founded a web3 community of 4,200 members (1,000 nft minted). https://discord.gg/qVXB5pE9vN
https://www.linkedin.com/in/taigakobayashi/

CTO: Michitomo Nakahara
Team lead in Rakuten Travel (Japan’s largest online travel reservation platform) for 8 years. 
Dev Manager in India. 
Technical advisor (part time) Prototype product of VR app to view live performance for Oculus Go, 3DCG avatar performs in real time, watch together with remote ~100 participants to share the excitement, performed by professional dancers, captured by 30x motion capture cameras.
Moved to San Francisco in 2021.
https://www.linkedin.com/in/michitomo/

## Relevant Experience
CEO: 
The owner of the web 3 community with 4,300 members (1,000 nft minted in 2 months.)
Researcher at Thirdverse.io

CTO: 
Technical advisor (part time) Prototype product of VR app to view live performance for Oculus Go, 3DCG avatar performs in real time, watch together with remote ~100 participants to share the excitement, performed by professional dancers, captured by 30x motion capture cameras.

## Team code repositories

# Additional Information

**Comment by realChainLife** [comment]
Hi @TaigaTigerKobayashi thank you for your proposal. We'll review this and get back to you, on this thread, with a status update or questions.

**Comment by realChainLife** [comment]
Hi @TaigaTigerKobayashi thank you for your patience with our review process. We will not be funding this project as part of our grants program. We will however recommend your proposal for consideration through our other funding and investment channels. Please email [grants@filecoin.org](mailto:grants@filecoin.org) with the best email to reach you for next steps.
