### ISSUE TITLE
Decentralized Online Password Encryption (DOPE)

### ISSUE THREAD

**Issue by Adityarai10101** [filecoin-project/devgrants#458]
# Open Grant Proposal: `DOPE`

**Name of Project:** Decentralized Online Password Encryption

**Proposal Category:** core-dev

**Proposer:** Adityarai10101

**(Optional) Technical Sponsor:** Jonathan Victor

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes

# Project Description

Currently, almost 20% of the global Bitcoin supply is in wallets that have been “lost” due to their owners forgetting their private key or SRP (Secret Recovery Phrase). More generally, if a person wants to store multiple SRPs, private keys, or any other piece of data that requires secure storage, their current options are limited to Web 2.0 password managers such as 1Password. However, there is a risk with companies like 1Password - all their passwords are stored on a single central database, with 1Password having complete access to any of the passwords stored with them. With the advent of Web 3.0 and decentralized storage, we believe we can create a data storage system that allows data to be locally encrypted on a users computer, and then allows for this encrypted data to be sharded and uploaded to a decentralized storage network in a way, that we as a protocol, have no access to the data uploaded.
After this data is stored, we need a way for this data to be recovered. We plan to create a system of 3 steps for recovery: Verification, Recovery, and Localized Decryption. In the verification phase, a verification form is sent to a user's phone number, email, and a “social recovery” contact (can be more than one social contact for added security.). If all of these forms are approved (which confirms that the user is in fact the person requesting the data), the user is prompted to enter a 6 digit code which they were given when their data was uploaded to the network. This code works much like a Nonce in the Ethereum blockchain and is hashed with all the stored data across all of our servers to figure out which pieces of data belong to the user. After this, the user's data is still encrypted but is now locally stored on the user's device, which is when the user is prompted to enter the 8 digit key that they used when locally encrypting their data. After this final key entry, the user can see their unencrypted data, without us ever having access to this unencrypted data.
One might raise the argument that memorizing a 6 digit and 8 digit key is about as difficult as memorizing an SRP. However, the unique way in which data is handled through the DOPE protocol allows for a user to upload as much data as they want while still only having to memorize a 6-digit and 8-digit key. (For many, this includes multiple SRPs from multiple wallets.) Additionally, memorizing 6 and 8 digit keys is not too difficult, as proven by most people being able to memorize their phone password and phone number, which are 6 and 10 digits respectively.

## Value

Since the dawn of the internet and Web 2.0, the average person has never really had a secure, trust-mitigated storage service for their data - DOPE remedies this problem - not only do we supply a fully decentralized, transparent platform to store data but we also allow users to retrieve their data at any time. Our project allows for the convenient storage of everyday people's private data in a near trustless system, and in real life use cases protects sensitive personal data from entering the wrong hands. 
From a building standpoint, everything is pretty straightforward but there may be some issues convincing the everyday user to actually care about the security of their personal data. We hope to solve this problem by pitching our idea as a secure way to store your SRPs. By tying our service to a person's Crypto Assets (and by extension their money) we believe that more people may be inclined to use our platform.

## Deliverables

A fully decentralized, secure, and transparent way for users to store and retrieve private data at any time across any network. We will also deploy a project website with all of our code and whitepaper in order to maintain complete transparency. Finally, we will launch an application that runs locally on a user's device where they can encrypt their data, receive their 6-digit key, and upload their encrypted data to the DOPE network.

## Development Roadmap

**Milestone 1: Developing our Basic Infrastructure**

_Description:_ 
As a start-up project, we need to first establish the basic infrastructure and software upon which the rest of our project will be based. We hope to do (and have already begun doing) all of this development in-house (between our two team members). This development of basic infrastructure includes the development of our Hash Algorithm (based on the SHA 256 Hash), 6 Digit Key Finder (which functions like a Nonce), and Local Encryption/Decryption software. All of these will be packaged into an app so that they can be run locally on a user’s device.

_People Involved:_ Aditya Rai and Avner Lipszyc 

_Expected Hours to Complete:_ 25

_Expected Days:_ 4

_Expected Budget:_ $2,500

**Milestone 2: Onboarding Designers and Developers and Continuing Development**

_Description:_ 
After we have developed the basic code, we need to take our project one step further by developing more complex code. We will need to onboard two more software engineers to work on our storage infrastructure, connect our platform to the Filecoin Ecosystem, and develop a secure verification system that includes “social verification”. We will also onboard and work with one graphic designer to develop our project website and our user interface for our client-side application. During this phase, we will also begin running cybersecurity tests on our platform by requesting an audit from a service like QuantStamp.

_People Involved:_ Avner Lipszyc, Aditya Rai, 2 other SWE, 1 graphic designer. 

_Expected Hours to Complete:_ 60

_Expected Days:_ 20 days

_Expected Budget:_ $8,000

**Milestone 3: Developing Documentation (Whitepaper)**

_Description:_ 
A whitepaper is crucial to aid in the understanding of what we do. We want users to be clear in the work we are doing to secure their data while being completely transparent in our actions as a project. During this stage, we will also release all of our code as Open Source on Github. We will encourage community contributions to the code, with all final decisions on what is included and what is not resting in the hands of the two co-founders. To aid in our vision of complete transparency, we will also publish the results of our security audit and our whitepaper on our project website.

_People Involved:_ Avner Lipszyc, Aditya Rai, 2 other SWE, 1 graphic designer. 

_Expected Hours to Complete:_ 10

_Expected Days:_ 4

_Expected Budget:_ $2,500

**Milestone 4: Marketing/General Management**

_Description:_ 
At this point, all the fundamental parts of our software should be developed and functional. We will now begin generating marketing materials for our software to be used on platforms like Instagram. Next, we will also target our desired market of new-Web3 users by requesting to speak at events such as ETH Miami. Finally, we will aim to be integrated into crypto wallets such as Metamask or Phantom through our ability to securely store a user's SRP. 
On the general management side, we will also now begin to develop a pricing plan for the DOPE platform so that we can ensure DOPE’s continued survival through a sustainable stream of revenue.

_People Involved:_ Aditya Rai, Avner Lipszyc, 1 Graphic Designer

_Expected Hours to Complete:_ Although this is an ongoing process, we expect it will take about 40 hours to complete our marketing materials, begin advertising, and develop materials for DeFi/Web3 events.

_Expected Days:_ 2 Weeks

_Expected Budget:_ $8,000

## Total Budget Requested

Our budget request is $21,000 USD (About 1,235 Filecoin at time of writing). This money will be spent on three key sections - Development, Labor Costs for Employees, and Marketing. See our development roadmap for more detail on cost-breakdown.

## Maintenance and Upgrade Plans

Planning stage - Drawing a roadmap for the code and the technical mechanisms used in a decentralized storage and recovery service.  
Early building stage - Write SHA 256 hash algorithm, 6 Digit key finder, local encryption and decryption software.
On-board extra dev help - Building our infrastructure on the Filecoin network, verification systems, Designing a User Interface.
Launch platform 
Grow platform - Market our platform, integrate into a few crypto wallets, and begin work with layers 1s and other layer 2s. 
Continuously update platform - Update software, bring on more devs, and integrate into all crypto wallets .
Expand beyond DOPE into other ventures - begin looking to buy similar companies, expand into other Web 3.0 fields (music, gaming, entertainment), and tokenization.

# Team

## Team Members

Aditya Rai
Avner Lipszyc

## Team Member LinkedIn Profiles

LinkedIn profile → https://www.linkedin.com/in/aditya-r-6213a8189
LinkedIn profile → https://www.linkedin.com/in/avner-lipszyc-6b20461a6

## Team Website

Not developed yet - planning to develop within the next week or so!

## Relevant Experience

Both of us come from typical Web 2.0 programming backgrounds, with other interests across the board and a fervent love for tech. We have always felt building to be a passion more than a responsibility, and bring that same attitude as we begin our early journey in Web 3.0. While we haven't created any Web 3.0 specific projects yet, we have dabbled in the space from an investment standpoint and have even become super involved in an early-stage DAO. Aditya has been competitively coding for 6 years and has done extensive university-level research with a strong focus on machine learning. He also enjoys actively analyzing financial markets and investing. His strongest skill is his ability to build tech itself. Avner has been coding for a shorter amount of time but has become increasingly involved in competitive programming and cybersecurity throughout the last two years. He also enjoys finance and his charismatic personality makes him the perfect mix between technical and personable. We believe we are a team that can not only create a functional project, but expand this project to a full-scale Web 3.0 venture.

## Team code repositories

https://github.com/Adityarai10101/ExtendedKalmanFilter

# Additional Information

Both members of this project have worked on a number of nonprofit and for-profit projects in the past. In addition, with our past work on Web 2.0 development and knowledge of the fundamentals of Web 3.0 development, we are the perfect people to code this project, manage its team, and market our solution to the public at large. DOPE TO THE MOON.

**Comment by ErinOCon** [comment]
Hi @Adityarai10101 , Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by realChainLife** [comment]
Hi @Adityarai10101 thank you for this proposal, we would like to fund the work outlined here. Please email devgrants@fil.org to discuss next steps.
