### ISSUE TITLE
Next Step Microgrant: NFT sync gaming API for NEAR ecosystem

### ISSUE THREAD

**Issue by jilt** [filecoin-project/devgrants#460]
### 1. What
We build on top of an unlockable content service for the NEAR nft ecosystem and will be launched by the end of march, you can see an alpha version at [this link](https://vault.varda.vision/)

**GitHub repo**
[https://github.com/jilt/varda-vault](https://github.com/jilt/varda-vault
)
  
**Alpha version (UI has to be reviewed)**
[https://vault.varda.vision/](https://vault.varda.vision/)

### Improvements Roadmap
The project uses the web3.storage client to provide immutable DB for unlockable content, we wish to build a similar API for NFT gaming interactions enabling gaming projects to recognize NFT ownership without querying the NEAR RPC but relying on an immutable database updated by a subgraph.
 
### 3. Will the work be Open Source?
All Varda's repositories are on MIT license, the subgraph may be developed with a [contributor](https://github.com/VitalPointAI/) who may ask to publish it on a different license, but querying the subgraph will be allowed to anyone.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
I'm already a subscriber to the slack channel since months now, as I was waiting to finish the first steps and ask for a grant, I also contributed  to the last release (3.5.4) of the web3.storage client npm package [link to solved issue](https://github.com/web3-storage/web3.storage/pull/930#event-6004270435)
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions
The gaming API will be connected to the Vault unlockable upload interface (uplocker.js and storage.js in the main github repo). 
  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
 [Link to community showcase post](https://github.com/filecoin-project/community/discussions/476).

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?
  
 [Link to community showcase first post](https://github.com/filecoin-project/community/discussions/476).

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  No hackathons yet

### Additional questions:
Aready answered to all your questions!
Here is my [pull request](https://github.com/filecoin-project/community/pull/477#issue-1150705595)!!

**Comment by ErinOCon** [comment]
Hi @jilt , Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
@jilt This microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.
