### ISSUE TITLE
Next Step Microgrant: Bookverse: NFT marketplace focused on Books

### ISSUE THREAD

**Issue by PovedaAqui** [filecoin-project/devgrants#462]
### 1. What is your project? (max 100 words)

Bookverse is an NFT marketplace where users will be able to buy, collect, and resold digital books. We want to be a decentralized version of Amazon Kindle and help to onboard authors, publishers and lectors to web3.

We've chosen ipfs and filecoin in order to guarantee the availability, disponibility and decentralization of the metadata of every book sold on the platform.

https://github.com/PovedaAqui/alpha-frontend
https://github.com/PovedaAqui/alpha-backend  

bookversexyz.com. Demo is not yet available.

### 2. How are you planning to improve this project? (max 200 words)

While I'm still working in the frontend and backend, I want to hire a DAO based in Barcelona specialising in UI/UX design, led by women, deepwork.studio, in order to get the best user experience and user interface design to disrupt the eBooks market. After that, the project will be deployed on testnet, looking for users validations. Then, I'll start working to launch Bookverse on mainnet using an Ethereum layer 2 solution.

### 3. Will the work be Open Source?

Bookverse will be completely open-source, with MIT license for code.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes.
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes.

### 6. Links and submissions

  
* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
   https://github.com/PovedaAqui/community/blob/patch-1/templates/project-submission-template.md

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)? Yes.
  
   https://github.com/filecoin-project/community/discussions/479

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Luis Poveda, founder and CEO.
Luis.poveda9321@gmail.com
Github.com/povedaaqui

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
@PovedaAqui , Thank you for submitting this proposal. Before proceeding, we would like to learn about the need you have identified. Can you define the specific user problem you intend to address?

**Comment by PovedaAqui** [comment]
Thanks, @ErinOCon. This is a problem I have and then, I saw an opportunity here. Now, I'm trying to build a user interface that not just crypto native people but the more traditional sectors could use and enjoy.

Some of the problems I've saw and how could be answering with Bookverse:

For users:

You’ll be able to resell your eBooks or share them for free with other users.
You could get limited, collectable and rare editions of your favourite books.
You could get an autographed book from your favourite author, backed by blockchain technology.
Your favourite book could be your key to DeFi, using your book as collateral.

For authors and creators:

You’ll get a considerable major income for any book you sell.
You’ll get a benefit for any book that is resold, forever, backed by public and audited smart contracts.
You’ll be able to shorten the distance between you and your community.
You’ll be able to launch rare or special editions of your books in seconds.
New ways to fund your incoming launches, even before they are written.

I posted an article related to it in [mirror](https://mirror.xyz/luispoveda.eth/dZoEaqpBt94HL8RAOFSRtK4dZzv1rVRv8RQjzXpRlTQ).

**Comment by ErinOCon** [comment]
@PovedaAqui, Thank you for the provided information! It looks like you are in the early stages for this project. Joining a hackathon could be a great next step! Have you checked out [hackathons.filecoin.io](http://hackathons.filecoin.io/)? 

Once the project is further along, a new issue can be opened to request funding. We would be excited to hear of your progress!
