### ISSUE TITLE
Flink SDK - A data provider offers Chainlink Oracle service for Filecoin Network 

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/devgrants#463]
### 1. What is your project? (max 100 words)
This a SDK for the[ filecoin and Chinalink data bounty project](https://github.com/filecoin-project/devgrants/pull/290/files). The  bounty implementation provide a data aggregator service for user check the data onchain information. This SDK is providing a  JavaScript client to flink data provider service. 

https://github.com/filswan/flink
  

https://calibration-mcs.filswan.com

### 2. How are you planning to improve this project? (max 200 words)
We are planing release the js client for community use it to interact with filnk service as an js client. It provides the following function:
* upload file to Filswan IPFS gate way
* Make payment to swan filecoin storage gate way
* Get status from filecoin
* Mint asset as NFT
* return list of file uploaded
* return file by cid

### 3. Will the work be Open Source?

MIT

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes
### 5. Does your proposal comply with our Community Code of Conduct?

Yes
### 6. Links and submissions

* Have you submitted to the Filecoin Community Showcase ([instructions](https://github.com/filecoin-project/community#showcase-your-project))?
   Yes

* Have you created a thread introducing your project in the community discussion board's [ Project Showcase category](https://github.com/filecoin-project/community/discussions/categories/project-showcase)?

 [Flink](https://github.com/filecoin-project/community/discussions/480)

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
[RFP : chainlink and filecoin data bounties ]( https://github.com/filecoin-project/devgrants/pull/290)

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project

- Yiming Liu	Smart Contract Developer GitHub: @liushmh
- Rick Zhao	    Blockchain Developer GitHub: @rykci

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
      ETHGlobal NFTHack

  * Please link to your hackathon submission
https://showcase.ethglobal.com/hackfs2021/filecoin-payment-bridge

**Comment by flyworker** [comment]
https://github.com/filswan/python-mcs-sdk
https://github.com/filswan/js-mcs-sdk
Is ready

**Comment by jenks-guo-filecoin** [comment]
Hi @flyworker, in the grant submission, the scope is to create SDKs for [Flink](https://docs.filswan.com/multichain.storage/overview/flink). However the link you submitted here are python & JS SDKs for multichain storage. Could you clarify on this? Has the product changed or the scope of the grant changed?

**Comment by jenks-guo-filecoin** [comment]
Hi @flyworker , thanks for providing more explanation of your products over the phone. I have reviewed the code again, the SDK is made for Multichain Storage which a subset of the functions fulfils the original grant's scope: providing ability to query for deal information via chainlink oracles. 

We can consider this grant delivered. @ErinOCon
