### ISSUE TITLE
Open Grant Application: FileDAG Storage

### ISSUE THREAD

**Issue by laurarenpanda** [filecoin-project/devgrants#470]
# Open Grant Proposal: `FileDAG Storage`

**Name of Project:** FileDAG Storage

**Proposal Category:** `app-dev`

**Proposer:** `@laurarenpanda`

**(Optional) Technical Sponsor:** `None`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:**  `Yes`

# Project Description

FileDAG Storage is a distributed storage service built on the IPFS technology stack, focusing more on data management, reliability, availability, fault tolerance, and clustering storage nodes.

The minimum storage unit of FileDAG Storage is DAG, which is the data block. When we organize files or objects in the Merkle-DAG structure, a part of multiple files or objects may share some data blocks. This method has obvious benefits, such as reducing data redundancy, especially for multi-version systems, and saving bandwidth on data transmissions through the network. However, it also has the disadvantage that data management will become more complex and meet some foreseeable challenges, including: 

- The management module of files or objects needs to be abstracted based on Merkle-DAG.
- It's nearly impossible to delete files or objects directly, only through garbage collection to release data blocks that don't need anymore.

Using a multi-user mode to store data resources would become even more complicated since the current open-sourced implementation of IPFS protocol does not support multi-user usage. Supporting multi-users and maintaining a larger DAG pool will expand the advantages of reducing data redundancy and saving network bandwidth. However, it will also increase the difficulty of data management at the same time.

For commercial decentralized storage services, it's necessary to ensure data reliability, availability, fault tolerance, and meet the requirements of different application scenarios. FileDAG Storage aims to provide a solution to these challenges, including:

- learn from object storage services about how to manage data
- process the release of data blocks by reference counting
- use distributed storage nodes to provide data availability and use erasure coding technology to improve data reliability and fault tolerance

## Value

For storing a large capacity of data onto the Filecoin network, especially the PiB-scale data, it's unavoidable to use the IPFS technology stack and build related tools, services, and infrastructure. The original IPFS implementation can solve the problem of how individual users can use IPFS for content distribution and data sharing. However, the data capacity was relatively small. Using IPFS to store and distribute massive data will meet many challenges that it's not limited to those mentioned before. FileDAG Storage aims to provide technical solutions to support data management, preprocess, and transmission for clients and storage providers and high-efficient data retrieval and availability for users.

With our years' experience on IPFS/Filecoin/Blockchain and the joint efforts of team members, we believe that FileDAG Storage could achieve its vision and intended plan and contribute to the long-term development of the Filecoin ecosystem.

## Deliverables

1. DAG Node:
   - provide the underlying storage module, responsible for the storage and release of data blocks, similar to block store

2. DAG Pool: 

   - a virtual data block composed of distributed DAG nodes

   - support the usage of multi-user systems and provide authentication methods

   - implement storage nodes clustering and provide data fault-tolerance solutions

   - be responsible for the reference records of data blocks and providing an interruptible garbage collection mechanism

3. Object Store:

   - the object storage service abstraction layer based on the DAG pool

   - be responsible for providing partially S3 compatible API

4. Control Panel:
   - a visual management UI

#### **Milestone 1**

**Goal:** build fundamental data structure and the overall architecture of this project

**Description:** 

- Development of single DAG Node: 

	- supports API of the block store
  - providers basic storage service for DAG Pool

- DAG Pool: 

	- multi-user access
  - authentication mechanism

- Object store:

	- implements basic data structure, such as user, region, bucket, and object
  - implements API of user authentication

**Resource:**

| Role | Rate/Hr | HC | Man-Hour | Workday | Price |
| ---- | :--- | ---- | :--- | :--: | ---- |
| Back-end Engineer | $50 | 3 | 720 hours | 30 days | $36,000 |
| Project Manager | $30 | 1 | 8 hours | 1 day | $240 |

Funding: $36,240

#### **Millstone 2**

**Goal:** implement data management

**Description:** 

- DAG Pool:

	- reference records of data blocks
  - strategy of data pin
  - interruptible garbage collection mechanism of DAG Pool

- Object store:

	- API of bucket related operations
  - API of object manipulation
  - API of permission operation

**Resource:**

| Role              | Rate/Hr | HC   | Man-Hour  | Workday | Price   |
| ----------------- | :------ | ---- | :-------- | :-----: | ------- |
| Back-end Engineer | $50     | 3    | 720 hours | 30 days | $36,000 |
| Project Manager   | $30     | 1    | 8 hours   |  1 day  | $240    |

Funding: $36,240

#### **Milestone 3**

**Goal:** realize clustered DAG Node and development of data fault tolerance

**Description:** 

- DAG Node:

	- develops data fault tolerance based on Reed-Solomon Erasure Code

- DAG Pool:

	- organizes multiple DAG Nodes to build a storage cluster based on libp2p and Redis Hash Slots
  - provides health report of storage nodes and status of global consistency
  - supports dynamic expansion of storage nodes
  - supports dynamic scaling of storage nodes

**Resource:**

| Role              | Rate/Hr | HC   | Man-Hour  | Workday | Price   |
| ----------------- | :------ | ---- | :-------- | :-----: | ------- |
| Back-end Engineer | $50     | 3    | 720 hours | 30 days | $36,000 |
| Project Manager   | $30     | 1    | 8 hours   |  1 day  | $240    |

Funding: $36,240

#### **Milestone 4**

**Goal:** develop the Control Panel of FileDAG Storage

**Description:** 

- Dashboard of storage pool statistics overview

- User interface

- Object Store interface:

	- users
  - user access operations
  - bucket operations
  - permission setting

**Resource:**

| Role               | Rate/Hr | HC   | Man-Hour  | Workday | Price  |
| ------------------ | :------ | ---- | :-------- | :-----: | ------ |
| Back-end Engineer  | $50     | 1    | 160 hours | 20 days | $8,000 |
| Front-end Engineer | $50     | 1    | 160 hours | 20 days | $8,000 |
| UI Designer        | $30     | 1    | 80 hours  | 10 days | $2,400 |
| Product Manager    | $30     | 1    | 80 hours  | 10 day  | $2,400 |
| Project Manager    | $30     | 1    | 8 hours   |  1 day  | $240   |

Funding: $21,040

#### **Milestone 5**

**Goal:** connect with IPFS

**Description:** 

- implements Satellite Nodes connected to the IPFS network in the outer layer of the DAG Pool
- provides lightweight IPFS gateway services according to user customization

**Resource:**

| Role              | Rate/Hr | HC   | Man-Hour  | Workday | Price   |
| ----------------- | :------ | ---- | :-------- | :-----: | ------- |
| Back-end Engineer | $50     | 2    | 480 hours | 30 days | $24,000 |
| Project Manager   | $30     | 1    | 8 hours   |  1 day  | $240    |

Funding: $24,240

## Total Budget Requested

- Estimated completion time: 140 workdays (~7 months)
- Funding for 5 milestones: $154,000
- Test and maintenance: $6,000 (2 Engineer + 1 PM) 

**Total budget requested:** $160,000

## Maintenance and Upgrade Plans

Maintenance and upgrade plans provided by FileDrive Labs will include:

- maintenance and bug fixing of this project to ensure that all bugs could be addressed 
- upgrade relevant documents as this project progresses
- identify ongoing ways to improve this project and build those features

# Team

#### FileDrive Labs:

- Felix Li (Founder, CTO, Full-stack Engineering)
- Laura Ren (Co-founder, PM)
- Eric Qian (Back-end Engineering)
- Abu Li (Front-end Engineering)
- Dean Wang (Back-end Engineering)
- MJ Han (Back-end Engineering)
- Romee Zhang (UI Designer)
- Sherry Yang (Operation Director)

## Team Member LinkedIn Profiles

- Felix Li: https://www.linkedin.com/in/felixlee20190908/
- Laura Ren: https://www.linkedin.com/in/laura-ren-panda/
- Eric Qian: https://www.linkedin.com/in/eric-qian-455141129/
- Abu Li: https://www.linkedin.cn/injobs/in/jian-tian-560bb1232
- Deanls Wang: https://www.linkedin.com/in/%E9%B9%8F%E5%85%89-%E7%8E%8B-b06b24232/
- MJ Han: https://www.linkedin.cn/injobs/in/%E6%98%8E%E5%86%9B-%E9%9F%A9-11200b233
- Romee Zhang: https://www.linkedin.cn/injobs/in/%E5%87%8C%E5%AB%A3-%E5%BC%A0-048010233
- Sherry Yang: https://www.linkedin.cn/injobs/in/sherry-yang-92b010233

## Team Website

https://filedrive.io/

## Relevant Experience

FileDrive Labs is a technical team actively building tools, applications, and infrastructure in Web3 and focuses on solutions for distributed storage & developments based on IPFS/Filecoin. We consist of several qualified engineers with more than 10-year development experience in the Block-chain Industry.

In the past years, we have gathered rich technical development experience by participating in the Slingshot Competition and several Hackathons and stored over 10 PiB data on the Feilcoin network through self-developed tools and platforms, the most important, cooperation with numbers of storage providers. At the same time of high-efficient storage, we also tried our best to maintain data availability and integrity by developing related tools if necessary.

A series of following products we're working on:

- **FileDrive Datasets:** a platform to effectively connect the huge storage market that Filecoin has built with publishers of public datasets.
- **FileDAG:** a decentralized storage solution based on IPFS that provides high-quality and efficient IPFS Pin Service and customized network service based on customer requirements.
- **Filplus.info:** the first visual dashboard for the Filecoin Plus project, recording relevant real-time data of each DataCap allocation and verified deal transactions on Filecoin through monitoring both on-chain and off-chain information.
- **Go-Graphsplit:** a tool for splitting a large dataset into graph slices to make deals in the Filecoin Network.
- **Go-DS-Cluster:** the storage layer and one of the most significant parts of FileDrive's product system. It aims to gather distributed key-value datastores to become a cluster to increase the data split function and improve data management.

## Team code repositories

https://github.com/filedrive-team

**Comment by ErinOCon** [comment]
Hi @laurarenpanda, we would like to fund the outlined work! Please email [devgrants@fil.org](mailto:devgrants@fil.org) to discuss next steps.
