### ISSUE TITLE
eVerse - The Future of Social Entertainment is on the Blockchain

### ISSUE THREAD

**Issue by MyEVerse** [filecoin-project/devgrants#474]
# Open Grant Proposal: `Project Title`

**Name of Project:**

The eVerse.tv Network

**Proposal Category:** Choose one of `core-dev`, `app-dev`, `devtools-libraries`, `technical-design`, `docs`

app-dev

**Proposer:** `replace with your GitHub username`

https://github.com/eVerseOrg

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

https://gist.github.com/pooja/

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Please respond with either "Yes" or "No"

Yes

# Project Description

The eVerse web3 platform will create opportunities for multimedia content applications to be built for many atomic networks/audiences. The eVerse team believes that, in order for web3/crypto to gain widespread adoption, consumer-facing applications need to give participants the benefits of blockchain technology without such consumers needing to understand the underlying details or architecture. We believe our protocols can enable a wide range of these applications. Our first reference application — (https://everse.tv/) — is a landscape video social application and a first use case of how the platform can be used. We are building for the long term, with elements of our development roadmap looking out for years to come.

The eVerse media and commerce infrastructure is designed to enable anyone who has or can reach an atomic network to create multimedia-based applications and/or websites with native web3/crypto. The eVerse protocols create a framework to allow future social-media and commerce applications, embodying creator-to-platform agreements, transparent smart contract payouts, and multiple monetization pathways. They also offer community members incentives to participate in the establishment and enforcement of community standards, including voting rights to evolve such community standards over time. Creators will be rewarded for publishing popular creative works while retaining provenance and ownership. The protocols provide a framework for content distribution and monetization via the eVerse token, which manifests as a vehicle for a robust economy for creators, advertisers, licensees, and fans. The token economy offers incentives to all parties to participate and earn on the platform.

The protocols will also provide a framework for content distribution via vibrant user interfaces comprising multiple forms of media and monetization via an embedded marketplace, all empowered by the eVerse token — a currency for intellectual property holders, advertisers, and users/fans. Lastly, the token economy, as currently contemplated, will offer incentives to all parties to participate and earn tokens on eVerse and other eVerse powered platforms for value-added activities such as content moderation, community engagement, and revenue generation (e.g., advertising revenue, donations, subscriptions, merchandise sales). The (https://everse.tv/) network, which is being built upon these protocols, is a first proof point and represents a short-form video platform to demonstrate the power and efficacy of the protocols.

The first application built on top of the platform and protocols –- the everse.tv network – is a short-form video platform, appealing to the immense gamer community, and designed to help usher in a new era of creator asset ownership, platform transparency, brand building, and monetization. Combining a range of powerful web3 protocols with a dynamic web2 user interface, the everse.tv application addresses many of the problems and inherent limitations encountered by creators and users on existing social media and commerce platforms.

## Value

For those of you who have used the app or have seen the demos, it has a novel and compelling design.  It's a very approachable app. We have large atomic networks that are ready to adopt as soon as we finish building.  Per the whitepaper, we're planning to use IPFS as our permanent long-term storage location, and give creators ownership rights they don't have on other platforms.  We are looking forward to video streaming options that are presently on the Filecoin development timeline as we are moving from the CDN in use by the closed beta app and we can certainly add value by adoption and intensive testing.

## Deliverables

IPFS storage of eVerse assets, references in NFT metadata
Then, ideally, a mechanism to stream video chunks via IPFS per the discussion with Pooja Shah

## Development Roadmap

The eVerse team is seeking a strategic investment with the Filecoin project that provides capital, expertise, collaboration, engineering, and marketing support, in addition to opportunities to partner with other Filecoin blockchain projects.

Timeline
Q3 2022
2,000 creators onboarded within the 10,000-user capped TestFlight environment
eVerse.tv network feature expansion (sharing, notifications, and search)
Expansion of engineering team

Q4 2022
Launch of token
eVerse.tv feature expansion
Open beta release (by invite only)

Metrics for Success:
Public token offering
Stretch Goal: Meaningful waitlist on App Store upon public release

## Total Budget Requested

We have three engineers on our dev team and plan to onboard two more this month.  We're seeking a budget for building on Filecoin.  The attention the eVerse project will generate will clearly benefit the Filecoin project.  Jonathan Victor brought us here and it's up to the Filecoin team to determine how much value we can add as we plan to onboard millions of users in the next 3-4 years.

We're pleased to announce that Harmony has made a $550k investment in the eVerse project. We hope to get support from FileCoin as well so we can get started on our on-chain video NFT storage.  Jonathan is helping us navigate that process.

Our project is noble in that it is designed to provide creators with a new deal, i.e. to dramatically empower them and give them several kinds of monetization opportunities.  The project addresses DMCA strike issues and community standards management problems that are not solved by state-of-the-art web2 social networks.  See our whitepaper for details.

https://docs.google.com/document/d/1F0GKk6_ywdg3fw-VwhLvUXEUmN2ODYxloKOlkqNhrU0

## Maintenance and Upgrade Plans

# Team

## Team Members

Benji Freedman, Founder — Benji is a former professional gamer, having become one of the top-200 Fortnite players in the US while still in high school. Throughout his professional gaming career, he saw firsthand the challenges faced by the creator community which drove his vision for a new solution, eVerse. He is the visionary and chief architect of the product and business model.

David Wertheimer, CEO - David has been a groundbreaking entrepreneur and industry leader in streaming and digital media. He most recently served as President of Fox Digital, which he oversaw more than 40 apps, and a social footprint of over 350 million users. Before joining Fox, he served as the first President of Paramount Digital. Prior to that, he worked under Steve Jobs at NeXT and at Oracle.

Joel Freedman, Founder — Joel is an entrepreneur who has launched several successful startup companies; most recently a hospital business which he built from a startup to more than $1 billion in net revenue in less than ten years. He has served on several Boards, including at Harvard Medical School and USC; served as Chairman of Harvard’s Healthcare Markets and Regularity Lab; and received a Lifetime Achievement Award from the Congressional Black Caucus and National Minority Quality Forum for his work on healthcare disparities.

Felix Baum, CTO — Felix has extensive experience building blockchain, social media and streaming technology companies, including an Ethereum backed, investor management and fundraising platform (acquired in 2021). He helped develop the E language and a social network featuring a token economy and smart contracts. He subsequently joined Knowledge Networks, where his analytics technologies were featured in NBC’s “The West Wing” and NYT Magazine. His work at MobiTV as a principal engineer helped launch the streaming media industry and garnered an Emmy Engineering Award for Outstanding Achievement in Engineering Development. He spent a decade at Adobe Inc. across numerous roles as a senior engineer.

Kyle Schmidt, Strategy — Kyle’s career has focused on M&A, finance, and capital structuring, in addition to operational and strategic roles, including turnaround and growth experience across industries and company stages. Kyle has spent over five years working directly for Joel across multiple business ventures. Prior to that, he held finance, operational, and business development roles at privately held businesses, including startups. Lastly, as a Consultant at L.E.K., Kyle worked on entertainment and media strategy for clients across the content delivery and production spectrum.

Mike Mayer, Product — Mike is an experienced product leader with strong operational, engineering, and team leadership experience, serving in various roles such as Chief Product Officer and Head of Product. Passionate about leading early-stage startups to product/market fit, he leverages deep expertise developed from working in both consumer and B2B verticals. He has been in numerous product roles and has realized two exits and several advanced venture rounds. Most recently he has served as Head of Product, leading his team to a series A and triple-digit revenue growth. He started his career in management consulting and corporate M&A before pivoting to building startups.

Dan Mayernick, Finance & Operations — Dan has broad experience in his career spanning from private equity, operating and raising capital at start-ups, as well as finance and operational roles. He has worked with Joel and Kyle directly for multiple years prior to working on eVerse. Dan brings a wealth of operational, financial, and transactional expertise to the Company.

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/wertheimer
https://www.linkedin.com/in/benji-freedman-133339206/
https://www.linkedin.com/in/felix-baum-66a5441/

## Team Website

https://www.everse.tv/

## Relevant Experience

David Wertheimer is a technology leader/executive with experience running new and existing businesses in start-up and publicly traded organizations. David's strengths stem from his deep technical background combined with widespread experience in management and operations.

Benji was one of the top Fortnite players in the world, it's his experience as a gamer and a creator that led him to envision the eVerse.tv project.

Felix Baum is writing this application now, and he's a bit shy about talking about himself but he is an experienced technology leader and an Emmy award winner.  He has built multiple technology companies in the blockchain, social media, and video streaming categories and is arguably quite a lot of fun to talk to.

## Team code repositories

https://github.com/eVerseOrg
https://github.com/mohammadreza-ashouri

# Additional Information

We have potential reach into Central Africa and Indonesia which I described to Jonathan, in our call.  The World Food Bank is seeking a partner to expand their media reach as they continue on their global quest to eradicate poverty.  An integrated blockchain and media application have clear educational and financial benefits for their organization, which produces television shows watched by 12M weekly viewers from Kenya to Nigeria.  They're expanding their reach into Indonesia next.  We'll need a storage and streaming partner to enable this kind of reach.

**Comment by ErinOCon** [comment]
Hi @MyEVerse, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
Hi @MyEVerse, I am closing this issue as the review was completed a while back over email. Please feel welcome to be in touch with any questions at grants@fil.org.

**Comment by neonflux-io** [comment]
Hi @MyEVerse, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by neonflux-io** [comment]
Hi @MyEVerse, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by neonflux-io** [comment]
Hi @MyEVerse, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.
