### ISSUE TITLE
Next Step Microgrant: FonoRoot

### ISSUE THREAD

**Issue by ottpeter** [filecoin-project/devgrants#477]
### 1. What is your project? (max 100 words)
An audio NFT with a tree-like minting process. Currently the front-end is 100% on IPFS (pinned on Infura, Crust, Pinata), for the image and music upload we use Crust.

[https://github.com/ottpeter/FonoRoot](https://github.com/ottpeter/FonoRoot)  
  
[Demo Video](https://www.youtube.com/watch?v=MQbYUI2n19s)  
Live version: [rarevandal.com](http://rarevandal.com)

### 2. How are you planning to improve this project? (max 200 words)
There are some bugs we need to fix and we need some small improvements in the smart contract. The problem with the IPFS front-end is that it is very slow, probably because of the gateway. We are planning to serve the front-end from a central server in the next release, but with the option to switch to IPFS version if the user has native IPFS support. The idea is that the site would keep on functioning from IPFS even if the server is down, it will be possible to buy NFTs from the IPFS version, but the new NFT creation (admin page) will not work, because we will move the pinning to the server. The main thing that we want to achieve is that it is stable, currently the load time is unreliable.
 
### 3. Will the work be Open Source?
We are using MIT license

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes
  
### Hackathon info:
The name of the hackathon was MetaBUILD
[https://devpost.com/software/troaco-audio-nft-drop-by-rare-vandal](https://devpost.com/software/troaco-audio-nft-drop-by-rare-vandal)

### Team Members
__Designer__: Lena ([website](https://www.lenamarakova.com/), [LinkedIn](https://www.linkedin.com/in/elenamarakova/))  
__Idea and Project Owner__: Vandal ([website](https://linktr.ee/vandigital), [Twitter](https://twitter.com/vandigital), [LinkedIn](https://www.linkedin.com/in/vandigital/))  
__Developer:__ Peter ([GitHub](https://github.com/ottpeter), [Twitter](https://twitter.com/ottpeter2/), [LinkedIn](https://www.linkedin.com/in/p%C3%A9ter-o-b4a20218a/))

**Comment by ErinOCon** [comment]
Hi @ottpeter, this microgrant has been approved! Look out for an email to submit payment details. Let's use your existing Community Discussion thread for updates.

For your work building on IPFS, we recommend [NFT.Storage](https://nft.storage/) as a resource!

**Comment by ottpeter** [comment]
ottpeter at tuta dot io




Mar 18, 2022, 19:03 by ***@***.***:

**Comment by ErinOCon** [comment]
Many thanks, @ottpeter! We have reached out by email to collect grant payment details.

**Comment by ottpeter** [comment]
Thank you!

**Comment by ottpeter** [comment]
__STATUS UPDATE__ We have deployed daorecords.io/, which was forked from FonoRoot. The ipfs.io gateway is not fast enough for the music, so we are using nft.storage, although my opinion is that this is a form of centralization. 
We are using a HashRouter, so the whole site can be mirrored to IPFS.

**Comment by ottpeter** [comment]
__STATUS UPDATE__ We've done the second drop for daorecords.io. The loading of the image and audio is sometimes slow (image coming from ipfs.io, audio coming from nft.storage). Probably I'll write an API route that will fetch the image and audio from our server, which is running an IPFS node.

**Comment by ottpeter** [comment]
__STATUS UPDATE__ I tried to upload the _dist_ folder to IPFS, it works. 
https://ipfs.io/ipfs/QmaR84hTMxa1ZsofFWhqFAfxo6t8WQAmfryou3N2eeaqTK/
