### ISSUE TITLE
Update grants template to explain the category types

### ISSUE THREAD

**Issue by autonome** [filecoin-project/devgrants#478]
The open grant issue template has this section:

> **Proposal Category:** Choose one of `core-dev`, `app-dev`, `devtools-libraries`, `technical-design`, `docs`

But there's no explanation of those.

Should either add inline explanation in a comment, or add a link, eg "Learn what these categories are here: {URL}".

**Comment by realChainLife** [comment]
Closing the loop here @autonome we made these changes!
