### ISSUE TITLE
BlockSpace

### ISSUE THREAD

**Issue by chaalpritam** [filecoin-project/devgrants#480]
# Open Grant Proposal: `Project Title`

**Name of Project:** BlockSpace

**Proposal Category:** `app-dev`,  `technical-design`

**Proposer:** `@chaalpritam`

**(Optional) Technical Sponsor:** `Discussed this with Longfei Wang during pitching session at Mars Asia Hackathon 2021`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** `Yes`

# Project Description

BlockSpace is a decentralized storage platform that runs on top of a filecoin blockchain. It allow users to store and share files like google drive/photos, also user can rent their storage space to act as a storage provider in a easy web and mobile application interface. BlockSpace is both Web and Mobile application. It runs on top of filecoin blockchain so the data is decentralized and gives you full control over your data, which stands apart from traditional storage system where an organization has the control. The data uploaded in BlockSpace is encrypted, only the user can decrypt it.

We started building this platform on top of ipfs for Mars Asia Hackathon 2021 and won the first prize & now we planning to build this on top of filecoin.

Here is the [BlockSpace Explainer Video](https://youtu.be/8S9WbIECULE) which we made for Hackathon.

## Value

* This project will make the adoption of decentralized storage more easier for customer and storage provider.
* Seemless interface like google photos/drive both in web and mobile is the key to adoption. So we are focussing on building those things first, which will make filecoin adoption to larger people.
* As any user can become a storage provider, it makes user to become the storage provider easily.

## Deliverables

* UI/UX of Web Dashboard, Androind and IOS App.
* BlockSpace Web app to easily upload and download files to storage on top of filecoin.
* Androind and IOS App for accessing the storage.
* Easy to access dashboard for storage providers to easily integrate their storage space with  filecoin.
* Filecoin fully working integration with the blockspace platform.

## Development Roadmap

1) ****Milestone 1 - Design UI/UX****
*  **Web Application** 
 BlockSpace Branding
 BlockSpace LandingPage
 User Onboarding
 User Dashboard
 Storage Purchase
 Creating Folder & Files
 Data Uploading
 Viewing Data
 Storage Provider Dashboard

* **Mobile Application**
User Dashboard
Creating Folder
Data Uploading
Viewing Data

Milestone budget: $20,000
Timeline: 30 days (Apr 01 - Apr 30)

2. **Milestone 2 - Backend/Frontend & Mobile App**
* **Backend**
Encrypting and Decrypting data
CRUD operations
Dashboard operations
 
* **Frontend**
Whole Dashboard design which we mentioned above 

* **Mobile**
Whole Mobile App for IOS & Android design which we mentioned above

Milestone budget: $40,000
Timeline: 30 days (May 02 - May 31)

3. **Milestone 3 - Deployment & Filecoin Integration**
* **Backend**
Integration of IPFS/Filecoin
User onboarding operations
Storage Purchase operations
Filecoin integration
Server hosting

* **Deployment**
Web App
Android App
IOS App
Backend 
FIlecoin Deployment

Milestone budget: $40,000 
Timeline: 30 days (June 1 - June 30)

## Total Budget Requested

$100k

## Maintenance and Upgrade Plans

* Our team plan to continue and maintain this project, as long as the project is funded.
* Once completing this milestone we planning to work on lotus GUI miner for storage space providers.

# Team

## Team Website
[BlockSpace Team Website](http://www.blockbase.team/)

[Chaal Pritam](https://github.com/chaalpritam) - UI Design (3 Years) & FullStack JS & Blockchain Engineer (8 Years)
[Vijjay](https://www.linkedin.com/in/vijjay-vidharthrae-45023b40) -> Product Designer (8 Years)
[Pavithranath](https://github.com/pavinane) - Frontend Engineer (3 Years)
[Sathish Kumar MSK](https://github.com/sathishkumarmsk) - Backend Engineer (2 Years)
[Yoga Lakshmi](https://github.com/IamYogalakshmi) - UI/UX & Frontend Engineer (2 Years)
[Ramees Ahmed](https://github.com/IAmBatMan-Ramees) - FullStack Engineer (3 Years)
[Akshaya](https://github.com/akshayacode) - Blockchain & Solidity Engineer (2 Years)
[Sathish Kumar](https://github.com/sathishshah) - Frontend Engineer (3 Years)

## Team code repositories

https://github.com/blockbasedev/blockspace-web

https://github.com/blockbasedev/blockspace-server

# Additional Information

We won the first prize for this idea for Mars Asia Hackathon 2021

**Comment by ErinOCon** [comment]
Hi @chaalpritam, thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by realChainLife** [comment]
Hello @chaalpritam thank you for this proposal. We will not fund the work as you've outlined it here based on the following considerations: 

- We were unable to identify a clearly described and defined differentiating factor, and path to sustainability? 
- Community traction is pretty low, a clear definition of a user need could help with user targeting. 

We'd be happy to reconsider a reworked proposal for partial funding with, proof of community traction prior to additional funding. If you have any questions in the meantime you can reach us via email at grants@filecoin.org or via filecoin.io/slack #grants-help channel.
