### ISSUE TITLE
Next Step Microgrant: NiftyGuilds

### ISSUE THREAD

**Issue by therealharpaljadeja** [filecoin-project/devgrants#483]
### 1. What is your project? (max 100 words)
A web3 based NFT gated group chat platform with blockchain level security.

**Github Repo**
https://github.com/therealharpaljadeja/niftyguilds 

**Website**
https://niftyguilds.vercel.app/

### 2. How are you planning to improve this project? (max 200 words)
- Currently, NiftyGuilds only lets people chat via text. I want to enable users to upload image and share documents which will leverage Filecoin technologies like web3.storage for storing images and documents. 
- Currently, NiftyGuilds doesn't store any user related information I directly get address and NFTs in the wallet using APIs and thus no need to store user information. However, I want to enable users to edit their profile and own their data which is why I want to use Tableland built by Textile team for giving users ownership of their profile data. 
- I want also want to do Livepeer Integration for livestreaming.
 
### 3. Will the work be Open Source?
Yes, all of the work will be Open Source under MIT license.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes, we will share weekly updates in Github Discussion thread.

### 5. Does your proposal comply with our Community Code of Conduct?
Yes.

### 6. Links and submissions

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  ETHGlobal BuildQuest (Protocol Labs 1st place) - https://showcase.ethglobal.com/buildquest/niftyguilds-j058z

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

**Harpalsinh Jadeja**
Email - harpaljadeja.informal@gmail.com
Github - threalharpaljadeja
Role - Developer

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  
  _ETHGlobal Buildquest_
  * Please link to your hackathon submission
  
    https://showcase.ethglobal.com/buildquest/niftyguilds-j058z

**Comment by ErinOCon** [comment]
Hi @therealharpaljadeja, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
Hi @therealharpaljadeja, This microgrant has been approved! Look out for an email to submit payment details.
