### ISSUE TITLE
FVM testnet/mainnet APIs on Chainstack

### ISSUE THREAD

**Issue by easeev** [filecoin-project/devgrants#484]
# Open Grant Proposal

**Name of Project:** `FVM testnet/mainnet APIs on Chainstack`

**Proposal Category:** `integration-adoption`

**Proposer:** [Eugene Aseev](https://github.com/easeev)

**Technical Sponsor:** [Dragan Zurzin](https://github.com/BlocksOnAChain) / [Eva Shon](https://github.com/eshon)

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Partially

# Project Description

- Remote Filecoin JSON-RPC API endpoints for the “Wallaby” Testnet targeted toward FVM developers
- Similar endpoints for Filecoin Mainnet
- Docs on how to connect are added to the Chainstack website
- Support for all read-only calls + MPoolPush (equivalent of `eth_sendRawTransaction`)
- [Lotus Lite](https://lotus.filecoin.io/lotus/install/lotus-lite/) nodes are also able to connect to the RPC endpoints via `FULLNODE_API_INFO=wss://filecoin_api_url/ ./lotus daemon --lite`

## Value

Developers to have the least friction possible when starting to develop for the FVM.

### Milestone 1 (est. Sep 2022)

Chainstack will provide RPC endpoints to the FVM Wallaby testnet for use by FVM early builders without having to spin up a node. Any testnet resets will be followed by Chainstack and endpoints updated accordingly.

### Milestone 2 (est. Nov 2022)

Chainstack will additionally provide RPC endpoints to Filecoin mainnet for use by developers without having to spin up a node. Any mainnet upgrades will be followed by Chainstack and endpoints updated accordingly.

## Total Budget Requested

Proposed schedule is the following:

- $15k pre-payment on Jul 1
- $20k payment on Sep 1 given testnet API powered by Chainstack is launched
- $20k payment on Nov 1 given mainnet API powered by Chainstack is launched
- $20k payment on Apr 1 2023
- $25k payment on Jul 1, 2023

Endpoints are hosted for 1 year from start date.

Total Budget $100K

### Maintenance

The terms of this grant will be 12 months so that the APIs built, along with the relevant engineering resources are covered by the grant until 1 Jul 2023.

# Team

## Team Website

https://chainstack.com

## Relevant Experience

Chainstack is a node as a service provider specialist, our team believes that we are an ideal fit for the FVM node provider role. As one of the most reliable providers of nodes in the industry, we believe that Chainstack can provide everything developers need to build and scale their blockchain solutions.

## Team code repositories

https://github.com/chainstack

**Comment by BlocksOnAChain** [comment]
@realChainLife this looks good to me, for the first stage of our collaboration.

**Comment by easeev** [comment]
The grant concluded and was not renewed hence the services were sunset: https://twitter.com/ChainstackHQ/status/1709585703103828452
