### ISSUE TITLE
Next Step Microgrant: <DBookMarket>

### ISSUE THREAD

**Issue by dev-ddid** [filecoin-project/devgrants#485]
### 1. What is your project? (max 100 words)

dBook is an nft book marketplace that allows authors/publishers to publish their works as nfts. 
Readers/collectors can purchase these nft books by their favorite authors for their reading pleasure using the dBook app.
Readers can also choose to resell or transfer ownership of their nft book collection at any point of time. Authors/publishers are guaranteed of their royalty earnings with each secondary sale of their work.

https://github.com/dev-ddid/
  

https://dbookmarket.com/

### 2. How are you planning to improve this project? (max 200 words)

The project is currently under development and will provide a trading platform for NFT books for readers, publishers, authors and collectors.

The project addresses three issues:

**1. Copyright Protection**
   Genuine transaction records can be traced and held, no additional copies will be generated for dBook transactions.

**2. Digital Transaction**
   In addition to publishers and authors who can release D-Books, readers have the right to resell dBooks again.

**3. Collection Value**
   Each dBook is a limited edition with the opportunity to obtain the author's rare and precious signature.

 
### 3. Will the work be Open Source?

MIT

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes.

  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes.

### 6. Links and submissions
Project added to Filecoin showcase. Waiting to be merged.
https://github.com/filecoin-project/community/discussions/498

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Joy / dev@ddid.io / @dev-ddid
EePing / -- / --
Horry Bi / -- / @onlyYU

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @dev-ddid, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
Hi @dev-ddid, this microgrant has been approved! Look out for an email to submit payment details. 

We would recommend you check out [NFT.Storage](https://nft.storage/) for this project!
