### ISSUE TITLE
Low/No-code Middleware for Web3

### ISSUE THREAD

**Issue by edbong123** [filecoin-project/devgrants#487]
Hey, we already have a prototype on IPFS and secured a grant from Near. We now need to move to the next stage.
Do you think we need to repost our entire whitepaper
https://drive.google.com/file/d/1SI5bK0F8FrDN5C23XTGOpUG7Pdfmzp-A/view?usp=sharing
in your format for this forum?

Maybe someone can review it first before we put in all the effort? :)

Feel free to reach out directly
https://telegram.me/edbong

**Comment by realChainLife** [comment]
Hi @edbong123 thanks for sharing the whitepaper. Its a great read, for evaluation as a grant proposal - we'll need a detailed outline of the roadmap, with milestones breakdown and budget/ funding request. Please use the template we have available [here](https://github.com/filecoin-project/devgrants/issues/new?assignees=realChainLife&labels=Open+Grant&template=open-grant-application.md&title=). Looking forward to reviewing the proposal.
