### ISSUE TITLE
Next Step Microgrant: Ukraine Art Collective

### ISSUE THREAD

**Issue by mikegrushin** [filecoin-project/devgrants#488]
### 1. What is your project? (max 100 words)

We will be minting NFTs with all proceeds going to support the Ukrainian People (for Phase 1 hardcoded address of well-known non-profit). We are planning to use Pinata, NFT.storage and likely FileCoint. More details can be found here: https://UkraineArtCo.org

Setting it up now
  

work in progress - Web3 functionality will be added by end of week: https://UkraineArtCo.org

### 2. How are you planning to improve this project? (max 200 words)
We are looking to hire developer(s) to implement Phase 1 and also architect Phase 2 where we are planning to send part of the proceeds to the artist contributing the art, with the rest going to the selected non-profit
 
### 3. Will the work be Open Source?

Not planned at this time but would be open to consider. 

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Absolutely!
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Mike Grushin: mike.grushin@nextleague.com; github: mikegrushin; Role: CTO, Business Lead; https://www.linkedin.com/in/mikegrushin/
Leon Flaksin: leon.flaksin@gmail.com; Role: Business Lead; https://www.linkedin.com/in/leon-flaksin/
Bora Nikolic: bora.nikolic@nextleague.com; Role: Chief Design Officer; https://www.linkedin.com/in/boranikolic/
Vadim Keffler: vadim.keffler@gmail.com; Role: Web3 Lead
Jessica Kim: jessica.kim25@gmail.com; Role PMO. https://www.linkedin.com/in/jessicakim25/

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by YuliiaDeriuhina** [comment]
The project is open source. Here's a link to the profile https://github.com/ukraineartco

**Comment by ErinOCon** [comment]
Hi @YuliiaDeriuhina, thank you for your time on our call today! This microgrant has been approved! Look out for an email to submit payment details.

**Comment by mikegrushin** [comment]
THANK YOU!

We appreciate your support!!!
