### ISSUE TITLE
Next Step Microgrant: FIL HD wallet

### ISSUE THREAD

**Issue by llifezou** [filecoin-project/devgrants#489]
### 1. What is your project? (max 100 words)
Fil-wallet - A hierarchical deterministic wallet

https://github.com/llifezou/fil-wallet

https://github.com/llifezou/fil-sdk

https://github.com/llifezou/hdwallet

An open source, out-of-the-box hierarchical deterministic wallet tool 

- One mnemonic can derive multiple addresses, which is convenient for users or storage providers to manage multiple private keys
- Hierarchical Deterministic protocol compatible with Filecoin secp256k1, bls

Solve problem:

- Convenience: the benefit of managing one mnemonic phrase without the need to manage multiple private keys
- Trust issue: open source wallet without any trust risk
- Reduced complexity: users do not need to start a Filecoin node, as long as they can have a node endpoint, such as [Glif nodes](https://lotus.filecoin.io/developers/glif-nodes/), can send any transaction
- Extended: can even be used as an offline signature machine if necessary, with a large degree of security

### 2. How are you planning to improve this project? (max 200 words)
- Support offline signature
- Support signature verification
- Support balance inquiry
- Support transfer
- Support for send transactions
- Support multi-signature
- Support fvm calls (in the future)

### 3. Will the work be Open Source?
Yes

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes

### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

  | Name     | Email              | Github                      | Role      |
  | -------- | ------------------ | --------------------------- | --------- |
  | llifezou | llifezou@gmail.com | https://github.com/llifezou | Developer |
- Additional Information：lotus contributor
    https://github.com/filecoin-project/lotus/pull/6635
    https://github.com/filecoin-project/lotus/pull/7844
    https://github.com/filecoin-project/lotus/pull/8208
    https://github.com/filecoin-project/lotus/pull/8298
    https://github.com/filecoin-project/lotus/pull/7512
    https://github.com/filecoin-project/lotus/pull/7834
    https://github.com/filecoin-project/lotus/pull/8310
    https://github.com/filecoin-project/lotus/issues/7833
    https://github.com/filecoin-project/lotus/issues/7132

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @llifezou, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by llifezou** [comment]
> Hi @llifezou, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

Hi, @ErinOCon ,  I added a description of `Solved problem` for your review

**Comment by llifezou** [comment]
@ErinOCon Added `Additional Information` in `Additional questions`

**Comment by ErinOCon** [comment]
Hi @llifezou, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by llifezou** [comment]
https://github.com/filecoin-project/community/discussions/505
