### ISSUE TITLE
codered.club

### ISSUE THREAD

**Issue by Zepp61** [filecoin-project/devgrants#490]
Hello Lovely People,

My name is Hans Johannes Schulte, I'm from the Netherlands, in Groningen and I'm running https://codered.club/
Main activity is Aligning eSports events with Filecoin technologies. All video content is and will be loaded on Estuary and Web3.Storage and Space.storage, utilizing IPFS & Filecoin and storing data is a means to do that. 

I initiated use of my own members coin $CRED to sponsor events and tournaments, addressing $CRED sponsored tournament games and events to file it as NFTs and to promote Filecoin & IPFS as decentralized and the better option vs Sia, Storj or Arweave, to name a few.

I'm addressing new users and club members via airdrops and currently counting almost 5000 interested participants; it is overwhelming and by far exceeding my expectations! https://www.coinscope.co/coin/cred/airdrop 

I did issue a press release on this:
https://world.einnews.com/pr_news/564878502/codered-club-is-aligning-esports-events-with-web3-industries-providing-streaming-ipfs-to-attract-new-users 

I'm working on several new applications to build on IPFS and Filecoin, and storing data is a means to do that.
Next step for me would be to expand my server needs and capacity to let me run different scripts, as my current reseller server has limitations.
I opt for Call of Duty Warfare as this has huge fanbase and audience but is not limited to it.

I'll add the support for uploading files to Estuary & Web3.Storage in my app's. That will take me further 6-8 weeks of dev time.
I need approx. USD 10000 in total for providing liquidity in $CRED as incentive in support for the projects, advertising of the projects  and USD 5000 to address the server dev and technicities. 

I'm currently working on simplified approach by using the existing user IPFS content address to make Filecoin storage deals, with making use of the Estuary PIN initiative or/and to use Space.storage 
I want to offer different upload alternatives on codered.club all based on Filecoin technologies.

It goes without saying, I'm very enthusiastic and believe firmly, stand for, and believe in decentralization, by all means!
Filecoin and IPFS, you provide truly brilliant service to and for all!

I have actively introduced codered.club and reached out to several members for support within your community on slack, discord and github.
I was directed to use and to apply to file for grants by Stefaan Vervaet, Bill Schreckenstein and David Choi.
https://bafybeifh2cixv467bfwrddh4xco4bxmcy4f7kkpuvjv6fyjsux4z5n3ozy.ipfs.dweb.link/slack.jpg
https://github.com/web3-storage/docs/issues/225#issuecomment-1067074384

I would highly appreciated to receive your support for my project as it would accelerate and "level up" to execute it better & faster!

Every "single" stored video is played by 150 eager participants as you can see in this
video: https://bafybeifnuycchcs5eymkdgcrjyibjau3dhqcsroqxotsi47ye27bskrazi.ipfs.dweb.link/150%20eager%20participants.mp4

My Filecoin account is: f1j6n4obv2b57tqve2ii22m7u6slebwrsd6q4qmxi

Q:Will the work be Open Source?
A: Yes.

Q: If selected, do you agree to share weekly updates and a grant report upon conclusion?
A: Yes, most certainly.

Q: Does your proposal comply with our Community Code of Conduct?
A: Yes, completely!

Q: Has this project prior submissions or been part of an event or hackathon?
A: No

Looking forward, eager on your support to make this the best Filecoin - last mile project ever!

Best Regards,
Hans Johannes Schulte

**Comment by ErinOCon** [comment]
Hi @Zepp61 , Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.
