### ISSUE TITLE
Next Step Microgrant: codered.club

### ISSUE THREAD

**Issue by Zepp61** [filecoin-project/devgrants#491]
### 1. What is your project? (max 100 words)

Aligning eSports events with Filecoin technologies. All video content is and will be loaded on Estuary and Web3.Storage and Space.storage, utilizing IPFS & Filecoin and storing data is a means to do that. 
https://codered.club/ 
Every single stored video is about 150 eager participants as you can see in this
video: https://bafybeifnuycchcs5eymkdgcrjyibjau3dhqcsroqxotsi47ye27bskrazi.ipfs.dweb.link/150%20eager%20participants.mp4
I'm addressing new users and club members via airdrops and currently counting almost 5000 participants; it is overwhelming and by far exceeding my expectations! https://www.coinscope.co/coin/cred/airdrop 

### 2. How are you planning to improve this project? (max 200 words)

Next step for me would be to expand my server needs and capacity to let me run different scripts, as my current reseller server has limitations. I opt for Call of Duty Warfare as this has huge fanbase and audience but is not limited to it. I'll add the support for uploading large game video files to Filecoin technologies such as Estuary & Web3.Storage in my app's. That will take me further 6-8 weeks of dev time, I need approx. USD 10000 , including advertising of the projects and USD 5000 to address the server dev and technicities.

### 3. Will the work be Open Source?
Yes.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes, most certainly.

### 5. Does your proposal comply with our Community Code of Conduct?
Yes, completely!

### 6. Links and submissions
https://github.com/filecoin-project/devgrants/issues/490 

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Hans Johannes Schulte, email:  info@codered.club , https://github.com/Zepp61 , Dev.
* If your project was created as part of an event or hackathon:
No

**Comment by ErinOCon** [comment]
Hi @Zepp61, thank you for your proposal! Can you provide the repo affiliated with this work? This will help us complete the review.

**Comment by Zepp61** [comment]
Happy to hear back from you @ErinOCon Please find here the repo https://github.com/Zepp61/codered.club

**Comment by Zepp61** [comment]
Hi @ErinOCon  Not yet, all progress will be made available when implemented to be used by others as example and we will make more websites based on it. We are uploading currently directly, hence our request for the grant.
<img width="1280" alt="Upload" src="https://user-images.githubusercontent.com/93491711/161125130-54b3e8f4-68a8-44c0-b838-f637588e8f23.png">

**Comment by Zepp61** [comment]
@ErinOCon First CodeRed NFT with Filecoin 6.75 GB NFT with Estuary https://ab2.gallery/asset/702197152 & 773 KB on NFT Storage https://ab2.gallery/  maybe Filecoin want to buy the very first CodeRed NFT with Filecoin 6.75 GB NFT on Estuary! Never Give Up!

**Comment by Zepp61** [comment]
@ErinOCon  I assume, as there is no reply, my project did not pass the review, that is alright. Do you want to you want me the close this? Happy Easter To All God' Bless"! Thanks.

**Comment by ErinOCon** [comment]
Hi @Zepp61, thank you for the additional background and updates - this is very helpful! Do you expect the applicable code to be available to share in upcoming weeks? The code and prototype of a project are generally key pieces to our review.

**Comment by Zepp61** [comment]
@ErinOCon Most certainly, even more, not just the code but a complete step by step blog addressing from installing git, node.js and yarn, install dependencies, install Truffle, install Ganache CLI - CUI, compile contract, etc, All video tutorials showing how to deploy the smart contracts. The reason for applying for the grant is to initiate "commitments" as I agreed to pay to devs & need to pay for ending trail on wasabi. With the grant I expect to have it all up and running within 7-8 weeks max. The project just keeps growing and growing, all about the user experience as the topic is sought after, but hey, I've the framework done! https://bafybeihqwnrpi24wsn4sbmkv4bg46ommz6jabgw5xinpgfaj3wuyb4uope.ipfs.nftstorage.link/  I'm sure it is a never ending filecoin blue story blog!

**Comment by ErinOCon** [comment]
Hi @Zepp61, thank you for the additional detail! Once your project has incorporated the code you are building into a repo, please let us know. This will help our team review and track progress!

**Comment by Zepp61** [comment]
Hello @ErinOCon, Wow,  This took me a long time to figure and to address the best way to start. It was right under my nose. I have updated the project accordingly! I had to "force myself" with the KISS principle, as you know, the KISS principle states that most systems work best if they are kept simple rather than made complicated. Lol, again, It was right under my nose! I salute you!

**Comment by Zepp61** [comment]
@ErinOCon This is the contract for uploads to IPFS https://polygonscan.com/address/0x8a9312c35b2764ebee4b04c7cd3b19a6cb4a936a and from https://upload.codered.club/ I can screen/determine suitable media for hash NFT upload. I hope it is sufficient for your team to review and track progress!

**Comment by Zepp61** [comment]
https://github.com/Zepp61/codered.club

**Comment by ErinOCon** [comment]
Thanks, @Zepp61!

**Comment by ErinOCon** [comment]
Hi @Zepp61, This microgrant has been approved! Look out for an email to submit payment details.
