### ISSUE TITLE
Polyphene - FVM Integration test framework

### ISSUE THREAD

**Issue by tchataigner** [filecoin-project/devgrants#492]
# Open Grant Proposal: FVM Integration test framework

**Name of Project:** FVM Integration test framework

**Proposal Category:** `devtools-libraries`

**Proposer:** @tchataigner

**Technical Sponsor:** @raulk 

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes

# Project Description

The evolution of the fvm in a programable runtime is one of the next big step for the Filecoin network. It involves changing how the current runtime runtime works from the inside out. Specifications have been completed in Phase 0 and implementation is currently under development in the ref-fvm repository.

To confidently verify the correctness of ref-fvm project, we need an integration test framework that will allow us to write small actors, and have them run inside the FVM, performing assertions inside the actor and on its execution environment (at the FVM level).

## Value

When this framework becomes available it will assists core devs in their task to develop the runtime for the network. To be more precise it will help exercise and mitigate risky behavior that could happen either at the actor or at the FVM level (Kernel, CallManager, Machine). Such behaviors could be: Providing malformed or otherwise malicious input to syscalls, sending malicious internal messages (infinite recursion, trying to manipulate other actors they aren’t authorized to, etc.), exchanging incorrect memory pointers via syscalls...

Without a proper test framework such behavior could stay undetected or untested which could compromise the security of the vm in the long-run.

## Deliverables

The final deliverable of the project will be the addition of a new module in the `ref-fvm` repository. This module under `testing/integration` will be a rust library delivering needs expressed by the `ref-fvm` core developers.

The module should:

- Assist a developer in instantiating a new `Machine` with a custom actor bytecode deployed, allowing him to interact with it and receiving the receipt summarizing how the interaction went.
- Create a new syscall, available during integration testing, providing the possibility to run assertions in actors code. The result of such assertions will then be available to the developer to work around in his tests
- Ensure accessibility of structural components of the FVM for the tester to analyze once the call to the actor is executed. Such components includes: `StateTree`, `Blockstore`, `Engine` and `Receipt`

## Development Roadmap

Three epics are composing our roadmap

### Introduction

Create a dedicated tooling to easily instantiate a new `Machine` with a pre-compiled actor code ready to be called. Some reference code can be find on the [ERC 20 PR](https://github.com/filecoin-project/ref-fvm/pull/290/files#diff-da5e5b6723420f78129e88167dde584702aa526cd3afcfdd272eae2a020d1d3c) and the [conformance tests](https://github.com/filecoin-project/ref-fvm/blob/raulk/example-token-actor/testing/conformance/src/vm.rs).

### Proposal

We should provide developers with a tooling suite that allows them to freely instantiate a new FVM  with a custom actor ready to be interacted with.

Instantiation should be as simple as possible. To start we will focus on having only one parameter, a WAT code being the actor to be instantiated along with the FVM.

Once the instantiation ready the developer should have access to:

- A list of 10 accounts to be used during his testing
- The address of the deployed actor
- A call manager interface to interact with the newly created instance

After a call is made the developer will access the return payload, allowing him to perform assertion to perform his test.

### Introduction

A developer using the integration test framework might want to test out assertions in the actor WAT code. To do so, a design should be found to properly communicate between the actor and the test framework.

### Proposal

Assertions would be carried out inside of an actor with a custom [`ÈxitCode`](https://github.com/filecoin-project/ref-fvm/blob/master/shared/src/error/mod.rs#L16) being created to related to assertions failing. Message will be propagated upward using the `fvm::abort` syscall.

### Introduction

Once an actor has been interacted with a core developer will want to analyze the state of the component composing the FVM to ensure that everything are still in an OK state and that all evolutions were taken into account. To do so he will need to access those components in his testing.

### Proposal

The `integration` library will have to properly instantiate those components and ensure their access to the developer running his test. The exposed components should be:

- `StateTree`
- `Blockstore`
- `The Engine`
- `Receipt`

### Introduction

After some [discussions](https://github.com/filecoin-project/devgrants/issues/492#issuecomment-1077649244) it was agreed that 5 integrations test would be delivered with the integration test framework.

### Proposal

The 5 tests to be added are:

- Calling syscalls that may or may not be available.
- Providing malformed or otherwise malicious input to syscalls
- Allocating memory beyond limits.
- Calling specific Wasm instructions.
- Triggering overflows.

## Total Budget Requested

Funds will be used to remunerate our developer, `tchataigner`, spending 6 days to develop the framework. One man-day is estimated at **1.5k USD**. Each milestone is then priced at **3k USD** and the whole development at **9k USD**. To these **9k USD** we are also adding 1 days of maintenance to help on bug fixes once the development is completed. The final budget would be a total of **12k USD**.

## Maintenance and Upgrade Plans

Maintenance of this test framework should fall under the maintainance of the `ref-fvm` repository

# Team

## Team Members

Thomas Chataigner, @tchataigner
Philippe Métais, @PhilippeMts

## Team Website

[https://polyphene.io](https://polyphene.io/)

## Relevant Experience

We already have some experience in handling wasm runtime and development of tooling around it. We spent last year designing and building the [Holium project](https://holium.org/). It allowed us to hone our skills to build rust-based protocols and libraries.

Moreover, we followed the FVM specification and development since its premises. We already had the opportunity to talk to @raulk 
 at the time about future collaboration and this grant is the result of this discussions.

## Team code repositories

[Holium Rust](https://github.com/polyphene/holium-rs)

[Holium Rust SDK](https://github.com/polyphene/holium-rs-sdk)

**Comment by raulk** [comment]
> That was not taking into account in my roadmap and I fear that it might get complicated for us to do the framework and all the testing implementation afterwards

I think it's important to cover at least a few, in case you can't cover all of them. This will allow you to validate that the framework being developed is indeed usable for the purposes we intend. Would it work for you to pick 5 cases to implement, maybe?

> [[Assertions]]

There are two places where we want to make assertions:
- On the Rust side: we'll perform these assertions post-facto by inspecting the respective objects (StateTree, Blockstore, Engine, Receipt, etc.)
- Inside the actor: I think the idea of introducing syscalls to do the logical comparisons (assert_eq, etc.) might overcomplicate things a little. I think we can perform these assertions _inside_ the actor, and abort the execution with a custom [ExitCode](https://github.com/filecoin-project/ref-fvm/blob/master/shared/src/error/mod.rs#L16) that only exists behind a feature. The `fvm::abort` syscall allows you to provide a message, so the assertion utility would create the right message to propagate it outwards.

```rust
    enum ExitCode {
		...
        
        #[cfg(feature = "testing")]
        TestAssertionFailed,
    }
```

>> One requirement of the RFP was to implement WAT and Rust based compilation for test actors -- this is not covered in the proposal? (unless I missed it!)
> As when we had our discussion yesterday it seemed that WAT was a priority and mandatory compared to Rust based compilation I left it out to move faster on development. If you think that it should be included here I will be glad to add it to the SOW.

Yes, please do ;-) WAT is P0 and we can consider Rust => Wasm compilation as a P1.

**Comment by raulk** [comment]
LGTM.

**Comment by ErinOCon** [comment]
Hi @tchataigner, this grant has been approved! We will continue to be in touch by email. Thank you for your submission!
