### ISSUE TITLE
Next Step Microgrant: beoble by Kryptonium

### ISSUE THREAD

**Issue by whtjdals016** [filecoin-project/devgrants#493]
### 1. What is your project? (max 100 words)
beoble is a social module with API and SDK for Web 3.0. It is an on-chain communication window and a user-owned Web 3.0 product. With beoble, Web 3.0 services can easily integrate social functionalities of social profile, messaging, and posting & feeds into their services in 5 minutes. beoble’s core features include 1) modularized social profile using NFTs, 2) modularized wallet-to-wallet messaging, and 3) modularized posting & feeds. We mainly target the NFT community at the moment, which involves ipfs and NFT storage.

We do not have a public repo for this project yet.

https://www.beoble.io/

### 2. How are you planning to improve this project? (max 200 words)
We are still in the initial building stage. Using your support, we will mostly focus on finishing the building of beoble. As our goal is to receive next round investment and hire more people, this grant will be very useful for the co-founders to carry on until we receive the next round investment. 
We are currently aiming to finish the initial building during 2022 Q2, and to launch the alpha / beta version of beoble by end of 2022 Q2. With initial version and few traction, we believe we can gain initial investment.
 
### 3. Will the work be Open Source?
Yes, with MIT License.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes, we agree. Will be helpful to receive feedbacks on our weekly updates, which will guide us to a better direction.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes, we believe it is aligned with your Community Code of Conduct.

### 6. Links and submissions
Our Deck: https://drive.google.com/file/d/11jAjjN6UvUm_yjLOYeQJewXdCDbTAFUJ/view?usp=sharing
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
https://showcase.ethglobal.com/nfthack2022/whoodid-com
We started with a full social service, but pivotted to a modularized one.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
1. CHO, Sung Min
sungmin.cho@kryptonium.group
https://www.linkedin.com/in/sung-min-cho/
CEO of the company, backend & blockchain developer

2. YUN, Jungwoo
jungwoo.yun@kryptonium.group
https://www.linkedin.com/in/jungwooyun/
Co-Founder of the company, frontend & web3 developer

3. YIM, Chanhyeok
chanhyeok.yim@kryptonium.group
https://www.linkedin.com/in/chanhyeokyim/
Co-Founder of the company, fullstack developer.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
1. ETHGlobal NFTHack
https://showcase.ethglobal.com/nfthack2022/whoodid-com
We started with a full social service, but pivotted to a modularized one.

2. EthGlobal LFGrow
https://showcase.ethglobal.com/lfgrow/beoble-rq9va

**Comment by ErinOCon** [comment]
Hi @whtjdals016, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by whtjdals016** [comment]
Updated the comment with our recent hackathon submission to ETHGlobal LFGrow.

**Comment by whtjdals016** [comment]
Also updated the terms regarding open sourcing.

**Comment by ErinOCon** [comment]
Hi @whtjdals016, thank you for providing notice of these updates! The hackathon details were very helpful for our review. Moving forward, please use your own repo for this work. 

This microgrant has been approved! Look out for an email to submit payment details.

**Comment by whtjdals016** [comment]
This is awesome, thank you so much!
Will take care of the form as soon as possible.
