### ISSUE TITLE
Next Step Microgrant: 3WebDAO

### ISSUE THREAD

**Issue by Jonkrua** [filecoin-project/devgrants#494]
### 1. What is your project? (max 100 words)

3WebDAO is a decentralized blockchain insight platform, which combines reserach reports and on-chain data metrics for digital asset stakeholders.

Why Report？
We found that blockchain is a high threshold industry combining technology and finance. 3WebDAO hope to help early users finding out blockchain through more professional and objective research reports which be stored on Filecoin/IPFS through [Web3.storage](https://web3.storage/).

Why On-Chain？
As early adopters of crypto, we found blockchains are constantly generating a wealth of open, incorruptible financial data that allows us to access precise, trustworthy measures of relevant economic activity in crypto networks.By unlocking this data, 3WebDAO is changing the way we measure market sentiment and behaviour.

**Github**：https://github.com/3WebDAO

**Website**: http://47.107.93.234/#/  (will become https://web.io)

  

### 2. How are you planning to improve this project? (max 200 words)

In the future, our team will continue to improve the development of the official website, and the design will encourage more blockchain researchers to output objective and professional industry reports in a decentralized form, and the reports will be uploaded to IPFS/Filecoin which  base on [Web3.storage](https://web3.storage/) in the form of decentralized governance voting. 
 
### 3. Will the work be Open Source?

Yes, the work will be Open Source.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes, Of course.
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes.

### 6. Links and submissions

https://github.com/filecoin-project/community/pull/483

https://github.com/filecoin-project/community/discussions/482

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

    Jonkrua:  Blockchain Developer/Researcher，https://github.com/Jonkrua

    Clayton:   Blockchain/Data development engineer ，https://github.com/clay98073429

    Alex:         Front-end engineer ，https://github.com/AlexzZzNM

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @Jonkrua, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by Jonkrua** [comment]
> Hi @Jonkrua, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

Hi @ErinOCon , The Project Submission about 3WebDAO have been Merged [#483](https://github.com/filecoin-project/community/pull/483) into master already. You can see it in https://github.com/filecoin-project/community/blob/master/projects/application/3WebDAO.md

**Comment by ErinOCon** [comment]
Hi @Jonkrua, Thank you again for your submission! It looks like the next steps of your project are primarily centered around reporting. If building out decentralized storage with Filecoin and related tech becomes a core value in the future, please feel welcome to submit a new Issue.
 
Good luck with the next steps of your project!
