### ISSUE TITLE
RFP Application

### ISSUE THREAD

**Issue by JoannaPicetti** [filecoin-project/devgrants#495]
# VISION OF THE PROJECT

PLANET EARTH DAO -  Global Digital Jurisdiction

8 Billion PEOPLE + NATION DAOs + Company DAOs → All in the same ledger.

# DESCRIPTION OF THE PROJECT

Different Blockchain mechanism for,

Citizens → Proof of Personhood
Nations  → Proof of Nation DAOs
Companies → Proof of Company DAOs

INTERPLANETARY ID SYSTEM →  [Planetary ID wallets](https://github.com/JoannaPicetti/INTERPLANETARY-ID-SYSTEM---PLANET-EARTH-PASSPORTS/blob/main/Planet%20Earth%20Identity%20Wallet)

Planet ID wallet for people → Planet Earth NFT Passports → Planetary Citizens
Planet ID wallet for Nations  …..         ( WORK IN PROGRESS )         
Planet ID wallet for Companies …….  ( WORK IN PROGRESS )     
                        
New web browser extension & mobile app to allow People - Nations - Companies to interact w/ PLANET EARTH DAO.

# PROBLEM     

Scale of Ethereum

→ Ethereum is left behind.

Proof of Stake is inherently a [Plutocracy](https://en.wikipedia.org/wiki/Plutocracy) that makes the rich richer.
I prefer Democracy - Digital Democracy 

Ethereum Blockchain has NO personhood, so you can't have 1 person = 1 vote. 
You can have 1 unit of money = 1 vote. Which is [Plutocracy](https://en.wikipedia.org/wiki/Plutocracy)  not democracy.

Ethereum Blockchain just blindly executes rules. 
The rules (that are effectively a monetary policy) are still written and approved by people, but these people aren't elected officials, but an oligarchy of developers and plutocracy of miners. And with Proof of Stake, the same happens with validators. POS is terrible.

Anybody who has capital to do so<< can turn that capital into influence (through staking or mining).That is the definition of plutocracy. If it wasn't anyone, we'd be talking about aristocracy..

Blockchain is the best invention ever since the internet. (It has existed for 13 years) -->Yes

But we have to move forward & fast → We don’t have time to waste → because of that I built →

#SOLUTION

[Planet Earth DAO](https://github.com/JoannaPicetti/PLANET-EARTH-DAO)  and its respective protocols,

[Global Taxation Protocol](https://gitcoin.co/grants/4349/global-taxation-protocol-global-crypto-currency)
[Interplanetary ID system - Global NFT Passports](https://github.com/JoannaPicetti/INTERPLANETARY-ID-SYSTEM---PLANET-EARTH-PASSPORTS)
[Planetary ID wallets](https://github.com/JoannaPicetti/INTERPLANETARY-ID-SYSTEM---PLANET-EARTH-PASSPORTS/blob/main/Planet%20Earth%20Identity%20Wallet)

To build   → [Global Government](https://github.com/JoannaPicetti/GLOBAL-GOVERNMENT-DIGITAL-ECONOMY-NEW-SOCIAL-CONTRACT-)

Some core use cases of [Planet Earth DAO](https://github.com/JoannaPicetti/PLANET-EARTH-DAO) 

Land registry
Transparent gov spending
Automated taxation [Global Tax](https://gitcoin.co/grants/4349/global-taxation-protocol-global-crypto-currency)
UBI

Some core use cases of [Planet Earth NFT Passports](https://github.com/JoannaPicetti/INTERPLANETARY-ID-SYSTEM---PLANET-EARTH-PASSPORTS)

Voting
Taxation
Border crossing
Medical records

(or you could get a loan, or purchase a house, etc…  all you do in your Nation but worldwide)

[Planetary ID wallets](https://github.com/JoannaPicetti/INTERPLANETARY-ID-SYSTEM---PLANET-EARTH-PASSPORTS/blob/main/Planet%20Earth%20Identity%20Wallet) → Digital Identity Wallets  (  [Decentralized Identity](https://www.forbes.com/sites/forbestechcouncil/2021/12/10/how-decentralized-identity-is-reshaping-privacy-for-digital-identities/?sh=6f384a2f3226) )

Citizens
Nations States
Companies

We are building with [Consensys](https://consensys.net/)
 [Data Integrity](https://en.wikipedia.org/wiki/Data_integrity)  prevent,

Fake news
Campaign disinformation
Hacking database
Hacking the voting software

https://ipfs.fleek.co/ipfs/bafybeiboqqadktzgtphounkcfabbui7665e6u3ffopw5enlggfqqw6tz2m

Appendix

*A digital identity wallet enables a user to establish relationships and interact with third parties in a trusted manner. It is a piece of software, which helps you to stay in control of your messaging, security, health records, privacy, purchases etc…

“DECENTRALIZE IDENTITIES GIVES INDIVIDUALS CONTROL OVER THEIR OWN IDENTITY SO THAT THEY CAN DECIDE HOW THEIR PERSONAL INFORMATION IS SHARED AND ACCESSED, ENABLING TRUSTED INTERACTIONS WHILE PRESERVING PRIVACY. “

KEY words:  INDIVIDUALS CONTROL, ENABLING TRUSTED, SOVEREIGN INDIVIDUAL

https://showcase.ethglobal.com/nfthack2022/nft-passports-planet-earth

https://showcase.ethglobal.com/buildquest/world-game-planet-otfaq

https://showcase.ethglobal.com/roadtoweb3/interplanetary-id-system-digital-passports

**Comment by realChainLife** [comment]
Closing this to deduplicate application submission.

**Comment by JoannaPicetti** [comment]
Sonia,

I applied in these 3 differents grants -->

[image: IMG_0464.jpg]

Please, could you confirm I am running all of them?

I don't want to miss any opportunity.

Thanks and best,

Joanna

**Comment by JoannaPicetti** [comment]
Please, could you open this submission?
