### ISSUE TITLE
Next Step Microgrant: Skillset

### ISSUE THREAD

**Issue by AjiteshBD** [filecoin-project/devgrants#499]
### 1. What is your project? (max 100 words)
NFT Talent Marketplace. Get hired based on skills NFT and paid real time per hour in crypto.

  https://github.com/AjiteshBD/SkillSet

https://skillset.cryptoineer.com

### 2. How are you planning to improve this project? (max 200 words)

1. Development of coding assessment and challenges for developers modules and integration from competitive programming site like  leetcode.
2. Building "Dynamic NFT" to mint their Dynamic Skill NTF's
3. Marketplace creation for companies to hire talent with employment benefits and polices. DAO court can be used by employees 
     to raise any dispute.
4.  Company to retain talent NFT's until hired and can be released in Talent Skill NFT metadata upon talent release.
5.  UDSC month payment module and streaming service using Superfluid.

### 3. Will the work be Open Source?

 No license Yet 
### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

  Yes
### 5. Does your proposal comply with our Community Code of Conduct?

Yes
### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

  https://showcase.ethglobal.com/nfthack2022/skillset
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
I was solo hacker on hackathon
Name : Ajitesh Mishra
email : ajiteshm@oulook.com
github link : https://github.com/AjiteshBD
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  EthGlobal NFTHack2022
  * Please link to your hackathon submission
   https://showcase.ethglobal.com/nfthack2022/skillset

**Comment by ErinOCon** [comment]
Hi @AjiteshBD, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
@AjiteshBD, if applicable, can you confirm under item 3 that you agree to open source this work? This is a requirement for the microgrant program. Let me know of questions!

**Comment by AjiteshBD** [comment]
Yes
