### ISSUE TITLE
Next Step Microgrant: <Your Title Here>

### ISSUE THREAD

**Issue by xunorus** [filecoin-project/devgrants#500]
### 1. What is your project? (max 100 words)
ScoreMinter is a DAP to mint, buy, sell and commission musical scores. 
With SCOREMINTER you can mint a new music scores, host your files on IPFS, and sell them as NFT.
You can also  buy or rent musical scores as NFTs, commission a composer to write a musical score for you and your group, and share the revenue from future sales!
You can protect your creation with our proposed PROOF OF OWNERSHIP mechanism!!!
You can validate your old and new commissionments through our OFFCHAIN COMMISSIONMENT mechanism.

<!-- Link to Github repo →
https://github.com/xunorus/scoreminter
  
<!-- Link to demo or website, if applicable →
https://scoreminter.xyz/

### 2. How are you planning to improve this project? (max 200 words)
I look forward to apply encryption methods to veil  in plain-sight (on NFT metadata) the contents each user uploads to IPFS, finish the marketplace's engineering, create a DAO to administer it,  and implement tokenomics mechanisms to incentivize the use of the dap.

 
### 3. Will the work be Open Source?
Yes. I don't know if MIT or GPL yet.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes!

  
### 5. Does your proposal comply with our Community Code of Conduct?
yes

### 6. Links and submissions
* For each team member(s), please list name, email, Github account, and role in the project.
Claudio Xunorus, [xunorus@gmail.com](mailto:xunorus@gmail.com) , https://github.com/xunorus, CEO and founder

* If your project was created as part of an event or hackathon:
My project was created as part of a hackathon

  * What was the name of the event? 
NFTHack

  * Please link to your hackathon submission
https://showcase.ethglobal.com/nfthack2022/scoreminter

**Comment by ErinOCon** [comment]
@xunorus, Thank you for your interest in a microgrant! It looks like the [full template](https://github.com/filecoin-project/devgrants/issues/new?assignees=ErinOCon&labels=Micro+Grant&template=microgrant.md&title=Next+Step+Microgrant%3A+%3CYour+Title+Here%3E) didn't go through. Would you like to update your submission to include this information?

**Comment by ErinOCon** [comment]
Hi @xunorus, this issue has been closed. Please feel welcome to request a new grant by opening a new issue.
