### ISSUE TITLE
Next Step Microgrant: NFT-LINK

### ISSUE THREAD

**Issue by grmkris** [filecoin-project/devgrants#502]
### 1. What is your project? (max 100 words)
NFT-Link is a tool to be used to distribute NFTs using magic links. Creator can create erc721, erc1155 NFT and wrap into a magic link. Whoever has the access to the magic link can mint the NFT. 
Creator can also define how many mints can be done using the magic link, creator can track the magic link performance (how many times it was opened etc..)
Creator also has view of all released NFTs and their current hodlers. If NFT was sold on secondary markets this will also be seen. 
Creator can define royalty fees when creating the NTs

 - https://github.com/Seth-McKilla/nfty-links

- https://nfty-links.vercel.app/
### 2. How are you planning to improve this project? (max 200 words)
It is currently possible to create NFTs and distribute them using magic link. You can also see the statistics for every created NFT. 
To improve everything we want to add the following features:
- track magic link performance
- admin dashboard view
- connect social / email providers for easier NFT distribution
- dockerize the backend middleware needed for magic links and make it deployable on decentralized networks like Akash and similar
 
### 3. Will the work be Open Source?
Yes work will be open source, free to use and distribute & modify

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes, I can make a weekly blog post with the progress 
  
### 5. Does your proposal comply with our Community Code of Conduct?
YES

### 6. Links and submissions
- https://docs.google.com/presentation/d/1ZPwCh1fG8BVmPT20z7UX3pFJMTXy3HPNkFZASf4CxKU/edit?usp=sharing
- https://www.youtube.com/watch?v=FrvbeYJkYPI

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:  
YES -  ETHGlobal NFT Hack 2022 . I was one of the winners

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
- Currently it is only me working on this: kristjan.grm1@gmail.com (github: grmkris)

* If your project was created as part of an event or hackathon:
ETHGlobal NFTHack

* Please link to your hackathon submission
https://www.youtube.com/watch?v=FrvbeYJkYPI

**Comment by ErinOCon** [comment]
Hi @grmkris, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
Hi @grmkris, This microgrant has been approved! Look out for an email to submit payment details.
