### ISSUE TITLE
Next Step Microgrant: NFTmall 🔥

### ISSUE THREAD

**Issue by nftgeek** [filecoin-project/devgrants#503]
### 1. What is your project? (max 100 words)
NFTmall is the world’s first Creator-centric & Physically-redeemable NFT Marketplace & Launchpad. ✨
We are building NFTmall as the `#1 NFT ecosystem` that provides a complete life cycle of NFTs. It starts from Minting, Dropping, Curation, Monetization, Trading via various types of auctions, launching new NFT projects, IDO platform, to ordering physical products in the real world from NFTs.
We are using IPFS to store NFT images and metadata.

Website: https://nftmall.io
Github: https://github.com/nftmall
Audit from CertiK: https://www.certik.com/projects/nftmall
Demo video: https://vimeo.com/672228751

[![NFTmall Demo Video](https://user-images.githubusercontent.com/85253037/160408567-13f479ce-85f4-4dae-a76b-910b6b200c01.png)](https://vimeo.com/3514904 "NFTmall Demo Video")

### 2. How are you planning to improve this project? (max 200 words)
- At the moment, our marketplace supports only picture NFTs (.jpg, .png, .gif) on IPFS, but we are going to support more file types such as videos (.mp4), audio (.mp3) and 3D objects (.gltf, .glb).
- We are going to launch on more EVM compatible chains.
 
### 3. Will the work be Open Source?

Our smart contracts are already open source.
In the future, we'll open source frontend code as well.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Sure.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Sure.

### 6. Links and submissions

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

We submitted our project for the IPFS prize at the Moralis+Avalanche hackathon.
https://moralis.io/hackathon-prizes/
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.  
  Learn more about our team here.  https://nftmall.io/team
 
* If your project was created as part of an event or hackathon: What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum). 
  Moralis+Avalanche hackathon.
  https://moralis.io/avalanche-hackathon/ 

* Please link to your hackathon submission.
Here's our submission link. (The hackathon organizer's website does not have permalink for individual projects)
https://nftmall.notion.site/NFTmall-Team-s-Hackathon-Submission-5675ec4c153f4ece9e07838037d748a8

Thanks.

**Comment by ErinOCon** [comment]
Hi @nftgeek, This microgrant has been approved! Please provide your email address to proceed with the payment process.

**Comment by nftgeek** [comment]
Hi @ErinOCon  We are thrilled to hear that!  Please reach out to our CMO sunny@nftmall.io.  Thanks!
