### ISSUE TITLE
Open Grant Proposal: NIIIFTY

### ISSUE THREAD

**Issue by edsilv** [filecoin-project/devgrants#504]
# Open Grant Proposal: `NIIIFTY`

**Name of Project:** NIIIFTY

**Proposal Category:** `devtools-libraries`

**Proposer:** `edsilv`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:**  Yes

# Project Description

Sites like [exhibit.so](https://exhibit.so/) allow cultural heritage institutions to build engagement with their online digital collections by leveraging [IIIF](https://iiif.io/)-formatted images, 3D models, and audiovisual content. There is a large [community](https://iiif.io/community/consortium/members/) of IIIF adopters, with 100's of cultural institutions worldwide using the protocol to allow their content to be remixed and reused.

**Problem**

IIIF json served over the web from online repositories can often [change](https://twitter.com/leoba/status/1498660317173329925) or even become unavailable. The promise of IIIF is to make cultural heritage content reusable by third-party applications, but for tools like [Exhibit](https://exhibit.so/) it can often be unreliable and lead to a poor user experience.

**Solution**

We would like to apply for a grant to increase the level of data robustness in the IIIF ecosystem, by leveraging the content addressing features of IPFS. Content addressing will allow IIIF consuming applications to reliably request immutable and redundantly stored data, therefore providing an improved user experience for applications like [Exhibit](https://exhibit.so/).
 
We propose to create a new software package named “NIIIFTY”. NIIIFTY is a set of software components that allow consuming applications to upload high resolution images, 3D models, and mp4 files to IPFS via [nft.storage](https://nft.storage/)’s javascript API. NIIIFTY allows users to browse their uploaded files, and link to them via their IPFS content id over any preferred IPFS gateway. All uploaded content is available in IIIF format with associated info.json and json manifest complying with the latest version of the specifications.

The upload experience will be designed to be as accessible as possible, with an option to either drag and drop or browse to a file. Once uploaded, users can easily find and copy the content ids (cids) for their files in order to be able to pin them on another IPFS node. We believe this will be an important feature for cultural institutions given their responsibility to preserve and safeguard data. The cids can also optionally be used to mint NFTs for the content using a third-party platform such as OpenSea. We believe that NFTs could represent an important new type of authoritative permanent identifier for the cultural heritage sector.

The outcome of this project will allow users to try out NIIIFTY features at a demo URL such as niiifty.com.

## Value

- IIIF content will become portable - cultural institutions can set up their own IPFS nodes to pin content, or use a third party service.
- IIIF content will be redundantly stored - if an IPFS node storing the content becomes unavailable, and the content has been pinned elsewhere, it can be loaded from there instead via any IPFS http gateway.
- IIIF content will become immutable - content addressing ensures that the IIIF content cannot change, making it a more dependable data source for third-party apps like exhibit.so. 
- High resolution images stored on IPFS will load quickly using IIIF image tiling.
- Audiovisual mp4 content will be segmented into HLS and MPEG-DASH formats for adaptive bitrate streaming
- 3D models will be automatically optimised in order for consuming applications to load them quickly.
- Images, 3D models, and audiovisual content can be minted as an NFT using any preferred third-party minting platform. It can also be remixed/reused via annotations in compliance with the IIIF specifications.

## Deliverables

- A set of [next.js](https://nextjs.org/) react components coupled with Firebase node.js functions that provide
  - A user account flow including the ability to create an account and list your uploaded files with name and thumbnail.
  - The ability to drag and drop or browse to upload images (jpg, png, tiff), 3D models (glTF, glb), or audiovisual content (mp4) to nft.storage. 
  - The ability to specify metadata per upload including attribution and licence.
  - The ability to use uploaded files in IIIF-compliant consuming applications such as exhibit.so
  - The ability to copy a file’s content id in order to pin it on another IPFS node, or mint it as an NFT on OpenSea and other similar platforms.
  - A demo site (e.g. niiifty.com) where users can try out these features.
- We are interested in exploring potential overlaps with [Supabase](https://supabase.com/) (an open source alternative to Firebase). Supabase currently does not support node.js cloud functions, but if these are added we may also consider compatibility with this platform, potentially as an alternative to Firebase.

## Development Roadmap

**Milestone 1: Project set-up**

- Initial setup of github repo, next.js, firebase
- Implement user account flow components

(time taken: 2 weeks)

**Milestone 2: Upload capability**

- Use nft.storage [Javascript API](https://nft.storage/docs/#using-the-javascript-api) to implement image, glTF, and mp4 upload component
- Implement IIIF image tiling and info.json generation on upload
- Implement glTF optimisation on upload
- Implement HLS and DASH segmentation on mp4 upload
- Implement thumbnail generation for uploaded images, glTFs, and mp4s
- Implement “my files” component listing all uploads for a given user

(time taken: 12 weeks)

**Milestone 3: Demo site**

- Implement demo site (e.g. niiifty.com) showing how the developed components can be used together.
- Write demo site documentation on how to use the next.js components in your application. Create a PR for the docs.ipfs.io How Tos section.

(time taken:  4 weeks)

## Total Budget Requested

Milestone 1: $6,000.00
Milestone 2: $36,000
Milestone 3: $12,000.00

**Total of $54,000.00** 

## Maintenance and Upgrade Plans

Potential paths forward for maintenance/upgrades will largely depend on uptake from the community and any further funded projects that emerge. It is our intention to promote NIIIFTY to this end. 

# Team

## Team Members

Edward Silverton 
[ed@mnemoscene.io](mailto:ed@mnemoscene.io)
[Github profile](https://github.com/edsilv)

## Team Member LinkedIn Profiles

[Edward Silverton’s Linkedin profile](https://www.linkedin.com/in/edsilv/)

## Team Website

[Mnemoscene](https://mnemoscene.io/)

## Relevant Experience

[Edward Silverton](https://twitter.com/edsilv) is a full stack web developer with 20 years of experience, 10+ years of which working with galleries, libraries, archives, and museums. He is experienced in IPFS, nodejs, nextjs, tailwind css, and firebase, is the lead developer of the [Universal Viewer](https://github.com/universalviewer) and [Exhibit](https://exhibit.so/), and is co-chair of the [IIIF 3D Technical Specification Group](https://iiif.io/community/groups/3d/tsg/). He presented at the 2018 [Internet Archive Decentralised Web Summit](https://decentralizedwebsummit2018.sched.com/speaker/e.silverton) on the subject of [P2P IIIF](https://docs.google.com/presentation/d/1vJtfzrIMvgiV9kYA8MwWk5KKVxTKfTeQMrs6SHVAI1s/edit?usp=sharing).

**Comment by ErinOCon** [comment]
Hi @edsilv, thank you for this proposal! We would like to fund the work outlined here. Please email [devgrants@fil.org](mailto:devgrants@fil.org) so we can discuss next steps.
