### ISSUE TITLE
Granular Energy Certificate 24/7 Project

### ISSUE THREAD

**Issue by CCEINC** [filecoin-project/devgrants#505]
Open Grant Proposal: `Granular Energy Certificate 24/7 Project`

Name of Project: Filecoin GC Solar Project

Proposal Category: `green`  Learn what these categories are here: {https://github.com/filecoin-project/devgrants/tree/master/open-grants}"

Proposer: `CCEINC`

(Optional) Technical Sponsor: `Alan Ransil`

Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Please respond with either "Yes"

Project Description

The solar farm project will provide a model/demonstrator for the widespread development and issuance of timestamp Granular Certificates or GC's for the cryptocurrency and blockchain technology industry. Granular Energy Certificates can be used to harness rising consumer demand for carbon-free energy and to drive investments in the technologies needed, such as energy storage, green energy usage and to eliminate dependence on fossil fuels usages. The project will help to solve the problem around timestamp GC's by working with other stakeholders to develop a handbook as a model for other projects that want to integrate GC's into their project.

This section should be 2-3 paragraphs long.

Value

Please describe in more detail why this proposal is valuable for the Filecoin ecosystem. The project is valuable because of hourly procurement of REC/EAC could incentivize consumers, large companies and energy users to access which clean energy resources are best suited to match their demand.

What are the benefits to getting this right? By getting this right Filecoin would be one of the leading companies in the blockchain technology storage space to provide a much needed product and be on the cutting edge to provide these GC's to the masses already participating within the Filecoin storage systems.

What are the risks if you don't get it right? Once the project has been funded the risk are very minimum, because it will be just a matter of time until a truly and reliable infrastructure is in place that will be able to provide the timestamp data needed for standardized GC's according to Energy Tag guidelines.

What are the risks that will make executing on this project difficult? The risk is that this project may not be equipped with the correct inverters according to Jason at blockchain laboratory. If not the project would need to be upgraded to the correct inverters. We are currently working to discover if we need to upgrade.

This section should be 1-3 paragraphs long.

Deliverables

Please describe in details what your final deliverable for this project will be. Include a specification of the project and what functionality the software will deliver when it is finished

Development Roadmap

This section should be 1-3 paragraphs long.

Deliverables

Please describe in details what your final deliverable for this project will be. Include a specification of the project and what functionality the software will deliver when it is finished

The Filecoin GC Solar Project will help deliver and support the development of a system of standards of Granular Energy Certificates (GC) that will keep track of the time of energy production with hourly granularity (down to 15 minutes or less) from generation according to the EnergyTag initiative. Enabling crypto and blockchain investors, mining companies and environmental friendly customers to link energy use estimates of their fossil fuel energy consumptions with clean energy procurement.

·         Filecoin will be on the cutting edge to be recognized as a founding sponsor and supporter in Georgia as a leader in establishing timestamp Granular Energy Certificates to its clients.

·         Filecoin will have the option through Crystal Clear Energy to have its GC's green-e certified and retired on behalf of its clients.

·         The final deliverable of this project is for Filecoin to receive on an annual basis half of the REC/EAC that it will produce up to 10 years the project is in operation. The project is estimated to produce between 2200-2500 REC/EAC per year.

Development Roadmap

Please break up your development work into a clear set of milestones. This section needs to be very detailed (will vary on the project, but aim for around 2 pages for this section). -->

For each milestone, please describe: -->

Milestone 1

Submit an offer on March 28, 2022 to purchase the solar farm project located at parcel # 004919202 Mineral Bluff GA 30559. Requirements of the purchase contract will include the following:

The seller will provide the buyer any and all assets, equipment, etc. which includes a 200kw solar farm and any other property that is free of liens that is associated with the subject property.

The seller agree to give the buyer any and all environmental attributes (RECs) that is associated with the property on and after the property is sold to the buyer. If the buyer have an agreement in place with another entity involving the environmental attributes (REC's) the seller agree to have the environmental attributes agreement terminated according to the TVA agreement section 2.2  term and termination.

Offer accepted, with a 6-week closing date from the original offer as of 3/28/22. If all requirements can be met with buyer and funders satisfaction.

People Involved

·         Julius Webb, Crystal Clear Energy, Inc. Buyer/owner. Julius Webb is a Georgia license real estate broker will prepare to offer to the seller to acquire the solar farm from the seller.

·         Jim Dye, Sun Farm LLC, Seller

·         Douglas Price, Real Estate Closing Attorney

Funding Requirement

·         $171,000 grant award

·         $50,000 Crystal Clear Energy Inc.

Timeline

·        Expected May 9, 2022 

The execution of Milestone 1 is the most important milestone because it sets the stage to be a model for similar GC projects to emulate in Georgia and across the southeastern coast.

Milestone 2

Upgrade to Revenue Grade Metering

The Filecoin GC Solar Project will need to be upgraded to accommodate Revenue Grade Metering (RMG) which is needed to record timestamp monitoring. On-site, the array is metered with a physical meter and we will need a smart IoT device to report from.

Estimated cost to add RGM accuracy to an inverter already reporting on generation is around $3000 per inverter. The project is estimated to have 28 inverters which will include any permitting if needed.  

People Involved

·         Julius Webb, Crystal Clear Energy, Inc. Buyer/owner will work with a qualified electrical contractor to install the equipment needed for RGM.

·         Hired Experience Electrical Contractor

Funding Requirement

·         $84,000 grant award

Timeline

·        Expected July 1, 2022 

Milestone 3

API Documentation

Collecting API data is very important to GC’s timestamp documentation and functionality. It is an opportunity to train and educate GC project developers.

People Involved

·         Julius Webb, Crystal Clear Energy, Inc.

·         Crystal Clear Energy Inc. will work closely with the Blockchain Laboratories Team to make sure that our solar project have a successful implementation in on-boarding verified GC's from small solar array projects and make it available to the crypto space.  

Total Budget Requested - $255,000

Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds. -->

$221.000 to be used to purchase solar farm project.

$84,000 to be used to upgrade the solar project to provide timestamp GC’s.

Maintenance and Upgrade Plans

Specify your team's long-term plans to maintain this software and upgrade it over time. -->

Crystal Clean Energy, Inc is the owner of the solar farm and will hire qualified maintenance and electrical contractors to maintain the property and provide any upgrades as needed throughout the remaining lifetime of the solar farm project.

Team

Team Member

·         Julius Webb

·         Will collaborate closely with Blockchain Laboratories, EnergyTag and M-RETS

We believe that as we grow in this solar space to provide GC’s to clients, our team will be built on expertise and will be open to anyone who have a desire to help environmental conscience clients obtain their green initiative goals.  

Team Member LinkedIn Profiles

https://www.linkedin.com/in/julius-webb-12b606133/

Team Website

https://www.greenenergytokens.com/

Relevant Experience

Julius Webb is an entrepreneur and a self-starter and motivator and possesses leadership abilities, teamwork, and has over 15 years of personnel management experience in the for profit the nonprofit sector; is familiar with budgeting, and business administration, and has a strong background in nonprofit fundraising. He possesses enthusiasm, energy, and a high level of knowledge in business management with a profound interest and enthusiastic in renewable energy resources with the desire to want to help our communities at large.

He is the founder of Crystal Clear Energy Inc. that was founded in 2021 as a renewable energy resource company for the cryptocurrency industry with a visionary goal: To bring decentralized renewable energy resources to crypto mining and large institutional transaction networks, which operates on the Ethereum blockchain ERC-20. Most non-fungible tokens are built using the ERC-721 and ERC-1155 standards, which allow developers to issue unique crypto assets via smart contract. The company goal is to tokenize REC/EAC and carbon offsets and invest in renewable energy infrastructure projects in the United States with emphasis globally.

Team code repositories

Please provide links to your team's prior code repos for similar or related projects. -->

Additional Information

Additional Information will be provided upon request.

**Comment by ErinOCon** [comment]
Hi @CCEINC, Thank you for your time with the submitted proposal! While the scope of the outlined work is currently not the best fit for our grant program, we would be interested to learn of future progress. Wishing you and your team success with this project!
