### ISSUE TITLE
Next Step Microgrant: Musing

### ISSUE THREAD

**Issue by jonching** [filecoin-project/devgrants#506]
### 1. What is your project? (max 100 words)
Musing is a platform for metaverse communities where users can post interesting or funny content and mine tokens for it. Every community on Musing has its own token that users can earn by helping the communities grow. You can think of it as a metaverse Reddit, but where the user owns his content, and where virtual communities can for the first time have economics.

[
](https://github.com/Musing-io/musing-protocol)
  
[
](https://musing.io/)

### 2. How are you planning to improve this project? (max 200 words)
Musing is currently just for Q&A content. We want to expand to all forms of content and focus on the bigger picture of building metaverse communities. We want to add assets to the project that users can purchase with their earned tokens and also want to create our own subnet on Avalanche. And we're looking to focus also on creating amazing content on our platform.
 
### 3. Will the work be Open Source?
Our smart contracts are already open source.

Here is the frontend portion of code that submits content to IPFS: https://github.com/Musing-io/musing-hackathon

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes.

### 6. Links and submissions
We won 1st place ($100k) at the Avalanche x Moralis Hackathon.
  
### Additional questions:
Jon Ching - jon@musing.io - CEO
Mhykl Nieves - mhykl@musing.io - COO
Mervin Villaceran - mervin@musing.io - Lead Engineer

The hackathon we did was Avalanche x Moralis Hackathon

Our presentation is here: https://youtu.be/8fnzkkj2eBw?t=4953

**Comment by ErinOCon** [comment]
Hi @jonching, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
@jonching, thank you again for your submission! Once the active work for this microgrant is open-source, we can proceed with approval. If/when this is the case, please update item 3 of this proposal. 

Please do not hesitate to reach out with any questions!

**Comment by jonching** [comment]
Hey @ErinOCon, I updated item 3 with the frontend source code. Not sure if this counts, but it's a portion of our codebase that uses IPFS.

**Comment by ErinOCon** [comment]
Thanks for the additional detail, @jonching! We would like to understand fully before proceeding, as this is an important piece of criteria. Is it correct that the portion of work covered by this grant would be open source?  

Let me know of questions!

**Comment by ErinOCon** [comment]
Hi @jonching, Do you have an update available? If all work funded by this grant is open source, we can proceed with approval. Please let me know of questions!

**Comment by ErinOCon** [comment]
Hi @jonching, this Issue has been closed. Please feel welcome to re-submit your proposal once the portion of work covered by this microgrant is fully open source. Thank you for considering our grant program to support your project!
