### ISSUE TITLE
Buddy Beater Games 

### ISSUE THREAD

**Issue by lDEADl** [filecoin-project/devgrants#507]
# Open Grant Proposal: Buddy Beater Game

**Name of Project:** Buddy Beater

**Proposal Category:** `app-dev`

**Proposer:** `lDEADl`

**(Optional) Technical Sponsor:** `Pan Chasinga`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** "No"

# Project Description

Buddy beater is a 2D comedic battle royale real-time multiplayer game on Etherium Chain with NFT avatar and items with the concept of "If it a game, It must be fun". The project is on going and planned release to be May 2022.
Gamefi industry is flooded with solo player games designed to have a lot of idle time which is not encourage community building which conflicted with community driven nature of Dapp. Most game designed to be focused on earning than the game itself with tokenomics that mostly proved to be not sustainable and in some case, devastating.
Aside from being high quality NFT, Buddy beater NFT avatar have a real-life benefit from generous partner. The NFT can be traded in market place as a game items or art collection.
Buddy beater designed to be real time multiplayer to drive community building which is the beating heart of most Dapp projects. Multiplayer games nature make players interact and exchange information. It make community grows and strong.
The tokenomic of the Buddy beater designed to be destinated by players only. Game token is fairy distributed and its value determined by only player and can be earned via playing the games only. Game token can be spent for buying in game NFT items.
In conclusion, Buddy beater is games on blockchain designed to be sustain and to be more "game" than to be a financial tools.

## Value
This project has the potential to be sustain way future of gamefi/NFT  game implementation which directly involve with Filecoin/IPFS ecosystem. the more sustain the game is, the more secured and transparent it needs and that's what Filecoin can provide. 

##Risk
This is an ambitious project to offer a new model for gamfi industry. Success of the project not only depends upon the quality of product but also to educate people about how the proposed concept works.

## Deliverables

The final product is Buddy Beater game with real-time multiplayer functionality. 

## Development Roadmap
| Mile Stone        | Start - Finish Date             | Deliverable  |Budget  |
| ------------- |:-------------:|:-----|:------:|
| Conceptual Design    |15/12/21 - 10/12/21  | <ul><li>Game Design Document</li><li>Tokenomic conceptual design</li><li>Art work conceptual design</li></ul>|-|
| Game Core Development    | 17/01/22 - 18/04/22 |<ul><li>Game with full function including SFX/VFX</li></ul>|$71,000|
| Art Work Production    | 10/01/22 - 18/04/22 |<ul><li>Avatar & item Art</li></ul>|$20,000|
| Block Chain API Development|26/01/22 - 8/04/22 |<ul><li>Smart contracts</li><li>API to interact with smart contract</li></ul>|$10,000|
|Marketing|17/01/22 - 12/05/22|<ul><li>More than 8k whitelist registration</li>|$40,000|
| Play Testing and Optimization|19/04/22 - 12/05/22     |<ul><li>Optimized and Bug free Game</li>|$10,000|
| Official Luach|13/5/22 |     |-|

## Total Budget Requested
$151,000
The budget allocation is as milestone above. Majority distributed to Development team and Marketing.

## Maintenance and Upgrade Plans
Buddy Beater will be maintain by the Team while new play mode is being developed.

# Team

## Team Members
Project Manager: [lDEADl](https://github.com/lDEADl)
Lead Developer: [LastRaven13](https://github.com/LastRaven13)
Developer Team : 
[alekporkchop](https://github.com/alekporkchop)
[Trissiklikk Anak Ladachat](https://github.com/Trissiklikk)
[Rapizz1112 PP Nuttapan](https://github.com/Rapizz1112)
[nail462438 Nagasuki](https://github.com/nail462438)

## Team Website
https://cointalk.co.th/

## Relevant Experience
Team have experience in various field that need to develop project. Developer, Game Developer, Project Management, IT infrastructure, Marketing, Organization Consulting.

# Additional Information
The game website link : https://buddybeater.io/

**Comment by ErinOCon** [comment]
Hi @lDEADl , Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
Hi @lDEADl, we believe your work may be a great fit for an accelerator program! If you have a preferred email address to share, I can connect you with a member of our team to discuss.

**Comment by lDEADl** [comment]
Hi @ErinOCon Glad to hear your response. Could you please sent me the detail about the program and advise how to proceed. You can contact me via apinat.sa@cointalk.co.th
Thank you

**Comment by ErinOCon** [comment]
Thanks @lDEADI, We've reached out by email to discuss further!
