### ISSUE TITLE
Next Step Microgrant: <Your Meta World>

### ISSUE THREAD

**Issue by xx014939** [filecoin-project/devgrants#508]
### 1. What is your project? (max 100 words)

Your Meta World recently won one of the top three IPFS/Filecoin prizes at the Moralis 2022 hackathon. The project is a truly decentralised Metaverse, which empowers users to build, create and collaborate in their very own 3D VR traversable digital space. We rely heavily on IPFS and NFT Storage to store and access our 3D NFT's and their Meta Data.

https://github.com/xx014939/metaworld-landing

https://github.com/xx014939/unity-code-scripts

https://github.com/xx014939/Netlify-Market
  

https://yourmetaworld.org/

### 2. How are you planning to improve this project? (max 200 words)

This project has a large scope, however I have decided to break this down into smaller goals to tackle one at a time. For this particular micro grant, I would like to build significantly on the 3D NFT minting functionality.

Currently users can lazy mint a 3D GLTF object, and then interact with this object inside of VR using our Unity application with their Metamask wallet.

I would like to extend this functionality, to provide users with a basic Unity scene which they can then modify and build upon. This Unity scene can then be minted as an NFT, and pulled into their Meta World. This will allow users to not just create and mint 3D objects as NFT's (using IPFS for storage), but also create and mint 3D, dynamic and interactable environments as NFT's. These environments can be used by the creator inside of the Unity application, or sold on the marketplace to another wallet who can spin it up in their account.

Environments may be social hangouts, event based venues (VR cinema, networking hall etc.), or even indie games created by amateur game devs.
 
### 3. Will the work be Open Source?

Yes this work will be open source, via MIT license.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes of course
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

Yes, I submitted my project into the Moralis 2022 hackathon - https://moralis.io/hackathon-prizes/

My project won the top three prize for "Best Use of IPFS or NFT.Storage for Content-Addressed Data"
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Name: Naail El-Sawah
Email: naailelsawah@gmail.com
Github: xx014939
Role: Sole Team Member

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
Moralis Avalanche Hackathon
  * Please link to your hackathon submission
https://yourmetaworld.org/

**Comment by ErinOCon** [comment]
Hi @xx014939, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
Hi @xx014939, thank you again for your submission! Our [microgrant criteria ](https://github.com/filecoin-project/devgrants/blob/master/microgrants/microgrants.md) requires all work be open-source. If you are able to proceed with open-source via MIT license, please update item 3 of this proposal. 

If/once completed, we can proceed with approval!

**Comment by xx014939** [comment]
Thanks very much @ErinOCon! I have updated this now.

**Comment by ErinOCon** [comment]
Hi @xx014939, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by xx014939** [comment]
Hey @ErinOCon, I have compiled this work into a single open source GitHub Repo now. Please view here --> https://github.com/xx014939/IPFS-Unity-Scene-Minter
