### ISSUE TITLE
Next Step Microgrant: Polyecho

### ISSUE THREAD

**Issue by drewcook** [filecoin-project/devgrants#512]
### 1. What is your project?

Polyecho is a music NFT collaboration protocol where artists co-create songs layer-by-layer until a collector purchases the song as an NFT. Upon purchase, the proceeds from the initial sale price are distributed evenly to the collaborating artists, including future royalties from resales on secondary markets.

- We’re storing NFT metadata.json files and audio files as blobs on IPFS using NFT.storage.
- Allow users to create new projects and upload stems to be stored on IPFS to contribute to them
- Allow projects to be minted as audio NFTs, where we create metadata and store on IPFS

Github: [Link](https://github.com/polyecho)

App demo: [Link](https://polyecho.xyz/)

Video demo: [Link](https://www.youtube.com/watch?v=conSFwNW3Ok&ab_channel=Polyecho)

### 2. How are you planning to improve this project?

Our overall effort is focused around incentivizing a closed alpha to refine our overall UX, start building out a community, and outreach to foster relationships with Web3 artists.

**Technical Feats**

- Handle audio file muxing in-browser with WASM, instead of over the network in a service
- Swap out to using WalletConnect and ensure seamless mobile experience for connecting
- Roll out logging to a database table for our production and staging environments
- Handling a few known UI bugs and improving the overall UX

**Community Feats**

- Start our closed alpha where artists can begin testing and creatively experimenting with our app
- Use a portion of grant money to incentivize artists to create full songs
- Use feedback to refine UI/UX and protocol spec

### 3. Will the work be Open Source?

Yes, all Polyecho code is published under GNU General Public License v3.0.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes.

### 5. Does your proposal comply with our Community Code of Conduct?

Yes.

### 6. Links and submissions

- If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
    
    Polyecho began at the ETHDenver IRL hackathon. [Project Link](https://dorahacks.io/buidl/2059)
    
    We submitted for the in-person and virtual hackathon, winning several prizes in both, including for IPFS / Filecoin.
    
    - In-person prizes: [1st Place Bounty Winner for IPFS/Filecoin](https://twitter.com/Filecoin/status/1501013407205519361)
    - Virtual prizes: [Top 30 overall and winner of Celebrity Judge Favorite bonus (1 of 5)](https://www.ethdenver.com/virtual-winners)

### Additional questions:

- For each team member(s), please list name, email, Github account, and role in the project.
    
    **Drew Cook**
    
    *Software Development*
    
    Github: [@drewcook](https://github.com/drewcook)
    
    Twitter: [@dcodev_](https://twitter.com/dcodev_)
    
    Discord: dco.dev#7839
    
    **Jack Gane**
    
    *Design & Marketing*
    
    Github: [ganejacks](https://github.com/ganejacks)
    
    Twitter: [@jackg808](https://twitter.com/jackg808)
    
    Discord: Jack G#7167
    
    **Noah Dahlman**
    
    ***Software Development***
    
    Github: [@noah_dahlman](https://github.com/noahdahlman)
    
    Twitter: [@noah_dahlman](https://twitter.com/noah_dahlman)
    
    Discord: AngeredZeus#7850

* If your project was created as part of an event or hackathon: ETHDenver 2022 
* Please link to your hackathon submission: [Link Here](https://dorahacks.io/buidl/2059)

**Comment by ErinOCon** [comment]
Hi @drewcook, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
Hi @drewcook, This microgrant has been approved! Look out for an email to submit payment details.
