### ISSUE TITLE
Next Step Microgrant:  LINKE

### ISSUE THREAD

**Issue by 1Busayo** [filecoin-project/devgrants#513]
### 1. What is your project? (max 100 words)

LINKE is a decentralized social network similar to the insatgram in which the backend is built with a solidity smart contract, the front end is built with reactjs  ,web3js, and images are been stored on IPFS. web3 made use of the ABI file to communicate with the solidity smart contract.IPFS made it easier to store images and records without using a database

  https://github.com/1Busayo/LINKE
  

### 2. How are you planning to improve this project? (max 200 words)

Am currently working on a new UI/UX design, 
I would be able to Launch a demo website, then also add new features like,
web3.0 auth, 
wallet address would be mapped to the username stored IPFS,
users to retrieve their collection of data from IPFS.

 
### 3. Will the work be Open Source?

source code would be open source and the latest commits would be available on Github

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes I would share weekly updates

### 5. Does your proposal comply with our Community Code of Conduct? 
Yes it complies

### 6. Links and submissions

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://showcase.ethglobal.com/nfthack2022/linke

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
name: Samuel Fanimokun
email: fanimokunbusayo@gmail.com
Github account: https://github.com/1Busayo

* If your project was created as part of an event or hackathon: 
hackthon
  * What was the name of the event?   (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) 
  ETHGlobal NFTHack

  * Please link to your hackathon submission
https://showcase.ethglobal.com/nfthack2022/linke

**Comment by ErinOCon** [comment]
Hi @1Busayo, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
Hi @1Busayo, would the work we would be funding be open source? Thanks!

**Comment by 1Busayo** [comment]
hello @ErinOCon , the project would be open source

**Comment by ErinOCon** [comment]
Thanks @1Busayo! This microgrant has been approved. Look out for an email to submit payment details.

**Comment by 1Busayo** [comment]
i submitted my details on the request portal but it got rejected

**Comment by ErinOCon** [comment]
Hi @1Busayo, thank you for being in touch! I will review further and will respond to your latest email.

**Comment by 1Busayo** [comment]
@ErinOCon  thanks have completed the final report for LINKE

**Comment by ErinOCon** [comment]
Hi @1Busayo, thank you for the submitted report! Can you point to the code built during the timeframe of this grant?

**Comment by 1Busayo** [comment]
@ErinOCon during the time frame of this grant I worked on version 2.0. please click the link to see the code that was written https://github.com/1Busayo/LINKE/tree/V2.0/linke.
visit this  link  to compare the changes on the code  to https://github.com/1Busayo/LINKE/compare/master...V2.0
