### ISSUE TITLE
Next Step Microgrant: <Daccred>

### ISSUE THREAD

**Issue by koolamusic** [filecoin-project/devgrants#514]
### 1. What is your project? (max 100 words)
Daccred is a No-code POAP (Proof of Attendance Protocol) and POKP (Proof of Knowledge Protocol) Platform where DAOs, communities and institutions can issue on-chain NFT enabled Badges and certificates. All Certificate metadata are hosted on IPFS through the Web3.Storage client.

We are recipients of the NFT Hack hackathon sponsored by ETHGlobal.

https://github.com/daccred
  

https://daccred.co

### 2. How are you planning to improve this project? (max 200 words)
We are already revamping the UX to make it easier to manage and publish certificates. See here https://twitter.com/daccred/status/1504812925156007960

### 3. Will the work be Open Source?
All of our work is opensource

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
https://showcase.ethglobal.com/nfthack2022/accred-badges

### Additional questions:

* For each team member(s), please list name, email, Github account, and role in the project.
U.M Andrew (Team Lead)
andrew@daccred.co
@koolamusic

* If your project was created as part of an event or hackathon:
  ETHGlobal NFTHack
  * Please link to your hackathon submission
  * https://showcase.ethglobal.com/nfthack2022/accred-badges

**Comment by ErinOCon** [comment]
Hi @koolamusic, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
Hi @koolamusic, This microgrant has been approved! Look out for an email to submit payment details.
