### ISSUE TITLE
Next Step Microgrant: Musomatic

### ISSUE THREAD

**Issue by Pushpit07** [filecoin-project/devgrants#515]
### 1. What is your project? (max 100 words)
Musomatic is an NFT marketplace for musicians and fans. Musomatic aims to uplift musicians by enabling them to create NFTs of their music and provide them with royalties and recognition that they deserve.

Musomatic aims to connect artists and fans like never before. Artists can generate money instantly and directly from fans without anyone in between. Fans can connect directly with their favorite artists. They can support artists and invest in assets that could increase in value with time. Musomatic also aims to enable talent discovery by creating an efficient marketplace and providing tools to propel growth.

Musomatic makes use of IPFS to store all kind of files ranging from images used in Song covers to profile pictures. We also store the mp3 files of the song on IPFS.

Link to Github repo: https://github.com/Pushpit07/Musomatic
  
Link to website: https://musomatic.vercel.app/

Link to demo: https://youtu.be/Qln_Tx7yQ7w

Hackathon submission: https://devfolio.co/submissions/musomatic-cf6f

### 2. How are you planning to improve this project? (max 200 words)
We’re planning to add multiple features to improve this project:

- Auction based system
- Improve the UI/UX of the platform
- Royalty distribution to artists (Split ownership)
- Multi-Copy NFTs (ERC1155)
- Initial NFT Staging Area
- Unlockable content
- Multichain support
- Migrating to Moralis
- Marketing the product
 
### 3. Will the work be Open Source?

Yes, it will be MIT.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes.
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes.

### 6. Links and submissions
- Winner at Polygon BUIDL IT 2021 hackathon in NFT & Gaming Track and Filecoin Track: [[Link to the submission](https://devfolio.co/submissions/musomatic-cf6f)](https://devfolio.co/submissions/musomatic-cf6f)
- Project added to the Protocol Lab’s Hall of Fame. Waiting to be accepted.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

- Musomatic was developed at Polygon BUIDL IT 2021 hackathon.
- [Link to the submission](https://devfolio.co/submissions/musomatic-cf6f)
- [Link to the live website](https://musomatic.vercel.app/)
- Team Members:
    1. **Name:** Pushpit Bhardwaj
    **Email:** [pushpit07@gmail.com](mailto:pushpit07@gmail.com)[](https://github.com/Pushpit07)
    **GitHub Account:** [https://github.com/Pushpit07](https://github.com/Pushpit07)
    **Role in the Project:** Smart Contracts Development, Front End Development, and Back End Development.
    2. **Name:** Yuvraj Chandra
    **Email:** [singhyuvraj179@gmail.com](mailto:singhyuvraj179@gmail.com)[](https://github.com/Yuvrajchandra)
    **GitHub Account:** [https://github.com/Yuvrajchandra](https://github.com/Yuvrajchandra)
    **Role in the project:** Product Management and Content Writing
    3. **Name:** Sparsh Sharma
    **Email:** [sparsh.sharma2510@gmail.com](mailto:sparsh.sharma2510@gmail.com)[](https://github.com/sparshsharma2510)
    **GitHub Account:** [https://github.com/sparshsharma2510](https://github.com/sparshsharma2510)
    **Role in the project:** Front End Development
    4. **Name:** Shivam Singh
    **Email:** [shivamsinghc502@gmail.com](mailto:shivamsinghc502@gmail.com)[](https://github.com/Shivamsingh-c17)
    **GitHub Account:** [https://github.com/Shivamsingh-c17](https://github.com/Shivamsingh-c17)
    **Role in the project:** Designing
    5. **Name:** Ayush Gupta
    **Email:** [[ayushgupta747492@gmail.com](mailto:ayushgupta747492@gmail.com)[](https://github.com/ayushgupta0110)](mailto:ayushgupta747492@gmail.com)
    **GitHub Account:** [https://github.com/ayushgupta0110](https://github.com/ayushgupta0110)
    **Role in the project:** Front End Development

**Comment by ErinOCon** [comment]
Hi @Pushpit07, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
Hi @Pushpit07, This microgrant has been approved! Look out for an email to submit payment details.
