### ISSUE TITLE
Odyssey DAO - Quality Web3 Education

### ISSUE THREAD

**Issue by mltan4** [filecoin-project/devgrants#516]
## **About**

We're creating quality web3 education to onboard the next 1 million people to web3. Check out our learning paths and articles: 

https://www.odysseydao.com/

![https://c.gitcoin.co/docs/7c2dd8ee8a574dfb4a5e868ddf184977/Gitcoin.png](https://c.gitcoin.co/docs/7c2dd8ee8a574dfb4a5e868ddf184977/Gitcoin.png)

## What problem are we trying to solve

Onboarding talent using easy-to-understand content is key to mass adoption. Our values include have proven to be effective in bringing people onboard into web3: 

1. Quality over quantity
We value creating high quality, 100% free web3 education.
2. Delightful Onboarding
We value delightful guided web3 onramps. No member should feel lost on what to do next.
3. Pay it forward
We value giving more than taking. No member should have to learn web3 alone.

## **What we've achieved so far**

Since our launch in December 2021, we have:

1. Won Product Hunt's [Best Education Product of 2021](https://www.producthunt.com/stories/announcing-the-golden-kitty-awards-2021-winners)
2. Launched free [[Intro to Web3](https://www.odysseydao.com/pathways/intro-to-web3)], [[NFT](https://www.odysseydao.com/pathways/nft)], [[DeFi](https://www.odysseydao.com/pathways/defi)], and [[DAO](https://www.odysseydao.com/pathways/dao)] learning paths
3. Localized to at least 10 native languages
4. Launched [[people of web3](https://www.odysseydao.com/people-of-web3)] and [[web3 company](https://www.odysseydao.com/web3-companies)] profiles
5. Landed top web3 partners such as [[Polygon](https://polygon.technology/)](https://polygon.technology/), [[Thirdweb](https://www.odysseydao.com/companies/thirdweb)], [[Phantom](https://www.odysseydao.com/companies/phantom)], and [[Aave](https://aave.com/)](https://aave.com/)
6. Led events and workshops such as [[build a web3 career](https://twitter.com/petergyang/status/1496531571184078853?s=20&t=hyY-j1dKFr3NTyzGGJoBdw)], [[no-code NFT drops](https://lu.ma/evr9s4ze)], and [[future of wallets](https://twitter.com/odyssey_dao/status/1504485793594634244)].

![https://c.gitcoin.co/docs/2e0257b309225442f9c5a38ef342f04a/image_1518_1.png](https://c.gitcoin.co/docs/2e0257b309225442f9c5a38ef342f04a/image_1518_1.png)

## **Our team**

Odyssey's core team includes:

- [[Peter](https://twitter.com/petergyang)], Content Lead. *Product Lead @ Reddit, Ex-Twitch, Meta.*
- [[Mark](https://twitter.com/marktanft)], Community Lead. *On Deck, Ex-Amazon.*
- [[Louie](https://twitter.com/louiesakoda)], Product Lead
- [[Wenda](https://twitter.com/wendalewis)], Product Lead

Plus 20+ amazing core contributors in our DAO who are working on writing learning guides, growing the community, and localizing our content.

## **Our Community**

- Developers - 19%
- Product Managers - 17%
- Design - 8%
- Growth - 15%
- Community - 20%
- Founders - 11%
- Investors - 10%

![Screen Shot 2022-03-29 at 10.17.51 PM.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/62fe6e02-a744-4c7f-9196-79d5d9368821/Screen_Shot_2022-03-29_at_10.17.51_PM.png)

## Deliverables

We are creating more learning paths, protocols, and platform tutorials to help onboard people. We are also working on localized technical and non-technical education and tutorials in native languages. 

1. Content guide that will be published on our site and for public goods. Showcase the potential of technology and add use cases on how to get started
2. Dedicated page, a placement on the landing page, and web3 companies
3. Add a profile under people of web3
4. Promotion on social and email our newsletter subscribers (12k+)
5. Option to do an event or community workshop to increase awareness of the product
6. Option to localized technical and non-technical education and tutorials including Chinese, Italian, Spanish, Russian, Japanese, Portuguese, and German

## Timeline

Target to complete the content, dedicated page, people of web3, and promotion, and event and workshop within 30 days of grant approval. 

## Success Metrics

For the first 30 days upon grant approval, here are some metrics for the base partnership via content and events:

1. 20k user views on our site 
2. 50k Impressions on social
3. 12k email subscribers reached
4. 100 event attendees

Given the permanent placement, the page visits will increase over time as we build more educational content, translate into multiple languages, and use different educational formats.

## Funding Request

We are open to both short to long-term partnership initiatives.

- $10k for content, placement, and events, breakdown in deliverables section
- $50k for growing talent network and/or training bootcamps
- $100k for learn-to-earn initiatives

## **What will we use the funds for?**

We'll use the funds to pay our contributors who are:

1. Expanding our written 100% free web3 learning guides
2. Building an on-demand web3 course
3. Building a learn to earn quest with NFT rewards
4. Building our inaugural cohort-based bootcamp
5. Building our talent collective and job boards
6. University student clubs: Reach out to support student groups worldwide to build the blockchain education programs and curriculum they want according to their needs
7. Expand language translation into more locales

We have big things coming this year and we need all your support to help us fulfill our mission to be one of the best web3 learning communities on the web. Thank you for your support and drop by [[our community](https://discord.com/invite/82Ybt6BCFg)](https://discord.com/invite/82Ybt6BCFg) to let us know if you have more questions!

**Comment by mltan4** [comment]
Thank you Eric! Happy to adjust the scope based on what works for both groups. Look forward to hearing from your team.

**Comment by ErinOCon** [comment]
Hi @mltan4, we would like to fund part of the outlined work! Please email [devgrants@fil.org](mailto:devgrants@fil.org) to discuss next steps.

**Comment by ErinOCon** [comment]
Hi @mltan4, I have sent an email with next steps regarding the grant. We look forward to hearing for you!
