### ISSUE TITLE
Open Grant Proposal: Third Storage

### ISSUE THREAD

**Issue by hackyguru** [filecoin-project/devgrants#518]
# Open Grant Proposal: `Third Storage`

**Name of Project:** `Third Storage`

**Proposal Category:** `devtools-libraries`
**Proposer:** `thirdstorage`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes

# Project Description

**The problem**
- Data storage is the most crucial aspect of web3 dApps. Most of the so-called dApps use ‘wallet sign in’ as the authentication method but end up using centralized storage providers to store the user data - voiding the whole concept of decentralization and distributed storage. 

- The user data is not censorship-resistant and can be tampered by the centralized stakeholders. Additionally, the user's privacy is also at risk as all the user data is custodial in a centralized storage location.

- There are no efficient tools that help developers in implementing decentralized user identity in their applications. User identities should be immutable.

![Problems](https://i.ibb.co/t2tjNfJ/tsp1.png)

**Solution offered by Third Storage**
- Third Storage is a decentralized storage paradigm for web 3.0 applications which value self-soverign data and decentralized identity.

- In other words, Third Storage is a decentralized Firebase which can help developers in seamlessly integrating different kinds of authentication, storage and indexing paradigms for dApps.

- Third Storage SDK will be available for most of the development frameworks by the upcoming months. With Third Storage SDK, developers can save a great amount of time by focussing on their idea and developing an MVP for their dApp in a matter of few hours.

![Solution](https://i.ibb.co/b5vzXnb/tsp2.png)

**Features offered**
Third Storage redefines serverless applications with the following features :

- Distributed and encrypted database powered by Filecoin
- Web3 authentication
- Distributed file storage
- Decentralized hosting with IPFS
- Prebuilt crypto payment gateways
- EVM and FVM functions with Smart contracts (similar to Cloud functions)
- Decentralized code repository for version control and collaboration
- Decentralized analytics
- ‘Staking’ based payments model (which means - you can just stake crypto to use the premium features of Third Storage without paying additional costs)

The detailed technical documentation can be found in our [Litepaper](http://localhost:3000/ThirdStorage-Litepaper.pdf).

## Value

**What are the benefits to getting this right?**
Third Storage can provide a great value proposition to the web3 development stack by **saving development time** and **organizing and reducing code**. The web3 devtooling has great scope and Third Storage can attract and inspire a lot of developers to use Filecoin as their choice of storage.

**What are the risks if you don't get it right?**
There are no direct risks if things don't go as expected. We wish to keep our packages open-source and welcoming for new contributors. However, in order to incentivize our product to the market - we have planned a set of marketting practices for more developers to get onboarded to our tool.

**Risk and success factors**
The most important factor for the success of this product is **consistency in development and maintanance*.

## Deliverables

The final product would be a web application (thirdstorage.com) and a wide range of SDKs that support different stacks like Node.js, Python, GoLang, Flutter etc.,

## Development Roadmap

**Milestone 1**
Specification : Developing the alpha version of the web application
Expected time : 3-4 weeks
Budget : 6000 USD

**Milestone 2**
Specification : Developing the alpha version of Node.js library
Expected time : 3-4 weeks
Budget : 6000 USD

**Milestone 3**
Specification : Deploying the alpha version for testing and fixing bugs
Expected time : 1-2 weeks
Budget : 500 USD

**Milestone 4**
Specification : Documentation and guides
Expected time : 3-4 weeks
Budget : 3000 USD

**Milestone 5**
Specification : Creating example projects and publishing tutorials
Expected time : 2-3 weeks
Budget : 3000 USD

**Milestone 6**
Specification : Maintaining and incentivizing the product
Expected time : 12 weeks
Budget : 10000 USD

![Roadmap](https://i.ibb.co/DpHqmTQ/tsp3.png)

## Total Budget Requested

Total budget requested : 28,500 USD

All expenses will go towards development costs. Please refer to the each milestone for the budget breakdown for each activity.

## Maintenance and Upgrade Plans

We are looking to setup a team consisting of experienced developers who can help in the maintanance of the product. The product has great scope and impact on the overall web3 devtooling eco-system and we look forward to add new functionalities and upgrade the product frequently. We are also exploring possiblities to create 'Third Storage DAO' which can help us in decision making and further roadmap of the product.

# Team

## Team Members

[Kumaraguru T](https://github.com/hackyguru) - Web3 developer with 4 years of coding experience.
[Mridula](https://www.linkedin.com/in/mridula-kalaiselvan-a627401a2/) - UI/UX Designer and front-end developer.
[Emma Thomas](https://www.linkedin.com/in/emma-thomas-4107411a2/) - Marketing.

## Team Website

Please feel free to check out our litepaper and other information at [thirdstorage.com](https://thirdstorage.com)

Twitter - [@thirdstorage](https://twitter.com/thirdstorage)
LinkedIn - [@thirdstorage](https://www.linkedin.com/company/thirdstorage/)
Github - [@thirdstorage](https://github.com/thirdstorage)
Email - team@thirdstorage.com

## Relevant Experience

We have a lot of experience in working and collaborating on different projects. We have won in multiple hackathons sponsored by FileCoin and IPFS. We are very much involved with web3 communities which we consider to be the primary platform to incentivize our product.

## Team code repositories

All the code will be opensourced on our [github organization](https://github.com/thirdstorage).

**Comment by ErinOCon** [comment]
Hi @hackyguru, We would like to fund the outlined work! Please email [devgrants@fil.org](mailto:devgrants@fil.org) to discuss next steps.

**Comment by hackyguru** [comment]
Hello @ErinOCon @realChainLife 

I was trying to reach out to your emails to update about the progress but unfortunately did not receive a response. We've completed all the milestones and it would be really helpful if you can assist us with the funds. 

We also made a [video demonstration of our MVP](https://youtu.be/beTzt2hxJCM) for you to review. The funds would be helpful in deploying the product and get things going  :)

**Comment by hackyguru** [comment]
@eshon Hi, following up on this

**Comment by hackyguru** [comment]
We're waiting for the funds to proceed further so that we can ship the product on the scheduled dates. Would be great if you can give us an update about this @eshon @realChainLife

**Comment by ErinOCon** [comment]
Hi @hackyguru, apologies for the significant delay. For some reason, we have not received notice from [team@thirdstorage.com](mailto:team@thirdstorage.com). I do see an update from your personal email. I will send details regarding next steps to this address.

**Comment by hackyguru** [comment]
No problem @ErinOCon :) Thanks for letting us know, we're looking forward for the next steps.

**Comment by ErinOCon** [comment]
Just sent!
