### ISSUE TITLE
Next Step Microgrant: React file upload wrapper on NFT.Storage - by The Mango Jelly

### ISSUE THREAD

**Issue by rkgudboy** [filecoin-project/devgrants#519]
### 1. What is your project? (max 100 words)

We are building a React wrapper for uploading files via a drag and drop functionality to IPFS/Filecoin using NFT.Storage service. It is an efficient solution for developers to implement a frequently required capability for uploading files to IPFS with a customizable and user-friendly experience.

[The Mango Jelly IPFS Project repo](https://github.com/rkgudboy/the-mango-jelly-ipfs)

[The Mango Jelly website](https://themangojelly.com/)

### 2. How are you planning to improve this project? (max 200 words)

The proposed module will be interacting with IPFS using NFT.Storage service.
And the offchain NFT data will be persisted on IPFS/Filecoin network using NFT.Storage service API "store" function.

#### Block Diagram

![The Mango Jelly - IPFS Project Block diagram](https://github.com/rkgudboy/the-mango-jelly-ipfs/blob/main/The%20Mango%20Jelly%20-%20IPFS.drawio%20(2).png?raw=true "The Mango Jelly - IPFS Project Block diagram")

#### On adding the package to react app:

- Developers can invoke a drag and drop supported React file input component to add it to their UI.
- The component will have configurable parameters like
    - ClassName - to supply any CSS class to be added onto UI component
    - Acceptable File formats - To specify supported file types on the file reader component
    - API Key - To specify NFT.Storage API Key
- On adding the file that is to be uploaded, store function call of NFT.Storage API will be made along with the supplied API Key to initiate the file upload process.
- After the file has been uploaded, the response object of success/failure received from NFT.Storage service will be made available to a handler function.
- Using the handler function developers will be able to read uploaded file address on IPFS/Filecoin network and implement their next steps, like using this IPFS address in minting NFTs.

 
### 3. Will the work be Open Source?

Yes

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

#### If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

Yes, we participated in NFTHack where we were building a functionality to mint content as NFTs. While adding the feature for our React app, we thought that it could be simplified as a wrapper to help other developers to quickly add the frequently required capability to upload files to IPFS with a customizable and user-friendly experience.
[The Mango jelly NFTHack showcase](https://showcase.ethglobal.com/nfthack2022/the-mango-jelly-nfthack)
  
#### For each team member(s), please list name, email, Github account, and role in the project.

* Rohit Kashyap
  [rohit@themangojelly.com](mailto:rohit@themangojelly.com)
  [Github](https://github.com/rkgudboy)
  Development

* Divya Upadhyay
  [divya@themangojelly.com](mailto:divya@themangojelly.com) 
  [Github](https://github.com/divyaupadhyay)
  Design

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum): ETHGlobal NFTHack
  * Please link to your hackathon submission: [The Mango jelly NFTHack submission](https://showcase.ethglobal.com/nfthack2022/the-mango-jelly-nfthack)

**Comment by ErinOCon** [comment]
Hi @rkgudboy, This microgrant has been approved! Look out for an email to submit payment details.
