### ISSUE TITLE
Next Step Microgrant: NFTickets

### ISSUE THREAD

**Issue by IKalonji** [filecoin-project/devgrants#520]
### 1. What is your project? (max 100 words)
The project combines the storage of a ticket in the form of a unique QR code which is stored on IPFS and redeemed on usage. The dapp has been build in it most simplest form for the hackathon. Process of usage: Contract is deployed, User logs in, adds a ticket to purchase, a ticket is then created and stored (IPFS), and then the ticket is burnt when used/presented.

[Repository](https://github.com/IKalonji/NFTickets)
  
[Demo](https://youtu.be/CjuSR8LEyws)

### 2. How are you planning to improve this project? (max 200 words)
I will be building a smart contract for the platform since I initially used the generic NFTPort contract in order to facilitate ticket generation/burning. Build a listing frontend for organisers/transport authorities to interact with the contract so that tickets can be created and listed on the mobile ticketing dapp.
 
### 3. Will the work be Open Source?
The work will be Open Source under the MIT license for Open Source projects.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Should I be selected, I agree to weekly updates and grant report. 
  
### 5. Does your proposal comply with our Community Code of Conduct?
The project proposal complies with the Community Code of Conduct.

### 6. Links and submissions

[NFTHack-submission](https://showcase.ethglobal.com/nfthack2022/nftickets)
[Repository](https://github.com/IKalonji/NFTickets)
[Demo](https://youtu.be/CjuSR8LEyws)
  
### Additional questions:
Issa Kalonji
Email: IKalonji@student.wethinkcode.co.za
[LinkedIn](https://www.linkedin.com/in/issa-kalonji-b301851ba/)
[Github](https://www.github.com/IKalonji/)
[Twitter](https://twitter.com/ISSDawg/)

Submission was part of NFTHack, submission link:
https://showcase.ethglobal.com/nfthack2022/nftickets

**Comment by ErinOCon** [comment]
Hi @IKalonji, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by IKalonji** [comment]
Thank you.

**Comment by ErinOCon** [comment]
Hi @IKalonji, the final report for this project can be completed [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let me know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @IKalonji, thank you for your final repot. Can you point to the code that was built during the time of this grant?
