### ISSUE TITLE
Next Step Microgrant: <AVASOUND (Felix Prabitz)>

### ISSUE THREAD

**Issue by felixpx** [filecoin-project/devgrants#521]
### 1. What is your project? (max 100 words)
Avasound is a music Marketplace & Royalty Distribution Service on the Avalanche Network. Using IPFS to store music files and make them accessible to download for owners. Our Web2 Benchmarks are Bandcamp & Beatport and partially Soundcloud. Finalist at the Moralis x Avax Hackathon.

Github:
https://github.com/AVASOUND

DEMO:
- Live Demo MVP (looks bad currently but new UI/UX is in the works.):
https://avasound-nine.vercel.app/
(please connect to avax fuji testnet for testing)

- Moralis Avax Hackathon Finale Ceremony (Timestamp 2:11:50)
https://www.youtube.com/watch?v=8fnzkkj2eBw

### 2. How are you planning to improve this project? (max 200 words)

* Improvement on Userexperience / Interface as we are targeting an audience partially not yet in the blockchain space. 
* Improvements specifically on the IPFS end: Uploading and organizing products, encryption of files (potentially via LIT)
* Legal Advisory for music & terms of agreements
 
### 3. Will the work be Open Source?

Not yet decided but for the most part probably yes. 

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes we definitely want to share weekly updates to also push ourselves with the process of getting where we want the project to get. Previous experience with working on Filecoin / IPFS was great. We did a lot of other hackathons to learn more about the product and its been good so far. 
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
We won a little under 200$ as pool price for AVAX & MORALIS Hackathon. Funds have been received a few days ago. No other support or grant has been given to the project as of now. 
Submission Links above, but here again: 

DEMO:
- Live Demo MVP (looks bad currently but new UI/UX is in the works.):
https://avasound-nine.vercel.app/
(please connect to avax fuji testnet for testing)

- Moralis Avax Hackathon Finale Ceremony (Timestamp 2:11:50)
https://www.youtube.com/watch?v=8fnzkkj2eBw
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
- Felix Prabitz, felix@prabitz.net, @felixpx (github), @felixfpx (twitter), CEO, Frontend Development
- Dominic Hackett, dominichackett@gmail.com, @dominichackett (github), @dominichackett (twitter), coCEO, Backend, Smart Contracts
- Dennis Ukonu , @ukonu_o (twitter), @devcraft1 (github), Smart Contracts
- Alicia Can, no twitter or github, Marketing

* If your project was created as part of an event or hackathon:
- Moralis x Avalanche Hackathon - Top 10 finalist. Demo Link above.
  * Please link to your hackathon submission
  Theres no website for the hackathon submissions, Live Demo & Youtube Finale stream as references above.

**Comment by ErinOCon** [comment]
Hi @felixpx, thank you for submitting this proposal! We do require microgrant work to be open source. If/when this is the case, please let us know!

**Comment by felixpx** [comment]
Hi Erin,
Thanks for reaching out so quickly. I spoke to my partner and we are fine
with putting the work for the microgrant open source. Let me know if you
need any more information on the project or how to proceed.

All the best,

felix



Am Di., 5. Apr. 2022 um 08:04 Uhr schrieb ErinOCon ***@***.***

**Comment by ErinOCon** [comment]
Thanks for the update, @felixpx! This microgrant has been approved. Look out for an email to submit payment details.

**Comment by felixpx** [comment]
Hi Erin,


We havent submitted the application yet. The reason being is that we are
unsure, of what is required to opensource for the grant? We do not want to
opensource the whole project as we are building a company with it. So the
question here is, if it is sufficient to open source the specific parts of
the code, which are in direct relation to IPFS.
This would essentially be the following:

- How to use IPFS in combination with Howler JS to have music files being
played on a website instead of opening the ipfs link separately. As well as
optimizing the upload process via 3rd party service Moralis.

Please let me know your thoughts on this. Thank you very much and have a
great start of the week.

All the best,

Felix , AVASOUND


Am Di., 5. Apr. 2022 um 21:59 Uhr schrieb ErinOCon ***@***.***
