### ISSUE TITLE
Open Grant Proposal: FilPulse

### ISSUE THREAD

**Issue by arctic-ash** [filecoin-project/devgrants#522]
# Open Grant Proposal: `FilPulse`

**Name of Project:** FilPulse

**Proposal Category:** app-dev, community

**Proposer:** arctic-ash (CrossChainLabs)

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes

# Project Description

Filecoin has increasingly grown the open source developer ecosystem. But there is currently no way to see all the activity among different Filecoin organizations on Github, understand what is their status, track the contributions made by developers and get an idea on how the repositories evolve.
Is hard to understand how the Filecoin ecosystem is progressing since the data is scattered all over GitHub, with contributors, commits, issues, repositories and PRs data that have no form of aggregation. Even just taking one organization such as filecoin-project, there are over 180 repositories, with different developers that are actively building.

The solution that CrossChain Labs presents is going to address the problems described above and will offer clarity on the open source Filecoin's developer ecosystem. This will be done by scraping the data related to Filecoin's organizations on GitHub and exposing it in a nicely designed dashboard that allows tracking the velocity of commits, the number of issues (open and closed), PRs, the top contributors, the active contributors for each month over the last year and the work done in the Filecoin ecosystem.

## Value

There are many benefits of getting the FilPulse project up and running:
 - it offers a clear overview on the open source development that is being done across the various Filecoin organizations, by having all the required data aggregated in one place
 - acknowledges the contributors of the month
 - displays the active contributors for each month over the last year
 - shows the evolution of the number of commits made on GitHub by developers throughout the entire Filecoin ecosystem
 - outlines the recent commits 

The risks are low since the architecture has a robust structure that contains the frontend, backend and a database stored on Google Cloud and the implemented APIs can be easily integrated in other apps.
CrossChain Labs team is experienced enough to accomplish this project and to maintain it during time.

## Deliverables

- GitHub Scraper that will collect all the required data from GitHub
- FilPulse APIs that will serve to get the data from the scraper and interact with the FilPulse dashboard
- FilPulse Dashboard that will include:
  - the statistics top section with the overall number of commits, repositories, contributors and PRs
  - contributors of the month
  - commits graph with info regarding the last 12 months
  - issues graph that shows the number of open and closed issues together with their total
  - graph of active contributors for each month over the last year
  - the recent commits section that shows the activity of the ecosystem over the last 30 days, with clickable links to open a commit, its repository or the developer's profile on GitHub

### Dashboard Overview

![FilPulse Dashboard](https://user-images.githubusercontent.com/91743348/161766128-eff95dad-e7f4-42ee-8fc6-c5d806bb893c.png)
## Development Roadmap

**Milestone 1**

Implement the Github scraper:
  - periodically update the list of repositories that are being part of the Filecoin organizations on GitHub
  - calculate the total number of commits, repositories, contributors and PRs from the entire Filecoin ecosystem
  - get the contributors of the month based on the number of commits
  - calculate the total number of commits across all the repositories for each month over the last year
  - collect the total number of issues that are being opened or closed at the moment
  - calculate the number of active contributors  for each month over the last year
  - collect the list of recent commits across all the Filecoin's Github repositories from the last 30 days

Members:
- Andreea - Backend Developer (JavaScript, dev-ops)
- Cristina - Full Stack Developer (JavaScript, React)

Start date: 16th of May, 2022
Completed By: 27th of June, 2022

Budgetary Needs: This milestone will last 6 weeks = $21,000

**Milestone 2**

Implement the FilPulse APIs required by frontend:
  - statistics API that returns the overall number of commits, repositories, contributors, PRs
  - contributors API that returns the list of contributors of the month based on the number of commits over the last month
  - issues APIs that return the total number of issues, the number of closed and open issues
  - commits API that returns the total number of commits per month
  - active contributors API that returns the number of active developers for each month over the last year 
  - recent commits API that returns the list of recent commits across all Filecoin repositories over the last 30 days

Build the FilPulse dashboard that display:
  - the statistics top section with the overall number of commits, repositories, contributors and PRs
  - contributors of the month
  - commits graph with info regarding the last 12 months
  - issues graph that shows the number of open and closed issues together with their total
  - active contributors graph
  - the recent commits section that shows the activity of the ecosystem over the last 30 days, with clickable links to open a commit, its repository or the developer's profile on GitHub

Members:
- Andreea - Backend Developer (JavaScript, dev-ops)
- Cristina - Full Stack Developer (JavaScript, React)
- Florin - UI/UX Designer (Sketch, Figma)

Completed By: 25th of July, 2022

Budgetary Needs: This milestone will last 4 weeks = $21,000

**Milestone 3**

Make the final adjustments and release the product:
  - create the production infrastructure
  - deploy filpulse.io Webapp 
  - run the final tests
  - public release on https://filpulse.io

Members:
- Andreea - Backend Developer (JavaScript, Rust, dev-ops)
- Cristina - Full Stack Developer (JavaScript, React)

Completed By: 8th of August, 2022

Budgetary Needs: This milestone will last 2 weeks = $8,000

> NOTE: The M3 calculation includes the cloud infrastructure cost estimated at $1,000.

## Total Budget Requested

We're requesting a total funding of $50,000 to complete all the above milestones, and the fund will be split into:

- Research and Development
- UX
- Infrastructure

| Milestone  | Duration| Cost    |
|------------|---------|---------|
|   #1       | 6 weeks | $21,000 |
|   #2       | 4 weeks | $21,000 |
|   #3       | 2 weeks | $8,000  |
|            |         |         |
| **Total**  | 12 weeks| $50,000 |

> NOTE: The M3 calculation includes the cloud infrastructure cost estimated at $1,000.

## Maintenance and Upgrade Plans

This is an open source project and we are committed to maintaining it by doing bug fixes based on the community feedback.

# Team

## Contact Info
Thank you for your interest in FilPulse project. If you have any question don't hesitate to contact me at andreea.stefan@crosschainlabs.tech 

## Team Members

- Andreea - Backend Developer (JavaScript, Rust, Go, C++, dev-ops)
- Cristina - Full Stack Developer (JavaScript, React)
- Florin - UI/UX Designer (Sketch, Figma)

## Team Member LinkedIn Profiles

- [Andreea Stefan](https://www.linkedin.com/in/andreea-stefan-66740b20/)
- [Cristina Varteniuc](https://www.linkedin.com/in/cristina-varteniuc-6b3121224/)
- [Florin Gradinaru](https://ro.linkedin.com/in/florin-gradinaru-73891bb)

## Team Website

https://github.com/CrossChainLabs

## Relevant Experience

We are a team of developers with experience in blockchain technologies. Some of the latest dev-grants were for projects from NEAR protocol (NEAR registrar, Audit Registry, near.link) and from Filecoin (FilMarket) with tech stack: IPFS, rust, react, go and javascript.
- Andreea Stefan - is a former Consensys employee and the co-founder of Crosschain Labs. Has a work experience as a software developer of 14 years and her main focus for the last several years is blockchain development
- Cristina Varteniuc - accomplished numerous courses of software development, participated to multiple hackatons and her focus is in blockchain-related products development
- Florin Gradinaru - is an experienced artist and graphic designer with 18 years of work experience and a strong passion for UI/UX

## Team code repositories

- https://github.com/CrossChainLabs
- https://filmarket.io 
- https://filpulse.io (coming soon)

**Comment by ErinOCon** [comment]
Hi @arctic-ash, Thank you for your proposal! We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
Hi @arctic-ash, we would like to fund part of the outlined work! Please email devgrants@fil.org to discuss next steps.
