### ISSUE TITLE
Next Step Microgrant: ThreeIPFS

### ISSUE THREAD

**Issue by hiekxel** [filecoin-project/devgrants#525]
### 1. What is your project? (max 100 words)
The ThreeIPFS project is the Three.js javascript code library integrated into IPFS. With Three.js, 3D objects can be published on the Web. Thanks to this integration, a 3D object can be hosted in IPFS. This module can be used in projects such as 3D NFT.

 https://github.com/hiekxel/ThreeIPFS

### 2. How are you planning to improve this project? (max 200 words)
I'm going to improve Three.js to take 3d model remotely instead of taking local source. After that I will adapt remote modeling to IPFS.
After publishing the project, I will develop a module for use in open source content management systems. However, I will support developers who want to use ThreeIPFS in their projects. Also, I will make some 3D file types available that are not used in Three.js.

 
### 3. Will the work be Open Source?

Yes, MIT License

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes

### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Excelsior Hiekzen
exelhiekzen@gmail.com

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @hiekxel, thank you for this submission! Do you have a repo with code available or other documentation of progress?

**Comment by ErinOCon** [comment]
Hi @hiekxel, circling back to confirm if code is available for review. Thanks!

**Comment by hiekxel** [comment]
Hi @ErinOCon, you can check the github repository. 

https://github.com/hiekxel/ThreeIPFS

Thanks!

**Comment by ErinOCon** [comment]
Thanks, @hiekxel! Can you confirm how you plan to save objects to IPFS (i.e. Pinning service, etc)?

**Comment by hiekxel** [comment]
Hi @ErinOCon, I confirm I plan to save object to IPFS (Pinning Services).

**Comment by hiekxel** [comment]
Hi @ErinOCon,
Just a friendly reminder.
If you have any questions, I'd be happy to answer them.

Thanks in advance!

**Comment by ErinOCon** [comment]
Hi @hiekxel, thank you for your patience. The proposal has been approved! We will be in touch by email to discuss payment details.
