### ISSUE TITLE
Next Step Microgrant: QSTN: Re-defining data, De-Fi and NFTs on NEAR Protocol 

### ISSUE THREAD

**Issue by qstnus** [filecoin-project/devgrants#527]
Name of Project:
QSTN

Tagline:
Re-defining data, De-Fi and NFTs on NEAR Protocol

**Proposal Category:**

**Filecoin x Encode Club stipend for graduation**

Proposer:

https://github.com/@qstnus (Orrin Campbell)

Open Source:
We agree to open source the IPFS and NFT.Storage integration but the platform and related functionality is proprietary.

Project Description:
Data has become a human rights issue and our goal is to bridge that gap by creating new tools on Web 3.0 which empower end-users.

 [QSTN](https://qstn.us) is a blockchain enabled market research portal where users answer questions, earn credits and spend these rewards within our digital environment.

Launching an application on [NEAR Protocol](https://near.org/) that focuses on consumer data privacy is paramount to the future of web security and internet data regulations as the world transitions to a Web3 structure.

As a data platform, the virtual $ANSR credit, allows users to earn digital rewards each time they answer a question on-chain by swapping for NFTs, discount codes and virtual experiences. 

The credit not only incentivizes collaboration between companies and consumers but also creates a sustainable data economy to showcase the true value of consumer data. 

QSTN is being implemented on NEAR Protocol because gas fees for thousands of daily, micro tasks would be ridiculously expensive on Ethereum.

Value:
Aside from the $ANSR credit, our platform offers a digital NFT marketplace where we offer various digital goods and experiences. 

These NFTs have images and metadata which we need to pin and host on a (preferably decentralized) file storage solution. 

After the initial launch, we will open the shop to different sectors of entertainment including music, fashion and technology to create new launches and product roll outs across all industries.

**Reason:
$5,000 stipend from Filecoin for graduating from the Encode Club accelerator** 

Team: 
•	Orrin Campbell – QSTN founder, CEO and blockchain architect who will be designing the workflow and user experience 
o	Twitter  https://twitter.com/realorrin 

o	Instagram  https://instagram.com/realorrin 
o	YouTube  https://youtube.com/realorrin
o	Linkedin  https://linkedin.com/in/realorrin 
o	GitHub  https://github.com/@qstnus 

•	Eugen Pyatygin – QSTN lead developer and back-end specialist, will be leading the integration and coding the NFT.Storage functionality 
o	Github  https://github.com/3ugen 

•	Lafi Raed & Borhen Jlidi – QSTN junior developers and front-end specialist, will be leading the visual redesign for the NFT marketplace and related functionality 

Background: 

Founded by NYU graduate [Orrin Campbell](https://youtube.com/c/realorrin), QSTN was birthed by a [recorded conversation](https://www.youtube.com/watch?v=ImdmYU6ykCo&t=1s) with astrophysicist Neil deGrasse Tyson. 

During the interview, Neil argued that even if software is ‘free’, companies still profit from the sale, transfer and storage of our information. 

For example, did you know Google makes almost $120 million dollars a day in advertising revenue (e.g. targeted ads, placements)? Orrin thought about how to creatively address this problem and deliver on his “[promise to save the world](https://www.youtube.com/watch?v=ReRddYVYfHU&t=16s).”

Orrin has released NFTs with Mintbase, spoken on Cryptovoxels and Somnium panels as well as created a large social following behind his afro futuristic aesthetic. Completing the QSTN team triad are the Suriel brothers, who Orrin met at NYU.

Jose Suriel is an NYU graduate who handles project management at Forge AI – bringing his expertise to the development and timeline of the QSTN marketplace.

Anibal Suriel is Jose’s twin brother and our head of legal, he is registered in New York and Florida; leveraging his time at KARM to create the legal framework and guidelines around data, compliance, storage and overall best practice.

Website:

•	Here is the official QSTN website - https://qstn.us 

Press: 
[QSTN x NEAR Protocol (Phillipines)](https://www.google.com/url?q=https://medium.com/nearphilippines/conversation-from-the-future-with-qstn-a09da7de1a1f&sa=D&source=docs&ust=1649273841457598&usg=AOvVaw2dD2KiRHA-c0mPFMwXy011)
[QSTN x NEAR Reddit AMA](https://www.google.com/url?q=https://www.reddit.com/r/nearprotocol/comments/rh8aig/this_weeks_ama_is_with_orrin_founder_of_qstn_qstn/&sa=D&source=docs&ust=1649273863032330&usg=AOvVaw0cprIekqPmm6-uiUwNfgVD) 
[QSTN x NEAR Twitter Announcement](https://www.google.com/url?q=https://twitter.com/NEARProtocol/status/1463538153856372738&sa=D&source=docs&ust=1649273881408144&usg=AOvVaw0O9jT2ipB_7RJVuVl5vepi)
[Keeping Up The Evolution of De-Fi on NEAR](https://www.google.com/url?q=https://ladevochka.medium.com/keeping-up-with-the-evolution-of-defi-on-near-croncat-roketo-burrowcash-and-qstn-61bb5e51e13a&sa=D&source=docs&ust=1649273904992417&usg=AOvVaw14SPCveE1G3Vuge-1x41vu)
[QSTN x NEAR Protocol (Switzerland)](https://www.google.com/url?q=https://medium.com/nearprotocol/qstn-is-launching-on-near-protocol-introducing-the-future-of-data-privacy-4c7567085666?source%3Dcollection_home---4------4-----------------------&sa=D&source=docs&ust=1649273927057746&usg=AOvVaw2TiXWttBzLlUH91GgJ466i)

Contact details:
qstnus@gmail.com
845 240 0573

**Comment by ErinOCon** [comment]
Hi @qstnus, This microgrant has been approved! Look out for an email to submit payment details.
