### ISSUE TITLE
Next Step Microgrant: <DeFiSlate DAO>

### ISSUE THREAD

**Issue by Alionakalitsun** [filecoin-project/devgrants#529]
### 1. What is your project? (max 100 words)
DeFiSlate DAO

https://twitter.com/defislate
https://defislate.com

### 2. How are you planning to improve this project? (max 200 words)
Objectives: Community Growth / Organic Engagement / Onboard New Users To Filecoin
### 3. Will the work be Open Source?
We should involve the greater amount of people:)

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes! Sure!
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes!

### 6. Links and submissions

https://www.youtube.com/channel/UCC2UPtfjtdAgofzuxUPZJ6g

### Additional questions:
https://twitter.com/defislate
https://twitter.com/ayyyeandy - the head of community

**Comment by ErinOCon** [comment]
Hi @Alionakalitsun, thank you for your submission! Can you provide more detail regarding the specific project work and the next steps you plan to take with the grant support? If applicable code or a repo is available, please include a link with your proposal.

**Comment by Alionakalitsun** [comment]
Adding the team here for this thread.


Adding the team here for this thread.

**Comment by Alionakalitsun** [comment]
Thanks for the reply Erin,

I've attached a detailed action plan for the usage of funds and next steps,
thanks!

https://docs.google.com/document/d/17J3Zq22cnz0SLEByR8xp87-BZgXLk076eq_3cEPkZ4s/edit?usp=sharing

Andy

**Comment by ErinOCon** [comment]
Thanks, @Alionakalitsun! Is there a repo/code applicable to this project?

**Comment by ErinOCon** [comment]
Hi @Alionakalitsun, do you have an update available? In addition to a repo, details regarding the work of your project and the next steps you plan to take with this grant would be very helpful. For reference, previous grants approved through the program can be found [here](https://github.com/filecoin-project/devgrants/blob/master/microgrants/accepted-microgrant-applications.md).

**Comment by ErinOCon** [comment]
Hi @Alionakalitsun, this item has been closed. If you are interested in connecting with our team to discuss content creation, please feel welcome to be in touch at grants@filecoin.org.

**Comment by Alionakalitsun** [comment]
Adding the team here for this thread.


чт 14. 4. 2022 о 22:11 ErinOCon ***@***.***> пише:
