### ISSUE TITLE
Next Step Microgrant: AstterEd

### ISSUE THREAD

**Issue by ari4325** [filecoin-project/devgrants#530]
### 1. What is your project? (max 100 words)
AstterEd is an ed-tech platform that rewards users to learn. Users buy subscriptions using USDT, get the equivalent amount of Astter ($AST) tokens in their wallets, and stake those $AST tokens and this gives them access to a huge library of courses. When they complete a course, they receive a particular amount of $AST tokens as a reward, which is calculated using our curated algorithm. This also gives them an incentive to keep learning.

The project would make use of IPFS in the form of Web3.Storage and NFT.Storage for storing resources. 

**_Github repo:_**
https://github.com/sushmitgh2/AstterEd
  
**_Live demo:_**
https://asttered.000webhostapp.com/
(Treasury may not reflect accurate results at the moment)

### 2. How are you planning to improve this project? (max 200 words)
-	Switching to a mobile-centric dapp for easier onboarding of users.
-	Gamification of the dapp using standings, streaks, levels, scores, awards, and much more.
-	Creating (Hiring) a team of developers and designers for shipping the first version of the dapp in a short period of time.
-	Curation of course contents: This includes video and audio recordings, content creation, assessment curation, editing, and graphics. 
-	Implementing an NFT certificate generation system within the dapp.
-	Making the reward system much more efficient and improving tokenomics.
-	Providing liquidity of $AST tokens to decentralized exchanges.
-	Branding: Coming up with a brand strategy that includes brand positioning, colour palette selection, and brand typography.
 
### 3. Will the work be Open Source?
Yes

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions
**Our project began at Moralis Avalanche Hackathon 2022.** 
Project Deck: https://drive.google.com/file/d/1WJzzk1pqdFkGQgWvaKHJuoV1HS7jTeqQ/view?usp=sharing
Demo: https://drive.google.com/file/d/1MQv5Z0MDMaPHe-SiyT09seXo38ahQ9dG/view?usp=sharing
  
### Additional questions:
**_Team Member 1:_** 
Arishmit Ghosh
Email Id: ari4325@live.com
Github: https://github.com/ari4325
Role: Founder and Developer

**_Team Member 2:_**
Sushmit Ghosh
Email Id: sushmitgh2@gmail.com
Github: https://github.com/sushmitgh2
Role: Founder and Developer

We would also be submitting the request to be put up on the Filecoin Hall of Fame. 
Since the submission for the hackathon was on Google Forms there is no link available for sharing, however, all relevant information has been shared in this issue.

**Comment by ErinOCon** [comment]
Hi @ari4325, This microgrant has been approved! Look out for an email to submit payment details.
