### ISSUE TITLE
Next Step Microgrant: pyMoralis

### ISSUE THREAD

**Issue by IKalonji** [filecoin-project/devgrants#531]
### 1. What is your project? (max 100 words)

pyMoralis is a Python SDK wrapper for the Moralis platform which has also implemented Covalent Class A queries as well as NFT.Storage for ease of use in web3 development. The aim is to make it easier for developers who already know the Python language to build rapidly using Moralis, Covalent and NFT.storage for IPFS

[Hackathon-submission-repository](https://github.com/IKalonji/pyMoralis)

### 2. How are you planning to improve this project? (max 200 words)

My next steps would be to implement IPFS core into the SDK and additionally add OrbitDB which is based on IPFS into the pyMoralis SDK project. Clean up the code and implement tests for release.
 
### 3. Will the work be Open Source?

The project will be distributed under the MIT License.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

I will be providing weekly updates on the developments of the SDK library.
  
### 5. Does your proposal comply with our Community Code of Conduct?

My project and proposal complies with the Filecoin/IPFS Community Code of Conduct

### 6. Links and submissions

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

[Moralis/Avalanche-hackathon-submission-repository](https://github.com/IKalonji/pyMoralis)
  
### Additional questions:

Issa Kalonji  
[LinkedIn](https://www.linkedin.com/in/issa-kalonji-b301851ba/)
[Github](https://github.com/IKalonji/)
[Discord] Issa_Kalonji#4638

* If your project was created as part of an event or hackathon:
  * Moralis-Avalanche 2022
  * [Moralis/Avalanche-hackathon-submission-repository](https://github.com/IKalonji/pyMoralis)

**Comment by ErinOCon** [comment]
Hi @IKalonji, This microgrant has been approved! Can you provide an email address to discuss payment details?

**Comment by IKalonji** [comment]
Thank you @ErinOCon, my email addr: IKalonji@student.wethinkcode.co.za

**Comment by ErinOCon** [comment]
Thanks @IKalonji! Look out for an email to submit payment details.

**Comment by ErinOCon** [comment]
Hi @IKalonji, I hope you are doing well! The final report for this project can be completed [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let me know if you have any questions!

**Comment by IKalonji** [comment]
Thank you, my email address: ***@***.***

**Comment by ErinOCon** [comment]
Hi @IKalonji, thank you for submitting the microgrant report! Can you point to the building progress made during this project in your repo? I do not see new updates since late January of this year.

**Comment by IKalonji** [comment]
Hi @ErinOCon I have the changes locally. I'll commit later this evening. Thanks.

**Comment by ErinOCon** [comment]
Hi @IKalonji, do you have an update available?

**Comment by ErinOCon** [comment]
Hi @IKalonji, circling back on this request.
