### ISSUE TITLE
Next Step Microgrant: DHost VS Code Extension (publish static websites to IPFS with just 2 commands!)

### ISSUE THREAD

**Issue by AkhileshThite** [filecoin-project/devgrants#532]
### 1. What is your project? (max 100 words)
<p align="center">
<img height="150" width="150" src="https://user-images.githubusercontent.com/68826419/161441628-bed0a7f0-dd25-4654-9f2e-2b4f8af71e78.png" />
</p>

DHost VS Code Extension allows you to instantly publish static websites to [IPFS](https://ipfs.io/) by using [web3.storage](https://web3.storage/). Now you can publish and share your websites quickly with anyone in the world!

GitHub: https://github.com/buidltools/vscode-dhost

VS Code Marketplace: https://marketplace.visualstudio.com/items?itemName=DHost.dhost

### 2. How are you planning to improve this project? (max 200 words)

1. Build a development feature (right now it's focused on publishing the websites) that will basically publish the site after saving the changes in VS Code, means after each `command` + `s` it'll generate a new hash.
2. Research and implement ceramic to keep the output link same after each change for development purposes (like live server extension, so that the user can see the changes "live" and also can share the link with team members).
3. Upgrade to TypeScript.
4. Digital marketing: educate developers about the dev tool through social media.

### 3. Will the work be Open Source?

Yes.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes.
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes.

### 6. Links and submissions

Filecoin community project showcase thread: https://github.com/filecoin-project/community/discussions/502

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

Yes.
DHost received "Across the Line Award" at Faber Web3 Hackathon.
https://devpost.com/software/dhost-vs-code-extension
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Name: Akhilesh Thite

Email: akhileshthite@hotmail.com

GitHub: [@AkhileshThite](https://github.com/AkhileshThite)

Role: Main developer 

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)

[Faber Web3 Hackathon](https://faberweb3.devpost.com/)

  * Please link to your hackathon submission

Submission link: https://devpost.com/software/dhost-vs-code-extension

**Comment by ErinOCon** [comment]
Hi @AkhileshThite, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by AkhileshThite** [comment]
> Hi @AkhileshThite, This microgrant has been approved! Look out for an email to submit payment details.

Received. Thank you :)

**Comment by akhileshthite** [comment]
### Task 1

1clickNFT: 
GitHub: https://github.com/buidltools/1clicknft
VS Code Extension Marketplace: https://marketplace.visualstudio.com/items?itemName=1clickNFT.1clicknft

**Comment by ErinOCon** [comment]
Hi @akhileshthite, thank you for the update! Can you submit the final report [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

**Comment by akhileshthite** [comment]
> Hi @akhileshthite, thank you for the update! Can you submit the final report [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

Sure!
