### ISSUE TITLE
Next Step Microgrant: NFT Teleporter

### ISSUE THREAD

**Issue by xx014939** [filecoin-project/devgrants#533]
### 1. What is your project? (max 100 words)

NFT Teleporter is a no/low code tool (API end points are available if needed), which offers users the ability to create and mint NFT's in multiple dimensions and mediums. NFT Teleporter allows users with little to no technical expertise to quickly and easily create their very own NFT's and NFT collections, whilst simultaneously providing up front web based experiences which integrate these NFT's seamlessly. 

All data saved inside of the NFT's metadata (utilising IPFS storage), is retrievable at a later date by using our simple API endpoints, meaning that bespoke experiences can be built upon our generic ones with data already stored on secure servers.

This was originally it's own separate project, but will be adopted by our main project "Your Meta World" (https://www.yourmeta.world/) as one of the many open source tools we will be offering free to users in order to facilitate growth and innovation inside of the NFT and Web3 community.

https://github.com/xx014939/nft-teleporter-faber-hackathon
  

README Instructions - https://github.com/xx014939/nft-teleporter-faber-hackathon
Main website - http://nftteleporter.com/

Hackathon entry and video demo - https://devpost.com/software/nftteleporter-com

### 2. How are you planning to improve this project? (max 200 words)

1. Extend current web based experience to be something much interactive and entertaining. Perhaps some type of simple game or animation which utilises the newly minted NFT.
2. Integrate NFT Teleporter into Your Meta World's suite of NFT tools
3. Extend functionality to creating entire NFT collections in addition to single NFT's
 
### 3. Will the work be Open Source?

Yes, with an MIT license

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Of course
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions

https://devpost.com/software/nftteleporter-com

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

I am the sole developer

Name: Naail El-Sawah
GitHub: xx014939

* If your project was created as part of an event or hackathon:

Faber Web3 Hackathon 

  * Please link to your hackathon submission

https://devpost.com/software/nftteleporter-com

**Comment by ErinOCon** [comment]
Hi @xx014939, This microgrant has been approved! Can you provide an email address to discuss payment details?

**Comment by xx014939** [comment]
@ErinOCon Amazing!

Yes, naailelsawah@gmail.com

**Comment by ErinOCon** [comment]
Thanks, @xx014939!

**Comment by xx014939** [comment]
@ErinOCon 

Hey Erin, just wanted to drop an update here. I've finished most/all of the functionality described in this grant and have pushed up to the following repos.

Main application --> https://github.com/xx014939/nft-teleporter-react-app
NFT Experiences --> https://github.com/xx014939/three-js-webpack

The project was recently entered into the Hedera Smart Contract hackathon, so in addition to the above functionality I also moved the project over to Hedera from Ethereum. You'll need a testnet wallet to get started but the app has been deployed here --> https://nft-teleporter.netlify.app/

You can view a video demo of the application and some more info on the hackathon entry itself here --> https://devpost.com/software/your-meta-world-931izb

I'll hopefully get round to putting together a proper README file later this week on both repos.

Thanks for all the support!
