### ISSUE TITLE
Open Grant Proposal: Imbue

### ISSUE THREAD

**Issue by carrabre** [filecoin-project/devgrants#534]
# Open Grant Proposal: Imbue

**Imbue**

**Proposal Category:**  `app-dev`

**Proposer:** `carrabre`

**(Optional) Technical Sponsor:** `Ruben Amenyogbo - `

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Please respond with either "Yes" or "No"

Yes

# Project Description

Imbue is building a decentralized, web3 native platform that will allow users to have a say in how the project is run and share in the value that Imbue creates through the IMBUE token. Everything is completely decentralized, from the site hosted on IPFS to the streaming through Livepeer, to the ENS domain and the .limo, which is a decentralized alternative to Cloudflares reverse proxy for ENS names and IPFS content. We're building the web3 twitch.

https://github.com/imbueworld/influence-create

https://imbue.eth.limo/
Demo video - https://www.youtube.com/watch?v=YqwB8LiAzIg

## Value

Having large quantities of of NFT's, a large volume of video storage and having our website with hundreds of thousands of website visits will dramatically increase the usage of IPFS and the filecoin ecosystem at large, generating more revenue for the entire ecosystem.

Presearch aims to be the Twitch of Web3. There are many risks and there is probably a greater than 90% chance that we, or any project in web3, reach the level of success that we are shooting for, but we plan to remain lean until we find our product market fit, iterate frequently and survive long enough until we reach our inflection point. The benefits of getting this right will be massive for the filecoin ecosystem and the web3 ecosystem as a whole.

## Deliverables

Creators on platforms like Twitch or Youtube are the sole value creators for the platforms. They bring all of the attention to the platforms for the platforms to monetize and in the best case, split revenue. But what about all of the value that they are creation for the company? Taking that into consideration, the best case scenario on Youtube, the platform is keeping more than 95% of all value created. On some platforms, creators can arbitrarily be removed or restricted based on the beliefs they have.

We’re here to change that, and bring more value back to the people who are creating it. Decentralizing the power and decentralizing the wealth creation to all levels of people who participate in a protocol is the future of business in all areas. Building a decentralized protocol means that it’s censorship resistant as well, so no one entity can take away someone’s right to earn an income or their place to voice their opinions even if they differ.

The final product will not just be an app hosted on IPFS, but will much more deeply integrated having all of our NFT's & videos stored on IPFS for our newly created explore page. 

See below for a more detailed roadmap 👇

## Development Roadmap

| Task        | Description           | Cost  |
| ------------- |:-------------:| -----:|
| Subscriptions | subscribe to any user to access all of their streams all the time | $3000 |
| Pay and View from any Chain  | Oracle to pull chain data to allow user to purchase and view from whichever chain they're on |   $4000 |
| Custom Streaming | allow creators to input the stream key into a streaming source of their choice to allow for maximum flexibility on streams (OBS, etc.) |  $3000 |
| Optional Gas Free events | no need to sign a transaction to view free streams. |  $1000 |
| Explore page | Have an explore page for most viewed live streams, optionally have streams available after stream finishes, stored on IPFS |  $15000 |
| NFT Gated Events | Users who have a certain amount or specific ERC-721 token can access certain streams |  $4000 |

## Total Budget Requested

| Task                   | Cost  |
| ------------- |:-----:|
| Subscriptions | $3000 |
| Pay and View from any Chain  | $4000 |
| Custom Streaming | $3000 |
| Optional Gas Free events | $1000 |
| Explore page | $15000 |
| NFT Gated Events | $4000 |
| Total | $30,000 |

## Maintenance and Upgrade Plans

With this grant, we'll have enough runway to fund the project for the next 12 months. I still work full time and am putting my own funds into the project.

EOY Goals - 500 creators on the platform, 10,000 monthly streamed hours.

# Team

## Team Member LinkedIn Profiles

[Alex Carrabre ](https://www.linkedin.com/in/alexcarrabre)
Vikas Doesn't have (based in Pakistan)

## Team Website

https://imbue.eth.limo

## Relevant Experience

I currently lead growth at [Presearch](https://presearch.io/team), previously built a [web2 streaming app](https://apps.apple.com/us/app/imbue-influencer-workouts/id1532470257).

## Team code repositories

https://github.com/imbueworld/influence-create
https://github.com/imbueworld/influence-proxy (streaming server)

# Additional Information

**Comment by ErinOCon** [comment]
Hi @carrabre, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by ErinOCon** [comment]
Hi @carrabre, We would like to fund the outlined work! Please email devgrants@fil.org to discuss next steps.

**Comment by carrabre** [comment]
> Hi @carrabre, We would like to fund the outlined work! Please email devgrants@fil.org to discuss next steps.

Thank Erin! Just replied!

**Comment by carrabre** [comment]
Just followed up!
