### ISSUE TITLE
Next Step Microgrant: <Quilt>

### ISSUE THREAD

**Issue by champ5898** [filecoin-project/devgrants#535]
### 1. What is your project? (max 100 words)

There’s a clear communication gap between users over the blockchain space. Currently, chatting platforms have not integrated themselves into web3. Quilt aims to solve these issues by providing a secure and encrypted end-to-end social protocol that gives users the freedom to interact and transact without any identity breach. Our project is deployed on Fleek which uses IPFS.  We are currently using gun (https://gun.eco/) for our p2p protocol. The universal GUN graph is distributed across all peers participating in the network. We are also doing some research on the alternatives available like OrbitDB (https://orbitdb.org/) and berty (https://berty.tech/).

https://github.com/quilt-dao/quilt-hackathon

https://quilt.chat/
https://app.quilt.chat/
  
### 2. How are you planning to improve this project? (max 200 words)

Currently, we are worried about the storage capacity. Browser peers use localStorage or IndexedDB to store only a subset of the graph they are subscribed to, synced using WebRTC, Websockets, or other transports. The same browser code also runs in NodeJS with adapter plugins for fs, S3-like storage backups, UDP multicast, and other features that let it stay in "relay" mode only or to store everything. But we don’t want to use centralized storage like S3. Therefore, we are planning to improve the efficiency and decentralization of our chat DAPP by migrating our DAPP to Orbit DB.
The current important need is to find a solution that will make our protocol more scalable and we think that libp2p will be more suitable for that along with various encryption algorithms. Also,  we need to onboard beta testers who will give us honest feedbacks which will make our product more perfect. Most importantly we will utilise these funds for community building and social outreach.
 
### 3. Is this project open source?

Our platform is free to use. But currently we are not in a position to make it open source. But in the future, we definitely want to make it open source so that all the developers can build on top of it. We are also in talk with a gaming project to provide them decentralized communication as a service. We would love to make collaborations with protocols that are in need of decentralized connections but still using centralized systems due to lack of availability.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes we will definitely do that
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes we did and won a reward of $211.26, for the Avalanche Hackathon and won a Business award and Across the Line Award at the Faber Web3 Hackathon https://devpost.com/software/quilt-axcfdl
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Chandan Das - Blockchain Developer (founding member) [daschandan83333@gmail.com](mailto:daschandan83333@gmail.com)
https://github.com/champ5898
Mer D - Graphics Designer (founding member)
Abduljalaal Abubakar - Business & Social Media strategist, [abduljalaalabubakar@gmail.com](mailto:abduljalaalabubakar@gmail.com) (founding member)
Vitcos - Blockchain Developer (founding Member) https://github.com/LordEvendim
Surya, fullstack developer, frontend developer (founding member) https://github.com/Surya742
Eugene - Frontend Developer (founding member) https://github.com/eanisei
Viktor - Frontend Developer (team member)
Oliver - Frontend Developer(team member)
Melo Augstine - Article Writer(team member)
Mah’d - Project Manager (team member)
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  We started with Quilt at the Avalanche Moralis Hackathon, which we changed after the hackathon from Avalanche to Polygon during 
  the Faber Web3 Hackathon and worked on the frontend of landing page, improving on the efficiency, and adding a AI assistant.
  * Please link to your hackathon submission
  https://devpost.com/software/quilt-axcfdl

**Comment by ErinOCon** [comment]
Hi @champ5898, Thank you for the submitted proposal! Open source work is a key point in our criteria that often aligns with the business models of our grantees (in case it's of interest, here's [a quick read](https://medium.com/blossom-capital/successful-open-source-business-models-2709e831e38a)!)

If/when this project is open source, we expect it will be a great candidate for microgrant funding! If you have any questions, please let me know.

**Comment by ErinOCon** [comment]
Hi @champ5898, I have closed this issue for the time being, but please feel welcome to resubmit if/when you move to an open source model. Wishing you all the best with this project!
