### ISSUE TITLE
Next Step Microgrant: INSIGNIA

### ISSUE THREAD

**Issue by george-shammar** [filecoin-project/devgrants#537]
### 1. What is your project? (max 100 words)

Insignia is an immersive, AAA, 3D military strategy blockchain game that pays to play. 

Born out of the need to solve the known problems currently plaguing the blockchain gaming ecosystem, Insignia is at the melting point of NFT, DEFI and 3D gaming. A multi-platform and multi-protocol play-and-earn blockchain application with enjoyable game-play built with Unreal Engine.

Players have the opportunity to own unique digital assets, not only valuable but have real in-game use case. Insignia is also implementing the concept of "collateral-less" NFT Leasing for non-stop, full-circle  earning potential. Players can now earn while they play their favorite game and when they are not playing. 

https://github.com/george-shammar/Insignia

  
### 2. How are you planning to improve this project? (max 200 words)

- We plan to begin testing the current application through our discord community, This would provide us with early feedback from the eventual users. 
- Release of the free-to-play version of the game.
- We hope to proceed to the next milestone on our roadmap which is launching the initial sets of game asset.
- First release of the play-to-earn version of the game.
 
### 3. Is this project open source?

Yes!

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes, we agree.
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes.

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* 
  Encode Club x Filecoin Accelerator

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

TEAM MEMBER 1:
- Name: George Gbenle
- Email: tasmarakalamazoo@gmail.com
- Github: https://github.com/george-shammar
- Role: Blockchain Developer/ Web Developer

TEAM MEMBER 2:
- Name: Isaac Otimi
- Email: isaackulenyotimi@gmail.com
- Role: 3D Game Animator

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)

- Encode Club & Filecoin Accelerator

  * Please link to your hackathon submission
  - Not a Hackathon submission but an Accelerator program.

**Comment by ErinOCon** [comment]
Hi @george-shammar, This microgrant has been approved! Look out for an email to submit payment details.
