### ISSUE TITLE
Next Step Microgrant: NFsTreamer

### ISSUE THREAD

**Issue by ankitpal1029** [filecoin-project/devgrants#538]
### 1. What is your project? (max 100 words)

NFsTreamer is a platform for creators to monetize their brands by selling clips of their live streams as utility NFTs which can be used by the fans as “Emotes” during the creator’s live streams in exchange for points that unlock fandom tiers. With each tier comes perks offered via our platform - for example, exclusive access to discord channels, private streaming sessions with the creator and more to be added later on. We are using NFT.Storage in order to store meta data for the NFTs that are being minted.

https://github.com/ankitpal1029/NFsTreamer

https://www.youtube.com/watch?v=xslB3TqPvwA&t=1s
https://marketplace.nfstreamer.tech/

### 2. How are you planning to improve this project? (max 200 words)

* Since the product involves minting clips of the creator's stream support for video meta data has to be implemented (since it's just images for now)
* Integrating exclusive Discord channel access
* Enabling private streaming sessions based off tier of the fan
* Hiring a team to help with the development of the product
* Getting the product production ready (mainnet deployment, hosting services on AWS since now it is all on free tiers of various services)

### 3. Is this project open source?

Yes, it is open source, GPL version3.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes, I agree to share weekly updates.
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes, it does.

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Yes, it began in Encode.club's NFT hackathon.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Ankit : https://github.com/ankitpal1029
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  **It was part of the EncodeXFilecoin Accelerator.**

**Comment by ErinOCon** [comment]
Hi @ankitpal1029, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by ErinOCon** [comment]
@ankitpal1029, can you provide your preferred email address? This is needed to proceed with the payment process.

**Comment by ankitpal1029** [comment]
Hey sure!
My preferred email address is 
ankitkumarpal27@gmail.com

**Comment by ankitpal1029** [comment]
@ErinOCon i have been informed by filecoin that the grant request hasn't reached them yet
What is it that i should do? I haven't recieved any mail either regarding this as mentioned above

**Comment by ErinOCon** [comment]
Hi @ankitpal1029, thanks for reaching out! The request for payment details has been sent to the email address provided. Please feel welcome to respond to our email with any questions.
