### ISSUE TITLE
Next Step Microgrant: DeBox

### ISSUE THREAD

**Issue by lakshh07** [filecoin-project/devgrants#540]
### 1. What is your project? (max 100 words)

Decentralised cloud storage built on top of web3 technologies.

Existing tools stores their data in a centralised database which can be taken down anytime. Using DeBox, your data is stored securely on decentralised Web3 Storage( IPFS network ).
It is built for virality and growth through community better than similar traditional consumer apps because we plan to issue a governance token.

***Who is it for?***
DeBox is the ideal tool for people who are stuck using Web2 because of the inconvenience and inertia of switching.

This project uses,

- The frontend is made with Next.js and contracts are integrated with ethers.js and hardhat.
- The smart contracts are made in Solidity using Open Zeppelin security.
- User profiles are created by ceramic 3id-connect (DID), data stored on IPFS.
- I am using IPFS/Filecoin (web3.storage) to store user files.

Github Repo: https://github.com/lakshh07/DeBox

  
### 2. How are you planning to improve this project? (max 200 words)

First of all, I want to improve UI for error flow and micro-interactions, little bugs and easy flow for consumers. Redesign the structure of the whole process of application and wanted to add some more features like

- Build an NFT subscription-based business model refinement consisting of 4 tiers Legendary, Epic, Rare and Common.
- Preview of files in the user dashboard.
- Paid storage.
- Add a short term file transfer tool on IPFS for everyday users.
- Wanted to add more security for user files using the public-private keys.

Deploy it to mainnet and more things.

### 3. Is this project open source?

Yes, this project is already under the MIT license.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes, I agree to share weekly updates and grant reports.
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: Yes, I have submitted for IPFS prizes
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.:
   Lakshay
   Email: lakshk886@gmail.com
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum): Polygon BUIDL It 2021 Hackathon
  * Please link to your hackathon submission: https://devfolio.co/projects/debox-e67b

**Comment by ErinOCon** [comment]
Hi @lakshh07, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by ErinOCon** [comment]
HI @lakshh07, Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @lakshh07, I hope you are doing well! Do you have any questions regarding the final report?

**Comment by ErinOCon** [comment]
@lakshh07, please confirm if you will be completing the final report for this project.
