### ISSUE TITLE
Next Step Microgrant: Fantribal - Encode Club/Filecoin Accelerator

### ISSUE THREAD

**Issue by iangriggs** [filecoin-project/devgrants#541]
### 1. What is your project? (max 100 words)

Fantribal - a website for music artists, bands and their fans to mint and buy NFTs that celebrate events in the lifetime of fledgling artists. The sale of collectible NFTs provides valuable funds to support the early life of new artists. When they are famous there will be financial rewards for venues and fans through royalties from the sale of ultimately valuable NFTs.

https://github.com/kasperdoggames/fantribal

https://vimeo.com/690288845
  
### 2. How are you planning to improve this project? (max 200 words)

 
Complete the Encode Club/Filecoin Accelerator programme

### 3. Is this project open source?

Yes

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Weekly updates shared as per Encode Club/Filecoin accelerator schedule posted on discord.
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
N/A

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

Encode Club/Filecoin Accelerator

**Comment by ErinOCon** [comment]
Hi @iangriggs, This microgrant has been approved! Look out for an email to submit payment details.
