### ISSUE TITLE
Unreal Engine NFT Integration By Filecoin & SWIM

### ISSUE THREAD

**Issue by jenkruk** [filecoin-project/devgrants#542]
# Open Grant Proposal
# Unreal Engine NFT Integration By Filecoin & SWIM

### Unreal Engine API for NFT Integration Powered By Filecoin & SWIM

**Proposal Category:** `integration-adoption`

**Proposer:** [Swim](https://github.com/swimgithub)

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** YES

<br>

# Project Description

We would like to bridge the gap between Unreal and the blockchain by providing the needed Web3 and IPFS json data to game developers to help get these products to market asap. 

Unreal Engine 5 produces some of the most beautiful games to date. There are a vast amount of games currently being developed that hope to integrate the players owned NFT's.  
	
As experienced blockchain developers with ties to Unreal developers, we see a need to help game developers easily incorporate NFTs into their work.  This API data will provide the much needed solution and provide game developers with the json data they require.

## Value
<hr>
This deliverable will mean that Unreal developers do not have to learn Web3 in order to include NFT's into their games, therefore they will be able to focus on what they do best.  

This will simplify their process, resulting in a faster completion of their projects and will encourage users to host on IPFS as this solves a critical need and is a no barrier solution.

Being experienced in blockchain processes, we already have the tools needed to provide this API data.  Therefore, we see this as a risk-free project that provides a win-win solution for Filecoin and Unreal developers.

## Deliverables
<hr>
We will provide a url to the necessary json data that the Unreal developer can pull into their projects.  This data will include the features and values along with a unique id for each of the users owned NFT's that relate to the game.  The Unreal developer can then include this data into the game using the provided url.

<br>

# Development Roadmap

## Milestone 1

Research Phase | 2 weeks | $3,200 USD

* Meet with various Unreal game developers to gather criteria on the needs of the NFT Metadata API to ensure a solid understanding of the various formats and/or metadata needed in addition to security requirements

<br>

## Milestone 2

Creation and Testing Phase | 3 weeks | $20,000 USD

* Create API that will deliver the necessary formats and metadata determined in phase 1, including but not limited to:

	*  web3 development to connect wallet
	*  Contract call to fetch metadata
	*  URL solution to integrate into Unreal
	*  Continuous updating 
	*  FileCoin Integration

<br>

## Milestone 3

Deployment Phase | 4 weeks | $26,800 USD

* Test with game developers
* Instruction and documentation for API
* Deployment

<br>

# Total Budget Requested

Developer Costs Total $50,000

<br>

# Maintenance and Upgrade Plans

Swim will maintain and upgrade this API as needed for as long as it is viable

<br>

# Team Members

- Andy Crosby
- Devon Martens
- Zackary Schmidt
- Jennifer Kruk

<br>

# Team Member LinkedIn Profiles

- [Andy Crosby](https://www.linkedin.com/in/andy-crosby-7b9b4754/)
- [Blake Kuhre](https://www.linkedin.com/in/bkuhre/)
- [Devon Martens](https://www.linkedin.com/in/devon-/)
- [Zackary Schmidt](https://www.linkedin.com/in/zack-schmidt-a71a2185/)
- [Jennifer Kruk](https://www.linkedin.com/in/jenkruk/)

<br>

# Team Website

https://swim.eco/

<br>

# Relevant Experience

- Andy Crosby, Founder at Swim

	Andy, a Futurist & Technologist Blockchain Systems Architect, began his career after graduating from the University of Technology Sydney in 2003 with a Bachelor’s in Business and Leisure Management. After university, he entered the workforce as a technology consultant solution designs architect with 3 of the Big 4 management consulting firms, including KPMG, PwC, and Capgemini.

	In 2014, Andy moved to New York and began working in live streaming to build one of the world's first global live news networks that could stream directly from phone to newsroom. This would become the precursor and backbone to the Citizen app we know today that has revolutionized live streamed, citizen journalism. After the hustle and bustle of the city life, Andy moved to Colorado in 2016 to immerse himself in a higher quality of life as well as to work on the architecture for the Denver Smart City network until 2019.

 

	All the while, Andy’s interest and prowess following the evolution of blockchain technology culminated after having first read the BitCoin whitepaper back in 2012. This became the bedrock for Andy to become the Founder and Chief Tokenomics Officer of Swim, in 2020; the sustainable blockchain with the core focus for renewable energy use across the entire ecosystem. Throughout 2020 and 2021, Swim grew its team and concentrated on building out DAPPs (decentralized applications in the Web3 space). With 2021 being the year for NFTs, Swim was able to ride the wave, launching several drops and providing smart contract services with the tools to make the transition from Web2 to Web3 seamless and equitable for all.

- Blake Kuhre (CURRY), Co-Founder at Swim

	Blake has a decade of entertainment experience with the world’s most beloved brand, The Walt Disney Company, incubating talent to become A-list celebrities and launching Disney Channels Worldwide franchises. Blake was with the Mouse House until growing impatient for more, found it in startups and live streaming, and found it the most in China. Recently exited NASDAQ: MEET post acquisition to Prosieben/General Atlantic for $500MM, one of the largest M&A prior to the pandemic.   

	Blake’s 8 years of Web 2 tech experience focused on monetization; leading to some of the highest-grossing iOS and Android apps, such as Hulu with live TV, Bytedance's transition of music.ly to TikTok, launching Tencent’s e-commerce, gaming and IRL live streaming across global markets, and signing a 3-year live streaming partnership with the world’s largest online dating conglomerate, Match Group.  Blake is passionate about what’s next at the intersection of tech & entertainment including the business of geopolitics, live streaming, monetization via gamification and e-commerce. Also rescues cats in his spare time as Founder & President of Furry Foundation, a 501(c)(3) non-profit that caters to South Los Angeles cats and kittens.

- Devon Martens, Solidity | Blockchain developer and the Senior VP of Web3 at Swim

	Devon began programming in 2015 and become the head of IT maintaining databases at a non-profit. Following that she began to work in finance and blockchain at the home depot's corporate office as an analyst. This sparked her interest as a developer she went on to develop at Georgia Tech and was hired by a partner of theirs 2U where she began as a technical lead moving forward to write a blockchain program taught at 15 different universities and teaching at the University of Minnesota. After several months of freelancing and owning her own blockchain company, she began developing at SWIM.  Now she is the Senior Executive Vice President of Web3 at SWIM.

- Jennifer Kruk is a Full Stack | React | Blockchain Developer for Swim

	Jennifer is a Full Stack Developer with particular affections for React, JavaScript and the Blockchain.  She enjoys integrating API's into her work and is excited to dive in to this project.

- Zack Schmidt is a Solidity | Blockchain developer at Swim

	Zack earned his degree in Chemical Engineering through the University of Minnesota in 2007. He spent 15 years working in product development for water treatment companies including 3M, Pentair, and EcoWater . His interest in blockchain was sparked after reading the BTC and ETH white papers in 2017. Realizing the disruptive potential for the technology he pursued his certification in solidity and python programming through the University of Minnesota with the intention of turning his skills and experience in product development to software development in web3. Since completing his certification in 2021 Zack has been developing smart contracts at SWIM and working with full stack developers to develop various web3 products. 	

<br>

# Team code repositories

- [Swim](https://github.com/swimgithub)
- [Jennifer Kruk](https://github.com/jenkruk)
- [Devon Martens](https://github.com/DevonMartens)
- [Zack Schmidt](https://github.com/schm1263)

<br>

# Additional Information

Blockchain games are on the rise at a rapid pace.  We see an opportunity to help this market grow and help game developers connect to web3 while allowing Filecoin and Swim to be at the forefront of this new territory in it's most explosive phase.

<br>

## Sources

[Coindesk: Number of 'Active' Blockchain Games Doubled in Past Year to Almost 400](https://www.coindesk.com/markets/2022/01/19/number-of-active-blockchain-games-doubled-in-past-year-to-almost-400/)

[Cision: Global Gaming Industry to Cross $314 Billion by 2026](https://www.yahoo.com/now/global-gaming-industry-cross-314-183000310.html)

[Forbes: Does Blockchain Herald The Dawn Of A New Era For Gaming?](https://www.forbes.com/sites/lawrencewintermeyer/2022/01/25/does-blockchain-herald-the-dawn-of-a-new-era-for-gaming/?sh=79fbaa596827)

**Comment by ErinOCon** [comment]
Hi @jenkruk, we would like to fund the outlined work! Please email [devgrants@fil.org](mailto:devgrants@fil.org) to discuss next steps.

**Comment by ErinOCon** [comment]
Hi @jenkruk, would you like to proceed with this project? Please let me know if new contact information is preferred.
