### ISSUE TITLE
Next Step Microgrant: DevNFT

### ISSUE THREAD

**Issue by vinzvinci** [filecoin-project/devgrants#543]
### 1. What is your project? (max 100 words)

 An NFT marketplace for open source repositories and contributions.

https://www.youtube.com/watch?v=lI0kBgQ68Ew 
http://devnft.xyz/

### 2. How are you planning to improve this project? (max 200 words)

 
- DevNFT will have a profile where each developers wil have their collection
- People holding NFT from the collection can join one-on-one video call
- Tipping feature, that people can tip their favorite developers in the top choice of their own token
- Commit feature, which will allow folks to create an NFT of their contribution to the other projects which will look something like these: name, commit message, number of lines of commit, and commit hash

### 3. Is this project open source?

Currently, the project is in the development stage, we don't want to public for now but as soon as possible: The code will be open source with a BSL license.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

  
I agree, we can give weekly updates.

### 5. Does your proposal comply with our Community Code of Conduct?

Yes, it is!

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
> Yes, it began in Encode Club x Filecoin Accelerator

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

> - Shubham Kukreti, [shubhamkukreti204@gmail.com](mailto:shubhamkukreti204@gmail.com) (@KukretiShubham) - Team Lead, Smart Contract Developer
> - Maxime Kubdev, [mkubdev@gmail.com](mailto:mkubdev@gmail.com) (@mkubdev) - Developer Lead, UX/UI Developer
> - Vincent Villafuerte, [vincent.villafuerte1@gmail.com](mailto:vincent.villafuerte1@gmail.com) (@vinzvinci) - UX/UI Design, Marketing Lead
> - Ritvik Shukla, [ritvikshukla261@gmail.com](mailto:ritvikshukla261@gmail.com) (@shuklaritvik06) - UX/UI Design, Content Writer
> - Sreekar Sarvepalli, [lakssar01@gmail.com](mailto:lakssar01@gmail.com), (@sreekar9601) - Smart Contract Developer

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
> It was part of the **EncodeXFilecoin Accelerator**.

**Comment by ErinOCon** [comment]
Hi @vinzvinci, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by vinzvinci** [comment]
> Hi @vinzvinci, This microgrant has been approved! Look out for an email to submit payment details.

Great thanks!

**Comment by vinzvinci** [comment]
Done 
![image](https://user-images.githubusercontent.com/73097560/164367855-ae915bd6-3240-4c0d-b3e2-42544852badb.png)
