### ISSUE TITLE
Next Step Microgrant: Firma

### ISSUE THREAD

**Issue by sunosuporno** [filecoin-project/devgrants#544]
#### Ans. Firma, a decentralised 'link-manager', lets people create their own decentralised 'link-in-bio' page. All of their data lives in IPFS (currently through Pinata). Users can directly login through Google - a web2 product. This gives people low barrier to entry and at the same time take benefits of web 3.0 and stop worrying about things like censorship. We are planning to take advantage of web3 and build cross-chain crypto donation feature as well and therefore enable users to accept payments/donations through their link page. Our current tech stack comprises of MEVN, Solidity, Truffle, Web3.js, Polygon, Alchemy, IPFS. 

[Our Front-End Github Repo](https://github.com/sunosuporno/metacoffee)
[Our Back-End Github Repo](https://github.com/sunosuporno/metacoffee-backend)
[Our Smart Contract Repo](https://github.com/VedWhat/MasterContract-firma)
Apologies for not having a monorepo. We are working on it.
[Demo Link](https://metacoffee.vercel.app/)
[Demo Video](https://www.youtube.com/watch?v=rfz8VJu7Z-g)
  
### 2. How are you planning to improve this project? (max 200 words)
Ans. 
In no particular order, these are the things we want to do within this year:
 * Design a better UI and build out a snappier user experience.
 * Make the dApp gas-less, so it fully achieves a web2-like smooth onboarding.
 * Launch a closed alpha and incentivise early adopters through NFTs (please check [4themetaverse](https://testnet.4themetaverse.xyz) - also built using IPFS (Pinata) and Polygon)
 * Explore migration to web3.storage/orbitDB from Pinata
 * Hire a Marketer/Growth-Hacker and a Community Manager.
 * Introduce more templates and styles to help people design their page more uniquely. 
 * Enable people to accept payments/donations in their link page regardless of chain (by using Biconomy's Hyphen). 
 * Strategise ways to fetch profiles quicker. 
 * Introduce a tiered subscription and have features specially for paid tiers (eg. analytics, removing our branding, etc.)
Bottomline: Build a product at least as good as current players in this space (Linktree, WithKoji, AllMyLinks, etc.)
 
### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  * Ans. Yes. And it has won in Filecoin Prize Pool. We were announced about our selection in a Zoom meeting, so we don't have relevant links/proof for that right now. [Here is the link for the project submission](https://devfolio.co/projects/firma-previously-called-it-as-metacoffee-84a3)

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  * Suporno Sarkar
    * Email: sarkarsuporno36@gmail.com
    * Github: https://github.com/sunosuporno
    * Role: Full-stack Dev
  * Ved Chitnis 
    * Email: ved.chitnis@gmail.com 
    * Github: https://github.com/VedWhat
    * Role: Smart Contract Dev & Designer
* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
    * Ans: [Ethernals](https://ethernals.devfolio.co/)
  * Please link to your hackathon submission
    * [Our Submission](https://devfolio.co/projects/firma-previously-called-it-as-metacoffee-84a3)

**Comment by ErinOCon** [comment]
Hi @sunosuporno, This microgrant has been approved! Look out for an email to submit payment details.
