### ISSUE TITLE
Next Step Microgrant: Punk Cities

### ISSUE THREAD

**Issue by HabacucMX** [filecoin-project/devgrants#545]
### 1. What is your project? (max 100 words)

Punk Cities is a collaborative Web3 to mint and collect IRL places as NFTs, get rewards and participate in DAO governance for public places. Players can mint NFTs by registering, verifying or updating IRL places in the game and get energy and chips to update places or unlock features.

When the place is updated, all the verifiers  get the NFT for that place. The game incentivize local collaboration with global competition to generate data from cities.  We used NFT Storage to upload to IFPS media and metadata from the NFTs minted by the player and piñata for the game assets. 

[Github ](https://github.com/zenbitETH/Punk-Cities)  
[🎮 Demo](https://punkcity.surge.sh/)

### 2. How are you planning to improve this project? (max 200 words)

1. UX/UI research and update
   1. Online workshops with citizens and urban organizations from Querétaro City, México
   2. Open pilot test
   3. New home dashboard and Hud distribution.
   4. Add animations and effects to UI.
   5. Player and cities leaderboards.

2. Migrate to Next.js and update the game with Lens profiles and DAO governance.
    1. Migrate to Next.js app for faster interactions.
    2. Lens Api integration for players' profiles.
    3. Storage on IPFS for images from the profile, post, and governance interactions.
    4. Integration of DAO governance contract.
5. Update smart contracts and game interactions
    1. Update 3d models for Universities, Nature locations, and Trees.
    2. Update energy and chips distribution
    3. Places upgradable to Lv2 and Lv3
    4. Add modals and visuals for loading and transactions screens.
    5. Production DApp for a pilot test.

### 3. Is this project open source?

Yes, Punk Cities is open source

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes, we agree to share weekly updates and a grant report upon conclusion

### 5. Does your proposal comply with our Community Code of Conduct?

Yes, our project complies with  the code of Conduct

### 6. Links and submissions

- [Build Quest 2022](https://showcase.ethglobal.com/buildquest/punk-cities-0w24e) / Winner of Best implementation of NFT collectibles by IPFS/Filecoin

### Additional questions:
**Habacuc Vera** / habacuc@zenbit.mx / https://github.com/HabacucMX / UX/UI and frontend  

**Alessandro Maci** /  alessandromaci96@gmail.com / https://github.com/alessandromaci / Smart Contracts and backend

**Developed @ ETH Global: Build Quest 2022**
- [Punk Cities @ Build Quest 2022](https://showcase.ethglobal.com/buildquest/punk-cities-0w24e)

**Comment by ErinOCon** [comment]
Hi @HabacucMX, This microgrant has been approved! Look out for an email to submit payment details.
