### ISSUE TITLE
Next Step Microgrant: Your Meta World AR

### ISSUE THREAD

**Issue by xx014939** [filecoin-project/devgrants#546]
### 1. What is your project? (max 100 words)

Your Meta World is a decentralised Metaverse, marketplace and suite of NFT tools which empower Web3 users to participate in the next digital revolution.

Front end tools 
https://github.com/xx014939/metaworld-landing/tree/main/software

Unity Scripts
https://github.com/xx014939/unity-code-scripts

Mint a 3D Unity scene as an NFT and pull it into your wallets "Your Meta World" at run time (Previous grant)
Github link will be completed and live before the end of the April.

Marketplace (work in progress)
https://github.com/xx014939/Netlify-Market

https://www.yourmeta.world/ (new website)
  
### 2. How are you planning to improve this project? (max 200 words)

Thus far much of our development has been in VR applications. For the most part we're almost done with this part of Your Meta World (barring aggregating these tools into a single application), however we would like to now venture to the AR realm before launching the projects first complete prototype. 

We've successfully built a bridge between 3D environments/objects and the blockchain. Now we would like to extend this to AR functionality, so NFT holders and creators can easily produce personalised AR photography and experiences with their digital NFT's and NFT collections completely free.
 
### 3. Is this project open source?

Yes, we will use the MIT license.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Yes, of course
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

Yes, the Moralis "Best Use of IPFS or NFT.Storage for Content-Addressed Data" top three prize
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

I am the sole member.

Name: Naail El-Sawah
Github: xx014939
Email: naailelsawah@gmail.com

* If your project was created as part of an event or hackathon:

Moralis 2022 Hackathon

  * Please link to your hackathon submission

https://www.yourmeta.world/ (click on the "old site" link).

**Comment by xx014939** [comment]
@ErinOCon I tagged you in the original issue but putting here for visibility as well.

Unity Scene Minter Project --> https://github.com/xx014939/IPFS-Unity-Scene-Minter

**Comment by ErinOCon** [comment]
Hi @xx014939, This microgrant has been approved! Look out for an email to submit payment details.
