### ISSUE TITLE
Next Step Microgrant: Ancon Protocol and du. data. universal.

### ISSUE THREAD

**Issue by molekilla** [filecoin-project/devgrants#547]
### 1. What is your project? (max 100 words)
Ancon Protocol is the layer 2 ICS 23 proof of existence used by .du which stands for data universal, is a set of products to unify data economy users into Creators, Analysts, and Markets

https://github.com/anconprotocol

https://du.xdv.digital
  
### 2. How are you planning to improve this project? (max 200 words)

Continuing du. baby steps after incubation, we are still looking for major funding, Ancon Protocol is pretty much complete

### 3. Is this project open source?

MIT and Apache

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes

### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions
Our project started as an Open Grant from Filecoin and this grant is for Encode Filecoin accelerator
  
### Additional questions:
https://github.com/lKrayola
https://github.com/menottiRicardo
https://github.com/luissanchez0305

**Comment by luissanchez0305** [comment]
Diferent product that derives from our infrastructure
![image](https://user-images.githubusercontent.com/1278025/164085123-54e488ca-b1c8-4bf5-890f-b1d9f5ccb725.png)

**Comment by molekilla** [comment]
Hi, question? We where in 10 week with Encode club which promise 5,000 usd. Now past 4 weeks and we haven't seen anything yet? I had to let go my team and myself looking for some income.

Of all the incubators, there is zero publicity about that particular one. @realChainLife could you please help me understand what went wrong? I need those 5000 because IFESA owns employees salary and liquidation.

Thanks
Rogelio
CEO

**Comment by ErinOCon** [comment]
Hi @molekilla, thank you for the recent microgrant submission and for your participation in the Encode program. This microgrant has been approved! Look out for an email to submit payment details.

In regards to your inquiries around timing, it looks like this proposal was submitted last week. If there was a delay outside of this Github submission, please let me know. I would be very happy to review.
