### ISSUE TITLE
Next Step Microgrant: Katreena NFT's

### ISSUE THREAD

**Issue by TerratekMusic** [filecoin-project/devgrants#548]
### 1. What is your project? (max 100 words)
Katreena is a 3D NFT marketplace platform where you can mint and display your 3D NFT's in augmented reality, giving the NFT world a hole new connection with the real world. But Katreena is not only that, we also care about ecological impact and 
conservation of natural ecosystems and for that we have our native NFT called "Katree" which is attached to an specific green area monitored by satellite images. All funds made by minting/selling/buying katrees will be donated to ecological organizations. We use IPFS to store all NFT data & files.

https://github.com/TerratekMusic/katreena

https://ar-nft.app/
https://www.youtube.com/watch?v=NNopLkugpF0
  
### 2. How are you planning to improve this project? (max 200 words)
1.- We will finish to implement the katree's and 3D NFT minting.
2.- Improve the Augmented Reality system in our platform.
3.- Implement Marketplace.
4.- Improve satellite data API and UI (so users can see their katree geolocation in our platform easily).
5.- Develop portal for Ecological Organizations to sign up, verify their identity and get funds from katree's near their location.
6.- Hire 3D artist's to create awesome Katree designs.
7.- Develop & Improve overall UI and UX.
8.- Create videos to explain our product and the goals of Katreena.
9.- Design and develop landing page.

 
### 3. Is this project open source?
Yes it has MIT license.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes.

### 6. Links and submissions
The project started at the Moralis Avalanche Hackathon 2022 and was part of the Moralis Avalanche IPFS/Filecoin leadership board
winning a a portion of the prize pool. 

https://moralis.io/avalanche-hackathon/

  
### Additional questions:
Team members:

Iván Avila - Founder, Frontend developer, Designer.
sunset.dfilms@gmail.com
https://github.com/TerratekMusic

Enrique Sanchez - Backend developer.
luisito1247@gmail.com
https://github.com/enriquesanchezz

Mario Andrade - Legal Consultant, Smart Contract Enthusiast.
mandradeu@andradeyasociado.com.mx

**Comment by ErinOCon** [comment]
Hi @TerratekMusic, This microgrant has been approved! Look out for an email to submit payment details.
