### ISSUE TITLE
Next Step Microgrant: Social3

### ISSUE THREAD

**Issue by Tlazypanda** [filecoin-project/devgrants#549]
### 1. What is your project? (max 100 words)
Social3 is the first-ever Web3 based social hiring platform that incorporates a refer-&-earn model but for talent. With Social3, degens can hop onto the website and refer talent by locking in a fixed amount of tokens to earn a percentage of the recruiting fee on successful conversions. Social3 also maintains your social Proof-of-work by verifying NFTs achieved through different Web3 EdTech based startups such as Buildspace, Questbook, Layer3 and many others. Thus helping recruiters vet through talent with just a click.

**Filecoin is integral for our project** since our Profile Building requires users who are not that familiar with Web3 to **upload their Web2 based certificates (Secured through Coursera, Udemy etc).** We upload these certificates on IPFS so that this data is available in a decentralised manner. Apart from this we also verify whether the uploaded certification is valid or not by applying PDF Parsing and special certificate code validating through Coursera/Udemy APIs. This incentivises users to upload the right data. 

Github Repo: https://github.com/Tlazypanda/social3-storage
Landing Website: [http://social3.club/](http://social3.club/)
Twitter: https://twitter.com/Social3Club
  
### 2. How are you planning to improve this project? (max 200 words)
PHASE 1 (IN PROGRESS TO BE COMPLETED BY JUNE 2022) (Funding Ask: 3000 USDC) :-Beta version of Product in progress with the social profile and hiring referral ability.

- Integrating NFT avatars for users to be stored on IPFS using NFT.storage.
- Creating files of the on-chain resume/profile page to be stored on IPFS.
- Setup referral smart contract to lock token and claim funds when listing expires/ successful conversion.
- Integrate Notifications through EPNS for claim funds

PHASE 2 (IN PROGRESS TO BE COMPLETED BY JULY 2022) (Funding Ask: 2000 USDC):

- PR and Community Building through newsletters, opportunity notifications
- Partner up with companies to list jobs.
- NFT Drop for the first 1000 members in exchange for an initial product review
- Invite founders/engineers from multiple companies to share info about their company and the interview process.
- Partner up with buildspace, layer5 etc. to verify their NFTs as Proof of Work.
 
### 3. Is this project open source?
Yes, this project is opensource under MIT License.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes, apart from submitting weekly/bi-weekly reports and final grant report I’m also interested in sharing blogs to help other users to build on Filecoin. 
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

- Name: Sneha Mishra Role: Creator + Backend + Smart contract
    - Intro: I am Sneha, a Blockchain Developer and full time builder. Having worked with Blockchain companies like Polygon, Buildspace and Reneverse I have the background knowledge of how the Web3 ecosystem works with ideas to contribute on both the development and business side. I have also been super involved on the community side as part of programmes like ETHWomen, BuildspaceWomen, Phoenix Guild Solidity Mentor and Buildspace India which has allowed me to tap into my network and help make things happen.
    - Email: [mishrasneha.bb@gmail.com](mailto:mishrasneha.bb@gmail.com)
    - Github: Tlazypanda
    
- Name: Adarsh Tripathi Role: Frontend Developer
    - Intro: Frontend developer with experience of working on react, react native and most recently on web3 based libraries such as etherjs.
    - Email: [itm2017004@iiita.ac.in](mailto:itm2017004@iiita.ac.in)
    - Github: rush-tea
    
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) Ideated as part of Devfolio’s ETHWMN programme as master project, build in progress.
  * Please link to your hackathon submission: N/A

**Comment by ErinOCon** [comment]
Hi @Tlazypanda, Thank you for your proposal. We will review this and get back to you, on this thread, with a status update or questions.

**Comment by Tlazypanda** [comment]
Hey @ErinOCon can you please let me know the status on this? Thank you! :v:

**Comment by ErinOCon** [comment]
Hi @Tlazypanda, This microgrant has been approved! Look out for an email to submit payment details.
