### ISSUE TITLE
Next Step Microgrant: <Cratch>

### ISSUE THREAD

**Issue by skidrow8852** [filecoin-project/devgrants#550]
### 1. What is your project? (max 100 words)

Cratch is the first decentralized live & video streaming platform in the Metaverse. 
It allows users to create or watch live streams in a Mobile App, Website Platform and  Metaverse world, while rewarding them from every minute they spend on the platform. 
We are building this platform to solve many problems in the video sharing and live streaming sectors such as censorship, data collection and targeted advertisement. All of the data and media files uploaded in our platform are stored in IPFS network.

Github repo   :    https://github.com/skidrow8852/Cratch_Beta

website    :      https://cratch.io/  
 

### 2. How are you planning to improve this project? (max 200 words)

Our mission is to make content creation, live streaming and video sharing easy, fun and interactive, and for that we will :
      •	Build our own RTMP server with IPFS storage ability.
      •	Build Backend for both the platform and the Metaverse.
      •	Implement NFTs creation for Content Creators.
      •	Create our mobile app.
      •	Ensure data is available at all times and availability of Media files uploaded by content creators media is uploaded to IPFS thus  making storage of Cratch distributed and secure.

 
### 3. Is this project open source?
Yes

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes.

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  -  We were finalists and won the IPFS/Filecoin "Top 3" prize for Best Use of IPFS or NFT.Storage for Content-Addressed Data at the Moralis Avalanche 2022 hackathon!
  -  We received $5k for the prize, link : https://filfox.info/en/message/bafy2bzaceb7dotiukqzwsntsu6j7fs4saqbkzx5hlzxd5tcx2s6rtmdwhc6ww
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
   * Youssef Rais
          - Full stack web developer and blockchain enthusiast.
          - Github : https://github.com/skidrow8852
          - email : amine20solo20@gmail.com
    * Daniel Palacio
          - Project Manager 
          - email : ossonevevo@gmail.com
* If your project was created as part of an event or hackathon:
              * Yes
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
           * Moralis Avalanche 2022 hackathon
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @skidrow8852, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by skidrow8852** [comment]
Hello @ErinOCon Thank You for accepting our application, we did submit a transfer request as described in the email.
