### ISSUE TITLE
Next Step Microgrant: DAOverse

### ISSUE THREAD

**Issue by rajkaria** [filecoin-project/devgrants#551]
### 1. What is your project? (max 100 words)
We are creating an on-chain review system to make discoverability in web3 easier. The issue right now is there is no way to get people's opinions on how their experience of certain DAO or communities is. We are giving them a platform to share their views about a community that can help others to make proper decisions.

In web2 solutions, the issue is reviews can be bought or deleted as per choice, which is inefficient. That is why we are building a trustless solution to give voice to people's opinion.

Links:
https://www.daoverse.app
  
### 2. How are you planning to improve this project? (max 200 words)
1. We want to enable dashboards for users and DAOs from where they can change the data of their data and see statistical data on number of reviews.
2. We will expand it to all the ecosystem of web3, where people could write reviews and easily discover NFT projects, DeFi, DAO tools, etc.
3. We want to create APIs that can be used by anyone to show the review data in their dapp.
 
### 3. Is this project open source?
Not open source yet

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes, we would love to keep filecoin team in the loop
  
### 5. Does your proposal comply with our Community Code of Conduct?

yes it does

### 6. Links and submissions
* no, it's not available, we haven't participated in any hackathon.
  
### Additional questions:
Team members:
Raj - Founder - rajkaria98@gmail.com
John Swaroop - Full stack developer - johnswaroop11@gmail.com

**Comment by ErinOCon** [comment]
Hi @rajkaria, thank you for submitting this proposal! Is your team building a repo/code that is available to view? Also, can you confirm when you expect the project to be open source?

**Comment by rajkaria** [comment]
Hey hi @ErinOCon we are having a private repo as of now, if you want to see it before we make it live, I could add you as a contributor. Our project will be open source by end of q2 2022 most probably. Let me know if you need any more details

**Comment by ErinOCon** [comment]
Thanks, @rajkaria! Funding open source work is a key point in our microgrant criteria. Once your project is ready to open source and the repo is public, please feel welcome to reapply for this grant!

**Comment by rajkaria** [comment]
Hey @ErinOCon we made it open source last week, here is the repo https://github.com/Daoverse123/client

let me know if you need more details

**Comment by ErinOCon** [comment]
Thanks, @rajkaria! Can you confirm if and how IPFS, FIlecoin, or related tech will be used for this project?

**Comment by rajkaria** [comment]
@ErinOCon We are having an upgradable NFT architecture, we will be using IPFS for that and to store all the data on-chain.
