### ISSUE TITLE
Next Step Microgrant: Simple.eth

### ISSUE THREAD

**Issue by briansoule** [filecoin-project/devgrants#554]
### 1. What is your project? 
Simple.eth makes it easy to publish an IPFS hosted website for your .eth domain. We went viral on Twitter this week: https://twitter.com/simpledoteth/status/1517120435187499011

Homepage: https://simple.eth.limo
  
### 2. How are you planning to improve this project? (max 200 words)
We would like to finalize a polished profile page for users to publish.
 
### 3. Is this project open source?
Yes

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions
The project has not been submitted, but a Ally encouraged us to apply for the microgrant during ETHAmsterdam.
  
### Additional questions:
Brian Soule, brian@briansoule.com, Github: briansoule
David Noah, david.t.noah@gmail.com
Joeseph Williams, josephwilli12@gmail.com

Was published during Devconnect, concurrent with ETHAmsterdam

**Comment by ErinOCon** [comment]
Hi @briansoule, thank you for your submission! Is your team building a repo/code that we are able to view?

**Comment by ErinOCon** [comment]
Hi @briansoule, do you have an update at this time?

**Comment by ErinOCon** [comment]
Hi @briansoule, do you expect to provide an update in the near future? A full description of your project and the next steps you plan to take with this grant would be very helpful for our review. For reference, previous grants approved through the program can be found [here](https://github.com/filecoin-project/devgrants/blob/master/microgrants/accepted-microgrant-applications.md).

**Comment by ErinOCon** [comment]
This issue has been closed. Please feel welcome to reapply once more details become available!
