### ISSUE TITLE
Next Step Microgrant: Evidence DAO

### ISSUE THREAD

**Issue by cryptotwilight** [filecoin-project/devgrants#555]
### 1. What is your project? (max 100 words)

The Evidence DAO project is to create a fully searchable project deliverable repository that can be used by DAOs to streamline the collection and curation of project deliverables. The concept is to create a single decentralized place where projects triggered by DAO proposals can store their deliverables on completion. This would allow DAOs to assign independent assessors of project deliverables to validate the quality and provide assent for payment, enabling the DAO assigned project administrator to quickly, with transparency and accountability release community funds to the project team. The importance of this streamlining increases as DAOs scale as the need for DAOs to know what they know increases. The project uses IPFS and the EVM with IPFS providing content addressing for deliverables and the EVM providing search and workflow functions

Demo 
https://raspy-frost-1289.on.fleek.co/

Github
https://github.com/cryptotwilight/evidenceDAO 

### 2. How are you planning to improve this project? (max 200 words)

The scope of this work will be to:
- Build out the remaining dashboards 
- Develop the DAO teams function
- Investigate integration with existing DAO governance tools such as Tally, Sybil etc
- Investigate integration with existing Treasury management tools such as Gnosis Safe 
- Implement open source IPFS content addressing based search functions and basic encryption 

### 3. Is this project open source?

This project outputs under the grant will be published under Apache 2.0 licensing

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

Agreed
  
### 5. Does your proposal comply with our Community Code of Conduct?

Yes

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:   Yes
Submission: 
https://showcase.ethglobal.com/daohacks/evidence-dao-y0mii

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Tony Kunz 
Role: Creator / Core Dev
Email: tonyusheuk@gmail.com

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal 
 Scaling Ethereum)
(DAOHacks by EthGlobal)[https://showcase.ethglobal.com/daohacks]

  * Please link to your hackathon submission
 https://showcase.ethglobal.com/daohacks/evidence-dao-y0mii

**Comment by ErinOCon** [comment]
Hi @cryptotwilight, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by ErinOCon** [comment]
Hi @cryptotwilight, Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

**Comment by cryptotwilight** [comment]
Hi Erin

Thank you for this, can I confirm you've received the final repor?

Thank you

Tony

**Comment by ErinOCon** [comment]
Hi @cryptotwilight, yes, we have received your report. Thank you!
