### ISSUE TITLE
Storage³ lightweight consumer-focused UI drag and drop Build package

### ISSUE THREAD

**Issue by devcloning** [filecoin-project/devgrants#560]
### 1. What is your project? (max 100 words)

    https://store.devbank.dev/
    https://ipfs.devbank.dev/
    https://nft.devbank.dev/
    https://color.devbank.dev/

Storage³ lightweight consumer-focused UI

This evolution challenge consists in a decentralized storage system, being sort of a folder used as a staging area, however in a extra decentralized method. Smart contracts to track file specifications, size, type, up-loader, file hash. 
devbank.dev samples are built with JavaScript to ensure smart contracts are accomplishing the expected functionalities.
Storage³ lightweight consumer-focused UI, permits the client/user to add a file to a decentralized system referred to as IPFS/Filecoin System, sharing it with anybody who knows of the hash identifier. 
The file ownership is tracked on the blockchain. It refers to the hash and as you can see in the presented samples, it is optional with not showing the content or showing it under corresponding bidirectional smart contract. 

https://devbank.dev/
https://github.com/devcloning 

  
### 2. How are you planning to improve this project? (max 200 words)
Improving and implementing [pinning-lists](https://docs.estuary.tech/pinning-list), Improving the smart contract users interface to deploy users owned smart contracts to any other supported ethereum chains and/or combinations thereof and presenting the app as customizable open-source (MIT license for code or CC-BY-SA 3.0 license) plug&play plugin to be deployed on users websites, providing exponent IPFS/Filecoin storage³ entries. 

Rewrite and providing optional “truffle-config”s for simple&fast visual studio code modifications.

    npm install
    npm install -g truffle
    npm install –save @truffle/hdwallet-provider
    truffle compile
    truffle test
    truffle migrate –network ropsten
    npm run build

The final product would be customizable drag and drop one stop shop “build” packages as instant deployable web applications with/and/or/without Ethereum chain(s) or combinations thereof, with great value proposition to the web3 development and can attract and inspire a lot of starting and aspiring developers to use IPFS/Filecoin as their choice of storage.

The Storage³ plug&play drag and drop "Build package is intended to be installed on any cPanel environment, also on shared hosting.
 
### 3. Is this project open source?
Yes

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* No
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Hans Schulte, https://github.com/devcloning , hans@devbank.dev , Dev Chief

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @devcloning, thank you for submitting this application! We recommend [usability testing](https://www.nngroup.com/articles/usability-testing-101/) for the website.

This microgrant has been approved! Look out for an email to submit payment details.
