### ISSUE TITLE
Four Decentralisation Protocols Book

### ISSUE THREAD

**Issue by soapdog** [filecoin-project/devgrants#561]
# Open Grant Proposal: `Four Decentralisation Protocols Book`

**Name of Project:** Four Decentralisation Protocols Book

**Proposal Category:** `docs`.

**Proposer:** soapdog

**(Optional) Technical Sponsor:** Dietrich Ayala

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** The book will be CC 4.0 licensed. The source-code for the samples will be MIT licensed.

# Project Description

An introductory book called "Four Decentralisation Protocols". It is a practical guide to begin ones decentralisation journey by exploring four popular protocols: IPFS, Hypercore, Secure Scuttlebutt, and ActivityPub.

The book is divided into four parts, one for each protocol. Each part is composed of three chapters:

* An introduction to that protocol.
* Playing with that protocol from a user's perspective by leveraging a popular tool in that ecosystem.
* Writing a small project using JS and official SDKs for that protocool.

At the end of each part, I provide links for futher references so that the reader can dive deeper if they're so inclined.

**This proposal covers the development of the IPFS part of the book.**

I'm not going to explore FileCoin on this book. It covers only IPFS, IPNS and dnslink. This book doesn't cover any form of cryptocurreny, NFT, or similar technologies.

## Value

Decentralisation is a hot topic and there is a lack of good introductory materials that covers more than a single project. Most decentralisation-adjacent content that is available right now is either trying to push a single project forward (understandable) or pushing some agenda (less acceptable). A book like this one is a taster that allow curious people to dip their toes into the decentralisation ecosystem without needing to invest too much effort into complex documentation and tools.

The value for Protocol Labs is that this book not only serves as a hands-on lightweight introduction to IPFS, but that it will be read by people who would not necessarily go after IPFS documentation. Because the book covers multiple protocols, people who are more interested in another protocol will end up picking the book and checking all the protocols available thus exposing IPFS to an audience that it can't reach right now.

## Deliverables

* eBook called "Four Decentralisation Protocols". It will be sold online and also licensed using CC which means it can be copied around and offered on other sites.
* Git repo with source code for the samples.
* Git repo with the manuscript for the book.

## Development Roadmap

This proposal covers only one part of the book development: The IPFS part. 

| Date | Stage |
|------|-------|
| May 2022 | Initial draft of the 3 IPFS chapters. Book early release for alpha and beta readers. |
| 1st half of June 2022 | Revision and editing of IPFS chapters based on feedback from early readers. |
| 2nd half of June 2022 | Release of final version of the book. |

I'm settling on an accelerated release model for this book based on multiple early releases in May.

## Total Budget Requested

Even though this project has a wider scope than just IPFS, this proposal covers only the IPFS part of it.

| Budget | Notes |
| ------|--------|
| $4.000 | Research and Drafting the IPFS chapters |
| $2.000 | Creating the sample for the IPFS part |
| $3.000 | Editing, Layout, and Revision |
| **$9.000** | **TOTAL BUDGET REQUEST**|

All three steps in this budget breakdown intersect with one another. They're vaguely parallel efforts that require going back and forth between development, revision, and writing. These are not sequential steps and thus can't be placed on a rigid schedule breakdown.

What is clear is that the bulk of the writing and development process happens in May 2022, while the editing and revision happens in June 2022.

Releasing a book as a self-published author requires one to wear all the hats that are usually distributed among different professionals in a traditional publisher. There is a lot of steps involved that demand a lot of time to be done properly. The amount requested reflects that this is a full-time commitment and that I live in an expensive city (London). Also, a sizeable chunk of this budget will end up going towards tax payment.

## Maintenance and Upgrade Plans

By releasing the book in eBook format, I'm allowed to update it as frequently as I see fit. I envision multiple iterations of the book while the drafting and editing phases are going on in May and June. 

After the book is released, a new release will only be issued if the code on the book is no longer buildable or if one of the protocols has a drastic change that renders the content invalid. 

# Team

## Team Members

Andre Alves Garzia

## Team Member LinkedIn Profiles

My LinkedIn profile is not really useful. Writers don't rely on LinkedIn much, but here it is: 

https://www.linkedin.com/in/andregarzia/

## Team Website

https://andregarzia.com

## Relevant Experience

I'm a published hybrid author with both self-published books and traditionally published books. So far I have published six books which have more than 10k readers combined. A recent review of my work can be seen in [this blog post from a happy reader](https://www.matthewhughes.co.uk/roguelike-development-andre-garzia-review/). 

As a developer I've been active in the decentralisation space for many years. I've written my own client for different protocols, gave talks at various conferences introducing many new people to decentralisation, and written part of the official documentation for other protocols such as SSB.

## Team code repositories

https://github.com/soapdog

# Additional Information

## Disclaimer of other potential funding sources in this project. 

I'm also trying to pursue a similar funding from Secure Scuttlebutt Maintenance Funds to cover the SSB part. The proposal is quite similar to this one (they're being written in tandem and use most of the same content).

There is a budget difference between both proposals that reflects the fact that I'm much more knowledgeable about SSB and can reuse a lot of my experience and code from being an active developer and writer in that ecosystem in this book. Writing the SSB part will be a lot faster than the IPFS part which requires more research and training for me.

**Comment by ErinOCon** [comment]
Hi @soapdog, we would like to fund the outlined work! Please email devgrants@fil.org to discuss next steps.
