### ISSUE TITLE
Next Step Microgrant: <MyDonate>

### ISSUE THREAD

**Issue by Brilliant497705** [filecoin-project/devgrants#565]
### 1. What is your project? (max 100 words)
<!
MyDonate is donation platform in the web3 space that allows the general public to raise funds in ETH to support whatever project (from education through to famine). We allow the fundraiser to set the target amount and any other component of the fund raising. We allow users to connect to the platform with their preferred wallet and undertake activities. We also allow users to donate any amount with their preferred wallet in whatever cryptocurrency including filecoin to a particular fundraising by going through the categories.  For testing purpose, use kovan testnet on the working url or use any testnet and configure the network to your preferred testnet once you clone the git repository. The media of fundraising are stored on the IPFS server.

https://github.com/mendsalbert/myDonate
https://mydonate.netlify.app/
  
### 2. How are you planning to improve this project? (max 200 words)
 We intend to take this project to the public domain to serve it's purpose in the next 2 months. We are looking for possible ways we can verify the credibility of fundraisers.
 
### 3. Is this project open source?
Yes

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes

  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Brilliant Kwakye, kwakyebrilliant@gmail.comk, I worked on the documentation and Frontend.
* Albert Mends, mendsalbert@gmail.com, mendsalbert , I worked as a full stack developer. From the Backend to the frontend.
* Daniel Sarkodie, dsarkodie500@gmail.com, AbrantepaSark ,I worked on the UI/UX of Sympodium to have the best user experience.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Chainlink 2022 Hackathon
  * Please link to your hackathon submission
https://devpost.com/submit-to/15086-chainlink-spring-2022-hackathon/manage/submissions/326108-mydonate/

**Comment by ErinOCon** [comment]
Hi @Brilliant497705, thank you for your proposal! Can you briefly describe the next steps you will take with this specific grant? Also, it looks like the hackathon link provided isn't working. Do you have an updated one available?

**Comment by Brilliant497705** [comment]
Our next steps:

* We will allow fundraisers to upload video to the platform as part of their supporting media which will be stored on the IPFS server.
* We will also add additional features to the platform which includes allowing fundraisers to provide supporting documents to their fundraising.
* We will add admin dashboard to the platform to help perform some checks and balances on fundraising and many other activities.
* We have started working on a mobile version of the platform as we prepare to push this project into the public domain.
* We intend to implement a model that will help us generate revenue from donors in order to sustain this project.
* We hope to have this project into the public domain in the next month or two.

Sorry for the link provided earlier, an updated link:
https://devpost.com/software/tipster-k8qcta

**Comment by Brilliant497705** [comment]
Our next steps:

1. We will allow fundraisers to upload video to the platform as part of
their supporting media which will be stored on the IPFS server.

2. We will also add additional features to the platform which includes
allowing fundraisers to provide supporting documents to their fundraising.

3. We will add an admin dashboard to the platform to help perform some
checks and balances on fundraising and many other activities.

4. We have started working on a mobile version of the platform as we
prepare to push this project into the public.

5. We intend to implement a model that will help us generate revenue from
donors in order to sustain this project.

6. We hope to have this project into the public domain in the next month or
two

Sorry for the link provided earlier, an updated link:
https://devpost.com/software/tipster-k8qcta

**Comment by ErinOCon** [comment]
Hi @Brilliant497705, thank you for the additional information! This microgrant has been approved! Look out for an email to submit payment details.

**Comment by tippi-fifestarr** [comment]
Nice!
