### ISSUE TITLE
Protocol for bundling NFT and generaing content based on bundled NFTs

### ISSUE THREAD

**Issue by Pe4enable** [filecoin-project/devgrants#566]
# Open Grant Proposal: `DoNFT`

**Name of Project:** `DoNFT`

**Proposal Category:** `app-dev`

**Proposer:** `pe4enable`

**(Optional) Technical Sponsor:** `@TkKonstantin Tkachuk Konstantin`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** `Yes`

# Project Description

## Problem 

Also there isn't technology for advanced management NFTs and creating hierarchical structure inside NFTs.

We are going to solve Collectible lifecycle problem.
When collection lose hype around it, it's start just holding on wallets without movements.

## Value

Our protocol provide mechanism for modificating NFT which provide gamefication and new attantion to old collection.
Unlike of wrapping, bundling allows to save original NFT for future reusege.

Moreover creating hierarchical structure "inside" NFT provides new opportunities for creating new type of products where is possible to manage rights or options without changing original NFT but just additing NFT-based artifact in bundle.

From modification logic side, we are going to create standart for storing implementation of modification algoritms (not only ML) and theirs artifacts on IPFS. This provide one more way how decentralised calculation could be implemented.

In addition to the previous, we have to solve the problem with delegated file access control.

## Deliverables

There you can find breife descriotion of the protocol
https://docs.google.com/document/d/13RSSjjvsALcE6zmQkGFvekFzQJk5ILa4tfJCa4TD3Rg/edit
Implementation of protocol will include
- set of smart contracts for EVM-competibale blockchains
- set of smart contracts for NEAR blockchain
- set of smart contracts for Solana blockcahin
- standart of backend (incluede ML-based) which downloading implementation and artifacts from IPFS
- standart of storing implementation and artifacts on IPFS
- frontend for working with bundles on different blockchains
- frontend for working with backend and artifacts
- a few modification service examples

## Development Roadmap

1 month 
5 developers (1 frontend, 1 data scientist, 1 python dev,  1 solidity dev, 1 QA) + infrastructure costs 
20k$
NFT bundling protocol for EVM-competibale blockchains 
centralized backend that downloads artifacts from IPFS 
develop a format of DL models and artifacts which will be stored in IPFS
frontend for working with bundles

2-3 months
5 developers (1 frontend, 1 data scientist, 1 python dev, solidity dev,  1 QA) + infrastructure costs
30k$
service template for DL models launching 
frontend for working with backend and artifacts on IPFS
proposal of decentralized backend with DNS-alike technology with access policies of artifacts management 

4 month
4 developers (1 python dev,  near dev, solana dev, 1 QA) + infrastructure costs
15k$ 
NFT bundling protocol for Near and Solana blockchain
testing and working with feedback

Total
65k$

## Maintenance and Upgrade Plans

Next steps is onboard DataScientists and Collection Creators (we are negotiating with few collections)
Collaborating with NFT-martketplaces (we already have agreements with raribles and mindbase)
Collaborating with metaverses and GameFi
Support protocol and make improvements

# Team

## Team Member (LinkedIn Profiles &  Relevant Experience)

Arsenii Pechenkin
https://www.linkedin.com/in/arsenii-pechenkin/
For the last 8 years has been working in IT industry from developer positions. 
Last 4 years is working on crypto projects  
- Digital Morgage System on Corda DLT of govetments of Georgia 
- Crypto-payment system for Waves Platfom
- non-custodial crypto wallet in telegram bot (ButtonWallet) and others
Serial winner of huge amount of hackathons all around the world.

Daria Samsonova
https://www.linkedin.com/in/daria-samsonova-3a933b230/
NLP data scientist 
- experienced in creates voicebots (with AI magic under the hood)
- Master degree in Computer

Natalia Kopylova
https://www.linkedin.com/in/natalia-kopylova-014486b1/
NFT artist
member of collaboration NFT 256

## Team Website

donft.io

## Team code repositories

https://github.com/DoNFT

# Additional Information

https://docs.google.com/document/d/13RSSjjvsALcE6zmQkGFvekFzQJk5ILa4tfJCa4TD3Rg/edit

**Comment by ErinOCon** [comment]
Hi @Pe4enable, thank you for your proposal. We would like to fund the outlined work! Please email grants@filecoin.org to discuss next steps.
