### ISSUE TITLE
Open Grant Proposal: SAO Network

### ISSUE THREAD

**Issue by vricale** [filecoin-project/devgrants#567]
# Open Grant Proposal: `SAO Network`

**Name of Project:** SAO Network

**Proposal Category:** `app-dev`

**Proposer:** vricale

**(Optional) Technical Sponsor:**

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Please respond with either "Yes"

# Project Description

SAO, an abbr. for Storage Aggregated/Autonomous Organization, is a decentralized storage network that utilizes the distributed peer-to-peer networks (e.g. Filecoin, Ethereum, Polygon) to create a framework for data to be managed by a Storage DAO. It provides an effective mechanism for the data to be verified, stored, and readily available for any service or Web3 application.

![img](https://3280704082-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2FJ1lcmSyp0T4hJjEZ5QwT%2Fuploads%2FWYeJI81wuRYrSAVAce7N%2FSAO%20Network-2022-04.png?alt=media&token=979e159f-09d9-4fd8-9cf5-751430347f47)

In phase one, SAO network will run the Filecoin miner nodes to help to store the useful data and make earnings from the storage mining business. We will make the miner nodes run publicly, transparently, and governed by a DAO. The proceeds of mining business will be distributed with a set of rules encoded on Ethereum, or Filecoin in the future (if Filecoin network supports smart contracts someday).

SAO network is designed to give NFT creators and NFT markets a single, effective, customizable, integrated productivity tool for storing useful data on their own for a certain period as expected or even permanently on a decentralized storage network like Filecoin, rather than on a central server; and it takes full advantage of the IPFS system, the oracle solutions and the latest AI recognition technologies to protect and track the copyright on any piece of painting, writing, music, etc. It will be a tool and community platform that users can trust, control, and extend to their liking. We want to do away with the terrible user experience of the current centralized apps and the data service.

In the next step after fundraising, SAO will provide an easy-to-use store pattern of any data that is useful or meaningful for our users on Filecoin Network, including files, pictures, videos, music, digital artworks, and data backup, etc. SDS integrates the smart contract based on multiple blockchains with oracle technology. Also, SAO will provide a powerful search engine for useful data stored in SAO, like NFTs, historical documents, Meteorological data, online libraries, etc.

 The Web 3 era is coming. And also we believe the SAO network has an enormous collaborative potential that the future Metaverse world needs.

## Value

The SAO network will become one of the most easy-to-use tools in the Filecoin ecosystem.

It will provide users with an easy way to upload and store files on to the distributed peer-to-peer networks, release a feature of store-to-earn to reward the data providers, enable users to mint NFTs with metadata of their stored files, provide Web3 applications with some publicly available data they need, create a standard accounting system for data billing and pricing to benefit the data providers.

Besides, the Filecoin mining DAO will also engage more people to take part in the Filecoin storage mining. At the beginning, we will provide the hardware and software solution for free and the only thing that users need to do is to stake Filecoin in the nodes.

## Deliverables

- Launch a publicly, transparently, and jointly FIL-mining DApp governed by a DAO.
- Launch an easy-to-use store pattern of any data that is useful or meaningful for our users on Filecoin Network.
- Launch a search engine/navigation.
- Initiate a Data DAO for Web 3 and Metaverse world using the blockchain technologies, oracle solutions, token economy model, and AI recognition technologies, etc.

### Milestone 1 Jointly FIL-mining DApp

  - SAO Network is set to upgrade the concept of cloud mining to “joint mining”. With strong technical know-how in the development and operations of Filecoin storage mining, the core team of SAO Network has developed a “Joint Mining” product. It allows users to join the mining business to earn FIL (a cryptocurrency that powers the Filecoin network) by staking FIL and obtaining a certain amount of storage power shares. We call it “stake-to-earn”.
  - Upgrade SAO network to enable the FVM (Filecoin Virtual Machine)  to automatically distribute mining revenue in Joint Mining App.
  - Tokenization of the storage power certification within Joint Mining app.

Already online: https://sao.network/#/miningpool

  ### Milestone 2 SAO Data Store

  Demo: https://staging.sao.network/#/datastore

  - Open the API key for enterprise clients onboarding data to Filecoin.

  - Release SAO Data Store App for any clients onboarding data to Filecoin.

  - Provide optimal storage solutions according to client requirements in Data Store.

  - Launch data marketplace for storage providers and clients in Data Store.

  ### Milestone 3 Search Engine

  - SAO Network is to provide a powerful search engine for useful data like NFTs, historical documents, Meteorological data, online libraries, etc., which comes from the publicly available data of “Sao data store” and public files and research documents.

  ### Milestone 4 Storage DAO

  - The Storage DAO of SAO Network will be a completely decentralized storage autonomous organization that governs SAO Network. It will consist of core team, data providers, validators, mining shareholders, community members and other stakeholders that contribute to the security and stability of SAO Network. The Storage DAO will operate in a truly democratically autonomous way to determine how the Network functions and how prospective incentives are distributed, so as to serve the interests of every single user and stakeholder.

## Total Budget Requested

| Milestones                                                   | Cost Items                                                   | Budget Amount | Time |
| ------------------------------------------------------------ | ------------------------------------------------------------ | ------------- | ---------------------- |
| Jointly FIL-mining DApp | Filecoin miner hardware, Filecoin mining software development, incentive Mechanism Design of the DAO | $15,000       | 2 week remaining |
| SAO Data Store | Cloud Server; Cost of Development | $15,000 | 4 weeks |
| Search Engine | Cloud Server; Cost of Development | $15,000 | 4 weeks |
| StorageDAO | TBD                                                          | $5,000    | 2 weeks          |
| Total |  | $50,000 |  |

## Maintenance and Upgrade Plans

# Team

- **Hedra Labs** 

## Team Website

Our website - https://sao.network

Twitter - [@SAONetwork](https://twitter.com/SAONetwork)

Medium - [@SAONetwork](https://saonetwork.medium.com/)

Discord - [@SAONetwork](https://discord.gg/q58XsnQqQF)

Email - [contact@sao.network](mailto:contact@sao.network)

## Relevant Experience

Hedra Labs is dedicated to supporting diversiform Web3 applications and mass Web3-natives by creating a storage protocol (SAO Network) and a decentralized autonomous organization (a storage DAO). We are a fully distributed team with all developers working remotely in the US, Canada, Singapore, South Korea, China, Czech, etc. However, we are holding the same goal to make our protocol and ecosystem applications more accessible. The core development team has rich experiences in IPFS and blockchains. We have members who used to be technical directors of celebrated mining Pools, extensively experienced in blockchain and cryptocurrency mining. We have experts in architecture design, software engineering, smart contract deployment, and middleware tools development. We also have members who once served as core developers of public blockchains, crypto wallets, crypto mining pools, computing platforms, network security fields, and data protection areas. We have all been actively involved in the Filecoin ecosystem and another decentralized storage network for years. We’ve been powering Web3 storage at pretty awesome places and will continue doing so here in OMIC Labs.

## Team code repositories

https://github.com/SaoNetwork

# Additional Information

Our team is always engaging more skilled or creative people from all over the universe. No one can reach high ambition just by himself or herself. Nevertheless, by leveraging the team and various skills, we have the power and ability to create an outcome that’s bigger than the sum of its parts.

**Comment by ErinOCon** [comment]
Hi @vricale, thank you for your proposal! Below are a few questions that will help with our review: 
      1. Is the work for Milestone 1 already complete? If so, can this be removed from the submitted proposal?
      2. Can you also provide an architecture overview and development overview for milestones 2 and 3?  

Please let me know if you have any questions!

**Comment by vricale** [comment]
Greeting ErinOCon,
Appreciates the time you have spent evaluating our grant proposal, please find our responses below.

**1. Is the work for Milestone 1 already complete? If so, can this be removed from the submitted proposal?**
Milestone 1 is almost completed and the Joint mining app is online for months. However, we plan to upgrade it to enable the FVM to automatically distribute mining revenue to users, and tokenize the storage power to make it tradable. That’s our remaining work so that we’d prefer to keep this item here.

**2. Can you also provide an architecture overview and development overview for milestones 2 and 3?**
![img](https://github.com/vricale/Mark_Repo/blob/main/SAO%20Architecture.png?raw=true)

Here is the high-level overview of SAO Network shown in the diagram. As you can see, our Data Store app is a storage platform as a hot data layer for public users. Data Store generates car files, makes storage deals, and stores data onto Filecoin network.
For milestone 3, we are going to deliver a powerful search engine for public data. Everyone can search it for useful data like NFTs, historical documents, meteorological data, movies, etc. We plan to develop a recommendation system and content audit system to support the search engine, which can be truly available and provide the best experience to users.
To give incentives to the use of Data Store and Search Engine, we will also design an economic model between data producers, providers, and consumers. NFTs or Filecoin rewards will be given to all types of participants, to let users store data on our network sustainably. 

Please let us know if you have any additional questions, we are very happy to answer them.
Best Regards

**Comment by ErinOCon** [comment]
Hi @vricale, thank you for the additional information! We believe the work outlined under milestone 2 could be a good fit for our grant program! If receiving support for this specific piece of your project is of interest, please submit a new proposal that provides a development road map and budgeting details for the SAO Data Store work specifically. 

Depending on the results of the new proposal, we may be able to consider a separate grant for milestone 3 work in the future.
