### ISSUE TITLE
Next Step Microgrant: MerkleWrite

### ISSUE THREAD

**Issue by mbcse** [filecoin-project/devgrants#568]
### 1. What is your project? (max 100 words)
This is a Decentralized content sharing platform made on top of ipfs, Defi, and Ethereum. Nowadays content creation is centralized and is subject to changes or partiality by the site owners. To support the content creators and provide them with equal rights and profits, merkleWrite is made!

In merkleWrite you can write a blog with images and markdown content. The users will need to pay 1 DAI as a subscription fee for 30 days to see the content. The DAI token(ERC20) from user's are then sent to Compound for generating Interest(In the Form Of CTokens). The Dai Taken and Interest generated are then equally divided between content creators who has Likes more than specified limit(Currenlty set at 10). You can transfer Subscription to other ethereum address, get paid once in a month and update your profile's to let world know you! The Best part Is All is Decentralized. The platform is deployed on the Matic Mumbai test net and the wallet is Portis wallet

https://github.com/mbcse/eth-eternals

https://merklewrite.herokuapp.com/

### 2. How are you planning to improve this project? (max 200 words)
- Improve Smart Contracts
- Use IPFS through pinata
- Add hashing, encryption and hiding of ipfs links
- Improve the website design and add more features like visits, bookmarks, share
- Add automatic NFT issue feature for star content writers of the month and year
- Launch on mainnet
- Build a community and market the product
 
### 3. Is this project open source?
Yes, Under MIT License

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes, Will provide updates about the progress
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions
https://youtu.be/xJGgvZsDfNg
  
### Additional questions:
**Team**
Name: Mohit Bhat
Email: mbcse50@gmail.com
Github: mbcse
Role: Founder
**If your project was created as part of an event or hackathon**
Yes, It was part of ETHernals Hackathon https://devfolio.co/projects/merklewrite-5468

**Comment by ErinOCon** [comment]
Hi @mbcse, Thank you for your interest in our grant program! Once our review is complete, we will be in touch with an update or questions.

**Comment by ErinOCon** [comment]
Hi @ErinOCon, Thank you for your interest in our grant program! Once our review is complete, we will be in touch with an update or questions.

**Comment by ErinOCon** [comment]
Hi @mbcse, This microgrant has been approved! Look out for an email to submit payment details.
