### ISSUE TITLE
Next Step Microgrant: DeSci Berlin Conference Sponsorship

### ISSUE THREAD

**Issue by seldamat** [filecoin-project/devgrants#569]
### 1. What is your project? (max 100 words)
OpSci is building a decentralized data commons for science research utilizing Ocean Protocol and Estuary for dataset discoverability, persistence, tokenization, and incentivized cloud services for compute/storage. As part of this, we have been growing a flourishing community of scientists, web 3 developers, and activists. We've established a template for community events with DeSci@ethDenver and DeSci Day at Devconnect. We are now seeking funding to support travel grants for DeSci Berlin (May 23 - 24). We were referenced to complete this application for sponsorship by Sonia, our grant program officer at Filecoin Foundation.

https://github.com/opscientia
https://opsci.io
https://desci.community
https://desci.berlin
  
### 2. How are you planning to improve this project? (max 200 words)
We are working with the wider DeSci community (Molecule, vitaDAO, labDAO) to hand off the administration and operations for DeSci Berlin. We've also sourced feedback from previous events and are actively seeking to improve the representation and diversity of event speakers and attendees.
 
### 3. Is this project open source?
Yes! All of our release ready code is public on https://github.com/opscientia

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
We will provide an update on the turn out for DeSci Berlin, including which travel grants have been awarded.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes!

### 6. Links and submissions
https://showcase.ethglobal.com/web3weekend/open-science-opsci-data-wallet
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
- Shady El Damaty, shady@opsci.io, seldamat, Project Lead
- Nanak Khalsa, nanak@opsci.io, nanaknihal, Engineer
- Caleb Tuttle, caleb@opsci.io, calebtuttle, Engineer
- Kinshuk Kashyapp, kinshuk@opsci.io, kinshukk, Engineer

* If your project was created as part of an event or hackathon:
Web3Weekend

* Please link to your hackathon submission
https://showcase.ethglobal.com/web3weekend/open-science-opsci-data-wallet

**Comment by ErinOCon** [comment]
Hi @seldamat, This microgrant has been approved! Look out for an email to submit payment details.
