### ISSUE TITLE
Open Grant Proposal: Filecoin’s Place in Web3

### ISSUE THREAD

**Issue by Dweb-wjbrowning** [filecoin-project/devgrants#575]
Open Grant Proposal: Filecoin’s Place in Web3
Name of Project: D-Web Web3 Education project
Proposal Category: community
Proposer: Dweb-wjbrowning
Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?: Yes
Project Description

As Filecoin grows out in the coming years, its place in Web3 will become more solidified, and the knowledge of how it can work among other Web3 projects will be of the utmost importance to its development. However, many who are interested in the filecoin ecosystem are ignorant of Web3 integration and unaware of how the project can be utilized moving into the next stage of the internet. Even the ESPA project devotes minimal time to how the different Web3 projects can function together. 
This is where the Web3 education project can be utilized. Focusing on the complementary relationship filecoin can have with other Web3 projects,  the Web3 Education Project is designed to educate other crypto developers on integrating filecoin into their frameworks to create a more robust Web3. 
The project lays out a curriculum in the style of the ESPA bootcamps, meant to develop a foundation for understanding how it combines with other Web3 projects to create a robust interproject ecosystem, with a significant focus on why filecoin is an ideal platform to integrate other projects into. 

Value
At present, in the cryptosphere, there is a tendency for tribalism, with projects being touted as competing with each other, even when the projects have very little to no competition. This mindset, rather than fostering innovation through competition, has led to many projects that are too isolated from each other. This is not functional. When Web3 replaces Web2, it will not be through one project but rather through the development of many projects that have been built on each other. Filecoin stands as one of the most valuable products for this storage. If this project is successful, other developers focused on Blockchain developments will be educated on the value of this interconnectivity and will be incentivized to develop with the filecoin project.
If this project fails, there will be the danger of misleading other crypto developers or turning developers off of the filecoin project. The failure of this project will occur if there is too little clarity in what is being taught or if the information is not streamlined in a way that allows others to view it effectively.
The biggest risk of this project is the ever-changing landscape that filecoin lives in. The constant development of new crypto projects and the folding of others means that presented information can become obsolete fast, even during production. The best way to mitigate this is to focus on blockchain projects that have already become well established so that the information can remain relevant for as long as possible. 
 
Deliverables
The Web3 Education project will create a series of five web videos, creating a Bootcamp for crypto developers to become familiarized with the Filecoin ecosystem and how it can be used moving forward. Each video will range from 10-30 minutes long and will include a linked slideshow that will be available to view. The style will be in keeping with the style used in the other ESPA Bootcamp series, as can be seen [here](https://m.fil.org/espa-bootcamp/contents). 
The curriculum will be carefully curated based on recent findings on retention and engagement. Systematic spaced repetition will be employed in the videos to carefully emphasize essential points without becoming redundant. Each video will build upon the previous one to create a comprehensive overview and inspire ideas for partnership and development in the space. 
 
Series: 
Filecoin vs Web2 Storage
Expansion Through Filecoin
Tools that allow for the better cross-compatibility with Filecoin
A roadmap for what a theoretical Web3 could look like
Projects Already Partnering with Filecoin and how they are integrated
Development Roadmap

Milestone 1
Research and Curriculum Layout

This milestone is the most important, as all the future milestones will depend on the information laid out in this research. A partnership between our research and our content teams to create factual and engaging concepts and create the layout of how all the information will be focused. 

This milestone is completed, we will have:

A comprehensive outline of all five videos
A layout of all information to be presented, including where points will be emphasized and where ‘spaced-repetition’ learning will be implemented
A complete list of partnerships and projects working with the Filecoin
A layout of a theoretical Web3

People Involved:
Willis Browning
Michael Maurakis
Kamin Hecox
James Halloway
Expected Hours:
80 hours
Expected Budget:
500 Fil

Milestone 2
Scripting and Slideshow Creation

The creative team will take the outline created in the previous milestone and form and organize it into valuable parts in this milestone. The scripting and creation of the slideshows will coincide, as there will be a lot of overlap.

By the end of this milestone, we will have: 
Completed slides that will form the main visuals of the video as well as be linked in the video proper
Completed scripts to be filmed.

People Involved:
Kamin Hecox
James Halloway
Jo Edwards
Expected Hours:
40 hours
Expected Budget:
250 FIL

Milestone 3
Acquisition and rehearsal of speakers

In this milestone, we will audition speakers for each script to be certain that the information is being presented in the most appropriate form.

By the end of this milestone, all pre-production on the series will be done. Our main speakers will be acquired, and the script will be memorized by each speaker. 

People Involved:
Kamin Hecox
Jo Edwards
Ken Briggs
Expected Hours:
40 hours
Expected Budget:
250 Fil

Milestone 4
Filming of the Speakers

In this milestone, the speakers will be placed against a professional neutral background and filmed giving their presentation. The lighting, audio, and visuals will all be professional grade.

By the end of this milestone, we will have
Completed production on the videos
Raw footage of all the speakers

People Involved:
Kamin Hecox
Expected Hours:
40 hours
Expected Budget:
250 Fil
Milestone 5

Editing of videos

In this final milestone, the videos will be edited together to integrate the slideshow slides with the information presented seamlessly and remove any excess footage or wasted moments to create a streamlined and straightforward-to-read video presentation. 

Once this milestone is done, the videos will be in a publishable state and ready to be uploaded. 

People Involved:
Kamin Hecox
Expected Hours:
80 hours
Expected Budget:
500 Fil

Total Budget Requested: 1750 Fil

Maintenance and Upgrade Plans
The constant changing of the Web3 landscape means that the videos will sometimes present outdated information. The videos will likely have to be updated yearly to show the growth of Filecoin and better reflect the changing landscape. We will create these updated videos annually, allowing for a continuous timeline of the evolution of Filecoin and allowing them to continue to function as effective onboarding. 
Team:

Team Members:
Robert Talts
Willis Browning
Michael Maurakis
Kamin Hecox
James Halladay
Jo Edwards
Ken Briggs

Team Member LinkedIn Profiles
https://www.linkedin.com/in/robert-talts/
https://www.linkedin.com/in/ken-briggs-iii-63210668/ 
[/](https://www.linkedin.com/in/robert-talts/)https://www.linkedin.com/in/willis-browning/ 
https://www.linkedin.com/in/jojoedwards/ 

Team Website
https://www.dweb.net/ 

Relevant Experience
D-Web has curated videos for multiple Decentralized projects, such as Helium, Sentinel, and Exidio. 

https://www.dweb.net/blogs/the-decentralized-web/nft-jpeg-an-introduction-to-non-fungible-tokens-that-goes-beyond-digital-art

https://www.dweb.net/blogs/the-decentralized-web/how-does-the-d-web-work

https://www.dweb.net/blogs/the-decentralized-web/d-web-invests-in-decentralized-cloud-network-filecoin

[Exidio: the Decentralized VPN App](https://www.youtube.com/watch?v=lfF4Vu2LhA4)

[VPNs: What Are They and Why Should They Be Decentralized?](https://www.youtube.com/watch?v=R9dMTrFr-lY&t=50s)

[Join the Decentralized Revolution](https://www.youtube.com/watch?v=v1Em_3hGSvw)
Team code repositories
 
 
Additional Information: 
We also serve as a marketing platform to promote the concept of decentralized network technology and build a robust customer base. We would direct our marketing efforts to highlight the content produced for the ESPA and generate further interest in Filecoin by providing high-quality educational content. 
For our marketing platform, our target audience is the general public, as we believe convincing the public of the need for decentralized systems versus centralized network systems is the largest barrier to growth in our industry and the best way to build a long-term consumer base.
Decentralized network systems, driven by innovations such as blockchain, are a fast-growing tech industry segment with an enormous variety of potential use cases. These uses include smart devices, autonomous vehicle guidance, geolocation, financial technology, decentralized applications (D-apps), etc. We hope to be an incubator and implementor of economically viable applications of decentralized web technologies.
We are putting a solid emphasis on public-facing marketing. We believe educating the public on the need and benefits of decentralized networks versus centralized networks is the most significant barrier to the widespread adoption of decentralized technology. Through curating events, resources, and research around decentralized tech and developing a solid brand, we can generate additional revenue streams through sponsorships, licensed use of our brand, and revenue from social media and website content. Additionally, positioning ourselves as a leader and innovator in this field will create organic lead generation and create a long-term consumer base.
This will allow us to embrace all aspects of the fledgling decentralized network industry, including network infrastructure, networking devices, smart devices, decentralized app development, and distributed computing systems. In our research, we could find no other company that combines network infrastructure, computing systems, and network devices. This gives us a comprehensive view of the industry and facilitates our role as a marketing front for this tech industry segment.
The core of our marketing strategy is to position Decentralized Web Technologies as a thought leader in our industry, with the building of a decentralized internet as our mission. This will be done using a combination of a public-facing social media campaign and cultivating contacts with various businesses across the industry. We believe this is the best way to maximize our long-term customer base and generate leads for new product lines. This marketing campaign is already in progress on our website and social media platforms, including Facebook, Instagram, Youtube, Twitter, and LinkedIn.

As part of its marketing, Decentralized Web Technologies will do the following:
Maintain and grow an extensive social media presence to engage the public and generate potential leads, including sponsored posts. Any data storage leads would be fed back into the ESPA ecosystem. 
Establish a company website containing engaging multimedia content about our business and movement and drive traffic with an emphasis on lead generation.
Paid advertisements using Google Ads.
As the business grows, place ads in industry newsletters.
Regular outside sales calls and visits to customers, attempting to generate Data providers for the Filecoin ecosystem.
We are leveraging our network in San Antonio, which includes major players in the local tech industry like TechBloc, Geekdom, the SA Economic Development Foundation, and the Hispanic Chamber of Commerce.
Our goal is to scale new technologies to enable the widespread adoption of decentralized networks. This is to build a future where a few large companies do not control network traffic. The best way to get there is by creating sustainable business models in the space and educating the public on the need for those businesses. The best way to do this, we believe, is by creating engaging and relatable content for high-traffic media channels. 
Our key strategies for audience reach and engagement are:
Creating engaging content for a non-technical audience, emphasizing video content and social media.
Frequent use of CTAs in all content to build a subscriber base for retargeting
Be an industry resource by hosting a resource library on the network.

Our Social Following:
Twitter: 17k followers
Instagram: 10k followers
Facebook: 6k followers
Linkedin: 8k followers

Utilization:
Daily posting on FB, Twitter, and LinkedIn
Daily use of IG stories
Weekly posting of video/social content across all platforms
Native advertising of content/page
All posts promoted on C-Suite personal social accounts
Direct Marketing Overview:
Our Resources:
Rapidly growing mailing list with 1K new subscribers per month
Comprehensive Shopify automated marketing suite backing website
Data-driven analytics to evaluate best marketing practices
Direct emails each time a new article or video is posted with CTA to share
Weekly newsletters highlighting content.
Viewer retargeting with suggested content
Comprehensive tracking/analytics to verify metrics are achieved.

**Comment by ErinOCon** [comment]
Hi @Dweb-wjbrowning, Thank you for your proposal! Would your team be looking for additional support outside of funding (i.e. input finalizing script, identifying helpful contacts, etc.)?

**Comment by ErinOCon** [comment]
Hi @Dweb-wjbrowning, your proposal has been approved! This [content](https://ecosystem-wg.notion.site/Getting-started-with-IPFS-Filecoin-c00526cf97ba4087ba5c3ad5f5337a58 ) may be a helpful resource. To proceed, please email grants@filecoin.org.
