### ISSUE TITLE
Next Step Microgrant: CRUZO - The first NFT greeting card & crypto gifts multi-chain Web3 platform.

### ISSUE THREAD

**Issue by modus77** [filecoin-project/devgrants#576]
### 1. What is your project? (max 100 words)
We a building the first NFT greeting card & crypto gifts multi-chain Web3 platform. Bringing a billion-dollar industry to Blockchain.

Our mission is to advance the mass adaptation of NFTs through a revolutionary greeting cards and gifts marketplace

Less competition, more profit. Cruzo combines the benefits of owning a niche platform in the NFT space for creators while serving a billion-dollar market requiring millions of on-chain transactions.

New hype on greetings. Cruzo’s greeting stories combined traditional greeting cards with viral video format to create a new market with the potential for secondary sales and crypto gift giving.

Creators DAO. We are developing a community-driven Web3 DAO platform based on ESG principles. Creators will shape the future of Cruzo and even choose Charitable Programs to support.

Ecology. Cruzo will move billions of greeting cards and envelopes to the digital world, reducing the deforestation required to support the paper giants currently running the greeting card industry.

Our DApp will provide an opportunity to send/share NFT greetings anywhere: Instagram stories, Tik-Tok, Facebook, WhatsApp, Telegram, etc. As well as time-saving on search and selection of proper greetings. People will love it! 

Including, but not limited to:

Secondary Market / Collectable
Greeting stories (new hype format)
smart event manager
Generative NFT invites
Sharprice (Fair NFT price)
Crypto gifts
XURY token
XURY Wallet

We use ipfs for ping images and meta data.

Link to public Github repo --> https://github.com/cruzocards
Link to demo --> https://front.alpha.cruzo.cards/
  
### 2. How are you planning to improve this project? (max 200 words)
Beta release. Greetings a billion-dollar market requiring millions of on-chain transactions. We need a sustainable blockchain partner to run our platform
 
### 3. Is this project open source?
Not yet. We open smart-contracts for now. Maybe later we will open all.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
We would like to discuss it after you will select our project for grant.
  
### 5. Does your proposal comply with our Community Code of Conduct?
Yes

### 6. Links and submissions
No
  
### Additional questions:
Person A: Denis Stepanov, Founder. Here is a link to his Linkedin [https://www.linkedin.com/in/](https://www.linkedin.com/in/denis-stepanov-9656b720/)dentai He has significant experience in Digital Marketing and Web Promotion. Worked in International companies in roles Sales & Marketing Director, Head of Mobile, E-commerce Director.

Person B: Roman Bobrik, Co-founder (CTO). Here is a link to his Facebook: https://www.facebook.com/profile.php?id=100010742799563. Worked for many different companies and projects within the last decade as a senior web/mobile/fullstack developer and team leader. Here’re the links to few latest projects: Official DAB Pumps mobile app and server side: iOS: https://apps.apple.com/us/app/dab-pumps-app/id1465714463 Android: https://play.google.com/store/apps/details?id=com.dabpumps VIP lounges web SPA and server side: https://vipgroup.ru Electric carsharing and charging mobile apps: iOS: https://apps.apple.com/us/app/aicar/id1446068511 Android: https://play.google.com/store/apps/details?id=ge.aicar.app&hl=en_US&gl=US

Person C: Jane Makey, Head of Design (UX/UI Designer). Here is a link to ther Linkedin https://www.linkedin.com/in/jane-makey-a9ab05bb/  She has significant experience in UX/UI, gained in software houses, startups, and also as a freelancer. Her goal is to solve problems with engaging and intuitive designs, by always having users and business in mind. Link to a few latest projects:http://be.net/janeappleby 

Person D: Nikita Korshunov, Full-stack developer. Here is a link to his Instagram https://github.com/kewka He has extensive experience in software development. Strong skills in Go, Node.js, React, Solidity. Here’re the links to few latest projects: https://alium.finance/ - development [web3, react, styled-components, thegraph, node.js], https://redpanda.game/ - frontend development [web3, react, emotion], https://dashboard.fragma.net/ - backend development [nest.js, postgres, gcp storage], https://app.orica.io/ clone - backend development [nest.js, postgres, redis, ipfs, ethers.js]

**Comment by ErinOCon** [comment]
Hi @modus77, thank you for your proposal! Is it possible for the portion of work covered by this grant to be fully open source? This is generally a key point in our criteria for microgrants.

**Comment by modus77** [comment]
> Hi @modus77, thank you for your proposal! Is it possible for the portion of work covered by this grant to be fully open source? This is generally a key point in our criteria for microgrants.

Yes, we already opened our smart-contracts.

**Comment by ErinOCon** [comment]
Hi @modus77, thank you for confirming the work funded by this grant would be fully open source. Can you confirm how the $5,000 grant amount would be used and how it will help you accomplish your project objectives?

In regards to the reporting, we intend to require all microgrant recipients to submit a final report at the end of a three month period. Please let us know if this will be a good fit for your team!

**Comment by modus77** [comment]
@ErinOCon did you saw comment from @bobrom ? Please give us a feedback. Thank you

**Comment by modus77** [comment]
Hi, @ErinOCon we are waiting for approval.

**Comment by ErinOCon** [comment]
Hi @modus77, thank you for the additional information! Would your team be willing to submit a final report at the end of the three month period?

**Comment by modus77** [comment]
> Hi @modus77, thank you for the additional information! Would your team be willing to submit a final report at the end of the three month period?

Yes, of course.

**Comment by modus77** [comment]
@ErinOCon We have a question. After approval can we post a twitt about received grant and partnership with Filecoin?

**Comment by modus77** [comment]
@ErinOCon kind reminder

**Comment by modus77** [comment]
@ErinOCon @iand @dokterbob 

Hey, Guys! We are bit confused. What's next?

**Comment by ErinOCon** [comment]
Hi @modus77, thank you for your patience. The outlined work has been approved! Can you confirm the best email address to discuss payment details? We can also use this email to discuss the communication options for this grant.

**Comment by modus77** [comment]
@ErinOCon Finally! Great news! Please use this email contact@cruzo.io

**Comment by bobrom** [comment]
Hi @ErinOCon, hope you're doing well!

Good news are coming from our side. We've recently finished major part of the work that has been committed in regards to the approved grant. Here's a brief report of our latest status:

- [x] **Allow users to buy arbitrary amount of the trade supply.**
✅ Done. Users can now buy any amount of a single trade.

- [x] **Review our latest changes related to making the contracts upgradable to allow future updates.**
✅ The changes have been reviewed. As a result, we decided to migrate our previous implementation to UUPS proxy, which is also completed as of now. 

- [x] **Add possibility to gift NFT: buy and transfer to another account.**
✅ This feature has been implemented.

- [x] **Limit trades amount for a User <> NFT pair.**
✅ Done.

- [x] **Implement service fee logic and integrate it into buying process.**
✅ Service fee logic is implemented and integrated.

 - [x] **Implement contracts factory in order to allow users to create their own collections.**
✅ Complete. With this change we enable our users to create custom collections based on Cruzo ERC-1155 token. 

As our project is progressing, we've also planned some more activities for the upcoming weeks:
 - [ ] Allow gifting NFT to a user who has no wallet with a secured token. 
 - [ ] Allow gifting NFT from a previously created own trade.
 - [ ] Add possibility for creators to mint and gift NFT within a single transaction.

Feel free to get in touch with me or @modus77 in case you have any questions about the development of Cruzo project.

**Comment by bobrom** [comment]
Hi @ErinOCon , how are you?

I'm happy to let you know that we've recently finished the last task from the backlog which has been previously committed for the microgrant.

 - [x] **Allow gifting NFT to a user who has no wallet with a secured token.**
✅ Done on the smart contracts side. We'll release this feature in our next Cruzo dApp release.  

Feel free to get familiar with the latest code changes and let me know in case you have any comments or questions about Cruzo project development.  

Of course we continue working on the project and preparations for Mainnet release. Next major task for us is to implement **creators royalties** feature. Could we discuss an opportunity to get further support for Cruzo project?

**Comment by modus77** [comment]
@ErinOCon @juliangruber @iand Dear filecoin team. Thanks a lot for your support and micro-grant on development. As @bobrom mentioned above - the job is done. Please welcome to do the necessary code review. Also, please, tell us if we can apply for another grant to continue our development. Thank you!

**Comment by ErinOCon** [comment]
HI @modus77, thank you for the update and congrats on your accomplished work! Would you have capacity to complete the final grant report [here](https://airtable.com/shrrtSlgdVvrPmAvr)? And, of course, please feel welcome to apply for a grant to support your future development work. We would be happy to review this request!
