### ISSUE TITLE
Next Step Microgrant: Decentralised Bounty Hunting platform for Hunters controlled by Hunters

### ISSUE THREAD

**Issue by Jds-23** [filecoin-project/devgrants#577]
### 1. What is your project? (max 100 words)

A tool for the community of developers, designers, and more. Members hold a unique NFT as their profile which gives them voting right in the DAO. Members gain rewards for completing bounties, they also receive special NFT representing their win which the winner can showcase as proof of experience. These NFTs represent the weight of the vote of the holder in DAO. Members can vote to add/remove organisations/individuals, only these added organisations/individuals have the right to post a bounty on our platform. All NFT and bounty data are stored in IPFS using web3.storage to make data decentralised.

[GitHub Repo](https://github.com/Bounty-Hunt-2022/bounty-hunt)
[Live Website](https://comfy-brioche-855118.netlify.app/)
  
### 2. How are you planning to improve this project? (max 200 words)

Currently only the development of platform in testnet is done. Our first milestone would be complete developing the DAO part. Then we will be set for mainnet alpha launch. This is being aimed at 1st June.

When we launch our alpha on 1st June, we will give [buildspace](https://buildspace.so/) NFT holders free access to our DAO to onboard the huge community buildspace. We would partnering with organisations to sponsor bounties for our members.

In our alpha stage(1st June to 2nd July), $1400 would be used. 

$400 for a community manager intern in discord.
$1000 for social media marketing.

We would be preparing for beta stage, aiming to be released on 2nd July with more contract security, improved UI and more organisations.
$1500 for UI/UX design to be prepared by freelance designers.

From 2nd July to 2nd August, $2100 would be used.
$700 for senior community manager in discord.
$400 for a community manager intern in discord.
$1000 for social media marketing.
 
 
### 3. Is this project open source?

Yes

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?

  Yes

### 5. Does your proposal comply with our Community Code of Conduct?

Yes
### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
https://devfolio.co/projects/bounty-hunt-b073
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project. 
   Joydeep Singha, joydeepsingha68@gmail.com, [Jds-23](https://github.com/Jds-23), Developer & Manager
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) [ETHernals](https://ethernals.devfolio.co/)
  * Please link to your hackathon submission [Submission](https://devfolio.co/projects/bounty-hunt-b073)

**Comment by ErinOCon** [comment]
Hi @Jds-23, Thank you for your interest in our grant program! Once our review is complete, we will be in touch with an update or questions.

**Comment by ErinOCon** [comment]
Hi @Jds-23, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by ErinOCon** [comment]
Hi @Jds-23, thanks for checking in! We have sent you an email with instructions for next steps.

**Comment by ErinOCon** [comment]
Hi @Jds-23, I hope you are doing well! Can you submit a final grant report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

**Comment by Jds-23** [comment]
Getting the report ready

**Comment by ErinOCon** [comment]
Hi @Jds-23, do you expect the report will be available this this week?
