### ISSUE TITLE
Next Step Microgrant: DokuMint

### ISSUE THREAD

**Issue by shashanka2a** [filecoin-project/devgrants#578]
### 1. What is your project? (max 100 words)
Showcase your certificates as NFTs.

Github repo
https://github.com/dokumintapp/ETHernals

Demo
https://youtu.be/IUpsRdQk3Pw

Website
Yet to launch

### 2. How are you planning to improve this project? (max 200 words)
As the project is developed as a part of hackathon, we didn't get enough time to implement our idea completely and efficiently. We are planning several improvements starting with UI updates and also focusing on improving the functionalities, like NFT smart contract deployment, which is currently dependent on NFTPort API. We are looking forward to add more resources for taking this project to next level. We are also planning to provide an API support to the teaching websites like Udemy to mint their students' certificates in an automated way, i.e as soon as the student completes the course, he'll be issued with the NFT certificate.

### 3. Is this project open source?
Yes, all of the work is Open Source under MIT license.

### 4. If selected, do you agree to share weekly updates and a grant report upon conclusion?
Yes, we will share weekly updates in Github Discussion thread.

### 5. Does your proposal comply with our Community Code of Conduct?
Yes.

### 6. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* ETHernals Devfolio(Protocol Labs Winner) - https://devfolio.co/projects/dokumint-cbc5
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  Shashank Jagannatham
  Email - [17211a05a5@bvrit.ac.in](mailto:17211a05a5@bvrit.ac.in)
  Github - shashanka2a
  Role - Full Stack Developer

  Pradeep Varma
  Email - [pradeepnadimpalli22@gmail.com](mailto:pradeepnadimpalli22@gmail.com)
  Github - pradeepvarma22
  Role - Smart Contract Developer 

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
     ETHernals Devfolio
  * Please link to your hackathon submission
     https://devfolio.co/projects/dokumint-cbc5

**Comment by ErinOCon** [comment]
Hi @shashanka2a, Thank you for your interest in our grant program! Once our review is complete, we will be in touch with an update or questions.

**Comment by ErinOCon** [comment]
Hi @zediogoviana, Thank you for your interest in our grant program! Once our review is complete, we will be in touch with an update or questions.

**Comment by ErinOCon** [comment]
Hi @Pedro1703, Thank you for your interest in our grant program! Once our review is complete, we will be in touch with an update or questions.

**Comment by ErinOCon** [comment]
Hi @Mercadojale, Thank you for your interest in our grant program! Once our review is complete, we will be in touch with an update or questions.

**Comment by ErinOCon** [comment]
Hi @husamia, Thank you for your interest in our grant program! Once our review is complete, we will be in touch with an update or questions.

**Comment by ErinOCon** [comment]
Hi @nftsgate, Thank you for your interest in our grant program! Once our review is complete, we will be in touch with an update or questions.

**Comment by ErinOCon** [comment]
Hi @ErinOCon, Thank you for your interest in our grant program! Once our review is complete, we will be in touch with an update or questions.

**Comment by ErinOCon** [comment]
Hi @shashanka2a, This microgrant has been approved! Look out for an email to submit payment details.
