### ISSUE TITLE
Volaverse: An Educational Metaverse

### ISSUE THREAD

**Issue by ujjwalvolaverse** [filecoin-project/devgrants#580]
# Open Grant Proposal: `Volaverse: An Educational Metaverse`

**Name of Project:** *Volaverse*

**Proposal Category:** `metaverse` 

**Proposer:**  `ujjwalvolaverse`

**(Optional) Technical Sponsor:** `N/A`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** "Yes" 

# Project Description

Introduction: Since the last 1 year concepts of Web 3.0 and Metaverse have gained a lot of popularity and awareness amongst the developer, investor and entrepreneurial communities. Digital NFT sales alone has skyrocketed to more than 200 times in the year and is growing exponentially further. But the in-depth knowledge about concepts like DAOs, Metaverse, Blockchain technology, virtual reality is still limited and the resources for them are scattered.

Volaverse aims at resolving this problem by providing structured, organized and consolidated Web 3.0 learning material on a community driven **Metaverse** platform. It will provide virtual land asset ownerships to content creators where they’ll be able to run courses with 3D immersive content.

## Value

**1. Enhancing Web3.0 Ecosystem:**
a. Web3.0 are taught and learnt, hence contributing to flourishment of its ecosystem
b. Decentralizing the process by empowering the community to make decisions

**2. Creators' Economy:**
a. Monetizing content to incentivise instructors to teach courses related to Web3.0
b. Providing communities for the creators

**3. 3D Immersive Play & Gamification:**
a. Virtual reality provides a more comprehensive networking experience to users.
b. Gamified curriculum leads to better user engagement

## Deliverables

We will be integrating the Filecoin as the storage layer of the project. We will be delivering the following in the project:

**1. Volocator**
a. A central space where a user starts its journey from and can come back to whenever he/she wants to.
b. A place with a directory to all the courses currently running in Volaverse with an option to directly teleport to the course.
c. Features a notice board where notices to all the events, properties for rental/sale, new courses coming up etc are put up.
d. Features a news bulletin showcasing news related to Web 3.0 world.
e. A place to socialize with other users.
 
**2. Course rooms**
a. Built on a bought/rented virtual property.
b. Easily customized depending on the content that the creator wants to showcase.
c. Recording options available, if needed, from the angles as needed by the creator.
 
**3. Vola Store**
a. Marketplace where the user can trade land, NFTs, avatar accessories etc
 
**4. Vola Build**
a. In-house easy to use builder tool for landowners to build on their land.
b. Features different objects for beautification and utility in the classroom.
 
**5. Land/Plots**
a. These are non fungible parcels in which the Volaverse is divided into.
b. Content creators and developers will claim (buy/rent) Land so that they can build
on it and reach their target audience.
c. Land parcels are distinguishable from each other, trading at different prices due to differences in adjacencies and traffic around an area.

## Development Roadmap

Phase 1 (3 months) (Launching Metaverse -> Community Building -> Initial Courses)
1. Developing the MVP of Volaverse
2. Promoting social media handles to build the Volaverse Community
3. Building initial courses for the community

Total amount requested: $12,500

Phase-2 (3 months) (Building Strong Creators’ economy)
1. Incentivizing the course and content creators to build more courses
2. Building a stronger community for the course consumption
3. Building a model to fund the course/content creators

Total amount requested: $12,500

## Total Budget Requested

We are requesting $25,000 support from Filecoin. We will be using the funding mostly for the development of the platform. We will also use the minority funds for community-building initiatives. 

## Maintenance and Upgrade Plans

We will maintain the platform and keep on updating it according to the community requirements for a minimum of five years.

# Team

## Team Members

Ujjwal Singla, CEO
Ujjwal is B.Tech graduate from IIT Delhi, India’s topmost Engineering college. Ujjwal has worked with FMCG giant P&G for two years before turning into the web3 space. ‘

Swati Goyal, COO
Swati has long-term experience of more than 8 years working with educational institutions like EduSquare, YSchool, etc. and her experience is quite vital in building the educational metaverse.

Tarush Goyal, CTO     
Tarush is the brain behind the tech of Volaverse. He is B.Tech CSE from IIT Bombay top ranked Engineering college in India. 

## Team Member LinkedIn Profiles
 https://www.linkedin.com/in/ujjwal-singla-262107109
 https://www.linkedin.com/in/swati-goyal-219aa8234
 https://www.linkedin.com/in/tarush-goyal-704a9b18b

## Team Website

https://www.volaverse.com/

## Team code repositories

https://github.com/Volaverse

# Additional Information
Please refer to the Litepaper: https://drive.google.com/file/d/1RZuZDwMWVZuqQ1kh7IS9qf-pPiWW9IuW/view?usp=sharing
Please refer to the pitch deck: https://drive.google.com/file/d/111pXDxDer6TCJWV5Pfwkk_0E_UgX47p3/view?usp=sharing
Please refer to the introductory video: https://www.youtube.com/watch?v=jCMtCLABmKQ&feature=youtu.be

**Comment by realChainLife** [comment]
Hi @ujjwalvolaverse thank you for your proposal. We had several questions regarding some elements of the proposal: 

- Proposal has not demonstrated why educational material will be consumed better in a metaverse env vs a static platform. Can you provide additional information here? 
- Format of the course content is unclear - the course rooms describe events customized by content creators. What's the use case tie in for land and NFT options?

**Comment by ujjwalvolaverse** [comment]
Thank you for your questions @realChainLife . Please refer to the answers below:

The metaverse will help organize the content. Web3 content is quite segregated and in the metaverse, it will be appropriately managed and the experience will ensure increased engagement in the learning process. This will ultimately result in a low attrition rate for the new community members who are just venturing into the web3 world. 

We can host live lectures plus recorded tutorials for any topic in the Volaverse. Educators can provide any downloadable materials for the students. Volaverse will allow the cohort-based learning programs to be introduced. 

Projects can host their learning experiences on different land parcels and NFT will validate the learner's participation in different learning tracks. They can build their learning hub which will act as a single place for all the educational resources related to project for different types of users ranging from normal users to developers. NFTs can also act as an entry pass for gated courses providing another way of monetization to the content creator.

**Comment by tippi-fifestarr** [comment]
This is very interesting! As an educator of kids, I think they would like something like this for basic blockchain concepts and even basic computer science knowledge. 

@ujjwalvolaverse Sam Tang and I are working on a [Web3 Library project for Orbit Community Program](https://web3-library.notion.site/web3-library/Web3-Library-7c60578efe8c414e917d1779c640b8df), would you be open to meeting with us for knowledge sharing and possible collaborative synergy?  @realChainLife is it inappropriate for me to try to connect this way?

**Comment by ujjwalvolaverse** [comment]
Hi @tippi-fifestarr nice to connect you here. You can reach out to me on telegram @ujjwaledu .

**Comment by ujjwalvolaverse** [comment]
Hi @realChainLife I hope I have answered your questions. Please let me know if there's any further clarification required.

**Comment by ujjwalvolaverse** [comment]
Hi @realChainLife , please let me know if you have any further questions regarding the project.

**Comment by ErinOCon** [comment]
Hi @ujjwalvolaverse, thank you for your time with the additional information. We would like to fund the outlined work! Please email grants@filecoin.org to discuss next steps.

**Comment by ujjwalvolaverse** [comment]
Thank you @ErinOCon for the approval. I have mailed on the given id from associations@volaverse.com
