### ISSUE TITLE
Web3 Data Specifications

### ISSUE THREAD

**Issue by ZhangPeibin** [filecoin-project/devgrants#583]
# Open Grant Proposal: `Web3 Data Specifications`

**Name of Project:**`W3DS`

**Proposal Category:** `app-dev` `metaverse` 
**Proposer:** `peibin`

**(Optional) Technical Sponsor:** `N/A`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:**  `Yes`

# Project Description
The goal of the Web3 Data Specification (abbreviated to W3DS) is to create a basic schema for Web3's data registry. W3DS is the cornerstone of the web3 world for building decentralized and scalable data registries. This mode helps to establish a complete data portrait of data content, and at the same time, it can query specific types of data for the search market in IPFS/Filecoin, and at the same time provide the intellectual property rights of web3 data on the chain, and provide data benefits for creators.

## Value
[Filecoin ](https://filecoin.io/)is becoming the storage cornerstone of web3. With the continuous growth of data storage and the cooperation between more chains and Filecoin, Filecoin is bound to be the largest decentralized storage project in the future. Filecoin builds the underlying storage layer based on [IPFS](https://ipfs.io/), a peer-to-peer hypermedia protocol.

Based on the characteristics of IPFS, all data can only be accessed through cid, which makes it impossible to know the data portrait of cid before loading the data corresponding to cid, even if nft.storage has metadata.json (also cid),this is very unsuitable for users to query related data according to the characteristics of the classification, or the corresponding cid data cannot be searched according to the keywords on the search engine.
Therefore, we establish the data portrait on the chain by establishing the W3DS protocol and integrating some storage providers (such as nft.storage, web3.storage), and also support adding the existing cid to the data portrait.

The data uploaded to Filecoin through the W3DS protocol will have its own data portrait on the chain, and the data portrait can also be updated at any time. Our data portrait data can be added to search engines or existing retrieval markets. Users can search Filecoin data directly through keywords, or know the data overview before loading cid.

## Deliverables
The results we will deliver are:

-  A website based on the W3DS protocol
-  Complete W3DS protocol documentation
-  Choice of optional storage platform (nft.storage, web3.storage, etc.)
-  An Interface to query all data portrait 
-  An Interface for querying data profile features
-  An interface for adding data portraits to cid
-  An sdk that integrates the W3DS protocol
-  Open source contract code

## Development Roadmap
Milestones:

- M1 (Week 2 to 3) 3 developers
Detailed function finalization
Web UI interface design
W3DS protocol finalized
W3DS documentation
Budget requested: $10,000

- M2 (Week 3 to 5) 2 developers
Front-end page development
Contract development of w3ds protocol
Contract test
Budget requested: $15,000

- M3 (Week 3 to 5) 2 developers
Data storage related function development
Custom storage platform selection function development
Complete the storage website based on w3ds protocol
Budget requested: $15,000

- M4 (Week 3 to 5) 2 developers
Query interface development
Feature interface development for querying all data
Develop interface for adding data portraits to cid
Develop an sdk that integrates the W3DS protocol
Project final test
Budget requested: $25,000

## Total Budget Requested
$65,000

## Maintenance and Upgrade Plans
We will arrange personnel to maintain and update the w3ds protocol, and continuously optimize the project stability and interface stability and expansion to adapt to changes in web3 data.
We will coordinate more free and reliable storage parties to provide users with reliable storage, and cooperate with search platforms and other products to promote and attract other partners.

We will continue to build to be the choice of most data platforms.

# Team

## Team Members

- peibin
With many years of full-stack development experience and years of project management experience, he is good at finding user pain points and proposing reliable approaches. 

- jiandan
Has 10 years of experience in large-scale project development, has led multiple teams to complete projects, has back-end and Solidity development experience, and has been developing in the blockchain field for many years

- AMing
With many years of product design experience, rich experience in product design and UI composition, all product design is designed to increase user experience

# Additional Information
We unanimously believe that the next Internet era must be Web3, and we have always believed that Filecoin will change the data storage method of web3. Ultimately, Filecoin will carry the data of the entire next-generation Internet. This is the emergence of a new era, and we hope that in this new era Make some of our own contributions.

Our team has experience in blockchain development, and we are also looking for pain points from users to enrich the ecological application of Filecoin

**Comment by ZhangPeibin** [comment]
Update our initial design version, we will continue to think and improve in the future:  [W3DS WebSite](https://w3ds.vercel.app/)

**Comment by ZhangPeibin** [comment]
@realChainLife About this project, the just-concluded Wanxiang Blockchain Hackathon was praised by PL and won the third place.
Please contact me if you have any questions or updates, thanks!

**Comment by ErinOCon** [comment]
Hi @ZhangPeibin, thank you for your proposal and for your patience as we continue our review! Can you provide the following information?
1. An architecture overview of your project
2. Additional roadmap details regarding milestone deliverables and how they will be achieved. 
3. A brief description of how users will be interacting with the indexes. For example, will it have associated costs / per search?

**Comment by ZhangPeibin** [comment]
> Hi @ZhangPeibin, thank you for your proposal and for your patience as we continue our review! Can you provide the following information?
> 
> 1. An architecture overview of your project
> 2. Additional roadmap details regarding milestone deliverables and how they will be achieved.
> 3. A brief description of how users will be interacting with the indexes. For example, will it have associated costs / per search?

Hi @ErinOCon ,I'm glad to receive your reply, here are some answers:
**1: [Architecture link ](https://pitch.com/public/9d77ca64-e386-4c74-b373-014c1e1bf058)**
**2: Deliverables :**

**1). M1 Deliverables:**
- An official website describing the W3DS protocol (users can view the relevant protocol definition details and the iterative process of the protocol on this)
- All data schemas of the W3DS protocol
- Complete the W3DS specification document on Github

**2). M2 Deliverables:**

- An application website based on the W3DS protocol (index page)
- Solidity contract code that implements Polygon-based W3DS protocol
- All code will open in github

**3). M3 Deliverables:**
- Users can build their own data systems on the platform
- Users can upload data to IPFS/NFT through nft.storage, web3.storage (determined in user configuration) on the application platform and register data portrait (W3DS) ,all data can register onchain and offchain
- Implementation of core  data pool (code based on GO implementation, which maintains data pool and W3DS-based data pool)

**4). M4 Deliverables:**
- An interface for querying all data profiles
- An interface for querying all data profiles by metadatas
- An Cid interface for adding data portraits
- Go sdk / node.js sdk  （add data portraits / edit data portraits / query data portraits and more）
- OnChain API 


Users can mainly search in the following ways:
1: Search through our application platform, which supports fuzzy queries of various keys, which is free, of course, we will pass some restrictions to avoid server attacks (DDOS)
2: Our registered data portraits will be optimized for seo through cooperation, so that users can link to our platform through keywords on search engines such as google and display the corresponding data stored in IPFS/Filecoin
3: Query through API, we will support sdk of GO sdk/node.js/http and other platforms for data interaction
4: For web2 users, we will have web platforms, mobile platforms, etc. that can provide users to interact with data.
5: For web3 users, one is to directly interact with data through our sdk, and the other is to interact with data through the on-chain api (contract).
6: For developers or enterprise users, you can establish a targeted data space, you can add data, access data, etc. through api, etc.

All on-chain and off-chain data interactions are free of cost. Of course, this is free for users, but for our platform, such as in seo, etc., there is a certain cost in the server. But because most of the data stored through our platform is real data, we consider cooperating with Filecoin miners later (DataCap)

Hope to receive your reply as soon as possible, If you have any questions and want to know, please let me know, I will answer you in detail

**Comment by ErinOCon** [comment]
Hi @ZhangPeibin, thank you for your reply! We will be in touch with an update once our review is complete.

**Comment by ZhangPeibin** [comment]
> Hi @ZhangPeibin, thank you for your reply! We will be in touch with an update once our review is complete.

Hi @ErinOCon  .Grateful! Let me know if you have any ideas or technical suggestions for this, I'd be very happy to discuss it with you

**Comment by realChainLife** [comment]
Hi @ZhangPeibin thank for the updated project details. We're continuing evaluation of the proposal as a solution to the open search engine problem, and our team had additional questions: 

- On data representation: will you be working with IPLD Schemas, or something RDF?
- Can you clarify whether the data format will be a database spec or a data transfer protocol. There's reference to both in the outlined proposal. 
- What degree of interoperability are you aiming for? Specifically, when you describe this as tool that "web3 users can talk directly via our sdk" How many networks or frameworks will this support? 
- Will this be a paid service or an OSS for self-hosting?

**Comment by ZhangPeibin** [comment]
> Hi @ZhangPeibin thank for the updated project details. We're continuing evaluation of the proposal as a solution to the open search engine problem, and our team had additional questions:
> 
> * On data representation: will you be working with IPLD Schemas, or something RDF?
> * Can you clarify whether the data format will be a database spec or a data transfer protocol. There's reference to both in the outlined proposal.
> * What degree of interoperability are you aiming for? Specifically, when you describe this as tool that "web3 users can talk directly via our sdk" How many networks or frameworks will this support?
> * Will this be a paid service or an OSS for self-hosting?
> 
> cc: @RangerMauve

Hi @realChainLife , Thanks for your replies and questions . Here are some of my answers.
1: We will use IPLD Schemas but we will also use JSON-LD to optimize content SEO
2: We will not do data transfer protocols, more data storage protocols
3: Our interoperability will be categorized by user:
- For ordinary users, we have a web platform that can interact with data, and will also adapt to mobile platforms (android/ios). At the same time, when our seo is completed, users can also interact with our data on google based on attributes
- For web2 developers: we will provide python , golagn node.js sdk for data interaction
- For web3 developers: You can complete data interaction by integrating our sdk or using our http interface to combine your own contracts, etc. At the same time, you can also introduce our data interaction function contract to complete data interaction, we will do it in stages To complete the network support, phase 1: Polygon, Ethereum, nervos. Of course, FVM is also our most important integration but we will complete the support according to the development progress of FVM
- Of course, we give priority to free, but if the follow-up cost is too large, we may provide a funding function to obtain sponsorship funds. Or enterprises, developers using sdk/http will consider charging a little fee at different stages, of course, we will give priority to Get support funds to make this project completely free. In the end, this project is not for profit, but is established to complete the ecology.

In terms of technology, we are also constantly looking for suitable technical solutions. If IPFS/Filecoin can also provide some technical support, we will be very happy

**Comment by ZhangPeibin** [comment]
@realChainLife @ErinOCon @RangerMauve ,our demo built with this  has won Outstanding Potential prize on  Filecoin China hackathon .

**Comment by ZhangPeibin** [comment]
Hello @realChainLife , any update here?

**Comment by ErinOCon** [comment]
Hi @ZhangPeibin, thank you again for your proposal! Before moving forward with the consideration of this project, we would like to evaluate the progress and success of another one of your projects, [Cid.Graph](https://github.com/filecoin-project/devgrants/issues/821). 

Please feel welcome to re-apply once your work for the microgrant is complete!
