### ISSUE TITLE
Next Steps Microgrant: Futuria DAO.

### ISSUE THREAD

**Issue by Pedro1703** [filecoin-project/devgrants#586]
**1. What is your project? (max 100 words)**

Futuria is a DAO to accelerate and provide open-source tech infrastructure to independent media companies. Our tech arm, Utopia, is already developed and being used by la diaria, an uruguayan media company with 1.5 million unique monthly visitors. We aim to implement IPFS as storage to Utopia´s stack and make our first implementation of that with sitiosdememoria.uy 

We plan to apply to further grants to continue improving our tool and onboarding companies that already showed explicit interest in working with us, like: El Confidencial (from Nicaragua), La Silla Vacía (from Colombia) and Conexión Migrante (from México).

**Github Link (Utopia, our open source tech stack for media companies):**

https://github.com/ladiaria/

Link to websites (Futuria, our DAO, and la diaria, the media company that incubated it):

ladiaria.com.uy
futuria.media

**### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)**

This project will use IPFS to make sure all the content in sitiosdememoria.uy is censorship resitant, decentralized and always accessible. It will be our first step in making IPFS our default data solution to all of our media ecosystem. 
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

This grant will allow us to afford the implementation of IPFS at sitiosdememoria.uy and start upgrading Utopia´s tech stack to the latest Python version. 

**Clear and concise description of the planned next step(s) or improvements for which you are seeking grant support**

We will help media companies that are accelerated by Futuria to transition to decentralized data storage for all their contents through web3.storage and IPFS. With this grant, we aim to accomplish our first implementation with sitiosdememoria.uy, an archive made by volunteers that consists of the official documents from the uruguayan dictatorship (1973-1985), and start to update Utopia to the latest Python version. 
 
**### 4. Is this project open source?**

Yes. 

**### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?**

Yes. 
  
**### 6. Does your proposal comply with our Community Code of Conduct?**

Yes.

  
**### Additional questions:**

Evan Henshaw Plath, CTO/Tech advisor, anarchogeek@gmail.com; anarchogeek@gmail.com 
Pedro Copelmayer, project coordinator; pedrocopelmayer@gmail.com
Lisandro Acuña, full stack developer; lisandroeliasa@gmail.com 
Maria Catalina Colmenares, lead media investor; Mariacatalinacolmenares@gmail.com 
Damián Osta; la diaria´s founder and Head of Innovation; odamian@gmail.com

**How did you learn about our microgrant program?**

Through conversations we had with Jonathan Victor, BD at Protocol Labs.

**Comment by ErinOCon** [comment]
Hi @Pedro1703, This microgrant has been approved! Look out for an email to submit payment details.
