### ISSUE TITLE
Incentive-Compatible proof of storage scheme

### ISSUE THREAD

**Issue by imanvk** [filecoin-project/devgrants#587]
# Open Grant Proposal: `Incentive-Compatible proof of storage scheme`

**Name of Project:**
Incentive-Compatible proof of storage scheme

**Proposal Category:**  `technical-design`

**Proposer:** `imanvk`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Please respond with either "Yes" 

# Project Description

Current DSNs require continuous proof from the storage provider to ensure that the data is stored accurately. This process is costly and causes a waste of energy. The proof of storage in the current DSNs requires storage providers to proof the storage to the DSNs’
network nodes. This can cause a service denying attack such that a dishonest storage provider only provides proof to the network nodes while rejecting service to the client. In this case, the storage provider will get paid while the client cannot even has access to its own outsourced data!
We aim to solve this problems by developing a challenge-based proof of storage such that the storage provider only needs to submit a proof whenever the client submits a challenge to the network.

## Value

The new design can improve the performance of the Fliecoin by removing the requirement of continuous submission of proof of storage. Moreover, Filecoin will be protected from a potential denying service attack. In this attack a dishonest storage provider submits proof of storage to the network nodes while refusing service to the original data owner customer. 
We design an incentive-compatible mechanism such that the storage provider will be challenged from the network only once the client submits the challenge request to the network. The payoffs will be set such that the Nash-Equilibrium of the storage game will be our desired goal. The smart-contract will govern the rules of the game. 

## Deliverables

A new incentive-compatible protocol will be developed. Using game-theory, the interaction of the client and storage provider will be modeled and analyzed as a dynamic game. A prototype of the protocol will be implemented using Solidity and JavaScript.

## Development Roadmap

Milestone-1:
50K-Completing the framework design. (3 month and 3 personnel)

Milestone-2: 
50K-Completing the implementation. (3 month and 3 personnel)

Milestone-3:
20K-Completing the test and improvement. (3 month and 3 personnel)

## Total Budget Requested

Total: 120K
As stipend for the project personnel.

## Maintenance and Upgrade Plans

Upon acceptance of the proposal, we hoper that the completed project can be integrated into Filecoin repo.  

# Team

## Team Members

Iman Vakilinia, PhD. [Project Lead]
Weihong Wang 
Jiajun Xin 

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/iman-vakilinia-0a794770/

## Relevant Experience

Iman Vakilinia is a researcher. His research interests are Cybersecurity and Game-Theory. His research publications are available here : https://scholar.google.com/citations?user=GD7bikwAAAAJ&hl=en

Weihong Wang is a graduate student at Hong Kong University of Science and Technology. Her expertise is in the blockchain application development. Her GitHub repo is accessible here: https://github.com/podiumdesu

Jiajun Xin is a PhD student at Hong Kong University of Science and Technology. His research studies include Cryptography, Networking, and Blockchain. His publication records are available here: https://scholar.google.com/citations?hl=en&user=1OFq_hgAAAAJ&view_op=list_works&sortby=pubdate

**Comment by realChainLife** [comment]
@

**Comment by ErinOCon** [comment]
Hi @imanvk, thank you for your proposal! This scope of work currently isn't the right fit for our grant program, but please feel welcome re-apply as your project continues to progress. 

Wishing your team success with the outlined work!
