### ISSUE TITLE
Next Step Microgrant: Staging for accountability release payments. 

### ISSUE THREAD

**Issue by nftsgate** [filecoin-project/devgrants#590]
### 1. What is your project? (max 100 words)
This challenge consists in a Decentralized Autonomous Organization (DAO) to deal with funds. 
The participant will purchase shares by depositing Ether to the Organization (the group). 
These shares will enable the participants to create Proposals and Vote on presented proposals (the more shares the participant has, the more voting power). 
This interface, built with React.js, relies on the web3.js library & IPFS network to communicate with the DAO smart contract through Metamask. 
The Ethereum blockchain uses content-based addresses that IPFS returns.
This means that the data reflected on the front-end application is fetched from the Ethereum blockchain & IPFS network. 
The concept is to create a single decentralized place where projects triggered by DAO proposals can store their deliverables on completion. 
This would allow DAOs to assign independent assessors of project deliverables to validate the quality and provide assent for payment, 
enabling the DAO assigned project administrator to quickly, with transparency and accountability release community funds to the project team. 
Each action performed by participants (create a proposal, vote...) creates a transaction and modification on Ethereum. 
This transaction which will require Metamask confirmation and pay an small fee, will constantly modify the state of the DAO smart contract.

https://github.com/nftsgate/ideas-of-EIP-1559
https://cryptostake.dev/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
The project is build on IPFS core types, ipfs-http-client, ipfs-core-utils, ipfs-utils dependencies

  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Going forward, there is a lot to build and explore on the ideas, not just for accountability release payments but moreover room for implementing upgradable architecture. The grant would accelerate dedicated working hours on the project to expand and to provide build modules to dev participants for further explorations and opportunity for collaboration.

### 4. Is this project open source?
Yes.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes?
*No.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Johannes Schulte, info@cryptostake.dev , https://github.com/nftsgate , dev
* How did you learn about our microgrant program?
* Surfing on filecoin.io 
* If your project was created as part of an event or hackathon:
No.

**Comment by nftsgate** [comment]
https://cryptostake.dev Runs on Ropsten Testnet Network 
https://ropsten.etherscan.io/address/0xb90dd10ac797e649ebee5cc0f1b826d95f6e6d9b

**Comment by ErinOCon** [comment]
Hi @nftsgate, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by nftsgate** [comment]
@ErinOCon, :-) Thank you, I will be on the glued to look-out for your email to submit payment details.
