### ISSUE TITLE
Open Grant Proposal: SwaggerUI-like tool for IPFS

### ISSUE THREAD

**Issue by byte-me-stan** [filecoin-project/devgrants#591]
# Open Grant Proposal: SwaggerUI-like tool for IPFS

**Name of Project:** Axe4IPFS

**Proposal Category:**  devtools and integration-adoption

**Proposer:** https://github.com/byte-me-stan

**(Optional) Technical Sponsor:** Pancy jochasinga (https://github.com/jochasinga)

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?: YES

# Project Description

Currently, IPFS does not support Json format. This project is to develop a GUI tool to convert to JSON format for frontend application developers.

In a nutshell, frontend developers can create, update, retrieve and delete manually from web ui. It is similar to swagger API tool (eg; https://tinyurl.com/2vn8xwcs) for IPFS so that frontend developers can easily host the public available information on IPFS such as products' information, weather information, customer reviews, customer recommendations, bus/train/flight/ship schedules, restaurants menu, hotel rooms availability, even IoT data or news on IPFS in JSON format.  Please refer to the below examples.

Retrieve data from IPFS in the right format
https://stackoverflow.com/questions/70220064/retrieve-data-from-ipfs-in-the-right-format

https://stackoverflow.com/questions/tagged/ipfs

Developers are looking for solution to integrate data from IPFS to their applications. Therefore, this project will fill the gap between IPFS and development community.

## Value

IPFS technology can also position as a distributed storage not only for NFT but also for frontend applications to host public available information. This will open many integration possibilities for frontend application developers to utilize the benefits of IPFS easily and thereafter, it can create larger effects in web3 eco-systems.

## Deliverables

Basic operational functions. (Eg; login/logout/profile)
Web ui to allow developers to create collections with http methods.
Developers would be able to toggle between http methods.
Developers can execute each API based on the http method selected.
Display the response Body.
Developer can toggle between json format and original IPFS format in response body.
Provide code sample to convert from IPFS format to JSON format in various programming languages (JavaScript, React, Angular, Vue) to embedded inside their applications.

## Development Roadmap

1 - 4 weeks ($8,800)

* Developed web ui with basic functional features.
* Feature to allow developers to create their own collections with http methods.
* Feature to allow developers to select the http method.

5 - 10 weeks ($14,500)

* Feature to allow developers to execute each collection based on the http method selected.
* Display the response body.

11 - 14 weeks ($14,500)

* Feature to allow developers to toggle between Json format and IPFS format in response body.
* Provide the code sample to convert to Json format in various programming languages (JavaScript, react, Angular, Vue).

## Total Budget Requested

37,800 USD

## Maintenance and Upgrade Plans

Will continuously take comments from community and make improvements to the portal.

# Team

Stanley - https://www.linkedin.com/in/my07/ 

## Relevant Experience

Worked at F5 networks and FireEye.

**Comment by ErinOCon** [comment]
Hi @byte-me-stan, thank you for your proposal! We would like to fund the outlined work! Please email grants@filecoin.org to discuss next steps.
