### ISSUE TITLE
Next Step Microgrant: NFT Buidlr

### ISSUE THREAD

**Issue by pradeepvarma22** [filecoin-project/devgrants#594]
### 1. What is your project? (max 100 words)
A Dashboard for generating NFT collection from scratch with metadata and smart contract
Github repo
https://github.com/meta-ps/NFTBuidlr
Demo
https://youtu.be/c3jHMTd5eLc

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
  For generating NFTs we are uploading images to IPFS and using the response hash for creating the smart contract

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
* Hiring: We are planning to improve user interface by onboarding frontend developer to our team.
* Feature-1: We are planning to Integrate with Online Art Creation Platforms, for amateur artists or other NFT enthusiasts who want to list their collection.
* Feature-2: We are also looking to extend this platform for Communities/DAOs, to verify their members through NFTs, with trustless governance in place.
 
### 4. Is this project open source?
Yes, all of the work is Open Source under MIT license.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
https://github.com/meta-ps/NFTBuidlr

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Pradeep Varma
Email - [pradeepnadimpalli22@gmail.com](mailto:pradeepnadimpalli22@gmail.com)
Github - pradeepvarma22
Role - Smart Contract Developer
  
  Shashank
  Email - [17211a05a5@bvrit.ac.in](mailto:17211a05a5@bvrit.ac.in)
  Github - shashanka2a
  Role - Full Stack Developer

* How did you learn about our microgrant program?
Friend
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  MoleHack: NFT 2.0
  * Please link to your hackathon submission
https://youtu.be/IwMeX9pZTN4?t=5670
Time Stamp: 1:34:30 to 1:43:39

**Comment by ErinOCon** [comment]
Hi @pradeepvarma22, This microgrant has been approved! Look out for an email to submit payment details.
