### ISSUE TITLE
Next Step Microgrant: Marble News

### ISSUE THREAD

**Issue by joalavedra** [filecoin-project/devgrants#595]
### 1. What is your project? (max 100 words)
Marble is a Hacker News-like platform to help decentralized the content on the internet. It allows people to build their own communities, upvote relevant news and comment on other posts. Every time someone shares a link with the community, the page is indexed and uploaded into IPFS. network.

https://github.com/jamalavedra/ethglobal-amsterdam
https://marbel-dashboard.vercel.app/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
  
Links and articles are submitted using IPFS. 
Marble is built on top of Lens Protocol a decentralized social protocol.
Polygon network for deploying a smart contract

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We will help DAOs to transition to decentralized data storage for all their contents through web3.storage and IPFS. Our overall effort is focused around incentivising a closed alpha to refine our overall UX, start building out a community, and outreach to foster relationships with DAOs. 

That being said, there are 3 technical ideas:
- Build a decentralized Discourse (Posts, comments, upvotes, polls)
- Index submitted pages into IPFS

 
### 4. Is this project open source?

Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
N/A
  
### Additional questions:

Team
Name: Jaume Alavedra
Email: jamalavedra@gmail.com
Github: https://github.com/jamalavedra
Role: Full Stack

Name: Joan Alavedra
Email: joalavedra@gmail.com
Github: https://github.com/joalavedra
Role: Operations

They sent us an email with potential next steps to support our project.

The project was part of ETHGlobal Amsterdam: https://showcase.ethglobal.com/ethamsterdam/marbel-7su6d

**Comment by ErinOCon** [comment]
Hi @joalavedra, This microgrant has been approved! Look out for an email to submit payment details.
