### ISSUE TITLE
NFT Teleporter

### ISSUE THREAD

**Issue by xx014939** [filecoin-project/devgrants#596]
# Open Grant Proposal: NFT Teleporter 

**Project Name.** NFT Teleporter

**Proposal Category:**  Application development & Metaverse

**Proposer:** `xx014939`

**(Optional) Technical Sponsor:** This project is an extension of our original project "Your Meta World" which has kind of grown into it's own separate entity. I did have some discussion about a possible strategy to get my project/s to where I'd like to be after winning one of the top IPFS prizes at the Moralis hackathon with Longfei Wang, who encouraged me to apply for dev grants.

To be clear, I did not request Longfei to be a "Technical Sponsor". However I thought it may be relevant to mention our conversation here.

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:**  Yes

# Project Description & Value

The Web3 industry can be technically very complex and difficult for non technical business owners to get involved in. Due to the nature of decentralised wallets, assets and services, many processes involve multiple steps, a basic knowledge of cryptography, and in some cases even some coding experience. As more and more companies wish to on board their brands, products and services onto the blockchain, no/low code services which offer users an easy, cheap and intuitive way to do this will be sought after.

NFT Teleporter is a no/low code tool (API end points are available if needed), which offers users the ability to create NFT collections and mint NFT's in multiple dimensions and mediums. NFT Teleporter allows users with little to no technical expertise to quickly and easily create their very own NFT's and NFT collections, whilst simultaneously providing up front web based experiences which integrate with these NFT's seamlessly.

All data saved inside of the NFT's metadata (utilising IPFS storage), is retrievable at a later date by using our simple API endpoints, meaning that bespoke experiences can be built upon our generic ones with data already stored on secure servers.

View our short hackathon demo here --> https://www.youtube.com/watch?v=fX1V8UOcY1g&feature=emb_title
Current prototype URL here --> https://nft-teleporter.netlify.app/

As this is a Hedera prototype you will need a Hedera test net wallet to use this.

NFT Teleporter allows for easy tokenisation of digital assets by businesses and individuals alike on the blockchain, with almost zero technical skills required! Our application also promotes reuse of existing digital assets and interaction to create new experiences, with pre-existing smart contracts that have already been deployed. This not only saves businesses time and money, but also saves the planet as well.

## Deliverables

The application will have the following deliverables

- Simple and intuitive UI for non technical users (designed by a professional designer)
- Ability for users to create NFT's and NFT collections through this UI
- Ability for users to upload multiple digital assets to an NFT's metadata
- No/Low code smart contract modification if a new contract is being deployed (select different features for a smart contract prior to deployment)
- Option to randomise NFT Metadata. Upload all assets into a pool of assets, after assets are hosted on IPFS randomise their attachment to different NFT's inside of your collection
- Multiple chain NFT contract deployment (Ethereum, Solana etc.)
- Test net and main net deployment options, so users can test their collections before going live
- Multiple dynamic experiences in various mediums (VR, AR, 2D, Video etc.) produced immediately upon NFT collection creation
- Custom REST API, so users can hire their own dev teams and create bespoke experiences from the assets inside of their existing IPFS hosted NFT metadata
- Technical documentation to facilitate continued development for users who wish to go that route and build on top of the experiences already provided.

## Development Roadmap

The above functionality can be completed in 16 weeks from the start date of development. The following milestones will be continuous, meaning that one will start as soon as the previous finished.

We will aim to have UI/UX as well as 3D digital assets and NFT experience wireframes/storyboards produced by a professional designer with expertise in that specific field. We will then work on the development side of things, implementing the designs in the actual code and getting them setup inside the web browser. 

### First Milestone - UI design & frontend development + backend setup & hosting

Time: 2-4 weeks
Total Cost: $12000

### Second Milestone - NFT creation through UI on the test net including metadata creation + full back end integration

Time: 2 weeks
Cost: $6000

### Third Milestone - Metadata randomisation & smart contract modification options + smart contract deployment

Time: 2-4 weeks
Cost:  $12000

### Fourth Milestone - NFT virtual experiences (includes 3D & 2D design of custom digital assets + development)

Time: 2-4 weeks
Cost: $12000

### Fifth Milestone - Multiple chain deployments across main net and test net + technical documentation + application hosting

Time: 2 weeks
Cost: $3000

## Total Budget Requested

Total Budget: $45,0000

35% ($15,750) of the budget is set aside for design and hosting fees.

65% ($29,250) is set aside for development fees and related costs.

## Maintenance and Upgrade Plans

Our plan is to continue building on the features and experiences offered. We want NFT Teleporter to be the go to app for businesses, influencers and everyday individuals who want to tokenize digital assets as NFT's.

We foresee that their will be many niches in the NFT industry in the near future, such as families wanting to save memorable moments like births, weddings etc. as NFT's they can keep forever (maybe we could offer an on chain data options in the app for this). 

We'd like to be at the forefront of this, offering non technical users a quick and easy way to rapidly tokenise their digital assets with no code!

# Team

## Team Members

Naail El-Sawah

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/naail-elsawah-525580198/

## Team Website

https://devpost.com/xx014939?ref_content=user-portfolio&ref_feature=portfolio&ref_medium=global-nav

## Relevant Experience

I graduated one year ago with a Bachelors degree in Computer Science form the University of Reading. I began working as a developer early on in my studies, so I was able to amass much more development experience than the average CS grad. I recently resigned from my position as a Front End developer on the Ford team at ESC (which is a large global web development agency specialising in E-commerce stores) to focus more on Web3. I've had the opportunity to work on E-commerce stores for large brands such as Ford and Fushi Wellbeing over the last few years professionally, whilst at the same time experimenting with XR and Web3 applications in my spare time.

I recently won one of the top IPFS/Filecoin prizes at the Moralis 2022 hackathon for my project "Your Meta World" --> https://www.yourmeta.world/

I then went on to win a prize at the Faber Web3 hackathon for the first iteration of NFT Teleporter --> https://devpost.com/software/nftteleporter-com

After receiving a Filecoin next-step grant for NFT Teleporter, I completed the promised functionality and entered it into the Hedera Smart Contract hackathon --> https://devpost.com/software/your-meta-world-931izb?ref_content=user-portfolio&ref_feature=in_progress

As you can see I'm passionate about Web3 and have a proven track record both professionally and academically both in development and in Web3.

## Team code repositories

https://github.com/xx014939/IPFS-Unity-Scene-Minter
https://github.com/xx014939/nft-teleporter-react-app

**Comment by xx014939** [comment]
Hey @realChainLife  @ErinOCon 

I'd be happy to answer any questions you guys may have, or elaborate on any points in my proposal if you'd like me to?

Thanks

**Comment by ErinOCon** [comment]
Hi @xx014939, thank you for your proposal! Below are a few additional questions that will help with our review:
1) Briefly describe your plan for testing usability and onboarding users. 
2) Do you have short and long-term goals for maintaining and growing your user base?
3) Is demand data available for this proposal?

**Comment by xx014939** [comment]
Hey @ErinOCon , thanks for getting back to me!

I have answered your questions below, if there are any additional questions/concerns you may have please let me know and I'll do my best to answer. If based on your experience you have any suggestions you might think helpful, I'd be happy to hear them also :)

Just before I answer the questions specifically, I would like to mention that I have worked as a freelance web developer for several years now alongside my day jobs. I still work with E-Commerce clients part time on a regular basis, and I have begun to receive an influx of requests from potential clients who want to sell NFT's on their E-Commerce stores alongside their other products. As such, I'm in an advantageous position to communicate directly with my target market and use them for product feedback / testing. 

1. Briefly describe your plan for testing usability and onboarding users.

Our first milestone is also one of our longest, as it involves the creation of our UI/UX for the web app. Not only will I select an experienced UI/UX expert to work on the designs with myself, but we will validate their usability via Explorative Usability Testing with a non technical control group.

As we proceed through the development of the UI, we will perform Comparative Testing with a handful of different iterations of our UI (non-functional UI prototypes can easily be deployed for this). Based on this, we will finalise the designs as we move towards coding the actual application, and then perform a final testing/review round at the end of development cycle to ensure product usability with our target market. 

2. Do you have short and long-term goals for maintaining and growing your user base?

Short Term Attainment 

I am an active member of many Web3, SASS and NFT communities (online and in person) and regularly take part in discussions around new businesses, services and protocols in this space. Whilst these communities may not contain the "non-technical" clientele the application is aimed at, the app is still something individuals in these communities want because

1. It saves them time when building NFT collections for their clients or themselves
2. It's an easy way to create NFT's in bulk and access them through a simple REST API
3. NFT Teleporter provides additional value to an NFT other than what is already build into the NFT at no extra development cost

In addition to the above, I am heavily embedded in the E-Commerce community, and NFT's are something I am increasingly being approached for. This application is something easy to refer people to in order to achieve their goals without spending an enormous amount on development costs.

And finally, launching the web app on services like Product Hunt will also be done.

Long Term Attainment & Maintenance 

In the long term, paid advertising, referrals and influencers/celebrities are likely to be part of our strategy. This will work in combination with word of mouth marketing and a continuation of building on our features.

My expertise is in Shopify development, and as Shopify is trialling their NFT integration currently I believe there will be huge opportunity for app integration with NFT's and Shopify E-Commerce stores in the near future. NFT Teleporter is well placed to take advantage of this, especially if we can show existing Shopify integration in the short term.

Maintaining customers will revolve around offering new integrations, blockchains, experiences and art generators for NFT collections. We will survey the community and learn from what they need most, and then build these requests into the application regularly. 

3. Is demand data available for this proposal?

Somewhat. I can speak from my own personal experience in the E-Commerce space, around a huge increase in businesses wanting to offer NFT's on their storefronts.

We can also infer a trend from the following data 

1. The NFT market grew 21,000% last year with almost $20 billion in sales
2. Large corporate businesses are purchasing NFT's and making their own collections
3. Popular artists are onboarding into Web3 and creating their own NFT collections


[1] - https://bitcoinke.io/2022/03/nft-market-grew-21000-percent-in-2021-says-latest-march-2022-report/
[2] - https://cointelegraph.com/news/corporate-brands-target-nfts-and-adoption-continues-to-skyrocket
[2] - https://www.ledgerinsights.com/audi-launches-novel-fractional-nft/
[3] - https://news.artnet.com/market/takashi-murakami-nft-interview-2114309


Thanks again, if you need more info please let me know!

**Comment by ErinOCon** [comment]
Hi @xx014939, thank you for the quick response! We will be in touch with an update by next week.

**Comment by xx014939** [comment]
Hey @ErinOCon 

Is there any update on this?

Thanks!

**Comment by ErinOCon** [comment]
Hi @xx014939, we would like to fund the outlined work! Please email grants@filecoin.org to discuss next steps.
