### ISSUE TITLE
Next Step Microgrant: GovtJobKaro

### ISSUE THREAD

**Issue by GovtJobKaro** [filecoin-project/devgrants#601]
### 1. What is your project? (max 100 words)
GovtJobKaro is a learning platform with offline and online course structures based in India. Our intent is to educate people in various subjects that are useful for them to get jobs in the Government Sector. Our portfolio of teachers include graduates from India's top most institutes dedicated towards the fullfillment of the students.

Github: https://github.com/GovtJobKaro/govtjobkaro/
Website: https://govtjobkaro.com/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
We will be issuing NFTs as a certificate of completion of courses to participants which will be issued using IPFS, Filecoin.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
This grant will help integrate Filecoin into the project. Students will be able to showcase their completion of courses using the NFTs. It can be verified by anyone giving authenticity. 
 
### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
No
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project. N/A
* How did you learn about our microgrant program? Website
* If your project was created as part of an event or hackathon:
  * What was the name of the event? N/A
  * Please link to your hackathon submission N/A

**Comment by ErinOCon** [comment]
Hi @GovtJobKaro, thank you for your proposal! Can you include the applicable coding of your project to the repo?

**Comment by GovtJobKaro** [comment]
Thank you @ErinOCon , we have added the code in the repo. Please check.

**Comment by GovtJobKaro** [comment]
@ErinOCon please check the following links:

https://github.com/GovtJobKaro/govtjobkaro-frontend

https://github.com/GovtJobKaro/govtjobkaro-learning-dashboard

**Comment by GovtJobKaro** [comment]
Hi @ErinOCon , please let me know if you need any additional information or details regarding the project.

**Comment by ErinOCon** [comment]
Thanks, @GovtJobKaro. Can you provide more detail explaining the next steps needed in your project on how this specific grant would be used to accomplish those steps?

**Comment by GovtJobKaro** [comment]
We will be firstly integrating the NFTs as certificates for students on the completion of the courses. Going forward we will host our course videos and other related content of the website on Filecoin/IPFS. With the help of this grant, we will be able to integrate Filecoin/IPFS into the website in different sections like NFTs, course videos, content, etc.

**Comment by GovtJobKaro** [comment]
Hi @ErinOCon please let us know if you need any additional information from our side regarding the project.

**Comment by ErinOCon** [comment]
Hi @GovtJobKaro, thank you for your patience. This microgrant has been approved! Can you provide an email to submit payment details?

**Comment by GovtJobKaro** [comment]
Thank you @ErinOCon , please use partnerships@govtjobkaro.com for sending the payment details.

**Comment by GovtJobKaro** [comment]
Hi @ErinOCon , can you please check with your team? We haven't received the email on the above id regarding submission of payment details.

**Comment by ErinOCon** [comment]
Hi @GovtJobKaro, an email has been sent using the provided address. I also wanted to make sure you were aware of [nft.stroage](https://nft.storage/), in case it can be a useful tool for your project. 

Happy building!

**Comment by GovtJobKaro** [comment]
Thank you @ErinOCon , we will surely check nft storage. Thank you for sharing the details.
