### ISSUE TITLE
 LEGACY – Preserving Memoirs Forever

### ISSUE THREAD

**Issue by motherdomains** [filecoin-project/devgrants#605]
# Open Grant Proposal: `MEMTELL-LEGACY`

**Name of Project:**
LEGACY – Preserving Memoirs Forever

**Proposal Category:**
app-dev

**Proposer:**
TheLegacyNetwork

**Technical Sponsor:**
Blake Lezenski / Outlier Ventures Filecoin Base Camp

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:**
Yes

# Project Description

How does one preserve one's Legacy “forever”, beyond our mortal lifetimes? What happens to our content, creations and assets after we've departed? Why spend time and energy investing into publishing content, that disappears whenever we move away from a platform? What is the historical value of today's moments and experiments to future generations?

Nowhere that we presently store our data and content is reliably assured to be available well into the future. Domain names expire, web hosting access is controlled by multinational conglomerates on periodic subscription models, social media platforms become extinct upon the mass migration away of its populace, and much of present life is based on short-term gratification: capitalizing on watered-down moments at the detriment of the future.

What if corporations were to restrict or censor our creations? What happens to the meaningful content we store, if we want to delete social media and / or questionable tech giants from our lives? What if we can no longer pay our hosting or CMS bills, or domains lapse from ever-rising domain prices, or disinterest? What happens when we die – where does all this content go? Particularly, the invaluable web of collective human experiences, knowledge and history?

Legacy publishes stories, memoirs, moments, media and milestones into the permaweb, passing down content for future generations of family, communities and society. When people publish their important memoirs, or stories behind their photographs, they will be saved in one place “forever”, where other sites and apps can be granted access to them upon the user's explicit permission.

Through this development process, we'll uncover blockchain solutions to wider, useful mechanisms of digital inheritance, a truly permaweb of Linked Data stories/memoirs/content, efficient DAO moderation and administration of publishing and communities, cross-generational secure/private/custom access to specified blockchain content, improving global accessibility to writing/transcribing tools (i.e. disabilities, illiteracy, other language speakers), Metaverse integration, and more.

### What are the benefits to getting this right?
By the end of this R&D process, we'll devise a suite of simple yet prolific functions to develop Legacy, that enhance and augment real life, humanity's history, and interpersonal digital-real world relationships. We'll discover new and alternative Filecoin/IPFS use cases for distributed storage / interoperable access between platforms, applications and metaverses. Our discoveries should inspire and progress furthermore third party applications, as well as the inherent discovery of future Filecoin systematic needs and requirements.

### What are the risks if you don't get it right?
A heap of data committed to the permaweb, unfulfilled Legacy promises, mutual emotional disappointment. Considerable time, money and resources invested into the undertaking.

Filecoin's resiliency in its ability to ensure a truly far-future permaweb, the prospective FIL costs of mass content storage (petabytes and beyond), and whether web3 will ever truly be widely adopted.

## Deliverables

A fully-functional Legacy platform (builder, account backend, semantic linked data and Legacy Pages) – with all of its demo content (memoirs, photos, video clips, audio recordings, NFTs) hosted across Filecoin and IPFS. We'll have instituted prototypes of the processes and mechanics that help autonomously build and moderate the system, and reward its various participants.

Creators will be able to submit their important Legacy content (memoirs, stories, multimedia) to the platform and their “forever” Legacy Pages. Readers can browse content of interest through Linked Data semantics, and view moments and memoirs on collective timelines and maps. We can run mutual interest campaigns, such as calling for survivors' memories of important moments like the falling of the Berlin Wall, tributes from fans of deceased legends, and countless other historical milestones, particularly while older generations are still alive to share them.

### Timeline
The timeline proposed spans over a 4-5 month period, intended from June 1st 2022 through September 2022.

### Milestone 1 – Decentralised File Storage
Drafting the proposed architecture of the wider system, mapping its relation to Filecoin/IPFS and other necessary processes (multichain interoperability, tokenomics, etc). Converting the present Legacy demo and its content from temporary AWS S3 repositories into fully IPFS-hosted of content. Preview / draft content on IPFS, experiment with Filecoin as a “Commit to Legacy” permaweb (need better understanding). Metaverse rendering and assets to be stored on IPFS.     
Resources required: Strategy, Research, Development
     
People/Roles: Web3 strategist to lead research & sketch proposed architecture. Tech lead to convert/integrate IPFS into Legacy content processes, and explore the permaweb possibilities. Opportunity to contract Filecoin freelancer programmer to assist.
     
Duration: 1 month (June 1-30 2022)
     
Funding required: USD15,000

### Milestone 2 – Access & Inheritance
Legacy user backend. Simplifying user account registration/authentication to the Legacy platform, using web3 wallet protocols. Enabling access controls of specific content entries: E.g. securing NFTs and sensitive entries that are committed to a blockchain. Exploring Inheritance models of access, and public content considerations beyond an author's lifetime for future generations / items of later historical interest.
     
Resources required: Research, Development
     
People/Roles: Web3 strategist to research & draft proposed solutions, liaising with relevant specialists in their fields. Tech lead to institute levels of access controls, including time-based (e.g. post-mortem), granting family/heirs access to account. Filecoin freelancer programmer to assist.
     
Duration: 4-6 weeks (July 1-31 2022)
     
Funding required: USD20,000

### Milestone 3 – DAO & Tokenisation
Prototype of proposed DAO functionality, including its interaction with Tokenomics, treasury, rewards and incentives. DAO processes to moderate and highlight content, as well as securing initial user onboarding. Exploring relevant methods of tokenisation to 1) settle FIL fees for hosting – short-term and far-future; 2) Rewarding necessary moderation / Guardian processes;     3) Incentivising user adoption mechanisms via content submission rewards and/or offering “free” commits to the platform
     
Resources required: Strategy, Research, Development, FIL tokens, possible DEX integration
     
People/Roles:  Web3 strategist to research & draft proposed solutions. Studying past research papers. Senior team discussion and workshop sessions on tokenomic and DAO architecting. Tech lead to integrate DAO processes and tokenomics rules. FIL / DEX integration. Filecoin freelancer programmer to assist.
     
Duration: 4-6 weeks (August 1-31 2022)
     
Funding required: USD30,000

### Milestone 4 – Preliminary User Adoption
Polishing up to prepare a Legacy Beta release by the milestone's end. This phase onboards an Alpha list of real-world users across multiple disciplines, for review of the system. Bug awareness / fixing, feature feedback and future feature set proposals. Documentation to be written and improved.
     
Resources required: Human Testers, Developers, FIL tokens, Marketing
     
People/Roles: Developer for bug fixing and coding tweaks. Filecoin freelancer programmer to assist. Marketer. Community Manager to onboard and cater to Alpha testers. Tech content writer/s for documentation.
     
Duration: 4-6 weeks (September 1-30 2022)
     
Funding required: USD25,000

## Total Budget Requested
USD$90,000

## Maintenance and Upgrade Plans

Through this R&D we'll explore future-proof processes to ensure Legacy's long-term Guardian DAO mechanisms, rewarding active Guardians now and (theoretically) centuries into the future. Treasury tokenomic allocations are intended to ensure technical support/maintenance, ongoing development, moderation, bug bounties, etc. In the meantime, our core development team will make manually-scheduled updates and correct bugs as necessary.

# Team

## Team Members
<b>Jono Birkett
Andreas Vogel
Kyle Matheson
Sea Ansley</b>

## Team Member LinkedIn Profiles
<b>Jono</b> -[ https://www.linkedin.com/in/jonothanbirkett/](https://www.linkedin.com/in/jonothanbirkett/)
<b>Andreas</b> -[ https://www.linkedin.com/in/andreasvogel/](https://www.linkedin.com/in/andreasvogel/)
<b>Kyle</b> -[ https://www.linkedin.com/in/kyle-matheson/](https://www.linkedin.com/in/kyle-matheson/)
<b>Sea</b> -[ https://www.linkedin.com/in/gashe/](https://www.linkedin.com/in/gashe/)

## Team Website
https://legacy.page/

## Relevant Experience
<b>Jono</b> – CEO, co-founder of Memtell, developed Memtell’s web2 app, crafted partnerships for European-wide retail distribution across thousands of physical outlets, headed marketing for Wao.io through Sevenval GmbH
<b>Andreas</b> – Headed Deutsche Telekom’s Portfolio of Business Applications, serial entrepreneur, published author
<b>Kyle</b> – CTO of Memtell, 10+ years experience leading tech companies / projects, coded across Arweave, Immutable, some IPFS and more, former Digital Media Manager at Bitcoin Group (2014)
<b>Sea</b> – CEO of Mother.Domains, 20+ years senior web architect & strategist, Certified Holochain Developer (from 2017), “pioneer in Internet radio” (from 2001), producer of hybrid events & festivals, published author

This experienced core team has enjoyed long-term success across all spectrums of Internet-based businesses, from architecture, research, strategy, domain & hosting infrastructure, development, production, onboarding strategic partners, marketing and bringing applications to market.

## Team code repositories

https://github.com/leoz2007 – Lead Memtell Developer
https://github.com/TheLegacyNetwork

# Additional Information

Latest Legacy pitch deck: 
[LEGACY - PITCH DECK MAY 2022.pdf](https://github.com/filecoin-project/devgrants/files/8760103/LEGACY.-.PITCH.DECK.MAY.2022.pdf)

We’re interested in any directory or recommendations of certified Filecoin/IFPS freelance programmers, with the intention of enlisting at least one to assist with our proposed undertaking. We’re keen on expanding our team’s diversity, if the best candidate enables us to.

**Comment by ErinOCon** [comment]
Hi @motherdomains, thank you for your proposal! We would like to fund part of the outlined work! Please email grants@filecoin.org to discuss next steps.
