### ISSUE TITLE
Next Step Microgrant: ipfs-pixel-drawing https://nftap.dev/

### ISSUE THREAD

**Issue by nftapdev** [filecoin-project/devgrants#606]
### 1. What is your project? (max 100 words)
This drawing tool allows you to make original pixel art built on IPFS. 
Goal is to allow users to create original-collectible pixel artwork and save 100% of the image’s pixel data information on IPFS.. 
Base64 to IPFS  - https://nftap.dev is the solution for real NFT data!
Base64 is an encoding algorithm that converts any characters, binary data, and even images or sound files into a readable string, which can be saved or transported over the network without data loss. The characters generated from Base64 encoding consist of Latin letters, digits, plus, and slash.

https://github.com/nftapdev/ipfs-pixel-drawing
https://nftap.dev/ or https://ipfs-pixel-drawing.vercel.app

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
The ipfs-pixel-drawing app is built and integrated on/within IPFS.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
More dev time to implement optional drawing variations. Next step is implementing pinning-lists (nft.storage, web3.storage). We are planning many improvements starting with UI updates and focusing on improving the functionalities, like NFT smart contract deployment as https://nftap.dev is the solution for real NFT data!
 
### 4. Is this project open source?
Yes.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
N.A  No
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Willem Mesdag, dev@nftap.dev , https://github.com/nftapdev , Dev.
* How did you learn about our microgrant program?
Social Media 
* If your project was created as part of an event or hackathon:
N.A  No
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
N.A  No
  * Please link to your hackathon submission
N.A. No.

**Comment by ErinOCon** [comment]
Hi @nftapdev, This microgrant has been approved! Look out for an email to submit payment details.
