### ISSUE TITLE
GUMMYS WEB3 (Decentralized video and streaming platform)

### ISSUE THREAD

**Issue by sorrentinopasquale** [filecoin-project/devgrants#607]
# Open Grant Proposal: Gummys WEB3, video and streaming platform, storing metadata and short videos on Filecoin

**Name of Project: GUMMYS**

**Proposal Category:** app-dev

**Proposer:** `replace with your GitHub username`

**Technical Sponsor:** I sometimes talk to Brad Holden sharing updates about our projects. We also know david@protocol.ai.
Gummys is actually incubated by CVVC (https://www.cvvc.com/).

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Please respond with either. Yes.

# Project Description

We are building a WEB3.0 video and streaming platform. 
Gummys solves several industry issues like no user rewards, content creators having no ownership of their own content, there is no free speech and more.
Using the blockchain we are creating an hub where people can talk freely about the future.

What are the benefits to getting this right? We can pay developers in order to complete our roadmap including the storing of files on Filecoin.

What are the risks if you don't get it right?  Just less money to build.

What are the risks that will make executing on this project difficult? Becoming viral will be the key.

## Deliverables
We are working on several amazing functionalities like wallet connect, crypto donations, NFT from videos and snapshots, shared revenues from videos via NFT, ownership of video on the blockchain, decentralized storage.
 

www.gummys.io
if you are open for a chat
https://calendly.com/psorrentino

**Comment by ErinOCon** [comment]
Hi @sorrentinopasquale, thank you for your interest in our grant program! In order to proceed with our review, the following information is required: 
1) Development roadmap
2) Budget breakdown
3) Team information.

Please let me know of questions!

**Comment by sorrentinopasquale** [comment]
Sure.
Roadmap:
Roadmap🛣
Q1 2022:
Wallet integration
User profile page
User channels
Live streaming 
Video upload
Give tips/incentivize crreators
Beta version live 

Q2: 2022
Live streaming chat
Video comments
Advertisement Platform
Advanced moderation 
Stream-watch-to-earn
Engage-to-earn 
FileCoin storage (via IPFS)

Q3 2022: 
Full version live 
$GUMMYS Token IDO 
Voting system DAO
User levels 
NFT sales 
Video Tokenization 
Open Broadcasting Software (OBS) 
Integration Mobile Applications (IOS & Android)

Q4 2022:
Cross-chain support
DeFi integrations
TV applications 
Metaverse integration 
NFT Marketplace 
Subscriptions
Events 

Budget breakdown:
$10k for uploading functionality for video metadata, fetching and management of the files on Filecoin
$10k short video upload on FileCoin, video management, fetching video
$10k Snapshots and images upload of videos on Filecoin, management and fetching. 
$15k NFT minting of all media stored on Filecoin via Gummys App

Team information:
Pasquale Sorrentino, CEO, Software Engineer - 10+ years of experience in IT. Experiences in corporates like FedEx, Rabobank, Accenture and crypto projects. [www.linkedin.com/in/pasquale-sorrentino-1aa1a363/](https://www.linkedin.com/in/pasquale-sorrentino-1aa1a363/)

Domas Juodele, CTO - 10+ years of experience in IT.
Former at DELL, ABN AMRO, FedEx, EU Concil and more.
[www.linkedin.com/in/domas-juodele-a388009/](https://www.linkedin.com/in/domas-juodele-a388009/)

Guido Schmitz-Krummacher, Board Member - Lawyer, a Certified Swiss Board Member of several projects like Cardano and Tezos. Expert in International law, corporate law and economics.
[www.linkedin.com/in/guidos1/](https://www.linkedin.com/in/guidos1/)

More members: [www.gummys.io/](https://www.gummys.io/#team)

Advisors
Marco Calicchia - 6+ Years experience in crypto. Building Communities for over 50 projects. Former Director of Sales at CertiK. [www.linkedin.com/in/marcocalicchia/](https://www.linkedin.com/in/marcocalicchia/)

Tejas Chopra -  Engineering Leader at Netflix. More than a decade of experience working on infrastructure at companies such as Apple, Samsung, Box. https://https://www.linkedin.com/in/chopratejas/

**Comment by sorrentinopasquale** [comment]
Good morning,
yes just updated the comment.

Please let me know if you have any comment.

Best,
Pasquale
________________________________
Da: ErinOCon ***@***.***>
Inviato: mercoledì 1 giugno 2022 08:04
A: filecoin-project/devgrants ***@***.***>
Cc: Sorrentino Pasquale ***@***.***>; Mention ***@***.***>
Oggetto: Re: [filecoin-project/devgrants] GUMMYS WEB3 (Decentralized video and streaming platform) (Issue #607)


Hi @sorrentinopasquale<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsorrentinopasquale&data=05%7C01%7C%7Cbdf935a4d9464789bc8f08da43948ef9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637896602579558837%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xMRoEWOBrDR7C7vsqKePDt3Vw2bZcw2Z%2B4aXQ3hSpUk%3D&reserved=0>, thank you for your interest in our grant program! In order to proceed with our review, the following information is required:

  1.  Development roadmap
  2.  Budget breakdown
  3.  Team information.

Please let me know of questions!

**Comment by sorrentinopasquale** [comment]
Good day, any news about our grants application?

Best,
Pasquale
________________________________
Da: ErinOCon ***@***.***>
Inviato: mercoledì 1 giugno 2022 08:04
A: filecoin-project/devgrants ***@***.***>
Cc: Sorrentino Pasquale ***@***.***>; Mention ***@***.***>
Oggetto: Re: [filecoin-project/devgrants] GUMMYS WEB3 (Decentralized video and streaming platform) (Issue #607)


Hi @sorrentinopasquale<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsorrentinopasquale&data=05%7C01%7C%7Cbdf935a4d9464789bc8f08da43948ef9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637896602579558837%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xMRoEWOBrDR7C7vsqKePDt3Vw2bZcw2Z%2B4aXQ3hSpUk%3D&reserved=0>, thank you for your interest in our grant program! In order to proceed with our review, the following information is required:

  1.  Development roadmap
  2.  Budget breakdown
  3.  Team information.

Please let me know of questions!

**Comment by sorrentinopasquale** [comment]
Hello any news?

Best,
Pasquale

**Comment by sorrentinopasquale** [comment]
Good day, thanks for the answer.
https://github.com/filecoin-project/devgrants/issues/607

Gummys is a Web3-powered video and streaming platform that rewards users for creating, watching, and interacting.  We want to create a new income opportunity for content creators and users. The team is very strong in the space and we already have a beta version of the product.

CVVC(https://www.cvvc.com/) has just invested in GUMMYS along with other VCs.
Polygon Studios and AAVE are finalizing grants for us as well. In some days we will also take part in ChainLink and Dfinity hackathons.

Best,
Pasquale


[https://opengraph.githubassets.com/0456ad466d8d99743395e4516713715effcdbda1548c2afc3f823734b7248438/filecoin-project/devgrants/issues/607]<https://github.com/filecoin-project/devgrants/issues/607>
GUMMYS WEB3 (Decentralized video and streaming platform) · Issue #607 · filecoin-project/devgrants<https://github.com/filecoin-project/devgrants/issues/607>
Open Grant Proposal: Gummys WEB3, video and streaming platform, storing metadata and short videos on Filecoin Name of Project: GUMMYS Proposal Category: app-dev Proposer: replace with your GitHub u...
github.com

________________________________
Da: General Support ***@***.***>
Inviato: lunedì 20 giugno 2022 12:01
A: ***@***.*** ***@***.***>
Cc: ***@***.*** ***@***.***>; ***@***.*** ***@***.***>; ***@***.*** ***@***.***>; ***@***.*** ***@***.***>; ***@***.*** ***@***.***>
Oggetto: Re: R: [filecoin-project/devgrants] GUMMYS WEB3 (Decentralized video and streaming platform) (Issue #607) #GS00010890

New reply for the ticket #GS00010890

Hi Pasquale,

Thank you for getting in touch.

Are you trying to apply for Gitcoin's Grants round? if yes, please provide me with your grant's link. It should looks like this: https://gitcoin.co/grants/6541/chainflag

Thank you.

Yuki Ling

Customer Support Agent

#GS00010890
General Support
This will be appended to all your emails.

**Comment by sorrentinopasquale** [comment]
### New reply for the ticket #GS00010890

Hi Pasquale,

That is a Github's link and not Gitcoin. This is support for Gitcoin.

Thank you.

Yuki Ling

Customer Support Agent

#GS00010890

General Support

This will be appended to all your emails.

**Comment by ErinOCon** [comment]
Hi @sorrentinopasquale, thank you for the additional information! This grant has been approved. To proceed with next steps, please email grants@filecoin.org.

**Comment by ErinOCon** [comment]
Hi @sorrentinopasquale, we have sent an email with next steps using the address in your profile. Please let us know of any questions!
