### ISSUE TITLE
Certy Network - Decentralized Storage for Educational Certificate, Career Builder and Learn to Earn Platform

### ISSUE THREAD

**Issue by AaronCerty** [filecoin-project/devgrants#608]
# Open Grant Proposal: Certy Network

**Name of Project:** Certy Network 

**Proposal Category:** app-dev 

**Proposer:** AaronCerty

**(Optional) Technical Sponsor:** Mr. Jenks Guo from Filecoin Foundation

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes 

### Project Description
We received 25000 USD grant from NEAR Foundation.

**Problems:**
Prevalence of fake educational certificates: There are millions of fake diploma search results available online. Although document forgery is prohibited, it is not difficult to find online sellers that market "undetectable and like-real" bachelor's degrees from prestigious universities. As a result, educational certificate counterfeiting has become a serious problem in many countries.

Employers usually have difficulty in verifying a candidate's qualifications: The procedure of verifying an applicant's certification is time-consuming, inefficient, and riddled with flaws. However, due to some hassles, many businesses prefer to forgo the trouble and simply double-check candidates who raise a red flag. This lax screening can create numerous loopholes, allowing unqualified individuals to be admitted and substantially damaging labor quality.

Students lack career orientation and industry knowledge, specifically computer science majors: In the world, technology is an emerging job market with a lot of positions available, but there are not enough candidates to fill them. This is because only 30% of students in this field are qualified and industry-ready, with the rest lacking critical technical and soft skills.

**Solution:** Certy Network is a decentralized storage for degrees and certificates built on top of Filecoin. We intend to develop a Blockchain-powered application for educational credential validation with the goal of eliminating the underlying flaws of the current certification system that have fostered the dominance of counterfeit documents. Furthermore, to make use of the abundance of extractable data, we use Artificial Intelligence to personalize students' learning pathways and support them with career orientation. Our project's expected objective is to develop a forgery-free certification environment, which would dramatically improve the reputation of educational institutions and businesses' recruitment of actual talents, while also enhancing students' employability and job preparation. In addition, a Learn to Earn platform, where users may earn money while learning new skills, is being developed to leverage the aforementioned features.

+ Blockchain-powered: Certy provides a timestamp certificate storing system that is immutable and forgery-free, accompanied by time-saving verification. Besides, there is no need for middlemen (notary office) to verify educational documents. Overall, the project’s purpose is to store education certificates as NFTs (Non-fungible tokens), which are digital assets that represent real-world objects like art, music, in-game items and videos, to utilize its immutable and transparent feature. The creators of NFTs, who are authorized individuals from educational institutions, can mint NFTs and send them to their students. These NFTs will be stored on the IPFS network. Then, a unique hash value of the contents will be generated and stored on the blockchain. After that, normal users can based on the hash value store on-chain to reconstruct the NFTs.

+ AI-powered: Utilizing the abundance of extractable data, Certy's AI system analyzes students' qualifications, goals and preferences, in order to formulate a personalized learning roadmap and career guidance for higher employability chances. For job-seeking, we can filter suitable job posts for students and build a digital profile based on their learning journey statistics (assignment completion, consistency,...) to create a more comprehensive insight beyond that of a traditional CV.
 
**Value**
Certy can advance Filecoin mission statement by bringing an open source education platform to Filecoin ecosystem. Moreover, as we have learn to earn feature, we can cooperate with Filecoin to attract more users from non-crypto world and crypto users from other chains. Specifically, we will upload Filecoin developer courses to our platform to educate more users about the Filecoin ecosystem.

**Deliverables**
If we receive a grant from Filecoin, we will use it to develop the Career Builder and Learn to Earn platform. Precisely, the final deliverables are as follow: 

- A platform that connects users with desired jobs based on their interests and skills.
- A platform that offers a Learn to Earn feature, where users can earn while learning new knowledge.

### Development Roadmap
**Our team have completed the Degree Minting feature, so in this roadmap, we only mention the Career Builder and Learn to Earn feature.** 

**Milestone 1:** 5000$: 15 days 

- Operation cost, hosting, related softwares & tool (yearly plan)
- UI/UX Design
- Developers hiring 

**Milestone 2:** 10000$: 45 days (**Career Builder** feature)

- Frontend development for certificate management: A dashboard that show users certificate, a system to connect users with HR and vice versa   
- Smart contract to manage certificate. 
- Backend to manage the Filecoin network. 

**Milestone 3:** 10000$: 45 days (**Learn to Earn** feature)

- Frontend development for course management: A dashboard that show all the courses, filter, shortlisted courses
- Online learning system
- Backend to manage courses: Add/drop/ courses,...

**Total Budget Requested:** 
|  Milestones  | Tasks | Delivery Time | Costs |
| ------------- | ------------- | ------------- | ------------- |
|  Milestones 1  | Operation, hiring & UI/UX Design | 15 days | 5000$ |
|  Milestones 2  | Career Builder feature | 45 days | 10000$ |
|  Milestones 3  | Learn to Earn feature | 45 days | 10000$ |
| Total | | 105 days | 25000$ |

### Team
**Team Members**
Aaron Ng - CEO
Minh Ha - CMO
Edric Ngo - CTO
Khiem Doan - Blockchain Developer
Dung Nguyen - Software Engineer
Giang Le - Full Stack Developer

**Team Website**
Website: https://certify-liard.vercel.app/

**Relevant Experience**
Minh Ha - CMO: Regional Community Manager at Covalent, Regional Community Manager at Algodex, Ambassador at Subquery.

Edric Ngo - CTO: Software Engineer at Vinagame, Co-founder and Lead Developer at Digital Monster and Hero Universe (Binance Smart Chain) with 5m$ Market Cap and 2000 active users, top 15 BSC MVB. Blockchain Developer at Wrejects and Battlefly. Github: https://github.com/EdricNgo

Khiem Doan - Blockchain Developer: Blockchain Developer at Black Ventures, Founder and Lead Developer at Allchains (https://allchains.xyz/). Github: https://github.com/khiemdt

Dung Nguyen – Software Engineer: Software Engineer at Viettel, Application Developer at Storytree Inc, Application Developer at Tokenize Xchange (Digital Currency Trading Platform). Github: https://github.com/dxungngh

Giang Le - Full stack Developer: https://github.com/GiangLh7 

**Team code repositories**
Certy Frontend: https://github.com/CertyNetwork/Certy-Frontend
Certy Contract: https://github.com/CertyNetwork/Certy-Contract/tree/dev

### Additional Information
Our project received a grant from NEAR Foundation (25000$).

**Comment by AaronCerty** [comment]
@realChainLife @ErinOCon 

I have an update about my proposal. Mr. Jenks Guo from Filecoin Foundation accepted to be the technical sponsor of my project. If you need any additional information regarding the project. Please do not hesitate to contact me!

**Comment by ErinOCon** [comment]
Hi @AaronCerty, thank you for your proposal! We would like to fund the outlined work! Please email grants@filecoin.org to discuss next steps.
