### ISSUE TITLE
Next Step Microgrant: Naipoa

### ISSUE THREAD

**Issue by GeoffreyMwashumbe254** [filecoin-project/devgrants#610]
### 1. What is your project? (max 100 words)
Naipoa.io is a web3 ecosystem for the East African creative economy and its worldwide fans & supporters, solving IP-rights- / work capital issues and changing the industry, by:

- offering a blockchain-based, decentralized registry/licensing service, with proof-of-ownership for any kind of artwork through NFTs, leading to stable & fair royalty payments

- providing access to work capital through social tokens and connecting East African artists to the global market, kick-starting careers

- providing a business module where fans become investors in the careers of their artists, their products, labels and brands and actively help building their artists‘ careers.

 

https://github.com/GeoffreyMwashumbe254/Naipoa
https://naipoa.io/ 
https://drive.google.com/file/d/13Ya8j1gsc6KBg4IEPuS5lv1JYB115fVd/view?usp=sharing

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
NFTs will be stored on IPFS through NFT.storage, with the option of downloading CAR into NFTs.
Backup through filecoin. Streaming module will call hashes from IPFS through api. 
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. UI/UX development --> $3000,-USD

2. Testing with test-group of Kenyan music & art students, with kick-off event at music business school --> $1000,-USD

3. Development of next naipoa.io module (social tokens), deploy on Avalanche C-Net, go live with kick-off event (online) and airdrops --> $1000,-

 
### 4. Is this project open source? 
YES

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
YES

  
### 6. Does your proposal comply with our Community Code of Conduct?
YES

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Geoffrey Mwashumbe: web3 dev, [geoffrey@naipoa.io,](mailto:geoffrey@naipoa.io,) github: https://github.com/GeoffreyMwashumbe254
Rob Boehm: coordinator, [rob@naipoa.io](mailto:rob@naipoa.io)
* How did you learn about our microgrant program? 
     Funding research
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @GeoffreyMwashumbe254, This microgrant has been approved! Look out for an email to submit payment details.
