### ISSUE TITLE
Next Step Microgrant: <Filecoin Documentation for Chinese Community + Official Doc Site Merging>

### ISSUE THREAD

**Issue by Zhixuan0318** [filecoin-project/devgrants#611]
### 1. What is your project? (max 100 words)
I'm currently leading the IPFS Chinese Documentation Project which is supported by the IPFS Dev Grants. The work and progress are smooth and slowly heading towards our second milestone. Hence, I think it's time to start leading more developers in the Chinese communities to recreate the Chinese ver. Filecoin Documentation.

**This project is to recreate, rephrase and manually translate the entire official Filecoin documentation for the Chinese community** and open up a gateway for them to start getting into the Filecoin ecosystem. This Chinese version documentation will be published on Github as well as create a merge on the official Filecoin doc site (turning the doc site multi-language, switching to Chinese ver. easily).

English is not the first language in a huge portion of the Chinese community. Chinese developers or newcomers have a hard time trying to read through the entire English documentation. In addition, auto page translation is always a bad idea, as most of the time, it will easily distort the whole meaning of the content (Chinese has its own sentence structure and grammar) and cause more confusion. Thus, Chinese Filecoin documentation is also essential.

Link to the Filecoin Chinese documentation repo I'm working on: [Click Here](https://github.com/Zhixuan0318/Filecoin-Docs-zh-CN)

Link to the IPFS Chinese documentation repo I'm currently leading: [Click Here](https://github.com/Zhixuan0318/ipfs-docs-zh-CN)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

This project is related to the Filecoin official documentation.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. **Invite more professional Chinese developers** who can help me out with translation, documentation writing, and proofreading, to let the entire workflow be more efficient.

2. **Recreate diagrams** embedded inside the documentation which is more suitable for the Chinese community to understand.

3. After getting the grant, I will plan and **create small bounties** to efficiently encourage talented Chinese developers or even enthusiasts to contribute to building this documentation. All work will be reviewed before merging. 

4. After the documentation is ready, I will **fork the entire official English doc site to work on the multi-language support feature**. We will first deploy a demo version and undergo testing. If everything is fine and no contradiction to the main branch, I will create a PR at the official Filecoin doc repo to undergo another check by the person in charge. 

<img width="162" alt="Screenshot (568)" src="https://user-images.githubusercontent.com/69501009/170528010-f009e513-dcf5-4149-b1f9-399d8a3cc86c.png"> 
👆 Note: I will add the Chinese ver. switching here. This is a screenshot from the official doc site. Users can switch to Chinese ver. and English ver. back and forth easily in the future!

#### Here is a brief roadmap:
* **Documentation [Github version]**: Mid-June 2022 - Mid-July 2022
* **Documentation review and second proof-reading**: Mid-July 2022 - End of July
* **Documentation merging and testing**: Aug 2022 - Mid-Aug 2022 
* **PR submission [Merging]**: End of Aug 2022

\* This roadmap is based on two weeks of grant reviewing period.  If the reviewing period is extended, an update of the roadmap will be done. 

### 4. Is this project open source?

Yes, this is a public good and open source. I will also keep maintaining the Chinese ver. parts after merging to the main public repo. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?

Yes. Everything related to the project and new implementations and creations throughout this period will be documented and shared with the Filecoin community.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions：

No.
  
### Additional questions:
* Personal detail:
Name: Tan Zhi Xuan
My Linkedin: https://www.linkedin.com/in/tan-zhi-xuan-805836196/
Email: (I will provide it privately after being selected)
Github: https://github.com/Zhixuan0318
Role: Project Leader

* How did you learn about our microgrant program?
I'm always working on IPFS and Filecoin projects, as well as participating in community events. Hence, I know the grant program.

**Comment by ErinOCon** [comment]
Hi @Zhixuan0318, thank you for your proposal! Once the work for the original microgrant is complete, we can proceed with the consideration of this grant. Please feel welcome to re-open this Issue at this time.
