### ISSUE TITLE
Web3 Course

### ISSUE THREAD

**Issue by web3Class** [filecoin-project/devgrants#613]
# Open Grant Proposal: `Web3Course`

**Name of Project:** Web3Course

**Proposal Category:** `app-dev`

**Proposer:** `Web3Course`

**(Optional) Technical Sponsor:** `N/A`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Please respond with either "Yes" 

# Project Description

Web3Courseis a comprehensive online learning platform launched for web3. It aggregates a large number of high-quality course content. It has excellent courses on blockchain, web3, nft, solidity, fvm and major chains. It helps the vast number of web2 users to improve their skills and knowledge to enter the web3 time .

Web3Course will rely on the storage of Filecoin, and use the decentralized storage method to store all course materials permanently and free of charge. We will use Web3.Storage to store the uploaded data of all users, and will also record the the video's info of courses based on smart contracts. When the video is watched by the user, the uploader can get a certain token income.

After the project is completed, the funds will be used to invite high-quality blockchain content providers to participate in the construction of the platform content and establish the first batch of high-quality blockchain course content.

## Value

Web3Course will become one of the most used tools for web3 users in the Filecoin-based ecosystem. Users of web2 or web3 who want to learn blockchain knowledge can find what they want to learn on the platform to improve themselves.

Any content creator can also earn a certain amount of incentives for others to watch videos. It can link learners and content providers to provide users with a good learning platform into the web3 era. 

Now there are many learning courses in the Internet of web2, but all of them are centralized, and it is easy to become inaccessible when the platform is closed. We make full use of the characteristics of Filecoin to save the courses permanently in the decentralized storage network. In this way, the course will not be inaccessible due to previous problems. At the same time, through the creator economy, when a user watches the creator's content, the creator can get a certain token income, which is also what we will bring to the "learn" to Earn".

## Deliverables
We will eventually deliver as follows:

1.  A new website build by Next.js
2. Use the web3 wallet to log in to the website function
3. Upload course function using web3.storage
4. The function of registering course information to the contract
5. Course study rankings
6. Favorite courses and like courses
7. Course learning function
8. Course Play Earning System 

## Development Roadmap

Milestone 1:  $10000 : 10 days

- Website UI/UX Design
- Determine functional requirements
- Writing the basic structure of the project

Milestone 2: $20000: 20days

- web3 wallet login system
- User information configuration contract writing
- Filecoin access function
- Contract & Upload tests
- Course display ranking function

Milestone 3: $20000: 30days

- User watch course function
- Video collect & like  function 
- Users view their favorite course data
- Video viewing revenue system

Milestone 4 : $10000: 30days

- Project function test
- Testnet launch
- Platform course resource establishment
- Mainnet open

## Total Budget Requested

 $60, 000

## Maintenance and Upgrade Plans
After the launch of the mainnet, we will use the funds provided by Filecoin to invite high-quality content owners to upload high-quality learning resources on the platform, and also hire people to upload more high-quality web3 learning resources
We will carry out the operation and promotion of the project in multiple communities, so that more users can learn the knowledge of blockchain through our platform。
We will maintain the project all the time, after that we will participate in the acceleration camp to seek more exposure and funding, and finally open the IDO of the project

# Team

## Team Members

- Yangyang  - full stack engineer
- SuTing - Senior Interaction Designer
- Ming - Senior front-end development engineer
- XWei - Contract development engineer

**Comment by ErinOCon** [comment]
Hi @web3Class, thank you for your proposal and for sharing your work! While this proposal isn't yet the right fit for our open grants program, we would be interested to learn of your progress!  

Please feel welcome to apply for a grant through our microgrant program (perhaps to support the development of a platform prototype).

**Comment by web3Class** [comment]
> Hi @web3Class, thank you for your proposal and for sharing your work! While this proposal isn't yet the right fit for our open grants program, we would be interested to learn of your progress!
> 
> Please feel welcome to apply for a grant through our microgrant program (perhaps to support the development of a platform prototype).

Hello! In fact, it is very suitable for Filecoin. Think about the future "decentralized classroom", where everyone can learn knowledge, and can also pay (pay in Fil) to get better content, and different users can use IPFS to complete peer-to-peer Online communication, such as discussion of study, submission of homework (IPFS), student communication after class, etc. These usage scenarios are very suitable for Filecoin, because there is currently no better alternative to Filecoin to accomplish all this. .

If you can, please reconsider this Open Grant, if not, we have also applied for a Micro Grant ! 

Thank you very much!
