### ISSUE TITLE
Key Management System SDKs 

### ISSUE THREAD

**Issue by martocrypto** [filecoin-project/devgrants#615]
# Open Grant Proposal: `Crypto APIs`

**Name of Project:** `Crypto APIs`

**Proposal Category:** `integration-adoption`

**Proposer:** `https://github.com/Crypto-APIs`

**(Optional) Technical Sponsor:** `None`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** `Yes`

# Project Description

There are two main issues we want to address. First, private keys and mnemonics remain the achilles heel of blockchain applications. If these get compromised at rest or in transfer, the financial damage to an app or a user is irreversible. Despite the rapid improvement of the technology used in our industry, the number and significance of the registered breaches remain very high. Private keys often need to be shared outside of the application, e.g. with technology providers such as Crypto APIs. Second, most secure wallets on the market often come with a considerable vendor lock-in. This makes the user dependent on the technology provider for years ahead and may incur significant costs in the long-term. 

We propose to build open-source KMS (Key Management System) SDKs for the Filecoin developer community. These open-source SDKs will allow users to create blockchain-agnostic HD Omnibus wallets, derive addresses, prepare and sign transactions, etc. The private keys, xPriv, etc. (key management) are generated and stored locally and not shared with anyone under any circumstances. Using it, developers can build enterprise-grade applications such as MetaMask with complete confidence over their customers' security and independence. There will be no vendor lock-in and users can use any infrastructure provider they want or run their own infrastructure.

## Value

The KMS SDKs will help developers build secure applications reducing the risk for a breach as much as possible. Their applications will also remain independent from technology providers. Moreover, the SDKs can easily be integrated to Crypto APIs existing product portfolio of developer tools. Crypto APIs is an infrastructure layer that significantly reduces our customers’ go-to-market time, development, and infrastructure costs. Of course, the user can switch to another blockchain tooling and infrastructure provider anytime. Since we have sigficant experience building custody solutions and developer tooling, we do not see any risk of failing to deliver that product to the Filecoin community. 

## Deliverables

The KMS SDKs will have the following functionality. The exact functionality is to be set after thorough analysis of Filecoin's technical specifics. 
- Generate Filecoin wallet (xPub)
- Store mnemonic-based Filecoin wallet
- Store private key of Filecoin wallet
- Obtain wallet and private key 
- Remove managed wallet
- Derive wallet 
- Prepare a transaction
- Sign a transaction
- Broadcast a transaction

## Development Roadmap

We plan on building this product in one milestone. The grant payment can be divided into 25% before the project start and 75% after the successful delivery of the products. 

1. Development costs

Deploying Filecoin mainnet and testnet nodes will be done by a DevOps lead is planned to take around 10 workdays.
Research of the blockchain's specifics will be conducted by a senior blockchain developer and will take 3 workdays. Setting up and managing the development plan will take our project manager 2 days. Developing the Filecoin KMS SDKs will be done by two blockchain developers and will take 30 workdays in total. Product Management by the Product Owner will take 3 workdays of effective work. Mapping/Creating Public Endpoints will be done by one blockchain developer and it will take 7 workdays. For the Code Review a senior blockchain developer is responsible and it will be due in 3 workdays. Finally, a QA Lead will work on the QA Testing for 7 days. Bug fixing will be carried out by one developer and we plan with 12 workdays for it, to be on the safe side. Updating the documentation and the website will take 6 workdays of two of our developers. Preparing the marketing materials will take our CMO 1 workday. 

This makes 84 workdays in total. We prefer to add 10 more workdays as a buffer for any unexpected difficulties in the product development, coming at 94 workdays. If we start on 1st August 2022 we expect to be ready by 30th September 2022. 

These 94 workdays cost us $300 per workday on average, which makes $28,200 development costs.

The software functionality that will be delivered was outlined in the previous section. 

2) Infrastructure costs

We will run mainnet and testnet Filecoin nodes while developing the products. To cover these costs we will need additional $3,000.

## Total Budget Requested

Requested budget for development is $28,200.
Requested budget for infrastructure is $3,000.
Total Budget Requested is $31,200.

## Maintenance and Upgrade Plans

We were founded in 2018. We have built one of the most comprehensive blockchain tooling portfolio with the following products: Wallet as a Service (MPC-based), Blockchain Data (unified APIs), Node as a Service (Dedicated), Blockchain Events (Webhooks), Blockchain Tools, Blockexplorer.One, open-source KMS SDKs, and others. We have already integrated 14 protocols into these products. Crypto APIs has more than 170 endpoints, 40 team members, and 15K+ community members (registrations). The company has over 30 networks running at lightning-fast speed with a 25 ms average execution time.

We are a stable company that wants to be one of the leading technology providers in the blockchain industry. We will maintain this product for at least 3 years after it is built.

# Team

## Team Members

•	Nashwan Khatib, CEO.
•	Ognyan Marinov, CTO.
•	Kristiyan Lozanov, COO.
•	Malin Ivanov, Chief of Engineers.
•	Radoslav Mitov, DevOps Lead.
•	Silviya Sotirova, Chief Marketing Officer.
•	Beduil Dauis, Chief Business Development Officer.

## Team Member LinkedIn Profiles

The company has 40 employees, 25 of which are software and DevOps engineers. You can find a list of the employees here: https://www.linkedin.com/company/cryptoapis/people/

## Team Website

https://cryptoapis.io/

## Relevant Experience

The CEO, CTO and Chief of Engineers have been with the team since the very start in 2018. They have successfully managed the development of all company's products and the integration of 14 blockchains into the product suite. 

## Team code repositories

https://github.com/Crypto-APIs

# Additional Information
 We searched for it on the Internet.
 martin.hrisoskulov@cryptoapis.io & nashwan.khatib@cryptoapis.io
 It would be best to schedule a call with the team and the CEO.

**Comment by ErinOCon** [comment]
Hi @martocrypto, thank you for your proposal! Your grant has been approved. To proceed with next steps, please email grants@filecoin.org.
