### ISSUE TITLE
Next Step Microgrant: m-tribe

### ISSUE THREAD

**Issue by Shubham0850** [filecoin-project/devgrants#616]
### 1. What is your project? (max 100 words)
A dashboard providing DAO tools and standards to empower the existing NFT Communities to transform into fully functioning DAOs
Github repo
https://github.com/Shubham0850/m-tribe
Demo
https://youtu.be/-L0prxXQjfU

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
The proposal details and the number of votes are stored on IPFS to ensure immutability and trust among the NFT community.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Currently, the project has only basic functionalities like listing users' NFT communities and a proposal dashboard for the user. We are planning to add more features for engaging the DAO community members, which include community meetings and NFT staking casino style games. We are in talks with a backend developer and a game developer to add our team to develop and ship the project.

### 4. Is this project open source?
Yes, all of the work is Open Source under MIT license.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* ETHGlobal DAOHacks(IPFS Pool Prize Winner) - https://showcase.ethglobal.com/daohacks/m-tribe-ncufj
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
    Shubham Raj
    Email - [rajshubham0850@gmail.com](mailto:rajshubham0850@gmail.com)
    Github - Shubham0850
    Role - Full Stack Developer 

    Shashank
    Email - [jagannathamshashank@gmail.com](jagannathamshashank@gmail.com)
    Github - shashanka2a
    Role - Smart Contract Developer

* How did you learn about our microgrant program?
    Friend
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) 
     ETHGlobal DAOHacks
  * Please link to your hackathon submission  
     https://showcase.ethglobal.com/daohacks/m-tribe-ncufj

**Comment by ErinOCon** [comment]
Hi @Shubham0850, this microgrant has been approved! Please look out for an email to submit payment details.

**Comment by Shubham0850** [comment]
Hi @ErinOCon, how long it will take to get the email?

**Comment by ErinOCon** [comment]
Hi @Shubham0850, thanks for checking in! An email with next steps was sent out just moments ago! Please let me know if you experience any trouble receiving the email.

**Comment by ErinOCon** [comment]
Hi @Shubham0850, I hope you are doing well! Can you provide your final report [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let me know if you have any questions!

**Comment by Shubham0850** [comment]
Hi ErinOCon,

Sorry for the late reply. Actually, I was busy building some great
projects. I've filed the form that you've shared with me.

Best,
Shubham Raj

**Comment by ErinOCon** [comment]
Thanks, @Shubham0850! We have received your report. Can you identify the code that was used during the time of the microgrant? I haven't uncovered it in the original [repo](https://github.com/Shubham0850/m-tribe) provided.

**Comment by Shubham0850** [comment]
Hi ErinOCon,

As I answered in the form. Our main goal was to build some utility for our
m-tribe project. But because we were working on it only part-time then we
only able to develop Yolo-Club
https://github.com/Crusader-Labs/yolo-club/tree/alpha

so you'll not find any commits on that repo. please check the above
Yolo-Club repo.

Thanks,
Shubham Raj
