### ISSUE TITLE
Web3Course

### ISSUE THREAD

**Issue by web3Class** [filecoin-project/devgrants#617]
### 1. What is your project? (max 100 words)
Web3Course is a comprehensive online learning platform launched for web3. It aggregates a large number of high-quality course content. It has excellent courses on blockchain, web3, nft, solidity, fvm and major chains. It helps the vast number of web2 users to improve their skills and knowledge to enter the web3 time .

Web3Course will rely on the storage of Filecoin, and use the decentralized storage method to store all course materials permanently and free of charge. We will use Web3.Storage to store the uploaded data of all users, and will also record the the video's info of courses based on smart contracts. When the video is watched by the user, the uploader can get a certain token income.

After the project is completed, the funds will be used to invite high-quality blockchain content providers to participate in the construction of the platform content and establish the first batch of high-quality blockchain course content.

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
 Data such as all courses of our learning platform will be stored and made available to all users via web3.storage . 
Filecoin-based storage can permanently allow users to learn more blockchain knowledge through the platform. Of course, the first must be about Filecoin

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will use this funding as start-up capital for the project and after completing the prototype demo will apply for other grants to continue with our final project
 
### 4. Is this project open source?
Yes, It will be open !

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes
### 7. Links and submissions
N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Yangyang - full stack engineer
SuTing - Senior Interaction Designer
Ming - Senior front-end development engineer
XWei - Contract development engineer

* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ZhangPeibin** [comment]
Hello! @ErinOCon ! Sorry for the misunderstanding, I misunderstood the meaning of 6. Number 6 is YES, this project is in compliance with the Community Code of Conduct

**Comment by web3Class** [comment]
Hello @ErinOCon ! Sorry for the misunderstanding, I misunderstood the meaning of 6, and the answer is YES, this project is in compliance with the Community Code of Conduct , and I already change it !

**Comment by ZhangPeibin** [comment]
> Hello @ErinOCon ! Sorry for the misunderstanding, I misunderstood the meaning of 6, and the answer is YES, this project is in compliance with the Community Code of Conduct , and I already change it !

There are many reasons why online learning and education will be the future, including Covid-19, so we have an idea and plan to make it happen! We are very much looking forward to the sponsorship and support of Filecoin

**Comment by ErinOCon** [comment]
Hi @web3Class, thank you for the update! This microgrant has been approved! Can you provide a preferred email address for submitting payment information?

**Comment by web3Class** [comment]
> Hi @web3Class, thank you for the update! This microgrant has been approved! Can you provide a preferred email address for submitting payment information?

Hi! Thank you very much! here is my email:  web3Class@163.com.

**Comment by web3Class** [comment]
> > Hi @web3Class, thank you for the update! This microgrant has been approved! Can you provide a preferred email address for submitting payment information?
> 
> Hi! @ErinOCon Thank you very much! here is my email: [web3Class@163.com](mailto:web3Class@163.com)

Hi @ErinOCon Is this email ok?

**Comment by ErinOCon** [comment]
Hi @web3Class, next step details have been sent to the provided address. If there is any trouble receiving this email, please let me know.
