### ISSUE TITLE
Next Step Microgrant: Solido Games

### ISSUE THREAD

**Issue by maksim-solido** [filecoin-project/devgrants#620]
### 1. What is your project? (max 100 words)
Solido Games – Decentralized P2E and Metaverse Ecosystem
Combining technologies of the metaverse, blockchain ledgers, and decentralized networks into a unified platform with an intuitive user interface, Solido Games represents the state-of-the art in gaming today bringing players, developers, and NFT traders together in one interactive ecosphere. Solido Games platform includes three important elements (i) a P2E Game Aggregator, (ii) a MVP Launchpad, and (iii) an NFT marketplace. Specifically, Solido’s P2E Aggregator provides players convenient access to a wide selection of online and play-to-earn (P2E) games hosted across multiple blockchain networks. In the P2E Aggregator, players are able to sort and select games by cost, genre, devices, blockchain, NFT and crypto support, popularity, ratings, and by special offers. In its MVP Launchpad, game makers are able to fund, develop, and launch new games in the Solido ecosphere, and promote their releases to gamers through special offers and token incentives, thereby bridging the gap between players and developers. Another unique innovation of Solido is its Metaverse Market, a market for swapping or procuring NFTs or exchanging for crypto (SLG token). 

[https://solido.games](https://solido.games/about) 

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

We often get new games that don't know which blockchain to run on, and here we can push them towards you. We can also show projects on your blockchain in priority, which will give more attention to the development of your ecosystem 

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We are looking for seed round for hire more blockchain developers.
 
### 4. Is this project open source?
No

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes 
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions:

Video: https://youtu.be/a3tWC8Ogm5Y
   Website: https://solido.games/about
   One Pager: https://app.solido.games/files/solido.games_onepager.pdf
   Whitepaper: https://app.solido.games/files/solido.games_whitepaper_v18.pdf
   Gitbook: https://litepaper.solido.games
   Pitch Deck: https://app.solido.games/files/solido.games_pitch.pdf
   Tokenomics - https://docs.google.com/spreadsheets/d/1xxaD9Zuk6PjpeHW82rq_VsqETVDm3WcQbJiTk9eLEAM/edit#gid=1785940346 

  
### Additional questions:

Team:

Anton CEO - https://www.linkedin.com/in/anton-kanavalau/
Extensive experience in creating Game Aggregators and marketplaces. Ex CEO at Cointelegraph store.

Evgeniy CTO - https://www.linkedin.com/in/evgeniy-mil/
Solid experience in creating CRM systems, marketplaces, game aggregators. High performance.

Isom CBDO 
Professional gamer. Web3 investor. Founder in Decorative smart system Diodey. 

Axinia CMO - https://www.linkedin.com/in/kseniashliakhtina/
Ex CMO Cointelegraph store. Experienced Digital Marketer.

Phillip Adviser - https://www.linkedin.com/in/philip-devine-a86b8538/
CEO Riveted Games, CryptoBlades, the world’s largest game marketplace.

Kevin Strategic Adviser - https://www.linkedin.com/in/Kevinabdulrahman
Strategist to Gaming, NFT & Metaverse projects. Public speaking coach to CEOs and world leaders. 

Sergio CFO 
Financial genius, Excel’s best friend. Ex-finance director with expensive experience.

Natali Designer
UI/UX professional. Winner of international design awards.

Petr SEO Director
Expert in SEO, 3D design. Gamer. Very proactive and creative.

**Comment by ErinOCon** [comment]
Hi @maksim-solido, thank you for your proposal. Open source work is a key criteria point in our microgrant program. Would your team be willing to make this an open source project?

**Comment by maksim-solido** [comment]
Hello, Filecoin team! Yes, we will have an open source. And also with an
mit license

вт, 14 июня 2022 г. в 15:23, ErinOCon ***@***.***>:

**Comment by ErinOCon** [comment]
Hi @maksim-solido, are you still interested in proceeding with this review? Please let me know if you have any questions.

**Comment by ErinOCon** [comment]
Hi @maksim-solido, can you update the proposal to reflect that the grant work will be open source? Also, do you have a repo link with the current code for this project?

**Comment by ErinOCon** [comment]
Hi @maksim-solido, do you expect to have an update available soon?

**Comment by ErinOCon** [comment]
Hi @maksim-solido, this Issue Item has been closed. Please feel welcome to re-apply when a github link can be provided to reflect your building progress.
