### ISSUE TITLE
Next Step Microgrant: MINI UTOPIA

### ISSUE THREAD

**Issue by faithful1ofall** [filecoin-project/devgrants#621]
### 1. What is your project? (max 100 words)
This program help users bother newbies to access the NFT market with less risk because we will build an insurance mechanism to make sure NFTs has a consistent value at every point in time so as not losing its own buy ack value we intend to build a marketplace where NFTs will not have decreasing value instead will have increasing value.

[](https://github.com/faithful1ofall/mnft)
[](https://miniutopia.co/)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
we will use the ipfs system for nft files(images, Audios, etc.) fetching and uploading we also intend to implement the filecoin network as an expandable point as we progress towards the multichain.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
we will expand our test phase to a complete startup by hiring 2 to 3 developers and 2 to 3 marketing experts  and proceed to futher integrations in less than 2 to 3 months 
 
### 4. Is this project open source?
we will work open sourced with MIT License. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes updates will be given on a weekly basis with completion of the development promptly reported.   
### 6. Does your proposal comply with our Community Code of Conduct?
yes it does

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* yes it began at the hackmoney 2022 hackathon and here is the link to my submission
* https://showcase.ethglobal.com/hackmoney2022/mini-utopia-t6n06
* 
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
team memeber: Faithfulness Obasi email: faithful1ofall@gmail.com

* How did you learn about our microgrant program?
from the hackmoney 2022 hackathon

* If your project was created as part of an event or hackathon:
  * What was the name of the event? ETHGlobal- hackmoney 2022
 
 * Please link to your hackathon submission
here is the link to my submission
https://showcase.ethglobal.com/hackmoney2022/mini-utopia-t6n06

**Comment by ErinOCon** [comment]
Hi @faithful1ofall, please note your final grant report is due September 27th. and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by faithful1ofall** [comment]
Sure we have built our API and backend with some community member's upto 6000+ on Twitter and telegram 1k+ we are still looking to deploy the upgrade it will involve creating of profiles and collections we will need marketing support as well as more funding

**Comment by faithful1ofall** [comment]
I have submitted the feed back thanks.
