### ISSUE TITLE
Next Step Microgrant: discord NFT minter

### ISSUE THREAD

**Issue by NftTopBest** [filecoin-project/devgrants#622]
### 1. What is your project? (max 100 words)
It's a discord NFT minter, that discord Guild owner can setup it to mint new NFT through the Channel

https://github.com/ntb-hackthon/mars-asia-hackathon-2021
https://github.com/ntb-hackthon/mars-asia-hackathon-2021/blob/main/demo-2.mov

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
1. It uses the Pinata service to upload files to IPFS.
2. It uses the discord's `splash` command feature so that user can submit their pinata private key in the discord channel without public.
3. user can use `~upload [fileName]` to upload a file to IPFS

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. Make it with more detailed use instructions in the project README.
2. Make all code open source with an MIT license
3. Write a blog to explain how the whole code works
4. Add deploy instructions for heroku.com

### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?
Yes

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Yes.
Received Track 2 Best Use of Filecoin/IPFS or any technology building on top of nft.storage, web3.storage, estuary, etc.
Winning Team # 1 – NTB

https://angelhack.com/blog/announcing-mercury-hackathon2021-winners-%f0%9f%8e%89.html/

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Bruce
Email: nfttop.best@gmail.com
Github: [@NFTTOPBEST](https://github.com/NftTopBest)
Role: Main Developer

* How did you learn about our microgrant program?
From the email that from IPFS member to tell me what I can do for Next Step after get the Hackathon Prize.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
[MercuryHackathon2021 ](https://angelhack.com/blog/announcing-mercury-hackathon2021-winners-%f0%9f%8e%89.html/)
  * Please link to your hackathon submission
https://virtual.hackathon.io/view-projects/2978
Prize Announcing: https://angelhack.com/blog/announcing-mercury-hackathon2021-winners-%f0%9f%8e%89.html/ (Track 2
NTB team)

**Comment by NftTopBest** [comment]
Hi @ErinOCon 
   Is that I need to finish the task list and then come here to apply? It's not a to-do list but a done list?

**Comment by ErinOCon** [comment]
Hi @NftTopBest, thank you for your proposal. This microgrant has been approved! Look out for an email to submit payment details.

**Comment by ErinOCon** [comment]
Hi @NftTopBest, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @NftTopBest, can the report be provided by next week?

**Comment by NftTopBest** [comment]
> Hi @NftTopBest, can the report be provided by next week?

oh, I am afraid I still need more time, will be about two weeks. Will report before 2022-11-21.

**Comment by NftTopBest** [comment]
> 

Hi @ErinOCon , I just submit the final report via the google link. pls check. thx !

**Comment by NftTopBest** [comment]
Hi @ErinOCon I already submit the form.
