### ISSUE TITLE
Open Grant Proposal: Filecoin Grants Dashboard

### ISSUE THREAD

**Issue by mrudulgole** [filecoin-project/devgrants#623]
# Open Grant Proposal: `Filecoin Grants Dashboard`

**Name of Project:**
Filecoin Grants Dashboard

**Proposal Category:** `app-dev`

**Proposer:** `mrudulgole`

**(Optional) Technical Sponsor:** NA

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

We propose building a Grants Dashboard for the Filecoin Ecosystem where it becomes easy for a user to ask for a new grant, check the status of their previous grants, and a place to find a list of all the grants that have been applied on Filecoin. We also plan to build an admin portal for the grants committee to manage, review and comment on grant applications.  

We feel the current grant application process for Filecoin is a little outdated. It should not be necessary for an average person to know about Markdown and understand different elements of Github like Issues, Commits and PRs. We feel it should be very easy for users with great ideas to apply for grants and help with the growth of the Filecoin ecosystem.

We plan to create a user-friendly dashboard for the Filecoin community, which will turn down the complexities of the present system with a minimal user interface for all community members to apply for new grants and track the status of their already applied grants. It will also bring in a lot of transparency around the whole grants process, identify the number of grants applied by different users, and be extremely helpful for the Filecoin grant moderators to evaluate grants at various stages. Like new, under review, denied and other, and take necessary action from the grant dashboard.

It will also allow community members and grant moderators to analyze the most active members applying for grants and make the whole process easier to use.

## Value

The main goals of building a grants dashboard for Filecoin are as follows:
1. Increase the speed with which grants are reviewed, making it easier for users and grant moderators to add comments, questions, and change requests to any grant submission.
2. Reduce friction between applicants and the grants team.
3. Bringing transparency to the whole grants review process.
4. And most importantly, providing an easy-to-use UI interface for users to apply and committees to review grants.

What are the risks if we don't get it right?
The community may not like the grants dashboard as it may require community members to get accustomed to the new UI. But since we are planning to keep the whole UI very simple and intuitive, we feel the chances of failing are pretty low, as our main goal is to simplify the entire process and not complicate it. We also plan to have a feedback section that would help us improve the dashboard as the product gets launched.

What are the risks that will make executing on this project difficult?
Currently, we see that Filecoin receives the most grant applications and proposals compared to other blockchains. So, to scale, we will have to make many design considerations. We are currently planning to deploy the grant dashboard on Fleek. But, we also plan to keep AWS as a backup option if the dashboard doesn't work up to speed and starts facing downtime.

## Deliverables

The grants dashboard design and development is divided into 2 milestones, and the main deliverables for these milestones are the UI/UX design, Dashboard source code, and Testing report.

The section below provides a detailed description of the associated deliverables.

**UI/UX Design**

1.  Information architecture (PDF)
2.  High fidelity wireframe (Invision prototype)
3.  High fidelity visual design (Source files)
4.  Click through prototype of visual designs (Invision prototype)

**Development**

1. High-level architecture diagram (PDF)
2.  Database schema (PDF)
3.  API Documentation
4.  Commented source code of backend and frontend
    1.  Dashboard source code
    2.  Admin portal source code
    3.  Backend source code

**Testing**

1.  Manual Test Report (Spreadsheet)

Post the launch of the product following are the activities that can be carried out:

**Users (Grants Dashboard):**

1.  Apply for new grants.
2.  View their applied applications.
3.  Check the status of their applied applications.
4.  View all other applications and their status.
5.  Know more about the Grant Program details and sample applications.
6.  Ability to like, bookmark and comment on different applications.
7.  Receive feedback from the grant moderators on their applications.
8.  and others.

**Admin Panel (Grant Moderator Dashboard)**

1.  Review application
2.  Mark application as Under review, Accepted, Rejected and other
3.  Access the database of all the grant applicants and their application details
4.  Send change request/feedback to the applicant
5.  View feedback received for platform degradation
6.  Basic analytics
7.  Add new moderators to the platform
8.  and others.

## Development Roadmap

**Milestone 1**

Design activity and collection of Data:

-   Completing the Wireframe, and Mockups of the Website Interface.
-   Conduct a discovery workshop and get feedback from the community on the Ideal Grants Dashboard
-   Research similar applications, their usage and design patterns
-   Build an information architecture
-   Design high fidelity wireframes
-   Create a clickable prototype for visual design
-   Collecting previous grant application data from Github.
-   Collect data on the Live Issues and already closed ones.
-   Sorting the different categories of issues present, such as Accepted, Rejected, Open Grant, Micro Grants, etc in the database.

Members:

-   Manoj Mohan - Sr. UI/UX Design Lead
-   Srinidhi M C - Sr. Backend Lead
-   Bharat Kumar - QA Engineer

Start date: 13th of June, 2022
Completion by: 11th of July, 2022
The total duration of the milestone: 4 weeks
Budget: $21,000

**Milestone 2**

Complete Grant Dashboard (Integrating the Frontend, Backend and the Admin Panel)

Frontend:

-   User Login
-   Ability to create a new grant application using a very minimal form than a Doc in Markdown.
-   Ability to see the status of the grants applied.
-   Ability to see the applications sent by other users.
-   Search through the list of all grants depending on their category.
-   Deploying the Frontend both on HTTP and IPFS using Fleek and Cloudflare IPFS.

Admin Dashboard:

-   Allowing admin to keep track of the grants assigned to them in a single place.
-   Tracking of applications on the basis of accepted, rejected and others.
-   Grant applicant data management.
-   Share feedback with the applicant and request for changes

Backend:

-   Using Textile Buckets / IPFS as a database to store the Grant Proposals.
-   Run tests to check for scalability issues and take according action on whether to host on Centralized Cloud Providers such as AWS, GCP.

General activities:

-   Create development environment
-   Create a high and low-level architecture of the application
-   Develop backend server APIs
-   Develop frontend user interface(s)
-   Manually test the application
-   Build, test and deploy intermediate versions of the application
-   Build, test and deploy the final release candidate.
-   Share documentation and testing guide

Members:

-   Srinidhi M C - Sr. Backend Lead
-   Roshit Omanakuttan - Sr. Frontend Lead, Product Lead
-   Swapnil Sagar - Jr. Frontend Dev
-   Bharat Kumar - QA Engineer

Start date: 12th of July, 2022
Completion by: 8th of August, 2022
The total duration of the milestone: 4 weeks
Budget: $29,000

## Total Budget Requested

We're requesting a total funding of $50,000 to complete all the above milestones, and the fund will be split for:

- UI/UX & Discovery
- Development & Testing

| Milestone | Duration | Cost |
| --- | --- | --- |
| 1 | 4 weeks | $21,000 |
| 2 | 4 weeks | $29,000 |
| Total | 8 weeks | $50,000 |

> Note: This does not include any infrastructure cost.

## Maintenance and Upgrade Plans

As it going to be an open source project, we are committed to maintaining the project for at least 12 weeks by performing bug fixes based on community feedback. A separate upgrades list can also be created to perform major feature up-gradation to the dashboard after or during the 12 week period as and when required.

# Team
## Contact

-   Contact Name: Mrudul Gole
-   Contact Email: mrudul.gole@wowlabz.com

## Team Members

- Manoj Mohan - Sr. UI/UX Design Lead  
- Srinidhi M C - Sr. Backend Lead
- Roshit Omanakuttan - Sr. Frontend Lead, Product Lead
- Swapnil Sagar - Jr. Frontend Dev
- Bharat Kumar - QA Engineer

## Team Member LinkedIn Profiles

Profiles of the people working on Radicle Discovery + Analytics

- Manoj Mohan - https://www.linkedin.com/in/manoj-mohan-13264b35/
- Srinidhi M C - https://www.linkedin.com/in/srinidhi22/
- Roshit Omanakuttan - https://www.linkedin.com/in/roshit/
- Swapnil Sagar - https://www.linkedin.com/in/swapnilsagar09/
- Bharat Kumar - https://www.linkedin.com/in/bharath-kumar-h-13a572126/

## Team Website

https://www.wowlabz.com/

## Relevant Experience

Filecoin Grants Dashboard will be built at Wow Labz. Wow Labz is one of India's leading turnkey product development firms. The team has previously built a decentralized storage protocol called Lake Network - [https://lakenetwork.io/](https://lakenetwork.io/) in addition to multiple dApps on Ethereum, Stellar, EOS, and Hyperledger.

A list of centralized apps published can be found [here](https://www.wowlabz.com/work/) which includes products involving analytics dashboards for Fortune 500 companies.

In addition to this, the team has also won grants from Web3 Foundation and Polkadot for building a decentralized marketplace linked [here](https://github.com/WowLabz/tasking_backend/blob/main/README.md).

Nearly 80% of the 100+ (centralized) products built by us have an Admin Portal with a dashboard, aggregate analytics and activity details for the Admins to get a bird’s eye view of the activities in the overall system. We have also built a few analytics products that provide drill down features on aggregate analytics.

## Team code repositories

- https://github.com/orgs/WowLabz/projects
- https://github.com/WowLabz/tasking_backend
- https://github.com/WowLabz/tasking_frontend
# Additional Information
### Mockups
![01](https://user-images.githubusercontent.com/52949018/172249651-de96325c-0668-4ad2-b4b1-fbfd5a4867e1.png)
![02](https://user-images.githubusercontent.com/52949018/172249835-2e3e9f78-8b76-4ac6-a2cf-3a9856d9e52c.png)

**Comment by mrudulgole** [comment]
Hello @realChainLife 

Hope you are doing well!

I just want to know if you have any updates for us on the shared proposal?
Would love to know what would be the next steps and how can we move forward?

Regards,
Mrudul

**Comment by ErinOCon** [comment]
Hi @mrudulgole, thank you for this proposal! We will be sure to keep this project in mind as we continue to build our grant program. In the meantime, I would recommend checking project opportunities at [radius](https://app.radius.space/)!

**Comment by mrudulgole** [comment]
Hey @ErinOCon @realChainLife 

Could you please update on what would be the next steps?
Is the proposal still under consideration or is it rejected?

Regards,
Mrudul
