### ISSUE TITLE
Next Step Microgrant: Burst My Bubble

### ISSUE THREAD

**Issue by Ciudadana** [filecoin-project/devgrants#624]
### 1. What is your project?

We are building Burst My Bubble, a Chrome extension that, when activated, analyses the twitter profiles that the user is following to determine their ideological bias (in a left-right axis) and then recommends to the user profiles that have different views to those that the user is mostly following, in an attempt to be more conscious of one’s biases and nudge the users in a way that let’s them escape their echo chamber. 

**Link to public Github repo**

https://github.com/Ciudadana/burstmybubble
 
**Link to website**

https://ciudadana.city/ (our agency’s site, we are currently building out the brand identity and website for Burst My Bubble). 

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

The code gets the tweets from Twitter API and uploads them to IPFS in order to have a public and decentralized record of the tweets used to train the model, and makes sure we can always access them if Twitter changes its API policy or the tweets get deleted, providing more transparency and robustness to the product. 
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The tech stack consists of three fundamental aspects: 

1) Twitter API connection. 

2) IPFS: the code gets the tweets from Twitter API and uploads them to IPFS in order to have a public and decentralized record of the tweets used to train the model, and makes sure we can always access them if Twitter changes its API policy or the tweets get deleted. 

3) NLP model that identifies political bias in tweets. 

We have already trained a beta version of our NLP model, achieving over 80% accuracy, and are seeking the grant to develop the IPFS integration and finalize the Twitter API work. We estimate it will take about 8-10 weeks to have the MVP completed. 
 
### 4. Is this project open source?

Yes. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### Team members

Julián Kanarek is the partner and director of Ciudadana, a company specialized in citizen, political and governmental communication.

He has Master in Communication and Culture and Bachelor in Social Communication from the Catholic University of Uruguay, he has worked in many areas of communication such as journalism, advertising, marketing, institutional communication and film.
In 2018 he was awarded as Political Consultant Revelation and in 2019 Digital Consultant of the Year by The Napolitan Victory Awards. He is a guest lecturer at at George Washington University.

Gmail: julian@ciudadana.city
LinkedIn: https://www.linkedin.com/in/juli%C3%A1n-kanarek-garibaldi-5814821b/

Matilde Mila holds a degree in International Relations from UDELAR. She also holds a Master's degree in International Business Administration (MBA) and a diploma in gender and public policies.

She has previously worked in private consulting services:

2018- Present Consultant at Wellness Techgroup in the technology and smart cities sector.

2016-2017- Data analyst Willis Towers Watson.

Gmail: matilde@ciudadana.city
LinkedIn: https://www.linkedin.com/in/matilde-mila-883b37a5/

Álvaro Yañez is a graphic design technician from ORT Uruguay University.  After graduating from ORT, he worked in different advertising agencies (Teorema, Notable, Escenario, Ímpetu, among others). He was the art director for clients such as Conaprole, Claro, MVOTMA, Médica Uruguaya, etc.

In the last 8 years he has directed the design department of the multimedia production company Trailer Media. 

Gmail: alvaro@amen.com.uy
LinkedIn: https://www.linkedin.com/in/%C3%A1lvaro-y%C3%A1%C3%B1ez-6a11381b/

Martin Brian is a software developer, currently in charge of AR Platforms at the retailer Ulta Beauty, partner in BroLi, and freelance dev. 

Role: Freelance Developer
LinkedIn: https://www.linkedin.com/in/martinbrianmdbn/
Github - mbrian23
Gmail: martin@broli.com.uy

**Comment by ErinOCon** [comment]
Hi @Ciudadana, thank you for your proposal! Can you confirm the steps you will take for the IPFS integration?

**Comment by Ciudadana** [comment]
@ErinOCon let us know if you need any more info :)

**Comment by Ciudadana** [comment]
Hey @ErinOCon, any news? We are happy to elaborate on any aspect of the project!

**Comment by ErinOCon** [comment]
Hi @Ciudadana, thank you for your patience with our review. Unfortunately, we will not be moving forward with this grant. While this project is using IPFS for storage purposes, dev grants are intended to support work that is more focused on building with IPFS, Filecoin, and related tech. Wishing you all the best with this project!
