### ISSUE TITLE
DeSecretSpace 

### ISSUE THREAD

**Issue by DeSecrtSpace** [filecoin-project/devgrants#626]
### 1. What is your project? (max 100 words)
DeSecretSpace is a decentralized secret storage space built on Filecoin, and all data will be stored in Filecoin through web3.storage after encryption. The user uses the web3 wallet to log in to the DeSecertSpace , and uses the encryption method provided by textile to encrypt all data. The encrypted public and private keys are obtained through the web3 wallet, and all are completed in the front end.

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
  
We will use the encryption and decryption methods provided by Textile.io, the storage provider of Filecoin, and use web3.storage to store all user data. In short, this project is a private encrypted network disk based on Filecoin/IPFS.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will use grants to support developers to complete this project. After completing the project, we will invite people to test in the IPFS community, and plan to apply for the next grant for project development and marketing activities, etc.
 
### 4. Is this project open source?
yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
N/A  
### Additional questions:
* Team 

1.  anthony  , Product design, full stack development , yangziLiu728@outlook.com

* How did you learn about our microgrant program?
  We learn from IPFS Group!
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @DeSecrtSpace, thank you for submitting this proposal. Do you have a repo link with code for this project? Please provide links to any evidence of your building progress.

**Comment by ErinOCon** [comment]
Hi @DeSecrtSpace, thank you for the additional information! Do you have a link to your project's code?

**Comment by DeSecrtSpace** [comment]
> Hi @DeSecrtSpace, thank you for the additional information! Do you have a link to your project's code?

Hi @ErinOCon ! here is our project github link：  https://github.com/DeSecrtSpace/desecretspace_web ,We are now on schedule to start coding!

**Comment by ErinOCon** [comment]
Hi @DeSecrtSpace, this microgrant has been approved! Look out for an email to submit payment details.

**Comment by DeSecrtSpace** [comment]
> Hi @DeSecrtSpace, this microgrant has been approved! Look out for an email to submit payment details.

Hi @ErinOCon , Thank you very much!
