### ISSUE TITLE
Next Step Microgrant: PRISM - composability engine for the metaverse

### ISSUE THREAD

**Issue by malte18** [filecoin-project/devgrants#627]
### 1. What is your project? (max 100 words)

PRISM is a composability engine for metaverse identities, art and digital creations. Creators can collaboratively create projects, upload trait layers and mint these as non-fungible as well as semi-fungible tokens. Owners can dynamically update their NFT composition through the PRISM composability engine. PRISM enables infinite creative and collaborative expandability for digital creations and collections powered by NFTs. We can give you access to our beta project on PRISM to experience composability first hand.

https://github.com/metaxu-art/prism-contracts
https://github.com/metaxu-art/prism-backend
https://github.com/metaxu-art/prism-frontend

We have an internal project, with which we test composability engine from NFT owner perspective: (send us your wallet address so we can WL you and airdrop trait and master NFTs.)
https://cyberfrens-beta.co/

Interface for creators to publish projects: 
Prototype will be finished this week, will do a screen recording, upload to YT and forward as reference.
https://mtx-labs-prism.netlify.app/ (updated version coming 15th June)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
In the current prototype, IPFS is used to store the image of each trait as well as the dynamically computed image composition of the master NFT. The longterm vision is expand NFT mutability on a data and visual level into all realms of the metaverse (different visual standards, integration with game engines etc.) . We choose IPFS to do that as decentralised as possible and guarantee the existence of creations and compositions beyond the lifespan of any service. 
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Precise steps we intent to take with the Microgrant: 
- implement NFT.storage to store the image and composition
    - improvement: guaranteed permanence through copies uploaded to IPFS network
Further steps,(hopefully) enabled through open grant: 
- move part of the metadata that is currently stored on-chain to IPFS through NFT.storage
    - improvements:
        - only store necessary data on-chain
        - eliminate need for centralised db
        - enable mutable NFTs, fully decentralised
- integrate with more creator engines (i.e. Blender) and file standards 
    - composability for more sophisticated file standards, 3D rendering 
 
### 4. Is this project open source?

Yes, APACHE2

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* @malte18 (Product, Growth)
* @elliottbrunet (Architecture, Product)
* @Cl2pp (Smart Contract Development)
* @gio-shara-code (Full Stack Dev)
* How did you learn about our microgrant program?
I met Lukas from Protocol Labs at the NFT Berlin conference. 

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
ETHGlobal Buildquest 
  * Please link to your hackathon submission
https://showcase.ethglobal.com/buildquest/prism-53jx5

**Comment by ErinOCon** [comment]
Hi @malte18, This microgrant has been approved! Can you provide an email address to confirm payment details?

**Comment by malte18** [comment]
That's great news, thanks @ErinOCon !! email: malte@mtx.studio

**Comment by ErinOCon** [comment]
Thanks, @malte18!
