### ISSUE TITLE
RFP Proposal: Filhak - FVM Development Environment

### ISSUE THREAD

**Issue by kapetan3sid** [filecoin-project/devgrants#628]
# RFP Proposal: Filhak - FVM Development Environment

**Name of Project:** Filhak 

**Proposal Category:** `devtools-libraries`

**Proposer:** `@thedivic`

Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, GPL, and APACHE2 licenses?: `Yes`

### Filhak 
(`>$ filhak)` is (*supposed to be*) a filecoin development environment heavily influenced by [Hardhat](https://hardhat.org/).

For MVP Filhak will allow FVM developers to:

- Easily launch a (stripped-down) local devnet Filecoin node (+FVM), with no setup required
- Use one or more **Go** packages that implement helper functions used in scripting **tasks** that are common to actor development (deploying and calling actors, creating & funding accounts, working with deals and the retrieval market etc)
- Use the task runner (similar to Hardhat Runner) that is used to run your Go tasks

### Motivation

After our research of the existing **EVM** tooling we realized how extensive and well rounded SDKs, libraries and plugins are. Even though there are some more "advanced" environments based on **WASM**, it was quite obvious to us why **EVM** is currently most utilized in blockchain and why it is so easy to build on it. 

Above all other **EVM** tools stand:

**Hardhat** - A one stop sandbox where developers are able to compile, deploy, test, and debug EVM smart contracts. 

We believe that sandbox similar to **Hardhat** would be highly valuable for developers that want to explore **FVM** and would greatly ease the building process.

### Filhak init

`>$ filhak init [path]`

Initializes a filhak project in the given directory.

Creates a `filhak.toml` configuration file, sets up the default file and directory structure, fetches **Go** modules etc.

### Filhak network

`>$ filhak node --port 8765`

**Filhak network** is a (stripped-down) local development network for Filecoin that works out of the box, with no setup required.

Every filhak task is executed inside the local filhak network.

The idea is to bootstrap and connect one lotus client and miner node and run them in the background.

Nodes should be headless and stripped down of all of the features that are unnecessary for local development but are required to operate a full lotus node, to improve performance and optimize the development experience. 

The network can be exposed for external JSON-RPC calls by running  `>$ filhak node` (if necessary).

⚠️  This assumes that lotus will integrate with FVM and at least built-in FVM actors (we can use a development version if it’s available, before launching to mainnet).

### Filhak Go package

`import "github.com/Bloxico/filhak/script"`

Filhak provides one or more **Go packages** that implement common helper functions & data structures used in writing filhak tasks during actor development.

Stuff like:

- Creating and funding accounts
- Creating and sending transactions
- Creating and interacting with deals
- Working with the retrieval market
- Interacting with deployed (or built-in) actors
- Reading the (devnet) chain state tree
- etc

These helper functions should be optimized for **developer experience,** and hide underlying complexity of instantiating big Lotus data structures and making multiple API calls.

### Filhak scripts

`>$ filhak run script.go [--task=<name>]` 

Runs a script file on the local development network.

Given the task parameter, it executes a single task from the file.

Tasks are simple go functions:

```go
func DeployActorTask(ctx Context, fh *filhak.Network) { ... }
```

Positional parameters can be passed to tasks via the run command, and accessed inside the task code

```go
func FundAccountTask(ctx Context, fh *filhak.Network) {
	amount := ctx.args[0]
	addr := ctx.args[1]
  fh.Accounts.Fund(addr, amount)
}
```

### Milestone 1 - Filhak Network

**Deliverables:**

- `filhak` CLI tool
- project scaffolding and configuration 
- launch and interact with the development network via `filhak node` command

**Funding for this milestone:**

For M1 three full time **Go** developers rate will be $45 / hour in order to fund the milestone.

However in this rate we are not including funding for **PO (Andreja Markovic)** and **PM (Katarina Milisavljevic)** positions, this will come from internal budget. Reason is that we want to have additional support for developers so that they can fully focus on development of this project.

Team will be paid an estimated $23,220 per month, and $46,440 per milestone.

The estimated payment amount per month will be subject to change due to different wokring days in a month, public holidays, sick leaves, etc. 

Upon completion of M1, team will be paid $25,000. 

**Total budget for M1 - $71,220.**

**Estimated Milestone Delivery:**
First half of August 2022

### Milestone 2 - Filhak Scripting

**Deliverables:**

- run filhak scripts via the `filhak run script.go [--task=<name>]` command on the local devnet
- implement the `github.com/Bloxico/filhak/script` helper package
- interact with locally deployed actors in scripts using the helper functions

**Funding for this milestone:**

For M2 three full time **Go** developers rate will be $45 / hour in order to fund the milestone.

However in this rate we are not including funding for **PO (Andreja Markovic)** and **PM (Katarina Milisavljevic)** positions, this will come from internal budget. Reason is that we want to have additional support for developers so that they can fully focus on development of this project.

Team will be paid an estimated $23,220 per month, and $46,440 per milestone.

The estimated payment amount per month will be subject to change due to different wokring days in a month, public holidays, sick leaves, etc. 

Upon completion of M2, team will be paid $25,000. 

**Total budget for M2 - $71,220.**

**Estimated Milestone Delivery:**
First Half of October 2022

## Maintenance and Upgrade Plans

We plan on maintaining our existing codebase as well as to develop and integrate additional features such as: 

**Filhak network**

Adding multi-runtime support for local network through *deployers* so that there is support for both **Native deployer** and **EVM deployer**.

**Filhak testing**

`import "github.com/Bloxico/filhak/testing"`

Filhak uses `go test` to run tests and provides helper functions for interacting with the filhak network and the deployed and built-in actors.

It also provides a set of filecoin-specific assertions that can be used in your tests.

**Filhak templates**

`>$ filhak template <template_name> [--name=<local_name>]` 

You can use filhak to instantiate actors from existing best-practice, reviewed actor templates implemented by other builders
or by PL developers (inspired by OpenZeppelin contracts).
Templated actors then can be further extended with additional business logic.

The repository that holds these contracts will be determined in sync with other early builders and PL developers and filhak will pull the templates from that repo and instantiate them locally.

**Filhak deployment**

Actor deployment on Testnet and Mainnet as soon as it's available.

**Filhak extensions and pluggins**

Implement a VS Code extension for filhak to improve the dev experience

⚠️ **Some of these future features depend on FVM delivery.**

🚀 **Moonshot**: Our end goal is to develop "Filecoin Simulation" similar to what **Ganache** is offering, where developers will be able to quickly fire up a personal **Filecoin** blockchain which they can use to run tests, execute commands, and inspect state while controlling how the chain operates. But this is a long-shot and way out of scope for this proposal.

## Project Requirements

- User programmability (3rd party actors) are required for filhak to reach it’s full potential. 
- Feedback from other early builders and PL developers is highly recommended, so we can improve the development experience of our framework

## Total Budget Requested

**M1:** 

$46,440 - Time and Material

$25,000 - Completion of M1

**M2:**

$46,440 - Time and Material

$25,000 - Completion of M2

**Total Budget: $142,440**

# Team
## Contact Info

**On Filecoin slack:**

    @Nikola Divic
    @Andreja Markovic

## Team Members

**Go Developers:**

    Nikola Divic @TheDivic
    Bojan Milinkovic @bokimilinkovic 
    Stefan Gajic: @StefanGajic
    
**Project Manager**
    
    Katarina Milosavljevic
    
**Product Owner**

    Andreja Markovic

## Team Member LinkedIn Profiles

[Nikola Divic](https://www.linkedin.com/in/thedivic/).

   [Bojan Milinkovic](https://www.linkedin.com/in/bojan-milinkovic-169780151/).
   
   [Stefan Gajic](https://www.linkedin.com/in/stefan-gajic-ns/).
   
   [Katarina Milosavljevic](https://www.linkedin.com/in/milosavljevicgkatarina/).
   
   [Andreja Markovic](https://www.linkedin.com/in/andreja-markovic-6704ba13b/).

## Team Website

https://bloxico.com/
## Relevant Experience 

Our team have extensive experience in regards to writting in **Go** as well as experiance with **Filecoin** technology. We have successfuly developed:
- **System Test Matrix** - Lotus Filecoin test coverage improvement and visualization dashboard.

And currently we are developing first phase of:
- **Testground** -  platform for testing, benchmarking, and simulating distributed and p2p systems at scale infrastructure and software revamp.

Furthermore, we followed the FVM development since its inception. We  participated in various **FVM AMA** sessions as well as recurring **FVM Early Builders Check In** where we indicated that we would like to to develop **Hardhat** inspired development enviroment for **FVM**
## Team code repositories

[fil-filhak](https://github.com/Bloxico/fil-filhak)

[fil-lotus](https://github.com/Bloxico/lotus)

**Comment by BlocksOnAChain** [comment]
@kapetan3sid what can we expect in terms of how-to guides and development experience for people that will use FIlHak to build use cases on FIlecoin? 
Also, do we have a list of requirements for your testnet support - how will one dev deploy and test things on a dedicated testnet?

**Comment by raulk** [comment]
Hey @kapetan3sid and Bloxico team, thanks for the submission! Unfortunately the proposed scope is not something we can fund.

- It is too abstract. This focuses on building a script-based skeleton, but defines very little in terms of actual commands and behaviours, which is what we're interested in and where the bulk of the work should go.
- The amount of funding requested for the little amount of value delivered is disproportional.
- I think your effort estimates to build what you've proposed are **way** above reality.
- I suspect you're wanting to mimic a plugin-based system, but the motivation to incur in that complexity at this stage is not clear. The resulting UX is also clunky: (a) please study how go scripts would work, it's not that easy in terms of deps, compile latencies, and more; (b) positional arguments will get unwieldly, (c) there are no signs of how help texts would be implemented.
- This cannot be T&Ms. T&M is super easy for the vendor, but it's really hard for the funder. We are looking for a self-driven team that can act as a thought leader, analysing the status quo, making strong proposals, and taking an active stance at shaping the developer experience for native actors. T&M is the opposite.
- All other grant requests from Early Builders are for fixed scope. I don't see a reason to deviate from that pattern. We're happy to fund those because they demonstrate that teams have done upfront research, they understand the problem space well, have put together compelling proposals, and are motivated to deliver the outlined scope.
- I don't understand the fee structure, concretely what the references to 25k USD represent.

Sorry but we cannot accept this proposal in this form. We're happy to discuss alternative directions forward.

**Comment by raulk** [comment]
Just to be clear, user-side extensibility is not a primary goal here. Yes, we should keep this in mind in our design (and have an idea of how it will be introduced later), but picking this as a starting point is weird. I would also not use Go scripts at all for modularity.

**Comment by kapetan3sid** [comment]
Hi @raulk and @BlocksOnAChain, thanks for your feedback! 
Let me discuss this with my team and see what is alternative approach in regards to definition of scope (to make it tangible) as well as funding. 
I'll get back to you with additional information as soon as possible.

**Comment by kapetan3sid** [comment]
Hi @raulk and @BlocksOnAChain, thanks for your feedback!
Let me discuss this with my team and see what is alternative approach in regards to definition of scope (to make it tangible) as well as funding.
I'll get back to you with additional information as soon as possible.

**Comment by realChainLife** [comment]
Thanks @raulk and @BlocksOnAChain for the reviews. 

@kapetan3sid we will close this issue for now - please submit a new application with the updated scope when you're ready.

**Comment by DeveloperAlly** [comment]
@realChainLife could we please re-open this.
I've pinged you to have a chat about how we were hoping to run these proposals. Thanks

**Comment by BlocksOnAChain** [comment]
closing since we got feedback that we won't collaborate, at this time
