### ISSUE TITLE
web3dev community

### ISSUE THREAD

**Issue by danicuki** [filecoin-project/devgrants#629]
# Open Grant Proposal: `web3dev`

**Name of Project:** web3dv

**Proposal Category:**  `community`

**Proposer:** `danicuki`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** YES

# Project Description

Web3dev is the largest and most engaged web3 developers community in LATAM.

We already have a Discord with more than 1800 developers: https://bit.ly/w3b3d3v Our community is organized in pods, each pod for a different theme or blockchain. Each pod has a leader, which helps that pod to evolve, promoting growth to the ecosystem and the whole web3dev community.

We already have leaders for Ethereum, Cardano, NEAR, Algorand, Solana, Terra. We incentivize those pods, creating bounties and paying individual contributors when they create new content and deliver value.

## Value

There are thousands of great developers in Brazil eager to get into Terra, but English-only content is still a limitation. We are building a developers community for web3 technologies in Latin America. We engage people to translate English content and also produce original content for specific blockchains.

Our objective is to bring thousands of web2 developers to the web3 world. Brazil is the biggest economy in Latin America and has thousands of high talent developers. When more Brazilian developers have the tools to build innovative solutions, Filecoin and libp2p technologies can be used to solve different problems in Brazil such as agro-business green certification, forest devastation, environmental issues, better wealth distribution and hunger.

We have limited resources to invest on all specific blockchains, so this partnership could accelerate the adoption of Filecoin and libp2p technology in Brazilian crypto startups.

## Deliverables

We expect to have 20,000 developers in our community by the end of 2022. We expect to reach at least 2,000 of them with specific filecoin and libp2p ecosystem content, some of them being able to work and deliver value on real projects in the filecoin ecosystem.

3 months of ongoing technical content creation:
- 15 videos - 5 per month, 3 months to produce, publish and advertise
- 15 text articles - 5 per month, 3 months to produce, publish and advertise

### Milestone Month 1 

- coordinator allocation and setup: $2,000 
- 5 videos: $1,500
- 5 articles: $900

### Milestone Month 2

- 5 videos: $1,500
- 5 articles: $900

### Milestone Month 3

- 5 videos: $1,500
- 5 articles: $900

## Total Budget Requested

- $4,500 for 15 videos (cost per video: $300)
- $2,700 for 15 articles (cost per article: $180)
- $2,000 for editorial and publishing coordination

Total **$9,200**

## Maintenance and Upgrade Plans

We can continue to generate high quality content for filecoin on a monthly basis. We are able to create not only video and written articles, but also podcasts, workshops and bootcamps to engage the community. Our bootcamp platform is 100% open source and we already have 800 developers subscribed to Solidity bootcamps.

# Team

## Team Members

- Daniel Cukier: PhD in CS, developer since 1995, In Crypto since 2020, Founder of Playax, CTO of Elo7, CTO of Pravaler
Twitter: https://www.twitter.com/danicuki
- Yan Luiz: Developer since 2014, in Crypto since 2016, Youtuber, Solidity Teacher, Blockchain Developer - https://www.linkedin.com/in/yanluiz/
- Rafael Lima, serial entrepreneur, Developer since 1998, in Crypto since 2015, Founder of Impulso, a community with more than 100.000 developers in Brazil. Founder of cobogo.social, Projog and Kobana - https://github.com/rafaelp

## Team Member LinkedIn Profiles
- https://www.linkedin.com/in/danielcukier/
- https://www.linkedin.com/in/yanluiz/

## Team Website

https://www.web3dev.com.br
https://bootcamp.web3dev.com.br

## Relevant Experience

I am a technology innovator, working with web3 projects in the last 2 years. Former CTO in Brazilian startups such as Pravaler - a fintech that offers accessible student loans - also founder and CTO at Playax - an audience development platform for music professionals based on BigData - also worked for two years as CTO at Elo7 – the biggest crafts marketplace in Brazil.

Experienced working in different programming languages such as Elixir, Ruby, JavaScript and Java, I helped many startups as venture advisor at Monashees Capital and other accelerator programs in Brazil. I am also PhD in Computer Science at University of São Paulo – IME-USP. My PhD research is about Software Startups Ecosystems and Entrepreneurship.

I mastered in Computer Science in University of São Paulo in 2009, with the Thesis Patterns for Introducing New Ideas in the Software Industry. Daniel is a Cloud Computing GDE (Google Developer Expert). I started developing software in Brazil when he was 10, on his TK-3000 Basic 2MB RAM computer.

## Team code repositories

- https://github.com/w3b3d3v
- https://github.com/w3b3d3v/web3-bootcamp-platform

# Additional Information
- 1800 developers in our Discord Server
- 838 Solidity [bootcamp](https://bootcamp.web3dev.com.br) subscriptions - more than 100 graduated
- [Bootcamp LMS platform open sourced](https://github.com/w3b3d3v/web3-bootcamp-platform) 
- 170 published articles [our website](https://www.web3dev.com.br)
- More than 1,500 page views / day in our website.

**Comment by ErinOCon** [comment]
Hi @danicuki, thank you for your proposal! This grant has been approved. To proceed with next steps, please email grants@filecoin.org.

**Comment by danicuki** [comment]
thanks! happy to know! I just sent the email, waiting for next steps! :-)
