### ISSUE TITLE
UDT-Tachyon an updated fast file transfer protocol

### ISSUE THREAD

**Issue by abheek9** [filecoin-project/devgrants#634]
# Open Grant Proposal: `UDT-Tachyon: An updated fast file transfer protocol`

**Proposal Category:** `core-dev`

**Proposer:** @abheek9

**(Optional) Technical Sponsor:** @dkkapur

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** *Yes*

# Project Description

Tachyon is a Y Combinator backed company building tools to transfer large datasets across the world faster. We offer developers an API to upload and download files in a similar fashion to an FTP server. Our file transfer technology is built on two pillars 1) A fast application-level transport protocol that increases bandwidth utilization 2) A network of edge servers to reduce latency.

After a series of conversations with internal stakeholders, and with Juan Benet, we believe it would be useful to make our data transfer tool open source for the web3 and OSS communities. 

We propose 1) open sourcing our high speed transport protocol (UDT-Tachyon) under the most permissive license and 2) creating easy 1 click deploys for our testing infrastructure.

Currently the only open-source high speed transport protocols are abandoned, outdated, and not easy to use (don’t build) (GridFTP, UDT, Tsunami). Many have not seen contributions since 2011, and do not have wrappers in the most popular languages. Additionally none of the existing projects have associated cloud-hosted testing infrastructure. This is important because of one of the hardest parts of contributing to new protocols is testing changes in a variety of network conditions.

UDT-Tachyon specifically aims to overcome the short comings of UDT and other open source protocols which are related to 1) performance;  2) ease of use.  The performance issues of the open source protocols are almost all related to poor performance under high packet loss conditions since most protocols conflate ‘true’ congestion with random packet loss. We make several changes to UDT to perform better under high packet loss, including a) improving the timer on the sender and receiver which was outdated and no longer deterministic leading to strange non-deterministic errors,  b) creating additional congestion signals that help UDT distinguish between random packet loss and ‘true’ congestion, c) Changing the control message logic of UDT to improve thread performance, and utilize the new signals we developed.

To overcome ease of use issues we propose providing better documentation and providing testing infrastructure in the form of 1 click deploys on cloud infrastructure. Our work will provide a nice fully encapsulated open-source project that will help add value to the world, and supports Protocol’s labs mission of being an open-source R&D lab and supporting work that could revolutionize the internet.

## Value

A new fast file transfer protocol will make it easier to share large datasets around the world. There have been a number of academic labs we have talked to as well as members of the public who would love to have a new user-friendly protocol available. Additionally there is a clear benefit to Filecoin to have a fast transfer protocol to help move data into the ecosystem

We have already improved and tested the new protocol. There are no major technical risks or gaps at this stage for the scope that we have defined above. This is explored further in [our blog post](https://www.trytachyon.com/post/how-we-built-a-new-fast-file-transfer-protocol).

We need to spend time modularizing the code, testing, writing new documentation, and making the testing infrastructure more easily useable. We think we need 2 months of time to sufficiently complete this work.

## Deliverables

Our final deliverable will be composed of 2 main parts. 

1) A github project with 2 branches of our UDT-Tachyon protocol, written in c++. A user will be able to clone the project, and use our ***sender*** and ***receiver*** libraries to transfer large datasets on linux and mac devices. There will be accompanying documentation

2) A one click deploy virtualized network emulator in the cloud. We will create AWS AMIs of our emulator. Along with documentation on how to use it. This emulator will let people test our protocol with varying levels of latency and packet loss.

## Development Roadmap

We plan to deliver the work in two milestones, each of which maps to the main pieces of deliverables we have planned above. 

**Milestone 1: C++ and other libraries shared on GitHub**

Core deliverable: GitHub repo with 2 branches of our UDT-Tachyon protocol

Effort required: 4 weeks of 2 developers

Approximate timeline: we can start within the next two weeks. This would roughly put us on a schedule to complete work for this milestone by July 25, 2022

Required funding: $22,000

| Feature/ Workstream      | Time Estimate (number of people) | Success Metric |
| ----------- | ----------- | ----------- |
| Clean up and modularize c++ code for UDT-Tachyon stable sender      | 1 Week (2 people)       | UDT-tachyon stable sender library can send 5GB file |
| Clean up and modularize c++ code for UDT-Tachyon stable receiver      | 1 Week (2 people)       |UDT-tachyon stable receiver library can receive 5GB file |
| Clean up and modularize c++ code for UDT-Tachyon experimental sender      | 1 Week (2 people)       | UDT-tachyon experimental sender library can send 5GB file |
| Clean up and modularize c++ code for UDT-Tachyon experimental receiver      | 1 Week (2 people)       | UDT-tachyon experimental receiver library can receive 5GB file |

**Milestone 2: Testing Infra**

Core deliverable: one-click-deploy virtualized network emulator in the cloud

Effort required: approx. 3.5 weeks of 2 developers

Approximate timeline: we can continue into the second milestone as soon as the first one completes. Earliest realistic date for completion of this would be Aug 24, 2022.

Required funding: $18,000

| Feature/ Workstream      | Time Estimate (number of people) | Success Metric |
| ----------- | ----------- | ----------- |
| Test build on linux (ubuntu) builds      | 1 Week (2 people)       |UDT-tachyon sender and receiver works on ubuntu 20+ builds|
| Test build on mac build     | 1 Week (2 people)       |UDT-tachyon sender and receiver works on Mac 10.14+  |
| Provide Testing Infrastructure as 1 click deploy AMI      | 1 Week (2 people)       | A user can download AWS AMI|
| Write up further blog posts on all technical details      | 1/2 Week (1 person)       | Blog post is up|
| Update our documentation       |        | Documentation is available |
| Write up blog posts on future direction of project and  how to reach Aspera parity  | 1/2 Week (1 person)     | Blog post is up|

## Total Budget Requested

40,000 USD for 2 software developers to work for 2 months. 

## Maintenance and Upgrade Plans

Our team will answer questions and work on issues for the GitHub project for the next 6 months. If there is additional appetite from the community, we can also expand to new languages and integrate more tightly with Filecoin.

# Team

## Team Members

Abheek Basu

Mahamad Charawi

## Team Member LinkedIn Profiles

[https://www.linkedin.com/in/abheek-basu-4a72a398](https://www.linkedin.com/in/abheek-basu-4a72a398)

[https://www.linkedin.com/in/mahamad-c-a025b9193/](https://www.linkedin.com/in/mahamad-c-a025b9193/)

## Team Website

https://www.trytachyon.com/

## Relevant Experience

We are a YCombinator backed company, with prior experience in networking. Our CTO and co-founder Mahamad Charawi used to work at Cisco where he developed new protocols. Both the founding team members have experience as software developers, specifically in networking.

## Team code repositories

# Additional Information

**Comment by ErinOCon** [comment]
Hi @abheek9, thank you for your proposal! This grant has been approved. To proceed with next steps, please email grants@filecoin.org.
