### ISSUE TITLE
Next Step Microgrant: build and run filecoin faucet website

### ISSUE THREAD

**Issue by blockchainx** [filecoin-project/devgrants#635]
### 1. What is your project? (max 100 words)
i want to build a faucet for filecoin mainnet and testnet for developers or interested in filecoin newcomer to easily to get some filecoin for play and develop.

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
it will be a easy way to get in touch in filecoin.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
first i need to build a website, then put e.g. 0.01FIL for each apply(using phone number as a condition, for testnet the apply will be daily limit) 
 
### 4. Is this project open source?
yes, the website sourcode will be open source in github.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes, i grant use will be reported in quarter.
  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by blockchainx** [comment]
Hello ErinOcon, not yet now,  but i will start to build a prototype.

**Comment by ErinOCon** [comment]
Hi @blockchainx, please feel welcome to submit a new proposal once building has progressed. Happy building!
