### ISSUE TITLE
Next Step Microgrant: IPFS Pastebin

### ISSUE THREAD

**Issue by Soptq** [filecoin-project/devgrants#637]
### 1. What is your project? (max 100 words)
This project builds a pastebin on IPFS. Specifically, this project saves users inputs to IPFS and generates a unique paste hash for them to share. User inputs can be encrypted so that only people who know both the paste hash and the corresponding password could retrieve the underlying input.

https://github.com/Soptq/ipfs-pastebin
https://ipfs-pastebin.vercel.app/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
This project is powered by web3.storage and IPFS. User inputs are saved to and fetched from IPFS using web3.storage.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
- Explore how to host the app completely on IPFS for maximum decentralization.
- Support more user inputs. Currently it only supports text, but it should support other types of file like image, video, etc.
- Make some UI updates.
- Other possible improvements like a dedicated domain (currently it is using vercel's public domain).
 
### 4. Is this project open source?
MIT

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
https://gitcoin.co/issue/ipfs-and-filecoin/hackathons-bounties/6/100028834
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Soptq
Email: outline_spoiler0t<at>icloud<dot>com
Github: Soptq
Role: Developer

* How did you learn about our microgrant program?
Email

* If your project was created as part of an event or hackathon:
Hackathon: L2 Rollathon: https://gitcoin.co/issue/ipfs-and-filecoin/hackathons-bounties/6/100028834

**Comment by ErinOCon** [comment]
Hi @Soptq, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by Soptq** [comment]
Updates will be posted here:
- 20.6.2022 - 4.7.2022 : Implement dark theme and mobile-first responsive webpage with some UI updates.
