### ISSUE TITLE
Next Step Microgrant: AMHO QR

### ISSUE THREAD

**Issue by nnons** [filecoin-project/devgrants#638]
### 1. What is your project? (max 100 words)

We utilized IPFS to store the metadata of our ceramic stream which also uses IPFS/IPLD under the hood. The Ceramic stream stores the encrypted data for each of meta-physcial items on sale and only allows the seller and the buyer to decrypt this data used in contract functions. The encryption is handled by Lit Protocol. For the case of public and transparent storage, we're safe using IPFS. It does not matter if the data is available to parties outside of the buyer or seller because only they are the only ones that can decrypt the IPFS data. Finally, the data will be then converted into a scannable QR code that the buyer and seller utilizes to confirm that a physical good was received so the digital twin NFT can be transferred to the owner of the physical item that was scanned. The goal of this system is to combine a physical item to it's digital twin (which is an NFT).

https://github.com/amhodao/AMHOQR

https://amho.xyz (Landing page not full dapp)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
IPFS and IPLD are utilized in storing NFT metadata, image data, and encrypted data using Ceramic Network as a DID provider. The website taps into IPFS when retrieving this type of data to use in a QR code scanning flow. In this case, we used it to enable users to redeem a non-tangible good with a tangible good.  

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
By building a boilerplate template/libraries so other users can build a product utilizing this QR code flow.
Also will improve gas efficiency within the smart contracts and build an oracle mechanism to punish bad actors from escaping the tethering flow.

Steps
1. Rescoping and redesigning the QR scanning flow
2. Optimizing gas within the smart contract by utilizing open source tools
3. Improving the QR scanning flow with zkProofs instead of storing a hash
4. Integrating an oracle mechanism within the smart contracts that reference IPFS contentURIs
5. Develop an NPM or react library others can use to import this QR flow into their applications.
 
### 4. Is this project open source?

Yes. CC-BY-SA 3.0

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

I agree.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

https://dorahacks.io/buidl/1946?roundProj=1645#intro
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Non - non@amho.xyz - https://github.com/nnons - Sole contributor
Mehdi - rhouzzm@gmail.com (No longer with project)
Louell - louell_salla@yahoo.com (No longer with project)

* How did you learn about our microgrant program?
Email from niki.gokani@protocol.ai
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) ETHDenver 2022 Virtual Buidlthon
  * Please link to your hackathon submission
https://dorahacks.io/buidl/1946?roundProj=1645#intro

**Comment by ErinOCon** [comment]
Hi @nnons, This microgrant has been approved! Look out for an email to submit payment details.
