### ISSUE TITLE
Next Step Microgrant: Domain Names & Data Economy In Hedera and IPFS

### ISSUE THREAD

**Issue by calebtuttle** [filecoin-project/devgrants#639]
### 1. What is your project? (max 100 words)
Our project allows a user to establish a verifiable link between their domain name and their blockchain address. The user can then sign IPFS content and thereby establish that the content is in fact from them (i.e., from the party controlling the domain name and blockchain address). Such verifiable links between domain names, blockchain addresses, and IPFS content reduces the need for oracles. Instead of relying on oracles to attest that certain data is from a certain website, consumers in data markets can now rely directly on the website itself--and website owners can sell their data directly to their consumers.

[https://github.com/nanaknihal/blockchain-sslcert](https://github.com/nanaknihal/blockchain-sslcert)
[Presentation](https://devpost.com/software/domain-names-data-economy-in-hedera-and-ipfs)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Streaming data to the blockchain can be expensive, so a solely on-chain data economy won't be able to handle large amounts of data. IPFS allows our project to scale. After linking their domain name to their blockchain address, a user can stream data to IPFS that is verifiably linked to their domain name. The user only needs to record on their smart contract a pointer to the latest IPFS content. 
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

This grant will allow us to improve our project by allowing us to accomplish the following:
- Write documentation for both data producers and data consumers who can benefit from our project.
- Improve our suite of tools to make it easier for both data consumers and producers to sell and buy data.
- Integrate other forms of identity (such as linking GitHub accounts to blockchain addresses) to further increase trust between market participants.

### 4. Is this project open source?
This project is open source and uses the MIT license.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
[https://devpost.com/software/domain-names-data-economy-in-hedera-and-ipfs](https://devpost.com/software/domain-names-data-economy-in-hedera-and-ipfs)

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
- Nanak Khalsa
  - Email: nanak@opsci.io
  - GitHub: https://github.com/nanaknihal
  - Role: Developer
- Caleb Tuttle
  - Email: caleb@opsci.io
  - GitHub: https://github.com/calebtuttle
  - Role: Developer

* How did you learn about our microgrant program?
We heard about the microgrant program after receiving an award from Filecoin in the "Hedera22: Hello Smart Contracts" hackathon.

* If your project was created as part of an event or hackathon:
  * Name: Hedera22: Hello Smart Contracts
  * Submission link: [https://devpost.com/software/domain-names-data-economy-in-hedera-and-ipfs](https://devpost.com/software/domain-names-data-economy-in-hedera-and-ipfs)

**Comment by ErinOCon** [comment]
Hi @calebtuttle, This microgrant has been approved! Look out for an email to submit payment details.
