### ISSUE TITLE
Next Step Microgrant: Phaeros (OpenRecon)

### ISSUE THREAD

**Issue by fraanetski** [filecoin-project/devgrants#640]
### 1. What is your project? (max 100 words)
I created OpenRecon during the L2 Rollathon and won the Social Good Warrior prize. I’ve since formed a clearer vision of what needs to be built in this space. Thus, I’m evolving OpenRecon into Phaeros - a platform for **decentralized open source investigative journalism.** 

Through a smart contract, subscribers form a monthly pot of money and vote on what topic(s) in current events they want to know more about for that month. Anybody can contribute to the investigation(s) by finding, analyzing, and/or synthesizing open source information, and will then get paid from the pot according to their contributions.

https://openrecon.xyz
https://github.com/fraanetski/OpenRecon
_Note: Phaeros will fork the OpenRecon codebase and stay under the same license_

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Decentralized storage is an extremely essential part of the project, because the infrastructure for this platform needs to be censor-proof and eventually allow for the formation of a DAO.

The topics that the subscribers decide on, the intel that the reporters submit, and the final reports will be stored on IPFS/Filecoin. The CIDs will be publicly viewable, that way the things that Phaeros contributors investigate and find out will always be accessible even if the Phaeros DApp goes offline. In short, IPFS/Filecoin will be used as the storage layer for anything important.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
The development to get to MVP for Phaeros given the OpenRecon starting point is probably about 1-2 months of greater than-full time work. This grant will give me the freedom to work full time on developing this project, and it will help pay for the other costs that come along with growing a project like legal, design, subscriptions, etc.

Specifically, here is what I aim to accomplish with the aid of this grant:

- Design and implement intel submission manager, with encryption/decryption on IPFS/Filecoin upload/retrieve to prevent cheating
- Design and implement intel analysis and synthesis collaboration workflow, integrating IPFS/Filecoin where necessary
- Implement subscription and explore the potential of CID access control based on subscription
- Implement final report distribution on IPFS/Filecoin
- Implement archiving feature

In short, under this grant I want to get to a beta MVP of the Phaeros platform that I can begin using for user testing and feedback.

### 4. Is this project open source?
Yes, under an MIT license.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

This project began at the L2 Rollathon where it won the Social Good Warrior prize.

https://gitcoin.co/hackathon/Rollathon/projects/15389/openrecon
https://gitcoin.co/hackathon/Rollathon/projects/15382/openrecon
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Netski, fraanetski@protonmail.com. https://github.com/fraanetski, Founder/Lead Dev

* How did you learn about our microgrant program?

Emails from the Protocol Labs team after the L2 Rollathon.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)

Gitcoin L2 Rollathon

  * Please link to your hackathon submission

https://gitcoin.co/hackathon/Rollathon/projects/15389/openrecon
https://gitcoin.co/hackathon/Rollathon/projects/15382/openrecon

**Comment by ErinOCon** [comment]
Hi @fraanetski, This microgrant has been approved! Look out for an email to submit payment details.
