### ISSUE TITLE
Next Step Microgrant: <Web3 Domain>

### ISSUE THREAD

**Issue by gupta977** [filecoin-project/devgrants#641]
### 1. What is your project? (max 100 words)
We are building WEB3 DOMAIN just like unstoppable & ENS domain. But with lot more features and use case they are still not providing. 
Eg. 
* Let user to mint own primary domain (Eg. .grant) and sell as domain provider (Eg. username.grant)
* It can be used for  to verify product or certificate, which has unique code.
* Including all features that unstoppable , ENS are providing. 

https://web3domain.org 

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Every domain holds lots of information like images, wallet address, social ids, notices, which are uploaded into IPFS, Filecoin. In short, without Filecoin our project cannot do anything. Everything is depend upon Filecoin. 
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
 This is very big long term NFT based project with complete use case. We need to work on all different sectors. Currently we hired developers and tried our best to achieve primary goal. With the grant money received, I will use it to level up our project with developers API and in building community.  
 
### 4. Is this project open source?
Yes, under an MIT license. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, I agree
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes 

### 7. Links and submissions
* Project has been build of our own. No any cash grants or 3rd party groups are involved. 
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
 Navneet Gupta, admin@web3domain.org, https://github.com/gupta977/, Founder

* How did you learn about our microgrant program?
From Filecoin <> PolygonDAO telegram group. 

* If your project was created as part of an event or hackathon:
Not taken part yet.

**Comment by ErinOCon** [comment]
Hi @gupta977, thank you for your proposal! Do you have a repo link with your current code available? Also, can you provide more detail on the next steps you will take with this project? What specifically do you hope to accomplish in the next three months with this grant? What is your strategy for meeting this goal?

**Comment by gupta977** [comment]
Hello,
Thank you for letting me to explain the project.

Web3Domain is big project which requires multiple type of application &
plugins which is combined to make one eco-system. So all the code is not at
single repo.
We are developing since more than a year.
Some of the public repo links for your reference only
https://github.com/gupta977/crypto
https://github.com/gupta977/flexi

You might have heard about https://unstoppabledomains.com/. We are building
better and much more advance with them.
Very proud to say that, must of the things in term of features we are
already beyond them.
What we all don't have is connection, partnership, community which are most
essential part.
With this grant we will develop much more innovative features which is not
yet introduced.
Eg. Product NFT certification, Domain reseller option, web2 based tools to
interact web3 interface.

Hope I able to give you the idea we are building and what goal we can
achieve in near future.
Thank You
Navneet Gupta

**Comment by ErinOCon** [comment]
Hi @gupta977, this microgrant has been approved! Look out for an email to submit payment details.

**Comment by ErinOCon** [comment]
Hi @gupta977, thank you again for your recent microgrant proposal! Please complete [this template](https://airtable.com/shrrtSlgdVvrPmAvr) for your final report.
