### ISSUE TITLE
Next Step Microgrant: <ChessPOS>

### ISSUE THREAD

**Issue by B-Venkatesh7210** [filecoin-project/devgrants#642]
### 1. What is your project? (max 100 words)
ChessPos is a decentralized web app where users can play chess with others by putting some matic coins at stake and getting rewards for winning. Chesspos also allows users to engrave their chess game memories on blockchain by minting position-based/Animated gif NFTs.

Link to public Github repo => https://github.com/AniketSindhu/ChessPos-Frontend 
Link to demo or website, if applicable => https://chesspos-b5d1e.web.app/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
For minting NFT of the user's favourite position. Our smart contract makes sure that every NFT minted is unique and fascinating in its own way. Users can select color of their own choice to mint the NFT.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will work on making the NFT more unique and interesting. We will work on the designing of the NFT and will try to make it auto generative. We are also planning to make it a 3D chess game where NFT that are animated gifs give a 3D look as well.
 
### 4. Is this project open source?
Yes this project is open source.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes we agree to provide you with any minute detail if asked.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes it complies with the Community Code of Conduct.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
https://devfolio.co/projects/chesspos-e565
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
-> Member 1
Name - Aniket Sindhu
Email - sindhuaniket@gmail.com
Github - https://github.com/AniketSindhu
Role - Smart Contract and Backend Developer

-> Member 2
Name - B Venkatesh
Email - venkumj1234@gmail.com
Github - https://github.com/B-Venkatesh7210
Role - Frontend and UI/UX designer

-> Member 3
Name - Rohit Kumar
Email - rohitduhan2301@gmail.com 
Github - https://github.com/Rohit2301
Role - Frontend and UI/UX designer

* How did you learn about our microgrant program?
Hackathon and Email

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
  Polygon BUIDL IT Hackathon 2021 
  * Please link to your hackathon submission
  https://devfolio.co/projects/chesspos-e565

**Comment by ErinOCon** [comment]
Hi @B-Venkatesh7210, this microgrant has been approved! Look out for an email to submit payment details.

**Comment by B-Venkatesh7210** [comment]
Hello, I haven't received any email to submit payment details. Please check
into it.

Thank you

**Comment by ErinOCon** [comment]
Hi @B-Venkatesh7210! Just closing the loop on this thread to confirm the email was sent and payment process in underway. If you have any questions for our team regarding payment, please be in touch by email.

**Comment by B-Venkatesh7210** [comment]
Thank you!

**Comment by B-Venkatesh7210** [comment]
Hello, I haven't received the payment yet. Please make it as soon as
possible.

**Comment by B-Venkatesh7210** [comment]
I have made the changes in the transfer request, please check and transfer
the amount as soon as possible.

Thank you

**Comment by ErinOCon** [comment]
Hi @B-Venkatesh7210, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!
