### ISSUE TITLE
Next Step Microgrant: ZooHarmony [ Your Favorite NFT Marketplace You Have Not Seen Yet ]

### ISSUE THREAD

**Issue by Agin-DropDisco** [filecoin-project/devgrants#644]
### 1. What is your project? 
Provides a new NFTs experience while embracing the popular crypto trend of dual farming in decentralize finance. The project complements another existing [DexSwapZoo Dapp](https://matic-amm.zoo-harmony.com/). [ZooHarmony](https://polygon.zoo-harmony.com/) has its own utility token ($ZOO) distributed as farming rewards to DexSwapZoo LPs, who stake their DEZU/DexSwapZoo tokens.

### 2. How will IPFS, Filecoin, or related technology be used for this project?
**Pined nft, Fetch All NFTs Data from Server Side 'Nginx', Gateaway, Post Data Request
Flow:** 
<p aling='center'>
  <img src='https://raw.githubusercontent.com/Agin-DropDisco/ethdenver/main/ipfs.png' />
</p>

### 3. How will you improve your project with this grant? What steps will you take to meet this objective?
- [x] Bring the new experience for higher mining/staking rewards and richer
- [x] Build mobile Gaming/Moba 5 vs 5 (will move this to open grants after microgrants completed)

### All the 5K funds will be spent for
- [x] Hosting/Server == Digital Ocean, Cloudflare, Pinata/IPFS, Amazon ( 3 ~ 6 Months)
- [x] Audit ZooHarmonyNFT Contracts
 
### 4. Is this project open source?
Yes
_GNU General Public License v3.0_ 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions

- Filecoin Community Showcase : https://github.com/ipfs/community/commit/fad295e914ccae04cd92fe00d14686cca661f7df

- Community discussion board : https://github.com/filecoin-project/community/discussions/529
  
### ZooHarmony Teams:
**1. Fullstack Developer**
**Name: Agin DropDisco** 
[Linkedin](https://www.linkedin.com/in/agin-dropdisco-5555b7171)
[Github](https://github.com/Agin-DropDisco)

**2. RPA Production from PT AXA Services Indonesia**
**Name: Adinda Ratnawati Ridwan**
[Linkedin](https://www.linkedin.com/in/adinda-ratnawati-ridwan-20a980170)
[Github](https://github.com/adinda-ratna)

**3.Senior Solidity Developer**
**Name: Agus Wildhan**
[Linkedin](https://www.linkedin.com/in/chikall)

**Comment by ErinOCon** [comment]
Hi @Agin-DropDisco, This microgrant has been approved! Can you provide an email address to confirm payment details?

**Comment by Agin-DropDisco** [comment]
@ErinOCon thank you much :) 
Email: gin.dropdisco@gmail.com

**Comment by Agin-DropDisco** [comment]
We received the funds. Thanks alot filecoin team. 
Next we will rebrand/rename and merged ZooHarmony to Zonulet [ https://zonulet.io ].

**Two milestone completed (Launching a feature-complete product on mainnet/testnet and contract audit)** 
**1. Contracts Audited ($ 3.5K)** 
- [x] https://github.com/zonulet-io/Audit-Contracts
**2. Hosting ( $1 ~ $3K )**
- [x] Digital Ocean
- [x] Pinata
- [x] Cloudflare
- [x] Amazon
