### ISSUE TITLE
Next Step Microgrant: multichain-cloud

### ISSUE THREAD

**Issue by shepherliu** [filecoin-project/devgrants#646]
### 1. What is your project? (max 100 words)
    Multichain-cloud is is a web3 cloud dapp which you can easily manage your files and folders and even websites by using the distributed storage.

    This is a web3 cloud dapp which you can easily upload your files and folders and even websites to the distributed storage such as Filcoin Network, Swarm Network and Arweave Network. And we use the smart contract as the file manager to search the file indexs, it is designed to be multi chains supported.

    The dapp also has a builtin NFT marketpalce called Web3NFT, so that you can mint your own nft with your uploaded images, audios and videos. And people can vote to like or dislike the nfts, and also can reward, sell and buy the NFTs so that the creators can earn through the NFTs. That is cool and representative to the future.

    https://github.com/shepherliu/multichain-cloud

    https://multichain-cloud.vercel.app/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

    The  IPFS is used for store files, folders and even websites.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

 
    1. Multi Chain Full Support.
    
    2. Swarm Storage Full Support.
    
    3. Arweave Storage Full Support.
    
    5. File/Folder Encrypt And Decrypt Support.
    
    6. Enhance NFT and DAO usage.
    
    7. User Friendly Design. 

### 4. Is this project open source?

    This project is an open sourceproject with GPL V3 License.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

    Yes

### 6. Does your proposal comply with our Community Code of Conduct?

    Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

    https://gitcoin.co/hackathon/Rollathon/projects/15097/polygon-cloud

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

    shepher liu, shepher.liu@gmail.com, https://github.com/shepherliu, manager

* How did you learn about our microgrant program?
    
    receive email from the protocol.ai to encourge me to apply for this microgrant

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
 
    https://gitcoin.co/issue/ipfs-and-filecoin/hackathons-bounties/6/100028834
     Hackathon: L2 Rollathon: a Virtual Hackathon : Storage Wizard: Best Use Of IPFS And/Or Filecoin In Your L2 Project
  
  * Please link to your hackathon submission
  
    https://gitcoin.co/hackathon/Rollathon/projects/15097/polygon-cloud

**Comment by ErinOCon** [comment]
Hi @shepherliu, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by shepherliu** [comment]
> 

shepher.liu@gmail.com

**Comment by ErinOCon** [comment]
- I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

**Comment by shepherliu** [comment]
> * I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

Yes, I have reported it with your link. If you have any questions, you can email me again.
