### ISSUE TITLE
Next Step Microgrant: HaresTech

### ISSUE THREAD

**Issue by mikhaelkamdem** [filecoin-project/devgrants#647]
### 1. What is your project? 
Mintrand is a opensource Javascript application library that allows you to mint NFTs on multiple blockchain using the IPFS storage system offered by Filecoin.

The library supports the creation of NFTs Assets on multiple Blockchain either by using an API system pre-designed by us or by using a Reactjs simplified graphical interface.

[Link to public Github repo](https://github.com/mikhaelkamdem/mintrand.git)
[Link to demo](https://194.195.244.155:3000/)

### 2. How will IPFS, Filecoin, or related technology be used for this project?

We use Filecoin's IPFS system to be able to store dynamic data from NFTs such as Images, videos and even music to produce a unique signature hash of the original file thanks to the Filecoin blockchain.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective?

To be able to improve the project we will use the grant on several aspects:
- Recruitment | We will use the Grant to recruit a frontend developer to be able to create and improve the project's interfaces. We will also need a community manager to manage the community around the project
- Infrastructure | Given that we have enormous material difficulties (old and worn laptops, electricity problems, etc.) in our country of origin, Cameroon, we will use part of this grant to improve our working conditions.
-Cloud | The last part of the Grant will be used to buy cloud servers to host our service nodes

 
### 4. Is this project open source?

The project is totally opensource.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, i Agree
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes
  
### Additional questions:
- For each team member(s), please list name, email, Github account, and role in the project.

  * Name - Mikhael Kamdem
    Email - mikhaelkamdem45@gmail.com
    Github - https://github.com/mikhaelkamdem
    Role - Lead Dev
 
  * Name - Njoya Pokam Abdelaziz 
    Email - njoyaabdelazizthierry@gmail.com
    Github - https://github.com/poclus
    Role - Dev
 
 
- How did you learn about our microgrant program?
    Friend
    Through the community forum

**Comment by ErinOCon** [comment]
Hi @mikhaelkamdem, This microgrant has been approved! Look out for an email to submit payment details.
