### ISSUE TITLE
Next Step Microgrant: Primero

### ISSUE THREAD

**Issue by Amtaf** [filecoin-project/devgrants#648]
### 1. What is your project? (max 100 words)

Primero is a decentralized educational platform and course marketplace. It is a token gated platform that revolutionizes course access and skills in developing countries. It aims to generate income for course content creators.
Github:- https://github.com/Primero-Project
Demo:- https://www.loom.com/share/3b3274be07394b15b77203e48f20b003

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

IPFS is used and will be used in this project to store NFTs
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We are planning on scaling our product which is oriented to be a web3 platform to distribute web3 content and pay creators to enable our economies to leapfrog and thrive.
Improvement of the current smart contract that generates the course NFTs. Development of Content curation modules and Dashboards.
Development of modules that Push video content to IPFS.
Improvement and enhancement of payment modules.
Creation of content to enhance web3 user experience while using our applications(explanations on how to setup wallets and How to buy courses)

 
### 4. Is this project open source?

This project is open source under the MIT license.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

We agree to share grant reports upon request.

### 6. Does your proposal comply with our Community Code of Conduct?

Our proposal complies with Filecoin's community code of conduct

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

https://twitter.com/developer_dao/status/1515016114601795585

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

| Name      | Email          | Github      |    Role     |
| ----------- | ----------- |-------------|----------|
|  Gabriela Sabate      |  gabriela.sabate@gmail.com     |                     |        Researcher/Advisor        |
| Fatma Abdulqadir    | abdulqadirfatma@gmail.com       |  https://github.com/Amtaf  |  Researcher /Developer  |
| Olubusayo Amowe   | amoweolubusayo@gmail.com | https://github.com/amoweolubusayo |Researcher/Developer  |

* How did you learn about our microgrant program?

We learnt about the grant program from the Filecoin website and Emails from protocol labs after winning the filecoin prize bounty during Web3Con hackathon

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)

web3con

  * Please link to your hackathon submission

https://github.com/Primero-Project/primero

**Comment by ErinOCon** [comment]
Hi @Amtaf, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by Amtaf** [comment]
Hello
Thank you for approving our Grant proposal,when should I expect the email with next steps?

**Comment by ErinOCon** [comment]
Hi @Amtaf! Just closing the loop on this thread. If you have any questions regarding the email we sent this week, please do not hesitate to be in touch.
