### ISSUE TITLE
Next Step Microgrant: DTube

### ISSUE THREAD

**Issue by akhileshthite** [filecoin-project/devgrants#653]
### 1. What is your project? (max 100 words)

<p align="center">
  <img align="center" src="https://ipfs.infura.io/ipfs/bafybeibomfre5a265cuszemgefkjrqtsx6tf3tl3z3a2eg7fg2grons7je/logo.png/" width="200" height="200"></img>
</p>

DTube is a decentralized video sharing & social media platform on Ethereum blockchain.

At this moment, DTube has `50 stars` and `87 forks` on github, plus it is used by hundreds of users.

GitHub: https://github.com/akhileshthite/dtube

Website: https://dtube-eth.on.fleek.co/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

DTube uses IPFS to stream videos (later, the IPFS video hashes are stored on the blockchain).
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. Integrate web3.storage for faster video streaming.
2. Work on UI/UX.
3. Add features such as video sharing, displaying uploader wallet address, etc.
4. Deploy the dapp on Ethereum mainnet.
5. Build a simple minimal "open-sourced" decentralized video sharing app. 

### 4. Is this project open source?
Yes.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

Yes.

Received `3rd prize at ETHOdyssey Hackathon` for Filecoin & IPFS track.

Submission link: https://devfolio.co/projects/dtube-c662
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Name: Akhilesh Thite

Email: [akhileshthite@hotmail.com](mailto:akhileshthite@hotmail.com)

GitHub: [@AkhileshThite](https://github.com/AkhileshThite)

Role: Main developer

* How did you learn about our microgrant program?
-> Received email after Hackathon winning.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  -> https://ethodyssey.devfolio.co
  
  * Please link to your hackathon submission
  -> https://devfolio.co/projects/dtube-c662

**Comment by ErinOCon** [comment]
Hi @akhileshthite, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by akhileshthite** [comment]
> Hi @akhileshthite, This microgrant has been approved! Look out for an email to submit payment details.

Hey @ErinOCon,
Thank you for approving this microgrant!
I haven't received the payment email yet.

**Comment by akhileshthite** [comment]
# Task ✅
<hr>
## Improve UI/UX
https://github.com/akhileshthite/dtube/commit/1cfc723fec42bcbb69e48f834e8b11ea8a3251c9

**Comment by akhileshthite** [comment]
## Task ✅

### Add features such as video sharing (IPFS gateway url), displaying IPFS CID of the video, etc.

https://github.com/akhileshthite/dtube/commit/6c695342880fc785d92a6050e2f49abb35534033

**Comment by akhileshthite** [comment]
## Task ✅

### Improve documentation

https://github.com/akhileshthite/dtube/commit/f765e4010a03d299e4b1af4889fee885e55e9277
https://github.com/akhileshthite/dtube/commit/064ca6441a4184a4b69aa43e011d9c4753ad5abf

**Comment by akhileshthite** [comment]
## Task ✅

### Integrate web3.storage

https://github.com/akhileshthite/dtube/commit/6e817ab4cb9d95ba4aab07277c9f60bb3e4e85e7

**Comment by ErinOCon** [comment]
Hi @akhileshthite, congrats on your grant progress!  The final grant report can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr) once your work is complete. Please let us know if you have any questions!

**Comment by akhileshthite** [comment]
> Hi @akhileshthite, congrats on your grant progress! The final grant report can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr) once your work is complete. Please let us know if you have any questions!

Hey @ErinOCon,
Thanks :)
Will submit the final grant report for this soon.

Can you send the final grant report submission form for DScan? or it's just the same link?
Issue: https://github.com/filecoin-project/devgrants/issues/433
Discussion thread: https://github.com/filecoin-project/community/discussions/410
GitHub: https://github.com/buidltools/dscan
Chrome web store: https://chrome.google.com/webstore/detail/dscan-decentralized-qr-co/idpfgkgogjjgklefnkjdpghkifbjenap

**Comment by ErinOCon** [comment]
Hi @akhileshthite, it's the same link!

**Comment by akhileshthite** [comment]
> Hi @akhileshthite, it's the same link!

Okay,
Thanks!
