### ISSUE TITLE
Next Step Microgrant: MadGum

### ISSUE THREAD

**Issue by oftheyear** [filecoin-project/devgrants#654]
### 1. What is your project?
Our project is MadGum, mini games platform built on Polygon blockchain with NFT collection stored on ipfs.
Our collection consists of the customizable characters. All holders will be able to claim free chips with their character on it to play for them. 

 https://madgum.io/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
We are storing our NFTs on ipfs.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will spend it on our game development, smart contract and finishing our demo version.
 
### 4. Is this project open source?
Currently no.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, we can share all grant reports
  
### 6. Does your proposal comply with our Community Code of Conduct?
 Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* oftheyear - Name - Sapabekov Madi, email - sapabekov.madi@gmail.com, Github - oftheyear, role - Co-founder, Designer
* Gamal - Name - Kubyeev Gamal, Github - Gamalg, role - Co-founder, Developer
* Marsel - Name - Gaziz Marsel, email - Marsel.ktl@gmail.com, Github - Officeman11, role - Co-founder, CEO
* How did you learn about our microgrant program?
* google
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @oftheyear, thank you for your proposal! Open source work is a key criteria point in our microgrant program. Would your team have an interest in proceeding with open source? If so, please update the proposal accordingly.

**Comment by MadGum** [comment]
Hi @ErinOCon, thanks for you respond! 
I'm Gamal, developer and co-founder of MadGum. I have the question regarding open source point.

Right now we have website, smartcontract, backend and unity projects in our company. Does it mean we have to share codebase of all our projects?

**Comment by ErinOCon** [comment]
Hi @MadGum, only the work funded by the grant would need to remain open source. Let me know if I can provide more information!

**Comment by ErinOCon** [comment]
Hi @MadGum, would you still like to proceed with the review of this grant? Please let me know if you have any questions.

**Comment by ErinOCon** [comment]
Hi @MadGum, do you expect to have an update available soon?

**Comment by oftheyear** [comment]
Hi @ErinOCon 
Yes, we will proceed with another grant reuest in two weeks approximately. Need to deal with some internal tasks.

**Comment by ErinOCon** [comment]
Hi @oftheyear, thank you for the update! To clarify, would you like to discontinue this grant request and proceed with a new one at a later date?

**Comment by ErinOCon** [comment]
Hi @oftheyear, this item has been closed. We look forward to reviewing the updated request!
