### ISSUE TITLE
Next Step Microgrant: manyverse_ipfs

### ISSUE THREAD

**Issue by xinminsu** [filecoin-project/devgrants#655]
### 1. What is your project? (max 100 words)
rich multimedia files save to ipfs: files generated from any format of pictures, audio, video, any form files
rich multimedia files update： and updated to the existing nft

https://github.com/xinminsu/manyverse_ipfs

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
rich multimedia editors new save and open features : save to ipfs, load from ipfs
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1)  markdown project
a. add ipfs save and ipfs  open feature in https://github.com/xinminsu/marktext
![marktext](https://user-images.githubusercontent.com/16698808/174074138-3f1723f9-30ba-4e38-9219-901b5a9b7498.png)
2) jspaint
a. add ipfs save and ipfs  open feature in https://github.com/xinminsu/jspaint
![jspain](https://user-images.githubusercontent.com/16698808/174468150-2772fb94-9ef4-4a4f-8c9f-144ea38b074f.png)
3)  video
a. add ipfs download and upload feature in https://github.com/Tenpi/Video-Player
![ideo_play](https://user-images.githubusercontent.com/16698808/174999041-dfc49e0d-66f9-4b5d-aac5-5af8f72197b7.png)

 
### 4. Is this project open source?
The MIT License.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
We will report content include progress or results of  microgrant-funded work, filecoin technical or usage guidance we used, and a description of our team experience building on Filecoin, also including any challenges or shortcomings encountered. 
  
### 6. Does your proposal comply with our Community Code of Conduct?
Our project will be in compliance with Filecoin Code of Conduct

### 7. Links and submissions
this project began at a hackathon,  https://gitcoin.co/issue/ipfs-and-filecoin/hackathons-bounties/6/100028834

**Comment by ErinOCon** [comment]
Hi @xinminsu, this grant has been approved! Can you provide an email address to confirm payment details?

**Comment by xinminsu** [comment]
Hi ErinOCon,

     Please send payment detail to ***@***.******@***.***>

Thank you.


从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年6月21日 16:17
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [filecoin-project/devgrants] Next Step Microgrant: manyverse_ipfs (Issue #655)


Hi @xinminsu<https://github.com/xinminsu>, this grant has been approved! Can you provide an email address to confirm payment details?

―

**Comment by ErinOCon** [comment]
Hi @xinminsu, thank you for your reply. Unfortunately, I wasn't able to view the email address provided in your latest comment. We will proceed by sending an email to the address provided in your profile.
