### ISSUE TITLE
Next Step Microgrant: DAOVerse

### ISSUE THREAD

**Issue by daphnecharles** [filecoin-project/devgrants#656]
### 1. What is your project? (max 100 words)

Our DAOVerse dApp enables Web3 communities (DAOs, NFT Creators and more) to gamify & personalize the process by which they onboard and incentivize new and existing community members. Our project provides an easily tailored 3D Web & VR-enabled metaverse framework that can be adopted and implemented for enhancing community engagement. 

https://github.com/sgarcia22/DAOverse

https://thedaoverse.org/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
  -NFT minting capabilities added for passport between onboarding experience & full DAOVerse utilizing Tatum API on Polygon, with assets stored on IPFS

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

 We'd love to expand our usage of FIlecoin and IPFS to help power events in DAOVerse. DAOVerse events will be engaging virtual experiences where users can connect with their DAO or web3 community members. We want to use Filecoin to store livestreaming assets and event recordings. We plan to utilize Livepeer and build a Filecoin integration on top of that.

### 4. Is this project open source?

Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  - https://showcase.ethglobal.com/ethamsterdam/the-daoverse-o8g12
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
- Daphne Charles, daphneacharles@gmail.com, https://github.com/daphnecharles, blockchain developer
- Sam Garcia, samangarc22@gmail.com, https://github.com/sgarcia22, game developer
- Jess Furman, jd@soundrevolver.com, product manager

* How did you learn about our microgrant program?
Niki Gokani from Filecoin
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
 ETHAmsterdam
  * Please link to your hackathon submission
https://showcase.ethglobal.com/ethamsterdam/the-daoverse-o8g12

**Comment by ErinOCon** [comment]
Hi @daphnecharles, This microgrant has been approved! Look out for an email to submit payment details.
