### ISSUE TITLE
Next Step Microgrant: <PensionFi - Web3 Pension Managers>

### ISSUE THREAD

**Issue by holyaustin** [filecoin-project/devgrants#657]
### 1. What is your project? (max 100 words)
A Contributoy pension scheme for web3 users. As the Blockchain ecosystem continues to grow, there is a need for web3 clients and organizations to adopt a pension scheme that will help users retire well in the future. Pension Finance was conceived to help users contribute their pension into a smart contract vault that will be invested on their behalf. The contribution will continue to yield interest for them until they retire. this is a great investment idea for one's retirement. NFT.Storage is used to store users' profiles as NFTs

[Link to public Github repo](https://github.com/holyaustin/PensionFi) 
[Link to demo or website, if applicable](https://pensionfi-1en67m.spheron.app/)) 

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
The front-end was designed with Vite and React framework. Technologies like IPFS / Filecoin were used to store users' profiles as NFT in a decentralized fashion on NFT.Storage. Users' metadata and profile images will be stored in a decentralized manner using NFT.Storage. Coinbase wallet and Wallet connect were integrated with metamask to give users a wide variety of wallets to connect with. The project was designed to be responsive so that whichever device you connect with, you will have a great user experience.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
* Writing better metadata for users' profiles and storing with nft.storage.
* Making users opt-out with ease at any time.
* Cleaning up the NFT smart contract and optimizing the smart contract for better performance
* Integrate Investment aggregator and Algorithmic interest Rate
* Also to improve the Pension reward system
* Improve the frontend to a better user interface
 
### 4. Is this project open source?
Yes, MIT+Apache.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
ETHGlobal Hackmoney2022 Hackathon
* https://showcase.ethglobal.com/hackmoney2022/pensionfi-uuczg
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Augustine Onuora, holyaustin@yahoo.com, @holyaustin – Sole developer.
* How did you learn about our microgrant program?
I was emailed about it after the hackathon
* If your project was created as part of an event or hackathon:
ETHGlobal Hackmoney2022 Hackathon
https://showcase.ethglobal.com/hackmoney2022/pensionfi-uuczg

**Comment by ErinOCon** [comment]
Hi @holyaustin, This microgrant has been approved! Look out for an email to submit payment details.

**Comment by ErinOCon** [comment]
Hi @holyaustin, I am including our [final grant report template](https://airtable.com/shrrtSlgdVvrPmAvr)) here, as well. 
Please let us know if you have any questions!

**Comment by holyaustin** [comment]
The final Grant template has been filled. Very grateful to Protocol lab and her team.

**Comment by ErinOCon** [comment]
Thanks, @holyaustin! Can you provide access to the repo for this project?

**Comment by holyaustin** [comment]
Hi,

The repo has not changed. https://github.com/holyaustin/PensionFi

thanks

Augustine





On Thursday, October 20, 2022 at 01:49:12 PM GMT+1, ErinOCon ***@***.***> wrote: 







Thanks, @holyaustin! Can you provide access to the repo for this project?
