### ISSUE TITLE
Open Grant Proposal: Better

### ISSUE THREAD

**Issue by seichris** [filecoin-project/devgrants#658]
# Open Grant Proposal: `Better`

**Name of Project:** Better Grants board

**Proposal Category:** `app-dev`

**Proposer:** @seichris

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

We aim to increase the number of high-quality grant applications the Filecoin team receives, while reducing the admin work of vetting each one by themselves.

Achieving this is a matter of **matching great ideas with great teams** that can execute them. The challenge is that
- great project or marketing ideas often get lost on Twitter feeds or Discord chats and
- great teams get lost in the noise, trying to find the most exciting challenges to work on.

Our platform
- **scales up the inflow of ideas** into Github issues and mirrors them into a natively hosted bounty page (eg. bounties.fil.org),
- where community members can vote to **surface the best ideas**,
- fund individual ideas as **sybil-resistant signal** and
- apply as builders to **implement the ideas** as part of the grant program

![Better Beta Roadmap](https://user-images.githubusercontent.com/25006584/173576109-1ec1e294-fe55-47de-b241-0ee157e872b6.JPG)

### Benefits

By hosting a Better page, **Filecoin**
- will receive more grant applications
- will be able to vet ideas more quickly and diligently
- will be able to match ideas with existing projects, benefiting from synergies
- will receive more attention and engagement on Socials from the community votes
- will end up with more useful projects built on Filecoin

**Builders** get
- a list of Filecoin-related ideas they can work on
- a sentiment signal from the community on their project idea
- a faster grants process

**Existing Filecoin-based projects** get
- a list of builders interested in working in the Filecoin ecosystem, to help their recruiting
- a list of ideas their users want to see implemented

### Risks
It’s very straightforward to set up our tool, since Filecoin already manages grant applications on Github issues. It is easy to iterate, which reduces the risks of failing.

We already deployed a demo board at https://fil.betterhq.org/, which mirrors the issues in https://github.com/better-feedback/better-fil/issues . We will help you to set up your own board in the Filecoin design language and host it at a filecoin subdomain.

Our main challenge will be feeding great project ideas into the platform, as the first leg of scaling our ‘marketplace for ideas’.

## Deliverables

Better will consist of:

- Hosted frontend
    - A kanban view with a ist of active proposals
    - Voting feature with Discord account
    - Funding feature for each issue
- Quadratic funding mechanism, if Filecoin wants to allocate a pool
- Github API that feeds UI from Github issues
- Github comment bot that updates bounty state changes
- Discord notification bot
- Twitter bot that allows anyone on Twitter to add ideas to the board by tagging it
- Proposal storage on Filecoin/IPFS
- Integrate with hackathons, job boards, accelerator and other Filecoin onboarding flows

### Milestone 1: Designs
🧑‍🤝‍🧑 Chris as designer, Philipp conducting user testing
💶 $10k
⌛ 2 weeks

- Figma low-fi and high-fi designs showing the complete user flow
- User interviews with grants participants, to get to know their needs and pain points

### Milestone 2: Github API that feeds UI from Github issues
🧑‍🤝‍🧑Aimen as full-stack coder
💶 $5k
⌛ 1 week

- Github API that allows the grants team to push Github issues to the UI, or automatically push based on issue tags
- Github bot that posts idea/bounty/proposal status updates to Github issue comments

### Milestone 3: Hosted interface
🧑‍🤝‍🧑 Chris as frontend, Aimen as full-stack coder
💶 $15k
⌛ 3 weeks

- Hosted UI that allows
    - community members to submit project ideas
    - community members to vote on their favorite ideas
    - community members to apply to work on these ideas and apply for a Filecoin grant
    - the Filecoin grants team to sort, show and hide ideas
The board could be open for anyone, or we could show/hide ideas based on certain Discord roles.
- Store proposals on Filecoin/IPFS

### Milestone 4: Quadratic funding
🧑‍🤝‍🧑 Chris as frontend, Aimen as full-stack coder
💶 $15k
⌛ 3 weeks

Quadratic funding mechanism serves as a sybil-resistant signal of value for each idea.

- UI that allows community members to fund each idea
- Allow the Filecoin team to allocate part of the grants fund to each idea based on the QF signal, similar to Gitcoin Grants.

### Milestone 5: Discord bot and Twitter bot
🧑‍🤝‍🧑 Chris as frontend, Aimen as full-stack coder
💶 $5k
⌛ 1 week

- Discord notification bot
- Twitter notification bot 
- Twitter bot that allows anyone on Twitter to add ideas to the board by tagging it

## Total Budget Requested

We're requesting a total funding of $50,000 to complete all the above milestones, and the fund will be split into:

Design, development and running the API and bot infrastructure.

## Maintenance and Upgrade Plans

Beyond scaling and streamlining the Filecoin grants program, we will use our platform to streamline onboarding flows for any Filecoin-based DAOs and DApps — From team formation for hackathons, collecting user feedback, to outsourcing development or content contributions in bounties.

Scaling our own platform will keep us maintaining the infrastructure and upgrade our frontend and API feature set.

# Team

## Team Members

Aimen: Full-stack dev https://github.com/aimensahnoun 
Chris: Design, product, frontend https://github.com/seichris https://twitter.com/chriscyph 
Philipp: User testing, product UX https://twitter.com/Philiff 
Izzy: Advising on DAO bounties and grant flows https://github.com/isidorosp 

## Team Website

https://betterhq.org/ 

## Relevant Experience

We’ve each been working on crypto projects for >4 years. Related projects include a demo of a decentralized jobs platform https://decentrajobs.aimensahnoun.com/, and a Filecoin-based Social Media DApp https://kontext-1ds9andww-kontext.vercel.app/.

Besides side projects, we are working for one of the anon bluechip DeFi DAOs, for imToken, LIDO and studying at ITU.

## Team code repositories

https://github.com/better-feedback/web
https://github.com/aimensahnoun/DecentraJobs

# Additional Information

We learned about the grants program from friends working in the same space.
chris@web3.consulting

**Comment by ErinOCon** [comment]
Hi @seichris, thank you for your proposal! While we are currently not looking to outsource this type of program work, it's great to see projects committed to making the grant process scalable. Wishing you the best on all future projects!

**Comment by seichris** [comment]
Thanks for your answer! @ErinOCon 

Our tool's main use case rn is allowing dApp communities prioritize user feedback - similar to canny.io

Even we couldn't make the grant program, I'd love to have a chat with you to see if Filecoin-based apps would be interested in using us :)
