### ISSUE TITLE
Next Step Microgrant: Docs Universe

### ISSUE THREAD

**Issue by dhi-raj07** [filecoin-project/devgrants#659]
### 1. What is your project? (max 100 words)
Docs Universe is a web based Dapp that allows to store important assets on IPFS instance. Ownership of files is securely recorded on the Ethereum blockchain making it the best platform to store assets

https://github.com/dhi-raj07/Docs-Universe
https://youtu.be/GeRm54iqMo0

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Store
>The store feature is a feature for uploading files to IPFS which is both a create operation on the application and write operation on the blockchain. 
`In the Store feature, system flow starts from the Metamask check for account selection. Furthermore, the user can perform store operation by affixing the file to the form on the web interface, the application then converts the file into a buffer, user confirms the transaction and proceed with storing the file to IPFS. As output, the user will get information in the form of file hash and transaction hash.`

Owership
>The ownership feature can check the ownership of the uploaded file while allowing users to be able to retrieve files that have been saved, this is an implementation of read operations on the application and on the blockchain. 
`Furthermore, the functionality of the Ownership feature is also started by checking the Metamask account. Followed by the choice of whether the user wants to check the ownership of a file or not. If so, the user can add the file that he wants to find out the owner of, but if the user does not want to check the ownership then the user can continue with the file retrieval feature. In the file retrieval feature, users only need to click the “Retrieve” button to retrieve the files they own.`

Transfer
>The transfer feature allows users to be able to make ownership transfers of files that have been previously stored, this illustrates the implementation of update operation on the application and write operation on the blockchain.
`As in the previous features flow, the Transfer feature also starts with a Metamask account check. Then users who wish to transfer ownership of their files can provide information on the destination account to be transferred, followed by confirming the transaction. The end result of this feature is the loss of the file entry that has been transferred and the receipt of the transfer transaction hash as proof that the ownership has been transferred.`
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Currently , I'm perusing my bachelor's degree in Computer Science right now I'm in third year of it. From this grant I'll work on its frontend part as I'm coming from backend background. Also various features I need to implement in existing project such as WalletConnect etc. There are various paid services are also need to be implemented in project for making it fluent and smooth.
All this things are just thought unless and until it is not on Mainnet for the major part of grant will used for transaction and gas fee.
Also more interesting ideas are yet come for Docs Universe.

 
### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes

  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
https://devpost.com/software/docs-universe
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Dhiraj Bari
Email: dhiru9bari@gmail.com
Github: https://github.com/dhi-raj07/
Role: This is my project I am solo in this project. I (Dhiraj Bari) worked as both front-end and blockchain developer. It was my first time with IPFS and truffle, which was bit challengeable, but I learn a lot.
* How did you learn about our microgrant program?
Mail from niki.gokani@protocol.ai as I've won Faber Web3 Hackathon

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
      Faber Web3 Hackathon
  * Please link to your hackathon submission
      https://devpost.com/software/docs-universe

**Comment by dhi-raj07** [comment]
@ErinOCon Is there any problem in project?

**Comment by ErinOCon** [comment]
Hi @dhi-raj07, this microgrant has been approved! Look out for an email to submit payment details.

**Comment by dhi-raj07** [comment]
Thanks @ErinOCon
