### ISSUE TITLE
Next Step Microgrant: SkillBlock

### ISSUE THREAD

**Issue by Drexter-07** [filecoin-project/devgrants#660]
### 1. What is your project? (max 100 words)
Hire nearest helper using cryptos. A DAO which helps both the public to search and hire nearest laborers/helpers and also the workmen/helpers to register themselves on the site to get rewarded for their service. Workmen will enter the required details. Storing the profile image from workmen device into IPFS and getting the URL. Also get the location of the workmen using Google Maps. Handling secure payments using blockchain with several wallet options. 

Link to public Github repo: https://github.com/PaLangCODE/SkillBlock

Link to demo or website: http://skill-block.vercel.app/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Decentralized uploads of media into IPFS and generating URL of it and fetching the same through React Moralis and displaying it in the bookings page of all service experts.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Major Changes in the UI/UX: 
1. Adding new sections like reviews, profile page, contacts us. 
2. Providing social links.  
3. Detailed interactive tutorial guide to use our DAO service.
4. Support for various platforms like Windows, iOS, Android and Linux etc.
5. Better user experience by integrating animations and responsive design.

- Exploring and using the flexibility of IPFS that lets us use its services through different softwares like Moralis by: 
- Engaging in IPFS usage through Moralis for users/community to use and explore IPFS technology through Moralis.
- Storing more details of workmen using IPFS. 
- Fetching cover image url stored in IPFS using React Moralis. 
- Updating realtime user data dashboard with Moralis database fetching various details through IPFS and smart contracts on polygon blockchain. 
- Purchase of Moralis server for using new features to integrate in our DAO.
- Google Cloud Credits for handling increased traffic through paid APIs, like Google Maps.
- Further enhancements like integrating NFT avatars through IPFS in our DAO in near future.

 
### 4. Is this project open source?
Yes, under MIT License.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* Gitcoin L2 Rollathon: Runner Up in IPFS/Filecoin category
* Submission link : https://gitcoin.co/hackathon/Rollathon/projects/15317/skillblock
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

 1. Sahil Siddhant
 Email: sahilsiddhantofficial@gmail.com
 Github: https://github.com/Drexter-07
 Role: Blockchain Developer

 3. Madhav Choudhary
 Email: madhavchoudhary0911@gmail.com
 Github: https://github.com/D5D0Ds
 Role: Backend Developer

 5. Piyush Alankar
 Email: piyushalankar251@gmail.com
 Github: https://github.com/piyushalankar251
 Role: UX, Frontend Developer

 6. Priyanshu Verma
 Github: https://github.com/Ghst-dg
 Role: Design UI, Frontend Developer.
 
* How did you learn about our microgrant program?
  Email from Niki Gokani, Ecosystem Growth at Protocol Labs.
<img width="705" alt="image" src="https://user-images.githubusercontent.com/59890906/173631858-34c6aeb3-f90d-4d10-ae40-40cf800707f5.png">

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
   Gitcoin L2 Rollathon 2022 hackathon.
  * Please link to your hackathon submission 
   https://gitcoin.co/hackathon/Rollathon/projects/15317/skillblock

**Comment by ErinOCon** [comment]
Hi @Drexter-07, this microgrant has been approved! Look out for an email to submit payment details.
