### ISSUE TITLE
Filecoin interoperability learning module

### ISSUE THREAD

**Issue by AllanMangeni** [filecoin-project/devgrants#662]
### 1. What is your project? (max 100 words)
Our project aims to strengthen and expand the use case of Filecoin by building an interoperability learning module and also have a bootcamp to educate developers about the Module. Interoperability is a core aspect when building web3 projects and we aim to build various use cases based on IPFS, Filecoin and how they can work with other Web3 frameworks/architectures. 

https://github.com/wengiweb
https://app.eduflow.com/join/no-session/J6WBXT

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
IPFS will be used to educate Developers on how they can build Applications and host them on IPFS
nft.storage will be used to educate people on how they can store NFT metadata and mint their NFTs on Bitcoin via https://heylayer.com/
Use case on EVM and FVM compatibility.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

* Milestone 1: Draft the learning module on eduflow
* Milestone 2: Invite beta testers to access and test out the learning module as we prepare for a public launch of the module
* Milestone 3: Do a public launch and make the course public allowing anyone to learn about Filecoin interoperability with other Web3 frameworks
* Milestone 4: Create a bootcamp whereby wer will have developers learn and help expand more ineteroperability posibilities with Filecoin and other Web3 projects.
 
### 4. Is this project open source? yes, the project will be open source.
MIT

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes

  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
Our previous learning modules
https://app.eduflow.com/join/no-session/J6WBXT

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Project lead: Allan Mang'eni
email: allan@wengiweb.com
Github: https://github.com/allanmangeni
* How did you learn about our microgrant program?
Referral
* If your project was created as part of an event or hackathon:
  *Our project was not created as part of an event or hackathon but it was more of a thought process on how we can make Filecoin ecosystem more accesible to other Web3 projects.

**Comment by ErinOCon** [comment]
Hi @AllanMangeni, thank you for your proposal! Can you provide a working Github link?

**Comment by AllanMangeni** [comment]
https://github.com/Wengi-web - This is the link to our organization. However, the courses we develop are uploaded on https://eduflow.com. Eduflow is well suited to gather feedback, track progress and evaluate learners who will use the interoperability learning module.

**Comment by ErinOCon** [comment]
Hi @AllanMangeni, this grant has been approved! As a part of your final report, please incorporate the impact of your learning module and bootcamp. 

We will send an email to confirm payment details.
