### ISSUE TITLE
Next Step Microgrant: Unstoppable Clubs

### ISSUE THREAD

**Issue by 0xmaeve** [filecoin-project/devgrants#663]
### 1. What is your project? (max 100 words)

Creators can create clubs where people can become members and have access to exclusive content. Everything is decentralised and encrypted. No one can censor anything.

This project uses,

- ReactJs to design the frontend and javascript for backend
- IPFS textile for storing metadata
- Polygon network for deploying a smart contract

Public Repo: https://github.com/0xmaeve/unstoppableClubs

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
We use metamask for public-private key encryption. Files are encrypted with AES-CBC and the encryption key is then encrypted with member public keys and stored on IPFS using textile. The unlock Protocol is used to keep track of memberships and each club is modelled as a lock. We also have a smart contract that mints each content post as an NFT and keeps track of their location in Textile.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

First of all, I want to improve UI for error flow and micro-interactions, little bugs and easy flow for consumers. Redesign the structure of the whole process of application and wanted to add some more features like

- Searching and filtering for creaters
- Accepts tip multichain and various methods
- Preview of files in the user dashboard.
- Make club more secure

Deploy it to mainnet and more things.

### 4. Is this project open source?

Yes, This project is under MIT License

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  Yes, I agree to share updates and grant reports.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes, I have submitted for IPFS prizes

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.: 
  Name: Maeve
  Email: maevecode07@gmail.com
* How did you learn about our microgrant program? : I have received mail for Apply for Next step grant
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum): Devfolio Ethernals
  * Please link to your hackathon submission: https://devfolio.co/projects/frais-1b6e

**Comment by ErinOCon** [comment]
Hi @0xmaeve, this microgrant has been approved! Look out for an email to submit payment details.

**Comment by 0xmaeve** [comment]
Hey @ErinOCon, Thanks for approving my project! but I didn't receive an email to submit payment details.

**Comment by ErinOCon** [comment]
Hi @0xmaeve, closing the loop here to confirm the kick off email was sent. Let me know of any questions!
