### ISSUE TITLE
Next Step Microgrant: DStack Protocol

### ISSUE THREAD

**Issue by stackprotocol** [filecoin-project/devgrants#665]
### 1. What is your project? (max 100 words)
DStack is an open source decentralized storage protocol that supports the AWS Standard. DStack will distribute data stored based on the AWS S3 standard in IPFS. It supports IPFS mainet and private networks by the deployment of IPFS nodes. Our goal is to make the life of a developer easier

Github: https://github.com/stackprotocol/DStack
Website: https://dstack.webflow.io/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

DStack Protocol is powered by IPFS
Current use cases of IPFS for DStack are as follows:

*1. Decentralized storage - Store and access data across several servers without a hitch*

*2. Storing metadata - Your contact list, file sizes, and directory structure can never be seen, even by us*

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
If DStack receives the grant the team will begin working towards the completion of our roadmap which involves:

IPFS Enhance security measures (25th June, 2022)
E2E Testing (July 15th, 2022)
Code Audit (July 30th, 2022)

Since we are working full time and have other responsibilities as well we are actively looking to hire developers to work with us and would also be looking to seek guidance on our project from team Filecoin as we are building directly to promote IPFS culture amongst developers.

Any financial aid from Filecoin/IPFS would allow us to devote more time to continue building DStack.
 
### 4. Is this project open source?
DStack Protocol is a completely open source project.
The project has license for content (MIT).

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes indeed!, We have also published a road-map (https://github.com/stackprotocol/DStack/blob/main/README.md) which throws light on the product timeline.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes! DStack Protocol complies with the Filecoin Community Code of Conduct. We have experience in building for Web3.

### 7. Links and submissions
The project began after seeing the reliance on centralised storage solutions around me. / NOT a part of a hackathon
Twitter - https://twitter.com/DStackprotocol
  
### Additional questions:

Alex Ferguson - Head Of Tech
Contact - dtsackcto@gmail.com
Github - https://github.com/stackprotocol

Gauri Dogra- Head Of Product
Contact - gauridogra2@gmail.com
Github - https://github.com/gauritech

How did you learn about our microgrant program?
Briefing session - Superteam DAO (Bangalore)

**Comment by stackprotocol** [comment]
Hey any update on this? @ErinOCon

**Comment by ErinOCon** [comment]
Hi @stackprotocol, this microgrant has been approved! Look out for an email to submit payment details.

**Comment by stackprotocol** [comment]
@ErinOCon Our team here at DStack thanks the file coin organization wholeheartedly!

**Comment by ErinOCon** [comment]
Happy building, @stackprotocol!

**Comment by stackprotocol** [comment]
@ErinOCon We had applied for the grant request on the 4th of July and we haven't received the funds yet just wanted to confirm what is the average time of fund release? Or should we apply for the transfer request again?

**Comment by stackprotocol** [comment]
@ErinOCon Hi hope you are doing good! We had applied for the grant request on the 4th of July and our request hasn't yet been approved for the funds just wanted to confirm what is the average time of fund release? Or should we apply for the transfer request again? Our building plans have slowed down due to this.

**Comment by ErinOCon** [comment]
Hi @stackprotocol, thank you for checking in. There shouldn't be a need to resubmit the request. I'll connect with our team and circle back by email.

**Comment by stackprotocol** [comment]
Thanks! Much appreciated

**Comment by ErinOCon** [comment]
Hi @stackprotocol, I hope you are doing well! Can you submit the grant report for this project? The report template can be found [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by gauritech** [comment]
> Hi @stackprotocol, I hope you are doing well! Can you submit the grant report for this project? The report template can be found [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

Hi @ErinOCon we are doing well and wishing the same for you. We will be submitting the grant report within the next 24 hours. Thanks!
