### ISSUE TITLE
Next Step Microgrant: Prezents (L2E Dapp)

### ISSUE THREAD

**Issue by heypran** [filecoin-project/devgrants#666]
### 1. What is your project? (max 100 words)
Prezents is a learn to earn dapp, where individuals and companies can create quizzes, tasks and campaigns to educate users and market their product. 

Demo Website - https://quiz-dapp.web.app/
WIP Website - https://prezents.xyz/
Github - https://github.com/heypran/prezents-contracts , https://github.com/heypran/prezents-ui 
Old Hackathon repo - https://github.com/heypran/blockchain-game
https://youtu.be/nIAMJQLiEKQ

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

Currently, it uses web3 storage for creation/storing quizzes. It will also be used to store tags, relevant campaign data when these features are introduced.  

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. Improvement of existing UI
2. Improve user flow for quiz creation, quiz management dashboard
3. Launch Beta on mainnet  

### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
Submission Link to Gitcoin Rollathon 2022 - https://gitcoin.co/hackathon/Rollathon/projects/15135/a-game-using-web3-storage
Winner of Creative Ninja Category for IPFS - Gitcoin Rollathon 2022 

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Pran
Github- @heypran
Role - Founder
Email - p*******a@gmail.com-  already with the filecoin team ( as I received the email)
* How did you learn about our microgrant program?
Email from IPFS team as a winner in one category.
Gitcoin Rollathon 2022 
https://gitcoin.co/hackathon/Rollathon/projects/15135/a-game-using-web3-storage

**Comment by ErinOCon** [comment]
Hi @heypran, this microgrant has been approved! Look out for an email to submit payment details.
