### ISSUE TITLE
Next Step Microgrant: Rapid Ticketing Marketplace(RTM)

### ISSUE THREAD

**Issue by EmperorRP** [filecoin-project/devgrants#669]
### 1. What is your project? (max 100 words)

A ticket booking platform where organizations can generate their own tickets or customers can buy the tickets. These tickets will contain information about the seat number, price, names, etc. The tickets can also be **generated and bought in mass**. Every ticket is an NFT and can be bought, sold, and traded on our platform. The setup is in 3 simple steps and we make it so that it is extremely fast, reliable, and very easy.  This is all done with the help of the trade of Ether(ETH) and could be backed by Polygon and Ethereum.

[Rapid Ticketing Marketplace Github](https://github.com/EmperorRP/hacknitp-CryptoCoolDudes)
 

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Storing data such as description, price, images, and other relevant info regarding the tickets(NFTs) is stored in IPFS.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- Improving the website and contracts
- Building better UI/UX 
- Deploying in mainnet and hosting
- Improving the mass upload feature

 
### 4. Is this project open source?

Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?

  Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  [Hackathon Submission](https://devfolio.co/projects/rapid-ticketing-marketplace-rtm-ec72)
Filecoin Track Prize
Received the prize for the track Filecoin & IPFS at HackNITP

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

      Sai Leela Rahul Pujari
      Email - sai20401@iiitd.ac.in
      Github - EmperorRP
      Role - Product Lead
      
      Asim Jawahir
      Email - asimjawahir123@gmail.com
      Github - CommanderAstern
      Role -  Full Stack Developer, Contract Developer
      
      Nevan D'Souza
      Email - nev.kd2832@gmail.com
      Github - nevan-dsouza
      Role -  Full Stack Developer

* How did you learn about our microgrant program?
We were emailed from Protocol.ai. They said they liked our project and sent us links to the microgrant program.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
   [HackNITP Hackathon](https://hacknitp.devfolio.co/)
  * Please link to your hackathon submission
 [Hackathon Submission](https://devfolio.co/projects/rapid-ticketing-marketplace-rtm-ec72)

**Comment by ErinOCon** [comment]
Hi @EmperorRP, this microgrant has been approved! Look out for an email to submit payment details.
