### ISSUE TITLE
Next Step Microgrant: Ethereum: The Tribe

### ISSUE THREAD

**Issue by danielmcclure** [filecoin-project/devgrants#670]
### 1. What is your project? (max 100 words)
Ethereum the tribe is an NFT project that creates trading card style NFTs featuring on chain acheivements of their owners and stores them on IPFS. 

https://github.com/danielmcclure/ethereum-the-tribe

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

IPFS will be used to host the digital assets and in the initial version they are uploaded via NFT.storage
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

I will finish the ENS integration, upgrade the designs, and as a stretch goal set up a decentralised website to mint the prohect that is fully hosted on IPFS. I'll also set up a node to pin all of the above.
 
### 4. Is this project open source?

MIT or similar if requirements change based upon used libraries. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

I won a prize at ETHGlobal NFT Hack 2022 though didn't receive it here:

https://showcase.ethglobal.com/nfthack2022/ethereum-the-tribe
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Daniel McClure and you have my email.

* How did you learn about our microgrant program?

You invited me to apply. 

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)

ETHGlobal NFT Hack 2022

  * Please link to your hackathon submission

https://showcase.ethglobal.com/nfthack2022/ethereum-the-tribe

**Comment by ErinOCon** [comment]
Hi @danielmcclure, this microgrant has been approved! Look out for an email to submit payment details.
