### ISSUE TITLE
Next Step Microgrant : PinBox

### ISSUE THREAD

**Issue by callmejakskys** [filecoin-project/devgrants#673]
### 1. What is your project? (max 100 words)
Pinbox is a cross-platform collection tool that you can use to jot down inspiration, read later, save material, and even anything on the web and all data will store in IPFS/Filecoin.

Here's a web2 app similar to what we want to do, but ours is more web3：https://withpinbox.com/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
We will use nft.storage to store short text data such as URL tags, and web3.storage to store large data such as pictures, articles, etc. By binding IPFS/Filecoin, we can store these data permanently, and can store these data in different Export/Import between wallets

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will use this than grant to support our developers in completing the first version of the project，At the same time, if there is more money, we will invite all kol to use our project and promote our project
 
### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
No, but we will join in the future.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
   jake, Product design and project organizer ，callmejakskys@gmail.com
  
* How did you learn about our microgrant program?
  Seen from the ipfs community

We would very much like to receive funding from Filecoin to support our project launch. We believe that the entire project has very strong practicality and will provide a good help to promote the IPFS/Filecoin ecosystem.

**Comment by ErinOCon** [comment]
Hi @callmejakskys, thank you for your proposal! Is there a Github repo or a link to your code that is available to review?

**Comment by callmejakskys** [comment]
> Hi @callmejakskys, thank you for your proposal! Is there a Github repo or a link to your code that is available to review?

Hi @ErinOCon ! We have not yet done code coding, and the team is still in the stage of requirements sorting. We hope the Filecoin Foundation can support us in starting this project, we are still short of developers.

**Comment by callmejakskys** [comment]
Hi @ErinOCon , I want to know what's going on ?

**Comment by callmejakskys** [comment]
Hi @ErinOCon , I would like to ask what is the progress ? In fact, in our daily life, there will be many favorite websites, articles, etc., but is there a free persistent Pin tool for us to use? What we want to do is this tool to save all user favorites link, content, data.Looking forward to your reply, and hope that with the support of PL, we can accomplish what we want to do.

**Comment by ErinOCon** [comment]
Hi @callmejakskys, I will have an update available this week. Thank you for your patience!

**Comment by ErinOCon** [comment]
Hi @callmejakskys, can you confirm the building steps you will take in the first version of your project? Specifically, the steps that will take place over the next three months?

**Comment by callmejakskys** [comment]
> Hi @callmejakskys, can you confirm the building steps you will take in the first version of your project? Specifically, the steps that will take place over the next three months?

hi @ErinOCon , We divide the next 3 months of development into 3 phases:
### Phase I : Basic functions of the user data storage system

- User UI/UX design and implementation
- The establishment of user data index system based on textile.io
- Different types of user data database establishment ( web pages, pictures, ideas and code snippets )

### Phase 2 : Mainly related to data storage functions

- Integrate with nft.storage and synchronize data to user data system
- Add data/data collection mint nft function (provide users to share or sell their collections)
- More login options integration (github, email, web3 wallet )
- Integrate with third-party content platforms, such as music, video content

### Phase 3 : Improve details

- Comprehensive testing, including different data uploads ， contract test 
- Add functions such as data search
- Focus on privacy ( Your data is only visible to you)
- Import/Export and Backup (using download to local or  pin to more Filecoin nodes)

We will start in 3 stages sequentially

**Comment by ErinOCon** [comment]
Thanks, @callmejakskys! I will circle back with an update next week.

**Comment by callmejakskys** [comment]
> Thanks, @callmejakskys! I will circle back with an update next week.

Hi @ErinOCon , okay! waiting your message !

**Comment by callmejakskys** [comment]
> > Thanks, @callmejakskys! I will circle back with an update next week.
> 
> Hi @ErinOCon , okay! waiting your message !

Hi @ErinOCon , any update?

**Comment by ErinOCon** [comment]
Hi @callmejakskys, thank you for your patience with our review. We will not be moving forward with a grant at this time as the microgrant program is intended to support projects that already have a working prototype. As a next step, we would highly recommend proceeding with this project at a hackathon. Once your project has progressed further, we would be happy to reconsider the grant.
