### ISSUE TITLE
Next Step Microgrant: <AllTrueVision Studios Grant App>

### ISSUE THREAD

**Issue by AllTrueVision** [filecoin-project/devgrants#675]
### 1. What is your project? (max 100 words)

        AllTrueVision is a collaborative app for creatives to build original narrative projects in Augmented Reality. We aim to democratize multimedia content by encouraging creative exploration, our tool aims to help normal people recognize untapped talent and potential through impromptu collaborative challenges. Each challenge will produce original storylines and frameworks which will offer the opportunity for players to swap their experiences and assets created during the experience for in-game currency which can be cashed in for dollars. The app will be an NFT marketplace which, leverages the Polygon SDK to deliver this unique experience to users and opens the opportunity for continual iteration on previous projects.  

https://github.com/AllTrueVision?tab=repositories

I would like to use the grant to create an MVP. Link to Pitch: 
https://bafybeigx3rvf3zlug2s7lcdpcefloqcdcuexk2pbtmnpwajlwroncbze3a.ipfs.nftstorage.link/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
  IPFS/Filecoin will be used to sustain the backend of our ecosystem via Estuary.We will need to hold the structure of the website itself and facilitate the exchange of ownership of the NFTs. Since our site is 3D and will encourage the integration of teamwork in an Augmented Reality environment it will need a comprehensive backend. Think Spatial.io if it were on 8thwall with the functionality of Google Teams.  

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Our next steps include recruitment of developers to contribute to the project, testing with potential clients and deployment of our MVP.
 
### 4. Is this project open source?

Yes. This iteration will be open source, for the grant's purposes.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes I will share all required reports and documentation upon request. Including final grant report at the end of the three month period. 

  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes my proposal is in compliance. 

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
NON APPLICABLE.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @AllTrueVision, this microgrant has been approved! Can you provide an email address to confirm payment details?

**Comment by AllTrueVision** [comment]
YYYYYYYYAAAAAAAYYYYYYYYY!!!!!!!!!!!!!!!!!
allseeing1dog@gmail.com

**Comment by AllTrueVision** [comment]
Hello @ErinOCon I just wanted to follow up having provided my email. Is there anything else you need? What are the next steps that need to be taken?

**Comment by ErinOCon** [comment]
Hi @AllTrueVision, an email has been sent to the provided address!
