### ISSUE TITLE
Next Step Microgrant: Aegis

### ISSUE THREAD

**Issue by maverickamit** [filecoin-project/devgrants#677]
### 1. What is your project? 
Aegis is a transparent, decentralized platform to support creators. Supporters of a creator will be able to stream money continuously to the creator and get access to excluside paid content. This will enable creators to get monetary support directly from their fans, without a middleman taking a cut.
https://github.com/0xaegis
https://aegis-landing.netlify.app
https://aegis-staging.netlify.app

### 2. How will IPFS, Filecoin, or related technology be used for this project? 
 Posts with attachments that are not marked paid will be free for everyone to download. The attachments will be uploaded through Web3.Storage which uses IPFS and will be open to anyone to view and download. 

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We implemented the paid content feature using Arcana. But due to various limitations with using Arcana, we are now planning to upload the paid content through IPFS and implement an encryption feature which will restrict access to only paying supporters.
Furthermore, we plan to implement Lens Protocol in future for the underlying infrastructure. The grant money will be of help paying for developer hours needed to implement these features. 

### 4. Is this project open source?
Yes, the project code have an MIT license. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, I agree.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* **If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:**
* Winner at Ethernals, India's biggest hackathon, one of the top 10 projects.
* Aegis was also selected for Filecoin pool prize. 
* https://devfolio.co/projects/aegis-9c2b
  
### Additional questions:
* **For each team member(s), please list name, email, Github account, and role in the project.***
* Name: **Amit Ghosh**
Email: amitdgpghosh@gmail.com
Github: https://github.com/maverickamit
Role: Lead Developer (React+Solidity)

* Name: **Sumit Ghosh**
Email: hi@sumit-ghosh.com
Github: https://github.com/SkullTech
Role: Lead Developer (React+Solidity)

* **How did you learn about our microgrant program?**
 Through the official email sent from the hackathons team of Filecoin / IPFS at ETHernals.
* **If your project was created as part of an event or hackathon**:
  * **What was the name of the event?**
  * Ethernals, https://ethernals.devfolio.co
  * **Please link to your hackathon submission**
  * https://devfolio.co/projects/aegis-9c2b

**Comment by ErinOCon** [comment]
Hi @maverickamit, this microgrant has been approved! Look out for an email to submit payment details.
