### ISSUE TITLE
Next Step Microgrant: EarthMMO

### ISSUE THREAD

**Issue by thomas-vu** [filecoin-project/devgrants#678]
### 1. What is your project? (max 100 words)
EarthMMO is an augmented reality mobile game using web3 technologies to bring concepts found in traditional MMO games into the real world. Players can earn NFT items by attending events and completing quests in the real world. These NFT items can be upgraded and equipped to customize a digital avatar which represents you.

<img src="https://user-images.githubusercontent.com/22990196/174417443-1161f4c0-2720-46ed-a878-e7d5bdbbe706.PNG" width="321" height="694" />

https://github.com/EarthMMO/mobile-app
https://github.com/EarthMMO/web-app
https://github.com/EarthMMO/api
https://www.earthmmo.com

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
We store all the images for the NFT items on IPFS.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will use part of the grant to commission art for the project, starting with a customizable human avatar and an initial set of items and gear to demonstrate the core concept. We have already found an artist willing to create the initial art and this grant would allow us to compensate them. The rest of the grant will be used to compensate other team members and to pay for server costs. We aim to launch the mobile app to iOS and Android by the end of the grant period.
 
### 4. Is this project open source?
Yes, under the MIT License.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
This project began at the ETHAmsterdam hackathon under the name "Looking for Party", where we ended up winning the **_🚀 Optimism — Just Deploy!_** prize. We have since expanded the scope of the project and renamed it to EarthMMO.
https://showcase.ethglobal.com/ethamsterdam/looking-for-party-uh99e
  
### Additional questions:
* **For each team member(s), please list name, email, Github account, and role in the project.**

  Name: Thomas Vu
  Email: thomazvu@gmail.com
  Github: https://github.com/thomas-vu
  Role: Founder / Engineer
  
  Name: Rowan Sommerfeld
  Email: rowan.sommerfeld@gmail.com
  Github: https://github.com/AwsumSawse
  Role: Operations

* **How did you learn about our microgrant program?**
We pitched to the IPFS sponsors at ETHAmsterdam and they recommended that we apply for this microgrant. We then got a follow-up email encouraging us to apply and that one of them really liked what we built.

* **If your project was created as part of an event or hackathon:**
  * **What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)**
      ETHAmsterdam
  
  * **Please link to your hackathon submission**
  https://showcase.ethglobal.com/ethamsterdam/looking-for-party-uh99e

**Comment by ErinOCon** [comment]
Hi @thomas-vu, this microgrant has been approved! Look out for an email to submit payment details.
