### ISSUE TITLE
Next Step Microgrant: <BHealth>

### ISSUE THREAD

**Issue by hakymulla** [filecoin-project/devgrants#680]
### 1. What is your project? 

The project brings healthcare data from standard databases - such as PostgreSQL - to the on-chain space, by leveraging the use of Chainlink API features. Initially, this data will be stored on IPFS and FileCoin's OrbidDB. This way, we can guarantee the security and privacy of the data, giving more control to the patient, as he can see at any time who has access to it.

This has no effect on the old systems, as hospital staff can keep using legacy databases. The connection using Chainlink simply enables a more cryptographic-proven management of sensitive data. It can also serve as a platform to build web3 health-applications.

https://github.com/hakymulla/ChainLink_Hackathon_2022

https://youtube.com/playlist?list=PL3iwl7dh_omgg-_-HXWftnTGnrKewkOVG

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
  
IPFS based OrbitDB is used to store health care data which is pulled from relational database like postgres.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

A full fletched smart contract to handle the following scenerios:
1. Visit several hospital to deteremine the structure of their database (dtabase schemas).
2. Patients can give access or revoke physicians/doctors access.
3. Physicians gives limited and required access to nurses, pharmacists, therapists etc.
4. Study and apply Lit Protocol for decentralized identity-based encryption and access control. Depending on how easy it can be implemented i might switch to Zero Knowledge proof (which i have been studying for the past few months)
5. Build a front end.

### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
 Yes.

### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

YES, ChainLink Hackathon 2022.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Kazeem Hakeem, www.github.com/hakymulla, owner/developer

* How did you learn about our microgrant program?
Filecoin & IPFS Hackathons team mail

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
Chainlink Spring 2022 Hackathon

  * Please link to your hackathon submission
  https://devpost.com/software/bhealth?ref_content=user-portfolio&ref_feature=in_progress

**Comment by ErinOCon** [comment]
Hi @hakymulla, this grant has been approved! We will send you an email to discuss payment details.
