### ISSUE TITLE
Next Step Microgrant: Memo IPFS

### ISSUE THREAD

**Issue by Carlavanos** [filecoin-project/devgrants#681]
### 1. What is your project? (max 100 words)
Fast and easy storage to IPFS for mobile or PC images and text, to send and save memo links for future reference. When you store your memo on https://memodapp.xyz/ , MemoDapp will save them on an immutable and secure blockchain called IPFS. IPFS generates a unique address which we use in generating a preview and to save this memo link for future reference.

https://github.com/Carlavanos/memo
https://memodapp.xyz/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
MemoDapp is about fast and easy storage to IPFS for mobile or PC images and text, to send and save links for future reference. It has very simple UI.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
This is just first prototype but stay tuned for the upgraded versions! There are some minor-bugs we need to fix and we need to apply several new key improvements (as mentioned on the website) that will take several weeks of prime dev time.
 
### 4. Is this project open source?
Yes it is.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
No  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Carla Van Os, carla@memodapp.xyz , Dev.
* How did you learn about our microgrant program?
via filecoin website.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
No - N/A

**Comment by ErinOCon** [comment]
Hi @Carlavanos, thank you for your proposal. [IPFS](https://docs.ipfs.io/concepts/what-is-ipfs/#decentralization) actually isn't a blockchain. It is a distributed system for storing and accessing files! For next steps, we would recommend building out your prototype at a hackathon. It may also be helpful to consider [Web3.storage](https://web3.storage/) in your building plan. 

Once more building progress is underway, please feel welcome to re-apply.!
