### ISSUE TITLE
Next Step Microgrant: <WebCryptoAPI>

### ISSUE THREAD

**Issue by WillyAstor** [filecoin-project/devgrants#682]
### 1. What is your project? (max 100 words)
2file is a filesharing service built on Filecoin and IPFS that allows encryption and sending of files and enhances privacy and control by using blockchain. 2file is using WebCryptoAPI to encrypt the files, each file is encrypted locally in your browser using AES-GCM algorithm.

https://github.com/WillyAstor/WebCryptoAPI
https://2file.xyz/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
2file uses Web3.Storage technology to store the files using FileCoin deals and distribute them using IPFS. The files are distributed on a decentralized network making it censorship resistant.
2file is a filesharing service built on Filecoin and IPFS.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
More improvements and to expand on https://estuary.tech/ .
We are planning many improvements starting with UI updates and focusing on improving and adding several more functionalities.
 
### 4. Is this project open source?
Yes, MIT

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Willy Astor, dev@2file.xyz , Chief Dev
* How did you learn about our microgrant program?
Social media
* If your project was created as part of an event or hackathon: 
N/A
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
This microgrant has been approved! For next steps, we will be in touch by email to discuss payment details.
