### ISSUE TITLE
Communities of Care-ful Learning

### ISSUE THREAD

**Issue by andytudhope** [filecoin-project/devgrants#683]
# Open Grant Proposal: 

**Kernel**

**Proposal Category:**  `community`

**Proposer:** @andytudhope @vs77bb

**Technical Sponsor:** James Tunningley, Sonia John

We have already open sourced all our work. We solemnly undertake to continue this practice, generally using the MIT license.

# Project Description

Kernel is a core web3 good. We have created an open source syllabus and guided six cohorts of 250-430 people through it over two years. One of these cohorts, or “blocks”, was called [Apollo and was done in partnership with Filecoin](https://filecoinproject.slack.com/archives/G019VS1QDAN/p1598967392000200). 

More than 1400 people have adventured through our peer-learning environments, and can attest to the quality of our courses. Many have gone on to found their own protocols and services: from EPNS, to Toucan Protocol, Impact Market, Swivel, Sherlock, DefiSafety, Pr1s0n Art, and many more. Please find a (shortened) list of Kernel fellows and projects [here](https://www.kernel.community/en/start/principled-people). Overall, we have had more than 60 projects formed in Kernel, who have collectively raised over $200M. You can also find personal testimonials from many of the people on our [wall of love](https://www.kernel.community/en/love/).

Kernel is the premiere, open, communal, peer-learning environment in web3. We teach both personal principles and web3 best practices, and are currently building our own suite of tools for communities of care based on what we have learnt together over the last twenty-four months. From contracts for more free learning, to [signature economies](https://github.com/kernel-community/signature-economies/blob/main/packages/hardhat/contracts/SignatureNFT.sol#L109), to convivial services: we are putting into practice all we preach.

In addition to our open source work and [Learn track](https://www.kernel.community/en/learn/), we also offer [build guilds](https://www.kernel.community/en/build/) to teach specific skills. In Kernel Block 7, we will offer an Open Data guild, which pulls together best practices from IPFS, The Graph, and Arweave. We also host less structured group explorations called “jams” and have entertained at least one of these on libp2p, in which acolytec3 and shresthagrawal built [this tutorial](https://github.com/shresthagrawal/learnp2p). While we are committed to maintaining an open environment in which our peers can learn about what most interests them, it so happens that we have helped assist many into the spacious world of IPFS because of the quality of the technology you produce.

During each block, we also host an internal expo for Fellows to demonstrate their ideas, and then an external Demo Day at the end of the eight weeks, where we invite mentors from the whole web3 ecosystem to come, provide their insights, and learn about the latest ideas being built with care and intention. These same mentors are also invited to Office Hours each Friday, which has become an industry-wide norm, and which allows them to, again, provide insight and experienced feedback, while also being exposed continuously to new and creative ideas. Such customs and rituals are critical for anyone running ecosystem development funds, incubators, or accelerators, and we have - and will continue to! - welcome Protocol Lab representatives to join us for both Office Hours and our public Expo each block. We generally have 30 teams present and an audience of a couple hundred hand-picked mentors and guides at these events.

# Value

## What are the benefits to getting this right?

An open educational web benefits us all. We know this is a broad claim, but it is our genuine thesis and we have been practicing it for two years. It is not enough to have [dynamic knowledge repositories](https://www.youtube.com/watch?v=whVnseOtElI). It is not even enough to have [networked improvement communities](https://dougengelbart.org/content/view/191/) cultivating and [consulting](https://www.kernel.community/en/learn/module-3/remember) such repositories. You need both of these things, **and a meta-narrative**: some clear and coherent ontological way of framing “the deep why”. _Why_ is open source software, and more decentralized tools, critical to our shared thriving? _Why_ does building a better web matter? _Why_ should you or I care?

Kernel is committed to asking [better questions](https://www.kernel.community/en/learn/module-2/better-questions) that might help illuminate the edges of such a frame, and then offering back to the wider web3 community patterns for thinking and creating care-fully in different and diverse contexts.

We have also tried to [focus on intimate events](https://convo.kernel.community/archive): small, intimate dinners, picnics, and walks with other Fellows which mirror the kind of open-hearted dialogues that are the primary pedagogical method in Kernel. The syllabus does not provide answers: only the sorts of questions which can open up honest dialogue between diverse peers: because that is the kind of environment capable of producing lifelong learning and relationships. Our IRL events are often hosted in people’s homes, or at favorite restaurants, and very rarely exceed 20 people. This is by design, because real impact has very little to do with numbers. These gatherings are the heart of resilient and sustainable communities of care and learning.

## What are the risks if we don't get it right?

An uneducated public building nothing truly [good](https://www.kernel.community/en/learn/module-7/perfection/#just-write). Without a radical approach to learning and creating, how can we create different patterns from the extractive ones within which we have all come of age?

There is also the ever-present risk that our syllabus might disappear, as it is currently hosted through gh-pages. We therefore [pin it to IPFS](https://ipfs.io/ipfs/QmPPd37vYkkkssneAaf76punc5s6CnjdtAPcugyrGvKRvZ/en) every so often. We feel confident enough that our git history is reliably stored across multiple local devices, as well as GitHub itself, though we are always considering better ways of ensuring our data remains open and accessible to all. 

## What are the risks that will make executing on this project difficult?

The benefits above may seem abstract to some who focus on specific KPIs and “shipping product” quickly: [delightful education](https://www.kernel.community/en/learn/module-6/learn/#a-surprisingly-educated-public) operates over a long time horizon. People we teach now may take years to integrate the learnings they begin to open up to through Kernel, and it may be even more time until they actually enact anything they learn.

While we feel we have already executed our initial vision, the risk is now that finding sustainable sources of funding may prove difficult, given that so many take for granted the benefits of an educated citizenry.

# Deliverables

1. The Signature Economies interactive essay - a new medium for significant expression which [leverages IPFS to generate dynamic images](https://github.com/kernel-community/signature-economies/blob/main/packages/hardhat/contracts/SignatureNFT.sol#L109) on an immutable foundation in order to expand our collective understanding of ‘ownership’ and what it really means.
2. An “Open Data” guild in Kernel Block 7, which begins on September 9th, 2022. 
    1. This guild will comprise of 4 sessions delivered over the course of 8 weeks.
    2. We will cover the history, the current state of the art, and then two sessions of technical direction and guidance dependent on what the participants would like to learn most.
    3. We expect 70-80 participants.
    4. We are hesitant to provide KPIs like “x number of developers using libp2p” or “y number of new Lotus nodes” as we feel that this kind of outcome-based education is precisely what we are working to remedy.
3. An open invitation to Protocol Labs representatives to attend all Kernel showcases: both those that occur in each Block, as well as the recurring Alumni showcases we now host every quarter. We feel this is valuable in the context of PL’s ecosystem funnel and could strengthen the quality of deals in their early stages.
4. A fireside discussion with [Juan Benet, similar to the one we hosted in KB2](https://youtu.be/WjQ87t2s2y8?t=1395), hopefully on Achieving Paretotopia and his own latest work and interests.
5. Ongoing contributions to the Filecoin ecosystem from graduating Kernel Fellows, such as Sonia John, James Tunningley, [Nandit Mehra](https://nanditmehra123.medium.com/lighthouse-new-feature-and-potential-applications-overview-9c0156b4e91) (started [Lighthouse](https://www.lighthouse.storage/)), [vasa-develop](https://github.com/vasa-develop), [johnx25bd](https://astral.global/), acolytec3, Viraz Malhotra, bitsikka and many more.

# Development Roadmap

Kernel is already an established web3 institution (in the sense of [customs and rituals](https://www.kernel.community/en/learn/module-4), not bureaucracy). This is a request for funding to ensure the ongoing sustainability of our team. 

Though we have minimal software costs, we have grown to 6 people and spend around $40k a month, mostly on salaries. We host one block every four months, which generally takes in ~$90k in fees. Before growing to 6 people, we were breaking even, but it was not manageable, hence the two critical new hires.

Our biggest software cost is Slack, which comes to around $3k of our $40k monthly expenses. Kernel slack, as Sonia and many others can attest to, is a unique place: it is a multi-year repository of some of the most interesting and wide-ranging ideas both within web3 and beyond. We use it to mint our own [Gratitude NFTs](https://gratitude.kernel.community) from a channel dedicated to such messages (the first deployed on Ethereum - we take the message with your name tagged and add them as the metadata to a generative NFT which is updated each block via a merkle root). There are also channels for guilds, asks, offers, opportunities, gardening photos, meditation, mindful movement and many, many more.

We hope to raise funds from aligned organizations in a one-time round while we create our own web3 experiments to make us sustainable without requiring any more external funding.

- **Signature Economies** - an essay which provides an alternative framing to the ownership economy and which allows readers to mint two different kinds of NFTs. Kernel earns royalties, and any amount spent on the second kind of NFT. This will be released by **June 24 2022** and can be found [here](https://github.com/kernel-community/signature-economies).
    1. Two engineers and one designer have been working on this. One engineer on the frontend, the other on the contracts and subgraph.
    2. This is built and only requires retroactive funding of $30k as one engineer elected to take no salary for the duration of the project.

- **[FreeLearn](https://www.kernel.community/en/guiding/free-learn/)** - two simple contracts built to ensure that learning is both free, and that edu(cre)ators can get duly rewarded for the work they do. We have some plans to generate revenue from this which are not public. The contracts are written and audited, but we only aim to deploy after extensive testing and integration, which may take until September this year. The repo is [here](https://github.com/kernel-community/learning-curve).
     1. Three engineers have been working on this. Two on the contracts, one on the frontend.
     2. This requires further funding of $30k given the scale of testing and integration we envision doing.
     3. In particular, you can see our python-based testing suite [here](https://github.com/kernel-community/learning-curve/blob/main/tests/test_unit_lc.py) which requires further work to ensure that we are safe from flash loans and other DeFi primitives which can be hard to predict.
     4. We also wish to integrate these contracts with our [non-custodial wallet](https://github.com/kernel-community/services/tree/main/packages/wallet), which requires some integration work and then some careful thought, design, and development in terms of the business logic we write in the wallet to ease interactions between Fellows, the contracts, and the wider syllabus.

- **Kernel Services** - open infrastructure for communities of care. This work is currently live in a staging environment, and the first version of it will be in production by August 9th, in time for RSVPs for Kernel Block 7. KB7 will begin on September 9th. Our intention is to keep creating a wonderful family of open source, focused web apps over the next few years which (a) solve problems we have and (b) do it in a way that is potentially useful to many other communities. The repo is [here](https://github.com/kernel-community/services).

     1. We have an open community of contributors working on this, and four engineers managing the work.
     2. This requires ongoing funding. Our engineering costs here amount to 8 ETH (~$60k for the next 3 months) per month.

# Total Budget Requested

We are seeking $3.2MM in total funding from the web3 ecosystem as a part of our transition to a KERNEL Foundation. We intend to explore contributions with a variety of other top tier, value-aligned ecosystems within web3, open source, plural goods communities. 

**We are requesting $250k from Filecoin**. The engineering work we intend to do, outlined in the milestones above, amounts to $120k. We require another $118k to keep paying the salaries of our operational and community team, who are equally critical to the long term success of Kernel as an open educational web. We require $12k to cover operational technology costs that enhance community communications (slack at $3k per month and airtable at $1k per month).

# Maintenance and Upgrade Plans

From a financial perspective, we are hopeful that experiments like Signature Economies and FreeLearn provide enough income to fund the current team, or one of commensurable size, into perpetuity. We are also applying for grants with The Graph and Climate Collective, and have conversations going with a few other teams we feel are well-aligned with our [principles](https://www.kernel.community/en/start/principled-people). If we get anything more than requested in this grant, it will enable us to form a web3 endowment, which we plan to use in a responsible, Long Now inspired, way to ensure we do not need exogenous sources of funding.

From a technical perspective: we have consciously chosen to build our tools using React and Solidity. We were tempted by previous experience to go with languages like Clojure and Vyper, but have decided that using a less elegant language which more people speak is a better way of building community software. If you read our code, it is intentionally simple (in the [Rich Hickey ](https://www.youtube.com/watch?v=rI8tNMsozo0)sense) and accessible. We feel confident that most people familiar with web development will be able to use, maintain, and improve what we do. This has, from the first, been a critical design consideration of ours.

# Team

## Team Members

1. Andy Tudhope
4. Vivek Singh
6. Angela Gilhotra
7. simonpure
8. Sachin Mittal
9. Sidcode
10. Aliya Donn

## Team Website

https://www.kernel.community/

## Relevant Experience

We’ve been running Kernel for two years and have established it as the premiere educational experience in web3.

Andy built a [simple curation mechanisms](https://observablehq.com/@andytudhope/embedded-discover) in [production](https://dap.ps) on Ethereum while working at Status. He has long worked in the realms of ontological and mechanism design.

Vivek was COO of Gitcoin and one of its first employees.

Simon has been around the block many times, and written so much software it’s now even in a [book](https://www.amazon.com/Applying-Case-based-Reasoning-Semantic-Web/dp/3639841336).

Angela built the [first Gratitude contract ever deployed on Ethereum](https://github.com/kernel-community/gratitude).

Sidcode is a [literal bridge between worlds](https://www.cyber-physical.space/).

Sachin first had the dream which turned into this reality.

Aliya has a background in justice of many kinds and is one of the most wholesome humans to go through Kernel.

## Team code repositories

https://github.com/kernel-community

# Additional Information

We watched a number of projects from Kernel go through the Open Grants program successfully, and were especially happy to see [Verses](https://github.com/filecoin-project/devgrants/issues/423) with Jasmine Wang, [21 MXXI](https://21mxxi.com/) with James Tunningley, and [Lynx](https://docs.lynx.phas3.io/) with Sarah Hamburg and Alexandra McCarroll gain your support. Please feel free to ask any of these people about their experiences in Kernel for additional due diligence on this request.

**Comment by ErinOCon** [comment]
Hi @andytudhope, thank you for your proposal! The grant has been approved. For next steps, please email grants@filecoin.org.
