### ISSUE TITLE
Open Grant Proposal - Flaq Club

### ISSUE THREAD

**Issue by d3fkon** [filecoin-project/devgrants#686]
# Open Grant Proposal: `Flaq Club`

**Name of Project:** Flaq Club

**Proposal Category:** app-dev
**Proposer:** `d3fkon`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** "Yes"

# Project Description

   
   

Flaq is a web3 discovery platform, where non-crypto-native users are incentivized via airdrops to learn about web3 / crypto projects.

There are four aspects to Flaq:

1. Hook
2. Reward
3. Learning
4. Airdrop

**Hook**

Since Flaq targets users who are curious about web3, and are not crypto-native, Flaq aims at having web2 hooks, to make the jump from web2 to web3 as effortless as possible. <br/>
Flaq intends to use every-day low-effort activities of users, as hooks to earn "Flaq Points". And these "Flaq Points" convert to a crypto-currency which Flaq is promoting, provided the user educates themselves about the project.

**Reward**

Each completion of a hook, will reward the user with "Flaq Points" at a specific rate, which can be accumulated over time to redeem for a crypto currency Flaq is promoting.

**Learning**

The user is required to learn about the projects being promoted using videos / text material and eventually answer a 10 point quiz to confirm their participation. The content for the learning can either come from the project itself or can be created by the Flaq Team on demand.

**Airdrop**

Successfully passing the quiz makes the user eligible for an instant airdrop to their wallet.

---

A simple use case would be as follows:

1. User downloads Flaq
2. **Hook & Reward** - Flaq leverages UPI as a Technology to detect user's UPI transactions. Thus, _Flaq Points_ are rewarded to user for making UPI Payments on their device
3. **Learning** - After accumulating a certain amount of Flaq Points, the user can withdraw these points into the crypto currency that Flaq is currently offering ($FRONT / $USDT), provided that they watch videos of promotion running and answer a 10 point quiz. This layer is customizable to be as interactive as possible with the user for maximum value add
4. **Airdrop** After this, a withdrawal request will be sent to the smart-contract on the respective chain, which airdrops the right amount of crypto as per the user's Flaq Point Holdings

A detailed outline on how rewards work with different use-cases on flaq can be found here - https://flaq.club/blogs/flaq-rewards-model/

---

#### Why are we doing this?

1. Crypto/Web3 discovery, distribution & onboarding is complex & cumbersome - It's not easy for new users to learn about existing web3 projects and existing users to learn about new web3 projects (unless they deep-dive into CT?)
2. In the market conditions of today, for web3 startups to survive, they require a level of exposure with new / existing audience which is not provided by traditional marketing
3. There's an inefficiency in the way startups can airdrop tokens. Most small / young startups have no way to reliably airdrop their tokens to an eligible set of users

---

#### How are we solving this?

1. Flaq acts as a platform to discover new projects via airdrops
2. Help web3 startups find the right set of users, via the interactive learning layer, which can change as per requirement
3. Help web3 startups conduct airdrop marketing campaigns using different parameters

---

## Value

Flaq leverages Filecoin for 2 specific reasons

1. Transparency
2. Wallet Adoption

**Transparency**
All payouts which happen on Flaq, are recorded on Filecoin via OrbitDB. This helps create a trustless environment for the users of Flaq as well as projects looking to adopt Flaq into their marketing.

**Wallet Adoption**
Under the Flaq umbrella, is the Solace Wallet and the Solace protocol. Solace is a program (smart-contract) based non-custodial wallet for Solana which eases user's onboarding and enhances security using social recovery. Solace uses Orbit DB and IPFS to store user's guardian information.

A little more on Flaq's usecases of Filecoin is written here - https://flaq.club/blogs/filecoin/

Flaq creates value to the web3 ecosystem in the following ways:

1. Flaq helps new users onboard themselves into web3 and make themselves discoverable to existing projects
2. Flaq helps existing web3 users discover new and upcoming web3 projects, helping in distribution / marketing

## Deliverables

| Description                                                              | Github Link                              | Progress |
| ------------------------------------------------------------------------ | ---------------------------------------- | -------- |
| Flaq Mobile App to transparently track user's UPI transaction            | https://github.com/d3fkon/flaq-rewards   | 80%      |
| Solace Wallet Protocol                                                   | https://github.com/d3fkon/solace-wallet  | 70%      |
| Integrating the Solace Wallet Protocol with Flutter and Flaq             | N/A                                      | 0%       |
| ERC20 Smart Contract for Airdrop Escrow deployed on all major EVM Chains | N/A                                      | 0%       |
| Solana Escrow Program to Airdrop SPL Tokens                              | https://github.com/d3fkon/sol-spl-escrow | 90%      |
| Open Source Chrome Extension for Online Transaction Hook                 | N/A                                      | 0%       |

Solace wallet has been a Micro Grant Recipient from Filecoin. Solace was also a prize winner at the Solana Hackathon 2022. Flaq is an extension to the effort for increasing web3 adoption

## Development Roadmap

The following are the various milestones

1. **The transparent UPI transaction detection mobile application written in Flutter/Dart** (May 2022 - July 2022)<br/>
   A mobile app where the user can reliably earn Flaq Points for every UPI transaction. The effort for this is already underway and can be found here https://github.com/d3fkon/flaq-rewards
   1. Quiz Module for testing user's understanding of the project Flaq is Promoting - Completion by June 2022
   2. Support for transparently tracking UPI transactions from 10+ Indian Banks - Completion by July 2022
2. **Solace Wallet / Flaq Integration** (July 2022 - September 2022)<br/>
   Integrating the Solace Wallet Protocol into Flaq enabling a native wallet experience to users
   1. Porting Solace Wallet Protocol to Flutter / Dart - Completion by August 2022
   2. Integrating Flaq rewards with Solace Flutter Protocol - Completion September 2022
3. **ERC20 Escrow Smart Contracts** (June 2022 - July 2022)<br/>
   Building an escrow smart contract to airdrop users in a decentralized way
   1. Smart Contract Development - Completion by July 2022
   2. Deploying Smart Contract on Ethereum, Poygon, Avalanche, Binance Smart Chain, Fantom - Completion by July 2022
4. **Solana Escrow Program to airdrop users SOL and SPL Tokens** (May 2022 - June 2022)<br/>
   Building an escrow program on Solana
   1. Program Development - Almost Completed - Completion by July 2022 (https://github.com/d3fkon/sol-spl-escrow)
   2. Program Deployment - Completion by July 2022
5. **Open source chrome extension for online transaction hook** (August 2022 - October 2022)<br/>
   Expanding beyond India requires a Chrome Extension to be built, which awards users crypto for shopping at known brands online.
   1. Developing the chrome extension - Completion by September 2022
   2. Integration Testing - Completion by October 2022

## Total Budget Requested

Total budget requested: 30,000 USD

**Budget Breakdown**

| Requirement                                          | Timeline | Overall Budget |
| ---------------------------------------------------- | -------- | -------------- |
| Flutter Developer - Junior                           | 6 months | 3,500 USD      |
| Flutter Developer - Senior                           | 6 months | 5,500 USD      |
| Node JS Developer - Junior                           | 6 months | 3,500 USD      |
| Node JS Developer - Senior                           | 6 months | 5,500 USD      |
| UI/UX Designer                                       | 6 months | 2,000 USD      |
| Community Building Activities (In-Person and Online) | 6 months | 4,000 USD     |
| Social Media Marketing                               | 6 months | 6,000 USD     |

## Maintenance and Upgrade Plans

Currently, Flaq is focused on India and hence uses UPI as it's primary hook. This will change after October as Flaq will also be a downloadable Chrome Extension which transparently rewards users with Flaq Points for every Online Transaction Globally.
However, our long-term plan is to build native reward hooks in major countries, by tapping into the country's specific infrastructure.
Some of the partnerships we are looking forward to are:

SuperPay - https://superpay.money<br/>
CRED - https://cred.club/

and other payment channels globally

# Team

## Team Members

**Ashwin Prasad** - Tech Lead<br/>
Email - ashwin@onpar.in<br/>
Github - https://github.com/d3fkon<br/>

Ashwin has over 6 years developing as a full stack developer and 3 years being a smart contract developer<br/>
He was the CTO at a FinTech Startup in India, called ZeroPay (https://zeropay.fyi), where he scaled to 100k users in 3 months in the space of consumer credit<br/>
Since then, he has been an avid blockchain developer focusing on Solana, also winning a prize in the Solana Hackathon Bangalore 2022 for his efforts on the Solace Wallet.<br/>
He is also the founder and CEO of Onpar Labs, which consults startups and companies globally

**Ankit Sethi** - Product Lead</br>
Email - ankit@onpar.in<br/>
Website - https://zethi.webflow.io<br/>
Dribble - https://dribbble.com/Desizgn<br/>

Ankit is an experienced Product folk, with 4 years of relevant experience working in startups. Ankit and Ashwin led the efforts at ZeroPay together, helping it scale from 0 to 100k.</br>
He has also led product at Solace, after leading teams at startups like Onpar Labs, Volaverse and YSchool<br/>
Ashwin and Ankit have known each other for over 7 years, meeting first at a hackathon and then subsequently working together on Onpar Labs and eventually Solace.

**Goutham SG** - Marketing and Growth Lead<br/>
Email: goutham@onpar.in<br/>

Goutham and Ashwin have known each other since school (since 2012). Goutham headed marketing at ZeroPay, and is a part of the GrowthX Cohort 2 (https://www.growthx.club). He has relevant experience managing high budgets for marketing products, both in web2 and web3

Apart from this, we have a team of developers and interns who are working / willing to work on Flaq

1. Sarthak Sharma - Core Team Member Flutter Developer Senior - https://github.com/affableSarthak/
2. Muaaz Khan - Operations Lead
3. Nisarg - Flutter Developer Junior - https://github.com/Nisarg-18
4. Ankit Negi - NodeJS Developer Senior - https://github.com/ankitn1311

## Team Member LinkedIn Profiles

1. Ashwin Prasad - https://www.linkedin.com/in/ashwinxprasad/
2. Ankit Sethi - https://www.linkedin.com/in/ankit-sethi-42074b222/
3. Goutham SG - https://www.linkedin.com/in/goutham-sg/
4. Sarthak Sharma - https://www.linkedin.com/in/sarth-ak/
5. Muaaz Khan - https://www.linkedin.com/in/muaaz-khan-284137176/

## Team Website

Hosted on Filecoin - https://bafybeig2tu4a4kcjjtpfuqsg5vqivfrgbsgmr5jf7vb5rccwegpjdan2nu.ipfs.infura-ipfs.io/

https://flaq.club

## Team code repositories

1. Solace Wallet - https://github.com/d3fkon/solace-wallet
2. Flaq Rewards App - https://github.com/d3fkon/flaq-rewards
3. Solana Escrow - https://github.com/d3fkon/sol-spl-escrow

The beta version of the Flaq app is currently under review on the Google Play Store

# Additional Information

- How did you learn about the Open Grants Program?<br/>
  Via our Technical Sponsor
- Please provide the best email address for discussing the grant agreement and general next steps.<br/>
  ashwin@onpar.in / ankit@onpar.in

- Please include any additional information that you think would be useful in helping us to evaluate your proposal.<br/>
  Flaq Pitch Deck - https://drive.google.com/file/d/1XNVjXmyNv83mK664XOvE4bCAQ5TNvu89/view?usp=sharing<br/>
  Flaq Mobile App Demo - https://pitch.com/public/741a97ac-638c-4ddf-806f-3882b72bca18<br/>
  Flaq Twitter - https://twitter.com/flaq_club <br/>
  The app is currently in Private Beta, and has seen participation from Fronter Wallet (https://frontier.xyz) as a project sponsor. Flaq has 110 users testing currently and has surpassed 400k INR of recorded transaction volume for which Flaq Points were rewarded

**Comment by d3fkon** [comment]
Please find the demo video here - https://youtube.com/shorts/G5EuKKkzBK0?feature=share

**Comment by ErinOCon** [comment]
Hi @d3fkon, thank you for your proposal. Unfortunately we will not be funding the work outlined based on the following observations. The development roadmap heavily focuses on the reward models which don’t provide a unique user experience. We recommend focusing on content development as a driver to user engagement, and platform scalability. We’ll be happy to review a proposal that highlights education planning!

**Comment by d3fkon** [comment]
Hi @ErinOCon over the last 30 days, considering our user feedback and recommendation from our mentors, we have pivoted Flaq to be more content-oriented instead of reward oriented. We would love to have your inputs on the same.
For this, I have opened a new proposal at #825 
Thank you for your feedback
