### ISSUE TITLE
Filecoin Community Grant Marketplace

### ISSUE THREAD

**Issue by InvluencerMikeDoyle** [filecoin-project/devgrants#689]
### Proposal to Filecoin
To create a decentralized Filecoin Community Grant Proposal platform that sources grant evaluation insights from the community, both experts and laypeople alike. The platform will work by:

1. Providing a standardized intake interface for proposals from projects 
2. Sourcing feedback from the Filecoin & greater ecosystem regarding project proposals using incentives
3. Dynamically creating models that score and rank the potential of opportunities and risks of proposed projects
4. Allocating grant funding to projects that pass the grant funding criterion
5. Tracking the success of each project against individual grant milestones
6. Providing future funding opportunities for successfully grant initiatives through integration with the Invluencer Alpha Investment Platform.

These capabilities will be made available via a Filecoin Grant Marketplace interface that will ease the publishing, evaluation, grant monitoring and next-stage development phases of Filecoin granted projects.  

In addition, it is proposed that the development of the Filecoin Community Grant Marketplace be extended to create a whitelabel marketplace solution framework. This solution framework will provide projects and companies looking to build a fit-for-purpose, Web3 marketplace with a solution that accelerates their time to market, and that leverages Filecoin storage by default. This solution will leverage existing Nevermined-Filecoin integrations to provide secure access and asset control.

### Intended Outputs

- A robust data marketplace that scores and ranks the potential of opportunities for risk reduction during funding cycles for these opportunities - each project follows a risk reduction ‘Funnel’ process
- A growing linked network of individual participants in the ecosystem ensuring projects outputs (data) do not asymptote
- A whitelabel marketplace framework integrated with Filecoin storage that is intended for off-the-shelf deployment of future, bespoke marketplaces
- Growth in data stored on Filecoin with full Data Provenance and Lineage features built in

### Problem

1. Poor Data Environment: Grant Funding and Early Stage investment exists in a poor data environment resulting in very high risk for the funders, lack of project completion & difficulty in identifying top class projects.
2. Screening Projects for reduced risk: An essential part of successful commitment to funding a project is a successful flow and screening process that takes place depending on the life cycle of the project, leading from one stage to the next with reduced risk as the process completes each stage:
![image](https://user-images.githubusercontent.com/77589457/174746782-4e82f18a-5381-4fa1-8b4c-397edfba07ac.png)

### Solution 
**_Background_**
The proposed solution will leverage two products that have been successful beneficiaries of previous Filecoin grants: Invluencer and Nevermined. The intention of leveraging these two solutions is twofold:

1. To accelerate time to market for the Filecoin Community Grant Proposal platform, and
2. To further the integration of Invluencer and Nevermined with Filecoin

Invluencer, and its corresponding i3D Protocol, is a community-based screening process designed to identify the potential alpha start-ups that have the highest likelihood of becoming successful companies. 

Working with Filecoin and Polygon, and through collaborative partnerships with Nevermined, Invluencer has launched its Beta Platform for the i3D Protocol. The output from participation is a Scoring and Ranking Platform displaying companies seeking alpha investment, that allows investors to make a better-informed decision on the allocation of their funds. 

_Current components include:_

- i3D Rapid (funded by Filecoin): a Mobile App that allows users to earn tokens for being part of the network, and by scoring the Idea and Team components of an alpha due diligence process. Users will be able to increase their reputations to earn at higher rates.
- i3D Arena: a web-based application that allows an expert with a higher reputation to complete deeper dives into companies, and earn at higher rates.
- i3D Angel NFT: an Access Control utility solution designed by Nevermined that ensures only validated network data is stored and retrieved from Filecoin, giving investors security in Data Provenance and Lineage, and providing novel mechanisms for licensing that leverage Filecoin secured assets.
- i3D Token: the payment mechanism rewarding the network participants.

Nevermined is a data ecosystem solution that provides the capabilities of building bespoke networks in which different entities can share and monetize their data and associated assets through an efficient and secure manner, even between untrusted parties. Nevermined currently leverages Filecoin for numerous features, including its [secure file storage solution](https://medium.com/nevermined-io/5-privacy-decentralised-storage-we-have-it-5ef5769b5b2d) with Data Transfer Proofs.

Nevermined provides the building blocks to define and implement different use cases based on:

- Assets Tokenization via NFTs (ERC-721 & ERC-1155)
- Secondary Markets
- Digital assets provenance tracking and royalties
- Proof of Attendance 
- Data Sharing
- Remote Computation

Nevermined has fully scoped a [whitelabel marketplace framework solution](https://docs.google.com/document/d/1KU9GGhru_xmzB7WJHu7lly6gzJJrmRpnZ4ANARKtQN8/edit#) that will piggyback off of the existing implementations of both Invluencer and Nevermined linked marketplaces (for example: https://www.i3d.ai/ and https://defi-data.net/) in order to accelerate development time substantially.

### Benefits
The proposed solution will offer the following features and benefits:

- A solution that offers Filecoin the opportunity to redefine its own grant process and expand the user base of Filecoin’s storage capabilities through the attraction of net new organizations to the ecosystem.
- A solution that improves Filecoin’s grant evaluation capabilities by providing the ability to audit funding requests with improved quantitative and analytic capabilities via modifications to Invluencers scoring system.
- Improved scoring of grant proposals via the inclusion of Wisdom of the Crowd based scoring.
- Better grant allocation tracking through Nevermined’s data provenance and lineage capabilities, and better asset management through Nevermined’s secure storage of project proposals, analysis reporting, success metrics, etc.
- Increased numbers of users actively engaging with Filecoin grant evaluation through  network development and ecosystem project identification incentives. Instead of risking funds for what sounds like a good idea, the fear of missing out, poor intelligence, or reliance on expensive analysis, leveraging the i3D Protocol offers the opportunity for participants to have access to and contribute to Invluencer’s Intelligent Distributed Due Diligence capabilities, and get paid for doing so.
- The delivery of a whitelabel marketplace framework intended to increase adoption by other organizations that are looking to accelerate their time to market, thus further increasing the storage demands for Filecoin through the framework’s default storage option - Filecoin.

### Development Milestones
Time to Build: 3 to 4 months

****Component 1**: Whitelable Customization of Nevermined Data Marketplace: 
Budget $115,000
2 X FTE, 2X PTE**

- Refactor and component feature generalization based on existing framework of Nevermined Data Marketplace (i.e. Defi Data Marketplace, etc.)
- Integration of similar core Filecoin components (i.e. leveraging verification / notarization components from Fil+)

****Component 2**: Development & Integration of Whitelable to existing Invluencer Components: 
**Budget $138,000**
6X FTE, 4X PTE**

**Milestone 2A: $68,000**
Global Onboarding Platform for any project applying for funding via Deal Originators i.e., Grant Foundations, Crowdfunding Platforms, or Venture Capital. 
**Milestone 2B: $30,000**
Customization/Whitelable: During onboarding projects are assigned/linked to Deal Originators who referred them with applicants completing a universal set of required information plus a custom set of information that may be required by the Deal Originators
**Milestone 2C: $20,000**
1. Publishing to i3D Platforms (i3D Arena & i3D Rapid) for review by Inner & Outer Swarm communities based on their Reputation Levels within the Protocol. 
2. Deal Originators to have the opportunity to select communities based on sector expertise, location, reputation level, number of participants, etc. all with min & max parameters to be established
3. Mechanisms for Deal Originators to complete an initial review as admins of projects prior to push to publishing

**Milestone 2D: $20,000**
Unlock mechanisms to move from grant funding stage to crowdfunding stage, etc., including publishing to Launchpad opportunity

****Component 3:** Backend Algorithms & Analytics: 
Budget $102,000
2X FTE, 2X PTE**
**Milestone 3A: $62,000**
Strengthen scoring components & algorithms for analytics process ensuring defined parameters are met
**Milestone 3B: $40,000**
Completion of a Technical Automated Score based on data inputs by applicants, produced via alt-data algorithm for an instant score - to conduct initial screening process

****Additional**: 
Budget: $40,000**
Development of Marketing Program & Network Structures for onboarding of Projects, Deal Originators & Users

**Team**
Team Members
Michael Doyle
Don Gossen
Oswald Garlick
Aitor Argomaniz
Jonathan Els
Matt Hacking
Patrick Doyle
Trevor Harraway

**Team Member LinkedIn Profiles**
https://www.linkedin.com/in/michael-doyle-26882bb6/
https://www.linkedin.com/in/donald-gossen-40ab96/
https://www.linkedin.com/in/oswaldgarlick/
https://www.linkedin.com/in/aitorargomaniz/
https://www.linkedin.com/in/elsjonathan/
https://www.linkedin.com/in/matthew-hacking-87651164/
https://www.linkedin.com/in/dr-patrick-doyle-88436110/
https://www.linkedin.com/in/trevor-harraway-81449a7/

**Team Website**
https://invluencer.com https://keyko.io https://defi-data.net/

**Relevant Experience**
The i3D Protocol is a collaboration between Invluencer Ltd and Nevermined.io blending Tradfi and Defi

**Invluencer Ltd Team**
Mike Doyle: Co Founder & CEO Invluencer
Bachelor of Commerce, Post Graduate Futures Studies
2X founder:

Rule 17 Ltd in the UK which grew to owning 4 X Pubs, 2 X Nightclubs and 4X youth hostels
Mickey Doyles Construction in South Africa which grew to a team of 58 employees involved in high end construction projects
Has also successfully built a large team of 78 managing the roll out of a full sustainability and facilities program for an international school in the Kingdom of Eswatini.
Oswald Garlick: CTO Invluencer
Network Engineering & Software Development
2X Co Founder of krpt.io and Vanirtech - servicing the financial services crypto arbitrage industry

Patrick Doyle: Co Founder & Development Advisor
Consultant Anaesthetist and Stanford Graduate School of Business Certificate of Innovation and Entrepreneurship
Founder of L2p.co.uk, a regulatory software company with +20K active users

Jonathan Els: Technical Consultant
Master of Science in Software Engineering
2X Co Founder of krpt.io and Vanirtech - servicing the financial services crypto arbitrage industry

Matt Hacking: Director Invluencer, Crypto Advisor
Director Pharmafinium: Digital Healthcare Accelerator
Co Founder Oxford Hormone Clinic

Trevor Harraway: Due Diligence
MSc Environmental Geochemistry
Invluencer Due Diligence Framework Developer and Founder of Endiligence - Transaction Due Diligence (non-financial)

**Nevermined Team** led by:

Don Gossen: CEO Nevermined

- BSc Engineering, Computer Engineering
- Serial Entrepreneur with extensive experience incubating and scaling ventures.
- 3x Founder & CEO
- Nevermined - The world’s first decentralized collaborative computing platform
- Keyko - Web3 Innovation Hub
- Ocean Protocol - The world’s first decentralized data marketplace; $350M+ Market Capitalization

Aitor Argomaniz: CTO Keyko

- Deep Tech and Big Data expert with keen eye for talent and extensive track record of delivery
- 2x Founder & CTO
- Nevermined - The world’s first decentralized collaborative computing platform
- Keyko - Web3 Innovation Hub

**Team code repositories**
• https://github.com/keyko-io
• https://github.com/nevermined-io
• https://github.com/bigchaindb
• https://github.com/oceanprotocol
• https://github.com/stratio
• https://github.com/xaynetwork
• https://github.com/filecoin-project
• https://github.com/celo-org
• https://github.com/bancorprotocol

**Additional Information**
Link to Design of i3D Rapid App:
https://xd.adobe.com/view/7e70710d-e307-4cfa-b33f-f3151029d194-2b23/

_Link to Whitepaper:_
https://docs.google.com/document/d/1enfdDqZKnu0VDls_43B3F_aUoHXgnkY5/edit#heading=h.gjdgxs

The i3D DDS framework is based on 3 components: an automated algorithmic score from data uploads, an expert score by network members holding a certain reputation within the network, and an ‘expert’ score by the larger network primarily based on sentiment (see Section 5). With identified triangulation points available in all three components, a consensus score is achievable, with the primary aim being to accurately build a set of data points that allows a fully automated score to be achievable.

In conceptualising such a framework for a distributed due diligence network, the example of Amazon Mechanical Turk (MTurk) can be referenced. MTurk is a marketplace for work that requires human intelligence. Companies use MTurk to tap into a broad network of anonymous workers that can choose from thousands of tasks to complete.

i3D uses this logic, enhances it, and applies it to the due diligence process, which also requires human intelligence to complete myriad small tasks. The scoring methodologies reduce the complexity of predictive analytics to simple analysis until consensus is achieved and then reconfigures the data back to an aggregated sectional score.

Companies are uploaded to the platform and distributed to the experts according to their reputation level within the network based on performance, level of expertise, first come first served basis, etc. depending on the level of expertise required. Experts lock up some of their coins for the duration of the scoring process.

To achieve Equilibrium of scores for each factor, algorithms track scores ensuring that once factor equilibrium is achieved the factor is removed from the process while factors yet to achieve equilibrium are continually assigned to experts until equilibrium is achieved. This ensures a factor is accurately scored and does not become lost or diluted in the overall sectional score.
Once Factor Equilibrium is achieved, the scores are aggregated and weighted according to these relevant sections. Commentary is also aggregated with common threads collated into a report that is sent to the platform for access by users.

An expert is rewarded or purchases i3D Coins to have a “stake” in the i3D network, and to access the platform to perform due diligence. The experts get paid Coins for performing the work successfully, as well as earning back the Coins used to bid for the work. The value of these coins is determined by the value of the coin at time of lock up, and by allocated due diligence from the Investor Liquidity pool made up from subscription fees. Excess Liquidity can also be used by Invluencer to Buy and Burn Coins or to maintain liquidity for further development. By asking experts to have a stake in our network, we ensure “skin in the game” and using principles such as loss-aversion and ownership-accountability to ensure that experts are performing due diligence to the best of their abilities. Successfully staking our Coins and earning them back is how an expert contributes to the network’s strength. See Earning Rewards in Whitepaper

**Comment by InvluencerMikeDoyle** [comment]
@realChainLife Please let me know if you need further info
Cheers
Mike

**Comment by ErinOCon** [comment]
Hi @InvluencerMikeDoyle, thank you for your proposal! While we are not currently outsourcing this program work, we will be sure to keep this project in mind in the future. It's always great to see projects focused on scalability!
