### ISSUE TITLE
Nada Amin, Harvard SEAS: Lurk language development

### ISSUE THREAD

**Issue by jpeg07** [filecoin-project/devgrants#691]
# Open Grant Proposal: Lurk language development 

**Name of Project:** Lurk language development 

**Proposal Category:** research

**Proposer:** @jpeg07 on behalf of @namin

**(Optional) Technical Sponsor:** @porcuquine 

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** This will need to be worked out in coordination with Harvard

# Project Description

Please refer to [this document](https://docs.google.com/document/d/1_iWHrIkKGOl1waSAhLQ-pom_VTB1oUrM6WP862yNqq0/edit) for a summary of work funded by Protocol Labs Research from 2021 to 2022 as well as goals for 2022-2023 (this proposal)

## Value

Lurk language development is crucial to enabling Lurk to adequately address the needs of users. Nada's has supported and will continue to support building core language features and libraries. 

The direct relevance of Lurk to the Filecoin network is most directly seen in implications for FVM and Hierarchical Consensus. Lurk integration with the FVM would allow Lurk programs and applications to be verified on the Filecoin blockchain. This would provide Filecoin smart contracts (or actors) with first-class native access to application-specific zero-knowledge provable computation. Filecoin actors could be used to broker, orchestrate, and incentivize long-running Lurk jobs over data stored in the Filecoin network. Further, it would allow proofs that combine public and private data from multiple sources, including Filecoin sectors, private storage, or the chain itself.

As to Hierarchical Consensus, Lurk could remove the need for full access to the state of a subnet in order to verify subnet proofs. Lurk would allow the building of self-verifiable proofs of the state changes performed in the subnet, which would improve the scalability and flexibility of the system.

While Nada's work is not directly on HC or FVM integration, her research and her contributions to building out the core language are essential parts of getting Lurk where it needs to be to optimize those integrations.

## Deliverables / Development Roadmap

Please see the same summary document above: https://docs.google.com/document/d/1_iWHrIkKGOl1waSAhLQ-pom_VTB1oUrM6WP862yNqq0/edit

## Total Budget Requested

$60000 to allocate the requisite amount of professorial research time to this project

## Maintenance and Upgrade Plans

Nada's work will be integrated with the Lurk development team's ongoing support of the project, including the technical sponsor listed above

# Team

## Team Members

[Nada Amin](https://namin.seas.harvard.edu/)

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/mitnamin/

## Relevant Experience

Nada's previous research at Harvard is very related to this, in particular the design and implementation of Lisp-based reflective and declarative languages [like Lurk], including their compilation. Her experience has also proven itself over the last year of working on Lurk.

## Team code repositories

At this point, the best repo for justifying Nada's ongoing work is the Lurk (Lisp) repo itself: https://github.com/lurk-lang/lurk 

## Additional Information
Discussions can happen via email to jonathan.gross@protocol.ai. I can make introductions as needed from there.

**Comment by ErinOCon** [comment]
Hi @jpeg07, this grant has been approved! Please look out for an email to discuss next steps.
