### ISSUE TITLE
Next Step Microgrant: Atila Arthouse

### ISSUE THREAD

**Issue by ademidun** [filecoin-project/devgrants#693]
### 1. What is your project? (max 100 words)

Arthouse is an NFT marketplace that allows you to min NFTs on-chain using an off-chain API key. Users can submit an `https` image and it automatically gets uploaded to IPFS before the NFT gets minted.

This allows users to mint multiple NFTs on multiple chains in one API call.

- https://github.com/atilatech/arthouse-api
- https://github.com/atilatech/arthouse
- https://art.atila.ca/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

There are two ways we use IPFS:

- API: When an `http` image gets submitted via API the image gets uploaded to ipfs using `urlSource`
- UI: When an image gets dragged and dropped via the UI, it automatically gets uploaded using IPFS
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- Add support for multiple chains
- Uploading smart contract source code using IPFS
- Add more robust long-term image storage

 
### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes

  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

https://showcase.ethglobal.com/ethamsterdam/atlas-collection-sharing-ohy7q

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
    * Tomiwa Ademidun, tomiwa@atila.ca, https://github.com/ademidun/
* How did you learn about our microgrant program? I received an email from the Ecosystem Growth team
* If your project was created as part of an event or hackathon:
  * What was the name of the event? ETHAmsterdam
  * Please link to your hackathon submission: https://showcase.ethglobal.com/ethamsterdam/atlas-collection-sharing-ohy7q

**Comment by ErinOCon** [comment]
Hi @ademidun, this microgrant has been approved! We have sent you an email to proceed with payment details.
