### ISSUE TITLE
Next Step Microgrant: The Top Controller- Gaming Consoles and Controllers 

### ISSUE THREAD

**Issue by thetopcontroller** [filecoin-project/devgrants#694]
### 1. What is your project? (max 100 words)
We at the top controller are focused on creating an enhanced gaming experience for our users. We provide enhancements to their console, Xbox as well as Playstation in the form of their favorite skins. Not just that, we do have an option where users can get their custom skins made from us.

https://github.com/thetopcontroller/thetopcontroller-code
https://thetopcontroller.com/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
We will be using IPFS as the storage layer for the designs submitted by the users along with all the data and pictures of the website.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
This grant will help us integrate the IPFS into our tech stack and use it as a storage layer for our website. We will be shifting to decentralised storage layer for our project. 
 
### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three months?
Yes

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  No
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program? From website
* If your project was created as part of an event or hackathon: No
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello: world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by thetopcontroller** [comment]
Hi @ErinOCon , is there any update regarding our application?

**Comment by ErinOCon** [comment]
Hi @thetopcontroller, thank you for your proposal. Unfortunately, we will not be moving forward with this grant at this time. Per our program [criteria](https://github.com/filecoin-project/devgrants/blob/master/microgrants/microgrants.md#program-qualifications), the dev grants program is intended to support projects that have already started integrating IPFS, Filecoin, or related tech into their project. Please feel welcome to propose a new grant once more progress has been made and evidence of the IPFS integration can be identified in your repo/code. Wishing you all the best with your project!

**Comment by thetopcontroller** [comment]
Hi @ErinOCon we have integrated IPFS/Filecoin into our tech stack. Please check: https://ipfs.io/ipfs/bafybeicdomlnsueb7wgj5n3faca6zhebjenrf5qvh255yazujvyct462hm

**Comment by thetopcontroller** [comment]
Please let me know if you need any other information regarding the proposal.

**Comment by thetopcontroller** [comment]
Hi @ErinOCon , if possible can you please have a re-look at our proposal? We have integrated the IPFS/Filecoin.

**Comment by thetopcontroller** [comment]
Hi @ErinOCon can you please guide me here regarding the grant after adding the IPFS in the tech stack
