### ISSUE TITLE
Next Step Microgrant: Embark

### ISSUE THREAD

**Issue by Saviour1001** [filecoin-project/devgrants#696]
### 1. What is your project? (max 100 words)
A learn to Earn platform where people can subscribe to a weekly newsletter, also understand Blockchain, mint their own NFTs with a user-Friendly UI. The goal is to be the bridge of bringing the non-crypto people in this rollercoaster.

[GitHub](https://github.com/EthGlobal2022/interface)
[Site](https://embarkethglobal2022.vercel.app/)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
The NFTs can be of varying lengths and calculating storage rent on chains is tough and expensive. Thus the data of each and every NFT on the platform is pinned on IPFS and the CID is stored in the smart contract to refer back to it.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Working on building [Blocktrain](https://blocktrain.info/) which is an education platform I have been working on for the past 4 months. I built enough audience to interact with and am looking forward to spreading the education more via this project. Will work on adding more features such as multichain token launchpads to make it easier for people to understand that how easy it is to launch one. 
 
### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?
Yes

  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 Yes the project was a winner at Ethernals. 
 https://devfolio.co/projects/embark-b0ea

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Harsh Ghodkar
Email: [harshghodkar@gmail.com](mailto:harshghodkar@gmail.com)
GitHub: Saviour1001
Role: Smart Contract Dev

* How did you learn about our microgrant program?
Won file coin prize at the Hackathon and got a mail regarding microgrant. 
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
 [Ethernals](https://ethernals.devfolio.co/)
  * Please link to your hackathon submission
 https://devfolio.co/projects/embark-b0ea

**Comment by Saviour1001** [comment]
@ErinOCon  Is there any problem in project?

**Comment by ErinOCon** [comment]
Hi @Saviour1001, thanks for checking in! It looks like building progress hasn't been updated in the repo recently. Can you provide more detail on the next steps you will take for this project? This will support our final report requirement at the end of the three month period.

**Comment by Saviour1001** [comment]
Hey @ErinOCon , any updates on this?

**Comment by ErinOCon** [comment]
Hi @Saviour1001, thanks for checking in! Do you have any numbers/information available on Blocktrain's growing user base over the past few months? Any new insights on how the learn to earn model is meeting specific market needs?

**Comment by Saviour1001** [comment]
Here is the Blocktrain YT Channel which showcases the growth of the community, there are some other socials which I am linking forward. The content provided by Blocktrain is pulling up numbers and Embark would help out with forming a stronger growth. 
[Youtube](https://www.youtube.com/c/Blocktrain), [Twitter](https://twitter.com/0xblocktrain), [LinkedIn](https://www.linkedin.com/company/0xblocktrain), [Discord](https://discord.gg/eDS49hBSms). 

These links provide the proof of work I have been putting up in the project since past few months. It's a team effort and now we are looking forward to build this project to help learning of the community.

**Comment by ErinOCon** [comment]
Hi @Saviour1001, thank you for the additional information. This grant has been approved! We will send an email to confirm payment details.
