### ISSUE TITLE
Next Step Microgrant: RUIDEA

### ISSUE THREAD

**Issue by GonzaDDV** [filecoin-project/devgrants#697]
### 1. What is your project? (max 100 words)
RUIDEA (Unique Ibero American Registry of people with Specific Learning Difficulties) is a digital passport that facilitates accommodations for people with specific learning disabilities (dyslexia, dyscalculia, etc...) that has already been adopted as an official document by the government of Spain.

It was developed by the [LectO team](https://lecto.app/en/about) (us) in collaboration with [DISFAM](https://www.disfam.org/), the biggest Spanish-speaking nonprofit for specific learning disabilities , present in 19 countries.

GitHub front-end: https://github.com/LectO-App/ruidea-frontend/
GitHub back-end: https://github.com/LectO-App/ruidea-backend/
Web app: https://pasaporte.dea.ong/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Anticipating the upcoming shift towards decentralized identity, we want the RUIDEA passport to be owned and controlled by its users as far as possible. Our plan is to allow our users to encrypt the [passport ID](https://pasaporte.dea.ong/verificar/ejemplo) and upload it to IPFS and Filecoin, making it possible to retrieve it, decrypt it, and present it to authorities in a permissionless manner, without the need to rely on our server and storage. We will focus on making this implementation easy to use and frictionless, so that everyone can take advantage of it regardless of their previous experience using Web3 tech.

![image](https://user-images.githubusercontent.com/53922815/175277985-9a75aee6-5064-4f8d-a7ba-f4e509f57fc9.png)

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. (Back-end) Generate private keys deterministically from existing user credentials.
2. (Back-end) Encrypt and upload already-issued passports to IPFS.
3. (Back-end) Add encryption and uploading process to the new passport creation feature.
4. (Front-end) Integrate user-friendly IPFS upload and retrieval.
5. (Others) Write a short and simple explanation about the implications of this new feature, how to generate private keys, and how to retrieve the RUIDEA passport from IPFS. Add it to the RUIDEA website.
 
### 4. Is this project open source?
The project is completely open source.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

| **Name**              | **Email**          | **Github account** | **Role**            |
|-----------------------|--------------------|--------------------|---------------------|
| Gonzalo Díaz de Vivar | gonzalo@lecto.app  | GonzaDDV           | Front-end developer |
| Lisandro Acuña        | lisandro@lecto.app | LichuAcu           | Back-end developer  |

* How did you learn about our microgrant program?

A friend of ours who was aware of our intentions to decentralize RUIDEA had previously applied for this grant and told us about it.

**Comment by ErinOCon** [comment]
Hi @GonzaDDV, this microgrant has been approved! We will send an email to proceed with payment details.
