### ISSUE TITLE
Open Grant Application - XY Finance

### ISSUE THREAD

**Issue by xyfinance-contact** [filecoin-project/devgrants#698]
# Open Grant Proposal: `Project Title`

**Name of Project:**
XY Finance

**Proposal Category:** Choose one of `core-dev`, `app-dev`, `devtools-libraries`, `integration-adoption` , `technical-design`, `docs` , `community` , `metaverse` , `research` , `green`  Learn what these categories are here: {https://github.com/filecoin-project/devgrants/tree/master/open-grants}"
Metaverse

**Proposer:** `replace with your GitHub username`
contact@xy.finance
(https://github.com/xyfinance-contact?tab=repositories)

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`
NO

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Please respond with either "Yes" or "No"
YES
# Project Description

XY FInance is the one-stop cross-chain application dedicated to helping all Web 3 users build more with less.

The team estabilshed as we see the need of users wanting to transfer their assets have been skyrocketing. And this can be quite a problem for both DeFi & GameFi users at any stage. That was when we decided to build a cross-chain aggregator that offers highest interoperability to solve the problems. The protocol has built a one-click swap aggregator with the highest interoperability that allows crypto users to trade all on-chain assets. At present, XY Finance have supported ten chains, including Ethereum, BSC, Fantom, Polygon, Arbitrum, Optimism, Avalanche C-Chain, Cronos, KCC, ThunderCore, and Astar.

As more and more strategic partners join our network, this will help the team create a powerful platform. We will help billions of assets transferred within clicks. With more features designed specifically for the GameFi world, we believe what we are going to provide to them is next-level."

## Value

Value:
>Find out the best routes for cross-chain users and complete transaction within seconds.
>SDK and widgets available for DeFi, GameFi & Metaverse projects.
>Y Pool provide yields for liquidity provider without impermanet loss

Challenges:

>Building applicable examples to present potential use cases for gamers & developers as lots of features are still under development.

## Deliverables

1. XY Finance
 1.1 One-click cross-chain aggregator for Web3.
 1.2 XY token to support the tokenomics.
2. Galaxy Kats
 GameFi NFT project that is currently on OpenSea.
3.Galaxy Kats Universe
 An upcoming project for the Metaverse.

XY tokens will be utilize around these deliverables to create a circulating tokenomics.
## Development Roadmap
"2022 Q3

Support More EVM Chains, Bridges and DEXes 
We will integrate more brdiges to enhance our operational stability.
We will integrate more EVM chains based on market trends and community needs. 
Support Solana, Osmosis
We will focus on the development of Solana cross-chain bridge to lower the threshold between EVM and Solana ecosystems.
NFT Markeplace Aggregator 
We will integrate all major NFT marketplaces, such as OpenSea, LooksRare, Ebisu’s Bay, Agora, Cronos World, Crosea, Lootex, and more.
GalaXY Kats Game Official Release
We plan to launch our first GameFi game in this quarter to expand P2E coverage.
GalaXY Kats Marketplace
We plan to launch our self-developed NFT marketplace focusing on GameFi market.
Multichain Wallet Dashboard
Multichain Wallet Dashboard will support all DeFi power users and NFT collectors to track their portfolio.
Complete Additional Audits

2022 Q4
Support More Bridges and DEXes to increase our stability
Support More NFT Marketplace (NFTrade/Solanart/Magic Eden)
Launch GameFi Infra API/SDK (NFT Disassembly/Gamefi Wallet)
we will start providing GameFi infrastructure solutions and tools to GameFi projects on all supported chains
Multichain Yield Farming Dashboard
This will support all DeFi power users to seek the best DeFi protocol on all supported chains.

2023 Q1
GalaXY Kats Universe Beta
GalaXY Kats will launch a metaverse called GalaXY Kats Universe to invite more NFT projects and game developers. By doing so, we can expand our coverage.
Multichain Yield Farming Pool
Multichain Yield Farming Pool will support all DeFi power users to stake/withdraw their assets on different DeFi protocols via our platform.

/

We will use all of the grant to expand our marketing activities, including but not limited to co-marketing, Cronos cross-chain swap fee rebate campaigns, putting ads on tracking platforms, and more.

We will focus on hosting more co-marketing activities with Cronos-based projects, such as MM Finance, VVS Finance, CronaSwap, Single Finance, DarkCrypto, Ebisu's Bay, and more, in Q2 2022 and Q3 2022. 

We are planning to host cross-chain swap fee rebate campaigns to encourage all of our users to bridgeswap to Cronos over the next three quarters. At present, CrogeCoin is using our swap widget to provide convenience to its community. 

In addition to the aforementioned two points, we also aim to use the grant to increase our awareness on Cronos. We will keep advertising our one-stop cross-chain swap services on Tin Network, Ape Board, Debank, and more platforms to attract more users to march into the Cronos ecosystem.

/

Milestone 1: Integrate BSC, Ethereum, Polyong, Fantom
Milestone 2: Launch our self-developed bridge Y Pool with USDT and USDC liquidity pool
Milestone 3: Integrate Cronos and become the first bridge to allow users to transfer any token to/from Cronos.
Milestone 4: Integrate ThunderCore, Avalanche to expand our XY ecosystem.
Milestone 5: Activiate single-chain trading services on Cronos & ThunderCore and become the first protocol to offer DEX aggregation on these two chains. 
Milestone 6: To integrate KCC on 4/27, expanding our ecosystem to eight chains. "

For more information, check us at:
https://docs.xy.finance/
## Total Budget Requested

150K USD over 6 months span. Funds will go to support product development, daily operation and compensation.

## Maintenance and Upgrade Plans

We will have at least 4 years of continuous support and updates, as well as updates to new features.

# Team

## Team Members

Wilson Huang, CEO
Tesia Liu, Marketing
Rudolph Hsieh, Product
Jesse, Engineering 
Leo, Business Development
Charlie Wang, Strategic Partnership

For company information please visit:
https://www.linkedin.com/company/xy-finance/

## Team Website

https://xy.finance/

## Relevant Experience
XY finance is a team of diversed talents. Each of us come here with various background including finance, engineering, product, marketing, from traditional Web 2 company to buisnesses rated one of the fastest-growing unicorn to Nasdaq in Asia.

Founder Wilson Huang has 8+ years of experiences in crypto field, especially engineering & product development. He is also the founder of Steaker, a centralized finance company with 55M USD asset under management. Previously he was ex-VP of Mithril, and ex-engineer at Yahoo!.

Each of us is still pushing the frontier of knowledge for the Web3 industry and contributed original thinking to the team that you cannot find anywhere else. We strive to provide the best product to scale our impact on the Web3 industry.

## Team code repositories

https://github.com/XY-Finance

# Additional Information

We learn this from Telegram by the Filecoin team.

charlie@xy.finance

Backed by animoca brands, YGG, Infinity Venture Crypto and other well-known Web3 partners, we 

Filecoin is considered to be an unique place in terms of its community culture and the vibrant ecosystem. Having seen more and more interesting projects join to the field, we believe what XY Finance provide can really enable DApps to flourish and make its full impact. 

Now, after backed by animoca brands, YGG, Infinity Venture Crypto and other well-known Web3 partners, we would like to make one step further team up with great teams like you to provide the best solution for all Web3 enthusiasts!

**Comment by ErinOCon** [comment]
Hi @xyfinance-contact, thank you for your proposal! Can this be updated to include a breakdown for the long-term adoption of IPFS and Filecoin? If preferred, we would be happy to connect to discuss integration ideas!

**Comment by ErinOCon** [comment]
Hi @xyfinance-contact, hoping you are well! Were you interested in providing the requested updates?

**Comment by xyfinance-contact** [comment]
Hey there!

Sorry for the late reply, please give us some time as the team is working
on it...appreciate your patience :)

Cheers,
Charlie

'ErinOCon' via contact xy ***@***.***> 於 2022年7月7日 週四 中午12:22寫道：

**Comment by xyfinance-contact** [comment]
Hi team,
Please refer to the reply below.

As XY Finance continues to play a pivotal role in today's multichain
scenario, we have reckoned how important it will be to have a stable, fast
and low-cost service, while the number of our users skyrocket. Integrating
Filecoin/IPFS technology to XY ecosystem will be a win-win for both sides,
as this will improve the overall experience of the XY-related applications,
and will secure a crucial spot for Filecoin in terms of the market of Web3
infrastructure.As a team who aims to build an ecosystem with rooted
community, XY Finance is just our first step in the blueprint. In short, we
focus on how each of the products we built can eventually be connecting
seamlessly under the XY Network as we have been long planning for. To
achieve this, having the computing ability on large data across
organization and distributing petabyte datasets, and preventing accidental
disappearance of important files are the cornerstones to success. Our
planned adoption of IPFS/Filecoin are listed but not limited to below
schedule:

   1. Test and verify IPFS/Filecoin's storage and authorization function in
   testnet: 0-2 months
   2. Adopt functions to deploy on our Dynamic NFT projects: 3-6 months
   3. Further Filecoin/IPFS-based adoptions to other projects: 7-10 months
   4. Strategic partnership with XY's partners based on IPFS/Filecoin's
   service: 11-12 months
   5. New deployment based on XY's product roadmap: 13 months and onward

We believe your applications will be the last piece of puzzles of helping
the XY team build a more connected ecosystem for XY Network and the
Web3 community, and we can't wait to get started!

Thanks,
Charlie


Charlie Wang ***@***.***> 於 2022年7月7日 週四 下午3:03寫道：

**Comment by ErinOCon** [comment]
Hi @xyfinance-contact, thank you for the additional information! We will be in touch with an update shortly.

**Comment by ErinOCon** [comment]
Hi @xyfinance-contact, thank you again for your proposal. We will not be moving forward with this project at this time, but would be happy to consider this grant in the future when the integration of Filecoin/IPFS is more established. If a future proposal is submitted, we would be interested to learn how much data is onboarded as your project progresses. It may be helpful to consider storage helpers like web3.storage or Estuary. 

Wishing you all the best with this project!

**Comment by xyfinance-contact** [comment]
Hi team,
Can we provide our reply here?

Thanks,
Charlie

Charlie Wang ***@***.***> 於 2022年7月7日 週四 下午2:48寫道：
