### ISSUE TITLE
Next Step Microgrant: Nft draw art

### ISSUE THREAD

**Issue by Highflatland** [filecoin-project/devgrants#699]
### 1. What is your project? (max 100 words)
NFT Drawing Art Prototype - Deployed on Mumbai using React, Solidity smart contract, truffle testing, and IPFS file storage.

https://github.com/Highflatland/art
https://nftdraw.art/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Project is using the IPFS file storage.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Adding  support for multiple chains. Cleaning up the code and adding improvements such as canvas size, adding several colors and more drawing tools specifics. 
 
### 4. Is this project open source?
Yes, is open source MIT.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Martin Hoogland, app@nftdraw.art , Developer 
* How did you learn about our microgrant program?
I was checking out Filecoin.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
No.
  * Please link to your hackathon submission
 Not available.

**Comment by ErinOCon** [comment]
Hi @Highflatland, this grant has been approved! We will reach out by email to confirm payment details.
