### ISSUE TITLE
Next Step Microgrant: GoFundYourself

### ISSUE THREAD

**Issue by jjaw** [filecoin-project/devgrants#701]
### 1. What is your project? (max 100 words)
We are GoFundYourself, an IRL tokenization platform to turn your hopes, dreams, and desires into fundable NFTs on the Polygon blockchain using Chainlink, IPFS, Moralis, and NFT.Storage.
[public Github repo](https://github.com/BrianHHough/GoFundYourself)
[live demo Mumbai testnet](https://gofundyourself.netlify.app/)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Immutably stores a project as an IPFS hashed blob on NFT.storage, so that people are held accountable to their commitments and for improved transparency. NFT.storage uses Filecoin agreements to provide long-term storage persistence as an indelible record. Our Worktoken (WKT) smart contract points to the HTTPS gateway as a tokenURI. We also have a separate function that saves the profile picture on IPFS.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
The backend of our APP is complete and the smart contract is only on mumbai testnet. Our primary focus would be completing the front end of the APP. Then we will integrate our smart contract suite as we prepare for mainnet launch. 

First major milestone will be the mainnet launch. We will spend a portion of the grant money on marketing to spread awareness for our APP, GoFundYourself.

Estimated grant breakdown:
$1000 complete APP frontend
$500 UI update
$500 integrate smart contract test suite, mainnet testing

First Major Milestone (~3 weeks in)
$1000 mainnet launch
$1500 social media marketing
$500 grant searching/writing

### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
[Chainlink Spring 2022 Filecoins - Runner’s up prize](https://devpost.com/software/brofundyourself?)
  
### Additional questions:
**For each team member(s), please list name, email, Github account, and role in the project.**
Patrick Santiago / hi@pats.cool / @patonchain / Head designer, maverick
Earl Potters / earl.potters@gmail.com / @Slyracoon23 / Fullstack developer
Riley Desrochers / brofundme0@gmail.com / @RileyDesrochers / Smart contract developer
Brian H. Hough / theinterstellarx@gmail.com / @BrianHHough / Fullstack developer
Arien / vbearc@gmail.com / @ElkiotBear / Designer, front end developer
Will Jaw / will.jaw@gmail.com / @jjaw / Relations, project manager

**How did you learn about our microgrant program?**
From speaking with Discordian, community engineer for Protocol Labs

**Please link to your hackathon submission**
[Chainlink Hackathon](https://devpost.com/software/brofundyourself?)
[Metaverse Hackathon](https://dorahacks.io/buidl/3039)

**Comment by jjaw** [comment]
updated team github

**Comment by ErinOCon** [comment]
Hi @jjaw, this microgrant has been approved! We will send an email to discuss payment details.

**Comment by ErinOCon** [comment]
Hi @jjaw, I hope you are doing well! Please submit your final grant report [here](https://airtable.com/shrrtSlgdVvrPmAvr). If you have any questions, let me know!
