### ISSUE TITLE
Next Step Microgrant: Niftios - Web3 Content Manager and Subgraph provider 

### ISSUE THREAD

**Issue by grmkris** [filecoin-project/devgrants#702]
### 1. What is your project? (max 100 words). 
A dApp don't want to use a typical backend for their data, it wants to use decentralized Web3 tools. The dApp can either save the data directly on-chain or on IPFS and reference to it from the chain. Then TheGraph indexes the changes from the chains and saves it locally to a database. The dApp can then use preformatted and precalculated results from TheGraph for displaying on their frontend.
We will provide a hosted version for that with direct access to an IPFS node to increase the performance.

 
- https://github.com/grmkris/nft-links 
 
- https://www.niftios.xyz/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words). 
IPFS is used for all file storing needs. For differnet usecase we will provide different connectors. 
- Storing NFT metadata - users are able to chose between nft.storage, web3.storage or a regular ipfs node
- Storing Graph configuration files - all files required for configuring subgraphs are stored on ipfs. For better performance we are hosting this ipfs node, as it needs to be hosted near the graph-node
- IPFS file parsing - as we are hosting IPFS node near our graph node, we can process and parse ipfs files inside the subgraph and add loads of interesting usecases. 
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
**Already done:**
- Created Infrastructure
- Deploy subgraph on high performance hosted graph solution with great ipfs integration
- Create requests against the graph node endpoint
- Started to talk to possible custumers to get early feedback and real world insights

**Next steps:**
- Integrate Optimism & Polygon chains and later more chains
- Add authentication agains graph node & IPFS node
- Create a frontend
  - To manage subgraph deployments and access management
  - Show metrics and logs to user
- Develop a GitHub action for usage by the enduser to integrate the flow into their CI/CD
- Talk to more potential customers and onboard them to the system once a working system is up and running
- Decide how to monitarize the service

 
### 4. Is this project open source?
Yes work on user facing systems will be open source, free to use and distribute & modify.
Application for managing NFTs, integrations and connection to the blockchain will be opensource. 
We plan to monetize our work, by also providing paid hosted solution. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, we can make a weekly blog post with the progress.
  
### 6. Does your proposal comply with our Community Code of Conduct?
YES

### 7. Links and submissions 
 - ETHGlobal ETHAmsterdam 2022. We were one of the graph category winners
[ETHGlobal Hackathon Showcase Web3Hunt](https://showcase.ethglobal.com/ethamsterdam/web3hunt-43443)

  
### Additional questions:
  - Kris, [kristjan.grm1@gmail.com](mailto:kristjan.grm1@gmail.com), GitHub: grmkris, Role: TheGraph & UI
  - Adam, [adam.urban@gmail.com](mailto:adam.urban@gmail.com), GitHub: urbanisierung, Role: Fullstack & Business
  - Samuel, [woffiss@protonmail.com](mailto:woffiss@protonmail.com), GitHub: woffiss, Role: Infrastructure & Automation

**- How did you learn about our microgrant program?**
- Email correspondence with Filecoin team

### Explanation for web3hunt -> Niftios
- By building web3hunt we wanted to showcase what can be done by using IPFS for storing content and then posting the pointer to this content on blockchain and then getting this content on client and display it in user friendly way.  
- But we came to realization that infrastructure for making this kind of project is not yet properlly developed, so we want to build an "umbrella solution" that will cover more usecases than web3hunt. 
- Once this project is built a project like web3hunt will be a 1 day project instead of a complex project full of problems.

**Comment by ErinOCon** [comment]
Hi @grmkris, this microgrant has been approved! We will send an email to proceed with payment details.
