### ISSUE TITLE
Open Grant Proposal: Emerald Academy

### ISSUE THREAD

**Issue by jacob-tucker** [filecoin-project/devgrants#704]
# Open Grant Proposal: `Emerald Academy`

**Emerald Academy:** A one-stop-shop for education in the Flow blockchain ecosysten.

**Proposal Category:** `app-dev`

**Proposer:** `jacob-tucker`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

To provide some context, this is Jacob Tucker from Emerald City DAO. Emerald City is the first DAO on the Flow blockchain and has been around for about 8 months. Our goal at Emerald City is to provide education for the Flow blockchain community and to build project/DAO tooling for the Flow ecosystem.

In the last few months, we have started a platform called [Emerald Academy](https://academy.ecdao.org/), a one-stop-shop for all education on the Flow blockchain. We recognized that there didn't exist any education in the Flow ecosystem and wanted to fulfill that need by providing bootcamps, hackathons, and most important to this grant, tutorials. During the months of April, May, and June, we completed an introductory Cadence bootcamp (so 3 in total) to teach the Flow community an introduction to Cadence, which is the smart contract language for the Flow blockchain. We have had around ~20% of graduates achieve paid positions in the Flow ecosystem after completing our bootcamps, a turnout rate that we think is extremely impressive.

Emerald Academy quickly became the largest and most trusted resource for education on Flow. We harness both our bootcamps and Jacob's (the founder of Emerald City) [personal YouTube tutorials](https://www.youtube.com/channel/UCf6DzMRwj7SJ3nPrZqd5hHw) to provide this education.

The reason we are applying for this grant is because, soon, we will be launching a ton of DApp tutorials for the Flow blockchain. If you have heard of [Scaffold-ETH](https://github.com/scaffold-eth/scaffold-eth), one of (if not the most) prominent educational sectors of the Ethereum blockchain, we will be replicating that inside Emerald Academy. We want to leverage IPFS integration into these DApps so that developers learn about decentralized storage through IPFS itself. This way, we can allow the entire Flow ecosystem to learn about decentralized storage, and IPFS will benefit by having the Flow ecosystem recognizing it as the go-to storage network.

## Value

If we are to get this right, IPFS/Filecoin will be used for our DApp tutorials. This means that nearly every single member of the Flow ecosystem that wants to dive into development will learn about IPFS and its benefits along the way. Much like [Scaffold-ETH](https://github.com/scaffold-eth/scaffold-eth), Emerald Academy has and still aims to become the one-stop-shop for education on Flow.

If we do not get this right, IPFS would not be leveraged as a supported decentralized storage option for people learning DApp development, and we would miss out on potentially tens of thousands of developers not knowing how to manage their assets. However, I believe that with this grant, we would have no problem integrating Filecoin into our solutions, so the risks are very minimal.

## Deliverables

The final deliverable of this grant would be between 4-5 completed DApp tutorials hosted and maintained by Emerald Academy. Right now, Emerald Academy consists solely of bootcamps, which you can see here: https://academy.ecdao.org/

If we were to receive this grant, we would be able to build out 4 DApp tutorials including:
1. Voting Tutorial. This is essential for DAO governance.
2. Fungible Token Tutorial. This is required if a DAO wishes to formulate their governance around a token.
3. A contract that formulates "Groups" of people. This would be desired for forming "subcommunities" in a DAO, or groups of voting pools.
4. Multisign Tutorial. To be used for core governance in a DAO.

Each of these DApps would have a README walkthrough that would not only help users complete the DApp, but learn about what Filecoin is.

Here is an example of what a tutorial would look like on our webpage. Note that we would also have a README + Source Code directly in GitHub for users to walk through the tutorial there as well.

<img width="1680" alt="Screen Shot 2022-06-26 at 7 14 48 PM" src="https://user-images.githubusercontent.com/15198786/175837493-06be3243-d29a-48f5-aa62-03c1077bde9d.png">

### **Milestone #1**: Voting DApp Planning & Implementation (Complete by September 14th, 2022) [Amount Required: $15,000]

Jacob Tucker (Ideation + Smart Contract Engineer)
- Come up with a proper user workflow for a Voting DApp
- Figure out the best way to educate Voting concepts to a new user, and how to introduce them to the world of Flow blockchain development
- Implement the smart contracts for a Fungible Token and Voting
- Implement the backend to allow users to mint tokens, vote with their tokens, read balances, transfer tokens, and connect FCL (the Flow Client Library) to their Next.js DApp

pelzzy (Front End Developer)
- To design a front end for a Voting DApp
- To implement the front end for a Voting DApp

### **Milestone #2**: Fungible Token DApp Planning & Implementation (Complete by September 14th, 2022) [Amount Required: $15,000]

Jacob Tucker (Ideation + Smart Contract Engineer)
- Come up with a proper user workflow for a FungibleToken DApp
- Figure out the best way to educate Fungible Token concepts to a new user, and how to introduce them to the world of Flow blockchain development
- Implement the smart contracts for a Fungible Token
- Implement the backend to allow users to mint fungible tokens, read balances, transfer tokens, and connect FCL (the Flow Client Library) to their Next.js DApp

pelzzy (Front End Developer)
- To design a front end for a Fungible Token DApp
- To implement the front end for an Fungible Token DApp

### **Milestone #3**: Groups/Subcommunities DApp Planning & Implementation (Complete by October 14th, 2022) [Amount Required: $25,000]

Jacob Tucker (Ideation + Smart Contract Engineer)
- Come up with a proper user workflow for a Groups (subcommunities) DApp
- Figure out the best way to educate subcommunity concepts to a new user, and how to introduce them to the world of Flow blockchain development
- Implement the smart contracts for an subcommunities
- Implement the backend to allow users to join subcommunities, view other members in their communities, view all available communities, leave their communities, and connect FCL (the Flow Client Library) to their Next.js DApp

pelzzy (Front End Developer)
- To design a front end for a Groups/Subcommunities DApp
- To implement the front end for a Groups/Subcommunities DApp

### **Milestone #4**: Multisign DApp Planning & Implementation (Complete by October 14th, 2022) [Amount Required: $25,000]

Jacob Tucker (Ideation + Smart Contract Engineer)
- Come up with a proper user workflow for a Multisign DApp
- Figure out the best way to educate multisigning to a user, and how to introduce them to the world of Flow blockchain development
- Implement the smart contracts for a multisigning DApp
- Implement the backend to allow users to join "groups" and multisign within those groups, and connect FCL (the Flow Client Library) to their Next.js DApp

pelzzy (Front End Developer)
- To design a front end for a Multisign DApp
- To implement the front end for a Multisign DApp

### **Milestone #5**: Foundation of Emerald Academy Website (Complete by October 1st, 2022) [Amount Required: $20,000]

We need to create a foundational layer inside of Emerald Academy to support DApp tutorials. On our [main webpage](https://academy.ecdao.org/), we only have bootcamps. We want to completely transform the front page so that it becomes clear Emerald Academy is not just for bootcamps, but a one-stop-shop for education on the Flow blockchain. In addition, this would allow people to more clearly find their way around the Academy and find the DApp tutorials.

In addition, we would like to create a landing page for all of our DApp tutorials so that people can get a quick overview of what to expect before diving into some code. For reference, please see the [landing page for Scaffold-ETH](https://docs.scaffoldeth.io/scaffold-eth/) where Austin Griffith, the founder of Scaffold-ETH, introduces folks to the platform.

Mateo (Design & Front End Developer) + Jacob Tucker (Ideation)
- To do all of the requirements listed above

### **Milestone #6**: Support for GitHub Markdown & Video Walkthroughs on Webpage (Complete by October 1st, 2022) [Amount Required: $20,000]

This section includes supporting the GitHub README markdown from all of our tutorials on the webpage itself. That way, people who follow our DApp tutorials can choose to follow the walkthrough on our webpage itself, if they are not comfortable staring at GitHub READMEs.

For reference, you can see what Scaffold-ETH does on Ethereum. They have DApp tutorials through GitHub, like so: https://github.com/scaffold-eth/scaffold-eth/tree/simple-nft-example, however they also support viewing this content on their main webpage, like so: https://docs.scaffoldeth.io/scaffold-eth/challenges/simple-nft

For each of our DApps, we would have to create a webpage for them on the Emerald Academy site, and continue to maintain all of them + future DApps to come out. In addition, we will have video walkthroughs of all of our DApps to be hosted on YouTube and linked through our website to provide a truly immersive experience for learners and developers.

ItzFantastic (Front End Developer)
- To create the webpages for each DApp 
- To allow users to easily copy + paste code from webpage to terminal (and elsewhere)
- To allow for easy discoverability and users to click through individual sections of the tutorials

Jacob Tucker (Video Creation)
- To create the video walkthroughs for each DApp

## Total Budget Requested

$120,000

| Milestone | Date | Amount | For |
| ------- | --- | --- | --- |
| 1 | 09/01/2022 | $5,000 | Smart Contract Development |
| 1 | 09/14/2022 | $5,000 | DApp Development |
| 1 | 09/14/2022 | $5,000 | Design & Frontend |
| 2 | 09/01/2022 | $5,000 | Smart Contract Development |
| 2 | 09/14/2022 | $5,000 | DApp Development |
| 2 | 09/14/2022 | $5,000 | Design & Frontend |
| 3 | 10/01/2022 | $10,000 | Smart Contract Development |
| 3 | 10/14/2022 | $7,500 | DApp Development |
| 3 | 10/14/2022 | $7,500 | Design & Frontend |
| 4 | 10/01/2022 | $10,000 | Smart Contract Development |
| 4 | 10/14/2022 | $7,500 | DApp Development |
| 4 | 10/14/2022 | $7,500 | Design & Frontend |
| 5 | 11/14/2022 | $10,000 | Design & Frontend of Main Page |
| 5 | 11/14/2022 | $10,000 | Design & Frontend of Landing Page |
| 6 | 11/01/2022 | $5,000 | Markdown + Video #1 |
| 6 | 11/01/2022 | $5,000 | Markdown + Video #2 |
| 6 | 11/01/2022 | $5,000 | Markdown + Video #3 |
| 6 | 11/01/2022 | $5,000 | Markdown + Video #4 |

## Maintenance and Upgrade Plans

Emerald Academy belongs to Emerald City DAO. Emerald City will continue to maintain this platform indefinitely in an effort to onboard members into the Flow ecosystem and educate the future of the Flow blockchain.

# Team

## Team Members

Jacob Tucker - the founder of Emerald City DAO and one of the first smart contract developers in the Flow ecosystem. I built the smart contracts for [MotoGP Ignition](https://motogp-ignition.com/), created a community of over 15,000 members, and write smart contracts for [Dapper Labs](https://www.dapperlabs.com/) on occasion. 

Mateo Roldos - a member of the [EME Studios](https://www.instagram.com/emestudio.dev/) team, an amazing front-end team that helps Web3 projects.

pelzzy - a contributor of Emerald City DAO, pelzzy has helped to build some of our frontends for our various projects.

ItzFantastic - like pelzzy, ItzFantastic is a contributor of Emerald City DAO and has helped to build some of our frontends for our various projects.

## Team Member LinkedIn Profiles

As a member of the Web3 community, and as the founder of a large organization, I do my best to respect the privacy of our contributors at all times. Thus, I will only be able to provide my LinkedIn profile, and will be happy to provide further details over private DM or email.

Please note: My LinkedIn is very out of date, because I never use it: https://www.linkedin.com/in/jacob-tucker-7435221b1/

## Team Website

https://ecdao.org/

## Relevant Experience

Emerald City DAO has become a very influential community on the Flow blockchain. We harness the most engaged developer community in the Flow ecosystem and constantly output different projects in the space. 

One of them is [FLOAT](https://floats.city/), a POAP-like platform for the Flow blockchain. In the last 2 months, we have seen almost 2 million NFTs minted on the platform. It has continued to scale exponentially as users are not required to whitelist their events like they are on POAP.

We have also built [Emerald bot](https://bot.ecdao.org/), a Collab.Land-like Discord bot to gate access to channels + roles based on asset holdings. Nearly every single community in the Flow ecosystem uses Emerald bot, including [NBATopShot](https://nbatopshot.com/), [UFC Strike](https://www.ufcstrike.com/), [NFL All Day](https://nflallday.com/), [Matrix World](https://matrixworld.org/home), [Flowverse](https://www.flowverse.co/), and more.

Lastly, as mentioned, we created [Emerald Academy](https://academy.ecdao.org/), which has become the most popular avenue for learning Flow blockchain development in the ecosystem.

## Team code repositories

We built FLOAT, a POAP-like platform for the Flow blockchain: https://github.com/muttoni/float
We build Emerald bot, a Collab.Land-like Discord bot to gate access to channels + roles based on asset holdings: https://github.com/emerald-dao/emerald-bot

# Additional Information
How did you learn about the Open Grants Program?
Another member of the Filecoin ecosystem: bz

Please provide the best email address for discussing the grant agreement and general next steps.
jacobtucker818@gmail.com

**Comment by ErinOCon** [comment]
Hi @jacob-tucker, Thank you for your proposal! Before proceeding, can you provide verifiable information on the size and quality of the expected audience for this work? Also can the development roadmap be updated to include the following: 

- Storage functionality (such as web3.storage or nft.storage)
- A milestone breakdown with multiple phases (2 or 3) with content creation, participation, and maintenance. 

[Here’s a tutorial](https://nftschool.dev/tutorial/flow-nft-marketplace/) showing expected outcomes! Please let us know of any questions or feedback.

**Comment by ErinOCon** [comment]
Hi @jacob-tucker, thank you for your reply! We will be in touch once our review is complete.

**Comment by ErinOCon** [comment]
HI @jacob-tucker, thank you for your patience with our review. Would you have an interest in providing updated tutorial plans for this project with a focus on DAO Tooling? We anticipate this being a high user need!

**Comment by ErinOCon** [comment]
Hi @jacob-tucker, I hope you are doing well! Do you have any feedback or questions regarding the DAO tooling focus?

**Comment by jacob-tucker** [comment]
Hi @ErinOCon ! Yes, we could absolutely switch the focus to DAO tooling instead. I'd imagine that, instead of making tutorials based on NonFungibleTokens or FungibleTokens, you would prefer something like:
1. Voting Contract
2. Multisign Contract
3. A contract that formulates "Groups" of people

Is this along the lines of what you were thinking as well?

**Comment by ErinOCon** [comment]
Hi @jacob-tucker, thank you for the quick reply! Our team will be in touch with an update early next week.

**Comment by ErinOCon** [comment]
Hi @jacob-tucker, thank you for your quick reply with these updates! This grant has been approved! Before moving forward, can you update your proposal to incorporate the revised focus? We would like to ensure the grant agreement captures your work correctly.

**Comment by jacob-tucker** [comment]
Yaaaaay @ErinOCon ! We are so excited! I have just updated the grant proposal to include the 4 new DApps. If you think a 5th DApp would be appropriate, we could update the milestones + budget required. In addition, if you believe NFT voting would also be benefitial in addition to Fungible Token voting, we could do the same and add another DApp tutorial.

Thanks so much! We will kick butt on this

**Comment by jacob-tucker** [comment]
Hi there again @ErinOCon ! Wanted to thank you again for moving forward with this. We have already made significant progress on the voting DApp tutorial.

 In terms of how grants are paid out, are they usually done in milestones? And how is the grant distributed once pay is to go out? If it is done in milestones, should I continue to post updates here when they are reached?

Hope you're having a nice day! <3

**Comment by ErinOCon** [comment]
Hi @jacob-tucker, thank you for your patience with our review. This grant has been approved! We will send an email this week with next steps. 

In regards to the pay out schedule, the grant will be distributed in installments after each milestone check-in. We will send more details regarding this process by email.

**Comment by jacob-tucker** [comment]
Hi @ErinOCon ! No rush, but just wanted to ping that we didn't receive an email just yet. Hope all is well and have a great weekend <3

**Comment by ErinOCon** [comment]
Hi @jacob-tucker, thank you for being in touch! I have just sent a new email. Can you confirm if this was received?

**Comment by jacob-tucker** [comment]
Hey there @ErinOCon ! Yes, I have received the email and already filled out the OSA document. Hopefully all the information is enough to continue forward :)

Thank you!
