### ISSUE TITLE
Next Step Microgrant: <AgroforestDAO>

### ISSUE THREAD

**Issue by DiogoJorg3** [filecoin-project/devgrants#705]
### 1. What is your project? (max 100 words)

We want to create a Learn2Earn system where apprentices are incentivized to level up while accessing land to produce food, steward seeds & create content through monthly journals NFTs. The NFT's sales will distribute royalties for the DAO's multisig and the apprentice's wallets as a scholarship, while building a database of Agroforestry experiences matched by metadata info on biorregion, food processing practices, stewarded seeds and species. Soulbound NFTs will allow for leveling up, reputation building and specialization on specific fields of food production. 

 we are being incubated by the Bloom Network https://bloomnetwork.org/
 https://t.co/0myyP91xQr , https://twitter.com/agroforestDAO

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
We want to create a ever growing storage of qualitative agroforestry personal data that can be accessed by members. It will be part of a global Food Forest Commons, with searchable educational content and internships, food processing techniques, etc and a seasonal newsletter helping to sync and coordinate the global community.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We will use it to build online community and the digital infrastructure, launch the first IRL apprenticeship MVP, and start the Journals NFT Collection
 
### 4. Is this project open source?
Yes, will be

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Agree 100%
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes it does comply

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Started on a hackathon but we didnt submit it to Protocol Labs prizes
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Diogo Jorge -  moradavivald@gmail.com ; https://github.com/DiogoJorg3 ; Founder, community builder, product manager
Magenta Ceiba - imaginationhealer@gmail.com ; https://github.com/magentaceiba ; Founder, chief dev
Darina - darina@agrivero.ai ; Founder ; community builder
* How did you learn about our microgrant program? ReFi DAO Discord
* If your project was created as part of an event or hackathon: Yes
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) Planet Positive ReFi DAO Hackathon
  * Please link to your hackathon submission
  It started at Planet Positive ReFi DAO Hackathon, we were awarded 3rd place: https://blog.refidao.com/planet-positive-nft-hackathon/

**Comment by ErinOCon** [comment]
Hi @DiogoJorg3, thank you for your proposal! Can you provide a link to the project repo (and anywhere else we can review building progress)?

**Comment by DiogoJorg3** [comment]
Hi @ErinOCon thanks for the reply! We are working on launching a series of rooted events in Brazil and streaming online, where we will experiment with NFT based gated access experiences, membership passport, auctions, possible rewards and contribution, fractionalized food forests and other culturally rooted interactions. We are gathering with experienced devs to create contracts and a repository. Will let you know when we are done. If you can provide us some help or training regarding these kinds of contracts would be pretty nice.

**Comment by ErinOCon** [comment]
Hi @DiogoJorg3, I hope you are doing well and that your event series is gaining traction! To clarify, you are interested in picking up on this grant request once the even series is over?

**Comment by DiogoJorg3** [comment]
Hi, Thanks for the contact and the wishes. Our event is gaining traction, indeed! We want to use it to kickstart our food forest commons social network. We are launching a landing page and a discord, but are studying and testing Lens.xyz as the home for the profiles in our community. A key element in our network is the creation of content as journals, which are supposed to be stored onchain. However we have a small team of volunteer devs and project managers. I keep building the community and we are growing with more people realizing the importance of creating reputation, positive sum social algoritms and leveling up possibilities. 
I believe Filecoin can be a key tool for our collective intelligence, looking forward to be able to use it, asap, wish we could be fully dedicated to that.


-- 
 Enviado de forma segura com Tutanota. Obtenha a sua caixa de correio criptografada, sem publicidade. 


2 de ago. de 2022 19:09 por ***@***.***:

**Comment by ErinOCon** [comment]
Hi @DiogoJorg3, glad to hear the event was a success! Can you confirm how you will use IPFS? Will you be using a specific service like nft.storage?

Also, you mentioned in your proposal that you would be building an online community/digital infrastructure, launching the first IRL apprenticeship MVP, and starting the Journals NFT Collection. Can you specify the practical next steps you will take over the next three months to achieve some of these goals?

**Comment by ErinOCon** [comment]
Hi @DiogoJorg3, I hope you are doing well! Do you expect to have a new update available this week?

**Comment by DiogoJorg3** [comment]
Hi!
We are moving forward. Just met a dev that has created a minting page for NFTs and can adapt it to our needs (change distribution of royalties and metadata, mainly). It is stored on IPFS. Here is the page, still on testnet Kovan: 
http://taodao-nft.web.app/

Our first pilot will be to create a collection of agroforestry apprentices journals. An attempt to monetize in their shared learnings becoming a scholarship. Later on we will also create SBT profiles, credentials and different forms of incentives. 
Thanks for being present, sorry for the delay. It just happened this last week. 
Cheers,
Diogo

-- 
 Enviado de forma segura com Tutanota. Obtenha a sua caixa de correio criptografada, sem publicidade. 


23 de ago. de 2022 10:04 por ***@***.***:

**Comment by DiogoJorg3** [comment]
Hi there!

we are building a web3 structure of a rooted social media and community around a NFT minting platform for different use cases such as governance, geolocation, identity, badges, carbon and royalties. 

Would love your opinion about it: https://rooted-club.web.app/

Cheers,
Diogo
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Aug 23, 2022, 10:04 by ***@***.***:

**Comment by ErinOCon** [comment]
Hi @DiogoJorg3, thank you for the Rooted Club link. Before proceeding with our review, I would like to confirm if a repo link will become available to review developer progress. Many thanks!

**Comment by ErinOCon** [comment]
Hi @DiogoJorg3, this item has been closed as a repo link is needed to review developer progress. Please feel welcome to reapply once your code and a prototype is available for review.
