### ISSUE TITLE
Next Step Microgrant: Decentralized-DropBox

### ISSUE THREAD

**Issue by DireWolf707** [filecoin-project/devgrants#707]
### 1. What is your project? (max 100 words)
Another IPFS/Filecoin based decentralized storage and management solution but Different. Its not just a standalone dApp but with a vision to be an extension for all other dApps utilizing IPFS.

Before writing this I have gone through previous project's applications with similar goals, but haven't come to mainstream because mostly focused on being a standalone dApp without any target audience or any hook other than incentive mechanism which is good but useless without users. 

My approach is to integrate it with other popular dApps which are already in mainstream to target users which are already familiar with web3 space and utilizing its offerings.

Github: https://github.com/DireWolf707/Decentralized-DropBox
Demo: https://youtu.be/l1ZY2MBnIHw

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
IPFS and Filecoin will be used to store and persist huge and large amount of data at hypercompetitive prices.
Combining the two networks we get the best of both worlds: IPFS for content addressing & data discovery, and Filecoin for longer-term persistence.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
I have divided further development of project in 3 phases :

- ### Phase I : Implementing all basic functionalities a cloud storage must have
It consist of redesigning UI/UX, adding micro-animations and basic functionalities such as search, sort, share, change file directory, hide/archive files, etc.

- ### Phase 2 : Integrating with other popular dApps utilizing IPFS
Some Examples -
1. Integrating with NFT marketplaces to mint NFTs directly from files uploaded to *Decentralized-DropBox* (already implemented and illustrated in demo video)
2. Integrating with video communication dApp such as Huddle01 to not only share files in chat but also to save recordings directly to *Decentralized-DropBox* instead of choosing from default options at end of each call (download/email link/display IPFS link)
3. Integrating with songs and video sharing dApps (such as Audius and D.tube) to directly share file from *Decentralized-DropBox*

and many more in future including popular social media dApps if feasible

- ### Phase 3 : Implementing profitable features
1. Incentive system
2. DAO
4. Payment Integration
5. Paid Storage 
etc.

### 4. Is this project open source?
Yes the project is and always will be open source.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, I agree to share grant reports upon request, including a final grant report at the end of the three month period
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: Yes I had submitted and won for best use of IPFS and/or Filecoin
https://devfolio.co/projects/decentralized-dropbox-db03
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Rahul Sood | rahulsood707@gmail.com | [github](https://github.com/DireWolf707) | Fullstack Developer
* How did you learn about our microgrant program?
Through email from member of 'Hackathons team at Filecoin / IPFS' after winning prize in hackathon.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  [Electrothon 4.0](https://electrothon-4.devfolio.co/)
  * Please link to your hackathon submission
  https://devfolio.co/projects/decentralized-dropbox-db03

**Comment by ErinOCon** [comment]
Hi @DireWolf707, this microgrant has been approved! We will send an email to confirm payment details.
