### ISSUE TITLE
Next Step Microgrant: retrox

### ISSUE THREAD

**Issue by jan-o-e** [filecoin-project/devgrants#709]
### 1. What is your project? (max 100 words)
Retrox implements a novel mechanism for funding public goods that add the most value to humanity by combining both retroactive and future (re-generative) funding of public good projects into a single on-chain protocol. The funding procedure has four components: rounds, nominations, voting and disbursement. Anyone will be able to fund and initiate a round with a particular theme like open source blockchain software or AI safety research. Sybil resistance is ensured by a curated whitelist of expert voter addresses which is provided by the round initiator (we aim to improve this aspect in future) and spam protection is ensured by providing a stake to nominate. Once nominations are in, voting is executed by the whitelisted experts. Round data including a whitelist and nomination data is automatically uploaded to IPFS. The smart contract, which is deployed on Optimism handles the voting and disbursement. We aim to implement variable voting logics (ranked preference, quadratic, perhaps MACI etc.) and variable funding disbursement (variable amounts of streaming & retroactive funding).

https://github.com/Retrox-PGF
https://retrox.xyz/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
 We use the js-ipfs library in our project to automatically upload data to IPFS upon interacting with our platform frontend. Firstly, the round details, which includes data such as instantiation timestamp, funding amount, theme & curated list of whitelisted experts at the round initiation are parsed to IPFS once a round is initiated by a funder. Moreover, the nominations for a particular round have a profile with a description, address & contact and these profiles are also automatically uploaded to IPFS, such that the contract can interact with them and such that they are transparently accessible. The voting results of past rounds are also uploaded to IPFS so that they are accessible for a full evaluation of past funding rounds.
 
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We’d like to improve the core project developed during the hackathon to make it as modular and customizeable as possible such that we can run some small scale experiments to test our platform and address various use cases. Currently we’ve implemented a quadratic voting module, but we will in future we want to include an actualization of Linear Voting, Ranked Preferences, Conviction based voting and at least explore the possibility of including Adjusting Quadratic Mechanisms for Pre-Existing Cooperation (or another anti-collusion implementation). Developing metrics for impact evaluation is also a domain we’d like to explore and winning the grant would allow us to dedicate more time to this. Improved metrics, both qualitative and quantitative could really aid in improving the efficacy of public goods funding into the future. Moreover, we’d also like to modularize fund disbursement such that there are variable amounts of upfront funding & streaming (which can be stopped if certain criteria are not met). Lastly we’d also like to expand on the past round evaluation tools and data science by fetching the voting, nomination and round data from IPFS to improve future funding rounds.

Every single team member is either studying or working alongside the work we do on retrox and winning this grant would give us the financial freedom to dedicate more time to working on retrox in the immediate future. We have pretty concrete timelines on implementing and testing these goals. Modularize and test voting schemes by end of July, modularize fund disbursement by end of August and by end of September have an idea of the possibilities for evaluating impact more concretely and implement more data visualization tools.

There are a few fixed costs we have to cover: ENS, website domain & paying for Vercel premium to host our MVP website which we could cover with this grant. This would allow us to receive external grants more transparently and host our site more professionally. These objectives are straightforward to meet.
 
### 4. Is this project open source?
Yes - it is MIT licensed.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes - we agree to share a final grant report.
  
### 6. Does your proposal comply with our Community Code of Conduct?
We have read and acknowledged the Filecoin Code of Conduct.

### 7. Links and submissions
https://showcase.ethglobal.com/ethamsterdam/retr0x-2p73o - our project began at the ETHGlobal Hackathon in Amsterdam in 2022.  

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
- Jan Ole Ernst - jan-o-e, janole7399@gmail.com, Theoretical development of voting logics and impact evaluation. IPFS & Contract integration, as well as some Solidity development.
- Orlando Fraser - Orland0x, orlandothefraser@gmail.com, Full time solidity dev, smart contract lead, particularly for voting and overall contract architecture
- Kyle Duffy - kyduff, kyle.duffy@oriel.ox.ac.uk, Full stack dev, focus on dev-ops and integration of contract with ipfs and frontend
- Jessica Pointing - jessicapointing, jqpointing@gmail.com, solidity focussed dev, lead on Superfluid and fund disbursement
- Konrad Kopp - kopy-kat, kopp.konrad@gmail.com, front-end dev
- Fernando Almansa - FerAlmansa01, fernando.almansamorenodebarreda@oriel.ox.ac.uk, data science and front-end dev

* How did you learn about our microgrant program?
Through an email to us from Niki that was sent out after the EthGlobal Hackathon.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
https://showcase.ethglobal.com/ethamsterdam/retr0x-2p73o - our project began at the ETHGlobal Hackathon in Amsterdam in 2022.

**Comment by ErinOCon** [comment]
Hi @jan-o-e, this microgrant has been approved! We will send an email to confirm payment details.
