### ISSUE TITLE
Thailand community development program by Spectre team

### ISSUE THREAD

**Issue by Isabellabcj** [filecoin-project/devgrants#713]
# Open Grant Proposal: 

**Name of Project:** `Filecoin NFT University Roadshow in Thailand`

**Proposal Category:** `community` 

**Proposer:** `Xyclopz`

**(Optional) Technical Sponsor:** `N/A`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Please respond with either "Yes" or "No"
Yes

# Project Description

We’re Spectre Esports, an esports agency and event organizer based in Bangkok, Thailand. We have been around in a crypto scene of Southeast Asia for awhile and noticed that despite the rapid growing of the blockchain industry, the main problem of this region is the lack of NFT/Blockchain education and also events to support the scene in a long run.

We have met Filecoin through Mr. Panisuan. Mr. Panisuan approached us and introduce us very well about how Filecoin works. That time we were in a process of making NFT Game called Buddy Beater and were interested in working with Filecoin on the Open Grants Program. However, me and some co-founder has left the game project due to internal management issue.

We still believe in the vision of Filecoin on elevating the scene and give people knowledge for a healthy blockchain scene in SEA. We came up with an event plan called “ Filecoin NFT Universities Roadshow” which is the series of 5 event in Thailand top universities with the intention of educating youngster and introduce them to a brand of Filecoin. This series will be the first appearance of Filecoin brand in SEA region. We focusing on make hte best experience for attendants and create a community for Filecoind.

The Filecoin NFT University Roadshow will be just the beginning of our master plan to market Filecoin in the SEA Region. We believe in the principle of Filecoin and will do our best to make Filecoin known by everyone the SEA blockchain industry.

Over the course of 5 months (Jul 2022 - Nov 2022), Spectre to provide Filecoin with the following services: 

Host the Filecoin NFT University Roadshow 5 events dating from July 1st 2022 to November 30th 2022. The events will be located in Universities in Bangkok, Thailand.
Spectre Esports shall use its professional knowledge to provide Filecoin consultation and also pre-event PR
Running the event, decorating, lecturing, photography, and livestreaming services
Hand filecoin the video highlights of each event and deliver the post event report.

## Value

The benifits of this project is the completion of Filecoin ecosystem by having a constantly events running in SEA, starting from Thailand. Spectre Esports will also use its well connection to introduce the project to important Blockchain people in the region. The Filecoin NFT Universities Roadshow will spark the light of education and branding of Filecoin that can be led to a sustainable marketing plan. The ultimate goal of this project is to have Filecoin Thailand up and running to increase user base of Filecoin here in SEA.

## Development Roadmap

Event 1: July 12th 2022

Event 2: August 2022 (The date is to be confirmed)

Event 3: September 2022 (The date is to be confirmed)

Event 4: October 2022 (The date is to be confirmed)

Event 5: November 2022 (The date is to be confirmed)

Details event format could be found [here](https://drive.google.com/file/d/1lD1FLdOA7_jB9gnwl0-fmDViYEktof8v/view?usp=sharing)

## Total Budget Requested

Payment 1: 31,000 USD Upon signing in to opengrants to kickstart the project, lock the venue, speakers, and build structures.

Payment 2: 18,600 USD (30%) to be paid within 14 days after the completion of 3 events.

Payment 3: 12,400 USD (20%) to be paid within 14 days after the completion of 5 events.

## Maintenance and Upgrade Plans

# Team

## Team Members

Treepob Tiangtrong - CEO
Dulyapat Wongkitchvanich - COO
Prompan Changkarndee - CFO
Punch Apiwat - Project manager
Satchukorn Bouthoung - PR Officer
Chaiyasit Tolanuwat - Account Executive
Pongpitch Sawasdichan - Content creator
Jiraphat Sriasawaprasert - Content Creator
Jirawut Wangworapinyo - Graphic Designer
Narintorn Lanoksrikhan - Project Coordinator
Anusorn Rammasong - Video Content Creator
Siriwat Sukha - Social Media Managers

## Team Website

facebook.com/spectre.th

## Relevant Experience

Our Spectre Esports Co.,Ltd has been in the esports agency and event organizer since 2020. With a headcount of 20, we hosted major events such as Thailand Game Talent Showcase 2022 a game developers competition event to find the best project in Thailand and connected them with investors. The event was sponsored by Bitkub, a cryptocurrency exchange in Thailand. It was a hugh success and bring joy to all parties.

On May 29th we hosted another major event, a 2 years anniversary party for Ragnarok online game (TH Division) on a ship at Asiatique. With more than 500 attendants, We have been praised by the ROTH on how well we manage the event.

Our company is also an expert on educational part of esports industry. We host countless of workshops in schools, universities, and malls teaching youngster about career in esports industry. 

Event organizing, marketing, and education is what we love to do wholehearted.

## Team code repositories
N/A

# Additional Information
 Recommend by Isabella
 treepob@spectreth.com 
[ Link](https://drive.google.com/file/d/1lD1FLdOA7_jB9gnwl0-fmDViYEktof8v/view?usp=sharing)

**Comment by jochasinga** [comment]
I'm really excited to see this happen! It's been brewing for a while though @realChainLife can we expedite this one?

**Comment by ErinOCon** [comment]
Hi @Isabellabcj, this grant has been approved! For next steps, please email grants@filecoin.org.
