### ISSUE TITLE
Planting of fruit trees in schools, health centres and distributing to communities (Ecosystem Restoration)

### ISSUE THREAD

**Issue by JJonathanOlwenyi** [filecoin-project/devgrants#714]
### 1. What is your project? (Climate Solutions) PLANTING FRUIT TREES IN SCHOOLS, HEALTH CENTERS & DISTRIBUTE TO COMMUNITIES/ECOSYSTEM RESTORATION

 john jonathan olwenyi
 https://www.ayoweccauganda.org

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
  Increasing plantation in the project area.
Enhancing the understanding of Climate change issues.
Building the capacities of the community in planting trees and maintaining forest cover to maximize their livelihood generation.
Raising awareness on Climate change/global warming and good security.
To establish and maintain maximum tree cover.
To maintain trees in a healthy condition through good cultural practices.
To establish and maintain an optimal level of age and species diversify.
To promote conservation of tree resources.
To select, situate, and maintain street trees appropriately to maximize benefits and minimize hazard, nuisance, hardscape damage and maintain costs.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
To reduce the impacts of Climate change in Uganda and ensure that the natural environment is used wisely and continues to be available for the benefit and enjoyment of future generations by buying more seeds, growing more seedlings, tree planting fruit trees in schools, health centers and distributing to communities, training local farmers for a sustainable food security and increase forests and forest covers. workshops, creating awareness on climate change and environmental protection
 
### 4. Is this project open source?
YES

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
YES
  
### 6. Does your proposal comply with our Community Code of Conduct?
YES
Our project is 100% to benefit public (community).

### 7. Links and submissions
https://gitcoin.co/grants/4014/agroforestry-climate-change-forests-and-ecosystems

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project. JJONATHAN OLWENYI, AGATHA NANYIRE, AWOR CATHERINE
* How did you learn about our microgrant program? Through Gitcoin Administration
* If your project was created as part of an event or hackathon: Gitcoin climate solutions
  * What was the name of the event? climate solutions
  * Please link to your hackathon submission https://gitcoin.co/grants/4014/agroforestry-climate-change-forests-and-ecosystems

**Comment by ErinOCon** [comment]
Hi @JJonathanOlwenyi, can you describe how you will use Filecoin, IPFS, or related technology to support your work?

**Comment by ErinOCon** [comment]
Hi @JJonathanOlwenyi, thank you for your reply. It doesn't appear that this work meets our grants criteria. In order to be eligible, the project should be actively building with Filecoin, IPFS, or related tech. Please feel welcome to consider this program for future work that has a prototype and evidence of building progress.
