### ISSUE TITLE
ENHANCING AGROFORESTRY/PERMACULTURE FOR PROMOTION OF CLIMATE CHANGE RESILIENCE AND RURAL LIVELIHOODS IN TORORO DISTRICT & EASTERN UGANDA

### ISSUE THREAD

**Issue by JJonathanOlwenyi** [filecoin-project/devgrants#715]
# Open Grant Proposal: ENHANCING AGROFORESTRY/PERMACULTURE FOR PROMOTION OF CLIMATE CHANGE RESILIENCE AND RURAL LIVELIHOODS IN TORORO DISTRICT

**Name of Project:** PLANTING FRUIT TREES IN SCHOOLS, HEALTH CENTERS AND DISTRIBUTING TO COMMUNITIES.

**Proposal Category:** Choose one of `core-dev`, `app-dev`, `devtools-libraries`, `integration-adoption` , `technical-design`, `docs` , `community` , `metaverse` , `research` , `green`  Learn what these categories are here: https://github.com/filecoin-project/devgrants/tree/master/open-grants#readme CLIMATE SOLUTIONS AND ENVIRONMENTAL PROTECTION

**Proposer:** `JOHN JONATHAN OLWENYI

**(Optional) Technical Sponsor:** `NAN

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Please respond with either YES or No.  
Yes

# Project Description

Climate change is a fact, and it is widely acknowledged that the world is in the midst of a global warming crisis. Human activities such as fossil fuel combustion and land use change have released greenhouse gases into the atmosphere, which is the primary driver of recent climate change. Land use such as agriculture alone, discharges more than 6 billion metric tons of greenhouse gases (GHG) into the atmosphere each year. Because of the increased severity of climate change impacts in some areas, the consequences have been more severe and disastrous.
In Uganda, Climate change is a serious problem, affecting livelihoods. The country experiences prolonged drought, short and erratic rains which are disastrous and affecting agricultural production the backbone of the country. Also, due to disparities in traditional roles, societal expectations, and livelihoods, men and women are affected differently by climate change. Women account for the bulk of Uganda's population of 23.19 million people. They have lower wages, less access to credit and decision-making power, and less control over resources, all of which make them more vulnerable to climate change. It’s therefore important to consider differences when tackling the issue of climate change. 
Agroforestry/permaculture has emerged as a major instrument in the fight against climate change in recent years. It's a widely accepted answer to the twin problems of climate change and food security. It's one of a number of innovative strategies targeted at increasing production while also assisting in the mitigation of climate change by increasing carbon sequestration and boosting the system's ability to cope with the negative consequences of climate change.This project aims to promote agroforestry/permaculture for climate change mitigation and the development of vulnerable groups' livelihoods, such as women, by planting fruit trees alongside food crops.

FOOD INSECURITY AND CLIMATE CHANGE

By planting fruit trees, we shall have a future with sustained food security among communities, increase plantations, forests and forest covers
Train local farmers to setup local farms increase agroforestry and permaculture for them to be economically empowered.
1.	To sensitize stakeholders on the importance of Agroforestry/permaculture
2.	To form groups among communities and train them in agroforestry practices.
3.	Enhance capacity of 500 households in 20 groups raise and plant seedlings on their individual/community farms alley crops.
4.	Establish nursery beds for raising seedlings to supply schools and  health centers across Eastern Uganda.

## Value

Having been in the field of tree planting, being a community founded organizationand familiarity with the operational areas, AYOWECCAUGANDA believes and it’s confident that they meet all the criteria for selection.
AYOWECCA UGANDA will has a monitoring and evaluation (M&E) plan to cover the 5 years. The M&E plan will be developed in consistency with the National Strategic Plan performance monitoring and management plan.
For each activity, there will be an expected output, verifiable to indicator to measure the achievement of the respective out puts and the annual possible variances.
The project will conduct Community outreach awareness in the form of demonstration to Climate change and Adaptation animations to educate the target Communities.
Once each month AYOWECCA UGANDA staff members will be responsible for oversight monitoring of the project and will supervise the implementation of activities by monthly site overview meetings of activities, prepare monthly (quarterly) reports detailing the status of the project, a review will be conducted on the general progress of the project

It is expected that female and male will continue to benefit from this project especially on issues of adaptation, resilience and mitigating effects of Climate change situation, youth participant will challenge their view on the subject matter and ehaust the pros and cons in Climate change and energy issues as in direct recipients.
As Climate change gains more and more importance, we cannot forget to integrate gender in our approaches to address it.

Economic empowerment, sustainable food security,

We expect a positive impact on the community through our actions like a drastic increase in the forest cover and better food security for the people.
However there are also unavoidable risks such as natural disasters, with the increasing global surface temperatures the possibility of more droughts among other effects are most likely to occur.

Lack of enough fundings, transport, political issues, drought/pest and diseases, hostile communities, gender discrimination in the fight for environmental justice

## Development Roadmap

So far with the grant we received from gitcoin, we managed to restore 3 wetlands, as per today planted fruit trees in 29 schools, 17 health centers and distributed 8000 to communities, we can provide details if selected or checkout our weekly twitter updates 
 we wish to plant fruit trees per phase, buying seeds, seedlings, transport, IT equipment, establishing a green house
 Our team will take photos and upload on a google drive that will be share with you after ever 3 months of the project life cycle.
 12
$15000 per milestone
 we intend to plant more than 1000000 tree seedlings

## Total Budget Requested

$30000

## Maintenance and Upgrade Plans

AYOWECCA UGANDA is a community founded Organization that will continue it’s operation to monitor and follow up with the progress, growth of trees planted and adaptation measures even after the project years. 
There will be full community engagement/participation and empowerment in this project.
Creating sustainability of the interventions at the grass root levels.
To improve adaptive capacity of the rural poor engagements on planting trees and other measures to cope with Climate variability.
Planning, service provision and implementation of Climate change adaptation components will risk assessment, planning, service provision and implementation of Climate adaptation interventions like implementation of Climate adaptation interventions in Agriculture by Community institutions (self-help groups) utilizing the community Climate upon approval of a community adaptation plan.
Provision of strategic Climate change adaptation services through knowledge assimilation and partnership with resource institutions.
Community lead risk assessment and participatory planning of climate change adaptation interventions.
Scaling and mainstreaming Community-based Climate adaptation component will enable support and build capacity for the implementation of Climate adaptation interventions and to develop the strategy for scaling up.
AYOWECCA UGANDAwill invest in establishment of adaptation units staffed will full-time professional within project participating areas of Uganda, and Establishment of a monitoring system and evaluation arrangements (baseline, mid-term, end-of-term and after-of-term).

# Team

## Team Members

John Jonathan Olwenyi
Awori Catherine
 Agatha Nanyire
 john jonathan olwenyi
Agatha Nanyire
Awori Catherine
 https://www.ayoweccauganda.org

## Relevant Experience

We are a team of 7 stuffs and 5 volunteers. We have 3 years of experience working with the local community. our team will always compile monthly reports on the progress of the project and participate in the monitoring and evolution. Our work was centered in one district we now want to expand it to parts of the region. 

## Team code repositories

https://gitcoin.co/grants/4014/agroforestry-climate-change-forests-and-ecosystems

# Additional Information
 GITCOIN ADMINISTRATION
 info@ayoweccauganda.org

https://gitcoin.co/grants/4014/agroforestry-climate-change-forests-and-ecosystems

**Comment by ErinOCon** [comment]
Hi @JJonathanOlwenyi, thank you for your proposal. Unfortunately, we will not be able to proceed as the outlined work does not align with the criteria of our dev grants program. Wishing you all the best with this admirable work!
