### ISSUE TITLE
Open Grant Proposal: dBookMarket

### ISSUE THREAD

**Issue by dev-ddid** [filecoin-project/devgrants#717]
# Open Grant Proposal: `dBookMarket`

**Name of Project:**dBookMarket

**Proposal Category:** `app-dev`

**Proposer:** `dev-ddid`

**(Optional) Technical Sponsor:** ``

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:**  Yes

# Project Description

**DBook is a socialFi-enabled e-book marketplace. Users can publish/trade their own books, earn money by reading them, and interact with other readers/authors to review them.**

**We will solve the following problems:**

1. Increase the income of literary creators as much as possible
> i) without limitation of authorship exclusivity;
> ii) Copyright shall remain with the creator, such as the right to change film and television, cartoon and game;
> iii) The income from works does not need to be shared with the platform;
> iv) Royalties may be levied on secondary transactions;
> v) The more readers there are, the more advertising revenue there is.

2. Copyright protection and the establishment of an open platform to prevent piracy
> i) Encrypt and protect the author's work data through holomorphic encryption;
> ii) Manage the book works of the platform through the DAO model, and provide legal channels for the rights protection of controversial works.

3. Motivate readers to read
> i) Provide a wider variety of books for readers to read according to their preferences;
> ii) Provide socialFi-enabled comments to enhance readers' interactivity in reading;
> iii) Add read to earn to motivate readers to read/learn.

To solve the above problems, we tried to come up with a feasible market plan with the PRODUCT MVP after half a year of market research and preliminary exploration. In combination with our mature encryption scheme: shaftStop, Dr David's ShaftStop was licensed by the United Nations Industrial Development Organisation WiiTs last year. The scheme can encrypt full bit operation, string, pictures, audio, video and so on. And the encryption scheme has a number of patents.

## Value

**What are the benefits to getting this right?**
The main purpose of our project is to help authors around the world better publish/sell their books and protect their copyright. At present, there are 800 million readers and 50 million literary creators in China, and the market size is still growing. We have contacted nearly 1,000 literary creators, who are very optimistic about our project and looking forward to their works being sold abroad. I think we might have a deeper collaboration in the future, because these writers are producing 4,000 + content per day, and I think it makes sense to store Filecoin.

 **What are the risks if you don't get it right?** 
Currently, many authors and readers are unfamiliar with the concept of nft books. Authors are bounded by publishers or online and readers do not have the option of reselling their digital books. We believe that the future of digital books lies with nfts – the challenge currently is to increase awareness and encourage adoption. We are exploring subsidies and other incentives to encourage authors to publish with dbookmarket. 

**What are the risks that will make executing on this project difficult?**
Currently, we maintain a core project management and development team and we engage independent developers to complement our development work. As we are self-funded currently, we operate a lean marketing budget to build community and awareness. Moving forward, we are actively seeking sponsors and collaborators to promote the future of reading on dbookmarket. 

## Deliverables

A dBook publishing, trading, and reading Web and mobile application that includes coverage of socialFi, Read to Earn, and DAO.

## Development Roadmap

**Milestone 1:**
At this milestone, we will complete the design and development of the new website, which will be adapted to PC and mobile phones. The new version of the website will add several new parts:
Home page (redesign); Explore the market; Earn; WhitePaper. Become an author; Author support Program.
One of the "Explore the market" and "Become a writer" sections of the application to become a writer for rework, including smart contract changes, new crawlers.

Estimated time: 4 weeks
Budget: $20,000
Roles involved: Smart contract developers, web developers, Python developers, UI designers, product managers, game effects designers

**Milestone 2:**
Web APP UI reconstruction, and support mobile display, mobile app support publishing/trading.
New text encryption and decryption algorithms and services, new text publishing methods for Web apps and mobile apps (iOS and Android), new text editing functions for Web Apps and mobile apps, and text decoding methods for mobile apps.
Refactoring smart contracts for settlement to add a simple review mechanism.

Estimated time: 8 weeks +2 weeks of testing
Budget: $50,000
Roles involved: Doctor of Algorithms, Smart Contract developer, Web developer, Flutter developer, Python developer, UI designer, product Manager

**Milestone 3:**
Add "Read to earn" contract development, token economy, AD access and AD revenue sharing contracts, and add corresponding functions to mobile apps.

Estimated time: 8 weeks +2 weeks of testing
Budget: $50,000
Roles involved: Smart contract developer, Web developer, Flutter developer, Python developer, UI designer, product manager

**Milestone 4:**
A comment system with socialFi attributes has been added to the token economy, as well as the development of corresponding smart contracts, the development of mobile APP functions and the basic version of Web APP functions.

Estimated time: 8 weeks +2 weeks of testing
Budget: $50,000
Roles involved: Smart contract developer, Web developer, Flutter developer, Python developer, UI designer, product manager

**Milestone 5:**
The "Listen to Earn" mode and corresponding smart contract development are added to the new token economy, Minimal model of book governance through DAO

Estimated time: 8 weeks +2 weeks of testing
Budget: $50,000
Roles involved: Smart contract developer, Web developer, Flutter developer, Python developer, UI designer, product manager

## Total Budget Requested

$220,000

## Maintenance and Upgrade Plans

This is an open source project, and as we complete all the milestones, we will set new ones and continue to iterate as the market changes.

# Team

## Team Members

- Bill Joy(Co-founder &PM)
- EePing neo(Co-founder)
- [horry Bi(Co-founder &Flutter developer)](https://github.com/onlyYU)
- Dr David(Algorithms)
- [Future(Python developer)](https://github.com/R-Future)
- [Navid(Smart contract developer)](https://github.com/xuxinlai2002)
- [Linxi(Web developer)](https://github.com/linxi1020)
- Ge yuf(UI designer)

## Team Member LinkedIn Profiles

[Bill Joy](https://www.linkedin.cn/incareer/in/%E5%AD%90%E8%88%AA-%E5%91%A8-680a91a2)
[EePing neo](https://www.linkedin.com/in/eeping-neo/)
[horry Bi](https://www.linkedin.cn/incareer/in/horry-%E6%AF%95-0323a8227)

## Team Website

[https://dbookmarket.com/#/](https://dbookmarket.com/#/)

## Relevant Experience

**Bill Joy**
In the last 5 years, he has managed multiple blockchain projects, including 2 crypto wallets and He was the project manager for FiveToken and Qbao cryptowallets and was responsible for the design, development and launch of both projects.

**EePing neo**
Edtech founder, Independent Director, Blockchain Enthusiast, founder passionate about how technology can make learning fun and accessible for all.

**Horry Bi**
More than 7 years of mobile development experience, leading blockchain related development such as exchanges, wallets and communities.

**Our team just won the IPFS/Filecoin-Pool Prize at HackMoney**

## Team code repositories

- [readme](https://github.com/dBookMarket/DBook.docs)
- [Web Application](https://github.com/dBookMarket/DBook.Web)
- [Mobile Application](https://github.com/dBookMarket/DBook.Flutter)
- [Smart Contracts](https://github.com/dBookMarket/DBook.Solidity)
- [Server](https://github.com/dBookMarket/DBook.Django)

**Comment by ErinOCon** [comment]
Hi @dev-ddid, thank you for this proposal! We would like to support a portion of the outlined work. For next steps, please email grants@filecoin.org.
