### ISSUE TITLE
Next Step Microgrant:  Community Care

### ISSUE THREAD

**Issue by delightfulabyss** [filecoin-project/devgrants#719]
### 1. What is your project? (max 100 words)
Community Care is a mutual aid protocol that allows digital community members to request and provide monetary assistance from and to eachother. There are three phases for each round: request, funding, and settlement. Users can submit aid requests during the request phase and then can donate to either specific requests or to a common pool during the funding phase. Users who donate generate token rewards based on a donation-to-request ratio being above 1 (those who request more than they donate will not earn rewards). The token could eventually be used for governance decisions. Once the funding phase concludes, the common pool funds are then allocated based on how many donations a request receives. During the subsequent settlement phase, users are able to withdraw all funds earmarked for their request.

[Community Care Repo](https://github.com/delightfulabyss/community-care)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Each request can be submitted with a link to supporting documentation. Our eventual front-end will use nft.storage, which would allow files to be stored on both IPFS and Filecoin.

  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Our planned next steps are as follows:
1. Audit the smart contracts for bugs and optimize for gas consumption
2. Write and deploy a front-end website for interacting with the contracts
3. Perform user interviews with members of a DAO and synthesize feedback
 
### 4. Is this project open source?
Yes, this project is under the MIT license

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
N/A
  
### Additional questions:
Team members
- Matthew Watman, mattwatman@gmail.com, delightfulabyss, developer
- Tippi Fifestarr, tippi@boober.org, tippi-fifestarr, developer

Tippi and Matthew met through their work in CabinDAO and are in Orbit Proto.school study group.

How did you learn about our microgrant program?
Through Tippi's involvment with Filecoin

**Comment by tippi-fifestarr** [comment]
@jenks-guo-filecoin @DeveloperAlly @Jorropo @realChainLife 
I'm really looking forward to working on this one with @delightfulabyss, would love your feedback and support if possible!

**Comment by DeveloperAlly** [comment]
Awesome! Excited for you to go down the startup route and keep building and growing!

**Comment by ErinOCon** [comment]
Closing this Issue as the grant has been kicked off be email. Happy building!

**Comment by jenks-guo-filecoin** [comment]
Thanks for the meeting. Happy to be your technical sponsor @tippi-fifestarr @delightfulabyss.
