### ISSUE TITLE
Open Grant Proposal: Cratch

### ISSUE THREAD

**Issue by skidrow8852** [filecoin-project/devgrants#721]
# Open Grant Proposal: `Cratch`

**Name of Project:** `Cratch` 

**Proposal Category:** `app-dev`,`metaverse` 

**Proposer:** `skidrow8852`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Please respond with either "Yes" or "No"

Yes

# Project Description

Cratch is the first decentralized live & video streaming platform in the Metaverse.
It allows users to create or watch live streams in a Mobile App, Website Platform and Metaverse world, while rewarding them from every minute they spend on the platform.
We are building this platform to solve many problems in the video sharing and live streaming sectors such as censorship, data collection and targeted advertisement. All of the data and media files uploaded in our platform are stored in IPFS network.

Github repo : https://github.com/skidrow8852/Cratch_Platform_V1

website : https://cratch.io/

Demo video : https://www.youtube.com/watch?v=xywr1phy8ic

## Value

Having a large number of in game asset & video NFTs, a large amount of video storage, and having our website with hundreds of thousands of website visits will greatly increase the use of IPFS and the filecoin ecosystem as a whole, generating more revenue for the entire ecosystem.
Cratch aims to be a mix of Youtube & Twitch for Web3 with more features, improvements and a Metaverse world. There are many risks and there is over 80% chance that we or any project on web3 will achieve the level of success we are aiming for, but we plan to stay lean until we find our product fit with the market, iterate frequently and survive long enough. until we reach the inflection point. The benefits of obtaining this right will be huge for the filecoin ecosystem and the web3 ecosystem as a whole.
 
## Deliverables

All of us use Youtube or Twitch from time to time, and all we can agree that the amount of ads in these platforms are a lot, without mentioning the data these platforms collect everyday from its users to benefit only one side. On some platforms, creators can arbitrarily be removed or restricted based on the beliefs they have.
We’re here to change that, and bring more value back to the people who are creating it. With Cratch we want to make sure both content creators and viewers benefit from our decentralized platform where no one entity can take away someone’s right to earn an income or their place to voice their opinions even if they differ, and therefore we are building a virtuous ecosystem that includes :
- An online video sharing, live streaming and social media platform built entirely on IPFS
- Metaverse world for content creation & live interaction with the community
- Mobile app to watch content on the run

## Development Roadmap

| Task   |      Description      |  Cost |
|----------|:-------------:|------:|
| NFT Subscriptions |  Access any user videos & live streams by owning at least 1 NFT from his/her NFT collections | $3500 |
| Custom RTMP server with IPFS storage |    Allow creators to input the stream key into a streaming source of their choice (OBS, etc.), have streams available after stream finishes, stored on IPFS  |   $5000 |
| Metaverse | Create MetaCratch with good graphics quality by using Unreal Engine and integrate Filecoin IPFS for in game NFT assests |    $16000 |
| Mobile app | Create MobiCratch with IPFS integration and list it in both Play Store & App Store |    $10000 |

## Total Budget Requested

| Task   |      Description      |  
|----------|:-------------:|
| NFT Subscriptions  | $3500 |
| Custom RTMP server with IPFS storage  | $5000 |
| Metaverse  | $16000 |
| Mobile app  | $10000 |
| Total  | $34,500 |

## Maintenance and Upgrade Plans

With this grant, we'll have enough runway to fund the project for the next 6 months. I still work full time and am putting my own funds into the project.

EOY Goals - 2000 creators on the platform, 25,000 monthly streamed hours, 500,000 monthly watched hours.

# Team

## Team Members

Youssef Rais
Victor Pyagai
Julia Mendeleve
Joseph Elkherchi

## Team Member LinkedIn Profiles

* Youssef Rais : https://www.linkedin.com/in/youssef-rais-4b8608110/
* Victor Pyagai : https://www.linkedin.com/in/victor-pyagai-504169213/
* Julia Mendeleve : https://www.linkedin.com/in/julie-mendeleve-a12a8a237/
* Joseph Elkherchi : https://www.linkedin.com/in/joseph-elkherchi/

## Team Website

https://cratch.io/team

## Relevant Experience

We are a small team of crypto enthusiasts gathered together to build better products in Web3 , and we've been working hard, with the firm belief that our project will facilitate and improve content creation live,video streaming. Here is our work experience : 
- Youssef Rais : Ex Accenture Software Engineer with 3 years of experience, worked on different technologies such as blockchain and finance.
- Victor Pyagai : Game Developer with over 2 years of experience, developed many cross platform games with Three.js, Unity game engine and Unreal Engine.
- Julia Mendeleve : Experienced UX/UI Designer worked in the creative industry for over 5 years.
- Joseph Elkherchi : Social Media Manager and Marketer with more than 7 years of experience business, technology and digital marketing strategies.

## Team code repositories

https://github.com/skidrow8852/Cratch_Platform_V1

# Additional Information
- How did you learn about the Open Grants Program?
Through emails from Protocol Labs
- Please provide the best email address for discussing the grant agreement and general next steps.
amine20solo20@gmail.com
- Please include any additional information that you think would be useful in helping us to evaluate your proposal.
We were finalists and won the IPFS/Filecoin "Top 3" prize for Best Use of IPFS or NFT.Storage for Content-Addressed Data at the Moralis Avalanche 2022 hackathon!

**Comment by ErinOCon** [comment]
Hi @skidrow8852, this grant has been approved! We will send an email to discuss next steps.

**Comment by skidrow8852** [comment]
Thank You @ErinOCon for accepting our application,

**Comment by lksbrssr** [comment]
Hi @skidrow8852  - we noticed you also submitted this same project to one of our hackathons. Can you shed some light on your rationale here? Cheers

**Comment by skidrow8852** [comment]
Hi @lksbrssr, thanks for your message, to be honest i didn't know that i cannot participate with the project on a hackathon, but if so i would like to appologize for this mistake, and this will not happen again in the future.
Thank you for your understanding.
