### ISSUE TITLE
Lands Enchanted NFT Launch pad and gamefi<Your Title Here>

### ISSUE THREAD

**Issue by faithful1ofall** [filecoin-project/devgrants#723]
### 1. What is your project? (max 100 words)

Lands Enchanted Introduction
Lands Enchanted is the first decentralized Enchanted assets platform that unites Intellectual Property and rated Assets. Bridging NFTs and rated assets, Lands Enchanted are able to reshape the rated market in the form of Enchanted NFT, thereby laying the foundational value for the E-NFT. Through the Minting Contract, Purchase Contract, and Mining Contract, Lands Enchanted are able to provide a useful toolbox for rated providers and Intellectual Property providers alike.
The liquidity of E-NFT are guaranteed by the decentralized infrastructures such as the SWAP, POOL, CREDIT, and AUCTION. Every Lands Enchanted NFT will exist permanently on the chain, with infinite expandability. All E-NFT data can be accessed by any third party, allowing community developers to build their own contracts above them, and it's a project that cut across launching of NFTs project looking at some creators find it difficult going to the market

 https://github.com/faithful1ofall/Lands-Enchanted-App or
THE NFT launch pc compatibility only
https://launch.landsenchanted.com/

LandsEnchanted.com

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
we will use the ipfs system for nft launchpad data(images, special traits etc.) uploading we also  add the filecoin network as an expandable point as we progress towards the multichain.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
we intend to build the first Mini game for a test within 2 to 3 Months and also build our launchpad for pre-sale and whitelist.
we will expand our test phase to a complete startup with more game developers, marketing experts and proceed to futher integrations in less than 2 to 3 months.
 
### 4. Is this project open source?

yes reports will be given upon request with completion of the development promptly reported.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Sure

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 No 

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?

From google

* If your project was created as part of an event or hackathon:
No

  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by faithful1ofall** [comment]
The content has been updated thanks

**Comment by ErinOCon** [comment]
Hi @faithful1ofall, thank you for the updates! Can you provide a working Github link?

**Comment by faithful1ofall** [comment]
https://github.com/faithful1ofall/Lands-Enchanted-App

What is the case this is the link for the launch with this link the rest are still in the game engine

**Comment by ErinOCon** [comment]
Hi @faithful1ofall, thank you for your reply. Unfortunately, this link is not working. Can you submit the correct or updated link?

**Comment by faithful1ofall** [comment]
I'm really sorry about that I have made the GitHub link public you can now access is thanks.

https://github.com/faithful1ofall/Lands-Enchanted-App

**Comment by ErinOCon** [comment]
Thanks, @faithful1ofall! It looks like you agreed to reporting under our question regarding open source work. Is it correct that the work will be open source?

Finally, can you confirm how you will be using IPFS? Are you using a service like web3.storage or NFT.storage?

**Comment by faithful1ofall** [comment]
Yes of course The work will be open sourced.

And we will be using the IPFS by using the service NFT.storage because we will need our NFTs and NFT data decentralized and ready for usage across the platform  so we will store all our NFTs and data of the NFT thanks.

**Comment by ErinOCon** [comment]
Hi @faithful1ofall, thank you again for your proposal! We would like to review the progress and success of the micorgrant project that is currently active before proceeding with a new grant. Once the final report for [Mini Utopia](https://github.com/filecoin-project/devgrants/issues/621) is complete and submitted to our team, please feel welcome to resubmit this proposal.

**Comment by faithful1ofall** [comment]
I would love if we could reopen this project
