### ISSUE TITLE
Next Step Microgrant: DecentralizedCV

### ISSUE THREAD

**Issue by decentralizedcv** [filecoin-project/devgrants#724]
### 1. What is your project? (max 100 words)
We will build web3's decentralized personal CV platform, everyone can create his own personal CV on our platform，We will use wallets as keys for everyone .so everyone can have their own personal cv and can optionally send this cv to other encryption employers or for other encryption personnel to view.At the same time, everyone can also get like-minded friends through personal cv to participate in the hackathon together.

All cv data will be stored to the IPFS/Filecoin platform through web3.storage, maintaining decentralization is the purpose pursued by our platform

https://github.com/decentralizedcv/cv

https://cv-psi-ten.vercel.app/home

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
  There are various data types in personal cv, such as pictures, videos or texts, etc. We can use IPFS/Filecoin to save these data, provide a permanent and reliable storage solution for these data, and provide users with data at the bottom layer. Provide a reliable decentralized solution. Everyone can control their own cv through the key, without worrying about having to re-create the cv because of the closure of the web2 platform

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
 We will use grant to recruit a very experienced IPFS/Filecoin developer to maintain the operation of our platform, and if there is more funds, we will invite KOLs to promote our platform through some grants
### 4. Is this project open source?
YES

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
YES
  
### 6. Does your proposal comply with our Community Code of Conduct?
YES

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
   Judis, Project Initiator, Product Manager ， decentralizedcv@outlook.com

* How did you learn about our microgrant program?
  from discord .

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
https://devpost.com/software/decentralizedcv

**Comment by decentralizedcv** [comment]
@ErinOCon we already joined [Web3 Infinity Hackathon](https://web3infinityhackathon.devpost.com/) .

**Comment by ErinOCon** [comment]
Hi @decentralizedcv, thank you for your proposal! We find it's best for builders to complete their hackathon prior to starting grant related work. Please feel welcome to submit your project for review once your hackathon is complete!

**Comment by decentralizedcv** [comment]
> Hi @decentralizedcv, thank you for your proposal! We find it's best for builders to complete their hackathon prior to starting grant related work. Please feel welcome to submit your project for review once your hackathon is complete!

Hi @ErinOCon.Grateful! I will resubmit the relevant application when I complete the hackathon . I hope that through this competition, we can get new inspiration to improve the project

**Comment by ErinOCon** [comment]
Happy building, @decentralizedcv!
