### ISSUE TITLE
Next Step Microgrant: FILDrop

### ISSUE THREAD

**Issue by buggsaff** [filecoin-project/devgrants#725]
### 1. What is your project? (max 100 words)
Backup your images to IPFS storage and convert them into NFTs.
Github repo
https://github.com/meta-ps/FilDrop
Demo
https://www.loom.com/share/73a52236240d42e597986fab12b0b5e1

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
IPFS is used as a reliable alternative platform for image storage replacing native cloud storage apps like Google Drive, OneDrive.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
As of now, our application is a simple two page dashboard, which allows user to upload images and mint them as NFTs on Polygon. We want to improve the user interactivity and include several features such as backup of videos, multi-chain support (like Solana),sharable links for a specific collection.
 
### 4. Is this project open source?
Yes, all of the work is Open Source under MIT license.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://devfolio.co/projects/fildrop-beb9
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

  Prerna Dhiman
  Email - [prernadhiman@duck.com](mailto:prernadhiman@duck.com)
  Github - buggsaff
  Role - Frontend Developer

  Shashank
  Email - [17211a05a5@bvrit.ac.in](mailto:17211a05a5@bvrit.ac.in)
  Github - shashanka2a
  Role - Full Stack Developer
  
  Pradeep Varma
  Email - [pradeepnadimpalli22@gmail.com](mailto:pradeepnadimpalli22@gmail.com)
  Github - pradeepvarma22
  Role - Smart Contract Developer

* How did you learn about our microgrant program?
  Friend.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
    [Built at BITS Web3 Week Hackathon](https://bits-web3-week-hackathon.devfolio.co/)
  * Please link to your hackathon submission
     https://devfolio.co/projects/fildrop-beb9

**Comment by ErinOCon** [comment]
Hi @buggsaff, this grant has been approved! We will reach out by email to confirm payment details.
