### ISSUE TITLE
Next Step Microgrant: Sling Protocol

### ISSUE THREAD

**Issue by Joseph-Gross** [filecoin-project/devgrants#726]
### 1. What is your project? (max 100 words)

We are building a decentralized and user-friendly automation network. We envision a protocol layer that users, developers, and enterprises can use to automate any on-chain action(s) and compose these automations into complex transactional state machines. This is infrastructure for making highly composable and flexible new primitives.

Some examples:
- Algorithmic Trading
- Creating a virtual orderbook on any structured product
- NFT/ENS Sniping
- Automated Liquidity Bridging
- Governance/DAO Management

The future of Sling is an established multichain hyperstructure facilitating trustless conditional transaction execution for its users. As more and more use cases move some component on-chain, we enable users to take full control over their cryptographic assets.

Links:
- GitHub: All repos currently private
- Landing Page: https://slingprotocol.xyz

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

We use OrbitDB heavily for as the storage provider for a our decentralized network of orderbooks. Essentially, OrbitDB stores a registry mapping our proxy contracts to their relevant OrbitDB databases. Then, our network of executor bots can scan this registry, construct a full orderbook made of all inidividual orderbooks, and process transactions with valid pre-conditions. Similarly, each proxy has complete ownership and we take advantage of OrbitDB's flexible access controllers to ensure the data integrity of every orderbook.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

This grant will allow us to fund ourselves through the summer. Next steps for getting the product ready for production:

Milestone 1: Distributed Orderbook (secure, trust-less, encrypted)
- Description: The core infrastructure for our network. This is essentially the protocol layer and is heavily integrated with OrbitDB/Filecoin, Lit Protocol, EPNS.

Milestone 2: Orderbook Explorer
- Description: A very basic UI for monitoring your orderbook in real time. This  includes viewing your order history and status, and can also be applied to monitor an executor's progress in processing transaction in real time

Milestone 3: Executor Network
- Description: A network of at least executor nodes working to process transactions for the network based on valid pre-conditions. These will initially be run by the team, but we plan on developing an executor marketplace where developers can license their executors for a share of profits. We also plan on releasing developer tools for writing your own executor that follows our framework.

Milestone 4: Core SDK
- Description: Common module, storage module, and order module. While this will
  initially be closed source and used for internal development, we intend to use this sdk to build higher level abstractions and wrappers for different use cases using the sdk. Eventually, we plan on fully open sourcing our sdk.

Milestone 5: Audited Smart Contract Layer
- Description: All of our smart contracts audited and deployed on at multiple EVM compatible chains

Milestone 6: Developer SDK v1
- Description: The first version of the sdk we will released for developers to build dApps using Sling Protocol

Milestone 7: Proxy Account Portfolio Page
- Description: Basic UI for connecting your wallet and interacting with all of your authorized Sling Proxy accounts (i.e. depositing, withdrawing, deploying, etc.)

Milestone 8: Sling dApp Component Library
- Description: A basic component library for building Sling dApps. We envision a similar toolset to the one provided by Gnosis Safe

Milestone 9: UI / UX Design System
- Description: Create a comprehensive design system in line with our mission and brand.

### 4. Is this project open source?

Not currently, but we intend to do so gradually over time. We intend to build a full decentralized automation network with an entire ecosystem of developers building on top of it, so while we do intend to open source all of our work at some point, we are planning on doing so gradually. The Lit Protocol component of our network, however, is one of the first components we intend to open source with the MIT license.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

This project did not begin at a hackathon, and as a result does not have a public repo or MVP yet.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

I learned about the microgrant program through a Hackathon we participated in (EthGlobal in New York City) and was encouraged to take a closer look at it and apply.

Team Members
- Joseph Gross: [josephgross157@gmail.com](mailto:josephgross157@gmail.com)
  - [GitHub](https://github.com/Joseph-Gross)
  - [Linkedin](https://www.linkedin.com/in/josgross/)
  - Role: Co-Founder / CTO (ideation, system architecture design, SDK design and implementation, UI/UX, executor network design)

- Richter Brzeski: [GitHub](https://github.com/richtermb)
  - [Linkedin](https://www.linkedin.com/in/r-brzeski/)
  - Role: Co-Founder / CEO (ideation, smart contract design and implementation, SDK development)

- Nick Ciepley: [GitHub](https://github.com/njciepley)
  - [Linkedin](https://www.linkedin.com/in/nicholas-ciepley/)
  - Role: Developer (UI / UX development, Executor network development)

- Will Seiple: [GitHub](https://github.com/willseiple)
  - [Linkedin](https://www.linkedin.com/in/wseiple/)
  - Role: Developer (product ideation, UX, smart contract development, Executor network deveopment)

**Comment by Joseph-Gross** [comment]
We do expect that our work will be open source and on our team Github in the near future (ideally by the end of the year). Our plan to open source will be in phases - First we'll open source our contacts and our storage module, next we will be open sourcing relevant tooling around creating / querying / updating / managing orders, and finally we be open sourcing the base executor bot which secures our network and executes transactions. These funds will be applied primary to our storage module as it is a significant part of our system. We'll be using Ceramic Network or Orbit Db for this (both of which publish to IPFS)

**Comment by ErinOCon** [comment]
Thanks, @Joseph-Gross! We will not be moving forward with a grant at this time as our Microgrant program is intended to support projects with a working prototype that are actively open source. 

We would be happy to consider your project in the future once there has been more progress. Wishing you and your team all the best as you continue building!
