### ISSUE TITLE
Open Grant Proposal : SectorScan

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/devgrants#728]
**Name of Project:**  SectorScan

**Proposal Category:**  App-dev

**Proposer:**  FroghubMan

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:**  Yes
# Project Description
 We are developing a FileCoin sectors browser to provide storage providers (SP) with services such as sector detail query and sector management.

1.  Display of sector information (including basic sector information and order information)
2.  Renew sectors
3.  Upgrade marked-sectors
4.  Terminate sectors
5.  Recovery sectors

## Value

At present, there is no browser tool focusing on sectors in the community. Lotus needs professional and careful operation and maintenance ability for sector management. This tool provides an easy-to-use sector management tool for cluster maintainers. Managers can quickly view the sector information and the order information of the sector and react.

In the current community, many mainstream filecoin browsers are managing the computing power, balance, pledge, and burst of storage providers (SP). Filecoin aims to build a data storage and retrieval method based on blockchain system, and sector is the basic unit of data storage. The management of sectors is also particularly important.

## Deliverables

Deliverable is a tool for SP to provide sector management, which makes it more convenient for SP to manage sectors

## Development Roadmap

**Milestone 1** (10,000$)
  Sort out the data prototype and design the browser prototype and UI.

**Milestone 2** (20,000$)
 Support the data end of the browser and build a complete full chain node
 We will provide sector query function for storage providers (SP).
	Function of obtaining sector details.
	Function of estimating sector termination cost.

**Milestone 3** (30,000$)

1. Set up the Daemon Gateway to provide Gateway Services for users to submit messages.
2. Provide scanning offline signature messages. The browser submits messages for users. And it is compatible with fivetoken.
3. Function of sector renewal.
4. Function of sector termination.
5. The function of generating and exporting sector metadata is used for sector repair. Refer to: https://github.com/froghub-io/filecoin-sealer-recover

  

## Total Budget Requested

 60,000$ We will use it all to fund the development of applications.

## Maintenance and Upgrade Plans

 We will upgrade regularly. If the version of lotus changes, we will also upgrade and update together.

# Team

## Team Members

 Wenxin Chen  wenxin@froghub.io

 ShunQuan Yu yusq@froghub.io

## Team Website

  https://www.froghub.io/
  https://github.com/froghub-io

## Relevant Experience

1. We implement a cloud C2 based on filecoin lotus optimization. We only changed a small part of the code to realize the remote execution of C2.(https://github.com/froghub-io/lotus-cloudc2)
2. CC sector recovery.(https://github.com/froghub-io/filecoin-sealer-recover) 
3. Have multiple evm smart contract project development experience
4. Master subgraph for data analysis on the chain
5. Master IPFS technology to store data for offline NFT
6. Master the development framework of intelligent contracts such as truss and hardhat
7. More than 1 year of experience in building and publishing production level smart contracts

## Team code repositories
 https://github.com/froghub-io

**Comment by ErinOCon** [comment]
Hi @FroghubMan, thank you for your proposal! Can you provide a technical breakdown on how you will build out each listed milestone? For milestone 2, please expand on how you will build a complete full chain node.

**Comment by FroghubMan** [comment]
What we want to achieve is a sector-themed browser and provide one-stop sector services for SP.
Based on this goal, we have reorganized and improved the roadmap:

Milestone 1

2-3 Month: USD35000

0. User interface design and Build a complete full-chain node as a data source
1. As an SP, I can view the sectors in the corresponding deadline according to the status (eg.live, faulty)
2. As an SP, I can view the sectors that are about to expire in the corresponding deadline
3. As an SP, I can view the precommit sector in the corresponding deadline
4. As an SP, I can view the on-chain information of the corresponding sector, including the orders in it
5. AS an SP, I can view the estimated termination cost of the corresponding sector
6. AS an SP, I can view sector status change line chart
7. Sector expiration time statistics
8. Sector growth Statistics
9. Sector type/version statistics
10. Statistics on the average number of orders in the sector

Build a full-chain node: We will open the temporary dedicated international bandwidth to pull the complete snapshot of the whole chain for recalculation, 
and will purchase high-capacity disks to run the whole chain nodes.

Milestone 2

2-3 Month: USD25000

1. Integrate filecoin wallet extension
2. As an SP, I can terminate unrecoverable sectors in bulk
3. As an SP, I can renew sectors in bulk
4. As an SP, I can batch export the relevant on-chain information of recoverable sectors for recovery
5. Provide relevant tools to help SP recover recoverable sectors (Refer to: https://github.com/froghub-io/filecoin-sealer-recover)

**Comment by ErinOCon** [comment]
Thank you, @FroghubMan!

**Comment by ErinOCon** [comment]
Hi @FroghubMan, thank you for your patience. This grant has been approved! We will be in touch by email to discuss next steps.
