### ISSUE TITLE
Next Step Microgrant: Meta4Swap

### ISSUE THREAD

**Issue by Tgb29** [filecoin-project/devgrants#730]
### 1. What is your project? (max 100 words)
Meta4Swap is a marketplace where sellers list their products/services and where buyers create orders in a single transaction. All payments are held in escrow until the seller and buyer both confirm the transaction is finished. All disputes are settled by the Meta4Swap DAO.

https://github.com/Tgb29/meta4swap-contracts
meta4swap.com

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
All listing information, including the product/service data model and product/service image, is uploaded through the front end and stored in IPFS, and the hash for the location of this data is stored on chain. The front end app renders pages using the data saved in IPFS, and basically, IPFS is our database -- we don't save product info in any other DB. All arguments for disputes are also saved in IPFS.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Our goal is to identify our customers and customize the experience for them. In the hackathon, we took a generalist approach, but now we want to focus on digital services for freelancers. The mechanics of our app will basically stay the same, but the UI/UX will changes, and we'll recruit specific buyers and sellers. Our side business is a web3 dev agency, so we'll list our services and request our future clients to pay through our app.
 
### 4. Is this project open source?
This project is open source and we're more than happy to share our research and ideas with other developers.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, we'll provide grant reports as requested and a final grant report when the 3 month period is over. We'll provide any other information that is requested from us.
  
### 6. Does your proposal comply with our Community Code of Conduct?
We've gone through the Community Code of Conduct and can confirm that our proposal doesn't break any of the rules.

### 7. Links and submissions
Our project began at the Chainlink 2022 Spring Hackathon. We won the Defi magician prize.

Our project has 2 team members, Theodore Brinkofski and Theodore James. TB was the smart contract developer and system architect, and TJ was the front end engineer. Together we worked on the front end and back end integrations.

https://github.com/Tgb29/
https://github.com/theojames222
  
We learned about the microgrant program from Ally Haire, who reviewed our hackathon project and suggested we apply for a grant.

Here is our hackathon submission on Devpost: https://devpost.com/software/theo-daos

**Comment by ErinOCon** [comment]
Hi @Tgb29, this grant has been approved! Can you confirm the preferred email address to discuss payment details?

**Comment by Tgb29** [comment]
hey @ErinOCon , thanks for the great news! You can email me at tgb29@cornell.edu

**Comment by ErinOCon** [comment]
Thank you!
