### ISSUE TITLE
Next Step Microgrant: Cryptotracker

### ISSUE THREAD

**Issue by banafederico** [filecoin-project/devgrants#731]
### 1. What is your project? (max 100 words)

We are [Cryptotracker](https://legalcryptotracker.io), and we're looking to create a platform where legal experts from all over the world collaborate to keep track of the state of regulation in each country. We have recently launched our MVP and many recognized legal experts have already submitted content about regulation in their countries, mostly in LATAM. Our core team is located in Uruguay.

https://github.com/legalcryptotracker
https://legalcryptotracker.io

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

We'll timestamp state of regulation data submitted by users of the platform and use IPFS to store it and create indices to simplify navigation.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We'll completely refactor the storage module for our platform in order to switch from the SQL database that we're using now to IPFS. 
 
### 4. Is this project open source?

Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
 
### 6. Does your proposal comply with our Community Code of Conduct?

Yes
 
### Additional questions:

* For each team member(s), please list name, email, Github account, and role in the project.

Agustina Perez Comenale
Role: Legal advisor - Founder
Email: agustina@legalcryptotracker.io

Mercedes Aramendía
Role: Legal advisor - Founder
Email: mercedes@legalcryptotracker.io

Federico Baña
Role: Software engineer
Github: banafederico
Email: federico@legalcryptotracker.io

**Comment by ErinOCon** [comment]
Hi @banafederico, thank you for your Github submission. Do you have a public Github link we can review?

**Comment by banafederico** [comment]
> Hi @banafederico, thank you for your Github submission. Do you have a public Github link we can review?

We made the source code available here: https://github.com/legalcryptotracker/legalcryptotracker.io. Thanks for reviewing our submission! :+1:

**Comment by ErinOCon** [comment]
Hi @banafederico, can you provide a brief technical design/outline for the refactor of your storage model? Also, can you confirm how you are using IPFS? For instance, are you using a service like web3.storage?

**Comment by banafederico** [comment]
> Hi @banafederico, can you provide a brief technical design/outline for the refactor of your storage model? Also, can you confirm how you are using IPFS? For instance, are you using a service like web3.storage?

We're currently not using IPFS. We're using Strapi and a PostgreSQL database for storage right now. Each version of every article is an independent piece of information and that's what we intend to store in IPFS. We would use web3.storage.

**Comment by ErinOCon** [comment]
Hi @banafederico, this grant has been approved! We will be in touch by email to confirm payment details.

The final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please reach out with any questions!
