### ISSUE TITLE
Mini Utopia 

### ISSUE THREAD

**Issue by faithful1ofall** [filecoin-project/devgrants#732]
# Open Grant Proposal: `Mini Utopia`

Name of Project:  Mini Utopia

Proposal Category: Choose one of `app-dev`, `integration-adoption`, `community` , `metaverse` 

Proposer: faithful1ofall (Mini Utopia)

Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?: Yes

# Project Description

We looked as the NFTs market grew and we knew that so many good creators are being declined because they don't have a good community we intend to build a strong community for NFT Creators one that's free from trust issues by implementation of the insurance staking CONSENSUS which needs to be implemented.

So Mini Utopia help users bother newbies to access the NFT market with less risk because we will build an insurance mechanism to make sure NFTs has a consistent value at every point in time so as not losing its own buy back value we intend to build a marketplace where NFTs will not have decreasing value instead will have increasing value as adoption increases.

## Value

 What are the benefits to getting this right?

We can bring users to adopt the Filecoin/IPFS ecosystem. We plan to upload/download hundreds of files (NFTs, Audios, data) in a daily basis and facilitate the discovery and access to them to the community. Because the nature of these files, they are not going to be very big in size, but because the information they contain (especially some gaming data) it can be very valuable. Using Filecoin/IPFS as storage of these valuables can help to identify Filecoin/IPFS as a reference solution as backend of relevant data.
 What are the risks if you don't get it right? 
If the solution is not executed right the main risk is we don't attract enough adoption from users and creators.

 What are the risks that will make executing on this project difficult?

Time to market, there is good interest on NFTs data now. The main difficulty here is if we don't execute quickly and we don't get enough user attention.

## Deliverables

NFT Ecosystem Frontend application
A frontend application implementing the NFT Ecosystem Marketplace. This application will have the following sections:

Home page. Welcome page with some initial information about the Marketplace. The Home page will be divided into different sub-sections:
Trending NFTs - With a list of the Top 3 or 5 or X NFTs selected as “trending”. This list of reports could be fetched from a database or static file in control by the Mini Utopia  team
NFTs Collection - A sub-list of the NFT collection (list of collection here)
Recently Minted- A list of the latest NFTs minted in the marketplace.
Search results page. When the user uses the search box or clicks in the category page or similar, a page with the list of results will be displayed. The search results page should allow users to filter and refine the search results by different options:

Collection (list of collection here)
Price (free and range of prices)
Details Page. When a user clicks to see a specific NFT anywhere in the application, this page will be open. In this page we want to show to the user all the information related to a specific asset/NFT. The complete list of metadata associated with an asset/NFT can be found [here].
User Asset Page. In this page, the user should be able to see a list of all the NFTs purchased in the marketplace and download them.
Information and Help. Static section where we will show basic information about the Marketplace, what information can be found, payment, etc.
Back-office
The back-office application in charge of:

Downloading and generating the multiple NFT assets. It will be based in the  Open Source framework 
Uploading the different datasets to Filecoin/IPFS
Register the datasets into the Mini Utopia Ecosystem Marketplace
## Development Roadmap

Milestone 1. Research/Architecture
The main objective is to define the architecture and identify the low level integrations between Mini Utopia, Filecoin/IPFS and the Blockchain. Tasks:

Definition of the Mini Utopias integration pattern with Filecoin/IPFS and the Blockchain
Definition of sequence flows and messages between protocols
Documentation of the changes required
Blog post & communication about the Filecoin grant and integration with the Mini Utopia Ecosystem 
Duration: 3 weeks

Milestone 2. NFT Marketplace product definition
The main objective is to define the complete use case functionality from a user point of view. Tasks:

Define and detail the features supported by the marketplace
Lower level definition of the sitemap and flows
Definition of the user stories
Definition of the Collections
Duration: 3 weeks

Milestone 3. Marketplace design
The main objective is to create a design implementing the main functionalities described in the previous milestones. Tasks:

Create the wireframes (Figma) with all the user flows, modals and messages
Integration of the wireframes in a HTML/CSS frontend application
Review of the user flows and core functionality
Duration: 2 weeks

Milestone 4. Back-office implementation
The objective is to create a group of backend agents able to fetch NFT data from different protocols. Tasks:

Implement the boilerplate agent to be reused across all the different NFT generators
Implement the core agents for the main NFT protocols identified
Fetching the data
Uploading the data to Filecoin/,IPFS
Registering the assets into the Marketplace
Unit and integration testing
Duration: 3 weeks

Milestone 5. Marketplace integration
The main objective is to integrate the frontend with the backend providing a totally functional marketplace. Tasks:

Integrate the different sections with the backend (home, search, details page)
Integration of download flow allowing users to get access to data stored into Filecoin
End to end testing
Duration: 3 weeks

Milestone 6. Deployment and Communications
The objective is to deploy the Marketplace in a production environment and communicate to the users the benefits of the solution built using Mini Utopia and Filecoin. Tasks:

Deploy the off-chain components into IPFS cloud infrastructure
Deploy the Smart Contracts in a EVM based network
Validate the integration with Filecoin in a production environment
Create a blog post explaining the benefits of the solution
Share with our community via Telegram, Twitter and Discord
Duration: 3 weeks

## Total Budget Requested

For us the project described fits into the Application Development category with the main objective of bringing usage to Mini Utopia and Filecoin networks. Taking into account the milestones and duration, we consider a budget of 100.000 USD (or the equivalent in FIL token) would be realistic for the total completion of the project. That budget will be used into:

Product design (UX, wireframes)
Development (including architecture, coding, etc.)
Infrastructure cost for the execution and operations of the off-chain components in the IPFS cloud infrastructure
Marketing & communications

Milestone	Duration	Cost
#1. Architecture	3 week		7.5k
#2. Product Definition	3 week		7.5k
#3. Marketplace design	2 weeks		20k
#4. Back-office	3 weeks		30k
#5. Integration	3 weeks		30k
#6. Deployment & Comms	3 weeks	5k
Total	17 weeks		100k

## Maintenance and Upgrade Plans

All the implementations resulted from this development will be Open Source and merged as part of the Nevermined upstream code. As a result of that, the code and functionality will be supported as long the Nevermined components are being used by the community.

# Team

## Team Members

Faithfulness Obasi GitHub.com/faithful1ofall

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/faithfulness-obasi-34566a130

## Team Website

https://miniutopia.co

## Relevant Experience

Beyond our experience  building Mini Utopia, our team has several years of background in data, Design, blockchain and Game development. We have worked in several organizations and projects related to these topics. 

## Team code repositories

GitHub.com/faithful1ofall

# Additional Information

From hackathon @ethglobal called Hackmoney

faithful@miniutopia.co or faithful1ofall@gmail.com

**Comment by ErinOCon** [comment]
Hi @faithful1ofall, thank you for your proposal. The sustainability of the outlined work currently isn't the best fit for our grants program, but we look forward to learning of your microgrant progress!
