### ISSUE TITLE
Next Step Microgrant: FunnyPic

### ISSUE THREAD

**Issue by superpenghu** [filecoin-project/devgrants#733]
### 1. What is your project? (max 100 words)
Funny Encyclopedia is  a original embarrassing joke sharing community. The funny jokes and funny pictures shared by hundreds of embarrassing netizens are the most precious happy experiences of embarrassing friends. 
We are a funny content community built on web3, users will log in to our platform through web3 wallet and link to each user through address, Everyone can upload funny videos and pictures to our platform. Users can increase the evaluation criteria of the content through factors such as likes or dislikes, and in turn increase the quality of the platform content.
 
Users can also praise their favorite content to encourage authors to create.
The crypto community needs a platform for relaxation.

https://github.com/superpenghu/FunnyPic

https://f-alpha.vercel.app/
### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
We use web3.storage to store the decentralized data of each user, all of which are free, and all the pictures, videos, etc. of the platform will be stored through web3.storage

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. Website refactoring, adding video, voice and other modules
2. Added contract function, users can choose to publish data to the platform after uploading the data through the contract
3. Add interactive functions such as videos, pictures, etc. (user likes, comments, etc.)

### 4. Is this project open source?
yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
   penghu , superpenghu@outlook.com

* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by superpenghu** [comment]
> ### 1. What is your project? (max 100 words)
> Funny Encyclopedia is a original embarrassing joke sharing community. The funny jokes and funny pictures shared by hundreds of embarrassing netizens are the most precious happy experiences of embarrassing friends. We are a funny content community built on web3, users will log in to our platform through web3 wallet and link to each user through address,
> 
> https://github.com/superpenghu/FunnyPic
> 
> ### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
> We use web3.storage to store the decentralized data of each user, all of which are free, and all the pictures, videos, etc. of the platform will be stored through web3.storage
> 
> ### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
> 1. Website refactoring, adding video, voice and other modules
> 2. Added contract function, users can choose to publish data to the platform after uploading the data through the contract
> 3. Add interactive functions such as videos, pictures, etc. (user likes, comments, etc.)
> 
> ### 4. Is this project open source?
> yes
> 
> ### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
> yes
> 
> ### 6. Does your proposal comply with our Community Code of Conduct?
> yes
> 
> ### 7. Links and submissions
> * If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
> 
> ### Additional questions:
> * For each team member(s), please list name, email, Github account, and role in the project.
>   penghu , [superpenghu@outlook.com](mailto:superpenghu@outlook.com)
> * How did you learn about our microgrant program?
> * If your project was created as part of an event or hackathon:
>   
>   * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
>   * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @superpenghu, this grant has been approved! We will send an email to confirm payment details.
