### ISSUE TITLE
Next Step Microgrant: Restoring sectors with orders

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/devgrants#735]
### 1. What is your project? 
 In the process of packaging or mining on filecoin network, you may face the risk of sector data loss. Then it is necessary to destroy the fil pre pledged by precommit, or terminate the sector (but this may cause the maximum loss of 90 days' earnings of the sector). Sector repair technology can repair lost files to reduce or avoid losses.

 At present, we have completed the function of repairing CC sector, and many storage providers (SP) in the community have used this function.（https://github.com/froghub-io/filecoin-sealer-recover）
 
 With the development of application ecology, accidental data loss on sectors with orders will also be a problem that most storage providers (SP) will encounter. We will research and develop sector repair with orders.

### 2. How will IPFS, Filecoin, or related technology be used for this project? 
 The retrieval function of filecoin and the API of lotus will be used to obtain sector information.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? 
 At present, we have completed the sector repair function of CC sector. We will use this grant to develop the recovery function of sectors which have orders. Therefore, we will also package some sectors with orders as tests.
 
### 4. Is this project open source?
 Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

 Agree

### 6. Does your proposal comply with our Community Code of Conduct?
 Yes

Additional questions:
For each team member(s), please list name, email, Github account, and role in the project.*

Name: RUWEN GUO
Email: 1215884602@qq.com
Github: GRW999
Role: Lead Developer

**Comment by ErinOCon** [comment]
Hi @FroghubMan, thank you for submitting this proposal. We will not be moving forward with this project as we would like to focus our grant support on the larger scope of your work ([here](https://github.com/filecoin-project/devgrants/issues/728)).  We will be in touch by email to discuss the next steps for SectorScan.
