### ISSUE TITLE
Proposal for Open grants - Metaverse project with both fantasy and real life value use cases

### ISSUE THREAD

**Issue by prashbi** [filecoin-project/devgrants#736]
# Open Grant Proposal: `Milkyway Infinity Metaverse`

**Milkyway Infinity Metaverse:**

**Proposal Category:** `metaverse`

**Proposer:** `prashbi`

**(Optional) Technical Sponsor:** `No`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** "No"

# Project Description

We are creating a metaverse called Milkyway Infinity, which will specifically target NFTs, Gaming, Entertainment, Video streaming and Real-world services such as VR based eCommerce shopping & Spaces explorations(real estate), Brand promotions, Advertisements, Property tokenisation, Banking & Payment system, Insurances data management with claim approval system and Data verification system through our Blockchain technologies, which will directly help people from different walks of life globally.

Milkyway Infinity metaverse is a world of fantasies which connects, with real-world infinity utility services globally.

Milkyway Infinity metaverse is planned in 3 phases, with 5 years timeline. Considering this as a vast project, we are currently breaking down our metaverse into 3 phases.

1st Phase

The 1st phase comprises the Akiko planet - NFTs and Gaming beta stage.

2nd Phase

The 2nd phase comprises the Wonderland planet - Games launch and MWI tokens beta stage.

3rd Phase

The 3rd phase comprises the MWI token launch and building real-world infinity services according to global norms and requirements, and launching the services, which can cater to the global audience.

**AKIKO**

Akiko a planet exclusively meant for our Milkyway Infinity Metaverse community. Anyone can become a part of our community by purchasing the Akiko NFT avatars, which are capped at 45000 avatars which will be incorporated in the wonderland games and will also be available on multiple blockchains, marketplaces and exchanges. Members of our community will get priority community mint for all the upcoming NFT launches and will also get exclusive free access to play to win games in our Gaming land, with privileges of exploring other planets, freebies, and prior access to all assets under Milkyway Infinity metaverse.

**WONDERLAND**

Wonderland – A fantasy planet comprising of many mini lands such as gamer land, music land, social media land, movie land, art land and would act as a marketplace too, for other communities or individuals to launch their fantasy lands. As part of the gamer land, anyone can launch and host games alongside us and use MWI tokens for rewards. Gamers can also earn tokens by advancing different levels across different games. Essentially, we are creating a universe of games and more.

As part of media and entertainment lands which is decentralized, we shall be powering content creators to post their content be it (music, art, short videos, tweets or any digital content) in our metaverse and earn money based on views, branding and influencer marketing.

**YOURTH**

Yourth – Pronounced as ‘Earth’ – our home planet, this is where all the real-world blockchain use-case projects that would really add value to the society will be ideated and developed. We have various plans to step into retail, real estate, banking, supply-chain and other Web3 use-cases. We intend to offer our blockchain products as a service for anyone from big MNCs to a common man to benefit from our Web3 solutions.

As we would be a metaverse comprising of different verses from fantasies to real life, providing infinite universes, infinite possibilities and infinite profits, the whole world is for sure going to be glued to our Milkyway platform

More details on our pitch can be found at: https://1drv.ms/b/s!ApWB4hey3mJGg4hBu9w9kr_TlyeapQ

**Milkyway Infinity Metaverse is created by PRASHBI labs, which is owned by PRASHBI GLOBAL SERVICES.**

## Value

From Milkyway Infinity Metaverse project, Filecoin will be benefitted in two ways in long term. One is through Filecoin branding in our NFT avatars which is incorporated in games, and in meta data. Secondly, as Filecoin would be our default storage,  all the content hosted in our metaverse by the creators will be stored on Filecoin, generating a passive income for Filecoin.

We intent to get everything right. The risk of not getting this right might lead to weaker community and less traction and in turn less profits. We have staged our phases in such a way so that we can avoid major risks or traps. While we progress through stages 2 and 3 of the projects, we plan to widen our team for faster execution and quality product

## Deliverables

We will be delivering the project in phases mentioned below:

<u>**Phase 1**</u>: Launch of Akiko NFTs alongside the first web-based game and our project website. We will be focusing more on the NFT pre-launch, Game beta stage and community building during this phase

<u>**Phase 2**</u>: With the grants, funding raised from Phase1, we shall be launching Akiko NFTs and the web game and developing more games which are rewarding to players and a Minimum of 1 multiplayer game will be delivered as part of game land. Decentralized content creation platform integrated with Filecoin for music, videos, and artworks. YouTube alike decentralized video streaming platform for videos, music albums and a virtual museum for all the artists and individuals to showcase their NFTs and earn

<u>**Phase 3**</u>: In phase 3, we would be established as a blockchain service company. This is our vision where we partner with different companies aiding them with blockchain-based solutions

## Development Roadmap

**<u>Milestone 1</u> – NFT design and contract functions implementation**

NFT concept visualisation and design. Filecoin integration to store the NFTs on Filecoin IPFS and NFT test contract creation on Ethereum, Polygon and Solana.  
Artist NFT drop, Whitelisting, social media platforms launch, Website with Initial beta game(game testing), and community marketing/promotion"

People/Skills Needed:  
1 x Web3 dev  
1 x BE Dev  
1 x FE Dev
3 x Game Dev
2 x Digital artist  
1 x PM/Ops/Marketing  
Total number of people: <u>9</u>

Cost per day (Ex GST) - $200  
Number of Days – 40

Contract creation - $2000

Marketing expenses - $15000  
Total Cost (Ex GST) - <u>$89,000</u>

Note: GST is at 30% as per Indian laws

**<u>Milestone 2</u> – Launch of NFT and game live**

NFT launching – whitelist transfers, airdrop transfers and public minting and game access to NFT holders

Creation of media platform for short videos, artworks and music based on Web3. All the views, sponsorship and licensing will be based on failproof Web3 infrastructure

People/Skills Needed:

2 x Web3 dev  
4 x BE Dev  
4 x FE and app Dev
2 x Game Dev
2 x PM/Ops/Marketing

  
Total number of people: <u>14</u>

Cost per day (Ex GST) - $200  
Number of Days – 120

Contract creation - $10000

Infrastructure costs - $30000  
Total Cost (Ex GST) - <u>$376,000</u>

Note: GST is at 30% as per Indian laws

**Milestone 3 – Based on the community strength and NFT profit, the remaining milestones will be charted out accordingly**

## Total Budget Requested

$465,000

<u>Budget Breakdown:</u>
 Tech Development - $336,000  
Project/ session identity and framework - $56000  
Procurement of Content Partner/s - $16000  
Marketing/Influencers - $15000

Deployment and systems - $42000  
TOTAL: $465,000.00

## Maintenance and Upgrade Plans

Incremental maintenance and upgrades will be planned as per the milestones and all the bugs and issues reported will be categorised based on priority and similarly releases will be planned to deploy the upgrades. During the first 6 months post launch active retrospection will occur.

We are planning to add resources who can look after support related activities

# Team

## Team Members

LOKESHWARAN B  
PRADEEP GS  
NAGABINDU SU  
ASHNA VISHMAY

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/lokeshwaran2491
https://www.linkedin.com/in/pradeep-gs-3a1a15a7
https://www.linkedin.com/in/nagabindu-s-u-809a25121
https://www.linkedin.com/in/ashna-jhunjhunwala-09a96a84

## Team Website

Website is under construction. Social pages are:
Twitter:
Discord:

## Relevant Experience

Our team is a young and energetic team who have partnered hands with a vision to create breakthrough solutions. We have vast experience across development, operations, artistry, product management. Our team consists of and includes:

**Lokeshwaran** is a Data Science consultant having around 8yrs of experience across skills namely java, javascript, python, cloud computing, solution architect, datascience and blockchain. He has worked for companies developing large scale solutions. His future plans includes research and creating unified solutions on blockchain, datascience and quantum computing

**Pradeep** is an entrepreneur who has started his journey into Foodtech, Blockchain and Cryptocurrency. He is an avid crypto follower and strategist. He has good leadership qualities and has around 8 years of experience as a startup consultant and mentor and is now more focused on working as a crypto consultant. He has good experience in creating NFT avatars and contracts. He is excellant at marketing and community management

## Team code repositories

No public code repositories we possess as of now. We can showcase our NFT script, game and further codes through our partnership as and when we develop

# Additional Information

We got to know about the open grants through filecoin moderators whom we had met in person during an event.

For any addition information or queries, please contact us at pradeepgs@prashbi.com and lokeshwaran@prashbi.com

**Comment by ErinOCon** [comment]
Hi @prashbi, thank you for your proposal. Unfortunately, we will not be funding the outlined work. We recommend collecting verifiable traction data that can demonstrate the addressable market of the platform. This information will help present the value of your project to the community!
