### ISSUE TITLE
Next Step Microgrant: d-blog system with token gating

### ISSUE THREAD

**Issue by NftTopBest** [filecoin-project/devgrants#737]
### 1. What is your project? (max 100 words)
d-blog system with token gating
Get the first place in the Ken Labs && IPFS Metaverse Hackathon
https://twitter.com/Web3HackerNinja/status/1539525943483863040

github: https://github.com/NftTopBest/d-blog-to-earn
demo: https://dev.web3nft.social/0xC6E58fb4aFFB6aB8A392b7CC23CD3feF74517F6C

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
  1. it uses the pinata service to upload json file(with the blog content) and image to IPFS
  2. it uses the https://litprotocol.com/ to encrypt the content before upload to IPFS
  3. so it has the token gating feature that make a way for creator to have a payment logic for their web3 content

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Will switch to nft.storage also have some optimization for the user upload file progress
1. switch to nft.storage SDK/API service
2. have an AWS s3 service that upload file to AWS s3 at the same time while uploading file to IPFS
3. it will much faster and better UX for users that can see the result instead of waiting for IPFS to upload it and pin it for a domain
4. improve && redesign the whole UI so it will be focused on blog creation and make it GTM!

 
### 4. Is this project open source?
yes, MIT

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
yes

Get the first place in the Ken Labs && IPFS Metaverse Hackathon
https://twitter.com/Web3HackerNinja/status/1539525943483863040
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Bruce
Email: [nfttop.best@gmail.com](mailto:nfttop.best@gmail.com)
Github: [@NFTTOPBEST](https://github.com/NftTopBest)
Role: Main Developer

* How did you learn about our microgrant program?
From the IPFS member to tell me what I can do for Next Step after get the Hackathon Prize.

* If your project was created as part of an event or hackathon:
  * What was the name of the event?
  Metaverse Hackathon： https://dorahacks.io/zh/hackathon/21/

  * Please link to your hackathon submission
https://dorahacks.io/zh/buidl/2876

**Comment by ErinOCon** [comment]
Hi @NftTopBest, this grant has been approved! We will reach out by email to confirm payment details.

**Comment by ErinOCon** [comment]
Hi @NftTopBest, can the report be provided by next week?

**Comment by NftTopBest** [comment]
> Hi @NftTopBest, can the report be provided by next week?

oh, I am afraid I still need more time, will be about two weeks. Will report before 2022-11-21.

**Comment by NftTopBest** [comment]
Hi @ErinOCon I already submit the form.
