### ISSUE TITLE
Next Step Microgrant: Encryption Pinner

### ISSUE THREAD

**Issue by xx014939** [filecoin-project/devgrants#738]
### 1. What is your project? (max 100 words)

Encryption Pinner is a simple development tool, which allows users to encrypt their files with an encryption method of their choice, and then pin them to their personal/business Pinata gateway.

https://github.com/xx014939/node-encrypt-decrypt-file

https://devpost.com/software/encryption-pinner?ref_content=user-portfolio&ref_feature=in_progress

### 2. How will IPFS, Filecoin, or related technology be used for this project? 

Encrypted files are pinned to Pinata using a custom Pinata gateway. From there, users can retrieve their encrypted files in the same way they would retrieve any other IPFS hosted content. The files can then be decrypted using the passcode the user entered initially.

IPFS hosts all of the file which pass through our application, and is vital to functionality of the app.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Currently, if users wish to use their own custom Pinata gateway then they must clone our repo and run the application locally. We would like to add functionality for users to easily input their own Pinata gateway details securely and pin directly without a need for running locally.

We would also like to improve our current UI to make it easier for users to upload, encrypt and decrypt files. We feel this can also be extended to provide bulk upload capabilities. 

In addition to the above we would like to provide high quality technical documentation for developers, who may want to utilise the application in different ways.
 
### 4. Is this project open source?

Yes, open source MIT license

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes of course. Please email me if you have any progress requests, and I will share an update upon completion also.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions

Yes, this project won 3rd place for the "On The Tools" prize pool at the Spring Filecoin hackathon - https://devpost.com/software/encryption-pinner?ref_content=user-portfolio&ref_feature=in_progress

Confirmation in closing ceremony 16:07 - https://www.youtube.com/watch?v=4kLXEqQ6tL0
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Name: Naail El-Sawah
Role: Sole Developer
Email: naailelsawah@gmail.com
Github: xx014939

* How did you learn about our microgrant program?

From competing in Filecoin sponsored hackathons

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)

Filecoin Spring Hackathon

  * Please link to your hackathon submission

https://devpost.com/software/encryption-pinner?ref_content=user-portfolio&ref_feature=in_progress

**Comment by xx014939** [comment]
@ErinOCon Im happy to answer any questions or concerns you may have :)

**Comment by ErinOCon** [comment]
Hi @xx014939, this grant has been approved! We will send an email to confirm payment details.
