### ISSUE TITLE
Next Step Microgrant: Jotter Dapp

### ISSUE THREAD

**Issue by jotterdapp** [filecoin-project/devgrants#739]
### 1. What is your project? (max 100 words)
Jotter is a web3 note-taking application, with an emphasis on encryption, decentralization and censorship-resistance of data. We are building the notion equivalent for the decentralized web using modern web technologies such as Tauri.
We started off as a small project at a College Level Hackathon, but are now wanting to take this up full-time due to the response we got from the community and developers at large. The vision of Jotter is to build a decentralized and performant note-taking application for everyone

Currently, Jotter is in it's MVP stage, where we are building the core-fundamentals of the application.

Our work - https://github.com/jotterdapp/jotter
MVP Demo - https://youtu.be/JmC5LI6a8zs

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

1. IPFS / Filecoin acts as the foundation for this project, where notes of all our users will be stored
2. We use Textile to keep track of user's CID's and provide a smooth UX
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Our objectives are defined:
 -   Textile Database Implementation
 -   Wallet Integrations [Metamask, WalletConnect]
 -   Implement an editor in Tauri (https://tauri.app/)
 -   Implement tags and note-taking widgets like Notion

Jotter's roadmap is updated regularly here - https://github.com/jotterdapp/jotter#readme
 
### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: No
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Hashim Conor - Senior Engineer
Email - jotterdapp@proton.me
Github - https://github.com/jotterdapp

Joshua Seth - Senior UI Developer
Email - joshhuaseth@proton.me
Github - https://github.com/joshhdb

* How did you learn about our microgrant program?
Through our participation at the ETH Amsterdam (Not for this project!)
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission - https://youtu.be/JmC5LI6a8zs

**Comment by ErinOCon** [comment]
Hi @jotterdapp, this grant has been approved! We will send an email to confirm payment details.
