### ISSUE TITLE
PinkPaper: Decentralised Publishing Platform

### ISSUE THREAD

**Issue by pinkpaper** [filecoin-project/devgrants#740]
# Open Grant Proposal: `Pink Paper: Decentralised Publishing Platform`

**Name of Project:** Pink Paper

**Proposal Category:**  `app-dev`

**Proposer:** `pinkpaper`

**(Optional) Technical Sponsor:** `NA`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** "Yes" 

# Project Description

Pink Paper provides a decentralized censorship-free publishing platform for individuals and communities worldwide. At the same time, one can raise funds for their endeavors on the platform allowing donating to world-changing technologies. 

There's increasing curbs on the free speech in the world dominated by the big tech. Everyone should have free access to put forward their viewpoint without any limitations. 

Pink Paper will provide a decentralised and censorship-free platform for everyone to use and express their views about different topics.

## Value

There are increased attacks from big tech worldwide on free speech. Big Tech platforms are increasingly banning specific individuals and communities from their platforms. In these testing times for free speech, Pink Paper aspires to protect the ethos of free speech and freedom for communities who want to raise their voice. Even Stani, founder of Aave was recently banned from Twitter for posting a joke which highlights the need for a decentralized platform. 

We will provide a free platform which will be available with zero censorship and there's increasing need for such a platform where users data is being used to profit billions and at the same time deplatform them anytime the big tech wants.

## Deliverables

- Decentralized Publishing Platform: 
 Pink Paper will provide a decentralized and permissionless publishing platform for individuals and communities worldwide to express their opinions and share the information with the rest of their communities. Users can come and publish blogs and other forms of content on the platform and showcase it to the world.
 
- Crowd Fundraising platform:
 Any individual, DAO, or any other entity can start a crowdfunding campaign on the platform. It will provide the opportunity to pay to their favorite campaigns and communities to raise funds for their respective projects.
 
- Tipping System
 Creators are the center of the Pink Paper. We will provide the tipping option with all the content posted on the platform. Fans and communities can tip their favorite creator or publisher with the in-built tipping system.
 
 
- Social Profiling
 Users' profiles on Pink Paper can act as social profiles and further down the line we can add more social media-focused features to increase the addressable market for Pink Paper. 
 
- Reputation system
 Going forward we will implement analysis to benefit popular and viral threads. Not just this, we will use the same to create a reputation of an account that will help them to be more visible on Pink Paper.
 

## Development Roadmap

Phase 1 (First three months):

1. Launching the testnet with the following features:
a. Decentralized content publishing
b. Tipping / Donations for the creators to contribute to creators' economy
c. A minimalistic design for content creators to ease creating content
d. Direct IPFS link sharing of the articles
2. Bringing initial creators and communities to the platform
3. Building community and establishing the community on different social platforms

Phase 2 (Next three months):

1. We will launch a Community Funding Platform for projects.
2. Increasing Social profiling for our users by connecting their different social media profiles on Pink Paper
3. Reputation system for accounts
4. Partnerships with DAOs and projects to start publishing on the platform.

## Total Budget Requested

We are looking for a total of $30,000

## Maintenance and Upgrade Plans
We are pursing this project for a long term. We guarantee a minimum of 5 years maintenance and updating according to the requirements.

# Team

## Team Members

Rupin Mathur(Founder)

He has been a Blockchain Maximalist since 2015 and an advocate of decentralization and self-sovereignty. He worked as marketing head for QuadB apparels from 2015-2017, India's second-largest custom apparel brand where he established the first VAL (Virtual Assembly Line) basically creating hundreds of nodal points for blue-collar workers scaling the business infinitely. From 2017 onwards, he decided to go all-in Web3 and thus acted a crucial part in setting up Finstreet, India's 1st Crypto Education Platform and scaled it to a community of 70,000+ Web3 Enthusiasts and 4.2 million social media following.

During this journey, he worked alongside brands such as WazirX, Huobi, Polygon, Aave, and many more to help bring their respective platforms adoption in the Indian Markets, 

He has begun his journey to create and bring adoption for the World's 1st Decentralized content management platform, Pink Paper

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/rupin-mathur-3a7689141/

## Team Website

https://pinkpaper.xyz/

Test Site: https://matic.pinkpaper.xyz/

## Relevant Experience

The team is well versed with the problem statement and has the required technical and business expertise to solve it on a large scale. 

## Team code repositories

https://github.com/pinkpaper/pink-paper-frontend

# Additional Information
How did you learn about the Open Grants Program? Website
Please provide the best email address for discussing the grant agreement and general next steps. team@pinkpaper.xyz

**Comment by ErinOCon** [comment]
Hi @pinkpaper, thank you for your proposal! We would be interested in supporting work that is focused on the development of one key system. Would you be open to submitting a new proposal specifically for the publishing platform? This proposal should include a specific adoption strategy, key desirable outcomes, and an in depth development roadmap.

**Comment by pinkpaper** [comment]
**Name of Project:** Pink Paper

**Proposal Category:** `app-dev` 

**Proposer:** `pinkpaper`

**(Optional) Technical Sponsor:** `NA`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:**  "Yes" 

# Project Description

Pink Paper provides a decentralized censorship-free publishing platform for individuals and communities worldwide. At the same time, one can raise funds for their endeavors on the platform allowing donating to world-changing technologies.

There's increasing curbs on the free speech in the world dominated by the big tech. Everyone should have free access to put forward their viewpoint without any limitations.

Pink Paper will provide a decentralised and censorship-free platform for everyone to use and express their views about different topics.

## Value

There are increased attacks from big tech worldwide on free speech. Big Tech platforms are increasingly banning specific individuals and communities from their platforms. In these testing times for free speech, Pink Paper aspires to protect the ethos of free speech and freedom for communities who want to raise their voice. Even Stani, founder of Aave was recently banned from Twitter for posting a joke which highlights the need for a decentralized platform.

We will provide a free platform which will be available with zero censorship and there's increasing need for such a platform where users data is being used to profit billions and at the same time deplatform them anytime the big tech wants.
## Deliverables

Decentralized Publishing Platform: 
Pink Paper will provide a decentralized and permissionless publishing platform for individuals and communities worldwide to express their opinions and share the information with the rest of their communities. Users can come and publish blogs and other forms of content on the platform and showcase it to the world.


## Development Roadmap

Phase 1 (First three months):

1. Launching the testnet with the following features:
a. Decentralized content publishing
b. Tipping / Donations for the creators to contribute to creators' economy
c. A minimalistic design for content creators to ease creating content
d. Direct IPFS link sharing of the articles
2. Enhancing user experience while publishing using the feedback of our community
3. Building community and establishing the community on different social platforms

Amount requested: $10,000

Phase 2 (Next three months):

1. We will launch a Community Funding Platform for projects.
3. Partnerships with DAOs and projects to start publishing on the platform.
5. Enhancing the security of the publishing platform. 
6. Changing the content template, where users can select from a variety of templates to showcase their blogs on. 

Amount requested: $10,000

## Total Budget Requested

We are looking for a total of $20,000


## Maintenance and Upgrade Plans

We are pursing this project for a long term. We guarantee a minimum of 5 years maintenance and updating according to the requirements.
# Team

## Team Members

Rupin Mathur(Founder)

He has been a Blockchain Maximalist since 2015 and an advocate of decentralization and self-sovereignty. He worked as marketing head for QuadB apparels from 2015-2017, India's second-largest custom apparel brand where he established the first VAL (Virtual Assembly Line) basically creating hundreds of nodal points for blue-collar workers scaling the business infinitely. From 2017 onwards, he decided to go all-in Web3 and thus acted a crucial part in setting up Finstreet, India's 1st Crypto Education Platform and scaled it to a community of 70,000+ Web3 Enthusiasts and 4.2 million social media following.

During this journey, he worked alongside brands such as WazirX, Huobi, Polygon, Aave, and many more to help bring their respective platforms adoption in the Indian Markets,

He has begun his journey to create and bring adoption for the World's 1st Decentralized content management platform, Pink Paper

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/rupin-mathur-3a7689141/

## Team Website

https://pinkpaper.xyz/

Test Site: https://matic.pinkpaper.xyz/

## Relevant Experience

The team is well versed with the problem statement and has the required technical and business expertise to solve it on a large scale.

## Team code repositories

https://github.com/pinkpaper/pink-paper-frontend
# Additional Information
How did you learn about the Open Grants Program? Website
Please provide the best email address for discussing the grant agreement and general next steps. [team@pinkpaper.xyz](mailto:team@pinkpaper.xyz)

**Comment by pinkpaper** [comment]
Hi @ErinOCon , thank you for your guidance. We have updated the proposal. Please let me know if there are any further questions regarding the project. Looking forward to build a truly decentralized, censorship-free publishing platform for everyone.

**Comment by pinkpaper** [comment]
Hi @ErinOCon , please let me know if you need any further information or details about the project.

**Comment by ErinOCon** [comment]
Hi @pinkpaper, thank you for the additional information. We will be back in touch as soon as our review is complete!

**Comment by pinkpaper** [comment]
Thank you @ErinOCon for the update.

**Comment by ErinOCon** [comment]
HI @pinkpaper, this grant has been approved! We will be in touch by email to discuss next steps.

**Comment by pinkpaper** [comment]
Thank you @ErinOCon for the approval.
