### ISSUE TITLE
Next Step Microgrant: Yellow Umbrella - a generative, DNA data-based game

### ISSUE THREAD

**Issue by chris-lovejoy** [filecoin-project/devgrants#742]
### 1. What is your project? (max 100 words)

Yellow umbrella is a generative NFT game based on DNA exploration.

Players use their genetic sequence to mint a unique NFT. Players can recombine their NFT with that of other players to generate new NFTs with different traits. Additionally, they can use the platform to discover more about their health. In the future, players will be able to optionally share their genetic data with researchers.

The repo is available here: https://github.com/billionshealth/yellow-umbrella
A live demo is available here: https://yellowumbrella.art/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

The generative NFTs are stored on IPFS (using NFT.storage). In future, we will introduce the option for players to optionally store an encrypted version of their genetic data on IPFS, which they can control and share (for health advice and with researchers).

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The grant will enable us to build out the functionality for players to store their encrypted genetic data on IPFS. At present, the genetic data is hashed to generate the NFTs but not stored. Additionally, we would add analytics and other educational material around genetics and health, tailored to the individual’s genetic data.

The grant would enable us to hire the dev support required; a part-time full stack developer ($2k for 2 months), a part-time blockchain developer ($1.5k for 2 months) and a part-time data analyst and content writer for genetic health-related analysis and educational material ($1.5k).

 
### 4. Is this project open source?

Yes, GPL license

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, we are happy to do so.

  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes, we are very aligned.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

We submitted the project to the encode x polygon hackathon, although there were no Protocol Lab prizes there.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Christopher Lovejoy - [Christopher.lovejoy1@gmail.com](mailto:Christopher.lovejoy1@gmail.com) - [github.com/Chris-Lovejoy](http://github.com/Chris-Lovejoy) - Lead developer, medical doctor
Ali Rizvi - [ali.rizvi.mck@gmail.com](mailto:ali.rizvi.mck@gmail.com) - [github.com/Syedrizvi](http://github.com/Syedrizvi) - Lead game designer, ML engineer
Abbas Reza - [abbasraza32@gmail.com](mailto:abbasraza32@gmail.com) - [github.com/MAbbasRaza](http://github.com/MAbbasRaza) - Front-end developer

* How did you learn about our microgrant program?

From Ally Haire (@DeveloperAlly), who advised us to apply at ETH Amsterdam.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

Encode x Polygon Hackathon (but no project profiles available yet - was submitted via a submission form)

**Comment by ErinOCon** [comment]
Hi @chris-lovejoy, this grant has been approved! We will send an email to confirm payment details.
