### ISSUE TITLE
Next Step Microgrant: Perpetual Democracy

### ISSUE THREAD

**Issue by SeeeRGo** [filecoin-project/devgrants#743]
### 1. What is your project? (max 100 words)

The project aims to create system for perpetual voting for communities to curate their policies and allocate and re-allocate resources as soon as majority's opinion shifts towards better option. To help users avoid being swamped by choices there is a voting power delegation system in place. There could be multiple delegates per user, delegates can be added or removed instantly without any term limits and user's pick always take priority to distribute user's voting power over any of user's delegates picks. OrbitDB is used to keep track of delegation graph

https://github.com/SeeeRGo/chainlink-hackathon-project

Submission video from chainlink hackathon spring 22
https://youtu.be/SJp-EdJQEDE

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
There are two main use cases for OrbitDB I intend at the moment:

- Keep track of delegation graph (already implemented)
- Store policy issues that are being voted on

  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

**Minimum goals**

- Deploy a live demo
- Add capabilities to host multiple policy issues (create, explore and vote on)
- Add "Production grade" UI (very minimalistic, but move away from "concept on a napkin" UI it has now)

**Maximum goals**

- Add issue grouping, sorting and filtering
- Re-write smart contracts to Solana blockchain
- Come up with a concept for creating separated communities and segmenting issues

 
### 4. Is this project open source?

YES

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

YES
  
### 6. Does your proposal comply with our Community Code of Conduct?

YES

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  I did submit for prizes even won a little bit)
https://devpost.com/software/permanent-voting-with-fractional-vote-delegation?ref_content=user-portfolio&ref_feature=in_progress
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Sergey Mizin seeergo@yahoo.com - creator and one man army for now
https://github.com/SeeeRGo 
* How did you learn about our microgrant program?
I actually learned about microgrant program from an email congratulating me on winning one of Runner-up prizes from Filecoin on the hackathon
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  ChainLink Spring Hackathon'22

  * Please link to your hackathon submission
 https://github.com/SeeeRGo/chainlink-hackathon-project

**Comment by SeeeRGo** [comment]
@ErinOCon Hi I created this one because couldn't find one I made previously https://github.com/ipfs/devgrants/issues/196
Which one should I keep open then? Also would you be so kind to share any updates on the application review status?

**Comment by ErinOCon** [comment]
Hi @SeeeRGo, thank you for your proposal and for your patience! This grant has been approved. We will be in touch by email to confirm payment details.
