### ISSUE TITLE
IPFS powered social media decentralized marketing platform

### ISSUE THREAD

**Issue by vincent-raven** [filecoin-project/devgrants#744]
# Open Grant Proposal: `IPFS powered,  decentralized, social media, marketing platform`

**Name of Project:** meCo; Mind your own business; we’ll provide the tools

**RFP Category:** *community* *marketing/main stream usage*

**Proposer:** Vincent-raven

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:**  yes; disclaimer... Please take the time to understand… this is a L2 delivery system for all ‘open sourced’, compliant tools. It is a ‘decentralized’ ‘open source’, social media, P2P, marketplace using IPFS as the upload server; meCo will NOT be a middleman; it will do minimal data mining, and will NOT sell [out] data nor ads… it is a tool for the masses to easily learn and understand W3 without digging deep into the tech weeds; and we all know it is a vortex, well out of reach for the ‘norms’ that only have interest in being users of tech. meCo is designed as a P2P interactive tool using ipfs as the main server and will offer access to all W3 tools being built, including filecoin. 
meCo W3 tools will be provided, mainly by outside vendors mostly in the open source communities; therefore, the compliance is based on the chosen tools.  Being a service provider, our operational practices will be exposed as it will be on display in the way the tools are managed. The moment we deviate from the core principles of not being on team, oligarchy, it will be exposed by exclusive deals and added expense items on the menu; none of this is in the plan.
Another part of the master plan is to give away ownership (open source/DAO ) much more preferably to _contributors,_ not bankers (as much as possible; money is needed to kick start of course; the launch and traction is needed first). The vision for sharing the economics of the platform, as well as decentralizing the social platform’s real-estate, very much also fits well into Juan’s **‘funding the commons’** vision. Day one, anyone joining the opens sourced platform, can monetize their profile. With a little effort in that direction, they can fund their needs as well as help promote their causes with the easily accessible P2P sponsor and donate tools. In the sense of helping the ‘commons’, this is exactly what meCo is being designed to do; an everyday guy, not a tech guy, is building a platform for commoners like himself, to start playing with W3 with the option earning a living/funding in the process. Most all found in W3 communities, are tech people only talking to tech people; they speak their own language and well over the head of the [soon to be] end users… meCo will break this pattern up and let everyday people join the club; I know because I’m one of them.

**Project Description**
meCo is being designed to be the introduction of W3 to the masses in the same way AOL introduced the world to the internet; simple point click, follow directions and learn as you go. Can I ask, what is the best, most used, interactive, main stream tool, using ipfs, outside the github community…? I don’t know of one; there is a need for heavy focus on the UX, from and for the ‘norms’ perspective. meCo will close the huge gap between tech builders and norms via a social platform which is sure to ‘bring significant new usage’; it will be the Panama Canal.
When thinking decentralized, we will NOT have a native [centralized] coin that is needed to transact; creators are free to pick the tools, wallets and currencies of choice; aka open source/free market (the project however will be tokenized and ownership will be distributed later in the development). We will NOT create the W3 tools ourselves but we will provide the plug and play use case for the tool builders to market their wares to the public as need surfaces. Backend tools will be incorporated as the project evolves.
Anyone can set up a private or public marketplace; it can be localized or off site (redirect hyperlinks). All user exchanges are P2P.
meCo will provide both a launch pad for tool builders and simple point and click tools to allow seamless adoption by the everyday people, without having to dive into the ‘tech’ in order to learn what/how IPFS, IPLD, IPNS… is/works, in order to be involved; they will just need to solve problems in their world; ‘where and how do I pay for/upload/display/save this…?’
The simple wallet connections will provide the public keys and quick links the needed/their favorite wallets so the users just have to ‘click here’ and all the needed public info will be fetched and populated to the appropriate fields (in the future DID connected). 
In the spirit of ‘Funding the Commons’, donations and sponsorships are on every post allowing for P2P support at all times; chains, devs and marketers are free to offer rewards/coins to the anyone as ‘air drops’, transactions or if they agree to promote an interest in their timeline, as a form of payment. The heart of this project is the first, P2P, S2E (Social to Earn) ecosystem. Newbies will be able to easily dip their toes in the water using these easily understandable, ‘alternative mining’ mechanisms; they can accumulate coins/tokens/NFTs without the need for expensive equipment; no linux knowledge, no cmd line prompts; just interact, collaborate and earn….
Atomic swaps will allow for NFT creators to transact with work as another alternative payment currency; exchanging parties can agree on whatever they wish as a fair value and most will need [outsourced] pinning services. Filecoin will setup a marketplace to allow pinning farms to quote their rates. On your website, there is a link for a textile produced marketplace for bidding on pinning service providers thru filecoin; the site tells of a release date of spring 2021; 1 yr behind. meCo will have it up and running (in prototype) in weeks (with some input); P2P, we will not be the middleman.
The only data mining will be forms to provide transactional details that were offered and executed, on the chain of choice, in an IPFS hash (in most cases), which will allow for the parties to have the settlement information should they need to settle disputes.
‘Studio’ will provide the tools to allow artists to generate CIDs for their creations. Within the studio will be a catalog of pinning services (among others) for them to catalog their work and of course, save it.
DID login will be adapted and a form of social credit will be developed within platform. 
The platform is being designed with W3 in mind (containers to have CIDs and such) but will start mostly in W2 format and as the tools are developed and implemented, the users/creators will take part in the transformation as it will morph into a full W3. With that, the created content will be exportable to other platforms that may specialize in broadcasting/streaming, publications, marketplaces…
The decentralized features makes this a ‘plug and play’ use case for all W3 tools being built. Any will be allowed to offer their utility in the ‘open source’, P2P market for people to use; may the best tool win.

**Value to the Filecoin and IPFS ecosystems**
Introducing ipfs [effortlessly] to the masses with a simple use case, in a familiar tool they already use every day, social media, will normalize this part of the revolution for the world. They will barely notice the difference when they upload, but they will be introduced to the CID url hashes helping it to become the new normal.
When the artists start to catalog their work, they will learn about pinning and about filecoin being the industry standard and potentially best in its class. It will give both tools a market to the masses; this is needed by much of W3 development.
With a filecoin ‘marketplace’ on the platform, the posted competing farms will be easily accessible in the Studios, allowing for mass adoption in a more ‘mainstream’ venue. As more people start to be active all day, the nodes will spread far and wide, of course securing the network more and more.
IPFS still uses youtube to present its recorded info…!! This needs to be fixed…! What will fix this shortfall…? I believe it happens because there’s no good display platform to present them to the public… meCo will provide the tools and allow for ipfs uploaded videos and easily accessible, cataloged, display.

**Deliverables**
Mobile; on some of the features the display on mobile is not acceptable and ruins the UX; this will require some root layout work. The upload to ipfs on mobile works well and we need mobile users to start having the experience. (4 weeks, $12,000)

Wallets; currently the wallets are designed to be launched from the currency/coin perspective; with that they are directed generally to the ‘core’ wallet or an ‘approved/recommended’ choice. With the emergence of quality multi-coin wallets like metamask and others, there needs to be the alternative option of launching these wallets and allowing the users to set up defaults for their most often used currencies. (3 weeks, $9,000)

Studio; Develop a customizable ‘studio’ landing page to allow artist to add their creations, upload to ipfs, create NFT’s and select pinning service options. (6 weeks, $18,000)

Pinning Service form in marketplace; work together with protocol labs to develop a form too allow servers to offer their pinning rates as a service. (2 weeks, $6,000)

Versatile side bars; for the prototype, the ‘side hustle’ bars are fixed on a 3 promotions per side layout. The final design will allow the users negotiate different scales layout designs, from 1-4 container per side. As the users [optionally] choose to, these bars will grant them free ‘real estate’ to develop/design as they wish. As they increase the sidebar content, they can add several different themes or campaigns and as they add content to their timeline, the sidebar content will cycle thru the variable list. This will create a much better UX from both perspectives; the users scroll as well as the ‘promotions’, varying the attention grabbing real estate content. (6 weeks, $18,000)

DID; With accountability being an important feature, the development of a proper ‘form’ as well as the implementation of a DID script such as self.ID from the ceramic developers, this will also help the public become acquainted with this emerging tech. (5 weeks, $15,000)

NFT payment; create the options and proper forms allowing users to accept NFTs as a form of payment. (3 weeks, $9,000)
Graphic design; the focus of the MVP build has been exclusively on functionality. Part of the UX will be to make the aesthetics of the platform. (8 weeks, $24,000)

Organized transactional receipt formation; one of the key features of the platform is user interacting and transactional record keeping. Allow the users to edit proposed deals will require a record of edited campaigns and a log of the ipfs revisions used in transactions in a chronological order so as to protect all parties from bait and switch dealings. Eventually planned for ceramic network. (6 weeks, $18,000)

Misc: Along the way speed bumps will happen ($6,000)

Add more W3 features; As things progress along, more and more W3 tools will be added to the mix. Of course, setting up the platform for an ipfs web host will be a huge milestone that has to be mapped out and executed. Other things such as an IPFS chat system is in the plans, https://docs.ipfs.io/how-to/create-simple-chat-app/ These details will not be laid out and budgeted for since it will involve a much bigger team and plan and are more part of the final build.

**Total Budget Requested**
$135,000

**Platform;** Please remember this is a working, MVP, prototype, not yet optimized for mobile https://meco.eeconme.com 

**Contact Info**
[psymplescience@proton.me](mailto:psymplescience@proton.me)

**Team Members**
•	My team is a small group of coders based in India. There are a few on deck waiting to join the team and help the project. Also involved are a few people working on their own W3 tools that collaborate on thoughts and tools. As funds allocate, most specific talent will be added including task specific blockchain [W3] knowledge as well as instructional documentation and influencers talent; remember, this is a marketing play.

**# Additional Information**
**How did you learn about the Open Grants Program?** I have been paying attention to Juan, IPFS, Protocol Labs and all other branches of each, for years during my building process.

**Please include any additional information that you think would be useful in helping us to evaluate your proposal.** Please remember this is built buy a newb, i do not code, looking to make all these wonderful tools being built, user friendly. It is a UX engineering project that will MARKET W3 to the masses; AOL style. The economics are decentralized and the marketing tools (and their simplicity) may not be as easily understood by a dev, as they are by a marketer, but trust the antifragile, viral marketing components are a very crucial key... more so than the code. I look forward to working with you all.

**Comment by ErinOCon** [comment]
Hi @vincent-raven, thank you for your submitted proposal! We will not be moving forward with a grant for this project at this time, as additional building progress is needed. As a next step, we recommend participating in a hackathon for this project!

**Comment by vincent-raven** [comment]
Hi Erin, 
I ask you to please understand, i am not a coder. I am engineering it from a UX perspective. The issues i am trying to solve is that coders all make tools for coders; coders like to talk shop. This is a decentralized social platform using ipfs on all it's uploads; it will offer pinning services and other W3 tools designed by the coders for an enjoyable UX. Can we please have a dialogue on this proposal. What else is being used on a main stream level with a grass roots plan...?

**Comment by vincent-raven** [comment]
As a non-coder i would say my execution has been pretty outstanding. Please remember it is a MVP prototype; ugly but functional. Please reconsider...

**Comment by ErinOCon** [comment]
Hi @vincent-raven, thank you for following up! I will circle back if there are additional support opportunities to consider.

**Comment by ErinOCon** [comment]
Hi @vincent-raven, thank you again for your interest in the grants program. In order to be considered, the prototype for this project will need to be further developed and a strong user base should be in progress. A great way to show case your skillset is through a hackathon!

Should you choose to apply for a grant in the future, we would recommend providing more detail on the educational elements of this project. Happy building!
