### ISSUE TITLE
CodeUp Blockchain Festival - Nigeria 2022

### ISSUE THREAD

**Issue by ogasky** [filecoin-project/devgrants#745]
# Open Grant Proposal: `CodeUp Blockchain Festival - Nigeria 2022`

**Name of Project:** CodeUp Blockchain Festival - Nigeria 2022

**Proposal Category:** `community` 

**Proposer:** `@ogasky`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:**  `Yes`

# Project Description

**Theme: Accessing BlockChain Digital Economy**

This event is organized to skill-up the under-represented people in blockchain technology with basic knowledge in blockchain development, and career opportunities. Also, we shall be having over 500 participants to attend this event and we have lined up speakers from different cities around the world.

Focus is on:

1. Blockchain & Web 3.0
2. Legal Frameworks on Blockchain
3. Smart Contracts
4. NFTs
5. DeFi
6. DAO
7. DApps
8. Cryptocurrency
9. Used Cases of Blockchain
10. Available Blockchain Grants

**Schedule Sessions:**
1. Keynotes session
2. Syndicate / Master class
3. Panelists
4. Hackathon
5. Pitching

**Confirmed Speakers**
Currently our confirmed speakers in the blockchain space include:

1. Deborah Enyone Oni; Managing Partner Hilton Top Solicitors & Blockchain Lawyer. She will be speaking on topic "Blockchain & Web 3.0: The regulatory framework in Nigeria".

2. Dominic Uririe Rume; Is a Certified MetaVerse Expert and Certified Blockchain Architect, an enthusiastic IT professional with proven abilities to analyze engineering concepts clearly and a significant driver of innovation, solutions, and disruptive technologies Globally. He is a valuable member of SiBAN (Stakeholders in Blockchain Technology Association of Nigeria). Through this platform, he has contributed immensely by supporting other players in securing the future through the power of the Blockchain. He is the founder/CEO of VOREM Nigeria. He will be handling a syndicate session on the "MetaVerse & Web 3"

3. Gino Osahon; is a Developer Advocate with IOV Labs. He will be speaking on "DeFi for Beginners"

4. Edegware Gift; he is the Founder/CEO of Gsoft Interactive Systems Ltd & he will be handling a syndicate session on "How to create your crypto wallet"

5. Onose Ogaga; he is the Founder/CEO of WittyHub and the convener of CodeUp Blockchain Festivals. He will be talking on "The Available Blockchain Opportunities"

More speakers will be listed in due course. However we ask for your support to help us spread the word about this event to your network & get more people to register. Thank you.

**Code Of Conduct (https://www.meetup.com/CodeUp-Africa/)**
Our meetup is dedicated to providing a harassment-free meetup experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion (or lack thereof), or technology choices. We do not tolerate harassment of meetup participants in any form. We do not hold meetups in religious and political settings, also sexual language and imagery are not appropriate for meetup venue, including talks, workshops, parties, Twitter and other online media. Meetup participants violating these rules may be sanctioned or expelled from the meetup at the discretion of the meetup organizers.

## Value

To Educate people about the various aspects of the Blockchain and the several opportunities available in it and also provide a platform for corporate brands to connect with their users. 

## Deliverables

1. To organize a standard well attended Blockchain Festival in the city of Warri, Nigeria.
2. To scale up the CodeUp Blockchain Community to the level for pool staking & DAO.
3. To create a launchpad for effective take-off of the CodeUp Blockchain Academy.
4. To create a platform for investors to access projects for possible investments.
5. To give room for blockchain startup founders to pitch their projects for funding.
6. To mobilize resource persons to educate and enlighten members/participants.
7. To contribute to open source projects and encourage blockchain startups.
8.  To build 3 projects using the Filecoin protocols via the Hackathon.

## Total Budget Requested

We are requesting for a total grant of **24,600 USD**, below is the breakdown of how the fund will used.

1. Hackathon Prizes = 5000 USD
2. Publicity = 1000 USD
3. Venue = 1200 USD
4. Attendees Breakfast = 3000 USD
5. Attendees Lunch = 3000 USD
6. Speakers Flight = 6000 USD
7. Speakers Hotel = 1400 USD
8. Media Coverage = 1000 USD
9. Swags = 2500 USD
10. Miscellaneous = 500 USD

TOTAL = 24,600 USD

## Maintenance and Upgrade Plans

This is an annual festival and it holds once in a year. Thank you.

# Team

## Team Members

1. **Onose Oghenevwogaga**; is a blockchain community advocate and lead organizer of CodeUp Blockchain Festival.
2. **Fole Jabulani Ogheneovo**; is in charge of the festival website development.
3. **Sarah Abamba**; is a lover of the Blockchain technology, and love everything that has to do with it. She is in charge of research.
4. **Pere chiko-bada**; is intentional about goals setting and aim at achieving them... she is an orator and capable of hosting talk shows and writing mini script... she also do a bit of editing on the side occasionally. She is in charge of the event social media.
5.  **Oveto Alisha**; she is in charge of graphic designs
6. **Achor Ugochukwu**; is a web developer, graphic designer and blockchain lover, he is in charge of publicity.
7. **Victory Emueje**; he is a tech skill acquisition advocate and in charge of multi media coverage.
8. **Efiri Tamaradeinyefa**; he is a medical doctor, a team player and blockchain enthusiast. He is in charge of health and safety.
9. **Ejiroghene Adeniyi**; she is a startup co-founder and co-organizer of the CodeUp Blockchain Festival.

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/onose-ogaga/

## Previous Edition

You can have a view of photos taken from the last edition via the link https://bit.ly/CBF-NG-2021-Pic and watch the news media coverage via https://youtu.be/zizqslKdhEs and https://youtu.be/r-B8KF6SkT8

## Event url

https://www.meetup.com/codeup-africa/events/285323362/
https://codeup.africa/

**Comment by ErinOCon** [comment]
Hi @ogasky, thank you for your proposal! We will not be proceeding with this grant, but do recommend submitting a proposal for a [hackathon](https://hackathons.filecoin.io/).  You can check out more information [here](https://www.notion.so/ecosystem-wg/BETA-VERSION-IPFS-Filecoin-Hackathon-in-a-box-fb0bd92e0418466eb941328da87c288b)!
