### ISSUE TITLE
Next Step Microgrant: Wordle on the Block

### ISSUE THREAD

**Issue by gitfrosh** [filecoin-project/devgrants#746]
### 1. What is your project? (max 100 words)
Wordle on the Block is a word game, chiefly inspired by the original wordle game that was built by Josh Wardle. In this online game, the user is able to play a daily round of Wordle and has the chance to proudly mint their result (may it be good or bad) on the Ethereum blockchain as an NFT. During this process, the user is asked to donate a small amount of Ether to a charity of their choosing to help a great cause.

[Github](https://github.com/gitfrosh/maxima)
[Demo](https://wordle-on-the-block.on.fleek.co/)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
The game stores the image files of the Wordle gaming result and all of its metadata in a decentralized way using IPFS and Filecoin technologies. The specific provider we use for our game data is Fleek; also the project frontend based on React is hosted at Fleek as well.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
The project is currently in an early prototype state, there are several improvements planned:
- switching from deprecated Rinkeby testnet and deploying on Polygon 
- improving and debugging the overall game flow and securing it against unfair ways of playing
- enabling donation feature (currently mocked)
- conducting user tests and get feedback/reviews, derive enhancements for UI/UX
- implementing individual user's page and displaying their gaming history
- implementing a "hall of fame" and players' ranking
 
### 4. Is this project open source?
Yes, under MIT license.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
The project was first submitted by "Team Maxima" during [web3con Hackathon 2022](https://www.web3con.dev/2022-recap) and was rewarded as Filecoin & IPFS Prize Pool Bounty Winner.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

**Rike Exner**
E-Mail: hello@rike.dev
Github: [https://github.com/gitfrosh/](https://github.com/gitfrosh/)
Role: Full-stack dev

* How did you learn about our microgrant program?
We were contacted by a Developer Advocate.

* If your project was created as part of an event or hackathon:
What was the name of the event? [web3con Hackathon 2022](https://www.web3con.dev/2022-recap)
Please link to your hackathon submission: See the hackathons' recap link above.

**Comment by ErinOCon** [comment]
Hi @gitfrosh, this grant has been approved! We will send an email to confirm payment details.
