### ISSUE TITLE
Artozo x Filecoin integration

### ISSUE THREAD

**Issue by artozoproject** [filecoin-project/devgrants#748]
# Open Grant Proposal: Artozo

**Name of Project:** Artozo x Filecoin integration

**Proposal Category:**  app-dev
**Proposer:** artozoproject

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

The idea is to provide a convenient gateway for user interaction with Filecoin as a reliable storage provider (i.e., GDrive). It will be implemented as one of the web3 modules of the Artozo platform. 
It can be useful in various cases, including NFT storage, backing up user data, storing other filetypes, and shared access. We have several important features to offer: 

- File versioning. In most storage services, this is a paid feature with a limited number of versions. Our goal is to move user file storage from IPFS+Pinata to Filecoin. A step further to increase web3 convenience and adoption.
- Seamless storage access monetization for users. We will allow monetizing content that a user uploads to the Filecoin network. Once a file is uploaded, a user can create a public link which will require paying a small fee to access the data. When someone clicks such a link, we can authorize a transaction from the client’s Artozo-connected wallet and provide an option to pay in any supported crypto through our connected payment gateways. 
A customer then covers the Filecoin data access fee and the monetization fee set up by the file owner.
- Role-based file access model. File access can be set up for specific wallet addresses, with some basic roles to choose from: viewer, editor, administrator.

## Value

Artozo is an NFT marketplace that implements several unique features currently missing in the industry. We have a growing number of supporters and community members. Integrating Filecoin will provide an immediate boost to the Filecoin userbase. 

**Risks and solutions:**

1. Role-based access model: to implement some features (i.e., modifying or deleting files), a private key of a user’s wallet is needed. There is a quite complicated and less user-friendly solution, though: request a signature from the file owner when such modifications are needed to be made.  

2. Monetization: it is easy to reward the one who shared a file, but it gets more complicated when we need to get a payment from the one who accesses it. We will need either a third-party universal crypto payments gateway to accept multiple currencies or to create a custom payment solution with top crypto coins support, which is not a trivial task.

3. All files in the Filecoin network are inherently public. To ensure privacy, we need to encrypt files in a way that it’s only decryptable by the owner. The hard part is encrypting big files (i.e., a 1 TB video file) - it’s expensive and takes a lot of time. We need to come up with a solution to make it fast and reliable - for example, use cloud computing as a proxy. 

## Deliverables

A specialized cloud storage section in the Artozo dashboard for all users. It will most likely be a separate Artozo module, including a GDrive-inspired user interface with monetization and file versioning. 

## Development Roadmap

**Milestone 1**
**Goal:** Change the approach to storing files in the Artozo platform. 
**Description:** To provide the most secure and decentralized storage for user files (currently, it’s mostly various NFTs), we need to switch from the current “IPFS+Pinata” approach to storing everything in Filecoin.
**Timeline:** 1 month.

**Milestone 2**
**Goal:** Develop UI/UX and server-side parts for the GDrive-like approach to storing and monetizing data.
**Description:** Develop an MVP module for Artozo that will allow basic operations with your stored data, provide version control and monetization features.
**Timeline:** 2-3 months.

**Milestone 3**
**Goal:** Develop a role-based model for file access.
**Description:** Extend the Artozo Filecoin module with the role-based access model. Allow users to control the access and other rights for their files. 
**Timeline:** 2-3 months.
**Note:** Presently, there is no decentralized solution to allow certain file operations (i.e., deleting a file) for a third party. Our idea is to offer the users our management over their Filecoin data, basically to act as an intermediary. 

## Total Budget Requested

Milestone 1: $10,000
Milestone 2: $20,000
Milestone 3: $20,000
Total: $50,000

## Maintenance and Upgrade Plans

Artozo is currently nearing its MVP launch phase, in development for almost a year now. This is a platform to stay, and the Filecoin features to be implemented will be an important part of the platform. Just as with any other part of Artozo, Filecoin module will be continuously supported, maintained, and improved. 

# Team

## Team Members

Ilya Korzhenko
[LinkedIn](https://www.linkedin.com/in/nex22/
)
[GitHub](https://github.com/nex125)

Alexey Vinogradov
[LinkedIn](https://www.linkedin.com/in/%D0%B0%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9-%D0%B2%D0%B8%D0%BD%D0%BE%D0%B3%D1%80%D0%B0%D0%B4%D0%BE%D0%B2-56b024216/
)
[GitHub](https://github.com/alexx876)

Kostiantyn Kryvonos
[LinkedIn](https://www.linkedin.com/in/kostya-kryvonos-41061a170/)
[GitHub](https://github.com/KostyaKrivonos)

Denis Ignatik
[LinkedIn](https://www.linkedin.com/in/denis-ignatik)

## Team Website

https://artozo.com/

## Relevant Experience

Our team has been in the process of developing the Artozo platform for almost a year now. The combined skills include everything that might be needed for the Filecoin integration. 

# Additional Information
_How did you learn about the Open Grants Program?_
We are already using Filecoin-related technology (IPFS) in our project. We also follow all news from Filecoin.

_Please provide the best email address for discussing the grant agreement and general next steps._
[pk@artozo.com](mailto:pk@artozo.com)

_Please include any additional information that you think would be useful in helping us to evaluate your proposal._
Artozo project is all about transitioning the mainstream web2 users to the web3 technologies. We aim to get attention from the mass web2 users by implementing a wide range of great features, including dynamic APY NFT staking and, potentially, easy access to decentralized data storage with a convenient pricing model. 
Adding the Filecoin integration to the Artozo platform will increase the value of both projects.

**Comment by ErinOCon** [comment]
Hi @artozoproject, this grant has been approved! We will send an email to discuss next steps.
