### ISSUE TITLE
Nest Step Microgrant: Verify-Me

### ISSUE THREAD

**Issue by HubertXaver** [filecoin-project/devgrants#750]
### 1. What is your project? (max 100 words)
Authors, Developers, Designers and Artists have to battle IP theft. The legal battle can sometimes be difficult if the origin of a specific file, let it be text, code, article or image can not be proven. web3 technology is in a unique position to solve the problem of attribution in a case where a legal resolution is required. Our technology allows creators of all kinds to upload their files to our system and then at a later stage cryptographically verify that they are the owners of a specific file.

***How it's made***

We used web3auth's authentication module to allow our users to use decentralised wallets as well as non-custodial social auth based wallets.

First, the frontend generates a signature (signed hash of the file) which is used to deploy a smart contract. We do this so that potential bad actors listening to certain events can not take the file itself or the hash of the file in order to front-run our execution.

Each IP confirmation is a new smart contract (1-of-1 NFT) that is deployed by the browser/dApp.

After a confirmation of this hash, the web app uploads the file to IPFS and that generated hash is stored in the smart contract. 

At a later stage, the user can view all of their NFTs (ERC721 contracts) that match the Verify-Me's format. The user can verify their work, by uploading the specific file, which goes through the hashing and signing processes in order to validate the origin. If a user can not validate an artwork with their private key, the smartcontract rejects the interaction.
Furthermore we are deploying our smart contracts on Polygon.

https://github.com/HubertXaver/verify-me

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
We use IPFS and Filecoin for storing NFT data as well as storing the hash generated by the dApp
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. Community Building - We plan on growing a community of artists, etc. who can use our product to secure their IP's. For this, we have mapped all major NFT events happening, and are applying to promote our product there
2. Development Goals - We have roadmapped our product development on our Github. We plan to expand to multiple chains and help artists from various different ecosystems. For this, we have planned on 
    a. Deploying on all major EVM compatible chains (Phase - 1)
    b. Deploying on Solana, Polkadot and NEAR (Phase - 2)

### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
We agree to share the report
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:No
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Xaver Hubert - https://github.com/HubertXaver (xavhubert@tutanota.com) - Project Lead
Asander J - (asanderx@tutanota.com) - Lead Designer

* How did you learn about our microgrant program? Social Media
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @HubertXaver, this grant has been approved! We will reach out by email to confirm payment details.
