### ISSUE TITLE
Next Step Microgrant: creatMe

### ISSUE THREAD

**Issue by en0c-026** [filecoin-project/devgrants#752]
### 1. What is your project? (max 100 words)
creatMe is a web application focused on developers or creators who want to implement an NFT Collection on the Tezos blockchain without interacting with the code.
Through intuitive forms, you can upload your images, metadata files and create a new collection in just a few clicks.
The functionalities are:
- Create a new multi-asset contract (FA2_MultiAsset or ERC1155).
- Mint new tokens
- Batch minting via a JSON file
- Token transfer via form
- Transfer of tokens in batches via form
- Transfer of tokens through JSON file.
- Search a collection
- Search items in a collection.

[https://github.com/en0c-026/creatMe](https://github.com/en0c-026/creatMe)
[https://youtu.be/NC-Yn7R9PlE](https://youtu.be/NC-Yn7R9PlE)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
  This app uses the Pinata SDK that interfaces with the IPFS service.
Stores the metadata of the collection, the image and metadata of each item.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
The original idea that was presented for the Tezos WAC Hackathon is focused on cultural institutions that would hold an exhibition in a physical location using the NFT collection.

- Generalize the use of the application for other interfaces and networks.

- Support for Ethereum, BSC, Polygon and Zilliqa blockchain. Where creators can create and manage their ERC721 and ERC115 collections, in an intuitive way through forms.

- Login component with web3modal, support for multiple wallets like Metamask, WallectConnect.

- Add a Manage component where the owner or NFT Holder can interact with the contract. For example, depending on the role of the caller, you can: Pause, Unpause, setOwnership, setRole, transfer, burn, etc.

- Add the Show component, show the items of a collection given a wallet address.

- Prepare and launch the application to Production in a Vercel instance

- Buy and locate the application in the creat.me domain
 
### 4. Is this project open source?
Yes, the projecti has an [MIT License](https://github.com/en0c-026/creatMe/blob/master/LICENSE)

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes I agree. I will share the required reports and at the end, I will write the final report.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Lucas Daniel Jovanovich
Email: bitup.games@gmail.com
Github: [https://github.com/en0c-026](https://github.com/en0c-026)
Role: Developer Solo

* How did you learn about our microgrant program?
Through a gitcoin bounty, I entered the filecoin-project profile and found this repository!
* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
[WAC Hackathon](https://gitcoin.co/hackathon/WAC)
  * Please link to your hackathon submission
[https://gitcoin.co/hackathon/WAC/projects/15846/creatme](https://gitcoin.co/hackathon/WAC/projects/15846/creatme)

**Comment by ErinOCon** [comment]
Hi @en0c-026, this grant has been approved! We will send an email to confirm payment details.
