### ISSUE TITLE
RFP Application

### ISSUE THREAD

**Issue by DcentHosting** [filecoin-project/devgrants#753]
# RFP Proposal: SBPS 

**Name of Project:** SBPS (Solar & Battery-Powered Storage)

**Link to RFP:** 

**RFP Category:** `technical-design`, `docs` & `community`

**Proposer:** DcentHosting

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes

# Project Description

Since the Filecoin project started almost two years ago, a lot has changed in the world we live in. Things that were unthinkable just a few years ago have now become reality and the changes are happening at an ever increasing pace. 

Now we wonder how and where Storage Providers are in this current world climate. Since the war in Ukraine, Dcent has been committed to providing support by making our backup available to store sectors of storage providers in affected areas, so that they can achieve PoSt and focus on the things that really matter. 

However, not only the war has brought a lot of instability to the world; A shortage of gas due to tensions between Russia and Europe, a sky-high inflation due to the economic decisions made during the Corona period, and too few resources on European soil to solve extreme gas and electricity prices for a while. We are looking forward to long periods of uncertainty on our grid and continuity in various business operations.

We as Dcent would like to realize a solution for all Storage Providers who are facing an uncertain climate somewhere on our planet. We believe that every storage provider, regardless of size, should be able to operate, in extreme cases, almost to fully independently of the grid. This solution consists of a combination of:

- Solar panels
- Inverters
- Battery systems
- Specially developed APIs
- Tools for automatically optimizing efficiency of sealing/storage
- Grid balancing 
- Full usage transparency to engage with regulation/government 

By implementing this project, we will be able to show Storage Providers on a "per kWh" or "per TiB" basis how they can keep their operations running during times of uncertainty on the grid.

We focus on different aspects during our research. The two most important aspects are:

- Optimal efficient operation during periods of tariff peaks or grid instability.
- The requirements and steps to keep a Storage Provider operational during a complete lack of electricity from the grid.

This information is not only crucial for the current Storage Providers located in Europe, Asia or America. But also for those countries where the grid is less stable during daily operation. You could even argue that it is even more important for those Storage Providers to stay operational.

Trying to make the Filecoin network sustainable and stable in operation is one of the most important aspects for the future of this decentralized network. 

## Development Roadmap

We can divide our research into the following milestones:

1. Research into hardware and software possibilities
2. Ordering and installation of hardware
3. Implementation of software and comprehensive documentation/manual

**Research on hardware and software possibilities**

The type of hardware used is very essential. Storage providers are primarily focused on remaining stable and online in order to be available for clients, retrievals and PoSt. The hardware used for the solar array and battery systems must therefore be of high quality in order not to jeopardize the stability of the storage provider. 

Likewise, the software implementations between the grid, the solar panels and the battery system must be extremely secure. After all, we are talking about the power of the entire storage operation here. The focus here is on custom solutions per installation. We will also consult with experts on how best to implement the hardware installation on arrival.

**Ordering and installation of hardware**

After the findings of the preliminary investigation, we will order the desired systems. This will probably take a few weeks due to the global shortage in the shipping market, during which time we can already work on the development of the required APIs and software tools. Upon delivery, we immediately work together with certified electricians and construction workers to ensure that everything runs smoothly. 

**Implementation of software and full documentation/manual**

After the installation is completed and the basic systems are operational, we will continue to work on internal software solutions for a.o. the different inverters, future hourly power tariffs, estimated sealing consumption, solar panel yield day-ahead and smart limiting of consumption during peak hours. These systems will be accessible through a dashboard, so they can be discussed with customers and potential governments/municipalities who want to have insight into the limitation of large users during times of power shortage.

We will then document everything to perfection so that Storage Providers interested in renewability and stability in this uncertain period have the opportunity to do so in our footsteps.

## Documentation, Education, and Community

The documentation we feel is important to share will consist of a number of components from which:

- Calculation option (Each Storage Provider has a different model)
- Hardware information 
- Installation options
- ROI calculations
- API manuals

It is intended that Storage Providers can achieve the desired result without our intervention by implementing the manuals.

## Total Budget Requested

<img width="1412" alt="Timeline" src="https://user-images.githubusercontent.com/95493190/178349902-50960f86-d25a-4a9f-a088-e95d6275e6bf.png">

## Maintenance and Upgrade Plans
Live tracking of every data point within our data center is crucial to optimizing our energy consumption. During our previous solar installation in cooperation with Filecoin Green, we have already developed tools for this, which we use daily. These steps are extended by adding a battery system and will not only give us, but the entire community insight into the power consumption and generation of a Storage Provider.

In the future, both the solar installation and the battery system will be expanded as the Datacenter grows. All this is purely focused on Web3 and Filecoin.

Our long-term vision for this project consists of a number of components. Firstly, it is intended that the entire installation, both software and hardware, will be accessible via documentation or by visiting the datacenter. It must be clear to everyone what we have developed and implemented here so that interested parties can benefit from the installation as an example. As a facility, we want to offer quarterly or annual tours and give various interested parties from the community the opportunity to see for themselves what renewability can look like for a Storage Provider. 

Secondly, we want to focus on the importance of renewable energy for data centres and large-scale consumers. Not just purchasing RECs through a supplier but actually implementing in-house production and storage facilities. All this to set a proper example to the outside world of what the web of the future could look like.

# Team
Hidde Hoogland
Wijnand Schouten
Alan Ransil (Filecoin Green)

## Contact Info
hidde@dcent.nl
info@dcent.nl
alan@protocol.ai

## Team Members
https://www.linkedin.com/in/wijnand-schouten-764a6412/
https://www.linkedin.com/in/hidde-hoogland-a68b7b1a/
https://www.linkedin.com/in/alan-ransil-53573873/

## Team Website
http://www.dcent.nl

## Relevant Experience
The team behind Dcent Hosting B.V. has a lot of knowledge and experience in the two main areas of this application.
Hardware Efficiency & Solar.

Hidde has spent the last four years developing and maintaining one of the largest Dutch Ethereum farms. During this project his main goal is always to operate as efficiently as possible. Energy costs and heat were in fact the biggest enemies of the operation. Through these experiences he has a good view on maximising the efficiency of hardware and air conditioning.

Wijnand has spent most of his early life as an network engineer, maintaining the largest USP in the Netherlands while constructing and maintaining his own Datacenter in the middle of Amsterdam. After that business was sold he founded his own Solar company, which is now maintained by his Family due to being occupied full-time as a Filecoin storage provider. There is no one around with more knowledge on renewables and solar installations than he has.

Currently Hidde and Wijnand are maintaining the DCENT data center and are continuously working on new software tools and hardware expansion. They are focussed on running the most efficient web3/Filecoin datacenter in Europe.

## Team code repositories
https://github.com/cryptowhizzard

# Additional Information
If anyone has any questions about our proposal please reach out to me through this issue or by sending an email to info@dcent.nl.

**Comment by DcentHosting** [comment]
Updated version:

We have been working together with the Filecoin Green team on ways of making this grant possible. We have decided to exclude the solar installation and move that towards a direct bank-loan to facilitate the investment. We have also deducted costs of implementation to the Dcent datacenter. Finally we updated the battery size to the 250kWh model.

Please take a look at the newly drafted costs and timeline:
<img width="1733" alt="Screenshot 2022-09-09 at 08 40 54" src="https://user-images.githubusercontent.com/95493190/189287451-a909ba37-ccb7-4b8b-a085-e2f833b6c3c3.png">
*Note that research has already begun

**Comment by redransil** [comment]
Thanks for the edits @DcentHosting and clarifying that the Grant amount = Project Total = $200k

**Comment by realChainLife** [comment]
Hi @DcentHosting we're happy to approve funding for the reworked proposals. Please emails grants@filecoin.org so we can kick-off next steps.

**Comment by ErinOCon** [comment]
Hi @DcentHosting, since the project work is now complete, I have closed this issue. Please contact our team at grants@fil.org with any updates or questions.
