### ISSUE TITLE
Next Step Microgrant :- InsureFinance

### ISSUE THREAD

**Issue by InsureFinance** [filecoin-project/devgrants#754]
### 1. What is your project? (max 100 words)
InsuranceFinance is a car insurance decentralized application that solves the traditional issue of not getting quotes instantly and not getting claims instantly

A decentralized solution to car insurance difficulty which includes getting quotes instantly, filing claims and getting payout instantly. Traditional car insurance companies due to the factors of high competition environment, clients do not have value for their money and data can be compromised.

What InsureFi tends to do is to make car insurance data tamper proof, faster and eliminate the middle men while getting value for the premium paid.

This project was written in Solidity and deployed to the Polygon testnet. The frontend has the web3 modal integration allowing for Rainbow, Metamask, Wallet Connect and Coinbase integrations. Superfluid for money streaming which streams the monthly insurance premium from users to the insurance company and IPFS which allows for image storage when filing claims.

https://github.com/InsureFinance

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
IPFS is used as the underlying technology to store images and other related data of claims
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. Introducing other types of decentralized insurances, including weather, property, bite-sized and trade insurances and smart contracts for each type
2. Expanding to AVAX, Solana and Dot ecosystems with the car insurance product (We are live on Polygon Testnet)
3. Mobile DApp development for adhoc insurance claim
4. Partnerships with Crypto lending institutes to add liquidity to the platform
 
### 4. Is this project open source?
Yes - MIT

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes Will do
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: Web3 Hackathon, UOB, Bahrain
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Ali Hamza - [GitHub](https://github.com/InsureFinance) - Chief Technical Officer
Muaaz Khan - [GitHub](https://github.com/KhannDev) - UI / Business Development / Prior Experience in motor insurance
Email - insurancefinancedefi@gmail.com
* How did you learn about our microgrant program? Social Media
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission - https://youtu.be/6MZpwI6RNzk

**Comment by ErinOCon** [comment]
Hi @InsureFinance, this grant has been approved! We will send an email to confirm payment details.
