### ISSUE TITLE
Primis-Web3 Desktop-Open Grant Application

### ISSUE THREAD

**Issue by Andy-Meta** [filecoin-project/devgrants#756]
# Open Grant Proposal: `Primis`

**Name of Project:** Primis

**Proposal Category:** `app-dev`

**Proposer:** `Andy-Meta`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:**  "Yes" 

# Project Description

Primis redefines the **Web3 Desktop** world.

In here, a basic Web3 explorer will be provided. Primis integrates all Dapps in the Web 3 world and interacts Dapps with blockchains through a simple operation interface.

Compared to hosting Dapps on the traditional Web 2.0 cloud server, now Dapps can be directly installed on nodes through a plug-in. Primis provides decentralized network services and multi-chain adaptation. Smart contracts record access point information and offer a self-updating, security, and fast method to upgrade services.

Primis was born with the Web3 wallet, and it created a privacy-encrypted Web3 ‘Discord’ by integrating P2P communication protocols and Zero-Knowledge Proof. Unlike the traditional Web2 chatting method, Primis provides secure privacy interaction, communication, community DAO governance, and voting through multi-channels, blogs, and open forums.
***

### *Primis Wallet*

Basic functions like managing Web3 wallet assets, showing NFT assets data, and offering other Dapp assets information. Primis Wallet also supports managing fortress assets based on ZK privacy technology.

### *P2P Communication Protocol*

The protocol supports Primis users to start P2P encrypted chats and create P2P encrypted group chats.

### *Primis Web3 Node Explorer*

Users can freely surf in the Web2/Web3 world through Explorer, which is kernel compatible with Chrome. Also, a multi-page plug-in page function is provided.

### *Dapp Docking*

A plug-in function is available in Primis, and all Dapps can be integrated into Primis.

Upgrade and confirm Dapps through the reliable link in the smart contract to ensure applications’ security.

## Value
Primis, as the first web3 desktop, will bring the brand-new web3  desktop concept to the Filecoin community.
And more, Primis will utilize Filecoin as the decentralized storage layer and interact Filecoin system with other ecosystems to attract more web3 users using Filecoin system.

## Deliverables

Primis will provide the web3 desktop client for the Filecoin community. And all deliverables are as follows.
### *1. P2P Encrypted Chats and P2P Encrypted Group Chats*

The conversation will be encrypted using Primis Client for P2P encrypted chats or P2P encrypted group chats. Primis users own right to have safe and private social lives.

### *2. Multi-channels Privacy Forum*

Primis provides the ‘Private Forum’ and ‘ Public Forums’ channels. The ‘ Private Forum’ provides communication and interaction areas for individuals, groups, organizations, and institutions. ‘Public Forum’ channel allows Primis users to discuss Proposals and vote publicly.

Forums support composing and submitting proposals, liking posts, and creating P2P Encrypted Chats or P2P Encrypted Group Chats.

Primis Forums supports plaintext or ciphertext privacy posts, and a plug-in off-chain DAO voting application can be embedded into the Forum channel. ZK Proof technology supports anonymous DAO voting to meet the privacy of DAO off-chain voting.

### *3. Primis - Off-Chain DAO Governance Tool*

The off-chain DAO governance tool is a DApp application that comes with the Primis hosting platform. It supports community DAO governance in ‘Privacy Forum’ multi-channels and provides more economical and efficient community DAO governance. Also, ZK Proof technology supports anonymous DAO voting to meet the privacy of DAO off-chain voting.

### *4. Web3 Node Explorer*

Web3 node Explorer provides a window for Primis Client users. Primis Client users can realize a multitude of interconnected Web3 Dapp services that are not isolated by exclusive or centralized technologies through this window. Also, Primis Client users can still access traditional Web2 data without interruption.

### Milestone1 (2 weeks, $5000)

Node Explorer

Native Wallet

Dapp Hosting Platform

### Milestone2 (4 weeks, $5000)

Compatible with multi-public chains

### Milestone3 (4 weeks, $5000)

Desocial Network - Multi Channels Privacy Forums

### Milestone4 (2 weeks, $5000)

Compatible with Dex, Defi Protocols & Applications

## Total Budget Requested

20,000 USD

## Maintenance and Upgrade Plans

 Primis Team will keep maintaining the development of web3 desktop client and finish on time according to the milestones.

# Team
Primis team has rich experience in the fields of the public chain, infrastructure, and defi. More details would be released after reviewing.

## Team Website

primis.cc

## Team code repositories

[Primis Github](https://github.com/Primis-Labs/client)
# Additional Information
Learn about the Open Grants Program From Filecoin official website
Primis Email: (contact@primis.cc)

**Comment by ErinOCon** [comment]
HI @Andy-Meta, thank you for your proposal! Can you provide a technical overview of the core components of this project and the architecture of the platform? For example, how will the platform function as a multi-chain dapp development platform/explorer? Additional information regarding the target audience for this platform would also be helpful!

**Comment by Andy-Meta** [comment]
> HI @Andy-Meta, thank you for your proposal! Can you provide a technical overview of the core components of this project and the architecture of the platform? For example, how will the platform function as a multi-chain dapp development platform/explorer? Additional information regarding the target audience for this platform would also be helpful!


> HI @Andy-Meta, thank you for your proposal! Can you provide a technical overview of the core components of this project and the architecture of the platform? For example, how will the platform function as a multi-chain dapp development platform/explorer? Additional information regarding the target audience for this platform would also be helpful!

Hi @ErinOCon , we will update our proposal regarding what you mentioned, and make more technical details & solutions customized to the filecoin system.

**Comment by Andy-Meta** [comment]
> HI @Andy-Meta, thank you for your proposal! Can you provide a technical overview of the core components of this project and the architecture of the platform? For example, how will the platform function as a multi-chain dapp development platform/explorer? Additional information regarding the target audience for this platform would also be helpful!

Hi @ErinOCon  , we will update our proposal regarding what you mentioned, and make more technical details & solutions customized to the filecoin system.

**Comment by ErinOCon** [comment]
Hi @Andy-Meta, I hope you are doing well! Can you confirm when an update will be available?

**Comment by Andy-Meta** [comment]
> Can

**Comment by Andy-Meta** [comment]
> Hi @Andy-Meta, I hope you are doing well! Can you confirm when an update will be available?

@ErinOCon hi, Erin, we have talked about some customed features for filecoin system eco recently, I will update the contents here by 18th August.

**Comment by ErinOCon** [comment]
Thanks, @Andy-Meta!

**Comment by Andy-Meta** [comment]
> Thanks, @Andy-Meta!

@ErinOCon  Hi, Erin, I have updated our grant file. We added technical descriptions and architectural diagrams and made executable milestones for our team. You can check it out again when you are available. Any other requests, please let us know asap.

**Comment by ErinOCon** [comment]
Hi @Andy-Meta, thank you for the provided updates! This grant has been approved. We will send an email to discuss next steps.

**Comment by Andy-Meta** [comment]
> 

@ErinOCon   sir, could you check your junk email, especially [contact@primis.cc]? we have replied to your email, but you continue to ask for our confirmation info.  I'll paste the email info here to let you know our reply asap.                                      
Hi Erin 

We have confirmed the content of OSA draft and finished the OSA review inside, and we think there're no problems with your OSA draft. For the information requested that we need to provide, please check out this link, we have updated it.  https://docs.google.com/document/d/1ACdzpRUbhMahhI0UY5SZitIxdyw-E0oI/edit?usp=sharing&ouid=115508155792506299686&rtpof=true&sd=true

If there's any other info we should provide, please let us know. We'll provide it immediately.

Best,
Andy From Primis Team

**Comment by ErinOCon** [comment]
HI @Andy-Meta, thank you for reaching out on this thread. It looks like your email was landing in our spam folder. We will send the final version of the contract out for signature via DocuSign.

**Comment by ErinOCon** [comment]
Hi @Andy-Meta, I just sent a new email to your team. It looks like the contract is missing some information. Please be in touch if you have any questions.

**Comment by ErinOCon** [comment]
Hi @Andy-Meta, do you think the final details of the contract can be completed this week?

**Comment by ErinOCon** [comment]
Hi @Andy-Meta, I hope you are doing well. Please let me know if a different email address is preferred.

**Comment by ErinOCon** [comment]
Hi @Andy-Meta, thank you for providing our team with an update. This grant has been cancelled.
