### ISSUE TITLE
Open Grant Proposal : Coinhook

### ISSUE THREAD

**Issue by pash161** [filecoin-project/devgrants#757]
**Name of Project:**
Coinhook

**Proposal Category:**  

`integration-adoption` 
**Proposer:** 
`coinhook`

**(Optional) Technical Sponsor:** 
`NA`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** "Yes"

# Project Description
We are building a platform to facilitate DAOs with easy user onboarding, member networking, and easy governance integration with Snapshot.

Problem: The onboarding funnel for any contributor is very leaky with information scattered around forums, governance portals, discord. That is why more than 70% of new contributors drop off after joining Discord.

Solution: 
1. Fully customizable DAO onboarding templates with clear actionable steps for new contributors.
2. Single page to stay updated with all the important information and action items for a contributor.
3. Members directory to form new connections and know who else is contributing.

##Value
We are currently using Web3Storage to upload all of our NFT resources to IPFS.

We have a lot of data about communities/DAOs (members name, tags, twitter, discord etc.) that are being stored on mongodb and aws s3, which we are planning to move to IPFS for a more distributed architecture. Doing so will make our approach to DAOs and communities more decentralized and easy for clients to never lose their data.

Since we will have a requirement to update and maintain the data on IPFS, we will create a library which can easily read/cache, write/update data to the IPFS resource.

If we get this right and able to solve the DAO onboarding, then these communities can easily attract and hire the right talent to do work. Members can engage with other community members to initiate new workstreams.

Riskes if we don't get this right would be that we end up building onboarding framework that is not composable and can only we used by one specific category of DAOs (Service DAOs). But even in this case we feel that market of service DAOs in futures would be huge and the product will still add value to a subset of bigger DAO market category. 

Riskes that will make executing on this project difficult are:
1. Mapping out common onboarding patterns accros multiple DAOs.
2. There is not enough people in the market who are interested to join New DAOs. 

## Deliverables

Present state of Project:
1. Can create communities on the platform. Ability to create gnosis safe, connect safe snap module and reality module to snapshot voting space. Community owner can also link the existing snapshot space to create a custom voting experience.
2. Distribute NFT based memberships and token gate various online & IRL events.

Deliverable after the funding:
1. Create more onboarding templates for the different DAO categories.
2. Allow ability to distribute membership based off of discord roles, POAPs and whitlisting.
3. Create on chain reputation vaults to enable contributor to prove various proofs of work or membership in order to redeem additional benefits like better compensation, more voting power etc.

## Development Roadmap

Aug 2022- Oct 2022

Milestone: Onboard 200 communities to Coinhook platform.

Software functionality:
1. Develop new onboarding templates for each DAO category.
2. Add more social feed features like: double opt-in connection, kudos, discord integration etc.
3. Launch on gnosis chain and Polygon.

Resources: 1 front end engineer, 1 solidity engineer, 1 full stack developer, 1 business development associate
Funding amount requested: $36,000

Nov 2022 - Jan 2023

Milestone: Introduce reputation valuts and custom governance logic on layer 2.

Software functionality:
1. Create reputation valuts for contributors which are gnosis on chain smart contract wallet used for providing claims of various work done in communities.
2. Allow communities to create custom voting mechanism which can input votes from any platform (discord, telegram, etc.) and can automatically trigger transaction from the safe.

Resources:
Funding requested: 1 front end engineer, 2 solidity engineer, 1 full stack developer 
Funding amount Requested: $42,000

## Total Budget Requested

Total funding requested: $78,000

For milestone 1, the funding amount of $36,000 will be used to pay salaries.
1 front end engineer ($2000 per month) * 3 months = $6,000
1 solidity engineer ( $4000 per month) * 3 months = $12,000
1 full stack engineer ( $4000 per month) * 3 months = $12,000
1 business development associate ( $2000 per month) * 3 months = $6,000

For milestone 2, the funding amount of $42,000 will be used to pay salaries
1 front end engineer ($2000 per month) * 3 months = $6,000
2 solidity engineer ( $4000 per month) * 3 months * 2 = $24,000
1 full stack engineer ( $4000 per month) *3 months = $12,000

## Maintenance and Upgrade Plans

Team's long term vision is to raise funding and continue to building this open source infrastructure for DAO contributor onboarding.

# Team

Presently there is a team of 4 members building the product. 2 full time and 2 part time contractors.

## Team Members

[[Prashant Sharma](https://www.linkedin.com/in/prashant-sharma-a3050171/)](https://www.linkedin.com/in/prashant-sharma-a3050171/) (Founder & CEO)(2x Founder): 

- Lead DAO strategy and growth for [[Tachyon](https://twitter.com/TachyonAccel)](https://twitter.com/TachyonAccel) ([[ConsensysMesh](https://twitter.com/ConsenSysMesh)](https://twitter.com/ConsenSysMesh)) as Associate Program Director.
- Worked at [[Polygon](https://twitter.com/0xPolygon)](https://twitter.com/0xPolygon) as Blockchain Growth Specialist (early team less than 15)

[[Nischit Prasad](https://www.linkedin.com/in/nischitpra/)](https://www.linkedin.com/in/nischitpra/) (CTO) (Full-stack & web3): 

- Worked as a CTO for a stockbrokerage firm called JF securities.
- Previously worked at Coinmax, a derivative exchange for crypto.

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/prashant-sharma-a3050171/
https://www.linkedin.com/in/nischitpra/

## Team Website

--> https://coinhook.xyz/

## Relevant Experience

Prashant Sharma:

I have worked at Polygon as growth specialist where i have worked closely with NFT communities and how they want to give membership benefits to contributors with NFT's.
I have also lead the DAO strategy at Tachyon to conceptulise the overall mechanism to structure a investment DAO and distribute value to it's participating stakeholders.

## Team code repositories
https://github.com/orgs/coinhook/repositories

# Additional Information
Got to know about the grants from Lukas (Ecosystem Growth).

**Comment by ErinOCon** [comment]
HI @pash161, this grant has been approved! To proceed, please email our team at grants@filecoin.org to discuss next steps.

**Comment by ErinOCon** [comment]
Hi @pash161, can you provide an email address to proceed with next steps?

**Comment by pash161** [comment]
Hey @ErinOCon 
Here is my email id: pash161@gmail.com

**Comment by ErinOCon** [comment]
Thanks, @pash161!

**Comment by pash161** [comment]
Dear Team,

Following my recent discussion with Stefan, I am sharing an update on our project and kindly requesting reimbursement for the first milestone funding amount. It was approved previously but then things stopped. 

In the meantime, we kept building and testing. 

Over the past nine months, we have built relationships with more than 25 DAOs in the field. Three months ago, we pivoted our startup's focus towards Web3 identities. After conducting numerous interviews with DAO operators and contributors, we concluded that contributor data is crucial for unlocking various identity use cases in Web3.

Mercle: Identity and Reward Infrastructure for Network States

Technical Implementation:

User profiles consist of two components:

![Community rewards (1)](https://user-images.githubusercontent.com/18010465/235370418-daee98e2-9794-48d4-8356-0e993d885e55.png)

1. User Actions / Identity: Decentralized, off-chain identities are maintained and verified while still enabling on-chain use cases through NFTs. Identities comprise validated user actions from various platforms, with ownership at the user level. Initially, claims will be issued by verified credential providers, eventually transitioning to community admin level for decentralized issuance and attestation, similar to real-life processes. Each user will also have a community-level identifier.

2. Rewards Profile: This represents the rewards earned through work in the ecosystem, symbolized by an NFT. The NFT can be tradable or non-tradable, depending on the desired membership and reward ownership structure. This token is acquired through community contributions.

This approach combines the advantages of verifiable credentials and NFT infrastructure, providing a reliable and flexible identity solution.

For further technical details, please visit: https://mercle.notion.site/Mercle-ba7e45089bc5418d8193e098fa190847

Progress:

We are working with some great projects, such as ShapeShift and Polygon, for our beta launch next month. ShapeShift is integrating our API into their native interface, while Polygon will utilize Mercle for their music festival campaign. We anticipate issuing 40,000 identity tokens through these campaigns, given the existing distribution and community reach of these platforms.

Alignment with FIL Ecosystem:

All identity and reward data is currently stored on IPFS.

New Development Roadmap:

January 2023 - April 2023

Milestone: Issue 40,000 identity NFTs to contributors.

Software functionality:

Fully functional onboarding module with minting filter by email, wallet addresses, and Discord.
Complete infrastructure for storing identities and rewards.
Gas-less integration for improved UX.
Polygon launch.
Resources: 1 front-end engineer, 1 solidity engineer, 1 full-stack developer, 1 marketing associate
Funding amount requested: $36,000

July 2023 - October 2023

Milestone: Issue 150,000+ identity NFTs.

Software functionality:

Create a smart contract wallet for each user, functioning as an on-chain wallet of identities managed by various key pairs.
Develop a governance use case, enabling communities to issue identity tokens that grant additional voting powers to holders.
Resources: 1 front-end engineer, 2 solidity engineers, 1 full-stack developer
Funding amount requested: $42,000

**Comment by pash161** [comment]
cc: @ErinOCon
