### ISSUE TITLE
Next Step Microgrant: Yubiai

### ISSUE THREAD

**Issue by bpieres** [filecoin-project/devgrants#759]
### 1. What is your project? (max 100 words)
Yubiai it´s a Decentralized Marketplace (D-commerce) in Web3, focused on protect customers of scams. We added a two security layers to be ensure that buyers and sellers are fully protected by Kleros Escrow and Dispute resolver. In first phase we add an extra security layer, using Proof of Humanity protocol, to guarantee both parts are validated real humans.

https://github.com/yubiai
https://app.yubiai.market

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
We want to use Filecoin to store all images of our users.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We want to change our centralized  DB to decentralized image storage.
 
### 4. Is this project open source?
Yes, it's an open source project.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, we are agree to share with you a report.
  
### 6. Does your proposal comply with our Community Code of Conduct?
YES!

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* https://linktr.ee/yubiai
  
### Additional questions:

Team
--
Ignacio Britos - CEO Entrepreneur by nature, I’ve been involved in technologies all my life, and I’m currently the lead developer/designer for the Proof Of Humanity Marketplace, with 7 years of experience managing teams, knowledgeable in Javascript, Python and solidity.
https://www.linkedin.com/in/ignacio-britos-7939978a/
 
Benjamin Pieres - CTO 10 years of experience in software development and 8 years managing development and designers teams.
https://www.linkedin.com/in/benjapieres/
 
David Rivero - Solidity and Fullstack Dev Fullstack developer with 5 years of experience in frontend architecture, Javascript and Python technologies. Curious by nature, I like to contribute my knowledge and ideas to new places, achieving past awards from hackathons in my city or working in public projects with other professionals.
https://www.linkedin.com/in/davidriveroalegre/
 
Leandro Venezia - Full Stack Backend Dev
Full Stack Web Developer. My base language is JavaScript, which I extend with various technologies. His main Stack is MERN (MongoDB, Express JS, React JS and Node JS) also has experience using Next.js, Angular, TypeScript and different CSS Frameworks
https://www.linkedin.com/in/leandrovenezia/

* How did you learn about our microgrant program?
In filecoin website

**Comment by ErinOCon** [comment]
Hi @bpieres, this grant is approved! We will send an email to confirm payment details.
