### ISSUE TITLE
Next Step Microgrant: Innercore Engine Web3

### ISSUE THREAD

**Issue by innercoredev** [filecoin-project/devgrants#760]
### 1. What is your project? (max 100 words)
Innercore Engine Web3 compiles blog page created by user into JSON data and deploys it to IPFS via Web3.storage and undergoes additional pinning via Pinata. The blog page CID can be used to render the JSON-formatted blog page with the specially-designed Render Machine.

https://github.com/innercoredev/innercore
https://innercore.dev

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Project is powered by web3.storage and IPFS. User inputs are saved to and fetched from IPFS using web3.storage
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
More dev time, Support for more user inputs.
Make UI updates and several optional renderings methodologies and combination's thereof.
Promotion to get more users to adopt blogs to Innercore Engine Web3!
 
### 4. Is this project open source?
Yes, MIT open source, repository will be fully updated.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* No.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Gerard Rutte, info@innercore.dev  Dev Solo
* How did you learn about our microgrant program?
* Twitter

**Comment by ErinOCon** [comment]
Hi @innercoredev, this grant has been approved! We will send an email to confirm payment details.
