### ISSUE TITLE
Next Step Microgrant : DPhotoAlbum

### ISSUE THREAD

**Issue by ZhangPeibin** [filecoin-project/devgrants#761]
### 1. What is your project? (max 100 words)
DPhotoAlbum started when we wanted to make a decentralized photo album (decentralized Google Photos?) to store our personal photos safely and stably. We use web3.storage in the project to save photos (will guide users to web3 .storage application key). At the same time, Pinata's ping service will also be provided to increase security.
The project has just been launched, ready to participate in the next HackFs IPFS/Filecoin competition.Hope to get this grant so I can hire technical staff to continue developing this project

https://github.com/ZhangPeibin/DPhotoAlbum

https://dp-hoto-album.vercel.app/
### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
  We will use web3.storage to save the user's photo album, and use other third-party ping services to increase the security and stability of the data.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Through this grant, the DPhotoAlbum team will be formed, and eventually the project will be iteratively optimized to make it a web3 album.
we will use https://developer.litprotocol.com/docs/SDK/authSig to sign user data.

This project originated when Google Photos was not enough and wanted more reliable and decentralized free apps. Very much hope that PL can fund me to complete this project. Users love it, at least I'm more than happy to put all my photos on it when the project is done
 
### 4. Is this project open source?
yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes

### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  peibin,  web3 ecological builder, web3 ecological researcher, IPFS/Filecoin ecological contributor ， wiki4zhang@gmail.com , https://github.com/ZhangPeibin
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ZhangPeibin** [comment]
> Hi @ErinOCon , Update RoadMap :
> 
> 1. Complete the storage of access to web3.storage （2 week）
> 2. Add file encryption function （1 week）
> 3. Overall web optimization（2 week）

Updata progress:
1: add metamask login
2: use textile/hub to create user identity (to link user all files)

**Comment by ErinOCon** [comment]
Hi @ZhangPeibin, thank you for your proposal! Can you provide a more extensive roadmap of the work that will be completed over the next three months?

**Comment by ZhangPeibin** [comment]
> Hi @ZhangPeibin, thank you for your proposal! Can you provide a more extensive roadmap of the work that will be completed over the next three months?

Hi @ErinOCon . here is a roadmap (I divided the next 3 months into 3 milestones by month ):
### Milestones 1 

1. Improve user picture index system (personal picture index)
2. Write a picture browsing page
3. Add image upload function （use web3.storage to save image）
4. Add NFT Image upload function (use nft.storage to save image and mint nft)

### Milestones 2

1. Write picture contract to allow user minting their picture to nft 
2. Complete the contract-based image indexing system
3. Add file encryption function 
4. Add magic login function, link magic and user's IPFS/Filecoin data

### Milestones 3
1. Optimize the interactive page of the album
2. Testing encrypted and non-encrypted uploads
3. Test the contract for minting nft
5. Testing a contract-based file indexing system
6. Detailed structural documentation to introduce the complete decentralization process of the project


Hope to hear from you soon, thanks

**Comment by ErinOCon** [comment]
Hi @ZhangPeibin, thank you for your proposal! This grant has been approved. We will send an email to confirm payment details.
