### ISSUE TITLE
Chanson Studio – FileCoin Powered Music NFT DApp

### ISSUE THREAD

**Issue by ChansonStudio** [filecoin-project/devgrants#762]
# Open Grant Proposal: `Chanson Studio – FileCoin Powered Music NFT DApp`

**Name of Project: Chanson Studio

**Proposal Category:** `app-dev`

**Proposer:** `ChansonStudio`

**(Optional) Technical Sponsor:** `jenks@fil.org`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** `Yes`

# Project Description

Chanson Studio is a Decentralised NFT online platform to promote, capture and propagate music inspirations. Chanson is powered by FileCoin to store and retrieve music created by both established or aspiring artists. 

Chanson has an innovative feature whereby music creators can mint NFTs for any musical works they created whether it is a full solo piece or just an unfinished melody. Other creators can then build on these musical components to create more music while the original creators get paid through their NFT copyright.

Chanson aims to reward music creators fairly and encourage more creation and innovations in the music industry through our platform.

Chanson is not just an NFT marketplace, it is a project in the creator economy. We want to create together with the artists an ecosystem that redefines the rules of the game and that brings value to artists and fans. Our goal is to help musicians spreading their creations all over the world.

We have a vision for decentralised content streaming (both music and video) achieved through the power of Web3 technologies and enhanced by the fully decentralised storage networks from FileCoin. Chanson Studio has also planned a decentralized peer-to-peer streaming that allows users to earn cryptocurrency while watching the streaming video (Watch & Earn).

## Value

1.	Our app allows music artists to store their creations on FileCoin network & IPFS with the help of NFT.storage
2.	Each stored creation forms an immutable record, the CID of the record along with other metadata are then minted as an NFT on blockchain for digital ownership and ease of transfer.
3.	Chanson provides an easy way for any music creators to mint NFTs to capture every inspiration and allow it to develop and evolve into a variety of different and unique tones. Each one of such NFT can be seen as a building block that can fork itself or merge with another block to produce a new block. This will effectively facilitate the formation of new music pieces.

# Incentive For Both Content Creators And Consumers
Chanson pays both music creators and consumers through Chanson token. Consumers can get rewarded simply by listening to sponsored and curated music from both Chanson, and from other artists who wants to reach more fans and listeners with their music.

Musicians get compensated through royalty payments for each listen as well as through selling/trading of their NFTs for their creations.

# The risks if we don't get it right:

Missing incentives for musical inspirations and creation of new musical assets result in a less vibrant creator economy. 

Fake ownership of music creation, if not stored on Filecoin/IPFS it is hard to provide uniqueness of the music content therefore hard to prove genuine ownership and therefore miss the reward to the original creator.  

# Risks likely to make project execution difficult:

Building the right mechanism design to incentivise participants – from creators to users to community participants.
Integration with blockchain and IPFS/Filecoin to provide a smooth upload, creation and trading experience. 

## Deliverables

Chanson Studio will deliver a web user frontend to allow users/artists to:

-	Login
-	Upload creation to the Filecoin network or manage their music assets
-	Mint NFTs
-	Trade NFTs

We will leverage the free NFT.storage from FileCoin but at the same time we plan to use tools and APIs/SDKs provided by filedrive platform to store the music assets which provides nice abstraction for the complexity from users about IPFS/FileCoin.

# Content Creator user journey:
1. Go to Chanson website and register for an account or login as a registered user.
2. Connect crypto wallet that to the Chanson web application, ensure there are sufficient funds in the wallet that can pay for the NFT mint cost.
3. Fill in content metadata and upload contents to IPFS/FileCoin storage to store and prepare for mint process.
4. Commit to mint NFT for the content that was uploaded.
5. Mint cost (transaction fee) is charged from the seller’s wallet account and the content corresponding NFT is created and commit to the chain via smart contracts.
6. Creator can then mark their items as visible allowing the item to be available for co-creation or trading.
7. When an item is sold successfully, the smart contract sends the purchasing price amount to creator’s account.

# Content Consumer user journey:
1. Go to Chanson website and register for an account or login for a registered user.
2. Connect crypto wallet that to the Chanson web application, ensure there are sufficient funds in the wallet that can pay for the metaverse content assets one would like to buy.
3. Browse Chanson content marketplace to shop for desired contents which are placed on the marketplace by the creators.
4. Select an item to buy (opt-in to a smart contract)
5. The smart contract account sends the asset to buyer, and the buyers account is charged by the amount of listed for such content item.

## Development Roadmap

Architecture: 
![Music_NFT(1) drawio(1)](https://user-images.githubusercontent.com/47976069/178956915-2847570f-7822-4436-8a4e-e855a3eef148.png)

# Milestone 1 - INFRASTRUCTURE SETUP, WEB FRONT-END UI DEVELOPMENT:
-	Design and complete AWS web server & application server hosting infrastructure setup. A web hosting solution is required for our webapp which then will be fully integrated with blockchain and FileCoin platform.
-	The web server infrastructure will be hosting our web application
-	The application server infrastructure will be hosting smart contract and storage operation application.
-	Set up front-end web portal home page and user interface.
-	duration: 1 month

# Milestone 2 - COMPLETE CRYPTO WALLET INTEGRATION, FILECOIN STORAGE INTEGRATION:
-	Complete crypto wallet integration with web app so that user can connect their wallet with the web application.
-	Complete Filecoin storage integration (NFT.Storage + Filedrive) to allow uploading digital assets via web portal.
-      UI & UX enhancement on music NFT creation path and user interfaces.
-	duration: 1 month

## Total Budget Requested
USD$50,000

| Budget Table        | Milestone 1 | Milestone 2 |
|---------------------|-------------|-------------|
| Graphic Designer    | USD$9,000   | USD$9,000   |
| Front End Dev       | USD$15,000  | USD$15,000  |
| Cloud Platform Cost | USD$1,000   | USD$1,000   |
|                     |             |             |
| Total               |             | USD$50,000  |

## Maintenance and Upgrade Plans

We will have dedicated Ops team running the platform daily. The platform will be running 24/7.

Upgrade will be planned regularly with a new feature release every 3 months and major release every 6 months.

# Team

## Team Members
Jack Hui – Founder and Tech Lead
Linda Chew – Blockchain Developer
Benjamin Russell – Front End Developer
Graphic Designer - TBA
Tester - TBA

## Team Member LinkedIn Profiles
https://www.linkedin.com/in/jackhui88/
https://www.linkedin.com/in/linda-chew-b8b578243/
https://www.linkedin.com/in/benjamin-russell-856392245/

## Team Website

[https://chansonstudio.xyz/](https://chansonstudio.xyz/)
[https://chaining.com.au/](https://chaining.com.au/)

## Relevant Experience

Jack Hui
A very passionate and experienced technologist who enjoys designing and implementing elegant designs that help achieve strategic business and human objectives. Practical knowledge in software development best practices and excellent communication skills. Hands on experiences in developing web-based applications and experiences with solidity, NFT's and other cryptocurrency technologies. Experiences in building micro services-oriented blockchain infrastructure and nodes.

Linda Chew
Linda has a strong passion for learning and is fascinated with disruptive technologies, particularly blockchain and genetic technologies. Linda has experience in both blockchain development and entertainment and media, music industry. Her unique combination of skills allows her to bring strong technical competencies, engaging communication and the accuracy required to produce secure code in the entertainment and media space.
Her initial interest in blockchain technology and cryptocurrency quickly compounded into a passion resulting her to pursue further study of blockchain technologies and programming, eventually becoming a digital nomad and full-time solidity developer.

## Team code repositories
https://github.com/ChansonStudio/ChansonStudio.git

# Additional Information

N/A

**Comment by jenks-guo-filecoin** [comment]
@ErinOCon I have spoken to the project owner Jack Hui and understood their project's objective, approach and architecture. Happy to answer questions.

**Comment by jenks-guo-filecoin** [comment]
@realChainLife team for faster and reliable retrieval, I recommend using this [Superhot](https://nft.storage/blog/post/2022-05-24-superhot-gateway-announcement/) and use a public gateway as fallback.

**Comment by ChansonStudio** [comment]
@jenks-guo-filecoin Good recommendation thanks for the advice, should we update our design as a result of this?

**Comment by jenks-guo-filecoin** [comment]
I would recommend investigating for your needs before making final decision. You can reach out to #nft-stroage support channel on our public slack to ask specific questions if you are unsure about thing. :-) 

@ChansonStudio

**Comment by ChansonStudio** [comment]
@jenks-guo-filecoin  Awesome team awesome advice, thanks for always pointing us to the right direction. Will do. Thanks again.

**Comment by ErinOCon** [comment]
Hi @ChansonStudio, thank you again for your proposal! We would like to consider supporting this project at a smaller amount. Can the proposal be updated to support a beta platform at $50,000? This could be for events, UX/UI improvements, etc.

Please let me know if you have any questions!

**Comment by ChansonStudio** [comment]
@ErinOCon Thanks Erin for reaching out, it is great for your team to first considered this project. We have discussed internally within our team and we have tried to remove some features in this project funded by Filecoin and pursue a USD$100k funding if possible.
The project itself is still a dream mission for us, we will try to complete all other features on our roadmap in future releases where funding is available, and we still aim at driving higher user adoption and user traffic to Filecoin infrastructure as part of this project mission.

# Milestone 1 - INFRASTRUCTURE SETUP, WEB FRONT-END UI DEVELOPMENT:
-	Design and complete AWS web server & application server hosting infrastructure setup. A web hosting solution is required for our webapp which then will be fully integrated with blockchain and FileCoin platform.
-	The web server infrastructure will be hosting our web application
-	The application server infrastructure will be hosting smart contract and storage operation application.
-	Set up front-end web portal home page and user interface.
-	duration: 1 month

# Milestone 2 - COMPLETE CRYPTO WALLET INTEGRATION, FILECOIN STORAGE INTEGRATION:
-	Complete crypto wallet integration with web app so that user can connect their wallet with the web application.
-	Complete Filecoin storage integration (NFT.Storage + Filedrive) to allow uploading digital assets via web portal.
-	duration: 1 month

# Milestone 3 - BUILD MARKETPLACE WEB PORTAL AND SMART CONTRACTS FOR MUSIC NFT MINTING:
-	Design and develop the smart contract logics for minting NFTs based on the uploaded digital content.
-	Build a marketplace web portal on which allows the users to upload and mint music NFTs.
-	duration: 1 month

## Planned Future Roadmap
-	Migrate the smart contract to FileCoin virtual machine
-	Using FileCoin token for NFT mint cost and NFT transaction costs

## Total Budget Requested
USD$100,000

| Budget Table        | Milestone 1 | Milestone 2 | Milestone 3 |
|---------------------|-------------|-------------|-------------|
| Graphic Designer    | USD$8,000   | USD$8,000   | USD$4,000   |
| Front End Dev       | USD$15,000  | USD$15,000  | USD$5,000   |
| Blockchain Dev      | USD$15,000  | USD$15,000  | USD$15,000  |
| Cloud Platform Cost | USD$1,000   | USD$1,000   | USD$1,000   |
|                     |             |             |             |
| Total               |             |             | USD$103,000 |

**Comment by ChansonStudio** [comment]
> Hi @ChansonStudio, thank you again for your proposal! We would like to consider supporting this project at a smaller amount. Can the proposal be updated to support a beta platform at $50,000? This could be for events, UX/UI improvements, etc.
> 
> Please let me know if you have any questions!

Hi @ErinOCon any updates on our suggestion with a changed scope? Thanks.

**Comment by ErinOCon** [comment]
Hi @ChansonStudio, thank you for checking in! We should have more information available next week!

**Comment by ChansonStudio** [comment]
Hi @ErinOCon Our team has discussed internally and have decided to go with your previous suggestion to support our beta platform at $50,000.
Below is the list of scope we will be considering at delivering:
- Infrastructure setup
- Storage integration with Filecoin
- UI development for Chanson music web portal and UI & UX improvement

The backend smart contract development work on blockchain we will try to find other funding resource to cover the efforts.

Thank you

**Comment by ErinOCon** [comment]
Hi @ChansonStudio, we have approved this grant! Can you update the proposal template with the $50k budget and updated deliverables in mind?

**Comment by ChansonStudio** [comment]
@ErinOCon  We are delighted to hear that, we have updated below plan as requested:

# Milestone 1 - INFRASTRUCTURE SETUP, WEB FRONT-END UI DEVELOPMENT:
-	Design and complete AWS web server & application server hosting infrastructure setup. A web hosting solution is required for our webapp which then will be fully integrated with blockchain and FileCoin platform.
-	The web server infrastructure will be hosting our web application
-	The application server infrastructure will be hosting smart contract and storage operation application.
-	Set up front-end web portal home page and user interface.
-	duration: 1 month

# Milestone 2 - COMPLETE CRYPTO WALLET INTEGRATION, FILECOIN STORAGE INTEGRATION:
-	Complete crypto wallet integration with web app so that user can connect their wallet with the web application.
-	Complete Filecoin storage integration (NFT.Storage + Filedrive) to allow uploading digital assets via web portal.
-      UI & UX enhancement on music NFT creation path and user interfaces.
-	duration: 1 month

## Total Budget Requested
USD$50,000

| Budget Table        | Milestone 1 | Milestone 2 |
|---------------------|-------------|-------------|
| Graphic Designer    | USD$9,000   | USD$9,000   |
| Front End Dev       | USD$15,000  | USD$15,000  |
| Cloud Platform Cost | USD$1,000   | USD$1,000   |
|                     |             |             |
| Total               |             | USD$50,000  |

**Comment by ErinOCon** [comment]
Hi @ChansonStudio, thank you for the update! Can you provide an email address for discussing next steps?

**Comment by ChansonStudio** [comment]
> Hi @ChansonStudio, thank you for the update! Can you provide an email address for discussing next steps?

Thanks @ErinOCon  We are reachable on ChansonStudioNFT@gmail.com, looking forward to your instructions on next step.

**Comment by ChansonStudio** [comment]
@ErinOCon  we still haven't received any instruction so far, have you reached out?

**Comment by ErinOCon** [comment]
Hi @ChansonStudio, thanks for checking in! We have sent the program details to the provided email address. Please let us know of any questions!
