### ISSUE TITLE
Open Grant Proposal: NFTCreatorStudio

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/devgrants#763]
# Open Grant Proposal: `NFTCreatorStudio`

**Name of Project:** NFTCreatorStudio

**Proposal Category:** app-dev

**Proposer:** `FroghubMan`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

Problem: In the Filecoin ecosystem, there is a lack of a platform that facilitates NFT creators to create and release NFTs. Although nft.storage greatly facilitates the storage of NFT data, it is difficult for NFT creators who do not have the ability to develop.
It's still not good enough. In order to publish NFTs, they need to master the following abilities:
- Use Photoshop to inefficiently synthesize footage into NFT images
- Know how to store NFT pictures to IPFS network
- Master the development and deployment of NFT contracts

Solution: Our team wants to implement a platform for NFT creators to facilitate the creation of NFTs. Users only need to configure the corresponding layers in order, then place the materials in the corresponding layers, With the NFT generation strategy, NFT can be produced in batches. Finally, the corresponding blockchain network can be selected for one-click publishing. At the implementation level, we want to use nft.storage to store NFT images.After FVM opens up its programmable capabilities, we will provide the ability to publish NFTs to the Filecoin network with one click.

## Value

NFTCreatorStudio connects NFT creators with the Filecoin network, lowers the threshold for NFT creators to enter the Filecoin network, and can effectively improve the adoption of the Filecoin network in the NFT field.

## Deliverables

Our goal is to provide a platform for NFT creators to facilitate the production and release of NFTs to the Filecoin network. Users only need to organize the materials and layers on the platform, select the corresponding generation strategy to generate NFT images in batches, and finally press a button to publish the NFT to the Filecoin network.

## Development Roadmap

Milestone 1: design phase

1-2 week: USD$3000

- user interface design
- Server-side data modeling

Milestone 2: Basic function development

1-2 month: USD$10000

- Integration with Dapp-enabled Filecoin wallet (optional)
- Material and layer module
- Generate strategy modules
- NFT module
- Integrate nft.storage to facilitate the storage of NFT images

Milestone 3: Integration of smart contracts

1-2 month: USD$12000

- Realize ERC-721-like NFT contract \ Owner authority contract based on FVM
- Realize ERC-721 factory contract based on FVM
- Integrate Filecoin smart contract into WebApp, users can publish NFT to Filecoin network with one click

## Total Budget Requested

Total: USD$25,000

## Maintenance and Upgrade Plans

We will maintain the project for a long time, fix related bugs, and actively adapt to the potential NFT market

# Team

## Team Members

Wenxin Chen wenxin@froghub.io
He Zheng zhenghe@froghub.io

## Team Website

https://www.froghub.io/

## Relevant Experience

We have provided related development tools to NFT creators:
     - Combine materials into NFT images in batches according to certain rules, and store them in the IPFS network
     - Post NFT images to EVM compatible blockchain networks

In addition, we have also made corresponding attempts in the NFT field:
- Implemented NFT blind box based on ChainLink and put it on the Opensea market
- Implemented ERC-721NFT-based  market, and conducted data analysis on collections in the market through thegraph

We has great experience in Blockchain and Smart Contract development.Major Skills are:
- Javascript, React.js, Vue.js
- Solidity, Rust, Golang, Java

We have also been paying attention to the development progress of FVM recently, and actively participated in the early construction activities, hoping to be the first development team to adapt to FVM.

## Team code repositories

https://github.com/froghub-io

# Additional Information

**Comment by ErinOCon** [comment]
Hi @FroghubMan, this grant has been approved! We will reach out by email to discuss next steps.
