### ISSUE TITLE
Next Step Microgrant: Soft load balanced client

### ISSUE THREAD

**Issue by FroghubMan** [filecoin-project/devgrants#764]
### 1. What is your project? (max 100 words)

Implement a soft load balancing client (as a library) with the heaviest chain selector for miner node.

Since a single chain node is prone to delay in chain synchronization due to network problems, it will affect the block production of miner node.

Using our chain node client can solve this problem. By dynamically selecting the heaviest chain node, it reduces the impact of network factors on chain synchronization, improves the stability of miner node' block production, and avoids the problem of single point of failure.

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

The Lotus API will be used for this project
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Since the load balancing client is provided to the miner nodes, there are many API interfaces involved, and more comprehensive testing is required.
With funding, we can lease computing resources and deploy more chain nodes for more comprehensive testing.

 
### 4. Is this project open source?

Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

  
### Additional questions:
|  Name   | Email  | Github | Role |
|  ----   | ----   | ---- | ---- |
| samuerio | 853713419@qq.com |   https://github.com/samuerio     | developer     |

**Comment by ErinOCon** [comment]
Hi @Froghubman, thank you for your proposal. We would like to see an active prototype before considering a grant for this project. Please feel welcome to re-apply once your building has progressed!

**Comment by FroghubMan** [comment]
Hi @ErinOCon, we'll add the active prototype info and re-apply.
