### ISSUE TITLE
Next Step Microgrant: Creative Coding NFT's

### ISSUE THREAD

**Issue by ClockworkOrange605** [filecoin-project/devgrants#766]
### 1. What is your project?

NFT Marketplace for Creative Coding Artworks
***Codepen.io for NFT's or Foundation.app for Programmable Art***

Creators can use our Online IDE to develop Artwork. Upload metadata to IPFS with Media Files generated at our server. And mint their tokens to our Curated Collection or deploy their own Smart Contract. In other words, they can create and publish their artworks without leaving our service.

Collectors can browse and collect Artworks that they like directly at our Marketplace. Or at any other Marketplaces (like Opensea.io or Rarible.com) that aggregates ERC-721 compatible NFT's.

Initial Prototype: https://github.com/ClockworkOrange605/nft-hack 
Refactored Version: https://github.com/ClockworkOrange605/crcode 

### 2. How will IPFS, Filecoin, or related technology be used for this project? 

All tokens metadata will be uploaded and stored at IPFS. Before minting Creators can check metadata already uploaded to IPFS and make sure that all files were been uploaded correctly and accessible with public IPFS gateway. 

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? 

My next goal is to finish MVP and run public beta. 

I have scope of tasks that I want to finish before I will be ready to show this project to the target audience. And this grant will let me to focus on the development of this project and cover the costs of cloud providers. 

### 4. Is this project open source? 

MIT 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period? 

Yes 

### 6. Does your proposal comply with our Community Code of Conduct? 

Yes 

### 7. Links and submissions 

NFTHack: https://medium.com/encode-club/nft-hack-finale-prizewinners-and-summary-a68be99f6c66 

### Additional questions: 

* For each team member(s), please list name, email, Github account, and role in the project. 
  - Andrey Kochkin | kochkin.andrey@gmail.com | https://github.com/ClockworkOrange605 | Founder/Developer 

* How did you learn about our microgrant program? 
  - Emails for Hackathon Finalists 

* If your project was created as part of an event or hackathon: 
  - NFTHack: https://youtu.be/cf11hpcSMT0

**Comment by ErinOCon** [comment]
Hi @ClockworkOrange605, this grant has been approved! We will send an email to confirm payment details.
