### ISSUE TITLE
Next Step Microgrant: Nexus Protocol

### ISSUE THREAD

**Issue by protocol-nexus** [filecoin-project/devgrants#767]
### 1. What is your project? (max 100 words)
Nexus Protocol is a Decentralized Storage Network (DSN) aggregator which helps developers build decentralized applications easily by abstracting the complexities of integrating different DSN's

Nexus provides a single point of access to all supported / major DSN via the SDK. We use AI to help individuals and businesses find the best DSN for their files, helping to make blockchain-based file storage more accessible and cost-effective. We aim to make decentralized file storage a viable alternative to regular cloud storage by reducing barriers to entry and improving efficiency. 

We are building a decentralized mesh system on IPFS.

[Nexus SDK](https://github.com/protocol-nexus/Nexus-SDK)
[Nexus Decentralized Storage](https://github.com/protocol-nexus/Nexus-Decentralized-Storage/tree/main/)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Nexus data mesh consist of three main components:

Decentralized storage(IPFS)
Decentralized database
Decentralized computation.

The decentralized storage(IPFS) and decentralized database provides fast storing/querying services for various
data types. Whether the data is structured data or unstructured data, the Nexus data mesh will process
them in different ways according to the different data type, such as speeding up data query and video
playback.

Filecoin is the primary DSN for Nexus. We directly interact with IPFS for storing, retrieving and pinning files
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Receiving financial aid would allow us to continue work on:
1. Nexus Incentive Testnet Features Enrichment
3. Go support for the Nexus SDK
4. Would allow us to enhance our security measures via Code audits.
5. Smart contract code audit

### 4. Is this project open source?
Yes! All github repositories links have been provided above in section 1.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Not a part of a hackathon. 

### Additional questions:
***Nexus Team***

Name: Ananya Sharma
Github: https://github.com/protocol-nexus
Role: Lead Developer
Email: nexus.associations@gmail.com

Name: Callum Cornock
Github: https://github.com/callum-codes
Role: Junior Developer
Email: callumcornock@gmail.com

* How did you learn about our microgrant program?
https://filecoin.io/build/#grants

**Comment by ErinOCon** [comment]
Hi @protocol-nexus, this grant has been approved! We will send an email to confirm payment details.

**Comment by ErinOCon** [comment]
Hi @protocol-nexus, I hope you are doing well! It looks like you are about a month out from your reporting date. Do you have any questions for our team? The template for the report can be found [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
