### ISSUE TITLE
Next Step Microgrant: Deco, Decentralized Commerce

### ISSUE THREAD

**Issue by HabacucMX** [filecoin-project/devgrants#768]
### 1. What is your project? (max 100 words)

Deco is a decentralized commerce Dapp and with game-fi interactions on [Punk Cities](https://showcase.ethglobal.com/buildquest/punk-cities-0w24e). Users can mint IRL small businesses as NFTs and set them to create products or services as burnable ERC 721 tokens and offer them on web3 marketplaces. **Deco uses IPFS through NFT storage** to pin logos from business NFTS , images from products/services, and NFTs’ metadata.

Every sale splits the income between the owner and a vault contract for income from de-fi protocols. Punk Cities use game units to buy products or services on Deco while owners will be able to exchange them for ERC20 tokens.

[Github repository](https://github.com/zenbitETH/DeCo)

[Demo](https://deconft.surge.sh/)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

We are looking to use IPFS through NFT storage for decentralized storage for the dapp assets, images for the business logos, and content for products/services, along with the storage of the JSON files with the NFTs metadata, and explore decentralized dapp hosting on IPFS through Fleek.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

**1. Player authentication**

- [ ]  Set locked and unlocked states
- [ ]  Upgrade Hud for a player account and PC game units

**2. Minting Business NFT**

- [ ]  Set IPFS for Business Logo
- [ ]  Set Form for dropdown with hardwired cities and digital store options
- [ ]  Use empty text field for address for testing
- [ ]  Evaluate the usage of google maps or any open source maps for the address field
- [ ]  Modals for transactions, minting, and error states

**3. Business Setup**

- [ ]  Set IPFS for products or services
- [ ]  UI and contract update for pricing products in USD
- [ ]  Set Matic, Ether, and USDC as payment currencies
- [ ]  Update UI to show sold products
- [ ]  Set verification on UI and Contracts
- [ ]  Buying active on UI
- [ ]  Covalent tracking dashboard

**4. DeFI Vault**

- [ ]  Set individual and general vaults
- [ ]  Update on contract to deposit on vault contract instead of blackhole on product sales
- [ ]  Covalent tracking balances on vault
- [ ]  Enable deposits of Matic, Ether, and USDC
- [ ]  Aave integration for compound interest on vaults

**5. Punk Cities Integration**

- [ ]  Fetch Punk Cities game units on hud
- [ ]  Set Energy and Chips as verification rewards
- [ ]  Set Energy and Chips as payment currencies for auctions
- [ ]  Evaluate Punk Cities treasury integration and/or DEX for energy/chips/Matic/Ether/USDC swaps
- [ ]  Punk Cities minting on Nuxt.js

### 4. Is this project open source?

Yes, this is an open source project under MIT license 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?

Yes, we agree to share weekly updates and a grant report upon conclusion

### 6. Does your proposal comply with our Community Code of Conduct?

Yes, our project complies with the code of Conduct

### 7. Links and submissions

[ETH Global Hack Money 2022](https://showcase.ethglobal.com/hackmoney2022/deco-zxa8s)

### Additional questions:

Tentative Team

- **Habacuc Vera** / [habacuc@zenbit.mx](mailto:habacuc@zenbit.mx)]  / [github](https://github.com/HabacucMX) / Frontend, Product Architect
- **Krisztian Barta** / [bartariki@gmail.com](mailto:bartariki@gmail.com) / [github](https://github.com/Riki0923) / Smart Contracts, Backend

We get noticed via email about the Filecoin/IPFS grants system

Deco was developed @ [ETH Global Hack Money 2022](https://showcase.ethglobal.com/hackmoney2022/deco-zxa8s)

**Comment by ErinOCon** [comment]
Hi @HabacucMX, this grant has been approved! We will send an email to confirm payment details.
