### ISSUE TITLE
Next Step Microgrant: w3s-rs

### ISSUE THREAD

**Issue by qdwang** [filecoin-project/devgrants#769]
### 1. What is your project? (max 100 words)

A Rust crate(library) for web3.stroage.

It supports concurrent uploading with compression and encryption.
It also supports >100MB file uploading with auto CAR generation.

[https://github.com/qdwang/w3s-rs](https://github.com/qdwang/w3s-rs)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
The crate includes:
* IPFS gateway checker
* CAR file generator
* web3.storage API usage

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

To accomplish the unfinished tasks in todo list and do more optimization and documentation.

### 4. Is this project open source?

Yes, already in MIT and Apache2.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, not a problem.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
No

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
dev: [qdwang](https://github.com/qdwang/)

* How did you learn about our microgrant program?
https://grants.filecoin.io/

* If your project was created as part of an event or hackathon:
No

  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by jenks-guo-filecoin** [comment]
@ErinOCon I understood the benefit of the project and signed up to be their technical sponsor. :-)

**Comment by ErinOCon** [comment]
Hi @qdwang, thank you for your proposal! Can you provide more detail on how you will improve your project over the next three months? This information will support our grant report process.

**Comment by qdwang** [comment]
@ErinOCon 

Mainly I'll do improvments in three parts:
1. Add more features for the library. (mainly include `download` parts and `directory` uploading)
2. Add code comments.
3. Complete project documentation.

**Comment by ErinOCon** [comment]
Hi @qdwang, this grant has been approved! We will send an email to confirm payment details.
