### ISSUE TITLE
 Next Step Microgrant : ContentPublishing

### ISSUE THREAD

**Issue by alwayschatter** [filecoin-project/devgrants#772]
### 1. What is your project? (max 100 words)
A new playground for anyone to create, discover, share, reward and distribute articles.All articles here are under Creative Commons Attribution 4.0 International License.We help turn articles into NFTs. People can buy their loved NFTs for donation purpose.We aim to help create next-generation content communities with pure open-source, open-data, open-protocols and web3 technology.

https://github.com/alwayschatter/ContentPublishing

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
We will use IPFS/Filecoin to store the content published by all users, and record the content index published by each web3 user on the chain, so that we can create our own content collection on the platform and persistently save the content published by ourselves.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
There is only one demo at present. We will use this fund to continuously improve the code and develop new functions along the established direction. We have many ideas based on this. We will use this fund to improve content publishing and content sponsorship. Wait a few functions
 
### 4. Is this project open source?
yes
### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes
### 6. Does your proposal comply with our Community Code of Conduct?
yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @alwayschatter, thank you for your proposal. This grant has been approved! Can you provide a preferred email address to confirm payment details?

**Comment by alwayschatter** [comment]
> Hi @alwayschatter, thank you for your proposal. This grant has been approved! Can you provide a preferred email address to confirm payment details?

Hi @ErinOCon , Thank you very much . Email  :  webchatter@163.com

**Comment by alwayschatter** [comment]
> > Hi @alwayschatter, thank you for your proposal. This grant has been approved! Can you provide a preferred email address to confirm payment details?
> 
> Hi @ErinOCon , Thank you very much . Email : [webchatter@163.com](mailto:webchatter@163.com)

Hi @ErinOCon , Awaiting your payment email, thanks again！

**Comment by ErinOCon** [comment]
Thank you!
