### ISSUE TITLE
Next Step Microgrant: <LCP SPE Learn to Earn>

### ISSUE THREAD

**Issue by rokushnir** [filecoin-project/devgrants#773]
### 1. What is your project? (max 100 words)
LCP SPE (L2E) is a training tote in which the participant buys a course bets on himself that will pass it to the end

[https://www.figma.com/proto/fvsBfj5Li3RIFfMCvTMQlB/Tochno_optyka?page-id=425%3A1632&node-id=774%3A937&viewport=941%2C-1221%2C1.13&scaling=scale-down&starting-point-node-id=742%3A3350](url)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
We need to store videos and user data and we can do it using Filecoin
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We are ready to use our video base on your resources.
 
### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions

https://docs.google.com/spreadsheets/d/1P6I2dGAviy8P96EGnYgGOUNhlz8CobSv3MHmNMMWFGI/edit?usp=sharing

https://drive.google.com/file/d/1t26uIOsC47YlIdx9v_j2gGQkaAnHh-Qx/view?usp=sharing

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Roman Kushnir | СEO, Founder | https://www.linkedin.com/in/rokushnir/ / rokushnir@gmail.com
Yurii Dygolyan | QA Automation Engineer (25%), SQL Developer (50%) | www.linkedin.com/in/sofard
Oleksandr Kravylnykov | TechLead (25%), DevOps Engineer (25%) | https://www.linkedin.com/in/alex-krasilnikov-3b600622a/
Anastasiya Ostryk | Marketing Director | https://www.linkedin.com/in/anastasiia-ostryk/
Olexandra Ulyan | Content manager |  
Liliana Poberezhnyuk | Sales manager, Account manager | https://www.linkedin.com/in/%D0%BB%D1%96%D0%BB%D1%96%D0%B0%D0%BD%D0%B0-%D0%BF%D0%BE%D0%B1%D0%B5%D1%80%D0%B5%D0%B6%D0%BD%D0%B8%D0%BA-31331021a/

* How did you learn about our microgrant program?
from friends

**Comment by ErinOCon** [comment]
Hi @rokushnir, thank you for your proposal. In order to consider this project for the microgrant program, a working prototype is needed. Please feel welcome to re-apply once your building has progressed. In the meantime, you may want to take this project to a hackathon!
