### ISSUE TITLE
Next Step Microgrant : DMovie

### ISSUE THREAD

**Issue by 0xrandom0x** [filecoin-project/devgrants#774]
### 1. What is your project? (max 100 words)
We plan to build a decentralized shared video media platform.Users can use the web3 wallet to log in to the platform, browse the corresponding video resources according to their own preferences, and also save video resources to their own collections (built on IPFS/Filecoin).
Users can tip their favorite videos to complete rewards for content creators, etc. At the same time, users can also upload their own video collections or individual videos to get rewards for video playback.
As an operator, we will communicate with content creators related to documentaries so that they can upload film and television resources to the platform to get rewards.
All media, film and television resources will be stored in the IPFS/Filecoin network through web3.storage, Filecoin nodes, etc.
All media and film and television resources are also allowed to record the ownership of the content on the chain through nft.storage, the relevant information of the film and television to which they belong (the number of viewers, the number of likers, the amount of appreciation, etc.)

https://github.com/0xrandom0x/dmovie
We have currently built the front-end template code for the entire website. In the future, business functions will be completed based on template code

https://m46ii-eyaaa-aaaad-qddpq-cai.ic.fleek.co/ 
This is the link to the deployed front-end interface

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
 We will use the ceramic network to establish user information flow data, which is a data network built on IPFS.
The user's video media resources will be stored through web3.storage and nft.storage. In order to increase greater stability and reliability, we will use third-party Pin services such as pinata to perform multi-node Pin services for data

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Through this grant, we will accomplish the following goals:

-  Build a user-based ceramic data system
-  Add web3.storage and nft.storage to upload video resources and record them to the user data system
-  Implement a Polygon-based contract system (content attribution, content viewers, praise, comments, and content appreciation funds)
- Deploy multiple media collections to increase platform initial video resources
- Invite video creators to participate in platform content creation
- The overall front end is modified based on business logic

### 4. Is this project open source?
Yes
### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
### 6. Does your proposal comply with our Community Code of Conduct?
Yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
 0xrandom0x , Decentralized developers active in web3, dedicated to bringing high-quality application resources to web3 users,0xrandom0x@proton.me
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @0xrandom0x, thank you for your grant proposal! We would like to see more progress towards a working prototype before considering a grant for this project. For next steps, we recommend participating in a hackathon!

Please feel welcome to re-apply once your working prototype is complete.
