### ISSUE TITLE
Open Grant Proposal: IPFS VS Code Extension

### ISSUE THREAD

**Issue by yjliu-dataseek** [filecoin-project/devgrants#775]
# Open Grant Proposal: `IPFS VS Code Extension`

**Name of Project:**
IPFS VS Code Extension

**Proposal Category:** `integration-adoption`

**Proposer:** `@yjliu-dataseek`

**(Optional) Technical Sponsor:** `none`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** `Yes`

# Project Description
It's like "IPFS Desktop" but made for Visual Studio Code IDE to provide developers with a more integrated development experience and convenient developer tooling.

The problem with developing with IPFS is it often requires developers to run a local IPFS node or use a hosted node (e.g. Infura) to be able to use it. This project aims to give developers a one-click experience to IPFS.

## Value

This integration project is able to improve the speed and the experience of developers who are seeking to interact with IPFS fast. It provides a "one-click" experience on IPFS node installation and a convenient way to deploy files and code to IPFS for storage.

This can improve the experience of developers and be offered on IPFS docs as an alternative way of interacting with the technology.

It speeds up developer's time it takes to upload their first file to IPFS which will improve satisfaction.

Major risks are unknown/undocumented limitation of the VS code environment stopping implementation of major function.

## Deliverables

The extension needs to allow developers to get a range of tools that helps speed up using IPFS and upload files without having to manually install IPFS.

It should:
* automate IPFS CLI installation process
* provide terminal panel to monitor IPFS node
* provide UI for uploading file(s) to IPFS
* allow any code file to be deployed to IPFS
* detect CIDs in code and display information

## Development Roadmap

Mocked UI (not a prototype):
<img width="1150" alt="Screen Shot 2022-07-21 at 4 40 25 pm" src="https://user-images.githubusercontent.com/109561889/180146522-5357935d-c7bd-474c-a149-693d39f65219.png">

Team members:
1x Product Manager
1x UX Designer (contract)
1x Lead Developer

### --- Milestone 1 ---
Breakdown requirements and technical spikes.

Tasks:
- design UI elements
- work out user flows
- discover tech challenges
- break down tasks to manageable sizes

Time: 2 week
Funding: $6,500

### --- Milestone 2 ---

Implement the core functionality

When extension is installed:
- checks if IPFS cli is already install, if not
- detect OS and install corresponding latest stable IPFS CLI tooling
- run IPFS node daemon in a new terminal
- checks if IPFS node is running correctly
- create a new IPFS activity bar with IPFS logo
- create a new IPFS status bar
- jump to IPFS view in sidebar
- jump a new terminal panel called IPFS and show daemon print out

In IPFS activity sidebar:
- show IPFS node status: online | offline
- show node information: Peer ID, connected peer numbers, gateway address, API address, public key
- accordion to show list of pinned files
- allow preview of the file in web view
- allow user to use a button to select and upload file(s) to IPFS
- pin the files
- display CID after uploading file(s) in IPFS panel

Time: 8 weeks
Funding: $24,000

### --- Milestone 3 ---

Status Bar:
- show IPFS node status: online | offline

Sidebar UI - right click on any file in sidebar, a file or a folder:
- allows send to IPFS via context menu
- show results on IPFS terminal

Code editor:
- Display an IPFS toolbar button to upload the file to IPFS
- show result in the IPFS terminal
- Detect v0 & v1 CID string syntax and highlight in editor

When user hover over a detected CID:  
- CID version
- Display human readable CID
- Multibase information (prefix, name)
- Multibase information (code, name, bits, Digest)

Look for test users.

Time: 4 weeks
Funding: $12,000

### --- Milestone 4 ---
Test and improve functions, performance and UI.

Acquire test users/developers of the VScode and:
- conduct 5-6 user interviews
- improve the UI of the extension
- improve the functionality of the extension
- improve performance of the extension
- refactor code & address tech debit incurred earlier

Time: 4 weeks
Funding: $9,000

### 12 months post-release support

Suport include:
- bug fixes
- changes to IPFS implementation
- small improvements based on user feedback

Funding: $10,000

## Total Budget Requested
$61,500

## Maintenance and Upgrade Plans

A part of the budget is allocated to keep staff on a casual basis to perform fixes, improvements over 12 months after the release of the tool.

This project will be open source so the community can contribute and help maintain the VS code extension.

If major changes to IPFS, then another grant will be required to run it.

# Team

## Team Members

[YJ Liu](https://github.com/yjliu-dataseek) - Project Manager - yjliu@dataseek.info

[Bo Liu](https://github.com/liubosdzl33?) - Lead Developer - liubo@dataseek.info

One UX/UI designer will be hired when the grant is approved

## Team Website
[Dataseek Agency](https://dataseek.info)

## Relevant Experience
See ["Our work" section](https://dataseek.info/#:~:text=concept%20to%20products.-,OUR%20WORK,-projects%20that%20we) on our agency website please.

## Team code repositories
https://github.com/DataseekCN/ipfs-vscode-extension

# Additional Information
How did you learn about the Open Grants Program?

`Filecoin Hackathon`

Please provide the best email address for discussing the grant agreement and general next steps.

`yjliu@dataseek.info`

**Comment by ErinOCon** [comment]
Hi @yjliu-dataseek, thank you for your proposal! This grant has been approved! We will send an email to confirm next steps for this grant.
