### ISSUE TITLE
Next Step Microgrant: Spicy Punks Phygital NFTs Themed Cafe

### ISSUE THREAD

**Issue by spicy-punks** [filecoin-project/devgrants#777]
### 1. What is your project? (max 100 words)
Spicy Punks is a NFT themed meet-up cafe based in Ludhiana, India which is focused on conducting the web3 meetups. Being Blockchain Maximalists we never found a space where we can interact with like-minded individuals, so we innovated the Spicy Punks to be a comfort for all our Web 3.0 fam. On a regular basis, we are conducting meetups so that all who share a similar vision in Ludhiana can discuss on the same platform about all the aspects of web3.

Introduction video: https://bit.ly/spicypunks

Github:https://github.com/spicypunks

Website:https://www.spicypunks.com/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
We will be storing the Phygital and POAP NFTs on IPFS/Filecoin. We will be educating about decentralised storage and Filecoin in our upcoming web3 meet-ups.  In future we plan to create NFT gated exclusive community for these meetups and IPFS/Filecoin will be used as the storage layer. 

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will be using this grant to integrate the NFTs in the cafe and organise meet-ups for educating about Filecoin and its role in decentralised storage.
 
### 4. Is this project open source?
Yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  NA
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program? Website
* If your project was created as part of an event or hackathon: No
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) NA
  * Please link to your hackathon submission NA

**Comment by ErinOCon** [comment]
Hi @spicy-punks, thank you for your proposal! Unfortunately, this does not closely align with our criteria for the microgrants program. We will keep this project in mind for any community building grants in the future! Wishing your team the best!
