### ISSUE TITLE
Next Step Microgrant: Hash Space - Winner of EthGlobal Hack Money 2022

### ISSUE THREAD

**Issue by syedrizvi** [filecoin-project/devgrants#778]
### 1. What is your project? (max 100 words)

Hash Space is a DeFi product discovery game that makes it fun for players to learn and test out new DeFi products, solutions, protocols. It combines DeFi, GameFi and HealthFi. Players fly around a galaxy in a starship powered by their footsteps (HealthFi). When they arrive at a new planet they learn about DeFi protocols and can get yield bounties from that protocol (DeFi), unless other players have already run away with the bounty on that planet for that day (GameFi).

It is centred around the starship NFT, which is stored on IPFS (via NFT.storage) and can be upgraded as the player progresses through the game.

The repo is available here: [https://github.com/hash-space/hash-space](https://github.com/hash-space/hash-space)

A live demo is available here: [https://v2.hashspace.quest/](https://hashspace.quest/) and [https://hashspace.quest](https://hashspace.quest)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
  Our game expands the boundaries of NFT gaming and it creates a completely new user acquisition avenue for DeFi protocols. The starship NFTs are stored on IPFS (using NFT.storage). The website itself is currently hosted in IPFS too (using Pinata). As we increase the sophistication of the upgradable starship NFTs, we will rely on IPFS for storage of our updating metadata.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The grant will enable us to build out the functionality for upgradable NFTs. At present, we are minting entirely new NFTs to upgrade from “level 1” to “level 2” starship, based on completion of challenges in the game. We want to set it up so that the NFT is only minted once, but continually updated and upgraded as the player progresses in the game. We want to make an open marketplace where players can trade these NFTs.

With the grant, we could bring in development support. We would hire a part-time blockchain developer ($2k for 2 months) and a part-time full stack developer ($1.5k for 2 months). We know people who are ready-to-go, but can’t commit the time unless reimbursed fairly. Additionally, we would hire a visual designer for 1 month ($1.5k) to create the aesthetics for our starships and galaxies.

—

*June - Our game is live on Polygon Mumbai Testnet.*

*July - Add optional decentralised storage of genetic data*

*Aug - Release updated version with genetic insights and reports*

*End of Sept - Social challenges introduced to encourage to inviting friends*
 
### 4. Is this project open source?

Yes - GPL license

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  Yes, aggreged. 

### 6. Does your proposal comply with our Community Code of Conduct?

Yes it complies with the Community Code of Conduct 

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  The project was initial built at ETHGlobal’s Hack Money 2022, where we won the most prizes out of all teams - including the Pool Prize from IPFS/Filecoin: https://showcase.ethglobal.com/hackmoney2022/hash-space-fjy9k

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
1. Ali Rizvi <ali.rizvi.mck@gmail.com>
https://github.com/syedrizvi
Community & partnerships, Project management, game design, graphic design, Frontend dev
2. Manuel Villing <manuel.villing@gmail.com>
https://github.com/theotow
Full stack dev, DeFi integrations, Smart contracts, Activity integration, Backend, DevOps
3. Chris Lovejoy <christopher.lovejoy1@gmail.com>
https://github.com/chris-lovejoy
Full stack dev, ML researcher, Multi chain deployment, Frontend
4. Ignacio Pastor <ignacio@fullstackwebthree.com>
https://github.com/IpastorSan
Smart contract dev, Contract upgradability
5. Dhruv Malik <malikdhruv1994@gmail.com>
https://github.com/grandgarcon 
Solidity developer, leading on DeFi integration 

* How did you learn about our microgrant program? 
From IPFS devrel https://twitter.com/DeveloperAlly

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
ETHGlobal Hack Money 2022
  * Please link to your hackathon submission
https://showcase.ethglobal.com/hackmoney2022/hash-space-fjy9k

**Comment by ErinOCon** [comment]
Hi @syedrizvi, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!
