### ISSUE TITLE
Building an on-chain market for RECs

### ISSUE THREAD

**Issue by jon-spark-eco** [filecoin-project/devgrants#780]
# Open Grant Proposal: `Building an on-chain market for RECs`

**Name of Project:** `Spark Eco` 

**Proposal Category:** `green`  

**Proposer:** `jon-spark-eco`

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

Marc Johnson

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Please respond with either "Yes" or "No"

Yes

# Project Description

Milestone 1: Research and Whitepaper
Conduct interviews of brokers, certifiers, solar developers, and other key players working in the existing REC markets worldwide.
Continue building a partnership with Zero Labs to better understand how to build on top of their REC minting protocol.
Bring on a part-time developer to help define the technical details of building on top of the Zero Labs protocol.
Write up this research and our plan for building the marketplace in the form of a whitepaper.
One operator/researcher, one developer, and two advisors will work on this milestone
$50,000
8/1/22-11/1/22

Milestone 2: Version 0 of the Aggregation Platform
Begin building the aggregator marketplace.
Zero Labs is minting the RECs as NFTs. We will start by aggregating these NFTs into pools.
Taking some inspiration from Toucan Protocol, we envision creating general pools for the RECs by vintage year.
We will write smart contracts to transfer the RECs into pools. 
We will create a UI so REC suppliers can bring their RECs on-chain, and Buyers can purchase these RECs.
 One operator/researcher and two developers, and two advisors will work on this milestone
$200,000
11/1/22-5/1/22

## Total Budget Requested

$250,000

## Maintenance and Upgrade Plans

Long Term, we plan to continue to build and maintain the marketplace. In future versions of the marketplace, we would like to add FIAT onramps, and more pools/aggregations and explore a forward market for these RECs.

# Team

## Team Members

Jon Ruth - Founder
Harper Reed - Tech Advisor
Tricia Wang - Research Advisor

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/jonruth/
https://www.linkedin.com/in/harperreed/
https://www.linkedin.com/in/triciawang/

## Team Website

https://spark.eco/

## Relevant Experience

[Jon Ruth](https://twitter.com/jhruth) is the founder of Spark Eco and has over 15 years of experience developing, managing, and constructing large utility-scale solar projects. Jon has many connections to developers, EPCs, and other parties in the solar industry. Since 2016 Jon has been involved in cryptocurrency, including mining various cryptocurrencies. This formed his early first-hand concerns about the environmental impact of blockchain technology. Jon is a passionate art collector who has been collecting art for several years. For 20 years, Jon has studied climate change, and he has a passion for building sustainable solutions to one of the most significant challenges humanity faces. Jon is building his legacy by making the maximum impact possible in the fight against climate change.

[Harper Reed](https://twitter.com/harper), is a technologist that predicts the future for a living. He is currently the CEO of [General Galactic Corp](https://galactic.io/). He spends most of his life building big things, hacking things, and talking about doing both of those things. As CTO of the Obama 2012 campaign, Harper was the first to bring the tech mentality to a political level. He believes the talent of a great bunch of humans can transform an organization like nothing else and uses that belief to strengthen, deploy, and inspire every team he works with. Harper also believes his incredible luck has led him to achieve wonderful things like pioneering crowdsourcing at Threadless.com, founding Modest Inc, and guiding the software team at PayPal. You can find Harper hacking on personal projects and enjoying life in Chicago with his partner, Hiromi, his son, Yuga, and their beautiful and bizarre poodle, Lulu.

[Tricia Wang](https://twitter.com/triciawang), is a tech ethnographer obsessed with designing equity into systems. Tricia is currently the co-founder of the Crytpo Research & Design Lab (CRADL) at CISA. Part data geek, part designer, part researcher, and part community organizer, her belief that technology must serve humanity is the thread across her work in the private sector. She is the co-founder of[ Sudden Compass](http://suddencompass.com/), a consulting firm that redesigns the way companies leverage data to serve their customers. Her tech career started with the early days of texting and mobile phones to the emergence of Web 1.0, then Web 2.0, and now the Web 3.0 stack with a focus on the social impact of crypto and blockchain enabling technologies. Her focus on tech has always been in adoption amongst marginalized communities from the US to China to South America. She optimizes her life to be spent dancing, eating, hanging with her dog[ Elle](https://www.instagram.com/ellethedog_/), and her grandma. 

## Team code repositories

# Additional Information

I learned about the grant program after several discussions with Marc Johnson on the Filecoin Green team.

jon@spark.eco

Note that we have pivoted in our mission so our webpage speaks more about financing and owning solar projects. We have pivoted to working on the REC problem as we believe it will help drive the acceleration of solar project deployment. We are currently speaking to several devs about this project and believe this funding will help secure the needed resources.

**Comment by ErinOCon** [comment]
Hi @jon-spark-eco, thank you for your proposal! We would like to learn more on how this project will build out UI and UX and how it will gain traction/grow an end user base. Can the work outlined in Milestone 2 be broken into two separate stages for this information? Perhaps Part 1 of the milestone can address the technical component and Part 2 can speak to building traction? 

Please let me know if you have any questions for our team.

**Comment by ErinOCon** [comment]
Hi @jon-spark-eco, do you have any questions or updates for our team? We would be happy to discuss further as needed!

**Comment by jon-spark-eco** [comment]
Hi @ErinOCon, UI and, in turn, UX are essential parts of this program. We need to build an accessible solution that works for crypto native and REC native people. Right now, that community doesn't have a robust or natural connection. There is a need to build a bridge that connects. 

The UX strategy starts with the interviews in milestone 1. This is one aspect of why the interviews are so important. UI is not the only barrier to entry and is not the only key to building a high quality UX. We need to identify the barriers beyond the UI (technical skills, knowledge, and fear of crypto, to name a few) that we need to solve. After defining the barriers, we will work with some contractors to help define the requirements for the UI to maximize the UX. Our advisor Tricia Wang is an ethnographer and designer who does this for large corporations and think tanks. We will work within her network to find a contractor to help build our UI/UX strategy to execute in milestone 2.

Breaking this into two pieces does make sense for the second milestone. I want to ensure that we can secure funding for the project and was worried that too many tranches could cause some friction in the future. 

My thought is as you have described:

Milestone 2: Version 0 of the Aggregation Platform 
Objective 1 - Build the technical interfaces for interfacing with the Zero Labs protocol: 
	- smart contracts, pools, etc
Objective 2 - Build upon what we learned in stage 1 to create the UI/UX that allows for people to interface with our pools and smart contracts (v1 of the dapp)

We will focus on traction and growth for the second objective of milestone 2. Once we build the alpha version (objective 1), we will bring people in to participate. We will reach out to our existing contacts in the web3, corporate and solar communities (crypto native and REC native people) to create an alpha test group. We plan to include some of the people we interview in this group. This alpha group will guide us and be the kernel for growth. 

I think of this as bookends: UI & UX (interviews, etc.) in the beginning and community (traction, growth, etc.) at the end. The tech in the middle is worthless without both of these foundational pieces.

**Comment by ErinOCon** [comment]
Hi @jon-spark-eco, thank you for this information! We will be in touch after we have completed our review.

**Comment by ErinOCon** [comment]
Hi @jon-spark-eco, thank you for your patience as we continue our review. We expect to have more information available soon. In the meantime, I wanted to let you know that this grant is still under consideration. 

Hoping you are well!

**Comment by jon-spark-eco** [comment]
Thanks for the update @ErinOCon I continue to be excited about partnering with Filecoin on this exciting project.

**Comment by ErinOCon** [comment]
Hi @jon-spark-eco, thank you again for your patience. This grant has been approved! We will be in touch by email to discuss next steps soon. In the meantime, can you 1) provide a project description that summarizes the work you will be completing with this grant and 2) briefly describe the value of your project. This information is needed for our grant agreement.

**Comment by jon-spark-eco** [comment]
Hello @ErinOCon this is amazing news! We are so excited to build this project. Here are the requested project description and value statement.

**Project Description**
Climate change is one of humanity's biggest threats, and cryptocurrency has a large energy footprint. After speaking with the Filecoin Green and Zero Labs teams, we are excited about Renewable Energy Certificates (RECs) being brought on-chain as a new money lego. Verified transparent energy offsets are a building block that can be used to drive down, below zero, the environmental impact of Filecoin and, eventually, all of web3.

We want to accelerate the adoption of renewable energy around the world. Now that Zero Labs has formalized a standard and rolled out a tokenized REC protocol, we believe the next step is to build a market for this new on-chain energy offset. We want to create a platform for aggregating REC buyers and sellers. We will design a marketplace to connect sellers and buyers of RECs on-chain. Only brokers, large sellers, and buyers can access the existing REC market. We want to change that so buyers and sellers of all sizes can access verified RECs to offset their energy footprint. We believe that as this new market grows, it has the potential to be a subsidy that will accelerate the deployment of solar and other renewable projects.

We will work in partnership with Zero Labs to better understand how to build on top of their REC minting protocol and develop technical details for building a marketplace on top of it. We will conduct interviews with brokers, certifiers, solar developers, and other key players working in the existing REC, iREC, and GO markets worldwide. This work will culminate in a research whitepaper detailing a plan for building the REC marketplace. 

Using this whitepaper and our research, we will build the MVP of the marketplace. It will include writing smart contracts to aggregate the REC NFTs generated by the Zero Labs protocol into vintages, an on-ramp for new RECs, and a UI for purchasing these RECs. We will build an alpha community to test out the marketplace and refine it to meet the needs of crypto native and REC native users. We will rely heavily on our research and interviews to guide our design decisions.

**Value Statement**
Currently, there is no incentive for existing brokers to bring RECs on-chain. They do not see the value because there is no significant demand for this new class of verified on-chain RECs. We believe aggregating demand for this new asset will incentivize brokers and certifiers to move these assets to the blockchain. We believe this new marketplace may be a way for sellers to connect directly with buyers and bypass the brokers and fees.

As this marketplace grows, we also think there will be an opportunity to build a forward market for these RECs. Selling future RECs would allow us to help project developers monetize a portion of their project's RECs on day 1, creating a subsidy that should help accelerate the construction of these critical projects. We believe this subsidy can help close the financing gap many projects in emerging markets face. 

If we get this right, we can grow the supply of on-chain RECs and, in turn, increase the demand for these RECs in the web3 ecosystem. While Zero Labs has built the initial tool for minting RECs on-chain and Filecoin has begun purchasing these certificates, it will be difficult for this new market to take off and grow without aggregating a large volume of supply and demand for these RECs. If we can build this new market, we will also help accelerate the adoption and installation of solar and other renewables.

**Comment by ErinOCon** [comment]
HI @jon-spark-eco, thank you for the projection description and value statement. We are currently reaching out by email. Please do not hesitate to be in touch with any questions.
