### ISSUE TITLE
Next Step Microgrant : Melodia Protocol

### ISSUE THREAD

**Issue by melodia-protocol** [filecoin-project/devgrants#781]
### 1. What is your project? (max 100 words)

Melodia is a decentralized music-sharing protocol, which provides a blockchain based solution to help artists publish and monetize music across the online community.
Artists can publish music on the Melodia Protocol, and earn passively from every user streaming on the platform. The payout logic is defined in the smart-contract and is transparent. 
User can also choose to donate to a particular artist and all the proceeds are shared accordingly. 

We are on a mission to give everyone the freedom to share and monetize music

https://github.com/melodia-protocol/melodia-protocol

![image](https://user-images.githubusercontent.com/109826789/182698194-f973ad07-5593-42a1-beee-b9bfa9ef7796.png)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
We use IPFS/Filecoin to encrypt and store music/art from artists. This will later be used by a relay server to decrypt and stream to fans

<img width="532" alt="image" src="https://user-images.githubusercontent.com/109826789/180567372-38220324-553f-4149-ae34-ad5ffd8886e8.png">
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
- Auditing Smart Contracts
- Melodia currently supports the EVM chains. We are developing support for Polkadot and Solana, where there is a higher engagement of artists and fans. This grant will help us scale to these other chains in a shorter period of time.
- This grant will help us to reach a broader set of audience as well, through participating in different out-reach programs planned such as, NFT Marketing Events, local Blockchain Artists Association Events, etc.

### 4. Is this project open source?
yes

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Karthik AG - CEO (https://github.com/melodia-protocol)
`melodiaprotocol@gmail.com `

Pranav Pramod - Lead Designer (https://dribbble.com/pranav)
`pranav@apextest.co`

* How did you learn about our microgrant program?
Previously attended hackathon

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @melodia-protocol, thank you for your proposal! Do you have a link to your hackathon submission?

**Comment by melodia-protocol** [comment]
Hi @ErinOCon , We started off Melodia at the Solana Bengaluru HackerHouse, where IPFS was one of the sponsors. We were asked by the organizers to apply to this once we had reached the MVP Milestone

**Comment by ErinOCon** [comment]
Hi @melodia-protocol, this grant has been approved! We will be in touch by email to confirm payment details. 

Your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please reach out if you have any questions!
