### ISSUE TITLE
Next Step Microgrant: Swishh App

### ISSUE THREAD

**Issue by swishh-p2p** [filecoin-project/devgrants#782]
### 1. What is your project? (max 100 words)

Swishh allows users to communicate directly and anonymously by messaging/phone/video with any other wallet owner in the world, based only on knowing their wallet addresses.
Trade crypto assets and tokens crypto P2P via an integrated ESC (escrow smart contract) functionality.

Swishh avoids the personal and data risks present in existing messaging apps while offering a significantly greater level of privacy. On Swishh, all data and messages are stored and are encrypted with end-to-end encryption using IPFS.
We do not collect any sensitive personal data (emails, ID numbers, DOBs, physical addresses, etc), avoiding altogether the risk of data hacks.
IPFS makes it possible to eliminate the security risk of centralised user data storage, bypassing any central points of failure
Stores message history and files (photos, documents, etc.) on anonymous, independent on the IPFS network.

[https://github.com/swishh-p2p/mobile-rn](https://github.com/swishh-p2p/mobile-rn)

[https://github.com/swishh-p2p/swishh-go](https://github.com/swishh-p2p/swishh-go)

**Why we need decentralised P2P Messaging applications?**

<img width="829" alt="image" src="https://user-images.githubusercontent.com/109857025/180620022-afde519c-ab4b-4053-8a8a-b1943de22fe7.png">

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

- We utilize **Diffie–Hellman key exchange** algorithm to securely exchange messages stored on IPFS using OrbitDB’s document storage.
- We use ***Web3 Storage*** to promote Data Security - Files (photos, documents, etc.), message history are stored on trusted, distributed P2P (peer to peer) network on IPFS, and transfers happen on a P2P basis, based on an encrypted procedure verified by the parties involved alone. No more data breaches, hacks, password leaks, or any other risk affecting existing cloud storage solutions.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. DApp development and advancement - In order to build an exceptional user experience our team would be needing to hire additional designers. Currently the development work is being handled by just the two of us and we would like to add more developers to our team.
2. Enable P2P trading on the platform - We are building a OTC (Over the counter) trading platform where trading between two Swishh users can happen using an intermediately Smart Contract. The Grant can help us get these smart-contracts audited.

### 4. Is this project open source?

MIT Licensed & Open Source.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes we agree

### 6. Does your proposal comply with our Community Code of Conduct?

Yes it does

### 7. Links and submissions

- If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

### Additional questions:

- For each team member(s), please list name, email, Github account, and role in the project.

Divyank V.
app.swishh@gmail.com
[Github](https://github.com/swishh-p2p)
Founder / Back End Developer

---

Alice F.
alicefisher97@gmail.com
[Github](https://github.com/alicescript)
UX Designer + Front End Developer

- How did you learn about our microgrant program?
Twitter

**Comment by ErinOCon** [comment]
Hi @swishh-p2p, thank you for your proposal! Since a working prototype is a key criteria point for the microgrants program, we will not be moving forward with a grant for this project at this time. Please feel welcome to re-aoply once your prototype is complete.
