### ISSUE TITLE
Next Step Microgrant Application: Lush - Climate Data 

### ISSUE THREAD

**Issue by lush-data** [filecoin-project/devgrants#783]
### 1. What is your project? (max 100 words)
With Lush we envision an IPFS/Filecoin-based file management app for collecting and sharing climate data, and then go a step further to help organise and visualise the data for the end consumer, which can be Green Tech companies or Web3 DAO's and to To develop GHG (Green House Gases) toolkit to prioritize, engage and drive emissions reductions to help meet companies their goals.

https://github.com/lush-data/lush-data

![image](https://user-images.githubusercontent.com/109896515/180645919-b833af8f-f40e-49f9-9cd1-9d63406fc219.png)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

IPFS is the backbone to hosting of transparent and decentralized climate data
We also help our clients use IPFS for optimising queries and help them visualize data in a structured and procedural way

The go-server runs a GRPC/API client, which will listen to and update the **_IPFS_** data storage with the most up-to-date information, available from various sources like IoT Endpoints or National Electricity Grid

We will be utilising IPFS for storing file archives and generate hash for references.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
a) - This grant will fund the many community outreach programs we have planned to reach & onboard Green NGO's & Communities fighting for a greener planet along with college outreach programs to build a community which supports this green initiative.

b) - I am the sole developer working on this project and I intend to hire developers & designers to support the development roadmap of this project. This grant will allow me to work on a dashboard to asses climate data with the help of User Interface designers.

d) To develop GHG (Green House Gases) toolkit to prioritize, engage and drive emissions reductions to help meet companies their goals.

### 4. Is this project open source?
MIT License (Open Source)

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
YES
  
### 6. Does your proposal comply with our Community Code of Conduct?
YES

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:

Name - Sushma S.
Github - https://github.com/lush-data
Email - sushma.lush@gmail.com
Role - Founder & Lead Developer

* How did you learn about our microgrant program?
* Filecoin Website

**Comment by ErinOCon** [comment]
Hi @lush-data, thank you for the update! Do you plan to store on IPFS directly or use a specific service?

**Comment by lush-data** [comment]
Hi @ErinOCon Thank you for your question. We are using, Tablelands SQL from IPFS for storing and retrieving our data.

**Comment by ErinOCon** [comment]
Hi @lush-data, this grant has been approved! We will be in touch by email to confirm payment details.

The final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please reach out with any question!

**Comment by lush-data** [comment]
> Hi @lush-data, this grant has been approved! We will be in touch by email to confirm payment details.
> 
> The final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please reach out with any question!

Good evening Erin! We will submit the grant report soon
Currently we are done with 2/3 tasks.
Thank you for your patience
