### ISSUE TITLE
Next Step Microgrant: Wordpress IPFS

### ISSUE THREAD

**Issue by blockrocknix** [filecoin-project/devgrants#784]
### 1. What is your project? (max 100 words)

Wordpress IPFS will be a Wordpress plugin that allows a website developed with Wordpress to be instantly converted to a static site and then sent to IPFS Pinning Services (eg. Infura). When something new is added to the content of the site developed with Wordpress, the plugin will automatically create the Static page and send it to the pinning services.

You can see the Github link of the plugin, which is still under development, here:

https://github.com/blockrocknix/Wordpress-IPFS

Also, once completed, it will be released on the Wordpress Market for free forever.

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

In this project, static pages will be stored in IPFS. Plugin user needs to work with IPFS pinning services like Infura.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

For the development and testing environment of the plugin, I will need to set up Wordpress sites in dozens of different domains, and I may have to pay IPFS pinning services to test the publication of the content.

### 4. Is this project open source?

Yes, GNU General Public License. 
### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  Yes
### 6. Does your proposal comply with our Community Code of Conduct?

Yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Mauri Lehtola
blockrocknix@gmail.com

* How did you learn about our microgrant program?
Search Engine
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @blockrocknix, this grant has been approved! We will send an email to confirm payment details.
