### ISSUE TITLE
NoCodeClarity

### ISSUE THREAD

**Issue by nocodeclarity** [filecoin-project/devgrants#785]
# Open Grant Proposal: `NoCodeClarity`

**NoCodeClarity**

**Proposal Category:** `integration-adoption`

**Proposer:** `NoCodeClarity`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes.

# Project Description

NoCodeClarity is building the bridge between NoCode and the wonderful world of Web3. We aim to build NoCode tooling for Filecoin that would empower non-technical users to do amazing things that directly interact with IPFS in a powerful way. From plugins to templates, NoCodeClarity is interested in opening the door for dreamers to build Filecoin dapps leveraging NoCode technology. Mass adoption is a multi-chain effort. NoCodeClarity is focused on bringing security, speed, and scalability to the masses through NoCode technology. We are passionate about Web3 and we know that making IPFS more accessible to people who have ideas to build on it via NoCode tools will allow for great adoption to take place. 

## Value

NoCodeClarity is creating an access point via a plugin that will allow users to create dapps leveraging IPFS and NoCode platforms. The execution and development are where the complexity comes into play as NoCode platforms do not natively support blockchains but we are the team to make it happen. We have created plugins in the past and can do so with Filecoin. We have discovered that along with the plugins, it's helpful to create an environment that allows for the plugin to flourish so along with the plugin, we will be creating templates to aid newcomers to NoCode development or Web3 development. Lastly, we will provide educational tutorials that empower users to build with confidence. As we build for audiences using Bubble and WebFlow, we know that the timeframe needed to build everything will require our team to work for the timeframe of 4 months. In order for adoption to happen, access points must be created and then made visible. With this said, NoCodeClarity leads with education and this is where adoption, as well as the public good, is directly part of our DNA. For anything we launch, we have step-by-step tutorials and we engage with our audience. Marketing and branding NoCodeClarity is one thing but inspiring a community of non-technical people who have ideas to be able to build something is the aim. Empowering technical builders to create MVPs quicker is a great benefit as well due to Red Hat coming out with a statistic on NoCode technology. NoCode tech cuts development time by 90% which means MVPs and public betas can enter the hands of users for testing at a rapid pace. 

## Deliverables

Our aim is to create two high-powered plugins on Bubble and WebFlow that will allow people to create dapps leveraging IPFS. Along with this, we will create two templates for people to have a headstart on dapp UI/UX. The templates are important because what the industry is most known for lacking is the UI/UX piece. Our templates can give people a great framework. We have a working prototype that leverages a plugin that we have started working on which is available here. It is responsive and even works on mobile! 

We will also educate people on how to create dapps that use IPFS. In the crypto space, some agencies are building NoCode tools for blockchains but not many have done so successfully. We look at success through the metrics of impact, education, and onboarding of people who are neither Web3-centric nor programming oriented. NoCodeClarity is able to impact both parties and with our connections to institutions such as Miami Dade College, we have a direct pulse on what our users need via swift feedback. 

## Development Roadmap

- Research & Development: Bubble + WebFlow 
- Deliverables: Fine-tune our prototypes as well as create and finalize the plugin and template.  We will be spending this time assessing if their are bugs in the code or anything that will disrupt users as they create dapps. 
- Staff: 2.
-  Cost: $25,000 
- Time: 4 weeks.

- Launching the Free NoCode Plugins + Free NoCode Templates
-  Deliverables: Launch and educate people on the power of IPFS in tandem with NoCode.  As we have to educate the world about Web3, more times than not we have to educate the Web3 world about NoCode. This will be an exciting time but also a time where we educate through tutorials and video content. 
- Staff: 2.
-  Cost: $25,000 
- Time: 4 weeks.

## Total Budget Requested

- The total budget is $50,000 and it will be used to cover working hours and allows for the development to be completed in 8 weeks. 

## Maintenance and Upgrade Plans

Maintenance and updating are part of the process. We are committed to the vision of creating a suite of access points for people all over the world to create dapps through NoCode. Beyond a project, we are aiming to build a company but the process of grants allows for us to create free tools for the community while providing new value. Also, it’s a mechanism of accountability where we have to provide only the most up-to-date version of everything. The people make everything so we have to serve the people’s needs. 

# Team

## Team Members

Name: Christopher Perceptions
Email: [christopher@nocodeclarity.com](mailto:christopher@nocodeclarity.com), 
GitHub: https://github.com/nocodeclarity 
LinkedIn: https://www.linkedin.com/in/perceptform/ 
Role: NoCode Strategist  

Name: Sergio Gongora
Email: [Sergio@nocodeclarity.com](mailto:Sergio@nocodeclarity.com)
GitHub: https://github.com/segongora 
LinkedIn: https://www.linkedin.com/in/segongora/ 
Role: NoCode Developer

## Team Website

https://www.NoCodeClarity.com

## Relevant Experience

I have a personal history with No Code as I was one of a few chosen from a national pool of applicants to be a Bubble Immerse Cohort founder. This armed me with a great experience with Bubble and showed me its power as well as its potential. I have been in the cryptocurrency space since mid-2016 and have committed myself to this industry as I know it has the power to change lives. As an African American founder with a Hispanic co-founder as CTO, I understand more than many why cryptocurrency and blockchain technology as a whole need to be accessible on all levels. Along with this, Sergio Gongora, my co-founder, is a prolific developer with over 3+ years, several developed projects, and complex problem-solving plugins with different features such as API, elements, and actions (both server and local side). With a strong passion for resolving complex problems in a no-code environment. In the last 5 years, Sergio has developed over 25 projects and plugins in Bubble. He is an experienced web developer with over 5+ years of doing several projects with different tools such as traditional code (HTML, CSS, JavaScript), WordPress, and Bubble.io. In WordPress, he has experience with building informative and e-commerce websites. NoCodeClarity has received a $100,000 grant from the Stacks Foundation to build a vast suite of NoCode tooling for developers interested in the Stacks ecosystem that will be accessible to over 10M people. With the support of Filecoin through this grant application, we believe that NoCodeClarity can place IPFS in front of 3M+ people. We understand that the world is going to exist with multi-chains and we want to create opportunities for all interested in Filecoin with the power of being able to build with NoCode. We aim to have this grant serve as the beginning of a long-term partnership with Filecoin. 

## Team code repositories

NoCodeClarity's GitHub: https://github.com/nocodeclarity 

Sergio's GitHub: https://github.com/segongora (Our first plugin was deployed automatically through his GitHub. This is the first plugin that we've created through the support of the Stacks Foundation: https://bubble.io/plugin/the-stacks-plug-in-1645467277638x949839693014368300) 

# Additional Information

As we developed the prototype, we learned of the grant opportunity. We are accessible via email at contact@nocodeclarity.com. 

Thank you for the opportunity!

**Comment by ErinOCon** [comment]
Hi @nocodeclarity, thank you for your proposal! This grant has been approved! We will send an email to discuss next steps for this grant.
