### ISSUE TITLE
web2 to web3 social media  integration 

### ISSUE THREAD

**Issue by bolajiscott** [filecoin-project/devgrants#788]
### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
Our project architecture will be dealing with tons of data which will require a decentralized storage. More reason we have deceided to make use of ipfs to catch most of the data we will be handling as a tier during and after authentication. we will be testing over diffrent networks , this make it seem like a good fit for our project to start usage with.
  
### 7. Links and submissions
yes
  
### Additional questions:
* * Team Members
Name : Azeez Mumeen
Email: azeezmumeen6@gmail.com
Github: https://github.com/mum33n
Role on project: Full stack /smart contract developer 

Name : Bolaji Ogidan
Email: bolajiscott@yahoo.com
Github: https:github.com/bolajiscott
Role on project : Front-end developer/ Tester
* How did you learn about our microgrant program?
     devpost community

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (Tron Dao)
  * https://hackathon-mum33n.vercel.app/

**Comment by ErinOCon** [comment]
Hi @bolajiscott, I have closed this Issue item. Please feel welcome to re-apply with a complete application.
