### ISSUE TITLE
Next Step Microgrant: iNFT

### ISSUE THREAD

**Issue by aaden-v2** [filecoin-project/devgrants#789]
### 1. What is your project? (max 100 words)
iNFT is a decentralized ad delivery sub-system for any platform in web3.
Any web3 platform can incentivise their user base using iNFT, with the due permission of their user (using https://eips.ethereum.org/EIPS/eip-712 signatures)

Any web3 platform can use iNFT to open a stream of revenue by helping other projects advertise through them. We named the project iNFT as we are just an interface (`i` in iNFT)
All ads will be delivered using NFT's minted on the platform, and stored on IPFS using NFT.storage
Measures like wallet detections and signature hashing, prevent spams to users using the ad Platform
A detailed overview with a diagram is given in the Readme file of the repository

### 2. **_Project links_**
https://github.com/aaden-v2/iNFT

**_Protoype_**

![image](https://user-images.githubusercontent.com/110059780/187666260-3c0c6136-2a1c-4f45-8ec0-ad52d798ca76.png)

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  
NFT.storage is used to mint and store NFT's. User's can claim the earned NFT's on the same portal while, blacklisting any companies. This blacklist/whitelist information is stored on IPFS via tablelands database

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

This project started out in college with my partner Aaliyah Mariyam and we are looking to use this grant to support ourselves to build this out further.
We have started to build a DAO to help us maintain and develop this project and take it to the next level. We are a community of 52 users/developers now. We are using this opportunity to bring web3 awareness in our college as well 

We also are also looking to get our smart contracts audited soon

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Aaden George (gogoaaden@gmail.com) Lead smart contract and backend developer 
Aaliyah Mariyam (aali.mariyam.96@gmail.com)  Lead frontend developer
* How did you learn about our microgrant program? Github
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @aaden-v2, thank you for your proposal! Can you provide a detailed breakdown of the next steps you will take to improve your project over the next three months?

**Comment by ErinOCon** [comment]
Hi @aaden-v2, thank you for checking in. This is an interesting project! Can you briefly speak to how the developments of this project will be a value add for web3 platform users?

**Comment by aali-mariyam** [comment]
Hi @ErinOCon I'm Aaliyah, the lead frontend developer for iNFT.
There are 3 major advantages for web3 companies who implement iNFT on their platforms
1. *Lower Cost* - As we all know, ads in web2 cost a lot. But using iNFT, depending on the chain you deploy the iNFT smart-contract on, your CPM will be significantly lower as it's based on the gas fees of the EVM chain you are using. Using chains like AVAX, BSC or Polygon, it can be 10 - 20x lesser
2. *Verifiable Results* - On web2, your audience are hidden from you as the ad display platforms with-hold information. But with iNFT is permissionless, all your audience is visible from the get go
3. *Easier Targeting* - It's easier to target people who own a particular collection of NFT's as the audience and serve them. This along with our user-side implementation of signature hashing, enables permissionless spam-prevention 

Thank you

**Comment by ErinOCon** [comment]
Hi @aaden-v2, this microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by aali-mariyam** [comment]
Thank you @ErinOCon . We will work our best and submit the form as soon as possible.
