### ISSUE TITLE
MintFlick - Social Media & NFT Marketplace powered by IPFS & Livepeer

### ISSUE THREAD

**Issue by Rishikeshk9** [filecoin-project/devgrants#791]
# Open Grant Proposal: `MintFlick`

![Mintflick-17 (1) (1)](https://user-images.githubusercontent.com/36479949/180735359-8418aa76-03d9-4fd5-b782-01b4535fde13.png)

**Name of Project:** `MintFlick`

**Proposal Category:**`community`,`metaverse`

**Proposer:** `rishikeshk9`

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** `Yes`

# Project Description

### MintFlick Introduction Video :

For a better experience listen with Audio 🔊

https://user-images.githubusercontent.com/36479949/181241321-dbab7d09-f124-4dea-91fa-b86fe24b36c6.mp4

MintFlick is a decentralized Social media & NFT marketplace on Blockchain
for Creators, Game Streamers, Bloggers, Music Artists and everyone else. We
are building a decentralized community where users can mint NFTs of their
videos, create NFTs during Live streams or post photos and make it an NFT.

During a Livestream a short video of the stream can be recorded and then it can be minted as an NFT without stopping the livestream.
Audience watching the Livestream can buy this NFT on the platform itself.

Creators can set up royalties for every secondary sale. Creators can also
earn royalties on every sale. This ensures a source of passive income for
original Creators.
MintFlick is a decentralized social media that lets people to flawlessly
convey their content. Just simply envision a video, blog post, music, pictures
and the platform then will store your contents in decentral and safe public
storage; Creators can choose if they have any desire to keep their music,
videos, pictures and other contents private or sell them in return for any
ERC20 tokens.

MintFlick is a community driven platform created with the creator’s wellbeing on a basic level.

MintFlick is built on blockchain which makes it transparent & reliable.
We believe in the right to speak freely of discourse with least restriction.
We believe in the development of decentralization and its advantages.

### Why did we pick this idea?

The idea of selling digital content like pictures or written text on sole content-only marketplaces like Opensea is quite old-school.
If someone is buying a piece of art or any form of Digital content and wants the backstory to his/her purchase, social media has all the elements of providing the backstories, so why not design a marketplace where the creators would interact, build a community around their social posts & sell those posts as NFTs. And also the creator has all the rights to choose what content will be an NFT & he can earn royalties if someone secondary sells his content to a third person with the use of Blockchain. This idea seems like the next big thing which excited me as a founder, many more expansions like VR/ARs can come into play as content creators slowly start experimenting with the platform. Creating NFTs from/while Livestreaming a concert was never done before & MintFlick lets you do that, this is when I thought I want to make this big & then connected with a co-founder & formed a team to work on this idea.

### What problem is MintFlick solving?

MintFlick is built focusing on the growing creators' economy it value adds to the existing ecosystem of Livestreaming & Content Marketplace through its uniquely designed Social Media styled marketplace feed. Artists were forced to sell their NFTs on Opensea & many other markets without any community being formed around the projects but with MintFlick artists, Influencers, Bloggers, Photographers, and Video content creators & everyone else has a platform to create a community, and then sell those content as NFTs among the community. Also, interact with the audience & go Livestream on the platform.

## Value

![LinkedIn cover2](https://user-images.githubusercontent.com/36479949/181236992-20c468e2-8246-4d3b-9303-f18bfdb2d2da.png)

#### Platform Independent Content

Content has to be stored on decentralised storage like IPFS instead of central storage units.

#### Royalty

Original Creators should get royalties from content sales, enabling a passive income source.

#### Perks

Incentivize creators with platform tokens($FLICK) for posting & moderating content. Signature of content moderator can be verified on blockchain.

#### Moderation

Moderated content can carry more value & authenticity. Creators who regularly moderate or create content can apply for account verification which will be decided by voters through community governance.

### 🥺 Risks if we don't get it right :

Risks involve in developing a social media platform on top of Blockchain is the same as developing a social media platform on top of centralized storage.

Creator's content can be duplicated on the platform and can be sold to third parties, for which the community moderation infrastructure needs to be robust and well tested.

### 🧛‍♂️Risks that will make executing on this project difficult?

Building the right mechanism design to incentivise participants – from creators to users to community participants.

A robust and well tested moderation infrastructure is required to ensure that the content is unique and relevant.

## Deliverables

A single platform for content creators to sell their content either as NFTs or like any other digital goods.

Low Level System Architecture :
![MintFlick Architecture](https://user-images.githubusercontent.com/36479949/181234792-b0b286b4-b565-401f-9f09-2303a3859c46.png)

Planned UI for the platform ⬇️

<a href="https://www.figma.com/file/wDG6PIWGdVQxeKm9Gjb2Cs/Mintflick-app?node-id=697%3A1007">🌐 Figma Link</a>

Feed - Social Media

![image](https://user-images.githubusercontent.com/36479949/180779215-c75413f0-a497-4be3-ac56-f817640c0abf.png)

Livestream
![image](https://user-images.githubusercontent.com/36479949/180991925-b6ac2c69-61c3-44c2-9ccc-56e239b06a7a.png)

Token Gated - Content
![image](https://user-images.githubusercontent.com/36479949/180991785-414d1165-bc34-4fd9-b8c2-79ac20b32dc8.png)

## Development Roadmap

Landing Page : https://mintflick.network

The MVP of the Platform is live on https://beta.mintflick.app

MintFlick Whitepaper : https://drive.google.com/file/d/1DX_xNBrjQomUFf5VtmxSxpaAgDhszUnw/view?usp=sharing

MintFlick Brand Guidelines : https://drive.google.com/file/d/1hmOJx1ETvz5mJ-RvUwIuGdFxsOB-M6YS/view?usp=sharing

Following Milestones are planned for the upcoming months:

### `Milestone 1` : 30/08/2022

Web app - accessible from anywhere & mobile friendly

- Developing the Social Feed which contains the content created by the creator. The Feed will contain `Music, Videos, Pictures` & `Text` whether/not NFT.
- Users can interact with the Feed and `Buy/Bid` for content.

* `Likes, Comments, Shares, Report` will be available for the content. This will enable the creator to get more value from the content. The content will be moderated by the community.

* Community Channels - A section where Creator can interact with the `Community`.

- Superfans - A Web3 `OnlyFans` spin-off of the platform. Audience can subscribe to the Creators and get exclusive Superfans only perks tailored custom by the Creator.
  Planned UI ⬇️
  ![image](https://user-images.githubusercontent.com/36479949/181255332-1f068f78-f274-4f51-b1eb-7f9f82098220.png)

- Livestreaming - MintFlick will be built on top of `Livepeer`. The Livestreaming will be decoded over Livepeer's Decentralized nodes where the content will be broadcasted to the audience.

### `Milestone 2` : 30/10/2022

Native Mobile App - iOS & Android

- An in-app wallet integrated for smooth user experience. The complete platform will be available for users on handheld devices.
- The app will be available on both iOS & Android.

- Mobile version will use the common Web Backend for the app.

* In-app notifications & better way for accessing the platform will bring new users on the app.

### `Milestone 3` : 31/12/2022

Native Integration with VR devices - Oculus, Samsung, Google, etc.

- The platform will be available on VR devices.

- With the VR integration, the team aims on onboarding VR users to the platform.

* One of the key features of the VR integration is the ability to interact with the platform from VR. This will make the platform an one-stop solution for creators to create, sell & Market their content in VR.

### 🎉Partnering with Creators & organising small community events for creators on MintFlick will be ran parallely with the product building during all 3 milestones.

This will help us gather user feedbacks & ideas to build and fine tune the platform.

## Total Budget Requested

| Resources          | Milestone 1 | Milestone 2 | Milestone 3 | Total    |
| ------------------ | ----------- | ----------- | ----------- | -------- |
| Backend Devs       | $10,000     | $10,000     | $10,000     | $30,000  |
| Frontend Devs      | $10,000     | $10,000     | $10,000     | $30,000  |
| Blockchain Devs    | $10,000     | $5,000      | $5,000      | $20,000  |
| Mobile Devs        | $5,000      | $5,000      | $5,000      | $15,000  |
| UX Designers       | $5,000      | $5,000      | $5,000      | $15,000  |
| Graphics Designers | $5,000      | $5,000      | $5,000      | $15,000  |
| Total              | $45,000     | $40,000     | $40,000     | $125,000 |

## Maintenance and Upgrade Plans

The platform will be maintained and upgraded regularly. As we have been working on the platform, we have learned that there are some areas that need to be improved.

We are building for the future & we want to be future-ready when it arrives, hence we will be planning for the following:

- Setting up a community Feedback System - This will enable the community to interact with the team and get feedbacks from the users.

* A community Manager role will be opened up which will help users with any Technical or non-Technical issues.

# Team

## Team Members

- <a href="https://www.linkedin.com/in/rushikeshkardile/">Rushikesh Kardile</a> - Founder & CEO

* <a href="https://www.linkedin.com/in/aniket-tandale-34b01510b/">Aniket Tandale</a> - Co-Founder & Chief Operations Officer

* <a href="https://www.linkedin.com/in/digvijay-dhamale/">Digvijay Dhamale</a> - Chief Product Officer

- <a href="https://www.linkedin.com/in/sahil-punjabi-884a811b0/">Sahil Panjabi</a> - Member of Technical Staff

* <a href="https://www.linkedin.com/in/prasad-karmalkar-517380165/">Prasad Karmalkar</a> - Backend Developer

- <a href="https://www.linkedin.com/in/sahil-shingate-909aa01b0/">Sahil Shingate</a> - Full Stack Developer

* <a href="https://www.linkedin.com/in/hande-abhishek/">Abhishek Hande</a> - DevOps Engineer

- <a href="https://www.behance.net/harshchavan">Harsh Chavan</a> - UI/UX Designer

* <a href="https://www.behance.net/saurabhdalcef3">Saurabh Dalvi </a> - Graphics Designer & Illustrator

## Relevant Experience

Rushikesh Kardile - Has an Engineering Degree in Information Technology from the University of Pune. He has worked on various projects in the past with clienteles from 5 continents. Has been featured in <a href="https://www.linkedin.com/feed/update/urn:li:activity:6803614444564938752/">TEOI</a>.
Started a IT services company in 2019 which was Recognised by the Government of India under DPIIT Startup India. Has spearheaded the development of MintFlick.

Aniket Tandale - Has an MBA in Operations, have successfully done a stint as a Business Analyst at a MNC in the past. He brilliantly saved millions of Dollars for the company through excellent inventory planning & smooth operations. Has spearheaded the Resource Management for MintFlick Development.

Digvijay Dhamale -
bbw Hochschule
M.Sc, Industrial Engineering , Product & Innovation Management | Project Management | Information and Communication Technologies  
He is an excellent Product Manager with a strong background in Product Development.

## Team code repositories

https://github.com/supersapiensdevlab/Mintflick-webapp

https://github.com/Rishikeshk9/warp-frontend

https://github.com/Rishikeshk9/vada

# Additional Information

**Comment by ErinOCon** [comment]
Hi @Rishikeshk9, thank you for submitting this proposal! Can you provide more information on how your project will gain traction/grow its user base?

**Comment by Rishikeshk9** [comment]
Hi @ErinOCon  Thanks for checking in.

I have updated the plan & programs the team has decided on carrying forward for onboarding the first 1M users.
https://docs.google.com/document/d/1mrG4hCXJtnWB-sHniWM7ZqNRA1oe60nmqmGozHAP_w0/edit?usp=sharing

**Screenshot from the Link** :
![image](https://user-images.githubusercontent.com/36479949/183263373-02a05032-1318-41d0-ba74-4a7de7d8c49c.png)

MintFlick Instagram : https://www.instagram.com/mintflick.app
Discord :  @https://discord.com/invite/xZavZyAbx4

**Comment by Rohanrex** [comment]
Crazy concept/something out of the box ❤️

**Comment by ErinOCon** [comment]
Hi @Rishikeshk9, thank you again for your proposal! We will not be moving forward with a grant for this project at this time. Once your project has progressed further and has grown a larger user base, please feel welcome to re-apply. Wishing you the best with this project!
