### ISSUE TITLE
Next Step Microgrant : RLTS

### ISSUE THREAD

**Issue by rltsonweb3** [filecoin-project/devgrants#792]
### 1. What is your project? (max 100 words)
We are the Red List of Threatened Species built on IPFS/Filecoin, and will use NFT technology and on-chain data proof to complete a permanent and permanent world ecology built on IPFS/Filecoin . 
From https://www.iucnredlist.org/, over 41,000 species are now facing extinction, but this is still 28% of all assessed species.
Even on the most authoritative iucnredlist, there are still many species without very detailed data, and we have to worry about the loss of data for each species, etc.
In order to increase the level of detail of species data, and to maintain species data, we choose to use IPFS/Filecoin to store all species data.
At the same time, DAO will also be used to establish a world species protection organization to support activities such as world species protection, and will also provide tools such as NFT to complete the sponsorship of world species-related organizations

### 2. Project links
We now have the species data crawler program, and the species data is saved to the IPFS/Filecoin program.
and now we are building website code and API to provide species datas.

Link to Github repo:
https://github.com/rltsonweb3/rlts

Link to demo or website, if applicable:
not yet ,

yes , we are in MIT
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
IPFS/Filecoin will be the storage choice for all species data in our project. In order to ensure the reliability of the data, in addition to the default NFT.Storage platform, we will also pin the data through a third-party sdk .
In our crawler processing program, we build the species information into a NFT-compliant uri through nft.storage and write back the species database.
 In the front-end program, users can select the corresponding species to assist in uploading the species data to IPFS/Filecoin through nft.storage, or select the corresponding species to upload the data they are looking for to IPFS/F through nft.storage

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We now have more than 70k species information , you can find here (https://github.com/rltsonweb3/rlts/blob/main/rlts_data.csv) , 
Among them, we have already saved more than 800 pieces of data to IPFS/Filecoin (You can view it in the cid column of the table).

We will use this grant to accomplish several things:
1:    building front website to show all species data 
2:    Construct donation contracts for species, all contracts are made public, and all funds are made public.
3:    Add the function of creating NFT for each species, this NFT cannot be sold, all NFT mint funds will be used as DAO treasury funds
4:    Establish an initial DAO, connect with the World Species Conservation Organization, and specify treasury funding rules

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
   xiaoxiao , rltsonweb3@outlook.com , https://github.com/rltsonweb3 . building meaningful project in web3 by IPFS/Filecoin

* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @rltsonweb3, thank you for your proposal! It looks like [this link](https://github.com/rltsonweb3/rlts/blob/main/rlts_data.csv) cannot show the stored files. Can this be updated? Also, can you confirm that the work for this project will be ooen source?

**Comment by rltsonweb3** [comment]
> Hi @rltsonweb3, thank you for your proposal! It looks like [this link](https://github.com/rltsonweb3/rlts/blob/main/rlts_data.csv) cannot show the stored files. Can this be updated? Also, can you confirm that the work for this project will be ooen source?

Hi @ErinOCon , This data format github cannot be loaded automatically, I will update a file for you, in addition, all of these are open source

**Comment by rltsonweb3** [comment]
> > Hi @rltsonweb3, thank you for your proposal! It looks like [this link](https://github.com/rltsonweb3/rlts/blob/main/rlts_data.csv) cannot show the stored files. Can this be updated? Also, can you confirm that the work for this project will be ooen source?
> 
> Hi @ErinOCon , This data format github cannot be loaded automatically, I will update a file for you, in addition, all of these are open source

Hi @ErinOCon , In order for you to better view the data, I uploaded documents in two data formats through nft.storage, one is pdf, which is convenient for you to open and browse directly, and the other is csv, which you can download and view

1:  https://bafybeihmgfuk5vqwtyn3r7seaaxxhepidvk2tn3cxpg3iefiweqw6hfjnm.ipfs.nftstorage.link/   , (pdf)
2:  https://bafybeig4ep53w4nhjnq4ng2ch5sm52cc3taqwl4gglrvxusslnffhhxva4.ipfs.nftstorage.link/,   (csv)

If there is an ipfs path in the last field, it means that the biological information has been stored in ipfs/Filecoin through nft.storage

**Comment by ErinOCon** [comment]
Hi @rltsonweb3, thank you for the quick reply! Can you confirm how you are affiliated with RLTS (i.e. an individual contributor outside the organization, a member on the development team, etc.) Also, can you complete a [Read Me](https://www.makeareadme.com/) on your Github?

**Comment by rltsonweb3** [comment]
> Hi @rltsonweb3, thank you for the quick reply! Can you confirm how you are affiliated with RLTS (i.e. an individual contributor outside the organization, a member on the development team, etc.) Also, can you complete a [Read Me](https://www.makeareadme.com/) on your Github?

hi @ErinOCon. In fact, I am very concerned about this grant, and grant can help me find helpers to complete this project.
I have nothing to do with RLTS, just an ordinary web3 resident who wants to make some personal contributions to the ecology.
I just updated the readme of the project and will update it at any time as the project progresses.
If you have some suggestions, I will be very happy, because I hope more volunteers can join here to build the world's ecological species conservation through web3.

**Comment by rltsonweb3** [comment]
> > Hi @rltsonweb3, thank you for the quick reply! Can you confirm how you are affiliated with RLTS (i.e. an individual contributor outside the organization, a member on the development team, etc.) Also, can you complete a [Read Me](https://www.makeareadme.com/) on your Github?
> 
> hi @ErinOCon. In fact, I am very concerned about this grant, and grant can help me find helpers to complete this project. I have nothing to do with RLTS, just an ordinary web3 resident who wants to make some personal contributions to the ecology. I just updated the readme of the project and will update it at any time as the project progresses. If you have some suggestions, I will be very happy, because I hope more volunteers can join here to build the world's ecological species conservation through web3.

By the way, it is really heartbreaking to see the news of the extinction of species. There is one less friend of mankind.

**Comment by rltsonweb3** [comment]
> Hi @rltsonweb3, thank you for the quick reply! Can you confirm how you are affiliated with RLTS (i.e. an individual contributor outside the organization, a member on the development team, etc.) Also, can you complete a [Read Me](https://www.makeareadme.com/) on your Github?

Hi @ErinOCon , sorry for misunderstanding, i have created ReadMe on github

**Comment by rltsonweb3** [comment]
> > Hi @rltsonweb3, thank you for the quick reply! Can you confirm how you are affiliated with RLTS (i.e. an individual contributor outside the organization, a member on the development team, etc.) Also, can you complete a [Read Me](https://www.makeareadme.com/) on your Github?
> 
> Hi @ErinOCon , sorry for misunderstanding, I have created ReadMe on github . here is link:https://github.com/rltsonweb3/rltsonweb3/blob/main/README.md

Hi @ErinOCon ,We will also update the project progress and our construction status at any time in REAMDE .

**Comment by rltsonweb3** [comment]
Hi @ErinOCon ，Are there any new process regarding this grant or other issues ?

**Comment by rltsonweb3** [comment]
@ErinOCon , Update the progress, the program will die by constantly calling nft.storage . We are considering implementing concurrent operations of data processing based on golang (maybe still using node.js) .
Also, we are looking for a way to sync all the data in the form of documents, although github can also view the data, but the visualization is not very good. If you have good suggestions, you can also tell us .
We will also follow up the communication with RLTS so that it can support us to permanently store data on IPFS/Filecoin

**Comment by rltsonweb3** [comment]
Hi ! @ErinOCon . When we sorted out the data, we found that a lot of ecological data did not have pictures (these data are all from https://www.iucnredlist.org/). After our internal discussions, we determined the future development route. 
We will build an ecological protection DAO. At present, DAO mainly has the following tasks
1: Complete the existing data with missing images.
2: Add image data to existing ecological species data

In addition, the website is under development. We will use Next.js as the web page structure. The first functions are as follows:
1: Display data according to different endangered types
2: Species data completion function (based on IPFS/Filecoin storage)
3: Species data added function (based on IPFS/Filecoin storage)

This is an open project, and the permanent preservation of ecological data is a great collaboration between IPFS/Filecoin.

**Comment by rltsonweb3** [comment]
Update demo website: https://rlts1.vercel.app/.
Next : 
1: Database interface implementation
2: Ecological Species List Page
3: Ecological species uploaded to IPFS/Filecoin via nft.storage (data not uploaded via script will be displayed)
4: Ecological Species details page & Complete ecological data function

**Comment by rltsonweb3** [comment]
Hi @ErinOCon . I would like to know if there is an update, and also, I would like to ask if this meaningful thing can be supported by Filecoin, do I need to contact rlts first?

**Comment by ErinOCon** [comment]
Hi @rltsonweb3, thank you for your patience with our proposal review. This grant has been approved! We have sent an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
