### ISSUE TITLE
Jolocom-Filecoin Integration

### ISSUE THREAD

**Issue by Joachim16** [filecoin-project/devgrants#793]
# Open Grant Proposal: `Jolocom-Filecoin Integration`

**Name of Project:** Jolocom-Filecoin Integration

**Proposal Category:** `integration-adoption` 

**Proposer:** `github.com/jolocom`

**(Optional) Technical Sponsor:** github.com/realChainLife

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** 
"Yes"

# Project Description

Storage is a fundamental part of the SSI (Self-soverein Identity) world. SSI software and systems need to store a wide range of data in a reliable and sometimes publicly accessible way. 
Managing the storage of personal information is not just technically but also legally challenging. More specifically, identity information must be GDPR compliant, and that imposes heavy limitations in how and where this data can be stored. These technical and specially these legal hurdles have made the use of distributed networks with SSI a complicated, sometimes impossible task. 
Filecoin however is developing a new way to store and manage data in a distributed network using its Filecoin VM (FVM). The FVM not only opens an unlimited number of ways to deal with data but also it potentially allows us to bring the SSI world to a distributed world in a GDPR compliant way. 
It is for this reason that we at Jolocom would like to explore a number of different applications for the Filecoin FVM in the SSI world. 
Should our technical and legal research return positive results, we intend to expand the prototype into an MVP that would be integrated with our Identity SDK2 and our Identity Agent. 

## Value
What are the benefits to getting this right?
For the decentralized world both storage and identity are fundamental and mutually beneficial building blocks, which can significatly spur adoption both technologies together. This will be a great service to the entire Web3/DWeb ecosystem. 
Ensure competitiveness of decentralized, SSI solutions in comparison to existing, federated identity solutions 
Contribute to the maturity of the SSI tech stack 
Increase adoption of both Filecoin VM, as well as Jolocom SSI Tech Stack 

What are the risks if you don't get it right?
While the technical feasibility has partly already been proven, arriving at a production-ready, interoperable implementation is dependent on aspects such as security and external factors, including regulatory compliance, that might adversely influence estimated project planning and time schedules. 

What are the risks that will make executing on this project difficult?
While the SSI approach is gaining in technological maturity, and a first generation of globally accepted standards has been completed, the concept and all technical specifications connected to it are still new and in development. 

All EU citizens must have an identity wallet. We want to ensure that these wallets hold Self Sovereign Identity (SSI) that puts true control back in the people’s hands. 
Currently, the[ German Government Projects](https://jolocom.io/blog/sdi-breakthrough/) are the global epicenter of SSI. With a total of 100M € ($105 million) of government/corporate funding flowing into the creation of a SSI ecosystem for Europe, this is the largest SSI project in the world. Jolocom was chosen to be the SSI solution in 3 out of 4 German projects, generating 40 different SSI use cases by 2024.  
This is a one time opportunity to roll out SSI to every EU citizen, some millions of people. Jolocom is well-positioned to play a large part in the roll out, however we must keep pace to realize the opportunity.

## Deliverables

The goal of the current project would be to explore three different areas where the world of SSI could greatly benefit from the Filecoin VM (and the other way around). 
We will develop a smart contract on the FVM that will store Credential Schemas in a secure and reliable way, for the use with Verifiable Credentials. The contract will accept payments in $FIL and/or a custom token to store said schemas on the Filecoin network. This is required as per specification ([https://w3c-ccg.github.io/vc-json-schemas/v1/index.html#storage](https://w3c-ccg.github.io/vc-json-schemas/v1/index.html%22%20/l%20%22storage)). 
We will explore the technical and legal feasibility of using Filecoin to store Wallet backups. These backups contain all the personal information of the user and are crucial in case their device is lost or damaged. These backups would be encrypted and stored in a GDPR compatible way. We will deliver a document explaining how this could be technically achieved and the potential legal issues we forsee, if any. If possible, a small prototype will be built. 
We will also research the technical and legal feasibility of using Filecoin as a storage for DID documents. These documents should be publicly accessible and contain user data such as their public keys and other metadata. The biggest challenge comes from the Right to be Forgotten (RTBF), and how this can be applied on an immutable network. We believe the Filecoin VM could help us circumvent that limitation. We will deliver a document explaining how this could be achieved and also the potential legal hurdles we forsee, if any.  If possible, a prototype will be built.

## Development Roadmap

**Milestone 0** 
Functionality: 
Implementation of a smart contract that allows and controls the storage of Credential Schemas. 
It should store the Schemas together with their version and metadata.  
It should support updates for the schemas, letting users know which is the latest available version. 
It should charge for the storage and allow for future upgrades of the Schema. 
Number of people: 4 
Funding: approx 73.000 US 
M0.1 35.000 US 
M0.2 38.000 US 
Delivery: time estimate 8 weeks (check point 0.1 after 4 weeks, Aug 31, 2022, check point 0.2 after 8 weeks, Sep 30, 2022) 

**Milestone 1** 
Functionality: 
Investigate the possibility of creating a UI for it using some browser wallet integration such as Metamask with the Filecoin Snap. Deliver a report on the topic. 
Either: 
Implement the UI in a browser using a wallet integration to create a Web3 Filecoin application. 
OR 
Create an HTTP service that implements the storage API and have the UI talk to said service. 
Number of people: 5 
Funding: approx 78.000 US 
M1.1 42.000 US 
M1.2 36.000 US 
Delivery: time estimate 8 weeks (check point 1.1 after 4 weeks, Sep 30, 2022, check point 1.2 after 8 weeks, Oct 31, 2022) 

**Milestone 2** 
Research: 
Using the experience and knowledge acquired during Milestones 0 and 1, explore the possibility of using the FVM to store an encrypted Wallet backup. 
Analyze the legal risks, specially the GDPR compliance and potential issues that may appear there. 
The backup system should allow direct integration with the Jolocom Wallet.  
The backup system should also support some sort of secure recovery mechanism in case the device is lost or broken.  
The backup should also allow the data to be permanently deleted or blocked if the user desires so. 
The system should support a way to pay for the storage, either using $FIL or a custom token. 
If there are no legal and technical hurdles to implement this, build a small prototype, acting as a tech demonstrator. 
Number of people: 5 
Funding: approx 66.000 US 
M2.1 32.000 US 
M2.2 34.000 US 
Delivery: time estimate 6-8 weeks (check point 2.1 after 4 weeks, Oct 31, 2022, check point 2.2 after 8 weeks, Nov 30, 2022) 

**Milestone 3:** 
Research: 
Investigate how to harness the Filecoin VM to store DID documents in a GDPR-compliant way. 
The DID document should be easily and freely accessible. 
The DID document should also be able to be deleted or permanently blocked from the network (to cumply with the RTBF). 
The DID document should be accessible by using some sort of hash or identification string (this would be our DID). 
If the research turns positive results (specially in what is regarding the GDPR compliance), build a draft specification of a DID method using Filecoin as storage, with advanced features such as implementing the RTBF. 
Implement a small prototype of the system described above 
Number of people: 6 
Funding: approx 58.000 US 
M3.1 27.000 
M3.2 31.000 
Delivery: time estimate 8 weeks (check point 3.1 after 4 weeks, Nov 30, 2022, check point 3.2 after 8 weeks, Dec 31, 2022) 
 
**Milestone 4:** 
Functionality: 
Integrate the Credential Schema storage into the Jolocom Identity Agent. 
IF the Backup research returns positive results: 
Expand the Backup prototype and integrate it with the Jolocom SmartWallet. 
Integration into all of Jolocom’s supported platforms (iOS and Android) 
It should allow the user to make the storage payment in a simple way 
It should be able to be retrieved/restored in case of broken or lost device 
IF the DID document storage research returns positive results: 
Expand the prototype to reach an MVP status 
Integrate this DID method into the Jolocom Identity SDK2 
Expand the initial spec and add it to the DID Method Registry 
Number of people: 4 
Funding: approx 73.000 US 
M4.1 31.000 
M4.2 42.000 
Delivery: time estimate 8 weeks (check point 4.1 after 4 weeks, Dec 31, 2022, check point 4.2 after 8 weeks, Jan 31, 2023) 

## Total Budget Requested

TOTAL: USD 348.145  
Cost of Personnel: 333.145 
Senior Software Engineer – 4,5 PM: USD 84.420 
Software Engineer – 7,5 PM: USD 79.875 
Software Developer – 8,75 PM: USD 59.500 
Researcher – 3,5 PM: USD 25.900 
Project Manager – 5,75 PM: USD 37.375 
UI/UX Designer – 1,5 PM: USD 8.700 
Agile Coach / Scrum Master – 5,75 PM: USD 37.375 
Cost of Legal Counsel: USD 15.000,00 

## Maintenance and Upgrade Plans

The software being developed will be upgraded and maintained as part of the Jolocom core stack, and available on github. 

# Team

## Team Members

Senior Software Engineer: Martin Exe Zulliger 
Software Engineer: Eugeniu Rusu, Serhii Temchenko 
Software Developer: Cristian Lungu, Edward Curran 
Partnership Manager/Researcher: Kai Wagner 
Project Manager: Ben Biedermann, Irene Adamski 
UI/UX Designer: Smera Goel 
Agile Coach / Scrum Master: Nicole Bolz 

## Team Website

https://jolocom.io/

## Relevant Experience

Jolocom has been developing open source technology for decentralized identity management for more than 8 years. 
Our work is open source, with our code publicly available on[ GitHub](https://github.com/jolocom) (e.g. our SSI Library, SDK and SSI Wallet). We contribute to[ DIF](https://jolocom.io/blog/jolocoms-contributions-to-dif/) and[ W3C](https://www.w3.org/) (e.g. DID WG, Interoperability Project, Decentralization Rubric, etc.). 
8 years in the SSI ecosystem 
Tech provider in 3 of 4 lighthouse projects by German Ministry of Economic Affairs https://jolocom.io/blog/sdi-breakthrough/ 
Stacks Foundation Grant Alumni.  
Member of various standardization and community bodies (DIF, INATBA, W3C, EUOS/StandICT, VDI, DIN/ISO) - Leadership: DIF steering commitee member, INATBA board member

## Team code repositories

https://github.com/stacksgov/Stacks-Grants/issues/61 
https://github.com/decentralized-identity/keriox/ 
https://github.com/decentralized-identity/didcomm-rs 

# Additional Information
Through Filecoin Foundation 

 joachim@jolocom.com; exe@jolocom.com; irene@jolocom.com

**Comment by ErinOCon** [comment]
Hi @Joachim16, thank you for submitting this proposal! We will be in touch ounce our review is complete.

**Comment by ErinOCon** [comment]
Hi @Joachim16, this item has been closed in anticipation of the new proposal previously discussed. Please be in touch with any questions or updates!
