### ISSUE TITLE
Next Step Microgrant: Filecoin Plus Docs

### ISSUE THREAD

**Issue by AlexxNica** [filecoin-project/devgrants#795]
### 1. What is your project? (max 100 words)

Filecoin Plus Docs is a documentation initiative for the Filecoin Plus ecosystem.

### 2. Project links

Link to Github repo: https://github.com/nikas-org/filecoin-plus-docs
Link to demo or website, if applicable: https://docs.filplus.dev/

### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

Filecoin Plus Docs is directly related to Filecoin as a documentation initiative for the Filecoin Plus program.

#### Milestones:

- Finish set up of the project's core infrastructure (e.g., tooling, analytics, contributor guidelines)
	- [Set up guidelines for repository contributions](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)
	- [Add a code of conduct](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project)
	- [Create issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
	- [Change deployment automation from Vercel to GitHub Pages](https://docusaurus.io/docs/deployment#deploying-to-github-pages)
	- Explore changing analytics from Google to [Matomo](https://matomo.org/) or alternatives
	- Set up automation for linting tools
- Add content about the concepts and processes involved in the Filecoin Plus program
	- Home / Introduction
	- Home / Getting started
	- Glossary
	- Processes & workflows
	- Guides / Become a notary
	- Guides / Become a verified client
	- Guides / Client / Request DataCap
	- Program architecture / General overview
	- Program architecture / Notary election
	- Program architecture / Dispute resolution
	- Program architecture / Program governance
	- FAQs
- Add a list of tools and resources related to Filecoin Plus
	- Resources / APIs
	- Resources / Tools / Dashboards
	- Resources / Related projects
- Coordinate collaboration with ecosystem stakeholders to align on up-to-date documentation
- Community engagement through multiple existing channels (e.g., Slack, Discord, GitHub)
	- Post news, updates, and other announcements

#### Next steps:

- Actively maintain the repository and keep its resources up-to-date
- Plan upgrades & improvements
- Add more content related to Filecoin Plus
- Add a way to easily collect feedback directly on pages
- Set up GitHub Projects
- Set up GitHub Discussions

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions

We've received a lot of support and very positive feedback from the community since the [announcement on Slack](https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1658296802391339) and governance meeting (recordings: [1st session](https://youtu.be/yqPc-0Wd75M?t=2636) & [2nd session](https://youtu.be/yqPc-0Wd75M?t=6223) & [slide deck](https://docs.google.com/presentation/d/1RNecvaa_O4DO8ES2Pwn54a_0bQv6QDRj47P2abGzn60/edit#slide=id.g13699adb539_0_15)).

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
	* Alexandre Nicastro, alexandre.nicastro@nikas.org, @AlexxNica, Founder
* How did you learn about our microgrant program?
	* A long time ago, when exploring the @filecoin-project repositories.
* If your project was created as part of an event or hackathon:
	* *Not applicable.*

**Comment by ErinOCon** [comment]
Hi @AlexxNica, thank you for your proposal! Can you provide more information on how you will improve your project and the next steps you will take? Please include concrete milestone and objectives - the more details the better!

**Comment by AlexxNica** [comment]
Hey there, @ErinOCon! I've updated the issue with the additional info! Can you review? 🙌

**Comment by ErinOCon** [comment]
Hi @AlexxNica, thank you for your patience as we completed our review. This grant has been approved! Since the outlined deliverables and next steps will be a key piece of the final report review, please be in touch with our team if adjustments are required. Please also feel welcome to utilize our public slack channels to receive additional support!

 For next steps, we will send an email to confirm payment details.

**Comment by ErinOCon** [comment]
Hi @AlexxNica, the final grant report can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
