### ISSUE TITLE
Next Step Microgrant: TagYourTree

### ISSUE THREAD

**Issue by shabbiryk** [filecoin-project/devgrants#796]
### 1. What is your project? (max 100 words)
TagYourTree provides a way to track proof of plantation leveraging geotagging technology, with its data stored on IPFS and reward the users with an #TGT NFT for taking care of plants consistently.
Link to Github:
https://github.com/meta-ps/tagyourtree
Demo:
https://www.loom.com/share/c1f77ad7ca89470ba16dccd37f07a9a3

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
 We use IPFS for hosting the images of plants and their metadata and for member NFTs.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
To develop a community of people with similar mindset who want to contribute to the environment and be a part of sustainable growth. We are also planning to add a feature for NGOs to raise donations with our platform based on the proof of plantation record, in a clean and transparent manner. We are looking to add community managers for the community growth and beta test our project with some existing NGOs.

### 4. Is this project open source?
Yes.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
   https://gitcoin.co/hackathon/sustainable/projects/16118/tagyourtree
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  Shabbir 
  Email - [shabbirkhand.sk@gmail.com](mailto:shabbirkhand.sk@gmail.com)
  Github - shabbiryk
  Role - Frontend Developer

  Shashank
  Email - [jagannathamshashank@gmail.com](mailto:jagannathamshashank@gmail.com)
  Github - shashanka2a
  Role - Full Stack Developer
  
  Pradeep 
  Email - [pradeepvarma107@gmail.com](mailto:pradeepvarma107@gmail.com)
  Github - pradeepvarma22
  Role - Smart Contract Developer

* How did you learn about our microgrant program?
   Discord
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
    Sustainable Blockchain Hackathon
  * Please link to your hackathon submission
     https://gitcoin.co/hackathon/sustainable/projects/16118/tagyourtree

**Comment by ErinOCon** [comment]
Hi @shabbiryk, thank you for submitting this proposal! Can you confirm how you plan to "develop a community of people with similar mindset"? In other words, what steps will you take to build a user base for this project?

**Comment by shabbiryk** [comment]
Hi @ErinOCon, we are already in discussions with VIT Social about building a userbase from the institute. We will contact more colleges and conduct online meetups. 
In order to reach out to more people with similar mindsets, we have already contacted a few NGOs, such as Anandvan.

**Comment by ErinOCon** [comment]
Hi @shabbiryk, thank you for the updated information. Please incorporate the results of these user traction developments in the final report for this microgrant. This grant has been approved. We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
