### ISSUE TITLE
Next Step Microgrant - WeTube

### ISSUE THREAD

**Issue by LiWei1297** [filecoin-project/devgrants#797]
### 1. What is your project? (max 100 words)
WeTube is a Web3 video platform merging Youtube + OpenSea functionality.
Videos uploaded by users are transcoded by Livepeer and loaded from IPFS then minted to NFT.
Users can upload and watch videos in a decentralized way using this platform

WeTube uses Next.js as front-end. It uses LivePeer to transcode the videos and export to IPFS as storage. Moralis to web3 blockchain functions is pre-loaded to future integrations with Web3 blockchains.  HSL Video Encoding is supported.

The vision of the project is to provide a scalable and decentralised way for users to consume videos on the web

### 2. Project links
  
Link to Github repo: https://github.com/LiWei1297/WeTube
Link to demo or website, if applicable: https://youtu.be/ogLVuLIzmr8 (The video demonstrates the video-player, playing from a video stored on IPFS, and a profile view fetched from orbitDB Data)

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

All videos are stored on IPFS, and the corresponding NFT's minted are stored on IPFS as well. 
All user related information (history, profile, etc.) are stored on OrbitDB.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
- [ ] Develop a stand-alone server for hosting endpoints in a decentralised way (currently uses nextjs router)
- [ ] Implement a more secure orbit-db integration with two way encryption for user data
- [ ] Host a community version (Grant will help us cover costs for this)
- [ ] Improve user experience by implementing compression/decompression algorithm and reducing buffer times

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes .
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

| Name | Email | Role |
| -- | --- | -- |
| Li Wei | liwei1297@outlook.com | Project Lead / Smart Contract expert |
| Jiao-Long | j.long@outlook.sg | Backend Developer |
| Shui Guang | xshuiguang@outlook.com | UX Designer|

* How did you learn about our microgrant program? ETH CC Paris Event
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @LiWei1297, thank you for your proposal! Is this project open source?

**Comment by ErinOCon** [comment]
Hi @LiWei1297, thank you for your patience with our review. This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
