### ISSUE TITLE
Next Step Microgrant:  Green-Dao 

### ISSUE THREAD

**Issue by shepherliu** [filecoin-project/devgrants#798]
### 1. What is your project? (max 100 words)

  Green-Dao is a web3 dao paltform for the public goods that make the world more green and sustainable. There are six parts now for this dapp: green-daos、green-auctions、green-grants、green-votes、green-learnings and green-chats.

### 2. Project links
  
Link to Github repo:

        https://github.com/shepherliu/Green-Dao

Link to demo or website, if applicable:

        https://green-dao-orcin.vercel.app/

        https://youtu.be/KZevWy_uPI8

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

         The  IPFS is used for store messages, images and websites as the resources for the DAOs.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

        1.add page to show dao treassure balance and track the event log of the use of dao treassure.

        2.integrated with the gitcoin passport identity platform to verify the dao members identities.

        3. add smart contract marketplace that can auto execute green tasks. for example auto buy and burn the carbon emission tokens.

        4. more functions upgrade to the green chat, support send offline messages to users using ipfs/filcoin.

        5. ui/ux degsign for more user friendly.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

        Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

        Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
        https://gitcoin.co/hackathon/sustainable/projects/16060/green-dao

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
 
        shepher liu, shepher.liu@gmail.com, https://github.com/shepherliu, manager

* How did you learn about our microgrant program?

        receive email from the protocol.ai to encourge me to apply for this microgrant

* If your project was created as part of an event or hackathon:
   
        Yes

  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
     
        Sustainable Blockchain Hackathon:    https://gitcoin.co/hackathon/sustainable/?      

  * Please link to your hackathon submission

        https://gitcoin.co/hackathon/sustainable/projects/16060/green-dao

**Comment by shepherliu** [comment]
contacts: 

shepher.liu@gmail.com

**Comment by ErinOCon** [comment]
Hi @shepherliu, thank you for your proposal! Is this work fully open source?

**Comment by shepherliu** [comment]
Hi @ErinOCon, this project is surely fully open source under the GPL-3.0 license building on the Sustainable Blockchain Hackathon and win the runner up rewards. And also receive an email from the protocol labs that tell me can apply for a next step microgrant if want to do more on this work.

**Comment by ErinOCon** [comment]
Hi @shepherliu, thank you for the quick reply! This grant has been approved. We will send an email to confirm payment details.

The final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please reach out if you have any questions!

**Comment by ErinOCon** [comment]
Hi @shepherliu, can you provide a final report for this microgrant? Please let me know if you have any questions.

**Comment by ErinOCon** [comment]
Hi @shepherliu, do you have an update on the report?

**Comment by shepherliu** [comment]
> Hi @shepherliu, do you have an update on the report?

well, I will update it in the next few days.

**Comment by shepherliu** [comment]
> Hi @shepherliu, do you have an update on the report?

I have reported it with your link. If you have any questions, you can email me again.
