### ISSUE TITLE
Next Step Microgrant : DIYAvatar

### ISSUE THREAD

**Issue by diyself** [filecoin-project/devgrants#799]
### 1. What is your project? (max 100 words)
DIYAvatar is an avatar customization project completed in the previous paragraph, you can choose avatar shape, backgournd color , face , colors, tops, ear , earrings and eyebrows in the project.
When you choose your favorite avatar combination, you can mint your own nft through the polygon testnet . This functionality is done via nft.storage

### 2. Project links
  
Link to Github repo:
https://github.com/diyself/diyavatar
Link to demo or website, if applicable:
https://diyavatar.vercel.app/

yes ,it's on MIT .
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
The avatar DIY data completed by the user will be cast into nft on polygon through nft.storage.Through nft.storage, we can also increase the user's metadata, and in turn display the user's identity information in web3 through the avatar

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will accomplish the following things with this grant

- Optimize front-end web pages
- Add web3's wallet login method
- Add user information  page and mint avatar nft with it.
- Modify the contract to add user information support

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes
### 6. Does your proposal comply with our Community Code of Conduct?
yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  gavin , Explore Decentralized Identity Products , diyidentity@outlook.com

* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @diyself, this grant has been approved! We will be in touch by email to confirm payment details. Your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr).
