### ISSUE TITLE
Next Step Microgrant : Memorandum

### ISSUE THREAD

**Issue by chasonfis** [filecoin-project/devgrants#800]
### 1. What is your project? (max 100 words)
Memo is a Dapp built on the decentralized storage of IPFS/Filecoin. We link your memo data in IPFS/Filecoin by supporting multiple login methods. Likewise, we also record your data locally.

### 2. Project links
  
Link to Github repo:
https://github.com/chasonfis/memorandum
Link to demo or website, if applicable:
https://memorandum.vercel.app/

our project and code is under MIT.
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
IPFS/Filecoin will be the bottom layer of data storage for our products. All user data, whether it is the current text memo or the future rich text memo, etc., will be stored on IPFS/Filecoin through nft.storage . 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
When we get this grant, we will improve our products in technology and product optimization
On technology:

- Add multiple login methods including metamask, email
- Add a variety of memo formats: graphic, pure image, video, voice
- Looking for DID project parties to cooperate with users to complete the construction of data space index based on IPFS/Filecoin

On Product optimization:

- Establish the first seed users to try out the product
- Designing user interactivity from a UI/UX perspective
- Increase the adaptation of mobile platforms

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes

### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  chason, The rookie of the blockchain engineer but all into the blockchain and web3 , chason623@hotmail.com

* How did you learn about our microgrant program?
 From web3's friend.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @chasonfis, this grant has been approved! We will be in touch by email to confirm payment details.
Your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr).
