### ISSUE TITLE
Enabling Filecoin interoperability with Cosmos Ecosystem

### ISSUE THREAD

**Issue by ma-sonr** [filecoin-project/devgrants#801]
# Research Grant Proposal: Exploring Filecoin interoperability with Cosmos Ecosystem

**Name of Project:** Exploring Filecoin IBC interoperability (by Sonr)

**Proposal Category:** `core-dev`

**Proposer:** ma-sonr

**(Optional) Technical Sponsor:** Boris Mann

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

**The problem** 

In its journey to become the decentralized storage layer for the new internet, Filecoin must find ways to interoperate several disjoint blockchain ecosystems. Native support of new blockchain-community protocols like IBC requires significant engineering complexity.  

**What we are building** 

Sonr is building a light-weight trustless Filecoin bridge to its IBC-enabled blockchain, allowing users of IBC-enabled blockchains to access Filecoin resources. 

**Why**

Our aim in building the describe solution is to cultivate Filecoin use cases, enable technical interoperability with a growing blockchain ecosystem, and ultimately foster ecosystem growth. Cosmos-based chains like Sonr are able to create use-cases involving Filecoin, the Filecoin will subsequently benefit from the increased utilization of resources. Cosmos’ ecosystem inter-blockchain communication protocol makes it specially positioned to accelerate Filecoin’s in its ecosystem growth.

## Value

**Interoperability with Cosmos ecosystem**

With the described solution, Cosmos' ecosystem of blockchains would be able to leverage Filecoin's storage resources. Cosmos ecosystem includes 100s of chains:

- Cosmos Hub
- Osmosis
- Binance chain
- DyDx
- etc..

The Cosmos ecosystem will continue to evolve as more application-specific blockchains emerge, and enabling IBC on Filecoin would create the opportunity for many use-cases across the entire ecosystem. This better positions Filecoin to become the go-to permission-less storage solution for the new internet. The expansion of chain support for Cosmos also adds liquidity to the Cosmos Ecosystem overall, making it more favorable to build DeFi protocols and other projects. 

**Branding and visibility risks**

Without the right partnerships and buy-in across ecosystems, we face the risk of inadequate visibility around the final solution. Beyond access to the best-in-class protocols and frameworks, this project will require intentional co-branding and broadcasting of its implications to both the Cosmos and Filecoin ecosystems. 

**Interoperability with Filecoin**

While the Sonr team has visibility into the construction of its IBC-enabled blockchain, we are external to the Filecoin team and thus have less visibility into the construction of the Filecoin chain. The execution difficulty risk arises in their being adequate Filecoin resources (documentation, Slack channels) in the event that assistance with the project is needed. Our hope is that our ongoing discussions in Filecoin Github, Filecoin Slack, and with other Filecoin stakeholders will mitigate this risk.

## Deliverables

**Milestone:** A case-study highlighting our findings, open questions, and solution next steps for Filecoin interoperability with Cosmos IBC. 

**Function:** The ability for Cosmos blockchains to gain access to Filecoin’s storage resources.

## Development Roadmap

**Milestone 1**

***Use-case exploration*** 

- Functionality: Research around potential use-cases within IBC
    - Which blockchains might leverage this interoperability initially? 
    - Where is Filecoin broadly applicable within the Cosmos ecosystem? 
- Teammates: Sonr Engineers (1); Sonr Product Manager (1)
- Budgetary Needs: [In progress]
- Completed By: [In progress] 

**Milestone 2**

***Best stack combination to support the IBC-compatible Filecoin permission-ing system***

- Functionality: Define end-to-end stack combination required to build the bridge
- Teammates: Sonr Engineers (2); Sonr Product Manager (1)
- Budgetary Needs: [In progress]
- Completed By: [In progress]

## Total Budget Requested

The total budget requested based on the assumptions below is [In progress]

- An hourly rate of $200/hr
- Full-time hours worked across Engineers and Product Manager
- Full used towards compensating the needed number of team members

## Maintenance and Upgrade Plans

The Sonr team aims to maintain the described software post grant-receipt and launch.

**Note:** As described by the phases in the [Textile team’s blog](https://blog.textile.io/native-filecoin-storage-for-blockchains/), the Sonr team will continuously consider the appropriate level of decentralization. 

# Team

## Team Members

Michael Amoako - Chief of Staff

Prad Nukala - CEO

Nick Tindle - Head of Engineering

## Team Member LinkedIn Profiles

[Michael Amoako LinkedIn](https://www.linkedin.com/in/michael-amoako-71b449113/)

[Prad Nukala LinkedIn](https://www.linkedin.com/in/pradn/)

[Nick Tindle LinkedIn](https://www.linkedin.com/in/ntindle/)

## Team Website

https://www.sonr.io/

## Relevant Experience

- **Prad Nukala**
    
    Prad has been involved with the tech industry since the introduction of the app store, making one of the first 5,000 apps at age 12. Before founding Sonr he has self developed over 10 projects commercial and open source that have totaled over 1 Million downloads. Most recently Prad has guest lectured at MIT's sloan school alongside Vitalik, Anthony Pompolio, and Yat Siu.
    
- **Michael Amoako**
    
    Michael graduated from the Massachusetts Institute of Technology (2019) with mix of degrees in Business Management, Computer Science, and Mathematics. He was admitted to Harvard Business School’s MS/MBA program 3 years ago in their deferred admission program, which he decided to defer to pursue his current career path. 
    
    Before joining forces with Prad and pursuing Sonr, Michael worked at several big technology players including Google and Microsoft, in AI-focused Engineering and Product management roles. While he enjoyed his roles and impact as a leader in the Responsible AI space, he was particularly moved by CEO Prad’s vision at Sonr. To Michael, joining Prad in building Sonr was an opportunity to finally enact Tim Berner's Lee's original goals around a user-owned internet. Michael’s technical product background made him the perfect first hire for Prad. 
    
- **Nick Tindle**
    
    Nick is a professional as a dev-ops engineer with a mix of hardware and software skills. When he’s not building the user-owned internet, Nick can usually be found attending hackathons, launching rockets, or building home made machines.

## Team code repositories

- [https://github.com/sonr-io/sonr](https://github.com/sonr-io/sonr)
- [https://github.com/sonr-io/explorer](https://github.com/sonr-io/explorer)
- [https://github.com/sonr-io/vault](https://github.com/sonr-io/vault)
- [https://github.com/sonr-io/nebula-react](https://github.com/sonr-io/nebula-react)
- [https://github.com/sonr-io/nebula-core](https://github.com/sonr-io/nebula-core)
- [https://github.com/sonr-io/MotorKit](https://github.com/sonr-io/MotorKit)

# Additional Information

We’ve spoken to several folks from the Protocol Labs and Filecoin ecosystems, who’ve pointed us towards this grants program including: 

- Boris Mann, IPFS Fission
- Juan Bennet, Protocol Labs
- Charles Cao, Fileswan
- Kaitlin, Filecoin Governance
- Jonathan Victor, Protocol Labs

michael@sonr.io

The grant proposal was inspired by discussions around Filecoin supporting Cosmos-based chains including Sonr: [https://github.com/filecoin-project/FIPs/discussions/398](https://github.com/filecoin-project/FIPs/discussions/398). From our discussions with Filecoin and Interchain, we came to the conclusion that native support of Filecoin on the Sonr blockchain through the bridge solution described would be the most practical short-term approach. This also fits well into Sonr’s overall narrative (described below) and opens the door to many use-cases for Filecoin.

Check out the [Sonr docs](https://www.sonr.dev/docs) to learn more about Sonr!

**Comment by ma-sonr** [comment]
Additional partner: FilSwan

**Comment by ErinOCon** [comment]
Hi @ma-sonr, thank you for your proposal! We are reviewing this project and will be in touch as soon as we have an update.

**Comment by BlocksOnAChain** [comment]
@ma-sonr I have some potential questions, Dragan from PL here.

What do we plan to do with:
 - relaying the proofs we must first think about signature verification, so both cosmos and Filecoin FVM need to support the same types of signature in their runtime? Who will implement this and make it work End to end?

- What is our plan for managing relayer infrastructure? Who and how will manage this during the implementation + who will manage it after the main implementation phase is done?
- 
- When you say October 30th as the end deadline, does that mean to solve all the issues + give users the ability to end, since I believe FVM would be a significant dependency to make all of this work? October 2022 is a bit premature for FVM since we plan to do a network upgrade in February 2023.

**Comment by ErinOCon** [comment]
Hi @ma-sonr, thank you again for your proposal! We are pleased to approve a $50k grant to support this project. We will send an email to confirm next steps.
