### ISSUE TITLE
Next Step Microgrant: BackedBy

### ISSUE THREAD

**Issue by cshowley** [filecoin-project/devgrants#802]
### 1. What is your project? (max 100 words)
BackedBy is a distributed payment platform for creators (demo live at [https://backed.by/](https://backed.by/)). It provides creators an easy way to bring their business and audience to web3. BackedBy's long term goal is to give creators complete control over distribution to their supporters by managing payouts and messaging through web3 channels, and censorship resistant content through decentralized file storage. The BackedBy platform is monetized through a 1% fee on all transactions on the platform.
### 2. Project links
  
Link to Github repo: https://gitlab.com/b4278
Link to demo or website, if applicable: https://backed.by

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Creators' content is stored on IPFS using Filecoin's web3.storage service, and premium content secured by Lit protocol for decentralized access control; only subscribers to a creator's paid tiers grants access to that content.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Filecoin's greatest contributions are assistance in funding and marketing for the short to medium future. Funding to use for hosting, legal, and pay for developer(s) with web3 experience, and marketing for directed targeting to creators with proven premium subscription success. Creators who have dedicated followings will naturally bring their fans to the blockchain, which means more revenue for BackedBy.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Boris Chobrutskiy
  email: boris@backed.by
  github: N/A
  role: founder/dev
Dax Herrera
  email: dax@backed.by
  github: N/A
  role: dev/outreach
Charlie Showley
  email: charlie@backed.by
  github: https://github.com/cshowley
  role: dev
Garrett Tynes
  email: jeffreytynes@gmail.com
  github: N/A
  role: legal
Joshua Erickson
  email: dajejoevicllc@outlook.com
  github: N/A
  role: dev
Brandt Hill
  email: brandtlarsonhill@gmail.com
  github: https://github.com/BrandtHill
  role: dev
Pete Oxenham
  email: pete@chatter.dev
  github: N/A
  role: frontend/design
John Bojtor
  email: paranoidsyntaxerror@gmail.com
  github: [https://github.com/ParanoidSyntaxError](https://github.com/ParanoidSyntaxError)
  role: dev

* How did you learn about our microgrant program?
We learned of the microgrant program by searching specifically for grants offered by Filecoin.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
N/A

**Comment by ErinOCon** [comment]
Hi @cshowley, thank you for this proposal! It looks like you provided a link to gitlab. Can you resubmit the github repo link? Also, can you provide more detail on the next steps for this project? Specifically, how will you use these funds over the next three months to move your project forward?

Finally, can you confirm this project is open source?

**Comment by ErinOCon** [comment]
Hi @cshowley, do you have an update for the above inquiries?

**Comment by cshowley** [comment]
Hi @ErinOCon did you have a chance to review my update?

**Comment by ErinOCon** [comment]
Hi @cshowley, thank you for checking in for an update and for the provided information. In order to be considered for the microgrant program, the project will need to be open source and the repo link will need to be public. We understand if this is not a preference at this time. 

If applicable, please feel welcome to re-apply when your project transitions to open source work!
