### ISSUE TITLE
Next Step Microgrant: Crowd Funded Cures

### ISSUE THREAD

**Issue by crowdfundedcures** [filecoin-project/devgrants#803]
### 1. What is your project? (max 100 words)
 
Crowd Funded Cures is an Impact Market platform validating the safety and efficacy of unmonopolisable therapies that are unprofitable under the traditional patent system because they are non-rivalrous and non-excludable public goods (e.g. optimising treatment protocols for repurposed generic drugs, plant medicines, psychedelics, nutraceuticals, and lifestyle interventions). Prospective funders purchase IP-NFTs in order to generate clinical trial data, and in the event of a successful treatment protocol, the IP-NFT owners are issued with a Hypercert / Impact Certificate entitling them to receive retroactive funding via a crowdfunded Medical Impact NFT fund, which serves as an Advance Market Commitment.

https://github.com/brahmapsen/CFC

https://crowdfundedcures.org/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

Clinical trial data associated with an IP-NFT is held in a decentralised storage under Molecule.to’s IP-NFT platform. An independent Contract Research Organisation (CRO) runs the clinical trials and acts as Results Oracle, which will provide Impact Points to owners of an IP-NFT and issue a Hypercert using Filecoin/IPFS, making owners eligible to receive a proportional outcome payment from a specific Medical Impact NFT fund backed by CFC token treasury, which is crowdfunded to retroactive funders via syndicate.io platform. Outcome payments from the Medical Impact NFT fund will be made from Gnosis multisig. 

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Microgrant to assist steps 1-3 of MVP launch roadmap.

Blockchain developer (Brahma P Sen) has developed initial smart contract for issue of Medical Impact NFT and front end developer (Zack West) built initial website with support.
Next step is to finalise project specification for Hypercert / IPFS integration with PL Hypercert project team (Holke Brammer) (1-2 weeks).
Front end developer (Zack West) to develop UX/UI and customer journey for crowdfunding landing page to issue Medical Impact NFTs as Advance Market Commitments for unmonopolisable therapies in specific disease classes (1-2 weeks).
Back end / blockchain developers (Brahma P Sen, Daniel Dohne, Kash Honey) to build API to allow issue of IP-NFTs to impact investors via Molecule.to platform, crowdfunding of Medical Impact NFT fund via Syndicate.io held in Gnosis multisig (2-3 weeks). 
MVP goes live on crowdfundedcures.org, syndicate.io, Gitcoin and Giveth to crowdfund Medical Impact NFT fund in specific disease class (e.g. Open Psychedelic NFT for depression partnered with PsyDAO) (2-4 weeks).
Successful treatment protocols linked to IP-NFTs result in issue of Hypercerts with rights to provide outcome payments to IP-NFT holders, proportional to Impact Points generated, as validated by independent CRO and Gnosis multisig. (12+ months).

### 4. Is this project open source?

Yes, code will be published under MIT licence, BSD licence or equivalent. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes 

### 7. Links and submissions

https://ethglobal.com/showcase/crowd-funded-cures-d6bwg

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Savva Kerdemelidis
[savva@crowdfundedcures.org](mailto:savva@crowdfundedcures.org)
https://www.linkedin.com/in/savvak/
Founder & CEO 

Andrew Horton
[horton.nz@gmail.com](mailto:horton.nz@gmail.com)
https://www.linkedin.com/in/andrewhortonsecurity/
https://github.com/urbanadventurer
CTO 

Brahma P. Sen
[bsen@inage-tech.com](mailto:bsen@inage-tech.com)
https://github.com/brahmapsen
https://www.linkedin.com/in/brahma-p-sen-06a2593/
Blockchain Developer

Zack West 
[alphazwest@gmail.com](mailto:alphazwest@gmail.com)
https://www.linkedin.com/in/alphazwest/
Web / Front End developer

Daniel Dohne
ddohne@aramid.finance
https://www.linkedin.com/in/ddohne/
Project Manager / Developer

Kash Honey (Cyrus) 
[knouroozi@gmail.com](mailto:knouroozi@gmail.com),
Front End / Back End / Blockchain Developer
https://www.linkedin.com/in/knouroozi/

* How did you learn about our microgrant program? 
Jonathan Victor / Holke Brammer

* If your project was created as part of an event or hackathon:
  * What was the name of the event?
 ETH NYC 2022

  * Please link to your hackathon submission

https://ethglobal.com/showcase/crowd-funded-cures-d6bwg

**Comment by jnthnvctr** [comment]
definitely in full support! would love to also have a blog or something to showcase how you guys are designing ip-nfts once the work lands (think the broader community would benefit!)

**Comment by crowdfundedcures** [comment]
> definitely in full support! would love to also have a blog or something to showcase how you guys are designing ip-nfts once the work lands (think the broader community would benefit!)

A blog would be amazing ! Molecule.to is also interested in the idea of integrating their IP-NFT platform with Impact Markets / Hypercerts as a way to incentivise investors to fund public good medicines (e.g. repurposing generic drugs) - Vincent and I reached out to Ale and Ela at 50 Years and will be discussing with them this week.

**Comment by ErinOCon** [comment]
Hi @crowdfundedcures, thank you for your proposal! This grant has been approved! We will send you an email to confirm payment details.

**Comment by crowdfundedcures** [comment]
> 

Thank you so much ! Very excited about starting to build the functionality to allow crowdfunding of a retroactive fund / Medical Impact NFTs!

**Comment by ErinOCon** [comment]
Hi @crowdfundedcures, we are also excited to kick off this grant! Please note your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr).
