### ISSUE TITLE
Next Step Microgrant: ipfsimple

### ISSUE THREAD

**Issue by ipfsimple** [filecoin-project/devgrants#804]
### 1. What is your project? (max 100 words)
IPFS most simple & brilliant users UI
Most systems work best if they are kept simple rather than made complicated; therefore, simplicity should be a key goal in design, and unnecessary complexity should be avoided. I simply followed that rule and want to extend and integrate more simple functionalities within it.

### 2. Project links
  
https://github.com/ipfsimple/upload
https://upload-ipfsimple.vercel.app/

MIT License
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

IPFS is the core and the project is build around it focusing on the most user friendly UI.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Further extensions and integrations with estuary to allow extensive user building on https://ipfsimple.xyz/ 
Onboarding more users, split large files, encrypting proprietary data sets, etc.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
*No
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Mike Wevers, info@ipfsimple.xyz , Dev.
* How did you learn about our microgrant program?
Surfing about Filecoin and IPFS
* If your project was created as part of an event or hackathon:
No.

**Comment by ErinOCon** [comment]
Hi @ipfsimple, this grant has been approved! We will be in touch by email to confirm payment details. 

Your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr).
