### ISSUE TITLE
Open Grant Proposal: New Generation CDN Service

### ISSUE THREAD

**Issue by vachkata** [filecoin-project/devgrants#805]
# Open Grant Proposal: New Generation CDN Service

**Name of Project: Cidien**

**Proposal Category:** `integration-adoption`

**Proposer:** vachkata

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description
Many web sites are using and paying for Azure Blob Storage Service exposed as a CDN server. I want to provide cheaper/faster/better/simpler CDN+Blob Storage service for .Net based web sites. There are hundreds of thousands paying clients for it now. We just need to provide better alternative, easy to integrate and we will achieve a massive Filecoin adoption step.

Needed features:
1. Transparent Filecoin. The customers of Cidien will not need to work with Filecoin protocols and APIs. They will have an easy to use C# API for using the Cidien blob/CDN service.
2. Account management web pages (handling API access key, basic invoicing, other fundamental features)
3. Standard payment provider integration. Since the customers of Cidien are non-pioneer businesses we will provide them the standard payment methods. The Cidien system will internally convert payments to Filecoin.
On the backend:
1. Converting Cidien API requests to Filecoin network actions
2. Converting client card payments to Filecoin and spend it for the storage service.
3. Have all backend user accounts storage on the Filecoin system, no additional/external databases

## Value
Having Cidien as described will easily convince standard online businesses to start using Filecoin. Great amount of paying business customers can switch to Filecoin. If done right we will compete directly with the current big cloud service providers at big scale.
The general risks are:
1. We fail to implement the Cidien API.
2. We fail to convince real businesses to use it.
3. Filecoin to appear slower or more expensive than the current Azure FileBlob and CDN
4. Filecoin to appear unprepared for serving many client connections

The riskiest technical part of the project is the automatic converting of fiat money to Filecoin.
Another risk is if the Filecoin API changes too fast and the Cidien API can't follow with the provided resources. 

## Deliverables
1. .Net API covering what can be done with Azure Blob Storage
2. Web site for administrating customer accounts
3. Integration with Filecoin (backend)
4. Fiat payment provider integration (backend)
5. Fiat to Filecoin exchange (backend)

## Development Roadmap

0. Initial Filecoin research (1 week) 15.08.2022

1. Integration with Filecoin implemented in C# (1 month) 22.08.2022
Add all needed API calls for working with CDN: account authentication, upload file, delete file, pay storage fee, tune-up load-balancing, geo-location, caching

2. Web site for administrating customer accounts (2 months) 22.09.2022
Features: Create/Edit Account, Deposit fiat money, Generate API access keys, Display CDN account data (public web address), Stop Service, Check Filecoin balance. Reports: Fiat transactions ledger, Filecoin transactions ledger, Storage stats, Traffic stats

3. .Net API covering what can be done with Azure Blob Storage (1 week) 01.10.2022
File upload, File delete

All milestones will be done by single developer. Evaluating one man-month to $6k

## Total Budget Requested
$21k
Milestone 0: $1.5k
Milestone 1: $6k
Milestone 2: $12k
Milestone 3: $1.5k

## Maintenance and Upgrade Plans

Keep the Cidien API end simple and not mutate it if possible. Keep updating to whatever changes on the Filecoin end.
I intend to involve my contacts from the online auction houses to start consuming more NFT like services than just an alternative CDN.

# Team
One man army
## Team Members
Ivan Milanov, vachkata

## Team Member LinkedIn Profiles

I do not use LinkedIn

## Team Website

https://www.koza.bg

## Relevant Experience
I work for the online auctions business and different e-commerce projects. I am maintaining ~80 live sites, each with need of well working CDN service. I have worked on different integrations for gaming, server-to-server night data transfers. I also keep eye on the Bitcoin and Lightning integrations with C#.
## Team code repositories
No public repos to show.

# Additional Information
I believe a storage service is a good way for adapting De-stuff so I checked what Filecoin is about.

**Comment by ErinOCon** [comment]
Hi @vachkata, this grant has been approved! Can you confirm the preferred email address to discuss next steps?

**Comment by vachkata** [comment]
Hello EriOcon,
Thank you for the good news!
My preferred e-mail address is ***@***.***
Kind Regards,
Ivan Milanov

**Comment by vachkata** [comment]
> Hi @vachkata, this grant has been approved! Can you confirm the preferred email address to discuss next steps?

Yes, 

> ivan.milanov@gmail.com

Hey, I replied yesterday via email from mobile and the address got asterisked. I want to make sure you saw it:
ivan.milanov@gmail.com

**Comment by vachkata** [comment]
@ErinOCon  @realChainLife 
Hi guys,
Can you give me a hint of when we can start working on the project? I want to schedule my time until the year end giving Cidien the priority. Also 16th-19th of August I will be on short vacation.

**Comment by ErinOCon** [comment]
Hi @vachkata, thank you for the contact information. We sent an email to the provided email address earlier this week. Please let us know if you are having any trouble receiving our email.

**Comment by vachkata** [comment]
Hello Erin,
I confirm I received the email. Today (Sunday) I will fill in the
questionnaire and sign the contract.
Cheers,
Ivan Milanov (vachkata)
