### ISSUE TITLE
Web3 Domain

### ISSUE THREAD

**Issue by gupta977** [filecoin-project/devgrants#806]
# Open Grant Proposal: `Web3Domain`

**Web3 Domain Name**

**Proposal Category:**  `integration-adoption`

**Proposer:** `gupta977`

**(Optional) Technical Sponsor:** `none`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** YES

# Project Description

- We are building Web3 Domain Name and all records associated with it will be over Filecoin Only. 
- Each and every domain referenced with CID through nft.storage
- As like a crypto long wallet addresses, CID are too big to remember or hard to tell anyone by oral. This will solve the issue as it will have handy unique, small name for each CID ending with .ipfs domain. 
- Currently .ipfs URL can only visited within brave browser. We will develop extension that will let user to visit IPFS URL even in chrome, edge and so on. 
-  The Wordpress Plugin will be developed, so that any website installs it will have Web3 Tools to visit IPFS URL within their website. This will build up the trust the the URL visited from own website. 
- That short domain name assigned with IPFS long address will get resolved within Telegram via Bot. No need to install any plugins or extension into website. 
- We will have .fil domain extension so that only the Filecoin member or staff will have subdomain of it. This will work as a identity of staff, volunteer, team. This will help people from getting spammed. 
- OR just like .eth domain we will introduce .fil domain within the market. 

## Total Budget Requested

We are looking for $20K USDT.
This includes all above promises we have done above along with marketing cost and to sustain company to develop further. 

## Maintenance and Upgrade Plans

We will keep on adding new tools where ever possible. 
Under planning: 
- Integration with Twitter to resolve domain within the message box without any extension.
- .fil domain address for wallets token transfer.
- only .fil domain holder have certain access within the site. 

# Team

## Team Members

I am only one and reset I get it done from freelancer. 
Help us to grow as a company. 

## Relevant Experience

Developing website & software since early 2000 AD. 

## Team code repositories
https://github.com/gupta977/

# Additional Information
- I got to learn and inspired about Filecoin from Mr. Piyush Maheshwari. Telegram @itspiyushmaheshwari
- My Telegram address is @gupta977 & email is navneet@odude.com

**Comment by ErinOCon** [comment]
Hi @gupta977, thank you for your proposal! Can you list the project deliverables and provide a milestone breakdown? Each milestone should include a description, payment amount, and estimated timeframe. Also, if your microgrant project is complete, please provide a final report using the template provided in the [Issue item](https://github.com/filecoin-project/devgrants/issues/641).

**Comment by gupta977** [comment]
Thank you for allowing me to describe more further.
I will try to explain as simple as possible in point wise. 

1- Just like ENS domain ending with .eth & unstoppable domain with .zil, we will create .fil domain.
User will able to create their sub-domain eg. elon.fil or support.fil
2- User can assign records like social media, wallet address, profile picture with the domain. 
3- Secondly, we will encourage user to create their own website which will be hosted over Filecoin and that website can be accessed using the domain name.
4- To access decentralized domain name & website, browser extension will developed.
5- Along with browser extension, Telegram bots will be created so that any information can be achieved instantly by typing ( /domain support.fil@email which displays email address). Similarly, other handles will also added like email, twitter, telegram, discord and many more.
6- If anyone don't want to install browser extension then domain website & information can be accessed by visiting support.fil.w3d.name. **(We** will buy w3d.name domain & private dedicated server today after this submission **).**
We can also install scripts on any wordpress site so that it can be visited as support.fil.filecoin.io

This all the part we are already working and many more still under planning. 
About fund break down, 
1 to 3 point is 50% of work and 4 to 6 is next 50% of the grant we have requested for. This we will cover all within 1 month of time. We are sure it will get achieved within our expected time. 
We will assure you that along with above all the promise we have made, we will do lot more mentioned. As we need continues development to increase user tools to access records over Filecoin through IPFS using nft.storage API. 

Thank you for positive and faster response.

**Comment by gupta977** [comment]
Domain purchased and now buying dedicated server.

**Comment by gupta977** [comment]
Purchased private server and assigned to w3d.name
Now server administrator is setting up everything.

**Comment by ErinOCon** [comment]
Hi @gupta977, thank you for the additional information. This grant has been approved. We will reach out by email to discuss next steps.
