### ISSUE TITLE
Autify Network

### ISSUE THREAD

**Issue by Nabarun006** [filecoin-project/devgrants#807]
### 1. What is your project? (max 100 words)

We are developing a trust protocol to make commerce and supply-chain more transparent through the power of blockchain, AI & computer vision.

Autify Network is the first and only certification platform designed to prove the authentication and ownership of any physical goods using an object’s biometry. No external proxies—no QR code, no barcodes, no microchips or add-ons.

We use a combination of intelligent technologies, including computer vision, artificial intelligence and decentralized infrastructure to mint, match, maintain and transfer digital twins. These NFT certificates provide a universal solution for certifying trust across the sectors.

Using advanced recognition and identification techniques in computer vision, artificial intelligence and decentralised infrastructure, Autify can uniquely identify physical objects even if they are of the same make or model. This solution far surpasses anything in the market today.

We are currently using web3.storage/IPFS as the default storage in our protocol to save product metadata, location data, logistics data, images and many more. 

### 2. Project links
  
Link to Github repo: https://github.com/autifynetwork/Authentication-contracts
Link to website: https://beta.autify.network/
Link to Twitter: https://twitter.com/AutifyNetwork
Link to LinkedIn: https://www.linkedin.com/company/autify-network/
Link to Litepaper: https://bit.ly/autify-network-litepaper-pl
We selected for the India blockchain accelerator: https://bit.ly/autify-iba-selection-pr

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

We are using web3.storage/IPFS as the default storage in our protocol to save product metadata, location data, logistics data, images and many more. 

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The process in supply chain and retails are very complex as there are lots of centralised data involved. By using decentralised storage like IPFS/Web3.storage, we are aiming to become a 100% decentralized platform in the next 3 months. 

This grant will help us to reduce our roadmap and launch the product faster. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: 

We started the project at one of the NEAR protocol hackathons. 
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

- Nabarun Chakraborty, nabarun@autify.network, https://www.linkedin.com/in/nabarunchakrabortty/
- Joel D'souza, joel@autify.network, https://www.linkedin.com/in/joel-d-souza-860a2916b/
- Reshmi Mitra, reshmi@autify.network, https://www.linkedin.com/in/reshmi-mitra/
- Wasim Bari, wasim@autify.network, https://github.com/wasim162010
- Kundan Mishra, kundan@autify.network, https://github.com/mishra811
- Kunal Goyal, kunal@autify.network, https://github.com/kunalgoyal9
- Keshava Varmaa, keshava@autify.network, https://github.com/keshav743
- Shreejata Neogi, shreejata@autify.network, https://www.linkedin.com/in/shreejata-neogi-0b37b1165/
- George Cheeran, george@autify.network, https://www.linkedin.com/in/george-e-cheeran-a36274a4/
- Soumitra Sen, soumitra@autify.network, https://www.linkedin.com/in/soumitra-sen-blockchain-content-writer-44a44b166/

* How did you learn about our microgrant program?

Referred by Jonathan Victor, Ecosystem Lead @ Protocol Labs

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by Nabarun006** [comment]
@ErinOCon When will I get an update?

**Comment by ErinOCon** [comment]
Hi @Nabarun006, thank you for this proposal! Can you confirm if this project will be fully open source? Also, can you provide a working Github repo link?

**Comment by Nabarun006** [comment]
Hey @ErinOCon, Yes, the **Authentication block** (Origin and supply chain traceability & Counterfeit verification) will be fully open source. 

Backend Github URL: https://github.com/autifynetwork/Authentication-backend
Frontend Github URL: https://github.com/autifynetwork/Autify-network-beta/tree/master/autify.network

Please let me know if you have any questions.

**Comment by Nabarun006** [comment]
@ErinOCon, When can we expect the final decision?

**Comment by ErinOCon** [comment]
Hi @Nabarun006, thank you for the updated information! This grant has been approved. We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
