### ISSUE TITLE
TeamPod Finance Grant Request

### ISSUE THREAD

**Issue by Kuraj11101** [filecoin-project/devgrants#809]
# Open Grant Proposal: `TeamPod Finance`

**TeamPod Finance:**

**Kindly see the Additional Information section For Details**

**Proposal Category:** Choose one of `core-dev`, `app-dev`, `devtools-libraries`, `integration-adoption` , `technical-design`, `docs` , `community` , `metaverse` , `research` , `green`  Learn what these categories are here: https://github.com/filecoin-project/devgrants/tree/master/open-grants#readme

**Proposer:** `replace with your GitHub username`

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Please respond with either "Yes" or "No"

# Project Description

## Maintenance and Upgrade Plans

# Team

## Team code repositories

# Additional Information

Project Description
Teampod Finance is a platform meant to create a close segment of nodes financially networked between a circle of friends, families, workmates, and partners.

The action here is to create a space where people can use extra capital or finance to stake in a cash or crypto pool together with other people or organizations in order to make cash/crypto pods savings and streams. Be it large or small scale streams and savings periodically which will be randomly awarded to one, two, three, four or five member(s) of a group at a time at the end of every monthly circle in a form of a reward token for staking with the group or team.

This random selection is done by no member of the group but by a smart contract developed on the blockchain embedded into each TeamPod to manage the cash/crypto flow of each team.

Team members get to have this reward only when they've join and stake with a team created by a team leader or creator who selects the actual staking amount that is to be deposited by each team member at the beginning of each month. Rewards of token given out to selected member(s) during an end of a circle or month round of staking is rewarded by summing the total amount of stakes deposited by each team member of a team into the Tpod (TeamPod) savings and Beneficiary or Beneficiaries of the month of a specific team incurs deduction for their next staking round plus a 10% Pod Management charge by the TeamPod Finance Team leaving the rest to the beneficiaries.

This process continues until there's a mutual and majority termination decision reached by the team.

Team members can only join by invites given out by a TeamPod creator or leader.

Each team posses a channel on the platform where in they can chat, have meetings, share documents, images, audios, stickers, files and more with a chance of each team member having their files and data store on a decentralized network using Filecoin and IPFS file storage mechanisms.

TeamPod Finance has a feature of cash pool financed by Liquidity Providers who are investors with a minimum 3% calculated return on their assets provided to fill the TeamPod Finance LP Cash/Crypto Pool which is available for TeamPod Finance team members to have access for credit wiith TeamPods reward token as guarantee.

The TeamPod Finance gets to make money by deducting a management fee of 10% off each reward round when a team member gets to cash out their benefits and 2% facilitator fee off the interest of each credit from the TeamPod Finance Liquidation Providers Cash Pool credited from by a team member. While TeamPod Finance also get to have a 4% out of 10% of the storage cost of filecoins pricing used by team members to buy storage for their data and file storage on the platform.

How it's Made
This project is built using Reactjs for frontend and nextjs for backend while harddart for smart contracts. Filecoin and IPFS for building storage network which are our major sponsors picks as it benefits the project in terms of decentralized storage and file systems mechanism. We are impress with coming up with such an idea that could change and empower more people worldwide

PS: A whole lot going on developing our product and we are quickly looking into getting technical help for our Filecoin and IPFS integration including financing of the system. So we just quickly put up description of our project. Please understand!

**Comment by ErinOCon** [comment]
Hi @Kuraj11101, thank you for your interest in our grant program. It looks like the template fields are incomplete. Please feel welcome to resubmit when the template information is available. It may also be helpful to review previous grants approved through our program.
