### ISSUE TITLE
Next Step Microgrant : FileSharing -wallet to wallet

### ISSUE THREAD

**Issue by gaoget** [filecoin-project/devgrants#811]
### 1. What is your project? (max 100 words)
FileSharing is an on-chain file sharing platform based on IPFS/Filecoin. It is based on wallet-to-wallet data sharing similar to peer-to-peer.
FileSharing uses nft.storage to upload data files to IPFS/Filecoin and secures the files can be obtained by the specified authorized wallet address by disciplinary file authorization wallets on the chain.
Our ultimate goal is to become a data transmission and sharing platform in web3. Implement complete decentralization, while implementing data encryption and other methods to ensure data security and stability

### 2. Project links
  
Link to Github repo:
https://github.com/gaoget/filesharing
Link to demo or website, if applicable:
Please connect the polygon testnet mumbai
https://https-github-com-gaoget-filesharing.vercel.app/

MIT License
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
The peer-to-peer data sharing of wallets will be based on IPFS/Filecoin. We use nft.storage to save the uploaded files of users. At present, we are building contracts based on the polygon test network. Later, we will build contracts on FVM to complete data sharing and other functions.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
At present, we have completed simple front-end page construction and contract development based on polygon testnet
After obtaining the grant, we will mainly develop the following functions

1. Hire a professional UI/UX to complete the web design of the product
2. Add wallet-based data management module to record data sharing history( when , who share to me,  share what to others)
3. Improve the transformation contract and add the description information of cid data
4. Increase data point-to-point encryption

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes

  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
   gaoge ,   gaogets527@163.com, https://github.com/gaoget
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @gaoget, thank you for your patience with our review. This grant has been approved We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
