### ISSUE TITLE
Next Step Microgrant : Junkstora

### ISSUE THREAD

**Issue by DarylNoupik** [filecoin-project/devgrants#812]
## 1. What is your project? 
JUNKSTORA is a database storage library for building decentralized applications in Typescript and Javascript, currently focused on Filecoin's IPFS platform.

Junkstora connects to Filecoin nodes, manipulates and encrypts live chain data and operations and Junkstora servers for high performance analytics on blockchain data. Internally, the library can be used either as a main database backup system or as a redundant secondary system.

[Link to public Github repo](https://github.com/DarylNoupik/Junkstora.git)
[Link to gobal demo API](https://45.147.98.123:3000/)

`

### 2. How will IPFS, Filecoin, or related technology be used for this project?

We use Filecoin IPFS to be able to store dynamic database data to produce a unique signature hash of the original file through the Filecoin blockchain.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective?

To be able to improve the project we will use the grant on several aspects:
- Recruitment | We will use the Grant to recruit a frontend developer to be able to create and improve a project interface. We will also need a community manager to manage the community around the project
- Infrastructure | Since we are in a country that is still underdeveloped, we have enormous difficulties in terms of equipment and internet connection. The grant will help us acquire equipment to be able to develop the project peacefully.
-Cloud | To be able to put the project online, we will need cloud space, mainly aws to host the filecoin service nodes.

 
### 4. Is this project open source?

The project is totally opensource.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, i Agree
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes
  
### Additional questions:
- For each team member(s), please list name, email, Github account, and role in the project.

  * Name - Daryl Noupik
    Email - [darylnoupik@gmail.com](mailto:darylnoupik@gmail.com)
    Github - https://github.com/DarylNoupik
    Role - Lead Dev
 
 
- How did you learn about our microgrant program?
    Friend
    Through the community forum

[GitHub](https://github.com/DarylNoupik)

**Comment by DarylNoupik** [comment]
Hi @ErinOCon
The link to the demon is as follows :[Link to demo API](https://45.147.98.123:3000/)
You can test the api using the following endpoints, while checking the changes on the test database deployed for this purpose (mongodb://test:6TP95zP0@45.147.98.123:27017/?authMechanism=DEFAULT&authSource=TestDB)

To backup test database create use this command :
```console
curl --location --request POST '45.147.98.123:3000/ipfs/mongodb/savedata' \
--header 'Content-Type: application/json' \
--data-raw '{
    "privatekey" : [30,104,54,17,122,129,82,206,12,139,126,62,205,2,192,111,210,181,77,68,248,1,93,152,118,138,194,249,70,241,203,21,227,205,47,74,156,194,248,154,193,14,191,5,9,96,178,1,123,85,170,148,123,248,161,115,249,86,186,141,193,35,8,66],
    "publickey": "4PGC6SU4YL4JVQIOX4CQSYFSAF5VLKUUPP4KC47ZK25I3QJDBBBB3PTV6B"
}'```


To Restore test database create use this command :
```console
curl --location --request GET '45.147.98.123:3000/ipfs/mongodb/getdata' \
--header 'Content-Type: application/json' \
--data-raw '{
    "cid" : "<Previous Generate CID",
    "privatekey" : [30,104,54,17,122,129,82,206,12,139,126,62,205,2,192,111,210,181,77,68,248,1,93,152,118,138,194,249,70,241,203,21,227,205,47,74,156,194,248,154,193,14,191,5,9,96,178,1,123,85,170,148,123,248,161,115,249,86,186,141,193,35,8,66],
    "publickey": "4PGC6SU4YL4JVQIOX4CQSYFSAF5VLKUUPP4KC47ZK25I3QJDBBBB3PTV6B"
}'```

PS : The public and private keys are dummy and only for testing purposes

**Comment by ErinOCon** [comment]
Thank you, @DarylNoupik! Can you confirm what you hope to achieve in the next three months with a frontend developer, community manager, and updated equipment? This information will help us evaluate your final report.

**Comment by DarylNoupik** [comment]
Hi @ErinOCon, yes I can confirm that thanks to this Grant I will be able to improve the interface of the project by recruiting a frontend developer who will create frontend tools in Nodejs to improve the developer experience. The essential equipment we need are cloud services as well as a slightly more efficient laptop. As for the community manager, we will create a discord channel as well as slack to allow better communication with the devs. They will be in charge of the community manager during the 3-month expansion period of the project thanks to the grant.

Regarding the problem with the test of the api I think you try the api in graphical interface but for the moment we have not developed an interface yet. To test the functional aspect you must use the previous command in bash terminale or make requests  via Postman or any other API creation software.

**Comment by DarylNoupik** [comment]
Hi @Erincon,
You can find a demo of the project on this video [Presentation](https://youtu.be/GDqDDdWY5Z0)

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by DarylNoupik** [comment]
Hi @ErinOCon ! Should I make another transfer request ? 
Because I haven't received the microgrant on my wallet
