### ISSUE TITLE
Next Step Microgrant: IPFS-based Instagram profile mirror

### ISSUE THREAD

**Issue by nschaievitch** [filecoin-project/devgrants#813]
### 1. What is your project?

The project consists of a protocol which allows users to replicate their Instagram profiles through IPFS, thus creating a mirror or archive. This might be useful for data availability in the event of downtime in the Meta servers or censorship, as well as simply giving an alternative for people who want to consume the media without going through the company. The implementation contains both a way to create this mirror from one's existing account and add it to IPFS, and a web-based client for displaying this data in a similar format to a regular Instagram profile.

### 2. Project links
  
Link to Github repo: https://github.com/nschaievitch/ipfs-instagram-mirror

Link to demo or website, if applicable: http://ipfs-instagram-mirror.vercel.app/ (link to the web-based client)

  
### 3. How is IPFS, Filecoin, or related technology used in this project?
  
IPFS is used to distribute the mirror, and IPNS is supported so that it can be properly updated.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective?

Many improvements should be done to the current MVP to make it practical, mostly developing the UX:
- Currently, the mirror is created from an Instagram Data Request, feeding the result into a Python script which formats it properly. However, a more practical solution needs to be developed such that the mirror can be updated on the fly, preferably automatically.
- Support for story highlights, videos, and reels is to be added.
- The current web-based view requires a gateway to access the data. This should be migrated to something like JS IPFS to avoid centralized third-party requirements.
- The current web-based view is an MVP, a proper UI should be developed.
- A browser extension could be developed to redirect to the mirror if available when visiting a profile.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.

  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
Does not apply

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

   - Nicolás I. Schaievitch - nicolas.schaievitch@gmail.com - https://github.com/nschaievitch/ - Full stack developer

* How did you learn about our microgrant program?

It was recommended to me by a friend.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

  Does not apply

**Comment by ErinOCon** [comment]
Hi @nschaievitch, thank you for your proposal! This grant has been approved. We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by Vaibhuge** [comment]
Hy sir

**Comment by Vaibhuge** [comment]
> Hy sir



> Hy sir
