### ISSUE TITLE
web2-web3  social-media integration

### ISSUE THREAD

**Issue by bolajiscott** [filecoin-project/devgrants#814]
# Open Grant Proposal: `web2-web3 social media integration`

**Name of Project:**
   web2-web3 social media integration

**Proposal Category:**  `integration-adoption` 

**Proposer:** `https://github.com/bolajiscott`

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?: YES

# Project Description
We are building towards web2 social media integration for easy transactions on web 3, statistics has shown from the adoption of cryptocurrency why most users who are coming from the web2 space are been scared performing transactions on addresses that are not been verified , Users most time are always  scared  of loosing their assets  due to sending transactions to wrong addresses. We have come up with a solution that allow transactions to be taken place via social media accounts, we have made Gmail Oauth2 that support TRX transfer, SUPPORT TRC transfer, we plan supporting multiple tokens, Encrypt message for user privacy , Gas fee optimisation, Improved UI , Usage with wallet. Making the DAPP multichain with BTTC. The link below has a demonstration of video how it works ====>   https://youtu.be/OlxVmpP3Lfc

## Value

Having the proposed project worked out will welcome more people to the web3 space community , a lots of users are been scared on 3rd party leveraging on their data. filecoin integration has come to fix the worries of data breach on privacy securities  more reason we considering our deployment mode based on this.

 The entire team strongly believe on the adoption of the project with the testing we have done and surveys.

if we are unable to get more technical supports as required, we plan involving some higher levels and adoptions of technology which might require us having access to api services 

## Deliverables

The completed projected will be a web based and mobile project. The basic functionality of the project is to accept social media integration as a mode of transaction tier for transactions. every users can perform transactions from their social media handles with encrypted  integration.

## Development Roadmap

  After completion of all the mile stone ,we expect all the integrations should have been completed and properly tested. currently we only have the Gmail Oauth working for transaction, we plan integrating multiple coin transactions, twitter integration as soon as project commenced.

3 People 
We have the frontend dev ( UI development)
                     QA Team  ( web & App testing)
                      Backend Dev ( web3 integration)

       
       

currently we plan using 4 months for our total developments.
 Aug 20, 2022 - october 20, 2022 ( completion of web app & Testing)
October 25 ,2022 - Dec  20,2022 ( completion and integration of mobile app for both ios and android)

## Total Budget Requested

$10,000
 First Mile
$1500 ( $500permonth*3 dev for the first month ) * 2 months  = $ 3000
$2,000 ( rentage of workspace  for 4months(Internet  & Power supply inclusive)

 Second MIle ( $500permonth * 5 dev for the second mile , which include hiring of mobile developers,which are not part of the early stage frontend developers in the project)
===> $2500*2months for total project completion ( $5000)

## Maintenance and Upgrade Plans

we plan bringing more dev on board the  more we expand on our development, currently we are working on making our web app available for use for everyone. which will be among our plans for the first mile stone , before transitioning to mobile for android users and ios in the last stage of our development. filrcoins will be used as main data storage for the projects. All users that have the app installed on theor devices will have premium security updates.

# Team

## Team Members

 Bolaji Ogidan

  mumeen azeez

azeez onikepe

Hakeem Kazeem

 https://hackathon-mum33n.vercel.app/

## Relevant Experience

Every member of the team has over 4years experience working as a developer, who has worked on various live projects in the web3 space and fintech industry. we have also attended and won  web3 hackathons conducted around. we have been able to demonstrate our expertise in different level  of projects done so far , some of which are products available in the playstore.

## Team code repositories
https://github.com/mum33n/hackathon

https://github.com/bolajiscott/chainlink-nft
https://github.com/hakymulla/ChainLink_Hackathon_2022
https://github.com/ZilSBT/Zilliqa-Soulbound-Project

# Additional Information

The grants was been discussed from our last meetup in the web3 community

      bolajiscott@yahoo.com

we have basic demosntrations illustrated in a youtube form on our current progress and what we also looking forward to integrate  in future, to enable more users using our product.    link ============>  https://youtu.be/OlxVmpP3Lfc

**Comment by realChainLife** [comment]
Hi @bolajiscott thank you for your proposal. We will not be funding the work outlined here as its unclear how the projects aims to, or will benefits from an IPFS / Filecoin integration. I'll be closing this issue at the time, but you're welcome to submit a new proposal with a focus on Filecoin utility in the future.
