### ISSUE TITLE
RFP Application: FVM - Filecoin Wallet: Phoenix

### ISSUE THREAD

**Issue by IPFSUnion** [filecoin-project/devgrants#815]
# RFP Proposal: `FVM - Phoenix`

**Name of Project:** Phoenix

**Link to RFP:** https://github.com/filecoin-project/devgrants/blob/master/rfps/fvm-open-tools-infra.md

**RFP Category:** app-dev

**Proposer:** [@IPFSUNION](https://www.ipfsunion.cn/)

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes

# Project Description

Phoenix is a Filecoin wallet implemented on Web3 to meet the needs of Filecoin-based secure and usable websites, 
available as a browser plug-in. It provides the simplest but most secure way to connect to filecoin-based applications. You are always in control when interacting on the new decentralized web.

On security, Phoenix generates passwords and keys on your device, so only you have access to your accounts and data. You always choose what to share and what to keep private.
It also allows users to manage accounts and their keys in a variety of ways, including hardware wallets, which can avoid mass account thefts.

On the network side, Phoenix comes pre-loaded with fast connections to the Filecoin Network with [Infura](https://docs.infura.io/infura/networks/filecoin). This allows you to get started without synchronizing a full node.

Furthermore, we intend to put the implementation of NFTS and swaps in the next phase, which will not have a definite time estimate yet, but not too far away.

## Value

- allow users to quickly trade Filecoin to attract more users

- swaps provide a better DeFi experience for the Filecoin Ecosystem
    - A simple, streamlined experience reduces friction for new token users, bringing more people into DeFi. It enables more trades faster by providing an optimized path for fees, and most importantly, bringing greater transparency and efficiency to the DeFi on Filecoin. This amount to a better network for all which with fewer fees and reduced network congestion.

- deepen the collaboration between Filecoin and NFT
    - When FVM goes live, the cross-chain communication between the Filecoin and Ethereum ecosystems allows all dapps that already use IPFS and Filecoin, as well as the vast majority of NFT's, to be well connected

- Phoenix is a microcosm of the metaverse, and in the future it may not just be a wallet, but a tool for connecting the Metaverse.

## Deliverables

We want to build a Filecoin wallet for users that can:

- import or create wallet by mnemonic
- create, import and export wallet address
- check FIL balance 
- send and receive FIL
- display transactions history

Further:
- NFTS && Swaps
- mobile application development on both Android and iOS devices

## Development Roadmap

| Milestone No. | Milestone Description | Funding | Estimated Timeframe |
| ------------- | --------------------- | ------- | ------------------- |
| 1             | Market Research and implementation of display contents (address, balance, transaction history, etc)     | $12500      | 4 weeks             |
| 2             | Implementation of the core transaction      | $10000      | 4 weeks             |
| 3             | Library release and deliverable demo, videos and documents | $10000      | 4 weeks             | 
| 4             | Official launch and subsequent maintenance and update     | $7500           | 4 weeks             |

For the 1. and 2. milestone, there will be 2 persons (frontend developer, and UI designer) working full-time and 1 person (backend developer) working part-time together with the project leader.

And for the 3. milestone, 2 full-time person (frontend developer and project leader) will be working on finishing all the deliverables.

Lastly, the 4. milestone holds time for all upgrades that will happen on Filecoin（FVM） and possible changes to Phoneix.

## Total Budget Requested

$40000

## Maintenance and Upgrade Plans

The project will be open source after the browser plug-in version is developed, and our team will work with the 
community to steadily maintain code and keep updates.

# Team

## Contact Info

Email: tech@ipfsunion.cn

## Team Members

- BiSheng Mao : Team leader
- JiangHu Liu : Project leader
- JiaLu Sun  : Backend developer
- YanYan Fu : Frontend developer
- Huan Shen : Backend developer
- Shun Wang : UI designer

## Team Website

https://www.ipfsunion.cn/zh/

## Relevant Experience

We already have experience with building apps on Filecoin as we have been a part of Wave 2 grant program. 

We developed [Filscout]((https://www.ipfsunion.cn/)), a Filecoin blockchain explorer and data service platform.

**Comment by ErinOCon** [comment]
Hi @IPFSUnion, this grant has been approved! We will send an email to discuss next steps.
