### ISSUE TITLE
Next Step Microgrant : web3Box

### ISSUE THREAD

**Issue by jasmynhcc** [filecoin-project/devgrants#816]
### 1. What is your project? (max 100 words)
This is a decentralized application built on the Ethereum/Polygon blockchain, it works like Dropbox or Google Drive by allowing users to securely store their files on the blockchain using IPFS/Filecoin Technology .

### 2. Project links
  
Link to Github repo:
https://github.com/jasmynhcc/web3Box
Link to demo or website, if applicable:
Not yet, you can follow our README to configure it yourself

MIT.
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
This is a project similar to Dropbox, all data will be stored in the IPFS/Filecoin network through web3.storage and recorded through the blockchain.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We need to deploy our contracts on multiple chains and pay the corresponding fees, and at the same time optimize the UI/UX interaction performance of the website, so that users can perform data operations on different blockchains, and also optimize the data workbench to facilitate data View, delete, modify and other operations

- Deploy and test multiple blockchain contracts
- Optimized website for multi-chain support and related UI/UX features
- Improve the user's data workbench to facilitate data addition, modification and viewing operations

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  jasmynh , https://github.com/jasmynhcc, jasmynh@163.com
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @jasmynhcc, thank you for your proposal! This grant has been approved. We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
