### ISSUE TITLE
RFP Application - Arock Explorer

### ISSUE THREAD

**Issue by tanukiroku89** [filecoin-project/devgrants#817]
# RFP Proposal: `Blockchain explorer`

**Name of Project:** `Arock Explorer Refactor & API as a service`

**Link to RFP:

**RFP Category:** `app-dev`

**Proposer:** `tanukiroku89`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes

# Project Description
Our team had developped the existing block explorer [arockpool.com](https://arockpool.com/) and it went live a year ago and kept running since then. It uses python3 and adopts microservice architecture, redis and kafka as cache and message middleware, flask and mongo to provide on-chain data services. Main users came from miner sector for its data service and profit/trend calculator. Since the Filecoin vitural machine (FVM) upgrade will dramatically extend the filecoin agility and usability, and it is coming soon, we have re-evaluated the exisiting platform structure and plan to make it more community and developer friendly with modern explorer features like testnet support, graphQL data API, RPC endpoint service, data dashboard refactor, smart contract verification & decompiler integration.

## Deliverables
1.A full-featured Multi-platform community-friendly open source block explorer which provide block scan, block chain status dashborad and GraphQL data API  system will be developed.

* Dashboard refactor to be more user-friendly.
* Database optimization to support faster block, message, order, mempool query.
* Testnet explorer.
* GraphQL API for developers and projects.
* Smart contract viewer module, including viever, verifier, and contract info including Nametag, Comments from twitter and other social medias.
* Filecoin RPC endpoint subscription 
* Open source repository and detailed documentation.

## Development Roadmap

| Milestone 1 | Milestone Description |HC| Funding | Estimated Timeframe |
| ------------- | --------------------- |--- | ------- | ------------------- |
| 1             | Dashboard refactor       |2 | $12,000      | 4 weeks             |
| 2             | Database refactor       |2 | $12,000      | 4 weeks             |
| 3             | Testnet explorer       |2 | $12,000      | 4 weeks             |
| 4             | GraphQL API for both mainnet and testnet      | 4| $60,000      | 12 weeks             |
| 5             | API Documentation     |  1|$3,000      | 3 weeks             |
 
| Milestone 2 | Milestone Description |HC| Funding | Estimated Timeframe |
| ------------- | --------------------- |--- | ------- | ------------------- |
| 1             | Explorer performance optimization       |1 | $6,000      | 4 weeks             |
| 2             | User and API subscription module      |  3|$24,000      | 8 weeks             |
| 3             | Smart contract explorer module      |  4|$66,000      | 16 weeks             |
| 4             | RPC endpoint subscription      |  2|$16,000      | 6 weeks             |
| 5             | Developer Documentation     |  1|$4,000      | 4 weeks             |

## Total Budget Requested

List the total proposed funding amount (currently in USD, eventually can be a distribution between USD/FIL)
USD$215,000 equivalent

**M1 total budget:** $99,000

**Timeline:** End of Nov 2022

**M2 total budget:** $116,000

**Timeline:** End of Mar 2023

## Maintenance and Upgrade Plans

**Maintenance:** Since we already have an existing valid product, We have applied and been granted migration and startup credits from AWS Singapore for the migration & infrasructure cost of M1 and M2 this year.  

**Upgrade:** We will collect community feedbacks after the M1 goes live and confirm the upgrade plan after M2.

# Team

For each team member(s), please list name, email, Github account, and role in the project.

| Name | Email |Github| Role |
| ------------- | --------------------- |--- | ------- |
| Tony             | tony@arockpool.com       |@tanukiroku89 | Founder/CTO     |
| Zovlian             | Zovlian@arockpool.com       |@littletiger1112 | UI/UX     |
| Travis             | travis@arockpool.com       |@heemoe | Frontend Engineer     |
| Angulia             | anguliachao@gmail.com     |@Anguliachao | Fullstack Engineer     |
| Edison             | superedison99n@gmail.com       |@SuperEdison | Backend Engineer     |
| Timothy             | timothy@gmail.com       |@Hello2021Year | Backend Engineer     |
| Wayne             | wayne@arockpool.com       |@zhubuz | WASM developer     |
| Leo             | leoknight.sg@gmail.com       |@Leoknight | Fullstack Engineer     |
|              |        | |      |

## Team Website

* [arockpool.com](https://arockpool.com/)

## Relevant Experience
We previously worked on [https://arockpool.com/](https://arockpool.com/) for around 1.5 years. Alongside this explorer, our team members have also worked on a few other projects on blockchain infra, wallet, DeFi, GameFi, NFT DAOs projects.

We are a team with 8 years of design and software engineering experience in average. During last 3 months, we have talked to many miners and developers about what kind of explorer they really need. Our passion makes us a good team to work on web3 storage infra tooling space.

## Team code repositories

* [Github Repo](https://github.com/arockpool/)

## Additional information
We would like to be part of this program in order to:

* contribute to the growth and expansion of the Filecoin ecosystem
* transform our project to be fully open source
* provide a useful Filecoin GraphQL API to community users with low cost
* have an early exposure to FVM related development.

**Comment by ErinOCon** [comment]
Hi @tanukiroku89, thank you for your proposal! We will provide an update once our review is complete.

**Comment by eshon** [comment]
Hi @tanukiroku89! We have a question...

When looking at this miner https://arockpool.com/en/chain/storagePool/f01080137

Where does the wallet balance and adjusted power come from? Because when looking up this short ID in Filfox or Filscan there are different results:

https://filfox.info/en/address/f01080137
https://filscan.io/address/general?address=f01080137

**Comment by tanukiroku89** [comment]
> Hi @tanukiroku89! We have some questions...
> 
> 1. Why are your top miners so different from the ones listed at Filfox?
> 
> Filfox: ![Screen Shot 2022-08-17 at 1 56 59 PM](https://user-images.githubusercontent.com/1017762/185112706-ba7af00a-09b1-45ed-bfb3-aa38b273f8b8.png)
> 
> Arockpool: ![Screen Shot 2022-08-17 at 1 56 42 PM](https://user-images.githubusercontent.com/1017762/185112716-58a2462f-7c3d-4f0e-a13f-eac5ab691cae.png)
> 
> 2. When looking at this miner https://arockpool.com/en/chain/storagePool/f01080137
> 
> Where does the wallet balance and adjusted power come from? Because when looking up this short ID in Filfox or Filscan there are different results:
> 
> https://filfox.info/en/address/f01080137 https://filscan.io/address/general?address=f01080137

Hi Eshon,

For question 1, it is for miner ranking, calculated with pooled miner data, which you can also check such data on Filscout: 

![image](https://user-images.githubusercontent.com/108316080/185574028-fd521351-c69e-44aa-bdeb-824a912b5c29.png)

Is calculated based on node data:

![image](https://user-images.githubusercontent.com/108316080/185574248-66bba1d5-1126-4945-8ff8-134b733706be.png)


2. as for https://arockpool.com/en/chain/storagePool/f01080137 , I have check with data team, there are some wrong data filterting with outdated data. The  team is struggling on updating it. This storage pool node f01036920 should have changed its owner and migrate to another storagePool account, owner changed to f01860588. We will update the mongodb database as soon as possible.

https://filscan.io/tipset/pool-detail?address=f01860588

**Comment by ErinOCon** [comment]
Hi @tanukiroku89, thank you for the additional information! We will not be moving forward with a grant for this project at this time. Typically, we do not provide grant support at this level to block explorers. We would be happy to review a proposal for a project that is smaller in scope that helps build more open source experiences with Filecoin. 

Wishing you the best with your project!
