### ISSUE TITLE
YSchool: Educational Video Series/Course for IPFS/Filecoin

### ISSUE THREAD

**Issue by sivia-yschool** [filecoin-project/devgrants#818]
# Open Grant Proposal: `Educational Video Series/Course for IPFS/Filecoin`

**Name of Project: YSchool**

**Proposal Category:** `community` 

**Proposer:** `sivia-yschool`

**(Optional) Technical Sponsor:** `NA`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** "Yes" 

# Project Description

YSchool is an education platform for Blockchain and Science learners. Since its inception in 2019, it has taught more than 100 K students across India. YSchool has more than 100k users on its mobile application. YSchool has faculty with numerous years of experience which makes it the go-to platform for learning. With the amalgamation of offline and online YSchool has a mass reach. 

YSchool is the product of stellar work from the team behind Edusquare which was co-founded in 2008. Edusquare has helped more than 400K students get admission to their dream engineering colleges. YSchool has the expertise of more than 15 years behind its leading team. 

YSchool has an official association with the state govt of Himachal for educating engineering students. These partnerships help reach a wider audience among engineering aspirants. 

**Key Stats:**

Total Users: 105K
 Average user Engagement time/ day: 1 h and 10 mins 
App users from 94 countries and 1120 cities of the world

User Review
Rating on Google play store: 4.4+
Number of Reviews: 2000+

Content details : 
Number of Videos: 30,000+
Duration of content: 10,000 plus hours 

**Achievements:**

- Selected to present in Beijing under Startup India
- Association with various State Governments
- Coverage in Forbes India, Yourstory & INC42
- Czars of North By Hindustan Times & Award by Dainik Bhaskar 
- Emerging Company Awards 2021 by IAF (Indian Achievers Forum)
- Member of IAMAI (Ed-tech council) for education policies in India

## Value

We will be creating an educational video series/course on IPFS/Filecoin. The IPFS/Filecoin educational video series will be focused on creating high-level awareness and developer-focused. We will have two modules in the series:

1. It will focus on the introduction to the IPFS/Filecoin ecosystem and how to get started in the IPFS/Filecoin ecosystem.
2. The second module will be purely practical and focused on integrating IPFS/Filecoin and building solutions using IPFS/Filecoin.

It will help developers have a deep understanding of the development on IPFS/Filecoin and help them build projects on IPFS/Filecoin and integrate in their projects. We will use a user-friendly visuals to create an attractive onboarding solution into the ecosystem. We will host the course on our application which has more than 100K users resulting new developers joining into the ecosystem. We will leverage our wider user base for the promotions along with reach through our partner network and official govt partnerships

We will help the builders in integrating the IPFS/Filecoin by providing the direct support and knowledge through this course.

## Deliverables

1. 25+ hours of curated content hosted on our application
2. Minimum reach to 25K developers
3. Minimum 10K enrolled developers in IPFS/Filecoin course

## Development Roadmap

Phase 1: Requested amount ($15,000)
Time: 1 month

1. Research part about the content to the curated.
2. Finalizing the course structure and content modules.
3. Getting the approval of the IPFS/Filecoin team for the course structure

Phase 2: Requested amount ($15,000)
Time: 2 months

1. Content creation of modules that needs to be created from scratch
2. Launch of course 
3. Promotion of course among the entire user base.
4. Send customized notifications to the app users for the course promotions
5. Activation on social media handles for the partnership course promotions.

Phase 3: Requested amount ($10,000)
Time: 3 months

1. Activate the alumni network for the promotions
2. 4 online meetups to promote the course
3. Townhall promoting grant infrastructure for builders on IPFS/Filecoin.
4. Distribution of courses to students at different colleges through our network.

Phase 4: Requested amount ($10,000)
Time: 3 months

1. Promotion of IPFS/Filecoin events and meetups through the entire userbase
2. Monthly events and meetups for spreading awareness about IPFS/Filecoin 
3. Promoting and educating about hackathons in partnership with IPFS/Filecoin to promote development. 
4. Partnerships inside the ecosystem to assist on-boarding of new users and promote their participation

## Total Budget Requested

We are looking for a total amount of $50,000. The funds will be used for the following:

1. Tech infrastructure 
2. Events
3. HR cost which includes:
 a. Educators 
 b. Support team
 c. Back-end team
4. Bounties
5. Miscellaneous

## Maintenance and Upgrade Plans

We will host this course for a minimum of 5 years plus update of content for the next two years. We will keep on adding the technical tutorials for new additions in IPFS/Filecoin ecosystem.

# Team

## Team Members

1. Sivia Goyal CEO &CHRO
 Sivia is MBA from MDI Gurgaon. She has 8 yrs of experience in IT / education HR / PR / academic ops and is responsible for assembling a stellar team at YSchool. Scaled up Yschool App to 1 lac + users by spearheading Product + User Interface team 

2. Deepak Goyal, Chief Educator
Deepak is a B.Tech Computer Science graduate from IIT Delhi and an educationist. He has been helping students fulfill their dreams of favorite engineering college admission for the past 10 years. He has helped more than 100K students through his network of coaching centers.

3. RK Goyal, COO
Mr. RK Goyal is an MBA and also did his masters from IIT Roorkee in power systems. He is a key element in all the operations for such a wider student base of more than 100K students. He has 40 yrs of experience in the Real Estate/ education Operational Excellence/ Power Sector. He has worked with various Govt companies and has successfully launched multiple ventures.

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/sivia-goyal-5447a919/
https://www.linkedin.com/in/deepak-goyal-1511ab7/
## Team Website

https://yschool.in/

## Relevant Experience

Team is experience of more than 15 years in the education sector along with partnerships with multiple govt. and strategic partnerships. We have already collaborated with Neo and Celo for their respective courses.

## Application Links: 

Google Play Store: https://play.google.com/store/apps/details?id=com.saathi.edusquare&hl=en_IN&gl=US

Apple Play Store: https://apps.apple.com/in/app/yschool-the-learning-app/id1559868429

# Additional Information
How did you learn about the Open Grants Program? Website
Please provide the best email address for discussing the grant agreement and general next steps. partnerships@yschool.in

**Comment by realChainLife** [comment]
Hi @sivia-yschool thank you for this proposal. We're still evaluating this and we would like to learn more about your project, specifically: 

- Is the goal to build a course or curriculum with multiple learning paths? 
- If building out beginner friendly content, what's the differentiation from other education programs in development? 
- What's the type of audience of in the community, how would you determine course usefulness for learners?
- What's the expected measurable outcome of launching the course? ( X number of expected participants, X number of learners referred to hackathon program) etc

**Comment by sivia-yschool** [comment]
Hi @realChainLife thank you for your questions. Please find the answers below:

1. Is the goal to build a course or curriculum with multiple learning paths?
Answer: Yes Sonia we are looking to build different learning paths like introduction to Filecoin ecosystem, How to integrate the IPFS/Filecoin into the tech stack, etc. Going forward we will add FVM learning track as well. We will target both technical and non-technical people through this course.

2. If building out beginner friendly content, what's the differentiation from other education programs in development?
Answer: We are into the education sector for the last 15 years and truly understands the needs of the learners. We will design the structure with step by step guides for all aspects of Filecoin ecosystem. We will provide direct call and whatsapp support to the community to better cater to the learning needs.

3. What's the type of audience of in the community, how would you determine course usefulness for learners?
Answer: The community is majority engineers, people from technical background. We have crypto enthusiasts as well which forms the small proportion. We will use the quiz stack already available in our application to determine the impact and accordingly make the additions in the structure.

4. What's the expected measurable outcome of launching the course? ( X number of expected participants, X number of learners referred to hackathon program) etc
Answer: We will reach to a minimum of 100K developers. A minimum of 10,000 will join the course. We will help them build their projects with Filecoin integration and a minimum of 50 projects will integrate the IPFS/Filecoin after the completion of the campaign.

**Comment by ErinOCon** [comment]
Hi @sivia-yschool, this grant has been approved! We will send an email to discuss next steps.
