### ISSUE TITLE
Next Step Microgrant : DeSign

### ISSUE THREAD

**Issue by fanxifen** [filecoin-project/devgrants#819]
### 1. What is your project? (max 100 words)
DeSign is a decentralized signing platform. Users can sign the corresponding information according to the template (w-8ben, invoice) on the platform, and finally generate cid data stored in IPFS/Filecoin, and support chaining on the polygon network The contract is signed on the chain, and the fairness, notarization and uniqueness of the signing are guaranteed through the chain.

### 2. Project links
  
Link to Github repo:
https://github.com/fanxifen/DeSign
Link to demo or website, if applicable:

tips: We are now using the public front-end template named "Web3 Starter Kit"

not yet, This is a test signed file produced by the platform: https://ipfs.io/ipfs/bafybeig3dbco53zlotrqv5on7f52suangtq5urybypbsjfgcylqln73ifi

MIT
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
The document signed by the user will be displayed to the user through cid. Our template image will finally generate data through image technology based on the information entered by the user and store it in IPFS/Filecoin through nft.storage
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We have now implemented file signing based on w-8ben, and users can enter the corresponding information on our platform to generate files stored in IPFS/Filecoin like this :  https://ipfs.io/ipfs/bafybeig3dbco53zlotrqv5on7f52suangtq5urybypbsjfgcylqln73ifi

Once funded, we will do make these plans:
1:  Template selection to support multiple templates (invoices)
2:  Write the contract code to record the signer 
3:  Sign the cid information of the files to the polygon network. 
4:  Redesign the overall website

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  Fanxifen, https://github.com/fanxifen.  fanxifen@outlook.com
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @fanxifen, thank you for your proposal. This grant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
