### ISSUE TITLE
Next Step Microgrant : IStorage

### ISSUE THREAD

**Issue by ZhangPeibin** [filecoin-project/devgrants#820]
### 1. What is your project? (max 100 words)
IStorage is building decentralized storage aggregation layer . IStorage designed to establish a data metaverse.
Unit of data stored on IPFS and Filecoin and minted in the blockchain, proving that a digital asset is unique and can be sold or bought, or can be shared for profit.

### 2. Project links
  
Link to Github repo:
https://github.com/ZhangPeibin/IStorage_web
Link to demo or website, if applicable:
https://www.istorage.one/

MIT
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  We use nft.storage as the default storage choice and also support web3.storage. We will add more reliable IPFS/Filecoin nodes to provide reliable storage for user data

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will use this funding to improve the following areas:
1.  Support data transfer from other storage chains (like AR to Filecoin)
2.  Increase the contract function of the Ethereum chain, contract test deployment and other costs
3.  The redesign of the overall website, more with web3hua

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes

### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
2022-Wanxiang-Blockchain-Spring-Hackathon  PL  third prize
https://github.com/wanxiang-blockchain/2022-Wanxiang-Blockchain-Spring-Hackathon-Istorage
https://wxblockchain.medium.com/2022-wanxiang-blockchain-spring-hackathon-wrapped-up-on-june-12th-5b61a1645823 (search Istorage )

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  peibin, web3 ecological builder, web3 ecological researcher, IPFS/Filecoin ecological contributor ， [wiki4zhang@gmail.com](mailto:wiki4zhang@gmail.com) , https://github.com/ZhangPeibin

* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @ZhangPeibin, thank you for your proposal. We will not be moving forward with a grant for this project at this time. Please feel welcome to re-apply once the final report is submitted for your Cid.Graph project.
