### ISSUE TITLE
Next Step Microgrant : Cid.Graph

### ISSUE THREAD

**Issue by ZhangPeibin** [filecoin-project/devgrants#821]
### 1. What is your project? (max 100 words)
Cid.graph is a data infrastructure service for developers/companies, providing a finely defined data stack and easy-to-use APIs, providing easy-to-use web3-based data solutions to connect web 2 applications.

### 2. Project links
  
Link to Github repo:
https://github.com/ZhangPeibin/cid.graph
Link to demo or website, if applicable:

MIT
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
 We support users to store data on IPFS/Filecoin through nft.storage. We plan to add more free storage services to support users to develop data storage, and provide paid services to support enterprise users.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. Hire a Golang engineer to develop our backend service
2.  Add at least 3 pin nodes to increase reliable service for user data
3.  Optimize and improve the overall website
4. Support polygon network (currently supports nervos testnet)

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
Filecoin China Hackathon 
we won PL's Outstanding Potential & nervos third prize
https://twitter.com/Filecoin/status/1554491609668100098

More than 600 geeks participated and 11 teams were finalists.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  peibin, web3 ecological builder, web3 ecological researcher, IPFS/Filecoin ecological contributor ， [wiki4zhang@gmail.com](mailto:wiki4zhang@gmail.com) , https://github.com/ZhangPeibin

* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @ZhangPeibin, this grant has been approved! We will be in touch by email to confirm payment details.

**Comment by ErinOCon** [comment]
Hi @ZhangPeibin, the final grant report for this project is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please reach out with any questions.

**Comment by ZhangPeibin** [comment]
> Hi @ZhangPeibin, the final grant report for this project is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please reach out with any questions.

okay!
