### ISSUE TITLE
Next Step Microgrant :IceFireDB

### ISSUE THREAD

**Issue by gitsrc** [filecoin-project/devgrants#822]
### 1. What is your project? (max 100 words)
IceFireDB is a database built for web3 and web2. The core mission of the project is to help applications quickly achieve decentralization and data immutability.The storage layer supports IPFS, libp2p used by network networking,IceFireDB strives to fill the gap of the decentralized stack, making the data ecology of web3 applications more complete, and making it easier for web2 applications to achieve decentralization and data immutability.

### 2. Project links
  
Link to Github repo: https://github.com/IceFireDB/IceFireDB
Link to demo or website, if applicable: https://www.icefiredb.xyz/

MIT Open Source License
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
In the IceFireDB project, libp2p is used for p2p networking of network nodes, and p2p-pubsub is used to build a decentralized message subscription system. In the storage layer, IceFireDB supports the construction of KV storage on IPFS, and is decentralized based on KV and coding technology Construction of Redis database data structure.

 
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will use this funding to improve the following areas:
1. Based on the ipfs-log、ipfs-crdt technology, the command broadcast function is added for the NoSQL database scenario,build conflict-free NoSQL database.
2. Enrich the official website of IceFireDB and establish the document center of icefiredb.
3. Provide clear descriptions of tools and libraries affiliated with project and how incorporated into icefiredb technical design(for NoSQL).
4. Incorporate building documentation for the developer tooling(for NoSQL).
5. Compare and contrast to similar databases in the market (i.e. OrbitDB and ThreadDB)

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  yes

### 6. Does your proposal comply with our Community Code of Conduct?

yes

### 7. Links and submissions

2022-Wanxiang-Blockchain-Spring-Hackathon Protocol Labs First Prize：

https://github.com/wanxiang-blockchain/2022-Wanxiang-Blockchain-Spring-Hackathon-IceFireDB

https://wxblockchain.medium.com/2022-wanxiang-blockchain-spring-hackathon-wrapped-up-on-june-12th-5b61a1645823

Web3 Infinity Hackathon: https://devpost.com/software/icefiredb

Data DAO Hackathon: https://dorahacks.io/hackathon/27/detail 

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
libiao, IPFS/Filecoin ecological contributor ,web3 ecological researcher and builder, corerman@gmail.com, https://github.com/gitsrc
* How did you learn about our microgrant program?
filecoin and friends
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by gitsrc** [comment]
@ErinOCon Excuse me, can we continue this next step microgrant?

**Comment by ErinOCon** [comment]
Hi @gitsrc, thank you for notice of the updates! Can you confirm which database you will be building out with this grant (i.e. NoSQL, SQL, SQLite)?

**Comment by gitsrc** [comment]
> Hi @gitsrc, thank you for notice of the updates! Can you confirm which database you will be building out with this grant (i.e. NoSQL, SQL, SQLite)?

@ErinOCon  Thanks for your reply, we will use for nosql build.

**Comment by ErinOCon** [comment]
Thanks, @gitsrc! This microgrant has been approved! Look out for an email to confirm payment details. 
 
Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by gitsrc** [comment]
@ErinOCon  Thanks for your reply, thank you filecoin for the project funding.
