### ISSUE TITLE
Next Step Microgrant :CloudSlit

### ISSUE THREAD

**Issue by gitsrc** [filecoin-project/devgrants#823]
### 1. What is your project? (max 100 words)

CloudSlit aims to build a global web3 decentralized zero trust security network system to help users regain the private security information eroded by giants under web2, so that the current global hot zero trust security network technology can better help users master their own security privacy data in combination with web3, and give users a good zero trust security network products and platform experience.

### 2. Project links
 
Link to Github repo: https://github.com/CloudSlit/cloudslit
Link to demo or website, if applicable: https://dash.cloudslit.xyz/

MIT Open Source License

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
In the CloudSlit project, the data storage uses Filecoin's web3.storage to store user data decentralized. Our nodes achieve automatic networking through peer discovery, routing through libp2p kademlia DHT and IPFS networks, and data and message synchronization between multiple nodes through libp2p's PubSub module.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We will use this funding to improve the following areas:
1. The current contract is based on nervos, adapting the contract to the Ethereum testnet.
2. Optimize smart contracts to reduce gas costs and support hot contract updates. 
3. Learn fvm ,when fvm can support evm contract, we adapt it.
4. Enrich website construction and build a document center.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

yes

### 7. Links and submissions

2022 Filecoin China Hackathon

We won a total of three awards, namely the most potential award in the filecoin track, the first prize in the nervos track, and the most ambitious project award.

[https://twitter.com/Filecoin/status/1554491609668100098](https://twitter.com/Filecoin/status/1554491609668100098)

[https://mp.weixin.qq.com/s/VjbtGJMMnfFOO1VottQ7sw](https://mp.weixin.qq.com/s/VjbtGJMMnfFOO1VottQ7sw)

More than 600 geeks participated and 11 teams were finalists.

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
libiao, IPFS/Filecoin ecological contributor ,web3 ecological researcher and builder, corerman@gmail.com, https://github.com/gitsrc

* How did you learn about our microgrant program?
filecoin and friends

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
     Project is participating in （Web3 Infinity Hackathon）：https://devpost.com/software/cloudslit
   Projects already registered （2022 Wanxiang Blockchain Autumn Hackathon）:  https://www.blockchainlabs.org/week2022/hackathon

**Comment by ErinOCon** [comment]
Hi @gitsrc , thank you for your proposal! This grant has been approved. For next steps, we will be in touch by email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
