### ISSUE TITLE
Next Step Microgrant: <Crow's Nest NFT & Content Storage>

### ISSUE THREAD

**Issue by Tarnauk** [filecoin-project/devgrants#824]
### 1. What is your project? (max 100 words)
Crow’s Nest is an NFT roleplaying game that will be launching on the Polygon Blockchain in which players take on the role of a daring pirate captain, leading his crew towards undiscovered treasures. 

### 2. Project links
  
Link to Github repo:
https://github.com/CrowsNest-Game/nft-storage-example
Link to demo or website, if applicable:
https://crowsnestgame.com/
https://www.youtube.com/watch?v=HgVTZnGiyKo

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

The Github-Repo which is linked was published by Stefan, our blockchain developer, as a basis for our usage of the technologies provided by Filecoin. We will update the repo as we develop our custom solutions for implementing these technologies in our main project which is an nft-based blockchain game. While the game is in closed development, the decentralized storage solution that we will develop for the project will be marked as open source so that other similar projects can adapt to their needs or even improve for everyone else.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- More development time
- Reduce costs and improve security by migrating from centralized database providers to the decentralized storage network
- Implement user profile stored with web3 storage (Username, Avatar, etc.)
- Implement transfer functionality of NFTs stored with nft.storage
- Storage of interactable game components using Web3.storage

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes

  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Andrei Tărnăuceanu, andrei@crowsnestgame.com, [Github](https://github.com/Tarnauk), Company Management
Stefănel Laiu, stefan@crowsnestgame.com, [Github](https://github.com/StefanLaiu), Blockchain & Web Developer
* How did you learn about our microgrant program?
Vivan Chauhan from Polygon Studios was kind enough to forward us to your grant program after one of our meetings.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @Tarnauk, thank you for your proposal! This grant has been approved. We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
