### ISSUE TITLE
Open Grant Proposal - Flaq Academy

### ISSUE THREAD

**Issue by d3fkon** [filecoin-project/devgrants#825]
# Open Grant Proposal: `Flaq Academy`

**Name of Project: Flaq Academy**

**Proposal Category:** Choose one of  `app-dev`  

**Proposer:** `d3fkon`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

### Our Vision

Flaq Academy’s contributors are united by our mission to onboard millions people to Web3.

In India, two-thirds of people are crypto curious. These people deserve a web3 onramp that isn’t fraught with scams and misinformation.

We're making quality web3 education. We're creating quality "explain like I'm five" learning paths backed by a thriving community and SuperteamDAO members 
<p float="left">
  <img src="https://user-images.githubusercontent.com/23007190/183075716-cbac1b1c-f9fb-4a64-83a7-83c58b00f9f5.png" width="170" />
  <img src="https://user-images.githubusercontent.com/23007190/183075733-b440de9b-c4d2-4d32-9492-6ea448126445.png" width="170" /> 
  <img src="https://user-images.githubusercontent.com/23007190/183075750-5b684356-7543-4075-b960-cd725f230e8c.png" width="170" />
</p>

### Why Flaq Academy?

Countless industries from financial services to art and medicine are being reconstructed by the promise of web3 — a paradigm shift to decentralized technologies owned by builders and users.

Education, an industry that has remained more or less the same for a long time is following a similar path.

If we think about it from the perspective of how education has changed with the different versions of the web:

- Education in web1 is equivalent to the knowledge transfer between authorized institutions (think: universities and high schools)
- Education in web2 is centralized platforms distributing education (think edX and Khan Academy)
- Education in web3 is individuals gathering skills from a variety of sources and validating that knowledge on chain in their own wallet (think something like a “proof of skill”)

Flaq opens new doors for a wealth of opportunities for the future of education. For most of history, education has been something only a small percentage of the population has access to. While other institutions provided opportunities for socializing, research, learning, and measurable credentials, it left a lot of people out.

And there are a few good reasons why. Constant education is one.

### **Our Values**

- **Quality over quantity**: We value creating high-quality, 100% free web3 education.
- **Delightful Onboarding**: We value delightful guided web3 onramps. No member should feel lost on what to do next.
- **Pay it forward**: We value giving more than taking. No member should have to learn web3 alone.
- **Decentralized:** All decisions will be taken by the approval of the DAO Members

### **Problem**

Most of the edtech products right now are don't have the right incentive mechanism to stay accessible, high quality and up-to-date.

The traditional model of charging users for attending courses, is broken. This optimizes for increasing the number of people coming through the front doors of the course. Once they are in, there is not much incentive to actually deliver a good learning experience. It quickly shifts from a game of education to a game of marketing.

### **Solution**

We think this can be fixed. This can be fixed with clear crypto-economic incentives that aligns with the actual learning outcomes of the learners. We're creating a Flaq DAO, one that is decentralized and permissionless. What does the Stanford native to the internet look like?

We believe that people learn best together. Our upcoming Web3 courses will feature:

1. **Hands-on experience** with web3 basics, NFTs, DeFi, and DAOs
2. **Cohort based learning** with a group of talented peers in our community
3. **On-chain credentials** upon course completion

Our vision is to enable the next 10M people enter the Web3 space and familiarize themselves with the majority of protocols and applications including IPFS. 

We intend to educate the vast majority of developers & Web3 enthusiasts through:

1. ****Simple explanations of Web3 protocols & concepts.****
2. ****Friendly development tutorials to get anyone up & running in the space.****
3. ****Community projects, hackathons & cohort based courses.****
4. ****Free utility NFTs for devs to unlock more opportunities.****

## Value

Apart from centralized paid platforms, like Udemy, Scalar and Unacademy, there is no one “name” which users associate to learn about web3. Flaq intends to be the go-to platform where web2 users can learn and get accustomed to web3.

Joining our DAO is as simple as signing up on the Flaq Mobile App or the Decentralized Web App.

We expect users on our platform to be first time web3 users, where we  help them do everything from setup their first wallet, learn about and discover DAO’s, join DAO’s, learn about and get introduced to open-source projects, etc. 

We are partnering with various DAO’s to help craft this curriculum and onboard the next wave of web3 users in a seamless way.

Flaq opens new doors for a wealth of opportunities for the future of education. For most of history, education has been something only a small percentage of the population has access to. While other institutions provided opportunities for socializing, research, learning, and measurable credentials, it left a lot of people out.

All courses created by the DAO will be stored on web3.storage
The NFT’s users receive after completing a course will be stored using nft.storage
Some of the tracks planned for launch:

**Non Technical Tracks**
1. Intro to web3
2. Intro to NFT's
3. Intro to DeFi
4. Intro to DAO's

**Technical Tracks**
1. Intro to EVM Development
2. Intro to Development on Solana
3. Intro to NFT.storage and Web3.storage 
4. Interop between chains
5. Using FileCoin as a database medium for web3 apps
6. File Management using FileCoin

## Deliverables

1. Developing the DAO Dashboard to manage the content on the Flaq App
1. Developing technical track courses
2. Developing non-technical track courses
3. Building a learn to earn quest with NFT rewards
4. Building our inaugural cohort-based bootcamp
5. Building our talent collective and job boards
6. Onboarding new contributors to the DAO

All this along with the roadmap planned below

**Target Audience**
We are targeting beginners in web3, as well as web2 developers who are looking at web3. Completion of tracks demands, taking up a 10 point quiz, which would determine the impact of the course on the user. Users also accumulate FLAQ Points for successful completion, which acts as the in-app point to unlock more courses, thus gamifying the system

**Outcome of Flaq**
Being a member of SuperteamDAO, we have the marketing push from SuperteamDAO's socials along the same support from Solana's ecosystem. If our development phase is executed well with your support, we are aiming for 100k app downloads by the end of December, and a steady growth of 40% month on month.
We expect a 30% monthly user retention rate and over 40% of all users completing at least one course on the application. We expect to meet user's demands and have a positive feedback loop of producing more courses as users request for the same

## Development Roadmap

**Phase 1**: **(17,000 USD)**

Launching the first version of the mobile app and a CMS:

1. Designing and developing a mobile application to host data using Textile DB
6. Tipping / Donations for the creators to contribute to creators' economy
8. A dashboard for the content creators to upload their videos on crypto
9. Viewer friendly playback system integration

**Phase 2: (17,000 USD)**

1. Developing launching a web application hosted on IPFS with features mirroring the mobile application
2. We will promote contributors to create content for Flaq
3. Create web3 content in-house
4. Work on a weekly news roll-up covering things happening in web3
10. Build DAO Admin Board - For core members to view stats for various participants 
11. Phase 2 UI/UX revamp to accommodate  for user feedback

**Phase 3:**

**DAO Phase (14,000 USD)**

1. Growing the core-membership of DAO’s
2. Portal to mint membership NFT’s
3. NFT gated events and online sessions
4. Earning NFT’s via completing quests / courses

## Total Budget Requested

Total budget requested to deploy Flaq: 48,000 USD

## Maintenance and Upgrade Plans

We intend to maintain our DAO and create a successful creator economy incentivising the contributors for minimum of 10 years.

# Team

## Team Members

**Ashwin Prasad** - Tech Lead + DAO Contributor + Core Member

Email - [d3fkonmusic@gmail.com](mailto:d3fkonmusic@gmail.com)

Github - [https://github.com/d3fkon](https://github.com/d3fkon)

I’m an Engineering Graduate Gold Medalist from VTU, ranking top 50 in India. 

I’m also a member of Solana’s Superteam DAO, where I contribute and help developers get into the Solana ecosystem. I have led multiple projects in my professional career, consulting for companies like Target, iHeart Media, and TATA. While more relevantly winning the most recent Solana Hacker House and working with a web3 wallet project called Solace. I have been associated in educating various developers via SkillRary, where I helped onboard 10k users on-to web3

The other senior members for this Dao are as follows.

1. Sarthak Sharma - Core Team Member Flutter Developer Senior / Dao Contributor - [https://github.com/affableSarthak/](https://github.com/affableSarthak/)
2. Muaaz Khan - DAO Contributor [https://www.linkedin.com/in/muaaz-khan-284137176/](https://www.linkedin.com/in/muaaz-khan-284137176/)
3. Nisarg Shah - Flutter Developer / DAO Contributor - [https://github.com/Nisarg-18](https://github.com/Nisarg-18)
4. Ankit Negi - NodeJS Developer / DAO Contributor - [https://github.com/ankitn1311](https://github.com/ankitn1311)

Plus 10+ amazing contributors in our DAO who are working on writing learning guides, growing the community, and localizing our content.

Initial videos from our DAO contributors 

https://www.youtube.com/watch?v=z0eqlZVB1Jo
https://www.youtube.com/watch?v=t-H-DM7fzaA

_We intend to produce content in various languages, to break any language barrier that might exist_

## Team Member LinkedIn Profiles

Ashwin Prasad - [https://www.linkedin.com/in/ashwinxprasad/](https://www.linkedin.com/in/ashwinxprasad/)

## Team Website

https://flaq.club

## Relevant Experience

Being a part of SuperteamDAO we help the most promising projects in the **Solana**
ecosystem in the ascending world (India, South East Asia, Eastern Europe, and Africa) launch and grow. We are organized as a co-operative of creatives, developers, and operators who are experienced in launching and growing technology businesses.

## Team code repositories

Our code is completely open sourced and MIT Licensed and actively developed on by me and the rest of our contributors -

[https://github.com/d3fkon/flaq-academy](https://github.com/d3fkon/flaq-academy) (Flutter)

[https://github.com/d3fkon/flaq-gin](https://github.com/d3fkon/flaq-gin) (Go)

# Additional Information

`d3fkonmusic@gmail.com`

**Comment by ErinOCon** [comment]
Hi @d3fkon, this grant has been approved! We will be in touch by email to discuss next steps.

**Comment by d3fkon** [comment]
Thank for your support @ErinOCon. Looking forward to the email and future collaborations!!
