### ISSUE TITLE
Next Step Microgrant : StoryNFT

### ISSUE THREAD

**Issue by rectinajha** [filecoin-project/devgrants#826]
### 1. What is your project? (max 100 words)
One allows readers to write stories, diaries and trade them on the shelves in the form of nft. Users can also purchase their favorite stories, diaries, etc. in the form of nft. All data of users are stored in IPFS/Filecoin through Fleek

### 2. Project links
  
Link to Github repo:
https://github.com/rectinajha/notenfts
Link to demo or website, if applicable:
https://storiesnft.netlify.app/

MIT(Open source)
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
All user data will be stored to the IPFS/Filecoin network through Fleek Storage, and we will also support Nft.storage to support multiple sdk storage methods in the future
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. Improve the NFT trading market
2. Support multi-chain contracts, complete user NFT cross-chain support
3. Add multi-storage sdk integration (nft.storage, pinata)
4. Increase the import and editing of markdown content
5. Added support for multiple data formats (picture, video, voice)

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes

### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  rectinajna , solidity developer, https://github.com/rectinajha , rectinajha@hotmail.com
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @rectinajha, thank you for your proposal! This grant has been approved. For next steps, we will email you to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by rectinajha** [comment]
@ErinOCon ,Thank you for your reply! The email left before is no longer available, this is our new email address :  a0xharrys@outlook.com . please send the payment email again . Thank you very much!

**Comment by rectinajha** [comment]
Hi @ErinOCon   , If you see my message here , please resend a payment email to me : [a0xharrys@outlook.com](mailto:a0xharrys@outlook.com) , Thank you very much!

**Comment by rectinajha** [comment]
Hi @ErinOCon , please resend a payment email to me : [a0xharrys@outlook.com](mailto:a0xharrys@outlook.com) ,Thank you very much!

**Comment by ysongh** [comment]
This person copy my codes from my project. https://github.com/ysongh/StoriesNFT

This person has been creating multiple accounts and copying other people projects.

**Comment by mishmosh** [comment]
@ysongh Noted, we are looking into this now.

**Comment by ErinOCon** [comment]
Hi @rectinajha, we will not be moving forward with a payment for this microgrant application. Unfortunately, it does not meet the program qualifications, specifically #1 (“You’ve built a working prototype”). The demo link in your application (https://storiesnft.netlify.app/) is exactly the same as the one listed in [@ysongh] (https://filecoinproject.slack.com/team/U015UTB9EAK)’s repo, so you didn’t deploy your own instance. We will be closing this issue.
