### ISSUE TITLE
Littercoin: Location Intelligence To Transform Environmental Reporting by Creating an Economic Incentive

### ISSUE THREAD

**Issue by xlcrr** [filecoin-project/devgrants#827]
# Open Grant Proposal: `Littercoin: Location Intelligence To Transform Environmental Reporting by Creating an Economic Incentive`

**Name of Project: Littercoin**

**Proposal Category:** `app-dev`

**Proposer:** `xlcrr`

**(Optional) Technical Sponsor:** `not applicable`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** "Yes"

# Project Description

At OpenLitterMap.com, we are turning cleaning the planet into a game, with real climate rewards. About 1 billion people have access to a device that can make important real-world observations. We have learned how to use these devices to share information, which has resulted in a huge awakening about global pollution. But we have not yet learned how to use these devices to collect real factual information about the world around us. Traditionally, the production of known and mapped information about the world was a practice that was limited to governments and institutions but this approach has imposed incredibly narrow limitations on society that has clearly failed to protect the environment.

Citizen science fixes this. We are turning cleaning the planet into a game to make collecting these real-world observations fun, competitive, climate positive and economically rewarding. We want people to feel empowered to use their device to collect this data however data collection tools and processes, incentives, and visualisations remain significantly underdeveloped. This work is almost entirely done by 1 person, who began researching litter mapping in 2008 after being introduced to GIS while studying Geography at university. Inspired by the open source, open data, and open science values from OpenStreetMap, the concept for OpenLitterMap was developed. After doing 2 masters to develop the methodology, the concept of tokenisation was introduced in 2015 that lead to the tokenisation of the citizen science process giving birth to Littercoin.

In 2021, we received our first funding from Project Catalyst on Cardano and we are currently applying for more funds which you can read about here.

https://cardano.ideascale.com/c/idea/418047

I would love to explore how we could move some of our image data onto the Filecoin ecosystem and evaluate its advantages + disadvantages relative to our current centralised provider (AWS), who have awarded us with credits to host our platform.

## Value

Litter and plastic pollution are increasingly recognised as a ubiquitous global problem but little is being done to involve citizens in the data collection process. On average, current estimates suggest there is about 900 tonnes of plastic entering the worlds oceans every hour. We are looking for partners that can support the development of OpenLitterMap and help us discover new ways that we can benefit from ecosystems like Filecoin to host and store our data. 

Governments and traditional science funding institutions have literally failed to protect the environment and are unsupportive of citizen science which takes authoritative power away from centralised institutions and opens the documentation and ownership of geographic knowledge to society. Crypto has disrupted funding opportunities, and are rightly placed to support the development of citizen science. We have applied the proof of work principle of the production of geographic information for the first time, and reward people with Littercoin for helping to clean up the planet and produce geographic information. But unlike any other token, Littercoin will not be listed on any exchange, is non-tradable, 

By supporting the development of OpenLitterMap, we will be able to include Filecoin on our list of partners, and experiment with storing our 600+ daily uploads on IPFS.

## Deliverables

We need to hire developers with skills in Laravel, Vue, React Native, Tensorflow, and also social media, video editing, graphic and UI UX design.

## Development Roadmap

For a similar project proposal please see

https://cardano.ideascale.com/c/idea/418047

## Total Budget Requested

$200,000

## Maintenance and Upgrade Plans

Too much to discuss here. Could we set up a call to answer any questions?

# Team

## Team Members

Seán Lynch

## Team Member LinkedIn Profiles

linkedin.com/in/seanlynchgis

## Team Website

https://openlittermap.com

## Relevant Experience

15 years developing citizen science

## Team code repositories

https://github.com/openlittermap

# Additional Information

LinkedIn or Twitter

info@openlittermap.com

I would love to set up a call to discuss the project in detail instead of writing another 100th+ grant proposal

**Comment by realChainLife** [comment]
Hi @xlcrr thanks for the proposal. Please email us at grants@filecoin.org and we can arrange the discussion call.

**Comment by ErinOCon** [comment]
Hi @xlcrr, thank you for your time connecting with our team! For next steps, can you provide a development road map for the outlined project? While the link to the separate proposal is helpful context, we would like to review roadmap details that are specific for this scope of work.

Also, if your intention is to use Filecoin for this project, we recommend checking out Estuary or web3.storage!

**Comment by ErinOCon** [comment]
Hi @xlcrr, I hope you are doing well! Do you have any updates or questions for our team?

**Comment by xlcrr** [comment]
Hi @ErinOCon, I will get back to you during the week

**Comment by ErinOCon** [comment]
Thanks, @xlcrr!

**Comment by ErinOCon** [comment]
Hi @xlcrr, do you expect an update will be available by next week?

**Comment by ErinOCon** [comment]
Hi @xlcrr, I hope you are doing well! Do you have an update available?

**Comment by xlcrr** [comment]
Hey team,

We have a lot going on. You can read about our weekly updates here: https://medium.com/@weeklyolm

It is my project but I am working full time elsewhere, hard to find the time to create new documentation at the moment

You can read more about how we budget here:

https://cardano.ideascale.com/c/idea/418047

https://cardano.ideascale.com/c/idea/420186

Money is needed to hire
x1-2 Laravel developer
x1-2 React Native developer
x1 AI developer
x1 Plutus developer
x1 web3 developer
x1 UIUX
x1 Social media manager
x2 Graphic design animation + storytelling

This will result in the production of littercoin which I believe will become the first token that most people earn.

Littercoin is different because it will not be listed on any exchange making it non-tradable. The only way to get Littercoin is to earn it by submitting data to openlittermap.com 

See:
https://opengeospatialdata.springeropen.com/articles/10.1186/s40965-018-0050-y

We would love to include filecoin on our list of partners and explore how we can host image and metadata across the ecosystem to make global data about pollution immutable

**Comment by ErinOCon** [comment]
Thanks, @xlcrr! We will not be proceeding with a grant for this project, but would like to invite you to check out the [Compute Over Data Working Group](https://www.cod.cloud/)! If you have any questions, there is a link to their Slack channel on the website.
