### ISSUE TITLE
Open Grant Application: Orphic Verse

### ISSUE THREAD

**Issue by Orphic-Verse** [filecoin-project/devgrants#828]
# Open Grant Proposal: `Orphic Verse`

**Name of Project: Orphic**

**Proposal Category:** Choose one of `metaverse`

**Proposer:** `Orphic-Verse`

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

Welcome to Orphic, we are building a Foodverse - Our vision is to create a unique virtual experience for Foodies, while creating a new marketing channel for the global Food & Beverage Industry. We are building the first tokenization layer that celebrates Food in Web3 - creating an immersive & gamified experience for users worldwide.

1. BRANDED NFTS IN GAMEPLAY
Orphic will celebrate the iconic dishes of Celebrity Chefs & Restaurants in our Gaming Zone as exclusive Dish NFTs. We are also collaborating with Food companies for our Ingredients section, introducing branded ingredients in special recipes. These NFTs will hold special powers in the gameplay and allow foodies to celebrate their favorite icons.
2. VIRTUAL EXPERIENCES
Orphic will partner with Food businesses to create their first Metaverse location - whether it is a virtual restaurant, event experience, virtual office or a unique gameplay. With each Food Partner, we will work on bringing their brand ethos into the Foodverse - allowing them to interact with global audiences, sell Recipes & Cookbook NFTs, create Online Ordering systems, interactive spaces and much more.
3. PROVIDING REAL LIFE UTILITY TO NFTs
The true test of Food lies in the taste, and the true adoption of Web3 lies in the yumminess of our Food. Orphic strives to provide real life use-cases for NFTs - and Food Businesses can launch special offers, new menus and much more through our Foodverse.

Orphic Verse In Progress: [https://drive.google.com/drive/folders/1oKMr7AkTUea6xiyaVFCt-kQUk10psQBo?usp=sharing](https://drive.google.com/drive/folders/1oKMr7AkTUea6xiyaVFCt-kQUk10psQBo?usp=sharing)

## Value

**For established food brands**, this is an opportunity to re-engerise their users and discover ways of monetisation in Web3. Having a Foodverse presence will enable them to reach out to global audiences, new generations that haven’t yet tried them. This also makes the brand younger and more appealing, and an obvious next step from social media engagement.

**For new & upcoming brands**, Orphic provides the perfect platform to create their first digital impression at no cost at all. They get a chance to showcase their product and use-cases in Web3 and create recall value for audiences that don’t know them yet.

**For Chefs & Restaurants**, we create the perfect window for global recognition. With their culinary skills and fame being limited to their region or social media channels, Orphic allows chefs to go truly global, and create an emphatic entry into Web3. Rather than independent NFT releases, chefs and restaurants get to be part of a Foodverse, where their dish is engaged meaningfully in gameplay.

The opportunity for the Food mavens to come into blockchain and monetise global audiences, rather than local, is tremendous. Taking their food to every corner of the world, Orphic aims to be the ultimate foodverse for the entire industry.

Unlike traditional advertising where brands pay per view to build outreach, Orphic allows them to achieve this through novel methods on the blockchain. We are already seeing the first of Food brands come into the NFT space, with Coca Cola and Taco Bell releasing artworks.

**Action against hunger**

We strongly believe that Web3 Projects can transcend borders and make a positive impact across the world. The massive reach of this industry creates tremendous potential for projects to be more than just entertainment, to work with a purpose.
While Orphic is a celebration of global food, we cannot disregard the growing hunger crisis that has escalated with COVID-19. 1 in 10 people sleep hungry every night, and 811 million humans slept on empty stomachs in 2020.
Orphic aims to be a Game with a Purpose, and work towards the cause of eliminating World Hunger. We are collaborating with celebrities, chefs, influencers & food companies to raise funds and awareness for this cause.

## Deliverables

1. Create Global Reach for F&B Industry : Bringing Celebrity Chefs, Restaurants, popular Cooking Shows & Food Brands to Web3 audiences for the first time through NFTs & Virtual Experiences - giving them a global platform to engage & monetize.
2. Food Partner for Web3 Projects : Curating a Food experience for Web3 projects in the form of special menus for Game characters, and creative F&B catering for Web3 events & parties.
3. Bring NFTs to Life : Application of NFTs in real life, allowing users to swap Orphic NFTs for meals & deals in Restaurants worldwide.
4. Action Against Hunger : Work towards the cause of eliminating World Hunger by partnering with the F&B industry & Web3 projects to raise funds & awareness.

## Development Roadmap

Quarter 3 - ETA September 29th

Amount required - $25,000

1. HDR to URP formatting (Rebuild of base code to allow for VR capability)
2. Creating Orphic Wallet to be able to store NFT's using nft.storage which users can redeem in their favorite restaurants.
3. Orphic Hype Video & UI/UX Redesign to suit Virtual Reality.
4. Private key ownership access (Allowing store owner rights to update stores and grant access rights)
5. Creating map v.1 for the Orphic Verse using blender and Adobe suite.
6. NFT Creation SDK (allowing community to create NFT’s for use and sale within Orphic Verse)

Quarter 4 - ETA December 25th

Amount required - $25,000

1. Creating map v.2 for the Orphic Verse adding more restaurants and elements for users to interact and socialize while earning NFTs.
2. Custom avatar integration (allowing a user to customise their own orphic avatar) all assets will be stored on IPFS.
3. Implementing voice chat feature in orphic Verse to up the socializing game.
4. Adding character interactions and movement (jumping, sitting etc. allowing users to feel a sense of realism while exploring the Orphic Verse. This will require 3D artists and blender software.
5. Optimisation and integration across multiple devices.

Technology Used:

Front End:

**Material UI** or MUI provides a robust, customizable, and accessible library of foundational and advanced components, that enables us to build a design system and develop React applications faster.
**React** is a free and open-source front-end JavaScript library for building user interfaces or UI components.
**EthersJs** is a JavaScript library that allows us to interact with the Ethereum blockchain.

Backend:

**Solidity** is a contract-oriented, high-level programming language for implementing smart contracts
**Hardhat** is an Ethereum development environment.
**The Graph** is an indexing protocol for querying networks like Ethereum and IPFS or in simple words theGraph is an open-sourced software used to collect, process and store data from various blockchain applications to facilitate information retrieval

Design:

**Figma**: Figma is a collaborative browser-based interface design tool, with additional offline features enabled by desktop applications for macOS and Windows
**Blendr**: Blender is a free and open-source 3D computer graphics software toolset used for creating animated films, visual effects, art, 3D-printed models, motion graphics, interactive 3D applications, virtual reality, and, formerly, video games

## Total Budget Requested

$50,000

## Maintenance and Upgrade Plans

We wish to upgrade the product on a quarterly basis making sure the product meets the demands of the metaverse marketing and gaming industry.
Maintenance & security upgrades will continue for the foreseeable future ~5 years.

# Team

## Team Members

Ajay Khanna - CEO & Founder
Sargum Agnihotri - CHO
Brandon Gibson - CTO

3D Designers - Akshay Deswal & Saswata Dutta
UI Designer - Chitra Arora
UX Researcher - Gopi Jaiswal

## Team Member LinkedIn Profiles

Founder - [Ajay Khanna](https://in.linkedin.com/in/ajkhannna)
CHO - [Sargum Agnihotri](https://www.linkedin.com/in/sargam-agnihotri-she-her-89aba5190/)
CTO - [Brandon Gibson](https://www.linkedin.com/in/brandon-lee-gibson)
Lead Designer 3D - [Akshay Deswal](https://www.linkedin.com/in/akshay-deswal-b0031b1b4/)

## Team Website

Website - https://orphic.webflow.io/

Our Instagram - https://www.instagram.com/orphic.menu/

Orphic Verse In Progress - https://drive.google.com/drive/folders/1oKMr7AkTUea6xiyaVFCt-kQUk10psQBo?usp=sharing

We have now partnered with two more restaurants and are in talks with onboarding 4 more restaurants all thanks to Filecoin Foundation and our team.

<img width="906" alt="image" src="https://user-images.githubusercontent.com/108719237/183261042-0e80c8b3-42c9-421a-af5c-a328f0db4535.png">

Orphic verse being designed: Check out our [Instagram]( https://www.instagram.com/orphic.menu/) for more updates

<img width="978" alt="image" src="https://user-images.githubusercontent.com/108719237/183261631-e0df044c-f412-484b-89d1-b6e104a90168.png">

<img width="964" alt="image" src="https://user-images.githubusercontent.com/108719237/183261645-606beac2-c69d-45cf-990e-02dca432fe21.png">

## Relevant Experience

Ajay Khanna also the Founder of 5th Element Hospitality (5EH)
At 5th Element Hospitality we believe that every business can succeed – given the right planning and impetus. 5EH has been set up with an experienced support team of associate consultants to provide services for start ups and operating restaurants, hotels and F&B Retail. Having been involved in a very hands on manner in hotels, restaurants, QSR’s, Industrial cafeterias "5EH" provides complete solutions - Concept validation, Feasibility Study, Financial Modelling, Project Management, Facility Planning, Process Design and re- engineering.

Current projects:

1. Leading South Indian Udupi food brand - restructuring
2. Expansion and Ops Excellence for a boutique resort at Rishikesh
3. Steering committee - Fast Food Convention by Oddbox
4. Design and expansion of food services for a leading student co housing company

At Reliance as the VP of hospitality services.
Ajay Khanna Managed the pan India network of 110 A1 Plazas.
Implemented the conversion of the business from a Trucker loyalty program facility to a highway traveller focus.

## Team code repositories

https://github.com/Orphic-Verse/orphic-app
https://github.com/Orphic-Verse/orphic-api

# Additional Information

As part of our Next Steps having received a microgrant from Filecoin Foundation for our efforts we had decided to apply for an open grant to scale globally.

`orphicassets@gmail.com`

**Conclusively speaking**

The Global Food industry is proof to that. With an estimated market size of $6196.15 billion in 2021, Food has grown from an item of consumption to an active conversation. We now have Food trends based on the consumer’s changing mindset and lifestyle. We have Food workshops not just for cooking recipes, but for understanding food palates & finding other foodies. We have Food Styling & photography as people begin to eat with their eyes first.
Over the past decade, Food has also grown as one of the largest content drivers on Television/OTT and social media networks. The rousing success of cooking competitions like Masterchef & Top Chef, specialised Food channels and Food influencers have spurred extremely loyal fan followings. Audiences are glued to food content - whether it is the making of a cake on Instagram, or Gordon Ramsay critiquing contestants.
COVID-19 has further spurred interest in Food as a global conversation and activity. Locked down in the pandemic, everyone ended up in their kitchens - whether cooking basic meals for survival, or recreating culinary gems they miss from restaurants. As millions scoured the internet for recipes and hacks, Food posts emerged as the largest category on social media - spurring trends like Dalgona coffee, Banana Bread and Pancake Cereal.

How will IPFS, Filecoin, or related technology be used for this project?

We believe in a decentralised future and in Filecoin's vision thus for Orphic Verse Decentralized storage is an extremely essential part of the project, because the infrastructure for this platform needs to enable NFTs with trustless operation, faster speeds, lower costs, improved security, and nearly 100% uptime all of this is solved by using IPFS.

Data needed to run the Orphic Verse, includes all data relevant to the player experience. For starters, all information about their avatar’s appearance this includes customisable aspects like hair, skin colour, height, and accessories for all this we use IPFS.

Then, the digital property symbolised by NFTs – from land plots to digital objects – will require safe and reliable storage space, too. And, there is data on the overall user experience. This can include how much time one has spent in various worlds, which unlocks token gated content: better, new, or different experiences based on the achievements and reputation of the owner. For a seamless user experience (UX) IPFS again takes care of our concerns.

**Comment by ErinOCon** [comment]
Hi @Orphic-Verse, thank you for your proposal. We would like to support the first milestone of this project! We will be in touch by email to confirm next steps.
