### ISSUE TITLE
Next Step Microgrant : DataSharing

### ISSUE THREAD

**Issue by gaorany** [filecoin-project/devgrants#829]
### 1. What is your project? (max 100 words)
DataSharing is a blockchain-based data sharing platform. By using IPFS as our storage bottom layer and through blockchain authorization and authentication, the data is encrypted and shared to recipients through the blockchain.

### 2. Project links
  
Link to Github repo:
https://github.com/gaorany/Dshare
Link to demo or website, if applicable:
https://file-share-dapp.herokuapp.com/files/upload

yes, our project is open-source and use MIT .
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  All data on our platform will be stored through IPFS, and we plan to access storage methods such as nft.storage

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. Add multiple data encryption methods
2. Added a variety of IPFS/Filecoin storage options to support real data storage to Filecoin nodes
3. Added data sharing support for polygon chains
4. Build a community platform to engage users

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes

### 6. Does your proposal comply with our Community Code of Conduct?
yes
### 7. Links and submissions
not yet  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  gaorany ,  solidity developer & react developer. https://github.com/gaorany,  gaoranycos@163.com

* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @gaorany, thank you for your proposal. This grant has been approved! Can you provide an email address to confirm payment details?

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by gaorany** [comment]
> Hi @gaorany, thank you for your proposal. This grant has been approved! Can you provide an email address to confirm payment details?
> 
> Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

Hi @ErinOCon ， Glad to receive this news, our email address is :  gaoranycos@163.com

**Comment by gaorany** [comment]
Hi @ErinOCon . Thanks again for the support of Filecoin. In addition, I would like to ask when we complete this grant, can we continue to apply for an Open grant with this project? Of course  we will have a new roadmap when we complete this Next Step Microgrant . Looking forward to your payment details email !

**Comment by gaorany** [comment]
> Hi @ErinOCon . Thanks again for the support of Filecoin. In addition, I would like to ask when we complete this grant, can we continue to apply for an Open grant with this project? Of course we will have a new roadmap when we complete this Next Step Microgrant . Looking forward to your payment details email !

Hi @ErinOCon . Hope to hear from you！

**Comment by gaorany** [comment]
Hi @ErinOCon . Hope to hear from you!

**Comment by gaorany** [comment]
@ErinOCon any updates?

**Comment by gaorany** [comment]
@ErinOCon ，Hi!  I see a lot of applications have been answered, but I have no message...

**Comment by ErinOCon** [comment]
HI @gaorany, thank you for being in touch! Please let me know if you continue to experience trouble receiving our email. And yes, please feel welcome to submit a proposal for an open grant at the conclusion of this project. Happy building!

**Comment by ErinOCon** [comment]
Hi @gaorany, I have sent an email regarding the status of your payment. Please let me know of questions.
