### ISSUE TITLE
Next Step Microgrant: Nervos.Land

### ISSUE THREAD

**Issue by nervosland** [filecoin-project/devgrants#831]
### 1. What is your project? (max 100 words)

Nervos.Land is a web3 RTS game using NFT.storage technology. 

### 2. Project links
  
Link to Github repo:
https://github.com/nervosland/
Link to demo or website, if applicable:
https://nervos.land/
https://demo.nervos.land/

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

All NFTs game object's attributes, like characters, are stored on IPFS using NFT.storage.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Game development is a complex process, especially for web3. So, the grant will help to hire another talented Unity developer.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Of course, I think even earlier than 3 months.
  
### 6. Does your proposal comply with our Community Code of Conduct?

I think, yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

Web3 World Championship by Nervos Network - https://web3champs.devpost.com/project-gallery
Last is Blockjam2022 by Nervos Network - https://itch.io/jam/blockjam-2022
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Main developer (like CEO) Dmytro - https://github.com/x777, email: diyasrv@gmail.com, 
DevOps, community manager, and main partner - Illia, https://github.com/louraider,  email: Dubyshkin@gmail.com

* How did you learn about our microgrant program?
I got an email from protocol.ai team.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
Web3 World Championship - https://devpost.com/software/todo-name
Blockjam2022 - https://itch.io/jam/blockjam-2022/rate/1610809

**Comment by ErinOCon** [comment]
Hi @nervosland, thank you for your proposal! Can you confirm if this project is open source?

**Comment by nervosland** [comment]
> Hi @nervosland, thank you for your proposal! Can you confirm if this project is open source?

No, it's not open source project. Grants only for open source projects?

**Comment by ErinOCon** [comment]
Hi @nervosland, thank you for your reply. That's correct! Our microgrants program is intended to support open source work.

**Comment by ErinOCon** [comment]
Hi @nervosland, thank you again for your proposal. If your work is open source in the future, please feel welcome to reapply!
