### ISSUE TITLE
Next Step Microgrant: IPDrive

### ISSUE THREAD

**Issue by jpldcarvalho** [filecoin-project/devgrants#832]
### 1. What is your project? (max 100 words)

IPDrive is a file storage service for users to store and share files on the decentralized internet. This service comes as a replacement for centralized services such as Dropbox, Google Drive, and One Drive.

Currently, IPDrive is built on top of Web3.Storage, but we intend to change to directly interacting with the Filecoin network.

### 2. Project links
  
Link to Github repo: https://github.com/raquel22rf/ipdrive
Link to demo or website, if applicable: N/A

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Currently, we are using web3.storage in our project to pin all the files in IPFS. In the future, we intend to upload files to IPFS and deal with the pinning service directly on the Filecoin network.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

With this grant we intend to launch the project to the public. For that, we will handle the following issues:
* Private files encryption
* File sharing
* Dynamic pricing
  * Payment streaming (instead of fixed monthly fee)
  * Cost sharing for files that are pinned by multiple people
* User interactions with the web interface

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* https://ethglobal.com/showcase/ipdrive-thna0
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  * João Carvalho, me@jpldcarvalho.com, jpldcarvalho, Wizard Developer
  * Raquel Ferreira, rro.ferreira98@gmail.com, raquel22rf, Mermaid Developer
  * We are looking for front-end magicians, reach out! 
* How did you learn about our microgrant program? Received an email from Protocol Labs announcing it
* If your project was created as part of an event or hackathon:
  * What was the name of the event? ETHGlobal HackFS
  * Please link to your hackathon submission: https://ethglobal.com/showcase/ipdrive-thna0

**Comment by ErinOCon** [comment]
Hi @jpldcarvalho, thank you for your proposal. Can you confirm if this project is open source?

**Comment by jpldcarvalho** [comment]
Hello @ErinOCon. Yes, you can find the link for the GitHub In the "Project Links" section

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
