### ISSUE TITLE
Next Step Microgrant: Blockify

### ISSUE THREAD

**Issue by KowalewskiPawel** [filecoin-project/devgrants#833]
### 1. What is your project? (max 100 words)

Blockify is a decentralized Platform as a Service, for creating fully decentralized blogs. Everyone can be sure that the content won't be lost, even if the application ever goes down still the data will be persisted on the blockchain, Ceramic Protocol, and IPFS. Moreover, to help creators create a passive income from their posts, and incentivize users to use the platform, some actions require pay in Blockify Tokens that are of ERC-20 standard. However, to read the blogs, posts, and comments, there is no need to register, pay, or even have a crypto wallet.

### 2. Project links
  
Link to Github repo: https://github.com/KowalewskiPawel/Blockify
Link to demo or website, if applicable: https://blockify.netlify.app/

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

The smart contracts are built with Solidity and deployed to the Polygon Mumbai network, later on, The Graph is used to query the data from the blockchain. To store publications, Ceramic Protocol is used as it also provided a decentralized way to store data, plus there is no gas fee required, and it's also faster. Since the publications are stored on Ceramic Protocol which is Blockchain agnostic, in case of moving the platform to any other chain, the publications will be preserved.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

First of all, the plan is to implement the project as the official Blog for Web3 Devs Poland community - https://web3pl.eth.link/ to test it out in real scenarios. There will some improvements needed on the frontend part, as well as some security audits for the smart contracts. Moreover, we would like to get some help from the Ceramic Protocol team to check the Ceramic Protocol Implementation, to check how it will possibly scale. Once everything is set, the goal is to publish the app on the mainnet - Polygon and possibly mainnet of Ceramic protocol.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
https://ethglobal.com/showcase/blockify-u0ou2

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Pawel Kowalewski - [pawelkowalewsk@gmail.com](mailto:pawelkowalewsk@gmail.com) - https://github.com/KowalewskiPawel  - Founder and Developer
Krzysztof Kuczma - [kuczma.krzysiek@gmail.com](mailto:kuczma.krzysiek@gmail.com) - https://github.com/KrzysiekKuczma  - Developer

* How did you learn about our microgrant program? A: From the email notification.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) A: ETHGlobal HackFS22
  * Please link to your hackathon submission A: https://ethglobal.com/showcase/blockify-u0ou2

**Comment by ErinOCon** [comment]
Hi @KowalewskiPawel, thank you for your proposal. Can you confirm if this project is open source?

**Comment by KowalewskiPawel** [comment]
> Hi @KowalewskiPawel, thank you for your proposal. Can you confirm if this project is open source?

Hi @ErinOCon - sure, the repo is open and available to everyone also my smart contracts are marked as MIT. Should I change the type, or add a respective info in the package.json files?

**Comment by ErinOCon** [comment]
Hi @KowalewskiPawel, thank you for the update! Confirming the license in the comments of this proposal is sufficient. This grant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
