### ISSUE TITLE
Next Step Microgrant: Elpis

### ISSUE THREAD

**Issue by parshviSri** [filecoin-project/devgrants#834]
### 1. What is your project? (max 100 words)

This app allows users to share their ideas as a microblogging site but more in a decentralised way. It will be a micro blogging app where you can share your thoughts and get incentives monetary for using the app. You can create a community or a mini dao for your community.
Since it is a social media dapp it will require to store a large amount of data and we are storing data using ipfs as it is one the best decentralised storage option available.
We also provide a feature to convert your profile in a NFT using NFT.storage.

### 2. Project links
  
Link to Github repo: https://github.com/parshviSri/elpis-original
Link to demo or website, if applicable: https://elpis-original.vercel.app/

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  It is a social media dapp it will require to store a large amount of data and we are storing data using ipfs as it is one the best decentralised storage option available.
We also provide a feature to convert your profile in a NFT using NFT.storage.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Currently we are supporting only small text files and images but we want to move toward mediums like blog post and, audio, video and even live stream and to do all the enhancement we need  more resources like developers , better infrastructure  and for this we will require grant money.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes

  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Link- https://ethglobal.com/showcase/elpis-d24pn
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
    * Main Developer- Parshvi 
    * email- parshvisrivastav@gmail.com
    * Github account- https://github.com/parshviSri
    * Role- Full stack developer

* How did you learn about our microgrant program?
     Recieved a mail  from niki.gokani@protocol.ai about it.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  name of the event -ETHGlobal HackFS 2022 
  * Please link to your hackathon submission-https://ethglobal.com/showcase/elpis-d24pn

**Comment by ErinOCon** [comment]
Hi @parshviSri, thank you for your proposal! Can you confirm if this project is open source?

**Comment by parshviSri** [comment]
Yes the project is open source and can be accessible @ https://github.com/parshviSri/elpis-original for review

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
