### ISSUE TITLE
Next Step Microgrant: <Tipster>

### ISSUE THREAD

**Issue by kwakyebrilliant** [filecoin-project/devgrants#835]
### 1. What is your project? (max 100 words)
Tipster is a social rewarding platform that seeks to reward users for their posts by the way of tips in crypto. A user makes a post on the platform which is available to the community and anyone in the community can show impression to the post by giving crypto in the form of tips. The platform comes with search page where users can explore posts made by other users and can also make a search for a particular post. There is also a profile visit where a user can click on a particular identicon by a user to see other posts by that user. The platform also comes with my profile which shows all posts made by yourself should you find yourself on the platform. There is also a chatting side of the platform. The chat side allow all users to communicate together in a single group and this is to allow users on the platform socialize. The chats are available on the platform for a specified period. For testing purposes, use ropsten testnet.

### 2. Project links
  
[Link to public Github repo](https://github.com/mendsalbert/tipster_)
[Link to demo or website ](https://tipster-peach.vercel.app/)

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
All media on the platform are stored on the IPFS server.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We intend to take this project to the public domain to serve it's purpose in late December and as such we are working on an updated version of this project. We are adding more features to the platform to make it more user-friendly. This grant will help us host the project, have it on mainnet and undertake some marketing to reach a couple of target market and make use of it.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: https://chainlinkspring2022.devpost.com/submissions/searchpage=3&prize_filter%5Bprizes%5D%5B%5D=56140&utf8=%E2%9C%93
  
### Additional questions:
* Brilliant Kwakye, [kwakyebrilliant@gmail.comk](mailto:kwakyebrilliant@gmail.comk), I worked on the documentation, Backend and Frontend.
* Albert Mends, [mendsalbert@gmail.com](mailto:mendsalbert@gmail.com), mendsalbert , I contributed to the Backend and the frontend.
* Daniel Sarkodie, [dsarkodie500@gmail.com](mailto:dsarkodie500@gmail.com), AbrantepaSark , I worked on the UI/UX of Tipster.
* How did you learn about our microgrant program? Through mail from protocol labs.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? Chainlink 2022 Hackathon
  * Please link to your hackathon submission
https://chainlinkspring2022.devpost.com/submissions/search?utf8=%E2%9C%93

**Comment by ErinOCon** [comment]
Hi @kwakyebrilliant, thank you for your proposal! Can you confirm this project is open source?

**Comment by kwakyebrilliant** [comment]
Tipter is an open source project. As the goal of web3 to provide transparency we tend to open source it for the public to go through all the source code and file issues and suggestions.

**Comment by kwakyebrilliant** [comment]
Tipter is an open source project. As the goal of web3 to provide
transparency we tend to open source it for the public to go through all the
source code and file issues and suggestions.

**Comment by kwakyebrilliant** [comment]
Yes it is open source

**Comment by kwakyebrilliant** [comment]
> Hi @kwakyebrilliant, thank you for your proposal! Can you confirm this project is open source?

Hi there, is there any updates on this case?

**Comment by kwakyebrilliant** [comment]
> Hi @kwakyebrilliant, thank you for your proposal! Can you confirm this project is open source?

Hi @ErinOCon, is there any updates on this case?

**Comment by mendsalbert** [comment]
Please consider this project for the grant request

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @kwakyebrilliant, once the three month period for this project is complete, please submit the final grant report [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
