### ISSUE TITLE
Next Step Microgrant: Tind3r

### ISSUE THREAD

**Issue by jeff0723** [filecoin-project/devgrants#836]
### 1. What is your project? (max 100 words)
A decentralized social app built on IPFS & Web3.storage & XMTP for web3 people to make friends.

### 2. Project links
  
Link to Github repo: https://github.com/jeff0723/Tind3r
Link to demo or website, if applicable: https://ethglobal.com/showcase/tind3r-i7rtt

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
We use IPFS to store all the media files on our platform.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. Develop a mobile version
2. Develop a more advanced recommendation system

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
Hackfs 2022: https://ethglobal.com/showcase/tind3r-i7rtt
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project: 
1. Jeffrey, jeffreylin0723@gmail, @jeff0723, PM & Full-stack Engineer
2. Justa, justaliang@protonmail.com, @JustaLiang, Backend & Smart contract Engineer
4. Greg, gregshen0925@gmail.com, @gregshen0925, Q&A Engineer
* How did you learn about our microgrant program? Email.
* If your project was created as part of an event or hackathon:
  * What was the name of the event?  ETHGlobal HackFS(e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission : https://ethglobal.com/showcase/tind3r-i7rtt

**Comment by ErinOCon** [comment]
HI @jeff0723, thank you for your proposal! Can you confirm if this project is open source? Also, can you provide more details on the steps you will take over the next three months to develop a mobile version and more advanced recommendation system?

**Comment by jeff0723** [comment]
Yes, this project is open source. 
As for the next step of development, we are going to use react native to build our mobile version. 
Due to the issue of connecting wallet, we will first build our in-app wallet to send every transaction.
Then, we will also talk to XMTP to see if their mobile SDK is ready. For the file storing part, we will still store 
on ipfs but not ceramic and maintain a user metadata DB to store their CID. And for the recommendation system, 
we will collect users' on-chain data and build a machine learning model to recommend user things (like match, follower) based on their on-chain activity.

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by jeff0723** [comment]
Hello, just to confirm, when will we receive the email?

**Comment by ErinOCon** [comment]
Hi @jeff0723, thanks for checking in! We sent this email on the day of approval last week. I have just sent a new follow up email. Can you confirm receipt?

**Comment by jeff0723** [comment]
Which email address did you send the email to? I haven't received any email about the payment or the follow-up email.

**Comment by ErinOCon** [comment]
Hi @jeff0723, closing the loop on this thread to confirm the email with payment details was received by your team. Happy building!
