### ISSUE TITLE
Next Step Microgrant: <PinTogether>

### ISSUE THREAD

**Issue by xtop-protocol** [filecoin-project/devgrants#837]
### 1. What is your project? (max 100 words)

PinTogether's design revolves around "memory". It’s built with IPFS and used NFT.storage technology. PinTogether uses NFTs as a carrier of memories, retained in a virtual world independent of the real world. This type of NFTS is different from the NFTS of digital collections, we will refer to the form of memory to design NFT, such as NFT life cycle including lighting up and fading out, and the group ownership framework of like DAO.
PinTogether won the third prize and the most innovative prize in Filecoin China Hackathon:
https://twitter.com/Filecoin/status/1554491609668100098?s=20&t=ZKMC3rK_llS05ZTdWecmuw

### 2. Project links

Link to Github repo: https://github.com/defiking0108/Hacthon_pinTogether
Link to demo or website, if applicable: 
https://drive.google.com/file/d/1QC5EZG0jpvkLCNYjm2HzJRXmh2vvuHzU/view?usp=sharing

  

### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

When a user creates an auxiliary information file such as NFT geographic location, the system will store it on IPFS and Filecoin through NFT.Storage. 
When the user checks in and browses, the system will obtain the corresponding NFT and geographic location and other auxiliary information through NFT.Storage. 

  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1.Design NFT life cycle interface and launch it as smart contract. 
2.Add token system and integrate it into the NFT's mint, transfer and dim process(also in smart contract format). 
3.Improve UI/UX design in the APP.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, I agree. 
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes, it does. 

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

PinTogether won the third prize and the most innovative prize in Filecoin China Hackathon:
https://twitter.com/Filecoin/status/1554491609668100098?s=20&t=ZKMC3rK_llS05ZTdWecmuw

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Harry, machengxue707@gmail.com, woshidama323, developer
Start, 4544242@qq.com, defiking0108, developer
Stella [xinxin.zhang.fs@gmail.com,](mailto:xinxin.zhang.fs@gmail.com,) product manager

* How did you learn about our microgrant program?
From Isabella, Filecoin/IPFS Asia marketing lead. When we won the prize and then got this information. 

* If your project was created as part of an event or hackathon:
Yes, it was. PinTogether was developed dedicate to the Filecoin Hackathon. 

  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
Coding with Filecoin
https://hackathon.city/

  * Please link to your hackathon submission
We’ve submitted project via https://jinshuju.net/f/BLWMCr. 
Info was collected by IPFS Asia team.

**Comment by ErinOCon** [comment]
HI @xtop-protocol, can you confirm if this project is open source?

**Comment by xtop-protocol** [comment]
> HI @xtop-protocol, can you confirm if this project is open source?

Yes, it was. Here is the link: https://github.com/defiking0108/Hacthon_pinTogether
Let me know if you need further information.

**Comment by xtop-protocol** [comment]
> HI @xtop-protocol, can you confirm if this project is open source?

Hi there, is there any updates on this case?

**Comment by ErinOCon** [comment]
Thanks, @xtop-protocol! Will funds received from this microgrant program be used to support open source work?

**Comment by xtop-protocol** [comment]
> Thanks, @xtop-protocol! Will funds received from this microgrant program be used to support open source work? That is to say, the project is also currently open source, correct?

Thanks for the reply. 
Yes, definitely. We will work on this project and the process can be open source.

**Comment by xtop-protocol** [comment]
> Thanks, @xtop-protocol! Will funds received from this microgrant program be used to support open source work? That is to say, the project is also currently open source, correct?

Hi, any update on this case? Thanks

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by xtop-protocol** [comment]
Thank you! Looking forward to your email.

**Comment by xtop-protocol** [comment]
> This microgrant has been approved! We will send an email to confirm payment details.
> 
> Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

Hi there, unfortunately we did not receive any email about payment details. Could you have a check with that. BTW, we've submitted the new version via your link in the email. Looking forward to your feedback. Thanks.
