### ISSUE TITLE
AiInsure – NextGen Insurance Powered by AI and Filecoin

### ISSUE THREAD

**Issue by aiinsure** [filecoin-project/devgrants#838]
# Open Grant Proposal: `AiInsure – NextGen Insurance Powered by AI and Filecoin`

**Name of Project: 
AiInsure

**Proposal Category:** 
`app-dev`

**Proposer:** `Jeffery Peng`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licences?:**
`Yes`

# Project Description
## The Problem
Insurance fraud costs U.S. consumers at least $80 billion every year, according to The Coalition Against Insurance Fraud (CAIF). The number is even more staggering worldwide. The problem facing most insurance providers today, is that there is no reliable, fast and cost-effective way to validate the claim history information disclosed(or not disclosed) by the customers.
For insurance customers, the lack of fully accessible, transparent and trustworthy insurance claim history profile often means that customers are paying unnecessarily higher premium as the insurance providers are mitigating the risk of non-disclosure by increasing premium for their products.

## The Project
AiInsure is an FinTech solution leveraging blockchain and decentralised Filecoin/IPFS technologies that provides a historical record of insurance claims related information on individuals and companies.

AiInsure believes that with the creation of such secure, immutable and trustworthy historical record on the blockchain and storing on Filecoin/IPFS would be hugely beneficial in countering insurance frauds which amounts to billions of dollars each year.  

The technology advantage of Filecoin’s fully decentralised storage allow us to store and share the historical claim records cost effectively, transact efficiently and at the same time, offering highest level of security to our application. 

Under AiInsure, individuals and companies own their insurance claims histories such that they can choose whether or not to allow a third party to access it. If they approve such access request, this information can be used by insurance providers and their third-party agents to assist them in the validation of information provided to them during the course of an insurance policy – from quotation, risk assessment, policy in effect, and claims.

AiInsure is available via a website portal, as well as web services APIs. Website portal is freely available for insurance customers to register and login, upload their claim histories and identity related information. Web services API is available for integration with insurance providers for validating customers claim histories.

## Value
AiInsure believes that our project can reduce the amount of insurance fraud which is estimated at more than $100 billions a year worldwide.

1. AiInsure allows historical insurance records to be stored on Filecoin network & IPFS with the help of FilSwan platform which hides the complexity of Filecoin/IPFS for end users.

2. Each stored insurance claim and associated documents stored is an immutable record, the CID of the record and related metadata will then be minted as an NFT token on the blockchain as a prove of ownership and smart contract operations such as auto claim, etc.

3. AiInsure uses AI algorithms and smart contracts containing business logic to generate risk score of the consumer based on the information in the profile. Risk score will be used by partner insurance providers to price the insurance policies for individual consumers.

# Incentive For Both Insurance Providers And Consumers
AiInsure is building an insurance claim history profile against an individual / legal entity that is verified and signed by leveraging blockchain and Filecoin technology to ensure the trustworthiness of the data, which can be widely used by insurance providers to correctly assess the risk levels and price the products appropriately.

It can also be used by customers buying new insurance products or switching insurance providers such that their claim history is accessible to the insurance providers to facilitate transaction and obtain the best possible premium for the chosen insurance products.

# The risks if we don't get it right:
-	Insurance industry continues to suffer from huge financial loss because of insurance frauds 
-	Insurance consumers continue paying higher premiums 

# Risks likely to make project execution difficult:
-	Building the correct AI logic to assess the risk profiles based on the information stored on Filecoin storage.
-	Integration of the Filecoin and blockchain smart contract component to provide users with seamless experiences.

# Detail technical description

Step 1:
Consumers connect to our web portal via secure HTTP either using mobile device or desktop PC. Consumers can then search insurance policies provided by partner insurance companies on our web portal.

Step 2:
Consumer selects the insurance policy they want to buy; Before being redirected to the partner insurance providers’ web site to complete purchase, they will be prompted to log in to their account (or create a new account) on our app and uploads required documents such as:
•	past claim history
•	address proof
•	age proof
•	passport size photos
•	identity documents
•	income proof

These documents are stored in the distributed storage, Filecoin.

Step 3:
Consumer provided information is verified against data from partner insurance companies.

Step 4: 
Verified results together with the hash address of the related documents are signed (with AlgoSigner) and stored in the blockchain to form the claim history profile of the consumer.

Step 5:
AiInsure uses smart contracts containing business logic to generate risk score of the consumer based on the information in the profile. Risk score will be used by partner insurance provider to price the insurance policies for individual consumers.

Step 6:
Insurance companies can request consumer risk score and claim history via API (built using Google Apigee) when assessing risk level of individual consumer.

Step 7:
If the request is approved by the consumer, smart contract (written in python using the PyTeal package) will fetch the specific claim history profile from the blockchain and provide to the insurance company.

# Risk Score and how it works
The risk score generated by smart contracts can help insurance providers validate users in real time. A user’s risk score can be improved by:
•	Uploading required documentation
•	Provide required information such as claim history
•	Information matches with data from the insurance providers
•	Allowing insurance providers to access claim history stored in the block chain

Users with higher score will enjoy lower insurance premium from partner insurance providers.

## Deliverables
We will deliver a web app integrated with Filecoin and blockchain to allow users to:
- Login
- Upload insurance related documents to the Filecoin/IPFS network
- Manage their claim history, etc

## Development Roadmap

Architecture Diagram
![AiInsure_Filecoin](https://user-images.githubusercontent.com/96064365/183853024-6813a8a8-edd8-4586-8a0e-2f8d7562ecd7.png)

# Milestone 1 - Infrastructure (Ethereum Backend): Set up backend infrastructure.
-	Create dev account, perform node testing on TestNet.
-	Design and complete AWS web server & application server hosting infrastructure setup. A web hosting solution is required for our web app which then will be fully integrated with the blockchain and FileCoin platform.
-	The web server infrastructure will be hosting our web application
-	The application server infrastructure will be hosting smart contract and storage operation applications.
-	Set up the front-end web portal home page and user interface.
-	duration: 1 month

# Milestone 2 - FILECOIN STORAGE INTEGRATION, SMART CONTRACTS LOGICS FOR MINTING NFTS:
-	Complete Filecoin/IPFS system set up to host uploaded documents. A decentralised storage system is required to store images and large sized documents, however the CID address of the file upload transaction will be stored on chain.
-	Design and develop the smart contract logics for minting NFTs based on the uploaded digital contents.
-	duration: 1.5 month

# Milestone 3 – Complete Frontend, Risk score:
-	Complete web portal user interface development.
-	The frontend user interface will support: user registration, ID document upload.
-	Complete user creation integration with blockchain platform so each app new user will create a user account on blockchain for future transaction use cases.
-	Integrate with stored contents from Filecoin/IPFS to complete risk score logic and implementation for each user. 
-	duration: 1.5 month

## Future Roadmap
- Migrate the smart contracts to Filecoin virtual machine (FVM) when ready
- Ultilise Filecoin token for transactions and payment for insurance claims, etc

## Total Budget Requested
USD$90,000 equivalent
| Budget (USD$)               | Milestone 1 | Milestone 2 | Milestone 3 |
|-----------------------------|-------------|-------------|-------------|
| Developer Frontend          | 15000       | 15000       | 15000       |
| Developer Backend           | 15000       | 15000       | 15000       |
| Infrastructure Subscription | 1000        | 1000        | 1000        |
| Total                       |             |             | 93000       |

## Maintenance and Upgrade Plans
A dedicated Ops team will be running the platform daily. The platform will be running 24/7.
Major software upgrade is planned every 6 months.

# Team

## Team Members
Jeffery Peng
Fred Zhang

## Team Member LinkedIn Profiles
https://www.linkedin.com/in/jeffery-peng-910bb8240/
https://www.linkedin.com/in/fred-zhang-aa69971/

## Team Website
www.ai-insure.com.au

## Relevant Experience
Jeffery Peng
Jeffery is an experienced leader who is passionate about tech-innovation and transfer into commercial environment.
He has both bachelor degree and master degree in IT computer science and has proven working experience in reputable technology companies since graduation such as Huawei, Oracle etc.
He started his blockchain developer journey back in 2017 by working on some small dApps on Ethereum network and have extensive amount of development experience in multiple projects built on famous public chain network.
Jeffery’s vision is to commercialise projects that decentralised technology can bring to our Web3 generation.

Fred Zhang
Fred has more than 25 years of experience in software development and data engineering space.
He has worked in various companies with insurance data background that he understands the pain points and solution gaps in the industry.
His hobby is in technology space and he builds applications during his leisure time as part of self-development and personal fulfilment.
He is passionate about leveraging Web3 technology to provide a secure, immutable and decentralised experience to build personal insurance risk profile.

## Team code repositories
https://github.com/aiinsure/aiinsure4.git

# Additional Information
N/A

**Comment by realChainLife** [comment]
Hi @aiinsure thanks for the proposal. We're still evaluating this proposal and had several open questions, will appreciate your take on these: 

- How will the smart contract functions standardize across different needs of multiple insurance companies
- What user research was conducted to determine proposed solution will address user pain points
- Website indicates filecoin / ipfs integration was completed 10 July 2022, can we get relevant links to the work completed so far? Will help understand how it builds on the proposed scope of work

**Comment by aiinsure** [comment]
Hi @realChainLife Thanks for taking your time assessing the proposal, please find our answers below:

- How will the smart contract functions standardize across different needs of multiple insurance companies
According to the E2E solution, data consumers (insurance companies) retrieve data from our customised API. API provides data by retrieving from both on-chain (via smart contracts) references (IPFS CID) from blockchain, and off-chain data from Filecoin storage. Data model is designed to fit for common insurance claim data structure.

- What user research was conducted to determine proposed solution will address user pain points
One of our co-founders worked in insurance industry(including big insurance companies such as IAG and Allianz) for many years and has extensive experiences and knowledge in industry wide pain points. There are limitations in our solution however, this would be the initiate step we are making to solve these pain points.

- Website indicates filecoin / ipfs integration was completed 10 July 2022, can we get relevant links to the work completed so far? Will help understand how it builds on the proposed scope of work
Website indicates filecoin / ipfs integration design was completed 10 July 2022, not implementation.

Hope this above has clarified your query, feel free to reach out to us, thanks.

**Comment by ErinOCon** [comment]
HI @aiinsure, thank you for your time with this additional information! We would be interested in considering a grant that focused on one or two of the functions listed in Step 2 of your technical description. Would you have an interest in reworking your proposal for this purpose? In this rework, we would like to learn more about the user traction for this project. How has your project grown over the last year from a user perspective? Do you have data that supports future onboarding potential?

**Comment by aiinsure** [comment]
@ErinOCon  Hi Team, we are happy with reduced scope of just completing below 2 milestones:

Milestone 1 - Infrastructure (Algorand Backend): Set up Algorand backend infrastructure.
Create dev account, perform node testing on TestNet to enable Algorand dev account for AiInsure.
Set up indexer & Postgre SQL database to prepare for outbound data retrieval.:
Design and complete AWS web server & application server hosting infrastructure setup. A web hosting solution is required for our web app which then will be fully integrated with the blockchain and FileCoin platform.
The web server infrastructure will be hosting our web application
The application server infrastructure will be hosting smart contract and storage operation applications.
Set up the front-end web portal home page and user interface.
duration: 1 month
Milestone 2 - FILECOIN STORAGE INTEGRATION, SMART CONTRACTS LOGICS FOR MINTING NFTS:
Complete Filecoin/IPFS system set up to host uploaded documents. A decentralised storage system is required to store images and large sized documents, however the CID address of the file upload transaction will be stored on the Algorand blockchain
Design and develop the smart contract logics for minting NFTs based on the uploaded digital contents.
Documents in scope for storage solution
• address proof
• identity documents
duration: 1.5 month

User Traction:
We are in discussion with white labelled insurance underwriter to resell their products on our website once our site launces, the past insurance claim history upload will be based on user's discretion if they would like to show their low risk score to achieve a high discount rate. We have not launched into market yet over the last year however we have kicked off API development on suppling data to insurance companies / underwriters should they want to sell their products on our site.
We anticipate high user traction rate due to the fact we are the reseller of the products so customer is still buying into a products with familiar branding they know of, but by providing their first party claim history data they will be able to enjoy a personal discount.
Benefits to us is we can store collected claim history data to provide a holistic view to insurance company and sell these risk score data.

**Comment by mishmosh** [comment]
> Website indicates filecoin / ipfs integration design was completed 10 July 2022, not implementation.

Can you describe the design of your Filecoin/IPFS integration? If you haven't encountered it already, we recommend using a storage helper such as web3.storage or Estuary.tech (both of these bundle IPFS & Filecoin storage into a single API call).

**Comment by ErinOCon** [comment]
Hi @aiinsure, thank you for the milestone breakdown! We would like to proceed with a $50k grant for this project. Would you be interested in revising the breakdown to align with this budget? Please reach out with any questions!

**Comment by aiinsure** [comment]
> > Website indicates filecoin / ipfs integration design was completed 10 July 2022, not implementation.
> 
> Can you describe the design of your Filecoin/IPFS integration? If you haven't encountered it already, we recommend using a storage helper such as web3.storage or Estuary.tech (both of these bundle IPFS & Filecoin storage into a single API call).

We were considering using direct IPFS integration. The HTTP Client Library with a self hosted IPFS. But will look into storage helpers to see which one is the best suite for the application. Because we would like to have a tighter integration with filecoin, this time. Implementing hosted  Estuary node seems like a good option, even though it means more complicated build.

**Comment by aiinsure** [comment]
> Hi @aiinsure, thank you for the milestone breakdown! We would like to proceed with a $50k grant for this project. Would you be interested in revising the breakdown to align with this budget? Please reach out with any questions!

Hi Team, please find the revised scope for USD$50k grant:

Milestone 1 - Infrastructure (Ethereum Backend): Set up backend infrastructure.
Create dev account, perform node testing on TestNet.
Set up indexer & Postgre SQL database to prepare for outbound data retrieval.:
Design and complete AWS web server & application server hosting infrastructure setup. A web hosting solution is required for our web app which then will be fully integrated with the blockchain and FileCoin platform.
The web server infrastructure will be hosting our web application
The application server infrastructure will be hosting smart contract and storage operation applications.
Set up the front-end web portal home page and user interface.
duration: 1 month
Milestone 2 - FILECOIN STORAGE INTEGRATION, SMART CONTRACTS LOGICS FOR MINTING NFTS:
Complete Filecoin/IPFS system set up to host uploaded documents. A decentralised storage system is required to store images and large sized documents, however the CID address of the file upload transaction will be stored on the blockchain
Design and develop the smart contract logics for minting NFTs based on the uploaded digital contents.
Documents in scope for storage solution
• address proof
• identity documents
duration: 1.5 month

Total Budget Requested
USD$70,000 equivalent

**Comment by aiinsure** [comment]
> Hi @aiinsure, thank you for the provided updates! Can you confirm the best email address to send the grant agreement to?

Thanks team aiinsurecom@gmail.com please, looking forward to the emails.

**Comment by ErinOCon** [comment]
This item has been closed as it is now considered a completed project. Please feel welcome to contact our team with updates at grants@fil.org.
