### ISSUE TITLE
Next Step Microgrant: Team Greener

### ISSUE THREAD

**Issue by Nwakakukaks** [filecoin-project/devgrants#840]
### 1. What is your project? (max 100 words)
Greener is a Dapp for raising funds for environmental causes such as climate/ozone support, plant a tree causes, natural emergencies like flood, fire outbreaks, earthquake, community projects etc. whats possible on Greener
1. Loans
2. One-time fundraiser: where the organizer describes the goal of the fundraiser and
optional the goal amount (in USD) and end date. Donors may choose to fund a one-time fundraiser as long
as it's in open status and they have funds in their wallet.
3. Recurring fundraiser: where donors may pledge to donate a set amount at a given interval.

### 2. Project links
  
Link to Github repo: https://github.com/nwakakukaks/greener
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  web3storage powered by filecoin/IPFS is used to store fundraiser descriptions and images in a decentralized manner without the cost of on-chain storage.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Next step would be getting Greener production ready in the shortest possible time, this grant would be used to ensure that and also to get more hands on the project.
Below are some improvements i consider making!!
 BrightID "proof of humanity" integration to minimize potential for fraud and highlight fundraisers run by real people in need.
 NFT reward pool - donated NFTs distributed randomly in raffles among highest ranking donors. The more you donate to verified fundraisers - the higher chance of winning!
Auto-donations - if you don't want to browse all open fundraisers, you can set how much you want to donate from your wallet and an algorithm will auto-donate based on donations of other (reputable) users of the system.
Accept donations in multiple different coins / tokens - use Chainlink price feeds to recalculate value.
UI/UX improvements ( I plan on involving a more professional hand as am not that great in UI/UX ).

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes, it does

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://gitcoin.co/issue/29009/nwakakukaks

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Nwakaku Winner
Email: winnernwakaku123@gmail.com
Github: github.com/nwakakukaks
Role: sole developer

* How did you learn about our microgrant program?
I was emailed from protocol labs informing me about their willingness to support my next step through microgrants.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)

Sustainable Blockchain Summit

  * Please link to your hackathon submission
https://gitcoin.co/issue/29009/nwakakukaks

**Comment by ErinOCon** [comment]
HI @Nwakakukaks, thank you for proposal! Can you confirm if this project is open source?

**Comment by Nwakakukaks** [comment]
Yes , it is open source

**Comment by Nwakakukaks** [comment]
We Haven’t heard from you again @ErinOCon

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by Nwakakukaks** [comment]
Awesome, thank you @ErinOCon
