### ISSUE TITLE
Next Step Microgrant: 3TIX

### ISSUE THREAD

**Issue by ChmilevFA** [filecoin-project/devgrants#841]
### 1. What is your project? (max 100 words)
3TIX platform helps events organizers to create and sell event tickets in form of NFT.
Created NFTs are also compatible with ERC2981 format, so creators of the event can receive royalties from secondary sales of tickets, which is one of the biggest problems in web2 for the ticketing industry.

### 2. Project links
  
Link to Github repo: https://github.com/3TIX
Hackathon showcase: https://ethglobal.com/showcase/3tix-r2ivv
Application website: https://3tix.github.io/event-management/
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
* All the data for the events are stored on IPFS via nft.storage
* We are utilizing The Graph protocol to index on-chain and IPFS event data
* We are experimenting with deployment of our DApp frontend to IPFS and eventually going to keep it that way
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
* Better management of already created event (update, delete, hide), hope to properly make it with IPFS related integration mainly
* Improve NFTs display on external marketplaces (like OpenSea)
* Make a mobile app for both event organizers and regular users (ideally)
* Fix issues with POAP integration
* Grow community
* Deploy to mainnet

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
https://ethglobal.com/showcase/3tix-r2ivv
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project:
  * Fedor, chmilev.fedor@gmail.com, https://github.com/ChmilevFA, Blockchain/Backend Engineer
  * Ulad, uladzislau.radkevich@gmail.com, https://github.com/vlad324, Blockchain/Backend Engineer
  * Michael, mikhail.stetc@gmail.com, https://github.com/decimal-corn, Frontend Engineer
  * Chris, chris@chrishayward.net, -, Designer
  * Wilhelm, wilhelm.zha@gmail.com, -, Product
* How did you learn about our microgrant program?
  * Email from you
* If your project was created as part of an event or hackathon:
  * HackFS2022
* Please link to your hackathon submission: https://ethglobal.com/showcase/3tix-r2ivv

**Comment by ErinOCon** [comment]
Hi @ChmilevFA, thank you for the proposal. Can you confirm if this project is open source?

**Comment by ChmilevFA** [comment]
hello @ErinOCon 
Yes, project is open source and new features/changes (which are under development) will be also published to the same repository

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
