### ISSUE TITLE
Next Step Microgrant: Mothora

### ISSUE THREAD

**Issue by 0xTimepunk** [filecoin-project/devgrants#842]
### 1. What is your project? (max 100 words)

Mothora is a web3 game of persistent large-scale incentivised 3-way Faction (iFvFvF) battles in Unreal Engine 5. It is set in a dystopian sci-fi future, in the aftermath of civilisational decay, where three factions struggle for survival.
As part of Chainlink Spring Hackathon 2022, we built a game demo that includes obtaining NFTs as rewards using Chainlink VRF and the staking of these NFTs to earn in-game rewards. Their metadata could be stored using a service such as NFT.storage and displayed directly within Unreal Engine 5.

### 2. Project links
  
Link to Github repo: https://github.com/Mothora/mothora-chainlinkspring
Link to demo or website, if applicable: 

1. Demo video: [https://www.youtube.com/watch?v=SDYk5hoVxzE](https://www.youtube.com/watch?v=SDYk5hoVxzE&t=1s) 
2. Website: [https://mothora.xyz](https://mothora.xyz)
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

The goal of Mothora is to be a game that gives back to players in a sustainable way. To achieve this mission decentralized storage of in-game assets is of great importance. All of Mothora’s items will be NFTs that can either be crafted or purchased in the in-game marketplace. Our goals with these technologies are:
- To ensure that these NFTs’ metadata is hosted in a storage system that uses IPFS under the hood
- To use an Unreal Engine 5 plugin/system that sources this metadata and supports displaying it in the game in relevant ways

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

With this grant we have some support to make the game’s visual assets more decentralized right from the outset. This means not having to rely so much on centralized servers to host the digital 3D assets of the game but rather IPFS/Filecoin related technologies that can support make the game more decentralized for everyone. To achieve our goals of implementing this we are planning, in the next three months, to:

1. Continue working on our internal demo leading to an MVP of a game. This implies a set of tasks such as:

- Continued work on the production of 3D Assets
- Landscape creation
- Smart Contract re-modelling to a MVP version

2. Integration of a reliable NFT storage system to properly showcase the NFTs within the game:

- Wire the NFT smart contracts to the storage system
- Integration of the storage system in the Unreal Engine 5 MVP environment

We intend to follow these two tracks of work in order. Likely at some point some parallel work can be started with the regard to the integration of the NFT storage system.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Link: https://devpost.com/software/mothora 

Yes, we submitted to the Chainlink Spring Hackathon 2022 to the following tracks:
- Filecoin - Bonus Gaming, Metaverse, Daos & NFTs (Oh My!) - $7,500 | The Game uses filecoin is used for NFT storage and IPFS used for NFT interactions.
- Filecoin - Runners up - $12,500 | The Game uses filecoin is used for NFT storage and IPFS used for NFT interactions.

We were just contacted by Niki Gokani regarding the fact that one of the hackathon judges really liked what we have built and Filecoin wanted to keep supporting us.

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

Mothora’s team consists of 5 members. We are not listing our email addresses due to privacy reasons. Feel free to reach out in private about these.

- João Martins - CEO at Mothora. Github: https://github.com/0xtimepunk 
- Jared Childers - Unreal Engine Game Developer and 3D Asset Modeler at Mothora. Github: https://github.com/JaredChilders 
- Luis Castillo -  Lead Web3 Front-End Engineer at Mothora. Github: https://github.com/castilloluis
- Mariana Rodrigues - Lead Community Manager and Content Writer at Mothora
- Pedro Merino - 3D Asset Modeler and Material Painter at Mothora.

We learned about the microgrant program after Niki Gokani contacted us. Our project was created as part of Chainlink Spring Hackathon 2022, whose submission link is https://devpost.com/software/mothora

**Comment by ErinOCon** [comment]
Hi @0xTimepunk, thank you for your proposal! Can you confirm if this project is open source?

**Comment by 0xTimepunk** [comment]
Hi @ErinOCon !

Only the smart contract code and associated NFT storage code on IPFS will be open sourced. Unreal Engine game source code will not be open sourced for the time being.

**Comment by ErinOCon** [comment]
Thanks, @0xTimepunk! Can you confirm that funds received from this microgrant would only be applied to open source work?

**Comment by 0xTimepunk** [comment]
Yes, we intend to use the funds from the micro grant only to support the aforementioned activities that deal with open source work.

**Comment by ErinOCon** [comment]
Thanks, @0xTimepunk! Can you make your github repo and demo video public?

**Comment by 0xTimepunk** [comment]
Hey @ErinOCon 

Apologies for the late answer! Mothora got an updated version of the contracts and video demo at two new links, hence why the above two got private. This is the result of our most recent work for Polygon Buildit Hackathon 2022:

- https://github.com/Mothora/mothora-polygon-buildit2022
- https://www.youtube.com/watch?v=3ymm2Jr1z6Q&t=1s

Let me know if you have further questions and requirements.

Thanks

**Comment by ErinOCon** [comment]
Hi @0xTimepunk, thank you for your patience with our review. This grant has been approved! Do you have a preferred email address for confirming payment information?

**Comment by jenks-guo-filecoin** [comment]
Congrats Team. :-)

**Comment by 0xTimepunk** [comment]
Super! 

Thanks a lot @ErinOCon and @jenks-guo-filecoin !

You can email at timepunk@mothora.xyz

I just got two questions, how are the payment terms and could the 3 month period start at a predefined date? (Such as 1st of November?)

**Comment by ErinOCon** [comment]
Hi @0xTimepunk! I have sent an email with details regarding the payment. If you have questions regarding these details, please reply with our grants team cc'd. 

Yes, please feel welcome to kick off the project at the beginning of the month. Please note that your final grant report is due within three months of your kick off date and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @0xTimepunk, confirming on this thread that the final report date for this project will be March 31, 2023.
