### ISSUE TITLE
Next Step Microgrant: HERE API IPFS Integration

### ISSUE THREAD

**Issue by dylan8** [filecoin-project/devgrants#843]
### 1. What is your project? (max 100 words)
I was tired of taking routes to work that would have me stuck in traffic the whole time. I wanted to create a script that could track what roads had the most incidents on them. The script retrieves the most recent traffic data for my city utilising the HERE traffic API. The api doesn't store historical data so I used CORTX and IPFS to store it. I then receive updates every morning by using the gmail api to send alerts about my route to work. I foresee someone like the local government using this data to better plan road maintenance etc.

### 2. Project links
https://github.com/Seagate/cortx/tree/main/doc/integrations/here_cortx_traffic_data 
Link to Github repo: https://github.com/dylan8/here_traffic_ipfs/
Link to demo or website, if applicable:

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
The HERE Traffic API doesn't store historical data so I use IPFS to store it which I can use to document past traffic incidents. 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
I plan to integrate more cities and API fields into the project to develop richer information about incidents around the various cities.
I plan to add a display map for a given city with the incidents in that city displayed on it. Post analysis on routes that may have more incidents than others and how it disrupts traffic flow.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?
I do agree to share grant reports upon request, including a final grant report at the end of the three-month period.
  
### 6. Does your proposal comply with our Community Code of Conduct?
It does comply. 

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
N/A
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Dylan Kearns, kearns.dylan@gmail.com, dylan8, developer
* How did you learn about our microgrant program?
I was reached out to by a member of Filecoin & IPFS
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  CORTX & Filecoin Integration Challenge 2022
  * Please link to your hackathon submission
  https://devpost.com/software/here-api-with-cortx-and-ipfs-integration

**Comment by ErinOCon** [comment]
HI @dylan8, thank you for your proposal! Can you confirm this project is open source?

**Comment by dylan8** [comment]
Hi @ErinOCon the project is open source yes.

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
