### ISSUE TITLE
Next Step Microgrant: <Trust Finance>

### ISSUE THREAD

**Issue by quadriproduct** [filecoin-project/devgrants#844]
### 1. What is your project? (max 100 words)

Trust Finance is a building a public good Defi tool that aims to onboard the next billion users into crypto by providing simple and real-time payroll payments, benefits, and accounting for DAOs/businesses to compensate, ensure improved operations, and attract top talents.
Trust Finance application seamlessly integrates with storage features such as ipfs, web3.storage that enable crypto businesses, DAO, and NFT projects to save time and cost and reduce complexity in managing talents and operations on Polygon. We are reducing the frictions that businesses encounter when making payroll payments to freelancers and DAO contributors. Additionally, it is time-consuming for businesses to keep track of transactions and ensure proper accounting and compliance.

### 2. Project links
  
Link to Github repo: https://github.com/quadriproduct/trust_app

Link to demo or website, if applicable: 
Website: https://www.trustfin.xyz/
Demo: https://showcase.ethglobal.com/hackmoney2022/trust-finance-vqk0h

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
 IPFS and web3.storage are used for decentralized storage of data such as user account information, transaction data, and historic data for generating reports within the Trust Finance app. 

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

This grant will enable us to scale our products to millions of users in different geographies such as Africa, Latin America, and Southeast Asia. Our goal is to empower businesses and personal users who want to adopt crypto as a way to compensate and invest respectively. The grant will be used to support additional product development, product design, and marketing so that we can launch a beta app by the beginning of September. 
The feature release schedule are;
1. Launch Business (Make a payment and add employees) (Business accounts) by Aug 19th, this will be deployed on Polygon and IPFS is used for storage
2. Launch transacting tracking and dashboard - August 19th
3. Launch Invoicing; including milestone based invoicing for personal users and business - August 26th
4. Launch marketing campaign on Twitter, Discord, and partnership with Chainlink and Unlock protocol - August 31st 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?

  
Yes, we will share the final grant report at the end of the three-month period.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes, our proposal complies with the community code of conduct

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
We have competed in two major ETH global hackathons and have won top prizes. We have also been accepted into Superfluid reactor and Chainlink Startup program.
https://twitter.com/Superfluid_HQ/status/1529574452224303111?t=KP1RHigtDHeSNgoY_T_krg&s=08

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Quadri Oguntade is a graduate of MIT Sloan MBA and MPA Harvard Kennedy School. Worked previously as a technical product manager at Amazon. Strong experience building web 3 companies.
Email: adetolaq@gmail.com
Github account: quadriproduct, qaoguntade
Linkedin: https://www.linkedin.com/in/quadrioguntade/

Member 2 - 
Name: Shuyue (Celia) Li, is a graduate of Harvard graduate school of design. Strong experience in product design and user experience.  
Email: shuyue_li@gsd.harvard.edu
Linkedin: https://www.linkedin.com/in/shuyue-li-109496152/

Member 3 - 
Name: Chilo Nwokolo - Front-End developer and blockchain engineer. 
Email: chilo.nwokolo@gmail.com
Github: constanteen
Linkedin: https://www.linkedin.com/in/chilo-nwokolo/

Member 4 - 
Name; Musungu Phidel - smart contract developer and back-end engineer.
Email; mphidel@gmail.com
Github;  Phydy
https://www.linkedin.com/in/phydy/

* How did you learn about our microgrant program?
We learned about microgrant program through Chainlink startup program

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
ETHGlobal Hack money 2022, Eth NYC Hack

  * Please link to your hackathon submission
https://showcase.ethglobal.com/hackmoney2022/trust-finance-vqk0h

**Comment by ErinOCon** [comment]
HI @quadriproduct, thank you for your proposal! Can you confirm the project is open source?

**Comment by quadriproduct** [comment]
Hello ErinOCon,

Yes the project is open source.

**Comment by quadriproduct** [comment]
Hello ErinOCon,

Here is the open source Github - https://github.com/quadriproduct/trust-finance-app

Let me know if you have any questions. 

Looking forward to hearing from you

**Comment by ErinOCon** [comment]
Hi @quadriproduct, thank you for your patience as we proceed with our final review. I didn't see IPFS/related tech in the current code, is this being incorporated in your next steps? If so, can you briefly describe? Many thanks!

**Comment by quadriproduct** [comment]
Hello ErinOcon,

Yes, this is currently being implemented in the next steps. We were not
able to complete it during the Hackathon.

Regards,

Quadri.

**Comment by ErinOCon** [comment]
Thank you for your patience with our review. Unfortunately, we will not be able to proceed with a grant at this time as this program is intended to support projects that are actively using our tech in their prototype. Please feel welcome to reapply as you make additional progress!
