### ISSUE TITLE
Music Entrepreneur University - Decentralized Learning System

### ISSUE THREAD

**Issue by useriff** [filecoin-project/devgrants#845]
# Open Grant Proposal: `Decentralized Learning`

**Name of Project:** Music Entrepreneur University

**Proposal Category:** `app-dev`

**Proposer:** `useriff`

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

Problem - Life as a creator entrepreneur is overwhelming: the rise of technology creates a million paths & new revenue streams to grow your career, resulting in a tsunami of info & massive uncertainty. With the rising GDP & available revenue across the creative fields, the existing educational systems can't keep up with demand or content. Existing educational material online is lengthy/not relevant to the specific task a creator has to accomplish, and usually comes from one perspective (leading to bias). Becoming an independent creative entrepreneur is only accessible to high socio-economic industry people. 

Solution - To solve we're building a virtual business partner (musicentrepreneur.co). Layering in a decentralized learning system empowers creative entrepreneurs to learn how to build a sustainable business while providing monetization opportunities for industry experts. We plan to layer proven contribution systems to build high-impact collaborative content at scale with our existing edtech & 5k+ engaged community.  

## Value

To build a decentralized learning system that intakes & manages continuous contributions around the world for the millions of creative entrepreneurs, we'll need to leverage the tools in the Filecoin ecosystem to store & manage massive data volumes. The risk of not getting it right is minimal as this data is driven by contribution (not personal data). The largest risk for execution will be educating industry experts & educators on the system. We plan to counter this by layering in multiple values in the token (incl. revenue), and run workshops+ for onboarding sessions/education.

## Deliverables

Ledger tracks & secures representation of content contribution/impact and revenue allocation. Virtual machines automate points accumulation (content quality, quality participation, etc.), tracks & disburses the revenue distribution, etc. Token value incentivizes learners to report feedback honestly, while the DAO aligns incentives from the music & creative development communities. 

## Development Roadmap

Milestone 1 - MVP & Pilot - $25k
- SMART contracts distributes appropriate volume of tokens for each stakeholder based on manual inputs
- Team: Demi, Harrison, Toluwa
- Target Date: September End

Milestone 2 - Automate Learning Model - $50k
- System intakes revenue from 3rd parties & distributes to appropriate tokenholders
- System stores SMART contract data
- SMART contracts distributes appropriate volume of tokens for each stakeholder based on automated inputs
- Team: Demi, Harrison, Toluwa, Rachel
- Target Date: December End

Milestone 3 - Decentralize Learning Model - $100k
- Fully decentralized (DAO)
- Earn-to-learn model integrated (where productivity = revenue source)
- Additional points-system (i.e. feedback/upvotes) integrated & tied to token distribution
- Team: Demi, Harrison, Toluwa, Rachel
- Target Date: July (2023) End

## Total Budget Requested

Budget Requested: $175k
- 100 high-impact tutorials created
- 200 collaborations & wallet interactions
- Token-system stood-up

## Maintenance and Upgrade Plans

# Team

Member 1 - [Harrison Lee] (https://www.linkedin.com/in/harrison-lee-a739515a/) - Product Build & Integration
Multiple hackathon winner & product lead at media/entertainment firm - his value is derived from experience building high-impact product with scarce resources and from a deep experience of creative education systems/architecture

Member 2 - [Rachel Karry] (https://www.linkedin.com/in/rachel-lynn-karry-1172141b/) - Community Build & Engagement
Her indie label has decades of successful experience monetizing musicians with limited fans - through signed musicians selling millions of records, their global music entrepreneur conference, and an industry network (LiveNation, Sony/AWAL, etc) with a ready reach of 5M+ transactions.

Member 3 - [Demi Oyebanji] (https://www.linkedin.com/in/demi-oyebanji/) - Building Points-Based System
Built companies with incentive programs & ran his own independent music label; his value lies in his experience working with industry experts, music entrepreneurs, and educators.

Member 4 - [Toluwa Fayemi] (https://www.linkedin.com/in/toluwafayemi/) - Engineer
Physics & Astronomy graduate with a strong background in Machine Learning, Deep Neural Networks and A.I. Constantly seeking opportunities to grow and learn both within and outside of academia. Former teacher and science educator with a passion for sharing the love of math and science with youth!

## Team Website

https://musicentrepreneur.co

## Relevant Experience

Why Us - Our team has decades of experience running & developing music entrepreneurs, with a large community driven from an annual conference. We've also vetted this system by education experts. We've seen the high quality of content & community with a similar system via Water/Music. We have the technical infrastructure that will interface & scale with the token contribution system (tutorial upvotes driving points, revenue layer integrated, etc.).

## Team code repositories

https://github.com/tfayemj

# Additional Information
Learned about Open Grants as a referral from Melissa (mintworthy.xyz). Feel free to contact me at harrison.lee@useriff.com.
We're looking for additional support & resources to learn how to best store & manage data for our SMART contracts.

**Comment by ErinOCon** [comment]
HI @useriff, thank you for your proposal! We will not be moving forward with a grant for this project, but would be interested in the possibility of providing a smaller grant that focuses on the educational piece of your work. Please feel welcome to submit a new proposal that focuses on the learning module/process.

Thank you again for your time with this proposal! Wishing you the best with your project!
