### ISSUE TITLE
Next Step Microgrant: Carbon NFT

### ISSUE THREAD

**Issue by lisztcoin** [filecoin-project/devgrants#846]
### 1. What is your project? (max 100 words)

Carbon NFT is a lucky draw system. A NFT will be awarded everyday to one lucky person among all people who have recorded their carbon activities. The system requires no gas usage on the user end, thus lowers the barrier of entry to the minimum. The project won runner up prize in the Sustainable Blockchain Hackathon. 

### 2. Project links
  
Link to Github repo: https://github.com/lisztcoin/carbonnft
Link to demo or website, if applicable: https://youtu.be/TLvybBBwBwc

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

OrbitDB is used for database storing user information and interaction; IPFS is used for NFT image and metadata storage.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

I'm confident that my zero-gas concept is the key to attract users so they can record activities and win prize without paying anything. My goal is to improve the project in below areas to provide a great experience for users, and hopefully it serves as some incentives for people to reduce their daily carbon emissions and cultivate a habit for environmental friendly behaviors.

* Nicer daily NFT. In hackathon I was using the same image and metadata. For this grant I will implement a nouns-like automatic generative NFT with custom metadata with the help of IPFS and Chainlink.
* Better OrbitDB integration. In hackathon I was only using the very basic functionality of OrbitDB. For this grant I will explore  more functionalities and improve security for my application. 
* Modern UI. In hackathon I was re-using the control center UI for convenience. I will update the UI so it will look like a professionally-made product.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://gitcoin.co/issue/29009
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project. **Kevin, lisztcoin@gmail.com, Developer**
* How did you learn about our microgrant program? **Email. Thanks for emailing me for this opportunity.**
* If your project was created as part of an event or hackathon: **Yes**
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum): **Sustainable Blockchain Hackathon**
  * Please link to your hackathon submission:  https://gitcoin.co/issue/29009

**Comment by ErinOCon** [comment]
Hi @lisztcoin, thank you for the proposal! Can you confirm this project is open source?

**Comment by lisztcoin** [comment]
Oops did not realize it was private! Just made the repo public and it will be open source. (will change readme accordingly, currently is still for the hackathon submission)

**Comment by lisztcoin** [comment]
@ErinOCon wanna follow up on this since it's already two weeks. Thanks!

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by lisztcoin** [comment]
Thank you! I will send occasional updates here and final report to your provided link!

**Comment by lisztcoin** [comment]
My wallet received grant last week. Will start to work. Thanks!
