### ISSUE TITLE
Next Step Microgrant: Filecoin + IPFS + S3

### ISSUE THREAD

**Issue by kyroninja** [filecoin-project/devgrants#847]
### 1. What is your project? (max 100 words)

Linking CORTX S3 (any s3 implementation) to IPFS and using Filecoin as an incentive for data storage

### 2. Project links
  
Link to Github repo: https://github.com/kyroninja/cortx/tree/main/doc/integrations/s3filecoin
Link to demo or website, if applicable: 

Demo
https://youtu.be/yA_qGKGFHCQ

Install
https://youtu.be/6NqOxSdcRXw

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Currently there is no incentive for a user to run an IPFS node, with filecoin, the node user can be given filecoin as an incentive to keep an IPFS node running and contribute to the effort of a decentralized data store. The implementation uses s3 as a base with ipfs and filecoin on top and powergate as a high level interface with all the layers.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The implementation was tested on a local devnet using powergate as a middle-man. The implementation needs to be tested against the mainnet. The next step would be to perform actual storage and retrieval using filecoin to pay for data etc. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* Yes - https://devpost.com/software/devpost-hackathon-2022-cortx-filecoin-integration
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
 * Shraddha Neerputh - dhrtirajcoomar@gmail.com - Designer/Coder

* How did you learn about our microgrant program?
* Email/Word of mouth

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) [CORTX & Filecoin Integration Challenge 2022](https://seagate-cortx-hackathon2022.devpost.com/)
 
  * Please link to your hackathon submission
  * https://devpost.com/software/devpost-hackathon-2022-cortx-filecoin-integration

**Comment by ErinOCon** [comment]
Hi @kyroninja, thank you for your proposal! Can you confirm this project is open source?

**Comment by kyroninja** [comment]
Hi @ErinOCon,

Yes it is open source

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
