### ISSUE TITLE
Next Step Microgrant: blankSpace - The DeSoC of Professionals

### ISSUE THREAD

**Issue by rohit-goswami** [filecoin-project/devgrants#849]
### 1. What is your project? (max 100 words)
In the web3 space, the supply and demand of skilled people are hugely imbalanced. Furthermore, web3 companies still hire based on resumes in the traditional manner. I think this is a great time to change how we hire and get hired.

blankSpace is building a fully decentralized society (DeSoc) of professionals which would help people learn, grow, and verify their skills on the blockchain using SBTs (soul-bound tokens). Without having to rely on third-party services, organizations can find the right candidate at the right time. Our goal is to revitalize the entire professional networking ecosystem. 

### 2. Project links
  
Link to Github repo: https://github.com/rohit-goswami/blankspace
Link to demo or website, if applicable: https://blankspace-alpha.on.fleek.co/#/

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
<img width="768" alt="blankSpace Interaction" src="https://user-images.githubusercontent.com/15854015/184001253-6c447da8-cf9e-430f-a9ca-ca46ec2bf243.png">

In our Proof-Of-Skill arena, organizations can host skills-based tests, and people can attempt those to earn a Proof-Of-Skill token (soul-bound token). The metadata of tests is stored on IPFS via web3.storage leveraging IPFS/Filecoin technology. Submissions from users are stored in IPFS.  Images and metadata for Proof of Skill, Proof of Membership, and Proof of Partnership tokens are also stored in IPFS using web3.storage. For token gating, we are going to use the Lit Protocol and IPFS. 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

In our roadmap, we plan to accomplish a few milestones within a year. On our website, you can view the entire roadmap. This grant will help us complete our second milestone, a decentralized marketplace where everyone can showcase their profiles. This pool of skilled individuals will enable companies to hire talented employees.  

Our plan:

1. Buy the domain.
2. UI and website design improvements: we will add a new team member for UI design and website design improvements. 
3. We will implement the Pool of Skilled People marketplace (second milestone) during these three months. UI designing, Smart Contracts, and IPFS for storing off-chain data.
4. Implement subgraphs for querying data, Token Gating, and content encryption. Implementing logic for Proof of Membership token and Proof of Partnership token and storing metadata in IPFS. We are exploring Polygon DID(decentralized Identity) and gassless minting of ERC721 tokens and we will implement them during these 3 months. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://ethglobal.com/showcase/blankspace-the-desoc-of-professionals-9230w
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
1. Rohit Goswami 
Role: Smart Contract Developer and Security Researcher
Github: https://github.com/rohit-goswami
Email: lynus.mascot@gmail.com
LinkedIn: https://www.linkedin.com/in/goswami-rohit/
2. Joseph Chetrit
Role: Smart Contract Developer
Github: https://github.com/josepchetrit12
Email: jchetrit1999@gmail.com
LinkedIn: https://www.linkedin.com/in/josep-chetrit-1751621ab/
3. Iuri Pons
Role: Front-end Developer
Github: https://github.com/IuriPons
Email: iuri.19.05@gmail.com
LinkedIn: https://www.linkedin.com/in/iuri-pons-80881a1b8/

* How did you learn about our microgrant program?
I was contacted by niki.gokani@protocol.ai in an email.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  Name of the Event: EthGlobal HackFS 2022
  * Please link to your hackathon submission
  https://ethglobal.com/showcase/blankspace-the-desoc-of-professionals-9230w

**Comment by ErinOCon** [comment]
Hi @rohit-goswami, thank you for the proposal! Can you confirm if this project is open source?

**Comment by rohit-goswami** [comment]
Yes, the project is open source under MIT license.

**Comment by rohit-goswami** [comment]
@ErinOCon please provide update for my project proposal.

**Comment by ErinOCon** [comment]
Hi @rohit-goswami, I am happy to confirm that this grant has been approved. We will follow up by email to confirm payment details.
