### ISSUE TITLE
Elastic: NFT rental aggregator and marketplace

### ISSUE THREAD

**Issue by kitfud** [filecoin-project/devgrants#850]
### 1. What is your project? (max 100 words)
An NFT rental aggregator where people can list their NFT for sale and describe some of the benefits derived from renting the NFT- the lister can also set all the terms of the agreement as a part of our platform, 'Elastic' being a minting platform for creating personalized smart contracts for brokering the exchange of a digital asset. Once a rental takes place we have a dashboard with dynamic information about the growing cost of rental as well as a deadline for return. To help maintain the integrity of the agreements, and the returns of NFTs, we have incorporated IPFS.

### 2. Project links
  
Link to Github repo:
https://github.com/EWCunha/EthGlobal-nftRent-elastic
Link to demo or website, if applicable: (use Rinkeby test eth + Metamask)
https://elastic-nft-renting-protocol.netlify.app/

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  Once a rental agreement takes place, a client and vendor receive an 'receipt', which we conceptualized as a file on IPFS. These records are stored on the user dashboard within our application and can be referenced anytime. Conceptualized use cases for these are for enforcing legal agreements offline or for accounting purposes. 
 
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
It would be distributed to team members, 1000 each. So to compensate for their time- 3hr (min) commitment before the 3 month deliverable deadline. This would entail everyone making at least one commit to the code base and involving themselves in discussions around what we are trying to build. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes- I can keep an itemized receipt of it and can submit it upon completion. Note, what was outlined in 4 is how I will proceed with the funding- I am open to suggestions but I think this is a fair request from our team of 5.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes, I read it. I appreciate an inclusive and fair space as well and am in agreement.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  Yes we did and we did not win anything during the actual hackathon. 

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* GZR, gloriareilly@protonmail.com,https://github.com/GZRdev, front end features and application touchups 
*  Joshua, joshualyguessennd@icloud.com, https://github.com/joshualyguessennd, authored back end smart contracts and revised them as needed
* Edwardo,eduardowestc@gmail.com, https://github.com/EWCunha, improved back end smart contracts and took on advanced front end features
* Svarogg, svarogg@tutanota.com, https://github.com/svarog-g, discussion, advising and feedback.
* Kit, kitfuderich@gmail.com, https://github.com/kitfud, app architecture/prototyping, front-end features + project management

* How did you learn about our microgrant program?
*We got an email from Niki, at Filecoin&IPFS about possible ways to get some support. 

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  *HackFS was the hackathon we came up with and developed the concept for
  * Please link to your hackathon submission
  * https://ethglobal.com/showcase/elastic-gybwe

**Comment by ErinOCon** [comment]
Hi @kitfud, thank you for your proposal! Can you confirm if this project is open source?

**Comment by kitfud** [comment]
@ErinOCon yes I can confirm it is open source

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
