### ISSUE TITLE
Next Step Microgrant: Floppy

### ISSUE THREAD

**Issue by TeodorescuCostin** [filecoin-project/devgrants#853]
### 1. What is your project?

Floppy is a project in which we've made two ends, Provider and Client. The providers will put at the dispose their storage. So they will run the script.sh on their linux machine and will connect to our private network on IPFS. The clients will have the option to store data on our website if they have an NFT. The NFT's are generated when you create your account. Overall Floppy is a cloud storage system that is fully decentralized from the creation of your account to the way on how data is stored.

### 2. Project links
  
Link to Github repo: https://github.com/TeodorescuCostin/hackFS
  
### 3. How is IPFS, Filecoin, or related technology used in this project?

We've used IPFS in this projects for both ends. We've created an IPFS private network in which the new providers can join to share their space storage for the clients. Also we've used IPFS in the client side. In this way we store the client's files in our private network where is received by our providers.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective?

We will take our project to the next level by:

- Creating an application for desktop, more specifically for Windows users
- Improving the design of the application:\
   - We will modify the menu on the side and also we will make changes to the main panel
- We will scale the efficiency of the account's structure so that every account will have their own UEID

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes, this proposal complies with the [Filecoin Code of Conduct](https://github.com/filecoin-project/community/blob/master/CODE_OF_CONDUCT.md).

### 7. Links and submissions

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:  https://ethglobal.com/showcase/floppy-6zvhk

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

   * Stefan Simion - stef.baloo123@gmail.com - DavidFanaru - Frontend Developer
   * David Fanaru - davidfanaru@gmail.com - stefsimion - Backend Developer
   * Costin Teodorescu - costin.teodorescu5@gmail.com -  TeodorescuCostin - FullStack Developer
  
* How did you learn about our microgrant program?
Through conversations we had with Niki Gokani from Protocol Labs.
* If your project was created as part of an event or hackathon:
  * What was the name of the event?
  ETHGlobal HackFS
  * Please link to your hackathon submission
  https://ethglobal.com/showcase/floppy-6zvhk

**Comment by ErinOCon** [comment]
Hi @TeodorescuCostin, thank you for your proposal. Is this project open source?

**Comment by TeodorescuCostin** [comment]
Hi @ErinOCon, yes this project will be fully open source
