### ISSUE TITLE
Next Step Microgrant: ChainLook

### ISSUE THREAD

**Issue by saleel** [filecoin-project/devgrants#854]
### 1. What is your project? (max 100 words)
ChainLook is a platform for creating analytics/visualization dashboards from decentralized data source like TheGraph, IPFS, Tableland, etc. Definition for the widgets and dashboards are stored as JSON files in IPFS.

This was originally build during ETHGlobal HackFS2022 hackathon and [was one of the top 10 projects](https://ethglobal.com/showcase/chainlook-1ft9u).

Demo : [https://chainlook.xyz/](https://chainlook.xyz/)
Repo : [https://github.com/saleel/chainlook](https://github.com/saleel/chainlook)

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
The definition of widget (JSON configuration containing what to render, data source, filters), and the definition of the dashboard (widget JSON and the layout) created by the users are stored on IPFS and addressed using CID. The URL of a dashboard would be `dashboard/$cid`. Users are free to publish and pin their own JSON config for dashboards/widgets to IPFS and view using ChainLook.

Additionally IPFS can be used as a data source for widget. A static JSON uploaded to IPFS, or a table from Tableland or a DB from OrbitDB (pending), can all act as a data source for widgets like LineChart, BarChart, Table, PieChart, etc.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
- Integrate OrbitDB as a data source.
- Add IPNS (alternatives) support for dashboard and widget IDs.
- Improve existing infra for storing and retrieving data from IPFS if necessary.
 
### 4. Is this project open source?
Yes, but still deciding on which license to use.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
Yes - [https://ethglobal.com/showcase/chainlook-1ft9u](https://ethglobal.com/showcase/chainlook-1ft9u)
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  - Saleel P saleel[at]me.com (Full stack developer - solo).
* How did you learn about our microgrant program?
  Searched online for grants from IPFS.
* If your project was created as part of an event or hackathon:
  * ETHGlobal HackFS2022 (one of the winning project)
  * [https://ethglobal.com/showcase/chainlook-1ft9u](https://ethglobal.com/showcase/chainlook-1ft9u)

**Comment by ErinOCon** [comment]
Hi @saleel, thank you for your proposal! Can you confirm that this project is open source?

**Comment by saleel** [comment]
Hi ErinOCon,

Yes, the project is open source and available here - https://github.com/saleel/chainlook <https://github.com/saleel/chainlook>

But I have not added a license yet. I normally go with MIT license but this is not a library that others would need to use use. Its a whole project, and I am keeping it open for transparency and allowing others to run their own versions / build on top of this. I need to do some research on what would be the ideal license for this use-case.

**Comment by ErinOCon** [comment]
Hi @saleel, thank you for the update! Can you confirm if the license for this project will align with [our policy](https://github.com/filecoin-project/devgrants/blob/master/open-source-policy.md)?

**Comment by saleel** [comment]
Hi @ErinOCon ,

I have added Apache license to the project. Is this enough? 
I can dual license it under MIT + Apache if this is a requirement.

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
