### ISSUE TITLE
Next Step Microgrant: <Your Title Here>

### ISSUE THREAD

**Issue by JanRuettinger** [filecoin-project/devgrants#855]
### 1. What is your project? (max 100 words)
My project DeGA is a decentralised photo gallery for NFT communities. All photos are stored on IPFS. Links to files on IPFS are managed in a table which is stored on-chain. Only members of an NFT community can make changes to that table.

### 2. Project links
Link to Github repo: https://github.com/JanRuettinger/hackfs2022-dega
Video (shows demo): https://stream.mux.com/xERkJ6262ORD00psC9501vjotuBjZ3EuQoKjospKx3kVk/high.mp4 

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
IPFS is used to store photos uploaded by the community.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
I will use the grant money to support myself while turning the MVP into product. I build the MVP during a Hackathon (hackFS) and a critical service went down during the Hackathon which made it pretty difficult to debug the code.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
HackFS: https://ethglobal.com/showcase/dega-decentralised-gallery-hr2o6 
=> Didn't receive any Protocol labs prices 
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Jan-Hendrik Ruettinger
E-Mail: service+filecoin@janruettinger.com
Role: Developer

Name: Renata Enriquez
E-Mail: renatanrqz@gmail.com
Role: Designer

* How did you learn about our microgrant program?
I received an email from Filecoin after my Hackathon project submission.

* If your project was created as part of an event or hackathon:
HackFS

* What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
HackFS

* Please link to your hackathon submission
https://ethglobal.com/showcase/dega-decentralised-gallery-hr2o6

**Comment by ErinOCon** [comment]
Hi @JanRuettinger, thank you for your proposal. Can you confirm that this project is open source?

**Comment by ErinOCon** [comment]
Hi @JanRuettinger, do you expect to have an update available this week?

**Comment by ErinOCon** [comment]
Hi @JanRuettinger, I hope you are doing well! Do you expect to have an update available this week?

**Comment by ErinOCon** [comment]
Hi @JanRuettinger, I have closed this issue. Please feel welcome to submit a new proposal with 1) confirmation that your work is open source and 2) a thorough breakdown of what you will complete next with your project.
