### ISSUE TITLE
Next Step Microgrant: Decentralized Event Ticketing Platform

### ISSUE THREAD

**Issue by shazi57** [filecoin-project/devgrants#856]
### 1. What is your project? (max 100 words)
A completely decentralized event ticketing platform designed to reduce the cost of hosting, attending and reducing platform dependency. There will also be a secondary market for tickets enabling creators to get a % of future sales (in the event of ticket arbitrage)

### 2. Project links
  
Link to Github repo:https://github.com/arthurka-o/decentralized-ticket-platform
Link to demo or website, if applicable:

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

We store NFT metadata and associated assets to NFT storage. Also deployed the website to Spheron via Filecoin protocol

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Grants will be used for developer time mostly

1. Complete rework on the frontend of the web by changing the framework to nextjs
2. Stabilize XMTP messaging between event creators and attendees
3. Add orbitDB as a decentralized database layer instead of storing event list on-chain
4. Utilize Ceramic for storing and managing user-centric data
5. use Zora's NFTDrop contracts for more cost-efficient smart contract deployment and sales of NFTs

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

 Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
(we had 4 people in the team, only I decided to continue the project)
1. Taewoo Ryu / xodn98@gmail.com / shazi57 / dev
* How did you learn about our microgrant program?
My team got emailed
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  HackFS 2022
  * Please link to your hackathon submission
https://ethglobal.com/showcase/decentralized-ticketing-platform-ok5fe

**Comment by ErinOCon** [comment]
HI @shazi57, thank you for your proposal! Is this project open source?

**Comment by ErinOCon** [comment]
HI @shazi57, do you expect to have an update available this week?

**Comment by shazi57** [comment]
Hi, sorry for the late reply. I thought you would communicate with my other
email. Is our project approved for the microgrant?

**Comment by shazi57** [comment]
Hi @ErinOCon , sorry for the late reply. This project will be open source, and I should be able to provide you with an update this week, but I was just curious whether our project has been approved for a microgrant or not.

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
