### ISSUE TITLE
Next Step Microgrant: Mojo

### ISSUE THREAD

**Issue by Webmoss** [filecoin-project/devgrants#857]
### 1. What is your project? (max 100 words)
Mojo is an audio/media streaming platform that empowers musicians, artists and content creators through web3 and blockchain technologies using IPFS, Filecoin/NFT.Storage. The Mojo web3 application allows users to upload their valuable digital assets easily and seamlessly to the IPFS Network via our upload and mint user interfaces. Creators can Mint NFTs and then add different attributes and values and assign these to the NFT based on the media type. Creators will be able to manage their NFT's metadata using Tableland's relational metadata protocol for EVM chains. Plans include cross-chain NFT metadata using Tableland.

### 2. Project links
  
Link to Github repo: https://github.com/Mojo-App
Link to demo or website, if applicable: https://mojo-lgp54n.spheron.app/

License as [CC-BY-SA 3.0]
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
The Mojo web3 application allows users to upload their digital assets to the IPFS Network via our user interfaces. NFT images and metadata are stored using NFT.Storage and IPFS as well as other services. Our website is also stored on IPFS and Fielcoin via Spheron.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. Complete core features including NFT minting and cross-chain metadata storage using Tableland
2. Complete music and video uploads to IPFS/Filecoin and NFT.Storage.
3. Authenticate user with Mojo NFT
4. Complete user collection page which fetches all NFT's from all chains
5. Search functionality for music and video NFT's, and more...
6. Create a social presence for Mojo
7. Create a business including setup website, .ens, emails, contacts info, etc. 
9. Launch a token for the project to go the next mile
10. Launch our exclusive NFT's to market

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
EthGlobal HackFS 2022 Project: [Mojo](https://ethglobal.com/showcase/mojo-11hkx)
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Name: Craig Moss
Email: craigmoss36@gmail.com
GitHub: https://github.com/Webmoss
Role: Design - Develop - Discover

* How did you learn about our microgrant program?
I believe one of the judges liked my project and I was sent an email by Niki Gokani, Ecosystem Growth, Filecoin & IPFS to apply for the Filecoin dev grant ;) thanks Alley

* If your project was created as part of an event or hackathon:
EthGlobal HackFS Project: [Mojo](https://ethglobal.com/showcase/mojo-11hkx)

**Comment by ErinOCon** [comment]
Hi @Webmoss, thank you for your proposal! This grant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by Webmoss** [comment]
Thanks @ErinOCon and Filecoin, this is really greatly appreciated!

**Comment by Webmoss** [comment]
Hello

I hope you are well today.

I would like to follow up with you please on the Mojo grant and Transfer
Request #623013301235, I submitted the correct forms for the grant and was
notified that the date on the w8ben form was incorrect. I then updated it
and re-submitted and again received a notice that the date was incorrect, I
again updated the form and re-submitted.

I believe the form to be correct as I have checked the format matches what
the document asks for, and used the date of signing which was the 14th
September

I did email ***@***.*** a few times to confirm this matter but
haven't received any response and got a bit worried.

I would like to make sure the grant is still on track and that the document
is correct, otherwise please let me know in detail about what I need to do
and will amend the form accordingly.

Another recent development is that I had to move my demo's domain due to
technical issues at spheron, the new domain is
https://mojo-music-nfts.netlify.app/.

Look forward to hearing from you

Regards

Craig Moss
contact us for all of your  hosting, support, website and custom
development needs.
We offer web solutions that fit the bill...
Cell: 082 229 2839
***@***.***
www.kaijoweb.com

**Comment by ErinOCon** [comment]
Hi @Webmoss, I hope you are doing well! Do you expect the final report for this project will be ready for submission soon? I understand the payment took additional time, please let me know if you need more time with this project.

**Comment by Webmoss** [comment]
Hi @ErinOCon Very well thanks, I have been really busy over the last while and have been working hard at achieving our goals. I was also accepted into the Tableland Pilot Program 02 and we have demo day today with all the Tableland community and rig holders who vote on the different projects. There was some excellent contenders and I've learnt so much again and got so many more cool ideas on how to make my project better.

I would like to kindly ask if I may have another week or so to put a report together and then close off this grant with the year with a much needed holiday. Next year I would like to continue building on additional features and carry on working on Mojo Music NFTs and would like to see what next steps can be taken with Filecoin's assistance. I'm also hoping that Tableland and NFT Port, will help me grow this project into a huge success.

Regards
Craig Moss

**Comment by Webmoss** [comment]
@ErinOCon I've completed the final report, let me know if you need more info or a demo ;)

I would like to find out more about the next steps we can take as a project building in the web3 space.
We have also been successful with the Tableland Pilot Program and would like to also work more with the protocol to further the project.

Thanks again Filecoin and IPFS, your assistance has been tremendous and is greatly appreciated.

Regards

Craig Moss
