### ISSUE TITLE
Next Step Microgrant: E-IPFS

### ISSUE THREAD

**Issue by ethereumtf** [filecoin-project/devgrants#859]
### 1. What is your project? (max 100 words)

E-IPFS is a hybrid IPFS service that embraces the advantages of decentralization and access security. It has the advantage of implementing decentralization based on IPFS/Filecoin and securing transmission security through OpenVPN.

### 2. Project links
  
Link to Github repo: https://github.com/ethereumtf/eipfs
Link to demo or website, if applicable: https://e-ipfs.web.app

### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

All files managed by E-IPFS are stored in IPFS/Filecoin. OpenVPN and VPN tunneling technology will be applied for business requirements such as connection via VPN and access management.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We will improve our project into a reliable service so that enterprise can actually try it.
Step 1. IPFS connection feature
- OpenVPN + IPFS
- VPN Tunneling
Step 2. Enterprise requirements
- Company user management
- IPFS file upload/download UI

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

https://ethglobal.com/showcase/e-ipfs-tdu8g 
 
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Benjamin Shim (myethereumtf@gmail.com, github.com/myethereumtf, Fullstack developer)

* How did you learn about our microgrant program?
This is a project submitted to HackFS 2022, one of the judges really liked it and received an email to apply.

* If your project was created as part of an event or hackathon:
  * What was the name of the event?
  ETHGlobal HackFS 2022

  * Please link to your hackathon submission
  https://ethglobal.com/showcase/e-ipfs-tdu8g

**Comment by ErinOCon** [comment]
Hi @ethereumtf, thank you for this proposal! Can you confirm the project is open source?

**Comment by ethereumtf** [comment]
Hi ErinOCon,

Yes, this project is open source and MIT licensed.

Here is the repository.

https://github.com/ethereumtf/eipfs

Thank you and kind regards,

Benjamin

**Comment by ErinOCon** [comment]
Hi @ethereumtf, thank you for the update. This grant has been approved! For nexts steps, we will reach out to you by email to confirm payment details.

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
