### ISSUE TITLE
Next Step Microgrant: CHELO

### ISSUE THREAD

**Issue by jvaldo** [filecoin-project/devgrants#860]
### 1. What is your project? (max 100 words)
DAO factoring app that allows DAOs to issue invoices to clients and sell the ownership of the invoices to increase capital efficiency. Usually when making transactions an invoice is issued, there are no tools in the web3 space that allow companies or DAOs to sell these invoices to receive liquid $$ on time in exchange for their invoices.

### 2. Project links
  
Link to Github repo: https://github.com/chelofinance/HackFS
Link to demo or website, if applicable: https://hack-fs.vercel.app/ 

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
We use IPFS/Filecoin to store metadata and documents related to each invoice issued. That information is crucial for having a decentralised open market for invoices. It will also traders decide whether to buy invoices or not. 

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Improve UI/UX (for us its a must the ease of use). We will also use it to audit our contracts and deploy them on ethereum (Gas fees) and other networks.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 Yes, at the prizes section it can be seen.
https://ethglobal.com/showcase/daofactoring-0tuvp

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Gerardo Lemus: CTO- > https://github.com/gllamat?tab=repositories&q=&type=public&language=&sort=
Rafael Contreras: Lead Developer -> https://github.com/Rcontre360/

* How did you learn about our microgrant program?
You sent us an invitation: “I am part of the Hackathons team at Filecoin / IPFS and worked on HackFS 2022 where you submitted your project:[ https://github.com/chelofinance/HackFS](https://github.com/chelofinance/HackFS). One of the hackathon judges really liked what you built and we would love to share how we can continue supporting you!”

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
HackFS 2022

  * Please link to your hackathon submission
https://github.com/chelofinance/HackFS

**Comment by ErinOCon** [comment]
Hi @jvaldo, thank you for your proposal. Can you confirm if this project is open source?

**Comment by jvaldo** [comment]
Hi Erin, 

Yes, this is an open source project.

**Comment by ErinOCon** [comment]
Thanks, @jvaldo! Has this project been handed off to your team after the hackathon? I currently do not see you listed as a participant.

**Comment by jvaldo** [comment]
Hi Erin, yes, I handle all the admin and funding stuff for the team. Would that be a problem?

**Comment by ErinOCon** [comment]
Hi @jvaldo, thank you for the confirmation! Can a member of your team that is linked to the project write a quick note confirming this submission? 

Thank you for your help with this! Please let me know of any questions.

**Comment by rafaelChelo** [comment]
Hi @ErinOCon! Im Rafael, part of the DAOFactoring team. I give my confirmation for this submission

**Comment by ErinOCon** [comment]
Many thanks for the confirmation, @rafaelChelo! This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
@rafaelChelo @jvaldo, can you provide the preferred email address for confirming payment details?

**Comment by TheCoCoClub** [comment]
Sure @ErinOCon, please send it to:
gerardo@chelo.fi
rafael@chelo.fi
jose@chelo.fi

Thank you!

**Comment by jvaldo** [comment]
Hi @ErinOCon, I just want to check the status. We haven't received any email for confirming the payment details. Please let me know if you need anything else. Thank you!

**Comment by jvaldo** [comment]
Hi again @ErinOCon, please let us know if we need to do anything else to complete the process. Thank you.

**Comment by jvaldo** [comment]
Please use jose@chelo.fi email address for confirming payment details.

**Comment by rafaelChelo** [comment]
Hi @ErinOCon! Should we make another transfer request? Because we haven't
received the microgrant on our wallet

**Comment by ErinOCon** [comment]
Hi @jvaldo and @rafaelChelo, you should only need to submit one transfer request. In case it wasn't already received, I have followed up with a new email with this information. Let me know of questions!
