### ISSUE TITLE
Next Step Microgrant : GiftaMatic

### ISSUE THREAD

**Issue by tusharojha** [filecoin-project/devgrants#862]
### 1. What is your project? (max 100 words)

GiftaMatic is a blockchain-based donation platform that allows people to donate via Matic, NFT, or passive incomes like APY yield, etc. The donors get rewarded with GFT tokens that are non-transferrable and make them eligible for NFT airdrops, gifts, and merchandise. 

People can easily create a campaign on the platform and share a link via social media to raise funds, the campaigns have proper titles, descriptions, images, and target / collected amount to show the donors to bring transparency. 

GitHub: https://github.com/giftamatic/giftamatic

Twitter: https://twitter.com/giftamatic

Website: https://giftamatic.org/

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

We are using web3.storage library on the frontend that immediately uploads all the campaign metadata to the IPFS network.
As of now, we are using Filecoin, and IPFS to store data like images, long descriptions (with markdown), and more to avoid extra gas fees paid by users if stored on the chain. We are going to store more data on IPFS like reward NFT’s metadata, user donations history data to track all the donations made so far, and campaign completion proof data (like images, videos, and more). 

We are working on creating a profile system for donations that will include a complete donation image of a user. They can burn GFT tokens to get some rare elements of an upgradable NFT to showcase on social media. All the data for rare elements, and upgradable NFTs will be stored on IPFS using Web3.storage and NFT.storage. 

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The grant amount will be used for the following:

- Hiring UI / UX designer
- 1 web dev to build a beautiful frontend
- Adding new features to the project
    - Improved version of NFT donation with support for auctions i.e. people can donate NFT and their NFT gets auctioned. The person who wins the bid pays for the campaign.
    - APY donation to allow people to donate without losing their crypto.
    - Upgradable NFT as reward i.e. burn GFT tokens to claim rewards
- Improving the UI / UX of the website
    - We still need a lot of work on revamping the website with a new design theme that our designer suggests.
- Launching the project from testnet to mainnet
    - We have the project on testnet right now, but we will use the grant to launch it on mainnet which includes paying the gas fees, spreading awareness, and doing a few airdrops.
    - We will need people to do a few campaigns on the project, and for that, we can use some part of the grant as a donation to some hosted campaigns

Some extra costs include: 

- Domain renewal cost
- Vercel premium version
- Paying for a graphic artist for NFTs
- Booking ENS domains

### 4. Is this project open source?

Yes, with MIT License. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes - we agree to share a final grant report.

### 6. Does your proposal comply with our Community Code of Conduct?

We have read and acknowledged the Filecoin Code of Conduct.

### 7. Links and submissions

GitHub: https://github.com/giftamatic/giftamatic

Website: https://giftamatic.org/
Hackathon Submission Link: https://devfolio.co/projects/gift-a-matic-56cd

### Additional questions:

- For each team member(s), please list name, email, Github account, and role in the project.
    - Tushar Ojha (Smart Contract & Frontend Dev)
    - GitHub: @tusharojha
    - Email: tusharojha2001@gmail.com

Currently, I am working alone, but this grant will help me hire more developers.

- How did you learn about our microgrant program?
    - From a friend: Raj Karia
- If your project was created as part of an event or hackathon:
    - What was the name of the event?
        - Warpspeed Hackathon by Lightspeed India
    - Please link to your hackathon submission
        - https://devfolio.co/projects/gift-a-matic-56cd

**Comment by ErinOCon** [comment]
Hi @tusharojha, thank you for your proposal, This grant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
