### ISSUE TITLE
Next Step Microgrant: Design Proposal 

### ISSUE THREAD

**Issue by cryptotwilight** [filecoin-project/devgrants#863]
### 1. What is your project? (max 100 words)

DesignProposal is a new way for DAOs to shape proposal ideas. The dApp is designed to use IPFS directly to enable the creation of a proposal that has had open community contribution and voting so as to deliver a higher quality of idea for the community to vote on. The primary focus of this dApp is to support more complicated proposals that require higher levels of competence during their formation so as to make them consumable and governable by the DAO community. 

### 2. Project links
  
Link to Github repo:
https://github.com/cryptotwilight/designproposal

Link to demo or website, if applicable:
https://blue-scene-9553.on.fleek.co/

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
DesignProposal uses IPFS to store proposal sections and to store the completed proposal itself. It uses IPFS as the storage and CDN for proposals which are managed via smart contract. 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The objective of this grant will be to complete the content management dashboards that will allow users to manage multiple proposals across multiple DAOs. It will also fund the addition of a search function that enables preview and sale of proposals across DAOs. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

'YES'
  
### 6. Does your proposal comply with our Community Code of Conduct?

'YES'

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://ethglobal.com/showcase/designproposal-7ii7b 

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

Name: Tony Kunz 
Email: (tonyusheuk@gmail.com), 
Github: cryptotwilight
Role: Project Founder 
Microgrant Info Source: Niki Gokani (Protocol Ai)
Hackathon: HackFS 2022
Submission: https://ethglobal.com/showcase/designproposal-7ii7b

**Comment by ErinOCon** [comment]
Hi @cryptotwilight, thank you for the proposal! Can you confirm if this project is open source?

**Comment by ErinOCon** [comment]
Hi @cryptotwilight, thank you for the update! This grant has been approved. We will be in touch by email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @cryptotwilight, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

**Comment by cryptotwilight** [comment]
Hi Erin,

Thank you for this, can I confirm you've received the final report?

Thank you

Tony

**Comment by ErinOCon** [comment]
Hi @cryptotwilight, yes, the report has been received. Thank you!
