### ISSUE TITLE
Next Step Microgrant: <Atticc>

### ISSUE THREAD

**Issue by AtticKnight** [filecoin-project/devgrants#864]
### 1. What is your project? (max 100 words)

Atticc is a web3 social media for crypto communities. We want to help communities launch, grow and monetise. Our vision is to return the ownership of identity, data, and monetisation to users and communities themselves. We help communities launch by allowing anyone to create an NFT collection for minting in under a minute for free, we help communities grow by providing them with a suite of crypto native tools, and we help them monetise using smart contract protocols for revenue sharing.

### 2. Project links
  
Link to Github repo: https://github.com/atticc/web
Link to demo or website, if applicable: https://atticc.netlify.app

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
One of our features is to help anyone launch an NFT collection for minting in under a minute for free. The NFT images users upload are saved on NFT.Storage.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. Develop more features including activating NFT communities for those who already have an NFT collection; creating a community by launching an NFT collection for minting on-chain; P2P token/NFT trading directly via messaging.
2. Improve UI and UX design to be more user friendly.
3. Make the product MVP quality and launch in the market.
4. Stretch goal: provide a data analytics dashboard for every NFT community, to help people know the data behind people, and meet the people behind the data.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
https://ethglobal.com/showcase/atticc-cobrv

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Jason Kan jason@atticc.xyz https://github.com/AtticKnight Product Manager
CY Lim cy@tcam.co https://github.com/cylim Software Engineer

* How did you learn about our microgrant program?
From an email I received from Filecoin/IPFS after winning a prize at HackFS 2022.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
EthGlobal HackFS 2022
  * Please link to your hackathon submission
https://ethglobal.com/showcase/atticc-cobrv

**Comment by ErinOCon** [comment]
Hi @AtticKnight, thank you for the proposal! Can you confirm if the project is open source?

**Comment by AtticKnight** [comment]
Hi Erin,

We agree to make progress to date and any progress made with the microgrant open source. 

We can’t promise to make all future progress post the microgrant open source though.

**Comment by ErinOCon** [comment]
Hi @AtticKnight, thank you for the update. This grant has been approved! For next steps, please provide access to your Github repo. Our team will be in touch by email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by AtticKnight** [comment]
Amazing, thank you so much! @ErinOCon
