### ISSUE TITLE
RFP Application: GreenFil - Sourcing Green Locations

### ISSUE THREAD

**Issue by cryptotwilight** [filecoin-project/devgrants#865]
# RFP Proposal: GreenFil - Sourcing Green Locations

**Name of Project:**
`GreenFil`

**Link to RFP:** Please link to the RFP that you are submitting a proposal for.
https://github.com/filecoin-project/devgrants/blob/master/rfps/green-grants.md 

**RFP Category:**
`green`

**Proposer:** 
`cryptotwilight`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Please respond with either "Yes" or "No"
"YES"

# Project Description

**_Please describe what problem or need your project addresses, why it's important, and your technical approach. Since this is a response to an RFP, make sure to address the request directly._**

Building on recent success at the Gitcoin hosted Sustainable Blockchain Hackathon the GreenFil team has decided to expand and go further with it’s work of helping Filecoin miners become and remain **Green**. The objective is to create a sound transparent platform on which new types of ReFi products in Carbon Trading can be created. 

Having reviewed our existing data challenge we identified is the skew in the distribution of **Green** Aware miners between a limited number of geographies. What this means is that whilst Filecoin miners are concentrated in a few areas and of those miners even fewer of them are **Green**. Given the need for the Filecoin network to not only decluster but also be intelligently **Green** about it, the GreenFil team identified that there is a need to correlate renewable energy source data with Filecoin miner locations. 

This creates the opportunity for Filecoin miners to do two things, first being to find ways to source and trade carbon credits from these **Green** sources more easily and second potentially redistribute operations to take direct advantage of these **Green** energy sources in their operations. This also helps to provide large storage consumers a better picture of which storage providers to leverage not only because of geographical concerns but also for **Green** concerns. 

## Development Roadmap

**_Please break up your research or development work into a clear set of 2-3 milestones._**

**_For each milestone, please describe the software functionality that we can expect after the completion of each milestone. This should be detailed enough that it can be used to ensure that the software meets the RFP scope._**

**_This section should be approximately 1 page long.
This project will consist of 3 major milestones_**

- Research and Data Structures 
- Infrastructure 
- Community 

#### Research and Data Structures

**Description**
The Research and Data Structures milestone is where the GreenFil team will research existing API based information sources that can deliver maintained data on Renewable Energy Sources (RES). This milestone will deliver the foundational reports and analysis necessary to drive the changes to infrastructure and service necessary for the community. The milestone deliverables are displayed in the table below: 

|ID |Deliverable | Content |
|---|------------|---------|
|D1|RES Data Collection Report |This report will describe the available Renewable Energy Source API data sources and the Geographies that are available. It will cover the risks and challenges associated with the selected data sources along with any data quality considerations|
|D2|Data Structure Report |This report will describe the aggregate data structures from both Filecoin Green and RES API data sources		   |
|D3|RES Data Mapping Report |This report will map the RES data sources to Filecoin Green data, ready for technical implementation|

**Duration**
The duration of each deliverable is described below:
|ID |Deliverable | Duration |
|---|------------|---------|
|D1|RES Data Collection Report|2 weeks|
|D2|Data Structure Report|1.5 weeks|
|D3|RES Data Mapping Report|1 week|

**Total Milestone Duration: 4.5 weeks**

**Staffing**
The staffing for each deliverable is described in the table below:
|ID |Deliverable |Headcount|
|---|------------|---------|
|D1|RES Data Collection Report|2|
|D2|Data Structure Report|2|
|D3|RES Data Mapping Report|1|

**Total Milestone Staffing: 5**

**Cost**
|ID |Deliverable |Cost|
|---|------------|----|
|D1|RES Data Collection Report|USD$3250|
|D2|Data Structure Report|USD$2655|
|D3|RES Data Mapping Report|USD$2500|

**Total Milestone Cost: USD$8405**

### Infrastructure and Service

**Description**
 The Infrastructure and Service milestone is where the GreenFil team will upgrade the existing GreenFil service 
 to incorporate the new data feeds and derivative data to provide the community with useful visualisations. 

|ID |Deliverable | Content |
|---|------------|---------|
|INF1|Java API ETL Code Upgrades|This deliverable consists of upgrades to the existing API Extract Transform and Load (ETL) code to introduce the new Renewable Energy Data Source fields, build new data processing modules and new integrations into |
|INF2|Solidity Code Upgrades|This deliverable consists of upgrades to the existing Ethereum smart contracts that support the UI, so that they can support the new data structures|
|INF3|UI/UX Upgrades|This deliverable consists of the upgrades to the UI and UX of the GreenFil site to support the new visualisations|

**Duration**
The duration of each deliverable is described below:
|ID |Deliverable | Duration |
|---|------------|---------|
|INF1|Java API ETL Code Upgrades|2 weeks|
|INF2|Solidity Code Upgrades|2 weeks|
|INF3|UI/UX Upgrades|1.5 weeks|

**Total Milestone Duration: 4.5 weeks**

**Staffing**
The staffing for each deliverable is described in the table below:
|ID |Deliverable |Headcount|
|---|------------|---------|
|INF1|Java API ETL Code Upgrades|2|
|INF2|Solidity Code Upgrades|2|
|INF3|UI/UX Upgrades|2|

**Total Milestone Staffing: 6**

**Cost**
|ID |Deliverable |Cost|
|---|------------|----|
|INF1|Java API ETL Code Upgrades|USD$3750|
|INF2|Solidity Code Upgrades|USD$3775|
|INF3|UI/UX Upgrades|USD$2500|

**Total Milestone Cost: USD$10,025**

### Community and Outreach

**Description**
 The Community and Outreach milestone will run concurrent to the previous  2 milestones. Our view is that our community must be engaged throughout this effort so as to gain early feature insights that will ensure success. The objective of this milestone will be to establish and grow

|ID |Deliverable | Content |
|---|------------|---------|
|CO1|Community Map|This is a map of the communities the GreenFil team intend to target, categorized into Filecoin, Web3, Web2|
|CO2|Community Outreach Report| This is a report on the outreach activity that has been executed alongside the previous milestones  
|CO3|Community Feedback Report| This report is a summary of community feedback acquired during previews of the various project deliverables. 

**Duration**
The duration of each deliverable is described below:
|ID |Deliverable | Duration |
|---|------------|---------|
|CO1|Community Map|2 weeks|
|CO2|Community Outreach Report|5 weeks|
|CO3|Community Feedback Report|2 weeks|

**Total Milestone Duration: 9 weeks **

**Staffing**
The staffing for each deliverable is described in the table below:
|ID |Deliverable |Headcount|
|---|------------|---------|
|CO1|Community Map|2|
|CO2|Community Outreach Report|3|
|CO3|Community Feedback Report|4|

**Total Milestone Staffing: 9**

**Cost**
|ID |Deliverable |Cost|
|---|------------|----|
|CO1|Community Map|USD$2450|
|CO2|Community Outreach Report|USD$4450|
|CO3|Community Feedback Report|USD$2450|

**Total Milestone Cost: USD$9350**

## Documentation, Education, and Community

**_Specify your plans for any documentation, education, and/or community-building that will be essential to your project's success._**

**Documentation** 
Software documentation will be provided as part of the standard GreenFil rollout. Business user documentation will be generated as an ongoing activity as part of the Community and Outreach milestone. 

**User Education** 
User Education will be supported via both Youtube based video tutorials and from 2 or 3 live workshops delivered towards the end of the programme as part of CO2 and CO3 deliverables.  

**Community Building**
Our strategy with respect to Community building is to make it a continuous activity throughout the programme. Our view is that this will help us grow a committed community.

## Other Deliverables

Specify any other deliverables proposed as part of this project.

## Milestone Summary

**This table should summarize all of the efforts above. For each milestone, please describe:
- Summary of milestone
- How many people will be working on each milestone and their roles
- The amount of funding required for each milestone
- How much time this milestone will take to achieve (using real dates)**

| Milestone No. | Milestone Summary & Staffing 	       | Funding 	       | Estimated Timeframe   | Estimated Time Frame        |
| --------------- | ----------------------------------------- |----------------|--------------------------|------------------------------|
| 1                     | Research and Data Structures              | USD$8405     | 4.5 weeks                     | 22/08/2022 -> 28/09/2022 |
| 2                     | Infrastructure and Service     	        | USD$10,025  | 4.5 weeks                     | 28/09/2022 -> 04/09/2022 |
| 3                     | Community and Outreach     		| USD$9350     | 9.0 weeks                     | 22/08/2022 -> 05/09/2022 |

## Total Budget Requested
**_Sum up the total requested budget across all milestones._**
**$27,780.00**

## Maintenance and Upgrade Plans
**_Specify your team's long-term plans to maintain and improve this project over time._**
Our plan for the project is focused around community engagement and contribution. Our goal will be to inspire a steady 
quorum of volunteer contributors who will help monitor and regularly maintain the project. We will look to commercialise the service to make it sustainable in line with market demand. 

# Team

## Contact Info

**_Provide us with a way to contact you (email is probably easiest). You can also email grants@filecoin.org with your GH username and link to your public proposal._**

Contact: tony@blockstarlogic.com

 
## Team Members

**Tony Kunz** 
Role : Project Founder / Projecct Lead
Github user [cryptotwilight](https://github.com/cryptotwilight) 
LinkedIn [LinkedIn](https://www.linkedin.com/in/tony-kunz-358a78166/)

## Team Website
Please link to your team's website here.
https://fragrant-bar-2053.on.fleek.co/index.html
http://www.blockstarlogic.com/

## Relevant Experience

**_Please describe (in words) your team's relevant experience, and why you think would do a great job with this RFP. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc._**

As a former management consultant, with experience working with public administrations at the local and central government (UK) level as well as with experience in regulated industries such as banking and finance, my commercial experience provides the necessary commercial understanding required to innovate Open Source Green solutions that move the Filecoin community forward. As an active blockchain hacker, open source contributor and founder, with projects such as JobCrypt (www.jobcrypt.com) and Open Block EI (https://www.blockstarlogic.com/obei/ ) I have sufficient understanding of the intricacies involved in building new blockchain protocols that have many unknowns. 

## Team code repositories
**_Please provide links to your team's prior code repos for similar or related projects._**
https://github.com/cryptotwilight/greenfil
https://github.com/Block-Star-Logic

# Additional Information
**_Please include any additional information that you think would be useful in helping us to evaluate your grant application._**

**Comment by ErinOCon** [comment]
Hi @cryptotwilight, thank you for your proposal! We will be in touch with an update or any questions once our review is complete.

**Comment by redransil** [comment]
Hi Tony! Sorry for the super long response time. The project you outlined is really interesting, and we are thinking along the same lines as you are. There are *a lot* of moving pieces, though, in building these tools and incentive structures to shift Filecoin in a more sustainable direction, and I think we need to workshop the approach some. Would love to talk about it, feel free to put some time on my calendar: https://calendly.com/ransil

**Comment by cryptotwilight** [comment]
Hi Alan, thank you for your time on the call. Based on our discussion, it would be logical to add an appraisal of Green Score rules that could be implemented using the new data. This would also imply the additional delivery of inclusive governance options. This would also necessitate an appraisal of incentives and to a lesser degree compliance mechanisms. This would create a strawman using the location aspect of the Green Score to which follow on projects could add the audit, forecasting and client aspects. 

From an outreach perspective it would make sense to have this as perhaps a forum track at Filecoin events where miners, clients and relevant stakeholders are invited to share their views. 

Do let me know if this resonates and considered next steps.

**Comment by ErinOCon** [comment]
This issue has been closed as the proposal is being reviewed through a different program.
