### ISSUE TITLE
Museum of Crypto Art Archive by Filecoin

### ISSUE THREAD

**Issue by shivani3000** [filecoin-project/devgrants#867]
# Open Grant Proposal: Museum of Crypto Art Archive by Filecoin

**Name of Project:** Museum of Crypto Art (M○C△)

**Proposal Category:**`app-dev`

**Proposer:** shivani3000

**(Optional) Technical Sponsor:** 

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** 
Yes 

# Project Description

The Museum of Crypto Art's mission to preserve the story of crypto art requires activity beyond just collecting of artworks from specific artists. Areas of vital importance in the broader crypto art movement include hosting culturally-significant events, analyzing curatorial practices, pioneering exhibition techniques, and experimenting in open Metaverse usage. Since incorporating as a non-profit foundation in March 2021, M○C△ has worked on creating a decentralized toolkit to assist in this mission. 

Members of the museum use our [dApp](https://app.museumofcryptoart.com/) Products to showcase their NFT collections and interact with a vibrant community of artists, collectors, curators, and creative developers. The Museum’s Multipass product, where users activate their NFTs for free, feeds directly into our **Community Collection: the largest decentralized art collection in the world with 8,609 artworks from 3,648 users**. M○C△ has also built a free and permission-less exhibition creation tool called Shows that ports directly into our flagship product **ROOM**: engine-agnostic 3D architectural objects that can be deployed into any virtual world. 

It is crucial that all the artworks in the Museum, and all the ways they are interacted with via M○C△’s products and community members, are both safely stored on-chain. **Without such a fix, crypto art preservation is impossible**. Having a safe, reliable, and standardized on-chain storage option accompanying the art movement itself is paramount for preservation and innovation. 

## Value

Blockchain’s capacity to record minute interactions on an infinite scale is redefining human record-keeping. As a cultural institution, M○C△ seeks to leverage this capability to bolster and advance the uniquely egalitarian crypto art movement.

Filecoin can help M○C△ realize this goal by providing support for the increasing number of users who are developing crypto art culture using our tools. Filecoin support would uplift the Museum — a market agnostic non-profit institution — by making it a gold-standard reliable storage system for art documentation and curation in web3. Additionally, by porting the security of a potential Filecoin-backed toolkit into all ROOMs, we incentivize record-keeping of all curation within the Metaverse and promote an interoperability-first metaverse culture. 

We have a wide-enough reach (with over 68,000 Twitter followers) to shape the entirety of crypto art culture, and **a commitment to Filecoin as our underlying storage solution will have ripple effects for crypto art as a whole**. It is crucial for us to create an archival solution for crypto art.

## Deliverables

We aim to ultimately **build a dynamic application around the immutable data we preserve on Filecoin**. The application will load all M○C△ artworks, architecture, and exhibitions from a single point in time, attributed to artists and collectors involved. Similar to the [Wayback Machine](https://web.archive.org/), but here focused on documenting the digital artistic renaissance brought about by cryptocurrency.

**Deliverable 1**
To begin, we store **Single NFTs (Crypto Art)** from the Museum on Filecoin:

1. All activated NFTs on our dApp currently [58,044 NFTs](https://dune.com/kleintonno/MOCA-MEMBERSPASS) 
2. Genesis Collection artworks [246 grail artworks](https://docs.google.com/spreadsheets/d/1HhLnZX6XtLwFKc5sFKyprhLpGwDmg9BEKWGBIaTNN6A/edit#gid=921645257) 
3. Community Collection artworks [8,609 artworks ++100 artworks added daily by users](https://app.museumofcryptoart.com/collection/community-collection) 

We integrate Filecoin with our dApp Multipass product and Community Collection so that all future users integrate Filecoin automatically in their uploading. File types to be supported here include .jpeg, .png, .mp4, .gif, .glb, .obj. 

**Deliverable 2**
Next, we store **ROOM NFTs (Museum Architecture and Exhibitions)** on Filecoin. A ROOM NFT is a customizable 3D architecture object hosting a fixed number of artworks within itself. ROOM can deploy into any virtual world, and each building becomes an *official curation* of the Museum.

For each owner of ROOM, the following ROOM NFT data will be on Filecoin:
1. ROOM Architecture (stored on ethereum, .obj)
2. [ROOM Architecture + Artworks](https://museumofcrypto.notion.site/M-C-ROOMs-7e5ff2af1d884f0c95e48a9c091152b3) displayed inside = a single curation (stored on polygon, .obj) 
    1. Metadata from the subgraph
    2. Data from M○C△ Show (tool we have built for the owner to curate each ROOM)
    3. Media data from Filecoin
    4. depending on the owner, they could have 1-1000 curatorial iterations of ROOM 

**Deliverable 3**
We create **an immutable application** to dynamically document the Museum of Crypto Art’s past, present, and future with Filecoin technology. It will be a permanent tool to learn about Crypto Art and its presence in the Metaverse — functional for non-web3-natives and crypto-natives alike.

## Development Roadmap

We plan to execute 5 months of full-time work over 1 year as we move from Deliverable 1 to Launch. We begin by storing Single NFTs (artworks), then ROOM NFTs (3d objects with multiple architecture/artworks inside), and finally producing an open *Filecoin Crypto Art Archive*. We anticipate the following breakdown in time and people:

**Deliverable 1**
45 days | 3 full-time ethereum developers | **complete Q1 2023** 
- Design and implement the fundamental software architecture for the integration.
- Connect APIs and setup a server with routines that automatically preserve new NFTs from the museum ecosystem.

We plan to execute 5 months of full-time work over 1 year as we move from Deliverable 1 to Launch. We begin by storing Single NFTs (crypto art), then ROOM NFTs (3d objects with multiple architecture/artworks inside), and finally producing an *Filecoin-Crypto Art Application*. We anticipate the following breakdown in time and personnel: 

**Deliverable 2**
45 days | 3 full-time ethereum developers | **complete Q3 2023**
- Expand the software architecture for compatibility with ROOMs.
- Throughput on this front might be higher, as all on-chain curations of any ROOM will be made available on-the-go to manifest the 3D media of the provenance .

As the ROOM ecosystem is taking shape, we’ll be able to generate and store curations of ROOMs in the form of aggregated glb files (architecture + NFT thumbnails on walls) to Filecoin. 

**Deliverable 3**
30 days | 3 full-time ethereum developers & 1 full-time architect | **complete Q4 2023**
- Design and build out the waybackmachine-style webapp that allows users to browse the conserved media in combination with the on-chain provenance record for each ROOM.
- Working with M○C△’s metaverse architect UntitledXYZ to deliver visuals of the product

We’ll build the permission-less web frontend that doesn’t rely on a centralized database to query, and load the 3D models of any ROOM at any given time from Filecoin. The curation meta data is pulled via TheGraph and additional NFT metadata of exhibitions queried from our ecosystem. 

**Marketing and Launch**
120 days part-time & 15 days full-time M○C△ team | **complete Q4 2023**
- create posts, graphic design, content production to bring first users into the application
- write 4 critical essays on Filecoin technology 
- engage artists and curators via marketing partnerships with ArtBlocks, Somnium Space, SuperRare, Christie’s, Polygon Studios, VerticalCrypto Art, PleasrDAO, FingerprintsDAO
- execute a Metaverse launch event and livestream to Twitter

**Total Budget Requested**
We request a total budget of $102,000 for this project based on the following costs:
- Software Development by 3 ethereum developers at [Qwellcode](https://twitter.com/qwellcode?lang=en)
    - $100/hr, 6 hours a day for 120 days: $72,000
- Metaverse Integration by untitledXYZ
    - $93.75/hr, 8 hours a day for 30 days: $22,500
- Marketing by M○C△ Team
    - $50/hr, 5 hours a day for ~30 days: $7,500

## Maintenance and Upgrade Plans

We will implement API endpoints and processes on our dApp that allow us to plug our Subgraphs and MySQL/AWS systems into Filecoin for ongoing conservation of media files. Depending on the circumstances and offerings by Filecoin we’d use Lotus or Estuary to interface with the storage provider. Qwellcode is going to maintain this backend and will make sure to upgrade server, software in the backend as well as frontend code bases along the way. We would request **$7,500** for any future maintenance of the existing application into 2024. 

Once the application has been created, we would be happy to pursue more conservation of cultural data through our AI Virtual Curator project. This AI-powered synthetic being will be the voice and collective conscious of crypto art, using blockchain data to provide real-time insight on artistry, viralness, political commentary, visual and symbol-based analysis. It would be incredible to store the Museum's AI inputs and outputs on Filecoin. 

# Team

Rene Schmidt
Kirk Finkel 
Alexander Gees
Markus Stickling
Shivani Mitra
Colborn Bell
Maxwell Cohen
Nikhil Koduri
Karan Malhotra
Daniel MacNeil
Michael Jathe
Julian Brangold

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/reneil1337
https://www.linkedin.com/in/kirk-finkel
https://www.linkedin.com/company/qwellcode-gmbh
https://www.linkedin.com/in/shivani-mitra/
https://www.linkedin.com/in/colbornbell/
https://www.linkedin.com/in/maxwell-cohen-6932b3127
https://www.linkedin.com/in/nikhil-koduri-07ab97186
https://www.linkedin.com/in/karan-s-malhotra

## Team Website

Official Website: [https://museumofcryptoart.com/](https://museumofcryptoart.com/)
Application: [https://app.museumofcryptoart.com/](https://app.museumofcryptoart.com/)
Wiki: [https://museumofcrypto.notion.site/Wiki-Museum-of-Crypto-Art-eb9824900aa1461b85b8a52e69b0d0b9](https://www.notion.so/Wiki-Museum-of-Crypto-Art-eb9824900aa1461b85b8a52e69b0d0b9)

## Relevant Experience

Qwellcode is an Ethereum developer group that has been building various web3 projects with NFTs focus since 2018. The company has existed since 2013, focusing primarily on  tailored software development, but starting with Virtual Reality development in 2015 with a strong focus on WebXR applications. 

Rene Schmidt is the Chief Technology Officer at M○C△ and leads a 3-person developer team within the Museum. Qwellcode was one of the first teams building on Polygon worldwide and they have expertise building open-source and gas-less tools for public good. Our product suite as outlined in our [Wiki](https://museumofcrypto.notion.site/Wiki-Museum-of-Crypto-Art-eb9824900aa1461b85b8a52e69b0d0b9) has been designed and created by Qwellcode. Rene had several other web3 involvements before M○C△, including the launch of POAP at ETHDenver 2019. He advises multiple projects in regards of NFTs and Metaverse tech.

## Team code repositories

 https://qwellcode.eth.limo/ + https://reneil.eth.limo/

# Additional Information

We learned about the grant program through Annie at IRLArt and Justin at MONA. Then, in talking with Sonia at Filecoin and Michelle at Protocol Labs, we have learned more about the dev grant program and Filecoin's goals. Please email shivani@museumofcryptoart.com to follow up. We welcome all your ideas and feedback. Below are some captures of our events, artist initiatives, and architecture-

![IMG_6883 JPG](https://user-images.githubusercontent.com/111304196/184689473-7cc4aad6-747f-4d2e-9a43-40c6888e546e.jpg)
![220728_16-Slot_Thumbnail (1)](https://user-images.githubusercontent.com/111304196/184689538-f8e7c347-e5e3-42b8-8666-93249cadd6ea.png)
![MOCA Manifesto Final (1) (1)](https://user-images.githubusercontent.com/111304196/184689551-82cd691c-5872-48b7-b309-e61a83795329.jpg)

**Comment by ErinOCon** [comment]
HI @shivani3000, thank you for your proposal. This grant has been approved! We will send an email to confirm next steps!

**Comment by shivani3000** [comment]
@ErinOCon, we had a call this morning with Anshuman and Zak. Deliverable 1 is now complete. Let us know what documentation you require to finalize this step and move on to the next. Thank you so much!

**Comment by shivani3000** [comment]
@ErinOCon @realChainLife we've completed Deliverable 2. Emailed to give details on how exactly, and clear verification on the technology creation. Please let us know how to proceed from here. Thank you!
