### ISSUE TITLE
RFP Proposal: IPFS-search engine

### ISSUE THREAD

**Issue by DecentralTech** [filecoin-project/devgrants#87]
# RFP: IPFS-search engine

**Name of Project:** IPFS-search engine

**RFP Category:** `app-dev`

**Proposer:** [@DecentralTech]

## Project Description

IPFS search engine mapping hash address to the semantic label.User can find content possible by search labels with IPFS search engine.

IPFS search engine point of departure is to solve data theft,vulgarity advertisement,fake traffic,keep the moral bottom line.

For example:Google controls about 77% of search traffic,and it had influenced on trillion of dollars in advertising.

A closed  search engine is not necessarily fair，and Probably unfair or monopoly。If we trust google，but what about the monopolists in the remaining search traffic？Are they fair and ethical like Google?

IPFS  search engine purpose is  solve  above question，and the technology is completely open source any one can join it。

## Deliverables

Fully functional IPFS search enginehave the following characteristics: 
- Copyright protection and Privacy protection
- Inspire share and search for free
- Decentralized advertising market
- Mobile version and PC version
- Open source libraries
- API
- Any one can start Block Explorer with local boot

## Event Details

| Milestone No. | Milestone Description | Funding | ETA |
| --- | --- | --- | --- |
| 1 | Algorithm research and implement | TBD | 2020-5 |
| 2 | Algorithm Validation | TBD | 2020-6 |
| 3 | Code upload and public | TBD | 2020-7 |
| 4 | Completed implementation of HomePage and search capability | TBD | 2020-8 |
| 5 | Test and Fix | TBD | 2020-9 |
| 6 | Issue web plug-ins and explorer | TBD | 2020-10 |
| 7 | Officially Online | TBD | 2020-11 |

## Contact Info

E-mail:chenwang@decentral.cc

## Maintenance and Upgrade Plans

- After project officially online，The team will fix important bugs last  once a week
- Optimization or upgrade the algorithm once a month 
- When the project is relatively mature，any one can add new function

## Team Website

https://dianduidian.tech/

### Relevant Experience
The team are all distributed storage professional researchers，all members be devoted to distributed storage promotion and equipment development，Distributed storage application development and data center integration construction.
Team members actively exploring and solving the problems of supply chain finance, traceability and bill storage.
We will use blockchain technology to achieve application innovation and strive to empower the real economy.

We finished a lot of projects that are Blockchain-related：
- Dianduidian-application
- Blockchain of XiAn education
- Blockchain of GuangZhou procuratorate
- Blockchain revolution of ShangHai antique market
- IPFS-browser

The famous IPFs community：
- ohttps://ipfsdrop.com/

**Comment by DecentralTech** [comment]
@eshon

**Comment by eshon** [comment]
Hi @DecentralTech,

Can you please provide more detail about how your search engine will work?

Specifically you say "mapping hash address to the semantic label" - where will this information be stored? How will the indexing and search work?

If your team includes researchers, do you have any links to previous papers or Github or other source code repos we can look at?

**Comment by DecentralTech** [comment]
@eshon 
Thank you very much~

We are writing a lightweight white paper including the following
A：decentralized search engine architecture
B：copyright protection and privacy protection
C：super node and light node
D：Ad auction ranking system
mybe and so one，anyway...we will try our best~

**Comment by DecentralTech** [comment]
BTW~~~
We will post it later and discussion and presentation it by our online meeting

**Comment by Lucas-Kohorst** [comment]
Hi @DecentralTech I like the idea. Curious if you have looked at [ipfs-search](https://github.com/ipfs-search/ipfs-search)? They index file and directory hashes and take a daily snapshot (which is queried with elasticsearch they also run a ipfs-cluster to publish the [latest updates](https://github.com/ipfs-search/ipfs-search/blob/master/docs/snapshots.md). 

Building on top of this using the [Wikipedia snapshot](https://en.wikipedia-on-ipfs.org/wiki/) search the ipfs hashes indexed by ipfs-search and Wikipedia entries [here](https://github.com/Lucas-Kohorst/ipfs-search-engine). 

Compared to what you are proposing (advertising, copyright/privacy, etc.) these projects are much smaller in scope, but curious if you have looked into them and how your indexing/searching will differ?
