### ISSUE TITLE
Next Step Microgrant: CassavaLand

### ISSUE THREAD

**Issue by iphyman** [filecoin-project/devgrants#870]
### 1. What is your project? (max 100 words)
CassavaLand is a multi-blockchain platform to create, explore and sell extra-ordinary non-fungible tokens (NFTs).
Cassavaland's core functionality at the moment is a platform to mint and showcase both ERC721 and ERC1155 standard NFTs on the Bittorrent, Binance, Boba network, Moonriver and Moonbeam blockchains.

### 2. Project links
  
Link to Github repo: https://github.com/cassavaland/mint-showcase
Live demo: https://cassavaland.vercel.app
Video demo: https://vimeo.com/717736971

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
The project uses [Pinata Cloud](https://www.pinata.cloud/) API to upload NFT assets and metadata to IPFS.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

At the moment, the core functionality of the project is just minting and displaying NFTs, we want to advance the project to add trading and to build a custom NFT indexer that will work across multiple chain.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* Yes, Cassavaland began as a hackathon project but no filecoin price. [Moonriver Hackathon](https://dorahacks.io/buidl/2713?roundProj=2007)
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* I.O Emmanuel
* Email: opensoftweb@gmail.com
* [Github](https://github.com/iphyman)
* Role: Co-founder and CTO
* How did you learn about our microgrant program?
* Through [Gitcoin](https://gitcoin.co)
* If your project was created as part of an event or hackathon:
  Submission was part of Moonriver Grant Hackathon
  * Please link to your hackathon submission
  * https://dorahacks.io/buidl/2713?roundProj=2007

**Comment by ErinOCon** [comment]
Hi @iphyman, thank you for your proposal! Is this project open source?

**Comment by iphyman** [comment]
> Hi @iphyman, thank you for your proposal! Is this project open source?

Yes, https://github.com/cassavaland/mint-showcase/blob/master/LICENSE

**Comment by iphyman** [comment]
Hello @ErinOCon is there a place a project can check grant application status?

**Comment by ErinOCon** [comment]
Thank you for your patience as we completed our review. This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by iphyman** [comment]
Hello @ErinOCon do I need to resubmit a transfer request because the due date of the previous one is far exceeded?
