### ISSUE TITLE
Next Step Microgrant: TradeRep

### ISSUE THREAD

**Issue by kiv1n** [filecoin-project/devgrants#871]
### 1. What is your project? (max 100 words)

TradeRep is a dApp that helps investors and beginners save money and time by filtering good traders from scammers with a reputation verified by blockchain.

### 2. Project links
  
Link to Github repo: https://github.com/traderep-space/app
Link to demo or website, if applicable: https://traderep-app.vercel.app/

### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  
IPFS (Web3.Storage, Filecoin) is used as a storage for data of traders, public and private forecasts.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

To finish the prototype, I still need to integrate oracle, improve the user interface, add support of complex forecats, and gather a community of early adopters.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes.

### 7. Links and submissions

- ETH Global Metabolism Hackathon - https://ethglobal.com/showcase/traderep-7gpzv
  
### Additional questions:

* For each team member(s), please list name, email, Github account, and role in the project.
  * Arthur Sabirzyanov, aloha@kiv1n.ru, https://github.com/kiv1n, developer.
* How did you learn about our microgrant program?
  * Filecoin website.
* If your project was created as part of an event or hackathon:
  * Yes, ETHGlobal Metabolism hackathon, https://ethglobal.com/showcase/traderep-7gpzv

**Comment by ErinOCon** [comment]
Hi @kiv1n, thank you for your proposal! Is this project open source?

**Comment by kiv1n** [comment]
Hey @ErinOCon, yeah, my project is open source.

**Comment by kiv1n** [comment]
The project also took third place in the Web3 Infinity Hachathon recently (FIL-Singapore ‘22 Summit) - https://twitter.com/force_ipfs/status/1562028169179279360

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
