### ISSUE TITLE
Next Step Microgrant: NFTickets

### ISSUE THREAD

**Issue by nonymousoctopus** [filecoin-project/devgrants#872]
### 1. What is your project? (max 100 words)
NFTickets is an open dapp that enables hosts to market and sell tickets to their events, and customers to browse and purchase tickets using a simple web/mobile interface. The dapp creates NFT tickets and relies on smart contracts and the blockchain for event tracking, customer verification, and in the future - for rewarding community participation and penalising bad bahavior, whilst using IPFS to store event marketing material, and in the future - seating or navigation details, and evidence collection for the penalty system.

### 2. Project links
  
Github [repo](https://github.com/nonymousoctopus/chainlink-hackathon-nftickets)
Demonstration [video](https://youtu.be/ZVe94JZ6uLc)
Prototype [apk](https://drive.google.com/file/d/1GnuljPu1Xdtxf667YXY5kQx-NzYWLNey/view?usp=sharing)

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
At the moment IPFS is use to store event graphics. Future versions will utilise IPFS/Filecoin to host a web interface with documentation and instructions, store relevant event collateral such as additional promotional materials, seat maps and attendance instructions, and most importantly to store evidence needed for event verification and complaint handling process.

  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
The grant will be used to fund the following:

- Improvements to exisiting smart contract (security and feature enhancements)
- Development of a web based front end for event hosts and customer - to be hosted on IPFS/Filecoin
- Development of an iOS version of the app
- Improvements of the Android version of the app
- Development of event verification and complaints functionality, leveraging IPFS/Filecoin for evidence storage
- Documentation and user guides

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes - Chainlink Sprint 2022 Hackathon [submission](https://devpost.com/software/nftickets-lsog6h)
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Andy, [nonymousoctopus@gmail.com](mailto:nonymousoctopus@gmail.com), [Github account](https://github.com/nonymousoctopus), Creator/Developer

* How did you learn about our microgrant program?
I was advised of it via an email from Protocol Labs.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
Chainlink Spring 2022 Hackathon

  * Please link to your hackathon submission
Hackathon [submission](https://devpost.com/software/nftickets-lsog6h)

**Comment by ErinOCon** [comment]
Hi @nonymousoctopus, thank you for your proposal. Is this project open source?

**Comment by nonymousoctopus** [comment]
Hi @ErinOCon, yes the project is and will continue to be open-source under the MIT license.

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
