### ISSUE TITLE
Next Step Microgrant: 𝔐𝔦̈𝔪𝔦𝔰

### ISSUE THREAD

**Issue by dysbulic** [filecoin-project/devgrants#873]
![Header](https://github.com/dhappy/forests/raw/main/public/header.svg)

### 1. What is your project?

𝔐𝔦̈𝔪𝔦𝔰 spiders an IPFS filesystem (comprehending symlinks) into a Neo4j
graph database instance in a tree rooted using the user's ENS name obtained from
Sign-In With Ethereum.

𝔐𝔦̈𝔪𝔦𝔰 is a communal “filesystem” which differs from a traditional directory tree in several ways. Resources can appear at multiple paths through the tree *(akin to symlinking)*, and each location resolves to an ordered list of resources. Ideally, *any* coherent path to a resource should resolve to it. Also, selection can be done using a single path or by conglomerating several.

The provides mutability to IPFS akin to [Ceramic](//ceramic.network), but using a central database *(which could eventually be sharded into a P2P system)*.

### 2. Project Links

* [Github Repository](https://github.com/dhappy/forests/)
* [Demo](https://mimisb.run)

*My project is currently licensed using the [Creative Commons Zero License](https://creativecommons.org/share-your-work/public-domain/cc0/), which puts it in the public domain.*

### 3. How is IPFS, Filecoin, or related technology used in this project?

The Neo4j instance stores context about blobs stored in IPFS.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective?

Ideally, I want for this project to run as a series of live-streamed pair-programming sessions via a Discord video chat streamed 24⁄7 to Twitch with one pair passing to another at the end of a session. I would like all parties to make a minimum fixed rate of $20⁄hour. This Navigator plus Driver plus a Witness is $60⁄hour times 24hour⁄day is $1,440⁄day times *(my ideal of)* a lunar month, at 29.53days, is $42,524⁄month.

With $5k, I'd work at scheduling experts in Neo4j for programming sessions. My initial task is writing a Git remote handler to serialize to and from the system. Also, updating the graph structure to support versioning. 

For HackFS, I did a simple app to spider an IPFS filesystem, decode symlinks, and store the structure in a Neo4j instance. There's also an interface for inputting a set of paths and displaying the images at their intersection.

This grant would cover a few months of Aura, Neo4j's cloud instances which run ~$75 / month at the low end.

Ultimately, I want to use this interface to allow users to create composites from hundreds of thousands of SVGs to design wraps for thirteen Cybertrucks which I get to have for a year before they go to the auction winners.

<p align="center">
  <img src="https://github.com/dhappy/forests/raw/main/public/cybertruck.svg" 
  width="350"/>
</p>

To this end, I want to allow for a structure where a group of images are shown in a conglomerate at higher in the tree, but then it's possible to decompose the image into accessible parts.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

I do.

### 6. Does your proposal comply with our [Community Code of Conduct](https://github.com/filecoin-project/community/blob/master/CODE_OF_CONDUCT.md)?

𝔐𝔦̈𝔪𝔦𝔰 does. I'm not completely ethically at ease with the copyright system it protects. One which creates a world where people suffer for want of digitally available information held back only to permit profit on intellectual property.

I'll just say that after the Revolution happens, people will have detailed credit as to digital information they create, but all of it will be public.

I think we'll one day create vast compendiums of open knowledge. One of my fervent hopes is that 𝔐𝔦̈𝔪𝔦𝔰 could be an early holder of that post-copyright file structure.

### 7. Links and Submissions

[HackFS 2022](https://ethglobal.com/showcase/mimis-zd5sn)

#### Personal Information

* I'm [dysbulic](https://dhappy.org)
* Principal Architect & Developer of 𝔐𝔦̈𝔪𝔦𝔰
* E-mailable at [dys@dhappy.org](mailto:dys@dhappy.org)
* [@dysbulic on GitHub](https://github.com/dysbulic)

#### How did you learn about our microgrant program?

An e-mail from [niki.gokani@protocol.ai](mailto:niki.gokani@protocol.ai).

<p align="center">
  <img src="https://github.com/dhappy/forests/raw/main/public/logo.svg" width="200"/>
</p>

**Comment by dysbulic** [comment]
I apologize that my demo is currently offline. I needed to switch it from Neo4j Sandbox *(deleted every seven days)* to Neo4j Aura *(their cloud-based offering)*, and in the process I've introduced a pernicious bug which will either cause the page not to load the final result, or it recurses  forever. Several hours of attempts have failed to resolve it, but I expect to have it fixed in the next couple days.

I've put up a precautionary message, and I will post here when it is fixed.

**Comment by dysbulic** [comment]
@ErinOCon, [mimisb.run](//mimisb.run) is functional once again, more or less. Despite implementing a limiter to control the rate at which resources are requested from `ipfs.dweb.link`, I am still getting HTTP 429 "too many requests" errors from the gateway.

Some images are still loading, but there are errors. The simple solution is to configure the system to a gateway instance running locally which generally isn't rate limited. Just click the gear icon on the right-hand side, and then select "use `localhost`" if you're running a local node.

**Comment by ErinOCon** [comment]
Hi @dysbulic, thank you for the provided updates. This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by dysbulic** [comment]
Ok, I'm late. I know that, but this program has been a larger mouthful than I was expecting when I agreed to bite it off. I think there's the potential for a really exciting piece of software, but it doesn't exist yet.

I *will* complete my report eventually.
