### ISSUE TITLE
Next Step Microgrant: DeFile

### ISSUE THREAD

**Issue by ctnava** [filecoin-project/devgrants#874]
### 1. What is your project? (max 100 words)

It is a boilerplate (decentralized) application that allows for easy and secure minting NFTs that act as keys to token-gated documents. Information considered sensitive will be encrypted, uploaded to IPFS, downloaded from IPFS, and decrypted via REST server, with secure keys stored in a NOSQL database. While identical documents may be processed by our backend, they will never result in the same CID because they will be bundled with randomly generated content before storage. Resulting NFT metadata will be a composite of OpenSea-compatible attributes and point to gated content.
```
tl;dr This is secure file storage in plain sight.
```

### 2. Project links
 
Link to Github repo: 
currently https://github.com/ctnava/raze.money
will make a new repository https://github.com/ctnava/defile-nfts

Link to video demo:
https://www.youtube.com/watch?v=P_LI7ZSdWO4
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

NFT metadata and encrypted, token-gated content will be stored on IPFS.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

I will extract the relevant source code from the raze.money (and by extension, deadDrop@hemlockStreet) into a standalone repository. From here, I will modify it to rely on a token gate for decryption instead of exclusively addresses and trim all unnecessary code (e.g. on-chain, encrypted context messages). The resulting boilerplate will be more general purpose and free from all monetization. On top of this, I will write documentation that I did not initially plan on because this specific piece of infrastructure was originally a solo project that I decided to implement on raze.money.

```
Anyone will be able to fork this repository, navigate the readme, create their own secure file-sharing web app, and instantiate their own NFT collection. 
```

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
https://ethglobal.com/showcase/raze-money-2qq4d
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
CyAaron Nava - cyaaron.tai.nava@gmail.com - ctnava - Full Stack
Ciaran Moore - cjm2391@gmail.com - ciciaran - UI/ UX
Antonio Maia - onioonio111@gmail.com - antonioonioflower - Product Manager 
Simon Oswald - contact@simonoswald.xyz - siosw - Frontend

* How did you learn about our microgrant program?
niki.gokani@protocol.ai
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  ETHGlobal HackFS
  * Please link to your hackathon submission
  https://ethglobal.com/showcase/raze-money-2qq4d

**Comment by ErinOCon** [comment]
Hi @ctnava, thank you for your proposal. Is this project open source?

**Comment by ctnava** [comment]
@ErinOCon yes, the described boilerplate will be open sourced

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by ctnava** [comment]
scope revision:

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

The resulting package will allow frontend clients to upload a file in chunks to a server, which will then encrypt and obfuscate it for storage on IPFS. After checking the result, the server will pin this CID on its own IPFS node instance so that it can hand it off to a third party later (like pinata or an FIL node). This package will also contain utilities for retrieving and decrypting stored assets.

```js
const { client, server } = require("defile-and-pin");
```

In the example code, users will be able to spin up a web3 frontend that will use a wallet to upload files them with signed messages. The rest server will store the CIDs & decryption keys; only releasing them to the user if they provide a valid signature. This keeps Web3 relevant, but does away with the smart contracts in order to minimize the amount of things that can go wrong.

I believe that if I do it this way, more people would use the code because it would be less annoying to import and the example would take less time to spin up. Originally, they would need to setup infura, mongodb atlas, and pinata accounts (which can cost money). Instead, I just want them to have to install dependencies & type `npm run start`.
