### ISSUE TITLE
Next step grant: Treenet

### ISSUE THREAD

**Issue by 41hulk** [filecoin-project/devgrants#875]
### 1. What is your project? (max 100 words)

Treenet is a decentralized app that rewards ordinary people for participating in reforestation, conservation efforts, and green initiatives using carbon offsets and carbon tokens. This project uses NFTs to tokenize and track the growing and monitoring of trees so we can help reward ordinary people for these NFTs through carbon offsets and carbon tokens

### 2. Project links
  
Link to Github repo: https://github.com/Treenets/Treenet-Frontend
Link to demo or website, if applicable: [Website](https://treenets.herokuapp.com/) - [Demo](https://youtu.be/DFL-_bXuAxQ)

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

NFT metadata and encrypted, token content will be stored on IPFS.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- [ ] Community Build. We'll be creating a community for the app and engaging people on different social media platforms and discord channels
- [ ] Modern UI. We'll be improving our UI to be more flexible and attractive for our user
- [ ] Deploy on mainnet. With a community and users, we need to provide a tangible app for them on the mainnet

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
https://ethglobal.com/showcase/treenet-b2s6u
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

**Kuzivakwashe Muvezwa
muvezwakuzivakwashe@yahoo.com
TheGodOfAwesome
Front-end**

**Ntare Guy
gntare2@gmail.com
41hulk
Back-end**

* How did you learn about our microgrant program?

Email/word of mouth

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  
   ETHGlobal HackFs2022

  * Please link to your hackathon submission
  
https://ethglobal.com/showcase/treenet-b2s6u

**Comment by ErinOCon** [comment]
Hi @41hulk, thank you for your proposal! Is this project open source?

**Comment by 41hulk** [comment]
Yes it's open source

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by 41hulk** [comment]
Hi @ErinOCon, I submitted a final Grant report for this microgrant. 

Hope it fits you well.

**Comment by ErinOCon** [comment]
Thank you!
