### ISSUE TITLE
Next Step Microgrant: vyomanaut

### ISSUE THREAD

**Issue by rajeevam3** [filecoin-project/devgrants#876]
### 1. What is your project? (max 100 words)
We are a web3 design studio taking ISRO to the metaverse and building an NFT card game. 
"VYOMANAUT" 
an NFT Phygital project officially licensed by ISRO!

which consists of
1. an NFT card game (Space Geek Cards)
2. First and only Official ISRO wristwatch
3. Comic series inspired by captain Vyom and related PFP
4. Vyom Station on Decentral land
5. Official Space tutor Educational VR museum for Indian Space History

We are the official merchandiser of ISRO-themed products
with licensing permission to make digital collectibles.

### 2. Project links
https://vyomanaut.io/
https://twitter.com/vyomanautnft

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Building an NFT card game 
using the feature of the mutability of web3.storage for dynamic nfts
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Will help us with better UI UX and also the full stack development part.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Definitely YES!
  
### 6. Does your proposal comply with our Community Code of Conduct?
YES

### 7. Links and submissions
NONE
  
### Additional questions:
- Rajeeva Mahalinga 
12 years of team building and development experience in fintech, full stack developer, and founder at MKTM studios 
- Sagar Vishwanath
Network engineer and DAO and Defi expert
- Sowjanya Prabhu
Engineer with extensive experience in operations, founder at MKTM studios 
- Sachin Arya 
3d blender and unity development expert
NID graduate 
- Oshal Ranade
3d blender and unity development expert
NID graduate 
- Mily 
3d blender and unity development expert
NID graduate 

* How did you learn about our microgrant program?
Piyush Maheshwari
https://twitter.com/hipiyushhere
is our technical sponsor from NFT.storage

* If your project was created as part of an event or hackathon:
  The project is created for ISRO - Indian Space Research Organization with licensing permission as a space tutor drive
  * Please link to your hackathon submission - isro.gov.in

**Comment by rajeevam3** [comment]
![1 (1)](https://user-images.githubusercontent.com/13529692/185114353-7ad2ebf0-1968-4901-8c66-df7e3c4b1485.jpeg)
![2 (1)](https://user-images.githubusercontent.com/13529692/185114366-17f77710-645f-49f3-9b51-59e83ba02ae5.jpeg)

https://user-images.githubusercontent.com/13529692/185114377-22d29a89-4084-4fea-9bb1-53a9627af973.mp4


https://user-images.githubusercontent.com/13529692/185114391-78bafe11-e17b-45e6-beaa-003d51f9116d.mp4

![PresentationNamasteyNFT1](https://user-images.githubusercontent.com/13529692/185114401-c07228ea-1581-4929-88cc-596140b33da9.jpeg)
![PresentationNamasteyNFT2 (1)](https://user-images.githubusercontent.com/13529692/185114405-a43da627-04bc-4792-b482-61c484932275.jpeg)
![PresentationNamasteyNFT2](https://user-images.githubusercontent.com/13529692/185114409-a891882d-6258-44ce-a7c5-cc6b33bb448b.jpeg)
![Sachin (1)](https://user-images.githubusercontent.com/13529692/185114410-ee0ce089-8352-4c17-9098-b601d89cd0e7.jpg)

https://user-images.githubusercontent.com/13529692/185114413-28598cde-2835-44d2-8569-e74d9b0c8430.mp4

[Vyomanaut Documentation (3).pdf](https://github.com/filecoin-project/devgrants/files/9359315/Vyomanaut.Documentation.3.pdf)
![watches](https://user-images.githubusercontent.com/13529692/185114440-5f19ed69-e611-4755-ad6f-0bf02d09552e.jpeg)

https://user-images.githubusercontent.com/13529692/185114457-3687ffd4-eb1a-4693-9e53-3a69859a4c01.mp4

**Comment by rajeevam3** [comment]
Our Vyomanaut NFT project got featured on NDTV.

https://youtu.be/cAPxupIJ1bw

**Comment by rajeevam3** [comment]
**Road Map 1.0**
- Finish building all the 3D blender models for the card game and NFTs (September)
- Marketing - Social Media and Discord setup and scaling (September)
- Trailer release and strategic partnership (September)
- Polygon and Filecoin collaboration (September)
- Finish the phase 1 implementation of the web app for the Space geek card game (October)
- Website app and Space Geek Card - Deck phase 1 drop (October)
- Merch (Clothing and accessories) drop for the community (October)
- ISRO official watch NFT drop and prototype production for the watch (November)
- ISRO official space tutor museum on Metaverse in collaboration with ISRO (December)
- ISRO watch 'Forging Pass' airdrop and NFT drops
- Finish phase 2 implementation for SGC game to launch and create the Vyomanauts on Eth main net (December)
- Vyom Cafe construction using unity (January)

**Comment by ErinOCon** [comment]
Hi @rajeevam3, thank you for your proposal. Do you have a project repo link available? Also, can you confirm if your project is open source?

**Comment by ErinOCon** [comment]
Hi @rajeevam3, I hope you are doing well! Do you have any updates or questions? For easy reference, here is our [open source policy](https://github.com/filecoin-project/devgrants/blob/master/open-source-policy.md) for our dev grants program.

**Comment by rajeevam3** [comment]
Hi @ErinOCon 
Greetings of the day 
Hope you are doing Great!

Yes it will be opensource: As this is a governmental project it will be open source.
Repo link is not available yet: We are yet to start the coding part at the moment we are working as a design studio to build the 3d elements and designs.

**Comment by rajeevam3** [comment]
The project is a part of marketing drive for ISRO - Indian research organization 

sorry for the tardy response.
Thank you very much!

**Comment by ErinOCon** [comment]
Hi @rajeevam3, thank you for your patience as we completed our review. This project looks really interesting! Unfortunately, it falls outside of our microgrants criteria. In case there is interest, here is [a link](https://ecosystem-wg.notion.site/Protocol-Labs-Accelerator-Program-d45d8792a7d544eca9beb7d3e3d3b05d) to the Protocol Labs Accelerator Program. The support opportunities described on this landing page may be a good fit for your team. 

Wishing you all the best with your project!
