### ISSUE TITLE
Next Step Microgrant: 🌿Meta Jungle Game🌿

### ISSUE THREAD

**Issue by TGS2016** [filecoin-project/devgrants#877]
### 1. What is your project? (max 100 words)

 Meta Jungle is metaverse open world game, where user can play, challenge each other, Buy NFT from in-game coins and create virtual world, they can also visit other user's virtual world. So now in-app items and achievements are not only statistic but it be used in game to create your own virtual world.
* We are using IPFS/Filecoin with NFT.Storage to store player's NFT metadata 

### 2. Project links
  
Link to Github repo: https://github.com/ThunderGameStudio/MetaJungle
Link to demo or website, if applicable: https://www.thundergamestudio.com/game/

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
- We are storing player's virtual world's NFT data on NFT. Storage which related to IPFS/Filecoin
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- We want to remove dependency of moralis sdk from current project and implement free blockchain communication to save cost of running this project live (Major concern to next step)
- Migrate user data from moralis database to firebase with authentication
- Implement in-app purchase to buy coins with smart contract (revenue model) 
- Update game coins, purchase mechanism and cost of NFT like real game

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: https://ethglobal.com/showcase/meta-jungle-7n6m0
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
 Jigar (Full Stack Developer) jigar@thundergamestudio.com Github : TGS2016
 Harsha (UI Designer) harsha@thundergamestudio.com Github : alexaport
 Mahesh (Backend developer) mlp@thundergamestudio.com

* How did you learn about our microgrant program?
 From protocol labs email

* If your project was created as part of an event or hackathon:
 Yes
  * What was the name of the event? 
  hackfs2022
  
  * Please link to your hackathon submission
   https://ethglobal.com/showcase/meta-jungle-7n6m0

**Comment by ErinOCon** [comment]
Hi @TGS2016, thank you for your proposal. Can you confirm if this project is open source?

**Comment by TGS2016** [comment]
@ErinOCon yes, license is already there in repo.
Thank you

**Comment by TGS2016** [comment]
@ErinOCon 
Link  : https://github.com/MetaJungleProject/MetaJungle/blob/main/LICENSE

**Comment by TGS2016** [comment]
Hi @ErinOCon , is there any update regarding approval ?
Thanks for your time

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by TGS2016** [comment]
@ErinOCon 
Thank you so much.
Will wait for email. !

**Comment by TGS2016** [comment]
Hi @ErinOCon ,
We have submitted report on the given link and updated repo.
Thank you so much for wonderful opportunity.
