### ISSUE TITLE
Next Step Microgrant: Decentralized Video Sharing Platform

### ISSUE THREAD

**Issue by 0xrandom0x** [filecoin-project/devgrants#878]
### 1. What is your project? (max 100 words)
We are building a decentralized short video sharing platform users can upload videos that they find very interesting or view videos uploaded by other users on the platform through web3.storage. At the same time, users can also appreciate the videos they like on the chain or perform LIKE operations. Content creators offer a great way to monetize, which in turn promotes premium video content and users share the fun videos they get every day

### 2. Project links
  
[Link to Github repo:]
https://github.com/0xrandom0x/dmovie
Link to demo or website, if applicable:]
https://m46ii-eyaaa-aaaad-qddpq-cai.ic.fleek.co/

YES, ALL is under MIT.
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
All video sharing on the platform will be based on IPFS/Filecoin, we use the very convenient web3.storage api to interact with users' data.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
1. Implement a Polygon-based contract system (content attribution, content viewers, praise, comments, and content appreciation funds)
2.  Implement Fil-based Appreciation feature
3.  Improve the video list playback and other functions

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes

### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  0xrandom0x , Decentralized developers active in web3, dedicated to bringing high-quality application resources to web3 users,[0xrandom0x@proton.me](mailto:0xrandom0x@proton.me)
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
