### ISSUE TITLE
Next Step Microgrant: <Your Title Here>

### ISSUE THREAD

**Issue by kalendula21k** [filecoin-project/devgrants#880]
### 1. What is your project? (max 100 words)

Identix.Space is a learn-to-earn quest service that helps Web3 newcomers to get hands-on experience of using blockchain products while creating and building up their own Digital reputation. We believe that the next billion Web3 users are still to come. Therefore, we focus on attracting, educating and engaging those people who wish to join Web3. We develop gamified scenarios (quests), each of which introduces the user to some knowledge of Web3. 

### 2. Project links
  
Link to Github repo: https://github.com/identix.space 
Link to demo or website: https://identix.space/

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
We would like to educate users on the topic of distributed storage and its importance in the context of Web3 usecases, e. g. NFTs, DAOs, etc. 

Identix.Space builds quests for ecosystems and its services, each of which introduces the user to some knowledge of Web3. Speaking about the very beginning of onboarding, as a rule, this is a some basic Web3 operations such as connecting a wallet, swapping tokens, staking and etc. The more the user learns, the more complicated the quests become and the greater the reward. Further, the division by subject areas (cryptocurrencies, NFTs, DAOs) may appear.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We want to develop a quest set that will onboard users to the Filecoin Ecosystem. The content will include tutorial guides, Loom video instructions, quizzes, interactive experience, onchain activity verification, rewards in tokens and NFTs and tasks on finding specific information. To succeed we need to build back-end part which includes includes interaction with the Filecoin ecosystem ( the developed backed-end code with the logics that will allow to verify transactions’ statuses; API that will interact with Filecoin blockchain; smart contracts (if necessary) to perform certain onchain transactions and checks. The back-end code will correspond to the CJM consisting of 4-7 quests) and UX/UI and Frontend Development for interacting with the users and their introduction to the blockchain (front-end code with user cabinet, quest map, and the possibility of interaction with  Filecoin ecosystrm; Web and Mobile apps with presented UX/UI design).

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, we are ready to provide community with grant reports.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
-
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
**Team Member #1:**
Full Name - Dmitriy Logunov, Lead Backend Developer
https://gitlab.com/dmitry.logunov / https://www.linkedin.com/in/dmitrii-logunov-b8623a173/ /

**Team Member #2:**
Full Name - Daniel Novichkov, Product Manager

https://www.linkedin.com/in/danielnovichkov/ / [danielnovichkov@gmail.com](mailto:danielnovichkov@gmail.com)  

**Team Member #3:**
Full Name - Yehor Churilov, Architect

https://gitlab.com/nivedano / https://www.linkedin.com/in/ychurilov

**Team Member #4:**
Full Name - Vyacheslav Zhuravlyov, Lead Blockchain Engineer

https://www.linkedin.com/in/uxname/ / https://gitlab.com/uxname / [uxname@gmail.com](mailto:uxname@gmail.com) 

**Team Member #5:**
Full Name - Julia Matsokina, Frontend Developer

https://gitlab.com/jkarik / https://www.linkedin.com/in/julia-matsokina/

**Team Member #7:**
Full Name - Shynkevich Maksim, Frontend developer

https://gitlab.com/odiinnn

**Team Member #8:**
Full Name - Alexey Vorobey, Co-founder

 https://www.linkedin.com/in/alexey-vorobey/ / [alexfialochka@gmail.com](mailto:alexfialochka@gmail.com) 

**Team Member #9:**
Full Name - Stepan Gershunu, Co-founder

https://www.linkedin.com/in/sgershuni/

* How did you learn about our microgrant program?
We’ve found out on the site https://www.kontour.io/grants/ .

**Comment by ErinOCon** [comment]
Hi @kalendula21k, thank you for your proposal! Can you provide a working repo link? Also, can you confirm if this project is open source?

**Comment by kalendula21k** [comment]
Hello!

Sure, https://github.com/identix-space - it's our repo link.
Identix Space is partially open source. We plan to create a Reputation
system for our quest platform. The SBT component with SSI element will be
general-purpose and open source.

The technical implementation generally includes:

   - *Infrastructure (smart contracts) for Soulbound tokens (SBT)*, which
   includes *S*BT contract for implementations on the Polygon network. Soul
   contract that allows laying the possibility of social recovery for the
   future, Collection contrac*t* for SBT issuers code for implementation
   Soul-based authentication and SBT import functionality.
   - *A module for transaction tracking.* This module will disclose our
   principles of transaction management and quest completion management.
   - *Quest content* which includes text, video, and quest conditions under
   CC license.


Thank you for replying!

Best,
Kristina from Identix

вт, 23 авг. 2022 г. в 13:14, ErinOCon ***@***.***>:

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
