### ISSUE TITLE
Next Step Microgrant: Polarys

### ISSUE THREAD

**Issue by SebPolarys** [filecoin-project/devgrants#884]
### 1. What is your project? (max 100 words)
With Polarys we aim to bring utility NFTs to everyday businesses. We are building the easiest Web3 onboarding suite for Web2 users, businesses & creators. We are building a suite made of 3 products built on Metis Andromeda :
1. A Multi-chain Minting Engine (live product)
2. A Marketplace
3. A Wallet

Users don’t need to have any code or crypto knowledge to onboard. Polarys focuses on utility NFT and provides an end-to-end solution.

### 2. Project links
  
Link to Github repo: 
https://github.com/orgs/PolarysDAC/repositories
https://github.com/PolarysDAC/polarys-nftstorage

Link to demo or website, if applicable:
www.polarys.ai (minting engine)
www.polarys.io (general website)

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
We used nft.storage api to upload Polayrs NFT images to IPFS and generate tokenURI.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We plan to use the grant to improve our unique, fully custom-made multi-chain minting engine. Our minting engine enables users to mint from Eth, BSC, Polygon, Avax, FTM, to Metis Andromeda, without having to bridge the funds.
With the grant, we will work on integrating 3 new key features to our minting engine:
* Build custom subgraph for multi-chain minting engine to improve performance and speed of the minting
* Add fiat onboarding to enable non-crypto native users to mint easily and thus enter web3
* Add Solana and Metis as new chains to mint from
* 
This will enable us to onboard non-crypto user on Web3, and in the longer term, allow for in real life purchases from users in businesses/stores that partner with us to trigger transactions on Metis chain without users knowing they are using it.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
- Max Hermans (max@polarys.io) CPO
- Hiroki Watanabe (@polarydev), Lead developer 
- Sebastien Van Hoof (sebastien@polarys.io), COO
- Selin Suntay (selin@polarys.io), CEO
* How did you learn about our microgrant program? HQ Han at Protocol labs (ex-BCG colleague of Sebastien Van Hoof)

**Comment by ErinOCon** [comment]
Hi @SebPolarys, thank you for your proposal! Can you confirm if this project is open source?

**Comment by SebPolarys** [comment]
Hi Erin,

No it is not open sourced.

Thanks
Sebastien 

__

Sebastien Van Hoof
Co-Founder
***@***.***
Whitepaper: https://www.polarys.io/ 
Twitter: @polarysDAC
Telegram: http://t.me/PolarysDAC 
Linkedin:/company/polarysnft

**Comment by SebPolarys** [comment]
Hi,

Any update on this?
Thanks

**Comment by ErinOCon** [comment]
Hi @SebPolarys, thank you for your reply! Supporting open source work is a key criteria point for our microgrants program. Will this project transition to open source in the future?

**Comment by ErinOCon** [comment]
Hi @SebPolarys, thank you for the update. Once your project has reached the point of open source work, please let us know! Wishing you all the best with your project!
