### ISSUE TITLE
Next Step Microgrant: pixel4te

### ISSUE THREAD

**Issue by en0c-026** [filecoin-project/devgrants#885]
### 1. What is your project? (max 100 words)
Convert your image to NFT pixel art!
Apply a color palette between 100 available or grayscale.
draw pixel by pixel,  resize to output image, upload it to the IPFS decentralized service. 

### 2. Project links
  
Link to Github repo: https://github.com/en0c-026/pixel4te
Link to demo or website, if applicable: https://pixel4te.vercel.app/

  The projects is open source under the MIT License . See [here](https://github.com/en0c-026/pixel4te/blob/master/LICENSE.md)

### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
pixel4te uses the IPFS decentralized storage service, through NFT.Storage.
The artist can upload their pixel art to IPFS with the click of a button.
Soon with the improvement and completion of the project it will be used to store the metadata of each NFT pixel art.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Below is the roadmap with pending tasks, to be carried out in the next three months
### pixel4te Editor
- [x] convert an image into pixels with different blocksize and draw pixel to pixel
- [x] choose 1 from 100 available color palettes or apply a grayscale
- [x] resize output image size
- [x] download your image to your device
- [x] upload your image to the IPFS decentralized service
- [ ] share your pixel art on your social networks

### pixel4te NFT
- [ ] connect your account from the browser wallet
- [ ] stores the NFT metadata in the IPFS decentralized service
- [ ] record NFT metadata in pixel4te API and gets its ID
- [ ] mint a new NFT in the pixel4te Collection
- [ ] list and sell your nft en pixel4te Marketplace
- [ ] set your NFT royalties and earn profit on every transfer

### project features
- [ ] own Infura IPFS gateway
- [ ] buy custom domain
- [ ] SEO optimization
- [ ] Discord community

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  Yes.
### 6. Does your proposal comply with our Community Code of Conduct?

Yes. I agree
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Name: Lucas Jovanovich
* Email: bitup.games@gmail.com
* Github: en0c-026
* Role: Founder and Developer
* How did you learn about our microgrant program?
* Explore ipfs repositories
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
