### ISSUE TITLE
Next Step Microgrant: DecentralizedWiki

### ISSUE THREAD

**Issue by QuantumSqrl** [filecoin-project/devgrants#887]
### 1. What is your project? (max 100 words)
This is a wiki built on IPFS/Filecoin. The goal is to engineer a **fully functional decentralized wiki that anybody can use to create their own wiki project.** To achieve this, we are building a wiki focused on explaining technologies (called WikiTechTree). This will act as an example of a modern decentralized wiki, and the codebase/docs will allow for anyone to create their own. Additionally, there are many existing wikis that could benefit from the decentralization/censorship resistance offered by Filecoin, but there are no existing examples or references of how to build a full wiki using Filecoin.

### 2. Project links
  
Link to Github repo: [github.com/quantumsqrl/decentralizedwiki](https://github.com/QuantumSqrl/DecentralizedWiki)
Link to working prototype: [wikitechtree.com](https://wikitechtree.com)
_Note: The code for this project is open source under an MIT License and always will be._

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

The data for each wiki article is saved on IPFS with storage then incentivized via Filecoin. We use web3.storage to enable this, and plan to use Lighthouse to ensure permanent storage. The crux of the project is to use this decentralized storage stack to enable a next-generation wiki platform — thus all text, images, etc for each article, and all past/future edits, are saved on Filecoin. 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

What we have right now is a working decentralized wiki built on IPFS/Filecoin. To really become useful and widely adopted as a platform and as a codebase for people to both develop decentralized wikis and port centralized wikis over to Filecoin with, we need to take a few more steps:

- Store edit history (CIDs of past edits), with information about each one
- Allow for Filecoin storage to be permanent using Lighthouse
- Allow for creation of new articles
- Allow for multiple individual sections per article
- Integrate user accounts and permissions
- Improve user interface
- Security testing: web app pentest + dynamic code analysis
- Do customer discovery: talk to potential users and ensure what we are building is in line with what is needed
- Create thorough documentation so people with no technical experience can create a wiki using this codebase

This is the minimum of what will be accomplished under the scope of this grant. If you have requests for other objectives to include in this development period, please let me know.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

This project began independently, but may be submitted to a hackathon in the future if it fits the scope.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Quantum Squirrel // quantumsqrl@proton.me // https://github.com/quantumsqrl // Founder, Developer

* How did you learn about our microgrant program?

I've known about IPFS and Filecoin for a while due to an interest in decentralized file storage technologies, and I discovered this microgrant program when researching potential funding sources that could allow me to take the next steps for this project.

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @QuantumSqrl, I hope you are doing well! Can you submit your final report using the provided link?
