### ISSUE TITLE
Next Step Microgrant: <Cluster3>

### ISSUE THREAD

**Issue by ghaniape** [filecoin-project/devgrants#888]
### 1. What is your project? (max 100 words)
Cluster3—— a tool for web3 community that establishes the physical organization relationship of the community through Membership NFT, and saves the membership (Membership NFT) data in the Filecoin network,and has more community tools such as the issuance of medals.All the NFTs are storage via Web3.storage.

### 2. Project links
  
Link to Github repo:https://github.com/cluster3labs/cluster3-sol 
Link to demo or website, if applicable:   https://home.cluster3.me/

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
All NFTs resources in the project use Web3.storage to exist on the Filecoin network.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1.We will provide more practical support for the richness of community tools;
2.We will organize activities with popular DAO communities to attract users to participate in the experience;
3.We will try to implement the community membership protocol standard on filecoin. Next, we will store more community data on Filecoin and try to do some community data retrieval related functions.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

agree
  
### 6. Does your proposal comply with our Community Code of Conduct?

fits the rules of Code of Conduct

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://github.com/wanxiang-blockchain/2022-Wanxiang-Blockchain-Spring-Hackthon-cluster3

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
zlext whee@zlext.com  backend engineer
showzyl  showzyl520@gmail.com https://github.com/showzyl   Front-end engineer

* How did you learn about our microgrant program?
wanxiang-blockchain

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
2022 Wanxiang Blockchain Spring Hackthon

  * Please link to your hackathon submission
  https://github.com/wanxiang-blockchain/2022-Wanxiang-Blockchain-Spring-Hackthon-cluster3

**Comment by ErinOCon** [comment]
Hi @ghaniape, thank you for your proposal! Is this project open source?

**Comment by ErinOCon** [comment]
Hi @ghaniape, I hope you are doing well! Do you have any updates or questions?

**Comment by ErinOCon** [comment]
Hi @ghaniape, do you expect to have an update available this week?

**Comment by ErinOCon** [comment]
Hi @ghaniape, this item has been closed. Please feel welcome to reapply at any time!

**Comment by ghaniape** [comment]
hi ErinOCon ,

I'm here to answer all your questions.
Is this project open source?of course yes, our github link ：https://github.com/https://github.com/cluster3labs/rank-sol.git

We've made a lot of progress recently, the team upgraded our products and rebranded.Now Cluster3 is the #1 source for Community Contributors.Aggregating both on-chain and off-chain data, Cluster3 serves as community achievement system for contributors.

Official link：https://rank.cluster3.net/
Twitter：https://twitter.com/cluster3me
Discord：https://discord.gg/Vqkmmknp5p

### What is Cluster3 now

With the development of Web3, a variety of NFT types are used based on different scenarios.Therefore, the data is scattered everywhere.The Cluster3 team found that if the scattered data can be integrated and made into dynamic NFT representing user portraits, it will be a huge treasure.

We integrate on-chain data credentials and off-chain behavior data(e.g. POAP/OATs, ERC-20 token,Voting data, behavioral label data, etc.）,and build a comprehensive user profile, to present externally in the form of dynamic NFT, so that the project party can intuitively understand the users, allowing users to trace back their contributions.

After months of development ,Cluster3 has now covered 1200+ communities, collated and calculated the data credentials of 1.2 million user addresses and helped these users calculate their contribution score and ranking to each community.

### What's next for Cluster3

1. Enrich the user portrait data of cluster3, consider introducing more user data certificates to enrich the user image, and make our contribution score more accurate.
2. Establish a community achievement system based on users' on-chain and off-chain behavioral data credentials.
3. Sort user Data Credentials,and based on the calculated user's contribution score in the community, and produce more user analysis models for different project parties.
