### ISSUE TITLE
Next Step Microgrant: CORTX Drive (CORTX and Filecoin Integration Challenge 2022 Entry)

### ISSUE THREAD

**Issue by kurosouza** [filecoin-project/devgrants#889]
### 1. What is your project? (max 100 words)
CORTX Drive is a web-based file management and migration tool designed to help users move their data from any S3-compatible file storage service to IPFS / Filecoin. It is built using Java and it currently integrates with Seagate's massively scalable object storage technology stack - CORTX. It can quite easily be configured to work with any S3-compatible object storage interface or service.

### 2. Project links
Github
[https://github.com/kurosouza/cortx-drive](https://github.com/kurosouza/cortx-drive)

Youtube Demo Video
[https://youtu.be/3ZVRK8s75SY](https://youtu.be/3ZVRK8s75SY)
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
CORTX Drive allows users to send files to IPFS in two ways:
1. A user can run their own IPFS node by using the preconfigured docker image bundled in the docker-compose file within the source repository. This scenario allows the user to quickly work with CORTX Drive and IPFS by just running the **docker-compose up** command
2. They can use an external IPFS endpoint or gateway by supplying the necessary IPFS endpoint URLs when they run the application
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
If my grant is approved, I plan to 
1. Improve the app's User Interface
2. Add a Search feature
3. Deploy it to AWS so that users can access it online
4. Publish and maintain the Java-IPFS Connector because the only Java-based IPFS client I could find online is outdated and no longer maintained.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
CORTX & Filecoin Integration Challenge 2022 (Devpost)
https://devpost.com/software/cortx-drive
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
	* Kuro Souza, kurosouza@gmail.com, https://github.com/kurosouza, Software Developer
* How did you learn about our microgrant program?
	* I received an email from Niki Gokani niki.gokani[at]protocol.ai informing me about the grant 
* If your project was created as part of an event or hackathon:
	  * CORTX & Filecoin Integration Challenge 2022 (Devpost)
* Please link to your hackathon submission
	* https://devpost.com/software/cortx-drive

**Comment by ErinOCon** [comment]
Hi @kurosouza, thank you for your proposal! Is this project open source?

**Comment by kurosouza** [comment]
Yes it is. The project and all its components will be released under the MIT license.

**Comment by kurosouza** [comment]
https://github.com/kurosouza/cortx-drive/blob/main/license.txt

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
