### ISSUE TITLE
Open Grant Proposal: Pin Save

### ISSUE THREAD

**Issue by GregTrifan** [filecoin-project/devgrants#890]
# Open Grant Proposal: Pin Save

**Name of Project: Pin Save**

**Proposal Category:** `app-dev`

**Proposer:** `GregTrifan`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** `Yes`

# Project Description

![https://bafkreifqwdvyov3mibrjm44adli7srsyo4b75fffqgydec7bkmb64w2ld4.ipfs.nftstorage.link/](https://bafkreifqwdvyov3mibrjm44adli7srsyo4b75fffqgydec7bkmb64w2ld4.ipfs.nftstorage.link/)

Pin Save is a decentralized image sharing and content aggregation platform where users can not only control the content, but also the platform itself.

**Problem**

Currently monolithic web applications retain ownership of user content and stifle the adoption of decentralized technology.

A user could use OpenSea to publish the content, however the obstacles are significant:

- Only a very small fraction of collections get to the homepage.
- The content publishing process requires confidence and experience in web3.
- Feedback and engagement metrics related to content are reflected mostly in price movement.

In addition, there is a lack of an alternative platform in Filecoin ecosystem to provide users with an ability to create, share, moderate and discuss decentralized posts.

**Solution**

Our team advocates implementation of decentralized image sharing and content aggregation platform where users can not only control the content, but also the platform itself.

![https://bafkreiccw66l45pdgonsazc5u3xwphi5s2cji2zl55lyizwtwtsy3xlk4i.ipfs.nftstorage.link/](https://bafkreiccw66l45pdgonsazc5u3xwphi5s2cji2zl55lyizwtwtsy3xlk4i.ipfs.nftstorage.link/)

## Value

We have already implemented a prototype both on [NEAR VM with Rust](https://pinsave.app/) and [EVM version on Polygon](https://evm.pinsave.app/).
The decentralized storage provider that we have implemented is NFT.storage. Besides, we have just contacted Estuary and received api key to implement decentralized storage provider, which compared to Web3.storage and nft.storage, provides unlimited upload file size and does not use Amazon S3.

The combination of decentralized storage, smart contracts and creator ownership of intellectual property creates new dynamics between content creators and forms new more meaningful communities.

PinSave assists in lowering the threshold for users to enter the Filecoin network, provides incentives to share content and effectively improves the adoption of the Filecoin.

*Potential Risk: Offensive Content*

However, the application operator can control what is distributed on the front end. We also believe that the community-led content moderation is the best system.

## Deliverables

Convenient for users, secure, unstoppable and censorship resistant Content Sharing platform.

1. Create more intuitive post upload page.
2. Enable creation of multiple posts.
3. Integrate on-chain reputation profile: ERC 725, to enable decentralized community feed moderation.

## Development Roadmap

Milestone 1: Design phase

2-3 week: USD$5000

- Feed, post, profile and upload pages interface design
- Server-side data modeling

Milestone 2: Smart contracts 

2-3 month: USD$15000

- Create, test and connect ERC-1155 contract to enable multiple NFTs of the same properties to be minted
- Create, test and connect ERC-725 contract to implement decentralized reputation system

Milestone 3: Developer Integration and Adoption

1-2 month: USD$10000

- NFT creation connection with contract module
- Decentralized Identity module
- Integrate estuary to facilitate more decentralized storage

## Total Budget Requested

USD$30000

## Maintenance and Upgrade Plans

We will maintain the project: fix related bugs and actively integrate Filecoin Virtual Machine

# Team

## Team Members

Pavel Fedotov 

LinkedIn: [https://www.linkedin.com/in/pavel-fedotov-pinsave/](https://www.linkedin.com/in/pavel-fedotov-pinsave/)

Twitter: [https://twitter.com/pfedprog](https://twitter.com/pfedprog)

GitHub: [https://github.com/Pfed-prog/](https://github.com/Pfed-prog/)

Grigore Gabriel Trifan

LinkedIn: [https://www.linkedin.com/in/grigore-trifan-666biyz/](https://www.linkedin.com/in/grigore-trifan-666biyz/)

Twitter: [https://twitter.com/grigore_trifan](https://twitter.com/grigore_trifan)

GitHub: [https://github.com/GregTrifan](https://github.com/GregTrifan)

## ****Team Website****

[https://dspyt.com](https://dspyt.com)

[https://github.com/dspytdao/](https://github.com/dspytdao/)

## Relevant Experience

As a team we have completed Gitcoin bounty project for Uniswap: ([https://github.com/dspytdao/dspytai](https://github.com/dspytdao/dspytai)), Algorand ([https://developer.algorand.org/solutions/artificial-intelligence-on-algorand/](https://developer.algorand.org/solutions/artificial-intelligence-on-algorand/)) and won 3rd prize for DeFi Algorand Encode track [https://medium.com/encode-club/encode-x-algorand-hackathon-prizewinners-and-summary-286fc4beea38](https://medium.com/encode-club/encode-x-algorand-hackathon-prizewinners-and-summary-286fc4beea38) building complex smart contracts, among others.

In addition, we have completed Encode and Filecoin Accelerator building a very first prototype for Pin Save. 

We have significant experience in Blockchain and Smart Contract development. Our key Skills include:

- Javascript, TypeScript, NextJS, React.js,
- Solidity, Rust, Python

## Team code repositories

Initial Codebase built during Filecoin Accelerator with [nft.storage](http://nft.storage) https://github.com/dspytdao/Pinsave

EVM version: https://github.com/dspytdao/PinSave-EVM

**Comment by ErinOCon** [comment]
HI @GregTrifan, thank you for your proposal. This grant has been approved! Can you provide an email address to discuss next steps?

**Comment by GregTrifan** [comment]
Sure, trifangaby71@protonmail.com

**Comment by ErinOCon** [comment]
Thank you, @GregTrifan!
