### ISSUE TITLE
Next Step Microgrant: Nstocks the NFT stocks marketplace

### ISSUE THREAD

**Issue by abrahamfai** [filecoin-project/devgrants#893]
### 1. What is your project? (max 100 words)
NStocks are NFTs that will be traded in the stock exchange in the long term. In the short term, members of our community are given placements that give them access to the NFTs. Members can freely trade their placements within the community under strictly monitored regulations. Those that are allowed access into the community are also given the right to drop exclusive NFTs that will be traded within the community. This right is reserved for those who rank high in the placement chain of the community. A member's ranking is determined by some criteria and determines the number of shares owned by such individual. This serves as private placement and its value will be recognised when the NFTs eventually go public.

### 2. Project links
  
Link to Github repo: https://github.com/abrahamfai/nnstocks
Link to demo or website, if applicable:

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
This project will use IPFS to make sure all our stock NFTs are decentralized and always accessible. making IPFS our default storage solution in our ecosystem
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We have completed the initial stage of the development of the NFTs and the vision to be shared by would-be members of the community.
The next stage is to carry out aggressive and targeted marketing for four months straight concentrating mainly on influencer marketing, paid ads on social media, and giving of little bonuses as incentives . With this grant, we can also employ much needed staff to manage our online presence  and collect data within the 4-month period. This grant will also help to pay for electronic media advertisement to boost our publicity and visibility.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

yes of course we must
  
### 6. Does your proposal comply with our Community Code of Conduct?

sure

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://github.com/abrahamfai/nnstocks
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Abraham Faithful Founder   https://github.com/abrahamfai
* How did you learn about our microgrant program?
while researching on a hackathon
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @abrahamfai, thank you for your proposal. Is this project open soure?

**Comment by abrahamfai** [comment]
Yes it is

**Comment by ErinOCon** [comment]
Hi @abrahamfai, thank you for your patience with our review. Before considering this project for a microgrant, a working prototype is required. Do you have a working demo that showcases the progress of your prototype and the user experience? If this is still in development, we would recommend participating in a hackathon as a next step!

**Comment by ErinOCon** [comment]
Hi @abrahamfai, I hope you are doing well! Do you have any updates or questions?

**Comment by ErinOCon** [comment]
Hi @abrahamfai, this item has been closed. If more information becomes available, please feel welcome to re-open the item.
