### ISSUE TITLE
Open Grant & Green Grant Proposals: SaaS Platform to Analyze a Product’s Climate Impact

### ISSUE THREAD

**Issue by DarkBlue2021** [filecoin-project/devgrants#894]
# Open Grant & Green Grant Proposals

**Name of Project:** SaaS Platform to Analyze a Product’s Climate Impact

**Proposal Category:**  `app-dev`, `green` 

**Proposer:** ` DarkBlue2021`

**(Optional) Technical Sponsor:** Jenks Guo  (jenks-guo-filecoin)

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** "Yes"

# Project Description

Closing the loop is the imperative behind the circular economy. To achieve this goal, tracking the entire lifecycle of a product is essential, and blockchain can be a valuable tool.  In fact, traceability-from materials sourcing, production, consumption, and end-of-life management-is the first step in ensuring material recovery, reuse, and recycling, avoiding waste, and proper disposal. 

We are planning to build a Software-as-a-Service (SaaS) with BaaS (Blockchain-as-a-Service) supported platform to create a digital product ID for a physical product. The digital product ID can be used to analyze and report a product’s climate impact, across the product’s full lifecycle, from manufacturing to consumption, and from reuse to disposal.

The integrated SaaS and BaaS platform uses IPFS/Filecoin to store a product’s specific information and will be able to display evidence-based climate-impact reports, based on analytics of the data.

We are focusing on opportunities and challenges in the circular economy and regenerative finance industries, and solutions to address issues in climate change. Climate change is one of the most pressing issues facing humanity today. To meet the Net Zero targets by 2030, there must be ways to record and report a product’s climate impact, so that brands and manufacturers have to do the right things to protect the environment. A recent report from IPCC (an UN agency) proved that “having the right policies, infrastructure and technology in place to enable changes to our lifestyles and behavior can result in a 40-70% reduction in greenhouse gas emissions by 2050" (https://www.ipcc.ch/2022/04/04/ipcc-ar6-wgiii-pressrelease/).

We would like to build a SaaS platform to create a digital product ID for a physical product (created by manufacturers or brands). The digital product ID can be used to record the product’s climate impact data, based on analytics of its full lifecycle. This will allow brands and manufacturers not only to store the data, but also to use the data for analytics - even for compliance reporting. The critical insights from the platform will provide evidence-based data for key stakeholders, including the general public, to understand the climate and sustainability practices of the brands and manufacturers. In our long-term vision, the platform can also provide incentives of decentralized storage, by sharing and monetizing valuable product-specific data with stakeholders.

A user case could be the following: In the textile and apparel sector,one of the most environmentally impactful, responsible for 10 percent of global CO2 emissions and 20 percent of global water waste. We are developingg a product which will have a worldwide impact and whose model will be replicable in many other sectors. 

We are looking to use Web3.storage or Estuary.tech for integration with Filecoin.

## Value

We believe the proposal is valuable for the Filecoin ecosystem, because it will further strengthen Filecoin’s mission to create a decentralized, efficient, and robust foundation for humanity’s information.  We believe Filecoin can provide the ideal decentralized storage layer to enable climate impact data to be trusted, recorded and stored for manufacturers and brands. IPFS gives the stored files immutability and Fielcoin persists the files on the permanent web for future reference.

Currently, a product’s climate impact is not well recorded by any stakeholder. There also tend to be conflicts of interest for brands and manufacturers to release their climate impact data by themselves, raising concerns for “green-washing” practices. Without the transparent and verifiable data, there will be a lack of incentives to ensure “responsible production and consumption” (UN Sustainable Development Goals, No. 12).

Potential risks that may make executing on this project difficult include:
1. Data privacy: Different countries have different legislations on data to be collected and stored. To address this risk, the proposal will not record any private or sensitive data.
2. Technology integration: Integration with IPFS/Filecoin from external systems requires proper architecture design. We will be working with Filecoin experts to engineer the solutions.
3. Applications: Without real-world application, the proposal may bring little to address climate change issues. We are collaborating with business partners to pilot the platform.

## Deliverables

The final deliverable of this project will be a SaaS Platform to report a product’s climate impact, based on analytics of the data stored on IPFS and Filecoin. The main deliverables include:

D1. SaaS Platform – to provide users interfaces on an online portal, with the following features:
D1.1 To allow users to create a product ID from an online portal
D1.2 To update a product’s status (e.g. from consumed to recycled), which will be recorded on IPFS storage
D1.3 To analyze and report on a product’s climate impact, based on data recorded on IPFS storage
D1.4 To store a product’s climate impact to Filecoin as long-term storage

D2. BaaS Platform – to provide Smart Contract Sidechain as part of users journey experiences on an online portal, with the following features:
D2.1 Self Sovereign Identity Smart Contract to ensure customer experiences journey in shared information as part circular economy
D2.2 To Explore-Aware-Reviewed-Enjoyed-Earned Journey Experiences Smart Contract
D2.3 Reward and Point Generated Smart Contract
D2.4 Validation and Audited Smart Contract to maintain trust, transparent, and reliability of the application

D3. IPFS Integration – to integrate SaaS platform with Web3.storage/Estuary.tech, with the following features:
D3.1 To create a unique product ID on IPFS, when the product is first created
D3.2 To upgrade a product’s status and record on IPFS, triggered from the SaaS platform
D3.3 To analyze the product’s climate impact, triggered from the SaaS platform
D3.4 To integrate IPFS with SaaS platform

## Development Roadmap

Our aim to deliver the project in three major milestones:

M1. SaaS - BaaS Platform Design & Development
The team will build a SaaS - BaaS platform (D1-D2), , to provide users interfaces on an online portal for this milestone (M1):
M1.1 To allow users to record a product ID from an online portal
M1.2 To update a product’s status (e.g. from consumed to recycled), which will be recorded on IPFS storage
M1.3 To analyze and report on a product’s climate impact, based on data recorded on IPFS storage
M1.4 To store a product’s climate impact to Filecoin as long-term storage
To achieve this milestone, we estimated: 
Funding: U$30,000
Duration: 2 Months

M2. SaaS System Integration & Testing
The team will deliver the IPFS (D2) and Filecoin (D3) integration with the SaaS platform, for this milestone (M2).
To deliver IPFS Integration (D2), the following features will be developed and tested:  
M2.1 To create a unique product ID on IPFS, when the product is first created
M2.2 To upgrade a product’s status and record on IPFS, triggered from the SaaS platform
M2.3 To analyze the product’s climate impact, triggered from the SaaS platform
M2.4 To integrate IPFS with SaaS platform
M2.5 To test and verify the IPFS integration
CID of documents will be written on chain
To achieve this milestone (M2.1 - M2.5), we estimated: 
Funding: U$30,000
Duration: 2 Months

## Total Budget Requested

We estimate the total requested budget would be U$60,000, as shown in the breakdown in Section 5.

## Maintenance and Upgrade Plans

We are on a mission to accelerate the transition to a circular economy and will remain fully committed to supporting the maintenance and upgrade of the project in the funded support period (2 years after receiving the funding). After the funded support period, We aim to continue the support to the best of our effort.

Maintenance Plans: we will maintain the SaaS platform and will fix any issues (including issues reported by communities).
Upgrade Plans: we will provide support for upgrades to the SaaS platform, including integration to IPFS and Filecoin, where there is a need for major system upgrade.

# Team

## Team Members

We have a strong technology and advisor team in this project. 

**Technology** 

(Bob) Weihai He. Bob is the lead software/systems engineer for this project. He is an European Engineer (EUR ING), with Chartered (UK Royal) status in Engineering (CEng), Science (CSci), and IT (CITP), an MSc graduate with Distinctions in Software Engineering from Oxford University, and alumnus of ConsenSys Academy and Encode Club. He is currently studying a dual Masters in Global Blockchain Technologies with Zigurat Global Institute of Technology and IL3-Universitat de Barcelona. 

Ciro Gargiulo.  Ciro is the business and financial lead of this project. He is an investment controller with a MSc in Economics and Finance and wide background experience in the Financial sector. Based in Luxembourg since 5 years, Ciro has a dynamic and holistic view of the overall Investment scene worldwide with working experience in Investment Fund and Big4. Ciro gained experience in the blockchain world stating from 2016 with an Internship subject-related and he completed his studies with a quantitative analysis of the crypto-market volatility. He is currently studying a dual Masters in Global Blockchain Technologies with Zigurat Global Institute of Technology and IL3-Universitat de Barcelona. 

Sonny Dhamayana. Sonny as Blockchain Technology Architect & Developer. He graduated in Industrial Technology, and received his 3 (three) Post Graduate Program in Artificial Intelligence & Deep Learning, Cloud Computing, and Digital Marketing from Manipal University India. He received Certified Diploma in Blockchain Technology Development from University of Dubai, and currently he pursuing further education a dual Masters in Global Blockchain Technologies with Zigurat Global Institute of Technology and IL3-Universitat de Barcelona. Most of the transition of his career and exposure in advanced industrial automation including digital transformation which involving Artificial Intelligence through Deep Neural Network and Blockchain Technology.

Jelena Gjorgjev. Jelena is a software full-stack and blockchain developer. She graduated and post graduated in Software development in Macedonia and she is pursuing further education with a dual Masters in Global Blockchain Technologies with Zigurat Global Institute of Technology and IL3-Universitat de Barcelona. Most of her career she was lead full-stack developer or CTO of few successful projects/companies and has great experience in both developing and managing projects.

**Advisors** 

Robin Weninger. Robin is the Managing Director of the Global Institute of Leadership and Technology (GILT), an educational company with the goal of putting education at the heart of every organization in order to cope with an evermore complex and uncertain world.  Robin is the Initiator of the Global Blockchain Initiative (GBI), an Advisory Board Member at Zigurat Innovation and Technology Business School and lecturing at the Frankfurt School of Finance & Management, the University of Barcelona, and the EU Business School, Geneva. Robin has been a member of the advisory board of several EU-funded innovation projects under the H2020 framework. The World Economic Forum recognized Robin as a Global Shaper in 2015 and as a European Digital Leader in 2017.

Laurent Strauss. Laurent is a Chief Cybersecurity Strategist at Micro Focus with great passion for emerging Trends and Technologies. He spent over 20 Years across multiple areas of the IT Industry ranging from Archiving, Backup, Virtualization, Cloud and Cyber Security. He is also part of a faculty board lecturing Blockchain Security and a founding member of the Global Blockchain Initiative and Crypto Community Switzerland. 

Ciro Vivacqua. Ciro is an experienced Enterprise Architect with a unique combination of deep technical knowledge, business acumen, and strong technical leadership and project experience with software ecosystem, cloud technologies, big data, blockchain, and frameworks in structured and fast growth organizations from diverse sizes and industries. He brings to the project 20 years of experience in the design of business critical solutions.

## Team Member LinkedIn Profiles

Our LinkedIn profiles include: 

(Bob) Weihai He: https://www.linkedin.com/in/bob-weihai-he/
Ciro Gargiulo: https://www.linkedin.com/in/ciro-gargiulo-06ab4074/
Sonny Dhamayana: https://www.linkedin.com/in/sonny-dhamayana-62b30810
Jelena Gjorgjev: https://www.linkedin.com/in/1nf3rn0/
Robin Weninger:https://www.linkedin.com/in/robinweninger/
Ciro Vivacqua: https://www.linkedin.com/in/cirovivacqua/
Laurent Strauss: https://www.linkedin.com/in/strausslaurent/

## Team Website

We will maintain the team website on Github. 

## Relevant Experience

We have strong domain expertise in software/solution engineering and architecture for mission critical large-scale systems, as well as FinTech, IoT and blockchain. We have conducted a large number of in-depth interviews with key stakeholders and experts, and have found the strong interests in circular economy, though they are not fully aware of the full potentials from the business model or technology innovation. 

## Team code repositories
This is our first team project on Github.

# Additional Information

Filecoin / IPFS.

[Weihai.he@hotmail.com](mailto:Weihai.he@hotmail.com)

The project's idea has been developed from the team's global accelerator and government climate programmes, including Startupbootcamp (EnergyInc 2021) and ClimateLaunchpad / Climate-KIC (2022) – Australian/EU government climate innovation programs.

**Comment by DarkBlue2021** [comment]
We would like to thank Jenks @jenks-guo-filecoin as our technical sponsor !

**Comment by redransil** [comment]
Hey folks! Sorry about the super long response time. This looks like a very interesting project with well aligned motivation, tech roadmap, and a strong team.

Please help me understand the go-to-market strategy. I get that the tracking can be applied across basically any industry, but which industry are you targeting first and why? Do you know people in that industry? What problem do they need solved? And can we get more details on what the real-world example in M3 will be?

**Comment by DarkBlue2021** [comment]
Hi Alan, many thanks for the updates! We are passionate about sustainability, especially how emerging technologies like blockchain would help to address climate change, which is one of the most pressing challenges facing humanity today. Following extensive customer interviews and industry research (especially with the help from Climate-KIC, the EU’s Climate Innovation program), we would like to focus on high pollution and high carbon impact industries as our beachhead market. We have access to customers who would be interested in piloting the platform, once it is ready. Some potential customers include: (1) Infant formula products – tracking product safety, and proof of climate impact to users (2) Clothes – prompting circularity of the clothes in marketplace (e.g. reuse, resold etc) (3) Computers – tracking the product usage and maintenance history for corporate users. There are other potential applications, and many innovative ways for positive climate impact – at product levels. We would like to apply for the grant to collaborate with the customers/users to co-create the solution. Hence, we have included M3. We would love to have a chat, if necessary. If you have any question, please let us know ! Regards, Bob and the Team.

**Comment by DarkBlue2021** [comment]
Hi Filecoin team, we has made progress in the past weeks. We have started the design and building process ourselves – we do request Filecoin/IPFS team’s support to make the project a success in the real world (rather than some random code on a developer’s computer). We have reduced the scope of work, and would appreciate the final decision from Filecoin as soon as possible. Thank you.

**Comment by orinayodele** [comment]
Hi @DarkBlue2021 we are finalizing all the grant decisions next week, and you will get back in touch with you next week

**Comment by DarkBlue2021** [comment]
Hi Filecoin team, it has certainly been a pleasure to explore collaboration opportunities with you all in the past months. We logged the grant request on 19 August 2022, and have been waiting for further responses since then. Our mission is to develop technologies that can be used in the real-world, and to deliver impact as much as we can. Everyday in the startup world counts. If Filecoin is not moving forward our grant application, I would appreciate if you could advise us as soon as you can, so we can move on to other solution that can help us to achieve our mission. All the best, and thank you.  @realChainLife @redransil @orinayodele

**Comment by orinayodele** [comment]
Hi @DarkBlue2021!


Sorry for the delay in sending over the contracts, we were finalizing a few things in the past few weeks. You should receive your contract by end of this week or early next week.

**Comment by realChainLife** [comment]
Hi @DarkBlue2021 Thanks for your patience here. We've shared an email with detailed next steps, we look forward to supporting you through the kick-off process.
