### ISSUE TITLE
Next Step Microgrant: BlockMail

### ISSUE THREAD

**Issue by franfran20** [filecoin-project/devgrants#896]
### 1. What is your project? 
BlockMail is an email decentralized application. BlockMail enables users to send mails across the decentralized web ensuring security, privacy and giving full control to the user of how they wish to manage their emails. BlockMail solves most of the problems facing emails today including phishing, spams etc.

BlockMail uses decentralized technology and on chain encryption in order to provide the most secure, noise free and private email environment, ensuring mails are stored forever using decentralized storage technology like IPFS.

BlockMail also doesn't limit you to just messages but brings on the concept of monetary messages. You can also send native currencies e.g ETH and erc20's and NFT's along with those messages, giving those tokens and monetary assets meaning for their transfers. BlockMail plans also to integrate other amazing features to give users the feel of their regular mail service without them knowing they're receiving extra security whilst giving full control to the users over their mails with concepts like access control.

### 2. Project links
  
These are the links to the GitHub repository for BlockMails website demo, smart contract code and frontend code.

Link here for github repo for both smart contract and website
Smart contracts - https://github.com/franfran20/blockmail_smart_contracts_testnet

Frontend code - https://github.com/franfran20/block_mail_project

This is in no way production ready as extra features and security checks along with a far greater user experience is currently being worked on and would be boosted by grant approval.
  
### 3. How is IPFS, Filecoin, or related technology used in this project? 

BlockMail is an email service that enables users send mails to-and-fro. Those mails need somewhere to be stored. BlockMail uses IPFS as it's primary storage layer for storing those encrypted mails and integrates web3.storage in the demo to do this. BlockMail plans to integrate other services to provide extra pinning of mails e.g pinata, filebase etc. In the case of anyone of the providers going down.
BlockMail aims to also provide users an optional decentralized storage solution for their mails.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 

BlockMail already has a functional demo which was a runner up at the Filecoin green Sustainable Blockchain hackathon. I understand this demo is nowhere near production ready as a lot of tests and new features need to be added on.

BlockMail has different layers to work on and believes this grant would boost the production of these layers drastically.

- Smart Contracts
The smart contract are an essential and fundamental area for BlockMail and serves as the base layer for access control and on chain encryption as well as security for BlockMail. With this grant new features will be added on to BlockMail including governance, incentives layer, naming system, fee structure, gas effeciency etc.

- Storage Layer
BlockMail aims to cover all the cost of pinning for all the mails sent to and fro it's service and provide other storage solutions for it's users to increase persistence of mails. 

- Encryption Layer
Right now in the demo BlockMail uses on chain encryption via lit protocol for single addresses and just one decryption mechanism. We plan to improve this to make the application more secure for all users.

- User Experience Layer
The user experience layer is a very important layer for BlockMail. Giving users a familiar environment to interact with their emails in the best friendly secure way as possible. The experience layer aims to abstract away from end users the storage layer, encryption layer and smart contracts. Providing smooth, fast and gasless experiences for users.
The documentation for BlockMail is also an essential part of any open source project. We plan to provide details on how BlockMail works and integrates all these cool technology to make sending and receiving mails as smooth and secure as possible.

- Finally, Marketing.

The grant will be split initially equally into the 5 layers to be worked on and some layers might take in more funds than others as the project progresses.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes. BlockMail would provide a weekly report template that would be submitted at the end of every week to share the progress of the project, challenges faced while building and inclusion of new team members and would provide a report also upon request from the Filecoin team.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes. BlockMail promises to comply with the ever changing community code of conduct at all times.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Yes my project was included in the runner ups for the Filecoin green Sustainable Blockchain hackathon. Here's the link to the submission of the project.

 Link - https://gitcoin.co/issue/29009

### Additional questions:

* For each team member(s), please list name, email, Github account, and role in the project.

Right now I'm the only one who is building BlockMail. Once the grant is approved I plan on involving new individuals to join the team.

Team 
Name: Egboluche Francis
Email: rickyegboluche@gmail.com
GitHub account: https://github.com/franfran20
Role: Founder | Smart contract engineer

* How did you learn about our microgrant program?

I received an email from the Filecoin team on taking the next steps through a dev grant for my project as one of the judges found it interesting after submission to the Sustainable Blockchain hackathon.

* If your project was created as part of an event or hackathon:
Yes it was!
  * What was the name of the event? 
  Filecoin green Sustainable Blockchain hackathon
  * Please link to your hackathon submission
  Link to project submission - https://gitcoin.co/issue/29009

**Comment by franfran20** [comment]
Hello @ErinOCon I haven't received any response yet. Is there any other information I'm suppose to provide. Will gladly do so

**Comment by franfran20** [comment]
Hello @ErinOCon it seems everyone is getting a response on their grant application except me. Would love to get feedback on my application

**Comment by ErinOCon** [comment]
Hi @franfran20, thank you for your proposal and for your patience with our review. This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
