### ISSUE TITLE
LedgerMail - The world's first Decentralized Email Service Grants Application

### ISSUE THREAD

**Issue by 0xsuraj** [filecoin-project/devgrants#899]
# Open Grant Proposal: LedgerMail integration with ChainSafe powered by Filecoin

**Name of Project:** LedgerMail - The world's first Decentralized Email Service

**Proposal Category:** integration-adoption

**Proposer:** 0xsuraj

**Technical Sponsor:** Mr. Piyush Maheshwari

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description
Let's consider this partnership as if Google Drive is to Gmail, OneDrive is to Outlook, and in a same way Filecoin will be to LedgerMail. 
LedgerMail is the world's first Decentralized Email Service which replaces the traditional email transfer protocols having centralized governance, cumbersome infrastructure and inadequate security measures with a disruptive Blockchain technology. LedgerMail inherits all the features of Blockchain Technology to emerge as an immutable, censorship-resistant, tamper-proof and democratic governance of user data. 
LedgerMail provides the military-grade security, cryptographic encryption, utmost level of user privacy and self-sovereignty in a decentralized way. 
LedgerMail platform is currently used by 740K+ users with half-a-million active wallets having exchanged 2 million plus transactions. LedgerMail is also used by leading enterprises and SMEs across the globe. 

## Value
LedgerMail platform has successfully integrated with Chainsafe powered by Filecoin to enable users to store their files & attachments in a decentralized way. Few of the core value propositions are:

**1. Increased User Adoption:** Simplifying the user on-boarding process to Filecoin Network through a simplistic process and real-world application of secure digital assets transfer, starting with decentralized email service. 

**2. Storage Drive:** Each user logging in or signing up to LedgerMail will have a fixed storage allocation from Filecoin powered Chainsafe which can be used for storing & sharing emails, files, data, attachments etc.  

**3. Real-world utility:** As Blockchain data is immutable which cannot be tampered or deleted, the storage utilization of Filecoin through LedgerMail will keep increasing, allowing Filecoin node operators to get rewarded for managing these operations.   

**4. Interconnectivity:** As outlined in Project Phase 2, we are planning to enable custom usernames (johndoe@filecoin) to represent uniform community of Filecoin, while allowing them to interconnect & interact with each other through our communication platform. (If we manage to partner with DNS providers to enable .FIL NFT domains for Filecoin users, we will enable the same through LedgerMail)  

**5. Personalized User Experience:** As outlined in Project Phase 2 below, we are customizing the LedgerMail application with a customized Filecoin theme to enable hyper-personalized user experience to Filecoin community.   

**6. Interoperability:** Filecoin users can seamlessly communicate with users signed up through different blockchain networks using an interoperable cross-chain bridge.   

**7. $FIL Transfer:** The interconnected community of Filecoin can use human-readable wallet IDs (johndoe@fil) to transfer $FIL tokens to each other without getting into any technical complexities. 

## Deliverables

Phase 1: The project deliverables includes a fully-functional LedgerMail service having Chainsafe as Decentralized Storage platform through which users can share & store the files & attachments. We have successfully completed this integration. 

Phase 2: Along with LedgerMail, we are introducing LedgerChat, LedgerPay & LedgerLive which are instant messaging, payment & collaboration services. We will be building these solutions while keeping Filecoin as a default storage providers. 
This project phase also covers interconnecting Filecoin community through a custom usernames (johndoe@filecoin) using which users can communicate, collaborate and transfer $FIL tokens to each other. 

## Development Roadmap
**Project Phase 1:**

Milestone 1: 

- Integration of LedgerMail with Filecoin’s ChainSafe
- Need to create accounts for each user through the backend using the APIs.
- User should be able to access the account through API using an API key. 
- User should be able to create buckets through APIs.
- User should be able to create folders and sub folders.
- User should be able to upload files to the existing folders/ sub-folders. 
- User should be able to move files between folders/sub-folders.

Milestone 2: 

- Enabling individual users to select Filecoin as storage upon login
- Creating custom APIs upon Sign Up to select Filecoin /Chainsafe as storage
- Hosting Application UI on Filecoin

Milestone 3: 

- Performing off-chain data computation on Filecoin
- Creating storage tiers for Premium data storage

Project Estimates Phase 1:
            Total Working Days    : 25                    
            Contingency               : 10%                       
            Total Cost                   : $60000 USD

Resource Allocation:
1.     Senior Blockchain Architect   : 1
2.     Senior Full Stack Developer   : 1
3.     QA Analyst                               : 1

**Project Phase 2:**

Milestone 1: Creating customized human-readable wallet IDs for Filecoin (johndoe@fil) operating on XDC Blockchain Platform
Milestone 2: Creating customized UI for users signing up with Filecoin username
Milestone 3: Interconnecting Filecoin community for exchanging digital assets with other users through cross-chain bridge
Milestone 4: Integrating LedgerChat (instant messaging solution) and LedgerLive (audio/video calling solution) with Filecoin

**Project Estimates Phase 2:**
               Total Working Days          : 45 
               Contingency                     : 10% 
               Total Cost                          : $75000 USD

## Total Budget Requested

Project Phase 1: $60,000 USD
Project Phase 2: $75,000 USD

## Maintenance and Upgrade Plans

LedgerMail team will completely own the responsibilities of ongoing support, maintenance, enhancements and upgrade plans of this integration. 

# Team

## Team Members

1. Dr. Vinay Krishna - Founder, CEO. 
Vinay is having 25+ years of extensive experience working as a Software Developer, Technical Lead, Blockchain Architect and Agile Coach. Vinay has successfully led a Blockchain Development firm which has grown to 45+ employees in last 3+ years. 
LinkedIn: https://www.linkedin.com/in/vinaykrishna/
 
2. Mr. Suraj Mulla, Vice President of Sales & Marketing
Suraj is having 9+ years of experience working in the Software Sales & Marketing industry with last 3+ years working exclusively in the Web 3.0 industry. Suraj has helped several startups to channelize their business strategic through Strategic Partnerships, Marketing, Investor Relations and Business Development. 
LinkedIn: https://www.linkedin.com/in/surajmulla/
 
3. Mr. Sujit Varghese, General Manager
Sujit is having 20+ years of experience in the Software industry specifically in the HealthCare industry where he has led initiatives around data security. Sujit has worked as CEO for one of the leading UAE based HealthCare company recently and has joined LedgerFi to expand our business operations in GCC. 
LinkedIn: https://www.linkedin.com/in/sujit-varghese/
 
4. Mr. Santhosh Thomas, Lead Blockchain Architect
Santhosh is having 15+ years of experience as a Software Architect with previous experience working with IBM as Blockchain Architect. 
LinkedIn: https://www.linkedin.com/in/santhoshkthomas/
 
5. Ms. Puja Kumari, Chief People Officer
6. Mr. Tibin Thomas, Senior Blockchain Developer
7. Mr. Ajay Kumar, Full Stack Developer
8. Mr. Naganath Bhat, Full Stack Developer
9. Mr. Anis Mangure, Digital Marketing Executive
10. Mr. Sanmeet Bamane, UI/UX Designer

## Team Website

[https://ledgermail.io](url)

## Relevant Experience

Our team has successfully built this production grade and enterprise ready application entitling it as the world's first Decentralized Email Service. We have successfully completed the Phase 1 of enabling Decentralized Storage option with Filecoin. We have prior experience building novice Web3 solutions, decentralized applications and a team of blockchain developers to enhance the product capabilities.. 

# Additional Information
We learn about the Open Grants Program from a Protocol Labs employee after reaching out through a social media platform for enabling Filecoin as a storage option for our email service. 
Email ID: suraj@ledgerfi.io

We are here not only to use Filecoin as a decentralized storage but to enable Filecoin community to have interconnected, interactive & interoperable platform for transferring their digital assets. We are enabling each of our 750K+ users to use Filecoin as their Decentralized Storage provider and we are hoping to serve millions of users through our strategic partners and enterprise customers.

**Comment by ErinOCon** [comment]
Hi @0xsuraj, congrats on your current user numbers! Is there additional context to consider when reviewing the total user count next to the total number of email exchanges? Did a large portion of your user base recently onboard?

**Comment by 0xsuraj** [comment]
Hi @ErinOCon 
Thank you for your kind words and LedgerMail users are picking up pace recently through our recent strategic announcements, so there are comparatively less email transactions. 
At the same time, LedgerMail is a closed-loop platform which operates on Blockchain technology. So, it is not possible to send emails to legacy providers operating on the IMAP/SMTP platform. 
LedgerMail is positioning itself as a Secure, End to End Encrypted Email service with a periodic use for sending sensitive information (text, files, attachments etc.). So, we are more focused towards onboarding as many users to activate the network effect and then focus on the transaction volume through a behavioural change.

**Comment by 0xsuraj** [comment]
Hi @ErinOCon 
Currently we are in the process of completing Phase 1 where LedgerMail users can enjoy the decentralized storage of Filecoin. Do we have any updates on the grants approval for this Phase 1 before we move to the second phase?
I believe it makes more sense to the users signing up to LedgerMail with their custom Filecoin usernames (johndoe@fil) when their default storage option is Filecoin. For enabling the same, we need to successfully complete the Phase 1.

**Comment by ErinOCon** [comment]
Hi @0xsuraj, thank you for your inquiry. We would like to focus our grant support on phase 2 of the project. If preferred, please feel welcome to proceed with our revision request once the integration work in phase 1 is complete. We would be happy to proceed with our final review when your team is ready!

**Comment by ErinOCon** [comment]
Hi @0xsuraj, I have closed this item for the time being. Please feel welcome to re-open when you are ready to proceed with the next phase of your project. We would be happy to kick things off when your ready!

**Comment by vinaykris** [comment]
Hi @ErinOCon - We are ready to proceed with next phase of project. Please guide us on how we could kick start it.
