### ISSUE TITLE
Walnut Wallet: Filecoin KaiOS wallet

### ISSUE THREAD

**Issue by kaifoundry09** [filecoin-project/devgrants#901]
# Open Grant Proposal: `Walnut Wallet`

**Name of Project: Walnut Wallet (Filecoin KaiOS Wallet)**

**Proposal Category:** `app-dev`

**Proposer:** `kaifoundry09`

**(Optional) Technical Sponsor:** `No`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes 

# Project Description

KaiFoundry is the leading technology solution providing company working in the world of KaiOS Creating all types of Gaming, News, Social Media and Blockchain apps for the people using the KaiOS platform. We already have 5 applications deployed on KaiOS with a cumulative user base of more than **half a million users**.

We are looking to create the first KaiOS wallet for Filecoin ecosystem. KaiOS brings the best of smartphones to affordable devices. Audience accessing this OS are first-time internet users from Asia, Africa, and South America. 

KaiOS is the third largest OS in the world with 160 million plus running devices. A wide audience of newly onboarded Internet users don’t have access to Web 3.0, due to unavailability of dApps, building on the KaiOS Platform. We need to provide the access to Filecoin ecosystem to the KaiOS users who are from countries like Africa, Asia and South America.

## Value

The Walnut wallet will help expand the Filecoin ecosystem to the KaiOS, world's third largest OS. In the next 18-24 months half a million new users will be on-boarded to the Filecoin ecosystem through the Walnut wallet. 

## Deliverables

1. Filecoin KaiOS wallet
2. Minimum 100K users for the wallet

**Adoption Strategy:** 

1. The dApp will be promoted on our existing Apps through in-app banners
2. KOLs will be onboarded to connect the audience with the application
3. Exclusive Educational Content will be created to onboard new users with the dApp
4. A campaign will be run in collaboration with KaiOS Team

## Development Roadmap

Milestone 0: At the time of grant approval ($40,000)

Milestone 1 ( 2 months) ($20,000)

1. Creating a new wallet
2. Importing an existing wallet
3. Making UI compatible with KaiOS platform and user friendly

Milestone 2 ( 3 months) ($25,000)

1. Security of private keys while generation and importing because this is a non custodial wallet.
2. Send and receive coins
3. Price discovery for the token

Milestone 3 (3 months) ($15,000)

1. Send and receive tokens from the application. 
2. Support in the application for multiple wallets 
3. Share the application via various avenues inside KaiOS app such as share via whatsapp. 
4. UI enhancements
5. Swapping tokens by taking help of blockchain ecosystem projects

## Total Budget Requested

We are looking for a total amount of $100,000 for the development and brining the first 100K users. 

## Maintenance and Upgrade Plans

We will develop and maintain the wallet for the next four years.

# Team

## Team Members

The team at Kaifoundry is lead by Mr. Vinayak Kalra. Through his excellent leadership, the team has developed and marketed 5 KaiOS apps in various different fields ranging from blockchain to gaming. Vinayak is a gold medalist computer science engineer. He is very popular speaker in India’s Top Engineering Institutes (IIT, NIT etc.) He has worked with multiple blockchain projects like Coinshop (P2P Crypto merchant network), Bricks Protocol etc. 

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/vinayak-kalra-b40910105/

## Team Website

https://kaifoundry.com/

## Relevant Experience

Team has significant experience in building the KaiOS applications and is successful in bringing users to already published applications.

## Team code repositories

https://github.com/kaifoundry/kaios-wallet

# Additional Information
How did you learn about the Open Grants Program? Twitter
Please provide the best email address for discussing the grant agreement and general next steps vinayak@kaifoundry.com
 Please include any additional information that you think would be useful in helping us to evaluate your proposal. 
Pitch Deck: https://docs.google.com/presentation/d/1JIINOU-LBC_sQHE5PGssGXo8h2C90pf3a_2A_Jfytwg/edit?usp=sharing

**Comment by ErinOCon** [comment]
Hi @kaifoundry09, thank you for your proposal! This grant is currently under review. We will be in touch with any questions.

**Comment by kaifoundry09** [comment]
Thank you @ErinOCon , please let me know if you have any questions.

**Comment by kaifoundry09** [comment]
Hi @ErinOCon please share your questions or feedback on our proposal. Looking forward to take Filecoin ecosystem to new community through the Walnut wallet.

**Comment by kaifoundry09** [comment]
Hi @ErinOCon , is there any latest update regarding the review of our proposal?

**Comment by ErinOCon** [comment]
Hi @kaifoundry09, thank you for your patience as we completed our review. We have approved a grant for $60k to support this project. In the instance that your team reaches your user onboarding goals, we can grant additional funding!

Do you have a preferred email for discussing next steps?

**Comment by kaifoundry09** [comment]
Thank you @ErinOCon Please use vinayak@kaifoundry.com for sending the email for discussing the next steps.

**Comment by ErinOCon** [comment]
Thanks you!

**Comment by smagdali** [comment]
Hi @kaifoundry09  - can you share the link with me for the project repo? the one linked here is giving me a 404: https://github.com/kaifoundry/kaios-wallet

**Comment by kaifoundry09** [comment]
Hi @smagdali please visit the following link: https://github.com/kaifoundry09/filecoin-kaios-wallet
