### ISSUE TITLE
Next Step Microgrant: WalletChat

### ISSUE THREAD

**Issue by cryptoKevinL** [filecoin-project/devgrants#904]
### 1. What is your project? (max 100 words)
WalletChat is a wallet-to-wallet chat program which aims to integrate with crypto wallets and exchanges as a way to bring a social layer to NFTs and trading.  We also include an API for use within custom applications and built-in UI for those just looking to get right to it and chat!

### 2. Project links
Link to Github repo:  https://github.com/cryptoKevinL/walletchat
Link to demo or website, if applicable:   https://ipfs.walletchat.fun,  https://walletchat-9pbwzq.spheron.app/

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
IPFS is currently used to store all message data, and we used Filecoin protocol when we deployed a secondary version of our UI on on Spheron at https://walletchat-9pbwzq.spheron.app/.  We would like to use libp2p someday for peer discovery instead of a centralized backend REST API, when the speed improves. 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
As part of open source code, we would like to create an API which is authenticated (users must request API keys) so the general public can utilize our current infrastructure to learn about the WalletChat API.  Our main focus is to ensure authentication provides users a safe learning experience, and we can easily restrict/block any spammer or inappropriate content.  We think this will help users understand and adopt the API and help build libp2p on top of it as well.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
https://devpost.com/software/walletchat
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
- Kevin L, walletchatextension@gmail.com, https://github.com/cryptoKevinL, Backend Developer 
- M Goes, mgoesdistance@gmail.com, N/A, Business Lead
- Mana Pixels, manapixels@gmail.com, https://github.com/manapixels, Front End Dev and UI Wizard
* How did you learn about our microgrant program?
 We were emailed directly, from niki.gokani@protocol.ai
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  [Chainlink Spring 2022](https://chainlinkspring2022.devpost.com/)
  * Please link to your hackathon submission
   https://devpost.com/software/walletchat

**Comment by ErinOCon** [comment]
Thanks, @cryptoKevin! Is the entirety of this project open source?

**Comment by cryptoKevinL** [comment]
yes its 100% open source, you can find the base project here:

https://github.com/cryptoKevinL/walletchat

The REST API is at:

https://github.com/cryptoKevinL/restWalletChat

**Comment by cryptoKevinL** [comment]
Hi @cryptoKevinL - is there any update to this request?  sorry I didn't tag you last message!

**Comment by cryptoKevinL** [comment]
HI @ErinOCon - just checking if this request is still open? Thanks

**Comment by ErinOCon** [comment]
Hi @cryptoKevinL, thanks for checking in! This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
