### ISSUE TITLE
Next Step Microgrant: you and i 

### ISSUE THREAD

**Issue by 0xgoldenlion** [filecoin-project/devgrants#905]
### 1. What is your project? (max 100 words)
You and I, is an on-chain music composition , its an interface composing an append only together.

### 2. Project links
  
Link to Github repo: https://github.com/0xgoldenlion/you-and-i
Link to demo or website, if applicable: https://ethglobal.com/showcase/you-and-i-ptuku
License: open source

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
nft storage is used to store the songs lyrics, and pass them to the smart contract for minting.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
add minting functionality for the completed song, in addition to that integrate it with zora auction house, those are short term goals for the long term i wanted to make it eaiser for people to join an online session together and start creating songs, i also want to implement lit protocol to hide the song lyrics which will be a fun little game sending someone the song and have the decipher its lyrics .

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

I agree
  
### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
https://ethglobal.com/showcase/you-and-i-ptuku
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
- M. Awad , 0xgoldenlion@gmail.com , creator. 
* How did you learn about our microgrant program?
We were emailed directly, from [niki.gokani@protocol.ai](mailto:niki.gokani@protocol.ai)
* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
     Zora Metabolism
  * Please link to your hackathon submission 
    https://ethglobal.com/showcase/you-and-i-ptuku

**Comment by 0xgoldenlion** [comment]
hey @ErinOCon , any news regarding this ?

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
