### ISSUE TITLE
Open Grant Proposal: Ai.Senses – FileCoin Powered Mental Health DApp

### ISSUE THREAD

**Issue by mentalinnov** [filecoin-project/devgrants#906]
# Open Grant Proposal: `Ai.Senses – FileCoin Powered Mental Health DApp`

**Name of Project: Ai.Senses

**Proposal Category:** `app-dev`

**Proposer:** `TBC`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** `Yes`

# Project Description

Ai.Senses is an artificial intelligent chatbot blockchain application powered by Filecoin’s fully decentralised storage and expert clinical psychologists. Ai.Senses provides mental health assistance to clients at anytime and anywhere and at the same time guarantees their personal privacy and confidentiality. 
Ai.Senses will be available to anyone in the world with access to internet.
The web app version will be hosted on ai-Senses.co. We endeavour to make the initial version of the app free for everyone to use.
We intended to leverage the Filecoin storage network to secure client identity, medical histories and interactions with the chatbot so as to provide privacy and confidentiality guarantee. With Filecoin’s secure decentralised storage, Ai.Senses can safeguard healthcare records, get access to data security, maintain transparency, prevent records from getting tampered and earn the trust of customers.

## Value

Stigma, discrimination and human rights violations against people with mental health conditions are widespread in communities and care systems everywhere; 20 countries still criminalize attempted suicide. Across countries, it is the poorest and most disadvantaged in society who are at greatest risk of mental ill-health and who are also the least likely to receive adequate services.

Even before the COVID-19 pandemic, just a small fraction of people in need had access to effective, affordable and quality mental health care. For example, 71% of those with psychosis worldwide do not receive mental health services. While 70% of people with psychosis are reported to be treated in high-income countries, only 12% of people with psychosis receive mental health care in low-income countries. For depression, the gaps in service coverage are wide across all countries: even in high-income countries, only one third of people with depression receive formal mental health care and minimally-adequate treatment for depression is estimated to range from 23% in high-income countries to 3% in low- and lower-middle-income countries.

Traditional mental health services have limited availability (too few mental health professionals), limited accessibility (even fewer outside major cities and office hours), limited affordability (high costs), and limited acceptability (take-up often stigmatized). Against a backdrop of limited resources and increasing need, digital tools present an opportunity understand people’s needs better and scale up support at lower per-capita costs.
By collecting data routinely and at scale, AiSenses can help people identify unnoticed and emerging areas of need and improvement — such as stress hotspots, service gaps and quality, and access and utilization barriers. Pooling aggregate and anonymized data on physical, mental, and financial well-being from different sources 
•	AiSenses can improve the diagnosis and treatment of mental ill health by facilitating measurement. It can gather standardized data easily and often, including validated, structured rating scales for the frequency and severity of symptoms — to overcome both users’ recall bias and providers’ treatment inertia.
•	AiSenses can passively monitor factors that affect or indicate emotions, moods, and behavior — such as users’ sleep, activity, location, voice, and keystroke patterns — to augment clinical ratings or patients’ journals or memories with blockchain technology platform. Over time, such digital biomarkers and phenotypes could better predict risk, response to treatment, recovery, and relapse, facilitating personalized interventions that improve outcomes. 
•	Most important part as AiSenses can have the potential to reduce public prejudice and internalized stigma attached to mental ill health, which are major barriers seeking support even when it is available. 
•	AiSenses can reach more people promptly, conveniently, and often. Chronic clinician shortages — particularly in rural areas and poorer countries — result in long delays for traditional services. 
With the help of Filecoin, Ai.Senses can also address the privacy and confidentiality issue that most people are concerned about when accessing mental health services. Filecoin will help us to: 
· processing and signing user’s digital identity, identity documents as well as important transactions related to user’s identity.
· securing the medical histories and interactions with the chatbot. 
· giving user full control over their own mental health records.

# The risks if we don't get it right:

Failure to act upon the current crisis of lack of mental health services can have disastrous consequences. For example, many health industry reports pointed out that inadequate treatment was linked to the suicide of patients. Suicide is one of the most common causes of preventable death among adolescents and young adults. Suicide is currently the second leading cause of death in 15 to 29 year old, resulting in enormous social disruption and losses in productivity. Between 10 and 20 million depressed individuals attempt suicide every year and approximately 1 million complete suicide. In response to these alarming circumstances, in 2016 the World Health Organization declared depression to be the leading cause of disability worldwide

# Risks likely to make project execution difficult:

An advance user interface design that provides a seamless experience for end-user and the integration of the AI model with clinical psychology database will be the biggest challenges for the project. 

## Deliverables

Ai.Senses will deliver a web (mobile responsive) user frontend to allow users to engage with our AI powered mental health chatbot to access mental health services.

![Bot2](https://user-images.githubusercontent.com/97427001/186414308-0a614d30-8d92-4b00-84ba-5c506db2e3b8.png)

### User Registration
User can access our platform through web browser from their devices using HTTPS protocol. Once connected, user will be prompted to register a new account in the system. This user registration will also trigger a new account being created in the blockchain. The blockchain address will then be used as the unique ID number for each user. User can choose to upload any related documents such as medical history or ID verification documents which will be securely stored in the Filecoin/IPFS with hash address written into the blockchain.

### Using the Chatbot
Once user registration is completed, user can start having conversation with the AI chatbot. Our chatbot is compatible with most mainstream messenger apps such as Wechat, Facebook messenger and WhatsApp.
The chatbot is backed with NLP and knowledge database as well as information (medical history) from the Filecoin secure storage. During the conversation, our chatbot will attempted to detect patterns in phrasing, typing, length of sentences and even in the number of grammatical errors, revealing dependencies to different emotional states. 

By detecting and monitoring the emotional state, our chatbot will be able to:
• raise awareness, reduce risk factors (such as insufficient sleep or physical activity), or teach healthy coping skills to the user
• provide digital support and treatment tools as alternatives to traditional counselling and talking therapies
• signal in time about reaching a level of depression where urgent intervention by a specialist is needed.

### Milestone 1 – Decentralised File Storage
Creating the proposed architecture of the overall system, mapping its relation to Filecoin/IPFS and other necessary processes (blockchain interoperability, tokenomics, etc). Designing the storage architecture for the type of contents and app features expected by exploring through the Filecoin APIs and functionalities. 
Resources required: Strategy, Research, Development

Roles: Blockchain strategist to lead research & sketch proposed architecture. Dev lead to convert/integrate IPFS into content processes, and explore the proposed Dapp features possibilities. Opportunity to contract Filecoin freelancer programmer to assist.

Duration: 1 month ()

Funding required: USD20,000

### Milestone 2 - INFRASTRUCTURE SETUP, WEB FRONT-END UI DEVELOPMENT:
-	Design and complete AWS web server & application server hosting infrastructure setup. A web hosting solution is required for our webapp which then will be fully integrated with blockchain and FileCoin platform.
-	The web server infrastructure will be hosting our web application
-	The application server infrastructure will be hosting smart contract and storage operation application.
-	Set up front-end web portal home page and user interface.

Duration: 1 month
Funding required: USD20,000

# Milestone 3 – USER ACCESS, USER CONTENT STORAGE AND CHATBOT INTEGRATION 
-	Simplifying user account registration/authentication to the platform, using web3 wallet protocols. Enabling access controls of specific content entries: e.g. individual health records 
-	Complete integration of Filecoin storage
-	Complete integration of AI logic for the chatbot
-	Release the product to public
Duration: 1.5 month
Funding required: USD20,000

## Total Budget Requested

USD60,000

# Team

## Team Member
Ming Cheng
Guo Liu

## Team Member LinkedIn Profiles
https://www.linkedin.com/in/%E6%98%8E-%E7%A8%8B-456821245/
https://www.linkedin.com/in/guofan-lu/

# Additional Information

N/A

**Comment by jenks-guo-filecoin** [comment]
Really interested in this project. Can I get some background on this @mentalinnov? Reach out to me via slack please @jenksguo on Filecoin public slack: https://filecoin.io/slack

**Comment by ErinOCon** [comment]
Hi @mentalinnov, thank you for your proposal! We will not be moving forward with a grant at this time, but would strongly encourage you to participate in hackathon. Doing so can build your experience with Filecoin/IPFS and can help showcase your work for future proposals.
