### ISSUE TITLE
Next Step Microgrant: Waterdrop

### ISSUE THREAD

**Issue by knrdrbn** [filecoin-project/devgrants#907]
### 1. What is your project? (max 100 words)
Devs need test eth to play around with. After using test eth, it's nice to give it back as it makes the faucet managers happy. We drop NFT art to people who give back test eth to testnet faucets.

### 2. Project links
  
Link to Github repo: https://github.com/ProphetFund/waterdrop
https://faucetdonors.xyz/
License: Unlicense 
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

The NFTs in the smart contract are AI generated images, using a state of the art diffusion model to create them. This is computationally quite expensive, but the end result is very satisfying. These images are then stored ipfs and pinned with Filecoin, to ensure they’re never lost. They are, truly, decentralized.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We want to making the minting and whitelisting dynamic. Currently, it's based on a one-off data analysis and a one-time mint. We want to make this dynamic and maintenance-free. 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### Additional questions:
* https://github.com/Hugo0/ hugo@prophet.money, https://github.com/knrdrbn konrad@prophet.money

* How did you learn about our microgrant program?

From Niki

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
Ethglobal
  * Please link to your hackathon submission
https://devpost.com/software/faucetdonors-xyz-waterdrop

**Comment by ErinOCon** [comment]
Hi @knrdrbn, I hope you are doing well! Do you expect to have an update available this week?

**Comment by ErinOCon** [comment]
Hi @knrdrbn, this item has been closed. Please feel welcome to reapply if your project is open source in the future.
