### ISSUE TITLE
Next Step Microgrant: <PeerTube – Federated Video Asset and Streaming Platform>  

### ISSUE THREAD

**Issue by Glochain** [filecoin-project/devgrants#908]
### 1. What is your project? (max 100 words)
As the Blockchain ecosystem continues to grow, there is a need to adopt a web3 based video platform since video content constitutes a large chunk of data online. PeerTube is decentralized and federated video platform developed using the blockchain technology where users, can watch their favorite videos NFTs and creators mints videos as NFTs in the community’s marketplace. They can buy and sell theses NFTs for profit in the marketplace. These NFT are also visible on OpenSea etc. The platform also incorporate video streaming based on the Livepeer protocol and IPFS/Filecoin. Assets are stored on IPFS using NFT.Storage. Metadata that are generated are stored on-chain. 

 [Link to public GitHub repo](https://github.com/Glochain/PeerTube) 

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)
The front-end was designed with Next.js framework. Technologies like IPFS / Filecoin were used to store users' video content  as NFTs in a decentralized fashion on NFT.Storage. Contents' metadata and user profile images will be stored on NFT.Storage. The project was designed to be responsive so that whichever device you connect with, you will have a great user experience. Video creators can create videos and upload them to the platform or schedule a live stream to all interest on that topic. All metadata and content would be stored on IPFS using NFT.Storage.
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
* Using ERC 1155 metadata standard to improve the current metadata which is ERC721.
* improve the way video contents are uploaded to NFT.Storage.
* Creating categories for grouping videos of the same niche.
* Curating data for analysis and visual data display
* Cleaning up the NFT smart contract and optimizing the smart contract for better performance
* Improve the frontend to a better user interface
 
### 4. Is this project open source?
Yes, MIT+Apache.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
Devfolio ETHERNALS 2022 Hackathon
* https://devfolio.co/projects/peertube-2131
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Gloria Onuora, gloriaukoha@gmail.com, @GloriAustin – Sole developer.

* How did you learn about our microgrant program?
Through a chat with an IPFS / Filecoin staff.
* If your project was created as part of an event or hackathon:
Devfolio ETHERNALS 2022 Hackathon

https://devfolio.co/projects/peertube-2131

**Comment by ErinOCon** [comment]
Hi @Glochain, thank you for your proposal! Is this project open source?

**Comment by Glochain** [comment]
Hi
Yes, the project is open source. I also stated that in the grant
application. Thanks

**Comment by ErinOCon** [comment]
Hi @Glochain, please check your email to review the status of this microgrant payment.
