### ISSUE TITLE
Next Step Microgrant: Marry3

### ISSUE THREAD

**Issue by 0xYootou** [filecoin-project/devgrants#909]
### 1. What is your project? (max 100 words)

Marry3 is the civil affairs bureau of the encrypted digital world, which is responsible for issuing the marriage certificate on the chain to the 0x address of the Web3 aborigines.
Marry3 mint two Marry3 Certificates to two addresses after multi-signature, which is a type of SBT. It stores the relationship between you two and other information, which can be queried and verified at any time.

### 2. Project links

Link to Github repo: https://github.com/marryinweb3/Marry3
Link to demo or website, if applicable: https://marry3.love
License: MIT

### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

one. we use nft.storage to storage our marriage certificate’s picture on ipfs.
two. we want to deploy it to fvm chain.
three. we want to use ipfs to storage more relationship created in marryverse activity.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. make marryverse activity trueth.
2. update our dapp, add wedding appointment function, add some social function around metaverse wedding.
3. deploy on more chain, like fvm.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

yes

### 6. Does your proposal comply with our Community Code of Conduct?

yes

### 7. Links and submissions

- If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

https://pl.coinemissary.com/transfer-requests/5766866771

### Additional questions:

- For each team member(s), please list name, email, Github account, and role in the project.
  - name: 0xyootou, email:xinyu198736@gmail.com, github:0xYootou, role: project manager
  - name: daodao, email:daodao@lxdao.io, github:daodao, role: designer
- How did you learn about our microgrant program?
  - kenlab team
- If your project was created as part of an event or hackathon:
  - What was the name of the event?
    - kenlab metaverse hackathon
  - Please link to your hackathon submission
    - https://dorahacks.io/buidl/2963

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
