### ISSUE TITLE
Next Step Microgrant: Warp - A super app for sharing on Web3

### ISSUE THREAD

**Issue by Rishikeshk9** [filecoin-project/devgrants#910]
![Warp logo-06 (1)](https://user-images.githubusercontent.com/36479949/186747624-538be095-8eed-49c5-85ed-2358e3e57f7e.png)

### 1. What is your project? (max 100 words)
Warp lets the user to share files from wallet to wallet.
Warp makes use of IPFS to store the file which needs to be shared & Tableland to add an entry to the database which contains receivers wallet ID,file CID & Sender's Wallet Address.
If the user wants to notify the receiver about the file he's sent,he can choose to enter receiver's mail ID. This mail ID is not stored anywhere to respect user's privacy.

### 2. Project links
  
Link to Github repo: 
https://github.com/Rishikeshk9/warp-frontend
https://github.com/Rishikeshk9/warp-backend
Link to demo or website, if applicable: 
https://warp-frontend-xi.vercel.app/

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
User chooses the file which he wants to share with the recipient & then this file is uploaded to IPFS using web3.storage javascript API. Content ID of the file is stored to database.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
| Milestone |    Features   |
|--------------|-----------|
| Milestones 1 | Saving Contacts, Data stored to TableLand   |  
| Milestones 2 | Extension for Browsers   |  

#### Milestone 1 :
Users can save other wallet addresses with uniquely identifiable names for easy sharing. 
Tableland will be used for saving data on-chain

#### Milestone 2 :
An extension for browsers starting with Brave & Chrome, this will have the users a handy way of sharing files over IPFS with an easy access to Warp

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

 Yes, We will share updates on Development every other week plus a report at the end of three months.
 
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
Live Demo(Goerli Testnet)  : 
https://warp-frontend-xi.vercel.app
[](url)
Introduction Video : 
https://www.youtube.com/watch?v=-yk3hpXE3xk
[![IMAGE ALT TEXT](http://img.youtube.com/vi/-yk3hpXE3xk/0.jpg)](http://www.youtube.com/watch?v=-yk3hpXE3xk "Warp - Introduction")

* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://ethglobal.com/showcase/warp-6jrwx
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Rushikesh Kardile - Fullstack Developer 
rushikeshkardile9@gmail.com
https://github.com/Rishikeshk9

* How did you learn about our microgrant program?
Reference from a Friend

* If your project was created as part of an event or hackathon:
  * What was the name of the event?  
Built the first Prototype at the ETHGlobal HackFS event.

  * Please link to your hackathon submission
  https://ethglobal.com/showcase/warp-6jrwx

**Comment by ErinOCon** [comment]
Hi @Rishikeshk9, thank you for your proposal! Is this project open source?

**Comment by Rishikeshk9** [comment]
> Hi @Rishikeshk9, thank you for your proposal! Is this project open source?

Yes, it is Open Source.

**Comment by Rishikeshk9** [comment]
> Hi @Rishikeshk9, thank you for your proposal! Is this project open source?

Hi @ErinOCon Kindly let me know if their is need of any more information on the project. Thanks

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by Rishikeshk9** [comment]
HI @ErinOCon, Thank You for the approval.
Reaching out to you on mail, for further actions.
Thanks :)
