### ISSUE TITLE
Open Grant Proposal: FilPulse V2

### ISSUE THREAD

**Issue by arctic-ash** [filecoin-project/devgrants#911]
# Open Grant Proposal: `FilPulse V2`

**Name of Project:** FilPulse V2

**Proposal Category:** app-dev, community

**Proposer:** arctic-ash (CrossChain Labs)

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Yes

# Project Description

Filecoin has increasingly grown the open source developer ecosystem. Currently there are over 240 repositories, that are actively increasing with the help of the developers around the world. This makes it hard to track the activity among different Filecoin organizations on Github and keep updated on the contributions done by the developers and how the ecosystem is evolving.

FilPulse V1 came as a good solution by aggregating data such as the number of commits, repositories, contributors, PRs, the top contributors of the month, the evolution of commits and active contributors for each month over the last year and by tracking the recent commits that are being done in the various Filecoin organisations. The focus was mainly on the perspective of investors, storage miners and clients, but not so much on the developer community. 

FilPulse V2 is going to address this gap by focusing on the developer community as well as improving the experience of all the interested parties. The solution is to create the proper environment for users to keep track of the GitHub data related to the Filecoin's open source ecosystem. PRs, issues, commits and contributors' information will be collected under an easy to use and interactive table that will enable users to search and filter data as needed. Users that want to have access to their private watchlist, to easily track the PRs and issues that are interested in, need to login/signup. 

Users will discover how fast they can access GitHub information from all the repositories scattered on different Filecoin organisations. They will be able to easily:
- search through PRs, issues, contributors and commits
- filter data in ways that will meet their needs
- build their own personalized GitHub watchlist
- follow the latest changes and comments made on their preferred PRs and issues 
- keep track of the contributions done across the entire Filecoin ecosystem

To drive adoption of the FilPulse V2 platform CrossChain Labs takes the commitment to:
- create a YouTube video tutorial showcasing the FilPulse functionalities and usage
- distribute it via Filecoin's Slack channels
- add Google Analytics to track users engagement in order to adapt and improve accordingly

## Value

There are many benefits of getting the FilPulse V2 project up and running:
 - it focuses on the developer community as well as improving the experience of all the interested parties
 - collects the relevant data on PRs, issues, commits and contributors and displays it in a clean, easy to use, interactive table 
 - provides a complete view of all the contributors that participate in the development of Filecoin ecosystem and all the contributions done across all repositories within the Filecoin organisations
 - allows users to fast-search and filter data as needed
 - users can login/signup to easily track the PRs and issues that are interested in, by adding them to their private watchlist

The risks are low since the architecture has a robust structure that contains the frontend, backend and a database stored on Google Cloud and the implemented APIs can be easily integrated in other apps.
CrossChain Labs team is experienced enough to accomplish this project and to maintain it during time.
## Deliverables

- GitHub Scraper V2 which will collect all the extra data from GitHub
- FilPulse V2 APIs which will serve to get the data from the scraper and interact with the new FilPulse V2 dashboard
- FilPulse V2 Dashboard which will include the following new features:
  - Login/Signup
  - Watchlist - with the following data: PR/commit's ID, name, participants, status, new comments, last update
  - PRs with - with the following data: PR's ID, name, contributor, status, last update
  - Issues - with the following data: issue's ID, name, contributor, assignee, status, last update
  - Commits - with the following data: commit's hash, description, contributor, last update
  - Contributors - with the following data: contributor's GitHub ID, project is working on, number of commits done on that project, PRs ratio bar (open/merged), issues ratio bar (open/closed)

### Dashboard Overview

**FilPulse V2 Dashboard**
<img width="662" alt="FilPulseV2 overview" src="https://user-images.githubusercontent.com/91743348/186755398-088469d4-5b20-4fe0-9d36-122d4494d31a.png">

**FilPulse V2 PRs tab**
<img width="662" alt="PRs" src="https://user-images.githubusercontent.com/91743348/186755418-b7bbdc21-8cb5-4358-8213-3cd70b9f2e9b.png">

**FilPulse V2 Issues tab**
<img width="662" alt="Issues" src="https://user-images.githubusercontent.com/91743348/186755437-bbc3092d-2719-482a-bfe3-79673aefb6d3.png">

**FilPulse V2 Commits tab**
<img width="662" alt="Commits" src="https://user-images.githubusercontent.com/91743348/186755462-0871bcaa-c3d0-4674-a391-3bb1a36d8b4b.png">

**FilPulse V2 Contributors tab**
<img width="662" alt="Contributors" src="https://user-images.githubusercontent.com/91743348/186755509-af398e81-2657-48df-8c0e-41581f6b8bd2.png">

## Development Roadmap

**Milestone 1**

Implement the Github scraper V2:
  - get the PRs data from all the repos included in the Filecoin organizations on GitHub 
  - collect the issues data across the Filecoin's Github repos
  - get all the commits info that are part of the Filecoin organizations on GitHub 
  - for each contributor that is part of the Filecoin organizations calculate all the contributions made on each project (commits, PRs and issues)

Build the FilPulse V2 UX

Implement the following FilPulse V2 APIs required to develop the frontend: 
  - PRs API that returns all the PRs. It allows to filter by PR's GitHub ID, PR's name, contributor, status and sort by last update
  - issues API that returns all the issues. It allows to filter by issue's GitHub ID, issue's name, contributor, assignee, status and sort by last update
  - commits API that returns all the commits from all the repos. It allows to filter by commit's GitHub hash, description, contributor and sort by last update
  - contributors API that returns the list of contributors and the corresponding contributions made per each repo. It allows to filter by contributor's GitHub ID, project name, and to sort by last update, number of commits done on that project, number of PRs and number of issues

Members:
  - Andreea - Project Manager
  - Cristina - Full Stack Developer (JavaScript, React)
  - Catalin - Full Stack Developer (JavaScript, React)
  - Florin - UI/UX Designer (Sketch, Figma)

Start date: 12th of September, 2022
Completed By: 10t of October, 2022

Budgetary Needs: This milestone will last 4 weeks = $28,000

**Milestone 2**

Implement the FilPulse V2 APIs required by frontend:
  - signup API for creating a new account 
  - login API is required for accessing the watchlist and choosing which PR/issue to add to it
  - add to watchlist API that is being used for adding PRs/issues to the logged in user's watchlist
  - remove from watchlist API that is being used for removing PRs/issues from the logged in user's watchlist
  - watchlist API that returns the updates on the tracked items such as issues and PRs, highlighting new comments

Build the dashboard to display:
  - signup section to create a new account
  - login section to have access to the user's watchlist and be able to select which PR/issue to add to it
  - PRs tab - allows to filter by PR's GitHub ID, PR's name, contributor, status and sort by last update
  - issues tab - allows to filter by issue's GitHub ID, issue's name, contributor, assignee, status and sort by last update
  - commits tab - displays all the commits and allows to filter by commit's GitHub hash, description, contributor and sort by last update
  - contributors tab - displays the list of contributors and the corresponding contributions (commits, PRs, issues). Allows to filter by contributor's GitHub ID, project name, and to sort by last update, by number of commits done on that project, number of PRs and number of issues 
  - the watchlist tab - shows updates on the tracked items such as issues and PRs, highlighting new comments. Allows to filter by PR's/issue's GitHub ID, name, participants, status and sort by number of new comments, last update

Make the final adjustments and release the product:
  - create the production infrastructure
  - deploy filpulse.io V2 webapp
  - run the final tests
  - public release on https://filpulse.io

Members:
  - Andreea - Project Manager
  - Cristina - Full Stack Developer (JavaScript, React)
  - Catalin - Full Stack Developer (JavaScript, React)

Completed By: 7th of November, 2022

Budgetary Needs: This milestone will last 4 weeks = $22,000

> NOTE: The M2 calculation includes the cloud infrastructure cost estimated at $1,000.

## Total Budget Requested

We're requesting a total funding of $50,000 to complete all the above milestones, and the fund will be split into:

- Research and Development
- UX
- Infrastructure

| Milestone  | Duration| Cost    |
|------------|---------|---------|
|   #1       | 4 weeks | $28,000 |
|   #2       | 4 weeks | $22,000 |
|            |         |         |
| **Total**  | 8 weeks | $50,000 |

> NOTE: The M2 calculation includes the cloud infrastructure cost estimated at $1,000.

## Maintenance and Upgrade Plans

This is an open source project and we are committed to maintaining it by doing bug fixes based on the community feedback.

# Team

## Contact Info
Thank you for your interest in FilPulse V2 project. If you have any question don't hesitate to contact me at andreea.stefan@crosschainlabs.tech 

## Team Members

- Andreea - Project Manager
- Cristina - Full Stack Developer (JavaScript, React)
- Catalin - Full Stack Developer (JavaScript, React)
- Florin - UI/UX Designer (Sketch, Figma)

## Team Member LinkedIn Profiles

- [Andreea Stefan](https://www.linkedin.com/in/andreea-stefan-66740b20/)
- [Cristina Varteniuc](https://www.linkedin.com/in/cristina-varteniuc-6b3121224/)
- [Catalin Vlad](https://www.linkedin.com/in/catalin-vlad-48b828229)
- [Florin Gradinaru](https://ro.linkedin.com/in/florin-gradinaru-73891bb)

## Team Website

https://www.crosschainlabs.tech/

## Relevant Experience

We are a team of developers with experience in blockchain technologies. Some of the latest dev-grants were for projects from NEAR protocol (NEAR registrar, Audit Registry, near.link) and from Filecoin (FilMarket) with tech stack: IPFS, rust, react, go and javascript.
- Andreea Stefan - is a former Consensys employee and the co-founder of Crosschain Labs. Has a work experience as a software developer of 15 years and her main focus for the last several years is blockchain development
- Cristina Varteniuc - accomplished numerous courses of software development, participated to multiple hackatons and her interest is in blockchain-related product development
- Catalin Vlad - has been programming for as long as he can remember and is passionate about anything related to technology. He prefers building blockchain-related apps and solving practical problems, as hard as they might be.
- Florin Gradinaru - is an experienced artist and graphic designer with 18 years of work experience and a strong passion for UI/UX

## Team code repositories

- https://github.com/CrossChainLabs
- https://filmarket.io 
- https://filpulse.io

**Comment by realChainLife** [comment]
Hi @arctic-ash thank you for the proposal. Can you also include in the proposal your teams plan for driving adoption of the platform. We'd appreciate an overview of how this feature and functionality suggestions will facilitate user onboarding.

**Comment by arctic-ash** [comment]
Hi @realChainLife, we included in the proposal my teams plan for driving adoption of the platform and an overview of how features and new functionalities will attract users. Looking forward to your feedback!

**Comment by ErinOCon** [comment]
Hi @arctic-ash, this grant has been approved! We will send an email to discuss next steps.
