### ISSUE TITLE
Open Grant Proposal: Streamline knowledge management &  discovery in Filecoin community with Peeranha protocol

### ISSUE THREAD

**Issue by sergeyi23** [filecoin-project/devgrants#912]
# Open Grant Proposal: `Streamline knowledge management &  discovery in Filecoin community with Peeranha protocol`

**Streamline knowledge management &  discovery in Filecoin community with Peeranha protocol:**

**Proposal Category:** `app-dev`

**Proposer:** `sergeyi23`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

Effective knowledge sharing is highly important for technical communities such as Filecoin. However, the current approach within the Filecoin ecosystem, as well as in other Web3 communities, is proven to be very inefficient.

Messengers such as Discord, Telegram, and Slack are the most widely used tools for community Q&A. There are several significant disadvantages of using these tools for community knowledge sharing, particularly Q&A:
- Questions have a short window of visibility to the community and disappear in the flow of the new messages in communication threads; 
- Existing questions are hard to find causing the same questions to be asked repeatedly;
- Questions and answers are not indexed by search engines as Google;
- Questions and answers are not curated;
- Communities in different messengers and different languages exist in silos.

The diagram below shows current knowledge-sharing flows in the Filecoin community:

![image3](https://user-images.githubusercontent.com/8031821/186766015-9e92902c-21ba-43a7-bea7-3b5711b848cc.png)

We are proposing to streamline knowledge management & discovery in the Filecoin community by expanding Peeranha protocol. The diagram below shows the proposed knowledge-sharing flow in the Filecoin community.

![image1](https://user-images.githubusercontent.com/8031821/186766049-85a2083b-a28e-4c75-a7b8-2b1d1af2b88c.png)

The proposed flow breaks down the silos between communication in various channels and languages, structures the most valuable knowledge, and exposes it to search engines such as Google. As a result, users are able to find information about Filecoin much easier using the tools and languages that they prefer.

## Value

An improved knowledge-sharing ecosystem will make it easier for people to find information about Filecoin. We will build a sophisticated knowledge base that is structured and searchable by search engines. It will bring together communities that otherwise exist in silos: users that prefer different tools for communication or speaking different languages.

The simplified diagram below shows the question and answer flow with the proposed approach allowing users that reside in different channels and speak different languages to collaborate effectively.

![image2](https://user-images.githubusercontent.com/8031821/186766085-5dfc962e-9134-47ec-ba91-e8013cf63e7f.png)

We at Peeranha share Filecoin’s mission of preserving "humanity's most important information" and we are taking it forwarded by preserving what we believe is one of the most critical pieces of information on the web, community knowledge. 

## Deliverables

1. **Organized Filecoin knowledge base on Peeranha** - advanced collection of Q&A, tutorials, and documentation about Filecoin from various sources in several languages;

1. **Slack, Telegram, and Discord bots for Peeranha** - bots helping to break down the silos between communication channels by allowing post content and receiving notifications;

1. **Auto-translation bot** - a bot that helps to break down the silos between different languages by instantly translating content posted on Peeranha to various languages;

1. **Auto-answer engine and bot** - AI and NLP-based engine and bot that allow users to instantly get answers to their questions from a channel that they prefer.

### Milestone 1 
*The work on this milestone can happen in parallel with the other milestones.*

**Goal**: Organize Filecoin knowledge base on Peeranha;
**Deliverables**: 
- Scrapped Slack, Discord, and Telegram channels and valuable knowledge extracted to Peeranha;
- Slack, Discord and Telegram monitored for valuable knowledge and that knowledge moved to Filecoin Q&A on Peeranha;
- The knowledge base is continuously updated based on other resources in the Filecoin ecosystem;
- Knowledge base translated to languages that are important to the Filecoin community.

**People**: 1 Community Knowledge Manager

**Funding**: $12,000

**Timing**: 6 months

### Milestone 2 
**Goal**: Build bots for Discord, Slack, and Telegram ;

**Deliverables**:

Bots for Discord, Slack, and Telegram that provide the following capabilities:
- Notifications to community members about new questions posted on Filecoin Q&A;
- Link account on Slack, Discord, and Telegram with blockchain account on Peeranha;
- Post answers to Peeranha protocol from Slack, Discord, and Telegram;
- Reply to questions on Peeranha directly from Slack, Discord, and Telegram.

Integrate bots to Filecoin communities in Slack, Discord, and Telegram.

**People**: ¼ architect, 1 back-end developer, ½  front-end developer

**Funding**: $25,000

**Timing**: 2.5 months

### Milestone 3 
**Goal**: Build an auto-translation bot;

**Deliverables**: 
- Auto-translation engine that listens for new questions, answers, or comments and instantly translates into required languages and posts translations on Peeranha;
- Multilingual capabilities on Peeranha Web UI;
- Multilingual capabilities for Slack, Discord, and Telegram bots;
- Content on Peeranha is indexed by search engines in several languages.

**People**: ¼ architect, 1 back-end developer, 1 front-end developer

**Funding**: $25,000

**Timing**: 2 months

## Milestone 4 

**Goal**: Build auto-answer engine and integrate it with Discord, Slack, and Telegram bots;

**Deliverables**: 
- ML model matching users' questions with existing Q&A using word-embedding and sentence-embedding algorithms of NLP;
- The auto-answer engine that find similar questions using built ML model;
- Auto-answering integrated into bots for Discord, Slack, and Telegram.

**People**: ¼ architect, 1 Data Scientists, 1 back-end developer

**Funding**: $35,000

**Timing**: 2 months

## Total Budget Requested

$98,000 spent on development

## Maintenance and Upgrade Plans

# Team

## Team Members

Slava Kreynin - CEO
Sergey Ilin - CTO, architect
Denys Romanov - Front-end developer
Oleksandr Zhytnyk - Back-end developer
Genady Yoffe - Data Scientist and AI

## Team Member LinkedIn Profiles

Slava Kreynin - https://www.linkedin.com/in/stevekreynin/

Sergey Ilin - https://www.linkedin.com/in/sergeyilinn/

Denys Romanov - https://www.linkedin.com/in/denis-romanov88/

Oleksandr Zhytnyk - https://www.linkedin.com/in/freitagg/ 

Genady Yoffe - https://www.linkedin.com/in/genady-yoffe-1b142824/

## Team Website

https://peeranha.io/

## Relevant Experience

Slava Kreynin is CEO of Peeranha and responsible for business development. Prior to Peeranha he started Forte Group, a full-spectrum, global software development company. Forte has 800 employees working out of 11 offices in 6 countries around the world and $50M in revenue.

Sergey Ilin is the technical co-founder of Peeranha and is responsible for the technology. He is a Software Architect with 15 years of experience building software development teams and working with blockchain technology for the past 6 years. He was the founding engineer at two successful blockchain companies, Bloxroute Labs and VM Capital .

Denys Romanov is a Front-end Team Lead with 5 years of experience in development of new user-facing features using different technologies. He has worked on React, Redux, Redux-Saga, JavaScript, HTML, CSS developing web applications.

Oleksandr Zhytnyk is backend and smart contracts developer with experience in Node JS, Solidity and C++ software development.

Genady Yoffe is an experienced analyst with PhD in Mathematics. He has a proven ability to design and implement efficient multithreaded (multicore) and massively parallel (CUDA) solutions to models with high computational complexity. 

## Team code repositories

https://github.com/peeranha

# Additional Information

Peeranha is an alumni of the first [Filecoin Techstars Accelerator](https://www.techstars.com/accelerators/filecoin).

Our team was referred to Filecoin Devgrants by Hunter Treseder from FFDWEB.

The best emails for communication about the proposal are sergey@peeranha.io and slava@peeranha.io

Demo: https://www.youtube.com/watch?v=Bvt42RqWFKc

**Comment by ErinOCon** [comment]
Hi @sergeyi23, thank you for your proposal! This grant is currently under review. We expect to be in touch next week with an update.

**Comment by sergeyi23** [comment]
> Hi @sergeyi23, thank you for your proposal! This grant is currently under review. We expect to be in touch next week with an update.

Thank you, @ErinOCon . Looking forward to it.

**Comment by ErinOCon** [comment]
HI @sergeyi23, thank you for your patience as we completed our review and for connecting with our team! Before considering future support for your work. we would like to see additional progress since your start with the accelerator program. 

Please feel welcome to re-apply once the project has made more progress. Wishing you and your team all the best as you continue building!

**Comment by sergeyi23** [comment]
> HI @sergeyi23, thank you for your patience as we completed our review and for connecting with our team! Before considering future support for your work. we would like to see additional progress since your start with the accelerator program.
> 
> Please feel welcome to re-apply once the project has made more progress. Wishing you and your team all the best as you continue building!

Hi @ErinOCon, thank you for reviewing our proposal and the feedback!
