### ISSUE TITLE
Open Grant Proposal: Galapago - Your Future Metaverse NFT Solution

### ISSUE THREAD

**Issue by ChainingAU** [filecoin-project/devgrants#913]
# Open Grant Proposal: `Galapago - Your Future Metaverse NFT Solution`

**Name of Project:**
Galapago
**Proposal Category:
`app-dev`
**Proposer:** `ChainingAU`

**(Optional) Technical Sponsor:** `If you have previously discussed this project with a member of the IPFS or Filecoin project teams and they have agreed to be a technical sponsor, include their name and/or github handle here`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Please respond with either "Yes" or "No"
Yes
# Project Description
![SolutionDiagram](https://user-images.githubusercontent.com/101615358/186925774-297a3f60-f115-493b-bb6d-7333f03c5a79.png)

-	Galapago solution provides a metaverse NFT content platform leveraging blockchain smart contract that assists digital VR/AR content buyer and seller to transact with project Galapago coin based on their needs and create an ecosystem to facilitate the growth of metaverse industry.
-	Galapago solution also provides protection of content creators’ ownerships and IPs by using NFT capability on blockchain but stores actual VR/AR content on Filecoin network to ensure content creators are getting the fair return they deserve to encourage growth in metaverse content space.

## Value

The benefit of getting this right is Filecoin ecosystem can be one of the leading players in Metaverse NFT industry. Given that Galapago will be the first of kind Metaverse NFT marketplace leveraging Filecoin decentralised storage solution, we are very confident that we will be able to make a huge impact to Filecoin when we launch.

The risks of not getting right is losing the opportunity in the growing Metaverse NFT market and fall behind other decentralised storage solution in the market.

Technical risk is low, Galapago project aims at integrating into Filecoin storage solution instead of centralised storage would be our top priority if we can successfully receive the grant for implementing such feature.
Risk in scaling up the market share and presence could be one of the risks and difficulties when launching into the market.

## Deliverables

Galapago project will create an online marketplace such that VR/AR content creators and buyers can buy and sell relevant contents in the form of NFT. This marketplace acts as the platform to facilitate and encourage creation of more quality VR/AR contents to support the development of the Metaverse. 
Buy and sell in the marketplace is supported by blockchain with register users using Galapago coin to trade with each other.
VR/AR content is rather large in size and the storage is supported by Filecoin decentralised storage solution.
We will be leveraging both stateless and stateful smart contracts to serve the requirements of minting NFTs for metaverse content and marketplace trading activities.
1.	Mint NFTs with content stored on Filecoin:
-	When seller fills in the web form asking for content metadata and upload the content via Filecoin integration to act as storage, the digital asset file will be uploaded.
-	Follow by metadata JSON to be uploaded and pinned to assets stored in Filecoin. This order needs to be followed.
-	User then puts the sha2-256 hash part of the metadata JSON inside the metadata hash field of NFT asset (representing the NFT generated as part of the mint process).
-	Finally, user puts the asset Filecoin URI of metadata JSON in URL field of NFT.
2.	Marketplace trading activities:
-	When seller places an item for sell on the marketplace, it creates a stateless smart contract account which stores the items he/she is selling.
-	When a buyer buys from the contract account, these high level conditions need to be met: 
o	a buyer would like to purchase the item (opt-in to the contract), 
o	the contract will send one asset, 
o	and the buyer will send the amount set by seller in the contract in Galapago coins.
-	The seller can withdraw from the contract account when Galapago coins are sent by the buyer and pays the transactions fee.
-	The smart contracts are atomic which means all transactions will fail if one of them fails.

## Development Roadmap
2022 Sep - Oct: Web Application Front-End UI Enhancement on existing blockchain solution 
-	Milestone funding required: USD$30,000
-	Team member details: Front End Dev *1, Backend Blockchain Dev*1
-	Enhance front-end web application portal UI to provide a better user experience.
-	Complete the build of Galapago marketplace that allows users to mint/trade NFT
-	Complete the marketplace integration where user can create AR/VR content

2023 Nov - Dec: Galapago marketplace integration with Filecoin
-	Milestone funding required: USD$30,000
-	Team member details: Front End Dev *1, Backend Blockchain Dev*1
-	Integrate NFT media content storage with Filecoin.
-	Marketplace user is able to upload NFT media content to Filecoin storage network.
-	Marketplace user is able to retrieve and download NFT media content from Filecoin storage network.

## Total Budget Requested
USD$60,000
Please refer to Budget Table.

# Team
## Team Members
Wenjing Wang
Fan Hui

## Team Member LinkedIn Profiles
https://www.linkedin.com/in/vivian-wang-94657920/
https://www.linkedin.com/in/jackhui88/

## Team Website
https://galapago.app/

## Team code repositories
https://github.com/ChainingAU/Galapago.git

**Comment by jenks-guo-filecoin** [comment]
@ChainingAU is this an Australia based project? 

Can you please classify your project type? I think this should be an "app-dev" project.

**Comment by realChainLife** [comment]
@ChainingAU thank you for the proposal. Can you also provide an overview of the Galapago coins cryptoeconomics model, as well as how, if at all this project is related to the NFT liquidity protocol services shared on your project website?

**Comment by ChainingAU** [comment]
> @ChainingAU is this an Australia based project?
> 
> Can you please classify your project type? I think this should be an "app-dev" project.

Yes @jenks-guo-filecoin  this is an AU based project and we have updated the category to 'app-dev'

**Comment by ChainingAU** [comment]
> @ChainingAU thank you for the proposal. Can you also provide an overview of the Galapago coin cryptoeconomics model, as well as how, if at all this project is related to the NFT liquidity protocol services shared on your project website?

Hi @realChainLife Galapago project actually breaks into below 2 capabilities:
1. NFT marketplace which we pitched for funding for improvement
2. NFT lending protocol which is on our development roadmap

In terms of cryptoeconomics model:
1. NFT marketplace - is based on transaction fee
2. NFT lending protocol - is based on yield difference between interest rate collected from loan and interest rate paid to liquidity providers. Transaction fee is also part of the revenue stream.

The Filecoin dev grant application we applied is more relevant to NFT storage solution with our first capability 1. NFT marketplace hence we have not included our point 2. capability in the project plan for Filecoin application, however we do have that capability on our development roadmap. Point 2 capability is more like a DeFi capability on top of Point 1 capability.

**Comment by ErinOCon** [comment]
Hi @ChainingAU, thank you for the additional information. We will be in touch if there are further questions.

**Comment by ErinOCon** [comment]
Hi @ChainingAU, thank you again for your interest in our grants program. We will not be proceeding with a grant at this time as grants of this size typically require additional time and development with a growing user base. 

Wishing you and your team all the best as you continue building!
