### ISSUE TITLE
Minting Engine for Hedera Hashgraph - HashGuild

### ISSUE THREAD

**Issue by danielHype** [filecoin-project/devgrants#914]
# Open Grant Proposal: `Minting Engine for Hedera Hashgraph`
**Name of Project:** `HashGuild's Minting Engine for Hedera Hashgraph`
**Proposal Category:**  `app-dev`
**Proposer:** `Daniel W. - datproto`
**(Optional) Technical Sponsor:** `hipiyushhere / Piyush`
**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** `Yes`
# Project Description
The NFT ecosystem on Hedera is currently blooming. While most NFT markets are being down due to the current bear market, new projects are entering Hedera on daily basis - looking to mint their projects. Not only collectible projects are entering, but individual creators as well as corporations - most of them are not technical.
As an infrastructure provider, we as the HashGuild team are helping those to mint free-of-charge since early on (January 2022), however know, that this is not sustainable nor friendly for adoption. Looking with a vision how to onboard the next billion people to Web3, an easy-to-use and accessible tooling needs to be developed to make minting easy - especially for non-technicals.
The solution proposed is open-source dApp, hosted, maintained and extended by the HashGuild team, which allows for the following:
1. Easy wallet connect
2. Creation of 1/1 NFTs as well as of collections through an accessible interface
3. No technical knowledge required 
4. A lot of documentation on how to use the application to allow for non-technical adoption

## Value
If such a dApp is built, this allows for mass adoption of users to NFTs. 2021 has already shown, that NFTs have made Web3 well-known - however, due to it being mostly on Ethereum - inaccessible for most persons due to the high gas fees. Hedera comes with an low-cost and carbon-negative approach - well-setup for new joiners.
This solution democratizes access to NFTs and Web3, without limiting it to the 27 million developers on Earth - most of them not being artists.
The risk lies in the early-stage of Hedera as a network itself as well as getting the UI and UX right. A 85 year old 'Grandma', painting infront of a TV, should be able to use that product and create own NFTs.
## Deliverables
The minting engine will allow logging in with a wallet and allow users to upload and manage their art works. The storage of the art as well as the metadata is utilizing fully automated IPFS/ Filecoin.
**Specification and Functionality of the finished software**
* An Open-Sourced repository for Users to build frictionless into their applications
  * Infrastructure to mint directly by only connecting a wallet, uploading an artwork and setting the metadata in an explained manner (1/1 NFTs)
  * Users can connect their wallet
  *  Users see the associated balance needed to mint their NFTs as well as instructions how to top up their balance
  *  Users can upload their artwork via Mobile or Desktop
  *  Artwork Data is directly stored on IPFS
  *  Users can enter the respective information which is stored as the metadata
        * Eg. Description, Attribute Data, Royalty Fees
  * Future different wallet support to show different options and preventing a monopolistic infrastructure
* The opportunity to mint collections with an integrated randomizer of assets (large collections and B2B use cases)
* Allowing to mint all types of NFTs, including Image NFTs, Video NFTs as well as 3D NFTs
* Integration into the HashGuild marketplace to demonstrate what can be done with the engine
* Documentation material & extended and ongoing support for new joiners to help and accomondate their first steps within this new World
## Development Roadmap
The roadmap below illustrates the development work, the team necessary and the funding required to complete.
| Functionality      | Team required | Funding required     |    Timeline |
| :---        |    :----   |          :--- |  :---- |
| **1. UI & UX Design**
Important to the success of the project is a neat and clean user experience, to allow for everyone to utilize this engine. Proper emphasis is being laid on understanding the background without being too technical and to demonstrate the different steps required     | 1x UI and 1x UX Designer, 1x Product Manager to conduct Interviews | $9,000   | 3 Weeks, 22th August until 9th September 2022  |
| **2. Building Engine Code**|
| The main functionality is being built in this milestone. Emphasis is being laid on covering the proposed functionality and allowing connection via a  Hedera wallet.   | 1x Frontend Engineer, 2x Backend Engineers      | $25,500      | 12th September until 28th September 2022 |
| **3. Integrating into HashGuild marketplace with video documentation**|
| To demonstrate the quick getting-up-to-speed, the engine is built into HashGuild marketplace. The development is video-recorded and explained so others can do the same.   | 1x Frontend Engineer, 1x Backend Engineers, 1x Developer Advocate        | $5,500    | 29th September until 5th Oktober 2022 |
| **4. Documentation of Repository as well as how to use and why to mint**|
| Core to the success is the documentation and easy-to-undestand guidelines for newcomers to the Web3 ecosystem - together with professionals this is achieved   | 1x UI Designer, 1x Copywriter        | $5000      | 29th September until 11th Oktober 2022 |
## Total Budget Requested
The total budget requested is the sum of the budgets above, totalling to $45,000.
## Maintenance and Upgrade Plans
The HashGuild went through the [Outlier Ventures program](https://outlierventures.io/meet-our-hedera-base-camp-cohort/) and is setup for the long run. While VC-backing is no guarant for success, it shows the pre-selected skills and the will and passion to achieve greatness. We see democracy and accessiblity of Web3 as a key obstacle to mass adoption and are joining the fight to change that. The repository will be actively maintained and the community will be incentived to commit new functionality as well as to integrate into their systems.
# Team
## Team Members
Daniel W. - Head of Product and Design, Co-Founder of HashGuild
Marcel S. - Head of Operations, Co-Founder of HashGuild
Alexander S.- Head of Technology, Founding Team HashGuild
Lawrence S. - Head of Community, Founding Team HashGuild
## Team Member LinkedIn Profiles
The team is currently not doxxed to the community but plans are to change that End of August. Nonetheless, we provide one LinkedIn profile here of Daniel, to show the seriousness:
[LinkedIn Daniel W.](https://linkedin.com/in/daniel-wintermeyer)
## Team Website
[HashGuild Marketplace](https://hashguild.xyz)
[HashGuild Information](https://hashguild.xyz/information)
## Relevant Experience
The team has a lot of experience in building technical infrastructure. While leading a software agency in the Web2 world, emergence and the possibilities lead the team to join the ecosystem and start building. By now, we’ve built several applications clients within the ecosystem and are fulltime in HashGuild since early this year.
The team is right to build this engine, as
1. We have the technical abilities to complete the project
2. We know what it takes to build projects for success
3. HashGuild has the reach and relevance to promote the open-sourced repository to be adopted and used by the broader community

Alex and Daniel are engineers and entrepreneurs, having build several technical projects by now for clients and founded several projects by now. While Alex is more proficient in the backend, Daniel will take care of the frontend. With Marcel and Lawrence, we have the expertise to promote it to new users and create in-depth guides and video-content for non-technicals.
## Team code repositories
Most of the team repositories are private - we are very happy to share them on request so developer advocates can see what we are capable of building. Nonetheless, we already started in our exploration doing the tests regarding implementation of IPFS and the Hedera network.
# Additional Information
*How did you learn about the Open Grants Program?*
We are Berlin based and Daniel, Head of Product, attended the Filecoin and IPFS event prior to NFT Berlin. An entertaining and insightful discussion later, Daniel learned a lot about IPFS and what is upcoming - as well as about the grant program.

*Please provide the best email address for discussing the grant agreement and general next steps.*
daniel@hashguild.xyz - Mail from Daniel, Co-Founder & Head of Product @HashGuild

*Please include any additional information that you think would be useful in helping us to evaluate your proposal.*
The HashGuild team is in for the long run - and looking for this strategic partnership and grant to build alongside with the IPFS team. We are looking forward to the upcoming exchanges and are grateful for the opportunity to apply.

**Comment by ErinOCon** [comment]
Hi @danielHype, thank you for your proposal! We recommend checking out nft.storage for data storage.

This grant has been approved! We will follow up with an email to discuss next steps.

**Comment by ErinOCon** [comment]
Hi @danielHype, just checking in to ensure you have received my emails. Please let me know if you are having any trouble receiving them or if you have any questions.
