### ISSUE TITLE
Next Step Microgrant:  GemGroove Music Minter

### ISSUE THREAD

**Issue by Hderek22** [filecoin-project/devgrants#915]
### 1. What is your project? (max 100 words)

A user friendly DApp for musicians to turn their songs into NFT's

### 2. Project links
  
Link to Github repo:https://github.com/Hderek22/Music-NFT-Minter
Link to demo or website, if applicable: https://ethglobal.com/showcase/gemgroove-music-minter-xkfyn

License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

     - The NFT Storage API is used
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

     - I will hook up to NFT Storage's API and allow the user to mint their songs into NFT's with on click of the button.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

     - Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

     - Yes
     
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

     - It has been submitted and was awarded  'Storage Wizard' award.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

     - I am the only person working on the project
          - Derek Hall
          - Hderek22@icloud.com
          - https://github.com/Hderek22
          - I am flying solo on this one!

* How did you learn about our microgrant program?

     - I received an E-Mail suggesting I apply after I was noticed by one of the hackathon judges
    
* If your project was created as part of an event or hackathon:
  * What was the name of the event? 
     - Metabolism
  * Please link to your hackathon submission
     -  https://ethglobal.com/showcase/gemgroove-music-minter-xkfyn

**Comment by Hderek22** [comment]
Thank you very much for your consideration!

**Comment by ErinOCon** [comment]
Hi @Hderek22, thank you for your proposal! Can you provide more detail on the next steps you will take for this project? How will your project improve over the next three months?

**Comment by Hderek22** [comment]
Hello,

Many decisions are still yet to be decided. Here is the bare minimum as to what is planned to be completed in the next three months.


First 30 days-
	-Backend details and design
		-establish API connectivity to NFT Storage.
		-NFT marketplace API’s established with connectivity built in for end user.
		-tokenomics planning and costs built in.
Days 31-60-
	-Front end
		-establish look and feel of the front end.
		-establish features of front end
		-create GemGroove emblem.
		-Deploy final GemGroove app
Days 61-90
	-Marketing
		-plan built and launched

Please let me know if this is what you are looking for.

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
