### ISSUE TITLE
Next Step Microgrant: Polydocs Dynamic Immutable Documents EIP

### ISSUE THREAD

**Issue by rhdeck** [filecoin-project/devgrants#917]
*Updated with additional hackathon prize recognition from IPFS/Filecoin*

### 1. What is your project? (max 100 words)
Smart contracts are increasingly used for managing the allocation of digital assets. These assets are more complex than the cash or deeds we sometimes use for analogies. Intellectual property involves rights and responsibilities. Financial instruments require acceptance on both sides. Communities need agreement on government by norms and rules.

The articulation and acceptance of these terms should be a first-class consideration for those creating digital assets and services. That's why we made Polydocs.

https://github.com/statechangelabs/polydocs
https://polydocs.xyz

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

The core insight of Polydocs is at the intersection of the decentralized ledger and decentralized storage. Every smart contract should go with a smart document that regulates the responsibilities of parties involved in it.

The purpose of the Polydocs EIP is to standardize the way these are connected, and to demonstrate IPFS CIDs as the best practice for defining immutable, trustable documents. 
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We created the Polydocs technology and some template contracts, but to make this truly useful it should be a standard that everyone can incorporate into their smart contracts. We want to submit this as an open-source Ethereum Improvement Proposal so that this functionality can be composed into others. Our Polydocs contracts would be offered as a reference, but be open-source so everyone can use this technology without concern for their intellectual property rights. 
 
### 4. Is this project open source?
Yes, Polydocs code is under MIT License, and the EIP is definitely open-source

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes. We plan to complete this work in October. 
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes. 

### 7. Links and submissions
We submitted to HackFS 2022 and placed as a finalist https://ethglobal.com/showcase/polydocs-1oas6. 
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
   1. Ray Deck ray@raydeck.com  @rhdeck Developer
   2. Akshay Rakheja rakheja.akshay@gmail.com @akshay-rakheja Developer
 
* How did you learn about our microgrant program?
We participated in an earlier hackathon with a different team where we won an IPFS prize and participated in the next-steps program. We are really excited about the potential for extending our work on this on the open-source side to make a difference for the web3 community

* If your project was created as part of an event or hackathon:
1. **HackFS 2022 finalist**: https://ethglobal.com/showcase/polydocs-1oas6. 
2. **Polygon Buidl It Prizewinner** (entry was an evolved, gasless version) won IPFS/Filecoin, Polygon prizes.

**Comment by akshay-rakheja** [comment]
Hi @mishmosh ,

The core of Polydocs is putting legal documents on the decentralized web. We make use of the immutable quality of CIDs so 
that people can trust that it is the exact document that they signed. Putting documents on the decentralized storage means that all parties have the same view of the documents that they agreed to anchored by an identifier that doubles as a hash which we record on-chain. Every legal document should be on IPFS. 

We see a future in which millions of agreements can be made on thousands of templates all stored and modified on IPFS.
IPFS also opens new value for legal agreements that was not possible with siloed or secret storage. Representing versions as merkle chains in the form of CARs in which each document has a link to the previous would make negotiations clearer and remove doubt as too intent. Lots of lawyers think web3 just means blockchain. Polydocs shows the central role of IPFS in the decentralized web of legal tech.

After winning HackFS and a IPFS pool prize at Polygon’s Buidl It Hackathon, we are seeking a grant to extend this work to make it a primitive which tightly connects blockchain with decentralized storage on IPFS.

**Comment by ErinOCon** [comment]
Hi @akshay-rakheja, thank you for the additional information. This grant has been approved! Look out for an email to confirm payment details.

**Comment by ErinOCon** [comment]
Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
