### ISSUE TITLE
Next Step Microgrant: Slack IPFS App

### ISSUE THREAD

**Issue by tolgayayci** [filecoin-project/devgrants#918]
### 1. What is your project? (max 100 words)
This app allows you to simply upload or view files to IPFS via web3.storage in Slack. While there are many tools for classic web2 storage solutions on Slack, I couldn't find an application that includes web3 solutions and IPFS.

The number of people using Slack daily exceeds 10 million. With this microgrant, I aim to bring new functions to this application and bring the IPFS ecosystem together with Slack.

### 2. Project links

[https://github.com/tolgayayci/slack-ipfs-app](https://github.com/tolgayayci/slack-ipfs-app)

In the repository, you can view other screenshots of the bot's usage.

<img width="1081" alt="Screen Shot 2022-08-28 at 21 55 56" src="https://user-images.githubusercontent.com/40897846/187091854-706f99ef-9055-48d5-8e19-b7bae33fb591.png">

License:

I confirm that the **bot will be released as open source** under either MIT, APACHE2, or GPL licenses after basic development is complete.
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

1. This app uses [Web3 Storage](https://web3.storage) to upload or display file from IPFS
2. User doesn’t need to use any command to upload, the application will ask automatically the user if he wants to upload the file to ipfs 
3. User can use /display {ipfs_hash} to display a file on IPFS
4. User can use /help to learn how they can use this app
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. Users will be able to use their web3.storage accounts by entering their API keys.
2. Statistics will be displayed on the main page of the application, and users will be able to quickly view the latest files they have uploaded or viewed.
3. Serverless AWS Lambda solution will be available for those who want to run the application on their own servers
4. A detailed readme will be prepared
5. The application will be open source under the MIT license.
6. Will apply for publishing to Slack app directory

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, I agree
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
  * No, it didn’t began at hackathon nor submitted for any Protocol Labs prizes.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  * Tolga Yaycı - tolgayayci@protonmail.com - [github.com/tolgayayci](http://github.com/tolgayayci) - Developer

* How did you learn about our microgrant program?
  * I noticed it thanks to GitHub repo while reviewing IPFS for my project

* If your project was created as part of an event or hackathon:
  * No, project didn’t created as part of even or hackathon.

**Comment by tolgayayci** [comment]
Yes, I confirm

**Comment by ErinOCon** [comment]
Hi @tolgayayci, it looks like your reply may have cut short. Please let me know if you have any questions!

**Comment by tolgayayci** [comment]
Hi @ErinOCon, thanks for your review.

I'll confirm all the steps which is outlined in item four. I will complete all the steps in a month and asking feedback from the community. After I collect feedbacks I will finalize the software and make that deploy readiness on AWS serverless and prepare all the documentation for the usage.

At this stage I have not any questions, I've read all microgrants guidelines and reviewed the grants so thanks for this opportunity for developers. If I have questions at later stages, I will ask you, thanks for your help!

**Comment by ErinOCon** [comment]
Hi @tolgayayci, it looks like this project is in its early stages. Can you send a link that showcases the prototype?

**Comment by tolgayayci** [comment]
Hi @ErinOCon, thanks for your comments. You are right, the project in early stages. There are screenshots of the current functions in the github repo I shared. The application works on slack, it needs to be published in the slack app directory for everyone to download and use, but I wrote this for my milestones because the plugin was not completed.

At this stage, the following features are working;

- Upload File (When user uploads a file, bot detects and ask if user want to upload to IPFS.
- Display File (User can query any content on IPFS with hash)
- Help Section

I mentioned the missing features of the bot in the fourth section and I guarentee to complete them.

If you want to try these features I need to add you on Slack channel because as I said bot just needed to custom install for servers at this stage. Also, I can make a screen recording to showcase features.

I would like you to give your e-mail address to add to the slack channel or I can add the prototype video as a link.

I will be eagerly waiting for your reply!

**Comment by tolgayayci** [comment]
Hi @ErinOCon, hope you are well!

Is there any update about the process?

Thanks

**Comment by ErinOCon** [comment]
Hi @tolgayayci, thank you for your time and patience with this proposal! The grant has been approved! Look out for an email with payment details.

**Comment by ErinOCon** [comment]
Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by tolgayayci** [comment]
Hey @ErinOCon , I'm preparing my final report, I'll post it in three days, your support has been very helpful, thank you again, I'll edit this answer when I post it.

**Comment by ErinOCon** [comment]
Hi @tolgayayci, do you have an update on your report?
