### ISSUE TITLE
Next Step Microgrant: IPFS-Certus

### ISSUE THREAD

**Issue by brhaguste** [filecoin-project/devgrants#919]
### 1. What is your project? (max 100 words)

IPFS-Certus is a platform that aims to provide a decentralized reliability environment by storing the certificates given at the end of the training programs in the IPFS environment. The generated certificates and their metadata will be transferred to the IPFS environment (first of all, I intend to use an IPFS pinning service), and then these certificates can be directly queried from IPFS with the given unique code. I'm thinking of doing this project with IPFS integrated using Laravel framework.### 2. Project links
  
Link to Github repo: https://github.com/brhaguste/IPFS-Certus
Link to demo or website, if applicable:
License:
 
MIT License 

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
In this project, both the file and metadata information of the certificates will be kept in IPFS, thus providing an environment of trust for certificate users and validators.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

While developing this project, I will need to use a pinning service and it may have a high cost as I will undergo extensive testing. There are also infrastructural needs such as the cost of hosting the framework. I am also planning to use CoreUI pro themes while using Laravel, this also has costs.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes, of course

### 6. Does your proposal comply with our Community Code of Conduct?

Yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
- Sjoerd Saarloos
- brhaguste@yahoo.com
- 
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @brhaguste, thank you for your proposal! Before considering a grant for this project, further progress is needed, including a built prototype. As a next step, you may want to consider participating in a hackathon! 

Wishing you all the best with your project!

**Comment by brhaguste** [comment]
Hi @ErinOCon,
I thought I had uploaded the prototype, now I uploaded it and opened a new microgrant application at [#999](https://github.com/filecoin-project/devgrants/issues/999)
