### ISSUE TITLE
Integrating FileCoin Protocol with Open Source Libraries

### ISSUE THREAD

**Issue by ARUNMANNURU** [filecoin-project/devgrants#920]
**Integrating FileCoin Protocol with Open Source Libraries**

**Name of Project: Integrating FileCoin using Apache Camel**

**Proposal Category:** `integration-adoption` , `docs` , `green`  Learn what these categories are here: https://github.com/filecoin-project/devgrants/tree/master/open-grants#readme

**Proposer:** `Arun Mannuru`

**(Optional) Technical Sponsor:** `N/A`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** `Yes` 

# Project Description

- In order to simplify accessing FileCoin protocol in any web application, We need to create a library which enables developers to connect any communication channel easily. 
- Apache Camel is open source framework which helps developers to connect any communication channel easily ( It does have enterprise integration pattern support ). My idea is to simply the development process, with the help of camel integration. 
-  Some of the examples of Apache Camel are, It does provide dependencies for Azure Data Storage/ AWS S3 etc.., Developers just need to pass the connection properties to connect. 

## Value

                Building open source library with Camel definitely helps consumers to quickly adapt the FileCoin protocol. This helps to dev teams to just plug and play and test the results. This is a way to start strengthening the community by simplifying the development process. 

There is no risk in creating the library within Apache Camel, which helps developers to adapt this protocol easily. 

## Deliverables

We can deliver a library, which helps developer to plug and play with FileCoin protocol for their web applications. I just thought of sharing my ideas, Need to do more research further on various things before committing for timelines. 

## Total Budget Requested

Not yet finalized the plan. Thought of submitting this idea and see if there is any appetite in this area. 

## Maintenance and Upgrade Plans

Not yet finalized work in progress. 

# Team

## Team Members

`Arun Mannuru`

## Team Member LinkedIn Profiles

[https://www.linkedin.com/in/arunmannuru/]

## Team Website

Work In Progress. 

## Relevant Experience

Work In Progress. 

## Team code repositories

# Additional Information
  I was there in dWEB conference. Learned by networking with other team members. 
 arunm057@gmail.com
 Here is a sample apache camel implementation [https://camel.apache.org/components/3.18.x/azure-storage-blob-component.html]

**Comment by ErinOCon** [comment]
Hi @ARUNMANNURU, thank you for being in touch! Generally speaking, a full proposal is required to determine if a project would be eligible for our grants program. With this in mind, it may be helpful to know that projects of this nature usually include parties that are deeply integrated with Apache Camel teams/updates.

If you have an interest in showcasing your work, participating in a hackathon can be a great next step!
