### ISSUE TITLE
Next Step Microgrant: Web3 Archive

### ISSUE THREAD

**Issue by web3-archive** [filecoin-project/devgrants#921]
### 1. What is your project? (max 100 words)
With Web3.Archive.xyz, you get all the benefits of decentralized storage technologies with the frictionless experience you expect in a modern archive workflow. Under the hood, Web3.Archive makes data accessible to users over the public IPFS network with optional encryptions and/or program languages.

### 2. Project links
  
Link to Github repo: https://github.com/web3-archive/Web3.Archive
Link to demo or website, if applicable: https://web3-archive.xyz/ 
License: https://web3-archive.xyz is licensed under the MIT License https://github.com/web3-archive/Web3.Archive/blob/main/LICENSE 

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
This project is build with using web3.storage & IPFS as core to file, archive and retrieve users content. 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
More options will be added with selective encrypted https://estuary.tech/ storage/archive alternatives.  Increasing user base with providing frictionless smoothness and reliability. Improving UI .

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Hans Landesmann , info@web3-archive.xyz , https://github.com/web3-archive , Dev
* How did you learn about our microgrant program?
Via Filecoin website.
* If your project was created as part of an event or hackathon: No.
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) 
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
