### ISSUE TITLE
Next Step Microgrant: Pixelverse

### ISSUE THREAD

**Issue by iapixelverse** [filecoin-project/devgrants#922]
### 1. What is your project? (max 100 words)
PixelMetaverse is a self-identity pixel metaverse. Everyone can choose their favorite picture to pixelize, we provide a variety of algorithms and various attributes, users can upload pictures to IPFS/Filecoin and mint into nft in polygon, which represents your presence in the Metaverse identity. This self-produced identity pixel is like your avatar on Facebook, Twitter. It's your external show pic.

### 2. Project links
  
Link to Github repo:
https://github.com/iapixelverse/Pixelverse
Link to demo or website, if applicable:
Not yet.  But you can look the video in our hackathon submission
License: MIT 

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
 We use various image processing algorithms to pixelize the image, and use IPFS/Filecoin's nft.storage to store the user's metadata in a decentralized storage network and perform Mint into nft in the polygon network

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
 We will use this grant to accomplish the following:
1. Modify the contract to create an IPFS/Filcoin based content storage space with a pixel identity
2. optimize website
3. Add user login function, build my nfts & my data & my activitys

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes

### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
   https://devpost.com/software/pixelmetaverse

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  ShengShi, Product Design & Team Leader , iapixelverse@outlook.com, https://github.com/iapixelverse
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  [Polygon BUIDL IT : Summer 2022](https://buidlit.devpost.com/)
  * Please link to your hackathon submission
  https://devpost.com/software/pixelmetaverse

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by bonggerbb** [comment]
@ErinOCon , So happy for this! Waiting for your payment details!

**Comment by ErinOCon** [comment]
Hi @iapixelverse, I have sent an email regarding the status of your payment. Please let me know of questions.
