### ISSUE TITLE
Next Step Microgrant: Launchpad for NFTS

### ISSUE THREAD

**Issue by nftdevking** [filecoin-project/devgrants#926]
### 1. What is your project? (max 100 words)
Launchpad for NFTS - https://nftlaunchpad.dev/ connects digital artists with their audience by providing a standard primary NFT market with both presale and non-presale options that fairly/randomly distribute collection NFTs among the buyers

### 2. Project links
  
Link to Github repo: https://github.com/nftdevking/launchpadnft
Link to demo or website, if applicable: https://nftlaunchpad.dev/ 
License: MIT 
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
The project data is build on IPFS

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
More dedicated dev time, Improvements FullStack Repo with/on: cleaning code on backEnd and frontEnd, extending browser support, expanding user base with facilitating simple upload and installations for launchpad for nfts for all interested.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
Not Available.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Jean Thomassen , dev@nftlaunchpad.dev , https://github.com/nftdevking , Dev Chief
* How did you learn about our microgrant program?
Surfing on IPFS
* If your project was created as part of an event or hackathon:
No
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @nftdevking, thank you for your proposal! Can you confirm how you are using IPFS? For example, are you using nft.storage?

**Comment by nftdevking** [comment]
Hi Erin, using Chainrand and web3.storage.

**Comment by ErinOCon** [comment]
Hi @nftdevking, we will not be proceeding with a grant for this project. After reviewing the code, it does not appear that our tech stack is essential to supporting your future work. Thank you for your interest in our grants program. Wishing you all the best with your project!

**Comment by nftdevking** [comment]
Hello @ErinOCon that would be silly as code review interpretation to state that IPFS is not as tech stack essential in the project or for that matter the storage of the data... I would recommend to review and change the participation rules and requests for the microgrants accordingly. I'm offended by your statement here with closing this as completed.
