### ISSUE TITLE
Next Step Microgrant : MintSelf 

### ISSUE THREAD

**Issue by rhyhammell** [filecoin-project/devgrants#927]
### 1. What is your project? (max 100 words)
MintSelf is a tool that can mint selfies into NFT and use this NFT to represents the person's decentralized identity in web3 . 
This will be the first to use a selfie as an expression of decentralized identity

### 2. Project links
  
Link to Github repo:
https://github.com/rhyhammell/mintSelf
Link to demo or website, if applicable:
Not yet, You can run and try it yourself

License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
We use IPFS/Filecoin to store the avatars and metadata taken by users. When the user clicks mint, these data will generate a unique tokenURL through IPFS/Filecoin to support us to mint into nft on the chain
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will use this funding to optimize the website, access the decentralized identity system, and add NFT.storage as a new storage method

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes

### 6. Does your proposal comply with our Community Code of Conduct?
yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  rhyhammell , web3 developer. rhyhammell@outlook.com, https://github.com/rhyhammell
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @rhyhammell, thank you for your proposal. Can you provide more specifics on the steps you will take over the next three months to improve your project? How will these steps advance MintSelf?

**Comment by ErinOCon** [comment]
Hi @rhyhammell, I hope you are doing well! Do you expect to have an update available this week?

**Comment by rhyhammell** [comment]
Hi @ErinOCon , Thank you for your reply, recently we are thinking about the development plan based on Mintself, the following will be the roadmap we will do next : 

1. Establish a decentralized identity data space with self-avatar, which will be realized with ceramic's did technology
2. Modify the storage bottom layer to NFT.storage, and support NFT implementation with nft.storage
3. Add self avatar attributes, enrich a variety of customizations, and create cid data of attributes with nft.storage
Looking forward to your reply!

**Comment by ErinOCon** [comment]
Hi @rhyhammell, thank you for the additional information and for your patience with our review. Since a unique, working prototype is a requirement of this grant program, we will not proceed with a grant for this project. Please be in touch with any questions.
