### ISSUE TITLE
Next Step Microgrant: IPFS for WordPress [Post FIL Singapore Hackathon]

### ISSUE THREAD

**Issue by Zhixuan0318** [filecoin-project/devgrants#928]
### 1. What is your project? 

IPFS for WordPress is an all-in-one plugin that provides powerful & comprehensive IPFS solutions for WordPress CMS. Everyone can now install it on their WordPress site and start to integrate IPFS features easily, as well as manage everything just by using one admin panel. 

#### Here is a features overview of the "IPFS for WordPress" plugin:

* APIs support for IPFS storage tools
* Media libraries for IPFS storage tools
* On-the-spot upload & retrieve for IPFS storage tools
* Lottie animation support for IPFS
* Elementor addons for IPFS integrations
* IPFS integration for WooCommerce
* IPFS image generation system
* IPFS Content Delivery Network (ICDN) for WordPress

>👋 This project is my submission for the **Web3 Infinity Hackathon** during the FIL Singapore 2022 and won **second place**. I had written a detailed description of my project and a full demo video on Devpost. Here is the link to the project's Devpost page: [**Click Here**](https://devpost.com/software/ipfs-for-wordpress)

### 2. Project links
  
Link to GitHub repo: https://github.com/Zhixuan0318/ipfs-for-wordpress

Link to project's Devpost page: https://devpost.com/software/ipfs-for-wordpress

Link to a full plugin demo video: https://youtu.be/4b-TclC-Wj8

License: **Open source with MIT license**, and will be available to download (on WordPress official plugin directory or plugin's GitHub repo) and install in WordPress CMS
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

The "IPFS for WordPress" plugin provides powerful and comprehensive IPFS solutions and features with the help of Pinata, Web3.Storage, and Nft.Storage connection.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

There are four major milestones to be complete with this grant:

#### ✔️ IPFS BLOG SYSTEM FOR WORDPRESS

> 💡 If everyone can easily run their Web3.0 blog site, isn't that cool? Especially building with a user-friendly CMS, WordPress.

After getting some inspiration from the [Mirror](https://mirror.xyz/) app (a web3.0 blogging platform), I designed and built an [IPFS blog engine](https://ipfs-blog-engine.vercel.app/#/) for the L2 Rollathon Hackathon this year May, at the same time having an excellent result in this hackathon. This motivates and inspires me further. Why don't I build an IPFS Blog System for WordPress, and by using this feature, everyone can now easily set up, build, run and manage their own decentralized Web3.0 blog site? In other words, everyone now has their own-managed "Mirror"!

The IPFS blog system will have visual editors, building blocks, elements library, full integration support with IPFS storage tools (Pinata, Web3.Storage, Nft.Storage), etc. This will definitely be an exciting upgrade for this "IPFS for WordPress" plugin!

#### ✔️ IPFS ELEMENT LIBRARY (ADDONS) FOR ELEMENTOR

I plan to come out with a library of elements (addons/building blocks) for Elementor which focus on building up a Web3.0 site and easily integrating all the IPFS solutions. When users install this plugin, they will automatically access all the addons on their Elementor website builder.

The most exciting plan is that IPFS element libraries for other WordPress website builders (such as WP Bakery, Divi, Oxygen, etc. ) will be released on this update.

#### ✔️ UPGRADED VERSION OF IPFS CDN

I will introduce more advanced and comprehensive features for the ICDN (IPFS Content Delivery Network) in the future. For instance, files preload function, advanced ICDN caching rules, ICDN cache rollback, security improvements, speed optimization, etc. ICDN will become more powerful in the upcoming upgraded version!

#### ✔️ AVAILABLE ON WORDPRESS PLUGIN DIRECTORY!

In the next release (with all the new features ready and checked), I will submit and publish the "IPFS for WordPress" plugin to the WordPress Plugin Directory. At that time, users can just search for this plugin in the WordPress Plugin Directory and directly install it for their WordPress site, much more faster and convenient! Plus, for future updates on the plugin, users will receive an update notification and can choose to manually update or enable auto-update for the plugin. 

<hr>

👇Here is a brief roadmap to achieve all the milestones above. However, this roadmap is based on the grant application being approved approximately in mid-Sept. If the approval is delayed, I will update the roadmap here accordingly.

| Timeline | Milestones |
| --- | --- |
| Sept - Oct | IPFS Blog System for WordPress |
| Oct - Nov |  IPFS Element Library for Elementor and other site builders |
| Nov - Dec | IPFS CDN Features Upgrade and Speed Optimisation |
| End of Dec | Final Checking & Submission for WordPress Plugin Directory |

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?
Yes.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

This project is submitted to the Web3 Infinity Hackathon, a FIL Singapore 2022 event: [Click Here](https://devpost.com/software/ipfs-for-wordpress)
  
### Additional questions:
Team Member:
Name: Tan Zhi Xuan
Email: t.zhixuan318@gmail.com
Linkedin: https://www.linkedin.com/in/tan-zhi-xuan-805836196/

* How did you learn about our microgrant program? The previous hackathon manager mentioned this grant program in the thank you email.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? Web3 Infinity Hackathon
  * Please link to your hackathon submission [Click Here](https://devpost.com/software/ipfs-for-wordpress)

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @Zhixuan0318, I hope you are doing well! Can you submit the report required for this project?
