### ISSUE TITLE
Open Grant Proposal: Storverse

### ISSUE THREAD

**Issue by vricale** [filecoin-project/devgrants#929]
# Open Grant Proposal: `Storverse`

![img](https://cdn.dorahacks.io/static/files/cover.jpeg)

**Name of Project:** Storverse

**Proposal Category:** `app-dev`

**Proposer:** vricale

**(Optional) Technical Sponsor:**

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Please respond with either "Yes"

# Project Description

As we all know, all data stored on IPFS and Filecoin is public, anyone can access it with CID. End users should encrypt his data before uploading. But sometimes it's inconvenient to encrypt on the end-user side. There are some applications that help users to encrypt and upload in a centralized way which means entire data may still be exposed to applications. We want to solve this problem by splitting and encrypting files in a distributed way.

Since data stored in IPFS and Filecoin lack metadata(CID is meaningless for other users), we want to provide a public file marketplace where data owners can share and sell their data while others can discover and pay to use their data.

https://user-images.githubusercontent.com/9106716/186823894-d3e56383-8bdb-4864-84eb-af4f6c4dec75.mp4

Storverse is built on SAO Network, SAO Network provides a decentralized storage protocol based on IPFS & Filecoin to increase the adoption of Web3 data storage and promote its ecosystem applications.

![Screen Shot 2022-08-28 at 3 30 06 PM](https://user-images.githubusercontent.com/9106716/187063093-2db9741d-c434-4b81-b6e7-999927f5bd31.png)

SAO nodes will provide basic services as follows:

- Application oriented services for customization and integration.
- Content cache for file access acceleration.
- Content encryption by a distributed encryption system.
- Verifiable attestation.

## Value
We have implemented the first version of SAO nodes with private data storage support and a file market demo application to demonstrate how users can upload and purchase file use rights.

Storverse provides an easy-to-use, privacy-preserving, and high-availability solution for end users to share content. Also, we plan to design an economic model for better incentives for SAO nodes and end users to attract more SAO nodes to provide storage services and more end users to share data, comment on content, and audit content on our platform. I believe the project will effectively improve the adoption of Filecoin.

## Deliverables

- All data will be stored on Filecoin/IPFS.
- Content Marketplace for free and paid content.
- Combine smart contract and IPFS/Filecoin storage to implement file copyright.
- Content Collection NFT - allows others to follow to get update notifications.
- File Socializing - owner, collection creator, user, and buyer can increase social engagement by following, sharing, and commenting.
- File Collaboration allows users to work on a file together.
- Incentive mechanism, designs an economic model which can maintain the balance of interest structure among SAO nodes, content producing user(uploader, collection creator), content audit user, and content consuming user. 
- Provide Soulbound Token, which can show the user's 'Data Influence' according to the user's engagement in Storverse.

### Milestone 1  Content Marketplace
2-3 weeks USD$5000

- Content encryption by distributed encryption system, for details please see https://github.com/SaoNetwork/sao-hackathon#encryptiondecryption-mechanism
- Content Marketplace for free and paid content.
- Deploy an ERC-721 NFT contract with our own custom logic added to support listing, purchase and claim.
- Combine smart contract and IPFS/Filecoin storage to implement file copyright.

Demo: https://hackathon-demo.sao.network/#/Space

### Milestone 2 Content Collection
2-3 weeks: USD$5000

- Content Collection NFT, users can collect files of the same topic into a collection and mint as an NFT. Others who are also interested in this collection topic can join and share collection ownership.
- Content Collection Collaboration, users who share collection NFT ownership can work together to manage collection content and share profit.

### Milestone 3 Content Socializing
2-3 weeks: USD$5000

- Content and collections can be easily discovered and located in the content marketplace.
- A social network for content owners, collection creators, content users, and buyers to easily manage, share or comment.
- Soulbound Token, which can show the user's 'Data Influence' according to the user's engagement in Storverse.

### Milestone 4 Incentive
1-2 months: USD$15000

- SAO node will get rewards
- Store content to get rewards
- Benefit from content audit
- Earn via DAO Governance
- Storage NFT, holders will get extra benefits

## Total Budget Requested
USD$30000

## Maintenance and Upgrade Plans

# Team

- **Hedra Labs**

## Team Website

Our website - https://sao.network

Twitter - [@SAONetwork](https://twitter.com/SAONetwork)

Medium - [@SAONetwork](https://saonetwork.medium.com/)

Discord - [@SAONetwork](https://discord.gg/q58XsnQqQF)

Email - [contact@sao.network](mailto:contact@sao.network)

## Relevant Experience

Hedra Labs is dedicated to supporting diversiform Web3 applications and mass Web3-natives by creating a storage protocol (SAO Network) and a decentralized autonomous organization (a storage DAO). We are a fully distributed team with all developers working remotely in the US, Canada, Singapore, South Korea, China, Czech, etc. However, we are holding the same goal to make our protocol and ecosystem applications more accessible. The core development team has rich experience in IPFS and blockchains. We have members who used to be technical directors of celebrated mining Pools, extensively experienced in blockchain and cryptocurrency mining. We have experts in architecture design, software engineering, smart contract deployment, and middleware tools development. We also have members who once served as core developers of public blockchains, crypto wallets, crypto mining pools, computing platforms, network security fields, and data protection areas. We have all been actively involved in the Filecoin ecosystem and another decentralized storage network for years. We’ve been powering Web3 storage at pretty awesome places and will continue doing so here in Hedra Labs.

## Team code repositories

https://github.com/SaoNetwork

# Additional Information

Our team always engages more skilled or creative people from all over the universe. No one can reach high ambition just by himself or herself. Nevertheless, by leveraging the team and various skills, we have the power and ability to create an outcome that’s bigger than the sum of its parts.

**Comment by vricale** [comment]
It's the successor of the previous dev grant https://github.com/filecoin-project/devgrants/issues/567, thanks for the time you spent reviewing it, and let me know if there are any more questions.
Best Regards,
Hedra Labs

**Comment by ErinOCon** [comment]
Hi @vricale, thank you for submitting your proposal. This grant has been approved! We will send an email to discuss next steps.

**Comment by ErinOCon** [comment]
Thanks @vricale! We have reached out using both your email address at [mark@sao.network](mailto:mark@sao.network) and your team email at [contact@sao.network](mailto:contact@sao.network).

**Comment by ErinOCon** [comment]
Hi @vricale, can you confirm receipt of my emails?
