### ISSUE TITLE
Next Step Microgrant: <Eden Protocol>

### ISSUE THREAD

**Issue by amoweolubusayo** [filecoin-project/devgrants#930]
### 1. What is your project? (max 100 words)

Eden (fka “Soil” in Developer DAO) is the ultimate talent coordination protocol for DAOs, providing a place where everyone can grow through work they love, thanks to our two-way person-project matching system. This system is Eden's core, built from an ML-driven bot, a platform-like interface, and some epic protocol-mechanics. 

Communities can integrate Eden into Discord, Slack, Telegram,... Think of it like a personal project scout that flags the most relevant individuals for projects and vice versa. Eden will open opportunities on all ends of the web3 ecosystem by streamlining overwhelming discord servers, convoluted onboarding processes and outdated notion tables. 

### 2. Project links
  
Link to Github repo: https://github.com/Soil-labs/soil-App-frontEnd
Link to demo or website, if applicable: https://eden-app-front-end-zeta.vercel.app/projects

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

We are using IPFS on Eden in these three ways:

1. Eden is using IPFS to create Soulbound NFTs that store the skillset of the endorsee. 
2. Eden is using IPFS on project creation. Specifically, when we store a new project on polygon, we store the project members, project description and other related project information.
3. Any project update visible on Lens Protocol is obtained from information stored on IPFS.

  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

**How will we improve our project with this grant**
The grant benefits this project in two primary ways

1. Helping with investigating the feasibility of further integration with IPFS 
2. Covering some of our total development costs on the road to the next version of Eden.

**What steps will we take to meet our objective**
We will organise a design + development sprint over the course of a month with two tracks. One will be focussed on further developing the use-caseses for which we’re already using IPFS. The other track will be used to explore, develop & test additionally interesting usecases 

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes  

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
1. [Alpha Demo video](https://share.descript.com/view/oXqRgLRzEZK)
2. https://github.com/Soil-labs/soil-App-frontEnd
3. ​​https://eden-app-front-end-zeta.vercel.app/projects
4. We are also live in DeveloperDAO

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

**Founders**

BluePanda#5982 | Miltiadis Saratzidis - Tech Lead
Miltos is a PhD-ML-Dropout with previous experience as a senior ML Engineer at multinationals & CTO of multiple startups. His combination of experiences with full-stack, ML, social graphs & solidity as well as exceptional leadership & managerial skills make him the perfect tech lead to realize our vision of building the world’s opportunity protocol. 

impactbilli#8647 | Tom Husson - Product Lead
Tom dropped out of his masters in Computer Science to build a 10-person [digital innovation consultancy](http://www.humain.ai/), which he sold. Among his clients were the 3 EU-institutions & various multinationals. His experience building & scaling a business in combination with innovative & strategic thinking with emerging technologies for large scale organizations make him the perfect product lead to realize our vision of building the world’s opportunity protocol.

**Core Contributors - those who spend at least 10h a week with us** 

Milo#7738 | Lolita Mileta
UI | Community | Research | Fundraising
Background: BS in Political Science & International Relations, PM Scrum Master in Sabre Corporation; UI designer; project facilitator
Linkedin: https://www.linkedin.com/in/lolitamileta

busayo#4524 | Olubusayo Amowe
Research & Collaboration
Background: BTech in Computer Science, Ethereum Foundation DevconV	Scholar Alum, Ex-Technical Writer MetisDAO, DevRel contributor Radicle, Contributor @ wbw3, Technical Grants Outreach @ Eden Prc
GitHub:[ https://github.com/amoweolubusayo](https://github.com/amoweolubusayo)
LinkedIn:[ https://linkedin.com/in/amoweolubusayo](https://linkedin.com/in/amoweolubusayo)

wiseTy#8689 | Tyrone Dunmore
Backend | Product
Upcoming CS graduate @ The University of DC; Community Manager @ Developer DAO; Backend & Product @ Soil Github:
GitHub:[ https://github.com/tyronedunmore](https://github.com/tyronedunmore)

exwhyzee.eth#1234 | Sundaram J
UX/UI
Incoming freshman and builder of @MetapassHQ & DesignJunction.xyz
Portfolio:[ www.sundaramj.tech](http://www.sundaramj.tech/)

sbelka.eth#3367 | Sergey Belyaev 
Frontend developer 
Contributor @ LW3 DAO, FrontEnd dev @ MyCoin 
GitHub:[ https://github.com/sbelka-1703](https://github.com/sbelka-1703)

Moiz#7516 | Moiz 
Solidity Developer 
Just graduated with a degree in computer engineering. 
LinkedIn: https://www.linkedin.com/in/moiz-lakkadkutta
GitHub:[ https://github.com/moiz-lakkadkutta](https://github.com/moiz-lakkadkutta)

Aayush Gupta#7870 | Aayush Gupta 
Blockchain Developer 
CS Graduate, Chainlink Community Advocate, Contributor LearnWeb3DAO 
GitHub:[ https://github.com/AAYUSH-GUPTA-coder](https://github.com/AAYUSH-GUPTA-coder)
LinkedIn:[ https://www.linkedin.com/in/aayush-gupta-20023b183/](https://www.linkedin.com/in/aayush-gupta-20023b183/)

Miral#6517 | Miral 
Frontend Developer 
Computer Engineering Degree, Freelance Frontend Developer, Contributor @GitcoinDAO @DevDao 
GitHub:[ https://github.com/miralsuthar](https://github.com/miralsuthar)

jengajojo.eth#5896 
Research & Outreach
Project Manager and Grants committee member in Banklessdao. Decentralization board at klimaDao. Other former roles in yearn.finance, raid guild. Data and Business Analyst in web2 
GitHub:[ https://github.com/jengajojo](https://github.com/jengajojo)

Tricelex#0703 | Emmanuel Okoye 
Blockchain Dev 
BSc Computer Science, Working in web2 fintech, Encode Solidity boot camp graduate 
GitHub:[ https://github.com/tricelex](https://github.com/tricelex) 
LinkedIn:[ https://linkedin.com/in/chuckzokoye](https://linkedin.com/in/chuckzokoye)

Adz#8404 | Adrienne 
Research | Outreach | Product 
10 years of strategy experience (consulting and corporate), then built two talent businesses in Asia (two exits), now a web3 consultant with Bankless Consulting (part of Bankless DAO) and active contributor to talent coordination and GTM. 
LinkedIn:[ https://www.linkedin.com/mwlite/in/adrienneyoungman](https://www.linkedin.com/mwlite/in/adrienneyoungman)

Alex1237#2487 | Alex 
Bot Wizard 
BSc and MSc in Computer Science. Aimed to grab a PhD position in EPFL but failed possibly due to GPA, like more than 3.8/4.0 -:(. Previous experience: Embedded System in Civil Engineering and FPGA. Jumped into web3 last year but failed to catch Defi Summer. Try my best to learn frontend and backend. They are sooo cool 
GitHub:[ https://github.com/myz1237](https://github.com/myz1237)

waxy#0208 | Eric
Blockchain Dev
FE This is my second career - previous: BA in music performance, Audio Engineer for 20 yrs, Production Manager for 8 yrs, General Manger for 2 yrs - all in the live events industry 20 yrs total (I was double duty) - current: YouTube Grad, 2.5ish yrs of full stack web dev., I just build
GitHub:[ https://github.com/e-roy](https://github.com/e-roy)

eloigil#4894 |  Eloi Gil Peiró 
Full Stack Developer 
Background: Industrial Design Engineering Graduate; Web Dev Teacher; Fullstack Dev @ European Commission project & Telecom company & Branding consultancy 
GitHub:[ https://github.com/heavensbee001](https://github.com/heavensbee001) 
LinkedIn:[ https://www.linkedin.com/in/eloigil/](https://www.linkedin.com/in/eloigil/)

Jonas 🇧🇪#9678 | Jonas Denil 
 UX/UI
UX designer by day, graffiti artist by night. Shooting film in de spare time I have.[ https://www.instagram.com/straatletters/](https://www.instagram.com/straatletters/)
https://www.instagram.com/jonasdenil/

Faina_Ivanovna#5781 | Erin Tupman
Grant Strategy | Wordcrafter
MA/PhD student; serial grant and scholarship recipient; Independent researcher of Siberian culture, language, and ecology; linguist on a team of coders to design and produce language production software for Russian.
LinkedIn: (To be updated soon)

* How did you learn about our microgrant program?
We learnt about it from our research about Filecoin

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  Our project was created and being used in DeveloperDAO

  * Please link to your hackathon submission
  Our bot is live on DeveloperDAO
  [Alpha Demo video](https://share.descript.com/view/oXqRgLRzEZK)

**Comment by ErinOCon** [comment]
Hi @amoweolubusayo, thank you for your proposal! Will this grant be open source?

**Comment by BluePanda-io** [comment]
I am really excited that we are here, I truly love the work from filecoin, and I want again to thank @amoweolubusayo for the incredible work connecting us to the filecoin community :)

**Comment by milo-27** [comment]
hey guys, following up on the proposal since it's been quite a few days! Here's the website we've shipped in the mean time - please check it out! https://www.edenprotocol.xyz/
Also, to stay up to date with Eden news follow us on twitter 🕊 https://twitter.com/edenprotocolxyz

**Comment by moiz-lakkadkutta** [comment]
It has been almost 2 months since I joined Eden Team and I can tell you it's been crazy how swiftly and steadily Eden has grown. This is just because the recipe for success is a great idea + a great team and Eden has both of these things.

**Comment by ErinOCon** [comment]
Hi @amoweolubusayo, thank you for your proposal. It looks like this project is still in the early stages. Once you have finished building out the remainder of your demo and at least one of the metadata features, please feel welcome to reapply!
