### ISSUE TITLE
Next Step Microgrant: Garbage Goober Rewards

### ISSUE THREAD

**Issue by MohinishTeja** [filecoin-project/devgrants#931]
### 1. What is your project? (max 100 words)
&nbsp;&nbsp;&nbsp;&nbsp;Landfills are one of the largest producers of Methane and house gases. Even power generation from Waste produces CO2. Why is it a big problem? It is because of no proper way in dumping. Dumping of huge wastes cause Soil, Air, Water contamination. 

&nbsp;&nbsp;&nbsp;&nbsp;Our solution to this problem is collecting waste **categorically** at source itself. How can we achieve it? By **Rewarding Users**. People get incentives for doing the right thing! These later can be regular habits and greatly saves atmosphere thus promoting sustainability. Rewards distributed are through Cryptocurrency from a decentralized application. Garbage thus collected categorically can be Reused, Recycled which can fund back the reward distribution process thus making this a circular economy. 

&nbsp;&nbsp;&nbsp;&nbsp;**Garbage Goober** is a reward distributing system for proper waste disposal. Rewards are calculated by Smart contract and sent in the form of cryptocurrency. Smart Contract takes input of what type of waste and weight of waste to calculate the reward from the machine. Kiosk alike machine automatically analyses the type of waste and segregates it. For this Deep Learning model based on CNN algorithm is used which relies on IPFS for image classification dataset of over 2,200+ images. NFT's can be minted based on input image and are stored using **NFT.storage**
<p align="center">
<img src="https://user-images.githubusercontent.com/45705872/187989063-533c36ba-3c7b-4539-b853-fc523716ddff.png" width="30%">
</p>
<p align="center">Proposed System for Waste Segregation</p>
<p align="center">
<img src="https://user-images.githubusercontent.com/45705872/188003938-9cdc2307-d15b-447a-9079-d867b7ecf793.png" width="50%" >
</p>
<p align="center">Overview of User Request process</p>

### Flow of the application 
 - User disposes the waste
 - System analyses the type of waste by continuously taking pictures
 - Pictures taken are analyzed and sent to IPFS for data set.
 - After analyzing the type of waste, reward is calculated and sent to User.
 - Parallelly NFT is also minted and stored through **NFT.storage**
 - Waste is properly sent to categorized bin and User gets his reward along with NFT.

<p align="center">
<img src="https://user-images.githubusercontent.com/45705872/188002408-a8447002-d78d-4955-8e99-5ceddc0690d1.png" width="40%" style="margin-left:10%;">
</p>
  

### 2. Project links

  
Link to Github repo 📁: https://github.com/MohinishTeja/garbage_goober
Link to demo or website, if applicable: 
 - Web App  💻 - https://mohinishteja.github.io/garbage_goober/
 - Mobile App 📱 - https://expo.dev/@jongan69/garbagegooberrewards
 - Video Demo - https://youtu.be/kkXdOf3BB2s

<h2>License: Yes, all of our work will be Open Source under MIT license.</h1>

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
&nbsp;&nbsp;&nbsp;&nbsp;**IPFS** is primarily used to save the new input images of waste both from the WebApp and mobile app. This adds to the existing dataset of over 2,200+ images to train the deep learning model. This will be a strong feature for garbage goober rewards in correctly analyzing the type of waste and distributing the rewards.

<p align="center">
<img src="https://user-images.githubusercontent.com/45705872/188002755-516b08d8-a989-402f-8f48-f7b4e827e421.png" width="40%" style="margin-left:10%;">
</p>

&nbsp;&nbsp;&nbsp;&nbsp;**NFT.storage** is used to store the minted NFT's from mobile app. NFT's can be collected and transacted to generate revenue for Grabage Goober rewards. **Filecoin** stores the NFT as well permanently which makes the system fool proof to any attacks. This revenue will be used for supporting reward distribution. Several other utilities with NFT's are planned ahead which can be found below.

Latest technologies like Deep Learning for Waste classification, Blockchain for Reward payout and mobile,web applications ensure the application rewards to only correct waste disposals. Snapshots of the application can be seen below. Please refer to Github repo for more detailed info.

  <h1>Web App</h1>
<p align="center">
  
<img src="https://user-images.githubusercontent.com/45705872/188003343-f2ee0b03-8895-43fc-89df-445d47260837.png" width="45%" style="margin-left:10%;">

<img src="https://user-images.githubusercontent.com/45705872/188003413-4a9131e0-30d1-4ae3-b27e-0f78d8230939.png" width="45%" style="margin-left:10%;">
</p>
<h1>Mobile App</h1>
<p align="center">
<img src="https://user-images.githubusercontent.com/45705872/188003473-f101546d-5d81-4738-9159-143880562243.png" width="45%" style="margin-left:10%;">
<img src="https://user-images.githubusercontent.com/45705872/188003563-96dcdcb1-cfbb-4505-a79c-d5df2165586d.png" width="45%" style="margin-left:10%;">
</p>

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

&nbsp;&nbsp;&nbsp;&nbsp;Currently the Web and Mobile Applications can perform reward distribution and mint NFT's. This is just the initial phase which will be followed up by building a Marketplace for NFT's. Anyone can list and trade their NFT's here based on rarity, attributes of NFT. This shall further be accompanied by access to reward distribution to users only having atleast one Garbage Goober NFT(similar to StepN model). This makes the entire DApp self sustaining in terms of revenue.

&nbsp;&nbsp;&nbsp;&nbsp;Garbage Goober Rewards is currently deployed on Polygon network. We have developed the contract as multi-chain compatible. Thus we shall deploy the application in more networks like BSC, Celo, Velas, Oasis etc., This makes the application accessible to wide range of audience as well improving the compatibility.

&nbsp;&nbsp;&nbsp;&nbsp;Currently the Web application is deployed locally. To use it one needs to clone the repo and run it using Flask framework. We will deploy the Web App globally using Heroku. This shall put our app in hands of people to use at any time. So we will focus on this deployment for the first week. Later on we will develop the market place for NFT in 4-6 weeks with clean UI and strong features to promote NFT trades which in turns helps our aim of rewarding users by collecting waste. Later on we will use the last 2 weeks to implement our smart contracts in other networks as well.

&nbsp;&nbsp;&nbsp;&nbsp;This plan should help us build Garbage Goober Rewards completely with full utility and collect categorized from sources like Households, factories etc.,

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  
Yes we agree to share grant reports upon request including a final report on whole project.
### 6. Does your proposal comply with our Community Code of Conduct?

Yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  &nbsp;&nbsp;&nbsp;&nbsp;    WorldInnovationDay2022 - https://www.worldinnovationday.com/
&nbsp;&nbsp;&nbsp;&nbsp;    Filecoin Track - https://www.worldinnovationday.com/challenge-resources
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Paturi Teja
    * Smart Contracts
    * Deep Learning
    * https://github.com/MohinishTeja
    * Mail Id - marvelmohinish99@gmail.com
* Jonathan
    * IPFS integration
    * React native developer
    * https://github.com/jongan69
* How did you learn about our microgrant program?
    We got to know about this program from Hackathon and later on supported by our mentor Niki from hackathon to apply for this Microgrant.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  **World Innovation Day 2022** organized by **Hackmakers**.
   ⭐ Our project won prize from Challenege#2: Blockchain for Good.
<p align="center">
<img src="https://user-images.githubusercontent.com/45705872/187994254-120c4697-3c8f-48ee-8075-5ce42624a46f.png" width="50%">
</p>
  * Please link to your hackathon submission
      
&nbsp;&nbsp;&nbsp;&nbsp;There is no public portal of project showcase for this hackathon but details about the hackathon can be found from the below links and Github repo.
&nbsp;&nbsp;&nbsp;&nbsp;    👉 WorldInnovationDay2022 - https://www.worldinnovationday.com/
&nbsp;&nbsp;&nbsp;&nbsp;    👉 Filecoin Track - https://www.worldinnovationday.com/challenge-resources
&nbsp;&nbsp;&nbsp;&nbsp;    👉 Awards Ceremony - https://youtu.be/PekZczFhDi4?t=926

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
