### ISSUE TITLE
Next Step Microgrant: Music3

### ISSUE THREAD

**Issue by kushagrasarathe** [filecoin-project/devgrants#932]
### 1. What is your project? (max 100 words)

Music3 is a decentralized platform that let's you upload &  share music over decentralized internet using IPFS, Filecoin/NFT.storage and Polygon.Users can upload the music of their choice on IPFS and mint the music NFT on the Polygon Mainnet  as a proof

### 2. Project links
  
Link to Github repo: https://github.com/kushagrasarathe/hackfs-project
Link to demo or website, if applicable: https://music3.vercel.app/
License: **MIT license**
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
The Music3 dapp lets users to upload music to IPFS by simply filling a form. The music banner and the metadata is then minted as NFT
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

* Work on UI/UX of our dapp and improve the ultimate user experience
* Work on making **Music3** a backend service powered by IPFS, for storing and minting music NFTs, which can be used by other applications.
* Provide a licensing service of music/songs created by the artists. 
* Host the website on a proper domain.
* Add profile support to dapp and render the data from IPFS 
* Making the platform multichain compatible
* Work on promotion strategies for **Music3** on different social media platforms

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes we agree to provide the grant reports.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes , it does comply with the code of conduct

### 7. Links and submissions
**EthGlobal HackFS 2022**
**Music3**: https://ethglobal.com/showcase/music3-zai5y
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

    Name: **Kushagra Sarathe**
Email: kushagrasarathe@gmail.com
GitHub: https://github.com/kushagrasarathe
Role: **Front-end Designing and Development**

    Name: **Dhruv Agarwal**
Email: dhruvagarwal2017@gmail.com
GitHub: https://github.com/Dhruv-2003/
Role: **Backend and Integration**

* How did you learn about our microgrant program?
We were sent an email Niki Gokani from Filecoin Team and details regarding the microgrant was mentioned in the email.

* If your project was created as part of an event or hackathon:
  * What was the name of the event?
  **EthGlobal HackFS 2022**
  * Please link to your hackathon submission
  https://ethglobal.com/showcase/music3-zai5y

**Comment by ErinOCon** [comment]
This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
