### ISSUE TITLE
Next Step Microgrant: nftcollectionlauncher

### ISSUE THREAD

**Issue by NFTChief** [filecoin-project/devgrants#933]
### 1. What is your project? (max 100 words)
nftcollectionlauncher - Processing, bundling and uploading NFT assets (.json, .png) to IPFS via NFTStorage API. Automatically deploying the NFT minter contracts to the following networks: StarkNet (testnet) & zkSync (testnet)

### 2. Project links
  
Link to Github repo: https://github.com/NFTChief/nftcollectionlauncher 
Link to demo or website: https://nftcollectionlauncher.xyz/
License: NFTChief/nftcollectionlauncher is licensed under the MIT License, Total opensource.
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Users NFTcollection is stored on NFTStorage with/ creating the resources/keys.json file and set your NFTStorage API Key: { "nftStorage": "" }
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Adding more NFT minter contract networks next to zkSync (testnet) and StarkNet (testnet) for automatically processing, bundling, uploading and deploying NFT collections. Implementing optional web3..storage next to nft.storage.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes we do.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Robert Shaw, info@nftcollectionlauncher.xyz , https://github.com/NFTChief , Dev.
* How did you learn about our microgrant program?
Through the community forum.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) -none
  * Please link to your hackathon submission -none

**Comment by NFTChief** [comment]
Hi @ErinOCon I hope I'm not forgotten about?

**Comment by NFTChief** [comment]
@ErinOCon  https://blog.infura.io/post/starknet-now-available-to-all-infura-users  That is very good news!

**Comment by ErinOCon** [comment]
Hi @NFTChief, thank you for your patience. Since a unique prototype is required for this program, we will not proceed with a grant for this submission. Please be in touch with any questions or to provide additional information.

**Comment by ipfsloafer** [comment]
@ErinOCon https://nftcollectionlauncher.xyz/
