### ISSUE TITLE
Next Step Microgrant: tProof

### ISSUE THREAD

**Issue by 70nyIT** [filecoin-project/devgrants#934]
### 1. What is your project? (max 100 words)
Decentralized proof of timestamp solution, with the option to publish the certified files on a public permaweb.
This solution allows anyone to certify a file existed prior to a certain date, with the process handled in a fully decentralized way.

### 2. Project links
  
Link to Github repo: -
Link to demo or website, if applicable: 
* website: https://tproof.io
* demo (Goerli testnet): https://app.tproof.io 

License: MIT
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Files certified can be made public on permaweb. Filecoin is a solution for their storage.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will include Filecoin and IPFS as supported storage (currently we support only Arweave). 
To do so, we will need to integrate it in the available solutions, as well as develop further the Chainlink Oracles that verifies the files.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes it does

### 7. Links and submissions
Never took part into an hackathon
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  * Aleixo - as@tproof.io - @70nyIT - Solidity dev and Co-founder
  * Frenk - fc@tproof.io - @fedecastelli - CTO and Co-founder

* How did you learn about our microgrant program?
  * On Twitter

**Comment by 70nyIT** [comment]
For total transparency, we're also live on Gitcoin GR15 batch: 
https://gitcoin.co/grants/7409/tproof

**Comment by ErinOCon** [comment]
Hi @70nyIT, thank you for your proposal! Can you share the repo link that includes the code for your project?

**Comment by 70nyIT** [comment]
hi @ErinOCon 
This is the link to the repo: https://github.com/blockwave-app/tproof-app-and-smart-contracts

Currently private, we'll make it public once we'll go on mainnet (mid-end Oct.). All our Smart Contracts will be released under MIT licence, with verified source contract.

If you need the access now for the grant, we can have you access it by granting permission, just let me know

**Comment by ErinOCon** [comment]
Hi @70nyIT, thank you for the additional information. In order to be an eligible candidate for a microgrant, the project should be actively open source. Once this is the case, please feel welcome to re-apply!

Wishing you the best with your project!

**Comment by 70nyIT** [comment]
Just to let you know, we're open source, with our Smart Contracts under the MIT licence. The repo is:
https://github.com/tproofio/tproof-smart-contracts

Should I open a new request or this one can be re-opened?
