### ISSUE TITLE
Cryptic OTT: Crypto/Blockchain-focused Edutainment OTT

### ISSUE THREAD

**Issue by crypticentertainments** [filecoin-project/devgrants#935]
# Open Grant Proposal: `Cryptic OTT`

**Name of Project: Cryptic Entertainments**

**Proposal Category:** `app-dev`

**Proposer:** `crypticentertainments`

**(Optional) Technical Sponsor:** `No`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

Cryptic Entertainments is a crypto/blockchain-focused edutainment media project. We have already worked for Filecoin in the past and produced a Filecoin anthem that was liked by the majority in the Filecoin ecosystem: https://open.spotify.com/track/2bxZNqhAKRI3S4cXckpfM8?si=dca201e0680f47d2
We have also organized the first metaverse concert in India which was covered by the national media:

Our coverage on NDTV: 
https://twitter.com/ndtv/status/1479546755595194368?s=20
https://www.youtube.com/watch?v=bVpxhRfmVLk
https://www.youtube.com/watch?v=bRsi1fFulAk

Our coverage on Indian Express: 
https://indianexpress.com/article/technology/tech-news-technology/indias-first-metaverse-music-concert-virtual-reality-7706446/

We are now producing short video series along with web series focused on bringing education and awareness about crypto/blockchain using edutainment content as a medium. We are building a decentralized OTT platform that will host all our edutainment content.

## Value

We will be using IPFS as our storage layer for all the content to be hosted which will be aimed at education and awareness using edutainment content as a medium. Through the content we will educate and aware about the technology and importance of decentralization using entertainment as a medium. The content hosted on the OTT will draw masses due to the mass appeal and entertaining nature of the content. 

## Deliverables

We will be developing a decentralized OTT which will host the edutainment content aimed at creating awareness about crypto/blockchain. We will be reaching 1 million people through our content through the OTT. We will be launching a minimum of 7 series in the next quarter.

## Development Roadmap

Phase 1

1) Launching Video Streaming platform as NFT gated club  for early adopters
2) Blockchain identification with login as a wallet option
3) Early Access on the platform before YT/OTT release
4) Decentralized video streaming

Fund requested: $20,000

Phase2:

1) Secondary trading NFT marketplace of platform NFT's 
2) Launching NFT's for each series for early access and AMA's with creators and Stars
3) DAO setup for NFT holders to govern the platform along with revenue sharing

Fund requested: $20,000

## Total Budget Requested

We are looking for a total amount of $40,000. 

## Maintenance and Upgrade Plans

Education for masses is still not solved in the crypto and blockchain space. We are looking this as a long term project with a vision for a minimum of 15 years. This platform will be a center piece of all our educational efforts centered towards awareness.

# Team

## Team Members

1. Litesh Gumber, Founder of Cryptic Entertainments 
Litesh Gumber is an Educationist and a team player who always believed that in order to introduce the "Early Majority" to the crypto and blockchain sector, we have to make learning fun. For this, he brought together 20+ industry experts from the entertainment and crypto ecosystem under one roof, to create meaningful art that'll act as a catalyst for the present crypto revolution.

2. Pratham Verma, Head Video Department 
Pratham is an experienced Veteran of Punjabi Film industry, specializing in cinematography, editing and post production processes
https://pro.imdb.com/name/nm12770889?rf=m_cons_nm_more&ref_=m_cons_nm_more#content=contacts

## Team Member LinkedIn Profiles

https://www.linkedin.com/in/litesh

## Team Website

https://platform.crypticentertainments.com/

## Relevant Experience

Team has all the required tech expertise in building the platform along with the content production. 

## Team code repositories

https://github.com/cryptic-entertainments/video-platform

# Additional Information
How did you learn about the Open Grants Program? Past Grantee
Please provide the best email address for discussing the grant agreement and general next steps. info@crypticentertainments.com

**Comment by ErinOCon** [comment]
Hi @crypticentertainments, thank you for your proposal! This grant has been approved. We have sent an email to discuss next steps.
