### ISSUE TITLE
Open Grant Proposal: Creation of Turkey Community

### ISSUE THREAD

**Issue by tolgayayci** [filecoin-project/devgrants#938]
# Open Grant Proposal: Creation of Turkey Community

**Creation of Turkey Community**

**Proposal Category:** `docs` , `community`

**Proposer:** `@tolgayayci` , `@justmert`

**(Optional) Technical Sponsor:** `-`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** `Yes`

# Project Description

We want to build local and sustainable Filecoin Turkey community that supports the Filecoin's mission. The Filecoin ecosystem and tools are not well known in Turkey, we want to reach more people and take firm steps towards our mission by producing content in the local language and organizing informative and technical events.

According to an analysis study conducted by Coingecko last year, we can say that the interest in the crypto ecosystem in Turkey is increasing rapidly every year.

> “Overall, our findings suggest that cryptocurrency awareness and adoption are relatively high in Turkey. The strong positive cryptocurrency sentiment could be due to the country’s high inflation rate (18-month high at 15.61% in February 2021), driving investors towards the global cryptocurrency market in search of greater returns against the inflationary pressure.”
> 

Source: [https://www.coingecko.com/learn/cryptocurrency-awareness-in-turkey-2021](https://www.coingecko.com/learn/cryptocurrency-awareness-in-turkey-2021)

Although there is a high interest in cryptocurrencies in Turkey, technical interest is just beginning to emerge. Interest in technical events has also increased, thanks to the recently established university blockchain communities and the work of some local actors. We want to draw attention to the technologies in this field by building the Filecoin ecosystem in our country, however, we will organize many events from informative content to competitions and constantly feed the community.

Our previous community experiences have given us some very good insights into what and how to do in a community. As we will discuss in more detail in the following sections, we have prepared an effective and long-term plan.

## Value

This proposal will help us achieve effective results for the ecosystem, including but not limited to the following items.

- Encourage people to produce projects that are beneficial for the ecosystem.
- Organize technical events to attract developers to Filecoin and IPFS.
- Organize events with other web3 partners and produce works for the benefit of Filecoin from inter-community interaction.
- Create a community infrastructure that can be sustained for long periods of time.
- Translate Filecoin and IPFS documents for Turkish-speaking people who do not speak English, and we will constantly produce new content, we will remove the language barrier and enable more people to discover Filecoin ecosystem.
- Promote Filecoin in different places, from public spaces to universities.

Since this is a community project, its risks cannot be classified as concrete like technical projects, but if the project is not carried out effectively, we can point out some risks such as insufficient promotion of the Filecoin ecosystem in the local community and a low rate of conversion.

It is difficult to create a local community from scratch, while creating this community, many problems will arise, from human resources to financial opportunities. Building a good community requires constant attention and effort. This grant will help us solve financial problems, and human resources will be more easily resolved by getting to know the many people in the local community who form other communities.

## Deliverables

When this community is started to be formed, our deliverables will be as follows.

- Turkish translation and maintenance of Filecoin Documentation over time
- Turkish translation and maintenance of IPFS Documentation over time
- Effective Telegram Account (At least 500 members)
- Effective Twitter Account (At least 500 followers)
- 6 University Community Events
- 2 Technical Workshops
- 2 Joint Activity with Ecosystem Partners (like Uniswap & Chainlink)
- Bi Weekly Newsletter (At least 200 member end of the 3 months)
- Turkish Blog Posts (At least 12 post end of the 3 months)

## Development Roadmap

Since building a community is a long-term event with many variables, we determined a three-month roadmap in the first place.

—> **Starter Budget**

- Webflow Business 12 Months
- Webflow Blog-News Template
- Domain & Mail Expenses for 1 Year
- Linktr Subscription for 1 year
- Zoom Business for 1 year
- Kommunity (Event Management Platform) Account Subscription for 1 year
- Roll Up & Promotional Materials
- Upfront budget for other milestones (venue renting and so on)

Time: At starting

Funding: $5000

—> **Milestone 1**

- Filecoin Türkiye Onboarding Event (+30 Person)
- 2 University Community Event (+50 Person)
- Community Management Expenses for Managers
- Social Media Management Expenses for Moderator
- Filecoin Docs’ Complete Translation
- IPFS Docs’ Complete Translation
- +2 Blog Posts
- +2 Newsletter

Time: 4 Weeks

Funding: $5000

—> **Milestone 2**

- 1 Technical Workshop (+40 Person)
- 1 Joint Activity with Ecosystem Partners
- 2 University Community Event (+50 Person)
- Community Management Expenses for Managers
- Social Media Management Expenses for Moderator
- Social Media Marketing Expenses
- +6 Blog Posts
- +2 Newsletter

Time: 4 Weeks

Funding: $5000

—> **Milestone 3**

- 1 Technical Workshop (+40 Person)
- 1 Joint Activity with Ecosystem Partners
- 2 University Community Event (+50 Person)
- Community Management Expenses for Managers
- Social Media Management Expenses for Moderator
- +4 Blog Posts
- +2 Newsletter

Time: 4 Weeks

Funding: $5000

## Total Budget Requested

$20000

## Maintenance and Upgrade Plans

Over time, we will build a sustainable infrastructure and community, allowing the community to move forward with community support.

# Team

## Team Members

- Tolga Yaycı - [GitHub](https://github.com/tolgayayci) - ChainLink Community Advocate & Aave Turkey Community Manager
- Mert Köklü - [GitHub](https://github.com/justmert) - Nvidia Certified Instructor & Aave Turkey Community Manager

## Team Member LinkedIn Profiles

- [https://www.linkedin.com/in/tolgayayci/](https://www.linkedin.com/in/tolgayayci/)
- [https://www.linkedin.com/in/mertkoklu/](https://www.linkedin.com/in/mertkoklu/)

## Team Website

You can check our past [community’s](https://kommunity.com/acmgazi/events/past) page for previous events.

## Relevant Experience

Tolga Yaycı:

- Chainlink Community Advocate
- Aave Turkey Community Manager
- Founding Chair of Gazi University ACM Student Chapter (Ex)
- Microsoft Learn Student Ambassador (Ex)

Mert Köklü:

- Aave Turkey Community Manager
- Nvidia Certified Instructor
- Founding Vice Chair of Gazi University ACM Student Chapter (Ex)
- Microsoft Learn Student Ambassador (Ex)

Since we are the founder of the ACM (Association for Computing Machinery) university community, we have access to approximately 1400+ young enthusiastic students in tech ecosystem. We also acted as student representatives of companies such as Microsoft and Nvidia and organized events in these programs. We know our community-forming friends in Turkey and we want to start taking solid steps for the Filecoin ecosystem in Turkey by blending it with the experience we have gained from volunteer assignments in global technology formations.

https://kommunity.com/acmgazi/events/past

We have just received grant support from Aave to form the Turkish community and we are currently taking the steps to establish it. After tens of events, we know how events can be organized in the world of technology and blockchain, and how an event can be organized from start to finish.

## Team code repositories

No Repository

# Additional Information
We discovered the open grant program in this repository while sending our project we developed for Filecoin.

**Email Address ⇒** [tolgayayci@protonmail.com](mailto:tolgayayci@protonmail.com)

Filecoin Türkiye (Domain Taken, Site Not Active) ⇒ https://filecointurkiye.org/

IPFS Docs Turkish Translation (Translation Started, Active) ⇒ https://ipfs.docs.filecointurkiye.org/

Filecoin Docs Turkish Translation (Translation Not Started, Site Not Active) ⇒ https://filecoin.docs.filecointurkiye.org/

Twitter: [https://twitter.com/FilecoinTurkiye](https://twitter.com/FilecoinTurkiye)

Telegram: [https://t.me/FilecoinTurkey](https://t.me/FilecoinTurkey)

**Comment by ErinOCon** [comment]
Hi @tolgayayci, thank you for your proposal! As a first step, we would like to recommend applying for our [Orbit Program]( https://orbitcommunity.filecoin.io/). To learn more about the program, please feel welcome to set up a call with Yuliia Deriuhina [here](https://calendly.com/yuliia-deriuhina). 

Please feel welcome to re-apply for our dev grants program after your events and community traction has progressed.
