### ISSUE TITLE
Decentralized Learning and Teaching Platform 

### ISSUE THREAD

**Issue by ARUNMANNURU** [filecoin-project/devgrants#940]
### 1. What is your project? (max 100 words)

Decentralized teaching and learning platform for instructors. 

### 2. Project links
  
Link to Github repo: ***Not Started Yet***
Link to demo or website, if applicable: ***N/A***
License: ***N/A***
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

```Will use NFT Storage to store the video tutorials. ```
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

```Will build the prototype and provide capabilities to end user to mint the video lectures```

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

```YES```
  
### 6. Does your proposal comply with our Community Code of Conduct?

```YES```

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

```Not Submitted/Not Participated. Thought of building prototype independently, with this opportunity.```
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

          - Planning to work independently (I'm a full-stack developer)
          - Arun, Mannuru
          - arunm057@gmail.com
          - https://github.com/ARUNMANNURU  

* How did you learn about our microgrant program?

```I was part of dWEB conference, met with few other people who had submitted application for Grants.```

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission
``` Not submitted. Planning to build prototype. ```

**Comment by ErinOCon** [comment]
HI @ARUNMANNURU, thank you for your proposal! Before proceeding with the consideration of this project, a working prototype is required. To support your building progress, participating in a hackathon could be a great next step!

Please feel welcome to re-apply for a grant in the future.
