### ISSUE TITLE
Next Step Microgrant: DeSciWorld - P2P Research Funding platform

### ISSUE THREAD

**Issue by JBate77** [filecoin-project/devgrants#941]
### 1. What is your project? (max 100 words)
Winner of the first place prize at ETHSeoul for the Filecoin/IPFS tract, the P2P Research Funding platform connects researchers and funders in a permissionless and peer-to-peer manner.

Researchers looking for funding can create a proposal, describe their research goals and funding requirements and vye for the attention of benevolent funders. Likewise, funders with a desire to commission a research goal can place a bounty on a subject and accept bids from researchers anywhere in the world to carry out their request.

### 2. Project links
  
Link to Github repo: https://github.com/ryptoc/ethseoul-desci 
Link to demo or website, if applicable: https://main.d2vmrape04fc5p.amplifyapp.com/ 
License: MIT 
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Building this platform on the blockchain allows decentralised and trustless handling of funds and data. Specifically, the data submissions, required for unlocking each milestone’s escrow, are automatically committed to IPFS and this commit is then stored in the metadata of the resulting research’s ipNFT. IPFS is important due to its immutability and permanence, essential for the storage of scientific and research data
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
The funds from this grant will be used for technical consultancy and scoping of development needs for the full build of the P2P Funding platform. User research will be conducted to determine UX improvements from the hackathon design. Design and implementation of improved automatic commits to IPFS during submission stage are with the scope of this grant.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available: Not submitted for prizes yet.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project. 
Joshua Bate, joshua@coinstruct.live, JBate77, Product Manager

* How did you learn about our microgrant program?
From the ETHSeoul hackathon

* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
ETHSeoul
  * Please link to your hackathon submission
https://devfolio.co/projects/desciconnect-cea4

**Comment by jenks-guo-filecoin** [comment]
@ErinOCon They are a winner of ETH Seoul Hackathon earlier. Happy to provide any support you might need in this grant application.

**Comment by ErinOCon** [comment]
Hi @JBate77, thank you for your patience with our review. This grant has been approved! Look out for an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
