### ISSUE TITLE
Next Step Microgrant: Aiverse

### ISSUE THREAD

**Issue by AiverseDai** [filecoin-project/devgrants#945]
1. What is your project? (max 100 words)
Aiverse is a deep tech ecosystem enabler on the blockchain. It is dedicated to the collaboration, Creation, and Commerce of DeepTech. 
We are creating a platform which provides no code tools to create AI/ML, AR/VR Applications without any prior knowledge to deliver smart & interactive experiences.

2. Project links
Link to demo or website, if applicable:
[www.aiverse.co.in](http://www.aiverse.co.in/)

3.0](https://ipfs.io/ipfs/QmVreNvKsQmQZ83T86cWSjPu2vR3yZHGPm5jnxFuunEB9u) licence for content must be applied to the current project and all work funded via this microgrant. →
Proprietary Software Licences
  
4. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  Users will be able to train their AI model using Datasets provided by us. These datasets will be stored on filecoin. We will also store Userprofile, Assets on filecoin.

5. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will use this grant to accomplish several things: 
1: Optimising the frontend and website for tools
2: Optimising the techstack and including a Data training feature. Users who want to train their model, will upload their Datasets which will be stored on filecoin.
3: Development of ai editor and adding template for models

6. Is this project open source?
Yes, will be

7. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
8. Does your proposal comply with our Community Code of Conduct?
Yes, we will comply with the Community Code of Conduct.

9. Links and submissions
* For each team member(s), please list name, email, Github account, and role in the project.
Gaurav Mishra - [synergy.gaurav05@gmsail.com](mailto:synergy.gaurav05@gmsail.com) - Cofounder & CTO - https://github.com/alcyada
Abhishek Roushan - [abhishekroushan2194@gmail.com](mailto:abhishekroushan2194@gmail.com) - Cofounder & COO - https://www.linkedin.com/in/abhishek-alecado/

* How did you learn about our microgrant program?
   Twitter

**Comment by ErinOCon** [comment]
Hi @AiverseDai, thank you for your proposal! Do you have a repo link with the code for this project?

**Comment by AiverseDai** [comment]
Hi @ErinOCon , currently our repo is private. We can show you demo of our product if needed

**Comment by ErinOCon** [comment]
Thank you for the quick reply, @AiverseDai! Unfortunately, we will not be able to consider the project for a microgrant until the project is open source and the affiliated repo has public access. Please feel welcome to reapply if/when the project reaches this phase.
