### ISSUE TITLE
Next Step Microgrant: Sonar Muse

### ISSUE THREAD

**Issue by KillaStryder** [filecoin-project/devgrants#946]
### 1. What is your project? (max 100 words)

Sonar Muse is an NFT music store and streaming platform. The aim of the platform is to unify and uplift musical artists and users using blockchain technology. Web monetization is one of the core incentives that the streaming platform offers to artists for their content as opposed to an ad-based revenue model. The main objective is to have a sustainable ecosystem for musicians and provide an interoperable music service to projects built on the XRPL. Sonar Muse abides by current music industry standards and norms so that artists can get the most out of their work and still become eligible for awards and certifications i.e. RIAA Certifications and Grammys.

### 2. Project links
 https://github.com/KillaStryder/eternal-vibes
https://github.com/KillaStryder/alternate-datastreams

Link to GitHub repo:
https://github.com/KillaStryder/sonar-muse

Link to demo or website, if applicable: 
- Dev Site (Private Beta) : We can provide the link upon request
License:  ARR ( May change in the future)
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
Sonar Muse uses IPFS (NFT.Storage) to upload metadata and the musical artist's music onto the platform in order to produce NFTs. We aim to abide by the standards that are used across multiple blockchains in order to be consistent. We aim to provide the artists with control over what has been uploaded onto IPFS by allowing them to provide their NFT.Storage API key, in order for their content to be stored in their account.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- Backup Power Supply for our business as we experience power outages
- Study IPFS and its use cases
- Ensure that we create an NFT music metadata standard by working/partnering with multiple blockchain music platforms that provide NFTs
- Look at creating our own node on the Filecoin/IPFS network to ensure we store the appropriate data for musicians and artists alike on our platform.
- Ensure that we are using IPFS and NFT.Storage correctly by getting audited by working closely with Filecoin and IPFS.
- Ensure we encrypt music data accordingly - create our own custom encryption standard for music files (Intellectual Property)

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?
Yes. Sonar Muse agrees to share grant reports upon request.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
N/A
  
### Additional questions:
Team:
Marc Zuze - marc@sonarmuse.org - https://github.com/KillaStryder/ - CTO and Co-founder (Lead dev)
Patience M Moyo - patience@sonarmuse.org - Strategic Management

How did you learn about our microgrant program? 
- Ally Haire provided us with insight about the grant, after hearing about our project and what we are building on the XRP Ledger

[Sonar Muse Cover Letter.pdf](https://github.com/filecoin-project/devgrants/files/9496615/Sonar.Muse.Cover.Letter.pdf)
[Sonar Muse - An NFT Music Store and Streaming Platform.pdf](https://github.com/filecoin-project/devgrants/files/9496629/Sonar.Muse.-.An.NFT.Music.Store.and.Streaming.Platform.pdf)

**Comment by ErinOCon** [comment]
Hi @KillaStryder, thank you for your proposal! It looks like the github repo for this project isn't currently public. Can this be updated? Also, do you intend to update the licensing for this project to align with [our policy](https://github.com/filecoin-project/devgrants/blob/master/open-source-policy.md)?

Please let me know of any questions!

**Comment by ErinOCon** [comment]
Hi @KillaStryder, thank you for the additional information. In order to be considered for a microgrant, the project needs to be actively open source and should include repo links that are accessible to the public. 

Please feel welcome to reapply if these details change in the future!
