### ISSUE TITLE
Next Step Microgrant: Freezone A decentralized social media

### ISSUE THREAD

**Issue by Fresszonesongs** [filecoin-project/devgrants#948]
### 1. What is your project? (max 100 words)
Freezone - A decentralized Social Media Platform in Blockchain that uses Smart Social  Tokens for Social consensus algorithm where everyone can leverage the power of Freezone for eccentric entrepreneurial cryptocurrency projects. More importantly, it is a social media platform that is guaranteed to save data and help users maximize their developments while also ensuring users data safety and also a way to make revenue 

### 2. Project links
  
Link to Github repo: https://github.com/Fresszonesongs/Freezone

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
The IPFS, Filecoin or related technologywill be used to save and store users data in a decentralized way. It helps in the integrity of data’s location making it easy to retrieve and hard to censor.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Freezone will create more awareness for the Platform, and initiate many activities and events which will help booster and create more Smart Media Tokens and encourage entrepreneurial pursuits for its users. In addition, Freezone will administer more administration, IT, and Market experts to develop the Platform into a global powerhouse that can accommodate centric entrepreneurial projects for all users.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

yes updates will be given on a monthly basis with completion of the development promptly reported.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes, It Complies with our Community code of conduct

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  https://github.com/Fresszonesongs/Freezone

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by mishmosh** [comment]
Hi @Fresszonesongs thanks for your submission. Can you share a link to a working demo of this project?

**Comment by ErinOCon** [comment]
Hi @Fresszonesongs, can you confirm if a prototype is available for review?

**Comment by ErinOCon** [comment]
Hi @Fresszonesongs, I hope you are doing well! I have closed this item for the time being, but please feel welcome to re-open if a prototype is available to review.

**Comment by Fresszonesongs** [comment]
our prototype is available on a subdomain https://freezone-nine.vercel.app/

**Comment by Fresszonesongs** [comment]
@ErinOCon  the prototype is set to vercel
