### ISSUE TITLE
Proposal for development of Gamalaxie

### ISSUE THREAD

**Issue by handeabhishek111** [filecoin-project/devgrants#949]
# Open Grant Proposal: `Gamalaxie`

**Name of Project:** Gamalaxie

**Proposal Category:**  `app-dev`, `metaverse` 

**Proposer:** @handeabhishek111

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes (MIT License)

# Project Description

We hope to create a decentralized platform where users can come and play games that are long forgotten. Many classic games are not utilized for their excellent quality. There is a huge player base on the internet who still play these arcade games. We can provide them with a platform where they can come and play together and compete. We want to create a platform to provide interoperability between different games. 

We wish to develop a 3D platform where gamers can walk into and interact with one of the many games hosted there. The platform will contain various games where users would need to get high scores to get good-level NFT cards which will help them win the duels. 
Duels would be our platform's game where the users can use the earned NFT to fight/duel with other players from the platform and win rewards. This is based on an earlier 2D version of the games called as Web3Arcade, and we are building many more features after this, like a gamer profile, a unified high score board, a reward section to calculate different types of rewards earned, etc.

We intend to develop a platform where users can interact with a 3D arcade-style universe.
The platform contains games like 2048/ Tetris for PvP (Player versus Player) NFT card-based duels. Such games help in creating multiple NFT cards, which are unique, thus providing a good use case for these NFTs.

The current problem is that these arcade-style games are long dormant (at least the games whose studios are defunct). There is a particular age group; let's refer to them as "Current Gen Players." They are unaware of these amazing arcade games. And some players know about these arcade games but yet are unaware of Metaverse. There is no way for these people to earn by playing these games. 
To solve these problems, we provide our platform Gamalaxie where 
1. Users will earn rewards by participating and winning in Duel matches.
2. Earn NFTs by scoring the highest in their favorite arcade games.
3. This will be accessible to all age groups.
4. The platform would provide a global ranking for each player.
5. In the future, where companies like META, HTC, Valve, etc, are supporting and boosting metaverse-related Dapps we expect a vast user base for this platform.
6. Last but not the least, the players would feel a wave of Nostalgia while playing these games!

## Value

What are the benefits of getting this right? First, since we would be using IPFS to store the NFT's metadata and images, this would increase our platform's use of IPFS as the primary decentralized storage solution. Second, the generation of these NFT Cards would be on a much high frequency as it will be minted in enormous numbers because it would be almost free as we would choose a zero or minimum gas fees blockchain that can handle the same. Finally, when the game is over, it would result in minting the NFTs and storing the data over IPFS. 
This would boost the IPFS network by sharing these resources uploaded over the blockchain, which will trigger faster retrieval times for NFTs.

What are the risks if you don't get it right? Building such a huge potential platform might be complex if we don't get adequate funding or grants. So here we request an additional $21,000 for creating a metaverse Dapp, which we will add to the details in the Deliverables section.

## Deliverables

We currently have the prototype of [Gamalaxie](https://showcase.ethglobal.com/buildquest/tetris-nft-game-60swi) created in vanilla JS and Dynamic HTML using EJS as the frontend, and we have used express js as the backend. The dueling system is now shifted to the smart contract, which was before on MongoDb, as we wanted to create this into a decentralized application. Right now, we intend to convert the centralized integration of the dealing system to a decentralized format with the contract we have just built. Thus we need to hire some skilled NextJs developers and NestJs Developers to develop our application. We would also need 2 Designers to help us create designs and wireframes for our app.

We are planning to build a Dapp where users can just come on our 3D platform and visit an arcade-style gaming collection, where they would choose one game to play and earn NFTs by scoring high as possible. 
The project is related to metaverse as we would require 3 Unity Developers to create the same using the Unity Engine. Thus we need extra funding of $21,000 just for the metaverse integration, as hiring skilled people for game development and testing the product is expensive.
But this is **optional** as we can build a fantastic Dapp without the extra funding where users would be given the option to select from many games available to play.

## Development Roadmap
|   Milestone  | Details  | Duration  | Funding   |
|---|---|---|---|
| Planning Phase  | Planning of architecture of the app with new frameworks. Designing landing page and working on the marketing side and hiring. | 4 weeks  | $6000  |
|  Development Phase 1 | Development of landing Page. Start work on designing the platform pages. Optimizing the current smart contract   | 4 weeks  | $10000 + **$5000\*\***  |
|Development Phase 2  | Re-evaluating the landing page. Start development of the platform integrating NextJs framework. Development of Profile Page, adding open source arcade-style games to the collection page. Developing per game page and testing them individually  | 4 weeks | $10000 + **$8000\*\***  |
| Development Phase 3   | Continue with developing the platform's second phase. Adding extra smart contract as needed for NFT minting for Dueling. Create a duel page where users would need to use their earned NFT Cards or tokens to enter the duel match. Develop a collections page so users can easily check their NFT Cards and filter them by the games they play.   | 4 weeks |  $8000 + **$8000\*\*** |
|  Incorporation of the Decentralized system   | Integrating the optimized smart contract with the platform. Testing out the smart contracts and their security when used on a large scale through scripts. Rewards integration with Metamask and connecting the Dapp to a blockchain that uses minimum or no gas fees for minting and transferring NFTs.  |  4 weeks |  $8000   |
| Beta testing and Beta Launch  |  In this stage, we will cover the testing of the platform with the dueling matches and keep in check with the platform's ongoing development parallelly. Will deploy on the Testnets and test out the decentralization system of the platform thoroughly. Testers would need to qualify the quality of this platform for the next stage to ascend. Then we will finally be deploying the smart contracts on the Mainnet. | 4 weeks  |  $8000 |

---------------------------------------------------------------------------------------------------------------------------------------------------

Funds Distribution Below is the list of people who will be working on the project for the next 6 months:

Full Stack developer (2) - $ 1,000 * 6 months * 2 = $12,000
Solidity Developer(1) - $1,200 * 6 months = $7,200
NextJs Frontend Developer(2) - $1,000 * 6 months * 2 = $12,000
NestJs Backend Developer(1) - $1,000 * 6 months = $6,000
Quality Assurance (tester) (1) - $800 * 6 months = $4,800
Social Media Manager(1) - $400 * 6 months = $2,400
Designers (2) - $500 * 6 months * 2 = $6,000

Total: **$50,000**

**(\*\*)Note - [optional]**:
Metaverse-based application development needs an extra $21,000 in the grant. We would need to hire skilled Unity Game Developers and Designers to create a [Decentraland](https://decentraland.org/) like 3D platform to let users freely move on our virtual platform. 
This grant amount would be distributed in Development Phase 1, 2, and 3 milestones as we would develop the main platform in that period of time. 
We would use the additional grant amount to test the platform and pay the Unity Game Developers and Designers, as game developers are a little expensive. 

Metaverse Additional grant distribution:
Unity Developer (3) - $1000 * 6 months * 3 = $18,000
Game Tester (1) - $500 * 6 months = $3,000

Total: **$71,000** (optional)

## Total Budget Requested

The Total Budget Requested is **$50,000** (mandatory for this project to develop)

The Total (Metaverse Dapp): **$71,000** (optional)

## Maintenance and Upgrade Plans

We would like to add some more future after the Beta is launched, like our own mini marketplace sort of tool for easy transfer of NFT Cards before dueling. 

# Team

## Team Members

Abhishek Hande [Linkedin Profile](https://www.linkedin.com/in/hande-abhishek/) | [Github Profile](https://github.com/handeabhishek111) | handeabhishek111@gmail.com

Sejal Angrakh [Linkedin Profile](https://www.linkedin.com/in/angrakh/) | [Github Profile](https://github.com/sejalangrakh) | sejal.angrakh.16@gmail.com

Vinay Sudrik [Linkedin Profile](https://www.linkedin.com/in/vinaysudrik/) | [Github Profile](https://github.com/optimus789) | vinaysudrik@gmail.com

- We are going to hire people for further development of the platform.

## Team Website
[Live Website](https://web3-arcade.herokuapp.com/)

## Relevant Experience

Abhishek has experience in DevOps for a duration of 1 year and also worked on the development of Web3Arcade. 
Sejal is an Operations Manager with experience of over 6 months and excellent communication skills. 
Vinay is a Blockchain Developer with 2 years of experience. 

## Team code repositories
[Current Codebase](https://github.com/handeabhishek111/Gamalaxie)

**Comment by realChainLife** [comment]
Hi @handeabhishek111 thanks for this proposal. Who's the targeted user for this platform, and

> In the future, where companies like META, HTC, Valve, etc, are supporting and boosting metaverse-related Dapps we expect a vast user base for this platform.

what time frame are you considering for peak adoption?

**Comment by handeabhishek111** [comment]
> Hi @handeabhishek111, thanks for this proposal. Who's the targeted user for this platform, and
> 
> > In the future, where companies like META, HTC, Valve, etc, are supporting and boosting metaverse-related Dapps we expect a vast user base for this platform.
> 
> what time frame are you considering for peak adoption?

@realChainLife, Though the targeted user for this platform could be of any age group, we can say mostly gamers who are more accustomed to arcade-style or indie games would be our targeted audience.

For the second question, 
The time frame would be dependent on the type of approval. However, we believe the metaverse will soon encapsulate the web3 gaming market. Thus, if we could create the metaverse application, we can say that our goal for achieving peak adoption for our app would be 4 to 5 months from Beta Launch as we would be more focused on marketing as we would have a working app to test on.
If this isn't a metaverse application, it will take extra seven months for peak adoption from the Beta Launch.

**Comment by ErinOCon** [comment]
Hi @handeabhishek111, thank you for the proposal and for circling back! We will not be moving forward with a grant at this time, but would be interested in reconsidering a project proposal with a prototype and an initial set of early users. 

We recommend participating in one of our [hackathons](https://hackathons.filecoin.io/) to start building!
