### ISSUE TITLE
 Next Step Microgrant : DDiary

### ISSUE THREAD

**Issue by kimuraakiia** [filecoin-project/devgrants#951]
### 1. What is your project? (max 100 words)
DDiary is a Diary platform built on web3, DDiary is completely decentralized, users have complete control of data, and there is no need to worry about the loss of data in web2 and it has been stolen.
The data of DDiary users can be stored in IPFS/Filcoin through encrypted/non-encrypted methods by using web3.storage , users do not need to pay for storage, and by establishing Diary's copyright on the chain
### 2. Project links
  
Link to Github repo:
https://github.com/kimuraakiia/DDiary
Link to demo or website, if applicable:
https://dd-iary.vercel.app/
License:
MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
All user data will be stored in IPFS/filecoin through web3.storage, and the user's data index will be established through the chain
Subsequent plans will also support saving user data through nft.storage and support mint nft to share your diary

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will have the following:
1: Improve our interactions
2: Add data encryption function
3: Add nft.storage and Mint NFT
4: Support binding your own web3.storage api token

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes

### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
 kimuraakiia , kimuraakiia@gmail.com , https://github.com/kimuraakiia
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @kimuraakiia, thank you for your proposal! Can you provide more information regarding the next steps for this project? How will you accomplish these steps? What is the anticipated end result once these steps are completed?

**Comment by kimuraakiia** [comment]
Hi @ErinOCon . Thanks for your reply, the original intention of this project is to allow people to keep a diary of what happens on web3 every day. In the next, we will mainly complete the following step :

1. Redesign UI/UX to improve ease of use for users
2. Increase the parameter configuration of web3.storage, so that users can use their own web3.storage configuration
3. Added nft.storage option to support users to share the shareable diary mint NFT
4. Support web cross-platform, support mobile and other platforms to use IPFS/Filecoin store their Diary
5. Add content encryption

The above steps will be completed within 3 months, I hope to get support from Filecoin . looking forward to your reply .

**Comment by kimuraakiia** [comment]
Hi @ErinOCon . I would like to know how long it will take, is there any new update news? At present, many project notes need to be recorded using DDiary. This is a good opportunity for large-scale users to use IPFS/Filecoin, and it also brings more real data to IPFS/Filecoin.
Looking forward to getting your reply！

**Comment by ErinOCon** [comment]
Hi @kimuraakiia, thank you again for your proposal and for your patience with our review. Before considering this grant further, we would like to see additional building progress. For next steps, I would recommend taking this project to [a hackathon](https://hackathons.filecoin.io/).

Once completed, please feel welcome to reapply!
