### ISSUE TITLE
Next Step Microgrant: PlayMe Protocol Decentralized Spotify

### ISSUE THREAD

**Issue by Playmenow** [filecoin-project/devgrants#952]
### 1. What is your project? (max 100 words)
PLAYME is a decentralized music streaming Platform that creates a platform for Uploading, storing and distributing Music and playlists by contents and discovery nodes. PLAYME integrates stablecoins for artists to offer paid contents, as well as artist tokens that gives the fans the ability to access exclusive content.

### 2. Project links
https://play-me-protocol.vercel.app
  
Link to Github repo: https://github.com/Playmenow/PlayMe-Protocol

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
IPFS, Filecoin, will be used to exclusively share files and contents between the parties involved, namely the artist or playlists creator and the fan or user of the streaming. It will aslo be used to store the needed data for the parties to securely share files and data for the artist and the fan
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
The grant will enable the Platform to create more publicity and encourage more creative and interactive contents and file sharing between artists and fans. More to that, the site/platform will be developed to handle more influx and traffics on the site more better. And more experts and marketers will be incorporated to make the platform run smoothly and better with new and emerging trends while enabling every user to earn some tokens

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  Yes, The grant reports will be published on a weekly basis, and as at when requested.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes, it is in Compliance with the Community code of Conduct

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
* Link to Github repo: https://github.com/Playmenow/PlayMe-Protocol
  
yes, it is an open source project

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @Playmenow, thank you for your proposal. Can you provide a quick description of your project? Also, can you share a link to your website or a demo?

**Comment by Playmenow** [comment]
updated

PLAYME is a decentralized music streaming Platform that creates a platform for Uploading, storing and distributing Music and playlists by contents and discovery nodes. PLAYME integrates stablecoins for artists to offer paid contents, as well as artist tokens that gives the fans the ability to access exclusive content.

https://play-me-protocol.vercel.app

**Comment by ErinOCon** [comment]
Hi @Playmenow, can you provide a bit more detail regarding your next steps for this project? What steps will you take to achieve the results described under item 4?

Thank you for your patience with our review - I expect to have an update this week!

**Comment by Playmenow** [comment]
Increase the team of developers and People to work on the platform to ensure it runs smoothly. Having gone through the Test-run successfully, developers will be brought in along with Programmers to bring the platform to a fully functional one where users can stream songs seamlessly and enjoy creative contents on the platform. This includes creating a social media page and writing to artist. Bringing Artists on boards and creating NFTS for the Artists. Briefing them on the benefits of joining the platform and how they should and will interact with users as well as exclusivity of the artist and how it works. The Server and Domain name will also be strengthened to boost the security and integrity of the platform.
The Next Logical Step is to increase Staff, and create a Publicity buzz for Playmenow, and to encourage people to use the platform as well as educate people to get tokens through the social media in the platform. The target of people expected to be in the platform to be a minimum of 500 within three months and over 5,000 after 6 months. Therefore, there will be Intensive Advertising and awareness creation. We will reach people through words of Mouth, advertising to friends/colleagues, posters/fliers and campaigning, and other social media platforms such as Facebook, Instagram, Twitter, Whatsapp, etc.
The Whitepaper for Playmenow will also be developed to give an insight into what the platform has to offer to the Users and interested parties. The whitepaper will also outline the idea of Playmenow and how it will work. Educating People on the use of Playmenow is also an integral part which we hope to accomplish, hence there will be blogs and sites where people can read to know more, social media pages for people to discuss and air their views on how the platform can be improved, and where corrections can be made to suit the usability of both the users and the artists.

**Comment by ErinOCon** [comment]
Hi @Playmenow, what platform features will you be prioritizing to increase the functionality of the current demo? How will these priorities lead to the onboarding of users and/or content?

**Comment by Playmenow** [comment]
What platform features will you be prioritizing to increase the functionality of the current demo? How will the prioritizing lead to the on-boarding of users and/or content?
One of the features to be prioritized will be the artiste and content creators/curators interface. Reasons for this development are:
a.	Seamless streaming and pleasure of listening to songs/playlists by curators and users, to distribute, monetize and stream any music content, and at the same time create more wealth for the artistes and the content creators.
b.	Bringing the artistes and the fans together through exclusive links and tokens which allow the artistes to create exclusive contents for the users
c.	Playmenow will bring the community closer by engaging them in tasks and other activities that will benefit everyone/user groups with a link to Playmenow, including the users, artistes, developers, etc. In addition, users will be compensated with the value they bring to the network.
In addition, the artistes will be able to integrate and sell themselves to the public through our channel by making available their songs, albums, social media pages and NFTs which can also be sold.
Another feature that will be prioritized is the Review/Feedback feature. The major reason is that, for the first few months, there will be massive developments and changes to enable Playmenow be user-friendly and more adaptable to the needs and satisfaction of both users and the platform, thus, opinions and suggestions from users will be highly appreciated and valued and taken into consideration. The comment/suggestion feature will give access to everyone, and our data analysts will use the information gathered to integrate and apply where needed to achieve our goals.
The next feature that will be improved on is the music contents available for users. The contents will be made to attract users, and the interface will be able to integrate the artiste's discography. Also, extra features will be added to enable the users create their personlaized playlists, and for the artiste to easily add his songs.
Also, there will be a Marketing Plan detailing how the artistes can showcase their songs and other assets, such as NFTs, and the benefits they will attain from that. The marketing Plan will also include the financial benefits that the users, curators and content creators will get from using Playmenow, and how to increase their earnings. More layers will also be added to the Web Design to make it attractive and user-friendly.

**Comment by ErinOCon** [comment]
Hi @Playmenow, thank you for your patience and for the additional information. We will not be proceeding with a grant at this time, but strongly encourage you to check out a hackathon to complete one of these features! Thank you again for your interest in our grants program.
