### ISSUE TITLE
Next Step Microgrant: We are FlowModel in Chainlink Spring 2022

### ISSUE THREAD

**Issue by jasonplato** [filecoin-project/devgrants#953]
### 1. What is your project? (max 100 words)
   
(Our project is called FlowModel during Chainlink Spring 2022 Hackathon, which is renamed as BlockModel now.)   
BlockModel is a R&D infrastructure for Web3, focusing on Tokenomics. 
We propose a standard for Tokenomics design, including Tokenomics Modeling Language and a development framework. The framework is graphical, which can be compatible with existing platforms. 
What's more, BlockModel has a built-in property-driven automatic economy analysis tool, which is easy to use and precise. With the help of this tool, a Web3 team could make accountable decisions for their tokenomics.
Last, we believe our Tokenomics-Insight-as-NFT mechanism will be good for Web3 ecosystem, improving the sustainability of it. Creators of tokenomics insights could be rewarded well, which stimulates more valuable insights.

### 2. Project links
  
Link to Github repo:
https://github.com/ModelLabs
Link to demo or website, if applicable:
(Demo Video) https://youtu.be/Zc8e4gTx1YI
(Website) https://modellabs.github.io/

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
We use IPFS to store and retrieve data of user-generated models and research insights, with some encrypted privacy data. 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. Support more general Tokenomics models: (1)Research more projects' tokenomics, especially that of stablecoins; (2) Improve semantic expression of current Tokenomics Modeling Language; (3) Release a case-study of stablecoins tokenomics using our product
2. Build up our Tokenomics community: (1) Expand our influence by participating into Web3 activities, forums, hackathon, grants, attracting more people into our community; (2) Produce Tokenomics-related contents (talks, podcasts, articles) inside our community to hold people. 
3. Improve UI / UX: (1) Website; (2) BlockModel Workspace on browser.   

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

YES
### 6. Does your proposal comply with our Community Code of Conduct?

YEs
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
https://devpost.com/software/flowable-dapp#updates ;   
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Jason, wangxufeibsdbd@outlook.com, jasonplato, founder;  
Bin, binwang_neu@163.com, binwang-neu, co-founder;
Dai, banks94@163.com, xuchaoliu, Head of Engineering;
Iris, 616731641@qq.com, Huiuixuan, Head of Product;
* How did you learn about our microgrant program?
We received email about this program after Chainlink Spring 2022 Hackathon
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  Chainlink Spring 2022 Hackathon;    
  * Please link to your hackathon submission
  https://devpost.com/software/flowable-dapp#updates ;

**Comment by ErinOCon** [comment]
Hi @jasonplato, thank you for your proposal! This grant has been approved. Look out for an email to confirm payment details.

**Comment by ErinOCon** [comment]
Hi @jasonplato, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!
