### ISSUE TITLE
OpenGrant Proposal: ParallelGraphSync

### ISSUE THREAD

**Issue by laurarenpanda** [filecoin-project/devgrants#954]
# Grant Proposal: `ParallelGraphSync`

**Name of Project:** ParallelGraphSync

**Proposal Category:** `devtools-libraries`

**Proposer:** `laurarenpanda`

**(Optional) Technical Sponsor:** @patrickwoodhead 

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:**  `Yes`

# Project Description

Currently, most projects in Filecoin Retrieval Market use GraphSync to synchronize data.

GraphSync works well when synchronizing small-volume files. Users can synchronize these multiple files from different nodes by downloading them in parallel. This way could spread the bandwidth pressure of one single node and shorten the synchronization time.

However, this one-to-one synchronizing method may not work well for large files. If data synchronization time becomes longer,  from minutes to tens of minutes or even hours, a single node's bandwidth load will increase. Besides, other nodes with the same data do not provide retrieval services, so resources in the Filecoin network can not be fully utilized.

ParallelGraphSync aims to provide a solution for synchronizing large files in Filecoin Retrieval Market. It can dynamically adjust the synchronization strategy of data blocks to achieve parallel download by connecting multiple nodes with retrieved data and measuring the synchronization speed of the nodes.

For example, we assume Node A needs to synchronize a 1GiB file and Node B, C, and D have duplicate file copies. Network delays between Node A and other nodes are:

- A to B: 10ms
- A to C: 50ms
- A to D: 100ms

The transmission speed from Node B, C, and D to A are all 1MB/s.

The results could be:

- By using GraphSync, it takes about 17mins to synchronize this file from Node B(optimal) to Node A.
- By using ParallelGraphSync, if we adjust the synchronization strategy according to their network delay and transmission speed, it takes about 5mins 42s to complete the same work.

The actual situation will be more complicated and time-consuming but will not affect parallel synchronization's advantages.

For one-to-one data synchronization, the increase in data copies only increases the throughput of a CDN network. The data retrieval speed can not improve significantly and is limited to a single node's transmission speed. 
With ParallelGraphSync, the number of data copies can increase the entire network's throughput and significantly improve the retrieval speed, especially for large files.

![image-20220721182144252](https://user-images.githubusercontent.com/74699939/189089689-b662ae27-fc46-4c74-a20a-69ff7bd634b4.png)

## Value

- Shift traffic from a single node to multiple nodes
- Spread the bandwidth pressure of one single node
- Increase the speed of content delivery
- Improve the utilization of network resources

Programming language: Golang

## Deliverables

1. Implement ParallelGraphSync based on GraphSync
   Building this program without changing the existing GraphSync protocol could reduce its complexity and make it more feasible.

2. Measurement method of synchronized data nodes
   In synchronizing data for multiple nodes, it is necessary to measure data nodes and count indicators such as delay and synchronization speed.

3. Synchronization strategy

- Equal distribution
- Proportional distribution based on measurement indicators

4. Dynamically generate selectors for synchronized data

#### **Milestone 1**

**Goal:** Implement a basic framework to synchronize data from multiple peer nodes.

**Description:** 

1. Enter the Root CID of a certain IPLD graph data, synchronize the entire graph data, and explore the method of generating multiple subgraph Selectors.
2. Implement the interface defined by ParallelGraphSync, compatible with the existing GraphSync interface, and mainly add an interface for synchronizing subgraph data from multiple nodes.

**Implementation ideas:** 

1. Use a Selector to synchronize the left node of each layer of the entire IPLD graph, and record the node path and the number of subgraphs with multiple subgraphs. Then take out the underlying data nodes from the record and assign them to the peer node for synchronization as needed. Other subgraphs keep repeating the above steps to synchronize.

The division of the known graph structure:
![image-20220823173257256](https://user-images.githubusercontent.com/74699939/189089311-c463c3b3-9919-411a-b390-a78676d1b288.png)

The division of the unknown graph structure:
![image-20220823173310305](https://user-images.githubusercontent.com/74699939/189089421-8c0300cc-d052-4f78-a5c5-cd934caf3cb2.png)

2. Compatible with the existing GraphSync interface, mainly the processing of RequestId. Create a Group RequestId first, and then associate the RequestId of the sub Request.

**Resource:**

| Role              | Rate/Hr | HC   | Man-Hour  | Workday | Price   |
| ----------------- | :------ | ---- | :-------- | :-----: | ------- |
| Back-end Engineer | $50     | 2    | 640 hours | 40 days | $32,000 |
| Project Manager   | $30     | 1    | 8 hours   |  1 day  | $240    |

Funding: $32,240

#### **Millstone 2**

**Goal:** When synchronizing a complete IPLD graph data, data can be synchronized from multiple peer nodes without being manually divided by selectors. And the synchronization speed is better than that of a single node.

**Description:** 
1. Add measurement methods while synchronizing data to count indicators, such as delay and transmission speed.
2. Based on the input Root CID and multiple peer node information, automatically split multiple selectors to synchronize data.

**Implementation ideas:**
1. Since ParallelGraphSync is a framework based on libp2p, the indicators for measuring data synchronization should be implemented at the ParallelGraphSync layer. Recording the time of calling Request and the callback processing of RegisterIncomingBlockHook can count indicators such as delay and transmission speed.
2. Explore the entire IPLD graph structure by generating several selectors that match a small number of nodes. Then analyze the synchronized IPLD nodes and generate subgraph selectors to synchronize the rest of the data. If the synchronization of subgraphs is completed, the next step is to check whether there is unsynchronized data. If so, the subgraph Selector is continuously generated to synchronize until all nodes are synchronized.

**Resource:**

| Role              | Rate/Hr | HC   | Man-Hour  | Workday | Price   |
| ----------------- | :------ | ---- | :-------- | :-----: | ------- |
| Back-end Engineer | $50     | 2    | 640 hours | 40 days | $32,000 |
| Project Manager   | $30     | 1    | 8 hours   |  1 day  | $240    |

Funding: $32,240

#### **Milestone 3**

**Goal:** Optimize the selector allocation according to the measurement index to improve the synchronization speed.

**Description:** 
1. Generate a subgraph selector based on the measurement indicators as weights. 
2. When the data synchronization of a node is complete, the synchronization of the node with the slowest transmission speed is canceled. Then regenerate two selectors for the incomplete subgraph branch based on the weight of the two nodes, and send synchronization requests, respectively.

**Implementation ideas:**
When creating a request, bind the measurement indicator variable to each peer node. Selectors in the same batch are assigned weights according to the transmission speed indicator of the peer node. During synchronization, the measurement indicators are continuously updated to serve as a reference for the subsequent generation of the subgraph Selector.

**Resource:**

| Role              | Rate/Hr | HC   | Man-Hour  | Workday | Price   |
| ----------------- | :------ | ---- | :-------- | :-----: | ------- |
| Back-end Engineer | $50     | 2    | 640 hours | 40 days | $32,000 |
| Project Manager   | $30     | 1    | 8 hours   |  1 day  | $240    |

Funding: $32,240

## Total Budget Requested

- Estimated completion time: 120 workdays (~6 months)
- Funding for 5 milestones: $96,720
- Test and maintenance: $6,000 (2 Engineer + 1 PM) 

**Total budget requested:** $102,720

## Maintenance and Upgrade Plans

Maintenance and upgrade plans provided by FileDrive Labs will include:

- Maintenance and bug fixing of this project to ensure that all bugs could be addressed 
- upgrade based on updates of GraphSync

# Team

#### FileDrive Labs (for this project):

- Eric Qian (Back-end Engineering)
- Deanls Wang (Back-end Engineering)
- Laura Ren (Co-founder, PM)

## Team Member LinkedIn Profiles

- Eric Qian: https://www.linkedin.com/in/eric-qian-455141129/
- Deanls Wang: https://www.linkedin.com/in/%E9%B9%8F%E5%85%89-%E7%8E%8B-b06b24232/
- Laura Ren: https://www.linkedin.com/in/laura-ren-panda/

## Team Website

https://filedrive.io/

## Relevant Experience

FileDrive Labs is a technical team actively building tools, applications, and infrastructure in Web3 and focuses on solutions for distributed storage & developments based on IPFS/Filecoin. We have several qualified engineers with more than 10-year development experience in the Block-chain Industry.

In the past years, we have gathered rich technical development experience by participating in the Slingshot Competition and several Hackathons and stored over 10 PiB data on the Feilcoin network through self-developed tools and platforms, the most important, cooperation with number of storage providers. At the same time of high-efficient storage, we also tried to maintain data availability and integrity by developing related tools if necessary.

A series of following products we're working on:

- **FileDrive Datasets:** a platform to effectively connect the huge storage market that Filecoin has built with publishers of public datasets.
- **FileDAG:** a decentralized storage solution based on IPFS that provides high-quality and efficient IPFS Pin Service and customized network service based on customer requirements.
- **Filplus.info:** the first visual dashboard for the Filecoin Plus project, recording relevant real-time data of each DataCap allocation and verified deal transactions on Filecoin through monitoring both on-chain and off-chain information.
- **Go-Graphsplit:** a tool for splitting a large dataset into graph slices to make deals in the Filecoin Network.
- **Go-DS-Cluster:** the storage layer and one of the most significant parts of FileDrive's product system. It aims to gather distributed key-value datastores to become a cluster to increase the data split function and improve data management.

## Team code repositories

https://github.com/filedrive-team

**Comment by patrickwoodhead** [comment]
@realChainLife - I will run this through the retrieval markets working group. I recommend that we sign off this grant proposal milestone by milestone.

**Comment by realChainLife** [comment]
Sounds good @patrickwoodhead we can do that.

**Comment by ErinOCon** [comment]
Hi @laurarenpanda, thank you for your proposal! This grant has been approved. Look out for an email to discuss next steps.
