### ISSUE TITLE
Next Step Microgrant: OPTIK (HackFs Finalist)

### ISSUE THREAD

**Issue by felixpx** [filecoin-project/devgrants#955]
### 1. What is your project? (max 100 words)

OPTIK - finalist of HACKFS by ETH-Global 2022 is a decentralized video conferencing tool specifically tailored to DAOs and general organizations. It's build with IPFS, LitProtocol, web3 storage, tableland, Hyperdapp and a few other service providers to store recordings of video meetings on the open web. The recordings are encrypted via lit protocol to ensure only DAO members (or Team members) are able to access these video recordings. (Private Data on the Open Web)
We also created our own OPEN POAP feature to enable anyone to create Poaps for their meetings. Follow the video down below in the link section to find out more about how it works. 

The project has a lot of potential to be taken to the next level but to truly decentralize an application like this, we need node operators across the world which comes with a lot of costs. 

### 2. Project links
  
Link to Github repo: https://github.com/felixpx/hackfs

Link to demo or website, if applicable:
Website (might be down) https://optik-hackfs-pbm5ito3q-felixpx.vercel.app/
Showcase on ETH GLOBAL: https://ethglobal.com/showcase/optik-fmm58
Youtube Finale Ceremony Presentation: https://youtu.be/8c2Zx-O48xI?t=996 (Timestamp 16:36)
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

IPFS stores video recordings of meetings, images for scheduled meetings and images for our open poap protocol. Videos saved in archive are encrypted by lit protocol to be able to store private data on the open web.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Update the UI for better user experience, fix bugs we couldn't get sorted before the end of the Hackathon and get a few additional team members to extend the network for potential investors which are needed to take it fully decentralized. A portion of the fund will also go towards server costs.  

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
The project was part of ETH GLOBALS' HackFS and won the following prizes:
HACK FS Finalist,
IPFS/Filecoin - Storage Mage
LitProtocol - Best Private Data on The Open Web
XMTP - Best Use
Hyperdapp - Most Innovative Use
Tableland - Poolprize

  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Felix Prabitz - felix@prabitz.net - https://github.com/felixpx/ - Project Manager & Fullstack Dev
Dominic Hackett - dominichackett@gmail.com - https://github.com/dominichackett - Smart Contract & Fullstack Dev
Devin Lamoreux - devinlamy@gmail.com - https://github.com/devinlamy/ - Product Design & Administrator
* How did you learn about our microgrant program?
We received an email a few days after our finale presentation on youtube via ethglobal!
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  ETH GLOBAL - HACK FS 2022
  * Please link to your hackathon submission
  
  https://ethglobal.com/showcase/optik-fmm58

**Comment by ErinOCon** [comment]
Hi @felixpx, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!
