### ISSUE TITLE
Open Grant Proposal: StationX.network

### ISSUE THREAD

**Issue by toshitsom** [filecoin-project/devgrants#957]
# Open Grant Proposal: `StationX.network`

**Name of Project:**  StationX.network

**Proposal Category:** Choose one of `app-dev` , `integration-adoption` , `community`
 
**Proposer:**  `toshitsom`

**(Optional) Technical Sponsor:** `Piyush Maheshwari`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

To date, the majority of the communities manage their treasuries on a member’s private wallet & take decisions on platforms like discord & telegram and keep track of transactions on spreadsheets. This leaves the members of such clubs/collectives/DAOs exposed to risks like loss/theft of funds, no proper tracking, human error, hassles of sending contributions & receiving returns, etc. The tools that currently exist also do not give the flexibility to these communities to manage themselves the way they want, therefore making it difficult for them to onboard themselves on these platforms. A Grants DAO is different from Investment DAO, Charity DAO and so on. One template fits all, approach, fails here.

- StationX is a protocol that enables anyone to start & manage decentralised permissionless pools/clubs/DAOs of any use-case in under 60 seconds.
- Onboarding on the platform is fairly simple, on StationX onboarding page, create your station (use predefined templates for various use cases or create a custom template for yourself) that suits you the best, fill out club details (Name, Token Name, Investment Currency, fund size, Quorum, etc) and with one button click, the club is deployed.
- Once in, invite users who would deposit funds in exchange for minted Club Tokens using a link. (You may also use a custom token/NFT for the DAO)
- Any kind of community/collective (Investors, NFT Collectors, Grants programmes, Parties, etc) can easily manage their capital & assets using the platform.

Product

- Our product gives users a no-code platform to create their DAO.
- Once you connect your wallet, choose to enter the clubs you are already a part of or create a new club.
- When creating a club, simply give your club a name & token symbol
- Once done, select the template that works best for you or create one!
- Set your governance & you’re ready to go!

Link to onboarding & walkthrough video - https://www.loom.com/share/d8755f67975e4d7da817060ab961907f 

Here’s how the dashboard looks (this is currently on testnet, hence the $ values shown here are 0):
![Screenshot 2022-09-09 at 11 25 31](https://user-images.githubusercontent.com/22795668/189281028-a608d34c-eaac-4530-9296-663e87f016be.png)

There will exist millions of people structures on-chain for everything, starting from small pools of friends to a community of 50K+. Small & large people networks investing in opportunities, running different businesses/protocols, funding ideas, collecting assets together, lending/borrowing assets, selling different things & a lot more. DAOs’ AUM was $13.8B in the last cycle, we expect to see $1T in DAOs’ AUM as the next milestone.

## Value

Using StationX, the previously complicated process of creating a DAO will become simplified and anyone will be able to onboard themselves & their communities seamlessly in under 60 seconds. This will empower anyone from a group of 3 to any size who earlier used to manage themselves through telegram/discord, private wallets & excel sheets to manage themselves in a better & safe way.

The protocol is decentralised, trustless & permissionless to its core. A truly decentralised protocol needs a decentralised approach of storing & managing data, especially when the data is as important as governance proposals, authentic user profiles, digital assets held or minted with a detail of minute changes at every step in a club/DAOs lifecycle.

We’re using Filecoin powered Web3.storage to store all proposals that are created by members of the club. In the future, every member’s profile data will also be stored on Web3.storage. We will also be using NFT.storage in the future to store all NFTs that a club owns and the NFTs minted by the club to give its members access to the dashboard (NFT gating for clubs).

The risks are around getting the templates right for specific usecases. For example a grant template would have a separate set of parameters as compared to an investment template. Getting this right would need significant research, participation in relevant communities, expert advisory & continuous feedback loops with early/potential customers.

## Deliverables

The MVP of the protocol would have templates for 

1. Investment DAOs
2. NFT Projects

**Setup using Factory Contracts:**
Anyone using Stationx.network would be able to get started (with a deployed smart contract) in 3 steps(under 60 seconds). All you’d have to do is select the right template for your usecase and StationX factory contracts deploy your contracts as per the parameters set by you. 
For an Investment template parameters could be - Name of Club, Token Ticker, Gating token (ERC20 or ERC721), Quorum, Min/Max Deposits, No. of members, Carry, etc. 

**NFT Projects / NFT Gated communities:**
Clubs/Collectives that have NFT as a way to gate their members would be able to mint membership NFTs and all of the NFT data (JPEGs, Metadata, etc) would be stored on Filecoin.

**Proposals & Governance:**
This is the second building block of the platform where communities can draft & store multiple versions of a proposal before they finally are approved & ready to be raised. All of the proposal data including drafts would be stored on Filecoin using Web3.Storage.

**User Profiles:**
Users of the protocol who are a part of different communities would need an onchain profile that is relevant to the community they are a part of. Each of these users would have PFPs, NFT assets, and other data as a part of their onchain profile. All of this data would also be stored on Filecoin & it’s solutions. 

## Development Roadmap

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-b2894aab-7fff-cf0f-a1c3-606badc11346"><div dir="ltr" style="margin-left:0pt;" align="left">

S No. | Milestone | Description | Team Required | Timeline | Amount
-- | -- | -- | -- | -- | --
1 | StationX protocol’s investment template(60% achieved) | Users would be able to start an investment club in under 60 seconds, create a basic proposal (uses Web3.storage powered by Filecoin) and accept deposits from members. | 2 Frontend Engineers, 1 Blockchain Engineer, Contract Audit of 1st Template | 23-09-2022 | $20,000
2 | Template for NFT gated communities | Users can start an NFT gated club by - Upload/Generation of artwork, metadata (uses Web3.storage, NFT.storage) & setting parameters. We’d have to build the UI of the template & build a dedicated factory contract for the job. | 2 Frontend Engineers, 2 Blockchain Engineers | 18-10-2022 | $25,000
3 | User profiles of community members | Members of DAOs, cults and popular collectives have the tendency to flex their memberships and communities that they belong to. Flex begins from PFP & slowly transitions to reputation based on their profile data. All of a users profile data(NFTs, Bio, Metadata, etc)  would be stored on Filecoin. | 1 Frontend Engineer, 1 Blockchain Engineer, 1 UX Designer | 05-11-2022 | $10,000
4 | Detailed proposal dashboard & version control for drafts | Communities can now collaborate & work on proposal drafts and each of these drafts would be forever stored on Filecoin committed & signed everytime a contributor makes a change to the draft. | 1 Frontend Engineer, 1 Blockchain Enginner, 1 Senior Blockchain Architect | 10-01-2023 | $15,000

</div></b>

## Total Budget Requested

$70,000

## Maintenance and Upgrade Plans

We are working full-time on the product. We’re a part of [Gitcoin Kernel Block 7](https://www.kernel.community/en/) and have been backed by [Polygon DAO](https://polygon.community/#/) & [AAVE Grants DAO](https://aavegrants.org/). We see DAOs as the future of how people & communities will work together and we’re excited to work with them to shape our platform.

# Team

## Team Members

- Rishav Bajoria - Head of Partnerships & Customer Acquisition, Co-Founder & CEO
- Subham Sengupta - Head of Technology, Co-Founder
- Pranav Yerabati - Head of Marketing & Community, Co-Founder
- Toshit Som - Head of Operations & Finance, Co-Founder

## Team Member LinkedIn Profiles

- Rishav Bajoria → Twitter - https://twitter.com/0xrishavb , LinkedIn - https://www.linkedin.com/in/rishavbajoria
- Subham Sengupta → Twitter - [https://twitter.com/subhamsengupta_](https://twitter.com/subhamsengupta_), LinkedIn - https://www.linkedin.com/in/subham-sengupta-ba2938134/
- Pranav Yerabati → Twitter - https://twitter.com/PranavYerabati , LinkedIn - https://www.linkedin.com/in/pranav-y-167998102/
- Toshit Som → Twitter - https://twitter.com/toshitsom , LinkedIn - https://www.linkedin.com/in/toshitsom/

## Team Website

https://stationx.network

## Relevant Experience

4 of us with CS backgrounds, ran a marketing & tech services company in India right after university from 2019 to 2021.

- Rishav used to invest in crypto since 2017 (started with investing in top-tier ICOs through small pools & communities that had allocation with private investors). Invested in over 30 ICOs (including polygon, arweave, ankr, republic network, etc). Found out small communities came together to act as micro VCs, funds, and syndicates. One of the first use-cases of communities managing capital towards a common goal.
- Subham has been building & shipping products since 2019. He soon transitioned into smart contracts. He has worked on multiple projects for clients ranging from retail, e-commerce, universities to build applications for custom use cases.
- Pranav has more than 3 years of experience in product design, community & marketing. He started working with Web3 projects in mid-2021 and worked with over 10 projects to build their community strategy.
- Toshit is a performance marketeer with more than 3 years of experience in marketing & operations, worked with web3 projects since mid-2021 to generate traction & helped them with getting investors & partners on board.

## Team code repositories

The repositories are private. We’d be happy to share them with the team on request.

# Additional Information
You can reach us at toshit@stationx.network & rishav@stationx.network

**Comment by toshitsom** [comment]
Hey @realChainLife, do let me know if you need anything else from our end!

**Comment by ErinOCon** [comment]
Hi @toshitsom, thank you for your proposal! We would like to proceed by supporting the first two milestones of your project. Look out for an email to discuss next steps!
