### ISSUE TITLE
Next Step Microgrant: DeAudit

### ISSUE THREAD

**Issue by priyansh71** [filecoin-project/devgrants#959]
### 1. What is your project?

Owing to the immutable nature of blockchain technology, it is impossible to update the code after its deployment. Placing smart contracts without adequate audits could lead to undesirable situations like differences in the contract's intended performance, gas leakage, and more.

Auditing isn't an easy process. Auditing wait times on top audit firms are 9-12 months and are expensive. We need something that is more participative and allows for new and yet-unproven security auditors. This is the motivation behind building DeAudit, a decentralized audit marketplace that turns the auditing process into a prediction marketplace.

### 2. Project links

Link to Github repo: [DeAudit](https://github.com/deaudit/deaudit)
Link to demo or website, if applicable: [DeAudit](https://deaudit.vercel.app/)
License: GPL-License

### 3. How is IPFS, Filecoin, or related technology used in this project?

Our application plans to help contract creators, security auditors and bug hunters as a whole with the help of a single platform by creating a profile for them. It acts as a user's wall for showing his proof of work in audit creation, bug hunting or audit judging. Here, users can upload profile or cover images for themselves, which are hosted on IPFS using web3.storage. Moreover, we also wish to host the project on a decentralised infrastructure in the future.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective?

Currently we are based on the Mumbai Testnet. We plan to on-board a lot of users, both as security auditors and audit creators. Hence, the grant money would be allocated for Smart Contract Auditing and Marketing of the product. to reach more potential customers for whom the product would prove worthwhile. Moreover, we'd require a Pitch Video and a better dApp design. 
Also would be used to hire more devs to scale it with new features for our frontend, backend and the Polygon contract.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, no worries.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes, it does.

### 7. Links and submissions

We submitted our project to [Polygon BUIDL IT 2022](https://buidlit.polygon.technology/) and included it to the relevant filecoin pool prize.
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

1. [Priyansh Vyas](https://github.com/priyansh71)
- I wrote the whole frontend in NextJS and designed it. 
- I also used [wagmi hooks](https://wagmi.sh/) based on ethers for configuring the frontend with the contract.
- Full-Stack Developer. Building in Web3. Contact me at priyansh710@outlook.com
- Built and maintained full-stack production apps i.e. [Transcript Grade-sheet Portal](https://augsdtranscripts.bits-goa.ac.in/) & [Course-Feedback Software](https://feedback.bits-goa.ac.in/) for [AUGSD](https://github.com/arc-bits-goa). 
- Find more about me [here](https://priyansh71.github.io/profile/).

3. [Arihant Bansal](https://github.com/arihantbansal/)
- Worked on Chainlink VRFs, Keepers and additional features on the contract. I also wrote the backend for managing off-chain user data.
- A builder. I was the lead dev at [Cryptocase](https://cryptocasehq.com/). Contact me at arihant.bansal@gmail.com.
- At [Cryptocase](https://github.com/Cryptocasehq), I built the payments and investing infrastructure from the ground up. 
- It led to raising a pre-seed round of $100k. 
- I've also won prizes at Harmony DeFi and Chainlink hackathons.

4. [Ameya Deshmukh](https://github.com/ameya-deshmukh)
- In the project's contract, I helped manage payment streaming on liquidation of the bug pools.
- I'm a Web3 developer and analyst. Contact me at f20200139@pilani.bits-pilani.ac.in.
- I've previously worked on building India's first crypto index, CRE8, at [CoinSwitch Kuber](https://coinswitch.co/crypto-index) and with Hummingbird Ventures as a VC fellow. 
- I also research blockchains. Find me at LinkedIn [here](https://shorturl.at/ipuxz).
* How did you learn about our microgrant program? Via the Filecoin website.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? Polygon BUIDL IT : Summer 2022.
  * Link to the hackathon submission : [DeAudit](https://devpost.com/software/deaudit)

**Comment by ErinOCon** [comment]
Hi @priyansh71, thank you for your proposal. This grant has been approved! Look out for an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @priyansh71, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

**Comment by priyansh71** [comment]
Hello @ErinOCon ,

I hope you're having a happy new year. Thank You for staying in constant touch.

Unfortunately, the team's schedule got clogged due to university examinations and logistic changes in the project architecture, which involved migration from the Polygon chain to Optimism. Hence we have yet to achieve all the milestones. 
I understand the importance of timely submission of the project and your organization's commitment to supporting it. 

However, I respectfully request a 1.5-month extension to ensure that the project is furnished to the best of our abilities and meets the high standards of your organisations respected micro-grant.

I assure you that the team is working diligently on the project and has made significant progress. The achieved milestones include :

- Implemented open-source protocol [XMTP](https://xmtp.org) in the application (decentralised messaging between bug reporters and  jury)
- Design prototyping and UI overhaul (ongoing work in Figma)
- Shifted hosting to a static IPFS-based architecture (deployed using [Spheron Protocol](https://spheron.network) currently)
- Secured the backend APIs using Bearer Auth-Tokens (ensuring synchronisation of database and contract state)

Upcoming milestones include :

- Improving contract security and gas optimization (elimination of contract bugs, minimising gas usage)
- Performing revisions over UX (implementing the prototype in frontend code)
- Finalizing the architectural changes (integrations with [Sherlock/code4rena](https://github.com/code-423n4/2021-07-sherlock))

Hope you understand. I look forward to submitting the completed report soon.

Sincerely,
Team DeAudit

**Comment by ErinOCon** [comment]
Hi @priyansh71, thank you for the update. Do you have a target date to complete the project?
