### ISSUE TITLE
Next Step Microgrant: KwizBox

### ISSUE THREAD

**Issue by kasiannapurna22** [filecoin-project/devgrants#960]
### 1. What is your project? (max 100 words)
KwizBox is an application made for engaging the student community, which enables them to learn and practice for a topic in a fun manner. Teachers can create questions for a topic that they have taught recently and students can attempt those quizzes. The students who get to pass are being rewarded with an NFT. This creates a healthy environment for the students and makes them to learn topics effectively.

### 2. Project links
  
Link to Github repo: https://github.com/kasiannapurna22/KwizBox
Link to demo: https://youtu.be/EPVcCWdN9r0
Link to website: https://kwizbox.pythonanywhere.com/
License: MIT

### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  Json files of Quiz Questions and Images of NFT Badges are uploaded to IPFS

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Although we were able to build half of the MVP of the project, it still to be added with many customizations on both teacher and student dashboards and make the User experience better.
We are planning to do this by Hiring UI / UX designer for 
improving the frontend of the website
We still need a lot of work on restructuring the website with a new design and features related to quizzes.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
https://devpost.com/software/kwizbox
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Kasi Annapurna
Full Stack developer 
kasiannapurna115@gmail.com
GitHub username: kasiannapurna22

* How did you learn about our microgrant program?
Email
* If your project was created as part of an event or hackathon: 
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  [Web3 Infinity Hackathon](https://web3infinityhackathon.devpost.com)
  * Please link to your hackathon submission
  https://devpost.com/software/kwizbox

**Comment by ErinOCon** [comment]
Hi @kasiannapurna22, thank you for your proposal! Is this project also connected to [this repo](https://github.com/meta-ps/KwizBox)?

**Comment by ErinOCon** [comment]
Hi @kasiannapurna22, do you have an update regarding the inquiry above?

**Comment by ErinOCon** [comment]
Hi @kasiannapurna22, this item has been closed. Please feel welcome to reopen the item to discuss further!
