### ISSUE TITLE
Next Step Microgrant ：Web3Markdown

### ISSUE THREAD

**Issue by aronchickay** [filecoin-project/devgrants#962]
### 1. What is your project? (max 100 words)
Establish a markdown editing platform for web3, users can create their own data space on textile.io through web3 wallet on our platform, and store their edited markdown documents through ipfs/Filecoin

### 2. Project links
  
Link to Github repo:
https://github.com/aronchickay/Web3MK
Link to demo or website, if applicable:
https://web3-markdown.vercel.app/
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
We have used IPFS/Filecoin-related technical points in two places. First, we use the Thread function of textile.io to establish the user's data space, and secondly, we use web3.storage to store the user's markdown document.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We will use this fund to improve the interactive function of markdown to achieve the interaction of the commonly used markdown editors on the market. Secondly, we will realize the function of casting markdown documents into nft (uploading user data through nft.storage), so that users can create The value expression in IPFS/Filcoin documents can already display the user's content copyright on the chain

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes

### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  aronchickay , aronchickay@gmail.com, https://github.com/aronchickay
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by aronchickay** [comment]
@ErinOCon any updates?

**Comment by aronchickay** [comment]
Hi @ErinOCon . We would like to provide all users with a free decentralized markdown editing platform and content sharing platform, looking forward to getting a reply

**Comment by ErinOCon** [comment]
Hi @aronchickay, we would like to see more building progress before considering this project for a grant. For next steps, I would recommend participating in a hackathon! If more information would be helpful, please do not hesitate to be in touch!
