### ISSUE TITLE
OpenGrant: FilecoinHUB Web3 Education and Developer Community

### ISSUE THREAD

**Issue by ChansonStudio** [filecoin-project/devgrants#963]
# Open Grant Proposal: `FilecoinHUB `

**Name of Project: FilecoinHUB Web3 Education and Developer Community

**Proposal Category:** 'community'

# What problem are we trying to solve
There is a lack of trained blockchain developers in the ecosystem who can build the Filecoin funded projects.

# What is FilecoinHUB
FilecoinHUB is a virtual community designed to build and grow the pipeline of Filecoin developers, connect them to funding and projects.
The goal of Filecoin Hub is to build more projects in the Filecoin Ecosystem.  Success will depend upon:
●	Having a pool of highly trained developers building on Filecoin
●	Blockchain start-ups and enterprise projects
●	Funding for projects to scale through or access to crowdfunding
Filecoin Hub can help Filecoin Foundation to achieve these goals.

# Our Roadmap Scope and How Funds Are Used
## Education
New & Existing blockchain developers will be trained with Filecoin developer tools. A pipe of Filecoin developer will be established by:
●	Create a pool of highly trained highly skilled blockchain developers with skills in blockchain programming
●	Promoted Education Courses and attract developers to the Filecoin approved Blockchain Education Providers eg Blockchain Academy and other Blockchain developers
●	Provide introductions to the Filecoin bounty programs for developer rewards
●	Co-Create Developer Bounties with the Filecoin Foundation
●	Provide introductions to the Filecoin SLACK, Telegram and Discord channels
●	Provide Scholarships for developers to attend the Filecoin Developer Training
●	Connect the students to blockchain enabled credentialing for their learning achievements

## Projects
Connections and support provided to build projects on the Filecoin platform.
FilecoinHUB will assist with building a developer ecosystem to connect developers with Filecoin funded projects.
Provide more developers with connections, fundings, scholarships and opportunities to work on funded projects to assist with further growth on these project features and at the same time learn more hand-on development skillsets.

## Community
The developer community is supported to connect, find funding and find talent.
FilecoinHUB will establish the cadence with:
●	Host monthly meetings and on-line forums for Blockchain Developers to meet and exchange ideas
●	Create developer challenges and rewards
●	An introduction to the Filecoin funding programs for start-ups and enterprise organisations with support for them to apply for the funding
●	Virtual incubation support and workshops for Filecoin Projects
●	Create connections between projects and funding such as VC’s, govt funding and crowdfunding
●	Help to connect the talent across project teams to drive successful projects- including marketing, legal, project management, community management, etc

# Who are our audiences
## New developers
The goal is to attract new developers to learn Filecoin tools.

## Existing developers
The goal is to re-train blockchain developers from existing cross chain developer pool who can / will be interested in getting the opportunities from Filecoin projects.
Connect existing cross chain developers to the Filecoin training ecosystem, provide incentives for current cross-chain developer pool to reskill in Filecoin tools, introduce Filecoin projects to the cross-chain developers to access experience Filecoin developers as mentor to gain hands-on experience through working on Filecoin projects.

# FilecoinHUB International Approach
FilecoinHUB will build international connections in Asia Pacific, New Zealand and Australia and partner with multiple universities in Oceanian region.
-	Connect Filecoin approved educator with universities.
-	Connect universities to Filecoin project.
-	Provide practical project opportunities to university students.
-	Promote Filecoin Bounty program at universities.

# FilecoinHUB Blockchain Education Scholarships
In order to attract more developers to the courses and build a pipeline of trained developers FilecoinHUB is recommending the following approach:
●	Monthly developer competitions for developer scholarships to be paid to the education suppliers- 10 scholarships to be paid quarterly
●	Selection processes for dev pool who can provide re-training scholarships for current cross-chain devs to be re-trained in Filecoin Development tools-10 scholarships per quarter
●	Developer Bounties and prizes for completing the courses and achieving the certifications

# Milestones & Funding Request
Milestone 1 ($30k) – Establish FilecoinHUB, build education supplier connections, source developer coach.
Milestone 2 ($30k) – Developer coach onboard and fund the coach. Source audiences connections from various universities in Oceania region.
Milestone 3 ($30k) – 1st developer event launch and establish scholarship.
Milestone 4 ($50k)– Award 10 scholarships to students. Sign on 1 external developer pool for training. 2nd developer event launch.
Milestone 5 ($150k) – This milestone onwards is a long-term repeating activity quarterly to deliver same content as Milestone 4. Lasting for 1 year.
Total of $290k within 2 year project life span.

# Success Metrics
-	20 new developers trained per quarter
-	20 cross-chain experienced developers trained per quarter
-	3 monthly developer community get together developer activities and learning
-	1 quarterly scholarship competition

# Our Team
Jack Hui https://www.linkedin.com/in/jackhui88/
Linda Chew https://www.linkedin.com/in/linda-chew-b8b578243/
Wen Wang https://www.linkedin.com/in/vivien-wang-98b612242/

**Comment by ErinOCon** [comment]
HI @ChansonStudio, thank you for your proposal! Since established community traction is a key criteria point for grants of this size, we recommend checking out the [orbit program](https://orbitcommunity.filecoin.io/) as a next step!

Wishing you all the best with this project!
