### ISSUE TITLE
Next Step Microgrant: <Decentroge> 

### ISSUE THREAD

**Issue by sensurusirupus** [filecoin-project/devgrants#964]
### 1. What is your project? (max 100 words)

Decentroge is a decentralise storage online Platforms with NFT and Chatting capabilities.Users can store their data on IPFS or Web3 Storage. Users can access files directly through web browser without using any third party software.

It has been implemented in order to reduce the dependency on centralized services like Dropbox and Google Drive where users are dependent on a single point of failure. It will give you complete control over your data, right from its inception. Features:

Storage: You have the freedom to choose whether to store your data on IPFS or Web3 Storage

File manager: Directly browse your files from your dashboard

Sharing: Easily share files with friends and family.

NFT Token: Mint NFTs directly from the files uploaded on decentroge

Chat: Send messages on Decentroge.

### 2. Project links
  
[Link to Github repo:
](https://github.com/sensurusirupus/decentroge)

[Link to demo or website](https://decentroge.netlify.app/)

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  
NFTs on the app were stored on IPFS , media files like videos, audios, musics were also stored on IPFS

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We are now working on an upgraded version of this project since we plan to make it available to the public in order to fulfill its intended function in early January. To improve the platform's usability, we are introducing new features. With the support of this award, we will be able to host the project, put it on the mainnet, and do some marketing to use it and reach a few target markets.

### 5. Do you agree to share grant reports upon request, including a 
Yes, sure 
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:  

https://www.encode.club/eth-safari-hackathon

### Additional questions:
* Sensurus Irupus : Full stack blockchain develooper
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (ETH safari)
 [ * Please link to your hackathon submission ](https://www.encode.club/eth-safari-hackathon)

**Comment by sensurusirupus** [comment]
Hi, Please any updates regarding this grant?

**Comment by sensurusirupus** [comment]
Hello, Please any updates on this grant

**Comment by sensurusirupus** [comment]
@ErinOCon Hi, Please any updates regarding this grant?

**Comment by ErinOCon** [comment]
Hi @sensurusirupus, thank you for your patience with our review. This grant has been approved! Can you provide a preferred email address for confirming payment details?

**Comment by sensurusirupus** [comment]
Hi, Thank you. Please find my preferred email below ***@***.*** from my iPhoneOn 12 Oct 2022, at 3:27 PM, ErinOCon ***@***.***> wrote:﻿
Hi @sensurusirupus, thank you for your patience with our review. This grant has been approved! Can you provide a preferred email address for confirming payment details?

**Comment by ErinOCon** [comment]
Hi @sensurusirupus, thank you for your reply! Can you clarify where I can find the preferred email address? If preferred, this information can be sent via Slack.

**Comment by sensurusirupus** [comment]
Hello, Please this is my preferred email ***@***.*** ***@***.***>

**Comment by ErinOCon** [comment]
Hi @sensurusirupus, I am still not able to view the provided address. Would you prefer to email us directly at grants@filecoin.org? If so, please follow up with a message on this thread to confirm this additional step is complete.

**Comment by sensurusirupus** [comment]
Please would you please clarify what you mean by preferred address? My email address or Filecoin address? Thank you

**Comment by ErinOCon** [comment]
Yes, your email address. Currently I cannot see the characters. I can only view the following: ***@***.*** ***@***.***.

**Comment by sensurusirupus** [comment]
***@***.*** ***@***.***> can you see this now please?

**Comment by ErinOCon** [comment]
I cannot see the email address above.

**Comment by sensurusirupus** [comment]
mendsalbert at gmail dot come

**Comment by ErinOCon** [comment]
Thank you! Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @sensurusirupus, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

**Comment by sensurusirupus** [comment]
Okay noted with thanks

**Comment by gonormonor** [comment]
Great project @sensurusirupus any update on this project?
