### ISSUE TITLE
<Auditra>

### ISSUE THREAD

**Issue by kwakyebrilliant** [filecoin-project/devgrants#965]
### 1. What is your project? (max 100 words)
Auditra is an auditing platform that seeks simplify the auditing process with blockchain. By doing so, we offer you an easy way to perform the most challenging and complex audits more efficiently. And what we seek to achieve is to make the auditing processes more transparent to end users.

### 2. Project links
  
[Link to public Github repo](https://github.com/kwakyebrilliant/Auditra2)
Link to demo or website ](https://auditra2.vercel.app/)
License: Distributed under MIT License.
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
All media on the platform are stored on the IPFS.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We intend to take this project to the public domain to serve it's purpose in late November and as such we are working on an updated version of this project. We are adding more features to the platform to make it more user-friendly. This grant will help us host the project, have it on mainnet and undertake some marketing to reach a couple of target market and make use of it.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
https://web3infinityhackathon.devpost.com/project-gallery?page=2
  
### Additional questions:
* Brilliant Kwakye, [kwakyebrilliant@gmail.comk](mailto:kwakyebrilliant@gmail.comk), I worked on the documentation, Backend and Frontend.
* Albert Mends, [mendsalbert@gmail.com](mailto:mendsalbert@gmail.com), mendsalbert , I contributed to the Backend and the frontend.
* How did you learn about our microgrant program? Through mail from protocol labs.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? Web3 Infinity Hackathon
  * Please link to your hackathon submission
https://web3infinityhackathon.devpost.com/project-gallery?page=2

**Comment by ErinOCon** [comment]
Hi @kwakyebrilliant, thank you for your proposal! It looks like we recently provided support for a couple of active projects. Once these projects are completed and a final report is submitted, please feel welcome to reapply for a grant.
