### ISSUE TITLE
Next Step Microgrant: CORTX-Flask-IPFS Integration

### ISSUE THREAD

**Issue by MatthewBarrettUCD** [filecoin-project/devgrants#966]
### 1. What is your project? (max 100 words)
IPFS and CORTX are very useful as mass storage tools, and when I considered what I personally found to be most valuable about cloud storage, I kept coming back to media: my personal images and videos. Being able to back up these memories and have the peace of mind that I won’t lose them is a huge benefit of cloud storage. So I decided to build a Flask project which allowed me to not only upload these images to CORTX, and replicate them to IPFS, but also access them through a static web page, connected to the database. This means that not only are my images backed up, but they are accessible remotely, meaning I can show them to friends and family on the go.

My project allows images to be uploaded to CORTX and IPFS, and also viewed via a static web page, all powered by a Flask app.

### 2. Project links
  
Link to Github repo: https://github.com/MatthewBarrettUCD/cortx/tree/main/doc/integrations/CORTX-Flask-MediaViewer
Link to demo or website, if applicable: https://devpost.com/software/cortx-ipfs-media-storage-viewer
Youtube Demo: https://www.youtube.com/watch?v=iwQ2beyMFtg
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

Images are uploaded to the web application using a static web page portal. These images are then replicated to IPFS, and CORTX, Seagate's distributed database, as this was built during a Seagate/Filecoin Hackathon. Users can then view images uploaded to IPFS via their portal.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Using this grant I will expand supported formats to video and also work on deploying the service. Currently it is a functional application but has only been run locally. Once it is deployed, I will attempt to build out a login/account service which will let users access their own images/videos uploaded to IPFS.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

I agree to share detailed reports each week on the progress of my project and a final grant report at the end of the three month period.
  
### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

Yes, it was given 3rd prize in a Seagate Hackathon and I have received the prize: https://devpost.com/software/cortx-ipfs-media-storage-viewer
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Matthew Barrett - matt.barrett10@gmail.com - MatthewBarrettUCD (Github)
* How did you learn about our microgrant program? 
* I learned about it via email from Niki Gokani after winning a prize in a hackathon.
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * CORTX & Filecoin Integration Challenge 2022
  * Please link to your hackathon submission
  * https://devpost.com/software/cortx-ipfs-media-storage-viewer

**Comment by ErinOCon** [comment]
Hi @MatthewBarrettUCD, thank you for your proposal! This microgrant has been approved. Look out for an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @MatthewBarrettUCD, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!
