### ISSUE TITLE
Next Step Microgrant: Flask Music Player

### ISSUE THREAD

**Issue by hessio** [filecoin-project/devgrants#967]
### 1. What is your project? (max 100 words)

This project is a flask app that acts as a music app where you can listen to songs and upload songs you like. Then the songs are also stored on IPFS.

### 2. Project links
  
Link to Github repo: https://github.com/hessio/MusicAppIPFS
Link to demo or website, if applicable: https://youtu.be/nvjf36RIK_g
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
 
I use IPFS to backup the songs on the app to the IPFS network.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

I want to add a recommender system to build a recommendations page to recommend songs to users and I also want to create a login for users. Then the data can be stored on IPFS for the recommender system.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three-month period?

 
Yes, I agree to share grant reports upon request and a final grant report at the end of 3 months.

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
 
N/A

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Patrick Hession - patrickhession97@gmail.com - hessio (GitHub)
* How did you learn about our microgrant program?
* Heard from friends
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @hessio, thank you for your proposal! Do you have a prototype for this project? If so, do you have a website or demo link that you can share?

**Comment by hessio** [comment]
Oh ya I will make the demo and upload the link here tomorrow

**Comment by hessio** [comment]
Hi @ErinOCon I have added a link to my demo

**Comment by ErinOCon** [comment]
Thanks, @hessio! Are you using a specific service when you use IPFS (web3.storage for example)?

**Comment by dilgarn** [comment]
Yes, exactly I am using web3.storage

**Comment by hessio** [comment]
Yes, I am using web3.storage

**Comment by ErinOCon** [comment]
Thanks, @hessio! Can you confirm the steps you will take to build the recommendation system and user login?

**Comment by hessio** [comment]
Yes, I will use the built-in flask libraries to build the user login system. Then for the recommender, I plan to use the surprise algorithm built-in to python for the recommendations. But I'll need to get collect a huge number of songs to create a good recommender, for example, I was thinking of using this dataset [here ](http://millionsongdataset.com/) so this will be expensive. 

I think it is a cool project and should be very manageable within 3 months being that I already have a working prototype.

**Comment by ErinOCon** [comment]
Hi @hessio, thank you for your patience with this review and for the additional information regarding next steps. Can you point me to where you are incorporating our tech (IPFS, web3.storage, etc.) in your code? I haven't come across it yet. This should be the final piece of the review - thank you again for your time with this information!

**Comment by hessio** [comment]
Hi, @ErinOCon no problem! Ya I checked to see and realized I didn't have the most up-to-date code in my repo. I just made a PR and here is the link to [IPFS](https://github.com/hessio/MusicAppIPFS/blob/main/flask-app/s3_functions.py#L11) code and the link for [web3.storage](https://github.com/hessio/MusicAppIPFS/blob/main/flask-app/s3_functions.py#L12)

**Comment by hessio** [comment]
Hi @ErinOCon - I was just wondering if there was an estimated date for when this proposal would be finalized?
