### ISSUE TITLE
Next Step Microgrant: Affix.io - Future of Medical Datasets

### ISSUE THREAD

**Issue by affix-io** [filecoin-project/devgrants#968]
# Affix

### 1. What is your project? (max 100 words)

Affix is a Medical Dataset versioning system, built in go, on IPFS, for the distributed web

Affix uses advanced language modeling and a network of scientific data engineering pipelines to produce datasets that accelerate the probability of discoveries connected to genes, proteins, pathways, RNA, molecular sequences and other biochemicals. Affix detects, extracts and validates hidden relationships between objects can quicken the pace of discovery in space biosciences.

Affix also provides a novel way to interact with IPFS to extract most out of what the decentralized web has to offer.

https://github.com/affix-io/affix

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

Affix stores datasets in IPFS. 
We store everything related to a dataset and meta-data on IPFS as tables.
Affix imports go-ipfs as a dependency and we utilise the latest stable version of go-ipfs & try to keep Affix's behaviour in relation to IPFS as close to standard go-ipfs as possible.

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We will improve dataset security which would involve multiple audits.
We would then partner with agencies such as National Library of Medicine's PubMed to expand our real-time visualization of data sources as published data grows exponentially.
The grant would help us focus more on our research for developing affix’s feature set.

### 4. Is this project open source?

Yes - [GPL-3.0 license](https://github.com/affix-io/affix/blob/master/LICENSE)

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions

- If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

### Additional questions:

- For each team member(s), please list name, email, Github account, and role in the project.

Member One:
Name - Thomas Govindrajan
Email - thomasgovindrajan@gmail.com
Role - Data Scientist & Product Designer

Member Two:
Name - Ravindran Antharaman
Email - datasets.affix@gmail.com
Github -  [https://github.com/affix-io](https://github.com/affix-io)
Role - Machine Learning & Backend Engineer

- How did you learn about our microgrant program?
Social Media (Twitter).

**Comment by ErinOCon** [comment]
Hi @affix-io, thank you for your proposal! Do you have a website or demo link for this project?

**Comment by ErinOCon** [comment]
Hi @affix-io, thank you for your patience with our review. Is this project related to [this repo](https://github.com/qri-io/qri)? If so, can you briefly describe the building progress that is specific to your prototype?

**Comment by ErinOCon** [comment]
Hi @affix-io, this item has been closed. Please feel welcome to reopen the item to discuss further!
