### ISSUE TITLE
Open Grant Proposal: Introducing Filecoin Liquid Staking Wrapper

### ISSUE THREAD

**Issue by lukaszh2o** [filecoin-project/devgrants#970]
# Open Grant Proposal: Introducing Filecoin Liquid Staking Wrapper

**Name of Project:** H2O

**Proposal Category:** app-dev

**Proposer:** lukaszh2o

**(Optional) Technical Sponsor:** N/A

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** Yes

# Project Description

There currently exists little activity or roles for $FIL holders that falls in between buy/hold/sell/spend and running both financially demanding and technically complex infrastructure nodes.

We acknowledge that Filecoin is very different from other blockchains, however at the same time, we recognize that the Filecoin ecosystem would greatly benefit from a liquid staking solution.

Liquid staking for layer-1s was first pioneered in the Lido ecosystem through stETH which allowed ETH holders to lock up their ETH into the ETH2.0 beacon chain through Lido (stETH) and gain the ability to delegate their node to earn passive revenue.

Avalanche, Solana, and nearly every other alt-L1 are among the latest of high profile protocols to adopt liquid staking, and thusly creating a whole ecosystem around it’s token.

Liquid staking wrapped tokens tend to trade at a slight discount to the base token, a tradeoff in exchange for transferability (e.g. the ability to sell the liquid staked tokens) - all while the base token CRV, BAL, FIL etc. remain locked or staked and taken out of the circulating supply.

## Value

For the Filecoin ecosystem, tokens are locked up for a long period, reducing sellable circulating supply and the resulting scarcity can put a positive pressure on token economics.

For individuals, they can put idle $FIL to work, without having to run storage providers or other highly technical and involved nodes.

The existence of liquid staking would create a new niche within the Filecoin ecosystem for more professional participants who do more than just buy/hold/sell $FIL but do not have the capabilities to run storage (or other) node providers. Adding an additional layer of security for the network by locking more of $FIL  supply.

On the supply side of the economy, node operators will benefit from:
- Storage providers can access additional Initial Pledge Collateral and Storage Provider Deal collateral from the $FIL pooled through liquid staking.
- Storage providers can expend capital on extra hardware capacity and borrow $FIL that has been pooled using liquid staking.
- Providers can pledge extra deal collateral to signal a higher level of confidence in their ability to meet SLAs and thereby differentiate themselves from the competition.

In Phase 2, depending on how FVM deployment unfolds we can offer additional DataFi services such as borrowing such as against block reward collateral. Please note this funding request is to develop Phase 1 of psdnFIL liquid staking for Filecoin.

## Deliverables

We propose to develop the liquid staking protocol for Filecoin in multiple phases to get around the cold-start problem once the FVM launches.

## Development Roadmap

We propose to develop the liquid staking protocol for Filecoin in multiple phases to get around the cold-start problem once the FVM launches.

**Note**: the request for funding is to develop the first milestone. 

**First Milestone Q4 2022 (Q4 2022):**
Liquid staking of bridged $FIL on Ethereum mainnet. Staked liquidity on Filecoin network will be managed using threshold signatures / multisig.

**Second Milestone (Q1-2023):**
Inclusion of psdnFIL as a collateral type for backing the H2O stable asset, which will open up new use cases for psdFIL.

**Third Milestone (Q2-2023):**
Once the FVM is deployed to Filecoin Mainnet we will move the core staking contracts such as psdnFIL onto Filecoin Mainnet and the representations on Ethereum Mainnet will be the bridged versions. This allows for native staking on the Filecoin network, while still having psdnFIL available in some form on Etheruem Mainnet with access to deep liquidity for DeFi and DataFi applications for psdnFIL and $FIL itself.

## Total Budget Requested

Demon, Miner and storage node : 18300 USD
Sealing Worker: 21040 USD
Offsite backup node : 9780 USD
Network & Other costs: 640 USD (Switch - Router - UPS - Cables etc.)
Total Hardware costs : 49760 USD
FIL collateral needed : 50611 USD (7680 FIL / Calculated on FIL $6.59 USD)
Development : 6 months
Dev Ops :  50000 USD 
Smart contract development:  50000 USD 

Total: 149760 USD + required FIL

## Maintenance and Upgrade Plans

The protocol will be operated as a DAO which will maintain and update the protocol as needed based on market and technological developments. The DAO will be funded through small fees on protocol revenue and activity. This is similar to how many defi protocols achieve long term sustainability

# Team

## Team Members

Okarin / Sebastian : 
Okarin is the business lead of H2O, being a digital expert with years of experience working with data in the public sector where he led the implementation of data-driven initiatives such as process automation and digitalization projects for major financial institutions. Okarin is completely embedded within the industry and truly believes in data as an asset class like no other.

Mr. L:
Mr. L. has extensive experience working in decentralized finance (DeFi) and blockchain development spheres. He began working in the DeFi space since 2020, serving as a technical advisor for a range of cryptocurrency projects, including index tokens, algorithmic stablecoins platforms, and arbitrage bots. Since then, he has been an active contributor to numerous cryptocurrency projects. As an experienced full-stack developer, Mr. L. has spent over eight years working on enterprise-class applications while always staying informed about emerging technologies in the Web3 and Blockchain space.

0xKaes: 
0xKaes is a front end developer with more than five years of experience. He has proven abilities in JavaScript, NodeJs, and front end frameworks such as Angular, Vue, and React. He has a deep understanding of Web3 architecture and an excellent grasp of UX/UI design principles.

Trang Nguyen:
Trang Ngyugen is a DeFi builder at heart. Ngyugen’s extensive background in the blockchain industry includes Token Engineering, TokenSPICE Core Developer, Ocean DAO grantee, and longtime contributor to the H2O project.

0xSami_:
DeFi gigabrain, chad, and crypto-native who worked as an analyst at prominent research firms and funds such as Messari, before moving on to contributing at some of the biggest Ethereum DeFi projects such as SushiSwap, and eventually co-founding both New Order DAO and Redacted Cartel.

Marek:
Marek earned his Ph.D  in Computer Engineering in 2011 with a focus on modeling and analysis of complex systems. Before joining New Order as technical co-founder, Marek was a professor of Data Science at the Schulich School of Business in Toronto, Canada, and Senior Research Scientist at BlockScience. 

## Team Website

https://www.h2odata.xyz/

## Relevant Experience

The team has extensive experience launching novel DeFi and staking protocols. 
For instance, the team has launched the H2O protocol back in April 2022 and has been successfully operating it including but not limited to the following activities: Creating smart contracts, Staking, Off-chain infrastructure, remote monitoring, operating cross-chain bridges and bridged assets.
- https://github.com/h2odata/
- https://app.h2odata.xyz/

Team has launched other multi-chain DeFi protocols including a DAO:
- [https://github.com/orgs/new-order-network](https://github.com/orgs/new-order-network/repositories)
- https://dao.neworder.network/

Team has also launched the Redacted Protocol project specializing in liquid staking and voting delegation:
- [https://www.redacted.finance/](https://www.redactedcartel.xyz/)
- https://github.com/redacted-cartel/

The team has performed extensive Token Engineering Modeling, Simulation, and Analysis using digital twins.
- https://github.com/trangnv
- Smart contracts agent based simulation: https://github.com/tokenspice/tokenspice that build on top of Brownie (smart contract framework written in Python)
- Solidity fuzzing with Echidna: https://github.com/trangnv/abdk-libraries-echidna-workshop
- System simulation with cadCAD: https://github.com/trangnv/geb-simulations-h20

## Team code repositories

https://github.com/h2odata

# Additional Information
We learned about the  Open Grants program through key members of the Filecoin community.
Further grant agreements can best be discussed on the following addresses : [sebastian@h2odata.xyz](mailto:sebastian@h2odata.xyz) and [lukasz@h2odata.xyz](mailto:lukasz@h2odata.xyz)

Additional information : We have also applied as a team to the fvm early  builders program. Both applications can be considered as one.

**Comment by realChainLife** [comment]
Hi @lukaszh2o thank you for your patience with our review here. Could you clarify why you need funding to set-up a miner operation for a smart contract based solution?

**Comment by lukaszh2o** [comment]
Hi @realChainLife 

The funding request is for phase 1 which comprises:
- Staking Smart Contracts (Ethereum)
- Bridging Wrapped $FIL to a multisig on Filecoin Mainnet
- Deployment of bridged $FIL to Storage providers (and potentially other node types)
- Redistribution of staking rewards bridged back to Ethereum Mainnet

Please refer to the architecture diagram below:

![image](https://user-images.githubusercontent.com/111342592/192833463-3165d091-8a73-492d-b42f-bb60ea8cb56b.png)


Correct operation of this system requires flawless choreography of the above mentioned on-chain (smart contracts) and off-chain systems (bridges, validators, multisig)

The support requested for hardware (and $FIL) is representative of a typical "small" Filecoin mining operation which we will operate as a model to validate that the system is functional end-to-end before going into live production where other users' funds are at potentially at risk. This same infrastructure will be used to bootstrap the staking part of the project, until we are able to onboard other node running parties to stake the gathered $FIL.

This modest investment in live testing infrastructure will ensure the quality of the liquid staking solution, considering that Filecoin mining has unique features not found in other blockchains.

**Comment by ErinOCon** [comment]
Hi @lukaszh2o, thank you for the provided information. We will not be proceeding with a grant for this project at this time. If the work can be completed without the mining set-up, please feel welcome to submit an updated proposal in the future.
