### ISSUE TITLE
Next Step Microgrant: Filterr

### ISSUE THREAD

**Issue by daniel-brave** [filecoin-project/devgrants#971]
### 1. What is your project? (max 100 words)

Filterr is a decentralized content moderation tool, which gives an easy way to moderate any unpleasant image content which a web3 DApp might want to sensor on the client side.
While decentralized image hosting has enabled a censorship resistant hosting of files on the internet, we believe that end-users should still be given the choice to enable filters, as a "heads up" mechanism before consuming open content.
This adds to a better user experience where users can choose to ignore specific X rated content, as they might find the same distasteful.

**_But how do we do it?_**

Running a decentralized relayer which provides meta-information about a given piece of content before putting it across to the end user. Using this, you can develop interfaces where they can give simple toggle options, where user can either view or hide content based on their preferences
We use IPFS CID's as the main source of truth for this content, so that it's not tampered by any layers in between. Files retrieved from the CID, will be passed through a Bloom Filter and then using machine learning of OpenCV, be classified as an NSFW or non-NSFW content. This meta data will then be relayed back to the requesting client, which can overlay any kind of required user-interfaces.

Link to Github repo: https://github.com/daniel-brave/filterr

Link to demo or website, if applicable:
The demo contains a dummy client which was built to showcase the relayer capabilities
https://youtu.be/ALnR0c8ZGrc

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

How do we use IPFS
We use IPFS CID's to track these files and processes the content stored on IPFS.
The API's developed for the relayer, used Web3.Storage to create and store content, which can then be easily filtered upon.
For the relayer to cache the OpenCV Model Output Data, we use Textile DB to map CID's with the model output results, so that subsequent requests to the relayer with the same CID, will result in sub 10ms response times
  
### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. We will develop a more performant relayer subsystem with OpenCV and more Haar Classifiers. Current un-cached requests take >400ms

2. We will develop v2 API's and expose various stages of the OpenCV classification, so as to give more flexibility to the developer

3. We will support a wider range of moderation beyond explicit content. Moderation can be a tool for various needs
 
### 4. Is this project open source?

Open Source

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes

### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  Daniel Scott
  daniel.scott.dr@gmail.com
  https://github.com/daniel-brave
  Founder - Technical Engineer Lead
  
* How did you learn about our microgrant program?
  Through Twitter

**Comment by daniel-brave** [comment]
Hi @ErinOCon it was told me to that the team would get back to me within a week regarding an update for this grant application, I haven't received any mail or any updates on this issue.

Would you please let me know the current status of this application as I first opened this issue on August 4th on IPFS dev grants but moved it to this repository as I received no reply there.

Thanks again for your time

**Comment by daniel-brave** [comment]
Hi @ErinOCon Currently what Im working on - > https://youtu.be/ALnR0c8ZGrc

**Comment by daniel-brave** [comment]
@ErinOCon Could you share the team's feedback on my idea if possible would love to know what Filecoin Foundation thinks about Filterr.

**Comment by jenks-guo-filecoin** [comment]
Hi @daniel-brave the grants team has a considerable backlog to deal with. Your patience is greatly appreciated.

**Comment by ErinOCon** [comment]
Hi @daniel-brave, thank you again for your patience. Is this a separate project from [this repo](https://github.com/SafeViewIPFS/IPFSContentModeration)? If so, can you briefly describe the building progress that is specific to your prototype?

**Comment by ErinOCon** [comment]
Hi @daniel-brave, this item has been closed. Please feel welcome to reopen to discuss further!
