### ISSUE TITLE
Next Step Microgrant : Web3Tickets

### ISSUE THREAD

**Issue by bonggerbb** [filecoin-project/devgrants#972]
### 1. What is your project? (max 100 words)
NFT marketplace for event tickets, where users can go to buy NFTicks(NFT tickets) to their favourite events, and where event planners can go to create events and sell tickets(NFTicks) to their created events all on the platform.

### 2. Project links
  
Link to Github repo:
https://github.com/bonggerbb/Web3Tickets
Link to demo or website, if applicable:
https://web3-ticket.vercel.app/
License:MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  We use IPFS/Filecoin to store all our Ticket data

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Improve the website, add a variety of IPFS/Filecoin storage modes (such as using web3.storage, nft.storage), improve contract development, and increase tickets

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes

### 6. Does your proposal comply with our Community Code of Conduct?
yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  BongGeRB, bonggerbb@outlook.com, https://github.com/bonggerbb
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @bonggerbb, we will not be moving forward with a grant for this project. Thank you for your proposal.
