### ISSUE TITLE
Next Step Microgrant : DeWebCheckout

### ISSUE THREAD

**Issue by kssammyyy** [filecoin-project/devgrants#974]
### 1. What is your project? (max 100 words)
Create instant checkout pages for your business or service hosted on IPFS. To create a hosted product catalog, you typically pay a subscription fee to a hosting provider like squarespace or shopify. Many of these existing providers do not integrate cryptocurrencies. Providers are not distributed and suffer from the disadvantages of existing centralized platforms (vendor lock-in, variable pricing, outages, credit card fees), now with IPFS/Filecoin you can create decentralized pages

### 2. Project links
  
Link to Github repo:
https://github.com/kssammyyy/DeWebCheckout
Link to demo or website, if applicable:
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
IPFS and Filecoin are the primary drivers making it possible. Using web3.storage, a storefront or product page creator can host a distributed menu or catalog of items available for purchase with cryptocurrency.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We'll focus on a few things:
1: Improve the overall interaction process
2: Access to multiple storage methods (web3.storage, nft.storage)
3: Add self-configuration, allowing users to configure the stored nodes and other data by themselves

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
yes

### 6. Does your proposal comply with our Community Code of Conduct?
yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  kssamy, kssammyyy@outlook.com, https://github.com/kssammyyy
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @kssammyyy, thank you for your proposal! Do you have a working prototype for this project?

**Comment by ErinOCon** [comment]
Hi @kssammyyy, since a unique and working prototype is required for this program, we will not be moving forward with a grant for this project. Please be in touch if you have any questions or would like to provide additional information. Thank you again for your time with this proposal.
