### ISSUE TITLE
Next Step Microgrant : IPFSSwiftKit

### ISSUE THREAD

**Issue by 0xtaoshengshi** [filecoin-project/devgrants#975]
### 1. What is your project? (max 100 words)
The Swift IPFS API shell/client is an asynchronous library that provides native calls to an IPFS node.
We want to build the basic framework of IPFS/Filecoin for IOS platform, so that mobile developers can use IPFS/Filecoin directly in IOS app to manage their own data

### 2. Project links
  
Link to Github repo:
https://github.com/0xtaoshengshi/IPFSSwiftKit
Link to demo or website, if applicable:
This is an IOS Swift plugin, so there is no website, you can check our README
License:MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
 We are building IOS/Swift components based on IPFS/Filecoin, users can directly use IPFS/filecoin services in IOS apps through our 
  sdk.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We use this grant to accomplish the following functions:
1: Add web3.storage and custom API Token
2: Add nft.storage to provide the implementation of mobile NFT
3: Build a mobile database interaction mode
4: Add developers to create user-based data spaces

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

yes
  
### 6. Does your proposal comply with our Community Code of Conduct?

requests, and a description of your experience building on Filecoin, including any challenges or shortcomings encountered. -->
yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  TaoShengShi, TaoshengShi@outlook.com , https://github.com/0xtaoshengshi
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @0xtaoshengshi, thank you for your proposal. This submission looks very similar to [a separate repo](https://github.com/pexavc/IPFSKit). Can you briefly describe your contributions to the provided code?

**Comment by ErinOCon** [comment]
Hi @0xtaoshengshi, this item has been closed, but please feel welcome to re-open when there is more information available.
