### ISSUE TITLE
Next Step Microgrant: Bytekode

### ISSUE THREAD

**Issue by AL-S4H3R** [filecoin-project/devgrants#976]
### 1. What is your project? (max 100 words)

bytekode is a developer tooling platform allowing devs to decode and analyze smart contracts & transactions on-chain.
It converts complex chain data to simple readable messages.

### 2. Project links
  
Link to Github repo: https://github.com/AL-S4H3R/bytekode-ipfs-backups
Website Link: https://bytekode.xyz
Demo: https://app.usebubbles.com/7g2WVy3gvKRUUE2e7V4eqi/decoding-smart-contracts-with-bytekode

License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
All the contracts added by users are in the 'contracts' table & all the functions decoded so far in the 'history' table. To make sure devs can verify what is going on behind the scenes, we backup all this table data to IPFS every hour via Filebase & S3 buckets.
The IPFS hash can then be used to verify this data.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

I plan on hiring a dev & building a js-library on top of s3 and filebase that allows devs to backup all their data to IPFS.
Phase 1 - Support for supabase:
Allowing devs to backup all their tables from supabase at specific intervals to IPFS
Amount - $1000

Phase 2 - Support for firebase:
Allowing devs to backup all their collections & documents from firebase at specific intervals to IPFS
Amount - $1000

Phase 3 - Different libraries for specific use-cases. I.e. Lazy Minting, NFT's, Certificates, Smart Contract ABI etc
Amount - $3000

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
YES

  
### 6. Does your proposal comply with our Community Code of Conduct?
YES

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
   SHLOK MANGE
   shlok@bytekode.xyz, https://github.com/AL-S4H3R
   Lead Developer.
* How did you learn about our microgrant program? - via Piyush Maheshwari

**Comment by ErinOCon** [comment]
Hi @AL-S4H3R, thank you for your proposal! This grant has been approved. Look out for an email to confirm payment information.

**Comment by ErinOCon** [comment]
Hi @shl0k28, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!

**Comment by shl0k28** [comment]
Hi @ErinOCon , just finished submitting the report. Let me know if you need anything else
