### ISSUE TITLE
Next Step Microgrant : IPFSNotepad

### ISSUE THREAD

**Issue by armorseth** [filecoin-project/devgrants#977]
### 1. What is your project? (max 100 words)
We are building a decentralized Notepad based on IPFS/Filecoin . Users can operate their own content data through our platform's local IPFS node or through our remote IPFS/Filecoin SDK

### 2. Project links
  
Link to Github repo:
https://github.com/armorseth/IPFSNotepad
Link to demo or website, if applicable:
https://armorseth.github.io/IPFSNotepad/
License: MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
 We are based on IPFS/Filecoin's Notepad, so all user data will be processed through IPFS/Filecoin technology

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
When we get the funding, we will iteratively upgrade the current code, mainly in the following parts
1: Modify the project framework, use next.js to refactor the project
2: Increase remote IPFS/Filecoin data storage by integrating web3.storage
3: Improve our front-end interaction according to Notepad's UI/UX
### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  yes
### 6. Does your proposal comply with our Community Code of Conduct?

  yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  armors, armorseth@163.com , https://github.com/armorseth
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @armorseth, thank you for your proposal! Do you have a prototype that can be demoed?

**Comment by armorseth** [comment]
Hi @ErinOCon , you can try it here : https://armorseth.github.io/IPFSNotepad/ . I alse updated in issue.

**Comment by ErinOCon** [comment]
This proposal was not selected for our grants program and has been closed.
