### ISSUE TITLE
RFP Application [Green Grant]: DoinGud Decentralized Impact Protocol

### ISSUE THREAD

**Issue by Jameel139** [filecoin-project/devgrants#978]
# RFP Proposal: `[Green Grant]: DoinGud Decentralized Impact Protocol`

**Name of Project:** DoinGud Protocol

**Link to RFP:** [Green Grant](https://github.com/filecoin-project/devgrants/blob/master/rfps/green-grants.md)

**RFP Category:**  `app-dev`

**Technical Sponsor:** Piyush Maheshwari and Jnthn Vctr

**Proposer:** `Jameel139`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** Please respond with either "Yes" or "No": **Yes**

# Project Description

DoinGud is a protocol that provides the infrastructure for Decentralized Impact. The DoinGud protocol offers a solution for the lack of transparency, trust, and effectiveness of the current funding models and delivery of social impact. As a solution, the protocol enables communities to easily organize, fundraise, and govern themselves to generate positive social impact.

Social Impact can be organized by creating and joining impact communities. This can be done by creating a Guild where anyone can submit proposals to help improve the community and have them voted on by its members. This gives communities a say in what projects they want to see funded and how the money is spent.

To fundraise for causes, people can use the DoinGud protocol to donate to causes they care about, receive proceeds from NFT sales and leverage yield pools. This allows for sustainable funding, easier donation tracking, and transparency on where the money is going.

For the purposes of this grant, IPFS will be used for all data storage related to *Impact Reporting, Linking Creations*, and *Impact Signaling*.

## Value To The Ecosystem
The protocol’s main objective is to incentivize and scale the contribution towards public goods, social causes, and environmental impact. The protocol will specifically help on the environmental side through  

- Organizing communities oriented around environmental protection on one platform (through Guilds) to provide better visibility and access
- Facilitate and incentivize funding those communities by streaming funds through a variety of means (NFT sales, direct donations, or plugins with other web3 DAOs and marketplaces)
- Track and validate the impact created by those communities through reporting-and-signaling cycles that the various guilds help monitor and validate transparently.

## Development Roadmap

*Impact Scope:*

Impact curation is a critical process of the DoinGud Protocol. The protocol is designed to incentivize positive social impact. However, not all types of impact are equal, and not all reports will be accurate or verifiable. That's why it's important for the Guild to have qualified reporters and signalers, who can evaluate reports represented by NFTs linked to impact makers, and signal the most worthy ones for rewards. This curation ensures that only verifiable impactful reports are rewarded and that resources are distributed fairly among impact makers, reporters, and signalers.

*Development Scope:*

The data storage has three milestones: Impact Reporting, Linking Creations, and Impact Signaling

1. **Reporting**
*Functionality:* This first stage lasts until 10 report NFTs are created and linked to impact makers by reporters. During this stage, reporters can link any number of report NFTs to an impact maker. All NFTs will be stored on IPFS or NFT Storage
    1. Develop the smart contracts for reporting mechanics
    2. Integrate graphs of interactive NFT data (comments, reactions, verifiable credentials e.g. Gitcoin Passport)
    3. Develop backend
    4. Develop designs and implement front end for the flow
2. **Linking Creations**
    
    *Functionality:* Creators on the DoinGud Protocol link their NFTs to specific Guilds. Each sale donates between 5%-100% to one or several of the over 60 verified Social Impact Organization partners who each work towards the United Nations 17 Sustainable Development Goals.
    
    All NFT data such as metadata, revenues, royalties, and donations are stored on IPFS. 
    
    1. Develop smart contract for linking, and unlinking creations 
    2. Integrate graphs of interactive NFT data (comments, reactions)
    3. Develop backend
    4. Develop designs and implement front end for the flow
3. **Signaling**
*Functionality:* During the period of one week, Signalers evaluate reports in a quadratic voting by burning their signaling tokens to indicate which impact reports are the most informative. As soon as a signaling week is over, another Reporting batch can start. All signaling records will be stored on IPFS or NFT Storage
    1. Develop the smart contracts for:
        1. Identifying signalers based on token amount
        2. Creating voting cycle
        3. Identifying voters and voting results
        5. Reward allocation based on quadratic voting
    2. Integrate Signaling data storage (signaling results, comments, reward allocation)
    3. Develop backend
    4. Develop designs and implement front end for the flow

## Documentation, Education, and Community

- Technical documentation
    - The source code will be open source with detailed documentation
    - A whitepaper will be published explaining the rationale, structure, and impact of the protocol
- Education:
    - Series of video explainers posted on social media
    - Series of blogs explaining the protocol based on different crypto knowledge levels
- Community:
    - Series of twitter spaces and discord events for AMA

## Milestone Summary

| Milestone No. | Milestone Summary | Funding | Estimated Timeframe |
| ------------- | --------------------- | ------- | ------------------- |
| 1             | Impact Reporting  | $45,000      | 6 weeks             |
| 2             | Linking Creations    | $31,000      | 4 weeks             |
| 3             | Impact Signaling   | $62,000     | 8 weeks             |

## Total Budget Requested

$138,000

## Maintenance and Upgrade Plans

The DoinGud DAO will maintain the protocol as long as the DAO is running. 

# Team

## Contact Info
andrew@doingud.com

## Team Members

- Manu Alzuru: Oversees all teams [[LinkedIn](https://www.linkedin.com/in/manuelgonzalezalzuru/)]
- Andrew Kline: Finance & Operations [[LinkedIn](https://www.linkedin.com/in/andrew-kline/)]
- Ludovic Bret: Tech Dev, Architecture & Decentralization Tech [[Github](https://github.com/ludovicbret)]
- Nikoline Arns: Community & SIO Relations [[LinkedIn](https://www.linkedin.com/in/nikoline-nik/)]
- Kyle Gordon: Creative Strategy & Curation [[LinkedIn](https://www.linkedin.com/in/kyle-gordon/)]
- Sanchit Banati: Smart Contract Dev [[Github](https://github.com/Kraznik)]
- Disha Agarwalla: Full Stack Dev [[Github](https://github.com/DishaAgarwalla)]
- DAOism Sytems [[Website](https://daoism.systems/)]

## Team Website

https://doingud.com/

## Relevant Experience

Manuel Alzuru (Manu), Founder at DoinGud. An engineer, humanist, Solarpunk & optimist who believes in humanity and its capacity to evolve and adapt for creating a more equitable future. At DoinGud, Manu wears many hats and takes part in almost all aspects of the project.

Andrew Kline, Co-Founder at DoinGud. Andrew has previously co-founded Cybee, a social Ed-Tech startup in Madrid. At DoinGud, he brings his expertise in business, finance, and legendary peacefulness to lead operations and finance.

Ludovic Bret (Ludo), Co-Founder at DoinGud. Ludovic has 12+ years of experience as a software engineer, startup founder, and system designer. At DoinGud, Ludo leads the decentralized tech team and project architecture.

Nikoline Arns, Co-Founder at DoinGud. Nikoline focuses on the connections amongst creators, social impact organizations, and the wider community. She is part of the vision-building team set to evolve DoinGud as a platform of "Communities for Communities''.

Kyle Gordon, Co-Founder at DoinGud. Kyle is the founder of Studio ZIRO, an independent production studio. Kyle brings his artistic entrepreneurship to the team via his extensive network and wide range of creative skills. At DoinGud, Kyle is a creative strategist and curator.

The team consists of 20+ people. Our distributed and remote-first organization has members all over the globe. We embrace diversity, many of us speak 3+ languages, we have a multicultural mindset and nearly have of the team are women.

## Team code repositories

- Ludovic Bret: Tech Dev, Architecture & Decentralization Tech [[Github](https://github.com/ludovicbret)]
- Sanchit Banati: Smart Contract Dev [[Github](https://github.com/Kraznik)]
- Disha Agarwalla: Full Stack Dev [[Github](https://github.com/DishaAgarwalla)]

**Comment by Jameel139** [comment]
Hello, we would appreciate feedback on the current submission before finalizing - thanks in advance

**Comment by ErinOCon** [comment]
Hi @Jameel139, thank you for the proposal! We are currently reviewing this project and will be in touch with any questions.

**Comment by orinayodele** [comment]
Hi @Jameel139 ! We would love to hear back from you about some of the feedback that @mjohnson518 provided for you.

**Comment by Jameel139** [comment]
Hey @mjohnson518 @orinayodele, managed to sync with the team today to clarify the questions. 

Regarding the data storage component, I've updated the milestone to outline how it's more related to integrating additional data graphs to the different types of NFTs (e.g. enable comments, reactions, and verifiable credentials). 

As for the Signaling budget, the development time for this milestone is longer due to the different layers it entails (reporting and signaling results, ranking, reward allocation for positive/negative reports). I've attached the schema below outlining the process. 

Are you open to scheduling a brief call next week and I'll include our core devs to clarify the details? 
Some open slots: 
- Wed Oct 26th 1.30pm EDT
- Thu Oct 27th 1pm EDT
- Fri Oct 28th 10am EDT

<img width="335" alt="image" src="https://user-images.githubusercontent.com/12619072/196801329-b435e221-b2f0-41aa-aaa1-77c7242e4cf8.png">

**Comment by Jameel139** [comment]
hey @orinayodele please let me know your thoughts on the above, I can propose new times for this week

**Comment by orinayodele** [comment]
Hi @Jameel139 we've had time to look through your proposal and think it's a great idea, however this grants round was specifically focused on Refi focused projects and DoinGud is a bit out of that scope and can not award you a grant at this time. We encourage you to connect with the[ HyperCerts](https://hypercerts.xyz/) team, who are building similar protocols.
