### ISSUE TITLE
Next Step Microgrant: Web3Archive

### ISSUE THREAD

**Issue by johnnlandip** [filecoin-project/devgrants#979]
### 1. What is your project? (max 100 words)
We are building a decentralized Internet Archive for web3, using Chainlink and IPFS to decentralize the archiving and storage capabilities of the Internet Archive. Essentially it's Archive.org, but files are stored in a decentralized fashion (IPFS) and retrieved in a decentralized fashion (using Chainlink Oracles). It provides the same public utility as Archive.org (holding valuable digital information for years to come), but is more resilient to censorship.

### 2. Project links
  
Link to Github repo:
https://github.com/johnnlandip/Web3Archive
Link to demo or website, if applicable:
https://www.youtube.com/watch?v=4wtQRLWR7zI
License:MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
All data on our platform and data uploaded by users will be permanently stored through IPFS/Filecoin . 
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
Add a variety of IPFS/Filecoin node options, provide private data storage based on point-to-point encryption, increase user adhesion by providing highly interactive design pages, and provide easy web2 usage to increase the user market

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  yes

### 6. Does your proposal comply with our Community Code of Conduct?

  yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  johnnland, johnnlandip@gmail.com , https://github.com/johnnlandip/Web3Archive

* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @johnnlandip, since our program criteria requires the code and prototype submitted to include unique contributions from the applicant, we will not be moving forward with a grant for this project. Please let me know if you have any questions or would like to provide additional information.
