### ISSUE TITLE
Next Step Microgrant: FileShare-App

### ISSUE THREAD

**Issue by abubakarsx** [filecoin-project/devgrants#980]
### 1. What is your project? (max 100 words)
File Share App is an mobile application that uploads the content to IPFS and generates decentralized QR codes. It is compatible with any android phones . Users can complete data sharing based on IPFS/Filecoin through mobile phones anytime, anywhere.

### 2. Project links
  
Link to Github repo:
https://github.com/abubakarsx/FileShare-App
Link to demo or website, if applicable:
https://bafybeid5bmzpjes4uvmdvsfgqemecrshx3h6nrlmyghe7bw26xfhoibaka.ipfs.dweb.link/
License:MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
The mobile app is built based on IPFS/Filecoin, all user data are stored through web3.storage and shared with others through unique cid

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. Optimize the interactive interface to make it more mobile
2.  Provide custom storage method selection and corresponding parameter configuration (web3.storage, nft.storage, pinata)
3.  Provide the function of mint nft, if the user uploads data through nft.storage, then you can directly Mint nft through this function

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  yes

### 6. Does your proposal comply with our Community Code of Conduct?

  yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  abubakar，https://github.com/abubakarsx ， abubakarsx@outlook.com
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @abubakarsx, we will not be moving forward with a grant for this project. Thank you.
