### ISSUE TITLE
Next Step Microgrant: Epics DAO

### ISSUE THREAD

**Issue by KishiTheMechanic** [filecoin-project/devgrants#981]
### 1. What is your project? (max 100 words)
Epics is a decentralized crowdsourcing platform for incentivizing open source software development.
Clients can set up a GitHub issue as a Quest (Smart Contract). 
Developers can receive token prizes by solving issues (Quests). 
This ecosystem makes developers focus on problems in their expertise.
Also, clients will be able to solve more advanced problems. 
The more token prizes, the more attention to be solved issues.
As a result, open-source software grows faster in quality. 
Epics solves resource imbalances in software development. 

### 2. Project links
  
Link to Github repo: [https://github.com/epicsdao](https://github.com/epicsdao)
Link to demo or website, if applicable: [https://alpha.epics.dev](https://alpha.epics.dev)
License: Now it's alpha version and in private repository though,
We will make it as dApp on Solana chain. It will be open-source (Apache-2.0)

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

We make tokens so we want to put the token image there. ($EPCT and $EPCD image are already on there) 
And we have Buidlers Collective NFT collection ([https://buidlers.epics.dev](https://buidlers.epics.dev)).
We have now only GENESIS collection but we will also release more versions.
Also we want to make NFT prize for the developers that can let us hold some events on our platform.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
For now Alpha version is like Web3 app and we're using cloud server for some functions.
But we will make Epics as dApp soon to make it decentralized and open-sourced.
We're already talking with some oracle teams to implement the smart contracts with GitHub data.
Also we want to implement on chain messaging ([https://www.dialect.to/](https://www.dialect.to/)) to let users know the quest status changing.
So we can make it fully on chain dApp.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes, we'll share the progress of our works of course.

### 6. Does your proposal comply with our Community Code of Conduct?
Yes, it does.

### 7. Links and submissions

Epics DAO won the 5th place of Solana Summer Camp hackathon.
[https://solana.com/news/solana-summer-camp-winners](https://solana.com/news/solana-summer-camp-winners)
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Fumitake Kawasaki
f.kawasaki@elsoul.nl
[https://github.com/POPPIN-FUMI](https://github.com/POPPIN-FUMI)
Co-founder

Shota Kishi
s.kishi@elsoul.nl
[https://github.com/KishiTheMechanic](https://github.com/KishiTheMechanic)
Co-founder

* How did you learn about our microgrant program?
Our partner [DFH](https://www.dfhcommunity.com/) introduced about it for us.

* If your project was created as part of an event or hackathon:
No, we made it by ourselves from start.

* Please link to your hackathon submission

Epics DAO won the 5th place of Solana Summer Camp hackathon.
[https://solana.com/news/solana-summer-camp-winners](https://solana.com/news/solana-summer-camp-winners)

**Comment by KishiTheMechanic** [comment]
Hello. How's it going?

**Comment by ErinOCon** [comment]
Hi @KishiTheMechanic, thank you for checking in! We are currently reviewing this grant and will be in touch with an update soon. In the meantime, can you confirm when the project will be open source? This is a key criteria point for the microgrant program.

**Comment by KishiTheMechanic** [comment]
Thank you for your reply.
We updated the white paper and website.
https://epics.dev/en/
https://storage.googleapis.com/epics-bucket/WhitePaper/EpicsWhitePaperV1-1-1EN.pdf

It will be open source in 2023.3 - Epics Beta launch
That will be fully dApp and published as open source.

**Comment by ErinOCon** [comment]
Hi @KishiTheMechanic, thank you for the provided update. Once the work for your project is actively open source, we would be glad to consider this proposal for a grant!

**Comment by KishiTheMechanic** [comment]
I see thank you!
I'll make another issue when that is open-sourced.
