### ISSUE TITLE
Next Step Microgrant: DStorage

### ISSUE THREAD

**Issue by cowkaoa** [filecoin-project/devgrants#982]
### 1. What is your project? (max 100 words)
DStorage is a data storage platform based on IPFS/Filecoin and blockchain. Users upload data to IPFS/Filecoin decentralized storage through the platform, and record the uploaded data information in the blockchain. What we ultimately want to achieve is web3 dropbox

### 2. Project links
  
Link to Github repo:
https://github.com/cowkaoa/DStorage
Link to demo or website, if applicable:
https://ds-torage.vercel.app/
License:MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
The core of DStorage is to use IPFS/Filecoin as the storage bottom layer of all our data, and user data is stored in a decentralized way through IPFS/Filecoin  

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
I will refactor the whole project, mainly in a few points, modify our project according to the interaction of Dropbox, add multiple storage configuration options, add paid storage (Estuary, Textile) and more free storage options (web3. storage,nft.storage), at the same time we will invite IPFS/Filecoin lovers to join our startup testing phase to provide more optimization points for web3's Dropbox
### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  yes

### 6. Does your proposal comply with our Community Code of Conduct?

yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  cowkao, cowkao@126.com , https://github.com/cowkaoa/DStorage
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @cowkaoa, we will not be moving forward with a grant for this project. Thank you for your time with this submission.
