### ISSUE TITLE
Next Step Microgrant: Acharya Academy

### ISSUE THREAD

**Issue by acharya-academy** [filecoin-project/devgrants#984]
### 1. What is your project? (max 100 words)

Acharya Academy is an open-source learning initiative to help educate the school and college teachers around the world and help them get up to speed with Blockchain and Web3.
We at Acharya Academy, are partnering with Colleges in Delhi, India to start this initiative and help teachers onboard themselves on to web3.
We have open sourced this initiative to help other members and communities participate in this initiative and contribute to the motion.
Link to Github - https://github.com/acharya-academy/acharya-academy

We have come up with a rudimentary course structure which covers the following:

1. Basics of Blockchain
2. Basics of Smart Contract
3. Types of Mining
4. Open Source Ethics in Blockchain & Web3 Development
5. How to train students to undertake web3 by
a. Working with a local blockchain
b. Connecting to Dapps
c. Example Dapps and Smart contracts
d. Deploying to Test Net
6. How decentralised storage works.
a.Introduction to Filecoin
b.How Filecoin Works
c.Why Filecoin
d.Filecoin compared to centralised storing options

As a part of the demo, we have 80% of the content ready for prototype here - [https://github.com/acharya-academy/acharya-academy/tree/master/content/teacher-training-track](https://github.com/acharya-academy/acharya-academy/tree/master/content/teacher-training-track)

We are recently honored at the Solana Delhi Hackerhouse, where we spoke to an avid crowd of students and teachers who are interested in this initiative. We have identified partnerships to take this forward in a larger scale.

### 2. Project links

Link to Github repo:  [https://github.com/acharya-academy/acharya-academy](https://github.com/acharya-academy/acharya-academy)
License: MIT

### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

We are currently using web3 storage to store the meta-data about the participants. We are using a JSON Object file to store and retrieve this information. Further, we use NFT Storage to store the certificates issued to the participants of the course, upon completion.

The target audience for our program is the web2 teachers from various institutes, who are yet to be onboarded to web3 as a technology. These can be teachers / faculty members who are well versed with web2 technologies but not web3.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. Expand the program to reach a broader teacher / educator community such as various institution faculty, as well as independent educators (Youtube, etc.)
2. Improve and update the program to include increasingly relevant information about the web3 space. (Different layers 1's ,etc.)
3. Increase offerings - we will put in efforts to create video courses for easier knowledge transfer. These will include various layers of content where we can nest the topics (Introduction to Blockchain, Introduction to Smart Contract Development, etc.)
4. Developing a Mobile app and Web Dashboard to act as the front end for our initiative, where teachers can login with their institution ID's and consume content. This will help us easily help us to do institution outreach programs, where we can onboard multiple faculty members
5. Building a TeacherDAO, where web3 educators from all around the world can learn and contribute.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes we do

### 6. Does your proposal comply with our Community Code of Conduct?

Yes

### 7. Links and submissions

We were participants at the Solana Delhi Hackerhouse - [https://solana.com/events/new-delhi-hacker-house](https://solana.com/events/new-delhi-hacker-house)

### Additional questions:

- For each team member(s), please list name, email, Github account, and role in the project.
Nagesha AG - [https://github.com/acharya-academy](https://github.com/acharya-academy)
Email - [acharya.learn@outlook.com](mailto:acharya.learn@outlook.com)
LinkedIn -[https://www.linkedin.com/in/nagesha-a-g-08577823](https://www.linkedin.com/in/nagesha-a-g-08577823)
I have been a professor of Computer Science of the last 14 years and have been a blockchain advocate for the last 5 years.

A few of my students who help me:
Aravind Kumar - 4th year BTech Student
Komal Sindhu G - 2nd year BBA Student
Rajesh Kannan Raj - 3rd year BTech Student
All from the college of Acharya Institute of Technology

- How did you learn about our microgrant program?
Solana Delhi HackerHouse, where I learnt about this - [https://superteam.fun/bounties/build-a-filecoin-project-and-apply-for-the-microgrant](https://superteam.fun/bounties/build-a-filecoin-project-and-apply-for-the-microgrant)
- If your project was created as part of an event or hackathon:
    - What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum) - Solana Delhi HackerHouse

**Comment by ErinOCon** [comment]
Hi @acharya-academy, thank you for your proposal! It looks like this work is affiliated with the project outlined [here](https://github.com/d3fkon/xrepox/issues/7). Can you briefly describe the relationship between the two accounts?

Also, can you point out any references in your code to IPFS, Filecoin, or related tech (such as web3.storage or nft.storage)?

**Comment by ErinOCon** [comment]
Hi @acharya-academy, I hope you are doing well! Can you speak to how IPFS, FIlecoin, or related tech are incorporated in your code?

**Comment by ErinOCon** [comment]
Hi @acharya-academy, I have closed this item for the time being, but please feel welcome to reopen the item once your project is incorporating IPFS, Filecoin, or closely related tech!
