### ISSUE TITLE
Next Step Microgrant: DreamTeam Platform

### ISSUE THREAD

**Issue by aahiliscoding** [filecoin-project/devgrants#985]
### 1. What is your project? (max 100 words)

DreamTeam is a decentralised betting platform, where users can trust-lessly bet on various sporting events across the globe.
All bets are handled by an ERC20 Smart Contract, and is fulfilled once the criteria is met.
Users have 0 platform risk, as the platform is completely open sourced and decentralised

[https://github.com/aahiliscoding/DreamTeam](https://github.com/aahiliscoding/DreamTeam)

our app:

<img width="258" alt="image" src="https://user-images.githubusercontent.com/110229179/182701416-02f76960-f2ae-4651-a6da-01a0d0ee4efc.png"> <img width="260" alt="image" src="https://user-images.githubusercontent.com/110229179/182701621-2e09ce6d-5745-4a41-9998-be4512b59ed8.png"> <img width="258" alt="image" src="https://user-images.githubusercontent.com/110229179/182701715-6e939b8e-7416-4f20-baac-2185e95e989a.png">

### 2. How will IPFS, Filecoin, or related technology be used for this project? (max 100 words)

1. All real-time records coming from various 3rd parties, are stored on IPFS using orbitdb
2. The token issued to the users acts their proof of participation. These tokens are NFT’s, which are stored on FileCoin using NFT.storage
3. Users can bet not just on sporting events, but on any other outcome-based event which they choose, as long as both sides of a bid can be fulfilled. These dynamic event-based-bet-matching occurs on the smart-contract using FileCoin as the data-storage layer
4. Anyone can build a client for DreamTeam’s infrastructure. Our specific client will be hosted on IPFS and served on the web. 

### 3. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

Objectives:

1. Host offline gaming tournaments & community programs promoting the core tech behind the product and bring about awareness in web3
2. Smart-Contract Audit by suggested authorities
3. Developing a decentralised backend using IPFS and other layers such as Spheron Protocol
4. Host work-shops to help hire interested candidates to the project

### 4. Is this project open source?

Project is Open Source with MIT License.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

Yes

### 6. Does your proposal comply with our Community Code of Conduct?

Yes it does

### 7. Links and submissions

- If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

### Additional questions:

- For each team member(s), please list name, email, Github account, and role in the project.

Aahil Faisal
[imaahil786@proton.me](mailto:imaahil786@proton.me) [https://github.com/aahiliscoding](https://github.com/aahiliscoding)
Founder

- How did you learn about our microgrant program? From the build section on Filecoin's [website](https://filecoin.io/build/#intro)

**Comment by ErinOCon** [comment]
Hi @aahiliscoding, thank you for your proposal! We will circle back with an update soon.

**Comment by ErinOCon** [comment]
Hi @aahiliscoding, thank you for your patience as we complete this review. Can you point to the use of IPFS, Filecoin, or related tech in your code? Also, is there a link or video for your demo?

**Comment by ErinOCon** [comment]
Hi @aahiliscoding, I hope you are doing well! Do you have an update regarding the above inquiries? Please be in touch with any questions!

**Comment by ErinOCon** [comment]
Hi @aahiliscoding, do you have an update available? Please let me know if you have any questions for our team.

**Comment by ErinOCon** [comment]
Hi @aahiliscoding, thank you for your patience and for the additional information. This microgrant has been approved! We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
