### ISSUE TITLE
Next Step Microgrant: <IPFS_Medical_Certificates>

### ISSUE THREAD

**Issue by grego02** [filecoin-project/devgrants#986]
### 1. What is your project? 
The project consists of a site to upload and download medical certificates from IPFS. It can be used for medical institutions to allow doctors to issue certificates, e.g. absence from work,  in a safe way. Only doctors registered in the system can issue a certificate. Once the document is written, the doctor can upload it to IPFS. If the upload is successful, a CID appears on the screen, and the professional can give it to the patient. Finally, with that CID, the patient can view and download the certificate.

### 2. Project links
  
Link to Github repo: https://github.com/grego02/IPFS-Medical-Certificates
Link to demo or website, if applicable:
Does not apply

  
### 3. How is IPFS, Filecoin, or related technology used in this project? 
IPFS is used to share medical certificates between doctors and patients.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? 
Many improvements should be done to the current MVP to make it practical:
●	Currently, despite having the registration page, it doesn’t have an active code. The aforementioned functionality will be added using a smart contract, to verify that doctors are authorized to issue certificates.
●	The functionality to cancel a doctor’s registration in the system will also be in charge of a smart contract.
●	The functionality to manage the login, and to determine wether a user is a medical company, a doctor or a patient will be in charge of the mentioned smart contract. Currently the program has the role of the users as fixed values.
●	Improvements will be made in the UX.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?yes
Yes.
### 6. Does your proposal comply with our Community Code of Conduct?
Yes.

### 7. Links and submissions
Does not apply
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
* Gregorio Kominiarz - gregorio.kominiarz@gmail.com - https://github.com/grego02/ Full stack developer
* How did you learn about our microgrant program?
It was recommended to me by a friend.
* If your project was created as part of an event or hackathon:
 Does not apply

**Comment by ErinOCon** [comment]
Hi @grego02, thank you for your proposal! Before considering this project for a grant, we would like to see building progress a bit further. For next steps, I would recommend building out your prototype at a hackathon!
