### ISSUE TITLE
Green Grant RFP Application - Reneum 

### ISSUE THREAD

**Issue by briannawelsh** [filecoin-project/devgrants#987]
https://github.com/filecoin-project/devgrants/issues

# RFP Proposal: `Green Grant RFP Application: Reneum

**Reneum:**

**Link to RFP:** `https://github.com/filecoin-project/devgrants/blob/master/rfps/green-grants.md`

**RFP Category:** `technical-design`

**Proposer:** `briannawelsh`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT and APACHE2 licenses?:** `Yes`

# Project Description

Reneum is a Regenerative Finance (ReFi) platform to fund climate solutions via natural capital-backed tokens. Focusing initially on the energy transition, Reneum partners with green energy developers to vet, monitor and issue tokens they can sell on Reneum's marketplace, for a vertically-integrated and digitally-native, fully traceable, approach to Energy Attribute Certificates (EACs). Sustainability-focused companies and citizens desiring climate action buy the RENW token to be burnt in return for a collectable (soulbound) "verified green" NFT representing proof-of-impact. Similar to the globally recognizable LEED or Fair Trade label, Reneum’s verified green NFT will become the de facto label for the green economy, symbolizing both citizen and company climate action. HODLing the green NFT earns its owner entry into the climate community, allowing them rights to vote on future climate causes to fund, badges for contribution to the broader Reneum network, and rewards for IRL climate action.

Reneum selected the energy transition as its first cause because it recognizes that the shift out of fossil fuels and into a renewably-powered economy is the single most impactful (and straightforward) lever to pull for climate change. The biggest impediment to achieving it is actually stagnant capital. Crypto offers a unique and unprecedented tool to distribute capital efficiently, so we're using it to mobilize a wall of money to project developers to drive new investments. To materially impact the deployment of renewables, Reneum is offering not only a spot market, but futures and forwards, which will be the first of its kind in this market. This acts as a new vehicle to finance renewable energy to bypass legacy processes which have proven to be inefficient at appropriating capital. Also distinctively, Reneum expands the market from B2B to B2C as well, allowing citizens to participate in this market for the first time. Concerned citizens do not have a straightforward mechanism to direct climate action, especially in the energy transition, so Reneum helps everyone become part of the movement for #DirectClimateAction. The primary objective is to leverage our existing economic systems to more efficiently and transparently fund renewable energy developments.

## Development Roadmap

Milestone 1: Smart contract build-out for both the RENW token (fungible ERC 20) and the Verified Green token (ERC 721A). Metadata representing the underlying renewable energy project will be represented on the front-side of each NFT for buyers to identify their unique project and contribution. The smart contracts will be integrated with the back-end data aggregator to allow for the automated minting of the RENW tokens based on the production of clean MWhs of energy generated in real-time. V1 of the marketplace (MVP) will go live, enabling the purchasing of the verified green NFTs in closed environment for pre-selected buyers. A static demo of the marketplace is live now at ([www.reneum.com/marketplace](http://www.reneum.com/marketplace). The MVP will allow users to identity a specific project they wish to fund (or multiple projects if they have preferences), select from a list of criteria including: type of renewable technology, year of the project, geographic location, climate impact, and relationship to the United Nations Sustainable Development Goals (SDGs). They will then settle their purchase directly on the marketplace by checking out by connecting their crypto wallet of chioice, and will receive their airdropped verified green NFT (721A). The natural capital token, called the RENW (an ERC 20), will be burnt automatically from Reneum’s Treasury which will prohibit that token from being purchased twice (to avoid double counting).

Milestone 2: Purchasing on the marketplace will be enabled via MoonPay to allow for on-ramp services, ensuring that non-Web3 natives are included in the ecosystem. This also means that custodial services will be implemented at this time for those who opt out of self-custodying with their crypto.

Milestone 3: Full project audit details (from the initial vetting process) will be integrated with Filecoin’s IPFS IPLD DAG system to be permanently stored, acting as the public good database for environmental assets like Energy Attribution Certificates (EACs). This will allow for greater transparency and a trust-less solution for buyers who can conduct their own project audit without relying on Reneum as the intermediary verifier. 

## Documentation, Education, and Community

As renewable energy developers, climate project owners, and natural capital market leaders, our team is deeply embedded within the networks of legacy markets. This gives us an important perspective to support the Web3 Natural Capital space, which we observe is missing in many conversations right now. We can add value by providing the industry expertise necessary in the whole ReFi movement.

We also recognize how important it is for all Reneum’s stakeholders, and frankly, the entire market, to understand the nuances of environmental assets and natural capital. Reneum provides a distinct solution for funding renewable energy which is novel in the Web3 space, as well as in legacy markets, but we recognize that the market is still new to many so significant education and community support is required. We are already publishing research reports, thought pieces and market analyses on a regular basis (see our reneum.com/blog) but will also host AMAs and engage in community podcasts, plenaries and working groups to support the whole market advance.

## Other Deliverables

Reneum intends to collaborate as both a marketplace and as a token issuer for EACs with other market participants, particularly with FIlecoin Green’s IPFS launch, along with other on-chain carbon providers like Senken, and oracle/harware provider IOTA, for connecting renewable projects securely. The objective is to expand the market, enhancing access to these instruments by all renewable energy providers worldwide, not to compete with our peers. We see an opportunity to partner with on-chain carbon tokens to offer a one-stop-shop package for companies managing their ESG footprints (Scope 1, 2 & 3), so they can satisfy the Greenhouse Gas Protocol requirements for emissions management. 

## Milestone Summary

This table should summarize all of the efforts above. For each milestone, please describe:
- Summary of milestone
- How many people will be working on each milestone and their roles
- The amount of funding required for each milestone
- How much time this milestone will take to achieve (using real dates)

| Milestone No. | Milestone Summary & Staffing | Funding | Estimated Timeframe |
| ------------- | --------------------- | ------- | ------------------- |
| 1             | ERC20 & ERC721A build and deployed to mainnet including closed transactions    | $50,000     | 7.5 weeks  10/10/22 – 11/30/22           |
| 2             | On-ramp & custody integrations     | $50,000      | 4 weeks  12/1/22 – 12/31/22           |
| 3             | IPFS storage & live metadata     | $50,000      | 6 weeks    12/1/22 – 1/15/22         |

## $150,000

Sum up the total requested budget across all milestones.

## Maintenance and Upgrade Plans

We have a permanent team of developers including back-end architects and developers, front-end and UX / UI developers, and Solidity developers and blockchain economy and tokenomics designers. The team will be responsible for maintenance of the platform, and the community will be incentivized to contribute their support and ideas to further enhance the cohesion of the network. 

# Team

## Contact Info

Email - [Brianna.welsh@reneum.com](mailto:Brianna.welsh@reneum.com) 
Telegram - @briannawelsh

## Team Members

Brianna Welsh (Co-Founder & CEO) -  https://www.linkedin.com/in/briannawelsh/
Assaad Razzouk (Co-Founder) - https://www.linkedin.com/in/assaadrazzouk/
Harib Bahkshi (VP of Engineering) - https://www.linkedin.com/in/haribbakhshi/?originalSubdomain=uk
Oliver Muldoon (VP of Community) - https://www.linkedin.com/in/olivermuldoon
Mikhail Schemm (VP of Marketing) - https://www.linkedin.com/in/mikhail-schemm-b3aa5951/ 
Antonio Lopez (VP of Commercial) - https://www.linkedin.com/in/antoniomlopezrodriguez/ 

## Team Website

www.reneum.com

## Relevant Experience

Brianna and Assaad have been building Reneum since 2018 when Assaad identified a critical problem in the energy transition: that it was simply too slow. Identifying financial markets as the biggest lever in this effort, and recognizing decentralized ledger technologies as a novel tool to redirect capital, Reneum was born. In the years since, they have been stealthily building the ecosystem to power an entirely new market; a re-conception of value for global environmental markets.  
Reneum is an innovative market leader backed by renewable asset owners with a long history in environmental markets, operating a carbon trading business, advising on carbon abatement strategies, and earning and selling RECs on behalf of their own assets. This means Reneum inherits significant market knowledge from all sides of the value chain along with an extensive network and resources. This institutional knowledge combined with our long-term relationships, provide for a moat around the market IP that prevents newcomers from eclipsing us.

## Team code repositories

https://github.com/ankurdaharwal/

# Additional Information

**Comment by mjohnson518** [comment]
Hey @briannawelsh, thanks for submitting this proposal! Would you mind providing more information on Milestone 1? 

Since this portion of work demands 50% of the funding and >50% of the time, it would be good to learn more about what activities will occur during M1. 

Also, since you estimate M1 to take several weeks, it may make sense to break out the milestones into separate grant proposals. You could do this by using a M1 as your first grant proposal, and then submitting another grant proposal for M2 & M3 once you make measurable progress on M1. 

Looking forward to hearing back!

**Comment by briannawelsh** [comment]
Hey @mjohnson518 - thanks for the comment! A couple questions for you:

1. How long do you typically like to see milestones running for? These milestones presented are to reach an MVP, whereas reducing to only M1 will not result in a working product that our customers will be able to use (ie - our customers require on-ramps & custodial services as many are not Web3-native). 

2. Can milestones be referring to concomitant development or are they expected to be sequential? If the former, then we can break out M1 into multiple milestones, as the smart contracts programming / testing and underlying project metadata integration / file storing are built in tandem by different team members and are highly inter-related.

Will resubmit the milestones subject to your response here. Thank you :)

**Comment by orinayodele** [comment]
Hi @briannawelsh have you been able to work out the milestones above?

**Comment by briannawelsh** [comment]
Hi @orinayodele  - sorry for the delay; I replied to Marc with my questions above but didn't see a response from him. Did I miss it somewhere?

**Comment by briannawelsh** [comment]
Hi Orinayodele,

Thanks for the feedback, I replied on the GitHub but I didn’t see a response from Marc yet to my questions. For reference, I replied asking the following:

@Marc ***@***.***>:

  1.  How long do you typically like to see milestones running for? These milestones presented are to reach an MVP, whereas reducing to only M1 will not result in a working product that our customers will be able to use (ie - our customers require on-ramps & custodial services as many are not Web3-native).
  2.  Can milestones be referring to concomitant development or are they expected to be sequential? If the former, then we can break out M1 into multiple milestones, as the smart contracts programming / testing and underlying project metadata integration / file storing are built in tandem by different team members and are highly inter-related.
Will resubmit the milestones subject to your response here. Thank you :)


From: orinayodele ***@***.***>
Date: Tuesday, October 4, 2022 at 3:51 PM
To: filecoin-project/devgrants ***@***.***>
Cc: Brianna Welsh ***@***.***>, Mention ***@***.***>
Subject: Re: [filecoin-project/devgrants] Green Grant RFP Application - Reneum (Issue #987)

Hi @briannawelsh<https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbriannawelsh&data=05%7C01%7Cbrianna.welsh%40reneum.com%7Cd4c0aaecb35b41b1cf8108daa60f82d6%7Ca881e9d4788146338a12727a1a1af79e%7C0%7C0%7C638004882792058261%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PkjmEwGJDTp3vxBdKXbtKQ2RFxLUYF3Y6PVgNocV0rs%3D&reserved=0> have you been able to work out the milestones above?

**Comment by orinayodele** [comment]
@mjohnson518 please answer @briannawelsh questions above about milestones

**Comment by briannawelsh** [comment]
Hi All,

Thanks for following up, Brianna! I'll reply on Github asap!

Best,
Marc

**Comment by mjohnson518** [comment]
Hey @briannawelsh thanks for the questions and apologies for the delayed response!

We don't have specific timelines for milestones, but generally like to see milestone timeframes < 8 weeks. 

It's good to hear that you have resources to conduct these milestones concurrently, but I'd still like to see more details on what activities will occur during M1. 

ERC20 & ERC721A contracts are used regularly, so it shouldn't be a heavy technical lift, and there are multiple options to help seamlessly store the token metadata on Filecoin/IPFS. Some available options include: NFT.Storage, Web3.Storage, CO2.Storage, Piñata (pinning service), or host your own IPFS node. 

Are there other activities in M1 that you anticipate will take extra time/resources?

**Comment by briannawelsh** [comment]
Thanks Marc, noted on all, will update the GitHub accordingly.

From: Marc Johnson ***@***.***>
Date: Thursday, October 6, 2022 at 12:39 AM
To: filecoin-project/devgrants ***@***.***>
Cc: Brianna Welsh ***@***.***>, Mention ***@***.***>
Subject: Re: [filecoin-project/devgrants] Green Grant RFP Application - Reneum (Issue #987)

Hey @briannawelsh<https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbriannawelsh&data=05%7C01%7Cbrianna.welsh%40reneum.com%7C8151da096a1842b2c21408daa7227834%7Ca881e9d4788146338a12727a1a1af79e%7C0%7C0%7C638006063731226638%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6xJs2MwoNj3%2FiEnZoI%2BFwfz3FS1E8N7a%2BDW8FxkOUGo%3D&reserved=0> thanks for the questions and apologies for the delayed response!

We don't have specific timelines for milestones, but generally like to see milestone timeframes < 8 weeks.

It's good to hear that you have resources to conduct these milestones concurrently, but I'd still like to see more details on what activities will occur during M1.

ERC20 & ERC721A contracts are used regularly, so it shouldn't be a heavy technical lift, and there are multiple options to help seamlessly store the token metadata on Filecoin/IPFS. Some available options include: NFT.Storage, Web3.Storage, CO2.Storage, Piñata (pinning service), or host your own IPFS node.

Are there other activities in M1 that you anticipate will take extra time/resources?

**Comment by orinayodele** [comment]
Hi @briannawelsh thanks for the followup! we are finalizing some things this week and you should hear back from us by latest next week.

**Comment by briannawelsh** [comment]
Hi All, just wondering if there is any update on this? Let me know if you require any additional info from me. Thank you :)

**Comment by orinayodele** [comment]
Hi! Your grant has been approved and next steps will be communicated to you
shortly!

**Comment by briannawelsh** [comment]
Thank you 😊. Haven’t seen anything come through just yet though, any updates on your end?

From: orinayodele ***@***.***>
Date: Monday, October 31, 2022 at 10:23 AM
To: filecoin-project/devgrants ***@***.***>
Cc: Brianna Welsh ***@***.***>, Mention ***@***.***>
Subject: Re: [filecoin-project/devgrants] Green Grant RFP Application - Reneum (Issue #987)
Hi! Your grant has been approved and next steps will be communicated to you
shortly!

**Comment by orinayodele** [comment]
Hi @briannawelsh you should receive a contract by the end of next week!

**Comment by briannawelsh** [comment]
﻿Hey again - just following up on the next steps here when you can 😊

From: orinayodele ***@***.***>
Date: Friday, November 4, 2022 at 7:16 AM
To: filecoin-project/devgrants ***@***.***>
Cc: Brianna Welsh ***@***.***>, Mention ***@***.***>
Subject: Re: [filecoin-project/devgrants] Green Grant RFP Application - Reneum (Issue #987)

Hi @briannawelsh<https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbriannawelsh&data=05%7C01%7Cbrianna.welsh%40reneum.com%7Ca03d2e2c23804c0d967208dabe6f1cd9%7Ca881e9d4788146338a12727a1a1af79e%7C0%7C0%7C638031681673612977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rs%2FZACvYq8eIfhrPv1cufCwS9IkR%2F9%2BVZnaAXjFOQpk%3D&reserved=0> you should receive a contract by the end of next week!

**Comment by realChainLife** [comment]
Hi @briannawelsh we appreciate your patience with our approval process. We've sent you an email with detailed next steps.
