### ISSUE TITLE
Next Step Microgrant ： Web3Mail

### ISSUE THREAD

**Issue by kaitlinff** [filecoin-project/devgrants#989]
### 1. What is your project? (max 100 words)
Web3Mail is an email decentralized application. Committed to building an email communication platform in the web3 metaverse, we use web3's gmail as a benchmark, and strive to improve its functions and interactions. And use decentralization technology and on-chain encryption technology to provide a completely decentralized, self-controlled private email platform, ensuring the use of IPFS, etc. to achieve complete data decentralization

### 2. Project links
  
Link to Github repo:
https://github.com/kaitlinff/Web3Mail
Link to demo or website, if applicable:
https://web3-mail-jlpl.vercel.app/
License:MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  Web3Mail is an email service, which is a peer-to-peer exchange of email data. All its data such as text, email attachments, etc. are stored to the IPFS/Filecoin platform through nft.storage. In the later stage, we will access a variety of IPFS /Filecoin's sdk to meet the different needs of different users

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

We will use this funding to complete iterative upgrades in the following areas

1. Contract layer: We will improve the contract function, add a variety of different mail types, and provide more sending options, such as plain text, image-text combination, link, encryption, etc.
2. UI/UX interaction: We will integrate the web2 email platform to improve our overall interaction process, so that users can smoothly migrate from web2 to web3
3. Storage layer: Currently we provide unified nft.storage storage, and we will add a variety of official free storage solutions and self-configured storage nodes in the future

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  yes

### 6. Does your proposal comply with our Community Code of Conduct?

yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
   kaitlin, kaitlinffsil@gmail.com ,https://github.com/kaitlinff
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ysongh** [comment]
This person copy my codes from my project. https://github.com/ysongh/PolyWeb3Mail

The only thing this person change is my project name.

**Comment by ysongh** [comment]
This person has been creating multiple accounts and copying other people projects.

I just found out that this person copy my second project that this person submitted for other Microgrant. https://github.com/filecoin-project/devgrants/issues/826

**Comment by kaitlinff** [comment]
@ysongh . 

I would like to give reasons for this
1: Your code is based on the MIT agreement, which allows others to continue to develop on it
2: I'm very interested in the logic and direction of your code, but you seem to have discarded it
3: For the explanation of 2, I want to continue to develop in the direction you thought before, so I copied the code directly.

Technology is never the most important, and your code is still under the MIT license.
I would like to continue to improve the development of the mail project in this direction.
Of course, maybe your code is based on the MIT license, but you don't seem to want others to continue to extend the function on the code you have discarded.
It seems this is against the MIT license.

In the end, I still closed the project. I will write a new mail dapp . Of course it will borrow ideas from your project.

**Comment by ysongh** [comment]
@kaitlinff 

1) I did not stop you from developing on my project
2) I did not discarded my project. I plan on working and continuing on this project.
3) I only informing everyone that you copied my project

Your github was created recently and it looks questionable

**Comment by kaitlinff** [comment]
> @kaitlinff
> 
> 1. I did not stop you from developing on my project
> 2. I did not discarded my project. I plan on working and continuing on this project.
> 3. I only informing everyone that you copied my project
> 
> Your github was created recently and it looks questionable

lol, so wherever use your code you need to tell it to copy your code?
Hope you will continue to develop this mail app, and I will also develop a web3mail.

end this topic.

**Comment by kaitlin-beegle** [comment]
@kaitlinff love the Github handle! In fact, it looks identical to the one I use in Filecoin Slack!

**Comment by ErinOCon** [comment]
@kaitlinff, As you may already be aware (as this item is closed), this microgrant application does not meet our program qualifications. It is not under consideration for a grant.
