### ISSUE TITLE
Next Step Microgrant: writeUp

### ISSUE THREAD

**Issue by tech-writeup** [filecoin-project/devgrants#990]
### 1. What is your project? (max 100 words)

writeUp is an app which allow users to write private and public notes on Solana Blockchain using IPFS. A public note can be easily shared with a unique ID. The note can also be protected by a password so only the selected one can see it.

The flow of the application is as follows:

1. User connects their Phantom wallet with our DApp.
2. User gets to see all the notes saved by them (Saved using textiledb)
3. Notes fetched will be decrypted using the user’s encryption keypair.
4. Anything new written by the user will be stored on IPFS using web3 decentralized storage.

We have received a lot of interest from the Indian web3 Writer’s community to use this as their defacto application.

### 2. Project links
  
Link to Github repo: https://github.com/tech-writeup/app-writeUp
Link to demo or website, if applicable: https://pitch.com/public/667c5a8f-4e36-4e39-8ccf-7b5fef129352 (Live Demo at Solana Hacker House)

**License: MIT + APACHE2**

### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)

writeUp is powered by IPFS
Current use cases of IPFS for writeUp are as follows:

- We’ll store the user’s title and the notes on [web3.storage](https://web3.storage), and store the IPFS hashes that point to their content on the Solana blockchain.
- In order to keep track of the user's CID we use [Textile](https://docs.textile.io/buckets/)

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

- [ ] Textile Database Implementation
- [ ] Currently, we only support the Phantom wallet. We want to extend support to the other ecosystem applications.
- [ ] Implement Bulk Metadata Upload To IPFS
- [ ] Implement advanced transaction handling with interfaces for relayers and user-signed messages.
- [ ] Reach out to web3 writer communities and develop the product with the end-user in mind.
- [ ] Implement tags and note-taking widgets like Evernote
- [ ] Write native rust smart contracts instead of using [Neon EVM](https://neon-labs.org) - for performance gains.
- [ ] Developing a mobile app for writeUp

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes we will share grant reports.
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes, project is compliant.

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:

https://superteam.fun/bounties/build-a-filecoin-project-and-apply-for-the-microgrant
  
https://solana.com/events/new-delhi-hacker-house
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Name: Hardik Sharma -- Email: write.up.connect@gmail.com
GitHub Account: https://github.com/tech-writeup -- Role: Senior Dev

* How did you learn about our microgrant program?
At the [Solana New Delhi Hacker House](https://solana.com/events/new-delhi-hacker-house)
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  [Solana New Delhi Hacker House](https://solana.com/events/new-delhi-hacker-house)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @tech-writeup, thank you for your proposal! It looks like elements of your code align with [Jotter Dapp](https://github.com/filecoin-project/devgrants/issues/739). Can you point to the code in your project that is specific to your prototype?

**Comment by ErinOCon** [comment]
Hi @tech-writeup, I hope you are doing well! Do you have an update available regarding the above inquiry?

**Comment by tech-writeup** [comment]
Hi @ErinOCon, sorry for the delayed response. Yes! 'Jotter' has been an inspiration as a hackathon project and we have used Jotter's front-end code to build a Solana DApp, but there's a stark difference in how writeUp and Jotter functions.

Primarily, Jotter is an EVM DApp, and  EVM comes with its own pros and cons. We are using Solana as our primary chain on writeUp because Solana's gas is almost always cheaper than any EVM chain's. All transactions are sent to the Solana blockchain and the smart contract code for the same is open-sourced in the same repository.

I would like to add that we have also updated the UI to look more in line with what we are developing and will be further updating the same.

Please note that we have resumed working on this project after a quick break from traveling around Delhi, post the hacker house.

**Comment by ErinOCon** [comment]
Hi @tech-writeup, thank you for your response and for your patience! This microgrant has been approved. We will send an email to confirm payment details. 

Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!
