### ISSUE TITLE
Next Step Microgrant: Multichain NFT Visor v2 By:dfhcommunity.com

### ISSUE THREAD

**Issue by irwingtello** [filecoin-project/devgrants#991]
### 1. What is your project? (max 100 words)
A multichain visor that allows users to search for their nfts easily in different blockchains and without connecting their wallet.

In this version we will add these blockchains:
- Solana.
- Stellar.

And we improved the UX/UI.

### 2. Project links
Link to Github repo:
https://github.com/irwingtello/ionicMultichainVisor

Link to demo or website, if applicable:
App Store:
https://apps.apple.com/mx/app/nft-metadata-browser/id1638277846?l=en

Play Store:
https://play.google.com/store/apps/details?id=com.dfhcommunity.nftvisor

License: Attribution-NonCommercial 4.0 International (CC BY-NC 4.0).

Clauses: 
1.- For anyone using the code, the [dfhcommunity.com](url) logo and website must be clearly displayed on the application/website where the code is used.
2.- If you decide to use a multichain visor feature for your app, it should remain free and open source.
3.- It is allowed to use the features of the multichain visor for other projects to be integrated and commercialized, the commercialization/publish to Play Store/App Store another apps store of the original concept is not allowed (because Play Store and App Store have different restrictions).

Why the conditions of this license?
1.- We realized the app stores (Play Store /App Store)  have requirements that are complex, fortunately we overcame these barriers and we have a working demo of the multichain visor v1.
2.- Greater user adoption of web3 is needed and pricing these features would limit that adoption. There are people who have low incomes and we are aware of them, that's why this initiative to always keep it free.

Because it is a public good and we encourage inclusive adoption for different people 😇 . 
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
The nfts we read are stored in IPFS, along with their metadata 😀.
We found a way to save them offline without having to be connected to the internet.

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
We are dedicated to open source, [dfhcommunity.com](url) is dedicated to serve to provide solutions for web3 adoption and this tool has been very well used and we receive feedback from different communities and new web3 users.

That is why we will implement them in this version and this grant supports the task of continuing to incubate web3 developers in Latin America.

Testimonials:
Luis Garza:
https://twitter.com/irwingtello/status/1567587190590275585

Samuel Polino:
https://twitter.com/irwingtello/status/1570929991306866689

Our students get involved and learn in real projects, mentored by senior developers.

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes 😀
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes 😀

### 7. Links and submissions
We born at NFT Hack 2022 by ETH Global as dfhcommunity.com.
https://www.dfhcommunity.com/story

### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.

Founder:
Irwing Tello
Experience:+5 yoe, JS, React, Solidity.
Experience in different communities teaching about web3. 
Role: Team Leader

Samuel Polino:
Full Stack Web3 Learner.

Luis Garza:
Full Stack Web3 Learner.

* How did you learn about our microgrant program?
We born thanks to one microgrant after NFTHack2022 by ETHGlobal 😃.

**Comment by ErinOCon** [comment]
Hi @irwingtello, thank you for your patience with our review. We will not be moving forward with a grant at this time. Please feel welcome to re-apply if/when your project further incorporates IPFS, Filecoin, or other closely related tech.
