### ISSUE TITLE
Next Step Microgrant : DVideoRecording

### ISSUE THREAD

**Issue by tangblock2022** [filecoin-project/devgrants#993]
### 1. What is your project? (max 100 words)
Video Recording is a platform to record videos as NFTs on the blockchain. "Screen Recorder" allows you to record videos of any app or browser tab and store to the decentralized network of IPFS/Filecoin, you can Completely control your own video data and make NFTs to bring value to your own videos

### 2. Project links
  
Link to Github repo:
https://github.com/tangblock2022/VideoRecording
Link to demo or website, if applicable:
https://nft-video-recording.netlify.app/
License:MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  Our goal is to build a mature and reliable video platform, users upload videos, and all data of video clips are stored through IPFS/Filecoin
![image](https://user-images.githubusercontent.com/113814634/190885817-6a68a746-13c4-4edd-aaad-396081ba64ad.png)

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

1. Refactoring the data storage layer : Provide data storage factory, allow users to choose storage nodes by themselves, connect with large miner nodes, and provide real data storage
2. Optimize the video NFT function, increase the purchase in currencies such as Fil, usdc, and appreciate the function
3. Optimize the overall website to make it marketable so that the market can accept video products based on IPFS/Filecoin

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  yes

### 6. Does your proposal comply with our Community Code of Conduct?

yes
### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  tangblock, tangblock@163.com , https://github.com/tangblock2022
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @tangblock2022, we will not be moving forward with a grant for this project at this time. Thank you for your proposal.
