### ISSUE TITLE
Next Step Microgrant : DVideo

### ISSUE THREAD

**Issue by qasertya** [filecoin-project/devgrants#995]
### 1. What is your project? (max 100 words)
Dvideo is committed to building a web3 video sharing platform, helping web3 content bloggers to share their web3 technical videos, learning videos, operation videos and any related videos on the platform, and supports casting their own video content into NFT, users can Purchase related video qualifications (for downloading and learning) or appreciate and LIKE your favorite video content.
All user data will be stored in the IPFS/Filecoin network . Users can configure their own IPFS/Filecoin nodes or api tokens to control these video content by themselves

### 2. Project links
  
Link to Github repo:
https://github.com/qasertya/DVideo
Link to demo or website, if applicable:
License:MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
All video content of our current video sharing platform will be stored in the IPFS/Filecoin network through the IPFS api.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

When trying to decentralize the data content, we use the http api of ipfs. When we receive the funding, we will use this funding to complete our architecture modification. We will support users to log in to web3 wallet and pass DID. To complete the user's decentralized identity authentication, and then the user's configuration and other operations will be completed through DID, we will modify the architecture to support two modes, one is free storage, and the data will be stored to the project side through web3.storage The applied IPFS/Filecoin storage space, the second is that users configure the token of web3.storage through DID to use their own web3.storage space. At the same time, we will learn excellent video platforms such as tiktok to improve our overall operation and interaction . 
We will use the remaining funds at the end to attract excellent content bloggers to bring more real video data to IPFS/Filecoin

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  yes

### 6. Does your proposal comply with our Community Code of Conduct?

  yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
   Qaser, qasertya@gmail.com , https://github.com/qasertya
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @qasertya, we will not be moving forward with a grant for this project at this time. Thank you for your proposal.
