### ISSUE TITLE
EventOnChain

### ISSUE THREAD

**Issue by mbcse** [filecoin-project/devgrants#996]
### 1. What is your project? (max 100 words)
The platform is the first multi-chain event management and ticketing platform on blockchain. This is not ordinary event platform, this platform comes up with event analytics, burn functionality and onchain data governance features. A user can come on platform and login with email or with his/her wallet. If he logins with only email and otp then we create a a multichain account for him. Then user can create events, mint ticket nfts , organizer can checkin user and user can burn tickets to get the value and buy new tickets with it. All the tickets have some value and they can showcase it to the world. There are many other feature like stripe and crypto wallet payment system. The amount of ticket is sent to smart contract and can be withdrawn only after event is ended. The organiser can choose blockchain of his/her choice for nft's. The data and event analytics details are stored on decentralised storage network ipfs. Currently pinata is used but probably we be shifting to lighthouse and filecoin for better management and data handling with access control

### 2. Project links
 
Link to Github repo: https://github.com/mbcse/ETHCC-Hack
Link to demo or website:
Demo: https://www.youtube.com/watch?v=ZqqdkH9bzcg
Website: http://eventonchain2.herokuapp.com/
Licence: MIT
  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
IPFS is used to store user centric and nft data. We are building analytics dashboard for events, all that analytics data will be stored in ipfs based database. This is to reduce data storage cost of platform and provide more decentralisation.
  
### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)
- Need to improve UI of platform, need to hire designers
- Need more developers to build this project into big one
- Will be adding cross chain NFT capabilities into the platform
- Adding funds management and allocation system
- Going live in next 1-2 Months

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?
Yes
  
### 6. Does your proposal comply with our Community Code of Conduct?
Yes

### 7. Links and submissions
Yes, Winner, Polygon: Best NFT Project, https://devpost.com/software/eventonchain-y43ul0 
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
Mohit Bhat, mbcse50@gmail.com, mbcse, Founder and Developer
* How did you learn about our microgrant program?
Email from filecoin
* If your project was created as part of an event or hackathon:
 [EthCC Hack 2022](https://ethcchack2022.devpost.com/)
  * Please link to your hackathon submission
   https://devpost.com/software/eventonchain-y43ul0

**Comment by mbcse** [comment]
Hey @ErinOCon , 
I will be working on improving UI of the platform, for this I am hiring a designer(As I am not a great designer) to develop cool wire-frames of the project. My aim is to make nft tickets look appealing. For cross chain capabilities currently I have different smart contracts on each chain deployed for minting tickets. I will be making my own bridge to allow users to burn and shift tickets to different chain. Also an event will not be limited to a single chain or a single contract but to multiple ones. They can choose which chain to mint ticket based on gas price.

For Fund management currently all money goes to contract. I will be separating this as I will be building a separate eventFund contract which will have functionalities to receive and distribute funds and also in case of issues in events refunds, cashbacks, etc can be processed. The fund management will be of two types - For new organisers funds will be given at the end of event completion (Rules are being defined) and  for approved/checked organisers funds will be distributed in 25-50-25 % flow, which will be automatic through contracts after deducting platform and other fee, etc .

**Comment by ErinOCon** [comment]
Hi @mbcse, thank you for your patience with our review. This grant has been approved! Look out for an email to confirm payment details!

**Comment by ErinOCon** [comment]
Please note that your final grant report is due within three months and can be submitted [here](https://airtable.com/shrrtSlgdVvrPmAvr). Please let us know if you have any questions!

**Comment by ErinOCon** [comment]
Hi @mbcse, I hope you are doing well! Can you provide a final report for this project [here](https://airtable.com/shrrtSlgdVvrPmAvr)? Please let us know if you have any questions!
