### ISSUE TITLE
Next Step Microgrant : IPFSWebExtension

### ISSUE THREAD

**Issue by fyuter** [filecoin-project/devgrants#997]
### 1. What is your project? (max 100 words)
Store all your data in IPFS/Filecoin and enjoy the fun of decentralization
Have you ever needed to quickly upload something to IPFS/Filecoin , e.g. some token metadata while minting an NFT, or maybe something as simple as posting an image on a forum that does not have an upload functionality?
Well, here is the IPFS Browser extension . Compatible with Chrome, Firefox, Edge and Brave, this extension allows you to upload anything on IPFS/Filecoin in just 1 click. Click upload, choose a file and you get an IPFS/Filecoin address with the CID of your file. You also get an HTTP address using the Infura gateway so your file is just ready to use. Copy the link, paste it anywhere, it just works!

### 2. Project links
  
Link to Github repo:
https://github.com/fyuter/IPFSWebExtension
Link to demo or website, if applicable:
License:MIT

  
### 3. How is IPFS, Filecoin, or related technology used in this project? (max 100 words)
  This plugin itself is to allow users to quickly store data to IPFS/Filecoin when browsing the web, so our core is to use IPFS/Filecoin functions to store user data

### 4. How will you improve your project with this grant? What steps will you take to meet this objective? (max 200 words)

As an IPFS/Filecoin plugin, we are committed to building a plugin-based IPFS/Filecoin user space, and we will mainly accomplish the following things through this funding

1. Build a user space and complete a decentralized indexing system for user data by introducing DID
2. Increase the use of sdk corresponding to different functions (web3.storage is used to store data, and nft.storage is used to store data that requires Mint nft)
3. Refactor the plug-in interaction design and hire professional designers to provide the most optimized interaction for the plug-in
4. Add the function of importing and exporting file index, so that the user's file data can be synchronized on different devices and different apps

### 5. Do you agree to share grant reports upon request, including a final grant report at the end of the three month period?

  yes

### 6. Does your proposal comply with our Community Code of Conduct?

  yes

### 7. Links and submissions
* If your project began at a hackathon, have you submitted it for the relevant Protocol Labs prizes? Include links here if available:
  
### Additional questions:
* For each team member(s), please list name, email, Github account, and role in the project.
  Alexandra ， fyuterxd@gmail.com ，https://github.com/fyuter
* How did you learn about our microgrant program?
* If your project was created as part of an event or hackathon:
  * What was the name of the event? (e.g. ETHGlobal NFTHack, Cal Hacks hello:world, Chainlink, CivHacks, GameDevJ, ETHGlobal Scaling Ethereum)
  * Please link to your hackathon submission

**Comment by ErinOCon** [comment]
Hi @fyuter, we will not be moving forward with a grant for this project at this time. Thank you for your proposal.
