### ISSUE TITLE
LedgerMail integration with Filecoin

### ISSUE THREAD

**Issue by 0xsuraj** [filecoin-project/devgrants#998]
# Open Grant Proposal: LedgerMail Integration with Filecoin

**Name of Project: LedgerMail - The world's first Decentralized Email Service**

**Proposal Category:** integration-adoption

**Proposer:** 0xsuraj

**(Optional) Technical Sponsor:** `Mr. Piyush Maheshwari`

**Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?:** "Yes" 

# Project Description
Let's consider this partnership as if Google Drive is to Gmail, OneDrive is to Outlook, and in a same way Filecoin will be to LedgerMail.
LedgerMail is the world's first Decentralized Email Service which replaces the traditional email transfer protocols having centralized governance, cumbersome infrastructure and inadequate security measures with a disruptive Blockchain technology. LedgerMail inherits all the features of Blockchain Technology to emerge as an immutable, censorship-resistant, tamper-proof and democratic governance of user data.
LedgerMail provides the military-grade security, cryptographic encryption, utmost level of user privacy and self-sovereignty in a decentralized way.
LedgerMail platform is currently used by 740K+ users with half-a-million active wallets having exchanged 2 million plus transactions. LedgerMail is also used by leading enterprises and SMEs across the globe.

## Value
LedgerMail platform has successfully integrated with Chainsafe powered by Filecoin to enable users to store their files & attachments in a decentralized way. Few of the core value propositions are:

1. Increased User Adoption: Simplifying the user on-boarding process to Filecoin Network through a simplistic process and real-world application of secure digital assets transfer, starting with decentralized email service.

2. Storage Drive: Each user logging in or signing up to LedgerMail will have a fixed storage allocation from Filecoin powered Chainsafe which can be used for storing & sharing emails, files, data, attachments etc.  

3. Real-world utility: As Blockchain data is immutable which cannot be tampered or deleted, the storage utilization of Filecoin through LedgerMail will keep increasing, allowing Filecoin node operators to get rewarded for managing these operations.   

4. Interconnectivity: As outlined in Project Phase 2, we are planning to enable custom usernames (johndoe@filecoin) to represent uniform community of Filecoin, while allowing them to interconnect & interact with each other through our communication platform. (If we manage to partner with DNS providers to enable .FIL NFT domains for Filecoin users, we will enable the same through LedgerMail)  

5. Personalized User Experience: As outlined in Project Phase 2 below, we are customizing the LedgerMail application with a customized Filecoin theme to enable hyper-personalized user experience to Filecoin community.   

6. Interoperability: Filecoin users can seamlessly communicate with users signed up through different blockchain networks using an interoperable cross-chain bridge.   

7. $FIL Transfer: The interconnected community of Filecoin can use human-readable wallet IDs (johndoe@fil) to transfer $FIL tokens to each other without getting into any technical complexities.

## Deliverables
1. Custom Filecoin Usernames: LedgerMail will allow Filecoin community users to have a specific usernames representing Filecoin ecosystem. For example, users will have an option to Sign Up to LedgerMail by entering custom Filecoin usernames such as johndoe@fil, alice@fil, bob@fil etc.
2. Custom UI for Filecoin users: Once the user logs in to LedgerMail with a custom Filecoin username, there will be a toggle option for switching between LedgerMail UI and Filecoin UI. This custom Filecoin UI will be designed referring to branding & marketing theme of Filecoin. 

## Development Roadmap

Milestone 1: Creating customized human-readable wallet IDs for Filecoin (johndoe@fil) operating on XDC Blockchain Platform
    Sub Tasks:
         i. Creating a Filecoin username module on XDC Network
        ii. Creating search, select and suggestions module for usernames
       iii. Creating non-custodial wallets for Filecoin specific users
       iv. Enabling wallet to wallet transactions for sharing emails, files & attachments
       v. Enabling Log in module for Filecoin specific usernames
       vi. Digital Asset exchange between Filecoin usernames and other users of LedgerMail

Milestone 2: Creating customized UI for users signing up with Filecoin username
    Sub Tasks:
         i. Design of Filecoin theme
        ii. Enabling toggle button for switching between Filecoin & LedgerMail theme

Project Estimates Phase 2:

Total Working Days          : 15
Contingency                     : 10% 
Total Cost                         : $30000 USD

## Total Budget Requested

Total Cost : $30000 USD

## Maintenance and Upgrade Plans

LedgerMail team will completely own the responsibilities of ongoing support, maintenance, enhancements and upgrade plans of this integration.

# Team

## Team Members

Dr. Vinay Krishna - Founder, CEO.
Vinay is having 25+ years of extensive experience working as a Software Developer, Technical Lead, Blockchain Architect and Agile Coach. Vinay has successfully led a Blockchain Development firm which has grown to 45+ employees in last 3+ years.
LinkedIn: https://www.linkedin.com/in/vinaykrishna/
 
Mr. Suraj Mulla, Vice President of Sales & Marketing
Suraj is having 9+ years of experience working in the Software Sales & Marketing industry with last 3+ years working exclusively in the Web 3.0 industry. Suraj has helped several startups to channelize their business strategic through Strategic Partnerships, Marketing, Investor Relations and Business Development.
LinkedIn: https://www.linkedin.com/in/surajmulla/
 
Mr. Sujit Varghese, General Manager
Sujit is having 20+ years of experience in the Software industry specifically in the HealthCare industry where he has led initiatives around data security. Sujit has worked as CEO for one of the leading UAE based HealthCare company recently and has joined LedgerFi to expand our business operations in GCC.
LinkedIn: https://www.linkedin.com/in/sujit-varghese/
 
Mr. Santhosh Thomas, Lead Blockchain Architect
Santhosh is having 15+ years of experience as a Software Architect with previous experience working with IBM as Blockchain Architect.
LinkedIn: https://www.linkedin.com/in/santhoshkthomas/
 
Ms. Puja Kumari, Chief People Officer
Mr. Tibin Thomas, Senior Blockchain Developer
Mr. Ajay Kumar, Full Stack Developer
Mr. Naganath Bhat, Full Stack Developer
Mr. Anis Mangure, Digital Marketing Executive
Mr. Sanmeet Bamane, UI/UX Designer

## Team Website

https://ledgermail.io

## Relevant Experience
Our team has successfully built this production grade and enterprise ready application entitling it as the world's first Decentralized Email Service. We have successfully completed the Phase 1 of enabling Decentralized Storage option with Filecoin. We have prior experience building novice Web3 solutions, decentralized applications and a team of blockchain developers to enhance the product capabilities..

# Additional Information
We learn about the Open Grants Program from a Protocol Labs employee after reaching out through a social media platform for enabling Filecoin as a storage option for our email service.
Email ID: [suraj@ledgerfi.io](mailto:suraj@ledgerfi.io)

We are here not only to use Filecoin as a decentralized storage but to enable Filecoin community to have interconnected, interactive & interoperable platform for transferring their digital assets. We are enabling each of our 750K+ users to use Filecoin as their Decentralized Storage provider and we are hoping to serve millions of users through our strategic partners and enterprise customers.

**Comment by ErinOCon** [comment]
Hi @0xsuraj, thank you for the updated submission! I have sent an email to discuss next steps!
